### ISSUE TITLE
Support tags for aws_db_snapshot data source

### ISSUE THREAD

**Issue by dkniffin** [hashicorp/terraform-provider-aws#10010]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, the [aws_db_snapshot data source](https://www.terraform.io/docs/providers/aws/d/db_snapshot.html) only supports finding snapshots by their id or their associated database id. 

These options will not work for the use-case I have. Multiple DB snapshots are created outside of my terraform config, all with a standard naming convention and set of tags. I would like to reference the latest of those.

To do that, I would like to filter based on tags (similar to the usage in [aws_ami](https://www.terraform.io/docs/providers/aws/d/ami.html)). Alternatively, my problem could also be solved by allowing for wildcards in the snapshot identifier.

### New or Affected Resource(s)

* aws_db_snapshot

### Potential Terraform Configuration

Here's an example of what this could look like in practice:
```hcl
data "aws_db_snapshot" "latest_snapshot" {
  most_recent = true

  filter {
    name   = "name"
    values = ["postgres-backup-*"]
  }
}
```

### References

* A similar request for `aws_db_instance` is #2988

**Comment by okgolove** [comment]
Is anyone here? :)

**Comment by hemzet** [comment]
Especially when hex values are automatically added to db snapshot identifiers, as done in the TF RDS modules, the actual name of a snapshot is unknown so any data resource request fails. The tag filter extension is highly needed.

**Comment by blevkovych** [comment]
*bump*

**Comment by kairu97** [comment]
Is there an update on this? I would love to have tags for the db snapshot identifier.

**Comment by rromic** [comment]
Hey guys, I have open two PRs for filtering DB snapshots by tags #31600 (db snapshots) and #31602 (cluster db snapshots - aurora). If you have any suggestion or possible improvements, please write them down :).
