### ISSUE TITLE
Tech debt: r/aws_cloudformation_stack: Use new 'waitForCloudFormationStackXXX' functions

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#10034]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

https://github.com/terraform-providers/terraform-provider-aws/pull/7342 added new functions to consistently check that a CloudFormation Stack reaches a desired state.
These functions can now be used in the `aws_cloudformation_stack` resource code:

* `waitForCloudFormationStackCreation` in `resourceAwsCloudFormationStackCreate`
* `waitForCloudFormationStackDeletion` in `resourceAwsCloudFormationStackDelete`

and additionally for `resourceAwsCloudFormationStackUpdate`.

### New or Affected Resource(s)

* `aws_cloudformation_stack`

### Potential Terraform Configuration

```hcl
n/a
```

**Comment by ewbankkit** [comment]
Can now refactor to separate `waiters` package: #12840.

**Comment by bflad** [comment]
I believe this may have been covered by recent changes here? https://github.com/hashicorp/terraform-provider-aws/pull/15989

**Comment by ewbankkit** [comment]
Yes, #15989 addressed this.
