### ISSUE TITLE
EC2 API request failures don't retry quickly enough

### ISSUE THREAD

**Issue by mattburgess** [hashicorp/terraform-provider-aws#10037]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.11.14
+ provider.aws v2.23.0
+ provider.template v2.1.2
```

### Affected Resource(s)

Anything that requires hitting an EC2 API endpoint appears to be affected, but it's particularly prevelant on `DescribeSecurityGroups`, `DescribePrefixLists` and `DescribeRouteTables` calls.

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

```
2019/09/06/ 23:15:56 DEBUG: Send Request ec2/DescribeSecurityGroups failed, will retry, error RequestError: send request failed
caused by: Post https://ec2.eu-west-2.amazonaws.com/: EOF
2019/09/06 23:19:13 DEBUG: Retrying Request ec2/DescribeSecurityGroups, attempt 1
2019/09/06 23:19:13 DEBUG: Request ec2/DescribeSecurityGroups Details:
```

Although elided, the request details show that the request body is identical, down to the size as shown by the `Content-Length` header, between failing and succeeding calls.

### Panic Output

Thankfully, Terraform doesn't crash; it does retry the API request but after far too long a retry interval.

### Expected Behavior

The failed request should be retried after a few seconds.  Ideally, that retry interval would be configurable but I'd be happy if the default/hard-coded timeout were dropped to a low number of seconds.

### Actual Behavior

The failed request is correctly retried, and invariably succeeds on the 2nd attempt.  However, it appears to be retried after about 3 minutes.  Depending on the number of resources and timing of the calls, this can cause Terraform to take around 10 minutes to refresh state.

### Steps to Reproduce

This is pretty hard to reproduce; it's intermittent in our environment but becoming more and more common as we deploy more resources that sit behind the EC2 API endpoint.

1. `terraform apply`

### Important Factoids

- Our CI pipeline is run from outside of AWS, and all requests go through a Squid proxy to reach the Internet. The proxy isn't showing any errors, and given the intermittent nature of this, and the fact that all other API calls succeed, I'm not convinced it's a problem with our Squid configuration.
- All of our resources are in eu-west-2 (London) in case the region is pertinent to the relatively high rates of API request failures.

### References

* https://github.com/aws/aws-sdk-go/issues/1332 looks particularly pertinent and suggests the high request failure rate may be region specific

**Comment by justinretzolk** [comment]
Hey @mattburgess :wave: Thank you for taking the time to file this issue! Given that there's been a number of AWS provider releases since this was initially filed, can you confirm whether you're still experiencing this behavior?

**Comment by mattburgess** [comment]
Wow, this is an old one! No, if I recall correctly this actually disappeared a few weeks after reporting.
