### ISSUE TITLE
Get latest version number of data source aws_lambda_function

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#10038]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To associate a lambda function to CloudFront distribution as a Lambda@Edge (using a cache behiavor's lambda_function_association block), it is required to provide a [__numbered version__](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-requirements-limits.html#lambda-requirements-cloudfront-triggers). The qualifier `$LATEST` will (unfortunately) not work.

At the moment, that data source allow to pass a `qualifier` as an argument, but its `qualified_arn` attribute will reference that exact same qualifier, not necessarily a version number, unless the attribute itself is a version number, but that requires that version number to be known.

From what I understand, the AWS SDK does not provide a built-in function to get the last published version directly, but as a workaround, it can be retrieved using the pagination API, such as shown in the resource aws_lambda_function:
https://github.com/terraform-providers/terraform-provider-aws/blob/v2.27.0/aws/resource_aws_lambda_function.go#L583

### New or Affected Resource(s)

* data-source [aws_lambda_function](https://www.terraform.io/docs/providers/aws/d/lambda_function.html)

Proposal: add new attributes to the data source `aws_lambda_function` to access the latest numbered version (and/or even better: the fully qualified latest numbered version?)

- latest_version_number (the actual version number only)
- latest_version_qualified_arn (the fully qualified latest numbered version of the function)

(better names can probably be found)

### Potential Terraform Configuration

This is an example how what would be possible with such a feature:

```hcl
data "aws_lambda_function" "example_lambda" {
  function_name = "example"
  qualifier     = "$LATEST"
}

resource "aws_cloudfront_distribution" "example_distribution" {
  # ...

  default_cache_behavior {
    # ...

    lambda_function_association {
      event_type   = "viewer-request"
      # The following ARN MUST BE a numbered version
      # Option 1: format the ARN manually
      lambda_arn   = format("%s:%s", data.aws_lambda_function.example_lambda.arn, data.aws_lambda_function.example_lambda.latest_version_number)
      # Option 2: use a fully qualified ARN if provided
      lambda_arn   = data.aws_lambda_function.example_lambda.latest_version_qualified_arn
    }
  }
}
```

### References

* https://github.com/terraform-providers/terraform-provider-aws/issues/8782 (I initially posted a comment on that issue)
* https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-requirements-limits.html

If the change can be resumed to something as simple as copy-pasting the behavior of the resource to the data source, I would be more than happy to create a PR for it myself.

I would like to get some feedback on the proposal before starting, though.

And since I have never written a single line of Go code in my life before, I would need some guidance regarding contribution and especially testing, if that is possible?

**Comment by flosch-hb** [comment]
(Hello, I am deleting this account in favour of @flo-sch, will keep watching it from there.)

@ddriddle I saw that your PR has been merged, is that a workaround that can already be used?

**Comment by ddriddle** [comment]
@flo-sch Yes, setting an alias called latest in Terraform code works fine as a workaround for CloudFront.

**Comment by brucedvgw** [comment]
Has there been any progress on the data resource for this? I'm keen not to hardcode the version number if I can help it.

**Comment by nkoterba** [comment]
This seems related to: https://github.com/terraform-providers/terraform-provider-aws/issues/11787. 

I attempted the suggest workarounds in https://github.com/terraform-providers/terraform-provider-aws/issues/8782 but none of them seem to work since I can't control the lambda and do not publish it.

Has anybody found a workaround if you're **not** publishing the lambda using `data` either on `aws_lambda_alias` or `aws_lambda_function`?

**Comment by Hasgaroth** [comment]
I could really do with a fix for this issue too, although as I do publish the Lambda functions via another Terraform run, I am able to extract the latest version number that was deployed by Terraform using the following code.

```
data "terraform_remote_state" "lambda" {
  backend = "s3"

  config = {
    encrypt  = true
    bucket   = "terraform-state"
    key      = "${local.vpc_tags["Account"]}/compute/lambda/global.tfstate"
    region   = "eu-west-2"
    role_arn = "arn:aws:iam::123456789012:role/terraform"
  }
}

data "aws_lambda_function" "cloudfront" {
  provider      = aws.cf_cert_region
  for_each      = var.cf_lambda_functions
  function_name = lookup(each.value, "function", null)
  qualifier     = data.terraform_remote_state.lambda.outputs.lambda_details[each.key].version
}
```

I hope this helps someone until this fix gets landed.

**Comment by pzanuto** [comment]
> I could really do with a fix for this issue too, although as I do publish the Lambda functions via another Terraform run, I am able to extract the latest version number that was deployed by Terraform using the following code (edited to remove some specifics).
> 
> ```
> data "terraform_remote_state" "lambda" {
>   backend = "s3"
> 
>   config = {
>     encrypt  = true
>     bucket   = "terraform-state"
>     key      = "${local.vpc_tags["Account"]}/compute/lambda/global.tfstate"
>     region   = "eu-west-2"
>     role_arn = "arn:aws:iam::123456789012:role/terraform"
>   }
> }
> 
> data "aws_lambda_function" "cloudfront" {
>   provider      = aws.cf_cert_region      # us-east-1
>   function_name = "function_name"
>   qualifier     = data.terraform_remote_state.lambda.outputs.lambda_details["function_name"].version
> }
> ```
> 
> I hope this helps someone until this fix gets landed.

thank you! works fine...
we just have to include an output after the lambda resource is created

**Comment by BertrandMarechal** [comment]
I arrived here by looking for how to set up this with a resource, not data.
Here is what I found if someone else follows this path too

```
resource "aws_lambda_function" "example_lambda" {
  # ...
  publish          = true // This is an important part, it publishes the lambda and creates a version
}

resource "aws_cloudfront_distribution" "example_distribution" {
  # ...

  default_cache_behavior {
    # ...

    lambda_function_association {
      event_type   = "viewer-request"
      # The following ARN MUST BE a numbered version
      lambda_arn   = "${aws_lambda_function.example_lambda.arn}:${aws_lambda_function.example_lambda.version}"
    }
  }
}
```

That works like a charm.

**Comment by WojciechCichy** [comment]
My workaround:

One terraform:
```
resource "aws_lambda_alias" "basic-auth" {
    provider = aws.us-east-1
    name = "latest"
    function_name = aws_lambda_function.basic-auth.arn
    function_version = aws_lambda_function.basic-auth.version
}
```


Completely different terraform/different state in the same infra:
```
data "aws_lambda_alias" "basic-auth" {
  provider = aws.us-east-1
  function_name = "basic-auth"
  name          = "latest"
}

data "aws_lambda_function" "basic-auth" {
  provider = aws.us-east-1
  function_name = "basic-auth"
  qualifier = data.aws_lambda_alias.basic-auth.function_version
}
```

Works like a charm...

**Comment by flo-sch** [comment]
I guess those workaround only work when publishing the lambda with Terraform though?

I might have missed to mention that, but in my initial use-case, Lambda functions were published by something else (serverless framework), hence the proposal for a new `data` that could look up the latest version, no matter what was used to deploy it

**Comment by WojciechCichy** [comment]
The deployment method has nothing to do with it. You can even clickops it, then use terraform `data` to read what has been there.

**Comment by flo-sch** [comment]
Oh nice, I missed that, then that sounds like a decent workaround indeed!

**Comment by tymik** [comment]
> My workaround:
> 
> One terraform:
> 
> ```
> resource "aws_lambda_alias" "basic-auth" {
>     provider = aws.us-east-1
>     name = "latest"
>     function_name = aws_lambda_function.basic-auth.arn
>     function_version = aws_lambda_function.basic-auth.version
> }
> ```
> 
> Completely different terraform/different state in the same infra:
> 
> ```
> data "aws_lambda_alias" "basic-auth" {
>   provider = aws.us-east-1
>   function_name = "basic-auth"
>   name          = "latest"
> }
> 
> data "aws_lambda_function" "basic-auth" {
>   provider = aws.us-east-1
>   function_name = "basic-auth"
>   qualifier = data.aws_lambda_alias.basic-auth.function_version
> }
> ```
> 
> Works like a charm...

This is perfect! Easiest solution to implement for this case!

**Comment by Eagleman7** [comment]
@Woitekku I cannot figure out how to do it with an existing Lambda being deployed outside of TF:



```
resource "aws_lambda_alias" "lambda-acc" {
  provider         = aws.us-east-1
  name             = "latest"
  function_name    = data.aws_lambda_function.lambda-acc.arn
  function_version = data.aws_lambda_function.lambda-acc.version
}


data "aws_lambda_alias" "lambda-acc" {
  provider      = aws.us-east-1
  function_name = "lambda-acc"
  name          = "latest"
}

data "aws_lambda_function" "lambda-acc" {
  provider      = aws.us-east-1
  function_name = "lambda-acc"
  qualifier     = data.aws_lambda_alias.lambda-acc.function_version
}
```


```
    lambda_function_association = {
      origin-request = {
        lambda_arn   =  data.aws_lambda_function.lambda-acc.qualified_arn
        include_body = "false"
      }
```

**Comment by sriniavgs** [comment]
@tymik  @Woitekku I tried the same steps, but the qualifier still points to one version older

data "aws_lambda_alias" "current" {
  function_name = module.lambda_function.function_name
  name          = "current"
}

resource "aws_lambda_provisioned_concurrency_config" "lambda_warming" {
  count                             = var.provision_concurrency_flag ? 1 : 0
  function_name                     = module.lambda_function.function_name
  provisioned_concurrent_executions = var.provision_executions
  qualifier                         = data.aws_lambda_alias.current.function_version
}

--> the above code sets the provisioned concurrency on the previous version. (example: "alias: current" --> v5, concurrency set on v4)

I also tried this and its same behavior, concurrency set on previous version.
qualifier                         = aws_lambda_function.main.version (using tf resource object, instead of tf module)

Any suggestions?

**Comment by tymik** [comment]
@sriniavgs it seems that you are missing the `data "aws_lambda_function` configuration block, can't test now but I'd say it is required for whole workaround to work.
The another thing is - do you have the `current` alias for your lambda and is it updated?
In the example I am using alias `latest` which is there by default, provided by AWS - if you use custom alias, you need to take care of it on your own - custom alias doesn't necessarily have to point to the latest version of your lambda function.

You might also want to check AWS docs regarding Lambda [versions](https://docs.aws.amazon.com/lambda/latest/dg/configuration-versions.html) and [aliases](https://docs.aws.amazon.com/lambda/latest/dg/configuration-aliases.html)

**Comment by jamiejackson** [comment]
I'm trying @Woitekku 's workaround. The function was generated by a CloudFront template (via Terraform), so I don't think I have any more direct access to it as a resource.

```terraform
data "aws_lambda_alias" "cognito_auth__check_auth_handler__localdev" {
  provider = aws.us-east-1
  function_name = "serverlessrepo-localdevCloudfront-CheckAuthHandler-yCGyEJodo4jh"
  name          = "latest"
}

data "aws_lambda_function" "cognito_auth__check_auth_handler__localdev" {
  provider = aws.us-east-1
  function_name = "serverlessrepo-localdevCloudfront-CheckAuthHandler-yCGyEJodo4jh"
  qualifier = data.aws_lambda_alias.cognito_auth__check_auth_handler__localdev.function_version
}
```

However, Terraform throws this, which I don't know how to interpret:

```
│ Error: Provider configuration not present
│ 
│ To work with data.aws_lambda_alias.cognito_auth__check_auth_handler__localdev its original provider configuration at provider["registry.terraform.io/hashicorp/aws"].us-east-1 is required, but it has been removed. This occurs when
│ a provider configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy data.aws_lambda_alias.cognito_auth__check_auth_handler__localdev, after which you
│ can remove the provider configuration again.
```

Do you know what this means and how to solve it?
