### ISSUE TITLE
Spot fleet request doesn't kill spawned instances on a destroy

### ISSUE THREAD

**Issue by chriskinsman** [hashicorp/terraform-provider-aws#10083]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.12.8
aws provider version 2.23

### Affected Resource(s)

* aws_spot_fleet_request

### Terraform Configuration Files

```
resource "aws_spot_fleet_request" "spot_fleet" {
  iam_fleet_role                      = "${var.spot_fleet_role}"
  spot_price                          = "1.4"
  target_capacity                     = 1
  valid_until                         = "2036-01-01T00:00:01Z"
  excess_capacity_termination_policy  = "Default"
  replace_unhealthy_instances         = true
  terminate_instances_with_expiration = true

  lifecycle {
    create_before_destroy = true
    ignore_changes = ["target_capacity"]
  }

  dynamic "launch_specification" {
      for_each = local.launch_specs

      content {
            instance_type = launch_specification.value[0]
            ami           = "${lookup(local.amis, data.aws_region.current.name)}"

            root_block_device {
                volume_size = "30"
                volume_type = "gp2"
            }

            ebs_block_device {
                volume_size = "50"
                volume_type = "gp2"
                device_name = "/dev/xvdcz"
            }

            key_name = "Default"

            user_data = <<USER_DATA
#!/bin/bash
echo ECS_CLUSTER='${aws_ecs_cluster.ecs-cluster.name}' > /etc/ecs/ecs.config
USER_DATA

            subnet_id                   = launch_specification.value[1]
            iam_instance_profile        = "${var.iam_instance_profile}"
            associate_public_ip_address = true
            vpc_security_group_ids      = "${var.security_groups}"

            tags = {
                type    = "spot"
                service = "${var.cluster_name}"
            }
      }
  }
}
```

### Expected Behavior

Terraform destroy completes and all instances spawned by spot fleet request are terminated

### Actual Behavior

Spot fleet request is cancelled but instances remain

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

**Comment by Bryksin** [comment]
I confirm the same issue, my terraform code snippet is provided in another opened issue #11161
The destroy command is stuck in an infinitive loop attempting to delete a security group which is still in use by spot-fleet instance which is not terminated, even though spot-fleet state changed to:
`fleetRequestChange | cancelled_running`

Not even sure if it's terraform provider issue, or AWS not killing instances when spot-fleet request was cancelled.

**Comment by Bryksin** [comment]
Found solution:
`terminate_instances_with_expiration 	= true` 
Ticket can be closed

**Comment by totomz** [comment]
`terminate_instances_with_expiration = true` is a working workaround but does not resolve this issue.

`TerminateInstancesWithExpiration` indicates whether running Spot Instances are terminated when the Spot Fleet request **expires**, not when it is cancelled, as per [AWS Docs](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SpotFleetRequestConfigData.html)

Also, [Terraform docs](https://www.terraform.io/docs/providers/aws/r/spot_fleet_request.html#iam_fleet_role) for iam_fleet_role describe the correct behaviour: spot instances should be terminated if the fleet request is cancelled (which is happening with terraform destroy) or when the Spot fleet request expires, if you set terminateInstancesWithExpiration.

**Comment by matthewfranglen** [comment]
Is there any progress on this issue?

**Comment by antonbormotov** [comment]
Confirm, terraform 0.12.24 cancels spotfleet and terminates instances when`terminate_instances_with_expiration = true` is set explicitly without `valid_until`.

**Comment by pmalek** [comment]
I have submitted a small change that should rectify this https://github.com/hashicorp/terraform-provider-aws/pull/17268

This basically adds `terminate_instances` in the same way as ec2 fleet defines it ([registry link](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_fleet#terminate_instances), [source link](https://github.com/hashicorp/terraform-provider-aws/blob/5e35b49d56e212e8f1905dd22e352b8d3f36cca5/aws/resource_aws_ec2_fleet.go#L314-L318))

I'd need to work on test for this PR but the gist of the change is there.
