### ISSUE TITLE
Manage ACM PCA CA Permissions

### ISSUE THREAD

**Issue by joshuabaird** [hashicorp/terraform-provider-aws#10090]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

PCA requires you to assign "permissions" to the PCA CA in order to grant access that allows ACM to perform automated renewals of PCA certificates.

See the AWS documentation here:  https://docs.aws.amazon.com/acm-pca/latest/userguide/PcaRenewalPermissions.html

### New or Affected Resource(s)

* aws_acmpca_certificate_authority

### Potential Terraform Configuration

Perhaps create a new `aws_acmpca_certificate_authority_permission` resource that allows a user to define permissions on the PCA CA.

### References
* https://docs.aws.amazon.com/acm-pca/latest/userguide/PcaRenewalPermissions.html

**Comment by nitrocode** [comment]
@breathingdust should this be open ? it seems like this was closed accidentally by the github-actions bot.

**Comment by breathingdust** [comment]
@nitrocode thanks for the bump, the stale bot is doing what it should in this case. Reopening.

**Comment by dejongm** [comment]
New reference links as the issue notes are stale:
I believe this is in reference to one of the two below: 

**ACM PCA Resource-based policy**
https://docs.aws.amazon.com/acm-pca/latest/userguide/pca-rbp.html

**Using a service-linked role (SLR) with ACM**
https://docs.aws.amazon.com/acm/latest/userguide/acm-slr.html

Either case, both should be implemented.

**Comment by breathingdust** [comment]
Hi all 👋 Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!
