### ISSUE TITLE
Terraform 11 bug with aws_iam_policy_document

### ISSUE THREAD

**Issue by soneil123** [hashicorp/terraform-provider-aws#10138]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
11.14 and 12.9

### Affected Resource(s)
* aws_iam_policy_document

### Expected Behavior
Valid TF11 syntax should work in both TF11 and TF12

### Actual Behavior
Unable to create code that works in both TF11 and TF12

### Details

I'm trying to create a 'bridge' version of our Terraform modules that work in both TF11 and TF12 (strict TF11 syntax).  I've been quite successful except for this issue duplication example:

```hcl
variable "bucket_users"  {
  type    = "list"
  default = []
  #default = ["user1", "user2"]
}

locals {
  bucket_users       = "${concat(list(data.aws_caller_identity.current.arn), var.bucket_users)}"
  bucket_name        = "blah"
}

data "aws_caller_identity" "current" {}

provider "aws" {
  region = "us-east-1"
}

terraform {
  backend "local" {}
}

output "bucket_users" {
  value = "${local.bucket_users}"
}

data "aws_iam_policy_document" "default_restricted" {
  statement {
    sid = "RequireBucketUserPolicy"

    actions = ["s3:*"]

    effect = "Deny"

    resources = [
      "arn:aws:s3:::${local.bucket_name}",
      "arn:aws:s3:::${local.bucket_name}/*",
    ]

    not_principals {
      type        = "AWS"
      identifiers = ["${local.bucket_users}"]
    }
  }
}
```

with Terraform 11.14 I can confirm that `bucket_users` is a list so when I try to switch `identifiers = ["${local.bucket_users}"]` to `identifiers = "${local.bucket_users}"` (remove the unneeded hint) it throws the following error:
```
Error: data.aws_iam_policy_document.default_restricted: statement.0.not_principals.0.identifiers: should be a list
```
The only way I can fix it is to put the brackets back. In Terraform 12.9, I get this error if I leave the brackets:
```
Error: Incorrect attribute value type

  on main.tf line 41, in data "aws_iam_policy_document" "default_restricted":
  41:       identifiers = ["${local.bucket_users}"]

Inappropriate value for attribute "identifiers": element 0: string required.
```
This seems to be a bug in the TF11 code (requiring the brackets) and I'm not able to use this module in both TF11 and TF12.

**Comment by git-heera** [comment]
Any update on this issue
I am getting same

**Comment by ucodevault** [comment]
any update on this?. I'm facing the same issue.

Error: Incorrect attribute value type

  on .terraform/modules/sns/main.tf line 21, in data "aws_iam_policy_document" "sns-topic-policy":
  21:       identifiers = [var.sns_policy_principals_identifiers]

Inappropriate value for attribute "identifiers": element 0: string required.

**Comment by ucodevault** [comment]
@soneil123 @git-heera you can remove "[" and "]" for the indentifiers = ["${local.bucket_users}"] and just do this "${local.bucket_users}" . As ${local.bucket_users} is already a list. Hope this works.

**Comment by justinretzolk** [comment]
Hey y'all 👋 Thank you for taking the time to file this issue, and for the discussion around it! Since this appears to be resolved at this point, we'll close the issue. If you feel we've done this in error, please let us know or open a raise a fresh issue.
