### ISSUE TITLE
Data source `aws_route_tables` is not indexable

### ISSUE THREAD

**Issue by trainsushi** [hashicorp/terraform-provider-aws#10147]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.8
+ provider.aws v2.28.1
```

### Affected Resource(s)

* aws_route_tables

### Terraform Configuration Files

```hcl
data "aws_route_tables" "vpc_route_tables" {
  vpc_id = var.vpc_id
  filter {
    name   = "tag:Name"
    values = ["*"]
  }
}

resource "aws_route" "client_b" {
  count                  = var.transit_gtw_id == "" ? 0 : length(data.aws_route_tables.vpc_route_tables.ids)
  route_table_id         = data.aws_route_tables.vpc_route_tables.ids[count.index]
  destination_cidr_block = var.vpn_client_b_cidr
  transit_gateway_id     = var.transit_gtw_id
}
```

### Panic Output

```
Error: Invalid index

  on .terraform/modules/some/path/file.tf line 31, in resource "aws_route" "client_b":
  31:   route_table_id         = data.aws_route_tables.vpc_route_tables.ids[count.index]
    |----------------
    | count.index is 4
    | data.aws_route_tables.vpc_route_tables.ids is set of string with 6 elements

This value does not have any indices.
```

### Expected Behavior

`data.aws_route_tables.vpc_route_tables.ids` data source should be a list of strings (route table ids) according to the [documentation](https://www.terraform.io/docs/providers/aws/d/route_tables.html).

### Actual Behavior

It's actually a set of strings.

```
data.aws_route_tables.vpc_route_tables.ids is set of string with 6 elements
```

### Steps to Reproduce

Assuming you have a VPC/subnets/route tables to test,
1. Grab all the route tables in the test VPC
2. Attach a route to the first one.
```
data "aws_route_tables" "vpc_route_tables" {
  vpc_id = var.test_vpc_id
  filter {
    name   = "tag:Name"
    values = ["*"]
  }
}

resource "aws_route" "client" {
  route_table_id         = data.aws_route_tables.vpc_route_tables.ids[0]
  destination_cidr_block = "172.25.0.0/22"
  network_interface_id   = var.test_network_interface_id
}
```

3. `terraform init`
4. `terraform plan`

### Important Factoids

The docs should be updated if this is expected behavior.

### References

* Similar to https://github.com/terraform-providers/terraform-provider-aws/issues/9381

**Comment by mikhail-bardash** [comment]
I'm having the same issue, but I was able to resolve it using [tolist](https://www.terraform.io/docs/configuration/functions/tolist.html).

`data "aws_route_tables" "route_tables" {
  vpc_id = var.vpc_id

  filter {
    name   = "tag:Type"
    values = ["private"]
  }
}

resource "aws_vpn_gateway_route_propagation" "vpn_gateway_route_propagation" {
  count = "${length(tolist(data.aws_route_tables.route_tables.ids))}"

  vpn_gateway_id = "${aws_vpn_gateway.vpn_gw.id}"
  route_table_id = "${tolist(data.aws_route_tables.route_tables.ids)[count.index]}"
}`

**Comment by trainsushi** [comment]
@mikhail-bardash `tolist` will give you a result in an undefined order.
```
Since set elements are not ordered, the resulting list will have an undefined order 
that will be consistent within a particular run of Terraform.
```

My understanding is this can potentially make Terraform destroy/create your route propagations if ordering changes. For instance,
```
# Result set (unordered)
{route_a, route_b, route_c}

# First terraform run with tolist (ordered)
[route_a, route_b, route_c]

# Second terraform run with tolist (ordered)
[route_a, route_c, route_b]
```

If you use Terraform 0.12, the fix will be refactoring the code with `for_each`
```
resource "aws_vpn_gateway_route_propagation" "vpn_gateway_route_propagation" {
  for_each       = data.aws_route_tables.route_tables.ids
  vpn_gateway_id = aws_vpn_gateway.vpn_gw.id
  route_table_id = each.key
}
```

**Comment by mootpt** [comment]
`for_each` will still result in the recreation of your route propagations or in my case routes. this warrants a better solution

**Comment by ltagliamonte-dd** [comment]
So I've found 2 issues so far on aws_route_tables in tf12.

Using the `for_each` on existing resources will re-create the resource because now the `each` is used as value for the array:
```
aws_route.staging_kube_to_staging_account["rtb-00b81351bfe433675378"]
```
compared to what it was before:
```
aws_route.staging_kube_to_staging_account["0"]
```

The second problem I've found is that the results from `data` object are now a set and they are ordered, something like this for example:
```
data "aws_route_tables" "staging_kube_private_subnets_rt" {
  filter {
    name = "association.subnet-id"

    values = [
      data.aws_subnet.staging-priv-0.id,
      data.aws_subnet.staging-priv-1.id,
      data.aws_subnet.staging-priv-2.id,
    ]
  }
}
```
returns an ordered set, that will screwup the terraform state because in array[0] now there is `rtb-123456` before there was `rtb-654321`.

Since I don't want to delete and re-create route tables to avoid any kind of network disruption but we did upgrade to tf12 , I've come up  with something like this:

```
data "aws_route_tables" "staging_kube_private_subnets_rt_0" {
  filter {
    name = "association.subnet-id"

    values = [
      data.aws_subnet.staging-priv-0.id
    ]
  }
}

data "aws_route_tables" "staging_kube_private_subnets_rt_1" {
  filter {
    name = "association.subnet-id"

    values = [
      data.aws_subnet.staging-priv-1.id
    ]
  }
}

data "aws_route_tables" "staging_kube_private_subnets_rt_2" {
  filter {
    name = "association.subnet-id"

    values = [
      data.aws_subnet.staging-priv-2.id
    ]
  }
}
```

and:

```
locals {
  staging_kube_private_subnets_rt = concat(
  tolist([for route in data.aws_route_tables.staging_kube_private_subnets_rt_2.*.ids : route][0]),
  tolist([for route in data.aws_route_tables.staging_kube_private_subnets_rt_0.*.ids : route][0]),
  tolist([for route in data.aws_route_tables.staging_kube_private_subnets_rt_1.*.ids : route][0])) 
}
```

and:

```
resource "aws_route" "staging_kafka_staging_account" {
  count                     = length(local.staging_kube_private_subnets_rt)
  route_table_id            = local.staging_kube_private_subnets_rt[count.index]
  destination_cidr_block    = local.kafka_00_cidr
  vpc_peering_connection_id = local.kafka_00_vpc_peering_id
}
```

concat will preserve the order of the lists you put in, in this way i can match the order of the elements in the existing terraform state.
I definitively would love to go back to a single data source, but in the meantime this works are workaround.

**Comment by opub** [comment]
The data.aws_route_tables documentation example is enough to cause this. At the very least the documentation should be updated. 
https://www.terraform.io/docs/providers/aws/d/route_tables.html

**Comment by Liath** [comment]
Seems kinda hacky but `sort(tolist(data.aws_route_tables.route_tables.ids))` has been stable enough and should stay that way until I add more route-tables.

**Comment by trainsushi** [comment]
This issue is resolved by https://github.com/hashicorp/terraform-provider-aws/pull/12802
