### ISSUE TITLE
Diff Suppression function in mixed instance policy prevents ASG from going from 1 to 0 on-demand instances with on_demand_base_capacity

### ISSUE THREAD

**Issue by ssabo** [hashicorp/terraform-provider-aws#10152]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.11.14
```

### Affected Resource(s)

* aws_autoscaling_group - https://github.com/terraform-providers/terraform-provider-aws/blob/563413f703780d98418f5f2885043b974805e8c9/aws/resource_aws_autoscaling_group.go#L97-L101

### Expected Behavior

Given an Autoscaling group where `on_demand_base_capacity` == 1, the value should be changed to 0 in AWS when the terraform variable is changed.

### Actual Behavior

`on_demand_base_capacity` remains set at 1 despite being changed in terraform config.

### Steps to Reproduce

1. Create an autoscaling group using mixed instance policy using terraform and set `on_demand_base_capacity` to 1. Setting to anything besides 1 will not reproduce this behavior.
1. `terraform apply` and double check that the value is set to 1.
1. change the value of `on_demand_base_capacity` for this ASG to 0 in terraform config.
1. `terraform plan` and observe no diff is generated. 

### References
https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_autoscaling_group.go#L97-L101

* #0000

**Comment by maryelizbeth** [comment]
Thanks for taking the time to submit this issue. 

This issue relates to an older version of Terraform that is no longer in active development, and many parts of Terraform have changed significantly since this version (`0.11.14`) of Terraform was released.

If you're still seeing this or a similar issue in the latest version of Terraform, please update the issue listing the most recent version of Terraform!

**Comment by ssabo** [comment]
Hey @maryelizbeth, I don't believe that the version of terraform has bearing on this bug. The issue is linked in the description in the aws provider. My understanding of the problem is that the provider is not differentiating between `on_demand_base_capacity` being absent from the terraform config and it being set to 0, but only when the previous value is `1`. 

I _think_ this is because the default for this attribute is `1`, but when an integer is absent in golang it defaults to 0. This short circuit likely exists to prevent changes when the config line is set to the default value and then removed from terraform config. 

This means that in order to change an ASG's `on_demand_base_capacity` from 1 to 0, you have to first change it to something > 1, apply the change, then then you can change it to 0.

**Comment by ssabo** [comment]
I have not verified, but it appears that this was fixed in https://github.com/hashicorp/terraform-provider-aws/commit/a86043071b8003f01ea8d861be21f94ec2681147. I'll close this issue.
