### ISSUE TITLE
CodeBuild: Unable to create secondary_artifact with type = "CODEPIPELINE" | "NO_ARTIFACT"

### ISSUE THREAD

**Issue by JonathanReiss15** [hashicorp/terraform-provider-aws#10176]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

`Terraform v0.12.2`

### Affected Resource(s)

* `+ provider.aws v2.28.1`

### Terraform Configuration Files

```hcl
resource "aws_codebuild_project" "frontend_build_project" {
  name          = "${var.frontend_repo_name}-${var.frontend_branch}-pipeline"
  description   = "CodeBuild project for CodePipeline used for ${var.frontend_branch} branch"
  build_timeout = "60" # minutes
  service_role  = "${aws_iam_role.codepipeline_role.arn}"

  artifacts {
    type = "CODEPIPELINE"
  }

  secondary_artifacts {
    type                = "CODEPIPELINE"
    artifact_identifier = "backend_repo_files"
  }

  environment {
    compute_type                = "BUILD_GENERAL1_SMALL"
    image                       = "aws/codebuild/standard:1.0"
    type                        = "LINUX_CONTAINER"
    image_pull_credentials_type = "CODEBUILD"
  }

  logs_config {
    s3_logs {
      status = "ENABLED"
      location = "${aws_s3_bucket.codepipeline_bucket.id}/build-log"
    }
  }

  source {
    type = "CODEPIPELINE"
  }

}
```

### Expected Behavior

Terraform should provision a CodeBuild project with a secondary_artifact that is sourced from a previous step in the CodePipeline.

### Actual Behavior

```
Error: expected secondary_artifacts.0.type to be one of [S3], got CODEPIPELINE

  on modules/frontend_pipeline/frontend_pipeline.tf line 127, in resource "aws_codebuild_project" "frontend_build_project":
 127: resource "aws_codebuild_project" "frontend_build_project" {
```

### Steps to Reproduce

1. `terraform apply`

### References

This was broken by the merge of this pull request because the reviewer was erroneously assuming that only "S3" is a valid `type`.

* #9652  - Breaking change occurs here

**Comment by AlexHilson** [comment]
The comments from @jckuester in #9652 showing that type = "CODEPIPELINE" is not supported match my experience. This is not a common issue (#9652 is the only google result for this error message), so I raised with AWS support, who state:

> I tried to update a codebuild project in a codepipeline phase via CLI, and it gave me the same error. I reached out to my colleagues from the CodeBuild team and they mentioned that for secondaryArtifact, CODEPIPELINE type is not supported. The only valid types are S3 and NoArtifacts
> 
> I will be reaching out to the AWS documentation team to get this updated to avoid any confusion. Apologies for the confusion regarding this.

<img width="727" alt="aws_support_response" src="https://user-images.githubusercontent.com/6014104/66220081-40674900-e6c4-11e9-8f83-cc3e13347b5b.png">

**Comment by anGie44** [comment]
Hi @JonathanReiss15 , as @AlexHilson commented above, `CODEPIPELINE` is no longer supported and our docs will now reflect this with the changes in #16535 (also takes into account `NO_ARTIFACTS` is not supported as well). Nevertheless, thank you for having raised this issue 👍
