### ISSUE TITLE
aws_macie_member_account_association tries to call macie.region.amazonaws.com, but that hostname doesn't resolve in DNS externally

### ISSUE THREAD

**Issue by scumola** [hashicorp/terraform-provider-aws#10172]
Not really sure if this is a terraform issue (should it be calling a different endpoint?) or an AWS issue (should macie.region.amazonaws.com resolve externally?) or can this just not be run outside of AWS maybe?

aws_macie_member_account_association tries to call macie.region.amazonaws.com, but that hostname doesn't resolve in DNS externally.

$ host macie.us-east-2.amazonaws.com
Host macie.us-east-2.amazonaws.com not found: 3(NXDOMAIN)

The error from Terraform:

Error: Error creating Macie member account association: RequestError: send request failed
caused by: Post https://macie.us-east-2.amazonaws.com/: dial tcp: lookup macie.us-east-2.amazonaws.com on mydns.domain.com:53: no such host

I've checked DNS in several locations and it doesn't resolve external to AWS at all from anywhere.

**Comment by ewbankkit** [comment]
@scumola According to the [AWS documentation](https://docs.aws.amazon.com/macie/latest/userguide/what-is-macie.html). Amazon Macie is currently only available in the `us-east-1` and `us-west-2` regions.
For other regions (e.g. `us-east-2` as in your example) the `no such host` error is expected.

**Comment by jar-b** [comment]
Closed by #31058, merged to `main` via #31392
