### ISSUE TITLE
AWS aurora unexpected state 'configuring-iam-database-auth' when modifying the `iam_database_authentication_enabled` flag

### ISSUE THREAD

**Issue by reegnz** [hashicorp/terraform-provider-aws#10197]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.9
AWS provider v2.29.0

### Affected Resource(s)

* aws_rds_cluster

### Expected Behavior

Terraform should have waited for the database to have the iam-authentication enabled.

### Actual Behavior

I got this error:
```
Error: error waiting for RDS Cluster (playground-aurora-db-postgres) to be available: unexpected state 'configuring-iam-database-auth', wanted target 'available'. last error: %!s(<nil>)

  on main.tf line 27, in resource "aws_rds_cluster" "this":
  27: resource "aws_rds_cluster" "this" {


Releasing state lock. This may take a few moments...
```

### Steps to Reproduce

1. provision an rds aurora database (postgres v10.7) with the `apply_immediately` flag.
2. once provisioned, add `iam_database_authentication_enabled = true` flag and try to reprovision

**Comment by tecnobrat** [comment]
I took a look at the code, this looks like its missing from the state transitions for `rds_cluster_instance` but not for `db_instance`:

Missing: https://github.com/terraform-providers/terraform-provider-aws/blob/e903501d82b3d83a5342deb4ec2df95732d61ba5/aws/resource_aws_rds_cluster_instance.go#L629-L639

Does exist: https://github.com/terraform-providers/terraform-provider-aws/blob/e903501d82b3d83a5342deb4ec2df95732d61ba5/aws/resource_aws_db_instance.go#L1774

**Comment by ldalorion** [comment]
Any updates on this issue? Currently seeing this with terraform version 0.13.5 and hashicorp/aws v3.22.0.

**Comment by bill-rich** [comment]
Hi @azhurbilo! I wasn't able to reproduce this problem with v3.33. Can you please provide an example configuration and steps to reproduce it?

**Comment by azhurbilo** [comment]
@bill-rich thnx for checking. now I don't have candidate DB for an upgrade to reproduce it. you can close issue, if I face with unexpected state one more time, I will share the config with you

**Comment by bill-rich** [comment]
That sounds good. Thank you!
