### ISSUE TITLE
Enhancement: Elastic Inference Accelerators for SageMaker

### ISSUE THREAD

**Issue by WriteCodeEveryday** [hashicorp/terraform-provider-aws#10208]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Sagemaker on the CLI and Console support attaching an elastic inference accelerator to notebooks. This is a far cheaper option when creating your notebook than a full size P2 instance.

### New or Affected Resource(s)

* aws_sagemaker_notebook_instance

### Potential Terraform Configuration

* The configuration available under [launch templates](https://www.terraform.io/docs/providers/aws/r/launch_template.html#elastic_inference_accelerator) can be used as a reference for this functionality

### References

* [Elastic Inference](https://aws.amazon.com/machine-learning/elastic-inference/)
* [Resource aws_sagemaker_notebook_instance](https://github.com/terraform-providers/terraform-provider-aws/pull/2999)

**Comment by ewbankkit** [comment]
Similar:
* https://github.com/terraform-providers/terraform-provider-aws/issues/8157
* https://github.com/terraform-providers/terraform-provider-aws/issues/11408
