### ISSUE TITLE
selection_pattern on aws_api_gateway_integraion_response doesn't get saved

### ISSUE THREAD

**Issue by dgoradia** [hashicorp/terraform-provider-aws#10222]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.12.9
+ provider.aws v2.29.0
```

### Affected Resource(s)

* aws_api_gateway_integraion_response

### Terraform Configuration Files

```hcl
resource "aws_api_gateway_integration_response" "a_post_default" {
  rest_api_id       = var.rest_api_id
  resource_id       = aws_api_gateway_resource.a.id
  http_method       = aws_api_gateway_method.a_post.http_method
  status_code       = aws_api_gateway_method_response.a_post_200.status_code
  selection_pattern = "-"

  response_templates = {
    "text/plain" = ""
  }

  response_parameters = {
    "method.response.header.Access-Control-Allow-Origin" = "'*'"
  }
}
```

### Expected Behavior

```
Plan: 0 to add, 0 to change, 0 to destroy.
```

### Actual Behavior

```
Terraform will perform the following actions:

  # module.my_staging_api.module.resources.aws_api_gateway_integration_response.t_post_default will be updated in-place
  ~ resource "aws_api_gateway_integration_response" "t_post_default" {
        http_method         = "POST"
        id                  = "agir-xxxxxyyyyy-zzzzzz-POST-200"
        resource_id         = "zzzzzz"
        response_parameters = {
            "method.response.header.Access-Control-Allow-Origin" = "'*'"
        }
        response_templates  = {
            "text/plain" = ""
        }
        rest_api_id         = "xxxxxyyyyy"
      + selection_pattern   = "-"
        status_code         = "200"
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform apply -target module.my_staging_api.module.resources.aws_api_gateway_integration_response.t_post_default`

### Important Factoids

Terraform will try to modify this every time.

**Comment by chriscorn-takt** [comment]
I run into the same problem with v0.11.14.

**Comment by bflad** [comment]
The `aws_api_gateway_integration_response` documentation has been updated to remove the `"-"` mention for the `selection_pattern` argument, especially since that is not documented by AWS. To specify the resource as the default, simply do not set `selection_pattern` in the resource configuration (or set it equal to `null` in a conditional). 👍
