### ISSUE TITLE
AutomationTargetParameterName parameter is missing on aws_ssm_association

### ISSUE THREAD

**Issue by arnaudouttiercloudreach** [hashicorp/terraform-provider-aws#10239]
[AutomationTargetParameterName](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateAssociation.html#systemsmanager-CreateAssociation-request-AutomationTargetParameterName) parameter is missing in the aws_ssm_association resource inputs, preventing for example to associate the [AWS-AttachIAMToInstance](https://docs.aws.amazon.com/systems-manager/latest/userguide/automation-aws-attachiamtoinstance.html) document.

**Comment by bflad** [comment]
Support for the `automation_target_parameter_name` argument in the `aws_ssm_association` resource was previously added in version 2.47.0 of the Terraform AWS Provider (https://github.com/hashicorp/terraform-provider-aws/pull/11755). 👍
