### ISSUE TITLE
Improve aws_ssm_association documentation about targets argument

### ISSUE THREAD

**Issue by marpada** [hashicorp/terraform-provider-aws#10261]
### Description

The documentation of the aws_ssm_association is somewhat confusing around the usage of the targets argument, for example

> targets - (Optional) A block containing the targets of the SSM association. Targets are documented below. AWS currently supports a maximum of 5 targets. 

There's no further reference to targets in the document. From the AWS API documentation

> Targets: The targets (either instances or tags) for the association. You must specify a value for Targets if you don't specify a value for InstanceId. 

If neither *targets* not  *instance_id* are provided resource creation fails with "Error creating SSM association: InvalidTarget: Instance ID or targets must be specified".

### References
https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateAssociation.html

**Comment by ljluestc** [comment]
With this updated documentation, users will be aware that if they don't provide an instance_id, they need to provide targets, and the targets block should include the key and values attributes. 

> Targets specify what instance IDs or tags to apply the document to and has these keys:

> * `key` - (Required) Either `InstanceIds` or `tag:Tag Name` to specify an EC2 tag.
> * `values` - (Required) A list of instance IDs or tag values. AWS currently limits this list size to one value.

could this be closed? Or still any confusion here? Just want to be sure. Thanks

**Comment by justinretzolk** [comment]
Given the updates to the `aws_ssm_association` resource due to the [`instance_id` deprecation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_association.html#instance_id), it feels like this is now clear. With that in mind I'll close this out.
