### ISSUE TITLE
route_53_record: `name` should be treated same both short and FQDN

### ISSUE THREAD

**Issue by Dominik-K** [hashicorp/terraform-provider-aws#1031]
In `aws_route53_record`, `name` should be treated as the same value, i.e. no new resource forced,  if it is configured as short name (only subdomains, e.g. `www`) as well as FQDN (e.g. `www.example.com`). 

Currently, Terraform will force a new resource if 
* `name = "www"` in config & 
* `name = "www.example.com"` in state file.

Tested with
* `0.10.0 dev` (e6ddd62583d89) and AWS provider `v0.1.2`
* `0.9.10`

I've stumbled on this issue, as 
* `import` saves `name = "www.example.com"`(`0.9.10`) in state file (`0.10.0`: with trailing dot, but not in `fqdn`), but
* `terraform apply` saves `name = "www"` in state file (if set so in the config).

Interestingly, `terraform plan -out terraform.plan` (with refreshed state) accepts the `name = "www"` config if it is already `name = "www"` in the state file.

**Comment by Dominik-K** [comment]
A trailing dot in the state file forces a new resource no matter if it is there in the config or not. In other words:
* `www.example.com.` (trailing dot) in state file forces a new resource if
* `www.example.com` or  `www.example.com.` in config.

It works the other way round (trailing dot in config, but not in state file). Tested again with both versions.

As the trailing dot confuses, see e.g. #241, I vote for always saving only the subdomains in the `name`:
* Easier to read in the configuration, especially if the hosted zone already is a subdomain.
* There's the (new?) `fqdn` field for the long version.

**Comment by G-Rath** [comment]
This is still an issue in Terraform v0.12.15 & AWS Provider v2.41.0.

It's a big pain when mass importing routes, as Terraform ends up destroying the majority of the routes *before* recreating them, causing downtime b/c it can't create until its destroyed and by default can only do 10 operators at once, and it views the creation & destruction as unrelated.
