### ISSUE TITLE
Tech debt: Consolidate ENI Describe/Detach/Delete calls

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#10363]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As noted by @obourdon in [this comment](https://github.com/terraform-providers/terraform-provider-aws/pull/10114#pullrequestreview-289996479), https://github.com/terraform-providers/terraform-provider-aws/pull/10114 and https://github.com/terraform-providers/terraform-provider-aws/pull/10347 introduced new routines to describe, detach and delete ENIs.
There are multiple other locations throughout the code that make similar calls.
We should consider consolidating on a single set of routines that perform these actions.

### New or Affected Resource(s)

* `aws_elb`
* `aws_internet_gateway`
* `aws_lb`
* `aws_network_interface`
* `aws_network_interface_attachment`
* `aws_network_interface_sg_attachment`

### Potential Terraform Configuration

```hcl
n/a
```

**Comment by VanWolf29** [comment]
I can take this ticket.

**Comment by VanWolf29** [comment]
Can I have some more background on this issue so that I can start working please?

**Comment by ewbankkit** [comment]
Closing in favor of #21406.
