### ISSUE TITLE
aws_dynamodb_table_item does not work if one of the field contains a hyphen

### ISSUE THREAD

**Issue by thelo-gaultier** [hashicorp/terraform-provider-aws#10385]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14
+ provider.aws v2.31.0

### Affected Resource(s)

* aws_dynamodb_table_item

### Terraform Configuration Files

```hcl
resource "aws_dynamodb_table" "dynamodb_table" {
  name            = "test-table"
  hash_key        = "name"

  billing_mode    = "PAY_PER_REQUEST"

  attribute {
    name = "name"
    type = "S"
  }
}

resource "aws_dynamodb_table_item" "item" {
  table_name = "${aws_dynamodb_table.dynamodb_table.name}"
  hash_key   = "${aws_dynamodb_table.dynamodb_table.hash_key}"

  item = <<ITEM
{
  "name":     {"S": "main"},
  "label":    {"S": "Main"}
}
ITEM
}

resource "aws_dynamodb_table_item" "item_2" {
  table_name = "${aws_dynamodb_table.dynamodb_table.name}"
  hash_key   = "${aws_dynamodb_table.dynamodb_table.hash_key}"

  item = <<ITEM
{
  "label-fail":    {"S": "Main"},
  "name":     {"S": "main2"}
}
ITEM
}
```

### Debug Output

https://gist.github.com/thelo-gaultier/d540ff24beebadca969d9db454ca8f4d

### Expected Behavior

the `item_2`should be created successfully

### Actual Behavior

Terraform throw this exception
```
Error: Error applying plan:

1 error occurred:
	* aws_dynamodb_table_item.item_2: 1 error occurred:
	* aws_dynamodb_table_item.item_2: Error retrieving DynamoDB table item: ValidationException: ExpressionAttributeNames contains invalid key: Syntax error; key: "#a_label-fail"
	status code: 400, request id: R9OU92P3E8G8G0GRT7954PSSGJVV4KQNSO5AEMVJF66Q9ASUAAJG
```
### Steps to Reproduce

1. `terraform apply`

### References

Dynamo offers [expression projection](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ExpressionAttributeNames.html) to solve this problem, however this does not seem to be available in the current terraform provider [documentation](https://www.terraform.io/docs/providers/aws/r/dynamodb_table_item.html)

**Comment by edward-of-clt** [comment]
Similar situation when the key contains a `/` 

```
Error: Error retrieving DynamoDB table item: ValidationException: ExpressionAttributeNames contains invalid key: Syntax error; key: "#a_#/test"
        status code: 400, request id: 6HARTQCVK3K2FB15D15LL9GG6VVV4KQNSO5AEMVJF66Q9ASUAAJG
```

**Comment by opub** [comment]
FYI this bug happens when evaluating the state of aws_dynamodb_table_item. So once you have a aws_dynamodb_table_item resource in your state with one of the bad cases above it can't be fixed without manually clearing that out. I just spent hours recreating my table, renaming attributes, changing attribute values, completely removing any references to aws_dynamodb_table_item, etc. all of which had no impact since the bad values were cached in my S3 state file.

**Comment by yermulnik** [comment]
Same here 😢 
```
│ Error: Error retrieving DynamoDB table item: ValidationException: ExpressionAttributeNames contains invalid key: Syntax error; key: "#a_s3.storage"
│       status code: 400, request id: 5H680R0K4RDMKE95D6FJN7C90BVV4KQNSO5AEMVJF66Q9ASUAAJG
```

Added `+1` to https://github.com/hashicorp/terraform-provider-aws/pull/14075
