### ISSUE TITLE
Deleted transit gateway attachments causing resource refresh to fail

### ISSUE THREAD

**Issue by GambolingPangolin** [hashicorp/terraform-provider-aws#10393]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```shell
$ terraform -v
Terraform v0.12.9
```

### Affected Resource(s)

* aws_vpn_connection

### Terraform Configuration Files

```hcl
resource "aws_ec2_transit_gateway" "main" { ... }
resource "aws_vpn_connection" "main" {
  ...
  transit_gateway_id = aws_ec2_transit_gateway.main.id
}
```

### Expected Behavior

The Site-to-site VPN connection was attached to the transit gateway.  We deleted the attachment, then reattached it in the console.  This creates a second transit gateway attachment.  However, one has status "active" and the other has status "deleted".

Terraform should ignore the "deleted" attachment when refreshing state.

### Actual Behavior

`Error: error reading EC2 VPN Connection (vpn-XXXXX) Transit Gateway Attachment: multiple responses`

### Steps to Reproduce

Create a transit gateway and VPN connection attached to it.  Create a virtual private gateway and associate the VPN connection with it, deleting the attachment between the VPN and the transit gateway.   Change the VPN association back the transit gateway.  There is a period during which the VPN has two attachments to the transit gateway, one "active" and one "deleted".  Run `terraform (refresh|plan|apply)`.

Eventually Amazon clears the deleted attachment and `terraform` resumes working as expected.

### Important Factoids

Grepping the code suggests an explanation and fix. Consider [this filter][1] and [this test][2].

This suggests that the problem is that the response contains records for the deleted attachment because we are filtering only based on VPN connection id, transit gateway id, and attachment type.  I expect that constructing a slice with only the `Status == "active"` values in `output.TransitGatewayAttachments` and using this new slice for the various tests in [this block][3] would solve the problem.

[1]: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_vpn_connection.go#L393
[2]: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_vpn_connection.go#L421
[3]: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_vpn_connection.go#L392

**Comment by dsantanu** [comment]
hi, any update on this issue yet? I'm having exactly the same issue. Right now I have two deleted TGW hanging around from the previous `terraform destroy`:

```
$ aws --profile=pppt-tgw ec2 describe-transit-gateways  --filters 'Name=options.amazon-side-asn,Values=4200064111' --query 'TransitGateways[*].[TransitGatewayId,State,Options.AmazonSideAsn]' --output text
tgw-0d32f8f5b017ccf56	deleted	4200064111
tgw-0dd1b6abd0d845b50	deleted	4200064111
```
and now the the data-source with this:
```
data "aws_ec2_transit_gateway" "tgwz" {
  filter {
    name   = "options.amazon-side-asn"
    values = ["4200064${substr(var.ccenter,1,3)}"]
  }
}
```
keep error'ing out with this:

> Error: error reading EC2 Transit Gateway: multiple results found, try adjusting search criteria
> 
>   on ../../modules/vpc/data.tf line 6, in data "aws_ec2_transit_gateway" "tgwz":
>    6: data "aws_ec2_transit_gateway" "tgwz" {

is there anyway to filter that out using the `State=available` or something? TF should ignore all the deleted TGW by default IMO.

-S

**Comment by mzhaase** [comment]
I think this is causing a second issue. TF does not re-create a deleted transit gateway attachment. It still assumes the attachment is fine, but every resource depending on it will fail.

**Comment by iamgeef** [comment]
If ignoring the deleted TGWs is not a valid fix, then at least update the docs for data "aws_ec2_transit_gateway" to show that the "state" filter is available:
[link](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ec2_transit_gateway)
