### ISSUE TITLE
Bug in aws_security_group - Unable to update SG if another group is referenced

### ISSUE THREAD

**Issue by kjartansible** [hashicorp/terraform-provider-aws#10390]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.6
+ provider.aws v2.27.0

### Affected Resource(s)

* aws_security_group

### Terraform Configuration Files

```hcl
resource "aws_security_group" "web_access" {
  name        = "Web SG"
  description = "Allow traffic from the ELBs"
  vpc_id      = "${aws_vpc.vpc.id}"
  ingress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    security_groups    = [
      "${aws_security_group.elb_public.id}",
      "${aws_security_group.elb_private.id}"
    ]
  }
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["${var.anybody.cidr}"]
    description = "${var.anybody.description}"
  }
}

resource "aws_security_group" "db" {
  name        = "Database SG"
  description = "Database security group"
  vpc_id      = "${aws_vpc.vpc.id}"
  ingress {
    from_port   = 3306
    to_port     = 3306
    protocol    = "tcp"
    security_groups = [
      "${aws_security_group.web_access.id}"
    ]
  }
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["${var.anybody.cidr}"]
    description = "${var.anybody.description}"
  }
}

```

### Expected Behavior

If I change the description of the security group, it forces a destroy and recreate of the security group, since AWS doesn't allow me to change the description.
The security group id needs to be deleted in the database security group and then the new id needs to be inserted.

### Actual Behavior

Seems like terraform doesn't see that the Web security group is referenced in the DB security group and that the reference needs to be deleted _before_ the group itself is deleted, so terraform hangs until it times out.

### Steps to Reproduce

1. `terraform apply`
2. Change the description of the web security group
3. `terraform apply`

**Comment by dariosusman** [comment]
Having a similar issue. The security_groups attribute does not "like" the reference aws_security_group.any-common_services.id - asks to be a set of strings. 
Even using toset(aws_security_group.any-common_services.id) didn't help.

```
$ terraform -v
Terraform v0.12.24
+ provider.aws v2.61.0
```
```
resource "aws_security_group" "any-common_services" {
  name = "any-common_services"
  description = "Common VPC Services"
  vpc_id = aws_vpc.default.id
  ingress {
    from_port = 22
    to_port = 22
    protocol = "tcp"
    cidr_blocks = ["10.192.1.10/32"]
  }
  ingress {
   from_port = -1
   to_port = -1
   protocol = "icmp"
   cidr_blocks = ["10.192.0.0/16"]
  }
  ingress {
   description = "salt"
   from_port = 4506
   to_port = 4506
   protocol = "tcp"
   cidr_blocks = ["10.192.70.11/32"]
  }
  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}  

resource "aws_security_group" "nat-traffic-out" {
  name = "nat-traffic-out"
  description = "Allows traffic through the NAT/VPN instance"
  vpc_id = aws_vpc.default.id
  ingress {
    from_port = 0
    to_port = 0
    protocol = -1
    security_groups = aws_security_group.any-common_services.id
  }  
  egress {
    from_port = 0
    to_port = 0
    protocol = -1
    cidr_blocks =  ["0.0.0.0/0"]
  }  
} 
```
```
Error: Incorrect attribute value type

  on fgxdev.tf line 306, in resource "aws_security_group" "nat-traffic-out":
 306:     security_groups = aws_security_group.any-common_services.id

Inappropriate value for attribute "security_groups": set of string required.
```

**Comment by dariosusman** [comment]
On terrafom 0.12 you don't need to reference other stuff with ${}. 

For example 
```
    security_groups    = [
      "${aws_security_group.elb_public.id}",
      "${aws_security_group.elb_private.id}"
    ]
```
should be referenced like
```
    security_groups    = [
      aws_security_group.elb_public.id,
      aws_security_group.elb_private.id
    ]
```

Give it a shot.
