### ISSUE TITLE
MalformedPolicyDocument: Policy document should not specify a principal.

### ISSUE THREAD

**Issue by ifaisalalam** [hashicorp/terraform-provider-aws#10419]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
* v0.12.9

### Affected Resource(s)

* aws_iam_policy_document
* aws_s3_bucket
* aws_s3_bucket_policy

### Terraform .tf File
```tf
provider "aws" {
  profile = "default"
  region = "ap-south-1"
  version = "~> 2.30"
}

provider "template" {
  version = "~> 2.1"
}

resource "aws_iam_user" "dummy_user" {
  name = "dummy-user"
}

data "aws_iam_policy_document" "dummy_s3_policy" {
  statement {
    actions = ["s3:*"]
    effect = "Allow"
    resources = ["arn:aws:s3:::dummy-bucket/*"]
    principals {
      identifiers = [aws_iam_user.dummy_user.arn]
      type = "AWS"
    }
  }
}

resource "aws_kms_key" "dummy_bucket_enc" {
  description         = "This is used to encrypt objects in dummy-bucket S3 bucket."
  enable_key_rotation = true
}

resource "aws_s3_bucket" "dummy_bucket" {
  bucket = "dummy-bucket"
  acl    = "private"
  policy = data.aws_iam_policy_document.dummy_s3_policy.json

  versioning {
    enabled = true
  }

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        kms_master_key_id = aws_kms_key.dummy_bucket_enc.arn
        sse_algorithm     = "aws:kms"
      }
    }
  }
}

resource "aws_iam_access_key" "dummy_user" {
  user = aws_iam_user.dummy_user.name
}

output "access_key_id" {
  value = aws_iam_access_key.dummy_user.id
}
```

### Expected Behavior

The resources should have been successfully deployed.

### Actual Behavior

Throws the following error message on the console

```
Error: Error creating IAM policy terraform-20191007202007807300000001: MalformedPolicyDocument: Policy document should not specify a principal.
        status code: 400, request id: db9c849e-e93f-11e9-bba2-111df2ad0ed5

  on deployment.tf line 84, in resource "aws_iam_policy" "rds_backup_s3_policy":
  84: resource "aws_iam_policy" "rds_backup_s3_policy" {
```

### Steps to Reproduce

1. `terraform apply`

**Comment by nicodujovne** [comment]
Any news about this? did you managed to work around the error? im getting the same error

**Comment by djordje-petrovic** [comment]
Any news on this?

**Comment by ifaisalalam** [comment]
> Any news on this?

Nope. I had to manually add policy to the document.

**Comment by djordje-petrovic** [comment]
> > Any news on this?
> 
> Nope. I had to manually add policy to the document.

Thanks for reply. Anyway I've tried using RoleIDs instead of ARNs and still doesn't help. Shall update this issue if come up with some solution.

**Comment by ifaisalalam** [comment]
> > > Any news on this?
> > 
> > 
> > Nope. I had to manually add policy to the document.
> 
> Thanks for reply. Anyway I've tried using RoleIDs instead of ARNs and still doesn't help. Shall update this issue if come up with some solution.

Sure, thank you.

**Comment by sukoneck** [comment]
I ran into a similar issue where I had a `aws_iam_policy_document` that specified `action, effect,` and `principals`. I had to switch from `principals` to `resources`. I'm betting that your issue is that you cannot assign a `principals` because `principals` is implied to be the `aws_s3_bucket` (the implication happens when you specify the `policy` argument in the `resource`). Try dropping `principals` from `aws_iam_policy_document` and it'll probably work. 

Caveat: I haven't messed with bucket policies, so I'm not 100% sure about the details. I basing this on **u/theWyzzerd** [comments here](https://www.reddit.com/r/Terraform/comments/cr54kb/terraform_policy_assignment_issue/ex383zb/) and @apparentlymart [comments here](https://github.com/hashicorp/terraform/issues/13449#issuecomment-296277581). 

FWIW, **u/theWyzzerd** recommends _"Put your heredoc string directly in the "policy" attribute"_... rather than using `aws_iam_policy_document`

**Comment by djordje-petrovic** [comment]
In my case it's not that. Principals are referring to IAM roles and users.

**Comment by sukoneck** [comment]
Bummer. I haven't found it written clearly anywhere, but I've never seen an HCL formatted policy (the kind that gets translated to json) work with both `resources` and `principals` defined. Does it work if you do what **u/theWyzzerd** [recommends ](https://www.reddit.com/r/Terraform/comments/cr54kb/terraform_policy_assignment_issue/ex383zb/) and "_Put your heredoc string directly in the "policy" attribute_"... rather than using aws_iam_policy_document?

**Comment by djordje-petrovic** [comment]
> Bummer. I haven't found it written clearly anywhere, but I've never seen an HCL formatted policy (the kind that gets translated to json) work with both `resources` and `principals` defined. Does it work if you do what **u/theWyzzerd** [recommends ](https://www.reddit.com/r/Terraform/comments/cr54kb/terraform_policy_assignment_issue/ex383zb/) and "_Put your heredoc string directly in the "policy" attribute_"... rather than using aws_iam_policy_document?

Yes. That did it. Thanks.

`resource "aws_kms_key" "key" {
  description             = "key desc"
  deletion_window_in_days = 10
  policy 		  = <<POLICY
{
...
}
POLICY
}
`

**Comment by alfredocambera** [comment]
I was receiving this error as I was, mistakenly, passing the assume role policy to `aws_iam_role_policy` in the `policy` field.  😞 

The assume role policy should be passed to  `aws_iam_role` in the `assume_role_policy`.

**Comment by tperelle** [comment]
Same error with terraform v0.12.25

```
data "aws_iam_policy_document" "iac" {
  for_each = data.external.accounts-list.result
  statement {
    sid    = "${each.value}"
    effect = "Allow"

    actions = ["sts:AssumeRole"]

    resources = [      
       "arn:aws:iam::${each.value}:role/iac"
    ]

    principals {
      identifiers = [aws_iam_user.account-iac[each.key].arn]
      type        = "AWS"
    }
  }
}
```

And. the error
```
Error: Error putting IAM group policy iac-access: MalformedPolicyDocument: Policy document should not specify a principal.
	status code: 400, request id: 77540964-3b13-4d49-b4de-23fb48691b80
```

So the behaviour doesn't correspond to [the documentation](https://www.terraform.io/docs/providers/aws/d/iam_policy_document.html#example-with-multiple-principals) !

**Comment by abdulg** [comment]
Same error. I was able to use the policy document directly instead of trying to create a policy. I think it's cleaner than a heredoc:

```
resource "aws_s3_bucket_policy" "logs_bucket" {
  bucket = aws_s3_bucket.logs_bucket.id
  policy = data.aws_iam_policy_document.logs_bucket_policy.json
}
```

The policy document creates the policy from [here](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html).

```
$ terraform version
Terraform v0.12.19
+ provider.aws v2.44.0
```

**Comment by SuperDuperOne** [comment]
this seems to still be happening, even after testing with the suggestions mentioned above.
has anyone managed to resolve this "bug/issue/problem"

my iam.tf file

```
resource "aws_iam_role" "dummy_role" {
  name               = "${var.name_prefix}${data.aws_caller_identity.current.account_id}-dummy_role"
  assume_role_policy = data.aws_iam_policy_document.dummy_role_assume.json
}

data "aws_iam_policy_document" "dummy_role_assume" {
  statement {
    actions     = ["sts:AssumeRole"]
    principals {
      identifiers = ["s3.amazonaws.com"]
      type = "Service"
    }
  }
}

resource "aws_iam_role_policy_attachment" "dummy_role" {
  role       = aws_iam_role.dummy_role.name
  policy_arn = aws_iam_policy.dummy_role.arn
}

resource "aws_iam_policy" "dummy_role" {
  name       = "${var.name_prefix}${data.aws_caller_identity.current.account_id}-dummy_role"
  policy     = data.aws_iam_policy_document.dummy_role.json
  depends_on = [aws_iam_role.dummy_role]

}

data "aws_iam_policy_document" "dummy_role_data_bucket_policy" {
  statement {
    sid = "AllowUsersToWrite"
    principals {
      type = "AWS"
      identifiers = [
        var.get_dummy_role_arn
      ]
    }
    effect = "Allow"
    actions = ["s3:PutObject"]
    resources = [
      "arn:aws:s3:::${var.name_prefix}${data.aws_caller_identity.current.account_id}dummy_role-bucket-data/*",
    ]
  }
  statement {
    sid = "AllowReading"
    principals {
      type = "AWS"
      identifiers = [
        var.view_dummy_role_arn,
        var.process_dummy_role_arn
      ]
    }
    effect = "Allow"
    actions = [
      "s3:GetObject",
      "s3:GetObjectVersion",
    ]
    resources = [
      "arn:aws:s3:::${var.name_prefix}${data.aws_caller_identity.current.account_id}dummy_role-bucket-data/*",
    ]
  }

  statement {
    sid = "AllowReadingListOfBuckets"
    principals {
      type = "AWS"
      identifiers = [
        var.view_dummy_role_arn,
        var.process_dummy_role_arn
      ]
    }
    effect = "Allow"
    actions = [
      "s3:ListBucket"
    ]
    resources = [
      "arn:aws:s3:::${var.name_prefix}${data.aws_caller_identity.current.account_id}dummy_role-bucket-data",
    ]
  }
}
```

**Comment by zelds** [comment]
Same error as above. I try grant allow permission to SNS topic where principals is CloudWatch.
https://aws.amazon.com/premiumsupport/knowledge-center/cloudwatch-receive-sns-for-alarm-trigger/

**Comment by biot023** [comment]
In case this is any help to anybody who ends up here...

I was having this issue with creating a bucket for an ALB to log to.
With AWS support (who are brilliant, btw), we realised that I was creating the wrong type of policy document -- I was creating an IAM policy document when I should have been creating a bucket policy document. That fixed it. After a number of hours that I have no intention of disclosing! :)

The code I ended up with (with some string interpolation) was this:

```terraform
resource "aws_s3_bucket" "alpha_lb_logs" {
  bucket = "alpha-lb-logs"
  acl = "log-delivery-write"

  tags = {
    "Name" = "Alpha Load Balancer Logs"
    "ns" = "alpha"
  }
}

resource "aws_s3_bucket_policy" "alpha_lb_logs" {
  bucket = aws_s3_bucket.alpha_lb_logs.id

  policy = <<EOT
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::${local.bucket_regional_account_id}:root"
            },
            "Action": "s3:PutObject",
            "Resource": "${aws_s3_bucket.alpha_lb_logs.arn}/AWSLogs/${local.bucket_account_id}/*"
        },
        {
            "Sid": "AWSLogDeliveryWrite",
            "Effect": "Allow",
            "Principal": {
                "Service": "delivery.logs.amazonaws.com"
            },
            "Action": "s3:PutObject",
            "Resource": "${aws_s3_bucket.alpha_lb_logs.arn}/AWSLogs/${local.bucket_account_id}/*",
            "Condition": {
                "StringEquals": {
                    "s3:x-amz-acl": "bucket-owner-full-control"
                }
            }
        },
        {
            "Sid": "AWSLogDeliveryAclCheck",
            "Effect": "Allow",
            "Principal": {
                "Service": "delivery.logs.amazonaws.com"
            },
            "Action": "s3:GetBucketAcl",
            "Resource": "${aws_s3_bucket.alpha_lb_logs.arn}"
        }
    ]
}
  EOT
}
```

**Comment by ewbankkit** [comment]
Closing this Issue as the comments capture the solution.
