### ISSUE TITLE
Feature Request: Dynamic Security Group Association for VPC Endpoint Interface

### ISSUE THREAD

**Issue by ben3683914** [hashicorp/terraform-provider-aws#10429]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm hoping to get a feature added to dynamically add security groups to a VPC Endpoint Interface. An example of something similar would be how security group rules can be added using aws_security_group_rule.

### New or Affected Resource(s)

* aws_vpc_endpoint_security_group_association

### Potential Terraform Configuration

```hcl
resource "aws_vpc_endpoint" "this" {
  vpc_id            = "vpc-myvpc"
  service_name      = "com.amazonaws.us-west-2.sns"
  vpc_endpoint_type = "Interface"

  subnet_ids = [
    "subnet-mysubnet1",
    "subnet-mysubnet2"
  ]

  private_dns_enabled = true
}

resource "aws_vpc_endpoint_security_group_association" "this-securitygroup-one" {
  vpce_id        = "${aws_vpc_endpoint.this.id}"
  source_security_group_id = "sg-securitygroupone"
}

resource "aws_vpc_endpoint_security_group_association" "this-securitygroup-two" {
  vpce_id        = "${aws_vpc_endpoint.this.id}"
  source_security_group_id = "sg-securitygrouptwo"
}

resource "aws_vpc_endpoint_security_group_association" "this-securitygroup-three" {
  vpce_id        = "${aws_vpc_endpoint.this.id}"
  source_security_group_id = "sg-securitygroupthree"
}
```

**Comment by ewbankkit** [comment]
@ben3683914 Thanks for opening this feature request.
Looking back at the initial implementation of [interface VPC endpoints](https://docs.aws.amazon.com/vpc/latest/userguide/vpce-interface.html) I see [this comment](https://github.com/terraform-providers/terraform-provider-aws/pull/2253#issuecomment-345554521) about why we didn't initially add a `aws_vpc_endpoint_security_group_association` resource.
I will take a look and see those observations are still valid.

**Comment by ewbankkit** [comment]
@ben3683914 I verified it's still the case that if no security groups are specified during VPC endpoint creation that the VPC's default security group is associated with the endpoint.

**Comment by ben3683914** [comment]
I don't believe I actually need this use case anymore, but I was running down the potential of it where we would need to add multiple security groups to the vpc endpoint dynamically based on how we had written other pieces of our terraform.

Maybe I'm misunderstanding, but couldn't you have it create it using the default security group of the VPC, but still allow adding of groups dynamically?

**Comment by vidyadhar7am** [comment]
Hi All, 
right now m stuck in mid of same requirement.
Where i need to use my newly created SG(via terraform) as an Interface to one of the existing vpc_endpoint. 
so can make use of above scenario or it any further modifications required regards to adding any missing contents?

**Comment by vidyadhar7am** [comment]
also ended up with an error "Provider doesn't support resource: aws_vpc_endpoint_security_group_association" when tried to make use of above scenario..

**Comment by DarkArc-Github** [comment]
Also waiting for this resource. I'm stuck at the AWSTransferFamily server that crerates a VPC endpoint but the current resource doesn't provide any param to specify the SG.
this could have helped me to attach SG to the endpoint.

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!
