### ISSUE TITLE
identity_source on api gateway authorizer create should have no default value

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#10461]
Here identity_source is defined as string: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_api_gateway_authorizer.go#L28

The v1 AWS API Gateway api does take a string for identity_source as per: https://docs.aws.amazon.com/apigateway/api-reference/link-relation/authorizer-create/

There is a valid authorizer config that has ttl set to 0 and no identity source. However, there is no way to express that in terraform because identity_source has a default value as per https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_api_gateway_authorizer.go#L31

That default value should be removed so that a config with ttl=0 and NO identity providers can be expressed in terraform.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by sadliak** [comment]
Any updates or ETA regarding this issue?

**Comment by antoiner77** [comment]
Any news ?

**Comment by bryan-taylor** [comment]
A crappy work around is to set `identity_source = ","` . The comma separates two empty entries and will cause no identity_source to be provisioned. However, the resulting stored state in terraform will be an empty string, which doesn't match the input, so this will be viewed as a change in state every time.

A default should supply a value only if a valid one isn't declared. If I declare `identity_source = ""` it's quite rude to override me and set it to the default.

**Comment by eerobinson** [comment]
what about setting it to a context or stage var?  like context.apiId
