### ISSUE TITLE
AWS Firewall Manager management of Amazon VPC security groups

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#10471]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Firewall Manager now supports management of Amazon VPC security groups.

### New or Affected Resource(s)

* [`aws_fms_policy`](https://github.com/terraform-providers/terraform-provider-aws/pull/9594)

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/10/aws-firewall-manager-now-supports-management-of-amazon-vpc-security-groups/).
[Blog post](https://aws.amazon.com/blogs/aws/aws-firewall-manager-update-support-for-vpc-security-groups/).

Requires [AWS SDK v1.25.10](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.10), https://github.com/terraform-providers/terraform-provider-aws/pull/10378.

Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/4058

**Comment by bflad** [comment]
For folks finding this issue, #4058 represents the feature request to add the new resource (with open PR (#9594). This issue represents enhancing that resource to include VPC security group management if the initial implementation does not include it.

**Comment by robh007** [comment]
I can look to enhance my original PR @bflad.

**Comment by bill-rich** [comment]
Added in #9594
