### ISSUE TITLE
resource: network_interface, private_ips is documented as a list, while it's a set

### ISSUE THREAD

**Issue by zerkms** [hashicorp/terraform-provider-aws#10506]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

All

### Affected Resource(s)

* aws_network_interface

https://www.terraform.io/docs/providers/aws/r/network_interface.html

https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_network_interface.go#L48

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by pmcevoy** [comment]
As a result, when assigning multiple static IPs, there is no guarantee that the _first_ ip becomes the _primary_ IP.  Instead, I need to use an *undocumented* `private_ip` property to specifiy which item from the list is the primary:
```
resource "aws_network_interface" "eni0_public" {
  count = length(local.zones)

  subnet_id         = data.aws_subnet.public[count.index].id
  security_groups   = [data.aws_security_group.fgt.id]
  source_dest_check = false
	private_ip        = cidrhost(data.aws_subnet.public[count.index].cidr_block, 11)
	private_ips       = [ 
		cidrhost(data.aws_subnet.public[count.index].cidr_block, 11),
		cidrhost(data.aws_subnet.public[count.index].cidr_block, 13)
	]
  description       = "${local.name_qualifier} ${count.index} port1 - External"
  tags = {
    Name = "${local.name_qualifier} ${count.index} port1 - External"
  }
}
```

**Comment by pmcevoy** [comment]
See also [No way to specify primary IP on aws_network_interface when multiple IPs in play](https://github.com/terraform-providers/terraform-provider-aws/issues/10674)

**Comment by zerkms** [comment]
Not stale.
