### ISSUE TITLE
Reader endpoint in aws_elasticache_replication_group

### ISSUE THREAD

**Issue by MateuszStefek** [hashicorp/terraform-provider-aws#10519]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS ElastiCache replication group for Redis has attribute called `ReaderEndpoint`. It has the same structure as `PrimaryEndpoint`.

Terraform aws provider already gives us `primary_endpoint_address` attribute.
Implement a new, similar attribute (`reader_endpoint_address`?) for the reader endpoint.

https://docs.aws.amazon.com/cli/latest/reference/elasticache/describe-replication-groups.html

### New or Affected Resource(s)

* `aws_elasticache_replication_group` resource and datasource

**Comment by jamesmcminn96** [comment]
If anyone is looking for a work around in the meantime, inferring the reader endpoint from the primary endpoint has worked well for us.

```
output "cache_reader_endpoint" {
  value = "${aws_elasticache_replication_group.cache.id}-ro.${
    join(
      ".",
      slice(
        split(".", aws_elasticache_replication_group.cache.primary_endpoint_address),
        1,
        length(split(".", aws_elasticache_replication_group.cache.primary_endpoint_address))
      )
    )
  }"
}
```

**Comment by nikskiz** [comment]
> If anyone is looking for a work around in the meantime, inferring the reader endpoint from the primary endpoint has worked well for us.
> 
> ```
> output "cache_reader_endpoint" {
>   value = "${aws_elasticache_replication_group.cache.id}-ro.${
>     join(
>       ".",
>       slice(
>         split(".", aws_elasticache_replication_group.cache.primary_endpoint_address),
>         1,
>         length(split(".", aws_elasticache_replication_group.cache.primary_endpoint_address))
>       )
>     )
>   }"
> }
> ```

It seems that AWS have updated endpoints. They are now:
Replica:
`replica.xxx.xxx.xxx.cache.amazonaws.com`
Master:
`master.xxx.xxx.xxx..cache.amazonaws.com`

I managed to get the reader endpoint with the following:
```
locals {
  # The AWS provider does not have a attribute reference for the reader_endpoint. Below is a way to get the reader_endpoint
  replace(aws_elasticache_replication_group.default[0].primary_endpoint_address, "/^master/", "replica") : 0
}
```

Keep in mind this is only for a non-clustered redis.

**Comment by tormodmacleod** [comment]
> If anyone is looking for a work around in the meantime, inferring the reader endpoint from the primary endpoint has worked well for us.
> 
> ```
> output "cache_reader_endpoint" {
>   value = "${aws_elasticache_replication_group.cache.id}-ro.${
>     join(
>       ".",
>       slice(
>         split(".", aws_elasticache_replication_group.cache.primary_endpoint_address),
>         1,
>         length(split(".", aws_elasticache_replication_group.cache.primary_endpoint_address))
>       )
>     )
>   }"
> }
> ```

we CNAME the address of the master to `cache.FULL_DOMAIN` and were hoping to CNAME the address of the reader to `cache-ro.FULL_DOMAIN` in order to have a consistent endpoint for our services.

just wanted to highlight that while this workaround is good for many use cases, it doesn't negate the need for this feature :¬)
