### ISSUE TITLE
Eks cluster version upgrade failing from terraform

### ISSUE THREAD

**Issue by nandeeshb09** [hashicorp/terraform-provider-aws#10543]
Hi Kit,
we tried to upgrade eks cluster by changing the Eks version , but eks cluster is deleting and re-creating the cluster with new version instead of updating.

Because of this we are loosing the data.

we are upgrading from 1.11 to 1.12.

Can you help us on this.?

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/9878

**Comment by ewbankkit** [comment]
@nandeeshb09 Could you please paste in the output of `terraform plan` that shows this resource recreation?
Thanks.

**Comment by bflad** [comment]
Closing due to lack of response. Please create a new issue following the bug report template if there is still a problem. 👍
