### ISSUE TITLE
`aws_customer_gateway` certificate authentication support

### ISSUE THREAD

**Issue by crypticmind** [hashicorp/terraform-provider-aws#10548]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Site-to-Site VPN now supports [certificate authentication](https://aws.amazon.com/about-aws/whats-new/2019/08/aws-site-to-site-vpn-now-supports-certificate-authentication/) besides pre-shared keys, but I don't see support for this in [`aws_customer_gateway`](https://www.terraform.io/docs/providers/aws/r/customer_gateway.html).

### New or Affected Resource(s)

* `aws_customer_gateway`
* `aws_vpn_connection`

### Potential Terraform Configuration

```hcl
resource "aws_customer_gateway" "cgtw" {
  bgp_asn         = 65000
  ip_address      = "${var.partner_ip_address}"
  type            = "ipsec.1"
  certificate_arn = "${config.vpn_certificate_arn}"
}
```

### References

- https://docs.aws.amazon.com/cli/latest/reference/ec2/create-customer-gateway.html
- https://aws.amazon.com/about-aws/whats-new/2019/08/aws-site-to-site-vpn-now-supports-certificate-authentication

**Comment by stekle** [comment]
please add aws_transit_gateway to "New or Affected Resource(s)" section above

**Comment by nweatimperkins** [comment]
> Cert Based VPNs are now a major requirement for LTE/G4/G5( dynamic tunnel IP address) and Security perspective and we can't use Terraform if this feature is not supported

Same. I think we can get around it by manually provisioning the CGW then importing it. That seems to be working for us at first glance.
