### ISSUE TITLE
New Resource: Amazon CloudWatch Anomaly Detector

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#10551]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon CloudWatch Anomaly Detection is now available in all commercial AWS regions.

### New or Affected Resource(s)

* `aws_cloudwatch_anomaly_detector`

### Potential Terraform Configuration

```hcl
resource "aws_cloudwatch_anomaly_detector" "example" {
  namespace   = "AWS/EC2"
  metric_name = "CPUUtilization"
  statistic   = "Average"

  dimension {
    name  = "dimension1"
    value = "value1"
  }
  dimension {
    name  = "dimension2"
    value = "value2"
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-cloudwatch-anomaly-detection-now-generally-available/).
[Blog post](https://aws.amazon.com/blogs/aws/new-amazon-cloudwatch-anomaly-detection/).
[API reference](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutAnomalyDetector.html).

**Comment by airmonitor** [comment]
I believe that this is a duplicated issue.

First request to implement  cw anomaly is below:

https://github.com/terraform-providers/terraform-provider-aws/issues/9293

**Comment by bflad** [comment]
Thanks for the note, @airmonitor -- this does appear to be a duplicate of #9293 (with an open pull request #9828). To prevent duplicate discussions and efforts, I'm going to close this issue in preference of the earlier ones. 👍

**Comment by airmonitor** [comment]
Please correct me if im wrong but both requests are for cloud watch anomaly detection in cloud watch alarms :)

**Comment by cougar2009** [comment]
Correct me if I am wrong, but will there not be a aws_cloudwatch_anomaly_detector resource then?  Just use aws_cloudwatch_metric_alarm  instead right?

**Comment by christianhaller3000** [comment]
@cougar2009 that's correct https://www.terraform.io/docs/providers/aws/r/cloudwatch_metric_alarm.html#example-with-an-expression (2nd example)
