### ISSUE TITLE
Using tags in Glue Jobs

### ISSUE THREAD

**Issue by swati04jain** [hashicorp/terraform-provider-aws#10678]
Hello,
Is there an option to tag glue jobs using terraform? AWS has introduced this functionality and it will be really helpful to organize our glue jobs.
Thanks,
Swati

**Comment by bflad** [comment]
Hi @swati04jain 👋 Thank you for submitting this.

This appears to be a similar ask to the existing issue (https://github.com/terraform-providers/terraform-provider-aws/issues/7668) and some community work has began (https://github.com/terraform-providers/terraform-provider-aws/pull/9866). To consolidate efforts and discussions, I'm going to close this issue in preference of the earlier ones. Please follow those for further updates.

Aside: Also please note that its helpful for the maintainers if you are to follow [one of the available issue templates](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) so they can fully understand the request. Issues in the future without all the requested information may automatically be closed. Thanks again. 👍
