### ISSUE TITLE
Update aws_dlm_lifecycle_policy to allow targetting instances

### ISSUE THREAD

**Issue by zaneeee** [hashicorp/terraform-provider-aws#10726]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, the AWS provider does not support a `resource_types` value of `INSTANCE`. This would be a useful feature, as it is AWS's recommended method for capturing snapshots of a RAID array. [See AWS blog post](https://aws.amazon.com/blogs/storage/taking-crash-consistent-snapshots-across-multiple-amazon-ebs-volumes-on-an-amazon-ec2-instance/).

### New or Affected Resource(s)

* aws_dlm_lifecycle_policy

### References

* Blog post describing how to create snapshots for RAID array: https://aws.amazon.com/blogs/storage/taking-crash-consistent-snapshots-across-multiple-amazon-ebs-volumes-on-an-amazon-ec2-instance/
* Example of CLI call with `ResourceTypes` of `INSTANCE`: https://docs.amazonaws.cn/en_us/AWSEC2/latest/WindowsGuide/snapshot-lifecycle.html#multivolume-lifecycle

**Comment by ismailyenigul** [comment]
This is really must have feature. Because we can't tag the root volume while creating instance. root_block_device   argument is in aws_instance does not support tagging https://www.terraform.io/docs/providers/aws/d/instance.html#root_block_device 
The solutions  are `resource_types  INSTANCE` support or tagging support for `root_block_device` as requested at 
https://github.com/hashicorp/terraform/issues/3531

**Comment by marcjay** [comment]
This actually works fine, even though the docs aren't updated to indicate that, just specify a value of `INSTANCE` for `resource_types`:
```
    resource_types = ["INSTANCE"]
```
I've got a PR open (#14348) that adds tests for this and also updates the docs to make support for it explicit
