### ISSUE TITLE
Add ability to allocate dedicated hosts for VMs

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform-provider-aws#10752]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add ability to allocate dedicated hosts for VMs.

API Methods: [AllocateHosts](https://docs.aws.amazon.com/en_pv/AWSEC2/latest/APIReference/API_AllocateHosts.html), [ReleaseHosts](https://docs.aws.amazon.com/en_pv/AWSEC2/latest/APIReference/API_ReleaseHosts.html), [ModifyHosts](https://docs.aws.amazon.com/en_pv/AWSEC2/latest/APIReference/API_ModifyHosts.html), [DescribeHosts](https://docs.aws.amazon.com/en_pv/AWSEC2/latest/APIReference/API_DescribeHosts.html).

(Note that these methods seem to work in aggregate, not sure if they can easily be unwound to a singular resource).

### New or Affected Resource(s)

* aws_ec2_dedicated_host

### Potential Terraform Configuration

```hcl
resource "aws_ec2_dedicated_host" "example" {
  auto_placement = ""
  availability_zone = ""
  host_recovery = ""
  instance_type = ""
  tags = {}
}

data "aws_ec2_dedicated_host" "example" {
  filters {}

  tags = {}
}
```

### References

- https://github.com/hashicorp/terraform/issues/4034

**Comment by hotdawg789** [comment]
Perfect timing @paultyng .  I just got done writing some boto3 to support this in my build pipeline... having it in terraform would be ideal, i forgot life without TFSTATE

**Comment by rpomykala** [comment]
My PR #10817  is ready for review, let me know if there's any way I can help further with getting this functionality added!

**Comment by marcincuber** [comment]
Just want to add that this new resource would be mega useful to have as Mac instances are now available. Mac instances require dedicated host of type `mac1.metal`. 

Otherwise we will have to stick to using CLI:
```
aws ec2 allocate-hosts --instance-type mac1.metal \
  --availability-zone eu-west-1 --auto-placement on \
  --quantity 1 --region eu-west-1
```

**Comment by jcollado** [comment]
@marcincuber As a workaround, note that you can call cloudformation from terraform:
```
resource "aws_cloudformation_stack" "dedicated_host" {
  name = "dedicated-host"
  template_body = jsonencode(
    {
      Description = "Dedicated host"
      Resources = {
        Host = {
          Type = "AWS::EC2::Host"
          Properties = {
            AvailabilityZone = <availability_zone>
            InstanceType     = <instance_type>
          }
        }
      }
      Outputs = {
        HostId = {
          Description = "Dedicated Host ID"
          Value = {
            Ref = "Host"
          }
        }
      }
    }
  )
  tags = <tags>
}

resource "aws_instance" "mac" {
  ...
  host_id                = aws_cloudformation_stack.dedicated_host.outputs.HostId
  ...
}
```

This is actually what this module from the registry does:
https://registry.terraform.io/modules/DanielRDias/dedicated-host/aws/latest

**Comment by scottmalkie** [comment]
Hello! Is there anything we can do to help accelerate this work? It looks like there is a PR waiting to be merged that adds this functionality.
