### ISSUE TITLE
aws_api_gateway_rest_api name alternates between provided config and OAS title.

### ISSUE THREAD

**Issue by adambutler** [hashicorp/terraform-provider-aws#10766]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.13
+ provider.aws v2.33.0
```

### Affected Resource(s)

aws_api_gateway_rest_api`

### Terraform Configuration Files

```hcl
resource "aws_api_gateway_rest_api" "api" {
  body = "${file("${path.module}/../public/api.yaml")}"
  name = "api-${terraform.workspace}"
}
```

### Debug Output

```
      ~ name                     = "Example Name" -> "api-staging"

Plan: 2 to add, 1 to change, 2 to destroy.
```

### Expected Behavior

The `name` provided in the terraform configuration should always be used.

### Actual Behavior

The `name` will alternate between the `name` provided in the terraform configuration and the one found within the provided OAS3 document at the key path `info.title`. For example:

```yml
openapi: "3.0.1"
info:
  version: 1.0.0
  title: Example Name
...
```

### Steps to Reproduce

1. `terraform apply` creates the resource with the correct name
2. `terraform apply` creates the resource with the name from the document
3. `terraform apply` creates the resource with the correct name again. etc.

**Comment by alex-bolenok-centralreach** [comment]
The `info.title` provided in then OpenAPI definition will overwrite anything you provide in the `name` parameter.

Creation of the rest API resource and providing its body are two separate AWS calls, though.

Ideally, `aws_api_gateway_rest_api` should yamldecode the `body` parameter if it's provided and substitute `name` and `description` with `info.title` and `info.description` from the body, if they are present there, as this is what the rest API is going to end up with anyway, regardless of what you provide in the resource parameters.

I'm just using this as a workaround:

```
resource "aws_api_gateway_rest_api" "rest_api" {
resource "aws_api_gateway_rest_api" "rest_api" {
  name        = local.openapi_document.info.title
  description = local.openapi_document.info.description

  endpoint_configuration {
    types = ["EDGE"]
  }

  body = yamlencode(local.openapi_document)
}
```

**Comment by adambutler** [comment]
🙏 Thank you to the Terraform maintrainers for resolving this issue.
