### ISSUE TITLE
aws_iam_policy_document doesn't detect invalid SIDs

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#10771]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v0.12.12

### Affected Resource(s)

* `aws_iam_policy_document`

### Terraform Configuration Files

Sample block:

```
data "aws_iam_policy_document" "test_doc" {
  statement {
    sid = "invalid-sid"
    actions = ["*"]
    resources = ["*"]
    effect = "Allow"
  }
}
```

### Expected Behavior

Terraform will fail to run the configuration because the `sid` field does not match the expression `[a-zA-Z0-9]+`.

### Actual Behavior

Terraform begins to run the configuration with the policy JSON where it is used and AWS reports that the SID is invalid.

**Comment by clar-cmp** [comment]
Hi Justin, I haven't checked this in a long time and don't have the time to confirm. You can close this if you think it's not an issue any more, or if no one else can verify it.
