### ISSUE TITLE
aws_ses_receipt_rule missing SNS Encoding property

### ISSUE THREAD

**Issue by garrett-hopper** [hashicorp/terraform-provider-aws#10855]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At the moment the default of `UTF-8` is the only supported encoding for SES to SNS rules. `Base-64` is often needed:
> The encoding to use for the email within the Amazon SNS notification. UTF-8 is easier to use, but may not preserve all special characters when a message was encoded with a different encoding format. Base64 preserves all special characters. The default value is UTF-8.

(https://docs.aws.amazon.com/ses/latest/APIReference/API_SNSAction.html#API_SNSAction_Contents)

This needs to be here: https://github.com/terraform-providers/terraform-provider-aws/blob/98b8b848ca94031b20c3e626c9d40484e3af80de/aws/resource_aws_ses_receipt_rule.go#L729
See https://godoc.org/github.com/aws/aws-sdk-go/service/ses#SNSAction for documentation.

### New or Affected Resource(s)

* aws_ses_receipt_rule

### Potential Terraform Configuration

```hcl
resource "aws_ses_receipt_rule" "$name" {
  name          = "$name"
  rule_set_name = $ruleSetName
  enabled       = true
  recipients    = [$recipient]

  sns_action {
    topic_arn = $topicArn
    position  = 1
    encoding = "Base64"
  }
}
```

**Comment by bflad** [comment]
An open pull request for this functionality can be found at #8605 -- it looks like its just waiting for another review from a maintainer (such as myself again 😅).

**Comment by Jumblemuddle** [comment]
Thanks, @bflad. I'd searched for issues, but I neglected to search for PRs.

**Comment by bflad** [comment]
@Jumblemuddle no worries! Its always good to have an associated issue for exactly that reason. 😄
