### ISSUE TITLE
Support AWS CLI v2 AWS Single Sign-On

### ISSUE THREAD

**Issue by e-moshaya** [hashicorp/terraform-provider-aws#10851]
https://aws.amazon.com/about-aws/whats-new/2019/11/use-the-aws-cli-v2-preview-with-aws-single-sign-on-to-increase-developer-productivity/

https://aws.amazon.com/blogs/developer/aws-cli-v2-now-supports-aws-single-sign-on/

I am using aws 2 with SSO integration to authenticate via command line. However, terraform is not recognising the configuration with the error below:

```
Error: No valid credential sources found for AWS Provider.
	Please see https://terraform.io/docs/providers/aws/index.html for more information on
	providing credentials for the AWS Provider

  on ../../modules/arangodb-terraform-module/providers.tf line 1, in provider "aws":
   1: provider "aws" {
```

**Comment by gdavison** [comment]
Thanks for submitting this issue, @e-moshaya. I'd like to clarify what you're seeing.

When you're trying to use the AWS SSO credentials with Terraform, what are the commands you execute on the command line?

Does calling `aws2 sts get-caller-identity` give you the credentials you expect?

**Comment by e-moshaya** [comment]
Hi @gdavison lookslike aws2 sso doesn't use ~/.aws/credentials file at all as all I have in my `ls ~/.aws/` directory is:

```
cli	config	sso
```

The ~/.aws/config has:
```
[profile default]
sso_start_url = https://synalogik-sso.awsapps.com/start
sso_region = eu-west-2
sso_account_id = 359814823984
sso_role_name = AdministratorAccess
region = eu-west-2
output = json
```

The output for ```aws2 sts get-caller-identity``` are as expected: 
```
{
    "UserId": "AROAR2UFOKOFEBO4KCB56:e.moshaya@mail.com",
    "Account": "125907653514",
    "Arn": "arn:aws:sts::xxxxxxxxxxx:assumed-role/AWSReservedSSO_AdministratorAccess_22134e45a32c8395/e.moshaya@mail.com"
}
```

**Comment by gdavison** [comment]
As a workaround, if either of the `~/.aws/cli` or `~/.aws/sso` files are structured like the old `~/.aws/credentials` file, for now you could add the `shared_credentials_file` parameter to your Terraform configuration.

I do see that https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html says that the v2 CLI is not ready for production use, but this is definitely something that needs to be implemented.

**Comment by e-moshaya** [comment]
@gdavison both sso and cli are folders with cache files in them.. There are no shared credentials files involved.

**Comment by ken5scal** [comment]
looking forward to it

**Comment by borrell** [comment]
FWIW, in the meantime this wrapper exists that will generate temporary credentials using aws2 then export them to the current session

    aws2-wrap --profile SSOProfileName --exec "terraform plan"

https://github.com/linaro-its/aws2-wrap

(found here https://github.com/aws/aws-cli/issues/4668)

**Comment by borrell** [comment]
AWS CLI v2 is now generally available.

https://aws.amazon.com/blogs/developer/aws-cli-v2-is-now-generally-available/

**Comment by eistrati** [comment]
Is there any timeline to this feature? Would be cool to see when this feature would be supported natively by terraform aws provider.

**Comment by bflad** [comment]
In my cursory looking, its my understanding that the [AWS Go SDK](https://github.com/aws/aws-sdk-go/) will need to first implement support for the `sso_*` configurations in the shared configuration file (e.g. in https://github.com/aws/aws-sdk-go/blob/master/aws/session/shared_config.go) or at least the SSO token cache (based off https://github.com/aws/aws-cli/tree/v2/awscli/customizations/sso). Depending on that implementation, the Terraform AWS Provider will either implicitly support SSO token access by nature of updating the AWS Go SDK or we can enable any necessary configurations to do so. I do not see any current upstream GitHub issues relating to this, so it may be worth starting there: https://github.com/aws/aws-sdk-go/issues

That being said, it is very likely that the Terraform AWS Provider cannot (or at least should not) implement the full SSO login workflow via opening a browser on expired SSO tokens unless there is support in the AWS Go SDK for this as well.

**Comment by b-dean** [comment]
The AWS SDK GO v2 is in a different repo: https://github.com/aws/aws-sdk-go-v2

It doesn't seem to have the same sessions and config stuff as the other sdk. Their [example looks pretty different](https://github.com/aws/aws-sdk-go-v2#hello-aws).

**Comment by ChristophShyper** [comment]
Looks like CLI now supports SSO: https://docs.aws.amazon.com/cli/latest/reference/sso/index.html#cli-aws-sso
Updated today.

**Comment by 273COS** [comment]
Did resolve the issue, I have done some testing but it still fails.

**Comment by claytonsilva** [comment]
Hi everyone, i read @borrell solution but, the solution from `aws2-wrap` is not safe for multiple profiles in same project. 
to solve this problem, i forked to 
https://github.com/claytonsilva/aws-sso-cred-restore

and  now i fill `~/.aws/credentials` file with my sso profiles (more than 1 in a single command)

I solve my problema until terraform solve this problem like `azure provider experience`.

**Comment by flyinprogrammer** [comment]
I took at stab at writing a [credential_process](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html) to solve this problem, which means you won't need to call scripts randomly, most applications are already smart enough to properly re-call the process when the credentials expire: https://github.com/flyinprogrammer/aws-sso-fetcher

it also does some caching so that sequential calls use a file until the credential expires.
It's pretty alpha software, but it seems to work  ¯\_(ツ)_/¯ Issues and feedback welcome.

**Comment by mknapik** [comment]
We had to use terraform with AWS account which supported SSO login only. Since AWS access key and secret expire, we've created a bunch of scripts to workaround the issue. I thought I'd share them here you might find it useful.
Check out fragment from our [`Taskfile.yml`](https://taskfile.dev/) (yaml based task runner, `Makefile` substitute): https://gist.github.com/mknapik/7220a2dda4a66b2710784b7a658bd491
Running `task aws:login` would login with SSO if necessary and migrate credentials to the format understood by terraform.

**Comment by Geethree** [comment]
Nice @mknapik Though I recommend you take a look at @flyinprogrammer 's work above yours... basically it is similar to the ecr-cred-helper for docker login. Quite.. a lovely workaround!

**Comment by valorl** [comment]
While the workaround is nice, it would be great to have this supported natively. Which project is this awaiting right now and are there any issues we can go vote on ?

**Comment by bflad** [comment]
@valorl https://github.com/aws/aws-sdk-go/issues/3186

**Comment by dkewley-uci** [comment]
I see that the AWS Go SDK appears to support AWS SSO:

https://docs.aws.amazon.com/sdk-for-go/api/service/sso/

I have no idea whether this is something that the Terraform AWS provider can use, or whether the aws-sdk-go issue cited by @bflad is the better way forward. I'm curious what others think.

**Comment by victorskl** [comment]
From https://github.com/aws/aws-cli/issues/4982 I ended up [yawsso](https://github.com/victorskl/yawsso) to sync v1 credentials from v2 SSO login session cache. So that I could keep going my daily terraform ops. While waiting to resolve this issue sooner!

**Comment by jason4151** [comment]
> From [aws/aws-cli#4982](https://github.com/aws/aws-cli/issues/4982) I ended up [yawsso](https://github.com/victorskl/yawsso) to sync v1 credentials from v2 SSO login session cache. So that I could keep going my daily terraform ops. While waiting to resolve this issue sooner!

Thank you @victorskl . This works nicely!

**Comment by jason4151** [comment]
> From [aws/aws-cli#4982](https://github.com/aws/aws-cli/issues/4982) I ended up [yawsso](https://github.com/victorskl/yawsso) to sync v1 credentials from v2 SSO login session cache. So that I could keep going my daily terraform ops. While waiting to resolve this issue sooner!

Thank you @victorskl. This works great!

**Comment by kapilt** [comment]
fwiw, aws vault supports this as an example of using the go sdk to support sso natively in tf  https://github.com/99designs/aws-vault/pull/549

**Comment by carlosrodf** [comment]
Just ran into this same problem
```
Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
```
managed to get it working with https://github.com/flyinprogrammer/aws-sso-fetcher but it would be nice this supported natively

**Comment by FernandoMiguel** [comment]
> Just ran into this same problem
> ```
> Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
> ```
> managed to get it working with https://github.com/flyinprogrammer/aws-sso-fetcher but it would be nice this supported natively

Been working fine on v6 beta

**Comment by onitake** [comment]
There's another option: You can use STS AssumeRole to create a temporary session token and export it into the environment.
That way you don't have to cache anything.
The downside is that you need to find the ARN of a role you can assume and you also need to parse the output of AWSCLI.

Example:
```shell
aws sts assume-role --role-arn "arn:aws:iam::123456:role/aws-reserved/sso.amazonaws.com/us-east-1/AWSReservedSSO_RoleName_123abcd" --role-session-name "temporary-session"
```

**Comment by Congee** [comment]
> 
> 
> fwiw, aws vault supports this as an example of using the go sdk to support sso natively in tf [99designs/aws-vault#549](https://github.com/99designs/aws-vault/pull/549)

For those who need the actual command, it's `aws-vault exec ${AWS_PROFILE} -- terraform plan`

see https://github.com/99designs/aws-vault/pull/653

**Comment by sean-nixon** [comment]
> > fwiw, aws vault supports this as an example of using the go sdk to support sso natively in tf [99designs/aws-vault#549](https://github.com/99designs/aws-vault/pull/549)
> 
> For those who need the actual command, it's `aws-vault exec ${AWS_PROFILE} -- terraform plan`
> 
> see [99designs/aws-vault#653](https://github.com/99designs/aws-vault/pull/653)

Adding onto this, for anyone that wants to interact with multiple accounts in the same Terraform workspace, you can do so by using the `credential_process` option in your `~/.aws/config` file for each AWS profile. Then you can specify the profile on the Terraform provider block just like normal.

```ini
[profile myssoprofile]
sso_start_url=https://example.awsapps.com/start
sso_region=us-east-1
sso_account_id=123456789000
sso_role_name=AWSAdministratorAccess
credential_process = aws-vault exec myssoprofile --json
```

**Comment by sandeep070** [comment]
I didn't upgraded my aws-vault - it was still v5.2.0

==> Upgrading 1 outdated package:
aws-vault 5.2.0 -> 6.2.0

After upgrading aws-vault version to 6.2.0, it works!

All I used is a below config, without credential_process
```[profile myssoprofile]
sso_start_url=https://example.awsapps.com/start
sso_region=us-east-1
sso_account_id=123456789000
sso_role_name=AWSAdministratorAccess```

**Comment by bulebuk** [comment]
With sean-nixon's approach of adding the `credential_process` line to `~/.aws/config`, you may call terraform (e.g. `terraform plan`) naturally without the wrapping aws-vault exec command.

**Comment by gentksb** [comment]
I tried `credential_process` solution. But it doesn't work for me.
SSO web page won't open at first time command (e.g.: `terraform plan` )

```
[profile myssoprofile]
...
credential_process = aws-vault exec myssoprofile --json --no-session
```

I always exec `aws-vault exec myssoprofile  --json --no-session` before `terraform plan` everyday. (my SSO profile TTL is 12h)
What should I set something additionally? w/o `--no-session` makes the same result. 

I am using Ubuntu18.04 on WSL2.

**Comment by bflad** [comment]
Hi folks 👋  Just to provide an update here -- the HashiCorp maintainers recently met with the AWS Go SDK maintainers and discussed this topic. We cannot give specifics, however please note that this support is very high on their priorities after finishing AWS Go SDK version 2. Once there are more public details we can provide in that regard and when we have more information about when/how support can be implemented in the Terraform AWS Provider, we will share them. Thanks!

**Comment by mmerickel** [comment]
> I tried credential_process solution. But it doesn't work for me.

@gentksb Did you `export AWS_SDK_LOAD_CONFIG=1` per https://docs.amazonaws.cn/sdk-for-go/api/aws/credentials/processcreds/? Without it the SDK will not use the `credential_process` directive.

**Comment by souzaxx** [comment]
Well, I've found a way to do that but It's not pretty

```terraform
data "external" "profile" {
  program = ["bash", "assume-role.sh"]
}

locals {
  access_key = data.external.profile.result["access_key"]
  secret_key = data.external.profile.result["secret_key"]
  token      = data.external.profile.result["token"]
}

provider "aws" {
  region     = "sa-east-1"
  access_key = local.access_key
  secret_key = local.secret_key
  token      = local.token
}

data "aws_caller_identity" "current" {}

output "caller" {
  value = data.aws_caller_identity.current
}
```

```bash
cat assume-role.sh                                                                                                                                        examples/sso-script
#!/bin/bash

set -x

unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_SESSION_TOKEN
unset AWS_ACCOUNT

JSON=$(aws sts assume-role \
         --role-arn arn:aws:iam::<accout>:role/<role> \
         --role-session-name teste \
         --duration-seconds ${AWS_STS_DURATION_SECONDS:-3600})

    AWS_ACCESS_KEY_ID=$(echo ${JSON} | jq --raw-output ".Credentials[\"AccessKeyId\"]")
AWS_SECRET_ACCESS_KEY=$(echo ${JSON} | jq --raw-output ".Credentials[\"SecretAccessKey\"]")
    AWS_SESSION_TOKEN=$(echo ${JSON} | jq --raw-output ".Credentials[\"SessionToken\"]")
       AWS_EXPIRATION=$(echo ${JSON} | jq --raw-output ".Credentials[\"Expiration\"]")

echo "{\"access_key\": \"$AWS_ACCESS_KEY_ID\", \"secret_key\": \"$AWS_SECRET_ACCESS_KEY\", \"token\": \"$AWS_SESSION_TOKEN\"}" | jq .
```

**Comment by FernandoMiguel** [comment]
> Hi guys, don't know if this can help in some way, in the sense is not an actual solution for the issue, BUT we have developed a project just to help with this kind of compatibility issues, it's here  on github: [https://github.com/Noovolari/leapp](https://github.com/Noovolari/leapp) and helps by enabling AWS SSO and third party tools to communicate, it connects to your AWS SSO managing all your accounts and roles but saves temporary credentials in .aws/credentials so it could address this issue for example.

Storing creds in clear text is a bad idea

**Comment by e-moshaya** [comment]
> > Hi guys, don't know if this can help in some way, in the sense is not an actual solution for the issue, BUT we have developed a project just to help with this kind of compatibility issues, it's here  on github: https://github.com/Noovolari/leapp and helps by enabling AWS SSO and third party tools to communicate, it connects to your AWS SSO managing all your accounts and roles but saves temporary credentials in .aws/credentials so it could address this issue for example.
> 
> Storing creds in clear text is a bad idea

I've just had a quick play with Leapp and it certainly looks promising for the interim. Just a few issues that needs to be ironed out before we all adopt it internally.

**Comment by dogzzdogzz** [comment]
> > Hi guys, don't know if this can help in some way, in the sense is not an actual solution for the issue, BUT we have developed a project just to help with this kind of compatibility issues, it's here  on github: https://github.com/Noovolari/leapp and helps by enabling AWS SSO and third party tools to communicate, it connects to your AWS SSO managing all your accounts and roles but saves temporary credentials in .aws/credentials so it could address this issue for example.
> 
> Storing creds in clear text is a bad idea

But better than my terraform not functional.
aws-vault still encounters credential issue when you want to run ```terraform plan``` in account A with profile A but its tfstate file is stored in the s3 bucket of account B which need to be accessed with profile B.

**Comment by FernandoMiguel** [comment]
> aws-vault still encounters credential issue when you want to run ```terraform plan``` in account A with profile A but its tfstate file is stored in the s3 bucket of account B which need to be accessed with profile B.

You should login to an account that allows you to assume roles to both accounts.
That's the correct way.
Seems you are trying to fix the wrong thing.

**Comment by willhughes-au** [comment]
>  That's the correct way.

That's not always possible, and not everyone agrees with this point of view. 

For me, we are not going to ever have that ability - I need to use multiple accounts concurrently. None of the terraform configuration is in the other accounts, and you can't assume-role between those accounts.

**Comment by FernandoMiguel** [comment]
> >  That's the correct way.
> 
> That's not always possible, and not everyone agrees with this point of view. 
> 
> For me, we are not going to ever have that ability - I need to use multiple accounts concurrently. None of the terraform configuration is in the other accounts, and you can't assume-role between those accounts. 

You have SSO right?
At least that's the topic of this thread.
Why wouldn't the use of the SSO account to assume roles be the correct way?

**Comment by willhughes-au** [comment]
I think you're talking about the other form of SSO where you'd use AssumeRole. 

This is about AWS SSO, which does not involve AssumeRole to authenticate. 

You use a specific profile to access an account and a specific permissionset

like this: 

```
[profile sso]  
sso_start_url = https://example.awsapps.com/start  
sso_region = us-east-1  
sso_account_id = xxx  
sso_role_name = AWSReadOnlyAccess  
region = ap-southeast-2  
```

For me to access resources in account A, I need profile A 
For me to access resources in account B, I need profile B. 

While technically I suppose I could then do an AssumeRole from Account A to Account B, this would require cross-account trusts/roles that permit this.  
This would then require that we duplicate the work we put into setting up PermissionSets and managing users/groups/etc in AWS SSO.

**Comment by ericvilla** [comment]
Hi @e-moshaya, as you know, as far as know AWS CLI v2 support for AWS SSO generated temporary credentials under ~/.aws/cli/cache folder which in many cases end up with "credentials not found" issue. I want to share - with people who want to solve this issue - the link to the GitHub repo of the Open Source project my team is working on. With new support to AWS SSO, it allows you to retreive - prior configuration of the Portal URL - a list of IAM Role that the AWS SSO user - you are logging in with - has access to. From this **flat** list you can generate temporary credentials with a click. Well, there are other details that you can find [here](https://github.com/Noovolari/leapp)

**Comment by prnvkbr** [comment]
I am not sure if this has been mentioned before, but this workaround worked for me:

1. On your AWS SSO landing page, click on the "Command line or programmatic access" link.
2. Copy Option 2 (contains profile, aws_access_key_id, aws_secret_access_key, aws_session_token)
3. On your local machine, create a or append to an existing `~/.aws/credentials` and paste the text selected from step 2. 
4. Use terraform

**Comment by willhughes-au** [comment]
@prnvkbr Those credentials, like all SSO credentials, are short lived.  While you can do that, others have already provided examples of tools that will also do this.

**Comment by onitake** [comment]
While the suggestions of workarounds and tools to make Terraform work with AWS SSO are appreciated, can we focus on the issue at hand, namely that the Terraform provider doesn't support it natively? Maybe by simply updating to a newer aws-go-sdk version? As suggested in https://github.com/hashicorp/terraform-provider-aws/issues/10851#issuecomment-670782765 , it seems to be supported already.

Is someone working on this already?

**Comment by anarsen** [comment]
@onitake If it's not on the [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/v3.24.0/ROADMAP.md) then I don't think so, no.

**Comment by jonasneves** [comment]
My workaround in case it helps anyone:
```
# Create access keys in aws cli cache
data "external" "caller_id" {
  program = ["aws", "sts", "get-caller-identity", "--output", "json"]
}

# Fetch credentials from aws cli cache. Requires jq pkg
data "external" "aws_creds" {
  program    = ["jq", ".Credentials", "${pathexpand("~")}/${tolist(fileset(pathexpand("~"), ".aws/cli/cache/*.json"))[0]}"]
  depends_on = [data.external.caller_id]
}

provider "aws" {
  access_key = data.external.aws_creds.result["AccessKeyId"]
  secret_key = data.external.aws_creds.result["SecretAccessKey"]
  token      = data.external.aws_creds.result["SessionToken"]
  region     = local.vars.aws_region
}
```

https://github.com/terraform-mars/terraform-multi-account/blob/main/accounts/dev/myapp/provider.tf

**Comment by jonasneves** [comment]
Another workaround in case it helps anyone:
```
# Create access keys in aws cli cache
data "external" "caller_id" {
  program = ["aws", "sts", "get-caller-identity", "--output", "json"]
}

# Fetch credentials from aws cli cache. Requires jq pkg
data "external" "aws_creds" {
  program    = ["jq", ".Credentials", "${pathexpand("~")}/${tolist(fileset(pathexpand("~"), ".aws/cli/cache/*.json"))[0]}"]
  depends_on = [data.external.caller_id]
}

provider "aws" {
  access_key = data.external.aws_creds.result["AccessKeyId"]
  secret_key = data.external.aws_creds.result["SecretAccessKey"]
  token      = data.external.aws_creds.result["SessionToken"]
  region     = local.vars.aws_region
}
```

https://github.com/terraform-mars/terraform-multi-account/blob/main/accounts/dev/myapp/provider.tf

**Comment by bflad** [comment]
AWS Go SDK version 1.37.0 now includes native SSO cached credential support: https://github.com/aws/aws-sdk-go/pull/3755

Will work on coordinating this dependency update.

**Comment by bflad** [comment]
Support for AWS Single-Sign On (SSO) cached credentials has been merged and will release with version 3.26.0 of the Terraform AWS Provider later today. When the release is available, an automated release comment will be sent to this issue.

_There are no future plans to support the AWS SSO login flow (e.g. web browser interaction) in Terraform CLI or the Terraform AWS Provider due to the complexity of operations across products. Feature requests for such functionality will be closed._

Please note that neither Terraform CLI nor the Terraform AWS Provider will initiate or perform the AWS SSO login flow. It is expected that you have already performed the SSO login flow using AWS CLI with the `aws sso login` command, or by some other mechanism before executing Terraform. More precisely, this credential handling must find a valid non-expired access token for the AWS SSO user portal URL in `~/.aws/sso/cache`. If a cached token is not found, is expired, or the file is malformed an error will be returned.

You can use configure AWS SSO credentials from the AWS shared configuration file by specifying the required keys in the profile:

```
sso_account_id
sso_region
sso_role_name
sso_start_url
```

For example, the following defines a profile "devsso" and specifies the AWS SSO parameters that defines the target account, role, sign-on portal, and the region where the user portal is located. Note: all SSO arguments must be provided, or an error will be returned.

```
[profile devsso]
sso_start_url = https:my-sso-portal.awsapps.com/start
sso_role_name = SSOReadOnlyRole
sso_region = us-east-1
sso_account_id = 123456789012
```

Additional Resources

* [Configuring the AWS CLI to use AWS Single Sign-On](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html)
* [AWS Single Sign-On User Guide](https://docs.aws.amazon.com/singlesignon/latest/userguide/what-is.html)

**Comment by onitake** [comment]
> _There are no future plans to support the AWS SSO login flow (e.g. web browser interaction) in Terraform CLI or the Terraform AWS Provider due to the complexity of operations across products. Feature requests for such functionality will be closed._

I think that's a perfectly reasonable decision. While it does require the user to install another tool besides Terraform to perform authentication, at least supporting credentials managed by other (standard) tools is probably sufficient for most users.

Thank you very much for the work!

**Comment by sergirosell** [comment]
🚀

**Comment by rajkshah14** [comment]
Now as SSO is enabled, can this documentation be updated?
https://registry.terraform.io/providers/hashicorp/aws/latest/docs#shared-credentials-file
