### ISSUE TITLE
Remove incosistence of default description

### ISSUE THREAD

**Issue by ad-m** [hashicorp/terraform-provider-aws#10868]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As noted in #10813 by @bflad defaulting descriptions to ```Managed by Terraform``` is not consistent across all resources in this provider.

I would like to discuss this topic more with the maintainers and community, so I create a new proposal feature request.

### New or Affected Resource(s)
 
This is a major change affecting a huge amount of resources. For idea about scale see #10813 and search for ```Managed by Terraform``` in codebase ( https://github.com/terraform-providers/terraform-provider-aws/search?q=%22Managed+by+Terraform%22&type=Code ).

The final list of affected resources depends on the adopted course of action.

### Potential Terraform Configuration

Blanking description or defaulting descriptions to ```Managed by Terraform```

### References

 #10813

**Comment by thatderek** [comment]
I vote blanking. 

Terraform should no more put descriptions by default than it should have a default set of tags on everything. If a call to the Create api doesn't by default create a description, then TF -- as the abstraction of that API -- shouldn't either. Any other behavior is some mixture of arbitrary and unnecessarily (even if just marginally) complex.
