### ISSUE TITLE
aws_api_gateway_method_settings: Throttling will not be enabled if limit numbers are not changed but throttling is manually disabled from console.

### ISSUE THREAD

**Issue by aramalipoor** [hashicorp/terraform-provider-aws#10909]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.6
```

### Affected Resource(s)

* aws_api_gateway_method_settings

### Terraform Configuration Files

```hcl
provider "aws" {
  region  = "eu-west-1"
}

resource "aws_api_gateway_rest_api" "test" {
  name        = "api_name"
}

resource "aws_api_gateway_deployment" "test" {
  rest_api_id = "${aws_api_gateway_rest_api.test.id}"
  stage_name  = "test"
}

resource "aws_api_gateway_stage" "test" {
  rest_api_id   = "${aws_api_gateway_rest_api.test.id}"
  deployment_id = "${aws_api_gateway_deployment.test.id}"

  stage_name = "${aws_api_gateway_deployment.test.stage_name}"
}

resource "aws_api_gateway_method_settings" "test" {
  rest_api_id = "${aws_api_gateway_rest_api.test.id}"
  stage_name  = "${aws_api_gateway_deployment.test.stage_name}"
  method_path = "*/*"

  settings {
    throttling_rate_limit = 1000
    throttling_burst_limit = 500
  }
}
```
### Problem

When API Gateway throttling is set via terraform for the first time it everything works as expected. But if you manually disable the throttling (and not change the numbers), then any subsequent terraform apply will not enable the default throttling on stage.

### Steps to Reproduce

1. `terraform apply` a stage with API Throttling configured.
2. Go to AWS console and manually disable the throttling:
![image](https://user-images.githubusercontent.com/1164589/69037573-7187a880-09e8-11ea-99f4-3c62f80de554.png)
3. `terraform apply` again.

### Expected Behavior

API Gateway throttling is enabled again.

### Actual Behavior

API Gateway throttling is still disabled.

### Notes

* If you change the throttling to a different number and terraform apply again it will update the numbers and enable throttling again.
* Logs are showing that Stage throttling is set to `-1`:
```
[DEBUG]: 2019/11/18 10:16:02 [DEBUG] Received API Gateway Stage: {
[DEBUG]:   CacheClusterEnabled: false,
[DEBUG]:   CacheClusterSize: "0.5",
[DEBUG]:   CacheClusterStatus: "NOT_AVAILABLE",
[DEBUG]:   CreatedDate: 2019-10-17 12:52:12 +0000 UTC,
[DEBUG]:   DeploymentId: "xxxxxxxx",
[DEBUG]:   LastUpdatedDate: 2019-11-18 08:51:57 +0000 UTC,
[DEBUG]:   MethodSettings: {
[DEBUG]:     */*: {
[DEBUG]:       CacheDataEncrypted: false,
[DEBUG]:       CacheTtlInSeconds: 300,
[DEBUG]:       CachingEnabled: false,
[DEBUG]:       DataTraceEnabled: false,
[DEBUG]:       LoggingLevel: "ERROR",
[DEBUG]:       MetricsEnabled: false,
[DEBUG]:       RequireAuthorizationForCacheControl: true,
[DEBUG]:       ThrottlingBurstLimit: -1,
[DEBUG]:       ThrottlingRateLimit: -1,
[DEBUG]:       UnauthorizedCacheControlHeaderStrategy: "SUCCEED_WITH_RESPONSE_HEADER"
[DEBUG]:     }
[DEBUG]:   },
[DEBUG]:   StageName: "dev",
[DEBUG]:   TracingEnabled: false,
```

**Comment by justinretzolk** [comment]
Hey @aramalipoor 👋 Thank you for taking the time to file this issue! Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?
