### ISSUE TITLE
AWS App Mesh increases default limits on several resources

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#10917]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS App Mesh has increased the default limits for a set of App Mesh resources - virtual nodes, backends, routers, and routes.

### New or Affected Resource(s)

* [`aws_appmesh_mesh`](https://www.terraform.io/docs/providers/aws/r/appmesh_mesh.html)
* [`aws_appmesh_virtual_node`](https://www.terraform.io/docs/providers/aws/r/appmesh_virtual_node.html)
* [`aws_appmesh_virtual_router`](https://www.terraform.io/docs/providers/aws/r/appmesh_virtual_router.html)

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/11/aws-app-mesh-increases-default-limits-on-several-resources/).

**Comment by sibizaestruch** [comment]
Hi, would be possible to sync the current AWS with the provider?
