### ISSUE TITLE
Amazon EBS Fast Snapshot Restore

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#10972]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

You can now enable Fast Snapshot Restore (FSR) on Amazon Elastic Block Store (EBS) snapshots, ensuring that EBS volumes restored from FSR-enabled snapshots instantly receive full provisioned performance.

### New or Affected Resource(s)

* [`aws_ebs_snapshot`](https://www.terraform.io/docs/providers/aws/r/ebs_snapshot.html)

### Potential Terraform Configuration

```hcl
resource "aws_ebs_snapshot" "example" {
  fast_snapshot_restore {
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-ebs-fast-snapshot-restore-eliminates-need-for-prewarming-data-into-volumes-created-snapshots/).
[Blog post](https://aws.amazon.com/blogs/aws/new-amazon-ebs-fast-snapshot-restore-fsr/).
[User guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-fast-snapshot-restore.html).

Requires [AWS SDK v1.25.39](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.39):
* https://github.com/terraform-providers/terraform-provider-aws/pull/10955

**Comment by blckct** [comment]
That's a cool feature!
It seems the configuration should be a simple true/false though? Maybe with an option to skip waiting for the snapshot to be optimised?

**Comment by ewbankkit** [comment]
@blckct A brief look at the API suggested to me that you would have to specify the AZs for the FSR.

**Comment by blckct** [comment]
@ewbankkit Oh, you're right.

**Comment by jleeh** [comment]
Would it make sense to have a seperate resource for this as well as a block within the snapshot resource?

Line of thinking is that FSR can be enabled and disabled independently to the snapshot creation, so users may want to enable/disable FSR in different pipelines to the snapshot creation. Especially considering the cost of FSR.

**Comment by Surajgupta9160** [comment]
Do we have any update on this feature?

**Comment by ron-spree** [comment]
Almost three years later, perhaps this has been implemented elsewhere, or is it still a wishlist/pending feature?

**Comment by nikoul** [comment]
Hello @breathingdust, happy to see this got prioritized. Any estimation on when it would be available? Happy to contribute if needed.
Thanks!

**Comment by jar-b** [comment]
### Related APIs

- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_EnableFastSnapshotRestores.html
- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeFastSnapshotRestores.html
- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DisableFastSnapshotRestores.html


### Proposed Design

As the [`CreateSnapshot` API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSnapshot.html) does not provide a mechanism to enable/disable fast snapshot restoration as part of the initial creation, I'd propose implementing this as a separate, standalone resource. The [`EnableFastSnapshotRestores` API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_EnableFastSnapshotRestores.html) can accept multiple snapshot identifiers in a single request, however, implementing this as a singular resource (single ID versus an array of IDs) aligns with the [preferred design principles](https://developer.hashicorp.com/terraform/plugin/best-practices/hashicorp-provider-design-principles#resources-should-represent-a-single-api-object) for the AWS provider. This design also prevents partial failure scenarios where some items complete successfully and others fail, leaving a complex remote state to reconcile on the following plan/apply.

```hcl
resource "aws_ebs_fast_snapshot_restore" "example" {
  availability_zone  = "us-east-2a"
  source_snapshot_id = aws_ebs_snapshot.example.id
}
```
