### ISSUE TITLE
Terraform fails to create aws_cloudwatch_metric_alarm

### ISSUE THREAD

**Issue by dcgomesbr** [hashicorp/terraform-provider-aws#10987]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14
+ provider.archive v1.2.2
+ provider.aws v2.39.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2

### Affected Resource(s)

* aws_cloudwatch_metric_alarm

### Terraform Configuration Files

```hcl
resource "aws_cloudwatch_metric_alarm" "errors_alert" {

  actions_enabled     = "true"
  alarm_description   = "Anomaly band (12 / 15 min)"
  alarm_name          = "some_alarm_name"
  comparison_operator = "GreaterThanUpperThreshold"
  datapoints_to_alarm = "1"
  evaluation_periods  = "1"
  treat_missing_data  = "breaching"
  threshold           = "0"
  tags                = "${map("Name","same_name")}"

  metric_query {
    id = "m1"

    metric {
      metric_name = "SomeMetric"
      namespace   = "SomeNamespace"
      period      = "900"
      stat        = "Maximum"

      dimensions = {
        Service = "SomeService"
      }
    }
  }

  metric_query {
    id          = "ad1"
    expression  = "ANOMALY_DETECTION_BAND(m1, 12)"
    label       = "SomeLabel"
    return_data = "true"
  }
}
```

### Debug Output

https://gist.github.com/dcgomesbr/5a47c13c8986bcd712a68ad87daae2d1

### Panic Output

None

### Expected Behavior
Create the Anomaly Band alarm.

### Actual Behavior

aws_cloudwatch_metric_alarm.errors_alert: Creating metric alarm failed: ValidationError: ComparisonOperators for ranges require ThresholdMetricId to be set
	status code: 400, request id: 01862480-0be5-4132-a5a3-63ee2e0eb4d1
### Steps to Reproduce

Plan and apply the resource above.

### Important Factoids

I could create the resource manually and import the state in some cases. In other cases, it insists in re-create the metric.query because of return_data != false and fails the same way.
### References

None

**Comment by KursLabIgor** [comment]
Almost the same for me. But in my case terraform force me to use ANOMALY_DETECTION_BAND which is no need. 

## Providers  
Terraform v0.11.14
+ provider.archive v1.3.0
+ provider.aws v2.52.0
+ provider.cloudflare v1.18.1
+ provider.github v2.9.2
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.postgresql v1.7.2
+ provider.random v2.3.1
+ provider.template v2.2.0

```terraform
resource "aws_cloudwatch_metric_alarm" "cw_alarm_ok" {
  count               = "${var.create == 1 ? 1 : 0}"
  alarm_name          = "${local.prefix_name}-${var.alarm_name}-ok"
  comparison_operator = "${var.comparison_operator_in}"
  evaluation_periods  = "${var.aws_cloudwatch_alarm_evaluation_period_scale_in}"
  threshold    = 0


  metric_query {
    id = "m1"

    metric {
      metric_name = "messages_total"
      namespace = "RABBITMQ/ANALYTICS"
      period = "60"
      stat = "Maximum"
      unit = "Count"

      dimensions = "${var.dimension}"
    }
  }
  metric_query {
    id = "m2"

    metric {
      metric_name = "deals4"
      namespace   = "RDS/ANALYTICS"
      period      = "60"
      stat        = "Maximum"
      unit        = "Count"

      dimensions = {
        env = "${var.env}"
        region = "${var.region}"
        database = "db1"
      }
    }

  }
  metric_query {
    id = "m3"

    metric {
      metric_name = "deals3"
      namespace   = "RDS/ANALYTICS"
      period      = "60"
      stat        = "Maximum"
      unit        = "Count"

      dimensions = {
        env = "${var.env}"
        region = "${var.region}"
        database = "db1"
      }
    }

  }
  metric_query {
    id = "m4"

    metric {
      metric_name = "deals2"
      namespace   = "RDS/ANALYTICS"
      period      = "60"
      stat        = "Maximum"
      unit        = "Count"

      dimensions = {
        env = "${var.env}"
        region = "${var.region}"
        database = "db1"
      }
    }

  }
  metric_query {
    id = "m5"

    metric {
      metric_name = "deals"
      namespace   = "RDS/ANALYTICS"
      period      = "60"
      stat        = "Maximum"
      unit        = "Count"

      dimensions = {
        env = "${var.env}"
        region = "${var.region}"
        database = "db1"
      }
    }

  }

  metric_query {
    id          = "e1"
    expression  = "SUM([FILL(METRICS(m2),0), FILL(METRICS(m3),0), FILL(METRICS(m4),0), FILL(METRICS(m5),0)])"
    label       = "sum deals"
  }
  metric_query {
    id          = "e2"
    expression  = "100-(m1/e1)*100"
    label       = "percent deviation"
  }
  metric_query {
    id          = "e3"
    expression  = "IF(e2<${var.threshold_ok}, 1, 0)"
    label       = "active rule alarm"
    return_data = "true"
  }


  alarm_actions       = ["${aws_appautoscaling_policy.down.arn}"]
  actions_enabled     = "${var.enable_scaling}"
  tags                = "${var.common_tags}"
}
```

Result rule e3 produce only 1 or 0 values. No need to use ANOMALY_DETECTION_BAND

## Expected 

Alarm creates 

## Actual Behavior

Updating metric alarm failed: ValidationError: ComparisonOperators for ranges require ThresholdMetricId to be set

**Comment by justinretzolk** [comment]
Hey @dcgomesbr 👋 Thank you for taking the time to file this issue! Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?
