### ISSUE TITLE
AWS DataSync Scheduling

### ISSUE THREAD

**Issue by gazoakley** [hashicorp/terraform-provider-aws#10995]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS have announced support for scheduled tasks for AWS Datasync: https://aws.amazon.com/about-aws/whats-new/2019/11/aws-datasync-adds-the-ability-to-schedule-data-transfers/

> You can now schedule AWS DataSync transfers between NFS servers, SMB servers, Amazon S3, and Amazon Elastic File System (Amazon EFS). DataSync task scheduling enables you to periodically execute a transfer task to detect and copy changes from your source storage system to the destination.

### New or Affected Resource(s)

- [`aws_datasync_task`](https://www.terraform.io/docs/providers/aws/r/datasync_task.html)

### Potential Terraform Configuration

```hcl
resource "aws_datasync_task" "example" {
  destination_location_arn = "${aws_datasync_location_s3.destination.arn}"
  name                     = "example"
  source_location_arn      = "${aws_datasync_location_nfs.source.arn}"

  schedule {
    schedule_expression = "<cron expression>"
  }
}
```

### References

* https://docs.aws.amazon.com/datasync/latest/userguide/API_CreateTask.html
* https://docs.aws.amazon.com/datasync/latest/userguide/API_UpdateTask.html
* https://docs.aws.amazon.com/datasync/latest/userguide/API_TaskSchedule.html

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.25.39](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.39):
* https://github.com/terraform-providers/terraform-provider-aws/pull/10955

**Comment by Hitesh-Agrawal** [comment]
We need this part of the terraform resource to schedule our datasync task.

**Comment by gonzaloraisin** [comment]
Voted. Could you add filtering feature to the request? Thanks

**Comment by mehfuzh** [comment]
+ 1

**Comment by bzcnsh** [comment]
shocked to find out that I cannot schedule/kick off the task with terraform, after spending hours setting up all the groundwork for EFS replication using terraform.
the ability to schedule task runs is absolutely needed.

**Comment by DrFaust92** [comment]
Ill take a crack at it.

**Comment by gazoakley** [comment]
@DrFaust92 Go for it - I don't have any plans to work on this right now 👍

**Comment by tmx-dxiao** [comment]
DataSync scheduling is a must have! The current Terraform datasync task does not support scheduling, does not support specify log level... Unbelievable!

**Comment by void0x79** [comment]
DataSync schedule is an absolute must.

**Comment by alxgruU** [comment]
yes please !!!, this is really necessary !

**Comment by smeluski** [comment]
Bumping this up! Would be really beneficial to have.

**Comment by robmoss2k** [comment]
Bump again. Having to use the AWS CLI to manually check the log level's state and schedule and update them if incorrect is painful.
