### ISSUE TITLE
Terraform plan command fails with error

### ISSUE THREAD

**Issue by vrbcntrl** [hashicorp/terraform-provider-aws#11026]
Hi I am new to terraform, I have a couple of questions related to plan command

1) why does tf tries to connect to cloud provider when we run plan?

2) why does the below 2 parameter configuration works for some resources and not for others

Skip_credentials_validation=true 
Skip_requesting_account_id=true

I’m using TF v0.12.10
aws provider v 2.33.0

Any help is appreciated 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @vrbcntrl 👋 Thank you for taking the time to open this issue! Were you able to find the answers to the questions you posed above, or are you still looking for assistance? I know it's been some time, so I figured I'd reach out before going too deep. As a heads up, questions like this are likely more suited for our [Discuss forums](https://discuss.hashicorp.com), though that wasn't around when you initially filed it! (I'm only mentioning it here in case you have questions in the future).
