### ISSUE TITLE
Data lookup for ACM certs when domain name ends with a dot.

### ISSUE THREAD

**Issue by lazzurs** [hashicorp/terraform-provider-aws#11036]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.16

### Affected Resource(s)

* aws_acm_certificate

### Terraform Configuration Files

```
data "aws_acm_certificate" "domain_cert" {
  domain      = "domain.com."
  types       = ["AMAZON_ISSUED"]
  most_recent = true
}
```

### Expected Behavior

Data lookup works

### Actual Behavior

Error: No certificate for domain "domain.com." found in this region

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Doing a data lookup for an ACM cert for domain.com works but not domain.com.

### References

* #241

**Comment by Ipswitch** [comment]
My issue is with a *.example.com lookup returning "Error: No certificate for domain "*.example.com" found in this region" when a terraform plan is run, but the certificate is listed when the aws acm list-certificates command is executed.
I want to use the data.aws_acm_certificate.example_com.arn in the load balancer section for the SSL.  This worked in 2018.
[I substitued "example.com" for a valid the valid domain and certificate in this example.]


provider "aws" {
  profile = "default"
  region  = "us-east-1"
}
 data "aws_acm_certificate" "example_com" {
  
   domain        = "*.example.com"
   types         = ["AMAZON_ISSUED"]
   key_types     = ["RSA_2048"]
}
output "SSL_Arn" {
  value = data.aws_acm_certificate.example_com.arn
    
}

**Comment by xakraz** [comment]
I agree with you @Ipswitch , I have the same issue.

Some TF code that worked in 2018 (according to the id in the tfstate) but not anymore today ...

**Comment by bikegriffith** [comment]
Data lookup for a wildcard certificate fails with this same message (currently using v0.12.31)

Created with:
```
resource "aws_acm_certificate" "main" {
  domain_name               = "*.foo.example.com"
  subject_alternative_names = ["foo.example.com"]
}
```

Then this fails:
```
data "aws_acm_certificate" "main" {
  domain = "*.foo.example.com"
  # also tried and failed, domain = "foo.example.com"
  # also tried and failed, domain = "*.foo.example.com."
  # also tried and failed, domain = "foo.example.com."
}
```

`Error: No certificate for domain "foo.example.com" found in this region`

**Comment by IgorFerretti** [comment]
> Data lookup for a wildcard certificate fails with this same message (currently using v0.12.31)
> 
> Created with:
> 
> ```
> resource "aws_acm_certificate" "main" {
>   domain_name               = "*.foo.example.com"
>   subject_alternative_names = ["foo.example.com"]
> }
> ```
> 
> Then this fails:
> 
> ```
> data "aws_acm_certificate" "main" {
>   domain = "*.foo.example.com"
>   # also tried and failed, domain = "foo.example.com"
>   # also tried and failed, domain = "*.foo.example.com."
>   # also tried and failed, domain = "foo.example.com."
> }
> ```
> 
> `Error: No certificate for domain "foo.example.com" found in this region`
> 
> EDIT: **Scratch that. I thought I had tried all of those cases, but I went back through after writing this and have it working now.**

Hi I got the same issue, how did you solved it?
Thank you

**Comment by justinretzolk** [comment]
Hey y'all 👋 Thank you for taking the time to file this issue, and for the additional discussion around it. Given that there's been a number of AWS provider releases since the issue was first filed, can anyone confirm if you're still experiencing this behavior?

**Comment by lazzurs** [comment]
Confirmed with the current version (4.2.0) of the provider this is still failing.

**Comment by reyazanwar-mf** [comment]
I was getting the same error with my wildcard domain.

```
data "aws_acm_certificate" "imported" {
  domain      = "*.mydomain.com"
  types       = ["IMPORTED"]
  most_recent = true
}
```

>  Error: no certificate for domain "*.mydomain.com" found in this Region

Then I figured out from the argument reference that by default, ACM does not return all certificate types when searching.

> [key_types](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/acm_certificate#key_types) - (Optional) List of key algorithms to filter certificates. By default, ACM does not return all certificate types when searching. See the [ACM API Reference](https://docs.aws.amazon.com/acm/latest/APIReference/API_CertificateDetail.html#ACM-Type-CertificateDetail-KeyAlgorithm) for supported key algorithms.

So, I added the optional argument **"key_types"** in the configuration and now the data source is able to retrieve the certificate.

```
data "aws_acm_certificate" "imported" {
  domain      = "*.mydomain.com"
  key_types =   ["RSA_4096"]
  types       = ["IMPORTED"]
  most_recent = true
}
```

**Comment by justinretzolk** [comment]
Hi all 👋 It looks like there's been mixed results here; can anyone confirm whether this is still a bug, or was perhaps a configuration issue in all cases?

**Comment by GreatChiefPowhatan** [comment]
Had same issue but it's working for me after specifying property `key_types` like @reyazanwar-mf said.

Terraform v1.3.6 - aws provider v4.48.0.

**Comment by ChrisJBurns** [comment]
I'm getting this issue also, I have one bit of Terraform that creates the certificate like so:

```yaml
resource "aws_acm_certificate" "wildcard_cert_ops_test" {
  certificate_authority_arn = var.acm_private_ca_arn
  domain_name = "ops-test.domain.com"
  subject_alternative_names = [
    "*.ops-test.domain.com",
    "*.ops-test.domain-dev.com"
  ]
}
```

Then another `data` resource to get it and attach it to an ALB like so:
```yaml
data "aws_acm_certificate" "wildcard_cert_tooling" {
  domain   = "*.${var.alb_domain_name}" # this renders to "*.ops-test.domain.com"
  key_types =   ["RSA_2048"]
  statuses = ["ISSUED"]
  most_recent = true
}
```

But get the error: `Error: no certificate for domain "*.ops-test.domain.com" found in this Region`

I'm not sure if this is because it doesn't retrieve certs based off their alternative names?

**Comment by justinretzolk** [comment]
Hi all 👋 It sounds like the initial issue (use of `data.aws_acm_certificate` when the domain ends in `.`) has since been resolved. With that in mind, I'm going to close this issue out. If you have other issues related to the `aws_acm_certificate` data source, or if this issue comes up again in more recent versions of the provider, please raise a new issue so that we can triage it as needed.
