### ISSUE TITLE
Subnet expansion support for NLBs

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#11045]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

You now have the flexibility to add additional subnets to an existing Network Load Balancer.

### New or Affected Resource(s)

* [`aws_lb`](https://www.terraform.io/docs/providers/aws/r/lb.html)

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

[Blog post](https://aws.amazon.com/blogs/aws/aws-load-balancer-update-lots-of-new-features-for-you/).

Requires [AWS SDK v1.25.42](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.42):
* https://github.com/terraform-providers/terraform-provider-aws/pull/10955

**Comment by LoganVS** [comment]
Hi,

The referenced PR [#10955](https://github.com/terraform-providers/terraform-provider-aws/pull/10955) is merged and released.  Has this been addressed?  Otherwise, are there any plans to address this in the near future?


Best,
Logan
