### ISSUE TITLE
Error when re-applying RDS changes that happen in a maintenance window (e.g. multi_az)

### ISSUE THREAD

**Issue by jansepke** [hashicorp/terraform-provider-aws#11050]
Terreaform AWS provider seems to have a problem with database changes that are not applied immediately but in the next maintenance window. The first run of terraform apply will correctly schedule the change (e.g. enabling multi_az) for the next maintenance window. If you now run terraform apply again it will fail with "No modifications were requested" because terraform tries again to schedule the change.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.7
+ provider.aws v2.40.0

### Affected Resource(s)

* aws_db_instance

### Terraform Configuration Files

```hcl
resource "aws_db_instance" "database" {
  multi_az                    = true // previously false 
  apply_immediately           = false
  engine                      = "postgres"
  engine_version              = "10.6"
  allow_major_version_upgrade = true
  maintenance_window          = "Mon:20:00-Mon:23:00"
  ...
}
```

### Expected Behavior

No change when running terraform apply a second time because the first run will 

### Actual Behavior

Error: Error modifying DB Instance XYZ: InvalidParameterCombination: No modifications were requested
	status code: 400, request id: ...

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

**Comment by justinretzolk** [comment]
Hey @jansepke 👋 Thank you for taking the time to file this issue. Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?

**Comment by jansepke** [comment]
Hey @justinretzolk, the codebase has evolved in the last 2 years, so I am not able to reproduce this issue.
