### ISSUE TITLE
Provider change (region) in resource doesn't destroy the initially created one

### ISSUE THREAD

**Issue by dimisjim** [hashicorp/terraform-provider-aws#11052]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.11.13

### Affected Resource(s)

aws_efs_file_system,
probably same result for any region specific aws resource

### Expected Behavior

After changing the provider argument of a tf resource, the previously created resource should be deleted, not just forgotten by terraform

### Actual Behavior

See above.

**Comment by justinretzolk** [comment]
Hey @dimisjim 👋 Thank you for taking the time to file this issue! Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?

**Comment by dimisjim** [comment]
Hey @justinretzolk

I think there's no way for me to reproduce this issue, given also that I have moved on with the latest, 1.x.x tf versions. 

Thus it makes sense to close this issue :+1:
