### ISSUE TITLE
resource/aws_s3_bucket: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by augustine-urolime** [hashicorp/terraform-provider-aws#11064]
2019-11-29T04:48:44.201Z [DEBUG] plugin.terraform-provider-aws_v2.19.0_x4: 2019/11/29 04:48:44 [DEBUG] [aws-sdk-go] 
2019-11-29T04:48:44.201Z [DEBUG] plugin.terraform-provider-aws_v2.19.0_x4: 2019/11/29 04:48:44 [DEBUG] [aws-sdk-go] DEBUG: Validate Response s3/HeadBucket failed, attempt 0/25, error NotFoun
d: Not Found
2019-11-29T04:48:44.201Z [DEBUG] plugin.terraform-provider-aws_v2.19.0_x4:      status code: 404, request id: 25DD7204967332EA, host id: DscRqp364O9rVUZcxJarUNoIeqcUouW722cAXZ2oF3w287K4ABUEQ
pY2q5SkeW32cpayJFbv8I0=
2019-11-29T04:48:44.201Z [DEBUG] plugin.terraform-provider-aws_v2.19.0_x4: 2019/11/29 04:48:44 [WARN] S3 Bucket (xxxxx) not found, error code (404)
2019/11/29 04:48:44 [DEBUG] module.s3.aws_s3_bucket.xxxxx: apply errored, but we're indicating that via the Error pointer rather than returning it: Provider produced inconsistent result after apply: When applying changes to module.s3.aws_s3_bucket.im-etickets-qa, provider "aws" produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
2019/11/29 04:48:44 [TRACE] module.s3: eval: *terraform.EvalMaybeTainted
2019/11/29 04:48:44 [TRACE] EvalMaybeTainted: module.s3.aws_s3_bucket.xxx encountered an error during creation, so it is now marked as tainted
2019/11/29 04:48:44 [ERROR] module.s3: eval: *terraform.EvalApplyPost, err: Provider produced inconsistent result after apply: When applying changes to module.s3.aws_s3_bucket.xxxx, provider "aws" produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
2019/11/29 04:48:44 [ERROR] module.s3: eval: *terraform.EvalSequence, err: Provider produced inconsistent result after apply: When applying changes to module.s3.aws_s3_bucket.xxxxx, provider "aws" produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by ewbankkit** [comment]
Similar:
* https://github.com/terraform-providers/terraform-provider-aws/issues/9725

**Comment by bflad** [comment]
While the code fix will be similar in nature to the fix for #9725, we'll track this separately as the different resource will require a change in a different part of the codebase. We currently retry automatically on resource creation for API error codes, however the `HeadBucket` (and `HeadObject` in the other issue) API calls need to be retried on the 404 HTTP status code for new resources.

**Comment by augustine-urolime** [comment]
Actually the code only does creation of 100's of buckets only without any other further dependencies.

**Comment by bflad** [comment]
This issue should have been resolved awhile ago with version 2.48.0 of the Terraform AWS Provider. There are some minor adjustments we can make to the read logic that would make this particular error impossible to occur as-is, but the read-after-create retry logic introduced in that earlier version should cover the issue enough to prevent it.

If you are still having trouble with the `aws_s3_bucket` resource and this error on more recent versions of the Terraform AWS Provider, please open a new bug report filling in the issue template and we can take a fresh look. 👍
