### ISSUE TITLE
Support Amazon EventBridge Schema Registry

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#11088]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon EventBridge schema registry and discovery announced - **In preview**.

### New or Affected Resource(s)

It looks like an initial set of resources could be:

* `aws_schemas_discoverer`
* `aws_schemas_registry`
* `aws_schemas_schema`

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/12/introducing-amazon-eventbridge-schema-registry-now-in-preview/).
[Blog post](https://aws.amazon.com/blogs/compute/introducing-amazon-eventbridge-schema-registry-and-discovery-in-preview/).
[User guide](https://docs.aws.amazon.com/eventbridge/latest/userguide/eventbridge-schemas.html).
[API reference](https://docs.aws.amazon.com/eventbridge/latest/schema-reference/what-is-eventbridge-schemas.html).

Requires [AWS SDK v1.25.44](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.44):
* https://github.com/terraform-providers/terraform-provider-aws/pull/11083

**Comment by abonawit** [comment]
Has there been any movement on this work for eventbridge schemas?

**Comment by jordanfinners** [comment]
Hi, I've added a [pull request](https://github.com/hashicorp/terraform-provider-aws/pull/19100) to support all these, please can you give the pull request a 👍 to help get it prioritised
