### ISSUE TITLE
out of the box, this is not working

### ISSUE THREAD

**Issue by tgtwm1github** [hashicorp/terraform-provider-aws#11099]
ec2 Instance creation is ok

but ssh into instance is not working.

**Comment by anarsen** [comment]
@tgtwm1github What does your Terraform configuration look like?

**Comment by tgtwm1github** [comment]
There is no additional setup... I downloaded the example for two tier setup
and run....
git clone https://github.com/terraform-providers/terraform-provider-aws.git

path for my example: $whereever-it-was-downloaded/examples/two-tier/

The default configuration main.tf has an ec2 creation followed by logging
into the server and install and start nginx....

When I run terraform apply, it prompts for the keypair name and the "pub"
file location...

Here are the sequence of events and the catch 22 I see...

1 If I provide a keypair name that already exists in AWS, it errors saying
that the keypair exists...
   so If I let it create a key pair, the pub file for that key will not
exist so the terraform apply will not even start...

2. So, I create a keypair, download the pem file and run ssh-keygen -y -f
and create a .pub file with the output.

Then, I run terraform apply, this time, when prompted for keypair name, I
give a name that does not exist in AWS ....
Then when prompted for the location/path of the "pub" file, I provide the
location where I create it from the step 2...
Now , the ec2 instance is created but it fails to login to the instance to
install nginx...

The only change I made is I have updated the main.tf to change from
"Ubuntu" to "ec2-user"....


I would like to mention that once the instance is created, I can from my
client,

do ssh -i pem-file ec2-user@aws-ec2-instance it works.
do ssh -i pub-file ec2-user@aws-ec2-instance it works.



Thanks,
Ganesh

mobile origin; e&oe

**Comment by joemsak** [comment]
Please try my comment and let me know https://github.com/terraform-providers/terraform-provider-aws/issues/1493#issuecomment-623280385 - take note of the edit to do the public key as a sensitive variable as well (yes you can copy paste those entire keys into the value for the variables)

**Comment by justinretzolk** [comment]
Hey @tgtwm1github 👋 Thank you for taking the time to file this issue. Were you able to get your configuration working after reviewing the additional information from the comments above?
