### ISSUE TITLE
Support AWS IAM Access Analyzer

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#11102]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

IAM Access Analyzer announced.

### New or Affected Resource(s)

It looks like an initial set of resources could be:

- [x] `aws_accessanalyzer_analyzer`
- [x] `aws_accessanalyzer_organization_admin_account `
- [x] `aws_accessanalyzer_archive_rule`

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/12/introducing-aws-identity-and-access-management-access-analyzer/).
[Blog post](https://aws.amazon.com/blogs/aws/identify-unintended-resource-access-with-aws-identity-and-access-management-iam-access-analyzer/).
[User guide](https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html).
[API reference](https://docs.aws.amazon.com/access-analyzer/latest/APIReference/Welcome.html).

Requires [AWS SDK v1.25.45](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.45):
* https://github.com/terraform-providers/terraform-provider-aws/pull/11097

**Comment by bflad** [comment]
Submitted the `aws_accessanalyzer_analyzer` resource: https://github.com/terraform-providers/terraform-provider-aws/pull/11169 🎉 

I agree with keeping the archive rules as a separate resource even though the analyzers do support inline archive rules as we do not need more security group vs security group rule confusion/trouble. 😄

**Comment by lorengordon** [comment]
I know I always appreciate having an option to enforce an exclusive configuration of something, where terraform removes anything not specified in the config... Not sure how that would work with separate resources, but maybe a consideration.

**Comment by bflad** [comment]
@lorengordon noted! We could not enforce exclusive management given Terraform's available functionality. We typically will want to lean towards being flexible for organizational/workflow boundaries (e.g. where rules may get defined in downstream Terraform modules with their associated resources) with API implementations that allow it, but we can certainly support both the separate and inline methods if its desirable for the community, by including the warnings about incompatibilities for managing them multiple ways.

**Comment by lorengordon** [comment]
I was thinking the rule resource could be plural, `aws_accessanalyzer_archive_rule`, with a flag to mark the config as exclusive, if keeping the resource separate were strongly desired...

**Comment by bflad** [comment]
Support for the new `aws_accessanalyzer_analyzer` resource has been merged and will release with version 2.43.0 of the Terraform AWS Provider, Thursday this week. 👍

**Comment by sutharshan-sharma** [comment]
@ewbankkit  @bflad  Any example usage available for aws_accessanalyzer_archive_rule resource in Terraform ?

**Comment by christophetd** [comment]
It would also be very useful to be able to create delegated administrators for Access Analyzer from terraform, c.f. https://aws.amazon.com/blogs/aws/new-use-aws-iam-access-analyzer-in-aws-organizations/

**Comment by ina-stoyanova** [comment]
Hey all - thank you for adding the IAM Access Analyzer. 

I was wondering (_if my understanding is correct_, the `aws_accessanalyzer_archive_rule` is not _yet_ a supported resource), then what do people recommend or have found themselves doing to add these rules? 

Thanks in advance!

**Comment by Sutharshansharma** [comment]
@ina-stoyanova  you can do it via aws_cli command via shell script with for loop to add archive rules + you can call that shell script with Terraform null resource.

**Comment by ina-stoyanova** [comment]
Thank you @Sutharshansharma 👍

**Comment by dpowley** [comment]
Adding another vote for supporting the `aws_accessanalyzer_organization_admin_account`. Similar to what has already been implemented for GuardDuty and Firewall Manager.

**Comment by mwarkentin** [comment]
Access Analyzer recently released some new functionality to analyze AWS IAM policies: https://aws.amazon.com/blogs/aws/iam-access-analyzer-update-policy-validation/

It would be interesting if this API could be wired into and exposed during plans for the `aws_iam_policy` resource.
