### ISSUE TITLE
Transit Gateway multicast support

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#11120]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Transit Gateway now supports routing internet protocol (IP) multicast traffic between attached Amazon Virtual Private Cloud (VPC) connections.

### New or Affected Resource(s)

* `aws_ec2_transit_gateway_multicast_domain`

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/12/run-ip-multicast-workloads-aws-transit-gateway/).
[Blog post](https://aws.amazon.com/blogs/aws/aws-transit-gateway-adds-multicast-and-inter-regional-peering/).

Requires [AWS SDK v1.25.46](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.46):
* https://github.com/terraform-providers/terraform-provider-aws/pull/11116

**Comment by windy1** [comment]
Here is an example / use case configuration: https://gist.github.com/windy1/61b0b0ec4e21748cf9dfa1b5f110ee25

Doesn't seem like it would be that much work, but I've never contributed to Terraform before. Be happy to look into it if someone else doesn't pick this up soon.

**Comment by windy1** [comment]
If anyone is interested in this feature, I believe my PR is ready for review now. https://github.com/terraform-providers/terraform-provider-aws/pull/11474
