### ISSUE TITLE
New Feature: AWS Network Manager for Transit Gateways

### ISSUE THREAD

**Issue by chrisdewar** [hashicorp/terraform-provider-aws#11132]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A new "global network" product has been released by AWS (see references), I would like to be able to use it in terraform.

### New or Affected Resource(s)

Suggested resource names (not wedded to any of them):

* aws_networkmanager_global_network
* aws_networkmanager_site
* aws_networkmanager_link
* aws_networkmanager_device
* aws_networkmanager_transit_gateway_registration

### Potential Terraform Configuration

```hcl
resource "aws_global_network" "network" {
  description = "this is a test network"
  tags = {
    Name = "test-network"
  }
}

resource "aws_globalnetwork_transit_gateway_registration" "transit_gateway" {
  network = "${aws_networkmanager_global_network.network}"
  transit_gateway = "${aws_ec2_transit_gateway.gateway.id}"
}
```

### References

* https://aws.amazon.com/blogs/aws/new-for-aws-transit-gateway-build-global-networks-and-centralize-monitoring-using-network-manager/
* https://docs.aws.amazon.com/networkmanager/latest/APIReference/API_GlobalNetwork.html

**Comment by Omarimcblack** [comment]
I will be working on this along with @j-nix, we propose the following updated resource list:

- aws_networkmanager_global_network
- aws_networkmanager_site
- aws_networkmanager_link
- aws_networkmanager_device
- aws_networkmanager_transit_gateway_registration
- aws_networkmanager_customer_gateway_association
- aws_networkmanager_link_association

**Comment by reegnz** [comment]
@Omarimcblack any progress on the new proposed resources? I am really excited about your work!

**Comment by Fuuzetsu** [comment]
I believe the work is on-going at https://github.com/terraform-providers/terraform-provider-aws/pull/13251

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

**Comment by Omarimcblack** [comment]
> Hi all 👋 Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

Thanks @ewbankkit for jumping in on my PR https://github.com/hashicorp/terraform-provider-aws/pull/13251 help has been much appreciated

**Comment by ewbankkit** [comment]
Renamed this issue to _AWS Network Manager for Transit Gateways_ from _Global Network_ as only the [transit gateway](https://docs.aws.amazon.com/vpc/latest/tgwnm/what-is-network-manager.html) functionality of AWS Network Manager will be implemented, NOT the currently in-preview [Cloud WAN](https://docs.aws.amazon.com/vpc/latest/cloudwan/cloudwan-concepts.html) functionality.
