### ISSUE TITLE
CloudWatch Synthetics

### ISSUE THREAD

**Issue by acdha** [hashicorp/terraform-provider-aws#11145]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

CloudWatch Synthetics was released in an open preview recently to test public websites or API endpoints. Since much of the underlying service is based on Lambda running headless Chrome this shouldn't be an inordinate amount of work but the additional API to integrate it into CloudWatch would be useful to have when this is released since the nature of the service would make it a natural fit for deployment in multiple regions.

### References

* https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries.html
* https://aws.amazon.com/about-aws/whats-new/2019/11/introducing-amazon-cloudwatch-synthetics-preview/

**Comment by ewbankkit** [comment]
Amazon CloudWatch Synthetics is now generally available:

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-cloudwatch-synthetics-generally-available/)
* [Blog post](https://aws.amazon.com/blogs/aws/new-use-cloudwatch-synthetics-to-monitor-sites-api-endpoints-web-workflows-and-more/)

Support in the API since [AWS SDK v1.30.10](https://github.com/aws/aws-sdk-go/releases/tag/v1.30.10):

* https://github.com/terraform-providers/terraform-provider-aws/pull/12715

**Comment by brucedvgw** [comment]
Any update on this one?

**Comment by DrFaust92** [comment]
WIP #13140, hopefully ill have something working very soon.

**Comment by MaksymBilenko** [comment]
Hello, if you don't want to wait for this feature to be merged and you ok to use custom provider, then you might use standalone provider https://github.com/MaksymBilenko/terraform-provider-aws-synthetics

**Comment by rayswilling** [comment]
Hi  @DrFaust92 @acdha 
1. Has synthetics been released in the new AWS Provider (version 3?) 
2. I cant see it in the provider version overviews :) 
3. If not - is there a roll out plan?

**Comment by tdmalone** [comment]
@rayswilling The PR is in progress - https://github.com/terraform-providers/terraform-provider-aws/pull/13140

**Comment by brucedvgw** [comment]
Any update on how this resource is progressing?

**Comment by olu-olajide** [comment]
Hi, I'm asking the same question on if synthetics is terraformable?

**Comment by smailc** [comment]
Hi, any update on this implementation? Thanks

**Comment by lloyd-cw** [comment]
Any update on when this will be merged into the aws provider? The temp terraform-provider-aws-synthetics by MaksymBilenko but is limited (can't get tags working).

**Comment by ewbankkit** [comment]
Addressing this issue is on the quarter's [Roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md#cloudwatch-synthetics).

**Comment by caleb15** [comment]
Link to docs of new resource: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/synthetics_canary
