### ISSUE TITLE
AWS DataSync Filter

### ISSUE THREAD

**Issue by Hitesh-Agrawal** [hashicorp/terraform-provider-aws#11153]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
AWS have  support for filtering data for datasync tasks for AWS Datasync:
https://aws.amazon.com/about-aws/whats-new/2019/05/aws-datasync-adds-filtering-for-data-transfers/

https://docs.aws.amazon.com/datasync/latest/userguide/filtering.html
Filtering the Data Transferred by AWS DataSync
When you transfer data from your source to your destination location, you can apply filters to transfer only a subset of the files in your source location. For example, if your source location includes temporary files that end with .tmp, you can create an exclude filter that ensures that these files are not transferred to the destination.

Filtering is an optional configuration to specify if you want to transfer a subset of your source files. You can leave the filter configuration empty if you want all files from the source to be transferred to the destination location.

### New or Affected Resource(s)

* [aws_datasync_task](https://www.terraform.io/docs/providers/aws/r/datasync_task.html)

### Potential Terraform Configuration

```hcl
resource "aws_datasync_task" "example" {
  destination_location_arn = "${aws_datasync_location_s3.destination.arn}"
  name                     = "example"
  source_location_arn      = "${aws_datasync_location_nfs.source.arn}"

  filter_exclude {
    filter_expression = "<filter expression>"
  }
}
```

### References

- https://docs.aws.amazon.com/datasync/latest/userguide/API_CreateTask.html
- https://docs.aws.amazon.com/datasync/latest/userguide/API_UpdateTask.html
- https://docs.aws.amazon.com/datasync/latest/userguide/API_TaskSchedule.html

**Comment by khateeb15** [comment]
I'd suggest renaming the issue to AWS DataSync Task Filter.

**Comment by gazoakley** [comment]
Planning to work on
