### ISSUE TITLE
Document for `aws_instance` is incorrect

### ISSUE THREAD

**Issue by waneal** [hashicorp/terraform-provider-aws#11155]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

- terraform
  - v0.12.16
- aws_provider
  - v2.41.0

### Affected Resource(s)

* aws_instance
  * root_block_device
  * Probably ebs_block_device, too

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

In this [PR](https://github.com/terraform-providers/terraform-provider-aws/issues/9668), we must use `kms_key_id` , but document has not fixed yet. 
https://www.terraform.io/docs/providers/aws/d/instance.html#kms_key_arn

### Steps to Reproduce

1. `terraform apply`

### References

* #9668

**Comment by justinretzolk** [comment]
👋 Thank you for taking the time to file this issue. I took a look over #9668 and it looks like it was referring to the `kms_key_arn`/`kms_key_id` value for block devices when using the `aws_instance` resource. In reviewing that document, it has been updated to appropriately reflect [`kms_key_id`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#kms_key_id). As such, we'll close this issue.
