### ISSUE TITLE
Premature assessment of attributes on dependent resource change (aws_s3_bucket)

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform-provider-aws#1117]
Terraform 0.9.8

I have a bucket:

```
resource "aws_s3_bucket" "mybucket" {
    bucket = "mybucket.myexample.com"
    acl    = "private"
}
```

This bucket exists, and is planned and applied in the statefile (crucial fact)

Now I decide to turn the bucket into a static website bucket. So I modify the resource, and add some route53 records:

```
resource "aws_s3_bucket" "mybucket" {
    bucket = "mybucket.myexample.com"
    acl    = "private"
    policy = "${file("./some_bucket_policy.json")}"
    versioning {
        enabled = true
    }
    website {
        index_document = "index.html"
        error_document = "error.html"
    }
}

resource "aws_route53_record" "mybucket_public" {
    zone_id = "${data.aws_route53_zone.myexample.zone_id}"
    name    = "mybucket"
    type    = "A"

    alias {
        name                   = "${aws_s3_bucket.mybucket.website_domain}"
        zone_id                = "${aws_s3_bucket.mybucket.hosted_zone_id}"
        evaluate_target_health = false
    }
}
```

Now I try and plan and apply the changes together - the plan works, the apply does not:

```
Error running plan: 1 error(s) occurred:

* aws_route53_record.mybucket_public: 1 error(s) occurred:

* aws_route53_record.mybucket_public: Resource 'aws_s3_bucket.mybucket' does not have attribute 'website_domain' for variable 'aws_s3_bucket.mybucket.website_domain'
```

Terraform is incorrectly assessing that there is no website_domain, when one exists in the new resource file, and after apply would exist in the statefile too. 

Terraform is instead looking in the statefile and seeing that the current bucket has no website_domain attribute.

It should be clever enough to realise that the new resource contains website information, so getting the dependency right, after applying the bucket change, the bucket resource would have the required website_domain attribute. 

Everything is still available to be applied if you plan/apply twice - first just including the bucket changes, and then including the route53 resource changes. However the whole thing should just work .

**Comment by amireldor** [comment]
Is this bug still open even though merged? I get the exact same error.

    Terraform v0.11.3
    + provider.aws v1.10.0

**Comment by bflad** [comment]
As far as I know, nothing has been merged into this repository surrounding this issue. Github is showing another repository PR (mentioning this issue) as merged.

Very briefly looking above, this might be solved a `CustomizeDiff` function on the `aws_s3_bucket` resource that marks the `website_domain` attribute as computed if website is being added.

**Comment by ronaldtse** [comment]
I'm seeing the exact error as well. Is this going to be fixed soon? Thanks.

**Comment by ronaldtse** [comment]
The simple workaround is to give the explicit URL instead of using `website_domain`:

```
data "aws_region" "main" {
  provider = "aws"
}

value = "${var.fqdn}.s3-website-${data.aws_region.main.name}.amazonaws.com"
```
