### ISSUE TITLE
Feature request: SES configuration set delivery options

### ISSUE THREAD

**Issue by logsnitch** [hashicorp/terraform-provider-aws#11197]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi, I'd like to request a new resource for creating Amazon SES Configuration Sets "DeliveryOptions": https://docs.aws.amazon.com/ses/latest/APIReference/API_DeliveryOptions.html

### New or Affected Resource(s)

aws_ses_configuration_set

### Potential Terraform Configuration

```hcl
resource "aws_ses_configuration_set" "enforce-tls" {
  name = "enforce-tls"

  delivery_options {
    tls_policy = "Require"
  }
}
```

### References

- https://docs.aws.amazon.com/ses/latest/APIReference/API_DeliveryOptions.html

**Comment by marcjay** [comment]
Hi, is this on any roadmap to address or would a PR for this feature be welcomed? This is a feature we'd like to see implemented as well

**Comment by marcjay** [comment]
I've raised #11600 based on the syntax above. Happy to change it to support a different syntax if there's a preference.

**Comment by marcjay** [comment]
Hi @bflad please could I get your view on the `delivery_options` syntax here: https://github.com/terraform-providers/terraform-provider-aws/issues/11197#issue-534581270 ? If you would like it to be something different I'd be happy to update the [PR](https://github.com/terraform-providers/terraform-provider-aws/pull/11600). Many thanks

**Comment by adamdecaf** [comment]
I added this as a new resource which also has `sending_pool` for https://github.com/terraform-providers/terraform-provider-aws/issues/10703. If https://github.com/terraform-providers/terraform-provider-aws/pull/11600 is merged I can add `sending_pool` on the existing `aws_ses_configuration_set` resource for my change. 

My Change: https://github.com/adamdecaf/terraform-provider-aws/commit/16045d0910a856ab1df813bfef5c5c422166d372

**Comment by l13t** [comment]
Hi there. It would be amazing to have possibility to configure TLS policy. We're now configuring SES in our infra and need to have a hack to set this option.

**Comment by adamdecaf** [comment]
I never got a reply on this repo for the original PR's, but my fork has been used in production. I'd dust off the PR's if there's a chance they'll get merged.

**Comment by marcjay** [comment]
> Hi there. It would be amazing to have possibility to configure TLS policy. We're now configuring SES in our infra and need to have a hack to set this option.

@l13t if you add a 👍 to #11600, that I think is the only way to encourage the PR to get merged, I've given up trying to nudge people

**Comment by l13t** [comment]
@marcjay already did it and asked colleagues :)
