### ISSUE TITLE
Beanstalk subnets settings are always applied even when no changes

### ISSUE THREAD

**Issue by gnouts** [hashicorp/terraform-provider-aws#11217]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
> terraform -v
Terraform v0.12.17
+ provider.aws v2.41.0
```

### Affected Resource(s)

* ElasticBeanstalk

### Terraform Configuration Files

```hcl
locals {
  profile = "default"
  region = "eu-west-3"
  cidr = "10.0.0.0/16"
}
provider "aws" {
  profile    = local.profile
  region     = local.region
}
# this create a VPC with 2 subnets : one pulic+IGW, one private. they communicate through NAT.
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"
  name = "TEST"
  cidr = local.cidr
  azs = ["${local.region}a"]
  public_subnets  = [cidrsubnet(local.cidr,8,1)]
  private_subnets = [cidrsubnet(local.cidr,8,101)]
  enable_nat_gateway = true
  single_nat_gateway = true
  enable_vpn_gateway = false
}
data "aws_iam_instance_profile" "default" {
  name = "aws-elasticbeanstalk-ec2-role"
}

resource "aws_elastic_beanstalk_application" "backend" {
  name        = "TEST"
  description = ""
}

resource "aws_elastic_beanstalk_environment" "backend" {
  name                = "TEST"
  application         = aws_elastic_beanstalk_application.backend.name
  solution_stack_name = "64bit Amazon Linux 2018.03 v2.12.17 running Docker 18.06.1-ce"

  setting {
    resource  = ""
    namespace = "aws:ec2:vpc"
    name      = "VPCId"
    value     = module.vpc.vpc_id
  }
  setting {
    resource  = ""
    namespace = "aws:ec2:vpc"
    name      = "subnets"
    value     = join(",", module.vpc.public_subnets)
  }
  setting {
    resource  = ""
    namespace = "aws:ec2:vpc"
    name      = "elbsubnets"
    value     = join(",", module.vpc.private_subnets)
  }
  setting {
    resource  = ""
    namespace = "aws:autoscaling:launchconfiguration"
    name = "IamInstanceProfile"
    value = data.aws_iam_instance_profile.default.name
  }
}
```

### Debug Output

https://gist.github.com/gnouts/f85e93ad66fe35a9b684ccecf614818c

### Expected Behavior

Running this twice. Second time should not produce any chages.

### Actual Behavior

Terraform update Beanstalk `elbsubnets` and `subnets` on every run.

### Steps to Reproduce

1. Copy the tf paste above.
2. Run `terraform init` because I use vpc module for convenience.
3. `terraform apply`

### Important Factoids

In my VPC, I create a public subnet that contains the Beanstalk's ELB and a private subnet that contains the Beanstalk's EC2.

**Comment by blckct** [comment]
And what is the plan? AWS probably returns them sorted so you could try adding  `sort()`

**Comment by gnouts** [comment]
@blckct Thanks for your answer, I thought about that too at first but when you supply only one AZ (in the module vpc `azs`), therefore only one subnet is created and the problem still happen.
I edited the debug gist to include the plan (issue is on the last two settings at the end).

**Comment by jeremy-w** [comment]
@blckct yes, i found i needed to sort the subnets before joining with `,`, and for instance types, i found i needed to join them space-separated to agree with AWS's formatting and avoid spurious diffs.

@gnouts reviewing your gist, i see that AWS is canonicalizing the capitalization of the subnets and elbsubnets setting names. if you match those, i expect you will not find any diffs. compare:

aws capitalizes as "Subnets": https://gist.github.com/gnouts/f85e93ad66fe35a9b684ccecf614818c#file-readable_plan-txt-L768-L773

while you have supplied "subnets": https://gist.github.com/gnouts/f85e93ad66fe35a9b684ccecf614818c#file-readable_plan-txt-L887-L891

the canonical spelling appears as documented in the "General options" reference: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-ec2vpc

it would be awesome if the provider handled the jiggery-pokery needed to agree on what to call & how to order lists with AWS on our behalf, for sure.
and similarly with ELBSubnets vs elbsubnets.

**Comment by justinretzolk** [comment]
Hey y'all 👋 Thank you for taking the time to file this issue, and for the additional discussion around it! Given the information above and that there's been a number of AWS provider releases since the last update, can anyone confirm whether you're still experiencing this behavior?
