### ISSUE TITLE
Hi guys, I'm trying to create a s3_bucket_notification to sqs but it fails with (Unable to validate the following destination configurations) error.

### ISSUE THREAD

**Issue by manherfo** [hashicorp/terraform-provider-aws#11219]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.16
+ provider.aws v2.41.0

Your version of Terraform is out of date! The latest version
is 0.12.17. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

* aws_s3_bucket_notification

### Terraform Configuration Files

provider "aws" {
  region  = var.aws_region
  profile = "sandbox"
}
variable "aws_region" {
  default = "us-east-1"
}
module "test_events" {
  ....
  this is the queue
}
variable "environment" {
  default = "testing"
}
module "test_s3_bucket" {
  source = "../../../storage/s3"
  bucket_name = "testmanherfowikiwiki"
  environment = var.environment
}
module "test_bucket_notification" {
  source = "../../../storage/s3_bucket_notification"
  bucket_id = module.test_s3_bucket.bucket_id
  queue_notification = true
  queue_arn = module.test_events.this_sqs_queue_arn
  bucket = module.test_s3_bucket.bucket
}

---------------------
this is the module I created...

resource "aws_s3_bucket_notification" "bucket_notification" {
  bucket = var.bucket_id
  depends_on = [var.bucket]
  dynamic "topic" {
    for_each = var.sns_notification == true ? [1] : []
    content {
      topic_arn     = var.topic_arn
      events        = ["s3:ObjectCreated:*"]
    }
  }
  dynamic "lambda_function" {
    for_each = var.lambda_notification == true ? [1] : []
    content {
      lambda_function_arn      = var.lambda_function_arn
      events        = ["s3:ObjectCreated:*"]
    }
  }
  dynamic "queue" {
    for_each = var.queue_notification == true ? [1] : []
    content {
      queue_arn     = var.queue_arn
      events        = ["s3:ObjectCreated:*"]
    }
  }
}

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Error: Error putting S3 notification configuration: InvalidArgument: Unable to validate the following destination configurations
	status code: 400, request id:, host id:

  on ../../../storage/s3_bucket_notification/main.tf line 1, in resource "aws_s3_bucket_notification" "bucket_notification":
   1: resource "aws_s3_bucket_notification" "bucket_notification" {

### Expected Behavior
it should create an s3 with a trigger to sqs

### Actual Behavior
It doesn't create the th notification

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by manherfo** [comment]
It is the same error linked with this closed issue https://github.com/terraform-providers/terraform-provider-aws/issues/7021 . (this issue was closed because of lack of response).

**Comment by assertnotnull** [comment]
I must say this is a blocker I think. I have an S3 bucket that won't trigger my lambda because of this error.

**Comment by assertnotnull** [comment]
The error is generic but I got it working. The lambda was lacking policy about S3.

**Comment by justinretzolk** [comment]
Hey y'all 👋 Thank you for taking the time to file this issue. Given that there's been a number of AWS provider releases since the last update, can anyone confirm whether you're still experiencing this behavior?

**Comment by MrCoffey** [comment]
I have the same error using version 4.0.0 of the AWS provider.


```
terraform -v

Terraform v1.0.2 on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.0.0
```

My configuration:

```
resource "aws_s3_bucket" "bucket_name" {
  bucket = "bucket_name"
  tags   = var.tags
}


resource "aws_sqs_queue" "q" {
  name                              = "service-queue"
  kms_master_key_id                 = var.kms_key

  tags   = var.tags
}


resource "aws_sqs_queue_policy" "q" {
  queue_url = aws_sqs_queue.q.id

  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": "*",
      "Action": "sqs:SendMessage",
      "Resource": "${aws_sqs_queue.q.arn}",
      "Condition": {
        "ArnLike": { "aws:SourceArn": "${aws_s3_bucket.bucket_name.arn}" }
      }
    },
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "s3.amazonaws.com"
      },
      "Action": [
        "kms:GenerateDataKey",
        "kms:Decrypt"
      ],
      "Resource": "*"
    }
  ]
}
POLICY
}


resource "aws_s3_bucket_notification" "notification" {
  bucket = aws_s3_bucket.bucket_name.id

  queue {
    id                    = "id-avro-sqs"
    queue_arn     = aws_sqs_queue.q.arn
    filter_prefix   = "prefix/"
    events = [
      "s3:ObjectCreated:*"
    ]
  }
  
  depends_on = [
    aws_sqs_queue.q
  ]
}
```

I receive the following error:

```
aws_s3_bucket_notification.export_notification: Creating...
╷
│ Error: error putting S3 Bucket Notification Configuration: InvalidArgument: Unable to validate the following destination configurations
│       status code: 400, request id: , host id: 
│ 
│   with aws_s3_bucket_notification.notification,
│   on main.tf line 181, in resource "aws_s3_bucket_notification" "notification":
│  181: resource "aws_s3_bucket_notification" "notification" {
│ 
╵
```

**Comment by MrCoffey** [comment]
In my case, I was able to resolve the issue by removing the `id` in the `queue` definition, then I edit it by adding the requested name.

```
resource "aws_s3_bucket_notification" "notification" {
  bucket = aws_s3_bucket.bucket_name.id

  queue {
  #  id                    = "id-avro-sqs"
    queue_arn     = aws_sqs_queue.q.arn
    filter_prefix   = "prefix/"
    events = [
      "s3:ObjectCreated:*"
    ]
  }
  
  depends_on = [
    aws_sqs_queue.q
  ]
}
```

**Comment by MrCoffey** [comment]
Months after the error persists, I'm using version `4.44.0` of the provider this time. At least in my case looks like this happens every time I provision the bucket_notification for the first time. Removing the id didn't help this time.

**Comment by c240amg** [comment]
Same sort of issue trying to create a SNS notification on an S3 bucket.
Bucket is in us-west-2, SNS is in eu-west-1
`resource "aws_s3_bucket_notification" "tfstate_bucket_notification" {
  depends_on = [data.aws_sns_topic.platform_team]
  provider   = aws.default

  bucket = aws_s3_bucket.tfstate.id

  topic {
    topic_arn = data.aws_sns_topic.platform_team.arn
    events    = ["s3:LifecycleTransition"]
  }
}`
