### ISSUE TITLE
ECS clusters created by terraform do not have capacity provider options

### ISSUE THREAD

**Issue by vladimirtiukhtin** [hashicorp/terraform-provider-aws#11233]
Hello

I am setting to set up capacity providers for our ECS clusters, however when I try to click on "Add provider" an empty list displayed. I noticed, that clusters created by terraform have such issue while clusters created manually are not affected. Please fix.

<img width="1183" alt="Screen Shot 2019-12-10 at 23 13 44" src="https://user-images.githubusercontent.com/15124334/70577725-af20c100-1ba3-11ea-999e-466146880659.png">

**Comment by justinretzolk** [comment]
Hey @vladimirtiukhtin 👋 Thank you for taking the time to file this issue. Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?
