### ISSUE TITLE
feature request: support Route53 Traffic Policies

### ISSUE THREAD

**Issue by knksmith57** [hashicorp/terraform-provider-aws#11256]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
[Traffic Policies](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/traffic-flow.html) are [groups of rules and endpoints](https://docs.aws.amazon.com/Route53/latest/APIReference/api-policies-traffic-policy-document-format.html#traffic-policy-document-format-rules) expressed as a single document that create multiple Resource Record Sets. Traffic Policies are reusable and are attached to Hosted Zones using [Traffic Policy Instances](https://docs.aws.amazon.com/Route53/latest/APIReference/API_CreateTrafficPolicyInstance.html). Traffic Policies are immutable and [automatically versioned](https://docs.aws.amazon.com/Route53/latest/APIReference/API_TrafficPolicy.html#Route53-Type-TrafficPolicy-Version).

### New or Affected Resource(s)
* `aws_route53_traffic_policy`
* `aws_route53_traffic_policy_document`
* `aws_route53_traffic_policy_instance`

### Potential Terraform Configuration

```hcl
data "aws_route53_traffic_policy_document" "example" {
  record_type = "A"
  start_rule  = "site_switch"

  endpoint {
    id    = "my_elb"
    type  = "elastic-load-balancer"
    value = "elb-111111.us-east-1.elb.amazonaws.com"
  }

  endpoint {
    id     = "site_down_banner"
    type   = "s3-website"
    region = "us-east-1"
    value  = "www.example.com"
  }

  rule {
    id   = "site_switch"
    type = "failover"
    primary = {
      endpoint_reference = "my_elb"
    }
    secondary = {
      endpoint_reference = "site_down_banner"
    }
  }
}

resource "aws_route53_zone" "main" {
  name = "test.com"
}

resource "aws_route53_traffic_policy" "www" {
  name     = "www"
  document = "${data.aws_route53_traffic_policy_document.example.json}"
}

resource "aws_route53_traffic_policy_instance" "www_main" {
  zone_id        = "${aws_route53_zone.main.zone_id}"
  name           = "${aws_route53_traffic_policy.www.name}_${aws_route53_zone.main.name}"
  policy_id      = "${aws_route53_traffic_policy.www.id}"
  policy_version = "${aws_route53_traffic_policy.www.version}"
}
```

### References

* #1159

**Comment by myakubiv-solringair** [comment]
Hi! are there any plans on implementing this?
thanks

**Comment by mwieczorek** [comment]
Hi. I started to work on `aws_route53_traffic_policy`, but cannot provide any date when will be ready (not much time I can spend on this).

Sidenote: I hit an issue with [GetTrafficPolicy](https://docs.aws.amazon.com/Route53/latest/APIReference/API_GetTrafficPolicy.html) - it returns data even for deleted traffic policies - I asked AWS support if it's expected behavior and waiting for a reply (I know I can use [ListTrafficPolicies](https://docs.aws.amazon.com/Route53/latest/APIReference/API_ListTrafficPolicies.html) and iterate to check but I prefer to make it clear which one should be used and why)

**Comment by crablab** [comment]
Do we have any updates on this? 👀  We're using a manual workaround outside of Tf as this isn't supported.

**Comment by rym-dd** [comment]
Hi, are there updates about this? Thanks.

**Comment by ewbankkit** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!
