### ISSUE TITLE
Add update support for ECS Cluster Capacity Providers

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#11287]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The AWS ECS API does not yet support update of cluster capacity providers, but there is an open issue on the ECS roadmap to address this: https://github.com/aws/containers-roadmap/issues/633.

Once this is implemented, add it to the `aws_ecs_capacity_provider` resource.

### New or Affected Resource(s)

* aws_ecs_capacity_provider

### References

* #11151 
* https://github.com/aws/containers-roadmap/issues/633

**Comment by jordanfbrown** [comment]
It looks like https://github.com/aws/containers-roadmap/issues/633 was finally resolved, so seems like work on this can finally be started!

https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-ecs-capacity-providers-now-support-update-functionality/

**Comment by Zogoo** [comment]
In Terraform 12 still not able to update it. Should I used latest version of Terraform to resolve this issue?

**Comment by legal90** [comment]
This PR implements that: https://github.com/hashicorp/terraform-provider-aws/pull/16942

**Comment by DrFaust92** [comment]
Closed via #16942
