### ISSUE TITLE
Redshift Elastic Resize Not Working When Node Count Increased - Classic Resize Performed Instead

### ISSUE THREAD

**Issue by frosty-007** [hashicorp/terraform-provider-aws#11303]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.4 
provider version = "~> 2.8"

### Affected Resource(s)

* aws_redshift_cluster

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

According to the API elastic resize should be the default resize method. One would expect modification of number_of_nodes that is within the conditions for an elastic resize to actually trigger an elastic resize.

### Actual Behavior

Classic Resize was performed instead of the Elastic resize taking the cluster offline. 
Classic resize successfully completes - but not great that the cluster has been taken offline, when a few minutes of downtime was expected.

### Steps to Reproduce

Increased node count from 4 - 8
terraform apply

### References

* #0000

**Comment by frosty-007** [comment]
Reszie successfully completes in AWS while terraform reports back the following.

````
Error: Error Modifying Redshift Cluster (analytics-tx-cluster): timeout while waiting for state to become 'available' (last state: 'resizing', timeout: 40m0s)

  on analytics.tf line 1, in resource "aws_redshift_cluster" "analytics_tx_cluster":
   1: resource "aws_redshift_cluster" "analytics_tx_cluster" {
```

**Comment by frosty-007** [comment]
On resizing back down to 4 cluster nodes this also ran as a classic resize and this completed successfully. However I believe this should have ran as online elastic resize.

**Comment by justinretzolk** [comment]
Hey @frosty-007 :wave: Thank you for taking the time to file this issue, and for the additional updates. Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?
