### ISSUE TITLE
aws_cloudformation_stack parameter value cannot be cleared

### ISSUE THREAD

**Issue by camlow325** [hashicorp/terraform-provider-aws#11312]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.18
+ provider.aws v2.42.0
```

### Affected Resource(s)

* aws_cloudformation_stack

### Terraform Configuration Files

```hcl
variable "bucket_name" {
  type = string
  default = ""
}

resource "aws_cloudformation_stack" "test" {
  name = "test"
  parameters = {
    BucketName = var.bucket_name
  }
  template_body = <<STACK
Parameters:
  BucketName:
    Type: String
    Default: ''
Conditions:
  UseBucketName: !Not [!Equals [!Ref BucketName, '']]
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If
       - UseBucketName
       - !Ref BucketName
       - !Ref AWS::NoValue
STACK
}
```

### Expected Behavior

When an `aws_cloudformation_stack` with a non-empty value for a parameter is changed to have an empty value and an apply is performed, the CloudFormation stack should be updated with an empty value for the parameter.

For the test config above, the previously created S3 bucket for the CloudFormation stack, `test`, should be removed and a new one with an autogenerated name should be created in its place.

### Actual Behavior

The CloudFormation stack remains unchanged - with the previous non-empty value for the parameter being retained.

For the test config above, the previously created S3 bucket for the CloudFormation stack, `test`, remains in place instead of being replaced with a new one having an autogenerated name.

### Steps to Reproduce

1. `terraform apply --var="bucket_name=test"`

The apply is successful, with an S3 bucket named "test" being created.

2. `terraform apply --var="bucket_name="`

### References

**Comment by camlow325** [comment]
I was able to reproduce this issue with a simple, fake provider implementation and so I filed an issue to Terraform core [here](https://github.com/hashicorp/terraform/issues/23904).

**Comment by justinretzolk** [comment]
Hey @camlow325 👋 Thank you for taking the time to file this issue and for the follow up that this seems to be a core issue rather than an issue with the provider. Given that's the case, we'll close this issue. If you feel we've done this in error, please do let us know.
