### ISSUE TITLE
Add possibility to retry/delay/timeout on data sources

### ISSUE THREAD

**Issue by obourdon** [hashicorp/terraform-provider-aws#11342]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

First of all, I was not sure if I needed to post this feature request here or in terraform core itself but as we are using AWS provider intensely in the first place and considering that this is also requiring changes in its corresponding code, I thought this was the best place to post this FR

Second, do not flame me right away as I know this is not really matching the "philosophical" way terraform and providers are supposed to work, but considering all others questions I have seen here and there concerning similar things I thought there is room/legitimity for this enhancement

Third, as I did look at the source code and more specifically [ aws/data_source_aws_instances.go](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_instances.go), I think this could be done quite easily/effortlessly

OK so here is my concern: let's assume we are using Autoscaling group and need to specify a dedicated target group rule for each instance (like a monitoring agent, ...). This could be done via Lambda code plugged to autoscaling events of course or also within the HCL code using a workaround/hack with null_resources, local-exec, sleep and data sources but as far as what I read so far:

1. null_resources + local_exec + sleep are highly discouraged
2. if the sleep time you specify is too short, you need to write another identical section and this is very painful

### New or Affected Resource(s)

All data sources concerning dynamic resources

### Potential Terraform Configuration

```hcl
data "aws_instances" "asg_instances" {
  instance_state_names = ["running", "pending"]

  filter = {
    name   = "instance.group-id"
    values = ["${aws_security_group.cluster.id}"]
  }

  poll = {
    delay = 20
    interval = 10
    retry_count = 10
    timeout = 60
  }
}
```

### References

* [#3128](https://github.com/terraform-providers/terraform-provider-aws/issues/3128)
* [#10715](https://github.com/terraform-providers/terraform-provider-aws/issues/10715)
* [#10769](https://github.com/terraform-providers/terraform-provider-aws/issues/10769)

**Comment by Z3R6** [comment]
any updates?

**Comment by dtphuc** [comment]
Hi Team,

Any updates on the ticket?

I'm looking forward to hearing from you guys. 

Thanks

**Comment by obourdon** [comment]
Any updates ?

**Comment by Deasel011** [comment]
Any updates on this issue??
Would like to retry until my query returns at least 1 result :'[

**Comment by dbarkin** [comment]
Any updates? or at least offer workaround (don't offer re-running with apply)
