### ISSUE TITLE
Add type to aws_sfn_state_machine

### ISSUE THREAD

**Issue by grahamhar** [hashicorp/terraform-provider-aws#11348]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Following the introduction of express step functions as described in [this blog post](https://aws.amazon.com/about-aws/whats-new/2019/12/introducing-aws-step-functions-express-workflows/) and documented [here](https://docs.aws.amazon.com/step-functions/latest/apireference/API_CreateStateMachine.html) can support be added to the existing resource for this new capability.
### New or Affected Resource(s)

* aws_sfn_state_machine

### Potential Terraform Configuration

type would default to Standard to make this a non breaking change.

```hcl
resource "aws_sfn_state_machine" "sfn_state_machine" {
  name     = "my-state-machine"
  role_arn = aws_iam_role.iam_for_sfn.arn
  type     = "Express"
  definition = <<EOF
{
  "Comment": "A Hello World example of the Amazon States Language using an AWS Lambda Function",
  "StartAt": "HelloWorld",
  "States": {
    "HelloWorld": {
      "Type": "Task",
      "Resource": aws_lambda_function.lambda.arn,
      "End": true
    }
  }
}
EOF
}
```

**Comment by rockycore** [comment]
For Type and Logging here is another PR: https://github.com/terraform-providers/terraform-provider-aws/pull/11570)
The former PR does not cover the relevant Logging Configuration for EXPRESS Workflows.

**Comment by rockycore** [comment]
https://github.com/terraform-providers/terraform-provider-aws/pull/11570

**Comment by breathingdust** [comment]
Hi all! :wave: Just wanted to direct you to our public [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/master/ROADMAP.md) for this quarter (Nov-Jan) in which this item has been mentioned.

Due to the significant community interest in support for this feature, we will be looking at merging existing contributions soon. 

We appreciate all the contributions and feedback thus far.

Look out for support in the provider soon!
