### ISSUE TITLE
Codepipeline Bitbucket Integration

### ISSUE THREAD

**Issue by vibhuyadav** [hashicorp/terraform-provider-aws#11389]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Codepipeline now supports integration with Bitbucket. Please refer this announcement
https://aws.amazon.com/about-aws/whats-new/2019/12/aws-codepipeline-now-supports-atlassian-bitbucket-cloud/

### New or Affected Resource(s)

* aws_codepipeline

### Potential Terraform Configuration

```hcl
resource "aws_codepipeline" "this" {
  name     = "${var.codecommit_name}-pipeline"
  role_arn = var.codepipeline_role_arn

  artifact_store {
    [..]
  }

  stage {
    name = "Source"

    action {
      name             = "Source"
      category         = "Source"
      owner            = "ThirdParty"
      provider         = "Bitbucket"
      version          = "1"
      output_artifacts = ["source_output"]

      configuration = {
        Owner  = "my-organization"
        Repo   = "test"
        Branch = "master"
      }
    }
    [..]
  }

  stage {
    name = "Build"

    action {
      name            = "BuildFrontend"
      category        = "Build"
      owner           = "AWS"
      provider        = "CodeBuild"
      input_artifacts = ["source"]

      output_artifacts = [
        [..]
      ]

      version = "1"

      configuration = {
        ProjectName = aws_codebuild_project.this.name
      }
    }

    action {
      name            = "BuildBackend"
      category        = "Build"
      owner           = "AWS"
      provider        = "CodeBuild"
      input_artifacts = ["source"]

      output_artifacts = [
        [..]
      ]

      version = "1"

      configuration = {
        ProjectName = aws_codebuild_project.this.name
      }
    }
  }

  stage {
    name = "DeployDevelopment"

    action {
      [..]
    }

    action {
      [..]
    }
  }
```

**Comment by bflad** [comment]
I believe this may also relate to the new CodeStar Connections service added in [AWS Go SDK v1.26.6](https://github.com/aws/aws-sdk-go/releases/tag/v1.26.6). If so, see also https://github.com/terraform-providers/terraform-provider-aws/pull/11375 and https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md#new-service

**Comment by vibhuyadav** [comment]
You are probably right. Here is the json response for Codepipeline set with CodeStarSourceConnection. The pipeline was created by hand on the console.

`$ aws codepipeline get-pipeline --name my-example --region us-east-1 > issue_11389.json`

`{
    "pipeline": {
        "roleArn": "arn:aws:iam::111111111111:role/code-pipeline-role", 
        "stages": [
            {
                "name": "Bitbucket", 
                "actions": [
                    {
                        "inputArtifacts": [], 
                        "name": "bitbucket", 
                        "region": "us-east-1", 
                        "actionTypeId": {
                            "category": "Source", 
                            "owner": "AWS", 
                            "version": "1", 
                            "provider": "CodeStarSourceConnection"
                        }, 
                        "outputArtifacts": [
                            {
                                "name": "bitbucket-artifact"
                            }
                        ], 
                        "configuration": {
                            "ConnectionArn": "arn:aws:codestar-connections:us-east-1:111111111111:connection/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx", 
                            "FullRepositoryId": "foo-bar/my-example", 
                            "BranchName": "master", 
                            "OutputArtifactFormat": "CODEBUILD_CLONE_REF"
                        }, 
                        "runOrder": 1
                    }
                ]
            }, 
     ...
     ...
`

**Comment by laghao** [comment]
Is bitbucket provider supported already in resource "aws_codepipeline"?

**Comment by romeroadrian** [comment]
I've managed to get bitbucket working using something like the following:

```
stage {
    name = "Source"

    action {
      name             = "Source"
      category         = "Source"
      owner            = "AWS"
      provider         = "CodeStarSourceConnection"
      version          = "1"
      output_artifacts = ["source"]

      configuration = {
        BranchName           = "master"
        ConnectionArn        = "the connection arn"
        FullRepositoryId     = "foo/bar"
        OutputArtifactFormat = "CODE_ZIP"
      }
    }
  }
```

I had to previously do the oauth thing to connect aws with bitbucket and manually copy the arn of the codestar connection.

**Comment by vibhuyadav** [comment]
That is right. I can confirm this works
`  stage {
    name = "Source"

    action {
      name             = "Source"
      category         = "Source"
      owner            = "AWS"
      provider         = "CodeStarSourceConnection"
      version          = "1"
      output_artifacts = ["SourceArtifact"]

      configuration = {
        ConnectionArn        = "arn:aws:codestar-connections:us-east-1:${var.aws_account_id}:connection/89cb0638-6cf7-4e37-9f11-228803e7aec7"
        FullRepositoryId     = "extron-electronics/${var.project_name}"
        BranchName           = "develop"
        OutputArtifactFormat = "CODEBUILD_CLONE_REF"
      }
    }
  }`

**Comment by mavencode01** [comment]
@vibhuyadav I tried configuring the Bitbucket source like you defined but am getting error message `The provided role does not have sufficient permissions` 

Could you please share the role / policy you used to create the Bitbucket connection ?

Thank you.

**Comment by vibhuyadav** [comment]
@mavencode01 Make sure you have allow on codestar-connections:UseConnection on the policy

**Comment by marcoslopesbritto** [comment]
Dear vibhuyadav, what policy do you refer to?

**Comment by marcoslopesbritto** [comment]
I saw all IAM's roles (CodeDeploy, CloudFormation, ToolChain and PermissionBoundary), but I couldn't find the correnct  to put a codestar-connections:UseConnection statement.

**Comment by vibhuyadav** [comment]
@marcoslopesbritto I just created a new customer managed role to use for the pipeline. Here is what all I have in the role.
```
statement {
    actions = [
      "ecr:BatchCheckLayerAvailability",
      "ecr:CompleteLayerUpload",
      "ecr:GetAuthorizationToken",
      "ecr:InitiateLayerUpload",
      "ecr:PutImage",
      "ecr:UploadLayerPart",
      "cloudformation:DescribeStacks",
      "cloudformation:ValidateTemplate",
      "cloudformation:GetTemplate",
      "logs:CreateLogGroup",
      "logs:CreateLogStream",
      "logs:PutLogEvents",
      "ssm:GetParameters",
      "ssm:GetParameter",
      "ssm:GetParametersByPath",
      "sts:AssumeRole",
      "codebuild:CreateReportGroup",
      "codebuild:CreateReport",
      "codebuild:UpdateReport",
      "codebuild:BatchPutTestCases",
      "codestar-connections:UseConnection",
    ]

    effect = "Allow"

    resources = [
      "*",
    ]
  }

**Comment by Wiickette** [comment]
> @marcoslopesbritto I just created a new customer-managed policy. Here is what all I have in the policy and I attached it to the role behind the pipeline.

Yep that's the default policy AWS put.
Some caveats:
1. You probably don't need most of the services that it opens
2. Won't work if you use KMS to store your artifacts in S3

To add KMS support, simply add the following block to the previous policy:
```
 {
     "Sid": "kms",
      "Effect": "Allow",
      "Action": [
          "kms:Decrypt",
          "kms:DescribeKey",
          "kms:Encrypt",
          "kms:GenerateDataKey*",
          "kms:ReEncrypt*"
      ],
      "Resource": "[your KMS key arn]"
  }
```

Here is the one I have been using, which gives you usage of :
- CodeBuild
- CodeDeploy
- CodeStar connections
- KMS
- Lambda calls
- ServiceCatalog
- S3
- SNS

```
policy = <<-EOF
  {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Sid": "s3",
        "Effect": "Allow",
        "Action": [
          "s3:*"
        ],
        "Resource": [
          "${aws_s3_bucket.codepipeline_bucket.arn}",
          "${aws_s3_bucket.codepipeline_bucket.arn}/*"
        ]
      },
      {
        "Sid": "codebuild",
        "Effect": "Allow",
        "Action": [
          "codebuild:BatchGetBuilds",
          "codebuild:StartBuild"
        ],
        "Resource": "*"
      },
      {
        "Sid": "codedeploy",
        "Effect": "Allow",
        "Action": [
          "codedeploy:CreateDeployment",
          "codedeploy:GetApplication",
          "codedeploy:GetApplicationRevision",
          "codedeploy:GetDeployment",
          "codedeploy:GetDeploymentConfig",
          "codedeploy:RegisterApplicationRevision"
        ],
        "Resource": "*"
      },
      {
        "Sid": "codestar",
        "Effect": "Allow",
        "Action": [
          "codestar-connections:UseConnection"
        ],
        "Resource": "*"
      },
      {
        "Sid": "ecr",
        "Effect": "Allow",
        "Action": [
          "ecr:DescribeImages"
        ],
        "Resource": "*"
      },
      {
          "Sid": "kms",
          "Effect": "Allow",
          "Action": [
              "kms:Decrypt",
              "kms:DescribeKey",
              "kms:Encrypt",
              "kms:GenerateDataKey*",
              "kms:ReEncrypt*"
          ],
          "Resource": "[your KMS key arn]"
      },
      {
        "Sid": "lambda",
        "Effect": "Allow",
        "Action": [
          "lambda:InvokeFunction",
          "lambda:ListFunctions"
        ],
        "Resource": "*"
      },
      {
        "Sid": "servicecatalog",
        "Effect": "Allow",
        "Action": [
          "servicecatalog:CreateProvisioningArtifact",
          "servicecatalog:DeleteProvisioningArtifact",
          "servicecatalog:DescribeProvisioningArtifact",
          "servicecatalog:ListProvisioningArtifacts",
          "servicecatalog:UpdateProduct"
        ],
        "Resource": "*"
      },
      {
        "Sid": "sns",
        "Effect": "Allow",
        "Action": [
          "sns:CheckIfPhoneNumberIsOptedOut",
          "sns:CreateTopic",
          "sns:GetEndpointAttributes",
          "sns:GetPlatformApplicationAttributes",
          "sns:GetSMSAttributes",
          "sns:GetSubscriptionAttributes",
          "sns:GetTopicAttributes",
          "sns:ListEndpointsByPlatformApplication",
          "sns:ListPhoneNumbersOptedOut",
          "sns:ListPlatformApplications",
          "sns:ListSubscriptions",
          "sns:ListSubscriptionsByTopic",
          "sns:ListTagsForResource",
          "sns:ListTopics",
          "sns:Publish",
          "sns:SetTopicAttributes",
          "sns:TagResource",
          "sns:UntagResource"
        ],
        "Resource": "*"
      }
    ]
  }
EOF
```
Could be simplified / secured even further, especially with targeting the exact resources that CodePipeline need access to.
