### ISSUE TITLE
aws_route53_record doesn't allow ttl = 0

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#11381]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.18
+ provider.aws v2.43.0

### Affected Resource(s)

* aws_route53_record

### Terraform Configuration Files

```hcl
provider "aws" {
    region = var.region
}

data "aws_route53_zone" "main" {
    name = "${var.domain}."
}

resource "aws_route53_record" "weighted_record" {
    name            = "test.${var.domain}"
    zone_id         = data.aws_route53_zone.main.zone_id
    type            = "CNAME"
    ttl             = 0
    records         = [
        "test-1.${var.domain}"
    ]
    weighted_routing_policy {
        weight = 0
    }
    set_identifier  = "01"
}
```

### Expected Behavior

A new DNS record should be added with TTL = 0.

### Actual Behavior

An error is thrown during `apply`:
```
 Error: provider.aws: aws_route53_record: test.***: "ttl": required field is not set
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by hv-work** [comment]
I believe [here](https://github.com/terraform-providers/terraform-provider-aws/blob/98b8b848ca94031b20c3e626c9d40484e3af80de/aws/resource_aws_route53_record.go#L825) `GetOk` should be replaced with `GetOkExists`.
