### ISSUE TITLE
Imported `aws_cognito_user_pool` with no tags causes update in plan

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#11392]
When importing a `aws_cognito_user_pool` with no tags into Terraform, a diff is generated in the plan. It doesn't force a change, but does show up if there are other changes.

The import operation is storing an empty map of tags, but the plan wants to update it to `nil`:

```
- tags = {} -> null
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource

* aws_cognito_user_pool

### Expected Behavior

There should be no diff in the plan

### Actual Behavior

There is a diff in the plan

**Comment by justinretzolk** [comment]
Hey @gdavison! 👋 Thanks for taking the time to file this issue! Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?
