### ISSUE TITLE
Import aws_security_group_rule with ICMP:Echo Request

### ISSUE THREAD

**Issue by richardgavel** [hashicorp/terraform-provider-aws#11433]
I am trying to import a security group rule whose purpose is an IMCP Echo Request, which is unique because the to_port = -1. This is resulting in a failure of validating the import string because the to_port > from_port

https://github.com/terraform-providers/terraform-provider-aws/blob/bd4d9757b189743c7b34409b7b7acfca5197cf0c/aws/resource_aws_security_group_rule.go#L959

### Terraform Version

0.11.8 (AWS Provider 2.35.0)

### Affected Resource(s)

aws_security_group_rule

### Terraform Configuration Files

```hcl
resource "aws_security_group_rule" "mgtp-rdp-sg-ingress-15" {
  description = ""
  cidr_blocks = ["205.144.146.0/24"]
  from_port = 8
  protocol = "icmp"
  security_group_id = "${aws_security_group.mgtp-rdp-sg.id}"
  to_port = -1
  type = "ingress"
}
```

### Expected Behavior

The security group rule imports appropriately.

### Actual Behavior

Error: module.shared.aws_security_group_rule.mgtp-rdp-sg-ingress-15 (import id: sg-d1bc0799_ingress_icmp_8_-1_205.144.146.0/24): import module.shared.aws_security_group_rule.mgtp-rdp-sg-ingress-15 (id: sg-d1bc0799_ingress_icmp_8_-1_205.144.146.0/24): unexpected format of import string ("sg-d1bc0799_ingress_icmp_8_-1_205.144.146.0/24"), expected SECURITYGROUPID_TYPE_PROTOCOL_FROMPORT_TOPORT_SOURCE[_SOURCE]*: invalid port

### Steps to Reproduce

Import an individual aws_security_group_rule of and ICMP: Echo Request

**Comment by davidkemper** [comment]
This is hitting me as well now.

Perhaps special-case this for ICMP to relax the `p2 < p1` check?

Also, when you're in the neighborhood, would be helpful to give better error text to differentiate the `from_port` and `to_port` errors.
