### ISSUE TITLE
Undetected configuration drift in policy for aws_sns_topic 

### ISSUE THREAD

**Issue by dynamike** [hashicorp/terraform-provider-aws#11447]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.18
+ provider.aws v2.43.0

### Affected Resource(s)

* aws_sns_topic

### Terraform Configuration Files

```hcl
provider "aws" {
  version = "~> 2.43.0"
  region  = local.region
}

locals {
  region = "us-west-2"
}

resource "aws_sns_topic" "dynatest" {
  name = "dynatest"
}
```

### Expected Behavior

When manually modified, Terraform should detect changes to the access policy of the sns topic.

### Actual Behavior

When manually modified, Terraform doesn't detect changes to the access policy of the sns topic.

### Steps to Reproduce

1. `terraform apply`
2. Manually change the access policy of the SNS topic created via terraform
3. `terraform apply` - this is where I would expect Terraform try to undo the manually applied changes. Instead I get 
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**Comment by justinretzolk** [comment]
Hey @dynamike 👋 Thank you for taking the time to file this issue! Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this issue?
