### ISSUE TITLE
Cannot create aws_route53_record with a name that contains period, space, and other characters

### ISSUE THREAD

**Issue by jandockx** [hashicorp/terraform-provider-aws#11445]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

≥ 0.11

This issue is introduced in [version 1.15.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1150-april-18-2018), by PR [4183](https://github.com/terraform-providers/terraform-provider-aws/pull/4183).

### Affected Resource(s)

* aws_route53_record

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Resource record sets are created _and_ recognized by Terraform

### Actual Behavior

Either the resource record sets are not created, or they are, but then not recognized by Terraform.

### Steps to Reproduce

Try to create a resource record set with a space, period, or a high character, like ä, in the name.

### Important Factoids

In DNS, resource record set names are dot-separated sequences of _labels_. Labels are sequences of octets, and all
octets are allowed. Octets thus are interpreted as ASCII characters. Since all octets are allowed, also non-printable
characters, the space, and the period are allowed.

AWS Route53 documentation
[DNS Domain Name Format/Formatting Domain Names for Hosted Zones and Records](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DomainNameFormat.html#domain-name-format-hosted-zones)
specifies what AWS Route53 does.

The following characters are used as is in labels:

    a-z0-9-!"#$%&'()*+,-/:;<=>?@[\]^_`{|}~\.

_Note that this list contains `.`, but that is the label separator._

When you send `[A-Z]`, the characters are converted to lower case.
To send other octets, you must send the octal escape code `\nnn`.

Notably, for the period, you should send `\056`. For space, `\040`. For `ä`, `\344`.

AWS Route53 stores all characters that are not

    a-z0-9-_

as octal escapes, and returns them as octal escapes.

This means you can _send_, e.g., `@`, but you get back `\100`. Note that you can also send `\100` for the same effect.
This applies to all the characters:

    !"#$%&'()*+,-/:;<=>?@[\]^`{|}~\

(Not the period).

[Terraform PR 4183](https://github.com/terraform-providers/terraform-provider-aws/pull/4183/files/b5fa8ed08131d7643ee48ce73806df08f581487e#diff-7f12b54e3263d749179bfb63338a8919)
changes `func cleanRecordName` to always un-escape resource record set names returned from AWS, before it is compared
to the name specified by the user. This means the user can use `!"#$%&'()*+,-/:;<=>?@[\]^`{|}~\` in resource record set
names, but not octal codes.

If the user specifies `a@b.example.org`, this is send _as is_ to AWS. AWS returns `a\100b.example.org`, which is cleaned
to `a@b.example.org`, which is the same as what was send.

If the user specifies `a\\100b.example.org`, this is send as `a\100b.example.org` to AWS. AWS returns
`a\100b.example.org`, which is cleaned to `a@b.example.org`, which is _not the same as what was send_. Terraform now no
longer recognizes this.

For `!"#$%&'()*+,-/:;<=>?@[\]^`{|}~\`, the obvious workaround is to not use the octal representation.

But it is now impossible to use any other non-printable character, like the period, the space,
or `ä`:

| User specified        | Send                 | Returned             | Cleaned           |
| --------------------- | -------------------- |  ------------------- | ----------------- |
| `a\\056b.example.org` | `a\056b.example.org` | `a\056b.example.org` | `a.b.example.org` |
| `a\\040b.example.org` | `a\040b.example.org` | `a\040b.example.org` | `a b.example.org` |
| `a\\344b.example.org` | `a\344b.example.org` | `a\344b.example.org` | `aäb.example.org` |

For the user to be able to specify the period (`\056`), `\000-\039`, or `\177`, it must be possible for the user to
specify escape codes. While the Go character escapes could be used for `\000-\039` (e.g., `\t` for `\011`), there is
no other option for the period (`\056`).

A partial solution therefore is to not clean what is returned from AWS, but instead make sure we compare what is returned
to an escaped version of what the user specified. Yet, that is complex, e.g., for `\`.

Actually, things better before the PR: for all characters not in `a-z0-9-_`, the user could use the octal escape. I suggest this is the only sensible solution. The intention of the PR was for users to be able to use regular characters for `!"#$%&'()*+,-/:;<=>?@[\]^`{|}~\`, where before the PR,
octal escape could be used already. I suggest that documenting the resource, and warning the user
that she should only use `a-z0-9-_`, and octal escape any other octet, is the solution that makes most sense.

### References

This issue is introduced in [version 1.15.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1150-april-18-2018), by PR [4183](https://github.com/terraform-providers/terraform-provider-aws/pull/4183).

**Comment by justinretzolk** [comment]
Hey @jandockx 👋 Thank you for taking the time to file this issue! Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?
