### ISSUE TITLE
Implement support for time based retention policies in DLM

### ISSUE THREAD

**Issue by civ0** [hashicorp/terraform-provider-aws#11456]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
AWS DLM supports time based retention policies since end of November 2019: https://aws.amazon.com/about-aws/whats-new/2019/11/data-lifecycle-manager-supports-time-based-retention-policies/

This feature is currently not supported by the Terraform AWS Provider.

### New or Affected Resource(s)

* aws/resource_aws_dlm_lifecycle_policy.go

### Potential Terraform Configuration

```hcl
retain_rule {
  type = "Age"
  interval = 7
  interval_unit = "Days"
}

```

**Comment by aviau** [comment]
This would be really nice!

The count-base retention is much more complicated to manage, for example when you delete disks and the snapshots remain forever because the count stops growing.

**Comment by NelsonJeppesen** [comment]
> ... for example when you delete disks and the snapshots remain forever because the count stops growing.

This is the exact issue I've run into

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!
