### ISSUE TITLE
Cloudfront distribution origin domain name restrictions

### ISSUE THREAD

**Issue by heylookalive** [hashicorp/terraform-provider-aws#1145]
Hi, I'm trying to create infrastructure with Terraform where we have an API Gateway instance and a Cloudfront CDN in front of that.

**Problem:**
It would seem that using Terraform you cannot create a Cloudfront distribution with a custom domain name (unrelated to AWS). I can do this manually.

**Output from terraform apply**
```
Error applying plan:

1 error(s) occurred:

* aws_cloudfront_distribution.apiCDN: 1 error(s) occurred:

* aws_cloudfront_distribution.apiCDN: NoSuchOrigin: One or more of your origins do not exist.
	status code: 404, request id: 5429e8d0-67ba-11e7-911b-3f3e58258526
```

**Example config** (partial)
```
resource "aws_cloudfront_distribution" "apiCDN" {
  depends_on = [
    "aws_api_gateway_integration.sitesIdMethodGetIntegration",
    "aws_api_gateway_deployment.apiGatewayDeploymentProd"
  ]

  origin {
      domain_name = "msn.com"
      ...
```

Being able to do this would allow us to put a CDN in front of our API Gateway.

**Comment by heylookalive** [comment]
This might suggest it's an AWS API issue https://forums.aws.amazon.com/thread.jspa?threadID=241564

**Comment by heylookalive** [comment]
Checked in with AWS, they've tested with boto and it works for them.

**Comment by gideonues** [comment]
I got same issue when I tried to apply "custom domain name" in a CloudFront districution. 

* module.cloudfront.aws_cloudfront_distribution.support_web_cf: 1 error(s) occurred:
* aws_cloudfront_distribution.support_web_cf: NoSuchOrigin: One or more of your origins do not exist.

**Comment by GustavoTango** [comment]
Having this same issue!
