### ISSUE TITLE
Add resource for CodeCommit approval rule templates

### ISSUE THREAD

**Issue by double16** [hashicorp/terraform-provider-aws#11461]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS recently added approval rule templates to CodeCommit to improve the pull request process. Need to add a resource for this.

### New or Affected Resource(s)

* aws_codecommit_approval_rule_template

### References

* https://docs.aws.amazon.com/codecommit/latest/APIReference/API_CreateApprovalRuleTemplate.html
* https://docs.aws.amazon.com/codecommit/latest/APIReference/API_GetApprovalRuleTemplate.html

**Comment by carthewd** [comment]
I have built a working resource for this - I'm just updating the documentation and then I'll submit the PR

**Comment by CloudMajix** [comment]
+1

**Comment by InTheKeyOfCSharp** [comment]
+1

**Comment by lakshmigk01** [comment]
+1

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters roadmap. If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!
