### ISSUE TITLE
Allow passing the assume_role ARN via an environment variable

### ISSUE THREAD

**Issue by orf** [hashicorp/terraform-provider-aws#11466]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In some situations it would be very handy to be able to do:

```
AWS_ASSUME_ROLE_ARN=xyz terraform plan
```

The "recommended" way is to create a AWS config file with the `assume_role` key, but there are have seemingly been a lot of bugs around this functionality (and indeed it does not currently work). Creating the config file in CI environments can be tricky and annoying, especially if you have the ARN in an environment variable already.

### New or Affected Resource(s)

The AWS provider itself.

### References

* https://github.com/terraform-providers/terraform-provider-aws/issues/11429

* https://github.com/terraform-providers/terraform-provider-aws/issues/11079

* https://github.com/terraform-providers/terraform-provider-aws/issues/10507

* https://github.com/terraform-providers/terraform-provider-aws/issues/9352

**Comment by bflad** [comment]
See also: https://github.com/aws/aws-sdk-go/issues/2802

I would suggest we wait until the AWS SDK team provides some guidance on the naming (for reasons in the mentioned issue), before we go about our own implementation. Theoretically if the AWS Go SDK implements that feature request, no work should be required in the Terraform AWS Provider beyond just upgrading our AWS Go SDK dependency and cutting a release.
