### ISSUE TITLE
S3 lifecycle transition error

### ISSUE THREAD

**Issue by kkeawkittikanchana** [hashicorp/terraform-provider-aws#11464]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.18 
+ provider.aws v2.43.0

### Affected Resource(s)
aws_s3_bucket {lifecycle_rule{transition}}

### Terraform Configuration Files

State

`+ resource "aws_s3_bucket" "main" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = (known after apply)
      + bucket_domain_name          = (known after apply)
      + bucket_prefix               = "tf-module"
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags                        = {
          + "Name"        = "s3-tf-module-test-tf"

        }
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + lifecycle_rule {
          + enabled = true
          + id      = "weekly_backup"
          + prefix  = "/Backup/Weekly"
          + tags    = {
              + "Name"        = "s3-lifecycle-tf-module-test-tf"
            }

          + expiration {
              + days = 8
            }

          + noncurrent_version_expiration {
              + days = (known after apply)
            }

          + noncurrent_version_transition {
              + days          = (known after apply)
              + storage_class = (known after apply)
            }

          + transition {
              + date          = (known after apply)
              + days          = (known after apply)
              + storage_class = (known after apply)
            }
        }
      + lifecycle_rule {
          + enabled = true
          + id      = "backup_log"
          + prefix  = "/Backup/Log"
          + tags    = {
              + "Name"        = "s3-lifecycle-tf-module-test-tf"
  
            }

          + expiration {
              + days = 100
            }

          + noncurrent_version_expiration {
              + days = (known after apply)
            }

          + noncurrent_version_transition {
              + days          = (known after apply)
              + storage_class = (known after apply)
            }

          + transition {
              + days          = 31
              + storage_class = "STANDARD_IA"
            }
        }

      + server_side_encryption_configuration {
          + rule {
              + apply_server_side_encryption_by_default {
                  + sse_algorithm = "aws:kms"
                }
            }
        }

      + versioning {
          + enabled    = false
          + mfa_delete = false
        }
    }
`

### Debug Output

`aws_s3_bucket.main: Creating...

Error: configuration for aws_s3_bucket.main still contains unknown values during apply (this is a bug in Terraform; please report it!)
`

### Expected Behavior

It should create s3 with transition life cycle. 

### Actual Behavior
When I tried to input life cycle it keep showing error after apply. I tried with GLACIER and STANDARD_IA. Both doesn't work.  I also made sure transition days is over 30. 

### Steps to Reproduce

1. create multiple lifecycle in one s3  and have transition in one of life cycle
2. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @kkeawkittikanchana 👋 Thank you for taking the time to file this issue! Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?
