### ISSUE TITLE
AppSync Terraform: Data Sources

### ISSUE THREAD

**Issue by darrenfurr** [hashicorp/terraform-provider-aws#11489]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
We have multiple AppSync graphql endpoints & multiple CD pipelines. Currently, there is no way to get the AppSync graphql endpoint unless we have all AppSync Terraform together in 1 pipeline.

Are Data Sources going to be supported for AppSync?
It appears we can do this via the AWS CLI:
https://docs.aws.amazon.com/cli/latest/reference/appsync/get-graphql-api.html

### New or Affected Resource(s)

* aws_appsync_graphql_api

### Potential Terraform Configuration

```hcl
data "aws_appsync_graphql_api" "current" {
  name = "MyAppSyncApi"
}

resource "aws_s3_bucket_object" "this" {
  bucket = "testBucket"
  content = <<EOF {
    ENDPOINT: data.aws_appsync_graphql_api.current.uris["GRAPHQL"]
  };
  EOF
}
```

### References

* N/A

**Comment by schematis** [comment]
Am wondering if leveraging `list-graphql-apis` on the backend and then doing filtering based off the key/value in the data block would be an option?
