### ISSUE TITLE
Aurora aws_rds_cluster_instance read replica creation times out 

### ISSUE THREAD

**Issue by brucedvgw** [hashicorp/terraform-provider-aws#11521]
When creating an RDS Aurora read replica of a MySQL instance the Terraform creation times out, however the new Aurora MySQL read replica is created in AWS. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v.0.12.18

### Affected Resource(s)

* aws_rds_cluster_instance

### Expected Behavior

- Set `replication_source_identifier` to current RDS Master.
- `Terraform apply` 
- Aurora MySQL read replica cluster instances created 

### Actual Behavior

Terraform times out.
When re-applying it recreated the instances, even though they are fully created.

* #0000

**Comment by justinretzolk** [comment]
Hey @brucedvgw 👋 Thank you for taking the time to file this issue. Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?

**Comment by brucedvgw** [comment]
Hi @justinretzolk 👋🏻  I have not encountered this issue recently so I would assume this may have been resolved from recent releases of the provider. Happy to close this one out.
