### ISSUE TITLE
AWS API GW - Method response does not show mapped model

### ISSUE THREAD

**Issue by santhedan** [hashicorp/terraform-provider-aws#11561]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.18
+ provider.aws v2.43.0

### Affected Resource(s)

aws_api_gateway_method_response

State of the API Gateway method's Method response is not properly configured

### Terraform Configuration Files

Following is the partial content - This is how I am creating the Method response. After executing terraform apply I can see that the response code 200 is mapped to a model called BookList. The Model BookList is also defined correctly. However when I look at the method in the AWS console the state of the method response is -> Select an integration response.

```hcl
resource "aws_api_gateway_method_response" "bookByAuthor_200" {
  rest_api_id   = aws_api_gateway_rest_api.BookAPI.id
  resource_id   = aws_api_gateway_resource.bookByAuthor.id
  http_method = aws_api_gateway_method.get-bookByAuthor.http_method
  status_code = "200"
  response_models = {
    "application/json" = aws_api_gateway_model.BookList.name
  }
}
```

### Expected Behavior

After deploying the API gateway - I expect that the "Method response" should show
```
HTTP Status: Proxy
Models: application/json => BookList
```

### Actual Behavior

the "Method response" is showing
```
Select an integration response.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The only way to fix this issue is to login to the AWS Console and the do the following:

- Go to "Integration request" and then uncheck "Use Lambda Proxy integration" and then check it again.
- After performing the above steps the Method response correctly shows the mapped model.

Only after this one can generate types SDK from the stage console.

### References

* #0000

**Comment by blundell** [comment]
> Go to "Integration request" and then uncheck "Use Lambda Proxy integration" and then check it again.

Thank you! Could not for the life of me work this out.
