### ISSUE TITLE
Amazon CloudFront additional real-time metrics in Amazon CloudWatch

### ISSUE THREAD

**Issue by piyushsonigra** [hashicorp/terraform-provider-aws#11577]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS recently released feature in CloudFront to view additional cloudwatch metrics.

### New or Affected Resource(s)

aws_cloudfront_distribution

### Potential Terraform Configuration

```
terraform "aws_cloudfront_distribution" "cf_name" {
   ....
   additional_metrics = true
   ....
}

```

### References

https://aws.amazon.com/about-aws/whats-new/2019/12/cloudfront-realtime-metrics/
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/viewing-cloudfront-metrics.html#monitoring-console.distributions-additional

**Comment by vamsi-yottamedia** [comment]
+1 any ETA adding this, please?

**Comment by webvamsi666** [comment]
+1 any ETA for adding this enhancement please?

**Comment by asaghri** [comment]
Hi, any update on this ? This feature will be greatly appreciated !

**Comment by jpeeler** [comment]
I was looking for this as well, but wasn't able to find the functionality implemented in https://github.com/aws/aws-sdk-go. Did I miss it? If not, it's doubtful this can move forward until the SDK supports it.

**Comment by r1m** [comment]
Apparently the console is using an undocumented API method (`UpdateMonitoringSubscription`) that is not public yet and not part of any SDK I checked. AWS support confirmed to me that it is not possible yet through SDK.
![image](https://user-images.githubusercontent.com/137285/81801486-cf6af800-9514-11ea-9dc1-b881fa69f18e.png)

**Comment by anmolbhatia05** [comment]
@piyushsonigra Is there a way to enable real time metrics via terraform now ?

**Comment by vicentllongo** [comment]
The functionality to manage additional and real-time metrics is already available in the aws-sdk-go since [v1.34.13](https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v13413-2020-08-28):
> You can now manage CloudFront's additional, real-time metrics with the CloudFront API.

**Comment by piyushsonigra** [comment]
@anmolbhatia05 directly inside terraform resource, it's not available yet but you can enable additional metrics using local-exec Provisioner in cloudfront resource and execute AWS cli command.

`resource "aws_cloudfront_distribution" "distribution" {
  ....
  ....
}

 resource "null_resource" "cloudfront_addtional_metrics" {

    command = "aws --profile $aws_profile cloudfront create-monitoring-subscription --distribution-id $cloudfront_distribution_id --monitoring-subscription RealtimeMetricsSubscriptionConfig={RealtimeMetricsSubscriptionStatus=Enabled}"

    environment = {
      aws_profile                         = var.aws_profile
      cloudfront_distribution_id = aws_cloudfront_distribution.distribution.id
    }
}
`

**Comment by ewbankkit** [comment]
Potential new resource:

```hcl
resource "aws_cloudfront_monitoring_subscription" "example" {
  distribution_id = aws_cloudfront_distribution.example.id

  monitoring_subscription {
    realtime_metrics_subscription_config {
      realtime_metrics_subscription_status = "Enabled"
    }
  }
}
```

**Comment by shuheiktgw** [comment]
I've started implementing this resource

**Comment by shuheiktgw** [comment]
I added it in https://github.com/hashicorp/terraform-provider-aws/pull/18083. Please upvote the PR for faster review 🙏
