### ISSUE TITLE
Faulty Read of Client VPN Network associations break state

### ISSUE THREAD

**Issue by fgrelak** [hashicorp/terraform-provider-aws#11586]
In aws/resource_aws_ec2_client_vpn_network_association.go line 112 commit/acc6a21a3bd6159f4f8c10a86bcd08e70edce4f2 
d.Set("subnet_id", result.ClientVpnTargetNetworks[0].TargetNetworkId)
leads to wrong subnet-ids if more than one Subnet is associated with the VPN Endpoint (as only the first entry of the map is read. Minimal example breaking the state:

```
resource "aws_ec2_client_vpn_network_association" "subnet-cvpn-associations" {
  for_each               = toset(var.subnets)
  client_vpn_endpoint_id = aws_ec2_client_vpn_endpoint.main-cvpn-endpoint.id
  subnet_id              = each.value
}

variable "subnets" {
  default = [
    "subnet-123",
    "subnet-456",
  ]
}
```
will lead to replacement on every terraform plan.

This may have teh reason that the API call here 	result, err := conn.DescribeClientVpnTargetNetworks(&ec2.DescribeClientVpnTargetNetworksInput{
		ClientVpnEndpointId: aws.String(d.Get("client_vpn_endpoint_id").(string)),
		AssociationIds:      []*string{aws.String(d.Id())},
actually does NOT return a list with only one entry, but all associations. One can test this by making this call with a wrong AssociationId.

**Comment by nijave** [comment]
This appears to be an Amazon API bug

doesn't work
```
'body': {
  'Action': 'DescribeClientVpnTargetNetworks',
  'Version': '2016-11-15',
  'ClientVpnEndpointId': 'cvpn-endpoint-123',
  'AssociationIds.1': 'cvpn-assoc-123'
}
```

works
```
'body': {'Action': 'DescribeClientVpnTargetNetworks', 'Version': '2016-11-15', 'ClientVpnEndpointId': 'cvpn-endpoint-123', 'Filter.1.Name': 'association-id', 'Filter.1.Value.1': 'cvpn-assoc-123'}
```

**Comment by cosmin-oprea** [comment]
I wonder when the pull request will be approved.
It's holding up my deployment in AWS as I make heavily use of this module and really don't like to start adding vpn client endpoint associations manually.

**Comment by breathingdust** [comment]
Hi all! :wave: Just wanted to direct you to our public [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/master/ROADMAP.md) for this quarter (Nov-Jan) in which this item has been mentioned.

Due to the significant community interest in resolving this issue, we will be looking at merging existing contributions soon. 

We appreciate all the contributions and feedback thus far.

**Comment by bill-rich** [comment]
The ability to use `AssociationIds` was fixed earlier this year. Rather than switching to using filters, I've left the original method, but added the acceptance test from #14380.
