### ISSUE TITLE
AWS Organizations acceptance test

### ISSUE THREAD

**Issue by ericksoen** [hashicorp/terraform-provider-aws#11582]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I've noticed that when I run the AWS Organizations Acceptance tests, I frequently encounter an error from the configured `testAccOrganizationsAccountPreCheck` that outputs the error "skipping tests; this AWS account must not be an existing member of an AWS Organization". The AWS Organizations API doesn't make it easy to leave an organization, e.g., the master account can't leave an organization and a member account receives the error "ConstraintViolationException when calling the LeaveOrganization operation. This operation requires a wait period" (without much supporting documentation from AWS regarding the duration of the wait period).

To make acceptance tests easier to run repeatedly, I was curious about the changing the behavior to remove the `resource "aws_organizations_organization" "test" {}` from certain acceptance tests and adding a PreTestCheck that validates that the account where acceptance tests are being run includes an AWS Organization. Alternatively (or in addition), where an explicitly AWS Organization resource is required, using the `data aws_organizations_organization` data source to get a provider reference. 

### New or Affected Resource(s)

* No directly impacted resources since the changes will all be to `*_test.go` files. Potentially impacted files include:
  * `provider_test.go`
  * `resource_aws_organizations_policy_test.go`
  * `resource_aws_organization_policy_attachment_test.go`
  * `resource_aws_organization_account_test.go`

**Comment by gdavison** [comment]
Thanks for this issue, @ericksoen. Typically, our acceptance tests are written to be standalone. As you've found, this can cause problems with some services. We've been talking on our team about some approaches we can take to deal with these more challenging services. Go 1.14 added a new [`Cleanup()` function](https://www.gopherguides.com/articles/test-cleanup-in-go-1-14/) which could help with this.
