### ISSUE TITLE
AWS Lambda Function Sensitive Environment Variables

### ISSUE THREAD

**Issue by FrediWeber** [hashicorp/terraform-provider-aws#11595]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Sensitive information is sometimes provided as an environment variable to an AWS Lambda function. When we provide the secret as an environment variable with Terraform, the plan and apply step will output these values as plain text.
We suggest that a possibility is added, to specify sensitive environment variables which will not be printed out by Terraform. We futher suggest to use the existing "sensitive" function from Terraform to accomplish this goal.

### New or Affected Resource(s)

* aws_lambda_function

### Potential Terraform Configuration

With backward compatibility
```hcl
resource "aws_lambda_function" "test_lambda" {
  filename      = "lambda_function_payload.zip"
  function_name = "lambda_function_name"
  role          = "${aws_iam_role.iam_for_lambda.arn}"
  handler       = "exports.test"
  runtime = "nodejs8.10"

  environment {
    sensitive_variables = {
      password = "SECRET"
    }
    variables = {
      foo = "bar"
    }
  }
}
```

Without backward compatibility
```hcl
resource "aws_lambda_function" "test_lambda" {
  filename      = "lambda_function_payload.zip"
  function_name = "lambda_function_name"
  role          = "${aws_iam_role.iam_for_lambda.arn}"
  handler       = "exports.test"
  runtime = "nodejs8.10"

  environment {
    variables = [
      {
        key = "foo"
        value = "bar"
        sensitive = false
      },
      {
        key = "password"
        value = "SECRET"
        sensitive = true
      }
    ]
  }
}
```

**Comment by GrantBirki** [comment]
I just stumbled across this thread. It appears a very solid work around is current available in later versions of Terraform. You can see the merged pull request [here](https://github.com/hashicorp/terraform/pull/26183) where this is now supported 😃 

You can do something link so to hide the output of a env var which you pass into your Lambda function:

```hcl
variable "SOME_VAR_HERE" {
  ...
  sensitive=true
}
```

Hope this helps!

**Comment by zhelding** [comment]
As I discussed in my response to PR #11614, the use case discussed here is now covered by the `sensitive` function introduced by Terraform `v0.15`.

(https://www.terraform.io/docs/language/functions/sensitive.html)
