### ISSUE TITLE
unexpected state

### ISSUE THREAD

**Issue by fstuck37** [hashicorp/terraform-provider-aws#11594]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the com
munity and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14
+ provider.aws v2.44.0
+ provider.local v1.4.0
+ provider.template v2.1.2

### Affected Resource(s)

aws_dx_hosted_private_virtual_interface

### Expected Behavior

Accept the state of approving

### Actual Behavior

Error: error waiting for Direct Connect virtual interface (dxvif-XXXXXX) to become available: 
unexpected state 'approving', 
wanted target 'available, confirming, down'. 
last error: %!s(<nil>)

**Comment by justinretzolk** [comment]
Hey @fstuck37 👋 Thank you for taking the time to file this issue! Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?

**Comment by fstuck37** [comment]
Will check. If I remember correctly this was primarily in AWS China were they manually approve each direct connect VIF.
