### ISSUE TITLE
AWS SecurityHub: the ability to disable specific compliance controls

### ISSUE THREAD

**Issue by marcincuber** [hashicorp/terraform-provider-aws#11624]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of Jan 15, 2020, AWS now allows to disable specific compliance controls within AWS SecurityHub. It will be very useful in my case to disable some of them or the ones that are not relevant for my setup.

### New or Affected Resource(s)

Potentially new resource

### References

* https://aws.amazon.com/about-aws/whats-new/2020/01/aws-security-hub-releases-ability-disable-specific-compliance-controls/

**Comment by steeef** [comment]
> Requires [AWS SDK v1.28.3](https://github.com/aws/aws-sdk-go/releases/tag/v1.28.3):
> 
>     * #11501

Looks like that was merged. What's next?

**Comment by marcincuber** [comment]
Any updates on this?

**Comment by phundisk** [comment]
@ewaltman or @brettcave anything I can do to help push this over the line?

**Comment by brettcave** [comment]
> 
> 
> @ewaltman or @brettcave anything I can do to help push this over the line?

@phundisk  - I haven't looked at this in a while, I will revisit this.

**Comment by jgeurts** [comment]
@brettcave (or @ewbankkit) Gentle nudge to see if you've had a chance to take a look at [the PR for this issue](https://github.com/hashicorp/terraform-provider-aws/pull/14714). 

If there's any other way for us to get hashicorp to review stale issues/PRs like this, that would be helpful to know. In the past, thumbs up on the issue was possibly used to triage work, but that seems unreliable and in some cases doesn't seem to make an impact to priority.

**Comment by jgeurts** [comment]
@ewbankkit @DrFaust92 @brettcave Can someone please acknowledge this and let us know what is needed to get someone to look at the PR/issue?

**Comment by osterman** [comment]
We've added support for this to our `cloudposse/awsutils` provider by using the [`awsutils_security_hub_control_disablement`](https://registry.terraform.io/providers/cloudposse/awsutils/latest/docs/resources/awsutils_security_hub_control_disablement) resource.
