### ISSUE TITLE
Issue with availability_zones (provider produced invalid final plan)

### ISSUE THREAD

**Issue by jackbritchford-perlego** [hashicorp/terraform-provider-aws#11639]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.19
+ provider.aws v2.44.0
+ provider.random v2.2.1
+ provider.template v2.1.2
```
Error: Provider produced inconsistent final plan

When expanding the plan for aws_autoscaling_group.ecs-nodes to include new
values learned so far during apply, provider "registry.terraform.io/-/aws"
produced an invalid new value for .availability_zones: was known, but now
unknown.
```
This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Affected Resource(s)

* any aws resource that has .availability_zones, in my case aws_autoscaling_group

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @jackbritchford-perlego 👋 Thank you for taking the time to file this issue. Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?
