### ISSUE TITLE
AWS Client VPN now supports port configuration

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#11633]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

You can now configure your AWS Client VPN endpoint to use either the port 443 or the port 1194.

### New or Affected Resource(s)

* [`aws_ec2_client_vpn_endpoint`](https://www.terraform.io/docs/providers/aws/r/ec2_client_vpn_endpoint.html)

### Potential Terraform Configuration

```hcl
resource "aws_ec2_client_vpn_endpoint" "example" {
  vpn_port = 1194
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/01/aws-client-vpn-now-supports-port-configuration/).
[API reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ClientVpnEndpoint.html).

Requires [AWS SDK v1.28.4](https://github.com/aws/aws-sdk-go/releases/tag/v1.28.4):
* https://github.com/terraform-providers/terraform-provider-aws/pull/11630

**Comment by e-moshaya** [comment]
any update on when this would get merged?

**Comment by internetstaff** [comment]
A year later ... any hope? :)

**Comment by chriskinsman** [comment]
Anyone?

**Comment by unity-unity** [comment]
Anyone?
