### ISSUE TITLE
Cannot add Step Function target for aws_cloudwatch_event_target

### ISSUE THREAD

**Issue by deepakjois** [hashicorp/terraform-provider-aws#11641]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.12.19
+ provider.aws v2.35.0
```

### Affected Resource(s)

* aws_cloudwatch_event_target

### Terraform Configuration Files

```hcl
# Event rule
resource "aws_cloudwatch_event_rule" "rule" {
  name                = "rule"
  description         = "run state machine periodically"
  schedule_expression = "cron(30 * ? * * *)"
  is_enabled          = true
}

# Event target to run fetch-export state machine regularly
resource "aws_cloudwatch_event_target" "target" {
  target_id = "some-target-id"
  rule = aws_cloudwatch_event_rule.rule.id
  arn = aws_sfn_state_machine.state_machine.id
  role_arn = data.aws_iam_role.some_valid_role.arn
}

resource "aws_sfn_state_machine" "state_machine" {
  # Define a valid state machine here…
}
```

### Expected Behavior
Rule gets created with a state machine target.

### Actual Behavior

Rule gets created without a state machine target.

![Screen Shot 2020-01-17 at 12 59 39 PM](https://user-images.githubusercontent.com/5342/72634798-545c5100-3929-11ea-9566-1c820349ab97.png)

```
$ aws events list-targets-by-rule --rule rule
{
    "Targets": []
}
```

I manually created the state machine target in the console, 

![Screen Shot 2020-01-17 at 1 02 04 PM](https://user-images.githubusercontent.com/5342/72634928-a1402780-3929-11ea-8e4c-2c81d9330eb4.png)

```
$ aws events list-targets-by-rule --rule rule
{
    "Targets": [
        {
            "Id": "Id47670273684",
            "Arn": "arn:aws:states:us-west-2:000000000000:stateMachine:SomeStateMachine",
            "RoleArn": "arn:aws:iam::000000000:role/SomeValidRole"
        }
    ]
}
```

and then did a `terraform plan`. There was no state change detected by Terraform.

```
$ terraform plan
…
…
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

### Steps to Reproduce

1. `terraform apply`

**Comment by TheodoreChuang** [comment]
Not sure what's causes the issue. I was able to add a step function as a cloud watch target with the Terraform below.

Terraform Version
`Terraform v0.12.19
+ provider.archive v1.3.0
+ provider.aws v2.44.0`

`resource "aws_cloudwatch_event_rule" "event_rule" {
  description         = "description"
  name                = "event_rule"
  schedule_expression = "cron(0 10 ? * * *)"
}
resource "aws_cloudwatch_event_target" "event_target" {
  rule     = aws_cloudwatch_event_rule.event_rule.id
  arn      = aws_sfn_state_machine.state_machine.id
  role_arn = aws_iam_role.cwe_sfn_role.arn
}

resource "aws_iam_role" "cwe_sfn_role" {
  name               = "cwe_sfn_role"
  assume_role_policy = data.aws_iam_policy_document.cwe_sfn_assume_role_policy_document.json
}
data "aws_iam_policy_document" "cwe_sfn_assume_role_policy_document" {
  statement {
    actions = [
      "sts:AssumeRole"
    ]

    principals {
      type = "Service"
      identifiers = [
        "states.ap-southeast-2.amazonaws.com",
        "events.amazonaws.com"
      ]
    }
  }
}
resource "aws_iam_role_policy" "cwe_sfn_role_policy" {
  name = "cwe_sfn_role_policy_${terraform.workspace}"
  role = aws_iam_role.cwe_sfn_role.id

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "states:StartExecution"
      ],
      "Resource": [
        "arn:aws:states:ap-southeast-2:123:stateMachine:state_machine"
      ]
    }
  ]
}
EOF
}`

**Comment by ewbankkit** [comment]
Relates: #16080.
IAM role issue.
