### ISSUE TITLE
Adding a Dynamo global table onto an existing table requires the non-global table to be empty

### ISSUE THREAD

**Issue by SarahRiley** [hashicorp/terraform-provider-aws#11678]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.18

### Affected Resource(s)

* aws_dynamodb_global_table

### Terraform Configuration Files

```hcl
resource "aws_dynamodb_table" "example" {
  name             = "tf-${var.service_name}-example"
  billing_mode     = "PAY_PER_REQUEST"
  hash_key         = "userId"
  range_key        = "courseId"
  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"
}

resource "aws_dynamodb_table" "example_west" {
  provider = aws.west

  name             = "tf-${var.service_name}-example"
  billing_mode     = "PAY_PER_REQUEST"
  hash_key         = "userId"
  range_key        = "courseId"
  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

}

resource "aws_dynamodb_global_table" "example" {
  name  = "tf-${var.service_name}-example"

  replica {
    region_name = "us-east-1"
  }

  replica {
    region_name = "us-west-2"
  }

  depends_on = [aws_dynamodb_table.example, aws_dynamodb_table.example_west]
}
```

### Expected Behavior

Global table should have been added

### Actual Behavior

```
Error: ValidationException: One or more parameter values were invalid: Tables must be empty. These tables contain items: [TableReplica{regionName=us-east-1, tableName=tf-foo-example}]
	status code: 400, request id: xxx
```

### Steps to Reproduce

1. Add data to an aws_dynamodb_table
1. Add a global table referencing that
1. `terraform apply`

**Comment by anGie44** [comment]
Hi @SarahRiley , thank you for raising this issue. The behavior described does appear to be a limitation of Global Table creation as listed here in the `Requirements for Adding a New Replica Table` section: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/globaltables_reqs_bestpractices.html

Let me know if you have any further questions or comments related to your use case and the given requirements!

**Comment by anGie44** [comment]
Hi @SarahRiley , I'm going to close this issue as it's gone a bit stale and the behavior described I believe still remains as an upstream limitation. If the issue continues in a newer version of the provider, do re-open for further discussion.
