### ISSUE TITLE
Add support for enabling and configuring Amazon Detective

### ISSUE THREAD

**Issue by marcincuber** [hashicorp/terraform-provider-aws#11672]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to be able to enable and configure AWS Detective. Service is now Generally available.

In general, service is required to be activated per account. Detective is aggregating findings in master account which invites child accounts to join (similar to guard duty).

### New or Affected Resource(s)

Will require number of new resources.

### References

* https://aws.amazon.com/detective/

**Comment by alvaro-fdez** [comment]
Detectives is GA right now, please kindly add support for this particular service.

**Comment by alvaro-fdez** [comment]
Please update.

**Comment by galartsi** [comment]
Would love to know if this is in progress!

**Comment by j-rat** [comment]
In for an update as well!

**Comment by brianabston001** [comment]
+1

**Comment by breathingdust** [comment]
Closing in favor of #23201 as the base resources were implemented and the new issue more specifically tracks a missing area of functionality.
