### ISSUE TITLE
Add version argument to aws_ssm_parameter data source

### ISSUE THREAD

**Issue by enummela** [hashicorp/terraform-provider-aws#11694]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add a version argument to the AWS SSM Parameter data source. This would allow specific versions of the parameter to be retrieved. As far as I can tell, the data source currently only retrieves the latest version of the parameter.

A version argument would make it much easier to rotate parameter values in the Terraform configuration.

### New or Affected Resource(s)

data.aws_ssm_parameter

**Comment by slapula** [comment]
I did a little digging on this issue and it turns out AWS doesn't expose this functionality via the API ([see here](https://docs.aws.amazon.com/sdk-for-go/api/service/ssm/#GetParameterInput)).  Bummer.  Terraform cannot perform this type of request if AWS doesn't support it.  AWS should support it IMO so maybe a ticket with their support team would help fix this.

**Comment by enummela** [comment]
I created a ticket in AWS Developer Forums about this.
https://forums.aws.amazon.com/thread.jspa?threadID=316808

**Comment by caWhite** [comment]
It seems that version history is supported via the [GetParameterHistory](https://docs.aws.amazon.com/cli/latest/reference/ssm/get-parameter-history.html) API. The calls seems to fail for AWS managed parameters however.

```
aws ssm get-parameter-history --name /aws/service/ami-windows-latest/Windows_Server-2019-English-Core-Base

An error occurred (AccessDeniedException) when calling the GetParameterHistory operation: Cannot access/update data for the restricted parameter.
```

**Comment by cfbao** [comment]
It's already supported in the API, the SDK, and in Terraform.
Just use `name = "<parameter-name>:<version-number-or-label>"`

**Comment by breathingdust** [comment]
Hi @enummela! 👋  As @cfbao has mentioned, this looks now supported so will close this issue!
