### ISSUE TITLE
aws_directory_service_directory not allowing access_url to be set

### ISSUE THREAD

**Issue by PartTimeLegend** [hashicorp/terraform-provider-aws#1170]
This appears to be a read-only property when provisioning an AWS directory service. As this is used for SSO purposes the ability to set this as part of Infrastructure as Code is heavily needed.

![image](https://user-images.githubusercontent.com/791578/28275690-95ea00ba-6b0c-11e7-8ef9-325ad2a9bda4.png)

Is there a plan to introduce this feature?

**Comment by Ninir** [comment]
Hey @PartTimeLegend,

It seems this is something that we could totally implement, looking at: https://docs.aws.amazon.com/goto/WebAPI/ds-2015-04-16/CreateAlias

Do you feel getting into the codebase and give this a try? 😃

**Comment by Tensho** [comment]
@Ninir AWS Directory Service doesn't provide API for setting access URL yet.
