### ISSUE TITLE
Support for multiple disks at aws MSK

### ISSUE THREAD

**Issue by dr460neye** [hashicorp/terraform-provider-aws#11713]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
> Kafka, dear Kafka, why do you perform so slowly ;)

Kafka lives by default from increasing the number of disks in most of the use cases together with the partitions.
By optimizing the disks together with some parameters like num.io.threads etc. it can provide even more throughput with less instances.

For now, only a single ebs volume is supported in the current implementation. This is enough for prototyping but not for high throughput requirements or for a resource optimised cluster.

It would be great to be able to provide a list of volumes somehow as an alternative option to just add the disk size, or be able to add a field for the amount of disks. 
It is totally okay to have each disks at the same size.

### New or Affected Resource(s)

* aws_msk_cluster

### Potential Terraform Configuration

```
resource "aws_msk_cluster" "msk" {
  cluster_name           = "mycluster-msk"
  kafka_version          = "2.3.1"
  number_of_broker_nodes = 5

  broker_node_group_info {
    instance_type  = "kafka.m5.xlarge"
    client_subnets = module.vpc.private_subnets
    ebs_volume_size = "10"
    ebs_volumes_per_node = "3"
    security_groups = [ "${aws_security_group.msk.id}" ]
  }
}
```

### References

* #0000

**Comment by mvitaly** [comment]
The feature of having multiple EBS volumes per broker is not supported by the AWS MSK API:
https://docs.aws.amazon.com/msk/1.0/apireference/clusters.html

Do we have a special status/label (blocked?) for these kinds of issues until AWS adds the proper support ?
