### ISSUE TITLE
"No valid credential sources" when the AWS_PROFILE is a temporary session

### ISSUE THREAD

**Issue by cjohansen** [hashicorp/terraform-provider-aws#11729]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.14
+ provider.aws v2.45.0
```

### Affected Resource(s)

S3 backend/provider configuration.

### Terraform Configuration Files

```hcl
terraform {
  backend "s3" {
    bucket = "my-tf-bucket"
    key = "prod/mymodule/tfstate"
    region = "eu-west-1"
    dynamodb_table = "tfstate-locking"
  }
}

provider "aws" {
  version = "~> 2.0"
  region = "eu-west-1"

  assume_role {
    role_arn = "arn:aws:iam::XXXXXXXXXX:role/terraform/ProductionTerraformer"
  }
}
```

Also relevant, my `~/.aws/config`:

```
[profile terraform-prod]
source_profile = myacc
mfa_serial = arn:aws:iam:: XXXXXXXXXX:mfa/christian
role_arn = arn:aws:iam:: XXXXXXXXXX:role/terraform/ProductionTerraformController
output = json
region = eu-west-1
```

### Debug Output

https://gist.github.com/cjohansen/6106cb8f5749dfd54dc84c7f3539e17e

### Expected Behavior

By running `AWS_PROFILE=terraform-production terraform plan`, the AWS SDK should use my access key to assume the `ProductionTerraformController` role in my account. This role grants me access to the terraform S3 bucket and the DynamoDB table, as well as `sts:AssumeRole` for the `ProductionTerraformer` role. The provider should then use this temporary session to assume the `ProductionTerraformer` role, which has Admin access, and use that to provision resources.

### Actual Behavior

Terraform failed to find valid credentials. If I instead use a base profile that has direct access to assume `ProductionTerraformer`, everything works as expected. It seems to me that the AWS provider is unable to work with nested assume_roles.

### Steps to Reproduce

1. Configure an AWS profile `base_profile` with access key
2. Configure another profile `controller` that assumes role A, with `source_profile = base_profile`
3. Configure a Terraform stack with an AWS provider that uses `assume_role` with role B.
4. `AWS_PROFILE=controller terraform plan`

**Comment by justinretzolk** [comment]
Hey @cjohansen 👋 Thank you for taking the time to file this issue! Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?

**Comment by gdavison** [comment]
Since we haven't heard back on this issue, we're going to close the issue. If you are still encountering the error, please open a new issue
