### ISSUE TITLE
Applying lifecycle rule (adding expired_object_delete_marker) doesn't work

### ISSUE THREAD

**Issue by enceladus95** [hashicorp/terraform-provider-aws#11733]
Tried adding **expired_object_delete_marker = true** in the lifecycle rule (expiration section) for an AWS S3 bucket, terraform plan will register the change, terraform apply will output that the change was made but it actually isn't.
No matter how many times you run apply it will never apply that change which makes me think it's a bug with the provider.

**Comment by DrFaust92** [comment]
Hey @enceladus95, 
setting `expired_object_delete_marker` to `true` does not immediately clean delete markers. it usually takes up to 24 hours to apply. this is AWS behaviour. can you confirm by changing the setting an waiting a day to see if this works?

**Comment by wiegandf** [comment]
It doesn't work - after applying and waiting 24hr the plan still shows a change.
