### ISSUE TITLE
Neptune create from snapshot results in "InvalidParameterValue: The parameter ResourceName must be provided and must not be blank."

### ISSUE THREAD

**Issue by trillom** [hashicorp/terraform-provider-aws#11752]
I'm seeing a similar issue to #5360, but when provisioning a Neptune cluster with tagging from an existing snapshot.

```
Error: error updating Neptune Cluster () tags: error tagging resource (): InvalidParameterValue: The parameter ResourceName must be provided and must not be blank.
	status code: 400, request id: ***
```
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.20
+ provider.aws v2.46.0
```

### Affected Resource(s)

* aws_neptune_cluster

### Terraform Configuration Files

```hcl
resource "aws_neptune_cluster" "default" {
  cluster_identifier        = var.snapshot_identifier == null ? var.cluster_identifier : "${var.cluster_identifier}-restored"
  apply_immediately         = var.apply_immediately
  backup_retention_period   = var.retention_period
  engine                    = var.engine
  engine_version            = var.engine_version
  final_snapshot_identifier = "${var.cluster_identifier}-${local.now}-final"
  neptune_subnet_group_name = aws_neptune_subnet_group.default.id
  port                      = var.port
  preferred_backup_window   = var.backup_window
  skip_final_snapshot       = var.skip_final_snapshot
  snapshot_identifier       = var.snapshot_identifier

  # Encryption
  storage_encrypted       = true
  kms_key_arn             = data.aws_kms_key.default.arn

  vpc_security_group_ids = [ var.clusterwide_sg == "" ? aws_security_group.default[0].id : var.clusterwide_sg ]

  tags = merge(local.common_tags, {})
}
```

### Expected Behavior

Neptune Cluster created from snapshot

### Actual Behavior

Above error is thrown, base cluster is created, but apply fails and instances are not created.

### Steps to Reproduce

1. `terraform apply`

### References

* #5360

**Comment by jayvee1110** [comment]
Still no solution for this?

**Comment by kalyansundar** [comment]
still it is continuing, is there any timeline to give a solution for this ?

**Comment by nikolaykolev** [comment]
I've hit the same issue today, it seems it's still not fixed :(

**Comment by chungath** [comment]
I could fix it locally  by doing the  `!d.IsNewResource()` check in [aws/resource_aws_neptune_cluster.go#L678](https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_neptune_cluster.go#L678). 

Existing Code
`
	if d.HasChange("tags") {
`
Fix
`
	if !d.IsNewResource() && d.HasChange("tags") {
`
Basically, only tag during actual resource update.  Similar to the fix done to the RDS issue mentioned above.

I was able to build terraform-provider-aws with the fix and validate it by creating the neptune cluster from a snapshot.

However, I am not able to run the tests. Also, am not able to create a pull request. git push fails with the following error:

- $ git push --set-upstream origin b/aws_neptune_cluster

> remote: Permission to hashicorp/terraform-provider-aws.git denied to chungath.

Can someone take this change and process it?

**Comment by santoshdevops119** [comment]
The issue still persists and its a blocker for planning disaster recovery automation via terraform for neptune DB. Can someone please fix this.

**Comment by NasAmin** [comment]
> I could fix it locally by doing the `!d.IsNewResource()` check in [aws/resource_aws_neptune_cluster.go#L678](https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_neptune_cluster.go#L678).
> 
> Existing Code
> `if d.HasChange("tags") {`
> Fix
> `if !d.IsNewResource() && d.HasChange("tags") {`
> Basically, only tag during actual resource update. Similar to the fix done to the RDS issue mentioned above.
> 
> I was able to build terraform-provider-aws with the fix and validate it by creating the neptune cluster from a snapshot.
> 
> However, I am not able to run the tests. Also, am not able to create a pull request. git push fails with the following error:
> 
> * $ git push --set-upstream origin b/aws_neptune_cluster
> 
> > remote: Permission to hashicorp/terraform-provider-aws.git denied to chungath.
> 
> Can someone take this change and process it?
Sounds like you have a fix for this. Did you apply a fix to a `fork` or did you directly clone this repo and made changes to it?

I think you should be able to push to a fork and then create a PR from it on this repo.

**Comment by FarhanKhan-sains** [comment]
Is there any workaround for this issue?

**Comment by chungath** [comment]
The workaround is to not create any tags on the neptune cluster.

**Comment by FarhanKhan-sains** [comment]
@chungath Thanks, that seems to have fixed the issue for now

**Comment by justinretzolk** [comment]
Hey y'all 👋 Thank you for taking the time to file this issue, and for the ongoing discussion. Given that there's been a number of AWS provider releases since the last update on this issue, can anyone confirm whether you're still experiencing this behavior?

**Comment by tachang** [comment]
I just ran into it as well. Tried to create from snapshot and wouldn't let me.

**Comment by danielcweber** [comment]
#25972 attempts to fix this. It's basically tries to include the change proposed by @chungath, though the referenced file has moved/changed. @chungath: Maybe you could have a quick look whether it captures your intent.

I'm neither familiar with Terraform nor Go but trying to get an internal showstopper resolved.
