### ISSUE TITLE
aws_ssm_patch_baseline approved/rejected patch enhancements

### ISSUE THREAD

**Issue by jdheyburn** [hashicorp/terraform-provider-aws#11767]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In AWS Console, and via `aws-sdk-go` - users can define the following properties of an SSM Patch Baseline:

- Approved patches include non-security updates
- Rejected patches action

These are all optional fields that `resource_aws_ssm_patch_baseline.go` currently does not support.

### New or Affected Resource(s)

* resource_aws_ssm_patch_baseline.go

### Potential Terraform Configuration

```hcl
resource "aws_ssm_patch_baseline" "production" {
  name             = "patch-baseline"
  description      = "Patch Baseline Description"
  approved_patches = ["KB123456", "KB456789"]
  rejected_patches = ["KB987654"]

  # New params below
  approved_patches_enable_non_security = "true"
  rejected_patches_action = "ALLOW_AS_DEPENDENCY"

  ...
}
```

### References

N/A

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 3.28.0 of the Terraform AWS Provider, later today. Thank you to @DrFaust92 for the implementation. 👍
