### ISSUE TITLE
Destroy fails on Elastic Beanstalk Application Version dependency

### ISSUE THREAD

**Issue by ramonpm** [hashicorp/terraform-provider-aws#11763]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.16
+ provider.aws v2.39.0
+ provider.null v2.1.2

### Affected Resource(s)

resource "aws_elastic_beanstalk_application_version"
resource "aws_elastic_beanstalk_environment"

### Terraform Configuration Files

```hcl
resource "aws_elastic_beanstalk_application_version" "default" {
  name        = "${var.slug}"
  application = data.aws_elastic_beanstalk_application.app.name
  description = "Application version created by terraform"
  bucket      = aws_s3_bucket.bucket.id
  key         = aws_s3_bucket_object.app_package.id
}

resource "aws_elastic_beanstalk_environment" "worker" {
  name                = "${var.slug}-worker"
  application        = data.aws_elastic_beanstalk_application.app.name
  tier                    = "Worker"
  solution_stack_name = var.platform_version
  version_label       = aws_elastic_beanstalk_application_version.default.name
}

resource "null_resource" "delay" {
  depends_on = [
    aws_elastic_beanstalk_application_version.default,
    aws_acm_certificate.cert,
    aws_security_group.app_security_group,
    aws_cloudfront_distribution.s3_distribution,
    aws_db_instance.db,
    aws_iam_access_key.es
  ]

  provisioner "local-exec" {
    command = "sleep 60"
  }
}

resource "aws_elastic_beanstalk_environment" "web" {
  # Instead of waiting for worker 10-15 min to prevent Migration clash
  # wait for 1 minute
  depends_on = [null_resource.delay]
  # Web and Worker can't run Migration at the same time
  # depends_on = [aws_elastic_beanstalk_environment.worker]

  name                = "${var.slug}-web"
  application         = data.aws_elastic_beanstalk_application.app.name
  tier                  = "WebServer"
  solution_stack_name = var.platform_version
  cname_prefix        = var.slug
  version_label       = aws_elastic_beanstalk_application_version.default.name
```

### Panic Output

```
Error: Unable to delete Application Version, it is currently in use by the following environments: [e-2vujdrkkt3 e-gj8ybjejz3].
```
But the same environments were destroyed completely prior to this, and there no other environment using this Terraform. The proof is if I ran destroy again it works.
```
aws_elastic_beanstalk_environment.web: Destruction complete after 2m52s
aws_elastic_beanstalk_environment.worker: Destruction complete after 3m27s
```

### Expected Behavior

Destroy process complete without errors.

### Actual Behavior

Destroy fails with this error:
```
Error: Unable to delete Application Version, it is currently in use by the following environments: [e-2vujdrkkt3 e-gj8ybjejz3].
```
Then if I ran destroy again it completes without errors.

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy` -> you get the error
3. `terraform destroy` -> works

### References

* #0000

**Comment by TejasBehra3107** [comment]
@ramonpm any update on this issue ?

**Comment by ramonpm** [comment]
@TejasBehra3107 I've seen it happening again recently, not consistent though. Reckon it's hard to fix something that don't fail consistently.

**Comment by justinretzolk** [comment]
Hey @ramonpm 👋 Thank you for taking the time to file this issue! Given that there's been a number of AWS provider releases since you initially filed it, and since your last update, can you confirm whether you're still experiencing this behavior?

**Comment by ramonpm** [comment]
@justinretzolk, been a while since the last time I faced this issue, and we do run "destroy" very often, every day, then I'd assume it's fixed.

**Comment by justinretzolk** [comment]
Thanks for confirming that! With that in mind, we'll close this issue for now, but if anyone experiences this in the future, please do open a new issue so that we can look into it.
