### ISSUE TITLE
Display Appsync GraphQL schema error

### ISSUE THREAD

**Issue by Ludonope** [hashicorp/terraform-provider-aws#11764]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.20
+ provider.aws v2.46.0

### Affected Resource(s)

* aws_appsync_graphql_api

### Terraform Configuration Files

```hcl
provider "aws" {
  region  = "eu-central-1"
}

resource "aws_appsync_graphql_api" "myapi" {
  authentication_type = "API_KEY"
  name                = "myapi"

  schema = <<EOF
# Some invalid graphql schema here
EOF
}
```

### Expected Behavior

When I try to set the invalid schema manually via the Appsync console, I get a validation error which helps me understand what is wrong and how to fix it.

For example, I tried using a scalar type `Date` which in fact does not exist here, and should be `AWSDate` instead.

I get the message `Type "Date" not found in document.` which is pretty explicit.

When using Terraform I would expect to see this error message when using the same invalid schema.

### Actual Behavior

I get the following output:
```
aws_appsync_graphql_api.myapi: Creating...

Error: error creating AppSync GraphQL API (xxxxxxxxxxxxxxxxxxxxxxxx) Schema: 
Error waiting for schema creation status on AppSync API xxxxxxxxxxxxxxxxxxxxxxxx: 
unexpected state 'FAILED', wanted target 'SUCCESS, ACTIVE'. last error: %!s(<nil>)

  on appsync.tf line 5, in resource "aws_appsync_graphql_api" "myapi":
   5: resource "aws_appsync_graphql_api" "myapi" {
```

### Steps to Reproduce

1. Create an Appsync GraphQL api with an invalid schema such as
```
schema {
    query: Query
    mutation: Mutation
}
type Query {
    # Get a single value of type 'Post' by primary key.
    singlePost(id: ID!): Post
}
type Mutation {
    # Put a single value of type 'Post'.
    # If an item exists it's updated. If it does not it's created.
    putPost(id: ID!, title: String!): Post
}
type Post {
    id: ID!
    date: Date!
    title: String!
}
```

2. `terraform apply`

**Comment by justinretzolk** [comment]
Hey @Ludonope 👋 Thank you for taking the time to file this issue! Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?

**Comment by Ludonope** [comment]
Hi, it's been a while since I filed this issue and I'm not using any of that anymore so I can't say :/

Gonna close it since no one else commented on there, must not be a common problem.

**Comment by Mainstay-Noah-Huppert** [comment]
@justinretzolk I can confirm that this is still an issue. It would be nice if the provider bubbled the error up instead of just saying "failed".
