### ISSUE TITLE
inconsistent final plan

### ISSUE THREAD

**Issue by nomaddevops** [hashicorp/terraform-provider-aws#11766]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.6
EDIT : provier aws is in version 2.46.0
### Affected Resource(s)

* data aws_availability_zones

### Terraform Configuration Files

```hcl
data "aws_availability_zones" "available" {
  state = "available"
}
module "compute" {
  source = "git@github.com:nomaddevops/compute.git"

  # GENERAL 
  name = "Compute"
  environment = var.platform_environment
  vpc_id = module.shell.vpc_id
  image_id = data.aws_ami.aws_optimized_ecs.id
  service = "ECS"
  user_data = data.template_file.ecs.rendered

  # NETWORK
  is_multi_az = var.is_multi_az
  availability_zones = var.is_multi_az == true ? data.aws_availability_zones.available.names : list(data.aws_availability_zones.available.names[0])
  private_subnets = module.shell.public_subnet_ids
  
  # LOGS
  bucket_logs = module.shell.s3_logging_bucket_name

  # CWL MONITORING
  enable_alarms = var.enable_alarms
  enable_scaling = var.enable_scaling
  
  # IAM
  assume_role = file("${path.module}/templates/iam/assume/ec2.json")
  iam_policy = file("${path.module}/templates/iam/policies/ecs.json")

  # ASG CONFIGURATION
  min_size = var.min_size
  max_size = var.max_size
  desired_capacity = var.desired_capacity

  # LOCAL STORAGE
  block_devices = var.block_devices
}
```

### Expected Behavior

Return a list of availability_zones 

### Actual Behavior

Got a final inconsistent plan, provider "aws" produced an invalid new value for
.availability_zones: was known, but now unknown.

### Steps to Reproduce

not sure you can, instead i share my module ?

* #0000

**Comment by nomaddevops** [comment]
Found more information on it, it's linked to autoscaling group definition, I'm using availability_zones and vpc_zones_identifier arguments inside, I've delete the argument to solve this.
You propably can close this it's up to you

**Comment by justinretzolk** [comment]
Thank you for taking the time to file this issue, and for the follow up! Since this seems to have been resolved by a configuration change, we'll go ahead and close this one out. If you do run into any further issues, please do let us know!
