### ISSUE TITLE
Cannot Combine Top Level Provider Credentials, with Assume Role Provider in Module

### ISSUE THREAD

**Issue by rorychatterton** [hashicorp/terraform-provider-aws#11779]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.20
+ provider.aws v2.46.0

### Affected Resource(s)

* provider

### Terraform Configuration Files

Top Level File
```hcl
provider "aws" {
  alias   = "root"
  version = "~> 2.46"
  profile = "..."
}

module "test_auto_role_module" {
  source = "./module"

  providers = {
    aws.target_account = aws.root
  }
}
```
In Module
```hcl

provider "aws" {
  alias   = "target_account"
  version = "~> 2.46"
  assume_role {
    role_arn = local.role_arn
  }
}

locals {
  role_arn = "arn:aws:iam::817981210047:role/RootAdministratorRole"
}

data "aws_availability_zones" "available" {
  provider = aws.target_account

  state = "available"
}
```

### Debug Output

https://gist.github.com/rorychatterton/c8a043c54326b8b78fa00a20bde7eaf5

### Expected Behavior

Terraform would take the credentials defined in the top level file under `aws.root`, combine it with the assumed role defined in the nested module `aws.target_account`, and work.

### Actual Behavior

I receive an invalid credentials error:

```powershell
PS ... > terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

Error: No valid credential sources found for AWS Provider.
        Please see https://terraform.io/docs/providers/aws/index.html for more information on
        providing credentials for the AWS Provider

  on module\main.tf line 6, in provider "aws":
   1: provider "aws" {

```

### Steps to Reproduce

1. Create two accounts, and create a role which one account can use to assume into the other.
2. Update the provider information to use your own locally provided role/account which has sts permission to log into the other account.
3. `terraform apply`

### Important Factoids

I have confirmed that this role has correct permissions. We can see this in the below example.

If you assume role in the top level module, everything works, even if the role_name was generated by a variable in the underlying module. I.e.

Top Level File
```hcl
provider "aws" {
  alias   = "root"
  version = "~> 2.46"
  profile = "..."
  assume_role {
    role_arn = module.test_auto_role_module.role_arn
  }
}

module "test_auto_role_module" {
  source = "./module"

  providers = {
    aws.target_account = aws.root
  }
}
```
In Module
```hcl
provider "aws" {
  alias   = "target_account"
  version = "~> 2.46"
}

locals {
  role_arn = "arn:aws:iam::817981210047:role/RootAdministratorRole"
}

data "aws_availability_zones" "available" {
  provider = aws.target_account

  state = "available"
}

output "role_arn" {
  value = local.role_arn
}

```
The use case for this is an account factory, where terraform creates an account in a module, then using the same module, generates a provider on the fly with the newly discovered account ID and default root role, then assumes into it to create additional resources.

Without this functionality, I now have to tightly couple the top level Terraform Files with the underlying code. Not the end of the world, but pretty messy to grok.

### References
N/A

**Comment by justinretzolk** [comment]
Hey @rorychatterton 👋 Thank you for taking the time to file this issue! Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?

**Comment by otani88** [comment]
Same problem. We have external process which inject env variables with credentials to runtime with AWS provider (version 3.74.2). There are: `AWS_ROLE_ARN`, `AWS_WEB_IDENTITY_TOKEN_FILE` and `AWS_ROLE_SESSION_NAME`. AWS provider doesn't respect it for assume_role which specified in provider configuration block

**Comment by womblep** [comment]
I have similar issue, AWS_ROLE_ARN is not being respected
