### ISSUE TITLE
r/aws_ecs_service with count returns null output for attributes

### ISSUE THREAD

**Issue by davidgereb** [hashicorp/terraform-provider-aws#11771]
When using an `aws_ecs_service` with `count` outputs for attributes are `null`. Works fine with other resources.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.12.20
+ provider.aws v2.29.0
+ provider.external v1.2.0
```

### Affected Resource(s)
* aws_ecs_service

### Terraform Configuration Files

```hcl
resource "aws_ecs_service" "main" {
  count = var.count
  name = "${var.application}-${count.index}"
  # ...
}

output "first_service_name" {
  value = aws_ecs_service.main[0].name
}
```

### Expected Behavior
Terraform should output the name of the service.

### Actual Behavior
Terraform returns `null` for the name of the service, results in output not being shown.

### Steps to Reproduce
1. Set up an `aws_ecs_service` with `count`
2.`terraform apply`

**Comment by justinretzolk** [comment]
Hey @DavidGereb 👋 Thank you for taking the time to file this issue! Given that there's been a number of Terraform and AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?
