### ISSUE TITLE
Naming Convention for aws_codepipeline is not allowed spaces

### ISSUE THREAD

**Issue by AzySir** [hashicorp/terraform-provider-aws#11778]
I'm not sure if this is an aws or terraform issue however when I create a aws_codepipeline via terraform I find that you cannot add spaces into the name. When you create the pipeline manually in the AWS Management Console spaces are allowed.

In the code below if I have `name = "Build Validate"` then it does not work through terraform. However works inside of the aws console UI the spaces are accepted.

**Terraform Code -** 
```
resource "aws_codepipeline" "mycompany_codepipeline" {
 ...
 stage {
    name = "Build_Validate"
    action {
      name             = "Build"
      category         = "Build"
      owner            = "AWS"
      provider         = "CodeBuild"
      input_artifacts  = ["SourceArtifact"]
      output_artifacts = ["ValidatedArtifact"]
      version          = "1"

      configuration = {
        ProjectName = aws_codebuild_project.mycompany.name
      }
    }
  }
```

**Error Received -** 
```
Error: [ERROR] Error updating CodePipeline (mycompany-codepipeline): ValidationException:
  on pipeline.tf line 1, in resource "aws_codepipeline" "mycompany_codepipeline":
   1: resource "aws_codepipeline" "mycompany_codepipeline" {```

**Comment by justinretzolk** [comment]
Hey @AzySir 👋 Thank you for taking the time to submit this issue! I took a look over the relevant [AWS API documentation](https://docs.aws.amazon.com/codepipeline/latest/APIReference/API_PipelineDeclaration.html) and it looks like that API does not accept spaces, so this would be related to the underlying API rather than the AWS provider: 

> Pattern: [A-Za-z0-9.@\-_]+
