### ISSUE TITLE
aws_lb_listener_rule condition block not accepting host_header block

### ISSUE THREAD

**Issue by autoist** [hashicorp/terraform-provider-aws#11788]
### Terraform Version
Terraform v11.13
AWS Provider v2.49

### Affected Resource(s)

* aws_lb_listener_rule

### Expected Behavior

Documentation at https://www.terraform.io/docs/providers/aws/r/lb_listener_rule.html shows that I can use a "host_header" block in the "condition" block. This block should work and allow for the rule to be created/updated.

### Actual Behavior

When this block is used and "terraform apply" is run there is an error saying that "host_header" isn't recognized.

### Steps to Reproduce

1. `terraform apply`

### Questions

So why is this failing? Is it an issue with the AWS provider version? Should I be using a new version? Could it be the terraform version?

You thought are appreciated.

**Comment by sean-wallace** [comment]
@autoist I found the same issue, but managed to fix it by using the older form:

```
condition {
    field  = "host-header"
    values = ["some.host.name"]
  }
```

**Comment by justinretzolk** [comment]
Hey @autoist 👋 Thank you for taking the time to file this issue. Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?
