### ISSUE TITLE
AWS Pinpoint - Control "Default message type" option

### ISSUE THREAD

**Issue by eladazary** [hashicorp/terraform-provider-aws#11791]
Can you please add the ability to control "Default message type" option (Promotional/Transactional) ?
Currently the Promotional option is the default and I need to change it manually.

Thanks,
Elad

**Comment by DrFaust92** [comment]
Hey @eladazary, can you refer to the specific resource and argument?

**Comment by eladazary** [comment]
Sure, the resource aws_pinpoint_sms_channel should have the ability to configure the default message type (Promotional/Transactional).

**Comment by DrFaust92** [comment]
This is something that is not supported by the underlying aws sdk as far as i can see. not as a property to set or read.

i see that it can be set as part of the `SendMessages` Pinpoint API but that's not related to the `aws_pinpoint_sms_channel` resource. or any Terraform Resource.
