### ISSUE TITLE
AWS Provider 2.46 - Terraform thinks resources don't exist in AWS, but they do exist

### ISSUE THREAD

**Issue by LennyCastaneda** [hashicorp/terraform-provider-aws#11807]
Terraform AWS Provider 2.46

When I did a 'Terraform plan' Terraform attempted to recreate resources that already existed despite no changes to my TF code. 

I noticed this after upgrading AWs provider from 2.34 to 2.46.

Attached below is a screen shot of 1 of 25 resources that Terraform is trying to recreate but already exists in the AWS account.

Please let me know if this is happening on your end and if you can recreate it. Thanks.

![CloudWatch](https://user-images.githubusercontent.com/9893446/73410535-22070800-42c8-11ea-9584-e20af27b34af.PNG)
![TF-CloudWatch](https://user-images.githubusercontent.com/9893446/73410536-22070800-42c8-11ea-80ef-8cab9f302bbf.PNG)

### Terraform Version

Terraform v0.12.19

### Affected Resource(s)

All resources were afftected in this particular module.

**Comment by justinretzolk** [comment]
Hey @LennyCastaneda 👋 Thank you very much for taking the time to file this issue! Given that there's been a number of AWS provider releases since you initially field it, can you confirm whether you're still experiencing this behavior?

**Comment by LennyCastaneda** [comment]
Hi Justin,

Thanks for the response. Although when I filed this issue it was happening when I was working with TF v0.12.x and provisioning AWS code build/pipeline resources is when I saw the issue, but now im not working on those resouexss anymore and using Terraform 1.x and haven’t seen this behavior.

Probably safe to close it. At least when someone reads the issue they know all that needs to happen is simply re-run terraform apply and error is resolved.

On Nov 18, 2021, at 11:52 AM, Justin Retzolk ***@***.***> wrote:

﻿
Hey @LennyCastaneda 👋 Thank you very much for taking the time to file this issue! Given that there's been a number of AWS provider releases since you initially field it, can you confirm whether you're still experiencing this behavior?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
