### ISSUE TITLE
aws_api_gateway_integration.root must be replaced ... every time I apply

### ISSUE THREAD

**Issue by jeffmacdonald** [hashicorp/terraform-provider-aws#11810]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.20
+ provider.aws v2.46.0

### Affected Resource(s)

* aws_api_gateway_integration

### Terraform Configuration Files

```hcl
# This provider is to make ACM Certificate in us-east-1
provider "aws" {
  region  = "us-east-1"
  version = "2.46"
  alias   = "us-east-1"
}

resource "aws_api_gateway_rest_api" "this" {
  name        = var.api_name
  description = var.api_description
}

resource "aws_api_gateway_resource" "webshell" {
  rest_api_id = aws_api_gateway_rest_api.this.id
  parent_id   = aws_api_gateway_rest_api.this.root_resource_id
  path_part   = "health"
}

resource "aws_api_gateway_method" "webshell" {
  rest_api_id   = aws_api_gateway_rest_api.this.id
  resource_id   = aws_api_gateway_resource.webshell.id
  http_method   = "ANY"
  authorization = "NONE"
}

resource "aws_api_gateway_integration" "webshell" {
  rest_api_id = aws_api_gateway_rest_api.this.id
  resource_id = aws_api_gateway_method.webshell.resource_id
  http_method = aws_api_gateway_method.webshell.http_method

  integration_http_method = "POST"
  type                    = "HTTP_PROXY"
  uri = "http://example_domain/health/"
# uri                     = "${var.webshell_endpoint}/health"
}

resource "aws_api_gateway_method" "root" {
  rest_api_id   = aws_api_gateway_rest_api.this.id
  resource_id   = aws_api_gateway_rest_api.this.root_resource_id
  http_method   = "ANY"
  authorization = "NONE"
}

# This will make it such that if someone tries to access /
# they will get a 500 error.
# There are ways to write default messagses. I haven't found them yet.
resource "aws_api_gateway_integration" "root" {
  rest_api_id = aws_api_gateway_rest_api.this.id
  resource_id = aws_api_gateway_method.root.resource_id
  http_method = aws_api_gateway_method.root.http_method

  integration_http_method = "POST"
  type                    = "MOCK"
}

# A note that if you are using a Custom Domain name (as we are) that the stage_name
# will not appear in the URL path (which is what we want)
resource "aws_api_gateway_deployment" "deployment" {
  depends_on = [
    aws_api_gateway_integration.root,
    aws_api_gateway_integration.webshell
  ]

  rest_api_id = aws_api_gateway_rest_api.this.id
  stage_name    = "jj"
}
```

### Debug Output

https://gist.github.com/jeffmacdonald/950d43a4a7ab16b7988e6fdde1514b6f

### Expected Behavior

With zero infra setup, I ran `terraform apply` and it created all resources and everything worked fine. Then I ran `apply` again, and I would have expected it to tell me that no resources need to be updated, as I changed nothing.

### Actual Behavior

Instead, it said it had to `module.apig.aws_api_gateway_integration.root must be replaced` (see Debug logs above in the Gist)

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

* #0000

**Comment by justinretzolk** [comment]
Hey @jeffmacdonald 👋 Thank you for taking the time to file this issue! Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?

**Comment by evanstachowiak** [comment]
@justinretzolk , I think I figured out the issue here.

If the `aws_api_gateway_integration` resource is of type "MOCK" AND `integration_http_method` is set, the AWS API silently ignores the `integration_http_method` setting. I suppose these combinations are not supported? Then, the next time an apply is run, terraform sees that `integration_http_method` is not set and recreates the resource. Wash, repeat, because this is never actually set with type == "MOCK".

@jeffmacdonald, a solution here is to remove your `integration_http_method` setting.
