### ISSUE TITLE
Ec2 Key_Name not being pulled into state 

### ISSUE THREAD

**Issue by Grasume** [hashicorp/terraform-provider-aws#11812]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

12.20

### Affected Resource(s)

Aws Ec2 aws_instance

Performing a Terraform Import should pull in the Key_Name feild. 

### Expected Behavior

Key_Name is left empty after a terraform import

### Actual Behavior
Terraform Plan informs me the below.
+ key_name            = "ServiceDefault" # forces replacement

Doing a Terraform Show the Key_name field is not present. 

### Steps to Reproduce

Restore an EC2 with the backup service
1. Terraform import 
2. Terraform plan 

* #0000

**Comment by justinretzolk** [comment]
Hey @Grasume 👋 Thank you for taking the time to file this issue! Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?

**Comment by Grasume** [comment]
I'm no longer working on this project, and don't remember the full spec of this so im going to close this out.
