### ISSUE TITLE
Changing aws_mq_broker engine_version should not force resource replacement

### ISSUE THREAD

**Issue by WillSewell** [hashicorp/terraform-provider-aws#11827]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon MQ allows you to upgrade the engine version in place, however the AWS provider forces a replacement of the resource if the engine_version is updated.

### New or Affected Resource(s)

* aws_mq_broker

**Comment by tomelliff** [comment]
This support was added in [v1.15.44 of the Go SDK](https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v11544-2018-09-27) but was previously not possible to change as there wasn't an `EngineVersion` field on the `UpdateBrokerRequest` struct.

**Comment by DrFaust92** [comment]
addressed in #12758
