### ISSUE TITLE
Additional QuickSight resource: aws_quicksight_iam_policy_assignment

### ISSUE THREAD

**Issue by tdewitt** [hashicorp/terraform-provider-aws#11832]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the     ↳ community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the    ↳ request 
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

On 2019-10-20, AWS released new APIs for QuickSight that allow for configuration management.  This request is in response to https://github.com/terraform-providers/terraform-      ↳ provider-aws/issues/10990#issuecomment-558244278, requesting that a feature request per resource be created.

### New or Affected Resource(s)

* aws_quicksight_iam_policy_assignment

### References

* https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-quicksight-adds-api-support-for-data-dashboard-spice-and-permissions/
* https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v12539-2019-11-20

### References

* https://github.com/terraform-providers/terraform-provider-aws/issues/10990

**Comment by leppikallio** [comment]
https://github.com/terraform-providers/terraform-provider-aws/pull/12203
