### ISSUE TITLE
Add url attribute to aws_sqs_queue resource

### ISSUE THREAD

**Issue by skolsuper** [hashicorp/terraform-provider-aws#11848]
Request:  export `url` as an attribute to the `aws_sqs_queue` resource.

Ah Github helpfully suggests #7850 as a similar issue.  Can add `url` as an identical attribute / alias to `id` on the resource?  I didn't realise `id === url` and I know I'm not the only one 😓 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Right now, I can get a queue url from a [Data Source: aws_sqs_queue](https://www.terraform.io/docs/providers/aws/d/sqs_queue.html#attributes-reference) but not from a [Resource: aws_sqs_queue](https://www.terraform.io/docs/providers/aws/r/sqs_queue.html#attributes-reference).  Adding both a resource and a data source causes issues with `terraform destroy`.

### New or Affected Resource(s)

* `aws_sqs_queue`

### Potential Terraform Configuration

```hcl
resource "aws_sqs_queue" "my_queue" {
  name = "my_queue"
}


resource "aws_ssm_parameter" "queue_url" {
  name      = "QUEUE_URL"
  type      = "String"
  value     = aws_sqs_queue.my_queue.url
  overwrite = true
}

```

**Comment by whatsfordinner** [comment]
Ah, should have checked the issue before I raised my PR. It's basically identical to the one raised by @kurtmc. Should I just close mine?

**Comment by kurtmc** [comment]
@whatsfordinner your PR is more complete as you have added a test. I'd prefer to close mine.
