### ISSUE TITLE
Pinpoint SMS sender ID not controlled by terraform

### ISSUE THREAD

**Issue by eladazary** [hashicorp/terraform-provider-aws#11853]
In order to configure the SMS sender ID in Pinpoint App I've created "aws_pinpoint_sms_channel" resource and set the sender_id param.
After the app was created it didn't changed the sender ID and set it as the AWS default value.

Please assist.

**Comment by bflad** [comment]
Looks like this is showing up in the resource acceptance testing here on update:

```
=== CONT  TestAccAWSPinpointSMSChannel_full
resource_aws_pinpoint_sms_channel_test.go:61: Step 3/3 error: Check failed: Check 2/6 error: aws_pinpoint_sms_channel.test_sms_channel: Attribute 'sender_id' expected "1234", got ""
--- FAIL: TestAccAWSPinpointSMSChannel_full (69.48s)
```

The code is only passing `sender_id` if it has a change on update:

https://github.com/hashicorp/terraform-provider-aws/blob/075f1302acb2d325c47e0dcebc169c7d544de47c/aws/resource_aws_pinpoint_sms_channel.go#L62-L64

Which seems incorrect as evidenced by the test -- the `UpdateSmsSettings` API call does not have the parameter and immediately after the `GetSmsSettings` API call has the `SenderId` unexpectedly removed.
