### ISSUE TITLE
aws_instance - ebs_optimized = true -> null # forces replacement

### ISSUE THREAD

**Issue by pscadiz** [hashicorp/terraform-provider-aws#11878]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.20
+ provider.aws v2.47.0

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

Showing module used, pointing out that ebs_optimized is omitted 
```hcl
variable "ami" {}
variable "instance_type" {}
variable "key_name" {}
variable "subnet_id" {}
variable "user_data" {}
variable "volume_size" { default = null }
variable "volume_type" { default = null }

resource "aws_instance" "instance" {
  ami                     = var.ami
  disable_api_termination = true
  instance_type           = var.instance_type
  key_name                = var.key_name
  monitoring              = true
  vpc_security_group_ids  = [aws_security_group.security_group.id]
  subnet_id               = var.subnet_id
  user_data               = var.user_data
  iam_instance_profile    = aws_iam_instance_profile.iam_instance_profile.id

  root_block_device {
    volume_type = var.volume_type
    volume_size = var.volume_size
  }
}
```

### Expected Behavior

```
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

### Actual Behavior

```
  # module.web.aws_instance.instance must be replaced
-/+ resource "aws_instance" "instance" {
      - ebs_optimized                = true -> null # forces replacement
     }
```

### Steps to Reproduce

terraform plan

### Important Factoids

Running t3a.large, which is an EBS Optimized instance by default

**Comment by ChanduReddy123** [comment]
I didn't change a thing in my ec2 module but for some reason it is trying to recreate the ec2 server 
![image](https://user-images.githubusercontent.com/29923972/73836750-fb9c1c00-4835-11ea-9f67-9f626dbf8367.png)

**Comment by roman-vynar** [comment]
Workaround:
```
  lifecycle {
    ignore_changes = [ebs_optimized]
  }
```

**Comment by live2rock** [comment]
> Workaround:
> 
> ```
>   lifecycle {
>     ignore_changes = [ebs_optimized]
>   }
> ```
Thanks, it works!

**Comment by tometzky** [comment]
I think you can just delete this unneeded attribute from the instance, as modern and future instance types most probably won't need it:
```
aws ec2 modify-instance-attribute --instance-id i-feedfacecaffef00d --no-ebs-optimized
```

**Comment by justinretzolk** [comment]
Hey @pscadiz 👋 Thank you very much for taking the time to file this issue! Given that there's been a number of AWS provider releases (and a couple of workarounds posted above!) since you initially filed it, can you confirm whether you're still experiencing this behavior?

**Comment by pscadiz** [comment]
I think this issue can be closed. Plans are only calling for modification instead of replacement when last tested (at aws provider version 3.66 now), and other than that the lifecycle policy and overrides can work around the problem. Thanks!
