### ISSUE TITLE
ECS Capacity Provider: error when refers attribute of aws_ecs_capacity_provider

### ISSUE THREAD

**Issue by franzramadhan** [hashicorp/terraform-provider-aws#11883]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.11.14
+ provider.aws v2.47.0
```

### Affected Resource(s)

* aws_ecs_capacity_provider

### Terraform Configuration Files

```hcl
resource "aws_ecs_capacity_provider" "ec2" {
  name = "${module.ecs-cluster-naming.name}"

  auto_scaling_group_provider {
    auto_scaling_group_arn         = "${aws_autoscaling_group.main.arn}"
    managed_termination_protection = "ENABLED"
  }
}

resource "aws_ecs_cluster" "this" {
  name = "test"

  capacity_providers = [
    "${aws_ecs_capacity_provider.ec2.name}"
  ]
}
```

### Expected Behavior

```
${aws_ecs_capacity_provider.ec2.name} can be referred
```

### Actual Behavior

```
Error: Error asking for user input: 1 error occurred:
        * Cycle: aws_ecs_capacity_provider.ec2, aws_ecs_cluster.this
```

### Steps to Reproduce

`terraform init && terraform plan`

### References
https://github.com/terraform-providers/terraform-provider-aws/issues/11338#issuecomment-569333231

**Comment by DrFaust92** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/22672
