### ISSUE TITLE
Support multiple aws_ec2_transit_gateway_vpc_attachment

### ISSUE THREAD

**Issue by awprice** [hashicorp/terraform-provider-aws#11880]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At the moment you can retrieve information about a single `aws_ec2_transit_gateway_vpc_attachment` using a data source. This enhancement is to be able to retrieve multiple `aws_ec2_transit_gateway_vpc_attachments` using a data source.

Retrieving multiple can already be done in the API - see references.

### New or Affected Resource(s)

* aws_ec2_transit_gateway_vpc_attachments

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
data "aws_ec2_transit_gateway_vpc_attachments" "attachments" {
  filter {
    name   = "vpc-id"
    values = ["vpc-12345678"]
  }
}
```

### References

* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeTransitGatewayVpcAttachments.html

**Comment by Maarc-D** [comment]
you could add comment to merge my code to solve it : https://github.com/terraform-providers/terraform-provider-aws/pull/12409 ;)
