### ISSUE TITLE
Malforming an aws_security_group_rule resource returns ALL security groups and rules that exist on account in error response.

### ISSUE THREAD

**Issue by mijdavis2** [hashicorp/terraform-provider-aws#11899]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_security_group_rule

### Terraform Configuration Files

```hcl
resource "aws_security_group_rule" "alb_egress_http_to_task" {
  type                     = "egress"
  from_port                = 80
  to_port                  = 80
  protocol                 = "tcp"
  source_security_group_id = "id-12345"
  security_group_id        = ""
  description              = "http_to_ecs_myservice"
}
```

### Debug Output

https://gist.github.com/mijdavis2/15cda299f25ba1bc4047edb84f9f0f49

### Expected Behavior

Tell the user that `security_group_id` should not be blank or an empty string.

### Actual Behavior

Output every single security group and rule in the target region/account.

### Steps to Reproduce

Use the above resource with valid inputs aside from `security_group_id`

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @mijdavis2 👋 Thank you very much for taking the time to raise this issue. Given that there's been a number of AWS provide releases since you initially filed it, can you confirm whether you're still experiencing this behavior?
