### ISSUE TITLE
"No valid credential sources found" with imported resources 

### ISSUE THREAD

**Issue by spatinolang-vtr** [hashicorp/terraform-provider-aws#11929]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

❯ terraform -v          
Terraform v0.12.20
+ provider.aws v2.47.0
+ provider.random v2.2.1

### Affected Resource(s)

* aws_[ALL]

### Terraform Configuration Files

https://gist.github.com/spatinolang-vtr/c66cebce39787e1e10be28927df01b66

### Debug Output

https://gist.github.com/spatinolang-vtr/193f75df5aa69a6acda543ec5c141d73

### Expected Behavior

* The credentials from ~/.aws/credentials should be used. 
* Terraform should be able to complete the plan

### Actual Behavior

* The credentials from ~/.aws/credentials are not used
* Terraform does not complete the plan

### Important Factoids

* It works when the credentials are configured directly in the .tf file (access_key+ secret_key)
* In a similar project without imported resources the ~/.aws/credentials file is used correctly (same profile)
* Similar behaviour here: https://github.com/terraform-providers/terraform-provider-aws/issues/590#issuecomment-515013966

**Comment by justinretzolk** [comment]
Hey @spatinolang-vtr 👋 Thank you for taking the time to submit this issue. Given that there's been a number of AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?

**Comment by gdavison** [comment]
Since we haven't heard back, I'm going to close this issue. If you are still experiencing this problem, please open a new issue
