### ISSUE TITLE
[Batch] Add Tags to the ECS cluster created by AWS Batch

### ISSUE THREAD

**Issue by hdryx** [hashicorp/terraform-provider-aws#11951]
### Description

Actually when we create a Batch using Terraform we can only assign Tags to the **aws_batch_compute_environment** resource. 
The EC2 instance created by Batch is correctly tagged but the ECS cluster itself doen't have any Tag.

For managment and billing purpose it would be nice to be able to Tag the ECS cluster too.

**Comment by ericscales** [comment]
Any chance this can be implemented?
