### ISSUE TITLE
Output for resource with for_each is empty

### ISSUE THREAD

**Issue by iancward** [hashicorp/terraform-provider-aws#11955]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.19
+ provider.aws v2.42.0
```

### Affected Resource(s)

* aws_network_acl_rule

### Terraform Configuration Files

```hcl
data "aws_network_acls" "acl1" {
  vpc_id = foo

  tags = {
    Name = "acl1"
  }
}

data "aws_network_acls" "acl2" {
  vpc_id = foo

  tags = {
    Name = "acl2"
  }
}

data "aws_network_acls" "acl3" {
  vpc_id = foo

  tags = {
    Name = "acl3"
  }
}

locals {
  all_nacl_ids = setunion(
    data.aws_network_acls.acl1.ids,
    data.aws_network_acls.acl2.ids,
    data.aws_network_acls.acl3.ids.
  }
}

resource "aws_network_acl_rule" "allow_egress_any_any" {
  for_each local.all_nacl_ids

  network_acl_id = each.value
  egress      = "true"
  rule_action = "allow"

  rule_number = 100
  cidr_block  = "0.0.0.0/0"
  protocol    = "-1"
}

output "all_egress_allow_any_to_any_nacl_rule_ids" {
  description = "Network ACL ID - all_egress_allow_any_to_any"
  value       = [for nacl_rule in aws_network_acl_rule.all_egress_allow_any_to_any : nacl_rule.id]
} 
```

### Expected Behavior

Output should contain nacl IDs in a list.

### Actual Behavior

Empty list is saved to state for the output.
State file:
```json
{
  ...
  "outputs": {
    "all_egress_allow_any_to_any_nacl_rule_ids": {
      "value": [],
      "type": [
        "tuple",
        []
      ]
    }
  ...
}
```

stdout from `apply`:
```
Outputs:

all_egress_allow_any_to_any_nacl_rule_ids = []
```
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This is following the [splat documentation](https://www.terraform.io/docs/configuration/expressions.html#splat-expressions)

Additionally, there is an [example](https://github.com/terraform-providers/terraform-provider-aws/blob/4299f558b13b061228353a30fa021f5dd2bd7815/website/docs/d/subnet_ids.html.markdown#example-usage) with similar list comprehension elsewhere in the documentation that seems to indicate this should work.

**Comment by justinretzolk** [comment]
Hey @iancward 👋 Thank you for taking the time to file this issue. Given that there's been a number of AWS provider and Terraform releases since you initially filed it, can you confirm whether you're still experiencing this behavior?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
