### ISSUE TITLE
AWS CodeBuild support for EFS

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#11961]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> You can now use Amazon Elastic Filesystem (EFS) in AWS CodeBuild build jobs.

### New or Affected Resource(s)

* [`aws_codebuild_project`](https://www.terraform.io/docs/providers/aws/r/codebuild_project.html)

### Potential Terraform Configuration

```hcl
resource "aws_codebuild_project" "example" {
  file_system_location {
    type = "EFS"
    ...
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/02/aws-codebuild-adds-support-for-amazon-efs/).
Requires [AWS SDK v1.28.12](https://github.com/aws/aws-sdk-go/releases/tag/v1.28.12):
* https://github.com/terraform-providers/terraform-provider-aws/pull/11893

**Comment by flroainmagnin** [comment]
Hi,

I also need this feature because codebuild cannot resolv DNS EFS endpoint :/

Thanks

**Comment by aduzsardi** [comment]
ditto for @florianmagnin message

**Comment by jamesflightwsf** [comment]
Hi, this feature would be really useful. I noticed there's an open PR for this https://github.com/terraform-providers/terraform-provider-aws/pull/12130

Is this likely to be merged soon?

Thanks

**Comment by jamesk322** [comment]
This would be great, is there an update on when we're likely to see this?

**Comment by praveenk0535** [comment]
Really need this. Any update when we can get this?
