### ISSUE TITLE
Add support for setting awsVpcTrunking in aws_ecs_cluster resource

### ISSUE THREAD

**Issue by cutik** [hashicorp/terraform-provider-aws#11988]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS ECS cluster supports setting AWSVPC Trunking to increase number of ENIs for EC2 instances.
However currently only setting for containerInsights is supported.

### New or Affected Resource(s)

**aws_ecs_cluster**

### Potential Terraform Configuration

```hcl
resource "aws_ecs_cluster" "ecs_cluster" {
  name = var.cluster_name
  setting {
    name  = "awsvpcTrunking" # NOT IMPLEMENTED IN TERRAFORM YET
    value = "enabled"
  }
}
```

### Actual behaviour:

`Error: expected setting.0.name to be one of [containerInsights], got awsvpcTrunking`

**Comment by ewbankkit** [comment]
[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/06/Amazon-ECS-Improves-ENI-Density-Limits-for-awsvpc-Networking-Mode/).
[Blog post](https://aws.amazon.com/blogs/compute/optimizing-amazon-ecs-task-density-using-awsvpc-network-mode/).
[Developer guide](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-instance-eni.html).

`awsvpcTrunking` is enabled via the ECS account settings.
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/10168

**Comment by adamhathcock** [comment]
I'd like to support all values: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_PutAccountSettingDefault.html

Not sure when these were added but they're the same:
`serviceLongArnFormat`
`taskLongArnFormat` 
`containerInstanceLongArnFormat`

**Comment by d4nyll** [comment]
FYI this is related to https://github.com/terraform-providers/terraform-provider-aws/issues/10168
