### ISSUE TITLE
filter data source aws_route53_resolver_rules based on tags

### ISSUE THREAD

**Issue by barrabyte** [hashicorp/terraform-provider-aws#12011]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_route53_resolver_rules

### Terraform Configuration Files

```hcl
data "aws_route53_resolver_rules" "example" {
  tags = {
    Environment = "dev"
  }
}
```

### Expected Behavior

The example in the documentation illustrates how to obtain a list of resolver rules using tags as filters. 

### Actual Behavior

```Error: Unsupported argument

  on dns-forwarder-rules.tf line 146, in data "aws_route53_resolver_rules" "forwarders":
 146:   tags = {

An argument named "tags" is not expected here.
```

### Steps to Reproduce

1. `terraform apply`

### References

https://www.terraform.io/docs/providers/aws/d/route53_resolver_rules.html

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/8508
* https://github.com/terraform-providers/terraform-provider-aws/pull/9085

As I remember, one of the original use cases I had involved filtering on `tags` which must be why I had it in the documentation. Agreed that this would be useful.
