### ISSUE TITLE
AWS Managed Policy Was Detached to Existing IAM Groups / Roles during destroy

### ISSUE THREAD

**Issue by rodel-talampas** [hashicorp/terraform-provider-aws#12019]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.20
+ provider.aws v2.48.0

### Affected Resource(s)

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

variable "admin_access_arn" {
  type = string
  default = "arn:aws:iam::aws:policy/AdministratorAccess"
}

variable "name" {
  default = "otp"
}

variable "iam_account" {
  default = "xxxxxxxxxx"
}

resource "aws_iam_role" "admin_access_role" {
  name = "${var.name}-administrator-access-role"
  assume_role_policy = <<DOC
{
  "Version": "2012-10-17",
  "Statement": [{
    "Effect": "Allow",
    "Principal": {
      "AWS": "arn:aws:iam::${var.iam_account}:root"
    },
    "Action": ["sts:AssumeRole"]
  }]
}
DOC
}

resource "aws_iam_policy_attachment" "admin_access_policy_attachment" {
  name       = "${var.name}-admin-access-policy-attachment"
  roles      = [aws_iam_role.admin_access_role.name]
  policy_arn = var.admin_access_arn
}

```

### Debug Output

https://gist.github.com/rodel-talampas/14f73f8f2f7e78e26fa7a70f545412c4

### Expected Behavior

During the destroy phase of the terraform scripts, destroy **admin_access_policy_attachment**. Do not detached **var.admin_access_arn** to existing IAM Group/Roles.

### Actual Behavior
During the destroy phase of the terraform scripts, instead of **JUST** destroying **admin_access_policy_attachment** , what it did was it destroyed **admin_access_policy_attachment** . and **DETACHED** **var.admin_access_arn** to ALL Existing IAM Group / Roles where it is attached

Sample Cloudtrail:

2020-02-13, 02:18:25 PM | rodel.talampas | DetachRolePolicy | IAM Policy and 1 more | arn:aws:iam::aws:policy/AdministratorAccess and 1 more
-- | -- | -- | -- | --

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### References

* #0000

**Comment by stynoo** [comment]
Hello @justinretzolk, I can confirm this issue still exists within the newer provider versions: 
```
Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.0.0
```
There is no mention of the detach in the terraform plans but you'll end up with detached policies in roles that shouldn't be touched.

**Comment by stynoo** [comment]
Nevermind, read the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy_attachment), especially the warning section.  I guess this can be closed.
