### ISSUE TITLE
Allow 'default' aws_redshift_subnet_group

### ISSUE THREAD

**Issue by mtekel** [hashicorp/terraform-provider-aws#12021]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I would like to manage default aws_redshift_subnet_group with terraform. I was able to import existing 'default' subnet group into TF fine. But for some reason, I am not allowed to use 'default' as a name, so TF now wants to destroy it and create new one, because of changed name...

Remove 'default' name restriction. Import worked fine.

* aws_redshift_subnet_group

### Potential Terraform Configuration

```hcl
resource "aws_redshift_subnet_group" "default" {
  name = "default"
  description = "default"

  subnet_ids = [
    aws_subnet.subnet-1.id,
    aws_subnet.subnet-2.id,
    aws_subnet.subnet-3.id
  ]

  tags = {}

}
```

### References

Looks like this code needs changing:

https://github.com/terraform-providers/terraform-provider-aws/blob/0c53f3bc63fd5979d2fe22d1fc6bd4cc7e9bf694/aws/resource_aws_redshift_subnet_group.go#L198-L201

I am willing to work on PR...

**Comment by mtekel** [comment]
Test adjustments here:
https://github.com/terraform-providers/terraform-provider-aws/blob/86b15faa3849c05935ed877351b16e8e99edb1c9/aws/resource_aws_redshift_subnet_group_test.go#L166-L169

**Comment by ewbankkit** [comment]
I think this one is similar:
* https://github.com/terraform-providers/terraform-provider-aws/issues/4674

**Comment by mtekel** [comment]
Thanks for the link. The thread container workaround that works for me as well:
```
lifecycle {
  ignore_changes = ["name"]
}
```

However I hope this will be eventually fixed, so that I can remove the workarounds and manage things in a standard way.
