### ISSUE TITLE
terraform data source filter wildcard for aws_ecr_repository

### ISSUE THREAD

**Issue by karandaid** [hashicorp/terraform-provider-aws#12039]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

Latest Terraform version 0.12.20

* aws_ecr_repository

### What do I want
I request for feature with ECR to search for the ECR Repositories using wildcards.

### Use Case
If you have multiple repos using a similar name, then you can retrieve the list of repos easily. 

#### Current HCL
```hcl
data "aws_ecr_repository" "service" {
  name = "ecr-repository"
}
```

#### Requesting Feature HCL
```hcl
data "aws_ecr_repository" "service" {
  name = "*ecr-repository"
}
```

### References

* https://www.terraform.io/docs/providers/aws/d/ecr_repository.html

**Comment by karolinepauls** [comment]
Workaround using filter expression to encode JSON as a string and store that as a singular JSON object value:

```
data "external" "ecr_repositories" {
  program = [
    "aws", "ecr", "describe-repositories", "--query",
    "{\"as_string\": to_string([repositories[*].repositoryName])}",
  ]
}

locals {
  ecr_repositories = jsondecode(data.external.ecr_repositories.result.as_string)
}
```
