### ISSUE TITLE
Unable to create an API Gateway Authorizer with no identity sources

### ISSUE THREAD

**Issue by djcrabhat** [hashicorp/terraform-provider-aws#12069]
### Terraform Version
0.12.20.  (but this bug has existed for as long back as I know)

### Affected Resource(s)
* aws_api_gateway_authorizer

### Terraform Configuration Files

```hcl
resource "aws_api_gateway_authorizer" "platform_authorizer" {
  name                             = "${var.environment}-my-authorizer"
  rest_api_id                      = aws_api_gateway_rest_api.test_api.id
  authorizer_uri                   = aws_lambda_function.authorizer.invoke_arn
  authorizer_credentials           = aws_iam_role.invocation_role.arn
  type                             = "REQUEST"
  authorizer_result_ttl_in_seconds = "0"

}
```

### Debug Output
N/A (terraform completes, but sets the identity_sources as `method.request.header.Authorization` by default)

### Expected Behavior
Should be able to create an authorizer without no authorization sources by omitting "identitySource" param and setting "authorizerResultTtlInSeconds" to 0 . (https://docs.aws.amazon.com/apigateway/api-reference/resource/authorizer/)

### Actual Behavior

Because https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_api_gateway_authorizer.go#L46 sets the default to "method.request.header.Authorization", and the API doesn't accept the empty string: so it's impossible to not provide the identity sources param in the API call and thus not have any identity sources.  (Our use case: API Gateway does an AND check for all authorizer identity sources and rejects it out of hand if not all sources are there..  If you need to potentially look for authorization sources in multiple places, say in a cookie _or_ auth header, you need to not use auth caching/identity sources at all).  

Now funny enough, the PATCH update of the authorizer resource _does_ accept the empty string.  So you can create the aws_api_gateway_authorizer resource, and _then_ change the identity source value to "", apply again and it'll reach the desired endstate.  But we'd like to be able to just set this first time on authorizer create.

I think the solution is as easy as removing the Default value from https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_api_gateway_authorizer.go#L46 , but I understand that'll break a bunch of people who already rely on this default behavior to be set as the Auth header.  So maybe some magic value that will indicate "don't send this param in the payload".

### Steps to Reproduce

Create a simple API Gateway with an authorizer.

1. `terraform apply`

### Important Factoids
NA

### References
NA

**Comment by antoiner77** [comment]
Any update here ?

**Comment by djcrabhat** [comment]
I'm thinking they'll be more responsive if I open up a PR, hopefully I'll get some time in the coming weeks to do it.

**Comment by antoiner77** [comment]
Probably 👍

**Comment by anGie44** [comment]
> setting "authorizerResultTtlInSeconds" to 0 .

Related #12633

**Comment by bsmedberg-xometry** [comment]
I believe that I have found a workaround for this issue: you can set

```terraform
authorizer_result_ttl_in_seconds = 0
identity_source = "method.request.header.Host"
```

Since the Host header will always exist, this is equivalent to making the key empty.
