### ISSUE TITLE
Feature Request: CodeDeploy linear and canary deployments for Amazon ECS

### ISSUE THREAD

**Issue by Yamitama** [hashicorp/terraform-provider-aws#12071]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

CodeDeploy are now supporting linear and canary deployments also for ECS,
but what we have now is linear and canary deployments only for lambda.
https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_codedeploy_deployment_config_test.go#L141

Therefore, people who are using ECS in the production environment will be very happy to have this feature in Terraform.

### New or Affected Resource(s)

* aws_codedeploy_deployment_config

### Potential Terraform Configuration

```hcl
resource "aws_codedeploy_deployment_config" "foo" {
  deployment_config_name = "test-deployment-config"
  compute_platform       = "ECS"

  traffic_routing_config {
    type = "TimeBasedCanary"

    time_based_linear {
      interval   = 10
      percentage = 10
    }
  }
}

resource "aws_codedeploy_deployment_group" "foo" {
  app_name               = "${aws_codedeploy_app.foo_app.name}"
  deployment_group_name  = "bar"
  service_role_arn       = "${aws_iam_role.foo_role.arn}"
  deployment_config_name = "${aws_codedeploy_deployment_config.foo.id}"

  auto_rollback_configuration {
    enabled = true
    events  = ["DEPLOYMENT_STOP_ON_ALARM"]
  }

  alarm_configuration {
    alarms  = ["my-alarm-name"]
    enabled = true
  }
}
```

### References

* https://aws.amazon.com/blogs/containers/aws-codedeploy-now-supports-linear-and-canary-deployments-for-amazon-ecs/

**Comment by nitrocode** [comment]
Can't you set the `compute_platform = "ECS"` with `TimeBasedCanary` now?

**Comment by breathingdust** [comment]
Hi @Yamitama! 👋  This does already look supported:

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codedeploy_deployment_config#argument-reference

Will close this issue, but please comment to reopen if I have done so in error.
