### ISSUE TITLE
Provider enforcing only lowercase alphanumeric characters and hyphens allowed in parameter group "name" makes importing impossible

### ISSUE THREAD

**Issue by iMartyn** [hashicorp/terraform-provider-aws#12144]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.21 (same with 0.12.20)
+ provider.aws v2.50.0

### Affected Resource(s)

* aws_db_parameter_group

### Terraform Configuration Files

```hcl
resource "aws_db_parameter_group" "default-postgres9-6" {
    name        = "default.postgres9.6"
    family      = "postgres9.6"
    description = "Default parameter group for postgres9.6"
... rest is not relevant ...
}
```

### Debug Output
Partial output https://gist.github.com/iMartyn/09aea39aff770335ce533ca3373a27c0#file-terraform-debug-txt - too much useful information to others in the full output to make that public.

### Panic Output
No panic, just errors

### Expected Behavior

Given that this resource exists on aws, I should be able to import it into terraform.

### Actual Behavior

Cannot execute plan
```
Error: only lowercase alphanumeric characters and hyphens allowed in parameter group "name"

  on dbpg.tf line 1874, in resource "aws_db_parameter_group" "default-postgres9-6":
1874: resource "aws_db_parameter_group" "default-postgres9-6" {
```

### Steps to Reproduce

1. create pg database point and click and then use something like terraforming to create terraform to import resources into.  or just create a db parameter group name with something like the hcl above.
2. `terraform plan`

### Important Factoids

The DB was pre-existing, I'm trying to import everything into terraform that has been created by point-and-click.

### References

I'm not the only one facing this problem : 
https://stackoverflow.com/questions/57386371/terraform-rds-instance-errors-with-lowercase-alphanumeric-characters-and-hypens

**Comment by ewbankkit** [comment]
Similar:
* https://github.com/terraform-providers/terraform-provider-aws/issues/12021
* #4674

@iMartyn Please try using the [`ignore_changes`](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) attribute:

```hcl
lifecycle {
  ignore_changes = ["name"]
}
```

**Comment by anthonsimonov** [comment]
Hi @ewbankkit, I have the same bug with importing aws_db_option_group. The `ignore_changes` attribute didn't help.

**Comment by spencer1248** [comment]
When attempting to modify a default RDS DB parameter group in the AWS management console I get:

> Error saving: Cannot modify a default parameter group. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: dc027191-3090-4cb2-8aff-4a567662ac7e), Cannot modify a default parameter group. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: eb45e3c5-c017-49a3-bc2a-e6012d1145a2)

So, for my purposes, there's no point in managing the DB parameter group state since it seems to be immutable. For the purpose of assigning the parameter group to a DB, perhaps it's also irrelevant since it gets assigned in the absence of an explicit DB parameter group? A little bit of explicitness is sacrificed but nothing that leaving a comment stating that the default DB parameter group is intentionally being used wouldn't address. For me the biggest downside has been that it was confusing to run into, so maybe something in the docs then?

**Comment by d4nyll** [comment]
Similar situation for option groups - trying to import an option group named `default:postgres-10`. Fails with the same error.

**Comment by erezinchy** [comment]
Facing same issue . Any update on this?

**Comment by rohammosalli** [comment]
You can use this func to fix your problem 

yourvar = `coalesce("default", "postgres-12")`

**Comment by voroniys** [comment]
With big noise Hashicorp announced a release of Terraform 1.0. And it was released with the errors that were reported a year ago and to fix which just tiny change in one line code with regexp needed.
So, more than year later, with version 1.0 still suffering from the same bug :(

**Comment by dimisjim** [comment]
@voroniys This is an issue in the provider, not core terraform

**Comment by VladoPortos** [comment]
Issue still exists:

```
│ Error: only lowercase alphanumeric characters and hyphens allowed in parameter group "name"
│
│   with aws_db_parameter_group.spot-rds-postgres-parmeters,
│   on RDS.tf line 42, in resource "aws_db_parameter_group" "spot-rds-postgres-parmeters":
│   42:     name   = "default.postgres13"
│
```
This is imported resource and the value is: default.postgres13 in aws

**Comment by aminsafarini** [comment]
I am encountering the same issue with a parameter group that is attached to a Redshift cluster. I am using the default in aws which is `default.redshift-1.0`. I tired using the latest provider version 4.50.0 (released 4 days ago at the time of this writing) and the issue remains... Any suggestions?

**Comment by autotune** [comment]
I am working on this now. It is a little bit mind boggling that no one has decided to take this on yet, the fix is simple and this is clearly a high priority.
