### ISSUE TITLE
Support for CodeBuild Triggers

### ISSUE THREAD

**Issue by pgieser** [hashicorp/terraform-provider-aws#12188]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for managing CodeBuild triggers.

### New or Affected Resource(s)

CodeBuild triggers.

* aws_codebuild_trigger

### Potential Terraform Configuration

```hcl
resource "aws_codebuild_trigger" "trigger" {
  project_name = ""

  name = ""
  description = ""

  frequency {
    type = "Hourly|Daily|Weekly|Custom"
    start_minute = "" // (Hourly|Daily|Weekly)
    start_hour = "" // (Daily|Weekly)
    start_day = "" // (Weekly)
    cron = "" // (Custom)
  }

  enabled = false

  advanced {
    source_version = ""
    hours = ""
    minutes = ""
  }
}

```

### References

* https://docs.aws.amazon.com/codebuild/latest/userguide/trigger-create.html
* https://docs.aws.amazon.com/codebuild/latest/userguide/triggers-edit.html

**Comment by jdyke** [comment]
I ran into this and got it working by using a `aws_cloudwatch_event_rule` and a `aws_cloudwatch_event_target ` pointing to the codebuild ARN. CodeBuild triggers are event rules behind the scenes.

**Comment by breathingdust** [comment]
I believe this can be closed, as CodeBuild triggers are configured via EventBridge. From AWS docs:

>  CodeBuild uses Amazon EventBridge rules for build triggers. You can use the EventBridge API to programmatically edit the build triggers for your CodeBuild projects. See Amazon EventBridge API Reference for more information.
