### ISSUE TITLE
aws_lb_listener race condition

### ISSUE THREAD

**Issue by jmgreg31** [hashicorp/terraform-provider-aws#12198]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We would like to build a listener on the same port depending on whether a user enables host headers.  Apply, Plan, and Destroy all work individually.  However, if you toggle the `var.host_header_enabled` and apply again, Terraform errors with notification that a listener can not be built on the same port.  The resource does in fact get destroyed as simply running the apply again builds the new listener with no issues.  It appears that even though the original listener does get destroyed, it does not update the state of the deployment to signify there is no longer a listener on that port.

### Versions

```
Terraform = 12.20
AWS provider = 2.49
```

### Example configuration
```hcl
resource "aws_lb_listener" "my-alb-listener" {
  count             = var.host_header_enabled ? 1 : 0
  load_balancer_arn = aws_lb.my-alb.arn
  port              = "443"
  protocol          = "HTTPS"
  ssl_policy        = "ELBSecurityPolicy-TLS-1-2-2017-01"
  certificate_arn   = var.alb_cert

  default_action {
    type = "fixed-response"

    fixed_response {
      content_type = "text/plain"
      message_body = "401 Unauthorized"
      status_code  = "401"
    }
  }
}

resource "aws_lb_listener" "my-alb-listener-noheader" {
  count             = var.host_header_enabled ? 0 : 1
  load_balancer_arn = aws_lb.my-bogie-alb.arn
  port              = "443"
  protocol          = "HTTPS"
  ssl_policy        = "ELBSecurityPolicy-TLS-1-2-2017-01"
  certificate_arn   = var.alb_cert

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.my-albtg.arn
  }
```

**Comment by myrahaubrich** [comment]
+1
