### ISSUE TITLE
aws_dlm_lifecycle_policy - Implement support for "Cross Region copy"

### ISSUE THREAD

**Issue by init418** [hashicorp/terraform-provider-aws#12204]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon Data Lifecycle Manager support "Cross region copy" since December 2019.

The feature is currently not supported by the Terraform AWS Provider.

### New or Affected Resource(s)

* aws/resource_aws_dlm_lifecycle_policy.go

### Potential Terraform Configuration

```hcl
cross_region_copy_rule [
  target_region = "string"
  encrypted = true|false
  cmk_arn = "string"
  copy_tags = true|false
  retain_rule = {
    interval = "integer"
    interval_unit = "DAYS"|"WEEKS"|"MONTHS"|"YEARS"
  }
]
```

### References

* https://aws.amazon.com/about-aws/whats-new/2019/12/amazon-data-lifecycle-manager-enables-automation-snapshot-copy-via-policies/

**Comment by rmalchow** [comment]
yeah. this would be very useful to have this supported directly from the provider!

**Comment by rsommer26270** [comment]
this would actually be a valuable improvement

**Comment by Youness1500** [comment]
is a good thing

**Comment by mcon-ivan** [comment]
This will really nice and helpful  :D

**Comment by DrewTittle** [comment]
Adding this to the provider would be a great enhancement

**Comment by dyn0m1ght** [comment]
Is this still not supported?  It's a simple checkbox in the console to do this? 

This would be pretty beneficial to add to the current feature set.

**Comment by Lynggaard91** [comment]
Yes please!

**Comment by raghureddycloud** [comment]
looking forward for this option.

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters roadmap. If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!
