### ISSUE TITLE
aws_ssm_parameter resource does not detect version changes due to changes in value

### ISSUE THREAD

**Issue by isobit** [hashicorp/terraform-provider-aws#12213]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.21
+ provider.aws v2.30.0
```

### Affected Resource(s)

* aws_ssm_parameter

### Terraform Configuration Files

```hcl
resource "aws_ssm_parameter" "my_config" {
	name  = "/my-config"
	type  = "String"
	value = var.config_data
}

resource "aws_lambda_function" "my_function" {
        # * snip *
	environment {
		variables = {
			SSM_PARAM= "${aws_ssm_parameter.my_config.name}:${aws_ssm_parameter.my_config.version}"
		}
	}
}

```

### Expected Behavior

Terraform detects that a changed value will force a new version number and waits until application to evaluate it.

```
  # aws_ssm_parameter.my_config will be updated in-place
  ~ resource "aws_ssm_parameter" "my_config" {
        id      = "/my-config"
        name    = "/my-config"
        type    = "String"
      ~ value   = (sensitive value)
      ~ version = (known after apply)
    }
```

### Actual Behavior

Value is updated-in-place but the version number is not detected and so the lambda function does not receive an update to its env var.

```
  # aws_ssm_parameter.my_config will be updated in-place
  ~ resource "aws_ssm_parameter" "my_config" {
        id      = "/my-config"
        name    = "/my-config"
        type    = "String"
      ~ value   = (sensitive value)
        version = 2
    }
```

### Important Factoids

S3 objects have similar behavior (data change forces version change) and the `aws_s3_bucket_object` resource _does_ handle this correctly by checking the `etag` in a custom diffing method:
https://github.com/terraform-providers/terraform-provider-aws/blob/af67efe96b4797b69c0cbcaa5678f2bfc8c1f258/aws/resource_aws_s3_bucket_object.go#L527-L533

I was thinking a similar custom diff method could be added to SSM parameters. It would have to compare the parameter value entirely rather than just a hash like the etag, however.

**Comment by argggh** [comment]
This still seems to be an issue with version 3.12.0 of the AWS provider (Terraform version 0.13.5); this example also needs two terraform runs to apply fully:
```
variable "input" {}

resource "aws_ssm_parameter" "dependee" {
  name  = "/test/some-parameter"
  type  = "String"
  value = var.input
}

resource "random_pet" "dependant" {
  keepers = {
    ref = "{{resolve:ssm:${aws_ssm_parameter.dependee.name}:${aws_ssm_parameter.dependee.version}}}"
  }
}

output "generation" {
  value = random_pet.dependant.id
}
```
to wit:
```
$ terraform apply -var input="First string" -auto-approve
aws_ssm_parameter.dependee: Creating...
aws_ssm_parameter.dependee: Creation complete after 1s [id=/test/some-parameter]
random_pet.dependant: Creating...
random_pet.dependant: Creation complete after 0s [id=stunning-newt]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

generation = stunning-newt
$ terraform apply -var input="Second string" -auto-approve
aws_ssm_parameter.dependee: Refreshing state... [id=/test/some-parameter]
random_pet.dependant: Refreshing state... [id=stunning-newt]
aws_ssm_parameter.dependee: Modifying... [id=/test/some-parameter]
aws_ssm_parameter.dependee: Modifications complete after 1s [id=/test/some-parameter]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

generation = stunning-newt
$ terraform apply -var input="Second string" -auto-approve
aws_ssm_parameter.dependee: Refreshing state... [id=/test/some-parameter]
random_pet.dependant: Refreshing state... [id=stunning-newt]
random_pet.dependant: Destroying... [id=stunning-newt]
random_pet.dependant: Destruction complete after 0s
random_pet.dependant: Creating...
random_pet.dependant: Creation complete after 0s [id=firm-impala]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.

Outputs:

generation = firm-impala
```

**Comment by loreleimccollum-work** [comment]
We are hitting this as well, and looking at a workaround of passing a tag of the modified Date and then using the tag output as a trigger for our other dependent code
