### ISSUE TITLE
Support email sns_topic_subscription

### ISSUE THREAD

**Issue by mtekel** [hashicorp/terraform-provider-aws#12286]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please support email protocol for sns_topic_subscription. I understand that creation is not possible (as per note in docs, see below in references). But existing topics can be imported (that works already). The use case is - for TF destroy and for monitoring changes (with terraform plan - vs any modifications done outside of TF) and applying changes that don't need resource re-creation. If the subscription is in non-confirmed state, then import should fail, preventing inability of TF to destroy or modify unconfirmed resource.

I understand that this is limited functionality, but still very valuable.

### New or Affected Resource(s)

sns_topic_subscription

### Potential Terraform Configuration

```hcl
resource "aws_sns_topic_subscription" "abc" {
  endpoint             = "abc@def.com"
  protocol             = "email"
  raw_message_delivery = "false"
  topic_arn            = aws_sns_topic.abc.id
}.
```

### References

https://github.com/terraform-providers/terraform-provider-aws/issues/7782

Docs: https://www.terraform.io/docs/providers/aws/r/sns_topic_subscription.html
> Unsupported protocols include the following:
>
> email -- delivery of message via SMTP
> email-json -- delivery of JSON-encoded message via SMTP
> These are unsupported because the endpoint needs to be authorized and does not generate an ARN until the target email address has been validated. This breaks the Terraform model and as a result are not currently supported.

**Comment by marcelboettcher** [comment]
I think this should be possible now as the [sns api](https://docs.aws.amazon.com/cli/latest/reference/sns/subscribe.html) has a new attribute:
--return-subscription-arn 

> Sets whether the response from the Subscribe request includes the subscription ARN, even if the subscription is not yet confirmed.

As AWS now returns an ARN, I guess this feature should be possible and easy to implement.

**Comment by mtekel** [comment]
So with http protocol/endpoints, TF does not support ones that don't have auto confirmation. Nevertheless, if you have one already created, TF imports it fine. This is because http(s) endpoints are not explicitly blacklisted like the email protocol. So the only change needed to support this functionality seems to be to remove that blacklist.

**Comment by gblues** [comment]
Seems to me like leveraging the `return-subscription-arn` flag would probably eliminate the auto-confirm requirement for http/s endpoints too.
