### ISSUE TITLE
Find LB Target Group by Tags

### ISSUE THREAD

**Issue by bliles** [hashicorp/terraform-provider-aws#12293]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to be able to find a aws_lb_target_group with the data provider by tags. Currently I can only lookup the data provider using arn or name. Attempting to use tags does not produce an error, but the tags do not filter the results so terraform complains because all of the target groups in my account/region are returned. Modification of load balancer listener rules using the beanstalk interface is extremely painful. I would prefer to get the target group for the beanstalk environment after creation using the data provider and then customize listener rules.

### New or Affected Resource(s)

* aws_lb_target_group

### Potential Terraform Configuration

```hcl
data "aws_lb_target_group" "backend" {
  tags = {
    "elasticbeanstalk:environment-id" = aws_elastic_beanstalk_environment.env.id
    Name = local.beanstalk_environment_name
  }
}
```

**Comment by pschulten** [comment]
@bliles I'd like to have that too, but I think amazon doesn't provide an API call for that yet (in their web console it's possible).

**Comment by ruciu** [comment]
I created issue https://github.com/aws/elastic-beanstalk-roadmap/issues/135 in elastic-beanstalk-roadmap repository about this. You can add :+1: so that AWS pushes it in a timely manner.

**Comment by pfilbin90** [comment]
Any status on this issue?  I upvoted and running into the same problem.

**Comment by zjomzjom** [comment]
Same problem here, still waiting for the fix.

**Comment by er1c** [comment]
👍🏻 please 

Tangentially related to: https://github.com/terraform-aws-modules/terraform-aws-alb/issues/238

**Comment by Ratomir** [comment]
+1

**Comment by youg9203** [comment]
+1

**Comment by ThisIsQasim** [comment]
As mentioned over at https://github.com/aws/elastic-beanstalk-roadmap/issues/135#issuecomment-911380735 we can use the `aws_resourcegroupstaggingapi_resources` data source for now.

```
data "aws_resourcegroupstaggingapi_resources" "test" {
  tag_filter {
    key    = "ingress.k8s.aws/stack"
    values = ["prod"]
  }
  resource_type_filters = ["elasticloadbalancing:targetgroup"]
}
```

**Comment by amit-cactus** [comment]
data "aws_lb_target_group" "tg" {
  name = "target-group-name"
}

Its working in my case
