### ISSUE TITLE
`load_balancing_algorithm_type` behaves incorrectly when added/removed.

### ISSUE THREAD

**Issue by lizthegrey** [hashicorp/terraform-provider-aws#12297]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

`Terraform/0.12.23 TFC/402a0ad321`

### Provider Version

[v2.52.0](https://github.com/terraform-providers/terraform-provider-aws/tree/v2.52.0)

### Affected Resource(s)

* aws_alb_target_group

### Terraform Configuration Files

First, create:
```hcl
resource "aws_alb_target_group" "shepherd_alb_tg" {
  name                          = "shepherd-${var.env}-alb-tg"
  target_type                   = "instance"
  load_balancing_algorithm_type = "least_outstanding_requests"
  port                          = 8080
  protocol                      = "HTTP"
  vpc_id                        = var.vpc_id
}
```
Then roll back to (notice the removed `load_balancing_algorithm_type` field):
```hcl
resource "aws_alb_target_group" "shepherd_alb_tg" {
  name        = "shepherd-${var.env}-alb-tg"
  target_type = "instance"
  port        = 8080
  protocol    = "HTTP"
  vpc_id      = var.vpc_id
}
```

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

```
  # module.kibble_asgs.aws_alb_target_group.shepherd_alb_tg will be updated in-place
  ~ resource "aws_alb_target_group" "shepherd_alb_tg" {
        arn                                = "arn:aws:elasticloadbalancing:us-east-1:702835727665:targetgroup/shepherd-kibble-alb-tg/63d1693fa2fca1b2"
        arn_suffix                         = "targetgroup/shepherd-kibble-alb-tg/63d1693fa2fca1b2"
        deregistration_delay               = 300
        id                                 = "arn:aws:elasticloadbalancing:us-east-1:702835727665:targetgroup/shepherd-kibble-alb-tg/63d1693fa2fca1b2"
        lambda_multi_value_headers_enabled = false
      ~ load_balancing_algorithm_type      = "least_outstanding_requests" -> "round_robin"
        name                               = "shepherd-kibble-alb-tg"
        port                               = 8080
        protocol                           = "HTTP"
        proxy_protocol_v2                  = false
        slow_start                         = 0
        tags                               = {}
        target_type                        = "instance"
        vpc_id                             = "vpc-f1ea198a"
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Actual Behavior

```
No changes. Infrastructure is up-to-date.
```

### Steps to Reproduce

1. `terraform apply` to create an ALB target group with `load_balancing_algorithm_type` set to the non-default of `least_outstanding_requests`
2. `terraform apply` to remove the `load_balancing_algorithm_type` parameter

### Important Factoids

n/a

### References

* #11141 (introduced the new `load_balancing_algorithm_type` parameter but didn't correctly restore it to defaults if not present)
* #11019 
* #11039

**Comment by nijave** [comment]
Just ran into this. I suspect it's because that field should be using a default instead of being "computed"

```
                       "load_balancing_algorithm_type": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
				ValidateFunc: validation.StringInSlice([]string{
					"round_robin",
					"least_outstanding_requests",
				}, false),
			},
```

**Comment by justinretzolk** [comment]
Hey @lizthegrey 👋 Thank you for taking the time to file this! Given that there's been a number of AWS Provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?
