### ISSUE TITLE
Datasource aws_ecs_capacity_provider 

### ISSUE THREAD

**Issue by oonisim** [hashicorp/terraform-provider-aws#12301]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Please add aws_ecs_capacity_provider datasoruce.

Due to the current AWS ECS bug of not being able to delete Capacity Provide once created, re-running terraform apply can cause the error because terraform apply cannot delete it.
```
Error: error creating capacity provider: ClientException: The specified capacity provider already exists. To change the configuration of an existing capacity provider, update the capacity provider.
```
Would like to reference the capacity provide that has been created and exists to attach to a ECS clsuter.

### New or Affected Resource(s)

aws_ecs_capacity_provider datasource

### References

[[ECS] Add the ability to delete an ASG capacity provider. #632](https://github.com/aws/containers-roadmap/issues/632)

**Comment by ShitulGupta** [comment]
any update on this , it creates issues

**Comment by michal-kosinski** [comment]
Also needed to assign capacity_provider_strategy in the aws_ecs_service
