### ISSUE TITLE
Inconsistent argument naming between aws_waf_ipset and aws_wafregional_ipset

### ISSUE THREAD

**Issue by jarinom** [hashicorp/terraform-provider-aws#12360]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.23
+ provider.archive v1.3.0
+ provider.aws v2.52.0
+ provider.kubernetes v1.11.1
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
```

### Affected Resource(s)

* aws_waf_ipset
* aws_wafregional_ipset

### Terraform Configuration Files

```hcl
resource "aws_waf_ipset" "ipset" {
  name = "tfIPSet"

  ip_set_descriptors {
    type  = "IPV4"
    value = "192.0.7.0/24"
  }

  ip_set_descriptors {
    type  = "IPV4"
    value = "10.16.16.0/16"
  }
}

resource "aws_wafregional_ipset" "ipset" {
  name = "tfIPSet"

  ip_set_descriptor {
    type  = "IPV4"
    value = "192.0.7.0/24"
  }

  ip_set_descriptor {
    type  = "IPV4"
    value = "10.16.16.0/16"
  }
}
```

### Expected Behavior

One might expect that changing `aws_waf_ipset` to `aws_wafregional_ipset` would be just changing the resource type but there's a slight difference in argument names.

### Actual Behavior

`aws_waf_ipset` has argument `ip_set_descriptors` (plural) but  `aws_wafregional_ipset` has `ip_set_descriptor` (singular).

### References

* https://www.terraform.io/docs/providers/aws/r/waf_ipset.html
* https://www.terraform.io/docs/providers/aws/r/wafregional_ipset.html

**Comment by ljluestc** [comment]
You can switch from aws_waf_ipset to aws_wafregional_ipset. However, keep in mind that aws_wafregional_ipset uses the singular ip_set_descriptor argument instead of the plural ip_set_descriptors. Here's how you can update your configuration:
```
resource "aws_wafregional_ipset" "ipset" {
  name = "tfIPSet"

  ip_set_descriptor {
    type  = "IPV4"
    value = "192.0.7.0/24"
  }

  ip_set_descriptor {
    type  = "IPV4"
    value = "10.16.16.0/16"
  }
}
```
