### ISSUE TITLE
Support for import-snapshot - to create ami's from s3 objects

### ISSUE THREAD

**Issue by arnvid** [hashicorp/terraform-provider-aws#12399]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Some vendors provide VMDK files or similar that can be used to create an AMI. Through the process of import-snapshot and register-snapshot. And to be able to automate this, or run it all from Terraform Cloud/Enterprise it would be good if one could do the whole process in Terraform without the use of alot of local exec's.

### References
https://docs.aws.amazon.com/cli/latest/reference/ec2/import-image.html
Seems to be added in AWS SDK release v1.26.7 (2019-12-20)
service/ec2: Updates service API and documentation
This release introduces the ability to tag key pairs, placement groups, export tasks, import image tasks, import snapshot tasks and export image tasks. You can use tags to organize and identify your resources for cost allocation.

* #0000

**Comment by m4h3** [comment]
https://github.com/hashicorp/terraform-provider-aws/pull/16373

**Comment by arnvid** [comment]
@m4h3 - we ended up solving this with using a few lambda's and dynamodb to keep track of the process

**Comment by grahamc** [comment]
This has been implemented by #16373
