### ISSUE TITLE
New Data Source: WAF Subscribed rule group

### ISSUE THREAD

**Issue by haidaraM** [hashicorp/terraform-provider-aws#12407]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

New data sources to fetch the waf (and waf regional) subscribed rule groups. These rule groups can be subscribed in the market place. 

Two data sources may be required because the same rule doesn't have the same ID depending on when using it with a regional web acl or a global web acl. 
```bash
$ aws waf-regional list-subscribed-rule-groups
{
    "RuleGroups": [
        {
            "RuleGroupId": "490f6909-95a7-4890-8ef7-cd2d2bb75950",
            "Name": "Fortinet Managed Rules for AWS WAF - Complete OWASP Top 10",
            "MetricName": "FortinetCompleteOWASPTopTenRuleset"
        }
    ]
}

$ aws waf list-subscribed-rule-groups
{
    "RuleGroups": [
        {
            "RuleGroupId": "fecbf80a-be95-43f2-a891-972c722f32f6",
            "Name": "Fortinet Managed Rules for AWS WAF - Complete OWASP Top 10",
            "MetricName": "FortinetCompleteOWASPTopTenRuleset"
        }
    ]
}
```

### New or Affected Resource(s)

* aws_waf_subscribed_rule_group
* aws_wafregional_subscribed_rule_group

### Potential Terraform Configuration

```hcl
data "aws_waf_subscribed_rule_group" "example" {
  name = ""
}

data "aws_wafregional_subscribed_rule_group" "example" {
  name = ""
}
```

### References
* API Reference: https://docs.aws.amazon.com/waf/latest/APIReference/API_waf_ListSubscribedRuleGroups.html
* SDK Reference: https://docs.aws.amazon.com/sdk-for-go/api/service/waf/#WAF.ListSubscribedRuleGroups and https://docs.aws.amazon.com/sdk-for-go/api/service/wafregional/#WAFRegional.ListSubscribedRuleGroups

**Comment by DrFaust92** [comment]
addressed by #10563
