### ISSUE TITLE
Support the SERVICE_MANAGED permission model for CloudFormation StackSets

### ISSUE THREAD

**Issue by srikanthchelluri** [hashicorp/terraform-provider-aws#12422]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, only the `SELF_MANAGED` permission model is supported by the `aws_cloudformation_stack_set` resource (it is the default). However, the `SERVICE_MANAGED` permission model is helpful when using StackSets to manage resources across an AWS Organization since it allows StackSet instances to target organizational units. But before changing the `aws_cloudformation_stack_set_instance` resource, the `aws_cloudformation_stack_set` resource needs to be updated to support the `SERVICE_MANAGED` permission model and configure `AutoDeployment` parameters.

### New or Affected Resource(s)

* `aws_cloudformation_stack_set`

### Potential Terraform Configuration

```hcl
resource "aws_cloudformation_stack_set" "accept_guardduty" {
  provider = aws.us-east-1

  name             = "AcceptGuardDuty"
  description      = "Creates an AWS::GuardDuty::Detector resource and optionally an AWS::GuardDuty::Master resource in a set of accounts and regions."
  permission_model = "SERVICE_MANAGED"
  template_body    = local.stack_set_accept_guardduty_template_body

  auto_deployment {
    enabled                          = true
    retain_stacks_on_account_removal = false
  }

  parameters = {
    MasterId = local.infosec_aws_account_id
  }
}
```

### References

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-orgs-enable-trusted-access.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/cloudformation/#CreateStackSetInput

**Comment by gespinoza22** [comment]
any word on when someone will get assigned to this?

**Comment by piersf** [comment]
@gespinoza22 CloudFormation released support for this last month if you happen to use also CloudFormation.

**Comment by chrisjaimon2012** [comment]
Any updates on this?

**Comment by rclark** [comment]
I found a workaround that helps while there's not direct terraform support: Use terraform to create a **cloudformation stack** in the organization's management account [terraform docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudformation_stack). This stack defines an `AWS::CloudFormation::StackSet` with `SERVICE_MANAGED` permissions model [cloudformation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-stackset.html).

This launches the stack set indirectly via `terraform apply`, using only credentials in the management account, without the need for concerns over how https://github.com/hashicorp/terraform-provider-aws/pull/12423 would need additional modification of the [aws_cloudformation_stack_set_instance terraform resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudformation_stack_set_instance).
