### ISSUE TITLE
Feature request: Allow aws_instance resource to create and manage spot instances

### ISSUE THREAD

**Issue by tomelliff** [hashicorp/terraform-provider-aws#1243]
I haven't taken a particularly long look at the code to see how much impact this would have but it would be nice if the `aws_instance` resource could be used to manage spot instances instead of having to explicitly use the `aws_spot_instance_request` resource.

This would simplify being able to switch between spot and on demand requests without duplicating code. As it is I have a module that creates EC2 instances and then a bunch of other dependent resources (Route53 records, Cloudwatch alarms etc) and I'm going to have to duplicate the `aws_instance` resource plus all the resources dependent on it to use the `aws_spot_instance_request` and also make them conditional on whether a spot price has been set.

So as a minimal example I'll have something like:

```hcl
variable "instance_count" {
  default = 1
}

variable "spot_price" {
  default = ""
}

data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}

resource "aws_instance" "instance" {
  count         = "${var.spot_price == "" ? var.instance_count : 0}"
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"

  tags {
    Name = "${var.name}${var.instance_count > 1 ? format("-%v", count.index+1) : ""}.${var.domain}"
  }
}

resource "aws_spot_instance_request" "instance" {
  count         = "${var.spot_price != "" ? var.instance_count : 0}"
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"
  spot_price    = "${var.spot_price}"

  tags {
    Name = "${var.name}${var.instance_count > 1 ? format("-%v", count.index+1) : ""}.${var.domain}"
  }
}

data "aws_vpc" "vpc" {
  tags {
    Name = "myvpc"
  }
}

data "aws_route53_zone" "zone" {
  name   = "example.com"
  vpc_id = "${data.aws_vpc.selected.id}"
}

resource "aws_route53_record" "on_demand_record" {
  count   = "${var.spot_price == "" ? var.instance_count : 0}"
  zone_id = "${data.aws_route53_zone.zone.zone_id}"
  name    = "${var.name}${var.instance_count > 1 ? format("-%v", count.index+1) : ""}.example.com"
  type    = "A"
  ttl     = "60"

  records = ["${element(aws_instance.instance.*.private_ip, count.index)}"]
}

resource "aws_route53_record" "spot_record" {
  count   = "${var.spot_price != "" ? var.instance_count : 0}"
  zone_id = "${data.aws_route53_zone.zone.zone_id}"
  name    = "${var.name}${var.instance_count > 1 ? format("-%v", count.index+1) : ""}.example.com"
  type    = "A"
  ttl     = "60"

  records = ["${element(aws_spot_instance_request.instance.*.private_ip, count.index)}"]
}
```
But with a lot more duplicated configuration between the `aws_instance` and `aws_spot_instance_request` and also anything else that needs the instance id, private IP address or other computed attributes.

Instead I'd love to just do:

```hcl
variable "instance_count" {
  default = 1
}

variable "spot_price" {
  default = ""
}

data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}

resource "aws_instance" "instance" {
  count         = "${var.instance_count}"
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"
  spot_price    = "${var.spot_price}"

  tags {
    Name = "${var.name}${var.instance_count > 1 ? format("-%v", count.index+1) : ""}.${var.domain}"
  }
}

data "aws_vpc" "vpc" {
  tags {
    Name = "myvpc"
  }
}

data "aws_route53_zone" "zone" {
  name   = "example.com"
  vpc_id = "${data.aws_vpc.selected.id}"
}

resource "aws_route53_record" "record" {
  count   = "${var.instance_count}"
  zone_id = "${data.aws_route53_zone.zone.zone_id}"
  name    = "${var.name}${var.instance_count > 1 ? format("-%v", count.index+1) : ""}.example.com"
  type    = "A"
  ttl     = "60"

  records = ["${element(aws_instance.instance.*.private_ip, count.index)}"]
}
```

Where the `aws_instance` resource takes an optional `spot_price` (plus other spot related config) and if it gets an empty string or isn't provided then it creates an on demand instance instead.

Would people be open to complicating the code in the `aws_instance` module to allow for this simpler interface? I'd guess it probably adds a fair bit more complexity to things in the code but I'm not sure if there's an specific steer away from that if it enables users (the vast majority of people) to more easily do something like this.

**Comment by tomelliff** [comment]
Sounds like this should be much easier with this announcement today: https://aws.amazon.com/blogs/aws/amazon-ec2-update-streamlined-access-to-spot-capacity-smooth-price-changes-instance-hibernation/

I'll take a look at the API and see if things can be simplified nicely.

**Comment by stefansundin** [comment]
I was just looking to see if I could implement this, but I'm glad I looked if someone else had started already. Thanks for making the effort.

I don't work for HashiCorp, but I think they would tell you to put this stuff in its own block, maybe called `instance_market_options` in order to emulate the API as closely as possible. Then you can get rid off `use_spot_market`. See how `credit_specification` is implemented.

So the end-user would use something like the following:

```hcl
resource "aws_instance" "web" {
  # ...

  instance_market_options {
    max_price = "0.1"
    spot_instance_type = "persistent"
    # ...
  }
}
```

Hopefully someone will stop by to help you get this merged. :)
