### ISSUE TITLE
Include ValidateFunc on AWS API for WorkSpaces

### ISSUE THREAD

**Issue by Ishiven** [hashicorp/terraform-provider-aws#12488]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In short - the issue causes the code to pass a validate and planning part, but fails to apply on... well, apply.

### New or Affected Resource(s)

aws_directory_service_directory

### Potential Terraform Configuration

`resource "aws_directory_service_directory" "main" {
  name     = var.aws_ds_name
  password = var.aws_ds_passwd
  size     = var.size
  type = "SimpleAD"
  vpc_settings {
    vpc_id     = module.networking.main_vpc
    subnet_ids = ["${module.networking.private-0}", "${module.networking.private-1}"]
  }
}`

`variable "aws_ds_name" {
  type = string
  default = ""
}
variable "aws_ds_passwd" {
  type = string
  default = ""
}
variable "aws_ws_ip_name" {
  type = string
  default = ""
}
`

### Expected Behavior

The Workspaces environment is created.

### Actual Behavior

No matter what data I input, I am stuck with that error:

`ValidationException: 2 validation errors detected: Value at 'password' failed to satisfy constraint: Member must satisfy regular expression pattern: (?=^.{8,64}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9\s])(?=.*[a-z])|(?=.*[^A-Za-z0-9\s])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9\s]))^.*; Value '' at 'name' failed to satisfy constraint: Member must satisfy regular expression pattern: ^([a-zA-Z0-9]+[\\.-])+([a-zA-Z0-9])+$
        status code: 400, request id: 2d9585d3-e663-4902-a511-5ccf49f126ad`

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
### Steps to reproduce

1. `terraform apply`

### References

* #0000

**Comment by gdavison** [comment]
Implementation note: The API documentation only specifies a validation regex when using a `SimpleAD` directory. The other forms may do validation on the server side, but API documentation only specifies a minimum length of one character for `ADConnector`. This will need to make use of the cross-attribute validation "hack" using a `CustomizeDiffFunc` on the resource.
