### ISSUE TITLE
Add Sagemaker TrainingJob Data resource

### ISSUE THREAD

**Issue by delwaterman** [hashicorp/terraform-provider-aws#12503]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am writing terraform to create and deploy a Sagemaker Model on Inference Engine. I receive the name of the training job and would like to pull the Model S3 location. I can do all this with scripts using `aws sagemaker describe-training-job` so it should be relatively simple to implement this data provider.

### New or Affected Resource(s)

data.sagemaer

* aws_data_sagemaker_training_job

### Potential Terraform Configuration

```hcl
data_aws_sagemaker_training_job {
  id = "my-training-job"
}
```

### References

* #0000

**Comment by DrFaust92** [comment]
Hey @delwaterman, i want to take a look at this. can you share a fuller example of how you would use it with other sagemaker resources?

**Comment by delwaterman** [comment]
Sorry for the late reply, I have been on leave. The training job has an s3 location for the output of the model (e.g. `s3://my-bucket/path/to/trained/model.dat`). I would use that data when creating AWS Model that will be used for making predictions

**Comment by desenhar** [comment]
is there any update on this?
