### ISSUE TITLE
Canonical ID of CloudFront log delivery account

### ISSUE THREAD

**Issue by limitusus** [hashicorp/terraform-provider-aws#12512]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For `acl` in `aws_s3_bucket`, I want a data source that provides CloudFront log delivery account's canonical ID.

With `acl` configuration block, we can configure bucket ACL instead of canned ACLs.
We need to write the magical canonical ID of CloudFront log delivery account [documented here](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html#AccessLogsBucketAndFileOwnership).

```hcl
  grant {
    type        = "CanonicalUser"
    permissions = ["FULL_CONTROL"]
    id          = "c4c1ede66af53448b93c283ce9448c4ba468c9432aa01d700d3878632f77d2d0"
  }
```

Now we have `aws_canonical_user_id` data resource, and I believe it's useful for having like this for CloudFront.
https://www.terraform.io/docs/providers/aws/d/canonical_user_id.html

### New or Affected Resource(s)

- `data.aws_cloudfront_canonical_user_id` maybe

### Potential Terraform Configuration

```hcl
data "aws_cloudfront_canonical_user_id" "current" {}

resource "aws_s3_bucket" "bucket" {
  bucket = "some-bucket"

  grant {
    type        = "CanonicalUser"
    permissions = ["FULL_CONTROL"]
    id          = data.aws_canonical_user_id.current.id
  }
  # CloudFront log delivery
  grant {
    type        = "CanonicalUser"
    permissions = ["FULL_CONTROL"]
    id          = data.aws_cloudfront_canonical_user_id.current.id
  }
  ...
}
```

### References

* N/A

**Comment by hgsgtk** [comment]
I thins it seems to be `aws_cloudfront_service_account` like `aws_elb_service_account`, `aws_redshift_service_account`, `aws_billing_service_account`.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/elb_service_account

**Comment by bryantbiggs** [comment]
bump, this would be great

**Comment by ewbankkit** [comment]
For China regions: https://docs.amazonaws.cn/en_us/aws/latest/userguide/cloudfront.html#feature-diff.

**Comment by hgsgtk** [comment]
oh...

> a52cb28745c0c06e84ec548334e44bfa7fc2a85c54af20cd59e4969344b7af56

**Comment by hgsgtk** [comment]
I tried to solve this issue by https://github.com/hashicorp/terraform-provider-aws/pull/15167 (not yet reviewed now).
