### ISSUE TITLE
import with different provider fails when using terraform cloud

### ISSUE THREAD

**Issue by mrinella-fs** [hashicorp/terraform-provider-aws#12515]
I am attempting to import a few existing aws resources into an existing state that are in a different region than the default provider in this terraform workspace.    The backend is terraform cloud, so the action is happening there.

For both of the attempts I have made, the result is:

Error: Cannot import non-existent remote object

The commands I am running:

terraform import -provider=aws.prod-us-east-2 aws_vpc.<name obscured> vpc-<id obscured>
terraform import -provider=aws.prod-us-east-2 aws_vpc_dhcp_options.<name obscured> dopt-<id obscured>

terraform version 0.12.23
aws provider version 2.54

I can assure you the places where I obscured the names and the ids were checked many times and I do have them correct.  The provider name is also correct for this codebase.  The default provider region is us-east-1.   I have built things in both regions in this codebase.  I'm just trying to bring in some existing items now.

Hopefully I'm doing something wrong and its easy.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @mrinella-fs 👋 Thank you for taking the time to file this issue. Given that there's been a number of Terraform and AWS provider releases since you initially filed it, can you confirm if you're still experiencing this behavior?
