### ISSUE TITLE
aws_volume_attachment on spot instance request fails due to "InvalidInstanceID.Malformed"

### ISSUE THREAD

**Issue by G-Rath** [hashicorp/terraform-provider-aws#12521]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
g-rath:env-minecraft$ terraform -v
Terraform v0.12.23
+ provider.aws v2.54.0
+ provider.template v2.1.2

Your version of Terraform is out of date! The latest version
is 0.12.24. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* aws_volume_attachment

### Terraform Configuration Files

```hcl
################################################################################
# Terraform Backend
################################################################################

terraform {
  required_version = ">= 0.12"

  backend "s3" {
    bucket = "tf-infrastructure-states"
    region = "ap-southeast-2"
    key    = "minecraft/env-minecraft.tfstate"
  }
}

################################################################################
# Variables
################################################################################

variable "AWS_ACCESS_KEY_ID" {
  type = string
}

variable "AWS_SECRET_ACCESS_KEY" {
  type = string
}

variable "AWS_REGION" {
  type    = string
  default = "ap-southeast-2" # Sydney
}

variable "DEPLOY_USER_PASSWORD" {
  type = string
}

variable "ec2_keypair_name" {
  type    = string
  default = "mc-server-host-key"
}

################################################################################
# Local Variables
################################################################################

locals {
  project_name = "minecraft-server"

  common_tags = {
    Project          = "Minecraft Server Host"
    Client           = "Ackama"
    Environment      = "Production"
    ProvisioningTool = "Terraform"
  }

  common_tags_in_asg_format = [
  for tag_name, tag_value in local.common_tags :
  {
    key                 = tag_name,
    value               = tag_value,
    propagate_at_launch = true
  }
  ]
}

################################################################################
# Providers
################################################################################

provider "aws" {
  version    = "~> 2.30"
  access_key = var.AWS_ACCESS_KEY_ID
  secret_key = var.AWS_SECRET_ACCESS_KEY
  region     = "ap-southeast-2"
}

################################################################################
# EBS Volumes
################################################################################

data "aws_availability_zones" "available" {
  state = "available"
}

resource "aws_ebs_volume" "mc_server_host_data" {
  availability_zone = data.aws_availability_zones.available.names[0]

  size = 5
  type = "gp2"

  lifecycle {
    prevent_destroy = false
  }

  tags = merge(
  local.common_tags,
  {
    DLM-SnapshotGroup = "mc-server-host-data",
    ExpectedMountPath = "/srv",
    Filesystem        = "ext4",
    Name              = "Minecraft Server Host Data"
  }
  )
}

resource "aws_volume_attachment" "mc_server_host_data" {
  device_name = "/dev/sdg"
  volume_id   = aws_ebs_volume.mc_server_host_data.id
  instance_id = aws_spot_instance_request.mc_server_host.id

  skip_destroy = false
}

################################################################################
# Spot Instance
################################################################################

data "aws_ami" "latest_ubuntu_lts" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}

resource "aws_spot_instance_request" "mc_server_host" {
  instance_type = "t3a.nano"
  ami           = data.aws_ami.latest_ubuntu_lts.id

  root_block_device {
    volume_size           = 8 # GB
    delete_on_termination = true
    volume_type           = "gp2"
  }
}
```

### Debug Output

[debug output](https://gist.github.com/G-Rath/c5e88743615ed699b0e55eea3b211c17).

### Expected Behavior

The instance is created without error, or otherwise a valid error message explaining the problem is shown.

### Actual Behavior

```
g-rath:env-minecraft$ tf apply -auto-approve
data.aws_availability_zones.available: Refreshing state...
data.aws_ami.latest_ubuntu_lts: Refreshing state...
aws_ebs_volume.mc_server_host_data: Creating...
aws_spot_instance_request.mc_server_host: Creating...
aws_spot_instance_request.mc_server_host: Creation complete after 1s [id=sir-pfq8hp9h]
aws_ebs_volume.mc_server_host_data: Still creating... [10s elapsed]
aws_ebs_volume.mc_server_host_data: Creation complete after 11s [id=vol-0b197ce857d1b98f5]
aws_volume_attachment.mc_server_host_data: Creating...
aws_volume_attachment.mc_server_host_data: Still creating... [10s elapsed]

Error: Error waiting for instance (sir-pfq8hp9h) to become ready: InvalidInstanceID.Malformed: Invalid id: "sir-pfq8hp9h"
        status code: 400, request id: 78a792d0-f30c-4665-87c1-13c078f9b42c

  on main.tf line 127, in resource "aws_volume_attachment" "mc_server_host_data":
 127: resource "aws_volume_attachment" "mc_server_host_data" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

None.

### References

* #0000

**Comment by bflad** [comment]
Hi @G-Rath 👋

According to the [`aws_spot_instance_request` resource documentation](https://www.terraform.io/docs/providers/aws/r/spot_instance_request.html#attributes-reference) it appears you should be using the `spot_instance_id` attribute instead of the `id` attribute. You will likely also want to include the `wait_for_fulfillment = true` argument, to ensure an instance is created, e.g.

```hcl
resource "aws_volume_attachment" "mc_server_host_data" {
  device_name = "/dev/sdg"
  volume_id   = aws_ebs_volume.mc_server_host_data.id
  instance_id = aws_spot_instance_request.mc_server_host.spot_instance_id

  skip_destroy = false
}

# ...

resource "aws_spot_instance_request" "mc_server_host" {
  ami                  = data.aws_ami.latest_ubuntu_lts.id
  instance_type        = "t3a.nano"
  wait_for_fulfillment = true

  root_block_device {
    volume_size           = 8 # GB
    delete_on_termination = true
    volume_type           = "gp2"
  }
}
```

That should contain the appropriate `i-...` identifier instead of `sir-...`.

**Comment by G-Rath** [comment]
haha yeah I made this late at night, and got it working using `spot_instance_id` shortly after posting.

I'm wondering if there is a way of making this nicer, but thinking about it I suspect the answer might be no just due to how Terraform works.

btw, thanks for the `wait_for_fulfillment` tip: completely missed that, and was running my TF twice for the attachment :joy:

**Comment by bflad** [comment]
The [EC2 API Reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AttachVolume.html) does not provide much guidance on acceptable values for that argument, however we could probably assume that EC2 Instance Identifiers as [described here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/resource-ids.html) could be validated by the attribute itself in Terraform.

The schema definition here: https://github.com/terraform-providers/terraform-provider-aws/blob/f3eb8159f9ec5e7fa14f8587dbfc4123b832f579/aws/resource_aws_volume_attachment.go#L31-L35

Can be updated with something like:

```go
"instance_id": {
	Type:         schema.TypeString,
	Required:     true,
	ForceNew:     true,
	ValidateFunc: validation.StringMatch(regexp.MustCompile(`^i-[a-z0-9]{8,17}$`), "must be an EC2 Instance identifier of i- followed by 8 or 17 lowercase alphanumeric characters"),
},
```

This error can occur only when the value is known though. If referencing a computed/unknown attribute (such as one not yet created), this would happen during the `apply` phase. You're more than welcome to contribute something like ☝️ though (and similar for the `volume_id`). 👍

**Comment by G-Rath** [comment]
I was thinking more about if it would be possible to catch the error and check it against this known situation.

i.e "if error is InvalidInstanceID.Malformed && resource is aws_spot_instance_request && attribute is id"

But your way works too, and is probably a lot more idiomatic 😄

**Comment by bflad** [comment]
@G-Rath your idea is fantastic as well! Its just not currently possible (yet 😉 ) in Terraform core and in the Terraform Plugin SDK.

Currently the resource schema and logic only receive evaluated expressions from the configuration (e.g. values like `i-12345678` or "unknown" for things yet computed). If we could enhance the core logic to save reference resource type (e.g. `aws_spot_instance_request`) and attribute (e.g. `id`) information when evaluating the configuration and pass that information back to the provider then that could unlock something we can return errors earlier. It'd be neat to have our schema logic able to declare something like:

```go
&schema.Schema{
  // ...
  ResourceReferenceValidation: []*schema.ResourceReferenceSuggestion{
    {
      ReferenceType: "aws_spot_instance_request",
      ReferenceAttribute: "id",
      SuggestedType: "aws_spot_instance_request",
      SuggestedAttribute: "spot_instance_id",
    },
  },
},
```

That the Terraform Plugin SDK automatically handled during the plan validation and returned an error like:

```
error TYPE.NAME argument ATTR contains invalid resource REFTYPE attribute REFATTR reference, did you mean resource SUGTYPE attribute SUGATTR?
```

In practice (hopefully output with the actual configuration):

```
error "aws_volume_attachment.mc_server_host_data" argument "instance_id" contains invalid resource "aws_spot_instance_request" attribute "id" reference, did you mean resource "aws_spot_instance_request" attribute "spot_instance_id"?
```

What do you think?

**Comment by G-Rath** [comment]
> What do you think?

I think that seems really powerful!

There's a number of places where that could come in handy:
  * passing `id` to fields that want `arn`
  * passing `name` instead of `arn` of an `aws_iam_role` to `mc_server_manager_lambda.role`
  * passing `arn` instead of `name` of an `aws_iam_role` to `aws_iam_role_policy_attachment.role`
  * passing `name` instead of `json` of an `aws_iam_policy_document` to `aws_iam_role.assume_role_policy`

and so on.
