### ISSUE TITLE
aws_iot_topic_rule modification fails with UnauthorizedException

### ISSUE THREAD

**Issue by jamescrowley** [hashicorp/terraform-provider-aws#12520]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24
+ provider.archive v1.3.0
+ provider.aws v2.54.0
+ provider.null v2.1.2

### Affected Resource(s)

* aws_iot_topic_rule

### Terraform Configuration Files

```hcl
resource "aws_iot_topic_rule" "forward" {
  name        = "${var.prefix}_forward_${var.name}"
  enabled     = true
  sql         = "SELECT * FROM 'v2/+/data/${var.name}'"
  sql_version = "2015-10-08"

  dynamic kinesis {
    for_each = var.realtime_lambda == "" ? [] : [var.realtime_lambda]
    content {
      partition_key = "$${topic()}"
      role_arn      = var.role_iot.arn
      stream_name   = aws_kinesis_stream.realtime_stream[0].name
    }
  }

  firehose {
    role_arn             = var.role_iot.arn
    delivery_stream_name = aws_kinesis_firehose_delivery_stream.to_s3_parquet.name
  }
}
```

### Debug Output

`2020-03-25T05:55:28.650Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: 2020/03/25 05:55:28 [DEBUG] [aws-sdk-go] DEBUG: Validate Response iot/GetTopicRule failed, attempt 0/25, error UnauthorizedException: Access to topic rule 'sandbox_v2_forward_state_data' was denied`

Available in terraform cloud: https://app.terraform.io/app/Relectrify/workspaces/Web-Infrastructure-sandbox_v2/runs/run-KTwRTs996B3LxVif

### Expected Behavior

* Shouldn't encounter UnauthorizedException errors

### Actual Behavior

* aws_iot_topic_rule modification fails with UnauthorizedException

### Steps to Reproduce

This was working fine, but our most recent change to the terraform config appears to have triggered this state, and it consistently fails running `terraform plan` 

Running in terraform cloud: https://app.terraform.io/app/Relectrify/workspaces/Web-Infrastructure-sandbox_v2/runs/run-KTwRTs996B3LxVif

### References

* Appears to be closely related to this issue which was fixed in January https://github.com/terraform-providers/terraform-provider-aws/issues/10365

**Comment by JoshM1994** [comment]
I encountered a similar issue on v2.47

I was having issues updating an error action - `terraform apply` would always see the change but the rule never got updated. Eventually, I removed the rule manually and ran `terraform rm [resource]` to remove it from the state.

Upon running a fresh `terraform apply`, the IoT rule was successfully created with the changes I needed

**Comment by tomscholz** [comment]
I can confirm that this bug is still occurring 👍

**Comment by richardj-bsquare** [comment]
Yep, still get this on occasions; only to fix is to remove topic rule state or topic rule.
```
Error: error getting IoT Topic Rule (iot_ingester): UnauthorizedException: Access to topic rule 'iot_ingester' was denied
```

**Comment by justinretzolk** [comment]
Hey y'all 👋 Looking at the error, the `UnauthorizedException` is coming from AWS. Looking at the AWS Go SDK reference for [GetTopicRule](https://docs.aws.amazon.com/sdk-for-go/api/service/iot/#IoT.GetTopicRule) (the function that is [being called when this error is logged](https://github.com/hashicorp/terraform-provider-aws/blob/7b4ea14367e7191232a4e3eb6addcd8f68cf31d6/internal/service/iot/topic_rule.go#L1212-L1216)), it calls out:

> Requires permission to access the GetTopicRule (https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiot.html#awsiot-actions-as-permissions) action.

Can you verify that the credentials being used to authenticate with the AWS Provider has the necessary permissions to access `GetTopicRule`?

**Comment by tomscholz** [comment]
The permission is definitely there. As @JoshM1994 already mentioned does it work eventually, but not always. 

> I encountered a similar issue on v2.47
> 
> I was having issues updating an error action - `terraform apply` would always see the change but the rule never got updated. Eventually, I removed the rule manually and ran `terraform rm [resource]` to remove it from the state.
> 
> Upon running a fresh `terraform apply`, the IoT rule was successfully created with the changes I needed
