### ISSUE TITLE
aws_iam_role_policy_attachment using count and list of polices returns an inconsistent result error if the list order is changed

### ISSUE THREAD

**Issue by gchristidis** [hashicorp/terraform-provider-aws#12536]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

If you have an aws_iam_role_policy_attachment resource with a count based on a list of policy arns and you re apply terraform with the list order changed (ie adding a new policy to the front of the list) terraform returns the error
```
Error: Provider produced inconsistent result after apply

When applying changes to aws_iam_role_policy_attachment.test[2], provider
"registry.terraform.io/-/aws" produced an unexpected new value for was
present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

I realize that for_each is better suited in the example below but in my case the list is a module variable where policy arns are passed in and if any of the arns are policies created by terraform then they are not known during planning and cannot be used with for_each.

### Terraform Version

Terraform v0.12.23
+ provider.aws v2.54.0

### Affected Resource(s)

* aws_iam_role_policy_attachment

### Terraform Configuration Files

```hcl
provider "aws" {
  region     = "ap-southeast-2"
}

locals {
    module_name = "TestInstanceProfile"
}

variable "policies" {
    description = "Set to true to create an IAM Instance profile and attach to EC2"
    type        = list(string)
    default     = [ ]
}

data "aws_ami" "ubuntu" {
  filter {
    name   = "name"
    values = ["ubuntu/images/*ubuntu-xenial-16.04-amd64-server-*"]
  }
  filter {
    name   = "architecture"
    values = ["x86_64"]
  }
  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
  filter {
    name   = "root-device-type"
    values = ["ebs"]
  }
  most_recent = true
  owners      = ["099720109477"] # Canonical
}


resource "aws_iam_role" "test" {
  name_prefix        = "${local.module_name}-"
  path               = "/"
  assume_role_policy = <<-EOF
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Action": "sts:AssumeRole",
          "Effect": "Allow",
          "Principal": {
            "Service": "ec2.amazonaws.com"
          },
          "Sid": ""
        }
      ]
    }
    EOF
}

resource "aws_iam_role_policy_attachment" "test" {
  count      = length(var.policies)
  role       = aws_iam_role.test.name
  policy_arn = var.policies[count.index]
}

resource "aws_iam_instance_profile" "test" {
  name_prefix = "${local.module_name}-"
  role        = aws_iam_role.test.name
}

resource "aws_instance" "test" {
  instance_type               = "t3.micro"
  ami                         = data.aws_ami.ubuntu.id
  iam_instance_profile        = aws_iam_instance_profile.test.name
  tags                        = {  "Name" = "${local.module_name}" }
}
```

### Debug Output

https://gist.github.com/gchristidis/337d2f3daf2c5af1948bcc1c4027af9e

### Panic Output

NONE

### Expected Behavior

Resources at index 0 and 1 are destroyed and recreated at index 1 & 2 and a new resource for the new policy is created at index 0

### Actual Behavior

Terraform destroys index 0 & 1 while creating 2 at the same time which might have an issue with attaching the same policy twice.  It then created resources at index 0 & 1.

When Terraform is reapplied after the error its plan shows it created resource at index 2 and works successfully.

### Steps to Reproduce

1. Create with 2 policies in the list
`terraform apply -var policies='[ "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore", "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy" ]'`
2. Add a new policy to the start of the list
`terraform apply -var policies='[ "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess", "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore", "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy" ]'`

### Important Factoids

None

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @gchristidis 👋 Thank you for taking the time to file this. When using `count`, the list is ordered, so adding an additional item that offsets the order will indeed exhibit this behavior. Due to this, `for_each` will be the only way to get around it (you may be able to use [toset()](https://www.terraform.io/docs/language/functions/toset.html), but I'm not positive).

With that said, given that there's been a number of Terraform and AWS Provider releases since you initially filed this, can you let us know if you're still experiencing this at all, or if the behavior has changed in your favor?

**Comment by gchristidis** [comment]
I now make sure that if any new policies are added they are added to then end of the list, so its not a big issue for me.  But latest Terraform and AWS provider still have the issue although a different error.  

```
│ Error: error reading IAM Role Managed Policy Attachment (TestInstanceProfile-20211006035110692400000001:arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy): couldn't find resource
│
│   with aws_iam_role_policy_attachment.test[2],
│   on main.tf line 57, in resource "aws_iam_role_policy_attachment" "test":
│   57: resource "aws_iam_role_policy_attachment" "test" {
```

My only thought is when dealing with count instances is it possible to make the creation phase of any index element dependent on the completion of the destruction phase of any other elements (if any).  

In the example above the first command creates policy attachments
[0] =AmazonSSMManagedInstanceCore
[1] = CloudWatchAgentServerPolicy 

Running the second command adds AmazonS3ReadOnlyAccess to the start of the list moving the others up by 1 so Terraform deletes index [0] & [1] while creating [2], which is the same as [1] at this point creating a race condition of [1] trying to delete CloudWatchAgentServerPolicy and [2] trying to create it.  When [0] and [1] are destroyed they are recreated with the new policies and [2] eventually fails with the error message.  Rerunning Terraform will create [2] and complete.

Having the destroy phase as a dependency means it can destroy [0] & [1] before creating all [3].  It would solve the issue but not sure what other ramifications it would have.

**Comment by mattops** [comment]
I believe this is still an issue.  Using Terraform v1.2.5, AWS provider v4.64.0, and version v5.18 of the IAM module.

In particular this line:

https://github.com/terraform-aws-modules/terraform-aws-iam/blob/1258cbaf8c6a32c15178cbc74dc00503941c32a5/modules/iam-assumable-role-with-oidc/main.tf#L105

Issue occurs if the order of the list in `var.role_policy_arns` changes.

**Comment by justinretzolk** [comment]
Hey @nusnewob 👋 In your configuration, the resources are being recreated (without the error that was initially described) due to the behavior outlined in the [`count` Meta-Argument documentation](https://developer.hashicorp.com/terraform/language/meta-arguments/count#when-to-use-for_each-instead-of-count). Particularly this line:

> If an element was removed from the middle of the list, every instance after that element would see its `subnet_id` value change [this makes more sense in the context of the document], resulting in more remote object changes than intended. Using `for_each` gives the same flexibility without the extra churn.

Since it doesn't look like anyone's experienced the initial error in any recent versions, closing this issue. If you encounter the error listed in the initial report again, please open a new issue, referencing this one where needed.
