### ISSUE TITLE
aws_elasticache_subnet_group import ignores the provided name

### ISSUE THREAD

**Issue by jubagarie** [hashicorp/terraform-provider-aws#12540]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24
+ provider.aws v2.54.0
+ provider.consul v2.6.1

### Affected Resource(s)

* aws_elasticache_subnet_group

### Terraform Configuration Files

```hcl
resource "aws_elasticache_subnet_group" "intra_all_azs" {
  name        = "stg-subnet-group-intra"
  subnet_ids  = module.mymodule.vpc_intra_subnets
}
```

### Debug Output
[Debug logs](https://gist.github.com/jubagarie/0e21cf30ad1eaa7a21006047acbb44a5)

### Expected Behavior

The `terraform import aws_elasticache_subnet_group.intra_all_azs stg-subnet-group-intra` command should find the existing `stg-subnet-group-intra` subnet group and import it into the tfstate.

### Actual Behavior

`terraform import aws_elasticache_subnet_group.intra_all_azs stg-subnet-group-intra` doesn't seem to use the provided `stg-subnet-group-intra` subnet group name.

The subnet group name is missing in the request to the AWS API extracted from the debug logs : 
```Action=DescribeCacheSubnetGroups&CacheSubnetGroupName=&Version=2015-02-02```

No subnet group description is sent in the AWS API response and the `terraform import` command fails.

### Steps to Reproduce

1. Create an Elasticache subnet group in an AWS account.
2. Add an `aws_elasticache_subnet_group` resource definition in you Terraform code.
3. Try to import the existing resource with `terraform import aws_elasticache_subnet_group.tf_resource_name existing_subnet_group_name`

**Comment by ewbankkit** [comment]
@jubagarie Looking at the resource Read code

https://github.com/terraform-providers/terraform-provider-aws/blob/4d04815d5a1c63b8d9fa39c0a5cf194e8cd0c0a7/aws/resource_aws_elasticache_subnet_group.go#L85-L89

you are correct, the `name` attribute isn't set when the resource is being imported (only `id` is).

**Comment by jubagarie** [comment]
After some tests, it appears that the error is on my side.

My AWS provider was initially configured like this : 
```
provider "aws" {
  region = "eu-west-3"

  assume_role {
    role_arn = "arn:aws:iam::${module.my_module.account_id["my_account"]}:role/my_role"
  }
}
```

The module called here looks like this : 
```
output "account_id" {
  value = {
    my_account = "0123456789"
  }
```


I replaced the `${module.my_module.account_id["my_account"]}` part by the account ID, so the provider now looks like this :
```
provider "aws" {
  region = "eu-west-3"

  assume_role {
    role_arn = "arn:aws:iam::0123456789:role/my_role"
  }
}
```

The `terraform import` command is now working as expected.

So, the `import` command isn't compatible with a provider calling a module in the `assume_role` parameter.
It seems to be explained [in this part](https://www.terraform.io/docs/commands/import.html#provider-configuration) of the documentation, which I missed before creating this issue. Sorry about that. :no_mouth:

Anyway, I think we can close this issue.
Thank you for you time !
