### ISSUE TITLE
Incomplete import of aws_instance tags

### ISSUE THREAD

**Issue by rulatir** [hashicorp/terraform-provider-aws#12565]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24
+ provider.aws v2.55.0

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

`init.tf`
```hcl
provider "aws" {
  region = "eu-central-1"
}
```

### Debug Output

I have obtained this information, but since the debug output contains the entirety of AWS API responses received by terraform during the import, and even *determining whether* any of this information is sensitive would be extremely time consuming, I am postponing this step until being advised as to how I can provide this information to a limited circle of developers instead of to everyone who reads this bug report. I am absolutely willing to do so.

Cursory examination of `DescribeInstancesResponse` dumped into the debug log reveals that the tags that are **missing** in generated `terraform.tfstate` are **present** in the response that terraform receives.

### Expected Behavior

`terraform.tfstate` should contain the tags with all the following keys (as seen in AWS Console, and in `DescribeInstancesResponse`):

* `aws:cloudformation:stack-id`
* `aws:autoscaling:groupName`
* `Description`
* `Name`
* `aws:cloudformation:logical-id`

### Actual Behavior

Only the following tags appear in `terraform.tfstate`:

* `Description`
* `Name`

### Steps to Reproduce

1. `terraform import -allow-missing-config aws_instance.example i-0f41347b6cdd25420`

### Important Factoids

* The above command is run on an "empty" terraform configuration. The only configuration file is `init.tf` pasted above, and there is no preexisting `terraform.tfstate`.

**Comment by ewbankkit** [comment]
Related:
* https://github.com/hashicorp/terraform/issues/4513
* https://github.com/hashicorp/terraform/pull/7454

**Comment by justinretzolk** [comment]
It looks like this issue was addressed with https://github.com/hashicorp/terraform/pull/7454. As such, we're going to close this out for now. Please let us know if you feel this was done in error.
