### ISSUE TITLE
aws_macie_s3_bucket_association plans mutually exclusive classification_type settings

### ISSUE THREAD

**Issue by MKgridSec** [hashicorp/terraform-provider-aws#12589]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.12.23
+ provider.aws v2.55.0
```

### Affected Resource(s)

* aws_macie_s3_bucket_association

### Terraform Configuration Files

```hcl
resource "aws_macie_s3_bucket_association" "bucket_example" {
  bucket_name = "bucketymcbucketface"

  classification_type {
    one_time = "NONE"
  }
}
```

### Expected Behavior

```

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_macie_s3_bucket_association.bucket_example will be created
  + resource "aws_macie_s3_bucket_association" "bucket_example" {
      + bucket_name = "bucketymcbucketface"
      + id          = (known after apply)

      + classification_type {
          + one_time   = "NONE"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

### Actual Behavior

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_macie_s3_bucket_association.bucket_example will be created
  + resource "aws_macie_s3_bucket_association" "bucket_example" {
      + bucket_name = "bucketymcbucketface"
      + id          = (known after apply)

      + classification_type {
          + continuous = "FULL"
          + one_time   = "NONE"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

### Steps to Reproduce

1. `terraform plan`
1. Review plan output: of note: both classification types appear, which are contradictory/ mutually exclusive settings per https://www.terraform.io/docs/providers/aws/r/macie_s3_bucket_association.html

### Important Factoids

I'm trying to only classify newly uploaded files and not perform a full classification of the bucket.

### References
* https://www.terraform.io/docs/providers/aws/r/macie_s3_bucket_association.html
* #5201

**Comment by ewbankkit** [comment]
@MKgridSec Thanks for raising this.
In your example it's the `classification_type.continuous` attribute that is being set to `FULL` (which is the default and only currently available value). This will not conflict with the `classification_type.one_time` attribute.
