### ISSUE TITLE
aws_elasticache_cluster should provide means to enable encryption-at-rest

### ISSUE THREAD

**Issue by ralfbergs** [hashicorp/terraform-provider-aws#12592]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It seems currently there is no way to create a single-node cluster with encryption-at-rest enabled:

### New or Affected Resource(s)

* aws_elasticache_cluster

### References

https://www.terraform.io/docs/providers/aws/r/elasticache_cluster.html

* #0000

**Comment by vlamic** [comment]
This can be solved if using `aws_elasticache_replication_group` of 1 instead of `aws_elasticache_cluster`.

**Comment by gdavison** [comment]
Unfortunately, the AWS API used by `aws_elasticache_cluster` does not support at-rest encryption. You can use a `aws_elasticache_replication_group` with a size of 1 to enable encryption

**Comment by gdavison** [comment]
We should update the documentation to make this clear.
