### ISSUE TITLE
AWS RDS The apply command fails the first time with the following errors. If you re run the plan and the run the apply command again it works.

### ISSUE THREAD

**Issue by hvram1** [hashicorp/terraform-provider-aws#12595]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.24
+ provider.aws v2.54.0
+ provider.template v2.1.2

### Affected Resource(s)

* aws_RDS
* aws_subnet

### Terraform Configuration Files

This is part of the Trillian Open source project .I am trying to submit a patch for the AWS deployment and I always hit the error.  I have stored the terraform file in the following github repository . 
[tfvars](https://raw.githubusercontent.com/hvram1/trillianpatch/master/init.tfvars)
[Terraform file](https://raw.githubusercontent.com/hvram1/trillianpatch/master/terraform.tf)
[Template file](https://raw.githubusercontent.com/hvram1/trillianpatch/master/trillian-install.sh.tpl)
[PrivateKey](https://raw.githubusercontent.com/hvram1/trillianpatch/master/trillian.pem)
[PublicKey](https://raw.githubusercontent.com/hvram1/trillianpatch/master/trillian.pem.pub)

### Debug Output

https://gist.github.com/hvram1/081656d8c4ff0b83d9d320d435df5094
This contains 4 files  
1. TerraformApplyLog1stRun
2. TerraformApplyLog2ndRun
3. TerraformPlanLog1stRun
4. TerraformPlanLog2ndRun

### Expected Behavior

The RDS instance is expected to be up and running 

### Actual Behavior

I always get one of the following errors when I run after terraform destroy . 
<pre>
Error: Error creating DB Subnet Group: DBSubnetGroupDoesNotCoverEnoughAZs: DB Subnet Group doesn't meet availability zone coverage requirement. Please add subnets to cover at least 2 availability zones. Current coverage: 1
	status code: 400, request id: 614f7d43-5378-413c-b7b0-ba56102d074e

  on terraform.tf line 87, in resource "aws_db_subnet_group" "dbsubnet":
  87: resource "aws_db_subnet_group" "dbsubnet" {

</pre>
OR 
<pre>
Error: no matching subnet found for vpc with id vpc-0ccdbf64aac782a44

  on terraform.tf line 82, in data "aws_subnet_ids" "created":
  82: data "aws_subnet_ids" "created" {

</pre>
### Steps to Reproduce

0.  The github link above has the files  
*    git clone https://github.com/hvram1/trillianpatch.git
*    cd trillianpatch
*    terraform init
*    . init.sh  ( After replacing the 3 variables for AWS KEYS and WHITELIST )
*   `terraform plan -out TerraformPlan 2>&1 | tee TerraformPlanMessages
*    terraform apply "TerraformPlan" 2>&1 | tee TerraformApplyMessages

I run the plan and apply again and the error disappears and things work normally 

* #0000

**Comment by justinretzolk** [comment]
Hey @hvram1 👋 Thank you for taking the time to file this issue. Given that there's been a number of Terraform and AWS Provider releases since you initially filed it, can you confirm if you're still experiencing this behavior?
