### ISSUE TITLE
AppSync datasource name can't be updated

### ISSUE THREAD

**Issue by ackintosh** [hashicorp/terraform-provider-aws#12608]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.24
+ provider.aws v2.55.0
```

### Affected Resource(s)

* aws_appsync_datasource

### Terraform Configuration Files

```hcl
resource "aws_appsync_datasource" "example_datasource" {
  api_id = aws_appsync_graphql_api.example.id
  name = "livedoor_weather_api"

  type = "HTTP"
  http_config {
    endpoint = "http://weather.livedoor.com"
  }
}


resource "aws_appsync_graphql_api" "example" {
  authentication_type = "API_KEY"
  name = "example"
  schema = file("./schema.graphqls")
}
```

### Debug Output

Here is HTTP logs when the provider sends a request to [UpdateDataSource](https://docs.aws.amazon.com/appsync/latest/APIReference/API_UpdateDataSource.html).

https://gist.github.com/ackintosh/762087d731400d9b538a9ae0302f35ee

### Expected Behavior

The datasource name should be updated.

### Actual Behavior

I got the error when run `terraform apply`:

```bash
$ terraform apply
  ...
  # aws_appsync_datasource.example_datasource will be updated in-place
  ~ resource "aws_appsync_datasource" "example_datasource" {
        ...
      ~ name   = "livedoor_weather_api" -> "livedoor_weather_api_changed"

...
...
  Enter a value: yes

...
...

Error: Provider produced inconsistent final plan

When expanding the plan for aws_appsync_resolver.example_resolver to include
new values learned so far during apply, provider "registry.terraform.io/-/aws"
produced an invalid new value for .data_source: was
cty.StringVal("livedoor_weather_api_changed"), but now
cty.StringVal("livedoor_weather_api").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Steps to Reproduce

1. Change the datasource name:
```diff
-       name   = "livedoor_weather_api" 
+       name   = "livedoor_weather_api_changed"
```

2. `terraform apply`

### References

* [AWS: aws_appsync_resolver - Terraform by HashiCorp](https://www.terraform.io/docs/providers/aws/r/appsync_resolver.html)
* [UpdateDataSource - AWS AppSync](https://docs.aws.amazon.com/appsync/latest/APIReference/API_UpdateDataSource.html)

EDIT: Updated the `Actual Behavior` section with latest version of Terraform.

**Comment by ackintosh** [comment]
I'm working on https://github.com/terraform-providers/terraform-provider-aws/pull/12609 to fix this issue. 😃

**Comment by ackintosh** [comment]
https://github.com/terraform-providers/terraform-provider-aws/pull/12609#issuecomment-608186594

> I've contacted with AWS tech support and understand that the AppSync API document has a mistake about the name parameter. 🙄
> 
> The answers from AWS tech support are:
> 
> * name parameter is not able to be changed
> * If you want to change name, should delete and create again the resource

**Comment by cajund** [comment]
One additional note for this ticket - the console has a limit on the length of the datasource name - 32 chars. Please see screen shot. As seen, it is possible for terraform to insert a string longer than the 32 char limit (also doesn't seem to have an adverse effect on anything).

Also, the datasource cannot be deleted if it is being used in a resolver, so there may be some daisy changing needed in the code (@ackintosh - I imagine you are already aware of this).

Thanks for your work on this.

<img width="829" alt="Screen Shot 2020-06-25 at 8 29 46 AM" src="https://user-images.githubusercontent.com/1558588/85720048-0ad51680-b6be-11ea-9acf-99de9621456a.png">

**Comment by ackintosh** [comment]
Thank you @cajund for your comment! I'll file a PR to fix the issue about the datasource name.
