### ISSUE TITLE
Add ability to enable/disable aws_autoscaling_policy

### ISSUE THREAD

**Issue by jsnod** [hashicorp/terraform-provider-aws#12624]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In Feb 2020 AWS added the ability to enable/disable an Autoscaling Policy: https://aws.amazon.com/about-aws/whats-new/2020/02/amazon-ec2-auto-scaling-now-supports-enabling-and-disabling-scaling-policies/

It would be nice to be able to manage this in Terraform.

### New or Affected Resource(s)

* aws_autoscaling_policy

### Potential Terraform Configuration

```hcl
resource "aws_autoscaling_policy" "bat" {
  name                   = "foobar3-terraform-test"
  scaling_adjustment     = 4
  adjustment_type        = "ChangeInCapacity"
  cooldown               = 300
  autoscaling_group_name = "${aws_autoscaling_group.bar.name}"
  enabled                = true
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2020/02/amazon-ec2-auto-scaling-now-supports-enabling-and-disabling-scaling-policies/
* https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-enable-disable-scaling-policy.html

**Comment by FlorinAndrei** [comment]
Any updates? This would be a very useful attribute.
