### ISSUE TITLE
Can not change target type on existing aws_route

### ISSUE THREAD

**Issue by RomanSaveljev** [hashicorp/terraform-provider-aws#12631]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.24
+ provider.aws v2.55.0
+ provider.github v2.5.1
```

### Affected Resource(s)

* aws_route

### Terraform Configuration Files

```hcl
provider "aws" {
  region      = "eu-west-1"
  max_retries = 10
}

provider "github" {
  anonymous = true
  individual = true
}

//data "github_ip_ranges" "github" {}

resource "aws_vpc" "vpc" {
  cidr_block = "10.200.0.0/16"
}

resource "aws_route_table" "route_table" {
  vpc_id = aws_vpc.vpc.id
}

resource "aws_subnet" "public" {
  vpc_id                          = aws_vpc.vpc.id
  cidr_block                      = "10.200.0.0/22"
  map_public_ip_on_launch         = true
}

resource "aws_internet_gateway" "internet" {
  vpc_id = aws_vpc.vpc.id
}

resource "aws_eip" "eip" {}

resource "aws_nat_gateway" "nat" {
  allocation_id = aws_eip.eip.id
  subnet_id     = aws_subnet.public.id
}

resource "aws_route" "git" {
  route_table_id         = aws_route_table.route_table.id
  destination_cidr_block = "8.8.8.8/32"
  //gateway_id             = aws_internet_gateway.internet.id
  nat_gateway_id         = aws_nat_gateway.nat.id
}
```

### Debug Output

https://gist.github.com/RomanSaveljev/0d5f4ca81c0d343cf79418ae6e2c8ac3

### Expected Behavior

* Changing route target from IGW to NAT succeeds

### Actual Behavior

 * `terraform apply` fails

### Steps to Reproduce

* Take embedded HCL and comment `nat_gateway_id` and uncomment `gateway_id`
* `terraform apply` to bring the infrastructure up
* Comment `gateway_id` and uncomment `nat_gateway_id`
* `terraform apply` to change route target

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/13079
* https://github.com/terraform-providers/terraform-provider-aws/issues/13302
