### ISSUE TITLE
ELB is not getting created with AZ and Subnets

### ISSUE THREAD

**Issue by bharti8085** [hashicorp/terraform-provider-aws#12635]
I am using below in my tf file.

resource "aws_elb" "elb" {
name = "${var.name}-lb"
availability_zones = [var.availability_zones]
subnets = [var.subnets]
security_groups = [var.security_groups]

I get below error when i run terraform plan

**Error creating ELB: ValidationError: Only one of SubnetIds or AvailabilityZones may be specified
status code: 400**

If I remove availability_zones and keep only subnets then I get below error.

**The argument "availability_zones" is required, but no definition was found.**

If I remove subnets and keep only availability_zones then I get below error.

**The argument "subnets" is required, but no definition was found.**

**Comment by iNeedICS** [comment]
> `availability_zones` - (Required for an EC2-classic ELB) The AZ's to serve traffic in.
> ...
> `subnets` - (Required for a VPC ELB) A list of subnet IDs to attach to the ELB.

According to the docs, for the elb resource, seems like you would need both? Correct me if I am wrong.

**Comment by bharti8085** [comment]
@iNeedICS - Yes, you are right. That's the reason. I am providing both.

**Comment by bharti8085** [comment]
When this issue would be closed?
