### ISSUE TITLE
Allow aws_dx_gateway_association to return transit_gateway_attachment_id when attaching TGW to DXGW

### ISSUE THREAD

**Issue by arnvid** [hashicorp/terraform-provider-aws#12646]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
When working with TGW attachments and TGW routing the missing transit_gateway_attachment_id requires us to use the data object aws_ec2_transit_gateway_dx_gateway_attachment which triggers a replacement of the following resources:
aws_ec2_transit_gateway_route_table_association
aws_ec2_transit_gateway_route

### New or Affected Resource(s)
  # aws_ec2_transit_gateway_route_table_association.tgw_route_XXXXX must be replaced
  # aws_ec2_transit_gateway_route.tgw_route_XXXXX must be replaced

### Potential Terraform Configuration

```hcl
resource "aws_dx_gateway_association" "dx_gw_assoc_tgw_XXXX" {
  dx_gateway_id         = aws_dx_gateway.dxgw_XXXX.id
  associated_gateway_id = module.tgw_XXXX.tgw_id
  allowed_prefixes = var.dxgw_tgw_prefixes
}

data "aws_ec2_transit_gateway_dx_gateway_attachment" "dx_tgw_attach" {
  transit_gateway_id = module.tgw_XXXX.tgw_id
  dx_gateway_id         = aws_dx_gateway.dxgw_XXXX.id
  depends_on = [aws_dx_gateway_association.dx_gw_assoc_tgw_XXXX]
}

resource "aws_ec2_transit_gateway_route_table_association" "tgw_route_assoc_dx_XXXXX" {
   transit_gateway_attachment_id = data.aws_ec2_transit_gateway_dx_gateway_attachment.dx_tgw_attach.id
   transit_gateway_route_table_id = module.tgw_XXXX.tgw_rt_XXXXX_id
}

resource "aws_ec2_transit_gateway_route" "tgw_route_YYYYYYY_to_XXXXX" {
  destination_cidr_block         = "192.168.0.0/24"
  transit_gateway_attachment_id  = data.aws_ec2_transit_gateway_dx_gateway_attachment.dx_tgw_attach.id
  transit_gateway_route_table_id = module.tgw_XXXX.tgw_rt_YYYYY_id
}

```

### References
* #0000

**Comment by ewbankkit** [comment]
@arnvid Thanks for raising this.
At one point during development (https://github.com/terraform-providers/terraform-provider-aws/pull/8528/commits/708a9e23d98d528fa171f571a8f00bd5c188294b) there was code to return the attachment ID but this [was removed](https://github.com/terraform-providers/terraform-provider-aws/pull/8528#pullrequestreview-240737460) as it involved a call to the EC2 service when managing a DirectConnect resource.
Could you please add an example of using the intermediate data source causing the RT and RT association to be recreated?

**Comment by arnvid** [comment]
@ewbankkit - it is in the code above - but any place you refrence the data    transit_gateway_attachment_id = data.aws_ec2_transit_gateway_dx_gateway_attachment.dx_tgw_attach.id

it gets replaced.

**Comment by arnvid** [comment]
This also breaks routing for 20-30 seconds while this gets reprovisioned.

**Comment by ewbankkit** [comment]
@arnvid I could repro the issue with a configuration very similar to yours.
Could you please change

```hcl
data "aws_ec2_transit_gateway_dx_gateway_attachment" "dx_tgw_attach" {
  transit_gateway_id = module.tgw_XXXX.tgw_id
  dx_gateway_id      = aws_dx_gateway.dxgw_XXXX.id

  depends_on = [aws_dx_gateway_association.dx_gw_assoc_tgw_XXXX]
}
```

to

```hcl
data "aws_ec2_transit_gateway_dx_gateway_attachment" "dx_tgw_attach" {
  transit_gateway_id = aws_dx_gateway_association.dx_gw_assoc_tgw_XXXX.associated_gateway_id
  dx_gateway_id      = aws_dx_gateway_association.dx_gw_assoc_tgw_XXXX.dx_gateway_id
}
```

and see if this helps?

**Comment by arnvid** [comment]
@ewbankkit  - that seems to remove the recreation

**Comment by krzysztof-magosa** [comment]
@ewbankkit i also can confirm that this construct helps.
