### ISSUE TITLE
Create was budget resource needs to support multiple linked accounts

### ISSUE THREAD

**Issue by mahpatil** [hashicorp/terraform-provider-aws#12669]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
The create budget resource needs to support multiple linked accounts. AWS budgets support using multiple linked accounts when creating a budget. This is especially important in a multi-account setup, so you can configure a budget across multiple accounts (dev, stage, prod) for a particular product or business unit. For some reason LinkedAccount in the C

### New or Affected Resource(s)

* aws_budgets_budget

### Potential Terraform Configuration

```hcl

resource "aws_budgets_budget" "product1_allservices" {
  name              = "budget-product1-allservices"
  budget_type       = "COST"
  limit_amount      = "50000"
  limit_unit        = "USD"
  time_unit         = "MONTHLY"
  time_period_start = "2020-03-01_00:00"

  cost_filters = {
    LinkedAccount = ["XXXX", "xxxx2"] //dev & prod accounts, currently this has to be a string
  }

  notification {
    comparison_operator        = "GREATER_THAN"
    threshold                  = 100
    threshold_type             = "PERCENTAGE"
    notification_type          = "FORECASTED"
    subscriber_email_addresses = ["a@gmail.com"]
  }
}


```

### References

* #0000

**Comment by jurajseffer** [comment]
From my testing it not only doesn't support using multiple accounts but it actually overrides the value (to a comma separated string) if you modify it outside of terraform even though the change will not show up in the plan.

**Comment by ChristophShyper** [comment]
Would be great to finally implement it. A lot of us use multi-account and this is crucial.

**Comment by ewbankkit** [comment]
Related:

* #5890
* #13288
