### ISSUE TITLE
terraform apply fails creating security group rules and erases all the current rules within single aws_security_group

### ISSUE THREAD

**Issue by varks** [hashicorp/terraform-provider-aws#12670]
Hi Team,

The terraform behavior for security groups is not consistent with terraform philosophy. For the below cases, terraform plan succeeds, but terraform apply fails causing service disruption.

Failure on terraform apply, would erase all the rules associated with a particular security group. This means that rules that were previously present are no longer there resulting in packet drops and service disruption.

```hcl

resource "aws_security_group_rule" "example_rule" {
--
  | description       = "Policy from  a to b "
  | type              = "ingress"
  | from_port         = 0
  | to_port           = 0
  | protocol          = "-1"
  | cidr_blocks       = ["1.1.1.2/32", "1.1.1.3/32", "1.1.1.4/32", "1.1.1.5/32", "1.1.1.6/32", "1.1.1.10/32","1.1.1.9/32", "1.1.1.8/32", "1.1.1.7/32" ]
  | security_group_id = "${aws_security_group.example.id}"
  | }
```

Failure modes:
* if the number of ips in cidr_blocks is more than security group limits, terraform apply fails and removes all the previous rules.
*  if there are duplicate ips in cidr_blocks, terraform apply fails and removes all the previous rules.

The above failure modes should either be caught at terraform plan stage or terraform apply should not delete the current rules on failure.

A similar request was claimed to be addressed in https://github.com/terraform-providers/terraform-provider-aws/issues/1885. However, the above failure modes is still seen in 

 provider.aws: version = “~> 2.49”
 terraform version: "v0.11.4"

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
provider.aws: version = “~> 2.49”
 terraform version: "v0.11.4"

### Affected Resource(s)

* aws_security_group
* aws_security_group_rule

### Failure message
```aws_security_group_rule.example_rule: Error authorizing security group rule type ingress: RulesPerSecurityGroupLimitExceeded: The maximum number of rules per security group has been reached.```

### Expected Behavior

On failure, terraform should **not** remove all the rules in the cidr. It should restore the rules to the previous state. For any failure in apply, the previous state must be retained.

### Actual Behavior
On failure in terraform apply, all rules attached to security group are deleted.

### Steps to Reproduce

1. create a security group rule with more than 60 cidrs.
2. `terraform plan`
3. `terraform apply`

### References

* #1885

**Comment by justinretzolk** [comment]
Hey @varks 👋 Thank you for taking the time to file this issue. Given that there's been a number of Terraform and AWS Provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?

**Comment by tnqv** [comment]
In `terraform-provider-aws versions: 3.46.0` I ran into this issue too which caused critical service disruption when the SecurityGroups IP list exceeds the limit. Currently, do we have any plan to work on this issue in the future?

**Comment by justinretzolk** [comment]
Hey @tnqv 👋 Thank you for letting us know that you experienced this in `3.46.0` as well. Would it be possible to test within a newer version of the AWS Provider to see if perhaps it was fixed along the way? The most recent version of the AWS Provider (in the `3.x` series) at the time of writing is `3.74.0`.

**Comment by mattburgess** [comment]
@justinretzolk we're seeing this here as well with `4.13.0` (we'll get to upgrading at some point, I'm sure!). The issue is that https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ec2/vpc_security_group_rule.go#L50 forces the creation of a new SG rule if the `cidr_blocks` changes and that in turn is due to limitations of the underlying AWS API.

As there is no plan-time validation of that `cidr_blocks` attribute then TF will delete the SG rule without first checking that it'll be able to successfully recreate it. Unfortunately, the limit that we hit is an adjustable Service Quota `Inbound or outbound rules per security group` (`L-0EA8095F1`). So the provider is presumably going to have to query for that value in order to determine if the new rules will exceed the quota. I couldn't immediately see any examples of other resources doing this so am concerned this might be an anti-pattern of some kind.

There are some [tests](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ec2/vpc_security_group_test.go#L2610) for inline SG rules inside `aws_security_group`s themselves, but not similar ones for `aws_security_group_rule` that I could see. I'll see if I can repro locally with a test case and go from there.

**Comment by mattburgess** [comment]
Maybe we shouldn't fix this in the provider? The following works fine for me as long as I'm using Terraform-1.2 or later:

```hcl
variable "num_rules" {
  type    = number
  default = 60
}

locals {
  ips = [
    for i in range(var.num_rules) : cidrsubnet("172.16.0.0/12", 20, i + 2)
  ]
}

resource "aws_vpc" "test" {
  cidr_block = "192.168.0.0/16"
}

resource "aws_security_group" "test" {
  vpc_id      = aws_vpc.test.id
  description = "Test"
}

data "aws_servicequotas_service" "ec2" {
  service_name = "Amazon Virtual Private Cloud (Amazon VPC)"
}

data "aws_servicequotas_service_quota" "sg_rule_limit" {
  service_code = data.aws_servicequotas_service.ec2.service_code
  quota_name   = "Inbound or outbound rules per security group"
}

resource "aws_security_group_rule" "test" {
  security_group_id = aws_security_group.test.id
  description       = "Test"
  type              = "ingress"
  cidr_blocks       = local.ips
  from_port         = 8080
  to_port           = 8080
  protocol          = "tcp"

  lifecycle {
    precondition {
      condition     = data.aws_servicequotas_service_quota.sg_rule_limit.value >= length(local.ips)
      error_message = "Too many rules in SG. Limit = ${data.aws_servicequotas_service_quota.sg_rule_limit.value}, Number of rules = ${length(local.ips)}"
    }
  }
}
```

```sh
$ terraform apply -auto-approve
data.aws_servicequotas_service.ec2: Reading...
data.aws_servicequotas_service.ec2: Read complete after 1s [id=vpc]
data.aws_servicequotas_service_quota.sg_rule_limit: Reading...
data.aws_servicequotas_service_quota.sg_rule_limit: Read complete after 1s [id=arn:aws:servicequotas:eu-west-2::vpc/L-0EA8095F]
...
Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

```sh
$ TF_VAR_num_rules=61 terraform apply -auto-approve
data.aws_servicequotas_service.ec2: Reading...
aws_vpc.test: Refreshing state... [id=vpc-03a577c7fdabdd60c]
aws_security_group.test: Refreshing state... [id=sg-0e3f2c7bd58f66eef]
data.aws_servicequotas_service.ec2: Read complete after 1s [id=vpc]
data.aws_servicequotas_service_quota.sg_rule_limit: Reading...
data.aws_servicequotas_service_quota.sg_rule_limit: Read complete after 0s [id=arn:aws:servicequotas:eu-west-2::vpc/L-0EA8095F]
aws_security_group_rule.test: Refreshing state... [id=sgrule-582640947]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Resource precondition failed
│ 
│   on vpc.tf line 41, in resource "aws_security_group_rule" "test":
│   41:       condition     = data.aws_servicequotas_service_quota.sg_rule_limit.value >= length(local.ips)
│     ├────────────────
│     │ data.aws_servicequotas_service_quota.sg_rule_limit.value is 60
│     │ local.ips is tuple with 61 elements
│ 
│ Too many rules in SG. Limit = 60, Number of rules = 61
```

I'd be more than happy to add this example to the docs if we think this is the way forward.

**Comment by mattburgess** [comment]
In addition, the following precondition will catch the duplicate case:

```hcl
    precondition {
      condition     = length(distinct(local.ips)) == length(local.ips)
      error_message = "Duplicate CIDR range found in SG rules"
    }
```

**Comment by varks** [comment]
@mattburgess Thanks for sharing. This looks like a reasonable solution.

**Comment by tnqv** [comment]
@mattburgess Thanks for sharing, this solution LGTM to me. 
But we're having a lot of `aws_security_group_rule` defining in our codebase. Define lifecycle for every single one of it seems to be stressed out. Currently I'm using OPA looping to check all of it from the terraform plan results.
The OPA policies implemented idea is similar to the above solution. :+1:

**Comment by justinretzolk** [comment]
@mattburgess Thanks for following up with that excellent sample configuration! I know I've seen folks mention other resources that have similar adjustable Service Quota limits, and similar to you, I can't recall us ever building in the functionality to have that checked real-time (and am not sure that's a pattern we'd be interested in implementing). I think adding your example to the documentation would be an awesome resource for other people who might run into this. As always, more than happy to work with you on getting a PR raised/merged 🙂.

**Comment by mattburgess** [comment]
It's probably also worth mentioning the very new (since 4.56.0) [`aws_vpc_security_group_ingress_rule`](https://registry.terraform.io/providers/-/aws/latest/docs/resources/vpc_security_group_ingress_rule) and [`aws_vpc_security_group_egress_rule`](https://registry.terraform.io/providers/-/aws/latest/docs/resources/vpc_security_group_egress_rule) resources which should help quite a lot with issues like this as it manages rules individually rather than as an entire 'block'.

e.g.

```hcl
resource "aws_vpc_security_group_ingress_rule" "test" {
  for_each          = toset(local.ips)
  security_group_id = aws_security_group.test.id
  ip_protocol       = "tcp"
  cidr_ipv4         = each.value
  from_port         = 8080
  to_port           = 8080
}
```

On an initial run, that'll create 60 individual SG rules, mapping 1:1 with exactly what you see in the AWS console. On the 2nd run, setting `num_rules` to `61`, you now get this behaviour:

```
$ TF_VAR_num_rules=61 terraform apply
... # skipped showing over 60 lines of output here!
Terraform will perform the following actions:

  # aws_vpc_security_group_ingress_rule.test["172.16.0.62/32"] will be created
  + resource "aws_vpc_security_group_ingress_rule" "test" {
      + arn                    = (known after apply)
      + cidr_ipv4              = "172.16.0.62/32"
      + from_port              = 8080
      + id                     = (known after apply)
      + ip_protocol            = "tcp"
      + security_group_id      = "sg-0d50eabaacdda46a2"
      + security_group_rule_id = (known after apply)
      + tags_all               = {}
      + to_port                = 8080
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_vpc_security_group_ingress_rule.test["172.16.0.62/32"]: Creating...
╷
│ Error: creating VPC Security Group Rule
│ 
│   with aws_vpc_security_group_ingress_rule.test["172.16.0.62/32"],
│   on vpc.tf line 31, in resource "aws_vpc_security_group_ingress_rule" "test":
│   31: resource "aws_vpc_security_group_ingress_rule" "test" {
│ 
│ RulesPerSecurityGroupLimitExceeded: The maximum number of rules per security group has been reached.
│ 	status code: 400, request id: e019f0f0-546f-44dc-8c3c-5e3a118e5618
╵
```

That out of the box behaviour is _so_ much nicer than the older `aws_security_group_rule`. It's still not perfect as it could still lead to disruption, e.g. if your plan shows 1 deletion and 2 additions, but those `precondition`s can still be used to provide additional protection if required.

**Comment by mattburgess** [comment]
@justinretzolk I reckon so, yeah!
