### ISSUE TITLE
aws_lb_cookie_stickiness_policy doesn't support cookie_expiration_period = 0

### ISSUE THREAD

**Issue by haidangwa** [hashicorp/terraform-provider-aws#12678]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform --version
Terraform v0.12.24
+ provider.aws v2.49.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.template v2.1.2
+ provider.tls v2.1.1
```

### Affected Resource(s)

* aws_lb_cookie_stickiness_policy

### Terraform Configuration Files

```hcl
resource "aws_lb_cookie_stickiness_policy" "elb" {
  name                     = "ELBCookiePolicy-${var.hostname}-${var.environment}"
  load_balancer            = aws_elb.elb.id
  lb_port                  = var.elb_listener_port
  cookie_expiration_period = 0
}
```

### Expected Behavior

According to [AWS documentation](https://docs.aws.amazon.com/cli/latest/reference/elb/create-lb-cookie-stickiness-policy.html), setting `cookie_expiration_period = 0` or not including this property in the config should be supported.

```
--cookie-expiration-period (long)

The time period, in seconds, after which the cookie should be considered stale. If you do not specify this parameter, the default value is 0, which indicates that the sticky session should last for the duration of the browser session.
```

### Actual Behavior

```
Error: expected cookie_expiration_period to be at least (1), got 0

  on modules/classic_lb/main.tf line 34, in resource "aws_lb_cookie_stickiness_policy" "elb":
  34: resource "aws_lb_cookie_stickiness_policy" "elb" {



Error: expected cookie_expiration_period to be at least (1), got 0

  on modules/classic_lb/main.tf line 34, in resource "aws_lb_cookie_stickiness_policy" "elb":
  34: resource "aws_lb_cookie_stickiness_policy" "elb" {

```

Leaving this property out of the resource configuration creates the policy with `expirationPeriod=0`

This configuration works:
```
resource "aws_lb_cookie_stickiness_policy" "elb" {
  name          = "ELBCookiePolicy-${var.hostname}-${var.environment}"
  load_balancer = aws_elb.elb.id
  lb_port       = var.elb_listener_port
}
```

### Steps to Reproduce

Create a classic load balancer and attach the aws_lb_cookie_stickiness_policy resource to it. Then run `terraform plan`

**Comment by DrFaust92** [comment]
the aws sdk fails on validation when the value is zero. so i guess this was done in the provider to guard against this as well

**Comment by DonBower** [comment]
not sure about the sdk, but the CLI supports it, so I would have to assume the SDKs do as well:
from [modify-target-group-attributes](https://docs.aws.amazon.com/cli/latest/reference/elbv2/modify-target-group-attributes.html)
```
stickiness.type - The type of sticky sessions. The possible values are lb_cookie for Application Load Balancers or source_ip for Network Load Balancers.
```

**Comment by jimbrowne** [comment]
This is also a problem with `aws_load_balancer_policy` and `policy_type_name   = "LBCookieStickinessPolicyType"`.

If one includes a stanza of:
```      
policy_attribute {
          name  = "CookieExpirationPeriod"
          value = "0"
        }
```
a validation error will be thrown by Terraform that the value must be a non-zero long.

But if one uses:
```
resource "aws_load_balancer_policy" "cookie-sticky" {
  load_balancer_name = aws_elb.elb[count.index].name
  count              = var.enable ? 1 : 0
  policy_name        = "${var.name}-cookie-sticky"   
  policy_type_name   = "LBCookieStickinessPolicyType"
}
```

this will apply the first time and create a policy with a value of zero, *however* on every subsequent apply a change is applied:
``` 
# module.lms-infrastructure.module.elbs.module.elk-vip.aws_load_balancer_policy.cookie-sticky[0] will be updated in-place
  ~ resource "aws_load_balancer_policy" "cookie-sticky" {
        id                 = "uflc-elk:uflc-elk-cookie-sticky"  
        load_balancer_name = "uflc-elk"
        policy_name        = "uflc-elk-cookie-sticky"
        policy_type_name   = "LBCookieStickinessPolicyType"

      - policy_attribute {
          - name  = "CookieExpirationPeriod" -> null
          - value = "0" -> null
        }
    }
```

*But* if the `policy_attribute` stanza is added after the ELB policy already exists no change will be flagged.

So there's some round trip problem happening here with the AWS API.
