### ISSUE TITLE
Elasticache Global Datastore for Redis Support

### ISSUE THREAD

**Issue by h-aboyd** [hashicorp/terraform-provider-aws#12708]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Recently, AWS has announced [Elasticache Global Datastore for Redis](https://aws.amazon.com/blogs/aws/now-available-amazon-elasticache-global-datastore-for-redis/). However, this is currently unsupported by the AWS provider. 

For those with use-cases that require the global datastore but also using terraform as our main utility when provisioning resources in the cloud, this is a blocking issue for us.

### New or Affected Resource(s)

* aws_elasticache_cluster 
* aws_elasticache_replication_group 
* aws_elasticache_parameter_group

**Comment by JeroenRijks** [comment]
I'm not good enough at Go to make sense of the codebase, so I can't create a PR myself. I'm happy to do manual testing and provide feedback once a PR gets made

**Comment by DanielMarcotte** [comment]
Guys do you have any ETA for that PR? Redis Global Datastore are almost 1 year old and there's still no support in terraform for them I believe.
