### ISSUE TITLE
Data Sources for Database Migration Service (DMS) Resources

### ISSUE THREAD

**Issue by elijah-ward** [hashicorp/terraform-provider-aws#12713]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I have a use case where I would like to build one module that defines a DMS replication instance and subnet, then another which would define a set of endpoints and a replication task. I need to be able to reference the ARN of the replication instance, whose creation is encapsulated in the other module. It would be nice to have a `data_source_dms_replication_instance` so that I can keep these modules completely decoupled and be able to query for the ARN based on the instance id or other filters as can be done for `data_source_aws_instance` or its RDS counterpart. While we're at it it may be useful to some to add data sources for the other DMS resources.

### New or Affected Resource(s)

* aws_dms_certificate
* aws_dms_endpoint
* aws_dms_replication_instance
* aws_dms_replication_subnet_group
* aws_dms_replication_task

### Potential Terraform Configuration

```hcl
data "aws_dms_replication_instance" "foo" {
  instance_id = "i-instance-id"
  filter {
    name   = "tag:Name"
    values = ["foo", "bar"]
  }
}

resource "aws_dms_replication_task" "foo" {
  migration_type           = "full-load"
  replication_instance_arn = data.aws_dms_replication_instance.foo.arn
  ...
}
```

If I find the time in the coming days I will take a crack at it but I thought I would pose it to the community first.

**Comment by snypelife** [comment]
Opened a PR for this (#15406). Only tackled the replication_instance for now.
