### ISSUE TITLE
Implicit dependency does not work with aws_shield_protection at the time of REMOVAL

### ISSUE THREAD

**Issue by shahamit2** [hashicorp/terraform-provider-aws#12725]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.3
+ provider.aws v2.38.0
+ provider.null v2.1.2

### Affected Resource(s)

* aws_shield_protection
* aws_lb (load_balancer_type:  application)

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
Code is very lengthy of complete stack. It is copyright of organisation and hence can't share the complete code. It's launching the complete stack hence not possible to share part of it.

### Panic Output

Error: Cycle: module.shield_alb.aws_shield_protection.this[0] (destroy), module.alb_target.aws_lb.this[0] (destroy), module.alb_target.output.lb, module.shield_alb.var.name, module.shield_alb.aws_shield_protection.this (prepare state), module.shield_alb.aws_shield_protection.this[1] (destroy), module.alb_target.aws_lb.this[1] (destroy)

### Expected Behavior

ALB info is passed to AWS shield. It is working as expected at time of creation. At time of deletion it is running into "cycle" error. Implicit dependency of passing output is working fine at the time of creation but not deletion.

### Actual Behavior

Terraform is trying to delete both resources ALB and AWS shield in parallel. Even though there is a implicit dependency of output variable of ALB is passed to AWS shield. 

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @shahamit2 👋 Thank you for taking the time to file this. Given that there's been a number of Terraform and AWS provider releases since you initially filed it, can you confirm if you're still experiencing this behavior?
