### ISSUE TITLE
Add support for Redshift scheduled actions

### ISSUE THREAD

**Issue by timurb** [hashicorp/terraform-provider-aws#12745]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It looks like there is currently no support for AWS Redshift scheduled actions such as pause and resume (those actions and schedules are different to those of snapshots) — at least I could not find any references to them in docs nor in issue tracker here.

### New or Affected Resource(s)

* aws_redschift_scheduled_action

### Potential Terraform Configuration

```hcl
resource "aws_redschift_scheduled_action" "this" {
  name = "nightly-pause"
  description = "Pause redshift cluster for the night"  # optional
  active = true  # optional

  # possibly use some more user-friendly time format here
  start_time = "2020-04-10T00:00:00+00:00"  # optional
  end_time = "2020-05-11T00:00:00+00:00"  # optional
  schedule = "cron(00 21 * * ? *)"   # time is UTC
  iam_role = aws_iam_role.scheduler.arn 

  target_action {
    action = "PauseCluster"
    cluster_identifier = aws_redshift_cluster.this.id
  }
}
```

### References

* https://docs.aws.amazon.com/redshift/latest/APIReference/API_ScheduledAction.html

**Comment by vijetha35** [comment]
https://docs.aws.amazon.com/redshift/latest/APIReference/API_ScheduledActionType.html

**Comment by spaszek** [comment]
This could _almost_ be merged already - https://github.com/terraform-providers/terraform-provider-aws/pull/13474 - seems like done but abandoned.

**Comment by tisteandii11** [comment]
Any news on this? It can be very helpful.

**Comment by olegflo** [comment]
Voting for this resource 👍

**Comment by niraj8241** [comment]
+1 for this

**Comment by niraj8241** [comment]
I have a lot of use case where I want to give my team the functionality to pause and resume the cluster when needed. Having this would be great

**Comment by vijetha35** [comment]
this feature is already there for pause and resume, resize,

**Comment by niraj8241** [comment]
@vijetha35 I am unable to find any such option in terraform resources for Redshift that supports scheduled pause/resume. Can you please point me to the resource?
