### ISSUE TITLE
Data source for ec2 Traffic Mirror Resources 

### ISSUE THREAD

**Issue by chrislujan** [hashicorp/terraform-provider-aws#12769]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Data sources for the following resources would be very helpful. I am building out traffic mirroring where a traffic mirror session is not declared in the same place the traffic mirror filter/target would be declared. Targets and filters are generally used across many traffic mirror sessions that would likely be declared upon instance creation.

### New or Affected Resource(s)

- aws_ec2_traffic_mirror_filter
- aws_ec2_traffic_mirror_filter_rule
- aws_ec2_traffic_mirror_target
- aws_ec2_traffic_mirror_session

### Potential Terraform Configuration

infrastructure/main.tf: 
```
resource "aws_ec2_traffic_mirror_filter" "some_mirror" {
  name = "some-filter"
}

resource "aws_ec2_traffic_mirror_target" "some-target" {
  name = "some-target"
}
```

some-project/main.tf:
```
data "aws_ec2_traffic_mirror_filter" "some-filter" {
  name = "some-filter"
}

data "aws_ec2_traffic_mirror_target" "some-target" {
  name = "some-target"
}

resource "aws_ec2_traffic_mirror_session" "some-session" {
  network_interface_id     = data.aws_instance.foo.primary_network_interface_id
  traffic_mirror_filter_id    = data.aws_ec2_traffic_mirror_filter.some-filter.id
  traffic_mirror_target_id  = data.aws_ec2_traffic_mirror_target.some-target.id
}
```
### References

https://github.com/terraform-providers/terraform-provider-aws/issues/9140

**Comment by radius314** [comment]
Is there a timeline for this feature request?
