### ISSUE TITLE
directory service - add capability to register sns topic

### ISSUE THREAD

**Issue by cstehlin** [hashicorp/terraform-provider-aws#12761]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

aws cli and console offer ability to register a directory service to an SNS topic, to send alarms on status changes:
https://docs.aws.amazon.com/cli/latest/reference/ds/register-event-topic.html

This is missing in terraform
Thanks

### New or Affected Resource(s)

* aws_directory_service_directory

**Comment by DrFaust92** [comment]
Closing in favor of #28279
