### ISSUE TITLE
aws_elasticsearch_domain - please consider SUCCEEDED_WITH_ISSUES(UpgradeStatus) as `terraform apply` succeeded

### ISSUE THREAD

**Issue by sogaoh** [hashicorp/terraform-provider-aws#12783]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please modify to give a success   
if result of `terraform apply` is `SUCCEEDED_WITH_ISSUES`.  
(if possible, with a warning.)

- because I got below after `29 minutes` apply: 
  ```
  Error: unexpected state 'SUCCEEDED_WITH_ISSUES', wanted target 'SUCCEEDED'. last error: %!s(<nil>)
  ```

### New or Affected Resource(s)

* I think this affects the [aws_elasticsearch_domain resource](https://www.terraform.io/docs/providers/aws/r/elasticsearch_domain.html)

### Potential Terraform Configuration

```hcl
resource "aws_elasticsearch_domain" "upgrade-domain" {
  #・・・
  elasticsearch_version = "7.4"   # <- 7.1
  #・・・
}
```

### References

* https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/elasticsearch/model/UpgradeStatus.html

**Comment by obourdon** [comment]
Exact same behaviour on my side today upgrading from 6.8 to 7.10

```
aws_elasticsearch_domain.logs[0]: Still modifying... [id=arn:aws:es:eu-west-1:328204580322:domain/logs, 42m38s elapsed]

Warning: Applied changes may be incomplete

The plan was created with the -target option in effect, so some changes
requested in the configuration may have been ignored and the output values may
not be fully updated. Run the following command to verify that no other
changes are pending:
    terraform plan

Note that the -target option is not suitable for routine use, and is provided
only for exceptional situations such as recovering from errors or mistakes, or
when Terraform specifically suggests to use it as part of an error message.


Error: error waiting for Elasticsearch Domain Upgrade (arn:aws:es:eu-west-1:328204580322:domain/logs) to succeed: unexpected state 'SUCCEEDED_WITH_ISSUES', wanted target 'SUCCEEDED'. last error: %!s(<nil>)

  on logging.tf line 37, in resource "aws_elasticsearch_domain" "logs":
  37: resource "aws_elasticsearch_domain" "logs" {


make: *** [terraform-apply] Error 1
```
