### ISSUE TITLE
aws_eks_node_group is missing way to configure taints on nodes

### ISSUE THREAD

**Issue by lzecca78** [hashicorp/terraform-provider-aws#12780]
I am trying to add taints to node_group, but is currently missing a parameter that allow that.
Is there a workaround for that or the only way is to change approach and  discard the aws_eks_node_group resource making manually asg and so on?

**Comment by aviau** [comment]
Is this even possible with the EKS API?

The only documentation that I can find is here:
 - https://aws.amazon.com/blogs/opensource/improvements-eks-worker-node-provisioning/

EKS node groups are backed by AutoScaling Groups, which are available from the aws_eks_node_group attributes.

Autoscaling groups are backed by launch configuration, which contain User data scripts.

User data scripts created by EKS contain code that calls ``/etc/eks/bootstrap.sh``.

As a workaroud until this is fully implemented in terraform, I think that it would be possible to find that launch template from the eks_node_group and manage it with terraform?

I don't want to go around breaking everything but I really need this feature.

**Comment by bflad** [comment]
Hi folks 👋  As mentioned in the excellent comment above, this is not directly supported in the EKS API, therefore it is not something we would implement in the Terraform AWS Provider `aws_eks_node_group` resource. To follow the upstream issue on this, please see https://github.com/aws/containers-roadmap/issues/864. When that support is potentially implemented, we can revisit adding this functionality within the Terraform AWS Provider. 👍
