### ISSUE TITLE
Support for AWS Cost Categories

### ISSUE THREAD

**Issue by anshprat** [hashicorp/terraform-provider-aws#12801]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for AWS Cost Categories

https://aws.amazon.com/about-aws/whats-new/2019/11/introducing-aws-cost-categories/

https://aws.amazon.com/aws-cost-management/aws-cost-categories/

https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_CreateCostCategoryDefinition.html

https://docs.aws.amazon.com/cli/latest/reference/ce/create-cost-category-definition.html

### New or Affected Resource(s)

New

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by sshvetsov** [comment]
Cost Categories are now in GA as of April 21, 2020, including some changes to the API: https://aws.amazon.com/about-aws/whats-new/2020/04/introducing-aws-cost-categories/

**Comment by sshvetsov** [comment]
### New or Affected Resource(s)



* aws_cost_category_definition

### Potential Terraform Configuration



```hcl
resource "aws_cost_category_definition" "environment" {
  name = "Environment"
  rule_version = "CostCategoryExpression.v1"
  rules = <<CONTENT
[
    {
        "Value": "production",
        "Rule": {
            "Dimensions": {
                "Key": "LINKED_ACCOUNT_NAME",
                "Values": [
                    "-prod"
                ],
                "MatchOptions": [
                    "ENDS_WITH"
                ]
            }
        }
    },
    {
        "Value": "staging",
        "Rule": {
            "Dimensions": {
                "Key": "LINKED_ACCOUNT_NAME",
                "Values": [
                    "-stg"
                ],
                "MatchOptions": [
                    "ENDS_WITH"
                ]
            }
        }
    },
    {
        "Value": "testing",
        "Rule": {
            "Dimensions": {
                "Key": "LINKED_ACCOUNT_NAME",
                "Values": [
                    "-dev"
                ],
                "MatchOptions": [
                    "ENDS_WITH"
                ]
            }
        }
    }
]
CONTENT
}
```

### References



* https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_CostCategory.html

**Comment by sshvetsov** [comment]
Looks like CloudFormation support for Cost Categories ([AWS::CE::CostCategory](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ce-costcategory.html)) is about to go live. Providing documentation links in case they're helpful in crafting relevant Terraform resources.

**Comment by ewbankkit** [comment]
Closes via https://github.com/hashicorp/terraform-provider-aws/pull/24402.
