### ISSUE TITLE
Need SSM update-service-setting equivalent

### ISSUE THREAD

**Issue by ryan-dyer-sp** [hashicorp/terraform-provider-aws#12816]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There does not appear to be a way currently of performing the equivalent of an aws ssm update-service-setting CLI command.  This command is used for increasing the throughput of the parameters store (https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-throughput.html) and changing the default tier of the parameters (https://docs.aws.amazon.com/systems-manager/latest/userguide/ps-default-tier.html)

### New or Affected Resource(s)

* aws_ssm_service_setting ?

### Potential Terraform Configuration

```hcl
resource "aws_ssm_service_setting" {
  id = "<arn for setting>"
  value = "<value>"
}
```

### References

* https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-throughput.html
* https://docs.aws.amazon.com/systems-manager/latest/userguide/ps-default-tier.html

**Comment by fatbasstard** [comment]
This is here for a while. Any chance this will get some more TLC?

**Comment by breathingdust** [comment]
Hi all 👋 Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!
