### ISSUE TITLE
Feat: Add aws_db_subnet_group(s) data sources

### ISSUE THREAD

**Issue by quentin9696** [hashicorp/terraform-provider-aws#12822]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The AWS provider didn't have an aws_db_subnet_group data source. Sometime, we need to extract the subnet_id. 

### New or Affected Resource(s)

Datasource : 
* aws_db_subnet_group
* aws_db_subnet_groups

### References

 * N/A

**Comment by dmportella** [comment]
i would be interested in working on this issue
