### ISSUE TITLE
Iam-Role does not attach to EC2instance via code

### ISSUE THREAD

**Issue by sam-sog** [hashicorp/terraform-provider-aws#12837]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Affected Resources

* aws_EC2instance

### Terraform Configuration Files

In several pipelines run throught code terraform I noticed the Iam_role does not attach to ECinstance while there are no issues in making the resources. Permissions are set correct. 

No error is given.

### Debug Output

No error

 Expected Behavior
IAM-Role- attached to EC2Instance

### Actual Behavior

Resources where made but Iam-Role does not attach to Ec2Instance 

### Steps to Reproduce

1. `terraform apply`

### References

--->

* #0000

**Comment by pompbediener** [comment]
👍

**Comment by vaibhav1006** [comment]
👍

**Comment by DrFaust92** [comment]
hey @sam-sog , can you post an example of how you are attaching an iam role to an ec2 instance?
