### ISSUE TITLE
Service Level Documentation

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#12842]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently there are three forms of Terraform AWS Provider documentation for Terraform configuration:

* Resource Pages (https://terraform.io/docs/providers/aws/): Low level references for each Terraform Resource, including a small example, arguments, attributes, import, and customizable timeouts
* Repository Examples (https://github.com/terraform-providers/terraform-provider-aws/tree/examples): Arbitrary longer form/multiple resource Terraform configurations. Many of these are not linked in the Resource Pages.
* Learn Guides (https://learn.hashicorp.com): Step-by-step walkthroughs of certain functionality and features

Many practitioners (asked during various in person events or submitted pull requests) have wanted a middle ground level of documentation, somewhere between Resource Pages and Repository Examples, which shows them how to complete certain tasks that might involve multiple resources or AWS services. These examples tend to fall outside our normal definition of what should be on Resource Pages due to their length or implementation of Terraform configuration language features.

As an example: #6313

### Proposal

Create new "service" level documentation pages that can cover some cross-resource/service functionality, while linking out to repository examples where necessary. e.g.

In the Sidebar:

* Guides
* ACM (now clickable!)
  * ACM Data Sources
  * ACM Resources
* ACM PCA (now clickable!)
  * ACM PCA Data Sources
  * ACM PCA Resources

In the new ACM "service" page (random example), we might have sections like the following:

* Using Self-Signed Certificates via ACM
* Using ACM PCA Issued Certificates via ACM

Of course other services like S3 and ELBv2 with their numerous cross-service touch points are much more interesting than my simple ACM example here. 😄

### References

* #6313

**Comment by bflad** [comment]
Since this proposal was originally written, the Terraform Registry documentation has come along which currently does not support "service" level links (and likely will not). We may want to instead leverage the `examples` directory in a more organized fashion while linking to those examples from various resource pages, similar to the [AzureRM provider resources](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine_scale_set.html#example-usage).

**Comment by bflad** [comment]
Closing as we will not get to this anytime before long-term.
