### ISSUE TITLE
Document eventual consistency handling in Contributing Guide

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#12844]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Improve contributing guide by including guidance for best practice for handling eventual consistency.

#### Best practice

* Wrap problematic code with resource.Retry() with 1-2 minute timeout
* Ensure there's a isResourceTimeoutError(err) conditional afterwards

#### To be avoided

* resource.RetryableError should be very specific to the eventual consistency problem (no generic handling of all errors or all "invalid parameter" errors)
* Customizable timeouts are _generally_ not the solution 🙂

**Comment by bflad** [comment]
💥  https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/retries-and-waiters.md
