### ISSUE TITLE
Add access-properties to aws_workspaces_directory

### ISSUE THREAD

**Issue by heldersepu** [hashicorp/terraform-provider-aws#12866]
### Community Note
* Please vote on this issue by adding a +1 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
One of the options on Amazon Workspaces directory is the device types. 
![Screenshot from 2020-04-16 16-06-18](https://user-images.githubusercontent.com/545474/79501561-3ff92480-7ffc-11ea-8472-15f5d8f9d07e.png)

### New or Affected Resource(s)
* aws_workspaces_directory

### Potential Terraform Configuration
```terraform
resource "aws_workspaces_directory" "example" {
  directory_id = aws_directory_service_directory.example.id

  access_properties {
    device_type_windows = true
    device_type_osx = true
    device_type_web = true
    device_type_ios = true
    device_type_android = true
    device_type_chromeos = true
    device_type_zeroclien = true
  }
}
```

### References
* https://docs.aws.amazon.com/cli/latest/reference/workspaces/modify-workspace-access-properties.html

**Comment by lmorfitt** [comment]
Until this is merged it is possible to set the settings with the following

```

data "aws_region" "current" {}

resource "null_resource" "modify-workspace-access-properties" {
  provisioner "local-exec" {

    # Invoke the AWS CLI passing through the required JSON body to setup the client actions
    # https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/workspaces.html#WorkSpaces.Client.modify_workspace_access_properties
    # Tested with AWS Cli version `aws-cli/2.0.40 Python/3.7.4 Darwin/19.6.0 exe/x86_64`
    command = <<-EOT
      aws workspaces modify-workspace-access-properties \
        --region=${data.aws_region.current.name} \
        --resource-id=${aws_workspaces_directory.this.id} \
        --workspace-access-properties='
         {
          "DeviceTypeWindows": "ALLOW",
          "DeviceTypeOsx": "ALLOW",
          "DeviceTypeWeb": "ALLOW",
          "DeviceTypeIos": "ALLOW",
          "DeviceTypeAndroid": "ALLOW",
          "DeviceTypeChromeOs": "ALLOW",
          "DeviceTypeZeroClient": "ALLOW"
        }'
    EOT
  }
}
