### ISSUE TITLE
aws_security_group thinks there are changes with every plan/apply

### ISSUE THREAD

**Issue by mrubinwch** [hashicorp/terraform-provider-aws#12883]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.24
+ provider.archive v1.3.0
+ provider.aws v2.58.0
+ provider.template v2.1.2
```

### Affected Resource(s)

* aws_security_group

### Terraform Configuration Files

```hcl
resource "aws_security_group" "example" {
  name        = "example"
  description = "Example Security Group"
  vpc_id      = aws_vpc.vpc.id

  lifecycle {
    create_before_destroy = true
  }

  tags = merge(
    var.tags,
    {
      "Name" = format("%s-example", var.env_name)
    },
  )

  # A

  ingress {
    description = "A"
    from_port   = 443
    to_port     = 443
    protocol    = "TCP"
    cidr_blocks = var.vendor_A_IPs
  }

  # B

  ingress {
    description = "B"
    from_port   = 443
    to_port     = 443
    protocol    = "TCP"
    cidr_blocks = var.vendor_B_IPs
  }

  # C, D, ...

  # Allow outbound traffic to the service instances
  # Responses to inbound traffic are allowed to flow out regardless of outbound security group rules
  egress {
    from_port       = 80
    to_port         = 80
    protocol        = "TCP"
    security_groups = [aws_security_group.example-service.id]
  }
}
```

### Expected Behavior

Once the above configuration is applied, if I run apply again, Terraform should indicate that no further changes are necessary.

### Actual Behavior

Every single time I ran plan or apply, Terraform thinks there are changes to this SG.

### Notes

I tried combining the ingress rules into a single one like so (though it means I'm losing the descriptions):

```hcl
  ingress {
    from_port   = 443
    to_port     = 443
    protocol    = "TCP"
    cidr_blocks = concat(var.vendor_A_IPs, var.vendor_B_IPs, ...)
  }
```

This did not help.

### Example Output

```
      ~ ingress                = [
          - {
              - cidr_blocks      = [
                  - "107.20.74.239/32",
                  - "18.208.7.136/32",
                  - "18.205.218.13/32",
                  - "54.227.71.35/32",
                  - "52.88.148.121/32",
                  - "34.233.139.122/32",
                  - "52.86.221.16/32",
                  - "34.238.107.121/32",
                ]
              - description      = "A"
              - from_port        = 443
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 443
            },
          + {
              + cidr_blocks      = [
                  + "52.88.148.121/32",
                  + "107.20.74.239/32",
                  + "18.205.218.13/32",
                  + "34.233.139.122/32",
                  + "34.238.107.121/32",
                  + "52.86.221.16/32",
                  + "54.227.71.35/32",
                  + "18.208.7.136/32",
                  + "107.20.74.239/32",
                ]
              + description      = "A"
              + from_port        = 443
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 443
            },
```

**Comment by mrubinwch** [comment]
I believe I've found the culprit here. It's not shown in the above example, but my list of IPs had duplicate IPs. Terraform would show changes on every apply and try to apply them (I don't know if it actually tried to apply the duplicates - they were not in the actual AWS SG). Once I manually removed the duplicate IPs from my configuration, all is well.

Ideally, Terraform would show a warning or perhaps even dedup the IPs?

**Comment by justinretzolk** [comment]
Thank you for filing this and for following up with a solution! Given that this seems to have been configuration related, we're going to go ahead and close this issue out. If you feel we've done this in error, please open a new issue with any relevant updates.
