### ISSUE TITLE
aws_kms_alias API ValidationException

### ISSUE THREAD

**Issue by yves-vogl** [hashicorp/terraform-provider-aws#12891]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24

### Affected Resource(s)

provider.aws v2.58.0

### Terraform Configuration Files

```hcl
resource "aws_kms_alias" "example" {
  name          = "alias/Service.Test"
  target_key_id = aws_kms_key.a.key_id
}


# Error: "name" must begin with 'alias/' and be comprised of only [a-zA-Z0-9:/_-]


resource "aws_kms_alias" "another_ example" {
  name          = "alias/Service:Test"
  target_key_id = aws_kms.another.key_id
}

# Error: ValidationException: alias/Service:Test contains invalid characters for an alias status code: 400
```

### Expected Behavior

Terraform validation should be congruent to AWS API validation.

### Actual Behavior

The validation seems to allow characters which are rejected by API.

_I'm creating this issue mainly as a reminder for me to fix this and submit a PR :-)_

**Comment by drexler** [comment]
The regex should not contain a `:` according to the  [AWS GO SDK documentation](https://docs.aws.amazon.com/sdk-for-go/api/service/kms/).

**Comment by ArchiFleKs** [comment]
I think the PR checks against `alias/aws` and not `alias/aws/` I have a KMS key : 

```
│ Error: "name" cannot begin with reserved AWS CMK prefix 'alias/aws'
│ 
│   with aws_kms_alias.aws-ebs-csi-driver[0],
│   on aws-ebs-csi-driver.tf line 212, in resource "aws_kms_alias" "aws-ebs-csi-driver":
│  212:   name          = "alias/aws-ebs-csi-driver-${local.aws-ebs-csi-driver.override_kms_alias != null ? local.aws-ebs-csi-driver.override_kms_alias : var.cluster-name}"
```

Which failed. Is the AWS API enforce `alias/aws/*` or `alias/aws*`
