### ISSUE TITLE
RDS  - error deleting, instance not found

### ISSUE THREAD

**Issue by michalschott** [hashicorp/terraform-provider-aws#12900]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.11.14 / probably not terraform related itself

### Affected Resource(s)

* aws_db_instance

### Terraform Configuration Files

```hcl
resource "aws_db_instance" "postgres_nsg" {
...
snapshot_identifier = "${lookup(var.config_nsg, "snapshot_identifier", "")}"
deletion_protection = true
...
  lifecycle {
    create_before_destroy = true
  }
}
```

### Expected Behavior

If instance does not exist, it should be removed from state. It looks like
```
* ErrCodeDBInstanceNotFoundFault "DBInstanceNotFound"
DBInstanceIdentifier doesn't refer to an existing DB instance.
```
is not handled at all, [ref](https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#RDS.DeleteDBInstance)

### Actual Behavior
```
	* aws_db_instance.postgres (destroy): 2 errors occurred:
	* aws_db_instance.postgres (deposed #1): 1 error occurred:
	* aws_db_instance.postgres (deposed #1): error deleting Database Instance "XXX": DBInstanceNotFound: DBInstance XXX not found.
	status code: 404, request id: 90c00e13-5a4a-40f6-a52f-d512c7e07035
```

### Steps to Reproduce

1. apply RDS_instance with snapshot identifier 
2. change source snapshot, deletion of old instance should fail
3. remove old instance using GUI/aws cli
4. run `terraform apply`, resource will be still as marked as deposed and TF will keep erroring.

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 3.15.0 of the Terraform AWS Provider, later this week. 👍
