### ISSUE TITLE
Error updating S3 Bucket tags: error setting resource tags: NoSuchBucket: The specified bucket does not exist

### ISSUE THREAD

**Issue by bpiper** [hashicorp/terraform-provider-aws#12907]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.10.8

### Affected Resource(s)

* aws_s3_bucket

### Terraform Configuration Files

```
resource "aws_s3_bucket" "mybucket" {
  bucket = "mybucket"
  force_destroy = true

  lifecycle {
    prevent_destroy = false
  }

  tags = {
    Name = "mybucket"
    Role = "whatever"
  }
}
```

### Expected Behavior

New S3 bucket created and tagged successfully.

### Actual Behavior

Bucket was created from Terraform's perspective, but tagging failed with following error due to eventual consistency.

`aws_s3_bucket.mybucket: error updating S3 Bucket (mybucket) tags: error setting resource tags (mybucket): NoSuchBucket: The specified bucket does not exist`

### Steps to Reproduce

Bucket resource must not exist yet.  Run `terraform apply` (see example resource definition above).  May need to destroy and apply a number of times before hitting the error (which by its nature doesn't always occur).  I've been hitting this error quite a lot recently.

### References

* Very similar to #10068 - which pertained to retrieving tags rather than updating them

**Comment by ewbankkit** [comment]
Similar:
* https://github.com/terraform-providers/terraform-provider-aws/issues/12652

**Comment by dude0001** [comment]
Has anyone found a workaround or root cause for this?

**Comment by nomeelnoj** [comment]
We just hit this today as well with `terraform 0.12.24`.  Any updates/workarounds at this time?

**Comment by boiaanstoianov** [comment]
Same error on v0.12.26 any updates on this issue ?
