### ISSUE TITLE
resource/aws_iam_user: force_destroy Does Not Detach Policies

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#12903]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.24
+ provider.aws v2.57.0
```

### Affected Resource(s)

* aws_iam_user

### Terraform Configuration Files

```hcl
resource "aws_iam_user" "example" {
  force_destroy = true
  name          = "example"
}
```

### Expected Behavior

With the `force_destroy = true` argument applied prior to deletion, any externally attached IAM Policies are detached and IAM User removal is successful.

### Actual Behavior

```
Error: Error deleting IAM User example: DeleteConflict: Cannot delete entity, must detach all policies first.
```

### Steps to Reproduce

1. `terraform apply`
1. Manually attach IAM Policy to IAM User
1. `terraform destroy`

### References

* Similar fix for test sweepers: https://github.com/terraform-providers/terraform-provider-aws/pull/7381

**Comment by kimayap03** [comment]
Do you have an ETA for this bug fix?

**Comment by ellisonc** [comment]
The same problem exists when Access Keys exist on the iam user.  The docs state when force_destroy is true any access keys would be deleted as well, but I'm seeing a DeleteConflict error.

**Comment by s-nakka** [comment]
Still seeing the same issue with TF version 1.3.6.

**Comment by leandromartinezJC** [comment]
Hello folks, any update on this? I'm facing this issue with Terraform v1.4.2
