### ISSUE TITLE
Cognito Identity Pool resource does not support AllowClassicFlow boolean

### ISSUE THREAD

**Issue by if-jeremy** [hashicorp/terraform-provider-aws#12926]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The aws_cognito_identity_pool resource type has no ability to set the "AllowClassicFlow" attribute

### New or Affected Resource(s)

aws_cognito_identity_pool

### Potential Terraform Configuration

```hcl
resource "aws_cognito_identity_pool" "example-pool" {
    identity_pool_name = "ExamplePool"
    allow_classic_flow = {true|false}
    ...
}
```

### References

* https://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_CreateIdentityPool.html

**Comment by akshaykrjain** [comment]
its been almost 1 year for this issue and still no progress.
