### ISSUE TITLE
awsproviderlint: New Check: Prefer %w verb for *awserr.Error in returning errors with context

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#12991]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Go 1.13 introduced a new error formatting verb, %w, which allows the original error to be wrapped and checked by type in consumers, rather than just checking by value.

Previously, it was not (easily) possible to have an AWS Go SDK helper function return a contextual message along the original error, e.g. this would not work
```
func doSomethingCool(conn *ec2.EC2) error {
  input := &ec2.DescribeSecurityGroupsInput{}
  _, err := conn.DescribeSecurityGroups(input)
  
  if err != nil {
    return fmt.Errorf("error describing EC2 Security Groups: %s", err)
  }

  return nil
}

// calling reference

err := doSomethingCool(conn)

// this would not work previously and the Go build chain will not raise any issues (error is checked by value)
if isAWSErr(err, "Code", "Message") {
  // error handling
}
```
Now with the %w verb in the AWS Go SDK calling function and the now updated isAWSErr() helper function, the error checking can work as expected.

### Flagged Code
```
fmt.Errorf("oh no: %s", err)
```
### Passing Code
```
fmt.Errorf("oh no: %w", err)
```
### References

- https://blog.golang.org/go1.13-errors

**Comment by ewbankkit** [comment]
This seems to be the same guidance as https://github.com/terraform-providers/terraform-provider-aws/issues/12987?

**Comment by ewbankkit** [comment]
We should be able to use the `golangci-lint` [`errorlint`](https://golangci-lint.run/usage/linters/#errorlint) linter for this.

**Comment by ewbankkit** [comment]
Superseded by https://github.com/hashicorp/terraform-provider-aws/issues/15891.
