### ISSUE TITLE
Ignore/Fix and Enable awsproviderlint AWSAT003: Regions should not be hardcoded, use aws_region and aws_availability_zones data sources instead

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#12995]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To ensure test configurations are region and partition agnostic, any hardcoded AZ identifiers ([a-z]{2}(-[a-z]+)+-[1-9][0-9]*(-[a-z]+-[1-9][0-9]*)?[a-z]) should be replaced with the aws_availability_zones data source.

To ensure test configurations are region and partition agnostic, any hardcoded Region identifiers ([a-z]{2}(-[a-z]+)+-[1-9][0-9]*) should be replaced with the `aws_region` data source.

#### Flagged Code

In test configuration:

```
us-west-2
```

```
us-west-2a
```

#### Passing Code

In test configuration:

```
data "aws_region" "current" {}
```

```
data "aws_availability_zones" "available" {
  # ... configuration ...
}
```

## Definition of Done

* `AWSAT003` check enabled in `GNUmakefile`
* CI testing passes

**Comment by YakDriver** [comment]
This was added as [AWSAT003](https://github.com/terraform-providers/terraform-provider-aws/tree/master/awsproviderlint/passes/AWSAT003). This is the central management issue.

Fixes needed:
- [ ] cloudfront_distribution_configuration_structure_test
- [ ] config_test
- [ ] data_source_aws_acmpca_certificate_authority_test
- [ ] data_source_aws_arn_test
- [ ] data_source_aws_cloudtrail_service_account
- [ ] data_source_aws_cur_report_definition_test
- [ ] data_source_aws_db_instance_test
- [ ] data_source_aws_ebs_snapshot_ids_test
- [ ] data_source_aws_ec2_transit_gateway_vpc_attachment_test
- [ ] data_source_aws_eip
- [ ] data_source_aws_eip_test
- [ ] data_source_aws_elastic_beanstalk_hosted_zone
- [ ] data_source_aws_elastic_beanstalk_hosted_zone_test
- [ ] data_source_aws_elb_hosted_zone_id
- [ ] data_source_aws_elb_hosted_zone_id_test
- [ ] data_source_aws_elb_service_account
- [ ] data_source_aws_ip_ranges_test
- [ ] data_source_aws_nat_gateway_test
- [ ] data_source_aws_prefix_list_test
- [ ] data_source_aws_pricing_product_test
- [ ] data_source_aws_rds_cluster_test
- [ ] data_source_aws_redshift_cluster_test
- [ ] data_source_aws_redshift_service_account
- [ ] data_source_aws_region_test
- [ ] data_source_aws_route_test
- [ ] data_source_aws_secretsmanager_secret_test
- [ ] data_source_aws_subnet_ids_test
- [ ] data_source_aws_transfer_server_test
- [ ] datasync_test
- [ ] hosted_zones
- [ ] hosted_zones_test
- [ ] provider
- [ ] provider_test
- [ ] resource_aws_alb_target_group_test
- [ ] resource_aws_api_gateway_domain_name_test
- [ ] resource_aws_app_cookie_stickiness_policy_test
- [ ] resource_aws_autoscaling_group_test
- [ ] resource_aws_budgets_budget_test
- [ ] resource_aws_cloudformation_stack_test
- [ ] resource_aws_cloudfront_distribution_test
- [ ] resource_aws_cloudwatch_event_target_test
- [ ] resource_aws_codebuild_project_test
- [ ] resource_aws_codedeploy_deployment_group_test
- [ ] resource_aws_codepipeline_test
- [ ] resource_aws_cognito_identity_pool_test
- [ ] resource_aws_cognito_user_group_test
- [ ] resource_aws_cognito_user_pool_domain_test
- [ ] resource_aws_config_aggregate_authorization
- [ ] resource_aws_config_aggregate_authorization_test
- [ ] resource_aws_config_configuration_aggregator_test
- [ ] resource_aws_cur_report_definition_test
- [ ] resource_aws_datasync_location_smb_test
- [ ] resource_aws_db_instance_test
- [ ] resource_aws_db_security_group_test
- [ ] resource_aws_default_security_group_test
- [ ] resource_aws_default_subnet_test
- [ ] resource_aws_default_vpc_dhcp_options
- [ ] resource_aws_default_vpc_dhcp_options_test
- [ ] resource_aws_devicefarm_project
- [ ] resource_aws_dms_endpoint_test
- [ ] resource_aws_dms_replication_subnet_group_test
- [ ] resource_aws_dms_replication_task_test
- [ ] resource_aws_docdb_cluster_instance_test
- [ ] resource_aws_docdb_cluster_test
- [ ] resource_aws_docdb_subnet_group_test
- [ ] resource_aws_dynamodb_global_table_test
- [ ] resource_aws_ec2_availability_zone_group_test
- [ ] resource_aws_ec2_client_vpn_authorization_rule_test
- [ ] resource_aws_ec2_client_vpn_network_association_test
- [ ] resource_aws_ec2_client_vpn_route_test
- [ ] resource_aws_ec2_transit_gateway_route_test
- [ ] resource_aws_ec2_transit_gateway_vpc_attachment_accepter_test
- [ ] resource_aws_ec2_transit_gateway_vpc_attachment_test
- [ ] resource_aws_ecs_task_definition_test
- [ ] resource_aws_efs_file_system_test
- [ ] resource_aws_eip
- [ ] resource_aws_eip_association_test
- [ ] resource_aws_eip_test
- [ ] resource_aws_eks_fargate_profile_test
- [ ] resource_aws_elasticache_cluster_test
- [ ] resource_aws_elasticache_replication_group_test
- [ ] resource_aws_elasticache_security_group_test
- [ ] resource_aws_elasticache_subnet_group_test
- [ ] resource_aws_emr_security_configuration_test
- [ ] resource_aws_fms_admin_account_test
- [ ] resource_aws_gamelift_test
- [ ] resource_aws_iam_access_key_test
- [ ] resource_aws_iam_user_login_profile_test
- [ ] resource_aws_instance_test
- [ ] resource_aws_iot_topic_rule_test
- [ ] resource_aws_kinesis_firehose_delivery_stream_test
- [ ] resource_aws_kinesis_stream_migrate_test
- [ ] resource_aws_lambda_permission_test
- [ ] resource_aws_launch_configuration_test
- [ ] resource_aws_launch_template_test
- [ ] resource_aws_lb_cookie_stickiness_policy_test
- [ ] resource_aws_lb_listener_rule_test
- [ ] resource_aws_lb_target_group_test
- [ ] resource_aws_lb_test
- [ ] resource_aws_lightsail_domain_test
- [ ] resource_aws_load_balancer_listener_policy_test
- [ ] resource_aws_load_balancer_policy_test
- [ ] resource_aws_neptune_cluster_instance_test
- [ ] resource_aws_neptune_subnet_group_test
- [ ] resource_aws_opsworks_instance_test
- [ ] resource_aws_opsworks_stack
- [ ] resource_aws_opsworks_stack_test
- [ ] resource_aws_organizations_policy_test
- [ ] resource_aws_proxy_protocol_policy_test
- [ ] resource_aws_rds_cluster_endpoint_test
- [ ] resource_aws_rds_cluster_instance_test
- [ ] resource_aws_redshift_cluster_test
- [ ] resource_aws_redshift_security_group_test
- [ ] resource_aws_redshift_subnet_group_test
- [ ] resource_aws_route_table_test
- [ ] resource_aws_route_test
- [ ] resource_aws_route53_health_check_test
- [ ] resource_aws_route53_query_log_test
- [ ] resource_aws_route53_record_test
- [ ] resource_aws_s3_bucket
- [ ] resource_aws_s3_bucket_test
- [ ] resource_aws_sagemaker_endpoint_configuration_test
- [ ] resource_aws_sagemaker_endpoint_test
- [ ] resource_aws_sagemaker_model_test
- [ ] resource_aws_security_group_rule_test
- [ ] resource_aws_security_group_test
- [ ] resource_aws_shield_protection_test
- [ ] resource_aws_sns_platform_application_test
- [ ] resource_aws_sns_topic_test
- [ ] resource_aws_spot_fleet_request_test
- [ ] resource_aws_sqs_queue_test
- [ ] resource_aws_storagegateway_cache_test
- [ ] resource_aws_storagegateway_cached_iscsi_volume_test
- [ ] resource_aws_storagegateway_upload_buffer_test
- [ ] resource_aws_storagegateway_working_storage_test
- [ ] resource_aws_transfer_server_test
- [ ] resource_aws_vpc_dhcp_options_test
- [ ] resource_aws_vpc_endpoint_connection_notification_test
- [ ] resource_aws_vpc_endpoint_service_allowed_principal_test
- [ ] resource_aws_vpn_gateway_test
- [ ] resource_aws_waf_web_acl_test
- [ ] resource_aws_workspaces_directory_test
- [ ] structure_test
- [ ] validators_test

**Comment by bflad** [comment]
Getting closer! Here's the current list of remaining files:

`aws/config_test.go`
`aws/data_source_aws_arn_test.go`
`aws/data_source_aws_cloudtrail_service_account.go`
`aws/data_source_aws_db_instance_test.go`
`aws/data_source_aws_eip.go`
`aws/data_source_aws_eip_test.go`
`aws/data_source_aws_elastic_beanstalk_hosted_zone.go`
`aws/data_source_aws_elastic_beanstalk_hosted_zone_test.go`
`aws/data_source_aws_elb_hosted_zone_id.go`
`aws/data_source_aws_elb_hosted_zone_id_test.go`
`aws/data_source_aws_elb_service_account.go`
`aws/data_source_aws_ip_ranges_test.go`
`aws/data_source_aws_prefix_list_test.go`
`aws/data_source_aws_pricing_product_test.go`
`aws/data_source_aws_redshift_service_account.go`
`aws/data_source_aws_region_test.go`
`aws/data_source_aws_transfer_server_test.go`
`aws/datasync_test.go`
`aws/hosted_zones.go`
`aws/hosted_zones_test.go`
`aws/provider.go`
`aws/provider_test.go`
`aws/resource_aws_api_gateway_domain_name_test.go`
`aws/resource_aws_budgets_budget_test.go`
`aws/resource_aws_cloudfront_distribution_test.go`
`aws/resource_aws_codebuild_project_test.go`
`aws/resource_aws_cognito_user_group_test.go`
`aws/resource_aws_cognito_user_pool_domain_test.go`
`aws/resource_aws_config_aggregate_authorization.go`
`aws/resource_aws_config_aggregate_authorization_test.go`
`aws/resource_aws_datasync_location_smb_test.go`
`aws/resource_aws_db_instance_test.go`
`aws/resource_aws_db_security_group_test.go`
`aws/resource_aws_default_security_group_test.go`
`aws/resource_aws_default_vpc_dhcp_options.go`
`aws/resource_aws_default_vpc_dhcp_options_test.go`
`aws/resource_aws_devicefarm_project.go`
`aws/resource_aws_dynamodb_global_table_test.go`
`aws/resource_aws_ec2_availability_zone_group_test.go`
`aws/resource_aws_ec2_client_vpn_authorization_rule_test.go`
`aws/resource_aws_ec2_client_vpn_network_association_test.go`
`aws/resource_aws_ec2_client_vpn_route_test.go`
`aws/resource_aws_ec2_transit_gateway_route_test.go`
`aws/resource_aws_ec2_transit_gateway_vpc_attachment_accepter_test.go`
`aws/resource_aws_ec2_transit_gateway_vpc_attachment_test.go`
`aws/resource_aws_efs_file_system_test.go`
`aws/resource_aws_eip.go`
`aws/resource_aws_eip_association_test.go`
`aws/resource_aws_eip_test.go`
`aws/resource_aws_eks_fargate_profile_test.go`
`aws/resource_aws_elasticache_cluster_test.go`
`aws/resource_aws_elasticache_security_group_test.go`
`aws/resource_aws_fms_admin_account_test.go`
`aws/resource_aws_gamelift_test.go`
`aws/resource_aws_guardduty_filter_test.go`
`aws/resource_aws_iam_access_key_test.go`
`aws/resource_aws_instance_test.go`
`aws/resource_aws_lambda_permission_test.go`
`aws/resource_aws_lightsail_domain_test.go`
`aws/resource_aws_opsworks_instance_test.go`
`aws/resource_aws_opsworks_stack.go`
`aws/resource_aws_organizations_policy_test.go`
`aws/resource_aws_redshift_security_group_test.go`
`aws/resource_aws_route53_health_check_test.go`
`aws/resource_aws_route53_query_log_test.go`
`aws/resource_aws_route53_record_test.go`
`aws/resource_aws_s3_bucket.go`
`aws/resource_aws_s3_bucket_test.go`
`aws/resource_aws_sagemaker_endpoint_configuration_test.go`
`aws/resource_aws_sagemaker_endpoint_test.go`
`aws/resource_aws_sagemaker_model_test.go`
`aws/resource_aws_security_group_rule_test.go`
`aws/resource_aws_security_group_test.go`
`aws/resource_aws_transfer_server_test.go`
`aws/resource_aws_vpc_dhcp_options_test.go`
`aws/resource_aws_vpn_gateway_test.go`
`aws/resource_aws_waf_web_acl_test.go`
`aws/resource_aws_workspaces_directory_test.go`
`aws/structure_test.go`
`aws/validators_test.go`

**Comment by YakDriver** [comment]
# Phase 2 !!

- [ ] config_test.go
- [ ] data_source_aws_arn_test.go
- [ ] data_source_aws_cloudtrail_service_account.go
- [ ] data_source_aws_eip.go
- [ ] data_source_aws_elastic_beanstalk_hosted_zone_test.go
- [ ] data_source_aws_elastic_beanstalk_hosted_zone.go
- [ ] data_source_aws_elb_hosted_zone_id_test.go
- [ ] data_source_aws_elb_hosted_zone_id.go
- [ ] data_source_aws_elb_service_account.go
- [ ] data_source_aws_ip_ranges_test.go
- [ ] data_source_aws_prefix_list_test.go
- [ ] data_source_aws_redshift_service_account.go
- [ ] data_source_aws_region_test.go
- [ ] data_source_aws_transfer_server_test.go
- [ ] datasync_test.go
- [ ] hosted_zones_test.go
- [ ] hosted_zones.go
- [ ] provider_test.go
- [ ] provider.go
- [ ] resource_aws_budgets_budget_test.go
- [ ] resource_aws_codebuild_project_test.go
- [ ] resource_aws_cognito_user_group_test.go
- [ ] resource_aws_config_aggregate_authorization_test.go
- [ ] resource_aws_config_aggregate_authorization.go
- [ ] resource_aws_default_vpc_dhcp_options_test.go
- [ ] resource_aws_default_vpc_dhcp_options.go
- [ ] resource_aws_devicefarm_project.go
- [ ] resource_aws_dynamodb_global_table_test.go
- [ ] resource_aws_ec2_availability_zone_group_test.go
- [ ] resource_aws_ec2_client_vpn_authorization_rule_test.go
- [ ] resource_aws_ec2_client_vpn_network_association_test.go
- [ ] resource_aws_ec2_client_vpn_route_test.go
- [ ] resource_aws_ec2_transit_gateway_route_test.go
- [ ] resource_aws_ec2_transit_gateway_vpc_attachment_accepter_test.go
- [ ] resource_aws_ec2_transit_gateway_vpc_attachment_test.go
- [ ] resource_aws_efs_file_system_test.go
- [ ] resource_aws_eip_test.go
- [ ] resource_aws_eip.go
- [ ] resource_aws_eks_fargate_profile_test.go
- [ ] resource_aws_gamelift_test.go
- [ ] resource_aws_guardduty_filter_test.go
- [ ] resource_aws_iam_access_key_test.go
- [ ] resource_aws_instance_test.go
- [ ] resource_aws_lightsail_domain_test.go
- [ ] resource_aws_opsworks_instance_test.go
- [ ] resource_aws_opsworks_stack.go
- [ ] resource_aws_organizations_policy_test.go
- [ ] resource_aws_route53_health_check_test.go
- [ ] resource_aws_route53_record_test.go
- [ ] resource_aws_s3_bucket_test.go
- [ ] resource_aws_s3_bucket.go
- [ ] resource_aws_sagemaker_endpoint_test.go
- [ ] resource_aws_security_group_rule_test.go
- [ ] resource_aws_transfer_server_test.go
- [ ] resource_aws_vpc_dhcp_options_test.go
- [ ] resource_aws_vpn_gateway_test.go
- [ ] resource_aws_workspaces_directory_test.go
- [ ] structure_test.go
- [ ] validators_test.go
