### ISSUE TITLE
AWS Transfer for FTP and FTPS

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#13016]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Transfer now supports FTP and FTPS protocols.

### New or Affected Resource(s)

* [`aws_transfer_server`](https://www.terraform.io/docs/providers/aws/r/transfer_server.html)

### Potential Terraform Configuration

```hcl
resource "aws_transfer_server" "example" {
  protocols = ["FTPS"]
  certificate = "..."
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/04/introducing-aws-transfer-family/).
[Blog post](https://aws.amazon.com/blogs/aws/new-aws-transfer-for-ftp-and-ftps-in-addition-to-existing-sftp/).

Requires [AWS SDK v1.30.13](https://github.com/aws/aws-sdk-go/releases/tag/v1.30.13):
* https://github.com/terraform-providers/terraform-provider-aws/pull/12970

**Comment by drexler** [comment]
@ewbankkit i'll like to tackle this once the dependency is merged.
