### ISSUE TITLE
aws_elastic_beanstalk_environment BreachDuration changes not applying

### ISSUE THREAD

**Issue by mrubinwch** [hashicorp/terraform-provider-aws#13068]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24
+ provider.archive v1.3.0
+ provider.aws v2.58.0
+ provider.template v2.1.2

### Affected Resource(s)

* aws_elastic_beanstalk_environment

### Terraform Configuration Files

```hcl
  setting {
    namespace = "aws:autoscaling:trigger"
    name      = "BreachDuration"
    value     = var.breachDuration
  }
```
### Actual Behavior

No matter how many times I apply, I see the following:

```
      + setting {
          + name      = "BreachDuration"
          + namespace = "aws:autoscaling:trigger"
          + value     = "3"
        }
      - setting {
          - name      = "BreachDuration" -> null
          - namespace = "aws:autoscaling:trigger" -> null
          - value     = "5" -> null
        }
```

Looking at the AWS web console, BreachDuration is set at 5. It doesn't appear to be actually applying from Terraform (though Terraform detects the difference in state and keeps trying to apply it).

**Comment by labmonkey42** [comment]
I have a similar issue with the resource refresh having a value of "1" and my setting defining it as "5", so every plan sees the setting as changed.

**Comment by justinretzolk** [comment]
Hey @mrubinwch 👋 Thank you for taking the time to report this. Since there's been quite a few releases of the AWS Provider between when you initially filed it and now, can you confirm whether you're still experiencing this behavior?
