### ISSUE TITLE
[BUG] aws_route with conditional target to use nat_gateway_id or transit_gateway_id

### ISSUE THREAD

**Issue by Bobonium** [hashicorp/terraform-provider-aws#13079]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.12.24

### Affected Resource(s)

* aws_route

### Terraform Configuration Files

```hcl
resource "aws_route" "route" {
  count = length(var.private_subnets)

  route_table_id         = element(aws_route_table.private_rts.*.id, count.index)
  destination_cidr_block = "0.0.0.0/0"
  nat_gateway_id         = var.enable_nat_gateway ? element(aws_nat_gateway.nat_gateways.*.id, count.index) : null
  transit_gateway_id     = var.enable_nat_gateway ? null : var.tgw_id
}

```
### Expected Behavior

if enable_nat_gateway is true it should create the route for destination 0.0.0.0/0 with the nat_gateway_id. If it is false it should use the supplied tgw_id instead.

### Actual Behavior

The plan output correctly shows the intended changes.
Running apply will fail because of 
```
Error: Error: more than 1 target specified. Only 1 of gateway_id, egress_only_gateway_id, nat_gateway_id, instance_id, network_interface_id or vpc_peering_connection_id is
```
In our case we switched an existing system from enable_nat_gateways = true, to enable_nat_gateways = false. Plan output was correct, but above error happened. We were able to solve the problem by manually changing the route in the UI, the next terraform plan was then empty, because of the refresh.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

none

### References

none

**Comment by ewbankkit** [comment]
Similar:
* https://github.com/terraform-providers/terraform-provider-aws/issues/684
* https://github.com/terraform-providers/terraform-provider-aws/issues/12631

**Comment by ewbankkit** [comment]
Verified that the same problem occurs with Terraform 0.11 (and `""` instead of `null` for the missing gateway ID).
