### ISSUE TITLE
aws_network_acl_rule incorrectly destroy/create nacl rule

### ISSUE THREAD

**Issue by haidangwa** [hashicorp/terraform-provider-aws#13086]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.12.24
+ provider.aws v2.59.0
+ provider.null v2.1.2
```

### Affected Resource(s)

* aws_network_acl_rule

### Expected Behavior

There should be no changes to our infrastructure state.

### Actual Behavior

`terraform plan` reports the following:

```
Terraform will perform the following actions:

  # module.network.module.nacl.aws_network_acl_rule.icmp_mgmt_ping[0] must be replaced
-/+ resource "aws_network_acl_rule" "icmp_mgmt_ping" {
        cidr_block     = "0.0.0.0/0"
        egress         = false
      ~ icmp_code      = "-1" -> "0" # forces replacement
        icmp_type      = "8"
      ~ id             = "nacl-3344144634" -> (known after apply)
        network_acl_id = "acl-07ee406bd05f6bd89"
        protocol       = "icmp"
        rule_action    = "allow"
        rule_number    = 80
    }

  # module.network.module.nacl.aws_network_acl_rule.icmp_mgmt_pingreply[0] must be replaced
-/+ resource "aws_network_acl_rule" "icmp_mgmt_pingreply" {
        cidr_block     = "0.0.0.0/0"
        egress         = false
      ~ icmp_code      = "-1" -> "0" # forces replacement
        icmp_type      = "0"
      ~ id             = "nacl-449134975" -> (known after apply)
        network_acl_id = "acl-07ee406bd05f6bd89"
        protocol       = "icmp"
        rule_action    = "allow"
        rule_number    = 81
    }

Plan: 2 to add, 0 to change, 2 to destroy.
```
* IMHO, this is a destructive bug and potentially causing outages while terraform must destroy the old NACL to "create" the new one, which in fact, there is no change required.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

We previously used the aws provider v2.58.0 and `terraform plan` showed 0 changes. We expected 0 changes.

### References

*  I believe this problem was created by an enhancement done in v2.59.0 in this [pull request](https://github.com/terraform-providers/terraform-provider-aws/pull/12921). The comment made [here](https://github.com/terraform-providers/terraform-provider-aws/pull/12921#pullrequestreview-397856511) is my concern.

**Comment by justinretzolk** [comment]
Hey @haidangwa 👋 Thank you very much for taking the time to report this. Given that there's been a few AWS Provider releases since you initially filed it, can you confirm if you're still seeing this behavior?

**Comment by ewbankkit** [comment]
With the latest version of the provider, this configuration

```hcl
resource "aws_vpc" "test" {
  cidr_block = "10.1.0.0/16"

  tags = {
    Name = "ewbankkit-test"
  }
}

resource "aws_network_acl" "test" {
  vpc_id = aws_vpc.test.id

  tags = {
    Name = "ewbankkit-test"
  }
}

resource "aws_network_acl_rule" "test" {
  network_acl_id = aws_network_acl.test.id
  rule_number    = 200
  egress         = false
  protocol       = "icmp"
  rule_action    = "allow"
  cidr_block     = "0.0.0.0/0"
  icmp_code      = -1
  icmp_type      = 0
}
```

Shows no diff on `terraform plan`.
