### ISSUE TITLE
Support for Amazon Athena Federated Query

### ISSUE THREAD

**Issue by ketoor** [hashicorp/terraform-provider-aws#13085]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
AWS launched Athena Federated Query (currently in preview state). It allows to query against different datasources (e.g. DynamoDB table).

### New Resource
* aws_athena_datasource_catalog

### Potential Terraform Configuration
```hcl
resource "aws_athena_datasource_catalog" "dynamodb_catalog" {
  name            = "dynamodb_catalog"
  lambda_function = aws_lambda_function.foo_lambda.function_name
  description     = "Optional"
}
```

### References

* https://docs.aws.amazon.com/athena/latest/ug/connect-to-a-data-source.html
* https://aws.amazon.com/blogs/big-data/query-any-data-source-with-amazon-athenas-new-federated-query/
* https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-athena-adds-support-for-running-sql-queries-across-relational-non-relational-object-custom-data-sources/

**Comment by tomelliff** [comment]
The normal thing with AWS resources is to match the shape of the API as much as possible rather than trying to abstract things cleverly because AWS does regularly change things in a way that could lead to things being a breaking change or the resource being unusable for other use cases without changes.

The [Cloudformation type](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-athena-datacatalog.html) would then suggest a resource that looks like this:

```hcl
resource "aws_athena_data_catalog" "example" {
  name        = "example"
  description = "optional"
  type        = "LAMBDA"

  parameters {
    function = aws_lambda_function.foo_lambda.function_name
  }

  tags {
    tag_key = "tag value"
  }
}
```

**Comment by mechastorm** [comment]
I think Athena Federated Query is out of preview at this point in time, so I think the feature is stable enough to build support into the AWS provider perhaps?

**Comment by jay-manday** [comment]
Would love to see a terraform support federated athena db's this would save us some serious overhead

**Comment by NirBarak-RecoLabs** [comment]
Any update on this issue? We're resorting to provisioners at the moment.

**Comment by rmsys** [comment]
I'm stuck with this too. 

But I have no time for waiting Terraform... 

I will try with `"resource "aws_cloudformation_stack" "connector"` and so launch stack

I can't see another options

**Comment by woz5999** [comment]
Super depressing finding a 2 year old issue with 66 likes and absolutely no forward progress =[

**Comment by jay-manday** [comment]
yeah this is a bummer indeed

**Comment by DrFaust92** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/22968
