### ISSUE TITLE
aws_lambda_alias not updating on new aws_lambda_function version

### ISSUE THREAD

**Issue by niklaskhf** [hashicorp/terraform-provider-aws#13099]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform: v0.12.24
provider.aws: v2.59.0

### Affected Resource(s)
* aws_lambda_function
* aws_lambda_alias

### Terraform Configuration Files

```hcl
resource "aws_lambda_function" "example" {
  function_name = "example-lambda"
  handler = "main"
  role = aws_iam_role.lambda_role.arn
  runtime = "go1.x"
  filename = "../code.zip"
  timeout = 20
  memory_size = 128
  reserved_concurrent_executions = 1
  publish = true
}

resource "aws_lambda_alias" "example" {
  name             = "example-alias"
  description      = "latest version"
  function_name    = aws_lambda_function.example.arn
  function_version = aws_lambda_function.example.version

  depends_on=[aws_lambda_function.example]
}
```

### Expected Behavior

The aws_lambda_funcion resource gets updated to a new version, because publish=true. The aws_lambda_alias resource gets updated to the new version of aws_lambda_function.

### Actual Behavior

The aws_lambda_funcion resource gets updated to a new version, because publish=true. The aws_lambda_alias does not get updated until the next apply. 

### Steps to Reproduce

1. `terraform apply` -> aws_lambda_function gets updated
2. `terraform apply` -> aws_lambda_alias gets updated 

### References

* #3032 
* #628 
* #3192

**Comment by yaochaoutokyo** [comment]
Exactly the same problem here. I tried to use a lambda alias named "prod" to point to the latest published version. However, when I modify the lambda function configuration and set the publish=true, the function gets a new version, but the alias doesn't get updated to the new version.

**Comment by jbilliau5668** [comment]
Yup, same here!

**Comment by andrewwheal** [comment]
This seems to be a regression of #2915

**Comment by kevinmstephens** [comment]
I think I may have found the reason. I opened this ticket with my best guess at the cause. https://github.com/terraform-providers/terraform-provider-aws/issues/14210.

Copied here:

Guess at Cause
I believe I have found the cause but I'd hope someone can confirm.

It seems that the auto-publish feature is used in updating lambdas. This API call to AWS will return the updated version. However the AWS provider doesn't appear to use that version and instead appears to call get-function-versions and grab the largest version from the return list and use that value. However, I've confirmed with AWS Support that get-function-versions isn't a strongly consistent call and in fact is eventually consistent and has a cache TTL (length unknown).

I believe that the calls to get-function-versions sometimes returns stale data and so the new version is not present.

To solve this issue the AWS provider should use the version returned from the update-function call (create-function call too if that's relevant).
