### ISSUE TITLE
AWS SecurityHub: Add support to EnableDefaultStandards option in aws_securityhub_account resource 

### ISSUE THREAD

**Issue by nagaharayuuki** [hashicorp/terraform-provider-aws#13100]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Support for `EnableDefaultStandards` parameter in the resource [aws_securityhub_account](https://www.terraform.io/docs/providers/aws/r/securityhub_account.html).
When SecurityHub is enabled, the `CIS AWS Foundations Standard` and `AWS Foundational Security Best Practices Standard` standards are automatically enabled, but some people may not want this.
To be able to disable this behaviour i am requesting the addition of an "enable_default_standards" parameter for the resource.

### New or Affected Resource(s)

* aws_securityhub_account

### References

* https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-settingup.html#securityhub-enable
* https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_EnableSecurityHub.html

**Comment by doublefelix7** [comment]
Hello, I have a PR that may resolve this issue, but I just need someone to run the acceptance tests for me and make sure that I haven't missed anything since this is my first contribution to this repo.
