### ISSUE TITLE
[AWS] Creating of ALB, Target Group and Service in one script causes errors

### ISSUE THREAD

**Issue by throwaway8787** [hashicorp/terraform-provider-aws#13105]
See: https://github.com/hashicorp/terraform/issues/12634

Don't know why it was closed there, it's not a provider issue, seems more like a graph issue in terraform.

**Comment by cdimitroulas** [comment]
There was a similar issue here https://github.com/terraform-providers/terraform-provider-aws/issues/3495 but that was also closed even though the issue persists

**Comment by justinretzolk** [comment]
Hey @throwaway8787 👋 Thank you for taking the time to file this. Given that there's been a few AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?
