### ISSUE TITLE
r/aws_cloudfront_distribution should use `wait_for_deployed` (or new property) on destroy

### ISSUE THREAD

**Issue by kevinkuszyk** [hashicorp/terraform-provider-aws#13102]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As we know CloudFront distributions can take some time to deploy and destroy.

We've had the `wait_for_deployed` property for some time now which is great. I was hoping that terraform would use that when destroying and not wait until the distribution has been deleted. Unfortunately it does not.

It would be great if we could either use this property to not wait on destroy, or add a new property for users to want to wait for deploy, but not destroy.

In my case, I don't want to wait for either.

If there is some consensus around this, I'm happy to have a stab at implementing.

### New or Affected Resource(s)

* aws_cloudfront_distribution

### Potential Terraform Configuration

Maybe a new property for this.  The default would be `true` to avoid any change in existing behaviour.

```hcl
resource "aws_cloudfront_distribution" "front_end" { 
  # other properties omitted 

  wait_for_destroy = false
}
```

**Comment by dmitriyshub** [comment]
Great idea!
