### ISSUE TITLE
Tech Debt: Standardize Naming Conventions in Go Code

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#13128]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Several naming styles having cropped up in the AWS provider. I propose that conventions be adopted and that any non-conforming code be aligned.

### Go Conventions

At this point, the AWS provider cannot adhere to standard [Go conventions](https://golang.org/doc/effective_go.html) without starting a losing tech debt war. However, when choosing between equally plausible options, weight can be given to the Go conventions. The Go conventions are simple:

- Use mixed caps instead of underscores (e.g., `func queryResult()` instead of `func query_result()`)
- An abbreviation should be all caps or all lowercase (e.g., `func getIP()` and `func ipAddress()` instead of `func getIp()` and `func iPAddress()`)

### Proposal

To minimize work to bring everything in conformity based on [all the function and constant names in the AWS provider](https://github.com/YakDriver/terraform-aws-conventions), some initial steps to bring the Terraform AWS provider to convention consistency:

- [ ] Function names should be mixed case with a maximum of one underscore ([1193](https://github.com/YakDriver/terraform-aws-conventions#multiple-underscores) to fix).
- [ ] The letter immediately after any underscore should be lowercase ([2012](https://github.com/YakDriver/terraform-aws-conventions#uppercase-after-first-underscore) to fix).
- [ ] "AWS" should be all caps or all lowercase, not mixed case (e.g., "testAWS" not "testAws", "awsTest" not "aWSTest") ([4539](https://github.com/YakDriver/terraform-aws-conventions#mixed-case-aws) to fix).
- [ ] All other abbreviations (except "AWS") should be mixed case (e.g., "getIam" not "getIAM") ([2993](https://github.com/YakDriver/terraform-aws-conventions#non-aws-multicaps) to fix).

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/9950
