### ISSUE TITLE
Terraform plan dialing to 127.0.0.1:10000

### ISSUE THREAD

**Issue by Predator1997** [hashicorp/terraform-provider-aws#13133]
Hi ,

I am trying to perform operation on AWS using terraform . I have installed latest package of terraform and set the environment variables correctly. When I run terraform init on PowerShell it downloads some files , but when I execute 'terraform plan ' it gives me following error :

Failed to retrieve schema from provider "aws": rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: error while dialing: dial tcp 127.0.0.1:10000: 
connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or 
established connection failed because connected host has failed to respond."

I have tried using different version of terraform and on Powershell and Command Line .
I currently use windows 10 operating system.

I have also tried to debug the process , I have attached the output of debug variable in this issue.

[debug.txt](https://github.com/terraform-providers/terraform-provider-aws/files/4567555/debug.txt)

Guidance in any direction will be helpful

Thanks in advance!!

**Comment by justinretzolk** [comment]
Hey @Predator1997 👋 Thank you for taking the time to file this issue. Given that there's been a number of AWS Provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?
