### ISSUE TITLE
ECS Cluster does not swap Capacity Providers on ASG swap.

### ISSUE THREAD

**Issue by asheliahut** [hashicorp/terraform-provider-aws#13131]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

`0.12.24`

### Affected Resource(s)

1. aws_ecs_capacity_provider
2. aws_launch_template
3. aws_autoscaling_group
4. aws_ecs_cluster

### Terraform Configuration Files

[Config files are located here](https://gist.github.com/asheliahut/fb6baefdb3f650a284e99679570933a9)

### Expected Behavior

When the new ASG is spun up next to the old ASG by using a new name based on launch template version a new capacity provider is created. Then when they are created they are attached to the cluster and any services pointing at that new capacity provider with the services swapping to being provisioned on the new ASG. After that the old capacity provider is removed and old ASG is deleted.

### Actual Behavior

The new ASG is spun up and a new capacity provider is created. The new capacity provider attaches to the cluster and services, but the old capacity provider can not be removed due to the old capacity provider still being in use.

Error: error changing ECS cluster capacity provider settings (cluster:arn): ResourceInUseException: The specified capacity provider is in use and cannot be removed.

### Steps to Reproduce

1. Create a new autoscaling group, capacity provider, launch template, ecs cluster, and ecs service running on the cluster.
2. Update the launch template.
3. Run `terraform apply`

### Important Factoids

I have tried multiple ways to get the ability to swap a launch configuration while using capacity providers. There doesn't seem to be a great way other than updating the launch template and then scaling the services up and down in order to change the launch template or fully creating a new cluster and services.

**Comment by justinretzolk** [comment]
Hey @asheliahut 👋 Thank you for taking the time to file this issue. Given that there's been a few AWS provider releases since you initially filed it, can you confirm whether you're still experiencing this issue?

**Comment by asheliahut** [comment]
@justinretzolk Sadly it does not, but that is mainly because of the fact of the way AWS works. It can not shift the services running over to the new cluster coming up. I think there may be a way to do it as I personally worked on a internal tool to my company that we use now to swap over services running to the new cluster that listens for the change and runs on a null provider to do the swap. As of today though it does not still do out of the box what I was asking in the issue.

**Comment by asheliahut** [comment]
Also to note the issue can be tricky too, because if you manage your ECS service outside of the location you host the ECS cluster/Capacity Provider/ASG/Launch Template then the services Terraform can become out of sync as the Capacity provider used previously may not exist. @justinretzolk
