### ISSUE TITLE
aws_launch_configuration associate_public_ip_address=false is ambiguous

### ISSUE THREAD

**Issue by duckfez** [hashicorp/terraform-provider-aws#13137]
When creating a `aws_launch_configuration` with `associate_public_ip_address=false`, the AWS provider does not make the correct call to the AWS API.

The AWS Autoscaling API (weirdly) has a "tri-state" value for AssociatePublicIPAddress.  It's a boolean argument that is optional.  So you can not provide a value, or you can provide a false, or a true.   If no value is provided, then the launch config basically defaults to the Subnet's "Auto-Assign-IP-Address" setting.

BUT, Terraform seems to never send the explicit value of `false`.  If your HCL contains `true`, then terraform sets the value in the API call to `true`.  If your HCL contains `false` then terraform does not explicitly send  `AssociatePublicIPAddress=false` in the API call.

In effect, as a user of Terraform you can only set two out of the three possible values that the API supports.  You can definitely set "yes I want public IPs for this launch configuration", or you can set "I want to take the subnet's default setting."   You cannot set "I want to disable public IPs for this launch configuration even if the subnet's default is `true`"

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.24
+ provider.aws v2.60.0
```

### Affected Resource(s)

* aws_launch_configuration

### Terraform Configuration Files

```hcl

resource "aws_launch_configuration" "test" {
  name                        = "test"
  image_id                    = "ami-0febcd3936ec626b6"
  instance_type               = "t2.micro"
  associate_public_ip_address = false
}
```

### Debug Output

https://gist.github.com/duckfez/49a1562faeffdb28e89690d441549c35

### Expected Behavior

The Launch Configuration is created with Automatic Public IP addresses disabled

### Actual Behavior

The Launch Configuration is created with Automatic Public IP addresses inheriting from the Subnet default.

### Steps to Reproduce

1. `terraform apply`

**Comment by duckfez** [comment]
Possibly the same thing as #1484

**Comment by Jukie** [comment]
I can pick this up if nobody’s working on it.

**Comment by wadeholler** [comment]
The last of a "disable" setting also causes our launch configuration ( or template )to be invalid for launching instances.  i.e. it will get declared in aws but will not launch instances and the auto scaling group will infinite loop trying to launch instances.  If I copy the launch config and just change the public ip setting to disabled - then it launches instances just fine.

This stops us from using terraform for launch configuation / launch template.

**Comment by wadeholler** [comment]
update - while I thought this was my issue  after I removed key_name and ebs_optimized the error went away. using t2.2xlarge so I guess that makes sense.

**Comment by fckbo** [comment]
Hello, 
it seems that this problem is still there:
```
Terraform v1.1.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.70.0
```
