### ISSUE TITLE
Principal type can be invalid for aws_iam_policy_document

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#13148]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.24

### Affected Resource(s)

* aws_iam_policy_document

### Terraform Configuration Files

```hcl
data "aws_iam_policy_document" {
  statement {
    # ...
    principal {
      type = "service"
      value = "..."
    }
  }
  # ...
}
```

### Expected Behavior

This should either cause a validation error in Terraform, or automatically convert the principal key to `Service`. When generating the actual JSON for this policy, this should create `{"Principal": {"Service": "..."}}` instead of `{"Principal": {"service": "..."}}`.

### Actual Behavior

The key is sent in lowercase to AWS, which causes an AWS-side syntax error.

**Comment by bendrucker** [comment]
I've posted a fix for this (adding validation) in #13157, please give that a 👍 to help prioritize it!

**Comment by clar-cmp** [comment]
Awesome work! Thank you!

**Comment by clar-cmp** [comment]
Should comment here that the PR was closed because no one responded after a short while -- so, this issue still remains unresolved.
