### ISSUE TITLE
Support ignore minor versions config change for RDS Cluster

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#13147]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`aws_db_instance` allows you to specify a version prefix when `auto_minor_version_upgrade` is enabled. This prevents a patch difference affecting the terraform configuration. Replicate this functionality for 'aws_rds_cluster_instance'

### New or Affected Resource(s)

* aws_rds_cluster_instance

### Potential Terraform Configuration

```hcl
resource "aws_rds_cluster_instance" "cluster_instances" {
  count              = 2
  identifier         = "aurora-cluster-demo-${count.index}"
  cluster_identifier = "${aws_rds_cluster.default.id}"
  instance_class     = "db.r4.large"
  engine_version    = "5.7"
  auto_minor_version_upgrade = true
}
```

**Comment by breathingdust** [comment]
Duplicate of #1198

**Comment by mikegreen** [comment]
@breathingdust should we mark this resolved now with https://github.com/hashicorp/terraform-provider-aws/issues/1198 looking like its closed?

**Comment by breathingdust** [comment]
Thanks @mikegreen!

Closing this as the investigation performed in #1198 was unable to reproduce.
