### ISSUE TITLE
s3 bucket policy with not_principal always changes due to ordering

### ISSUE THREAD

**Issue by craiggenner** [hashicorp/terraform-provider-aws#13144]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

$ terraform -v
Terraform v0.12.24
+ provider.aws v2.60.0
+ provider.template v2.1.2

### Affected Resource(s)

* aws_s3_bucket_policy
* aws_iam_policy_document
* aws_s3_bucket

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket" "av" {
  bucket = "app-storage"
  acl    = "private"
}

data "aws_iam_policy_document" "s3_av" {
  statement {
    sid       = "DenyInfected"
    effect    = "Deny"
    actions   = ["s3:GetObject", "s3:PutObjectTagging"]
    resources = ["arn:aws:s3:::${var.s3_bucket}/*"]

    not_principals {
      type        = "AWS"
      identifiers = [
        aws_iam_role.antivirus.arn,
        "arn:aws:sts::${var.account_id}:assumed-role/${aws_iam_role.antivirus.name}/${aws_lambda_function.antivirus.function_name}"
      ]
    }

    # Deny where 'av-status' tag is 'INFECTED'
    condition {
      test     = "StringEquals"
      variable = "s3:ExistingObjectTag/av-status"
      values   = ["INFECTED"]
    }
  }
}

resource "aws_s3_bucket_policy" "av" {
  bucket = aws_s3_bucket.av.id
  policy = data.aws_iam_policy_document.s3_av.json
}
```

### Debug Output

https://gist.github.com/craiggenner/b315384e6ca2cead486b14665840807e

### Panic Output

None

### Expected Behavior

Terraform shouldn't expect to make any changes

### Actual Behavior

Terraform always wants to replace the policy of the s3 bucket

### Steps to Reproduce

1. Create terraform code as above

1. `terraform apply`

1. `terraform apply`

### Important Factoids
Running this against eu-west-1 region.

The issue appears to be related to the use of the sts assumed-role in the `not_principals`, a regular iam role entry doesn't produce this. With multiple entries the order of the `not_principals` block is moved around within the json policy

### References

* https://github.com/hashicorp/terraform/issues/4948

**Comment by roccomuscaritolo-okta** [comment]
I can confirm this issue is still occurring in AWS hashicorp/aws version v3.18.0.

Even adding a sort on the principals directly does not change this diff behavior.
```hcl
principals {
      type        = "AWS"
      identifiers = sort([for role in data.aws_iam_role.decrypt_allowed_roles : role.arn])
    }
```

While the end result makes no difference, at a much larger scale this puts an undo burden on the reviewer to manually parse the output. I personally have had to review about 9 prinicple changes for someone simply adding 1 new role to a list.
```
------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_s3_bucket_policy.main will be updated in-place
  ~ resource "aws_s3_bucket_policy" "main" {
        bucket = "rocco-testing"
        id     = "rocco-testing"
      ~ policy = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                        Action    = "s3:*"
                        Effect    = "Allow"
                      ~ Principal = {
                          ~ AWS = [
                                "arn:aws:iam::123456789:role/test",
                              + "arn:aws:iam::123456789:role/rundeck-test",
                                "arn:aws:iam::123456789:role/kallentest",
                                "arn:aws:iam::123456789:role/career-test",
                              + "arn:aws:iam::123456789:role/career-test123",
                                "arn:aws:iam::123456789:root",
                              - "arn:aws:iam::123456789:role/rundeck-test",
                            ]
                        }
                        Resource  = [
                            "arn:aws:s3:::rocco-testing/*",
                            "arn:aws:s3:::rocco-testing",
                        ]
                        Sid       = "Allow test/root access"
                    },
                ]
                Version   = "2012-10-17"
            }
        )
    }

Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------
```

**Comment by iainelder** [comment]
@craiggenner I can confirm what @roccomuscaritolo-okta sees. It happens in the normal principal field as well.

The crazy thing is that if you test an expression such as `[for role in data.aws_iam_role.decrypt_allowed_roles : role.arn]` in `terraform console` then it always returns the same order of elements.

It looks like the bucket policy resource is jumbling them up at some point.

**Comment by iainelder** [comment]
The Principals and NotPrincipals elements of IAM policy statements appear to be handled in exactly the same way, so that would explain why the behavior is observed in both places.

https://github.com/hashicorp/terraform-provider-aws/blob/3b05635c2bb9486f5156576b3701746066aa92f8/aws/iam_policy_model.go#L22-L23

The problem appears to occur in the unmarshalling of the policy document. That's a guess because it only happens when the result of encodejson has been set on the bucket policy resource.

I'm unsure if a change is required in UnmarshalJSON. It looks like it just iterates over whatever its given without reodering anything.

https://github.com/hashicorp/terraform-provider-aws/blob/e9a98cf0dad9bad4c17aa7deeb657f7e4066aa6d/aws/iam_policy_model.go#L127-L159

The schema for the principal policy element says that identifiers are a set, and so unordered. As it turns out, the order matters for diffs. Instead of using schema.TypeSet, should it instead be using schema.TypeList?

https://github.com/hashicorp/terraform-provider-aws/blob/ac06ced75cba0daf09fef2938752ad13cc6fff6e/aws/data_source_aws_iam_policy_document.go#L344-L364

A similar change was applied to preserve the order of condition values. The type of the values in the condition schema was changes from TypeSet to TypeList.

https://github.com/hashicorp/terraform-provider-aws/commit/e9a98cf0dad9bad4c17aa7deeb657f7e4066aa6d

https://github.com/hashicorp/terraform-provider-aws/pull/17556

@YakDriver you were here recently (it was your PR that fixed the condition ordering!) Do you think changing TypeSet to TypeList here would be enough to fix this?

**Comment by iainelder** [comment]
See below for a small Terraform configuration that reproduces the issue. Change to a temporary directory and copy the configuration to a file in the directory called main.tf.

Before running the Terraform commands, first set your environment with credentials and a region.

```bash
export AWS_PROFILE=...
export AWS_DEFAULT_REGION=...
```

Output after first apply shows that the principal elements in the bucket policy are ordered according to the configuration.

```bash
terraform apply
terraform output --raw test | jq
```

```json
{
  "Statement": [
    {
      "Action": "*",
      "Effect": "Deny",
      "Principal": {
        "AWS": [
          "arn:aws:iam::480783779961:role/role-0",
          "arn:aws:iam::480783779961:role/role-1",
          "arn:aws:iam::480783779961:role/role-2",
          "arn:aws:iam::480783779961:role/role-3",
          "arn:aws:iam::480783779961:role/role-4",
          "arn:aws:iam::480783779961:role/role-5",
          "arn:aws:iam::480783779961:role/role-6",
          "arn:aws:iam::480783779961:role/role-7",
          "arn:aws:iam::480783779961:role/role-8",
          "arn:aws:iam::480783779961:role/role-9"
        ]
      },
      "Resource": "arn:aws:s3:::tftest20210525081545966100000001"
    }
  ],
  "Version": "2012-10-17"
}
```

Second apply shows a change to the output. Without changing the effective permissions of the bucket policy, the policy elements are reordered.

```
terraform apply
terraform output --raw test | jq
```

```text
Changes to Outputs:
  ~ test = jsonencode(
      ~ {
          ~ Statement = [
              ~ {
                  ~ Principal = {
                      ~ AWS = [
                          - "arn:aws:iam::480783779961:role/role-0",
                          - "arn:aws:iam::480783779961:role/role-1",
                          - "arn:aws:iam::480783779961:role/role-2",
                          - "arn:aws:iam::480783779961:role/role-3",
                            "arn:aws:iam::480783779961:role/role-4",
                            "arn:aws:iam::480783779961:role/role-5",
                          - "arn:aws:iam::480783779961:role/role-6",
                          - "arn:aws:iam::480783779961:role/role-7",
                          + "arn:aws:iam::480783779961:role/role-2",
                          + "arn:aws:iam::480783779961:role/role-3",
                          + "arn:aws:iam::480783779961:role/role-0",
                          + "arn:aws:iam::480783779961:role/role-1",
                            "arn:aws:iam::480783779961:role/role-8",
                            "arn:aws:iam::480783779961:role/role-9",
                          + "arn:aws:iam::480783779961:role/role-6",
                          + "arn:aws:iam::480783779961:role/role-7",
                        ]
                    }
                    # (3 unchanged elements hidden)
                },
            ]
            # (1 unchanged element hidden)
        }
    )
```

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Deny",
      "Principal": {
        "AWS": [
          "arn:aws:iam::480783779961:role/role-4",
          "arn:aws:iam::480783779961:role/role-5",
          "arn:aws:iam::480783779961:role/role-2",
          "arn:aws:iam::480783779961:role/role-3",
          "arn:aws:iam::480783779961:role/role-0",
          "arn:aws:iam::480783779961:role/role-1",
          "arn:aws:iam::480783779961:role/role-8",
          "arn:aws:iam::480783779961:role/role-9",
          "arn:aws:iam::480783779961:role/role-6",
          "arn:aws:iam::480783779961:role/role-7"
        ]
      },
      "Action": "*",
      "Resource": "arn:aws:s3:::tftest20210525081545966100000001"
    }
  ]
}
```

The order of the policy elements changes arbitrarily with each successive apply.

---

The Terraform configuration:

```hcl
output "test" {
  value = aws_s3_bucket_policy.test.policy
}

resource "aws_s3_bucket" "test" {
  bucket_prefix = "tftest"
}

resource "aws_s3_bucket_policy" "test" {
  bucket = aws_s3_bucket.test.id

  policy = jsonencode({
      Statement = [
        {
          Principal = {
            AWS = [for r in aws_iam_role.test: r.arn]
          }
          Resource = "${aws_s3_bucket.test.arn}"
          Action = "*"
          Effect = "Deny"
        }
      ]
      Version = "2012-10-17"
  })
}

resource "aws_iam_role" "test" {
  count = 10
    
  name = "role-${count.index}"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Deny"
        Action = "sts:AssumeRole"
        Principal = {
          AWS = "*"
        }
      }
    ]
  })
}
```

**Comment by ewbankkit** [comment]
Potentially related: https://github.com/jen20/awspolicyequivalence/issues/10.

**Comment by crawforde** [comment]
I can confirm I'm having this same problem for both `Principal` and `NotPrincipal` blocks using terraform v1.0.0 and provider version v3.52.0.

**Comment by virgofx** [comment]
Also observing this issue with `hashicorp/aws` `3.60.0` and Terraform 1.0.8.
