### ISSUE TITLE
aws_cognito_user_pool add support for SES ConfigurationSet

### ISSUE THREAD

**Issue by mousedownmike** [hashicorp/terraform-provider-aws#13154]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The AWS [CreateUserPool](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPool.html) and [UpdateUserPool](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserPool.html) APIs now support a [ConfigurationSet EmailConfiguration option](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_EmailConfigurationType.html#CognitoUserPools-Type-EmailConfigurationType-ConfigurationSet). It would be great to incorporate this into the existing `aws_cognito_user_pool` resource.

### New or Affected Resource(s)

* `aws_cognito_user_pool`

### Potential Terraform Configuration

```hcl
resource aws_ses_email_identity example {
  email = "cognito@example.com"
}
resource aws_ses_configuration_set cognito_config {
  name = "cognito-config"
}
resource aws_cognito_user_pool example {
  name = "example-user-pool"
  email_configuration {
    source_arn = aws_ses_email_identity.example.arn
    from_email_address = "Example <${aws_ses_email_identity.example.email}>"
    email_sending_account = "DEVELOPER"
    configuration_set = aws_ses_configuration_set.cognito_config.name
  }
}

```

### References

* https://forums.aws.amazon.com/thread.jspa?threadID=302169&tstart=0&messageID=940659#940659
* https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_EmailConfigurationType.html#CognitoUserPools-Type-EmailConfigurationType-ConfigurationSet
* https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPool.html
* https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserPool.html

**Comment by s16tom** [comment]
@mousedownmike did you work around this at all? This is more of a pain than other similar issues I've encountered, as the AWS CLI does not let you _just_ update this field - you have to provide all Cognito User Pool config otherwise it gets replaced by defaults. 

I'm currently using a provisioner on the user pool that is using the AWS CLI to invoke a lambda function, then reading, updating and then rewriting the Cognito config in that. It's a horrendous work around though, so any other pointers would be appreciated!

**Comment by mousedownmike** [comment]
@s16tom I did not have a work around for this, it is one of the few manual steps I perform after creating an environment.
