### ISSUE TITLE
    assign_generated_ipv6_cidr_block = true is not supported

### ISSUE THREAD

**Issue by anupom2017** [hashicorp/terraform-provider-aws#13159]
I am writing a small terraform code for AWS to create a VPC with IPV6 enabled.  But i am getting an error " invalid or unknown key: assign_generated_ipv6_cidr_block". Please suggest an alternative.

here is my code :

resource "aws_vpc" "test-vpc" {
    provider = "aws.acit-vpc"
    enable_dns_support = true
    enable_dns_hostnames = true
    assign_generated_ipv6_cidr_block = true
    cidr_block = "10.0.0.0/16"

**Comment by rick-masters** [comment]
Were you able to figure this out? Do you remember what version you were trying this with? This configuration works fine for me and that key has been supported for years. So, I can only think that you have a an older version of terraform, like around 0.8 or earlier?
