### ISSUE TITLE
Resource aws_volume_attachment fails on already attached volume

### ISSUE THREAD

**Issue by henrytk** [hashicorp/terraform-provider-aws#13160]
This is a request to reopen https://github.com/hashicorp/terraform/issues/18519

The original issue confirmed if you attach a volume to an instance with a device name, then use an `aws_volume_attachment` resource with a different device name, Terraform will try and fail to attach the volume to the instance. I think Terraform should recognise the attachment being in an incorrect state (wrong device name) and should detach the volume and re-attach with the correct device name.

**Comment by justinretzolk** [comment]
Hey @henrytk 👋 Thank you for taking the time to submit this issue. Given that there's been a number of Terraform and AWS Provider releases since you initially filed it, can you confirm whether this is still an issue you're facing?
