### ISSUE TITLE
aws_backup_plan Rule Lifecycle Should Be Optional

### ISSUE THREAD

**Issue by jdurhamcgi** [hashicorp/terraform-provider-aws#13165]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.18
+ provider.aws v2.60.0

### Affected Resource(s)

* aws_backup_plan

### Terraform Configuration Files

```hcl
resource "aws_backup_vault" "example1" {
  name = "example-vault"
}

resource "aws_backup_vault" "example2" {
  name = "example-vault-2"
}

resource "aws_backup_plan" "plan" {
  name = "example-plan"
  rule {
    rule_name = "rule"
    target_vault_name = aws_backup_vault.example1.name
    schedule = "cron(0 4 * * ? *)"
    copy_action {
      destination_vault_arn = aws_backup_vault.example2.arn
    }
  }
}
```

### Debug Output

https://gist.github.com/jdurhamcgi/2d029ba87e472c874853c678c7b1ce2d

### Expected Behavior

I should be able to create a rule with a copy_action block that does not require lifecycle arguments.

### Actual Behavior

Plan fails because Terraform sends an empty `lifecycle` block in the request.

### Steps to Reproduce

1. `terraform apply`

**Comment by mikalai-t** [comment]
1. Even when either of the parameters is set Terraform keeps failing with the same error `Invalid lifecycle. Both MoveToColdStorageAfterDays and DeleteAfterDays are missing.`.
2. Setting `null` values to both of them leads to chaotic combination of errors (every launch you may get a different combination):
```hcl
Error: rpc error: code = Unavailable desc = transport is closing
```
```hcl
Error: rpc error: code = Canceled desc = context canceled
```
```hcl
Error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: read unix @->/tmp/plugin616988045: read: connection reset by peer"
```
```hcl
Error: rpc error: code = Canceled desc = latest connection error: connection error: desc = "transport: authentication handshake failed: read unix @->/tmp/plugin616988045: read: connection reset by peer"
```

**Comment by exavier-slf** [comment]
resource "aws_backup_plan" "aws_backup_plan" {
  name = "tf_example_backup_plan"

  rule {
    rule_name         = "resource_nackup"
    target_vault_name = "${aws_backup_vault.backup_vault.name}"
    schedule          = "cron(0 12 * * ? *)"
    copy_action = {
      destination_vault_arn = "arn:aws:backup:us-east-1:ACCOUNT_NUMBER:backup-vault:backup-cross-region"
      lifecycle           = {
        cold_storage_after = 0 
        delete_after = 0

      }
    }
  }
  
}




Facing the same issue 
``` 1 error occurred:
        * module.main.aws_backup_plan.aws_backup_plan: 1 error occurred:
        * aws_backup_plan.aws_backup_plan: error creating Backup Plan: InvalidParameterValueException: Error in rule resource_nackup : Invalid lifecycle. Both MoveToColdStorageAfterDays and DeleteAfterDays are missing.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "997f46aa-ade5-4358-85bb-f99bcfcd85cf"
  },
  Code_: "ERROR_3015",
  Context: "[\"resource_nackup\",\"Invalid lifecycle. Both MoveToColdStorageAfterDays and DeleteAfterDays are missing.\"]",
  Message_: "Error in rule resource_nackup : Invalid lifecycle. Both MoveToColdStorageAfterDays and DeleteAfterDays are missing."
}

```

**Comment by exavier-slf** [comment]
Needed to check if we have any updates on this issue ?
