### ISSUE TITLE
aws_redshift_snapshot_schedule_association fails waiting for state to become ACTIVE

### ISSUE THREAD

**Issue by charlesakalugwu** [hashicorp/terraform-provider-aws#13164]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
+ Terraform v0.12.24
+ provider.aws v2.58.0
+ provider.kubernetes v1.11.1
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
```

### Affected Resource(s)

* aws_redshift_snapshot_schedule_association

### Terraform Configuration Files

```hcl
resource "aws_redshift_cluster" "this" {
  cluster_identifier = "analytics"
  database_name      = "analytics"
  master_username    = "analytics"
  master_password    = "Mustbe8characters"
  node_type          = "dc1.large"
  cluster_type       = "single-node"
}

resource "aws_redshift_snapshot_schedule" "redshift" {
  identifier = "daily-snapshot"
  definitions = [
    "rate(24 hours)",
  ]

  depends_on = [
    aws_redshift_cluster.this
  ]
}

resource "aws_redshift_snapshot_schedule_association" "redshift" {
  cluster_identifier  = aws_redshift_cluster.this.id
  schedule_identifier = aws_redshift_snapshot_schedule.redshift.id

  depends_on = [
    aws_redshift_snapshot_schedule.redshift
  ]
}
```

### Expected Behavior

The redshift snapshot schedule association resource waits until the association is made on the AWS side before returning to the terraform caller

### Actual Behavior

It seems the snapshot schedule association resource bails out after 30s, waiting for the state of the association to become ACTIVE
```
module.analytics-environment.aws_redshift_cluster.this: Still creating... [2m20s elapsed]
module.analytics-environment.aws_redshift_cluster.this: Still creating... [2m30s elapsed]
module.analytics-environment.aws_redshift_cluster.this: Creation complete after 2m36s [id=analytics]
module.analytics-environment.aws_redshift_snapshot_schedule.redshift: Creating...
module.analytics-environment.aws_redshift_snapshot_schedule.redshift: Creation complete after 0s [id=daily-snapshot]
module.analytics-environment.aws_redshift_snapshot_schedule_association.redshift: Creating...
module.analytics-environment.aws_redshift_snapshot_schedule_association.redshift: Still creating... [10s elapsed]
module.analytics-environment.aws_redshift_snapshot_schedule_association.redshift: Still creating... [20s elapsed]
module.analytics-environment.aws_redshift_snapshot_schedule_association.redshift: Still creating... [30s elapsed]

Error: Error waiting for Redshift Cluster (analytics) and  Snapshot Schedule (daily-snapshot) Association state to be "ACTIVE": unexpected state 'destroyed', wanted target 'ACTIVE'. last error: %!s(<nil>)

  on modules/account-type/analytics/redshift.tf line 81, in resource "aws_redshift_snapshot_schedule_association" "redshift":
  81: resource "aws_redshift_snapshot_schedule_association" "redshift" {
```
The snapshot schedule association is always processed correctly by terraform after a subsequent `plan` and `apply`

```
terraform apply -auto-approve -no-color ".terraform/plan/tfplan"
module.analytics-environment.aws_redshift_snapshot_schedule_association.redshift: Creating...
module.analytics-environment.aws_redshift_snapshot_schedule_association.redshift: Still creating... [10s elapsed]
module.analytics-environment.aws_redshift_snapshot_schedule_association.redshift: Still creating... [20s elapsed]
module.analytics-environment.aws_redshift_snapshot_schedule_association.redshift: Still creating... [30s elapsed]
module.analytics-environment.aws_redshift_snapshot_schedule_association.redshift: Creation complete after 30s [id=analytics/daily-snapshot]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

### References
New Resource: aws_redshift_snapshot_schedule #8064
New Resource: aws_redshift_snapshot_schedule_association #8064

**Comment by justinretzolk** [comment]
Hey @charlesakalugwu 👋 Thank you for taking the time to file this. Given that there's been a few AWS Provider releases since you initially filed it, can you confirm whether you're still experiencing this?

**Comment by rodrigoney** [comment]
@justinretzolk still happening in `hashicorp/aws` version `3.64.1`

**Comment by justinretzolk** [comment]
Hey @rodrigoney 👋 Thank you for the confirmation! With that in mind, I'll mark this as a bug so that we can take a look into it as soon as time allows.

**Comment by DrFaust92** [comment]
#24900 should take care of it, please re-open if issue persistes
