### ISSUE TITLE
resource/aws_subnet: Add customer_owned_ipv4_pool and map_customer_owned_ip_on_launch arguments

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#13170]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Go SDK v1.30.21 includes additional functionality for AWS Outposts, suitable for the `aws_subnet` resource.

### Affected Resource

* aws_subnet

### Potential Terraform Configuration

```hcl
resource "aws_subnet" "example" {
  cidr_block                      = "..."
  customer_owned_ipv4_pool        = data.aws_ec2_coip_pool.example.id
  map_customer_owned_ip_on_launch = true
  outpost_arn                     = "arn:..."
}
```

### References

* https://github.com/aws/aws-sdk-go/releases/tag/v1.30.21
* #12302 
* #12852

**Comment by bflad** [comment]
While this is supported in the SDK, it does not appear to be deployed to `us-west-2` yet. Sending any combination of `CustomerOwnedIpv4Pool` and `MapCustomerOwnedIpOnLaunch` to the `ModifySubnetAttributes` call returns the following error:

```
MissingParameter: No valid attributes specified.
```

They are also missing from the `DescribeSubnets` response.

**Comment by FireballDWF** [comment]
This support is needed for instances launched in ASG's to get CoIPs
