### ISSUE TITLE
S3 bucket replication rule requires versioning even if Disabled

### ISSUE THREAD

**Issue by rastakajakwanna** [hashicorp/terraform-provider-aws#13179]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.20
+ provider.aws v2.46.0
+ provider.external v1.2.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2

### Affected Resource(s)

* aws_s3_bucket

### Terraform Configuration Files

```hcl
  replication_configuration {
    role = local.iam_role_replication_arn
    rules {
      id     = "replication"
      status = "Disabled"
      source_selection_criteria {
        sse_kms_encrypted_objects {
          enabled = true
        }
      }
      destination {
        bucket             = local.s3_replica_arn
        replica_kms_key_id = local.kms_key_replica_arn
      }
    }
```

### Expected Behavior

According to documentation:
> status - (Required) The status of the rule. Either Enabled or Disabled. The rule **is ignored** if status is not Enabled.

I expected the rule to be ignored and not requiring replication prerequisite (Versioning).

### Actual Behavior

```Error: versioning must be enabled to allow S3 bucket replication```

### Steps to Reproduce

1. create resource aws_s3_bucket with versioning disabled and add disabled rule for replication
```
  versioning {
    enabled = false
  }

  replication_configuration {
    role = local.iam_role_replication_arn
    rules {
      id     = "replication"
      status = "Disabled"
      destination {
        bucket             = local.s3_replica_arn
        replica_kms_key_id = local.kms_key_replica_arn
      }
    }
```

2. `terraform apply` will result in error `Error: versioning must be enabled to allow S3 bucket replication`

### References

* #0000

**Comment by rastakajakwanna** [comment]
Perhaps, there is just missing support for option `enabled(bool)` in `replication_configuration` object.

**Comment by justinretzolk** [comment]
Hey @rastakajakwanna 👋 Thank you for taking the time to submit this issue. Given that there's been a few AWS Provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?

**Comment by rastakajakwanna** [comment]
Hey @justinretzolk , I did a quick test for you and I confirm the issue still persists:
```
aws_s3_bucket.general_bucket: Creating...
╷
│ Error: versioning must be enabled to allow S3 bucket replication
│ 
│   with aws_s3_bucket.general_bucket,
│   on s3.tf line 5, in resource "aws_s3_bucket" "test_bucket":
│    5: resource "aws_s3_bucket" "test_bucket" {
│ 
╵
~$ terraform -version
Terraform v1.0.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.53.0
```

**Comment by rastakajakwanna** [comment]
In case someone would like to reproduce my test, here is the code:
```
provider "aws" {
  region = "eu-west-1"
}

resource "aws_s3_bucket" "test_bucket" {
  bucket = "test-no-versioning-failure"

  acl    = "private"

  force_destroy = true

  versioning {
    enabled = false
  }

  replication_configuration {
    role = aws_iam_role.replication.arn
    rules {
      id     = "replication"
      status = "Disabled"
      destination {
        bucket             = "arn:aws:s3:::no-replica"
      }
    }
  }
}

resource "aws_iam_role" "replication" {
  name               = "s3-test-replication-role"
  assume_role_policy = data.aws_iam_policy_document.replication_assume_role.json
}

data "aws_iam_policy_document" "replication_assume_role" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["s3.amazonaws.com"]
    }
  }
}
```

**Comment by justinretzolk** [comment]
Thank you for the update, and for providing the reproduction configuration! I've marked this issue as a bug so that we may look into it as time permits.
