### ISSUE TITLE
Terraform silently adopts existing S3 buckets 

### ISSUE THREAD

**Issue by gilesvessey** [hashicorp/terraform-provider-aws#13185]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

12.21

### Affected Resource(s)

* aws_s3_bucket

#### Bucket Creator Project
```hcl
resource "aws_s3_bucket" "the_bucket" {
  bucket        = "the-bucket-in-question"

  tags = map(
    "Name", "the-bucket-in-question",
    "Managed by", "bucket-creator"
  )
}
```

#### Bucket Taker Project
```hcl 
resource "aws_s3_bucket" "the_bucket" {
  bucket        = "the-bucket-in-question"

  tags = map(
    "Name", "the-bucket-in-question",
    "Managed by", "bucket-taker"
  )
}
```
### Expected Behavior

Terraform should recognize that it is trying to create a bucket with a name that is already taken, and produce an error.

### Actual Behavior

The bucket is adopted by the second project without informing the user, leaving the bucket in the state of *both* terraform projects. The bucket's tags are overwritten by the second project, but the bucket is not recreated. Terraform states " aws_s3_bucket.the_bucket: Creation complete after 10s " without indication that we have taken over someone else's bucket. Destroying the second project will delete the bucket out of the first project.

### Steps to Reproduce

1. Download the attached zip or paste the above code into two separate .tf projects.
1. Apply the "Bucket Creator" project into an AWS account, change the bucket name if needed.
2. Apply the "Bucket Taker" project into the same account, ensuring the bucket name is the same as with the first project. The apply will complete without mention of the bucket already existing.
3. Destroy the "Bucket Taker" project
4. Note how the bucket has been deleted out of the first project.
[bucket-adopt-test.zip](https://github.com/terraform-providers/terraform-provider-aws/files/4587302/bucket-adopt-test.zip)

**Comment by ewbankkit** [comment]
@gilesvessey Thanks for raising this issue.
It has been noticed in #13587. I'm going to close this one as a duplicate (as it has fewer upvotes, even though it's older) so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
