### ISSUE TITLE
Add Global Accelerator data source

### ISSUE THREAD

**Issue by madpipeline** [hashicorp/terraform-provider-aws#13202]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
The Global Accelerator resource does not have a data source thus hindering the possibility of discovering an existing Global Accelerator instance.

### New or Affected Resource(s)

* `aws_globalaccelerator_accelerator`

**Comment by skolodyazhnyy** [comment]
I needed this data source to pass static IP of the global accelerator from one terraform workspace to another, so I can create some DNS records. As workaround, I wrote values into key-value storage (I used AWS SSM) and then retrieve them by key using SSM data source.

**Comment by kumadee** [comment]
Hi Guys. Can you please share any progress on this issue?

**Comment by thiagolsfortunato** [comment]
Any news?
