### ISSUE TITLE
InvalidParameterValue Tag error on aws_security_group resource creation - works on 2.44 fails on 2.5x - regression?

### ISSUE THREAD

**Issue by bhadrim** [hashicorp/terraform-provider-aws#13211]
I am using terraform 0.11.11 with AWS provider 2.5x. I have a security group resource with 2 tags. When I execute my template I see the following error 

aws_security_group.sg_cluster: 1 error(s) occurred:
* aws_security_group.sg_cluster: error adding EC2 Security Group (sg-04564928bebeb828a) tags: error tagging resource (sg-04564928bebeb828a): InvalidParameterValue: Value ( '' ) for parameter Tag key is invalid. Tag key cannot be null or empty.

The same template works fine on 2.44. Did anything change in the later provider? Is this a bug with the latest provider? Thank you for your time.

This is how my resource looks on a successful run

aws_security_group.sg_cluster: Creating...
  arn:                                 "" => ""
  description:                         "" => "Cluster communication with worker nodes"
  egress.#:                            "" => "1"
  egress.482069346.cidr_blocks.#:      "" => "1"
  egress.482069346.cidr_blocks.0:      "" => "0.0.0.0/0"
  egress.482069346.description:        "" => ""
  egress.482069346.from_port:          "" => "0"
  egress.482069346.ipv6_cidr_blocks.#: "" => "0"
  egress.482069346.prefix_list_ids.#:  "" => "0"
  egress.482069346.protocol:           "" => "-1"
  egress.482069346.security_groups.#:  "" => "0"
  egress.482069346.self:               "" => "false"
  egress.482069346.to_port:            "" => "0"
  ingress.#:                           "" => ""
  name:                                "" => "BMEKS2-sg-cluster"
  owner_id:                            "" => ""
  revoke_rules_on_delete:              "" => "false"
  tags.%:                              "" => "2"
  tags.aws:cloudformation:logical-id:  "" => "ControlPlaneSecurityGroup"
  tags.aws:cloudformation:stack-name:  "" => "BMEKS2-vpc"
  vpc_id:                              "" => "vpc-0cb0a97891fc3be48"

**Comment by justinretzolk** [comment]
Hey @bhadrim 👋 Thank you for taking the time to file this issue. Given that there's been a few Terraform and AWS Provider releases since you initially filed it, can you confirm whether you're still experiencing this behavior?
