### ISSUE TITLE
New resource: aws_cloudwatch_query_definition

### ISSUE THREAD

**Issue by mwarkentin** [hashicorp/terraform-provider-aws#13223]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS just added [Saved Queries for AWS Cloudwatch Logs Insights](https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-cloudwatch-logs-insights-now-allows-you-to-save-queries/). It would be nice to be able to manage and programatically generate saved queries using Terraform.

### New or Affected Resource(s)

* `aws_cloudwatch_query_definition`

### Potential Terraform Configuration

```hcl
resource "aws_cloudwatch_query_definition" "lambda_latency" {
  "logGroupNames": [
    "/aws/lambda/foo",
    "/aws/lambda/bar",
  ],
  "name": "/lambda/latency/foo_bar",
  "queryString": <<EOF
filter @type = "REPORT"
| stats avg(@duration), max(@duration), min(@duration) by bin(5m)
EOF
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-cloudwatch-logs-insights-now-allows-you-to-save-queries/
* https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutQueryDefinition.html
* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/logs/put-query-definition.html

**Comment by nerixim** [comment]
SDK support is available since v1.30.23 https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v13023-2020-05-07

[SDK Reference](https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatchlogs/#CloudWatchLogs.PutQueryDefinition)
