### ISSUE TITLE
Add support for "operation_name" on the aws_api_gateway_method resource

### ISSUE THREAD

**Issue by wperron** [hashicorp/terraform-provider-aws#13232]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To make it more convenient to use API Gateway's generated SDK with APIs created via Terraform, it would be interesting to add support for the "operation_name" option on the `aws_api_gateway_method` resource. The option is already supported by the putMethod and updateMethod actions on the API Gateway API so this is probably a very simple change to implement

### New or Affected Resource(s)

* aws_api_gateway_method

### Potential Terraform Configuration

```hcl
resource "aws_api_gateway_method" "list_foo" {
  authorization  = "NONE"
  http_method    = "GET"
  resource_id    = aws_api_gateway_rest_api.my_api.foo
  rest_api_id    = aws_api_gateway_rest_api.my_api.id
  operation_name = "listFoos"
}
```

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 3.24.0 of the Terraform AWS Provider, later this week. Thank you to @wperron for the implementation. 👍
