### ISSUE TITLE
aws_db_parameter_group resource and parameters that depends on each other 

### ISSUE THREAD

**Issue by komarEX** [hashicorp/terraform-provider-aws#13284]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.24
+ provider.aws v2.60.0
```

### Affected Resource(s)

* aws_db_parameter_group

### Terraform Configuration Files

```hcl
resource "aws_db_parameter_group" "mysql" {
    name   = format("%s-mysql-pg", lower(var.environment))
    family = var.mysql_family

    parameter {
        apply_method = "pending-reboot"
        name  = "enforce_gtid_consistency"
        value = "ON"
    }
    parameter {
        apply_method = "pending-reboot"
        name  = "gtid-mode"
        value = "ON"
    }
    parameter {...}
    parameter {...}
    parameter {...}
    parameter {...}
    (about 50 other parameters)
}
```

### Expected Behavior

Resource creation

### Actual Behavior

```
invalidparametervalue: having gtid-mode set to on requires that enforce_gtid_consistency is also set to on
```

### Steps to Reproduce

1. Create resource with many many different parameters set and try to set gtid as enabled
2. `terraform apply`

### Important Factoids

Ok so what's actually is happening here is that when you create a `aws_db_parameter_group` resource it will first create a default parameter group based on provided family (in my case it is mysql5.7) and then it will modify said group with provided values. When you have a lot of these parameters to set it will change them in batch of max 20 each time (https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_db_parameter_group.go#L263). Because of this limitation we are getting into trouble while setting `gtid-mode` and `enforce_gtid_consistency` because they are depended on each other. We are getting `gtid-mode` set **before** `enforce_gtid_consistency` is set (in different batches when `gtid-mode` is getting set first) so we are getting error from API that `having gtid-mode set to on requires that enforce_gtid_consistency is also set to on` essentially meaning that terraform fails here and resource isn't created as we want it to be.

We are trying to figure out how to workaround it without manual intervention into AWS console/API.

**Comment by komarEX** [comment]
Actually the proper code link based on provider version would be https://github.com/terraform-providers/terraform-provider-aws/blob/v2.60.0/aws/resource_aws_db_parameter_group.go#L263

**Comment by justinretzolk** [comment]
Hey @komarEX 👋 Thank you for taking the time to file this issue. Given that there's been a few Terraform and AWS Provider releases since you initially filed it, can you confirm if you're still experiencing this behavior?
