### ISSUE TITLE
Add data source for aws_rds_global_cluster

### ISSUE THREAD

**Issue by bagelbits** [hashicorp/terraform-provider-aws#13289]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I was hoping that we could add a data source for `aws_rds_global_cluster`, as there is a [Describe API](https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#RDS.DescribeGlobalClusters) exposed for it. 

### New or Affected Resource(s)

* aws_rds_global_cluster

### Potential Terraform Configuration

```hcl
data "aws_rds_global_cluster" "my_global_cluster" {
  global_cluster_identifier = "my-global-cluster"
}
```

**Comment by vikashkodati** [comment]
`$ terraform validate
Error: Invalid data source
  on network.tf line 85, in data "aws_rds_global_cluster" "am-k2k-prod-global":
  85: data "aws_rds_global_cluster" "am-k2k-prod-global" {
The provider provider.aws does not support data source
"aws_rds_global_cluster".`

Request this data source be added as well. thanks
