### ISSUE TITLE
SSH to my created ec2 instance on AWS

### ISSUE THREAD

**Issue by PrajjawalBanati** [hashicorp/terraform-provider-aws#13297]
### Terraform Version
Terraform v0.12.24
### Affected Resource(s)
- aws-ec2-instance
### Terraform Configuration Files

I created a module `main.tf` with the following code

```hcl
locals {
    region="${var.region}"  
}

resource "aws_vpc" "module_vpc" {
  cidr_block = "${var.vpc_cidr_block}"
}

resource "aws_key_pair" "ec2-key" {
  key_name="${var.key_name}"
  public_key=file("${var.file_path}")
}

resource "aws_subnet" "module_subnet" {
  vpc_id     = "${aws_vpc.module_vpc.id}"
  cidr_block = "${var.subnet_cidr_block}"
}

resource "aws_security_group" "all" {
  name        = "all"
  description = "Allow all inbound traffic"
  vpc_id      = "${aws_vpc.module_vpc.id}"

  ingress {
    description = "all VPC"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "allow_ssh"
  }
}

resource "aws_instance" "testInstance" {
  ami           = "${var.instance_image}"
  instance_type = "t2.micro"
  count = var.instance_count
  key_name="${aws_key_pair.ec2-key.key_name}"
  vpc_security_group_ids = ["${aws_security_group.all.id}"]  
  associate_public_ip_address=true
  subnet_id="${aws_subnet.module_subnet.id}"
  connection {
    host        = coalesce(self.public_ip,self.private_ip)
    type        = "ssh"
    user        = "ec2-user"
    password    = ""
    private_key = file("${var.private_file_path}")
  }
  }

```
And my root module configuration file is

```hcl
provider "aws" {
  region="us-east-1"
}

module "myec2" {
  source = "./modules/ec2-instance"
  instance_count = 2
  key_name="ec2-key"
  file_path="~/.ssh/service_terraform.pub"
  private_file_path="~/.ssh/service_terraform"
  vpc_cidr_block="192.168.0.0/16"
  subnet_cidr_block="192.168.1.0/24"
  instance_image="ami-0915e09cc7ceee3ab"
  instance_type="t2.micro"
}
```
### Debug Output

After `terraform apply` it's creating a vpc, a subnet, a security group with **ssh** enabled on port 22, and 2 ec2-instances attached to the security group created. 

### Panic Output

After creating ec2-instance I am not able to ssh into my instance
- Converted my private key `service-terraform` into `ec2-key.pem` to connect.
- Did `ssh -i "ec2-key.pem" ec2-user@public-ip`
- **Output Coming ** 
`Connection timed out`

### Expected Behavior

It should have shown me the terminal of the instance.

### Actual Behavior

- **Output Coming ** 
`Connection timed out`

### Steps to Reproduce

1. `terraform apply`

### References

https://gist.github.com/mingfang/4aba327add0807fa5e7f
https://stackoverflow.com/questions/56977357/why-cant-terraform-ssh-into-my-ec2-instance

**Comment by mmmorris1975** [comment]
There appears to be a bunch of configuration missing.

What is the route table setup for the subnet?
Does the subnet automatically assign a public IP to the instance on creation?
Are you attempting to access the instance over the internet, or via a private connection (like Direct Connect of VPN)?

**Comment by rick-masters** [comment]
There is no outbound connectivity specified. Here is the additional configuration required to make this work:
```
resource "aws_internet_gateway" "module_igw" {
  vpc_id = aws_vpc.module_vpc.id
}

resource "aws_default_route_table" "module_main_rt" {
  default_route_table_id = aws_vpc.module_vpc.default_route_table_id
  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.module_igw.id
  }
}
```

**Comment by PrajjawalBanati** [comment]
Thanks @rick-masters
