### ISSUE TITLE
Add namevaluesfilters package for resource filtering code

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#13304]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A number of AWS services, for example [EC2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Filtering.html#Filtering_Resources_CLI) and [RDS](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_Filter.html), support generic attribute filtering in APIs' resource `Describe` calls. The code to manipulate the data structures associated with resource filtering is nearly identical across services and is very amenable to code generation.

Following on from [this comment](https://github.com/terraform-providers/terraform-provider-aws/pull/13301#discussion_r424483800), it make senses to implement such generators in a new `namevaluesfilters` package.

One possible interface is:

```
type NameValuesFilters map[string][]string

func New(m map[string][]string) NameValuesFilters

func (NameValuesFilters) AutoscalingFilters() []*autoscaling.Filter
func (NameValuesFilters) DatabasemigrationserviceFilters() []*databasemigrationservice.Filter
func (NameValuesFilters) DocdbFilters() []*docdb.Filter
func (NameValuesFilters) Ec2Filters() []*ec2.Filter
func (NameValuesFilters) FsxFilters() []*fsx.Filter
func (NameValuesFilters) ImagebuilderFilters() []*imagebuilder.Filter
func (NameValuesFilters) LicensemanagerFilters() []*licensemanager.Filter
func (NameValuesFilters) NeptuneFilters() []*neptune.Filter
func (NameValuesFilters) RdsFilters() []*rds.Filter
func (NameValuesFilters) Route53resolverFilters() []*route53resolver.Filter
```

### Definition of Done

* `namevaluesfilters` code generation for all relevant services with passing unit tests
* Documentation on use of the generated code
* Instructions in the Contributing Guide on how to add `namevaluesfilters` support for new services
* Refactor at least one EC2 service data source to use the new pattern. Passing acceptance tests
* Refactor at least one non-EC2 service data to use the new pattern. Passing acceptance tests
* Open linked issue(s) to complete the refactoring work, ideally one per AWS service
* Open linked issue to use `namevaluefilters` in generated _GetTags_ code: #13745, #13868
* Look at `aws/internal/service/ec2/filter.go` and open a linked issue if there is an opportunity for simplification/reuse/refactoring

Related:

* #10688
* https://github.com/terraform-providers/terraform-provider-aws/issues/11994

**Comment by ewbankkit** [comment]
The code for data sources such as the `aws_vpc` data source could be changed to something like

```go
	// Filters based on attributes.
	nvf := namevaluesfilters.New(map[string]string{
		"cidr":            d.Get("cidr_block").(string),
		"dhcp-options-id": d.Get("dhcp_options_id").(string),
		"isDefault":       isDefaultStr,
		"state":           d.Get("state").(string),
	})
	// Filters based on keyvalue tags.
	nvf = nvf.Merge(namevaluesfilters.Ec2Tags(keyvaluetags.New(d.Get("tags").(map[string]interface{})).IgnoreAws().Map()))
	// Filters based on the custom filtering "filter" attribute.
	nvf = nvf.Merge(namevaluesfilters.New(d.Get("filter").(*schema.Set)))

	req.Filters = nvf.Ec2Filters()
```

**Comment by ewbankkit** [comment]
Data sources (other than EC2 resources) that can use this functionality:

* [ ] `aws_autoscaling_groups`
* [ ] `aws_db_cluster_snapshot`
* [ ] `aws_db_event_categories`
* [ ] `aws_db_instance`
* [ ] `aws_db_snapshot`
* [ ] `aws_route53_resolver_rule`
* [ ] `aws_route53_resolver_rules`

**Comment by bflad** [comment]
Looks like [AWS Go SDK v1.33.5 includes similar functionality for `service/secretsmanager`](https://github.com/aws/aws-sdk-go/pull/3416/files#diff-5ca804d816a3b67a36dcf72c88da16c5R478) 🎉

**Comment by ewbankkit** [comment]
Yes, it's effectively the same functionality although the `Name` field is called `Key` but the code generator can handle that.
I'll add the `aws_secretsmanager_secret` data source to the list above.
Requires https://github.com/terraform-providers/terraform-provider-aws/pull/14000.

**Comment by ewbankkit** [comment]
I decided not to add the `secretsmanager` service to the generated code list as the fact that the _name_ field is `Key` implies we cannot use the standard

```go
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"name": {
					Type:     schema.TypeString,
					Required: true,
				},

				"values": {
					Type:     schema.TypeSet,
					Required: true,
					Elem: &schema.Schema{
						Type: schema.TypeString,
					},
				},
			},
		},
```

definition for the `filter` attribute.
