### ISSUE TITLE
SSM document association parameters don't support arrays

### ISSUE THREAD

**Issue by awilkins** [hashicorp/terraform-provider-aws#13306]
AWS provider 2.61

See : https://github.com/terraform-providers/terraform-provider-aws/issues/1889

When using an array for a parameter, you receive

```
Inappropriate value for attribute "parameters": element "dnsIpAddresses":
string required.
```

This is a blocker for using this resource with e.g. `aws:domainJoin`, which takes an array of IP address strings.

```hcl
resource "aws_ssm_association" "join" {
  name = aws_ssm_document.joiner.name
  targets {
    key    = "InstanceIds"
    values = [aws_instance.domain_controller.id]
  }
  parameters = {
    directoryId    = aws_directory_service_directory.ad.id
    directoryName  = aws_directory_service_directory.ad.name
    directoryOU    = local.ou
    dnsIpAddresses = aws_directory_service_directory.ad.dns_ip_addresses
  }
}
```

The original thread describes the problem well but is auto-locked. However, this is now eminently possible in 0.12

**Comment by undecomposed** [comment]
I appear to have the same thing in the ssm document itself.
