### ISSUE TITLE
[BUG] Cannot replace Virtual Private Gateway route with Transit Gateway route in aws_route resource

### ISSUE THREAD

**Issue by snovikov** [hashicorp/terraform-provider-aws#13302]
When trying to replace existing route pointing to VGW (Virtual Private Gateway) with TGW (Transit Gateway) error is thrown.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform version
Terraform v0.12.24
+ provider.aws v2.61.0
```

### Affected Resource(s)

* aws_route

### Terraform Configuration Files

```hcl
resource "aws_route" "this" {
  for_each = {
    for route in local.routes_in_tables : "${route.table_id}.${route.dest_cidr_block}" => route...
  }

  provider = aws.satellite

  destination_cidr_block = each.value[0].dest_cidr_block
  transit_gateway_id     = local.transit_gateway_id
  route_table_id         = each.value[0].table_id

  depends_on = [aws_ec2_transit_gateway_vpc_attachment.this]
}
```

### Debug Output

When run apply:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_route.this["rtb-aaaabbbb.10.10.10.0/24"] will be updated in-place
  ~ resource "aws_route" "this" {
        destination_cidr_block = "10.10.10.0/24"
        gateway_id             = "vgw-0aaaabbbbccccdddd"
        id                     = "r-rtb-aaaabbbb1111222233"
        origin                 = "CreateRoute"
        route_table_id         = "rtb-aaaabbbb"
        state                  = "active"
      + transit_gateway_id     = "tgw-0aaaabbbbccccdddd"

        timeouts {}
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behavior

VGW route is replaced with TGW route

### Actual Behavior

Error message:
```
Error: more than 1 target specified. Only 1 of gateway_id, egress_only_gateway_id, nat_gateway_id, instance_id, network_interface_id or vpc_peering_connection_id is allowed.
```

### Steps to Reproduce

1. `terraform import 'aws_route.this["rtb-aaaabbbb.10.10.10.0/24"]' rtb-aaaabbbb_10.10.10.0/24`
2. `terraform apply`

### References

Similar to
* #13079

**Comment by ewbankkit** [comment]
Similar:
* https://github.com/terraform-providers/terraform-provider-aws/issues/684
* https://github.com/terraform-providers/terraform-provider-aws/issues/12631
* https://github.com/terraform-providers/terraform-provider-aws/issues/13079
