### ISSUE TITLE
Strange aws_route53_record for certificate validation, when hosted zone isn't managed by terraform

### ISSUE THREAD

**Issue by Cosiek** [hashicorp/terraform-provider-aws#13349]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.17
+ provider.aws v2.59.0
```

### Affected Resource(s)

* aws_route53_record
* aws_acm_certificate_validation

### Terraform Configuration Files

```hcl
locals {
  domain = "tp-dev-1.example.com"
}

# Certificate =========================

resource "aws_acm_certificate" "cert" {
  domain_name = local.domain
  validation_method = "DNS"

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_route53_record" "cert_validation" {
  name     = aws_acm_certificate.cert.domain_validation_options[0].resource_record_name
  type     = aws_acm_certificate.cert.domain_validation_options[0].resource_record_type
  zone_id  = "Z0466666666666666666Z"
  ttl      = 60

  records  = [aws_acm_certificate.cert.domain_validation_options[0].resource_record_value]
}

resource "aws_acm_certificate_validation" "default" {
  depends_on = [aws_route53_record.cert_validation]
  certificate_arn = aws_acm_certificate.cert.arn
  validation_record_fqdns = [
    aws_route53_record.cert_validation.fqdn
  ]
}
```

### Expected Behavior

Terraform should create a aws_route53_record for the certificate validation.
This record should look something like `_57e311c3741f1282a6ed84c8e5e81c36.tp-dev-1.example.com`

### Actual Behavior

Terraform creates a aws_route53_record for the certificate validation, that looks like this:
`_57e311c3741f1282a6ed84c8e5e81c36.tp-dev-1.example.com.tp-dev-1.example.com.`
Notice that it is in fact the right record, but concated with hosted zones domain.

Then later aws_acm_certificate_validation.default complains that validation record is missing:
```apex
aws_route53_record.cert_validation: Creation complete after 45s [id=Z04696662WXI8H25F0HOZ__57e311c3741f1282a6ed84c8e5e81c36.tp-dev-1.example.com._CNAME]
aws_acm_certificate_validation.default: Creating...

Error: 1 error occurred:
	* missing tp-dev-1.example.com DNS validation record: _57e311c3741f1282a6ed84c8e5e81c36.tp-dev-1.example.com



  on main.tf line 25, in resource "aws_acm_certificate_validation" "default":
  25: resource "aws_acm_certificate_validation" "default" {

```

### Steps to Reproduce

1. Create an route53 hosted zone manually, without using terraform
2. Pass said hosted zones id to aws_route53_record.cert_validation.zone_id
3. `terraform apply`

### Important Factoids

The hosted zone I'm using is created dynamically, and I only receive its id.
The same code works as expected if hosted zone is created by terraform.

### References

* #0000

**Comment by archoversight** [comment]
As a note, I am using a [route53_zone](https://www.terraform.io/docs/providers/aws/d/route53_zone.html) data provider to fetch the hosted zone, and then grab the `zone_id` for the route53 record for ACM validation and that seems to be working okay (my zone is not managed by terraform at all, just certain records).

Maybe that could be a work-around that works for you too?

**Comment by justinretzolk** [comment]
Hey @Cosiek 👋 Thank you for filing this issue. Given that there's been a number of Terraform and AWS Provider releases since you initially filed it, can you confirm whether you're still experiencing this?

**Comment by Cosiek** [comment]
Hi @justinretzolk 
I no longer work on that project and have no way of checking if it's still an issue.

**Comment by justinretzolk** [comment]
Thank you for following up. Given that's the case, we're going to go ahead and close this issue out. If anyone comes across this issue and is experiencing similar behavior, please open a new issue to let us know.
