### ISSUE TITLE
Unable to update db_parameter_group's shared_preload_library to use two preload libraries

### ISSUE THREAD

**Issue by omada-jacob-smith** [hashicorp/terraform-provider-aws#13354]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

$ terraform -v
Terraform v0.12.20
+ provider.aws v2.49.0

### Affected Resource(s)

aws_db_parameter_group (resource)

### Terraform Configuration Files

```
resource "aws_db_parameter_group" "db_params" {
  name   = "foo"
  family = "postgres11"

  parameter {
    name         = "shared_preload_libraries"
    value        = "pglogical,pg_stat_statements"
    apply_method = "pending-reboot"
  }
}
```

### Expected Behavior

I should be able to use both pg_stat_statements and pglogical

### Actual Behavior

The parameter group seems to be stuck on pg_stat_statements and only pg_stat_statements

### Steps to Reproduce

First, we were only using `"pglogical"` and that worked, then we updated the parameter to be `"pglogical,pg_stat_statements"`.
We ran a plan/apply and then only `pg_stat_statements` was in the parameter group.
I tried setting it back to `pglogical` only and it still is `pg_stat_statements`.
The only way that I could get the values to work and for terraform to be content is to manually update the AWS UI. This has happened on four different databases/pg groups in exactly the same way.

### Important Factoids

Not that I know of.

**Comment by justinretzolk** [comment]
Hey @omada-jacob-smith 👋 Thank you for taking the time to file this issue. Given that there's been a number of Terraform and AWS Provider releases since you initially filed this, can you confirm whether you're still experiencing the same behavior?

**Comment by rvmey** [comment]
I upgraded the aws provider version 4.13 and it still didn’t set the value correctly.  

My shared_preload_libraries value is still "pg_stat_statements" but it should be "pgaudit,pg_stat_statements"

    {
      name          = "shared_preload_libraries"
      value         = "**pgaudit,pg_stat_statements**"
      apply_method  = "pending-reboot"
    },
