### ISSUE TITLE
Warning: Quoted references & Interpolation-only expressions are deprecated

### ISSUE THREAD

**Issue by oke-py** [hashicorp/terraform-provider-aws#13369]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
terraform -v
Terraform v0.12.25
+ provider.aws v2.60.0
```
### Affected Resource(s)

* aws_config_config_rule (probably many other resources)

### Terraform Configuration Files

```hcl
resource "aws_config_config_rule" "r" {
  name = "example"

  source {
    owner             = "AWS"
    source_identifier = "S3_BUCKET_VERSIONING_ENABLED"
  }

  depends_on = ["aws_config_configuration_recorder.foo"]
}

resource "aws_config_configuration_recorder" "foo" {
  name     = "example"
  role_arn = "${aws_iam_role.r.arn}"
}

resource "aws_iam_role" "r" {
  name = "my-awsconfig-role"

  assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "config.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
POLICY
}

resource "aws_iam_role_policy" "p" {
  name = "my-awsconfig-policy"
  role = "${aws_iam_role.r.id}"

  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
        "Action": "config:Put*",
        "Effect": "Allow",
        "Resource": "*"

    }
  ]
}
POLICY
}
```

This is the same as the example [here](https://www.terraform.io/docs/providers/aws/r/config_config_rule.html#aws-managed-rules).

### Debug Output

https://gist.github.com/oke-py/7342ceba7e642a7b430cd89bca876062

### Expected Behavior

The example does not output warnings.

### Actual Behavior

The example outputs warnings described in the gist.

https://github.com/terraform-providers/terraform-provider-aws/blob/14c139d67eb1129c790d2bcd516ef7e40b440eac/website/docs/r/config_config_rule.html.markdown#L30

should be `  depends_on = [aws_config_configuration_recorder.foo]`.

https://github.com/terraform-providers/terraform-provider-aws/blob/14c139d67eb1129c790d2bcd516ef7e40b440eac/website/docs/r/config_config_rule.html.markdown#L35

should be `  role_arn = aws_iam_role.r.arn`.

https://github.com/terraform-providers/terraform-provider-aws/blob/14c139d67eb1129c790d2bcd516ef7e40b440eac/website/docs/r/config_config_rule.html.markdown#L60

should be `  role = aws_iam_role.r.id`.

Or, shouldn't they be fixed for backward compatibility?

### Steps to Reproduce

1. `terraform validate`

**Comment by DrFaust92** [comment]
Quoted references & Interpolation-only expressions are deprecated are deprecated after terraform 0.11.x
