### ISSUE TITLE
Support for AWS Kendra

### ISSUE THREAD

**Issue by mrchief** [hashicorp/terraform-provider-aws#13367]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for AWS Kendra https://aws.amazon.com/kendra/

### New or Affected Resource(s)

* aws_kendra_index (#24920)
* aws_kendra_experience (https://github.com/hashicorp/terraform-provider-aws/pull/25315)
* aws_kendra_faq (https://github.com/hashicorp/terraform-provider-aws/pull/25515)
* aws_kendra_thesaurus (#25199) 
* aws_kendra_query_suggestion_block_list (#25198)

### New or Affected Data Sources
* aws_kendra_index (#25473)
* aws_kendra_faq (https://github.com/hashicorp/terraform-provider-aws/pull/25523)
* aws_kendra_thesaurus (#25555)

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by rmmathik** [comment]
Hi Tam -- is anyone working on this? Please confirm as we are looking to work on this service and make it available for the AWS provider. Help please.

**Comment by nodomain** [comment]
+1

**Comment by jrodz-ak** [comment]
+1

**Comment by jfcm-td** [comment]
+1

**Comment by ParsadInformatics** [comment]
Are there any updates regarding adding Kendra supports?

**Comment by breathingdust** [comment]
Hi all 👋 Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!
