### ISSUE TITLE
Cannot import existing aws_cloudwatch_log_group

### ISSUE THREAD

**Issue by aviau** [hashicorp/terraform-provider-aws#13377]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24

Provider version 2.62.0

### Affected Resource(s)

* aws_cloudwatch_log_group

I cannot seem to import an existing log group. I keep getting the error:
```
Error: Cannot import non-existent remote object
```

However, creating the log group gives the error:
```
The specified log group already exists:  The CloudWatch Log Group 'censored' already exists.
```

Creating a data resource with the same log group name works without issue.

I tried to work arround this by deleting the log group and have terraform create it, but it is the log group associated with my eks cluster and it is automatically recreated so fast that terraform does not have the time to create it.

**Comment by knjname** [comment]
Reproduced with Terraform: `0.12.29`, and AWS provider: `3.8.0`.

**Comment by Jeinhaus** [comment]
Just a quick addition:

I tried importing a log group created by `eksctl` named `aws/eks/staging/cluster`.
When trying to create that resource it fails with 
```sh
Error: Creating CloudWatch Log Group failed: InvalidParameterException: Log groups starting with AWS/ are reserved for AWS. 'aws/eks/staging/cluster'
```

Maybe the failing import is connected with the `aws` namespace?

**Comment by ewbankkit** [comment]
@Jeinhaus Do you run `terraform import aws/eks/staging/cluster` or `terraform apply` a configuration with `aws_cloudwatch_log_group.name` equal to `aws/eks/staging/cluster`?
