### ISSUE TITLE
aws_cloudfront_distribution could be created without viewer_certificate block

### ISSUE THREAD

**Issue by Mallear** [hashicorp/terraform-provider-aws#13374]
When creating a aws_cloudfront_distribution resource a viewer_certificate block is required while AWS documentation says the opposite.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.24
+ provider.aws v2.10.0
```

### Affected Resource(s)

* aws_cloudfront_distribution 

### Terraform Configuration Files

```hcl
resource "aws_cloudfront_distribution" "cms_distribution" {
  origin {
    domain_name = var.loadbalancer_hostname
    origin_id   = local.origin_id

    custom_origin_config {
      http_port              = 80
      https_port             = 443
      origin_protocol_policy = "match-viewer"
      origin_ssl_protocols   = ["SSLv3", "TLSv1.1", "TLSv1.2"]
    }
  }

  enabled         = true
  is_ipv6_enabled = true

  logging_config {
    include_cookies = false
    bucket          = aws_s3_bucket.cf_log_bucket.bucket_domain_name
  }

  aliases = ["mydomain.com"]

  default_cache_behavior {
    allowed_methods  = ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = local.origin_id

    forwarded_values {
      query_string = false
      cookies {
        forward = "all" # To replace by whitelist
      }
    }
    compress               = true
    viewer_protocol_policy = "allow-all"
  }

  price_class = "PriceClass_All"

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }
}
```

### Debug Output

```
Error: "viewer_certificate": required field is not set
```

### Expected Behavior

Cloudfront distribution should have been created.

### Actual Behavior

AWS Terraform provider fails because of viewer_certificate block missing.

### Steps to Reproduce

1. `terraform apply`

### References

- [AWS CreateDistribution APIReference](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_DistributionConfig.html#cloudfront-Type-DistributionConfig-ViewerCertificate)

**Comment by ewbankkit** [comment]
[Required fields for creating and updating distributions](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-overview-required-fields.html).
