### ISSUE TITLE
Feature: Implement data source for EKS Manage Node Groups

### ISSUE THREAD

**Issue by zot24** [hashicorp/terraform-provider-aws#13442]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At the minute there is no data source for EKS Manage Node Groups https://www.terraform.io/docs/providers/aws/r/eks_node_group.html only the resource, will be interesting to have the information from that created resource for different scenarios.

For example when building the `aws-auth` from a different plan than the one creating the node groups https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/aws_auth.tf#L62 you can gather all the information from https://docs.aws.amazon.com/cli/latest/reference/eks/describe-nodegroup.html to build the `map_role` using the specific `role_arn` from `nodeRole` set to your node group

### New or Affected Resource(s)

* data.aws_eks_node_group
* data.aws_eks_node_group_names

### Potential Terraform Configuration

```hcl
data "aws_eks_node_group_names" "example" {
  cluster_name = "example"
}

data "aws_eks_node_group" "example" {
  for_each = data.aws_eks_node_group_names.example.names
  cluster_name    = "example"
  node_group_name = each.value
}
```

### References

* https://docs.aws.amazon.com/cli/latest/reference/eks/list-nodegroups.html
* https://docs.aws.amazon.com/cli/latest/reference/eks/describe-nodegroup.html

**Comment by zot24** [comment]
I'm willing to work on this as it's something we need at the minute, some feedback and thoughts will be appreciated

**Comment by DonBower** [comment]
nearly a year old, and the PR is still open?

**Comment by zot24** [comment]
Hey @DonBower the individual contributor for the PR related to this issue, I believe I have pending to do some modifications they are recommending us to do on this comment https://github.com/hashicorp/terraform-provider-aws/pull/13564#issuecomment-675724446

Maybe that's why it's being stuck in that state, will try to find some time to address those and see if that move things forward as well as upgrade from master

**Comment by zot24** [comment]
Done @DonBower I have updated the PR with the requested changes 👍🏽 cc @bflad

**Comment by DonBower** [comment]
Thanks, @zot24 Can't wait to use it!

**Comment by DonBower** [comment]
@blflad do you know when the  [PR for this](https://github.com/hashicorp/terraform-provider-aws/pull/13564) will be merged?

**Comment by DonBower** [comment]
@zot24 @bflad Still looking forward to this feature...

**Comment by ankitjhingan** [comment]
+1 for having data-source of aws_eks_node_group....
