### ISSUE TITLE
AWS example: ecs-alb

### ISSUE THREAD

**Issue by amirdolev** [hashicorp/terraform-provider-aws#13454]
When I apply the ecs-alb example for AWS I get the following errors:

 Error: Incorrect attribute value type

  on main.tf line 46, in resource "aws_autoscaling_group" "app":
  46:   vpc_zone_identifier  = ["${aws_subnet.main.*.id}"]
    |----------------
    | aws_subnet.main is tuple with 2 elements

Inappropriate value for attribute "vpc_zone_identifier": element 0: string
required.

Error: Incorrect attribute value type

  on main.tf line 301, in resource "aws_alb" "main":
 301:   subnets         = ["${aws_subnet.main.*.id}"]
    |----------------
    | aws_subnet.main is tuple with 2 elements

Inappropriate value for attribute "subnets": element 0: string required.

Any idea how to fix this?

**Comment by justinretzolk** [comment]
Hey @amirdolev 👋 Thank you for taking the time to file this issue. Given that there's been a few Terraform and AWS provider releases since you initially filed it, can you confirm if you're still experiencing this?

**Comment by amirdolev** [comment]
Sorry, I am no longer working in this environment.

**Comment by justinretzolk** [comment]
Thank you for following up. Given that and the age of the issue (and the number of Terraform and AWS provider releases since), I'm going to go ahead and close this issue for now. If anyone comes across this issue again in the future and feels it needs to be looked at again, please do let us know.
