### ISSUE TITLE
service/codebuild: Address TestAccAWSCodeBuildProject failure

### ISSUE THREAD

**Issue by anGie44** [hashicorp/terraform-provider-aws#13450]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, the following consistent test failure occurs in AWSCodeBuildProject acceptance testing which requires manual intervention and may potentially be skipped.
```
--- FAIL: TestAccAWSCodeBuildProject_Source_Auth (11.50s)
    testing.go:683: Step 1 error: errors during apply:
        
        Error: Error creating CodeBuild project: InvalidInputException: No Access token found, please visit AWS CodeBuild console to connect to GitHub
```

### New or Affected Resource(s)

* aws_resource_codebuild_project

**Comment by bflad** [comment]
`TestAccAWSCodeBuildProject_VpcConfig` was fixed awhile ago -- `TestAccAWSCodeBuildProject_Source_Auth` should be hidden behind an environment variable and skipped since it requires manual AWS Console interaction.

**Comment by bflad** [comment]
Just wanted to potentially use the helpers from https://github.com/hashicorp/terraform-provider-aws/pull/17197 instead of just rolling yet another thing to refactor before submitting this.
