### ISSUE TITLE
Vgw in dxg association proposal not found

### ISSUE THREAD

**Issue by rsmolins** [hashicorp/terraform-provider-aws#13455]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I'm trying to associate VGW on one account to DXGW on another account. Unfortunately I got error message that VGW can not be found. 

### Terraform Version
Terraform v0.12.24
+ provider.aws v2.62.0

### Affected Resource(s)

* aws_dx_gateway_association

### Terraform Configuration Files

Follow documentation example
https://github.com/terraform-providers/terraform-provider-aws/blob/master/examples/dx-gateway-cross-account-vgw-association/main.tf

### Debug Output
https://gist.github.com/rsmolins/94034dd0d6cd201f8d491a2143f4a3d0

### Expected Behavior
Direct Connect gateway association proposal is accepted on second account

### Actual Behavior
Direct Connect gateway association proposal fails with status 
`Error: error accepting Direct Connect gateway association proposal: DirectConnectClientException: The Virtual Gateway in the Direct Connect Gateway Association Proposal  [id_here] not found`

### Steps to Reproduce

1. terragrunt apply

**Comment by jerem991** [comment]
This issue seems to be a false positive.

Had the same issue (provider.aws v2.70.0), but it was because i misconfigured the region of the second aws provider (if you follow the tutorial).

**Comment by alithya-us** [comment]
Agree with jerem991.  I experienced the same issue - make sure the first and second provider are set to the region where the VGW is deployed.
