### ISSUE TITLE
RAM Resource Share Principal Association cannot be deleted while in ASSOCIATING state

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#13458]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource

* `aws_ram_principal_association`
* `aws_ram_resource_association` (possibly)

### Description

During an acceptance test run, got the following error:

```
error disassociating RAM Resource Share (arn:aws:ram:us-west-2:123456789012:resource-share/32c82ac0-74b3-4290-8ec8-4ef9a74408b1) Principal Association (210987654321): InvalidStateTransitionException: At least one of the associations in the resource share is in ASSOCIATING status.
```

The delete function for RAM associations should wait to be in `ASSOCIATED`, or `FAILED` state before attempting deletion. If the state is `DISASSOCIATING`, it should skip to the final waiting step.

**Comment by bosco-rodrigues** [comment]
Hi team, 

We've just encountered this exact same problem and we can't seem to get past it. 

Steps to reproduce: 

1. Create a Resource share with an invalid principal (wrong account id in our case )
2. The principal association then fails. 
3. You won't be able to run Terraform from there on. 

I've tried deleting it from the Terraform state file.  
I still can't seem to get past the error. 

Many thanks,
-Bosco.

**Comment by rgooler** [comment]
The delete also fails if the state is `ASSOCIATING` - IE if the accepting role hasn't said yes yet.

**Comment by dbergman24** [comment]
We just ran into this error - is there a workaround?

**Comment by djgraves** [comment]
I put in the account owner ID in this field as a ram_principal and it didn't like that at all, I removed the account ID but terraform won't run anymore saying:

`Error: error reading RAM Resource Share (arn:aws:ram:us-east-2:XXXXXXXXXXXX:resource-share/c3610023-32a8-4895-9940-7180da0b1435) Principal Association (XXXXXXXXXXXX), status not associating or associated: FAILED`

I tried to manually delete this resource share from AWS thinking the state file would pick up on this and try to recreate it with the updated code, but, it just keeps hitting me with this same error message over and over. Even if I try to delete all of my transit gateway resources (the reason I was using RAM) it just doesn't matter. Terraform will not do anything anymore.

**Comment by djgraves** [comment]
After waiting about 4 hours the only command that I ran while attempting to pull the terraform state down to my local machine (which didn't work) was **terraform init -migrate-state**, i'm not sure what this did, or if perhaps just waiting 4 hours after I deleted the RAM Resource Share that was causing me issues finally resolved itself? Either way, my terraform state is fine now. Just wanted to post this update.

**Comment by peterhriser** [comment]
Follow up on this for people who may find this later, this is an issue with AWS maintaining a deleted resource share for longer than it should. New state or migrating it did not work for me either.

**Comment by julian-berks-2020** [comment]
> Follow up on this for people who may find this later, this is an issue with AWS maintaining a deleted resource share for longer than it should. New state or migrating it did not work for me either.
> 
> running `terraform state rm <BAD_OBJECT>` worked for me.

I had one share in a failed state. Removed the code that tried to create it and 
ran `terraform state rm <BAD_OBJECT> .
Apply ran fine. I assume failed shares are eventually dropped from AWS.
