### ISSUE TITLE
private_key in provider_details should be marked as sensitive for aws_cognito_identity_provider

### ISSUE THREAD

**Issue by jmetzmeier** [hashicorp/terraform-provider-aws#13460]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24

### Affected Resource(s)

* aws_cognito_identity_provider

### Expected Behavior

When running a plan or apply the value for `provider_details.private_key` should not be displayed in plain text.

### Actual Behavior

The ssh private key is displayed in plain text in the plan/apply output.

### Steps to Reproduce

1. Run `terraform apply` with a aws_cognito_identity_provider resource with `provider_details.private_key` set.

**Comment by cc-stjm** [comment]
In case it helps anyone else, I've written an awk script that filters out the private key. Works in busybox awk (the one that's in the terraform docker image). 

Usage `terraform plan | awk -f mask_private_key.awk`

```awk
BEGIN {
    mask=0
}
/END PRIVATE KEY/ { mask = 0 }
{
    if(mask == 0){
        print
    }else{
        if(match($0, /^\s*/)) {
            # Will always match, might be zero width
            # Copy the spaces, then print [Masked]
            print substr($0, RSTART, RLENGTH) "[Masked]"
        }
    }
}
/BEGIN PRIVATE KEY/ { mask=1 }
```

I'm sure that smaller awk scripts can be written, but it works for me to keep private keys out of CI logs
