### ISSUE TITLE
force_new_deployment argument for aws_ecs_service resources doesn't work with codedeploy

### ISSUE THREAD

**Issue by e-moshaya** [hashicorp/terraform-provider-aws#13473]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The change to introduce force_new_deployment argument for resource/aws_ecs_service as part of v2.63.0 of this provider  does not work with CODE_DEPLOY deployment controller. I get the following error with force_new_deployment set to true and a CODEDEPLOY deployment controller:

`
Error: Error updating ECS Service (arn:aws:ecs::xxxxx:service/cluster/service): InvalidParameterException: Unable to update network parameters on services with a CODE_DEPLOY deployment controller. Use AWS CodeDeploy to trigger a new deployment.
`

**Note:** _force_new_deployment works fine when enabled through the UI with the CODEDEPLOY deployment controller_

### New or Affected Resource(s)

* resource/aws_ecs_service

### References

* https://github.com/terraform-providers/terraform-provider-aws/pull/13376

**Comment by bflad** [comment]
This could be related to https://github.com/terraform-providers/terraform-provider-aws/issues/8005 in the sense that we may need to omit sending the networking configuration during updates for that deployment type. It would be helpful to see the (redacted if necessary) 
 planned difference and relevant configuration so we can reproduce this issue.

**Comment by e-moshaya** [comment]
Hi,

Please see below with the missing redacted info:

`Error: Error updating ECS Service (arn:aws:ecs:eu-west-1:126907643513:service/ecs-cluster/ecs-service): InvalidParameterException: Unable to update network parameters on services with a CODE_DEPLOY deployment controller. Use AWS CodeDeploy to trigger a new deployment.`

**Comment by jedipunkz** [comment]
Hi,

We have the same issue, and We've noticed that the problem only occurs when the CodeDeploy process is running.

**Comment by przemek1990** [comment]
Any update on this issue?
