### ISSUE TITLE
Add `tags` attribute to `aws_iam_user` data source

### ISSUE THREAD

**Issue by Omicron7** [hashicorp/terraform-provider-aws#13470]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I attempted to use `tags` from an `aws_iam_user` data source and found that they were missing. The `aws iam get-user` response already includes the tags, so it shouldn't be too difficult to expose them in the data source. The `aws_iam_role` data source already does this.

This would be extremely useful as values from tags could be used in other terraform configuration.

### New or Affected Resource(s)

* aws_iam_user data source

### Potential Terraform Configuration

```hcl
data "aws_iam_user" "tony" {
  name = "tony.stark"
}

resource "aws_s3_bucket" "bucket" {
  bucket = "ironman-docs"
  tags = {
    contact = data.aws_iam_user.tony.tags.email_address
  }
}
```

### References

* #13287

**Comment by Omicron7** [comment]
@bflad Any way to get this in an upcoming release, or whats the normal process to get these small, non-breaking enhancements moving forward?
Thanks.

**Comment by anGie44** [comment]
Thanks again @Omicron7 🚀 - expect this feature out in the upcoming Terraform AWS Provider, likely to be released on Thursday.
