### ISSUE TITLE
aws_iam_instance_profile.id returns name instead of id

### ISSUE THREAD

**Issue by upsilon2gamma** [hashicorp/terraform-provider-aws#13480]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.25
+ provider.aws v2.63.0
```

### Affected Resource(s)

* aws_iam_instance_profile

### Terraform Configuration Files

```hcl
resource "aws_iam_role" "test_role" {
  name = "test_role"
  //...
}

resource "aws_iam_instance_profile" "test_profile" {
  name = "test_profile"
  role = aws_iam_role.test_role.name
}

// fetch the profile resource by `data`
data "aws_iam_instance_profile" "test_profile" {
  name = "test_profile"
}

output "test_profile_id_when_resource" {
  value = aws_iam_instance_profile.test_profile.id
}

output "test_profile_name_when_resource" {
  value = aws_iam_instance_profile.test_profile.name
}

output "test_profile_id_when_data" {
  value = data.aws_iam_instance_profile.test_profile.id
}
```

### Expected Behavior

```
test_profile_id_when_resource = <PROFILE_ID>
test_profile_name_when_resource = test_profile
test_profile_id_when_data = <PROFILE_ID>
```

### Actual Behavior

```
test_profile_id_when_resource = test_profile
test_profile_name_when_resource = test_profile
test_profile_id_when_data = <PROFILE_ID>
```

### Steps to Reproduce

1. `terraform apply`

### References

* https://www.terraform.io/docs/providers/aws/r/iam_instance_profile.html#id

**Comment by DrFaust92** [comment]
Hey @upsilon2gamma  the `id` attribute doesn't necessarily mean its corresponds to the AWS resource ID. in this case to get the instance profile id use `unique_id`. in your case it would be ` aws_iam_instance_profile.test_profile.unique_id`
