### ISSUE TITLE
SSM Document rename appears to work but fails silently

### ISSUE THREAD

**Issue by parmouraly** [hashicorp/terraform-provider-aws#13483]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

terraform `0.12.18`
aws-provider: `2.63.0`

### Affected Resource(s)

* aws_ssm_document

### Terraform Configuration Files

```hcl
resource "aws_ssm_document" "command" {
  name            = "TestCommand1"
  document_type   = "Session"
  document_format = "JSON"
}
```

Replaced by

```hcl
resource "aws_ssm_document" "command" {
  name            = "TestCommand2"
  document_type   = "Session"
  document_format = "JSON"
}
```

### Expected Behavior

`terraform apply` shows expected diff and after successful apply, the name of the resource is actually modified.

### Actual Behavior

`terraform apply` shows expected diff (in place rename of resource) and after successful apply, the name of the resource on AWS is actually unchanged.

### Steps to Reproduce

1. Create an SSM document using terraform code similar to above
2. Change the name in the code
3. `terraform apply`
4. Apply is successful
5. Check actual document name on AWS, it's unchanged
6. Alternatively if you try to re-apply you will get the same diff because nothing actually changed on AWS.

**Comment by bflad** [comment]
The fix (requiring `aws_ssm_document` resource replacement when changing the `name` argument) has been merged and will release with version 3.29.0 of the Terraform AWS Provider, likely later today.
