### ISSUE TITLE
 CloudFront Distribution: InvalidViewerCertificate: The specified SSL certificate doesn't exist, isn't

### ISSUE THREAD

**Issue by abiodunjames** [hashicorp/terraform-provider-aws#13489]
I'm currently having an issue requesting a wildcard certificate that works with CloudFront. 
* The certificate was issued in `us-east-1` by the same terraform code
* The certificate was successfully provisioned but does not work with cloudformation.
I get this error

```
creating CloudFront Distribution: InvalidViewerCertificate: The specified SSL certificate doesn't exist, isn't in us-east-1 region, isn't valid, or doesn't include a valid certificate chain.
	status code: 400, request id: b6187fb9-539f-4c40-bdd2-bdec5af7ab2e[0m

 on .terraform/modules/cdn/main.tf line 193, in resource "aws_cloudfront_distribution" "default":
 193: resource "aws_cloudfront_distribution" "default" 
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24

### Affected Resource(s)

* aws_cloudfront_distribution

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

https://gist.github.com/abiodunjames/8fed4004cffd0c9f07adb067c460edc7

### Expected Behavior

Certificate provisoning should work with cloudfront

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by alex-bes** [comment]
hi, @abiodunjames! did you manage to work this around? thanks in advance!

**Comment by justinretzolk** [comment]
Hey @abiodunjames 👋 Thank you for taking the time to file this. Given that there's been a few Terraform and AWS Provider releases since you initially filed it, can you confirm whether you're still experiencing this?

**Comment by abiodunjames** [comment]
Hey @justinretzolk,
I eventually got this fixed. It was as a result of a rule applied on the AWS Organisation Account level. The central account that manages all other accounts enforced a rule to make requests for certain resources in `eu-central-1` only. This was rectified and it worked.

**Comment by justinretzolk** [comment]
Thank you for following up and letting us know! Given that's the case, I'm going to go ahead and close this issue out.
