### ISSUE TITLE
  Error: error creating Kinesis Firehose Delivery Stream Firehose record format conversion is not available in the current region.

### ISSUE THREAD

**Issue by anoora17** [hashicorp/terraform-provider-aws#13499]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.13

### Affected Resource(s)

resource "aws_kinesis_firehose_delivery_stream" "kinesis_firehose" {
  destination = "extended_s3"
  extended_s3_configuration {
    bucket_arn = var.destinationBucketArn
    cloudwatch_logging_options {
      enabled = true
      log_group_name = aws_cloudwatch_log_group.kinesis_firehose_log_destination_group.name
      log_stream_name = aws_cloudwatch_log_stream.kinesis_firehose_log_destination_stream.name
    }
    prefix = local.s3BucketPrefix
    role_arn = module.IAMRolesKinesisFirehose.firehose_delivery_role_arn
  }
  kinesis_source_configuration {
    kinesis_stream_arn = aws_kinesis_stream.kinesis_stream.arn
    role_arn = module.IAMRolesKinesisFirehose.firehose_delivery_role_arn
  }
  name = "name-kinesis-firehose"
  })
}
* aws_XXXXX

### Debug Output
Error: error creating Kinesis Firehose Delivery Stream: InvalidArgumentException: Firehose record format conversion is not available in the current region.

1. `terraform apply`
Error: error creating Kinesis Firehose Delivery Stream: InvalidArgumentException: Firehose record format conversion is not available in the current region. 
region (aws-us-gov-west-1) east is working also it does work with cloudformation it is kind of disappointing to spend time write code in TF and then I have to switch to CFT again.

**Comment by justinretzolk** [comment]
Hey @anoora17 👋 Thank you for taking the time to file this. Given that there's been a few Terraform and AWS Provider releases since you initially filed it, can you confirm whether you're still experiencing this?
