### ISSUE TITLE
Feature Request: `aws_elasticache_cluster` allow auto-minor-version-upgrade to be set

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#13517]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `aws_elasticache_cluster` resource does not allow auto-minor-version-upgrade to be set. It is supported through the [API](https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateCacheCluster.html) and [SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.CreateCacheCluster). 

### New or Affected Resource(s)

* aws_elasticache_cluster

### Potential Terraform Configuration

```hcl
resource "aws_elasticache_cluster" "test" {
  cluster_id           = ""
  engine               = "memcached"
  node_type            = "cache.t3.small"
  num_cache_nodes      = 1
  port                 = 11211
  auto_minor_version_upgrade = true
}
```

**Comment by gdavison** [comment]
The `AutoMinorVersionUpgrade` parameter is not currently enabled in the AWS API. The [API documentation](https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateCacheCluster.html#API_CreateCacheCluster_RequestParameters) and [SDK documentation](https://github.com/aws/aws-sdk-go/blob/v1.36.9/service/elasticache/api.go#L9100-L9373) both have notes that
> This parameter is currently disabled.
