### ISSUE TITLE
aws_msk_cluster support in-place upgrades

### ISSUE THREAD

**Issue by rifelpet** [hashicorp/terraform-provider-aws#13547]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS recently added support for upgrading MSK clusters. It would be great if the terraform provider supported upgrades as well.

https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-msk-supports-apache-kafka-version-upgrades/

https://docs.aws.amazon.com/msk/latest/developerguide/version-upgrades.html

### New or Affected Resource(s)

* aws_msk_cluster

### Potential Terraform Configuration

N/A

### References

N/A

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.31.7](https://github.com/aws/aws-sdk-go/releases/tag/v1.31.7):
* https://github.com/terraform-providers/terraform-provider-aws/pull/13459

**Comment by arafsheikh** [comment]
Ready for review #13654

**Comment by jmisharp** [comment]
Why is this issue still not released or part of a milestone? The pull request seems to be all good.

**Comment by jmisharp** [comment]
@breathingdust Do you know why this hasn't been released yet?

**Comment by breathingdust** [comment]
Hi @jmisharp 👋 It's on our list for review, and I'd expect that we would get to it in the next couple weeks. We appreciate your patience!

**Comment by anGie44** [comment]
Hi @rifelpet et al. 👋 This feature has been merged and will release with `v3.16.0` of the Terraform AWS Provider.
