### ISSUE TITLE
aws_subnets data resource for multiple subnets

### ISSUE THREAD

**Issue by tedivm** [hashicorp/terraform-provider-aws#13565]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be nice if there was a data source that could pull multiple subnets down, rather than just a single subnet.

### New or Affected Resource(s)

* data.aws_subnets

### Potential Terraform Configuration

```hcl
data "aws_subnets" "public" {
  vpc_id = data.aws_vpc.main.id
  tags = { Network = "public" }
}
```

### References

* #373
* [terraform #10123](https://github.com/hashicorp/terraform/issues/10123)

**Comment by ewbankkit** [comment]
@tedivm Thanks for raising this issue.
The existing [`aws_subnet_ids`](https://www.terraform.io/docs/providers/aws/d/subnet_ids.html) data source returns the IDs of subnets that match the specified criteria and can be used in conjunction with the [`aws_subnet`](https://www.terraform.io/docs/providers/aws/d/subnet.html) data source (see the _Example Usage_ section of the `aws_subnet_ids` documentation for guidance).
Is this sufficient for your use case?
