### ISSUE TITLE
Terraform Plan is not same across Operating Systems(Windows and Linux) with same state configured as s3 backend

### ISSUE THREAD

**Issue by parshuram-patil** [hashicorp/terraform-provider-aws#13566]
### Terraform Version

```
Terraform v0.12.25
```

### Affected Resource(s)

* aws_instance
* aws_ebs_volume
* aws_lb_target_group_attachment
* aws_volume_attachment

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "eu-central-1"
}

terraform {
  backend "s3" {}
}
```

```
Scripts with Affected Resource(s) which has `template_cloudinit_config` that mount attached volumes to EC2 instances
```

### Debug Output

```
1. Terraform Plan on Windows 10 - https://gist.github.com/parshuram-patil/4bdd747ee4bcfcc08387059e27aa678e
2. Terraform Plan on Ubuntu 18.04 - https://gist.github.com/parshuram-patil/058be0653965e132be2be54480b2f16c
```

### Expected Behavior

```
`terraform plan` with backend as s3 should show same plan on both Windows(version 10) and Linux(Ubuntu 18.04) Machines
```

### Actual Behavior

```
`terraform plan` is showing different plan on Windows and Linux after applying changes from Windows machine
```

### Steps to Reproduce

```
1. `terraform apply` from Windows 10
2. `terraform plan` on Windows 10 --> shows no change
3. `terraform plan` on Ubuntu 18.04 --> shows resources to be recreated
```

### Important Factoids

```
1. First time we applied changes using Git bash on windows and then using GitLab CI/CD with Linux machine as runner
1. We are using `template_cloudinit_config` to mount attached volumes to EC2 instances
2. I observed that the order of refreshing state of the resources on both the operating systems is not same
3. Using Terraform Workspace to handle multiple environments
```

**Comment by psoares** [comment]
We hit the same error today. It seems related to differences in file permissions (or some kind of filesystem difference between windows and linux).

We checked out our terraform code from git on windows from a powershell terminal, and did a terraform plan. We then repeated the terraform plan on a WSL terminal (debian and ubuntu) from the same directory (i.e. /mnt/c/path/to/code), the result is consistent both on powershell and on the WSL terminal.

However, when doing a checkout of the code directly from the WSL terminal (e.g. /tmp/code), then `terraform plan` shows a different result than the windows  version.

When comparing the directory cloned from git on windows and the one on WSL, the only differences I see are the file permissions (which appear as 777 on the windows mounted directory).

This looks like a serious bug. In our case, the windows version shows 4 tainted resources, when the linux version only shows 2... I'm not sure which version is correct.

**Comment by parshuram-patil** [comment]
Yes for us its a serious bug as its recreating resources. 

@psoares, I feel its not a problem related to file permission, Terraform decides resource recreation or taint based on state file only, also if its problem with file permission, there would be problem in executing that script(in my case scripts are executing absolutely fine). So i feel somewhere terraform keeps track of OS in state file from where we have applied the changes. What you say?

**Comment by kylelee24** [comment]
Was this problem ever resolved? I am using the `azurerm` with similar behaviour but on PowerShell/WSL or WSL (with a new cloned dir under `/tmp`) which are all the same, differs from my Azure DevOps Pipeline hosted agent on Ubuntu. The pipeline shows no changes (which is expected), and locally it shows 2 in place updates, and 4 which will be recreated. I am using remote state as well.

**Comment by frdvo** [comment]
I'm also having the same problem running a terraform plan from PowerShell and WSL2. Although, if I run from WSL accessing a Windows file system path (/mnt/c/Users...) the outcome is the same as the PowerShell.

**Comment by kcighon** [comment]
Same issue with azure provider on terraform 0.14.7. Problem if you develop on a Windows machine but your ADO pipeline runs on Ubuntu!

**Comment by tsposato** [comment]
I have similar issues, I believe it may be a GIT checkout issue to do with CR vs. CRLF on *nix and Windows?
If I apply on windows and then do a plan on Linux it always wants to taint/replace things that terraform checksums (like user init scripts and lambda functions etc.) as they are different across operating systems.

**Comment by kcighon** [comment]
Thanks @tsposato - that helped. I added a .gitattributes:
```bash
* text=auto

*.tf  eol=lf
*.tfvars  eol=lf
*.yml  eol=lf

```
and dos2unix-ed the files:
```bash
find ./ -type f \( -iname \*.tf -o -iname \*.tfvars -o -iname \*.md -o -iname \*.yml \) -print0 | xargs -0 dos2unix
dos2unix .gitignore
dos2unix .gitattributes
```

Appears ok now.

**Comment by starteleport** [comment]
I've spent hours to figure out the problem was with line endings. And now I know the right google query to find this issue. 😄

**Comment by justinretzolk** [comment]
Hi all 👋 Given that this seems to have been as a result of file formatting and a solution of sorts has been found, I'm going to go ahead and close this issue. If you feel I've done this in error, please do let me know.
