### ISSUE TITLE
aws_workspace: Timeout reached on creation

### ISSUE THREAD

**Issue by GuillermoContrerasP** [hashicorp/terraform-provider-aws#13598]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24

### Affected Resource(s)

* aws_workspace

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
resource "aws_workspaces_workspace" "workspace_racker" {
  directory_id = module.directory.directory_id
  bundle_id    = data.aws_workspaces_bundle.standard_windows_10.id
  user_name    = "racker-test"

  workspace_properties {
    compute_type_name                         = data.aws_workspaces_bundle.standard_windows_10.compute_type[0].name
    user_volume_size_gib                      = data.aws_workspaces_bundle.standard_windows_10.user_storage[0].capacity
    root_volume_size_gib                      = data.aws_workspaces_bundle.standard_windows_10.root_storage[0].capacity
    running_mode                              = "AUTO_STOP"
    running_mode_auto_stop_timeout_in_minutes = 60
  }

  tags = {
    Environment = "Development"
  }

}
### Debug Output

aws_workspaces_workspace.workspace_racker: Still creating... [29m1s elapsed]
aws_workspaces_workspace.workspace_racker: Still creating... [29m11s elapsed]
aws_workspaces_workspace.workspace_racker: Still creating... [29m21s elapsed]
aws_workspaces_workspace.workspace_racker: Still creating... [29m31s elapsed]
aws_workspaces_workspace.workspace_racker: Still creating... [29m41s elapsed]
aws_workspaces_workspace.workspace_racker: Still creating... [29m51s elapsed]
aws_workspaces_workspace.workspace_racker: Still creating... [30m1s elapsed]

Error: workspace "ws-7dq7plqrv" is not available: timeout while waiting for state to become 'AVAILABLE' (last state: 'PENDING', timeout: 30m0s)

  on main.tf line 134, in resource "aws_workspaces_workspace" "workspace_racker":
 134: resource "aws_workspaces_workspace" "workspace_racker" {

### Expected Behavior

Workspace creation should be successful
### Actual Behavior

Workspace creation reaches a timeout and the state is not updated successfully. Either the internal timeout should be updated or the nested block timeouts should be allowed, just like RDS
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by sulabhk** [comment]
+1, I second @fweep in having a configurable option wrt timeouts not just for WS, but for other services like RDS, Aurora etc that take longer times to be created/updated.

**Comment by aleliaert** [comment]
+1, am helping a Windows IT team move to the cloud with an infrastructure-as-code mindset.  Don't want to retreat and use CloudFormation.  Help appreciated!

**Comment by Tensho** [comment]
Hi there, I've recently added [timeout attributes](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/workspaces_workspace#timeouts) to `aws_workspaces_workspace` resource. Please could you test them for your configuration? 🙇

**Comment by bflad** [comment]
Given the resource now supports configurable timeouts and since there has been no further activity here, I'm going to close this issue.
