### ISSUE TITLE
No documention for AWS Glue Crawler configuration

### ISSUE THREAD

**Issue by goochi1** [hashicorp/terraform-provider-aws#13595]
Terraform Version

Terraform v0.11.14
### Affected Resource(s)

aws_glue_crawler

### Terraform Configuration Files

```hcl
resource "aws_glue_crawler" "trusted_advisor" {
  database_name = "kpmgcostanalysisathenadatabase${var.env}"
  name          = "trusted_advisor${var.env}"
  role          = "${aws_iam_role.compute_optimizer_role.arn}"
  schedule      = "cron(07 10 * * ? *)"

  s3_target {
    path = "s3://kpmgcloud-cost-report${var.env}/Trusted_Advisor"
  }

  configuration = <<EOF
    {"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}, }}
EOF

  tags = {
    Team = "FinOps"
  }
}
```

### Expected Behavior

I need to be able to have these config options:

**Schema updates in the data store** - Ignore the change and don't update the table in the data catalog

**Inherit schema from table** - 	Update all new and existing partitions with metadata from the table.

**Object deletion in the data store** - 	Mark the table as deprecated in the data catalog.

I know how to do the second one as seen in my exmple but i cant see how to do the first. Its not clear in these documents https://www.terraform.io/docs/providers/aws/r/glue_crawler.html#configuration

Please can you point me to an example with how to configure

**Comment by goochi1** [comment]
Hi can some point me to the example?

**Comment by tee** [comment]
Hey @goochi1 and anybody else looking for this answer. If you check https://docs.aws.amazon.com/glue/latest/dg/crawler-configuration.html you will see an example of how it can be achieved . While I agree this should be documented in TF under the glue provider docs, here is an example. I'm using this in pre-prod and prod envs and it's working perfectly. 

```
resource "aws_glue_crawler" "events_crawler" {
  database_name = aws_glue_catalog_database.glue_database.name
  schedule      = "cron(0 1 * * ? *)"
  name          = "events_crawler_${var.environment_name}"
  role          = aws_iam_role.glue_role.arn
  tags          = var.tags

  configuration = jsonencode(
    {
      Grouping = {
        TableGroupingPolicy = "CombineCompatibleSchemas"
      }
      CrawlerOutput = {
        Partitions = { AddOrUpdateBehavior = "InheritFromTable" }
      }
      Version = 1
    }
  )

  s3_target {
    path = "s3://${aws_s3_bucket.data_lake_bucket.bucket}"
  }
}
```

**Comment by DrFaust92** [comment]
Hey @tee, would you mind opening a PR and adding some examples and the link you mention to the docs?
