### ISSUE TITLE
aws_dms_certificate doesn't import Oracle wallet correctly

### ISSUE THREAD

**Issue by lawrieke** [hashicorp/terraform-provider-aws#13605]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v0.12.20
v0.12.16
### Affected Resource(s)

aws_dms_certificate

### Terraform Configuration Files
```hcl
resource "aws_dms_certificate" "source" {
  certificate_id     = "source-oracle-wallet-ca"
  certificate_wallet = filebase64("${path.root}/rds-ca-2019-root.sso")
}
```

### Debug Output

Output shows as successful, the DMS certificate is visible in the AWS console

### Expected Behavior

The imported certificate should be valid

### Actual Behavior

The imported certificate isn't valid.

Importing the certificate in the AWS console works and the below cli import is successful;
```
aws dms import-certificate --certificate-identifier source-oracle-wallet-ca-fromcli --certificate-wallet fileb://rds-ca-2019-root.sso
```

The TF state contains the correct base64 encoded certificate, but when TF imports it into AWS DMS, a second base64 encoding is applied corrupting the certificate.

### Important Factoids

If I try;
```
certificate_wallet = file("${path.root}/rds-ca-2019-root.sso")
```
It fails with 'provided string is not valid UTF-8'

There were changes to the certificate_wallet input back in version v2.46.0, but this issue occurs in versions before or after 2.46
https://github.com/terraform-providers/terraform-provider-aws/pull/11496

### References

* #0000

**Comment by sonikro** [comment]
I'm having the same issue. We can't use the `file` function because the certificate contains invalid UTF-8 characters, however we can't also use `fillebase64`, because the aws-sdk-go will encode the content again, so that's why the certificate is corrupted.

I've opened a PR to try to fix this issue
