### ISSUE TITLE
ELB SSL cert update resets SSL ciphers causing silent configuration drift

### ISSUE THREAD

**Issue by jrcasso** [hashicorp/terraform-provider-aws#13628]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform & AWS Provider Version

Terraform v0.11.14
provider.aws v2.39.0

### Affected Resource(s)

* aws_lb_ssl_negotiation_policy
* aws_elb

## Initial Configuration
```hcl
resource "aws_acm_certificate" "example-cert-foo" {
    domain_name       = "foo.example.com"
    validation_method = "DNS"
}

resource "aws_acm_certificate" "example-cert-bar" {
    domain_name       = "bar.example.com"
    validation_method = "DNS"
}

resource "aws_elb" "lb" {
  name               = "test-lb"
  availability_zones = ["us-east-1a"]

  listener {
    instance_port      = 8000
    instance_protocol  = "https"
    lb_port            = 443
    lb_protocol        = "https"
    ssl_certificate_id = "${aws_acm_certificate.example-cert-foo.arn}"
  }
}

resource "aws_lb_ssl_negotiation_policy" "baz" {
  name          = "baz-policy"
  load_balancer = "${aws_elb.lb.id}"
  lb_port       = 443

  attribute {
    name  = "Protocol-TLSv1"
    value = "false"
  }

  attribute {
    name  = "Protocol-TLSv1.1"
    value = "false"
  }

  attribute {
    name  = "Protocol-TLSv1.2"
    value = "true"
  }

  attribute {
    name  = "Server-Defined-Cipher-Order"
    value = "true"
  }

  attribute {
    name  = "ECDHE-RSA-AES128-GCM-SHA256"
    value = "true"
  }

  attribute {
    name  = "AES128-GCM-SHA256"
    value = "true"
  }

  attribute {
    name  = "EDH-RSA-DES-CBC3-SHA"
    value = "false"
  }
}
```

## Change: `diff`

```
- ssl_certificate_id = "${aws_acm_certificate.example-cert-foo.arn}"
+ ssl_certificate_id = "${aws_acm_certificate.example-cert-bar.arn}"
```

## Final Configuration

Only the ELB configuration changes:

```hcl
[...]

resource "aws_elb" "lb" {
  name               = "test-lb"
  availability_zones = ["us-east-1a"]

  listener {
    instance_port      = 8000
    instance_protocol  = "https"
    lb_port            = 443
    lb_protocol        = "https"
    ssl_certificate_id = "${aws_acm_certificate.example-cert-bar.arn}"  # Changed
  }
}

[...]
```

### Expected Behavior

After applying the new SSL certificate to the ELB, the custom ciphers policies should persist as declared.

### Actual Behavior

After applying the new SSL certificate to the ELB, the custom ciphers are reset to AWS default cipher policies, clearing out the previous custom ciphers. They do not persist as declared, and Terraform does not recognize a change in custom cipher policy state upon subsequent `terraform plan`s.

### Steps to Reproduce

1. Execute `terraform apply`  (see **Initial Configuration**)
1. Observe that the declared custom SSL cipher policies are correctly associated with the ELB.
1. Modify the ELB by attaching a new SSL certificate (see **Change: `diff`** -> **Final Configuration**)
1. Execute `terraform apply`
1. Observe through the AWS console that the prior custom SSL cipher policies are no longer associated with the ELB, in disagreement with `terraform.tfstate`, drifted from the declared state.
1. Execute `terraform plan`
1. Observe that Terraform _does not_ recognize any difference in state, despite a clear configuration drift.

### Important Factoids

- An alternate way to enumerate the ciphers on the ELB without using the console is to utilize a popular network analysis tool called `nmap`, executing the following command:
  `nmap --script ssl-enum-ciphers -p 443 <foo.example.com>`

I believe the explanation for this issue is quite straightforward; I am more than happy to clarify/assist where able.

* #0000

**Comment by ewbankkit** [comment]
Similar:
* https://github.com/terraform-providers/terraform-provider-aws/issues/187

**Comment by ibrahima** [comment]
Huh, just ran into this. Is there a way to "reset" the state so that it re-applies this setting? I suppose I could rename the resource... Looking at #187, it seems like there might be a workaround by adding a `aws_load_balancer_listener_policy` but that feels like it should not be necessary given that `aws_lb_ssl_negotiation_policy` does directly refer to the load balancer ID and I don't have any other load balancer policy resources.

**Comment by jrcasso** [comment]
@ibrahima My solution was to utilize the `depends_on` meta-argument to handle hidden resource dependencies that Terraform was unable infer (such as this case)

**Comment by kartvep** [comment]
It looks like aws_lb_ssl_negotiation_policy checks if a ploicy is present, but doesn't check if the policy is assigned to a balancer.

aws_load_balancer_policy seems to check the assignment status in the update method (which is not implemented for aws_lb_ssl_negotiation_policy), but I'm not a real gopher.

**Comment by haidangwa** [comment]
We ran into this bug on AWS provider 3.19.0 and terraform 0.13.5.

**Comment by jasonrojas** [comment]
Similar issue with aws_lb_ssl_negotiation_policy - if a aws_elb listener is set to HTTPS a policy is added, if that listener is changed say from HTTPS to TCP the policy remains attached to the LB listener.

**Comment by jrcasso** [comment]
I'd just like to note that this is pretty serious in not uncommon business use-cases where consumers require specific ciphers for comms -  particularly because it occurs silently! Engineers aren't going to realize what has happened until it's too late.

**Comment by ewbankkit** [comment]
The ability to detect a change in the `aws_lb_ssl_negotiation_policy` `attribute` list was removed in https://github.com/hashicorp/terraform-provider-aws/pull/13418.
