### ISSUE TITLE
DLM Lifecycle Policy CronExpression support

### ISSUE THREAD

**Issue by niklaskhf** [hashicorp/terraform-provider-aws#13627]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS DLM Lifecycle Policies support custom scheduling beyond 24 hours with custom cron expressions. It would be useful to support the usage of cron expressions in Terraform. 

### New or Affected Resource(s)

* aws_dlm_lifecycle_policy

### Potential Terraform Configuration

```hcl
cron_expression = "cron(0 18 ? * WED *)"
```

### References

* https://docs.aws.amazon.com/dlm/latest/APIReference/API_CreateLifecyclePolicy.html

**Comment by niklaskhf** [comment]
CronExpression was added to the AWS Go SDK in v1.31.5

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.31.5](https://github.com/aws/aws-sdk-go/releases/tag/v1.31.5):
* https://github.com/terraform-providers/terraform-provider-aws/pull/13459

**Comment by isandozi** [comment]
👍

**Comment by albertocorrales** [comment]
Without cron expression, the minimal frequency to take a snapshot is 1 hour, which is not enough for critical systems

**Comment by DrFaust92** [comment]
Closed by #23880
