### ISSUE TITLE
aws_cloudwatch_metric_alarm with metric_query with period set to strings not working in cloudwatch

### ISSUE THREAD

**Issue by fnickels** [hashicorp/terraform-provider-aws#13621]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.25

### Affected Resource(s)

* aws_cloudwatch_metric_alarm 

### Terraform Configuration Files

```hcl
resource aws_cloudwatch_metric_alarm ASG_flapping {

  alarm_name = "myalarm"


  comparison_operator = "GreaterThanThreshold"
  threshold           = "0"
  treat_missing_data  = "breaching"                     

  datapoints_to_alarm = "1"
  evaluation_periods  = "1"



  metric_query {
    id          = "e2"
    expression  = "f1+f2"
    label       = "FlappingRate"
    return_data = "true"
  }

  metric_query {
    id = "f1"

    metric {
      metric_name = "TriggeredRules"
      namespace   = "AWS/Events"
      period      = "600"
      stat        = "Sum"
      unit        = "Count"

      dimensions = {
        AutoScalingGroupName = aws_cloudwatch_event_rule.asg_events_launch.name
      }
    }
  }

  metric_query {
    id = "f2"

    metric {
      metric_name = "TriggeredRules"
      namespace   = "AWS/Events"
      period      = "600"
      stat        = "Sum"
      unit        = "Count"

      dimensions = {
        AutoScalingGroupName = aws_cloudwatch_event_rule.asg_events_terminate.name
      }
    }
  }
}
```

### Expected Behavior

Alarm will be created that reports events

### Actual Behavior

Alarm is created but no metrics are picked up.  No errors are reported.  If you change the references from `period = "600"` to `period=600`.  Things work as expected.

Some form of error check should be done on these values or typecasting should occur to convert the strings to numbers.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by gdavison** [comment]
This should be resolved in current versions of Terraform and the AWS Provider, so I'm going to close this issue. If you still see this problem, please open a new issue,
