### ISSUE TITLE
Add ARN and/or plan time validations to resources/data_sources

### ISSUE THREAD

**Issue by anGie44** [hashicorp/terraform-provider-aws#13624]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This particular Issue serves as a log of PRs addressing this tech-debt Issue Topic

### ARN Support
- [x] aws_ec2_client_vpn_endpoint 
- [x] aws_glue_connection
- [x] aws_ebs_volume
- [x] aws_api_gateway_rest_api
- [x] aws_wafregional_rate_based_rule
- [x] aws_wafregional_rule_group
- [x] aws_wafregional_rule

### Plan time validations
- [x] aws_ec2_client_vpn_endpoint 
- [x] aws_waf_xss_match_set
- [x] aws_opsworks_application
- [x] aws_spot_fleet_request
- [x] aws_launch_template
- [x] aws_instance

### Relates

* #13601, #13404, #13021, #12777, #12383, #12295, #11486, #10971, #10897, #10896, #10895,

**Comment by bflad** [comment]
@anGie44 is there a definition of done for this issue?

**Comment by anGie44** [comment]
that's a good question @bflad!  I believe this issue tries to address too much 😅 . using a naive grep search 
```
grep -L 'd.Set("arn",' aws/resource*.go | grep -v '_test.go$' | wc -l
```
we still have over 300 resources needed to satisfy just a portion of this issue. 

lmk what your thoughts on this are, but I think we should contain the associated PRs as is (so definition of done will be when those are merged) and then moving forward, we should create enhancement issues on a resource/data-source by resource/data-source basis

**Comment by anGie44** [comment]
Going to close this for the time being as validation changes are captured well enough in changelog files and we aren't monitoring this tech debt item.
