### ISSUE TITLE
lb_listener_rule target group support in 2.65

### ISSUE THREAD

**Issue by jmgreg31** [hashicorp/terraform-provider-aws#13636]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.26
provider.aws: version = "~> 2.65"
```
### Affected Resource(s)

* aws_lb_listener_rule

### Terraform Configuration Files

```hcl
resource "aws_lb_target_group" "my-albtg" {
  count    = length(var.autoscaling_group_name)
  name     = format("${var.name}%01d-alb-tg", count.index +1)
  ...
}

resource "aws_lb_listener_rule" "my-alb-listener-rule" {
  listener_arn = aws_lb_listener.my-alb-listener.arn
  priority     = 100
  action {
      type  = "forward"
      forward {
        dynamic "target_group" {
          for_each = var.autoscaling_group_name
          content {
            arn = aws_lb_target_group.my-albtg[target_group.key].arn
          }
        } 
      }
    }
```

### Debug Output

```
Error: action.0.forward.0.target_group: attribute supports 2 item as a minimum, config has 1 declared
```
### Expected Behavior

This pattern works fine if you are using multiple target groups blocks.  Per the documentation, I would expect this to work with a single target group block as well

### Actual Behavior

error

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Found a workaround, however, if you re-apply a listener rule with fewer target groups it will throw an error 
```
Error: Error deleting Target Group: ResourceInUse: Target group 'arn:aws:elasticloadbalancing:us-east-1:.......' is currently in use by a listener or a rule
```

Attempted workaround:
```hcl
action {
    type             = "forward"
    target_group_arn = length(var.autoscaling_group_name) == 1 ? aws_lb_target_group.my-albtg[0].arn : null
    dynamic "forward" {
      for_each = length(var.autoscaling_group_name) == 1 ? [] : [aws_lb_target_group.my-albtg[0].arn]
      content {
        dynamic "target_group" {
          for_each = var.autoscaling_group_name
          content {
            arn = aws_lb_target_group.my-albtg[target_group.key].arn
          }
        } 
      }
    }
  }
```

Wondering if the use case of dynamic number of target groups is just not yet supported?

**Comment by bflad** [comment]
Hi @jmgreg31 👋  What version of Terraform CLI are you using (`terraform version`)? There were similar reports in earlier 0.12 versions of the Terraform CLI.

**Comment by jmgreg31** [comment]
@bflad I am using the latest version:
```
Terraform v0.12.26
```

**Comment by jmgreg31** [comment]
I believe the attempted working around is facing this issue: https://github.com/terraform-providers/terraform-provider-aws/issues/636

However none of the solutions mentioned with random naming would solve for this use case as we would in fact need to destroy the resource.

**Comment by andrenho** [comment]
I seem to be having the same issue when creating a single listener rule based on a set of strings:

`resource "aws_lb_listener_rule" "lb_rule" {
  for_each    = var.target_identifiers   # set of strings

  listener_arn = aws_lb_listener.alb_listener_https.arn
  action {
    type = "forward"
    forward {
      target_group {
        arn    = aws_lb_target_group.target_group[each.value].arn
      }
    }
  }
  condition {
    path_pattern {
      values = ["/${each.value}/*"]
    }
  }
}`

The proposed workaround doesn't seem to work on this situation. I can't find one that works. Does anybody has any idea of a workaround?

**Comment by SpComb** [comment]
https://github.com/terraform-providers/terraform-provider-aws/pull/12574#issuecomment-639642524 explains that this is an API issue with `type = "forward"` + `target_group_arn = ...` vs multiple `target_group { arn = ... }` blocks...

> Hi @jmgreg31, I think you're correct. I make a mistake in the documentation. To route to a single target group you must use the "target_group_arn" attribute outside the forward block, and to route to two or more target groups, the "forward" block with "target_group" blocks.
>
> This is because of an API limitation in the AWS upstream, but I'll make my best to work around this behavior and/or update the documentation this weekend.

I suppose the terraform provider would need to special-case the single-`target_group` case for this to work?

**Comment by SpComb** [comment]
Best workaround might be to use separate resources for the two structural cases:

```
resource "aws_lb_listener_rule" "http-forward" {
  count = (var.second_target_group_arn == null) ? 1 : 0

  listener_arn = var.alb_listener_arn
  priority     = var.alb_priority

  condition {
    host_header {
      values = [var.server_name]
    }
  }

  action {
    type             = "forward"
    target_group_arn = var.first_target_group_arn
  }
}

resource "aws_lb_listener_rule" "http-forward-weighted" {
  count = (var.second_target_group_arn == null) ? 0 : 1

  listener_arn = var.alb_listener_arn
  priority     = var.alb_priority

  condition {
    host_header {
      values = [var.server_name]
    }
  }
  
  action {
    type             = "forward"

    forward {
      target_group {
        arn    = var.first_target_group_arn
        weight = var.first_target_group_weight
      }
      target_group {
        arn    = var.second_target_group_arn
        weight = var.second_target_group_weight
      }
    }
  }
}
```

**Comment by ctacka** [comment]
Having same issue in v0.12.29
```
resource "aws_lb_listener_rule" "https" {
  listener_arn = data.aws_lb_listener.https.arn
  action {
    type = "forward"
    target_group_arn = aws_lb_target_group.tg.arn
    forward {
      target_group {
        arn    = aws_lb_target_group.tg.arn
      }

      stickiness {
        enabled  = true
        duration = 600
      }
    }
  }

  condition {
    host_header {
      values = [aws_route53_record.db.fqdn]
    }
  }
}
```
> Error: List shorter than MinItems
> 
>   on main.tf line 151, in resource "aws_lb_listener_rule" "https":
>  151:       target_group {
> 
> Attribute supports 2 item minimum, config has 1 declared

**Comment by nicon89** [comment]
Same issue on TF 0.14.4.

**Comment by kiddom-kq** [comment]
I hit this exact error while trying trying out a `dynamic` block inside of the `default_action` block on the `aws_lb_listener` resource. I know that `aws_lb_listener` is not the same as the resource that the ticket was opened for: `aws_lb_listener_rule ` but this behavior seems too bizarre to not document and seems to be related and might possibly be a work around.


```hcl2
resource "aws_lb_listener" "this" {
  load_balancer_arn = module.alb.arn
  port     = "443"
  protocol = "HTTPS"

  ssl_policy = "ELBSecurityPolicy-FS-1-2-Res-2020-10"
  certificate_arn = var.lb_certificate_arn

  default_action {
    type = "forward"
    # WORKS, even though length(aws_lb_target_group.this) is 1
    # forward {
    #   # Create a TG block for each of the TGs we created from user input
    #   dynamic "target_group" {
    #     for_each = aws_lb_target_group.this
    #     content {
    #       arn = target_group.value["arn"]
    #     }
    #   }
    # }

    # WORKS
    # forward {
    #   target_group {
    #     arn    = "Foo"
    #     weight = 80
    #   }
    #   target_group {
    #     arn    = "Bar"
    #     weight = 80
    #   }
    # }

    # DOES NOT WORK!
    # Returns: Attribute supports 2 item minimum, config has 1 declared
    forward {
      target_group {
        arn    = "Foo"
        weight = 80
      }
    }
  }
}

```


When the last `forward` block is enabled/un-commented, i get the same error OP reported:

```shell
❯ tf apply

Error: List shorter than MinItems

  on .terraform/modules/mo-module/main.tf line 173, in resource "aws_lb_listener" "this":
 173:       target_group {

Attribute supports 2 item minimum, config has 1 declared
```

But when the `forward` block with two 'dummy' `target_group`s is enabled/uncommented:

```shell
  # module.my-module.aws_lb_listener.this will be created
  + resource "aws_lb_listener" "this" {
      + arn               = (known after apply)
      + certificate_arn   = "arn:aws:acm:..."
      <...>
      + ssl_policy        = "ELBSecurityPolicy-FS-1-2-Res-2020-10"

      + default_action {
          + order = (known after apply)
          + type  = "forward"

          + forward {

              + target_group {
                  + arn    = "Bar"
                  + weight = 80
                }
              + target_group {
                  + arn    = "Foo"
                  + weight = 80
                }
            }
        }
    }
```

And when the first `forward` block is enabled:


```shell
  # module.my-module.aws_lb_listener.this will be created
  + resource "aws_lb_listener" "this" {
      + arn               = (known after apply)
      <...>
      + ssl_policy        = "ELBSecurityPolicy-FS-1-2-Res-2020-10"

      + default_action {
          + order = (known after apply)
          + type  = "forward"

          + forward {

              + target_group {
                  + arn    = (known after apply)
                  + weight = 1
                }
            }
        }
    }
```

So you can get around the "need a minimum of two" error if you do it `dynamic`ally...

**Comment by dominicrjames** [comment]
I got it working doing the following 

`resource "aws_lb_listener" "DEV_ENV_ALB_Forward_443" {
  load_balancer_arn = aws_lb.DEV_ENV_alb.arn
  port              = "443"
  protocol          = "HTTPS"
  ssl_policy        = "ELBSecurityPolicy-2015-05"
  certificate_arn   = var.secure_ssl_certificate_id_arn

  default_action {
    type = "forward"

    forward {
      target_group {
        arn    = aws_lb_target_group.CHERRIES_ALB_Forward_TG_80.arn
        weight = 80
      }

      target_group {
        arn    = aws_lb_target_group.GRAPES_ALB_Forward_TG_80.arn
        weight = 80
      }

      target_group {
        arn    = aws_lb_target_group.MANGOES_ALB_Forward_TG_80.arn
        weight = 80
      }

      target_group {
        arn    = aws_lb_target_group.APPLES_ALB_Forward_TG_80.arn
        weight = 80
      }
    }
  }
}
`

**Comment by DanGardnerr** [comment]
Also experiencing this issue in terraform verison `0.14.5`  

```
resource "aws_alb_listener_rule" "host_based_routing" {
  listener_arn = "arn"
  priority     = 99

  action {
    type = "forward"
    forward {
      target_group {
        arn    = aws_alb_target_group.nginx-service-tg.arn
        weight = 80
      }

      stickiness {
        enabled  = true
        duration = 600
      }
    }
  }

  condition {
    path_pattern {
      values = ["/ng/"]
    }
  }
}
```

Getting the error

```
Error: Error creating LB Listener Rule: ValidationError: You cannot specify the same target group multiple times in the target group list
        status code: 400, request id: 
```

**Comment by mnazir23** [comment]
Facing the same issue. Terraform Version is 0.13.5

I am trying to create the default ALB listener rule. 

`resource "aws_lb_listener" "my-alb-httpslistener" {
    load_balancer_arn = ALB_ARN
    port              = 443
    protocol          = "HTTPS"
    ssl_policy        = var.AlbSslPolicy
    certificate_arn   = var.AlbCertificateArn
    default_action {
        type             = "forward"
        forward {
            target_group {
                arn    = <Target Group ARN>
            }
            stickiness {
                enabled  = true
                duration = 3600
            }
        }
    }
}`


Getting the same error `attribute supports 2 item minimum, config has 1 declared`

**Comment by trentondyck** [comment]
Why should I have two target groups in my ALB listener rule? I just don't get it.

**Comment by daniloalves** [comment]
In this comment I got a explanation: https://github.com/hashicorp/terraform-provider-aws/pull/12574#issuecomment-639642524
When route to a single target group you must use the "target_group_arn" attribute outside the forward block.

**Comment by bereket42** [comment]
> In this comment I got a explanation: [#12574 (comment)](https://github.com/hashicorp/terraform-provider-aws/pull/12574#issuecomment-639642524)
> When route to a single target group you must use the "target_group_arn" attribute outside the forward block.

But what if you need to create a stickiness block? Or if the existing default has an invalid duration? See https://github.com/hashicorp/terraform-provider-aws/issues/15144

**Comment by suneshgovind** [comment]
Trying to do the same operation as @trentondyck is doing. How do you add stickiness block for a listener rule with a single target group?

```
forward {
  target_group {
    arn = var.target_group_arn
  }

  dynamic "stickiness" {
    for_each = var.stickiness_enabled == false ? [] : [1]
    content {
      enabled  = true
      duration = var.stickiness_duration
    }
  }
}
```

**Comment by Jayne1086** [comment]
issue is still happening with Terraform v1.1.5

**Comment by engineertdog** [comment]
This is still an issue, an not an AWS API limitation as this point.

**Comment by Yukititit** [comment]
Same issue with version:
```
Terraform v1.3.5
on windows_amd64
```

i am able to route to a single target group with target_group_arn but how should i add a stickiness block?

**Comment by autotune** [comment]
I am working on this as part of my 100 days of terraform contributions challenge. PR arriving soon.
