### ISSUE TITLE
Support Attaching and Detaching IAM Roles to RDS Clusters

### ISSUE THREAD

**Issue by dnedev** [hashicorp/terraform-provider-aws#13641]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Since https://github.com/terraform-providers/terraform-provider-aws/issues/8038 Terraform supports attaching IAM roles to RDS instances. However, for an S3 integration with Aurora clusters, the roles should be attached to the cluster and rather than an individual instance.

### New or Affected Resource(s)
* aws_rds_cluster
* aws_db_instance_role_association (existing resource with reciprocal function for DB instances)
* aws_rds_cluster_role_association (new)

### Potential Terraform Configuration

```hcl
resource "aws_rds_cluster_role_association" "example" {
  cluster_identifier = "${aws_rds_cluster.example.id}"
  feature_name = "s3Import"
  role_arn = "${aws_iam_role.example.arn}"
}
```

Note: AFAIK, the attached role (`${aws_iam_role.example.arn}`) should also be added to the `iam_roles` list for the `aws_rds_cluster`.

### References

* https://github.com/terraform-providers/terraform-provider-aws/issues/8038
* https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Integrating.LoadFromS3.html

**Comment by nickmasster** [comment]
Probably a duplicate for #9552.
