### ISSUE TITLE
EKS Node Group Resource Tag Inheritance

### ISSUE THREAD

**Issue by jornj-lululemon** [hashicorp/terraform-provider-aws#13643]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently EKS Node Group resources create autoscaling groups that do not inherit or pass down any configuration defined tags except the default EKS service association tags.  AWS EKS clusters (both on the cluster itself and created node groups) currently do not support tag propagation, and terraform only appears to track the autoscaling group name(s) created by the EKS node group resource.  Since the AWS terraform provisioner does not have functionality to define supplemental tags on untracked resources, the current workaround seems to be creating a local_exec provisioner calling the AWS autoscaling CreateOrUpdateTags API call.

### New or Affected Resource(s)

eks_node_group

### Potential Terraform Configuration

```
autoscaling_group_tags = {
    "my.eksnodegroup.asg.key" = "value"
}
```

or

```
propagate_tags = true/false
```

### References

https://docs.aws.amazon.com/eks/latest/userguide/eks-using-tags.html
https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_CreateOrUpdateTags.html

**Comment by ewbankkit** [comment]
@jornj-lululemon Thanks for raising this issue.
As similar thought has been [noted](https://github.com/terraform-providers/terraform-provider-aws/issues/9061#issuecomment-555497826) in #9061.
Let's keep this issue open until that is addressed.

**Comment by jornj-lululemon** [comment]
@ewbankkit Thanks for the triage, one thing to note is that the eks_node_group resources expose the autoscaling group name attribute list under `aws_eks_node_group.my_resource_name.resources[*].autoscaling_groups[*].name` so all the information necessary to passdown tags is available.

**Comment by DrFaust92** [comment]
FYI, Ive asked AWS SA that i work with to ask the EKS service team to address this, its seems to be in their roadmap.

**Comment by bflad** [comment]
Please note I'm dual labeling this issue -- if the upstream EKS API implements tag propagation support, great! Otherwise, we can consider the following new resource type for managing Autoscaling tags in the meantime:

```hcl
resource "aws_autoscaling_tag" "example" {
  key                 = "key1"
  propagate_at_launch = true
  resource_id         = aws_eks_node_group.my_resource_name.resources[*].autoscaling_groups[*].name
  value               = "value1"
}
```
