### ISSUE TITLE
ECR: Add Image URI as an Attribute for the image data source

### ISSUE THREAD

**Issue by dcherman** [hashicorp/terraform-provider-aws#13671]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Expose Image URI as an output attribute for the `aws_ecr_image` data source since it would be useful in many areas.  For example, passing it to ECS for a task def, or Kubernetes as the image in a pod.

While it's absolutely possible to construct it yourself, it feels like this is a common enough use case that it'd be nice to expose it for users.

### New or Affected Resource(s)

* `aws_ecr_image`

**Comment by dcherman** [comment]
Happy to make a PR for this if it's something the provider would accept.

**Comment by jessefarinacci** [comment]
It would also be useful with `aws_lambda_function.image_uri` configuration. Right now I have to create a pretty horrible looking URI manually..

**Comment by cliedeman** [comment]
What am I using in the mean time

```
"${data.aws_ecr_repository.registry.repository_url}:${data.aws_ecr_image.image.image_digest}"
```

**Comment by RemyNtshaykolo** [comment]
> What am I using in the mean time
> 
> ```
> "${data.aws_ecr_repository.registry.repository_url}@${data.aws_ecr_image.image.image_digest}"
> ```

thanks!

**Comment by Oriho** [comment]
I need to have Terraform to deploy ECS Farget,the image stored in ECR

**Comment by weaversam8** [comment]
I've authored a pull request that addresses this issue here: #24526.
