### ISSUE TITLE
Changing a DyanmoDB table billing mode from PAY_PER_REQUEST to PROVISIONED fails

### ISSUE THREAD

**Issue by rhowe** [hashicorp/terraform-provider-aws#13693]
It looks like https://github.com/terraform-providers/terraform-provider-aws/issues/7097 might have reared its head again.

Changing a table's billing mode from PAY_PER_REQUEST to PROVISIONED (with a read and write capacity of 1) fails with

`Error: Write capacity must be > 0 when billing mode is PROVISIONED`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.10
AWS provider version 2.65.0

### Affected Resource(s)

* aws_dynamodb_table

### Terraform Configuration Files

```
resource "aws_dynamodb_table" "base" {
  name             = "sometable"
  billing_mode     = "PROVISIONED"
  read_capacity    = 1
  write_capacity   = 1
  hash_key         = "somekey"

  server_side_encryption {
    enabled     = true
  }

  ttl {
    attribute_name = "TimeToLive"
    enabled        = true
  }
}
```

### Debug Output

Getting this might be a little troublesome, but if it's needed I can try.

### Expected Behavior

The table should be converted to `PROVISIONED` billing successfully.

### Actual Behavior

`terraform apply` failed (`terraform plan` succeeded)

### Steps to Reproduce

1. Deploy a dynamodb table with `billing_mode = "PAY_PER_REQUEST"`
1. Adjust the `billing_mode` to `"PROVISIONED"`
1. Set the `read_capacity` and `write_capacity` to 1
1. `terraform apply`

### References

* Looks a lot like #7097

**Comment by nishkrishnan** [comment]
We are seeing this issue as well.  I'm assuming that setting capacities to 1 with PAY_PER_REQUEST doesn't do anything if you have zero traffic since it's dynamic provisioning.

aws provider: 2.65
terraform version: 0.12.20

**Comment by rostams-lyft** [comment]
I hit this issue as well. It seems On-Demand (PAY_PER_REQUEST) cannot be moved to Autoscaling model right away. Even if the value is none-zero still I get the same error.

The workaround is to move On-Demand to Provisioned first and then move that to Autoscaling. 

This is very painful for us since we have a lot of table and we transition back and forth from On-Demand to Autoscaling. 

aws provider: 2.65
terraform version: 0.12.20

**Comment by ccampo133** [comment]
Just ran into this today. I am able to move from ON_DEMAND to PROVISIONED but only if I don't ignore the read/write capacity in a `lifecycle` block. For example, including this causes TF to fail:

```
lifecycle {
  ignore_changes = [ read_capacity, write_capacity ]
}
```

But removing it succeeds. I was able to work around this by first running tf apply w/o the `lifecycle` block and changing `ON_DEMAND` to `PROVISIONED`, and then re-adding the `lifecycle` block and running apply again.
