### ISSUE TITLE
Error: error using credentials to get account ID: error calling sts:GetCallerIde ntity: InvalidClientTokenId: The security token included in the request is inval id.

### ISSUE THREAD

**Issue by connectgeeks** [hashicorp/terraform-provider-aws#13695]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.26
[files.zip](https://github.com/terraform-providers/terraform-provider-aws/files/4751633/files.zip)

### Affected Resource(s)

#providers
provider "aws" {
  access_key = var.access_key
  secret_key = var.secret_key
  region     = var.region
}

#resources
resource "aws_vpc" "vpc" {
  cidr_block           = var.cidr_vpc
  enable_dns_support   = true
  enable_dns_hostnames = true
  tags = {
    "Environment" = var.environment_tag
  }
}

resource "aws_internet_gateway" "igw" {
  vpc_id = aws_vpc.vpc.id
  tags = {
    "Environment" = var.environment_tag
  }
}

resource "aws_subnet" "subnet_public" {
  vpc_id                  = aws_vpc.vpc.id
  cidr_block              = var.cidr_subnet
  map_public_ip_on_launch = "true"
  availability_zone       = var.availability_zone
  tags = {
    "Environment" = var.environment_tag
  }
}

resource "aws_route_table" "rtb_public" {
  vpc_id = aws_vpc.vpc.id

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.igw.id
  }

  tags = {
    "Environment" = var.environment_tag
  }
}

resource "aws_route_table_association" "rta_subnet_public" {
  subnet_id      = aws_subnet.subnet_public.id
  route_table_id = aws_route_table.rtb_public.id
}

resource "aws_security_group" "sg_22_80" {
  name   = "sg_22"
  vpc_id = aws_vpc.vpc.id

  # SSH access from the VPC
  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    "Environment" = var.environment_tag
  }
}

resource "aws_key_pair" "ec2key" {
  key_name   = "publicKey"
  public_key = file(var.public_key_path)
}

resource "aws_instance" "testInstance" {
  ami                    = var.instance_ami
  instance_type          = var.instance_type
  subnet_id              = aws_subnet.subnet_public.id
  vpc_security_group_ids = [aws_security_group.sg_22_80.id]
  key_name               = aws_key_pair.ec2key.key_name

  tags = {
    "Environment" = var.environment_tag
  }

  provisioner "remote-exec" {
    inline = [
      "sudo amazon-linux-extras enable nginx1.12",
      "sudo yum -y install nginx",
      "sudo systemctl start nginx",
    ]
  }

  connection {
    host        = coalesce(self.public_ip, self.private_ip)
    type        = "ssh"
    user        = "ec2-user"
    password    = ""
    private_key = file("~/.ssh/private_key.ppk")
  }
}

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Error: error using credentials to get account ID: error calling sts:GetCallerIde
ntity: InvalidClientTokenId: The security token included in the request is inval
id.
        status code: 403, request id: c546698b-594a-47db-9cf2-36251bf24668

  on resources.tf line 2, in provider "aws":
   2: provider "aws" {

### Steps to Reproduce

C:\Users\XXXXXXXXXXXXXXX>terraform init

Initializing the backend...

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 2.65"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

C:\Users\XXXXXXXXXXXXXXX>terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

------------------------------------------------------------------------

Error: error using credentials to get account ID: error calling sts:GetCallerIde
ntity: InvalidClientTokenId: The security token included in the request is inval
id.
        status code: 403, request id: c546698b-594a-47db-9cf2-36251bf24668

  on resources.tf line 2, in provider "aws":
   2: provider "aws" {

C:\Users\XXXXXXXXXXXXXXX>

PS  

C:\Users\XXXXXXXXXXXXXXX>terraform validate
Success! The configuration is valid.

terraform validate is fine
terraform init is fine
**terraform plan gives this error**

Additionally, ssh key file is generated in path C:\Users\MyUser\.ssh by putty KeyGen using Win8
1) Name private_key.ppk
2) public_key

### References

* #0000

**Comment by justinretzolk** [comment]
Hi @connectgeeks 👋 Thank you for taking the time to file this. Given that there's been a few Terraform and AWS Provider releases since you initially filed it, can you confirm whether you're still experiencing this?
