### ISSUE TITLE
Format func doesn't work when multiplied by 0.1 or 10%

### ISSUE THREAD

**Issue by im-dgundam** [hashicorp/terraform-provider-aws#13704]
**Community Note**

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Terraform Version**

```
0.12.07 to
0.12.21

```
**Affected Resource(s)**

aws_appautoscaling_policy

**Terraform Configuration Files**

```hcl
resource "aws_appautoscaling_policy" "alb_target_request_duration_scaling_policy_test" {
  count              = var.autoscaling_alb_request_duration_target == null ? 0 : 1
  name               = "service-alb-target-request-duration-policy"
  policy_type        = "StepScaling"
  resource_id        = "service/ecs-cluster/staging-ecs-service"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"

  step_scaling_policy_configuration {
    adjustment_type         = "PercentChangeInCapacity"
    cooldown                = 30
    metric_aggregation_type = "Average"

    step_adjustment {
      metric_interval_lower_bound = format("%.2f", var.autoscaling_alb_request_duration_target * 0.1 + var.autoscaling_alb_request_duration_target)
      scaling_adjustment          = 25
    }
  }

}
```

**Expected Behavior**

`metric_interval_lower_bound = "0.42"`

**Actual Behavior**

When applied
`metric_interval_lower_bound = "0.42000000000000004"`

I am trying to achieve a calculated value of 0.42 for metric_interval_lower_bound. Formatting on terraform plan looks fine, issue come in place when applied. If I replace 0.1 to 0.2 it gets applied with the desired decimal format 0.42
The value for var.autoscaling_alb_request_duration_target is 0.2

**Steps to Reproduce**

1. `terraform apply`

**Comment by im-dgundam** [comment]
the calculations look correct in tf console. When it comes to tf apply it gets messed up
```
$ terraform console
> format("%.2f", 4 * 0.1 + 0.02)
0.42
> format("%.2f", 2 * 0.2 + 0.02)
0.42
> format("%.2f", var.autoscaling_alb_request_duration_target * 0.1)
0.02
> format("%.2f", var.autoscaling_alb_request_duration_target * 0.1 + 0.2)
0.22
```

**Comment by ewbankkit** [comment]
It looks like this is the code that is responsible for returning the value that will be written to Terraform state:

https://github.com/terraform-providers/terraform-provider-aws/blob/cda1d2db6c5ba93c4db97f7d29e6cc4582e42c47/aws/resource_aws_appautoscaling_policy.go#L723-L742

It looks like [percentiles](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html#Percentiles) can have at most 2 decimal places.
