### ISSUE TITLE
Provide better documentation for Storage Gateway's data.aws_storagegateway_local_disk 

### ISSUE THREAD

**Issue by Gowiem** [hashicorp/terraform-provider-aws#13701]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Using `data.aws_storagegateway_local_disk` can be troublesome as it seems there is some undocumented different between `disk_node` and `disk_path`. After finding #5589, I was able to use `disk_node` which allowed my data lookup to find my corresponding disk, but before then I was left scratching my head. This should be addressed in the documentation so others don't run into the same problem and therefore we alleviate any future storage gateway head scratching. 

### New or Affected Resource(s)

* [data.aws_storagegateway_local_disk](https://www.terraform.io/docs/providers/aws/d/storagegateway_local_disk.html)

### References

* #5589

**Comment by sksumit1** [comment]
The entire storage gateway needs better documentation.
E.g. aws_storagegateway_gateway -> gateway_vpc_endpoint
This needs to be the dns name. Its ambiguous and i tried using gateway id and it never worked till i figured out from the code, why.
This is what works
 gateway_vpc_endpoint = element(aws_vpc_endpoint.file_gateway_endpoint.dns_entry, 0)["dns_name"]
