### ISSUE TITLE
aws_cur_report_definition throwing - HTTP/1.1 400 Bad Request

### ISSUE THREAD

**Issue by lw-kaijparo** [hashicorp/terraform-provider-aws#13702]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.26
+ provider.aws v2.65.0
+ provider.template v2.1.2
```

### Affected Resource(s)

aws_cur_report_definition

### Terraform Configuration Files

```
resource "aws_s3_bucket" "generic" {
  bucket = "generic-cur-bucket"
  region = "us-west-2"
  acl = "private"

  policy = <<POLICY
{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Sid": "get",
      "Effect": "Allow",
      "Principal": {
        "Service": "billingreports.amazonaws.com"
      },
      "Action": [
        "s3:GetBucketAcl",
        "s3:GetBucketPolicy"
      ],
      "Resource": "arn:aws:s3:::generic-cur-bucket"
    },
    {
      "Sid": "put",
      "Effect": "Allow",
      "Principal": {
        "Service": "billingreports.amazonaws.com"
      },
      "Action": [
        "s3:PutObject"
      ],
      "Resource": "arn:aws:s3:::generic-cur-bucket/*"
    }
  ]
}
POLICY
}

resource "aws_cur_report_definition" "generic" {
  report_name = "generic-cur-report-definition"
  time_unit = "HOURLY"
  format = "textORcsv"
  compression = "GZIP"
  additional_schema_elements = ["RESOURCES"]
  s3_bucket = "${aws_s3_bucket.generic.id}"
  s3_region = "us-west-2
  s3_prefix = "cur"
  additional_artifacts = ["REDSHIFT", "QUICKSIGHT"]
}
```
### Debug Output

https://gist.github.com/lw-kaijparo/718847458abaf5f39a0049c9aecf1b97

### Expected Behavior

aws_cur_report_definition created without error

### Actual Behavior

Received HTTP/1.1 400 Bad Request

### Steps to Reproduce

1. `terraform apply`

### References

Used example: https://www.terraform.io/docs/providers/aws/r/cur_report_definition.html#example-usage

* #0000

**Comment by ChristophShyper** [comment]
I have similar issue if my default region is `eu-west-1`. But in `aws_cur_report_definition` provider is configured to use `us-east-1` and I'm still getting: 
```
Error: Error creating AWS Cost And Usage Report Definition: RequestError: send request failed
caused by: Post "https://cur.eu-west-1.amazonaws.com/": dial tcp: lookup cur.eu-west-1.amazonaws.com on 192.168.65.1:53: no such host
```

My resource config is (bucket for CUR is in `eu-west-1`):
```terraform
resource "aws_cur_report_definition" "cur" {
  provider = aws.us_east_1

  report_name                = local.cur_bucket_name
  time_unit                  = "HOURLY"
  format                     = "Parquet"
  compression                = "Parquet"
  additional_schema_elements = ["RESOURCES"]
  s3_bucket                  = local.cur_bucket_name
  s3_prefix                  = local.cur_bucket_name
  s3_region                  = local.eu_west_1
  additional_artifacts       = ["ATHENA"]
  refresh_closed_reports     = true
  report_versioning          = "OVERWRITE_REPORT"
}
```


I see you're using `us-est-2` region so that's probably the same error with this resource.

**Comment by PeterYou** [comment]
@lw-kaijparo , Did you get this error fixed?

**Comment by ewbankkit** [comment]
Because the Cost And Usage Report service has such a low API rate limit we may want to add custom retry logic to [`config.go`](https://github.com/hashicorp/terraform-provider-aws/blob/31bf342ed9d61ebb7c88f6ae7feda004bc377c25/aws/config.go#L712-L733) to **NOT** retry if the `ThrottlingException` error is being returned from the AWS API.

**Comment by upegnasrame** [comment]
> Because the Cost And Usage Report service has such a low API rate limit we may want to add custom retry logic to [`config.go`](https://github.com/hashicorp/terraform-provider-aws/blob/31bf342ed9d61ebb7c88f6ae7feda004bc377c25/aws/config.go#L712-L733) to **NOT** retry if the `ThrottlingException` error is being returned from the AWS API.

does this resource require s3 bucket to be in us-east-1 region ? i still can't create it in eu-west-1 where all resources are deployed.

**Comment by NK74** [comment]
Similar issue, is there a workaround ?

**Comment by leonardocoronel** [comment]
> does this resource require s3 bucket to be in us-east-1 region ? i still can't create it in eu-west-1 where all resources are deployed.

the bucket can be located in any AWS Region with the ACL access permissions on the S3 Bucket. All the code block to display the resources is correct. It is necessary to indicate the us-east-1 region in the provider

SOLUTION: Add block Provider

```hcl
provider "aws" {
  region = "us-east-1"
}
```
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cur_report_definition  

# Manages Cost and Usage Report Definitions.

Note
NOTE: The AWS Cost and Usage Report service is only available in us-east-1 currently.

Note
NOTE: If AWS Organizations is enabled, only the master account can use this resource.

**Comment by NK74** [comment]
You're a boss @leonardocoronel, thx

Solved on my side ;)

**Comment by ChristophShyper** [comment]
Yep. Looks like it got solved somewhere during those, almost, two years.
My code, from the previous comment, is now working as expected.
