### ISSUE TITLE
Better Lambda error

### ISSUE THREAD

**Issue by pauldraper** [hashicorp/terraform-provider-aws#13709]
When creating a Lambda function, I get

```
Error: Error creating Lambda function: ValidationException: 
	status code: 400, request id: 2db74e8f-49b6-4fe7-a005-55ac6afa6d23
```

I had used role name instead of role ARN. Does the API provide any further detail than status code 400 about the problem? If so, we should display that.

See also https://discuss.hashicorp.com/t/error-creating-lambda-function-validationexception/8192/3

**Comment by cosbor11** [comment]
+1 
I've have spend all day on trying to figure out what error is occurring and still have no hint, ValidationException is the Error message.  There is no documentation anywhere on what possible causes for the "ValidationException". What is validation rule has been violation?????

**Comment by cosbor11** [comment]
This happens when invoking a lambda from within another lambda

**Comment by maryfromcolorado** [comment]
I've had this error for many reasons, and have spent countless hours trying to figure it out each time.  Please fix this hashicorp, as lambdas are becoming critical infrastructure, and we need actual error to be able to resolve.

**Comment by IrmantasMarozas** [comment]
Stuck on this for 2 hours now, no idea what's wrong. I wouldn't mind if it was during plan, but now I have to apply change every time just to check.

**Comment by ricardoduval** [comment]
It's just sad the error message is so unhelpful and provides no insight whatsoever.

This is something that must be addressed as soon as possible. The amount of time spent trying to troubleshoot an error that you can find no correlation anywhere is absurd.

**Comment by ricardoduval** [comment]
I will actually retract my comment. In fact, what stinks is the AWS client response. I redacted the information of the execution in debug mode, but clearly, we can see the lack of any meaningful field in the response data.

`2022-01-27T01:32:49.265Z [INFO]  provider.terraform-provider-aws_v3.69.0_x5: 2022/01/27 01:32:49 [DEBUG] [aws-sdk-go] DEBUG: Request lambda/CreateFunction Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST /2015-03-31/functions HTTP/1.1
Host: lambda.us-east-1.amazonaws.com
User-Agent: APN/1.0 HashiCorp/1.0 Terraform/1.0.5 (+https://www.terraform.io) terraform-provider-aws/3.69.0 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go/1.42.18 (go1.16; linux; amd64)
Content-Length: 1478
Authorization: <REDACTED>, 
SignedHeaders=content-length;content-type;host;x-amz-date;x-amz-security-token, 
Signature=<REDACTED>
Content-Type: application/json
X-Amz-Date: 20220127T013249Z
X-Amz-Security-Token: <REDACTED>
Accept-Encoding: gzip

{"Code":{"ZipFile":"UEsDBBQA<REDACTED>AAAA="},"Description":"","Environment":{"Variables":{"RF_API_TOKEN":"rf/api/token","S3_INGEST_BUCKET":"xxxxxxxxxxxxxx"}},"FunctionName":"get_subdomains_from_rf","Handler":"get_subdomains.lambda_handler","MemorySize":128,"PackageType":"Zip","Publish":false,"Role":"arn:aws:iam::XXXXXXXX:role/acct-managed/ers-lambda-get_subdomains_from_rf-role","Runtime":"python3.8","Tags":{"Description":"This lambda gets the subdomains of the domains in the Domains List and ingests the data","Name":"Get Subdomains From RF","Source":"RF","Target":"xx"},"Timeout":120}
-----------------------------------------------------: timestamp=2022-01-27T01:32:49.264Z
2022-01-27T01:32:49.455Z [INFO]  provider.terraform-provider-aws_v3.69.0_x5: 2022/01/27 01:32:49 [DEBUG] [aws-sdk-go] DEBUG: Response lambda/CreateFunction Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 400 Bad Request
Content-Length: 594
Content-Type: application/json
Date: Thu, 27 Jan 2022 01:32:49 GMT
X-Amzn-Errortype: ValidationException
X-Amzn-Requestid: 37440ca9-0a51-4544-8aa3-881784cc9fbd


-----------------------------------------------------: timestamp=2022-01-27T01:32:49.454Z
2022-01-27T01:32:49.455Z [INFO]  provider.terraform-provider-aws_v3.69.0_x5: 2022/01/27 01:32:49 [DEBUG] [aws-sdk-go]: timestamp=2022-01-27T01:32:49.454Z
2022-01-27T01:32:49.455Z [INFO]  provider.terraform-provider-aws_v3.69.0_x5: 2022/01/27 01:32:49 [DEBUG] [aws-sdk-go] DEBUG: Validate Response lambda/CreateFunction failed, attempt 0/25, error ValidationException:
	status code: 400, request id: 37440ca9-0a51-4544-8aa3-881784cc9fbd: timestamp=2022-01-27T01:32:49.455Z
2022-01-27T01:32:49.455Z [INFO]  provider.terraform-provider-aws_v3.69.0_x5: 2022/01/27 01:32:49 [DEBUG] Unlocking "aws_lambda_function": timestamp=2022-01-27T01:32:49.455Z
2022-01-27T01:32:49.455Z [INFO]  provider.terraform-provider-aws_v3.69.0_x5: 2022/01/27 01:32:49 [DEBUG] Unlocked "aws_lambda_function": timestamp=2022-01-27T01:32:49.455Z
2022-01-27T01:32:49.458Z [DEBUG] Uploading remote state to S3: {
  Body: buffer(0xc0023ec630),`

**Comment by sergei-ivanov** [comment]
I have just wasted at least half a day trying to get to the root cause of `ValidationException` with absolutely no clues given by Terraform. Just like @ricardoduval I ran it Terraform with `TF_LOG=DEBUG`, which only confirmed the same error and did not give any further details. So I ended up crafting a command line equivalent which finally gave me a proper error message. In my case it was:
```
$ aws lambda create-function <...>

An error occurred (ValidationException) when calling the CreateFunction operation: 1 validation error detected: Value '1800' at 'timeout' failed to satisfy constraint: Member must have value less than or equal to 900
```

**Comment by sergei-ivanov** [comment]
I think we have some compatibility problem between AWS SDK and the underlying AWS API for Lambda.

I decided to dig a bit deeper.

Here's the API response, taken from the Terraform debug log:

```
2022-02-01T20:12:59.603Z [INFO]  provider.terraform-provider-aws_v3.74.0_x5: 2022/02/01 20:12:59 [DEBUG] [aws-sdk-go] DEBUG: Response lambda/CreateFunction Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 400 Bad Request
Content-Length: 147
Content-Type: application/json
Date: Tue, 01 Feb 2022 20:12:59 GMT
X-Amzn-Errortype: ValidationException
X-Amzn-Requestid: bdd1fc86-1e92-430f-b386-43b458f6c603


-----------------------------------------------------: timestamp=2022-02-01T20:12:59.603Z
```

Apparently there's 147 bytes of JSON content, which must be an encoded error message, which the provider needs to extract  and return to Terraform. But the provider seems to throw away the error message and then we simply get a "computer says no" in the console:

```
│ Error: error creating Lambda Function (1): ValidationException: 
│ 	status code: 400, request id: bdd1fc86-1e92-430f-b386-43b458f6c603
```

So I tried to obtain the content of that error message. Running my AWS CLI command with `--debug` I got:

```
2022-02-02 00:42:23,232 - MainThread - urllib3.connectionpool - DEBUG - https://lambda.eu-west-2.amazonaws.com:443 "POST /2015-03-31/functions HTTP/1.1" 400 147
2022-02-02 00:42:23,233 - MainThread - botocore.parsers - DEBUG - Response headers: {'Date': 'Wed, 02 Feb 2022 00:42:23 GMT', 'Content-Type': 'application/json', 'Content-Length': '147', 'Connection': 'keep-alive', 'x-amzn-RequestId': '78eca618-d5bb-41ab-8647-9d152a7fa349', 'x-amzn-ErrorType': 'ValidationException'}
2022-02-02 00:42:23,233 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"message":"1 validation error detected: Value \'1800\' at \'timeout\' failed to satisfy constraint: Member must have value less than or equal to 900"}'
```

And if I copy the request parameters from Terraform debug log and stick them into an HTTP client, I get a similar response:

```
HTTP/1.1 400 
Date: Wed, 02 Feb 2022 00:52:26 GMT
Content-Type: application/json
Content-Length: 147
Connection: keep-alive
x-amzn-RequestId: 5933fbf3-bde1-46ef-bc09-d6b8e2014803
x-amzn-ErrorType: ValidationException

{
  "message": "1 validation error detected: Value '1800' at 'timeout' failed to satisfy constraint: Member must have value less than or equal to 900"
}
```

But [AWS API](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html) for `CreateFunction` does not list `ValidationException` among possible error types. The closest it gets to it is `InvalidParameterValueException`.

Likewise, `aws-sdk-go` does not have `ValidationException` in the list of [generated exception classes](https://github.com/aws/aws-sdk-go/blob/e63fed29763ffbab38f38d280895f69ce31b3637/service/lambda/errors.go#L237) for Lambda API, most likely because it is absent from the API schema. An example of API that **does** support `ValidationException` and has it in the generated API/SDK is [ACM](https://github.com/aws/aws-sdk-go/blob/e63fed29763ffbab38f38d280895f69ce31b3637/service/acm/errors.go#L130).

So I suspect that somehow Lambda service sends back an error type that is not part of the schema for Lambda API, and hence it is not recognised by `aws-sdk-go`, which makes it fall back to the default implementation, which does not know how to format the message.

**Comment by webdev-q3** [comment]
In my case it was name of the lambda function which was incorrect. I was using spaces and that's not allowed.

**Comment by jacobtb23** [comment]
Same for me. The function name and handler had invalid characters. Once I did that the error went away.

**Comment by chrisdlangton** [comment]
I'm seeing `ValidationException` but for Lambda Function URL, i.e. `error creating Lambda Function URL` is all I get

How does one get access to the AWS responses from use of terraform itself?

Frankly, if I have to reproduce in CLI i'll abandon the broken and clearly brittle Terraform and have no problems managing the CLI that not only stays compatible with AWS changes, it is what I needed to use here to progress and I might as well stay with it if Terraform can't even give us the debugging tools we need to figure out these incompatibility issues ourselves or have decent error handling and output..

**Comment by chrisdlangton** [comment]
The issue for me was having a comma in the tag value
I had spent hours trying to figure it out too
It was only when I ABANDONED Terraform and used the AWS CLI directly (i.e. boto3, for which I contributed to myself before and easily saw how they provide good error feedback) and then went to the Go SDK and found the exact same validation ported to Go

It's simply to do validation when it's already shown and the same programming language
it's built in to AWS tools
all Hashicorp has to do is read AWS source in the Go SDK and copy/paste over the validation
Hashicorp are claiming their tools are not just at least as good as AWS, they claim they are better! And yet they don't even do the same validation, or much validation at all based on this thread

Poor effort when you look at a thread like this and feel the pain yourself it makes it blatantly obvious Hashicorp are not interested in maintaining good 'fundamental' tools anymore, their too focused on shiny new stuff

**Comment by Navapon** [comment]
For my case environment variable got extra space to spend an hour looking at it.

**Comment by micksatana** [comment]
In my case, it was about `s3_existing_package` `bucket`. The `bucket` should be name not ARN. Hope this might help someone.

**Comment by draoncc** [comment]
I've been attempting to replicate my Terraform plan with the AWS CLI, but when doing so the AWS CLI lambda create-function command creates the function successfully, whereas Terraform Cloud apply will fail with a nondescript ValidationException.

Here is a description of my specific case: https://stackoverflow.com/questions/74561968/terraform-cloud-apply-lambda-function-fails-with-validationexception-aws-cli-la

This is extremely frustrating and makes it practically impossible to effectively debug whatever issue I might be running into with validation.

**Comment by remidebette** [comment]
Please deliver this, also lost precious hours debugging this

**Comment by jar-b** [comment]
This may be an upstream issue in the `aws-go-sdk` V1 library (see https://github.com/aws/aws-sdk-go/issues/4733 for a complete writeup). In this case, the provider itself is not filtering any messaging returned from the `CreateFunction` call at all, the additional information just isn't there.

While we await a response on the bug report, we'll also investigate updating to V2 of the AWS Go SDK for the Lambda function resource.
