### ISSUE TITLE
Failed to update scaling policy: ValidationException: You cannot change a TargetTrackingScaling policy to a non TargetTrackingScaling policy, or vice versa

### ISSUE THREAD

**Issue by deepakbaug** [hashicorp/terraform-provider-aws#13710]
Is there any way to update non TargetTrackingScaling  to a TargetTrackingScaling policy without destroying existing infra ?
- Terraform v0.11.14
- provider.aws v2.65.0

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ewbankkit** [comment]
@deepakbaug Thanks for opening this issue.
Which resource are you using that reports this error?

**Comment by deepakbaug** [comment]
AWS ECS Fargate

**Comment by kynefuk** [comment]
any update?

**Comment by alexey-taliuk** [comment]
any news on that?
