### ISSUE TITLE
aws_eip intermittent AuthFailure during destroy

### ISSUE THREAD

**Issue by camlow325** [hashicorp/terraform-provider-aws#13763]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.12.20
+ provider.aws v2.58.0
```

### Affected Resource(s)

* aws_eip

### Terraform Configuration Files

```hcl
locals {
  public_subnets     = ["10.0.2.0/24", "10.0.4.0/24", "10.0.6.0/24"]
  subnet_count       = length(local.public_subnets) > length(data.aws_availability_zones.available.names) ? length(data.aws_availability_zones.available.names) : length(local.public_subnets)
  resource_base_name = "test"
}

data "aws_availability_zones" "available" {
  state = "available"
}

resource "aws_vpc" "test" {
  cidr_block = "10.0.0.0/16"
  tags = {
    Name = local.resource_base_name
  }
}

resource "aws_internet_gateway" "test" {
  vpc_id = aws_vpc.test.id
  tags = {
    Name = local.resource_base_name
  }
}

resource "aws_subnet" "test" {
  count                   = local.subnet_count
  vpc_id                  = aws_vpc.test.id
  cidr_block              = local.public_subnets[count.index]
  availability_zone       = data.aws_availability_zones.available.names[count.index]
  map_public_ip_on_launch = true
  tags = {
    Name = "${local.resource_base_name}-${count.index}"
  }
}

resource "aws_eip" "test" {
  count            = local.subnet_count
  vpc              = true
  public_ipv4_pool = "amazon"
  tags = {
    Name = "${local.resource_base_name}-${count.index}"
  }
}

resource "aws_route53_zone" "test" {
  name = "test1234abcd5678.com"
  tags = {
    Name = local.resource_base_name
  }
}

resource "aws_route53_record" "test" {
  count          = local.subnet_count
  zone_id        = aws_route53_zone.test.id
  name           = local.resource_base_name
  type           = "A"
  ttl            = "60"
  set_identifier = "${local.resource_base_name}-${count.index}"
  weighted_routing_policy {
    weight = "255"
  }
  records = [
    aws_eip.test[count.index].public_ip
  ]
}

resource "aws_lb" "test" {
  name                             = local.resource_base_name
  internal                         = false
  load_balancer_type               = "network"
  enable_deletion_protection       = false
  enable_cross_zone_load_balancing = false
  ip_address_type                  = "ipv4"

  dynamic "subnet_mapping" {
    for_each = aws_eip.test[*].id

    content {
      subnet_id     = aws_subnet.test[subnet_mapping.key].id
      allocation_id = subnet_mapping.value
    }
  }

  depends_on = [aws_internet_gateway.test]

  tags = {
    Name = local.resource_base_name
  }
}
```

### Debug Output

I haven't been able to get this failure to occur with debug logging on, so I don't have any detailed output to share yet.

### Expected Behavior

The `terraform destroy` should be successful.

### Actual Behavior

In most cases, the `terraform destroy` is successful. For the failure case, this error appeared:

```
Error: AuthFailure: You do not have permission to access the specified resource.
  status code: 400, request id: xxx
```

In the Terraform state, the only remaining resource after the failure is one of the `aws_eip` instances. All other resources have successfully been removed. This leads me to believe that the problem occurred when trying to destroy the `aws_eip` resource.

If `terraform destroy` is run again sometime later with the same configuration, the destroy is successful. This may indicate that the problem is an eventual consistency issue, not sure.

### Steps to Reproduce

1. `terraform apply`
1. `terraform destroy`

### Important Factoids

I'm not sure which of the resources related to the `aws_eip` resource might be critical in this case, so I included all of the ones involved when the error occurs.

### References

* #3572 - The same error message was displayed for the same resource was encountered in this case but the nature of the error seems different. In the above test case, `network_interface` is not explicitly set for the `aws_eip` resource.

**Comment by MeghanaSrinath** [comment]
We are also facing the exact same issue with the EIP module and the resources are destroyed on the second run of terraform destroy. Is there any update on this yet?

**Comment by justinrowan** [comment]
I'm having the same issue with an EIP created and an allocation_id set for an NLB. First destroy gives me AuthFailure on the EIP, running destroy a second time succeeds.
