### ISSUE TITLE
CloudFront Lambda@Edge Cannot use $LATEST qualifier

### ISSUE THREAD

**Issue by canadiannomad** [hashicorp/terraform-provider-aws#13799]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform version
Terraform v0.12.21
+ provider.archive v1.3.0
+ provider.aws v2.66.0
+ provider.random v2.2.1
```

### Affected Resource(s)

* aws_cloudfront_distribution
* data.aws_lambda_function

### Terraform Configuration Files

```hcl
data "aws_lambda_function" "lambda_at_edge" {
  function_name = "lambda_at_edge"
}
resource "aws_cloudfront_distribution" "my_cloudfront" {
# ...
ordered_cache_behavior {
# ...
    lambda_function_association {
      event_type   = "viewer-request"
      lambda_arn   = "${data.aws_lambda_function.lambda_at_edge.qualified_arn}"
      include_body = false
    }
# ...
}
# ...
}
```

### Expected Behavior

CloudFront requires a fully qualified arn... $LATEST won't work.
I'm trying to find any way to get the latest lambda's version number so that I can qualify the lambda arn properly.
We need a qualified arn similar to
```
arn:aws:lambda:us-east-1:123456789:function:lambda_at_edge:21
```
Note an actual numbered version, not $LATEST.

### Actual Behavior

```
Error: error updating CloudFront Distribution (XXXXXXXXXXXX): InvalidLambdaFunctionAssociation: The function ARN must reference a specific function version. (The ARN must end with the version number.) ARN: arn:aws:lambda:us-east-1:123456789:function:lambda_at_edge:$LATEST
	status code: 400, request id: x-x-x-x-x
```

### Steps to Reproduce

1. `terraform apply`

### References

* #4446
* https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-edge-edit-function.html "You can't create triggers for $LATEST."

**Comment by kevinkuszyk** [comment]
@canadiannomad I think you need to publish your lambdas in order to get a fully qualified arn with the version number.  

You need something like this where you define the lambda:

```
resource "aws_lambda_function" "example" {
  ...
  publish = true
}
```

**Comment by canadiannomad** [comment]
They are published.  This is for the data resource.

**Comment by tecnobrat** [comment]
Looks like the data resource has different code than the non-data resource.

Specifically the non-data version has this: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_lambda_function.go#L603-L630

**Comment by tecnobrat** [comment]
Looks like the data resource has different code than the non-data resource.

Specifically the non-data version has this: https://github.com/terraform-providers/terraform-provider-aws/blob/c11f488967bc3ba001124f862e96421c6de5ba28/aws/resource_aws_lambda_function.go#L603-L630

**Comment by TheMedina** [comment]
I'm still a little confused on what the work around is for this? @canadiannomad, how did you work around this?

**Comment by AndreiPaulau** [comment]
Hey, do somebody workarounded this (except the getting version from remote state resource - working but ugly)?
Initially I did lambda and cloudfront resources in the same .tf template. But finally TF(or AWS) can't gracefully purge lambda edge in timely manner and tf destroy fails. Workaround - remove from state and purge the deployment w/o lambda.

OK if we can't deal with LambdaEdge then let's make it as a separate .tf template and onboard it via data source. Aha, yeah ,boy! =) Take it - quilified_arn returns $Latest

**Comment by Maxwe11** [comment]
>Hey, do somebody workarounded this (except the getting version from remote state resource - working but ugly)?
Initially I did lambda and cloudfront resources in the same .tf template. But finally TF(or AWS) can't gracefully purge lambda edge in timely manner and tf destroy fails. Workaround - remove from state and purge the deployment w/o lambda.

As a workaround just read/write quilified arn from/to SSM

**Comment by tymik** [comment]
seems that [alias for Lambda@Edge should work](https://github.com/hashicorp/terraform-provider-aws/issues/10038#issuecomment-853450068) for that - gonna test it after the weekend

**Comment by tymik** [comment]
> seems that [alias for Lambda@Edge should work](https://github.com/hashicorp/terraform-provider-aws/issues/10038#issuecomment-853450068) for that - gonna test it after the weekend

Confirmed - works like a charm, perfect solution and easiest to implement!

**Comment by mattes3** [comment]
Found a workaround: I changed `lambda_function_association` to `function_association`, and it worked! Like so:

```hcl
function_association {
  event_type   = "viewer-request"
  function_arn = aws_cloudfront_function.lambda_at_edge.arn
}

resource "aws_cloudfront_function" "lambda_at_edge" {
  name    = "MyMagicEdgeFunction"
  runtime = "cloudfront-js-1.0"
  publish = true
  code    = file("${path.module}/cloudfrontMagicFunction.js")
}
```

**Comment by rstml** [comment]
> Found a workaround: I changed `lambda_function_association` to `function_association`, and it worked! Like so:

`lambda_function_association` and `function_association` are two completely different mechanisms: https://aws.amazon.com/blogs/aws/introducing-cloudfront-functions-run-your-code-at-the-edge-with-low-latency-at-any-scale/

**Comment by gforien** [comment]
I don't see how this is related to the terraform provider. Cloudfront documentation states
> **LambdaFunctionARN**
    The ARN of the Lambda@Edge function. You must specify the ARN of a function version; you can't specify an alias or $LATEST.
    Type: String
    Required: Yes


https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_LambdaFunctionAssociation.html#cloudfront-Type-LambdaFunctionAssociation-LambdaFunctionARN

**Comment by canadiannomad** [comment]
@gforien Yeah this was 2 years ago.. $LATEST didn't work at that time. On top of that the data provider for aws_lambda_function now works as expected... I'm going to close this ticket, as I don't think it is an issue anymore.
