### ISSUE TITLE
EKS Node Group ASG metrics

### ISSUE THREAD

**Issue by bpoland** [hashicorp/terraform-provider-aws#13793]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would it be possible to enable metrics for autoscaling groups created by the `aws_eks_node_group` resource?  The standalone `aws_autoscaling_group` resource has `enabled_metrics`.  I have tried enabling in the AWS console after the fact but subsequent applies of the node group overwrite the setting :(

### New or Affected Resource(s)

* `aws_eks_node_group`

### Potential Terraform Configuration

This seems to make the most sense with how things are set up currently, but I'm not too picky as long as it can be done :)

```hcl
resource "aws_eks_node_group" "example" {
  # ... other configurations ...

  scaling_config {
    enabled_metrics = ["GroupInServiceCapacity"]

    # ... other configurations ...
  }
}
```

### References

* (none)

**Comment by bpoland** [comment]
It looks like this is supported in the `terraform-aws-eks` module: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/local.tf#L71

**Comment by packrat386** [comment]
Stable link to the config line in question https://github.com/terraform-aws-modules/terraform-aws-eks/blob/3d2f7d28c132e62a91309eafd88c5d1d4500eb2b/local.tf#L72

**Comment by agirlnamedsophia** [comment]
Am also interested in support for this feature!

**Comment by bflad** [comment]
Hi folks 👋  Thank you for raising this feature request.

The [EKS API Reference](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html) does not include functionality like this directly in the EKS service, so therefore it is not something that would be implemented in the Terraform AWS Provider `aws_eks_node_group` resource. The links to the `terraform-aws-eks` module above are threading through the `enabled_metrics` argument value into the `aws_autoscaling_group` resource, which is presumably the only option that is "supported" by the EKS and Auto Scaling APIs. If there are issues with directly managing the Auto Scaling metrics in this manner, it would be best to talk to the service team about this issue.

If you have suggestions for improving the EKS API, you can submit an issue to the [aws/containers-roadmap repository](https://github.com/aws/containers-roadmap) (where the product managers for that service tend to monitor) and/or submit an AWS Support case that will get routed to the appropriate service team. If/when the API supports managing the functionality directly in the EKS API, we can take a fresh look at implementing it in the Terraform AWS Provider to match. Thank you.
