### ISSUE TITLE
Using aws_ebs_default_kms_key key_arn forces instance replacement

### ISSUE THREAD

**Issue by kyl191** [hashicorp/terraform-provider-aws#13860]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.12.26
+ provider.aws v2.67.0
```

### Affected Resource(s)

* aws_ebs_default_kms_key

### Terraform Configuration Files

```hcl
data "aws_ebs_default_kms_key" "current" {}

resource "aws_instance" "instance" {
  key_name      = aws_key_key.key_name
  ami           = "ami-0daa0ab8c404bda92"
  instance_type = "t3.micro"

  root_block_device {
    volume_type = "gp2"
    volume_size = 20
    encrypted   = true
    kms_key_id  = data.aws_ebs_default_kms_key.current.key_arn
  }
}
```

### Debug Output
https://gist.github.com/kyl191/13388519becc6ac65c520bbb7541058a

### Expected Behavior

Repeated `terraform apply` runs wouldn't change the instance

### Actual Behavior

Once the instance is created, subsequent terraform runs want to replace the instance:
```
~ root_block_device {
            delete_on_termination = true
          ~ device_name           = "/dev/sda1" -> (known after apply)
            encrypted             = true
          ~ iops                  = 100 -> (known after apply)
          ~ kms_key_id            = "arn:aws:kms:us-west-2:<redacted>:key/b25f8e1d-03ff-4df5-a0ad-267f95d00c0c" -> "alias/aws/ebs" # forces replacement
```

### Steps to Reproduce

1. `terraform apply`
2. Wait for the instance to be created
3. Rerun `terraform apply`

### Important Factoids
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_GetEbsDefaultKmsKeyId.html actually returns the alias, not the ARN, even after the key is created.

I think you'll have to resolve the alias, and return that ARN. 
Or convince the EC2 API team to return a list of KMS aliases as well, which will probably be harder.

**Comment by kyl191** [comment]
Workaround is to add
```
lifecycle {
    ignore_changes = [root_block_device[0].kms_key_id]
  }
```
to the instance. Not optimal, but it works.

**Comment by anGie44** [comment]
Hi @kyl191, thank you for creating this issue! After coming across #15137, the workaround suggested by @karnauskas looks like a good candidate here for your config. It should eliminate the repeated replacement you're seeing after each `apply`. You'll just need to add an additional data_source (`aws_kms_key`) as provided in the comment to then reference in the `aws_instance` resource 

https://github.com/terraform-providers/terraform-provider-aws/issues/15137#issuecomment-691730866

**Comment by kyl191** [comment]
Hey @anGie44 -just confirming that the workaround of the extra `aws_kms_key` data source still works on terraform v0.14.2

You mentioned asking the team to add the workaround to the docs, but https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ebs_default_kms_key hasn't been updated.  

I'm not sure if you want to close this issue in favour of #15137, or close #15137 in favour of this one, but they're pretty much identical.
