### ISSUE TITLE
`allow_major_version_upgrade` is missing from aws_rds_cluster_instance

### ISSUE THREAD

**Issue by ps2goat** [hashicorp/terraform-provider-aws#13874]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.26
aws providers version 2.66 (I believe, I was more watching the user)

### Affected Resource(s)

* aws_rds_cluster_instance

It seems that this is missing implementation of the `AllowMajorVersionUpgrade` that CloudFormation uses. There was a similar bug on the core terraform project for the `aws_db_instance` from 2015, but I figured this issue was pretty self-explanatory. The cluster instance is an Aurora instance, and we were trying to upgrade the major version, but it had `AllowMajorVersionUpgrade: false` set via CloudFormation.

We can use CloudFormation or the AWS CLI to adjust this value, but wanted to bring it to your attention that this config value was missing, even in the documentation. We did try to use the value from the regular `aws_db_instance`, which was `allow_major_version_upgrade`, but terraform output that the property was unexpected.

**Comment by johnsonaj** [comment]
After some review, and testing, it looks like adding `allow_major_version_upgrade` to an `aws_rds_cluster_instance` has no effect on the resource itself when the instance is a part of a cluster. To upgrade the major version on a RDS cluster the `allow_major_version_upgrade` input should be used on the `aws_rds_cluster` resource itself.

**Comment by johnsonaj** [comment]
Closing since feature to upgrade major version on clusters was merged in #14709
