### ISSUE TITLE
aws version 2.67 causes old tf error: connection is shut down

### ISSUE THREAD

**Issue by david-salkin** [hashicorp/terraform-provider-aws#13919]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
11.10

### Affected Resource(s)

* provider.aws

### Debug Output
Error: module.account_provisioning.module.ebs_governance.provider.aws.ap-northeast-1: connection is shut down
Error: module.account_provisioning.module.vpc_flow_logs_governance.provider.aws.ap-northeast-1: unexpected EOF

This is inconsistent - approx 50% execution of the same plan will succeed.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids
Rolling back to 2.66 solves issue.

### References

* #0000

**Comment by ewbankkit** [comment]
@david-salkin Thanks for raising this issue. Do you have any more output that would help debug this, for example anything that looks like a stack trace?

**Comment by david-salkin** [comment]
Thanks ewbankkit. I have attached the CodeBuild error file which includes the stdout of TF_LOG (TRACE). 
At line 975962:
2020/06/24 12:49:31 [ERROR] root.account_provisioning.required_tags: eval: *terraform.EvalInitProvider, err: unexpected EOF
and then at line 975998
2020/06/24 12:49:31 [ERROR] root.account_provisioning.required_tags: eval: *terraform.EvalInitProvider, err: connection is shut down

[error(1).zip](https://github.com/terraform-providers/terraform-provider-aws/files/4825582/error.1.zip)

**Comment by david-salkin** [comment]
Also note that version 2.67 includes upgrade of aws-sdk-go to v1.32.0.
And that the error above is preceeded by this:
2020/06/24 12:49:31 [ERR] yamux: keepalive failed: session shutdown

**Comment by david-salkin** [comment]
Any ideas on this? Please note: rollback to version 2.66 _succeeds_.

**Comment by david-salkin** [comment]
Solved. As per https://support.hashicorp.com/hc/en-us/articles/360022608473-Runs-sometimes-failing-with-connection-is-shut-down-or-unexpected-EOF-
"Terraform runs are exceeding the currently configured maximum memory for the run containers, and need more memory allocated per run to complete successfully."
Increasing CodeBuild's "Compute" mem allocation setting solved the issue.
