### ISSUE TITLE
aws_eip support new attributes NetworkBorderGroup and address

### ISSUE THREAD

**Issue by FireballDWF** [hashicorp/terraform-provider-aws#13998]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

1. Support the NetworkBorderGroup attribute that the AllocateAddress API supports to provide IP addresses advertised by LocalZones and Wavelength Zones
2. Support the Address attribute that the AllocateAddress API supports to request a specific IP

### New or Affected Resource(s)

* aws_eip

### Potential Terraform Configuration

```hcl
network_border_group - The location from which the IP address is advertised. Use this parameter to limit the address to this location
```

### References

* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AllocateAddress.html

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 3.14.0 of the Terraform AWS Provider, likely later today. Thanks to @drexler for the implementation. 👍
