### ISSUE TITLE
Support BYOIP for Global Accelerator in AWS Provider

### ISSUE THREAD

**Issue by gtpgi** [hashicorp/terraform-provider-aws#14002]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS added the ability for customers to provide their own IP addresses (BYOIP) when provisioning a Global Accelerator accelerator. This feature request is to add support for BYOIP i Global Accelerator in the Terraform AWS provider.

### New or Affected Resource(s)

`aws_globalaccelerator_accelerator`

**Comment by ewbankkit** [comment]
[Developer Guide](https://docs.aws.amazon.com/global-accelerator/latest/dg/using-byoip.html).

Related: https://github.com/hashicorp/terraform-provider-aws/issues/6521.

**Comment by pmcevoy** [comment]
Please don't let this request die...

**Comment by s-vanam** [comment]
@ewbankkit - Any plans to add this soon to the Global Accelerator resource ?

**Comment by ewbankkit** [comment]
I think the biggest blocker to implementing this would be testing - AFAIK no maintainers have access to a BYOIP pool.

**Comment by s-vanam** [comment]
Hello @ewbankkit I can help you with that , we already have BYOIP ranges for GA and can help you with the testing

**Comment by dginzbourg** [comment]
any progress here? I can test it as well

**Comment by gerricchaplin** [comment]
Hello @ewbankkit happy to help with testing here too. We have IPv4 and IPv6 available for testing should you require different cases.

**Comment by danhanks** [comment]
Hello @ewbankkit, also willing to help with testing, and eager to see this implemented.

**Comment by malcolm061990** [comment]
Hi, guys.
16 months passed. Do you have any progress on it?
We have BYOIP ranges and we can test it too.

**Comment by AdamTylerLynch** [comment]
Related #21998 

Need to scope of effort to to finish BYOIP.

**Comment by AdamTylerLynch** [comment]
I will be picking this issue up to work on.

**Comment by gerricchaplin** [comment]
@AdamTylerLynch do you have some IP space to test this with?
We are unfortunately about to use our last IPv4 range.
We do have IPv6 available for testing but GA does not support IPv6.

**Comment by AdamTylerLynch** [comment]
> @AdamTylerLynch do you have some IP space to test this with? We are unfortunately about to use our last IPv4 range. We do have IPv6 available for testing but GA does not support IPv6.

Thank you for asking. Yes, I work for AWS and I have IPv4 and IPv6 space that I can test with.

**Comment by saurabh19n** [comment]
@AdamTylerLynch Do we have any update on this enhancement? Not seeing any posts since last 6 months here.
