### ISSUE TITLE
Standardize Acceptance Testing IAM Role Naming [Part 1]

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#14003]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A lot of our older acceptance testing does not implement the more common practice of randomized naming with the prefix `tf-acc-test` (e.g. `acctest.RandomWithPrefix("tf-acc-test")`). @anGie44 found some great examples of oddly named ones, in addition to those added as part of some recent `aws_iam_role` test sweeper updates. This list is not exhaustive for the whole provider, but it represents a nice chunk of effort.

### Affected Resources

Ideally these would be submitted per resource to reduce review time and since many will likely require some additional test refactoring. 

- [ ] aws_autoscaling_lifecycle_hook
- [ ] aws_cloudwatch_event_target
- [ ] aws_cloudwatch_log_destination
- [ ] aws_db_option_group
- [ ] aws_iot_role
- [ ] aws_msk_cluster
- [ ] aws_rds_cluster
- [ ] aws_sns_topic
- [ ] aws_ssm_maintenance_window_task

When updated, the `aws_iam_role` sweeper prefixes should be removed.

### References

- https://github.com/terraform-providers/terraform-provider-aws/pull/13901#discussion_r448009180

**Comment by YakDriver** [comment]
This continues to be a work in progress.
