### ISSUE TITLE
Add Wildcard to tag:<> filter in Data resource

### ISSUE THREAD

**Issue by privomark** [hashicorp/terraform-provider-aws#14022]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow for wildcards in the `tag:Name` of a data filter

**Current:**
```hcl
data "aws_subnet_ids" "selected" {
  filter {
    name   = "tag: kubernetes.io/role/internal-elb"
    values = ["1"]
  }
}
```

### New or Affected Resource(s)

* aws_subnet_ids

### Potential Terraform Configuration

```hcl
data "aws_subnet_ids" "selected" {
  filter {
    name   = "tag:kubernetes*"
    values = ["1"]
  }
}
```

### References

* https://www.terraform.io/docs/providers/aws/d/subnet_ids.html#tags

**Comment by GioLauria** [comment]
Struggling with the same issue. Any improvements?

**Comment by liorgolan-yakim** [comment]
Any update for this?
