### ISSUE TITLE
aws_batch_job_definition | Error: "Container properties should not be empty"

### ISSUE THREAD

**Issue by Geartrixy** [hashicorp/terraform-provider-aws#14024]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

*aws_batch_job_definition

### Terraform Version

```
Terraform v0.12.23
+ provider.aws v2.68.0
+ provider.template v2.1.2
```

### Terraform Configuration Files

```hcl
# job definition
resource "aws_batch_job_definition" "job_definition" {
  name = var.batch_job_definition_name
  type = "container"
  
  retry_strategy {
      attempts = var.retry_strategy_attempts
  }

  timeout {
    attempt_duration_seconds = var.timeout_attempt_duration_seconds
  }

  # API Container Properties: https://docs.aws.amazon.com/batch/latest/APIReference/API_ContainerProperties.html
  container_properties = data.template_file.job_definition.rendered
}

# template file
data "template_file" "job_definition" {
  template = file("${path.module}/job_definitions/job_definition.json")

vars = {
    command                = jsonencode(var.job_def_command)
    image                  = jsonencode(var.job_def_image)
    jobrolearn             = jsonencode(aws_iam_role.ecs_task.arn)
    memory                 = var.job_def_memory
    vcpus                  = var.job_def_vcpus
    privileged             = var.job_def_privileged
    readonlyrootfilesystem = var.job_def_readonly_root_file_system
    gpus                   = var.job_def_gpus
  }
}

# job definition json
{
    "containerProperties": {
        "command": [ ${command
            }
        ],
        "image": ${image
        },
        "jobRoleArn": ${jobrolearn
        },
        "memory": ${memory
        },
        "vcpus": ${vcpus
        }
    },
    "nodeProperties": {
        "nodeRangeProperties": [
            {
                "container": {
                    "privileged": ${privileged
                    },
                    "readonlyRootFilesystem": ${readonlyrootfilesystem
                    },
                    "resourceRequirements": [
                        {
                            "type": "GPU",
                            "value": ${gpus
                            }
                        }
                    ]
                }
            }
        ]
    }
}
```

### Debug Output
https://gist.github.com/Geartrixy/9d5944e0a60c8c06dfeba37664b61927

### Expected Behavior

Job definition for batch gets created.

### Actual Behavior

Error: : Error executing request, Exception : Container properties should not be empty, RequestId: b61cd41a-6f8f-49fe-b3b2-2b0e6d01e222
        status code: 400, request id: b61cd41a-6f8f-49fe-b3b2-2b0e6d01e222 "tf-my-job"

  on modules\batch\batch.tf line 40, in resource "aws_batch_job_definition" "job_definition":
  40: resource "aws_batch_job_definition" "job_definition" {

### Steps to Reproduce

`terraform apply`

**Comment by Geartrixy** [comment]
Upgraded terraform version and receive the same error

```
Terraform v0.12.28
+ provider.aws v2.68.0
+ provider.template v2.1.2
```
Added debug with trace here: https://gist.github.com/Geartrixy/6f3bb11216a215f297f7773d293fb75b

**Comment by Zavestang** [comment]
Guys what the F on this, I went back to 12.2 and same issue?

**Comment by Geartrixy** [comment]
Think this is the issue: "planned value cty.NullVal(cty.String) does not match config value cty.StringVal"

```
2020/07/02 07:46:30 [WARN] Provider "registry.terraform.io/-/aws" produced an invalid plan for module.my_module.aws_batch_job_definition.job_definition, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .container_properties: planned value cty.NullVal(cty.String) does not match config value cty.StringVal("{\r\n    \"containerProperties\": {\r\n        \"command\": [ \"python /src/bulkload.py\"\r\n        ],\r\n        \"image\": \"123456789.dkr.ecr.eu-central-1.amazonaws.com/test:latest\",\r\n        \"jobRoleArn\": \"arn:aws:iam::733412096037:role/tf-ecs-task-container-my\",\r\n        \"memory\": 2048,\r\n        \"vcpus\": 2\r\n    },\r\n    \"nodeProperties\": {\r\n        \"nodeRangeProperties\": [\r\n            {\r\n                \"container\": {\r\n                    \"privileged\": false,\r\n                    \"readonlyRootFilesystem\": false,\r\n                    \"resourceRequirements\": [\r\n                        {\r\n                            \"type\": \"GPU\",\r\n                            \"value\": 0\r\n                        }\r\n                    ]\r\n                }\r\n            }\r\n        ]\r\n    }\r\n}"
```

**Comment by Geartrixy** [comment]
Is there any status update on this?

Thanks in advance!

**Comment by renxunsaky** [comment]
Hello, I found the problem:
you should only put the content inside "containerProperties" json block. That's what the Terraform expecting too.
But it's true, the error message is not clear at all.

**Comment by basilnsage** [comment]
I ran into this myself and may have something for you. The API request to the AWS backend has a top-level `containerProperties` field, yes, but underneath Terraform is unmarshalling the JSON you provide into a type built on the `ContainerProperties` type in the underlying library https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.42.44/service/batch#ContainerProperties.

Relevant line in the Terraform provider https://github.com/hashicorp/terraform-provider-aws/blob/a3c3027750444c59e022b46013f157c4446716d0/internal/service/batch/job_definition.go#L333
Relevant line wrapping the Golang AWS SDK type https://github.com/hashicorp/terraform-provider-aws/blob/a3c3027750444c59e022b46013f157c4446716d0/internal/service/batch/container_properties.go#L14

Neither type defines a public `containerProperties` field that the JSON can be unmarshalled into, so the result is an empty `ContainerProperties` struct. This is consistent with the `container_properties: planned value cty.NullVal(cty.String) does not match config value cty.StringVal(...` warning which, to me, indicates that the planned value is null.

When I ran into this, my terraform plan output looks something like 
```
Terraform will perform the following actions:

  # aws_batch_job_definition.test will be created
  + resource "aws_batch_job_definition" "test" {
      + arn                   = (known after apply)
      + id                    = (known after apply)
      + name                  = "hello_world_small_cpu"
      + platform_capabilities = [
          + "EC2",
        ]
      + propagate_tags        = true
      + revision              = (known after apply)
      + tags                  = {
          + "project" = "saptProduct"
        }
      + tags_all              = {
          + "terraform" = "true"
        }
      + type                  = "container"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```
Note the missing `container_properties` attribute.

For my Terraform, I fixed this by using the fields defined here https://docs.aws.amazon.com/batch/latest/APIReference/API_ContainerProperties.html as the top-level fields in my JSON object. My JSON template file looks something like
```
${jsonencode({
    "image": "${image_name}",
    "command": cmd,
    "resourceRequirements": [
        {
            "type": "MEMORY",
            "value": "${cntr_memory}"
        },
        {
            "type": "VCPU",
            "value": "${cntr_vcpus}"
        }
  ],
  "type": "container",
  "jobDefinitionName": "${def_name}"
})}
```

**Comment by gdavison** [comment]
Hello. As @basilnsage suggests, the values in the `container_properties` JSON can only be the `"containerProperties"` key in your example, i.e. `"command"`, `"image"`, `"jobRoleArn"`, `"memory"`,  and `"vcpus"`. Because it contains the keys `"containerProperties"` and `"nodeProperties"` at the top level, it fails to parse.
