### ISSUE TITLE
SNS-HTTPS subscription with delivery policy always shows up in plan

### ISSUE THREAD

**Issue by aaleksandrov** [hashicorp/terraform-provider-aws#14041]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.8
+ provider.aws v2.51.0
```
But this issue is here for 1+ years

### Affected Resource(s)

* aws_sns_topic_subscription

### Terraform Configuration Files

```
terraform {
  required_version = "0.12.8"
}

provider "aws" {
  region  = "eu-west-1"
  version = "~> 2.51.0"
}

resource "aws_sns_topic" "test_sns_topic" {
  name   = "test_sns_topic"
}

resource "aws_sns_topic_subscription" "test_sns_sub" {
  topic_arn              = aws_sns_topic.test_sns_topic.arn
  protocol               = "https"
  endpoint               = "https://some-valid.url"
  endpoint_auto_confirms = true

  delivery_policy = file("${path.module}/delivery_policy.json")
}
```
delivery_policy.json:
```
{
  "healthyRetryPolicy": {
    "minDelayTarget": 20,
    "maxDelayTarget": 300,
    "numRetries": 60,
    "numMaxDelayRetries": 0,
    "numNoDelayRetries": 2,
    "numMinDelayRetries": 5,
    "backoffFunction": "exponential"
  },
  "throttlePolicy": {}
}
```
### Debug Output

1st plan https://gist.github.com/aaleksandrov/07f9bcd6f11734d9b163d4be066fd04d
2nd plan https://gist.github.com/aaleksandrov/3d6fba42cd08b96a27ac342e0f8f564c

### Expected Behavior

The 2nd plan should have no changes

### Actual Behavior

The 2nd plan shows changes

### Steps to Reproduce

`terraform plan`
`terraform apply`
`terraform plan`

**Comment by mwarkentin** [comment]
@aaleksandrov I'm seeing the same. I noticed that if I flattened the JSON in the file to a single line, the changes no longer showed up on the plan. Do you see the same?

**Comment by aaleksandrov** [comment]
Hi @mwarkentin they don't show in plan indeed. But if I do some meaningful change in such json (for instance `"numMinDelayRetries" : 7`) this change doesn't show up either. 
So this is not a solution
