### ISSUE TITLE
aws_datasync_location_nfs unable to set NFS Version

### ISSUE THREAD

**Issue by MartinBaas-qb** [hashicorp/terraform-provider-aws#14054]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.19
+ provider.aws v2.60.0

### Affected Resource(s)

* aws_datasync_location_nfs

### Terraform Configuration Files

n/a

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

when creating a aws_datasync_location_nfs, there should be a way to define the nfs version to use.

### Actual Behavior

this is not possible at the moment. 

### Steps to Reproduce

n/a

**Comment by bflad** [comment]
In the underlying [DataSync CreateLocationNfs API](https://docs.aws.amazon.com/datasync/latest/userguide/API_CreateLocationNfs.html), this appears to be the `MountOptions` handling and would translate to the following new configuration block in Terraform:

```tf
resource "aws_datasync_location_nfs" "example" {
  # ... other configuration ...

  mount_options {
    version = "..." # AUTOMATIC | NFS3 | NFS4_0 | NFS4_1
  }
}
```
