### ISSUE TITLE
Support PutBucketReplication x-amz-bucket-object-lock-token

### ISSUE THREAD

**Issue by prettymuchbryce** [hashicorp/terraform-provider-aws#14061]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS S3 allows for creating both a `replication_configuration` as well as an `object_lock_configuration`. However, if used together, then AWS support must be contacted and a token (`x-amz-bucket-object-lock-token`) supplied to enable the combination of both replication and object locking for an S3 bucket.

After contacting AWS support, the AWS support team instructs you run a command like this with a `<TOKEN>` that they supply.

```shell
aws s3api put-bucket-replication --bucket <BUCKET_NAME> --replication-configuration <REPLICATION CONFIGURATION> --token <TOKEN>
```

This `<TOKEN>` is mapped to the `x-amz-bucket-object-lock-token` header in the request to `PutBucketReplication`.

Currently there is no way to manage this configuration through Terraform.

### New or Affected Resource(s)

* aws_s3_bucket

### References

* https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lock-managing.html#object-lock-managing-replication
* https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketReplication.html#API_PutBucketReplication_RequestSyntax
* https://github.com/aws/aws-sdk-go/blob/bcb2cf3fc2263c8c28b3119b07d2dbb44d7c93a0/service/s3/content_md5_test.go#L129

**Comment by ewbankkit** [comment]
@prettymuchbryce Thanks for raising this issue.
Is the token value something that you would expect to set in the Terraform configuration and hence be persisted in state?

**Comment by prettymuchbryce** [comment]
Hi @ewbankkit. Yes. That is my expectation given my understanding of this token.

**Comment by ebarault** [comment]
hi @ewbankkit I'm facing the exact same issue.
The current aws_s3_bucket module raises the following error when trying to add replication configurations on object-lock enabled buckets:

"Error putting S3 replication configuration: InvalidRequest: Replication configuration cannot be applied to an Object Lock enabled bucket"

Indeed, after contacting the AWS support team, they provided us with a token that needs to be passed as described by @prettymuchbryce 

@prettymuchbryce did you bypass the problem by making your own api calls to the aws s3 api ?

**Comment by ebarault** [comment]
@ewbankkit Hi, is there any plan to tackle this issue at short term? any PR in progress i could review/test ?

**Comment by amazza-signerstech** [comment]
Hi, any update on this? It's really needed

**Comment by lnader** [comment]
👍

**Comment by akloss-cibo** [comment]
FWIW, I've observed that as long as the configuration applied by `aws_s3_bucket_replication_configuration` exactly matches what already exists, the API will succeed even without the token.  It's clunky, but using something like a `null_resource` to use the aws cli to create the replication configuration with a token *and* using `aws_s3_bucket_replication_configuration` does mostly work.
