### ISSUE TITLE
422 Error when trying to import ECR repository

### ISSUE THREAD

**Issue by BarakBD-Globality** [hashicorp/terraform-provider-aws#14098]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.28
+ provider.aws v2.27.0
+ provider.template v2.1.2
### Affected Resource(s)

* aws_ecr_repository

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

ECR repo is imported succesfully

### Actual Behavior

```
module.account.aws_ecr_repository.repo_name: Importing from ID "repo-name"...
module.account.aws_ecr_repository.repo_name: Import prepared!
  Prepared aws_ecr_repository for import
module.account.aws_ecr_repository.repo_name: Refreshing state... [id=repo-name]
Error writing state file: HTTP error: 422
Body: {"status":"422","error":"Unprocessable Entity"}
```
### Steps to Reproduce

1. `terraform import module.account.aws_ecr_repository.repo_name repo-name`

### References

* https://www.terraform.io/docs/providers/aws/r/ecr_repository.html

**Comment by gdavison** [comment]
Hi @BarakBD-Globality, are you still encountering this error? If so, could you please run the `terraform import` command with the environment variable `TF_LOG=DEBUG` please?

I suspect that the error is coming from the Terraform CLI, since the provider does not access the state file and the error is `Error writing state file: HTTP error: 422`. How is your state being stored?
