### ISSUE TITLE
Terraform equivalent of aws pinpoint-email create-configuration-set-event-destination

### ISSUE THREAD

**Issue by gmaghera** [hashicorp/terraform-provider-aws#14095]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.28

### Affected Resource(s)

https://docs.aws.amazon.com/cli/latest/reference/pinpoint-email/create-configuration-set-event-destination.html

* aws_pinpoint_?

### Terraform Configuration Files

I cannot find the equivalent of this aws CLI command: `aws pinpoint-email create-configuration-set-event-destination ...`

Is this something yet to be implemented?

**Comment by gmaghera** [comment]
I think I might have found a way around this.

My understanding of PinPoint is pretty limited, but it appears to use SES under the hood.
Calling `aws pinpoint-email create-configuration-set-event-destination` seems to wrap `aws ses create-configuration-set-event-destination` and then do some additional PinPoint configuration.  I haven't had much luck in finding documentation confirming this, I've been comparing deployment which used `aws pinpoint` against Terraform deployments using the `aws_ses_*` and `aws_pinpoint-*` providers.

It would be helpful to have some literature on how to replace `aws pinpoint-email ...` calls (no Terraform equivalent) with `aws ses ...` and `aws pinpoint ...` invocations, but maybe that's on AWS.

**Comment by shouze** [comment]
No, would be great to keep it open, definitely need it!
