### ISSUE TITLE
Add support for parameter "version-name" to resource "aws_ssm_document"

### ISSUE THREAD

**Issue by eballetbaz** [hashicorp/terraform-provider-aws#14107]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The AWS CLI API allows to specify the "version-name" when creating an "aws_ssm_document" 
https://docs.aws.amazon.com/cli/latest/reference/ssm/create-document.html

This version is very usefull to work with progressive deployment, and even quite mandatory
So please add support for parameter "version-name" to resource "aws_ssm_document"

### New or Affected Resource(s)

https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_ssm_document.go

### Potential Terraform Configuration

```
resource "aws_ssm_document" "agent_install" {
  name            = "Agent-Install"
  document_type   = "Package"
  document_format = "JSON"
  version-name   = "release-1.0.0"

  content = <<DOC
{
  "schemaVersion": "2.0",
  "description" : "Agent installation",
  "version": "release-1.0.0",
  "packages": {
    "windows": {
      "_any": {
        "_any": {
          "file": "${local.agent_build_file}"
        }
      }
    }
  },
  "files": {
    "${local.agent_build_file}": {
      "checksums": {
        "sha256": "${filesha256("${local.build_packages_dir}/${local.agent_build_file}")}"
      }
    }
  }
}
DOC
}

  attachments_source {
    key    = "SourceUrl"
    values = [ "s3://xxx" ]
  }
}
```

### References

https://docs.aws.amazon.com/cli/latest/reference/ssm/create-document.html
https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_ssm_document.go

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 3.28.0 of the Terraform AWS Provider, later today. Thank you to @drexler for the implementation. 👍
