### ISSUE TITLE
Fetching SSO IAM role ARNs dynamically

### ISSUE THREAD

**Issue by mattdodge** [hashicorp/terraform-provider-aws#14173]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.12.19
+ provider.aws v2.61.0
```

### Affected Resource(s)

* aws_iam_role

### Expected Behavior

We're using AWS SSO to authenticate into our different AWS accounts. This creates roles in each account that maps to the permission sets in AWS SSO. I'm wondering how I can get these role names in a dynamic fashion in terraform.

For example, I want to allow our developers access to our Kubernetes cluster. I do this by creating a role that has access that a developer can call `AssumeRole` on, like so.

```hcl
resource "aws_iam_role" "developer_cluster_access" {
  name                 = "cluster-access-developer"
  assume_role_policy   = data.aws_iam_policy_document.developer_cluster_access.json
}

data "aws_iam_policy_document" "developer_cluster_access" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type = "AWS"
      identifiers = ["my_role_arn_goes_here"]  # <-- I want this to be dynamic
    }
  }
}
```

Right now I'm having to hard code that role ARN in the assume role policy document - I would like for this to be fetched dynamically. 

I could use the `aws_iam_role` data source but for that I need the role name. The name structure of the role seems to be something like `AWSReservedSSO_<permission set>_<unique hash>` (Example role name: `AWSReservedSSO_AWSPowerUserAccess_aaaaaabbbbbbcccc`). Is there a reliable/deterministic way to compute that hash in terraform?

**Comment by sidewinder12s** [comment]
Anyone know how easy it might be to update the aws_iam_role data source to search for roles based on part of the name or by tags?

**Comment by Marcvd316** [comment]
This issue is nearly identical to the one I opened in August last year : https://github.com/hashicorp/terraform-provider-aws/issues/14470. Maybe they should be merged?

**Comment by seddarj** [comment]
I believe #18048 would fix this issue 😅
