### ISSUE TITLE
aws:cloudformation:template:parameter --> double quotes problem

### ISSUE THREAD

**Issue by santiago-flores-kenility** [hashicorp/terraform-provider-aws#14180]
Terraform v0.12.28
+ provider.aws v2.69.0
+ provider.null v2.1.2
+ provider.tls v2.1.0

aws:cloudformation:template:parameter

resource "aws_elastic_beanstalk_environment" "beanstalk" {
  name                = var.app_name
  application         = "AppName"
  solution_stack_name = "64bit Amazon Linux 2018.03 v3.3.7 running Tomcat 8.5 Java 8"
  tier                = "WebServer"
  version_label       = var.version_label

  setting {
    name      = "EnvironmentVariables"
    namespace = "aws:cloudformation:template:parameter"
    resource  = ""
    value     = var.template_parameter
  }

variable "template_parameter" {}

vars.tfvars
template_parameter                      = "env_var1=bla,env_var2=ble,sms.invalidchars=\\\\\\\""
sms_invalidchars                        = "\\\\\\\""

### Expected Behavior

set three environment properties
env_var1=bla
env_var2=ble
sms.invalidchars=\\\"

### Actual Behavior
env_var1=bla,env_var2=ble,sms.invalidchars=\\\"

It set one environment properties instead of separating them by the comma

### Steps to Reproduce

add this    custom_var=\\\\\\\"    to an existing template:parameter
  setting {
    name      = "EnvironmentVariables"
    namespace = "aws:cloudformation:template:parameter"
    resource  = ""
    value     = "env_var1=bla,env_var2=ble,sms.invalidchars=\\\\\\\""
  }

### Workaround
the work around was setting the parameter in a new setting:
  setting {
    name      = "sms.invalidchars"
    namespace = "aws:elasticbeanstalk:application:environment"
    resource  = ""
    value     = var.sms_invalidchars
  }

but the downside is that template:parameter will always find a difference

It does work if I'm setting sms.invalidchars=\\\\\\\" in the tf file and not in the tfvars file

**Comment by justinretzolk** [comment]
Hi @santiago-flores-kenility 👋 Thank you for reporting this. Given that there's been a few Terraform and AWS provider releases between when you filed this and now, can you confirm whether you're still experiencing this?

**Comment by santiago-flores-kenility** [comment]
> Hi @santiago-flores-kenility 👋 Thank you for reporting this. Given that there's been a few Terraform and AWS provider releases between when you filed this and now, can you confirm whether you're still experiencing this?

I've migrated to tf v1 and not using beanstalk anymore, closing the ticket and thank you for talking a look to the tkt!
