### ISSUE TITLE
Lambda auto-publish - Sometimes does not output new version

### ISSUE THREAD

**Issue by kevinmstephens** [hashicorp/terraform-provider-aws#14210]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
terraform 0.12.26

provider "aws" {
  version = "2.47.0"
}
```

I realize this is not the latest AWS provider but for a few reasons I feel this ticket should be considered anyway.
- The bug is seemingly a race condition so it's very hard for us to find instances of the bug. If we bump to latest we will have to wait another few weeks to find the bug again.
- I'm fairly sure I know the reason of the bug and I believe the problem may still exists in the codebase 

### Affected Resource(s)

* aws_lambda_function

### Terraform Configuration Files

```hcl
resource "aws_lambda_function" "lambda" {
  function_name                  = format("%s-service", var.resource_name)
  role                           = var.role_arn
  source_code_hash               = var.source_code_hash
  handler                        = var.handler
  runtime                        = var.runtime
  timeout                        = var.timeout
  publish                        = var.publish
  memory_size                    = var.memory_size
  description                    = var.description
  reserved_concurrent_executions = var.reserved_concurrent_executions
  s3_bucket                      = var.s3_bucket
  s3_key                         = aws_s3_bucket_object.artifact.key
  s3_object_version              = aws_s3_bucket_object.artifact.version_id

  dynamic "dead_letter_config" {
    for_each = var.dead_letter_config == null ? [] : [var.dead_letter_config]
    content {
      target_arn = dead_letter_config.value.target_arn
    }
  }

  dynamic "tracing_config" {
    for_each = var.tracing_config == null ? [] : [var.tracing_config]
    content {
      mode = tracing_config.value.mode
    }
  }

  vpc_config {
    security_group_ids = [aws_security_group.lambda_egress.id]
    subnet_ids         = var.private_subnets
  }

  dynamic "environment" {
    for_each = length(var.environment) < 1 ? [] : [var.environment]
    content {
      variables = environment.value.variables
    }
  }

  tags = var.tags
}
```

### Expected Behavior

We have output the lambda version. I expect if lambda version `8` is created on a Terraform run, that the output be `8`.
### Actual Behavior

Usually the output will be `8`. Infrequently the Terraform logic will create `8` but output the old version `7`.

### Steps to Reproduce

Simply push changes to your lambda and deploy with Terraform many times until you hit this condition. It seems to be very infrequent.

#### Guess at Cause

I believe I have found the cause but I'd hope someone can confirm.

It seems that the auto-publish feature is used in updating lambdas. This API call to AWS will return the updated version. However the AWS provider doesn't appear to use that version and instead appears to call `get-function-versions` and grab the largest version from the return list and use that value. However, I've confirmed with AWS Support that `get-function-versions` isn't a strongly consistent call and in fact is eventually consistent and has a cache TTL (length unknown).

I believe that the calls to `get-function-versions` sometimes returns stale data and so the new version is not present.

To solve this issue the AWS provider should use the version returned from the `update-function` call (`create-function` call too if that's relevant). 

* #0000

**Comment by cgeisel** [comment]
Update here, we contacted AWS Support and they confirmed the behavior. Their recommendation is to use the return value from update-function/create-function, which are strongly consistent.
