### ISSUE TITLE
aws_ec2_capacity_reservation: errant error 'availability_zone' is required, but no definition was found

### ISSUE THREAD

**Issue by haidangwa** [hashicorp/terraform-provider-aws#14236]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.26
+ provider.aws v2.70.0
+ provider.null v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

* aws_ec2_capacity_reservation

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

```
resource "aws_ec2_capacity_reservation" "indexer_cluster" {
  availability_zone = "us-east-1b"
  instance_type     = "i3en.xlarge"
  instance_platform = "Red Hat Enterprise Linux"
  instance_count    = 16
}
```

### Debug Output

```
2020/07/17 15:36:44 [ERROR] <root>: eval: *terraform.EvalValidateResource, err: Missing required argument: The argument "availability_zone" is required, but no definition was found.
2020/07/17 15:36:44 [ERROR] <root>: eval: *terraform.EvalSequence, err: Missing required argument: The argument "availability_zone" is required, but no definition was found.
2020-07-17T15:36:44.508-0700 [DEBUG] plugin: plugin process exited: path=**REDACTED**/.terraform/plugins/darwin_amd64/terraform-provider-template_v2.1.2_x4 pid=11563
2020-07-17T15:36:44.508-0700 [DEBUG] plugin: plugin exited

Error: Missing required argument
```

### Expected Behavior

The resource should compile without error

### Actual Behavior

Even though `availability_zone` is clearly defined, the error is thrown.

```
Acquiring state lock. This may take a few moments...

Error: Missing required argument

  on indexer_cluster.tf line 1, in resource "aws_ec2_capacity_reservation" "indexer_cluster":
   1: resource "aws_ec2_capacity_reservation" "indexer_cluster" {

The argument "availability_zone" is required, but no definition was found.

Releasing state lock. This may take a few moments...
```

### Steps to Reproduce

1. `terraform plan`

* #0000

**Comment by shuheiktgw** [comment]
I cannot reproduce this behavior with the same configuration file you provided and the plan succeeds. Are you sure your file is the same with the one you described above...?
