### ISSUE TITLE
availability_zone shouldn't be required for aws_ec2_capacity_reservation

### ISSUE THREAD

**Issue by haidangwa** [hashicorp/terraform-provider-aws#14237]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.26
+ provider.aws v2.70.0
+ provider.null v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

* aws_ec2_capacity_reservation

### Terraform Configuration Files

```hcl
resource "aws_ec2_capacity_reservation" "cluster" {
  instance_type     = "c5.4xlarge"
  instance_platform = "Red Hat Enterprise Linux"
  instance_count    = 16
}
```

### Expected Behavior

According to [AWS documentation](https://aws.amazon.com/ec2/pricing/reserved-instances/), availability zone is optional.

> Availability Zone (optional): By selecting an Availability Zone, the RI you purchase will provide a capacity reservation and a discount for the use of instances in the selected Availability Zone. When an Availability Zone isn’t specified, the RI discount will apply to a running instance of any size (within the same family) in the region. As an example, let’s say you own an m4.2xlarge Linux/UNIX RI with default tenancy in US East (N.Virginia). Then this RI’s discounted rate can automatically apply to two m4.xlarge instances in us-east-1a or four m4.large instances in us-east-1b.

### Actual Behavior

Terraform throws an error and availability_zone is required.

```
Error: Missing required argument

  on indexer_cluster.tf line 1, in resource "aws_ec2_capacity_reservation" "cluster":
   1: resource "aws_ec2_capacity_reservation" "cluster" {

The argument "availability_zone" is required, but no definition was found.
```

### Steps to Reproduce

1. `terraform plan`

**Comment by shuheiktgw** [comment]
I think you mixed up `RI` with `Capacity reservations`... I think you cannot use capacity reservation without specifying availability zones!

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-capacity-reservations.html

**Comment by justinretzolk** [comment]
Hi @haidangwa 👋 Thank you for filing this. Based on the link provided above, my read is also that you do indeed need to specify an availability zone with `aws_ec2_capacity_reservation`. 

It looks like you may instead be looking for the [capacity_reservation_specification](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#capacity-reservation-specification) and/or the [capacity_reservation_target](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#capacity-reservation-target) arguments of the `aws_instance` resource (in combination with the `aws_ec2_capacity_reservation` you've defined here).
