### ISSUE TITLE
Support policy attachment idempotentence by allowing implicit removal of unconfigured policy attachments

### ISSUE THREAD

**Issue by Deku-shrub** [hashicorp/terraform-provider-aws#14250]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

During IAM and application development, it's increasingly common for IAM roles to be attached to test policies, or maybe for a short term migration powerful policy.

One defines this by attaching a policy two times, the real policy and the test/migration policy. Everything is fine so far.

However when it comes time to remove the policy. One can just delete the attachment defintion right? Wrong! Unless you're cleaning up the underlying policy, the temporary policy will stay attached to the role, even after the attachment function is removed. This can leave to a role in production with too many permissions, never noticed. One must then manually detach the test policy, not very infrastructure-as-code!

The problem appears to be there is no trigger to detach the policy. The role doesn't have an understanding of what policies it should have attached (unless we're dealing with inline policies which we're not) and the attachment functions don't understand the concept of 'attach theses policies and only these policies'.

I'm not exactly sure how to fix this, but I believe it should be fixed. There is also the question of whether this should be supported implicitly or explictly to avoid being a breaking change.

#### Aggressive fix
Change to terraform core provider.

Once all roles and associated attachments are calculated, any attachments undefined and detatched from the role

#### Optional fix
Change to aws_iam_role

Allows a configuration parameter such as 'all_policy_attachments_defined_in_terraform' which is 'false' by default. 

If enabled, terraform will detach any undefined attachments at run time against this role.

### New or Affected Resource(s)

aws_iam_role_policy_attachment / aws_iam_role

### Potential Terraform Configuration

```hcl
resource "aws_iam_role_policy_attachment" "testing_policy" {
   role = aws_iam_role.myrolename.name
   policy_arn = some_test_policy.arn
}

resource "aws_iam_role_policy_attachment" "final_policy" {
   role = aws_iam_role.myrolename.name
   policy_arn = final_policy.arn
}
```
In the above example, even after removing 'testing_policy' from your code, it will remain attached!

**Comment by paulhammond** [comment]
I think this was fixed in #5904?
