### ISSUE TITLE
data source for "aws_cloudfront_origin_access_identity"

### ISSUE THREAD

**Issue by goetzc** [hashicorp/terraform-provider-aws#14258]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Data sources exist for most resource types, including [`aws_cloudfront_distribution`](https://github.com/terraform-providers/terraform-provider-aws/pull/6468), but not yet for `aws_cloudfront_origin_access_identity`.

### New or Affected Resource(s)

* aws_cloudfront_origin_access_identity (data source)

### Potential Terraform Configuration

Useful to be referenced from a S3 bucket policy or from another CloudFront distribution.

### References

* https://github.com/terraform-providers/terraform-provider-aws/issues/6586#issuecomment-470953841

**Comment by geoffreywiseman** [comment]
I'm just setting up a second independent Terraform project within a single AWS account, currently without shared remote state, and wishing I had this to avoid creating a second access identity or setting up more shared state.

**Comment by neosam01** [comment]
i need this feature

**Comment by reda-sj** [comment]
Same here.
scenario:
We have multiple cloudfront distribution using their own identity what share the same bucket as origin (different path).
updating the bucket for each distribution via terraform is not possible as it will override the existing permissions.
at the moment we use the web ui ... just for that.
If we have that datasource, we can create a permission module which will retrieve those aws_cloudfront_origin_access_identity and update the bucket in 1 shot.

**Comment by woodcockjosh** [comment]
Please add

**Comment by rajat-b-upadhyay** [comment]
Up Vote
