### ISSUE TITLE
ECS Service Replacement removes aws_appautoscaling_target and aws_appautoscaling_policy

### ISSUE THREAD

**Issue by MBali-GitHub** [hashicorp/terraform-provider-aws#14254]
Replacing the ECS service (which destroys and add the resource) does not retrigger the aws_appautoscaling_target and aws_appautoscaling_policy to be retriggered. As a result, replacing ecs_service resource causes them to be removed, requiring a subsequent terraform apply to again add them.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.24

### Affected Resource(s)

* aws_ecs_service
* aws_appautoscaling_target
* aws_appautoscaling_policy

### Terraform Configuration Files

```terraform
resource "aws_ecs_service" "ecsService" {
  name                                = var.service_name
  cluster                              = data.aws_ecs_cluster.cluster.id
  task_definition                 = module.ecs_fargate_task_definition.fargate_task_definition_arn
  desired_count                  = var.desired_count
  launch_type                      = "FARGATE"
  .......
}

resource "aws_appautoscaling_target" "ecs_target" {
  max_capacity       = 2
  min_capacity       = 0
  resource_id        = "service/${var.cluster}/${aws_ecs_service.ecsService.name}"
  role_arn           = "arn:aws:iam::${data.aws_caller_identity.identity.account_id}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"
}

resource "aws_appautoscaling_policy" "appScalingPolicy" {
  name               = aws_appautoscaling_target.ecs_target.id
  policy_type        = "StepScaling"
  resource_id        = aws_appautoscaling_target.ecs_target.resource_id
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"

  step_scaling_policy_configuration {
    adjustment_type         = "ExactCapacity"
    cooldown                = 60
    metric_aggregation_type = "Average"

    step_adjustment {
      metric_interval_lower_bound = 2
      scaling_adjustment          = 2
    }
  }
}
```

### Expected Behavior

aws_appautoscaling_target and aws_appautoscaling_policy would still be attached to the ecs service

### Actual Behavior

aws_appautoscaling_target and aws_appautoscaling_policy are not attached to the ecs service. A subsequent terraform apply adds it back.

### Steps to Reproduce

terraform apply
change task definition cpu (or any update in ecs task definition/service which needs the service to be replaced. keep the service name unchanged)
terraform apply (causes the resources to be removed)
terraform apply (adds them back)

**Comment by shkw** [comment]
I ran into the same problem and the workaround mentioned in https://github.com/hashicorp/terraform-provider-aws/issues/10432#issuecomment-588264307 works for me.
