### ISSUE TITLE
resource "aws_lambda_function" "default" {  Terraform doesn't like the Alexa example

### ISSUE THREAD

**Issue by rhino007US** [hashicorp/terraform-provider-aws#14289]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by rhino007US** [comment]
This is from the HashiCorp Terraform Alexa example. the block of code that blows up:

# This resource is the core take away of this example.
resource "aws_lambda_permission" "default" {
  statement_id  = "AllowExecutionFromAlexa"
  action        = "lambda:InvokeFunction"
  function_name = "${aws_lambda_function.default.function_name}"
  principal     = "alexa-appkit.amazon.com"
}

Error: "function_name" doesn't comply with restrictions ("^(arn:[\\w-]+:lambda:)?([a-z]{2}-(?9-_]+))?$"): "aws_lambda_function.lambda.function_name"

  on main.tf line 10, in resource "aws_lambda_permission" "lambda":
  10: resource "aws_lambda_permission" "lambda" {

If this is not the correct way to ask about this please let me know the right way.

**Comment by rhino007US** [comment]
https://github.com/terraform-providers/terraform-provider-aws/examples/aws/alexa

**Comment by rhino007US** [comment]
https://github.com/terraform-providers/terraform-provider-aws/tree/master/examples/alexa  

This is the path to the example

**Comment by breathingdust** [comment]
Hi @rhino007US :wave I was able to validate that the example works. It looks like the example was updated on the day you submitted this issue, so I assume this was fixed but the issue didn't get closed appropriately. Please comment to reopen if this is not the case. Thanks!
