### ISSUE TITLE
Terraform equivalent of aws pinpoint create-email-template

### ISSUE THREAD

**Issue by gmaghera** [hashicorp/terraform-provider-aws#14293]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.28

### Affected Resource(s)

https://docs.aws.amazon.com/cli/latest/reference/pinpoint/create-email-template.html

* aws_pinpoint_?

### Terraform Configuration Files

Currently there is no way (as far as I can tell) to create a PinPoint email template from terraform.  There is an overlap between PinPoint and SES and some resources can be created in either place (and still be usable with PinPoint), but that is not the case with email templates.  Creating an email template in SES does not result in a template usable in PinPoint (AWS consultant confirmed this).

Could you please add this to your roadmap?  Do you have a workaround?

**Comment by niels-baltodano-matrix** [comment]
any update ???

**Comment by nielsbaltodanomatrix** [comment]
I have created a module that works for me:
[create-pinpoint-templates](https://registry.terraform.io/modules/devops-pe/pinpoint-create-templates/aws/latest)

best regards

**Comment by vl-kp** [comment]
any update?
