### ISSUE TITLE
Rename "master" branch to "main"

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#14292]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> GitHub is working on replacing the term "master" on its service with a neutral term like "main" to avoid any unnecessary references to slavery, its CEO said on Friday.

I recommend renaming the default branch in the AWS provider GitHub repo to `main` so as to avoid using the term `master`.

This will not affect resources but will have wide implications on existing forks, CI configuration, and documentation.

### New or Affected Resource(s)

None

### Potential Terraform Configuration

```hcl
```

### References

* https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/
* https://discuss.hashicorp.com/t/rename-master-branch-to-main/11831
* https://medium.com/faun/git-step-by-step-renaming-a-master-branch-to-main-16390ca7577b
* Internal: ENGSRV-037
* Internal: PDCT-002

**Comment by bflad** [comment]
This is now explicitly part of a company-wide initiative, https://discuss.hashicorp.com/t/inclusive-language-changes/12797, so removing the proposal label. The maintainers team will provide additional information on timing when it has been decided.

**Comment by bflad** [comment]
Context: https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/

`main` is now the default choice when creating GitHub repositories and it sounds like they will be releasing tooling by end of year to cover all the various scenarios of doing the migration. Depending on the timing of that tooling and our migration, we can either leverage GitHub's tooling or some various (currently internal only) tooling.

**Comment by breathingdust** [comment]
This has now been completed 🎉. To update your local copy run:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```
