### ISSUE TITLE
Permanent diff on User Pool schema attributes when pool name is changed but is configured to be ignored

### ISSUE THREAD

**Issue by bassmanitram** [hashicorp/terraform-provider-aws#14317]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform - 0.11.14
was - 2.70.0

### Affected Resource(s)

* aws_cognito_user_pool

### Terraform Configuration Files

```hcl
resource "aws_cognito_user_pool" "cognito_user_pool" {  
  name = "${local.pool_name}"

  alias_attributes = [
    "phone_number",
    "email",
    "preferred_username"
  ]

  schema {
    name                = "email"
    attribute_data_type = "String"
    mutable             = true
    required            = true

    string_attribute_constraints {
      min_length = 6
      max_length = 32
    }
  }

... lots of other stuff

  #
  # Ignore pool name changes
  #
  lifecycle = {
    ignore_changes = [ "name" ]
  }
}
```

### Expected Behavior

Our naming policy changed but we don't want our existing Cognito pools to be destroyed

We change the value generated from `${local.pool_name}`.

A subsequent plan should not destroy the pool (since name change is a destructive change but it
is now configured as ignored), and should detect no diff at all

### Actual Behavior

The pool is not destroyed but all schema attributes are listed as changed to their same values

```
  ~ module.main.aws_cognito_user_pool.cognito_user_pool
      schema.#:                                                    "7" => "7"
      schema.126709184.attribute_data_type:                        "String" => "String"
      schema.126709184.developer_only_attribute:                   "false" => "false"
      schema.126709184.mutable:                                    "true" => "true"
      schema.126709184.name:                                       "l" => "l"
      schema.126709184.number_attribute_constraints.#:             "0" => "0"
      schema.126709184.required:                                   "false" => "false"
      schema.126709184.string_attribute_constraints.#:             "1" => "1"
      schema.126709184.string_attribute_constraints.0.max_length:  "32" => "32"
      schema.126709184.string_attribute_constraints.0.min_length:  "0" => "0"
      schema.1347931994.attribute_data_type:                       "String" => "String"
      schema.1347931994.developer_only_attribute:                  "false" => ""
      schema.1347931994.mutable:                                   "true" => "true"
...
```

### Steps to Reproduce

1. create a user pool with schema information
1. terraform apply
1. change the name of the pool and add the lifecycle block to ignore the name change
1. `terraform apply`

**Comment by justinretzolk** [comment]
Hi @bassmanitram 👋 Thank you for reporting this. Given that there's been a few Terraform and AWS provider releases between when you filed this and now, can you confirm whether you're still experiencing this?

**Comment by justinretzolk** [comment]
Since we haven't heard back, we'll close this issue. If you (or anyone else) runs into this again, please open a new issue so that we can triage is appropriately.
