### ISSUE TITLE
aws_launch_template does not accept spot_price as in doc

### ISSUE THREAD

**Issue by ALutchko** [hashicorp/terraform-provider-aws#14318]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform 0.12.29
provider.aws: version = "~> 2.70"

### Affected Resource(s)
* aws_launch_template

### Terraform Configuration Files

Like in this doc: https://www.terraform.io/docs/providers/aws/r/spot_fleet_request.html

```hcl
terraform {
  required_version = ">= 0.12"
}

provider "aws" {
  region     = var.default_region
}

resource "aws_launch_template" "foo" {
  name          = "launch-template"
  image_id      = "ami-516b9131"
  instance_type = "m1.small"
  key_name      = "some-key"
  spot_price    = "0.05"
}
```

### Debug Output

```
./terraform validate 

Error: Unsupported argument

  on spot_fleet.tf line 6, in resource "aws_launch_template" "foo":
   6:   spot_price    = "0.05"

An argument named "spot_price" is not expected here.
```

### Expected Behavior

Validation should be passed successfully

### Actual Behavior

Validation failed

### Steps to Reproduce

1. Create a tf file with sample aws_launch_template from the mentioned doc
2. `terraform init`
3. `terraform validate`

### References

* #0000

**Comment by shuheiktgw** [comment]
Did you look into `instance_market_options`? https://www.terraform.io/docs/providers/aws/r/launch_template.html#market-options

**Comment by ALutchko** [comment]
Hi @shuheiktgw , I'm in doubt it will work with further `overrides` like below
```
resource "aws_spot_fleet_request" "foo" {
  launch_template_config {
    launch_template_specification {
      id      = aws_launch_template.foo.id
    }
    overrides {
      instance_type = "t3a.xlarge"
      spot_price    = "0.1"
    }
```
Will it? Nevertheless I've tried this way:
```
resource "aws_launch_template" "foo" {
  name          = "launch-template"
  image_id      = "ami-516b9131"
  instance_type = "m1.small"
  key_name      = "some-key"
  instance_market_options {
    market_type = "spot"
    spot_options {
      max_price = "0.12"
    }
  }
}
```
the error is: `An argument named "max_price" is not expected here.` Am I doing something wrong here?

**Comment by breathingdust** [comment]
Hi @ALutchko! I don't see a `spot_price` parameter on the `aws_launch_template` resource. The documentation you link to does refer to `aws_spot_fleet_request. You can however refer to an `aws_launch_template` via the specification (as described in that linked documentation). I'll close this for now, but if you think I've made a mistake please comment to reopen the issue.
