### ISSUE TITLE
aws_customer_gateway device name attribute

### ISSUE THREAD

**Issue by mikereinhold** [hashicorp/terraform-provider-aws#14346]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating more than one customer gateway with the same public IP and BGP ASN, the second resource creation does not actually create a new resource but instead imports the first resource created and that customer gateway ID can be found for both aws_customer_gateways in the Terraform state.

This behavior mimics the action in the console: creating a second customer gateway with the same public IP and BGP ASN will not create a new resource, but instead will return the id of the pre-existing customer gateway.

The way to get around this in the console is to provide a Device identifier, which will provide uniqueness within AWS:
![image](https://user-images.githubusercontent.com/5108289/88458859-f0c65980-ce5e-11ea-8e77-504f76c627ba.png)

At this point in time, the aws_customer_gateway resource does not allow setting the device-name field as exposed by the AWS API for [create-customer-gateway](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/create-customer-gateway.html):
![image](https://user-images.githubusercontent.com/5108289/88458889-17849000-ce5f-11ea-81f3-06cc941f11d5.png)

Adding the device name attribute to the aws_customer_gateway resource would allow the Terraform user to avoid this accidental import of a pre-existing resource and explicitly declare that the two customer gateways are supposed to be unique by specifying a device name.

Having multiple customer gateways with the same BGP ASN and Public IP is a common scenario when you have redundant routers behind a NAT and need to distinguish between them separately in the AWS console.

### New or Affected Resource(s)

* aws_customer_gateway

### Potential Terraform Configuration

```hcl
resource "aws_customer_gateway" "first" {
  bgp_asn    = 65000
  ip_address = "172.83.124.10"
  type       = "ipsec.1"

  device = "first"
}

resource "aws_customer_gateway" "second" {
  bgp_asn    = 65000
  ip_address = "172.83.124.10"
  type       = "ipsec.1"

  device = "second"
}
```

### References

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/customer_gateway
* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/create-customer-gateway.html

**Comment by bflad** [comment]
Support for `device_name` in the `aws_customer_gateway` resource and data source has been merged and will release with version 3.28.0 of the Terraform AWS Provider, later today. Thank you to @shuheiktgw for the implementation. 👍
