### ISSUE TITLE
Terraform force replaces instance during the second apply command

### ISSUE THREAD

**Issue by Anbukugan** [hashicorp/terraform-provider-aws#14344]
### Issue description
I have created a script that will create EC2 instances from the base AMI and added another EBS volume via code. I added a flag that would enable/disable resource creation. The logic works fine during the first terraform apply. But when I give it the second time even though there were no changes added to the EBS volumes terraform force replaces all the volumes including the volumes from AMI.

### Terraform CLI and Terraform AWS Provider Version
* Terraform v0.12.24
* provider.aws v2.63.0

### Terraform Configuration Files

```
resource "aws_key_pair" "keys" {
  count = var.ec2_enable == 1 ? 1 : 0
  public_key = var.public_key
  key_name = var.key_name
}


#Create EC2 Instances
resource "aws_instance" "infrainstances" {
  for_each = {
  for l in range(length(var.instance_names)) :
  "${var.instance_names[l]}-${var.sitename}" => {
    instance_name = var.instance_names[l]
    pub_subnet_ids = var.pub_subnet_ids[l]
  }
  }
  ami = data.aws_ami.image.id
  instance_type = "m5a.xlarge"
  ebs_block_device {
    device_name = "/dev/sdg"
    volume_type =  "gp2"
    volume_size = "10"
    encrypted = true
    kms_key_id = "arn:aws:kms:us-east-1:351387070227:key/4d494c58-6687-4b88-a628-3fa8fc00a51c"
    delete_on_termination = true
  }
  disable_api_termination = true
  key_name =  var.ec2_enable == 1 ? aws_key_pair.keys.0.key_name : ""
  monitoring = true
  vpc_security_group_ids = var.ec2sgids
  subnet_id = each.value.pub_subnet_ids
  tags = {
    Name:"${each.value.instance_name}-${var.sitename}"
    Deployed_by:"Ck-Automation"
    Farm: var.farmname
  }
}
```
### Expected Behavior

It should show no changes.

### Actual Behavior

It force replaces all the resources

### Steps to Reproduce

1. `terraform apply`

**Comment by justinretzolk** [comment]
Hi @Anbukugan 👋 Thank you for filing this. Given that there's been a few releases of Terraform and the AWS provider between when you filed this and now, can you confirm whether you're still experiencing this?
