### ISSUE TITLE
While doing restacking i am getting below error.

### ISSUE THREAD

**Issue by Anwardba09** [hashicorp/terraform-provider-aws#14351]
data.template_file.user_data: Refreshing state...
aws_kms_key.secrets_cli_key: Refreshing state... (ID: fef76b8c-5d04-4118-8afb-ac7463b3e0ee)
aws_iam_role.oracle_gg_ec2: Refreshing state... (ID: oracle_gg_ec2_gg_crm_dev)
aws_kms_key.oracle_gg_ec2_key: Refreshing state... (ID: 449f696f-d469-4b35-92b9-49ac125ad73d)
aws_iam_policy.oracle_gg_ec2_policy: Refreshing state... (ID: arn:aws:iam::410104884591:policy/oracle_gg_ec2_policy_gg_crm_dev)
aws_security_group.oracle_gg_ec2_sg: Refreshing state... (ID: sg-08e7c8015b5127638)
data.aws_route53_zone.dns_zone: Refreshing state...
data.aws_region.current: Refreshing state...
data.aws_subnet.install_subnet_1: Refreshing state...
data.aws_iam_policy_document.oracle_gg_ec2_policy_doc_sns: Refreshing state...
aws_iam_policy.oracle_gg_ec2_policy_sns: Refreshing state... (ID: arn:aws:iam::410104884591:policy/oracle_gg_ec2_policy_gg_crm_dev_sns)

Error: Error refreshing state: 7 errors occurred:
	* module.IAM.aws_iam_policy.oracle_gg_ec2_policy: 1 error occurred:
	* module.IAM.aws_iam_policy.oracle_gg_ec2_policy: aws_iam_policy.oracle_gg_ec2_policy: unexpected EOF

	* module.GG.data.aws_route53_zone.dns_zone: 1 error occurred:
	* module.GG.data.aws_route53_zone.dns_zone: data.aws_route53_zone.dns_zone: unexpected EOF

	* module.IAM.aws_iam_role.oracle_gg_ec2: 1 error occurred:
	* module.IAM.aws_iam_role.oracle_gg_ec2: aws_iam_role.oracle_gg_ec2: unexpected EOF

	* module.IAM.aws_iam_policy.oracle_gg_ec2_policy_sns: 1 error occurred:
	* module.IAM.aws_iam_policy.oracle_gg_ec2_policy_sns: aws_iam_policy.oracle_gg_ec2_policy_sns: unexpected EOF

	* module.GG.aws_kms_key.oracle_gg_ec2_key: 1 error occurred:
	* module.GG.aws_kms_key.oracle_gg_ec2_key: aws_kms_key.oracle_gg_ec2_key: unexpected EOF

	* aws_kms_key.secrets_cli_key: 1 error occurred:
	* aws_kms_key.secrets_cli_key: aws_kms_key.secrets_cli_key: unexpected EOF

	* module.GG.aws_security_group.oracle_gg_ec2_sg: 1 error occurred:
	* module.GG.aws_security_group.oracle_gg_ec2_sg: aws_security_group.oracle_gg_ec2_sg: unexpected EOF

______________________________________________________

2020-07-27T16:31:51.108+0530 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: 	/opt/goenv/versions/1.13.7/src/net/rpc/server.go:377 +0x16f
2020-07-27T16:31:51.108+0530 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: created by net/rpc.(*Server).ServeCodec
2020-07-27T16:31:51.108+0530 [DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: 	/opt/goenv/versions/1.13.7/src/net/rpc/server.go:474 +0x42b
2020/07/27 16:31:51 [ERROR] root.GG: eval: *terraform.EvalRefresh, err: aws_security_group.oracle_gg_ec2_sg: unexpected EOF
2020/07/27 16:31:51 [ERROR] root.GG: eval: *terraform.EvalRefresh, err: aws_kms_key.oracle_gg_ec2_key: unexpected EOF
2020/07/27 16:31:51 [ERROR] root.IAM: eval: *terraform.EvalRefresh, err: aws_iam_policy.oracle_gg_ec2_policy_sns: unexpected EOF
2020/07/27 16:31:51 [ERROR] root.IAM: eval: *terraform.EvalSequence, err: aws_iam_policy.oracle_gg_ec2_policy_sns: unexpected EOF
2020/07/27 16:31:51 [TRACE] [walkRefresh] Exiting eval tree: module.IAM.aws_iam_policy.oracle_gg_ec2_policy_sns
2020/07/27 16:31:51 [ERROR] root: eval: *terraform.EvalRefresh, err: aws_kms_key.secrets_cli_key: unexpected EOF
2020/07/27 16:31:51 [ERROR] root: eval: *terraform.EvalSequence, err: aws_kms_key.secrets_cli_key: unexpected EOF
2020/07/27 16:31:51 [ERROR] root.GG: eval: *terraform.EvalReadDataApply, err: data.aws_route53_zone.dns_zone: unexpected EOF
2020/07/27 16:31:51 [ERROR] root.GG: eval: *terraform.EvalSequence, err: data.aws_route53_zone.dns_zone: unexpected EOF
2020/07/27 16:31:51 [TRACE] [walkRefresh] Exiting eval tree: module.GG.data.aws_route53_zone.dns_zone
2020/07/27 16:31:51 [ERROR] root.IAM: eval: *terraform.EvalRefresh, err: aws_iam_role.oracle_gg_ec2: unexpected EOF
2020/07/27 16:31:51 [ERROR] root.IAM: eval: *terraform.EvalSequence, err: aws_iam_role.oracle_gg_ec2: unexpected EOF
2020/07/27 16:31:51 [ERROR] root.GG: eval: *terraform.EvalSequence, err: aws_security_group.oracle_gg_ec2_sg: unexpected EOF
2020/07/27 16:31:51 [TRACE] [walkRefresh] Exiting eval tree: module.IAM.aws_iam_role.oracle_gg_ec2
2020/07/27 16:31:51 [TRACE] [walkRefresh] Exiting eval tree: module.GG.aws_security_group.oracle_gg_ec2_sg
2020/07/27 16:31:51 [ERROR] root.GG: eval: *terraform.EvalSequence, err: aws_kms_key.oracle_gg_ec2_key: unexpected EOF
2020/07/27 16:31:51 [TRACE] [walkRefresh] Exiting eval tree: module.GG.aws_kms_key.oracle_gg_ec2_key
2020/07/27 16:31:51 [ERROR] root.IAM: eval: *terraform.EvalRefresh, err: aws_iam_policy.oracle_gg_ec2_policy: unexpected EOF
2020/07/27 16:31:51 [ERROR] root.IAM: eval: *terraform.EvalSequence, err: aws_iam_policy.oracle_gg_ec2_policy: unexpected EOF
2020/07/27 16:31:51 [TRACE] dag/walk: upstream errored, not walking "module.IAM.aws_iam_role_policy_attachment.oracle_gg_ec2_attachment_sns"
2020/07/27 16:31:51 [TRACE] dag/walk: upstream errored, not walking "module.IAM.aws_iam_instance_profile.oracle_gg_ec2_profile"
2020/07/27 16:31:51 [TRACE] dag/walk: upstream errored, not walking "module.GG.output.oracle_gg_ec2_sg"
2020/07/27 16:31:51 [TRACE] [walkRefresh] Exiting eval tree: module.IAM.aws_iam_policy.oracle_gg_ec2_policy
2020/07/27 16:31:51 [TRACE] dag/walk: upstream errored, not walking "module.GG.aws_kms_alias.oracle_gg_ec2_key"
2020/07/27 16:31:51 [TRACE] dag/walk: upstream errored, not walking "module.IAM.output.oracle_gg_ec2_iam_instance_profile_name"

**Comment by mihaico** [comment]
same issue here with tf version 0.11.7 and provider version 2.70.0

**Comment by justinretzolk** [comment]
Hi @Anwardba09 👋 Thank you for filing this. Given that there have been a few releases of Terraform and the AWS provider between when you originally filed this and now, can you confirm whether you're still experiencing this?
