### ISSUE TITLE
aws_spot_instance_request fails to file provision via aws_instance bastion

### ISSUE THREAD

**Issue by smalinowski-ac** [hashicorp/terraform-provider-aws#14369]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.12.21
+ provider.aws v2.70.0
```

### Affected Resource(s)

* aws_spot_instance_request

### Terraform Configuration Files

```hcl
...

resource "aws_instance" "this" {
	instance_type = var.instance_id
	ami           = data.aws_ami.this.id
	key_name      = var.keypair_name
	subnet_id     = var.subnet_id
}

resource "aws_eip" "this" {
	vpc = true
}

resource "aws_eip_association" "this" {
	allocation_id = aws_eip.this.id
	instance_id   = aws_instance.this.id
}

resource "aws_spot_instance_request" "this" {
	instance_type = var.instance_id
	ami           = data.aws_ami.this.id
	key_name      = var.keypair_name
	subnet_id     = var.subnet_id

	spot_price = var.spot_price
	spot_type  = "persistent"

	depends_on = [
		aws_instance.this
	]

	connection {
		type         = "ssh"
		bastion_host = var.bastion_public_ip
		bastion_user = var.bastion_username
		host         = self.private_ip
		user         = var.ssh_username
		private_key  = var.keys.private
	}

	# Upload Private SSH Key
	provisioner "file" {
		content     = var.keys.private
		destination = "~/.ssh/id_rsa"
	}

	# Upload Public SSH Key
	provisioner "file" {
		content     = var.keys.public
		destination = "~/.ssh/id_rsa.pub"
	}
}

...
```

*FYI: This is just a condensed snippet of the actual setup. In actuality there are modules and networking resources to build out the VPC, subnet, security group, and NAT.*

### Debug Output

```
...
file-provisioner (internal) 2020/07/28 12:48:24 [DEBUG] Connecting to :22 for SSH
file-provisioner (internal) 2020/07/28 12:48:24 [DEBUG] Connecting to bastion: 3.129.83.201:22
file-provisioner (internal) 2020/07/28 12:48:25 [DEBUG] Connecting via bastion (3.129.83.201:22) to host: :22
file-provisioner (internal) 2020/07/28 12:48:25 [ERROR] connection error: ssh: rejected: administratively prohibited (open failed)
file-provisioner (internal) 2020/07/28 12:48:25 [WARN] retryable error: ssh: rejected: administratively prohibited (open failed)
file-provisioner (internal) 2020/07/28 12:48:25 [INFO] sleeping for 20s
2020/07/28 12:48:41 [WARN] Errors while provisioning aws_spot_instance_request.this with "file", so aborting
2020/07/28 12:48:41 [ERROR] aws_spot_instance_request.this: eval: *terraform.EvalApplyPost, err: 1 error occurred:
	* timeout - last error: ssh: rejected: administratively prohibited (open failed)
...
```

### Actual Behavior

The file(s) fail to scp to `aws_spot_instance_request.this` via bastion host.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

It looks like issue [azure-#616](https://github.com/terraform-providers/terraform-provider-azurerm/issues/616), however, the image used by `aws_instance.this` has `AllowTcpForwarding yes` in its `sshd_config`.
Additionally, if `aws_instance` is used instead of `aws_spot_instance_request`, then everything works normally.

**Comment by justinretzolk** [comment]
Hey @smalinowski-ac 👋 Thank you for filing this. Given that there's been a number of releases of Terraform and the AWS provider between when this was initially filed and now, can you confirm whether you're still experiencing this issue?
