### ISSUE TITLE
IAM policy document condition list order must be respected

### ISSUE THREAD

**Issue by shinglyu** [hashicorp/terraform-provider-aws#14365]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.29
+ provider.aws v2.70.0

### Affected Resource(s)

* data aws_iam_policy_document
* resource aws_iam_policy

### Terraform Configuration Files

```hcl
data "aws_iam_policy_document" "s3-bucket" {
  statement {
    sid = "AllowListing"

    actions = [
        "s3:ListBucket"
    ]

    resources = [
      "arn:aws:s3:::mybucket",
    ]
    condition {
      test = "StringLike"
      variable = "s3:prefix"

      values = var.allow_list_paths
    }
  }
}

resource "aws_iam_policy" "s3-bucket-policy" {
  name        = "s3-bucket-policy"
  policy = data.aws_iam_policy_document.s3-bucket.json
}

variable "allow_list_paths" {
  default = ["", "/foo/", "/foo/*"]
}
```

### Debug Output

https://gist.github.com/shinglyu/7dca7de082afce288cdce4f4c25035c9

### Expected Behavior

The s3 prefix list in the condition should respect the order of the var list:
```
                      + Condition = {
                          + StringLike = {
                              + s3:prefix = [
                                  + "",
                                  + "/foo/",
                                  + "/foo/*",
                                ]
                            }
                        }
```
### Actual Behavior

The list is re-ordered
```
                      + Condition = {
                          + StringLike = {
                              + s3:prefix = [
                                  + "/foo/*",
                                  + "/foo/",
                                  + "",
                                ]
                            }
                        }
```
I also tried using `sort()` or `reverse(sort())` before passing the list to `values=`, but the output remains the same.
### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Important Factoids

The order of these conditions is very important when we are trying to expose S3 through SFTP interface using AWS Transfer Family. If the order is not correct, the user won't be able to list the files and folder under `/foo/`
### References

* #0000

**Comment by shinglyu** [comment]
Additional information: I tried using the `source_json` and `override_json` option but the order is still changed.

**Comment by nodefortytwo** [comment]
@shinglyu this clearly should be fixed but a workaround that might work for you is to use template_files instead of the policy resource (https://learn.hashicorp.com/tutorials/terraform/aws-iam-policy#template_file-data-source), you can then control the order much more easily however its more error prone generally.

**Comment by shinglyu** [comment]
@nodefortytwo Thank you for the suggestion. I tried the `template_file` data source. But in the `terraform plan` output the list order is still reordered. I guess the template and it's rendered JSON order is correct, but when the lists are reordered when being  transformed into AWS API calls.

**Comment by YakDriver** [comment]
I have not replicated the issue but can tell you why it is happening. Currently, `statement.condition.values` is a `Set`. It does not care about order. In my opinion, this should be a `List` instead.
