### ISSUE TITLE
Unchanging task_role_arn and execution_role_arn force replacement of task definition 

### ISSUE THREAD

**Issue by mimozell** [hashicorp/terraform-provider-aws#14364]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.0-rc1
provider registry.terraform.io/hashicorp/aws v2.70.0

### Affected Resource(s)

* aws_ecs_task_definition

### Terraform Configuration Files

```hcl
data aws_iam_role task_role { name = "ecsTaskExecutionRole" }

resource aws_ecs_task_definition service {
  container_definitions = <<-JSON
    [
      {
        "name": "${var.service-name}",
        "image": "${var.image}",
        "essential": true,
        "portMappings": [
          {
            "containerPort": ${var.container_port},
            "hostPort": ${var.container_port}
          }
        ],
        "environment" : [
          { "name" : "SPRING_PROFILES_ACTIVE", "value" : "cloud,${var.environment}${var.spring-profiles}" }
        ],
        "logConfiguration": {
          "logDriver": "awslogs",
          "options": {
            "awslogs-group": "${var.awslogs-group}",
            "awslogs-region": "${var.awslogs-region}",
            "awslogs-stream-prefix": "web"
          }
        }
      }
    ]
  JSON

  family = "${var.service-name}-${var.environment}"
  task_role_arn = data.aws_iam_role.task_role.arn
  execution_role_arn = data.aws_iam_role.task_role.arn
  requires_compatibilities = ["FARGATE"]
  network_mode = "awsvpc"
  cpu = var.container_cpu
  memory = var.container_memory

  tags = {
    Environment = var.environment
    AppName = var.service-name
  }
}
```

### Expected Behavior

No resources should show as changed.

### Actual Behavior
Execution Role ARN and Task Role ARN seem to change, but they don't. Every time we run terrafom apply we see the same output, which forces recreation of task definitions.
```
      ~ execution_role_arn       = "arn:aws:iam::<accountID>:role/ecsTaskExecutionRole" -> (known after apply) # forces replacement
        family                   = "appName-lab"
      ~ id                       = "appName-lab" -> (known after apply)
        memory                   = "1024"
        network_mode             = "awsvpc"
        requires_compatibilities = [
            "FARGATE",
        ]
      ~ revision                 = 15 -> (known after apply)
        tags                     = {
            "AppName"     = "appName"
            "Environment" = "lab"
        }
      ~ task_role_arn            = "arn:aws:iam::<accountID>:role/ecsTaskExecutionRole" -> (known after apply) # forces replacement
```
_accountID_ is the actual account ID, purposely omitted here.
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

We started seeing this once we enabled [Amazon ECS ARN and resource ID settings](https://eu-west-1.console.aws.amazon.com/ecs/home?region=eu-west-1#/settings) for container service, service and task, but we're not sure the two are related as the IAM ARN marked here is not changing.

**Comment by mimozell** [comment]
Further investigation on the output of terraform plan from data confirms that the arn for the aws_iam_role seems to need re-evaluation:
```
 <= data "aws_iam_role" "task_role"  {
      ~ arn                         = "arn:aws:iam::<accountID>:role/ecsTaskExecutionRole" -> (known after apply)
      ~ assume_role_policy          = jsonencode(
            {
              - Statement = [
                  - {
                      - Action    = "sts:AssumeRole"
                      - Effect    = "Allow"
                      - Principal = {
                          - Service = "ecs-tasks.amazonaws.com"
                        }
                      - Sid       = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
...
```
even though nothing has changed, and then this causes the task definitions to be recreated every time. The question is, why does an unchanging ARN need recomputing?

**Comment by justinretzolk** [comment]
Hey @mimozell 👋 Thank you for filing this. Given the most recent comment that the data source is showing `(known after apply)` as well, and the that `aws_ecs_task_definition` resource has values interpolated from that data source, that'll be why the resource is noting as needing to be replaced. 

That said, given that there's been a few Terraform and AWS provider releases between when you filed this and now, can you confirm whether you're still running into this?

**Comment by mimozell** [comment]
Since this wasn't working at the time, we stopped using data and just referred to the arn of the role (hardcoded :(), so we haven't been seeing this issue. Haven't tried to switch to using data since that worked.

**Comment by justinretzolk** [comment]
Thank you for the update. Given that's the case, I'm going to go ahead and close this issue out for now. If you (or anyone else reading this in the future) runs into this again, please do let us know so we can take another look.

**Comment by duganth** [comment]
I am also seeing this issue but not consistent across ecs tasks. Is there any information I can provide to help? its the same issue.
