### ISSUE TITLE
Add backup support for aws_efs_file_system

### ISSUE THREAD

**Issue by jeremietharaud** [hashicorp/terraform-provider-aws#14372]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for automatic backups for EFS. See [announcement](https://aws.amazon.com/about-aws/whats-new/2020/07/announcing-automatic-backups-for-amazon-elastic-file-system/).

### New or Affected Resource(s)

* aws_efs_file_system

### Potential Terraform Configuration

```hcl
resource "aws_efs_file_system" "foo" {
  creation_token = "my-product"

  # ...

  backup_policy {
    status = "ENABLED"
  }
}
```

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.33.3](https://github.com/aws/aws-sdk-go/releases/tag/v1.33.3):

* https://github.com/terraform-providers/terraform-provider-aws/pull/14000

**Comment by shuheiktgw** [comment]
I'm working on this issue.

**Comment by shuheiktgw** [comment]
Move the PR to https://github.com/hashicorp/terraform-provider-aws/pull/18006 following https://github.com/hashicorp/terraform-provider-aws/pull/14670#issuecomment-790652157
