### ISSUE TITLE
SES: support setting domain from on email identities (or perhaps unify it into a new resource)

### ISSUE THREAD

**Issue by piotrb** [hashicorp/terraform-provider-aws#14378]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Much like `aws_ses_domain_mail_from` we need a resource for email identities to set the same.

### New or Affected Resource(s)

perhaps this could just become a new universal resource .. much like `aws_ses_identity_notification_topic` which can operate on domains or emails .. 

*`aws_ses_identity_mail_from` .. ?

### Potential Terraform Configuration

```hcl
resource "aws_ses_email_mail_from" "example-email" {
  identity = aws_ses_domain_identity.example.arn
  mail_from_domain = "bounce.${aws_ses_domain_identity.example.domain}"
}

resource "aws_ses_email_mail_from" "example-domain" {
  identity = aws_ses_email_identity.example.arn
  mail_from_domain = "bounce.${aws_ses_domain_identity.example.domain}"
}
```

### References

It seems like https://docs.aws.amazon.com/ses/latest/APIReference/API_SetIdentityMailFromDomain.html supports both types of identities .. so this might just do it ..

**Comment by caparisi** [comment]
This could be done with "aws_ses_domain_mail_from", maybe this will need to be specified in documentation :

```terraform
resource "aws_ses_email_identity" "xxxxxxxx" {
  email = "xxxxxxxx@example.com"
}

resource "aws_ses_domain_mail_from" "xxxxxxxx" {
  domain           = aws_ses_email_identity.xxxxxxxx.email
  mail_from_domain = "yyyyyyy.example.com"
}
```

**Comment by ElvenSpellmaker** [comment]
This should be specified in the docs on both `domain_mail_from` and `ses_email_identity` really...

Also if e-mails may be passed to `domain` then it's no longer a 'domain' and the variable probably wants renaming, as it's no longer just for domains but emails too.

**Comment by cebidhem** [comment]
Hey @piotrb , I've tried to implement the issue with the new resource way, instead of the generic resource for both use-cases (I wasn't super comfortable going with the latter directly). Anyway, I left it in WIP for the moment because I couldn't make the `testacc` pass.

Will try to reach out to maintainers on the PR comments to get this merged at some point.

**Comment by piotrb** [comment]
This is by no means urgent any more since the `aws_ses_domain_mail_from` workaround works just fine (albeit is a bit confusing) .. thanks for taking a stab at it though
