### ISSUE TITLE
Technical Debt Theme: Resolve Acceptance Test Failures (EC2)

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#14383]
### Description

This is a meta-issue which tracks the list of EC2 Acceptance Tests which now consistently fail. The August-October 2020 [Roadmap](https://github.com/terraform-providers/terraform-provider-aws/blob/master/ROADMAP.md) for the AWS Provider includes a technical debt theme which decides an area of debt upon which we want to apply focus. 

The focus for this period is improving our Acceptance Test suite. This covers resolving failing and flaky tests. Our initial focus will be to resolve failing tests which exist within our [Core Service](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CORE_SERVICES.md) list.

## EC2 Tests Currently Failing

- [x] `TestAccAWSSpotFleetRequest_tags`
- [x] `TestAccAWSSpotFleetRequest_launchSpecToLaunchTemplate`
- [x] `TestAccAWSInstance_EbsRootDevice_ModifyDeleteOnTermination`
- [x] `TestAccAWSInstance_EbsRootDevice_MultipleBlockDevices_ModifyDeleteOnTermination`
- [x] `TestAccAWSInstance_EbsRootDevice_ModifyAll`
- [x] `TestAccAWSInstance_metadataOptions`
- [x] `TestAccAWSSpotFleetRequest_withoutSpotPrice`
- [x] `TestAccAWSFlowLog_LogFormat`
- [ ] `TestAccAWSEIPAssociation_ec2Classic`
- [ ] `TestAccAwsEc2ClientVpn_serial` (related to Max # of certs)
- [ ] `TestAccAWSEIP_Ec2Classic`
- [ ] `TestAccAWSRouteTable_panicEmptyRoute`
- [ ] `TestAccAWSVpcPeeringConnectionOptions_sameRegionDifferentAccount`
- [ ] `TestAccAWSInstance_instanceProfileChange`
- [x] `TestAccAWSInstance_EbsBlockDevice_KmsKeyArn`
- [ ] `TestAccAWSEIPAssociation_spotInstance` (passing since 8/19 in Commercial and Gov)
- [ ] ~~`TestAccAWSInstance_ipv6_supportAddressCountWithIpv4`~~ (passing in Commercial and Gov)
- [ ] ~~`TestAccAWSRoute_changeRouteTable`~~ (passing in Commercial and Gov)
- [ ] `TestAccAWSVpcEndpointServiceAllowedPrincipal_basic` (consistently passing since 8/18  in Commercial and Gov)

**Comment by bflad** [comment]
All set except, `TestAccAWSInstance_instanceProfileChange` which can be tracked in https://github.com/hashicorp/terraform-provider-aws/issues/16769 👍
