### ISSUE TITLE
ACM renew fails but state is updated 

### ISSUE THREAD

**Issue by skycremaschinin** [hashicorp/terraform-provider-aws#14404]
### Terraform CLI and Terraform AWS Provider Version
0.12.28

### Affected Resource(s)

* aws_acm_certificate

### Terraform Configuration Files

```
data "local_file" "private_key_cf" {
  filename = "${path.module}/${var.cloudfront_cert["privatekey_file"]}"
}

data "local_file" "certificate_cf" {
  filename = "${path.module}/${var.cloudfront_cert["certificate_file"]}"
}

data "local_file" "cert_ca_cf" {
  filename = "${path.module}/${var.cloudfront_cert["cert_ca_file"]}"
}

resource "aws_acm_certificate" "cert_cf" {
  private_key       = data.local_file.private_key_cf.content
  certificate_body  = data.local_file.certificate_cf.content
  certificate_chain = data.local_file.cert_ca_cf.content
  
  tags = {
    Name        = join(".", [var.project_info["prefix"], var.project_info["env"],"cert"])
    Project     = var.project_info["name"]
    Environment  = var.project_info["env"]
  }
}
```

### Expected Behavior

terraform state should not be saved with renewed certificates

### Actual Behavior
The following error shows up:

ValidationException: Tagging is not permitted on re-import.

but terraform state is update with renewed certificates, certificates aren't actually update.

A further plan results in  

No changes. Infrastructure is up-to-date.

### Steps to Reproduce

1. renew a tagged certificate

**Comment by IvanMoucha** [comment]
I can confirm the same behavior and expectation.
