### ISSUE TITLE
aws_ses_receipt_rule doesn't return name attribute

### ISSUE THREAD

**Issue by throwaway8787** [hashicorp/terraform-provider-aws#14415]
the `aws_ses_receipt_rule_set` module does not return any attributes.

`aws_ses_receipt_rule_set` is the parent of `aws_ses_receipt_rule`, and thusly one must add `depends_on`. If `aws_ses_receipt_rule_set` returned it's name one could pass the output to `aws_ses_receipt_rule` and let the graph cycle complete automatically without providing `depends_on`.

**Comment by ewbankkit** [comment]
@throwaway8787 Thanks for raising this issue.

Did you try adding a dependency like

```hcl
resource "aws_ses_receipt_rule_set" "example" {
  rule_set_name = "example"
}

resource "aws_ses_receipt_rule" "store" {
  rule_set_name = aws_ses_receipt_rule_set.example.rule_set_name
}
```

?

**Comment by DrFaust92** [comment]
Closing for lack of, @throwaway8787 if issues still persists please open a new issue with more detail
