### ISSUE TITLE
IAM role for aws_backup_selection should be optional

### ISSUE THREAD

**Issue by jeremietharaud** [hashicorp/terraform-provider-aws#14413]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
The property `iam_role_arn` should be optional for the resource aws_backup_selection since there is a AWS Service-Linked role for AWS Backup that is automatically created if it does not exist.

### New or Affected Resource(s)

* aws_backup_selection

### Potential Terraform Configuration

```hcl
resource "aws_backup_selection" "example" {
  # should work without iam_role_arn
  name         = "tf_example_backup_selection"
  plan_id      =  aws_backup_plan.example.id

  resources = [
    aws_db_instance.example.arn,
    aws_ebs_volume.example.arn,
    aws_efs_file_system.example.arn,
  ]
}
```

### References

https://docs.aws.amazon.com/aws-backup/latest/devguide/using-service-linked-roles.html

**Comment by DrFaust92** [comment]
API and SDK docs seem to imply its required:
https://docs.aws.amazon.com/aws-backup/latest/devguide/API_BackupSelection.html

if there is a gap between docs and actual functionality please open a ticket to AWS support, meanwhile im closing this.
