### ISSUE TITLE
[aws_elasticache_replication_group] PreferredCacheClusterAZs error occurred on 3.0

### ISSUE THREAD

**Issue by bruceleell** [hashicorp/terraform-provider-aws#14425]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform cli version: 0.12.6 
aws provider version: 3.0 

### Affected Resource(s)

* aws_elasticache_replication_group

### Terraform Configuration Files

Sorry, I cannot provide it. The code is private.

### Panic Output

```
Error: Error creating Elasticache Replication Group: InvalidParameterCombination: PreferredCacheClusterAZs can only be specified for one node group.
	status code: 400, request id: c02af4ed-19ae-4db6-a490-c9c412d46856
```

### Expected Behavior

It should create redis cluster on AWS successfully. And if I specify the version of AWS provider as 2.69, it's good.

### Actual Behavior

Create redis cluster failed

**Comment by gdavison** [comment]
HI @bruceleell. This error is typically seen when `availability_zones` and `cluster_mode` are both configured. You can specify `subnet_group_name` to control the availability zones if your Replication Group is in a VPC.

We are also working on #5118 to allow more control over clusters.
