### ISSUE TITLE
Turn on Dependabot for GitHub Actions

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#14437]
### Description

Dependabot is now able to [update GitHub Actions](https://docs.github.com/en/github/administering-a-repository/keeping-your-actions-up-to-date-with-github-dependabot). This should be enabled for the repo.

**Comment by bflad** [comment]
This has been working since we migrated GitHub Organizations. e.g. https://github.com/hashicorp/terraform-provider-aws/pull/16764
