### ISSUE TITLE
resource.aws_api_gateway_rest_api with body not updating

### ISSUE THREAD

**Issue by maxcbc** [hashicorp/terraform-provider-aws#14445]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.12.28
+ provider.aws v2.70.0
```

### Affected Resource(s)

* aws_api_gateway_rest_api 

### Terraform Configuration Files

```hcl
resource "aws_api_gateway_rest_api" "api" {
  name = var.domain_name
  body = var.open_api_specification
}
```

### Expected Behavior

When body is updated, it should overwrite body on rest_api

### Actual Behavior

rest_api body not updated

**Comment by voroniys** [comment]
I have the same issue. I just investigated it a little bit more. The resources definition are updated with the new body, what is not updated is deployment, and thus API GW stays serving old definitions. ATM the only workaround I have is destroy the deployment with destroy -target and than do apply again. This way deployment is refreshed and code from new body become active.

**Comment by bflad** [comment]
Hi folks 👋  Just dropping a quick note here that this behavior is currently expected, albeit not documented well. When using an OpenAPI specification or even fully declared via Terraform `aws_api_gateway_*` resources, the `aws_api_gateway_deployment` resource must be used and triggered for recreation (potentially triggering further downstream `aws_api_gateway_stage` resource updates). The `aws_api_gateway_deployment` resource supports a `triggers` map which may help in this scenario, e.g.

```terraform
resource "aws_api_gateway_deployment" "example" {
  # ... other configuration ...

  triggers = {
    open_api_specification = var.open_api_specification
  }
}
```

I'm going to leave this issue open here to ensure we have covered this particular documentation covered as part of our bug fix investigation and documentation enhancements in this area as part of #11344.

**Comment by bflad** [comment]
The next provider release will contain better deployment documentation in the `aws_api_gateway_rest_api`, `aws_api_gateway_deployment`, and `aws_api_gateway_stage` resources among others, but for the purposes of this issue here is the relevant configuration:

```terraform
resource "aws_api_gateway_rest_api" "example" {
  body = jsonencode({
    openapi = "3.0.1"
    info = {
      title   = "example"
      version = "1.0"
    }
    paths = {
      "/path1" = {
        get = {
          x-amazon-apigateway-integration = {
            httpMethod           = "GET"
            payloadFormatVersion = "1.0"
            type                 = "HTTP_PROXY"
            uri                  = "https://ip-ranges.amazonaws.com/ip-ranges.json"
          }
        }
      }
    }
  })

  name = "example"
}

resource "aws_api_gateway_deployment" "example" {
  rest_api_id = aws_api_gateway_rest_api.example.id

  triggers = {
    redeployment = sha1(jsonencode(aws_api_gateway_rest_api.example.body))
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_api_gateway_stage" "example" {
  deployment_id = aws_api_gateway_deployment.example.id
  rest_api_id   = aws_api_gateway_rest_api.example.id
  stage_name    = "example"
}
```

Substituting the `body` value with `file()` or a variable as appropriate for your environment.
