### ISSUE TITLE
data source for fsx_lustre_file_system

### ISSUE THREAD

**Issue by mtpdt** [hashicorp/terraform-provider-aws#14455]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There exists an [AWS resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_lustre_file_system) for `aws_fsx_lustre_file_system`. It would be great to have a corresponding Data Source.

### New or Affected Resource(s)
* `aws_fsx_lustre_file_system` Data Source

### Potential Terraform Configuration

```hcl
data "aws_fsx_lustre_file_system" "fsxl" {
  filter {
    name   = "tag:Name"
    values = "instancename"
  }
}
```

### References

* https://github.com/aws/aws-sdk-go/blob/master/service/fsx/api.go#L4874 - It looks like `aws-sdk-go`'s query method for file systems only allows for query by `FileSystemIds`, and doesn't allow filtering yet like other queries. So we either have to wait for AWS to implement it, or query all FSX file systems and manually filter them on terraform's end. I will try to see if AWS is willing to implement this feature for us.

**Comment by jdheyburn** [comment]
It's not uncommon for TF to filter resources locally, I would suggest we do not wait for AWS to implement it as we could be waiting for a long time.

Given that the data source name is singular (`aws_fsx_lustre_file_system`), there should be enough parameters provided to the user to allow them to request only one resource - not dissimilar to how [data_source_aws_ssm_patch_baseline.go](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_ssm_patch_baseline.go) operates. 

Would it be beneficial to have another data source for returning multiple `aws_fsx_lustre_file_systems`? I guess some use cases of how the data source would be used would be helpful in understanding what is preferred.

**Comment by mtpdt** [comment]
Thanks for the suggestion, I will take a look at how `ssm_patch_baseline` does it, and see if I can put together a working PR.
