### ISSUE TITLE
for_each over AWS security groups

### ISSUE THREAD

**Issue by scott-doyland-burrows** [hashicorp/terraform-provider-aws#14456]
### Terraform Version
```
Terraform v0.13.0-beta3
+ provider registry.terraform.io/hashicorp/aws v3.0.0
```

### Terraform Configuration Files
```
provider "aws" {
  region = "eu-west-2"
}

locals {
  securitygroupinboundipv4 = {
    "${aws_instance.ec2instance.private_ip}/32" = "8888"
    "0.0.0.0/0"                                 = "80"
  }
}

resource "aws_instance" "ec2instance" {
  ami           = "ami-0a13d44dccf1f5cf6"
  instance_type = "t2.micro"
}

resource "aws_security_group" "securitygroup" {
  name   = "mysecuritygroup"
  vpc_id = "vpc-xxxxxxxx"

  dynamic "ingress" {
    for_each = local.securitygroupinboundipv4

    content {
      cidr_blocks = ["${ingress.key}"]
      from_port   = ingress.value
      to_port     = ingress.value
      protocol    = "tcp"
    }
  }

}
```

### Expected Behavior
Terraform should create an EC2 instance.
Then it should obtain the private IP of the EC2 instance and create a security group containing the private IP allowed on port 8888 and all IPs allowed on port 80.

### Actual Behavior
The first run creates the EC2 instance and then has the error as below when creating the security group.

If I immediately rerun (EC2 already created) it creates the security group successfully.
If I do a destroy (so start from scratch) and then rerun with the line removed for 0.0.0.0/32 port 80, then it also works.
If I split the code, so that I have two distinct "ingress" blocks, once that uses the private IP variable and one that uses 0.0.0.0/0 then it also works.

ERROR on first run:
```aws_instance.ec2instance: Creating...
aws_instance.ec2instance: Still creating... [10s elapsed]
aws_instance.ec2instance: Still creating... [20s elapsed]
aws_instance.ec2instance: Creation complete after 22s [id=i-05e8019237d1a04bc]

Error: Provider produced inconsistent final plan

When expanding the plan for aws_security_group.securitygroup to include new
values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.ingress: length changed from 1 to 2.
```

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by trevorrea** [comment]
The private IP of the instance is only known at apply time as you're not setting a static private IP.  So Terraform is saying that the local had one value and then once the private IP was known the local was expanded to 2 which causes "confusion".

If it were me I would attach a security group to the instance and then use that security group to allow access rather than looking up the private IP address as all.  

So something like:-

```
provider "aws" {
  region = "eu-west-2"
}

resource "aws_instance" "ec2instance" {
  ami                    = "ami-0a13d44dccf1f5cf6"
  instance_type          = "t2.micro"
  vpc_security_group_ids = [aws_security_group.instance.id]
}

resource "aws_security_group" "instance" {
  name   = "securitygroup1"
  vpc_id = "vpc-xxxxxxxx"
}

resource "aws_security_group" "other" {
  name   = "securitygroup2"
  vpc_id = "vpc-xxxxxxxx"
}

resource "aws_security_group_rule" "instance" {
  type                     = "ingress"
  from_port                = 8888
  to_port                  = 8888
  protocol                 = "tcp"
  security_group_id        = aws_security_group.other.id
  source_security_group_id = aws_security_group.instance.id
}

resource "aws_security_group_rule" "anywhere" {
  type              = "ingress"
  from_port         = 80
  to_port           = 80
  protocol          = "tcp"
  security_group_id = aws_security_group.other.id
  cidr_blocks       = ["0.0.0.0/0"]
}
```

Also is there any particular reason you want to use for_each rather than distinct resources as the code without for_each is more readable (in my opinion)?

**Comment by scott-doyland-burrows** [comment]
I ended up with this (it is now a module).  So the same as you have suggested. 

I still use a variable for the IP allowed into the security group in rule1, as I want just one specific (unknown before it is created) IP to be allowed into the security group on port 8888 (FYI that security group is attached to an ECS service, so my EC2 instance sends outbound on port 8888, into the security group / ECS service).

I still think my original example should have worked, to me it seems that originally, the sec group should not have been created until the variable value was available as a "local" value.  But anyway - the new way works and it better overall.


module "securitygroupruleipv4sigserv" {
  source          = <my_module_source>
  securitygroupid = module.securitygroups

  securityrule = {

    rule1 = {
      ip = [
        "${module.ec2instance.private_ip}
      ]
      fromport = "8888"
      toport   = "8888"
      protocol = "tcp"
      type     = "ingress"
    }

    rule2 = {
      ip = [
        "0.0.0.0/0"
      ]
      fromport = "80"
      toport   = "80"
      protocol = "tcp"
      type     = "ingress"
    }
  }
}
