### ISSUE TITLE
Feature: Support for Sagemaker Studio resources

### ISSUE THREAD

**Issue by agrider** [hashicorp/terraform-provider-aws#14453]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has released a fully integrated IDE environment for ML called Sagemaker Studio. API's are now available and support for allocating resources has been added to boto3 for Sagemaker Studio. This request is for the addition of the resources and datasources needed to automate creation of Sagemaker Studio assets.

### New or Affected Resource(s)

* aws_sagemaker_user_profile
* aws_sagemaker_domain
* aws_sagemaker_app
* aws_sagemaker_code_repository

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://aws.amazon.com/blogs/aws/amazon-sagemaker-studio-the-first-fully-integrated-development-environment-for-machine-learning/
* https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html

**Comment by GISTech01** [comment]
The following AWS blog references Boto3 API for creating, updating and deleting AWS SageMaker Studio Domains - https://aws.amazon.com/blogs/machine-learning/creating-amazon-sagemaker-studio-domains-and-user-profiles-using-aws-cloudformation/
