### ISSUE TITLE
New Data Source : aws_iam_roles

### ISSUE THREAD

**Issue by Marcvd316** [hashicorp/terraform-provider-aws#14470]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be helpful to have a terraform data source that lists all the AWS IAM roles that exists in an account. An example of a use case where this would be useful is for roles created by AWS SSO in different accounts in an AWS Organization, the roles end up with a known prefix, but the last few characters are randomly generated (e.g.: AWSReservedSSO_Administrators_3785d47bba2d9cde4).

### New or Affected Resource(s)

* data.aws_iam_roles

### Potential Terraform Configuration

```hcl
data "aws_iam_roles" "administrators" {
  filter {
      name   = "role-name"
      values = ["AWSReservedSSO_Administrators_*"]
  }
}
```

### References

* IAM REST API ListRoles : https://docs.aws.amazon.com/IAM/latest/APIReference/API_ListRoles.html
* AWS CLI implementation of that API : https://docs.aws.amazon.com/cli/latest/reference/iam/list-roles.html

**Comment by michelzanini** [comment]
I had exactly that same requirement today 👍

**Comment by sidewinder12s** [comment]
Related to the ask: #14173

A resource like this more closely matches similar lookup requirements like the aws_subnet_ids data source.

**Comment by seddarj** [comment]
Hello, I've taken a bit of a different approach to solve this issue in #18048. Instead of listing all roles based on a filter, I try to find the role that matches the Permission Set for which it was created.

Feel free to have a look there and to comment on it 😅
