### ISSUE TITLE
Codebuild Batch Processing

### ISSUE THREAD

**Issue by charles-d-burton** [hashicorp/terraform-provider-aws#14472]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add the ability to configure Codebuild Batch processing to the provider.

### New or Affected Resource(s)

* aws_codebuild_project

### Potential Terraform Configuration

```hcl
codebuild_batch = {
  service_role_arn = <some arn>
  allowed_compute_types = []
  maximum_builds = <int>
  timeout = <hh::mm>
  combine_artifacts = true/false
}
```

### References

https://docs.aws.amazon.com/codebuild/latest/userguide/batch-build.html

* #0000

**Comment by ewbankkit** [comment]
[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/07/aws-codebuild-now-supports-parallel-and-coordinated-executions-of-a-build-project/).

Requires [AWS SDK v1.33.16](https://github.com/aws/aws-sdk-go/releases/tag/v1.33.16):

* #14000
