### ISSUE TITLE
Support direct resolvers in aws_appsync_resolver resource

### ISSUE THREAD

**Issue by npellegrin** [hashicorp/terraform-provider-aws#14488]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS now supports direct lambda resolvers in AppSync.

Developers can now send directly the request and build the response in a Lambda function, without the need to write VTL ( Apache Velocity Template Language) templates.

### New or Affected Resource(s)

* aws_appsync_resolver

### Potential Terraform Configuration

The fields `request_template` and `response_template` are now optional.
Sugested code:

```hcl
resource "aws_appsync_resolver" "test" {
  api_id      = aws_appsync_graphql_api.test.id
  field       = "singlePost"
  type        = "Query"
  data_source = aws_appsync_datasource.lambda.name
}
```

### References

AWS blog post:
 * https://aws.amazon.com/fr/blogs/mobile/appsync-direct-lambda/

Change in botocore (change available from 1.17.36):
 * https://github.com/boto/botocore/commit/06210b5a5158027da1a12db6c95602c4a9752fa9#diff-03a20e0acefe68dfa350f5c3d516a439L1216

Change in aws-sdk-go (change available from 1.33.20):
 * https://github.com/aws/aws-sdk-go/commit/2007a989b072e6c85ac3caf9d22753e0c7b3be17#diff-3788cc6943b7c1e2dcb5dcc3b9a853caL936

**Comment by ewbankkit** [comment]
[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/08/aws-appsync-releases-direct-lambda-resolvers-for-graphql-apis/).

Requires [AWS SDK v1.33.20](https://github.com/aws/aws-sdk-go/releases/tag/v1.33.20):

* #14000

**Comment by antonbabenko** [comment]
It turns out that direct lambda resolvers are using VTL templates under the hood, too.

This code is a workaround unless `request_template` and `response_template` are optional (#14710):

```terraform
resource "aws_appsync_resolver" "lambda" {
  api_id      = aws_appsync_graphql_api.this.id
  field       = "getLayer"
  type        = "Query"
  data_source = aws_appsync_datasource.lambda.name

  request_template = <<EOF
{
  "version" : "2017-02-28",
  "operation": "Invoke",
  "payload": $util.toJson($context.args)
}
EOF

  response_template = <<EOF
$util.toJson($context.result)
EOF
}
```
