### ISSUE TITLE
VPC Peer vpc_id vpc created route gets deleted when terraform apply is run a second time

### ISSUE THREAD

**Issue by wdanbag** [hashicorp/terraform-provider-aws#14496]
In creating a VPC Peer, the vpc_id vpc create route gets deleted after running terraform apply a second time.  It gets recreated when run a third time.  In the code below, aws_route.single2p-management gets destroyed when apply is run a second time and created again when apply gets run a third time etc..  No destroy message is in the output, just a refreshing of the route state. The route created going the opposite direction which is not below does not have this issue.

// Configure VPC Peering
resource "aws_vpc_peering_connection" "single2managment_vpc_peering" {
  peer_vpc_id   = var.vpc_p_managment.vpc_id
  vpc_id        = aws_vpc.single_vpc.id
  auto_accept   = true
}

// Create Route for single_vpc to reach the P's VPC over the peer
resource "aws_route" "single2p-management" {
    route_table_id = aws_route_table.mgmt_route_table.id
    destination_cidr_block = var.vpc_p_managment.cidr
    vpc_peering_connection_id = aws_vpc_peering_connection.single2managment_vpc_peering.id
}

**Comment by ewbankkit** [comment]
@wdanbag Thanks for raising this issue.
What is the value of `var.vpc_p_managment.cidr` in your example?

**Comment by wdanbag** [comment]
@ewbankkit 
"cidr" = "10.255.0.0/16"

**Comment by ewbankkit** [comment]
@wdanbag Do the `terraform apply`s that cause the route deletion show any diffs in the plan? If so, could you please attach.
Thanks.

**Comment by wdanbag** [comment]
@ewbankkit just to clarify, you would like the output from the two terraform Apply runs?

**Comment by ewbankkit** [comment]
Yes that would help. Thanks.

**Comment by wdanbag** [comment]
@ewbankkit <https://github.com/ewbankkit> 

Here are the outputs.  The first, Initial Run - terrformlogging.txt, the routes are correct.  The second, Second Run - terrformlogging.txt, the route is removed.  Please let me know if there is something else I can provide.

 

Thank you
