### ISSUE TITLE
Terraform state refresh doesn't notice "aws_eip" deletions

### ISSUE THREAD

**Issue by tedivm** [hashicorp/terraform-provider-aws#14519]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_eip

### Terraform Configuration Files

```hcl
resource "aws_eip" "nat" {
  count = 3
  vpc    = true
  lifecycle {
    create_before_destroy = true
  }
}

```

### Expected Behavior

Terraform should notice if one of the IP addresses doesn't actually exist.

### Actual Behavior

Terraform throws an error that the resource is empty.

> aws_eip.nat is empty tuple

### Steps to Reproduce

1. `terraform apply`
2. Delete an EIP from the console.
3. `terraform refresh`

**Comment by ewbankkit** [comment]
Similar:

* https://github.com/hashicorp/terraform-provider-aws/issues/13276
