### ISSUE TITLE
aws_lambda_event_source_mapping: incorrectly setting values for optional resource parameters that weren't explicitly specified

### ISSUE THREAD

**Issue by dlenski** [hashicorp/terraform-provider-aws#14522]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.12.29

* provider.aws: version = "~> 2.70"
* provider.null: version = "~> 2.1"
* provider.template: version = "~> 2.1"
```

### Affected Resource(s)

* aws_lambda_event_source_mapping

I attempted to modify this existing `aws_lambda_event_source_mapping` resource:

```tf
resource "aws_lambda_event_source_mapping" "event_source_mapping_name" {
  batch_size             = 1000
  event_source_arn       = var.dynamo_stream_arn
  enabled                = true
  function_name          = aws_lambda_function.lambda_n.arn
  starting_position      = "TRIM_HORIZON"
}
```

Originally-intended changes (The parallelization factor feature for AWS lambda stream processing was [announced in November 2019](https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-parallelization-factor-for-kinesis-and-dynamodb-event-sources/) and added to Terraform in https://github.com/terraform-providers/terraform-provider-aws/commit/2d5b2cd40f630cb0bf1fbd8dd1ebf34104bbc751#diff-943f35dca31585fb17f97dbca05290db.)

```diff
 resource "aws_lambda_event_source_mapping" "event_source_mapping_name" {
   batch_size             = 1000
+  parallelization_factor = 10
   event_source_arn       = var.dynamo_stream_arn
   enabled                = true
   function_name          = aws_lambda_function.lambda_n.arn
   starting_position      = "TRIM_HORIZON"
 }
```

Execution of these changes **fails**:

```
Error updating Lambda event source mapping: InvalidParameter: 1 validation error(s) found.
- minimum field value of 60, UpdateEventSourceMappingInput.MaximumRecordAgeInSeconds.
```

`terraform plan` shows why:

```tf
   # aws_lambda_event_source_mapping.event_source_mapping_name will be updated in-place
   ~ resource "aws_lambda_event_source_mapping" "event_source_mapping_name" {
         batch_size                         = 1000
         bisect_batch_on_function_error     = false
         enabled                            = true
         event_source_arn                   = "arn:aws:dynamodb:..."
         function_arn                       = "arn:aws:lambda:..."
         function_name                      = "arn:aws:lambda:..."
         id                                 = "deadbeef-dead-beef-f00f-deadbeeff00f"
         last_modified                      = "2020-08-06T05:49:00Z"
         last_processing_result             = "OK"
         maximum_batching_window_in_seconds = 0        # BAD!
         maximum_record_age_in_seconds      = 0        # BAD!
         maximum_retry_attempts             = 0        # BAD!
       ~ parallelization_factor             = 0 -> 10
         starting_position                  = "TRIM_HORIZON"
         state                              = "Enabled"
         state_transition_reason            = "User action"
         uuid                               = "deadbeef-dead-beef-f00f-deadbeeff00f"
     }
```

There are three other new parameters, marked with `# BAD!` above, which are apparently being set to a value of `0` even though:

* These parameters are all _optional_
* `0` is _not even a legal value_ for `maximum_record_age_in_seconds` or `maximum_retry_attempts`

https://github.com/terraform-providers/terraform-provider-aws/blob/1c28287a3de773d41e20c174591f0fd355c59e1b/aws/resource_aws_lambda_event_source_mapping.go#L99-L120

### Terraform Configuration Files

See relevant excerpt above.

### Debug Output

See relevant excerpt above.

### Panic Output

N/A

### Expected Behavior

- Terraform should have not attempted to set the optional parameters of this resource, since no explicit value was indicated for them.

### Actual Behavior

- Terraform attempted to set the value of 3 not-explicitly-included optional, numeric parameters to a value of `0` (which is neither a default value, nor even a valid value, for some of them)

- My hypothesis is that there is a faulty internal model for the state of an optional parameter that has never been set previously.

- In order to work around this, I had to _explicitly_ set these parameters to their default values:

```diff
 resource "aws_lambda_event_source_mapping" "event_source_mapping_name" {
   batch_size             = 1000
+  parallelization_factor = 10
   event_source_arn       = var.dynamo_stream_arn
   enabled                = true
   function_name          = aws_lambda_function.lambda_n.arn
   starting_position      = "TRIM_HORIZON"

+  # Workaround for apparent Terraform issue?
+  # Default values of these parameters seem to be: https://github.com/awsdocs/aws-cloudformation-user-guide/pull/767
+  maximum_batching_window_in_seconds = 0
+  maximum_record_age_in_seconds      = 604800
+  maximum_retry_attempts             = 10000
 }
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

* PR to add documentation on default values/semantics of `AWS::Lambda::EventSourceMapping` optional parameters: https://github.com/awsdocs/aws-cloudformation-user-guide/pull/767

**Comment by danieladams456** [comment]
I'm not sure if this is related or not, but if I set `batch_size` and then remove that parameter or set it to `null`, I get the following error.  I would expect it to go back to the default.

```
  # aws_lambda_event_source_mapping.event_source will be updated in-place
  ~ resource "aws_lambda_event_source_mapping" "event_source" {
      - batch_size                         = 5 -> null
        id                                 = "23c57369-45c0-492b-80fa-82964730f9e1"
        # (13 unchanged attributes hidden)
    }

Error: Error updating Lambda event source mapping: InvalidParameter: 1 validation error(s) found.
- minimum field value of 1, UpdateEventSourceMappingInput.BatchSize.
```

**Comment by dlenski** [comment]
@danieladams456, definitely seems like it could be related. In both cases, a not-present *optional* parameter is getting set to a value that isn't legal for it.

**Comment by HongChenTW** [comment]
Hi @dlenski, seems that your PR was overwritten by AWS docs auto-gen mechanism...

awsdocs/aws-cloudformation-user-guide@b2a0d98
