### ISSUE TITLE
Kinesis Analytics application tags already registered after successive apply

### ISSUE THREAD

**Issue by jacobus-herman** [hashicorp/terraform-provider-aws#14541]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.12.29
+ provider.aws v3.1.0
```

### Affected Resource(s)

* aws_kinesis_analytics_application

### Terraform Configuration Files

```hcl
provider "aws" {
  profile = "profile"
  version = "~> 3.0"
  region  = "eu-central-1"
}

locals {
  common_aws_cost_tags = {
    "tag1" = "value1"
    "tag2" = "value2"
  }
}

data "aws_region" "current" {}

data "aws_iam_policy_document" "StreamReaderWriter" {
  statement {
    effect = "Allow"
    actions = ["kinesis:DescribeStream",
      "kinesis:GetShardIterator",
    "kinesis:GetRecords"]
    resources = [aws_kinesis_stream.EventsStream.arn]
  }
}

data "aws_iam_policy_document" "KinesisAssume" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["kinesisanalytics.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "kapp" {
  name               = "kapp_${data.aws_region.current.name}"
  path               = "/"
  tags               = local.common_aws_cost_tags
  assume_role_policy = data.aws_iam_policy_document.KinesisAssume.json
}

resource "aws_iam_role_policy_attachment" "attach_kapp" {
  role       = aws_iam_role.kapp.name
  policy_arn = aws_iam_policy.StreamReaderWriter.arn
}

resource "aws_kinesis_stream" "EventsStream" {
  name             = "events"
  shard_count      = 1
  retention_period = 168
  tags             = local.common_aws_cost_tags
}

resource "aws_kinesis_analytics_application" "kapp" {
  name = "kapp"
  tags = local.common_aws_cost_tags
  description = "bla bla bla description"
  code = <<-EOT
              # Some code.
              EOT
  inputs {
    name_prefix = "EventsInputStream"

    kinesis_stream {
      resource_arn = aws_kinesis_stream.EventsStream.arn
      role_arn     = aws_iam_role.kapp.arn
    }

    parallelism {
      count = 1
    }

    schema {
      record_encoding = "UTF-8"
      record_columns {
        mapping  = "$.request_id"
        name     = "request_id"
        sql_type = "VARCHAR(64)"
      }

      record_columns {
        mapping  = "$.timestamp"
        name     = "event_timestamp"
        sql_type = "TIMESTAMP"
      }

      record_format {
        mapping_parameters {
          json {
            record_row_path = "$"
          }
        }
      }
    }
  }
}

resource "aws_iam_policy" "StreamReaderWriter" {
  name   = "KinesisStreamReaderWriter_${data.aws_region.current.name}"
  path   = "/"
  policy = data.aws_iam_policy_document.StreamReaderWriter.json
}
```

### Debug Output

https://gist.github.com/jacobus-herman/8134ea613465fa51505f87d4d3417a05

### Expected Behavior

At `2020/08/10 14:51:37` the execution of the first `terraform apply` is successful and at `2020/08/10 14:55:04` the destruction of the resources is also successful. However, executing a second `terraform apply` at `2020/08/10 14:55:43`, I expected the aws_kinesis_analytics_application resource to be provisioned successfully.

### Actual Behavior

The aws_kinesis_analytics_application was not provisioned (after running the second `terraform apply`) and an `Error: Unable to create Kinesis Analytics application: ConcurrentModificationException: Tags are already registered for this resource ARN: arn:aws:kinesisanalytics:eu-central-1:069176307164:application/kapp, please retry later. Or you can create without tags and then add tags using TagResource API after successful resource creation.` message was returned.

### Steps to Reproduce

1. `terraform apply`
1. `terraform destroy`
1. `terraform apply`

### Important Factoids

I did notice that after waiting about 14 minutes and running `terraform apply` again, the aws_kinesis_analytics_application resource was successfully provisioned.

**Comment by ewbankkit** [comment]
@jacobus-herman Thanks for raising this issue an apologies for the delay in responding.
The code to wait for the application to move from `DELETING` state to being removed is incorrect:

https://github.com/terraform-providers/terraform-provider-aws/blob/3663a904afb87436d7cdc14d5eb004523dc92ce8/aws/resource_aws_kinesis_analytics_application.go#L875-L887

`d.Id()` is the application's ARN but the code inside the `waitForDeleteKinesisAnalyticsApplication` function expects it to be the application name, hence the error in the log:

```
2020-08-10T14:55:21.209+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5.exe: 2020/08/10 14:55:21 [DEBUG] [aws-sdk-go] {"__type":"ValidationException","message":"1 validation error detected: Value 'arn:aws:kinesisanalytics:eu-central-1:123456789012:application/kapp' at 'applicationName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+"}
2020-08-10T14:55:21.209+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5.exe: 2020/08/10 14:55:21 [DEBUG] [aws-sdk-go] DEBUG: Validate Response kinesisanalytics/DescribeApplication failed, attempt 0/25, error ValidationException: 1 validation error detected: Value 'arn:aws:kinesisanalytics:eu-central-1:123456789012:application/kapp' at 'applicationName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+
2020-08-10T14:55:21.209+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5.exe: 	status code: 400, request id: b061b7f9-23d8-4804-99d2-9751840b1431
```

The code to check the response from that API call is also incorrect, not returning the underlying AWS error:

https://github.com/terraform-providers/terraform-provider-aws/blob/3663a904afb87436d7cdc14d5eb004523dc92ce8/aws/resource_aws_kinesis_analytics_application.go#L1611-L1620

so Terraform thinks the resource has been deleted even though at AWS it's still `DELETING` and you get the `ConcurrentModificationException: Tags are already registered for this resource` error.

I am in the middle of implementing a fix for https://github.com/terraform-providers/terraform-provider-aws/issues/15881 and will include the fix for this issue in the same PR.
