### ISSUE TITLE
Error while running terraform plan from visual studio code

### ISSUE THREAD

**Issue by NavneetKourSidhu** [hashicorp/terraform-provider-aws#14562]
Error: Failed to instantiate provider "aws" to obtain schema: Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.

I have installed latest version of terraform and intialized terraform with terraform init comand as well but still getting above error.

**Comment by breathingdust** [comment]
Hi @NavneetKourSidhu 👋  Unfortunately we are unable to investigate IDE level issues.
