### ISSUE TITLE
VPN Connection customer_gateway_configuration attribute returning string instead of plain XML

### ISSUE THREAD

**Issue by AMMullan** [hashicorp/terraform-provider-aws#14598]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
v0.12.26

### Affected Resource(s)
aws_vpn_connection

### Terraform Configuration Files
```hcl
output "vpn_gw_config" {
  value = [aws_vpn_connection.vpn_connection.*.customer_gateway_configuration]
}
```

### Expected Behavior
Should return valid XML i.e.
```xml
[
    <?xml version="1.0" encoding="UTF-8"?>
<vpn_connection id="vpn-xxx">
  <customer_gateway_id>cgw-xxx</customer_gateway_id>
  <vpn_gateway_id>vgw-xxx</vpn_gateway_id>
  <vpn_connection_type>ipsec.1</vpn_connection_type>
  <ipsec_tunnel>
```

### Actual Behavior
Seems to add lists and escapes characters, i.e.
```xml
[
  [
    [
      "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<vpn_connection id=\"vpn-xxx\">\n  <customer_gateway_id>cgw-xxx</customer_gateway_id>\n  <vpn_gateway_id>vgw-xxx</vpn_gateway_id>\n
```

### Steps to Reproduce
1. `terraform apply`

**Comment by AMMullan** [comment]
Looking at the output further it seems like it's quoting the entire string, which is why it's likely escaped. Taking that it's a list I can't see any easy way to use functions to clean this up either.

**Comment by justinretzolk** [comment]
Hey @AMMullan 👋 Thank you for filing this. I think that [jsondecode](https://www.terraform.io/docs/language/functions/jsondecode.html) may give you the unescaped output that you're looking for. Can you test that and let me know if you run into additional issues?

**Comment by ewbankkit** [comment]
@AMMullan It seems like you would like the customer gateway configuration XML string decoded into a Terraform `object` similar to how the `jsondecode` function does for JSON strings? Is my understanding correct?
Thanks.

**Comment by AMMullan** [comment]
Hey @ewbankkit  - think that's correct, yes. I've actually moved teams so no longer involved in the every day usage of this but I know that it was causing quite a few issues.
