### ISSUE TITLE
Add support for RDS snapshot permissions (sharing)

### ISSUE THREAD

**Issue by tdmalone** [hashicorp/terraform-provider-aws#14600]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for sharing manual RDS snapshots with other accounts (snapshot permissions, implemented through the [ModifyDBSnapshotAttribute API method](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBSnapshotAttribute.html)).

### New or Affected Resource(s)

* [aws_db_snapshot](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_snapshot)

### Potential Terraform Configuration

```hcl
resource "aws_db_snapshot" "main" {
  db_instance_identifier = "my-instance"
  db_snapshot_identifier = "my-snapshot"

  attribute {
    name   = "restore"
    values = [111122223333, 444455556666]
  }

  tags = {
    "Managed By" = "Terraform"
  }
}
```

### References

* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ShareSnapshot.html
* https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBSnapshotAttribute.html

**Comment by tdmalone** [comment]
Workaround:

```hcl
resource "aws_db_snapshot" "main" {
  db_instance_identifier = "my-instance"
  db_snapshot_identifier = "my-snapshot"

  provisioner "local-exec" {
    command = <<-EOF
      aws rds modify-db-snapshot-attribute \
        --db-snapshot-identifier "my-snapshot" \
        --attribute-name "restore" \
        --values-to-add {"111122223333", "444455556666"}
    EOF
  }

  tags = {
    "Managed By" = "Terraform"
  }
}
```

**Comment by tdmalone** [comment]
Possibly related, to some extent: #9885 & #3295 (requests to add support for `CopyDBSnapshot`)

**Comment by Hamza-Aziz** [comment]
is this not yet supported ?

**Comment by atuljadhav316** [comment]
> Workaround:
> 
> ```terraform
> resource "aws_db_snapshot" "main" {
>   db_instance_identifier = "my-instance"
>   db_snapshot_identifier = "my-snapshot"
> 
>   provisioner "local-exec" {
>     command = <<-EOF
>       aws rds modify-db-snapshot-attribute \
>         --db-snapshot-identifier "my-snapshot" \
>         --attribute-name "restore" \
>         --values-to-add '["111122223333", "444455556666"]'
>     EOF
>   }
> 
>   tags = {
>     "Managed By" = "Terraform"
>   }
> }
> ```

for this work araound , the provisioner local-exec block starts executing before the snapshot is completely created, any changes i can make?

**Comment by MrFishFinger** [comment]
this looks like it has now been implemented with the `shared_accounts` argument:

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_snapshot#shared_accounts

i guess this ticket could probably be closed

**Comment by ikegentz** [comment]
The `shared_accounts` argument works for the `aws_db_snapshot` resource itself, but it would be great to also have for `aws_db_snapshot_copy`

**Comment by ikegentz** [comment]
Related, but for RDS Clusters (Aurora) https://github.com/hashicorp/terraform-provider-aws/issues/31359

**Comment by ewbankkit** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/28424.
