### ISSUE TITLE
aws s3 lifecycle bucket wants to set expiration to null when abort multipart upload is present

### ISSUE THREAD

**Issue by mpodber1971** [hashicorp/terraform-provider-aws#14603]
when i add a lifecycle policy to delete abort multipart uploads and do NOT include an expiration on an AWS s3 bucket, terraform wants to set the expiration to null. It is misleading and a little concerning as to whether I accidentally implemented a lifecycle policy to delete our production data.

If the multi part upload isn't present, then terraform acts as expected.

I have attached the plan before apply, aws cli showing lifecycle post apply and a second terraform plan showing that it wants to apply these changes.

[test-bucket-post-apply-new-plan.log](https://github.com/terraform-providers/terraform-provider-aws/files/5064111/test-bucket-post-apply-new-plan.log)
[test-bucket-lifecycle-post-apply.log](https://github.com/terraform-providers/terraform-provider-aws/files/5064112/test-bucket-lifecycle-post-apply.log)
[test-bucket-pre-apply.log](https://github.com/terraform-providers/terraform-provider-aws/files/5064113/test-bucket-pre-apply.log)

**Comment by mjreed-turner** [comment]
Confirming. The documentation for the `lifecycle_rule` block says that one of 'expiration' or 'transition' (or their `noncurrent_` equivalents) is required, but the `abort_multipart_upload` rule is also a top-level rule that should be allowed to stand alone. I don't know why it's adding `expiration` in there.
