### ISSUE TITLE
resource/aws_guardduty_detector: S3 events with GuardDuty

### ISSUE THREAD

**Issue by vaishnavmurthy** [hashicorp/terraform-provider-aws#14607]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Could you create a Terraform resource to enable S3 events with GuardDuty?

### New or Affected Resource(s)
Details / documentation here: https://docs.aws.amazon.com/guardduty/latest/ug/s3_detection.html

Relevant AWS CLI command:
aws guardduty update-member-detectors --detector-id 12abc34d567e8fa901bc2d34e56789f0 --account-ids 123456789012 --data-sources '{"S3Logs":{"Enable":true}}'

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by ewbankkit** [comment]
[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/07/amazon-guardduty-expands-threat-detection-coverage-to-help-you-better-protect-your-data-stored-in-amazon-s3/).

Requires [AWS SDK v1.33.15](https://github.com/aws/aws-sdk-go/releases/tag/v1.33.15):

* #14000

**Comment by pietro** [comment]
I'm willing to implement this myself.

The AWS API and corresponding AWS Go SDK methods have a `DataSources` parameter for the create and update requests. That parameter has one S3Logs parameter with one boolean field for enabling/disabling S3 detection.

IMHO, the most straight forward way to add this feature would be to add a boolean parameter called something like `enable_s3_detection` and construct `DataSources` and `S3Logs` structs from that.

For better provider resource/AWS API parity we might want to add a `data_sources` block with the `enable_s3_detection` parameter in it.

What's the preferred way to add this feature to this resource?

**Comment by bflad** [comment]
Hi @pietro 👋  Thank you for reaching out and for your interest in implementing this! We typically prefer following the API structures for consistency with other AWS tooling (CLI, etc.) and to prevent future maintenance/deprecation issues with our own abstractions. 👍 

Briefly looking at the API reference, the equivalent Terraform configuration we would expect here would be something like:

```terraform
resource "aws_guardduty_detector" "example" {
  # ... other configuration ...

  datasources {
    s3_logs {
      enable = true
    }
  }
}
```

**Comment by michaelm-88** [comment]
@ewbankkit  any update on this

**Comment by jacoor** [comment]
Any update, please?

**Comment by dimisjim** [comment]
hi @pietro 

Willing to resume or should someone else pick this up?

**Comment by m-stojanovic** [comment]
any news about when this is going to be implemented? @pietro @bflad
