### ISSUE TITLE
New resource aws_secretsmanager_resource_policy

### ISSUE THREAD

**Issue by ribeiroh** [hashicorp/terraform-provider-aws#14618]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
It would be interesting to have the ability to decouple the creation of a Secrets Manager from the definition of its resource policy. This is useful if you need to "inject" the policy from a separate module, especially when that happens after the secret already exists.

### New or Affected Resource(s)

* aws_secretsmanager_resource_policy

### Potential Terraform Configuration

```hcl
resource "aws_secretsmanager_secret" "example" {
  name = "example"
}

resource "aws_secretsmanager_resource_policy" "example_policy {
  secret_arn = aws_secretsmanager_secret.example.arn
  block_public_policy = true
  policy = <JSON policy>
}
```

### References

* [PutResourcePolicy](https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_PutResourcePolicy.html)
* [DeleteResourcePolicy](https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_DeleteResourcePolicy.html)

**Comment by DrFaust92** [comment]
will be added in #14468 

ill add `block_public_policy` argument as well
