### ISSUE TITLE
Adding `capacity_provider_strategy` leads to removal of autoscaling policy targets

### ISSUE THREAD

**Issue by jay-dee7** [hashicorp/terraform-provider-aws#14615]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.29
+ provider.aws v2.70.0
+ provider.template v2.1.2

### Affected Resource(s)
* aws_ecs_service
* aws_appautoscaling_policy (potentially)
* aws_appautoscaling_target (potentially)

### Terraform Configuration Files
> Webapp Config
```hcl
resource "aws_ecs_service" "fargate_webapp_service" {

  name            = "webapp"
  task_definition = aws_ecs_task_definition.webapp.family
  cluster         = aws_ecs_cluster.fargate_cluster.id

  desired_count = lookup(var.webapp_fargate_conf, "replicas", 1)
  launch_type   = lookup(var.webapp_fargate_conf, "capacity_provider_strategy", false) ? null : "FARGATE"

  deployment_minimum_healthy_percent = 100
  deployment_maximum_percent         = 200

  network_configuration {
    security_groups  = [data.terraform_remote_state.vpc.outputs.webappp_sg]
    subnets          = [data.terraform_remote_state.vpc.outputs.private_app_subnet_id]
    assign_public_ip = true
  }

  dynamic "capacity_provider_strategy" {
    for_each = lookup(var.webapp_fargate_conf, "capacity_provider_strategy", false) ? tolist([
      {
        capacity_provider = "FARGATE_SPOT"
        weight            = lookup(var.webapp_fargate_conf, "fargate_spot_weight", var.default_fargate_spot_weight)
        base              = lookup(var.webapp_fargate_conf, "fargate_spot_base", var.default_fargate_spot_base)
      },
      {
        capacity_provider = "FARGATE"
        weight            = lookup(var.webapp_fargate_conf, "fargate_weight", var.default_fargate_weight)
        base              = lookup(var.webapp_fargate_conf, "fargate_base", var.default_fargate_base)
      }
    ]) : []

    content {
      capacity_provider = capacity_provider_strategy.value["capacity_provider"]
      weight = capacity_provider_strategy.value["weight"]
      base = capacity_provider_strategy.value["base"]
    }
  }

  load_balancer {
    target_group_arn = aws_alb_target_group.webapp_alb_targets.id
    container_name   = "nginx_service"
    container_port   = "80"
  }

  depends_on = [aws_iam_role_policy_attachment.ecs_task_execution_role]

  lifecycle {
    ignore_changes = [desired_count]
  }
}
```

> AppAutoScaling Config

```hcl
resource "aws_appautoscaling_target" "webapp" {

  max_capacity       = lookup(var.webapp_fargate_conf, "auto_scaling_max_replicas", var.webapp_fargate_conf["replicas"])
  min_capacity       = var.webapp_fargate_conf["replicas"]
  resource_id        = "service/${aws_ecs_cluster.fargate_cluster.name}/webapp"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"

  depends_on = [aws_ecs_service.fargate_webapp_service]
}

resource "aws_appautoscaling_policy" "webapp_cpu_scaleup_policy" {

  name               = "${aws_ecs_cluster.fargate_cluster.name}-webapp-scale-up-policy"
  policy_type        = "StepScaling"
  resource_id        = aws_appautoscaling_target.webapp.resource_id
  scalable_dimension = aws_appautoscaling_target.webapp.scalable_dimension
  service_namespace  = aws_appautoscaling_target.webapp.service_namespace

  step_scaling_policy_configuration {
    adjustment_type         = "ChangeInCapacity"
    cooldown                = lookup(var.webapp_fargate_conf, "cpu_scaleup_cooldown_period", 180)
    metric_aggregation_type = "Average"

    step_adjustment {
      metric_interval_lower_bound = 0
      metric_interval_upper_bound = 20
      scaling_adjustment          = 1
    }

    step_adjustment {
      metric_interval_lower_bound = 20
      scaling_adjustment          = 2
    }

  }

  depends_on = [aws_ecs_service.fargate_webapp_service]
}
```

> Providing input to this code
```hcl
webapp_fargate_conf = {
    cpu                             = 512
    memory                          = 1024
    replicas                        = 1
    auto_scaling_max_replicas       = 4
    cpu_scaleup_datapoints_to_alarm = "1"
    cpu_scaleup_eval_period         = "1"

    capacity_provider_strategy = false
    fargate_spot_weight = 3
    fargate_weight = 1
    fargate_base = 0
    fargate_spot_base = 1
  }
```
### Expected Behavior
when `capacity_provider_strategy = false`, it should run the ecs service with `launch_type=FARGATE` (and it does), but when we set `capacity_provider_strategy = true`, terraform runs successfully but the ecs services ends up losing the autoscaling policy, in the plan, it doesn't show as removing the autoscaling policy or the target, but it gets removed.
And if you run the same configuration without any changes, it notifies for adding the appautoscaling policy back.

### Actual Behavior
while switching from `launch_type` to `capacity_provider_strategy`, it should not removed autoscaling policy+targets.

### Steps to Reproduce
1. Rename the cluster according to your own setup
2. `terraform init`
3. `terraform apply`

### Important Factoids
> We're running this on `ECS FARGATE`, using `launch_type`, but an ecs service can either have `launch_type` or `capacity_provider_strategy`. So we recently made a change to accomodate more flexibility into our cluster and ended up with this issue. Right now we're just applying the terrraform config twice and it all works fine, but in reality, running it once should've been enough

**Comment by pseidel-kcf** [comment]
We've been bitten by this when changing capacity provider weights.

**Comment by jay-dee7** [comment]
Hey @pseidel-kcf were you able to find a work-around for this?

**Comment by pseidel-kcf** [comment]
We just apply a second time. Normally after we notice a queue has fallen behind because auto scaling is broken.

**Comment by jay-dee7** [comment]
guys any updates on this? I personally would love to work on this if this actually is a bug.
