### ISSUE TITLE
plan for aws_elasticsearch_domain shows differences in 3.10.0 version after 2.70.0

### ISSUE THREAD

**Issue by m3nthal** [hashicorp/terraform-provider-aws#14628]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.29
+ provider.aws v3.1.0
+ provider.kubernetes v1.12.0
+ provider.template v2.1.2

### Affected Resource(s)

* aws_elasticsearch_domain

### Terraform Configuration Files

```hcl

resource "aws_cloudwatch_log_group" "application_logs" {
  count             = var.elastic_enabled == true ? 1 : 0
  name              = "/aws/eks/debug/application-logs"
  # irrelevant parts omitted
}

resource "aws_elasticsearch_domain" "elasticsearch" {
  count                 = var.elastic_enabled == true ? 1 : 0

# irrelevant parts omitted

  log_publishing_options {
    cloudwatch_log_group_arn = aws_cloudwatch_log_group.application_logs.0.arn
    log_type                 = "ES_APPLICATION_LOGS"
    enabled                  = true
  }
}
```

### Debug Output

Relevant part of Terraform plan:
```
      + log_publishing_options {
          + cloudwatch_log_group_arn = "arn:aws:logs:****************************:log-group:/aws/eks/debug/application-logs"
          + enabled                  = true
          + log_type                 = "ES_APPLICATION_LOGS"
        }
      - log_publishing_options {
          - cloudwatch_log_group_arn = "arn:aws:logs:****************************:log-group:/aws/eks/debug/application-logs:*" -> null
          - enabled                  = true -> null
          - log_type                 = "ES_APPLICATION_LOGS" -> null
        }
```

Terraform state shows correct arn of the log group (with `:*` at the end):

```hcl
resource "aws_cloudwatch_log_group" "search_logs" {
    arn               = "arn:aws:logs:****************************:log-group:/aws/eks/debug/search-logs:*"
   # irrelevant parts omitted
}
```

### Expected Behavior

Terraform plan should not show any differences. As in 2.70.0 version of aws provider.

### Actual Behavior
3.10.0 version of aws provider shows differences in arn (note the `:*` on the end) of the log group, however nothings was changed apart from aws provider version.

### Steps to Reproduce

1. terraform apply with aws-provider 2.70.0
2. terraform plan with aws-provider 3.10.0

**Comment by anGie44** [comment]
Hi @m3nthal thank you for creating this issue! since the major version release of `3.0.0` of the provider, the `aws_cloudwatch_log_group` resource's `arn` attribute no longer is returned with the `:*` suffix, explaining the diff you're seeing. A workaround to suppress this diff is to use the string interpolation `${aws_cloudwatch_log_group}.arn}:*"` in the `cloudwatch_log_group_arn` reference. Further upgrade examples are also available [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#resource-aws_cloudwatch_log_group). 

Hope this helps and if you have additional questions, please let me know 😃
