### ISSUE TITLE
importing aws_lambda_permission forces replacement

### ISSUE THREAD

**Issue by a-watson** [hashicorp/terraform-provider-aws#14661]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_lambda_permission

### Terraform Configuration Files

Not terribly relevant for this bug. This is the configuration for the aws_lambda_permission resource, but any valid values for `function_name` and `source_arn` can be subsitituted:

```hcl
resource "aws_lambda_permission" "allow_cloudwatch" {
  action        = "lambda:InvokeFunction"
  function_name = "my_function"
  principal     = "events.amazonaws.com"
  source_arn    = "arn:aws:events:us-east-1:account-id:rule/my-rule"
}

```

### Expected Behavior

When I import this resource with `my_function/statement-id` I expect `terraform plan` to list no changes required for this resource.

### Actual Behavior

The import sets the full function ARN as the `function_name` in the terraform state instead of just the name, so `terraform plan` thinks the resource needs to be replaced.

```
  # module.monitoring.aws_lambda_permission.allow_cloudwatch must be replaced
-/+ resource "aws_lambda_permission" "allow_cloudwatch" {
        action        = "lambda:InvokeFunction"
      ~ function_name = "arn:aws:lambda:us-east-1:my-account-id:function:my-function" -> "my-function" # forces replacement                    
      ~ id            = "my-id" -> (known after apply)
        principal     = "events.amazonaws.com"
        source_arn    = "arn:aws:events:us-east-1:my-account-id:rule/my-rule"                                                                                               
      ~ statement_id  = "my-id" -> (known after apply)
    }


```

### Steps to Reproduce

1. `terraform apply`
2. delete the terraform state (oops)
3. `terraform import <function-name>/<statement-id>`
4. `terraform plan`

### Important Factoids
Here's the state of a freshly deployed aws_lambda_permission:
```
    {
      "module": "module.monitoring",
      "mode": "managed",
      "type": "aws_lambda_permission",
      "name": "allow_cloudwatch",
      "provider": "module.monitoring.provider.aws",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "action": "lambda:InvokeFunction",
            "event_source_token": null,
            "function_name": "my-function",
            "id": "my-id",
            "principal": "events.amazonaws.com",
            "qualifier": "",
            "source_account": null,
            "source_arn": "arn:aws:events:us-east-1:my-account-id:rule/my-rule",
            "statement_id": "my-id",
            "statement_id_prefix": null
          },
          "private": "foobarbaz",
        }
      ]
    }
```
and the same resource after importing:
```
    {
      "module": "module.monitoring",
      "mode": "managed",
      "type": "aws_lambda_permission",
      "name": "allow_cloudwatch",
      "provider": "module.monitoring.provider.aws",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "action": "lambda:InvokeFunction",
            "event_source_token": null,
            "function_name": "arn:aws:lambda:us-east-1:my-account-id:function:my-function",
            "id": "my-id",
            "principal": "events.amazonaws.com",
            "qualifier": "",
            "source_account": null,
            "source_arn": "arn:aws:events:us-east-1:my-account-id:rule/my-rule",
            "statement_id": "my-id",
            "statement_id_prefix": null
          },
          "private": "foobarbaz",
        }
      ]
    }
```

**Comment by ashokdasari06** [comment]
We see similar issue with our lambda module too. Terraform forces replacement on all resources that uses the lambda function_name. Here is what i did.

1. Created 2 lambdas using our lambda module and its successful.
2. Tried adding dead letter queue or a SQS event source to one of the lambdas and that forces a replacement of both lambdas, cloudwatch log groups and SSM parameters which uses lambda function_name.
3. When i run terraform apply i see an error that the lambda already exists.

**Comment by a-watson** [comment]
@ashokdasari06 I took a look at your issue, #14925, and I'm fairly confident they're unrelated. The issue I'm reporting here is specifically that the state generated by `terraform import` doesn't match the state if you create the same resource using `terraform apply`. I don't believe you're using import anywhere.

**Comment by oshmyrko** [comment]
I have the same issue:
```
$ terraform version
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.65.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

```bash
$ terraform import module.my_handler.aws_lambda_permission.permission my-handler/AllowExecutionFromLb

$ terraform plan
  # module.my_handler.aws_lambda_permission.permission must be replaced
-/+ resource "aws_lambda_permission" "permission" {
      ~ function_name = "arn:aws:lambda:eu-west-1:123456789000:function:my-handler" -> "my-handler" # forces replacement
      ~ id            = "AllowExecutionFromLb" -> (known after apply)
        # (3 unchanged attributes hidden)
    }
```

**Comment by ahmadelafify** [comment]
+1 I also am facing this issue

**Comment by shbedev** [comment]
Looks like this issue did not get any answers recently. We are also running into the same issue, and I am wondering if this issue should be open under the relevant repo (https://github.com/terraform-aws-modules/terraform-aws-lambda)? Maybe it will get more attention.

**Comment by shbedev** [comment]
If you want to work around this:
1. Clone the repo
2. Change the module source to the path of the cloned repo
3. In the _main.tf_ file, do **one** of the following:
- Change `function_name` variable inside `aws_lambda_permission` resource to `aws_lambda_function.this[0].arn` instead of `aws_lambda_function.this[0].function_name`
- Inside `aws_lambda_permission` resource, add `ignore_changes` to ignore the name change
`lifecycle {
    ignore_changes = [function_name]
  }`

**Comment by shbedev** [comment]
Same issue here. The import inputs the function's ARN instead of the function's name into the state, which forces replacement.
```
# aws_lambda_permission.qualified_alias_triggers["statement_id"] must be replaced
-/+ resource "aws_lambda_permission" "qualified_alias_triggers" {
      ~ function_name       = "arn:aws:lambda:us-west-2:xxx:function:function_name" -> "function_name" # forces replacement
      ~ id                  = "statement_id" -> (known after apply)
      + statement_id_prefix = (known after apply)
        # (6 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

**Comment by shoheihosaka7** [comment]
I had the same issue with lambda function when I imported existing lambda function.
I tried to remove and  import the same resource several times without changing my src, then it was suddenly resolve.   

`  # aws_lambda_function.my_function must be replaced
-/+ resource "aws_lambda_function" "my_function" {
      ~ arn                            = "arn:aws:lambda:ap-northeast-1:123456789012:my_function" -> (known after apply)
      ~ function_name                  = "arn:aws:lambda:ap-northeast-1:123456789012:function:my_function" -> "my_function" `

**Comment by lukej7** [comment]
Has anyone found a workaround for this? I am experiencing the same issue and cannot seem to find an alternative to replacing the aws_lambda_permission

**Comment by duganth** [comment]
I resorted to editing the statefile directly.

**Comment by kishaningithub** [comment]
An Open PR that addresses this issue https://github.com/hashicorp/terraform-provider-aws/pull/16436

**Comment by justinretzolk** [comment]
It looks like the PR above fixes this has been merged, so I'm going to close this issue. If you encounter the same issue, please open a new issue (referencing this one as needed) so that we can triage it appropriately.
