### ISSUE TITLE
Add aws_workspaces_ip_group association with directory

### ISSUE THREAD

**Issue by loopif** [hashicorp/terraform-provider-aws#14669]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This PR #10904  added the aws_workspaces_ip_group resource but it is useless since it cant' be applied to a directory: neither the directory resources like aws_workspaces_directory or aws_directory_service_directory has ip group argument nor there is such an association resource like aws_workspaces_ip_group_association.

### New or Affected Resource(s)

* aws_workspaces_ip_group

### References

*[ IP Access Control Groups for Your WorkSpaces](https://docs.aws.amazon.com/workspaces/latest/adminguide/amazon-workspaces-ip-access-control-groups.html)

**Comment by tedivm** [comment]
I really don't understand why this provider lets you create the groups but doesn't let you associate them. It's really frustrating that Workspaces aren't fully supported yet.
