### ISSUE TITLE
Improve aws_api_gateway_domain_name acceptance tests

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#14664]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The basic acceptance test cases should verify all fields have expected values, including that values expected to be empty are empty. For example, when using `EDGE` endpoints, `regional_domain_name` should be empty, and when using `REGIONAL` endpoints, `cloudfront_domain_name` should be empty.

Typically, uses of `resource.TestCheckResourceAttrSet()` should be avoided, and replaced with more specific tests. For example, `cloudfront_domain_name` should match `[a-z0-9]+.cloudfront.net` and `regional_domain_name` should use `testAccMatchResourceAttrRegionalHostname()` with the pattern `d-[a-z0-9]+`.

Rather than using environment variables to specify existing certificates, in many cases creating a certificate in the test using DNS validation can be used so that the test can be run consistently.

### Affected Resource

* aws_api_gateway_domain_name

**Comment by ewbankkit** [comment]
This could be addressed while adding support for mutual TLS authentication options: https://github.com/terraform-providers/terraform-provider-aws/issues/15220.
