### ISSUE TITLE
AWS Site-to-Site VPN support for IPv6

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#14698]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> AWS Site-to-Site VPN now supports IPv6 traffic for VPN connections to AWS Transit Gateway.

### New or Affected Resource(s)

* [`aws_vpn_connection`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpn_connection)

### Potential Terraform Configuration

```hcl
resource "aws_vpn_connection" "example" {
  transit_gateway_id  = aws_ec2_transit_gateway.example.id

  tunnel1_inside_ipv6_cidr = "fd00::/126"
  tunnel2_inside_ipv6_cidr = "fdff:ffff:ffff:ffff:ffff:ffff:ffff:fff0/126"
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/08/aws-site-to-site-vpn-supports-ipv6-traffic/).
[User Guide](https://docs.aws.amazon.com/vpn/latest/s2svpn/how_it_works.html#ipv4-ipv6).

**Comment by MRinalducci** [comment]
Could be easily added to PR https://github.com/terraform-providers/terraform-provider-aws/pull/14740, but we need to write a validate function to constraints a size /126 CIDR block from the local fd00::/8 range like for IPV4 inside CIDR:
```
func validateVpnConnectionTunnelInsideCIDR() schema.SchemaValidateFunc {
	disallowedCidrs := []string{
		"169.254.0.0/30",
		"169.254.1.0/30",
		"169.254.2.0/30",
		"169.254.3.0/30",
		"169.254.4.0/30",
		"169.254.5.0/30",
		"169.254.169.252/30",
	}

	return validation.All(
		validation.IsCIDRNetwork(30, 30),
		validation.StringMatch(regexp.MustCompile(`^169\.254\.`), "must be within 169.254.0.0/16"),
		validation.StringNotInSlice(disallowedCidrs, false),
	)
}
```

**Comment by MRinalducci** [comment]
Hi @ewbankkit,
I added support for your request in that PR #14740.

**Comment by bill-rich** [comment]
Added in #14740
