### ISSUE TITLE
aws_transfer_server doesn’t support security policies

### ISSUE THREAD

**Issue by Hanse00** [hashicorp/terraform-provider-aws#14694]
First off, my apologies if this is a duplicate issue, or if I’m wrong and I somehow missed it.

As far as I can tell, the aws_transfer_server resource does not support specifying a Security Policy.

The [AWS provider docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_server) make no mention of security policies, whilst the AWS console requires you to select one of the (at time of writing) three options, as documented in the [AWS docs](https://docs.aws.amazon.com/transfer/latest/userguide/security-policies.html).

**Comment by robbiet480** [comment]
Dug in for a moment on this... the AWS Go SDK does support passing the SecurityPolicyName, so this is purely a limitation of the Terraform provider.

**Comment by vaxxor** [comment]
this needs to be seen
