### ISSUE TITLE
Unable to update tags of ECS service with code deploy

### ISSUE THREAD

**Issue by hitsumabushi** [hashicorp/terraform-provider-aws#14711]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

* Terraform v0.12.29
* aws provider v2.69.0

### Affected Resource(s)

* aws_ecs_service

### Terraform Configuration Files

https://gist.github.com/hitsumabushi/404567895e2336e9f6a733a6388249ea#file-main-tf
At first, run terraform apply with this file, and edit local.tags variable, adding tag or delete tag. After that, run terraform apply again.
No changes except for aws ecs service tags.

### Debug Output

https://gist.github.com/hitsumabushi/404567895e2336e9f6a733a6388249ea#file-log
(some information masked)

### Expected Behavior

succeed to run terraform apply and aws ecs service tags are updated.

### Actual Behavior

failed to apply terraform, and terraform outputs following error.

```
Error: Error updating ECS Service (arn:aws:ecs:us-west-2:XXXXXXXXXXX:service/sample_cluster/ecs-service-terraform-tagging-test): InvalidParameterException: Unable to update network parameters on services with a CODE_DEPLOY deployment controller. Use AWS CodeDeploy to trigger a new deployment.
```

### Steps to Reproduce

1. `terraform apply`
2. edit tags variable
3. `terraform apply`

### References

* Related to #13658

**Comment by hitsumabushi** [comment]
No, it is not.
In my case, terraform should not call UpdateService API, because no difference except for tags in plan result.
And, for assigning tags, we use [TagResource](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_TagResource.html) API.

I think this is a problem related with TypeSet. `security_groups`, `subnets` are declared as TypeSet.
TypeSet are includes func values.
* https://github.com/hashicorp/terraform-plugin-sdk/blob/master/helper/schema/set.go#L48
* https://github.com/hashicorp/terraform-plugin-sdk/blob/master/helper/schema/schema.go#L301

And, these values are compared by using [reflect.DeepEqual](https://golang.org/pkg/reflect/#DeepEqual) in apply phases.
> Func values are deeply equal if both are nil; otherwise they are not deeply equal. 

If we change TypeSet to TypeList (TypeList is more simple type than TypeSet), it seems to work well. But, I can't pass acceptance tests yet.
https://github.com/hitsumabushi/terraform-provider-aws/commit/eb4cc683731fe374053804adadb31c043bcba891

**Comment by netzere** [comment]
@hitsumabushi You're right.
I'm getting the same error when trying to update the number of replicas for my ECS service

**Comment by marcovergueira** [comment]
@hitsumabushi I'm facing exactly the same issue using Terraform v0.12.29 and AWS provider v2.70.0, when I try to update tags on a existent resource, something to notice is this issue don't happen if we create new resources only change existent ones, the workaround I'm working on is running the aws-cli in order to change the tags before run Terraform, that way when Terraform look for the diff in the deployed resources against the Terraform code, will identify no changes to apply and later we can remove the workaround.

This workaround proofs one thing, change the tags are possible with no impact or any error from AWS, so I assume this is an error related with the AWS provider, this seems to not handling correctly this particular change.

![image](https://user-images.githubusercontent.com/929114/93212161-20f0f100-f75a-11ea-8a49-1494c07f715d.png)

**Comment by wadeyw** [comment]
Team, any finding for this issue? Looked around seems this issue last for few years and no proper solution yet, this seriously blocked using Terraform with blue green deployment feature of ECS

**Comment by jpinsolle-betclic** [comment]
Hello, any news ?

I'm facing exactly the same issue.

**Comment by wadeyw** [comment]
> Hello, any news ?
> 
> I'm facing exactly the same issue.

My Current solution is
In  resource "aws_ecs_service" add propagate_tags and enable_ecs_managed_tags
`propagate_tags  = "TASK_DEFINITION
enable_ecs_managed_tags = true`

propagate_tags: Specifies whether to propagate the tags from the task definition or the service to the tasks. The valid values are SERVICE and TASK_DEFINITION.

enable_ecs_managed_tags: Specifies whether to enable Amazon ECS managed tags for the tasks within the service.

At least you can cascade some environment tags or identifier to the task level

**Comment by larstobi** [comment]
Re:  @wadeyw's solution, this forces recreate of the service. 

For existing services, I find @marcovergueira's workaround to be more practical.
