### ISSUE TITLE
GitHub Organization Transfer of Repository from terraform-providers to hashicorp

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#14715]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Since the [launch of Terraform 0.10](https://www.hashicorp.com/blog/hashicorp-terraform-0-10), the broad ecosystem of HashiCorp, third-party, and verified community Terraform Providers have resided under the single [`terraform-providers` GitHub Organization](https://github.com/terraform-providers/). With the recent [addition of providers to the Terraform Registry](https://www.hashicorp.com/blog/providers-in-the-hashicorp-terraform-registry-now-live) and [additional support in Terraform 0.13 for provider source](https://www.hashicorp.com/blog/automatic-installation-of-third-party-providers-with-terraform-0-13), the source code location of each provider can now be transferred to their associated maintainers within GitHub.

To align with other HashiCorp maintained Terraform Providers, in the near future, this GitHub repository will be migrated from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws.

#### Common Questions

_When will this occur?_

This is currently scheduled to occur first week of November 2020.

_Do I need to do anything as a practitioner?_

No practitioner action is necessary. The Terraform AWS Provider will still automatically download correctly and the provider documentation links will remain the same. Most GitHub functionality such as links to issues and pull requests will automatically redirect to the new location and GitHub notifications will continue to send the same as before.

_Do I need to do anything as a developer?_

No developer action is anticipated. Most GitHub functionality such as Git URLs and links to files will automatically redirect to the new location and GitHub notifications will continue to send the same as before. Go import paths pointing to `github.com/terraform-providers/terraform-provider-aws` can remain for now.

_Will the HashiCorp Contributor License Agreement (CLA) be required?_

Most code projects in the `hashicorp` GitHub Organization require the HashiCorp CLA to be signed for contributions. After the repository transfer, the CLA functionality will be disabled for this repository. There are no current plans to enable the CLA requirement, however this may change in the future after the transfer and will be broadly announced.

**Comment by breathingdust** [comment]
Completed November 2nd, 2020.
