### ISSUE TITLE
r/aws_lambda_event_source_mapping: Creation doesn't wait for state to become 'Enabled' or 'Disabled'

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#14748]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* [`aws_lambda_event_source_mapping`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping)

### Terraform Configuration Files

```hcl
resource "aws_lambda_event_source_mapping" "example" {
  event_source_arn  = aws_kinesis_stream.example.arn
  function_name     = aws_lambda_function.example.arn
  starting_position = "LATEST"
}
```

When the `aws_lambda_event_source_mapping` resource is created Terraform does not wait for the underlying AWS resource's state to reach `Enabled` (or `Disabled`) state before returning. The usual value of the `state` attribute immediately after creation is `Creating`.

**Comment by shuheiktgw** [comment]
I'm working on this issue! 👍

**Comment by shuheiktgw** [comment]
PRed: https://github.com/terraform-providers/terraform-provider-aws/pull/14765
