### ISSUE TITLE
r/aws_servicequotas_service_quota Check AWS default quota if GetServiceQuota returns empty list

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#14774]
Currently, if a Service Quota is not applied, [`GetServiceQuota` errors out.](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_servicequotas_service_quota.go#L84-L92) In that case, check the default serrvice quota ([GetAWSDefaultServiceQuota](https://docs.aws.amazon.com/goto/WebAPI/service-quotas-2019-06-24/GetAWSDefaultServiceQuota)) and compare against that

```
aws service-quotas  get-service-quota --service-code lambda --quota-code <code>
vs
aws service-quotas  get-aws-default-service-quota --service-code lambda --quota-code <code>
```

### Affected Resource(s)

* r/aws_servicequotas_service_quota

### Terraform Configuration Files

```hcl
variable "aws_quotas" {
  description = "List of Service Quotas"
  type        = list(map(string))
  default     = []
}

resource "aws_servicequotas_service_quota" "quotas" {
  count = length(var.aws_quotas)

  quota_code   = var.aws_quotas[count.index]["QuotaCode"]
  service_code = var.aws_quotas[count.index]["ServiceCode"]
  value        = var.aws_quotas[count.index]["Value"]
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by gdavison** [comment]
I can not reproduce this error. If you have encountered this error, please [create a new Issue](https://github.com/hashicorp/terraform-provider-aws/issues/new/choose) and include both the Terraform configuration and the output, as requested in the Issue template.
