### ISSUE TITLE
Terraform is unable to read role credentials from SDK config files for Milan region

### ISSUE THREAD

**Issue by warp3r** [hashicorp/terraform-provider-aws#14772]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.29
+ provider.aws v2.70.0
+ provider.null v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

* the provider itself

### Terraform Configuration Files

```hcl


provider "aws" {
  alias  = "eu-south-1"
  profile = var.aws_profile
  region = "eu-south-1"
  version = "~> 2.50"
}

module "aws-vpc-10" {
  source  = "./modules/xxx-vpc"
  vpc_name  = "milan"
  vpc_cidr_block  = "10.110.13.0/24"
  vpc_id = ""
  subnet_priv_name = var.subnet_eu_milan.priv_name
  subnet_pub_name = var.subnet_eu_milan.pub_name
  subnet_priv_cidr_block = var.subnet_eu_milan.priv_cidr_block
  subnet_pub_cidr_block = var.subnet_eu_milan.pub_cidr_block
  providers = {
    aws = aws.eu-south-1
  }
}

variable "aws_profile" {}
variable "region" {}

variable "subnet_eu_milan" {
  type = map
  default = {
    priv_name = "xxx-milan-private-1a"
    pub_name = "xxx-milan-public-1a"
    priv_cidr_block = "10.110.13.0/25"
    pub_cidr_block = "10.110.13.128/25"
  }
}
```

### Debug Output

https://gist.github.com/warp3r/3b27aedbc72c8c41e25989c6e9fd2d95

### Panic Output

no panic

### Expected Behavior

Terraform should be able to read the profile with access key, secret and token and use it.

### Actual Behavior

Terraform says "No valid credential sources found for AWS Provider"

This only happens for Milan region. The rest of the regions (including Hong Kong or Dubai are ok)

### Steps to Reproduce

1. `terraform plan -var-file=xxx-prod.tfvars -out=prod.plan`

### Important Factoids

If we change the provider section with the following code (indicating explicit secret and key) it works

```hcl
provider "aws" {
  alias  = "eu-south-1"
  access_key = "xxxxxx"
  secret_key = "yyyyyy"
  region = "eu-south-1"
  version = "~> 2.50"
}
```

### References

N/A

**Comment by s4ntos** [comment]
Are there any news on this, this may be related to the fact that the new regions are using mandatory aws cli v2.

https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-sts-regional-endpoint

**Comment by warp3r** [comment]
I confirm that enabling the V2Token fixed this. It has to do with Milan not having STS token enabled by default.

See https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html

Maybe an update in the documentation of the provider should indicate that's the case!



cheers and thanks @s4ntos
