### ISSUE TITLE
Elastic Beanstalk setting is changed every time aws:elbv2:listener:80 / ListenerEnabled

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#14780]
_This issue was originally opened by @njlr as hashicorp/terraform#25959. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    
### Terraform Version

```
$ terraform version
Terraform v0.12.15
+ provider.aws v2.65.0
+ provider.http v1.2.0

```

### Terraform Configuration Files

```terraform
resource "aws_elastic_beanstalk_environment" "my_eb" {

...

  setting {
    namespace = "aws:elbv2:listener:80"
    name      = "ListenerEnabled"
    value     = false
    resource  = ""
  }
}
```

### Debug Output

```
...

 + setting {
          + name      = "ListenerEnabled"
          + namespace = "aws:elbv2:listener:80"
          + value     = "false"
 +      }

...
```

### Crash Output

N/A

### Expected Behavior

The setting should be applied only once

### Actual Behavior

The setting is applied as a change on every subsequent `apply`

### Steps to Reproduce

```
terraform apply

# setting is applied once

terraform apply

# setting is applied again!
```

### Additional Context

Running on Ubuntu machine with state in AWS Dynamo DB

### References

None

**Comment by njlr** [comment]
Probably related https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/issues/43

**Comment by molleafauss** [comment]
I seems to have a similar issue with the standard elbs; the below setting keeps getting applied every time I do an `apply`
```
  setting {
    namespace = "aws:elb:listener"
    name      = "ListenerEnabled"
    value     = "false"
    resource  = ""
  }
```

**Comment by molleafauss** [comment]
I also made a further test, created an EB without the above `ListenerEnabled: false` setting.
The EB gets created with the listener on port 80 open (and added to the managed SG). 
*manually* disabling the listener from the EB console, doesn't come up as a diff in terraform that should be rectified.

**Comment by posobin** [comment]
Experiencing the same issue.
