### ISSUE TITLE
StepScaling bounds are not correctly created

### ISSUE THREAD

**Issue by ay0o** [hashicorp/terraform-provider-aws#14799]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.26
+ provider.aws v3.2.0
+ provider.random v2.3.0

### Affected Resource(s)

* aws_autoscaling_policy

### Terraform Configuration Files

```hcl
resource "aws_autoscaling_policy" "scale_out" {
  name                    = "scale-out"
  autoscaling_group_name  = aws_autoscaling_group.workers.name
  policy_type             = "StepScaling"
  adjustment_type         = "PercentChangeInCapacity"
  metric_aggregation_type = "Average"
  min_adjustment_magnitude = 2
  estimated_instance_warmup = 60

  step_adjustment {
    scaling_adjustment          = 0
    metric_interval_upper_bound = 60
  }

  step_adjustment {
    scaling_adjustment          = 15
    metric_interval_lower_bound = 60
    metric_interval_upper_bound = 80
  }

  step_adjustment {
    scaling_adjustment          = 30
    metric_interval_lower_bound = 80
  }
}
```

### Expected Behavior

A policy should have been created reading:

```
Take the action:
Add 0 percent of group when -infinity <= CPUUtilization < 60
Add 15 percent of group when 60 <= CPUUtilization < 80
Add 30 percent of group when 80 <= CPUUtilization < +infinity
Add capacity units in increments of at least 2 capacity units
```

### Actual Behavior

The actual policy that is being created:
```
Take the action:
Add 0 percent of group when +infinity <= CPUUtilization < 120
Add 15 percent of group when 120 <= CPUUtilization < 140
Add 30 percent of group when 140 <= CPUUtilization < +infinity
Add capacity units in increments of at least 2 capacity units
```

### Other info
The values are correct during `terraform plan`, so don't know what might be causing the incorrect ones after the `apply`

```
  # aws_autoscaling_policy.scale_out will be created
  + resource "aws_autoscaling_policy" "scale_out" {
      + adjustment_type           = "PercentChangeInCapacity"
      + arn                       = (known after apply)
      + autoscaling_group_name    = "workers"
      + estimated_instance_warmup = 60
      + id                        = (known after apply)
      + metric_aggregation_type   = "Average"
      + min_adjustment_magnitude  = 2
      + name                      = "scale-out"
      + policy_type               = "StepScaling"

      + step_adjustment {
          + metric_interval_upper_bound = "60"
          + scaling_adjustment          = 0
        }
      + step_adjustment {
          + metric_interval_lower_bound = "60"
          + metric_interval_upper_bound = "80"
          + scaling_adjustment          = 15
        }
      + step_adjustment {
          + metric_interval_lower_bound = "80"
          + scaling_adjustment          = 30
        }
    }
```

**Comment by ay0o** [comment]
It was a random glitch. Destroyed all the infrastructure and started over, and now the correct values are displayed.

**Comment by ay0o** [comment]
The problem is related to configure an alarm using the policy.

So, if only the policy is created, the values are correct.

However, if the policy is linked to an alarm like:

```hcl
 resource "aws_cloudwatch_metric_alarm" "scale_out" {
   alarm_name          = "workers-scale-out"
   comparison_operator = "GreaterThanThreshold"
   datapoints_to_alarm = "3"
   evaluation_periods  = "3"
   metric_name         = "CPUUtilization"
   namespace           = "AWS/EC2"
   period              = "60"
   statistic           = "Average"
   threshold           = "60"

   dimensions = {
     AutoScalingGroupName = aws_autoscaling_group.workers.name
   }

   alarm_description = "Trigger a scaling out event when the average CPU > 60% for the past three minutes"
   alarm_actions     = [aws_autoscaling_policy.scale_out.arn]
 }
```

The values are changed to the wrong ones.

**Comment by ewbankkit** [comment]
@ay0o Thanks for raising this issue.
Digging in to this it seems that it's a quirk (bug?) in the way that the AWS Console displays the actions when the Auto Scaling policy is associated with a CloudWatch Metric Alarm.
With you configuration, in the AWS Console I see the actions displayed as you describe:

![Annotation 2020-08-24 112224](https://user-images.githubusercontent.com/2404182/91063706-52174f00-e5fc-11ea-921a-65591a884654.png)

but through the AWS API I see the values as specified in the Terraform configuration:

```console
$ aws autoscaling describe-policies
{
    "ScalingPolicies": [
        {
            "AutoScalingGroupName": "test-001",
            "PolicyName": "scale-out",
            "PolicyARN": "arn:aws:autoscaling:us-west-2:111111111111:scalingPolicy:03582a02-8aba-4ec2-97f9-5f9106af47d9:autoScalingGroupName/test-001:policyName/scale-out",
            "PolicyType": "StepScaling",
            "AdjustmentType": "PercentChangeInCapacity",
            "MinAdjustmentStep": 2,
            "MinAdjustmentMagnitude": 2,
            "StepAdjustments": [
                {
                    "MetricIntervalUpperBound": 60.0,
                    "ScalingAdjustment": 0
                },
                {
                    "MetricIntervalLowerBound": 60.0,
                    "MetricIntervalUpperBound": 80.0,
                    "ScalingAdjustment": 15
                },
                {
                    "MetricIntervalLowerBound": 80.0,
                    "ScalingAdjustment": 30
                }
            ],
            "MetricAggregationType": "Average",
            "EstimatedInstanceWarmup": 60,
            "Alarms": [
                {
                    "AlarmName": "workers-scale-out",
                    "AlarmARN": "arn:aws:cloudwatch:us-west-2:111111111111:alarm:workers-scale-out"
                }
            ],
            "Enabled": true
        }
    ]
}
```

And Terraform shows no drift when I run `terraform plan`.
I suggest contacting AWS Support to raise this as an issue.

**Comment by ay0o** [comment]
I don't think it's a visual bug in AWS for these two reasons:

- If you create the policy using the AWS Console and associate the CloudWatch alarm to it as part of the process, the values are correctly displayed.
- Even though the AWS CLI returns the correct values, whatever is under the hood handling the alarms is using the wrong ones. 

Regarding the second point, that's how I noticed about this bug. I had a simple and controlled test environment. Three instances, 6 CPUs overall. Raising the CPU to 100% on four of them should trigger the alarm, but it wasn't. When I found out about the incorrect values, replace them using the AWS Console, and now everything is working.

**Comment by ewbankkit** [comment]
@ay0o On closer inspection, it seems that you are correct in that this is not a bug, either in the Console or in the triggering of the alarm, but is the (to my mind confusingly) documented behaviour. The [Step Adjustment bounds](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_StepAdjustment.html) are bounds for the **difference** between the alarm threshold and the CloudWatch metric but the Console displays the bounds for the **absolute** values of the metric (which is what the alarm triggers on).
Hence adjustment bounds of 60 and 80 in the API (and the `aws_autoscaling_policy` resource) with an alarm metric threshold of 60 leads to the displayed bounds of 120 and 140.
There is a worked example in the service's [User Guide](https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-scaling-simple-step.html#policy-creating-aws-cli) but the provider's documentation could be made clearer - What do you think?

**Comment by ay0o** [comment]
I had read those docs, but guess I failed to notice this:

> You specify the upper and lower bounds relative to the breach threshold

That's the key. I was trying to configure the full range, from 0 to 100%, but instead I should have started from 60% which was my threshold.

I'm going to open a PR to make the documentation clearer.
