### ISSUE TITLE
attaching different Security Groups to different EC2s based on count

### ISSUE THREAD

**Issue by kamlendra** [hashicorp/terraform-provider-aws#14806]
Requirement:- I have multiple group(say 2 groups) of EC2s where each group contain 2 EC2. and I have to attach different SG to each group. Example:- Group1 contains :- EC2-1, EC2-2 and need to attach SG1 Group2 contains :- EC2-3, EC2-4 and need to attach SG2

**I don't want to write separate resource "aws_instance"

SecurityGroup:

```hcl
resource "aws_security_group" "security_group" {
  name        = "${local.account}"
  vpc_id      = local.vpc_id
}
resource "aws_security_group" "security_group1" {
  name        = "${local.account}1"
  vpc_id      = local.vpc_id
}
EC2_instance:

data "aws_security_groups" "data_security_group" {
    filter {
    name   = "group-name"
    values =  ["${local.account}", "${local.account}1"]
}
}
resource "aws_instance" "ec2_instance" {
  count                   = var.ec2_instance_count
security_groups         = [element(data.aws_security_groups.data_security_group.*.id, count.index)]
}
```

Error: Error launching source instance: InvalidGroup.NotFound: The security group 'terraform-2020082 4151444795600000001' does not exist in VPC 'vpc-ghhje85abcy' status code: 400, request id: 9260fd88-a03a-4c46-b67c-3287594cdab5

on main.tf line 68, in resource "aws_instance" "ec2_instance": 68: resource "aws_instance" "ec2_instance" {

Note: I am using data "aws_security_groups" instead of data "aws_security_group". If i use the later one, I know I will be able to get only one SG in the data resource and it throws me an error :multiple Security Groups matched; from which i kind of moved ahead by using data "aws_security_groups" and this error get vanished. but the latest error I m facing is : InvalidGroup.NotFound as mentioned above.

**Comment by ljluestc** [comment]
```
# Define the security groups
resource "aws_security_group" "security_group_1" {
  name        = "security-group-1"
  vpc_id      = local.vpc_id
}

resource "aws_security_group" "security_group_2" {
  name        = "security-group-2"
  vpc_id      = local.vpc_id
}

# Create the EC2 instances
resource "aws_instance" "ec2_group_1" {
  count             = 2
  ami               = "your-ami-id"  # Replace with your desired AMI ID
  instance_type     = "t2.micro"     # Replace with your desired instance type
  subnet_id         = "your-subnet-id"  # Replace with your desired subnet ID
  security_groups   = [aws_security_group.security_group_1.id]
}

resource "aws_instance" "ec2_group_2" {
  count             = 2
  ami               = "your-ami-id"  # Replace with your desired AMI ID
  instance_type     = "t2.micro"     # Replace with your desired instance type
  subnet_id         = "your-subnet-id"  # Replace with your desired subnet ID
  security_groups   = [aws_security_group.security_group_2.id]
}
```

**Comment by justinretzolk** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. To maintain that, we ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). With that in mind, and given that it looks like an answer has already been given, I'm going to close this issue.
