### ISSUE TITLE
aws_spot_instance_request bug

### ISSUE THREAD

**Issue by dvir-frey** [hashicorp/terraform-provider-aws#14816]
we are having problem since the last version 
"[0m[1maws_spot_instance_request.jenkins_agent[1]: Creating...[0m[0m
[0m[1maws_spot_instance_request.jenkins_agent[0]: Creating...[0m[0m
[0m[1maws_spot_instance_request.jenkins_agent[0]: Creation complete after 1s [id=sir-r49gd8dg][0m[0m
[31m
[1m[31mError: [0m[0m[1mProvider produced inconsistent result after apply[0m

[0mWhen applying changes to aws_spot_instance_request.jenkins_agent[1], provider
"aws" produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker."

**Comment by breathingdust** [comment]
Hi @dvir-frey 👋 I realize it has been some time since you reported this. This issue report does not have enough information for us or the community to help. If this is still an issue for you can you resubmit filling in the provided issue template? Thank you!
