### ISSUE TITLE
Document parameter types in modules

### ISSUE THREAD

**Issue by jlosito** [hashicorp/terraform-provider-aws#14836]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* All of them

### Expected Behavior

The provider's documentation on the registry does not display the parameter types for each of its resources as shown in the following [link](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_identity_pool#provider_name). 

### Actual Behavior

It would be nice if the documentation had the type of the parameter in addition to whatever is currently there.

### References

Below I've listed some providers which I believe do a good job at displaying the respective parameter types within each of the provider's resources.

* https://registry.terraform.io/providers/paultyng/unifi/latest/docs/resources/port_forward
* https://registry.terraform.io/providers/hashicorp/ad/latest/docs/resources/computer

**Comment by bflad** [comment]
Hi @jlosito 👋  Thank you for submitting this. To add some context here, those smaller providers are experimenting with a Terraform Provider documentation generation tool, which this project will likely also implement in the medium to long-term future. Given other priorities we have on this maintainer team at the current time, we likely will not want to inconsistently implement the type information in our resource documentation or spend the massive effort to bulk update/review everything all at once and instead we will want to focus on migrating the documentation into the resource schema `Description` fields when the time comes. I'm going to leave this issue open for long term tracking although we really do not have any timeframe on this implementation.
