### ISSUE TITLE
aws_cognito_user_pool_client missing attributes

### ISSUE THREAD

**Issue by pll** [hashicorp/terraform-provider-aws#14840]
Based on the current documentation for the AWS CLI for creating a Cognito User Pool Client, the following settings/attributes are missing from the Terraform documentation (and I assume from the code itself as well):

--access-token-validity
--id-token-validity 

Reference: https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/create-user-pool-client.html

**Comment by lablood** [comment]
Can anyone help on this?

**Comment by danielwhite** [comment]
Does #14935 address this issue?

**Comment by DrFaust92** [comment]
Closed by #14935
