### ISSUE TITLE
ID missing on Resource aws_api_gateway_vpc_link import example

### ISSUE THREAD

**Issue by brodriguesneto** [hashicorp/terraform-provider-aws#14856]
Hi guys.

I've noticed that in the given example of the[ aws_api_gateway_vpc_link](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_vpc_link#import) import it miss the `id`:

`$ terraform import aws_api_gateway_vpc_link.example `

Should be:

`$ terraform import aws_api_gateway_vpc_link.example  abcdef`

Regards.

**Comment by breathingdust** [comment]
Looks like this documentation issue has been resolved in another PR. Closing
