### ISSUE TITLE
aws_rds_cluster applies invalid scaling_configuration.min_capacity value for Aurora Serverless with PostgreSQL

### ISSUE THREAD

**Issue by kinghuang** [hashicorp/terraform-provider-aws#14855]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.0
hashicorp/aws v3.3.0
```

### Affected Resource(s)

* aws_rds_cluster

### Terraform Configuration Files

```hcl
resource "aws_rds_cluster" "this" {
  cluster_identifier = "example"

  engine         = "aurora-postgresql"
  engine_version = "10.7"
  engine_mode    = "serverless"
  
  master_username = "master"
  master_password = "password"
}
```

Note that a `scaling_configuration` block is not provided.

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

If I create a RDS Aurora Serverless cluster using a [aws_rds_cluster](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster) resource and *don't* supply a [scaling_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#scaling_configuration) block, the cluster is created with default `min_capacity` and `max_capacity` values. For an `aurora-postgresql` engine, these are `2` and `16`, respectively.

After the cluster is created, if I run apply again, I expect no changes to the `aws_rds_cluster` resource.

### Actual Behavior

If I run apply again with no configuration changes, Terraform attempts to change the `min_capacity` to `1`, which is an invalid value for `aurora-postgresql`.

```
  # module.rds.aws_rds_cluster.this will be updated in-place
  ~ resource "aws_rds_cluster" "this" {
        apply_immediately                   = false
        arn                                 = "arn:aws:rds:us-west-2:XXXXXXXXXXXX:cluster:example"
        …
        engine                              = "aurora-postgresql"
        engine_mode                         = "serverless"
        engine_version                      = "10.7"
        …
      ~ scaling_configuration {
            auto_pause               = true
            max_capacity             = 16
          ~ min_capacity             = 2 -> 1
            seconds_until_auto_pause = 300
            timeout_action           = "RollbackCapacityChange"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.rds.aws_rds_cluster.this: Modifying... [id=sa-dagster-staging]

Error: Failed to modify RDS Cluster (sa-dagster-staging): InvalidParameterValue: Capacity value 1 is not valid. The valid scaling range for this cluster is 2 to 384. To change the clusters scaling range use the ModifyDBCluster call.
	status code: 400, request id: 3a59dea1-6eb5-48ed-a57e-01143ce13d2f
```

### Steps to Reproduce

1. Using the config above as a reference, create an Aurora Serverless with PostgreSQL cluster.
2. After the cluster is created, apply again without making any changes to the configuration.

### Important Factoids

The documentation for aws_rds_cluster says `min_capacity` defaults to `1`. However, the set of possible values is dependent on the engine. For `aurora-mysql`, `1` is valid. For `aurora-postgresql`, `2` is the smallest valid value for `min_capacity`.

**Comment by anGie44** [comment]
Related to changes here: https://github.com/terraform-providers/terraform-provider-aws/pull/14268

**Comment by alansikora** [comment]
This actually has cost impact, I'm considering using terraform for several databases (over 100), but they need to able to scale down to zero.

Any updates on this?
