### ISSUE TITLE
aws_route53_zone name_servers attribute is inconsistent (returns trailing "." for private zones)

### ISSUE THREAD

**Issue by dthvt** [hashicorp/terraform-provider-aws#14863]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v0.12.29
+ provider.aws v3.3.0

Your version of Terraform is out of date! The latest version
is 0.13.1. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* aws_route53_zone

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
provider "aws" {
  profile = "ops"
  region  = "us-east-1"
}

resource "aws_route53_zone" "public" {
  name = "blah.kickidle.com"
}

resource "aws_vpc" "test" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_route53_zone" "private" {
  name = "blah.example.com"
  vpc {
    vpc_id = aws_vpc.test.id
  }
}

output "public" {
  value = aws_route53_zone.public
}

output "private" {
  value = aws_route53_zone.private
}

```

### Expected Behavior

name_servers array will behave consistently regardless of whether zone is private or not (i.e. name_servers strings will always have a trailing "." or never have a trailing ".").

### Actual Behavior

```
$ terraform apply
aws_route53_zone.public: Refreshing state... [id=Z004444311TEDB2NIBNX6]
aws_vpc.test: Refreshing state... [id=vpc-0ba7f14893707cf0a]
aws_route53_zone.private: Refreshing state... [id=Z05774952INA4M7AHF83S]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

private = {
  "comment" = "Managed by Terraform"
  "delegation_set_id" = ""
  "force_destroy" = false
  "id" = "Z05774952INA4M7AHF83S"
  "name" = "blah.example.com"
  "name_servers" = [
    "ns-0.awsdns-00.com.",
    "ns-1024.awsdns-00.org.",
    "ns-1536.awsdns-00.co.uk.",
    "ns-512.awsdns-00.net.",
  ]
  "tags" = {}
  "vpc" = [
    {
      "vpc_id" = "vpc-0ba7f14893707cf0a"
      "vpc_region" = "us-east-1"
    },
  ]
  "zone_id" = "Z05774952INA4M7AHF83S"
}
public = {
  "comment" = "Managed by Terraform"
  "delegation_set_id" = ""
  "force_destroy" = false
  "id" = "Z004444311TEDB2NIBNX6"
  "name" = "blah.kickidle.com"
  "name_servers" = [
    "ns-1496.awsdns-59.org",
    "ns-1546.awsdns-01.co.uk",
    "ns-534.awsdns-02.net",
    "ns-71.awsdns-08.com",
  ]
  "tags" = {}
  "vpc" = []
  "zone_id" = "Z004444311TEDB2NIBNX6"
}
```

I note that in resource_aws_route53_zone.go the name servers are populated differently based on whether PrivateZone is true.  If it is false, they are populated from the DelegationSet.  If it is true they are populated by calling getNameServers().  Presumably these two methods are what introduces the inconsistency.

I regard this as a bug because it makes it difficult to rewrite the SOA record using aws_route53_zone.example.name_servers[0] in the SOA record string.  Currently, I must manually append or omit a period depending on whether the zone is private, which produces apparent inconsistencies in our code base.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by bflad** [comment]
As a workaround to ensure you never get the trailing period, you can use the following configuration reference:

```terraform
replace(aws_route53_zone.example.name_servers[0], "/\\.$/", "")
```

Otherwise to ensure the opposite of always getting the trailing period:

```terraform
"${replace(aws_route53_zone.example.name_servers[0], "/\\.$/", "")}."
```
