### ISSUE TITLE
Destroying a 'aws_api_gateway_authorizer' resource that is referenced by a 'aws_api_gateway_method' does not actually destroy it

### ISSUE THREAD

**Issue by EddyMaric** [hashicorp/terraform-provider-aws#14883]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform: 0.13.1
AWS Provider: 3.4.0

### Affected Resource(s)

* aws_api_gateway_authorizer
* aws_api_gateway_method

### Terraform Configuration Files

I only included the code which I was changing and was giving me issues.

BEFORE: (linking method to authorizer)
```hcl
resource "aws_api_gateway_method" "api_gateway_method" {
  rest_api_id   = aws_api_gateway_rest_api.api_gateway.id
  resource_id   = aws_api_gateway_resource.api_resource.id
  http_method   = "POST"
  authorization = "CUSTOM"
  authorizer_id = aws_api_gateway_authorizer.test_authorizer.id
}

resource "aws_api_gateway_authorizer" "test_authorizer" {
  name                   = "test_authorizer"
  rest_api_id            = aws_api_gateway_rest_api.api_gateway.id
  authorizer_uri         = aws_lambda_function.authorizer_lambda.invoke_arn
  authorizer_credentials = aws_iam_role.invocation_role.arn
  type                   = "REQUEST"
}
```

AFTER: (deleting authorizer and unlinking from method)
```hcl
resource "aws_api_gateway_method" "api_gateway_method" {
  rest_api_id   = aws_api_gateway_rest_api.api_gateway.id
  resource_id   = aws_api_gateway_resource.api_resource.id
  http_method   = "POST"
  authorization = "NONE"
}
```

### Panic Output

No panic was produced

### Expected Behavior

I expected the authorizer to be deleted. If I set the authorization to 'NONE' in the aws_api_gateway_method first, and then destroy the authorizer, then the authorizer is actually deleted.

### Actual Behavior

The aws_api_gateway_method resource got its authorization value set to 'NONE',  as expected, but the authorizer resource was not destroyed. This is a problem because the next time I try to create an authorizer with the same name, it will fail because this one already exists.

### Steps to Reproduce

1. Create an api gateway method that uses an authorizer
2. `terraform apply`
3. Remove the authorizer resource, and set authorization to 'NONE' for the method. Also delete the authorizer id field in the method.
4. `terraform apply`
5. Open the AWS management console and see that the authorizer was not destroyed, even though terraform says it will destroy it.

**Comment by EddyMaric** [comment]
Could this have anything to do with it:

https://github.com/terraform-providers/terraform-provider-aws/blob/eca69aed77eb2f3392d221ec4188d15a5eea6cca/aws/resource_aws_api_gateway_authorizer.go#L273

**Comment by vladb-metapack** [comment]
Hi, 

We're also experiencing exactly this and have a contingency running aws-cli scripts which destroy the authorizer manually. 

Is this in the pipeline to fix?

**Comment by joshstclair** [comment]
@EddyMaric did you ever land anywhere with this issue? I see that it's nearly been a year since you opened it. I think we might be running into the same issue. Essentially it's the same problem (resource being marked as destroyed but it's still sticking around). We're getting subsequent errors that the resource already exists when we deploy again. I haven't troubleshooted enough to know if it's the same exact cause but it seems like it. 

Our environment: 
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.52.0

**Comment by EddyMaric** [comment]
@joshstclair Hey, this was at the end of one of my internships and I didn’t get a chance to fix this and don’t have access to that code anymore.

**Comment by joshstclair** [comment]
No worries. I appreciate you responding after it's been so long. I ended up writing a script to just remove the old authorizer after terraform marks it as destroyed.

**Comment by vishwasjione** [comment]
Any update on this issue ? I am facing the same error.
