### ISSUE TITLE
Inconsistency between documentation and schema

### ISSUE THREAD

**Issue by sj158** [hashicorp/terraform-provider-aws#14887]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/aws v3.3.0
+ provider registry.terraform.io/hashicorp/template v2.1.2

### Affected Resource(s)

* aws_lb_listener

### Terraform Configuration Files

irrelevant

### Debug Output

"Error: List shorter than MinItems"

### Panic Output

irrelevant

### Expected Behavior

According to the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener#target_group) the `forward` block is required to have "One or more target groups block". 
Furthermore, it is even [stated](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener#forward) that it can have **exactly one** target block: "[..]you can specify only one target group using forward [...]"

### Actual Behavior

An error is thrown: "Error: List shorter than MinItems"

### Steps to Reproduce

AWS provider schema (fetched via `terraform providers schema -json`) defines `"min_items": 2` for the target_group block. This is inconsistent with the writings in the documentation and should be harmonized.

### References

**Comment by andrewpage** [comment]
I am also having this exact same issue. It seems that the schema is misconfigured.

**Comment by nicon89** [comment]
Same here.

**Comment by don-code** [comment]
If anybody is looking for workarounds, I can report that:

1. Terraform does not let you specify just one target group, and fails with `Error: List shorter than MinItems` (that is the bug).
2. Terraform lets you specify the same target group twice, but AWS fails it with a `ValidationError: You cannot specify the same target group multiple times in the target group list`.
3. Creating a second target group and registering targets with it, if you are deployed in ECS, has the nasty side effect of destroying and recreating your service and is a no-go for our production environment. Setting `create_before_destroy` here does not help due to naming restrictions.

I ended up settling on not using `aws_lb_listener_rule` at all, and instead using `null_resource` with a `local_exec` provisioner that creates the rule instead. This is not great, and it'd be much better if #15112 would merge.

```hcl
locals {
  create_my_listener_rule_command = <<EOF
    aws elbv2 create-rule \
      --listener-arn ${aws_alb_listener.my_listener.arn} \
      --priority 100 \
      --actions Type=forward,TargetGroupArn=${aws_alb_target_group.my_target_group.arn} \
      --conditions '[{"Field": "host-header","HostHeaderConfig":{"Values":["my-site.com"]}}]'
EOF
}

resource "null_resource" "create_my_listener_rule" {
  provisioner "local-exec" {
    command = local.create_my_listener_rule_command
  }

  triggers = {
    command = local.create_my_listener_rule_command
  }
}
```

**Comment by don-code** [comment]
I also found that the same behavior is true for `aws_lb_listener_rule`, which shares the schema with the default action in `aws_lb_listener`.

**Comment by chrisalbright** [comment]
If you have only one target group, it seem you can specify the target_group_arn directly, so you don't need any tricks to get it working. [aws_lb_listener.target_group_arn](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener#target_group_arn)

**Comment by horkko** [comment]
Hi same problem here. What if I want to also add `stickiness` attribute to my lb_listener? According to the documentation, `target_group` is required within the `forward` block which also set `stickiness` attribute ?
Below is the resource I'd like to set:
```
resource "aws_lb_listener" "web_app_websocket" {
  load_balancer_arn = aws_lb.web_elb.arn
  port              = 6001
  protocol          = "HTTP"
  default_action {
    type             = "forward"
    forward {
      target_group {
        arn = aws_lb_target_group.web_app_websocket.arn
      }
      stickiness {
        enabled = true
        # One day
        duration = 86400
      }
    }
  }
}
```

**Comment by horkko** [comment]
Hi,
I've found a workaround for my situation, I didn't create a `aws_lb_listener`, I've instead added a `stickiness` attribute in an `aws_lb_listner_rule` and attached it to an `aws_lb_target_group`

```
resource "aws_lb_listener_rule" "web_app_websocket_rule" {
  listener_arn = aws_lb_listener.web_app_https.arn
  action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.web_app_websocket.arn
  }
  condition {
    path_pattern {
      values = ["/socket.io"]
    }
  }
}
```
If it can help.
