### ISSUE TITLE
Create a Data Source Provider for the "Service Discovery" Resources

### ISSUE THREAD

**Issue by dgeorges** [hashicorp/terraform-provider-aws#14881]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Create a Data Source Provider for the [Service Discovery Resources](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/service_discovery_service):

- aws_service_discovery_http_namespace
- aws_service_discovery_private_dns_namespace
- aws_service_discovery_public_dns_namespace
- aws_service_discovery_service 

### New or Affected Resource(s)

The following Data Sources would be new. (The resources already exist)
- aws_service_discovery_http_namespace
- aws_service_discovery_private_dns_namespace
- aws_service_discovery_public_dns_namespace
- aws_service_discovery_service 

### Potential Terraform Configuration

Below is a potential use case for how the data sources could be used in a Terraform Configuration

```hcl

data "aws_service_discovery_private_dns_namespace" "example" {
  name        = "hoge.example.local"
  vpc         = aws_vpc.example.id
}

data "aws_service_discovery_service" "example" {
  name           = "service.name.example"
  vpc              = aws_vpc.example.id
  namespace = data.aws_service_discovery_private_dns_namespace.example.id
 }

...

resource "aws_ecs_service" "mongo" {
  ...
  service_registries = {
     registry_arn = data.aws_service_discovery_service.example.arn
     ....
  }
  ...
}
```

### References

None

**Comment by ewbankkit** [comment]
Related:

* https://github.com/terraform-providers/terraform-provider-aws/issues/6384

**Comment by jessicastenning** [comment]
Any update on when the data source for `aws_service_discovery_service` might become available?

**Comment by brittandeyoung** [comment]
I just opened a pull request that I believe takes care of the remaining requested data sources. Please let me know if there is something in this issue that is not covered by the two additional data sources in the Pull request:

`aws_service_discovery_service`
`aws_service_discovery_http_namespace`

**Comment by hhh-zest** [comment]
could we merge this pr it would be very helpful

**Comment by matt-land** [comment]
Just tried out the new providers in v4.21.0, and @brittandeyoung's PR closes the gap on missing functionality. However, I think the scope of this ticket left off some required functionality for instances.
 
I think this ticket should have had a data provider "aws_service_discovery_instance" that takes in the cloud map service id and returns the list of instances backing the service, and the instance's individual attributes. 

"aws_service_discovery_service" returns the service's attributes and tags as expected. But I have no way to get to the values I need on the instances.

I am using an http only service, so health checks, and dns_config do not apply.

**Comment by brittandeyoung** [comment]
@matt-land  If there is new functionality needed outside of scope of this issue, please open up a new issue for this functionality as mentioned by the github-action bot.
