### ISSUE TITLE
Unable to import existing Direct Connect Public VIF

### ISSUE THREAD

**Issue by robertsuarez-progenity** [hashicorp/terraform-provider-aws#14895]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.29
+ provider.aws v3.4.0

### Affected Resource(s)

aws_dx_public_virtual_interface

### Terraform Configuration Files

```hcl
resource "aws_dx_public_virtual_interface" "primary_public_vif" {
  address_family        = var.primary_public_vif_address_family
  bgp_asn               = var.primary_public_vif_bgp_asn
  connection_id         = aws_dx_connection.primary_dx_connection.id
  name                  = "${local.resource_name_prefix}-primary-public-vif"
  route_filter_prefixes = var.primary_public_vif_route_prefixes
  vlan                  = var.primary_public_vif_vlan
  tags                  = local.common_tags
  amazon_address        = var.primary_public_vif_amazon_address
  customer_address      = var.primary_public_vif_customer_address

  lifecycle {
    ignore_changes = [name]
  }
}
```

### Debug Output

2020-08-28T11:34:16.046-0700 [DEBUG] plugin.terraform-provider-aws_v3.4.0_x5: -----------------------------------------------------
2020-08-28T11:34:16.046-0700 [DEBUG] plugin.terraform-provider-aws_v3.4.0_x5: 2020/08/28 11:34:16 [DEBUG] [aws-sdk-go] {"__type":"DirectConnectClientException","message":"Invalid ARN(s) or resource not found"}
2020-08-28T11:34:16.046-0700 [DEBUG] plugin.terraform-provider-aws_v3.4.0_x5: 2020/08/28 11:34:16 [DEBUG] [aws-sdk-go] DEBUG: Validate Response directconnect/DescribeTags failed, attempt 0/25, error DirectConnectClientException: Invalid ARN(s) or resource not found
Error: error listing tags for Direct Connect public virtual interface (arn:aws:directconnect:us-east-1:xxxxxxxxx:dxvif/dxvif-xxxxxxxx): DirectConnectClientException: Invalid ARN(s) or resource not found
2020/08/28 11:34:16 [ERROR] <root>: eval: *terraform.EvalRefresh, err: error listing tags for Direct Connect public virtual interface (arn:aws:directconnect:us-east-1:xxxxxxx:dxvif/dxvif-xxxxx): DirectConnectClientException: Invalid ARN(s) or resource not found
2020/08/28 11:34:16 [ERROR] <root>: eval: *terraform.EvalSequence, err: error listing tags for Direct Connect public virtual interface (arn:aws:directconnect:us-east-1:xxxxxxxx:dxvif/dxvif-xxxxxxx): DirectConnectClientException: Invalid ARN(s) or resource not found

### Expected Behavior

Resource should have been imported

### Actual Behavior

Error about listing tags

### Steps to Reproduce

1. `terraform import aws_dx_public_virtual_interface.primary_public_vif dxvif-xxxxxxxx`

### References

* #0000

**Comment by jdelnano** [comment]
I thought I had this issue, but then I realized I was trying to import an interface that was in fact owned by a different AWS account than I was working in/viewing the interface in the UI. Not sure if that's your case as well, but thought I'd chime in.

**Comment by ewbankkit** [comment]
@robertsuarez-progenity Thanks for raising this issue.
This has been noticed again in #17833, and that issue has some more details. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
