### ISSUE TITLE
AWS Cognito: support token validity units

### ISSUE THREAD

**Issue by borfig** [hashicorp/terraform-provider-aws#14919]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Cognito allows configuring the token validity units of tokens for each User Pool Client.

### New or Affected Resource(s)

* aws_cognito_user_pool_client

### Potential Terraform Configuration
```hcl
// the Console user pool client
resource "aws_cognito_user_pool_client" "this" {
  // other attributes
 
  token_validity_units {
     access_token  = "hours"
     id_token      = "hours"
     refresh_token = "days"
     // the above are defaults; valid values are: seconds | minutes | hours | days
  }
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-cognito-user-pools-supports-customization-of-token-expiration/
* https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPoolClient.html#CognitoUserPools-CreateUserPoolClient-request-TokenValidityUnits
* https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserPoolClient.html#CognitoUserPools-UpdateUserPoolClient-request-TokenValidityUnits
* https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_TokenValidityUnitsType.html

**Comment by francotel** [comment]
I hope add this feature comming soon
