### ISSUE TITLE
route 53 resolver (aws_route53_resolver_endpoint) cannot accept dynamic number of subnets

### ISSUE THREAD

**Issue by queglay** [hashicorp/terraform-provider-aws#14913]
The aws_route53_resolver_endpoint cannot accept a dynamic number of subnet entries.  This means we have to bake the number of subnets into the whole deployment.  Subnets should be attached with an association, not like the provided example below:

```
resource "aws_route53_resolver_endpoint" "foo" {
  name      = "foo"
  direction = "INBOUND"

  security_group_ids = [
    aws_security_group.sg1.id,
    aws_security_group.sg2.id,
  ]

  ip_address {
    subnet_id = aws_subnet.sn1.id
  }

  ip_address {
    subnet_id = aws_subnet.sn2.id
    ip        = "10.0.64.4"
  }

  tags = {
    Environment = "Prod"
  }
}
```

**Comment by ewbankkit** [comment]
@queglay Thanks for raising this issue.
Can the Terraform 0.12+ [`for_each`](https://www.terraform.io/docs/configuration/resources.html#for_each-multiple-resource-instances-defined-by-a-map-or-set-of-strings) syntax help here?
A major reason that there is not a separate `aws_route53_resolver_endpoint_ip_address_association` resource is that at least one `ip_address` block must be specified when the `aws_route53_resolver_endpoint` resource is created and attempting to manage associations through both a required attribute of the `aws_route53_resolver_endpoint` and a number of `aws_route53_resolver_endpoint_ip_address_association` resources would be confusing to practitioners.
