### ISSUE TITLE
Docs: Data source aws_route_tables has non-planning example code.

### ISSUE THREAD

**Issue by jkodroff** [hashicorp/terraform-provider-aws#14948]
The docs for [data source `aws_routing_tables`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/route_tables) has non-planning code.  Code like example:

```hcl
data "aws_route_tables" "rts" {
  vpc_id = var.vpc_id

  filter {
    name   = "tag:kubernetes.io/kops/role"
    values = ["private*"]
  }
}

resource "aws_route" "r" {
  count                     = length(data.aws_route_tables.rts.ids)
  route_table_id            = data.aws_route_tables.rts.ids[count.index]
  destination_cidr_block    = "10.0.1.0/22"
  vpc_peering_connection_id = "pcx-0e9a7a9ecd137dc54"
}
```

Will result in an error like:

```
Error: Invalid index

  on ../modules/dx_gateway/main.tf line 33, in resource "aws_vpn_gateway_route_propagation" "vast":
  33:   route_table_id = data.aws_route_tables.vast.ids[count.index]
    |----------------
    | count.index is 1
    | data.aws_route_tables.vast.ids is set of string with 5 elements

This value does not have any indices.
```

Instead, I believe ` route_table_id = data.aws_route_tables.rts.ids[count.index]` should be `route_table_id = sort(data.aws_route_tables.rts.ids)[count.index]`.

PS - I don't seem to be able to find "Edit this page" or else I'd submit a PR directly.  Am I missing it, or has it since been removed?

**Comment by ewbankkit** [comment]
Related:

* https://github.com/terraform-providers/terraform-provider-aws/issues/10147

**Comment by gdavison** [comment]
Thanks for letting us know, @jkodroff. We don't currently have an "Edit this page" option on our new documentation site, just a link to create a GitHub issue. Adding the option to create a pull request would be a useful feature.

In the meantime, on the page https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/d/ec2_local_gateway_route_tables.html.markdown, there is a pencil icon that should allow you to make a PR.

**Comment by umeshkumhar** [comment]
Hey @gdavison @ewbankkit 
This is PR against this issue regarding documentation change. Please give a look.
Thanks
