### ISSUE TITLE
CloudFront: Support real-time logs

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#14944]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon CloudFront now supports real-time log delivery of CloudFront access logs.

### New or Affected Resource(s)

* `aws_cloudfront_realtime_log_config` (new)
* [`aws_cloudfront_distribution`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution) (updated)

### Potential Terraform Configuration

```hcl
resource "aws_cloudfront_realtime_log_config" "example" {
  endpoint {
    kinesis_stream_config {
      stream_arn = aws_kinesis_stream.example.arn
    }
  }
}

resource "aws_cloudfront_distribution" "example" {
  default_cache_behavior {
    realtime_log_config_arn = aws_cloudfront_realtime_log_config.example.arn
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/08/cloudfront-realtimelogs/).
[Developer Guide](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/real-time-logs.html).

Requires [AWS SDK v1.34.14](https://github.com/aws/aws-sdk-go/releases/tag/v1.34.14):

* https://github.com/terraform-providers/terraform-provider-aws/pull/14936

**Comment by mwarkentin** [comment]
Here was the resource definition I came up with in #14945 which included a few extra configurations:

```hcl
resource "aws_cloudfront_realtime_log_config" "test" {
  name = "test_realtime_log_config"
  sampling_rate = 50
  
  # It would be nice if there was some easy way to specify all fields, not sure how but the docs indicate its possible:
  # A list of the fields that are included in each real-time log record. You can choose to receive all of the available fields, or only the fields that you need to monitor and analyze performance. 
  fields = [
    "timestamp",
    "c-ip",
    "time-to-first-byte",
    "sc-status",
  ]

  # There can be multiple endpoints I think, could have 1 block per endpoint? Or would you have endpoints [ endpoint, endpoint, ...]?
  endpoint {
     stream_type = "Kinesis"
     kinesis_stream_config = {
       role_arn = aws_iam_role.test.arn
       stream_arn = aws_kinesis_data_stream.test.arn
     }
  }
}
```

**Comment by seanturner026** [comment]
Would it be possible to merge PR #14974? I see it's approved.
