### ISSUE TITLE
Research Spike: Elasticache Service Fixes and Improvements

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#14959]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Elasticache implementation in the Terraform AWS Provider presents some unique challenges:

- The `aws_elasticache_cluster` and `aws_elasticache_replication_group` resources were created early in Terraform's history, when certain Terraform resource design philosophies were not fully understood yet.
- The Elasticache API predates infrastructure as code tooling so the API calls and parameters do not necessarily align across Create/Read/Update/Delete operations.

Over the past year or so, there are a lot of reports of odd Elasticache behaviors in the Terraform AWS Provider and new features which because of the above items can be more difficult to implement than other AWS services. Rather than piecemeal handling each of these reports and requests, this issue represents a dedicated effort by the maintainers to summarize an action plan across addressing the various open Elasticache issues, including but not limited to:

* Returning endpoint information in a manner appropriate for Terraform resources and useful for practitioners
* Adding new multi-AZ capabilities, which were separated from automatic failover capabilities in the API
* Investigating missing or confusing documentation, in particular encryption with single cluster Redis
* Investigating individual replica/shard management
* Investigating encryption updates in Replication Groups
* Investigating availability zone handling in Replication Groups
* Investigating Global Replication Groups and their potential implementation as a new Terraform resource
* Investigating Snapshots and their potential implementation as a new Terraform resource to ensure restore behaviors are appropriately implemented
* Adding support for deployment in Outposts

The output of this research will likely be similar to that [done for the `aws_acm_certificate` resource](https://github.com/terraform-providers/terraform-provider-aws/issues/13053), but does not necessarily mean any breaking changes are to be proposed as part of this effort.

### New or Affected Resources

* aws_elasticache_cluster
* aws_elasticache_global_replication_group
* aws_elasticache_replication_group
* aws_elasticache_snapshot
* aws_elasticache_user
* aws_elasticache_user_group

### References

* [Similar effort for `aws_acm_certificate` research](https://github.com/terraform-providers/terraform-provider-aws/issues/13053)
* [Open service/elasticache issues and pull requests](https://github.com/terraform-providers/terraform-provider-aws/labels/service%2Felasticache)

**Comment by alexjurkiewicz** [comment]
There are a lot of PRs adding support for loading the reader endpoint. #11513, #11371, #10531, #9979, #6014, #15515, #15513 are all near-duplicates.

**Comment by gdavison** [comment]
Individual issues have been created to track findings
