### ISSUE TITLE
custom classifiers are not being added to crawler

### ISSUE THREAD

**Issue by aminullahfc** [hashicorp/terraform-provider-aws#14969]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.20
provider.archive v1.3.0
provider.aws v2.70.0

### Affected Resource(s)

* aws_glue_crawler

### Terraform Configuration Files

```hcl
resource "aws_glue_classifier" "csv_classifier" {
  count = var.csv_classifier_name != "" ? 1 : 0
  name  = var.csv_classifier_name

  csv_classifier {
    allow_single_column    = lookup(var.csv_classifier_configs, "allow_single_column")
    contains_header        = lookup(var.csv_classifier_configs, "contains_header")
    delimiter              = lookup(var.csv_classifier_configs, "delimiter")
    disable_value_trimming = lookup(var.csv_classifier_configs, "disable_value_trimming")
    quote_symbol           = lookup(var.csv_classifier_configs, "quote_symbol")
  }

}

resource "aws_glue_crawler" "crawler" {
  classifiers   = [var.csv_classifier_name != "" ? aws_glue_classifier.csv_classifier[0].id : ""]
  database_name = var.glue_catalog_database_name
  name          = var.glue_crawler_name
  role          = aws_iam_role.glue_crawler_role.arn
  s3_target {
    path       = format("s3://%s/%s", var.s3_bucket_name, var.filter_s3_path)
    exclusions = var.exclusions
  }

```

### Expected Behavior

After terraform apply, expected result is custom classifier being added to crawler.
### Actual Behavior

it appears in the list of `custom classifiers` but not in `selected classifiers`. 

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by DrFaust92** [comment]
Hey @aminullahfc, im taking a look at this and there isn't an option directly in the API to set `selected classifiers`. (didn't see how to set it in the UI either) it might might be part of the `configuration` argument. so im not sure this issue is directly related to the AWS Provider. will update.

**Comment by DrFaust92** [comment]
closing for lack of response
