### ISSUE TITLE
Modifying cidr_blocks of resource aws_security_group_rule should not force a new resource

### ISSUE THREAD

**Issue by iwasnobody** [hashicorp/terraform-provider-aws#14966]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
If sometimes we modify the cidr_blocks to add addtional cidr, terraform will destroy then create the resource, not add resource. This behavior will have the following issues:
1.We have sentinel policy combined with workspace auto approve. If sentinel check there is only add operation, no change or destroy. It will pass and workspace auto approve. This will not work for this scenario although we just add a cidr. In aws console, it just like add another sg rule entry which I think should make it add
2.AWS will destroy previously sg rule entry and recreate all entry at once, it may influence newly created connection although tf do the delete then create very quickly

The following is what I discussed with terraform enterprise support and he suggest I open an issue here.
![image](https://user-images.githubusercontent.com/20101997/91920353-60035900-ecfb-11ea-93d8-e2522b1697b5.png)
![image](https://user-images.githubusercontent.com/20101997/91920375-6c87b180-ecfb-11ea-977f-eb98c8b94265.png)

### New or Affected Resource(s)

* aws_security_group_rule

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by peterx1986** [comment]
Yeah, this is still a case unfortunately. Update to "cidr_blocks" attribute (type list - actually) in resource "aws_security_group_rule" causing "# forces replacement". That's a pitty.
