### ISSUE TITLE
Add validation to targets for `aws_route`

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#14995]
### Description

The `aws_route` resource allows practitioners to incorrectly add more than one target type, when only one can be used. `tflint` has added [a check to prevent this](https://github.com/terraform-linters/tflint/blob/master/docs/rules/aws_route_specified_multiple_targets.md), but we should implement it in the provider.

Use `ExactlyOneOf`, since one of the targets is required.

### New or Affected Resource(s)

* aws_route

**Comment by ewbankkit** [comment]
We should also be able to do this for destination type `destination_cidr_block` and `destination_ipv6_cidr_block` (and `destination_prefix_list_id` for https://github.com/terraform-providers/terraform-provider-aws/issues/13986).
