### ISSUE TITLE
CloudWatch Logs integration  Missing on OpsWorks Layers

### ISSUE THREAD

**Issue by hc-danieltiziani** [hashicorp/terraform-provider-aws#15010]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When you create a Layer on Opsworks, e.g. a Custom Layer <https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_custom_layer>, it's missing the option to activate Cloudwatch Logs.

The option is the following:

![image](https://user-images.githubusercontent.com/58551089/92130897-8e6d5b00-ee05-11ea-83f8-9bc239db2528.png)

### Affected Resource

* aws_opsworks_*_layer

**Comment by DrFaust92** [comment]
#12433 addresses this
