### ISSUE TITLE
Add support for ApplyOnlyAtCronInterval to aws_ssm_association

### ISSUE THREAD

**Issue by xoob** [hashicorp/terraform-provider-aws#15034]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS System Manager has the ability to skip the first run of a new association and only execute it at the next cron interval. This can be useful for things like periodic snapshots that you don't want to execute immediately after the system boots up. When editing an SSM association in the AWS Console, there's a checkbox labelled **Apply association only at the next specified cron interval**.

The AWS API call `CreateAssociation` accepts it as well:

> `ApplyOnlyAtCronInterval` - By default, when you create a new associations, the system runs it immediately after it is created and then according to the schedule you specified. Specify this option if you don't want an association to run immediately after you create it.

Unfortunately it doesn't look like Terraform accepts this parameter. It would be great it you could add it.

### New or Affected Resource(s)

* aws_ssm_association

### Potential Terraform Configuration

```hcl
resource "aws_ssm_association" "example" {
  name = aws_ssm_document.example.name

  apply_only_at_cron_interval = true

  targets {
    key    = "InstanceIds"
    values = [aws_instance.example.id]
  }
}
```

### References

* https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateAssociation.html#systemsmanager-CreateAssociation-request-ApplyOnlyAtCronInterval

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 3.28.0 of the Terraform AWS Provider, later today. Thank you to @nikhil-goenka for the implementation. 👍
