### ISSUE TITLE
[Feature] set provider configs more easier

### ISSUE THREAD

**Issue by dfang** [hashicorp/terraform-provider-aws#15050]
### Description

if you use localstack for local testing in local or dev stage. you need to set various endpoints for aws provider like [this](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/custom-service-endpoints#localstack). 

and you want to use real aws for endpoints for other stages. eg. you have stages, dev、staging、prod 。

so you want to use localstack in dev stage,  how do you set this ?

for set different config backends for different stages, [this](https://aws-blog.de/2019/05/managing-multiple-stages-with-terraform.html) would help, but i don't find a effective way to implement different provider configs for different stages.

in simple terms, what i want to achieve is (pseudo code):

```
provider "aws" {
  if is_dev_stage or is_local_stage {
    s3_force_path_style         = true
    secret_key                  = "mock_secret_key"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_requesting_account_id  = true

    endpoints {
        apigateway     = "http://localhost:4567"
        cloudformation = "http://localhost:4581"
        cloudwatch     = "http://localhost:4582"
        dynamodb       = "http://localhost:4569"
        es             = "http://localhost:4578"
        firehose       = "http://localhost:4573"
        iam            = "http://localhost:4593"
        kinesis        = "http://localhost:4568"
        lambda         = "http://localhost:4574"
        route53        = "http://localhost:4580"
        redshift       = "http://localhost:4577"
        s3             = "http://localhost:4572"
        secretsmanager = "http://localhost:4584"
        ses            = "http://localhost:4579"
        sns            = "http://localhost:4575"
        sqs            = "http://localhost:4576"
        ssm            = "http://localhost:4583"
        stepfunctions  = "http://localhost:4585"
        sts            = "http://localhost:4592"
    }
  }
}
```

**Comment by bflad** [comment]
Hi @dfang 👋  Thank you for submitting this. Terraform has built-in functionality for [override files](https://www.terraform.io/docs/configuration/override.html) which may help in your case. You should be able to optionally add the provider configuration override file passed on what environment you are operating in. Does this look like it would satisfy what you are looking for?

**Comment by dfang** [comment]
i'm not sure if `count = 1` like [this](https://medium.com/capital-one-tech/building-feature-toggles-into-terraform-d75806217647) works for endpoints block in provider block.

even if it works, how can i set `skip_credentials_validation, skip_metadata_api_check` only in local stage ?
