### ISSUE TITLE
Lambda EFS does not attempt to deal with a "not yet ready" error

### ISSUE THREAD

**Issue by lijok** [hashicorp/terraform-provider-aws#15053]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/aws v3.5.0
```

### Affected Resource(s)

* aws_lambda_function

### Terraform Configuration Files

Simple lambda config with an efs attachment

### Expected Behavior

Provider should catch the error, recognize it and try again
### Actual Behavior

```json
Error: Error creating Lambda function: InvalidParameterValueException: EFS file system arn:aws:elasticfilesystem:us-east-1:509665555555:file-system/fs-55ad290a referenced by access point arn:aws:elasticfilesystem:us-east-1:509665555555:access-point/fsap-0a0d70094333e958e has mount targets created in all availability zones the function will execute in, but not all are in the available life cycle state yet. Please wait for them to become available and try the request again.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "8576ac4d-3702-43e5-b871-f962a6fdad42"
  },
  Message_: "EFS file system arn:aws:elasticfilesystem:us-east-1:509665555555:file-system/fs-55ad290a referenced by access point arn:aws:elasticfilesystem:us-east-1:509665555555:access-point/fsap-0a0d70094333e958e has mount targets created in all availability zones the function will execute in, but not all are in the available life cycle state yet. Please wait for them to become available and try the request again.",
  Type: "User"
}
```
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by anGie44** [comment]
Hi @lijok, depending on how your `lambda_function` is configured, if you're also using an `aws_efs_mount_target` resource in your configuration, a possible workaround in the meantime would be to use an explicit `depends_on = [aws_efs_mount_target.example]` within the 'aws_lambda_function`.

**Comment by lijok** [comment]
Hi @anGie44 
The dependency is already there, based on the `file_system_config.arn` attribute being set to the arn of `aws_efs_access_point` resource. It appears that although the `aws_efs_access_point` is created, as far as terraform cares, it is not yet usable, which is what we're essentially attempting to do at `aws_lambda_function` creation time, by trying to attach an efs mount to it. So, because the resource is not yet ready to use, it returns that error code. Which I think the provider should catch, and retry on, rather than propogating it to the user

**Comment by anGie44** [comment]
I see, yep I was able to reproduce what you're seeing with the `file_system_config.arn` attribute being set to the arn of `aws_efs_access_point` resource, so I can confirm that dependency isn't sufficient at the moment and a possible fix could include catching the error you're seeing.  Does your configuration make use of the `aws_efs_mount_target` resource though? If so, this example could be applicable as it works around the runtime error with use of `depends_on` https://github.com/terraform-providers/terraform-provider-aws/blob/d197893acac9ee6b7271aad7eb58b7361d0768a1/aws/resource_aws_lambda_function_test.go#L1920

**Comment by lijok** [comment]
Ah great, we'll make use of that, thank you

**Comment by Vetchu** [comment]
I have a very similar case to that, I also setup the similar infrastructure (with `depends_on = [aws_efs_mount_target.mount]`) , but after the Lambda is created I immediately call it, and it fails with:
```
Error: EFSMountFailureException: The function couldn't mount the Amazon EFS file system with access point arn:aws:elasticfilesystem:us-east-1:275394553263:access-point/fsap-00498ec5b12fc6825.
{
  RespMetadata: {
    StatusCode: 403,
    RequestID: "7d6ed5e1-816c-4e9e-b5a5-665ab11758da"
  },
  Message_: "The function couldn't mount the Amazon EFS file system with access point arn:aws:elasticfilesystem:us-east-1:275394553263:access-point/fsap-00498ec5b12fc6825.",
  Type: "User"
}
```

I think it should wait for EFS to be ready before allowing terraform to complete the lambda resource.

Should I open another issue? It seems similar enough that I could append it to the one at the top.

**Comment by alastair-smith** [comment]
I also get this issue @Vetchu. Did you manage to find a suitable alternative/workaround?

---

>Error: EFSMountFailureException: The function could not mount the EFS file system with access point arn:aws:elasticfilesystem:us-east-2:123456789012:access-point/fsap-015cxmplb72b405fd.
>
>The mount request to the function's file system was rejected. Check the function's permissions, and confirm that its file system and access point exist and are ready for use.

[source](https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-invocation.html)

>You must add the DependsOn to ensure that the mount targets are fully created before the Lambda runs for the first time.

[source](https://docs.aws.amazon.com/lambda/latest/dg/configuration-filesystem.html)

Based on these two snippets of info in AWS docs I added a local exec to wait for the following

* Access point state: accepted
* File system state: accepted
* Mount target state: accepted

However I still had the same issue.

I'm running out of ideas and think it may be some DNS issue, e.g. https://docs.aws.amazon.com/efs/latest/ug/troubleshooting-efs-mounting.html#mount-fails-propegation, so am tempted to just put a dirty 90s sleep in my terraform.

**Comment by Vetchu** [comment]
@alastair-smith I had no luck in fixing the error, so I simply put 
`terraform apply -auto-approve || terraform apply -auto-approve`
and it automated it in my pipeline. I think there might be a way to ensure that mount point is reachable, but I did not investigate that as this workaround worked for my use case. 

Good luck fixing it though should you insist on not putting sleep in terraform :)
