### ISSUE TITLE
AWS GovCloud (US) support for aws_rds_cluster_endpoint resource

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#15061]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This is a tracking issue for problems with the `aws_rds_cluster_endpoint` resource on GovCloud. A precheck is likely needed to avoid the test failure.

### New or Affected Resource(s)

* aws_rds_cluster_endpoint

### Problem report

Output from `aws_rds_cluster_endpoint` acceptance testing (GovCloud):

```
--- FAIL: TestAccAWSRDSClusterEndpoint_tags (790.96s)
Error: Error creating RDS Cluster Endpoint: InvalidParameterValue: Tagging endpoints is currently not available
        	status code: 400, request id: 89d2ddd4-a2cc-4e68-a694-ab07c529b87b

--- FAIL: TestAccAWSRDSClusterEndpoint_basic (946.55s)
Error: error listing tags for RDS Cluster Endpoint (arn:aws-us-gov:rds:us-gov-west-1:357342307427:cluster-endpoint:reader-6910710774328620347): InvalidParameterValue: The specified resource name does not match an RDS resource in this region.
        	status code: 400, request id: cadfaeaa-2001-4e44-823e-af840be8aa89
```

### References

* #15027

**Comment by tatsuya4559** [comment]
I've got the same problem in ap-northeast-3(Osaka) region.
