### ISSUE TITLE
VPC flow log churn using Terraform 0.13

### ISSUE THREAD

**Issue by acdha** [hashicorp/terraform-provider-aws#15073]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.2
+ provider registry.terraform.io/-/aws v3.5.0
+ provider registry.terraform.io/hashicorp/aws v3.5.0
+ provider registry.terraform.io/hashicorp/http v1.2.0
```

### Affected Resource(s)

* aws_flow_log
* aws_cloudwatch_log_group

### Terraform Configuration Files

```hcl
data "aws_cloudwatch_log_group" "VPCFlowLogs" {
  name = "/Security/VPCFlowLogs"
}

data "aws_iam_role" "VPCFlowLogger" {
  name = "VPCFlowLogger"
}

resource "aws_flow_log" "vpc_flow_logs" {
  vpc_id          = module.vpc.vpc_id
  traffic_type    = "ALL"
  log_destination = data.aws_cloudwatch_log_group.VPCFlowLogs.arn
  iam_role_arn    = data.aws_iam_role.VPCFlowLogger.arn
}
```

### Expected Behavior

1. Terraform would update the flog log once and not attempt to recreate it on every run

### Actual Behavior

```
 ~ log_destination          = "arn:aws:logs:us-east-1:…:log-group:/Security/VPCFlowLogs" -> "arn:aws:logs:us-east-1:…:log-group:/Security/VPCFlowLogs:*" # forces replacement

```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This is new in Terraform 0.13 and did not happen with 0.12.29 and the AWS provider 3.20 

### References

I was not expecting to see this with #14214 having shipped in 3.0.0

**Comment by anGie44** [comment]
Hi @acdha, thank you for creating this issue. I believe the diff occurs b/c #14214 removed the trailing suffix in the `cloudwatch_log_group` resource, but not in the data-source and behind the scenes, the `aws_flow_log` resource automatically trims the configured `log_destination` value's `:*` suffix. In the meantime I would recommend using a `replace` method like described here https://github.com/terraform-providers/terraform-provider-aws/pull/14214#issuecomment-670548936 to handle the perpetual diff.

**Comment by acdha** [comment]
That is exactly what I did and it’s working well

**Comment by anGie44** [comment]
just a follow-up question @acdha: does the workaround not behave as expected in Terraform 0.13?

**Comment by anGie44** [comment]
Note to future self (and others): to have the `aws_cloudwatch_log_group` data source behave on-par with the resource's ARN handling, this would need to be handlined in the next major release.

**Comment by acdha** [comment]
It's definitely not hard to work around so I wonder whether this could be perhaps addressed by simply updating the documentation (it seems like more trouble than it'd be worth to add something like an accessor which trims it).

**Comment by anGie44** [comment]
Sure thing! If you or someone who comes across this issue wants to submit a PR with the documentation update we'll be happy to review it 😄

I'm going to leave this issue open in the meantime as it can still be addressed but further down the line in the next major release 👍
