### ISSUE TITLE
security group is required and not optional when creating aws_efs_mount_target

### ISSUE THREAD

**Issue by maherfayez** [hashicorp/terraform-provider-aws#15089]
kindly update your documentation here 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_mount_target

**Comment by anGie44** [comment]
Hi @maherfayez, thank you for creating this issue! Do you mind providing an example configuration or more details regarding a case where the `security_groups` argument is needed?

**Comment by maherfayez** [comment]
Hi @anGie44  

###################################### Creating the EFS ##################
resource "aws_efs_file_system" "EFS" {
  creation_token = var.EFSTokenName

  tags = {
    Name = var.EFSName
  }
}

output "EFS-ID"{
    value = aws_efs_file_system.EFS.id
}

# creating the EFS required
module "smsxxxEFS" {
    source                                          = "xxxxxxxxxxxxxxxxx"
    EFSTokenName                            = var.smsxxxEFSTokenName
    EFSName                                      = var.smsxxxEFSName
}

# the EFS variables
variable "smsxxxEFSTokenName" {
    description = ""
    default     = "developEFS"
    type        = string 
}
variable "smsxxxEFSName" {
    description = ""
    default     = "developEFS"
    type        = string 
}

###################################### Creating the EFS mount Target #################
resource "aws_efs_mount_target" "EFSMountTarget" {
  count                                           = var.EFSMountTargetsubnetsCount
  file_system_id                              = var.EFSID
  subnet_id                                    = element(var.EFSMountTargetSubnet,count.index)
  #security_groups                        = var.EFSMounTargetsSG                  ###This is required and not optional as per documentation
}

module "smsxxxWorkerNewEFSMountTarget" {
    source                                                    = "xxxxxxxxxxx"        # path of the below module
    EFSMountTargetsubnetsCount              = var.qcAccountPrivateSubnetsCount
    EFSID                                                     = module.smsxxxEFS.EFS-ID
    EFSMountTargetSubnet                         = var.qcAccountPrivateSubnetIDs
    #EFSMounTargetsSG                             = xxxxxxxxxxxxxxxxx        ###This is required and not optional 
}


#EFS target mount variables
variable "qcAccountPrivateSubnetsCount" {
  type        = string
  description = "number of subnets to mount to"
  default     = 3
}

variable "qcAccountPrivateSubnetIDs"{
    description =   ""
    default       =   ["subnet-xxx","subnet-xxxx","subnet-xxxx"]
    type        =   list(string)
}
