### ISSUE TITLE
resource/aws_guardduty_organization_configuration: Guardduty S3 Protection Auto Enable for Member Accounts not available

### ISSUE THREAD

**Issue by nehalsangoi** [hashicorp/terraform-provider-aws#15106]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_guardduty

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

No data-sources S3Logs autoenable option in Resource: aws_guardduty_organization_configuration similar to provided in aws cli at https://awscli.amazonaws.com/v2/documentation/api/latest/reference/guardduty/update-organization-configuration.html

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by bflad** [comment]
For others benefit, please note this is different than #14607 which is for the `aws_guardduty_detector` resource while this one can be used for tracking the `aws_guardduty_organization_configuration` resource enhancement. I have updated the issue titles in both to delineate the difference.
