### ISSUE TITLE
bucket_regional_domain_name does not contain the region

### ISSUE THREAD

**Issue by ac-hibbert** [hashicorp/terraform-provider-aws#15102]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_s3_bucket

### Expected Behavior

bucket_regional_domain_name should contain a region i.e.

```<bucket-name>.s3.us-east-1.amazonaws.com```

### Actual Behavior

However it doesn't, it is the same value as bucket_domain_name i.e. 

```<bucket-name>.s3.amazonaws.com```

### Steps to Reproduce

Create an S3 bucket with terraform

**Comment by bflad** [comment]
Hi @hibbert 👋  Thank you for reporting this and sorry you ran into trouble here. Could you please provide some additional information so we can help troubleshoot this issue?

* Terraform AWS Provider version
* Associated provider configuration (`provider "aws" { ... }` ) for the `aws_s3_bucket` resource

The current resource code that configures that attribute can be found here: https://github.com/terraform-providers/terraform-provider-aws/blob/2dbd3ddeaf97e59d4cc4096257b1f87bd2f78b2e/aws/resource_aws_s3_bucket.go#L1276-L1300

This was updated in the last month or so per recommendations from AWS. The discovered region should always be returned as `us-east-1` due the AWS Go SDK calling `NormalizeBucketLocation` when the response is empty, which in turn should be triggering the endpoint lookup returning `https://s3.us-east-1.amazonaws.com`, but maybe there is something unaccounted for in your setup.

**Comment by nuxero** [comment]
I'm also getting this issue. Provider details are:

```
provider "aws" {
  version = "~> 2.0"
  region  = var.aws_region
  profile = "XXXXX"

  assume_role {
    role_arn = "arn:aws:iam::${var.aws_account_id}:role/XXXXX-${terraform.workspace}-XXXXX"
  }
}
```

This is a multi AWS accounts scenario where a Terraform assumes a role based on the local profile. Account ID and region are provided through vars and the workspace name is used to construct the role name.

**Comment by GaboFDC** [comment]
Same issue, can't properly point a cname to the bucket because I need to use the regional domain.

**Comment by albertocastro63** [comment]
Same issue, I am trying to configure a CF distribution and I need that value.

**Comment by Madh93** [comment]
```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.40.0
```

Same issue, but only the buckets created in the `us-east-1` region are affected.

Bucket in `us-east-2` is :heavy_check_mark::

```
Changes to Outputs:
  + bucket_regional_domain_name = "xxx-xxx-xxx.s3.us-east-2.amazonaws.com"
```

Bucket in `us-west-2` is :heavy_check_mark::

```
Changes to Outputs:
  + bucket_regional_domain_name = "xxx-xxx-xxx.s3.us-west-2.amazonaws.com"
```

Bucket in `us-east-1`is :x::

```
Changes to Outputs:
  + bucket_regional_domain_name = "xxx-xxx-xxx.s3.amazonaws.com"
```

**Comment by harrisoncramer** [comment]
> ```
> Terraform v0.13.5
> + provider registry.terraform.io/hashicorp/aws v3.40.0
> ```
> 
> Same issue, but only the buckets created in the `us-east-1` region are affected.
> 
> Bucket in `us-east-2` is ✔️:
> 
> ```
> Changes to Outputs:
>   + bucket_regional_domain_name = "xxx-xxx-xxx.s3.us-east-2.amazonaws.com"
> ```
> 
> Bucket in `us-west-2` is ✔️:
> 
> ```
> Changes to Outputs:
>   + bucket_regional_domain_name = "xxx-xxx-xxx.s3.us-west-2.amazonaws.com"
> ```
> 
> Bucket in `us-east-1`is ❌:
> 
> ```
> Changes to Outputs:
>   + bucket_regional_domain_name = "xxx-xxx-xxx.s3.amazonaws.com"
> ```

I'm having the same issue, my S3 bucket in us-east-1 does not contain the region.

**Comment by snstanton** [comment]
Has there been any progress on this issue?  This is problematic for cloudfront origin configurations.

**Comment by martingehrke** [comment]
I am also having this issue.

**Comment by mkozjak** [comment]
Same here. Needed to form the ID manually using aws_s3_bucket.region and aws_s3_bucket.name, hardcoding the rest of the parts.

**Comment by cfarrend** [comment]
We also have this issue, provider version `3.63.0` for `us-east-1` region.

**Comment by alansikora** [comment]
3.74 still have this issue...

**Comment by deltacodepl** [comment]
yep, it's still relevant

**Comment by privomcgowan** [comment]
hashicorp/aws v4.54.0 still having this issue

**Comment by Aronyu127** [comment]
hashicorp/aws v4.66.1 still having this issue

**Comment by ypamplona-flourishfi** [comment]
`    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.67.0"
    }`
    
    still having this issue :(
