### ISSUE TITLE
aws_ebs_default_kms_key returns invalid key_arn

### ISSUE THREAD

**Issue by alekna** [hashicorp/terraform-provider-aws#15137]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

# Terraform CLI and Terraform AWS Provider Version
```
$ terraform version
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/aws v3.6.0
```

### Affected Resource(s)

* aws_ebs_default_kms_key
* aws_ebs_volume

### Terraform Configuration Files
As per example on https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ebs_default_kms_key
```hcl
data "aws_ebs_default_kms_key" "current" {}

resource "aws_ebs_volume" "example" {
  availability_zone = "us-west-2a"

  encrypted  = true
  kms_key_id = data.aws_ebs_default_kms_key.current.key_arn
}
```

### Expected Behavior

* encrypted EBS volume is created

### Actual Behavior
```
$ terraform apply
data.aws_ebs_default_kms_key.current: Refreshing state...

Error: "kms_key_id" (alias/aws/ebs) is an invalid ARN: arn: invalid prefix

  on ec2.tf line 21, in resource "aws_ebs_volume" "example":
  21:   kms_key_id = data.aws_ebs_default_kms_key.current.key_arn
```

### Steps to Reproduce

1. `terraform apply`

**Comment by karnauskas** [comment]
Looks like AWS API which returns it: `<kmsKeyId>alias/aws/ebs</kmsKeyId>` if default key is managed by AWS.
You can work around this with:

```
data "aws_ebs_default_kms_key" "current" {}

data "aws_kms_key" "current" {
  key_id = data.aws_ebs_default_kms_key.current.key_arn
}

resource "aws_ebs_volume" "example" {
  availability_zone = "us-west-2a"

  encrypted  = true
  kms_key_id = data.aws_kms_key.current.arn
}
```

**Comment by anGie44** [comment]
Related https://github.com/terraform-providers/terraform-provider-aws/issues/13860

**Comment by anGie44** [comment]
Hi @alekna, thank you for creating this issue! Given the upstream behavior @karnauskas mentioned above, we can plan to document this behavior in the data-source docs to capture this use case. In the meantime I've provided feedback to the EC2 service team's API documentation.
