### ISSUE TITLE
Graceful sequencing of RDS changes with apply_immediately=false

### ISSUE THREAD

**Issue by acdha** [hashicorp/terraform-provider-aws#15146]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With an RDS Aurora cluster, I ran into an issue when attempting to upgrade the cluster database version on a cluster with `apply_immediately=false`. The API to modify the cluster failed with an error like this:

```
 InvalidDBInstanceState: Cannot modify engine version because there is a pending orderable config change for DB instance: …20200803214748409900000001
```

The root cause for this wasn't immediately obvious since this is completely invisible in the AWS Console but it was immediately clear checking the API response, which showed that some previous instance class changes hadn't yet been applied since it was before the scheduled maintenance window:

```json
"PendingModifiedValues": [
    {
        "DBInstanceClass": "db.r4.xlarge"
    }
]
```

Trying to push both of these changes out required a somewhat inelegant approach: rollback the change to the version, set `apply_immediately=true` on the instances, let Terraform apply it, and then run the version change to upgrade. 

The current situation is workable but it feels like there could be a more graceful way to handle this — maybe just as simple as helpfully reporting a suggestion for the `InvalidDBInstanceState`  error when the API status shows a non-empty `PendingModifiedValues` for any instance or, more ambitiously, deferring the cluster update until after the instances finish apply even though the dependencies would normally run the other way.

### New or Affected Resource(s)

* aws_rds_cluster
* aws_rds_cluster_instance

### Potential Terraform Configuration

```hcl
resource "aws_rds_cluster" "this" {
  apply_immediately               = (var.environment != "production")
  cluster_identifier              = lower(var.deployment_id)
  database_name                   = lower(var.project_name)
  tags                            = var.tags
  engine                          = "aurora-mysql"
  engine_version                  = "5.7.mysql_aurora.2.08.2"
…
}

resource "aws_rds_cluster_instance" "this" {
  apply_immediately               = (var.environment != "production")
  for_each                        = aws_rds_cluster.this.availability_zones
  cluster_identifier              = aws_rds_cluster.this.id
  engine                          = "aurora-mysql"
  availability_zone               = each.key
  tags                            = var.tags
  instance_class                  = var.database_instance_class
…
}
```

## Terraform Versions

```
Terraform v0.13.2
+ provider registry.terraform.io/-/aws v3.5.0
+ provider registry.terraform.io/-/http v1.2.0
+ provider registry.terraform.io/hashicorp/aws v3.5.0
+ provider registry.terraform.io/hashicorp/http v1.2.0
```

**Comment by gdavison** [comment]
Thanks for raising this issue, @acdha. To help recreate this during development and testing, was the pending change in `DBInstanceClass` from a change in the `aws_rds_cluster_instance` resources, or did it originate elsewhere, such as the CLI or Console?

The best approach will likely be to handle the `InvalidDBInstanceState` and retry

**Comment by acdha** [comment]
It was from a change I'd made – actually applied in the same run as I was making multiple changes in one config update.
