### ISSUE TITLE
r/aws_instance,r/aws_launch_template: Handle credit_specification for new EC2 T4g instance family

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#15156]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is a new burstable Amazon EC2 instance family, **T4g**.
The `aws_instance.credit_specification` attribute needs to be handled as for the **T3** instance family.

> T4g instances are designed for applications that don’t use CPU at full power most of the time, using the same credit model as T3 instances with unlimited mode enabled by default.

#### Resources

* [`aws_instance`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance)
* [`aws_launch_template`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template)

#### Data sources

* [`aws_instance`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/instance)
* [`aws_launch_template`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/launch_template)

### Potential Terraform Configuration

```hcl
resource "aws_instance" "example" {
  instance_type = "t4g.micro"
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/09/announcing-new-amazon-ec2-t4g-instances-powered-by-aws-graviton2-processors/).
[Blog post](https://aws.amazon.com/blogs/aws/new-t4g-instances-burstable-performance-powered-by-aws-graviton2/).

**Comment by jackluo923** [comment]
Any updates on this? The pull request has been in WIP for half a year. Do you plan on continue working on it or is it abandoned?

**Comment by rafalkrupinski** [comment]
As a workaround, have you tried changing the default credit specification in EC2 settings?
