### ISSUE TITLE
Disabling DynamoDB stream leads to inconsistency between tfstate file and tf config files

### ISSUE THREAD

**Issue by jbigtani** [hashicorp/terraform-provider-aws#15189]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.29
+ provider.aws v3.4.0

### Affected Resource(s)

* aws_dynamodb_table

### Terraform Configuration Files

```hcl
Step 1: Create table with Stream enabled. 
resource "aws_dynamodb_table" "jb-example" {
  name             = "jb-example"
  hash_key         = "TestTableHashKey"
  billing_mode     = "PAY_PER_REQUEST"
  attribute {
    name = "TestTableHashKey"
    type = "S"
  }
  stream_enabled=true
  stream_view_type="KEYS_ONLY"
}

Step 2: Disable Stream
Step 1: Create table with Stream enabled. 
resource "aws_dynamodb_table" "jb-example" {
  name             = "jb-example"
  hash_key         = "TestTableHashKey"
  billing_mode     = "PAY_PER_REQUEST"
  attribute {
    name = "TestTableHashKey"
    type = "S"
  }
  stream_enabled=false
  stream_view_type="KEYS_ONLY"
}

Step 3: do terraform apply without changes.
```

### Expected Behavior

After disabling stream, tf config file and tfstate file should be in same state. 

### Actual Behavior

There is difference in both due to presence of stream_view_type in tf config file which is missing in tfstate file. This leads to issues in next step when you apply same file without changes. 

### Steps to Reproduce

1. `terraform apply` to create table with streaming enabled.
stream_enabled=true
stream_view_type="KEYS_ONLY"
2. `terraform plan` to disable streaming. Keep stream_view_type field.
stream_enabled=false
stream_view_type="KEYS_ONLY"
plan output is 
~ stream_enabled   = true -> false

3. `terraform apply` to with above change to disable streaming. Keep stream_view_type field.

4. `terraform show` to confirm only stream_enable field. No stream_view_type in tfstate. 
stream_enabled = false

This leads to inconsistency now. 

5. `terraform plan`  without any changes.
 + stream_view_type = "KEYS_ONLY"

6. `terraform apply`  without any changes.
Error: error updating DynamoDB Table (jb-example): ValidationException: Table has no stream to disable: TableName: jb-example
        status code: 400, request id: M788PONTG571HEBI2MV3FBP49VVV4KQNSO5AEMVJF66Q9ASUAAJG

There should be two solutions to it. 
A. Enforce to not have stream_view_type when streaming is being disabled. Looks like this was original behaviour but it was changed. 
https://github.com/terraform-providers/terraform-provider-aws/issues/1134
https://github.com/cloudposse/terraform-aws-dynamodb/pull/26

B. If we allow to keep stream_view_type, it needs to be there in tfstate too so that tf config file and state file matches to each other. This way on next apply it will show no change. 

I really liked Cloudformation way to handle stream with one field rather than two fields.
### References

*  #1134
* https://github.com/cloudposse/terraform-aws-dynamodb/pull/26
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-streamspecification.html

**Comment by gdavison** [comment]
Thanks for the issue @jbigtani.

`stream_view_type` should only be valid when `stream_enabled` is `true`. Unfortunately, there is a gap when `stream_enabled` is set to `false`.

Implementation note: `stream_view_type ` should be configured with `RequiredWith`. It also should use the values from `dynamodb.StreamViewType_Values()` instead of individual strings, and the `StateFunc` should likely be removed.

**Comment by achobanov** [comment]
Having the same issue, under slightly different circumstances:
1. I had multiple dynamo tables already defined
2. I added streams configuration in my resources and variable:
  - added `stream_enabled` to the resource (all tables) with a dynamic value (var)
  - added `stream_view_type` to in the resource (all tables) with a constant value (regardless of `stream_enabled`)
  - configured only single table output with `stream_enabled = true`
3. Plan  -  no issues
4. Apply - adds stream to the single table and throws errors for the rest.

**Comment by mkpatel-tivo** [comment]
I also face same issue, 

1. I had multiple dynamo tables already defined
2. I added streams configuration in my resources and variable:

- added stream_enabled to the resource (all tables) with a dynamic value (var)
- added stream_view_type to in the resource (all tables) with a constant value (regardless of stream_enabled)
- configured only single table output with stream_enabled = true

3. Plan - no issues
4. Apply - adds stream to the single table and throws errors for the rest.

**Comment by balajibandlapalli** [comment]
Having the same issue:

1.  Multiple dynamo tables already created
2. Enabled streams configuration via variable files with default false
3.  Added stream_enabled to the resource (all tables as we use module) with a dynamic value (var)
4. Added stream_view_type to in the resource (all tables) with a constant value (regardless of stream_enabled)
5. configured only single table with stream_enabled = true
Plan - no issues
Apply - adds stream to the single table and throws errors for the rest for the tables (Table has no stream to disable)

**Comment by YakDriver** [comment]
I was able to reproduce this and found several problems. I've fixed them (in <PR forthcoming>) but since this came from several issues, please let me know if there are still edge cases that are causing problems with a new issue.
