### ISSUE TITLE
aws directory service directory timeout increase

### ISSUE THREAD

**Issue by jkoop144** [hashicorp/terraform-provider-aws#15186]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The aws_directory_service_directory will timeout with the default 10m creation time when deploying this to a govcloud based env.

### New or Affected Resource(s)

* `aws_directory_service_directory`

### Potential Terraform Configuration

```hcl
resource "aws_directory_service_directory" "secops_directory_service" {
  name     = var.directory_name
  password = var.directory_pass
  edition  = "Standard"
  type     = "MicrosoftAD"

  vpc_settings {
    vpc_id     = sort(data.aws_vpcs.vpc.ids)[0]
    subnet_ids = [for s in data.aws_subnet.private : s.id]
  }

  tags = {
    Name = "directory_service"
    ManagedBy = "terraform"
    Compliance = "fedramp"
    Environment = lower(var.environment)
    Stage = lower(var.stage)
    Region = lower(var.region)
    Account = lower(var.account)
    ChargeCode = lower(var.application)
    GitTag = lower(var.GIT_TAG)
    BranchName = lower(var.BRANCH_NAME)
    RepoName = lower(var.REPO_NAME)
  }

  timeout = {
    create = "60m"
    delete = "45m"
  }
}
```

the output during a validate is:

```
Error: Unsupported argument
  on directory_service.tf line 26, in resource "aws_directory_service_directory" "secops_directory_service":
  26:   timeout = {
An argument named "timeout" is not expected here.
```

### References

* #0000

**Comment by anGie44** [comment]
Hi @jkoop144, thank you for creating this issue. While the resource doesn't support user-configurable timeouts, the create timeout is currently set to 60 Minutes. Do you mind providing more details regarding the timeout error you received?

**Comment by jkoop144** [comment]
Hi @anGie44, the timeout I am seeing is after only 10 minutes of creation time. Our environment is current running Terraform v0.12.28 so I am not sure when the 30 minute timeout was implemented.
