### ISSUE TITLE
Replace EC2 instance if in `shutting-down` state

### ISSUE THREAD

**Issue by optplx** [hashicorp/terraform-provider-aws#15222]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.12.26

### Affected Resource(s)
* aws_instance

### Expected Behavior

When an instance is in shutting-down state, it would be nice to be able to trigger the replace of the instance (e.g using a flag?). It happened multiple times that an instance is stucked for about 30 minutes in this state and I can't re-run Terraform to replace it until I open a ticket to their support to unlock the situation.

An instance can only be in shutting-down state if it is being terminated as per https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-lifecycle.html (`shutting-down: The instance is preparing to be terminated.`)

### Actual Behavior

Terraform sees no diff when the instance is stucked in shutting down and says `No changes. Infrastructure is up-to-date.`

### Steps to Reproduce

Hard to reproduce: you have to have the instance stucked in the shutting down state; or to trigger a `terraform apply` at the right time (while the instance is in shutting down)

**Comment by gdavison** [comment]
Thanks for the issue, @optplx. This looks like a reasonable option. However, we will need to do some research into what side-effects this may have.

**Comment by optplx** [comment]
Hello @gdavison it looks like AWS did something on their end, I did not reproduce any instance blocked in `shutting-down` state in a while. Thus I think we may close this issue
