### ISSUE TITLE
cloudfront.hosted_zone_id is wrong in China

### ISSUE THREAD

**Issue by romaninsh** [hashicorp/terraform-provider-aws#15223]
```
  zone_id = aws_cloudfront_distribution.web_distribution.hosted_zone_id
```

When using `hosted_zone_id` of `aws_cloudfront_distribution` it returns a hardcoded value of Z2FDTNDATAQYW2. This value is different for AWS in China and should be Z3RFFRIM2A3IF5 instead.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/aws v3.7.0
```

### Affected Resource(s)

* aws_cloudfront_distribution

### Terraform Configuration Files

```hcl
resource "aws_cloudfront_distribution" "web_distribution" {
  enabled             = true
  is_ipv6_enabled     = false
  aliases             = ["static.${var.domain}"]
  default_root_object = "index.html"

  origin {
    domain_name = data.aws_s3_bucket.components_bucket.bucket_regional_domain_name
    origin_id   = "S3"
  }

  viewer_certificate {
    iam_certificate_id =  aws_iam_server_certificate.cert.id
    ssl_support_method  = "sni-only"
  }

  default_cache_behavior {
    allowed_methods  = ["GET", "HEAD"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "S3"

    forwarded_values {
      query_string = false

      cookies {
        forward = "none"
      }
    }

    viewer_protocol_policy = "redirect-to-https"
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  tags = {
    CreatedBy = "terraform ssl-init"
  }
}

output "zone_id" {
  value = aws_cloudfront_distribution.web_distribution.domain_name
}
```

### References

I believe assumption is coming from:
https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/cloudfront_distribution_configuration_structure.go#L24

**Comment by anGie44** [comment]
Related docs: https://docs.amazonaws.cn/en_us/aws/latest/userguide/route53.html

**Comment by mgzenitech** [comment]
this isn't an enhancement, this is a bug :100: %

**Comment by anGie44** [comment]
nice catch @mgzenitech ! updated 👍
