### ISSUE TITLE
Unwarranted changes when updating tags on aws_autoscaling_group

### ISSUE THREAD

**Issue by philbal611** [hashicorp/terraform-provider-aws#15227]
### Community Note

* Please vote on this issue by adding a ?? [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.13
provider.aws v3.7.0

### Affected Resource(s)

* aws_autoscaling_group

### Terraform Configuration Files

```hcl
resource "aws_launch_configuration" "example" {
  .
  .
  .
}

resource "aws_autoscaling_group" "example" {
  name                 = "example"
  launch_configuration = "${aws_launch_configuration.example.name}"
  min_size             = "1"
  max_size             = "1"

  tags = [
    {
      key                 = "Name"
      value               = "example"
      propagate_at_launch = true
    },
    {
      key                 = "Owner"
      value               = "bezos"
      propagate_at_launch = true
    },
  ]
}
```

### Expected Behavior

After the `aws_autoscaling_group` has applied, when deleting a tag or updating an existing tag, only that change should plan.

### Actual Behavior

The deleted/updated tag update is shown, as well as an empty map entry, shown as `{}` in the plan.

### Steps to Reproduce

1. Configure the `aws_autoscaling_group`
2. Run `terraform apply`
3. Once deployed, either update or delete one of the tags:

```hcl
resource "aws_autoscaling_group" "example" {
  name                 = "example"
  launch_configuration = "${aws_launch_configuration.example.name}"
  min_size             = "1"
  max_size             = "1"

  tags = [
    {
      key                 = "Name"
      value               = "example"
      propagate_at_launch = true
    },
    {
      key                 = "Owner"
      value               = "gates" // <--- changed from "bezos"
      propagate_at_launch = true
    },
  ]
}
```
4. Run `terraform plan` and review the output:

```hcl
 # aws_autoscaling_group.example will be updated in-place
  ~ resource "aws_autoscaling_group" "example" {
        arn                       = "<arn>"
        availability_zones        = []
        default_cooldown          = 300
        desired_capacity          = 1
        enabled_metrics           = []
        force_delete              = false
        health_check_grace_period = 300
        health_check_type         = "EC2"
        id                        = "example"
        launch_configuration      = "launch_configuration_example"
        load_balancers            = []
        max_instance_lifetime     = 0
        max_size                  = 1
        metrics_granularity       = "1Minute"
        min_size                  = 1
        name                      = "example"
        protect_from_scale_in     = false
        service_linked_role_arn   = "<arn>"
        suspended_processes       = []
      ~ tags                      = [
          + {
              + "key"                 = "Owner"
              + "propagate_at_launch" = "true"
              + "value"               = "gates"
            },
          - {
              - "key"                 = "Owner"
              - "propagate_at_launch" = "true"
              - "value"               = "bezos"
            },
            {
                "key"                 = "Name"
                "propagate_at_launch" = "true"
                "value"               = "example"
            },
          + {}, // <--- this change is not configured in code
        ]
        target_group_arns         = []
        termination_policies      = []
        vpc_zone_identifier       = []
        wait_for_capacity_timeout = "10m"
    }
```

### Important Factoids

This specific anomaly doesn't seem harmful...the empty map _does_ persist in state once applied, but it doesn't change anything to the actual resource. The only time we caught it is when we ran it in TFE against our AWS Tags policy, which iterates through each `tags` map for the `aws_autoscaling_group` resource. When this extra empty map shows up, it breaks our policy. We've gotten around the policy issue in the meantime, but the provider issue still stands.

### References

* #0000

**Comment by anGie44** [comment]
Notes: I'm able to reproduce this in versions as early as `v2.64.0` of the provider
