### ISSUE TITLE
Add SASL/SCRAM auth to MSK

### ISSUE THREAD

**Issue by janlud** [hashicorp/terraform-provider-aws#15237]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS recently released SASL/SCRAM authentication for Kafka (MSK). Please add this option to the msk_cluster resource. The Go SDK should already have this.
[Go AWS SDK](https://github.com/aws/aws-sdk-go/releases/tag/v1.34.24)
### New or Affected Resource(s)

* aws_msk_cluster

### Potential Terraform Configuration

```hcl
client_authentication {
    sasl/scram = ""
  }
```

### References

* [AWS Go SDK](https://github.com/aws/aws-sdk-go/releases/tag/v1.34.24)
* [aws console](https://us-west-2.console.aws.amazon.com/msk/home?region=us-west-2#/cluster/create?isCustomCreate=true
)

**Comment by ewbankkit** [comment]
[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/09/amazon-msk-now-supports-sasl-scram-authentication-with-usernames-and-passwords-secured-by-aws-secrets-manager/).

```hcl
resource "aws_msk_cluster" "example" {
  client_authentication  {
    sasl {
      scram {
        enabled = true
      }
    }
  }
}
```
