### ISSUE TITLE
Unable to create encrypted Neptune cluster from unencrypted Neptune cluster snapshot

### ISSUE THREAD

**Issue by kalyansundar** [hashicorp/terraform-provider-aws#15240]
I am trying to create a new encrypted Neptune cluster from an unencrypted cluster snapshot through terraform but the created cluster is not encrypted.

**Expected Behavior**
Neptune cluster created should be encryption enabled

**Current Behavior**
Created cluster is not encryption enabled

**version**
```
Terraform v0.12.29
+ provider.aws v3.7.0

```

**Steps to Reproduce**

1. code snippet:
```
resource "aws_neptune_cluster" "default" {
  cluster_identifier        = "name"
  apply_immediately         = true
  backup_retention_period   = 5
  engine                    = "neptune"
  engine_version            = "1.0.1.0"
  final_snapshot_identifier = "name-final"
  neptune_subnet_group_name = "neptune-subnets"
  port                      = 8182
  preferred_backup_window   = "06:25-06:55"
  skip_final_snapshot       = false
  snapshot_identifier       = "snapshot_arn"

  # Encryption
  storage_encrypted       = true
  kms_key_arn             = "KMD_key_arn"

  vpc_security_group_ids = [ "security_group_id" ]

  
}
```

2. terraform plan  - shows `storageEncrypted` as true
3. terraform apply -  successfully created
4. on verification in aws console the cluster shows Encryption as Not Enabled

**Additional info is**, looks it supporting only if the snapshot tooks from encrypted cluster only.

**Comment by FarhanKhan-sains** [comment]
Any updates on this? I deleted a cluster thinking I would be able to recreate it with encryption enabled using a snapshot but am running into this problem.

**Comment by nlaxmi** [comment]
as far as I remember, It's not possible to take a snapshot from an unencrypted cluster and try to encrypt  it.

![image](https://user-images.githubusercontent.com/8059721/119140550-e9151880-ba61-11eb-81ec-63e5d813d1b1.png)

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/neptune.html

**Comment by FarhanKhan-sains** [comment]
@nlaxmi That's to copy a snapshot though. I'm trying to create a new cluster using a snapshot. This should be possible according to the AWS docs:

![image](https://user-images.githubusercontent.com/59688338/119145838-f15d5b80-ba41-11eb-94f6-f2ddcdab93fb.png)

https://docs.aws.amazon.com/neptune/latest/userguide/encrypt.html
