### ISSUE TITLE
ElastiCache cluster does not document ARN output field

### ISSUE THREAD

**Issue by kalyansundar** [hashicorp/terraform-provider-aws#15267]
HI,
I uable to get a elastic cache arn value after created the resource. Could you please give some suggestion to get that value ?

I have tried with data and output blocks, and using the pycharm with terraform support plugin

**Comment by gdavison** [comment]
Hi @kalyansundar. Unfortunately, the field is not in the documentation.

The field is named `arn`, so to access the ARN of the following ElastiCache cluster

```terraform
resource "aws_elasticache_cluster" "example" {
    ...
}
```

use `aws_elasticache_cluster.example.arn`.

**Comment by kalyansundar** [comment]
hi @gdavison I am getting the following error message

### Step-1
**Actual my code is given below**
```
resource "aws_elasticache_replication_group" "default" {
  for_each = { for item in var.replication_groups : item.name => item }

  replication_group_id          = each.value.name
......

locals {
 arn = [for replication_group in aws_elasticache_replication_group.default : (replication_group.arn)]
 }
```

switched into terraform console
Enter this command on terraform console `**local.arn**`


```
Error: Unsupported attribute

 arn = [for replication_group in aws_elasticache_replication_group.default : (replication_group.arn)]
This object does not have an attribute named "arn".

```

### Step-2
**And then i have tried by general way**
code
```
resource "aws_elasticache_replication_group" "default" {
  replication_group_id = "testing4"
  replication_group_description = "testing4-desc"
  number_cache_clusters = 2
  node_type = "cache.t3.micro"
  engine_version = "5.0.5"
  subnet_group_name = "redis-subnet-qa-group"
  security_group_ids = ["ffffffff",]
  maintenance_window = "sun:02:00-sun:04:00"
  apply_immediately  = true

  # Options we mandate
  automatic_failover_enabled = true
  auto_minor_version_upgrade = true
  engine                     = "redis"
  at_rest_encryption_enabled = true
  port                       = 6379



}

output "test" {
  value = aws_elasticache_replication_group.default.arn
}

```

```
Error: Unsupported attribute

  on main.tf line 168, in output "test":
 168:   value = aws_elasticache_replication_group.default.arn

This object has no argument, nested block, or exported attribute named "arn".


```

**Comment by angelabad** [comment]
Hi, @gdavison is talking about **aws_elasticache_cluster** and @kalyansundar about **aws_elasticache_replication_group**. So,

* aws_elasticache_cluster: hasnt arn documented
* aws_elasticache_replication_group: hasnt arn attribute in go code

I will try to fix this in next days.

Bye!

**Comment by angelabad** [comment]
Hi, @bflad or @gdavison , could you review this?

Thanks!
