### ISSUE TITLE
s3_object_copy: New resource

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#15277]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Practitioner workflows require copying S3 objects. For example, if a process periodically creates an s3 object with updated data and various people with varying bucket access need access to the object, copying the object to various buckets can create a simple, maintainable workflow. This sort of distribution can be automated with Terraform and creates an alternative to disrupting existing access management policies.

The `aws_s3_bucket_object` has a `source` argument which can be a local file. This mechanism creates a copy of a local file in S3. However, the source cannot be another s3 object. A new resource is needed to copy an S3 object.

### New or Affected Resource(s)

* aws_s3_object_copy

### Potential Terraform Configuration

```hcl
resource "aws_s3_object_copy" "test" {
  source = "reports/january.pdf"
  bucket = "destination_bucket"
  key    = "destination_key"
}
```

### References

* #3943
* #6383
* [aws_ami_copy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ami_copy)

**Comment by YakDriver** [comment]
@lorengordon What do you think of this approach?

**Comment by lorengordon** [comment]
A new resource would be fine. I don't entirely understand why the source for `aws_s3_bucket_object` can't be a more generic getter, but I can deal.

But, is there some intentional rationale for trying to construct something like an arn for an s3 object? I can't say I've ever seen any project that references s3 objects like that...

**Comment by YakDriver** [comment]
It comes from the API. I was thinking we'd be format agnostic and let the API handle the rest.

> You specify the value in one of two formats, depending on whether you want to access the source object through an access point.

https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#CopyObjectInput

`CopyObject()` is designed for cross-account copies. I'm not sure if cross-account will require the ARN format.

**Comment by YakDriver** [comment]
This is the potential list of arguments and attributes:

```
ACL *string `locationName:"x-amz-acl" type:"string" enum:"ObjectCannedACL"`
Bucket *string `location:"uri" locationName:"Bucket" type:"string" required:"true"`
CacheControl *string `locationName:"Cache-Control" type:"string"`
ContentDisposition *string `locationName:"Content-Disposition" type:"string"`
ContentEncoding *string `locationName:"Content-Encoding" type:"string"`
ContentLanguage *string `locationName:"Content-Language" type:"string"`
ContentType *string `locationName:"Content-Type" type:"string"`
CopyObjectResult *CopyObjectResult `type:"structure"`
CopySource *string `locationName:"x-amz-copy-source" type:"string" required:"true"`
CopySourceIfMatch *string `locationName:"x-amz-copy-source-if-match" type:"string"`
CopySourceIfModifiedSince *time.Time `locationName:"x-amz-copy-source-if-modified-since" type:"timestamp"`
CopySourceIfNoneMatch *string `locationName:"x-amz-copy-source-if-none-match" type:"string"`
CopySourceIfUnmodifiedSince *time.Time `locationName:"x-amz-copy-source-if-unmodified-since" type:"timestamp"`
CopySourceSSECustomerAlgorithm *string `locationName:"x-amz-copy-source-server-side-encryption-customer-algorithm" type:"string"`
CopySourceSSECustomerKey *string `marshal-as:"blob" locationName:"x-amz-copy-source-server-side-encryption-customer-key" type:"string" sensitive:"true"`
CopySourceSSECustomerKeyMD5 *string `locationName:"x-amz-copy-source-server-side-encryption-customer-key-MD5" type:"string"`
CopySourceVersionId *string `locationName:"x-amz-copy-source-version-id" type:"string"`
ExpectedBucketOwner *string `locationName:"x-amz-expected-bucket-owner" type:"string"`
ExpectedSourceBucketOwner *string `locationName:"x-amz-source-expected-bucket-owner" type:"string"`
Expiration *string `locationName:"x-amz-expiration" type:"string"`
Expires *time.Time `locationName:"Expires" type:"timestamp"`
GrantFullControl *string `locationName:"x-amz-grant-full-control" type:"string"`
GrantRead *string `locationName:"x-amz-grant-read" type:"string"`
GrantReadACP *string `locationName:"x-amz-grant-read-acp" type:"string"`
GrantWriteACP *string `locationName:"x-amz-grant-write-acp" type:"string"`
Key *string `location:"uri" locationName:"Key" min:"1" type:"string" required:"true"`
Metadata map[string]*string `location:"headers" locationName:"x-amz-meta-" type:"map"`
MetadataDirective *string `locationName:"x-amz-metadata-directive" type:"string" enum:"MetadataDirective"`
ObjectLockLegalHoldStatus *string `locationName:"x-amz-object-lock-legal-hold" type:"string" enum:"ObjectLockLegalHoldStatus"`
ObjectLockMode *string `locationName:"x-amz-object-lock-mode" type:"string" enum:"ObjectLockMode"`
ObjectLockRetainUntilDate *time.Time `locationName:"x-amz-object-lock-retain-until-date" type:"timestamp" timestampFormat:"iso8601"`
RequestCharged *string `locationName:"x-amz-request-charged" type:"string" enum:"RequestCharged"`
RequestPayer *string `locationName:"x-amz-request-payer" type:"string" enum:"RequestPayer"`
ServerSideEncryption *string `locationName:"x-amz-server-side-encryption" type:"string" enum:"ServerSideEncryption"`
SSECustomerAlgorithm *string `locationName:"x-amz-server-side-encryption-customer-algorithm" type:"string"`
SSECustomerKey *string `marshal-as:"blob" locationName:"x-amz-server-side-encryption-customer-key" type:"string" sensitive:"true"`
SSECustomerKeyMD5 *string `locationName:"x-amz-server-side-encryption-customer-key-MD5" type:"string"`
SSEKMSEncryptionContext *string `locationName:"x-amz-server-side-encryption-context" type:"string" sensitive:"true"`
SSEKMSKeyId *string `locationName:"x-amz-server-side-encryption-aws-kms-key-id" type:"string" sensitive:"true"`
StorageClass *string `locationName:"x-amz-storage-class" type:"string" enum:"StorageClass"`
Tagging *string `locationName:"x-amz-tagging" type:"string"`
TaggingDirective *string `locationName:"x-amz-tagging-directive" type:"string" enum:"TaggingDirective"`
VersionId *string `locationName:"x-amz-version-id" type:"string"`
WebsiteRedirectLocation *string `locationName:"x-amz-website-redirect-location" type:"string"`
```

**Comment by YakDriver** [comment]
@lorengordon 

> I don't entirely understand why the source for aws_s3_bucket_object can't be a more generic getter, but I can deal.

One of the design goals is to have one API call per resource/data source. Using `source` to copy a local file doesn't technically require a second AWS API call since it just uses Go to open and read the file. However, even still, the s3 bucket object is really, really old and if it were implemented today it would not have the `source` attribute probably. Using the `content` attribute and combining resources you could get the same result.

**Comment by lorengordon** [comment]
Unfortunately, combining the `content` options with another data source does not stream the data the way `source` does (or claims to), so that would still require a fair overhaul to pipe raw bytes between interfaces/sockets.

**Comment by lorengordon** [comment]
> But, is there some intentional rationale for trying to construct something like an arn for an s3 object? I can't say I've ever seen any project that references s3 objects like that...

Oh I see, the ARN is specific to the S3 Access Point feature (`accesspoint/my-access-point`), which is a new thing. That's not a "normal" reference for an s3 object; it's a way of telling the SDK to utilize a custom endpoint.

**Comment by YakDriver** [comment]
> Unfortunately, combining the `content` options with another data source does not stream the data the way `source` does (or claims to), so that would still require a fair overhaul to pipe raw bytes between interfaces/sockets.

From the code, they all (`source`, `content`, `content_base64`) stream the same way, using a byte Reader. 

See lines 211, 216, 225, 234, and 244.
https://github.com/terraform-providers/terraform-provider-aws/blob/fca055d8104032449eb521ff31273ddf281fdaa7/aws/resource_aws_s3_bucket_object.go#L211-L244

**Comment by lorengordon** [comment]
Then perhaps I'm just reading too much into the doc... This makes it sound like `source` streams and `content*` does not:

> For larger objects, use `source` to stream the content from a disk file.`

I know I attempted to use the `content*` options before settling on the hacky file-retrieval+`source`, and couldn't combine anything that actually worked. But it's been a while.

**Comment by YakDriver** [comment]
I haven't tried it either. Perhaps the inbound network stream plus outbound network stream is just not practical for big objects. The local file streaming is going to be much faster.
