### ISSUE TITLE
Inconsistent destination field naming for route table

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#15275]
The AWS API field names for route table route destinations are `DestinationCidrBlock`, `DestinationIpv6CidrBlock`, and `DestinationPrefixListId`.

In `aws_route_table` and `data.aws_route_table`, the inline route fields are `cidr_block` and `ipv6_cidr_block` (#15273 adds `DestinationPrefixListId`). In `aws_route` and `data.aws_route`, the fields are named `destination_cidr_block`, `destination_ipv6_cidr_block`, and `destination_prefix_list_id`.

Naming should be made consistent and the old names deprecated.

### Affected Resources

* aws_route_table
* data.aws_route_table

**Comment by ewbankkit** [comment]
For #15273 I am going with `destination_prefix_list_id`.
