### ISSUE TITLE
Add destination prefix list to route table

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#15273]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In addition to the destination CIDR block (`cidr_block`) and destination IPv6 CIDR block (`ipv6_cidr_block`), Routes can support a destination prefix list ID. One of the destination values is required.

This is already implemented on the resource `aws_route`, but only as a `Computed` field. It does not exist for inline routes in `aws_route_table` or in the data source `aws_route`.

### Affected Resources

* aws_route_table
* aws_route
* data.aws_route_table
* data.aws_route

**Comment by ewbankkit** [comment]
Related:

* #13986

**Comment by sethbacon** [comment]
Now that prefix lists are available, can we add them as a destination to the route resources in the list above? Any updates on this?

**Comment by randyspainhower** [comment]
any update on this? I need to do exactly this...

**Comment by puffpuf** [comment]
Hey, any updates?

**Comment by ewbankkit** [comment]
All applicable PRs have been merged.
This functionality will be available with Terraform AWS Provider **v3.35.0**.
