### ISSUE TITLE
Glue Data Catalog: support TargetDatabase and TargetTable

### ISSUE THREAD

**Issue by roberth-k** [hashicorp/terraform-provider-aws#15296]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This is related to the overall implementation of Lake Formation (https://github.com/terraform-providers/terraform-provider-aws/issues/9700).

https://github.com/terraform-providers/terraform-provider-aws/issues/14411 must also be implemented in order for Glue databases to be shareable with Lake Formation.

The `TargetDatabase` and `TargetTable` properties of Glue Data Catalog databases and tables are used for setting up [Resource Links](https://docs.aws.amazon.com/lake-formation/latest/dg/creating-resource-links.html), which is required to be able to surface cross-account shared tables in Athena and Redshift Spectrum.

It's possible there's also a specific `TableType` associated with this.

### New or Affected Resource(s)

* `aws_glue_catalog_table`
* `aws_glue_catalog_database`

### Potential Terraform Configuration

```hcl
resource "aws_glue_catalog_database" "example" {
  name = "my-database"

  target_database {
    catalog_id    = "1234567890"
    database_name = "external-database"
  }
}

resource "aws_glue_catalog_table" "example" {
  name          = "my-table"
  database_name = aws_glue_catalog_database.example.name

  target_table {
    catalog_id    = "1234567890"
    database_name = "external-database"
    name          = "external-table"
  }
}
```

### References

* https://github.com/terraform-providers/terraform-provider-aws/issues/9700
* https://github.com/terraform-providers/terraform-provider-aws/issues/14411
* https://docs.aws.amazon.com/lake-formation/latest/dg/creating-resource-links.html
* `TargetDatabase` in https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-catalog-databases.html#aws-glue-api-catalog-databases-DatabaseInput
* `TargetTable` in https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-catalog-tables.html#aws-glue-api-catalog-tables-TableInput

**Comment by breathingdust** [comment]
Closed via #19371 + #19372 and released in `v3.41.0` of the provider 🎉
