### ISSUE TITLE
"public" is an invalid value as acl for s3 resource

### ISSUE THREAD

**Issue by NikolaeVarius** [hashicorp/terraform-provider-aws#15304]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.12.29
provider.aws v3.7.0

### Affected Resource(s)

* aws_s3_bucket

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket" "eggegeggg" {
  bucket = "szhhehszhz"
  acl    = "public"
}
```

### Expected Behavior

Terraform should have rejected this code

### Actual Behavior

I only caught this since my CICD linter notified me.

According to https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl `public` is not a valid state.

Below shows TF output showing that the state had been successfully written with "public" and needs to be changed to "public-read"
```
resource "aws_s3_bucket" "www_codecademy_dev" {
      ~ acl                         = "public" -> "public-read"
```
The bucket was actually public so running apply gives me
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```
### Steps to Reproduce
Create a s3 bucket with "public" as the acl

1. `terraform apply`

### References

* #0000

**Comment by gdavison** [comment]
Thanks for raising this issue, @NikolaeVarius. We missed adding validation to that field.
