### ISSUE TITLE
Workspaces error handling should include ErrorCode, not just ErrorMessage

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#15317]
Workspaces API operations on a Workspace return an array of failed requests. These are structured similarly to an `awserr.Error`, containing both `ErrorCode` and `ErrorMessage`.

Error handling should take the `ErrorCode` into account. At minimum, the `ErrorCode` should be output in error messages. The `ErrorCode` can also be used for handling specific error cases.

### Affected Resource

* aws_workspaces_workspace

**Comment by Tensho** [comment]
@gdavison My pleasure to fix error handling for WorkSpaces service resource. Please could you refer me to other example service, which handles errors correctly?

**Comment by gdavison** [comment]
We mostly use functions like `tfawserr.ErrCodeEquals()` and `tfawserr.ErrMessageContains()` to check the error codes and messages from AWS API errors. The API errors are all returned as the `awserr.Error` type, which have the functions `Code()` and `Message()`. When printed, the errors are formatted as `<Code()>: <Message()>`.

For example, `tfawserr.ErrCodeEquals()` is implemented as:

```go
func ErrCodeEquals(err error, code string) bool {
	var awsErr awserr.Error
	if errors.As(err, &awsErr) {
		return awsErr.Code() == code
	}
	return false
}
```

In addition, older code, such as `aws_autoscaling_group`'s `getAwsAutoscalingGroup()` makes calls such as

```go
autoscalingerr, ok := err.(awserr.Error)
if ok && autoscalingerr.Code() == "InvalidGroup.NotFound" {
	return nil, nil
}
```

Many of the Workspaces API functions return a `FailedRequests` which contain `ErrorCode` and `ErrorMessage` fields. e.g. `CreateWorkspacesOutput.FailedRequests` has the type `[]*workspaces.FailedCreateWorkspaceRequest`.

The `ErrorCode` and `ErrorMessage` fields are equivalent to the `Code()` and `Message()` calls on `awserr.Error`, so when outputting the failure information for a request, it should be formatted as `<ErrorCode>: <ErrorMessage>`. Depending the the value of `ErrorCode`, we may also be able to provide more context or even retry the operation.

So far, the `CreateWorkspaces()` and `TerminateWorkspaces()` API calls are the calls which return `FailedRequests` in the provider.

If there are more than one `FailedRequests` returned, they should probably all be added to the error message, as well.
