### ISSUE TITLE
Add Service Catalog resources

### ISSUE THREAD

**Issue by ahgittin** [hashicorp/terraform-provider-aws#15369]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Service Catalog is an important service especially for large companies who want to make certain deployment patterns available to end-users.  Recently support has been developed that allows SC to deploy Terraform-based deployments (https://aws.amazon.com/blogs/apn/using-terraform-to-manage-aws-programmable-infrastructures/), and it would be helpful to complete the capabilities for those who use Terraform and Service Catalog to be able to _create_ their SC estate using Terraform.

Support in this provider for the AWS SC resources would permit that.

### New or Affected Resource(s)

* `aws_servicecatalog_portfolio_principal_association`
* `aws_servicecatalog_portfolio_product_association`
* `aws_servicecatalog_product`
* `aws_servicecatalog_provisioned_product`

### Potential Terraform Configuration

Example for a product (assuming buckets etc exist):

```hcl
resource "aws_servicecatalog_product" "demo" {
  name                = "product-tfprov-demo-123"
  product_type        = "CLOUD_FORMATION_TEMPLATE"

  owner               = "Cloudsoft"
  support_email       = "info@cloudsoft.io"
  support_url         = "http://cloudsoft.io"

  provisioning_artifact {
    description = "v1"
    name        = "pa-tfprov-demo-123"
    info = {
      LoadTemplateFromURL = "https://s3.amazonaws.com/${aws_s3_bucket.bucket.id}/${aws_s3_bucket_object.tfprov-demo-template.key}"
    }
  }
}
```

### References

Early work (from 2 years ago) was done in PR #4980, but both TF and AWS have evolved since then, and more is needed on top of that work.  We have integrated that work in new PRs which are now available as follows:

* #13834 - **SC Product** - adds ability to define an `aws_servicecatalog_product`; this PR is long because we've tried to include/credit the pre-existing #4980
* #13866 - **SC Portfolio** - address minor items of consistency and technical debt in the existing `aws_servicecatalog_portfolio` resource (make tests consistent with current best practices)
* #13837 - **SC PortfolioPrincipalAssociation** - adds the `aws_servicecatalog_portfolio_principal_association` needed to allow things in portfolios to be provisioned
* #13864 - **SC PortfolioProductAssociation** - adds the `aws_servicecatalog_portfolio_product_association` needed to put products in portfolios (builds on #13834)
* #13797 - **SC Provisioned Product** - adds the `aws_servicecatalog_provisioned_product`, the ability to provision a product; builds on all the above because we need all those resources as scaffolding to be able to test this one
* #14281 - **SC Constraints** - adds the various constraint resources (builds on #13797, again for testing)

These are designed so they can be reviewed and merged in the sequence, with the latter ones using the functionality of the former in their tests to be able to test the complete functionality (creating portfolios and products, then provisioning a product).  Many review comments have been addressed, with the full battery of standard tests implemented, and we expect it will be a small job to review and merge despite the comparative large size of some.

This issue can be used to track progress on the set of PRs above.

**Comment by ahgittin** [comment]
All PRs above have been updated as per the 18 Aug notifications to use the v2 sdk and remove `aws.erb` (fixing the conflicts), and also updating to conform to the stricter markdown checks.

They appear to be passing all checks apart from unrelated `go test` failures (in the aws_vpc resource, not touched by this work).

All tests confirmed passing - `make testacc TESTARGS='-run=TestAccAWSServiceCatalog'` with all the above merged.

**Comment by jcmcken** [comment]
Are any of these in scope for this issue?

* Provisioning a product (vs creating one): https://docs.aws.amazon.com/servicecatalog/latest/dg/API_ProvisionProduct.html
* Looking up a product or other items as data sources

**Comment by breathingdust** [comment]
Closing as initial support for Service Catalog has been completed!
