### ISSUE TITLE
Postgres aurora cluster instance deleted when trying to upgrade postgres version

### ISSUE THREAD

**Issue by jsyrjala** [hashicorp/terraform-provider-aws#15377]
I tried to upgrade Aurora Postgres cluster from version 11.6 to 11.8. Terraform failed when deploying, and destroyed the instance.

```
Error: Provider produced inconsistent final plan

When expanding the plan for aws_rds_cluster_instance.my-db to
include new values learned so far during apply, provider
"registry.terraform.io/-/aws" produced an invalid new value for
.engine_version: was cty.StringVal("11.8"), but now cty.StringVal("11.6").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.12.29
+ provider.aws v2.70.0

Your version of Terraform is out of date! The latest version
is 0.13.3. You can update by downloading from https://www.terraform.io/downloads.html
```
### Affected Resource(s)

* aws_rds_cluster
* aws_rds_cluster_instance

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Terraform should either upgrade database version as requested, or fail without deleting instances.

### Actual Behavior

Terraform failed and deleted aws_rds_cluster_instance

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by takkyuuplayer** [comment]
I found a workaround. I used aurora-mysql but hope it works in aurora-postgres, too.

## Workaround

```rds.tf
resource "aws_rds_cluster" "aurora_cluster" {
  engine = "aurora-mysql"
  engine_version = "5.7.mysql_aurora.2.09.2"
  apply_immediately = true
  // ...other params.
}

resource "aws_rds_cluster_instance" "aurora_cluster_instances" {
  count = 2
  engine = aws_rds_cluster.aurora_cluster.engine
  engine_version = aws_rds_cluster.aurora_cluster.engine_version

  // The instance's engine version follows the cluster version, so ignore the change.
  lifecycle {
    ignore_changes = [engine_version]
  } 
  // ...other params
}
```

then, run

```
$ terraform apply
$ terraform refresh
```
