### ISSUE TITLE
Error: error deleting CloudWatch Event Rule

### ISSUE THREAD

**Issue by blake-enyart** [hashicorp/terraform-provider-aws#15376]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/aws v3.8.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/template v2.1.2

### Affected Resource(s)

* aws_cloudwatch_event_rule.on_aws_events-event
* aws_cloudwatch_event_rule.every_two_minutes-event
* aws_cloudwatch_event_rule.every_minute-event

### Terraform Configuration Files

```hcl
     ...
    {
      "mode": "managed",
      "type": "aws_cloudwatch_event_rule",
      "name": "every_minute-event",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "arn": "arn:aws:events:us-east-2:828630395474:rule/every_minute-event",
            "description": "",
            "event_pattern": null,
            "id": "every_minute-event",
            "is_enabled": true,
            "name": "every_minute-event",
            "name_prefix": null,
            "role_arn": "",
            "schedule_expression": "rate(1 minute)",
            "tags": {
                   ...
            }
          }
        }
      ]
    },
    {
      "mode": "managed",
      "type": "aws_cloudwatch_event_rule",
      "name": "every_two_minutes-event",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "arn": "arn:aws:events:us-east-2:828630395474:rule/every_two_minutes-event",
            "description": "",
            "event_pattern": null,
            "id": "every_two_minutes-event",
            "is_enabled": true,
            "name": "every_two_minutes-event",
            "name_prefix": null,
            "role_arn": "",
            "schedule_expression": "rate(2 minutes)",
            "tags": {
                   ...
            }
          }
        }
      ]
    },
    {
      "mode": "managed",
      "type": "aws_cloudwatch_event_rule",
      "name": "on_aws_events-event",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "arn": "arn:aws:events:us-east-2:828630395474:rule/on_aws_events-event",
            "description": "",
            "event_pattern": "{\"source\":[\"aws.events\"]}",
            "id": "on_aws_events-event",
            "is_enabled": true,
            "name": "on_aws_events-event",
            "name_prefix": null,
            "role_arn": "",
            "schedule_expression": "",
            "tags": {
                   ...
            }
          }
        }
      ],
    ...
```

NOTE: If the rest of the configuration file is needed I can send it, but there is only a CFN stack managed in the state as well which is note associated with the CW Rules that I am currently attempting to destroy in this effort

### Debug Output

* https://gist.github.com/blake-enyart/aa8196b1f6dba0319afcb4a7ec7fece9

### Panic Output

N/A

### Expected Behavior

Removal of CW rules

### Actual Behavior

CW rules persisted

### Steps to Reproduce

1. `terraform destroy -target=aws_cloudwatch_event_rule.on_aws_events-event`

NOTE: I was able to have the system fail in multiple ways such as `apply` and target resources scheduled to be removed

### Important Factoids

Nothing of note. This issue seems to be persistent in the Terraform AWS provider as indicated in the issues linked below

### References

* https://github.com/terraform-providers/terraform-provider-aws/issues/1479
* https://github.com/hashicorp/terraform/issues/15863

**Comment by gdavison** [comment]
Thanks for raising this issue, @blake-enyart. You've included the Terraform state, which gives us some good information, but if you include the Terraform configuration `.tf` files, that would be more helpful.

Is this happening during a `terraform apply` or a `terraform destroy` operation?

**Comment by gdavison** [comment]
Hi @blake-enyart, I've re-read your issue, and I misread it the first time.

The `aws_cloudwatch_event_rule` is not being deleted because it has `aws_cloudwatch_event_target`s associated with it. Are the Targets also defined in your Terraform configuration? Being able to view the configuration would help here.

Running `terraform destroy` with `-target` is supposed to delete dependencies of the `-target` resource as well, so if the `aws_cloudwatch_event_target` resources are defined in your Terraform configuration, it is an error in the `terraform` cli tool if they are not deleted. However, if they are not defined in your configuration, Terraform will not be able to detect them.

**Comment by gdavison** [comment]
Hi @blake-enyart, I haven't heard back from you, so hopefully this has been resolved. If you're still encountering the issue, please submit a new issue. If you do submit a new issue, please include the Terraform configuration that causes the issue.

**Comment by blake-enyart** [comment]
Hi @gdavison I apologize for losing track of this. Can I reopen this once I dig up the old configuration file?

**Comment by gdavison** [comment]
For sure
