### ISSUE TITLE
Support AWS Data Pipeline

### ISSUE THREAD

**Issue by petterl** [hashicorp/terraform-provider-aws#1538]
It would be nice to be able to use AWS Data Pipeline with Terraform.
We are using it for dumping data from RDS to S3 every night.

http://docs.aws.amazon.com/datapipeline/latest/APIReference/Welcome.html

I need ability to create: 
 - S3DataNode
    - CSVDataFormat
    - TSVDataFormat
 - SqlDataNode
    - RdsDatabase
 - CopyActivity
    - Ec2Resource

Similar issue in core before split: hashicorp/terraform#4077

**Comment by cep21** [comment]
Supporting the nodes may be too much at first.  What about starting with JSON import/export of the pipeline definition.

**Comment by armanshan12** [comment]
Any updates on this?

**Comment by Constantin07** [comment]
@petterl do you have any status updates on this ?

**Comment by scraly** [comment]
Hi,
we terraformed EMR and EMR steps but now we need to terraform aws data pipeline which should schedule emr.
How can we do that?
When it will be possible to terraform data pipeline resources?
Thanks.

**Comment by djk29a** [comment]
You can deploy data pipelines via Terraform by using [CloudFormation stacks to create data pipelines](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-datapipeline-pipeline.html). Note that data pipelines in use (especially in "deactivating" state) can be very unstable in their provisioning states and can oftentimes fail to delete after several minutes of no feedback. This will result in a CloudFormation rollback or a stack creation that may require you to clean up the CF stack.

**Comment by dvopsway** [comment]
+1 Any updates on this?

**Comment by nolancash** [comment]
It looks like this is pretty close to being done. Do we know how long till this will be released?

**Comment by scottpazelt** [comment]
Is there any update on when this will be available?
Thanks.

**Comment by dave2535** [comment]
following

**Comment by scottpazelt** [comment]
@nolancash are you aware of any timing on this?

**Comment by nolancash** [comment]
@scottpazelt I have no connection to hashicorp and thus have no info.

**Comment by Szasza** [comment]
@bflad now that TF 0.12 is released, could this PR get some attention please?

Thank you in advance for your time.

**Comment by bflad** [comment]
The first piece of functionality here, the `aws_datapipeline_pipeline` resource has been released in [version 2.19.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2190-july-11-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For further feature requests or bug reports with this new resource, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!

**Comment by tbugfinder** [comment]
Current resource implementation seems to be very basic. Would any options be added to it soon ish?

**Comment by kevintvh** [comment]
Any update on the release time frame support please?

**Comment by dotnetooo** [comment]
same question here. is the resource going to be available any time soon?

**Comment by breathingdust** [comment]
Closed via #22597
