### ISSUE TITLE
Adding the certificate's CN as a SAN forces a destroy/create on every plan/apply

### ISSUE THREAD

**Issue by jameshopkins** [hashicorp/terraform-provider-aws#15381]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

`Terraform 0.13.3`
`provider registry.terraform.io/hashicorp/aws v3.8.0`

### Affected Resource(s)

* `aws_acm_certificate`

### Terraform Configuration Files

```hcl
resource "aws_acm_certificate" "default" {
  domain_name = "james.com"
  validation_method = "DNS"
  subject_alternative_names = [
    "james.com",
    "foo.com"
  ]
}
```

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

The presence of the CN as a SAN, should be a no-op on `plan`/`apply` if the SAN entry already exists in the ACM certificate resource's Terraform state. It should not recreate the certificate

### Actual Behavior

It re-creates the certificates on every `apply`, even though no resource configuration has changed.

### Steps to Reproduce

1. `terraform apply`

### References

Vaguely similar to https://github.com/terraform-providers/terraform-provider-aws/issues/13317

**Comment by toddlucas** [comment]
It appears that Terraform will always add the CN (`domain_name` argument) to the SAN list. The associated entries in `domain_validation_options`, etc. will be there as expected. If you explicitly list the CN it in the `subject_alternative_names` list argument, it will cause Terraform to see the SAN as different, which results in a replacement action.

**Comment by jameshopkins** [comment]
> The documentation should at least be updated if this is the expected behavior, since it's different than the actual underlying subjectAltName record and the way other tools handle the SAN

Yes I agree. The confusion here is between the [explicitness of the X509 spec](https://blog.confirm.ch/ssl-certificates-with-subjectalternativename-san/), and the abstractions that tools like the ACM API provide. Since the ACM API doesn't currently document this, I've submitted [feedback to their documentation team](https://docs-feedback.aws.amazon.com/feedback.jsp?hidden_service_name=AWS%20Command%20Line%20Interface&hidden_guide_name=Reference}&topic_url=https%3A%2F%2Fdocs.aws.amazon.com%2Fcli%2Flatest%2Freference/acm/request-certificate.html).
