### ISSUE TITLE
aws_ec2_transit_gateway support update of parameters

### ISSUE THREAD

**Issue by CliffHoogervorst** [hashicorp/terraform-provider-aws#15380]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has (silently) released the option to change almost all parameters of the Transit Gateway (aws_ec2_transit_gateway)  https://docs.aws.amazon.com/cli/latest/reference/ec2/modify-transit-gateway.html

Would be great if TF supports this instead of destroy-create the TGW. 

### New or Affected Resource(s)

* aws_ec2_transit_gateway

### Potential Terraform Configuration

no changes

### References

https://docs.aws.amazon.com/cli/latest/reference/ec2/modify-transit-gateway.html
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyTransitGateway.html

**Comment by raut02a** [comment]
Definitely needs this enhancement.

**Comment by philnichol** [comment]
I'd like to give this a go if that's alright?

**Comment by bflad** [comment]
Support for this has been merged and will release with version 3.15.0 of the Terraform AWS Provider, which will release today or tomorrow. Thanks to @philnichol for the implementation. 👍
