### ISSUE TITLE
Add Organizations policy data source

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#15398]
### Description

Add a data source for Organization policy. Allow lookup by name or ARN.

### New Data Source

* aws_organizations_policy

### Data Source Configuration

* `name`: String, `ExactlyOneOf: []string{"name", "arn"}`, Computed
* `arn`: String, `ExactlyOneOf: []string{"name", "arn"}`, Computed

Outputs:

* `content`: String
* `description`: String
* `type`: String
* `tags`: Map, cannot be read from AWS-managed policies

### References

* #15347

**Comment by l1x** [comment]
This would be really nice.

**Comment by brunosalvatico** [comment]
This would be great to have for one of my projects where I need to look up if an SCP already exists

**Comment by Kostoprav19** [comment]
Also interseted
