### ISSUE TITLE
resource/aws_datasync_location_s3: Add agent_arns and s3_storage_class arguments

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#15418]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As part of the [initial S3 on Outposts support for the Terraform AWS Provider](https://github.com/terraform-providers/terraform-provider-aws/issues/15412), enhancements to the `aws_datasync_location_s3` resource are necessary.

### Existing Resource

* aws_datasync_location_s3

### Potential Terraform Configuration

```hcl
resource "aws_datasync_location_s3" "outposts" {
  agent_arns    = [aws_datasync_agent.example.arn]
  s3_bucket_arn = aws_s3_access_point.example.arn
  subdirectory  = "/"

  s3_config {
    bucket_access_role_arn = aws_iam_role.example.arn
  }
}
```

### References

* [Feature Request: S3 on Outposts Support](https://github.com/terraform-providers/terraform-provider-aws/issues/15412)
* [New Resource: aws_s3control_bucket](https://github.com/terraform-providers/terraform-provider-aws/issues/15413)
* [Update module aws/aws-sdk-go to v1.35.0](https://github.com/terraform-providers/terraform-provider-aws/pull/15226)
* [DataSync API Reference](https://docs.aws.amazon.com/datasync/latest/userguide/API_Operations.html)
* [AWS Go SDK v1.35.0](https://github.com/aws/aws-sdk-go/releases/tag/v1.35.0)
* [AWS Go SDK service/datasync](https://docs.aws.amazon.com/sdk-for-go/api/service/datasync/)

**Comment by olgakogan** [comment]
Awesome! Note that for S3 on Outposts, DataSync only supports S3 Access Points, so the bucket ARN is an Acces Point ARN

**Comment by bflad** [comment]
Good catch, @olgakogan! Will update the example.

**Comment by cesarpball** [comment]
Do we have any update about **_s3_storage_class_** property? 
Using local-exec to update the location is not an option as we can't do even in the AWS Console

**Comment by ewbankkit** [comment]
Related:

* https://github.com/hashicorp/terraform-provider-aws/issues/19191
