### ISSUE TITLE
New Resource: aws_timestreamwrite_table

### ISSUE THREAD

**Issue by yardensachs** [hashicorp/terraform-provider-aws#15422]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon Timestream is now generally available, and a supporting Terraform resource for managing a table is necessary. [Amazon Timestream](https://docs.aws.amazon.com/timestream/latest/developerguide/what-is-timestream.html) is a fast, scalable, fully managed, purpose-built time series database.
(#15421 was created for `aws_timestreamwrite_database`)

### New or Affected Resource(s)

* aws_timestreamwrite_table

### Potential Terraform Configuration

```hcl
resource "aws_timestreamwrite_table" "example" {
  database_name = aws_timestreamwrite_database.database_name
  table_name    = "string"
  retention_properties {
    magnetic_store_retention_period_in_days = 10
    memory_store_retention_period_in_hours  = 10
  }
  tags = {
    Name = "value"
  }
}
```

- `database_name` (string) -- The name of the Timestream database.
- `table_name` (string) -- The name of the Timestream table.
- `retention_properties.magnetic_store_retention_period_in_days` (int) -- The duration for which data must be stored in the magnetic store.
- `retention_properties.memory_store_retention_period_in_hours` (int) -- The duration for which data must be stored in the memory store.

### References

* #15421 - `aws_timestreamwrite_database`
* https://aws.amazon.com/about-aws/whats-new/2020/09/amazon-timestream-now-generally-available/
* https://docs.aws.amazon.com/timestream/latest/developerguide/what-is-timestream.html
* https://docs.aws.amazon.com/timestream/latest/developerguide/getting-started.go.code-samples.create-table.html
* https://github.com/awslabs/amazon-timestream-tools/tree/master/sample_apps
* https://github.com/aws/aws-sdk-go/tree/master/service/timestreamwrite
* https://github.com/aws/aws-sdk-go/blob/master/service/timestreamwrite/api.go#L2254-L2273 (this is the code, because API docs are still missing)

**Comment by roberth-k** [comment]
API documentation is part of the Developer Guide: https://docs.aws.amazon.com/timestream/latest/developerguide/API_Reference.html.

**Comment by ewbankkit** [comment]
Strictly, this resource should be named `aws_timestreamwrite_table` to match the AWS service name and the [resource naming conventions](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/contributing/contribution-checklists.md#new-resource).
AWS call the underlying API the _Timestream Write API_.

**Comment by yardensachs** [comment]
@ewbankkit Updated

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.34.34](https://github.com/aws/aws-sdk-go/releases/tag/v1.34.34):

* https://github.com/terraform-providers/terraform-provider-aws/pull/15226

**Comment by shuheiktgw** [comment]
Let me work on this issue if anyone else does

**Comment by TomTucka** [comment]
I started working on this, should have a PR open by tomorrow evening 🙂

**Comment by yardensachs** [comment]
Hi @TomTucka 
I have a draft branch for tables waiting, but I cant finish it before the team reviews #15463
Because you would need a database first anyway for testing

**Comment by yardensachs** [comment]
Hi @TomTucka thanks!
I have a draft branch for tables waiting and ready actually, but I cant finish it before the team reviews #15463
Because you would need a database first anyway for testing

**Comment by dusansusic** [comment]
Is there any timeframe when this could to be merged?

**Comment by yardensachs** [comment]
@ivanovit looks like I lost that branch for some reason, so I don't have that work anymore :(
