### ISSUE TITLE
New Resource: aws_timestreamwrite_database

### ISSUE THREAD

**Issue by yardensachs** [hashicorp/terraform-provider-aws#15421]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon Timestream is now generally available, and a supporting Terraform resource for managing a database is necessary. [Amazon Timestream](https://docs.aws.amazon.com/timestream/latest/developerguide/what-is-timestream.html) is a fast, scalable, fully managed, purpose-built time series database.

### New or Affected Resource(s)

* aws_timestreamwrite_database

### Potential Terraform Configuration

```hcl
resource "aws_timestreamwrite_database" "example" {
  database_name = "string"
  kms_key_id    = "string"
  tags = {
      Name = "value"
  }
}
```

- `database_name` (string) -- The name of the Timestream database.
- `kms_key_id` (string, optional) -- The KMS key for the database. If the KMS key is not specified, the database will be encrypted with a Timestream managed KMS key located in your account. (#15422 was created for aws_timestream_table)

### References

* #15422 - `aws_timestreamwrite_table`
* https://aws.amazon.com/about-aws/whats-new/2020/09/amazon-timestream-now-generally-available/
* https://docs.aws.amazon.com/timestream/latest/developerguide/what-is-timestream.html
* https://docs.aws.amazon.com/timestream/latest/developerguide/getting-started.go.code-samples.create-database.html
* https://github.com/awslabs/amazon-timestream-tools/tree/master/sample_apps
* https://github.com/aws/aws-sdk-go/tree/master/service/timestreamwrite
* https://github.com/aws/aws-sdk-go/blob/master/service/timestreamwrite/api.go#L2156-L2172 (this is the code, because API docs are still missing)

**Comment by roberth-k** [comment]
API documentation is part of the Developer Guide: https://docs.aws.amazon.com/timestream/latest/developerguide/API_Reference.html.

**Comment by ewbankkit** [comment]
Strictly this resource should be named `aws_timestreamwrite_database` to match the AWS service name and the [resource naming conventions](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/contributing/contribution-checklists.md#new-resource).
AWS call the underlying API the _Timestream Write API_.

**Comment by yardensachs** [comment]
@ewbankkit Updated

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.34.34](https://github.com/aws/aws-sdk-go/releases/tag/v1.34.34):

* https://github.com/terraform-providers/terraform-provider-aws/pull/15226

**Comment by mattyev87** [comment]
any update when this will be merged in and made available?
