### ISSUE TITLE
Support X-Ray Tracing Config for Step Functions

### ISSUE THREAD

**Issue by jdunnaway** [hashicorp/terraform-provider-aws#15430]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS recently released X-Ray tracing for Step Functions (see [here](https://aws.amazon.com/about-aws/whats-new/2020/09/aws-step-functions-adds-support-for-aws-x-ray/)). The aws_sfn_state_machine resource should provide support for this attribute.

### New or Affected Resource(s)

* aws_sfn_state_machine

### Potential Terraform Configuration

```hcl
resource "aws_sfn_state_machine" "sfn_state_machine" {
  name     = "state_machine_name"
  role_arn = "role_arn"
  definition = "definition"
  tracing_config {
    enabled = true
  }
}
```

**Comment by lu-liu-rft** [comment]
Hi any update on this? Or is there any workaround to enable x-ray tracing for stepfunction in Terraform?

**Comment by vatima2016** [comment]
> Or is there any workaround to enable x-ray tracing for stepfunction in Terraform?

Yes, here: https://github.com/hashicorp/terraform-provider-aws/issues/12192
Look for `--tracing-configuration enabled=true`
