### ISSUE TITLE
Secure Environment Entries from OpsWorks Applications are being displayed on plan

### ISSUE THREAD

**Issue by hc-danieltiziani** [hashicorp/terraform-provider-aws#15447]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/aws v3.8.0

### Affected Resource(s)

* aws_opsworks_application

### Terraform Configuration Files

```hcl
resource "aws_opsworks_application" "app" {
  stack_id = var.STACK_ID
  name        = var.APP_NAME
  short_name  = var.APP_SHORT_NAME
  description = var.APP_DESCRIPTION
    type        = "other"

  app_source {
    type = var.APP_SOURCE_TYPE
    url  = var.APP_SOURCE_URL
  }

  domains = []

  environment {
    key    = "KEY_NAME"
    value  = data.aws_ssm_parameter.secret.secret_key.value
    secure = secure
  }
}
```

### Debug Output
```hcl
Plan Result

resource "aws_opsworks_application" "app" {
      ~ description = ""
        domains     = []
        enable_ssl  = false
        id          = ""
        name        = ""
        short_name  = ""
        stack_id    = ""
        type        = "other"

       environment {
            key    = "KEY_NAME"
            secure = true
            value  = "SECRET VALUE"
        }
}
```

### Expected Behavior

Not display the real value of SECURE Environment entry on the plan

### Actual Behavior
Is displaying in plain text the whole value that will be added/updated.
I'm retrieving the value from my Secret Manager and expected for it to not be displayed on the plan IF the `secure` flag is true for the entry.

**Comment by bflad** [comment]
Hi @hc-danieltiziani 👋  Thank you for raising this.

Terraform Providers do not currently have a way through the Terraform Plugin SDK to conditionally signal whether a particular attribute is sensitive to Terraform core. I will need to check upstream in [that repository](https://github.com/hashicorp/terraform-plugin-sdk/issues) to see if this is already captured as a feature request.

Our only current option would be to always mark `value` as `Sensitive: true` in the resource schema, which would always obfuscate the value even for "insecure" values.

**Comment by hc-danieltiziani** [comment]
Is this a possibility (marking always as Sensitive?) for all then?
Because I'm storing those in AWS SSM as secure, so it makes sense for me, but just wanted to check this.

Thanks!
