### ISSUE TITLE
r/aws_s3_bucket_object: Remove "bucket" from resource name

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#15458]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`aws_s3_bucket_object` should be called `aws_s3_object` because:
1. "bucket" does not add information since every S3 object exists in a bucket: "S3 bucket object" does not convey more information or improve clarity over "S3 object"
2. Extraneous words are verbose
3. Removing "bucket" aligns the AWS provider with the API which never uses "bucket object"

All AWS SDK Go "object" operations none of which has "bucket object":

```
CopyObject	
DeleteObject	
DeleteObjectTagging	
DeleteObjects	
GetObject	
GetObjectAcl	
GetObjectLegalHold	
GetObjectLockConfiguration	
GetObjectRetention	
GetObjectTagging	
GetObjectTorrent	
HeadObject	
ListObjects
ListObjectsV2
PutObject	
PutObjectAcl	
PutObjectLegalHold	
PutObjectLockConfiguration	
PutObjectRetention	
PutObjectTagging	
RestoreObject	
SelectObjectContent	
```

### New or Affected Resource(s)

* aws_s3_bucket_object

### Potential Terraform Configuration

```hcl
resource "aws_s3_object" "object" {
  bucket = aws_s3_bucket.test.bucket
  key    = "nyckeln"
}
```

### References

* [AWS S3 API](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/)

**Comment by ewbankkit** [comment]
What about adding an `aws_s3_object_version` resource?
In a versioned S3 bucket `aws_s3_object` represents the _latest_ version of the object and there are cases when it would be useful to manage a specific version.
One downside is that it will be confusing to have both `aws_s3_object` and `aws_s3_object_version` resources that potentially manage the same S3 object.
