### ISSUE TITLE
cross account cross region transit gateway acceptor fails

### ISSUE THREAD

**Issue by waheedshahani** [hashicorp/terraform-provider-aws#15487]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_ec2_transit_gateway_peering_attachment_accepter

### Terraform Configuration Files

```hcl
resource "aws_ec2_transit_gateway_peering_attachment_accepter" "example" {
  provider = aws.XXX
  transit_gateway_attachment_id = ############

  tags = {
    Name = peering_name
    Side = "Accepter"
  }
  
}
```

### Debug Output

```
module.cust-aws.module.transit_gateway[0].aws_ec2_transit_gateway_peering_attachment_accepter.cis-tgw-accepter: Still creating... [3m0s elapsed]

Warning: Applied changes may be incomplete

Error: error waiting for EC2 Transit Gateway Peering Attachment (tgw-attach-06af003b09f92dfbc) availability: couldn't find resource (21 retries)
```
### Expected Behavior
The Accepter side of peering should change status from "pending acceptance" to "available" before terraform reports a failed attempt.
### Actual Behavior

As AWS takes longer to change status from "pending acceptance" to "Available", TF fails. 
This also means that TF retry attempts are low or timeout is low for such resource. 

### Steps to Reproduce
 Use cross account , cross region TGW peering and acceptor resource to reproduce the issue. 
Run terraform apply
It will fail
Wait few minutes and you will see AWS console changing status from "pending acceptance" to "available" however terraform has already failed and doesn't know this state. 
Next terraform run will fail with incorrect state.

1. `terraform apply`

### Important Factoids

I am doing cross account cross region transit gateway peering.
### References
#0000

**Comment by joneteus** [comment]
I faced the same issue with cross-region TGW peering within one AWS account. @waheedshahani Did you figure out any workaround?
