### ISSUE TITLE
Unable to import ICMPv6 aws_security_group_rule resources

### ISSUE THREAD

**Issue by theseanhodges** [hashicorp/terraform-provider-aws#15501]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.4
+ provider registry.terraform.io/-/aws v3.9.0
+ provider registry.terraform.io/hashicorp/aws v3.9.0
```

### Affected Resource(s)

* aws_security_group_rule

### Terraform Configuration Files

```hcl
resource "aws_security_group_rule" "security_group_rule" {
  security_group_id = aws_security_group.security_group.id
  description       = "Allow IPv6 ICMP"
  type              = "ingress"
  from_port         = -1
  to_port           = -1
  protocol          = "icmpv6"
  ipv6_cidr_blocks  = ["::/0"]
}
```

### Debug Output

```
Error: unexpected format of import string ("sg-redacted_ingress_icmpv6_-1_-1_::/0"), expected SECURITYGROUPID_TYPE_PROTOCOL_FROMPORT_TOPORT_SOURCE[_SOURCE]*: protocol must be tcp/udp/icmp/all or a number
```

### Expected Behavior

Existing AWS Security Group rule should have been imported to Terraform state.  As shown when querying with boto3:
```python
{'FromPort': -1, 'IpProtocol': 'icmpv6', 'IpRanges': [], 'Ipv6Ranges': [{'CidrIpv6': '::/0', 'Description': 'Allow IPv6 ICMP'}], 'PrefixListIds': [], 'ToPort': -1, 'UserIdGroupPairs': []}
```

### Actual Behavior

Terraform was unable to find the existing rule.

```
Error: unexpected format of import string ("sg-redacted_ingress_icmpv6_-1_-1_::/0"), expected SECURITYGROUPID_TYPE_PROTOCOL_FROMPORT_TOPORT_SOURCE[_SOURCE]*: protocol must be tcp/udp/icmp/all or a number
```

### Steps to Reproduce

1. `terraform init -reconfigure`
2. `terraform import module.security_groups.aws_security_group_rule.security_group_rule sg-redacted_ingress_icmpv6_-1_-1_::/0`

### References

* Per [Terraform Registry: aws_security_group_rule](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule), the protocol should be `icmpv6`, but there's no `imcpv6` option mentioned in the import section.
* In the [validation function](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_security_group_rule.go#L945..L997), only tcp/udp/icmp/all are [valid protocols](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_security_group.go#L1396)
  - Does this perhaps need to be expanded to include `icmpv6` since the AWS CLI internals appear to use that protocol?

**Comment by anGie44** [comment]
Hi @theseanhodges, thank you for creating this issues and apologies you came across this error! Since there isn't an `icmpv6` option, it looks like an alternative at import time could be to explicitly pass the IANA protocol number. I would try passing `58` instead. Let me know if this workaround works as expected!

**Comment by theseanhodges** [comment]
Hi @anGie44 , so sorry for the delay -- I forgot to actually follow up here it seems.  No luck with Terraform 0.13.4 and AWS Provider 3.9.0 (same error).  Please let me know if I can provide any further information.

**Comment by dacut** [comment]
Passing the protocol number doesn't help here. Looks like the root of the issue is an API change made by AWS, where they're now reporting the protocol as `icmpv6` in the XML (along with some odd indentation errors, but only for ICMPv6 rules):

```
<DescribeSecurityGroupsResponse xmlns="http://ec2.amazonaws.com/doc/2016-11-15/">
    <requestId>515f8068-042f-46bd-9195-e06f4be58395</requestId>
    <securityGroupInfo>
        <item>
            <ownerId>0123456789012</ownerId>
            <groupId>sg-01234567890abcdef</groupId>
            <groupName>MySecurityGroup</groupName>
            <groupDescription>Security group description</groupDescription>
            <vpcId>vpc-01234567890abcdef</vpcId>
            <ipPermissions>
                <item>
                    <ipProtocol>tcp</ipProtocol>
                    <fromPort>80</fromPort>
                    <toPort>80</toPort>
                    <groups>
                        <item>
                            <userId>0123456789012</userId>
                            <groupId>sg-0aabbccddeeff0011</groupId>
                            <description>HTTP from load balancer</description>
                        </item>
                    </groups>
                    <ipRanges/>
                    <ipv6Ranges/>
                    <prefixListIds/>
                </item>
...
            <item>
                    <ipProtocol>icmpv6</ipProtocol>
                    <fromPort>-1</fromPort>
                    <toPort>-1</toPort>
                    <groups/>
                    <ipRanges/>
                    <ipv6Ranges>
                        <item>
                            <cidrIpv6>2001:db8:1::/56</cidrIpv6>
                            <description>Internal ICMPv6</description>
                        </item>
                        <item>
                            <cidrIpv6>2001:db8:7::/56</cidrIpv6>
                            <description>Internal ICMPv6</description>
                        </item>
                    </ipv6Ranges>
                    <prefixListIds/>
                </item>
```
