### ISSUE TITLE
Data resource aws_lambda_invocation invokes lambdas twice

### ISSUE THREAD

**Issue by vladimirtiukhtin** [hashicorp/terraform-provider-aws#15536]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/aws v3.9.0
+ provider registry.terraform.io/hashicorp/random v2.3.0
```

### Affected Resource(s)

* aws_lambda_invocation

### Expected Behavior

Lambda gets invoked once

### Actual Behavior

Lambda gets invoked twice causing lot's of problems

**Comment by VR6Pete** [comment]
Any update on this issue?
