### ISSUE TITLE
Terraform fails to import a CloudTrail with 'Organization Trail' set to true

### ISSUE THREAD

**Issue by dev-e** [hashicorp/terraform-provider-aws#15553]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/aws v3.9.0
```

### Affected Resource(s)

* aws_cloudtrail

### Terraform Configuration Files

```hcl
provider "aws" {
  alias   = "va"
  region  = "us-east-1"
  version = ">= 3.9.0"
}

resource "aws_cloudtrail" "events" {
  provider       = aws.va
  is_organization_trail = true
  name           = "events"
  s3_bucket_name = "events"
}
```

### Expected Behavior

Trail imported

### Actual Behavior

```
$ terraform state import aws_cloudtrail.events events                                    
aws_cloudtrail.events: Importing from ID "events"...
aws_cloudtrail.events: Import prepared!
  Prepared aws_cloudtrail for import
aws_cloudtrail.events: Refreshing state... [id=events]

Error: Cannot import non-existent remote object

While attempting to import an existing object to
aws_cloudtrail.events, the provider detected that no object exists
with the given id. Only pre-existing objects can be imported; check that the
id is correct and that it is associated with the provider's configured region
or endpoint, or use "terraform apply" to create a new remote object for this
resource.

Releasing state lock. This may take a few moments...
```

### Steps to Reproduce

1.  manually create the CloudTrail trail with name trail-organizations
3. set Apply trail to my organization to yes
4. select/create an S3 bucket
5. try to import the resource

### Important Factoids

A trail with `"IsOrganizationTrail": true` cannot be described by the name, only by the arn. However, import relies on `Name` field

```
$ aws cloudtrail describe-trails --trail-name-list='["events"]' --region=us-east-1                                                
{
    "trailList": []
}
$ aws cloudtrail describe-trails --trail-name-list='["arn:aws:cloudtrail:us-east-1:<AWS_ACCOUNT_ID>:trail/events"]' --region=us-east-1
{
    "trailList": [
        {
            "Name": "events",
            "S3BucketName": "events",
            "IncludeGlobalServiceEvents": true,
            "IsMultiRegionTrail": true,
            "HomeRegion": "us-east-1",
            "TrailARN": "arn:aws:cloudtrail:us-east-1:<AWS_ACCOUNT_ID>:trail/events",
            "LogFileValidationEnabled": true,
            "HasCustomEventSelectors": false,
            "HasInsightSelectors": false,
            "IsOrganizationTrail": true
        }
    ]
}
```

### References

* #6561

**Comment by faleon** [comment]
This import function also fails for non-Organization Trails aka regular trails.
