### ISSUE TITLE
support optional request and response mapping templates in appsync resolver

### ISSUE THREAD

**Issue by vchinnakotla** [hashicorp/terraform-provider-aws#15593]
AWS Console or CLI allows me to create a resolver by attaching a datasource without VTL templates (request and response templates)

Terraform doesn't support it yet. I played with TF 0.13.4 with AWS provider 3.10.0.

```
request_template - (Required) The request mapping template for UNIT resolver or 'before mapping template' for PIPELINE resolver.
response_template - (Required) The response mapping template for UNIT resolver or 'after mapping template' for PIPELINE resolver.
```

This feature would allow to ditch my ugly hack that i was doing with local-exec provisioner.

**Comment by luisamador** [comment]
We've just come across the same. We'd like to just disable the usage of VTL templates and it is not supported yet.

![image](https://user-images.githubusercontent.com/18208396/102198532-ca16c700-3ec2-11eb-9f69-2f7ed9bbe9cf.png)

**Comment by Speediing** [comment]
+1

**Comment by freimer** [comment]
I would not categorize this as an enhancement.  I believe the proper tag is bug, as this is clearly supported by AWS, and is particularly useful for direct Lambda functions.

Any info on how to create a custom AWS module to work around this bug until it is fixed would be appreciated.  Anyone have a quick pointer?

**Comment by razki** [comment]
We would like this functionality too. Seems to be a mismatch between AWS and the provider.

**Comment by razki** [comment]
https://github.com/hashicorp/terraform-provider-aws/pull/14710

Looks like this was merged 5 days ago

**Comment by DrFaust92** [comment]
#14710 has addressed this, closing.
if there is still an issue please open a new issue with relevant details.
