### ISSUE TITLE
access multiple AWS ElasticContainerRegistries (ECR)

### ISSUE THREAD

**Issue by maqzee-git** [hashicorp/terraform-provider-aws#15591]
We have close to 100 AWS ECR repos which do not have any lifecycle policy and there's a need to add them through Terraform. I was expecting there would be a filter or some way I can access all ECR repos based on regex or some other manner so I can apply the lifecycle policy on them. I have added my environment and expected terraform config file here, would be really grateful if someone can guide me.

### Affected Resource(s)
Data Resource - aws_ecr_repository

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/aws v3.10.0

### Terraform Configuration Files (Expected)
```
data "aws_ecr_repository" "torid_apps" {
  filter {
    name   = "name"
    values = ["torid/apps/*"]
  }
  name = ""
}

resource "aws_ecr_lifecycle_policy" "cleanupPolicy" {
  for_each = "${data.aws_ecr_repository.torid_apps.name}"
  repository = each.value 
  policy = file("${local.ecrfilesPath}/expire_ecr_lifecycle_policy.json")
}

```

**Comment by gdavison** [comment]
Hi @maqzee-git, thanks for the submitting the issue. Data sources such as `aws_ecr_repository` typically return a single resource, and fail if more than one could be matched. It appears that `aws_ecr_repository` is not failing in this case and is simply returning the first of the returned repositories.

We do have a number of data sources that will return all of the resources matching a query, and we use a plural name for those. In this case it would be `aws_ecr_repositories`. We don't currently have this data source, but it would be a good addition.
