### ISSUE TITLE
security_group_rule: 'self' conflicts with 'cidr_blocks'

### ISSUE THREAD

**Issue by mschuchard** [hashicorp/terraform-provider-aws#15606]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform 0.12.29
AWs Provider: 2.70.0

### Affected Resource(s)

* aws_security_group_rule

### Terraform Configuration Files

```hcl
"aws_security_group_rule" "foo" {
  cidr_blocks = ["1.2.3.4/16", "5.6.7.8/24"]
  self        = true
}
```

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

According to the [documentation](https://github.com/terraform-providers/terraform-provider-aws/blob/v2.70.0/website/docs/r/security_group_rule.html.markdown) for 2.70.0, `source_security_group_id` conflicts with `cidr_blocks` and `self` for arguments. `self` does not conflict with `cidr_blocks`.

### Actual Behavior

> Error: 'self': conflicts with 'cidr_blocks' ([]interface {}{"1.2.3.4/16", "5.6.7.8/24"})

### Steps to Reproduce

`terraform apply`

### Important Factoids

Does not matter to me if this is a bug or documentation issue; I would just like some clarification please and thank you. I could even just easily PR the doc update myself if desired if that is the issue. If that is the issue, I also think the resource should probably also have argument validation added in a similar fashion to how co-specifying `source_security_group_id` with `self` throws an error before CRUD operations: https://github.com/terraform-providers/terraform-provider-aws/blob/v2.70.0/aws/resource_aws_security_group_rule.go#L129

### References

n/a

**Comment by gdavison** [comment]
Thanks for pointing this out, @mschuchard. Yes, `self` is expected to conflict with any of `cidr_blocks`, `ipv6_cidr_blocks`, or `source_security_group_id`. The documentation and schema both need to be updated. I believe the "late validation" is from before we added the validation instructions to the schema.

**Comment by mschuchard** [comment]
Thanks for the clarification. Let me know if there is interest in my doing the PR for this, and I could likely put it together based on your explanation.
