### ISSUE TITLE
"aws_spot_instance_request" ignores "metadata_options" changes

### ISSUE THREAD

**Issue by Roman-Danyk** [hashicorp/terraform-provider-aws#15657]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/aws v3.2.0
```
and the latest version of AWS provider (v3.10.0)

### Affected Resource(s)

* aws_spot_instance_request

### Terraform Configuration Files

```hcl
resource "aws_spot_instance_request" "cheap_worker" {
  ami           = "ami-056114420b6ed624e"
  instance_type = "t3a.micro"

  metadata_options {
    http_endpoint               = "enabled"
    http_tokens                 = "required"
    http_put_response_hop_limit = 1
  }
}
```

### Debug Output

https://gist.github.com/Roman-Danyk/ad08998cd4b2f838072131d0b80f883e

### Expected Behavior

Created spot instance with required Instance Metadata Service v2 usage (`"HttpTokens": "required"`).

```shell
$ aws ec2 describe-instances --instance-ids i-0a8288a4540323c8e --query 'Reservations[].Instances[].MetadataOptions'
[
  {
    "State": "applied",
    "HttpTokens": "required",
    "HttpPutResponseHopLimit": 1,
    "HttpEndpoint": "enabled"
  }

```

### Actual Behavior

Created spot instance has the default `MetadataOptions` parameters (`"HttpTokens": "optional"`):

```shell
$ aws ec2 describe-instances --instance-ids i-0a8288a4540323c8e --query 'Reservations[].Instances[].MetadataOptions'
[
  {
    "State": "applied",
    "HttpTokens": "optional",
    "HttpPutResponseHopLimit": 1,
    "HttpEndpoint": "enabled"
  }
]
```

### Steps to Reproduce

1. `terraform apply`

### Additional information

* If the `metadata_option` section is absent in the `aws_spot_instance_request` resource, Terraform will replace the resource in case of adding this section. However, it's possible to add or update `metadata_options` for `aws_instance` resource in-place.

* Modifying the MetadataOptions with AWS CLI works well:

  ```shell
  $ aws ec2 modify-instance-metadata-options --instance-id i-0a8288a4540323c8e --http-tokens required
  {
      "InstanceId": "i-0a8288a4540323c8e",
      "InstanceMetadataOptions": {
          "State": "pending",
          "HttpTokens": "required",
          "HttpPutResponseHopLimit": 1,
          "HttpEndpoint": "enabled"
      }
  }
  ```

**Comment by gdavison** [comment]
Thanks for reporting this, @Roman-Danyk. It's actually an error that the `aws_spot_instance_request` Terraform resource accepts `metadata_options`, since the underlying Spot Instance API doesn't support setting the metadata options.

I've created #16189 to fix this error.

**Comment by RomanDanyk** [comment]
I'm a bit confused. Does `aws ec2 modify-instance-metadata-options` command use different APIs for regular instances and spot instances?

**Comment by RomanDanyk** [comment]
I got this. Terraform can't modify instance metadata options for spot instances because if fact these resources are created without these options. That's why Terraform replaces the `aws_spot_instance_request` resource in case of adding `metadata_options`.
Here is API Reference [RequestSpotInstances - Amazon Elastic Compute Cloud](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RequestSpotInstances.html).
