### ISSUE TITLE
Acceptance Tests: `TestAccAWSCloudWatchEventTarget_` has intermittent test failures

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#15652]
Various `aws_cloudwatch_event_target` acceptance tests have intermittent failures when deleting Rules, especially `TestAccAWSCloudWatchEventTarget_ecs` and `TestAccAWSCloudWatchEventTarget_ecsWithBlankTaskCount` due to eventual consistency

### Affected Resource

* aws_cloudwatch_event_target

**Comment by gdavison** [comment]
Might be related to #15376

**Comment by ewbankkit** [comment]
This is a duplicate of #18601 and #15668.
