### ISSUE TITLE
MSK support for Zookeeper TLS connection string

### ISSUE THREAD

**Issue by mgusiew-guide** [hashicorp/terraform-provider-aws#15661]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS announced support for Kafka 2.5.1, see https://docs.aws.amazon.com/msk/latest/developerguide/supported-kafka-versions.html 

There is a new ZookeeperConnectStringTls attribute in the DescribeCluster response that enables Zookeeper TLS connectivity

### New or Affected Resource(s)

* aws_msk_cluster resource 
* aws_msk_cluster data source

### Potential Terraform Configuration

Include zookeeper_connect_string_tls in output on the same level as zookeeper_connect_string

There is already similar setup for bootstrap_brokers and bootstrap_brokers_tls

### References

* https://docs.aws.amazon.com/msk/latest/developerguide/supported-kafka-versions.html

**Comment by ameyapanse** [comment]
If this is still open, I'd like to take a shot at this.

**Comment by mgusiew-guide** [comment]
I checked master branch and it looks like the output is still missing so IMHO this is still valid

**Comment by ameyapanse** [comment]
Alright. I'll send a fix soon.
