### ISSUE TITLE
aws_spot_instance_request failure causes dependent resources to block further use of terraform

### ISSUE THREAD

**Issue by matthewfranglen** [hashicorp/terraform-provider-aws#15672]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.4
+ provider registry.terraform.io/-/aws v3.11.0
+ provider registry.terraform.io/hashicorp/aws v2.70.0

### Affected Resource(s)

* aws_spot_instance_request
* aws_ec2_tag
* aws_volume_attachment

### Terraform Configuration Files

```hcl
resource "aws_spot_instance_request" "my_request" {
  wait_for_fulfillment = true
  spot_type = "one-time"
  key_name = var.ssh_key_name

  ami = var.elasticsearch_ami_id
  availability_zone = var.elasticsearch_availability_zone
  subnet_id = var.subnet_ids[var.elasticsearch_availability_zone]
  spot_price = "0.000001"
  instance_type = "t2.xlarge"
}

resource "aws_ec2_tag" "my_tag" {
  resource_id = aws_spot_instance_request.my_request.spot_instance_id
  key = "Name"
  value = "my-instance"
}
```

### Expected Behavior

`terraform state list` should not contain `aws_spot_instance_request.my_request`
`terraform destroy` should not fail with an error.
`terraform apply` should not fail with an error.

### Actual Behavior

When creating the spot instance the apply fails with the error:

```
}) to resolve: unexpected state 'price-too-low', wanted target 'fulfilled'. last error: %!s(<nil>)

  on instance.tf line N, in resource "aws_spot_instance_request" "my_request":
 N: resource "aws_spot_instance_request" "twitter_lists_elasticsearch" {
```

Once this error has occurred subsequent use of the `terraform apply` and `terraform destroy` commands fail with the error:

`Error: "resource_id": required field is not set`

This error is produced for the `resource "aws_ec2_tag" "my_tag"`.
The failure means that destroy and apply cannot complete.

The resource for the spot instance has been created and can be viewed with `terraform state list`.
Running `terraform state rm aws_spot_instance_request.my_request` will fix the state and allow apply and destroy to work.

### Steps to Reproduce

1. Make a spot instance request with a price that is too low to be fulfilled.
2a. Perform `terraform state list`, see resource for spot instance request.
2b. Perform `terraform destroy`, see error.
2c. Perform `terraform apply`, see error.

**Comment by gdavison** [comment]
Hi @matthewfranglen, thanks for raising this issue. It looks like there are several issues coming together here.

Firstly, there's an [open issue on the Terraform Plugin SDK](https://github.com/hashicorp/terraform-plugin-sdk/issues/476) which is causing state to be written even when there's an error.

Secondly, when `wait_for_fulfillment` is `true`, we currently only support a limited set of the possible states of a Spot request. Specifically, we don't support the ["Holding" states](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-request-status.html#spot-instances-request-status-lifecycle). These should probably be added.

Lastly, tagging on the Spot request should be done using the `tags` argument on the `aws_spot_instance_request` resource itself. According to the [documentation for `aws_ec2_tag`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_tag),
> This resource should only be used in cases where EC2 resources are created outside Terraform (e.g. AMIs), being shared via Resource Access Manager (RAM), or implicitly created by other means (e.g. Transit Gateway VPN Attachments).

**Comment by gdavison** [comment]
I've created #15674 to address the states

**Comment by matthewfranglen** [comment]
Thanks for the tip about using count. I'll give that a go. Please let me know if I can be of any more help.

**Comment by matthewfranglen** [comment]
The count approach doesn't really work out unfortunately. This error occurs for both apply and delete:

> The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the         
resources that the count depends on.

As a workaround it's easier to just fix the state with `terraform state rm aws_spot_instance_request.my_request` when the error happens than run multiple apply commands. It was still a good suggestion.
