### ISSUE TITLE
tests/provider: Unsupported field 'inferenceAccelerators' (ECS Task Definition)

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#15685]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`inferenceAccelerators` field is not supported in GovCloud and possibly other non-standard partitions.

### New or Affected Resource(s)

* aws_ecs_task_definition

### Config

```hcl
resource "aws_ecs_task_definition" "test" {
  family = "acctest"

  container_definitions = <<TASK_DEFINITION
[
	{
		"cpu": 10,
		"command": ["sleep", "10"],
		"entryPoint": ["/"],
		"environment": [
			{"name": "VARNAME", "value": "VARVAL"}
		],
		"essential": true,
		"image": "jenkins",
		"memory": 128,
		"name": "jenkins",
		"portMappings": [
			{
				"containerPort": 80,
				"hostPort": 8080
			}
		],
        "resourceRequirements":[
            {
                "type":"InferenceAccelerator",
                "value":"device_1"
            }
        ]
	}
]
TASK_DEFINITION


  inference_accelerator {
    device_name = "device_1"
    device_type = "eia1.medium"
  }
}
```

### Error

```
    resource_aws_ecs_task_definition_test.go:774: Step 1/2 error: Error running apply: 
        Error: ClientException: Unsupported field 'inferenceAccelerators'.
        
        
--- FAIL: TestAccAWSEcsTaskDefinition_inferenceAccelerator (9.35s)
```

### References

* #15679
* #15662

**Comment by ewbankkit** [comment]
Closed via #19670.
