### ISSUE TITLE
Add JSON path validators to CloudWatch Events target

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#15691]
### Description

In the resource `aws_cloudwatch_event_target`, `input_path` and the values of the `input_transformer.input_paths` map use the [dot-notation form of JSONPath](https://goessner.net/articles/JsonPath/index.html#e2). This should be validated.

### New or Affected Resource(s)

* aws_cloudwatch_event_target

### References

* https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutTargets.html
* https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_InputTransformer.html

**Comment by philnichol** [comment]
@gdavison  I'd be happy to give this a go. Had a couple of quick questions if that's alright. Are you expecting just some basic validation (eg. startswith "$.") or something a bit more comprehensive?
