### ISSUE TITLE
Sort subnet ids by amount of available ip addresses in subnet

### ISSUE THREAD

**Issue by matthias-herrmann** [hashicorp/terraform-provider-aws#15701]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

If using shared vpcs in a company with the `data.aws_subnet_ids` block there are only a few subnets being used which results in subnets with low amount of available ip adresses and other subnets where no ip addresses are being used at all.

### New or Affected Resource(s)

* aws_subnet_ids

**Comment by bostrowski13** [comment]
I am also looking to do this to help more evenly distribute resrouces across subnets.  For me, a numerical sort could solve this, but I'll take a solution in any form.  In particular, it would be great to sort on map values in ascending order to be able to pull the top _n_ from that list.

I can produce a map of subnets and available IPs from the `data "aws_subnet"` resource....
```
data "aws_subnets" "cur_subnets" {
  filter {
    name   = "vpc-id"
    values = ["vpc-12345678"]
  }

  filter {
    name   = "state"
    values = ["available"]
  }
}

data "aws_subnet" "cur_subnets" {
  for_each = toset(data.aws_subnets.cur_subnets.ids)
  id       = each.value
}

locals {
  available_ips_per_subnet = {
    for k, sn in data.aws_subnet.cur_subnets : k => sn.available_ip_address_count
  }
}

output "available_ips_per_subnet" {
  value = local.available_ips_per_subnet
}
```

which gives me....
```
available_ips_per_subnet = {
  "subnet-a" = 8
  "subnet-b" = 17
  "subnet-c" = 20
  "subnet-d" = 18
  "subnet-e" = 15
  "subnet-f" = 15
}
```

I'd love to be able to sort on the values and select the top _x_ from the list.
