### ISSUE TITLE
When there is a constraint on a resource argument (eg. length), it should be mentioned in the docs

### ISSUE THREAD

**Issue by Makeshift** [hashicorp/terraform-provider-aws#15712]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It isn't obvious while browsing the documentation how long a particular argument can be. The only 'user-friendly' way to work this out is to put in an arbitrarily long name and see if it errors:

```
Error: expected length of bucket to be in the range (0 - 63), got iea-dev-resat-genplanning-instance-re_sat_qa_com-data-files-store
```
~~I _think_ that~~ these constraints are known by the TF Provider before trying to create the resource, as the error in this case is produced right at the beginning of a state refresh ~~(I can't find them in the code, though!)~~. So, those constraints should be available to view in a user-friendly way as part of the documentation.

~~(As a side note, could somebody show me where in the code these constraints are kept? I'm trying to make sure all my modules truncate or modify long resource names and would love to know how to look this up)~~

https://github.com/terraform-providers/terraform-provider-aws/blob/512f2aba2054327c2f528e13f6862622aacd6eab/aws/resource_aws_s3_bucket.go#L48

As these are validation functions as opposed to just a simple object containing constraints that are then ran through, I can definitely foresee this potentially being a bit difficult to extract cleanly from the code to generate documentation. 

It may seem like a very unimportant addition with a potentially large area of effect, but I think it's very important for developers to be able to start designing as quickly as possible once browsing the documentation, and being slowed down by errors that could have been avoided with a minor addition to docs must be avoided.

**Comment by philnichol** [comment]
I've come up with a hacky series of greps to pick up documentation items missing a max length. It's picked up just over 200 of these including the s3 bucket that you mentioned. While it may not be complete, it might be a good start.
It will still involve some manual work, @anGie44 assuming the you reckon this is worthwhile I'd be happy to raise a PR.

**Comment by anGie44** [comment]
Hi @philnichol, this documentation effort would be greatly appreciated! In the future we do plan to move towards automated documentation generation but we've noted that this type of validation text will need to be added manually for the time being.
To move forward with the manual work, I would recommend creating PRs with small, reviewable sections, say 5-10 files at a time that reference this tracking issue. If you have any additional questions, please let me know!

**Comment by philnichol** [comment]
@anGie44 Sure I'll raise the first one shortly to get some feedback

**Comment by anGie44** [comment]
Hi @Makeshift (and others that may come across this issue) 👋 noting here, as commented in #16057, we're unlikely to merge similar pull requests related to this issue in the future. There are a couple reasons for this: One is that we have some more internal research planned that may provide an automated solution to this problem so we don't want to waste contributors' time if a solution like that is upcoming. The other is that we aren't seeing that much community support for it at the moment, so it's hard for us to prioritize similar PRs over others.
