### ISSUE TITLE
Changing security_group_ids of aws_fsx_windows_file_system forces replacement

### ISSUE THREAD

**Issue by supergibbs** [hashicorp/terraform-provider-aws#15726]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
->terraform -v
Terraform v0.12.29
+ provider.aws v3.10.0

Your version of Terraform is out of date! The latest version
is 0.13.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* aws_fsx_windows_file_system

### Terraform Configuration Files

```hcl
resource "aws_fsx_windows_file_system" "share" {
  #added
  security_group_ids               = ["sg-123456"]
}

```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Be able to modify `security_group_ids` in a `aws_fsx_windows_file_system` resource. It's possible by modifying the security groups of the elastic network interface used by your FSx resource

https://docs.aws.amazon.com/fsx/latest/WindowsGuide/limit-access-security-groups.html#fsx-vpc-security-groups

### Actual Behavior

Modifying `security_group_ids` in a `aws_fsx_windows_file_system` resource forces replacement

### Steps to Reproduce

1. Create a `aws_fsx_windows_file_system` and don't specify any `security_group_ids`, `default` security group will automatically be used. 
2. `terraform apply`
3. Add a `security_group_ids` value
2. `terraform apply`

### Important Factoids

Only tested with `aws_fsx_windows_file_system` but probably same issue with `aws_fsx_lustre_file_system`

**Comment by philnichol** [comment]
@supergibbs I had a look at this and unfortunately using the API you cannot update the security groups directly other than at creation of the FSX File System. You can't even read them with describe:
```
    // A list of IDs specifying the security groups to apply to all network interfaces
    // created for file system access. This list isn't returned in later requests
    // to describe the file system.
    SecurityGroupIds []*string `type:"list"`
```
The only way to do so would be like you said, to update the network interface directly.

@ewbankkit I'm not too familiar with how you guys like to do things in this provider. Would the best of course of action be to stick to what's available via the API or to add a way around changing the security groups by reading/updating the ENIs directly?

Alternatively, documentation could suggest managing changing security groups of the ENIs via something like:
```
resource "aws_network_interface_sg_attachment" "sg_attachment" {
  for_each = aws_fsx_windows_file_system.example.network_interface_ids
  security_group_id    = aws_security_group.sg.id
  network_interface_id = each.value
}
```

**Comment by ewbankkit** [comment]
@philnichol We try wherever possible to avoid making calls to AWS services that aren't the resource's "home" service (so calls to EC2 for the ENI vs. FSX for the file system).
There's a similar issue with the `aws_transfer_server` resource: https://github.com/terraform-providers/terraform-provider-aws/issues/15788.

**Comment by DrFaust92** [comment]
Closing this as this is a gap on the AWS API side, there is not way around this currently in the AWS Provider. I would recommend reaching out to AWS support and opening a ticket regarding this gap.
