### ISSUE TITLE
zone_awareness_enabled is ignored for AWS ES domain resource

### ISSUE THREAD

**Issue by OleksandrMykytenko** [hashicorp/terraform-provider-aws#15730]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.20
+ provider.aws v3.10.0

### Affected Resource(s)

* aws_elasticsearch_domain

### Terraform Configuration Files

```hcl
resource "aws_elasticsearch_domain" "es" {
  domain_name           = "${local.name_prefix}-cluster"
  elasticsearch_version = var.elasticsearch_version

  cluster_config {
    instance_type  = var.elasticsearch_instance_type
    instance_count = var.elasticsearch_num_nodes

    zone_awareness_enabled = false

    zone_awareness_config {
      availability_zone_count = var.elasticsearch_az_count
    }
}
...
}
```

### Expected Behavior

Terraform should ignore `zone_awareness_config` section and does not propose to set `availability_zone_count` to any numbers in case if `zone_awareness_enabled` is set to `false`.

### Actual Behavior

See plan output below:

```
 ~ cluster_config {
            dedicated_master_count   = 0
            dedicated_master_enabled = false
            instance_count           = 2
            instance_type            = "t2.medium.elasticsearch"
            warm_count               = 0
            warm_enabled             = false
            zone_awareness_enabled   = false

          + zone_awareness_config {
              + availability_zone_count = 2
            }
        }
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Not sure about creation of new cluster, but it is true for updating.

**Comment by macdrorepo** [comment]
Have the same issue, vote up.
