### ISSUE TITLE
Fix Hardcoded Region GovCloud Test Failures

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#15737]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Acceptance tests that are necessarily hardcoded to `us-east-1` fail in GovCloud and any other partition where `us-east-1` does not exist (i.e., all partitions except `aws`). Most of the time these tests use `os.Setenv()` to set `AWS_DEFAULT_REGION` to `us-east-1`. Once this is done, credentials will not work in non-standard partitions since the region does not exist.

See #8316 for a way forward.

### Existing Reports

- [x] TestAccDataSourceAwsCurReportDefinition_basic
- [x] TestAccDataSourceAwsCurReportDefinition_additional
- [x] TestAccAWSDbInstanceDataSource_ec2Classic
- [ ] TestAccDataSourceAwsEip_PublicIP_EC2Classic
- [ ] TestAccDataSourceAwsPricingProduct_ec2
- [ ] TestAccDataSourceAwsPricingProduct_redshift
- [ ] TestAccDataSourceAwsRegion_basic
- [ ] TestAccDataSourceAwsRegion_endpoint
- [ ] TestAccDataSourceAwsRegion_endpointAndName
- [ ] TestAccDataSourceAwsRegion_name
- [ ] TestAccAWSAPIGatewayDomainName_CertificateArn
- [ ] TestAccAWSCloudFrontDistribution_ViewerCertificate_AcmCertificateArn
- [ ] TestAccAWSCloudFrontDistribution_ViewerCertificate_AcmCertificateArn_ConflictsWithCloudFrontDefaultCertificate
- [ ] Perhaps everything CloudFront?
- [ ] TestAccAWSCognitoUserPoolDomain_custom
- [x] TestAccAwsCurReportDefinition_basic
- [x] TestAccAwsCurReportDefinition_textOrCsv
- [x] TestAccAwsCurReportDefinition_parquet
- [x] TestAccAwsCurReportDefinition_athena
- [x] TestAccAwsCurReportDefinition_refresh
- [x] TestAccAwsCurReportDefinition_overwrite
- [x] TestAccAWSDBInstance_ec2Classic
- [x] TestAccAWSDBSecurityGroup_basic
- [ ] TestAccAWSDefaultSecurityGroup_Classic_basic
- [ ] TestAccAWSDefaultSecurityGroup_Classic_empty
- [ ] TestAccAWSEIPAssociation_ec2Classic
- [ ] TestAccAWSEIP_Ec2Classic
- [ ] TestAccAWSEIP_tags_Ec2Classic
- [ ] TestAccAWSElasticacheCluster_SecurityGroup_Ec2Classic
- [ ] TestAccAWSElasticacheSecurityGroup_basic
- [ ] TestAccAwsFmsAdminAccount_basic
- [ ] TestAccAWSInstance_inEc2Classic
- [ ] TestAccAWSLightsailDomain_basic
- [ ] TestAccAWSLightsailDomain_disappears
- [ ] TestAccAWSOpsWorksStack_classicEndpoints
- [x] TestAccAWSRedshiftSecurityGroup_basic
- [x] TestAccAWSRedshiftSecurityGroup_ingressCidr
- [x] TestAccAWSRedshiftSecurityGroup_updateIngressCidr
- [x] TestAccAWSRedshiftSecurityGroup_ingressSecurityGroup
- [x] TestAccAWSRedshiftSecurityGroup_updateIngressSecurityGroup
- [ ] TestAccAWSRoute53HealthCheck_withHealthCheckRegions
- [ ] TestAccAWSRoute53QueryLog_basic
- [ ] TestAccAWSRoute53Record_latency_basic
- [ ] TestAccAWSSecurityGroup_defaultEgressClassic
- [ ] TestAccAWSSecurityGroup_ingressWithCidrAndSGsClassic
- [ ] TestAccAWSWafWebAcl_LoggingConfiguration
- [ ] TestAccAwsWorkspacesDirectory_* (?)
- [ ] TestAccAWSOrganizations_serial/Policy

### Definition of Done

All tests that are hardcoded for `us-east-1` pass/skip in GovCloud.

### References

* #8316
* #15791

**Comment by ewbankkit** [comment]
Related:

* https://github.com/terraform-providers/terraform-provider-aws/issues/8316

**Comment by bflad** [comment]
Most of these should be squared away! There may be one or two lingering still.
