### ISSUE TITLE
data source aws_msk_node

### ISSUE THREAD

**Issue by dblooman** [hashicorp/terraform-provider-aws#15731]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Adds a way of getting MSK node information

### New or Affected Resource(s)

* aws_msk_node

### Potential Terraform Configuration

```hcl
data "aws_msk_node" "test" {
  cluster_arn     = aws_msk_cluster.test.arn
  broker_endpoint = trimsuffix(split(",", aws_msk_cluster.test.bootstrap_brokers_tls)[0], ":9094")
}
```

### References

#15163

**Comment by ewbankkit** [comment]
@dblooman Thanks for raising this issue.
Use of the upcoming `aws_msk_broker_nodes` data source along with [a filter](https://www.terraform.io/docs/language/expressions/for.html#filtering-elements) should give you the functionality you are looking for.
