### ISSUE TITLE
Amazon CloudFront Origin Shield

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#15752]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon CloudFront announces Origin Shield.

### New or Affected Resource(s)

* [`aws_cloudfront_distribution`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution)

### Potential Terraform Configuration

```hcl
resource "aws_cloudfront_distribution" "example" {
  origin {
    origin_shield {
      enabled = true

      origin_shield_region = "eu-west-2"
    }
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/10/announcing-amazon-cloudfront-origin-shield/).

Requires [AWS SDK v1.35.10](https://github.com/aws/aws-sdk-go/releases/tag/v1.35.10):

* https://github.com/terraform-providers/terraform-provider-aws/pull/15716

**Comment by philnichol** [comment]
@ewbankkit mind if I have a crack at this?

**Comment by philnichol** [comment]
Cheers @ewbankkit! Apologies if it's a silly question, but since it requires AWS SDK v1.35.10 would I update the version as part of this PR? Or would that normally be left to a separate PR of it's own? Obviously will still test locally with 1.35.10

**Comment by ewbankkit** [comment]
@philnichol The AWS SDK merge will be done independently - I'll try and move that along.

**Comment by ebdxflr** [comment]
is this implemented? can I now use Shield in my Origin with CloudFront through terraform?

**Comment by philnichol** [comment]
@ebdxflr hi, appears the PR still hasn't been approved and merged. @ewbankkit should I raise a new one with only this feature? Appreciate that I shouldn't have raised a couple of things in 1 PR instead of 2 separate ones.
