### ISSUE TITLE
AWS Cluster Endpoints: The specified resource name does not match an RDS resource in this region

### ISSUE THREAD

**Issue by willmafra** [hashicorp/terraform-provider-aws#15758]
Terraform tries to get tags of a rds cluster endpoint and it seems that rds/ListTagsForResource doesn't work with Cluster Endpoints

**Terraform*
**Error:** error listing tags for RDS Cluster Endpoint (arn:aws:rds:sa-east-1:xxxxxxxx:cluster-endpoint:my-endpoint): InvalidParameterValue: The specified resource name does not match an RDS resource in this region.
	status code: 400, request id: 6b2de28d-2df7-4955-ab99-54e072404eca

**Code:** https://github.com/terraform-providers/terraform-provider-aws/blob/d697785e783257316423772e16121921e47e373e/aws/resource_aws_rds_cluster_endpoint.go#L163

**Aws cli**
aws rds   describe-db-cluster-endpoints  --db-cluster-identifier my-endpoint
{
    "DBClusterEndpoints": [
        ....
        {
            "DBClusterEndpointIdentifier": "xxxxxx",
            "DBClusterIdentifier": "my-endpoint",
            "DBClusterEndpointResourceIdentifier": "xxxxxx",
            "Endpoint": "xxxxxxxx",
            "Status": "available",
            "EndpointType": "CUSTOM",
            "CustomEndpointType": "ANY",
            "StaticMembers": [],
            "ExcludedMembers": [],
            "DBClusterEndpointArn": "arn:aws:rds:sa-east-1:xxxxxxxx:cluster-endpoint:my-endpoint"
        }
    ]
}

aws rds  list-tags-for-resource --resource-name  arn:aws:rds:sa-east-1:270036487593:cluster-endpoint:my-endpoint
An error occurred (InvalidParameterValue) when calling the ListTagsForResource operation: The specified resource name does not match an RDS resource in this region

**Comment by ewbankkit** [comment]
Related:

* https://github.com/terraform-providers/terraform-provider-aws/issues/11043
