### ISSUE TITLE
aws_vpc support new attribute Ipv6CidrBlockNetworkBorderGroup

### ISSUE THREAD

**Issue by pingwin** [hashicorp/terraform-provider-aws#15766]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

1. Support the Ipv6CidrBlockNetworkBorderGroup attribute to provide IPv6 addresses to LocalZones and Wavelength Zones.

### New or Affected Resource(s)

* aws_vpc

### Potential Terraform Configuration

```hcl
ipv6_cidr_block_network_border_group = The name of the location from which we advertise the IPV6 CIDR block. Use this parameter to limit the address to this location. 
```

### References

* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVpc.html

**Comment by efog** [comment]
Hi,

I would be interested in working on this as I could need this. Is it necessary for the AWS SDK to be updated with the new properties (ec2/api.go) to start working on this? 

ÉB

**Comment by ewbankkit** [comment]
For full functionality we will also need to add an `aws_vpc_ipv4_cidr_block_association` resource (and update the `aws_vpc` data source) as a VPC that includes Local (or Wavelength, if IPv6 is supported) Zone subnets can have multiple IPv6 CIDR blocks ([one per network border group](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssociateVpcCidrBlock.html#API_AssociateVpcCidrBlock_RequestParameters)).

Relates: https://github.com/hashicorp/terraform-provider-aws/issues/14518.

**Comment by FireballDWF** [comment]
> Hi,
> 
> I would be interested in working on this as I could need this. Is it necessary for the AWS SDK to be updated with the new properties (ec2/api.go) to start working on this?

The SDK has been updated, so their should be no blockers to working on this.
