### ISSUE TITLE
Feature request: Start/stop Kinesis Analytics Flink applications

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#15760]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

[From](https://github.com/terraform-providers/terraform-provider-aws/pull/11652#issuecomment-708831299) #11652:

> @ewbankkit @blake-wilson Hey, I was just wondering if it would be appropriate to include a call to StartApplication (https://docs.aws.amazon.com/sdk-for-go/api/service/kinesisanalyticsv2/#KinesisAnalyticsV2.StartApplication) as part of this resource or does it make more sense to have some other resource perhaps aws_kinesisanalyticsv2_application_start or something where creating the resource calls start and deleting it calls stop.
>
> The reason I am asking is because I would ideally like to be able to create and start an Apache Flink Kinesis application entirely with terraform.

### New or Affected Resource(s)

* `aws_kinesisanalyticsv2_application`

### Potential Terraform Configuration

```hcl
#TBD but should match similar feature for aws_kinesis_analytics_application.
```

### References

* #11652
* #7383

[API reference](https://docs.aws.amazon.com/kinesisanalytics/latest/apiv2/API_StartApplication.html).
[Running applications](https://docs.aws.amazon.com/kinesisanalytics/latest/java/how-running-apps.html).
[Snapshots](https://docs.aws.amazon.com/kinesisanalytics/latest/java/how-fault-snapshot.html).

**Comment by tedivm** [comment]
Honestly the fact that this isn't setup yet should be considered a bug. Right now it is literally impossible to use terraform to launch a working pipeline that includes flink because while terraform can do all the work setting it up, terraform unfortunately leaves it in an unusable state until manual intervention occurs.

**Comment by ewbankkit** [comment]
@tedivm Do you have the use case of starting from a [savepoint/snapshot](https://docs.aws.amazon.com/kinesisanalytics/latest/java/how-fault-snapshot.html)?

**Comment by tedivm** [comment]
@ewbankkit - I don't really, our systems would just start reprocessing the backups in the case of a crash.
