### ISSUE TITLE
MSK configuration not constrained to kafka_versions specified

### ISSUE THREAD

**Issue by dacreify** [hashicorp/terraform-provider-aws#15797]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
❯ terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/-/aws v3.12.0
+ provider registry.terraform.io/hashicorp/aws v3.12.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
```

### Affected Resource(s)

* `aws_msk_configuration`

### Terraform Configuration Files

```hcl
resource "aws_msk_configuration" "config" {
  name = "config"
  kafka_versions = ["2.2.1"]
  server_properties = "auto.leader.rebalance.enable=true"
}
```

### Expected Behavior

Successful creation of the config

### Actual Behavior

```
Error: error creating MSK Configuration: BadRequestException: [ {
  "name" : "auto.leader.rebalance.enable",
  "value" : "true",
  "errorMessages" : [ "Key 'auto.leader.rebalance.enable' is not supported by at least one Apache Kafka version. Key checked against versions: [2.4.1.1, 2.5.1, 2.6.0, 2.3.1, 1.1.1, 2.2.1]" ]
} ]
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "33dcc73e-6302-458b-84c0-7cce6e93d649"
  },
  InvalidParameter: "serverproperties",
  Message_: "[ {\n  \"name\" : \"auto.leader.rebalance.enable\",\n  \"value\" : \"true\",\n  \"errorMessages\" : [ \"Key 'auto.leader.rebalance.enable' is not supported by at least one Apache Kafka version. Key checked against versions: [2.4.1.1, 2.5.1, 2.6.0, 2.3.1, 1.1.1, 2.2.1]\" ]\n} ]"
}
```

### Steps to Reproduce

1. `terraform apply`

**Comment by timcosta** [comment]
Has anyone found a workaround/solution for this issue? We're experiencing it currently and haven't been able to find a workaround.

**Comment by alexandergunnarson** [comment]
To be fair, I did just try it from the AWS console and it yields the same error:
<img width="837" alt="Screen Shot 2021-08-11 at 1 40 19 PM" src="https://user-images.githubusercontent.com/4691106/129100091-b30980c7-316e-4eae-b103-56241015acc3.png">

So this is actually a problem upstream.

**Comment by alexandergunnarson** [comment]
FWIW doing the same thing from the AWS CLI (v2) is similarly problematic:

```bash
aws kafka create-configuration \
--name "Test" \
--kafka-versions "2.2.1" \
--server-properties $(echo "auto.leader.rebalance.enable=true" | base64)
```

**Comment by alexandergunnarson** [comment]
The same error happens when using the Java v2 SDK via Clojure:
```clojure
(let [client  (-> (software.amazon.awssdk.services.kafka.KafkaClient/builder)
                  (.build))
      request (-> (software.amazon.awssdk.services.kafka.model.CreateConfigurationRequest/builder)
                  (.kafkaVersions ["2.2.1"])
                  (.name "test")
                  (.serverProperties (software.amazon.awssdk.core.SdkBytes/fromUtf8String
                                       "auto.leader.rebalance.enable=true"))
                  (.build))]
  (.createConfiguration client request))
```

```
software.amazon.awssdk.services.kafka.model.BadRequestException: 
  [ { 
      "name" : "auto.leader.rebalance.enable",
      "value" : "true",
      "errorMessages" : [ "Key 'auto.leader.rebalance.enable' is not supported by at least one Apache Kafka version. Key checked against versions: [2.4.1.1, 2.6.2, 2.7.1, 2.8.0, 2.5.1, 2.6.0, 2.6.1, 2.7.0, 2.3.1, 2.2.1]" ]
     } ] 
(Service: Kafka, Status Code: 400, Request ID: 139ff36f-61e5-4b98-8f17-20a6a111a1a6, Extended Request ID: null)
```

**Comment by alexandergunnarson** [comment]
@dacreify and @timcosta —
Just realized that certain properties are disallowed by AWS to be changed in MSK. It doesn't seem to be a matter of checking Kafka versions — that's just a red herring. For instance, at least the following properties can't be set:
```
allow.everyone.if.no.acl.found
auto.leader.rebalance.enable
zookeeper.set.acl
```
even to their default values per https://docs.aws.amazon.com/msk/latest/developerguide/msk-default-configuration.html.

**Comment by timcosta** [comment]
That's super interesting, thanks for pointing that out @alexandergunnarson. I may try to bring this up with our AWS rep as it's fairly confusing to have documentation around default settings but no documentation around which setting can be updated or not.

**Comment by breathingdust** [comment]
Hi all 👋 As this seems an upstream issue I'll close for now. Thanks!
