### ISSUE TITLE
Contributing Documentation: Add section on error handling

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#15792]
Add a section to documentation providing guidance on API error handling.

Among others, things to document:
* The Delete operation should not return an error when the resource is not found, but simply short circuit.
* Repeat the instructions to remove resource from state using `d.SetId("")` when not found during the Read operation
* Document use of `resource.Retry(iamwaiter.PropagationTimeout, ...)` for IAM eventual consistency

**Comment by bflad** [comment]
Since this is similar to other in progress provider documentation I'm already working on, picking this up as well. Most likely this will make sense as its own page, since there could be a lot of content that does not fit well with the existing information architecture of the contributing guide.

**Comment by bflad** [comment]
This information is now present in the following Contributing Guide documentation:

- https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/error-handling.md
- https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/retries-and-waiters.md
