### ISSUE TITLE
Acceptance testing: Create EC2-Classic alternate test provider

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#15791]
In our current testing environment, EC2-Classic is only supported in `us-east-1` in one specific account. We have the pre-check `testAccEC2ClassicPreCheck()` to skip tests when EC2-Classic is not supported.

Currently, we hardcode the region `us-east-1` and override the `AWS_DEFAULT_REGION` environment variable.

Using the environment variable override impacts other acceptance tests when run locally unless those tests are not run in parallel, i.e. run with `resource.Test()` instead of `resource.ParallelTest()`, so it is not ideal.

In addition, the assumption that only `us-east-1` supports EC2-Classic is incorrect, and only applies in our testing environment. EC2-Classic is also [supported in GovCloud](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-ec2.html#govcloud-ec2-vpc), which does not have the region `us-east-1`.

Our testing framework supports the use of alternate provider configurations and environment variables to define regions for specific types of tests. Defining an environment variable such as `AWS_EC2CLASSIC_REGION` which is used in an EC2-Classic-related provider configuration, for example`testAccProviderEC2Classic()`, would allow this to be addressed.

**Comment by bflad** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/8316
* https://github.com/terraform-providers/terraform-provider-aws/issues/15737

**Comment by bflad** [comment]
This will be complete after:

* #16026
* #16032
* #16034
* #16035
* #16036
