### ISSUE TITLE
MSK storage autoscaling

### ISSUE THREAD

**Issue by cemeyer2** [hashicorp/terraform-provider-aws#15796]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

MSK now supports autoscaling of storage per https://aws.amazon.com/about-aws/whats-new/2020/09/amazon-msk-can-now-automatically-expand-cluster-storage/

It would be beneficial for the terraform provider to be able to configure this as well.

### New or Affected Resource(s)

* aws_msk_cluster

### References

* https://aws.amazon.com/about-aws/whats-new/2020/09/amazon-msk-can-now-automatically-expand-cluster-storage/

**Comment by dblooman** [comment]
Hi, just to let you know, this isn't an MSK resource it is an app scaling resource

so 
```hcl
resource "aws_appautoscaling_target" "kafka_storage" {
  max_capacity       = var.scaling_max_capacity
  min_capacity       = 1
  resource_id        = aws_msk_cluster.primary.arn
  scalable_dimension = "kafka:broker-storage:VolumeSize"
  service_namespace  = "kafka"
}

resource "aws_appautoscaling_policy" "kafka_broker_scaling_policy" {
  name               = "${local.service_name}-broker-scaling"
  policy_type        = "TargetTrackingScaling"
  resource_id        = aws_msk_cluster.primary.arn
  scalable_dimension = aws_appautoscaling_target.kafka_storage.scalable_dimension
  service_namespace  = aws_appautoscaling_target.kafka_storage.service_namespace

  target_tracking_scaling_policy_configuration {
    predefined_metric_specification {
      predefined_metric_type = "KafkaBrokerStorageUtilization"
    }

    target_value = var.scaling_target_value
  }
}
```
All that was required was an update to the SDK, which now supports MSK arn as a resource

**Comment by cemeyer2** [comment]
thanks @dblooman ....that did it for me too! The `min_capacity` being 1 was a tad confusing (especially when the AWS api complains if it is greater than 1) but the docs make it clear storage only scales up and when its likely the apis are being reused for a new autoscaling use case, everything falls into place.

thanks again
