### ISSUE TITLE
Amazon SNS FIFO topics

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#15805]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon SNS introduces First-in-First-out (FIFO) topics with strict ordering and deduplication of messages.

### New or Affected Resource(s)

* [`aws_sns_topic`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_topic)

### Potential Terraform Configuration

```hcl
resource "aws_sns_topic" "example" {
  fifo_topic = true
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-sns-introduces-fifo-topics-with-strict-ordering-and-deduplication-of-messages/).
[Blog post 1](https://aws.amazon.com/blogs/aws/introducing-amazon-sns-fifo-first-in-first-out-pub-sub-messaging/).
[Blog post 2](https://aws.amazon.com/blogs/compute/building-event-driven-architectures-with-amazon-sns-fifo/).
[Developer Guide](https://docs.aws.amazon.com/sns/latest/dg/sns-fifo-topics.html).

**Comment by gvasquez95** [comment]
this extra supported attribute would be a win-win for SQ FIFO queues subscribed to SNS FIFO topics

**Comment by ShiraShaf** [comment]
Please add, FIFO is going to be very useful (SQS FIFO queues subscribed to SNS FIFO topics)!

**Comment by wellermiranda** [comment]
Any chance to be merged soon?

**Comment by cmardonespino** [comment]
what we are waiting for? please, merge it !! we need it !

**Comment by woodsae** [comment]
Any chance of getting this soon?

**Comment by DhayanandBaskar** [comment]
FIFO SQS queues can only subscribe to FIFO SNS Topics, We need this, please!

**Comment by chloe-codes1** [comment]
Any updates?

**Comment by MitchellKununu** [comment]
Any info on when this will be released?

**Comment by gvasquez95** [comment]
This kind of delays is exactly why I ditched Terraform and favored CloudFormation :(

**Comment by luisgo1411** [comment]
Nothing yet?

**Comment by cavallos** [comment]
Merge it please...! 👍

**Comment by konguparthi** [comment]
Is this available? Please confirm

**Comment by bitintheskud** [comment]
Why is this PR stuck in limbo without any explanation ? this feature is very important :'(  @teamterraform @mitchellh

**Comment by ThiagoAndrad** [comment]
Any updates?

**Comment by thiagokpelo** [comment]
> Any updates?
+1

**Comment by luisgo1411** [comment]
If someone is having issues with this the best approach that I find its a cloudformation, the issue to create independently the sqs or the sns its because to create it there should exist the queue before, imposible because this is an unsupported feature still.
Here is my cf example:

```terraform
resource "aws_cloudformation_stack" "sns_fifo_to_sqs_fifo" {
  name = "sns-fifo-to-sqs-fifo"
  template_body = <<CONTENT
  {
    "AWSTemplateFormatVersion": "2010-09-09",
    "Resources": {
      "VidispineSNSTopic": {
        "Type": "AWS::SNS::Topic",
        "Properties": {
          "TopicName": "SNS-Vidispine-Topic.fifo",
          "FifoTopic": true,
          "ContentBasedDeduplication": false
        }
      },
      "VidispineSQS": {
        "Type": "AWS::SQS::Queue",
        "Properties": {
          "QueueName": "SQS-Vidispine-queue.fifo",
          "FifoQueue": true,
          "ContentBasedDeduplication": false
        }
      },
      "SQSVidispineSubscription": {
        "Type": "AWS::SNS::Subscription",
        "Properties": {
          "TopicArn": {
            "Ref": "VidispineSNSTopic"
          },
          "Endpoint": {
            "Fn::GetAtt": [
              "VidispineSQS",
              "Arn"
            ]
          },
          "Protocol": "sqs",
          "RawMessageDelivery": "false"
        }
      },
      "SQSQueuesPolicy": {
      "Type": "AWS::SQS::QueuePolicy",
        "Properties": {
          "PolicyDocument": {
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Service": "sns.amazonaws.com"
                },
                "Action": [
                  "sqs:SendMessage"
                ],
                "Resource": "*",
                "Condition": {
                  "ArnEquals": {
                    "aws:SourceArn": {
                      "Ref": "VidispineSNSTopic"
                    }
                  }
                }
              }
            ]
          },
          "Queues": [
            {
              "Ref": "VidispineSQS"
            }
          ]
        }
      }
    }
  }
CONTENT
}
```

**Comment by yumingqiao** [comment]
This feature is very important, any update?

**Comment by eliurkis** [comment]
Any update on this?

**Comment by cburkhardtBB** [comment]
4 months since release of this feature and its still not added to Terraform. 634 PRs pending. 2500+ issues. 

PR related to this passing all tests and requested for review 1 month ago but not touched by Hashicorp: https://github.com/hashicorp/terraform-provider-aws/pull/17164. 

If we have to wait 4-6 months for each new service that is released on AWS, how are we supposed to rely on Terraform? We started looking around at other services that will provide better support. Hashicorp needs to hire more people or get some better internal management to speed things up.

**Comment by kojoa** [comment]
There is other aspect to this issue also; Terraform's `Data Source: aws_sns_topic` doesn't seem to allow . (dot) in SNS topic name. AWS documentation suggests that FIFO topic name should end in .fifo-suffix. (See: https://docs.aws.amazon.com/sns/latest/dg/fifo-example-use-case.html)

So referencing correctly named fifo topic is not possible in other Terraforms without hardcoding the topic ARN.

**Comment by terencec-padok** [comment]
We would really like to have this feature, it's painful to manage FIFO SNS topics without the proper resource.

**Comment by michaelxmora** [comment]
Released Oct. 22, 2020 and now at the end of March, still no support?
