### ISSUE TITLE
tests/provider: Improve documentation for anti-hardcoding efforts

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#15819]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Static checks/linters now check or will soon check for many hardcoded issues. We should add documentation (contributor guide?) that helps contributors know how to avoid these issues or fix them when the linters complain.

### Definition of Done

Easily available documentation contains helpful sections on avoiding hardcoding in these situations:

- [ ] AMI ID
- [ ] Availability zones
- [ ] Caller ID
- [ ] Canonical user ID
- [ ] Database versions
- [ ] Instance types
- [ ] Partition DNS suffix
- [ ] Partition in ARN
- [ ] Region
- [ ] Spot price
- [ ] State hash

### References

* https://github.com/terraform-providers/terraform-provider-aws/tree/master/awsproviderlint

**Comment by bflad** [comment]
Some of this information is documented in https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/contributing/pullrequest-submission-and-lifecycle.md#common-review-items, which is linked from some of the https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/contributing/contribution-checklists.md sections.

However, those guidelines could probably be improved to be more clear. Maybe having each of these specific items as sub-sections and linked in a table of contents would help.

**Comment by YakDriver** [comment]
@bflad I amplified everything and added the table of contents. I kept with the checklist format - I like that.
