### ISSUE TITLE
Update documentation for using multiple http methods for a single resource in AWS API Gateway 

### ISSUE THREAD

**Issue by sgabenov** [hashicorp/terraform-provider-aws#15832]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In TF documentation there is no example of how to set up multiple HTTP methods for a single resource path in AWS API Gateway. The AWS UI gives the possibility to set multiple methods, but in TF resource we could not use list of methods.
I expect to set up a list of methods, but this throws an error. And also mapping different methods to a single aws_api_gateway_resource gives an error. 

### New or Affected Resource(s)

* aws_api_gateway_method

### Potential Terraform Configuration

```hcl
resource "aws_api_gateway_method" "proxy" {
   rest_api_id   = aws_api_gateway_rest_api.ess_proxy_api_gateway.id
   resource_id   = aws_api_gateway_resource.proxy.id
   http_method   = ["ANY", "OPTIONS"]
   authorization = "NONE"
}
```

**Comment by nitish-vts** [comment]
I have been facing the same issue and was thinking if for_each would resolve this issue? but not sure how to implement on the same and add another resource and method into the same API gateway that i did using UI.

**Comment by lentyai2** [comment]
What if you need to define two methods with one using authorizer and the other one not? I'm facing this exact scenario. I know that it can be done as I was able to set it up in AWS console. But I'm struggling how to properly script it in terraform, though. There has to be 2 methods for sure, but how to script the "aws_api_gateway_integration" is the real question! Can I use `for_each      = toset(["POST", "ANY"])` and be sure that one will use auth and the other doesn't? Do I script a separate "integration"? Guide is real lacking for that...
