### ISSUE TITLE
aws_athena_workgroup documentation error

### ISSUE THREAD

**Issue by kkotowick** [hashicorp/terraform-provider-aws#15856]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

AWS provider: 3.12.0
Terraform: N/A

### Affected Resource(s)

aws_athena_workgroup (documentation)

* aws_XXXXX

### Expected Behavior

Example config in the documentation for this resource should work (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/athena_workgroup).

### Actual Behavior

The documentation has an error. It contains:
```
output_location = "s3://{aws_s3_bucket.example.bucket}/output/"
```

This is missing the `$` symbol before the opening curly bracket.

**Comment by bflad** [comment]
Hi @kkotowick 👋  Thank you for raising this. If you or anyone is interested in fixing the documentation, its source can be found in the [`website/docs/r/athena_workgroup.html.markdown` file](https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/athena_workgroup.html.markdown). 👍
