### ISSUE TITLE
Adding processing_configuration to aws_kinesis_analyltics_application errors.

### ISSUE THREAD

**Issue by jtsaito** [hashicorp/terraform-provider-aws#15881]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

> Terraform v0.12.28
> provider.aws v3.11.0

### Affected Resource(s)

* `aws_kinesis_analytics_application`

### Terraform Configuration Files

```hcl
resource "aws_kinesis_analytics_application" "tealium_kinesis_analytics_app" {
  name        = "tealium-${var.environment}-kinesis-analytics-app"
  description = <<EOF
    Kinesis Data Analytics application to filter web:converted events
    from the main Kinesis Data Stream and propagate them to a Firehose Function
  EOF

  code = file("${path.module}/kinesis/tealium_kinesis_analytics_query.sql")

  tags = {
    app = "tealium-integration"
    env = var.environment

    consuming_from = local.consuming_from
  }

  inputs {
    name_prefix = "tealium-stream"

    kinesis_stream {
      resource_arn = local.consuming_from
      role_arn     = aws_iam_role.kinesis-analytics-tealium.arn
    }

    # ATTRIBUTE CAUSING ERROR ON APPLY!!
    processing_configuration {
      lambda {
        resource_arn = module.lambda-tealium-event-filtration.lambda.arn
        role_arn     = aws_iam_role.kinesis-analytics-tealium.arn
      }
    }

    parallelism {
      count = 1
    }

    schema {
      record_columns {
        mapping  = "$.name"
        name     = "name"
        sql_type = "VARCHAR(256)"
      }
  ...
  }

  outputs {
    name = "DESTINATION_SQL_STREAM"

    schema {
      record_format_type = "CSV"
    }

    kinesis_firehose {
      resource_arn = module.firehose-tealium-integration-output-stream.arn
      role_arn     = aws_iam_role.kinesis-analytics-tealium.arn
    }
  }

  outputs {
    name = "error_stream"

    schema {
      record_format_type = "JSON"
    }

    kinesis_firehose {
      resource_arn = module.firehose-tealium-integration-error-stream.arn
      role_arn     = aws_iam_role.kinesis-analytics-tealium.arn
    }
  }

```

### Debug Output

> InvalidArgumentException: There is no existing input processing configuration to update. You can add an input processing configuration using AddApplicationInputProcessingConfiguration

### Expected Behavior
No error and the apply updates the Kinesis analytics application by adding the the `processing_configuration`.

### Actual Behavior

When adding the `processing_configuration` block, the plan correctly shows that the `processing_configuration` will be added but the apply fails with the above error.

### Steps to Reproduce

You should be able to reproduce this by

1. creating a minimal Kinesis analytics app, and 
2. adding the `processing_configuration` block and applying.

**Comment by ewbankkit** [comment]
@jtsaito Thanks for raising this issue.
You are correct that the `UpdateApplication` API is being called for all changes:

https://github.com/terraform-providers/terraform-provider-aws/blob/6df99631b7a7af689373cf9b3449a36ec9e76ccd/aws/resource_aws_kinesis_analytics_application.go#L701-L716
