### ISSUE TITLE
tests/provider: Migrate from internal TypeSet check functions to TF SDK v2.1.0 check functions

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#15882]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As part of the Terraform Plugin SDK version 2 development work, some internal acceptance testing state checking functions were created to handle `TypeSet` attributes which had some underlying changes in the testing framework. These currently can be found in the [`aws/internal/tfawsresource` package in this repository](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/internal/tfawsresource/testing.go). This functionality has now been promoted into the Terraform Plugin SDK itself as of version 2.1.0 into the commonly used [`helper/resource` package](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource) and the dependency has already been updated in this project, so we can remove our internal copies.

Should be a matter of find/replace of the following:

* `tfawsresource.TestCheckTypeSetElemAttr` -> `resource.TestCheckTypeSetElemAttr`
* `tfawsresource.TestCheckTypeSetElemAttrPair` -> `resource.TestCheckTypeSetElemAttrPair`
* `tfawsresource.TestCheckTypeSetElemNestedAttrs` -> `resource.TestCheckTypeSetElemNestedAttrs`
* `tfawsresource.TestMatchTypeSetElemNestedAttrs` -> `resource.TestMatchTypeSetElemNestedAttrs`

Along with removing the `github.com/terraform-providers/terraform-provider-aws/aws/internal/tfawsresource` import line (can be handled by many editors on save).

Once all usage has changed, the `aws/internal/tfawsresource` directory can be removed.

The maintainers preference for broad changes like these is to batch changes by service or a few resources. A few acceptance tests should be ran to verify the migration.

### Affected Resource(s)

- [x] `aws_acm_certificate`
- [x] `aws_api_gateway_integration`
- [x] `aws_apigatewayv2_api`
- [x] `aws_apigatewayv2_authorizer`
- [x] `aws_apigatewayv2_stage`
- [x] `aws_appautoscaling_policy`
- [x] `aws_appmesh_route`
- [x] `aws_appmesh_virtual_gateway`
- [x] `aws_appmesh_virtual_node`
- [x] `aws_autoscaling_group`
- [x] `aws_autoscaling_policy`
- [x] `aws_autoscalingplans_scaling_plan`
- [x] `aws_backup_plan`
- [x] `aws_cloudformation_stack`
- [x] `aws_cloudfront_distribution`
- [x] `aws_codebuild_project`
- [x] `aws_codedeploy_deployment_group`
- [x] `aws_cognito_identity_pool`
- [x] `aws_cognito_user_pool_client`
- [x] `aws_cognito_user_pool`
- [x] `aws_config_config_rule`
- [x] `aws_db_instance`
- [x] `aws_db_option_group`
- [x] `aws_db_parameter_group`
- [x] `aws_db_proxy_default_target_group`
- [x] `aws_db_proxy`
- [x] `aws_db_security_group`
- [x] `aws_default_route_table`
- [x] `aws_default_security_group`
- [x] `aws_dms_event_subscription`
- [x] `aws_docdb_cluster_parameter_group`
- [x] `aws_dx_gateway_association_proposal`
- [x] `aws_dx_gateway_association`
- [x] `aws_dx_hosted_public_virtual_interface`
- [x] `aws_dx_public_virtual_interface`
- [x] `aws_dynamodb_table`
- [x] `aws_ec2_client_vpn_network_association`
- [x] `aws_ecs_cluster`
- [x] `aws_eks_cluster`
- [x] `aws_eks_cluster`
- [x] `aws_elastic_beanstalk_configuration_template`
- [x] `aws_elasticache_parameter_group`
- [x] `aws_elasticsearch_domain`
- [x] `aws_elb`
- [x] `aws_globalaccelerator_endpoint_group`
- [x] `aws_globalaccelerator_listener`
- [x] `aws_glue_partition`
- [x] `aws_guardduty_filter`
- [x] `aws_instance`
- [x] `aws_kinesisanalyticsv2_application`
- [x] `aws_kms_grant`
- [x] `aws_launch_configuration`
- [x] `aws_lb_listener_rule`
- [x] `aws_lex_bot_alias`
- [x] `aws_lex_slot_type`
- [x] `aws_mq_broker`
- [x] `aws_neptune_cluster_parameter_group`
- [x] `aws_neptune_cluster`
- [x] `aws_neptune_parameter_group`
- [x] `aws_network_acl`
- [x] `aws_opsworks_application`
- [x] `aws_opsworks_custom_layer`
- [x] `aws_organizations_organization`
- [x] `aws_proxy_protocol_policy`
- [x] `aws_rds_cluster_parameter_group`
- [x] `aws_rds_cluster`
- [x] `aws_redshift_parameter_group`
- [x] `aws_redshift_security_group`
- [x] `aws_route53_record`
- [x] `aws_route53_resolver_rule`
- [x] `aws_route53_resolver_rules`
- [x] `aws_route_table`
- [x] `aws_s3_bucket`
- [x] `aws_secretsmanager_secret_version`
- [x] `aws_security_group`
- [x] `aws_spot_fleet_request`
- [x] `aws_ssm_patch_baseline`
- [x] `aws_storagegateway_nfs_file_share`
- [ ] `aws_vpc_peering_connection_options`
- [x] `aws_waf_byte_match_set`
- [x] `aws_waf_geo_match_set`
- [x] `aws_waf_ipset`
- [x] `aws_waf_rate_based_rule`
- [x] `aws_waf_regex_match_set`
- [x] `aws_waf_regex_pattern_set`
- [x] `aws_waf_rule_group`
- [x] `aws_waf_rule`
- [x] `aws_waf_size_constraint_set`
- [x] `aws_waf_sql_injection_match_set`
- [x] `aws_waf_xss_match_set`
- [x] `aws_wafregional_byte_match_set`
- [x] `aws_wafregional_geo_match_set`
- [x] `aws_wafregional_ipset`
- [x] `aws_wafregional_rate_based_rule`
- [x] `aws_wafregional_regex_match_set`
- [x] `aws_wafregional_regex_pattern_set`
- [x] `aws_wafregional_rule_group`
- [x] `aws_wafregional_rule`
- [x] `aws_wafregional_size_constraint_set`
- [x] `aws_wafregional_sql_injection_match_set`
- [x] `aws_wafregional_web_acl`
- [x] `aws_wafregional_xss_match_set`
- [x] `aws_wafv2_ip_set`
- [x] `aws_wafv2_regex_pattern_set`
- [x] `aws_wafv2_rule_group`
- [x] `aws_wafv2_web_acl_logging_configuration`
- [x] `aws_wafv2_web_acl`

### References

* [Contributing Guide on Running/Writing Acceptance Testing](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/contributing/running-and-writing-acceptance-tests.md)

**Comment by breathingdust** [comment]
Big thanks to @mattburgess for your work on this! 👍
