### ISSUE TITLE
Add support for adding WAF to AppSync API

### ISSUE THREAD

**Issue by jnelson788** [hashicorp/terraform-provider-aws#15897]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS AppSync now has support to add an AWS WAF. Please add this new functionality in terraform

### New or Affected Resource(s)

* aws_appsync_graphql_api

### Potential Terraform Configuration

```hcl
resource "aws_waf_ipset" "ipset" {
  name = "tfIPSet"

  ip_set_descriptors {
    type  = "IPV4"
    value = "192.0.7.0/24"
  }
}

resource "aws_waf_rule" "wafrule" {
  depends_on  = [aws_waf_ipset.ipset]
  name        = "tfWAFRule"
  metric_name = "tfWAFRule"

  predicates {
    data_id = aws_waf_ipset.ipset.id
    negated = false
    type    = "IPMatch"
  }
}

resource "aws_waf_web_acl" "waf_acl" {
  depends_on = [
    aws_waf_ipset.ipset,
    aws_waf_rule.wafrule,
  ]
  name        = "tfWebACL"
  metric_name = "tfWebACL"

  default_action {
    type = "ALLOW"
  }

  rules {
    action {
      type = "BLOCK"
    }

    priority = 1
    rule_id  = aws_waf_rule.wafrule.id
    type     = "REGULAR"
  }
}

resource "aws_appsync_graphql_api" "example_with_waf" {
  authentication_type = "API_KEY"
  name = "example"
  web_acl_id = aws_waf_web_acl.waf_acl.id

# ... other configuration ...
}
```

### References

* #0000

**Comment by anGie44** [comment]
Hi @jnelson788, thank you for creating this issue! Looking at the dev guides for WAF and WAF Classic, I believe this AppSync support is only available to Terraform AWS Provider `wafv2` resources at this time as described here https://docs.aws.amazon.com/waf/latest/developerguide/web-acl-associating-aws-resource.html (WAF)
vs. 
https://docs.aws.amazon.com/waf/latest/developerguide/classic-web-acl-associating-cloudfront-distribution.html (WAF Classic)

I would just note to update this in the description unless support is added by AWS to all WAF related resources (including Classic)

**Comment by DrFaust92** [comment]
Closing as the question was answered
