### ISSUE TITLE
Create an aws ssm association with Target as a resource group.

### ISSUE THREAD

**Issue by shivansh931** [hashicorp/terraform-provider-aws#15895]
### Terraform code
```hcl
resource "aws_ssm_association" "test_association" {
  count = "${var.deploy_patch_ssm_automation ? 1 : 0}"
  association_name = "patch_deployment-${var.environment}-2"
  name  = "patch_deployment-${var.environment}-${data.aws_region.current.name}"
  automation_target_parameter_name = "InstanceId"
  targets {
    key    = "ResourceGroup"
    values = ["${aws_resourcegroups_group.dev_wcfserver[count.index].name}"]
  }
  depends_on = [
    "aws_ssm_document.patch_deployment_doc"
  ]
}
```

### Debug Output

```
undefinedTerraform v0.12.2

Initializing plugins and modules...
2020/10/28 12:53:19 [DEBUG] Using modified User-Agent: Terraform/0.12.2 TFE/v202005-2
aws_ssm_association.test_association[0]: Destroying... 
aws_ssm_document.test_document[0]: Creating...
aws_ssm_association.test_association[0]: Destruction complete after 0s
aws_ssm_document.test_document[0]: Creation complete after 0s [id=testDocument]
aws_ssm_association.test_association[0]: Creating...

Error: leftover module module.start-patch-deployment in state that should have been removed; this is a bug in Terraform and should be reported

Error: Error creating SSM association: InvalidTarget: Unsupported Target Type

  on ssm.tf line 134, in resource "aws_ssm_association" "test_association":
 134: resource "aws_ssm_association" "test_association" {
```

### Expected Behavior

``` An association with target as resource group should be launched.```

### Cuurent Behavior

``` Even if the association is created with required resource grouo as target there are no servers showing in target, not sure why?```

**Comment by bill-rich** [comment]
I believe resource groups are supported as targets in the existing `ssm_associtiation` resource, but I am not certain of the correct input to make that work.

**Comment by marpada** [comment]
Using the key `resource-groups:Name` works for adding a Resource Group as a target, the documentation incorrectly states that only the keys `tag:Tag Name` or `InstanceIds` are allowed.

**Comment by i255d** [comment]
marpada I get this error when I tried it:
Error: Error creating SSM association: InvalidTarget: Cannot pass target type resource-groups:Name into an automation association
but when I try just resource-groups, I get this: 
Error: Error creating SSM association: InvalidTarget: Unsupported target key: resource-groups, can either be InstanceIds, aws:NoOpAutomationTag, resource-groups:name, tag-key or start with tag:
Grrrrrrrrrrr

**Comment by i255d** [comment]
After trying this over and over, I think the key work in the error is "automation association".
Error: Error creating SSM association: InvalidTarget: Cannot pass target type resource-groups:Name into an automation association

So I think I need to change the document type form automation to command or something like that.
