### ISSUE TITLE
Race condition between pinpoint event stream and dependencies not handled

### ISSUE THREAD

**Issue by jwilmoth-nc** [hashicorp/terraform-provider-aws#15899]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

* terragrunt version v0.25.5
* Terraform version: 0.13.5
* hashicorp/aws version = "~> 3.12.0"

### Affected Resource(s)

* aws_pinpoint_event_stream
* aws_kinesis_firehose_delivery_stream

### Terraform Configuration Files

Settup is identical to https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_event_stream#example-usage except we're using a `aws_kinesis_firehose_delivery_stream` instead of the `aws_kinesis_stream` in the example.  Please note that adding explicit `depends_on` did not resolve the issue.

```hcl
resource "aws_pinpoint_event_stream" "transaction_app_event_stream" {
  application_id         = aws_pinpoint_app.transaction_app.application_id
  destination_stream_arn = aws_kinesis_firehose_delivery_stream.pinpoint_event_delivery_stream.arn
  role_arn               = aws_iam_role.pinpoint_kinesis_delivery_stream_role.arn
  depends_on = [
    aws_iam_role.pinpoint_kinesis_delivery_stream_role,
    # make sure the role's policy is present
    aws_iam_role_policy.pinpoint_kinesis_delivery_stream_policy,
    aws_kinesis_firehose_delivery_stream.pinpoint_event_delivery_stream
  ]
}
```

### Expected Behavior

We have a module that creates a pinpoint event stream along with the kinesis delivery stream and iam role needed to access the delivery stream.  This is pretty much identical to the https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_event_stream#example-usage.  The only difference is we're using a delivery stream instead of a data stream.

Pinpoint Event stream should've been created with the configured `destination_stream_arn` and `role_arn` which are also defined in the same module.

### Actual Behavior

All resources in the module except the `aws_pinpoint_event_stream` are created successfully.  The event streams error with the following message.  Simply re-running apply immediately after the failure successfully creates the event streams.

module.pinpoint.aws_iam_role_policy.pinpoint_kinesis_delivery_stream_policy: Creating...
module.pinpoint.aws_iam_role_policy.pinpoint_kinesis_delivery_stream_policy: Creation complete after 1s [id=role-dev-navigating-care-pinpoint-event-delivery-stream:delivery_stream_policy]
module.pinpoint.aws_pinpoint_event_stream.info_app_event_stream: Creating...
module.pinpoint.aws_pinpoint_event_stream.transaction_app_event_stream: Creating...

Error: error putting Pinpoint Event Stream for application ***masked***: BadRequestException: Destination stream validation failed. Check Destination and Role ARN values and make sure the IAM Role is configured correctly.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "248a4927-ddab-4cc8-9444-b65379e795ae"
  },
  Message_: "Destination stream validation failed. Check Destination and Role ARN values and make sure the IAM Role is configured correctly.",
  RequestID_: "248a4927-ddab-4cc8-9444-b65379e795ae"
}

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by DrFaust92** [comment]
Was able to recreate by making some change to the test config. opened a PR to address this
