### ISSUE TITLE
Additional Pinpoint resources

### ISSUE THREAD

**Issue by jwilmoth-nc** [hashicorp/terraform-provider-aws#15900]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There are a number of Cloudformation resource definitions for Pinpoint that don't have a Terraform equivalent.

### New or Affected Resource(s)

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pinpoint-emailtemplate.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pinpoint-smstemplate.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pinpoint-segment.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pinpoint-campaign.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pinpoint-voicechannel.html

**Comment by sreimer15** [comment]
Hi!
Let's say that I create these resources using [cloudformation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudformation_stack), and later these cloudformation resources are added to the AWS provider, is there a way to give terraform ownership of them without having to recreate the resource?
Thank you!

**Comment by 06kellyjac** [comment]
You'll have to write out the HCL for the existing resource yourself (for the import to fit into) but should be able to import the resource: https://www.terraform.io/docs/cli/import/index.html
