### ISSUE TITLE
Support the use of CloudFront Trusted Key Group as a signer

### ISSUE THREAD

**Issue by briananstett** [hashicorp/terraform-provider-aws#15912]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
AWS CloudFront now supports the ability to create public keys and a Trust Key Group which can be used as a signer for CloudFront signed URLs and cookies. Historically you had to use a key pair that was created by the root account user.

![image](https://user-images.githubusercontent.com/18585217/97610694-9d2e5380-19eb-11eb-9504-0c8b401df5f0.png)

The current AWS terraform provider appears to support the creation of a CloudFront Public Key but does not appear to have support for creating the Trusted Key Group nor support for using that Trusted Key Group in the distribution.

### New or Affected Resource(s)
* A new resource for a Trusted Key Group may need to be created.
* The existing aws_cloudfront_distribution resource may need to be updated to support the use of a Trust Key Group as a signer.

### References
* https://aws.amazon.com/about-aws/whats-new/2020/10/cloudfront-iam-signed-url/
* https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-trusted-signers.html

**Comment by Manny334** [comment]
👍

**Comment by schollii** [comment]
Seems this would need a new resource type `aws_cloudfront_key_group` that refers to a `aws_cloudfront_public_key` (that type of resource already exists), and a new field in `aws_cloudfront_distribution` to refer to the key group. Been using tf for 3 years but never created a new resource type so I have no idea how hard this is, is this something I could take on?

**Comment by shuheiktgw** [comment]
I've started working on this issue 👍

**Comment by shuheiktgw** [comment]
As a first step, I've added `aws_cloudfront_key_group` resource, so please upvote the PR for a faster review 🙏 

- https://github.com/hashicorp/terraform-provider-aws/pull/17041

Once the PR is merged, I'm going to modify `aws_cloudfront_distribution` to support the key group.

**Comment by shuheiktgw** [comment]
I've started working on adding `trusted_key_groups` argument since the previous PR has been merged

**Comment by shuheiktgw** [comment]
It's now ready for review!
https://github.com/hashicorp/terraform-provider-aws/pull/18644

**Comment by takayamaki** [comment]
I used this resource in work. Thank you!
