### ISSUE TITLE
Possibility to Add multiple subnets on Emr

### ISSUE THREAD

**Issue by rubenssoto** [hashicorp/terraform-provider-aws#15911]
Hello,

Is a best pratice to use multiple subnets on EMR when you are using instance fleets, but terraform only allow to configure one subnet by option subnet_id.
I will be good if we could configure many subnets as we want.

thank you

**Comment by bill-rich** [comment]
Thank you for bringing this up. We are currently using `Ec2SubnetId` to assign the subnet, but there is another argument we could be using instead (`Ec2SubnetIds`). To be backwards compatible, we will need to add a new argument to the schema (probably `subnet_ids`) that would conflict with the existing `subnet_id`.

**Comment by kristerjaanhold** [comment]
@bill-rich are there any updates on this? Or branches we could follow?

**Comment by steveburton4** [comment]
@bill-rich Is there any update on this do you know?

**Comment by kasparg** [comment]
Hi, @bill-rich @philnichol how could we bump up https://github.com/hashicorp/terraform-provider-aws/pull/17219 (that resolve this issue)?
