### ISSUE TITLE
Support the new Application Load Balancer gRPC workload & HTTP/2 protocol versions

### ISSUE THREAD

**Issue by chappoo** [hashicorp/terraform-provider-aws#15929]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS have added support for gRPC workloads with end to end HTTP/2 to the Application Load Balancer.  The `aws_lb_target_group` resource needs to be enhanced to support these additional protocol versions.

### New or Affected Resource(s)

* aws_lb_target_group

### Potential Terraform Configuration

```hcl
# gRPC
resource "aws_lb_target_group" "grpc" {
  name             = "tf-example-lb-tg"
  port             = 5500
  protocol         = "HTTPS"
  protocol_version = "gRPC"
  vpc_id           = aws_vpc.main.id
}

# http2
resource "aws_lb_target_group" "http2" {
  name             = "tf-example-lb-tg"
  port             = 443
  protocol         = "HTTPS"
  protocol_version = "HTTP2"
  vpc_id           = aws_vpc.main.id
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2020/10/application-load-balancers-enable-grpc-workloads-end-to-end-http-2-support/
* https://aws.amazon.com/blogs/aws/new-application-load-balancer-support-for-end-to-end-http-2-and-grpc/

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.35.18](https://github.com/aws/aws-sdk-go/releases/tag/v1.35.18):

* #15930
