### ISSUE TITLE
Storage Gateway - SMB file share name

### ISSUE THREAD

**Issue by rmdashrfslash** [hashicorp/terraform-provider-aws#15937]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Hi - I'm attempting to setup a SMB file share on an AWS Storage Gateway and unfortunately it does not appear that I can set the share name with terraform.  I can do it from the GUI and from the command line using --file-share-name.

Please add an argument to the resource aws_storagegateway_smb_file_share that would allow us to set the file share name.  Maybe "file_share_name" or  simply "name".

aws_storagegateway_smb_file_share

### Potential Terraform Configuration

```hcl
resource "aws_storagegateway_smb_file_share" "example" {
  authentication  = "ActiveDirectory"
  file_share_name = "example_name"
  gateway_arn     = aws_storagegateway_gateway.example.arn
  location_arn    = aws_s3_bucket.example.arn
  role_arn        = aws_iam_role.example.arn
}
```

### References

* #0000

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.35.18](https://github.com/aws/aws-sdk-go/releases/tag/v1.35.18):

* #15930

**Comment by gazoakley** [comment]
This also blocks use when creating a share for an S3 bucket with a key prefix. From the docs:

> FileShareName must be set if an S3 prefix name is set in LocationARN.

I'm interesting in taking a look at this.
