### ISSUE TITLE
r/aws_ec2_transit_gateway_vpc_attachment: Support Appliance mode

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#15936]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

>Support for Appliance mode on Transit Gateway that simplifies deployment of stateful network appliances.

### New or Affected Resource(s)

* [`aws_ec2_transit_gateway_vpc_attachment`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_transit_gateway_vpc_attachment)

### Potential Terraform Configuration

```hcl
resource "aws_ec2_transit_gateway_vpc_attachment" "example" {
  appliance_mode_support = true
}
```

### References

[API Reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTransitGatewayVpcAttachment.html).
[User Guide](https://docs.aws.amazon.com/vpc/latest/tgw/transit-gateway-appliance-scenario.html).

Requires [AWS SDK v1.35.18](https://github.com/aws/aws-sdk-go/releases/tag/v1.35.18):

* #15930

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 3.15.0 of the Terraform AWS Provider, today or tomorrow. Thanks to @philnichol for the implementation. 👍
