### ISSUE TITLE
aws_kinesis_firehose_delivery_stream returns ARN for AWS public when in GovCloud

### ISSUE THREAD

**Issue by donnyspi** [hashicorp/terraform-provider-aws#15946]
aws_kinesis_firehose_delivery_stream.XXXXXXX.arn returns an ARN starting with arn:aws: instead of arn:aws-us-gov: when using GovCloud

**Comment by DrFaust92** [comment]
Hi,

It has been a while since this was opened, is this still and issue?

Code-wise it seems we are using the AEN returned from AWS API, meaning there is an issue upstream.
