### ISSUE TITLE
Multiple subnet_id-s are not supported with EMR instance fleets

### ISSUE THREAD

**Issue by kristerjaanhold** [hashicorp/terraform-provider-aws#15970]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Summary

When using instance fleets in EMR one can not specify multiple subnet_id-s as part of ec2_attributes block since it expects a string https://github.com/terraform-providers/terraform-provider-aws/blob/8fc7ebf0d5bc893921207efbbc4ea5696b147cde/aws/resource_aws_emr_cluster.go#L112

However, to spawn EC2 instances in multiple AZ-s (to tackle instance availability issues), providing multiple subnet_id-s is recommended (https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-instance-fleet.html).

For reference, the CLI command looks something like this when creating an EMR cluster with instance fleets in multiple AZ-s:
`... --ec2-attributes InstanceProfile=EMR_EC2_DefaultRole,SubnetIds=['subnet-ab12345c','subnet-de67890f'] ... `

### Affected Resource(s)

* aws_emr_cluster

**Comment by philnichol** [comment]
Looks like this was also raised here: #15911

**Comment by kasparg** [comment]
Hi, @philnichol how could we bump https://github.com/hashicorp/terraform-provider-aws/pull/17219 (that resolves this issue)?

**Comment by philnichol** [comment]
> Hi, @philnichol how could we bump https://github.com/hashicorp/terraform-provider-aws/pull/17219 (that resolves this issue)?

Hey @kasparg unfortunatey I'm not a maintainer so don't have input on this but with the upvotes I'm sure it will get picked soon enough.
