### ISSUE TITLE
aws_apigatewayv2_integration timeout_milliseconds input should have a ceiling of 30,000

### ISSUE THREAD

**Issue by tscully49** [hashicorp/terraform-provider-aws#16002]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.12.26
+ provider.aws v2.70.0
(also tested with AWS provider version 3.13.0)
```

### Affected Resource(s)

* aws_apigatewayv2_integration resource

### Terraform Configuration Files

```hcl
resource "aws_apigatewayv2_integration" "my_lambda" {
  api_id           = aws_apigatewayv2_api.api_gateway.id
  integration_type = "AWS_PROXY"

  connection_type              = "INTERNET"
  integration_method         = "POST"
  payload_format_version  = "2.0"
  timeout_milliseconds      = 30000
  integration_uri                  = aws_lambda_function.lamba.arn
}
```

### Expected Behavior

Should be allowed to set the input timeout_milliseconds to a value up to 30000 per the documentation https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html.

### Actual Behavior

The provider throws an error if a value above 29000 is given.

### Important Factoids

Documentation here (https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html) claims that the timeout for integrations is 30 seconds.

**Comment by ewbankkit** [comment]
@tscully49 Thanks for raising this issue.
You are correct, the default and maximum timeouts are [different for WebSocket and HTTP APIs](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/apis-apiid-integrations-integrationid.html#apis-apiid-integrations-integrationid-prop-integration-timeoutinmillis):

> Custom timeout between 50 and 29,000 milliseconds for WebSocket APIs and between 50 and 30,000 milliseconds for HTTP APIs. The default timeout is 29 seconds for WebSocket APIs and 30 seconds for HTTP APIs.

**Comment by warrenstephens** [comment]
Looks like I am seeing the 29000 limit in provider version **3.15**.

My integration is currently deployed with 30000, and terraform wants to change it to 29000.

**Comment by ewbankkit** [comment]
@warrenstephens Can you paste the relevant configuration?
