### ISSUE TITLE
aws_cloudfront_distribution should allow specifying ConnectionAttempts on an origin

### ISSUE THREAD

**Issue by don-code** [hashicorp/terraform-provider-aws#16009]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

CloudFront origins allow specifying a `ConnectionAttempts` parameter ([relevant docs from the SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/cloudfront/#Origin)), but this is not exposed through Terraform. Origins are always created with the default policy of three retries for failed requests.

A downstream effect of having this set to the default of three is that undesirable extra load can be placed on endpoints which do not respond within the timeout period.

### New or Affected Resource(s)

* aws_cloudfront_distribution

### Potential Terraform Configuration

```hcl
resource "aws_cloudfront_distribution" "foo" {
# [...]
  origin {
    custom_origin_config {
      http_port = 80
      https_port = 443
      origin_protocol_policy = "https-only"
      origin_ssl_protocols = ["TLSv1.2"]
    }

    connection_attempts = 1
    domain_name = var.origin_dns_name
    origin_id = "default"
  }
# [...]
}
```

### References

* aws/aws-sdk-go#3354 introduced this parameter.

**Comment by philnichol** [comment]
@don-code  hope you don't mind I raised a PR for this.

**Comment by don-code** [comment]
I don't mind at all!
