### ISSUE TITLE
Resource aws_lex_bot constantly changes the version, possibly based on not pulling description

### ISSUE THREAD

**Issue by nateww** [hashicorp/terraform-provider-aws#16007]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
% terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.13.0
```
### Affected Resource(s)

* aws_lex_bot

### Terraform Configuration Files

```hcl
resource "aws_lex_bot" "order-flowers" {
  name        = "OrderFlowers"
  description = "Bot to order flowers on the behalf of a user"

  create_version              = true
  locale                      = "en-US"
  voice_id                    = "Salli"
  child_directed              = false
  idle_session_ttl_in_seconds = 600
  process_behavior            = "BUILD"

  abort_statement {
    message {
      content      = "Sorry, I am not able to assist at this time"
      content_type = "PlainText"
    }
  }

  clarification_prompt {
    max_attempts = 2

    message {
      content      = "I didn't understand you, what would you like to do?"
      content_type = "PlainText"
    }
  }

  intent {
    intent_name    = "OrderFlowers"
    intent_version = "1"
  }
}
```

### Debug Output

Everytime `terraform plan` is run, it wants to modify the bot, stating that the description field needs to be added/changed.

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_lex_bot.order-flowers will be updated in-place
  ~ resource "aws_lex_bot" "order-flowers" {
        arn                             = "arn:aws:lex:us-west-2:redacted:bot:OrderFlowers"
        checksum                        = "0f80a16f-5845-4a74-8a8b-672e724a89b5"
        child_directed                  = false
        create_version                  = true
        created_date                    = "2020-11-03T17:22:35Z"
      + description                     = "Bot to order flowers on the behalf of a user"
        detect_sentiment                = false
        enable_model_improvements       = false
..
Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behavior

It should not attempt to modify the resource, as nothing has changed.  Even if I run a `terraform apply` on the resource, the next run will show the same results as before.  **I suspect (but did not verify) that the description field is not being fetched from AWS, so the description field (if set) will always be different.** This suspicion is reinforced by the fact that if I remove the description field from the resource, terraform plan behaves properly.

A `terraform apply` run should return with no changes needing to be made.
```
No changes. Infrastructure is up-to-date.
```
### Actual Behavior

Nothing happened.

### Steps to Reproduce

1. Create a lex_bot resource which contains a description field, and once it's fully instantiated, attempt to run `terraform plan` without making any changes to the terraform files.  It should not show any differences.

### Important Factoids

The field `create_version = true` is set, which may have something to do with the results.

### References

https://docs.aws.amazon.com/lex/latest/dg/gs-cli-create.html

**Comment by philnichol** [comment]
I was able to reproduce this issue also. Weirdly it looks like description is never actually being set in AWS. Which I guess explains why TF wants to keep trying to add it on each apply.
Can't seem to spot where the problem is though, code looks like it should be setting the description correctly https://github.com/hashicorp/terraform-provider-aws/blob/master/aws/resource_aws_lex_bot.go.
