### ISSUE TITLE
aws_batch_job_definition resource recreated each time on AWS 3.10

### ISSUE THREAD

**Issue by shlomi-viz** [hashicorp/terraform-provider-aws#16014]
`aws_batch_job_definition` reosurce always recreate the same resource even if no changes were made. If I run it with AWS V2.7 I get
```bash
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```bash
terraform --version
Terraform v0.12.29
+ provider.aws v3.13.0
+ provider.template v2.1.2
```

### Affected Resource(s)

* aws_batch_job_definition

### Terraform Configuration Files

```hcl
data "template_file" "job_definition" {
  template = "${file("${path.module}/templates/job_definition.json.tpl")}"

  vars = {
    image                 = var.image_tag
    memory_limit          = var.memory_limit
    cpu_limit             = var.cpu_limit
    resource_requirements = var.resource_requirements
    log_group_name        = var.log_group_name
  }
}

resource "aws_batch_job_definition" "job_definition" {
  name = var.job_definition_name
  type = "container"

  container_properties = data.template_file.job_definition.rendered

  timeout {
    attempt_duration_seconds = var.attempt_duration_seconds
  }

  retry_strategy {
    attempts = 2
  }
}
```

`job_definition.json.tpl`
```tpl
{
    "image": "${image}",
    "memory": ${memory_limit},
    "vcpus": ${cpu_limit},
    "resourceRequirements": [${resource_requirements}],
	"logConfiguration": {
		"logDriver": "awslogs",
		"options": {
			"awslogs-group": "${log_group_name}"
		}
	}
}
```

### Expected Behavior

Resources shouldn't be recreate, no changes. 

### Actual Behavior

Resources is replaced (new revision) each time.

### Steps to Reproduce

1. Run `terraform plan`
2. Terraform want to update all resources
3. Change code to use AWS provider 2.7
1. Run `terraform plan`
1. See `Apply complete! Resources: 0 added, 0 changed, 0 destroyed.`

### References

Terraform Plan:
```hcl
  # module.job_qa.aws_batch_job_definition.job_definition must be replaced
-/+ resource "aws_batch_job_definition" "job_definition" {
      ~ arn                  = "arn:aws:batch:us-east-2:XXXXXX:job-definition/job-qa:3" -> (known after apply)
      ~ container_properties = jsonencode(
          ~ {
              - command              = [] -> null
              - environment          = [] -> null
                image                = "XXXXXX:dkr.ecr.us-east-2.amazonaws.com/repo:qa"
              ~ logConfiguration     = {
                    logDriver     = "awslogs"
                    options       = {
                        awslogs-group = "/ecs/qa"
                    }
                  - secretOptions = [] -> null
                }
                memory               = 15259
              - mountPoints          = [] -> null
                resourceRequirements = [
                    {
                        type  = "GPU"
                        value = "1"
                    },
                ]
              - secrets              = [] -> null
              - ulimits              = [] -> null
                vcpus                = 2
              - volumes              = [] -> null
            } # forces replacement
        )
      ~ id                   = "arn:aws:batch:us-east-2:XXXXXX:job-definition/qa:3" -> (known after apply)
        name                 = "qa"
      - parameters           = {} -> null
      ~ revision             = 3 -> (known after apply)
      - tags                 = {} -> null
        type                 = "container"

        retry_strategy {
            attempts = 2
        }

        timeout {
            attempt_duration_seconds = 1200
        }
    }
```

* [13629](https://github.com/hashicorp/terraform-provider-aws/issues/13629)
* [11998](https://github.com/hashicorp/terraform-provider-aws/issues/11998)
* [15560](https://github.com/hashicorp/terraform-provider-aws/issues/15560)

**Comment by bflad** [comment]
If I had to adventure an immediate guess, it is that our containers properties equivalency code needs `logConfiguration.secretOptions` to treat `[]` and missing as equal, similar as we've needed for many of the other top-level arrays ([code reference](https://github.com/hashicorp/terraform-provider-aws/blob/78b3139a51459235ee198269a8deefdba5e7ad2b/aws/internal/service/batch/equivalency/container_properties.go#L16)).

@shlomi-viz does it work if you update your container properties template to set `secretOptions` equal to `[]`?

**Comment by shlomi-viz** [comment]
Thanks @bflad that fixed it.
