### ISSUE TITLE
Add Cross Account Eventbus as target for cloudwatch event rules.

### ISSUE THREAD

**Issue by Vishal2696** [hashicorp/terraform-provider-aws#16015]
Currently from reading the docs provisioned for cloudwatch-event target, there doesn't seem to be support for cross account event-bus https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_target#argument-reference. 

Hence I would request to add that feature in future release.

**Provider-Version:** 3.13.0

**Comment by gdavison** [comment]
Hi @Vishal2696, thanks for submitting this. We have an open issue for adding cross-account event bus targets, #8759, so I'm going to close this issue.
