### ISSUE TITLE
Support for RabbitMQ engine on aws_mq_broker

### ISSUE THREAD

**Issue by richardgavel** [hashicorp/terraform-provider-aws#16027]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for RabbitMQ as an engine on the aws_mq_broker resource

### New or Affected Resource(s)

* aws_mq_broker

### References

https://aws.amazon.com/blogs/aws/amazon-mq-update-new-rabbitmq-message-broker-service/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+AmazonWebServicesBlog+%28Amazon+Web+Services+Blog%29

**Comment by yardensachs** [comment]
Oy I posted one also #16030

**Comment by ewbankkit** [comment]
@yardensachs Thanks for raising this issue.
I'm going to close this one as a duplicate so that we can concentrate discussion in https://github.com/hashicorp/terraform-provider-aws/issues/16030.
