### ISSUE TITLE
APIGatewayV2 API resource - possible arn generation bug

### ISSUE THREAD

**Issue by aferg439** [hashicorp/terraform-provider-aws#16023]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Tested with:
terraform 0.13.4, 0.12.20
aws provider 3.10, 2.70

### Affected Resource(s)

aws_apigatewayv2_api

### Terraform Configuration Files

```
resource "aws_apigatewayv2_api" "example_api" {
  name                     = "example_name"
  protocol_type        = "HTTP"
  description            = "Proxy gateway to handle lambda requests"
  tags                       = merge(local.product_tags, map("name", "example_gateway"))

  cors_configuration {
    allow_credentials = false
    allow_headers     = ["Authorization", "Content-Type", "X-Amz-Date", "X-Amz-Security-Token", "X-Api-Key"]
    allow_methods     = ["GET", "POST", "OPTIONS"]
    allow_origins     = ["*"]
    max_age           = 7200
  }
}
```

### Debug Output

Company blocks Gist sooooo, oh well.

### Expected Behavior

Create the API GatewayV2 API resource

### Actual Behavior

Error: error creating API Gateway v2 API: AccessDeniedException: Role is not authorized to perform: apigateway:POST on resource: arn:aws:apigateway:us-east-1::arn:aws:apigateway:us-east-1::/tags/{string of text here}

**See ARN above^** it appears to be somewhat duplicated.

The role being used has permissions to make any action on said resources (apigateway:*) but stated resources don't include it duplicating a portion of the ARN....

**UPDATE** The resource creates successfully once the tags are removed from the resource. However, since tags are supported (per the documentation) it's probably still an issue.

Thanks in advance and apologies if I'm an idiot and missed something obvious :) 

### Steps to Reproduce

1.  `terraform apply`

* #0000

**Comment by ewbankkit** [comment]
@aferg439 Thanks for raising this issue.
Tags are specified as part of the `CreateApi` call:

https://github.com/hashicorp/terraform-provider-aws/blob/a795ecaeb55187b6a346d3a9a3da1b1e062fea48/aws/resource_aws_apigatewayv2_api.go#L204-L212

so it's not the Terraform provider that is specifying that ARN, it must be internal to the AWS service.
I suggest opening a ticket with AWS support to get some clarity on this.

**Comment by aferg439** [comment]
Thanks for the quick response! I've reached out to AWS and I'll update the issue when I hear back from them.

**Comment by bflad** [comment]
Closing due to lack of response. This was likely due to an internal API issue, but if there actually is a Terraform AWS Provider issue here, please feel free to open a new bug report and we will take a fresh look. 👍
