### ISSUE TITLE
Support EC2 rebalancing

### ISSUE THREAD

**Issue by scalp42** [hashicorp/terraform-provider-aws#16033]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS introduced EC2 rebalancing for ASG, EC2 Fleet and Spot Fleet.

### New or Affected Resource(s)

* aws_autoscaling_group
* aws_spot_fleet

### References

See: https://aws.amazon.com/about-aws/whats-new/2020/11/introducing-ec2-instance-rebalance-recommendation-for-ec2-spot-instances/

Flag: https://docs.aws.amazon.com/autoscaling/ec2/userguide/capacity-rebalance.html

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.35.21](https://github.com/aws/aws-sdk-go/releases/tag/v1.35.21):

* https://github.com/hashicorp/terraform-provider-aws/pull/16021

**Comment by ewbankkit** [comment]
##### [`aws_autoscaling_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group)

```hcl
resource "aws_autoscaling_group" "example" {
  capacity_rebalance = true
}
```

##### [`aws_spot_fleet_request`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/spot_fleet_request)

```hcl
resource "aws_spot_fleet_request" "example" {
  spot_maintenance_strategies {
    capacity_rebalance {
      replacement_strategy = "launch"
    }
  }
}
```

**Comment by isaac88** [comment]
Hello @ewbankkit,
Any updates regarding that ?

Thanks

**Comment by grigorov** [comment]
@ewbankkit https://github.com/hashicorp/terraform-provider-aws/pull/16085 is merged.

**Comment by ewbankkit** [comment]
A PR to address this is forthcoming. The contributor is waiting on some formalities.
