### ISSUE TITLE
Fix and Enable tfproviderlint AT009 Check

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#16046]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

tfproviderlint version 0.20.0 added the [AT009 check](https://github.com/bflad/tfproviderlint/tree/master/passes/AT009) for determining `acctest.RandStringFromCharSet()` calls that can be simplified to `acctest.RandString()`, which we have a few reports in the repository, e.g.

```
/Users/bflad/src/github.com/hashicorp/terraform-provider-aws/aws/data_source_aws_lex_bot_alias_test.go:12:11: AT009: should use RandString call instead
11	func testAccDataSourceAwsLexBotAlias_basic(t *testing.T) {
12		rName := acctest.RandStringFromCharSet(8, acctest.CharSetAlpha)
13		dataSourceName := "data.aws_lex_bot_alias.test"
```

### Affected Resource(s)

- [ ] `aws/data_source_aws_lex_bot_alias_test.go`
- [ ] `aws/data_source_aws_lex_bot_test.go`
- [ ] `aws/data_source_aws_lex_intent_test.go`
- [ ] `aws/data_source_aws_lex_slot_type_test.go`
- [ ] `aws/resource_aws_appmesh_virtual_node_test.go`
- [ ] `aws/resource_aws_cloudformation_stack_set_test.go`
- [ ] `aws/resource_aws_elb_test.go`
- [ ] `aws/resource_aws_iam_role_policy_test.go`
- [ ] `aws/resource_aws_iam_user_policy_test.go`
- [ ] `aws/resource_aws_lb_test.go`
- [ ] `aws/resource_aws_lex_bot_alias_test.go`
- [ ] `aws/resource_aws_lex_bot_test.go`
- [ ] `aws/resource_aws_lex_intent_test.go`
- [ ] `aws/resource_aws_lex_slot_type_test.go`
- [ ] `aws/resource_aws_load_balancer_listener_policy_test.go`
- [ ] `aws/resource_aws_service_discovery_http_namespace_test.go`
- [ ] `aws/resource_aws_service_discovery_service_test.go`
- [ ] `aws/resource_aws_vpn_connection_test.go`
- [ ] `aws/resource_aws_worklink_fleet_test.go`
- [ ] `aws/resource_aws_worklink_website_certificate_authority_association_test.go`
- [ ] `aws/validators_test.go`

**Comment by mattburgess** [comment]
I see the upstream bug has now been fixed. Here's the list of offending files; there's 243 violations across them currently:

- [ ] `data_source_aws_dynamodb_table_test.go`
- [ ] `data_source_aws_elb_test.go`
- [ ] `data_source_aws_instance_test.go`
- [ ] `data_source_aws_kms_key_test.go`
- [ ] `data_source_aws_lb_listener_test.go`
- [ ] `data_source_aws_lb_target_group_test.go`
- [ ] `data_source_aws_lb_test.go`
- [ ] `data_source_aws_rds_cluster_test.go`
- [ ] `data_source_aws_route53_resolver_rules_test.go`
- [ ] `resource_aws_alb_target_group_test.go`
- [ ] `resource_aws_backup_plan_test.go`
- [ ] `resource_aws_cognito_identity_pool_roles_attachment_test.go`
- [ ] `resource_aws_cognito_identity_pool_test.go`
- [ ] `resource_aws_cognito_resource_server_test.go`
- [ ] `resource_aws_cognito_user_group_test.go`
- [ ] `resource_aws_cognito_user_pool_client_test.go`
- [ ] `resource_aws_cognito_user_pool_domain_test.go`
- [ ] `resource_aws_ec2_traffic_mirror_session_test.go`
- [ ] `resource_aws_ec2_traffic_mirror_target_test.go`
- [ ] `resource_aws_elasticsearch_domain_test.go`
- [ ] `resource_aws_instance_test.go`
- [ ] `resource_aws_kms_key_test.go`
- [ ] `resource_aws_lb_listener_test.go`
- [ ] `resource_aws_lb_target_group_attachment_test.go`
- [ ] `resource_aws_lb_target_group_test.go`
- [ ] `resource_aws_lb_test.go`
- [ ] `resource_aws_ram_resource_share_accepter_test.go`
- [ ] `resource_aws_ram_resource_share_test.go`
- [ ] `resource_aws_ses_domain_dkim_test.go`
- [ ] `resource_aws_ses_domain_identity_test.go`
- [ ] `resource_aws_ses_domain_identity_verification_test.go`
- [ ] `resource_aws_ses_domain_mail_from_test.go`
- [ ] `resource_aws_ses_email_identity_test.go`
- [ ] `resource_aws_ses_identity_notification_topic_test.go`
- [ ] `resource_aws_ses_identity_policy_test.go`
- [ ] `resource_aws_shield_protection_test.go`
- [ ] `resource_aws_vpc_endpoint_connection_notification_test.go`
- [ ] `resource_aws_vpc_endpoint_route_table_association_test.go`
- [ ] `resource_aws_vpc_endpoint_service_allowed_principal_test.go`
- [ ] `resource_aws_vpc_peering_connection_test.go`
