### ISSUE TITLE
AWS ElasticSearch Custom endpoint support 

### ISSUE THREAD

**Issue by nnovaes** [hashicorp/terraform-provider-aws#16059]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Add support for AWS ElasticSearch custom endpoint 

### New or Affected Resource(s)

* aws_elasticsearch_domain

### References

[https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-customendpoint.html](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-customendpoint.html)

* #0000

**Comment by ewbankkit** [comment]
[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-elasticsearch-service-now-supports-defining-a-custom-name-for-your-domain-endpoint/).

Requires [AWS SDK v1.35.22](https://github.com/aws/aws-sdk-go/releases/tag/v1.35.22):

* https://github.com/hashicorp/terraform-provider-aws/pull/16071

Potential syntax:

```hcl
resource "aws_elasticsearch_domain" "example" {
  domain_endpoint_options {
    custom_endpoint_enabled         = true
    custom_endpoint                 = "example.com"
    custom_endpoint_certificate_arn = aws_acm_certificate.example.arn
  }
}
```

**Comment by matiaszilli** [comment]
Hi @ewbankkit. I can try to implement it. :smiley:

**Comment by tdmalone** [comment]
Current workaround:
```
resource "null_resource" "custom_endpoint" {
  provisioner "local-exec" {
    command = <<-EOF
      # Some settings here are duplicated from the ones set natively, so that we don't overwrite them.
      aws es update-elasticsearch-domain-config \
        --domain-name "${aws_elasticsearch_domain.main.domain_name}" \
        --domain-endpoint-options '{
          "EnforceHTTPS": ${aws_elasticsearch_domain.main.domain_endpoint_options.0.enforce_https},
          "TLSSecurityPolicy": "${aws_elasticsearch_domain.main.domain_endpoint_options.0.tls_security_policy}",
          "CustomEndpointEnabled": true,
          "CustomEndpoint": "${local.hostname}",
          "CustomEndpointCertificateArn": "${aws_acm_certificate.custom_endpoint.arn}"
        }'
    EOF
  }
}
```
