### ISSUE TITLE
Client Connection Handler for Client VPN Endpoint

### ISSUE THREAD

**Issue by KyleKotowick** [hashicorp/terraform-provider-aws#16056]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Client VPN Endpoints support a featured called "[Client Connection Handler](https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/connection-authorization.html)", which is a Lambda function that dynamically determines if a client should be allowed to connect or not. Currently, the Terraform AWS provider does not have any configuration option to support this feature.

### New or Affected Resource(s)

* aws_ec2_client_vpn_endpoint

### Potential Terraform Configuration

```hcl
aws_ec2_client_vpn_endpoint "client_vpn" {
  ... existing config options
  client_connect_handler_arn = aws_lambda_function.vpn_connection_handler.arn
}
```

Note that there are a couple restrictions on the Lambda that would be good to check. Namely, its name must start with the prefix "AWSClientVPN-" and it must have a timeout of 30 seconds.

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.35.21](https://github.com/aws/aws-sdk-go/releases/tag/v1.35.21):

* https://github.com/hashicorp/terraform-provider-aws/pull/16021

**Comment by ewbankkit** [comment]
Strictly speaking the new syntax should be:

```hcl
aws_ec2_client_vpn_endpoint "example" {
  client_connect_options {
    enabled = true

    lambda_function_arn = aws_lambda_function.example.arn
  }
}
```

to match the [AWS API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateClientVpnEndpoint.html#API_CreateClientVpnEndpoint_RequestParameters).

**Comment by choeflake** [comment]
Hi, could this issue get some prio?
