### ISSUE TITLE
Error when destroying global rds cluster (from Snapshot) when secondary cluster is attached.

### ISSUE THREAD

**Issue by marinsalinas** [hashicorp/terraform-provider-aws#16065]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.29
+ provider.aws v3.13.0

### Affected Resource(s)

- aws_rds_global_cluster

### Terraform Configuration Files

```hcl
data "aws_kms_alias" "this" {
  name  = "alias/rds"
}


# The source_db_cluster_identifier argument does not currently exist
resource "aws_rds_global_cluster" "global_cluster" {
  # ... other configuration ...
  source_db_cluster_identifier = aws_rds_cluster.example.id
force_destroy = true
}

resource "aws_rds_cluster" "example" {
  snapshot_identifier = aws_db_cluster_snapshot.example.id
 # ... other configuration ...

  storage_encrypted = true
  kms_key_id              =  data.aws_kms_alias.this.target_key_arn

  lifecycle {
    ignore_changes = [global_cluster_identifier]
  }
}

provider "aws" {
  alias  = "secondary"
  region = "us-west-2"
}

resource "aws_rds_cluster" "secondary" {
   providers = {
      aws.secondary = aws.secondary
   }

  global_cluster_identifier =  aws_rds_global_cluster.global_cluster.id
 # ... other configuration ...
  
storage_encrypted = true
  kms_key_id              =  data.aws_kms_alias.this.target_key_arn
}

```

### Expected Behavior

Terraform destroy should be with no errors.

### Actual Behavior

Terraform destroy is errored:

```log
Error: error removing RDS DB Cluster (arn:aws:rds:us-west-2:414158246671:cluster:dbtfmodules-mysql-rds-testing-global-us-west-2) from Global Cluster (dbtfmodules-mysql-rds-testing-global): InvalidParameterValue: Cluster arn:aws:rds:us-west-2:414158246671:cluster:dbtfmodules-mysql-rds-testing-global-us-west-2 is not found in global cluster dbtfmodules-mysql-rds-testing-global
	status code: 400, request id: 858997c6-de0f-4bc7-8553-769456e5aae3
```

### Steps to Reproduce

1. `terraform destroy`

### Important Factoids

I'm not sure why is not reaching this: https://github.com/hashicorp/terraform-provider-aws/blob/master/aws/resource_aws_rds_global_cluster.go#L256

**Comment by bflad** [comment]
Hi @marinsalinas 👋  The code you reference there was merged yesterday with https://github.com/hashicorp/terraform-provider-aws/pull/15938 and will release with version 3.14.0 of the Terraform AWS Provider in a few minutes (release is running now).
