### ISSUE TITLE
resource/aws_cloudwatch_event_target: ecs_target's launch_type should not have a default

### ISSUE THREAD

**Issue by ianneub** [hashicorp/terraform-provider-aws#16078]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.14.1
```

### Affected Resource(s)

* aws_cloudwatch_event_target

### Terraform Configuration Files

```hcl
resource "aws_ecs_cluster" "database" {
  name = "database"
}

resource "aws_cloudwatch_event_rule" "db_backup" {
  name                = "DBBackup"
  description         = "Run daily at 07:05 UTC"
  schedule_expression = "cron(5 7 * * ? *)"
}

resource "aws_cloudwatch_event_target" "dump_database" {
  arn       = aws_ecs_cluster.database.arn
  rule      = aws_cloudwatch_event_rule.db_backup.name
  role_arn  = "arn:aws:iam::696278446003:role/ecsEventsRole"

  ecs_target {
    task_count          = 1
    task_definition_arn = aws_ecs_task_definition.dump_database.arn
  }
}

resource "aws_ecs_task_definition" "dump_database" {
  family                = "service"
  container_definitions = file("task-definitions/dump_database.json")
}
```

task-definitions/dump_database.json:
```json
[
  {
    "name": "first",
    "image": "service-first",
    "cpu": 10,
    "memory": 512,
    "essential": true,
    "portMappings": [
      {
        "containerPort": 80,
        "hostPort": 80
      }
    ]
  }
]
```
### Expected Behavior

The `launch_type` should not be set.

### Actual Behavior

In the `aws_cloudwatch_event_target` output,  the `ecs_target` `launch_type` is set to `EC2`.

### Steps to Reproduce

1. `terraform apply`

### References

* [AWS CloudWatch Events ECS Parameters](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_EcsParameters.html)

**Comment by gbataille** [comment]
Additionally, `launch_type = ''` should be a valid value (which I guess used to be the default)

This is critical to be able to use the capacity provider of the ECS cluster. You can have a look here

# https://github.com/aws/containers-roadmap/issues/937#issuecomment-700299611

This is a regression. I have had this setup with `launch_type = ''` for a few months. I just tested, it worked fine with provider `3.13.0`. The regression was introduced in `3.14.0`, although the validation error is not the same in `3.14.0`:
```
Error: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, ListTargetsByRuleInput.EventBusName.
```
and `3.14.1`:
```
Error: expected ecs_target.0.launch_type to be one of [EC2 FARGATE], got 
  on dr_db.tf line 105, in resource "aws_cloudwatch_event_target" "db_dump":
 105:     launch_type         = ""
```

**Comment by danishgarg** [comment]
We are also facing this issue. We want to be able to run scheduled task on an ECS cluster and want to scale to 0 with termination protection on the ASG. The capacity provider is not activated when the CloudWatch event is triggered and the event fails complaining about the absence of any EC2 instances on the cluster. (https://github.com/aws/containers-roadmap/issues/937). We came across the workaround that @gbataille has put in the corresponding GitHub issue (https://github.com/aws/containers-roadmap/issues/937) but we are getting a terraform error 
` Error: expected ecs_target.0.launch_type to be one of [EC2 FARGATE], got  `

Can you please let us know if we can expect a fix for this issue from terraform end?

**Comment by brossini-financialsolutions** [comment]
We had the same issue, and ended up creating a lambda python to run a task using Fargate Spot; using run_rask():

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#ECS.Client.run_task

**Comment by ianneub** [comment]
Bump. This appears to be the cause of the problem:
https://github.com/hashicorp/terraform-provider-aws/blame/main/aws/resource_aws_cloudwatch_event_target.go#L149

@DrFaust92 Can this be easily changed to allow an empty string?

This is blocking me from upgrading my aws provider that I now need to get access to newer settings.

**Comment by anGie44** [comment]
Hi @ianneub , thank you for raising this issue! Just noting here that removing the default value would be a breaking change, though the workaround you've proposed to support the empty string is a great alternative 👍
