### ISSUE TITLE
Way to get an RDS endpoint resolving IP not available via terraform

### ISSUE THREAD

**Issue by gowrisankar22** [hashicorp/terraform-provider-aws#16089]
Hello All,

How to get the RDS endpoint resolving IP and pass it to the NLB target group in an automated way. ??

RDS DNS endpoint=test.test.eu-central-1.rds.amazonaws.com

Currently, I am passing manually every time via `terraform.tfvars` 
targetip_rds=10.1.1.1

```
resource "aws_lb_target_group_attachment" "tga-pac" {
  target_group_arn = aws_lb_target_group.tg-pac.arn
  target_id        = var.targetip_rds
  port             = 5432
}
```

**Comment by gowrisankar22** [comment]
I have even reported the same here https://discuss.hashicorp.com/t/get-private-ips-from-enis-of-nlb/17427

**Comment by quercusilvam** [comment]
Hello. I found a solution:

1. I need to find all ENIs in RDS subnets list. I work with Aurora that needs at least two subnets but creates only one ENI (if one  db instance is created). I use for that aws_network_interface**s**
2. Then I need a private ip for each ENI I found. Aws_network_interface**s** doesn't have this information so I need to use aws_network_interface instead.

The code:
`data "aws_network_interfaces" "enis_list" {
  filter {
    name   = "vpc-id"
    values = [vpc_id]
  }
  filter {
    name   = "subnet-id"
    values = subnet_ids
  }

  filter {
    name   = "description"
    values = ["RDSNetworkInterface"]
  }
}

data "aws_network_interface" "eni" {
  for_each = toset(data.aws_network_interfaces.enis_list.ids)
  id       = each.value
}` 

And how to get list of all IPs:

`output "endpoints_private_ips" {
  value = formatlist("%s", [for eni in data.aws_network_interface.eni : eni.private_ip])
}`
