### ISSUE TITLE
aws_rds_cluster detecting engine_mode change when using aws_rds_global_cluster

### ISSUE THREAD

**Issue by marcincuber** [hashicorp/terraform-provider-aws#16088]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.14.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
```

### Affected Resource(s)

* aws_rds_cluster

### Terraform Configuration Files

```hcl
provider "aws" {
  region  = "eu-west-1"
  version = ">= 3.14"
}

provider "aws" {
  alias   = "primary"
  region  = "eu-west-1"
  version = ">= 3.14"
}

provider "aws" {
  alias   = "secondary"
  region  = "eu-west-2"
  version = ">= 3.14"
}

data "aws_caller_identity" "current" {}
data "aws_region" "current" {}

variable "engine_version" {
  type    = string
  default = "5.7.mysql_aurora.2.08.2"
}
#####
# VPC and subnets
#####
module "vpc_ireland" {
  providers = {
    aws = aws.primary
  }

  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 2.63"

  name = "simple-vpc"

  cidr = "10.0.0.0/16"

  azs             = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]

  enable_nat_gateway = false
}

module "vpc_london" {
  providers = {
    aws = aws.secondary
  }

  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 2.63"

  name = "simple-vpc"

  cidr = "10.0.0.0/16"

  azs             = ["eu-west-2a", "eu-west-2b", "eu-west-2c"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]

  enable_nat_gateway = false
}

resource "aws_rds_global_cluster" "main" {
  provider = aws.primary

  engine                    = "aurora-mysql"
  engine_version            = var.engine_version
  global_cluster_identifier = "main-global-mysql-cluster"
  deletion_protection       = false

  storage_encrypted = true

  lifecycle {
    ignore_changes = [engine_version]
  }
}

#############
# RDS Aurora
#############
module "aurora_primary" {
  source = "../../"

  providers = {
    aws = aws.primary
  }

  global_cluster_identifier = aws_rds_global_cluster.main.id

  enable_global_cluster = true

  name_prefix         = "example-aurora-mysql-ireland"
  engine_mode         = "global"
  engine              = "aurora-mysql"
  engine_version      = var.engine_version
  deletion_protection = false

  storage_encrypted = true
  kms_key_id        = module.kms-ireland.key_arn

  vpc_id  = module.vpc_ireland.vpc_id
  subnets = module.vpc_ireland.public_subnets

  replica_count               = 1
  instance_type               = "db.r5.large"
  apply_immediately           = true
  allow_major_version_upgrade = true
  skip_final_snapshot         = true

  create_security_group = true

  depends_on = [aws_rds_global_cluster.main]
}

module "aurora_secondary" {
  source = "../../"

  providers = {
    aws = aws.secondary
  }

  enable_global_cluster = true

  source_region             = "eu-west-1"
  global_cluster_identifier = aws_rds_global_cluster.main.id

  name_prefix         = "example-aurora-mysql-london"
  engine_mode         = "global"
  engine              = "aurora-mysql"
  engine_version      = var.engine_version
  deletion_protection = false

  storage_encrypted = true
  kms_key_id        = module.kms-london.key_arn

  username = null
  password = null

  vpc_id  = module.vpc_london.vpc_id
  subnets = module.vpc_london.public_subnets

  replica_count               = 1
  instance_type               = "db.r5.large"
  apply_immediately           = true
  allow_major_version_upgrade = true
  skip_final_snapshot         = true

  create_security_group = true

  depends_on = [module.aurora_primary, aws_rds_global_cluster.main]
}
```

### Expected Behavior

No changes to be detected for engine_mode in aws_rds_cluster resource.

### Actual Behavior

Each `aws_rds_cluster` that belongs to `global_cluster` resource is applied with `engine_mode` set to `global`. Once everything deploys correctly during first apply. Second run of terraform detects a change in the resource which forces a new resource:

```
~ engine_mode  = "provisioned" -> "global" # forces replacement
```

By the looks of it, global engine_mode is simply not applied by terraform.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform plan`

**Comment by bflad** [comment]
Hi @marcincuber 👋  Thank you for submitting this and sorry you ran into trouble here. This is due to [RDS API changes](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBCluster.html) where effectively the `global` engine mode is deprecated but the API is still accepting the value on creation:

> The global engine mode isn't required for Aurora MySQL version 1.22 and higher 1.x versions, and global engine mode isn't required for any 2.x versions.

Since the API is automatically canonicalizing the engine mode based on Aurora engine version and since the value seems to be on its way out of recommended usage, we likely would not want to introduce special logic into the Terraform AWS Provider since it could be errant or complex to manage.

That said, we probably need to update some our documentation to discourage its usage going forward, so I'm going to mark this issue with that label and submit changes in that regard. 👍

**Comment by marcincuber** [comment]
@bflad Yeah, I was about to post that docs need to be updated as well. Thanks for quick action against this problem.
