### ISSUE TITLE
support the new connection pool and outlier detection features in app mesh virtual node resource

### ISSUE THREAD

**Issue by rmaskara** [hashicorp/terraform-provider-aws#16097]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

support the new connection pool and outlier detection features in app mesh virtual node resource

### New or Affected Resource(s)

aws_appmesh_virtual_node

### Potential Terraform Configuration

```hcl

```

### References

https://aws.amazon.com/about-aws/whats-new/2020/11/aws-app-mesh-introduces-circuit-breaker-capabilities/
https://docs.aws.amazon.com/cli/latest/reference/appmesh/create-virtual-node.html
* #0000

**Comment by ewbankkit** [comment]
##### [`aws_appmesh_virtual_gateway`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appmesh_virtual_gateway)

```hcl
resource "aws_appmesh_virtual_gateway" "example" {
  name      = "example-virtual-gateway"
  mesh_name = "example-service-mesh"

  spec {
    listener {
      port_mapping {
        port     = 8080
        protocol = "http"
      }

      connection_pool {
        http {
          max_connections      = 3
          max_pending_requests = 2
        }
      }
    }
  }
}
```

##### [`aws_appmesh_virtual_node`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appmesh_virtual_node)

```hcl
```

**Comment by rmaskara** [comment]
Hi @ewbankkit, the examle config looks good. I was also expecting to see connection pool settings in the virtual node since App Mesh seems to allow overriding these settings at node level as well..

**Comment by ewbankkit** [comment]
@rmaskara Yes, `connection_pool` will be a `aws_appmesh_virtual_node` attribute.

**Comment by rkmaskara** [comment]
When are we expecting this be available through a provider version release?
