### ISSUE TITLE
aws_dms_replication_task cannot modify running tasks

### ISSUE THREAD

**Issue by pancochea** [hashicorp/terraform-provider-aws#16092]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.14.1

### Affected Resource(s)

* aws_dms_replication_task

### Terraform Configuration Files

```hcl
resource "aws_dms_replication_task" "dms-replication-task" {
    migration_type            = "cdc"
    replication_instance_arn  = var.replication_instance_arn
    replication_task_id       = var.replication_task_id
    source_endpoint_arn       = var.source_endpoint_arn
    table_mappings            = ""

    target_endpoint_arn       = target_endpoint_arn
    replication_task_settings = ""
    lifecycle {
        ignore_changes = [
            replication_task_settings,
            table_mappings
        ]
    }
}
```

### Expected Behavior

When modifing any task parameter, the task should stop, update and start

### Actual Behavior

An error raises stating that the task must be in state Stopped to modify and crashes

### Steps to Reproduce
1. Create a dms task resource
2. Once created, modify any parameter of the task.
3. `terraform apply`

### References

A pull request with the solution already exists, but looks like it's abandoned

https://github.com/hashicorp/terraform-provider-aws/pull/2305/files

* #0000

**Comment by fermezz** [comment]
This is a dup for https://github.com/hashicorp/terraform-provider-aws/issues/2236
