### ISSUE TITLE
Anchor links does not work on doc site

### ISSUE THREAD

**Issue by tlamr** [hashicorp/terraform-provider-aws#16119]
Hello dear maintainers,

  Using anchor names in urls on doc site does not work.
Click on https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#reserved_concurrent_executions

### Expected Behavior

ui should scroll to the anchor in the middle of the page

### Actual Behavior

the top of the page is shown, no scrolling happens

Browsers: latest Chrome, latest Brave

### Something else?
Thanks a lot you are brilliant

cheers, 
Tomas

**Comment by bflad** [comment]
Hi @tlamr 👋  Thank you for reporting this issue. I'm going to contact the team responsible for the Terraform Registry website.

**Comment by gregone** [comment]
Hi @tlamr We have deployed changes to the Terraform registry to address this issue. Thanks for reporting!

**Comment by bflad** [comment]
Closing as this should be resolved. Thank you @gregone for fix this up and thank you @tlamr for the report!
