### ISSUE TITLE
aws_iot_topic rule update not adding error action

### ISSUE THREAD

**Issue by shanmud** [hashicorp/terraform-provider-aws#16115]
**Problem Description**
We have a topic rule created without error action. We are trying to update the topic rule with error action. Terraform apply shown that the resource is successfully updated but in AWS console, the changes were not reflected. During the next plan, we could see the old stage(without error action)

Note: The error action added successfully when the resource deleted and recreated with terraform taint command. This needs to be done every time for the update in error action

**Comment by ewbankkit** [comment]
`error_action` changes are not correctly handled:

https://github.com/hashicorp/terraform-provider-aws/blob/3d309518bdcb02c8b26237929b0a87d9e189b895/aws/resource_aws_iot_topic_rule.go#L1201-L1224
