### ISSUE TITLE
S3 Intelligent-Tiering Archive configuration

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#16123]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon S3 Intelligent-Tiering adds Archive Access tiers.

### New or Affected Resource(s)

* `aws_s3_bucket_intelligent_tiering_configuration`

### Potential Terraform Configuration

```hcl
resource "aws_s3_bucket_intelligent_tiering_configuration" "example" {
  bucket = aws_s3_bucket.example.name
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-s3-intelligent-tiering-adds-archive-access-tiers/).
[Blog post](https://aws.amazon.com/blogs/aws/s3-intelligent-tiering-adds-archive-access-tiers/).

Requires [AWS SDK v1.35.24](https://github.com/aws/aws-sdk-go/releases/tag/v1.35.24):

* https://github.com/hashicorp/terraform-provider-aws/pull/16109

**Comment by leosilvasouza** [comment]
Good feature!

**Comment by flibustier** [comment]
Hello !
What is the status with this one ?

**Comment by azsorkin-stripe** [comment]
Hello!

We are also interested in using intelligent tiering with archive/deep archive functionality in terraform. Any updates on this issue?

**Comment by maxter252** [comment]
Hello, I am interested in making a contribution here, as this is something we need, and can potentially give a few days of work to this, but may need some help as i am not familiar with Go or the terraform-provider-aws code. @ewbankkit  What do you think? 

Looking at the AWS API / GO SDK implementing [this](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketIntelligentTieringConfiguration.html) could be the answer?
Configuring with 'ARCHIVE_ACCESS' and 'DEEP_ARCHIVE_ACCESS' maybe?

**Comment by max-thorpe-sains** [comment]
We are working on this branch [issue-16123-add-intelligent-tiering-configuration-resource](https://github.com/daniepett/terraform-provider-aws/tree/issue-16123-add-intelligent-tiering-configuration-resource)

**Comment by maxter252** [comment]
We are working on this branch [issue-16123-add-intelligent-tiering-configuration-resource](https://github.com/daniepett/terraform-provider-aws/tree/issue-16123-add-intelligent-tiering-configuration-resource)

**Comment by daniepett** [comment]
PR open to implement this resource
https://github.com/hashicorp/terraform-provider-aws/pull/20329

**Comment by KVInventoR** [comment]
Guys,
any progress for this requests?

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters roadmap. If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!
