### ISSUE TITLE
AWS Directory Service Directory Description Change Requires Replacement

### ISSUE THREAD

**Issue by kclinden** [hashicorp/terraform-provider-aws#16130]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.14.1

### Affected Resource(s)

* aws_directory_service_directory

### Terraform Configuration Files

```hcl
resource "aws_directory_service_directory" "directory" {
  name     = "mydomain.com"
  #description = "Active Directory Domain forTesting Environment"
  password = jsondecode(data.aws_secretsmanager_secret_version.password.secret_string)["dev_admin_password"]
  edition  = "Standard"
  type     = "MicrosoftAD"

  vpc_settings {
    vpc_id     = module.vpc.vpc_id
    subnet_ids = [module.vpc.private_subnets[0], module.vpc.private_subnets[1]]
  }

  tags = {
    Terraform   = "true"
  }
}
```

### Expected Behavior

Terraform will update the description without replacing the directory service.

### Actual Behavior

Terraform wants to replace the entire directory service deployment instead of just updating the description field.

### Steps to Reproduce

1. `terraform apply`
2. Add or remove description for Directory Service
3. `terraform apply`

* #0000

**Comment by gdavison** [comment]
Hi @kclinden. Unfortunately, the AWS API does not offer a way to change the description field on a directory without replacing it. We should document this better.
