### ISSUE TITLE
Provider produced inconsistent result after apply - aws_vpc_dhcp_options_association.dns_resolver

### ISSUE THREAD

**Issue by JustLeo** [hashicorp/terraform-provider-aws#16142]
### Affected Resource(s)
aws_vpc_dhcp_options_association.dns_resolver

### Terraform Configuration Files
```terraform
resource "aws_vpc_dhcp_options" "aws_client_dhcp" {
  domain_name          = "mydomainname"
  domain_name_servers  = ["${aws_instance.node01.private_ip}", "${cidrhost(aws_subnet.subnet.0.cidr_block, 2)}"]
  ntp_servers          = ["${aws_instance.node01.private_ip}"]
  netbios_name_servers = ["${aws_instance.node01.private_ip}"]
  netbios_node_type    = 2
}
resource "aws_vpc_dhcp_options_association" "dns_resolver" {
  vpc_id          = aws_vpc.awsnononapvpc01.id
  dhcp_options_id = aws_vpc_dhcp_options.aws_client_dhcp.id
}
```

### Debug Output
Error: Provider produced inconsistent result after apply
When applying changes to aws_vpc_dhcp_options_association.dns_resolver,
provider "registry.terraform.io/-/aws" produced an unexpected new value for
was present, but now absent.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Expected Behavior
Terraform apply should have been successful

### Actual Behavior
Terraform apply fails

### Steps to Reproduce
This does not happen all the time, running apply multiple times

**Comment by militantslacker** [comment]
Same behavior with Terraform Version 0.14.6 and aws provider version 3.29.1

**Debug output:**

Error: Provider produced inconsistent result after apply
When applying changes to
module.test.aws_vpc_dhcp_options_association.dns_resolver, provider
"registry.terraform.io/hashicorp/aws" produced an unexpected new value: Root
resource was present, but now absent.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
