### ISSUE TITLE
Data source for querying account OU membership in AWS Organizations

### ISSUE THREAD

**Issue by mmerickel** [hashicorp/terraform-provider-aws#16153]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There's a missing data source for querying information about account membership. Currently the `aws_organizations_organization` provides a list of all accounts, and `aws_organizations_organizational_units` provides a list of OUs by parent. However, there's neither the accounts list nor the ou list provide something that can map between the two.

The AWS API [ListAccountsForParent](https://docs.aws.amazon.com/organizations/latest/APIReference/API_ListAccountsForParent.html) would allow querying the accounts within an OU.

### New or Affected Resource(s)

- `data "aws_organizations_accounts"`

required parameter: `parent_id`

### Potential Terraform Configuration

```hcl
data "aws_organizations_organization" "this" {}

data "aws_organizations_organizational_units" "root" {
  parent_id = data.aws_organizations_organization.this.roots[0].id
}

data "aws_organizations_accounts" "prod" {
  parent_id = [
    for x in data.aws_organizations_organizational_units.root.children :
    x.id if x.name == "prod"
  ][0]
}
```

**Comment by aferg439** [comment]
I'm in a place where this would be very handy so +1 to you! However, I think the standard would be more like:

- `data aws_organizations_organizational_unit`

The behavior you described would be spot on for helping me manage accounts based on OU. For example, inviting members of certain OUs to SecurityHub and exclude others. Right now I can only iterate over all accounts using the `aws_organizations_organization` data source.

**Comment by ebi-yade** [comment]
Hello, I'm now in a similar issue and have just found this!

@mmerickel, your idea and the proposal sound really nice! :muscle:
And I think the `parent_id` should be a single string value, not like an array or a set.
You'll be able to do things like the example using `for_each` argument and data manipulation in `locals` block. :ok_hand:

As this issue seems to have no update until last November, is anyone working in progress?  If not, I will try to implement and submit a Pull Request!

**Comment by ryancausey** [comment]
I think this might be missing a use case, or perhaps what I want is a different feature request:

Similar to using `data "aws_organizations_organization" "current" {}` to get the Organization the current AWS account Terraform is executing upon, I was hoping to be able to leverage a `data "aws_organizations_organizational_units" "current" {}` pattern to get the immediate OU for the current AWS account Terraform is executing upon.

I don't think the proposed solution allows this check for AWS accounts that are not the root account, as the `roots` attribute [will be null in these cases](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/organizations_organization#master-account-attributes-reference). Thus for non-root AWS accounts it is not possible to get the ID of the Root OU, and the provided example wouldn't work.

Do y'all think this is a different issue entirely or is it still related to this?

**Comment by salecharohit** [comment]
> 

Thats absolutely correct if this is allowed then it would be a big lapse in security as a child account is now able to access details about its parents.

**Comment by cacack** [comment]
I too have found my way here with the same need.

I'll also comment that the security concern is real and why the AWS API doesn't allow a child account to access such information about the Organization.  However, a principal with the proper authorization to make the API call to Organization or it's delegated administration account wouldn't be.  I think the OP's suggestion follows this security model, and is what I'd love to see implemented.

**Comment by ahublersos** [comment]
In [#24350](https://github.com/hashicorp/terraform-provider-aws/pull/24350) I've made a go at creating two new data sources that allow you to gather direct child accounts within an OU as well as all generations of child accounts within an OU. 

I've build a custom provider off of this branch and am using it internally to help manage assignments of SSO permission sets.
