### ISSUE TITLE
provider/aws: Increased retention period for Kinesis streams

### ISSUE THREAD

**Issue by ElizaRayner** [hashicorp/terraform-provider-aws#16179]
Aws has recently released an update allowing streams to have a retention period up to one year (8760 hours) that is not allowed with terraform.

Relevant API calls:
IncreaseStreamRetentionPeriod
DecreaseStreamRetentionPeriod

**Comment by ewbankkit** [comment]
Affected resource:

* [`aws_kinesis_stream`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_stream)

**Comment by anGie44** [comment]
Support has been added with the recent merge of #16608 and will go out with the next AWS Provider release, `v3.23.0`.
