### ISSUE TITLE
resource/aws_spot_instance_request: incorrectly reuses resource definition of aws_instance

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#16189]
The implementation of `aws_spot_instance_request` copies and modifies the resource definition of `aws_instance`. This results in a number of unsupported arguments existing on the resource but having no effect, including `metadata_options`.

The documentation also states that

> Spot Instance Requests support all the same arguments as `aws_instance`, with the addition of…

which is not correct.

`aws_spot_instance_request` should be a stand-alone resource.

### Affected Resource

* aws_spot_instance_request

**Comment by bflad** [comment]
Related in a good way to https://github.com/hashicorp/terraform-provider-aws/issues/16145
