### ISSUE TITLE
rds: export db snapshot data to S3

### ISSUE THREAD

**Issue by aviau** [hashicorp/terraform-provider-aws#16181]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great if the provider allowed for exporting db snapshot data to S3 as documented here:
 - https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_ExportSnapshot.html

### New or Affected Resource(s)

* aws_rds_*

**Comment by abhinaysutrakar** [comment]
Hi ,

Do we have any update in which version this enhancement can be available?

**Comment by GISTech01** [comment]
Any update on the following?

**Comment by debu99** [comment]
any update

**Comment by Felistas** [comment]
Any update?

**Comment by Kristin0** [comment]
any update

**Comment by jar-b** [comment]
A formal write-up for this proposed resource is documented below. There are no update or delete API's, so the alternative behavior for each operation is proposed to be:

- **Update** - A change to any required or optional attribute will force replacement (destroy + create).
- **Delete** - Destruction of an "in-progress" task will cancel the task and remove from state. Destruction of a completed or failed task will simply remove the resource from state.

## API Implementations

[service/rds](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/rds)

### Export Task
- [StartExportTask](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/rds#Client.StartExportTask)
- [DescribeExportTasks](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/rds#Client.DescribeExportTasks)
- [CancelExportTask](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/rds#Client.CancelExportTask)

## Potential Terraform Features
### New Resource: `aws_rds_export_task`

**Rationale:** Allow practitioners to manage RDS export tasks.


**Potential Terraform Configuration:**

```terraform
resource "aws_rds_export_task" "example" {
  # required attributes
  export_task_identifier = "my_snapshot_export"
  iam_role_arn           = "iam_role" # actually an IAM role name
  kms_key_id             = "my_key"
  s3_bucket_name         = "my_export_bucket"
  source_arn             = "arn:aws:rds:AWS_Region:123456789012:snapshot:snapshot_name"

  # optional attributes
  export_only = ["database.table mutable"]
  s3_prefix   = "my_prefix/my-export-name"
}
```

**Arguments:**

- `export_task_identifier` - (Required) A unique identifier for the snapshot export task.
- `iam_role_arn` - (Required) Name of the IAM role to use for writing to the Amazon S3 bucket. NOTE: this attribute expects a **role name** (not ARN). The `_arn` convention has been preserved to match the AWS field name despite the misnomer.
- `kms_key_id` - (Required) ID of the Amazon Web Services KMS key to use to encrypt the snapshot.
- `s3_bucket_name` - (Required) Name of the Amazon S3 bucket to export the snapshot to.
- `source_arn` - (Required) Amazon Resource Name (ARN) of the snapshot to export.

- `export_only` - (Optional) Data to be exported from the snapshot. If this parameter is not provided, all the snapshot data is exported. Valid values are documented in the [AWS StartExportTask API documentation](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_StartExportTask.html#API_StartExportTask_RequestParameters).
- `s3_prefix` - (Optional) Amazon S3 bucket prefix to use as the file name and path of the exported snapshot.

**Attributes:**

- `failure_cause` - Reason the export failed, if it failed.
- `percent_progress` - Progress of the snapshot export task as a percentage.
- `snapshot_time` - Time that the snapshot was created.
- `source_type` - Type of source for the export.
- `status` - Status of the export task.
- `task_end_time` - Time that the snapshot export task completed.
- `task_start_time` - Time that the snapshot export task started.
- `warning_message` - Warning about the snapshot export task, if any.
