### ISSUE TITLE
resource/aws_spot_instance_request: correct spelling of `instance_interruption_behaviour`

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#16190]
As documented at https://github.com/hashicorp/terraform-provider-aws/blob/master/docs/contributing/pullrequest-submission-and-lifecycle.md#resource-contribution-guidelines, the AWS Provider uses American English spelling for attribute names and documentation.

Add the argument `instance_interruption_behaviour` and deprecate `instance_interruption_behaviour`.

Removing `instance_interruption_behaviour` is a breaking change and will be done at a major version update with Issue #16191.

### Affected Resource

* aws_spot_instance_request

**Comment by bflad** [comment]
Historical context: https://github.com/hashicorp/terraform-provider-aws/issues/7006

**Comment by anGie44** [comment]
Closing this one since it was addressed in https://github.com/hashicorp/terraform-provider-aws/pull/20188
