### ISSUE TITLE
r/aws_network_interface_sg_attachment: "Error: Provider produced inconsistent result after apply"

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#16201]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

[Reported](https://github.com/hashicorp/terraform-provider-aws/issues/12449#issuecomment-634979827) by @queglay and @atsalolikhin-spokeo in #12449:

```
3776 [23:29:14] Error: timeout - last error: ssh: rejected: connect failed (Connection timed out)
3777 [23:29:14] 
3778 [23:29:14] 
3779 [23:29:14] 
3780 [23:29:14] Error: Provider produced inconsistent result after apply
3781 [23:29:14] 
3782 [23:29:14] When applying changes to
3783 [23:29:14] module.softnas.aws_network_interface_sg_attachment.sg_attachment_vpn[0],
3784 [23:29:14] provider "registry.terraform.io/-/aws" produced an unexpected new value for
3785 [23:29:14] was present, but now absent.
3786 [23:29:14] 
3787 [23:29:14] This is a bug in the provider, which should be reported in the provider's own
3788 [23:29:14] issue tracker.
```

[and](https://github.com/hashicorp/terraform-provider-aws/issues/12449#issuecomment-726394546):

```
Error: Provider produced inconsistent result after apply

When applying changes to
module.my_module_name.aws_network_interface_sg_attachment.my_server[2],
provider "registry.terraform.io/hashicorp/aws" produced an unexpected new
value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Affected Resource(s)

* [`aws_network_interface_sg_attachment`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/network_interface_sg_attachment)

**Comment by ewbankkit** [comment]
I see that the resource ID is not being set in `resourceAwsNetworkInterfaceSGAttachmentCreate` after successful creation but instead is being set later in `resourceAwsNetworkInterfaceSGAttachmentRead`.

**Comment by Buri** [comment]
We are seeing the same error, but with https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_topic_subscription

**Comment by camlow325** [comment]
We saw the "Root resource was present" error for an `aws_sns_topic_subscription` resource as well, but I think the root cause for it may be different than for the others in this issue. Our case seems to be an AWS / eventual consistency problem. I filed #16695 with details on the error we saw.

**Comment by recintoit** [comment]
I stumbled onto this because I have a similar error using a different provider.   I thought it could be something didn't configure correctly in the config, but now that I see the simllar error in other providers, I will watch to see if an issue is fixed if it will be patched in other providers.
