### ISSUE TITLE
S3 bucket ACL validation is missing valid Canned ACLs

### ISSUE THREAD

**Issue by james-skinner-deltatre** [hashicorp/terraform-provider-aws#16212]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

CLI: 0.13.5
provider: 3.15.0

### Affected Resource(s)

* aws_s3_bucket

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      version = "= 3.15.0"
      source  = "hashicorp/aws"
    }
  }
  required_version = ">= 0.13.5"
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_s3_bucket" "app" {
  bucket_prefix = "test-app"
  acl           = "bucket-owner-full-control"
}
```

### Expected Behavior

Bucket is created

### Actual Behavior
An error at the plan stage:

```
Error: expected acl to be one of [private public-read public-read-write authenticated-read aws-exec-read log-delivery-write], got bucket-owner-full-control

  on s3.tf line 46, in resource "aws_s3_bucket" "app":
  46:   acl           = "bucket-owner-full-control"
```

### Steps to Reproduce

1. Create main.tf with the above code
2. run `terraform init && terraform plan`

### References

* List of canned ACLs is [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl)
* both `bucket-owner-read` and `bucket-owner-full-control` are missing form the validation list
* Seems the validation was added in #15327

**Comment by gdavison** [comment]
Hi @james-skinner-deltatre. `bucket-owner-full-control` is confusingly named: it only applies to S3 Objects, as documented at https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl. It gives both the object owner and bucket owner full control over the object.

**Comment by james-skinner-deltatre** [comment]
oh yeah, you're right:

>  If you specify this canned ACL when creating a bucket, Amazon S3 ignores it.

I guess we were setting a pointless ACL in this case :-). Thanks
