### ISSUE TITLE
Tag AmazonECSManaged produces "Missing required argument" error

### ISSUE THREAD

**Issue by magraeber** [hashicorp/terraform-provider-aws#16214]
This seems to be because terraform doesn't add AmazonECSManaged as a propagated tag to the ASG itself when it links the capacity provider. There's a workaround for this by adding the following to your ASG configuration:

```
resource "aws_autoscaling_group" "service_asg" {
        ...
        tag {
            key                 = "AmazonECSManaged"
            propagate_at_launch = true
        }
        ...
}
```

Making this change worked for me.

_Originally posted by @peter-boekelheide-ah in https://github.com/hashicorp/terraform-provider-aws/issues/12582#issuecomment-614746862_

**Comment by magraeber** [comment]
This approach is recommencement in capacity provider documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_capacity_provider

But this code produces the following error:
```
Error: Missing required argument

  on main.tf line 558, in resource "aws_autoscaling_group" "scale-windows-instances":
 558:   tag {

The argument "value" is required, but no definition was found.
```
Tested with:
Terraform v0.13.4
provider registry.terraform.io/hashicorp/aws v3.15.0

**Comment by gdavison** [comment]
Hi @magraeber, thanks for submitting this. When assigning tags using the `tag` attribute, `value` is a required parameter. However, when using `tags`, `value` is not required. I'll update the documentation to reflect this.
