### ISSUE TITLE
Listeners for Gateway Load Balancers must not specify port number or protocol

### ISSUE THREAD

**Issue by mabdelghany** [hashicorp/terraform-provider-aws#16228]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform version: 0.13.5
Terraform AWS Provider version: v3.15.0_x5

### Affected Resource(s)

* aws_lb_listener

### Expected Behavior

When adding a listener to the gateway load balancer, according to AWS Documentation for Cloudformation (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listener.html), the port and protocol can not be specified when using a gateway load balancer.

### Actual Behavior

When the port is not specified, Terraform complains that these are required parameters (per the Terraform documentation https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener#port)

### Steps to Reproduce

The error is thrown a the `terraform plan` stage

### References

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listener.html
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener#port

**Comment by gdavison** [comment]
`port` and `protocol` need to be `Optional` instead of `Required`

**Comment by bflad** [comment]
Fix submitted: https://github.com/hashicorp/terraform-provider-aws/pull/16306

**Comment by bflad** [comment]
The fix for this has been merged and will release shortly with version 3.18.0 of the Terraform AWS Provider.
