### ISSUE TITLE
Feature Request: ElasticSearch - native SAML Authentication for Kibana

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#16259]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

_"Amazon Elasticsearch Service now natively supports using Security Assertion Markup Language (SAML) to offer single sign-on (SSO) for Kibana. SAML authentication for Kibana enables users to integrate directly with third-party identity providers (IDP) such as Okta, Ping Identity, OneLogin, Auth0, Active Directory Federation Services (ADFS) and Azure Active Directory. With this feature, your users can leverage their existing usernames and passwords to log in to Kibana, and roles from your IDP can be used for controlling privileges in Elasticsearch and Kibana, including what operations they can perform and what data they can search and visualize. "_

### New or Affected Resource(s)

* aws_elasticsearch_domain

### Potential Terraform Configuration

```hcl


resource "aws_elasticsearch_domain" "test" {
    advanced_security_options {
        saml_options {
            enabled  = true
            master_user_name = "my-idp-user"
            master_backend_role = "my-idp-group-or-role"
            idp {
                entity_id = "entity-id"
                metadata_content = "metadata-content-with-quotes-escaped"
            }
            roles_key =optional-roles-key
            session_timeout_minutes = 180
            subject_key = "optional-subject-key"
        }
    }
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-elasticsearch-service-adds-native-saml-authentication-kibana/
* https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/saml.html

**Comment by xxxbobrxxx** [comment]
Hi! Looks like everything is done in the linked Pull Request.
Can you _please_ provide estimation where this feature will be released?
Thanks!

**Comment by GuusDeGraeve** [comment]
Same here, looking forward to using native SAML Authentication.

**Comment by thameezb** [comment]
As are we

**Comment by TimBuss** [comment]
Looking forward to this!

**Comment by prabaharang** [comment]
Any update on when we can expect this feature to be available. Is there any roadmap?

**Comment by debu99** [comment]
Why this PR can't be merged?

**Comment by JeffAshton** [comment]
> Why this PR can't be merged?

I don't think this PR is exactly what we want.  I think the SAML config should be it's own resource.  See https://github.com/hashicorp/terraform-provider-aws/pull/16424#issuecomment-827525439

**Comment by lsacco-nutreense** [comment]
Looks like there's a new PR. Any chance this can be merged soon? Would love to add this!
