### ISSUE TITLE
S3 Bucket Replication add Delete Markers

### ISSUE THREAD

**Issue by jonjohnston** [hashicorp/terraform-provider-aws#16250]
V2 of replication configuration allows for delete markers to be replicated. Need option in terraform

Example configuration:

```terraform
replication_configuration {
    role = aws_iam_role.replication.arn

    rules {
      id     = "foobar"
      prefix = "foo"
      status = "Enabled"
      delete_marker_replication {
        status = "Enabled"
      }
      destination {
        bucket        = aws_s3_bucket.destination.arn
        storage_class = "STANDARD"
      }
    }
```

**Comment by Zordrak** [comment]
This setting is entirely dependent on whether the replication rules are a V1 or V2 configuration. V1 configurations have Delete Marker Replication enabled, and V2 configurations have Delete Marker Replication disabled.

If you specify a `filter` block in the replication rule(s), then it will automatically become a V2 configuration, and Delete Marker Replication will be disabled. If you specify no filter block, or you specify a prefix parameter outside of a filter block, the it will be a V1 configuration and Delete Marker Replication will be enabled.

**Comment by jonjohnston** [comment]
@Zordrak your statement is invalid. AWS recently allows V2 replication configuration to replicate delete markers.

**Comment by byxchen** [comment]
Would also appreciate this. Please refer to the following notice from AWS:
https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-s3-replication-adds-support-for-replicating-delete-markers/

```
You can enable delete marker replication on a new or existing replication rule. You can apply it to the entire S3 bucket or a subset of S3 objects filtered by a prefix. You can monitor delete marker replication progress on the S3 management console or Amazon Cloudwatch by enabling S3 Replication metrics and notifications or S3 Replication Time Control. When creating a replication rule, you will have an option to enable delete marker replication for each replication rule. You can use the S3 Management Console, SDK, API, or AWS CloudFormation to enable delete marker replication.
```

**Comment by obobrova** [comment]
Checking to see if there is any progress on this feature request. Both `v1` and `v2` versions of replication configuration now support this parameter, even though their defaults are the opposites. But terraform already can distinguish between v1 and v2, so this should not really be a blocker.

**Comment by Choms** [comment]
Any news? this sounds like a trivial change, and forces me to use a dirty ignore_changes for the replication so it doesn't removes the delete markers I have to add manually - no need to say this defeats the purpose of writing infra as code

**Comment by mkrant** [comment]
Hey folks, if you get a chance please head over to [the open pull request](https://github.com/hashicorp/terraform-provider-aws/pull/19323) and drop a 👍 to help get it prioritized for review.
