### ISSUE TITLE
d/msk_kafka_version: new data source

### ISSUE THREAD

**Issue by anGie44** [hashicorp/terraform-provider-aws#16268]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Ease the practitioner burden of selecting deprecated kafka versions by providing access to information on available MSK kafka engine versions. In addition, the `preferred_versions` argument should allow selecting a version from a list of acceptable options.

### New Data Source

* aws_mks_kafka_version

### Potential Terraform Configuration

```hcl
data "aws_msk_kafka_version" "test" {}
```

### References

* AWS MSK [ListKafkaVersions](https://docs.aws.amazon.com/msk/1.0/apireference/kafka-versions.html#ListKafkaVersions)

**Comment by kevinb-nomi** [comment]
+1 to this. Terraform should also default to the latest version if `kafka_version` is not supplied.

**Comment by james-bjss** [comment]
Had a first stab at this. The versions are filtered in code. It doesn't return a default version, but it could be added if needed. Would probably need to ensure correct sorting of versions and check that the latest version has a status of `ACTIVE`
