### ISSUE TITLE
IAM Access Analyzer does not validate analyzer name

### ISSUE THREAD

**Issue by sidewinder12s** [hashicorp/terraform-provider-aws#16264]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```bash
Terraform v0.12.29
+ provider.aws v3.11.0
```

### Affected Resource(s)

* aws_accessanalyzer_analyzer

### Terraform Configuration Files

```hcl
resource "aws_accessanalyzer_analyzer" "us_east_1" {
  analyzer_name = "Organization Analyzer us-east-1"
  type          = "ORGANIZATION"
}
```

### Expected Behavior

Should have error'd in Plan that the analyzer_name was invalid

### Actual Behavior

```bash
  # aws_accessanalyzer_analyzer.us_east_1 will be created
  + resource "aws_accessanalyzer_analyzer" "us_east_1" {
      + analyzer_name = "Organization Analyzer us-east-1"
      + arn           = (known after apply)
      + id            = (known after apply)
      + type          = "ORGANIZATION"
    }

Plan: 1 to add, 0 to change, 0 to destroy.


Warning: Resource targeting is in effect

You are creating a plan with the -target option, which means that the result
of this plan may not represent all of the changes requested by the current
configuration.
		
The -target option is not for routine use, and is provided only for
exceptional situations such as recovering from errors or mistakes, or when
Terraform specifically suggests to use it as part of an error message.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_accessanalyzer_analyzer.us_east_1: Creating...

Warning: Applied changes may be incomplete

The plan was created with the -target option in effect, so some changes
requested in the configuration may have been ignored and the output values may
not be fully updated. Run the following command to verify that no other
changes are pending:
    terraform plan
	
Note that the -target option is not suitable for routine use, and is provided
only for exceptional situations such as recovering from errors or mistakes, or
when Terraform specifically suggests to use it as part of an error message.


Error: error creating Access Analyzer Analyzer (Organization Analyzer us-east-1): BadRequestException: 
	status code: 400, request id: 347fc340-2cab-4289-abbf-bb9bdd764f58


Releasing state lock. This may take a few moments...
```

### Steps to Reproduce

1. `terraform apply` with an invalid analyzer name.

### Important Factoids

Went into the console to create the analyzer manually, which showed the Name we were trying to use was invalid.

https://docs.aws.amazon.com/access-analyzer/latest/APIReference/API_CreateAnalyzer.html#API_CreateAnalyzer_RequestSyntax

**Comment by gdavison** [comment]
According to https://docs.aws.amazon.com/access-analyzer/latest/APIReference/API_CreateAnalyzer.html#API_CreateAnalyzer_RequestBody, the valid name pattern is `^[A-Za-z][A-Za-z0-9_.-]*$`
