### ISSUE TITLE
aws_lambda_function_tag resource to tag lambdas

### ISSUE THREAD

**Issue by mosheavni** [hashicorp/terraform-provider-aws#16273]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I'd like to request a resource called `aws_lambda_function_tag` that its name describe itself, an option to tag a lambda function without actually creating the lambda.

### New or Affected Resource(s)

* aws_lambda_function

### Potential Terraform Configuration

```hcl
data "aws_cloudformation_stack" "myCoolLambdaFunc" {
  name = "myCoolLambdaFunc"
}

resource "aws_lambda_function_tag" "lambda_tag" {
  resource_id = data.aws_cloudformation_stack.myCoolLambdaFunc.id
  key         = "someKey"
  value       = "someVal"
}
```

* #0000

**Comment by ewbankkit** [comment]
Similar:

* https://github.com/hashicorp/terraform-provider-aws/issues/11634

@Moshem123 Thanks for raising this issue.
This can be solved once https://github.com/hashicorp/terraform-provider-aws/pull/13783 is merged, which will add the ability to generate per-service tag resources like the one you suggest.

**Comment by Moshem123** [comment]
Thanks @ewbankkit , should I close this issue?

**Comment by ewbankkit** [comment]
@Moshem123 Let's keep it open.
