### ISSUE TITLE
eks_fargate_profile creation failed because unexpected status

### ISSUE THREAD

**Issue by vdahmane** [hashicorp/terraform-provider-aws#16272]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform 0.13
AWS Provider 2.67

### Affected Resource(s)

* aws_eks_fargate_profile

### Terraform Configuration Files

```hcl
resource "aws_eks_fargate_profile" "eks_fargate_profile" {
  cluster_name           = aws_eks_cluster.eks_cluster.name
  fargate_profile_name   = element(var.fargate_profile, count.index)
  pod_execution_role_arn = aws_iam_role.eks_fargate_profile_role.arn
  subnet_ids             = var.private_subnets

  selector {
    namespace = element(var.fargate_profile, count.index)
  }
  count = length(var.fargate_profile)
}

```

### Panic Output

Error: error creating EKS Fargate Profile (prod-cluster:kube-system): ResourceInUseException: Cannot create Fargate Profile kube-system because cluster prod-cluster currently has Fargate profile env in status CREATING
{
  RespMetadata: {
    StatusCode: 409,
    RequestID: "66e06cb6-e04a-4b58-a9bc-6339a5c485e5"
  },
  ClusterName: "prod-cluster",
  Message_: "Cannot create Fargate Profile kube-system because cluster prod-cluster currently has Fargate profile env in status CREATING"
}

### Expected Behavior

Waiting previous profile has been creating.

1. `terraform apply`

### References

* #0000

**Comment by bflad** [comment]
Hi @vdahmane 👋  Thank you for raising this and sorry you ran into trouble with this functionality. This appears to be similar to https://github.com/hashicorp/terraform-provider-aws/issues/13372, so to consolidate efforts and discussions, I'm going to close this in preference of the existing issue. Please 👍  react and subscribe to that issue for further updates.
