### ISSUE TITLE
Add aws_api_gateway_usage_plan_stage_association resource

### ISSUE THREAD

**Issue by artikumari27** [hashicorp/terraform-provider-aws#16276]
I have tried with these two resources in latest aws version:3.15.0
---------------------------------------------------------------------------
resource "aws_api_gateway_usage_plan_association" "MyDemoAPIAssociation" {
  rest_api_id = "${aws_api_gateway_rest_api.MyDemoAPI.id}"
  stage_name = "dev"
  usage_plan_id = "y6fyrn" //get usage plan id
}
resource "aws_api_gateway_usage_plan_stage_association" "developers-version" {
  usage_plan_id = "y6fyrn"
  api_id = aws_api_gateway_rest_api.MyDemoAPI.id
  stage  = "dev"
}

unfortunately got same error for both:
---------------------------------------------
The provider provider.aws does not support resource type
"aws_api_gateway_usage_plan_association".

The provider provider.aws does not support resource type
"aws_api_gateway_usage_plan_stage_association".

**Comment by philnichol** [comment]
Hey @artikumari27 👋 
Looks like those resources (aws_api_gateway_usage_plan_association,aws_api_gateway_usage_plan_stage_association) don't exist in this provider.
From what I can see associating a stage to a usage plan must be done within the aws_api_gateway_usage_plan like in the examples [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_usage_plan).
Eg:
```hcl
resource "aws_api_gateway_usage_plan" "MyUsagePlan" {
  name         = "my-usage-plan"
  description  = "my description"
  product_code = "MYCODE"

  api_stages {
    api_id = aws_api_gateway_rest_api.myapi.id
    stage  = aws_api_gateway_deployment.dev.stage_name
  }

  api_stages {
    api_id = aws_api_gateway_rest_api.myapi.id
    stage  = aws_api_gateway_deployment.prod.stage_name
  }
}
```
Hope this helps, I'm not a maintainer so a more useful answer may still come from one of them 😃

**Comment by artikumari27** [comment]
yes I agree , but It will create a new usage plan. I don't want to create new usage plan. I want to add new stage to my existing usage plan.

**Comment by philnichol** [comment]
@artikumari27 makes sense, is the existing usage_plan managed by terraform?

**Comment by artikumari27** [comment]
Actually, I had Usage Plan is created Manually. Now I want to add a new stage in that through Terraform

**Comment by philnichol** [comment]
@artikumari27 ah right I see. Would importing your existing usage plan into terraform be an option? Assuming that's possible you could just add an api_stages block once it's been imported.

**Comment by gdavison** [comment]
Hi @artikumari27, thanks for your question. We don't currently have those resources in the provider, but they look like a good idea that would make the `aws_api_gateway_usage_plan` resource more composable.

Documentation for the AWS Provider and all of the resources and data sources supported can be found at https://registry.terraform.io/providers/hashicorp/aws/latest/docs.

If you have questions about using the AWS Provider, the AWS Provider forums at https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33 are a better place, since there are more community members participating there. The GitHub Issues are geared more towards errors and suggestions for improvements.

**Comment by gdavison** [comment]
Implementation Notes:

As with most `*_association` resources, `aws_api_gateway_usage_plan_stage_association` would be incompatible with `api_stages` blocks on `aws_api_gateway_usage_plan`. Make sure to document this on `aws_api_gateway_usage_plan_stage_association` and `aws_api_gateway_usage_plan` documentation pages.

This will be more useful for composition with a `aws_api_gateway_usage_plan` data source (#16323)

**Comment by gdavison** [comment]
@artikumari27, as @philnichol suggested, you can import an existing resource to make it managed by Terraform. This is documented at https://www.terraform.io/docs/import/index.html
