### ISSUE TITLE
GuardDuty auto-update TrustedIP list on change

### ISSUE THREAD

**Issue by xlrd** [hashicorp/terraform-provider-aws#16309]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

GuardDuty support was implemented in https://github.com/hashicorp/terraform-provider-aws/issues/2489, but if the contents of the file used in `aws_guardduty_ipset.MyIPSet` changes will not take effect until it is manually update via UI or [API](https://docs.aws.amazon.com/cli/latest/reference/guardduty/update-ip-set.html)

AWS Support confirmed that there is an enhancement request to make this update process "automatic", but I am just wondering if such functionality can be implemented on the TF level, somehow fire "update" call when file is changed?

### New or Affected Resource(s)

See `aws_guardduty_ipset.MyIPSet` https://github.com/hashicorp/terraform-provider-aws/issues/2489

### References

https://aws.amazon.com/premiumsupport/knowledge-center/guardduty-trusted-ip-list-alert/
https://docs.aws.amazon.com/cli/latest/reference/guardduty/update-ip-set.html

**Comment by gdavison** [comment]
Hi @xlrd, thanks for the suggestion. We typically don't monitor for changes in other resources to trigger an update in a resource. There are open issues on Terraform itself for options like this, such as https://github.com/hashicorp/terraform/issues/8099.

Depending on your workflow, you might be able to use the `terraform taint` command (https://www.terraform.io/docs/commands/taint.html) to force recreation of the IP Set.

Alternatively, you could use EventBridge rule that would listen for S3 object events to trigger a Lambda function that would update the IP Set.
