### ISSUE TITLE
service/networkfirewall: Investigate Tags Field in Describe API Calls

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#16300]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The general availability release of the Network Firewall APIs includes a `Tags` field in the following API calls:

* [`DescribeFirewall`](https://docs.aws.amazon.com/network-firewall/latest/APIReference/API_DescribeFirewall.html)
* [`DescribeFirewallPolicy`](https://docs.aws.amazon.com/network-firewall/latest/APIReference/API_DescribeFirewallPolicy.html)
* [`DescribeRuleGroup`](https://docs.aws.amazon.com/network-firewall/latest/APIReference/API_DescribeRuleGroup.html)

This may allow us to remove the extra [`ListTagsForResource`](https://docs.aws.amazon.com/network-firewall/latest/APIReference/API_ListTagsForResource.html) calls in the resources that support resource tagging.

### Affected Resource(s)

* aws_networkfirewall_firewall
* aws_networkfirewall_firewall_policy
* aws_networkfirewall_rule_group

### Potential Terraform Code

```go
// Replace

tags, err := keyvaluetags.NetworkfirewallListTags(conn, arn)
if err != nil {
	return diag.FromErr(fmt.Errorf("error listing tags for NetworkFirewall Firewall (%s): %w", arn, err))
}

if err := d.Set("tags", tags.IgnoreAws().IgnoreConfig(ignoreTagsConfig).Map()); err != nil {
	return diag.FromErr(fmt.Errorf("error setting tags: %w", err))
}

// With

if err := d.Set("tags", keyvaluetags.NetworkfirewallKeyValueTags(resp.Tags).IgnoreAws().IgnoreConfig(ignoreTagsConfig).Map()); err != nil {
	return diag.FromErr(fmt.Errorf("error setting tags: %w", err))
}
```

### References

* https://github.com/hashicorp/terraform-provider-aws/pull/16277#pullrequestreview-533640849
* [Contributing Guide on Running/Writing Acceptance Testing](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/contributing/running-and-writing-acceptance-tests.md)

**Comment by anGie44** [comment]
This enhancement has been merged and will release with `v3.17.0` of the Terraform AWS provider, likely out on Thurs.
