### ISSUE TITLE
Amazon S3 Storage Lens configuration

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#16310]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS S3 Storage Lens provides visibility into your storage usage and activity trends at the organization or account level, with aggregations by Region, storage class, bucket, and prefix.
Amazon S3 Storage Lens requires a _configuration_ that contains the properties that are used to aggregate metrics on your behalf for a single dashboard or export.

### New or Affected Resource(s)

* `aws_s3control_storage_lens_configuration`

### Potential Terraform Configuration

```hcl
resource "aws_s3control_storage_lens_configuration" "example" {
  config_id = "example-configuration"
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-s3-storage-lens-delivers-organization-wide-visibility-into-object-storage-usage-and-activity-trends/).
[Blog post](https://aws.amazon.com/blogs/aws/s3-storage-lens/).
[User Guide](https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage_lens.html)

Requires [AWS SDK v1.35.31](https://github.com/aws/aws-sdk-go/releases/tag/v1.35.31):

* #16308

**Comment by CarlInglisTT** [comment]
Is this on the teams roadmap with any sense of when it'll be added? Thanks.

**Comment by md5** [comment]
> Is this on the team;s roadmap with any sense of when it'll be added? Thanks.

It was added to the roadmap in https://github.com/hashicorp/terraform-provider-aws/pull/26166
