### ISSUE TITLE
`aws_cloudwatch_metric_alarm` does not preserve dimensions order nor is stable

### ISSUE THREAD

**Issue by calve** [hashicorp/terraform-provider-aws#16316]
Order of `dimensions` defined in a `metric` or `metric_query` is not preserved when applied to AWS, nor is stable. Also, changing the order in the source file is not reflected in Terraform plan.

This is a bug as dimension ordering is significant when querying metrics.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.12.29
+ provider.aws v2.70.0
+ provider.null v2.1.2
+ provider.random v2.2.1
```

### Affected Resource(s)

* `aws_cloudwatch_metric_alarm`

### Terraform Configuration Files

```hcl
resource "aws_cloudwatch_metric_alarm" "blocked_requests_high_rate" {
  alarm_name          = "waf-blocked-requests-high-rate"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = "1"
  threshold           = "1"

  metric_query {
    id          = "blocked_request_rate"
    expression  = "100*blocked_request_count/(blocked_request_count+allowed_request_count)"
    label       = "WAF blocked requests rate"
    return_data = "true"
  }

  metric_query {
    id = "blocked_request_count"
    metric {
      metric_name = "BlockedRequests"
      namespace   = "WAF"
      period      = "60"
      stat        = "Sum"
      unit        = "Count"

      dimensions = {
        Rule   = "ALL"
        Region = "eu-west-1"                                                                                               
        WebACL = "wafacl"
      }

    }
  }

  metric_query {
    id = "allowed_request_count"
    metric {
      metric_name = "AllowedRequests"
      namespace   = "WAF"
      period      = "60"
      stat        = "Sum"
      unit        = "Count"

      dimensions = {
        Rule   = "ALL"
        Region = "eu-west-1"                                                                                               
        WebACL = "wafacl"
      }
}
```

### Expected Behavior

Two things expected here;

 - Terraform should respect the `dimensions` order as it's defined. 
 - A change in the order of metric_query dimensions should reflect on `terraform plan`

### Actual Behavior

terraform does not preserve the dimension order, as one can see with the describe-alarms API;

```
$ aws cloudwatch describe-alarms --alarm-names=waf-blocked-requests-high-rate
{
    "MetricAlarms": [
        {
            "AlarmName": "wafacl-blocked-requests-high-rate",
            "AlarmDescription": "More than 1% of requests blocked on wafacl",
            "Dimensions": [],
            "EvaluationPeriods": 1,
            "Threshold": 1.0,
            "ComparisonOperator": "GreaterThanOrEqualToThreshold",
            "TreatMissingData": "notBreaching",
            "Metrics": [
                {
                    "Id": "blocked_request_rate",
                    "Expression": "100*blocked_request_count/(blocked_request_count+allowed_request_count)",
                    "Label": "WAF blocked requests rate",
                    "ReturnData": true
                },
                {
                    "Id": "allowed_request_count",
                    "MetricStat": {
                        "Metric": {
                            "Namespace": "WAF",
                            "MetricName": "AllowedRequests",
                            "Dimensions": [
                                {
                                    "Name": "Rule",
                                    "Value": "ALL"
                                },
                                {
                                    "Name": "Region",
                                    "Value": "eu-west-1"
                                },
                                {
                                    "Name": "WebACL",
                                    "Value": "wafacl"
                                }
                            ]
                        },
                        "Period": 60,
                        "Stat": "Sum",
                        "Unit": "Count"
                    },
                    "ReturnData": false
                },
                {
                    "Id": "blocked_request_count",
                    "MetricStat": {
                        "Metric": {
                            "Namespace": "WAF",
                            "MetricName": "BlockedRequests",
                            "Dimensions": [
                                {
                                    "Name": "Region",
                                    "Value": "eu-west-1"
                                },
                                {
                                    "Name": "WebACL",
                                    "Value": "wafacl"
                                },
                                {
                                    "Name": "Rule",
                                    "Value": "ALL"
                                }
                            ]
                        },
                        "Period": 60,
                        "Stat": "Sum",
                        "Unit": "Count"
                    },
                    "ReturnData": false
                }
            ]
        }
    ],
    "CompositeAlarms": []
}
```

You can see that list items in `MetricStat`/`Dimensions` gets different ordering. 
Deleting then recreating the ressource gets different ordering. Ordering is not stable across multiple invocations.
More over, changing Dimensions order in the source terraform file create an empty plan and terraform wont adjust the ressource. 

### Steps to Reproduce

1. Create a `aws_cloudwatch_metric_alarm` ressource as specified above
2. `terraform apply`

### References

https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricStatistics.html#API_GetMetricStatistics_RequestParameters mentions

> CloudWatch treats each unique combination of dimensions as a separate metric.

**Comment by gdavison** [comment]
Hi @calve, while the combinations of dimensions are unique, I can't find any reference to the order of the dimensions being significant. The definition of dimension combinations can be found at https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html#dimension-combinations

Are the alarms not functioning as expected?

**Comment by calve** [comment]
I can't either find any explicit reference of the order of the dimensions being significant. I guess that 

> CloudWatch treats each unique combination of dimensions as a separate metric

as read in both our links should be interpreted as «a different list of dimensions makes a different combinaison». I'm willing to open a ticket to AWS Support to clarify the claim if necessary. AWS API returning a list of map (in opposition to a map of items) might be a clue here. https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricAlarm.html also require an *Array of Dimension objects* but that does not make the order significant.

I could not find any issue in terraform-provider-aws and I would be surprised to be the first on the internet to see this behaviour. So I'm not 100% confident I'm correct in my claims and I could be understanding something incorrectly, in which case I'm willing to provide a documentation update when it's clearer.

Indeed, the alarms does not function as expected and one must manually update them, from the Cloudwatch console or via API. In the following screenshot, `m1` and `m2` are created Terraform and does not return values, where `m3` and `m4` are created in the Cloudwatch console and return metrics.

![Screenshot_20201119_215348](https://user-images.githubusercontent.com/4311079/99722931-bc337900-2ab1-11eb-99dc-51cfdda2fb81.png)


Hope I'm made myself clear, english is not my native language. Let me know if I can provide any other information.

**Comment by gdavison** [comment]
Thank you for the additional details. Since `m3` and `m4` work, and `m1` and `m2` don't, this definitely appears to be an error.

**Comment by calve** [comment]
After more investigations, it appears that my mistake was to declare `unit = Count`, which might not allowed in the WAF metrics context. This value is not exposed in Cloudwatch web console.

The following configuration work as expected

```terraform
resource "aws_cloudwatch_metric_alarm" "blocked_requests_high_rate" {
  alarm_name          = "waf-blocked-requests-high-rate"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = "1"
  threshold           = "1"

  metric_query {
    id          = "blocked_request_rate"
    expression  = "100*blocked_request_count/(blocked_request_count+allowed_request_count)"
    label       = "WAF blocked requests rate"
    return_data = "true"
  }

  metric_query {
    id = "blocked_request_count"
    metric {
      metric_name = "BlockedRequests"
      namespace   = "WAF"
      period      = "60"
      stat        = "Sum"

      dimensions = {
        Rule   = "ALL"
        Region = "eu-west-1"                                                                                               
        WebACL = "wafacl"
      }

    }
  }

  metric_query {
    id = "allowed_request_count"
    metric {
      metric_name = "AllowedRequests"
      namespace   = "WAF"
      period      = "60"
      stat        = "Sum"

      dimensions = {
        Rule   = "ALL"
        Region = "eu-west-1"                                                                                               
        WebACL = "wafacl"
      }
}
```

For any future reader, it appears that order of dimensions is indeed not significiant. Multiple permutations returns the same results.

**Comment by gdavison** [comment]
Thanks for the update, @calve!
