### ISSUE TITLE
Storagegateway NFS/SMB File Share default value for `DefaultStorageClass` does not match AWS Docs

### ISSUE THREAD

**Issue by DrFaust92** [hashicorp/terraform-provider-aws#16312]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the default value for the `DefaultStorageClass` field is `S3_STANDARD` but AWS docs show its `S3_INTELLIGENT_TIERING`

### New or Affected Resource(s)

* aws_storagegateway_nfs_file_share
* aws_storagegateway_smb_file_share

**Comment by pmkuny** [comment]
This is also not called out in the latest version of the Terraform docs for `aws_storagegateway_nfs_file_share` and `aws_storagegateway_smb_file_share` - both of those docs still list three tiers of storage class. I can confirm however, that manually setting `default_storage_class = S3_INTELLIGENT_TIERING` does deploy the file share correctly (only tested with NFS)
