### ISSUE TITLE
Add aws_api_gateway_usage_plan data source

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#16323]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In order to make the `aws_api_gateway_usage_plan` resource more composable, #16276 proposes adding a `aws_api_gateway_usage_plan_stage_association` resource. This association will be assisted by creating a data source to return Usage Plan information.

### New Data Source

* data.aws_api_gateway_usage_plan

### References

* #16276

**Comment by bruno-chavez** [comment]
I would really love this new data source, Im in a escenario where creating api keys on-demand is impossible if not placed in the same state where the usage plan is created!
