### ISSUE TITLE
Create Resources and Data Sources for User Groups and Users Redis 6.X RBAC

### ISSUE THREAD

**Issue by drarnold** [hashicorp/terraform-provider-aws#16327]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please incorporate the functionality of adding/updating/removing user groups and users for the redis elasticache integration.

### New or Affected Resource(s)

Impacted Existing Resources
- aws_elasticache_cluster
- aws_elasticache_replication_group

Impacted Existing Data Sources
- N/A

Impacted New Resources
- aws_elasticache_user_group
- aws_elasticache_user

Impacted New Data Sources
- aws_elasticache_user_group
- aws_elasticache_user

### Potential Terraform Configuration

Will need fully developed resources and data sources for this feature request.

### References
* https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Clusters.RBAC.html

**Comment by ewbankkit** [comment]
Related:

* https://github.com/hashicorp/terraform-provider-aws/issues/15625

**Comment by HaroonSaid** [comment]
Any Updates?

**Comment by drarnold** [comment]
Hey @HaroonSaid 
I was actually going to start working on this pull request during my company's Hackathon since this will be something that we will need in the future.  Not sure if anyone is working on it from the Hashicorp side, but willing to work with someone to get this pushed out for usage.

**Comment by bill-rich** [comment]
User and user group PRs have been merged

**Comment by jamesglennan** [comment]
Am I right in understanding that the above code merge allows the creation of user and usergroups but doesn't allow us to create an association between a usergroup and an elasticache cluster yet? If this is the case, should this be filed in a separate issue or re-open this one?

**Comment by ramekin** [comment]
@jamesglennan - I am not seeing a way to associate a usergroup with the cluster either. I just went down the path of creating some users and a usergroup and realized there was still that last manual step.

**Comment by jamesglennan** [comment]
@ramekin I have created another issue https://github.com/hashicorp/terraform-provider-aws/issues/20328
I have some code that i need to test out to implement this, however note this will only affect the replication_group resource (as opposed to the cluster resource) because of limitation on aws side- their api and go-sdk only support this on replication_group resources

I'm still fuzzy on the real difference, but as i understand one is more for memcache the other more for redis? So i guess it makes sense why usergroups arent supported.
