### ISSUE TITLE
aws_lb_listener

### ISSUE THREAD

**Issue by salsop** [hashicorp/terraform-provider-aws#16329]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/aws v3.16.0

### Affected Resource(s)

* aws_lb_listener

### Terraform Configuration Files

```hcl
resource "aws_lb_listener" "gwlb" {
  load_balancer_arn = aws_lb.gwlb.arn
//  port = 6081
  default_action {
    type = "forward"
    target_group_arn = aws_lb_target_group.vmseries.arn
  }
}
```

### Expected Behavior

Create Listener for Gateway Load Balancer

### Actual Behavior

With Port Specified:

```
aws_lb_listener.gwlb: Creating...

Error: error creating ELBv2 Listener: ValidationError: A port cannot be specified for gateway listeners
	status code: 400, request id: c010b6d2-7dab-4f78-a1b9-ffb0f2af0e46
```

Without Port Specified:

```
Error: Missing required argument

  on main.tf line 177, in resource "aws_lb_listener" "gwlb":
 177: resource "aws_lb_listener" "gwlb" {

The argument "port" is required, but no definition was found.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ewbankkit** [comment]
@salsop Thanks for raising this issue.
It has already been noticed in #16228. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
