### ISSUE TITLE
AWS Glue Schema Registry

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#16342]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The AWS Glue Schema Registry is a new feature that allows you to centrally discover, control, and evolve data stream schemas.

### New or Affected Resource(s)

* `aws_glue_registry`
* `aws_glue_schema`

### Potential Terraform Configuration

```hcl
resource "aws_glue_registry" "example" {
  name = "example-registry"
}

resource "aws_glue_schema" "example" {
  registry_id {
    registry_arn = aws_glue_registry.example.arn
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/11/control-evolution-data-streams-using-aws-glue-schema-registry/).
[Developer Guide](https://docs.aws.amazon.com/glue/latest/dg/schema-registry.html).

Requires [AWS SDK v1.35.32](https://github.com/aws/aws-sdk-go/releases/tag/v1.35.32):

* https://github.com/hashicorp/terraform-provider-aws/pull/16339

**Comment by DrFaust92** [comment]
Working on this now.
