### ISSUE TITLE
ALB support for HTTP/2 and gRPC

### ISSUE THREAD

**Issue by kevinkirkup** [hashicorp/terraform-provider-aws#16341]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The AWS ALB supports new settings for HTTP/2 and gRPC
https://aws.amazon.com/blogs/aws/new-application-load-balancer-support-for-end-to-end-http-2-and-grpc/

### New or Affected Resource(s)

* aws_lb_target_group

### Potential Terraform Configuration

```hcl
resource "aws_lb_target_group" "ip-example" {
  name        = "tf-example-lb-tg"
  port        = 80
  protocol    = "HTTP"
  protocol_version = "gRPC"                                            <-------------- Here
  target_type = "ip"
  vpc_id      = aws_vpc.main.id
}
```

### References

* #0000

**Comment by ewbankkit** [comment]
@kevinkirkup Thanks for raising this issue.
It has already been noticed in #15929. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
