### ISSUE TITLE
Add destination metrics for Replication rule

### ISSUE THREAD

**Issue by JoshiiSinfield** [hashicorp/terraform-provider-aws#16347]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It is now possible to enable metrics on a replication rule that is not S3 Replication Time Control

### New or Affected Resource(s)

aws_s3_bucket

* aws_XXXXX

### Potential Terraform Configuration

```hcl
replication_configuration = {
   ...
    destination = {
        metrics = {
            status = "Enabled"
        }
        bucket = ""
        account_id = ""
    }
}
        
```

### References

* loosely related to #11337
* https://docs.aws.amazon.com/AmazonS3/latest/dev/replication-metrics.html

**Comment by robertstettner** [comment]
Hey @timoguin, I am very interested in this feature, will you eventually raise a PR against upstream? Thanks!

**Comment by timoguin** [comment]
Hey @robertstettner, unfortunately my PR doesn't work. I discovered in testing that the metrics depend on enabling Replication Time Control, which has an open PR: #11337. It hasn't been reviewed yet, but I can confirm that it works. I've added a comment on the PR sharing my thoughts.

**Comment by timoguin** [comment]
To clarify, this feature isn't loosely related to #11337. It is actually dependent on enabling Replication Time Control.

**Comment by jrutroff** [comment]
This isn't true anymore.  You can now enable replication metrics on a bucket that does not have RTC enabled.  I have testing this in the S3 console.  

Announcement:
https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-s3-replication-adds-support-for-metrics-and-notifications/

New doc link:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication-metrics.html

**Comment by caiohasouza** [comment]
Hi!

Some update about this feature? We using the "Replication metrics and notifications" to enable support to send notifications if replication has problems using "Event Notifications", so for us this feature is very important.

Regards

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

**Comment by raelga** [comment]
Awesome @breathingdust , thanks!

**Comment by DrFaust92** [comment]
This is now available via `s3_bucket_replication_configuration` resource
