### ISSUE TITLE
aws_subnet support map_coip_on_launch

### ISSUE THREAD

**Issue by brylex418** [hashicorp/terraform-provider-aws#16349]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### aws_subnet should support map_coip_on_launch

this will allow an IP from the COIP pool to be mapped to the ENI on an ec2 instance when launched into the subnet created by terraform.  

* aws_subnet

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by ewbankkit** [comment]
@brylex418 Thanks for raising this issue.
It has already been noticed in #13170. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
