### ISSUE TITLE
internal/keyvaluetags: Generate Context-Aware Functions

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#16346]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

_Note: Do not implement this until after version 3.17.0 release_

The generators in `internal/keyvaluetags` are tailored to our current AWS Go SDK receiver method usage without `context.Context`. While we do not have a specific need for it today, as we continue our experimentation with end-to-end resource context handling, we will eventually come across the need to pass through the context to AWS Go SDK calls provided by this functionality. Ideally the generators should create both context and non-context functions, in a DRY fashion.

Adding something like the below for each of the templates should hopefully be on the right track:

```go
// Code generated by generators/listtags/main.go; DO NOT EDIT.

package keyvaluetags

import (
	"context"

	"github.com/aws/aws-sdk-go/aws"
{{- range .ServiceNames }}
	"github.com/aws/aws-sdk-go/service/{{ . }}"
{{- end }}
)
{{ range .ServiceNames }}

// {{ . | Title }}ListTags lists {{ . }} service tags.
// The identifier is typically the Amazon Resource Name (ARN), although
// it may also be a different identifier depending on the service.
func {{ . | Title }}ListTags(conn {{ . | ClientType }}, identifier string{{ if . | TagResourceTypeField }}, resourceType string{{ end }}) (KeyValueTags, error) {
	return {{ . | Title }}ListTagsWithContext(context.Background(), identifier{{ if . | TagResourceTypeField }}, resourceType{{ end }})
}

// {{ . | Title }}ListTagsWithContext lists {{ . }} service tags.
// The identifier is typically the Amazon Resource Name (ARN), although
// it may also be a different identifier depending on the service.
func {{ . | Title }}ListTagsWithContext(ctx context.Context, conn {{ . | ClientType }}, identifier string{{ if . | TagResourceTypeField }}, resourceType string{{ end }}) (KeyValueTags, error) {
	input := &{{ . | TagPackage  }}.{{ . | ListTagsFunction }}Input{
		{{- if . | ListTagsInputFilterIdentifierName }}
		Filters: []*{{ . | TagPackage  }}.Filter{
			{
				Name:   aws.String("{{ . | ListTagsInputFilterIdentifierName }}"),
				Values: []*string{aws.String(identifier)},
			},
		},
		{{- else }}
		{{- if . | ListTagsInputIdentifierRequiresSlice }}
		{{ . | ListTagsInputIdentifierField }}: aws.StringSlice([]string{identifier}),
		{{- else }}
		{{ . | ListTagsInputIdentifierField }}: aws.String(identifier),
		{{- end }}
		{{- if . | TagResourceTypeField }}
		{{ . | TagResourceTypeField }}:         aws.String(resourceType),
		{{- end }}
		{{- end }}
	}

	output, err := conn.{{ . | ListTagsFunction }}WithContext(ctx, input)

	if err != nil {
		return New(nil), err
	}

	return {{ . | Title }}KeyValueTags(output.{{ . | ListTagsOutputTagsField }}{{ if . | TagTypeIdentifierField }}, identifier{{ if . | TagResourceTypeField }}, resourceType{{ end }}{{ end }}), nil
}
{{- end }}
```

### References

- [Integrate Provider Context For Cancelling Requests](https://github.com/hashicorp/terraform-provider-aws/issues/4177)
- [internal/generators/listpages: Generate Context-Aware Functions](https://github.com/hashicorp/terraform-provider-aws/issues/16344)

**Comment by ewbankkit** [comment]
Implemented in https://github.com/hashicorp/terraform-provider-aws/pull/25238.
