### ISSUE TITLE
aws_route_table - I can't see a way to specify a Network Firewall resource

### ISSUE THREAD

**Issue by dsw88** [hashicorp/terraform-provider-aws#16355]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.16.0

### Affected Resource(s)
* aws_route_table

### Expected Behavior
Terraform just released day-one support for AWS Network Firewall. The firewall resources themselves are all working properly. However, I of course need to configure route tables to route traffic to the firewall. The aws_route_table resource does not have any resources for network_firewall_id or something similarly named. I can't see any way to add my firewall to the route table.

### Steps to Reproduce
1. Create a new network firewall resource
2. Create a route table
3. Attempt to reference the network firewall ID in the route table.

Thanks!

**Comment by ewbankkit** [comment]
@dsw88 Thanks for raising this issue.
A route to a Network Firewall can be specified by setting the route's `vpc_endpoint_id` attribute. However, the VPC Endpoint ID of the Network Firewall is not currently returned - See #16350.
