### ISSUE TITLE
New Data Source: aws_imagebuilder_image

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#16377]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support lookup of an Image Builder Image.

### New Data Source

* aws_imagebuilder_image

### Potential Terraform Configuration

```hcl
data "aws_imagebuilder_image" "example" {
  arn   = "" # Optional
  most_recent_date_created = true # Optional
  owner = "" # Optional

  filter { # Optional
    name = "" # Required
    values = "" # Required
  }
}
```

Potentially can support functionality.

### References

* [Initial Support for EC2 Image Builder](https://github.com/hashicorp/terraform-provider-aws/issues/11084)
* [`GetImage` API Reference](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_GetImage.html)
* [`ListImages` API Reference](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_ListImages.html)
* [AWS Go SDK `service/imagebuilder`](https://docs.aws.amazon.com/sdk-for-go/api/service/imagebuilder/)
* [Contributing Guide](https://github.com/hashicorp/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md)

**Comment by Dogers** [comment]
The datasource makes sense to me, so you can then build upon an image in another pipeline:
AWS Base Image > Pipeline A > Image A
Image A > Pipeline B > Image B

**Comment by bflad** [comment]
Submitted: https://github.com/hashicorp/terraform-provider-aws/pull/16710

This solely uses the `GetImage` API, whose `ImageBuildVersionArn` field accepts `x.x.x` wildcards and returns the latest image, so no extra `most_recent`-type argument is necessary. 👍  If the other type of filtering is desirable, it probably should be implemented in a separate plural data source (`aws_imagebuilder_images`) that uses the `ListImages` API and can return multiple results.
