### ISSUE TITLE
Support waf fail open attribute for ALB

### ISSUE THREAD

**Issue by iwasnobody** [hashicorp/terraform-provider-aws#16372]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

By default, if the load balancer cannot get a response from AWS WAF, it returns an HTTP 500 error and
does not forward the request. If you need your load balancer to forward requests to targets even if it is
unable to contact AWS WAF, you can enable the WAF fail open attribute.

So I want alb resource can support this waf fail open attribute.
### New or Affected Resource(s)

* aws_lb

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References
https://docs.amazonaws.cn/en_us/elasticloadbalancing/latest/application/elb-ag.pdf

* #0000

**Comment by nunofernandes** [comment]
Also had this exact issue yesterday in eu-west-1 region... Having this feature in the terraform-aws provider would help out!

**Comment by shuheiktgw** [comment]
I've created a PR to support the WAF fail open attribute so please upvote it for a faster review! 🙏 

https://github.com/hashicorp/terraform-provider-aws/pull/16393
