### ISSUE TITLE
AWS RDS Proxy

### ISSUE THREAD

**Issue by stnslav** [hashicorp/terraform-provider-aws#16379]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

**terraform 0.13.6**

### Affected Resource(s)

**AWS RDS Proxy
* aws_db_proxy -> auth -> username**

### Expected Behavior

**username in auth variables need to be added to provider as your documentation have it and latest provider not**

### Actual Behavior

**Error: Unsupported argument

  on main.tf line 43, in resource "aws_db_proxy" "db_proxy":
  43:       username    = "username"

An argument named "username" is not expected here.**

### Steps to Reproduce

**creating a resource, entering, user name, and for example terraform plan**

1. `terraform apply`

### References

* #0000

**Comment by stnslav** [comment]
+ latest provider version

**Comment by stnslav** [comment]
Please also adjust Secret Manager to secret types, currently it's not giving an option to create secret with "credentials for database"

**Comment by njlr** [comment]
I have also encountered this issue.

I think an RDS secret is just a regular secret with a particular format. You can recreate that format like this: 

```hcl
resource "aws_secretsmanager_secret_version" "my_db_proxy" {
  secret_id     = aws_secretsmanager_secret.my_db_proxy.id
  secret_string = jsonencode({
    "username"             = aws_db_instance.my_db.username
    "password"             = var.db_password
    "engine"               = "postgres"
    "host"                 = aws_db_instance.my_db.address
    "port"                 = 5432
    "dbInstanceIdentifier" = aws_db_instance.my_db.id
  })
}
```

**Comment by stnslav** [comment]
> I have also encountered this issue.
> 
> I think an RDS secret is just a regular secret with a particular format. You can recreate that format like this:
> 
> ```terraform
> resource "aws_secretsmanager_secret_version" "my_db_proxy" {
>   secret_id     = aws_secretsmanager_secret.my_db_proxy.id
>   secret_string = jsonencode({
>     "username"             = aws_db_instance.my_db.username
>     "password"             = var.db_password
>     "engine"               = "postgres"
>     "host"                 = aws_db_instance.my_db.address
>     "port"                 = 5432
>     "dbInstanceIdentifier" = aws_db_instance.my_db.id
>   })
> }
> ```

Did it with null_resource & CLI :)

**Comment by njlr** [comment]
> > I have also encountered this issue.
> > I think an RDS secret is just a regular secret with a particular format. You can recreate that format like this:
> > ```terraform
> > resource "aws_secretsmanager_secret_version" "my_db_proxy" {
> >   secret_id     = aws_secretsmanager_secret.my_db_proxy.id
> >   secret_string = jsonencode({
> >     "username"             = aws_db_instance.my_db.username
> >     "password"             = var.db_password
> >     "engine"               = "postgres"
> >     "host"                 = aws_db_instance.my_db.address
> >     "port"                 = 5432
> >     "dbInstanceIdentifier" = aws_db_instance.my_db.id
> >   })
> > }
> > ```
> 
> Did it with null_resource & CLI :)

I'm not sure if my solution actaully works, since I still get `DBProxy Target unavailable due to an internal error`:

```json
{
    "Targets": [
        {
            "Endpoint": "mydb.aaaaaaaaaaaa.eu-west-2.rds.amazonaws.com",
            "RdsResourceId": "mydb",
            "Port": 5432,
            "Type": "RDS_INSTANCE",
            "TargetHealth": {
                "State": "UNAVAILABLE",
                "Description": "DBProxy Target unavailable due to an internal error"
            }
        }
    ]
}
```

Would you mind sharing your configuration?

**Comment by stnslav** [comment]
> > > I have also encountered this issue.
> > > I think an RDS secret is just a regular secret with a particular format. You can recreate that format like this:
> > > ```terraform
> > > resource "aws_secretsmanager_secret_version" "my_db_proxy" {
> > >   secret_id     = aws_secretsmanager_secret.my_db_proxy.id
> > >   secret_string = jsonencode({
> > >     "username"             = aws_db_instance.my_db.username
> > >     "password"             = var.db_password
> > >     "engine"               = "postgres"
> > >     "host"                 = aws_db_instance.my_db.address
> > >     "port"                 = 5432
> > >     "dbInstanceIdentifier" = aws_db_instance.my_db.id
> > >   })
> > > }
> > > ```
> > 
> > 
> > Did it with null_resource & CLI :)
> 
> I'm not sure if my solution actaully works, since I still get `DBProxy Target unavailable due to an internal error`:
> 
> ```json
> {
>     "Targets": [
>         {
>             "Endpoint": "mydb.aaaaaaaaaaaa.eu-west-2.rds.amazonaws.com",
>             "RdsResourceId": "mydb",
>             "Port": 5432,
>             "Type": "RDS_INSTANCE",
>             "TargetHealth": {
>                 "State": "UNAVAILABLE",
>                 "Description": "DBProxy Target unavailable due to an internal error"
>             }
>         }
>     ]
> }
> ```
> 
> Would you mind sharing your configuration?

**"DBProxy Target unavailable due to an internal error"** -> check settings for security group, try with inbound/outbound 0.0.0.0/0, after that limit the traffic to specific CIDRs

**"Proxy does not have any registered credentials"** -> Check your IAM role, the correct one is

**iam_role** resource assume_role_policy

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": ["sts:AssumeRole"],
      "Effect": "Allow",
      "Principal": {
        "Service": ["rds.amazonaws.com"]
      }
    }
  ]
}

**aws_iam_policy** resource


{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Access1",
            "Effect": "Allow",
            "Action": [
                "secretsmanager:GetResourcePolicy",
                "secretsmanager:GetSecretValue",
                "secretsmanager:DescribeSecret",
                "secretsmanager:ListSecretVersionIds"
            ],
            "Resource": [
                "arn:aws:secretsmanager:<region>:<account_id>:secret:*"
            ]
        },
        {
            "Sid": "Access2",
            "Effect": "Allow",
            "Action": "kms:Decrypt",
            "Resource": "arn:aws:kms:<region>:<account_id>:key/*"
        }
    ]
}
EOF
}


**For VPC subnets in aws, make sure availability zone "us-east-1e" is excluded**

**Comment by stnslav** [comment]
sorry GitHub is messing the syntax, anyway should help

**Comment by njlr** [comment]
> sorry GitHub is messing the syntax, anyway should help

Very helpful. Thanks!

**Comment by Simonl9l** [comment]
Albeit out use case is with MySQL, this is pretty much to _only_ google hit for `Proxy does not have any registered credentials`, and we are using TF! 

We have all the above policies set as above; however we had scoped it to the the specific secret manager key and set that `kms_key_id` in the secret setup:

```hcl
resource "aws_secretsmanager_secret" "<name>" {
  name                    = mysql_user.<user>.user
  recovery_window_in_days = 0
  kms_key_id              = arn:aws:kms:<region>:<account>:key/<id of aws/secretsmanger key>
} 
```


Of note it is [documented](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html) that the proxy ignores any additional values defaulted in the `secret_string` except **`username`** and **`password`**!    

![image](https://user-images.githubusercontent.com/66816457/108018397-790f7600-6fcc-11eb-8525-d7de248f14f2.png)

Per the portal there are secrets set up with the secret `name` as the as the `mysql_user.<user>.user` with the correct data with the secret version set up as follows:
```hcl
secret_string = jsonencode({
    username = mysql_user.<user>.user
    password = mysql_user.<user>.plaintext_password
})
```
all a mystery!
