### ISSUE TITLE
AWS HTTP API example

### ISSUE THREAD

**Issue by Chanonry** [hashicorp/terraform-provider-aws#16382]
Any news on the HTTP API example ??

@zhaoyi0113 Thanks for opening this.
Integrations are attached to routes via the [`aws_apigatewayv2_route.target`](https://www.terraform.io/docs/providers/aws/r/apigatewayv2_route.html) attribute, for example

```hcl
resource "aws_apigatewayv2_integration" "ConnectIntegrat" {
  api_id             = "${aws_apigatewayv2_api.SimpleChatWebSocket.id}"
  integration_type   = "AWS_PROXY"
  description        = "Connect Integration"
  integration_uri    = "${aws_lambda_function.OnConnectFunction.invoke_arn}"
  integration_method = "POST"
}

resource "aws_apigatewayv2_route" "ConnectRoute" {
  api_id         = "${aws_apigatewayv2_api.SimpleChatWebSocket.id}"
  route_key      = "$connect"
  operation_name = "ConnectRoute"
  target         = "integrations/${aws_apigatewayv2_integration.ConnectIntegrat.id}"
}
```

A full-featured WebSocket API example is in https://github.com/terraform-providers/terraform-provider-aws/pull/9533.
We will provide similar examples for HTTP APIs.

_Originally posted by @ewbankkit in https://github.com/hashicorp/terraform-provider-aws/issues/12934#issuecomment-617785410_

**Comment by ewbankkit** [comment]
@Chanonry Thanks for raising this issue.
Could you suggest any examples you are aware of that could be translated to Terraform?
There are some here - https://github.com/aws-samples/sessions-with-aws-sam - that seem suitable candidates.

**Comment by Chanonry** [comment]
That’s one of the problems, there are limited numbers of examples out there and they tend to be a bit simplistic. The sam example you attached looks like a decent start. I will be interested to see how you attache AuthenticationScopes. I will have a dig around tomorrow and see if there are any others

**Comment by Chanonry** [comment]
I worked through this yesterday which is not exactly comprehensive but is better than other examples which tend to be extremely minimalist. It is also demonstrating an api with OIDC and OAUTH. Digging down in the comments led me to adding scopes to the JWT Authorizer which gave rise to #16387  

[https://auth0.com/blog/securing-aws-http-apis-with-jwt-authorizers/](url)

**Comment by ewbankkit** [comment]
There are some potential HTTP API candidates in [this repo](https://github.com/aws-samples/sessions-with-aws-sam) that could be translated from SAM.
