### ISSUE TITLE
Adding scopes to aws_apigatewayv2_authorizer

### ISSUE THREAD

**Issue by Chanonry** [hashicorp/terraform-provider-aws#16387]
How can I add scopes to an http api JWT authorizer ?  I can do it in the console but it isn't obvious to me how to configure that in terraform?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.29

### Affected Resource(s)

aws_apigatewayv2_authorizer

### Terraform Configuration Files

resource "aws_apigatewayv2_authorizer" "example" {
  api_id           = aws_apigatewayv2_api.api_v2.id
  authorizer_type  = "JWT"
  identity_sources = ["$request.header.Authorization"]
  name             = "test-lambda-authorizer-${terraform.workspace}"

  jwt_configuration {
    audience = ["example"]
    issuer   = "https://${aws_cognito_user_pool.example.endpoint}"
  }
}
```
* #0000

**Comment by ewbankkit** [comment]
Related:

* https://github.com/hashicorp/terraform-provider-aws/issues/16382

**Comment by ewbankkit** [comment]
@Chanonry Thanks for raising this issue.
To add another audience, say **example2**, add it the `jwt_configuration.audience` list:

```hcl
resource "aws_apigatewayv2_authorizer" "example" {
  api_id = aws_apigatewayv2_api.api_v2.id

  authorizer_type = "JWT"
  identity_sources = ["$request.header.Authorization"]

  name = "test-lambda-authorizer-${terraform.workspace}"

  jwt_configuration {
    audience = ["example", "example2"]
    issuer = "https://${aws_cognito_user_pool.example.endpoint}"
  }
}
```

and run `terraform apply`.

**Comment by Chanonry** [comment]
Thanks but I want to add a scope to an JWT Authorizer such as pets:get or wish-list:add

The example in the other thread attaches a scope to the api which isn’t what I am after but does show an implementation of the concept. From the SAM template its the AuthorizationScopes piece:

Auth:
        Authorizers:
          GeneralAuth:
            AuthorizationScopes:
              - email
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPoolId}
              audience:
                - !Ref Audience

**Comment by Chanonry** [comment]
As per this:

![output-onlinepngtools](https://user-images.githubusercontent.com/20876829/100070238-98fe2600-2e31-11eb-9479-281ca4ae0fdd.png)

**Comment by ewbankkit** [comment]
@Chanonry Those scopes are specified via the `aws_apigatewayv2_route` resource's [`authorization_scopes`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_route#authorization_scopes) attribute.
Agree that documentation and examples are missing here.

**Comment by Chanonry** [comment]
Excellent thanks for this. 

The console was leading me to look for the field in the authorizer resource while actually the scope/s are arguably really a route parameter. A hole a number of people will fall into I suspect.
