### ISSUE TITLE
aws_mq_broker required attribute list in documentation is incomplete

### ISSUE THREAD

**Issue by awshew** [hashicorp/terraform-provider-aws#16395]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.16.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* aws_mq_broker

### Terraform Configuration Files

Tried to create an aws_mq_broker resource using only the attributes marked as required in https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mq_broker and received this error:

```
Error: Required attribute is not set

  on main.tf line 2, in resource "aws_mq_broker" "activemq_broker":
   2: resource "aws_mq_broker" "activemq_broker" {
```

Resource looked like this:
```
resource "aws_mq_broker" "activemq_broker" {
  broker_name        = var.broker_name
  engine_type        = "ActiveMQ"
  engine_version     = var.activemq_version
  host_instance_type = var.mq_instance_type
  security_groups    = [aws_security_group.allowed_traffic.id]
  apply_immediately  = var.apply_immediately
  deployment_mode    = "ACTIVE_STANDBY_MULTI_AZ"
  subnet_ids         = var.broker_subnet_list

  encryption_options {
    kms_key_id        = aws_kms_key.amq_kms_key.arn
    use_aws_owned_key = false
  }

  tags = {
    Name = var.broker_name
    Managed_by = "Terraform"
  }
}
```

Confirmed all vars were defined and set to acceptable values. After a lot of trial and error, discovered that you MUST supply a user block with a user and password (even if granting it no permissions/groups). Final working resource block looks like:
```
resource "aws_mq_broker" "activemq_broker" {
  broker_name        = var.broker_name
  engine_type        = "ActiveMQ"
  engine_version     = var.activemq_version
  host_instance_type = var.mq_instance_type
  security_groups    = [aws_security_group.allowed_traffic.id]
  apply_immediately  = var.apply_immediately
  deployment_mode    = "ACTIVE_STANDBY_MULTI_AZ"
  subnet_ids         = var.broker_subnet_list

  encryption_options {
    kms_key_id        = aws_kms_key.amq_kms_key.arn
    use_aws_owned_key = false
  }

  user {
    username = "ExampleUser"
    password = "RedactedPasswordForExample"
  }
  
  tags = {
    Name = var.broker_name
    Managed_by = "Terraform"
  }
}
```

### Debug Output
https://gist.github.com/awshew/c3548df0606cf9828737f86a58fe6e46

### Expected Behavior
Defining all required attributes (and only those options) should create a resource

### Actual Behavior
Resource creation errored, citing missing required attributes

### Steps to Reproduce

1. `terraform plan`

### Important Factoids
We're using Terraform Enterprise as a backend

**Comment by alvarodelvalle** [comment]
Hi 👋🏽 I would be interested in working on this issue! Any contributing guidelines on updating the website files?
