### ISSUE TITLE
Amazon Kinesis Data Streams for Amazon DynamoDB

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#16406]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Kinesis Data Streams for DynamoDB captures item-level modifications in any DynamoDB table and replicates them to a Kinesis data stream of your choice.

### New or Affected Resource(s)

* `aws_dynamodb_kinesis_streaming_destination`

### Potential Terraform Configuration

```hcl
resource "aws_dynamodb_kinesis_streaming_destination" "example" {
  table_name = aws_dynamodb_table.example.name
  stream_arn = aws_kinesis_stream.example.arn
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/11/now-you-can-use-amazon-kinesis-data-streams-to-capture-item-level-changes-in-your-amazon-dynamodb-table/).
[Developer Guide](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/kds.html).

Requires [AWS SDK v1.35.34](https://github.com/aws/aws-sdk-go/releases/tag/v1.35.34):

* https://github.com/hashicorp/terraform-provider-aws/pull/16381

**Comment by matthewrj** [comment]
Fixed by https://github.com/hashicorp/terraform-provider-aws/pull/16743

**Comment by terozio** [comment]
Any news when this might be released? The pull request has been ready for more than a month.

**Comment by barryoneill** [comment]
Yes, we're eagerly awaiting this feature too :)

**Comment by matthewrj** [comment]
Would love an update on when we can expect the PR to be reviewed.

**Comment by barryoneill** [comment]
It really feels like they're pushing folks to the newer [kinesis change data capture solution](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/streamsmain.html#streamsmain.choose) but "Duplicate records might occasionally appear in the stream."  isn't exactly a sales pitch :)

**Comment by JennyLeahy** [comment]
Any update on the release date?

**Comment by marcote** [comment]
Does anybody know who we need to assign to release this feature?

**Comment by mansi135** [comment]
We are waiting on this feature too :)
