### ISSUE TITLE
PoolArn attribute support in Data Source: aws_ec2_coip_pool

### ISSUE THREAD

**Issue by FireballDWF** [hashicorp/terraform-provider-aws#16426]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

add return the attribute PoolArn (or pool_arn or arn), as arn is required for aws_ram_resource_association.resource_arn

### New or Affected Resource(s)

* aws_ec2_coip_pool

### References

* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CoipPool.html

**Comment by ewbankkit** [comment]
Relates: https://github.com/hashicorp/terraform-provider-aws/issues/16978.
