### ISSUE TITLE
Support wrapped errors in tfresource.TimedOut()

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#16425]
`tfresource.TimedOut()` only tests that the top-level error is of type `resource.TimeoutError`. Extend it to support wrapped `resource.TimeoutError` errors.

`tfresource.TimedOut()` is used throughout the provider, so thorough testing will be required.

**Comment by ewbankkit** [comment]
Also ` isResourceTimeoutError()`

https://github.com/hashicorp/terraform-provider-aws/blob/70eea15f4253783d30267d465813ded6b56ab7f9/aws/utils.go#L51-L54

which is still used extensively.

**Comment by gdavison** [comment]
Ha, that's the same implementation.

Also `isResourceNotFoundError()` in the same file

**Comment by gdavison** [comment]
I prefer the naming pattern of `Is<whatever>Error()`

**Comment by ewbankkit** [comment]
I agonized over the naming in https://github.com/hashicorp/terraform-provider-aws/pull/15477.
What decided it for me was that `isResourceTimeoutError` is testing more than just that the error is of type `resource.TimeoutError`.
