### ISSUE TITLE
Can not tag a TGW VPN attachment

### ISSUE THREAD

**Issue by gchek** [hashicorp/terraform-provider-aws#16438]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.14.0
+ provider registry.terraform.io/terraform-providers/vmc v1.4.0

### Affected Resource(s)

* aws_ec2_transit_gateway_vpc_attachment

### Terraform Configuration Files

```hcl
resource "aws_ec2_transit_gateway_vpc_attachment" "TGW-attach-Egress" {
  subnet_ids          = [var.vpc-egress-30-private-A, var.vpc-egress-40-private-B]
  transit_gateway_id  = aws_ec2_transit_gateway.TGW.id
  transit_gateway_default_route_table_association = false
  transit_gateway_default_route_table_propagation = false
  vpc_id              = var.egress-vpc_id
  tags = {
    Name = "TGW-attach-Egress-VPC"
  }
}

/*===========================================
Add VPN Site to site and TGW VPN attachment
============================================*/
// 1- Customer  GW (the  SDDC side)
resource "aws_customer_gateway" "VMC" {
  bgp_asn    = var.SDDC_ASN_VPN
  ip_address = var.SDDC_VPN_publicIP
  type       = "ipsec.1"
  tags = {
    Name = "VMC-Side-VPN"
  }
}
// 2- Build a VPN connection to TGW
resource "aws_vpn_connection" "RB_VPN" {
  customer_gateway_id = aws_customer_gateway.VMC.id
  transit_gateway_id  = aws_ec2_transit_gateway.TGW.id
  type                = aws_customer_gateway.VMC.type
  tunnel1_inside_cidr = var.tunnel1_inside_cidr
  tunnel2_inside_cidr = var.tunnel2_inside_cidr
  tunnel1_preshared_key = var.tunnels_preshared_key
  tunnel2_preshared_key = var.tunnels_preshared_key
  tags = {
    Name = "VPN to SDDC"
  }
}

data "aws_ec2_transit_gateway_vpn_attachment" "TGW_attach_SDDC" {
  transit_gateway_id = aws_ec2_transit_gateway.TGW.id
  vpn_connection_id  = aws_vpn_connection.RB_VPN.id
}

```

### Expected Behavior

Looking for a way to tag the VPN TGW attachment similar to the VPC attachment

<img width="762" alt="Screenshot 2020-11-24 at 09 28 23" src="https://user-images.githubusercontent.com/25104887/100252283-fbdde300-2f3f-11eb-81f0-a8d67279c163.png">

**Comment by bflad** [comment]
Hi @gchek 👋  EC2 Transit Gateway VPN Attachments are a little special in that they are implicitly created by the VPN Connection with a Transit Gateway ID and not a separate managed resource. Good news for you though (and one of the reasons we introduced this), you actually can tag these via the existing [`aws_ec2_tag` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_tag). 

Combining the example and your configuration above, something like this might get you close:

```terraform
resource "aws_vpn_connection" "RB_VPN" {
  customer_gateway_id = aws_customer_gateway.VMC.id
  transit_gateway_id  = aws_ec2_transit_gateway.TGW.id
  type                = aws_customer_gateway.VMC.type
  tunnel1_inside_cidr = var.tunnel1_inside_cidr
  tunnel2_inside_cidr = var.tunnel2_inside_cidr
  tunnel1_preshared_key = var.tunnels_preshared_key
  tunnel2_preshared_key = var.tunnels_preshared_key
  tags = {
    Name = "VPN to SDDC"
  }
}

resource "aws_ec2_tag" "TGW_attach_SDDC" {
  resource_id = aws_vpn_connection.RB_VPN.transit_gateway_attachment_id
  key         = "Name"
  value       = "TGW-attach-xxx"
}
```

You can use Terraform configuration concepts like resource `for_each` to apply multiple tags, if necessary.

I will mark this issue as a documentation issue to add some more references to that resource to help future travelers also find it.

**Comment by gchek** [comment]
@bflad Thanks a lot - works perfectly and tags my VPN  attachment.
