### ISSUE TITLE
API Gateway ConflictException: Unable to complete operation due to concurrent modification

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#16439]
Getting error when creating `aws_api_gateway_integration_response`

```
Error: Error creating API Gateway Integration Response: ConflictException: Unable to complete operation due to concurrent modification. Please try again later.
```

Getting error when destroyng `aws_api_gateway_method_response`

```
Error: error deleting API Gateway Method Response (agmr-up2tv87jie-v6cvep-POST-200): ConflictException: Unable to complete operation due to concurrent modification. Please try again later.
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.24
AWS provider 2.61

### Terraform Configuration Files

```
resource "aws_api_gateway_method_response" "this" {
  for_each = local.methods
  rest_api_id = aws_api_gateway_rest_api.this.id
  resource_id = aws_api_gateway_resource.this[each.value.path].id
  http_method = aws_api_gateway_method.this[each.key].http_method
  status_code = "200"
  response_models = {
    "application/json" = "Empty"
  }

  depends_on = [aws_api_gateway_method.this]
}
```

```
resource "aws_api_gateway_integration_response" "this" {
  for_each = local.methods
  rest_api_id = aws_api_gateway_rest_api.this.id
  resource_id = aws_api_gateway_resource.this[each.value.path].id
  http_method = aws_api_gateway_method_response.this[each.key].http_method
  status_code = aws_api_gateway_method_response.this[each.key].status_code

  depends_on = [aws_api_gateway_integration.this]
}
```

**Comment by mimozell** [comment]
I'm seeing a similar issue, but when creating routes:
`Error: error creating API Gateway v2 route: ConflictException: Unable to complete operation due to concurrent modification. Please try again later.`

```
Terraform v0.13.5
provider registry.terraform.io/hashicorp/aws v3.17.0
````

```
resource aws_apigatewayv2_route routes {
  for_each = toset(var.routes)
  api_id = aws_apigatewayv2_api.http.id

  route_key = each.key
  target = "integrations/${aws_apigatewayv2_integration.integration.id}"
}
```

**Comment by Glen-Moonpig** [comment]
Looks like a simple retry could reduce the likelihood of failure.

**Comment by bflad** [comment]
In the upcoming Terraform AWS Provider version 3.24.0 release, any API Gateway REST API (v1) operation that throws the `ConflictException: Unable to complete operation due to concurrent modification. Please try again later.` error will be retried automatically. If you are still having issues after that release, please open a new GitHub issue and we will triage further. Thanks.
