### ISSUE TITLE
Adding CustomEndpoint parameters to aws_elasticsearch_domain

### ISSUE THREAD

**Issue by aryus96** [hashicorp/terraform-provider-aws#16449]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello,
On the AWS Console, the AWS ElasticSearch offers the option to setup an custom domain name.

### New or Affected Resource(s)

* aws_elasticsearch_domain

### Potential Terraform Configuration

[Regarding the AWS documentation ](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-configuration-api.html#es-configuration-api-actions-createelasticsearchdomain)

>  domain_endpoint_options {
>     enforce_https = true
>     tls_security_policy = "Policy-Min-TLS-1-2-2019-07"
>     #"CustomEndpointEnabled": "true|false",
>     #"CustomEndpoint": "www.my-custom-endpoint.com",
>     #"CustomEndpointCertificateArn": "arn:aws:iam::123456789012:certificate/my-certificate"
>   }

**Comment by ewbankkit** [comment]
@aryus96 Thanks for raising this issue.
It has already been noticed in #16059. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
