### ISSUE TITLE
lambda_permission's imported function_name isn't function name but function ARN.

### ISSUE THREAD

**Issue by suzuki-shunsuke** [hashicorp/terraform-provider-aws#16445]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.18.0
```

### Affected Resource(s)

* aws_lambda_permission

### Terraform Configuration Files

```hcl
resource "aws_lambda_permission" "test" {
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

provider "aws" {
  region = "ap-northeast-1"
}
```

Create a Lambda policy without Terraform.

```
$ aws lambda get-policy --function-name test-pr-16436 | jq .Policy -r | jq .
{
  "Version": "2012-10-17",
  "Id": "default",
  "Statement": [
    {
      "Sid": "AWSEvents_test-pr-16436",
      "Effect": "Allow",
      "Principal": {
        "Service": "events.amazonaws.com"
      },
      "Action": "lambda:InvokeFunction",
      "Resource": "arn:aws:lambda:ap-northeast-1:xxx:function:test-pr-16436",
      "Condition": {
        "ArnLike": {
          "AWS:SourceArn": "arn:aws:events:ap-northeast-1:xxx:rule/test-pr-16436"
        }
      }
    }
  ]
}
```

Import a resource `aws_lambda_permission` and check the state.

```
$ terraform import aws_lambda_permission.test test-pr-16436/AWSEvents_test-pr-16436
$ terraform state show aws_lambda_permission.test
```

### Expected Behavior

`function_name` is the Lambda Function's name.

```
$ tf state show aws_lambda_permission.test
# aws_lambda_permission.test:
resource "aws_lambda_permission" "test" {
    action        = "lambda:InvokeFunction"
    function_name = "test-pr-16436"
    id            = "AWSEvents_test-pr-16436"
    principal     = "events.amazonaws.com"
    source_arn    = "arn:aws:events:ap-northeast-1:xxx:rule/test-pr-16436"
    statement_id  = "AWSEvents_test-pr-16436"
}
```

### Actual Behavior

`function_name` is the Lambda Function's ARN.

```
$ tf state show aws_lambda_permission.test
# aws_lambda_permission.test:
resource "aws_lambda_permission" "test" {
    action        = "lambda:InvokeFunction"
    function_name = "arn:aws:lambda:ap-northeast-1:xxx:function:test-pr-16436"
    id            = "AWSEvents_test-pr-16436"
    principal     = "events.amazonaws.com"
    source_arn    = "arn:aws:events:ap-northeast-1:xxx:rule/test-pr-16436"
    statement_id  = "AWSEvents_test-pr-16436"
}
```

### Steps to Reproduce

1. `terraform import aws_lambda_permission.test test-pr-16436/AWSEvents_test-pr-16436`
1. `terraform state show aws_lambda_permission.test`

### References

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_permission#function_name
  * > function_name - (Required) Name of the Lambda function whose resource policy you are updating

**Comment by suzuki-shunsuke** [comment]
This issue would be solved by #16436

**Comment by ewbankkit** [comment]
Related:

* https://github.com/hashicorp/terraform-provider-aws/issues/14661

**Comment by kishaningithub** [comment]
Not stale it has an active PR
