### ISSUE TITLE
r/networkfirewall_logging_configuration: InvalidRequestException - Given logging configuration is temporarily unsupported.

### ISSUE THREAD

**Issue by anGie44** [hashicorp/terraform-provider-aws#16442]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_networkfirewall_logging_configuration

### Terraform Configuration Files

* I've ommitted some non-networkfirewall resources for brevity

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

resource "aws_networkfirewall_firewall_policy" "test" {
  name = %[1]q
  firewall_policy {
    stateless_fragment_default_actions = ["aws:drop"]
    stateless_default_actions          = ["aws:pass"]
  }
}

resource "aws_networkfirewall_firewall" "test" {
  name                = %[1]q
  firewall_policy_arn = aws_networkfirewall_firewall_policy.test.arn
  vpc_id              = aws_vpc.test.id

  subnet_mapping {
    subnet_id = aws_subnet.test.id
  }
}

resource "aws_networkfirewall_logging_configuration" "test" {
  firewall_arn = aws_networkfirewall_firewall.test.arn

  logging_configuration {
    log_destination_config {
      log_destination = {
        logGroup = aws_cloudwatch_log_group.test.name
      }
      log_destination_type = %[2]q
      log_type             = %[3]q
    }
  }
}
```

### Expected Behavior

* Tests should pass

### Actual Behavior

* errors are thrown including:
```
InvalidRequestException: Given logging configuration is temporarily unsupported.
```

### Important Factoids

Given the [API docs](https://docs.aws.amazon.com/network-firewall/latest/developerguide/firewall-logging.html) now specify more restrictions to logging including: 
* Firewall logging is only available for traffic that you forward to the stateful rules engine (configured in a firewall policy)
* records alert logs for traffic that matches stateful rules that have the rule action set to `DROP` or `ALERT`. (configured in a rule group)

it's possible our tests need to be updated (add a stateful `networkfirewall_rule_group` resource and update the policy to reference it in addition to updating the default_actions to be `aws:forward_to_sfe`) to reflect these changes and/or the resource is affected by recent upstream API deployments. Further investigation required.

**Comment by CliffHoogervorst** [comment]
We hit the same issue yesterday. Trying in the console resulted in the same error message. Opened a support ticket and got this answer:
Our internal service team has temporarily removed flow logging based on customer feedback to improve the relevancy of information that is included. We expect to have the feature enabled again soon.

**Comment by anGie44** [comment]
Thanks for the info @CliffHoogervorst ! On our end, we're also waiting to hear from AWS support for an answer regarding errors creating Firewalls in the `us-east-1` and `us-west-2` (where our acceptance tests run) region, since these tests depend on them as well.

**Comment by anGie44** [comment]
Closing as these are now passing in `us-west-2` daily acceptance tests after getting in touch w/AWS support.  Firewall creation/logging configurations are once again supported.
