### ISSUE TITLE
ALB should allow setting the "waf.fail_open.enabled" attribute (and other documented attributes)

### ISSUE THREAD

**Issue by dtreskunov** [hashicorp/terraform-provider-aws#16444]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This load balancer attribute defines what happens when the WAF fails to process the configured rules. By default, the attribute is "false", which means that a problem with the WAF should result in HTTP 500 errors returned from the load balancer [link](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-500-issues).

The following [documented](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#load-balancer-attributes) attributes appear to be unsupported by the Terraform provider:
* `routing.http.desync_mitigation_mode`
* `routing.http.drop_invalid_header_fields.enabled`
* `waf.fail_open.enabled`

### New or Affected Resource(s)

* aws_lb

### Potential Terraform Configuration

```hcl
resource "aws_lb" "test" {
  desync_mitigation_mode: "defensive" # default, other possible values: "monitor", "strictest"
  enable_waf_fail_open: false # default
  enable_drop_invalid_header_fields: false # default
}
```

### References

* [Supported application load balancer attributes](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#load-balancer-attributes)
* [modify-load-balancer-attributes](https://docs.aws.amazon.com/cli/latest/reference/elbv2/modify-load-balancer-attributes.html) AWS CLI command

**Comment by ewbankkit** [comment]
@dtreskunov Thanks for raising this issue.
It has already been noticed in #16372 and #14696. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
