### ISSUE TITLE
aws_default_network_acl documentation default rules are incorrect I think?

### ISSUE THREAD

**Issue by Luminoth** [hashicorp/terraform-provider-aws#16456]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.18.0

### Affected Resource(s)

* aws_default_network_acl documentation

### Issue

I could be mistaken about this, but the AWS documentation here: https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html notes that the default Network ACL ingress CIDR block is 0.0.0.0/0, while the aws_default_network_acl documentation for "Basic Example Usage, with default rules" suggests using this:
```
resource "aws_vpc" "mainvpc" {
  cidr_block = "10.1.0.0/16"
}

[...]
  ingress {
    protocol   = -1
    rule_no    = 100
    action     = "allow"
    cidr_block = aws_vpc.mainvpc.cidr_block
    from_port  = 0
    to_port    = 0
  }
[...]
```

The problem with that example is that it ends up denying all inbound traffic from outside of that block (including inbound load balancer traffic and apparently inbound internet response traffic - my ECS tasks were no longer able to access my registry). If that turns out to be correct, I'm happy to offer a PR if someone could point me where to go about updating it.

**Comment by mattsta** [comment]
Noticed this today too. The actual default rule AWS creates is allow all inbound/outbound, but the example only allows the private VPC IP space as inbound which is kinda not useful.

Correction is just changing `cidr_block = aws_vpc.mainvpc.cidr_block` to `cidr_block = "0.0.0.0/0"`
