### ISSUE TITLE
restore_to_point_in_time conflicts with snapshot_identifier even when is set to empty string

### ISSUE THREAD

**Issue by jamengual** [hashicorp/terraform-provider-aws#16454]
### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.18.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/terraform-providers/mysql v1.9.0
```

### Affected Resource(s)

* aws_rds_cluster

### Terraform Configuration Files

```hcl
resource "aws_rds_cluster" "clone_us_east_2" {
  count                           = var.clone_enabled ? 1 : 0
  cluster_identifier              = "${local.cluster_identifier_us_east_2}-clone"
  vpc_security_group_ids          = local.cluster_security_groups_ids_us_east_2
  db_subnet_group_name            = "${local.cluster_identifier_us_east_2}-clone"
  db_cluster_parameter_group_name = "${local.cluster_identifier_us_east_2}-clone"
  skip_final_snapshot             = true
  snapshot_identifier             = ""
  tags                            = local.complete_tags
  restore_to_point_in_time {
    source_cluster_identifier  = local.cluster_identifier_us_east_2
    restore_type               = "copy-on-write"
    use_latest_restorable_time = true
  }
  provider = aws.us_east_2
}
```

### Debug Output
Sensitive information on output I can't provide complete debug info.

### Expected Behavior

Clone cluster should be created and it should ignore the snapshot_identifier if is empty

### Actual Behavior
```Error: ConflictsWith

  on ../terraform-aws-rds-cluster/main.tf line 47, in resource "aws_rds_cluster" "primary":
  47: resource "aws_rds_cluster" "primary" {

"restore_to_point_in_time": conflicts with snapshot_identifier

Releasing state lock. This may take a few moments...
```
### Steps to Reproduce

1. `terraform plan`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by klang** [comment]
I have wandered into this issue by way of cross-account cloning.

`snapshot_identifier             = ""` can be excluded completely. You can't ask for the snapshot_identifier to be the empty string, but you ARE allowed to not specify it at all.

**Comment by jamengual** [comment]
> I have wandered into this issue by way of cross-account cloning.
> 
> `snapshot_identifier = ""` can be excluded completely. You can't ask for the snapshot_identifier to be the empty string, but you ARE allowed to not specify it at all.

yes, it is possible to not specify it but that does not work when using a module that allows you to use `snapshot_identifier` for other configurations which makes it not DRY since you will have to duplicate a lot of code to make this work due to a bug.

`snapshot_identifier = ""` should not conflict if is empty since empty is the same as not defined.

**Comment by anGie44** [comment]
Hi @jamengual, thank you for raising this issue. While explicitly setting the attribute with an empty string `""` will cause the plan-time error, I believe with terraform 0.12+, setting the value with `snapshot_identifier = null` allows you to bypass that error.  Is this workaround feasible with the module you are working with?

**Comment by jamengual** [comment]
hi @anGie44 using null as the value did get rig of the error.

is this the expected workaround to use or is in fact not a workaround? I have been using "" as value to other arguments and I don't remember having this problem before.
