### ISSUE TITLE
AmazonMQ

### ISSUE THREAD

**Issue by dunnill** [hashicorp/terraform-provider-aws#16458]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add storage option configuration for AmazonMQ AMQ to enable use with EBS or EFS.  This exists in the AWS API but not in Terraform. 

### New or Affected Resource(s)

* aws_mq_broker

### Potential Terraform Configuration

```hcl
terraform "aws_mq_broker" "broker" {
   ...
  storage_arn = aws_efs_file_system.efs.id
  ...
}
```

### References

* https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/broker-storage.html

**Comment by gdepuille** [comment]
Hi, @dunnill I think this is a duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/11325.

**Comment by YakDriver** [comment]
Please see #16108.
