### ISSUE TITLE
Add support for Directory Services Replicated Regions

### ISSUE THREAD

**Issue by tom-henderson** [hashicorp/terraform-provider-aws#16455]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Directory Service directories can be replicated across regions. The first region is considered the primary region. Multi-Region replication is only supported for the Enterprise Edition of AWS Managed Microsoft AD.

The new resource would probably have the same attributes as `aws_directory_service_directory`.

### New or Affected Resource(s)

* `aws_directory_service_replicated_region`

### Potential Terraform Configuration

```hcl
resource "aws_directory_service_directory" "directory" {
  name     = "ad.example.com"
  password = "SuperSecretPassw0rd"
  type     = "MicrosoftAD"
  edition  = "Enterprise"

  vpc_settings {
    vpc_id     = aws_vpc.main.id
    subnet_ids = [aws_subnet.foo.id, aws_subnet.bar.id]
  }
}

resource "aws_directory_service_replicated_region" "additional" {
  directory_id = aws_directory_service_directory.directory.id
  region       = "us-east-1"

  vpc_settings {
    vpc_id     = aws_vpc.alternate.id
    subnet_ids = [aws_subnet.baz.id, aws_subnet.qux.id]
  }
}
```

### References

https://docs.aws.amazon.com/directoryservice/latest/admin-guide/ms_ad_configure_multi_region_replication.html

**Comment by adrienp13** [comment]
@ewbankkit I can see this feature has now been implemented based on your recent activity in tis thread. Can you confirm in which version of the provider will this be made available ? Many thanks in advance.
