### ISSUE TITLE
aws_route53_health_check failure_threshold & request_interval should not be required

### ISSUE THREAD

**Issue by Techbrunch** [hashicorp/terraform-provider-aws#1645]
### Terraform Version

Terraform v0.10.3

### Affected Resource(s)

- aws_route53_health_check

### Terraform Configuration Files

```hcl
resource "aws_route53_health_check" "health_check" {
  fqdn              = "test.com"
  port              = 443
  type              = "HTTPS"
  resource_path     = "/api/health"
  measure_latency   = true

  tags = {
    Origin      = "terraform"
    Environment = "${var.environment}"
  }
}
```

### Debug Output

```
-/+ aws_route53_health_check.health_check_portal (new resource required)
      enable_sni:        "true" => "<computed>"
      failure_threshold: "3" => "0"
      fqdn:              "test.com" => "test.com"
      measure_latency:   "true" => "true"
      port:              "443" => "443"
      request_interval:  "30" => "0" (forces new resource)
      resource_path:     "/api/health" => "/api/health"
      tags.%:            "2" => "2"
      tags.Environment:  "acc" => "acc"
      tags.Origin:       "terraform" => "terraform"
      type:              "HTTPS" => "HTTPS"
```

### Expected Behavior

Apply 2 consecutive time should not change anything.

### Actual Behavior

`request_interval` & `failure_threshold` are changed.

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### Important Factoids

`request_interval` & `failure_threshold` are both required and I did not specify them. If they really need to be specified, I expect the first apply to fail explaining that I am missing required arguments.

I think those arguments should not be required and that the default values should be the same as on the AWS console:

- 3 for `failure_threshold`
- 30 for `request_interval`

**Comment by atz** [comment]
Still seeing the same failure to recognize defaults in `v0.12.12`.  In the body of the `aws_route53_health_check`, instead of **4** lines, I have to have **13**.  Otherwise, terraform thinks there is always an outstanding update to apply.
