### ISSUE TITLE
AWS SSM DoesNotExistException for missing Maintenance Window Target

### ISSUE THREAD

**Issue by kevinscholz** [hashicorp/terraform-provider-aws#16451]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.16.0
```

### Affected Resource(s)

* aws_ssm_maintenance_window_target

### Terraform Configuration Files

```hcl
resource "aws_ssm_maintenance_window" "default" {
  cutoff   = 1
  duration = 3
  name     = "default"
  schedule = "cron(0 0 2 ? * * *)"
}

resource "aws_ssm_maintenance_window_target" "default" {
  window_id     = aws_ssm_maintenance_window.default.id
  name          = "default-target"
  description   = "Default maintenance window target"
  resource_type = "INSTANCE"

  targets {
    key    = "tag:SystemManagement"
    values = ["default"]
  }
}
```

### Panic Output

`Error: DoesNotExistException: Maintenance window mw-XXXX does not exist`

### Expected Behavior

After deleting all resources in our AWS Account via aws-nuke, I'd like to refresh the Terraform state to remove the deleted resources from the state as well. I expect that after running `terraform refresh` my state should be updated.

### Actual Behavior

`terraform refresh` errors with `Error: DoesNotExistException: Maintenance window mw-XXXX does not exist`. This seems to be caused by the `aws_ssm_maintenance_window_target` resource. When I manually remove it from the state via `terraform state rm aws_ssm_maintenance_window.default` and then run the refresh again, everything works fine.

### Steps to Reproduce

1. `terraform apply`
2. Delete the resource via AWS cli, aws-nuke or via the Developer Console.
3. `terraform refresh`

### Important Factoids

Nothing I know of.

### References

Looks similar to the following issues:
* https://github.com/hashicorp/terraform-provider-aws/issues/5412

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 3.20.0 of the Terraform AWS Provider. Thank you to @DrFaust92 for the implementation. 👍
