### ISSUE TITLE
Terraform is unable to read aws credentials from ~/.aws/credential for Ohio region

### ISSUE THREAD

**Issue by msuzoagu** [hashicorp/terraform-provider-aws#16473]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v2.47.0

### Affected Resource(s)

* the provider itself

### Terraform Configuration Files

```hcl
provider "aws" {
  version = "2.47.0"
  region  = var.aws_region
  profile = var.aws_profile
 shared_credentials_file = "~/.aws/credentials"
}

terraform {
  required_version = ">=0.13.5"
  
  backend "s3" {
    bucket         = "bucket-name"
    key            = "module_name/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "dynamodb_name"
    encrypt        = true
  }
}
```

** Note that I am able to use the profile in question if I set it to the default in ~/aws/credentials**
### Debug Output

```
> terraform init

Initializing the backend...

Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.

Please see https://www.terraform.io/docs/backends/types/s3.html
for more information about providing credentials.

Error: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

### Expected Behavior

I expect Terraform to be able to pick up on credentials stored in `~/.aws/credentials` without my having to set the profile being used as the default profile. 

> My default profile is a non-admin profile (doesn't have the same permissions as that given to the IAM profile used to perform terraform actions.

### Actual Behavior

* Create new IAM user with programmatic access
* Add access key and secret to ~/aws/credentials 
* Attempt to use this profile in terraform file (via terraform init)
* Attempt fails. 

### Steps to Reproduce

* Create new IAM user with programmatic access
* Add access key and secret to ~/aws/credentials 
* Plug in values in `variable.tf` or `terraform.tfvars`
* Run `terraform init`

**Note that I am able to use the profile in question if I set it to the default in ~/aws/credentials**

### Important Factoids

**Note that I am able to use the profile in question if I set it to the default in ~/aws/credentials**

### References

* #0000

**Comment by frdvo** [comment]
@msuzoagu I got the same problem with Azurerm backend and S3.

The best solution is to use the Terraform [partial configuration](https://www.terraform.io/docs/backends/config.html#partial-configuration)

You create your provider block with the non-sensitive information in your Terraform project folder and a file containing your keys, for instance`, ../secrets/backend_config.key `outside your repository with the sensitive information

````
access_key = xxxx
secret_key = xxxxx
````

and then you do a `terraform init -backend-config=../secrets/backend_config.key

It will init your project with the credentials and you are not at risk to commit sensitive data to git.

I hope it helps.
