### ISSUE TITLE
Documentation Update for aws_directory_service_directory

### ISSUE THREAD

**Issue by matt-slalom** [hashicorp/terraform-provider-aws#16487]
I previously created a bug report for this but closed it before anyone could triage it. The short version is that the documentation for the aws_directory_service_directory module could use some updates. Specifically, the "Size" parameter is ignored in some cases because the "Edition" parameter defaults to "Enterprise" which has no "Small" option.

Details here:
https://github.com/hashicorp/terraform-provider-aws/issues/15839#issue-729919355

**Comment by abelgvidal** [comment]
I proposed this PR https://github.com/hashicorp/terraform-provider-aws/pull/27266  .
