### ISSUE TITLE
Provider produced inconsistent result after apply: aws_secretsmanager_secret

### ISSUE THREAD

**Issue by mkielar** [hashicorp/terraform-provider-aws#16482]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v0.13.3
- Using hashicorp/tls v3.0.0 from the shared cache directory
- Using hashicorp/random v2.3.1 from the shared cache directory
- Using hashicorp/aws v3.18.0 from the shared cache directory
- Using hashicorp/external v1.2.0 from the shared cache directory
- Using hashicorp/local v1.4.0 from the shared cache directory
- Using hashicorp/null v2.1.2 from the shared cache directory
```

### Affected Resource(s)

* `aws_secretsmanager_secret`

### Terraform Configuration Files

```
locals {
  name = "${var.environment}-${var.name}"
}

resource "aws_secretsmanager_secret" "secret" {

  # Use prefixes to workaround destroy-then-recreate issues.
  name_prefix = "${local.name}-"
  lifecycle {
    create_before_destroy = true
  }

  description             = var.description
  kms_key_id              = var.kms_key_arn
  recovery_window_in_days = var.recovery_window_in_days

  tags = merge(var.tags, {
    "Name"                  = local.name
  })
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The resource should be created.

### Actual Behavior

Creating `aws_secretsmanager_secret` fails with:
```
Error: Provider produced inconsistent result after apply
When applying changes to
module.st_service_template.module.ingress_nlb.aws_secretsmanager_secret.ingress_nlb_ca_certificate_secret[0],
provider "registry.terraform.io/hashicorp/aws" produced an unexpected new
value: Root resource was present, but now absent.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Steps to Reproduce

1. `terraform apply`

### References

There's plenty of those already for other resources. Looks like a generic solution for this would be a good idea.
* https://github.com/hashicorp/terraform/issues/20688
* https://github.com/hashicorp/terraform-provider-aws/issues/14043
* https://github.com/hashicorp/terraform-provider-aws/issues/15084

**Comment by sivamca127** [comment]
I'm also facing the same issue since 2 days onwards during azure resource deployment. can we get fix for this ?

**Comment by david-b8-ncsc** [comment]
Same issue TF 0.12.29
Error: Provider produced inconsistent result after apply 
When applying changes to
aws_secretsmanager_secret.a-secret, provider
"registry.terraform.io/-/aws" produced an unexpected new value for was
present, but now absent.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
