### ISSUE TITLE
Add support for ECS deployment circuit breakers

### ISSUE THREAD

**Issue by tomelliff** [hashicorp/terraform-provider-aws#16499]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has announced ECS deployment circuit breakers that can automatically roll back a failed deployment: https://aws.amazon.com/blogs/containers/announcing-amazon-ecs-deployment-circuit-breaker/

### New or Affected Resource(s)

* aws_ecs_service

### Potential Terraform Configuration

```hcl
resource "aws_ecs_service" "bar" {
  name                = "bar"
  cluster             = aws_ecs_cluster.foo.id
  task_definition     = aws_ecs_task_definition.bar.arn
  scheduling_strategy = "DAEMON"

  deployment_configuration = {
    maximum_percent = 200
    minimum_healthy_percent = 100

    deployment_circuit_breaker = {
      enabled  = true
      rollback = true
    }
  }
}
```

I'm not a massive fan of that API layout and would love it to be as simple as `enable_deployment_circuit_breaker = true` as a top level thing but I think the general pattern here is to have Terraform follow the AWS API and then people can abstract that behind modules if that works for them. That way if the API changes it doesn't cause breaking changes in the provider to support the new functionality.

### References

* https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DeploymentConfiguration.html

**Comment by mkielar** [comment]
I'm considering using this feature in out automated pipelines, and was wondering how will this be implemented in terraform:
1. Would terraform wait for the success/failure/rollback of the service deployment?
2. If rollback is disabled, would `terraform apply` fail if service deployment fails due to circuit breaker?
2. If rollback is enabled, would terraform treat a successful rollback as a success or failure? I.e., would a successful rollback fail `terraform apply`?
3. If rollback is enabled, would terraform update the state after rollback to reflect infrastructure status?

**Comment by zhenglisai** [comment]
when this feature can terraform support?

**Comment by shuheiktgw** [comment]
Let me see if I can implement it. It seems the current aws-sdk-go already supports `DeploymentCircuitBreaker` configuration.

**Comment by shuheiktgw** [comment]
I've implemented it so please upvote the PR for a faster review! 🙏 
https://github.com/hashicorp/terraform-provider-aws/pull/16936

**Comment by anagarjunr** [comment]
waiting for this feature
