### ISSUE TITLE
Accept a custom key store Id as a KMS origin during create key

### ISSUE THREAD

**Issue by ambrosy-eric** [hashicorp/terraform-provider-aws#16491]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently `aws_kms_key` only allows for creating a KMS key with a KMS origin. I would like to use a custom key store to create my keys.

KMS allows you to set a custom key store (often a cloudHSM cluster), and then use this key store to generate KMS keys without having to import key material for them directly.

As a developer I would like to be able to define in terraform an origin of my custom key store through its id.

### New or Affected Resource(s)

* aws_kms_key

New
* data-source aws_kms_custom_store

### Potential Terraform Configuration

```hcl
data "aws_kms_custom_key_store" "key_store" {
  key_store_id = "my-key-store-name"
}

resource "aws_kms_key" "key" {
  description              = "My key for encrypting"
  custom_key_store   = data.aws_kms_custom_key_store.key_store.id
}
```

### References

* https://docs.aws.amazon.com/kms/latest/developerguide/custom-key-store-overview.html
* https://docs.aws.amazon.com/kms/latest/developerguide/create-cmk-keystore.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/kms/#KMS.DescribeCustomKeyStores

**Comment by alexis-renard** [comment]
Hello, we are still heavily waiting for that new feature to come out. Is there any progress on it, any visibility by chance ? We had to deploy a custom API to deal with our Cloud HSM keys efficiently and securly, and would really like to use terraform to handle our HSM Keys in our workflows (therefore decomissioning our use case specific API). 
Thanks !

**Comment by bbratchiv** [comment]
Hi @justinretzolk, when do you plan to release this feature? I see PR is pending above
