### ISSUE TITLE
tests/provider: API Gateway V2 - Mutual TLS Authentication

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#16508]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_apigatewayv2_domain_name

### Debug Output
```console
ACM_CERTIFICATE_ROOT_DOMAIN=<domainname> make testacc TEST=./aws TESTARGS='-run=TestAccAWSAPIGatewayV2DomainName_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAPIGatewayV2DomainName_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayV2DomainName_basic
=== PAUSE TestAccAWSAPIGatewayV2DomainName_basic
=== RUN   TestAccAWSAPIGatewayV2DomainName_disappears
=== PAUSE TestAccAWSAPIGatewayV2DomainName_disappears
=== RUN   TestAccAWSAPIGatewayV2DomainName_Tags
=== PAUSE TestAccAWSAPIGatewayV2DomainName_Tags
=== RUN   TestAccAWSAPIGatewayV2DomainName_UpdateCertificate
=== PAUSE TestAccAWSAPIGatewayV2DomainName_UpdateCertificate
=== RUN   TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication
=== PAUSE TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication
=== CONT  TestAccAWSAPIGatewayV2DomainName_basic
=== CONT  TestAccAWSAPIGatewayV2DomainName_UpdateCertificate
=== CONT  TestAccAWSAPIGatewayV2DomainName_Tags
=== CONT  TestAccAWSAPIGatewayV2DomainName_disappears
=== CONT  TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication
    resource_aws_apigatewayv2_domain_name_test.go:273: Step 1/4 error: Error running pre-apply refresh: 2020/12/01 10:54:22 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0

        Error: no matching Route53Zone found


--- FAIL: TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication (2.30s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_disappears (18.60s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_basic (192.99s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_Tags (371.29s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_UpdateCertificate (446.56s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	448.539s
FAIL
make: *** [testacc] Error 1
```

### Expected Behavior

Test should pass

### Actual Behavior

Test fails

### Steps to Reproduce

1. `ACM_CERTIFICATE_ROOT_DOMAIN=<domainname> make testacc TEST=./aws TESTARGS='-run=TestAccAWSAPIGatewayV2DomainName_`

### References

* #15249

**Comment by ewbankkit** [comment]
@breathingdust Do you remember if this error occurs just in Gov Cloud?

**Comment by ewbankkit** [comment]
If the same root domain name is being shared by the Commercial and GovCloud tests then I don't think you can register the same domain name with Route 53 in seperate accounts or partitions. i.e. you would need a 2nd domain name registered just in GovCloud.

**Comment by breathingdust** [comment]
@ewbankkit Thanks, makes sense, i just checked and our CI does use the same name for testing. We'll need to change that when we pick this one up.
