### ISSUE TITLE
EBS gp3 volume scalable throughput

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#16514]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With the new `gp3` EBS volumes throughput is scalable.

##### Resources

* [`aws_ami`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ami)
* [`aws_ebs_volume`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ebs_volume)
* [`aws_instance`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance)
* ~[`aws_launch_configuration`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_configuration)~ Not (yet?) supported
* [`aws_launch_template`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template)
* [`aws_spot_fleet_request`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/spot_fleet_request)
* [`aws_spot_instance_request`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/spot_instance_request)

##### Data Sources

* [`aws_ami`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami)
* [`aws_ebs_volume`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ebs_volume)
* [`aws_instance`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/instance)
* ~[`aws_launch_configuration`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/launch_configuration)~ Not (yet?) supported
* [`aws_launch_template`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template)

### Potential Terraform Configuration

```hcl
resource "aws_ebs_volume" "example" {
  type       = "gp3"
  throughput = 500
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/12/introducing-new-amazon-ebs-general-purpose-volumes-gp3/).
[User Guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html#gp3-ebs-volume-type).

**Comment by ewbankkit** [comment]
I propose splitting into a number of smaller PRs, once for each resource (and data source if applicable).

* [ ] `aws_ami`
* [ ] `aws_ebs_volume`
* [ ] `aws_instance`
* [ ] `aws_launch_configuration`
* [ ] `aws_launch_template`
* [ ] `aws_spot_fleet_request`
* [ ] `aws_spot_instance_request`

**Comment by lukedd** [comment]
Some of these resources only allow the `iops` option to be set for `io1`/`io2` volume types, eg:
https://github.com/hashicorp/terraform-provider-aws/blob/v3.19.0/aws/resource_aws_instance.go#L1377
These would need to be extended to allow setting `iops` for `gp3` instance types too.  Is that going to be handled here or do we need to file a separate issue?

**Comment by k3ypad** [comment]
I know this was _just_ released, but is there a seperate issue for all the services that use EBS volumes? e.g. RDS and Elasticseach to name a few

**Comment by ewbankkit** [comment]
@k3ypad Other service APIs have not (yet?) been updated to support the `gp3` volume type (e.g. [RDS `CreateDBInstance`](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html)).

**Comment by ewbankkit** [comment]
@lukedd Yes, those validations will be updated to allow `iops` to be specified for `gp3` volumes.

**Comment by mattburgess** [comment]
`aws_emr_cluster` could use this same treatment, but like `aws_launch_configuration` doesn't appear to support the `throughput` parameter at the moment (https://github.com/aws/aws-sdk-go/blob/v1.36.2/service/emr/api.go#L15262-L15278).

**Comment by dimisjim** [comment]
@mattburgess EMR APIs do not support gp3 yet. See https://github.com/aws/aws-sdk/issues/29

**Comment by bflad** [comment]
Support for `gp3` volume type and throughput configuration has been added across various resources and data sources in the Terraform AWS Provider, with `aws_ami*` and `aws_ebs_volume` being released in version 3.25.0 later this week. If there are specific places remaining where the API supports the configuration, but the provider does not, please create new feature requests for specific tracking. 👍

**Comment by vdmkenny** [comment]
This doesn't seem be working yet for launch configurations.
Using terraform 0.14.6 and aws provider 3.27.
```
Error: Error creating launch configuration: ValidationError: gp3 is invalid. Valid volume types are standard, io1, gp2, st1 and sc1.
```

**Comment by dimisjim** [comment]
@vdmkenny 

from a few comments above: https://github.com/hashicorp/terraform-provider-aws/issues/16514#issuecomment-762893090

>If there are specific places remaining where the API supports the configuration, but the provider does not, **please create new feature requests for specific tracking**. +1
