### ISSUE TITLE
aws_ecs_service wait_for_steady_state AWS & provider don't have same definition

### ISSUE THREAD

**Issue by richardgavel** [hashicorp/terraform-provider-aws#16526]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform 0.12.x
aws 3.14.1

### Affected Resource(s)

* aws_ecs_service

### Expected Behaviour

When the ECS service references target groups, the TF resource waits until the healthcheck completes. It is at this point that the ECS events add the "service xxx has reached a steady state" entry.

### Actual Behavior

Once the service is in a running state, the TF resource stops waiting.

### Important Factoids

The behavior does match the definition provided in the documentation (equivalent to wait service-stable). However, calling it "wait_for_steady_state" is a misnomer since the target group(s) need to be healthy to get the matching event in ECS.

I don't know if there is a single method in the SDK that covers it all, but worse case is you could wait until service stable AND all target groups are healthy.

* #0000

**Comment by RichardHarperInfinityWorks** [comment]
This error is in provider v3.20.0 also and cannot be resolved by setting the wait_for_steady_state property within the resource.

```
Error: Provider produced inconsistent final plan

When expanding the plan for aws_ecs_service.main["mi-data-service"] to include
new values learned so far during apply, provider "registry.terraform.io/-/aws"
produced an invalid new value for .wait_for_steady_state: was cty.False, but
now null.
```

**Comment by richardgavel** [comment]
@RichardHarperInfinityWorks Is your issue intermittent and only happens on a create? Because this is a common issue across the AWS provider in areas that are eventually consistent in AWS (provider does a create, but do to eventual consistency, the immediate follow up get results in a 404 on the resource).

**Comment by RichardHarperInfinityWorks** [comment]
This is only on a provider bump up where the resource expects and update in this case because the properties are defaulted in TF state where they weren't before. In this occasion it happened 100% of the time not intermittent.

**Comment by artburkart** [comment]
I'm seeing the same thing.

**Comment by richardgavel** [comment]
This is not about eventual consistency. Again, my point is that for ECS to consider it "reached a steady state" requires 2 conditions when attaching the containers to a load balancer based on the logs you can see in ECS:

- services stable AND
- targets groups healthy

If the property was called "wait_for_services_stable" then the definition would be consistent with AWS's own definition. But referring to "steady state" is not consistent.

**Comment by Botono** [comment]
Is there a workaround for the `aws_ecs_service` inconsistent plan error that @RichardHarperInfinityWorks wrote about? I am receiving the same error after upgrading to v3.25 from v2.70. Setting the `wait_for_steady_state` in the resource does not correct the problem. I am also not have any luck reverting back to provider v2.70.

**Comment by zarakay** [comment]
I took ran into this problem when going to v3.25 to v2.70 on TF 0.12.x. Couldn't figure out a solution, so I managed to downgrade to 3.12 which was the release before `wait_for_steady_state`. I did have to do some `state rm` shenanigans to make it work, there were some modules which seem to be stuck on a new provider schema.  

Hope this helps

**Comment by naysayer** [comment]
My org was running into this issue.

We are on terraform v0.12.28 - the issue seemed to also be related to terraform pulling in a new version of the AWS provider that produces this breaking change. Per the docs, if a version of the provider is not specified it will automatically pull in the latest version. We set the version of the aws provider using the what is below. We downgraded to this version specifically as it was the last version we preformed a successful deployment with. 

```
terraform {
  required_providers {
    aws = "~> 3.11.0"
  }
}
```

Here is a link to the documentation:
[https://www.terraform.io/docs/language/providers/requirements.html](https://www.terraform.io/docs/language/providers/requirements.html)

**Comment by yadmitri** [comment]
As workaround for terraform v0.12.30 and aws 3.25.0 i use:
```
lifecycle {
    ignore_changes = [wait_for_steady_state] 
}
```

**Comment by AlexisJackson** [comment]
Are there any updates on this issue? Our org started randomly having this error occur seven days ago after weeks of no issues. 

TF version: 0.12.31
AWS version: 3.47.0

**Comment by dstanfieldom** [comment]
I encountered the `wait_for_steady_state` issue when upgrading the aws provider from 2.68.0 to 3.64.0.

My workaround:

While manually setting `wait_for_steady_state = false` in the aws_ecs_service resource definition exhibited the same problem, setting `wait_for_steady_state = true` allowed a successful apply.  Removing the `wait_for_steady_state = true` afterward and reapplying correctly set it to false without the error
