### ISSUE TITLE
Support Managing EKS Cluster Add-Ons

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#16542]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Announced at re:Invent 2020:

> Amazon Elastic Kubernetes Service (Amazon EKS) now allows you to install and manage Kubernetes operational software (add-ons) as part of the Amazon EKS console, CLI, and API. Today, EKS supports managing the Amazon VPC CNI networking plugin, with more add-ons coming soon.

This is for supporting the management of an add-on itself.

### New Resource

* aws_eks_addon

### Potential Terraform Configuration

```hcl
resource "aws_eks_addon" "example" {
  addon_name = ""
  addon_version = ""
  cluster_name = aws_eks_cluster.example.name
  resolve_conflicts = ""
  service_account_role_arn = ""
  tags = {}
}
```

### References

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-eks-simplifies-installation-and-management-for-kubernetes-culster-add-ons/)
* [User Guide](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html#update-cluster-add-ons)
* [API Reference](https://docs.aws.amazon.com/eks/latest/APIReference/Welcome.html)
* [AWS Go SDK Service Reference](https://docs.aws.amazon.com/sdk-for-go/api/service/eks/)

**Comment by shuheiktgw** [comment]
Let me see if I can implement it!

**Comment by juozasget** [comment]
Hey @shuheiktgw, I already have some working code, but no acceptance tests yet. Maybe you'd like to collaborate on this?

**Comment by shuheiktgw** [comment]
@juozasget Thank you, but then I'll check other issues so please add ACCs and finish up the PR! If you need any help please let me know! 👍

**Comment by juozasget** [comment]
Thanks! Working on it!

**Comment by juozasget** [comment]
I'll just mention it here - in case the issue has more visibility. ACC test are added and I think the PR is in good shape for a review. Maybe someone could have a look? :)

**Comment by DonBower** [comment]
So it looks like the tactic here is to add a separate resource for add-ons as opposed to adding a configuration block.
We still may want to look at the configuration block idea that I suggested in #17440, now closed.
It's a bit like EC2 Security Group Rules.  They can exist in both the **aws_security_group** resource as a **egress** and **ingress** blocks, or as separate resources, **aws_security_group_rule** 

In any case, is there an ETA on the new resource?

**Comment by NeckBeardPrince** [comment]
Any chance for a review soon?

**Comment by billinghamj** [comment]
Current PR is #16972 I believe

**Comment by williamcodes** [comment]
Who is in charge of code reviews? Looks like the PR has been open for forever.
