### ISSUE TITLE
capacity_type introduced on aws_eks_node_group is forcing recreation in v3.19.0

### ISSUE THREAD

**Issue by samcday** [hashicorp/terraform-provider-aws#16547]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider

Terraform 0.12.x
AWS provider v3.19.0

### Affected Resource(s)

* aws_eks_node_group

### Terraform Configuration Files

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/node_groups/node_groups.tf#L1

### Plan Output

```
  # module.eks.module.node_groups.aws_eks_node_group.workers["node-group-3"] must be replaced
+/- resource "aws_eks_node_group" "workers" {
      ~ ami_type        = "AL2_x86_64" -> (known after apply)
      ~ arn             = "<REDACTED>" -> (known after apply)
      + capacity_type   = "ON_DEMAND" # forces replacement
        cluster_name    = "<REDACTED>"
        disk_size       = 120
        <SNIP>
    }
```

### Expected Behavior

Upgrading to terraform-provider-aws v3.19.0, which is a minor semver change, should not cause existing `aws_eks_node_group` should not cause existing resources to be replaced.

### Actual Behavior

Existing node groups are being forced to recreate.

### Steps to Reproduce

1. Deploy an `aws_eks_node_group` with terraform-provider-aws v3.18.0
2. Update terraform-provider-aws to v3.19.0
3. `terraform plan`

### References

https://github.com/hashicorp/terraform-provider-aws/compare/v3.18.0...v3.19.0#diff-fbadf1462da63413e1e824058fc520a1711c7a8c0ec3a27266fc51adb96e94c4R50

**Comment by langesven** [comment]
@anGie44 replying here from the linked [PR comment](https://github.com/hashicorp/terraform-provider-aws/pull/16510#issuecomment-737246909) I made.

Yes we're also upgrading from using 3.18.0 to now 3.19.0
We're in eu-central-1 if that makes a difference, because you mentioned regions
If there's anything else I can supply that could help you let me know.
As mentioned modifying the state surprisingly did not convince terraform to not want to do the replacement even though the bit it wants to add was pushed into the state manually by me

**Comment by anGie44** [comment]
Hi @samcday @langesven , thank you for raising this issue. the team has reached out to the AWS EKS service team to confirm the API expectations for pre-existing node groups and once we hear back, we'll comment back here with updates.

**Comment by anGie44** [comment]
Hi all, we've been notified from the EKS service team the new field only applies to new node groups so we'll move forward with removing drift detection from that field unless explicitly configured.
