### ISSUE TITLE
Windows FSx DNS alias support 

### ISSUE THREAD

**Issue by akfroman** [hashicorp/terraform-provider-aws#16548]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS recently added support for DNS aliases for Windows FSx systems. Please add this as an available attribute in in the aws_fsx_windows_file_system resource.

https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-fsx-windows-file-server-supports-access-file-systems-alternate-dns-names/

### New or Affected Resource(s)

* aws_fsx_windows_file_system 

### Potential Terraform Configuration

```hcl
resource "aws_fsx_windows_file_system" "example" {
  active_directory_id = aws_directory_service_directory.example.id
  kms_key_id          = aws_kms_key.example.arn
  storage_capacity    = 300
  subnet_ids          = [aws_subnet.example.id]
  throughput_capacity = 1024

  dns_alias = ["fsx.domain.local"]
}
```

### References

* #0000

**Comment by jeremyciak** [comment]
Is it possible to get some attention on this issue and [the corresponding PR](https://github.com/hashicorp/terraform-provider-aws/pull/16683)? The PR was submitted almost 4 months ago and hopefully a review can get this feature support in place.

**Comment by aserakhi** [comment]
Hello 

We really need this to our production envrionement 
https://github.com/hashicorp/terraform-provider-aws/pull/16683
