### ISSUE TITLE
aws_apigatewayv2_api: ignore_changes considers only the first changed attribute from the list

### ISSUE THREAD

**Issue by vatima2016** [hashicorp/terraform-provider-aws#16553]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.0-rc1
+ provider registry.terraform.io/hashicorp/aws v3.18.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* aws_apigatewayv2_api

### Terraform Configuration Files

```hcl
resource "aws_apigatewayv2_api" "my_api" {
  version = "1.0.0"
  name          = "my_api"
  description   = ""
  body          = data.template_file.my_openapi.rendered
  protocol_type = "HTTP"
  target = var.my_lambda_arn

  cors_configuration {}

  tags = {}

  lifecycle {
    ignore_changes = [ body, cors_configuration, tags ]
    create_before_destroy = true
  }
```

### Expected Behavior

The API definition, including **_cors_configuration_**  and **_tags_**, is specified in the Open API file. 
So changes caused by the re-import of the Open API definition should be ignored by Terraform.
```hcl
ignore_changes = [ body, cors_configuration, tags ]
```
### Actual Behavior

Only the first changed attribute from the **_ignore_changes_** list is considered. This behavior has been observed when changing the order of the changed attributes to be ignored.

The workaround for the moment is to keep API definition (**_cors_configuration_**  and **_tags_**) on both places in Terraform template and OpenAPI file in sync :-(

Although the documentation for **aws_apigatewayv2_api** states that _"If the body argument is provided, the OpenAPI specification will be used to configure the integrations and route for the HTTP API.  ... Further more, the name, description, cors_configuration, tags and version fields should be specified in the Terraform configuration and the values will override any values specified in the OpenAPI document."_, we find this behavior inconsistent and expect rather one source of the truth and namely the Open API file.

### Steps to Reproduce

1. `terraform apply`
1. Change some data in **_cors_configuration_**  and **_tags_** attributes only in the Terraform template end not in the Open API definition file
1. `terraform apply`

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_api#cors_configuration
```
Note: If the body argument is provided, the OpenAPI specification will be used to configure the integrations and route for the HTTP API. 
...
Further more, the name, description, cors_configuration, tags and version fields should be specified in the Terraform configuration and the values will override any values specified in the OpenAPI document.
```

**Comment by ewbankkit** [comment]
@vatima2016 Thanks for raising this issue.
I think what _may_ be happening here is that because changes to the `body` attribute are being ignored, any changes made to the OpenAPI spec that are in the rendered body will be ignored.
What happens if you remove **body** from the `ignore_changes` list (leaving just **cors_configuration** and **tags**)?

**Comment by ewbankkit** [comment]
@vatima2016 Did upgrading to Terraform v0.14.2 resolve the problem?

Converting those attributes to `Computed` (so that not specifying no value in the Terraform configuration means no drift detection is done) is problematic as it will cause backwards compatibility issues and confusion.

For example, changing

```hcl
resource "aws_apigatewayv2_api" "example" {
  description = "An example API"
}
```

to

```hcl
resource "aws_apigatewayv2_api" "example" {
  # No description.
}
```

will currently remove the API's description, but changing `description` to `Computed` would mean that the API's description would be unchanged (and could be unset by specifying `description = ""`).
If we were to do this we would have to declare a breaking change and wait for a major version upgrade.

**Comment by vatima2016** [comment]
@ewbankkit 

> I think what _may_ be happening here is that because changes to the `body` attribute are being ignored, any changes made to the OpenAPI spec that are in the rendered body will be ignored.
> What happens if you remove **body** from the `ignore_changes` list (leaving just **cors_configuration** and **tags**)?
> 
The first attribute from the `ignore_changes` list is actually handled properly, the rest is ignored.
Thus if I remove (or move) **body** from the 1st position, the new 1st attribute is handled properly.

**Comment by vatima2016** [comment]
@ewbankkit
>  Did upgrading to Terraform v0.14.2 resolve the problem?

Yes :-)

> Converting those attributes to `Computed` (so that not specifying no value in the Terraform configuration means no drift detection is done) 
...
> will currently remove the API's description, but changing `description` to `Computed` would mean that the API's description would be unchanged (and could be unset by specifying `description = ""`).

I agree that this would be the right solution to keep things consistent in case if the `body` attribute is provided 

> If we were to do this we would have to declare a breaking change and wait for a major version upgrade.

As long as there is a workaround thanks to the `ignore_changes` list functioning properly, we have time ;-)

Thank you very much for your great support!
