### ISSUE TITLE
Transfer server cannot transition from public to an external VPC endpoint

### ISSUE THREAD

**Issue by hh-nharward** [hashicorp/terraform-provider-aws#16556]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

    Terraform v0.13.5
    provider[registry.terraform.io/hashicorp/aws] 3.13.*, 3.13.*, 3.13.*

### Affected Resource(s)

* `aws_transfer_server`

### Terraform Configuration Files

```hcl
resource "aws_transfer_server" "my_transfer_server" {
  identity_provider_type = "SERVICE_MANAGED"
+   endpoint_type          = "VPC"
+   endpoint_details {
+     subnet_ids             = xxx
+     vpc_id                 = xxx
+     address_allocation_ids = [xxx]
+   }
}
```

### Debug Output

Apologies as I do not have this available to report.

### Panic Output

Apologies again, not available to report.

### Expected Behavior

The transfer service should use the specified [external] VPC.

### Actual Behavior

Apply failed with _cannot add Address Allocation ID's at that time_.

### Steps to Reproduce

1. Create public endpoint AWS Transfer Family Instance.
2. Create VPC infrastructure for VPC type transfer family.
3. Change endpoint type to VPC, passing in the three necessary fields: VPC ID, Subnet IDs, Address Allocation IDs (see `+` lines above in the configuration file example)

### Important Factoids

Workaround: removing the Address Allocation ID's allows an apply to work, but creates an internal resource instead of external. Adding them back after this apply correctly creates the external type and associates the IP Address.

**Comment by ewbankkit** [comment]
@hh-nharward Thanks for raising this issue.
Whilst looking at merging #13371 I have been taking an in-depth look at this code and think I see the bug (we are not clearing the `AddressAllocationIds` specified for the `UpdateServer` call). I will address this as part of the merge.
