### ISSUE TITLE
aws_fsx_windows_file_system import fails to read security groups

### ISSUE THREAD

**Issue by dthvt** [hashicorp/terraform-provider-aws#16550]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

$ terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/-/aws v3.19.0
+ provider registry.terraform.io/-/vault v2.16.0
+ provider registry.terraform.io/hashicorp/aws v3.18.0
+ provider registry.terraform.io/hashicorp/vault v2.16.0

### Affected Resource(s)

* aws_fsx_windows_file_system

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

When importing an FSx file system, terraform should populate the security_group_ids list in the state file.

### Actual Behavior

The security_group_ids list does not get populated, which then triggers a recreation on the next apply.

### Steps to Reproduce

1. `terraform import aws_fsx_windows_file_system <existing id>`
1. `terraform plan`

### Important Factoids

I'm guessing/assuming this is because the security groups are not exposed by the DescribeFileSystem API.  They need to be scrapped from the ENIs exposed under the NetworkInterfaceIds list.

### References

* https://docs.aws.amazon.com/fsx/latest/APIReference/API_DescribeFileSystems.html
* https://docs.aws.amazon.com/fsx/latest/APIReference/API_CreateFileSystem.html

**Comment by dthvt** [comment]
As a work around, you can manually edit the state file to set the security groups which will avoid the recreation.

**Comment by DrFaust92** [comment]
As you specified the `DescribeFileSystem` api does not return sg information, to avoid extraneous changes to the resource post import an `ignore_changes` block will prevent this similar to some other cases this pops up. 
an addition to documentation can be helpful similarly to https://github.com/hashicorp/terraform-provider-aws/pull/14878.

**Comment by dthvt** [comment]
Strictly speaking, I suspect it would be possible to perform drift detection and correction by fixing the SGs on the ENIs.  But I haven't looked into it.  The ignore_changes suggestion is a good one as well, although I try to avoid it when possible to maximize our ability to detect drift.

**Comment by DrFaust92** [comment]
Hi @dthvt, the main issue with that is cross service operation on the fsx resource level which is something to be avoided for several reasons. it can cause confusion related to permissions needed for other service (in this case ec2) to perform actions on the fsx resource. second as the FSX api doesnt return this info at the moment retrieving from other sources may not reflect the way FSx handles this under the hood and when the day comes and the API does return this information in may cause a breaking change on the provider level. so there may be a lot of considerations (like preventing API breaking in the future) to keep this as is.

the best course of action IMO is to reach out to AWS and ask them to amend the API to return the correct info and catch drift detection then.

**Comment by dthvt** [comment]
@DrFaust92 I will open a support ticket w/ a feature request.  Thanks.

**Comment by dthvt** [comment]
Follow-up from AWS Support:

> Thank you for your patience while awaiting a response from Service team. I am happy to inform you that the feature request has been approved to add security group information in describe-file-systems API output.
>
> Unfortunately, I do not have an ETA as to when the feature request would be implemented and publically available.
