### ISSUE TITLE
Support AWS Batch retry strategies

### ISSUE THREAD

**Issue by hectcastro** [hashicorp/terraform-provider-aws#16574]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Batch now has support for custom retry functionality based on job failure types (e.g., container image pull failure, underlying EC2 host failure, etc.). This support has been incorporated into the existing `RetryStrategy` API component.

### New or Affected Resource(s)

* `aws_batch_job_definition`

### Potential Terraform Configuration

```hcl
resource "aws_batch_job_definition" "test" {
  name = "tf_test_batch_job_definition"
  type = "container"

  container_properties = <<CONTAINER_PROPERTIES
{
    "command": ["ls", "-la"],
    "image": "busybox",
    "memory": 1024,
    "vcpus": 1,
    "volumes": [
      {
        "host": {
          "sourcePath": "/tmp"
        },
        "name": "tmp"
      }
    ],
    "environment": [
        {"name": "VARNAME", "value": "VARVAL"}
    ],
    "mountPoints": [
        {
          "sourceVolume": "tmp",
          "containerPath": "/tmp",
          "readOnly": false
        }
    ],
    "ulimits": [
      {
        "hardLimit": 1024,
        "name": "nofile",
        "softLimit": 1024
      }
    ]
}
CONTAINER_PROPERTIES

  retry_strategy = {
    attempts = 3

    evaluate_on_exit = {
      action = "RETRY"
      on_status_reason = "Host EC2*"
    }

    evaluate_on_exit = {
      action = "EXIT"
      on_reason = "*"
    }
  }
}
```

### References

* https://aws.amazon.com/blogs/compute/introducing-retry-strategies-for-aws-batch/
* https://docs.aws.amazon.com/batch/latest/APIReference/API_EvaluateOnExit.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/batch/#EvaluateOnExit

**Comment by tomreposify** [comment]
any new on this?
