### ISSUE TITLE
Clarify Documentation for config_configuration_recorder 

### ISSUE THREAD

**Issue by sukoneck** [hashicorp/terraform-provider-aws#16575]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There are 3 optional arguments within the [recording_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_configuration_recorder#recording_group) argument of the [config_configuration_recorder](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_configuration_recorder) resource. To successfully use the [resource_types](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_configuration_recorder#resource_types) argument, you must set [all_supported](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_configuration_recorder#all_supported) to `false`; however, the documentation for [all_supported](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_configuration_recorder#all_supported) says: 

> Conflicts with `resource_types`.

It would be nice if the documentation clarified that `all_supported = false` is required when using `resource_types`.

### New or Affected Resource(s)

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_configuration_recorder
https://docs.aws.amazon.com/config/latest/APIReference/API_ResourceIdentifier.html#config-Type-ResourceIdentifier-resourceType

### Potential Terraform Configuration

```hcl
resource "aws_config_configuration_recorder" "foo" {
  name     = "example"
  role_arn = aws_iam_role.r.arn
  recording_group {
    all_supported  = false
    resource_types = [ "AWS::IAM::User" ]
  }
}
```

### References

* Found this from [Josh Baird's comment here](https://gitter.im/hashicorp-terraform/Lobby?at=5d9b85897aa5602ffc873d3a).

**Comment by gunadhya** [comment]
Hi, I'd like to work on this issue.

**Comment by gunadhya** [comment]
I was thinking of adding this line  (Set `all_supported = false` is required to use this argument) in the resource_types section over [here](https://github.com/hashicorp/terraform-provider-aws/blob/master/website/docs/r/config_configuration_recorder.html.markdown#recording_group). What do you think?

**Comment by sukoneck** [comment]
Seems like that would cover it.
