### ISSUE TITLE
MSK cluster recreation problem when KMS key changes

### ISSUE THREAD

**Issue by TanmayaA** [hashicorp/terraform-provider-aws#16579]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```bash
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/archive v2.0.0
+ provider registry.terraform.io/hashicorp/aws v3.13.0
+ provider registry.terraform.io/hashicorp/helm v1.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/mongey/kafka v0.2.10
```

### Affected Resource(s)

* aws_msk_cluster

### Terraform Configuration Files

```hcl
resource "aws_msk_cluster" "kafka" {
  depends_on             = [aws_msk_configuration.msk_configuration]
  cluster_name           = local.name_prefix
  kafka_version          = "2.4.1.1"
  number_of_broker_nodes = 3

  broker_node_group_info {
    instance_type   = var.msk_instance_type
    ebs_volume_size = var.msk_instance_storage_size
    client_subnets  = var.vpc_private_subnets
    security_groups = [aws_security_group.msk_access.id]
  }

  configuration_info {
    arn      = aws_msk_configuration.msk_configuration.arn
    revision = aws_msk_configuration.msk_configuration.latest_revision
  }

  encryption_info {
    encryption_at_rest_kms_key_arn = var.kms_key_arn
  }
}

```

### Debug Output
https://gist.github.com/TanmayaA/36f5628d88bf72645ddc9f589e2566a6

### Panic Output

N/A

### Expected Behavior

Terraform should have just recreated the resource

### Actual Behavior

It exited with error as seen in the gist https://gist.github.com/TanmayaA/36f5628d88bf72645ddc9f589e2566a6
On retrying, it rather complains that the server with same name already exists

### Steps to Reproduce

1. Change the KMS key
2. `terraform apply`

### References

* #0000

**Comment by breathingdust** [comment]
Hi @TanmayaA 👋  The AWS API does not allow a KMS key to be changed for an existing cluster, so we are currently unable to support this:

https://docs.aws.amazon.com/msk/1.0/apireference/clusters-clusterarn-configuration.html
