### ISSUE TITLE
aws_lex_bot Unable to update intent version based on slot type dependency

### ISSUE THREAD

**Issue by zach-anthony** [hashicorp/terraform-provider-aws#16584]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

- Terraform Version 12.23
- AWS Provider Version 3.20.0

### Affected Resource(s)

- aws_lex_intent

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

intent.tf
```hcl
resource "aws_lex_intent" "example_a" {
  name                 = "${local.prefix}_ExampleA"
  create_version       = true

...

slot {
    name        = "slot_a"
    priority    = 1

    slot_constraint   = "Required"
    slot_type         = aws_lex_slot_type.slot_a.name
    slot_type_version = aws_lex_slot_type.slot_a.version

    value_elicitation_prompt {
      max_attempts = 2
      message {
        content      = "optional"
        content_type = "PlainText"
      }
    }
  }
```

slot_type.tf
```hcl
resource "aws_lex_slot_type" "slot_a" {
  description              = "Slot A"
  name                     = "${local.prefix}_SlotA"
  value_selection_strategy = "ORIGINAL_VALUE"
  create_version   = true

enumeration_value {
    value = "test"
  }
```

### Expected Behavior

When updating the enumeration value for the Slot Type:
- A new version of the Slot Type should be created
- A new version of the Intent which depends on the Slot Type should be created, referring to the new version of the Slot Type
- A new version of the Bot which depends on the Intent should be created, referring to the new version of the Intent

### Actual Behavior

When updating the enumeration value for the Slot Type:
- A new version of the Slot Type is created
- A new version of the Intent is not created, the existing version of the Intent refers to the previous version of the Slot Type
- A new version of the Bot is created but refers to the 'existing' version of the Intent

### Steps to Reproduce

1. `terraform apply`

**Comment by nashvan** [comment]
Any update on this issue? this is really a show stopper for the Lex bot with terraform. 
@jzbruno perhaps you would be able to provide some help on fixing this issue?

**Comment by jzbruno** [comment]
@nashvan Really sorry for the slow response. Unfortunately, I don't think I have time to look into this. From a quick look, I didn't see an obvious reason for this.

For anyone that may look into it.

1. Would check if terraform apply is showing a change to the intent, is the resource dependency being captured correctly.
2. Slot type version is a nested field in the intent, would check if it is being sent on to the AWS API correctly.
3. Is the AWS API call correct and the API isn't updating it?
4. Is there possibly a race condition, the call to get the latest version is still showing the old version?

From the source side I would check if the slot type version change is actually being seen by the intent, next would check that the intent dependency is correct between slot type and intent
