### ISSUE TITLE
General tags

### ISSUE THREAD

**Issue by T00mm** [hashicorp/terraform-provider-aws#16588]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A way to provide global tags to all resources which support it. The resources themselves can override a global tag in their own config block.

### New or Affected Resource(s)

* All resources that have a tagging block

### Potential Terraform Configuration

```hcl
provider "aws" {
    region = "eu-west-1"
    version = "~> 3.3.0"
    global_tags = {
        Automation = "Terraform"
        CostCenter = "ProjectX"
    }
}

resource "aws_dynamodb_table" "other_project" {
  tags = {
      CostCenter = "YProjectY"  // Overrides ProjectX GlobalTag
  }
}
```

**Comment by bflad** [comment]
Hi @T00mm 👋  Thank you for submitting this. We have a previous issue that is tracking this feature request: https://github.com/hashicorp/terraform-provider-aws/issues/7926

Please feel free to 👍  react and subscribe there for updates. To consolidate efforts and discussions, I'm going to close this issue in preference of the existing one.
