### ISSUE TITLE
Support AWS Batch Fargate compute environments

### ISSUE THREAD

**Issue by mrosales** [hashicorp/terraform-provider-aws#16592]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Batch now supports using Fargate or Fargate Spot as compute environments instead of a traditional EC2/Spot environment.

### New or Affected Resource(s)

* `aws_batch_compute_environment`
* `aws_batch_job_definition` (`ExecutionRoleArn` parameter becomes required)

### Potential Terraform Configuration

```hcl
resource "aws_batch_compute_environment" "sample" {
  compute_environment_name = "sample"

  compute_resources {
    max_vcpus = 16

    security_group_ids = [
      aws_security_group.sample.id,
    ]

    subnets = [
      aws_subnet.sample.id,
    ]

    type = "FARGATE|FARGATE_SPOT"
  }

  service_role = aws_iam_role.aws_batch_service_role.arn
  type         = "MANAGED"
  depends_on   = [aws_iam_role_policy_attachment.aws_batch_service_role]
}
```

### References

* https://aws.amazon.com/blogs/aws/new-fully-serverless-batch-computing-with-aws-batch-support-for-aws-fargate/
* https://docs.aws.amazon.com/batch/latest/APIReference/API_ComputeResource.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-computeenvironment-computeresources.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/batch/#ComputeResource

**Comment by gmazelier** [comment]
Need to update job definition too, to support platform capabilities (covered in another pull request):
https://docs.aws.amazon.com/batch/latest/APIReference/API_JobDefinition.html

**Comment by gmazelier** [comment]
The two pull requests above should resolve this issue.

**Comment by tabvn** [comment]
i got same issue, it should have more option like: FARGATE 

The type of compute environment: EC2 , SPOT , FARGATE , or FARGATE_SPOT . For more information, see Compute Environments in the AWS Batch User Guide .

**Comment by dmccaffery** [comment]
Anything left to do to see this make its way into the next release? We're really looking forward to it. Happy to lend a hand if there is outstanding blockers.

**Comment by grinszju** [comment]
Hi,

for the moment you can still use a "aws_cloudformation_stack" to manage the aws batch fargate component...

Regards,

**Comment by hbakkum-dotstar** [comment]
We are also looking forward to getting this change. Is it going to make the next release?

**Comment by nbzn** [comment]
Me too, Please include next release...

**Comment by domhdp** [comment]
We are also looking forward to this, we need it in a terraform way. (I just tried with the "aws_cloudformation_stack" and it was hell.)

**Comment by AndyMakings** [comment]
Any ETA for this, please?

**Comment by itsx** [comment]
Hi @gmazelier , we are also waiting for this feature and your PR looks awesome!

Hi @DrFaust92 , thank you for Terraform at the first place.
This PR looks quite ready and we are wondering, when it could make its way to the release
(also #16850 looks quite ready, if I can say).

We will definitely use this, thanks for the work :thumbsup:
