### ISSUE TITLE
Error: Invalid or unknown key in resource "aws_ecs_service" "service"

### ISSUE THREAD

**Issue by nperry** [hashicorp/terraform-provider-aws#16590]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.0
provider registry.terraform.io/hashicorp/aws v3.20.0

### Affected Resource(s)

* aws_ecs_service

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ecs_service" "service" {
  lifecycle {
    ignore_changes  = all
    prevent_destroy = true
  }
  depends_on                         = [aws_lb_listener_rule.listener_rule_prod, aws_lb_listener_rule.listener_rule_test]
  name                               = var.service_name
  cluster                            = var.cluster_id
  desired_count                      = var.desired_count
  deployment_maximum_percent         = 200
  deployment_minimum_healthy_percent = 100
  enable_ecs_managed_tags            = true
  propagate_tags                     = "SERVICE"
  health_check_grace_period_seconds  = 240
  launch_type                        = "FARGATE"
  network_configuration {
    subnets          = var.subnet_ids
    assign_public_ip = false
    security_groups  = var.security_group_ids
  }
  deployment_controller {
    type = "CODE_DEPLOY"
  }
  load_balancer {
    target_group_arn = aws_lb_target_group.target_group[0].arn
    container_name   = var.service_name
    container_port   = 8080
  }
  task_definition = var.task_definition
  tags            = var.default_tags
}

```

### Expected Behavior

No error

### Actual Behavior

```
Error: Invalid or unknown key

  on modules/deployable_service/main.tf line 81, in resource "aws_ecs_service" "service":
  81: resource "aws_ecs_service" "service" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Was working OK on 0.13.x/3.5.0.

**Comment by bflad** [comment]
Hi @nperry 👋  Quick question: does this configuration work if you temporarily remove `ignore_changes = all`?

**Comment by nperry** [comment]
Hey @bflad 

Just given it a go and yes it does, however we have found that this was the best as we are using code deploy to deploy to the service that the module creates.

**Comment by bflad** [comment]
This is going to be a case that requires fixing in the Terraform CLI codebase, since the `lifecycle` block handling is outside anything we can control in the Terraform AWS Provider codebase. My best suggestion is to add this use case to this upstream Terraform CLI issue (https://github.com/hashicorp/terraform/issues/27106). 👍  If you know of specific attributes to ignore, rather than using `all`, [that may be workaround](https://github.com/hashicorp/terraform/issues/27106#issuecomment-737988347).
