### ISSUE TITLE
ECS Deployment Circuit Breaker

### ISSUE THREAD

**Issue by carlochess** [hashicorp/terraform-provider-aws#16601]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS ECS now supports using Circuit Breaker for Fargate deployments. With this feature, Amazon ECS customers can now automatically roll back unhealthy service deployments without the need for manual intervention. This empowers customers to quickly discover failed deployments, without worrying about resources being consumed for failing tasks, or indefinite deployment delays.

### New or Affected Resource(s)

* aws_ecs_service

### Potential Terraform Configuration

```hcl
resource "aws_ecs_service" "example" {
  name    = "example"
  cluster = aws_ecs_cluster.example.id

  deployment_configuration {
    deployment_circuit_breaker {
       enable=true
       rollback=true
    }
    maximum_percent = 100
    minimum_healthy_percent = 100
  }

  deployment_controller {
    type = "ECS"
  }
}
```

### References

* https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-type-ecs.html

**Comment by danieladams456** [comment]
Duplicate of #16499?

**Comment by carlochess** [comment]
Duplicate, closing
