### ISSUE TITLE
Need ability to specify "on-demand" instance count for aws_spot_fleet_request resource

### ISSUE THREAD

**Issue by ZillaG** [hashicorp/terraform-provider-aws#16607]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
```
$ terraform -version
Terraform v0.12.17
+ provider.aws v3.2.0
```

I created an AWS launch template via the aws_launch_template resource, and am creating a spot fleet request using the template via the aws_spot_fleet_request resource.

In the AWS console, when creating a spot fleet request using a launch template, I have the option to specify on-demand instances.

However, I don't see that option in the aws_spot_fleet_request resource. So even though I'm able to create the spot fleet request, all of the instances are spot instances, and no on-demand instances. Can we add it please?

I posted [Setting AWS on-demand instances using Terraform aws_spot_fleet_request resource using a launch_template?](https://stackoverflow.com/questions/65152811/setting-aws-on-demand-instances-using-terraform-aws-spot-fleet-request-resource) in Stackoverflow which has the screen shot of the AWS console option I mention.

### New or Affected Resource(s)

* aws_spot_fleet_request

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by DrFaust92** [comment]
Related #7011

**Comment by ZillaG** [comment]
Same as #13127
