### ISSUE TITLE
AWS aws_secretsmanager_secret_version resource shows changes upon no change in secret value

### ISSUE THREAD

**Issue by f3d0r** [hashicorp/terraform-provider-aws#16606]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform version: `v0.14.0`
`hashicorp/aws` provider version: `v3.20.0`

### Affected Resource(s)

* `aws_secretsmanager_secret_version`

### Terraform Configuration Files

```hcl
module "foo" {
   ...
}

resource "aws_secretsmanager_secret" "foo" {
  name = module.foo.some_key
}

resource "aws_secretsmanager_secret_version" "foo" {
  secret_id     = aws_secretsmanager_secret.foo.name
  secret_string = module.foo.some_value
}
```

### Expected Behavior

 - Upon receiving an identical value (from a module) as stored in the TF state for the `secret_string` field of the `aws_secretsmanager_secret_version` resource, I expect Terraform to report that there are no changes between the old TF state and new TF state when refreshing the module values.

### Actual Behavior

 - Despite the actual secret value staying the same, terraform reports the following changes in the `terraform plan` step:

```
  # aws_secretsmanager_secret_version.aurora_master will be updated in-place
  ~ resource "aws_secretsmanager_secret_version" "foo" {
        id             = "somekey|SOME_SECRET_VERSION"
      + secret_binary  = (sensitive value)
      # Warning: this attribute value will be marked as sensitive and will
      # not display in UI output after applying this change
      ~ secret_string  = (sensitive value)
        # (4 unchanged attributes hidden)
    }
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

 - I was previously using terraform `v0.13.5` and `hashicorp/aws` provider version: `v3.14.0` without issues
 - After upgrading to `v0.14.0`, in order to debug, I downgraded the provider back to `v3.14.0` (with terraform `v0.14.0` and the issue persisted.

**Comment by bill-rich** [comment]
Hi @f3d0r! Please upgrade to v0.14.2 and give this another try. There were some changes with the the recent releases to address similar issues https://github.com/hashicorp/terraform/releases/tag/v0.14.1.

**Comment by f3d0r** [comment]
Thanks @bill-rich, I believe this is fixed. Can no longer reproduce.
