### ISSUE TITLE
AMI tag-on-create

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#16610]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon Machine Images (AMIs) now support tag-on-create.

### New or Affected Resource(s)

* [`aws_ami_from_instance`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ami_from_instance)

### Potential Terraform Configuration

```hcl
resource "aws_ami_from_instance" "example" {
  tags = {
    Environment = "test"
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-machine-images-support-tag-on-create-tag-based-access-control/).

Requires: [AWS SDK v1.36.2](https://github.com/aws/aws-sdk-go/releases/tag/v1.36.2),

**Comment by kamilturek** [comment]
Hey @ewbankkit 
Looks like it can be closed due to https://github.com/hashicorp/terraform-provider-aws/pull/17968.
