### ISSUE TITLE
Terraform 0.14.0 Breaks Lifecycle ignore_changes for aws_lambda_function Resource

### ISSUE THREAD

**Issue by e-moshaya** [hashicorp/terraform-provider-aws#16635]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.0
+ provider registry.terraform.io/hashicorp/archive v2.0.0
+ provider registry.terraform.io/hashicorp/aws v3.20.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* aws_lambda_function

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_lambda_function" "this" {
  count = var.enable ? 1 : 0
  lifecycle {
    ignore_changes = [
      last_modified
    ]
  }
}
```

### Expected Behavior

Terraform plan runs without erros

### Actual Behavior

```
Error: Computed attribute cannot be set

  on ../../modules/terraform-aws-lambda-module/main.tf line 87, in resource "aws_lambda_function" "this":
  87: resource "aws_lambda_function" "this" {
```

### Steps to Reproduce

Since updating to Terraform 0.14.0, I get the error above. This error goes away when I remove the lifecycle ignore_changes block.

**Comment by ewbankkit** [comment]
@e-moshaya Thanks for raising this issue.
This is an upstream Terraform issue being tracked here: https://github.com/hashicorp/terraform/pull/27141.
