### ISSUE TITLE
data source/service: Add a service data source

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#16641]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be helpful to have a data source to help with service names such as `com.amazonaws.us-east-1.s3`. While these components can be composed from existing data sources, a new data source would be convenient for practitioners and provide a way to work backwards from a service name to regions, service prefixes, and service IDs.

This allows practitioners and maintainers to create configurations that can move more easily between partitions. This is a next step following on with data sources such as `aws_region` and `aws_partition`.

### New or Affected Resource(s)

* aws_service

### Potential Terraform Configuration

```hcl
resource "aws_vpc" "test" {
  cidr_block = "10.0.0.0/16"

  tags = {
    Name = %[1]q
  }
}

data "aws_service" "s3" {
  service_id = "s3"
}

resource "aws_vpc_endpoint" "test" {
  vpc_id       = aws_vpc.test.id
  service_name = data.aws_service_name.s3.reverse_dns_name
}
```

### References

* #16639

**Comment by DrFaust92** [comment]
Question, how does this differ from the `aws_vpc_endpoint_service` data source?

**Comment by bflad** [comment]
@DrFaust92 the missing context here is that this data source would initially operate without an API call. 👍 

I think the naming could be improved though, since an `aws_service_name` sounds like "EC2" to me and we try to leave off any particular "attributes" when naming data sources (`aws_subnet_ids` having ARNs 😢 ). Since the expectation here would be that is supports forward and reverse DNS entries, and potentially other attributes in the future, maybe `aws_service` is more apt?

**Comment by YakDriver** [comment]
I always like shorter; `aws_service` sounds good to me.

As for attributes, what about:
* `name` - e.g., `cn.com.amazonaws.ap-northeast-1.s3` (same as `reverse_dns`)
* `reverse_dns`  - e.g., `cn.com.amazonaws.ap-northeast-1.s3` (same as `name`)
* `region` - e.g., `ap-northeast-1`
* `service_id` - `s3`
* `dns` - e.g., `s3.ap-northeast-1.amazonaws.com.cn`

Would there be any value in an attribute like this?

* `supported` - boolean of whether service is listed in partition services (would document that not 100% accurate)
