### ISSUE TITLE
Support AWS Codepipeline Transition

### ISSUE THREAD

**Issue by vibhuyadav** [hashicorp/terraform-provider-aws#16646]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support AWS Codepipeline Transition
https://docs.aws.amazon.com/codepipeline/latest/APIReference/API_DisableStageTransition.html

### New or Affected Resource(s)

* aws_codepipeline

**Comment by michaaelw** [comment]
👍
