### ISSUE TITLE
Crashing with: Error: rpc error: code = Unavailable desc = transport is closing 

### ISSUE THREAD

**Issue by rmgval** [hashicorp/terraform-provider-aws#16654]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.14.2 + provider registry.terraform.io/hashicorp/aws v3.20.0

### Affected Resource(s)

* aws_workspaces_directory
* aws_workspaces_workspace
* aws_directory_service_directory

### Terraform Configuration Files

```resource "aws_workspaces_directory" "anotherworkspace" {
  directory_id = aws_directory_service_directory.anotherworkspace.id
  subnet_ids   = ["subnet-xxxxxxxx", "subnet-yyyyyyyyyyyy"]
  #subnet_ids   = ["data.terraform_remote_state.network.public_subnets"]
  
  workspace_creation_properties {
    enable_internet_access = true
    enable_maintenance_mode = true
    #user_enabled_as_local_administrator = false
  }
}

data "aws_workspaces_bundle" "w10_terraform_test" {
  bundle_id = "wsb-5rw9k8l9c" # Value with Windows 10 (English)
}
```

### Debug Output

```
Error: rpc error: code = Unavailable desc = transport is closing

```

### Expected Behavior

Should at least run plan without error.

### Actual Behavior

Getting the error below:
`Error: rpc error: code = Unavailable desc = transport is closing
`

### Steps to Reproduce

1. `terraform plan`

### Important Factoids
It happens all the time.
I can't even get to ``terraform apply`` as it happens during ``terraform plan``

### References

* #0000

**Comment by ewbankkit** [comment]
@rmgval Thanks for raising this issue.
Do you have the crash stack trace that you could paste into this issue?

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/d8d69f553e6c770dea61f1e711df1396ee21de11/aws/resource_aws_workspaces_workspace.go#L195-L205

https://github.com/hashicorp/terraform-provider-aws/blob/d8d69f553e6c770dea61f1e711df1396ee21de11/aws/internal/service/workspaces/waiter/status.go#L27-L38

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 3.22.0 of the Terraform AWS Provider, later this week. Thank you to @Tensho for the fix. 👍

**Comment by rmgval** [comment]
Was 3.22.0 released? I am still experiencing the same error.

**Comment by Tensho** [comment]
@rmgval Will be released at the ned of the week.

**Comment by rmgval** [comment]
Hi,
I just tested and I am still experiencing the same issue..

**Comment by Tensho** [comment]
@rmgval Please could you share the crash report, full configuration, debug log and steps to reproduce?

**Comment by rmgval** [comment]
I used the same steps and configuration as when I opened this issue and the logs also show are the same results I posted initially. Am I doing something wrong?
Again, I am getting this error while running `terraform plan`.

**Comment by rmgval** [comment]
Update: 
My apologies. I thought I replied earlier but didn't submit it. I forgot to update my provider version.
I can confirm this works properly now. Thanks again for your help.
