### ISSUE TITLE
service/ec2: Using STS GetCallerIdentity ARN As Principal Can Fail

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#16657]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Certain acceptance test configurations rely on the `aws_caller_identity` data source (STS GetCallerIdentity) `arn` attribute, which when using assume role credentials can cause problems:

```
=== CONT  TestAccAWSVpcEndpoint_VpcEndpointType_GatewayLoadBalancer
    resource_aws_vpc_endpoint_test.go:519: Step 1/2 error: Error running apply:
        Error: error adding VPC Endpoint Service permissions: InvalidPrincipal: Invalid Principal: 'arn:aws:sts::--OMITTED--:assumed-role/terraform_team1_dev-admin/--OMITTED--'
          status code: 400, request id: 375c4645-3761-49b1-9758-3c9b5a51c115

=== CONT  TestAccAWSVpcEndpointService_AllowedPrincipals
    resource_aws_vpc_endpoint_service_test.go:125: Step 1/3 error: Error running apply:
        Error: error adding VPC Endpoint Service permissions: InvalidPrincipal: Invalid Principal: 'arn:aws:sts::--OMITTED--:assumed-role/terraform_team1_dev-admin/--OMITTED--'
          status code: 400, request id: f3e9a77f-3c7d-4acc-9127-f931c4ffbb37
```

e.g.

```terraform
data "aws_caller_identity" "current" {}

resource "aws_vpc_endpoint_service_allowed_principal" "allow_me_to_foo" {
  vpc_endpoint_service_id = aws_vpc_endpoint_service.foo.id
  principal_arn           = data.aws_caller_identity.current.arn
}
```

These likely need to be updated to `"*"` or the root account ARN `"aws:${data.aws_partition.current.partition}:iam::${data.aws_caller_identity.current.account_id}:root"`

### Affected Resources

* aws_default_route_table (testing)
* aws_route (testing)
* aws_route_table (testing)
* aws_vpc_endpoint (testing and documentation)
* aws_vpc_endpoint_connection_notification (testing)
* aws_vpc_endpoint_service (testing)
* aws_vpc_endpoint_service_allowed_principal (testing and documentation)

### References

- https://github.com/hashicorp/terraform-provider-aws/pull/16656

**Comment by grf5** [comment]
Seeing this as well

Terraform version:
```
% terraform -v
Terraform v0.15.5
on darwin_amd64
```

Provider versions:
```
- Using previously-installed hashicorp/external v2.1.0
- Using previously-installed hashicorp/aws v3.44.0
- Using previously-installed hashicorp/random v3.1.0
- Using previously-installed hashicorp/tls v3.1.0
- Using previously-installed hashicorp/template v2.2.0
```

Plan snippet (lines 313-320):
```
resource "aws_vpc_endpoint_service" "securityServicesES" {
  acceptance_required = false
  allowed_principals = [data.aws_caller_identity.current.arn]
  gateway_load_balancer_arns = [aws_lb.securityServicesGWLB.arn]
  tags = {
    Name = "${var.projectPrefix}-securityServicesES-${random_id.buildSuffix.hex}"
  }
}
```

Response:
```
│ Error: Error modifying VPC Endpoint Service permissions: InvalidPrincipal: Invalid Principal: 'arn:aws:sts::--OMITTED--:assumed-role/--OMITTED--/--OMITTED--'
│       status code: 400, request id: 4975dd95-34fd-48f4-ae31-01cb938a4b5c
│ 
│   with aws_vpc_endpoint_service.securityServicesES,
│   on main.tf line 313, in resource "aws_vpc_endpoint_service" "securityServicesES":
│  313: resource "aws_vpc_endpoint_service" "securityServicesES" {
│ 
```

**Comment by erikpaasonen** [comment]
I can confirm experiencing this issue using 3.70.0 and Terraform v1.0.11 with the following code:
```hcl
resource "aws_vpc_endpoint_service_allowed_principal" "test" {
  vpc_endpoint_service_id = aws_vpc_endpoint_service.test.id
  principal_arn           = data.aws_iam_session_context.assumed.issuer_arn
}

data "aws_iam_session_context" "assumed" {
  arn = data.aws_caller_identity.current.arn
}

data "aws_caller_identity" "current" {}
```
Result:
> Error: Error creating VPC Endpoint Service allowed principal: InvalidPrincipal: 
status code: 400, request id: a30719f0-GUID-GUID-GUID-fd53f24f3b07
