### ISSUE TITLE
ECR cross region image replication

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#16668]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Amazon Elastic Container Registry (Amazon ECR) now supports cross region replication of images in private repositories

### New or Affected Resource(s)

* `aws_ecr_registry_policy`
* `aws_ecr_replication_configuration`

### Potential Terraform Configuration

```hcl
resource "aws_ecr_registry_policy" "example" {
  policy = <<EOF
{
...
}
EOF
}

resource "aws_ecr_replication_configuration" "example" {
  replication_configuration {
    rule {
      destination {
        region      = "eu-central-1"
        registry_id = "123456789012"
      }
    }
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-ecr-announces-cross-region-replication-of-images/).
[Blog post](https://aws.amazon.com/blogs/containers/cross-region-replication-in-amazon-ecr-has-landed/).
[User Guide](https://docs.aws.amazon.com/AmazonECR/latest/userguide/registry-settings.html).

Requires [AWS SDK v1.36.4](https://github.com/aws/aws-sdk-go/releases/tag/v1.36.4):

* https://github.com/hashicorp/terraform-provider-aws/pull/16662

**Comment by TomTucka** [comment]
@bflad I'm happy to pick this up for implementation. Rather than creating a new resource though, should we follow on from what s3 replication does and have `replication_configuration` as an optional on the `aws_ecr_repository` resource?

**Comment by DenisBY** [comment]
It seems it's not possible to define replication per repository, only per whole ECR for all repositories in it.

**Comment by groodt** [comment]
Yes, it seems like it applies at the registry level, not the repository level. That's fine though I think.

**Comment by marcuz** [comment]
Any ETA on when #16831 and #16853 will be merged and released? :raised_hands:

**Comment by gdavison** [comment]
The linked PRs #16831 and #16853 have beed merged
