### ISSUE TITLE
Add support for `aws_subnet_network_acl_association`

### ISSUE THREAD

**Issue by Tzrlk** [hashicorp/terraform-provider-aws#16660]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform still doesn't have support for adding an `aws_subnet` to an existing `aws_network_acl` (previous request: #5466).

The API call that CloudFormation uses for `AWS::EC2::SubnetNetworkAclAssociation` is [ReplaceNetworkAclAssociation](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ReplaceNetworkAclAssociation.html)

### New or Affected Resource(s)

* aws_subnet_network_acl_association

### Potential Terraform Configuration

```hcl
resource "aws_subnet_network_acl_association" "subnet_a" {
  subnet_id      = "${aws_subnet.public_a.id}"
  network_acl_id = "${aws_network_acl.public_acl.id}"
}
```

### References

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet-network-acl-assoc.html
* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ReplaceNetworkAclAssociation.html

**Comment by elior379** [comment]
any news on this?
