### ISSUE TITLE
Support node_group_name_prefix for aws_eks_node_group

### ISSUE THREAD

**Issue by mfreebairn-r7** [hashicorp/terraform-provider-aws#16699]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

aws_eks_node_group should support node_group_name_prefix.

Currently it only supports `node_group_name`. This is an issue when you want to change instance type(s) for your node group as terraform forces a replacement of the node group, and because `node_group_name` must be unique, this therefore prevents you from adding the `create_before_destroy` lifecycle.

This leads to downtime (zero compute due to the node group having to be destroyed) every time you want to change instance type(s) (even if you are only adding an additional instance type to the `instance_types` list).

`node_group_name_prefix` would allow us to support `create_before_destroy` and therefore we could bring up a new node group prior to destroying the old one when we want to change `instance_types`

### New or Affected Resource(s)

aws_eks_node_group

**Comment by Skaronator** [comment]
This seems to be fixed by the following PRs once merged.
* https://github.com/hashicorp/terraform-provider-aws/pull/13938 OR
* https://github.com/hashicorp/terraform-provider-aws/pull/15407

**Comment by mfreebairn-r7** [comment]
Thanks, I missed those PRs!

**Comment by dstevensson** [comment]
@mfreebairn-r7 this was fixed in #13938 which made it's way into [v3.40.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3400-may-13-2021). As a workaround before the PR got accepted I started changing the instance type in a custom launch template instead which allowed me to change the instance type without bringing down all the nodes.

**Comment by breathingdust** [comment]
This appears to be resolved as the comments indicates. Closing.
