### ISSUE TITLE
aws_ec2_instance_type_offerings should return the locations

### ISSUE THREAD

**Issue by orgito** [hashicorp/terraform-provider-aws#16703]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The data source `aws_ec2_instance_type_offerings` should return a  locations field when the `location_type` is `availability-zone` or `availability-zone-id`. It actually makes sense to return the locations field even if the location_type is `region`, to keep the interface consistent.

The locations can be obtained from the Location field in the AWS API response as shown below:

```json
$ aws ec2 describe-instance-type-offerings --location-type availability-zone --filters Name=instance-type,Values=c5a.xlarge
{
    "InstanceTypeOfferings": [
        {
            "InstanceType": "c5a.xlarge",
            "LocationType": "availability-zone",
            "Location": "us-east-1d"
        },
        {
            "InstanceType": "c5a.xlarge",
            "LocationType": "availability-zone",
            "Location": "us-east-1c"
        },
        {
            "InstanceType": "c5a.xlarge",
            "LocationType": "availability-zone",
            "Location": "us-east-1a"
        }
    ]
}
```

For now, I'm using an `external` data source to get the info. But it would be nice and more portable to use the AWS provider for that.

### New or Affected Resource(s)

* aws_ec2_instance_type_offerings

### Potential Terraform Configuration

```hcl
# I want to select only private subnets in availability zones that support a specific instance type

# Here I select the azs that support my instance type
data "aws_ec2_instance_type_offerings" "supports-my-instance" {
  filter {
    name   = "instance-type"
    values = [var.instance_type]
  }
  location_type = "availability-zone"
}

# and here I use the locations to to filter
data "aws_subnet_ids" "private" {
  vpc_id = var.vpc_id
  filter {
    name   = "availability-zones"
    values = data.aws_ec2_instance_type_offerings.supports-my-instance.locations
  }
  tags = {
    Terraform = "true"
    Tier      = "private"
  }
}
```

### References

* #16704

**Comment by Elethiomel** [comment]
I have a similar use case in that I need to launch N instances over M availability zones. For all the instances I've used so far, selecting based on azs[N%M] has been fine. Now I'm launching GPU instances and some regions only have support in specific azs. I need the location field so I can only select those azs support my instance type.

**Comment by ewbankkit** [comment]
@orgito Thanks for raising this issue.
It has already been noticed in #15272. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
