### ISSUE TITLE
resource/aws_db_instance: Should support enabling cross-region automated backups

### ISSUE THREAD

**Issue by JTP3XP** [hashicorp/terraform-provider-aws#16708]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

RDS supports enabling cross-region automated backups via the API as described here:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReplicateBackups.html

### New or Affected Resource(s)

* aws_db_instance

### Potential Terraform Configuration

```hcl
resource "aws_db_instance" "this_db_instance" {
	identifier = local.rds_name

	allocated_storage = var.allocated_storage
	max_allocated_storage = var.max_allocated_storage
	
	apply_immediately = var.apply_immediately
	
	auto_minor_version_upgrade = var.auto_minor_version_upgrade
	allow_major_version_upgrade = var.allow_major_version_upgrade
	
	availability_zone = data.aws_subnet.rds_subnet1.availability_zone
	multi_az = var.multi_az
	
	backup_retention_period = var.backup_retention_period
	backup_window = var.backup_window
	
	###### NEW CONFIGURATION
	backup_replication_region = "us-east-2"
	backup_replication_retention_period = 28
	######
	
	maintenance_window = var.maintenance_window
	
	db_subnet_group_name = aws_db_subnet_group.this_db_subnet_group.name

	deletion_protection = var.deletion_protection
	
	engine = var.engine
	engine_version = var.engine_version
	
	kms_key_id = aws_kms_key.this_key.arn
	storage_encrypted = "true"
	
	parameter_group_name = aws_db_parameter_group.this_parameter_group.name

	username = var.username
	password = var.password
	
	publicly_accessible = false
	
	skip_final_snapshot = false
	final_snapshot_identifier = "finalsnapshot-${local.rds_name}"
	
	instance_class = var.instance_class
	
	performance_insights_enabled = true
	performance_insights_kms_key_id = aws_kms_key.this_key.arn
	performance_insights_retention_period = var.performance_insights_retention_period
	
	tags = {
		Name = local.rds_name
	}
}
```

**Comment by dannyg28** [comment]
If no one is already working on this I wouldn't mind giving it a shot

**Comment by danieljamesscott** [comment]
> If no one is already working on this I wouldn't mind giving it a shot

I'd be happy to help out with this too.

**Comment by jonasoneves** [comment]
Related to this. Please give a thumbs up.
https://github.com/hashicorp/terraform-provider-aws/issues/21851

We currently can't restore backups via terraform using automated backups as a source.

**Comment by mzazon** [comment]
> Related to this. Please give a thumbs up. #21851
> 
> We currently can't restore backups via terraform using automated backups as a source.

We had started using source_dbi_resource_id  for cross-region restore and this appears to work, rather than the source_db_instance_identifier

**Comment by jashvadevops** [comment]
Hi guys,
do you have any solution on this Enable replication in another AWS Region using terraform..I also came through the same kind of requirement.

kindly let me know Enable replication in another AWS Region using terraform..

Thanks in Advance.

Regards
Jashva

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

**Comment by ewbankkit** [comment]
Similar: https://github.com/hashicorp/terraform-provider-aws/issues/16708.
