### ISSUE TITLE
Amazon EMR on Amazon EKS

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#16717]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Amazon EMR on EKS provides a deployment option for Amazon EMR that allows you to run open-source big data frameworks on Amazon Elastic Kubernetes Service (Amazon EKS).

### New or Affected Resource(s)

* `aws_emrcontainers_virtual_cluster`

### Potential Terraform Configuration

```hcl
resource "aws_emrcontainers_virtual_cluster" "example" {
  name = "example-cluster"

  container_provider {
    id = aws_eks_cluster.example.id
  }
}
```

### References

[Blog post](https://aws.amazon.com/blogs/aws/new-amazon-emr-on-amazon-elastic-kubernetes-service-eks/).
[Developer Guide](https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/emr-eks.html).
[API Reference](https://docs.aws.amazon.com/emr-on-eks/latest/APIReference/Welcome.html)

Requires [AWS SDK v1.36.4](https://github.com/aws/aws-sdk-go/releases/tag/v1.36.4):

* https://github.com/hashicorp/terraform-provider-aws/pull/16713

**Comment by jmazumder** [comment]
👍

**Comment by jmazumder** [comment]
👍

**Comment by shuheiktgw** [comment]
I'm going to work on this issue!

**Comment by shuheiktgw** [comment]
Added emrcontainers service as a first step so would anybody review the PR? 🙏 
- https://github.com/hashicorp/terraform-provider-aws/pull/17065

**Comment by shuheiktgw** [comment]
While implementing it, I noticed problems...
https://github.com/hashicorp/terraform-provider-aws/pull/17355#issuecomment-772095379

**Comment by mickmorseMB** [comment]
@shuheiktgw any updates on getting this in?

**Comment by shuheiktgw** [comment]
@mickmorseMB There are several problems we need to tackle and right now I don't have enough time for them... I'll leave the draft PR open so that if someone wants to take it over from there, please go ahead and implement it.

**Comment by thehunt33r** [comment]
Hi @ewbankkit 

I have continued @shuheiktgw's work in https://github.com/hashicorp/terraform-provider-aws/pull/20003. Could you please take a look at some point? There's one small issue left where I would need your guidance (appears to be a bug in the plugin-sdk?)

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

**Comment by bryantbiggs** [comment]
getting close to the end of the quarter - hopefully its coming soon 😬 🙏🏽
