### ISSUE TITLE
VPC Reachability Analyzer / EC2 Network Insights

### ISSUE THREAD

**Issue by Omarimcblack** [hashicorp/terraform-provider-aws#16715]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* `aws_ec2_network_insights_analysis`
* `aws_ec2_network_insights_path`
* data source: `aws_ec2_network_insights_path`
* data source: `aws_ec2_network_insights_analysis`

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-vpc-announces-reachability-analyzer-to-simplify-connectivity-testing-and-troubleshooting/)
* [blog post](https://aws.amazon.com/blogs/aws/new-vpc-insights-analyzes-reachability-and-visibility-in-vpcs/)
* [User Guide](https://docs.aws.amazon.com/vpc/latest/reachability/what-is-reachability-analyzer.html)

Requires [AWS SDK v1.36.6](https://github.com/aws/aws-sdk-go/releases/tag/v1.36.6):

* #16713

**Comment by ewbankkit** [comment]
@Omarimcblack Thanks for raising this issue.
The names should probably be `aws_ec2_network_insights_path` and `aws_ec2_network_insights_analysis` as they fall under the EC2 umbrella.

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-vpc-announces-reachability-analyzer-to-simplify-connectivity-testing-and-troubleshooting/).
[User Guide](https://docs.aws.amazon.com/vpc/latest/reachability/what-is-reachability-analyzer.html).

Requires [AWS SDK v1.36.6](https://github.com/aws/aws-sdk-go/releases/tag/v1.36.6):

* https://github.com/hashicorp/terraform-provider-aws/pull/16713

**Comment by getsec** [comment]
Has there been any future consideration for this?

**Comment by songhanpoo** [comment]
+1

**Comment by ulfmansson** [comment]
+1

**Comment by kderck** [comment]
+1

**Comment by driscolljt** [comment]
+1
