### ISSUE TITLE
tests/data-source/aws_vpc_peering_connection: TestAccDataSourceAwsVpcPeeringConnection_basic Multiple Matches

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#16721]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This acceptance test can have false positives given the environment its running in:

```
=== CONT  TestAccDataSourceAwsVpcPeeringConnection_basic
TestAccDataSourceAwsVpcPeeringConnection_basic: data_source_aws_vpc_peering_connection_test.go:12: Step 1/1 error: Error running apply:
Error: multiple VPC peering connections matched; use additional constraints to reduce matches to a single VPC peering connection
Error: multiple VPC peering connections matched; use additional constraints to reduce matches to a single VPC peering connection
Error: multiple VPC peering connections matched; use additional constraints to reduce matches to a single VPC peering connection
--- FAIL: TestAccDataSourceAwsVpcPeeringConnection_basic (13.23s)
```

The test configuration should be updated to always return only one possible result.

### Affected Data Source

* aws_vpc_peering_connection

### References

* [Contributing Guide on Running/Writing Acceptance Testing](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/contributing/running-and-writing-acceptance-tests.md)

**Comment by morgoved** [comment]
i have this errors

**Comment by bflad** [comment]
These acceptance testing failures have been resolved.
