### ISSUE TITLE
tests/resource/aws_spot_fleet_request: gp3 Volume Type Failures

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#16722]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The recently announced `gp3` volume type, while supported in "all regions", does not appear to work correctly with EC2 Spot Fleet Requests yet in all regions as found by new acceptance testing that passes in AWS Commercial but not AWS GovCloud (US):

```
=== CONT  TestAccAWSSpotFleetRequest_LaunchSpecification_EbsBlockDeviceGp3
    resource_aws_spot_fleet_request_test.go:953: Step 1/2 error: Error running apply:
        Error: Error requesting spot fleet: InvalidSpotFleetRequestConfig:
          status code: 400, request id: af58b8ad-a9bb-49cc-a19a-9fa4cd605df2

=== CONT  TestAccAWSSpotFleetRequest_LaunchSpecification_RootBlockDeviceGp3
    resource_aws_spot_fleet_request_test.go:986: Step 1/2 error: Error running apply:
        Error: Error requesting spot fleet: InvalidSpotFleetRequestConfig:
          status code: 400, request id: aade31cb-4dcc-4d75-9bb2-f94a349a8c41
```

Introducing the new Terraform resource handling does not introduce any regressions, so this functionality will be merged in so practitioners can benefit in AWS Commercial, but the tests will either need `ErrorCheck` handling for the (admittedly very generic) error and/or a support case raised.

### Affected Resource

* aws_spot_fleet_request

### References

* https://aws.amazon.com/blogs/aws/new-amazon-ebs-gp3-volume-lets-you-provision-performance-separate-from-capacity-and-offers-20-lower-price/
* https://github.com/hashicorp/terraform-provider-aws/pull/16652

**Comment by ewbankkit** [comment]
This is now passing:

```
--- PASS: TestAccAWSSpotFleetRequest_LaunchSpecification_EbsBlockDeviceGp3 (135.77s)
```
