### ISSUE TITLE
Global Accelerator BYOIP IP addresses as Arguments for aws_globalaccelerator_accelerator resource

### ISSUE THREAD

**Issue by s-vanam** [hashicorp/terraform-provider-aws#16746]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* Global accelerator now supports BYOIP addresses for an accelerator, While we could choose the IP addresses from the BYOIP pools through GUI / BOTO3 call, Terraform global accelerator resource doesnt have any arguments to assign the BYOIP IP addresses to the new listener when we are provisioning them

* We can use the same ```ip_addresses``` attribute of this resource also as an argument to provide list of IP addresses that we want to attach to a listener

### New or Affected Resource(s)

* aws_globalaccelerator_accelerator

### References

* https://docs.aws.amazon.com/global-accelerator/latest/dg/using-byoip.html
* https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/globalaccelerator.html#GlobalAccelerator.Client.create_accelerator

* #0000

**Comment by ewbankkit** [comment]
@s-vanam Thanks for raising this issue.
It has already been noticed in #14002. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
