### ISSUE TITLE
Codeguru profiling group resource

### ISSUE THREAD

**Issue by taylora433** [hashicorp/terraform-provider-aws#16768]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Resource for codeguru profiler is missing.

### New or Affected Resource(s)

* aws_codeguruprofiler_profiling_group

Will also need to attach permissions to the profiling group, unsure if this would be the same resource or another resource, as you attach them after creation. 

### Potential Terraform Configuration

```hcl
resource "aws_codeguruprofiler_profiling_group" "default" {
  name = "name"
  compute_platform = "other|lambda"
  tags = {tag1 = val1}
}
```

### References

* https://docs.aws.amazon.com/codeguru/latest/profiler-ug/what-is-codeguru-profiler.html

**Comment by gdavison** [comment]
Thanks for the issue, @taylora433. To match with our naming conventions (defined at https://github.com/hashicorp/terraform-provider-aws/blob/master/docs/contributing/contribution-checklists.md#new-resource), this should be called `aws_codeguruprofiler_profiling_group`.

**Comment by taylora433** [comment]
Thank you for the response. I'll update the naming :)

**Comment by adeline-chew-sp** [comment]
Hi there, is there any plan in getting this merged?

**Comment by dwilches** [comment]
Any news on the state of this request?

**Comment by marcelo-herrera-sp** [comment]
Anything new on this request?

**Comment by 0x91** [comment]
bump?

**Comment by weallwegot** [comment]
checking in on this- any alternative to setting up profiling on AWS with terraform?
