### ISSUE TITLE
Support Custom Email Sender & Custom SMS Sender in lambda_config for aws_cognito_user_pool

### ISSUE THREAD

**Issue by eddywashere** [hashicorp/terraform-provider-aws#16760]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support to define custom email sender and custom sms sender cognito lambda triggers within the lambda_config for aws_cognito_user_group resource. Additionally, the lambda config will need to support setting a kms key id. More info here https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-sender-triggers.html.

### New or Affected Resource(s)

* aws_cognito_user_group

### Potential Terraform Configuration

```hcl
resource "aws_cognito_user_pool" "pool" {
  name                       = "terraform-example"

  lambda_config {
    create_auth_challenge          = aws_lambda_function.main.arn
    custom_message                 = aws_lambda_function.main.arn
    define_auth_challenge          = aws_lambda_function.main.arn
    kms_key_id                     = aws_kms_key.main.arn
    post_authentication            = aws_lambda_function.main.arn
    post_confirmation              = aws_lambda_function.main.arn
    pre_authentication             = aws_lambda_function.main.arn
    pre_sign_up                    = aws_lambda_function.main.arn
    pre_token_generation           = aws_lambda_function.main.arn
    user_migration                 = aws_lambda_function.main.arn
    verify_auth_challenge_response = aws_lambda_function.main.arn

    custom_email_sender {
      lambda_arn     = aws_lambda_function.test.arn
      lambda_version = "V1_0"
    }

    custom_sms_sender {
      lambda_arn     = aws_lambda_function.test.arn
      lambda_version = "V1_0"
    }
  }
}
```

### References

- More info here https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-sender-triggers.html

**Comment by maximivanov** [comment]
Until it's supported by Terraform natively, one workaround is to use `null_resource` with `aws cognito-idp update-user-pool` command.

```hcl
locals {
    update_user_pool_command = "aws cognito-idp update-user-pool --user-pool-id ${aws_cognito_user_pool.cognito_user_pool.id} --cli-input-json file://${var.update_user_pool_config_file} --lambda-config \"CustomEmailSender={LambdaVersion=V1_0,LambdaArn=${aws_lambda_function.lambda_function_trigger.arn}},KMSKeyID=${aws_kms_key.kms_key.arn}\""
}

resource "null_resource" "cognito_user_pool_lambda_config" {
  provisioner "local-exec" {
    command = local.update_user_pool_command
  }
  depends_on = [local.update_user_pool_command]
  triggers = {
    input_json = filemd5(var.update_user_pool_config_file)
    update_user_pool_command = local.update_user_pool_command
  }
}
```

`--cli-input-json file://${var.update_user_pool_config_file}` is to use existing pool configuration (otherwise pool settings will be reset to defaults by `update-user-pool`). 

It's not super convenient (deploy stack without null resource -> download pool configuration -> redeploy with null resource) and can probably be scripted so it works in one go... But it works nevertheless. Full blog post [here](https://www.maxivanov.io/send-aws-cognito-emails-with-3rd-party-esps/).

**Comment by unfor19** [comment]
@maximivanov - extending your solution, to avoid this

> It's not super convenient (deploy stack without null resource -> download pool configuration -> redeploy with null resource) and can probably be scripted so it works in one go... But it works nevertheless.

The following setup works, I've tested it on my infra.

### Requirements
- AWS CLI v2 - To me it wasn't obvious, I had to upgrade from v1.18 to v2 to use to the `update-user-pool` with `CustomEmailSender`
- [jq](https://stedolan.github.io/jq/download/) to merge existing lambda_config with the newly added `CustomEmailSender` lambda_config
- Tested with Terraform 0.13.5

### Solution

At least until there's a better solution (feel free to improve this one). Comments inline

```terraform
module "send_email_lambda" {
 source = "terraform-aws-modules/lambda/aws"
 version = "2.2.0"
 # omitted for brevity
}

resource "aws_kms_key" "kms_key" {} # omitted for brevity
resource "aws_cognito_user_pool" "app_users" {} # omitted for brevity

variable "region" {
  default = "eu-west-1"
}

locals {
  # Get the lambda_config of `aws_cognito_user_pool.app_users` and merge it with `CustomEmailSender` and `KMSKeyID`
  # Save the output to a file named `merged_lambda_config_app_users.json`
  merged_lambda_config_app_users = "aws cognito-idp describe-user-pool --user-pool-id ${aws_cognito_user_pool.app_users.id} --output json --region ${var.region} --query UserPool.LambdaConfig | jq '. + {\"CustomEmailSender\": { \"LambdaVersion\": \"V1_0\", \"LambdaArn\": \"${module.send_email_lambda.lambda_function_arn}\"}, \"KMSKeyID\": \"${aws_kms_key.kms_key.arn}\" }' > merged_lambda_config_app_users.json"

  # Use the file `merged_lambda_config_app_users.json` to update the user pool, while preserving existing configurations
  update_user_pool_command_app_users = "aws cognito-idp update-user-pool --user-pool-id ${aws_cognito_user_pool.app_users.id} --region ${var.region} --lambda-config \"$(cat merged_lambda_config_app_users.json)\""
}


# Generate merged file
resource "null_resource" "merged_lambda_config_app_users" {
  provisioner "local-exec" {
    command = local.merged_lambda_config_app_users
  }
  depends_on = [local.merged_lambda_config_app_users]
  triggers = {
    merged_lambda_config_app_users = local.merged_lambda_config_app_users
  }
}

# Apply changes
resource "null_resource" "cognito_user_pool_lambda_config_app_users" {
  provisioner "local-exec" {
    command = local.update_user_pool_command_app_users
  }
  depends_on = [null_resource.merged_lambda_config_app_users, local.update_user_pool_command_app_users]
  triggers = {
    update_user_pool_command_app_users = local.update_user_pool_command_app_users
  }
}
```

@maximivanov  Thank you very much for sharing your solution!
