### ISSUE TITLE
Support discovery using tags in data.aws_lb 

### ISSUE THREAD

**Issue by AlexMichaelJonesNC** [hashicorp/terraform-provider-aws#16771]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As a user of kubernetes and the AWS Load Balancer Controller, I have use cases where I want to deploy a private link to target network load balancers created by the AWS Load Balancer Controller. Since the name of these created balancers is not deterministic, This currently requires manual effort to lookup the ARN or name of the created balancer to place into the data object. 

It would be highly beneficial to my use case if I was able to lookup the load balancer based on tags and vpc. 

I believe the reason this is not currently available is because the AWS elbb2 describe-load-balancer call does not allow any filtering, so it would need to be implemented client side, and possibly have a huge performance impact. 

### New or Affected Resource(s)

* data.aws_lb

### Potential Terraform Configuration

```hcl
data "aws_lb" "my_nlb" {
  vpc_id = var.vpc_id
  tags = {
       "kubernetes.io/service-name" =  "logging/ingest"
       "kubernetes.io/cluster/my-cluster" = "owned"
  }
}
```

### References

* #0000

**Comment by ewbankkit** [comment]
@AlexMichaelJonesNC Thanks for raising this issue.
It has already been noticed in #12265. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
