### ISSUE TITLE
Support private DNS for endpoint services

### ISSUE THREAD

**Issue by AlexMichaelJonesNC** [hashicorp/terraform-provider-aws#16775]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We would like to use terraform to manage an endpoint service with a private dns entry, but the current version of the provider does not allow setting a private_dns_name, or retrieving the domain verification data from an endpoint service. This makes it impossible to fully manage an endpoint service with a dns name.

### New or Affected Resource(s)

* aws_vpc_endpoint_service
* data.aws_vpc_endpoint_service

### Potential Terraform Configuration

```hcl
resource "aws_vpc_endpoint_service" "example" {
  acceptance_required        = false
  network_load_balancer_arns = [aws_lb.example.arn]
  private_dns_name = "my-endpoint-service.mydomain.com"
}
```

**Comment by ewbankkit** [comment]
@AlexMichaelJonesNC Thanks for raising this issue.
It has already been noticed in #16568. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
