### ISSUE TITLE
aws_s3_bucket grant deployed with FULL_ACCESS when permissions are set

### ISSUE THREAD

**Issue by eimantas-gecas-axomic** [hashicorp/terraform-provider-aws#16776]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.5
provider registry.terraform.io/hashicorp/aws v3.12.0

### Affected Resource(s)

* aws_s3_bucket

### Terraform Configuration Files

```hcl
resource aws_s3_bucket logs {
  bucket = "test-bucket"
  grant {
    type        = "CanonicalUser"
    permissions = ["READ", "WRITE"]
    id          = "c4c1ede66af53448b93c283ce9448c4ba468c9432aa01d700d3878632f77d2d0"
  }
}
```

### Expected Behavior

Running terraform apply deploys the bucket as expected

### Actual Behavior

Running terraform apply deployed the bucket, with the grant in "FULL_ACCESS" permissions. Which means, you then have to run terraform apply again to change the permissions

### Steps to Reproduce

1. `terraform apply`
1. `terraform plan`

**Comment by ewbankkit** [comment]
Related:

* https://github.com/hashicorp/terraform-provider-aws/issues/13109
