### ISSUE TITLE
Unable to Create DAEMON Service In ECS Cluster with default_capacity_provider_strategy

### ISSUE THREAD

**Issue by pilchkinstein-perspectum** [hashicorp/terraform-provider-aws#16772]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.21.0

### Affected Resource(s)

* aws_ecs_service
* aws_ecs_cluster

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ecs_service" "service" {
  name            = "service_16772"
  task_definition = aws_ecs_task_definition.task.family
  cluster         = "cluster_16772"

  scheduling_strategy = "DAEMON"

  placement_constraints {
    type = "distinctInstance"
  }
}

resource "aws_ecs_task_definition" "task" {
  container_definitions    = file("service.json")
  family                   = "task_16772"
  requires_compatibilities = ["EC2"]
}

resource "aws_ecs_cluster" "cluster" {
  name               = "cluster_16772"
  capacity_providers = ["cps_16772"]
  default_capacity_provider_strategy {
    capacity_provider = "cps_16772"
    weight            = "100"
    base              = "1"
  }
}

resource "aws_ecs_capacity_provider" "ecs_capacity_provider" {
  name = "cps_16772"
  auto_scaling_group_provider {
    auto_scaling_group_arn = aws_autoscaling_group.asg.arn
  }
}

resource "aws_autoscaling_group" "asg" {
  name             = "asg_16772"
  max_size         = 1
  min_size         = 1
  desired_capacity = 1

  launch_template {
    id      = aws_launch_template.lc.id
    version = aws_launch_template.lc.latest_version
  }

  availability_zones = ["us-east-1a"]
}

resource "aws_launch_template" "lc" {
  image_id = "ami-00ddb0e5626798373"
  instance_type = "t2.small"
}

```

// service.json 
```hcl
[
  {
    "name": "main",
    "image": "nginx",
    "cpu": 10,
    "memory": 512,
    "essential": true,
    "portMappings": [
      {
        "containerPort": 80,
        "hostPort": 80
      }
    ]
  }
]

```

### Debug Output

[bug-16772-debug.log](https://gist.github.com/pilchkinstein-perspectum/23c7f0c6d2b4bd74ecc0ebc853dead42)

### Panic Output

N/A

### Expected Behavior

New DAEMON service should be created on each instance in the ECS cluster

### Actual Behavior

No service is created.
Terraform returns the following:-

Error: InvalidParameterException: Specifying a capacity provider strategy is not supported when you create a service using the DAEMON scheduling strategy. "cadvisor"

### Steps to Reproduce

1. `terraform apply -target=aws_launch_template.lc -target=aws_autoscaling_group.asg -target=aws_ecs_capacity_provider.ecs_capacity_provider`
2. `terraform apply -target=aws_ecs_cluster.cluster -target=aws_ecs_task_definition.task`
3. `terraform apply -target=aws_ecs_service.service`

### Important Factoids

None

### References

* #0000

**Comment by pilchkinstein-perspectum** [comment]
This is now reproducible behaviour.
An ECS cluster with a default capacity provider cannot create a DAEMON task.
The workaround is:-
1. update the ECS cluster and remove the default capacity provider
2. create the DAEMON task
3. update the ECS cluster and add back the default capacity provider

**Comment by wendtek** [comment]
I was able to get around this by setting `launch_type = "EC2"` on the service. I got this tip from https://github.com/aws/containers-roadmap/issues/692
The strange thing is the AWS provider docs indicate `EC2` is the default value for that argument, but it did not work until I explicitly set it on the service.

**Comment by pilchkinstein-perspectum** [comment]
Any news on this?
I'd hate to see it suddenly be archived due to inaction

**Comment by infracaninophile** [comment]
Contrary to @wendtek 's experience, I tried the `launch_type = "EC2"` explicit setting, and it worked fine for me: DAEMON processes successfully running on every instance in the cluster, whether using the default capacity provider or not. 

terraform 0.15.3
aws-provider 3.45.0

**Comment by dspv** [comment]
> Contrary to @wendtek 's experience, I tried the `launch_type = "EC2"` explicit setting, and it worked fine for me: DAEMON processes successfully running on every instance in the cluster, whether using the default capacity provider or not.
> 
> terraform 0.15.3 aws-provider 3.45.0

Worked for me, thanks

**Comment by eyal-solomon1** [comment]
> Contrary to @wendtek 's experience, I tried the `launch_type = "EC2"` explicit setting, and it worked fine for me: DAEMON processes successfully running on every instance in the cluster, whether using the default capacity provider or not.
> 
> terraform 0.15.3 aws-provider 3.45.0
worked for me too, thanks @infracaninophile

**Comment by eyal-solomon1** [comment]
> Contrary to @wendtek 's experience, I tried the `launch_type = "EC2"` explicit setting, and it worked fine for me: DAEMON processes successfully running on every instance in the cluster, whether using the default capacity provider or not.
> 
> terraform 0.15.3 aws-provider 3.45.0

worked for me too, thanks @infracaninophile
