### ISSUE TITLE
AWS Lambda self-managed Apache Kafka event source

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#16785]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> AWS Lambda now allows customers to build applications that can be triggered by messages in an Apache Kafka cluster hosted on any infrastructure.

### New or Affected Resource(s)

* [`aws_lambda_event_source_mapping`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping)

### Potential Terraform Configuration

```hcl
resource "aws_lambda_event_source_mapping" "example" {
  function_name = aws_lambda_function.example.arn

  self_managed_event_source {
    endpoints = {
      KAFKA_BOOTSTRAP_SERVERS = ["abc3.xyz.com:9092,abc2.xyz.com:9092"]
    }
  }

  source_access_configuration {
    type = "VPC_SUBNET"
    uri  = "subnet:${aws_subnet.example.id}"
  }

  topics = ["example"]
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/12/aws-lambda-now-supports-self-managed-apache-kafka-as-an-event-source/).
[Blog post](https://aws.amazon.com/blogs/compute/using-self-hosted-apache-kafka-as-an-event-source-for-aws-lambda/).
[Developer Guide](https://docs.aws.amazon.com/lambda/latest/dg/kafka-smaa.html).

Requires [AWS SDK v1.36.9](https://github.com/aws/aws-sdk-go/releases/tag/v1.36.9):

* #16783

Related:

* #14658
* #14746

**Comment by mishabruml** [comment]
hey! is there intention to start this soon? is there anything I could work on?

**Comment by z00** [comment]
Any idea when will work on this get started?
