### ISSUE TITLE
Add support for Amazon Managed Service for Prometheus

### ISSUE THREAD

**Issue by abuchanan920** [hashicorp/terraform-provider-aws#16788]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has added a preview for a managed Prometheus service.

 Many folks who are using EKS would be interested in offloading support for this to AWS, especially since self-hosted instances are frequently configured in a non-faulttolerant manner (e.g. storage not replicated, etc.)

### References

https://aws.amazon.com/prometheus/

* #16789 - Add support for Amazon Managed Service for Grafana

**Comment by gdavison** [comment]
Thanks for submitting this, @abuchanan920. Since this is currently in preview, we will need to wait for AWS to release it in the [AWS SDK for Go](https://github.com/aws/aws-sdk-go)

**Comment by larstobi** [comment]
@gdavison https://github.com/aws/aws-sdk-go/blob/master/service/prometheusservice/api.go

**Comment by bflad** [comment]
Support for a new `aws_prometheus_workspace` resource (the only available in the current Prometheus API) has been merged and will release with version 3.26.0 of the Terraform AWS Provider, later today. Thank you to @nicolai86 for the implementation. 👍
