### ISSUE TITLE
AWS Lambda checkpointing for Amazon Kinesis and Amazon DynamoDB Streams

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#16787]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> AWS Lambda now allows customers to automatically checkpoint records that have been successfully processed for Amazon Kinesis and Amazon DynamoDB Streams, using a new parameter, FunctionResponseType.

### New or Affected Resource(s)

* [`aws_lambda_event_source_mapping`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping)

### Potential Terraform Configuration

```hcl
resource "aws_lambda_event_source_mapping" "example" {
  function_name = aws_lambda_function.example.arn

  function_response_types = ["ReportBatchItemFailures"]
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/12/aws-lambda-launches-checkpointing-for-amazon-kinesis-and-amazon-dynamodb-streams/).
[Blog post](https://aws.amazon.com/blogs/compute/optimizing-batch-processing-with-custom-checkpoints-in-aws-lambda/).
[Developer Guide](https://docs.aws.amazon.com/lambda/latest/dg/with-ddb.html#services-ddb-batchfailurereporting).

Requires [AWS SDK v1.36.9](https://github.com/aws/aws-sdk-go/releases/tag/v1.36.9):

* #16783

**Comment by orkrichli** [comment]
is there an estimate when this will be supported by terraform?

**Comment by hally9k** [comment]
Does anyone have a workaround for this?

**Comment by Cristigeo** [comment]
I'm using the CLI and running an `aws lambda update-event-source-mapping --function-response-types "ReportBatchItemFailures"` in my pipeline,  after `terraform apply`; I'm also passing the uuid of the terraform-created _aws_lambda_event_source_mapping_.  It's messy, but it works.
