### ISSUE TITLE
Add support for Amazon Managed Service for Grafana

### ISSUE THREAD

**Issue by abuchanan920** [hashicorp/terraform-provider-aws#16789]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon has added a preview release of a managed Grafana service. Many users who are currently using EKS are using self-hosted Grafana instances for metrics dashboards.

### References

https://aws.amazon.com/grafana/

* #16788 - Add support for Amazon Managed Service for Prometheus

**Comment by gdavison** [comment]
Thanks for submitting this, @abuchanan920. Since this is currently in preview, we will need to wait for AWS to release it in the [AWS SDK for Go](https://github.com/aws/aws-sdk-go)

**Comment by McTristan** [comment]
It is now GA!

**Comment by sobi3ch** [comment]
> Thanks for submitting this, @abuchanan920. Since this is currently in preview, we will need to wait for AWS to release it in the [AWS SDK for Go](https://github.com/aws/aws-sdk-go)

Prometheus is in preview but [it has](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/prometheus_workspace) already support.

**Comment by moserke** [comment]
Sadly the difference between Grafana and Prometheus is that AWS has not release an API for the Grafana service, however they have for Prometheus. https://docs.aws.amazon.com/sdk-for-go/api.  The terraform provider will not be able to implement this until AWS releases an API. If you have an account team it would be helpful to push on them to open a feature request or add you to it if it is already opened.

**Comment by damdo** [comment]
I've created an issue on the AWS SDK for Go to support Grafana here: https://github.com/aws/aws-sdk-go/issues/3894
You can react/comment on it to get more traction behind it.

**Comment by ksiebel-coachub** [comment]
Managed Grafana is now supported: https://docs.aws.amazon.com/sdk-for-go/api/service/managedgrafana/

**Comment by damdo** [comment]
Great news! cc. @gdavison

**Comment by tsposato** [comment]
https://docs.aws.amazon.com/sdk-for-go/api/service/managedgrafana/
Would be good to get this implemented now that the AWS SDK for Go supports it.

**Comment by sanarena** [comment]
Any update on this?

**Comment by qubusp** [comment]
Is there any development on that?

**Comment by AlexanderSchiff** [comment]
Starting to work on this...

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

**Comment by a-patel** [comment]
great news!
