### ISSUE TITLE
New Feature: AWS Managed Active Directory - Multi-Region replication

### ISSUE THREAD

**Issue by adrienp13** [hashicorp/terraform-provider-aws#16790]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has recently announced multi-region replication for [AWS Managed Microsoft Active Directory](https://aws.amazon.com/blogs/aws/multi-region-replication-now-enabled-for-aws-managed-microsoft-active-directory/).

AWS directory service interface (also available through [AWS CLI ](https://docs.aws.amazon.com/cli/latest/reference/ds/add-region.html)and API) allows to add one or more regions to be added to the directory service such that it is replicated across all regions.

Is this possible to enhance [resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/directory_service_directory) `aws_directory_service_directory` to support this new functionality ?

Alternatively, is it possible to create a new resource altogether ? 

The required parameters to add a new region are:

1. `directory-id`
2. `region-name` - the new region to add to the directory service
3. `vpc-settings` - **vpc id** and **subnet id(s)** of the new region
### New or Affected Resource(s)

* `aws_directory_service_directory` - if enhancement
* `aws_directory_service_directory_multi_region` - if new resource

### Potential Terraform Configuration

```hcl
resource "aws_directory_service_directory_multi_region" "this" {
   directory_service_id = aws_directory_service_directory.this.id
   region = "us-east-2"
   vpc_settings {
       vpc_id          = var.vpc_id
       subnet_ids      = var.subnet_ids    
   }  
}
```

### References

* https://aws.amazon.com/blogs/aws/multi-region-replication-now-enabled-for-aws-managed-microsoft-active-directory/
* https://docs.aws.amazon.com/cli/latest/reference/ds/add-region.html

**Comment by ewbankkit** [comment]
@adrienp13 Thanks for raising this issue.
It has already been noticed in #16455. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
