### ISSUE TITLE
AWS Cognito User Pool - Unable to set remember user's devices to "No"

### ISSUE THREAD

**Issue by chrispruitt** [hashicorp/terraform-provider-aws#16799]
In the AWS Console, there are 3 options. Here only two are currently available in the `device_configuration` block since this is a boolean.

```
device_only_remembered_on_user_prompt = true (console shows "User Opt In" selected)
device_only_remembered_on_user_prompt = false (console shows "Always" selected)
```

I would propose something like this to match the AWS Cognito console:
```
rememer_device = "ALWAYS | USEROPTIN | NO"
```

**Comment by gdavison** [comment]
Hi @chrispruitt. We implement the Terraform resources to match up with the underlying AWS API structures. In this case the three options are:

"Always"
```terraform
resource "aws_cognito_user_pool" "example" {
  ...
  device_configuration {
    device_only_remembered_on_user_prompt = false
  }
}
```

"User Opt In"
```terraform
resource "aws_cognito_user_pool" "example" {
  ...
  device_configuration {
    device_only_remembered_on_user_prompt = true
  }
}
```

"No": do not specify a `device_configuration` block, i.e.
```terraform
resource "aws_cognito_user_pool" "example" {
  ...
}
```

We can improve the documentation around this.

**Comment by chrispruitt** [comment]
Well, that makes perfect sense. Thank you for the explanation. @gdavison, feel free to close this unless you want to leave it open to track a documentation update.
