### ISSUE TITLE
aws_iam_access_key keys created with `state = "Inactive"` are in fact Active

### ISSUE THREAD

**Issue by grahamc** [hashicorp/terraform-provider-aws#16818]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v0.14.0
+ provider registry.terraform.io/nixpkgs/aws v3.21.0

Your version of Terraform is out of date! The latest version
is 0.14.2. You can update by downloading from https://www.terraform.io/downloads.html
```

(though I'm pretty sure the out of date terraform version has no bearing on this.)

### Affected Resource(s)

* aws_iam_access_key

### Terraform Configuration Files

```hcl
resource "aws_iam_user" "example" {
  name = "example-user"
}

resource "aws_iam_access_key" "example" {
  user = aws_iam_user.example.name
  status = "Inactive"
}
```

### Debug Output

I think this is the relevant part of the debug log: https://gist.github.com/grahamc/c10e3df343bd6edc6aaf5e93dd0cc95b unfortunately it would be quite difficult to post the entire log.

### Panic Output

n/a

### Expected Behavior

Terraform creates the example user, provisions the access key, and marks it as Inactive.

### Actual Behavior

The key is created but considered active until the second run.

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### Important Factoids

n/a

### References

n/a

**Comment by bflad** [comment]
Fix submitted: https://github.com/hashicorp/terraform-provider-aws/pull/17322

**Comment by grahamc** [comment]
Thanks!
