### ISSUE TITLE
aws_iam_role fails to modify-in-place if an added user is very new

### ISSUE THREAD

**Issue by grahamc** [hashicorp/terraform-provider-aws#16820]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v0.14.0
+ provider registry.terraform.io/nixpkgs/aws v3.21.0

Your version of Terraform is out of date! The latest version
is 0.14.2. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* aws_iam_role

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

#### Step one config:

```hcl
resource "aws_iam_user" "example" {
  name = "example-user"
}

data "aws_iam_policy_document" "assume-role" {
  statement {
    effect = "Allow"

    actions = [
      "sts:AssumeRole",
    ]

    principals {
      type = "AWS"
      identifiers = [ aws_iam_user.example.arn ]
    }
  }
}

resource "aws_iam_role" "example" {
  assume_role_policy = data.aws_iam_policy_document.assume-role.json
  max_session_duration = 3600
}
```

#### Step two config, adding a second user:

```hcl
resource "aws_iam_user" "example" {
  name = "example-user"
}

resource "aws_iam_user" "example2" {
  name = "example-user2"
}

data "aws_iam_policy_document" "assume-role" {
  statement {
    effect = "Allow"

    actions = [
      "sts:AssumeRole",
    ]

    principals {
      type = "AWS"
      identifiers = [
        aws_iam_user.example.arn,
        aws_iam_user.example2.arn
      ]
    }
  }
}

resource "aws_iam_role" "example" {
  assume_role_policy = data.aws_iam_policy_document.assume-role.json
  max_session_duration = 3600
}
```

### Debug Output

complete debug output: https://gist.github.com/grahamc/5e53ee2ae23ababce9760218b2910876

### Panic Output

n/a

### Expected Behavior

The role should be updated to include the newly created user.

### Actual Behavior

```
aws_iam_user.example2: Creating...
aws_iam_user.example2: Creation complete after 0s [id=example-user2]
data.aws_iam_policy_document.assume-role: Reading... [id=301115085]
data.aws_iam_policy_document.assume-role: Read complete after 0s [id=99189492]
aws_iam_role.example: Modifying... [id=terraform-20201217173629104500000001]

Error: Error Updating IAM Role (terraform-20201217173629104500000001) Assume Role Policy: MalformedPolicyDocument: Invalid principal in policy: "AWS":"arn:aws:iam::xxx:user/example-user2"
	status code: 400, request id: fdf1fb11-bcbe-455a-a7d1-93234b3f35a2
```

### Steps to Reproduce

1. `terraform apply` with the step one config
2. `terraform apply` with the step two config

### Important Factoids

n/a

### References

It appears the "create" implementation handles this error properly, but the "update" implementation doesn't attempt a retry.

**Comment by kgns** [comment]
We are also having this same issue. Is anyone using some kind of a workaround for this until a fix is pushed? I'm surprised so few people left a 👍 reaction, is this actually a problem or are we using resources improperly?
