### ISSUE TITLE
aws_wafv2_web_acl – Add Wildcard Search Functionality on Name

### ISSUE THREAD

**Issue by jdgoins** [hashicorp/terraform-provider-aws#16828]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Firewall Manager can be used to deploy WAFs to accounts in an AWS organization. The WAF name is automatically generated by AWS, making it unpredictable. In order to attach a WAF to one of my Terraform managed resources, I can use a `aws_wafv2_web_acl ` data lookup to reference it. That data lookup does not allow any form of wildcarding on the name, meaning I need to look up the WAF name manually and hardcode the value into the `aws_wafv2_web_acl ` lookup.

I would like a way of using wildcards in the `aws_wafv2_web_acl ` data lookup's name property. Similar functionality exists in the [aws_ami](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami) data resource.

### New or Affected Resource(s)

* aws_wafv2_web_acl

### Potential Terraform Configuration

```hcl
data "aws_wafv2_web_acl" "example" {
  filter {
    name   = "name"
    values = ["FMManagedWebACLV2mywafv2-policy*"]
  }
  scope = "CLOUDFRONT"
```

**Comment by Kimnor** [comment]
This functionality could also be useful on the `aws_waf_web_acl` as well.
