### ISSUE TITLE
Support for Route 53 Resolver DNSSEC validation

### ISSUE THREAD

**Issue by gazoakley** [hashicorp/terraform-provider-aws#16837]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Today, Amazon Web Services announced the launch of Domain Name System Security Extensions (DNSSEC) for Amazon Route 53. You can now enable DNSSEC signing for all existing and new public hosted zones, and enable DNSSEC validation for Amazon Route 53 Resolver. Amazon Route 53 DNSSEC provides data origin authentication and data integrity verification for DNS and can help customers meet compliance mandates, such as FedRAMP.

When you enable DNSSEC validation on the Route 53 Resolver in your VPC, it ensures that DNS responses have not been tampered with in transit. DNSSEC validation is available in all AWS regions where the Route 53 Resolver is available.

### New or Affected Resource(s)

* aws_route53_resolver_dnssec_config

### Potential Terraform Configuration

```hcl
resource "aws_route53_resolver_dnssec_config" "example" {
  resource_id = aws_vpc.example.id
  validation = "ENABLE"
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2020/12/announcing-amazon-route-53-support-dnssec/

**Comment by reedloden** [comment]
Other references:
* https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver-dnssec-validation.html
* Requires aws-sdk-go v1.36.11 (https://github.com/hashicorp/terraform-provider-aws/pull/16834)

**Comment by shuheiktgw** [comment]
Let me see if I can implement this!
