### ISSUE TITLE
EC2 Image Builder container images

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#16839]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Customers of EC2 Image Builder can now build and test container images compliant with the Open Container Initiative (OCI) specification.

### New or Affected Resource(s)

* `aws_imagebuilder_container_recipe`
* `aws_imagebuilder_container_recipe_policy`

### Potential Terraform Configuration

```hcl
resource "aws_imagebuilder_container_recipe" "example" {
  name             = "example-recipe"
  container_type   = "DOCKER"
  semantic_version = "1.0.0"
  ...
}

resource "aws_imagebuilder_container_recipe_policy" "example" {
  container_recipe_arn = aws_imagebuilder_container_recipe.example.arn

  policy = jsonencode({
  ...
  })
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/12/ec2-image-builder-supports-container-images/).
[User Guide](https://docs.aws.amazon.com/imagebuilder/latest/userguide/start-build-container-pipeline.html).

Requires [AWS SDK v1.36.11](https://github.com/aws/aws-sdk-go/releases/tag/v1.36.11):

* https://github.com/hashicorp/terraform-provider-aws/pull/16834

**Comment by lagrianitis** [comment]
The aws_imagebuilder_distribution_configuration needs to be refactor to support container distribution as well:
https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_Distribution.html#imagebuilder-Type-Distribution-containerDistributionConfiguration

**Comment by jussisallinen** [comment]
Would be great to see this make progress.

**Comment by zhginev** [comment]
> Would be great to see this make progress.

+1 , it's been almost a year now, this would have been ideal for an AWS native container factory implementation.

**Comment by josjaf** [comment]
+1

**Comment by kamilturek** [comment]
I'll take that one.
