### ISSUE TITLE
docs: aws_codeartifact_repository incorrect attribute reference or missing one

### ISSUE THREAD

**Issue by jack1902** [hashicorp/terraform-provider-aws#16842]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_codeartifact_repository

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This is  entirely related to the documentation but i kept referencing the `id` attribute which is actually the `arn`. This is incorrect as according to the documentation `id` should resolve to the repository name. After digging into the docs on the page, i could see `repository` and tried that. It worked :).

`id` -> `repository` 
<img width="703" alt="Screenshot 2020-12-18 at 18 31 08" src="https://user-images.githubusercontent.com/39212456/102648317-33b30180-415f-11eb-9ae8-82dd8d31f123.png">

### References

* #0000

**Comment by sumodirjo** [comment]
Hi @jack1902 ,
Can you provide sample code that I can use to reproduce the problem you're facing? Thank you.
