### ISSUE TITLE
More options for starting an instance refresh in ASG

### ISSUE THREAD

**Issue by cajund** [hashicorp/terraform-provider-aws#16849]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

$ terraform -v
Terraform v0.13.4
- Installed hashicorp/aws v3.22.0 (signed by HashiCorp)

### Affected Resource(s)

Referring to [16678](https://github.com/hashicorp/terraform-provider-aws/pull/16678) which was released last night. Is there a way to trigger an instance refresh when the AMI ID changes in the launch template? Is this only triggered when the `launch_template` value changes on the `aws_autoscaling_group` resource? Or can it be triggered when the launch template resource changes that the `aws_autoscaling_group.launch_template` refers to? 

Thanks.

### References

https://github.com/hashicorp/terraform-provider-aws/pull/16678

**Comment by kumaranbsundar** [comment]
One way you can force an instance refresh is via Tags.

I added the following tag to ASG resource
  tag {
    key                 = "AMI-ID"
    value               = var.AMI_ID
    propagate_at_launch = false
  }

and set the instance refresh to be trigger on tags like this....
  instance_refresh {
    strategy = "Rolling"
    preferences {
      min_healthy_percentage = 90
    }
    triggers = ["tag"]
  }

Now every time the AMI ID is updated via AMI_ID variable, it triggers the refresh automatically. 

Hope this helps!

**Comment by pascal-hofmann** [comment]
For me instance refresh works on changes to launch templates with these lines:
```
resource "aws_autoscaling_group" "this" {
  launch_template {
    id      = aws_launch_template.this.id
    version = aws_launch_template.this.latest_version
  }
  …
  instance_refresh {
    strategy = "Rolling"
    preferences {
      min_healthy_percentage = 50
    }
  }
}
```

**Comment by tx-kstav** [comment]
@pascal-hofmann does the above work for you if you change **just** the ami of the launch template a couple of times? 
@kumaranbsundar 's solution with tags works for me (for changing just the ami in the LT), but I have not had any luck without the tags.

**Comment by pascal-hofmann** [comment]
Yes, that works for me with just a changed AMI.

**Comment by kwunlyou** [comment]
> For me instance refresh works on changes to launch templates with these lines:
> 
> ```
> resource "aws_autoscaling_group" "this" {
>   launch_template {
>     id      = aws_launch_template.this.id
>     version = aws_launch_template.this.latest_version
>   }
>   …
>   instance_refresh {
>     strategy = "Rolling"
>     preferences {
>       min_healthy_percentage = 50
>     }
>   }
> }
> ```

Unfortunately, it doesn't here. I noticed the `version` is always "$Latest" and can't trigger instance refresh. Anyone else has the same problem?

**Comment by tx-kstav** [comment]
Yes @kwunlyou, even though pascal-hofmann says it's working for them, it doesn't for me. Using the ami_id in a tag, as a workaround that kumaranbsundar also mentioned above, is working fine for me until this is properly fixed.

**Comment by prachikhadke** [comment]
> One way you can force an instance refresh is via Tags.
> 
> I added the following tag to ASG resource
> tag {
> key = "AMI-ID"
> value = var.AMI_ID
> propagate_at_launch = false
> }
> 
> and set the instance refresh to be triggered on tags like this....
> instance_refresh {
> strategy = "Rolling"
> preferences {
> min_healthy_percentage = 90
> }
> triggers = ["tag"]
> }
> 
> Now every time the AMI ID is updated via AMI_ID variable, it triggers the refresh automatically.
> 
> Hope this helps!

What about if i'm using [aws_ami](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami) to pull in the ami_id dynamically in the autoscaling group. If I run terraform apply and a new ami is pulled and used in the autoscaling group, will it also, trigger the refresh? Do I still need tags? What other kind of triggers exist? I couldn't find more documentation.

```
  data "aws_ami" "example_ami" {

    # self means the current account

    most_recent      = true
    owners           = ["self"]

    filter {
      name = "state"
      values = ["available"]
    }

    filter {
      name   = "tag:Name"
      values = ["example-ami"]
    }
  }

  module "example_asg" {
    source                  = "terraform-aws-modules/autoscaling/aws"
    version                 = "4.1.0"
    image_id                = data.aws_ami.example_ami.image_id

    ...

  }

```

**Comment by carsondoesbusiness** [comment]
Any updates on this? I am facing the same issue where a launch_template update is not triggering a refresh
