### ISSUE TITLE
Support for SAML/AD principals in aws_lakeformation_permissions

### ISSUE THREAD

**Issue by chrisbulgaria** [hashicorp/terraform-provider-aws#16848]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The brand new aws_lakeformation_permissions does not seem to support SAML/AD principals (see console, the CLI accepts them without issues)

  on lakeformation.tf line 65, in resource "aws_lakeformation_permissions" "xxx":
  65:   principal   = "${local.saml_provider}:group/xxx"
Error: "principal" doesn't look like a user or role: "arn:aws:iam::yyyy:saml-provider/zzz:group/xxx"
  

### New or Affected Resource(s)

 aws_lakeformation_permissions

**Comment by chrisbulgaria** [comment]
Probably “validateprincipal” should be replaced by some lighter for this field - given the wider possibilities of what a LF principal can be - not only SAML/AD but as well Quicksight.

**Comment by colonmelvin** [comment]
How about support for IAM federated users? We're using `aws_cloudformation_stack` resources since `aws_lakeformation_permissions` doesn't support "arn:aws:iam::<account>:federated-user/<username>" principals.

**Comment by chrisbulgaria** [comment]
Hi , federated-user ? You mean SAml or AD ? The linked pull request supports all allowed principals , as listed here https://docs.aws.amazon.com/lake-formation/latest/dg/lf-permissions-reference.html
It just needs to be merged ....
Chris

**Comment by colonmelvin** [comment]
> Hi , federated-user ? You mean SAml or AD ? The linked pull request supports all allowed principals , as listed here https://docs.aws.amazon.com/lake-formation/latest/dg/lf-permissions-reference.html
> It just needs to be merged ....
> Chris

In this case, authentication is done via [GetFederationToken](https://docs.aws.amazon.com/STS/latest/APIReference/API_GetFederationToken.html) (FederatedUser), I was able to apply Lake Formation permissions via CLI using the ARN pattern `arn:aws:iam::account:federated-user/username`. I'm also working with the Lake Formation team to potentially add console support for federated users as to not be forced to use AWS CLI to manage them.

**Comment by YakDriver** [comment]
Related #16848
Related #17633
Related #18374
Related #18446
Related #18505
Related #19063
Related #19064
