### ISSUE TITLE
Amazon EBS Multi-Attach for io2 volumes

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#16847]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> You can now enable Provisioned IOPS SSD (io2) volumes for Amazon EBS Multi-Attach.
> You can enable Multi-Attach for io1 and io2 volumes during creation.
> You can also enable Multi-Attach for io2 volumes after they have been created.

### New or Affected Resource(s)

* [`aws_ebs_volume`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ebs_volume)

### Potential Terraform Configuration

```hcl
resource "aws_ebs_volume" "example" {
  type = "io2"

  multi_attach_enabled = true
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/12/multi-attach-support-now-available-on-amazon-ebs-provisioned-iops-volume-type-io2/).
[User Guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volumes-multi.html#working).

Requires [AWS SDK v1.36.12](https://github.com/aws/aws-sdk-go/releases/tag/v1.36.12):

* #16857

Relates:

* https://github.com/hashicorp/terraform-provider-aws/pull/16517
* https://github.com/hashicorp/terraform-provider-aws/pull/14894
* https://github.com/hashicorp/terraform-provider-aws/pull/13108

**Comment by DrFaust92** [comment]
Whats needed to be added here? `multi_attach_enabled` argument is already supported this seems like a doc change only.

**Comment by ewbankkit** [comment]
Currently multi-attach on io2 is available in `us-east-2`, `eu-central-1`, and `ap-south-1` regions.
This is probably not worth tackling until there is wider region support.
