### ISSUE TITLE
Terraform intermittently fails to deploy aws_elasticsearch_domain

### ISSUE THREAD

**Issue by lijok** [hashicorp/terraform-provider-aws#16864]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_elasticsearch_domain

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource aws_elasticsearch_domain this {
  advanced_options = {
    "indices.fielddata.cache.size"           = ""
    "rest.action.multi.allow_explicit_index" = "true"
  }
  domain_name           = "mydomain.com"
  elasticsearch_version = "7.7"


  cluster_config {
    dedicated_master_count   = 0
    dedicated_master_enabled = false
    instance_count           = 3
    instance_type            = "t3.small.elasticsearch"
    zone_awareness_enabled   = false
  }


  domain_endpoint_options {
    enforce_https       = true
    tls_security_policy = "Policy-Min-TLS-1-0-2019-07"
  }

  ebs_options {
    ebs_enabled = true
    volume_size = 100
    volume_type = "gp2"
  }

  snapshot_options {
    automated_snapshot_start_hour = 0
  }
}
```

### Actual Behavior

Intermittently, terraform gets stuck in "Still creating..." phase when deploying aws_elasticsearch_domain.
![image](https://user-images.githubusercontent.com/28689084/102790333-31d68180-439d-11eb-8c0f-794a7862fc15.png)

Somewhere half way through that, the cluster had finished deploying but terraform continued on "Still creating..."
Would capture debug output, but this happens maybe 1/10 deploys

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by xgt001** [comment]
Can second I faced this a couple of times too, with both `terraform apply` and `terraform destroy`. 
The actual domain is created/destroyed just fine in AWS from the terraform code but terraform doesn't seem to reflect state correctly. I will try to capture trace logs and update here
