### ISSUE TITLE
Can't get Name Servers with aws_route53_zone data

### ISSUE THREAD

**Issue by ichasco** [hashicorp/terraform-provider-aws#16862]
I can't get Name Servers from data aws_route53_zone

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.22.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/vault v2.17.0
```

### Affected Resource(s)

* data.aws_route53_zone

### Terraform Configuration Files

WORKS
```hcl
resource "aws_route53_zone" "primary" {
  name = "example.com"
}

output "name" {
  value = aws_route53_zone.primary.name_servers
}
```

DOESN'T WORKS
```hcl
data "aws_route53_zone" "devops-cross-domain" {
  name          =  "example.com."
  private_zone  = true
}

output "name2" {
  value = data.aws_route53_zone.devops-cross-domain.name_servers
}
```

### Expected Behavior

Get Name Servers with data

### Actual Behavior

```
  + name  = [
      + "ns-0.awsdns-00.com.",
      + "ns-1024.awsdns-00.org.",
      + "ns-1536.awsdns-00.co.uk.",
      + "ns-512.awsdns-00.net.",
    ]
  + name2 = []
```

Thanks!

**Comment by bflad** [comment]
Hi @ichasco 👋  Thank you for reporting this. Indeed there is a mismatch between the `aws_route53_zone` resource and data source with this attribute, but it appears to only be when the Hosted Zone is private. I will submit a fix shortly.

**Comment by bflad** [comment]
Fix submitted: https://github.com/hashicorp/terraform-provider-aws/pull/17002
