### ISSUE TITLE
aws_networkfirewall_rule_group unnecessary replacement

### ISSUE THREAD

**Issue by dthvt** [hashicorp/terraform-provider-aws#16868]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.22.0

### Affected Resource(s)

* aws_networkfirewall_rule_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_networkfirewall_rule_group" "permit_any" {
  capacity = 1
  description = "Permits all traffic"
  name = "permit-any"
  type = "STATEFUL"
  rule_group {
    rules_source {
      stateful_rule {
        action = "ALERT"
        header {
          source = "ANY"
          source_port = "ANY"
          destination = "ANY"
          destination_port = "ANY"
          protocol = "IP"
          direction = "ANY"
        }
        rule_option {
          keyword = "sid:1"
        }
      }
    }
  }
  tags = {
    Name = "Example permit-any stateful rule group"
  }
}

resource "aws_networkfirewall_firewall_policy" "example" {
  name = "example-inspection-vpc-policy"
  firewall_policy {
    stateless_default_actions          = ["aws:forward_to_sfe"]
    stateless_fragment_default_actions = ["aws:forward_to_sfe"]
    stateful_rule_group_reference {
      resource_arn = aws_networkfirewall_rule_group.permit_any.arn
    }
  }
  tags = {
    Name = "Example policy for global-network/modules/inspection_vpc"
  }
}
```

### Expected Behavior

Changing a stateful_rule block should not attempt to recreate the rule_group.  Attempting to modify a stateful_rule block currently introduces a deadlock condition where terraform cannot delete the rule group if it's in use, but cannot create a new version before destruction because each rule group must have a unique name.  While supporting name_prefix would also work around this issue, the UpdateRuleGroup API should be used to update the rule group in place when possible.

### Actual Behavior

Rule group destruction of an in-use rule group fails, causing terraform apply to fail.  Using lifecycle create_before_destroy fails because name must be unique.

### Steps to Reproduce

1. `terraform apply`
2. Change action to "PASS"
3. `terraform apply`

### References

* https://docs.aws.amazon.com/network-firewall/latest/APIReference/API_UpdateRuleGroup.html

**Comment by dthvt** [comment]
I'll add as an aside, that I can't seem to work around this by editing the rule in the web console because the web console sets any as "Any" and terraform (or the API) apparently expects "ANY".  So touching the rule in the console results in a rebuild as well.

**Comment by anGie44** [comment]
Hi @dthvt, thank you for raising this issue! Looks like updating in-place for when that rule-group field changes works fine, so I'll submit a fix w/the `ForceNew` removed from that block 👍 (I think at the time of writing that resource, that wasn't the case for some reason...)

**Comment by dthvt** [comment]
@anGie44 wouldn't surprise me if the API wasn't totally mature on release.  I know I had to open a ticket w/ AWS support because Network Firewall didn't actually work in one of the AZs in us-east-1 when they announced it's release.  Thanks for the quick turn around!
