### ISSUE TITLE
New Data Sources: `aws_ses_domain_identity` and `aws_ses_email_identity`

### ISSUE THREAD

**Issue by JessieAMorris** [hashicorp/terraform-provider-aws#16878]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I would like to be able to fetch AWS SES email identities and domain identities to attach policies to them dynamically.

### New or Affected Resource(s)

* data aws_ses_domain_identity
* data aws_ses_email_identity

### Potential Terraform Configuration

```hcl
data "aws_ses_domain_identity" "example" {
  domain = "example.com"
}

data "aws_iam_policy_document" "example" {
  statement {
    actions   = ["SES:SendEmail", "SES:SendRawEmail"]
    resources = [aws_ses_domain_identity.example.arn]

    principals {
      identifiers = ["*"]
      type        = "AWS"
    }
  }
}

resource "aws_ses_identity_policy" "example" {
  identity = data.aws_ses_domain_identity.example.arn
  name     = "example"
  policy   = data.aws_iam_policy_document.example.json
}
```

**Comment by anGie44** [comment]
Related https://github.com/hashicorp/terraform-provider-aws/issues/16877 https://github.com/hashicorp/terraform-provider-aws/issues/20318
