### ISSUE TITLE
make sweep tries to delete shared TransitGateways

### ISSUE THREAD

**Issue by tbugfinder** [hashicorp/terraform-provider-aws#16898]
https://github.com/hashicorp/terraform-provider-aws/blob/bebe732d7185320b303d0d14d3c19551213c1ba2/aws/resource_aws_ec2_transit_gateway_test.go#L61

While running `make sweep` deletion of a shared transit gateway of a different AWS account was tried and obviously failed. Shared TransitGateways should be skipped.

Thanks & Best

**Comment by tbugfinder** [comment]
Most probably we should add a check as done in route53_resolver_rule test.

https://github.com/hashicorp/terraform-provider-aws/blob/master/aws/resource_aws_route53_resolver_rule_test.go#L43-L47

**Comment by ewbankkit** [comment]
More generally we should ensure that [all shareable resources](https://docs.aws.amazon.com/ram/latest/userguide/shareable.html) follow the same pattern.

**Comment by tbugfinder** [comment]
Actually we might not know which AWS might also add to RAM in future. 
Wouldn't you think the R53R code would still be applicable?

**Comment by tbugfinder** [comment]
For general approach #16570 was referenced.
