### ISSUE TITLE
provider shared_credentials_file works only with plain access/secret key - not with anything advanced

### ISSUE THREAD

**Issue by chrisbulgaria** [hashicorp/terraform-provider-aws#16894]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

0.14.3   , 3.22
### Affected Resource(s)

Provider

### Terraform Configuration Files

```terraform
provider "aws" {
  profile                 = "k8s"
  shared_credentials_file = "/home/cloudshell-user/terraform/test/credentials"
}


resource "aws_s3_bucket" "test-lab-data1" {
  bucket = "test-lab-data2"
  acl    = "private"
}
```

credentials file:

```ini
[source]
credential_source = Ec2InstanceMetadata
role_arn = arn:aws:iam::xxx:role/yyyyyyyy

[k8s]
source_profile = source
role_arn = arn:aws:iam::zzzzzz:role/aaaaa
```

### Expected Behavior

The same provider config  and credential file works in all situations where the credentials are taken from the fallback to session credentials - i.e. either credential file in default location or AWS_SHARED_CREDENTIAL_FILE env variable set. 
However with the custom provider chain (which is the only thing which can work  with  shared_credentials_file , as the session knows nothing about this setting), the SharedCredentialProvider is used ( https://github.com/aws/aws-sdk-go/blob/master/aws/credentials/shared_credentials_provider.go) , which accepts only access/secret key, nothing else.
So above test case fails with "no valid credential sources for Terraform AWS Provider found". If access/secret key are placed into k8s profile - all works.

This should at least be documented - took me quite some time to troubleshoot it. But there may be situations like mine where I cant set an environment variable or put a file into the default location (well - need to think more about that .... ) , so maybe one could actually make this work ?  

Thanks,
Chris

**Comment by chrisbulgaria** [comment]
I see that the the Session actually would support a SharedConfigFiles parameter - which is however not used here : https://github.com/hashicorp/aws-sdk-go-base/blob/master/awsauth.go

Would suggest we initialise this from the shared_credentials_file, will try todo a PR for the aws-sdw-go-base

**Comment by chrisbulgaria** [comment]
see https://github.com/hashicorp/aws-sdk-go-base/pull/53

**Comment by gdavison** [comment]
Hi @chrisbulgaria, are you still seeing this error? If so, can you please try running Terraform with debug logging enabled? You can enable it by setting the environment variable `TF_LOG=DEBUG` (see https://www.terraform.io/docs/internals/debugging.html for more information)

**Comment by suciuandrei94** [comment]
Hello @gdavison , I am using terraform-provider-aws_v3.54.0_x5 and I still encountered this problem.
I solved it by setting environment variable `export AWS_SHARED_CREDENTIALS_FILE=../keys/terraform-$ENVIRONMENT`.

I had a .tfvars file which specified `shared_credentials_file = "../keys/terraform-dev"` but to no success.

**Comment by lorengordon** [comment]
I don't believe those options are valid for the credentials file. The credentials file is _only_ supposed to contain sensitive credential info, e.g. the access key and secret key.

Try using `AWS_CONFIG_FILE` instead, https://docs.aws.amazon.com/sdkref/latest/guide/environment-variables.html. Ideally the aws provider would accept an attribute, `aws_config_file` as well...

**Comment by suciuandrei94** [comment]
I am not using any options apart from `[default]
aws_access_key_id = {AWS_ACCESS_KEY}
aws_secret_access_key = {AWS_SECRET_KEY}` 

And it still won't work for me, unless I set the environment variable

**Comment by lorengordon** [comment]
@suciuandrei94 yes, sorry, if _that_ isn't working, that sounds like a bug in the provider argument `shared_credentials_file`.

I was actually referring to the options the OP was specifying:

```
[source]
credential_source = Ec2InstanceMetadata
role_arn = arn:aws:iam::xxx:role/yyyyyyyy

[k8s]
source_profile = source
role_arn = arn:aws:iam::zzzzzz:role/aaaaa
```

Those options are generally supported only in the shared _config_ file, not in the shared _credential_ file. It may work in some cases for historical/legacy reasons, but support across each SDK will be inconsistent because it is not part of the design for the credentials file.

**Comment by gdavison** [comment]
With the release of version 4 of the provider, we now have support for indicating both the shared configuration and credentials files.

@suciuandrei94, if you're still seeing your problem, can you please open a new issue and show both the provider configuration block and the .tfvars?
