### ISSUE TITLE
Unable to create ASG policy with Target tracking configurations

### ISSUE THREAD

**Issue by rajivreddy** [hashicorp/terraform-provider-aws#16915]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```bash
$ terraform version 
Terraform v0.12.29
+ provider.aws v3.22.0
```

### Affected Resource(s)

* aws_autoscaling_policy.*

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
   region = "us-west-2"
}
resource "aws_autoscaling_policy" "bat" {
  name                   = "foobar3-terraform-test"
  scaling_adjustment     = 4
  adjustment_type        = "ChangeInCapacity"
  cooldown               = 300
  policy_type  = "TargetTrackingScaling"
  autoscaling_group_name = aws_autoscaling_group.bar.name
  target_tracking_configuration {
    predefined_metric_specification {
      predefined_metric_type = "ASGAverageCPUUtilization"
    }

    target_value = 40.0
  }

  target_tracking_configuration {
    customized_metric_specification {
      metric_dimension {
        name  = "ClusterName"
        value = "staging"
      }

      metric_name = "MemoryReservation"
      namespace   = "AWS/ECS"
      statistic   = "Maximum"
    }

    target_value = "75"
  }


}
```

### Debug Output

```logs
terraform plan 

Error: List longer than MaxItems

  on main.tf line 4, in resource "aws_autoscaling_policy" "bat":
   4: resource "aws_autoscaling_policy" "bat" {

Attribute supports 1 item maximum, config has 2 declared
```

### Expected Behavior

Terraform should able to create Scaling policies which is defined in resoures 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_policy

### Actual Behavior

Terraform complains that it can have only 1 target tracking configuration in an scaling policy

### Steps to Reproduce

1. `terraform plan`

### References
**Doc Link:**
 https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_policy

Either documention define 2 set of exampels, one with `predefined_metric_specification` and another example with `customized_metric_specification`.

**Comment by rajivreddy** [comment]
Any update on this issue?

**Comment by breathingdust** [comment]
Hi @rajivreddy 👋  Unfortunately our documentation specifies 2 `target_tracking_configurations` blocks however the upstream AWS API only supports (and one of customized or predefined specifications can be used)

https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_PutScalingPolicy.html
https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_TargetTrackingConfiguration.html

We will need to fix the documentation example to accurately represent what is possible given the underlying API
