### ISSUE TITLE
aws_lambda_invocation result attribute escapes already escaped characters

### ISSUE THREAD

**Issue by vladimirtiukhtin** [hashicorp/terraform-provider-aws#16912]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/archive v2.0.0
+ provider registry.terraform.io/hashicorp/aws v3.22.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/tls v3.0.0
```

### Affected Resource(s)

* aws_lambda_invocation

### Expected Behavior

When Lambda returns json (a string effectively), AWS escapes quotas - there is no need to double escape it. This results in having three backslashes in "result" attribute and makes it impossible to use with "jsondecode" function, which in turn makes it impossible to reference any keys from the json

### Actual Behavior

```
test = "\"{\\\"tasks\\\":[{\\\"attachments\\\":[{\\\"id\\\":\\\"......
```

### Steps to Reproduce

Simply create a lambda which returns json (not  dict), then reference its result in any output through aws_lambda_invocation data resource like this
```
output "test" {
  value = data.aws_lambda_invocation.test.result
}
```

**Comment by breathingdust** [comment]
Hi @vladimirtiukhtin 👋 Apologies for the delay in repsonse. The data source returns the result from AWS verbatim, there should be no extra escaping occurring. Are you able to confirm the AWS CLI response differs from the one you get with the provider?

https://github.com/hashicorp/terraform-provider-aws/blob/53a32d179f05700b78f285f079ad52a4218a26f4/aws/data_source_aws_lambda_invocation.go#L65
