### ISSUE TITLE
Error "image_uri" is not expected here.

### ISSUE THREAD

**Issue by nirsv** [hashicorp/terraform-provider-aws#16911]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.25
+ provider.aws v3.5.0
### Affected Resource(s)

* aws_lambda_function
### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_lambda_function" "my-dockerized-lambda" {
  image_uri                      = var.lambda_image_uri
  description                    = "Lambda using docker image"
  function_name                  = "my-lambda-function"
  role                           = aws_iam_role.lambda-role.arn
  handler                        = "my_lambda.lambda_handler"
  runtime                        = "python3.6"
  timeout                        = "780"
  memory_size                    = "512"
  reserved_concurrent_executions = "-1"
  publish                        = false

  vpc_config {
    subnet_ids         = var.subnets
    security_group_ids = [data.aws_security_group.default_sg.id]
  }

  environment {
    variables = merge(
      var.env_vars
    )
  }
}
```

### Expected Behavior

I expect the lambda to be created (at least the plan to succeed)

### Actual Behavior
Error: Unsupported argument
An argument named "image_uri" is not expected here.

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by ewbankkit** [comment]
@nirsv Thanks for raising this issue.
AWS Lambda container image support (and the `image_uri` attribute) was added in https://github.com/hashicorp/terraform-provider-aws/pull/16512 and released in [v3.19.0](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md#3190-december-01-2020) of the Terraform AWS Provider.
You will need to upgrade to at least that version of the provider for the functionality you require.
