### ISSUE TITLE
data/aws_lambda_function fails to get container image based lambda

### ISSUE THREAD

**Issue by mousiefasil** [hashicorp/terraform-provider-aws#16945]
Hi everyone,

I have a project where I am using container images to build Lambdas, in a second project I am want to retrieve them via data aws_lambda_function, but i get a 400 with the error *Code signing is not supported for functions created with container images.*

I was able narrow the issue down to the data aws_lambda_function part, this issue prevails over mutliple version of terraform so I guess it is a bug in the provider.aws.

Thx in advance.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.12.6
+ provider.aws v3.22.0

Your version of Terraform is out of date! The latest version
is 0.14.3. You can update by downloading from www.terraform.io/downloads.html

and

Terraform v0.14.2
+ provider registry.terraform.io/hashicorp/aws v3.22.0

Your version of Terraform is out of date! The latest version
is 0.14.3. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

* data aws_lambda_function

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

please see below

### Expected Behavior

return of an aws_lambda_function object.

### Actual Behavior

Error: error getting Lambda Function (XXX) Code Signing Config: InvalidParameterValueException: Code signing is not supported for functions created with container images.
```
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "************"
  },
  Message_: "Code signing is not supported for functions created with container images.",
  Type: "User"
}
```
### Steps to Reproduce

Simplest use case:
```
main.tf
---
provider "aws" {
    region = "eu-central-1"
}

data "aws_lambda_function" "lambda" {
    function_name = "foo"
}
---
```
1. `terraform init`
2. `terraform plan`

### References

I saw that the aws documentation mentions that code signer ist not working with container image based lambdas.
[Link](https://docs.aws.amazon.com/lambda/latest/dg/configuration-codesigning.html)

* #0000

**Comment by dmccaffery** [comment]
Recommend using terraform_remote_state via an output on the root module that creates the lambda as a workaround for now (if not a best practice).

😃

**Comment by mousiefasil** [comment]
I am not sure if calling the terraform_remote_state is best practice. However my current workaround is simple, I just created a variable for the name of the lambda in my second project.
