### ISSUE TITLE
docs/provider: Update resource timeouts links

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#16949]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The upstream Terraform CLI documentation for resource timeouts has been shuffled from its previous location. While the old link is valid, there is only a "manual redirect" link to the correct location there now. https://github.com/hashicorp/terraform-provider-aws/pull/16899 includes fixes for one style of these links, however there are some others as well.

Documentation links needing update:

* `/docs/configuration/resources.html#timeouts` -> `https://www.terraform.io/docs/configuration/blocks/resources/syntax.html#operation-timeouts`

### References

* https://github.com/hashicorp/terraform-provider-aws/pull/16899
* https://www.terraform.io/docs/configuration/resources.html#timeouts
* https://www.terraform.io/docs/configuration/blocks/resources/syntax.html#operation-timeouts

**Comment by SijmenHuizenga** [comment]
I will create a pr

**Comment by SijmenHuizenga** [comment]
PR Created. This issue description part:

>  `/docs/configuration/resources.html#timeouts` -> `https://www.terraform.io/docs/configuration/blocks/resources/syntax.html#operation-timeouts`

inspired me to also changed a bunch of relative links to absolute links. Hope that's oke!
