### ISSUE TITLE
aws_imagebuilder_image_recipe should allow WorkingDirectory as parameter

### ISSUE THREAD

**Issue by schabert** [hashicorp/terraform-provider-aws#16946]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
The Resource Recipe allows a parameter "workingDirectory" but its missing in the module.

The CLI/API supports this with the variable `working-directory`

### New or Affected Resource(s)

* aws_imagebuilder_image_recipe

### Potential Terraform Configuration

```hcl
resource "aws_imagebuilder_image_recipe" "main" {
  description       = "Image Builder Recipe"
  name              = "test1"
  parent_image      = "arn:aws:imagebuilder:us-west-2:aws:image/windows-server-2019-english-core-base-x86/x.x.x"
  working_directory = "/workspace"
  version           = "1.0.0"

  # root disk
  block_device_mapping {
    device_name = "/dev/sda1"

    ebs {
      delete_on_termination = true
      encrypted             = true
      kms_key_id            = "alias/aws/ebs"
      volume_size           = 40
      volume_type           = "gp2"
    }
  }
  component {
    component_arn = "arn:aws:imagebuilder:us-west-2:aws:component/update-windows/x.x.x"
  }
}
```

### References

* https://docs.aws.amazon.com/cli/latest/reference/imagebuilder/create-image-recipe.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/imagebuilder/#Imagebuilder.CreateImageRecipe

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 3.23.0 of the Terraform AWS Provider, later this week. Thanks to @schabert for the implementation.
