### ISSUE TITLE
SQS redrive policy JSON shows whitespace difference with Localstack

### ISSUE THREAD

**Issue by jessemyers** [hashicorp/terraform-provider-aws#16964]
While testing SQS dead letter queue configurations with a Localstack endpoint, I notice that the queue's redrive policy is treated as opaque text rather than structured JSON. As a result, whitespace differences between Localstack and AWS result in terraform showing spurious diffs. IMO, this is a bug on both sides: terraform should understand that the redrive policy is structured data (see #811) and Localstack should be more faithful to AWS behavior, even though whitespace is legal in JSON.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```sh
$ terraform -v
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/aws v3.22.0
```

### Affected Resource(s)

* `aws_sqs_queue`

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  access_key                  = ""
  region                      = "us-west-2"
  s3_force_path_style         = true
  secret_key                  = ""
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    sqs = "http://localhost:4566"
  }
}

resource "aws_sqs_queue" "dead_letter_queue" {
  name                       = "example-DLQ"
  message_retention_seconds  = 14 * 24 * 60 * 60
  visibility_timeout_seconds = 1
}

resource "aws_sqs_queue" "queue" {
  name                       = "example"
  delay_seconds              = 0
  message_retention_seconds  = 14 * 24 * 60 * 60
  visibility_timeout_seconds = 1

  redrive_policy = jsonencode({
    deadLetterTargetArn = aws_sqs_queue.dead_letter_queue.arn
    maxReceiveCount     = 3
  })

  depends_on = [
    aws_sqs_queue.dead_letter_queue,
  ]
}
```

I am also running Localstack using this `docker-compose.yml`:

```yaml
version: '3.8'

volumes:
  localstack-data:

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack
    network_mode: bridge
    ports:
      - 4566:4566
    environment:
      - DEFAULT_REGION=us-west-2
      - SERVICES=sns,sqs
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - localstack-data:/tmp/localstack
```

### Debug Output

https://gist.github.com/jessemyers/ad334b17d5fdcf332b3b8caf4e0f6a58

### Expected Behavior

No diff shown.

### Actual Behavior

A diff including whitespace. 

### Steps to Reproduce

1. `terraform apply` (once to create queues)
2. `terraform plan` (shows spurious diff)
3. `terraform apply` (attempt to apply change; this has no effect)
4. `terraform plan` (still shows spurious diff)

### Important Factoids

Localstack implements its SQS simulation using Python; the default Python JSON encoder includes whitespace after separators (`:`, `,`); the tail end of the `apply` output shows JSON differences that match this sort of whitespace:

```
2021/01/04 14:44:52 [WARN] Provider "registry.terraform.io/hashicorp/aws" produced an unexpected new value for aws_sqs_queue.queue, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .redrive_policy: was cty.StringVal("{\"deadLetterTargetArn\":\"arn:aws:sqs:us-west-2:000000000000:example-DLQ\",\"maxReceiveCount\":3}"), but now cty.StringVal("{\"deadLetterTargetArn\": \"arn:aws:sqs:us-west-2:000000000000:example-DLQ\", \"maxReceiveCount\": 3}")
      - ```

### References

* #811

**Comment by adrian-hippo** [comment]
+1

**Comment by ewbankkit** [comment]
Should be fixable by adding `DiffSuppressFunc: suppressEquivalentJsonDiffs` to

https://github.com/hashicorp/terraform-provider-aws/blob/eb5174ab89e852fa16f662e6c07008f350a3a94f/aws/resource_aws_sqs_queue.go#L97-L105
