### ISSUE TITLE
ARN attribute may contain incorrect AWS account ID for shareable resources

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#16978]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

AWS Provider **v3.22.0**.

Various resources (and data sources) for a number of AWS services include a computed `arn` resource that is synthesized in the resource's `Read` code rather than being set from relevant AWS API call's response (as the AWS API response does not include an ARN property). [This page](https://docs.aws.amazon.com/service-authorization/latest/reference/reference_policies_actions-resources-contextkeys.html) is a good starting point for finding the correct ARN format for such resources.
For [shareable resources](https://docs.aws.amazon.com/ram/latest/userguide/shareable.html) the account ID should be [the ID of the AWS account that owns the resource](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arns-syntax), however in many such cases we are incorrectly setting the account ID field to the ID of the AWS account that is running Terraform. While these two account IDs are equal for resources that are actually created, they will be different for data sources (and resources that adopt resources, such as `aws_default_route_table`) if Terraform is run in the AWS account that the resource is shared into I.e. NOT the account that the corresponding resource was created in and subsequently shared from).

A typical incorrect pattern is

https://github.com/hashicorp/terraform-provider-aws/blob/04e3b2741736d9a0c7c6a61b8ecd221e52e0cf78/aws/data_source_aws_vpc.go#L192-L199

whereas a correct pattern is:

https://github.com/hashicorp/terraform-provider-aws/blob/04e3b2741736d9a0c7c6a61b8ecd221e52e0cf78/aws/data_source_aws_security_group.go#L102-L109

(apart from from the raw pointer dereference: https://github.com/hashicorp/terraform-provider-aws/issues/12992).

### Affected Resource(s)

* [x] [`aws_ec2_capacity_reservation`](https://github.com/hashicorp/terraform-provider-aws/pull/17129)
  * Add `owner_id`
  * Correct `arn` - can be API response

* [x] [`aws_licensemanager_license_configuration`](https://github.com/hashicorp/terraform-provider-aws/pull/17160)
  * Add `owner_account_id`
  * Add [`arn`](https://docs.aws.amazon.com/service-authorization/latest/reference/list_awslicensemanager.html#awslicensemanager-resources-for-iam-policies)

* [x] [`aws_ami` (and friends)](https://github.com/hashicorp/terraform-provider-aws/pull/17178)
  * Add `owner_id`

* [x] [`aws_vpc`/`aws_default_vpc`](https://github.com/hashicorp/terraform-provider-aws/pull/17729)
  * Correct `arn`

* [x] [`aws_ec2_carrier_gateway`](https://github.com/hashicorp/terraform-provider-aws/pull/17736)
  * Correct `arn`

* [x] [`aws_vpc_dhcp_options`](https://github.com/hashicorp/terraform-provider-aws/pull/17758)
  * Correct `arn`

* [x] [`aws_vpc_endpoint`](https://github.com/hashicorp/terraform-provider-aws/pull/17782)
  * Correct `arn`

* [x] [`aws_internet_gateway`](https://github.com/hashicorp/terraform-provider-aws/pull/17803)
  * Correct `arn`

* [x] [`aws_network_acl`/`aws_default_network_acl`](https://github.com/hashicorp/terraform-provider-aws/pull/17834)
  * Correct `arn`

* [x] [`aws_route_table`](https://github.com/hashicorp/terraform-provider-aws/pull/17001)/[`aws_default_route_table`](https://github.com/hashicorp/terraform-provider-aws/pull/16979)
  * Correct `arn`

* [x] [`aws_ec2_traffic_mirror_session`](https://github.com/hashicorp/terraform-provider-aws/pull/17938)
  * Add `owner_id`
  * Correct `arn`

* [x] [`aws_ec2_traffic_mirror_target`](https://github.com/hashicorp/terraform-provider-aws/pull/17973)
  * Add `owner_id`
  * Correct `arn`

Relates: https://github.com/hashicorp/terraform-provider-aws/issues/13624.

**Comment by shuheiktgw** [comment]
- aws_ec2_capacify_reservation: https://github.com/hashicorp/terraform-provider-aws/pull/17129

**Comment by shuheiktgw** [comment]
- aws_licensemanager_license_configuration: https://github.com/hashicorp/terraform-provider-aws/pull/17160

**Comment by shuheiktgw** [comment]
- aws_ami: https://github.com/hashicorp/terraform-provider-aws/pull/17178

**Comment by shuheiktgw** [comment]
- aws_vpc: https://github.com/hashicorp/terraform-provider-aws/pull/17729

**Comment by shuheiktgw** [comment]
- aws_ec2_carrier_gateway: https://github.com/hashicorp/terraform-provider-aws/pull/17736

**Comment by shuheiktgw** [comment]
- aws_vpc_dhcp_options: https://github.com/hashicorp/terraform-provider-aws/pull/17758

**Comment by shuheiktgw** [comment]
- aws_vpc_endpoint: https://github.com/hashicorp/terraform-provider-aws/pull/17782

**Comment by shuheiktgw** [comment]
- aws_internet_gateway: https://github.com/hashicorp/terraform-provider-aws/pull/17803

**Comment by shuheiktgw** [comment]
- aws_network_acl/aws_default_network_acl: https://github.com/hashicorp/terraform-provider-aws/pull/17834

**Comment by shuheiktgw** [comment]
- aws_ec2_traffic_mirror_session: https://github.com/hashicorp/terraform-provider-aws/pull/17938

**Comment by shuheiktgw** [comment]
- aws_ec2_traffic_mirror_target: https://github.com/hashicorp/terraform-provider-aws/pull/17973

The last one! 🎉 Thank you for your review, @ewbankkit!

**Comment by breathingdust** [comment]
Hi @shuheiktgw! Thanks for all your work on this issue. 🚀  I've been trying to find your contact details, if you had a moment would you be able to email me at the address in my profile? Thank you!

**Comment by shuheiktgw** [comment]
@breathingdust  Sure, I just sent you an email so would you check your inbox?

**Comment by ewbankkit** [comment]
The final affected resource will be corrected with Terraform AWS Provider **v3.35.0**.
