### ISSUE TITLE
aws_cloudwatch_event_rule does not support EventBus ARNs in event_bus_name 

### ISSUE THREAD

**Issue by georgealton** [hashicorp/terraform-provider-aws#16973]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```sh
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/aws v3.22.0
```

### Affected Resource(s)

* aws_cloudwatch_event_rule

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.22.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_cloudwatch_event_rule" "example_event_bus_rule" {
  name           = "example"
  event_bus_name = "arn:aws:events:us-east-1:123456789012:event-bus/default"
  event_pattern  = ""
}
```

### Expected Behavior

The plan should succeed. AWS recently allowed Rules to be put directly against Event Buses in other Accounts.

### Actual Behavior

Terraform Plan rejects the an `event_bus_name` of `arn:aws:events:us-east-1:123456789012:event-bus/default` when it doesn't match its expected format.  

```sh
Error: expected value of event_bus_name to match regular expression "^[a-zA-Z0-9._\\-]+$", got arn:aws:events:us-east-1:123456789012:event-bus/default

  on example.tf line 16, in resource "aws_cloudwatch_event_rule" "example_event_bus_rule":
  16:   event_bus_name = "arn:aws:events:us-east-1:123456789012:event-bus/default"
```

The AWS API for PutRule now supports an extended Regex, that allows either an ARN or an EventBus Name
`(arn:aws[\w-]*:events:[a-z]{2}-[a-z]+-[\w-]+:[0-9]{12}:event-bus\/)?[/\.\-_A-Za-z0-9]+`

### Steps to Reproduce

1. `terraform plan`

### References

https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutRule.html#API_PutRule_RequestSyntax
https://aws.amazon.com/blogs/compute/simplifying-cross-account-access-with-amazon-eventbridge-resource-policies/

**Comment by grstavares** [comment]
The same problem happens when we try to map the rule to an Event Bridge Partner bus, like:

`aws.partner/mongodb.com/stitch.trigger/variablestringhere`

The API and mentioned regex support the value but it is not accepted by it not pass the provider input validation.

**Comment by AlexBatorykLeliw** [comment]
Any movement on this issue? We have the exact same problem as @grstavares

**Comment by mdragilev** [comment]
Added a PR for this issue: https://github.com/hashicorp/terraform-provider-aws/pull/18383

**Comment by gdavison** [comment]
This was resolved by #18143, which will be released in v3.36.0 later this week

**Comment by prashant-tyagi-cko** [comment]
This fixed the Eventbus name error but now I get another error *while setting ID* - "error reading CloudWatch Events Rule (aws.partner/appflow/salesforce.com/xxx/foo-eventbus/bar-rule): unexpected format for ID ("aws.partner/appflow/salesforce.com/xxx/foo-eventbus/bar-rule"), expected <event-bus-name>/<rule-name> or <rule-name>"

Could this be due to RuleParseID, which expects only two values separated by "/" - https://github.com/hashicorp/terraform-provider-aws/blob/03072134f5110be18b431bdb2d3e1758793098f9/aws/internal/service/cloudwatchevents/id.go#L40

**Comment by knbrlo** [comment]
Thanks @prashant-tyagi-cko, also facing the same issue when setting the rule as well.
