### ISSUE TITLE
Route53 module doesn't validate characters in domain names but should prohibit e.g.: _ underscore

### ISSUE THREAD

**Issue by wkoszek** [hashicorp/terraform-provider-aws#16992]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions. They generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.3
Terraform v0.14.2

### Affected Resource(s)

Domain names configured with Route53 module.

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_route53_record" "cirunner" {
  zone_id = aws_route53_zone.segmed_ai.zone_id
  name    = "ci_runner" 
  type    = "A"
  ttl     = "1799"
  records = [aws_eip.cirunner_ip.public_ip]
}
```

### Expected Behavior

I'd love `terraform plan` to alert me when I'm doing stupid stuff. We have a simple CI flow where every branch pushes as Pull-Request get "terraform plan" run, and we run "terraform apply" on merge. It's a little annoying to see "terraform plan" succeeding, but later on "apply" failing.

### Actual Behavior

Route53 should prevent invalid characters from being applied to domain names.

`terraform plan` is perfectly happy with it. `terraform apply` fails.

### Steps to Reproduce

Just try to create domain names with `_` in them. 

1. `terraform plan` <- plan somehow is perfectly happy with it. I guess we don't really validate things API calls will validate for us
2. `terraform apply` <- this will hit AWS Route53 API, and this won't be happy with an underscore

### Important Factoids

We should probably filter all special characters:

https://www.saveonhosting.com/scripts/index.php?rp=/knowledgebase/52/What-are-the-valid-characters-for-a-domain-name-and-how-long-can-a-domain-name-be.html

### References

* #0000

**Comment by bflad** [comment]
Hi @wkoszek 👋  Thank you for raising this.

According to the [Route 53 documentation](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DomainNameFormat.html#domain-name-format-hosted-zones) and from my past operational experience, the underscore (`_`) character is allowed by the Route 53 API and in some cases actually required (such as SRV records). If you are running into a particular issue, we will need to see the error output and potentially the debug API request and response logging from the provider (e.g. `TF_LOG=debug terraform apply`) .

Given that we would not want to introduce "matching"/"positive" schema validation in this case that prevents valid inputs and the complexity of the validation that would be necessary to properly implement ASCII escape code and Punycode validation to match the API, I'm going to close this for now. If there are specific "negative" schema validations that should occur (ASCII spaces are noted in the documentation), then it might be best to have an issue specifically on those case(s). 👍
