### ISSUE TITLE
Placement GroupName being specified causing conflict with HostResourceGroupArn

### ISSUE THREAD

**Issue by mkey0bc** [hashicorp/terraform-provider-aws#16995]
AWS_INSTANCE resource instance fails to deploy to a dedicated host resource group using an AMI registered with license manager.

It appears that the placement property GroupName is being set even though the HostResourceGroupArn property is being specified by the registered AMI from license manager.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.14.3

### Affected Resource(s)

* aws v3.22.0

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  profile = "my-profile"
  region  = "us-west-2"
}

resource "aws_instance" "hosttest" {
  ami           = "ami-###########"
  instance_type = "r5.large"
  subnet_id = "subnet-############"

  tags = {
    Name = "host-test"
  }
}
```

### Expected Behavior

EC2 instance deployed on dedicated host resource group.

### Actual Behavior

```hcl
Error: Error launching source instance: InvalidParameterValue: Invalid value 'When HostResourceGroupArn is specified, Placement GroupName cannot be set.' for groupName.
        status code: 400, request id: 92732a93-966a-4123-96aa-08dcac07e380
```

### Steps to Reproduce

1. `terraform apply`

### References

* [#15785]

**Comment by flaviorodrigo** [comment]
This won't close this issue as we should be able to launch aws_instance without a Launch Template.

**Comment by YakDriver** [comment]
The crux of the problem results from`placement_group` (`ec2.RunInstanceInput.Placement.GroupName`) always being set in API calls, even if to an empty string, if instance interruption behavior was not set or set to terminate. `ec2.RunInstanceInput.Placement.GroupName` cannot be set if launching in a (dedicated) host resource group. Even though the `host_resource_group_arn` argument was not previously available, the association can be done implicitly based on the AMI ID and the host resource group being set to "Allocate hosts automatically."

The solution is ensure that if `placement_group` is not set, `ec2.RunInstanceInput.Placement.GroupName` is also not set.
