### ISSUE TITLE
Document aws_default_route_table warning on aws_main_route_table_association

### ISSUE THREAD

**Issue by JEBoothjr** [hashicorp/terraform-provider-aws#1699]
A few months back while I was learning Terraform, I set up the route tables and used the aws_default_route_table. The document for this clearly states that "It is recommended you do not use both aws_default_route_table to manage the default route table and use the aws_main_route_table_association, due to possible conflict in routes."

Recently, I realized that I wanted to change the main route table association. So I looked into the docs and used aws_main_route_table_association. There is no warning or reference in this doc to havoc that can happen when used with aws_default_route_table. It really messed things up, but I was able to recover. I did not think to go back to the aws_default_route_table documentation. It would have been nice to see this warning or a link on the aws_main_route_table_association doc as well.

**Comment by alvarodelvalle** [comment]
Hi 👋🏽 I would like to work on this documentation. I will submit a PR soon.
