### ISSUE TITLE
How to Create Terraform Lambda Layer by specifiying ARN

### ISSUE THREAD

**Issue by mohamednazarae** [hashicorp/terraform-provider-aws#17008]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

How to Create Terraform Lambda Layer by specifying ARN

### New or Affected Resource(s)

aws_lambda_layer_version

### Potential Terraform Configuration

```hcl
data “archive_file” “converttopdf_lambda” {
type = “zip”
source_dir = “./data/converttopdf”
output_path = “converttopdf.zip”
}

resource “aws_lambda_layer_version” “lambda_converttopdf_lambda” {
layer_name = var.converttopdf_layername
filename = “${data.archive_file.converttopdf_lambda.output_path}”
}

resource “aws_lambda_function” “converttopdf_lambda_funcn” {
filename = "${data.archive_file.converttopdf_lambda.output_path}"
function_name = "copi_${var.environment}_converttopdf"
role = aws_iam_role.role_lambda.arn
handler = var.converttopdf_lambda_handler
runtime = var.converttopdf_lambda_runtime
publish = var.converttopdf_lambda_publish
timeout = var.lambdatimeout
memory_size = var.lambda_memorysize
layers = [aws_lambda_layer_version.lambda_converttopdf_lambda.arn]
}
```

### References

Please refer the below screenshot, that I used to create Lambda Layer using AWS console, the same I am trying to create via Terraform.

![image](https://user-images.githubusercontent.com/70500230/103911950-b01c7d00-512c-11eb-94fa-1328751c6830.png)

**Comment by anGie44** [comment]
Hi @mohamednazarae, thank you for raising this issue. From the configuration you've provided, I believe you're on the right track in specifying the `layers` argument with the value extracted from the `aws_lambda_layer_version.lambda_converttopdf_lambda.arn`. Given the configuration you've provided, what output are seeing after a `terraform apply` ?

**Comment by mohamednazarae** [comment]
Its successfully applied there is no error in terraform apply and I can see Lambda layer created. But did you saw the AWS screenshot that I added my first post? I want to have one new Argument Reference to specify other lambda ARN while creating Lambda Layer. 

Please help and add new argument or please let me know shall I use existing argument to achieve the same?

Thanks

**Comment by mohamednazarae** [comment]
I just found that we dont want to create new layer, just we can specify libre office ARN directly in Lambda configuration in terraform. Hence closing this.
