### ISSUE TITLE
docs: aws_docdb_cluster documentation is missing preferred_maintenance_window

### ISSUE THREAD

**Issue by nerdingasnate** [hashicorp/terraform-provider-aws#17019]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)
  * aws_docdb_cluster

### Actual Behavior
Not sure if this is correct location to report, but the documentation in https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/docdb_cluster is missing preferred_maintenance_window parameter.

I have wasted quite a bit of time trying to find how to set up preferred_maintenance_window for the cluster, while it was actually just missing from the resource documentation. Hope others wont have to do it.

### References

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/docdb_cluster

**Comment by bflad** [comment]
Hi @nerdingasnate 👋  Thank you for raising this. Indeed, that attribute documentation is missing. If you or anyone is interested in adding it, the source can be found in [`website/docs/r/docdb_cluster.html.markdown`](https://github.com/hashicorp/terraform-provider-aws/blob/master/website/docs/r/docdb_cluster.html.markdown).

At some point, hopefully later this year, we will be able to pull the attributes and descriptions from the resource schemas to automatically generate the resource documentation, alleviating the disconnect between the resource definition and the documentation. There is some outstanding work within the underlying Terraform type system that currently prevents that automation from working with this provider. As a stopgap solution, https://github.com/hashicorp/terraform-provider-aws/issues/15842 is able to report some of the documentation mismatches and needs its reports to be fixed up before it can be enabled.

**Comment by antmordel** [comment]
Hi @bflad and @nerdingasnate, I've took the opportunity to create a small PR that fixes this! https://github.com/hashicorp/terraform-provider-aws/pull/17038

Any feedback is appreciated!
