### ISSUE TITLE
RPC ERROR on deleting EMR cluster on TF v0.12.16 provider (aws- 3.18.0)

### ISSUE THREAD

**Issue by nivreddy14** [hashicorp/terraform-provider-aws#17015]
I see the problem when deleting EMR cluster on TF v0.12.16 provider (hashicorp/aws) 3.18.0, could someone please suggest the fix
```
module.emr_cluster.aws_emr_cluster.emr_cluster: Refreshing state... [id=j-*********]

Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4246485 vs. 4194304)
```
I have included the step under ignore_changes section  but could see liststeps on debug logs when Terraform plan is run
```
  lifecycle {
      ignore_changes = [kerberos_attributes, step, configurations_json]
  }
```

Never faced this problem on Terraform 0.11

_Originally posted by @nivreddy14 in https://github.com/hashicorp/terraform-provider-aws/issues/14976#issuecomment-755144130_

**Comment by rednuht** [comment]
Related to: https://github.com/hashicorp/terraform-provider-aws/issues/9888

**Comment by nokernel** [comment]
yep duplicate of #9888.
