### ISSUE TITLE
Security Groups with name or name_prefix starting with "terraform-" get recreated every time

### ISSUE THREAD

**Issue by crubier** [hashicorp/terraform-provider-aws#17017]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

 - `terraform v1.12` and up
 - `terraform-provider-aws v2.50` and up

### Affected Resource(s)

* aws_security_group
* potentially any other resource that uses the `name` / `name_prefix` API pattern

### Terraform Configuration Files

Minimum reproduction:

```hcl
resource "aws_security_group" "foobar" {
  count       = 1
  name_prefix = "terraform-baz"
  description = "Security group."
  vpc_id      = var.vpc_id
}
```

This is used for example in `terraform-aws-eks` in two places:

- https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers.tf#L316
- https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/cluster.tf#L80

### Expected Behavior

- First apply: Create the security group
- Subsequent apply: Nothing to change

### Actual Behavior

- First apply: Create the security group
- Subsequent apply: Recreate the security group

```
+/- resource "aws_security_group" "foobar" {
    ...
     + name_prefix            = "terraform-baz" # forces replacement
  }
  ```

### Steps to Reproduce

1. `terraform apply`

### References

* This is very related to this comment. Same cause, different effect https://github.com/hashicorp/terraform-provider-aws/issues/14898#issuecomment-683469198

* This is caused by this line of the current project https://github.com/hashicorp/terraform-provider-aws/blob/e208508ede65805a23187128af515cb06bbcec39/aws/internal/naming/naming.go#L58 

* The prefix is defined there https://github.com/hashicorp/terraform-plugin-sdk/blob/651b26a663d34daed50d135ddd25e170ff6c6aae/helper/resource/id.go#L10 

* Big boss told me to open this issue :-) https://twitter.com/mitchellh/status/1347375993057464322?s=20

**Comment by bflad** [comment]
Thank you for reporting this issue, @crubier, as this is certainly unexpected behavior. Please note that the `naming` package is currently only in use in two resources right now with this functionality, so these resources should be the only ones affected at the moment:

* `aws_cloudwatch_event_rule`
* `aws_security_group`

The fix in this case should be fairly straightforward and I will try to get that submitted along with covering testing (and contributing guide documentation) later today.

**Comment by bflad** [comment]
Pull request submitted here: https://github.com/hashicorp/terraform-provider-aws/pull/17030
