### ISSUE TITLE
Ability to find a load balancer by its tags

### ISSUE THREAD

**Issue by videocursoscloud** [hashicorp/terraform-provider-aws#17018]
According to the lb data source we can only filter a lb by name and arn 
 https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/lb

Is it possible to implement the ability of getting a lb details finding it by its tags?

```
data "aws_lb" "test" {
  tags {
    whateveristhetag ="whateveristhecontent"
  }
}

```
It would help me a lot in order to attach a waf to a particular load balancer without the need of hardcoding its arn on my code.

Cheers

**Comment by ewbankkit** [comment]
@videocursoscloud Thanks for raising this issue.
It has already been noticed in #16771. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
