### ISSUE TITLE
Unable to specify the destination CloudMap service for aws_apigatewayv2_integration 

### ISSUE THREAD

**Issue by aponyrko** [hashicorp/terraform-provider-aws#17020]
An HTTP API integration (API Gateway V2) can be configured to proxy requests to ECS services registered with CloudMap/service discovery.

An integration can be associated with service discovery in Terraform by supplying the `arn` of the `aws_service_discovery_service` as the `integration_uri` parameter on the `aws_apigatewayv2_integration` resource.

However, the AWS Console, also allows one to specify the actual service namespace and service ID for the integration:

![image](https://user-images.githubusercontent.com/6899182/104020485-4e3f3000-518b-11eb-95a5-fdb4589e1168.png)

Is this a missing feature or resource in Terraform?

To be fair, I haven't yet found a way to specify this using the AWS CLI either. The AWS docs say the following:

> If you specify the ARN of an AWS Cloud Map service, API Gateway uses DiscoverInstances to identify resources. You can use query parameters to target specific resources. To learn more, see DiscoverInstances . For private integrations, all resources must be owned by the same AWS account.

**Comment by ewbankkit** [comment]
@aponyrko Thanks for raising this issue.
It seems that the _Namespace_ drop-down is used to populate the _Service_ drop-down and once a service is selected, that Cloud Map service's [`arn`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/service_discovery_service#arn) along with any parameters is specified as the integration's [`integration_uri`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_integration#integration_uri) attribute.

For example:

```console]
$ aws --region us-west-2 apigatewayv2 get-integrations --api-id 8lxqmm9yv2
{
    "Items": [
        {
            "ConnectionId": "glyem9",
            "ConnectionType": "VPC_LINK",
            "Description": "Integration description",
            "IntegrationId": "4llkjw3",
            "IntegrationMethod": "ANY",
            "IntegrationType": "HTTP_PROXY",
            "IntegrationUri": "arn:aws:servicediscovery:us-west-2:123456789012:service/srv-5xfh5mwa4g3ftccn?param1=value1",
            "PayloadFormatVersion": "1.0",
            "TimeoutInMillis": 30000
        }
    ]
}
```
