### ISSUE TITLE
aws_s3_bucket - Add support for Intelligent Tiering configuration

### ISSUE THREAD

**Issue by dthvt** [hashicorp/terraform-provider-aws#17028]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for configuring Intelligent Tiering properties on an S3 bucket.

### New or Affected Resource(s)

* aws_s3_bucket

### Potential Terraform Configuration

It appears that these properties are very similar to replication configuration blocks.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "aws_s3_bucket" "example" {
  # ...
  intelligent_tiering_configuration {
    id = "tiering"
    status = "Enabled"
    filter {  
      prefix = "example"
      tags = {
        Storage = "tiered"
      }
    }
    tiering {
      days = 100
      access_tier = "ARCHIVE_ACCESS"
    }
    tiering {
      days = 200
      access_tier = "DEEP_ARCHIVE_ACCESS"
    }
  }
}

    
```

### References

* https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketIntelligentTieringConfiguration.html
* https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketIntelligentTieringConfiguration.html
* https://aws.amazon.com/blogs/aws/s3-intelligent-tiering-adds-archive-access-tiers/
* https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-s3-intelligent-tiering-adds-archive-access-tiers/
* https://docs.aws.amazon.com/AmazonS3/latest/dev/storage-class-intro.html

**Comment by bflad** [comment]
Hi @dthvt 👋  Thank you for raising this. It appears to be the same request as https://github.com/hashicorp/terraform-provider-aws/issues/16123, so to consolidate discussions and efforts, I'm going to close this issue in preference of the existing one. Please :+1: react and subscribe to that issue for further updates. Thanks.

**Comment by dthvt** [comment]
Interesting, I searched for a duplicate issue and didn't get any results.  Thanks!
