### ISSUE TITLE
aws_globalaccelerator_accelerator timeout longer then 10 minuets

### ISSUE THREAD

**Issue by YotamHershk** [hashicorp/terraform-provider-aws#17048]
Terraform version: v0.13.5
AWS provider: 3.23.0

Region, where the error occurs: us-east-1

Currently terraform fails too early when creating an AWS Global Accelerator Endpoint group when creating an AWS Global Accelerator in the same run. The current timeout is 10 minutes, but usually it takes more time to create an accelerator.
The terraform run then fails, because the Accelerator is not yet available within those 10 minutes. We always need to retry. It always fail

`Error: Error waiting for Global Accelerator accelerator (arn:aws:globalaccelerator::<ACCOUNT_ID>:accelerator/<UUID>) availability: timeout while waiting for state to become 'DEPLOYED' (last state: 'IN_PROGRESS', timeout: 10m0s)
`I propose to increase the timeout to a more reasonable value of at least 15min (better 30min) to avoid failed runs in the future. Or better yet, enable a user input timeout setting

Example code:

```
resource "aws_globalaccelerator_accelerator" "default" {
  count = var.enable_ingress_infra ? 1 : 0

  name            = "default"
  ip_address_type = "IPV4"
  enabled         = true

  attributes {
    flow_logs_enabled   = true
    flow_logs_s3_bucket = "some_bucket"
    flow_logs_s3_prefix = "accelerator"
  }
}

resource "aws_globalaccelerator_listener" "https" {
  accelerator_arn = aws_globalaccelerator_accelerator.default.id
  client_affinity = "SOURCE_IP"
  protocol        = "TCP"

  port_range {
    from_port = 443
    to_port   = 443
  }
}

resource "aws_globalaccelerator_endpoint_group" "https" {
  listener_arn = aws_globalaccelerator_listener.https.id

  endpoint_configuration {
    endpoint_id = aws_alb.default.arn
    weight      = 100
  }
}

```

**Comment by ewbankkit** [comment]
Agree that being able to specify timeouts is the best option here.
