### ISSUE TITLE
sql server s3 import

### ISSUE THREAD

**Issue by fdavier** [hashicorp/terraform-provider-aws#17063]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Hi, in resource `aws_db_instance`, there is option to set s3 import with
`s3_import{}`
This actually worlk only for mysql

### New or Affected Resource(s)
Following https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance
```hcl
resource "aws_db_instance" "db" {
  s3_import {
    source_engine = "mysql"
    source_engine_version = "5.6" 
    bucket_name = "mybucket"
    bucket_prefix = "backups"
    ingestion_role = "arn:aws:iam::1234567890:role/role-xtrabackup-rds-restore"
  }
}
```
And following AWS documentation:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/User.SQLServer.Options.S3-integration.html
It should be possible to use it with SQL Server

### Potential Terraform Configuration
```
resource "aws_db_instance" "db" {
  s3_import {
    source_engine = "sqlserver"
    source_engine_version = "xxx.xxx"
    bucket_name = "mybucket"
    bucket_prefix = "backups"
    ingestion_role = "arn:aws:iam::1234567890:role/role-xtrabackup-rds-restore"
  }
}
```

**Comment by breathingdust** [comment]
Hi @fdavier! For the provider to support this functionality it must be supported via the AWS RDS API. The existing API method still only supports `mysql` and the method you link to has no associated API support. So at this time this is not possible, I will mark this as upstream and we can revisit if/when AWS support.
