### ISSUE TITLE
terraform import fails with sts:GetCallerIdentity: InvalidClientTokenId error

### ISSUE THREAD

**Issue by tgallagher91** [hashicorp/terraform-provider-aws#17071]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

when i run terraform import, the route module should be imported into the state file. this is not happening.

### Actual Behavior

when i run terraform import, i receive the below:

Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
        status code: 403, request id: 29003176-c32e-40da-b7ee-57b5c7b4d7b7

### Steps to Reproduce

1. write module for route
2. `terraform import module.public_route_IPADDRESSHERE.route ROUTETABLEIDHERE`

### Important Factoids

This is happening on multiple clients in multiple AWS tenants. I assumed it was terraform permissions related for myself as I am in an organization, but I want to cover all of my bases and make sure it is not a bug, as I can run plans just fine.

### References

All of these are similar, but none of them exactly match. Have been following this documentation to import the route: https://www.terraform.io/docs/commands/import.html#example-import-into-module

* #7418
* #10840
* #15196

**Comment by chris-neely** [comment]
In my particular use case this seems to happen on terraform imports when the providers are configured using variables for the role_arn. If I hardcode the ARN instead of using a var or locals var it resolves the issue.  Unfortunately this includes any providers in modules used by the workspace as well. It's very cumbersome to manually update every reference.
