### ISSUE TITLE
Terraform Cloud aws remote backend fails to use local credentials

### ISSUE THREAD

**Issue by xirkus** [hashicorp/terraform-provider-aws#17076]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v0.14.4
```

### Terraform Configuration Files

```
terraform {
  backend "remote" {
    organization = "REDACTED"
    workspaces {
      name = "REDACTED"
    }
  }
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 2.70"
    }
  }
}
```

### Debug Output

[error](https://gist.github.com/xirkus/8797c295ee3a43839c146ce9521537c9)

### Expected Behavior

When running `terraform plan` with a configured remote backend using AWS, an error is encountered with the default `Remote` execution mode. The issue appears to be the inability for the remote backend to use local aws credentials. 

NOTE: Running the aws CLI results in no errors which suggests that local credentials are valid. In addition, changing a Workspace's setting to use `Local` backends results is correct behavior. The current work-around is to switch default the `Remote` backend behavior in the UI. 

As per your documentation [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#authentication), I also tried to specify the `shared_credentials_file` parameter in the `provider` clause which pointed to my local AWS credentials and got the same error. This suggests there is an issue with `Remote` backends interacting with local AWS creds.

### Actual Behavior

The error is displayed and planning is aborted.

### Steps to Reproduce

1. Use the above configuration.
2. `terraform plan`

### Important Factoids

None AFAIK.

### References

* #0000

**Comment by anGie44** [comment]
Hi @xirkus, thank you for raising this issue. To further investigate the issue you are facing, do you mind providing details regarding how and where (directory/path) you were initially storing your `aws` credentials? 

Aside: This [tutorial on Hashicorp Learn](https://learn.hashicorp.com/tutorials/terraform/aws-remote?in=terraform/aws-get-started) describes a similar scenario of connecting to Terraform Cloud remote backend and reading from local AWS credentials as seen [here](https://learn.hashicorp.com/tutorials/terraform/aws-build) which may help for reference in the meantime.

**Comment by xirkus** [comment]
Sure; my credentials are stored in the default location: $HOME/.aws/credentials

Thanks, M.

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
