### ISSUE TITLE
New Resource: DyanmoDB Global Secondary Index (aws_dynamodb_table_gsi)

### ISSUE THREAD

**Issue by SaintSimmo** [hashicorp/terraform-provider-aws#17096]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I have a project making use of a single-table design where sparse-index GSIs need to be added dynamically as the project's services expand. The lack of this resource is currently my only roadblock for having this fully modularized in Terraform (that is to say, for each new service, instead of the service's Terraform config itself being fully decoupled, I still have to manually add a new GSI via the table attributes to my base project Terraform config before applying the service config separately).

### New or Affected Resource(s)

* aws_dynamodb_table_gsi

### Potential Terraform Configuration

```hcl
# adapted from the abandoned pull request below
resource "aws_dynamodb_table_gsi" "gsi" {
  table_name = aws_dynamodb_table.table.id
  name = "gsi"
  hash_key {
    name = "TestGsiHashKey"
    type = "S"
  }
  write_capacity = 1
  read_capacity = 1
  projection_type = "KEYS_ONLY"
}
```

### References

This pull request (kindly authored by @ben-bourdin451) was looking to implement this resource, but seems it got stymied by backwards compatibility tests and has since been abandoned. I've been trying to carve some time to take a look at it myself but unfortunately my Golang fu is not presently what it could be.

* https://github.com/hashicorp/terraform-provider-aws/pull/6688

**Comment by ewbankkit** [comment]
Similar: https://github.com/hashicorp/terraform-provider-aws/issues/671.
