### ISSUE TITLE
aws_appautoscaling_scheduled_action does not see and fix drift in min/max capacity

### ISSUE THREAD

**Issue by pnickerson-cashstar** [hashicorp/terraform-provider-aws#17100]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.14.4
provider registry.terraform.io/hashicorp/aws v3.23.0

### Affected Resource(s)

* aws_appautoscaling_scheduled_action

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ecs_cluster" "foo" {
  name = "white-hart"
}

resource "aws_ecs_task_definition" "service" {
  family                = "service"
  container_definitions = <<TASK_DEFINITION
[
  {
    "name": "first",
    "image": "service-first",
    "cpu": 10,
    "memory": 512,
    "essential": true
  }
]
TASK_DEFINITION
}

resource "aws_ecs_service" "mongo" {
  name            = "mongodb"
  cluster         = aws_ecs_cluster.foo.id
  task_definition = aws_ecs_task_definition.service.arn
  desired_count   = 3
}

resource "aws_appautoscaling_target" "ecs" {
  max_capacity       = 4
  min_capacity       = 1
  resource_id        = "service/${aws_ecs_cluster.foo.name}/${aws_ecs_service.mongo.name}"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"
}

resource "aws_appautoscaling_scheduled_action" "embiggen" {
  name               = "embiggen"
  service_namespace  = aws_appautoscaling_target.ecs.service_namespace
  resource_id        = aws_appautoscaling_target.ecs.resource_id
  scalable_dimension = aws_appautoscaling_target.ecs.scalable_dimension
  schedule           = "at(2006-01-02T15:04:05)"

  scalable_target_action {
    min_capacity = 1
    max_capacity = 10
  }
}
```

### Debug Output
https://gist.github.com/pnickerson-cashstar/6427ffeb6a69c6723f77482f64708cb3

### Panic Output
None.

### Expected Behavior
After I apply the config, and then use a different tool to change the application auto scaling scheduled action scalable target minimum and maximum capacities, Terraform should see that the min and max capacity in AWS have changed, and fix the drift.

### Actual Behavior
Terraform thinks that min and max are still at their old values, and does nothing.

### Steps to Reproduce

1. `terraform apply`
2.
```
aws application-autoscaling put-scheduled-action --cli-input-json '{
    "ServiceNamespace": "ecs",
    "Schedule": "at(2006-01-02T15:04:05)",
    "ScheduledActionName": "embiggen",
    "ResourceId": "service/white-hart/mongodb",
    "ScalableDimension": "ecs:service:DesiredCount",
    "ScalableTargetAction": {
        "MinCapacity": 2,
        "MaxCapacity": 20
    }
}'
```
3. `terraform plan`

### Important Factoids
None.

### References
None.

### More information
After applying the Terraform config, run this to see the capacities:
```
aws --profile cashstarsandbox --output json application-autoscaling describe-scheduled-actions --scheduled-action-names embiggen --service-namespace ecs
{
    "ScheduledActions": [
        {
            "ScheduledActionName": "embiggen",
            "ScheduledActionARN": "arn:aws:autoscaling:us-east-2:692973256363:scheduledAction:1183194f-e5aa-4a10-9b61-503b559a7eef:resource/ecs/service/white-hart/mongodb:scheduledActionName/embiggen",
            "ServiceNamespace": "ecs",
            "Schedule": "at(2006-01-02T15:04:05)",
            "ResourceId": "service/white-hart/mongodb",
            "ScalableDimension": "ecs:service:DesiredCount",
            "ScalableTargetAction": {
                "MinCapacity": 1,
                "MaxCapacity": 10
            },
            "CreationTime": "2021-01-13T20:04:33.041000-05:00"
        }
    ]
}
```
Then, run step 2 in the reproduction steps above.
Then, run the describe command again to see that the capacities have changed:
```
                "MinCapacity": 2,
                "MaxCapacity": 20
```
Terraform should see this drift, and fix it. But it doesn't.
Running `terraform refresh; terraform show` will show that the state is not updated with the capacities that were modified by a different tool:
```
# aws_appautoscaling_scheduled_action.embiggen:
resource "aws_appautoscaling_scheduled_action" "embiggen" {
    arn                = "arn:aws:autoscaling:us-east-2:692973256363:scheduledAction:1183194f-e5aa-4a10-9b61-503b559a7eef:resource/ecs/service/white-hart/mongodb:scheduledActionName/embiggen"
    id                 = "embiggen-ecs-service/white-hart/mongodb"
    name               = "embiggen"
    resource_id        = "service/white-hart/mongodb"
    scalable_dimension = "ecs:service:DesiredCount"
    schedule           = "at(2006-01-02T15:04:05)"
    service_namespace  = "ecs"

    scalable_target_action {
        max_capacity = 10
        min_capacity = 1
    }
}
```

**Comment by anGie44** [comment]
Hi @pnickerson-cashstar, thank you for raising this issue. Unfortunately it's not apparent in the documentation, but the resource itself does not support in-place updates when terraform detects a drift in any of the argument values. Rather, any change will cause resource recreation. https://github.com/hashicorp/terraform-provider-aws/blob/95f94addc338289e32589fc2c3c02f3bc121880d/aws/resource_aws_appautoscaling_scheduled_action.go#L16-L21

We can consider support for in-place updates as a feature request as it does seem supported by the API https://docs.aws.amazon.com/autoscaling/application/APIReference/API_PutScheduledAction.html.

**Comment by pnickerson-cashstar** [comment]
Thank you, @anGie44. A few responses:

1. Even if the provider does not currently support updating the resource if there's been drift in the real-world infrastructure, shouldn't a state refresh still reflect that the change happened in AWS? `terraform refresh; terraform show` still shows inaccurate capacity numbers. Or, am I misunderstanding the way Terraform is intended to work here?

2. I think the documentation should be updated to note that Terraform won't detect and fix drift in the real-world infrastructure. Should I submit a separate issue for that? Would it be a feature request? Would the issue be in terraform-provider-aws, terraform core, or somewhere else?

3. I would also like to request for Terraform to detect drift in the real-world infrastructure and either perform an in-place update, or at least delete and recreate the resource (I think this would be an OK solution). Should I submit a separate feature request asking for that?

4. Finally, a note on the API: AWS's API here is a bit odd. They have put, describe, and delete actions, but no update action. But as you found, the put action is intended to "create or update a scheduled action." But still, the action requires all the initial parameters (ServiceNamespace, ResourceId, etc.), instead of just the ARN. Maybe that's why the provider's authors have not supported updating the resource so far? I dunno, just speculation here.

Let me know about those first three questions, please. Thank you.

**Comment by brent-au** [comment]
Raised the PR above, looks like the read function for the resource was only pulling the ARN, as opposed to the remainder of the configuration:

https://github.com/hashicorp/terraform-provider-aws/blob/95f94addc338289e32589fc2c3c02f3bc121880d/aws/resource_aws_appautoscaling_scheduled_action.go#L157-L188

**Comment by gdavison** [comment]
From looking at the API, it doesn't look like there's any reason for this resource to not allow update-in-place. This may be a change in the AWS API since the resource was implemented.

We should allow update-in-place and add tests for update operations, in addition to fixing drift detection as in #17190

**Comment by gdavison** [comment]
Hi @pnickerson-cashstar, it looks like this is addressed by PRs that have already been merged in, so I'm going to close this issue. If you're still seeing this error after updating to the latest version of the provider, please open a new issue.
