### ISSUE TITLE
aws_emr_managed_scaling_policy doesn't support maximum_ondemand_capacity_units = 0

### ISSUE THREAD

**Issue by jdiebold** [hashicorp/terraform-provider-aws#17113]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform 0.13.5
aws-provider 3.23

### Affected Resource(s)

* aws_emr_managed_scaling_policy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_emr_cluster" "sample" {
  name          = "emr-sample-cluster"
  release_label = "emr-5.30.0"

  # skip ...
}

resource "aws_emr_managed_scaling_policy" "cluster_scaling" {
  cluster_id = aws_emr_cluster.sample.id
  compute_limits {
    unit_type                       = "InstanceFleetUnits"
    minimum_capacity_units          = 1
    maximum_capacity_units          = 10
    maximum_ondemand_capacity_units = 0
    maximum_core_capacity_units     = 4
  }
}
```

### Expected Behavior

The cluster should be created with a Managed Scaling policy with MaximumOnDemandCapacityUnits = 0 limit set. This means the cluster only starts spot instances for core and task nodes.

### Actual Behavior
There is no MaximumOnDemandCapacityUnits set. The cluster starts with on demand nodes only since no limit is set for on demand nodes.

### Steps to Reproduce

1. `terraform apply`

### References
*AWS explicitly offers the possibility to start an EMR cluster with spot nodes only (setting MaximumOnDemandCapacityUnits to 0) see [documentation](https://docs.aws.amazon.com/emr/latest/ManagementGuide/managed-scaling-allocation-strategy.html)

**Comment by mebuffet** [comment]
There is any update or estimated time? At this moment, the workaround is setting the maximum_ondemand_capacity_units to 1 (core node). This isn't the desired result for a complete spot cluster.
