### ISSUE TITLE
Terraform continues even if ecs task has not reached steady state

### ISSUE THREAD

**Issue by jmbosse19** [hashicorp/terraform-provider-aws#17118]
### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/aws v3.23.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/tls v3.0.0

### Affected Resource(s)

aws_ecs_service

### Terraform Configuration Files

```hcl
resource "aws_ecs_service" "service" {
  name            = "${var.environment}-service"
  cluster         = aws_ecs_cluster.ecs_cluster.id
  task_definition = aws_ecs_task_definition.task_def.arn
  desired_count   = 1
  launch_type     = "EC2"

  load_balancer {
    target_group_arn = var.alb_tg
    container_name   = "container"
    container_port   = var.port
  }

  network_configuration {
    security_groups  = [var.aws_sec_group]
    subnets          = var.application_subnet_ids
    assign_public_ip = false
  }

  wait_for_steady_state = true
}

resource "aws_ecs_service" "service2" {
  name            = "${var.environment}-service2" ...

  depends_on [aws_ecs_service.service]
  wait_for_steady_state = true
}

```

### Debug Output

Output is successful, no errors

### Expected Behavior

Terraform creates the first ecs service. Terraform then waits for the ECS task for this service to reach a steady state. Once this state is reached, service 2 is created because service 1 is its dependency (as specified by a manual `depends_on`. 

### Actual Behavior

Terraform creates the first ecs service. Terraform does not wait for the ECS task to reach a steady state, instead it looks that once the task registers a target group is believes this is satisfied. Service 2 is created and if service 1 isn't actually ready for service 2 to connect, these will loop and fail, and continue to create other services in our application.

### Steps to Reproduce

1. `terraform apply`
2. Monitor the ecs service status.

**Comment by pv93** [comment]
This issue also means that when we apply an update to an ECS service that requires a replacement (e.g changes to `network_configuration`) we will see downtime.

This is because a new replacement service is created and the old service is immediately destroyed without actually waiting for (desiredTasks == runningTasks) on the new service, as described in the docs for `aws ecs wait services-stable` [here](https://docs.aws.amazon.com/cli/latest/reference/ecs/wait/services-stable.html).
