### ISSUE TITLE
New Resource: data aws_ec2_managed_prefix_lists

### ISSUE THREAD

**Issue by uo-thomas** [hashicorp/terraform-provider-aws#17119]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, the data resource `aws_ec2_managed_prefix_list` exists and refers to a single managed prefix list which you can select by filtering by `prefix-list-id` or `prefix-list-name`. I propose a new data resource be created that can select a list of managed prefix lists by `owner-id`, `prefix-list-name` with if there is a naming pattern that is already in place that would return multiple managed prefix lists, or by tag.

AWS CLI already supports getting a list of managed prefix lists with the the following command:

`aws ec2 describe-managed-prefix-lists --filter Name=tag:Name,Values=values`

The contents of which would be helpful in my specific use case of having existing managed prefix list already created, adding the new data resource to select several managed prefix lists based on name or tag, and then creating an `aws_ram_principal_association` with a for_each loop to iterate through the list to share the lists with AWS Resource Access Manager instead of having to create separate `aws_ram_principal_association` blocks for each.

### New or Affected Resource(s)

* data.aws_ec2_managed_prefix_lists

### References

**AWS CLI v2 documentation:**
* [https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-managed-prefix-lists.html](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-managed-prefix-lists.html)

**Comment by ewbankkit** [comment]
Relates #13986.
Relates #16738.
