### ISSUE TITLE
Error: Invalid address to set: []string{"ebs_block_device", "0", "tags"}

### ISSUE THREAD

**Issue by devonbleak** [hashicorp/terraform-provider-aws#17125]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
$ terraform version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/archive v2.0.0
+ provider registry.terraform.io/hashicorp/aws v3.24.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

This seems to be related to the new `tags` field of the `ebs_block_storage` block in `aws_instance` resource and data source (I'm getting 9 copies of the error when I plan and I have aggregate 9 aws_instance resources and data sources in this workspace).

```hcl
resource "aws_instance" "test" {
  ami           = "ami-redacted"
  instance_type = "t2.micro"

  tags = {
    Name          = "redacted"
  }
}
```

### Expected Behavior

Plan succeeds.

### Actual Behavior

Plan produces a copy of the error for each aws_instance resource and data source.

### Steps to Reproduce

1. `terraform init -upgrade`
2. `terraform plan`

`terraform refresh` also produces the error.

### Important Factoids

This is an existing workspace with an existing state from aws provider 3.23.0.

**Comment by tdmalone** [comment]
Also affects `root_block_device` in the same way.

**Comment by ewbankkit** [comment]
Given the lack of additional context in the error message, my initial guess as to the offending code is:

https://github.com/hashicorp/terraform-provider-aws/blob/5bb0ab125c011351ed2ff7b3475b974e157943a2/aws/resource_aws_instance.go#L1655-L1694

**Comment by aglarendil** [comment]
facing the same issue with 3.24.0. 3.23.0 works well.

**Comment by aglarendil** [comment]
We have simple terraform vault provider config with s3 as backend - not even managing aws resources.

**Comment by YakDriver** [comment]
We apologize for the inconvenience! We are working on this now and will have more information shortly.

**Comment by YakDriver** [comment]
@devonbleak Can you or anyone provide more complete configuration to reproduce the problem? We are having trouble reproducing with a variety of different configurations.

**Comment by ivan-ayala-mx** [comment]
Hello

I got the similar error today.

I am using TF 0.12.29, and the code was working ok yesterday and today it started to complain about it with EC2 code:

Error: Invalid address to set: []string{"root_block_device", "0", "tags"}
Error: Invalid address to set: []string{"ebs_block_device", "0", "tags"}

**Comment by YakDriver** [comment]
We appreciate letting us know about this and your patience!

We are planning release `3.24.1` to address this issue. We did replicate this problem with the data source and the point release fixes the data source. However, we were never able to reproduce the problem with the `aws_instance` resource. We will leave this open for a few days to make sure that the point release fixes all the related issues. If not, please let us know!

**Comment by breathingdust** [comment]
`3.24.1` has been released which included the fix for the datasource. Please let is know if you continue to see issues.

**Comment by devonbleak** [comment]
@breathingdust @YakDriver confirmed this solved it for us.  Apologies for the wild goose chase with the resource!

**Comment by ivan-ayala-mx** [comment]
Thank you so much. issue resolved.
