### ISSUE TITLE
docs/elasticsearch_domain: resource in "VPC based ES" example only accepts 1 subnet_id, while 2 are configured

### ISSUE THREAD

**Issue by sce81** [hashicorp/terraform-provider-aws#17138]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

0.14.3
3.24.0

### Affected Resource(s)

aws_elasticsearch_domain

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "aws_vpc" "selected" {
     id = var.vpc_id
}

data "aws_subnet_ids" "selected" {
  vpc_id = var.vpc_id

    tags = {
    Name = "${var.env}-core-*"
  }
}
locals {subnet_ids  = tolist(data.aws_subnet_ids.selected.ids)}


resource "aws_elasticsearch_domain" "main" {
  vpc_options {
    subnet_ids                  = [local.subnet_ids]
  
    security_group_ids          = [aws_security_group.main.id]
  }
}
```

### Expected Behavior

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain
according to the documents I should be able to pass in a list of Subnet IDs.
passing in 
```
    subnet_ids                  = [local.subnet_ids.0]
```
is accepted

### Actual Behavior
However if i try to pass in 2 or more subnet IDs.
```
Error: Error creating ElasticSearch domain: ValidationException: You must specify exactly one subnet.
```
The plan output shows the list as expected
```
          + subnet_ids         = [
              + "subnet-03a3a1fXXXXX3a22c",
              + "subnet-04630XXXXXc9f30c",
              + "subnet-0c7aXXXXX25d2b5",
            ]
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by sce81** [comment]
Okay, so i figured this out. But the example provided on registry.terraform.io is incorrect. zone_awareness_enabled is not set in the example.

```
cluster_config {
zone_awareness_enabled = true
}
```
needs to be enabled in order for 2 subnets to be accepted. 

```
cluster_config {
zone_awareness_enabled = true
availability_zone_count = 3
}
```
availability_zone_count needs to be set to 3 in order for 3 x subnet IDs to be accepted

**Comment by anGie44** [comment]
Hi @sce81, thank you for creating this issue and resolving the error you were facing! Apologies for the confusion -- we'll keep this issue open to track the need to update the documentation example your'e referring to 👍
