### ISSUE TITLE
aws_transfer_user not accepting arguments introduced since v3.8.0

### ISSUE THREAD

**Issue by gmconte** [hashicorp/terraform-provider-aws#17131]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```hcl
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/aws v3.24.0
+ provider registry.terraform.io/hashicorp/external v1.2.0
+ provider registry.terraform.io/hashicorp/helm v1.2.4
+ provider registry.terraform.io/hashicorp/kubernetes v1.12.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
+ provider registry.terraform.io/hashicorp/tls v3.0.0

Your version of Terraform is out of date! The latest version
is 0.14.4. You can update by downloading from https://www.terraform.io/downloads.html
```
### Affected Resource(s)

* aws_transfer_user

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
### Before: working fine
resource "aws_transfer_user" "sftp_user" {
  for_each = local.enable_sftp ? local.user_to_home : {}
  server_id = data.aws_transfer_server.existing_sftp_server[0].server_id
  user_name = each.key
  role = data.aws_iam_role.sftp_s3_access_role[0].arn
  policy = data.aws_iam_policy_document.sftp_scoped_down_user_policy[0].json
  home_directory = "/${local.sftp_bucket}/${each.value}"
  tags = local.common_tags
  provider = aws.sftp_provider
}

### After: BROKEN
resource "aws_transfer_user" "sftp_user" {
  for_each = local.enable_sftp ? local.user_to_home : {}
  server_id = data.aws_transfer_server.existing_sftp_server[0].server_id
  user_name = each.key
  role = data.aws_iam_role.sftp_s3_access_role[0].arn
  policy = data.aws_iam_policy_document.sftp_scoped_down_user_policy[0].json
  home_directory = "/${local.sftp_bucket}/${each.value}"
  tags = local.common_tags
  provider = aws.sftp_provider
  home_directory_mappings = []  <-- this is the problem
}
```

### Debug Output
`terraform apply` fails during code validation step, so no plan is generated
I believe in this case the Debug output is irrelevant, so I copied the normal output below:

```hcl
Error: Unsupported argument

  on modules/ec2_v2/jobs_sftp.tf line 87, in resource "aws_transfer_user" "sftp_user":
  87:   home_directory_mappings = []

An argument named "home_directory_mappings" is not expected here. Did you mean
to define a block of type "home_directory_mappings"?

```

### Expected Behavior

Terraform plan should show no changes as the argument is valid since aws provider v3.8.0 and I specify an empty list which should cause no changes
### Actual Behavior 

Terraform throws an error stating that the argument is not expected
```hcl
Error: Unsupported argument

  on modules/ec2_v2/jobs_sftp.tf line 87, in resource "aws_transfer_user" "sftp_user":
  87:   home_directory_mappings = []

An argument named "home_directory_mappings" is not expected here. Did you mean
to define a block of type "home_directory_mappings"?
```
I already had some suspicions when I saw that my IntelliJ tooltip suggestion wasn't showing the argument in the list (see below image):

![image](https://user-images.githubusercontent.com/3528114/104725747-69c9ae00-572a-11eb-8f1a-ba55d85b462f.png)

### Steps to Reproduce

1. given a working sftp user configuration with the same structure as in the "Before" snippet
2. add the `home_directory_mappings` argument with any value
3. `terraform apply`

### Important Factoids

My steps:

1. This feature has been merged in v3.8.0 - PR https://github.com/hashicorp/terraform-provider-aws/pull/13591 
2. The first time I saw this error, my codebase was configured to use AWS Provider version v3.19.0
3. I then retried after I upgraded to the current version v3.24.0, to make sure it was not some regression bug specific to v3.19.0
4. Still experiencing the same issue, I tried deleting the entire project folder and re-initializing from scratch
5. After another failure, I decided to open this issue

Worth noting that my sftp code is inside my custom module (see path mentioned in the error), but everything else works fine 

### References

* PR #13591

**Comment by drexler** [comment]
@gmconte `home_directory_mappings` is a block.  So what's expected there is something akin to this: 

```hcl
  home_directory_mappings {
    entry  = "/your-personal-report.pdf"
    target = "/bucket3/customized-reports/tftestuser.pdf"
  }
```

**Comment by gmconte** [comment]
@drexler thanks, that example actually solved my problem. Everything now works fine.
I wonder if this snippet, including the `home_directory_type = "LOGICAL"` argument, could be added to the resource documentation, as it was difficult for me to understand the resource source code (I read the schema type "list" and thought that was the type to use in here).
A documented example certainly would avoid the same confusion in the future considering that the IntelliJ plugin doesn't give any suggestions.

I know my issue now can be considered solved, but I wonder why the Intellij Terraform plugin doesn't pick up these arguments.
The plugin should be asking to the Terraform executable for some kind of metadata model (at least I think that's what it does), so either `home_directory_mappings` and `home_directory_type` are not compatible or their schema metadata is not "published" where the plugin is looking.

I wonder if there's a terraform command I can use to get the metadata model of a resource directly when something like this happens?

Is looking into the source code the only option?

thanks! I appreciate this is all extra info that may not be relevant to this ticket anymore.

**Comment by drexler** [comment]
@gmconte glad that helped. In rare cases, in the source code I look at the associated integration test of a `resource` or `data_source` to see an example of usage. Most times the documentation examples reflect those used in the integration tests. I'll create an issue for the documentation update to include these examples for this resource.
