### ISSUE TITLE
Add CHANGELOG file contents linting

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#17135]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We will be merging in our new CHANGELOG handling via `go-changelog` shortly (#16215). It might be good if we followed up this new process with content checking tooling to reduce some maintainer burden of reviewing these:

* Any `.changelog` directory file should be named `[0-9]+.txt`
* File should contain release note block:

``````markdown
```release-note:{CATEGORY}
```
``````

* Release note blocks should not contain new lines (instead should be multiple release note blocks)
* Release note blocks should have an expected category:
    * `breaking-change`
    * `bug`
    * `enhancement`
    * `new-resource`
    * `new-data-source`
    * `new-guide`
    * `note`
* Entries should not contain an issue link
* Entries should not contain a leading asterisk or hyphen (covered by prefix checks below)
* For entry categories `new-resource` and `new-data-source`:
    * Uses the prefix `aws_`
    * Contains no whitespace
* For entry categories `breaking-change`, `bug`, `enhancement`, and `note`:
    * Uses the prefix `resource/aws_`, `data-source/aws_`, `provider`, or `service/`

Similar Markdown AST checking can be found in the `tfproviderdocs` tooling. It should be investigated whether this tooling should live within the `go-changelog` codebase or separately (at least to start).

### References

* https://github.com/hashicorp/terraform-provider-aws/pull/16215
* https://github.com/hashicorp/go-changelog

**Comment by bflad** [comment]
Its worth mentioning that there is a separate command available in that codebase [`changelog-pr-body-check`](https://github.com/hashicorp/go-changelog/tree/master/cmd/changelog-pr-body-check) which covers some of this functionality, but would need enhancements to support the provider-specific checks.

**Comment by tbugfinder** [comment]
Hi @bflad ,
CHANGELOG.md wasn't updated recently. It guess it is related to this issue however it still would be helpful having the changes documented in the file.
