### ISSUE TITLE
attempting to destroy aws_lakeformation_resource produces error

### ISSUE THREAD

**Issue by WafflesMcDuff** [hashicorp/terraform-provider-aws#17143]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.13.6
+ provider registry.terraform.io/hashicorp/aws v3.23.0

### Affected Resource(s)

* aws_lakeformation_resource

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
terraform {
  required_version = ">= 0.12"
}

provider "aws" {
  version = "~> 3.23"
  region  = "us-east-2"

}

data "aws_s3_bucket" "selected" {
  bucket = var.s3_bucket
}

resource "aws_lakeformation_resource" "main" {
  arn = data.aws_s3_bucket.selected.arn
}
```

### Expected Behavior

terraform should be able to apply and destroy
### Actual Behavior

apply works, destroy returns this error:
`Error: error deregistering Lake Formation Resource (arn:aws:s3:::mybucket): InvalidInputException: Must manually delete service-linked role to deregister last S3 location.`

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

**Comment by trejas** [comment]
I see exactly the same behavior.

**Comment by tuannguyen0901** [comment]
Same here

**Comment by WafflesMcDuff** [comment]
Hmm wonder if we need to create a service linked role as a resource managed by this TF config in order so that destroy removes it?

**Comment by abhihashi** [comment]
I had the same issue, tried rerunning my apply and seems to have worked. Anyone with the same experience ?

**Comment by pkdcloud** [comment]
Simulated @abhihashi 's as a stop gap until a permanent fix is applied in a buildkite pipeline.
``
  - label: ":terraform: Destroy"
    command: make destroy
    retry: 
      automatic: true # https://github.com/hashicorp/terraform-provider-aws/issues/17143
    <<: *dev
