### ISSUE TITLE
New Feature: Launch AWS Marketplace produccts (AMIs, containers) in linked AWS accounts

### ISSUE THREAD

**Issue by gjoshevski** [hashicorp/terraform-provider-aws#17146]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently if you want to use AMIs or Containers from AWS Marketplace in any of your AWS accounts members of the same AWS Organization you have to go to the web UI and subscribe to the products manually.

You can now manage entitlements for product in AWS Marketplace within AWS License Manager, meaning if you have subscribed to the product in one of you AWS accounts, now you can share the entitlement and the same AMI or container product can be launched in any AWS Account member of the org that has received the grant.

### References

https://docs.aws.amazon.com/license-manager/latest/userguide/granted-licenses.html

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor blog posts or documentation? For example:

* https://aws.amazon.com/about-aws/whats-new/2018/04/introducing-amazon-ec2-fleet/

**Comment by breathingdust** [comment]
Hi all 👋 Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

**Comment by YakDriver** [comment]
This looks like maybe 4-5 resources, after a quick look. AWS SDK for Go v1 operations:

### A (`aws_licensemanager_grant`?)
* [CreateGrant](https://docs.aws.amazon.com/sdk-for-go/api/service/licensemanager/#LicenseManager.CreateGrant)
* [DeleteGrant](https://docs.aws.amazon.com/sdk-for-go/api/service/licensemanager/#LicenseManager.DeleteGrant)
* [GetGrant](https://docs.aws.amazon.com/sdk-for-go/api/service/licensemanager/#LicenseManager.GetGrant)

### B (`aws_licensemanager_license_grants` data source)
* [ListDistributedGrants](https://docs.aws.amazon.com/sdk-for-go/api/service/licensemanager/#LicenseManager.ListDistributedGrants)

### C (`aws_licensemanager_grant_version`?)
* [CreateGrantVersion](https://docs.aws.amazon.com/sdk-for-go/api/service/licensemanager/#LicenseManager.CreateGrantVersion)

### D (`aws_licensemanager_grant_accepter`?)
* [AcceptGrant](https://docs.aws.amazon.com/sdk-for-go/api/service/licensemanager/#LicenseManager.AcceptGrant)
* [ListReceivedGrants](https://docs.aws.amazon.com/sdk-for-go/api/service/licensemanager/#LicenseManager.ListReceivedGrants) (maybe a separate data source)
* [RejectGrant](https://docs.aws.amazon.com/sdk-for-go/api/service/licensemanager/#LicenseManager.RejectGrant)

**Comment by Jamie-Leon** [comment]
Any updates on when this will be made available?

**Comment by brittandeyoung** [comment]
I also added the `aws_licenasemanager_grant_accepter` to the same PR

**Comment by brittandeyoung** [comment]
@gjoshevski and @YakDriver  I have updated the PR with the following:

New Resources:
* `aws_licensemanager_grant - Allow sharing a license with another account.
*  `aws_licensemanager_grant_accepter` -  Accepting a shared license in the target account. 
New Datasources: 
* `aws_licensemanager_received_license` -  A data source to get detailed data about an accepted AWS License from the market place. 
*  `aws_licensemanager_received_licenses` - A data source to get a list of ARNs for accepted AWS market place licenses that match a filter. 

I believe that these combination of resources and data sources completes what is being requested in this issue. Please let me know if that is not that case.
