### ISSUE TITLE
 Error publishing version when lambda using container updates code

### ISSUE THREAD

**Issue by mauriciocm9** [hashicorp/terraform-provider-aws#17153]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform:  v0.13.3
Terraform AWS Provider: 3.24.1
```

### Affected Resource(s)

* aws_lambda_function

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

For simplicity, using public module with additional `source_code_hash` argument. Module from: https://github.com/terraform-aws-modules/terraform-aws-lambda/

```hcl
module "lambda_function_from_container_image" {
  source = "../.."

  function_name = "${random_pet.this.id}-lambda-from-container-image"
  description   = "My awesome lambda function from container image"

  create_package = false
  source_code_hash = trimprefix(data.aws_ecr_image.ecr_lambda_image.id, "sha256:")

  ##################
  # Container Image
  ##################
  image_uri    = docker_registry_image.app.name
  package_type = "Image"
}
```

### Expected Behavior

Changes should have been applied without error.

### Actual Behavior
```
Error: Error publishing Lambda Function (bursting-deer-lambda-from-container-image) version: ResourceConflictException: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-east-1:xxx:function:bursting-deer-lambda-from-container-image
{
  RespMetadata: {
    StatusCode: 409,
    RequestID: "a11bc6ec-1586-4a1f-bf7b-17ae01e861b6"
  },
  Message_: "The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-east-1:xxx:function:bursting-deer-lambda-from-container-image",
  Type: "User"
}

```
### Steps to Reproduce

1. Create lambda resource using container.
2. Update ECR repository with new change. (this will trigger lambda UpdateFunctionCode using `source_code_hash` with ECR latest digest.)
3. `terraform plan`
4. `terraform apply`
### References

* #0000

I was able to reproduce the problem by setting the publish argument to true and the source_code_hash argument with the latest digest from the ECR repository (so the latest change of the image is used). Since source_code_hash has changed, terraform will trigger the UpdateFunctionCode method causing the lambda to move to pending state while [the image undergoes an optimization process for running on Lambda](https://docs.aws.amazon.com/lambda/latest/dg/configuration-images.html#configuration-images-optimization). 
Once the image is updated, terraform will try to publish the version. However it will fail because the lambda is still in pending state.
Here are some logs of the plan:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.lambda_function_from_container_image.aws_lambda_function.this[0] will be updated in-place
  ~ resource "aws_lambda_function" "this" {
        arn                            = "arn:aws:lambda:us-east-1:xxx:function:bursting-deer-lambda-from-container-image"
        description                    = "My awesome lambda function from container image"
        function_name                  = "bursting-deer-lambda-from-container-image"
        id                             = "bursting-deer-lambda-from-container-image"
        image_uri                      = "xxx.dkr.ecr.us-east-1.amazonaws.com/bursting-deer:1.0"
        invoke_arn                     = "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:xxx:function:bursting-deer-lambda-from-container-image/invocations"
      ~ last_modified                  = "2021-01-18T00:08:53.000+0000" -> (known after apply)
        layers                         = []
        memory_size                    = 128
        package_type                   = "Image"
        publish                        = true
      ~ qualified_arn                  = "arn:aws:lambda:us-east-1:xxx:function:bursting-deer-lambda-from-container-image:$LATEST" -> (known after apply)
        reserved_concurrent_executions = -1
        role                           = "arn:aws:iam::xxx:role/bursting-deer-lambda-from-container-image"
      ~ source_code_hash               = "6c4f42f959e3d6471b4128a4f3806e43a8aaa36dc1ca7e67b30ecf994a0439f8" -> "d09bd32a66fb7747aa2d180c4326011822cf1195704f2ca24c07f6ea8351bc96"
        source_code_size               = 0
        tags                           = {}
        timeout                        = 3
      ~ version                        = "$LATEST" -> (known after apply)

        tracing_config {
            mode = "PassThrough"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
Once the apply has finished (with Error publishing Lambda Function message), you can check that the lambda status is still in pending:
```aws lambda get-function-configuration --function-name bursting-deer-lambda-from-container-image```
```
{
    "FunctionName": "bursting-deer-lambda-from-container-image",
    "FunctionArn": "arn:aws:lambda:us-east-1:xxxx:function:bursting-deer-lambda-from-container-image",
    "Role": "arn:aws:iam::xxx:role/bursting-deer-lambda-from-container-image",
    "CodeSize": 0,
    "Description": "My awesome lambda function from container image",
    "Timeout": 3,
    "MemorySize": 128,
    "LastModified": "2021-01-18T00:13:05.000+0000",
    "CodeSha256": "6c4f42f959e3d6471b4128a4f3806e43a8aaa36dc1ca7e67b30ecf994a0439f8",
    "Version": "$LATEST",
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "bc691819-b517-42a4-85ad-ba9b2e828449",
    "State": "Active",
    "LastUpdateStatus": "InProgress",
    "LastUpdateStatusReason": "The function is being created.",
    "LastUpdateStatusReasonCode": "Creating"
}
```

**Comment by shaimona** [comment]
Please also note that this issue is preventing creation of version and alias thus blocking blue/green and canary deployment.

**Comment by yingdongzhang** [comment]
Also experiencing the exact issue, when updating the lambda to a new image, the concurrent error occurs, have to wait and execute apply again. Even when it goes through the lambda version stays unchanged.

**Comment by germanamz** [comment]
The issue happens when you reference the `hash` on the `image_uri`

**Comment by yingdongzhang** [comment]
Here's a workaround by setting `publish=false` which removes this blocker for me. Of course depends on your use case it may not be acceptable.
