### ISSUE TITLE
resource/aws_elasticache_replication_group: computed member_clusters attribute not updated

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#17161]
When updating an `aws_elasticache_replication_group` by adding or removing cache clusters using `number_cache_clusters`, the computed attribute `member_clusters` is not updated.

This is likely related to the Terraform Plugin SDK issue hashicorp/terraform-plugin-sdk#195.

### Terraform CLI and Terraform AWS Provider Version

```console
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/aws v3.24.1
```

```console
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/aws v3.24.1
```

### Affected Resource

* aws_elasticache_replication_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```terraform
resource "aws_elasticache_replication_group" "test" {
  automatic_failover_enabled    = false
  node_type                     = "cache.t3.medium"
  number_cache_clusters         = var. number_cache_clusters
  replication_group_id          = "gmd-test-elasticache"
  replication_group_description = "Terraform Acceptance Testing - number_cache_clusters"
  subnet_group_name             = aws_elasticache_subnet_group.test.name
}

output "number_cache_clusters"{
    value = aws_elasticache_replication_group.test.number_cache_clusters
}

output "member_clusters"{
    value = aws_elasticache_replication_group.test.member_clusters
}

data "aws_availability_zones" "available" {
  state = "available"

  filter {
    name   = "opt-in-status"
    values = ["opt-in-not-required"]
  }
}

resource "aws_vpc" "test" {
  cidr_block = "192.168.0.0/16"
}

resource "aws_subnet" "test" {
  count = 2

  availability_zone = data.aws_availability_zones.available.names[count.index]
  cidr_block        = "192.168.${count.index}.0/24"
  vpc_id            = aws_vpc.test.id
}

resource "aws_elasticache_subnet_group" "test" {
  name       = "gmd-test-elasticache"
  subnet_ids = aws_subnet.test[*].id
}
```

```console
$ terraform apply -var 'number_cache_clusters=2'
...
Apply complete! Resources: 5 added, 0 changed, 0 destroyed.

Outputs:

member_clusters = toset([
  "gmd-test-elasticache-001",
  "gmd-test-elasticache-002",
])
number_cache_clusters = 2

$  terraform apply -var 'number_cache_clusters=4'
...
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

member_clusters = toset([
  "gmd-test-elasticache-001",
  "gmd-test-elasticache-002",
])
number_cache_clusters = 4
```

### Expected Behavior

The contents of `member_clusters` should be updated.

### Actual Behavior

The contents of `member_clusters` is not updated, though `number_cache_clusters` (which is set to the length of the same API response that is used to set `member_clusters`) is.

Calling `terraform refresh` updates state to the correct values.

### References

* hashicorp/terraform-plugin-sdk#195

**Comment by bflad** [comment]
Terraform core requires that the provider resources signal when a `Computed` attribute will have an updated value during a plan, otherwise it assumes the value is going to remain the same. If the `Read` function of the resource is setup correct and calls `d.Set()` on the attribute, it should get picked up with a second `terraform refresh` or `terraform apply`.

To prevent the need for a double apply, our only option today is to use `CustomizeDiff` to modify the plan a signal to Terraform core the side-effect of a `Computed` attribute value update during the same plan. `ResourceDiff` supports either updating the value to a known value (`diff.SetNew()`) or an unknown value (`diff.SetNewComputed()`). e.g. to do it "manually":

```go
CustomizeDiff: func(_ context.Context, diff *schema.ResourceDiff, v interface{}) error {
	if diff.HasChange("attr1") {
		return diff.SetNewComputed("attr2")
	}

	return nil
},
```

Or the `customdiff` package provides some helpers:

```go
CustomizeDiff: customdiff.Sequence(
	customdiff.ComputedIf("attr2", func(ctx context.Context, diff *schema.ResourceDiff, meta interface{}) bool {
		return diff.HasChange("attr1")
	}),
),
```
