### ISSUE TITLE
Error registering targets with target group: InvalidTarget: The following targets are not in a running state and cannot be registered.  For ALB

### ISSUE THREAD

**Issue by mikepiehler** [hashicorp/terraform-provider-aws#17167]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
0.13.0
provider.aws v3.20

### Affected Resource(s)
aws_lb_target_group_attachment

### Terraform Configuration Files
```
provider "aws" {
  region  = "us-east-1"
  version = "~> 3.20"
}

locals {
  securityGroups     = []
  subnetIds          = []
  subnetId           = ""
  vpcId              = ""
  amiId              = ""
  keyPairName        = ""
  iamInstanceProfile = ""
}

resource "aws_lb" "alb" {
  name               = "bug-alb"
  internal           = false
  load_balancer_type = "application"
  security_groups    = local.securityGroups
  subnets            = local.subnetIds
}

resource "aws_lb_target_group" "alb-target" {
  name     = "alb-target"
  port     = 80
  protocol = "HTTP"
  vpc_id   = local.vpcId
}

resource "aws_spot_instance_request" "spot" {
  ami                             = local.amiId
  instance_type                   = "t2.medium"
  key_name                        = local.keyPairName
  availability_zone               = "us-east-1b"
  subnet_id                       = local.subnetId
  iam_instance_profile            = local.iamInstanceProfile
  valid_until                     = timeadd(timestamp(), "${24 * 7 * 52}h")
  wait_for_fulfillment            = true
  associate_public_ip_address     = false
  instance_interruption_behaviour = "stop"
}

resource "aws_lb_target_group_attachment" "alb-target-group-attachment" {
  target_group_arn = aws_lb_target_group.alb-target.arn
  target_id        = aws_spot_instance_request.spot.spot_instance_id
  port             = 80
}
```

### Expected Behavior
Expect retry behavior for ALBs that already exists for ELBs.  
https://github.com/hashicorp/terraform-provider-aws/blob/23f242a81a05691db24ae623435ea201d7817560/aws/resource_aws_elb_attachment.go#L49

### Actual Behavior
Error: Error registering targets with target group: InvalidTarget: The following targets are not in a running state and cannot be registered: 'i-01f57b6a85ee627b4' status code: 400

### References
Similar issue -
https://github.com/hashicorp/terraform-provider-aws/issues/7561

Fixed ELB -
https://github.com/hashicorp/terraform-provider-aws/blob/23f242a81a05691db24ae623435ea201d7817560/aws/resource_aws_elb_attachment.go#L49

No ALB retry -
https://github.com/hashicorp/terraform-provider-aws/blob/99c0da9bacaa4ffaf000dafd0a0ee5b4b75b5b67/aws/resource_aws_lb_target_group_attachment.go#L71

**Comment by bill-rich** [comment]
Hi @mikepiehler! Can you please provide a complete example configuration to reproduce the problem? The one in the mentioned issue, is missing several required portions.

Thanks!

**Comment by mikepiehler** [comment]
Hi @bill-rich! The original comment has been updated.  Let me know if you need anything else.  Thanks!

**Comment by efleming18** [comment]
Hey @bill-rich - any update or information on this? I've run in to this issue before as well.
