### ISSUE TITLE
aws provider does not respect `user_data` vs. `user_data_base64` distinction

### ISSUE THREAD

**Issue by justinTM** [hashicorp/terraform-provider-aws#17171]
Throughout the Terraform documentation, there is a distinction made between `user_data` (as string) and `user_data_base64` (string encoded as base64). After troublshooting and digging, it appears [the AWS provider resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#user_data) does not care to include this distinction and throws it out the window (setting base64-encoded user data to the not-base64-encoded `user_data` argument), causing problems with implementation of the rest of terraform code.

It is important for people wishing to implement both string and encoded string versions of user data that AWS respects the implementation Terraform has provided. Please update to allow both please and thank you.

**Comment by bill-rich** [comment]
Hi @justinTM! 

Can you provide an example of the problem you're running into? On the AWS API side, all the user data is base64 encoded. The distinction on the Terraform side is for convenience.

**Comment by breathingdust** [comment]
Closing due to lack of response.
