### ISSUE TITLE
There is no way to set up an approval rule by a specific date for aws_ssm_patch_baseline

### ISSUE THREAD

**Issue by jjuliogallegos** [hashicorp/terraform-provider-aws#17170]
The aws_ssm_patch_baseline resource doesn't provide an option to setup auto approvals by a specific date, like AWS allows. The reason why approvals by date are needed, is because that is the only way to create patch baselines that are consistent.

With auto approvals based on the time a patch has been there before it is approved, can potentially result in having servers with different levels of patching if the patching process extends to multiple days.

**Comment by bflad** [comment]
Hi @jjuliogallegos 👋  Thank you for raising this. We just merged in support for `approval_rule` block `approve_until_date` argument support for the `aws_ssm_patch_baseline` resource, which will release with version 3.28.0 of the Terraform AWS Provider later today. e.g.

```terraform
resource "aws_ssm_patch_baseline" "example" {
  # ... other configuration ...
  approval_rule {
    approve_until_date = "2021-01-01"
    # ... other configuration ...
  }
}
```

If this is not the feature you are looking for, please open a new feature request filling out all the details requested by the issue template. 👍
