### ISSUE TITLE
Data source not updated when it depends on a different resource

### ISSUE THREAD

**Issue by sblask** [hashicorp/terraform-provider-aws#17176]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.21.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/vault v2.16.0

### Affected Resource(s)

aws_iam_policy_document

### Terraform Configuration Files

Simplified:

```
data "aws_iam_group" "developers" {
  group_name = "developer"
}

locals {
  developers = {
    for user in data.aws_iam_group.developers.users
    :
    replace(split("@", user.user_name)[0], ".", "-") => { arn = user.arn, name = user.user_name }
  }
}

resource "aws_iam_user_policy" "assume" {
  for_each = local.developers

  name = "${each.key}"
  user = each.value.name

  policy = data.aws_iam_policy_document.assume[each.key].json
}

data "aws_iam_policy_document" "assume" {
  for_each = local.developers

  statement {
    sid       = "AssumeReplRole"
    actions   = ["sts:AssumeRole"]
    resources = [aws_iam_role.role[each.key].arn] # I run into the same problem when I remove this but have an explicit depends_on to aws_iam_role.role
  }
}

resource "aws_iam_role" "role" {
  for_each = local.developers
  name     = "${each.key}"
}
```

### Expected Behavior

I should always be able to plan/apply this

### Actual Behavior

When the aws_iam_group contains more users than during a previous run, like I have 12 users, apply and add new.user@example.com I get:

```
Error: Invalid index

  on xyz line 67, in resource "aws_iam_user_policy" "assume":
  67:   policy = data.aws_iam_policy_document.assume[each.key].json
    |----------------
    | data.aws_iam_policy_document.assume is object with 12 attributes
    | each.key is "new-user"
```

No matter how many users there are, it always shows the previous number

### Steps to Reproduce

1. `terraform apply`
1.  add user
1. `terraform plan`

**Comment by sblask** [comment]
Same problem after a provider upgrade:

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.24.1
+ provider registry.terraform.io/hashicorp/random v3.0.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/vault v2.17.0

**Comment by bill-rich** [comment]
Hi @sblask! This looks like its related to a change in Terraform rather than with the AWS provider. Please open an issue for this over at https://github.com/hashicorp/terraform to get the best results.
