### ISSUE TITLE
aws_cloudwatch_event_target support explicit capacity provider strategy for ecs_target EC2

### ISSUE THREAD

**Issue by evilGitHub** [hashicorp/terraform-provider-aws#17185]
This is a feature request.

Please support setting an Explicit capacity provider strategy for ecs_target (Launche Type EC2) in resource aws_cloudwatch_event_target

**Comment by couling** [comment]
For reference this does appear to be supported by AWS https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-ecsparameters.html

**Comment by nwalter-wb** [comment]
Definitely needed
