### ISSUE TITLE
aws_transfer_server does not return vpc_endpoint_id when endpoint_type=VPC

### ISSUE THREAD

**Issue by clvx** [hashicorp/terraform-provider-aws#17188]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```$terraform -v
Terraform v0.13.5
```

### Affected Resource(s)

* aws_transfer_server

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_transfer_server" "test" {
  identity_provider_type = "API_GATEWAY"
  invocation_role        = aws_iam_role.test.arn
  url                    = aws_api_gateway_deployment.test.invoke_url

  endpoint_type = "VPC" 
  endpoint_details {
    subnet_ids = [data.aws_subnet.default.id]
    vpc_id     = data.aws_vpc.default.id
  }
}
```

### Expected Behavior

`vpc_endpoint_id` should be returned for the `vpc_id` as an [attribute reference](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_server#attributes-reference)

### Actual Behavior

`vpc_endpoint_id` is not managed by terraform when `endpoint_type = "VPC"` is used. 

### Steps to Reproduce

1. `terraform apply`

**Comment by ewbankkit** [comment]
@clvx Thanks for raising this issue.
Could you please try using `aws_transfer_server.test.endpoint_details.0.vpc_endpoint_id` and see if the VPC Endpoint ID is available there?

**Comment by clvx** [comment]
That worked.
All good to close.
