### ISSUE TITLE
aws_ec2_managed_prefix_list: number of entries per request cannot exceeds limit (100)

### ISSUE THREAD

**Issue by dn95** [hashicorp/terraform-provider-aws#17191]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/aws v3.24.1

### Affected Resource(s)

* aws_ec2_managed_prefix_list

### Terraform Configuration Files

```hcl
locals {
  services = toset(["amazon", "ec2"])
  regions  = ["eu-central-1", "global"]
  ec2      = data.aws_ip_ranges.cidrs["ec2"].cidr_blocks
  amazon   = data.aws_ip_ranges.cidrs["amazon"].cidr_blocks
  entries  = setunion(local.amazon, local.ec2)
}

data "aws_ip_ranges" "cidrs" {
  for_each = local.services
  services = [each.value]
  regions  = local.regions
}

resource "aws_ec2_managed_prefix_list" "test" {
  name           = "test"
  address_family = "IPv4"
  max_entries    = length(local.entries)  # right now 253

  dynamic "entry" {
    for_each = local.entries
    content {
      cidr = entry.value
    }
  }
}

```

### Expected Behavior

Terraform should create an EC2 Managed Prefix List of size 253 (at the time of writing) with 253 CIDR entries.

### Actual Behavior

Terraform stops with an error:
```
aws_ec2_managed_prefix_list.test: Creating...

Error: error creating EC2 Managed Prefix List: InvalidParameterValue: The number of entries per request cannot exceeds limit (100).
        status code: 400, request id:
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Creating an empty list of size 253 works flawlessly. The problem occurs as soon as more than 100 entries are created / modified per request.

### References

See for example
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateManagedPrefixList.html
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyManagedPrefixList.html

```
AddEntry.N
One or more entries to add to the prefix list.

Type: Array of AddPrefixListEntry objects

Array Members: Minimum number of 0 items. Maximum number of 100 items.
```

**Comment by ewbankkit** [comment]
Relates:

* #13986
* #14068

**Comment by Stretch96** [comment]
A workaround for now I've found is to split the list into chunks of 100, then create multiple prefix lists:

```hcl
locals {
  really_long_list = [
    # ...
  ]

  really_long_list_split = [
    for i in range(0, length(local.really_long_list), 100):
      slice(local.really_long_list, i, i + min( length(local.really_long_list) - i, 100))
  ]
}

resource "aws_ec2_managed_prefix_list" "example_ips" {
  count                 = length(local.really_long_list_split)
  name                 = "IP list ${count.index}"
  address_family = "IPv4"
  max_entries      = 1000

  dynamic "entry" {
    for_each = local.really_long_list_split[count.index]
    content {
      cidr = entry.value
    }
  }
}
```
