### ISSUE TITLE
Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by da-edra** [hashicorp/terraform-provider-aws#17207]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
terraform -v
Terraform v0.14.0
+ provider registry.terraform.io/hashicorp/aws v3.16.0
```

### Affected Resource(s)

* aws_iam_role_policy_attachment

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_iam_role_policy_attachment" "REDACTED" {
  role       = aws_iam_role.REDACTED.id
  policy_arn = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:policy/REDACTED"
}

resource "aws_iam_role_policy_attachment" "REDACTED" {
  role       = aws_iam_role.REDACTED.id
  policy_arn = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:policy/REDACTED"
}

resource "aws_iam_role_policy_attachment" "REDACTED" {
  role       = aws_iam_role.REDACTED.id
  policy_arn = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:policy/REDACTED"
}
```

Please replace the sections that say `REDACTED` with real values of managed policies, I can't include them for confidentiality.
### Debug Output

[Gist link](https://gist.github.com/da-edra/890b1999d19fc8acfaa0efdc521bc8f9)

### Expected Behavior

Terraform should deploy my infrastructure.

### Actual Behavior

Terraform failed to attach the managed policies to a role and failed.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

None.

### References

* #0000

**Comment by bill-rich** [comment]
Hi @da-edra! 

In order to make sure we're able to quickly reproduce the issue, can you please provide a complete example configuration that will result in the reported error?

**Comment by da-edra** [comment]
Hi @bill-rich , this was an issue in our AWS Configuration, sorry for the late reply but it took us a while to diagnose the problem and understand what's going on. It's not related to Terraform.
