### ISSUE TITLE
Add support for adding IAM role to Aurora DB clusters.

### ISSUE THREAD

**Issue by HassanJaveed84** [hashicorp/terraform-provider-aws#17216]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS provides ability to add role to Aurora DB cluster through https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_AddRoleToDBCluster.html
Currently there seems to be no way of doing that in terraform. 

### New or Affected Resource(s)

* aws_rds_cluster_role_association

### Potential Terraform Configuration

```hcl
resource "aws_rds_cluster_role_association" "example" {
  cluster_identifier = aws_rds_cluster.example.id
  role_arn           = aws_iam_role.example.arn
}
 ```

### References

* https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_AddRoleToDBCluster.html

**Comment by DrFaust92** [comment]
Hi!, The `aws_rds_cluster` resource seems to have an `iam_roles` argument. that calls the `AddRoleToDBCluster` does this help you?

**Comment by bflad** [comment]
Closing due to lack of response.

**Comment by HassanJaveed84** [comment]
Apologies, I missed this before. Our cluster is not under terraform otherwise we would have been able to use what you suggested @DrFaust92
