### ISSUE TITLE
aws_elasticsearch_domain: Allow setting custom endpoint

### ISSUE THREAD

**Issue by phyrog** [hashicorp/terraform-provider-aws#17213]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

According to the [API docs](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-configuration-api.html#es-configuration-api-actions-createelasticsearchdomain), elastic search domains support three fields not yet supported by Terraform:

- DomainEndpointOptions.CustomEndpointEnabled
- DomainEndpointOptions.CustomEndpoint
- DomainEndpointOptions.CustomEndpointCertificateArn

These allow users to use a custom endpoint for their elastic search domain instead of the auto-generated one.

### New or Affected Resource(s)

* aws_elasticsearch_domain

### Potential Terraform Configuration

```hcl
resource "aws_elasticsearch_domain" "es" {
  domain_name           = var.domain
  elasticsearch_version = "6.3"

  domain_endpoint_options {
    custom_endpoint_enabled         = true
    custom_endpoint                 = "www.my-custom-endpoint.com"
    custom_endpoint_certificate_arn = "arn:aws:iam::123456789012:certificate/my-certificate"
  }
}
```

### References

* https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-configuration-api.html#es-configuration-api-actions-createelasticsearchdomain
* https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-customendpoint.html
* https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-elasticsearch-service-now-supports-defining-a-custom-name-for-your-domain-endpoint/

**Comment by ewbankkit** [comment]
@phyrog Thanks for raising this issue.
It has already been noticed in #16059. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by phyrog** [comment]
Ah for some reason that issue did not show up when I searched for existing issues
