### ISSUE TITLE
aws_instance ebs_block_device volume_type ignored when changed

### ISSUE THREAD

**Issue by dthvt** [hashicorp/terraform-provider-aws#17218]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.6
+ provider registry.terraform.io/hashicorp/aws v3.24.1

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_instance" "test" {
  ami = "ami-0be2609ba883822ec"
  instance_type = "t3.micro"
  ebs_block_device {
    device_name = "/dev/sdb"
    volume_size = 50
    volume_type = "gp2"
    tags = {
      Name = "test-case"
    }
  }
  tags = {
    Name = "test-case"
  }
}

```

### Debug Output

https://gist.github.com/dthvt/1113a01ebb0aed69577a455c297af677

### Expected Behavior

The block device should be modified to the new volume_type when changed in code.

### Actual Behavior

volume_type changes are ignored.

### Steps to Reproduce

1. `terraform apply`
2. Modify volume_type to a new type (i.e. "gp3").
3. `terraform apply` which will show no changes required.

### References

* #0000

**Comment by dthvt** [comment]
It looks like ebs_block_device volume_type is also set to force new true, which is probably wrong.

**Comment by ewbankkit** [comment]
Related:

* https://github.com/hashicorp/terraform-provider-aws/issues/2709

@dthvt Thanks for raising this issue.
There is a note in the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#block-devices):

![ebs-block-device-drift](https://user-images.githubusercontent.com/2404182/105411299-38a51e00-5c01-11eb-9c9b-cdf1131039fe.PNG)

**Comment by dthvt** [comment]
Apologies, I looked for existing issues but I guess I didn't search back far enough.  And I regretfully didn't think to check the documentation for a known caveat.  Given that the necessary information appears to be retrieved from the API in the debug log, is there some sort of technical barrier to updating block devices, or is this just a "it's not implemented so don't try to do it" situation?

**Comment by ewbankkit** [comment]
@dthvt Now worries, there is a LOT of documentation for the `aws_instance` resource.
My guess is that this pattern is following the underlying AWS EC2 API where block devices can be specified in the [`RunInstances`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RunInstances.html) call that creates the instance but there is no instance API to update the instance's block devices, the [`ModifyVolume`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyVolume.html) API must be used and that logically belongs to the `aws_ebs_volume` resource.

There is similar behavior for the instance's ENI(s):

> Each of the network_interface blocks attach a network interface to an EC2 Instance during boot time. However, because the network interface is attached at boot-time, replacing/modifying the network interface WILL trigger a recreation of the EC2 Instance. If you should need at any point to detach/modify/re-attach a network interface to the instance, use the aws_network_interface or aws_network_interface_attachment resources instead.

except here the `ForceNew` does take effect (I think the reason it doesn't for the `ebs_block_device` attribute is the additional `Computed` flag on the attribute).
