### ISSUE TITLE
aws_identitystore_user: can't process more than 7 data sources at once

### ISSUE THREAD

**Issue by rvoitenko** [hashicorp/terraform-provider-aws#17214]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.14.5
 * provider registry.terraform.io/hashicorp/aws v3.24.1

### Affected Resource(s)

* aws_identitystore_user

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "aws_ssoadmin_instances" "example" {}

data "aws_identitystore_user" "all" {
  for_each          = toset(yamldecode(file("user-roles.yaml"))[*].user)
  identity_store_id = identity_store_id = tolist(data.aws_ssoadmin_instances.example.identity_store_ids)[0]

  filter {
    attribute_path  = "UserName"
    attribute_value = each.key
  }
}
```

### Debug Output
```
2021-01-21T10:21:11.649+0100 [INFO]  plugin.terraform-provider-aws_v3.24.1_x5: 2021/01/21 10:21:11 [DEBUG] [aws-sdk-go] {"Users":[{"UserId":"936707e5a6-5e42b25b-830d-44d9-b883-5804c4c396d7","UserName":"user@example.com"}]}: timestamp=2021-01-21T10:21:11.649+0100
2021/01/21 10:21:11 [TRACE] EvalWriteState: using RefreshState for data.aws_identitystore_user.all["user@example.com"]
2021/01/21 10:21:11 [TRACE] EvalWriteState: writing current state object for data.aws_identitystore_user.all["user@example.com"]
2021/01/21 10:21:11 [TRACE] EvalWriteState: writing current state object for data.aws_identitystore_user.all["user@example.com"]
2021/01/21 10:21:11 [TRACE] vertex "data.aws_identitystore_user.all[\"user@example.com\"]": visit complete
2021/01/21 10:21:11 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/01/21 10:21:11 [TRACE] vertex "data.aws_identitystore_user.all": dynamic subgraph encountered errors
2021/01/21 10:21:11 [TRACE] vertex "data.aws_identitystore_user.all": visit complete
2021/01/21 10:21:11 [TRACE] vertex "data.aws_identitystore_user.all (expand)": dynamic subgraph encountered errors
2021/01/21 10:21:11 [TRACE] vertex "data.aws_identitystore_user.all (expand)": visit complete
2021/01/21 10:21:11 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/aws\"] (close)" errored, so skipping
2021/01/21 10:21:11 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/01/21 10:21:11 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/01/21 10:21:11 [INFO] backend/local: plan operation completed

Error: no Identity Store User found matching criteria; try different search


2021-01-21T10:21:11.650+0100 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-01-21T10:21:11.655+0100 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/aws/3.24.1/darwin_amd64/terraform-provider-aws_v3.24.1_x5 pid=69566
2021-01-21T10:21:11.655+0100 [DEBUG] plugin: plugin exited
```

### Expected Behavior

I should always be able to request more than 7 data.aws_identitystore_user source(more details in Factoids)
Also if user not found in Identity Store, terraform should at least include user name in Error message without setting debug flag.

### Actual Behavior

Terraform stops with an error:
```
Error: no Identity Store User found matching criteria; try different search
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids
I'm trying to make batch AWS SSO account assignments via aws_ssoadmin_account_assignment resource, which require Identity Store User Id for each user.
That's why I've created dynamic data.aws_identitystore_user source to fetch Id of each user in batch.
But when number of users is more than 7 terraform reporting "no Identity Store User found matching criteria" which is not true, because I manually verify each reported user and they exist in  Identity Store.
Each run terraform report this error about random user from the list. So maybe it's related to Identity Store API, I'm not sure.

**Comment by rvoitenko** [comment]
The error also reproduced when I add 8 individual uniq aws_identitystore_user data sources.

**Comment by anGie44** [comment]
Hi @rvoitenko, thank you for raising this issue. Unfortunately, I'm not able to reproduce this on my end with 10 users atm; i'm only using the `ssoadmin_instances` and `identitystore_user` and data-sources.  

Do you mind providing the configuration you have for the `ssoadmin_account_assignment` resource? 

Also to start isolating where the issue may be occurring, are you experiencing this issue only when using these data-sources in conjunction w/the `ssoadmin_account_assignment` resource ?

**Comment by rvoitenko** [comment]
Yes, the issue was on my side - one of the users I requested  was not exist in AWS SSO. 
However, I had to verify all users manually because terraform trace log didn't show which user is problematic.
I've run terraform with

```
TF_LOG=trace terraform plan -lock=false -parallelism=0
```

And there is no single sign in the trace log about problematic user.
For example:
```
2021-01-21T10:21:11.649+0100 [INFO]  plugin.terraform-provider-aws_v3.24.1_x5: 2021/01/21 10:21:11 [DEBUG] [aws-sdk-go] {"Users":[{"UserId":"936707e5a6-5e42b25b-830d-44d9-b883-5804c4c396d7","UserName":"user1@example.com"}]}: timestamp=2021-01-21T10:21:11.649+0100
2021/01/21 10:21:11 [TRACE] EvalWriteState: using RefreshState for data.aws_identitystore_user.all["user1@example.com"]
2021/01/21 10:21:11 [TRACE] EvalWriteState: writing current state object for data.aws_identitystore_user.all["user1@example.com"]
2021/01/21 10:21:11 [TRACE] EvalWriteState: writing current state object for data.aws_identitystore_user.all["user1@example.com"]
2021/01/21 10:21:11 [TRACE] vertex "data.aws_identitystore_user.all[\"user1@example.com\"]": visit complete
2021/01/21 10:21:11 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/01/21 10:21:11 [TRACE] vertex "data.aws_identitystore_user.all": dynamic subgraph encountered errors
2021/01/21 10:21:11 [TRACE] vertex "data.aws_identitystore_user.all": visit complete
2021/01/21 10:21:11 [TRACE] vertex "data.aws_identitystore_user.all (expand)": dynamic subgraph encountered errors
2021/01/21 10:21:11 [TRACE] vertex "data.aws_identitystore_user.all (expand)": visit complete
2021/01/21 10:21:11 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/aws\"] (close)" errored, so skipping
2021/01/21 10:21:11 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/01/21 10:21:11 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/01/21 10:21:11 [INFO] backend/local: plan operation completed

Error: no Identity Store User found matching criteria; try different search
```

Error message come after messages about user1@example.com, but this user is correct.
The issue can be closed but it can potentially make problems with debug of similar scenario. Especially when you process 100+ users. Would be nice if terraform can return little bit more verbose error, at minimum with username.
Thank you!

**Comment by anGie44** [comment]
I see @rvoitenko, thank you for the feedback! Will definitely take a note to update the error messaging w/more context 👍
