### ISSUE TITLE
aws_cloudwatch_event_target: requiring RunCommandParameters with custom automation ssm_document 

### ISSUE THREAD

**Issue by rbbrasil** [hashicorp/terraform-provider-aws#17223]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I'm trying to create a "SSM Automation" target in a CloudWatch Event, but when I use a custom `aws_ssm_document`, Terraform forces me to use a "SSM Command" as a Target to my CloudWatch Rule, demanding the `run_command_targets` parameter in my `aws_cloudwatch_event_target` resource, but this type of target won't work with my document, as its an Automation type document.

I got no errors when I use a regular AWS Automation Document. My target points to an SSM Automation correctly.

### Terraform CLI and Terraform AWS Provider Version

```
# terraform version
Terraform v0.13.0-beta2
+ provider registry.terraform.io/hashicorp/aws v3.3.0
```

### Affected Resource(s)

* aws_cloudwatch_event_target
* aws_ssm_document

### Terraform Configuration Files
Automation type SSM Document creation:
```hcl
resource "aws_ssm_document" "start_rds_doc" {
  name            = "Start_RDSCluster"
  document_type   = "Automation"
  document_format = "YAML"
  target_type     = "/AWS::RDS::DBCluster"
  content         = <<DOC
---
description: Start RDS Cluster
schemaVersion: "0.3"
assumeRole: "{{ AutomationAssumeRole }}"
parameters:
  ClusterId:
    type: String
    description: (Required) RDS Cluster Id to start
  AutomationAssumeRole:
    type: String
    description: (Optional) The ARN of the role that allows Automation to perform the actions on your behalf.
    default: ""
mainSteps:
  -
    name: AssertNotStartingOrAvailable
    action: aws:assertAwsResourceProperty
    isCritical: false
    onFailure: step:StartCluster
    nextStep: CheckStart
    inputs:
      Service: rds
      Api: DescribeDBClusters
      DBClusterIdentifier: "{{ClusterId}}"
      PropertySelector: "$.DBClusters[0].Status"
      DesiredValues: ["available", "starting"]
  -
    name: StartCluster
    action: aws:executeAwsApi
    inputs:
      Service: rds
      Api: StartDBCluster
      DBClusterIdentifier: "{{ClusterId}}"
  -
    name: CheckStart
    action: aws:waitForAwsResourceProperty
    onFailure: Abort
    maxAttempts: 10
    timeoutSeconds: 600
    inputs:
      Service: rds
      Api: DescribeDBClusters
      DBClusterIdentifier: "{{ClusterId}}"
      PropertySelector: "$.DBClusters[0].Status"
      DesiredValues: ["available"]
    isEnd: true
...
DOC
}
```

Creation of Event Target (should be a "SSM Automation" type):
```hcl
resource "aws_cloudwatch_event_target" "rds_start" {
  count = var.enable ? 1 : 0
  arn   = var.is_aurora ? data.aws_ssm_document.start_rds_doc.arn : "arn:aws:ssm:${data.aws_region.current.name}::automation-definition/AWS-StartRdsInstance:$DEFAULT"

  input = <<DOC
{
	"ClusterId": ["${var.identifier}"],
    "AutomationAssumeRole": ["${aws_iam_role.ssm_automation[0].arn}"]
}
DOC

  role_arn  = aws_iam_role.event[0].arn
  rule      = aws_cloudwatch_event_rule.rds_start[0].name
  target_id = "rds-scheduler-${var.identifier}-start"
}
```

### Output Error:
```
Error: Creating CloudWatch Event Target failed: ValidationException: Parameter RunCommandParameters is not valid for target rds-scheduler-start.
        status code: 400, request id: f4411608-331c-484f-8962-1c69e5e94212
```

### Expected Behavior
Create a "SSM Automation" Target to my CloudWatch Event Rule.

### Actual Behavior
Forces a creation of a "SSM Command", demanding `run_command_targets` parameter.

**Comment by NHoppe** [comment]
Hey @rbbrasil,

I ran into a similar issue with a different version of AWS provider (`2.70.0`). However, [this workaround mentioned in the issue #6461 worked for me](https://github.com/terraform-providers/terraform-provider-aws/issues/6461#issuecomment-510845647) and `terraform apply` works now. Unfortunately, I cannot guarantee that the overall workflow will work using this workaround because I am still trying to make my logic to work on AWS.

**Comment by ewbankkit** [comment]
@rbbrasil Thanks for raising this issue.
It has already been noticed in #17619. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
