### ISSUE TITLE
Add connection termination control to AWS LB target group

### ISSUE THREAD

**Issue by austinbutler** [hashicorp/terraform-provider-aws#17227]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow setting [`deregistration_delay.connection_termination.enabled`](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#target-group-attributes) on [`aws_lb_target_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group).

### New or Affected Resource(s)

* aws_lb_target_group

### Potential Terraform Configuration

```hcl
resource "aws_lb_target_group" "test" {
  name     = "tf-example-lb-tg"
  port     = 80
  protocol = "TCP"
  vpc_id   = aws_vpc.main.id
  connection_termination = true
}
```

**Comment by MeisterMasi** [comment]
This new option deregistration_delay.connection_termination.enabled is only for target groups assigned to network load balancers. So in the example configuration the protocol "HTTP" is misleading, better choose protocol "TCP" in the example.

**Comment by austinbutler** [comment]
@MeisterMasi you are right, I just did a quick copy and paste. Edited the request.

**Comment by mailtoparveen** [comment]
has it been added ?

**Comment by jtjeferreira** [comment]
Although the default value is false, in the AWS UI the recommended value is true...

![image](https://user-images.githubusercontent.com/943051/123133254-75db3980-d447-11eb-916c-58fd0de5114e.png)

**Comment by gkirill** [comment]
Would be nice to have it.

**Comment by ayellapurkar** [comment]
Any timeline by when this will be supported ?

**Comment by loitho** [comment]
Hi, 
in the spirit of "be the change you want to see in the world", I proposed a PR for this, feel free to upvote it so it gets prioritized :) 
https://github.com/hashicorp/terraform-provider-aws/pull/21130

**Comment by smcglincy** [comment]
Should the default value be changed to 'true' to match the AWS UI recommendation?
Please see @jtjeferreira comment

**Comment by loitho** [comment]
If creating the ressource through the AWS console doesn't set the value to `true`, I would assume terraform to match this behavior.
Maybe adding a bit more detail in the Terraform documentation to indicate that the option is recommended by AWS to be set to true would be better ?

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters roadmap. If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!
