### ISSUE TITLE
Fails to manage permissions on registered data lake location

### ISSUE THREAD

**Issue by mristau-gn** [hashicorp/terraform-provider-aws#17222]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v0.12.29
+ provider.aws v3.22.0
```

### Affected Resource(s)

* aws_lakeformation_permissions

### Terraform Configuration Files

```tf
resource "aws_lakeformation_permissions" "s3_lake_permissions" {
  principal   = "<principal role arn>"
  permissions = ["ALL"]

  data_location {
    arn = "<data lake location arn>"
  }
}
```

Same as example usage in docs: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lakeformation_permissions

### Actual Behavior

```
Error: error creating Lake Formation Permissions (input: {
  Permissions: ["ALL"],
  Principal: {
    DataLakePrincipalIdentifier: "<principal role arn>"
  },
  Resource: {
    DataLocation: {
      ResourceArn: "<data lake location arn>"
    }
  }
}): error creating Lake Formation Permissions: InvalidInputException: Permissions modification is invalid.
```

### Steps to Reproduce

1. `terraform apply`

### References

* Relates to PR: https://github.com/hashicorp/terraform-provider-aws/pull/13396

**Comment by patrickdeutsch-wk** [comment]
I was struggling on this for a minute especially since the example uses "ALL"
I switched to  `permissions = ["DATA_LOCATION_ACCESS"]` and it seems to have worked. https://docs.aws.amazon.com/lake-formation/latest/dg/lf-permissions-reference.html#perm-location

**Comment by mristau-gn** [comment]
Thanks @patrickdeutsch-wk . This works for me as well.
