### ISSUE TITLE
Implement advanced filtering for patch baseline data source

### ISSUE THREAD

**Issue by AlinoeDoctari** [hashicorp/terraform-provider-aws#17239]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The current implementation of the patch baseline resource does not allow to filter resources with the same prefix. For instance the default patch baseline "AWS-WindowsPredefinedPatchBaseline-OS" cannot be retrieved as another default baseline with the name as prefix exists: sAWS-WindowsPredefinedPatchBaseline-OS-Applications".
We should be able to retrieve all baseline matching the prefix and implement a local advanced filtering with full support of regexp (something similar to the aws ami data source).

### New or Affected Resource(s)

data aws_ssm_patch_baseline

### Potential Terraform Configuration

```hcl
data "aws_ssm_patch_baseline" "windows_os_update" {
  owner            = "AWS"
  name_prefix      = "AWS-WindowsPredefinedPatchBaseline-OS"
  operating_system = "WINDOWS"
}
```

### References

* #0000

**Comment by DrFaust92** [comment]
SInguar resources return a single resource by design, to return a set or results will need to implement a plural data source, i.e. `aws_ssm_patch_baselines`
