### ISSUE TITLE
AWS S3 intelligent tiering archive access tier

### ISSUE THREAD

**Issue by KVInventoR** [hashicorp/terraform-provider-aws#17245]
I couple of time ago, AWS released new feature for S3:  Intelligent-Tiering archive access tiers 
Is it possible to use this feature with terraform?

https://aws.amazon.com/ru/blogs/aws/s3-intelligent-tiering-adds-archive-access-tiers/

It's not the same as Lifecycle configuration and probably required some changes.

**Comment by ewbankkit** [comment]
@KVInventoR Thanks for raising this issue.
It has already been noticed in #16123. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
