### ISSUE TITLE
Support other launch template tag_specifications

### ISSUE THREAD

**Issue by leolorenzoluis** [hashicorp/terraform-provider-aws#17253]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS already supports other tag specifications for other resources

### New or Affected Resource(s)

* aws_launch_template

### Potential Terraform Configuration

```hcl
 tag_specifications {
    resource_type = "network-interface"
    tags          = var.tags
  }
```

### References

* https://github.com/hashicorp/terraform-provider-aws/blob/master/aws/resource_aws_launch_template.go#L588

**Comment by ewbankkit** [comment]
@leolorenzoluis Thanks for raising this issue.

According to the [AWS User Guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-templates.html#create-launch-template-define-parameters):

> You can tag the instance, the volumes, Spot Instance requests, or all three.

whereas the [AWS API reference]:(https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RequestLaunchTemplateData.html#API_RequestLaunchTemplateData_Contents) says

> You can only tag instances and volumes on launch.

In the AWS console:

![create-launch-template](https://user-images.githubusercontent.com/2404182/105578644-ae1f0480-5d4f-11eb-80cb-a94dc9c3f9b2.PNG)

which is what the AWS Provider code has implemented.

To tag any other EC2 resources created implicitly via the launch template you can use the [`aws_ec2_tag`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_tag) resource.

**Comment by ewbankkit** [comment]
Related:

* https://github.com/hashicorp/terraform-provider-aws/issues/14558
