### ISSUE TITLE
Sagemaker App Image Config - add tagging support

### ISSUE THREAD

**Issue by DrFaust92** [hashicorp/terraform-provider-aws#17267]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A follow-up issue to #17221, to support tagging. currently there is a server side bug with deleting tagged Sagemaker App Image configs (see https://github.com/hashicorp/terraform-provider-aws/pull/17221#issuecomment-766194963)

### New or Affected Resource(s)

* aws_sagemaker_app_image_config

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #17221

**Comment by maciej-wilczynski** [comment]
Also documentation says that tags are optional here but the truth is:
```
Error: Unsupported argument

  on sage_maker_image.tf line 21, in resource "aws_sagemaker_app_image_config" "image_config":
  21:   tags = {

An argument named "tags" is not expected here.
```
and there is no argument in https://github.com/hashicorp/terraform-provider-aws/blob/v3.29.1/aws/resource_aws_sagemaker_app_image_config.go#L25

**Comment by DrFaust92** [comment]
probably a leftover from when i tried to implement. sorry! need to be deleted from docs
