### ISSUE TITLE
Do we have a plan to create terraform-aws-waf modules?

### ISSUE THREAD

**Issue by anemptyair** [hashicorp/terraform-provider-aws#17273]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Do we have a plan to create terraform-aws-waf modules? 
If not , why? I want to know what is the motivation that push u to create a module for it.
### New or Affected Resource(s)

* aws_waf_rule
* ...

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by DrFaust92** [comment]
Terraform module are not related to this repository, as this repo has to do with the AWS Provider and its development.

for community modules (particularly AWS community module) please see https://registry.terraform.io/namespaces/terraform-aws-modules or by any means, create a module of your own. although a search in the Terraform registry is bound to come up with several results.
