### ISSUE TITLE
Terraform AWS provider resources for Amazon IVS(Interactive Video Service)

### ISSUE THREAD

**Issue by moosakhalid** [hashicorp/terraform-provider-aws#17272]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Just like the header reads, Amazon IVS has been out for a while and there's no resource for it in Terraform AWS provider. I don't see a resource in the AWS provider on the roadmap either. Are there any plans to work on getting it into the AWS provider?

something like:

amazon_ivs_*

Here's a link to it's Boto3 API page for a list of API calls and methods that pertain to it.

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ivs.html

**Comment by ir-vsem** [comment]
Greeting has there an progress made on this? Thanks
