### ISSUE TITLE
Adding support for multiple AWS Image builder components for aws_imagebuilder_image_recipe resource

### ISSUE THREAD

**Issue by zaldevops** [hashicorp/terraform-provider-aws#17276]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Can support for multiple components using a components block for aws_imagebuilder_image_recipe resource be added. Currently there is only a component block. My suggestion is to change that to components to allow additional components to be added. This feature is already available in Cloudformation

### New or Affected Resource(s)

* aws_imagebuilder_image_recipe

### Potential Terraform Configuration

```hcl
resource "aws_imagebuilder_image_recipe" "example" {

  components { 
    component_arns = [aws_imagebuilder_build_component.example.arn, aws_imagebuilder_test_component.example.arn]
    }
}
```

### References

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-imagerecipe.html

**Comment by lithiumoxide** [comment]
This is something we would be very interested in seeing in place.

**Comment by sb-travelperk** [comment]
Same here... but note that aws-cli doesn't seem to provide any function to update a recipe (yet?), would be nice for the 2 to come together :wink:

**Comment by nleskiw** [comment]
> Same here... but note that aws-cli doesn't seem to provide any function to update a recipe (yet?), so there might be a limitation somewhere. It would be nice for the 2 features to come together wink

@sb-travelperk

I think that ImageBuilder expects you to bump the `--semantic-version` to update an existing AWS ImageBuilder Recipe.  Same with AWS ImageBuilder Components. 


I suppose you could always use `delete-recipe` and `create-recipe` sequentially to effectively "update" a recipe, but then you'd lose all the historic versions of that recipe. You'd perpetually only have version 1.0.0, then though. AWS keeps track of the changes for you when you increase the version number. 

I am a bit confused though. If you could explain how this relates to not allowing multiple components in a recipe (which is allowed by both the web console and the CLI) it would be appreciated.

**Comment by Dogers** [comment]
The recipe resource already supports multiple components, you just add it repeatedly, or via a dynamic:
```hcl
  dynamic "component" {
    for_each = var.components
    content {
      component_arn = component.value
    }
  }
```

Changing this list does unfortunately cause the recipe to be replaced even with a version change as TF has no concepts of versions, only _what is_, but then the history is saved in your code anyway!

**Comment by flickerfly** [comment]
@Dogers Thanks for the workaround.

So if this isn't a functional bug, then it is a UI bug. It is overly complex.

Why can't I just pass a list of component ARNs? There is only one argument to component{}, component_arn. Then component_arn only takes one arn as input. This is awkward. The JSON output of the aws cli when I get an image recipe seems to be more consistent with my expectations.

```
        "components": [
            {
                "componentArn": "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/amazon-cloudwatch-agent-windows/x.x.x"
            },
            {
                "componentArn": "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/reboot-windows/x.x.x"
            },
            {
                "componentArn": "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/simple-boot-test-windows/x.x.x"
            },
            {
                "componentArn": "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/windows-activation-test/x.x.x"
            },
            {
                "componentArn": "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/windows-is-ready-with-password-generation-test/x.x.x"
            },
            {
                "componentArn": "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/ebs-volume-usage-test-windows/x.x.x"
            },
            {
                "componentArn": "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/ec2-network-route-test-windows/x.x.x"
            },
            {
                "componentArn": "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/eni-attachment-test-windows/x.x.x"
            },
            {
                "componentArn": "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/reboot-test-windows/x.x.x"
            }
        ]
```

That same thing in terraform code is

```
  component {
    component_arn  = "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/amazon-cloudwatch-agent-windows/x.x.x"
  }
  component {
    component_arn  = "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/reboot-windows/x.x.x"
  }
  component {
    component_arn  = "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/simple-boot-test-windows/x.x.x"
  }
  component {
    component_arn  = "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/windows-activation-test/x.x.x"
  }
  component {
    component_arn  = "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/windows-is-ready-with-password-generation-test/x.x.x"
  }
  component {
    component_arn  = "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/ebs-volume-usage-test-windows/x.x.x"
  }
  component {
    component_arn  = "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/ec2-network-route-test-windows/x.x.x"
  }
  component {
    component_arn  = "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/eni-attachment-test-windows/x.x.x"
  }
  component {
    component_arn  = "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/reboot-test-windows/x.x.x"
  }
```

I'd rather write it like this.
```
  component_arns  = [ 
    "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/amazon-cloudwatch-agent-windows/x.x.x"
    "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/reboot-windows/x.x.x"
    "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/simple-boot-test-windows/x.x.x" 
    "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/windows-activation-test/x.x.x"
    "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/windows-is-ready-with-password-generation-test/x.x.x"
    "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/ebs-volume-usage-test-windows/x.x.x"
    "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/ec2-network-route-test-windows/x.x.x"
    "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/eni-attachment-test-windows/x.x.x"
    "arn:aws-us-gov:imagebuilder:us-gov-east-1:aws:component/reboot-test-windows/x.x.x" 
  ]
```

**Comment by kclarkey** [comment]
FWIW, I think the existing components block pattern is the correct approach. While it may have initially presented itself as an over-engineered implementation of a simple object, recent enhancements to components (i.e. addition of [parameters](https://aws.amazon.com/about-aws/whats-new/2021/07/ec2-image-builder-supports-parameters-components-creating-custom-images/) this past July) seems to support its initial design, as we now have a path to support the addition of parameters w/out introducing breaking changes. Ref: https://github.com/hashicorp/terraform-provider-aws/issues/20855

The new AWS API response looks similar to this: 
```
"components": [ 
         { 
            "componentArn": "string",
            "parameters": [ 
               { 
                  "name": "string",
                  "value": [ "string" ]
               }
            ]
         }
      ],
```
https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_GetImageRecipe.html#API_GetImageRecipe_ResponseSyntax

**Comment by AmitArie** [comment]
Hi all, 
Any updates when we will be able to use parameters in the components section?

**Comment by corapoid** [comment]
Hi,
Any updates?

**Comment by mattburgess** [comment]
parameter support was added in [4.0.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#400-february-10-2022).

I think this issue is therefore ready to close; multiple component blocks can be specified and a component block supports parameters.

**Comment by kamilturek** [comment]
Hey @ewbankkit, could we please close this issue? It has many upvotes but the provider already supports multiple components and parameters.
