### ISSUE TITLE
resource aws_iam_access_key doesn't support import

### ISSUE THREAD

**Issue by cedricbastin** [hashicorp/terraform-provider-aws#17288]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Make it possible to import AWS IAM Access Keys that were manually via the AWS Console. It should be possible to run
`terraform import aws_iam_access_key.my_access_key <Access Key ID>` and bring them under Terraform management.

Currently this is not supported and results in the error message: `resource aws_iam_access_key doesn't support import`.

### Affected Resource

* `aws_iam_access_key`

### Potential Terraform Configuration

```hcl
resource "aws_iam_access_key" "my_access_key" {
  user = "${aws_iam_user.my_user.name}"
}
```

**Comment by bflad** [comment]
Hi @cedricbastin 👋  Thank you for raising this. We can certainly add import support for the resource. Please note though, that the IAM API does not provide a method for fetching the secret, so imported resources cannot provide that that information. Imported resources will however be able to perform `status` updates and be deleted, which is still useful.

**Comment by cedricbastin** [comment]
@bflad Thanks for getting back to me and for clarifying this, I was also wondering about this! 👍
There would still be value in tracking the existence of the keys in code, for inventory reasons.
Would it be possible for Terraform to warn about old (> x days) access keys during a plan/apply?

**Comment by bflad** [comment]
@cedricbastin not with the Terraform AWS Provider itself -- its primary function is to map AWS APIs onto Terraform resources. This is typically a space for Policy as Code/Configuration tooling such as [Sentinel](https://www.hashicorp.com/sentinel), [Open Policy Agent](https://www.openpolicyagent.org/docs/latest/terraform/), etc. which can provide informational, warning, or failure information based on Terraform configuration or state.
