### ISSUE TITLE
Data source to query ssm parameter by path

### ISSUE THREAD

**Issue by RaguRJ** [hashicorp/terraform-provider-aws#17283]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, there are no data sources in the AWS Terraform provider to query SSM parameter by path. I am working on a couple of projects where secrets are organized in hierarchical structure provided by the SSM parameter store. I was able to create secrets in hierarchical structure via terraform but the `aws_ssm_parameter` data source only queries a single secret with the entire path provided in the query by using the [GetParameter](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ssm#Client.GetParameter) API call. It would be nice to have a separate data source or a flag in the `aws_ssm_parameter` data source for the [GetParametersByPath](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ssm#Client.GetParametersByPath) API call.

### New or Affected Resource(s)

* aws_ssm_parameter

### Potential Terraform Configuration

**Option 1 - Adding a boolean to the existing datasource**
```hcl
data "aws_ssm_parameter" "foo" {
  name = "foo/bar/"
  by_path = true //defaults to false
}
```
**Option 2 - new data source**
```hcl
data "aws_ssm_parameter_by_path" "foo" {
  name = "foo/bar/"
}
```

### References

* https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-hierarchies.html
* https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ssm#Client.GetParametersByPath

**Comment by ghostd** [comment]
Is this a duplicate of #9429 (which seems to have a PR #9615)?

**Comment by RaguRJ** [comment]
Yes, that seems to be the case. I might have missed it somehow. I will close this issue and follow the PR. Thanks.
