### ISSUE TITLE
`self=true` option in security group rule doesn't work in Saopaulo (`sa-east-1`)

### ISSUE THREAD

**Issue by imcheck** [hashicorp/terraform-provider-aws#17308]
### Terraform CLI and Terraform AWS Provider Version
Terraform Version: `v0.13.5`
AWS Provider Version: `v3.25.0`

### Affected Resource(s)

* aws_security_group
* aws_security_group_rule

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_security_group" "sg" {
  name   = "sg"
  vpc_id = "vpc-9a44a6fc"
}

resource "aws_security_group_rule" "sg" {
  type      = "ingress"
  from_port =1 
  to_port   = 65535
  protocol  = "tcp"
  self = true # This option doesn't work !!!
  security_group_id = aws_security_group.sg.id
}

```

### Debug Output
```bash
Error: Error authorizing security group rule type ingress: InvalidGroup.NotFound: The security group 'sg-06b3d33dbd32b821a' does not exist
        	status code: 400, request id: 66d7abfb-82ae-47ab-9396-ced4713b2f62
```
### Expected Behavior

This HCL code work in other region like Tokyo, Oregon, ...

### Actual Behavior

As you can see `Debug Output`, you will face the problem.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ewbankkit** [comment]
@imcheck Thanks for raising this issue.

I can reproduce something similar with our acceptance tests:

```console
# Default is us-west-2:
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSSecurityGroupRule_SelfReference' ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSSecurityGroupRule_SelfReference -timeout 120m
=== RUN   TestAccAWSSecurityGroupRule_SelfReference
=== PAUSE TestAccAWSSecurityGroupRule_SelfReference
=== CONT  TestAccAWSSecurityGroupRule_SelfReference
--- PASS: TestAccAWSSecurityGroupRule_SelfReference (26.36s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	26.452s
# Random other region:
$ AWS_DEFAULT_REGION=eu-south-1 make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSSecurityGroupRule_SelfReference' ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSSecurityGroupRule_SelfReference -timeout 120m
=== RUN   TestAccAWSSecurityGroupRule_SelfReference
=== PAUSE TestAccAWSSecurityGroupRule_SelfReference
=== CONT  TestAccAWSSecurityGroupRule_SelfReference
--- PASS: TestAccAWSSecurityGroupRule_SelfReference (36.47s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	36.558s
# sa-east-1:
$ AWS_DEFAULT_REGION=sa-east-1 make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSSecurityGroupRule_SelfReference' ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSSecurityGroupRule_SelfReference -timeout 120m
=== RUN   TestAccAWSSecurityGroupRule_SelfReference
=== PAUSE TestAccAWSSecurityGroupRule_SelfReference
=== CONT  TestAccAWSSecurityGroupRule_SelfReference
    resource_aws_security_group_rule_test.go:399: Step 1/2 error: Error running apply: 2021/01/27 09:07:35 [DEBUG] Using modified User-Agent: Terraform/0.12.26 HashiCorp-terraform-exec/0.12.0
        
        Error: Error authorizing security group rule type ingress: InvalidGroup.NotFound: The security group 'sg-06b3d33dbd32b821a' does not exist
        	status code: 400, request id: 66d7abfb-82ae-47ab-9396-ced4713b2f62
        
        
--- FAIL: TestAccAWSSecurityGroupRule_SelfReference (21.69s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	21.774s
FAIL
GNUmakefile:27: recipe for target 'testacc' failed
make: *** [testacc] Error 1
```

**Comment by bflad** [comment]
Just to clarify here, this error is not specific to the `self=true` configuration, which is working fine for me in that region:

```
--- PASS: TestAccAWSSecurityGroupRule_SelfReference (36.31s)
```

The original `Error creating Security Group: InvalidVpcID.NotFound: The vpc ID 'vpc-9a44a6fc' does not exist` error from the `aws_security_group` resource and `Error authorizing security group rule type ingress: InvalidGroup.NotFound: The security group 'sg-06b3d33dbd32b821a' does not exist` error from the `aws_security_group_rule` resource likely point to two separate EC2 eventual consistency handling issues on creation.

**Comment by bflad** [comment]
@imcheck in your original configuration you have:

```terraform
resource "aws_security_group" "sg" {
  name   = "sg"
  vpc_id = "vpc-9a44a6fc"
}
```

Can you confirm if that VPC identifier is hardcoded, exists in the `sa-east-1 region (via AWS CLI, e.g. `aws --region sa-east-1 ec2 describe-vpcs`), and confirm that the credentials used by Terraform have the correct permissions? Does running `terraform apply` a second time work as expected?

**Comment by imcheck** [comment]
@ewbankkit
I'm sorry that I made mistake to upload wrong results. ( I got a result same to you)
I faced the problem only in `sa-east-1`.

@bflad 
Thanks for your suggestions ! :)
I already did with your suggestions but it doens't work :(
