### ISSUE TITLE
Error: template body contains an invalid JSON or YAML: invalid character '}' looking for beginning of object key string

### ISSUE THREAD

**Issue by rhel** [hashicorp/terraform-provider-aws#17312]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/aws v3.25.0
$
```

### Affected Resource(s)

* `data.aws_cloudformation_stack`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.24"
    }
  }
}
provider "aws" {
  region     = "eu-west-1"
}
data "aws_cloudformation_stack" "qa" {
  name = "qa"
}
```

### Debug Output

The debug output can be provided privately. 

### Expected Behavior

`data.aws_cloudformation_stack.qa` should be populated by values obtained from the CloudFormation Stack. 

### Actual Behavior

`terraform plan` raises an error "template body contains an invalid JSON or YAML".

```
$ terraform plan

Error: template body contains an invalid JSON or YAML: invalid character '}' looking for beginning of object key string


$
```

### Steps to Reproduce

1. `terraform plan` or `terraform apply`

**Comment by hanggard** [comment]
Agree, have met completely the same issue.

**Comment by bflad** [comment]
Hi folks 👋  I'm trying to reproduce this error using our end-to-end testing suite of the `aws_cloudformation_stack` resource and data source in the `eu-west-1` region, but not having luck. It would be great if we could get at least the CloudFormation `GetTemplate` API response prior to this error with [debug logging enabled](https://www.terraform.io/docs/internals/debugging.html) so we can further troubleshoot. If you are worried about any sensitive data, it can be encrypted with the [HashiCorp GPG Key](https://keybase.io/hashicorp) or redacted as necessary. In addition to the API response that is generating the error, it would also be helpful to know if this only is occurring in the `eu-west-1` region and if you notice anything in particular with the CloudFormation Stacks that might be causing this.
