### ISSUE TITLE
aws_ec2_transit_gateway_route_table does not output ARN

### ISSUE THREAD

**Issue by stobias123** [hashicorp/terraform-provider-aws#17317]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.24
+ provider.aws v3.6.0

### Affected Resource(s)

* `aws_ec2_transit_gateway_route_table`

### Terraform Configuration Files

```hcl
resource "aws_ec2_transit_gateway_route_table" "foo" {
  transit_gateway_id = aws_ec2_transit_gateway.tgw.id
}


output "test" {
   value =aws_ec2_transit_gateway_route_table.foo.arn
}
```

### Expected Behavior

It should output the ARN as described in docs.

### Actual Behavior

ARN is not available as an output

### Steps to Reproduce

See Above tf config

**Comment by ewbankkit** [comment]
@stobias123 Thanks for raising this issue.

The `arn` attribute for the `aws_ec2_transit_gateway_route_table` resource was added via https://github.com/hashicorp/terraform-provider-aws/pull/13921 and released in AWS Provider **v3.15.0**.

Please upgrade your provider to pick up this functionality.
