### ISSUE TITLE
Restrict argument not working

### ISSUE THREAD

**Issue by agenerette-cais** [hashicorp/terraform-provider-aws#17323]
Hi,

My understanding from https://github.com/hashicorp/terraform-provider-aws/issues/11632 is that the Terraform aws provider supports use of a "restricted = true" argument setting for duplicating the AWS GUI behavior:

"When a home directory is set to "Restricted", your users will not be able to access anything outside of that folder, nor will they be able to see the S3 bucket or folder name."

I'm on version 3.9.0 of the provider, though:

MacBook-Pro-3:aws_transfer anthony$ terraform --version
Terraform v0.13.6
+ provider registry.terraform.io/-/aws v3.25.0
+ provider registry.terraform.io/hashicorp/aws v3.9.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

But, I'm still seeing:

Error: Unsupported argument

  on aws_transfer.tf line 285, in resource "aws_transfer_user" "testuser":
 285:   restricted          = true

An argument named "restricted" is not expected here.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by DrFaust92** [comment]
It has been implemented, See https://github.com/hashicorp/terraform-provider-aws/issues/11632#issuecomment-580752501 for more details.
