### ISSUE TITLE
Ability to retrieve all route 53 zones from data.aws_route53_zone

### ISSUE THREAD

**Issue by hfeixas** [hashicorp/terraform-provider-aws#17334]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_route53_zone

### Potential Terraform Configuration

We need the ability to retrieve all of the avialable route 53 hosted zones in the account/region we are targeting. 
Currently we must provide a name/zone_id to the data, however this is information we do not have at the time of deployment.

```hcl
provider "aws" {
  region = "us-east-1"
}
data "aws_route53_zone" "all" {}
```

**Comment by chammock** [comment]
I'd like to see this data resource as `aws_route53_zones` and could closely mimic like `aws_vpcs`

**Comment by yuonoda** [comment]
Hi there, I opened a pull request #17457 to close this issue. As  @chammock suggested above, I mainly copied settings from `aws_vpcs `. I want someone to review this pull request!
