### ISSUE TITLE
aws_launch_template does not support instance_types even though aws_eks_node_groups does

### ISSUE THREAD

**Issue by theothermike** [hashicorp/terraform-provider-aws#17331]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With the recent ability to provide mixed `instance_types` to aws_eks_node_groups, I would expect, since this is an abstraction on `aws_auto_scaling_group`, that the `aws_launch_template` would support mixed `instance_types` as well. 

### New or Affected Resource(s)

* aws_launch_template

### Potential Terraform Configuration

```hcl
resource aws_launch_template my-template {
  <snip>
  instance_types = ["t3.small", "t3.medium"]
 <snip>
}
```

### References

* #0000

**Comment by ewbankkit** [comment]
@theothermike Thanks for raising this issue.
In the [EKS API](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html#API_CreateNodegroup_RequestBody) `instance_types` are specified separate from the `launch_template` and the documentation states

> **instanceType**
>
> Specify the instance types for a node group. If you specify a GPU instance type, be sure to specify `AL2_x86_64_GPU` with the `amiType` parameter. If you specify `launchTemplate`, then you can specify zero or one instance type in your launch template or you can specify 0-20 instance types for instanceTypes. If however, you specify an instance type in your launch template and specify any instanceTypes, the node group deployment will fail. If you don't specify an instance type in a launch template or for instanceTypes, then t3.medium is used, by default. If you specify Spot for capacityType, then we recommend specifying multiple values for instanceTypes. For more information, see Managed node group capacity types and Launch template support in the Amazon EKS User Guide.
>
> Type: Array of strings
>
> Required: No
