### ISSUE TITLE
Amazon Elasticsearch Service extends encryption at rest and node-to-node encryption to existing domains

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#17330]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For domains running Elasticsearch 6.7 or later encryption of data at rest and node-to-node encryption can now be set after domain creation.
This means that the updating the `encrypt_at_rest` and `node_to_node_encryption` attributes will update the domain's configuration - These attributes were not marked as `ForceNew: true` but `resourceAwsElasticSearchDomainUpdate` ignored any change to these attributes

### New or Affected Resource(s)

* [`aws_elasticsearch_domain`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain)

### Potential Terraform Configuration

```hcl
resource "aws_elasticsearch_domain" "example" {
  encrypt_at_rest {
    enabled = true
  }

  node_to_node_encryption {
    enabled = true
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2021/01/amazon-elasticsearch-service-extends-data-encryption-rest-node-to-node-encryption-support-existing-domains/).

Requires [AWS SDK v1.36.33](https://github.com/aws/aws-sdk-go/releases/tag/v1.36.33):

* #17327

**Comment by tmccombs** [comment]
To clarify the current behavior: 

`node_to_node_encryption.enabled` and `encrypt_at_rest.enabled` (as well as the kms_key_id) are marked with `ForceNew: true`, so changing those properties results in terraform recreating the domain (which generally means data loss), although for opensearch and elasticsearch 6.7 and later, AWS allows updating these attributes for existing clusters.

**Comment by YakDriver** [comment]
In my testing, I'm seeing that AWS is allowing updates for es 6.0 as well.

**Comment by jimishs** [comment]
Hi, To add some clarification on version support for encryption of data at rest and node to node encryption

Encryption of data at rest on new domains requires either OpenSearch or Elasticsearch 5.1 or later. Enabling it on existing domains requires either OpenSearch or Elasticsearch 6.7 or later.

Node-to-node encryption on new domains requires any version of OpenSearch, or Elasticsearch 6.0 or later. Enabling node-to-node encryption on existing domains requires any version of OpenSearch, or Elasticsearch 6.7 or later. 

You can find the same info in the official documentation 

https://docs.aws.amazon.com/opensearch-service/latest/developerguide/encryption-at-rest.html

and 

https://docs.aws.amazon.com/opensearch-service/latest/developerguide/ntn.html

**Comment by YakDriver** [comment]
> To clarify the current behavior:
> 
> `(as well as the kms_key_id) are marked with `ForceNew: true`, so changing those properties results in terraform recreating the domain (which generally means data loss), although for opensearch and elasticsearch 6.7 and later, AWS allows updating these attributes for existing clusters.

I have not been able to update the KMS key regardless of version. AWS responds with "not supported."
