### ISSUE TITLE
apigatewayv2_integration SQS-SendMessage does not support MessageAttributes

### ISSUE THREAD

**Issue by rogueturnip** [hashicorp/terraform-provider-aws#17348]
I've been fighting with this one for a while and done a bunch of reading but there is no documentation about this parameter in the integration.  What I have for my configuration is:

```
resource "aws_apigatewayv2_integration" "webhook-api-alana" {
  api_id              = aws_apigatewayv2_api.webhook-api.id
  description         = "Send webhook to SQS "
  credentials_arn     = aws_iam_role.webhookSQS.arn
  integration_type    = "AWS_PROXY"
  integration_subtype = "SQS-SendMessage"
  request_parameters = {
    "QueueUrl"          = var.sqs_queue_url
    "MessageBody"       = "$request.body"
    "MessageAttributes" = jsonencode({ "somename" : { DataType : "String", StringValue : "somevalue" } })
  }
}
```
If I remove MessageAttributes it works fine but as soon as I add it I get the following error:
```
Error: error updating API Gateway v2 integration: BadRequestException: Invalid selection expression specified: Validation Result: warnings : [], errors : [Invalid source: {"somename":{"DataType":"String","StringValue":"somevalue"}} specified for destination: MessageAttributes]
```
I'm hoping this is just a lack of documentation and not an actual bug since lacking this would mean I'd have to use rest api for my integration.

Thanks!

**Comment by ewbankkit** [comment]
@rogueturnip Thanks for raising this issue.
You are correct that AWS documentation here is rather lacking and I only worked this out by playing in the AWS Console.
The [`MessageAttributes`](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-aws-services-reference.html#SQS-SendMessage) value in the `request_parameters` is not the actual [SQS message attributes](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_MessageAttributeValue.html) but is a [selection expression](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-parameter-mapping.html) that specifies where in the API request that the message attributes can be found, for example `"MessageAttributes" = "$request.body.msg_attrs"` would pick out a field `msg_attrs` in the request body and pass whatever is in that field to the SQS API when sending the message.

**Comment by ewbankkit** [comment]
Related:

* https://github.com/hashicorp/terraform-provider-aws/issues/14761
