### ISSUE TITLE
Provider assume role block with profile no longer works with 3.26.0

### ISSUE THREAD

**Issue by JoshiiSinfield** [hashicorp/terraform-provider-aws#17353]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.26.0
```

### Affected Resource(s)

* provider "aws" {}

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  region = "eu-west-1"
  profile = "my-auth-account-profile"
  assume_role {
    role_arn     = "arn:aws:iam::123456789012:role/ROLE"
    session_name = "SESSION_NAME"
  }
  
}
```

### Expected Behavior

Terraform should have used the profile to obtain a session and assumed the role specified in the assume_role block

### Actual Behavior

Terraform plan and apply both fail with  `Error: error configuring Terraform AWS Provider: error creating assume role session: SharedConfigErr: only one credential type may be specified per profile: source profile, credential source, credential process, web identity token, or sso` 

### Steps to Reproduce

1. Setup a profile, using API credentials for a user with assume role perms to a cross-account role
2. setup a role to be assumed cross account using the above profile
3. configure provider using the profile, and specify assume_role block as detailed abouve using the role in step 2.
4. `terraform init` will succeed
5. `terraform apply` will fail

### Important Factoids

This works on Provider version 3.25.0. It's broken in 3.26.0.

### References

* #17352 Sounds very similar

**Comment by ewbankkit** [comment]
Related:

* https://github.com/hashicorp/terraform-provider-aws/pull/17340

**Comment by bflad** [comment]
Hi folks 👋 

This particular error [is from the AWS Go SDK](https://github.com/aws/aws-sdk-go/blob/3974dd034387fbc7cf09c8cd2400787ce07f3285/aws/session/session.go#L39) we depend on:

```
SharedConfigErr: only one credential type may be specified per profile: source profile, credential source, credential process, web identity token, or sso
```

Which was adjusted to include checking for SSO configuration in an AWS shared configuration profile with the support for SSO cached credentials in version 1.37.0 (released as part of Terraform AWS Provider version 3.26.0). If you have both `sso_*` and `source_profile` configuration within the same profile, removing one or the other will likely fix the issue.

This particular validation is being controlled by the AWS Go SDK, so it may be best to track or contribute to these conversations upstream for updates on whether this particular validation might be relaxed:

* https://github.com/aws/aws-sdk-go/pull/3755/files#r566539101
* https://github.com/aws/aws-sdk-go/issues/3763

**Comment by JoshiiSinfield** [comment]
Hi @bflad ,

Thanks for the update, however that's not the case for me.

My profile contains only the secret key and key id, no sso. I do have *other* profiles in the same file that are sso, but not this one. 

Please see below ...
credentials file contains:
```
[my-auth-account-profile]
aws_access_key_id = AKIAVXXXXXXXXXXXXX
aws_secret_access_key = eCXXXXXXXXXXXXXXXXXXXXXX
region = eu-west-1

```

terraform config:
```
provider "aws" {
  region = "eu-west-1"
  profile = "my-auth-account-profile"
  assume_role {
    role_arn     = "arn:aws:iam::123456789012:role/ROLE"
    session_name = "SESSION_NAME"
  }
 
}
```

**Comment by JoshiiSinfield** [comment]
Here is a complete set of configs I have used to replicate the issue:
main.tf:
```hcl
provider "aws" {
  region = "eu-west-1"

  assume_role {
    role_arn = "arn:aws:iam::XXXXX:role/XXXXXX"
  }
}

data "aws_caller_identity" "current" {}

output "acc_id" {
  value = data.aws_caller_identity.current.account_id
}
```

~/.aws/config
```
[default]
sso_start_url = https://XXXXX.awsapps.com/start
sso_region = eu-west-1
sso_account_id = XXXXX
sso_role_name = AdministratorAccess
region = eu-west-1
output = json
credential_process = aws-sso-credential-process --profile default
[profile joshs-test]
region = eu-west-1
output = json
[profile profile2]
sso_start_url = https://XXXXXX.awsapps.com/start
sso_region = eu-west-1
sso_account_id = XXXXXX
sso_role_name = AdministratorAccess
region = eu-west-1
output = json
credential_process = aws-sso-credential-process --profile profile2
```


~/.aws/credentials
```
[joshs-test]
aws_access_key_id = 12345
aws_secret_access_key = aabbcc
```


software versions:
```
terraform -v  
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.26.0
```

Cheers,
Josh

**Comment by martindcernadas** [comment]
I could finally resolved this, updating to the latest GO version: https://golang.org/doc/install  , "go version go1.15.7 linux/amd64"

And everything is fine!

**Comment by abeluck** [comment]
@martindcernadas You mean you updated go and built the aws provider plugin from source?

**Comment by JoshiiSinfield** [comment]
sorry @martindcernadas please can you elaborate?

I've just upgraded from 1.15.2 to 1.15.7_1 and it made no difference. I still receive the error.

Cheers,
Josh

**Comment by JoshiiSinfield** [comment]
Just to confirm - I can get this working by removing all "credential_process" lines from my profiles.

However, I had an older version of awscli (v2.0.55). This was generating credentials with an invalid timestamp. (see [here](https://github.com/hashicorp/terraform-provider-aws/issues/17372) )

I upgraded to 2.1.24, re logged in and the timestamp issue disappeared. 

Therefore I guess this technically isn't an issue any more. HOWEVER, it should have come with a large warning that it needs the latest AWS CLI version to generate credentials with valid timestamps.

**Comment by ollytheninja** [comment]
Came here to say I had `sso_*` configuration and a `credential_process` lines in the same profile in my `.aws/credentials` file.
Issuing a `terraform init` resulted in the `Error: error configuring Terraform AWS Provider: error creating assume role session: SharedConfigErr: only one credential type may be specified per profile: source profile, credential source, credential process, web identity token, or sso` error message.
Removing the `credential_process` line fixed this issue.
After upgrading to terraform 1.0.10 from 1.0.1 (which presumably also comes with newer versions of go) I added the `credential_process` line back into the profile and I don't get an error running terraform.

I am not using an assume role block.

I'm using `provider registry.terraform.io/hashicorp/aws v3.63.0`

Hope this helps 🙂

**Comment by lorengordon** [comment]
This just bit me also. It definitely does not work to use a profile in the provider config that is based on `credential_process`, and also use the provider `assume_role` feature. Very frustrating.
