### ISSUE TITLE
IAM role trust relationship changes not applied

### ISSUE THREAD

**Issue by napalm684** [hashicorp/terraform-provider-aws#17360]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Description
In our situation it appears someone manually adjusted an IAM role trust relationship in the AWS console. When applying the TF infrastructure, it did not identify that a change to the trusted entities had occurred. It simply verified there was a relationship and skipped past applying the changes.

**Comment by ewbankkit** [comment]
@napalm684 Thanks for raising this issue.
Do you have (suitably obfuscated) output from a `terraform plan` and `terraform apply` that you could share to help diagnose the problem?

**Comment by napalm684** [comment]
That is probably going to be tricky for us. We have a nest of modules in there. Anything particular from the plan you are looking for?

**Comment by ewbankkit** [comment]
@napalm684 Output showing what attributes are showing as changed during `plan` and then what happens during `apply` will be sufficient. Thanks.

**Comment by napalm684** [comment]
@ewbankkit unfortunately I went and took a look at this and our CI/CD log doesn't have anything in it for the plan/apply. That was the only change it was making that run and thus it ignored the difference in the trust relationship's content (since it did in fact exist).

**Comment by tolidano** [comment]
I can provide some... 

```
/app/enterprise-iam/us-east-1/iam-roles/datadog/tfplan
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:

Terraform will perform the following actions:

Plan: 0 to add, 0 to change, 0 to destroy.
```

I had a variable that I am changing the default for:
```
variable "external_id" {
   type        = string
   default     = "cheese"
   description = "Datadog AWS external ID taken from datadog before attaching a new account"
 }
```

Used here:

```
data "aws_iam_policy_document" "datadogAssumeRole" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::464622532012:root"]
    }

    condition {
      test     = "StringEquals"
      variable = "sts:ExternalId"

      values = [var.external_id]
    }
  }
}
```

With this simple role:
```
resource "aws_iam_role" "datadog" {
   name = "datadog"

   assume_role_policy = data.aws_iam_policy_document.datadogAssumeRole.json
 }
```

Note that there used to be this on the role (but it is being removed in the SAME plan/apply):
```
 lifecycle {
     ignore_changes = [assume_role_policy]
   }
```
