### ISSUE TITLE
MSK support for updating Kafka broker type 

### ISSUE THREAD

**Issue by mgusiew-guide** [hashicorp/terraform-provider-aws#17377]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Recently AWS MSK team announced support for changing Kafka broker type on existing MSK cluster. This is a rolling upgrade (similar to upgrade Kafka version) 

Before that change it was necessary to build new MSK cluster and if needed copy over the data (for example using MirrorMaker)

### New or Affected Resource(s)

* aws_msk_cluster

### Potential Terraform Configuration

No change in HCL needed. 

What should change is the behaviour of the resource in case when instance_type is changed. Currently the provider rebuilds the MSK cluster, ideally it should modify the cluster in place by performing rolling upgrade as described here: https://docs.aws.amazon.com/msk/latest/developerguide/msk-update-broker-type.html

### References

* #0000

**Comment by ewbankkit** [comment]
@mgusiew-guide Thanks for raising this issue.
It has already been noticed in #17264. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
