### ISSUE TITLE
aws_db_subnet_group.default: Error creating DB Subnet Group: DBSubnetGroupDoesNotCoverEnoughAZs: DB Subnet Group doesn't meet availability zone coverage requirement

### ISSUE THREAD

**Issue by laeno27** [hashicorp/terraform-provider-aws#17373]
I have a problem terraform

	* aws_db_subnet_group.default: 1 error occurred:
	* aws_db_subnet_group.default: Error creating DB Subnet Group: DBSubnetGroupDoesNotCoverEnoughAZs: DB Subnet Group doesn't meet availability zone coverage requirement. Please add subnets to cover at least 2 availability zones. Current coverage: 1
	status code: 400, request id: 23eec270-9ffb-4695-9486-b7482c64396e

Version terraform
v0.11.14

**Comment by breathingdust** [comment]
Hi @laeno27! 👋  We would need the issue template filled out with a full reproduction to help the maintainers and community with your issue. If this is still a problem please open another issue!
