### ISSUE TITLE
aws sso credentials profile not working Cannot parse expiration timestamp

### ISSUE THREAD

**Issue by JoshiiSinfield** [hashicorp/terraform-provider-aws#17372]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws provider

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

main.tf:
```hcl
provider "aws" {
  region = "eu-west-1"

  assume_role {
    role_arn = "arn:aws:iam::XXXXX:role/XXXXXX"
  }
}

data "aws_caller_identity" "current" {}

output "acc_id" {
  value = data.aws_caller_identity.current.account_id
}
```

~/.aws/config
```
[default]
sso_start_url = https://XXXXX.awsapps.com/start
sso_region = eu-west-1
sso_account_id = XXXXX
sso_role_name = AdministratorAccess
region = eu-west-1
output = json
credential_process = aws-sso-credential-process --profile default
[profile profile2]
sso_start_url = https://XXXXXX.awsapps.com/start
sso_region = eu-west-1
sso_account_id = XXXXXX
sso_role_name = AdministratorAccess
region = eu-west-1
output = json
credential_process = aws-sso-credential-process --profile profile2
```

~/.aws/credentials is empty.

software versions:
```
terraform -v  
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.26.0
```

### Expected Behavior

Terraform retrieves creds properly and runs the plan or apply.

### Actual Behavior

```
Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.

Please see https://registry.terraform.io/providers/hashicorp/aws
for more information about providing credentials.

Error: SSOProviderInvalidToken: the SSO session has expired or is invalid
caused by: expected RFC3339 timestamp: parsing time "2021-02-01T19:34:23UTC" as "2006-01-02T15:04:05Z07:00": cannot parse "UTC" as "Z07:00"

```

![image](https://user-images.githubusercontent.com/4964422/106456910-15426480-6486-11eb-8921-8bf2ed91158a.png)

### Steps to Reproduce

1. produce files/config as above
2. terraform init
2. `terraform apply`

### Important Factoids

see below referenced issue. 

### References

* #17353 - Following discussions in there and the referenced aws-sdk-go issue I removed `credential_process` from my profiles, which resulted in the above error.

**Comment by jeff-jk** [comment]
I needed to use AWS CLI v2.1.23 (latest on linux)

```
$ aws --version                    
aws-cli/2.1.23 Python/3.7.3 Linux/5.8.0-7630-generic exe/x86_64.ubuntu.20 prompt/off
```

**Comment by JoshiiSinfield** [comment]
@jeff-jk  Thanks for the suggestion, that worked! 

I upgraded my awscli version to the below, and regenerated credentials.

I'll close this log. 

```shell
$ aws --version
aws-cli/2.1.24 Python/3.9.1 Darwin/20.2.0 source/x86_64 prompt/off
```
