### ISSUE TITLE
tests/resource/aws_imagebuilder_image_pipeline: Schedule Expression Test Failures

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#17396]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The two `aws_imagebuilder_image_pipeline` resource acceptance tests that configure schedule expressions are currently failing:

```
=== CONT  TestAccAwsImageBuilderImagePipeline_Schedule_PipelineExecutionStartCondition
resource_aws_imagebuilder_image_pipeline_test.go:378: Step 1/3 error: Error running apply:
Error: error creating Image Builder Image Pipeline: InvalidParameterValueException: The value supplied for parameter 'schedule.scheduleExpression' is not valid. Invalid schedule expression. Details: Invalid CRON expression: error at position 9, details: Unexpected end of expression.
--- FAIL: TestAccAwsImageBuilderImagePipeline_Schedule_PipelineExecutionStartCondition (47.57s)

=== CONT  TestAccAwsImageBuilderImagePipeline_Schedule_ScheduleExpression
resource_aws_imagebuilder_image_pipeline_test.go:412: Step 1/3 error: Error running apply:
Error: error creating Image Builder Image Pipeline: InvalidParameterValueException: The value supplied for parameter 'schedule.scheduleExpression' is not valid. Invalid schedule expression. Details: Invalid CRON expression: error at position 9, details: Unexpected end of expression.
--- FAIL: TestAccAwsImageBuilderImagePipeline_Schedule_ScheduleExpression (43.82s)
```

The configuration needs to be updated, but at first glance the cron expressions that previously worked fine do match the AWS documentation.

### Affected Resource(s)

* aws_imagebuilder_image_pipeline

### References

* https://docs.aws.amazon.com/imagebuilder/latest/userguide/cron-expressions.html

**Comment by anGie44** [comment]
idk if it was luck but plugging in the first AWS doc example `cron(0 10 * * *)` seemed to work 😅

**Comment by bflad** [comment]
Hmmm trying that in the acceptance testing still showed failures for me in the Commercial main and standalone accounts (just to verify its nothing weird with preview access) -- the error shifts from 9th character to 10th:

```
=== CONT  TestAccAwsImageBuilderImagePipeline_Schedule_PipelineExecutionStartCondition
    resource_aws_imagebuilder_image_pipeline_test.go:378: Step 1/3 error: Error running apply:
        Error: error creating Image Builder Image Pipeline: InvalidParameterValueException: The value supplied for parameter 'schedule.scheduleExpression' is not valid. Invalid schedule expression. Details: Invalid CRON expression: error at position 10, details: Unexpected end of expression.


--- FAIL: TestAccAwsImageBuilderImagePipeline_Schedule_PipelineExecutionStartCondition (20.42s)
=== CONT  TestAccAwsImageBuilderImagePipeline_Schedule_ScheduleExpression
    resource_aws_imagebuilder_image_pipeline_test.go:412: Step 1/3 error: Error running apply:
        Error: error creating Image Builder Image Pipeline: InvalidParameterValueException: The value supplied for parameter 'schedule.scheduleExpression' is not valid. Invalid schedule expression. Details: Invalid CRON expression: error at position 10, details: Unexpected end of expression.


--- FAIL: TestAccAwsImageBuilderImagePipeline_Schedule_ScheduleExpression (24.54s)
```

Do you have ideas how you got it to work?

I didn't mention it above, but the current cron syntax passes in AWS GovCloud (US). I'll keep fiddling by trying the [extended CloudWatch schedule expression syntax](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html) with its year field to see if maybe that is something new but not documented. Otherwise I'll just raise an AWS Support case.

**Comment by anGie44** [comment]
Ohh weird it must be something partition/region related b/c i definitely see the errors you have when using `us-west-2` but i retested with `us-east-1`/`us-west-1` and got:
```
--- PASS: TestAccAwsImageBuilderImagePipeline_Schedule_PipelineExecutionStartCondition (35.99s)
``` 
and if you run the current version of the tests in `us-east-1`,for example, they pass 🙃 hmm guess it merits an AWS support case

**Comment by bflad** [comment]
The plot thickens with `cron(0 0 * * * *)` in `us-west-2`:

```
    resource_aws_imagebuilder_image_pipeline_test.go:412: Step 1/3 error: Error running apply:
        Error: error creating Image Builder Image Pipeline: InvalidParameterValueException: The value supplied for parameter 'schedule.scheduleExpression' is not valid. Invalid schedule expression. Details: Invalid CRON expression: error at position 0, details: Specifying both a day-of-week AND a day-of-month parameter is not supported.
```

Anddddd adjusting it to fix that error with `cron(0 0 * * ? *)` passes in `us-west-2`:

```
--- PASS: TestAccAwsImageBuilderImagePipeline_Schedule_PipelineExecutionStartCondition (48.05s)
--- PASS: TestAccAwsImageBuilderImagePipeline_Schedule_ScheduleExpression (52.39s)
```

**Comment by anGie44** [comment]
🤭 🤭

**Comment by a019647** [comment]
For me it's failing in `us-east-1` despite @anGie44 reporting success there. Character 9. This is a showstopper :(

**Comment by bflad** [comment]
@a019647 thank you for the heads up, this API update may be rolling out to other AWS regions now. Confirmed just now in `us-east-1` and `us-east-2`. If that is the case, then the Image Builder documentation updates will also likely be rolling out soon for the change (likely this afternoon). From our AWS Support case, I think I can publicly mention that the longer syntax will be expected for new pipelines going forward.

**Comment by a019647** [comment]
update: whether because I used the syntax workaround, or because the fix was in place in `us-east-1` already, my scenario is now working. Thanks @bflad !

**Comment by a019647** [comment]
Update: I tried to re-apply the before-workaround version of my code in a different account/base module, and it still fails in us-east-1.

**Comment by a019647** [comment]
In addition, I seem to have a problem now when TF attempts to update an image recipe. It complains that something depends on the recipe (only the old pipeline does), and changing the version number of the recipe doesn't change its mind at all. Is that behavior as expected? I don't seem to have a path to create a new version of a recipe that's currently being used in a pipeline.  ???
