### ISSUE TITLE
Changing multi_az from true to false on aws_db_instance does not apply changes

### ISSUE THREAD

**Issue by sarahbarberuk** [hashicorp/terraform-provider-aws#17407]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_db_instance

### Terraform Configuration Files

```hcl

resource "aws_db_instance" "rds" {
  allocated_storage               = 20
  db_subnet_group_name            = "dev.test.rds.subnet-group"
  deletion_protection             = true
  enabled_cloudwatch_logs_exports = ["audit", "error", "general"]
  engine                          = "mysql"
  engine_version                  = 5.7
  final_snapshot_identifier       = replace("dev.test.rds.final-snapshot", ".", "-")
  instance_class                  = "db.t3.medium"
  identifier                      = replace("dev.test.rds", ".", "-")
  name                            = replace(replace("dev.test.rds.db", "-", ""), ".", "")
  password                        = "pass"
  publicly_accessible             = true
  username                        = "un"
  multi_az                        = true
}

```
### Expected Behavior

Should be possible to turn multi-az on and off

### Actual Behavior

It is possible to turn multi-az on but not off

### Steps to Reproduce

1. `terraform apply` to first create the instance correctly.
2. Modify the above hcl and set multi-az: false
3. `terraform apply`
4. Note that no resource changes have occurred
5.  Modify the above hcl and set multi-az: true (again)
6. `terraform apply`
7. Note that there is now an error message: `Error: Error modifying DB Instance dev-test-rds: InvalidParameterCombination: No modifications were requested
	status code: 400`
8. This could be because aws-cli modify-db-instance multi-az parameter is not a boolean. We must use --no-multi-az to make it false. https://docs.aws.amazon.com/cli/latest/reference/rds/modify-db-instance.html

* #0000

**Comment by drexler** [comment]
@sarahbarberuk  does adding `apply_immediately = true` resolve your issue?

**Comment by sarahbarberuk** [comment]
> @sarahbarberuk does adding `apply_immediately = true` resolve your issue?

Yes it does @drexler . My apologies, this can be closed. Thanks!
