### ISSUE TITLE
aws_autoscaling_group fails to roll when healthy and unhealthy targets present and min_elb_capacity used

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#17405]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

* Terraform version: 0.12.25
* Provider "random" (hashicorp/random) 3.0.1
* Provider "template" (hashicorp/template) 2.2.0
* Provider "aws" (hashicorp/aws) 2.65.0

NOTE: Although I am not using the latest AWS provider version, I see the same code mentioned below.

### Affected Resource(s)

* aws_autoscaling_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
// Note the ALB target group gets associated with BOTH the ASG and ECS service. This causes both healthy and unhealthy ports behind the target group.
// ASG registers unhealthy tasks on port 80 (TG default), ECS service registers healthy tasks on container ports (EG: 12345)
resource "aws_alb_target_group" "load_balancer" {
  name                 = "my-service-prod"
  port                 = 80
  protocol             = "HTTP"
  vpc_id               = "vpc-12345678"
  deregistration_delay = 30
  tags                 = []

  health_check {
    path     = "/h"
    matcher  = 200
    interval = 5
    timeout  = 2
  }
}

resource "aws_autoscaling_group" "autoscaling_group" {
  name                      = aws_launch_configuration.launch_configuration.name
  min_size                  = 3
  max_size                  = 6
  desired_capacity          = 3
  min_elb_capacity          = 1
  launch_configuration      = aws_launch_configuration.launch_configuration.name
  health_check_grace_period = 300
  health_check_type         = "EC2"
  vpc_zone_identifier       = ["subnet-aaaaaaaa","subnet-bbbbbbbb","subnet-cccccccc"]
  target_group_arns         = [aws_alb_target_group.load_balancer.arn]
  termination_policies      = ["OldestInstance","OldestLaunchConfiguration","ClosestToNextInstanceHour"]
  metrics_granularity       = "1Minute"
  enabled_metrics           = ["GroupMinSize","GroupMaxSize","GroupDesiredCapacity","GroupInServiceInstances","GroupPendingInstances","GroupStandbyInstances","GroupTerminatingInstances","GroupTotalInstances"]
  wait_for_capacity_timeout = "15m"
  tags                      = []

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_launch_configuration" "launch_configuration" {
  name_prefix                 = "zzz-my-service-prod-XX-XX-"
  instance_type               = "i3.4xlarge"
  image_id                    = "ami-12345678901234567"
  iam_instance_profile        = "ecs-instance-profile"
  security_groups             = ["sg-12345678"]
  key_name                    = "server4001"
  user_data                   = "#!/bin/bash"
  associate_public_ip_address = false
  ebs_optimized               = true

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_ecs_cluster" "default" {
  name = "my-service-production"
  tags = []
}

resource "aws_ecs_service" "service" {
  name            = "my-service-api-prod"
  cluster         = aws_ecs_cluster.default.id
  task_definition = aws_ecs_task_definition.task_definition.arn
  desired_count   = 6
  iam_role        = "arn:aws:iam::123456789012:role/my-service-ecs-service"

  lifecycle {
    ignore_changes = [desired_count]
  }

  load_balancer {
    target_group_arn = aws_alb_target_group.load_balancer.arn
    container_name   = "caddy"
    container_port   = 8080
  }

  ordered_placement_strategy {
    type  = "spread"
    field = "instanceId"
  }
}

resource "aws_ecs_task_definition" "task_definition" {
  family                = "my-service-api-prod"
  container_definitions = "[...TRUNCATED...]"
  tags                  = []
}
```

### Debug Output

I cannot provide debug output. I can provide the actual response from the describe target health endpoint:
https://gist.github.com/bricebentler/d108e6cc6a20685a92b6f5121dad3308

### Panic Output

N/A

### Expected Behavior

When updating the user data in the Launch Configuration, we should see Terraform do the following:

* Create a new Launch Configuration along-side the existing one
* Create a new AutoScaling Group along-side the existing one
* Look at the Application Load Balancer Target Group associated with the new ASG, determine that the new ASG has instances with healthy targets.
* Destroy the old ASG
* Destroy the old LC 

### Actual Behavior

We associate the ALB target group with both the ASG and ECS service. During a deploy which rotates ASGs, this configuration allows us to confirm the new ASG has instances with healthy containers before killing off the old ASG. As a side effect, this causes the ALB target group to have both healthy and unhealthy targets. The ECS service registers healthy containers. The ASG registers unhealthy EC2 instances on port 80 (TG default port).

We have discovered a bug in the AWS Terraform provider, when Terraform determines how many instances associated with an ASG should be considered healthy. This only happens when instances have both healthy and unhealthy ports, like in the above configuration.

When the bug scenario is present, we see the following behavior from Terraform:

* Create a new Launch Configuration along-side the existing one
* Create a new AutoScaling Group along-side the existing one
* Look at the Application Load Balancer Target Group associated with the new ASG, determine that the new ASG does NOT have any instances with healthy targets.
* Continue polling the ALB TG, looking for healthy instances in the new ASG. Continue to find none.
* Time out, leaving both the old and new ASG/LC in place.

Here is the Terraform code: https://github.com/hashicorp/terraform-provider-aws/blob/v3.26.0/aws/resource_aws_autoscaling_group.go#L1588
In it, you will see Terraform making a call to the ELB API's DescribeTargetHealth endpoint which returns a response body like so:

```
... TRUNCATED ...
<member>
  <HealthCheckPort>12345</HealthCheckPort>
  <TargetHealth>
    <State>healthy</State>
  </TargetHealth>
  <Target>
    <Id>i-aaaaaaaaaaaaaaaaa</Id>
    <Port>12345</Port>
  </Target>
</member>
<member>
  <HealthCheckPort>80</HealthCheckPort>
  <TargetHealth>
    <Reason>Target.FailedHealthChecks</Reason>
    <Description>Health checks failed</Description>
    <State>unhealthy</State>
  </TargetHealth>
  <Target>
    <Id>i-aaaaaaaaaaaaaaaaa</Id>
    <Port>80</Port>
  </Target>
</member>
... TRUNCATED ...
```

Terraform then iterates each instance/port combination, storing the health state in a hash, where the key is the EC2 instance ID. Because the EC2 instance ID is used as the hash key, the last occurrence of the EC2 instance will always be used. When the last occurrence is unhealthy, the entire EC2 instance is marked as unhealthy, despite having healthy containers. If this happens for all instances in the new ASG, Terraform will timeout, and never tear down the old ASG/LC.

### Steps to Reproduce

This is tricky to reproduce. You will need to set up the infrastructure, where the Target Group is associated with both the ASG and ECS Service. Then you will need to change user data and run Terraform apply until you see the API return the state described above. Using a lower instance count of 2 might make this easier.

1. `terraform apply`

### Important Factoids

Just that both the ASG and ECS Service are associated with the Target Group, as shown in the Terraform code.

**Comment by dvishniakov** [comment]
Potential bad scenarios associated with the current logic of the provider:
1. Release fails due to health check order + rollback, RCA, 2nd release attempt.
2. Even worse scenario: (depending on customer base): bad release with a bug/issue/etc succeeds due to health check order. Customers are affected. Downtime? Rollback, RCA.

Suggestions:
- Make the health check condition configurable. For example, require N% of health checks from the instance to be healthy to consider EC2 instance healthy from ALB point of view. This will allow to require 100% and to avoid 2nd bad scenario.

**Comment by slatsinoglou** [comment]
Is there any update on this issue? Thank you in advance
