### ISSUE TITLE
tests/data-source/aws_acm_certificate: Update tests to be self-contained

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#17404]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently these two acceptance tests require manually created ACM certificates to exist based on environment variable:

```
=== CONT  TestAccAWSAcmCertificateDataSource_singleIssued
data_source_aws_acm_certificate_test.go:38: Step 1/6 error: Error running pre-apply refresh:
Error: No certificate for domain "tf-acc-single-issued.--OMITTED--" found in this region
--- FAIL: TestAccAWSAcmCertificateDataSource_singleIssued (11.71s)

=== CONT  TestAccAWSAcmCertificateDataSource_multipleIssued
data_source_aws_acm_certificate_test.go:110: Step 1/6, expected an error with pattern, no match on: Error running pre-apply refresh:
Error: No certificate for domain "tf-acc-multiple-issued.--OMITTED--" found in this region
--- FAIL: TestAccAWSAcmCertificateDataSource_multipleIssued (10.56s)
```

The test configurations should be updated to be self-contained, which means each of these should be using the `aws_acm_certificate` resource as well.

### Affected Resource(s)

* aws_acm_certificate

**Comment by yuonoda** [comment]
Hi @bflad ,

I am thinking to work on this issue and have one question. Even if you use "aws_acm_certificate" for this test, a publically accessible domain should be specified in the environment variable, right? Is it ok or is there any solution that doesn't need a registered domain?
