### ISSUE TITLE
quicksight user add fail

### ISSUE THREAD

**Issue by endlesslight0** [hashicorp/terraform-provider-aws#17406]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
❯ terraform -v
Terraform v0.14.5

aws provider v3.24.1
```
### Affected Resource(s)

* aws_quicksight_user

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_quicksight_user" "users" {
  user_name     = "firstname_lastname"
  email         = "firstname.lastname@company.com"
  identity_type = "IAM"
  user_role     = "ADMIN"
}
```

### Debug Output

```
Error: Error registering QuickSight user: InvalidParameterValueException: Invalid resource identifiers provided. Please check the documentation. 
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "00891fdc-2ad3-4534-81fe-24ac1a96c42f"
  },
  Message_: "Invalid resource identifiers provided. Please check the documentation. "
}
```

### Expected Behavior

New quicksight user added according to successful plan:

```
# aws_quicksight_user.users["firstname_lastname"] will be created
  + resource "aws_quicksight_user" "users" {
      + arn            = (known after apply)
      + aws_account_id = (known after apply)
      + email          = "firstname.lastname@company.com"
      + id             = (known after apply)
      + identity_type  = "IAM"
      + namespace      = "default"
      + user_name      = "firstname_lastname"
      + user_role      = "ADMIN"
    }
```

### Actual Behavior

User not created. See error from "Debug Output"

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by motilevy** [comment]
This is because `identity_type = "IAM"` does not support the user name attribute, instead it expects a `session_name` attribute 

for example this aws command: 

```
aws quicksight register-user --aws-account-id <ACCT> \
        --namespace default \
        --identity-type IAM \
        --iam-arn arn:aws:iam::<ACCT>:role/roleName \
        --user-role READER \
        --session-name "user@domain.com"  \
        --email "user@domain.com"
```

will result in: 
```
An error occurred (InvalidParameterValueException) when calling the RegisterUser operation: The following parameters are not applicable to this identity type: User Name. AWS account ID: <ACCT>, Namespace: default.
```

Same in terraform ... your above example will fail but if you remove the `user_name` and add `session_name` it'll work.

**Comment by breathingdust** [comment]
Hi @endlesslight0! It looks like @motilevy was able to help you with this issue so going to close it.

**Comment by jackson-theisen** [comment]
@breathingdust if @motilevy's answer is indeed accurate, then the documentation for https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/quicksight_user needs to be updated. The example has `identity_type = "IAM"` and `user_name     = "an-author"` in conjunction.

**Comment by breathingdust** [comment]
Thanks for the heads-up @jackson-theisen, I'll raise a PR shortly to resolve it 👍
