### ISSUE TITLE
aws_autoscaling_group collapses all tags with values unspecified until apply into a single value, resulting in an inconsistent plan on apply

### ISSUE THREAD

**Issue by sriddell** [hashicorp/terraform-provider-aws#17416]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/aws v3.26.0
+ provider registry.terraform.io/hashicorp/random v3.0.1

### Affected Resource(s)

* aws_autoscaling_group

### Terraform Configuration Files

Complete test cases showing working and error scenarios with detailed analysis/guesses in README.md at https://github.com/sriddell/aws_autoscaling_group_error_example

```hcl


resource "random_string" "random" {
  length = 16
  special = true
  override_special = "/@£$"
}



data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}

resource "aws_launch_configuration" "as_conf" {
  name          = "web_config"
  image_id      = data.aws_ami.ubuntu.id
  instance_type = "t2.micro"
}


resource "aws_autoscaling_group" "bar" {
  name                      = "shane1"
  max_size                  = 1
  min_size                  = 0
  health_check_grace_period = 300
  force_delete              = true
  vpc_zone_identifier       = ["subnet-0b64c3204be4d14c1"]
  launch_configuration = aws_launch_configuration.as_conf.name
  tags = [
      {
        "key"                 = "Name"
        "value"               = random_string.random.result
        "propagate_at_launch" = "true"
      },
      {
        "key"                 = "kubernetes.io/cluster/fixed"
        "value"               = random_string.random.result
        "propagate_at_launch" = "true"
      }
  ]

}

```

### Debug Output
plan debug: https://gist.github.com/sriddell/4316a722c9b3186d16b998677ba24bdc
apply debug https://gist.github.com/sriddell/214c223b53484adc7374213830f90699
--->

### Expected Behavior

Plan should have been applied without error.

### Actual Behavior

Apply failed with "Provider produced inconsistent final plan".

The README.md in https://github.com/sriddell/aws_autoscaling_group_error_example has full details, but the basic problem appears to be that the aws_autoscaling_group resource, when presented with 2 or more tags in the "tags" attribute with keys or values that are unspecified until apply time, collapses them all down into a single unspecified value in the "tags" list.  This means that when the plan is applied, the tags list expands to be larger than it as in the plan, which violates the checks in the assertValueCompatible function in compatible.go from terraform-core, which allows a list to shrink in size, but not expand during the apply.

### Steps to Reproduce

1. `terraform plan -out plan`
2. `terraform apply plan`

**Comment by ewbankkit** [comment]
@sriddell Thanks for raising this issue.
It has already been noticed in #14085. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
