### ISSUE TITLE
Notice: `aws_vpc_endpoint_service`: Error: multiple VPC Endpoint Services matched

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#17417]
### Problem

For those users who are encountering the following error when using the `aws_vpc_endpoint_service` data source:

```console
 Error: multiple VPC Endpoint Services matched; use additional constraints to reduce matches to a single VPC Endpoint Service
```
- AWS have just released a new feature in S3 (PrivateLink) which means that multiple results are now being returned when searching for the S3 endpoint service.
- Singular data sources in the Terraform AWS Provider (like `aws_vpc_endpoint_service`) return an error if multiple results are returned.

### Configuration changes required to resolve the issue

Add a `filter` block to select a service type, e.g.

```hcl
data "aws_vpc_endpoint_service" "s3" {
  service = "s3"

  filter {
    name   = "service-type"
    values = ["Gateway"]
  }
}
```

For provider versions `v3.10.0` and up, it is also possible to use the `service_type` argument for simplifying the configuration:

```hcl
data "aws_vpc_endpoint_service" "s3" {
  service      = "s3"
  service_type = "Gateway"
}
```

Please note that if you are using a Terraform module that relies on this datasource, the module itself will need to be updated. Terraform modules are not maintained by HashiCorp, so you will need to reach out to the modules maintainers to make that configuration update.

### References

- #15467

**Comment by circa10a** [comment]
if you are using a provider version prior to v3 **this won't work** for `aws_vpc_endpoint_service`_data sources  since multiple items will be returned due to the new vpc service endpoint being the same name and service type filtering was added in v3

```hcl
data "aws_region" "current" {}

data "aws_vpc_endpoint_service" "s3" {
  count = var.create_vpc && var.enable_s3_endpoint ? 1 : 0

  service = "s3"
  filter {
    name   = "service-name"
    values = ["com.amazonaws.${data.aws_region.current.name}.s3"]
  }
}
```

**Comment by circa10a** [comment]
Workaround for now is to tag the service endpoint: `aws ec2 create-tags --resources vpce-svc-***** --tag Key=type,Value=gateway --region us-east-1`

**Comment by circa10a** [comment]
And here's a crufty script to tag the existing s3 gateway service endpoints in all regions, should you need to

```
 #!/usr/env/bin/bash
 
 export AWS_PAGER=""
 REGIONS=("us-east-1" "us-east-2" "us-west-1" "us-west-2" "ap-northeast-1" "ap-northeast-2" "ap-southeast-1" "ap-southeast-2" "ca-central-1" "eu-central-1" "eu-west-1" "eu-west-2" "eu-west-3" "sa-east-1")
 # REGIONS=("us-gov-west-1" "us-gov-west-2")
 for REGION in "${REGIONS[@]}";do
   echo "Tagging region: ${REGION}"
   S3_GATEWAY_ENDPOINT_ID=$(aws ec2 describe-vpc-endpoint-services --region ${REGION} --output json | grep -C 5 s3 | grep -B 3 Gateway | grep -oE "vpce.*" | sed 's/",//g')
   echo "S3 Gateway ID: ${S3_GATEWAY_ENDPOINT_ID}"
   aws ec2 create-tags --resources "$S3_GATEWAY_ENDPOINT_ID" --tag Key=type,Value=gateway --region "$REGION"
 done
~~~

**Comment by endlesslight0** [comment]
> The configuration fix is to specify the `service_type` argument, which was added in Terraform AWS Provider version `3.10.0`:
> 
> ```terraform
> data "aws_vpc_endpoint_service" "s3" {
>   service      = "s3"
>   service_type = "Gateway"
> }
> ```

Using AWS provider version 3.24.1 and with the solution above still getting the same error.

**Comment by kelvinmatheus** [comment]
> Workaround for now is to tag the service endpoint:
> 
> ```shell
> aws ec2 create-tags --resources vpce-svc-***** --tag Key=type,Value=gateway --region us-east-1
> ```
> 
> Then in terraform
> 
> ```terraform
> data "aws_vpc_endpoint_service" "s3" {
>   count = var.create_vpc && var.enable_s3_endpoint ? 1 : 0
> 
>   service = "s3"
>   filter {
>     name   = "tag:type"
>     values = ["gateway"]
>   }
> }
> ```

Thanks a lot, it worked here with some changes. We have just created the filter and changed the count assignment a little bit..

```
count = "${var.enable_s3_endpoint ? 1 : 0}"
```

**Comment by karkrish** [comment]
Guys, I got another workaround for this issue. I removed the data section and integrated with endpoint resource.

resource "aws_vpc_endpoint" "s3" {
  count = "${var.create_vpc && var.enable_s3_endpoint ? 1 : 0}"
  vpc_id       = "XXXX"
  service_name = "com.amazonaws.${var.aws_region}.s3"
  vpc_endpoint_type = "Gateway"
  tags {
    Name = "XXXXX"
  }
}

**Comment by circa10a** [comment]
> Guys, I got another workaround for this issue. I removed the data section and integrated with endpoint resource.
> 
> resource "aws_vpc_endpoint" "s3" {
> count = "${var.create_vpc && var.enable_s3_endpoint ? 1 : 0}"
> vpc_id = "XXXX"
> service_name = "com.amazonaws.${var.aws_region}.s3"
> vpc_endpoint_type = "Gateway"
> tags {
> Name = "XXXXX"
> }
> }

Fantastic, [confirmed this is supported with provider `2.70.0`](https://registry.terraform.io/providers/hashicorp/aws/2.70.0/docs/resources/vpc_endpoint)

Here's how we implemented

```hcl
data "aws_region" "current" {}

resource "aws_vpc_endpoint" "s3" {
  count = var.create_vpc && var.enable_s3_endpoint ? 1 : 0

  vpc_id                      = local.vpc_id
  service_name          = "com.amazonaws.${data.aws_region.current.name}.s3"
  vpc_endpoint_type = var.s3_vpc_endpoint_type # default = "Gateway"
  tags                          = local.vpce_tags
}
```

**Comment by fazalmasood** [comment]
Error: "service_type": this field cannot be set

  on .terraform/modules/iq_networking/main.tf line 323, in data "aws_vpc_endpoint_service" "s3":
 323: data "aws_vpc_endpoint_service" "s3" {
[script-executor] Script completed with exit code: 1.

**Comment by fazalmasood** [comment]
Could some one help me here to solve this issue

**Comment by circa10a** [comment]
@fazalmasood This is because you are using provider version `2.70.0`. I mentioned the fix for that provider version just above. You essentially need to get rid of the data source, but if you can't I also listed an alternative method further up in the issue.

> > Guys, I got another workaround for this issue. I removed the data section and integrated with endpoint resource.
> > resource "aws_vpc_endpoint" "s3" {
> > count = "${var.create_vpc && var.enable_s3_endpoint ? 1 : 0}"
> > vpc_id = "XXXX"
> > service_name = "com.amazonaws.${var.aws_region}.s3"
> > vpc_endpoint_type = "Gateway"
> > tags {
> > Name = "XXXXX"
> > }
> > }
> 
> Fantastic 🎉 , [confirmed this is supported with provider `2.70.0`](https://registry.terraform.io/providers/hashicorp/aws/2.70.0/docs/resources/vpc_endpoint)
> 
> Here's how we implemented
> 
> ```terraform
> data "aws_region" "current" {}
> 
> resource "aws_vpc_endpoint" "s3" {
>   count = var.create_vpc && var.enable_s3_endpoint ? 1 : 0
> 
>   vpc_id            = local.vpc_id
>   service_name      = "com.amazonaws.${data.aws_region.current.name}.s3"
>   vpc_endpoint_type = var.s3_vpc_endpoint_type # default = "Gateway"
>   tags              = local.vpce_tags
> }
> ```

**Comment by kjsingh** [comment]
Verified on Terraform version 0.11:

`resource 
"aws_vpc_endpoint" "s3" 
{

vpc_id = 
"${module.vpc.vpc_id}"

service_name = 
"com.amazonaws.${local.region}.s3"

vpc_endpoint_type = 
"Gateway"

}`

**Comment by BradH19** [comment]
> Verified on Terraform version 0.11:
> 
> ```
> resource 
> "aws_vpc_endpoint" "s3" 
> {
> 
> vpc_id = 
> "${module.vpc.vpc_id}"
> 
> service_name = 
> "com.amazonaws.${local.region}.s3"
> 
> vpc_endpoint_type = 
> "Gateway"
> 
> }
> ```
What AWS Provider are you using? I'm still getting the same error (shown below), even when using the region. 
"multiple VPC Endpoint Services matched; use additional constraints to reduce matches to a single VPC Endpoint Service"

**Comment by kjsingh** [comment]
have you removed the data block?

```data "aws_vpc_endpoint_service" "s3" {...}```

**Comment by BradH19** [comment]
@kjsingh That may have been it. I've just removed that data block and ran plan with no errors. Still need to do some other testing but this is looking much better than it did a few hours ago.

**Comment by dgonzalez** [comment]
@kjsingh this is causing an issue for me too. That data block is the actual problem I am getting, not the `aws_endpoint` itself. So, this is not solved or I am missing something.

**Comment by kumartushar** [comment]
> Verified on Terraform version 0.11:
> 
> ```
> resource 
> "aws_vpc_endpoint" "s3" 
> {
> 
> vpc_id = 
> "${module.vpc.vpc_id}"
> 
> service_name = 
> "com.amazonaws.${local.region}.s3"
> 
> vpc_endpoint_type = 
> "Gateway"
> 
> }
> ```

Thanks this worked 👍

**Comment by circa10a** [comment]
Update: AWS added a new `filter` to the [DescribeVPCEndpointServices](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeVpcEndpointServices.html) API which will now allow for this:

```hcl
data "aws_vpc_endpoint_service" "s3" {
  count = var.create_vpc && var.enable_s3_endpoint ? 1 : 0

  service = "s3"
  filter {
    name   = "service-type"
    values = ["Gateway"]
  }
}
```

**Comment by circa10a** [comment]
FYI that [v2.74.0 of the terraform-aws-vpc module](https://github.com/terraform-aws-modules/terraform-aws-vpc/compare/v2.73.0...v2.74.0) was updated the be compatible v2 and v3 of the terraform AWS provider.

**Comment by MysticalMount** [comment]
Hi all, we fixed this in the interim with a custom bash script (https://github.com/MysticalMount/aws_vpc_endpoint_service) - forgive me for lack of knowledge but it looks like the v2.74.0 vpc module mentioned above might be a more appropriate fix - will this automatically install along with the AWS provider in version 11 of Terraform now or are there some other steps - does this module form part of the AWS provider itself?
