### ISSUE TITLE
Issue with KMS and DynamoDB Global Tables

### ISSUE THREAD

**Issue by christopher-wong** [hashicorp/terraform-provider-aws#17422]
I'm trying to create a DynamoDB global table using the configuration specified here https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#global-tables.

All my tables are encrypted using a custom KMS key, however, I'm unable to specify the KMS key for the replica global tables and receive the following error when running `apply`.

Removing my custom KMS key resolves the issue, however, I need to use a custom KMS key.

```
Error: error creating DynamoDB Table (<TABLE_NAME>) replicas: error creating DynamoDB Table (<TABLE_NAME>) replica (us-east-2): ValidationException: One or more parameter values were invalid: KMSMasterKeyId must be specified for each replica.
        status code: 400, request id: xxx
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.29
+ provider.aws v3.26.0

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files
```hcl
resource "aws_dynamodb_table" "my_table" {
  name = "my_table"
  stream_enabled = true
  stream_view_type = "NEW_AND_OLD_IMAGES"
  billing_mode = "PAY_PER_REQUEST"

  server_side_encryption {
    enabled = true
    kms_key_arn = data.terraform_remote_state.kms.outputs.my_key_arn
  }

  replica {
    region_name = "us-west-2"
  }

  replica {
    region_name = "us-east-2"
  }

  hash_key = "producer_id"

  attribute {
    name = "producer_id"
    type = "S"
  }

  tags = {
    Name = "my_table"
    Environment = var.env
  }
}
```

**Comment by ewbankkit** [comment]
@christopher-wong Thanks for raising this issue.
It has already been noticed in #16358. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
