### ISSUE TITLE
aws_instance with private_ip gives error on update

### ISSUE THREAD

**Issue by nmarus** [hashicorp/terraform-provider-aws#17431]
### Summary

When using a `private_ip` with `aws_instance`, a `terraform apply` after intiial apply where changes to `aws_instance` requires a "forces replacement", AWS/TF errors that IP address is already in use.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.4

### Affected Resource(s)

* aws_instance
* aws_eip

### Terraform Configuration Files

```hcl
resource "aws_vpc" "default" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
}

resource "aws_internet_gateway" "gw" {
  vpc_id = aws_vpc.default.id
}

resource "aws_subnet" "tf_test_subnet" {
  vpc_id                  = aws_vpc.default.id
  cidr_block              = "10.0.0.0/24"
  map_public_ip_on_launch = true

  depends_on = [aws_internet_gateway.gw]
}

resource "aws_instance" "foo" {
  ami           = "ami-5189a661"
  instance_type = "t2.micro"

  private_ip = "10.0.0.12"
  subnet_id  = aws_subnet.tf_test_subnet.id
}

resource "aws_eip" "bar" {
  vpc = true

  instance                  = aws_instance.foo.id
  associate_with_private_ip = "10.0.0.12"
  depends_on                = [aws_internet_gateway.gw]
}
```

### Debug Output

```
Error: Error launching source instance: InvalidIPAddress.InUse: Address 10.0.0.12 is in use.
	status code: 400, request id: xxx-xxx-xxx-xxx-xxxxxxxxxxx
```

### Expected Behavior

Persist same private IP address after reapply of terraform when aws_instance params are changed

### Actual Behavior

See debug output.

### Steps to Reproduce

Use something similar to above, , and apply again.

1. `terraform apply`
2. Change a param under aws_instance that "forces replacement" (ie userdata)
3. `terraform apply`

**Comment by nmarus** [comment]
Looking at the Terrform output, it seems it is doing a create_before_destroy even though that lifecycle option does not exist on aws_instance. My guess this is the root of my issue as it is trying to create a new instance with the same private_ip as the that still exists on the old instance.

**Comment by anGie44** [comment]
Hi @nmarus, thank you for raising this issue. Have you by chance also tried referring to the `aws_instance` resource's `private_ip` attribute from within the `aws_eip` resource? I've tried on my end with the config you provided and if I adjust the following:
```hcl
resource "aws_eip" "bar" {
  vpc = true

  instance                  = aws_instance.foo.id
  associate_with_private_ip = aws_instance.foo.private_ip
  depends_on                = [aws_internet_gateway.gw]
}
```
I see the apply output (after adding in `user_data` to ForceNew) shows the order as we'd hope:
```
aws_vpc.default: Refreshing state... [id=vpc-08fdc9dd7eb70973b]
aws_internet_gateway.gw: Refreshing state... [id=igw-051359f186a76cd9b]
aws_subnet.tf_test_subnet: Refreshing state... [id=subnet-0485b50dca67ab186]
aws_instance.foo: Refreshing state... [id=i-0b51c5cc580607722]
aws_eip.bar: Refreshing state... [id=eipalloc-04b270114fd876a53]
aws_instance.foo: Destroying... [id=i-0b51c5cc580607722]
aws_instance.foo: Still destroying... [id=i-0b51c5cc580607722, 10s elapsed]
aws_instance.foo: Still destroying... [id=i-0b51c5cc580607722, 20s elapsed]
aws_instance.foo: Still destroying... [id=i-0b51c5cc580607722, 30s elapsed]
aws_instance.foo: Destruction complete after 30s
aws_instance.foo: Creating...
aws_instance.foo: Still creating... [10s elapsed]
aws_instance.foo: Still creating... [20s elapsed]
aws_instance.foo: Still creating... [30s elapsed]
aws_instance.foo: Still creating... [40s elapsed]
aws_instance.foo: Creation complete after 49s [id=i-05872fa58b31a3682]
aws_eip.bar: Modifying... [id=eipalloc-04b270114fd876a53]
aws_eip.bar: Modifications complete after 6s [id=eipalloc-04b270114fd876a53]
```

**Comment by nmarus** [comment]
That worked! Thankyou!
