### ISSUE TITLE
Support S3 lifecycle rules independently from buckets

### ISSUE THREAD

**Issue by wkokolis** [hashicorp/terraform-provider-aws#17432]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A resource to define S3 bucket lifecycles rules in a stand-alone fashion, much like the security group rule resource.  At present, lifecycle rules must be defined in the aws_s3_bucket resource, and because they're nested blocks it's difficult to create a reusable module.

The resource would almost certainly need the ID/ARN of an existing bucket as one of its inputs.  This would also likely be incompatible with in-line lifecycle rules.

### New or Affected Resource(s)

* aws_s3_bucket_lifecycle_rule

### Potential Terraform Configuration

```hcl
resource "aws_s3_bucket_lifecycle_rule" "thisrule" {
  bucket_id = aws_s3_bucket.thisbucket.id
  prefix = "somefolder/"
  rule_type = "noncurrent_version_expiration"
  days = 90
}

resource "aws_s3_bucket_lifecycle_rule" "thatrule" {
  bucket_id = aws_s3_bucket.thisbucket.id
  prefix = "somefolder/"
  rule_type = "noncurrent_version_transistion"
  days = 30
  storage_class = "GLACIER"
}
```

### References

None that I could find in a quick search.

**Comment by ewbankkit** [comment]
@ wkokolis Thanks for raising this issue.
It has already been noticed in #6188. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
