### ISSUE TITLE
Create add_on configuration block for aws_eks_cluster resource

### ISSUE THREAD

**Issue by DonBower** [hashicorp/terraform-provider-aws#17440]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### The AWS EKS Configuration optionally requires add on(s) (aws cli: aws eks create-addon) for the cluster to operate. 
see https://docs.aws.amazon.com/eks/latest/userguide/getting-started-console.html
aws eks update-addon \
  --cluster-name my-cluster \
  --addon-name vpc-cni \
  --service-account-role-arn arn:aws:iam::<111122223333>:role/myAmazonEKSCNIRole 

### New or Affected Resource(s)

* aws_eks_cluster

### Potential Terraform Configuration

```
esource "aws_eks_cluster" "eks" {
  name                                = var.clusterName
  role_arn                            = var.eksRole

  vpc_config {
    endpoint_private_access           = true
    endpoint_public_access            = false
    subnet_ids                        = var.subnetList
    security_group_ids                = var.secgrpIDs
  }

 add_on {
    name = "vpc_cni"
    type   = "networking"
    service-account-role-arn = var.myRoleARN
  }

  add_on {
    name = "another-addon"
    type = "the-other-type"
    service-account-role-arn = var.myOtherRoleARN
  }
  
tags                                = merge(
   var.tagsAIG,
   map(
     "Name",var.clusterName
    )
  )
}
```

### References

* #0000

**Comment by ewbankkit** [comment]
@DonBower Thanks for raising this issue.
It has already been noticed in #16542. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
