### ISSUE TITLE
tests/resource/aws_emr_managed_scaling_policy: Managed scaling is not available for the account for this release.

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#17442]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `TestAccAwsEmrManagedScalingPolicy_` acceptance tests currently fail in AWS GovCloud (US):

```
=== CONT  TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumCoreCapacityUnits
    resource_aws_emr_managed_scaling_policy_test.go:42: Step 1/2 error: Error running apply:
        Error: error putting EMR Managed Scaling Policy: ValidationException: Managed scaling is not available for the account for this release.
        	status code: 400, request id: d0355659-979a-4b1c-9293-0e7ac4d2df33


=== CONT  TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits
    resource_aws_emr_managed_scaling_policy_test.go:66: Step 1/2 error: Error running apply:
        Error: error putting EMR Managed Scaling Policy: ValidationException: Managed scaling is not available for the account for this release.
        	status code: 400, request id: 3801156d-280d-4060-ad9f-f1aaf9388f83


=== CONT  TestAccAwsEmrManagedScalingPolicy_basic
    resource_aws_emr_managed_scaling_policy_test.go:18: Step 1/2 error: Error running apply:
        Error: error putting EMR Managed Scaling Policy: ValidationException: Managed scaling is not available for the account for this release.
        	status code: 400, request id: 9324e1bf-eae7-4676-9b65-26e47759f2f8


=== CONT  TestAccAwsEmrManagedScalingPolicy_disappears
    resource_aws_emr_managed_scaling_policy_test.go:90: Step 1/1 error: Error running apply:
        Error: error putting EMR Managed Scaling Policy: ValidationException: Managed scaling is not available for the account for this release.
        	status code: 400, request id: bb061a65-c104-41f3-ab27-a6eb992daa57


--- FAIL: TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits (421.03s)
--- FAIL: TestAccAwsEmrManagedScalingPolicy_disappears (445.83s)
--- FAIL: TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumCoreCapacityUnits (462.71s)
--- FAIL: TestAccAwsEmrManagedScalingPolicy_basic (466.76s)
```

These tests likely need an additional `PreCheck` function to skip the tests in unsupported regions.

### Affected Resource(s)

* aws_emr_managed_scaling_policy

**Comment by anGie44** [comment]
@bflad was wondering how to go about this one given this is a specific functionality w/in the EMR service. since the API doesn't have a method like ListManagedScalingPolicies and the another API method uses the ClusterID as a required field, could we instead use `ExpectError` to catch those errors?

**Comment by bflad** [comment]
We recently updated the Terraform Plugin SDK to support a [`TestCase` level `ErrorCheck` field](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource#TestCase.ErrorCheck), which we have used to implement skipping in Route 53 testing with `testAccErrorCheckSkipRoute53()` and the helper `testAccErrorCheckSkipMessagesContaining()`

Briefly, we can probably do something like the below 👍 

```go
ErrorCheck: testAccErrorCheckSkipMessagesContaining(t, "Managed scaling is not available"),
```

**Comment by anGie44** [comment]
ahah my bad totally got the names confused! will make use of the fresh new func 👍
