### ISSUE TITLE
tests/data-source/aws_workspaces_workspace: Simple AD directory creation is currently not supported in this region

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#17441]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `TestAccDataSourceAwsWorkspacesWorkspace_byDirectoryID_userName` acceptance test currently is failing in AWS GovCloud (US) with:

```
=== CONT  TestAccDataSourceAwsWorkspacesWorkspace_byDirectoryID_userName
    data_source_aws_workspaces_workspace_test.go:48: Step 1/1 error: Error running apply:
        Error: ClientException: Simple AD directory creation is currently not supported in this region. : RequestId: ab0931ef-0d3e-47ee-853f-6b624a112ef8 : RequestId: ab0931ef-0d3e-47ee-853f-6b624a112ef8
        {
          RespMetadata: {
            StatusCode: 400,
            RequestID: "ab0931ef-0d3e-47ee-853f-6b624a112ef8"
          },
          Message_: "Simple AD directory creation is currently not supported in this region. : RequestId: ab0931ef-0d3e-47ee-853f-6b624a112ef8 : RequestId: ab0931ef-0d3e-47ee-853f-6b624a112ef8",
          RequestId: "ab0931ef-0d3e-47ee-853f-6b624a112ef8"
        }


--- FAIL: TestAccDataSourceAwsWorkspacesWorkspace_byDirectoryID_userName (21.31s)
```

This test and potentially other `aws_workspaces_workspace` managed resource or data source tests will need configuration updates for region agnostic support or additional `PreCheck` handling to skip the tests.

### Affected Resource(s)

* aws_workspaces_workspace

### References

* Similar for FSx testing: https://github.com/hashicorp/terraform-provider-aws/issues/16172

**Comment by ewbankkit** [comment]
Fixed in #18243.
