### ISSUE TITLE
Feature Request: nodejs14.x support for aws_lambda_function

### ISSUE THREAD

**Issue by willfarrell** [hashicorp/terraform-provider-aws#17450]
### Description

The Nodejs v14 runtime has been released for Lambda.

Currently returns:
```bash
Error: expected runtime to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x java8 java8.al2 java11 python2.7 python3.6 python3.7 python3.8 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2], got nodejs14.x
```

### New or Affected Resource(s)

* aws_lambda_function

### References

https://aws.amazon.com/about-aws/whats-new/2021/02/aws-lambda-now-supports-node-js-14/

**Comment by ewbankkit** [comment]
@willfarrell Thanks for raising this issue.
The provider will start allowing the new `nodejs14.x` value for the `aws_lambda_function` and `aws_lambda_layer_version` resources once [AWS SDK v1.37.3](https://github.com/aws/aws-sdk-go/releases/tag/v1.37.3) is merged (#17452).

**Comment by willfarrell** [comment]
Thanks, I hoped it was as simple as updating the SDK. But wanted to raise, just in case it wasn't.

**Comment by sateesh3550** [comment]
@willfarrell @ewbankkit what terraform version are u guys using ?

**Comment by willfarrell** [comment]
I'm using terraform v0.13.6 with aws v3.27.0.

**Comment by vinothvk** [comment]
@ewbankkit i tested with 3.18.0 and terraform 0.14 still getting same error

**Comment by illia-sh** [comment]
Works for me with TF `0.13.15 and AWS provider 3.29.1`
```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.29.1"
    }
  }
  required_version = "= 0.13.5"
}
```
