### ISSUE TITLE
aws_dlm_lifecycle_policy copy and remap specific tags to snapshots

### ISSUE THREAD

**Issue by KVInventoR** [hashicorp/terraform-provider-aws#17455]
Hi all,

I would like to ask you about new feature for existing resource: aws_dlm_lifecycle_policy
It will be really useful if in resource: aws_dlm_lifecycle_policy  we will be able to use paratemeter: copy_tags  which will be able to copy only specific set tags and remap them as additional tags.
As example:
Ebs volume has a tag: Name - Ec2Instance01
I would like during create a new snapshot over DLM to copy (remap) EBS tagName as new tag: 
SourceEBSName = Ec2Instance01
and same for some another tags if they exist on source volume.

**Comment by breathingdust** [comment]
Hi @KVInventoR 👋 . If still interested in this update, could you resubmit the issue filling in all fields of the issue template? Without the template filled in it can be difficult for the maintainers and community to understand what you need and potentially contribute. Thank you!
