### ISSUE TITLE
Support for AthenaEngineVersion option in Athena work groups

### ISSUE THREAD

**Issue by hgalura** [hashicorp/terraform-provider-aws#17456]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When defining a work group for Athena, I would like to be able to specify Athena Engine Version.

### New or Affected Resource(s)

* aws_athena_workgroup

### References

* https://docs.aws.amazon.com/athena/latest/ug/engine-versions-changing.html

**Comment by theophilechevalier** [comment]
Hello, any update on this?
It doesn't look like a big deal to merge the proposed MR 👍

**Comment by renxunsaky** [comment]
For who is waiting for the feature be available, here is the AWS CLI to update the engine version. After the modification, Terraform will not override this setting since the API used doesn't refer to this property.

```
for wg in $(aws athena list-work-groups | jq -r '.WorkGroups[].Name')
do
	conf=$(aws athena get-work-group --work-group $wg | jq '.WorkGroup.Configuration | .EngineVersion.SelectedEngineVersion |= "Athena engine version 2" | .EngineVersion.EffectiveEngineVersion |= "Athena engine version 2" | .ResultConfigurationUpdates = .ResultConfiguration | del(.ResultConfiguration)')
	aws athena update-work-group --work-group $wg --configuration-updates $conf
done
```

**Comment by chris922** [comment]
AWS now announced that the Athena engine version 1 will be deprecated in the near future. Thus it would be great to have Terraform support there in advance so that we can at least manually update and verify everything before AWS migrates it automatically to V2. 
We've got plenty of workgroups that we don't want to migrate manually and would prefer to use Terraform for this.

> Athena engine version 1 will be deprecated in the near future. The exact deprecation date will be announced 90 days in advance in your AWS Personal Health Dashboard. To upgrade your workgroups now, use the Settings page, the Workgroups list page, or the Edit workgroup page of the Athena console. Workgroups not upgraded by the deprecation date will be upgraded to version 2 automatically. 

_(see the AWS Athena Query editor)_

**Comment by dimaqq** [comment]
AWS automatically upgrades Athena engine version now, it has upgraded the engine version for the workgroup I've created with terraform, and after that `tf apply` is happy, it doesn't see any changes.
I'd say, this time, we bit the bullet.

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters roadmap. If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!
