### ISSUE TITLE
aws_launch_template tag_specifications missing network-interface resource_type

### ISSUE THREAD

**Issue by DonBower** [hashicorp/terraform-provider-aws#17467]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform Version 0.13.5
Providers:
* hashicorp/aws: version = "~> 3.26.0"
* hashicorp/tls: version = "~> 3.0.0"
* hashicorp/vault: version = "~> 2.18.0"

### Affected Resource(s)

* aws_launch_template 
* tag_specifications

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```
resource "aws_launch_template" "thisLT" {
  ...
  ...
  ...
  dynamic tag_specifications {
    for_each                           = ["instance", "volume", "elastic-gpu", "spot-instances-request", "network-interface"]
#    for_each                           = ["instance", "volume", "elastic-gpu", "spot-instances-request"]
    content {
      resource_type                    = tag_specifications.value

      tags                             = merge(
       var.tagsK8s,
       var.tagsAIG,
       map(
         "Name",local.templateName
        )
      )
    }
  }
}
```

### Debug Output

Error: expected tag_specifications.4.resource_type to be one of [instance volume spot-instances-request elastic-gpu], got network-interface

  on /Users/dobower/Developer/ent-devops-tf/tf-paas-source/paas/launchTemplate/main.tf line 1, in resource "aws_launch_template" "thisLT":
   1: resource "aws_launch_template" "thisLT" {

### Expected Behavior

Create propagated tags for network interfaces 

### Actual Behavior

failed

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by ewbankkit** [comment]
Related:

* #14558
* #17253

**Comment by ewbankkit** [comment]
@DonBower Thanks for raising this issue.

According to the [AWS User Guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-templates.html#create-launch-template-define-parameters):

> You can tag the instance, the volumes, Spot Instance requests, or all three.

whereas the [AWS API reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RequestLaunchTemplateData.html#API_RequestLaunchTemplateData_Contents) says:

> You can only tag instances and volumes on launch.

In the AWS console:

![create-launch-template](https://user-images.githubusercontent.com/2404182/105578644-ae1f0480-5d4f-11eb-80cb-a94dc9c3f9b2.PNG)

which is what the AWS Provider code has implemented.

To tag any other EC2 resources created implicitly via the launch template you can use the [`aws_ec2_tag`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_tag) resource.
