### ISSUE TITLE
aws_vpc_endpoint_service data source panics on invalid service_type

### ISSUE THREAD

**Issue by tms** [hashicorp/terraform-provider-aws#17463]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.5 / AWS provider v3.26.0

### Affected Resource(s)

* aws_vpc_endpoint_service (data)

### Terraform Configuration Files

```hcl
data "aws_vpc_endpoint_service" "ses" {
    service = "email-smtp"
    service_type = "interface"
}
```

### Panic Output

https://gist.github.com/tms/1fa9f707720342f5fdb8feeaf8f1b07c

### Expected Behavior

(ignoring that `service_type` is not actually needed for the service in the example case)

Matching should possibly be case-insensitive (result returned). Invalid `service_type` should produce an error indicating no matching results found.

### Actual Behavior

Application panic. Since this filtering currently is done client-side, we're past the "no matching VPC Endpoint Service found" checks which look at the response directly, and the only remaining bounds check is [if there's multiple results](https://github.com/hashicorp/terraform-provider-aws/blob/v3.26.0/aws/data_source_aws_vpc_endpoint_service.go#L155). Since in this case there are too _few_ results, `sd := serviceDetails[0]` ends up out of bounds.

### Steps to Reproduce

1. Use an invalid value for `service_type` (incorrect casing, in this case)
2. `terraform apply`

**Comment by ewbankkit** [comment]
@tms Thanks for raising this issue.
It has already been noticed in #17419. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
