### ISSUE TITLE
Please support gRPC status code [0-99] in the matcher of healthcheck of lb_target_group

### ISSUE THREAD

**Issue by habuchin** [hashicorp/terraform-provider-aws#17479]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

#17405 now supports protocol_version = "GRPC", but the health_check matcher does not support gRPC status codes.
We need to be able to specify the status code [0-99] when protocol_version = "GRPC".

### New or Affected Resource(s)

* aws_lb_target_group

### Potential Terraform Configuration

```hcl
resource "aws_lb_target_group" "example" {
  name     = "example"
  port             = 80
  protocol         = "HTTP"
  vpc_id           = xxxxxxxxx
  target_type      = "ip"
  protocol_version = "GRPC"

  health_check {
    interval            = 30
    path                = "/grpc.health.v1.Health/Check"
    port                = "traffic-port"
    protocol            = "HTTP"
    timeout             = 10
    healthy_threshold   = 2
    unhealthy_threshold = 2
    matcher             = "0"
  }
}
```

```Error message
Error: Error modifying Target Group: ValidationError: Health check matcher HTTP code '0' must be within '200-499' inclusive
        status code: 400, request id: xxxxxxxxx
```

### References

* https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html
* #17405

**Comment by ewbankkit** [comment]
At the [API level](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_Matcher.html) the matcher is actually structure with 2 fields, `GrpcCode` and `HttpCode`. Currently the provider always correlates the `matcher` attribute with the `HttpCode` field.
In order not to introduce a breaking change, some logic will have to be introduced to use the correct API field depending on the `health_check.protocol` value.

**Comment by ewbankkit** [comment]
Related:

* https://github.com/hashicorp/terraform-provider-aws/pull/16132
* https://github.com/hashicorp/terraform-provider-aws/pull/17534

**Comment by ewbankkit** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/17534.
