### ISSUE TITLE
New Resource - QLDB Data Streams

### ISSUE THREAD

**Issue by frumpled** [hashicorp/terraform-provider-aws#17471]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

From the docs:

- The QLDB data stream is "a stream of journal data from your ledger to Amazon Kinesis Data Streams."
- "The QLDB stream captures every document revision that is committed to your journal and sends it to a Kinesis data stream."
- "Every QLDB journal stream is a subresource of a ledger and is uniquely identified by an Amazon Resource Name (ARN)."

A key thing to note here is that a QLDB instance can have many data streams.

### New or Affected Resource(s)

* `aws_qldb_stream`

### Potential Terraform Configuration

```hcl
resource "aws_qldb_stream" "some_ledger_data_stream" {
  ledger_name = "source-ledger-name"
  stream_name = "my-stream-name"
  destination_stream = "some-destination-kinesis-arn"
  start_date_time = ""
  end_data_time = "" # optional
  iam-role = "iam-role-arn"
  tags = {}
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-qldb-supports-real-time-streaming/
* https://docs.aws.amazon.com/qldb/latest/developerguide/streams.create.html

**Comment by ewbankkit** [comment]
The resource should probably be named `aws_qldb_stream` as that's how it's named in the [AWS API](https://docs.aws.amazon.com/qldb/latest/developerguide/API_ListJournalKinesisStreamsForLedger.html) and [ARN](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonqldb.html#amazonqldb-resources-for-iam-policies).

**Comment by frumpled** [comment]
Good point, I updated that 😅

**Comment by frumpled** [comment]
Seems like there isn't much interest in this, so I will make an attempt at this myself 😅 
If someone else is already working on this or there's a rush to get this out, please reach out 😄

**Comment by frumpled** [comment]
After doing some digging, it looks like the potential terraform configuration should look more like this:
```terraform
resource "aws_qldb_stream" "sample-ledger-stream" {
  ledger_name          = "existing-ledger-name"
  stream_name          = "sample-ledger-stream"
  role_arn             = "arn:aws:kinesis:us-east-1:xxxxxxxxxxxx:role/sample-role-arn"
  inclusive_start_time = "2021-01-01T00:00:00Z"

  kinesis_configuration = {
    aggegation_enabled = false
    stream_arn         = "arn:aws:kinesis:us-east-1:xxxxxxxxxxxx:stream/example-kinesis-stream"
  }

  tags = {
    "example" = "tag"
  }
}
```

Lmk if anyone has thoughts on this 🤔
