### ISSUE TITLE
Documentation: aws_default_subnet lacks import instructions

### ISSUE THREAD

**Issue by ianwestcott** [hashicorp/terraform-provider-aws#17475]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/aws v3.23.0
```

### Affected Resource(s)

* `aws_default_subnet`

### Issue Description

The [documentation for the `aws_default_subnet` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_subnet) lacks an "Import" section. I was able to import a default subnet by mimicking the [instructions for importing a regular subnet](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/subnet#import), so it is possible. This functionality should be documented.

I was unable to find the source code for the AWS provider documentation, but if it's possible for me to contribute this improvement myself, please point me in the right direction. Thanks!

**Comment by ewbankkit** [comment]
@ianwestcott Thanks for raising this issue.
The `aws_default_subnet` resource does not require `terraform import` functionality as creating a resource of this type actually does the import:

https://github.com/hashicorp/terraform-provider-aws/blob/9c9de45b8e36fc5cffc7f59b3f882a8ec22bee1d/aws/resource_aws_default_subnet.go#L58-L80

This may change when we implement full lifecycle functionality for default subnets: #4957.

**Comment by ianwestcott** [comment]
@ewbankkit thanks for clarifying that.

The auto-import functionality was unclear to me, because when I ran `terraform plan` the output implied that Terraform would attempt to create the resource:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_default_subnet.default will be created
  + resource "aws_default_subnet" "default" {
      + arn                             = (known after apply)
      + assign_ipv6_address_on_creation = (known after apply)
      + availability_zone               = "us-east-1f"
      + availability_zone_id            = (known after apply)
      + cidr_block                      = (known after apply)
      + id                              = (known after apply)
      + ipv6_cidr_block                 = (known after apply)
      + ipv6_cidr_block_association_id  = (known after apply)
      + map_public_ip_on_launch         = (known after apply)
      + owner_id                        = (known after apply)
      + vpc_id                          = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

Given that the resource already existed, my next recourse was to try importing it, and that worked despite the lack of documentation.

Is it expected behavior for Terraform to show `aws_default_subnet` resources as pending creation when running `terraform plan`, and "adopt" them into state only on apply? If so, that could be made clearer in either the plan output, or the documentation, or both. I'd be happy to open a new ticket for that issue if it makes sense, but I wanted clarify the expected behavior first. (Alternatively, please let me know if there's a better forum for this discussion.) Thanks!

**Comment by ewbankkit** [comment]
Yes, that is "expected". Terraform core knows only that a resource is to be created, not that the resource doesn't actually create anything at AWS but instead adopts the resource into management.
There's an issue https://github.com/hashicorp/terraform-provider-aws/issues/17374 that I have open collecting some suggestions for additions to the [maintainer documentation](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/provider-design.md) about various non-standard resource or attribute patterns and I'll add an item there.

The [practitioner documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_subnet) comment we have is

![default-subnet](https://user-images.githubusercontent.com/2404182/107085921-2c0af300-67c7-11eb-9f64-74d25768dc18.PNG)

Can you think of a better way of capturing the behavior?

**Comment by ianwestcott** [comment]
@ewbankkit I think that's a good start, but I would want to see a note added to clarify that the adoption happens at the `apply` stage, and caveat that the resource will show in the `terraform plan` output as needing to be "created", even though no state will be manipulated in AWS during apply. In my case, the `plan` output gave me pause, because I was concerned about making unwanted changes to my infrastructure. That's what led me to try to import it, and create this ticket.
