### ISSUE TITLE
outpost_arn support for aws_ebs_snapshot

### ISSUE THREAD

**Issue by FireballDWF** [hashicorp/terraform-provider-aws#17491]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

add the outpost_arn attribute to enable snapshots to be stored on the specified Outpost, as an alternative to the default behavior of snapshots from being stored in the region

### New or Affected Resource(s)

* aws_ebs_snapshot

### Potential Terraform Configuration

```hcl
outpost_arn - (Optional) The Amazon Resource Name (ARN) of the Outpost to store the snapshot on
```

### References

* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSnapshot.html

**Comment by ewbankkit** [comment]
[Announcement](https://aws.amazon.com/about-aws/whats-new/2021/02/introducing-amazon-ebs-local-snapshots-on-outposts/).
[Blog post](https://aws.amazon.com/blogs/aws/new-amazon-elastic-block-store-local-snapshots-on-aws-outposts/).
