### ISSUE TITLE
Error: error creating API Gateway v2 route: BadRequestException: Invalid authorizer ID specified. Setting the authorization type to CUSTOM or COGNITO_USER_POOLS requires a valid authorizer.

### ISSUE THREAD

**Issue by mwhiter** [hashicorp/terraform-provider-aws#17497]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

`Terraform v0.14.0`

### Affected Resource(s)

* aws_apigatewayv2_authorizer
* aws_apigatewayv2_route

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_apigatewayv2_authorizer" "api-gateway-auth0-authorizer" {
  api_id           = aws_apigatewayv2_api.api-gateway-staging.id
  authorizer_type  = "JWT"
  identity_sources = ["$request.header.Authorization"]
  name             = "auth0-authorizer"

  jwt_configuration {
the Auth0 API identifier
    audience = [trim(aws_apigatewayv2_stage.api-gateway-stage-staging.invoke_url, "/")]
    issuer   = var.auth0_tenant_domain_url
  }
}

resource "aws_apigatewayv2_route" "api-gateway-staging-route-buildings" {
  api_id             = aws_apigatewayv2_api.api-gateway-staging.id
  route_key          = "ANY /buildings/{proxy+}"
  target             = "integrations/${aws_apigatewayv2_integration.api-gateway-integration-buildings.id}"
  authorization_type = "CUSTOM"
  authorizer_id      = aws_apigatewayv2_authorizer.api-gateway-auth0-authorizer.id
}
```

### Debug Output

Terraform Plan (Redacted): https://gist.github.com/mwhiter/fa6cba0bc321415ce40f08d97e59ea09
Terraform Apply (Redacted): https://gist.github.com/mwhiter/33dda3b13a2c0e72b6e2beb27378f15b

### Panic Output

None

### Expected Behavior

Terraform should create the Route correctly. The `aws_apigatewayv2_authorizer` output `id` should be the `authorizer_id` used in the `aws_apigatewayv2_route`.

Per `aws_apigatewayv2_authorizer` documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_authorizer#id
> id - The authorizer identifier.

Per `aws_apigatewayv2_route` documentation:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_route#authorizer_id
> authorizer_id - (Optional) The identifier of the aws_apigatewayv2_authorizer resource to be associated with this route, if the authorizationType is CUSTOM.

Manually associating the route to the authorizer works, so something must be wrong with the Terraform config:

![image](https://user-images.githubusercontent.com/4925402/107127138-17d7fc00-6882-11eb-9a11-79ade9643ea4.png)

### Actual Behavior

Amazon API throws this error on apply:
> Error: error creating API Gateway v2 route: BadRequestException: Invalid authorizer ID specified. Setting the authorization type to CUSTOM or COGNITO_USER_POOLS requires a valid authorizer.

### Steps to Reproduce

1. `terraform apply` with above configuration

### Important Factoids

1. I set up an API Gateway with a route. The configuration is a terraform version of the approach documented here: https://auth0.com/blog/securing-aws-http-apis-with-jwt-authorizers/

### References

* #0000

**Comment by ewbankkit** [comment]
@mwhiter Thanks for raising this issue.
Please try setting `authorization_type = "JWT"` in your configuration, that fixed the issue for me in testing.
The AWS API error message is misleading (as that is a valid authorizer ID) - I will update the Terraform AWS Provider documentation.

**Comment by ewbankkit** [comment]
Related:

* https://github.com/hashicorp/terraform-provider-aws/issues/12972

**Comment by mwhiter** [comment]
Looks like adding `authorization_type = "JWT"` to the route helped. Thanks @ewbankkit!

This configuration works:
```
resource "aws_apigatewayv2_route" "api-gateway-staging-route-buildings" {
  api_id    = aws_apigatewayv2_api.api-gateway-staging.id
  route_key = "ANY /buildings/{proxy+}"
  target    = "integrations/${aws_apigatewayv2_integration.api-gateway-integration-buildings.id}"

  authorizer_id      = aws_apigatewayv2_authorizer.api-gateway-auth0-authorizer.id
  authorization_type = "JWT"
}
```
