### ISSUE TITLE
Provider produced inconsistent result after apply when HTTPS instead of https as protocol for an aws_sns_topic_subscription

### ISSUE THREAD

**Issue by madpipeline** [hashicorp/terraform-provider-aws#17509]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform: `v0.12.24`
Provider: `2.45`

### Affected Resource(s)

* aws_sns_topic_subscription

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
variable "sns_subscriptions" {
  description = "A list of objects with `protocol` and `endpoint` to be created as subscriptions to the sns topic."
  type = list(object({
    protocol = string
    endpoint = string
  }))
  default = []
}

resource "aws_sns_topic_subscription" "sns_subscriptions" {
  count                  = length(var.sns_subscriptions)
  topic_arn              = aws_sns_topic.sns.arn
  protocol               = element(var.sns_subscriptions.*.protocol, count.index)
  endpoint               = element(var.sns_subscriptions.*.endpoint, count.index)
  endpoint_auto_confirms = true
}

# value of var.sns_subscriptions is:
sns_subscriptions = [
  {
    protocol = "HTTPS"
    endpoint = "https://events.pagerduty.com/integration/XXXXXXX/enqueue"
  }
]

```

### Debug Output

https://gist.github.com/madpipeline/43def6a230de01cdab0be20720efbc4b

### Expected Behavior

```
module.sns.aws_sns_topic.sns: Refreshing state... [id=arn:aws:sns:us-east-1:XXXXXX:XXX]
module.sns.aws_sns_topic_subscription.sns_subscriptions[0]: Creating...
module.sns.aws_sns_topic_subscription.sns_subscriptions[0]: Creation complete after 2s [id=arn:aws:sns:us-east-1:XXXX:XXXX:XXXX]

```

### Actual Behavior

```
module.sns.aws_sns_topic.sns: Refreshing state... [id=arn:aws:sns:us-east-1:XXXXXX:XXX]
module.sns.aws_sns_topic_subscription.sns_subscriptions[0]: Creating...
Error: Provider produced inconsistent result after apply

When applying changes to
module.sns.aws_sns_topic_subscription.sns_subscriptions[0], provider
"registry.terraform.io/-/aws" produced an unexpected new value for was
present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The issue goes away if you change the value of `protocol` from `HTTPS` to `https`.

**Comment by ewbankkit** [comment]
Similar:

* #11737
* #12692
* #16695

**Comment by ewbankkit** [comment]
@madpipeline Thanks for raising this issue.
It has already been noticed in #11737. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by madpipeline** [comment]
Hello @ewbankkit . Sorry for the duplicate. I didn't find that ticket when I looked if it was already reported. I'll be more careful next time.

**Comment by ewbankkit** [comment]
@madpipeline No worries, there are a lot of open issues.
