### ISSUE TITLE
Terraform doesn't support custom hostname configuration for internet facing aws sftp server.

### ISSUE THREAD

**Issue by poojasingh-cgi** [hashicorp/terraform-provider-aws#17507]
Community Note
Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

Description:-
@hashicorp-cloud, I couldn't find argument reference for custom hostname creation within sftp in the below registry documentation.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_server

is this new feature update yet to come in terraform aws provider for sftp?

**Comment by ewbankkit** [comment]
@poojasingh-cgi Thanks for raising this issue.
A custom hostname for a Transfer server can be setup using [Amazon Route 53](https://docs.aws.amazon.com/transfer/latest/userguide/requirements-dns.html) and the [`aws_route53_record`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_record) resource.
You can use the [`endpoint`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_server#endpoint) attribute of the server as the [`CNAME` record's value](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html#CNAMEFormat).

**Comment by poojasingh-cgi** [comment]
> @poojasingh-cgi Thanks for raising this issue.
> A custom hostname for a Transfer server can be setup using [Amazon Route 53](https://docs.aws.amazon.com/transfer/latest/userguide/requirements-dns.html) and the [`aws_route53_record`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_record) resource.
> You can use the [`endpoint`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_server#endpoint) attribute of the server as the [`CNAME` record's value](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html#CNAMEFormat).

thanks for your update, currently i've setup using route 53 however I am looking for an option in sftp itself to create a custom hostname via terraform. 

![image](https://user-images.githubusercontent.com/61690409/107228923-83a29c00-6a1d-11eb-8298-d87a37581d82.png)

**Comment by poojasingh-cgi** [comment]
@ewbankkit, there should be an custom hostname argument supported in terraform for sftp server so we can configure custom hostname as part of endpoint_details.
