### ISSUE TITLE
aws_iot_topic_rule support for MSK

### ISSUE THREAD

**Issue by yayfeng** [hashicorp/terraform-provider-aws#17506]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* Terraform v0.13+
+ provider.aws v3.27.0

AWS has launched the support for delivering message to MSK in IoT Actions, see
https://aws.amazon.com/about-aws/whats-new/2020/12/aws-iot-core-adds-the-ability-to-deliver-data-to-apache-kafka-clusters/ for more details.

Any plan to support this?

**Comment by ewbankkit** [comment]
Affected resource [`aws_iot_topic_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_topic_rule).
