### ISSUE TITLE
flow_logs_s3_prefix is 'Required' when it should be 'Optional'

### ISSUE THREAD

**Issue by gitoutthere** [hashicorp/terraform-provider-aws#17519]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```bash
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/archive v2.0.0
+ provider registry.terraform.io/hashicorp/aws v3.26.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.0.0
```

### Affected Resource(s)

* aws_globalaccelerator_accelerator

### Terraform Configuration Files

```hcl
resource "aws_globalaccelerator_accelerator" "my_ga" {
  name            = "ga"
  ip_address_type = "IPV4"
  enabled         = true
  attributes {
    flow_logs_enabled   = true
    # flow_logs_s3_prefix = ""
    flow_logs_s3_bucket = aws_s3_bucket.central_logs.bucket
  }
}
```

### Expected Behavior

Terraform should create the flow log without requiring `flow_logs_s3_prefix` as per documentation.

### Actual Behavior

`Error: Error updating Global Accelerator accelerator attributes: InvalidArgumentException: Flow logs prefix should not be empty.`

### Steps to Reproduce

1. Create an aws_globalaccelerator_accelerator resource with flow logs enabled.
2. Do not include  `flow_logs_s3_prefix` attribute.
3. `terraform apply`

### References

Could be related to this?
* #14185

**Comment by ewbankkit** [comment]
@gitoutthere Thanks for raising this issue.
The [AWS API Reference](https://docs.aws.amazon.com/global-accelerator/latest/api/API_UpdateAcceleratorAttributes.html#globalaccelerator-UpdateAcceleratorAttributes-request-FlowLogsS3Prefix) is confusing here:

> Update the prefix for the location in the Amazon S3 bucket for the flow logs. Attribute is required if FlowLogsEnabled is true.
>
> If you don’t specify a prefix, the flow logs are stored in the root of the bucket. 

I will investigate.

**Comment by gitoutthere** [comment]
Thanks @ewbankkit . Further notes below which you may find useful.

Most AWS resource produce logs under below path structure:
`s3-bucket_name/s3-bucket-prefix/AWSLogs/aws_account_id/resource_name/region/`
So when you don't provide a prefix it would give you similar to below:
`my-s3-bucket/AWSLogs/123456789012/guardduty/us-west-2/`
Ideally we want the same thing with the Global Accelerator. 

We also tried to pass `/` as prefix so we get `s3-bucket_name//AWSLogs/aws_account_id` structure, but this will only create a folder named '/' in the root of the bucket and inside it `/AWSLogs/aws_account_id/globalaccelerator/region/`

**Comment by ewbankkit** [comment]
This is the offending code:

https://github.com/hashicorp/terraform-provider-aws/blob/3408713a4d636e4c9f074f8d5185b19daa65c5f3/aws/resource_aws_globalaccelerator_accelerator.go#L340-L342

per the [guidelines](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/data-handling-and-conversion.md#nested-typestring-and-aws-string), we should compare against `""`, not `nil`.

From the [API Reference](https://docs.aws.amazon.com/global-accelerator/latest/api/API_UpdateAcceleratorAttributes.html#globalaccelerator-UpdateAcceleratorAttributes-request-FlowLogsS3Prefix)

> If you don’t specify a prefix, the flow logs are stored in the root of the bucket. If you specify slash (/) for the S3 bucket prefix, the log file bucket folder structure will include a double slash (//), like the following:
>
> s3-bucket_name//AWSLogs/aws_account_id

**Comment by ewbankkit** [comment]
Even with that fix, so not passing `""` for the S3 prefix, I still get the same error:

```
{"AcceleratorArn":"arn:aws:globalaccelerator::123456789012:accelerator/87665b2e-f216-49ff-8db0-2af21da301a6","FlowLogsEnabled":true,"FlowLogsS3Bucket":"tf-test-globalaccelerator-20210209225321231800000001"}
2021-02-09T17:53:55.136-0500 [INFO]  plugin.terraform-provider-aws: 2021/02/09 17:53:55 [DEBUG] [aws-sdk-go] {"__type":"InvalidArgumentException","Message":"Flow logs prefix should not be empty."}: timestamp=2021-02-09T17:53:55.136-0500
```

I suggest contacting AWS Support and seeing if specifying no prefix is actually possible.

**Comment by gitoutthere** [comment]
This is a not so ideal response from AWS:

> I checked the related ticket internally and at AWS we recognize that the document statement is bit misleading relating to --flow-logs-s3-prefix.
> Hence the AWS documentation will be updated to reflect the following:
> 
> "The flag --flow-logs-s3-prefix (string) is needed when FlowLogsEnabled is set to true" 
> 
> in absence of this prefix, it will throw the following error:
> aws: error: argument --flow-logs-s3-prefix: expected one argument
> 
> if you pass an empty prefix then it will throw the following error:
> An error occurred (InvalidArgumentException) when calling the UpdateAcceleratorAttributes operation: Flow logs prefix should not be empty."

**Comment by gitoutthere** [comment]
Further in my conversation above. AWS will be updating their documentation accordingly (making `--flow-logs-s3-prefix` required when flow logs is enabled. I am assuming that they'll be fixing the issue to make it optional in future.

Should Terraform documentation be updated to reflect the current as-is?

**Comment by ewbankkit** [comment]
Yes, the documentation can definitely be improved here.
