### ISSUE TITLE
WebSocket API Gateway (v2) - Integration responsive doesn't appear

### ISSUE THREAD

**Issue by enzo-billis** [hashicorp/terraform-provider-aws#17528]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.6
AWS Provider 3.26.0

### Affected Resource(s)

* aws_apigatewayv2_integration_response
* aws_apigatewayv2_route_response

### Terraform Configuration Files

```hcl
resource "aws_apigatewayv2_api" "myapi" {
  name                       = "myapi"
  protocol_type              = "WEBSOCKET"
  route_selection_expression = "$request.body.action"
}

resource "aws_apigatewayv2_route" "connectRoute" {
  api_id    = aws_apigatewayv2_api.myapi.id
  route_key = "$connect"
  target = "integrations/${aws_apigatewayv2_integration.connectIntegration.id}"
}

resource "aws_apigatewayv2_integration" "connectIntegration" {
  api_id              = aws_apigatewayv2_api.myapi.id
  integration_type    = "MOCK"
}

resource "aws_apigatewayv2_route_response" "connectResponse" {
  api_id             = aws_apigatewayv2_api.myapi.id
  route_id           = aws_apigatewayv2_route.connectRoute.id
  route_response_key = "$default"
}

resource "aws_apigatewayv2_integration_response" "connectIntegrationReponse" {
  api_id                   = aws_apigatewayv2_api.myapi.id
  integration_id           = aws_apigatewayv2_integration.connectIntegration.id
  integration_response_key = "$default"
  template_selection_expression = "xxx"
  response_templates = {
    "$default" = "{}"
  }
}
```

### Debug Output

Not concerned, there is no error while applying.

### Expected Behavior

It should create a integration response

### Actual Behavior

Integration reponse doesn't appear. For example route $connect doesn't work because it need a response.
![image](https://user-images.githubusercontent.com/23307522/107381126-d39d6380-6aee-11eb-83e7-7f14dff78627.png)

But, if I try to add it manually through the GUI, "Add integration response", it will prompt an error box meaning $default reponse is already defined. Finally, if I refresh after this error box, integration reponse appear, like if a kind of state had been refreshed.

![image](https://user-images.githubusercontent.com/23307522/107381462-270fb180-6aef-11eb-8515-1767c9677d01.png)

![image](https://user-images.githubusercontent.com/23307522/107381518-35f66400-6aef-11eb-8b12-4ccaf641844c.png)

### Steps to Reproduce

1. `terraform apply`
2. Deploy your API and try to connect to your API with any WS Client
3. See the 403 error
4. Go to AWS Console Management > Your API
5. Check $connect route and see there is no integreation response appearing
6. Try clicking "Add integration response" and read the error message
7. Refresh F5
8. See the integration reponse appearing 
9. Deploy
10. Wait few minutes and try again to connect to your API, it's working nice now

### Important Factoids

No

**Comment by ewbankkit** [comment]
@enzo-billis Thanks for raising this issue.
I see the same thing in the AWS Console - I `terraform apply` your configuration and the route response doesn't show in the console.
It's there via the API:

```console
$ aws --region us-west-2 apigatewayv2 get-route-responses --api-id ryzgeoo2qk --route-id t9bta2p
{
    "Items": [
        {
            "RouteResponseId": "f1tydm",
            "RouteResponseKey": "$default"
        }
    ]
}
```

and I can see in the Chrome Developer Tools that the AWS Console gets that same data:

```
headers: {X-Amz-User-Agent: "aws-sdk-js/2.589.0 promise", Content-Type: "application/json"}
method: "GET"
operation: "getRouteResponses"
params: {}
path: "/apis/ryzgeoo2qk/routes/t9bta2p/routeresponses"
region: "us-west-2"

{"items":[{"routeResponseId":"f1tydm","routeResponseKey":"$default"}]}
```

This must be a bug in the console.
I suggest that you raise a ticket with AWS Support.

**Comment by enzo-billis** [comment]
Thank's for reply
I will contact them and update the issue once I get an answer.

**Comment by enzo-billis** [comment]
AWS Support replied to me, this is not an issue from AWS or Terraform, but a missing argument in my configuration file.
I need to use `route_response_selection_expression = "$default"` in my `aws_apigatewayv2_route` ressource.
Case solved, thank's for helping me.
