### ISSUE TITLE
Support AWS OpsWorks CM

### ISSUE THREAD

**Issue by Fuuzetsu** [hashicorp/terraform-provider-aws#17523]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There are two AWS OpsWorks services: `AWS OpsWorks Stacks` and `AWS OpsWorks CM`: https://docs.aws.amazon.com/opsworks/index.html . Only the former is currently supported in the provider. Both are supported in the AWS Go SDK.

The AWS OpsWorks CM allows for provisioning and managing Chef Automate and Puppet services.

### New or Affected Resource(s)

* `aws_opsworkscm_*`

### Potential Terraform Configuration

Straight-forward translation of the API from the Go SDK should be possible.

### References

* https://docs.aws.amazon.com/opsworks-cm/latest/APIReference/Welcome.html

**Comment by ewbankkit** [comment]
@Fuuzetsu Thanks for raising this issue.
It has already been noticed in #403 for Chef Automate and #14084 for Puppet Enterprise. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issues.
Please add any additional comments there.
