### ISSUE TITLE
Terraform to control ECS Service App Autoscaling completely - Scaling Action part is missing

### ISSUE THREAD

**Issue by kodeeshm** [hashicorp/terraform-provider-aws#17529]
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)
AWS ECS Tasks autoscaling fails

### Terraform Configuration Files
```hcl
resource "aws_appautoscaling_policy" "ecs_policy-down" {
  name = "${aws_ecs_service.service.name}-scale-down"
  policy_type = "StepScaling"
  resource_id = aws_appautoscaling_target.ecs_target.resource_id
  scalable_dimension = aws_appautoscaling_target.ecs_target.scalable_dimension
  service_namespace = aws_appautoscaling_target.ecs_target.service_namespace

  step_scaling_policy_configuration {
    adjustment_type = "ChangeInCapacity"
    cooldown = 60
    metric_aggregation_type = "Maximum"

    step_adjustment {
      scaling_adjustment = -1
      metric_interval_upper_bound = 0
    }
  }
}
```
### Debug Output
Error: Failed to update scaling policy: ValidationException: There must be a step adjustment with an unspecified upper bound when one step adjustment has a positive upper bound

### Expected Behavior

It should fill in Scaling Action with Add/Remove tasks with given policy conditions

### Actual Behavior

It updated for one policy and failed for another policy

### Steps to Reproduce
Use the code above and run terraform apply

![image](https://user-images.githubusercontent.com/38654198/107384797-4ec73f80-6b18-11eb-93af-6db752c6a6fa.png)

**Comment by anGie44** [comment]
Hi @kodeeshm , thank you for raising this issue. To further investigate the error you are seeing, do you mind providing the full configuration(s) you initially applied so i can attempt to reproduce the "update" behavior?

**Comment by kodeeshm** [comment]
Thanks @anGie44 for your response, Here you go for the configuration I've been trying...

Please fill the values according to your choice and run to see if this is reproducible on your environment.

resource "aws_ecs_service" "service" {
  	name            = service_test
  	iam_role        = iam_role
  	cluster         = cluster_name
  	task_definition = task-definition_arn
  	health_check_grace_period_seconds = 60
    scheduling_strategy = "REPLICA"
    
    deployment_maximum_percent = 100
    deployment_minimum_healthy_percent = 50

  	load_balancer {
    	target_group_arn  = target_group_arn
    	container_port    = 80
    	container_name    = container_name
	  }

    ordered_placement_strategy {
      type  = "spread"
      field = "instanceId"
    }
    
    ordered_placement_strategy {
      type  = "spread"
      field = "attribute:ecs.availability-zone"
    }

    placement_constraints {
      type       = "memberOf"
      expression = "attribute:ecs.availability-zone in [${var.GeneralSettings.availability_zones}]"
    }

    lifecycle {
    ignore_changes = [desired_count]
   }
   depends_on = [null_resource.dependency_getter, aws_ecs_task_definition.task-definition, aws_lb_listener_rule.ecs-host-rule ]
}

resource "aws_cloudwatch_metric_alarm" "alarm_cpu-high" {
  alarm_name        = service_name_-high-cpu
  alarm_description = "Monitors ECS Memory Utilization"
  
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = "2"
  metric_name         = "CPUUtilization"
  namespace           = "AWS/ECS"
  period              = "60"
  statistic           = "Average"
  threshold           = 50
  //ARN of the policy
  alarm_actions = [
    aws_appautoscaling_policy.ecs_policy-up.arn
  ]
  dimensions = {
    "ClusterName" = var.ecs_cluster_name
    "ServiceName" = aws_ecs_service.service.name
  }
}

resource "aws_cloudwatch_metric_alarm" "alarm_cpu-low" {
  alarm_name        = service_name_alarm-low-cpu
  alarm_description = "Monitors ECS Memory Utilization"
  
  comparison_operator = "LessThanOrEqualToThreshold"
  evaluation_periods  = "4"
  metric_name         = "CPUUtilization"
  namespace           = "AWS/ECS"
  period              = "60"
  statistic           = "Average"
  threshold           = 30
  //ARN of the policy
  alarm_actions = [
    aws_appautoscaling_policy.ecs_policy-down.arn
  ]
  dimensions = {
    "ClusterName" = cluster_name
    "ServiceName" = service_name
  }
}

resource "aws_appautoscaling_target" "ecs_target" {
  max_capacity       = 3
  min_capacity       = 2
  resource_id        = "service/${var.ecs_cluster_name}/${aws_ecs_service.service.name}"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"
}

resource "aws_appautoscaling_policy" "ecs_policy-down" {
  name               = service_name-scale-down
  policy_type        = "StepScaling"
  resource_id        = aws_appautoscaling_target.ecs_target.resource_id
  scalable_dimension = aws_appautoscaling_target.ecs_target.scalable_dimension
  service_namespace  = aws_appautoscaling_target.ecs_target.service_namespace

  step_scaling_policy_configuration {
    adjustment_type         = "ChangeInCapacity"
    cooldown                = 60
    metric_aggregation_type = "Maximum"
    
    step_adjustment {
      metric_interval_upper_bound = 0
      scaling_adjustment          = -1
    }
  }
}

resource "aws_appautoscaling_policy" "ecs_policy-up" {
  name               = service_name-scale-up"
  policy_type        = "StepScaling"
  resource_id        = aws_appautoscaling_target.ecs_target.resource_id
  scalable_dimension = aws_appautoscaling_target.ecs_target.scalable_dimension
  service_namespace  = aws_appautoscaling_target.ecs_target.service_namespace

  step_scaling_policy_configuration {
    adjustment_type         = "ChangeInCapacity"
    cooldown                = 60
    metric_aggregation_type = "Maximum"
    
    step_adjustment {
      metric_interval_upper_bound = 0
      scaling_adjustment          = 1
    }
  }
}

**Comment by kodeeshm** [comment]
We have fixed the issue by using 'metric_interval_lower_bound = 0' in scale up and 'metric_interval_upper_bound = 0' in scale down policy setup block...
