### ISSUE TITLE
Error authorizing security group egress rules:  InvalidGroup.NotFound: The security group 'sg-ANOTHER_ACCOUNT_ANOTHER_REGION' does not exist

### ISSUE THREAD

**Issue by jfairchild** [hashicorp/terraform-provider-aws#17537]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_security_group egress rule

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

aws_security_group.vpn: Modifying... [id=sg-XXX]

Error: Error authorizing security group egress rules: InvalidGroup.NotFound: The security group 'sg-XXX' does not exist
	status code: 400, request id: XXXX

  on vpn.tf line 24, in resource "aws_security_group" "vpn":
  24: resource "aws_security_group" "vpn" {

### Expected Behavior

allow a rule to connect to another account in another region
### Steps to Reproduce

1. set up vpc peering connection
2. add rule to connect from 1 security group to the other security group
3. plan
4. plan should show connection from 1 security group to "accountid/sg-id"
1. `terraform apply`
2. apply fails ": InvalidGroup.NotFound"

### References

* #0000

**Comment by anGie44** [comment]
Hi @jfairchild , thank you for raising this issue. To further investigate the error you're seeing, do you mind providing details including:
(1) Terraform AWS Provider version you are working with
(2) The terraform configuration being applied; can be a snippet with negligible attributes omitted for brevity 
(3) Any debug/trace logs of the incident in question if reproducible on your end or readily available

thanks in advance!

**Comment by jfairchild** [comment]
Thanks for getting back to me @anGie44. I'm going to close this issue because it appears to be an issue with the AWS API. I'm going to reach out to them directly.
