### ISSUE TITLE
Allow data resource that lookup sets of items to return empty sets.

### ISSUE THREAD

**Issue by bcsgh** [hashicorp/terraform-provider-aws#17540]
### Community Note

* Please vote on this issue by adding a � [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

data resource that exist to generate a list of items should (or should be able to) return an empty list when no resource match the filters used.

### New or Affected Resource(s)

More or less any data resource ending in a plural, a few of many that likely exhibit this issue:  

* `aws_autoscaling_groups`
* `aws_instances`
* `aws_subnet_ids`
* ...

### Potential Terraform Configuration

I need to create a resource for_each of some other thing. Things that exists outside TF's control.

```hcl
data "aws_things" "lookup" {
  ...
}

resource "aws_other_thing" "make" {
  for_each = data.aws_things.lookup.ids

  ...
  build_from_thing = each.key
}
```

(note this is only one of several patterns that run into this problem, but in my experience the most common.)

Right now this works, but only when something is actually found.
When the possibility exist that in, non error condition, there may be zero of those things, making things work is much more complex.
All (or most) data resource that lookup sets of things issue an error when they find nothing.

### Attempted Solutions

The general workaround is to use a wider query that is assured to always return _something_ and lookup enough about each of those results to manually filter that in terraform.
Besides being much more complex and requiring many more data requests, this has many other issues that I shouldn't need to go into.

### References

https://github.com/hashicorp/terraform/issues/27712

**Comment by ewbankkit** [comment]
Relates:

* https://github.com/hashicorp/terraform-provider-aws/pull/17546
* #8302
* #17382
* #13951
* https://github.com/hashicorp/terraform-provider-aws/pull/13982
* https://github.com/hashicorp/terraform-provider-aws/issues/17446

(and probably others)

**Comment by bcsgh** [comment]
Glad to see that. It looks like other more specific issues predate this one. I'll leave it up to you to decide if having a totally general issues open is worth while. If not I'm find with this being marked as a duplicate.

Keep up the good work!

p.s. could someone _please_ acknowledge https://github.com/hashicorp/terraform/issues/13022 ?

**Comment by bflad** [comment]
We have now documented in our [Provider Design documentation](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/provider-design.md) that _plural_ data sources should return zero, one, or multiple results without error. Singular data sources should still return an error when the remote component is not found.

We can go back through any non-conformant plural data sources to fix them up, but this might want to wait until our next major release since it is a behavior change for the existing cases. I'm going to mark it with that milestone for tracking for now, but it might be done sooner depending on some further investigation work to determine if it was previously possible to rely on the error in configurations (e.g. with `try()`).

**Comment by zpriddy** [comment]
I was wondering if there are any updates on this or #13951 ?

**Comment by anGie44** [comment]
List of Affected Data Sources:

- [ ] aws_vpc_peering_connections
- [ ] aws_cognito_user_pools
- [ ] aws_ec2_coip_pools
- [ ] aws_ebs_volumes
- [ ] aws_local_gateway_route_tables
- [ ] aws_ec2_local_gatway_virtual_interface_groups
- [ ] aws_ec2_local_gateways
- [ ] aws_network_acls
- [ ] aws_network_interfaces
- [ ] aws_route_tables
- [ ] aws_subnet_ids
- [ ] aws_ec2_transit_gateway_route_tables
- [ ] aws_vpcs
- [ ] aws_efs_access_points
- [ ] aws_emr_release_labels
- [ ] aws_inspector_rules_packages
- [ ] aws_ip_ranges
- [ ] aws_db_event_categories
- [ ] aws_servicecatalog_portfolio_constraints
- [ ] aws_ssoadmin_instances
