### ISSUE TITLE
aws_workspaces_directory workspace_access_properties lacks device_type_linux setting which is available in AWS Console

### ISSUE THREAD

**Issue by guydavis** [hashicorp/terraform-provider-aws#17553]
As show in attached AWS Console allows one to enable Linux device access to an AWS Workspaces Directory, however the aws_workspaces_directory workspace_access_properties lacks device_type_linux setting.  Example:

```
resource "aws_workspaces_directory" "my-directory" {
  provider    = aws.resources-eu-west-1
  directory_id = aws_directory_service_directory.my-connector.id
  subnet_ids = [aws_subnet.my-private2.id, aws_subnet.my-private3.id,]

  workspace_creation_properties {
    custom_security_group_id            = "sg-123456789"
    default_ou                          = "OU=Workspaces,DC=ad,DC=dev,DC=foo,DC=com"
    enable_internet_access              = false
    enable_maintenance_mode             = true
    user_enabled_as_local_administrator = false
  }

  workspace_access_properties {
    device_type_android    = "ALLOW"
    device_type_chromeos   = "ALLOW"
    device_type_ios        = "ALLOW"
    device_type_osx        = "ALLOW"
    device_type_web        = "ALLOW"
    device_type_windows    = "ALLOW"
    device_type_zeroclient = "ALLOW"
    device_type_linux      = "ALLOW"
  }
}
```

Terraform jobs with that setting fail with `Error: Unsupported argument`.  Using: Plugin for provider "aws" (hashicorp/aws) 3.27.0.

![20210210_112903](https://user-images.githubusercontent.com/12936/107555224-22e99f80-6b94-11eb-9254-7669a11cebe5.png)

**Comment by anGie44** [comment]
Hi @guydavis, thank you for raising this issue. Unfortunately, I believe we're blocked at this time by the upstream AWS API / AWS Go SDK as the property is not yet configurable programmatically (supported attributes: https://docs.aws.amazon.com/workspaces/latest/api/API_WorkspaceAccessProperties.html).

**Comment by danial-k** [comment]
Still unavailable in upstream; also missing from CLI v2 docs: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/workspaces/modify-workspace-access-properties.html

**Comment by hicklemon** [comment]
This is now available in the Go SDK:

https://github.com/aws/aws-sdk-go/blob/v1.38.58/service/workspaces/api.go#L11214

**Comment by mattk-ce** [comment]
Any sense of when this can be done?
