### ISSUE TITLE
AWS SSM Maintenance Window Task Outputs allow cloudwatch in the console, no option in terraform

### ISSUE THREAD

**Issue by aromond** [hashicorp/terraform-provider-aws#17554]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

aws_ssm_maintenance_window_task does not have any parameters for cloudwatch output for Run Commands. This is an option in the console but I can't seem to use it with my terraform.

### New or Affected Resource(s)

* aws_ssm_maintenance_window_task

### Potential Terraform Configuration
```hcl 
resource "aws_ssm_maintenance_window_task" "test" {
  window_id        = aws_ssm_maintenance_window.test.id
  task_type        = "RUN_COMMAND"
  task_arn         = "AWS-RunShellScript"
  priority         = 1
  service_role_arn = aws_iam_role.test.arn
  max_concurrency  = "2"
  max_errors       = "1"

  targets {
    key    = "WindowTargetIds"
    values = [aws_ssm_maintenance_window_target.test.id]
  }

  task_invocation_parameters {
    run_command_parameters {
      cloud_watch_output_config {
        cloud_watch_log_group_name = "example"
        cloud_watch_output_enabled   = true
      }
    }
  }
}
```

### References

* https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_MaintenanceWindowRunCommandParameters.html#systemsmanager-Type-MaintenanceWindowRunCommandParameters-CloudWatchOutputConfig
* https://docs.aws.amazon.com/sdk-for-go/api/service/ssm/#MaintenanceWindowRunCommandParameters

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 3.28.0 of the Terraform AWS Provider, later today. Thank you to @DrFaust92, @0x91, and @mycodeself for the implementation efforts. 👍
