### ISSUE TITLE
Support SES v2 Delivery Delayed notifications

### ISSUE THREAD

**Issue by piotrb** [hashicorp/terraform-provider-aws#17570]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of ~June 2020 AWS had support for enabling notifications for messages being delayed in their system waiting on a soft bounce.

https://aws.amazon.com/about-aws/whats-new/2020/06/amazon-ses-can-now-send-notifications-when-the-delivery-of-an-email-is-delayed/

This seems to be a bit special since they have a big note about it .. 

> To add the DELIVERY_DELAY event type to an event destination, you have to use the UpdateConfigurationSetEventDestination operation in the Amazon SES API V2. Currently, you can't add this event type to a configuration set by using the Amazon SES console.

here: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/event-publishing-add-event-destination-sns.html

It's also not available to be set in the AWS UI.

### New or Affected Resource(s)

* aws_sesv2_event_destination

### Potential Terraform Configuration

```hcl
resource "aws_sesv2_event_destination" "cloudwatch" {
  matching_types         = ["delay"] # of course combined with any other valid value for this field
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2020/06/amazon-ses-can-now-send-notifications-when-the-delivery-of-an-email-is-delayed/
* https://docs.aws.amazon.com/ses/latest/DeveloperGuide/event-publishing-add-event-destination-sns.html
* https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_EventDestinationDefinition.html#SES-Type-EventDestinationDefinition-MatchingEventTypes

**Comment by anGie44** [comment]
Hi @piotrb, thank you for creating this issue! Just noting here this `delay` type is only available in the `sesv2` service client (not currently supported in the AWS Provider atm.

**Comment by Puneeth-n** [comment]
@anGie44 I am currently working on this feature. I will open a PR in the next few days :)

**Comment by AMMullan** [comment]
Any update on this? Last update was in September and this would be really useful to have in place.

**Comment by pokatov** [comment]
Is there an update about this issue?
