### ISSUE TITLE
aws_elastic_beanstalk_application resource service_role should have ARN validation

### ISSUE THREAD

**Issue by liath** [hashicorp/terraform-provider-aws#17576]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/aws v3.27.0
```

### Affected Resource(s)
* aws_elastic_beanstalk_application

### Terraform Configuration Files
```hcl
resource "aws_iam_role" "app" {
  name = "app"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [{
    "Effect": "Allow",
    "Principal": {
      "Service": "elasticbeanstalk.amazonaws.com"
    },
    "Action": "sts:AssumeRole",
    "Condition": {
      "StringEquals": {
        "sts:ExternalId": "elasticbeanstalk"
      }
    }
  }]
}
EOF
}

resource "aws_elastic_beanstalk_application" "app" {
  name = "app"

  appversion_lifecycle {
    delete_source_from_s3 = false
    max_age_in_days       = 90
    max_count             = 0
    service_role          = aws_iam_role.app.id
  }
}
```

### Debug Output

https://gist.github.com/Liath/16f26a09cbf8403c3c7604a5999385a8

### Expected Behavior

An error message indicating that the `service_role` field expects an ARN. It is probably worth the overhead to validate that `service_role` is an ARN here as the error message from passing in the IAM role's name is not intuitive and cost me some time today. If I'm understanding this correctly, the patch for this is just a matter inserting `ValidateFunc: validateArn,` in the schema at `aws/resource_aws_elastic_beanstalk_application.go`.

### Actual Behavior

```
Error: InsufficientPrivilegesException: Insufficient privileges for IAM PassRole Action.
        status code: 403, request id: <guid>
```

### Steps to Reproduce

1. `terraform apply`

**Comment by C-Otto** [comment]
Thank you for this report, this saved me a lot of time (after I already wasted a lot). I provided this knowledge as a Q&A: https://stackoverflow.com/questions/66748539/how-can-i-fix-insufficient-privileges-for-iam-passrole-action-when-creating-a/66748540#66748540

**Comment by C-Otto** [comment]
Please keep this issue open.
