### ISSUE TITLE
AWS- Transfer family - FTPS server Protocol

### ISSUE THREAD

**Issue by balu3m** [hashicorp/terraform-provider-aws#17581]
hi,
we are trying to create a AWS Transfer family with protocol as "FTPS" and trying to attach a certificate ,  with terraform script - AWS. we have followed (as a reference) 
https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fregistry.terraform.io%2Fproviders%2Fhashicorp%2Faws%2Flatest%2Fdocs%2Fresources%2Ftransfer_server&amp;data=04%7C01%7CBhargav.kumar.Murala%40PACCAR.com%7C12e6e19eb92e41f278fb08d8ce84ad5a%7Ce201abf9c5a343f88e29135d4fe67e6b%7C0%7C0%7C637486416539112332%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=9w2%2FqsZk814LPOoh2lZgHWaqUSZ8Gs2x%2Fjhk8%2B%2BTz6U%3D&amp;reserved=0    and 
https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.aws.amazon.com%2Ftransfer%2Flatest%2Fuserguide%2FAPI_CreateServer.html&amp;data=04%7C01%7CBhargav.kumar.Murala%40PACCAR.com%7C12e6e19eb92e41f278fb08d8ce84ad5a%7Ce201abf9c5a343f88e29135d4fe67e6b%7C0%7C0%7C637486416539112332%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=uLzNV5CqNKSpGkD466MSOUSMqphXyLLVp8A1UxUa7FM%3D&amp;reserved=0 
and followed all the guidelines of Request Parameters and created the script every parameters is right  . but we are facing the following issues 
1) An argument named "protocols" is not expected here.
2) An argument named "certificate" is not expected here.
3) An argument named "security_group_ids" is not expected here.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by ewbankkit** [comment]
@balu3m Thanks for raising this issue.
It has already been noticed in #13016 (add support for FTP(S) protocols). I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
