### ISSUE TITLE
Support tags on additional IAM resources

### ISSUE THREAD

**Issue by tylersmith34** [hashicorp/terraform-provider-aws#17594]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
AWS now supports tags on additional IAM resources:

- Customer Managed Policies
- Instance Profiles
- OpenID Connect Providers
- SAML Providers
- Server Certificates
- Virtual MFAs

https://aws.amazon.com/about-aws/whats-new/2021/02/aws-identity-and-access-management-now-supports-tags-on-additional-resources/

### New or Affected Resource(s)

* aws_iam_instance_profile
* aws_iam_openid_connect_provider
* aws_iam_policy
* aws_iam_saml_provider
* aws_iam_server_certificate

### Potential Terraform Configuration

```hcl
resource "aws_iam_policy" "policy" {
  name        = "test_policy"
  path        = "/"
  description = "My test policy"
  tags = {
    key = "value"
  }

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "ec2:Describe*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
EOF
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2021/02/aws-identity-and-access-management-now-supports-tags-on-additional-resources/

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.37.10](https://github.com/aws/aws-sdk-go/releases/tag/v1.37.10).

**Comment by imaginarynik** [comment]
Please provide an ETA on this.

**Comment by dmurvihill** [comment]
Any chance of adding `aws_iam_group` to this list?

**Comment by ewbankkit** [comment]
@dmurvihill IAM groups do not yet support tags: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags.html.

**Comment by bflad** [comment]
The following resources received tagging support in version 3.34.0 of the Terraform AWS Provider:

* `aws_iam_instance_profile`
* `aws_iam_openid_connect_provider`
* `aws_iam_saml_provider`
* `aws_iam_server_certificate`

The `aws_iam_policy` resource support was just merged and will release next week with version 3.35.0 of the Terraform AWS Provider. 👍  Thank you to @DrFaust92 for the implementations here.
