### ISSUE TITLE
Error: if automatic_failover_enabled is true, number_cache_clusters must be greater than 1

### ISSUE THREAD

**Issue by iancward** [hashicorp/terraform-provider-aws#17605]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

- terraform 0.13.5
- aws provider 3.26.0

### Affected Resource(s)

* aws_elasticache_replication_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_elasticache_replication_group" "redis" {
  port                 = "6379
  replication_group_id = "${local.environment}-${var.prefix}"
  replication_group_description = "Terraform managed replication group ${local.environment}-${local.project}"
  node_type                  = "cache.r3.large"
  automatic_failover_enabled = true
  engine_version             = "5.0.6"
  ...

  cluster_mode {
    replicas_per_node_group = 0
    num_node_groups         = 1
  }
}

```

### Expected Behavior

Terraform plan and apply would succeed.

### Actual Behavior

`Error: if automatic_failover_enabled is true, number_cache_clusters must be greater than 1`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Terraform apply succeeds with aws provider < 3.26.0 (that is, AWS doesn't complain), so it would seem the validation that terraform attempts to do here is invalid.

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/17376#issuecomment-771174117

**Comment by DoctorPolski** [comment]
Please also see m y comment here: https://github.com/hashicorp/terraform-provider-aws/issues/17376#issuecomment-779775674

**Comment by frsh-augustin** [comment]
I run into the same issue, any one can look into it?

**Comment by gdavison** [comment]
Hello,

When `automatic_failover_enabled` is `true`, there need to be at least two nodes in the cluster. Otherwise, there would be nowhere to failover to.

This can be configured either by setting `number_cache_clusters` to a number 2 or higher, or using `cluster_mode` and setting `replicas_per_node_group` to 1 or higher.

If setting these values does not fix the problem, please open a new issue and include the debug logs.
