### ISSUE TITLE
aws_ses_reciept_rule validation isn't accurate, causing plan/apply failures for things AWS would be fine with

### ISSUE THREAD

**Issue by joshsleeper** [hashicorp/terraform-provider-aws#17602]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v0.12.26
+ provider.aws v3.28.0
```

### Affected Resource(s)

* `aws_ses_receipt_rule`

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ses_receipt_rule" "example" {
  name = "my.custom.domain"

  # snipped rest of config, since the regex error applies
  # to any properly configured resource of this type
}
```

### Expected Behavior

it should `plan` without issue

### Actual Behavior

```
Error: invalid value for name (must contain only alphanumeric, underscore, and hyphen characters)

  on ses.tf line 2, in resource "aws_ses_receipt_rule" "example":
 137:   name = "my.custom.domain"
```

### Steps to Reproduce

1. `terraform plan`

### References

- #13960
    - the non-exhaustive regex was added in this PR, specifically the line linked below:
    - https://github.com/hashicorp/terraform-provider-aws/pull/13960/files#diff-22e529e720e3c2f669137855c123b95e70b6829e6ddad3b16cbd7aa0c4cef006R40
- screencapture from the AWS console, showing that `.` (period) characters are allowed
    - ![image](https://user-images.githubusercontent.com/849941/107814029-400ea180-6d3f-11eb-9ff4-45d4a68c8bbc.png)

**Comment by joshsleeper** [comment]
pretty sure it's just a matter of changing the linked regex from:

```
^[0-9a-zA-Z_-]+$
```

to

```
^[0-9a-zA-Z._-]+$
```

**Comment by anGie44** [comment]
HI @joshsleeper, thank you for raising this issue and apologies for new new behavior! you're definitely correct, the regex should account for `.` as Step 6.a. in the [aws dev guide](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/receiving-email-receipt-rules.html) mentions the `name` can include `.` chars.

**Comment by joshsleeper** [comment]
you're very welcome, thanks for helping maintain an infinitely useful `terraform` provider! 😆 
probably worth double-checking the other regexes added in that same PR, just in case anything else slipped through.

**Comment by DrFaust92** [comment]
My bad, i went by https://docs.aws.amazon.com/ses/latest/APIReference/API_ReceiptRule.html and it doesnt cover `.`. ill open a PR to fix this unless @joshsleeper is willing to try.

**Comment by joshsleeper** [comment]
well hell, hard to blame you for the mistake when the docs lie! 😆
lemme see if I can open a PR real quick to fix just that one~
