### ISSUE TITLE
How to setup tag_specifications for launch template resource

### ISSUE THREAD

**Issue by tkumark** [hashicorp/terraform-provider-aws#17609]
base on the documentation example given below I see the tag set for instance type. But If I want the same tag to be applied to multiple resources then how would I set it up 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template

```
  tag_specifications {
    resource_type = "instance"

    tags = {
      Name = "test"
    }
  }
```

![image](https://user-images.githubusercontent.com/2689801/107866831-e4f1c180-6e9a-11eb-9c30-d7787966786f.png)

**Comment by DrFaust92** [comment]
A documentation example can be added but for this specific issue:

```
  tag_specifications {
    resource_type = "instance"

    tags = {
      Name = "test"
    }
  }

  tag_specifications {
    resource_type = "volume"

    tags = {
      Name = "test"
    }
  }
```

can achieve this. to make this more DRY you can use https://www.terraform.io/docs/language/expressions/dynamic-blocks.html

**Comment by ChaitanyaChandra** [comment]
* use the below example.
```
locals {
  tags_dest = ["instance", "volume", "elastic-gpu", "network-interface", "spot-instances-request"]
}

  dynamic "tag_specifications" {
    for_each = toset(local.tags_dest)
    content {
      resource_type = tag_specifications.key
      tags = {
          ENV = "dev"
           }
       }
    }
````

**Comment by mafeko** [comment]
Be aware that aws will not be able to start a new instance (in the Autoscaling Group) if you specify a `resource_type` which you don't launch.
```
Launching a new EC2 instance. Status Reason: You cannot specify tags for elastic GPUs if there are no elastic GPUs being created by the request. Launching EC2 instance failed.
```

**Comment by iaroslav-nakonechnikov** [comment]
@mafeko this is strange.

if default tags are set on provider level, i expect that all resources will be tagged.... but i see why it don't happen.
