### ISSUE TITLE
EKS support for authentication using identity providers

### ISSUE THREAD

**Issue by dvulpe** [hashicorp/terraform-provider-aws#17607]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

EKS now supports OIDC identity providers as a mechanism of Kubernetes API authentication. This is really great news as it makes kubectl access and end user experience similar to the self managed clusters using the identity provider of choice instead of requiring IAM credentials. 

The annoucement is [here](https://github.com/aws/containers-roadmap/issues/166#issuecomment-778519901) and AWS have introduced three new API calls:
* [AssociateIdentityProviderConfig](https://docs.aws.amazon.com/eks/latest/APIReference/API_AssociateIdentityProviderConfig.html)
* [DescribeIdentityProviderConfig](https://docs.aws.amazon.com/eks/latest/APIReference/API_DescribeIdentityProviderConfig.html)
* [DisassociateIdentityProviderConfig](https://docs.aws.amazon.com/eks/latest/APIReference/API_DisassociateIdentityProviderConfig.html)

### New or Affected Resource(s)

* aws_eks_identity_provider_config

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

resource "aws_eks_identity_provider_config" "config" {
    oidc {
        client_id = ""
        groups_claim = ""
        groups_prefix = ""
        identity_provider_config_name = ""
        issuer_url = ""
        required_claims = {
            "key" = "value"
        }  
       username_claim = ""
       username_prefix = ""
    }
   tags = {
   }
}
```

### References

* [Launch blog](https://aws.amazon.com/about-aws/whats-new/2021/02/amazon-eks-clusters-support-user-authentication-oidc-compatible-identity-providers/)

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.37.10](https://github.com/aws/aws-sdk-go/releases/tag/v1.37.10):

* #17616

**Comment by willvrny** [comment]
I'm happy to attempt adding this as a new resource.
