### ISSUE TITLE
Optional attributes are required for aws_route_table

### ISSUE THREAD

**Issue by chrischen** [hashicorp/terraform-provider-aws#17618]
**Community Note**

Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

I copied most of this from this previous issue report:https://github.com/hashicorp/terraform-provider-aws/issues/13854. Was fixed but I seem to have this with the most recent terraform provider version too.

**Terraform Version**

$ terraform -v
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/aws v3.28.0

**Affected Resource(s)**

aws_route_table
Terraform Configuration Files

```
resource "aws_route_table" "hmviart" {
  count = var.use_aws

  vpc_id = aws_vpc.hmviart[0].id

  route = [
    {
      cidr_block                = "0.0.0.0/0"
      egress_only_gateway_id    = ""
      gateway_id                = aws_internet_gateway.hmviart[0].id
      instance_id               = ""
      #ipv6_cidr_block           = ""
      nat_gateway_id            = ""
      network_interface_id      = ""
      transit_gateway_id        = ""
      vpc_peering_connection_id = ""
    },
  ]
}
```

**Debug Output**

With the 'ipv6_cidr_block' commented out...

```
Inappropriate value for attribute "route": element 0: attribute
"ipv6_cidr_block" is required.
```

**Expected Behavior**

The ipv6_cidr_block attribute should be Optional as per docs...

https://www.terraform.io/docs/providers/aws/r/route_table.html#ipv6_cidr_block

**Actual Behavior**

Attribute (as well as other optional attributes) are not actually optional and must be set to empty values.

**Steps to Reproduce**

terraform apply

**Comment by ewbankkit** [comment]
@chrischen Thanks for raising this issue.
Although the `route` attribute accepts the syntax you have in your configuration, an artefact of the attribute being processed in [attribute-as-blocks mode](https://www.terraform.io/docs/configuration/attr-as-blocks.html), the preferred syntax is to use standard repeated block syntax for this attribute as shown in the [example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route_table#example-usage).

Modifying your configuration to

```hcl
resource "aws_route_table" "hmviart" {
  count = var.use_aws

  vpc_id = aws_vpc.hmviart[0].id

  route {
    cidr_block                = "0.0.0.0/0"
    egress_only_gateway_id    = ""
    gateway_id                = aws_internet_gateway.hmviart[0].id
    instance_id               = ""
    #ipv6_cidr_block           = ""
    nat_gateway_id            = ""
    network_interface_id      = ""
    transit_gateway_id        = ""
    vpc_peering_connection_id = ""
  }
}
```

should resolve your problem.
