### ISSUE TITLE
Implement application based session stickiness for ALB

### ISSUE THREAD

**Issue by rafaljanicki** [hashicorp/terraform-provider-aws#17617]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

On Feb 5th, AWS has introduced application based session cookies for ALB (target groups). It'd be great to have this in Terraform as well. Documentation:

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/sticky-sessions.html#application-based-stickiness

### New or Affected Resource(s)

* aws_lb_target_group

### Potential Terraform Configuration

```hcl
resource "aws_alb_target_group" "target_group" {
  name = "tg-name"
  port = 80
  protocol = "HTTP"
  vpc_id = var.vpc_id
  target_type = "instance"

  stickiness {
    type = "app_cookie"
    enabled = true

    app_cookie {
      cookie_name = "Cookie"
      duration_seconds = 86400
    }
  }

  tags = local.common_tags
}
```

**Comment by kclinden** [comment]
also need this!

**Comment by adrian202** [comment]
I need this too!

**Comment by ttalla14** [comment]
I am looking for the same feature!
