### ISSUE TITLE
support for NLB target group client_ip_preservation_enabled

### ISSUE THREAD

**Issue by muthu-vgh** [hashicorp/terraform-provider-aws#17622]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by muthu-vgh** [comment]
does seem to have a cli support yet, but I can enable it via the console
<img width="1367" alt="Screen Shot 2021-02-15 at 11 43 15 AM" src="https://user-images.githubusercontent.com/40494743/107963658-062ddd00-6f83-11eb-9750-ca3a26338f3f.png">

**Comment by ewbankkit** [comment]
@muthu-vgh Thanks for raising this issue.
It has already been noticed in #17550. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
