### ISSUE TITLE
aws_ssm_maintenance_window_task working directory option not supported

### ISSUE THREAD

**Issue by luisamador** [hashicorp/terraform-provider-aws#17620]
The resource aws_ssm_maintenance_window_task doesn't currently support the optional configuration "working directory". Would be great to add this feature.

This is how it looks like from the AWS console:

![image](https://user-images.githubusercontent.com/18208396/107946906-f2d63e00-6f91-11eb-8a16-c35861ef5ace.png)

**Comment by luisamador** [comment]
```
parameter {
        name   = "workingDirectory"
        values = ["/opt/app/backups"]
}
```

The solution is to use the block above. Feel free to close this.

**Comment by breathingdust** [comment]
Thanks for the update @luisamador!
