### ISSUE TITLE
aws_ssm_maintenance_window_task sns notifications IAM role not supported

### ISSUE THREAD

**Issue by luisamador** [hashicorp/terraform-provider-aws#17624]
On the AWS console when I create a maintenance window task there's an option to set an IAM role that is used when triggering notifications. It would be great if this option is added so that Terraform supports it too.

![image](https://user-images.githubusercontent.com/18208396/107967233-283c5500-6fad-11eb-9082-a398eb4533b2.png)

**Comment by luisamador** [comment]
I've just realised that this is already implemented but the name of the property that controls the above is pretty confusing "service_role_arn", in my opinion should be changed to "notification_iam_role" or similar to avoid any confusions.

**Comment by DrFaust92** [comment]
Hi, the naming is according to the underlying AWS SDK. I was going to answer with `service_role_arn` under the `run_command_parameters` before i saw you already found the relevant argument. this is not to be confused with the `service_role_arn` the root level argument. As the provider tends to follow the underlying SDK for naming im going to close this.
