### ISSUE TITLE
aws_ssm_maintenance_window_task execution timeout not supported

### ISSUE THREAD

**Issue by luisamador** [hashicorp/terraform-provider-aws#17632]
**aws_ssm_maintenance_window_task**

![image](https://user-images.githubusercontent.com/18208396/108046481-f1198280-7044-11eb-9def-6fd0dedb1055.png)

This provider doesn't support the "Execution timeout" option that is available on the AWS console. Would be great to add it.

**Comment by luisamador** [comment]
you can ignore the above, I've managed to set that property by doing this:

```parameter {
        name   = "executionTimeout"
        values = ["7200"]
}```

**Comment by FearlessHyena** [comment]
I still feel it should be consistent with the `timeout_seconds` argument and be made a separate `execution_timeout_seconds` argument

**Comment by DrFaust92** [comment]
The SSM API does not directly support the `ExecutionTimeout` property and as @luisamador already stated, its support ther via the `parameter` config block.

There seems to be a difference between the Console UI and the SDK so this may just be a documentation change as no code change can be done here.
