### ISSUE TITLE
aws_s3_bucket_policy data source

### ISSUE THREAD

**Issue by michael-robbins** [hashicorp/terraform-provider-aws#17649]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Re-opening a very old request (https://github.com/hashicorp/terraform-provider-aws/issues/6977) for the S3 Bucket Policy data-source as I feel it warrants an actual discussion request.

We have a few situations where we'd like to be able to reference an existing S3 Bucket Policy to append an new Statement into it then apply that policy 'back' to the S3 bucket (using aws_iam_policy_document and source_json to perform the merge).

Currently we're just using a separate S3 Object to 'mirror' this S3 Bucket Policy and reading/writing to that object before/after the Bucket Policy application, but this is hacky and involves extra steps and increases the chances of failure!

### New or Affected Resource(s)

aws_s3_bucket_policy

### Potential Terraform Configuration

```hcl
data "aws_s3_bucket_policy" "policy" {
  arn = "arn:aws:s3:::my-bucket-name"
}

data "aws_s3_bucket_policy" "policy" {
  name = "my-bucket-name"
}
```

**Comment by ewbankkit** [comment]
Related:

* #4418
