### ISSUE TITLE
Add support for 'aws_subnet_nacl_association' resource

### ISSUE THREAD

**Issue by geofflancaster** [hashicorp/terraform-provider-aws#17648]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Cloudformation has [EC2:SubnetNetworkAclAssociation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet-network-acl-assoc.html) but there is not an equivalent resource in terraform.

### New or Affected Resource(s)

* aws_subnet_nacl_association

### Potential Terraform Configuration

```hcl
resource "aws_subnet_nacl_association" "association" {
  subnet_id = ""
  network_acl_id = ""
}
```

### References

Existing issue: https://github.com/hashicorp/terraform-provider-aws/issues/5466

Steps to implement:
[DescribeNetworkAcls](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeNetworkAcls.html) and filter by `association.subnet-id` to determine the `AssociationId`.
[ReplaceNetworkAclAssociation](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ReplaceNetworkAclAssociation.html) providing the `AssociationId` and `NetworkAclId` will reassign appropriately.

* #0000

**Comment by geofflancaster** [comment]
I've started coding this out but I do not have any Go experience. Any assistance, especially with a valid test suite would be appreciated.

https://github.com/geofflancaster/terraform-provider-aws/commit/49408fa687b7bf048dd1281a51b949b31e34aea5

**Comment by edmundcraske-bjss** [comment]
Looks like #16660, #12364, and #1034 are all related to this... Should this be closed as a duplicate?

**Comment by geofflancaster** [comment]
new MR incoming.  Closing this.
