### ISSUE TITLE
Change EBS type from gp3 to gp2

### ISSUE THREAD

**Issue by brunoxd13** [hashicorp/terraform-provider-aws#17644]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v0.13.6
provider  hashicorp/aws v3.28.0
```

### Terraform Configuration Files

```hcl
resource "aws_ebs_volume" "this" {
  availability_zone = "us-west-2a"
  size = 40
  type = "gp2"
  throughput = null
}
```

### Debug Output
`Error: InvalidParameterCombination: The throughput parameter is not supported for gp2 volumes.`

### Expected Behavior
When changing the EBS disk type from gp3 to gp2, an error related to throughput should not be reported, as it does not "exist" for the gp2 disk type.

The validation on code base is [this one ](https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_ebs_volume.go#L410)

I have seen the [code base](https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_ebs_volume.go#L183) and on this line its maintained the throughput var, but for gp2 it should not maintain.

### Actual Behavior
When I change the disk from gp3 to gp2 the change is not allowed because the disk has no throughput configuration, I cannot even pass as null or 0. 

I cannot pass this variable because of the error saying that the type gp3 has saved in the state.

### Steps to Reproduce

1. Create an ebs disc with the gp3 type;
2. Change the disc type from gp3 to gp2;

**Comment by ewbankkit** [comment]
Related:

* #16514

**Comment by ewbankkit** [comment]
I can reproduce with a new acceptance test case:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSEBSVolume_gp3_to_gp2'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSEBSVolume_gp3_to_gp2 -timeout 120m
=== RUN   TestAccAWSEBSVolume_gp3_to_gp2
=== PAUSE TestAccAWSEBSVolume_gp3_to_gp2
=== CONT  TestAccAWSEBSVolume_gp3_to_gp2
    resource_aws_ebs_volume_test.go:603: Step 3/3 error: Error running apply: exit status 1
        2021/02/16 17:50:00 [DEBUG] Using modified User-Agent: Terraform/0.12.26 HashiCorp-terraform-exec/0.13.0
        
        Error: InvalidParameterCombination: The throughput parameter is not supported for gp2 volumes.
        	status code: 400, request id: f42faf20-398b-4948-9706-dbbbffa5d155
        
        
--- FAIL: TestAccAWSEBSVolume_gp3_to_gp2 (31.83s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	31.926s
FAIL
GNUmakefile:27: recipe for target 'testacc' failed
make: *** [testacc] Error 1
```
