### ISSUE TITLE
aws_organizations_organization return only active accounts

### ISSUE THREAD

**Issue by ChristophShyper** [hashicorp/terraform-provider-aws#17656]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`aws_organizations_organization` returns active and suspended accounts in the organization.
It should have possibility to return only active accounts.
Maybe with some attribute for the data source?

### Potential Terraform Configuration

```hcl
data "aws_organizations_organization" "this" {
  type = "ACTIVE"
}
```

**Comment by ChristophShyper** [comment]
Here is my current solution for the problem: https://gist.github.com/ChristophShyper/b343567feba26e2c095d7d301a9dae5d

**Comment by brodster2** [comment]
The data source now provides the `status` attribute for `accounts` and `non_master_accounts` items.
- https://github.com/hashicorp/terraform-provider-aws/blob/c1630b35e0d18f674c60a6c72fb11bf451df64f2/aws/data_source_aws_organizations_organization.go#L29
- https://github.com/hashicorp/terraform-provider-aws/blob/c1630b35e0d18f674c60a6c72fb11bf451df64f2/aws/data_source_aws_organizations_organization.go#L89

Could this now be solved with:
```terraform
locals {
  active_accounts = [for a in data.aws_organizations_organization.org.accounts : a if a.status == "ACTIVE"]
```

**Comment by ChristophShyper** [comment]
Looks like this was already working but not mentioned in the documentation. Thanks @brodster2 for adding missing information.
