### ISSUE TITLE
ListenerCertificateParseID function returns an error for a correct ID value

### ISSUE THREAD

**Issue by mateusz-kleinert** [hashicorp/terraform-provider-aws#17669]
Hello :wave: 

I wanted to upgrade my provider from v3.23.0 to v3.28.0 to be able to import listener certificates. After the upgrade I've found out that [ListenerCertificateParseID](https://github.com/hashicorp/terraform-provider-aws/blob/8cb94555763099278654b6a554e231d00aed0130/aws/internal/service/elbv2/id.go#L10) function returns an error on my already created resources. Apparently for the Listener Certificate it expects the format of `listener-arn_certificate-arn` and assumes that non of the provided arn values contain `_` character. My certificate arn contains multiple `_` characters. I'd like to make sure this is the correct behavior of the `ListenerCertificateParseID` function as in this case I have to rename some of my resources and if AWS allows for such names I can only assume `_` character should be supported. I'd be grateful for an information if this is an issue on the provider side or I should simply rename my resources for that purpose.

**Comment by ewbankkit** [comment]
@mateusz-kleinert Thanks for raising this issue.
It has already been noticed in #17639 and fixed in #17645. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
