### ISSUE TITLE
Documentation: aws_cognito_user_pools uses arns attribute in example but doesn't list arns as valid attribute

### ISSUE THREAD

**Issue by JohnNeville** [hashicorp/terraform-provider-aws#17660]
I was looking over the documentation for the aws_cognito_user_pools data source and noticed that the example is using an undocumented attribute. 

See below:

![image](https://user-images.githubusercontent.com/11984108/108235151-926f0a00-7113-11eb-8c5e-5866a8a2826d.png)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Documentation is for v3.28.0

### Affected Resource(s)

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/cognito_user_pools

**Comment by kamilturek** [comment]
@JohnNeville The issue was solved by https://github.com/hashicorp/terraform-provider-aws/pull/20167.
