### ISSUE TITLE
 Documentation on the aws_imagebuilder_image_pipeline is not correct

### ISSUE THREAD

**Issue by gswallow** [hashicorp/terraform-provider-aws#17665]
The documentation on schedule_expressions is wrong: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/imagebuilder_image_pipeline#schedule_expression

Instead of five fields, you must supply six.  Also, one of the fields (day of month or day of week) must be a '?' if the other is set.

Source:

https://docs.aws.amazon.com/imagebuilder/latest/userguide/cron-expressions.html

**Comment by bflad** [comment]
Thank you for the heads up, @gswallow! The syntax recently changed in the Image Builder API. A documentation (and testing) update has been submitted: https://github.com/hashicorp/terraform-provider-aws/pull/17666

**Comment by gswallow** [comment]
Sweet!  Cheers!
