### ISSUE TITLE
Advanced Backup Setting Arguments backup_options is not optional 

### ISSUE THREAD

**Issue by lassebenni** [hashicorp/terraform-provider-aws#17667]
### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.7

### Affected Resource(s)

[aws_backup_plan](https://registry.terraform.io/providers/hashicorp/aws/3.28.0/docs/resources/backup_plan)

### Terraform Configuration Files

```hcl
resource "aws_backup_plan" "example" {
  name = "tf_example_backup_plan"

  rule {
    rule_name         = "tf_example_backup_rule"
    target_vault_name = aws_backup_vault.test.name
    schedule          = "cron(0 12 * * ? *)"
  }

  advanced_backup_setting {
    resource_type = "EC2"
  }
}
```

### Debug Output

```
Error: error creating Backup Plan: MissingParameterValueException: Resource Type or Backup Options is null in Advanced Backup Settings
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "1a493370-ed04-4ca7-93d3-14d58e2c8862"
  },
  Code_: "ERROR_4214",
  Message_: "Resource Type or Backup Options is null in Advanced Backup Settings"
}
```

### Expected Behavior

Creation of aws_backup_plan resource without stating the `backup_options` argument.

### Actual Behavior

`tf plan` produces the error that states that the `backup_options` argument inside `advanced_backup_setting` is required, which is unlike what is stated in the documentation:

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_plan#advanced-backup-setting-arguments

But in the latest docs of CloudFormation it states that the `BackupOptions` argument IS required: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-backup-backupplan-advancedbackupsettingresourcetype.html

### Steps to Reproduce

1. `terraform apply`

**Comment by ewbankkit** [comment]
Related:

* #15329
* #15341

**Comment by ewbankkit** [comment]
@lassebenni Thanks for raising this issue.
Indeed, the [AWS Backup API Reference](https://docs.aws.amazon.com/aws-backup/latest/devguide/API_AdvancedBackupSetting.html) states backup options are optional but I can reproduce the error you got with a modified acceptance test:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAwsBackupPlan_AdvancedBackupSetting'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsBackupPlan_AdvancedBackupSetting -timeout 120m
=== RUN   TestAccAwsBackupPlan_AdvancedBackupSetting
=== PAUSE TestAccAwsBackupPlan_AdvancedBackupSetting
=== CONT  TestAccAwsBackupPlan_AdvancedBackupSetting
    resource_aws_backup_plan_test.go:533: Step 1/3 error: Error running apply: exit status 1
        2021/02/18 17:48:26 [DEBUG] Using modified User-Agent: Terraform/0.12.26 HashiCorp-terraform-exec/0.13.0
        
        Error: error creating Backup Plan: MissingParameterValueException: Resource Type or Backup Options is null in Advanced Backup Settings
        {
          RespMetadata: {
            StatusCode: 400,
            RequestID: "aab23569-3c28-4c67-933b-8a02b320b349"
          },
          Code_: "ERROR_4214",
          Message_: "Resource Type or Backup Options is null in Advanced Backup Settings"
        }
        
        
--- FAIL: TestAccAwsBackupPlan_AdvancedBackupSetting (8.17s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	8.264s
FAIL
GNUmakefile:27: recipe for target 'testacc' failed
make: *** [testacc] Error 1
```

I'll fix the resource so that `backup_options` and `resource_type` are both `Required`.
