### ISSUE TITLE
aws_api_gateway_stage.cache_cluster_size continually shows up as out-of-date

### ISSUE THREAD

**Issue by pauldraper** [hashicorp/terraform-provider-aws#17661]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform: v0.13.2
AWS Provider: 3.37.0

### Affected Resource(s)

* aws_api_gateway_stage

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_api_gateway_stage" "hl7" {
  depends_on    = [aws_cloudwatch_log_group.execution]
  deployment_id = aws_api_gateway_deployment.hl7.id
  rest_api_id   = aws_api_gateway_rest_api.hl7.id
  stage_name    = "latest"

  access_log_settings {
    destination_arn = aws_cloudwatch_log_group.access.arn
    format          = "$context.identity.sourceIp $context.identity.caller $context.identity.user [$context.requestTime] $context.httpMethod $context.resourcePath $context.protocol $context.status $context.responseLength $context.requestId"
  }
}
```

### Expected Behavior

After successful apply, there is no diff.

### Actual Behavior

There is a diff.

```
  # module.demo-hl7.aws_api_gateway_stage.hl7 will be updated in-place
  ~ resource "aws_api_gateway_stage" "hl7" {
        arn                   = "arn:aws:apigateway:us-east-1::/restapis/hznyocj4cl/stages/latest"
        cache_cluster_enabled = false
      - cache_cluster_size    = "0.5" -> null
        deployment_id         = "lxue66"
        execution_arn         = "arn:aws:execute-api:us-east-1:853263162156:hznyocj4cl/latest"
        id                    = "ags-hznyocj4cl-latest"
        invoke_url            = "https://hznyocj4cl.execute-api.us-east-1.amazonaws.com/latest"
        rest_api_id           = "hznyocj4cl"
        stage_name            = "latest"
        tags                  = {}
        variables             = {}
        xray_tracing_enabled  = false
 
        access_log_settings {
            destination_arn = "arn:aws:logs:us-east-1:853263162156:log-group:/api-gateway/demo-hl7/access"
            format          = "$context.identity.sourceIp $context.identity.caller $context.identity.user [$context.requestTime] $context.httpMethod $context.resourcePath $context.protocol $context.status $context.responseLength $context.requestId"
        }
    }
```

### References

**Comment by bill-rich** [comment]
Hi @pauldraper! You're getting this diff because Terraform is trying to set the `cache_cluster_size` to `null`, but that does not end up getting sent to the API. As a workaround until this is addressed, you can set `cache_cluster_size` to a number and it should eliminate the diff.

**Comment by binarymist** [comment]
Not just any number

**Comment by andyt10** [comment]
I've come across this recently, as well.
It seems as though if the `cache_cluster_size ` value is set for any reason, it then can't be unset/removed.
So as @bill-rich said it can't be set to `null`.

The value `cache_cluster_size ` is not present on stage resources by default.
I've tried to remove/replace using the AWSCLI [command](https://docs.aws.amazon.com/cli/latest/reference/apigateway/update-stage.html) as well but that doesn't seem permissible.

I guess to flush it the stage resource needs to be re-created? 
This seems like an API Gateway API spec issue to me...

**Comment by andyt10** [comment]
I could probably look into fixing this, but would need some guidance on best next steps:

 The attribute is optional https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/apigateway/stage.go#L64

In my mind it would be fine to ignore diff in the value if `cache_cluster_enabled` is false but I don't know how that sort of logic is seen from a TF perspective, and is really just a hack around this API's behaviour.

More ideally AWS would allow removing the value once set 😇
