### ISSUE TITLE
Terraform aws_cloudfront_distribution can't set Use Origin Cache Headers

### ISSUE THREAD

**Issue by jshah** [hashicorp/terraform-provider-aws#17673]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/aws v3.28.0
```

### Affected Resource(s)

* aws_cloudfront_distribution

### Terraform Configuration Files

```hcl
ordered_cache_behavior {
    allowed_methods = [
      "GET",
      "HEAD",
      "OPTIONS",
    ]
    cached_methods = [
      "GET",
      "HEAD",
    ]
    path_pattern           = "/assets/*"
    target_origin_id       = "xxxxx"
    viewer_protocol_policy = "https-only"
    forwarded_values {
      query_string = false
      cookies {
        forward = "none"
      }
    }
  }
```

### Expected Behavior

Cloudfront should be created with "Use Origin Cache Headers" selected.

### Actual Behavior

Cloudfront is created with "Customize" selected and ttl values as 0.

![CleanShot 2021-02-17 at 17 04 52](https://user-images.githubusercontent.com/1421038/108289089-99f9d780-7142-11eb-8ed6-22e6a495ee59.png)

### Steps to Reproduce

Cloudfront distribution with above `ordered_cache_behavior`

1. `terraform apply`

### Important Factoids

This issue (https://github.com/hashicorp/terraform-provider-aws/issues/1994) covers the same problem and mentions it was fixed as part of AWS provider version 1.11.0 but the solution mentioning to remove all `ttl` values does not work.

### References

* #1994

**Comment by jshah** [comment]
Well... I don't know when this changed but setting the default `ttl` values now selects "Use Origin Cache Headers"

```
ordered_cache_behavior {
    allowed_methods = [
      "GET",
      "HEAD",
      "OPTIONS",
    ]
    cached_methods = [
      "GET",
      "HEAD",
    ]
    path_pattern           = "/assets/*"
    target_origin_id       = "xxxxx"
    viewer_protocol_policy = "https-only"
    forwarded_values {
      query_string = false
      cookies {
        forward = "none"
      }
    }
    min_ttl                = 0
    default_ttl            = 86400
    max_ttl                = 31536000
  }
```

**Comment by RichardBradley** [comment]
This is an extant bug -- it shouldn't be closed just because you have found a workaround.
I have hit the same issue
