### ISSUE TITLE
Step Function Invalid Logging configuration error

### ISSUE THREAD

**Issue by pradeepbhadani** [hashicorp/terraform-provider-aws#17682]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
`Terraform v0.14.5`
`hashicorp/aws v3.28.0`

### Affected Resource(s)

* aws_sfn_state_machine

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_sfn_state_machine" "sfn_state_machine" {
  name     = "my-state-machine"
  role_arn = aws_iam_role.iam_for_sfn.arn

  definition = <<EOF
{
  "Comment": "A Hello World example of the Amazon States Language using an AWS Lambda Function",
  "StartAt": "HelloWorld",
  "States": {
    "HelloWorld": {
      "Type": "Task",
      "Resource": "${aws_lambda_function.lambda.arn}",
      "End": true
    }
  }
}
EOF

  logging_configuration {
    log_destination        = aws_cloudwatch_log_group.log_group_for_sfn.arn
    include_execution_data = true
    level                  = "ERROR"
  }
}
```

### Expected Behavior
Terraform to create the AWS Step Function with Logging Configuration.

### Actual Behavior
Following error:
```
Error: InvalidLoggingConfiguration: Invalid Logging Configuration: Log Group ARN must be provided with '*' qualifier.
```

### Steps to Reproduce

1. `terraform apply`

**Comment by veluguletigdnb** [comment]
I ran into same situation, was able to execute with the below modification for log_destination. I am using Terraform 0.12.30,  aws: 3.27.0

log_destination        = "${aws_cloudwatch_log_group. log_group_for_sfn.arn}:*"

**Comment by pradeepbhadani** [comment]
@veluguletigdnb  - yes and #17683  updates the documentation.
