### ISSUE TITLE
options feature is NOT working in aws_datasync_task

### ISSUE THREAD

**Issue by yulinbao99** [hashicorp/terraform-provider-aws#17691]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by yulinbao99** [comment]
None of the following options - is working and got the POSIX permission error.

  options {
    bytes_per_second       = var.task_options_bytes_per_second
    preserve_deleted_files = var.task_options_preserve_deleted_files
    verify_mode            = var.task_options_verify_mode
    posix_permissions      = var.task_options_posix_permissions
  }

**Comment by bill-rich** [comment]
Hi @yulinbao99! In order to address your issue as quickly and thoroughly as possible, please fill out the entire bug report template. Without examples and log output, it is much more difficult to pinpoint the problem.

I'm going to close this issue, but if you're still experiencing the problem, please open a new issue with the requested information.
