### ISSUE TITLE
Generic Fetching Resources via Tags

### ISSUE THREAD

**Issue by DrFaust92** [hashicorp/terraform-provider-aws#17705]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In many cases it is easier to group resources using tags rather than keeping hard coded lists of resources by their id (which may differ in connection from service to service)

There are multiple feature requests to fetch resource by filter them through tags. A non exhaustive list of those are:

* https://github.com/hashicorp/terraform-provider-aws/issues/17701
* https://github.com/hashicorp/terraform-provider-aws/issues/12293
* https://github.com/hashicorp/terraform-provider-aws/issues/12265

Some of the service do not implement that kind of filtering on the API level which would require building some custom logic to filter that which may differ from resource to resource based on the API response. that may introduce a maintenance burden, and my break in a future release of the AWS SDK/API Change.

Having the ability to fetch a group of resources (from the same type or even for multiple types at once to make code more DRY) may be beneficial for a multitude of case. for example adding cloudwatch log group to a group of resource based on their id instead of iterating a few separate data sources.

AWS has a single generic API to fetch multiple resource types (or single by filter) and filter them by tags. This will make Terraform config more DRY and will reduce amount of API calls (which in turn reduce various throttling and wait issues).

The way to do it is use the [Resource Groups Tagging API](https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/API_GetResources.html)

### New or Affected Resource(s)

* aws_resource_groups_tagging 

### Potential Terraform Configuration

```hcl
data "aws_ aws_resourcegroupstagging_resources" "filter" {
  resource_type_filters = ["elbv2:loadbalancer"]

  tag_filters {
    key = "tag_key_1"
  }

  tag_filters {
    key = "tag_key_2"
    values = ["tag_value_1", "tag_value_2"]
  }
}

data "aws_alb" "alb_test_with_arn" {
  for_each = data.aws_resource_groups_tagging.filter.resource_tag_mapping_list

  arn = each.resource_arn
}
```

**Comment by bflad** [comment]
I personally think this is a good solution to offer since the API support already exists. My only suggestion would be to name it `aws_resourcegroupstagging_resources` to match our naming standards a little better ("api" and "service" in the service naming we generally have smoothed over) 👍 .
