### ISSUE TITLE
Make the Makefile Make our Lives Better

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#17709]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Cheeky title aside, various folks have made suggestions to improve our `GNUmakefile` consistency and ensure it continues to be developer friendly.

Some overarching goals of the Makefile should be:

- Easily allowing contributors to install Go-based tooling
- Easily allowing contributors to run all pull request checks
- Easily allowing contributors to run individual tool checks
- Easily allowing contributors to run automatic fixes where possible
- Easily allowing contributors to run code generation and maintainers to verify it is up to date
- Having GitHub Actions workflows use the Makefile targets for consistency where possible

Things that cannot change:

- The `fmtcheck` target must exist until the release process is migrated into this repository.

Things that probably should not change:

- Using Make as it is conventional across many Terraform Providers
- The `build`, `sweep`, `test`, and `testacc` targets are conventional across many Terraform Providers
- The `tools` target covers installing tooling already and is fairly conventional

### Current Makefile Targets

- awsproviderlint: `awsproviderlint`
- build: fmtcheck, `go install`
- depscheck: `go mod tidy`, `git diff`
- docscheck: `tfproviderdocs check` (not enhanced checks), `misspell` (changelog files)
- docs-lint: `misspell` (docs), `markdownlint` (docs)
- docs-lint-fix: `misspell` (docs), `markdownlint` (docs)
- fmt: `gofmt`
- fmtcheck: `scripts/gofmtcheck.sh`
- gen: `go generate`
- gencheck: gen, `git diff`
- generate-changelog: `scripts/generate-changelog.sh`
- golangci-lint: `golangci-lint`
- importlint: `impi`
- lint: awsproviderlint, golangci-lint, importlint
- sweep: `go test -sweep`
- test: fmtcheck, `go test`
- testacc: fmtcheck, `TF_ACC=1 go test`
- tools: `go install`
- test-compile: `go test -c`
- website-link-check: `markdown-link-check`
- website-lint: `misspell` (website), `markdownlint` (website), `terrafmt` (website)
- website-lint-fix: `misspell` (website), `markdownlint` (website), `terrafmt` (website)

**Comment by ewbankkit** [comment]
Can you point to some examples?

**Comment by bflad** [comment]
@ewbankkit they are not public unfortunately, but I have pointed folks that have made suggestions to comment here.

In general though, the problems we likely should address are:

- Covering "Easily allowing contributors to run all pull request checks" whether it be by creating a `all` or `pr` target or updating the default target
- Covering "Having GitHub Actions workflows use the Makefile targets for consistency where possible"
- Updating for target naming consistency and documenting the standard in the Makefile itself

**Comment by anGie44** [comment]
Related https://github.com/hashicorp/terraform-provider-aws/issues/17603 
Not necessarily the Makefile itself but the documentation we have around the dev env `Requirements` to use our Makefile could be more explicit
