### ISSUE TITLE
Error setting Instance Profile on Instance when ARN contains multiple / in v3.29.0

### ISSUE THREAD

**Issue by dgrizzanti** [hashicorp/terraform-provider-aws#17719]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

v3.29.0 for AWS Provider
v0.14.5 for Terraform

### Affected Resource(s)

aws_instance

### Terraform Configuration Files

```hcl
resource "aws_instance" "instance_metrics" {
  ami                         = var.ami_id
  instance_type               = var.instance_type
  iam_instance_profile        = var.instance_profile
  subnet_id                   = var.subnet_id
  vpc_security_group_ids      = concat([var.base_security_group], var.extra_sg_ids)
  user_data                   = data.template_file.user_data.rendered
  associate_public_ip_address = local.vpc_type_toggle.associate_public_ip

  root_block_device {
    volume_type           = var.root_vol_type
    volume_size           = var.root_vol_size
    delete_on_termination = var.vol_delete_on_termination
  }

  lifecycle {
    ignore_changes = [volume_tags]
  }
}
```

### Expected Behavior

Creates instance with desired instance profile passed in by `var.instance_profile`

### Actual Behavior

Terraform apply fails with the following error:

```
Error: error setting iam_instance_profile: expected 2 resource parts in ARN (arn:aws:iam::xxx:instance-profile/yyy/zzz), got: 3
```

Where `zzz` was the name passed in via `var.instance_profile`

### Steps to Reproduce

1. `terraform apply` with an instance profile name that has an ARN with multiple `/` after `instance-profile`

### References

Poking around, I think this new function may be the culprit?

https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/internal/service/iam/arn.go

I was able to reproduce the behavior pulling out that function, passing it an ARN that is formatted as above to re-create the same response.

**Comment by anGie44** [comment]
Relates to changes in https://github.com/hashicorp/terraform-provider-aws/pull/17414
