### ISSUE TITLE
Empty strings are removed from aws_iam_policy_document condition statements

### ISSUE THREAD

**Issue by orf** [hashicorp/terraform-provider-aws#17711]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Provider 3.28.0, terraform 0.13.5

**this issue is not present in provider version 3.25.0**

### Affected Resource(s)

* aws_iam_policy_document

### Terraform Configuration Files

```hcl
variable "bucket_arn" {}

data "aws_iam_policy_document" "test" {
  statement {
    actions = [
      "s3:ListBucket",
      "s3:ListBucketVersions"
    ]
    resources = [
      var.some_bucket_arn
    ]
    condition {
      test = "StringLike"
      values = [
        "*/????????-????-????-????-????????????/*",
        ""
      ]
      variable = "s3:prefix"
    }
    effect = "Allow"
  }
}

resource "aws_iam_policy" "service_media_bucket_write" {
  policy = data.aws_iam_policy_document.aws_iam_policy_document.json
}
```

### Expected Behavior

The policy should be created with an empty "" as a condition

### Actual Behavior

The empty string is removed in the plan

```
                      ~ Condition = {
                          ~ StringLike = {
                              ~ s3:prefix = [
                                    "*/????????-????-????-????-????????????/*",
                                  - "",
                                ]
                            }
                        }
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This worked in 3.25.0. It is also a valid policy, the `""` matches only the root of the bucket and this policy is an example one that AWS shows. For example: https://aws.amazon.com/premiumsupport/knowledge-center/iam-s3-user-specific-folder/

### References

* #0000

**Comment by orf** [comment]
I would guess this is related to https://github.com/hashicorp/terraform-provider-aws/pull/17556/ (cc @YakDriver)

**Comment by orf** [comment]
Yeah, `expandStringList` skips empty strings: https://github.com/hashicorp/terraform-provider-aws/blob/4425957ef58f94061f92a45e694ff6ddb56cfe3b/aws/structure.go#L979

**Comment by ewbankkit** [comment]
Similar:

* https://github.com/hashicorp/terraform-provider-aws/issues/17623

**Comment by YakDriver** [comment]
The problem with #17556 is, as @orf says, that `expandStringList()` removes empty strings. However, the problem with `iamPolicyDecodeConfigStringList()`, used previously, is that it does not preserve order. The solution involves 1. preserving order, and 2. preserving empty strings.
