### ISSUE TITLE
Make MSK Cluster create timeouts configurable

### ISSUE THREAD

**Issue by Stratouklos** [hashicorp/terraform-provider-aws#17726]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

New AWS MSK Clusters can routinely take close to 60 minutes or more to be created. This causes timeouts and in subsequent runs the resource shows as `tainted` requiring manual untainting.

### New or Affected Resource(s)

* aws_msk_cluster

### Potential Terraform Configuration

```hcl
resource "aws_msk_cluster" "kafka" {
  cluster_name           = local.service
  kafka_version          = var.kafka_version
  number_of_broker_nodes = var.number_of_broker_nodes

  broker_node_group_info {
    instance_type   = var.instance_type
    ebs_volume_size = var.ebs_volume_size
    client_subnets  = flatten([for s in data.aws_subnet_ids.private : s.ids])
    security_groups = [aws_security_group.kafka.id]
  }

  configuration_info {
    arn      = aws_msk_configuration.kafka.arn
    revision = aws_msk_configuration.kafka.latest_revision
  }

  encryption_info {
    encryption_at_rest_kms_key_arn = aws_kms_key.kafka_key.arn

    encryption_in_transit {
      client_broker = "TLS"
      in_cluster    = true
    }
  }

  client_authentication {
    sasl {
      scram = true
    }
  }

  open_monitoring {
    prometheus {
      jmx_exporter {
        enabled_in_broker = true
      }
      node_exporter {
        enabled_in_broker = true
      }
    }
  }

  logging_info {
    broker_logs {
      cloudwatch_logs {
        enabled   = true
        log_group = aws_cloudwatch_log_group.broker_logs.name
      }
    }
  }

  timeouts {
    create = "2h" # As of Feb 2021 MSK clusters can take 1h or more to be created 
  }
}
```

### References

* NA

**Comment by ewbankkit** [comment]
For creation (1h):

https://github.com/hashicorp/terraform-provider-aws/blob/27f1e21c87c2324beb23fe445126ce51d0077d08/aws/resource_aws_msk_cluster.go#L393-L397

but for other cluster operations (2h):

https://github.com/hashicorp/terraform-provider-aws/blob/27f1e21c87c2324beb23fe445126ce51d0077d08/aws/resource_aws_msk_cluster.go#L1196-L1202

**Comment by mgusiew-guide** [comment]
FTR there is another issue describing this problem: https://github.com/hashicorp/terraform-provider-aws/issues/11736
