### ISSUE TITLE
Unable to use terraform-aws-modules/rds/aws with latest v3.29.0 - potential misinterpretation of blank string?

### ISSUE THREAD

**Issue by jamesokingston** [hashicorp/terraform-provider-aws#17720]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
terraform -v
Terraform v0.13.6
```

### Affected Resource(s)

* aws_db_instance 
* via https://registry.terraform.io/modules/terraform-aws-modules/rds/aws/latest

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
module "this" {
  source  = "terraform-aws-modules/rds/aws"
  version = "2.20.0"

  identifier = "${var.component_prefix}-rds-${var.db_name}"

  engine             = local.db_type[var.db_type]["engine"]
  engine_version     = local.db_type[var.db_type]["engine_version"]
  instance_class     = var.db_config["instance_class"]
  allocated_storage  = var.db_config["allocated_storage"]
  storage_encrypted  = true
  maintenance_window = local.db_type[var.db_type]["maintenance_window"]
  backup_window      = local.db_type[var.db_type]["backup_window"]

  multi_az = var.db_config["multi_az"]

  username = local.username

  password = var.password

  port = var.db_config["port"]

  iam_database_authentication_enabled = var.db_config["iam_database_authentication_enabled"]

  vpc_security_group_ids = [aws_security_group.this.id]

  enabled_cloudwatch_logs_exports = var.db_config["enabled_cloudwatch_logs_exports"]

  subnet_ids = var.subnet_ids

  family = local.db_type[var.db_type]["family"]

  major_engine_version = local.db_type[var.db_type]["major_engine_version"]

  final_snapshot_identifier = "${var.component_prefix}-rds-${var.db_name}"

  deletion_protection = var.db_config["deletion_protection"]

  auto_minor_version_upgrade = var.db_config["auto_minor_version_upgrade"]

  parameters = concat(local.db_type[var.db_type]["parameters"], var.extra_parameters)

  tags = var.tags

}

```

### Expected Behavior

My plan should go through successfully and show creation of an RDS

### Actual Behavior

In the `terraform-aws-modules/rds/aws` module, the variable `var.snapshot_identifier` defaults to `""`. But the error output below would suggest that it is being interpreted incorrectly.

```
Error: ConflictsWith

  on .terraform/modules/rds_db.this/modules/db_instance/main.tf line 63, in resource "aws_db_instance" "this":
  63:   snapshot_identifier = var.snapshot_identifier

"snapshot_identifier": conflicts with username
```

### Steps to Reproduce

Run a terraform plan with `terraform-aws-modules/rds/aws` resource as above.

### Important Factoids

My module that calls the module above has not changed.  I ran it earlier today with success, but came back to it about an hour ago and its now failing with the error.

I do not set, or pass in the `snapshot_identifier` variable as I have no requirement for it.

I downgraded my aws provider, forced it to 

`"3.28.0"`

and the problem goes away.

### References

* #0000

**Comment by ewbankkit** [comment]
@jamesokingston Thanks for raising this issue.
It has already been noticed in #17712. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by jamesokingston** [comment]
> @jamesokingston Thanks for raising this issue.
> It has already been noticed in #17712. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
> Please add any additional comments there.

Sure - I just noticed the same below.  Thanks.
