### ISSUE TITLE
The RDS instances created from Snapshots cannot be updated anymore

### ISSUE THREAD

**Issue by konstl000** [hashicorp/terraform-provider-aws#17722]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.29.0
```

### Affected Resource(s)

* aws_db_instance

### Terraform Configuration Files

```hcl
resource "aws_db_instance" "db" {
  allocated_storage       = 100
  storage_type            = "gp2"
  engine                  = "postgres"
  engine_version          = "11.5"
  instance_class          = "db.t3.micro"
  vpc_security_group_ids  = ["sg-EXISTING_SG"]
  db_subnet_group_name    = aws_db_subnet_group.db_sg.name
  parameter_group_name    = "default.postgres11"
  deletion_protection     = false
  skip_final_snapshot     = true
  snapshot_identifier     = "EXISTING_SNAPSHOT"
  tags                    = {
    "foo" = "bar"
  }
  identifier              = "bugcatcher"
  maintenance_window      = "Sun:00:00-Sun:08:00"
}
resource "aws_db_subnet_group" "db_sg" {
  name                    = "bugcatcher"
  subnet_ids              = ["EXISTING_SUBNETS"]
  tags                    = {
    "foo" = "bar"
  }
}

```

### Debug Output

https://gist.github.com/konstl000/3261f63f77c4c3587b6872282ede667b
### Expected Behavior

On the first run, terraform successfully creates a DB instance from the snapshot provided. After this, terraform plan should return the "Infrastructure is up to date" message.

### Actual Behavior
On the first run, terraform successfully creates a DB instance from the snapshot provided. After this, terraform plan exits with a following error message:
```
Error: 1 error occurred:
        * name attribute is not supported with snapshot_identifier when engine is postgres



  on bug.tf line 1, in resource "aws_db_instance" "db":
   1: resource "aws_db_instance" "db" {
```

### Steps to Reproduce

1. `terraform apply`

2. `terraform plan -out plan`

### References

* Seems to be related to https://github.com/hashicorp/terraform-provider-aws/pull/17156
* Also seems that these changes were reverted by the [last commit](https://github.com/hashicorp/terraform-provider-aws/commit/609f858240c60ab8ab9f9c78c7269bf7016bf451) in the repo.

**Comment by ewbankkit** [comment]
@konstl000 Thanks for raising this issue.
It has already been noticed in #17712. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
