### ISSUE TITLE
AWS provider tries to delete network firewall rule group first before removing its reference from firewall policy

### ISSUE THREAD

**Issue by sslavic** [hashicorp/terraform-provider-aws#17744]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform: v0.12.29
AWS provider: 3.27.0

### Affected Resource(s)

* aws_networkfirewall_rule_group and aws_networkfirewall_firewall_policy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_networkfirewall_rule_group" "allow_list" {
  name        = "allow-list"
  description = "allow domain list"
  capacity    = 1000
  type        = "STATEFUL"
  rule_group {
    rules_source {
      rules_source_list {
        generated_rules_type = "ALLOWLIST"
        target_types         = ["HTTP_HOST", "TLS_SNI"]
        targets              = []
      }
    }
  }

  tags = {
    Name = "allow-list"
  }
}

resource "aws_networkfirewall_rule_group" "default_deny_traffic" {
  name        = "default-deny-traffic"
  description = "default deny traffic"
  capacity    = 1000
  type        = "STATEFUL"
  rule_group {
    rules_source {
      stateful_rule {
        action = "DROP"
        header {
          destination      = "ANY"
          destination_port = "ANY"
          protocol         = "IP"
          direction        = "ANY"
          source_port      = "ANY"
          source           = "ANY"
        }
        rule_option {
          keyword = format("sid:1")
        }
      }
    }
  }

  tags = {
    Name = "default-deny-traffic"
  }
}

resource "aws_networkfirewall_firewall_policy" "allow_list" {
  name        = "allow-list"
  description = "allow domain list"
  firewall_policy {
    stateless_default_actions          = ["aws:forward_to_sfe"]
    stateless_fragment_default_actions = ["aws:forward_to_sfe"]
    stateful_rule_group_reference {
      resource_arn = aws_networkfirewall_rule_group.allow_list.arn
    }
    stateful_rule_group_reference {
      resource_arn = aws_networkfirewall_rule_group.default_deny_traffic.arn
    }
  }

  tags = {
    Name = "allow-list"
  }
}
```

And then in the same go try to remove `default_deny_traffic` `aws_networkfirewall_rule_group` and its reference from the policy.

### Debug Output

Terraform plan will list both changes:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
  - destroy

Terraform will perform the following actions:

  # aws_networkfirewall_firewall_policy.allow_list will be updated in-place
  ~ resource "aws_networkfirewall_firewall_policy" "allow_list" {
...
      ~ firewall_policy {
            stateless_default_actions          = [
                "aws:forward_to_sfe",
            ]
            stateless_fragment_default_actions = [
                "aws:forward_to_sfe",
            ]

            stateful_rule_group_reference {
                resource_arn = "arn:aws:network-firewall:baz"
            }
          - stateful_rule_group_reference {
              - resource_arn = "arn:aws:network-firewall:foo-bar" -> null
            }
        }
    }

  # module.form3_fps_egress.aws_networkfirewall_rule_group.default_deny_traffic will be destroyed
  - resource "aws_networkfirewall_rule_group" "default_deny_traffic" {
...
    }

Plan: 0 to add, 1 to change, 1 to destroy.
```

but it will actually try do deletion first (or only) without removing the reference, and it will hang.

### Expected Behavior

To-be-deleted network firewall rule group gets removed first from the policy, and then it gets deleted.

### Actual Behavior

Terraform AWS provider tries to delete network firewall rule group first, which hangs and timeouts since reference to the group is still in the policy.

### Steps to Reproduce

1. `terraform apply` resources defined above
2. delete the rule group and its reference from the policy
3. Try to `terraform apply` the changes

**Comment by gdavison** [comment]
Hi @sslavic, could you please include the output that you get when you try to make this change? That would help us to track it down. Also, I assume that the change you're making is to complexity remove the resource `resource "aws_networkfirewall_rule_group" "default_deny_traffic" { ... }` and to update the `aws_networkfirewall_firewall_policy` resource to the following:

```terraform
resource "aws_networkfirewall_firewall_policy" "allow_list" {
  name        = "allow-list"
  description = "allow domain list"
  firewall_policy {
    stateless_default_actions          = ["aws:forward_to_sfe"]
    stateless_fragment_default_actions = ["aws:forward_to_sfe"]
    stateful_rule_group_reference {
      resource_arn = aws_networkfirewall_rule_group.allow_list.arn
    }
  }

  tags = {
    Name = "allow-list"
  }
}
```

If not, please also include the "after" Terraform configuration.

There is a good chance that this is related to an existing issue in how Terraform models dependencies between resources. Sometimes the a dependent resource needs to be deleted or detached before the containing resource, but we currently have no way to model that relationship. See, for example, hashicorp/terraform#8099 and hashicorp/terraform#16065.

If this is the case, the easiest workaround is to use two steps to delete the rule group: first, remove it from the policy, then delete the rule group.

**Comment by sslavic** [comment]
Yes, it's related to the existing issue in how Terraform models dependencies between resources. Thanks! Closing.
