### ISSUE TITLE
Documentation for aws_kms_grant.operations is incomplete for asymmetric keys

### ISSUE THREAD

**Issue by karlpokus** [hashicorp/terraform-provider-aws#17745]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_kms_grant

The documentation at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kms_grant#operations is missing these valid operations: "GetPublicKey", "Sign", "Verify" for asymmetric keys.

````
operations - (Required, Forces new resources) A list of operations that the grant permits.
The permitted values are: Decrypt, Encrypt, GenerateDataKey, GenerateDataKeyWithoutPlaintext
ReEncryptFrom, ReEncryptTo, CreateGrant, RetireGrant, DescribeKey
````
Where does one make a pr for the docs?

**Comment by karlpokus** [comment]
hmm are those operations not supported by tf?

First run: error from aws

> Error creating KMS grant: ValidationException: Operations [Decrypt, Encrypt, GenerateDataKey] are not supported when creating a grant for an asymmetric CMK with key usage SIGN_VERIFY. Valid operations are [CreateGrant, RetireGrant, DescribeKey, GetPublicKey, Sign, Verify]

Second run: error from tf

> Error: expected operations.2 to be one of [CreateGrant Decrypt DescribeKey Encrypt GenerateDataKey GenerateDataKeyWithoutPlaintext ReEncryptFrom ReEncryptTo RetireGrant], got GetPublicKey
on iam.tf line 43, in resource "aws_kms_grant" "foo":
43:   operations        = ["CreateGrant", "RetireGrant", "DescribeKey", "GetPublicKey", "Sign", "Verify"]

**Comment by gdavison** [comment]
Hi @karlpokus, thanks for raising this. It appears that the `aws_kms_grant` resource doesn't currently support those operations, though we may be able to implement those.

Can you please provide the Terraform configurations that you're using to get those error messages? That will help us to identify the cause of the error.

According to the AWS API documentation for creating a [KMS Grant](https://docs.aws.amazon.com/kms/latest/APIReference/API_CreateGrant.html), different sets of operations are supported depending on if the KMS key is symmetric or asymmetric.

**Comment by karlpokus** [comment]
> Can you please provide the Terraform configurations that you're using to get those error messages? That will help us to identify the cause of the error.

````
$ terraform --version
Terraform v0.14.5
$ terragrunt --version
terragrunt version v0.25.4
````
main.tf
````
provider "aws" {
  region = var.aws_region
}

terraform {
  # The configuration for this backend will be filled in by Terragrunt
  backend "s3" {}

  # Provider requirements https://www.terraform.io/docs/language/providers/requirements.html
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.25.0"
    }
  }
  
  # Terraform version
  required_version = ">= 0.14.0"
}
````

The other source code has been deleted but off the top of my head

````
resource "aws_kms_key" "key" {
  key_usage                = "SIGN_VERIFY"
  customer_master_key_spec = "RSA_2048"
  policy = <redacted>
}

resource "aws_kms_grant" "grant" {
  key_id            = aws_kms_key.key.key_id
  operations        = [ "GetPublicKey", "Sign", "Verify"]
}
````
