### ISSUE TITLE
ecs_service with wait_for_steady_state should allow to configure delay and retries

### ISSUE THREAD

**Issue by lev112** [hashicorp/terraform-provider-aws#17746]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

when applying `ecs_service` with `wait_for_steady_state=true`, terraform will wait for the service to reach a steady state.
currently there is no way to set the delay and max retries to be used while waiting.
the requested feature is to support passing custom parameters for those values

the default value is 10 minutes:
the function call is here: https://github.com/hashicorp/terraform-provider-aws/blob/master/aws/resource_aws_ecs_service.go#L1201
which defines the default values here: https://github.com/aws/aws-sdk-go/blob/master/service/ecs/waiters.go#L31-L32

### New or Affected Resource(s)

* aws_ecs_service

**Comment by gdavison** [comment]
Implementation note: The resource is currently using the waiter function provided by the AWS SDK. Switching this to use a Terraform Provider SDK waiter function will allow the desired configurability

**Comment by lev112** [comment]
> Switching this to use a Terraform Provider SDK waiter function will allow the desired configurability

I think it is possible to achieve the functionality with the AWS SDK waiter as well.
just need to use the function `WaitUntilServicesInactiveWithContext`, 
and pass `WithWaiterMaxAttempts` and `WithWaiterDelay` as `ops`

**Comment by brunhil** [comment]
Yeah I was looking at that possibility as well. If I've got time in the coming days I'll see if I can take a stab at this one! Seems like a great way to add flexibility for the community!

**Comment by richardgavel** [comment]
Yeah, thought I submitted an issue on this one but now I can't find it, the fact that ecs_service only supports timeouts on delete and not create/update.

**Comment by gdavison** [comment]
This has been addressed in #25641
