### ISSUE TITLE
Access Denied on download terraform 0.14.6

### ISSUE THREAD

**Issue by BWhitfield** [hashicorp/terraform-provider-aws#17750]
navigate to https://releases.hashicorp.com/terraform/0.14.6/
click terraform_0.14.6_linux_amd64.zip (or any for that matter)
package should download.

I am currently getting a 403

**Comment by BWhitfield** [comment]
Closing as it's a duplicate of https://github.com/hashicorp/terraform/issues/27866

**Comment by jpke** [comment]
same for https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_darwin_amd64.zip
