### ISSUE TITLE
AWS provider > 3 aws_cloudwatch_metric_alarm issues 

### ISSUE THREAD

**Issue by Tech-Med7** [hashicorp/terraform-provider-aws#17767]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_cloudwatch_metric_alarm

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

resource "aws_cloudwatch_metric_alarm" should create the alarm

### Actual Behavior

the process is hung . it does not move forward . when i downgrade the provider version, it works just fine 

### Steps to Reproduce

with aws provider version > 3 try to run resource resource "aws_cloudwatch_metric_alarm" 

### References

* #0000

**Comment by breathingdust** [comment]
Hi @Tech-Med7, this works fine for us, can you post a reproduction so that the maintainers or community can help?

**Comment by Tech-Med7** [comment]
> Hi @Tech-Med7, this works fine for us, can you post a reproduction so that the maintainers or community can help?

Hi , thanks for the reply . I figured it was some Missing configurations. It is fine now .
