### ISSUE TITLE
Support for AMAZON_LINUX_2 in the aws_gamelift_build resource

### ISSUE THREAD

**Issue by judgeaxl** [hashicorp/terraform-provider-aws#17763]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`aws_gamelift_build` doesn't support the AMAZON_LINUX_2 platform, which has been in the AWS SDK since 2019. Are there any known reasons for not adding that as a valid option to the resource? If not, I'm happy to provide a PR. As far as I can tell there are no other changes needed than simply adding the enum to the resource validation logic.

### New or Affected Resource(s)

* aws_gamelift_build

**Comment by ewbankkit** [comment]
Relates:

* #14601

Changing

https://github.com/hashicorp/terraform-provider-aws/blob/bc9dff22070971c2b28751520c52bd5c9a26bc6b/aws/resource_aws_gamelift_build.go#L33-L36

to

```go
ValidateFunc: validation.StringInSlice(gamelift.OperatingSystem_Values(), false),
```

will fix this.
