### ISSUE TITLE
How aws SSO users assume roles in AWS via terraform

### ISSUE THREAD

**Issue by Anja05** [hashicorp/terraform-provider-aws#17765]
Hi all,

I have created a role on AWS account and like to assign an sso user to that role. I m facing an error that the user **sample** is not found in iam. 
```hcl
resource "aws_iam_role" "dev_role" {
  name               = "dev-role"
  assume_role_policy = data.aws_iam_policy_document.dev-role-assume-policy-data.json
  tags = merge(var.tags, {
    "bmw:version" = local.version
  })
}


data "aws_iam_policy_document" "dev-role-assume-policy-data" {
  statement {
    effect = "Allow"
    actions = ["sts:AssumeRole"]
    principals {
      identifiers = ["arn:aws:sts::111802884793:assumed-role/sso/sample@xyz.com"]
      type        = "AWS"
    }
  }
}

data "aws_iam_policy_document" "this" {
  statement {
    effect = "Allow"
    sid    = "allowUserAssumeRole"

    actions = [
      "sts:AssumeRole",
    ]

    resources = [
      aws_iam_role.teleservices_dev_role.arn
    ]
  }
}

resource "aws_iam_policy" "dev-role-assume-policy" {
  name        = "dev-role-assume-policy"
  description = "A policy that enable user to assume iam_role ${aws_iam_role.dev_role.name}"
  policy      = data.aws_iam_policy_document.this.json
}

resource "aws_iam_user_policy_attachment" "dev-role-user-attachment" {
  user       = "xyz"
  policy_arn = aws_iam_policy.dev-role-assume-policy.arn
}
```
How can i achieve this?

**Comment by gdavison** [comment]
Hi @Anja05, are you encountering an error with the Terraform AWS Provider? If so, can you please create a new issue and include the error output?

The Issues for this repository are intended for errors with the provider. If you're looking for information about using AWS SSO in general, the AWS documentation can be found at https://docs.aws.amazon.com/singlesignon/latest/userguide/what-is.html. You may also be able to get advice from the community in our forums at https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33
