### ISSUE TITLE
2 SSO profiles mixup

### ISSUE THREAD

**Issue by frederiksf** [hashicorp/terraform-provider-aws#17762]
In my configuration i registered the s3 backend in sso profile master and a second sso profile in the aws provider (were i want to deploy my stuff :)

This is my config

![Screenshot from 2021-02-23 09-27-00](https://user-images.githubusercontent.com/3944511/108818414-a1ddcf80-75b9-11eb-8b06-2ecbe5c5c389.png)
![Screenshot from 2021-02-23 09-22-48](https://user-images.githubusercontent.com/3944511/108818415-a2766600-75b9-11eb-8bf1-6b447b8fcd4c.png)

When i run terraform apply my resource are deployes in profile "master" instead of profile "acc". Looks like a bug to me.

Terraform provider 3.29.0
Terraform v0.12.24

**Comment by ewbankkit** [comment]
@frederiksf Thanks for raising this issue.
Support for AWS SSO credentials with the S3 state backed was released with Terraform [**v0.14.6**](https://github.com/hashicorp/terraform/blob/v0.14/CHANGELOG.md#0146-february-04-2021) and has not been backported to Terraform v0.12 (or v0.13).
Are you able to upgrade your Terraform version?

**Comment by breathingdust** [comment]
Closing due to lack of response.
