### ISSUE TITLE
AWS Elasticache - Global replication group is not supported for the node type

### ISSUE THREAD

**Issue by OmarSalka** [hashicorp/terraform-provider-aws#17768]
AWS Provider version = v3.29.1

Hi,

I am not able to create a Global Replication Group. I get the following error:
```
Error: error creating ElastiCache Global Replication Group: InvalidParameterValue: 
Global replication group is not supported for the node type.
status code: 400, request id: xxxxxxxxxxxxxxxxxxxxxxxxxx
```
But I am using a supported node type `cache.t3.medium` aaccording to the [documentation](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/CacheNodes.SupportedTypes.html)

Here is the configuration for the primary replication group:

```
resource "aws_elasticache_replication_group" "ae1" {
  replication_group_id          = "ae1-elasticache-test
  replication_group_description = "ae1-elasticache-test replication group"
  engine                        = "redis"
  engine_version                = "6.0.5"
  node_type                     = "cache.t3.medium"
  number_cache_clusters         = 2
  port                          = 6379
  subnet_group_name             = "subnet-group"
  security_group_ids            = [aws_security_group.redis_sg.id]
  multi_az_enabled              = true
  automatic_failover_enabled    = true
}

```

Also here's the configuration for the global replication group:

```
resource "aws_elasticache_global_replication_group" "global" {
  global_replication_group_id_suffix = "elasticache-grg-test
  primary_replication_group_id       = aws_elasticache_replication_group.ae1.id
}
```

**Comment by OmarSalka** [comment]
tried with a `cache.m4.large` node type and it's still returning the same error

**Comment by OmarSalka** [comment]
I went to the console and tried doing it manually and noticed the list of node types that are supported are different from the documentation. If you could update the [aws documentation](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/CacheNodes.SupportedTypes.html) that would be very much appreciated

![image](https://user-images.githubusercontent.com/44652775/108904608-52f95f80-75e4-11eb-975d-ebcab41b10e2.png)

**Comment by bflad** [comment]
Hi @OmarSalka 👋  This project is not maintained by AWS ([FAQ](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/FAQ.md#who-are-the-maintainers)), however, for this type of documentation update request you can click the "Feedback" link that is present on each of the AWS documentation pages. Please also note that there is a separate page that contains [Global Datastores Prerequisites and Limitations](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Redis-Global-Datastores-Getting-Started.html) and references the required node types, that maybe could be linked.

**Comment by OmarSalka** [comment]
Thanks you for sharing that link with me!
