### ISSUE TITLE
tests/ds/network_acls: Inconsistent result on Terraform 0.15.0-alpha

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#17778]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Acceptance Test

`TestAccDataSourceAwsNetworkAcls_VpcID ` produces inconsistent result after apply on Terraform v0.15.0-alpha:

```
    data_source_aws_network_acls_test.go:78: Step 1/1 error: Error running apply: exit status 1
        
        Error: Provider produced inconsistent result after apply
        
        When applying changes to aws_network_acl.acl[1], provider
        "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected
        new value: Root resource was present, but now absent.
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
        
        
        Error: Provider produced inconsistent result after apply
        
        When applying changes to aws_network_acl.acl[0], provider
        "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected
        new value: Root resource was present, but now absent.
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
        
    testing_new.go:63: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: Error deleting VPC: DependencyViolation: The vpc 'vpc-0bcf8c22c43d8e391' has dependencies and cannot be deleted.
        	status code: 400, request id: 74bd0956-3cae-4051-91c1-66b40ff25638
        
        
--- FAIL: TestAccDataSourceAwsNetworkAcls_VpcID (309.70s)
```

### Affected Resources

* resource/aws_network_acls
* data-source/aws_network_acls

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_vpc" "test" {
  cidr_block = "10.0.0.0/16"

  tags = {
    Name = "yakceptance"
  }
}

resource "aws_network_acl" "acl" {
  count = 2

  vpc_id = aws_vpc.test.id

  tags = {
    Name = "yakceptance"
  }
}

data "aws_network_acls" "test" {
  vpc_id = aws_network_acl.acl[0].vpc_id
}
```

### References

* https://github.com/hashicorp/terraform/releases/tag/v0.15.0-alpha20210210

**Comment by YakDriver** [comment]
As noted in #17776, this data source (or more likely, the underlying resource) needs fixes along these lines:

* Add `d.IsNewResource()` checks before potentially returning `d.SetId("")` on creation (see #16796)
* Mitigate the eventual consistency issues with a pattern such as [Resource Lifecycle Retries](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/retries-and-waiters.md#resource-lifecycle-retries)

**Comment by bflad** [comment]
This should be resolved as of https://github.com/hashicorp/terraform-provider-aws/pull/18388 👍
