### ISSUE TITLE
aws_db_proxy subnet_ids

### ISSUE THREAD

**Issue by tburow** [hashicorp/terraform-provider-aws#17781]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Relates #23446 

### Terraform CLI and Terraform AWS Provider Version

Terraform 14.6
- Using hashicorp/aws v3.29.1 from the shared cache directory
- Using hashicorp/null v3.1.0 from the shared cache directory
- Using hashicorp/template v2.2.0 from the shared cache directory

### Affected Resource(s)

aws_db_proxy
aws_db_proxy_default_target_group
aws_db_proxy_target

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_db_proxy" "orc_rds_proxy" {
  count                  = var.rds_proxy_feature_enabled
  idle_client_timeout    = 120
  require_tls            = false
  engine_family          = "POSTGRESQL"
  name                   = "${var.ENV}-orc-rds-proxy"
  role_arn               = aws_iam_role.rds_proxy_role[0].arn
  vpc_security_group_ids = [aws_security_group.raves-internal.id]
  vpc_subnet_ids         = sort(data.terraform_remote_state.vpc.outputs.private_app_subnet_ids)

  auth {
    auth_scheme = "SECRETS"
    iam_auth    = "DISABLED"
    secret_arn  = aws_secretsmanager_secret.orc_db_secrets[0].arn
  }

  tags = var.custom_tags
}

resource "aws_db_proxy_default_target_group" "orc_rds_proxy_settings" {
  count         = var.rds_proxy_feature_enabled
  db_proxy_name = aws_db_proxy.orc_rds_proxy[0].name

  connection_pool_config {
    connection_borrow_timeout    = 120
    max_connections_percent      = 50
    max_idle_connections_percent = 50
  }
}

resource "aws_db_proxy_target" "orc_rds_proxy_target_attachement" {
  count                 = var.rds_proxy_feature_enabled
  db_cluster_identifier = aws_rds_cluster.default.id
  db_proxy_name         = aws_db_proxy.orc_rds_proxy[0].name
  target_group_name     = aws_db_proxy_default_target_group.orc_rds_proxy_settings[0].name
}
```

### Second run Change Output
```
  # aws_db_proxy.orc_rds_proxy[0] must be replaced
-/+ resource "aws_db_proxy" "orc_rds_proxy" {
      ~ arn                    = "arn:aws:rds:us-east-1:redacted-proxy:redacted" -> (known after apply)
      - debug_logging          = false -> null
      ~ endpoint               = "solo-orc-rds-proxy.proxy-cb8v7colw9k8.us-east-1.rds.amazonaws.com" -> (known after apply)
      ~ id                     = "solo-orc-rds-proxy" -> (known after apply)
        name                   = "solo-orc-rds-proxy"
        tags                   = {
            "Contact"     = "redacted"
            "CostCenter"  = "redacted"
            "Department"  = "redacted"
            "Environment" = "redacted"
            "Project"     = "redacted"
            "RepoName"    = "redacted"
        }
      ~ vpc_subnet_ids         = [ # forces replacement
          + "subnet-07b034a04be7e8c84",
            # (5 unchanged elements hidden)
        ]
        # (5 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce

1. `terraform apply`
2.  `terraform apply`

Primary bug:
first apply works as expected, however additional applys result in an infinite change loop.
the resource is only setting 5 of 6 subnets being passed to the config via the data lookup.
subsequent runs try to add the 6th subnet - resulting in an infinite change loop

Secondary Bug:
when the proxy change gets executed - the proxy gets deleted and recreated - however the target group does not get reprocessed resulting in a loss of a downstream dependency.   only recovery is a full resource destroy, then recreate - however you are still left in an infinite change scenario due to the original issue. 

### Important Factoids

we are in us-east-1, using all 6 subnet AZs
this is executed with in the terragrunt wrapper

**Comment by joshfriend** [comment]
I was having these _exact same_ issues, so I tried creating the RDS proxy in the web UI. I am **100% sure** that all 6 of my subnets were listed when I clicked create, but afterwords, us-east-1e was missing. I tried this THREE TIMES with the same results, am I going insane? Does AWS have a bug? Maybe this isn't terraform's fault?

**Comment by silvinobarreiros** [comment]
@joshfriend we've been seeing the same behavior. Mainly around `us-east-1e`. Here's a less than great work around

```terraform
data "terraform_remote_state" "vpc" {
  backend = "s3"
  config = {
    region = var.terraform_state_aws_region
    bucket = var.terraform_state_s3_bucket
    key      = var.terraform_state_key
  }
}

data "aws_subnet" "private_persistence_subnets" {
  for_each = toset(data.terraform_remote_state.vpc.outputs.private_persistence_subnet_ids)
  id            = each.key
}

locals {
  private_persistence_subnet_ids = [
    for subnet in data.aws_subnet.private_persistence_subnets :
    subnet.id if subnet.availability_zone != "us-east-1e"
  ]
}
```

That filter is hardcoded but obviously could be parameterized

**Comment by esnewland** [comment]
It's worth noting that the first deployment of this workaround @silvinobarreiros outlines above forces the proxy to replace itself, which results in the proxy losing association with the target group resource, even when using a `depends_on` block, requiring a second deployment.  We found that after the second deployment, however, subsequent deployments did not result in the proxy destroying and recreating itself, and therefore the association with the proxy was stable.

**Comment by KyleKotowick** [comment]
I ran into this same issue and discussed it with AWS Support. @joshfriend you're not crazy, it was creating the RDS Proxy with fewer subnets than you specified.

The issue is that RDS Proxy isn't supported in all AZs. Specifically, `use1-az3` is not supported (the letter mapping of the AZ name can change between AWS accounts; for your account, it mapped to `us-east-1e`). So what AWS does, in their infinite wisdom, is instead of throwing an error saying you can't use a given subnet because it's in an unsupported AZ, it creates the proxy without saying a word, but just doesn't include that subnet.

This is a ridiculous approach on AWS's side, since it makes it impossible to fail the creation because there's no way to know in advance if a given subnet is supported or not. Therefore, I'm not sure there's even a solution possible for the Terraform AWS provider. I also haven't been able to find any documentation that states which AZs are or are not supported.

In the meantime, as @silvinobarreiros suggests, you can filter out any subnets that are in the unsupported AZ. However, I'd suggest filtering on AZ ID (`use1-az3`) instead of the AZ name (`us-east-1e`), since the AZ name can change between accounts and you might end up copy-pasting the code to a different Terraform config for a different account one day.

**Comment by zavaliy** [comment]
> 

Exactly the same issue I'm having with AWS provider v4.27.0. Regardless of region and number of subnets.


Are there any separate open issues on this secondary bug?

**Comment by sap147** [comment]
Is there any update on this?

**Comment by rquadling** [comment]
Purely as a rant, why can't we just use the same subnet group that's used by RDS? Yes. I know it can be different, but if a subnet group is good enough for the ACTUAL server doing all the REAL work, why is it not a suitable alternative for a proxy?

End of rant.
