### ISSUE TITLE
aws_lb_target_group protocol_version update should destroy/create

### ISSUE THREAD

**Issue by github-vincent-miszczak** [hashicorp/terraform-provider-aws#17797]
### Affected Resource(s)
`aws_lb_target_group`

Using `3.27.0`.

### Expected Behavior
Changing property `protocol_version` from `GRPC` to `HTTP2` should trigger a destroy/create.

### Actual Behavior
```
# aws_lb_target_group.XXX will be updated in-place
~ resource "aws_lb_target_group" "XXX" {
  ...
    ~ protocol_version                   = "GRPC" -> "HTTP2"
    ...
  }
```
TF wants to modify the resource.
When applied, no error occurs but the value is not updated, and another plan wants to apply the update again.

In my case, I did change the healthcheck endpoint at the same time, expecting the updated protocol would be used. The endpoint was changed but not the protocol, healtchcheck failed and my ASG was drained :boom: 

### Steps to Reproduce
Create a resource `aws_lb_target_group` with `protocol_version` = `GRPC` then update to `HTTP2` and notice the change is not applied.

**Comment by ewbankkit** [comment]
Relates:

* https://github.com/hashicorp/terraform-provider-aws/pull/17534

The diff is being suppressed here:

https://github.com/hashicorp/terraform-provider-aws/blob/7546a7f44d9e0c2a7420f11daba9f65b00f95655/aws/resource_aws_lb_target_group.go#L89-L97

**Comment by dizlv** [comment]
Same here: ` protocol_version                   = "HTTP2" -> "HTTP1"` and tries to update in-place, but nothing actual happens.
Provider Version: `3.37.0`.

Had to use `terraform taint` for that specific resource to force re-creation.
