### ISSUE TITLE
NcharCharacterSetName for RDS oracle aws_db_instance

### ISSUE THREAD

**Issue by balefr1** [hashicorp/terraform-provider-aws#17792]
Hi community,
I think it would be really nice to have the property for **aws_db_instance** NcharCharacterSetName  , just like character_set_name (already supported by aws_db_instance). 
As the official AWS API doc states at the bottom of this page https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.OracleCharacterSets.html
this property is supported by AWS API calls.
I'm working in a quite big enterprise project and we've been struggling with this since some Oracle EE 12 DB tables require this property set to UTF-8, rather than the default AL16UTF16.
The only option left is to manually handle the RDS creation, since neither CloudFormation supports this property for db instances.
Thanks for your attention

**Comment by ewbankkit** [comment]
@balefr1 Thanks for raising this issue.
It has already been noticed in #20413. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
