### ISSUE TITLE
Cannot plan when aws_acm_certificate validation window has expired

### ISSUE THREAD

**Issue by devonbleak** [hashicorp/terraform-provider-aws#17799]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/archive v2.1.0
+ provider registry.terraform.io/hashicorp/aws v3.29.1
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* aws_acm_certificate

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
####################################
# Website CF Distro Certs
####################################
resource "aws_acm_certificate" "nonprod_cert" {
  provider                  = aws.east
  domain_name               = "nonprod.media.somedomain.com"
  subject_alternative_names = ["www.nonprod.media.somedomain.com"]
  validation_method         = "DNS"

  lifecycle {
    create_before_destroy = true
  }

  tags = local.somedomain_tags
}
```

### Panic Output

No panic.

### Expected Behavior

Terraform should be able to plan in order to recreate the certificate

### Actual Behavior

TF tries to DescribeCertificate multiple times (can see it in the trace output) until it finally gives up with error:
```
Error: asynchronous ACM service domain validation assignment not complete, need to retry: {
  DomainName: "nonprod.media.somedomain.com",
  ValidationDomain: "nonprod.media.somedomain.com",
  ValidationMethod: "DNS",
  ValidationStatus: "PENDING_VALIDATION"
}
```
### Steps to Reproduce

1. create the certificate
2. wait 72 hours
3. `terraform plan`

`terraform refresh` is also impacted.

### Important Factoids

Culprit seems to be in `func convertValidationOptions`

### References

* #0000

**Comment by devonbleak** [comment]
FYI here's the response that was coming back from the DescribeCertificate calls:
```{
  "Certificate": {
    "CertificateArn": "arn:aws:acm:us-east-1:123456789012:certificate/some-uuid-here",
    "CreatedAt": 1613782427,
    "DomainName": "nonprod.media.somedomain.com",
    "DomainValidationOptions": [
      {
        "DomainName": "nonprod.media.somedomain.com",
        "ValidationDomain": "nonprod.media.somedomain.com",
        "ValidationMethod": "DNS",
        "ValidationStatus": "PENDING_VALIDATION"
      },
      {
        "DomainName": "www.nonprod.media.somedomain.com",
        "ValidationDomain": "www.nonprod.media.somedomain.com",
        "ValidationMethod": "DNS",
        "ValidationStatus": "FAILED"
      }
    ],
    "ExtendedKeyUsages": [],
    "FailureReason": "OTHER",
    "InUseBy": [],
    "Issuer": "Amazon",
    "KeyAlgorithm": "RSA-2048",
    "KeyUsages": [],
    "Options": {
      "CertificateTransparencyLoggingPreference": "ENABLED"
    },
    "RenewalEligibility": "INELIGIBLE",
    "SignatureAlgorithm": "SHA256WITHRSA",
    "Status": "VALIDATION_TIMED_OUT",
    "Subject": "CN=nonprod.media.somedomain.com",
    "SubjectAlternativeNames": [
      "nonprod.media.somedomain.com",
      "www.nonprod.media.somedomain.com"
    ],
    "Type": "AMAZON_ISSUED"
  }
}```

**Comment by bflad** [comment]
Thank you for raising this, @devonbleak, I have submitted a fix for this here: https://github.com/hashicorp/terraform-provider-aws/pull/17869
