### ISSUE TITLE
timeouts block not working in 0.12.24

### ISSUE THREAD

**Issue by edwardpr23** [hashicorp/terraform-provider-aws#17800]
resource "aws_ec2_client_vpn_network_association" "vpn_network_association" {
  count                  = length(var.subnet_ids)
  client_vpn_endpoint_id = aws_ec2_client_vpn_endpoint.client_vpn_endpoint.id
 ....
 
  timeouts {
    create = "60m"
    delete = "60m"
  }
}

I get this error:

Error: Unsupported block type

  on .terraform/modules/cvpn/okta_vpn_module/main.tf line 35, in resource "aws_ec2_client_vpn_network_association" "vpn_network_association":
  35:   timeouts {

Blocks of type "timeouts" are not expected here.

I thought timeouts are supported in Terraform resource. I'm using 0.12.24.. When I try to create the Client VPN Endpoint with multiple associations and routes, ,it simply times out and fails in Apply stage in Terraform though the actual resource gets created in AWS. But since Terraform  apply stage fails, I presume the state file will not be in sync with the resource created.. This is so frustrating.. 
Any help in this matter will be really appreciated..

**Comment by ewbankkit** [comment]
@edwardpr23 Thanks for raising this issue.
The `aws_ec2_client_vpn_network_association` resource does not currently support custom timeouts.
I'll change this issue to a an enhancement request.

Related:

* #16890
* #16645

**Comment by lukeyeager** [comment]
@edwardpr23 try adding a `depends_on` from your route to your association: https://github.com/hashicorp/terraform-provider-aws/issues/16645#issuecomment-777668198. No more timeout issues for me.

**Comment by edwardpr23** [comment]
Thanks for. the tips. But somehow when I tried the second time, it worked..
