### ISSUE TITLE
Documentation: Prefer "terraform" to "hcl" in Markdown code fences

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#17810]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Based on [comments in the VS Code Terraform extension repo](https://github.com/hashicorp/vscode-terraform/pull/225#issuecomment-650265457), the language label on Markdown fenced code blocks should be `terraform` instead of `hcl`, because

> [We should not] keep treating generic HCL the same as Terraform, because they are not the same.

Version 1.x of the VS Code Terraform extension supported syntax highlighting of Terraform code in `terraform` code blocks, and not `hcl`. This has been removed from 2.x, though there is an [open issue](https://github.com/hashicorp/vscode-terraform/issues/403) to restore the functionality.

### Definition of Done

* [Custom `markdownlint` rule](https://github.com/DavidAnson/markdownlint/blob/main/doc/CustomRules.md) created
* Reports via custom rule are addressed
* CI testing passes with rule enabled

**Comment by bflad** [comment]
Related:

* https://github.com/bflad/tfproviderdocs/issues/21
* https://github.com/hashicorp/terraform-provider-aws/issues/15842

Although it currently accepts both `hcl` and `terraform`, which can be adjusted.

**Comment by bflad** [comment]
These were converted across the board and this is now enforced in CI via `tfproviderdocs` contents checking. 👍
