### ISSUE TITLE
Cloud9 Resource with "type=ssh"

### ISSUE THREAD

**Issue by alexandrud** [hashicorp/terraform-provider-aws#17818]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A new resource type for cloud9, e.g. "aws_cloud9_environment_ssh".
One flow using a EC2 instance would be:
- create EC2 resource
- create EIP
- attach EIP to EC2 resource
- get cloud9 IP ranges from datasource
- create access SSH access rule to permit cloud9 IPs
- create cloud9 environment and attach to EIP above

This would enable users to have a host that preserves it's IP and connect to it via SSH or Cloud9 interchangeably.
An output with the public key would probably help.

### New or Affected Resource(s)

* aws_cloud9_environment_ssh

### Potential Terraform Configuration

```hcl
resource "aws_cloud9_environment_ssh" "this" {
  instance_ip  = var.instance_ip
  name           = var.name
  description  = "[TF] DevOps Jumper for ${var.tags["Environment"]} environment"
  tags             = var.tags
}
```

**Comment by DrFaust92** [comment]
Im assuming you are trying to implement some bastion but there is not API for "cloud9_environment_ssh" explicitly. there is an option to create a "aws_cloud9_environment" with type SSH so im closing this. if there is a more specific request or issues please open a new issue with relevant details.
