### ISSUE TITLE
Can’t assign a secondary elasticache replication group to a global elasticache replication group

### ISSUE THREAD

**Issue by OmarSalka** [hashicorp/terraform-provider-aws#17812]
Hi,

I couldn’t find a way to assign a secondary replication group to a global replication group. There isn’t an attribute for global_replication_group_id that I can provide to the replication group. However, the CLI has this attribute which can be used to attach a secondary replication group to a global one. Am I missing something?

**Comment by bflad** [comment]
It appears this may be covered by https://github.com/hashicorp/terraform-provider-aws/pull/17725
