### ISSUE TITLE
Support s3 Replication Time Control and Replication metrics and notifications

### ISSUE THREAD

**Issue by isaacgraf** [hashicorp/terraform-provider-aws#17817]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is no way for terraform to configure the following checkboxes s3 bucket replication rule:
Replication Time Control
Replication metrics and notifications

### New or Affected Resource(s)

aws_s3_bucket

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by ewbankkit** [comment]
@isaacgraf Thanks for raising this issue.
It has already been noticed in #10974. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
