### ISSUE TITLE
Can't use ECDH subkey due to outdated version of go-crypto module

### ISSUE THREAD

**Issue by mickaelvalmier** [hashicorp/terraform-provider-aws#17823]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.29.1
```

### Affected Resource(s)

* aws_iam_access_key
* aws_iam_user_login_profile
* all resources using PGP key

### Terraform Configuration Files

```
gpg --keyid-format LONG  key.pgp
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   nistp384/**************** 2021-01-02 [C]
      ****************************************
uid                           ********* ********** <******@**********.***>
sub   nistp384/**************** 2021-01-03 [E] [expire : 2023-01-03]
```

```hcl
locals {
  gpg_key_public = "Base64-encoded GPG public key"
}

resource "aws_iam_user" "johndoe" {
  name = "johndoe"
  path = "/"
}

resource "aws_iam_user_login_profile" "johndoe" {
  user                    = aws_iam_user.johndoe.name
  pgp_key                 = local.gpg_key_public
  password_length         = 20
  password_reset_required = true
}
```

### Expected Behavior

Password is generated then encrypted with PGP public subkey having the encryption capability before creating resource.

### Actual Behavior

The `terraform plan` command fails during the encryption step and throws this error :

```Error: error encrypting password during IAM User Login Profile (*****) creation:
Error encrypting Password: error setting up encryption for PGP message: openpgp:
invalid argument: cannot encrypt a message to key id ************** because it has
no encryption keys
```

### Steps to Reproduce

1. `terraform apply`

### How to fix

I've tried to reproduce the problem by copypastting encryption step found here :
* https://github.com/hashicorp/terraform-provider-aws/blob/master/aws/internal/vault/helper/pgpkeys/encrypt_decrypt.go#L18
* https://github.com/hashicorp/terraform-provider-aws/blob/master/aws/internal/vault/helper/pgpkeys/encrypt_decrypt.go#L70

You can see the result from this link :
* https://gist.github.com/mickaelvalmier/b4b63841e9a3077352291795dfbc78ad

The encryption works when I use an up-to-date version of `go-crypto`, moreover after doing a Git blame on , it appears the support of ECDH encryption was added after the version used by the AWS provider `v0.0.0-20161004153544-93f5b35093ba` :
* https://github.com/keybase/go-crypto/blob/master/openpgp/packet/packet.go#L429
* https://github.com/keybase/go-crypto/blame/master/openpgp/packet/packet.go#L429
* https://github.com/keybase/go-crypto/commit/a79096c2654331901f5d50b28e99931490fff6b8

**Comment by marcaurele** [comment]
Any idea when it will be shipped to a release? I tested the `3.75.1` and it does not work to use an ECC key for the `pgp_key` attribute.
