### ISSUE TITLE
Implement Provider Default Tags Functionality

### ISSUE THREAD

**Issue by anGie44** [hashicorp/terraform-provider-aws#17829]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Placeholder for resource-level implementation roll-out of default_tags.
Preceded by #17826 #17827 

### Affected Resource(s) (subject to change)

_The maintainers will decide if these should be completed all at once or in another manner._

- [x] aws/resource_aws_opsworks_*_layer.go
- [x] aws/resource_aws_accessanalyzer_analyzer.go
- [ ] aws/resource_aws_acm_certificate.go
- [ ] aws/resource_aws_acmpca_certificate_authority.go
- [ ] aws/resource_aws_ami.go
- [ ] aws/resource_aws_ami_copy.go
- [ ] aws/resource_aws_ami_from_instance.go
- [ ] aws/resource_aws_api_gateway_api_key.go
- [ ] aws/resource_aws_api_gateway_client_certificate.go
- [ ] aws/resource_aws_api_gateway_domain_name.go
- [ ] aws/resource_aws_api_gateway_rest_api.go
- [ ] aws/resource_aws_api_gateway_stage.go
- [ ] aws/resource_aws_api_gateway_usage_plan.go
- [ ] aws/resource_aws_api_gateway_vpc_link.go
- [ ] aws/resource_aws_apigatewayv2_api.go
- [ ] aws/resource_aws_apigatewayv2_domain_name.go
- [ ] aws/resource_aws_apigatewayv2_stage.go
- [ ] aws/resource_aws_apigatewayv2_vpc_link.go
- [ ] aws/resource_aws_appmesh_gateway_route.go
- [ ] aws/resource_aws_appmesh_mesh.go
- [ ] aws/resource_aws_appmesh_route.go
- [ ] aws/resource_aws_appmesh_virtual_gateway.go
- [ ] aws/resource_aws_appmesh_virtual_node.go
- [ ] aws/resource_aws_appmesh_virtual_router.go
- [ ] aws/resource_aws_appmesh_virtual_service.go
- [ ] aws/resource_aws_appsync_graphql_api.go
- [ ] aws/resource_aws_athena_workgroup.go
- [ ] aws/resource_aws_backup_plan.go
- [ ] aws/resource_aws_backup_vault.go
- [ ] aws/resource_aws_batch_compute_environment.go
- [ ] aws/resource_aws_batch_job_definition.go
- [ ] aws/resource_aws_batch_job_queue.go
- [ ] aws/resource_aws_cloud9_environment_ec2.go
- [ ] aws/resource_aws_cloudformation_stack.go
- [ ] aws/resource_aws_cloudformation_stack_set.go
- [ ] aws/resource_aws_cloudfront_distribution.go
- [ ] aws/resource_aws_cloudhsm_v2_cluster.go
- [ ] aws/resource_aws_cloudtrail.go
- [ ] aws/resource_aws_cloudwatch_composite_alarm.go
- [ ] aws/resource_aws_cloudwatch_event_bus.go
- [ ] aws/resource_aws_cloudwatch_event_rule.go
- [ ] aws/resource_aws_cloudwatch_log_group.go
- [ ] aws/resource_aws_cloudwatch_metric_alarm.go
- [ ] aws/resource_aws_codeartifact_domain.go
- [ ] aws/resource_aws_codeartifact_repository.go
- [ ] aws/resource_aws_codebuild_project.go
- [ ] aws/resource_aws_codebuild_report_group.go
- [ ] aws/resource_aws_codecommit_repository.go
- [ ] aws/resource_aws_codedeploy_app.go
- [ ] aws/resource_aws_codedeploy_deployment_group.go
- [ ] aws/resource_aws_codepipeline.go
- [ ] aws/resource_aws_codepipeline_webhook.go
- [ ] aws/resource_aws_codestarconnections_connection.go
- [ ] aws/resource_aws_codestarnotifications_notification_rule.go
- [ ] aws/resource_aws_cognito_identity_pool.go
- [ ] aws/resource_aws_cognito_user_pool.go
- [ ] aws/resource_aws_config_aggregate_authorization.go
- [ ] aws/resource_aws_config_config_rule.go
- [ ] aws/resource_aws_config_configuration_aggregator.go
- [ ] aws/resource_aws_customer_gateway.go
- [ ] aws/resource_aws_datapipeline_pipeline.go
- [ ] aws/resource_aws_datasync_agent.go
- [ ] aws/resource_aws_datasync_location_efs.go
- [ ] aws/resource_aws_datasync_location_fsx_windows_file_system.go
- [ ] aws/resource_aws_datasync_location_nfs.go
- [ ] aws/resource_aws_datasync_location_s3.go
- [ ] aws/resource_aws_datasync_location_smb.go
- [ ] aws/resource_aws_datasync_task.go
- [ ] aws/resource_aws_dax_cluster.go
- [ ] aws/resource_aws_db_cluster_snapshot.go
- [ ] aws/resource_aws_db_event_subscription.go
- [ ] aws/resource_aws_db_instance.go
- [ ] aws/resource_aws_db_option_group.go
- [ ] aws/resource_aws_db_parameter_group.go
- [ ] aws/resource_aws_db_proxy.go
- [ ] aws/resource_aws_db_proxy_endpoint.go
- [ ] aws/resource_aws_db_security_group.go
- [ ] aws/resource_aws_db_snapshot.go
- [ ] aws/resource_aws_db_subnet_group.go
- [ ] aws/resource_aws_default_network_acl.go
- [ ] aws/resource_aws_default_route_table.go
- [ ] aws/resource_aws_default_security_group.go
- [ ] aws/resource_aws_directory_service_directory.go
- [ ] aws/resource_aws_dlm_lifecycle_policy.go
- [ ] aws/resource_aws_dms_certificate.go
- [ ] aws/resource_aws_dms_endpoint.go
- [ ] aws/resource_aws_dms_event_subscription.go
- [ ] aws/resource_aws_dms_replication_instance.go
- [ ] aws/resource_aws_dms_replication_subnet_group.go
- [ ] aws/resource_aws_dms_replication_task.go
- [ ] aws/resource_aws_docdb_cluster.go
- [ ] aws/resource_aws_docdb_cluster_instance.go
- [ ] aws/resource_aws_docdb_cluster_parameter_group.go
- [ ] aws/resource_aws_docdb_subnet_group.go
- [ ] aws/resource_aws_dx_connection.go
- [ ] aws/resource_aws_dx_hosted_private_virtual_interface_accepter.go
- [ ] aws/resource_aws_dx_hosted_public_virtual_interface_accepter.go
- [ ] aws/resource_aws_dx_hosted_transit_virtual_interface_accepter.go
- [ ] aws/resource_aws_dx_lag.go
- [ ] aws/resource_aws_dx_private_virtual_interface.go
- [ ] aws/resource_aws_dx_public_virtual_interface.go
- [ ] aws/resource_aws_dx_transit_virtual_interface.go
- [ ] aws/resource_aws_dynamodb_table.go
- [ ] aws/resource_aws_ebs_snapshot.go
- [ ] aws/resource_aws_ebs_snapshot_copy.go
- [ ] aws/resource_aws_ebs_volume.go
- [ ] aws/resource_aws_ec2_capacity_reservation.go
- [ ] aws/resource_aws_ec2_carrier_gateway.go
- [ ] aws/resource_aws_ec2_client_vpn_endpoint.go
- [ ] aws/resource_aws_ec2_fleet.go
- [ ] aws/resource_aws_ec2_local_gateway_route_table_vpc_association.go
- [ ] aws/resource_aws_ec2_managed_prefix_list.go
- [ ] aws/resource_aws_ec2_traffic_mirror_filter.go
- [ ] aws/resource_aws_ec2_traffic_mirror_session.go
- [ ] aws/resource_aws_ec2_traffic_mirror_target.go
- [ ] aws/resource_aws_ec2_transit_gateway.go
- [ ] aws/resource_aws_ec2_transit_gateway_peering_attachment.go
- [ ] aws/resource_aws_ec2_transit_gateway_peering_attachment_accepter.go
- [ ] aws/resource_aws_ec2_transit_gateway_route_table.go
- [ ] aws/resource_aws_ec2_transit_gateway_vpc_attachment.go
- [ ] aws/resource_aws_ec2_transit_gateway_vpc_attachment_accepter.go
- [ ] aws/resource_aws_ecr_repository.go
- [ ] aws/resource_aws_ecs_capacity_provider.go
- [ ] aws/resource_aws_ecs_cluster.go
- [ ] aws/resource_aws_ecs_service.go
- [ ] aws/resource_aws_ecs_task_definition.go
- [ ] aws/resource_aws_efs_access_point.go
- [ ] aws/resource_aws_efs_file_system.go
- [ ] aws/resource_aws_egress_only_internet_gateway.go
- [ ] aws/resource_aws_eip.go
- [ ] aws/resource_aws_eks_addon.go
- [ ] aws/resource_aws_eks_cluster.go
- [ ] aws/resource_aws_eks_fargate_profile.go
- [ ] aws/resource_aws_eks_node_group.go
- [ ] aws/resource_aws_elastic_beanstalk_application.go
- [ ] aws/resource_aws_elastic_beanstalk_application_version.go
- [ ] aws/resource_aws_elastic_beanstalk_environment.go
- [ ] aws/resource_aws_elasticache_cluster.go
- [ ] aws/resource_aws_elasticache_replication_group.go
- [ ] aws/resource_aws_elasticache_subnet_group.go
- [ ] aws/resource_aws_elasticsearch_domain.go
- [ ] aws/resource_aws_elb.go
- [ ] aws/resource_aws_emr_cluster.go
- [ ] aws/resource_aws_flow_log.go
- [ ] aws/resource_aws_fsx_lustre_file_system.go
- [ ] aws/resource_aws_fsx_windows_file_system.go
- [ ] aws/resource_aws_gamelift_alias.go
- [ ] aws/resource_aws_gamelift_build.go
- [ ] aws/resource_aws_gamelift_fleet.go
- [ ] aws/resource_aws_gamelift_game_session_queue.go
- [ ] aws/resource_aws_glacier_vault.go
- [ ] aws/resource_aws_globalaccelerator_accelerator.go
- [ ] aws/resource_aws_glue_crawler.go
- [ ] aws/resource_aws_glue_dev_endpoint.go
- [ ] aws/resource_aws_glue_job.go
- [ ] aws/resource_aws_glue_ml_transform.go
- [ ] aws/resource_aws_glue_registry.go
- [ ] aws/resource_aws_glue_schema.go
- [ ] aws/resource_aws_glue_trigger.go
- [ ] aws/resource_aws_glue_workflow.go
- [ ] aws/resource_aws_guardduty_detector.go
- [ ] aws/resource_aws_guardduty_filter.go
- [ ] aws/resource_aws_guardduty_ipset.go
- [ ] aws/resource_aws_guardduty_threatintelset.go
- [ ] aws/resource_aws_iam_instance_profile.go
- [ ] aws/resource_aws_iam_openid_connect_provider.go
- [ ] aws/resource_aws_iam_policy.go
- [ ] aws/resource_aws_iam_role.go
- [ ] aws/resource_aws_iam_saml_provider.go
- [ ] aws/resource_aws_iam_server_certificate.go
- [ ] aws/resource_aws_iam_user.go
- [ ] aws/resource_aws_imagebuilder_component.go
- [ ] aws/resource_aws_imagebuilder_distribution_configuration.go
- [ ] aws/resource_aws_imagebuilder_image.go
- [ ] aws/resource_aws_imagebuilder_image_pipeline.go
- [ ] aws/resource_aws_imagebuilder_image_recipe.go
- [ ] aws/resource_aws_imagebuilder_infrastructure_configuration.go
- [ ] aws/resource_aws_inspector_assessment_template.go
- [ ] aws/resource_aws_instance.go
- [ ] aws/resource_aws_internet_gateway.go
- [ ] aws/resource_aws_iot_topic_rule.go
- [ ] aws/resource_aws_key_pair.go
- [ ] aws/resource_aws_kinesis_analytics_application.go
- [ ] aws/resource_aws_kinesis_firehose_delivery_stream.go
- [ ] aws/resource_aws_kinesis_stream.go
- [ ] aws/resource_aws_kinesis_video_stream.go
- [ ] aws/resource_aws_kinesisanalyticsv2_application.go
- [ ] aws/resource_aws_kms_external_key.go
- [ ] aws/resource_aws_kms_key.go
- [ ] aws/resource_aws_lambda_function.go
- [ ] aws/resource_aws_launch_template.go
- [ ] aws/resource_aws_lb.go
- [ ] aws/resource_aws_lb_target_group.go
- [ ] aws/resource_aws_licensemanager_license_configuration.go
- [ ] aws/resource_aws_lightsail_instance.go
- [ ] aws/resource_aws_media_convert_queue.go
- [ ] aws/resource_aws_media_package_channel.go
- [ ] aws/resource_aws_media_store_container.go
- [ ] aws/resource_aws_mq_broker.go
- [ ] aws/resource_aws_mq_configuration.go
- [ ] aws/resource_aws_msk_cluster.go
- [ ] aws/resource_aws_mwaa_environment.go
- [ ] aws/resource_aws_nat_gateway.go
- [ ] aws/resource_aws_neptune_cluster.go
- [ ] aws/resource_aws_neptune_cluster_instance.go
- [ ] aws/resource_aws_neptune_cluster_parameter_group.go
- [ ] aws/resource_aws_neptune_event_subscription.go
- [ ] aws/resource_aws_neptune_parameter_group.go
- [ ] aws/resource_aws_neptune_subnet_group.go
- [ ] aws/resource_aws_network_acl.go
- [ ] aws/resource_aws_network_interface.go
- [ ] aws/resource_aws_networkfirewall_firewall.go
- [ ] aws/resource_aws_networkfirewall_firewall_policy.go
- [ ] aws/resource_aws_networkfirewall_rule_group.go
- [ ] aws/resource_aws_opsworks_stack.go
- [ ] aws/resource_aws_organizations_account.go
- [ ] aws/resource_aws_organizations_organizational_unit.go
- [ ] aws/resource_aws_organizations_policy.go
- [ ] aws/resource_aws_pinpoint_app.go
- [ ] aws/resource_aws_placement_group.go
- [ ] aws/resource_aws_qldb_ledger.go
- [ ] aws/resource_aws_ram_resource_share.go
- [ ] aws/resource_aws_rds_cluster.go
- [ ] aws/resource_aws_rds_cluster_endpoint.go
- [ ] aws/resource_aws_rds_cluster_instance.go
- [ ] aws/resource_aws_rds_cluster_parameter_group.go
- [ ] aws/resource_aws_redshift_cluster.go
- [ ] aws/resource_aws_redshift_event_subscription.go
- [ ] aws/resource_aws_redshift_parameter_group.go
- [ ] aws/resource_aws_redshift_snapshot_copy_grant.go
- [ ] aws/resource_aws_redshift_snapshot_schedule.go
- [ ] aws/resource_aws_redshift_subnet_group.go
- [ ] aws/resource_aws_resourcegroups_group.go
- [ ] aws/resource_aws_route53_health_check.go
- [ ] aws/resource_aws_route53_resolver_endpoint.go
- [ ] aws/resource_aws_route53_resolver_firewall_domain_list.go
- [ ] aws/resource_aws_route53_resolver_firewall_rule_group.go
- [ ] aws/resource_aws_route53_resolver_firewall_rule_group_association.go
- [ ] aws/resource_aws_route53_resolver_query_log_config.go
- [ ] aws/resource_aws_route53_resolver_rule.go
- [ ] aws/resource_aws_route53_zone.go
- [ ] aws/resource_aws_route_table.go
- [ ] aws/resource_aws_s3_bucket.go
- [ ] aws/resource_aws_s3_bucket_object.go
- [ ] aws/resource_aws_s3_object_copy.go
- [ ] aws/resource_aws_s3control_bucket.go
- [ ] aws/resource_aws_sagemaker_app.go
- [ ] aws/resource_aws_sagemaker_domain.go
- [ ] aws/resource_aws_sagemaker_endpoint.go
- [ ] aws/resource_aws_sagemaker_endpoint_configuration.go
- [ ] aws/resource_aws_sagemaker_feature_group.go
- [ ] aws/resource_aws_sagemaker_image.go
- [ ] aws/resource_aws_sagemaker_model.go
- [ ] aws/resource_aws_sagemaker_model_package_group.go
- [ ] aws/resource_aws_sagemaker_notebook_instance.go
- [ ] aws/resource_aws_sagemaker_user_profile.go
- [ ] aws/resource_aws_secretsmanager_secret.go
- [ ] aws/resource_aws_security_group.go
- [ ] aws/resource_aws_serverlessapplicationrepository_cloudformation_stack.go
- [ ] aws/resource_aws_service_discovery_http_namespace.go
- [ ] aws/resource_aws_service_discovery_private_dns_namespace.go
- [ ] aws/resource_aws_service_discovery_public_dns_namespace.go
- [ ] aws/resource_aws_service_discovery_service.go
- [ ] aws/resource_aws_servicecatalog_portfolio.go
- [ ] aws/resource_aws_servicecatalog_product.go
- [ ] aws/resource_aws_sfn_activity.go
- [ ] aws/resource_aws_sfn_state_machine.go
- [ ] aws/resource_aws_shield_protection.go
- [ ] aws/resource_aws_signer_signing_profile.go
- [ ] aws/resource_aws_sns_topic.go
- [ ] aws/resource_aws_spot_fleet_request.go
- [ ] aws/resource_aws_sqs_queue.go
- [ ] aws/resource_aws_ssm_activation.go
- [ ] aws/resource_aws_ssm_document.go
- [ ] aws/resource_aws_ssm_maintenance_window.go
- [ ] aws/resource_aws_ssm_parameter.go
- [ ] aws/resource_aws_ssm_patch_baseline.go
- [ ] aws/resource_aws_ssoadmin_permission_set.go
- [ ] aws/resource_aws_storagegateway_cached_iscsi_volume.go
- [ ] aws/resource_aws_storagegateway_gateway.go
- [ ] aws/resource_aws_storagegateway_nfs_file_share.go
- [ ] aws/resource_aws_storagegateway_smb_file_share.go
- [ ] aws/resource_aws_storagegateway_stored_iscsi_volume.go
- [ ] aws/resource_aws_storagegateway_tape_pool.go
- [ ] aws/resource_aws_subnet.go
- [ ] aws/resource_aws_swf_domain.go
- [ ] aws/resource_aws_synthetics_canary.go
- [ ] aws/resource_aws_transfer_server.go
- [ ] aws/resource_aws_transfer_user.go
- [ ] aws/resource_aws_vpc.go
- [ ] aws/resource_aws_vpc_dhcp_options.go
- [ ] aws/resource_aws_vpc_endpoint.go
- [ ] aws/resource_aws_vpc_endpoint_service.go
- [ ] aws/resource_aws_vpc_peering_connection.go
- [ ] aws/resource_aws_vpc_peering_connection_accepter.go
- [ ] aws/resource_aws_vpn_connection.go
- [ ] aws/resource_aws_vpn_gateway.go
- [ ] aws/resource_aws_waf_rate_based_rule.go
- [ ] aws/resource_aws_waf_rule.go
- [ ] aws/resource_aws_waf_rule_group.go
- [ ] aws/resource_aws_waf_web_acl.go
- [ ] aws/resource_aws_wafregional_rate_based_rule.go
- [ ] aws/resource_aws_wafregional_rule.go
- [ ] aws/resource_aws_wafregional_rule_group.go
- [ ] aws/resource_aws_wafregional_web_acl.go
- [ ] aws/resource_aws_wafv2_ip_set.go
- [ ] aws/resource_aws_wafv2_regex_pattern_set.go
- [ ] aws/resource_aws_wafv2_rule_group.go
- [ ] aws/resource_aws_wafv2_web_acl.go
- [ ] aws/resource_aws_workspaces_directory.go
- [ ] aws/resource_aws_workspaces_ip_group.go
- [ ] aws/resource_aws_workspaces_workspace.go
- [ ] aws/resource_aws_xray_group.go
- [ ] aws/resource_aws_xray_sampling_rule.go

### References

* #7926

**Comment by georev** [comment]
Is there a list of which of these are functional at this point? Docs for 3.38.0 say it is available for many resources, but I'm not getting ECS resources tagged with provider default_tags. The config deploys without error, but no tags on resources.

**Comment by anGie44** [comment]
Hi @georev, the functionality in theory is available to all resources that have a configurable `tags` argument. Do you mind creating a new issue with more details related to the ECS resources that are not receiving the tags as expected

**Comment by georev** [comment]
Thanks @anGie44 I'll make a new issue when I get back to this. I just went ahead and did it the old way and need to move on at the moment.
