### ISSUE TITLE
Update documentation to reflect current bugs preventing use of shared credentials file

### ISSUE THREAD

**Issue by ajsharp** [hashicorp/terraform-provider-aws#17824]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.29.1

### Terraform Configuration Files

```hcl
provider "aws" {
  profile = "profile_name"
  region  = "us-east-1"
}
```

### Debug Output

```
terraform plan

Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

Waiting for the plan to start...

Terraform v0.14.7
Configuring remote state backend...
Initializing Terraform configuration...

Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.

Please see https://registry.terraform.io/providers/hashicorp/aws
for more information about providing credentials.

Error: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

### Expected Behavior

The documentation [states](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#shared-credentials-file) that you can use a shared credentials file with a profile name to load aws credentials:

> You can use an AWS credentials or configuration file to specify your credentials. The default location is $HOME/.aws/credentials on Linux and macOS, or "%USERPROFILE%\.aws\credentials" on Windows. You can optionally specify a different location in the Terraform configuration by providing the shared_credentials_file argument or using the AWS_SHARED_CREDENTIALS_FILE environment variable. This method also supports a profile configuration and matching AWS_PROFILE environment variable:

Due to a [current bug](https://github.com/hashicorp/aws-sdk-go-base/pull/53) in the go client that part documentation is outdated, and should be noted accordingly in the docs.

The documentation should reflect the current limitations of AWS credential loading.

### Actual Behavior

See debug output above.

### Steps to Reproduce

1. `terraform plan`

### References

* #16894
* #9854

**Comment by chrisbulgaria** [comment]
Or even better - merge the pull request for #16894

**Comment by ajsharp** [comment]
For me, credentials file with a profile is completely broken. Only way I can get it to auth is by using access key and secret key explicitly.

**Comment by gdavison** [comment]
Hi @ajsharp, based on the log message

> Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
> will stop streaming the logs, but will not stop the plan running remotely.

It looks like the actual execution of your Terraform run is running on Terraform Cloud or Terraform Enterprise. This means it won't have access to the shared credentials file on your local workstation and you will need to use other authentication settings, such as using the `access_key` and `secret_key` parameters or their corresponding environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.

If you want to execute Terraform locally and just use Terraform Cloud or Terraform Enterprise for state storage, you'll need to update the workspace configuration to the "Local" execution mode.

**Comment by breathingdust** [comment]
Closing due to lack of response.
