### ISSUE TITLE
AWS Lambda support for AWS MSK with SASL/SCRAM as an event source

### ISSUE THREAD

**Issue by AlexanderSchiff** [hashicorp/terraform-provider-aws#17825]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Amazon MSK now supports SASL/SCRAM authentication with usernames and passwords secured by AWS Secrets Manager

### New or Affected Resource(s)

* [aws_lambda_event_source_mapping](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping)

### Potential Terraform Configuration

```hcl
resource "aws_lambda_event_source_mapping" "example" {
  event_source_arn  = aws_msk_cluster.example.arn
  function_name     = aws_lambda_function.example.arn
  topics            = ["Example"]
  starting_position = "LATEST"

  source_access_configuration {
    type = "SASL_SCRAM_512_AUTH"
    uri  = aws_secretsmanager_secret.example.arn
  }
}
```

### References

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2020/09/amazon-msk-now-supports-sasl-scram-authentication-with-usernames-and-passwords-secured-by-aws-secrets-manager/)
* [Blog post](https://aws.amazon.com/blogs/compute/using-amazon-msk-as-an-event-source-for-aws-lambda/)
* [SASL/SCRAM Authentication for event source mapping](https://docs.aws.amazon.com/lambda/latest/dg/msk-permissions.html)
* [Adding MSK cluster as an event source](https://docs.aws.amazon.com/lambda/latest/dg/services-msk-topic-add.html)

**Comment by ewbankkit** [comment]
Related:

* https://github.com/hashicorp/terraform-provider-aws/issues/14658
* https://github.com/hashicorp/terraform-provider-aws/pull/14746

`source_access_configuration` is also needed for self-managed Kafka event sources: #16785.

**Comment by AlexanderSchiff** [comment]
@ewbankkit hi, do you think this feature will get worked on? I would like it for my project
