### ISSUE TITLE
resource/aws_acmpca_certificate_authority: Remove returned status value

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#17832]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When an `aws_acmpca_certificate_authority` is created, it enters the state `CERTIFICATE_PENDING`, where it needs to have a certificate imported before it can be used. A root CA can create its own self-signed certificate when in this state.

A certificate can be imported using the console, API, or CLI, and there is work in progress to add the `aws_acmpca_certificate_authority_certificate` resource. When a certificate is imported, the status of the certificate authority changes to `ACTIVE`. In all of the above cases, Terraform will still report the status `CERTIFICATE_PENDING`.

The only other practitioner-controllable status is `DISABLED`. All other states are transitional, and the providers waits until the resource reaches a non-transitional state. https://docs.aws.amazon.com/acm-pca/latest/userguide/PCAUpdateCA.html details the possible states.

Switching between `ACTIVE` and `DISABLED` is controlled by the `enabled` flag on the resource.

These factors make the `status` field superfluous and sometimes-incorrect, so it should be removed.

### Affected Resource

* aws_acmpca_certificate_authority

**Comment by zhelding** [comment]
PR #22878 has deprecated the `status` attribute as part of release `v4.0`.

The `status` attribute is scheduled to be removed as part of major version release `v5.0`.
