### ISSUE TITLE
new aws_backup_plan validation is incorrectly strict

### ISSUE THREAD

**Issue by atz** [hashicorp/terraform-provider-aws#17835]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.12.29
+ provider.aws v3.29.1
+ provider.random v2.1.1
```

### Affected Resource(s)

* **aws_backup_plan**

### Terraform Configuration Files

```hcl
resource "aws_backup_plan" "aws_efs_automatic_backup_plan" {
  name = "aws/efs/automatic-backup-plan" 

  rule {
    completion_window   = 10080
    recovery_point_tags = {}
    rule_name           = "aws/efs/automatic-backup-rule"
    schedule            = "cron(0 5/12 ? * * *)"
    start_window        = 480
    target_vault_name   = "aws/efs/automatic-backup-vault"

    lifecycle {
      cold_storage_after = 14
      delete_after       = 104
    }
  }
}
```

### Expected Behavior

Names AWS permits should be permitted, including slashes.

### Actual Behavior
```
Error: invalid value for rule.0.rule_name (must contain only alphanumeric characters, hyphens, underscores, and periods)

  on example.tf line 1, in resource "aws_backup_plan" "aws_efs_automatic_backup_plan":
 1: resource "aws_backup_plan" "aws_efs_automatic_backup_plan" {

Error: invalid value for rule.0.target_vault_name (must contain only alphanumeric characters, hyphens, and underscores)

  on example.tf line 1, in resource "aws_backup_plan" "aws_efs_automatic_backup_plan":
 1: resource "aws_backup_plan" "aws_efs_automatic_backup_plan" {
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Note: resources were successfully created with a previous version of `provider.aws` (2.70).  

### References
- Validation was added here: https://github.com/hashicorp/terraform-provider-aws/pull/16476
- The author reasonably interpreted the [AWS SDK comments](https://github.com/aws/aws-sdk-go/blob/v1.37.18/service/backup/api.go#L5979-L6001) that say, for example, that BackupVaultName `consist of letters, numbers, and hyphens`.  But the SDK comments are objectively incorrect.  Slashes are permitted.

```sh
aws backup list-backup-vaults| jq '.BackupVaultList[].BackupVaultName'
"Default"
"aws/efs/automatic-backup-vault"
```

**Comment by atz** [comment]
Note: filed ticket on the upstream AWS SDK docs/comments https://github.com/aws/aws-sdk-go/issues/3800

**Comment by ewbankkit** [comment]
When you create your own vault, the AWS Console restricts the name:

![Screenshot 2021-02-26 073101](https://user-images.githubusercontent.com/2404182/109300529-9b8f6380-7804-11eb-85e8-d4be828a75d7.png)

but other AWS services (e.g. [EFS](https://aws.amazon.com/premiumsupport/knowledge-center/efs-disable-automatic-backups/)) can create backup vaults with '/'s in the name.

**Comment by atz** [comment]
@ewbankkit: interesting.  In the example TF, the vault is created as part of a backup plan (same service, presumed same validation).  Seems like AWS inconsistency is the root problem.  

In that case, provider.aws would only trip up (fail `plan` for an existing resource) in the context of:
- import
- upgrade of provider.aws

It probably makes sense to retain the stricter (more service-specific) validation.  But I suggest a comment in docs (migration instructions or release notes) would be in order.  Thanks for the clarification!

**Comment by ewbankkit** [comment]
@atz We should certainly retain strict validation of `name` for the `aws_backup_vault` resource but remove the validation of `target_vault_name` for `aws_backup_plan` as you can create a plan on an AWS-created vault (as in your example).

**Comment by atz** [comment]
@ewbankkit I leave it to your discretion.

**Comment by ewbankkit** [comment]
As this blocks a valid workflow and backup vaults with `/`s in the name are allowed in the AWS Console

![Screenshot 2021-02-28 164917](https://user-images.githubusercontent.com/2404182/109434827-11522580-79e5-11eb-96b8-75a17e778467.png)

I'll go ahead and reverse the validation on the `rule.target_vault_name` attribute.

**Comment by ewbankkit** [comment]
If you try and create a backup plan on the `aws/efs/automatic-backup-vault` the AWS API returns

```
        Error: error creating Backup Plan: AccessDeniedException: 
        	status code: 403, request id: ed2afb4c-7f60-469c-a0ab-c6c8d6820e93
```

It seems that only the built-in `aws/efs/automatic-backup-plan` plan can exist for this vault:

![Screenshot 2021-02-28 172044](https://user-images.githubusercontent.com/2404182/109435642-58421a00-79e9-11eb-9034-bd8e87586485.png)

**Comment by ewbankkit** [comment]
@atz We'll leave the validation in place for `target_vault_name` as no rule can be created on the built-in vault(s).
