### ISSUE TITLE
Import or create mode for aws_cloudwatch_log_group

### ISSUE THREAD

**Issue by lijok** [hashicorp/terraform-provider-aws#17839]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS automatically creates some cloudwatch log groups, such as `RDSOSMetrics` and `/aws/apigateway/welcome`.
We want to bring these log groups under terraform management, both in production and ephemeral environments.

### New or Affected Resource(s)

* aws_cloudwatch_log_group

### Potential Terraform Configuration

```hcl
resource "aws_cloudwatch_log_group" "rds_os_metrics" {
  name              = "RDSOSMetrics"
  retention_in_days = 365
  tags              = local.tags
  import_or_create  = true
}
```

**Comment by ewbankkit** [comment]
@lijok Thanks for raising this issue.
Is a reason that `terraform import` of the resource is insufficient for your use case that you do not want the underlying, AWS-created resource to be deleted if the Terraform resource is destroyed?
Are you looking to potentially manage all attributes of the log group or just specific attributes, for example `tags`?

**Comment by lijok** [comment]
@ewbankkit thanks for looking into this
Wanting the resource to be deleted when the underlying terraform resource is destroyed, is one of the reasons why we want to bring these automatically created log groups under terraform management. The other reason is to manage the retention_in_days and tags attribute.
The reason `terraform import` is insufficient is because we have dozens of ephemeral aws environments, which we spin up and down every day automatically, so running manual `terraform import` on them is not feasible
This would be somewhat similar to what https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_security_group does

**Comment by ewbankkit** [comment]
@lijok Thanks for the prompt response.
Does Terraform CLI issue https://github.com/hashicorp/terraform/issues/19017 cover your use case?

**Comment by lijok** [comment]
@ewbankkit Yes, I think it does, thank you

**Comment by ewbankkit** [comment]
Great.
Let's leave this one open.
I'm sure I've seen similar requests for AWS resources and I'll link them.
