### ISSUE TITLE
Warning when creating multiple aws_s3_bucket_notification resources on the same bucket

### ISSUE THREAD

**Issue by njlr** [hashicorp/terraform-provider-aws#17842]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating multiple `aws_s3_bucket_notification` resources on the same bucket, it would be great if Terraform could produce a warning, since this is invalid and can lead to confusing bugs. 

### New or Affected Resource(s)

 * `aws_s3_bucket_notification`

### Potential Terraform Configuration

This is invalid:

```hcl
resource "aws_s3_bucket_notification" "foo_writes" {
  bucket = aws_s3_bucket.foo.id

  lambda_function {
    lambda_function_arn = aws_lambda_function.foo.arn
    events              = [ "s3:ObjectCreated:*" ]
  }
}

resource "aws_s3_bucket_notification" "foo_writes2" {
  bucket = aws_s3_bucket.foo.id

  lambda_function {
    lambda_function_arn = aws_lambda_function.bar.arn
    events              = [ "s3:ObjectCreated:*" ]
  }
}
```

Terraform should warn the user. 

This is what should be done instead:

```hcl
resource "aws_s3_bucket_notification" "foo_writes" {
  bucket = aws_s3_bucket.foo.id

  lambda_function {
    lambda_function_arn = aws_lambda_function.foo.arn
    events              = [ "s3:ObjectCreated:*" ]
  }

  lambda_function {
    lambda_function_arn = aws_lambda_function.bar.arn
    events              = [ "s3:ObjectCreated:*" ]
  }
}
```

**Comment by bflad** [comment]
Hi @njlr 👋  Thank you for raising this feature request. Long term, this is likely something we do want to address more holistically for Terraform resources. We have been consolidating these types of requests into https://github.com/hashicorp/terraform-provider-aws/issues/14394 as a single tracking issue for the Terraform AWS Provider and https://github.com/hashicorp/terraform-plugin-sdk/issues/224 in the Terraform Plugin SDK. Please feel free to 👍  react and subscribe to them for further updates and discussions.
