### ISSUE TITLE
aws_ssm_maintenance_window run command SNS notification, can't specify IAM Role

### ISSUE THREAD

**Issue by aromond** [hashicorp/terraform-provider-aws#17848]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

![image](https://user-images.githubusercontent.com/578855/109354535-f5674c00-784b-11eb-8567-713ebe4673ef.png)

Maintenance Window Run Command Tasks interface allows specifying an IAM Role to notify SNS with. This currently is not an option under aws_ssm_maintenance_window_task

When I try to use a custom service role it does not seem to propagate to the SNS section and my maintenance window gives an error that the role is invalid. 

Could a field for specifying the IAM Role for SNS notifications be added?

**Comment by DrFaust92** [comment]
See #17624.
