### ISSUE TITLE
An argument named "tags" is not expected in AWS Sagemaker (sagemaker_app_image_config service).

### ISSUE THREAD

**Issue by SebastianUA** [hashicorp/terraform-provider-aws#17858]
Hello,

When I was developing an AWS Sagemaker module, I got the next issue: 
```
on ../../modules/sagemaker/sagemaker_app_image_config.tf line 33, in resource "aws_sagemaker_app_image_config" "sagemaker_app_image_config":
  33:   tags = merge(

An argument named "tags" is not expected here.
```

The code can be found here: https://github.com/SebastianUA/terraform/blob/dev/aws/modules/sagemaker/sagemaker_app_image_config.tf#L33-L38

Could you please update the documentation or fix the bug of tags?
Thanks

**Comment by DrFaust92** [comment]
Related #17267
