### ISSUE TITLE
Feature request add filtering to aws_iam_role

### ISSUE THREAD

**Issue by adamstirk-ct** [hashicorp/terraform-provider-aws#17868]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be useful to be able to filter IAM roles using datasource filtering as per [https://registry.terraform.io/providers/hashicorp/oci/latest/docs/guides/filters](https://registry.terraform.io/providers/hashicorp/oci/latest/docs/guides/filters).

In our use case we use AWS Control Tower which creates AWS SSO roles which are unique and we currently have no way of getting the roles without first storing it somewhere first (e.g. variable or SSM parameter).

### New or Affected Resource(s)

* aws_iam_role

### Potential Terraform Configuration

```hcl
data "aws_iam_role" "example" {
	filter {
		name = "name"
		values = ["AWSReservedSSO_AWSAdministratorAccess_*"]
	}
	
	filter {
		name = "path"
		values = ["/aws-reserved/sso.amazonaws.com/eu-west-1/"]
	}
}
```

**Comment by bplotnick** [comment]
I think this is a dupe of https://github.com/hashicorp/terraform-provider-aws/issues/14470, which is addressed in https://github.com/hashicorp/terraform-provider-aws/pull/18585 (PR in review)

**Comment by jlamande** [comment]
Yes the #18585 is still open and waiting for any review
