### ISSUE TITLE
changing an aws_ssm_maintenance_window_task that has priority 0 results in a "Member must not be null" priority constraint error from the API

### ISSUE THREAD

**Issue by tzvifriedman** [hashicorp/terraform-provider-aws#17871]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.4
AWS provider 3.23 

### Affected Resource(s)

* aws_ssm_maintenance_window_task

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ssm_maintenance_window_task" "datadog_mute" {
  count            = var.mx_window_multiple == true ? 2 : 1
  priority         = 0
  max_concurrency  = "10"
  max_errors       = "5"
  service_role_arn = [...]
  task_arn         = "AWS-RunPowerShellScript"
  task_type        = "RUN_COMMAND"
  window_id        = aws_ssm_maintenance_window.mx_window_install.*.id[count.index]

  targets {
    key    = "WindowTargetIds"
    values = [aws_ssm_maintenance_window_target.mx_window_install_target.*.id[count.index]]
  }

  task_invocation_parameters {
    run_command_parameters {
      service_role_arn = "[...]"
      timeout_seconds  = "600"

      parameter {
        name   = "commands"
        values = [...]
      }
    }

  }
}
```

### Debug Output

Terraform v0.13.4
Initializing plugins and modules...
module.default_mx.aws_ssm_maintenance_window_task.datadog_mute[0]: Modifying... [id=7ee87613-fafe-42cf-90b9-21e46b7f569a]

Error: Error updating Maintenance Window (mw-0206570beb23779d2) Task (7ee87613-fafe-42cf-90b9-21e46b7f569a): ValidationException: Value null at 'Priority' failed to satisfy constraint: Member must not be null
	status code: 400, request id: 6a6385ca-410f-47e2-a9c9-6663afac6208

  on ../../../base/mx_window/main.tf line 119, in resource "aws_ssm_maintenance_window_task" "datadog_mute":
 119: resource "aws_ssm_maintenance_window_task" "datadog_mute" {

I don't actually have access to the full debug logs at this point, since I'm on TFE and I'm not sure how to get access to the full debug log...
### Expected Behavior

I'm just changing the contents of the script commands, and the plan is successful. It is supposed to change the commands and it lists the priority as 0. 

### Actual Behavior

The apply should change the commands and leave the priority as 0. Instead, on apply, the API seems to think that value is actually null. 

I have three tasks in this MX Window, and I can actually bypass this issue by setting the priorities to 1, 2, and 3; obviously this is not ideal. There's something about the 0 that is making AWS think it's trying to pass null.

### Steps to Reproduce

1. Create a maintenance window task with priority 0.
2. Make a change to something in the task that doesn't trigger a recreate. 
3. `terraform apply`

### References

* #0000

**Comment by bflad** [comment]
Hi @tzvifriedman 👋  Thank you for submitting this and sorry you ran into trouble here. This is a small bug in the resource, which can be fixed up with this change: https://github.com/hashicorp/terraform-provider-aws/pull/17885

**Comment by tzvifriedman** [comment]
I had a hunch that validation was the issue, but I do not have the Go knowledge to confirm. Thanks for the quick turnaround!
