### ISSUE TITLE
Volumes created with aws_launch_configuration have no tags

### ISSUE THREAD

**Issue by tburt11** [hashicorp/terraform-provider-aws#1788]
### Terraform Version
Terraform v0.10.4

Instances created with "aws_instance" may include a "volume_tags" parameter when specifying root_block_device and/or ebs_block_device.

This option is missing from the aws_launch_config resource.

Therefore, volumes created for autoscaling group instances - Have No Tags -

This makes orphan volumes difficult to ID.

**Comment by tylux** [comment]
I am interested in this functionality as well.

**Comment by bflad** [comment]
Hi folks! The autoscaling group APIs have not historically supported volume tagging until very recently when EC2 Launch Templates were announced at re:invent (provider issue: #2505). Launch templates are supported by both EC2 instances and autoscaling groups and contain support for volume tagging. It looks like this might be the way forward for supporting this feature on autoscaling group instances. Hope this helps.

**Comment by blockjon** [comment]
I would like this too

**Comment by nunofernandes** [comment]
I also need this :+1:

**Comment by kantipov** [comment]
Helpful feature, would be nice to have it

**Comment by arjun-dandagi** [comment]
i would like this as well :)

**Comment by 2mailram** [comment]
+1

**Comment by hdhruna** [comment]
+1

**Comment by hossein-rasi** [comment]
+1

**Comment by ewbankkit** [comment]
To tag any EC2 resources created implicitly via the launch template you can use the [`aws_ec2_tag`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_tag) resource.
