### ISSUE TITLE
"managed_policy_arns" in "aws_iam_role" not expected here...

### ISSUE THREAD

**Issue by jeffmacdonald** [hashicorp/terraform-provider-aws#17883]
### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.29.0

### Affected Resource(s)

* aws_iam_role

### Terraform Configuration Files

```hcl
resource "aws_iam_role" "example" {
  name                = "yak_role"
  assume_role_policy  = data.aws_iam_policy_document.instance_assume_role_policy.json
  managed_policy_arns = ["arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"]
}

data "aws_iam_policy_document" "instance_assume_role_policy" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}
```

### Expected Behavior

I would expect it to create a role with that managed policy attached.

### Actual Behavior

```
$ terraform validate

Error: Unsupported argument

  on lambda.tf line 4, in resource "aws_iam_role" "example":
   4:   managed_policy_arns = ["arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"]

An argument named "managed_policy_arns" is not expected here.
```

### Steps to Reproduce

1. `terraform validate`

### Important Factoids

I guess the only important factoid is that I followed this https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role very closely :)

**Comment by bflad** [comment]
Hi @jeffmacdonald 👋  Thank you for submitting this and sorry you ran into trouble here.

The `managed_policy_arns` argument was introduced in [Terraform AWS Provider version 3.29.1](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3291-february-23-2021), so updating your provider version should pick it up.

I was able to verify this self-contained configuration:

```terraform
terraform {
  required_version = "0.14.7"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.29.1"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_iam_role" "example" {
  name                = "yak_role"
  assume_role_policy  = data.aws_iam_policy_document.instance_assume_role_policy.json
  managed_policy_arns = ["arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"]
}

data "aws_iam_policy_document" "instance_assume_role_policy" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}
```

You can also change provider versions in the Terraform Registry documentation by using the version dropdown to ensure you are looking at the functionality available for the specific version you are on. 👍

**Comment by jeffmacdonald** [comment]
Thanks! Also confirmed on my end.
