### ISSUE TITLE
Manage Opsworks Stack Elastic IP Resources With More Granularity 

### ISSUE THREAD

**Issue by Velgus** [hashicorp/terraform-provider-aws#17891]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, the only option for using Elastic IPs with OpsWorks is to enable `auto_assign_elastic_ips` from a layer resource. This seems to just create EIPs and put them in a pool that can be drawn from any instances using the layer with that setting.

This is limiting and can cause issues if you use OpsWorks to manage an instance that needs to use a specific IP for mail reputation or such.

The current workaround for this is to manage it via the Resources section in the OpsWorks Stack Console. From here, specific EIPs can (1) be registered with the stack, (2) be named, and (3) be associated with a specific instance. It would be nice to have equivalent functionality from Terraform.

### Affected Resources

* aws_opsworks_*_layer 
* aws_opsworks_stack
* aws_opsworks_instance

**Comment by ewbankkit** [comment]
@Velgus Thanks for raising this issue.
It seems a new resource `aws_opsworks_elastic_ip`, similar to the [`aws_opsworks_rds_db_instance`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_rds_db_instance) resource would help here.
