### ISSUE TITLE
resource aws_msk_cluster re-creates the cluster when broker instance_type changed

### ISSUE THREAD

**Issue by prashantknagarro** [hashicorp/terraform-provider-aws#17894]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/aws v3.29.1
+ provider registry.terraform.io/hashicorp/helm v2.0.2
+ provider registry.terraform.io/hashicorp/http v2.0.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v2.3.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

### Affected Resource(s)

* aws_msk_cluster

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "aws_msk_cluster" "example" {
  cluster_name           = "example"
  kafka_version          = "2.4.1"
  number_of_broker_nodes = 3

  broker_node_group_info {
    instance_type   = "kafka.m5.large"
    ebs_volume_size = 1000
    client_subnets = [
      aws_subnet.subnet_az1.id,
      aws_subnet.subnet_az2.id,
      aws_subnet.subnet_az3.id,
    ]
    security_groups = [aws_security_group.sg.id]
  }

  encryption_info {
    encryption_at_rest_kms_key_arn = aws_kms_key.kms.arn
  }

  open_monitoring {
    prometheus {
      jmx_exporter {
        enabled_in_broker = true
      }
      node_exporter {
        enabled_in_broker = true
      }
    }
  }

  logging_info {
    broker_logs {
      cloudwatch_logs {
        enabled   = true
        log_group = aws_cloudwatch_log_group.test.name
      }
      firehose {
        enabled         = true
        delivery_stream = aws_kinesis_firehose_delivery_stream.test_stream.name
      }
      s3 {
        enabled = true
        bucket  = aws_s3_bucket.bucket.id
        prefix  = "logs/msk-"
      }
    }
  }

  tags = {
    foo = "bar"
  }
}
```

### Expected Behavior

terraform should update the existing cluster as same thing can be achieved through aws console, cli or api.

### Actual Behavior

terraform is replacing existing cluster and re-creating the msk cluster. This is highly risky as we will lose all data in existing cluster when it gets re-created.
```hcl
resource "aws_msk_cluster" "this" {
      ~ arn                          = "XXXX -> (known after apply)
      ~ bootstrap_brokers            = "dns:9021" -> (known after apply)
      + bootstrap_brokers_sasl_scram = (known after apply)
      ~ bootstrap_brokers_tls        = "dns-tls:9024" -> (known after apply)
      ~ current_version              = "XX" -> (known after apply)
      ~ id                           = "arn:aws:kafka:ARNID" -> (known after apply)
        tags                         = {
            "Environment" = "prive-sit"
            "Team"        = "DevOps"
            "Terraform"   = "true"
        }
      ~ zookeeper_connect_string     = "YYY" -> (known after apply)
        # (4 unchanged attributes hidden)

      ~ broker_node_group_info {
          ~ instance_type   = "kafka.m5.large" -> "kafka.t3.small" # forces replacement
            # (4 unchanged attributes hidden)
        }


      ~ encryption_info {
          ~ encryption_at_rest_kms_key_arn = "arn:aws:kms:NNN" -> (known after apply)

            # (1 unchanged block hidden)
        }


        # (3 unchanged blocks hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce

1. update terraform configuration to change instance_type.
2. run `terraform apply`

### References

* #0000

**Comment by ewbankkit** [comment]
@prashantknagarro Thanks for raising this issue.
It has already been noticed in #17264. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
