### ISSUE TITLE
Contributing Documentation: Additions to Data Handling and Conversion

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#17902]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Some thoughts on additional content for the [Data Handling and Conversion](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/data-handling-and-conversion.md) documentation.

#### AWS Structure Field Accessors

The structures defined in the AWS Go SDK have both public fields and setter member functions:

```go
// In service/api.go

type Structure struct {
	AttributeName *string
}

// SetAttributeName sets the AttributeName field's value.
func (s *Structure ) SetAttributeName(v string) *Structure {
	s.AttributeName = &v
	return s
}
```

We should document that we always prefer setting the public field directly.

**Comment by bflad** [comment]
Nice, thank you for writing this up. I could have swore we also had a linter issue associated with this particular code style, but my quick issue searching is not bringing it up. I had a semgrep rule already written up for it and everything. I'll just write up the issue now and link it to this one. 👍

**Comment by ewbankkit** [comment]
I just spotted some occurrences in code I am fixing for a PR

https://github.com/hashicorp/terraform-provider-aws/blob/302ff329c9d344df4aa8ac9f1b7423c3f9995fcf/aws/resource_aws_lambda_event_source_mapping.go#L388-L404

I'll change these.
