### ISSUE TITLE
Terraform support for DevOps Guru

### ISSUE THREAD

**Issue by saswatadash** [hashicorp/terraform-provider-aws#17919]
This meta issue will outline the plan for adding coverage of the Amazon DevOps Guru service to the Terraform AWS Provider. The following items cover the full scope of work:

- [x] #36306 
- [x] #36332 
- [x] #36333 
- [x] #36334 
- [ ] #36335 
- [x] #36354 
- [x] #36355 

### Reference:
* https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_Operations.html

**Comment by azhurbilo** [comment]
+1 
we want use Devops Guru for RDS https://aws.amazon.com/devops-guru/features/devops-guru-for-rds/

**Comment by jltxwesley** [comment]
And update on this?

**Comment by yshollander-selerity** [comment]
+1. Would be very useful to automate devops guru configuration.

**Comment by sakomws** [comment]
++1

**Comment by CyrilDevOps** [comment]
+1

**Comment by tonyhess** [comment]
+1

**Comment by jar-b** [comment]
After assessing the publicly available AWS APIs, a proposed service design has been documented below. Individual issues with additional details and example configurations will be opened for each resource and data source.

---

## DevOps Guru Service Design

### Resources

- `aws_devopsguru_event_sources_config` - Manages event source configurations, currently limited to enabling integration with Amazon CodeGuru Profiler.
  - https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_UpdateEventSourcesConfig.html
  - https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_DescribeEventSourcesConfig.html
- `aws_devopsguru_notification_channel` - Manages adding and removing notification channels, such as SNS topics.
  - https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_AddNotificationChannel.html
  - https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_ListNotificationChannels.html
  - https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_RemoveNotificationChannel.html
- `aws_devopsguru_resource_collection` - Manages which resource collections DevOps Guru will analyze.
  - https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_UpdateResourceCollection.html
  - https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_GetResourceCollection.html
- `aws_devopsguru_service_integration` - Manages service integrations, such as enabling logs anomaly detection.
  - https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_UpdateServiceIntegration.html
  - https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_DescribeServiceIntegration.html

### Data Sources

- `aws_devopsguru_notification_channels` - Returns a list of all configured notification channels.
  - https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_ListNotificationChannels.html
- `aws_devopsguru_resource_collection` - Returns details about the configured resource collections.
  - https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_GetResourceCollection.html
- `aws_devopsguru_resource_collection_health` - Returns details about the health of configured resource collections.
  - https://docs.aws.amazon.com/devops-guru/latest/APIReference/API_DescribeResourceCollectionHealth.html

**Comment by jar-b** [comment]
#36694 is the last of the planned resources for this service implementation. Once merged this parent meta issue will be closed. Please open a new issue for any enhancement requests or bug fixes.
