### ISSUE TITLE
Missing cloudwatchLogs option in error_action of aws_iot_topic_rule

### ISSUE THREAD

**Issue by fstephany** [hashicorp/terraform-provider-aws#17914]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The [AWS API](https://docs.aws.amazon.com/iot/latest/apireference/API_CreateTopicRule.html) lists  a `cloudwatchLogs` option for the `error_action` of a IoT Topic Rule. 

The current AWS Provider does not list this action (see [docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_topic_rule#error_action)). 

### New or Affected Resource(s)

* aws_iot_topic_rule

### Potential Terraform Configuration

```hcl
resource "aws_iot_topic_rule" "rule" {
  # Regular iot_topic_rule config

  error_action {
     cloudwatch_logs: { 
       "log_group_name": "myloggroup",
       "role_arn": "iamrole"
  }
}

```

### References

- [Full CreateTopicRule AWS API doc](https://docs.aws.amazon.com/iot/latest/apireference/API_CreateTopicRule.html)

**Comment by ewbankkit** [comment]
Closed via #23440.
