### ISSUE TITLE
Could not retrieve EC2 repository

### ISSUE THREAD

**Issue by pranavi9** [hashicorp/terraform-provider-aws#17939]
Hi,

I'm working on creating an Amazon EC2 instance through terraform code. Apparently, my code was working well until March 4 12 PM EST but, it is throwing an error now that it is unable to find the provider EC2 dependency from 'hashicorp/aws' repo. Please find the error below

`
[Archive.zip](https://github.com/hashicorp/terraform-provider-aws/files/6087114/Archive.zip)

$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 2.0.0"...
- Finding hashicorp/random versions matching "3.0.0"...
- Finding latest version of hashicorp/ec2...
- Installing hashicorp/aws v3.30.0...
- Installed hashicorp/aws v3.30.0 (signed by HashiCorp)
- Installing hashicorp/random v3.0.0...
- Installed hashicorp/random v3.0.0 (signed by HashiCorp)

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/ec2:
provider registry registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/ec2

If you have just upgraded directly from Terraform v0.12 to Terraform v0.14
then please upgrade to Terraform v0.13 first and follow the upgrade guide for
that release, which might help you address this problem.

`
Attached the TF script

Thanks,
PB

**Comment by ewbankkit** [comment]
@pranavi9 Thanks for raising this issue.

In `main.tf`

```hcl
resource "ec2_instance" "demo_ecs" {
```

should read

```hcl
resource "aws_instance" "demo_ecs" {
```

Terraform uses the stem (before the first `_`) of the resource type to determine which provider to use (so `ec2` in your case) and [Terraform 0.12 doesn't require](https://www.terraform.io/docs/language/providers/requirements.html#v0-12-compatible-provider-requirements) that all providers be listed in the `required_providers` block.
