### ISSUE TITLE
workflows: Errors labelling new issues

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#17949]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Since #17881 was merged there have been errors labelling new issues:

![Screenshot 2021-03-05 080617](https://user-images.githubusercontent.com/2404182/110119376-b96f4200-7d89-11eb-94c1-998fdb60bb51.png)

**Comment by bflad** [comment]
Adding the requested configuration generates the opposite error 🙃 

![Screen Shot 2021-03-05 at 8 29 48 AM](https://user-images.githubusercontent.com/189114/110121986-0bfe2d80-7d8d-11eb-9298-8cfa2da5432e.png)

Will get it working in a separate repository and fix it here.

**Comment by bflad** [comment]
🤦  Easy fix, just typo'd the file names.

**Comment by bflad** [comment]
All set: https://github.com/hashicorp/terraform-provider-aws/issues/17953#event-

Thank you for the heads up.
