### ISSUE TITLE
403 errors when auto_deploy is not explicitly set to True in aws_apigatewayv2_stage

### ISSUE THREAD

**Issue by VitalyAssurance** [hashicorp/terraform-provider-aws#17955]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.29
+ provider.aws v3.30.0

### Affected Resource(s)

* aws_apigatewayv2_stage

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
locals {
  app_name      = "myapp"
  stage_name    = "dev"
  function_name = "my_ws"
}
resource "aws_apigatewayv2_api" "ws_api" {
  name                       = "${local.app_name}-${local.stage_name}"
  protocol_type              = "WEBSOCKET"
  route_selection_expression = "$request.body.action"
}

resource "aws_apigatewayv2_stage" "ws_api_stage" {
  api_id      = aws_apigatewayv2_api.ws_api.id
  name        = local.stage_name
  // auto_deploy = true
}

data "aws_lambda_function" "ws_func" {
  function_name = "${local.function_name}-${local.stage_name}-websocket"
}

# Permissions to call Lambda
resource "aws_lambda_permission" "ws_func" {
  action        = "lambda:InvokeFunction"
  function_name = data.aws_lambda_function.ws_func.arn
  principal     = "apigateway.amazonaws.com"

  source_arn = "${aws_apigatewayv2_api.ws_api.execution_arn}/*/*"
}

resource "aws_apigatewayv2_integration" "ws_func" {
  api_id           = aws_apigatewayv2_api.ws_api.id
  integration_type = "AWS_PROXY"

  connection_type        = "INTERNET"
  integration_method     = "POST"
  integration_uri        = data.aws_lambda_function.ws_func.invoke_arn
  passthrough_behavior   = "WHEN_NO_MATCH"
  payload_format_version = "1.0"
}

resource "aws_apigatewayv2_route" "ws_connect" {
  api_id    = aws_apigatewayv2_api.ws_api.id
  route_key = "$connect"
  target    = "integrations/${aws_apigatewayv2_integration.ws_func.id}"
}

resource "aws_apigatewayv2_route" "ws_disconnect" {
  api_id    = aws_apigatewayv2_api.ws_api.id
  route_key = "$disconnect"
  target    = "integrations/${aws_apigatewayv2_integration.ws_func.id}"
}

resource "aws_apigatewayv2_route" "ws_message" {
  api_id    = aws_apigatewayv2_api.ws_api.id
  route_key = "$default"
  target    = "integrations/${aws_apigatewayv2_integration.ws_func.id}"
}

resource "aws_apigatewayv2_deployment" "ws" {
  api_id = aws_apigatewayv2_api.ws_api.id

  lifecycle {
    create_before_destroy = true
  }
  depends_on = [
    aws_apigatewayv2_route.ws_connect,
    aws_apigatewayv2_route.ws_disconnect,
    aws_apigatewayv2_route.ws_message
  ]
}
```

### Debug Output

https://gist.github.com/VitalyAssurance/5363bbc818a7f599c679f72153edd0f5

### Expected Behavior

Being able to connect to the newly created websockets gateway
```
> wscat -c wss://XXX.execute-api.us-east-1.amazonaws.com/dev/
Connected (press CTRL+C to quit)
>
```
### Actual Behavior

Connection fails:
```
wscat -c wss://XXX.execute-api.us-east-1.amazonaws.com/dev/
error: Unexpected server response: 403
>
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

When auto_deploy option is not specified the stage object is created but not deployed, as a result any attempts to connect through websockets fail with 403 error.

When auto_deploy option is set to True then the gateway and stage are deployed in usable condition. Either the deployment process, or documentation need to be modified to specify that this option is extremely important. That aws_apigatewayv2_stage is different from other AWS entities that even if it's created in AWS it's not usable by default.

### References

* #0000

**Comment by anGie44** [comment]
Hi @VitalyAssurance , thank you for raising this issue! Given the behavior you're seeing, I definitely agree the documentation around that argument could be more explicit as it only references "new deployment" but does not make note of usability 👍 If you'd like to make a PR with the update, I'd be happy to review it 😃
