### ISSUE TITLE
Amazon EventBridge introduces support for API Destinations

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#17950]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Amazon EventBridge now supports API Destinations, a simple and reliable way for customers to send events to any HTTP API

### New or Affected Resource(s)

* `aws_cloudwatch_event_api_destination`
* `aws_cloudwatch_event_connection`

### Potential Terraform Configuration

```hcl
resource "aws_cloudwatch_event_api_destination" ""example" {
  name                = "example-api-destination"
  connection_arn      = aws_cloudwatch_event_connection.example.arn
  invocation_endpoint = "http://example.com/"
  http_method         = "GET"
}

resource "aws_cloudwatch_event_connection" ""example" {
  name = "example-connection"

 # ...
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2021/03/amazon-eventbridge-introduces-support-for-api-destinations/).
[Blog post](https://aws.amazon.com/blogs/compute/using-api-destinations-with-amazon-eventbridge/).

Requires [AWS SDK v1.37.24](https://github.com/aws/aws-sdk-go/releases/tag/v1.37.24):

* #17934

**Comment by jordanfinners** [comment]
I have submitted a [pull request](https://github.com/hashicorp/terraform-provider-aws/pull/18905) to add API Destination and Connection resources :)

**Comment by jordanfinners** [comment]
Please can you add a 👍 to the [pull request](https://github.com/hashicorp/terraform-provider-aws/pull/18905) to help make it a priority
