### ISSUE TITLE
Error if aws_route53_query_log deleted outside of terraform - NoSuchQueryLoggingConfig

### ISSUE THREAD

**Issue by jantman** [hashicorp/terraform-provider-aws#17954]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.31.0
```

### Affected Resource(s)

* aws_route53_query_log

### Terraform Configuration Files

```hcl
provider "aws" {
  region              = "us-east-1"
}

resource "aws_cloudwatch_log_group" "log_group" {
  name              = "/aws/route53/testquerylogs"
  retention_in_days = 30
}

resource "aws_route53_query_log" "log" {
  cloudwatch_log_group_arn = aws_cloudwatch_log_group.log_group.arn
  zone_id                  = "Z05329843NO0XUPWNUWNK"
}
```

### Debug Output

https://gist.github.com/jantman/6ee4a2973afe3795381bb45a0d29be4e#file-tf-aws-provider-r53-query-bug-txt-L694-L739

### Expected Behavior

Terraform will show the query log resource as needing to be created.

### Actual Behavior

Terraform exits with an error:

```
Error: Error reading Route53 query logging configuration: NoSuchQueryLoggingConfig: The query logging configuration does not exist.
        status code: 404, request id: 849074c6-90c5-47f6-9710-c70d38e24cef
```

### Steps to Reproduce

1. `terraform apply` ; note the ID of the query log that was created
2. Delete the Hosted Zone itself from Route53, entirely.
3. `terraform plan` or `terraform apply` - either fails with an error when refreshing the resource

### Important Factoids

It looks to me like the provider isn't properly handling the ``NoSuchQueryLoggingConfig`` exception that the SDK is returning.

**Comment by ewbankkit** [comment]
Relevant code:

https://github.com/hashicorp/terraform-provider-aws/blob/0c820b1d18714eceb53ea58aebc62a6768911cdc/aws/resource_aws_route53_query_log.go#L65-L68

This resource needs a `_disappears` test.

Related:

* #13826
* #13527
* #15945
