### ISSUE TITLE
Amazon EKS now supports adding KMS envelope encryption to existing clusters

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#17952]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Amazon Elastic Kubernetes Service (EKS) now allows you to implement envelope encryption of Kubernetes secrets using AWS Key Management Service (KMS) keys for existing EKS clusters.

### New or Affected Resource(s)

* [`aws_eks_cluster`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster)

Adding [`encryption_config`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#encryption_config) to an existing cluster no longer recreates the cluster.

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2021/03/amazon-eks-supports-adding-kms-envelope-encryption-to-existing-clusters/).
[API Reference](https://docs.aws.amazon.com/eks/latest/APIReference/API_AssociateEncryptionConfig.html).

Requires [AWS SDK v1.37.20](https://github.com/aws/aws-sdk-go/releases/tag/v1.37.20):

* #17934

**Comment by voidlily** [comment]
AWS SDK has been updated so this change should now be doable

**Comment by mlopez-eb** [comment]
When I add the blocks:
```
resource "aws_kms_key" "eks" {
  description = "EKS Secret Encryption Key"
}
```
and
```
  cluster_encryption_config = [
    {
      provider_key_arn = aws_kms_key.eks.arn
      resources        = ["secrets"]
    }
  ]
```
I get the following error:
`Error: Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp [::1]:80: connect: connection refused`
As soon as I comment out the second block, my Terraform plan completes successfully.
