### ISSUE TITLE
MQ Broker Name and Security Group validations

### ISSUE THREAD

**Issue by DrFaust92** [hashicorp/terraform-provider-aws#17966]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

According to [AWS MQ Docs](https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/amazon-mq-limits.html) the `name` and `security_groups` field are missing validations

### New or Affected Resource(s)

* aws_mq_broker

**Comment by kubawi** [comment]
Hi, I opened a PR (#18088) to try to fix this issue and I would appreciate a review. It's my first attempt at contributing to this repo, so there is a fair chance I missed something, please let me know if that's the case.
