### ISSUE TITLE
Tag values are not correct on EKS Nodegroup EC2 Instances

### ISSUE THREAD

**Issue by fh-jinoa** [hashicorp/terraform-provider-aws#17961]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

0.14.7

### Affected Resource(s)

EKS Nodegroup EC2 Instance Tags

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
module "eks" {
  source                          = "terraform-aws-modules/eks/aws"
  cluster_name                    = local.cluster_name
  cluster_version                 = var.kubernetes_version
  subnets                         = module.vpc.private_subnets
  create_eks                      = true
  enable_irsa                     = true
  cluster_endpoint_private_access = true
  write_kubeconfig                = false
  tags = {
    "contact"          = "team email"
    "team"             = "team name"
    "env"              = var.environment
    "system"           = "eks"
    "compliance-hipaa" = false
    "compliance-pci"   = false
  }

  vpc_id = module.vpc.vpc_id

  node_groups = [
    {
      instance_type    = var.instance_type
      min_capacity     = var.min_instance_size
      max_capacity     = var.max_instance_size
      desired_capacity = var.desired_instance_size
      disk_size        = var.instance_disk_size
      version          = var.kubernetes_version
    }
  ]

  map_roles = [
    {
      rolearn  = data.aws_iam_role.xxxx.arn
      username = data.aws_iam_role.xxxx.id
      groups   = ["xxx"]
    }
  ]
}

```

### Debug Output

No changes

### Expected Behavior

Tags to be updated on the EC2 instances

### Actual Behavior

Tags get set with "PLACEHOLDER" instead of the correct value.  The terraform plan shows that the aws eks cluster nodes will have tags unchanged (6 of which are hidden and the ones I care about)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @fh-jinoa 👋 In looking over the reproduction example, it looks like you're using a module. I suspect that the issue may be a module issue rather than a provider issue. Can you let us know the version of both the module and AWS provider that you're using so that we can get a better idea?

**Comment by justinretzolk** [comment]
Since we haven't heard back, we'll close this issue out. If you're still experiencing issues, please feel free to open a new issue and reference this one for added context.
