### ISSUE TITLE
TF state file not processing added information and erroring out (EntityAlreadyExists)

### ISSUE THREAD

**Issue by astevenson2** [hashicorp/terraform-provider-aws#17977]
Hi there,

* When running a targeted terraform apply, errors are being produced related to EntityAlreadyExists. We've tried to solve this issue by deleting all of the aws resources and reapplying. The apply will be successful if the Entities have just been deleted however if ran locally again terraform doesn't acknowledge what should be saved in the terraform state file.
* The individual modules are ran in a shell and target applied so that the shell doesn't expire before the job is complete.
* * 2021-03-05T15:35:39.015Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing" - the debug output gives the following warning alongside various others.

-->

`Terraform v0.14.7`

-->

### Debug Output

* 2021-03-05T15:35:39.015Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing" - the debug output gives the following warning alongside various others

### Expected Behavior

* The terraform should be applied and information should be stored in the tf state file 

### Actual Behavior

* The apply runs successfully once but if you want to apply it again errors relating to EntityAlreadyExists: Duplicate names are not allowed, are produced

### Steps to Reproduce

* Please list the full steps required to reproduce the issue, for example:
1. Create shell
2. `terraform init`
3. `terraform apply`

**Comment by ewbankkit** [comment]
@astevenson2 Thanks for raising this issue.
Could you please add the configuration that is causing this?

**Comment by astevenson2** [comment]
Hi @ewbankkit, we call a module 60 times (one time per distinct client, but all of them are in the same aws account and tfstate file). This module creates an rds, ecs cluster, 2 s3 buckets, security groups, load balancer, lambda, route 53, ssm and secrets manager resources for each client.

**Comment by anGie44** [comment]
Hi @astevenson2 👋 , following up on @ewbankkit's comment above. would you be able to provide a terraform configuration of the resources listed to further investigate?  as well, if you have any additional debug output leading to the error provided in the original description that would be greatly appreciated as well 👍 

thank you in advance!
