### ISSUE TITLE
Validation check of Global Accelerator is different from AWS Console

### ISSUE THREAD

**Issue by n-osanai** [hashicorp/terraform-provider-aws#17978]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.31.0
```

### Affected Resource(s)

* aws_globalaccelerator_accelerator

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_globalaccelerator_accelerator" "example" {
  name = "test-accelerator-test-accelerator"
}
```

### Debug Output

* https://gist.github.com/n-osanai/8d9560f9df13cfe596508d701815aa31#file-tf-aws-provider-global-accelerator-bug-txt-L315-L326

### Expected Behavior

* Terraform create the accelerator with over 32 characters name.

### Actual Behavior

```
Error: expected length of name to be in the range (1 - 32), got test-accelerator-test-accelerator

  on main.tf line 3, in resource "aws_globalaccelerator_accelerator" "this":
   3:   name            = "test-accelerator-test-accelerator"
```

### Steps to Reproduce

1. only try to create global accelerator with over 32 characters name. 

### Important Factoids

* [AWS document](https://docs.aws.amazon.com/global-accelerator/latest/api/API_CreateAccelerator.html#globalaccelerator-CreateAccelerator-request-Name) says confusing sentences.
* But I examined, It seems that It can create global accelerator with up to 64 characters.
<img width="793" alt="スクリーンショット 2021-03-08 20 42 16" src="https://user-images.githubusercontent.com/65223648/110317562-aab9b100-804f-11eb-88c4-2a50b5061951.png">

* Actually, I can create 64 characters global accelerator.
<img width="1352" alt="スクリーンショット 2021-03-08 20 44 13" src="https://user-images.githubusercontent.com/65223648/110317224-2ff09600-804f-11eb-8d0b-3bce1f04ac99.png">

* I think following validation check needs to change 32 to 64
  * https://github.com/hashicorp/terraform-provider-aws/blob/366aa1dd8ae9a00364c5590c1e90fc6652dc0a13/aws/resource_aws_globalaccelerator_accelerator.go#L46

**Comment by ewbankkit** [comment]
@n-osanai Thanks for raising this issue.
The [AWS API documentation](https://docs.aws.amazon.com/global-accelerator/latest/api/API_CreateAccelerator.html#globalaccelerator-CreateAccelerator-request-Name) is self-contradictory:

![Screenshot 2021-03-08 074724](https://user-images.githubusercontent.com/2404182/110323396-8d023280-7fe2-11eb-90e2-05085a845cd8.png)

I'll correct the max. length to `255` (and double check the other attributes).

**Comment by chkelly** [comment]
My team just ran into the 32 character limitation when attempting to import our production global accelerator instances which have a name that exceeds 32 characters. 

I reached out to our AWS TAM around the contradictory nature of the docs and they have escalated to the service team to hopefully get them corrected.

Based on our testing the Max length of 255 seems to be the actual limitation that is enforced.

**Comment by ewbankkit** [comment]
Related:

* https://github.com/hashicorp/terraform-provider-aws/pull/17739

**Comment by e-moshaya** [comment]
We just hit the same issue. The name can have a maximum of 64 characters, must contain only alphanumeric characters, periods (.), or hyphens (-), and must not begin or end with a hyphen or period. You can check the API documentation here: https://docs.aws.amazon.com/global-accelerator/latest/api/API_CreateAccelerator.html#API_CreateAccelerator_RequestSyntax

**Comment by e-moshaya** [comment]
@ewbankkit The actual max length is 64 and not 255. Please can you amend your PR?
