### ISSUE TITLE
workflows: Investigate Single Sources of Truth for Maintainers and Service Maintainer Usernames

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#17986]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Some of our GitHub Actions based workflows are based on knowing whether the issue or pull request author is a collaborator. Currently, we hardcode this list as JSON strings of usernames, but it would be great if this was based on a single source file so multiple workflows did not need to be updated.

**Comment by lorengordon** [comment]
Fwiw, if it helps, many github events seem to have an author_association attribute that contains this data. I've used it with comments, in particular, but it's also available for at least pull requests. Worth checking if it's available for issues, also.
