### ISSUE TITLE
aws_kms_key.by_alias does not allow key_id when value begins 'aws'

### ISSUE THREAD

**Issue by simonB2020** [hashicorp/terraform-provider-aws#17999]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.20
+ provider.archive v2.1.0
+ provider.aws v2.70.0

### Affected Resource(s)

* aws_kms_key

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "aws_kms_key" "by_alias" {
  key_id = "aws/s3"
}
```

### Debug Output

`Error: "key_id" must be one of the following patterns: [A-Za-z0-9-]+, arn:[^:]+:kms:[^:]+:[^:]+:key/[A-Za-z0-9-]+, alias/[a-zA-Z0-9:/_-]+ or arn:[^:]+:kms:[^:]+:[^:]+:alias/[a-zA-Z0-9:/_-]+`

### Expected Behavior

Block should reference the KMS alias stated.

### Actual Behavior

Does not allow specifying an alias beginning with the string "aws"

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ewbankkit** [comment]
@simonB2020 Thanks for raising this issue.
Use of a key alias requires specifying `alias/` as a prefix for `key_id`.

```hcl
data "aws_kms_key" "by_alias" {
  key_id = "alias/aws/s3"
}
```

should work.
