### ISSUE TITLE
delete_on_termination default does not apply if aws_instance does not contain root_block_device section

### ISSUE THREAD

**Issue by ColinScott** [hashicorp/terraform-provider-aws#1800]
### Terraform Version
0.10.7

### Affected Resource(s)
- aws_instance

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "ap-southeast-2"
}

resource "aws_instance" "test1" {
  ami = "ami-24959b47"
  instance_type = "t2.micro"
  subnet_id = ""

  root_block_device {
    delete_on_termination = true
  }

  tags {
    Name = "Test 1"
  }
}

resource "aws_instance" "test2" {
  ami = "ami-24959b47"
  instance_type = "t2.micro"
  subnet_id = ""

  root_block_device {}

  tags {
    Name = "Test 2"
  }
}

resource "aws_instance" "test3" {
  ami = "ami-24959b47"
  instance_type = "t2.micro"
  subnet_id = ""

  tags {
    Name = "Test 3"
  }
}

```

### Expected Behavior
All three instances should have delete on terminate set to true on the root block device.

### Actual Behavior
Only the instances where root_block_device is specified have their root device set to delete on terminate set to true. Test 3 has this set to false. This is inconsistent and unexpected behaviour given the documentation lists the default as true.

### Steps to Reproduce
1. Insert a subnet ID
2. `terraform apply`

### Important Factoids
This doesn't happen using AWS Linux (ami-30041c53 specifically). This attaches as /dev/xvda. The failing instance attaches the block device as /dev/sda1. In the details of these AMIs the block device for AWS Linux is specified as "/dev/xvda=snap-01be861ac05e22c46:8:true:gp2" and that for the CentOS image is specified as "/dev/sda1=snap-0a295cebd9d323dc2:8:false:standard". This suggests that when the root_block_device section is not specified is uses a default value from the AMI. This seems at odds with the documentation which specifies the default is true and also the behaviour when the block is present but empty. It is not obvious from the documentation that the defaults for this block are not used if it is excluded.

**Comment by chris-kiick-sp** [comment]
Still seeing same issue on Terraform v0.11.8.
