### ISSUE TITLE
aws_kinesis_firehose_delivery_stream does not allow default S3 encryption

### ISSUE THREAD

**Issue by simonB2020** [hashicorp/terraform-provider-aws#18001]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.20
+ provider.archive v2.1.0
+ provider.aws v2.70.0

### Affected Resource(s)

* aws_kinesis_firehose_delivery_stream

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_kinesis_firehose_delivery_stream" "stream" {
    name        = "ap-fhse-cloudwatch${local.ap_suffix}"
    destination = "extended_s3"
    server_side_encryption {
        enabled = true
        key_type = "AWS_OWNED_CMK"         
    }

    extended_s3_configuration {
        role_arn   = aws_iam_role.firehose_role.arn
        bucket_arn = data.aws_s3_bucket.meta_bucket.arn
        prefix = "cloudwatch/"
        error_output_prefix = "cloudwatcherr/"
        buffer_size = 5
        buffer_interval = 300
        compression_format = "UNCOMPRESSED"
        #kms_key_arn = data.aws_kms_key.by_alias.arn

        processing_configuration {
            enabled = "true"
            processors {
                type = "Lambda"
                parameters {
                    parameter_name  = "LambdaArn"
                    parameter_value = "${aws_lambda_function.cloudwatch_hose_processing.arn}:$LATEST"
                }
                parameters {
                    parameter_name  = "NumberOfRetries"
                    parameter_value = 3
                }
                parameters {
                    parameter_name  = "RoleArn"
                    parameter_value = aws_iam_role.firehose_role.arn
                }
                parameters {
                    parameter_name  = "BufferSizeInMBs"
                    parameter_value = 3
                }
                parameters {
                    parameter_name  = "BufferIntervalInSeconds"
                    parameter_value = 60
                }
            }
        }
        cloudwatch_logging_options{
            enabled = true
            log_group_name = "/aws/kinesisfirehose/to_s3_delivery_stream"
            log_stream_name = "S3Delivery"
        }
    }

    tags = merge(
        local.tags,
        {
            Name = "ap-rle-cloudwatch_firehose_s3${local.environment_short}",
            Description = "Role for CloudWatch Firehose to put to s3"
        }
    )
}
```

### Debug Output

```
Error: Unsupported argument

  on firehose.tf line 6, in resource "aws_kinesis_firehose_delivery_stream" "stream":
   6:         key_type = "AWS_OWNED_CMK" 
```

### Expected Behavior

On apply, the Delivery Stream should be built with configuration for SSE S3 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream

### Actual Behavior

Terraform does not recognise the parameter "key_type"

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by anGie44** [comment]
Hi @simonB2020, thank you for raising this issue. unfortunately, `key_type` is not available in the version of the Terraform AWS Provider you've referenced (v2.70.0). See documentation specific to that version: https://registry.terraform.io/providers/hashicorp/aws/2.70.0/docs/resources/kinesis_firehose_delivery_stream#server_side_encryption). 
The argument was introduced in `v3.7.0` of the Terraform AWS Provider so an upgrade would be needed. 

If you have any additional questions, please reach out!
