### ISSUE TITLE
Amazon EFS now supports single Availability Zone storage classes

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#18016]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Amazon Elastic File System (Amazon EFS) now supports single Availability Zone (AZ) storage classes (One Zone).

### New or Affected Resource(s)

* [`aws_efs_file_system`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_file_system)

### Potential Terraform Configuration

```hcl
resource "aws_efs_file_system" "example" {
  availability_zone_name = "us-west-2b"
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2021/03/introducing-lower-cost-storage-classes-for-amazon-elastic-file-system/).
[Blog post](https://aws.amazon.com/blogs/aws/new-lower-cost-one-zone-storage-classes-for-amazon-elastic-file-system/).
[User Guide](https://docs.aws.amazon.com/efs/latest/ug/storage-classes.html).

Requires [AWS SDK v1.37.27](https://github.com/aws/aws-sdk-go/releases/tag/v1.37.27):

* #18012

**Comment by shuheiktgw** [comment]
I've started working on this PR

**Comment by shuheiktgw** [comment]
Added the support!: https://github.com/hashicorp/terraform-provider-aws/pull/18319
