### ISSUE TITLE
Data sources for Network Firewall

### ISSUE THREAD

**Issue by Omarimcblack** [hashicorp/terraform-provider-aws#18026]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* `(data) aws_networkfirewall_firewall`
* `(data) aws_networkfirewall_firewall_policy`
* `(data) aws_networkfirewall_resource_policy`
* `(data) aws_networkfirewall_rule_group`

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/16270

**Comment by LuigiClemente-Awin** [comment]
Yes, please, this is important to decouple the vpc module from the firewall module.

**Comment by phwelo** [comment]
this is slowing me down at the moment, was surprised to find them missing
