### ISSUE TITLE
Unable to update CloudTrail tags with Terraform CLI

### ISSUE THREAD

**Issue by rchildress87** [hashicorp/terraform-provider-aws#18027]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
% terraform -version
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.31.0
```
### Affected Resource(s)

* aws_cloudtrail

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_cloudtrail" "sample" {
  cloud_watch_logs_group_arn    = "arn:aws:logs:us-east-1:123456789000:log-group:cust-cloudtrail-prd:*"
  cloud_watch_logs_role_arn     = "arn:aws:iam::123456789000:role/cust-cloudtrail-prd"
  enable_log_file_validation    = true
  is_multi_region_trail         = true
  kms_key_id                    = "arn:aws:kms:us-east-1:123456789000:key/1a2b3c4d-1a2b-1a2b-1a2b-1a2b3c4d5e6f"
  name                          = "cust-trail-prd"
  s3_bucket_name                = "cust-cloudtrail-prd"
  sns_topic_name                = "cust-cloudtrail-prd"
  tags                          = {
    "Developer"   = "StratusGrid",
    "Environment" = "prd",
    "Name"        = "cust-trail-prd",
    "Provisioner" = "Terraform",
    "SourceRepo"  = "cust-account-prd",
    "Terraform"   = "true",
  }
}
```

### Debug Output

[https://gist.github.com/rchildress87/286bd2af5f8be8105193682019c44e66](
https://gist.github.com/rchildress87/286bd2af5f8be8105193682019c44e66)

### Panic Output

None

### Expected Behavior

The CloudTrail resource tag "Terraform" should be updated in-place from `true` to `false`.
### Actual Behavior

```
% terraform apply
aws_cloudtrail.sample: Refreshing state... [id=cust-trail-prd]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_cloudtrail.sample will be updated in-place
  ~ resource "aws_cloudtrail" "sample" {
        id                            = "cust-trail-prd"
        name                          = "cust-trail-prd"
      ~ tags                          = {
          ~ "Terraform"   = "true" -> "false"
            # (5 unchanged elements hidden)
        }
        # (12 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_cloudtrail.sample: Modifying... [id=cust-trail-prd]

Error: Error updating CloudTrail: AccessDeniedException: User: arn:aws:sts::123456789000:assumed-role/cust-restricted-admin-role/botocore-session-1615395086 is not authorized to perform: cloudtrail:UpdateTrail on resource: arn:aws:cloudtrail:us-east-1:123456789000:trail/cust-trail-prd
	status code: 400, request id: 1a2b3c4d-1a2b-1a2b-1a2b-1a2b3c4d5e6f

  on main.tf line 4, in resource "aws_cloudtrail" "sample":
   4: resource "aws_cloudtrail" "sample" {

```

### Steps to Reproduce

1. Import or create a CloudTrail resource.
2. While assuming a role with `cloudtrail:AddTags` and `cloudtrail:RemoveTags` actions but without the `cloudtrail:UpdateTrail` action, attempt to change an existing tag on the resource.

### Important Factoids

I am able to update the tag in the AWS Resource Groups Tag Editor with only the `cloudtrail:AddTags` and `cloudtrail:RemoveTags` actions. `cloudtrail:UpdateTrail` does not seem to be required.

### References

None

**Comment by ewbankkit** [comment]
`UpdateTrail` is being called even if only `tags` have been updated:

https://github.com/hashicorp/terraform-provider-aws/blob/19b732b11d48b226029976b2e6c051f75705bcb4/aws/resource_aws_cloudtrail.go#L378-L407

**Comment by rchildress87** [comment]
Thanks for the quick triaging @ewbankkit

**Comment by ewbankkit** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/21882.
