### ISSUE TITLE
Tags support for `aws_fms_policy`

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#18037]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add tag support for `aws_fms_policy`

### New or Affected Resource(s)

* aws_fms_policy

### Potential Terraform Configuration

```hcl
resource "aws_fms_policy" "example" {
  tags = {
    Tag1 = "TagValue"
  }
}
```

**Comment by Victorp99** [comment]
Hello! I would like to work on this enhancement!
