### ISSUE TITLE
Beanstalk using Shared Load Balancer - Does not work

### ISSUE THREAD

**Issue by sanflores** [hashicorp/terraform-provider-aws#18030]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.29
+ provider.aws v3.31.0
+ provider.null v2.1.2
+ provider.tls v2.1.0

Your version of Terraform is out of date! The latest version
is 0.14.7. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

aws_elastic_beanstalk_environment

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```
resource "aws_elastic_beanstalk_environment" "beanstalk" {
  name                = var.app_name
  application         = var.application
  solution_stack_name = var.solution_stack
  tier                = var.tier
  setting {
    name      = "LoadBalancerType"
    namespace = "aws:elasticbeanstalk:environment"
    resource  = ""
    value     = "application"
  }
  setting{
    name = "LoadBalancerIsShared"
    namespace = "aws:elasticbeanstalk:application:environment"
    resource  = ""
    value = "true"
  }
  setting{
    name = "SharedLoadBalancer"
    namespace = "aws:elbv2:loadbalancer"
    resource  = ""
    value = data.terraform_remote_state.shared.outputs.shared_elb_arn
  }  
  setting {
    name      = "IamInstanceProfile"
    namespace = "aws:autoscaling:launchconfiguration"
    resource  = ""
    value     = var.rol
  }
  tags = {
    Terraform   = "true"
    Environment = terraform.workspace
    VPC         = var.root_workspace
  }
}


resource "aws_lb" "shared_elb" {
  name               = "shared-elb-${terraform.workspace}"
  internal           = false
  load_balancer_type = "application"
  security_groups    = [aws_security_group.http.id]
  subnets                    = flatten([module.vpc.public_subnets])
  enable_deletion_protection = true
  tags = {
    Terraform   = "true"
    Environment = "${terraform.workspace}-VPC"
    VPC         = terraform.workspace
  }
}
```

### Expected Behavior

A new elastic beanstalk is created using a shared Load Balancer

### Actual Behavior

A new elastic beanstalk is created with a new load balancer

### Steps to Reproduce

Create a load balancer and an elastic beanstalk configuring shared load balancer (beanstalk code above)

**Comment by boneheaded-bat** [comment]
@sanflores -- try changing this block:
```
  setting{
    name = "LoadBalancerIsShared"
    namespace = "aws:elasticbeanstalk:application:environment"
    resource  = ""
    value = "true"
  }
```

It works for me with the namespace set to "aws:elasticbeanstalk:environment" (i.e. no 'application'). Naming the environment is still a challenge, though...

**Comment by breathingdust** [comment]
Hi @sanflores 👋  Did @boneheaded-bat 's suggestion work for you?

**Comment by sanflores** [comment]
> Hi @sanflores 👋 Did @boneheaded-bat 's suggestion work for you?

Yes it worked!
