### ISSUE TITLE
Lakeformation permission for external account access fails validation

### ISSUE THREAD

**Issue by vadivelselvaraj** [hashicorp/terraform-provider-aws#18034]
When sharing glue catalog database or tables with external AWS accounts, the principal argument for the AWS LakeFormation Permissions API should accept a valid AWS account ID. Currently, only a valid AWS role or user ARN is accepted and a code like the below would fail because of this validation.

```hcl
resource "aws_lakeformation_permissions" "high_fidelity_db_external_access" {
  principal = "259712912613"
  permissions = ["SELECT"]
  permissions_with_grant_option = ["SELECT"]

  database {
    name = aws_glue_catalog_database.sample_db.name
  }
}
```
**ValidationError:** `Error: "principal" doesn't look like a user or role: "259712912613"`

The validation for the `principal` argument is done [here](https://github.com/hashicorp/terraform-provider-aws/blob/7ca26150c9a702cd40f21c05b25eab753ec5a216/aws/resource_aws_lakeformation_permissions.go#L104) and needs to be changed to allow AWS account ID as valid input.

Additionally, the `principal` argument can also be an organization as can be seen [here](https://docs.aws.amazon.com/lake-formation/latest/dg/lf-permissions-reference.html).

**Comment by chrisbulgaria** [comment]
Hi , this is the same as https://github.com/hashicorp/terraform-provider-aws/issues/16848
And the linked pull request fixes it . Just needs to be merged . Maybe add a vote there such that it has a chance to receive attention ?
Thanks ,
Chris

**Comment by YakDriver** [comment]
| Additional Principals | Perm Delete/Revoke |
| --- | --- |
| Related #16848 (Issue)<br/>Related #16916<br/>Related #18034 (Issue)<br/>Related #18374 | Related #17633 (Issue)<br/>Related #18446 (Issue)<br/>Related #18505<br/>Related #19063 (Issue)<br/>Related #19064 (Issue) |
