### ISSUE TITLE
aws_ecrpublic_repository works only with us-east-1 region

### ISSUE THREAD

**Issue by Vrtak-CZ** [hashicorp/terraform-provider-aws#18047]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/aws v3.31.0
```

### Affected Resource(s)

* aws_ecrpublic_repository

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  region  = "eu-central-1"
}

resource "aws_ecrpublic_repository" "example" {
  repository_name = "example"
}
```

### Expected Behavior

Repository will be created

### Actual Behavior

```
Error: error reading ECR Public repository: RequestError: send request failed
caused by: Post "https://api.ecr-public.eu-central-1.amazonaws.com/": dial tcp: lookup api.ecr-public.eu-central-1.amazonaws.com on 1.1.1.1:53: no such host
```

### Steps to Reproduce

Just use this resource with non `us-east-1` region provider.

1. `terraform apply`

### References

* https://docs.aws.amazon.com/general/latest/gr/ecr-public.html

**Comment by Vrtak-CZ** [comment]
possible workaround

```hcl
provider "aws" {
  alias = "us_east_1"

  region  = "eu-central-1"
}

resource "aws_ecrpublic_repository" "example" {
  provider = aws.us_east_1

  name = "example"
}
```

**Comment by anGie44** [comment]
Hi @Vrtak-CZ, thank you for raising this issue and apologies you came across. looking at the error message you've provided, it occurs at read time, so I'm curious did that occur by trying to import an existing repository or it was possible to successfully create the repo but reading it back during the apply caused the error?

**Comment by Vrtak-CZ** [comment]
Hi @anGie44 thanks for response.

> read time, so I'm curious did that occur by trying to import an existing repository or it was possible to successfully create the repo but reading it back during the apply caused the error? 

Yes this error is reported when i try to import resource. But creating new repository also fails.

> Since this looks like an upstream behavior, i think the best thing we can do in the meantime until AWS perhaps adds additional region endpoints, is to make a note in the documentation that the resource is currently only available in `us-east-1`.

I think adding note to documentation should be enough.

**Comment by andormarkus** [comment]
> possible workaround
> 
> ```terraform
> provider "aws" {
>   alias = "us_east_1"
> 
>   region  = "eu-central-1"
> }
> 
> resource "aws_ecrpublic_repository" "example" {
>   provider = aws.us_east_1
> 
>   repository_name = "example"
> }
> ```

Did not work for me.
