### ISSUE TITLE
aws_cognito_user_pool_client - missing granular token validity configuration options

### ISSUE THREAD

**Issue by jono85** [hashicorp/terraform-provider-aws#18049]
Hello,
I've been using terraform for 2 years now very happy on AWS. One of the services we use is Cognito and it's user pool app clients.

Recently AWS finally added an option to configure the TTL expiration for different token types. Previously you could only set the TTL for the refresh token in number of days.
Now you can configure TTL for Refresh token (1-365 days), Access token (5 min - 1 day) and ID token (5 min - 1 day). 

Can the resource be updated to allow configuration of these TTL settings through terraform?

![image](https://user-images.githubusercontent.com/58177631/110800582-3ca20380-8274-11eb-864b-fb62d7b90355.png)

**Comment by danielwhite** [comment]
Does https://github.com/hashicorp/terraform-provider-aws/issues/14935 address this issue?

**Comment by jono85** [comment]
yes, thank you!

**Comment by DrFaust92** [comment]
Closed by #14935
