### ISSUE TITLE
Terraform state leaks on interrupt

### ISSUE THREAD

**Issue by ialidzhikov** [hashicorp/terraform-provider-aws#18051]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -version
Terraform v0.12.26
+ provider.aws v3.18.0
```

### Affected Resource(s)

* aws_vpc

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  access_key = var.ACCESS_KEY_ID
  secret_key = var.SECRET_ACCESS_KEY
  region     = "eu-west-1"
  version    = "3.18.0"
}

resource "aws_vpc" "vpc" {
    cidr_block           = "10.250.0.0/16"
    enable_dns_support   = true
    enable_dns_hostnames = true

    tags = {
      Name = "deleteme"
    }
}
```

### Expected Behavior

I would expect when I interrupt a running `terraform apply` process, no terraform state to be leaked.

### Actual Behavior

When you interrupt a running  `terraform apply` process, the resource is actually being created but not saved in the terraform state.

### Steps to Reproduce

1. Run `terraform apply`

```
$ terraform apply -var-file=creds.tfvars --auto-approve
```

2. Interrupt with ^C as soon as you see that the VPC is being created.

```
$ terraform apply -var-file=creds.tfvars --auto-approve
aws_vpc.vpc: Creating...
^CInterrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...
Stopping operation...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

3. Checkout the cloudprovider and see that the requested VPC is created and it is not saved in the terraform state

```
$ aws ec2 describe-vpcs --output=json

        {
            "CidrBlock": "10.250.0.0/16",
            "DhcpOptionsId": "dopt-ab0f2ecc",
            "State": "available",
            "VpcId": "vpc-05866c95df657d7ac",
            "InstanceTenancy": "default",
            "CidrBlockAssociationSet": [
                {
                    "AssociationId": "vpc-cidr-assoc-0587023f907f7e62e",
                    "CidrBlock": "10.250.0.0/16",
                    "CidrBlockState": {
                        "State": "associated"
                    }
                }
            ],
            "IsDefault": false,
            "Tags": [
                {
                    "Key": "Name",
                    "Value": "deleteme"
                }
            ]
        },
```

### References

* #0000

**Comment by ewbankkit** [comment]
@ialidzhikov Thanks for raising this issue.
I think consistent behavior on cancellation requires #4177 and #15090.
Let's leave this one open for now as an explicit use case.
