### ISSUE TITLE
Pinpoint email friendly sender name not controlled by terraform.

### ISSUE THREAD

**Issue by mbelang** [hashicorp/terraform-provider-aws#18050]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The email channel Friendly Sender Name cannot be controlled by terraform with `aws_pinpoint_email_channel` resource. We would like to have an additional optional parameter to be able to set it via terraform resource.

### New or Affected Resource(s)

* aws_pinpoint_email_channel

### Potential Terraform Configuration

```hcl
resource "aws_pinpoint_email_channel" "email" {
  application_id = aws_pinpoint_app.my_app.application_id
  from_address   = "support@example.com"
  friendly_sender_name = "Example Support Friendly Name"
  identity       = var.ses_domain_identity_arn
  role_arn       = aws_iam_role.my_app.arn
}

```

**Comment by anGie44** [comment]
Hi @mbelang, thank you raising this issue. At the moment, I don't see that parameter currently supported by the AWS Pinpoint EmailChanelRequest as seen here https://docs.aws.amazon.com/pinpoint/latest/apireference/apps-application-id-channels-email.html#apps-application-id-channels-email-properties, so we're blocked atm by the upstream service.  You may want to create a feature request with AWS specifically and once that is available from the AWS SDK Go, we'll be able to support the parameter w/in the provider resource.

**Comment by mbelang** [comment]
@anGie44 TIL, if you do `from_address   = "Friendly Name<support@example.com>"` it works. This is kinda obvious but it is not documented....

**Comment by anGie44** [comment]
Interesting, thanks for the update @mbelang! must be using formatting defined in [RFC 5399](https://www.ietf.org/rfc/rfc5322.txt) like when using SES. our documentation could include this example in the argument definition if it helps others 👍
