### ISSUE TITLE
aws_subnet_ids data source updated to not require vpc_id

### ISSUE THREAD

**Issue by FireballDWF** [hashicorp/terraform-provider-aws#18060]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

aws_subnet_ids data source modified so the vpc_id argument is not required.  The DescribeSubnets API call does not require vpc_id to be specified.  Use case is want to return all subnets (regardless of vpc_id) which match a filter condition, in this case OutpostArn=value.  Then use those subnets arns in a policy to deny launching in any subnet which is not an located on an Outpost, thus implementing a preventative control to enforce data residency

### New or Affected Resource(s)

* aws_subnet_ids

### References

* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeSubnets.html

**Comment by ewbankkit** [comment]
Not sure whether removing `vpc_id` would be a breaking change.
Maybe we can take the opportunity to introduce a new data source `aws_subnets` (which conforms to the [preferred naming](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/provider-design.md#plural-data-sources)), without the `vpc_id` attribute, and deprecate `aws_subnet_ids`?

**Comment by FireballDWF** [comment]
I would be fine with a new data source
