### ISSUE TITLE
Inconsistency between documentation and schema (aws_lb_listener_rule)

### ISSUE THREAD

**Issue by mrysbekov** [hashicorp/terraform-provider-aws#18072]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.30
+ provider.aws v3.32.0

### Affected Resource(s)

* aws_lb_listener_rule

### Terraform Configuration Files

irrelevant

### Debug Output

Error: List shorter than MinItems

### Panic Output

irrelevant

### Expected Behavior

According to the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_rule#target_group) the forward block is required to have "One or more target groups block".
Furthermore, it is even [stated](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_rule#forward) that it can have **exactly one** target block: "[..]you can specify only one target group using forward [...]"

### Actual Behavior

An error is thrown: "Error: List shorter than MinItems"

### Steps to Reproduce

AWS provider schema (fetched via ```terraform providers schema -json```) defines ```"min_items": 2``` for the target_group block. This is inconsistent with the writings in the documentation and should be harmonized.

### References

* This has already been [fixed](https://github.com/hashicorp/terraform-provider-aws/pull/15112) for "aws_lb_listener" resource in provider.aws v3.31.0.

**Comment by don-code** [comment]
I've been running a fork of the provider with a fix for this (and other) bugs for some time now. Some other bugs in ALB and CloudFront resources have all since been fixed, other than this one, so I'm trying to upstream the one remaining change in #19806.
