### ISSUE TITLE
Data source to read DMS subnet group

### ISSUE THREAD

**Issue by sunkaraamrutha** [hashicorp/terraform-provider-aws#18073]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am trying to find a way to read the dms subnet group instead of creating it everytime i create a replication instance in effort to standardize subnet group use. We are currently on terraform 0.12.28 version. 

### New or Affected Resource(s)

* aws_dms_replication_subnet_group
```hcl
data "aws_dms_replication_subnet_group" "common_subnet_group" {
  # name = "dre-dms-common-${var.dre_common_lookup_role}-${var.dre_common_lookup_environment}-${var.region}-subnet"
  name = "${var.tgt_env}-dms-replication-subnet-group-tf"
}
```

### References
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/prefix_list

**Comment by ewbankkit** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/30832.
