### ISSUE TITLE
Documentation about aws_dms_replication_instance seems wrong regarding replication_subnet_group_id

### ISSUE THREAD

**Issue by Imanuel-Mizrahi** [hashicorp/terraform-provider-aws#18086]
Inside the docs of [aws_dms_replication_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_replication_instance), there seems to be a mistake.
For the parameter: "replication_subnet_group_id", the value is: `aws_dms_replication_subnet_group.test.id.`
However, inside the docs for "[aws_dms_replication_subnet_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_replication_subnet_group)", there is no 'id' field at all!
I guess that the value should be: "replication_subnet_group_id" instead, as this one is a required field for aws_dms_replication_subnet_group.

**Comment by anGie44** [comment]
Hi @Imanuel-Mizrahi , thank you raising this issue.  While the `aws_dms_replication_instance` resource documentation is correct to reference the `aws_dms_replication_subnet_group.test.id`, you've raised a good point in that the `aws_dms_replication_subnet_group` documentation is missing details on the `id` attribute, which happens to be the `replication_subnet_group_id` as seen here:
 https://github.com/hashicorp/terraform-provider-aws/blob/078a334a6db220dc9b4e784c6872c75055299475/aws/resource_aws_dms_replication_subnet_group.go#L72

Adding a row with the `id` attribute in the documentation should fix this 👍

**Comment by Imanuel-Mizrahi** [comment]
Thank you @anGie44 !!
So, now I come to the part how it all began...
I was using this TF template, based on the docs:

```
resource "aws_dms_replication_subnet_group" "test" {
  replication_subnet_group_description = "Test replication subnet group"
  replication_subnet_group_id          = "test-dms-replication-subnet-group-tf"

  subnet_ids = [
    aws_subnet.nondefault_1.id,
    aws_subnet.nondefault_2.id
  ]

  tags = {
    Name = "test"
  }
}

resource "aws_dms_replication_instance" "test" {
  allocated_storage            = 20
  apply_immediately            = true
  auto_minor_version_upgrade   = true
  multi_az                     = true
  preferred_maintenance_window = "sun:10:30-sun:14:30"
  publicly_accessible          = true
  replication_instance_class   = "dms.t2.micro"
  replication_instance_id      = "test-dms-replication-instance-tf"
  replication_subnet_group_id  = aws_dms_replication_subnet_group.test.id

  tags = {
    Name = "test"
  }
```
I was sure that the "terraform plan" will import the replication_subnet_group_id from the "aws_dms_replication_subnet_group" resource, so the "aws_dms_replication_instance" resource will show it as the actual name ("test-dms-replication-subnet-group-tf"), once I run the plan.
However, the result was:
```
Terraform will perform the following actions:

  # aws_dms_replication_instance.test will be created
  + resource "aws_dms_replication_instance" "test" {
      + allocated_storage                = 20
      + apply_immediately                = true
      + auto_minor_version_upgrade       = true
      + availability_zone                = (known after apply)
      + engine_version                   = (known after apply)
      + id                               = (known after apply)
      + kms_key_arn                      = (known after apply)
      + multi_az                         = true
      + preferred_maintenance_window     = "sun:10:30-sun:14:30"
      + publicly_accessible              = true
      + replication_instance_arn         = (known after apply)
      + replication_instance_class       = "dms.t2.micro"
      + replication_instance_id          = "test-dms-replication-instance-tf"
      + replication_instance_private_ips = (known after apply)
      + replication_instance_public_ips  = (known after apply)
      + replication_subnet_group_id      = (known after apply)
      + tags                             = {
          + "Name" = "test"
        }
      + vpc_security_group_ids           = (known after apply)
    }
```
Note that replication_subnet_group_id **will only be known after apply**.

Now, if I change the TF to use the ```
replication_subnet_group_id from resource "aws_dms_replication_subnet_group", as follows:
resource "aws_dms_replication_instance" "test" {
  allocated_storage            = 20
  apply_immediately            = true
  auto_minor_version_upgrade   = true
  multi_az                     = true
  preferred_maintenance_window = "sun:10:30-sun:14:30"
  publicly_accessible          = true
  replication_instance_class   = "dms.t2.micro"
  replication_instance_id      = "test-dms-replication-instance-tf"
  replication_subnet_group_id  = aws_dms_replication_subnet_group.test.replication_subnet_group_id

  tags = {
    Name = "test"
  }

}
```

The plan result is as expected, and the data is imported:
```
Terraform will perform the following actions:

  # aws_dms_replication_instance.test will be created
  + resource "aws_dms_replication_instance" "test" {
      + allocated_storage                = 20
      + apply_immediately                = true
      + auto_minor_version_upgrade       = true
      + availability_zone                = (known after apply)
      + engine_version                   = (known after apply)
      + id                               = (known after apply)
      + kms_key_arn                      = (known after apply)
      + multi_az                         = true
      + preferred_maintenance_window     = "sun:10:30-sun:14:30"
      + publicly_accessible              = true
      + replication_instance_arn         = (known after apply)
      + replication_instance_class       = "dms.t2.micro"
      + replication_instance_id          = "test-dms-replication-instance-tf"
      + replication_instance_private_ips = (known after apply)
      + replication_instance_public_ips  = (known after apply)
      + replication_subnet_group_id      = "test-dms-replication-subnet-group-tf"
      + tags                             = {
          + "Name" = "test"
        }
      + vpc_security_group_ids           = (known after apply)
    }
```

I am pretty new with github, should I create a new issue for this...?

Appreciate your assistance @anGie44 !!

**Comment by Imanuel-Mizrahi** [comment]
Turns out this behavior changes, depends on the terraform version you use.
So, using v0.12.30 the plan include the information correctly.
I think that initially, I was running with a higher version while experiencing the issue with the plan version 14 I think.
