### ISSUE TITLE
aws_dynamodb_table: Global Secondary Index capacity changes are not applied

### ISSUE THREAD

**Issue by Madh93** [hashicorp/terraform-provider-aws#18095]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

    Terraform v0.13.5
    + provider registry.terraform.io/hashicorp/aws v3.32.0

### Affected Resource(s)

    aws_dynamodb_table

### Terraform Configuration Files

```hcl
resource "aws_dynamodb_table" "this" {
  name           = "test_table"
  billing_mode   = "PROVISIONED"
  read_capacity  = 1
  write_capacity = 1
  hash_key       = "UserId"
  range_key      = "GameTitle"

  attribute {
    name = "UserId"
    type = "S"
  }

  attribute {
    name = "GameTitle"
    type = "S"
  }

  attribute {
    name = "TopScore"
    type = "N"
  }

  global_secondary_index {
    name               = "GameTitleIndex"
    hash_key           = "GameTitle"
    range_key          = "TopScore"
    projection_type    = "INCLUDE"
    non_key_attributes = ["UserId"]
    read_capacity      = 1
    write_capacity     = 1  ### Update this value
  }
}
```

### Terraform Plan

```hcl
  # aws_dynamodb_table.this will be updated in-place
  ~ resource "aws_dynamodb_table" "this" {
        arn            = "arn:aws:dynamodb:us-east-1:000000000000:table/test_table"
        billing_mode   = "PROVISIONED"
        hash_key       = "UserId"
        id             = "test_table"
        name           = "test_table"
        range_key      = "GameTitle"
        read_capacity  = 1
        stream_enabled = false
        tags           = {}
        write_capacity = 1

        attribute {
            name = "GameTitle"
            type = "S"
        }
        attribute {
            name = "TopScore"
            type = "N"
        }
        attribute {
            name = "UserId"
            type = "S"
        }

      - global_secondary_index {
          - hash_key           = "GameTitle" -> null
          - name               = "GameTitleIndex" -> null
          - non_key_attributes = [
              - "UserId",
            ] -> null
          - projection_type    = "INCLUDE" -> null
          - range_key          = "TopScore" -> null
          - read_capacity      = 1 -> null
          - write_capacity     = 1 -> null
        }
      + global_secondary_index {
          + hash_key           = "GameTitle"
          + name               = "GameTitleIndex"
          + non_key_attributes = [
              + "UserId",
            ]
          + projection_type    = "INCLUDE"
          + range_key          = "TopScore"
          + read_capacity      = 1
          + write_capacity     = 2
        }

        point_in_time_recovery {
            enabled = false
        }

        ttl {
            enabled = false
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
### Expected Behavior

Update the `write_capacity` value from `1` to `2` for the `GameTitleIndex` global secondary index when I run `terraform apply`.

### Actual Behavior

The change is not applied. So in the next rerun I get the same change to apply.

### Steps to Reproduce

1. Modify `read_capacity` or `write_capacity` values of the global secondary index
2. `terraform apply`
3. `terraform apply` (same result)

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/9671 (similiar but not the same)

**Comment by bill-rich** [comment]
The root of this problem is the same as in #9671. I'm going to close this issue, so we can track it there. This will be helpful to have an extra example.
