### ISSUE TITLE
customer_owned_ipv4_pool does not support static public ips to use in eip resource?

### ISSUE THREAD

**Issue by eduda** [hashicorp/terraform-provider-aws#18105]
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eip

not sure if this is a bug or not, but it appears when the code was added to support coip 11 months ago telling it what public ip to use was overlooked? it appears right now, all you can do is pull from the pool and not say, use ip X, like you can in aws-api?

Thanks,
Eric

**Comment by ewbankkit** [comment]
@eduda Thanks for raising this issue.
It has already been noticed in #8004. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
