### ISSUE TITLE
Redshift resource defaults to classic resize with RA3 node type

### ISSUE THREAD

**Issue by bgiardie** [hashicorp/terraform-provider-aws#18104]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

###  Terraform AWS Provider Version
`provider.aws: version = "~> 3.32"`
`terraform 0.12.24`

### Affected Resource(s)

* aws_redshift_cluster

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
  node_type            = "ra3.4xlarge"
  compute_nodes        = var.environment == "prod" ? "12" : "2"
  cluster_type         = "multi-node"
  json_config          = file("${path.module}/config/explorer_wlm_json_configuration.json")
```

### Expected Behavior

According to the API, elastic resize should be the default resize method.  RA3 nodes as a destination node type are valid when resizing from ds2 node types.

### Actual Behavior

Classic resize was triggered.  

### Steps to Reproduce

Change the `number_of_nodes` and do `terraform apply`.

### References

* #7599

**Comment by RangaSairohith** [comment]
@**bgiardie** Hey, I would like to work on this issue. And since this is one of the mandatory requirements for my course work, will make sure that it gets completed.

**Comment by aflansburg** [comment]
Interested to know if this is still the case - i.e. will applying changes to the `node_type` and `number_of_nodes` attribute for the `aws_redshift_resource` cluster result in a classic resize or elastic resize? We are scaling our cluster to a separate type, and just interested in what type of resize will take place as one (classic) has much more potential for lengthy down time than the other (elastic).

I would be interested if there is a way to get some synopsis of the calls TF will make to the AWS API. I'm not asking to see the entire workflow of how my hamburger is made FWIW - just to get a bit more insight on what's happening.
