### ISSUE TITLE
New RabbitMQ support in aws_mq_broker fails to create resource with general log enabled

### ISSUE THREAD

**Issue by trevorrea** [hashicorp/terraform-provider-aws#18107]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_mq_broker

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_mq_broker" "hubs" {
  broker_name                = local.resource_prefix
  apply_immediately          = var.hubs_mq_apply_immediately
  auto_minor_version_upgrade = var.hubs_mq_auto_minor_version_upgrade
  deployment_mode            = "SINGLE_INSTANCE"
  engine_type                = "RabbitMQ"
  engine_version             = "3.8.6"
  host_instance_type         = "mq.t3.micro"
  security_groups            = [aws_security_group.hubs_mq.id]
  subnet_ids                 = [module.vpc.private_subnets[0]
  tags                       = local.common_tags
  logs {
    general = true
  }
  maintenance_window_start_time {
    day_of_week = var.hubs_mq_maintenance_day_of_week
    time_of_day = var.hubs_mq_maintenance_time_of_day
    time_zone   = var.hubs_mq_maintenance_timezone
  }
  user {
    username = var.hubs_mq_username
    password = var.hubs_mq_password
  }
  lifecycle {
    prevent_destroy = true
  }
}
```

```hcl
resource "aws_mq_broker" "hubs" {
  broker_name                = local.resource_prefix
  apply_immediately          = var.hubs_mq_apply_immediately
  auto_minor_version_upgrade = var.hubs_mq_auto_minor_version_upgrade
  deployment_mode            = "SINGLE_INSTANCE"
  engine_type                = "RabbitMQ"
  engine_version             = "3.8.6"
  host_instance_type         = "mq.t3.micro"
  security_groups            = [aws_security_group.hubs_mq.id]
  subnet_ids                 = [module.vpc.private_subnets[0]
  tags                       = local.common_tags
  logs {
    audit  = false
    general = true
  }
  maintenance_window_start_time {
    day_of_week = var.hubs_mq_maintenance_day_of_week
    time_of_day = var.hubs_mq_maintenance_time_of_day
    time_zone   = var.hubs_mq_maintenance_timezone
  }
  user {
    username = var.hubs_mq_username
    password = var.hubs_mq_password
  }
  lifecycle {
    prevent_destroy = true
  }
}
```

### Expected Behavior

Terraform should have created the Amazon MQ broker with general logging enabled to CloudWatch.

### Actual Behavior

Error message received

```
Error: BadRequestException: Audit logging is not supported for RabbitMQ brokers.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "aac00a9c-7a8c-463d-9d2a-6bd9763c43c0"
  },
  ErrorAttribute: "logs.audit",
  Message_: "Audit logging is not supported for RabbitMQ brokers."
}
```

### Steps to Reproduce

Create a RabbitMQ broker with general logging enabled. Note - adding audit = false results in the same error.

### Important Factoids

N/A

### References

* #16030

Tagging @yardensachs  - thanks so much for adding support for RabbitMQ - not sure if you can easily reproduce this but hopefully you should be able to!

**Comment by anGie44** [comment]
Hi @trevorrea , thank you for raising this issue. It happens to duplicate #18067 , so I'm going to close this issue but please refer to the other issue for updates.
