### ISSUE TITLE
Add ARN prefix attribute to aws_batch_job_definition

### ISSUE THREAD

**Issue by andrewmwilson** [hashicorp/terraform-provider-aws#18111]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Adding an `arn_prefix` attribute to `aws_batch_job_definition` would make for significantly cleaner syntax when you want refer to the latest version of a job definition (without the revision suffix) in another resource.

Currently the only method I can come up with is this:
```hcl
resource "aws_batch_job_definition" "example" {
  name = "..." 
  type = "container"
  container_properties = "..."
}

resource "aws_cloudwatch_event_target" "example" {
  target_id = "..."
  rule      = "..."
  arn       = "..."
  role_arn  = "..."

  batch_target {
    job_name       = "..."
    job_definition = trimsuffix(aws_batch_job_definition.example.arn, ":${aws_batch_job_definition.example.revision}")
  }
}
```

### New or Affected Resource(s)

* aws_batch_job_definition

### Potential Terraform Configuration

```hcl
resource "aws_batch_job_definition" "example" {
  name = "..." 
  type = "container"
  container_properties = "..."
}

resource "aws_cloudwatch_event_target" "example" {
  target_id = "..."
  rule      = "..."
  arn       = "..."
  role_arn  = "..."

  batch_target {
    job_name       = "..."
    job_definition = aws_batch_job_definition.example.arn_prefix
  }
}
```

**Comment by gauthierm** [comment]
As a workaround, you can use:

```tf
replace(aws_batch_job_definition.example.arn, "/:[0-9]+$/", ""),
```

**Comment by andrewmwilson** [comment]
@drewmullen thanks so much for this!
