### ISSUE TITLE
enableExecuteCommand for aws_ecs_service

### ISSUE THREAD

**Issue by jtatum** [hashicorp/terraform-provider-aws#18112]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

ECS services (Fargate and EC2) now allow commands to be executed inside the container. This must be enabled on every ECS task and service. The provider must send a new field to `CreateService`/`UpdateService`, `enableExecuteCommand`, to enable this functionality.

### New or Affected Resource(s)

* aws_ecs_service

### Potential Terraform Configuration

```hcl
resource "aws_ecs_service" "mongo" {
  name                   = "mongodb"
  cluster                = aws_ecs_cluster.foo.id
  task_definition        = aws_ecs_task_definition.mongo.arn
  enable_execute_command = true
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2021/03/amazon-ecs-now-allows-you-to-execute-commands-in-a-container-running-on-amazon-ec2-or-aws-fargate/
* https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-exec.html
* https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateService.html#API_CreateService_RequestSyntax
* https://github.com/aws/containers-roadmap/issues/1050

**Comment by iancward** [comment]
I think an update is also required to `aws_ecs_cluster` to add support for the [logging configuration](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-exec.html#ecs-exec-logging).

**Comment by ewbankkit** [comment]
[Blog post](https://aws.amazon.com/blogs/containers/new-using-amazon-ecs-exec-access-your-containers-fargate-ec2/).

Requires [AWS SDK v1.37.31](https://github.com/aws/aws-sdk-go/releases/tag/v1.37.31):

* #18119

**Comment by shedimon** [comment]
@ewbankkit, @bill-rich , I've opened a [PR](https://github.com/hashicorp/terraform-provider-aws/pull/18347), that adds `enable_execute_command` to the `aws_ecs_service` resource. Would be grateful for the review.

**Comment by markbaird** [comment]
The merged PR only covers the `aws_ecs_service` portion, it doesn't add the `executeCommandConfiguration` configuration options to the `aws_ecs_cluster` resource.

**Comment by WhyNotHugo** [comment]
@markbaird Do you really need `executeCommandConfiguration`? I just updated the services and could run `ExecuteCommand` just fine (e.g.: it seems updating the cluster was not necessary).

**Comment by iancward** [comment]
@WhyNotHugo if you want any auditing of the commands run in the task, we'll need support for `executeCommandConfiguration` in `aws_ecs_cluster`. See my note [above](https://github.com/hashicorp/terraform-provider-aws/issues/18112#issuecomment-799868624} and documentation link.
