### ISSUE TITLE
Name plan time validation aws_globalaccelerator_accelerator broken

### ISSUE THREAD

**Issue by e-moshaya** [hashicorp/terraform-provider-aws#18110]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_globalaccelerator_accelerator

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_globalaccelerator_accelerator" "this" {
  name = "tes-mount-test-global-accelerator"
}
```

### Debug Output

```
Error: expected length of name to be in the range (1 - 32), got syn-scout-test-global-accelerator
```

### Expected Behavior

The plan time validation in https://github.com/hashicorp/terraform-provider-aws/pull/17739  has broken our Terraform project. The expected length of name to be in the range for the aws_globalaccelerator_accelerator should be (1 - 64)  and not (1 - 32). Our plans for previously created resources are failing. Check the API documentation for [name range](https://docs.aws.amazon.com/global-accelerator/latest/api/API_CreateAccelerator.html#API_CreateAccelerator_RequestSyntax).

```
Error: expected length of name to be in the range (1 - 32), got tes-catlo-besg-global-accelerator
```

Even though this name is within the allowed range.

### Actual Behavior

The plan time validation for the name length should be between 1-64 and not 1-32

### Steps to Reproduce

1. `terraform apply`

### References

* https://docs.aws.amazon.com/global-accelerator/latest/api/API_CreateAccelerator.html#API_CreateAccelerator_RequestSyntax
* https://github.com/hashicorp/terraform-provider-aws/pull/17739

**Comment by anGie44** [comment]
Hi @e-moshaya , thank you raising this issue and apologies you came across this behavior! This issue happens to duplicate https://github.com/hashicorp/terraform-provider-aws/issues/17978, so I'm going to close this but please refer to #17978 for updates.
