### ISSUE TITLE
Changing EC2 instance_type does not update all attributes

### ISSUE THREAD

**Issue by fheinle-mak** [hashicorp/terraform-provider-aws#18120]
# The Problem

When changing an EC2 instance type in terraform, changes in attributes like `public_ip` are only visible in the second run of terraform. Resources depending on those attributes consequently only get updated then instead of with the first run.

## How to reproduce

Consider the following minimal example:

```terraform
resource "aws_route53_record" "testing" {
  zone_id = data.aws_route53_zone.external.zone_id
  name    = "testing.example.com"
  type    = "A"
  ttl     = "300"
  records = [aws_instance.testing_host.public_ip]
}
resource "aws_instance" "testing_host" {
  ami                    = var.ami_id
  instance_type          = "t3.micro"
  vpc_security_group_ids = [aws_security_group.allow_ssh.id]
  subnet_id              = aws_subnet.public.id
}
```

Now change `aws_instance.testing_host.instance_type` to something else. On `terraform apply`, the resource is modified in-place as far as terraform is concerned, however on the AWS side it results in a reboot of the instance and consequently a change of IP address. Running `terraform apply` again will recognize this changed IP address and update the `aws_route53_record.testing`.

We're using terraform 0.14.8 and registry.terraform.io/hashicorp/aws 3.31.0

**Comment by sambonator** [comment]
This is still a problem under Terraform 1.2.7 and aws provider 4.22.0

Snippet from tfstate file shows mismatching instance_public_up output and its actual public_ip:
{
  "version": 4,
  "terraform_version": "1.2.7",
  "serial": 20,
  "lineage": "67b8bb46-991f-1ade-bb73-6b019da84c74",
  "outputs": {
    "instance_id": {
      "value": "i-0f714bb0ffa6a0432",
      "type": "string"
    },
    "instance_public_ip": {
      "value": "3.86.90.83",
      "type": "string"
    }
...
      "instances": [
        {
          "schema_version": 1,
          "attributes": {
            "ami": "ami-0070c5311b7677678",
...          ],
            "private_ip": "172.31.48.185",
            "public_dns": "ec2-54-84-143-168.compute-1.amazonaws.com",
            "public_ip": "54.84.143.168",
            "root_block_device": [
              {
                "delete_on_termination": true,
                "device_name": "/dev/sda1",
...
