### ISSUE TITLE
tests/resource/aws_globalaccelerator_accelerator: BucketNotEmpty errors

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#18121]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Found while testing #17985 

```
Error: error deleting S3 Bucket (tf-acc-test-8066618524275417147): BucketNotEmpty: The bucket you tried to delete is not empty
	status code: 409
        
--- FAIL: TestAccAwsGlobalAcceleratorAccelerator_attributes (519.52s)
```

Since the objects in the S3 Bucket are outside the control of the Terraform configuration, it is expected to enable `force_destroy = true` on these `aws_s3_bucket` managed resources for this testing. While we are adjusting this configuration, it is probably best to also set the ACL to private.

### Affected Resource

* `aws_globalaccelerator_accelerator`

### Potential Terraform Configuration

```hcl
resource "aws_s3_bucket" "test" {
  acl           = "private"
  bucket        = %[1]q
  force_destroy = true
}
```

Related:

* #18094
* #18093

**Comment by bflad** [comment]
I'll just go ahead and add this to #18096 since I'm in the neighborhood already there. 👍
