### ISSUE TITLE
AWS Failure Injection Simulator (FIS) experiment template resource

### ISSUE THREAD

**Issue by mwarkentin** [hashicorp/terraform-provider-aws#18125]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon just launched [AWS FIS](https://aws.amazon.com/fis/) (Failure Injection Simulator) in GA ([blog post](https://aws.amazon.com/blogs/aws/aws-fault-injection-simulator-use-controlled-experiments-to-boost-resilience/)). The experiment templates look like a good fit for terraform.

### New or Affected Resource(s)

* `aws_fis_experiment_template`

### Potential Terraform Configuration

This seems like a pretty complex resource so I've filled out most of the available options, but the structure is very likely not what it should look like in the end.

```hcl
resource "aws_fis_experiment_template" "main" {
  description = "Description of the experiment template."

  # Note: This is a list of conditions in the AWS API
  stop_condition = {
    source = "aws:cloudwatch:alarm"
    value = "aws:cloudwatch:arn"
  }

  # Note: This is a list of targets in the AWS API
  target = {
    # There are 6 resource types currently
    resource_type = "aws:ec2:instance"

    resource_arns = [
       "arn:to:ec2:instance1",
       "arn:to:ec2:instance2",
    ]

    resource_tags = [
      {
        key = "TagName"
        value = "TagValue"
      }
    ]

    filters = [
      {
        path = "string",
        values = ["val1", "val2"]
      }
    ]

    # One of ALL, count(n), percent(n)
    selection_mode = "percent(25)"
  }

  # Note: this is a list of actions in the AWS API
  action {
    action_id = "actionId1"
    description = "This is an action description."

    start_after = [
      "actionId2"
    ]
   
    # List of parameters
    parameter {
      
    }

    # List of targets
    { 

    }
  }
}
```

### References

* https://docs.aws.amazon.com/cli/latest/reference/fis/create-experiment-template.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fis-experimenttemplate.html
* https://aws.amazon.com/fis/
* https://aws.amazon.com/blogs/aws/aws-fault-injection-simulator-use-controlled-experiments-to-boost-resilience/
* https://docs.aws.amazon.com/fis/latest/APIReference/API_CreateExperimentTemplate.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/fis/#FIS.CreateExperimentTemplate

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.37.31](https://github.com/aws/aws-sdk-go/releases/tag/v1.37.31):

* #18119

**Comment by puneet739** [comment]
Hi there, any update on this, This is a good service and should be available. Its already been more then 1 year

**Comment by dknz2008** [comment]
Hi, would love an update on this, FIS has been out for a while now

**Comment by cdschneider** [comment]
Any update here?  I'm very curious about any upcoming release plans for this feature/resource

**Comment by ashutoshupadhyay** [comment]
You may already know and using it already, something along the lines is currently available via "awscc" provider. Obviously it means using a different provider but it is quite handy as compared to writing custom scripts. Happy to share sample code. https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/fis_experiment_template

**Comment by breathingdust** [comment]
Hi all 👋 Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!
