### ISSUE TITLE
Feature request: Amazon Workspaces Bundle Support

### ISSUE THREAD

**Issue by gazoakley** [hashicorp/terraform-provider-aws#18124]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon WorkSpaces bundle management APIs are now available for customers to perform WorkSpaces bundle operations. The new set of APIs supports creation, deletion, and image association operations for WorkSpaces bundles. These APIs are intended for use by WorkSpaces administrators who want to automate WorkSpaces management workflows.

### New or Affected Resource(s)

* `aws_workspaces_bundle`

### Potential Terraform Configuration

```hcl
resource "aws_workspaces_bundle" "test" {
  name        = "test"
  description = "test"
  image_id    = "wsi-abcdef123"

  compute_type {
    name = "STANDARD"
  }

  root_storage {
    capacity = "80"
  }

  user_storage {
    capacity = "50"
  }

  tags = {}
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2021/03/amazon-workspaces-introduces-bundle-management-apis/

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.37.30](https://github.com/aws/aws-sdk-go/releases/tag/v1.37.30):

* #18119
