### ISSUE TITLE
AWS S3 Bucket object sensitive content

### ISSUE THREAD

**Issue by vishmit123** [hashicorp/terraform-provider-aws#18137]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS S3 Bucket object-sensitive content argument. When creating an object in s3 using Resource: aws_s3_bucket_object, the value passed to content is visible in diffs/plan/apply. Require a new argument (sensitive-content preferably) for using this resource for sensitive content creation.

**Comment by ewbankkit** [comment]
@vishmit123 Thanks for raising this issue.
It has already been noticed in #9105. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
