### ISSUE TITLE
AWS Synthetics Canary Resource returning "name" in "ID" output

### ISSUE THREAD

**Issue by dj-maisy** [hashicorp/terraform-provider-aws#18136]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.4
AWS Provider v3.30.0

### Affected Resource(s)

* aws_synthetics_canary

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_synthetics_canary" "some_canary_test" {
  name                 = "some_canary_test"

  artifact_s3_location = "s3://${aws_s3_bucket.some_canary_test.id}/canary/eu-west-1/some_canary_test"
  execution_role_arn   = aws_iam_role.some_canary_test_role.arn
  handler              = "some_canary_test.handler"

  runtime_version      = "syn-nodejs-puppeteer-3.1"

  zip_file             = "${path.module}/some_canary_test.zip"

  schedule {
    expression = "rate(0 minute)"
  }

  # Ignore changes to the zip_file. This will be updated by our CI.
  lifecycle {
    ignore_changes = [
      zip_file
    ]
  }
}

resource "aws_cloudwatch_log_group" "some_canary_test_log_group" {
    name = "/aws/lambda/cw-syn-${aws_synthetics_canary.some_canary_test.name}-${aws_synthetics_canary.some_canary_test.id}"
}
```

### Plan Output

I've included the Plan Output, as I don't think Debug Output is necessary to hone-down this issue.

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.some_canary_test.aws_cloudwatch_log_group.some_canary_test_log_group will be created
  + resource "aws_cloudwatch_log_group" "some_canary_test_log_group" {
      + arn               = (known after apply)
      + id                = (known after apply)
      + name              = "/aws/lambda/cw-syn-some_canary_test-some_canary_test"
      + retention_in_days = 0
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

### Expected Behavior

I would expect a CloudWatch Log Group to be created with the name of `/aws/lambda/cw-syn-some_canary_test-7d3a6c8f-8857-44e8-a570-d7197b649819`, or whatever UUID4 belongs to the Canary Resource that was just created.

### Actual Behavior

A Cloudwatch Log Group with the name `/aws/lambda/cw-syn-some_canary_test-some_canary_test` is created. Unless this is rectified, I cannot create a Log Group to be used by a Canary Test Runner, which makes debugging difficult if the canary script fails or is invalid.

### Steps to Reproduce

1. Take the sample HCL from above and attempt to apply it with `terraform apply`.

### Important Factoids

I suspect this line may by the culprit:

https://github.com/hashicorp/terraform-provider-aws/blob/8a532d019bee7af6bd2aeb3d8e312e435c9d837e/aws/resource_aws_synthetics_canary.go#L267

The Canary Name field is already set here:

https://github.com/hashicorp/terraform-provider-aws/blob/8a532d019bee7af6bd2aeb3d8e312e435c9d837e/aws/resource_aws_synthetics_canary.go#L302

Instead, the ID should probably use the Unique ID as exposed by the Canary struct [here](https://github.com/aws/aws-sdk-go/blob/aff86fdd1389b3a2c57e8238cff418cb91a9880e/service/synthetics/api.go#L1457), so [Line 267](https://github.com/hashicorp/terraform-provider-aws/blob/8a532d019bee7af6bd2aeb3d8e312e435c9d837e/aws/resource_aws_synthetics_canary.go#L267) instead looks like this:

```go
d.SetId(aws.StringValue(resp.Canary.ID))
```

If this cannot be changed or fixed for some reason, then I would alternatively propose exposing the Canary Unique ID via some kind of "uid" output.

**Comment by ewbankkit** [comment]
@dj-maisy Thanks for raising this issue.

That CloudWatch log group ([amongst other resources](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries_Create.html#CloudWatch_Synthetics_Canaries_Resources_Created)) is created implicitly by AWS and its name is outside the control of Terraform.

Agree that we can add the `canary_id` (or some equivalently named) attribute.
