### ISSUE TITLE
aws_s3_access_point not changing VPC when 'edited in place'

### ISSUE THREAD

**Issue by andrewp-sf** [hashicorp/terraform-provider-aws#18132]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_s3_access_point

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_s3_access_point" "example" {
  bucket = aws_s3control_bucket.example.arn
  name   = "example"
  vpc_configuration {
    vpc_id = aws_vpc.example.id
  }
}
```

### Expected Behavior

Access point is re-created with new VPC configuration (this parameter can't be edited in place).

### Actual Behavior

Access point is changed with success according to terraform, however VPC id remains from old version.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/16061dd6419397d15a9e5c65a41ad10e4f4547b2/aws/resource_aws_s3_access_point.go#L103-L117

`vpc_id` needs `ForceNew: true,`.
