### ISSUE TITLE
Configure retry limit for aws_lambda_function 

### ISSUE THREAD

**Issue by lxop** [hashicorp/terraform-provider-aws#18152]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Lambda functions have a configurable retry limit (either 0, 1, or 2 times) to control failure handling behaviour. It would be great to be able to configure this with Terraform.

### New or Affected Resource(s)

* aws_lambda_function

### Potential Terraform Configuration

```hcl
resource "aws_lambda_function" "test_lambda" {
  dead_letter_config {
    target_arn = "<ARN for SQS queue or SNS topic>"
    retry_limit = 1
  }
}
```

### References

* https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html#dlq

**Comment by lxop** [comment]
Today I have finally stumbled upon the way this is actually configured: via the [aws_lambda_function_event_invoke_config](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function_event_invoke_config) resource. This wasn't simple to find (at least for me), so I suggest that this is more of a documentation issue.

**Comment by sherman-grewal** [comment]
@bill-rich Hey Bill! I was wondering if you were still interested in adding a retry limit to the `aws_lambda_function` resource, as there happens to be a solution to this issue. I would love to pick up this issue as a first-time contributor, but let me know if you think it is necessary 😄
