### ISSUE TITLE
aws_cloudwatch_event_rule "Provider produced inconsistent result after apply"

### ISSUE THREAD

**Issue by richardgavel** [hashicorp/terraform-provider-aws#18151]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

TF: 0.12.30
AWS: 2.70.0

### Affected Resource(s)

aws_cloudwatch_event_rule

### Expected Behavior

Resource created

### Actual Behavior

Very intermittent

Error: Provider produced inconsistent result after apply

When applying changes to
aws_cloudwatch_event_rule.datalake_runaggregationsjob_rule, provider
"registry.terraform.io/-/aws" produced an unexpected new value for was
present, but now absent

### Important Factoids

This seems like an eventual consistency issue like has been seen with other resources.

* #0000

**Comment by bill-rich** [comment]
Hi @richardgavel!

In order to help reproduce this issue, can you please provide an example configuration?

**Comment by breathingdust** [comment]
Closing due to lack of response.
