### ISSUE TITLE
 aws_cloudfront_distribution incorrect hosted_zone_id in China

### ISSUE THREAD

**Issue by mgzenitech** [hashicorp/terraform-provider-aws#18169]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_cloudfront_distribution

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

In China **hosted_zone_id** should be **Z3RFFRIM2A3IF5** and in international aws **Z2FDTNDATAQYW2**

### Actual Behavior

In both China and international aws_cloudfront_distribution returns **Z2FDTNDATAQYW2**

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ewbankkit** [comment]
@mgzenitech Thanks for raising this issue.
It has already been noticed in #15223. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
