### ISSUE TITLE
aws_route53_vpc_association_authorization - is this working as intended?

### ISSUE THREAD

**Issue by kennyche** [hashicorp/terraform-provider-aws#18176]
**Terraform version:**
terraform_0.13.0
terraform_0.12.1

Issue:  Following the documentation example works fine.  However, i think this moves away from the actual real world example of a cross account vpc that has not been created by the terraform plan initiating the authorization.  If you try and associate a vpc created outside the authorizing account, I still get a 401 saying that the authorizing account does not have rights to associate the vpc from the other aws account to the authorizing accounts private zone, even though the authorization resource has been created.  
```

aws_route53_vpc_association_authorization.primary: Creating...
aws_route53_vpc_association_authorization.primary: Creation complete after 2s [id=ZXYZREDACTED:vpc-001THATACCOUNT]
aws_route53_zone_association.primary: Creating...
Error: error associating Route 53 Hosted Zone (ZXYZREDACTED) to EC2 VPC (vpc-001THATACCOUNT): NotAuthorizedException: User: arn:aws:iam::THISACCOUNT is not authorized to perform: route53:AssociateVPCWithHostedZone on resource: arn:aws:ec2:eu-west-2:THISACCOUNT:vpc/vpc-001THATACCOUNT
        status code: 401, request id: xxx
```

#14215
#12362

Im guessing the issue is here... arn:aws:ec2:eu-west-2:**THISACCOUNT**:vpc/**vpc-001THATACCOUNT**

The only difference from the example in the documentation is that the second accounts vpc is not created in the same tf plan .

```
provider "aws" {
}

provider "aws" {
  alias = "alternate"
}

resource "aws_vpc" "example" {
  cidr_block           = "10.6.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true
}

resource "aws_route53_zone" "example" {
  name = "example.com"

  vpc {
    vpc_id = aws_vpc.example.id
  }
}

resource "aws_route53_vpc_association_authorization" "example" {
  vpc_id  = data.terraform_remote_state.THATACCOUNT.outputs.vpc_id
  zone_id = aws_route53_zone.example.id
}

resource "aws_route53_zone_association" "example" {
  provider = "aws.alternate"

  vpc_id  = aws_route53_vpc_association_authorization.example.vpc_id
  zone_id = aws_route53_vpc_association_authorization.example.zone_id
}
```

**Comment by lindu-dd** [comment]
any update on this? I'm encounter the same issue
