### ISSUE TITLE
aws_globalaccelerator_endpoint_group timeouts  are not documented

### ISSUE THREAD

**Issue by madpipeline** [hashicorp/terraform-provider-aws#18170]
The [documentation page](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/globalaccelerator_endpoint_group) for `aws_globalaccelerator_endpoint_group` does not have documented the `timeouts` block, that has been added by https://github.com/hashicorp/terraform-provider-aws/pull/17112 and released in https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3240-january-14-2021.

**Comment by ewbankkit** [comment]
@madpipeline Thanks for raising this issue.

On closer inspection the timeouts are documented, but in the wrong section ([`Attributes Reference`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/globalaccelerator_endpoint_group#attributes-reference) vs. `Timeouts`).
I'll fix this.
