### ISSUE TITLE
aws_redshift_cluster maintenance_track_name is missing

### ISSUE THREAD

**Issue by olysyuk** [hashicorp/terraform-provider-aws#18171]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
aws_redshift_cluster is missing MaintenanceTrackName parameter. It is possible to change this value from AWS CLI via `aws redshift modify-cluster --cluster-identifier=redshift-etl --maintenance-track-name=sql_preview` and AWS Console.

### New or Affected Resource(s)

* aws_redshift_cluster
 
### Potential Terraform Configuration

```hcl
resource "aws_redshift_cluster" "default" {
  cluster_identifier = "test-cluster"
  database_name      = "test-db"
  master_username    = "user"
  master_password    = "pass"
  node_type          = "ra3.xlplus"
  cluster_type       = "multi-node"
  number_of_nodes    = 2
  publicly_accessible  = false
  maintenance_track_name = "sql_preview"
}
```

### References
* https://docs.aws.amazon.com/redshift/latest/APIReference/API_Cluster.html - MaintenanceTrackName

**Comment by hanumanthan** [comment]
@bill-rich Interested to pick this up as a first time contributor. Is this open ?

**Comment by RangaSairohith** [comment]
**@olysyuk** Hey, I would like to work on this issue. And since this is one of the mandatory requirements for my course work, will make sure that it gets completed.

**Comment by RangaSairohith** [comment]
@olysyuk Can you please confirm this. So that I can start working on this. Waiting for your positive response.

_Best Regards,
P Sai Rohith_
