### ISSUE TITLE
aws_cloudwatch_event_rule: Expected value of event_bus_name to match regular expression

### ISSUE THREAD

**Issue by vdahmane** [hashicorp/terraform-provider-aws#18182]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform Version: 0.13.5
Provider: v3.32.0

### Affected Resource(s)

* aws_cloudwatch_event_rule

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_cloudwatch_event_rule" "foo" {
  name           = "foo"
  description    = "foo"
  event_bus_name = "aws.partner/datadog.com/foo"
  event_pattern = <<EOF
{
  "account": ["12345678"]
}
EOF
}


```

### Expected Behavior

TF should create event rule with this event bus name.
### Actual Behavior

Terraform displaying this error output:
`expected value of event_bus_name to match regular expression "^[a-zA-Z0-9._\\-]+$", got aws.partner/datadog.com/foo`

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ewbankkit** [comment]
Related:

* #16815
* #16431
