### ISSUE TITLE
resource aws_sns_topic: add topic type argument support

### ISSUE THREAD

**Issue by izaneuski** [hashicorp/terraform-provider-aws#18279]
As described [here](https://docs.aws.amazon.com/sns/latest/dg/sns-create-topic.html)
SNS topic now supports topic type - standard or FIFO.
`During creation, you choose a topic type (standard or FIFO) and name the topic. After creating a topic, you can't change the topic type or name. All other configuration choices are optional during topic creation, and you can edit them later. `

Current version of aws provider doesn't support topic type.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_topic

It would be very helpful to be able create FIFO SNS topic with terraform. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_sns_topic

### Potential Terraform Configuration

```hcl
resource "aws_sns_topic" "user_updates" {
  name              = "user-updates-topic"
  kms_master_key_id = "alias/aws/sns"
  topic_type = "FIFO"
}
```

### References

* #0000

**Comment by ewbankkit** [comment]
@izaneuski Thanks for raising this issue.
It has already been noticed in #15805. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
