### ISSUE TITLE
lambda_function CodeSigning Regression in ap-northeast-3

### ISSUE THREAD

**Issue by kylegoch** [hashicorp/terraform-provider-aws#18328]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/aws v3.33.0
```
### Affected Resource(s)

* aws_lambda_function

### Expected Behavior

Lambda to be created cleanly. It should be noted that the Lambda actually creates, but terraform errors out.

### Actual Behavior

Error: error getting Lambda Function (datadog-log-forwarder-ap-northeast-3) code signing config AccessDeniedException:
	status code: 403, request id: 073a1429-9c57-4185-ae77-b87646766077

### Steps to Reproduce

1. `terraform apply` in `ap-northeast-3

### Important Factoids

The terraform template in question creates a Lambda function in every "default" region (those that arent opt-in). Running `terraform apply` was successful in the following regions before failing in `ap-northeast-3`. This does not point to an IAM issue like the referenced issues below potentially are related to. 

Also pinning to `3.16.0` like the other issues mention does not work because the provider does not recognize `ap-northeast-3` as a valid region as it's a newer region.

This template worked successfully in these regions:
    "us-east-1",
    "us-east-2",
    "us-west-1",
    "us-west-2",
    "ap-northeast-1",
    "ap-northeast-2",
    "ap-south-1",
    "ap-southeast-1",
    "ap-southeast-2",
    "ca-central-1",
    "eu-central-1",
    "eu-north-1",
    "eu-west-1",
    "eu-west-2",
    "eu-west-3",
    "sa-east-1"

### References

* #16755
* #16398

**Comment by ewbankkit** [comment]
Relevant code:

https://github.com/hashicorp/terraform-provider-aws/blob/7141d1c315dc0c221979f0a4f8855a13b545dbaf/aws/resource_aws_lambda_function.go#L820-L842

Lambda code signing must not yet be available in the newly-full `ap-northeast-3` region.

**Comment by gdavison** [comment]
Code signing is not available in `ap-northeast-3` yet. If you try the console, you cannot access either the Lambda Code Signing configuration or the general AWS Signer service.

You haven't included your configuration, but you may be able to use a [`dynamic` block](https://www.terraform.io/docs/language/expressions/dynamic-blocks.html) to disable code signing when deploying to `ap-northeast-3`.

**Comment by brikis98** [comment]
I'm getting the same error in `ap-northeast-3` _and we are not trying to enable code signing at all_. This code used to work fine, so something about introducing Lambda code signing into the AWS Provider has broken Lambda functions in general in `ap-northeast-3`, whether or not you are trying to use the code signing functionality.
