### ISSUE TITLE
Resource aws_lex_bot not setting detect_sentiment when create

### ISSUE THREAD

**Issue by iicy90** [hashicorp/terraform-provider-aws#18325]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.23

### Affected Resource(s)

* aws_lex_bot

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_lex_bot" "test_bot" {
  name             = "test_bot"
  locale           = "en-AU"
  process_behavior = "BUILD"
  voice_id         = "Russell"
  create_version   = false
  child_directed   = false
  description      = "Test Bot"
  detect_sentiment = true

  ...
}

output lex_bot_detect_sentiment {
  value = aws_lex_bot.test_bot.detect_sentiment
}
```

### Expected Behavior

It should create the bot with Detect Sentiment enabled

### Actual Behavior

It create bot with Detect Sentiment disabled

```hcl
Outputs:

lex_bot_detect_sentiment = false
```

### Steps to Reproduce

1. `terraform apply`

### References

https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_lex_bot.go#L197-L206

**Comment by ewbankkit** [comment]
It looks like `nlu_intent_confidence_threshold` also isn't being set on create.
