### ISSUE TITLE
ECS service wait_for_steady_state doesn't work

### ISSUE THREAD

**Issue by laur1s** [hashicorp/terraform-provider-aws#18329]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/archive v2.1.0
+ provider registry.terraform.io/hashicorp/aws v3.33.0

### Affected Resource(s)

aws_ecs_service

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

We have a terraform code base that deploys around 10 ECS services. The problem is that sometimes after 3 minutes. Terraform fails with an error code: 
`Error: error waiting for service (arn:aws:ecs:eu-xxx-1:xxx:service/dev-xx/email) to reach a steady state: ResourceNotReady: failed waiting for successful resource state`

The strange part is that terraform instead of updating the services first tries to delete them and only then create new services. This error waiting for service happens at random times from 3-to 3:40minutes. Sometimes it launches services correctly. In AWS console I can see that all services are launched correctly without any errors!

```hcl
resource "aws_ecs_service" "email" {
  cluster                            = local.cluster
  deployment_maximum_percent         = 200
  deployment_minimum_healthy_percent = 50
  desired_count                      = 1
  health_check_grace_period_seconds  = 30
  name                               = local.email_name
  propagate_tags                     = "TASK_DEFINITION"
  scheduling_strategy                = "REPLICA"
  task_definition                    = aws_ecs_task_definition.email.arn
  wait_for_steady_state              = true

  deployment_controller {
    type = "ECS"
  }

  load_balancer {
    container_name   = local.email_name
    container_port   = 443
    target_group_arn = local.email_target_group
  }
}
```

### Expected Behavior
Update should update the ecs services

### Actual Behavior
Some random timeouts
### Steps to Reproduce

1. Create a terraform state with multiple ecs services
2. Try updating multiple serivices at the same time with  `terraform apply`

**Comment by gdavison** [comment]
Hi @laur1s, thank you for submitting this issue. You've included one ECS service above. Is your configuration deploying 10 copies of that service, or is that an example of how the different services are configured?

**Comment by gdavison** [comment]
Implementation note: When `wait_for_steady_state` is set, the resource currently uses the function `WaitUntilServicesStable()` provided by the AWS SDK. We may get better results by using our own `waiter` function.

**Comment by gdavison** [comment]
Possibly related to #17118

#17746 is another `wait_for_steady_state ` issue

**Comment by laur1s** [comment]
Hi @gdavison, thank you for a fast reply. The ECS service included is an example service. We have 10 services configured like this(just different names) The bug is quite hard to reproduce because. The timeout happens only from time to time. Sometimes terraforrm deploys ecs services correctly and sometimes it fails after a same amount of time (the deployment is always successful on ECS side). If I can help somehow please let me know

**Comment by brunhil** [comment]
@laur1s - From my experience, this fails to finish due to AWS still waiting to finish switching the services over.

**Comment by YakDriver** [comment]
It would be great if an eventual solution could address most/all of the related issues:

Related #16021
Related #16184
Related #16526
Related #16888
Related #17118
Related #17446
Related #18329 (this issue)
Related #18868 (PR)
