### ISSUE TITLE
ECR Public: the attribute for repository url has a different variable name from the doc

### ISSUE THREAD

**Issue by eastenluis** [hashicorp/terraform-provider-aws#18321]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

- Terraform version: `v0.13.5`
- AWS provider version: `3.33.0`

### Affected Resource(s)

* aws_ecrpublic_repository

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ecrpublic_repository" "repo" {
    repository_name = "dummy"
}

resource "aws_lambda_function" "function" {
     function_name = "dummy_function"
     image_uri = "${aws_ecrpublic_repository.dummy.repository_url}:latest"
     package_type = "Image"
     
    role = ....
}
```

### Debug Output

For the line `image_uri = "${aws_ecrpublic_repository.dummy.repository_url}:latest"`, it reported "This object has no argument, nested block, or exported attribute named
"repository_url". Did you mean "repository_uri"?".

### Steps to Reproduce

1. `terraform plan`

### References

In the documentation, it says the attribute name is `repository_url` (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecrpublic_repository#repository_url). However in the source, it seems to output `repository_uri` instead (https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_ecrpublic_repository.go#L100). There is a conflict between the doc and the actual computed value, and `repository_uri` doesn't seem to be quite consistent with the private ECR repository.

**Comment by eastenluis** [comment]
I realized the example may not be a valid use case (as `image_uri` expects an output from an ECR private repo's image URL). But still the issue with the difference in doc and actual output persists.

**Comment by anGie44** [comment]
Hi @eastenluis , thank you for raising this issue. Looks like the documentation will need a quick edit to reflect the `ecrpublic_repository` attribute `repository_uri` 👍

**Comment by eastenluis** [comment]
May I ask why the ECR public resource uses `repository_uri` instead of `repository_url`? That is different from ECR private one and I wonder if that's intentional.

**Comment by anGie44** [comment]
Hi @eastenluis 👋 we generally follow the AWS API naming conventions, so in this case the `CreateRepository` API method returns a `Repository` object type (defined here: https://docs.aws.amazon.com/AmazonECRPublic/latest/APIReference/API_Repository.html), which in turn has a nested `repository_uri` field ...why it maybe different from ECR public..i personally am not aware of the differentiation but definitely a good question for AWS :) !
