### ISSUE TITLE
Support Amazon ECS Exec settings on ECS cluster and service resources

### ISSUE THREAD

**Issue by trevorrea** [hashicorp/terraform-provider-aws#18334]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_ecs_cluster
*  aws_ecs_service

### Potential Terraform Configuration

```hcl
resource "aws_ecs_cluster" "foo" {
   name = "white-hart"
   executeCommandConfiguration = {
      kms_key_id = "string"
      logging =  "NONE"|"DEFAULT"|"OVERRIDE",
      logConfiguration =  {
        cloudWatchLogGroupName = "string"
        cloudWatchEncryptionEnabled = true|false
        s3BucketName": "string"
        s3EncryptionEnabled": true|false,
        s3KeyPrefix": "string"
      }
  }
}
```

```hcl
resource "aws_ecs_service" "mongo" {
  name            = "mongodb"
  cluster         = aws_ecs_cluster.foo.id
  task_definition = aws_ecs_task_definition.mongo.arn
  desired_count   = 3
  iam_role        = aws_iam_role.foo.arn
  depends_on      = [aws_iam_role_policy.foo]
  execute-command = true
}
```

**Comment by dimisjim** [comment]
the aws_ecs_service part is covered by https://github.com/hashicorp/terraform-provider-aws/issues/18112
