### ISSUE TITLE
aws_rds_cluster master_password change has no effect

### ISSUE THREAD

**Issue by ggoddemeier** [hashicorp/terraform-provider-aws#18345]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Tested with:
- Terraform 13.6 & 14 
- was 3.3.0 / 3.3.2

### Affected Resource(s)

* aws_rds_cluster
* master_password

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_rds_cluster" "pgsql" {
  provider = aws.db

  cluster_identifier      = "footest"
  engine                        = "aurora-postgresql"
  engine_version         = "11.6"
  master_username        = "smurf"
  master_password        = "foo"
  availability_zones = [
    "eu-central-1a",
    "eu-central-1b",
    "eu-central-1c"
  ]
  backup_retention_period = 5
  preferred_backup_window = "07:00-09:00"
  skip_final_snapshot     = true
  apply_immediately     = true
}
```

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_rds_cluster.pgsql will be updated in-place
  ~ resource "aws_rds_cluster" "pgsql" {
        id                                  = "footest"
      ~ master_password                     = (sensitive value)
        tags                                = {}
        # (29 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
### Expected Behavior

After changing the master_password value with a different value it should be updated in the RDS Cluster. This is not the case. Login is only possible with the old value

### Actual Behavior

master_password value is not updated but stated as will be updated in the tf plan

### Steps to Reproduce

1. `terraform plan' shows that master_password value will be changed when value is updated
2. 'terraform apply' is running without errors but not changing the master_password value

**Comment by ggoddemeier** [comment]
@gdavison do you need more info on this topic?

**Comment by chadmyers** [comment]
I believe this is a duplicate of #3220

Summary: By default in the RDS API, changing the master password will be applied during the next maintenance window (not immediately).  In the API, you can override this by setting `apply_immediately=true` but the Terraform AWS provider doesn't have the capability (at least at the time 3220 was created) to set this parameter.

**Comment by thatderek** [comment]
I don't know precisely what the documentation listed before, but [this page](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.DBInstance.Modifying.html) notes under `MasterPassword` that:
>The change is applied asynchronously, as soon as possible. This setting ignores the apply immediately setting.

I would expect Terraform to replicate that behavior insofar as `apply_immediately` could be null and changes to the `master_password` setting would be sent to the AWS RDS API and take effect immediately.
