### ISSUE TITLE
Unable to create Amazon MQ RabbitMQ broker with logging enabled.

### ISSUE THREAD

**Issue by lukaszkorecki** [hashicorp/terraform-provider-aws#18350]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/aws v3.33.0

### Affected Resource(s)

* aws_mq_broker

### Terraform Configuration Files

```hcl

resource "aws_mq_broker" "this" {
  broker_name = var.name

  subnet_ids = var.subnet_ids
  security_groups = var.security_group_ids

  deployment_mode = length(var.subnet_ids) == 1 ? "SINGLE_INSTANCE" : "CLUSTER_MULTI_AZ"

  publicly_accessible =  false

  engine_type = "RabbitMQ"
  engine_version           = "3.8.6"

  host_instance_type = var.instance_type


  # RabbitMQ only supports general logs, no audit logs 
  logs {
    general = true
    audit = false
  }

  user {
    username = var.username
    password = var.password
  }

  auto_minor_version_upgrade  = false

  maintenance_window_start_time {
    day_of_week = "SUNDAY"
    time_of_day = "03:00"
    time_zone = "UTC"
  }
}



```

### Expected Behavior

The broker should be created with general logs enabled.

### Actual Behavior

AWS throws an error:

```
module.rabbitmq.aws_mq_broker.this: Creating...

Error: BadRequestException: Audit logging is not supported for RabbitMQ brokers.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "35ad4197-8cd0-4a6a-a547-4700c568681c"
  },
  ErrorAttribute: "logs.audit",
  Message_: "Audit logging is not supported for RabbitMQ brokers."
}

```

### Steps to Reproduce

1. Create `variables.tf` with the following variables:
  - subnet_ids
  - security_group_ids
  - name
  - username
  - password

2.  then `main.tf` with above manifest.
3. `terraform apply`

**Comment by anGie44** [comment]
Relates #18067
