### ISSUE TITLE
Terraform doesn't wait for RDS proxy modification inside the module and breaks the state

### ISSUE THREAD

**Issue by uniit** [hashicorp/terraform-provider-aws#18358]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/aws v3.33.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
### Affected Resource(s)

* aws_db_proxy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

[Download](https://www.icloud.com/iclouddrive/0IlJvfFfgTg2fhuA_qbqnqAKA#tf%5Frds%5Fproxy%5Fissue)

### Expected Behavior

Terraform waits for RDS Proxy modification and spawns no errors. 

### Actual Behavior

Terraform doesn't wait for RDS Proxy modification and spawns errors in case we dynamically provision RDS Proxy inside a module. RDS Proxy state becomes broken. Terraform hangs every next time we want to change anything.

### Steps to Reproduce

1. `terraform apply -var-file configs/dev.tfvars`
2. Add a user to configs/dev.tfvars ("databases" dictionary - "user4" = "db4")
2. `terraform apply -var-file configs/dev.tfvars`. You will face the error:
```
Error: Error updating DB Proxy: InvalidDBProxyStateFault: DB Proxy db-proxy is in an unsupported state - MODIFYING_PROXY, needs to be in [ACTIVE]
        status code: 400, request id: 7812cfd8-c3d7-45dc-8933-6dcdbe3cd075
```
4. `terraform apply -var-file configs/dev.tfvars`. After all retries you will face the error:
```
Error: Error reading RDS DB Proxy (db-proxy): RequestError: send request failed
caused by: Post "https://rds.us-east-2.amazonaws.com/": net/http: HTTP/1.x transport connection broken: too many transfer encodings: ["chunked" "chunked"]
```

### Important Factoids

The same configuration works fine without a module and loops.

**Comment by tatodorov** [comment]
There is another related problem.
When I define more than 1 "auth" block and execute Terraform, it fails with:

```
Error: Error creating DB Proxy: DBProxyAlreadyExistsFault: DBProxy 'testdb01' already exists
        status code: 400, request id: 327a08c3-8ff2-4fee-81a6-6882345159f6

  on .terraform/modules/testdb/main.tf line 245, in resource "aws_db_proxy" "aurora":
 245: resource "aws_db_proxy" "aurora" {
```
The RDS proxy didn't exist before I executed Terraform.
After I get the above error, I can see in the AWS console that the RDS proxy is in status Creating.

If there is only 1 "auth" block, Terraform doesn't throw an error and creates the proxy successfully.
However, when I decide to add more "auth" blocks after the proxy is being created, Terraform fails with:

```
Error: Error updating DB Proxy: InvalidDBProxyStateFault: DB Proxy testdb01 is in an unsupported state - MODIFYING_PROXY, needs to be in [ACTIVE]
        status code: 400, request id: a03d39c9-996a-4d64-8e6b-a54e55489731

  on .terraform/modules/testdb/main.tf line 245, in resource "aws_db_proxy" "aurora":
 245: resource "aws_db_proxy" "aurora" {
```
I am using:
Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/aws v3.35.0

**Comment by tatodorov** [comment]
Just tried with the latest version of aws provider for Terraform and I still encounter the same error.
```
Terraform v0.15.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.37.0
```
With PR #19096 Terraform completes successfully.

**Comment by uniit** [comment]
Thanks, @tatodorov! I hope it'll be approved soon!
