### ISSUE TITLE
patch_filter for aws_ssm_patch_baseline

### ISSUE THREAD

**Issue by brianbuda** [hashicorp/terraform-provider-aws#18359]
On the AWS Console, you can select "All" for Product when creating a rule.  When using aws provider 3.33.0 and terraform 0.14.4 I receive the following error when trying to use "All"

Error: error updating SSM Patch Baseline (pb-01b2b6d3690271cdd): ValidationException: Invalid Filter Value: All for Key: PRODUCT, valid values are: AmazonLinux2012.03, AmazonLinux2012.09, AmazonLinux2013.03, AmazonLinux2013.09, AmazonLinux2014.03, AmazonLinux2014.09, AmazonLinux2015.03, AmazonLinux2015.09, AmazonLinux2016.03, AmazonLinux2016.09, AmazonLinux2017.03, AmazonLinux2017.09, AmazonLinux2018.03
        status code: 400, request id: 182ceadc-a34d-4c9f-bb85-99da49c5add0

**Comment by breathingdust** [comment]
Hi @brianbuda 👋  There is not enough information here for the maintainers or community to investigate. If this is still a problem, can you resubmit the issue using the supplied template and filling out all fields? Thank you!
