### ISSUE TITLE
Docs: Add MSK/kafka example to aws_appautoscaling_* examples 

### ISSUE THREAD

**Issue by mikegreen** [hashicorp/terraform-provider-aws#18363]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To add examples for AWS managed service for kafka/MSK autoscaling
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appautoscaling_target
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appautoscaling_scheduled_action
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appautoscaling_policy

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by alathers** [comment]
The below snippet seems to work for me.  I haven't tried to exercise it yet, but I do see the config manifest in the aws console, so it seems accurate.  

```
resource "aws_appautoscaling_target" "msk_datastory_target" {
  max_capacity       = format("%d", var.volume_size * 100)
  min_capacity       = 1
  resource_id         = aws_msk_cluster.msk_cluster.arn
  scalable_dimension  = "kafka:broker-storage:VolumeSize"
  service_namespace  = "kafka"
}

resource "aws_appautoscaling_policy" "msk_datastore_policy" {
  name = "${var.environment}-msk-cluster-scale-policy"
  service_namespace  = "kafka"
  resource_id         = aws_msk_cluster.msk_cluster.arn
  scalable_dimension = aws_appautoscaling_target.msk_datastory_target.scalable_dimension

  policy_type = "TargetTrackingScaling"
  target_tracking_scaling_policy_configuration {
    predefined_metric_specification {
      predefined_metric_type = "KafkaBrokerStorageUtilization"
    }
    target_value = 75
  }
}
```


Weird nuance: setting min_capacity to the value I had initially sized the instance storage to gave me an error:
```
Error: Error creating application autoscaling target: ValidationException: Minimum capacity cannot be greater than 1
```

**Comment by bryantbiggs** [comment]
FYI - if this helps anyone https://github.com/clowdhaus/terraform-aws-msk-kafka-cluster/blob/cdc8cd21f2ea3eeeadd6eb7bda00405c68c96001/main.tf#L149-L176
