### ISSUE TITLE
aws_ec2_transit_gateway_route fails consistently due to invalid API action

### ISSUE THREAD

**Issue by mf-lit** [hashicorp/terraform-provider-aws#18371]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform: 0.14.6
Provider: 3.33.0

### Affected Resource(s)

`aws_ec2_transit_gateway_route`

### Terraform Configuration Files

```
resource "aws_ec2_transit_gateway_route" "name" {
  destination_cidr_block         = "172.18.0.0/16"
  transit_gateway_attachment_id  = aws_ec2_transit_gateway_peering_attachment.name.id
  transit_gateway_route_table_id = aws_ec2_transit_gateway.name.association_default_route_table_id
}
```

### Expected Behavior

Transit Gateway Route is created successfully

### Actual Behavior

Transit Gateway Route is created successfully, but `apply` fails (and subsequent `plan`s fail) because Terraform can't read information about that route.

```
aws_ec2_transit_gateway_route.name: Creating...

error reading EC2 Transit Gateway Route: UnauthorizedOperation: You are not authorized to perform this operation.
status code: 403, request id: xxxxxx-yyyy-zzz
```

### Important Factoids

At first I thought this was a permissions issue, but even with full Admin access in IAM the issue occurs. Digging into the codebase looking for the error message leads me [here](https://github.com/hashicorp/terraform-provider-aws/blob/b6e34c1c4e123c9eb1c23c1c8182763727452679/aws/resource_aws_ec2_transit_gateway_route.go#L90):

```
transitGatewayRoute, err = ec2DescribeTransitGatewayRoute(conn, transitGatewayRouteTableID, destination)
```

Which is weird, as far as I can tell there is no such API action as`ec2DescribeTransitGatewayRoute`
at least not according to the [API reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/operation-list-tgw.html)

So as far as I can tell the `aws_ec2_transit_gateway_route` is completely broken.

**Comment by gdavison** [comment]
Hi @mf-lit. Could you please include more of your configuration, please? There isn't enough information to figure out what's happening here.

The function `ec2DescribeTransitGatewayRoute` is defined by the provider, at https://github.com/hashicorp/terraform-provider-aws/blob/b6e34c1c4e123c9eb1c23c1c8182763727452679/aws/ec2_transit_gateway.go#L81
