### ISSUE TITLE
Add enable_execute_command to aws_ecs_service

### ISSUE THREAD

**Issue by driskillb43** [hashicorp/terraform-provider-aws#18389]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has recently added support for being able to execute a command remotely to a container running within ECS. With this feature, they have added an enable_execute_command option that sets whether tasks running within the service allow a command to be remotely executed.

### New or Affected Resource(s)

* aws_ecs_service

### Potential Terraform Configuration

resource "aws_ecs_service" "test {
  enable_execute_command = true
}

### References

https://aws.amazon.com/blogs/containers/new-using-amazon-ecs-exec-access-your-containers-fargate-ec2/

* #0000

**Comment by ewbankkit** [comment]
@driskillb43 Thanks for raising this issue.
It has already been noticed in #18112. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
