### ISSUE TITLE
aws_apigatewayv2_route is missing support for request parameters

### ISSUE THREAD

**Issue by pedrodbsa** [hashicorp/terraform-provider-aws#18387]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

aws_apigatewayv2_route is missing the ability to configure request parameters as can be seen in this example: https://docs.aws.amazon.com/apigateway/latest/developerguide/websocket-api-data-mapping.html#websocket-data-mapping-examples

This makes forwarding headers (like Authorization) to an HTTP_PROXY integration fail with following error:

`Error: error updating API Gateway v2 integration: BadRequestException: Error while validating the connection between the integration <integration_id> and the route <route_id>: Invalid mapping expression parameter specified: route.request.header.authorization`

The only way to get this to work is by temporarily apply the configuration without the header forwarding request parameters, manually add the request parameters to the route using something like
`aws apigatewayv2 update-route --route-id <route-id>--api-id <api-id> --request-parameters '{"route.request.header.authorization": {"Required": false}}'` and then re-apply the configuration with the header forwarding in place.

### New or Affected Resource(s)

* aws_apigatewayv2_route

### Potential Terraform Configuration

```hcl
resource "aws_apigatewayv2_api" "example" {
  name                       = "example"
  protocol_type              = "WEBSOCKET"
  route_selection_expression = "$request.body.action"
}

resource "aws_apigatewayv2_route" "connect" {
  api_id = aws_apigatewayv2_api.example.id

  route_key                           = "$connect"
  route_response_selection_expression = "$default"

  request_parameters = {
    "route.request.header.authorization" = true
  }

  target = "integrations/${aws_apigatewayv2_integration.connect.id}"
}

resource "aws_apigatewayv2_integration" "connect" {
  api_id = aws_apigatewayv2_api.example.id

  integration_type   = "HTTP_PROXY"
  integration_method = "ANY"
  integration_uri    = var.integration_uri

  request_parameters = {
    "integration.request.header.authorization" = "route.request.header.authorization"
    "integration.request.header.connectionId"  = "context.connectionId"
  }
}
```

### References

* https://docs.aws.amazon.com/apigateway/latest/developerguide/websocket-api-data-mapping.html#websocket-data-mapping-examples
* https://docs.aws.amazon.com/cli/latest/reference/apigatewayv2/create-route.html
* https://docs.aws.amazon.com/apigateway/latest/developerguide/samples/websocket-data-mapping.zip

**Comment by ewbankkit** [comment]
Given the structure of the underlying [AWS API](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/apis-apiid-routes-routeid.html#apis-apiid-routes-routeid-prop-updaterouteinput-requestparameters), I suggest a slightly more complex configuration syntax:

```hcl
resource "aws_apigatewayv2_route" "connect" {
  api_id = aws_apigatewayv2_api.example.id

  route_key                           = "$connect"
  route_response_selection_expression = "$default"

  request_parameter {
    request_parameter_key = "route.request.header.authorization"
    required              = true
  }

  target = "integrations/${aws_apigatewayv2_integration.connect.id}"
}
```

**Comment by pedrodbsa** [comment]
Looks perfectly fine to me. 

My suggestion was based on this one https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_method#request_parameters but to be honest I wouldn't be able to say if it fits or not - was mainly for consistency sake.

**Comment by ewbankkit** [comment]
The underlying problem is that the current Plugin SDK does not support maps with values anything other than simple types:

https://github.com/hashicorp/terraform-plugin-sdk/blob/b5604678a4d0326c5c94366bb89bb7d3ad06bc29/helper/schema/schema.go#L790-L796

AWS has the map key for a request parameter as a `struct` (which today only has one field, `required`, but we don't want to get into a situation where AWS adds another field to this structure and we can't easily project that into provider attributes).
This is similar to the situation with `aws_apigatewayv2_stage.route_settings`.
