### ISSUE TITLE
aws_elastic_beanstalk_environment with multiple `setting{}` block reports changes every time, even when there aren't any

### ISSUE THREAD

**Issue by briandilley** [hashicorp/terraform-provider-aws#18393]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_elastic_beanstalk_environment

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_elastic_beanstalk_environment" "platform_worker_server" {
  tags = {
    Environment = var.environment_name
    ManagedBy   = "Terraform"
  }

  name                = "${var.environment_name}-platform-workerserver"
  application         = var.aws_elastic_beanstalk_application
  solution_stack_name = "64bit Amazon Linux 2 v3.1.6 running Corretto 11"
  tier                = "Worker"

  setting {
    namespace = "aws:elasticbeanstalk:command"
    name      = "BatchSize"
    value     = var.deployment_batch_size_percent
    resource = ""
  }

  setting {
    namespace = "aws:autoscaling:trigger"
    name      = "BreachDuration"
    value     = var.scaling_trigger_breach_duration
    resource = ""
  }

  setting {
    namespace = "aws:autoscaling:asg"
    name      = "Cooldown"
    value     = "30"
    resource = ""
  }

  setting {
    namespace = "aws:autoscaling:launchconfiguration"
    name      = "InstanceType"
    value     = var.instance_type
    resource = ""
  }

  setting {
    namespace = "aws:autoscaling:launchconfiguration"
    name      = "EC2KeyName"
    value     = var.ssh_key_name
    resource = ""
  }

  setting {
    namespace = "aws:autoscaling:launchconfiguration"
    name      = "IamInstanceProfile"
    value     = var.instance_profile_name
    resource = ""
  }

  setting {
    namespace = "aws:autoscaling:launchconfiguration"
    name      = "MonitoringInterval"
    value     = var.monitoring_interval
    resource = ""
  }
...
}
```

### Expected Behavior
Don't show changes when there are none

### Actual Behavior
Shows changes when there are none

### Steps to Reproduce
1. `terraform apply` (apply changes)
2. `terraform apply` (run immediately, it shows changes in settings blocks)

**Comment by svenlito** [comment]
`settings` blocks take a `resource` argument, setting it to `""` will resolve this.

**Comment by briandilley** [comment]
@svenlito sorry - that didn't help.

**Comment by miguelaferreira** [comment]
@briandilley could your issue be a duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/12889?
