### ISSUE TITLE
State Change with not Change Bug has Returned.

### ISSUE THREAD

**Issue by scoleri** [hashicorp/terraform-provider-aws#18407]
Bug from [https://github.com/hashicorp/terraform-provider-aws/issues/13721](url) was resolved in 3.31.0 returned in >3.32.0.

This was resolved and I was very happy especially when rolling/detecting IAM changes in infra.

When running terraform the state gets updated regardless of the fact there has been no actual change.

It has something to do with the placement in the file/state of the resources.

**Comment by scoleri** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/13721 [https://github.com/hashicorp/terraform-provider-aws/issues/13721](url)

**Comment by breathingdust** [comment]
Hi @scoleri! 👋 If this is still an issue would you be able to resubmit filling out the issue template with all required fields? It looks like your original report was fixed, and that change has not been reverted so something else must be at play. Thank you!
