### ISSUE TITLE
AWS Cloud Map now supports API-only services in namespaces configured with DNS resolution

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#18401]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> You can now manage non-IP based cloud resources in AWS Cloud Map’s public and private DNS namespaces.

### New or Affected Resource(s)

* [`aws_service_discovery_service`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/service_discovery_service)

### Potential Terraform Configuration

```hcl
resource "aws_service_discovery_service" "example" {
  name = "example"

  type = "HTTP"
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2021/03/aws-cloud-map-now-supports-api-only-services-in-namespaces-configured-with-dns-resolution/).
[Developer Guide](https://docs.aws.amazon.com/cloud-map/latest/dg/services-values.html#service-creating-values-service-discovery-configuration).

Requires [AWS SDK v1.37.24](https://github.com/aws/aws-sdk-go/releases/tag/v1.37.24).

**Comment by matt-land** [comment]
Here is a workaround for anyone else that needs this:
```
resource "aws_cloudformation_stack" "service-api" {
  name          = "ServiceDiscoveryApi-${var.service_name}"
  template_body = <<STACK
{
  "Resources" : {
    "CloudMapServiceApi": {
      "Type" : "AWS::ServiceDiscovery::Service",
      "Properties" : {
        "Name" : "${var.service_name}",
        "Description" : "${var.service_description}",
        "NamespaceId" : "${var.namespace_id}",
        "Type" : "HTTP"
      }
    }
  },
  "Outputs" : {
    "id": {
      "Value" :  {"Fn::GetAtt" : ["CloudMapServiceApi", "Id"]}
    },
    "arn": {
      "Value" :  {"Fn::GetAtt" : ["CloudMapServiceApi", "Arn"]}
    },
    "name": {
      "Value" :  {"Fn::GetAtt" : ["CloudMapServiceApi", "Name"]}
    }
  }
}
STACK
}
```
