### ISSUE TITLE
No ability to download KMS public key for asymetric customer managed keys

### ISSUE THREAD

**Issue by rabidscorpio** [hashicorp/terraform-provider-aws#18411]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
There's currently no way to download the KMS public key for an asymetric customer managed key even though it's possible through both the console and the API.
### New or Affected Resource(s)

* aws_kms_key

### Potential Terraform Configuration

```hcl
resource "aws_kms_key" "a" {
  description             = "KMS key 1"
  deletion_window_in_days = 10
}

resource "helm_release" "main" {
  ...

  set {
    app.public_key = aws_kms_key.a.public_key
  }
}
  
```

### References

Public key downloads are supported by the aws golang sdk:
* https://github.com/aws/aws-sdk-go/blob/main/service/kms/api.go#L4059
* https://docs.aws.amazon.com/kms/latest/developerguide/download-public-key.html

**Comment by ewbankkit** [comment]
@rabidscorpio Thanks for raising this issue.
The [`aws_kms_public_key` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/kms_public_key) provides access to the public key value.
