### ISSUE TITLE
Support for Ec2Configuration in AWS Batch Compute Environment

### ISSUE THREAD

**Issue by mbiokyle29** [hashicorp/terraform-provider-aws#18414]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the `aws_batch_compute_environment` resource does not support the `EC2Configuration` block defined here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-computeenvironment-computeresources.html#cfn-batch-computeenvironment-computeresources-ec2configuration

The feature request is to update the resource to allow for specifying this block.

### New or Affected Resource(s)

* aws_batch_compute_environment

### Potential Terraform Configuration

```hcl
resource "aws_batch_compute_environment" "sample" {
  compute_environment_name = "sample"
  ...
  compute_resources {
      ec2_configuration {
            image_type =  "ECS_AL2"
      }
  }
  ...
}
```

**Comment by mbiokyle29** [comment]
Great work @ijin! Thank you so much!

**Comment by ijin** [comment]
@mbiokyle29 I happened to need this feature too! :D
