### ISSUE TITLE
cloudfront: 'data' support for aws_cloudfront_realtime_log_config

### ISSUE THREAD

**Issue by zarnovican** [hashicorp/terraform-provider-aws#18426]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Could you please add support to reference `aws_cloudfront_realtime_log_config` via data object ?

Example use-case: Single real-time logging configuration is created once in one Terraform project, but then it is referenced from multiple CloudFronts in different Terraform projects.

### New or Affected Resource(s)

* data.aws_cloudfront_realtime_log_config

### Potential Terraform Configuration

```hcl
data "aws_cloudfront_realtime_log_config" "cf_log" {
  name = "cf_log"
}

...
   ordered_cache_behavior {
      ...
     realtime_log_config_arn = data.aws_cloudfront_realtime_log_config.cf_log.arn
   }
```

**Comment by danquack** [comment]
https://docs.aws.amazon.com/sdk-for-go/api/service/cloudfront/#CloudFront.GetRealtimeLogConfig
