### ISSUE TITLE
Missing update assume role policy on existing role resource https://docs.aws.amazon.com/cli/latest/reference/iam/update-assume-role-policy.html

### ISSUE THREAD

**Issue by alexmnyc** [hashicorp/terraform-provider-aws#18429]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by breathingdust** [comment]
Hi @alexmnyc 👋 I can't tell what this issue is requesting, please resubmit explaining what you need by filling in the issue template.

**Comment by efernandes-dev-ops** [comment]
@alexmnyc Did you find a way to do this in terraform?
