### ISSUE TITLE
Add support for setting auto tune options in aws_elasticsearch_domain

### ISSUE THREAD

**Issue by tdmalone** [hashicorp/terraform-provider-aws#18421]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for specifying new Auto Tune options for Amazon Elasticsearch Clusters.

### New or Affected Resource(s)

* [aws_elasticsearch_domain](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain)

### Potential Terraform Configuration

```hcl
resource "aws_elasticsearch_domain" "example" {
  ...
  auto_tune_options {
    desired_state       = "ENABLED"          # Valid values ENABLED, DISABLED
    rollback_on_disable = "DEFAULT_ROLLBACK" # Valid values NO_ROLLBACK, DEFAULT_ROLLBACK

    maintenance_schedule {
      start_at                       = "2021-04-01T00:00:00Z"
      duration                       = "1" # or separate into eg. 'duration = { value = 1, unit = "HOURS" }', but HOURS is the only valid unit
      cron_expression_for_recurrence = "* * * * *"
    }
  }
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2021/03/amazon-elasticsearch-service-announces-auto-tune-feature-improved-performance-application-availability
* https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/auto-tune.html
* Requires [AWS SDK v1.35.22](https://github.com/aws/aws-sdk-go/releases/tag/v1.37.18) (#17802)
* Might be able to be implemented at the same time as #16059?

**Comment by tdmalone** [comment]
Current workaround (note: untested):
```
resource "null_resource" "auto_tune_options" {
  provisioner "local-exec" {
    command = <<-EOF
      aws es update-elasticsearch-domain-config \
        --domain-name "${aws_elasticsearch_domain.main.domain_name}" \
        --auto-tune-options '{
          "DesiredState": "ENABLED",
          "RollbackOnDisable": "DEFAULT_ROLLBACK",
          "MaintenanceSchedules": [{
            "StartAt": "2021-04-01T00:00:00Z",
            "Duration": {"Value": 1, "Unit": "HOURS"},
            "CronExpressionForRecurrence": "* * * * *"
          }]
        }'
    EOF
  }
}
```

**Comment by oscarwest** [comment]
Looking forward to seeing this in the resource.

**Comment by nnovaes** [comment]
does anyone know if enabling auto tune from the console causes any issues with terraform?

**Comment by jgrumboe** [comment]
@maxeaubrey
Hi, I'm still very new to Go and Terraform development. It would be cool to have this feature.
I don't know if this is a practise which is used somewhere in aws provider, but wouldn't a simple "if" statement around auto-tune options checking a minimum value of elasticsearch_version do the trick?
