### ISSUE TITLE
aws_lakeformation_permissions throwing "no permissions found" for wildcard table

### ISSUE THREAD

**Issue by josh-aguilar** [hashicorp/terraform-provider-aws#18446]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform: v0.13.5
Provider: v0.34.0

### Affected Resource(s)

* aws_lakeformation_permissions

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_lakeformation_permissions" "test" {
  principal = "arn:aws:iam::XXXXXXXXXXXX:role/MyRole"
  permissions = ["ALL", "ALTER", "DELETE", "DESCRIBE", "DROP", "INSERT", "SELECT"]
  permissions_with_grant_option = ["ALL", "ALTER", "DELETE", "DESCRIBE", "DROP", "INSERT", "SELECT"]
  table {
    database_name = "my_database"
    wildcard = true
  }
}
```

### Expected Behavior

Running a `terraform apply` should succeed without any error messages.

### Actual Behavior

When running a `terraform apply` the permissions are applied successfully as shown in this screenshot.
![Screen Shot 2021-03-29 at 12 46 52 PM](https://user-images.githubusercontent.com/13978147/112772380-eebb3700-908c-11eb-94f7-a94a0753c6e0.png)

However, terraform throws the following error after finishing.
```
Error: error reading Lake Formation permissions: no permissions found
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

* Only happens when `wildcard` is set to true for the `table` argument.
* This error only started showing up after version `v3.33.0` of the AWS provider was released which included this fix
https://github.com/hashicorp/terraform-provider-aws/pull/18203
* Downgrading the provider to `v3.32.0` seems to work for us at the moment but would be good to have the latest version working.

**Comment by brunhil** [comment]
I can take a look at this one considering I caused it 😊 . I know the fix and just want to write a test first to confirm the situation here

**Comment by YakDriver** [comment]
Related #16848
Related #17633
Related #18374
Related #18446
Related #18505
Related #19063
Related #19064

**Comment by akuzni2** [comment]
That would be great to get a fix for this one - currently I have to write a block of TF to specify permissions for every table in my lake formation DB.
