### ISSUE TITLE
resource/aws_elasticache_replication_group, data_source/aws_elasticache_replication_group: Remove deprecated parameters

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#18441]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

#18440 deprecates the following parameters on resource and data source `aws_elasticache_replication_group`. Remove them.

Resource:
* `number_cache_clusters`
* `cluster_mode`
* `replication_group_description`

Data Source:
* `number_cache_clusters`
* `replication_group_description`

**Comment by rahul-amzn** [comment]
I will look into this.

**Comment by rquadling** [comment]
I'm having issues with `terraform validate -json` with these deprecations (https://github.com/hashicorp/terraform-provider-aws/issues/22903). Would appreciate a "it's us, not you" answer as I'm not sure what's happening.

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/22666.

**Comment by jar-b** [comment]
Closed by #31008, merged to `main` via #31392
