### ISSUE TITLE
resource/aws_elasticache_replication_group, data_source/aws_elasticache_replication_group: Migrate to parameters matching API parameters

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#18440]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The resource and data source `aws_elasticache_replication_group` have a number of parameters that do not match the API parameters. New parameters matching the API parameters should be added to the resource and data source.

Resource:
* add `num_cache_clusters`, deprecate `number_cache_clusters`
* add `num_node_groups` and `replicas_per_node_group`, deprecate `cluster_mode`
* add `description`, deprecate `replication_group_description`

Data Source:
* add `num_cache_clusters`, deprecate `number_cache_clusters`
* add `num_node_groups` and `replicas_per_node_group`
* add `description`, deprecate `replication_group_description`

**Comment by anGie44** [comment]
Addressed in #22666 and #22667
