### ISSUE TITLE
Error: Provider produced inconsistent result after apply AWS_IAM_ROLE_ATTACHMENT_TASK

### ISSUE THREAD

**Issue by McCo0L** [hashicorp/terraform-provider-aws#18457]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.33.0

### Affected Resource(s)

* aws_iam_role_policy_attachment

* aws_XXXXX

### Terraform Configuration Files

```hcl
resource "aws_iam_role" "ecs_task_execution_role" {
  name = "executionRole"

  assume_role_policy = <<EOF
{
 "Version": "2012-10-17",
 "Statement": [
   {
     "Action": "sts:AssumeRole",
     "Principal": {
       "Service": "ecs-tasks.amazonaws.com"
     },
     "Effect": "Allow",
     "Sid": ""
   }
 ]
}
EOF
}

resource "aws_iam_role_policy_attachment" "task_cw" {
  role       = aws_iam_role.ecs_task_execution_role.name
  policy_arn = "arn:aws:iam::aws:policy/CloudwatchFullAccess"
}
```

### Expected Behavior

Succesfully attach the policy to the role 

### Actual Behavior

Error: Provider produced inconsistent result after apply

When applying changes to module.ecs.aws_iam_role_policy_attachment.task_cw,
provider "registry.terraform.io/hashicorp/aws" produced an unexpected new
value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to Reproduce

1. `terraform apply`

* #0000

**Comment by bflad** [comment]
Hi @McCo0L 👋  Thank you for reporting this and sorry you ran into trouble there. We plan on fixing this issue with the resource shortly (e.g. https://github.com/hashicorp/terraform-provider-aws/pull/18435).
