### ISSUE TITLE
Modifying a dms replication task type should taint resource

### ISSUE THREAD

**Issue by pancochea** [hashicorp/terraform-provider-aws#18450]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_dms_replication_task

### Terraform Configuration Files

```terraform
resource "aws_dms_replication_task" "testing-replication-task" {
  migration_type           = "cdc"
  replication_instance_arn = aws_dms_replication_instance.replication instance.replication_instance_arn
  replication_task_id      =  "test-replication"
  source_endpoint_arn      = aws_dms_endpoint.source.endpoint_arn

  target_endpoint_arn = aws_dms_endpoint.target.endpoint_arn

}
```
Modified configuration:
```terraform
resource "aws_dms_replication_task" "testing-replication-task" {
  migration_type           = "full-load"
  replication_instance_arn = aws_dms_replication_instance.replication instance.replication_instance_arn
  replication_task_id      =  "test-replication"
  source_endpoint_arn      = aws_dms_endpoint.source.endpoint_arn

  target_endpoint_arn = aws_dms_endpoint.target.endpoint_arn

}
```

### Expected Behavior

The resource type is changed.

### Actual Behavior

An error raises stating that the resource type cannot be modified at this moment:

Error: InvalidResourceStateFault: Replication Task, excluding logging severity task settings, cannot be modified while it is running state

### Steps to Reproduce

1. `terraform apply`
2. Wait for resources to be avaliable
3. Change the replication type configuration of that resource.
4. `terraform plan` will state that the resource type will be changed
5. `terraform apply` fails

### Important Factoids

Changing the replication type of an existing should destroy and recreate the resource. From the GUI and the api this parameter cannot be modified.

The aws-cli states that using the modify-replication-task command is able to perform this change, but running it raises the same error (as expected), so it could be an error from the aws API, or a combination of the current replication task type and the new target type.

### References

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/dms/modify-replication-task.html

**Comment by anGie44** [comment]
Hi @pancochea , thank you for raising this issue! looking at the AWS documentation, looks like we need to be stopping the task before performing any modifications (https://docs.aws.amazon.com/dms/latest/APIReference/API_ModifyReplicationTask.html). we don't currently do so; instead we directly call `ModifyReplicationTask`.  afict, modifying the `migration_type` is technically supported, so we'll have to update the resource's `Update` logic to include a call to`StopReplicationTask` and give it a try in a new acceptance test 👍

**Comment by pancochea** [comment]
Hi @anGie44,  just to let you know, if you are going to change the Update behavior to stop a task, I think this issue #16092  and the linked pull request will be useful (https://github.com/hashicorp/terraform-provider-aws/issues/16092). That issue has been aroudn for quite a while and will solve a lot of problems.

**Comment by anGie44** [comment]
Thank you @pancochea for linking the issue! 

Noting this also relates to: https://github.com/hashicorp/terraform-provider-aws/issues/2236

**Comment by fermezz** [comment]
Stopping the task is one part of the problem, which was solved by a PR of mine. But I think this issue still stands. AWS won't allow the task type to be modified _even if the task is stopped_. I think we need to modify the logic to destroy the task if this parameter is changed.
