### ISSUE TITLE
RDS DB Auth Token Data Source for IAM Authentication

### ISSUE THREAD

**Issue by lawliet89** [hashicorp/terraform-provider-aws#18455]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add a new data source similar to `aws_eks_cluster_auth` to generate what is essentially a signed URL to authenticate with RDS databases via IAM authentication.

### New or Affected Resource(s)

* data.aws_rds_auth_token

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

data "aws_rds_auth_token" "instance" {
  hostname = "...."
  port = 5432
  username = "..."
}
```

### References

- https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.Go.html

**Comment by jlsalmon** [comment]
Having this would be a great enhancement, as it would eliminate the need to store the RDS master password in Terraform state.
