### ISSUE TITLE
resource/aws_elasticache_cluster: Add Outpost support

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#18460]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add Outpost support to `aws_elasticache_cluster`.

### Potential Terraform Configuration

New fields:

```terraform
resource "aws_elasticache_cluster" "example" {
  ...
  outpost_mode = "single-outpost" # Valid values: "single-outpost" and "cross-outpost"

  preferred_outpost_arn = "<valid ARN>"
}
```

Note: only `single-outpost` is currently supported.

Note: `CreateCacheClusterInput` has both a single `PreferredOutpostArn` and list `PreferredOutpostArns`, but `CacheCluster` only has the field `PreferredOutpostArn` and does not have the field `OutpostMode`.

### Affected Resource

* resource/aws_elasticache_cluster
* data source/aws_elasticache_cluster

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* ElastiCache for Redis: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/ElastiCache-Outposts.html
* ElastiCache for Memcached: https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/ElastiCache-Outposts.html

**Comment by weizhangfd** [comment]
👋  @gdavison I have made a PR for this enhancement, but I don't seem to have push right to the repo. Would you mind giving me the write access please? 🙏
