### ISSUE TITLE
argument "email" is not required anymore on aws_securityhub_member

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [hashicorp/terraform-provider-aws#18469]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform CLI v0.14.9
Terraform AWS Provider v3.34.0

### Affected Resource(s)

* aws_securityhub_member

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "aws_caller_identity" "current" {}

resource "aws_organizations_account" "account" {
  name  = "an_account"
  email = "example@domain.com"
}

resource "aws_securityhub_account" "account" {}

resource "aws_securityhub_organization_admin_account" "account" {
  depends_on       = [aws_securityhub_account.account]
  admin_account_id = data.aws_caller_identity.current.account_id
}

resource "aws_securityhub_member" "member" {
  depends_on = [aws_securityhub_organization_admin_account.account]
  account_id = aws_organizations_account.account.id
}
```

### Output

```
Error: Missing required argument

  on securityhub/securityhub_member.tf line 0, in resource "aws_securityhub_member" "member":
  0: resource "aws_securityhub_member" "member" {

The argument "email" is required, but no definition was found.
```

### Expected Behavior

The resource should have been created.

### Actual Behavior

An error is thrown.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

The account that I tried to apply the resource is the account delegated to be the administrator of Security Hub inside the AWS Organization.

The e-mail is not a required field anymore, as accounts member of the same AWS Organization can be added to Security Hub by the delegated administrator without the invitation process.

<img width="1456" alt="Screen Shot 2021-03-29 at 6 58 05 PM" src="https://user-images.githubusercontent.com/7753096/112906096-f8ab5d00-90c1-11eb-85d3-4e07033fe8f0.png">

### References

* https://docs.aws.amazon.com/securityhub/latest/userguide/designate-orgs-admin-account.html
* https://docs.aws.amazon.com/securityhub/latest/userguide/orgs-accounts-enable.html#accounts-orgs-enable-api

**Comment by yair-sedaka** [comment]
Any update regarding this issue?
