### ISSUE TITLE
AWS NAT Gateway - Computed attributes cannot be set, but a value was set for "allocation_id"

### ISSUE THREAD

**Issue by gordysc** [hashicorp/terraform-provider-aws#18482]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```sh
Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/aws v3.34.0
```

### Affected Resource(s)

* aws_nat_gateway

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_vpc" "default" {
  cidr_block = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support = true

  tags = {
    Name = "vpc-dev"
  }
}

resource "aws_subnet" "public" {
  cidr_block = "10.0.1.0/24"
  vpc_id = aws_vpc.default.id
  availability_zone = "us-east-1a"

  depends_on = [aws_internet_gateway.default]

  tags = {
    Name = "subnet-public-dev"
    AZ="us-east-1a"
  }
}

resource "aws_internet_gateway" "default" {
  vpc_id = aws_vpc.default.id

  tags = {
    Name = "internet-gateway-dev"
  }
}

resource "aws_eip" "nat_eip" {
  vpc = true

  tags = {
    Name = "nat-eip-dev"
    AZ="us-east-1a"
  }
}

data "aws_nat_gateway" "default" {
  subnet_id = aws_subnet.public.id
  allocation_id = aws_eip.nat_eip.id

  depends_on = [aws_internet_gateway.default, aws_eip.nat_eip]

  tags = {
    Name = "nat-gateway-dev"
    AZ="us-east-1a"
  }
}
```

### Debug Output

Link to the GIST can [be found here](https://gist.github.com/gordysc/5d8f99c1dc4feee47ef6e933c33c393a)

### Panic Output

_None_

### Expected Behavior

Terraform would return the following:

```sh
Success! The configuration is valid.
```

### Actual Behavior

```sh
on main.tf line 47, in data "aws_nat_gateway" "default":
  47:   allocation_id = aws_eip.nat_eip.id

Computed attributes cannot be set, but a value was set for "allocation_id".
```

Terraform is complaining about the allocation_id cannot be set as it's computed.  However, the documentation states that this field is required: [docs/resources/nat_gateway](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/nat_gateway).   If I comment out allocation_id it does validate successfully (when I'd expect it to fail).  However, it'll fail when doing a `terraform apply` with the following:

```sh
data.aws_nat_gateway.default: Reading...

Error: no matching NAT gateway found: {
  Filter: [
    {
      Name: "subnet-id",
      Values: ["subnet-0240b29c49944ea06"]
    },
    {
      Name: "tag:Name",
      Values: ["nat-gateway-dev"]
    },
    {
      Name: "tag:AZ",
      Values: ["us-east-1a"]
    },
  ]
}

  on main.tf line 87, in data "aws_nat_gateway" "default":
  87: data "aws_nat_gateway" "default" {
  ```

### Steps to Reproduce

1. `terraform validate`

### Important Factoids

_None_

### References

 _None_

**Comment by ewbankkit** [comment]
@gordysc Thanks for raising this issue.
The documentation for the `aws_nat_gateway` data source is [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/nat_gateway).
Are you looking to create the NAT Gateway, in which case you should change

```hcl
data "aws_nat_gateway" "default" {
  subnet_id = aws_subnet.public.id
  allocation_id = aws_eip.nat_eip.id

  depends_on = [aws_internet_gateway.default, aws_eip.nat_eip]

  tags = {
    Name = "nat-gateway-dev"
    AZ="us-east-1a"
  }
}
```

to

```hcl
resource "aws_nat_gateway" "default" {
  subnet_id = aws_subnet.public.id
  allocation_id = aws_eip.nat_eip.id

  depends_on = [aws_internet_gateway.default, aws_eip.nat_eip]

  tags = {
    Name = "nat-gateway-dev"
    AZ="us-east-1a"
  }
}
```

**Comment by gordysc** [comment]
Ugh, I'm an idiot.  Mahalo @ewbankkit
