### ISSUE TITLE
Support no-ingress EC2 instance for Cloud9 environment

### ISSUE THREAD

**Issue by AriHerna** [hashicorp/terraform-provider-aws#18487]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Could you please add the ability to choose the environment type for a new Cloud9 environment? The following environment types are available in the AWS Console: 

- Direct access
- Access via Systems Manager
- SSH connection

Terraform always creates Direct access instances since there is no way to choose a different one.

### New or Affected Resource(s)

aws_cloud9_environment_ec2

### Potential Terraform Configuration

```hcl
resource "aws_cloud9_environment_ec2" "example" {
  name              = "example-env"
  environment_type  = "ssm_access"
  platform          = "ubuntu_server_18_04" 
}
```

Thank you so much! ✨

**Comment by johnthedev97** [comment]
I have made an attempt to implement this here - https://github.com/hashicorp/terraform-provider-aws/pull/19195
