### ISSUE TITLE
Panic at Terraform 0.15-beta: can't use ElementIterator on unknown value

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#18484]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.15.0-beta2
AWS provider v3.32.0

### Affected Resources/Data Sources

* ds/aws_elasticsearch_domain
* r/aws_appsync_datasource
* r/aws_elasticsearch_domain_policy
* r/aws_kinesis_firehose_delivery_stream
* r/aws_opsworks_application
* r/aws_opsworks_custom_layer
* r/aws_opsworks_ganglia_layer
* r/aws_opsworks_haproxy_layer
* r/aws_opsworks_instance
* r/aws_opsworks_java_app_layer
* r/aws_opsworks_memcached_layer
* r/aws_opsworks_mysql_layer
* r/aws_opsworks_nodejs_app_layer
* r/aws_opsworks_permission
* r/aws_opsworks_php_app_layer
* r/aws_opsworks_rails_app_layer
* r/aws_opsworks_rds_db_instance
* r/aws_opsworks_static_web_layer

### Failing tests

1. TestAccAwsAppsyncDatasource_ElasticsearchConfig_Region
1. TestAccAwsAppsyncDatasource_Type_Elasticsearch
1. TestAccAWSDataElasticsearchDomain_basic
1. TestAccAWSElasticSearchDomainPolicy_basic
1. TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigEndpointUpdates
1. TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigUpdates
1. TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchWithVpcConfigUpdates
1. TestAccAWSOpsworksApplication_basic
1. TestAccAWSOpsworksCustomLayer_basic
1. TestAccAWSOpsworksCustomLayer_noVPC
1. TestAccAWSOpsworksCustomLayer_tags
1. TestAccAWSOpsworksGangliaLayer_basic
1. TestAccAWSOpsworksGangliaLayer_tags
1. TestAccAWSOpsworksHAProxyLayer_basic
1. TestAccAWSOpsworksHAProxyLayer_tags
1. TestAccAWSOpsworksInstance_basic
1. TestAccAWSOpsworksInstance_UpdateHostNameForceNew
1. TestAccAWSOpsworksJavaAppLayer_basic
1. TestAccAWSOpsworksJavaAppLayer_tags
1. TestAccAWSOpsworksMemcachedLayer_basic
1. TestAccAWSOpsworksMemcachedLayer_tags
1. TestAccAWSOpsworksMysqlLayer_basic
1. TestAccAWSOpsworksMysqlLayer_tags
1. TestAccAWSOpsworksNodejsAppLayer_basic
1. TestAccAWSOpsworksNodejsAppLayer_tags
1. TestAccAWSOpsworksPermission_basic
1. TestAccAWSOpsworksPermission_Self
1. TestAccAWSOpsworksPhpAppLayer_basic
1. TestAccAWSOpsworksPhpAppLayer_tags
1. TestAccAWSOpsworksRailsAppLayer_basic
1. TestAccAWSOpsworksRailsAppLayer_tags
1. TestAccAWSOpsworksRdsDbInstance_basic
1. TestAccAWSOpsworksStaticWebLayer_basic
1. TestAccAWSOpsworksStaticWebLayer_tags

### Terraform Configuration Files

See individual tests.

### Panic Output

```
    data_source_aws_elasticsearch_domain_test.go:17: Step 1/1 error: Error running pre-apply refresh: exit status 2
        panic: can't use ElementIterator on unknown value
        
        goroutine 120 [running]:
        github.com/zclconf/go-cty/cty.Value.ElementIterator(0x2c020b8, 0xc001896e40, 0x23a6120, 0x3caae20, 0xc00069a2a0, 0x19)
        	/go/pkg/mod/github.com/zclconf/go-cty@v1.8.1/cty/value_ops.go:1113 +0x13b
        github.com/hashicorp/terraform/terraform.getValMarks(0xc00124c330, 0x2c02128, 0xc001897370, 0x23cfa00, 0xc002a1adb0, 0x0, 0x0, 0x0, 0x4010100, 0x0, ...)
        	/home/circleci/project/project/terraform/evaluate.go:992 +0x6c5
        github.com/hashicorp/terraform/terraform.markProviderSensitiveAttributes(0xc00124c330, 0x2c02128, 0xc001897370, 0x23cfa00, 0xc002a1adb0, 0x2c02128, 0xc001897370, 0x23cfa00, 0xc002a1adb0)
        	/home/circleci/project/project/terraform/evaluate.go:959 +0x6e
        github.com/hashicorp/terraform/terraform.(*evaluationStateData).GetResource(0xc000456fc0, 0x4d, 0xc000058708, 0x18, 0xc0001a69c8, 0x4, 0xc0000581e0, 0x18, 0x3d, 0x11, ...)
        	/home/circleci/project/project/terraform/evaluate.go:762 +0xbd5
        github.com/hashicorp/terraform/lang.(*Scope).evalContext(0xc001eb1f90, 0xc0017dc3f0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x30)
        	/home/circleci/project/project/lang/eval.go:360 +0x206d
        github.com/hashicorp/terraform/lang.(*Scope).EvalContext(...)
        	/home/circleci/project/project/lang/eval.go:238
        github.com/hashicorp/terraform/lang.(*Scope).EvalBlock(0xc001eb1f90, 0x2c00bb8, 0xc002997470, 0xc0017221b0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        	/home/circleci/project/project/lang/eval.go:51 +0xf3
        github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateBlock(0xc001144b60, 0x2c00e58, 0xc002997470, 0xc0017221b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        	/home/circleci/project/project/terraform/eval_context_builtin.go:273 +0x1ad
        github.com/hashicorp/terraform/terraform.(*NodeAbstractResourceInstance).planDataSource(0xc000452000, 0x2c37770, 0xc001144b60, 0x0, 0x1, 0x1, 0x0, 0x0, 0x0)
        	/home/circleci/project/project/terraform/node_resource_abstract_instance.go:1350 +0x515
        github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).dataResourceExecute(0xc0018964e0, 0x2c37770, 0xc001144b60, 0xc000000001, 0xc0007a3118, 0xc002565c80)
        	/home/circleci/project/project/terraform/node_resource_plan_instance.go:73 +0x478
        github.com/hashicorp/terraform/terraform.(*NodePlannableResourceInstance).Execute(0xc0018964e0, 0x2c37770, 0xc001144b60, 0xc000180002, 0xc002565d18, 0x40bb05, 0x2418a80)
        	/home/circleci/project/project/terraform/node_resource_plan_instance.go:43 +0x10d
        github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc00039fc80, 0x2c37770, 0xc001144b60, 0x7f1682310508, 0xc0018964e0, 0x0, 0x0, 0x0)
        	/home/circleci/project/project/terraform/graph_walk_context.go:127 +0xbf
        github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x2745d00, 0xc0018964e0, 0x0, 0x0, 0x0)
        	/home/circleci/project/project/terraform/graph.go:59 +0xba2
        github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc001149ec0, 0x2745d00, 0xc0018964e0, 0xc001267900)
        	/home/circleci/project/project/dag/walk.go:381 +0x288
        created by github.com/hashicorp/terraform/dag.(*Walker).Update
        	/home/circleci/project/project/dag/walk.go:304 +0x1246
--- FAIL: TestAccAWSDataElasticsearchDomain_basic (3.37s)
```

### References

*  hashicorp/terraform#28180

**Comment by pselle** [comment]
This should be fixed in RC1: https://github.com/hashicorp/terraform/pull/28180, hopefully

**Comment by YakDriver** [comment]
This did not reappear against Terraform 0.15.0-rc1!
