### ISSUE TITLE
Support for Cloudformation StackSet OperationPreferences

### ISSUE THREAD

**Issue by pshuman-heb** [hashicorp/terraform-provider-aws#18490]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Update API action on AWS Cloudformation StackSets support a `--operation-preferences` flag that allows you to specify a failure tolerance threshold and a concurrency setting. Since Stacksets are often used in cases where you're going to be managing quite a number of StackSet Instances, without being able to set these, actions will often take a long time, or fail due to one-off issues.

### New or Affected Resource(s)

* aws_cloudformation_stack_set

### Potential Terraform Configuration

```hcl
resource "aws_cloudformation_stack_set" "example" {
  administration_role_arn = aws_iam_role.AWSCloudFormationStackSetAdministrationRole.arn
  name                    = "example"

  parameters = {
    VPCCidr = "10.0.0.0/16"
  }

  operation_preferences = {
    region_order = ["us-east-1", "us-west-1"]
    failure_tolerance_percentage = 10
    max_concurrent_percentage = 100
  }

  template_body = <<TEMPLATE
SNIP.
TEMPLATE
}
```

### References

* https://docs.aws.amazon.com/cli/latest/reference/cloudformation/update-stack-set.html

**Comment by zopanix** [comment]
@pshuman-heb @anGie44 : This issue is wrong, unfortunetely, the operation_preferences is not defined on the stackset itself, but on the stackset instances. I know AWS let you believe it's on the stackset in both the AWS Console and the Cloudformation Resources. But these are actually specified in the stackset instances according to the aws-go sdk. What I currently cannot figure out is why updating the stack set will automatically revert the stackset-instances, but that seems to be more an AWS API inconsistency then a terraform issue.

**Comment by zopanix** [comment]
OK I've been digging a bit deeper, and it seems that operation_preferences are not supported in the create action, but are in the update action

https://docs.aws.amazon.com/sdk-for-go/api/service/cloudformation/#CreateStackSetInput vs https://docs.aws.amazon.com/sdk-for-go/api/service/cloudformation/#UpdateStackSetInput

**Comment by pshuman-heb** [comment]
Yea, I think I found out some of that in the past months - It's definitely related to  #12425 as you point out. In short, Service Managed StackSets are super messy right now and barely functional at all.

**Comment by praddc** [comment]
Just bumping this since the lack of both of the failure tolerance and max concurrent options make the aws_cloudformation_stack_set_instance almost useless when using SERVICE_MANAGED stack sets and more than a handful of accounts. Thanks!

**Comment by pshuman-heb** [comment]
An additional bump on this - for sufficiently large organizations, this makes the resource almost entirely useless, as the creation or update of a new Stackset takes so long that any temporary credentials (MFA token, Assumed Role) expires. It also runs up against the fact that the `aws_cloudformation_stack_set` resource can't set a `timeout` on Create, so you can get stuck in a loop where the `apply` will always time out.

**Comment by faurel** [comment]
Hi @ewbankkit, #23666  is not fixing this issue. As mentioned by @zopanix, when updating stackset you need to have those operation preferences. Otherwise stackset update will take ages on organizations with log of accounts.
