### ISSUE TITLE
Linter for .changelog files

### ISSUE THREAD

**Issue by anGie44** [hashicorp/terraform-provider-aws#18506]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* Ensure .changelog files created for PRs adhere to expected format to be used in file generation including:
  * balanced code block fences i.e. blocks start and end with three backticks (```) 
  * newline between blocks (handled by markdowlint rule `MD031`)
  * valid release-note types include : `note`, `bug`, `enhancement`, `new-resource`, `new-data-source`

### New or Affected Resource(s)

* N/A

### References

* #0000

**Comment by bflad** [comment]
Potentially related: https://github.com/hashicorp/terraform-provider-aws/issues/17135

**Comment by anGie44** [comment]
Ahhh totally related 😉 i like yours better! i'll close this one just to not have the duplicate 👍
