### ISSUE TITLE
Error: Provider produced inconsistent result after apply - aws_network_interface_sg_attachment

### ISSUE THREAD

**Issue by JustLeo** [hashicorp/terraform-provider-aws#18504]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.26
* provider registry.terraform.io/hashicorp/aws v3.34.0

### Affected Resource(s)

* aws_network_interface_sg_attachment
* aws_XXXXX

### Terraform Configuration Files

```hcl
resource "aws_network_interface_sg_attachment" "sg_kubernetes_attachment_awsnothtaikum02" {
   security_group_id    = aws_security_group.linux_kubernetes_sg1.id
   network_interface_id = aws_instance.awsnothtaikum02.primary_network_interface_id
}
```

### Expected Behavior

Succesfully attach the SG

### Actual Behavior

Error: Provider produced inconsistent result after apply

When applying changes to
aws_network_interface_sg_attachment.sg_kubernetes_attachment_awsnothtaikum02,
provider "registry.terraform.io/-/aws" produced an unexpected new value for
was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by bflad** [comment]
Hi @JustLeo 👋  Thank you for raising this and sorry you ran into trouble here. The fix for this error with the `aws_network_interface_sg_attachment` resource will be merging soon with https://github.com/hashicorp/terraform-provider-aws/pull/18466.
