### ISSUE TITLE
Enable EC2 Serial Console access

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#18503]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> EC2 Serial Console provides a simple and secure way to troubleshoot boot and network connectivity issues by establishing a connection to the serial port of an instance.

### New or Affected Resource(s)

* `aws_ec2_serial_console_access`

### Potential Terraform Configuration

```hcl
resource "aws_ec2_serial_console_access" "example" {
   enabled = true
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2021/03/introducing-ec2-serial-console/).
[Blog post](https://aws.amazon.com/blogs/aws/troubleshoot-boot-and-networking-issues-with-new-ec2-serial-console/).
[User Guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configure-access-to-serial-console.html#serial-console-account-access).

Requires [AWS SDK v1.38.9](https://github.com/aws/aws-sdk-go/releases/tag/v1.38.9):

* #18497

**Comment by bodgit** [comment]
I've submitted #23443 which adds a resource and data source for this.
