### ISSUE TITLE
Trigger update of `CHANGELOG.md` w/ `Unreleased` heading after a release

### ISSUE THREAD

**Issue by anGie44** [hashicorp/terraform-provider-aws#18507]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would be nice to have this component automated for us (if not achievable by `tf-release-bot`) :)

Possible Solution:

* use a `release` trigger within a github actions workflow to append to the file "in-place" such as with `-i` option in `sed` (if possible 🤔 ..or if file too large, with explicit temp file)

### New or Affected Resource(s)

* N/A

### References

* https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release

**Comment by ewbankkit** [comment]
This should be fixed with #19384/#19457. We will find out after the next release.
