### ISSUE TITLE
resource/aws_elasticache_cluster: `engine` parameter should be required

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#18514]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `aws_elasticache_cluster` resource can be used to create either Memcached or Redis clusters, based on the value of the `engine` parameter. If no value is specified, the AWS API defaults to creating a Memcached cluster, but the Terraform provider does not supply a default value.

To minimize practitioner surprise, the parameter should be required.

### Affected Resource

* aws_elasticache_cluster

**Comment by GavinWu1991** [comment]
I can submit a pull request for this.
