### ISSUE TITLE
Multiple destinations for S3 bucket replications

### ISSUE THREAD

**Issue by tlgkk** [hashicorp/terraform-provider-aws#18524]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I was checking [7610](https://github.com/hashicorp/terraform-provider-aws/issues/7610) this request and saw it was not possible. But apparently, things have changed [New – Amazon S3 Replication Adds Support for Multiple Destination Buckets](https://aws.amazon.com/blogs/aws/new-amazon-s3-replication-adds-support-for-multiple-destination-buckets/). I have tested from AWS console and it was working.

I was hoping it is possible to add the feature here 🙏  

### New or Affected Resource(s)

* aws_s3_bucket

### Potential Terraform Configuration

```hcl
resource "aws_s3_bucket" "foo" {
  bucket        = "foo"
  region        = "us-east-1"
  acl           = "private"
  force_destroy = true

  versioning {
    enabled = true
  }

  replication_configuration {
    role = "replication-role.arn"

    rules {
      id     = "replication-rule-1"
      priority = "1"
      status = "Enabled"

      destination {
        bucket        = "bar.arn"
      }
    }

    rules {
      id     = "replication-rule-2"
      priority = "2"
      status = "Enabled"

      destination {
        bucket        = "baz.arn"
      }
    }
  }
}
```

returns `Error: Error putting S3 replication configuration: InvalidRequest: Number of distinct destination bucket ARNs cannot exceed 1`

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/7610
* https://aws.amazon.com/blogs/aws/new-amazon-s3-replication-adds-support-for-multiple-destination-buckets/

**Comment by ewbankkit** [comment]
Related:

* https://github.com/hashicorp/terraform-provider-aws/issues/16546
* https://github.com/hashicorp/terraform-provider-aws/pull/16677

@tlgkk Thanks for raising this issue.
To enable replication to multiple buckets you will need to specify an empty `filter {}` block in each of the `rules`.
This is called out in a note in the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket):

> Replication to multiple destination buckets requires that `priority` is specified in the `rules` object. If the corresponding rule requires no filter, an empty configuration block `filter {}` must be specified.
