### ISSUE TITLE
aws_elasticache_replication_group logic does not permit automatic_failover_enabled when num_of_clusters = 1

### ISSUE THREAD

**Issue by DoctorPolski** [hashicorp/terraform-provider-aws#18522]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.8
* provider registry.terraform.io/hashicorp/aws v3.34.0

### Affected Resource(s)

* aws_elasticache_replication_group

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_elasticache_replication_group" "elasticache_redis" {
  replication_group_id          = "${var.environment}-redis"
  replication_group_description = var.redis_replication_group_description
  node_type                     = var.redis_instance_type
  automatic_failover_enabled    = var.redis_automatic_failover_enabled
  multi_az_enabled              = var.redis_multi_az_enabled
  auto_minor_version_upgrade    = var.redis_auto_minor_version_upgrade
  availability_zones            = data.aws_subnet.redis[*].availability_zone
  at_rest_encryption_enabled    = var.redis_at_rest_encryption_enabled
  transit_encryption_enabled    = var.redis_transit_encryption_enabled
  engine_version                = var.redis_engine_version
  parameter_group_name          = var.redis_parameter_group_name
  port                          = var.redis_port
  subnet_group_name             = aws_elasticache_subnet_group.mds_elasticache_redis_subnet_group.name
  maintenance_window            = var.redis_maintenance_window
  snapshot_window               = var.redis_snapshot_window
  snapshot_retention_limit      = var.redis_snapshot_retention_limit

  security_group_ids = [
    aws_security_group.elasticache_redis_sg.id,
  ]

  cluster_mode {
    replicas_per_node_group = var.redis_replicas_per_node_group
    num_node_groups         = var.redis_num_node_groups
  }
}
```

### Expected Behavior

```hcl
automatic_failover_enabled = true
multi_az_enabled           = false

cluster_mode {
  replicas_per_node_group = 0
  num_node_groups         = 1
}
```

With the above config, Terraform should plan.

### Actual Behavior

`Error: if automatic_failover_enabled is true, number_cache_clusters must be greater than 1`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

1. This working redis config is currently in place on AWS and has been for well over a year. This was configured via Terraform v0.12 with an obviously much earlier version of the provider.
2. Ever since the release of provider v3.26.0 Terraform will no longer plan despite this config not having changed.
3. The config suggestion made by @gdavison in https://github.com/hashicorp/terraform-provider-aws/issues/17376#issuecomment-808596790 is already in place as illustrated above so is of no help here.
4. As mentioned here https://github.com/hashicorp/terraform-provider-aws/issues/17376#issuecomment-771174117 and here https://github.com/hashicorp/terraform-provider-aws/issues/17376#issuecomment-778522264 the issue remains that Terraform is insisting this:

> If `automatic_failover_enabled` is enabled, number_cache_clusters must be greater than 1

Source: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#automatic_failover_enabled

Which does not agree with the working config I currently have on AWS:
![small_env](https://user-images.githubusercontent.com/13274475/113287684-cbd78f80-92e5-11eb-8be2-7a890f6d0964.png)

So I have to question whether or not the assertion made by Terraform is correct. It is my belief that number of clusters **DOES NOT** need to be > 1 for `automatic_failover_enabled` to be `TRUE`.

I agree with @gdavison here https://github.com/hashicorp/terraform-provider-aws/issues/17605#issuecomment-808600211 that it makes no logical sense setting `automatic_failover_enabled` to true for a single node since indeed where would it failover to. But AWS permits this and therefore it is incorrect for Terraform enforce otherwise.

I have Serverless code dependencies on cluster mode being set so I cannot specify my single node environments without clustering mode enabled.

### References

* #17605
* #17376
* #17320

**Comment by choikijin-techcross** [comment]
I have same problem.

https://github.com/hashicorp/terraform-provider-aws/issues/17605#issuecomment-808600211
https://github.com/hashicorp/terraform-provider-aws/issues/17376#issuecomment-808596790

I saw these 2 comments from related issues, so I feel like the developer of this code predicts that this terraform code works.
```
automatic_failover_enabled = true
multi_az_enabled           = false

cluster_mode {
  replicas_per_node_group = 0
  num_node_groups         = 1
}
```

unfortunately, I can't create smallest redis-cluster set @gdavison mentioned. I hope it'll be fixed soon.

**Comment by gdavison** [comment]
For clarification, is part of the issue that you haven't directly configured `number_cache_clusters`, yet the error message references it? If so, I can try to improve the error message. We currently allow configuring non-cluster mode replication groups using either `number_cache_clusters` or `cluster_mode` to make development and production configurations easier. `number_cache_clusters` == `cluster_mode.num_node_groups` * (1 + `cluster_mode.replicas_per_node_group`).

For your existing replication group, can you add a screenshot of the current parameters? In the list of replication groups, click on the triangle to show this. I'm wondering if there's an unexpected configuration, especially since AWS changed how some settings are interpreted.

**Comment by choikijin-techcross** [comment]
@gdavison I didn't configure `number_cache_clusters` and the error message is `Error: if automatic_failover_enabled is true, number_cache_clusters must be greater than 1`.

My setting was same as @DoctorPolski, so

`cluster_mode.num_node_groups`             = 1,
`cluster_mode.replicas_per_node_group` = 0,
`number_cache_clusters` == 1 * (1 + 0) = 1

and it's not greater than 1.
So I think the calculation is working, but terraform doesn't allow me to use a smallest set of a cluster.

I didn't add `number_cache_clusters` in my code, but terraform plan is showing `number_cache_clusters` on the result.
Maybe terraform is putting `number_cache_clusters` internally.

In below terraform plan result doesn't show the change of `replicas_per_node_group` because I already removed my replica on my aws console.
![image](https://user-images.githubusercontent.com/57892128/113372785-5ed6ff00-93a4-11eb-8ebf-347be139703e.png)

```
  # module.elasticache-redis["xxxx"].aws_elasticache_replication_group.repgroup will be updated in-place
  ~ resource "aws_elasticache_replication_group" "repgroup" {
        arn                           = "arn:aws:elasticache:ap-northeast-1:xxxxxx:replicationgroup:xxxxxx"
        at_rest_encryption_enabled    = false
        auto_minor_version_upgrade    = true
        automatic_failover_enabled    = false
        cluster_enabled               = false
        engine                        = "redis"
        engine_version                = "4.0.10"
        id                            = "xxxxxx"
        maintenance_window            = "tue:05:00-tue:06:00"
        member_clusters               = [
            "xxxxxx",
        ]
        multi_az_enabled              = false
        node_type                     = "cache.t2.small"
        number_cache_clusters         = 1
        parameter_group_name          = "xxxxxx"
        port                          = 6379
        primary_endpoint_address      = "xxxxxx.cache.amazonaws.com"
        reader_endpoint_address       = "xxxxxx.cache.amazonaws.com"
        replication_group_description = "xxxxxx"
        replication_group_id          = "xxxxxx"
        security_group_ids            = [
            "sg-xxxxxx",
        ]
        security_group_names          = []
        snapshot_retention_limit      = 0
        snapshot_window               = "14:00-15:00"
        subnet_group_name             = "xxxxxx"
      ~ tags                          = {
          - "AppRole"   = "xxxxxx" -> null
          + "RedisRole" = "xxxxxx"
          + "env"       = "stage1"
        }
        transit_encryption_enabled    = false

        cluster_mode {
            num_node_groups         = 1
            replicas_per_node_group = 0
        }

        timeouts {}
    }
```
```
$ grep -rn number_cache_clusters modules/elasticache/redis_cluster/
```

**Comment by DoctorPolski** [comment]
Thanks for engaging on this Graham.

The error message is a little confusing because effectively it only directly references the `number_cache_clusters` method for provisioning clusters. Honestly good luck thinking up a concise error message that references both...

These are the params for the cluster referenced in my OP:
![small_env_params](https://user-images.githubusercontent.com/13274475/113398083-f08b4000-9395-11eb-9eaf-0b83e89c4bba.jpg)

I believe we may share the same suspicion that since AWS made their changes that brought about the need for your v3.26.0 update that my config may effectively be no longer possible to create? Could it therefore be that I and others have been left with an orphaned legacy cluster config as a result of those changes?

The only way to test this theory directly would be to attempt to recreate a similar cluster config from scratch using AWS console or CLI. Even if that turned out to be possible the mystery of being able to set `automatic_failover_enabled` to `TRUE` for a single node with nothing to failover to would still remain.

In either case I think a support request to AWS is required here in parallel to our investigations.

**Comment by gdavison** [comment]
I'll take a look at improving the error messaging. Part of the complication is that we allow setting either, `number_cache_clusters` or `cluster_mode`, and calculate the other. When the parameter validations are done, it's picking up the calculated `number_cache_clusters`.

I'll do some more investigation around the configuration and try to reproduce it. It theoretically should not be possible, at least now, unless there's also some interaction with "Cluster-Mode enabled"/sharding.

**Comment by DoctorPolski** [comment]
I have tested the creation of a "single node cluster" directly on the console and your suspicions are correct @gdavison, `cluster.on` does indeed make all the difference.

### This is my creation template:
![small_create](https://user-images.githubusercontent.com/13274475/113685710-6e18be00-96be-11eb-9c30-fe369455eec5.png)

Selecting the `Cluster Mode enabled` Redis sub-option dynamically updates the `Parameter group` setting to include the `cluster.on` suffix.

Setting `Number of Shards` to 1 and `Replicas per Shard` to 0 forcibly unsets the `Multi-AZ` option and produces the blue info ribbon. We know the provider currently accounts for this as per previous discussion in this issue and related threads.

### Resulting cluster:
![small_cluster](https://user-images.githubusercontent.com/13274475/113686567-4aa24300-96bf-11eb-8c8f-ebe3d439b80d.png)

In respect of clustering, this matches the config of my "small environments".

**Comment by gdavison** [comment]
Thanks for testing that, @DoctorPolski. That's not the result I expected… 😀
