### ISSUE TITLE
aws_eip_association resource ignores allow_reassociation argument when it's set to false

### ISSUE THREAD

**Issue by leftyb** [hashicorp/terraform-provider-aws#18548]
Hi,

Terraform v0.12.19

```
provider "aws" {
  version = "2.70.0"
}
```

When setting  allow_reassociation to false at aws_eip_association resource EIPs reassociation still takes place. 
We faced that problem and it seems to be a bug.

Same issue opened in the past: [linked issue](https://github.com/hashicorp/terraform/issues/14553 ) 

```
locals {
 aws_eips = ["111.111.111.111","222.222.222.222","333.333.333.333"]
}

resource "aws_instance" "nc_instance" {
  count=5
  ....
  ....
}

resource "aws_eip_association" "eip_assoc" {
  count       = 5
  allow_reassociation = false 
  instance_id = element(aws_instance.nc_instance.*.id, count.index)
  public_ip   = element(locals.eips, count.index)
  lifecycle {
    ignore_changes = all
  }
}
```
At this example the `allow_reassociation=false` will not work and will reassociate the EIPs for the 4th & 5th aws_instance. 
Expected behavior terraform apply to exit with error.

**Expected Behavior**
- Associate EIP 0-2 to aws_instances 0-2.
- terraform to exit with error when trying to re-associate EIPs 0&1 to aws_instances 3 & 4.

**Actual Behavior**
 - Associate EIPs 0-2 to aws_instances 0-2.
 - EIPs 0&1 are  re-associated  to aws_instances 3 & 4.
 - Terraform completed successfully.

Best regards.

**Comment by breathingdust** [comment]
Hi @leftyb! 👋 Aplogies for the long delay. At present we are not considering bugfixes for the 2.* provider versions unless are are deemed critical security fixes. Are you able to confirm the issue is present in a recent version of the provider?

**Comment by njam** [comment]
I can confirm that this bug still exists in the latest version `3.70.0`.  

Setting `allow_reassociation = false` does not have any effect it seems.

**Comment by njam** [comment]
I think this is a duplicate of: https://github.com/hashicorp/terraform-provider-aws/issues/14179
