### ISSUE TITLE
eu-south-1 Error releasing EIP address: UnknownParameter: The parameter NetworkBorderGroup is not recognized

### ISSUE THREAD

**Issue by dievri** [hashicorp/terraform-provider-aws#18545]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.14.9
AWS Provider 3.35.0

### Affected Resource(s)
* aws_eip

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "eu-south-1"
}

resource "aws_eip" "eip" {
  vpc  = true
}
```
### Expected Behavior

aws_eip.eip: Destruction complete after 1s

### Actual Behavior

Error releasing EIP address: UnknownParameter: The parameter NetworkBorderGroup is not recognized
        status code: 400

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### Important Factoids
Just in eu-south-1 region!

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/e98c67eba23e956e73448025d011f5b0da9d71bf/aws/resource_aws_eip.go#L435-L468

According to the [API Reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ReleaseAddress.html) `NetworkBorderGroup` is not required.

**Comment by dievri** [comment]
according to debug, the following string is sent to AWS (notice empty **NetworkBorderGroup** parameter):

```
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: ec2.eu-south-1.amazonaws.com
User-Agent: aws-sdk-go/1.38.6 (go1.16; linux; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.14.9 (+https://www.terraform.io) terraform-provider-aws/dev (+https://registry.terraform.io/providers/hashicorp/aws)
Content-Length: 100
Authorization: ****
Content-Type: application/x-www-form-urlencoded; charset=utf-8
X-Amz-Date: 20210402T123822Z
Accept-Encoding: gzip

Action=ReleaseAddress&AllocationId=eipalloc-0a9a5f62d8646ed38&NetworkBorderGroup=&Version=2016-11-15
```

and the response is: 

```
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 Bad Request
Connection: close
Transfer-Encoding: chunked
Cache-Control: no-cache, no-store
Date: Fri, 02 Apr 2021 12:38:22 GMT
Server: AmazonEC2
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Amzn-Requestid: d9272587-cc79-4aa8-bc7c-a71ebe02f01f


-----------------------------------------------------: timestamp=2021-04-02T15:38:22.200+0300
2021-04-02T15:38:22.200+0300 [INFO]  plugin.terraform-provider-aws_v3.35.0_x5: 2021/04/02 15:38:22 [DEBUG] [aws-sdk-go] <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>UnknownParameter</Code><Message>The parameter NetworkBorderGroup is not recognized</Message></Error></Errors><RequestID>d9272587-cc79-4aa8-bc7c-a71ebe02f01f</RequestID></Response>: timestamp=2021-04-02T15:38:22.200+0300
2021-04-02T15:38:22.200+0300 [INFO]  plugin.terraform-provider-aws_v3.35.0_x5: 2021/04/02 15:38:22 [DEBUG] [aws-sdk-go] DEBUG: Validate Response ec2/ReleaseAddress failed, attempt 0/25, error UnknownParameter: The parameter NetworkBorderGroup is not recognized
	status code: 400, request id: d9272587-cc79-4aa8-bc7c-a71ebe02f01f: timestamp=2021-04-02T15:38:22.200+0300
2021-04-02T15:38:22.200+0300 [INFO]  plugin.terraform-provider-aws_v3.35.0_x5: 2021/04/02 15:38:22 [TRACE] Waiting 500ms before next try: timestamp=2021-04-02T15:38:22.200+0300
2021-04-02T15:38:22.701+0300 [INFO]  plugin.terraform-provider-aws_v3.35.0_x5: 2021/04/02 15:38:22 [DEBUG] [aws-sdk-go] DEBUG: Request ec2/ReleaseAddress Details:
---[ REQUEST POST-SIGN ]-----------------------------
```

**Comment by ewbankkit** [comment]
The code should change to

```go
	if v, ok := d.GetOk("network_border_group"); ok {
		input.NetworkBorderGroup = aws.String(v.(string))
	
```
