### ISSUE TITLE
Issues after updating AWS provider to 3.25.0 version

### ISSUE THREAD

**Issue by almarty** [hashicorp/terraform-provider-aws#18549]
After updating to AWS provider 3.25.0 I got the following after executing pipeline:

```
in resource “aws_lambda_function” “lambda_function”:
651 4: resource “aws_lambda_function” “lambda_function” {
652
653
654
655 Error: handler and runtime must be set when PackageType is Zip
```

Can it be fixed somehow? Probably it is some bug the affect current functionality.

**Comment by anGie44** [comment]
HI @almarty , thank you for raising this issue and apologies you came across an error after upgrading. Do you mind providing the configuration you're working with? I believe the error you're seeing is the intended current behavior given the changes merged in here: https://github.com/hashicorp/terraform-provider-aws/pull/16512 (`v3.19.0`).

**Comment by almarty** [comment]
@anGie44 just to make short preview: I try to fix issue with binary_media_types that is particular the same as is mentioned in https://github.com/hashicorp/terraform-provider-aws/issues/9722. But after updating terraform provider to 3.25.0 to fix this I'm faced with other issue related to lambda_function. Can be this fixed from your side? Probably it related to changes that you are mentioned in #16512, not sure. Is any other assumptions here? 
Received error didn't tell me so much: 
`Error: handler and runtime must be set when PackageType is Zip`

**Comment by almarty** [comment]
Is any updates here?

**Comment by anGie44** [comment]
Hi @almarty 👋 So given the error you're seeing i would recommend adding the `handler` and `runtime` arguments to your `aws_lambda_function` resource configuration to be able to apply the config without that plan-time error as a successful update to the resource now requires those 2 arguments when your function package type is "Zip". If you're experiencing something different even with 2 arguments set, please reach out :)

**Comment by almarty** [comment]
Hi @anGie44, 
The main thing that `handler` and `runtime` are already specified in Lambda configuration. 
```
name = "test-lambda-function"
runtime = "java11"
handler = "io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest"
```
Is any ideas?
