### ISSUE TITLE
AWS Batch now supports EFS volumes at the job level

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#18557]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> AWS Batch customers can now specify EFS file systems in their AWS Batch job definitions. 

### New or Affected Resource(s)

* [`aws_batch_job_definition`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/batch_job_definition)

### Potential Terraform Configuration

```hcl
resource "aws_batch_job_definition" "example" {
  name = "example"
  type = "container"

  container_properties = jsonencode({
    volumes = [
      efsVolumeConfiguration = {
        fileSystemId = aws_efs_file_system.example.id
      }
    ]
  })
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2021/04/aws-batch-supports-efs-volumes-job-level/).

Requires [AWS SDK v1.38.10](https://github.com/aws/aws-sdk-go/releases/tag/v1.38.10):

* #18544

**Comment by drewmullen** [comment]
This is working now:

```hcl
resource "aws_batch_job_definition" "test" {
  container_properties = jsonencode({
    command = ["echo", "test"]
    image   = "busybox"
    memory  = 128
    vcpus   = 1
    volumes = [{
      name = "test"
      efsVolumeConfiguration = {
        fileSystemId = aws_efs_file_system.foo.id
      }}
    ]})
  name = "test"
  type = "container"
}

resource "aws_efs_file_system" "foo" {
  creation_token = "my-product"
}
```
