### ISSUE TITLE
allowed_pattern could not be 0 symbols hence omitted

### ISSUE THREAD

**Issue by T0tt1** [hashicorp/terraform-provider-aws#18552]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_ssm_parameter

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "aws_ssm_parameter" "default" {
  count           = var.enabled == "true" ? length(var.parameter_write) : 0
  name            = lookup(var.parameter_write[count.index], "name")
  description     = lookup(var.parameter_write[count.index], "description", lookup(var.parameter_write[count.index], "name"))
  type            = lookup(var.parameter_write[count.index], "type", "SecureString")
  key_id          = lookup(var.parameter_write[count.index], "type", "SecureString") == "SecureString" && length(var.kms_arn) > 0 ? var.kms_arn : ""
  value           = lookup(var.parameter_write[count.index], "value")
  overwrite       = lookup(var.parameter_write[count.index], "overwrite", "false")
  allowed_pattern = lookup(var.parameter_write[count.index], "allowed_pattern", "")
  tags            = var.tags
}
```

### Debug Output

https://gist.github.com/T0tt1/e74a2b8f56e1dadeee74803904b6d475

### Expected Behavior

allowed_pattern is optional attribute hence should be able to skip setting the attribute

### Actual Behavior

Terraform expects length of the allowed_pattern attribute to be ` symbol at minimum

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ewbankkit** [comment]
Related:

#17819
#17830

**Comment by ewbankkit** [comment]
@T0tt1 Thanks for raising this issue.
Is this a new or existing Terraform configuration? The additional validation of the `allowed_pattern` attribute was added in v3.35.0 of the Terraform AWS Provider and we would like to know whether this is a regression or not.

**Comment by T0tt1** [comment]
This is an existing configuration and it just happened yesterday to update the version of provider yesterday and start throwing these errors while trying to deploy

**Comment by ewbankkit** [comment]
Related:

* #18550

**Comment by ewbankkit** [comment]
@T0tt1 As a workaround you could try `allowed_pattern = lookup(var.parameter_write[count.index], "allowed_pattern", null)`.
