### ISSUE TITLE
aws_db_proxy: Add support for reader endpoint

### ISSUE THREAD

**Issue by tatodorov** [hashicorp/terraform-provider-aws#18586]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
On Mar 16, 2021 AWS have added read-only endpoints for Amazon Aurora Replicas to the RDS Proxy.
This is not yet implemented in the AWS provider.

### New or Affected Resource(s)

* aws_db_proxy

### Potential Terraform Configuration

```hcl
resource "aws_db_proxy" "example" {
  name                   = "example"
  debug_logging          = false
  engine_family          = "MYSQL"
  idle_client_timeout    = 1800
  require_tls            = true
  role_arn               = aws_iam_role.example.arn
  vpc_security_group_ids = [aws_security_group.example.id]
  vpc_subnet_ids         = [aws_subnet.example.id]
  add_reader_endpoint    = true

  auth {
    auth_scheme = "SECRETS"
    description = "example"
    iam_auth    = "DISABLED"
    secret_arn  = aws_secretsmanager_secret.example.arn
  }

  tags = {
    Name = "example"
    Key  = "value"
  }
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2021/03/amazon-rds-proxy-adds-read-only-endpoints-for-amazon-aurora-replicas/
* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html#rds-proxy-endpoints-overview

**Comment by fabioviana-hotmart** [comment]
I've opened this https://github.com/hashicorp/terraform-provider-aws/issues/18673, it's the same...

So I think that would be interesting if the definition is a structure that be able to define a custom endpoint too. Today it's not possible (create a proxy to use a custom endpoint) but there is a PFR to do that. In the future it can be possible.
