### ISSUE TITLE
Cannot read new elasticsearch custom domain options

### ISSUE THREAD

**Issue by fdw** [hashicorp/terraform-provider-aws#18583]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform: 0.14.8
AWS Provider: 3.35.0

### Affected Resource(s)

* `aws_elasticsearch_domain`

### Terraform Configuration Files
I cannot manage to read the value of the new custom domain options that were introduced with 3.35 (#16059).

```
resource "aws_elasticsearch_domain" "thingy" {
  [snip]
  domain_endpoint_options {
    custom_endpoint_enabled = true
    custom_endpoint = "something"
    custom_endpoint_certificate_arn = var.certificate
  }
}

resource "aws_route53_record" "thingy" {
  [snip]
  name    = aws_elasticsearch_domain.thingy.domain_endpoint_options.custom_endpoint
}
```

### Expected Behavior

The custom domain name can be read and used by other resources.

### Actual Behavior

```
Block type "domain_endpoint_options" is represented by a list of objects, so
it must be indexed using a numeric key, like .domain_endpoint_options[0].
```

### Steps to Reproduce

Try the above config.

### References

* #16059

**Comment by bill-rich** [comment]
Hi @fdw! You should be able to access those values by using the numeric key.

```
resource "aws_route53_record" "thingy" {
  [snip]
  name    = aws_elasticsearch_domain.thingy.domain_endpoint_options[0].custom_endpoint
}
```

The reason for this is that the `domain_endpoint_options` attribute is stored as a list in the Terraform schema. Since there is only one, you can safely use the `0` identifier.

**Comment by fdw** [comment]
Thanks, then I misunderstood the error message. Maybe it makes sense to mention that in the documentation?
