### ISSUE TITLE
Unable to use scope_down_statement for Managed Rule Group Statement

### ISSUE THREAD

**Issue by KeerthiPattabhi** [hashicorp/terraform-provider-aws#18584]
The UI for a managed rule group allows a scope down statement but it is not possible to do the same using terraform for a managed rule group statement. Can this be added?
**
![image](https://user-images.githubusercontent.com/20239017/113684332-69a3d380-96c5-11eb-88a9-fc1a2a0b58be.png)
**

**Comment by tlvince** [comment]
Scope-down statements aren't supported by legacy WAF - I think this should be labelled `service/wafv2` and #19125 closed as a duplicate.
