### ISSUE TITLE
aws_route with vpc_endpoint_id and destination_prefix_list_id do not work together.

### ISSUE THREAD

**Issue by james-masson** [hashicorp/terraform-provider-aws#18607]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform v0.14.9

aws-provider v3.35.0 

### Affected Resource(s)

`aws_route`

### Terraform Configuration Files

```hcl
resource "aws_route" "s3_vpce" {
  route_table_id                 = var.route_table_id
  vpc_endpoint_id              = var.s3_vpce_id
  destination_prefix_list_id = var.s3_prefix_list_id
}
```

### Debug Output

Can't provide this - air-gapped environment.

### Expected Behavior

Terraform should have created a route table entry using a Prefix list, pointing to a VPC-endpoint

### Actual Behavior

Terraform / AWS API error

```
vpc_endpoint_id conflicts with destination_prefix_list_id
```

if I remove `destination_prefix_list_id`, and hope that terraform/AWS will figure it out, I get...

```
route destination attribute not specified
```

### Steps to Reproduce

1. `terraform apply`

### Related

https://github.com/hashicorp/terraform-provider-aws/issues/15273

**Comment by james-masson** [comment]
While it seems that this approach is the logical way to do it, `aws_vpc_endpoint_route_table_association` seems to work too - with the benefit that the prefix list doesn't have to be supplied and is automatically calculated.

```
resource "aws_vpc_endpoint_route_table_association" "example" {
  route_table_id  = aws_route_table.example.id
  vpc_endpoint_id = aws_vpc_endpoint.example.id
} 
```

So, this is probably still a bug, as it stops some more advanced use cases, but the workaround is actually better in my case.

**Comment by ewbankkit** [comment]
@james-masson Thanks for raising this issue.
You are correct that for Gateway VPC Endpoints (such as for S3) the [`aws_vpc_endpoint_route_table_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint_route_table_association) should be used to associate an AWS-managed prefix list with a route table.
If you attempt to add a route targeting a Gateway Load Balancer endpoint with a customer-managed prefix list destination the underlying AWS API errors with _Cannot create or replace a prefix list route targeting a VPC Endpoint._ This is why the plan-time conflict between `vpc_endpoint_id` and `destination_prefix_list_id` was added.
I agree that we should clearer in the documentation on how to use this functionality.

**Comment by posquit0** [comment]
I have a same issue.
`aws_route` with `vpc_endpoint_id` and `destination_prefix_list_id` (from gateway_endpoint) do not work together.
Is there plan to support? Is it bug? What is the use-case of `vpc_endpoint_id` argument if it is not expected usage.

**Comment by kakmt** [comment]
Same issue here with terraform-provider-aws ver 3.70.0

**Comment by roded** [comment]
Same issue here with 4.21.0.
Does anyone know if there's a workaround for this issue?
Thanks

**Comment by rohitvermasrt** [comment]
I also have the same issue. Is there any workaround for the same? Or any updates on the feature? 

Thanks

**Comment by rohitvermasrt** [comment]
Hi guys, I have managed to add a route for s3 vpc endpoint by using terraform resource "[aws_vpc_endpoint_route_table_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint_route_table_association)".  So there is not need to add a route, instead this will create a route.  Thanks

**Comment by diverbeard** [comment]
> @james-masson Thanks for raising this issue. You are correct that for Gateway VPC Endpoints (such as for S3) the [`aws_vpc_endpoint_route_table_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint_route_table_association) should be used to associate an AWS-managed prefix list with a route table. If you attempt to add a route targeting a Gateway Load Balancer endpoint with a customer-managed prefix list destination the underlying AWS API errors with _Cannot create or replace a prefix list route targeting a VPC Endpoint._ This is why the plan-time conflict between `vpc_endpoint_id` and `destination_prefix_list_id` was added. I agree that we should clearer in the documentation on how to use this functionality.
> 
> Related:
> 
> * [r/aws_route: 'destination_prefix_list_id' attribute can be specified for managed prefix list destinations #17291](https://github.com/hashicorp/terraform-provider-aws/pull/17291)
> * [Add destination prefix list to route table #15273](https://github.com/hashicorp/terraform-provider-aws/issues/15273)

@ewbankkit I'm confused about this reply and need some clarification.  I wanted to use a managed prefix list targeting a Gateway Load Balancer and found that it was not allowed.  Researching the reason behind this brought me here.  Are you saying that using Terraform allows us to apply PL to AWS endpoints like S3 but there is no hope for Gateway Load Balancers ... or are you saying that if you use the API you get this error but this process works for GLB as well?  I think you're saying there's no hope for me.

**Comment by dwiesttq** [comment]
Would it be possible to update the Terraform documentation (and error message) for "Resource: aws_route" to mention that aws_vpc_endpoint_route_table_association should be used in this situation?  This bug has been open for more than 2.5 years.

**Comment by d-medvedev1** [comment]
Just want to mention that suggested workaround with `[aws_vpc_endpoint_route_table_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint_route_table_association)` resource works only if S3 endpoint has `vpc_endpoint_type   = "Interface"`. 

Otherwise Terraform raises error `InvalidParameter: Route table IDs are only supported for Gateway type VPC Endpoint.`

So at this moment seems like no Terraform based-way to specify AWS Managed prefix list and attach route in route table in case there is Interface endpoint type specified for S3 endpoint.
