### ISSUE TITLE
aws_dx_gateway_association_proposal still recreated

### ISSUE THREAD

**Issue by toelke** [hashicorp/terraform-provider-aws#18608]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Issue

This is to note that issue #9209 is closed but not solved; creating a `aws_dx_gateway_association_proposal` and accepting it will still, after a few days, try to recreate the `aws_dx_gateway_association_proposal`. See #9209 for all information.

**Comment by bill-rich** [comment]
Thanks for reporting this @toelke! @ewbankkit, do you have any feedback on what could be happening here?

**Comment by ewbankkit** [comment]
@toelke Can you attach the output of a `terraform plan` or `terraform apply` that shows the proposal being recreated?
This will help greatly with our troubleshooting.
Thanks.

**Comment by toelke** [comment]
![image](https://user-images.githubusercontent.com/183276/114180802-fe663580-9940-11eb-8b1f-3a8771ba1bcc.png)

When applying this it will work but break the association for a few minutes. In three days or so it will again want to re-create the proposal.

The original poster in #9209 has this quote from AWS: "Once the proposal is accepted, it will disappear after some time. There is no defined time duration as to how long the proposal is available after acceptance". See especially the comment https://github.com/hashicorp/terraform-provider-aws/issues/9209#issuecomment-606784439

**Comment by ewbankkit** [comment]
@toelke You could try adding

```hcl
  lifecycle {
    ignore_changes = [
      proposal_id,
    ]
  }
```

to the `aws_dx_gateway_association` resource.

**Comment by toelke** [comment]
Yes, but the proposal will still be re-created, breaking the connection.

**Comment by ewbankkit** [comment]
Aah, so it's the creation of the new proposal that causes the association to break (and thus the network outage) rather than the change of the proposal ID in the `aws_dx_gateway_association` (because from the code, updating `proposal_id` doesn't actually do anything)?

**Comment by toelke** [comment]
I can try to check that.

In any case terraform.would recreate the proposal every few days which will show up as configuration drift. Even without outage that's not ideal.

**Comment by toelke** [comment]
I tested re-creating the proposal and *not* changing the `aws_dx_gateway_association` (by using `ignore_changes`) and the connection stays up even if I accept or reject the new proposal in the web-console.

So using `ignore_changes` is indeed a solution for not breaking the connection.

I would still prefer not to have config drift, though.
