### ISSUE TITLE
tests/resource/aws_sfn_state_machine: TestAccAWSSfnStateMachine_expressLoggingConfiguration Configuration Error

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#18614]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `TestAccAWSSfnStateMachine_expressLoggingConfiguration` acceptance test consistently fails with:

```
=== CONT  TestAccAWSSfnStateMachine_expressLoggingConfiguration
resource_aws_sfn_state_machine_test.go:211: Step 1/2 error: Error running apply: exit status 1
Error: Error creating Step Function State Machine: InvalidLoggingConfiguration: Invalid Logging Configuration: Log Group ARN must be provided with '*' qualifier.
on terraform_plugin_test.tf line 105, in resource "aws_sfn_state_machine" "foo":
105: resource "aws_sfn_state_machine" "foo" {
--- FAIL: TestAccAWSSfnStateMachine_expressLoggingConfiguration (44.05s)
```

Likely requires doing exactly what the API error says to the test configuration.

### Affected Resource

* aws_sfn_state_machine

**Comment by ewbankkit** [comment]
It looks like there are stray `<<<` in the configuration from a botched merge conflict resolution.
