### ISSUE TITLE
resource/aws_cloudwatch_event_rule: Error reading CloudWatch Events Rule

### ISSUE THREAD

**Issue by nicolas-alie** [hashicorp/terraform-provider-aws#18637]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

v3.35.0

### Affected Resource(s)

Resource: aws_cloudwatch_event_rule

### Terraform Configuration Files

```hcl
resource "aws_cloudwatch_event_rule" "auth0_event_rule" {
  name        = "auth0-success-verification-email${var.suffix}"
  description = "Forward Auth0 Event 'Success Verification Email' to MS-USER"

  event_bus_name = "aws.partner/auth0.com/landr-dev-aadeb281-5fb2-4ac0-8a73-c50bb4107906/auth0.logs"

  event_pattern = <<EOF
{
  "type": ["sv"]
}
EOF
}
```

### Debug Output

```
Error: error reading CloudWatch Events Rule (aws.partner/auth0.com/landr-dev-aadeb281-5fb2-4ac0-8a73-c50bb4107906/auth0.logs/auth0-success-verification-email-ba-03): unexpected format for ID ("aws.partner/auth0.com/landr-dev-aadeb281-5fb2-4ac0-8a73-c50bb4107906/auth0.logs/auth0-success-verification-email-ba-03"), expected <event-bus-name>/<rule-name> or <rule-name>

on ../shared/auth0events.tf line 31, in resource "aws_cloudwatch_event_rule" "auth0_event_rule":
 31: resource "aws_cloudwatch_event_rule" "auth0_event_rule" {
```

### Expected Behavior

terraform should be able to parse a event bus name created by Auth0 which has multiple / in it. It should only take the last part as rule-name when parsing

### Actual Behavior

Error reading CloudWatch Events Rule

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

A event bus was created automatically by Auth0 following the guide "Stream Logs to Amazon EventBridge".
https://auth0.com/docs/logs/streams/stream-logs-to-amazon-eventbridge

### References

https://github.com/hashicorp/terraform-provider-aws/blob/4425957ef58f94061f92a45e694ff6ddb56cfe3b/aws/internal/service/cloudwatchevents/id.go#L40

**Comment by ewbankkit** [comment]
@nicolas-alie Thanks for raising this issue.
It has already been noticed in #18431. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

This is addressed in #18491.
