### ISSUE TITLE
resource/aws_lb_target_group: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#18633]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Discovered via acceptance testing:

```
=== CONT  TestAccAWSLBListenerRule_priority
resource_aws_lb_listener_rule_test.go:407: Step 1/8 error: Error running apply: exit status 1
Error: Provider produced inconsistent result after apply
When applying changes to aws_lb_target_group.test, provider
"registry.terraform.io/hashicorp/aws" produced an unexpected new value: Root
resource was present, but now absent.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
--- FAIL: TestAccAWSLBListenerRule_priority (192.19s)
```

This resource should fast track `d.IsNewResource()` error checking and implement resource lifecycle retries.

### Affected Resources

* aws_lb_target_group

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/16796
* https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/retries-and-waiters.md#resource-lifecycle-retries

**Comment by EladDolev** [comment]
looks like this version re-introduced the bug described [here](https://github.com/hashicorp/terraform-provider-aws/issues/16860)

running `0.14.10` with AWS provider `3.36.0`
