### ISSUE TITLE
Add SAML config support to advanced_security_options block of aws_elasticsearch_domain

### ISSUE THREAD

**Issue by kevinhwang** [hashicorp/terraform-provider-aws#18642]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

See below:

### New or Affected Resource(s)

* [aws_elasticsearch_domain](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain)

### Potential Terraform Configuration

```hcl
resource "aws_elasticsearch_domain" "domain" {
  domain_name = "my-domain"
  advanced_security_options {
    enabled = true
    saml_options {
      enabled = true
      idp = {
        entity_id        = "my-idp.com"
        metadata_content = file("my-idp-metadata.xml")
      }
      roles_key               = "groups"   # optional
      subject_key             = "username" # optional
      session_timeout_minutes = 180        # optional
      master_user_name        = "me"       # optional
      master_backend_role     = "admins"   # optional
    }
  }
}
```

### References

* [`es:UpdateElasticsearchDomainConfig` API reference](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-configuration-api.html#es-configuration-api-actions-updateelasticsearchdomainconfig)

**Comment by JeffAshton** [comment]
Is this a duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/16259 ?

**Comment by DrFaust92** [comment]
Duplicate of #16259
