### ISSUE TITLE
ElastiCache Tag Modification

### ISSUE THREAD

**Issue by bondsb** [hashicorp/terraform-provider-aws#18668]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Provide tag modification support to AWS ElastiCache resources.

Support for tag modification has recently been updated in [Go SDK version 1.38.15](https://github.com/aws/aws-sdk-go/releases/tag/v1.38.15).

### New or Affected Resource(s)

* aws_elasticache_*

### Potential Terraform Configuration

```hcl
resource "aws_elasticache_replication_group" "my_replication_group" {
  ...

  tags = {
    MyTagKey = "MyTagValue"
  }
}
```

### References

* #1615
* #5366
* #9002

**Comment by ewbankkit** [comment]
Requires:

* #18702

**Comment by bondsb** [comment]
@justinretzolk Apologies for the delay.

That fix does not appear to work.  v3.65.0 does not detect external tag changes and the result of a difference between actual tags and expected tags results in a plan with no changes.
