### ISSUE TITLE
Expose update timeout configuration for Lambda functions

### ISSUE THREAD

**Issue by tlvince** [hashicorp/terraform-provider-aws#18661]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When updating a Lambda@Edge function, I regularly hit "exceeded wait attempts":

```
module.redirector.aws_lambda_function.main: Modifying... [id=my-edge-func]
module.redirector.aws_lambda_function.main: Still modifying... [id=my-edge-func, 10s elapsed]
module.redirector.aws_lambda_function.main: Still modifying... [id=my-edge-func, 20s elapsed]
...
module.redirector.aws_lambda_function.main: Still modifying... [id=my-edge-func, 4m30s elapsed]
module.redirector.aws_lambda_function.main: Still modifying... [id=my-edge-func, 4m40s elapsed]
module.redirector.aws_lambda_function.main: Still modifying... [id=my-edge-func, 4m50s elapsed]

Error: while waiting for function (my-edge-func) update: ResourceNotReady: exceeded wait attempts
Exited with code exit status 1
```

I can only reproduce this on Lambda@Edge functions, which I assume can take longer than the default 5m to propagate.

Currently, the [create](https://github.com/hashicorp/terraform-provider-aws/blob/355e5b78c3306cb75490189129cf439c52c0237e/aws/resource_aws_lambda_function.go#L38-L40) [timeout](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#timeouts) is configurable. Please could `update` be added (and perhaps other lifecycles)?

### New or Affected Resource(s)

* aws_lambda_function
* terraform v0.14.7
* hashicorp/aws v3.31.0

### Potential Terraform Configuration

```hcl
resource "aws_lambda_function" "main" {
  timeouts {
    update = "10m"
  }
}
```

### References

* #8043

**Comment by christianhaller3000** [comment]
I see this with regular lambdas.

**Comment by christianhaller3000** [comment]
It's gone with terraform 0.15.1 and aws-provider 3.39.0 ¯\_(ツ)_/¯

**Comment by tlvince** [comment]
Unfortunately, I can still reproduce this with 0.15.5 and aws-provider 3.44.0, albeit for Lambda@Edge functions.

**Comment by christianhaller3000** [comment]
I can confirm this: we saw it today with 0.15.5 and 3.44.0 for a regular lambda fn

**Comment by parisholley** [comment]
I was stuck on this recently after upgrading to pulumi 3 and realized that sometimes the timeout message is a false positive and some underlying IAM permissions are missing and causing the success check to fail. I was able to get this to go away by giving my CI/CD IAM role the following permissions on my lambda functions:

```
lambda:GetCodeSigningConfig
lambda:GetFunctionCodeSigningConfig
lambda:GetFunctionConfiguration
```

**Comment by christianhaller3000** [comment]
@parisholley 
on which resources do you allow this?

* or scoped to the lambda you want to deploy?

**Comment by parisholley** [comment]
@christianhaller3000 i apply my lambda policies to the function, and each version, eg:

```
arn:aws:lambda:us-east-2:xxxx:function:my-function
arn:aws:lambda:us-east-2:xxxx:function:my-function:*
```

didn't test which actually fixes

**Comment by christianhaller3000** [comment]
<img width="703" alt="Bildschirmfoto 2021-11-11 um 21 34 49" src="https://user-images.githubusercontent.com/42344734/141365320-91616981-e433-4083-a6a5-c940d9108c63.png">

we do this as well and I still see this

` while waiting for function (robby) update: ResourceNotReady: exceeded wait attempts`

**Comment by christianhaller3000** [comment]
@parisholley oohhhhh, I see a `-` instead of a `:` in my code 😬
