### ISSUE TITLE
'plan' and 'apply' do not re-add roles to instance profiles when the roles have been removed since the last apply

### ISSUE THREAD

**Issue by jimnarey** [hashicorp/terraform-provider-aws#18664]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/aws v3.35.0
```

### Affected Resource(s)

* aws_iam_role
* aws_iam_instance_profile

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
  required_version = "0.14.9"
}

resource "aws_iam_role" "example" {
  name = "example"

  assume_role_policy = <<-EOF
  {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Principal": {
          "Service": "ecs-tasks.amazonaws.com"
        },
        "Action": "sts:AssumeRole"
      }
    ]
  }
EOF
}

resource "aws_iam_instance_profile" "example" {
  name = "example"
  role = aws_iam_role.example.name
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

After running `terraform apply` and then manually removing the created aws_iam_role from the aws_iam_instance_profile, running `terraform plan` or `terraform apply` should recognise the the actual state (role not attached to instance profile) is different from the declared state (role is attached) and make the necessary changes.

The purpose of manually removing the roles from the instance profiles was to simulate a recent accidental occurrence of this. 

### Actual Behavior

Running `terraform plan` after removing the role from the profile returns:

```
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

Running `terraform apply` returns:

```
aws_iam_role.example: Refreshing state... [id=example]
aws_iam_instance_profile.example: Refreshing state... [id=example]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed
```

### Steps to Reproduce

* Apply the above terraform code for the first time:

```
>terraform apply

...
Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_iam_role.example: Creating...
aws_iam_role.example: Creation complete after 2s [id=example]
aws_iam_instance_profile.example: Creating...
aws_iam_instance_profile.example: Creation complete after 1s [id=example]
...
```
* Check that the role is attached to the instance profile as expected (it is):

```
>aws iam get-instance-profile --instance-profile-name example

{
    "InstanceProfile": {
        "Path": "/",
        "InstanceProfileName": "example",
        "InstanceProfileId": "XXXXXXXXXXXXXXXXXX",
        "Arn": "arn:aws:iam::XXXXXXXXXXXX:instance-profile/example",
        "CreateDate": "2021-04-08T14:42:13Z",
        "Roles": [
            {
                "Path": "/",
                "RoleName": "example",
                "RoleId": "XXXXXXXXXXXXXXXXXXXX",
                "Arn": "arn:aws:iam::XXXXXXXXXXX:role/example",
                "CreateDate": "2021-04-08T14:42:11Z",
                "AssumeRolePolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Principal": {
                                "Service": "ecs-tasks.amazonaws.com"
                            },
                            "Action": "sts:AssumeRole"
                        }
                    ]
                }
            }
        ]
    }
}
```
* Manually remove the role from the instance profile:

```
>aws iam remove-role-from-instance-profile --instance-profile-name example --role-name example
```

* Run `terraform apply` again:

```
>terraform apply

aws_iam_role.example: Refreshing state... [id=example]
aws_iam_instance_profile.example: Refreshing state... [id=example]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

* Check again whether the role is attached to the instance profile (it isn't):

```
>aws iam get-instance-profile --instance-profile-name example


{
    "InstanceProfile": {
        "Path": "/",
        "InstanceProfileName": "example",
        "InstanceProfileId": "XXXXXXXXXXXXXXXXXXX",
        "Arn": "arn:aws:iam::XXXXXXXXXX:instance-profile/example",
        "CreateDate": "2021-04-08T14:42:13Z",
        "Roles": []
    }
}
```

### Important Factoids

N/A

### References

N/A

**Comment by 0x91** [comment]
It looks like the bug is here: https://github.com/hashicorp/terraform-provider-aws/blob/0a76c88a4f66439dcc3ed1c751e38110cf60372c/aws/resource_aws_iam_instance_profile.go#L289

When there are no roles returned, d.Set(..) is not called on this schema attribute so no drift detection is performed.

**Comment by jimnarey** [comment]
Thank you for the helpful pointer. I'll see if I can get a fix working.
