### ISSUE TITLE
Support for define the target-role on aws_db_proxy

### ISSUE THREAD

**Issue by fabioviana-hotmart** [hashicorp/terraform-provider-aws#18673]
## Description
We've been using aurora a lot and now we've started the proxy usage, but some clusters we can't use the master endpoint and there are more then one read replica, because of that we need to use the cluster endpoint but without accessing the master instance, so, the resource aws_db_proxy doesn't have an attribute to define the target-role (with the values READ_WRITE | READ_ONLY).

I've seen that the command [create-db-proxy-endpoint](https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-proxy-endpoint.html) has this attribute.

## Usage

```
resource "aws_db_proxy" "example" {
  name                   = "example"
  debug_logging          = false
  engine_family          = "MYSQL"
  idle_client_timeout    = 1800
  require_tls            = true
  role_arn               = aws_iam_role.example.arn
  vpc_security_group_ids = [aws_security_group.example.id]
  vpc_subnet_ids         = [aws_subnet.example.id]

  target_role = "READ_ONLY"

  auth {
    auth_scheme = "SECRETS"
    description = "example"
    iam_auth    = "DISABLED"
    secret_arn  = aws_secretsmanager_secret.example.arn
  }

  tags = {
    Name = "example"
    Key  = "value"
  }
}
```

**Comment by fabioviana-hotmart** [comment]
It's duplicated: https://github.com/hashicorp/terraform-provider-aws/issues/18586

**Comment by sxslex** [comment]
👍🏽 I share the same need
