### ISSUE TITLE
Bug: leading whitespace causes aws_iam_policy to incorrectly report valid JSON policies as invalid

### ISSUE THREAD

**Issue by WintersMichael** [hashicorp/terraform-provider-aws#1873]
### Terraform Version
0.10.7, 0.9.11

### Affected Resource(s)
- aws_iam_role
- aws_iam_policy

### Terraform Configuration Files
```hcl
resource "aws_iam_policy" "nodes_sqs_policy" {
    name        = "nodes_sqs_policy"
    description = "nodes SQS"
    policy = <<EOF
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "sqs:GetQueueAttributes"
          ],
          "Resource": [
            "arn:aws:sqs:us-east-1:123123123:myapp-dev-us-east-1*"
          ]
        }
      ]
    }
EOF
}
```

### Expected Behavior
The policy was applied

### Actual Behavior
```
1 error(s) occurred:

* aws_iam_policy.nodes_sqs_policy: "policy" contains an invalid JSON policy
```

### Important Factoids
According to [RFC 4627](https://www.ietf.org/rfc/rfc4627.txt), "Insignificant whitespace is allowed before or after any of the six structural characters."

Removing the whitespace before the first character in the policy allows it to be applied:
```hcl
data "template_file" "nodes_iam_sqs" {
    name        = "nodes_sqs_policy"
    description = "nodes SQS"
    policy = <<EOF
{
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "sqs:GetQueueAttributes"
          ],
          "Resource": [
            "arn:aws:sqs:us-east-1:123123123:myapp-dev-us-east-1*"
          ]
        }
      ]
    }
EOF
}
```

### References
[Terraform #11906](https://github.com/hashicorp/terraform/issues/11906) is where the JSON validation was applied.

**Comment by xocasdashdash** [comment]
Adding this here as docs but this can cause bugs on resources that depend on this policy and the warning is extremely disconcerting. 

The example would be if you have an aws_iam_role_policy_attachment depend on your policy it will tell you that the policy does not exist.

**Comment by nodesocket** [comment]
I came across this today as well. This is a bug right?

```tf
    policy = <<CONFIG
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Action": [
                    "s3:GetObject"
                ],
                "Resource": [
                    "arn:aws:s3:::our-org-secrets",
                    "arn:aws:s3:::our-org-secrets/*"
                ]
            }
        ]
    }
    CONFIG
```

```
"policy" contains an invalid JSON policy
```

**Comment by mplanchard** [comment]
Also affects terraform 0.11.4, aws provider 1.13.0

**Comment by lakshmigk01** [comment]
+1 I encountered this as well

**Comment by woodcockjosh** [comment]
#trim

**Comment by larroy** [comment]
+1

**Comment by nwipfli** [comment]
+1 Same issue for me.

**Comment by whatisaphone** [comment]
![](https://i.imgur.com/BHvMNrx.png)

**Comment by MikeSchuette** [comment]
I finally had a minute to write https://github.com/terraform-providers/terraform-provider-aws/pull/5887 but I don't currently have an environment I can run acceptance tests in.  If someone can pull my branch, run `make testacc TEST=./aws TESTARGS='-run=TestAccAWSLaunchTemplate_'`, and post results in the PR thread, that might help get this merged.

**Comment by MikeSchuette** [comment]
I found a donor account, test results are added.

**Comment by mgasner** [comment]
👍

**Comment by goetzc** [comment]
As a workaround on using the ugly JSON inline Heredoc, the [aws_iam_policy_document](https://www.terraform.io/docs/providers/aws/d/iam_policy_document.html) data source works great, HCL to JSON transformer.

**Comment by goetzc** [comment]
Can be in a stale state, but it's still a bug :smile:

**Comment by himanshubora12** [comment]
OMG!! Just a small whitespace in starting is stopping!!! harsh

**Comment by yogeshbodke** [comment]
`jsonencode()` solved my issue

```
policy = jsonencode({
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ecr:BatchCheckLayerAvailability",
                "ecr:BatchGetImage",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetAuthorizationToken"
            ],
            "Resource": "*"
        }
    ]
  })
```

**Comment by anirudhdggl** [comment]
Even with jsonencode, it's giving me **MalformedPolicyDocument: JSON strings must not have leading spaces**

**Comment by devopsrick** [comment]
FWIW I have switched almost exclusively to the aws_iam_policy_document data resources for these policies.  JSON blocks cause more trouble than they are worth.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document#basic-example 

Here is a very hand utility you can use to generate them from the json policy themselves in more or less one line with echo.

https://github.com/flosell/iam-policy-json-to-terraform

**Comment by srinisakh** [comment]
Indented heredoc should work here: instead of `<<CONFIG` use `<<-CONFIG`

ref: https://developer.hashicorp.com/terraform/language/expressions/strings#indented-heredocs
