### ISSUE TITLE
Improve EKS cluster name validation

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#18806]
[AWS API documentation](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html#API_CreateCluster_RequestSyntax) describes the format for an EKS cluster name is `^[0-9A-Za-z][A-Za-z0-9\-_]*`, with 1 to 100 characters.

Current validation in the provider is `validation.NoZeroValues`.

Update validation for `aws_eks_cluster` and other resources and data sources where the name is used.

### Affected Resource

* aws_eks_cluster
* aws_eks_addon (#16972)
* aws_eks_fargate_profile
* aws_eks_node_group
* data.aws_eks_addon (#16972)
* data.aws_eks_cluster

**Comment by philnichol** [comment]
Hi @gdavison :wave:, hope you don't mind I went ahead and raised  #19078 which should close this
