### ISSUE TITLE
Allow configuration of indivdual brokers in AWS MSK

### ISSUE THREAD

**Issue by spr-mweber3** [hashicorp/terraform-provider-aws#18808]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We have the requirement to configure individual brokers in the MSK. We want to configure `advertised.listeners` and that has to be done for every broker. In the provider there currently seems to be no option to do that. Only per-cluster configuration of the MSk can be supplied.

What we currently do to workaround this limitation is running a statement like the one below for every broker:

```
./kafka-configs.sh --alter \
    --bootstrap-server b-1.msk-name.1ydkhw.c2.kafka.eu-central-1.amazonaws.com:9096 \
    --entity-type brokers \
    --command-config server.properties \
    --entity-name 2 \
    --add-config advertised.listeners=[CLIENT_SASL_SCRAM://broker-1.my.domain:9001,REPLICATION://b-1-internal.msk-name.1ydkhw.c2.kafka.eu-central-1.amazonaws.com:9093,REPLICATION_SECURE://b-1-internal.msk-name.1ydkhw.c2.kafka.eu-central-1.amazonaws.com:9095]
```
 It would be nice if we could achive that through the provider itself as it's kind of a hassle to get the Kafka tooling working which is needed to perform these type of commands.

**Comment by ewbankkit** [comment]
@spr-mweber3 Thanks for raising this issue.
Does the [`aws_msk_configuration`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_configuration) resource provide the functionality you require?

**Comment by spr-mweber3** [comment]
@ewbankkit I am aware of the aws_msk_configuration resource. In fact, we are utilizing it to set some cluster-wide settings in it. What can not be achieved by that resource is the update of broker-specific options.

With your response triggering another lookup of the [documentation](https://docs.aws.amazon.com/msk/latest/developerguide/msk-configuration-properties.html) at AWS I found the statement "You can set the advertised.listeners property, but not the listeners property." in the Dynamic Configuration section.

The link there which is labeled [Updating Broker Configs](https://kafka.apache.org/documentation/#dynamicbrokerconfigs) describes how to do that.

It would be great to have the option to do these dynamic broker configs in Terraform itself

**Comment by ewbankkit** [comment]
@spr-mweber3 Thanks for the prompt response.
Until AWS supports the functionality in the MSK it is unlikely that the Terraform AWS Provider would add this functionality.
From my brief browsing of the [underlying code](https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/admin/ConfigCommand.scala) for the `kafka-configs.sh` tool, it looks like this functionality is implemented using Kafka's API and that there is a community [Terraform Kafka Provider](https://github.com/Mongey/terraform-provider-kafka) that would be a more suitable implementer of this.

**Comment by spr-mweber3** [comment]
Allright, thank you very much. I did check out the Kafka Provider but it lacks a lot of functionality. Guess I'll have to wait until AWS natively supports this, if ever. Anyways, thanks for your support. 👍
