### ISSUE TITLE
Consolidate EKS update waiter function

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#18805]
The EKS service has a central function, `DescribeUpdate` (or `DescribeUpdateWithContext`) to track updates to clusters, add-ons, and node groups. This can use a centralized waiter function, but is currently implemented separately for each resource.

The PR #16972 adds the waiter function `EksAddonUpdateSuccessful`. This can be adapted for clusters and node groups.

### Affected Resource

* aws_eks_cluster
* aws_eks_node_group

**Comment by ewbankkit** [comment]
Because each call to `DescribeUpdate` is slightly different (`NodegroupName` must be passed for node group updates, `AddonName` must be passed for add-on updates, etc.), attempting to centralize the waiter will lead to more complex code.
