### ISSUE TITLE
SSO New User & Group Resource

### ISSUE THREAD

**Issue by ajaychoudhary-bcg** [hashicorp/terraform-provider-aws#18812]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Related #18739

### Description

It would be great if we can provide resource to create new group and add members using terraform.

### New or Affected Resource(s)

New

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by YakDriver** [comment]
@ajaychoudhary-bcg This sounds like a good idea. However, can you please provide additional details, such as a possible name for the new resource and what the Terraform configuration would look like?

**Comment by ajaychoudhary-bcg** [comment]
When we create group from UI, it requires only name and description. 
resource "aws_ssoadmin_group" "example" {
name = "test"
description = "test" # Optional argument
users = [list of users arns] # Optional argument
#other attributes as required for integration
}
similarly we need for user
resource "aws_ssoadmin_user" "example" {
Username= string
EmailAddress= string
firstname = string
lastname = string
#other attributes as required for integration
}
and data source for users will also be required with filter to get existing users and add in group.

**Comment by ajaychoudhary-bcg** [comment]
do we know by when this will be available?

**Comment by bhegazy** [comment]
I don't think this is yet possible since it's not yet [supported in AWS SDK ](https://github.com/aws/aws-sdk/issues/25), maybe we should also edit the title to be `SSO New User & Group Resource`

**Comment by rpuserh** [comment]
Any update on this ?

**Comment by rwejdling** [comment]
I guess the best option for now is to enable an [automatic provisioning](https://docs.aws.amazon.com/singlesignon/latest/userguide/provision-automatically.html) endpoint on the SSO tenant and use the [SCIM API](https://docs.aws.amazon.com/singlesignon/latest/developerguide/what-is-scim.html) directly. Annoying, but could work.

**Comment by Stasmo** [comment]
The AWS SCIM API only returns a maximum of 50 users when listing users. There is no way to retrieve the rest of the users. The AWS SCIM endpoint also does not return a user's group information, so there's no way to tell which groups the user is part of. Unfortunately, the AWS SCIM API is not a great option for automated user provisioning.

**Comment by antonioned** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/26598 - currently being worked on by TF team

**Comment by ewbankkit** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/26948 and https://github.com/hashicorp/terraform-provider-aws/pull/26674.

**Comment by rainmanh** [comment]
@ewbankkit is in your roadmap the implementation of the imports for  the following?
- aws_identitystore_user
- aws_identitystore_group

While I can create new User/Groups, I would really need to import  the resources from the existing infrastructure.
I've looked into the current documentation and the import feature is not there for either of them, so I wonder whether that will be done sometime soon.
p.s: I see aws_identitystore_group_membership got the import feature but without the other 2 it's a bit of an issue on this end.

Many thanks

Gonzalo

**Comment by sblask** [comment]
@rainmanh I just imported users and groups, so that just works, but it might not be documented. You can just import using the ID of the user and group unlike the group membership where you need to get the membership ID first.
