### ISSUE TITLE
r/aws_network_interface add support for interface_type argument

### ISSUE THREAD

**Issue by farhanangullia** [hashicorp/terraform-provider-aws#18839]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow the resource to indicate the type of network interface to create. Specifically, to create an Elastic Fabric Adapter (EFA), specify `efa` which is currently supported by the API. 

### New or Affected Resource(s)

* aws_network_interface

### Potential Terraform Configuration

```hcl
resource "aws_network_interface" "foo" {
  subnet_id         = aws_subnet.foo.id
  private_ips       = ["172.16.10.100"]
  interface_type    = "efa"
}
```

### References

* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#network-cards
* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateNetworkInterface.html

**Comment by YakDriver** [comment]
@farhanangullia Cool idea! Thanks for bringing this up. While we aren't able to get to everything we'd like to, you've provided great information!

**Comment by FireballDWF** [comment]
While efa is the open currently supported public value, there are additional values which will be publicly supported in the near future.
