### ISSUE TITLE
aws_iam_policy_document does not update dynamic resources during runtime when new accounts are created and referenced via aws_organizations_organization.org.non_master_accounts

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform-provider-aws#18845]
I have terraform that dynamically creates aws accounts then adds that account to some iam policies using dynamic blocks but is not adding the to-be-created accounts:

### Terraform CLI and Terraform AWS Provider Version

```
terraform version
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/aws v3.29.1
```

### Affected Resource(s)

* aws_organizations_account
* aws_iam_policy_document

### Terraform Configuration Files

```
variable "account_list" {
  description = "This parameter will make OUs and accounts. Its a nested map where data represents account_name: ou_name"
  type        = map(string)
  default = {
    logging  = "core",
    uat      = "uat"
  }
}

resource "aws_organizations_organization" "org" {}

resource "aws_organizations_organizational_unit" "managed" {
  count     = length(distinct(values(var.account_list)))
  name      = distinct(values(var.account_list))[count.index]
  parent_id = aws_organizations_organization.org.roots[0].id
}

resource "aws_organizations_account" "managed" {
  for_each  = var.account_list
  name      = each.key
  email     = "${local.account_email_prefix}+tf-${each.key}@${local.account_email_suffix}"
  role_name = var.master_role_name
  parent_id = compact([for ou in aws_organizations_organizational_unit.managed[*] : ou.name == each.value ? ou.id : ""])[0]
}

data "aws_iam_policy_document" "state_access_by_ou" {
  dynamic "statement" {
    for_each = var.account_list
    content {
      sid    = "${title(statement.value)}${title(statement.key)}OuTFStateAccess"
      effect = "Allow"
      actions = [
        "s3:GetObject",
        "s3:PutObject",
      ]
      principals {
        type = "AWS"
        identifiers = compact([
          for acnt in aws_organizations_organization.org.non_master_accounts :
          acnt.name == statement.key ?
          # true
          join("", ["arn:aws:iam::", acnt.id, ":role/", var.master_role_name])
          # false
          : ""
        ])
      }
      resources = [
      "${data.aws_s3_bucket.state_bucket.arn}/terraform/${statement.value}/${statement.key}/*"]
    }
  }
}
```

### Expected Behavior

terraform plan should output with `(known after apply)`:
```
          + principals {
              + identifiers = {
              AWS = "arn:aws:iam::(known after apply):role/MasterAcntAdmin"
              }
            }
```
### Actual Behavior

`terraform plan` output does not pass in a correct `principal`:
```
statement {
          + actions   = [
              + "s3:GetObject",
              + "s3:PutObject",
            ]
          + effect    = "Allow"
          + resources = [
              + "arn:aws:s3:::<redacted>/terraform/uat/uat/*",
            ]
          + sid       = "UatUatOuTFStateAccess"

          + principals {
              + identifiers = []
              + type        = "AWS"
            }
        }
```

### Important Factoids

If i set `data.aws_iam_policy_document.state_access_by_ou` explicitly `depends_on = [aws_organizations_organization.org]` i get the same result

an example of the `aws_organizations_organization.org.non_master_accounts` [object](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/organizations_organization#non_master_accounts):
```
non_master_acnts = tolist([
  {
    "arn" = "arn:aws:organizations::<redacted>"
    "email" = "test+tf-logging@test.com"
    "id" = "<redacted>>"
    "name" = "logging"
    "status" = "ACTIVE"
  }
])
```

**Comment by YakDriver** [comment]
@drewmullen Thank you for reporting this and including configuration and results! This definitely seems strange. If you or anyone has any ideas on why it is behaving this way, please let us know. Otherwise, hopefully we can look at it soon.

**Comment by drewmullen** [comment]
i havent really looked into the source code at all but just guessing heres where i would look first:
- how does `aws_iam_policy_document` determine whether or not to "wait" before constructing its computed value. perhaps it thinks its getting a valid value, something like `None` or `""`?
- at what point does `aws_organizations_account ` include the new values in the output attributes?
- how does `aws_organizations_account` generate its computed values that are available via `non_master_accounts`?

its probably some odd behavior between non_master_accounts having some values but not the new one to be added

**Comment by drewmullen** [comment]
@YakDriver so ive thought about this problem a lot while ive been working on other stuff.

so i noticed today that the `id` value when you reference the resource directly is available during the 1st apply. however, the value for `aws_organizations_organization.org.non_master_accounts` is not computed till the 2nd terraform apply. I believe this is the key to the problem. 

```
Changes to Outputs:
  ~ non_master_acnts = [
        # (3 unchanged elements hidden)
        {
            arn    = "arn:aws:organizations::<>:account/o-<>/<>"
            email  = "drmullen+tf-<>-dev@amazon.com"
            id     = "<>"
            name   = "dev"
            status = "ACTIVE"
        },
      + {
          + arn    = "arn:aws:organizations::<>:account/o-<>/<>"
          + email  = "drmullen+tf-<>-testaccount@amazon.com"
          + id     = "<>"
          + name   = "testaccount"
          + status = "ACTIVE"
        },
```

the cause has to do with order of operations:
1st `terraform apply`
1. create the org
2. create accounts <- each id value is referenceable specifically

2nd `terraform apply`
1. org is _refreshed_ <- child accounts are found and `non_master_accounts` is populated

can you think of ways that either exist today or could be added to the resource that would allow a refresh of that data in the first tf apply?

**Comment by drewmullen** [comment]
the last comment is actually the ultimate problem. the organizations attributes are populated _after_ the account is created. not a bug - this is just how the tool works. a great workaround is to perform a read of the org after the accounts are created then use that value for the policies, etc:

```
data "aws_organizations_organization" "org" {
  depends_on = [
    aws_organizations_account.managed
  ]
}
```
