### ISSUE TITLE
aws_autoscaling_policy adjustment_type argument causes the resource to be updated in place each time

### ISSUE THREAD

**Issue by jamesmealing** [hashicorp/terraform-provider-aws#18853]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/archive v2.1.0
+ provider registry.terraform.io/hashicorp/aws v3.36.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0

### Affected Resource(s)

* aws_autoscaling_policy

### Terraform Configuration Files

```hcl
resource "aws_autoscaling_policy" "concourse_web" {
  name                   = "concourse-web-autoscaling"
  policy_type            = "TargetTrackingScaling"
  adjustment_type        = "ChangeInCapacity"
  autoscaling_group_name = aws_autoscaling_group.concourse_web.name
  
  target_tracking_configuration {
    predefined_metric_specification {
      predefined_metric_type = "ASGAverageCPUUtilization"
    }
    target_value = 70.0
  }
}
```

### Debug Output

https://gist.github.com/jamesmealing/9ece120333e7c1135e2f74643463a286

### Panic Output

N/A

### Expected Behavior

Specifying the 'adjustment_type' argument shouldn't require the resource to be updated in place on every run.

### Actual Behavior

The 'adjustment_type' argument is recognised as new each time causing the autoscaling policy to be updated in place, even when the argument or its value hasn't changed.

```hcl
Terraform will perform the following actions:

  # module.web.aws_autoscaling_policy.concourse_web will be updated in-place
  ~ resource "aws_autoscaling_policy" "concourse_web" {
      + adjustment_type           = "ChangeInCapacity"
        id                        = "concourse-web-autoscaling"
        name                      = "concourse-web-autoscaling"
        # (6 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

N/A

### References

N/A

**Comment by YakDriver** [comment]
@jamesmealing Sorry you're seeing this! Thank you for reporting it. Problems with unnecessary diffs are annoying. Hopefully we, or someone in the community, will have a chance to figure this out before long.

**Comment by jamesmealing** [comment]
@YakDriver No worries, thanks for getting back to me. From looking at the output of the [describe-policies](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/autoscaling/describe-policies.html) command, 'AdjustmentType' doesn't appear to be in the output in my case, even though it is listed in the documentation as an output... 🤔

**Comment by mamoit** [comment]
@YakDriver, I have the same issue, there is always a diff to add the `adjustment_type` on every plan/apply.
But in my case the `describe-policies` command actually returns the `AdjustmentType` field correctly.

**Comment by mamoit** [comment]
@YakDriver after some investigation, I figured that `AdjustmentType` doesn't make sense with `TargetTrackingScaling`.
I don't know if the provider should validate this though and refuse to apply the changes given that one parameter should not be there.
If you look at the [`TargetTrackingScaling` documentation](https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-scaling-target-tracking.html) you can see that there is no `AdjustmentType` anywhere.
I was looking at the wrong ASG on the `describe-policies` output, mine also does not have the `AdjustmentType`.
