### ISSUE TITLE
EKS Cluster security group

### ISSUE THREAD

**Issue by midestefanis** [hashicorp/terraform-provider-aws#18856]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_eks_cluster
* aws_security_group

### Terraform Configuration Files

```hcl
resource "aws_eks_cluster" "eks-cluster" {
  name                      = var.cluster_name
  version                   = var.cluster_version
  role_arn                  = aws_iam_role.eks_cluster_role.arn
  enabled_cluster_log_types = ["api", "audit", "authenticator", "controllerManager", "scheduler"]

  vpc_config {
    subnet_ids = concat(
      sort(data.aws_subnet_ids.private.ids),
      sort(data.aws_subnet_ids.public.ids)
    )

    security_group_ids = tolist([aws_security_group.eks-sg.id])

  }

  encryption_config {
    resources = ["secrets"]
    provider {
      key_arn = aws_kms_key.eks-kms.arn
    }
  }

  tags = merge(local.tags, { tf_mod = "eks-cluster" })

  depends_on = [
    aws_iam_role_policy_attachment.AmazonEKSClusterPolicy1,
    aws_iam_role_policy_attachment.AmazonEKSVPCResourceController1,
    aws_security_group.eks-sg,
    aws_security_group_rule.cluster_ingress-0,
    aws_security_group_rule.cluster_egress-0,
    aws_security_group_rule.cluster_egress-1
  ]
}

resource "aws_security_group" "eks-sg" {
  name_prefix = var.cluster_name
  vpc_id      = var.vpc_id
  tags = merge(
    var.tags,
    {
      "Name"                                      = "${var.cluster_name}-eks_cluster_sg",
      "kubernetes.io/cluster/${var.cluster_name}" = "owned",
    }
  )
}

resource "aws_security_group_rule" "cluster_ingress-0" {
  security_group_id        = aws_security_group.eks-sg.id
  protocol                 = -1
  from_port                = 0
  to_port                  = 0
  type                     = "ingress"
  source_security_group_id = aws_security_group.eks-sg.id
}

resource "aws_security_group_rule" "cluster_egress-0" {
  security_group_id        = aws_security_group.eks-sg.id
  protocol                 = "TCP"
  from_port                = 10250
  to_port                  = 10250
  type                     = "egress"
  source_security_group_id = aws_security_group.eks-sg.id
}

resource "aws_security_group_rule" "cluster_egress-1" {
  security_group_id        = aws_security_group.eks-sg.id
  protocol                 = "TCP"
  from_port                = 443
  to_port                  = 443
  type                     = "egress"
  source_security_group_id = aws_security_group.eks-sg.id
}
```

### Actual Behavior

I was expecting that when i create manually the Security Group with MY rules AWS doesn't creates the Security Group and let me handle it. But this isn't happening, AWS or the module is creating the security group anyway.

I'm running EKS with Fargate

### Behavior that i need

What I need is that the Security Groups have the corresponding rules applied. I can't allow all outbound traffic.

I tried two different approaches:

1 - With a Data Source bring the SG and add the rules I need. This worked but it left me the rule that enables all outgoing traffic (I mean the same as nothing). I also did not find a way to delete a rule about an SG, just how to add them.

```
resource "aws_security_group_rule" "cluster_egress-0" {
  #security_group_id       = aws_security_group.eks-sg.id
  security_group_id        = aws_eks_cluster.eks-cluster.vpc_config[0].cluster_security_group_id
  protocol                 = "TCP"
  from_port                = 10250
  to_port                  = 10250
  type                     = "egress"
  source_security_group_id = aws_eks_cluster.eks-cluster.vpc_config[0].cluster_security_group_id
}

resource "aws_security_group_rule" "cluster_egress-1" {
  security_group_id        = aws_eks_cluster.eks-cluster.vpc_config[0].cluster_security_group_id
  protocol                 = "TCP"
  from_port                = 443
  to_port                  = 443
  type                     = "egress"
  source_security_group_id = aws_eks_cluster.eks-cluster.vpc_config[0].cluster_security_group_id
}
```

![image](https://user-images.githubusercontent.com/59846928/114768699-9f892d80-9d3f-11eb-9836-f1faabd9bd79.png)

2 - I tried creating the SG as I show in the code and following the doc -> https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html
This also didn't "work" since it created both for me. 
 
The strange thing is that when I validate which Security Group is using, it is what I create and not what AWS creates. But in console I see the other created as well.

### References

* https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#vpc_config

**Comment by YakDriver** [comment]
@midestefanis I'm sorry you are having this problem. It should allow you to create and associate the correct SG. While I don't see immediately why this is happening, perhaps looking at the acceptance tests and how they are structured would provide insight. The test in particular looks to be doing something similar: https://github.com/hashicorp/terraform-provider-aws/blob/158803d44ee32a9542d002fd561c1a158597601a/aws/resource_aws_eks_cluster_test.go#L779

This may be a bug but if it is not, it may be helpful to discuss the issue at https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33.
