### ISSUE TITLE
aws_efs_mount_target data source lookup by file_system_id and access_point_id

### ISSUE THREAD

**Issue by sheisnicola** [hashicorp/terraform-provider-aws#18859]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great to allow `aws_efs_mount_target` data source lookups based on EFS file system ID, as is described by https://docs.aws.amazon.com/cli/latest/reference/efs/describe-mount-targets.html, and can be achieved by the following example AWS CLI command: `aws efs describe-mount-targets --file-system-id fs-xxxxxxxx`

### New or Affected Resource(s)

* aws_efs_mount_target

### Potential Terraform Configuration

```hcl
data "aws_efs_mount_target" {
  file_system_id = "fs-xxxxxxxx"
}
```

### References

* https://docs.aws.amazon.com/efs/latest/ug/API_DescribeMountTargets.html
* https://docs.aws.amazon.com/cli/latest/reference/efs/describe-mount-targets.html

**Comment by YakDriver** [comment]
@sheisnicola Thanks for bringing this up! Please see #18918 with a fix.
