### ISSUE TITLE
CloudTrail support for Advanced Event Selectors

### ISSUE THREAD

**Issue by luisrussi** [hashicorp/terraform-provider-aws#18867]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

From the documentation, I can see how to deploy a CloudTrail with basic data [event selector](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail#data-event-logging), but I was not able to deploy an [advanced data event selector](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-data-events-with-cloudtrail.html#creating-data-event-selectors-advanced).
Is this a valid request? If not, can you point me to the documentation, please?

### New or Affected Resource(s)

* aws_cloudtrail

### Potential Terraform Configuration

```hcl
resource "aws_cloudtrail" "event-trail" {
  # ... trail configuration ...

  advanced_event_selector {
    name      = var.name
    field_selectors = [ 
        'Field': 'string',
        'Equals': [
            'string',
        ],
        'StartsWith': [
            'string',
        ],
        'EndsWith': [
            'string',
        ],
        'NotEquals': [
            'string',
        ],
        'NotStartsWith': [
            'string',
        ],
        'NotEndsWith': [
            'string',
        ]
    ]
    }
}
```

### References

I haven't found a related issue here (maybe I missed it, sorry for that!), but I can add:
[AWS docs](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-data-events-with-cloudtrail.html#creating-data-event-selectors-advanced)
[Boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudtrail.html#CloudTrail.Client.put_event_selectors)

**Comment by YakDriver** [comment]
@luisrussi Thanks for raising this enhancement! I personally think that given the importance of security, this feature would be very useful. I don't see another related issue or PR. I've also verified nothing in the code refers to `AdvancedEventSelector` or  `AdvancedFieldSelector`. If the capability existed, both of these would be required.

If enough people express interest, we will be able to take this on. Or, if someone from the community wants to create a PR, we can take a look.

Docs for future travelers:
* https://docs.aws.amazon.com/sdk-for-go/api/service/cloudtrail/#AdvancedEventSelector
* https://docs.aws.amazon.com/sdk-for-go/api/service/cloudtrail/#AdvancedFieldSelector
* https://docs.aws.amazon.com/sdk-for-go/api/service/cloudtrail/#CloudTrail.PutEventSelectors
* https://docs.aws.amazon.com/sdk-for-go/api/service/cloudtrail/#PutEventSelectorsInput
* https://docs.aws.amazon.com/sdk-for-go/api/service/cloudtrail/#PutEventSelectorsOutput
* https://docs.aws.amazon.com/sdk-for-go/api/service/cloudtrail/#InvalidEventSelectorsException
* https://docs.aws.amazon.com/sdk-for-go/api/service/cloudtrail/#GetEventSelectorsInput
* https://docs.aws.amazon.com/sdk-for-go/api/service/cloudtrail/#GetEventSelectorsOutput
* https://docs.aws.amazon.com/sdk-for-go/api/service/cloudtrail/#DataResource
* https://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-data-events-with-cloudtrail.html

**Comment by luisrussi** [comment]
Hi @YakDriver , how are you doing?
I will take the opportunity to understand the Terraform provider code (and also Go) and adventure myself with this addition. I hope I can create a PR soon :D
