### ISSUE TITLE
Feature Request: Support Managed Failovers for Aurora Global Clusters

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#18863]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_rds_global_cluster_primary

### Potential Terraform Configuration

```hcl
resource "aws_rds_global_cluster_primary" "example" {
  global_cluster_identifier    = aws_rds_global_cluster.example.id
  target_db_cluster_identifier = aws_rds_cluster.example.id
}
```

### References

- https://aws.amazon.com/about-aws/whats-new/2021/02/amazon-aurora-global-database-supports-managed-planned-failover/
- https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_FailoverGlobalCluster.html
- https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_FailoverState.html

**Comment by bflad** [comment]
Some additional design notes:

* The reasoning for a separate resource would be to reduce chances for configuration cycles, which are easy to create today between `aws_rds_global_cluster` and `aws_rds_cluster` given they must reference each other already (opposite direction if creating global cluster via source cluster)
* Given this resource is better suited for "adopting" existing infrastructure, this resource's `Create` function should perform a read-only check and no-op if the primary is already correct 👍
