### ISSUE TITLE
Redshift Cluster AQUA Support

### ISSUE THREAD

**Issue by troxil** [hashicorp/terraform-provider-aws#18869]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS announced some time back in 2020 - Redshift AQUA. As of today it has now been [officially released](https://aws.amazon.com/blogs/aws/new-aqua-advanced-query-accelerator-for-amazon-redshift/), with roll out pending in the first half of this year. 

The functionality is already present in the UI for certain node types as well as the Redshift API as [AquaConfigurationStatus](https://docs.aws.amazon.com/redshift/latest/APIReference/API_CreateCluster.html).

### New or Affected Resource(s)

* `aws_redshift_cluster`

### Potential Terraform Configuration

```hcl
resource "aws_redshift_cluster" "default" {
  cluster_identifier = "tf-redshift-cluster"
  database_name      = "mydb"
  master_username    = "foo"
  master_password    = "Mustbe8characters"
  node_type          = "dc1.large"
  cluster_type       = "single-node"
  aqua_status        = "enabled"  # other options include "disabled" and "auto"
}
```

### References

* [AQUA (Advanced Query Accelerator) – A Speed Boost for Your Amazon Redshift Queries](https://aws.amazon.com/blogs/aws/new-aqua-advanced-query-accelerator-for-amazon-redshift/)
* [YouTube: AWS re:Invent 2020: Introduction to AQUA for Amazon Redshift (Preview)](https://www.youtube.com/watch?v=0LVyd-kqpdE)
* [Golang AWS SDK - CreateClusterInput](https://docs.aws.amazon.com/sdk-for-go/api/service/redshift/#CreateClusterInput) - New Clusters
* [Golang AWS SDK - ModifyAquaConfiguration](https://docs.aws.amazon.com/sdk-for-go/api/service/redshift/#Redshift.ModifyAquaConfiguration) - Toggling existing resources

**Comment by YakDriver** [comment]
@troxil Cool! Thanks for raising this.
