### ISSUE TITLE
single quote is not supported in the description attribute of aws_security_group and aws_security_group_rule resource

### ISSUE THREAD

**Issue by satyamsareen** [hashicorp/terraform-provider-aws#18874]
Hi,

So I wanted to add a description for one of my rules in a security group that had an **Apostrophe** in it.
Looks like it is not supported.

Snippet:
```
ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "ssh"
    cidr_blocks = ["SOME.IP.ADD.RESS/32"]
    description="SSH FROM CUSTOMER'S IP"
  }
```
I get the below error:
_Error: "ingress.0.description" doesn't comply with restrictions ("^[A-Za-z0-9 \\.\\_\\-\\:\\/\\(\\)\\#\\,\\@\\[\\]\\+\\=\\&\\;\\{\\}\\!\\$\\*]*$"): "SSH FROM CUSTOMER'S IP"

I even tried using the replace function as below. But no luck:(
`description=replace("SSH FROM CUSTOMER'S IP","'","'")`

The same value i.e "SSH FROM CUSTOMER'S IP" works fine if give as a value of an output. Thus it makes me believe it could be a bug. I also tried escaping but no luck.

```
output "test" {
    value = "SSH FROM CUSTOMER\"S IP"
}
```
It is not a big issue, but any help will be appreciated.

Thank you, contributors!

**Comment by YakDriver** [comment]
The error message you are receiving comes from the AWS SDK for Go. We cannot change the validation for this so I'm going to close this issue. For reference, the regex AWS uses to validate is `^[A-Za-z0-9 \.\_\-\:\/\(\)\#\,\@\[\]\+\=\&\;\{\}\!\$\*]*$`.
