### ISSUE TITLE
cloudfront origin for application loadbalancer

### ISSUE THREAD

**Issue by umapathireddy** [hashicorp/terraform-provider-aws#18872]
terraform for alb

locals {
  alb_origin_id =  "test"
}
resource "aws_cloudfront_distribution" "alb_beanstalk" {
  origin {
    domain_name = "aws_elastic_beanstalk_environment.environment.endpoint_url"   ####### alb endpoint print using variable
    origin_id   = local.alb_origin_id
   }

  enabled             = true
  restrictions {
    geo_restriction {
      restriction_type = "none"
     }

   }
  default_cache_behavior {
    allowed_methods  = ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = local.alb_origin_id

    forwarded_values {
      query_string = false

      cookies {
        forward = "none"
      }
    }

    viewer_protocol_policy = "allow-all"
    min_ttl                = 0
    default_ttl            = 3600
    max_ttl                = 86400
   }
  viewer_certificate {
    cloudfront_default_certificate = true
   }

alb endpoint output

**error ourput**

Error: error creating CloudFront Distribution: InvalidArgument: The parameter Origin DomainName does not refer to a valid S3 bucket.
        status code: 400, request id: 6db303a1-9719-46a5-bd4e-c8de42a26ec0

  on main.tf line 136, in resource "aws_cloudfront_distribution" "alb_beanstalk":
 136: resource "aws_cloudfront_distribution" "alb_beanstalk" {
 
 
 
 please help any create cloudfront with alb using terraform

**Comment by ewbankkit** [comment]
@umapathireddy  Thanks for raising this issue.
It has already been noticed in #412. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
