### ISSUE TITLE
resource_aws_cloudtrail errors out when validating data_resource type AWS::DynamoDB::Table

### ISSUE THREAD

**Issue by ryanbreed-clearme** [hashicorp/terraform-provider-aws#18906]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.6
+ provider registry.terraform.io/-/aws v3.36.0
```

### Affected Resource(s)

* aws_cloudtrail

### Terraform Configuration Files

```hcl
data "aws_partition" "main_current" {}

resource "aws_cloudtrail" "very_chatty_cloudtrail" {
  name                          = "unhappy-trail"
  s3_bucket_name                = "any-cloudtrail-bucket"
  enable_logging                = true
  include_global_service_events = true
  is_multi_region_trail         = true
  enable_log_file_validation    = true

  event_selector {
    read_write_type           = "All"
    include_management_events = true
    data_resource {
      type   = "AWS::Lambda::Function"
      values = ["arn:${data.aws_partition.main_current.partition}:lambda"]
    }
  }

  event_selector {
    read_write_type           = "All"
    include_management_events = true
    data_resource {
      type   = "AWS::S3::Object"
      values = ["arn:${data.aws_partition.main_current.partition}:s3:::"]
    }
  }

  event_selector {
    read_write_type           = "All"
    include_management_events = true
    data_resource {
      type   = "AWS::DynamoDB::Table"
      values = ["arn:${data.aws_partition.main_current.partition}:dynamodb"]
    }
  }
}
```

### Debug Output

error log [here](https://gist.github.com/ryanbreed-clearme/5d2e7f6f0a2050aba03ef9ea675089be)

### Expected Behavior

This configuration is required to implement data plane event logging of DynamoDB tables in cloudtrail and is a permitted configuration of the resource per the current api spec

### Actual Behavior
errors out when validating `data_resource` in `https://github.com/hashicorp/terraform-provider-aws/blob/v3.36.0/aws/resource_aws_cloudtrail.go#L113`

`ValidateFunc` only checks membership in `{"AWS::S3::Object", "AWS::Lambda::Function"}`

```
Error: expected event_selector.2.data_resource.0.type to be one of [AWS::S3::Object AWS::Lambda::Function], got AWS::DynamoDB::Table
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

* Tried in ue1 and govcloud

### References

* [Current reference for data type DataResource in CloudTrail API](https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_DataResource.html)

**Comment by anGie44** [comment]
Hi @ryanbreed-clearme, thank you for raising this issue. Support for that `type` is being addressed in a PR tied to a similar issue (https://github.com/hashicorp/terraform-provider-aws/issues/18394) , so I'd refer there to follow-up on the needed change. I'm going to close this as a duplicate, but thank you again 😃 !
