### ISSUE TITLE
Terraform replaces imported VPC Peering due to "known after apply" on peer_owner_id

### ISSUE THREAD

**Issue by mmingorance-dh** [hashicorp/terraform-provider-aws#18904]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/aws v3.36.0
+ provider registry.terraform.io/hashicorp/external v1.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.3
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Terraform Configuration Files

Resources to create the VPC peering as a module:
```hcl
data "aws_caller_identity" "current" {}

# VPC peering connection requester
resource "aws_vpc_peering_connection" "peering_requester" {
  peer_owner_id = data.aws_caller_identity.current.account_id
  peer_vpc_id   = var.accepter_vpc_id
  vpc_id        = var.requester_vpc_id
  auto_accept   = true

  accepter {
    allow_remote_vpc_dns_resolution = true
  }

  requester {
    allow_remote_vpc_dns_resolution = true
  }
}

## Peering accepter
resource "aws_vpc_peering_connection_accepter" "peering_accepter" {
  vpc_peering_connection_id = aws_vpc_peering_connection.peering_requester.id
  auto_accept               = true
}

data "aws_vpc" "requester" {
  id = var.requester_vpc_id
}

data "aws_vpc" "accepter" {
  id = var.accepter_vpc_id
}

# Routes for the peering requester
resource "aws_route" "peering_requester" {
  count = length(var.peering_requester_routes)

  vpc_peering_connection_id = aws_vpc_peering_connection.peering_requester.id
  route_table_id            = var.peering_requester_routes[count.index]
  destination_cidr_block    = data.aws_vpc.accepter.cidr_block
}

# Routes for the peering accepter
resource "aws_route" "peering_accepter" {
  count = length(var.peering_accepter_routes)

  vpc_peering_connection_id = aws_vpc_peering_connection.peering_requester.id
  route_table_id            = var.peering_accepter_routes[count.index]
  destination_cidr_block    = data.aws_vpc.requester.cidr_block
}
```

### Affected Resource(s)
```hcl
# module.vpc_peering.aws_vpc_peering_connection.peering_requester must be replaced
-/+ resource "aws_vpc_peering_connection" "peering_requester" {
      ~ accept_status = "active" -> (known after apply)
      + auto_accept   = true
      ~ id            = "pcx-123456789" -> (known after apply)
      ~ peer_owner_id = "$ACCOUNT_NUMBER" -> (known after apply) # forces replacement
      ~ peer_region   = "ap-southeast-1" -> (known after apply)
        # (2 unchanged attributes hidden)
    }

  # module.vpc_peering.aws_vpc_peering_connection_accepter.peering_accepter must be replaced
-/+ resource "aws_vpc_peering_connection_accepter" "peering_accepter" {
      ~ accept_status             = "active" -> (known after apply)
      + auto_accept               = true
      ~ id                        = "pcx-0694c9182c811e655" -> (known after apply)
      ~ peer_owner_id             = "$ACCOUNT_NUMBER" -> (known after apply)
      ~ peer_region               = "ap-southeast-1" -> (known after apply)
      ~ peer_vpc_id               = "vpc-54321" -> (known after apply)
      ~ vpc_id                    = "vpc-12345" -> (known after apply)
      ~ vpc_peering_connection_id = "pcx-123456789" -> (known after apply) # forces replacement

      ~ accepter {
          ~ allow_classic_link_to_remote_vpc = false -> (known after apply)
          ~ allow_remote_vpc_dns_resolution  = true -> (known after apply)
          ~ allow_vpc_to_remote_classic_link = false -> (known after apply)
        }

      ~ requester {
          ~ allow_classic_link_to_remote_vpc = false -> (known after apply)
          ~ allow_remote_vpc_dns_resolution  = true -> (known after apply)
          ~ allow_vpc_to_remote_classic_link = false -> (known after apply)
        }
    }
```

### Expected Behavior

Terraform should have detected that the `peer_owner_id` of the imported VPC peering is the same as in the new Terraform plan/apply. Therefore, no changes should have been required.

### Actual Behavior

Terraform detected the `peer_owner_id` as a `known after apply` value and caused the replacement of the VPC peering during the Terraform apply.

### Steps to Reproduce
1. Create a VPC Peering manually or through a different Terraform module. Both, `owner_id` and `peer_owner_id` must be the same
2. Create a new Terraform module and import the previously created VPC Peering to this new Terraform module.
3. Run Terraform plan and see the `# forces replacement` label
4. Run Terraform apply and observe how the VPC Peering is recreated.

**Comment by YakDriver** [comment]
@mmingorance-dh Sorry you're having this issue! Thanks for reporting it. We hope to have a chance to take a look at this.

Possibly related #14496
