### ISSUE TITLE
aws_ssm_document failed to be updated when package content is changed

### ISSUE THREAD

**Issue by gabrielgutunoi** [hashicorp/terraform-provider-aws#18913]
Here is a snippet of my code that creates successfully a SSM package in AWS: 
```
resource "aws_ssm_document" "ssm_package" {
  depends_on = [data.archive_file.package]
  name          = "${var.product}-${var.env}-${var.name}"
  document_type = "Package"
  tags          = local.tags

  attachments_source {
    key    = "SourceUrl"
    values = [local.s3_url]
  }
  content = templatefile("${path.module}/schema.tpl", { platform = var.platform, file = "${local.ssm_name}.zip", checksum = data.external.sha256.result.output })
}

locals {
  s3_url      = "https://s3.amazonaws.com/${var.s3_bucket_name}/ssm_document_packages"
}
```

If files of the package are changed I would expect that the ssm will be updated, but instead I got this error:

Error: Error updating SSM document: InvalidParameterValueException: AttachmentSource not provided in the input request.
	status code: 400, request id: 65931e7e-37b1-4ef2-84c3-7c2ccadda44c
  on ../ssm.tf line 1, in resource "aws_ssm_document" "ssm_package":

Extract from plan stage:
```
 ~ update in-place
Terraform will perform the following actions:
  # module.ssm_linux.aws_ssm_document.ssm_package will be updated in-place
  ~ resource "aws_ssm_document" "ssm_package" {
        arn              = "arn:aws:ssm:eu-west-2:450845411598:document/frtt-ci-test-pck"
      ~ content          = jsonencode(
          ~ {
              ~ files         = {
                  - frtt-ci-test-pck6.zip = {
                      - checksums = {
                          - sha256 = "d8bbb92347b097c574b1264e4a2dfe22af3afeb2bfc5d92a6a13d59e05ca804b"
                        }
                    } -> null
                  + frtt-ci-test-pck7.zip = {
                      + checksums = {
                          + sha256 = "d8bbb92347b097c574b1264e4a2dfe22af3afeb2bfc5d92a6a13d59e05ca804b"
                        }
                    }
                }
              ~ packages      = {
                  ~ amazon = {
                      ~ _any = {
                          ~ x86_64 = {
                              ~ file = "frtt-ci-test-pck6.zip" -> "frtt-ci-test-pck7.zip"
                            }
                        }
                    }
```

Terraform version is v0.13.5 and aws provider is v3.36.0.

**Comment by YakDriver** [comment]
@gabrielgutunoi Thanks for reporting this problem! To clarify, you're saying that the first apply works. Then, you change the files or the configuration? After that, a new apply fails?

**Comment by gabrielgutunoi** [comment]
@YakDriver The first apply works, then if the files from the package are changed terraform fails to update the ssm package.

**Comment by gabrielgutunoi** [comment]
@YakDriver Any update for this issue?

**Comment by jverhoeks** [comment]
I ran into the same issue. Looks like for create it is attached
https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_ssm_document.go#L216
With the update there is no attachments 
https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_ssm_document.go#L375

It is supported by the API: https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_UpdateDocument.html

I'll create a PR and attach it to this ticket. Hopefully it can be merged quickly then.

**Comment by jverhoeks** [comment]
While diving deeper into this

https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_ssm_document.go#L673
This will also add the attachment when the attachment is changes.  Just tested this and it works.

making a small PR to always add the attachement as it's required by the API
