### ISSUE TITLE
Error: "email_verification_message" cannot be longer than 20000 characters

### ISSUE THREAD

**Issue by mg98** [hashicorp/terraform-provider-aws#18912]
```
Terraform v0.15.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.36.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

I think the bug mentioned in https://github.com/hashicorp/terraform-provider-aws/issues/2600 still persists! The error message changed. It says that the string cannot be longer than 20.000 characters (which is correct), but from my observations the limit is still set to 2000 characters! So texts longer than 2000 characters and shorter than 20.000 characters will still throw this error!

**Comment by YakDriver** [comment]
@mg98 Can you provide a configuration to reproduce the issue?

From what I see, this limit is 20000:

https://github.com/hashicorp/terraform-provider-aws/blob/79da3dd367c2bd9a820953626a6a8ca97d1c2d5a/aws/validators.go#L1584 

https://github.com/hashicorp/terraform-provider-aws/blob/79da3dd367c2bd9a820953626a6a8ca97d1c2d5a/aws/validators.go#L1656

https://github.com/hashicorp/terraform-provider-aws/blob/79da3dd367c2bd9a820953626a6a8ca97d1c2d5a/aws/validators.go#L1672

https://github.com/hashicorp/terraform-provider-aws/blob/79da3dd367c2bd9a820953626a6a8ca97d1c2d5a/aws/validators.go#L1736

**Comment by mg98** [comment]
Really strange. But sure, I can share a minimal configuration. Try applying the following tf

```
resource "aws_cognito_user_pool" "client_user_pool" {
  name                       = "test"
  username_attributes        = ["email"]
  auto_verified_attributes   = ["email"]
  email_verification_subject = "Votre code de vérification"
  email_verification_message = file("${path.module}/email-verification-template.html")

  password_policy {
    minimum_length                   = 8
    require_lowercase                = true
    require_uppercase                = true
    require_numbers                  = true
    require_symbols                  = false
    temporary_password_validity_days = 7
  }
}

resource "aws_cognito_user_pool_client" "client_pool_client" {
  name                = "test-client"
  user_pool_id        = aws_cognito_user_pool.client_user_pool.id
  generate_secret     = false
  explicit_auth_flows = ["ADMIN_NO_SRP_AUTH"]
}
```

using this `email-verification-template.html` file in the same folder: https://pastebin.com/mEaG3ck6

The html file has a length of ~3400 characters. Before I minified the html it had a length of ~6700 characters. Both give me the error.

I also tried using a 7000 char long string, generated by https://loremipsum.de/, and it would work! Any idea why that is?

Thank you very much for your investigation.
