### ISSUE TITLE
aws_lambda_event_source_mapping ValidationException should be more descriptive

### ISSUE THREAD

**Issue by yoshutch** [hashicorp/terraform-provider-aws#18917]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating a aws_lambda_event_source_mapping resource for a DynamoDB Table I got a very generic error:
```
Error: error creating Lambda Event Source Mapping (): ValidationException: 
	status code: 400, request id: xxxxxxxxxxxxx
```

Turns out all I needed to do was enable streams on my DynamoDB table.

It would be nice to explain why the ValidationException was thrown. Maybe something like `Event Source does not support streams`

### New or Affected Resource(s)

* aws_lambda_event_source_mapping

### Terraform Configuration

```hcl
resource "aws_dynamodb_table" "events" {
  name         = "events"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "event_id"
  tags         = var.tags

  attribute {
    name = "event_id"
    type = "S"
  }
}
resource "aws_lambda_event_source_mapping" "event_dynamo" {
  event_source_arn  = aws_dynamodb_table.events.stream_arn
  function_name     = aws_lambda_function.my_function.function_name
  starting_position = "LATEST"
}
```
#### Results in this error
```
aws_lambda_event_source_mapping.event_dynamo: Creating...

Error: error creating Lambda Event Source Mapping (): ValidationException: 
	status code: 400, request id: xxxxxxxxxxxxx

  on main.tf line 12, in resource "aws_lambda_event_source_mapping" "event_dynamo":
 12: resource "aws_lambda_event_source_mapping" "event_dynamo" {
```
#### Should result in a more descriptive error
```
aws_lambda_event_source_mapping.event_dynamo: Creating...

Error: error creating Lambda Event Source Mapping (): ValidationException: 
	status code: 400, request id: xxxxxxxxxxxxx
        error message: provided 'event_source_arn' does not support streams

  on main.tf line 12, in resource "aws_lambda_event_source_mapping" "event_dynamo":
 12: resource "aws_lambda_event_source_mapping" "event_dynamo" {
```

**Comment by YakDriver** [comment]
@yoshutch Thank you for letting us know. The problem here is that, from the code, we don't know what the reason for the error is beyond what AWS provides. `error creating Lambda Event Source Mapping` comes from the AWS Provider. The other portion, `ValidationException: status code: 400, request id: xxxxxxxxxxxxx` comes from AWS.

In this situation, perhaps the best idea would be to update the documentation to alert users to the potential fix. Another possibility is to contact AWS directly through Support in your AWS account to request the API provide a more useful error.
