### ISSUE TITLE
Is there a reason there is no dataSourceFiltersSchema for the aws_lb data type?

### ISSUE THREAD

**Issue by juandiegopalomino** [hashicorp/terraform-provider-aws#18921]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Is there a reason there is no dataSourceFiltersSchema for the aws_lb data type?
Genuinely curious as EKS automatically creates lbs for me and it'd be great to filter them based on tags
### New or Affected Resource(s)

* aws_lb

### Potential Terraform Configuration

```hcl
data "aws_lb" "test" {
filter {
    name   = "tag:Name"
    values = ["instance-name-tag"]
  }
}
```

### References

* #0000

**Comment by ewbankkit** [comment]
@juandiegopalomino Thanks for raising this issue.
The simple answer is that the underlying [AWS `DescribeLoadBalancers` API](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_DescribeLoadBalancers.html) has no `Filters` parameter and so the Terraform resource has no `filter` attribute.

If what you require is the ability to just filter load balancers by tags, there is an existing issue (#12265) for that.
Please upvote that issue if appropriate.

**Comment by juandiegopalomino** [comment]
@ewbankkit thank you!
