### ISSUE TITLE
error setting replica: Invalid address to set: []string{"replica", "0", "kms_key_arn"}

### ISSUE THREAD

**Issue by explorigin** [hashicorp/terraform-provider-aws#18922]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.2
+ provider registry.terraform.io/hashicorp/aws v3.37.0

Your version of Terraform is out of date! The latest version
is 0.15.0. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

* aws_dynamodb_table

### Terraform Configuration Files

https://gist.github.com/explorigin/d200614c77d13f2eb5ee6d57288a55d5

### Debug Output

https://gist.github.com/explorigin/d200614c77d13f2eb5ee6d57288a55d5

### Expected Behavior

Plan completes.

### Actual Behavior

(See output and issue title)

### Steps to Reproduce

1. `terraform plan`

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/17125

**Comment by ewbankkit** [comment]
Related:

* #18844
