### ISSUE TITLE
aws_storagegateway_upload_buffer : Error: error reading Storage Gateway Upload Buffer (arn:aws:storagegateway:XXXXXX:gateway/sgw-XXXX:/dev/XXX): not found during apply

### ISSUE THREAD

**Issue by AdrianBegg** [hashicorp/terraform-provider-aws#18928]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v0.15.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.36.0
```

### Affected Resource(s)

* aws_storagegateway_upload_buffer

### Terraform Configuration Files

```
resource "aws_storagegateway_gateway" "storage_gw_EC2" {
  gateway_ip_address   = aws_instance.storage_gw_appliance.public_ip
  gateway_name         = "EC2-Example"
  gateway_timezone     = "GMT"
  gateway_type         = "CACHED"

  timeouts {
    create = "12m"
  }
}

data "aws_storagegateway_local_disk" "ec2_buffer_disk" {
  disk_node   = "/dev/sdc"
  gateway_arn = aws_storagegateway_gateway.storage_gw_EC2.arn

  depends_on = [
    aws_storagegateway_gateway.storage_gw_EC2
  ]
}

resource "aws_storagegateway_upload_buffer" "storage_gw_EC2" {
  disk_id     = data.aws_storagegateway_local_disk.ec2_buffer_disk.id
  gateway_arn = aws_storagegateway_gateway.storage_gw_EC2.arn
}
```

### Expected Behavior

* The resource functions correctly, creates/configures the resource and continues execution

### Actual Behavior

* Resource is created/configured in AWS
* Terraform throws the following error, marks the resource as tainted and breaks workflow
```
 Error: error reading Storage Gateway Upload Buffer (arn:aws:storagegateway:region:account:gateway/sgw-XXXXX:/dev/xvdc): not found

   on storagegw.tf line 252, in resource "aws_storagegateway_upload_buffer" "storage_gw_EC2":
  252: resource "aws_storagegateway_upload_buffer" "storage_gw_EC2" {

```
* Subsequent executions throws:
```
Error: error adding Storage Gateway upload buffer: InvalidGatewayRequestException: The specified disk is already allocated.
{
   RespMetadata: {
     StatusCode: 400,
     RequestID: "XXXXX"
   },
   Error_: {
     ErrorCode: "DiskAlreadyAllocated"
   },
   Message_: "The specified disk is already allocated."
 }
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
N/A

### References

* #0000

**Comment by bflad** [comment]
Hi @AdrianBegg 👋 

When working with cached type Storage Gateways, behaviors in the Storage Gateway API require a slightly different configuration with the `disk_path` argument instead of the `disk_id` argument. There is a quick example available in the [`aws_storagegateway_upload_buffer` resource documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/storagegateway_upload_buffer#cached-and-vtl-gateway-type) for reference. So for in your case:

```terraform
resource "aws_storagegateway_upload_buffer" "storage_gw_EC2" {
  disk_path   = data.aws_storagegateway_local_disk.ec2_buffer_disk.disk_path
  gateway_arn = aws_storagegateway_gateway.storage_gw_EC2.arn
}
```

Hope this helps. 👍
