### ISSUE TITLE
Provider produced inconsistent final plan aws_autoscaling_group force_delete_warm_pool

### ISSUE THREAD

**Issue by bpazera** [hashicorp/terraform-provider-aws#18937]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.37.0
+ provider registry.terraform.io/hashicorp/helm v2.1.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v2.3.1
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* aws_autoscaling_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_autoscaling_group" "eks_node" {
  name_prefix = "${local.environment_name}-eks-node${var.SUFFIX}-"

  timeouts {
    delete = "60m"
  }

  launch_template {
    id      = aws_launch_template.eks_node.id
    version = aws_launch_template.eks_node.latest_version
  }

  vpc_zone_identifier       = var.SUBNET_IDS
  min_size                  = 3
  desired_capacity          = 3
  max_size                  = 4
  health_check_grace_period = 60
  health_check_type         = EC2
  default_cooldown          = 300
  force_delete              = false
  wait_for_capacity_timeout = 0
  target_group_arns         = var.TARGET_GROUP_ARNS

  enabled_metrics = [
    "GroupMinSize",
    "GroupMaxSize",
    "GroupDesiredCapacity",
    "GroupInServiceInstances",
    "GroupPendingInstances",
    "GroupStandbyInstances",
    "GroupTerminatingInstances",
    "GroupTotalInstances",
  ]
}
```

### Panic Output
```
Error: Provider produced inconsistent final plan

When expanding the plan for module.eks_node.aws_autoscaling_group.eks_node to
include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.force_delete_warm_pool: was cty.False, but now null.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Expected Behavior
* apply without errors
* **force_delete_warm_pool** documented under https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
When added:
```
provider "aws" {
  version = "<3.37"
}
```
and having
```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.36.0
+ provider registry.terraform.io/hashicorp/helm v2.1.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v2.3.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
```
there are no problems

**Comment by paulbailey** [comment]
For what it's worth, I was able to work around this issue by manually removing the offending ASGs from the state, and then importing them back in with the latest provider.

**Comment by jsojourner11** [comment]
Can we at least have the documentation https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group updated to explain what force_delete_warm_pool does?
