### ISSUE TITLE
loglevel is not supported by resource_aws_datasync_task

### ISSUE THREAD

**Issue by nikhil-goenka** [hashicorp/terraform-provider-aws#18933]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

resource_aws_datasync_task doesn't support loglevel param and by default it is OFF.

### New or Affected Resource(s)

* resource_aws_datasync_task

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by bflad** [comment]
DataSync API Reference for new attribute: https://docs.aws.amazon.com/datasync/latest/userguide/API_Options.html#DataSync-Type-Options-LogLevel
