### ISSUE TITLE
RDS DB instance resource does not change license model on existing RDS instance

### ISSUE THREAD

**Issue by gchristidis** [hashicorp/terraform-provider-aws#19009]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.37.0

### Affected Resource(s)

* aws_db_instance

### Terraform Configuration Files

An example Terraform source file to show issue

```hcl
terraform {
  required_version = "~> 0.13"
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}


variable "rds_license" {
  default = "license-included"
  type = string
}

variable "rds_apply" {
  default = true
  type = bool
}

resource "aws_db_instance" "default" {
  allocated_storage          = 10
  engine                     = "oracle-se2"
  engine_version             = "12.1.0.2.v13"
  instance_class             = "db.t3.micro"
  identifier                 = "test-rds-license"
  name                       = "MYDB"
  username                   = "foo"
  password                   = "foobarbaz"
  skip_final_snapshot        = true
  license_model              = var.rds_license
  apply_immediately          = var.rds_apply
  auto_minor_version_upgrade = false
}
```

### Expected Behavior

The RDS instance is created with the defined license model however after the instance is created changing the license model and applying changes does not make any changes to the RDS instance.  Terraform plan shows the license change and apply applies it but the end result is no change.  The apply_immediately option has no effect either, if true the change does not happen and if false there is no pending action created.

### Actual Behavior

Terraform should apply the change and wait for it to complete if apply_immediatly is true or should create a pending action if false.

### Steps to Reproduce

Using the source above

1. `terraform apply --auto-approve --var rds_license="license-included"` to create the rds with license-included
2. Query AWS RDS shows correct values  `aws rds describe-db-instances --db-instance-identifier test-rds-license --query 'DBInstances[0].{LicenseModel: LicenseModel, PendingModifiedValues: PendingModifiedValues}'` 
```json
{
    "LicenseModel": "license-included",
    "PendingModifiedValues": {
    }
}
```
3. Running a plan with a new license model shows the expected change `terraform plan -out plan --var rds_license="bring-your-own-license"`
```hcl
Terraform will perform the following actions:

  # aws_db_instance.default will be updated in-place
  ~ resource "aws_db_instance" "default" {
        ...
      ~ license_model                         = "license-included" -> "bring-your-own-license"
        ...
    }
```
4. Appling the plan takes less than a second, license change requires downtime so it should take longer
```
terraform apply plan
aws_db_instance.default: Modifying... [id=test-rds-license]
aws_db_instance.default: Modifications complete after 0s [id=test-rds-license]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
5. Query AWS RDS shows incorrect (original) values  `aws rds describe-db-instances --db-instance-identifier test-rds-license --query 'DBInstances[0].{LicenseModel: LicenseModel, PendingModifiedValues: PendingModifiedValues}'` 
```json
{
    "LicenseModel": "license-included",
    "PendingModifiedValues": {
    }
}
```
6. Running a plan again with the BYOL license model shows the same change needs to be made.

Repeating the process with rds_apply=false should create a pending action but this does nothing as well

**Comment by gchristidis** [comment]
Sorry for the push but any chance this could get looked at.
We have in excess of a 100 environments managed by Terraform with RDS Oracle instances using BYOL licensing.  The company is changing its Oracle licensing arrangements and us such we will have the need in the near future before our Oracle license changes to move all RDS instances to "license-included"

**Comment by DrFaust92** [comment]
its seems that while `license_model` does not require recreation but the attribute is not being passed to `ModifyDBInstance`
