### ISSUE TITLE
aws_cloudformation_stack_set with disabled auto_deployment fails validation

### ISSUE THREAD

**Issue by Steffen911** [hashicorp/terraform-provider-aws#19015]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
terraform -v                   
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/aws v3.37.0

Your version of Terraform is out of date! The latest version
is 0.15.0. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* aws_cloudformation_stack_set

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_cloudformation_stack_set" "aws_backup_init_stack" {
  name                    = "AWSBackupInit"
  permission_model = "SERVICE_MANAGED"
  capabilities = ["CAPABILITY_NAMED_IAM"]
  auto_deployment {
    enabled = false
    retain_stacks_on_account_removal = false
  }
  template_body = <<TEMPLATE
AWSTemplateFormatVersion: 2010-09-09
Resources:
  BackupVault:
    Type: AWS::Backup::BackupVault
    Properties:
      BackupVaultName: "My_Backup_Vault"
  BackupIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - backup.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: "IAM Role for cross-account Backups"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup
      RoleName: "BackupRole"
TEMPLATE
}
```

### Expected Behavior

A stack set with disabled autodeployment should be created.

### Actual Behavior

```
aws_cloudformation_stack_set.aws_backup_init_stack: Creating...

Error: error creating CloudFormation StackSet: ValidationError: Can only set RetainStacksOnAccountRemoval if AutoDeployment is enabled.
	status code: 400, request id: a117dca5-7139-40be-b946-846929669874

  on stackset.tf line 1, in resource "aws_cloudformation_stack_set" "aws_backup_init_stack":
   1: resource "aws_cloudformation_stack_set" "aws_backup_init_stack" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Using 
```
aws cloudformation create-stack-set --stack-set-name AWSBackupInit \
               --template-body file://$(pwd)/deployment.yaml \
               --permission-model SERVICE_MANAGED \
               --capabilities CAPABILITY_NAMED_IAM \
               --auto-deployment Enabled=false
```
on the CLI behaves as expected.
```
aws cloudformation create-stack-set --stack-set-name AWSBackupInit \
               --template-body file://$(pwd)/deployment.yaml \
               --permission-model SERVICE_MANAGED \
               --capabilities CAPABILITY_NAMED_IAM \
               --auto-deployment Enabled=false,RetainStacksOnAccountRemoval=false
```
fails with the error above. Hence I assume that terraform always passes the `RetainStacksOnAccountRemoval ` flag even when it's null. I guess omitting the flag from the API request if enabled is false would resolve this issue.

**Comment by Junkern** [comment]
Just to add to this issue: We would need to modify this line of code:

https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_cloudformation_stack_set.go#L385

to be only set (whether it be `true` or `false`) in case `Enabled: true`

**Comment by wmartins** [comment]
I've been affected by this one today.

It looks like the issue and the PR haven been sitting around for a while. @Steffen911 did you get around this some way?

**Comment by Steffen911** [comment]
@wmartins In the end, we used the CLI to create the stack set.

**Comment by dbagan** [comment]
Confirming this is till an issue. I it it myself today.
