### ISSUE TITLE
Using aws_dms_replication_task without replication_task_settings being provided

### ISSUE THREAD

**Issue by dealweb723** [hashicorp/terraform-provider-aws#19021]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

* terraform 13.6
* hashicorp/aws 3.36

### Affected Resource(s)

* aws_dms_replication_task

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_dms_replication_task" "dms_rep_task" {
  migration_type            = "full-load-and-cdc"
  replication_instance_arn  = [remove for security reasons]
  replication_task_id       = "my-dms-task-id"
  source_endpoint_arn       = [remove for security reasons]
  table_mappings            = "{\"rules\":[{\"rule-type\":\"selection\",\"rule-id\":\"1\",\"rule-name\":\"1\",\"object-locator\":{\"schema-name\":\"%\",\"table-name\":\"%\"},\"rule-action\":\"include\"}]}"

  target_endpoint_arn       = [remove for security reasons]
}
```

### Expected Behavior

Expected tf apply to be able to run multiple times without issue

### Actual Behavior

* Running aws_dms_replication_task but without providing replication_task_settings as that is an optional setting per the doc (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_replication_task#replication_task_settings)
* Everything is created just fine after the first apply
* Run the same tf code again and still without the optional replication_task_settings and it fails.  In looking at tf plan it shows that replication_task_settings is there and it plans to remove it.  The tf apply fails with "Error: InvalidParameterCombinationException: No modifications were requested on the task"
* The work around is to add some dummy json to aws_dms_replication_task in the initial build and keep that in any builds onwards.

### Steps to Reproduce

1. Run terraform apply
2. Rerun terraform apply

### References

* #1513 https://github.com/hashicorp/terraform-provider-aws/issues/1513
* #9200 https://github.com/hashicorp/terraform-provider-aws/issues/9200

**Comment by Sebor** [comment]
I've faced with the same issue.
it is necessary to use
```
  lifecycle {
    ignore_changes = [replication_task_settings]
  }
```
as dirty workaround
