### ISSUE TITLE
Cant manage wafv2 log filtering through terraform

### ISSUE THREAD

**Issue by paullemon** [hashicorp/terraform-provider-aws#19048]
I dont see a way to use Terraform to manage wafv2 log filtering.  Assume this could be used in the "wafv2_web_acl_logging_configuration" resource block.

https://docs.aws.amazon.com/cli/latest/reference/wafv2/put-logging-configuration.html
(From the url)
``` 
 "LoggingFilter": {
    "Filters": [
      {
        "Behavior": "KEEP"|"DROP",
        "Requirement": "MEETS_ALL"|"MEETS_ANY",
        "Conditions": [
          {
            "ActionCondition": {
              "Action": "ALLOW"|"BLOCK"|"COUNT"
            },
            "LabelNameCondition": {
              "LabelName": "string"
            }
          }
          ...
        ]
      }
```

From the AWS GUI:
- Navigate to the WAFv2 console
- Select the webacl
- Click "Logging and Metrics" tab
- Click either "Enable logging" or "Edit logging" whichever is relevant.
- Under "Filter logs" section click "Add filter"

**Comment by anGie44** [comment]
HI @paullemon, thank you for raising this issue. A similar request has been made in https://github.com/hashicorp/terraform-provider-aws/issues/18665, so I'm going to close this one as a duplicate but please refer to the existing issue to track it's progress/future release 😄
