### ISSUE TITLE
Add launchTemplateConfigurations section to aws_imagebuilder_distribution_configuration

### ISSUE THREAD

**Issue by gregnphe** [hashicorp/terraform-provider-aws#19046]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The UI and [docs](https://docs.aws.amazon.com/imagebuilder/latest/userguide/dist-using-launch-template.html) refer to `launchTemplateConfigurations` but this is not available in aws_imagebuilder_distribution_configuration resources. The setDefaultVersion attribute would be super useful.

### New or Affected Resource(s)

* aws_imagebuilder_distribution_configuration

### Potential Terraform Configuration
```hcl
resource "aws_imagebuilder_distribution_configuration" "example" {
  name = "example"

  distribution {
    ami_distribution_configuration {
      ami_tags = {
        CostCenter = "IT"
      }

      name = "example-{{ imagebuilder:buildDate }}"

      launch_permission {
        user_ids = ["123456789012"]
      }

    launchTemplateConfiguration {
                    launchTemplateId = "lt-0a1bcde2fgh34567"
                    accountId =  "935302948087"
                    setDefaultVersion =  true
    }
    launchTemplateConfiguration {
                    launchTemplateId = "lt-0aaa1bcde2ff3456" # only this field is required
    }

    region = "us-east-1"
  }
}

```

### References
* https://docs.aws.amazon.com/imagebuilder/latest/userguide/dist-using-launch-template.html

**Comment by rmccarthy-ellevation** [comment]
Can we have an update on this?
