### ISSUE TITLE
Better error message when create a s3 bucket which already exits

### ISSUE THREAD

**Issue by tkumark** [hashicorp/terraform-provider-aws#19043]
When create s3 if the bucket already exits by some one else, there should be a better message like "Bucket with the same name already exists". current messaage is miss leading

Error: Error creating S3 bucket: AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'

```
resource "aws_s3_bucket" "prod_terraform_state" {
  bucket = "mybucketname"
  # Enable versioning so we can see the full revision history of our
  # state files
  versioning {
    enabled = true
  }
  # Enable server-side encryption by default
  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }
}
```

**Comment by ewbankkit** [comment]
@tkumark Thanks for raising this issue.
It has already been noticed in #13587. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
