### ISSUE TITLE
lakeformation_permissions: Throws "no permissions found" error if no permissions_with_grant_options property is used

### ISSUE THREAD

**Issue by MitchellGerdisch** [hashicorp/terraform-provider-aws#19064]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_lakeformation_permissions

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_version = ">= 0.14.0"
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_lakeformation_permissions" "add-pii-clientstest-tf" {
  principal   = "arn:aws:iam::xxxxxxxxx:role/xxxxxxxx"
  permissions = ["SELECT"]

  table_with_columns {
    database_name = "mydb"
    name = "mytable"
    column_names =  ["mycolumn"]
  }
}
```

### Expected Behavior

As per the documentation, the `permissions_with_grant_option` is optional (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lakeformation_permissions#permissions_with_grant_option)
And creating resource without that option should work as expected.

### Actual Behavior

Without that option a few things happen:
1.  This error is given: `│ Error: error reading Lake Formation permissions: no permissions found`
2. But the resource is created as seen in the AWS console, for example.
3. Any attempt to modify, refresh or destroy the resource continues to throw the error.
4. Thus, manual deletion of the permission in AWS is required and 
5. The state file needs to be modified to get things back to a sane state.

### Steps to Reproduce

1. Create an Athena db/table
3. Create a role.
4. Create a lakeformation permission resource for the role on the Athena table as per the code above.
5. terraform apply and see the error.
6. Note that even though an error is thrown,  the permission was created in AWS console. 
7. Try any other terraform command (e.g. apply, destroy, refresh) and get the error (with or without untainting).

### References

* #0000

**Comment by YakDriver** [comment]
Related #16848
Related #17633
Related #18374
Related #18446
Related #18505
Related #19063
Related #19064
