### ISSUE TITLE
Snowball Edge EC2 Deploy Fails -- Func resourceAwsInstanceRead Error

### ISSUE THREAD

**Issue by bjsheppa** [hashicorp/terraform-provider-aws#19068]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.15.0 on darwin_amd64

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Due to the nature of my project, I may not be able to post this information. Checking with team and will post if I receive approval.

### Panic Output

Due to the nature of my project, I may not be able to post this information. Checking with team and will post if I receive approval. Can post this little snippet for now...

https://gist.github.com/bjsheppa/ec2b0ccc6879ed57a710a3cad86454d7

### Expected Behavior

Upon running the Terraform apply cli command on aws_instance code against a Snowball Edge custom EC2 endpoint, an EC2 instance should be deployed to the Snowball Edge and instance metadata should be reflected in Terraform state. The command should finish successfully.

### Actual Behavior

Upon running the Terraform apply cli command on aws_instance code against a Snowball Edge custom EC2 endpoint, an EC2 instance is deployed to the Snowball Edge but the instance metadata in not reflected in Terraform state. The command errors out with a resourceAwsInstanceRead function error.

### Steps to Reproduce

1.	Set custom EC2 endpoint to deploy to Snowball Edge 
2.	Run `terraform apply` to deploy an aws_instance onto the Snowball Edge
3.	The ‘terraform apply’ command will throw the error described in this issue.

### References

NA

**Comment by ewbankkit** [comment]
@bjsheppa Thanks for raising this issue.
Could you include just one more line in the crashlog gist so that we can see the source line number for the crash.

**Comment by bjsheppa** [comment]
@ewbankkit Thank you for the quick reply! Yes sir I can do, one minute please.

**Comment by bjsheppa** [comment]
@ewbankkit please check when you get time and let me know if that is what you are looking for. Thank you!

**Comment by ewbankkit** [comment]
Relevant code:

https://github.com/hashicorp/terraform-provider-aws/blob/bf230a0d3debf5f769b7a238f7af451f34a320db/aws/resource_aws_instance.go#L779-L784

`instance.Placement` is `nil`.

**Comment by bjsheppa** [comment]
https://docs.aws.amazon.com/snowball/latest/developer-guide/edge-compute-instance-metadata.html

This link may be helpful. I have a feeling this issue has to do with metadata supported on Snowball Edge EC2 service.

**Comment by bjsheppa** [comment]
And guess I did not make this clear but I am open to assisting in resolving this issue. I have access to a couple Snowball Edges and have the provider dev env configured. I am out today but will be back looking at this starting Monday. Cheers and happy weekend!

**Comment by SebTardif** [comment]
@ewbankkit There is no concept of placement group on Snowball Edge, it's detached from AWS/Internet, just like an expensive rental server. See the list of supported stuff: https://docs.aws.amazon.com/snowball/latest/developer-guide/using-ec2-endpoint.html

But without that knowledge, and with just static analysis, we can see the code is wrong. I think if Hashicorp had run the source code of this Terraform plug-in via PMD, a static analyzer, it may had detected the problem: https://github.com/pmd/pmd

Line 779 exists because Placement could be null, but line 782 assume Placement is never null.

**Comment by bjsheppa** [comment]
I believe I have figured out and resolved the first issue locally. There is an if statement that checks if instance.Placement is not equal to nil. That seems to fail fine because instance.Placement is equal to nil in the case of the SBE. 

The very next if statement is where the problem occurs. The if statement checks to see if instance.Placement.GroupName is equal to nil. This check bombs out with a nil dereference error, possible because instance.Placement does not exist.

There are several more consecutive if statements that check for the various children of instance.Placement.

To fix, I nested all the checks for the various children of instance.Placement inside of the very first if statement that just checks for instance.Placment which fails as expected. Therefore when this first check for the parent fails, the code will skip over the check for any children.

Quick code snippet here...

https://gist.github.com/bjsheppa/4764286d5d5fb97a0eb090e00169fdfb

BUT, after getting past this I hit another error I am currently looking into a bit more. Has to do with setting "disable_api_termination" in state I believe. More to come.

**Comment by bjsheppa** [comment]
https://gist.github.com/bjsheppa/4c547ab5366fc54b97ce9e3c0765af83

I cheated for now with a SBE only workaround but this does allow me to successfully plan, apply and destroy ec2s on SBE.

Still looking into a real fix to address this second issue.

**Comment by bjsheppa** [comment]
Believe I have a suitable fix in place for the second issue encountered. Getting a PR going for the fix.

**Comment by bjsheppa** [comment]
https://github.com/hashicorp/terraform-provider-aws/pull/19256

**Comment by dsmithbauer** [comment]
Bump. This issue has been open for over a year. I agree with the author and verified that their PR worked last year on a Snowball Edge device we had in house - https://github.com/hashicorp/terraform-provider-aws/pull/19256#issuecomment-854959860
Is there any intention of incorporating this fix (or a similar fix) soon? Snowball Edge devices have a subset of the AWS APIs and could greatly benefit from being able to have onboard/edge infrastructure provisioned via Terraform.
