### ISSUE TITLE
lakeformation_permissions doesn't delete/revoke permission on destroy.

### ISSUE THREAD

**Issue by MitchellGerdisch** [hashicorp/terraform-provider-aws#19063]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_lakeformation_permissions

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_version = ">= 0.14.0"
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_lakeformation_permissions" "add-pii-clientstest-tf" {
  principal   = "arn:aws:iam::xxxxxxxxx:role/xxxxxxxx"
  permissions = ["SELECT"]
  permissions_with_grant_option = ["SELECT"]

  table_with_columns {
    database_name = "mydb"
    name = "mytable"
    column_names =  ["mycolumn"]
  }
}
```

### Expected Behavior

Management of a lakeformation_permission resource should fully revoke the permission(s) on destroy.

### Actual Behavior

The permission remains.

### Steps to Reproduce

1. Create an Athena db/table
2. Create a role.
3. Create a lakeformation permission resource for the role on the Athena table as per the code above.
4. `terraform apply` and see that terraform indicates the permission was created 
5. Verify the permission was created in AWS console. Note that it has both the "Permission" and "Grantable Permission" setting.
6. `terraform destroy`and see that terraform indicates the permission was deleted.
7. Look at the AWS console and see that the permission still exists - although the "Grantable" has been removed.

### References

* #0000

**Comment by YakDriver** [comment]
Related #16848
Related #17633
Related #18374
Related #18446
Related #18505
Related #19063
Related #19064
