### ISSUE TITLE
aws_synthetics_canary cannot be capitals

### ISSUE THREAD

**Issue by brendan-sherrin** [hashicorp/terraform-provider-aws#19073]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.30
+ provider.archive v2.1.0
+ provider.aws v3.34.0
+ provider.local v2.1.0

### Affected Resource(s)

aws_cloudwatch_metric_alarm

### Debug Output

Error: invalid value for name (must contain only alphanumeric, hyphen, underscore.)

  on synthetics_canary\cloudwatch_canary.tf line 41, in resource "aws_synthetics_canary" "canary_api":
  41:   name                 = lookup(each.value, "friendly_name")

### Expected Behavior

Either of: 
1.  The canary should be created with upper case
2.  The error message should include that the canary name needs to be in lower case in addition to alphanumeric and either underscore or dash.

### Actual Behavior

I recieved an error message that didn't tell me what the actual problem was.

### Steps to Reproduce

1.  Try to create an aws_synthetics_canary with capital letters in the name field 
2.  Run a terraform apply

### References

The doco here just mentions the name needs to be unique, nothing about a requirment to be lower case only:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_metric_alarm

**Comment by gdavison** [comment]
Thanks for reporting this, @brendan-sherrin. The AWS documentation doesn't specify it, but the AWS Console says "A name consists of up to 21 lowercase letters, numbers, hyphens or underscores with no spaces." We will update the error message and the Terraform documentation.
