### ISSUE TITLE
`aws_instance` requires `subnet_id` if non-default VPC is used, even with `aws_network_interface_attachment` set

### ISSUE THREAD

**Issue by afmorris** [hashicorp/terraform-provider-aws#19089]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.32.0
```

### Affected Resource(s)

* aws_instance
* aws_network_interface
* aws_network_interface_attachment

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# There's nothing unique or interesting in the `aws_instance` resource, except
# that it DOES NOT have `subnet_id` or `vpc_security_group_ids` set.
# Additionally, there is no `network_interface` block defined.
resource "aws_instance" "this" {
  ami = var.ami_id
  instance_type = var.instance_type
  user_data = var.user_data

  root_block_device {
    ...
  }
}

# The ENI is being created in a subnet in the NON-DEFAULT VPC. This is important.
resource "aws_network_interface" "this" {
  subnet_id = var.subnet_id
  private_ips_count = var.private_ips_count
  security_groups = [var.security_group_id]
}

resource "aws_network_interface_attachment" "this" {
  device_index = 0
  instance_id = aws_instance.this.id
  network_interface_id = aws_network_interface.this.id
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

1. The ENI is created in the specified subnet
2. The EC2 instance is created in the subnet defined by the ENI, as it has that relationship defined by the `aws_network_interface_attachment`

### Actual Behavior

1. The ENI is created in the specified subnet
2. The apply fails with the following error:

```
Error: Error launching source instance: VPCIdNotSpecified: No default VPC for this user. GroupName is only supported for EC2-Classic and default VPC.
	status code: 400, request id: xxx
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

* It should be explicitly called out that this can be fixed by adding the `network_interface` block to the `aws_instance` resource, rather than using the explicit `aws_network_interface_attachment` resource. This basically removes the usefulness of using `aws_network_interface_attachment` in a non-default VPC scenario. I assume that some reference cannot be passed transitively, or something.

### References

N/A

**Comment by gdavison** [comment]
Hi @afmorris, thanks for submitting this.

When Terraform creates a resource, it only uses values configured on the resource itself. In addition, when resource B references values from another resource A, resource A must be created before B. Because of these two reasons, `aws_instance.this` is created before `aws_network_interface_attachment.this` and with no network configuration. The AWS API interprets no network configuration as being assigned to the default VPC.

`aws_network_interface_attachment` is primarily intended to attach additional network interfaces after the instance is initially created.

In your case, your best approach is to use the `network_interface` block to attach `aws_network_interface.this` at creation time.

**Comment by afmorris** [comment]
Thanks for the follow-up @gdavison! I figured that was the case, but wanted to make sure I wasn't missing anything.
