### ISSUE TITLE
Athena Read Permissions

### ISSUE THREAD

**Issue by splkforrest** [hashicorp/terraform-provider-aws#19085]
The current athena database implements a query on read. This means that the terraform plan needs
the permission to execute queries against athena as well as permission to write to the
s3 bucket where the execution results are stored. This makes it hard to run plan in an
environment where we don't want it to modify any aws resources. The StartQueryExecution
also does not have a way to restrict the queries. This means that it is possible to use
the permissions set up for a terraform plan to run any queries against athena.

PR for the fix here: https://github.com/hashicorp/terraform-provider-aws/pull/18141

**Comment by harsimranmaan** [comment]
Can we merge the MR for this?
