### ISSUE TITLE
Update documentation and logging and error messages for Macie (v1) to "Macie Classic" branding

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#19094]
### Description

AWS has rebranded version 1 of Macie as "Macie Classic" and the current v2 as "Macie". Documentation and logging and error messages in the provider should be updated to reflect this branding

### Affected Resources

* aws_macie_member_account_association
* aws_macie_s3_bucket_association

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/13441.

**Comment by jar-b** [comment]
Closed by #31058, merged to `main` via #31392
