### ISSUE TITLE
Amazon Redshift AZ Relocation

### ISSUE THREAD

**Issue by nriveraonica** [hashicorp/terraform-provider-aws#19098]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon Redshift, the most widely used data warehouse, now offers the ability to move an Amazon Redshift cluster to another AWS Availability Zone (AZ). 

### New or Affected Resource(s)

* aws_redshift_cluster

### Potential Terraform Configuration

```hcl
resource "aws_redshift_cluster" "default" {
 ...
 availability_zone_relocation = true|false
 ...
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-redshift-launches-ability-easily-move-clusters-between-aws-availability-zones/
* https://docs.aws.amazon.com/redshift/latest/mgmt/managing-cluster-recovery.html
* https://github.com/aws/aws-sdk-go/blob/5bc5b89e6457ad38c0d906681704ddb31e097f9e/models/apis/redshift/2012-12-01/docs-2.json#L2646
* https://github.com/aws/aws-sdk-go/blob/5bc5b89e6457ad38c0d906681704ddb31e097f9e/models/apis/redshift/2012-12-01/api-2.json#L2173

**Comment by peramnaveen29** [comment]
Any tentative release date for this?
