### ISSUE TITLE
Error modifying Redshift Cluster IAM Roles (cluster-role-s3-access): InvalidParameterValue

### ISSUE THREAD

**Issue by msafikeepersecurity** [hashicorp/terraform-provider-aws#19113]
Greetings,

I have a Redshift cluster which I am associating with an IAM Role that grants access to some S3 buckets.  Terraform provider for AWS is able to create the role and the cluster but is unable to associate the role with the cluster.  However, using the AWS CLI or AWS console I am able to attach the policy to the cluster.

Full error text:

Error: Error modifying Redshift Cluster IAM Roles (mycluster-role-s3-access): InvalidParameterValue: The IAM role mycluster-role-s3-access is not valid. The IAM role must delegate access to an Amazon Redshift account.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/aws v3.16.0

### Affected Resource(s)

* aws_redshift_cluster
* aws_iam_role

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output
Error: Error modifying Redshift Cluster IAM Roles (mycluster-role-s3-access): InvalidParameterValue: The IAM role mycluster-role-s3-access is not valid. The IAM role must delegate access to an Amazon Redshift account.
        status code: 400, request id: 765ae606-3891-4940-a6b9-9c8688fc6bcc

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by gdavison** [comment]
Hi @msafikeepersecurity, could you please include the Terraform configuration that causes this error? We don't have a way to reproduce the error you've reported without it.

**Comment by msafikeepersecurity** [comment]
I am unable to reproduce this issue. In an attempt to provide sample code and additional details, I found that the role attachment happens without any issues. Not sure what was causing it at the time, but since the workstation has been rebooted a few times since then, I tend to attribute it to local environment as the root cause of that issue.  Closing this issue.

**Comment by msafikeepersecurity** [comment]
Up on further testing I found that it was user error and not a bug.  I was erroneously using the role ID instead of ARN, but the error returned was misleading - "The IAM role mycluster-role-s3-access is not valid.".

It would be helpful for the error to say "Role not found" or something to that effect.
