### ISSUE TITLE
AWS WAFv2 doesn't support Scope-down statement for managed_rule_group_statements

### ISSUE THREAD

**Issue by brandonpalmer** [hashicorp/terraform-provider-aws#19125]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.14.7 / 0.15.1

### Affected Resource(s)

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl
For Managed Rules,  the Scope-Down is not supported in Terraform.  It IS supported in the AWS CLI / AWS SDK

This does work for other rule types (like rate_based_statement statement rules)

### Terraform Configuration Files

```hcl
resource "aws_wafv2_web_acl" "default_alb_rules" {
  name        = "default_alb_waf"
  description = "Default ALB WAF Rules"
  scope       = "REGIONAL"

  default_action {
    allow {}
  }

 rule {
    name     = "AWS-AWSManagedRulesAmazonIpReputationList"
    priority = 1

    override_action {
      count {}
    }
    statement {
      managed_rule_group_statement {
        name        = "AWSManagedRulesAmazonIpReputationList"
        vendor_name = "AWS"

        scope_down_statement {
          geo_match_statement {
            country_codes = ["US", "NL"]
          }
        }
      }
    }
    visibility_config {
      cloudwatch_metrics_enabled = true
      metric_name                = "AWS-AWSManagedRulesBotControlRuleSet"
      sampled_requests_enabled   = true
    }
  }
  visibility_config {
    cloudwatch_metrics_enabled = false
    metric_name                = "default_alb_waf"
    sampled_requests_enabled   = false
  }
}
```

### Debug Output

https://gist.github.com/brandonpalmer/6ac46bc9c028fdca6faee038e67aaf56

### Expected Behavior

Scope-down should have been applied to rule. 

Throws error

1. `terraform apply`

### References

* #0000

**Comment by rajholla** [comment]
There is open PR to address this:  https://github.com/hashicorp/terraform-provider-aws/pull/19407
