### ISSUE TITLE
Add Trusted Devices config to aws_workspaces_directory 

### ISSUE THREAD

**Issue by emulanob** [hashicorp/terraform-provider-aws#19123]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Along the lines of https://github.com/hashicorp/terraform-provider-aws/issues/12866, can we please have support to the Trusted Devices part of that config, i.e. enabling the two "Only Allow Trusted Devices..." options and import up to 2 base64-encoded root certificates.

### New or Affected Resource(s)

* aws_workspaces_directory

### Potential Terraform Configuration

The new arguments of the `workspace_access_properties` block would resemble the following:
```hcl
resource "aws_workspaces_directory" "example" {
 # ...
  workspace_access_properties {
    allow_windows_trusted_devices_only = true
    allow_osx_trusted_devices_only     = true
    trusted_devices_root_cert_1        = filebase64("path/to/git-ignored-cert.pem")
    trusted_devices_root_cert_1        = filebase64("path/to/another-git-ignored-cert.pem"))
    # ...
  }
  # ...
}

```

Thank you. Regards,
Kdu.

**Comment by gdavison** [comment]
Thank you for the suggestion, @emulanob. It doesn't appear that the AWS API supports registering the certificates, and you have to use the AWS Console to do that step. However, the fields `device_type_osx` and `device_type_windows` in `workspace_access_properties` do support the value `TRUST` in addition to `ALLOW` and `DENY` like the other fields. We can make that change.

**Comment by emulanob** [comment]
Great, @gdavison! Thank you.

**Comment by emulanob** [comment]
If you could please point me to that resource in the code, I might try submitting a PR myself. :D
