### ISSUE TITLE
data sources trigger unnecessary replacement

### ISSUE THREAD

**Issue by arneckx** [hashicorp/terraform-provider-aws#19136]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

2021-04-28T10:42:20.212+0200 [INFO]  Terraform version: 0.15.1
2021-04-28T10:42:20.212+0200 [INFO]  Go runtime version: go1.16.2
2021-04-28T10:42:20.212+0200 [INFO]  CLI args: []string{"/usr/local/bin/terraform", "-v"}
2021-04-28T10:42:20.214+0200 [INFO]  CLI command args: []string{"version", "-v"}
Terraform v0.15.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.22.0
+ provider registry.terraform.io/hashicorp/null v3.1.0

### Affected Resource(s)

* aws_api_gateway_rest_api
* aws_api_gateway_resource

### Terraform Configuration Files

```terraform
data "aws_api_gateway_rest_api" "mobile-api-gateway" {
  name = var.gateway_name
}

data "aws_api_gateway_resource" "path_resource" {
  path = var.api_gateway_path
  rest_api_id = local.rest_api_id
}

locals {
  rest_api_id = data.aws_api_gateway_rest_api.mobile-api-gateway.id
  path_id = data.aws_api_gateway_resource.path_resource.id
}

resource "aws_api_gateway_method" "this" {
  rest_api_id = local.rest_api_id
  resource_id = local.path_id
  http_method = var.http_method
  authorization = "NONE"

  request_parameters = var.request_parameters
}

resource "aws_api_gateway_integration" "this" {
  rest_api_id = local.rest_api_id
  resource_id = local.path_id
  http_method = var.http_method
  integration_http_method = var.integration_http_method
  type = var.type
  uri = var.uri
  timeout_milliseconds = var.gateway_integration_timeout

  request_parameters = var.integration_request_parameters

  depends_on = [
    aws_api_gateway_method.this
  ]
}
```

### Expected Behavior

resource_id + rest_api_id are not changing so aws_api_gateway_integration + aws_api_gateway_method should not be replaced.

### Actual Behavior

```
# module.events_post_actions.module.api_gateway_integration.aws_api_gateway_integration.this must be replaced
+/- resource "aws_api_gateway_integration" "this" {
      - cache_key_parameters    = [] -> null
      ~ cache_namespace         = "z02bdb" -> (known after apply)
      ~ id                      = "agi-1xq92wzm61-z02bdb-POST" -> (known after apply)
      ~ passthrough_behavior    = "WHEN_NO_MATCH" -> (known after apply)
      - request_parameters      = {} -> null
      - request_templates       = {} -> null
      ~ resource_id             = "z07bdb" -> (known after apply) # forces replacement
      ~ rest_api_id             = "1xq93wzm61" -> (known after apply) # forces replacement
        # (6 unchanged attributes hidden)
    }

  # module.events_post_actions.module.api_gateway_integration.aws_api_gateway_method.this must be replaced
+/- resource "aws_api_gateway_method" "this" {
      - authorization_scopes = [] -> null
      ~ id                   = "agm-1xq92wzm61-z02bdb-POST" -> (known after apply)
      - request_models       = {} -> null
      - request_parameters   = {} -> null
      ~ resource_id          = "z07bdb" -> (known after apply) # forces replacement
      ~ rest_api_id          = "1xq93wzm61" -> (known after apply) # forces replacement
        # (3 unchanged attributes hidden)
    }
```

terraform forces a replacement which results in a aws error: 'Error: Error creating API Gateway Method: ConflictException: Method already exists for this resource'

### Steps to Reproduce

1. use data source to get rest_api_id + resource_id
2. `terraform apply`

**Comment by gdavison** [comment]
Thanks for submitting the issue, @arneckx. Can you supply the values for the variables and also include the `DEBUG` log from when you run `terraform apply` in a Gist? Instructions for enabling `DEBUG` logging can be found at https://www.terraform.io/docs/internals/debugging.html

**Comment by breathingdust** [comment]
Closing due to lack of response
