### ISSUE TITLE
Error: Inconsistent final plan in aws_route_table 

### ISSUE THREAD

**Issue by matt-slalom** [hashicorp/terraform-provider-aws#19133]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/aws v3.37.0

### Affected Resource(s)

* aws_route_table

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

Gist with the code to reproduce the error: https://gist.github.com/matt-slalom/c09df4db8147cc394da27a1a4c0a7e82

### Debug Output

Gist for debug output: https://gist.github.com/matt-slalom/6c6901a9b9ffaab1485ddacde9c33341

### Actual Behavior

The first run results in an error. Running `apply` a second time successfully completes.
```
Error: Provider produced inconsistent final plan

When expanding the plan for
aws_route_table.the_private_route_table["vpc1-private-1B"] to include new
values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.route: was known, but now unknown.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Steps to Reproduce

1. `terraform apply` to the code in the gist: https://gist.github.com/matt-slalom/c09df4db8147cc394da27a1a4c0a7e82

### Important Factoids

None

### References
None

**Comment by matt-slalom** [comment]
This is 100% reproducible, and since the output says it's an error, I'm reporting it. If this is due to something I'm doing wrong, please let me know!

**Comment by ewbankkit** [comment]
@matt-slalom Thanks for raising this issue.
I can reproduce in our test environment using your provided configuration.

**Comment by ewbankkit** [comment]
May be related to calling `d.Set("route")` in `resourceAwsRouteTableUpdate()`:

https://github.com/hashicorp/terraform-provider-aws/blob/1a465255d69c8037d232846616b250c899b2fac8/aws/resource_aws_route_table.go#L408

https://github.com/hashicorp/terraform-provider-aws/blob/1a465255d69c8037d232846616b250c899b2fac8/aws/resource_aws_route_table.go#L502
