### ISSUE TITLE
Synthetics Canary Cleanup

### ISSUE THREAD

**Issue by bauteb-sci** [hashicorp/terraform-provider-aws#19141]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating an aws_synthetics_canary, it automatically creates a lambda function and lambda layer for the source code.  When you destroy the canary resource, those lambda resources are left behind.  Please enhance the removal process to also destroy those resources.

### New or Affected Resource(s)

* aws_synthetics_canary >>> aws_lambda_function & aws_lambda_layer_version

### Potential Terraform Configuration

```hcl
resource "aws_synthetics_canary" "canary-monitor" {
  name                 = var.canary_name
  handler              = "${var.handler_name}.handler"
  start_canary       = var.start_canary
  artifact_s3_location = var.artifact_s3_location
  execution_role_arn  = var.synthetics_exec_role
  runtime_version      = var.runtime_version
  s3_bucket          = var.synthetics_bucket_name
  s3_key               = aws_s3_bucket_object.canary-source-zip.key
  s3_version         = aws_s3_bucket_object.canary-source-zip.version_id
  schedule {
    expression = var.schedule_expression
  }
  run_config {
    timeout_in_seconds = var.run_timeout
  }
}
```
Thanks!

* #0000

**Comment by gdavison** [comment]
Thanks, @bauteb-sci, this would be very useful for a lot of users. When developing the AWS provider, we follow the AWS API fairly closely, and the API doesn't provide specific calls to clean up after a Canary after it's deleted. The AWS documentation advises users to manually clean up after deleting a Canary https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/synthetics_canaries_deletion.html

One potential workaround to this is to use [`terraform import`](https://www.terraform.io/docs/cli/import/index.html) to bring the extra resources under Terraform management after AWS has created them.
