### ISSUE TITLE
Warning during init for Terraform versions 0.12.1 - 0.12.30: "This version of Terraform has an outdated GPG key and is unable to verify new provider releases."

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#19158]
As part of HashiCorp's response to [HCSEC-2021-12](https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512), the Terraform Registry is returning a warning message to Terraform Clients version 0.12.1 - 0.12.30:

```
Warning: registry.terraform.io: This version of Terraform has an outdated GPG key and is unable to
verify new provider releases. Please upgrade Terraform to at least 0.12.31 to receive new provider
updates. For details see:
https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512
```

This message means that the Registry is omitting provider versions signed by the new GPG key, and your Terraform client will install the last version of each provider that it can successfully verify. 

Detailed information about the Terraform implications of the GPG key rotation can be found here: https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570 

Upgrading to the latest maintenance release for your major Terraform version (0.12.31, 0.13.7, 0.14.11, 0.15.1) will remove this message.

**Comment by mikeobr** [comment]
Just to clarify for 0.12.1 - 0.12.30, using an unpinned version of the aws provider will pull the last known version signed by the previous GPG key?

Does the impact `Terraform may fail GPG checks with errors as new providers are released.` not apply to the aws provider?
