### ISSUE TITLE
aws_glue_crawler: name reported as invalid against regex when AWS accepts the name

### ISSUE THREAD

**Issue by SeanKilleen** [hashicorp/terraform-provider-aws#19159]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

* Terraform v0.15.0
* on windows_amd64
* provider registry.terraform.io/hashicorp/aws v3.35.0

### Affected Resource(s)

* aws_glue_crawler

### Terraform Configuration Files

This has to do with the import process and the act of _not_ writing some HCL, so I won't include the HCL here, but am happy to paste what's relevant with a little guidance.

### Steps to reproduce

* Create a crawler manually within AWS with a name that contains `/` characters, e.g. `Crawler-business-solutions-data/s3path/contact/rawdata/`
* Create HCL with the intent of importing the resource and working backward, e.g. 

```hcl
resource "aws_glue_crawler" "raw_data_crawler" {
  database_name = aws_glue_catalog_database.aws_glue_catalog_database.name
  name          = "Crawler-business-solutions-data/s3path/contact/rawdata/"
  role = "TBD"
}
```

NOTE: the import will complete successfully

* Run `terraform plan` with the appropriate variables

### Expected Behavior

Expect to see the drift between our defined configuration and the current resource's state so that I can work backward.

### Actual Behavior

I see an error: 

> expected value of name to match regular expression "[a-zA-Z0-9-_$#]+$", got Crawler-business-solutions-data/s3path/contact/rawdata/

### Important Factoids

* I am still new enough to AWS and Terraform that I very much accept this may be an issue of my understanding rather than a bug. If this is a question of my mistaken understanding, I am happy to bring my inquiry to the forum for more general resolution.
* It appears that AWS has possibly relaxed its rules around names and the terraform provider may need to follow suit.

**Comment by DrFaust92** [comment]
I cant find exact AWS docs that prompted to use this regex but its a bug.

**Comment by SeanKilleen** [comment]
Thanks for the confirmation @DrFaust92! I've got #19160 which should fix this particular instance, and I'd be happy to do a more holistic sweep for this regex occurrence and update it where applicable.
