### ISSUE TITLE
aws_glue_catalog_table: unprovided optional `parameter` section results in suggested change rather than no-op

### ISSUE THREAD

**Issue by SeanKilleen** [hashicorp/terraform-provider-aws#19157]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

* Terraform v0.15.0
* on windows_amd64
* provider registry.terraform.io/hashicorp/aws v3.35.0
* ~~provider registry.terraform.io/hashicorp/null v3.1.0~~ (nevermind this, we're using locals instead now.)

### Affected Resource(s)

* aws_glue_catalog_table

### Terraform Configuration Files

This has to do with the import process and the act of _not_ writing some HCL, so I won't include the HCL here, but am happy to paste what's relevant with a little guidance.

### Steps to reproduce

* Manually Create an AWS Glue Catalog table within an AWS Glue database. 
* Create a terraform file that maps to the appropriate structure, with the exception of `parameters`, as these seem to be set by the resource itself, e.g. `objectCount`. 
* Import the existing resource into our terraform.
* Run `terraform plan` with appropriate arguments.

### Expected Behavior

I'd expect terraform to suggest no changes to the parameters, as I have not specified a parameters section in my configuration

### Actual Behavior

Terraform suggests setting the various parameters (`classification`, `sizeKey`, `typeOfData`, `averageRecordSize` etc.) from their existing values to "null". 

### Important Factoids

* I am still new enough to AWS and Terraform that I very much accept this may be an issue of my understanding rather than a bug. If this is a question of my mistaken understanding, I am happy to bring my inquiry to the forum for more general resolution.
* It is 100% possible that I am making an assumption about `terraform import` here. Did `terraform import` bring in the `parameters` collection and that is why it's assuming we'd be setting them? If so, is there a way to remove the parameters collection from the imported resource so that this difference will not be taken into account?

**Comment by DrFaust92** [comment]
Hi @SeanKilleen, i cant say for certain but when creating this resource manually the above mentioned attributes may be implicitly added. import reads the all of the resource metadata as it is returned from the API. the provider doesnt add/alter the above mentioned attributes by default.

**Comment by jeremyolliver** [comment]
I've definitely seen this behaviour without issue in other AWS resources, where these are ignored on their own, but sometimes show up in a plan diff when other parameters are changing.

There is a specific issue relating to `aws_glue_catalog_table` where this does cause an issue though because only `schema_reference` OR `columns` can be specified - it's invalid to specify both. If I specify `schema_reference`, any future updates to the resource pulls back an implicit value for columns, so that updates *attempts* to set both values, even though only 1 is explicitly set in my tf files. This appears fine in the plan phase, but in the apply phase you'll see:

```
aws_glue_catalog_table.my_table: Modifying... [id=<AWS-ACCOUNT-ID>:<database-name>:<table-name>]

Error: Error updating Glue Catalog Table: InvalidInputException: Both SchemaReference and Columns are populated, only one of them should be populated.
```

This issue is causing any modifications to the table to require me to taint the resource, causing it to destroy and re-create.

**Comment by SeanKilleen** [comment]
I think @DrFaust92 gets it right here. I wasn't understanding the import process correctly in this case.

In this case, I destroyed and recreated the resource and all was well.

Thanks for the help!
