### ISSUE TITLE
aws_dms_endpoint engine_name not validated correctly

### ISSUE THREAD

**Issue by phumberdroz** [hashicorp/terraform-provider-aws#19150]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_dms_endpoint

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_dms_endpoint" "target" {
  endpoint_id                 = 
  endpoint_type               = "target"
  engine_name                 = "aurora-serverless"
  extra_connection_attributes = ""
  server_name                 = 
  username                    = 
  password                    = 
  port                        = 
}
```
### Expected Behavior

engine_name aurora-serverless is setable via the console but not in the resource

### Actual Behavior

got an error that the value is not valid

### Steps to Reproduce

try to create the said resource.

**Comment by phumberdroz** [comment]
Seems like this list is not correct: 
https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_dms_endpoint.go#L110-L128

aws dms describe-endpoint-types --output table

**Comment by cloudbow** [comment]
Was able to import the resource via terraform import but cannot apply it back as the plan shows that the engine is not supported. Please fix this hashicorp. We are unable to proceed with dms because of this.
