### ISSUE TITLE
tests/r/docdb_cluster: docdb3.6 no longer valid

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#19161]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`default.docdb3.6` is no longer a valid version and needs to be upgraded to `default.docdb4.0`.

### New or Affected Resource(s)

* aws_docdb_cluster

### Potential Terraform Configuration

```terraform
resource "aws_docdb_cluster" "default" {
  cluster_identifier = "tf-docdb-cluster-1111"

  availability_zones = [
    data.aws_availability_zones.available.names[0],
    data.aws_availability_zones.available.names[1],
    data.aws_availability_zones.available.names[2]
  ]

  master_username                 = "foo"
  master_password                 = "mustbeeightcharaters"
  db_cluster_parameter_group_name = "default.docdb4.0"
  final_snapshot_identifier       = "tf-acctest-docdbcluster-snapshot-1111"

  tags = {
    Environment = "production"
  }
}
```

### References

* #0000

**Comment by DrFaust92** [comment]
This has been addressed
