### ISSUE TITLE
service_role is required in aws_batch_compute_environment but optional in AWS.Batch.CreateComputeEnvironment

### ISSUE THREAD

**Issue by alex-bolenok-centralreach** [hashicorp/terraform-provider-aws#19178]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.15.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.38.0
```

### Affected Resource(s)

* aws_batch_compute_environment 

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_batch_compute_environment" "environment_bug_test" {
  compute_environment_name = "environment-bug-test"

  compute_resources {
    type               = "FARGATE"
    min_vcpus          = 0
    max_vcpus          = 1
    subnets            = var.subnets
    security_group_ids = var.security_group_ids
  }

  # service_role = ""
  # ^^ should be optional
  type = "MANAGED"
}

```

### Expected Behavior

Environment created with the default service role:

https://docs.aws.amazon.com/batch/latest/APIReference/API_CreateComputeEnvironment.html#Batch-CreateComputeEnvironment-request-serviceRole

> The full Amazon Resource Name (ARN) of the IAM role that allows AWS Batch to make calls to other AWS services on your behalf. For more information, see AWS Batch service IAM role in the AWS Batch User Guide.
> 
> Important
> If your account has already created the AWS Batch service-linked role, that role is used by default for your compute environment unless you specify a role here. If the AWS Batch service-linked role does not exist in your account, and no role is specified here, the service will try to create the AWS Batch service-linked role in your account.
> 
> If your specified role has a path other than /, then you must specify either the full role ARN (recommended) or prefix the role name with the path. For example, if a role with the name bar has a path of /foo/ then you would specify /foo/bar as the role name. For more information, see Friendly names and paths in the IAM User Guide.
> 
> Note
> Depending on how you created your AWS Batch service role, its ARN might contain the service-role path prefix. When you only specify the name of the service role, AWS Batch assumes that your ARN doesn't use the service-role path prefix. Because of this, we recommend that you specify the full ARN of your service role when you create compute environments.
> 
> Type: String
> 
> Required: No

### Actual Behavior

```
╷
│ Error: Missing required argument
│
│   on batch.tf line 1, in resource "aws_batch_compute_environment" "environment_bug_test":
│    1: resource "aws_batch_compute_environment" "environment_bug_test" {
│
│ The argument "service_role" is required, but no definition was found.
╵
```

### Steps to Reproduce

1. `terraform apply`

### References

Relates: #16819.

**Comment by ewbankkit** [comment]
@alex-bolenok-centralreach Thanks for raising this issue.
Is this breaking an existing Terraform configuration?

**Comment by alex-bolenok-centralreach** [comment]
We have a workaround of specifying an empty `service_role` if that's what
you're asking.

пт, 30 апр. 2021 г., 12:38 Kit Ewbank ***@***.***>:
