### ISSUE TITLE
aws_security_group_rule "self": conflicts with cidr_blocks

### ISSUE THREAD

**Issue by evandam** [hashicorp/terraform-provider-aws#19179]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/aws v3.38.0
```

### Affected Resource(s)

* aws_security_group_rule

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_security_group_rule" "example" {
  type              = "ingress"
  from_port         = 8000
  to_port           = 8000
  protocol          = "tcp"
  self              = false
  security_group_id = aws_security_group.example.id
  cidr_blocks       = ["10.10.0.0/16"]
}
```

### Expected Behavior

Create security group rule as it worked in previous provider versions.

### Actual Behavior

```
Error: ConflictsWith

  on example.tf line 75, in resource "aws_security_group_rule" "example":
  75:   cidr_blocks       = ["10.10.0.0/16"]

"cidr_blocks": conflicts with self
```

### Important Factoids

This started occurring after upgrading from the AWS provider 3.36.0 -> 3.38.0. These attributes should not conflict if `self = false`.

**Comment by dec5e** [comment]
The change was introduced in https://github.com/hashicorp/terraform-provider-aws/pull/18467
