### ISSUE TITLE
Better interaction between provider default_tags and aws_instance volume_tags

### ISSUE THREAD

**Issue by acdha** [hashicorp/terraform-provider-aws#19188]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

3.38.0 introduced the very handy provider-level `default_tags` which avoids a lot of tedious boilerplate. While migrating a large project, I noticed that EBS resources created by `aws_instance` do not use `default_tags`.

Obviously this could be resolved by changing `volume_tags` to inherit the `default_tags` values but I put this in as a feature request because it seems like a more generally useful situation would be making the provider's `default_tags` queryable in some way so it could be used for every resource type which has the concept of tags separate from the standard `tags` attribute — I'm pretty sure the same situation will arise with AWS Backup, for example — and it would be handy if you could reference the provider's configuration in something like `merge(provider.aws.default_tags, var.extra_tags)`.

### New or Affected Resource(s)

* aws_instance

### Potential Terraform Configuration

```hcl
aws_instance {
  volume_tags = merge(provider.aws.default_tags, var.extra_tags)
}
```

### References

* #7926

**Comment by devopsrick** [comment]
I would argue that volume_tags should definitely inherit default_tags, if the idea behind default_tags is to replace the general use of tags on resources (except for overrides).  Otherwise root ebs volumes of ec2 instances will not get tagged, while separate ebs volume will, and everything else.

**Comment by jtdoepke** [comment]
It should be documented that `default_tags` does not currently apply to `aws_instance` volume tags (and any resources with the same arguments like `aws_spot_instance_request`).

This note from the `aws_instance` documentation makes me think implementing `default_tags` here could be tricky:

> NOTE:
> 
> Do not use `volume_tags` if you plan to manage block device tags outside the `aws_instance` configuration, such as using `tags` in an `aws_ebs_volume` resource attached via `aws_volume_attachment`. Doing so will result in resource cycling and inconsistent behavior.

**Comment by wedneyyuri** [comment]
Potential workaround where the provider is not available:

```terraform
data "aws_default_tags" "example" {}
aws_instance {
  volume_tags = merge(aws_default_tags.example.default_tags, var.extra_tags)
}
```
