### ISSUE TITLE
Crashing when creating an aws_cloudwatch_log_group

### ISSUE THREAD

**Issue by reubendevries** [hashicorp/terraform-provider-aws#19189]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform version: 0.15.1
Go runtime version: go1.16.2

provider "registry.terraform.io/hashicorp/aws"
version = "3.38.0"

### Affected Resource(s)

* aws_cloudwatch_log_group

### Terraform Configuration Files

https://gist.github.com/reubendevries/826dcf1aaa43fb26f43ce9a8fec19244

### Debug Output

https://gist.github.com/reubendevries/a5f9761a30b9f0670802b8d7ae8fd3d8

### Panic Output

https://gist.github.com/reubendevries/ec048800367e69f010f70103d5716250

### Expected Behavior

It should have allowed me to plan or our create an AWS Cloudwatch Log Group

### Actual Behavior

Terraform crashed

### Steps to Reproduce

1. Create a terraform module to build a new aws cloudwatch log group, 
2. Try terraform plan or apply (or even init - if you haven't done that yet, it will crash.

### Important Factoids

Workaround is don't use terraform to build out Cloudwatch Log Group.

**Comment by ewbankkit** [comment]
@reubendevries Thanks for raising this issue 👏.
There is a missing `"` character in your configuration:

```hcl
resource "aws_cloudwatch_log_group "kaizen-energy-frontend" {
```

should be

```hcl
resource "aws_cloudwatch_log_group" "kaizen-energy-frontend" {
```

but of course, this should not crash the Terraform CLI.
I will open an issue in the upstream Terraform Core repository for this.

**Comment by ewbankkit** [comment]
I have opened https://github.com/hashicorp/terraform/issues/28587 upstream to track this.
