### ISSUE TITLE
Add tags as search criteria for aws_acm_certificate data source

### ISSUE THREAD

**Issue by sheldonkwok** [hashicorp/terraform-provider-aws#1918]
We are currently attempting to add more domains to our certificate and need to rotate it out across our ALBs. However, the aws_acm_certificate data source functionally only accepts the domain for discovery.  Discovery with tags allows matching on similar domain certificates through a method that is commonly accepted with other data sources.

There is another issue that is similar to this: https://github.com/terraform-providers/terraform-provider-aws/issues/546
However, tagged resources are immune to users creating new certificates and could allow for more than two ACM resources with the same name at once.

**Comment by petewilcock** [comment]
Bump and +1 to this. The current data source isn't usable as we also have certificates with the same domain name, and so this single filter isn't sufficient.

**Comment by bflad** [comment]
I know its not exactly what you're looking for, but we did just recently merge in `most_recent` filtering for the `aws_acm_certificate` data source. You'll also be happy to know that I am just about to click the merge button on a `aws_acm_certificate` _resource_ that should support importing. Both will be available in v1.9.0 of the AWS provider. 😀 

I do think filtering via tags is a valid request though, even if the above items mitigate its need partially!

**Comment by petewilcock** [comment]
Thanks @bflad - the resource news is very good! Look forward to using it :)

**Comment by pocheptsov** [comment]
It's quite useful to match ACM **by tags** whenever domain name will be **optional**, cause it can be not the same in different contexts. Thx

**Comment by dgoradia** [comment]
Is this still going to be implemented? We also have multiple domain certs and need to be able to filter via tags.

**Comment by lee5i3** [comment]
Same here, would be nice to match the ACM by what tag I want rather than the specific domain name.. I've been tagging my certs with application and environment, would rather keep passing that to get the cert rather than also requiring the domain name

**Comment by sheldonkwok** [comment]
https://www.terraform.io/docs/providers/aws/r/acm_certificate.html
It looks implemented now

**Comment by gwkunze** [comment]
As the message above states, I implemented the basic functionality for this in #8352. But my familiarity with how the testing of the provider works is not enough to finish it. It is unclear to me how to properly implement the tests as I don't know where the resources the data source has to retrieve are created and what they look like.

**Comment by hc-danieltiziani** [comment]
Do we have any hopes of filtering the datasource for the certificates via tag?
I have a requirement that I can have multiple certificates for the same domain (transitioning from infrastructures), and I cannot rely on most_recent filter alone, so I'd like to be able to filter by specific tags. 

Is there any workaround to achieve this using terraform aws provider?

**Comment by blevine** [comment]
Any status on this. It seems like all data sources for resources that accept tags should support search by tags.

**Comment by gibsonje** [comment]
Unable to use this data source without tag filtering.

**Comment by abualy** [comment]
filtering based only on domain_name can cause very big issues when you have certs with same domain name but different `subject_alternative_names`
this enhancement is a must have in this data source :/

**Comment by treksler** [comment]
to summarize this issue then

**abandoned PR**
looks good to me, but have not tested
https://github.com/hashicorp/terraform-provider-aws/pull/8352

**another abandoned PR to do the filtering**
looks ok as well, even has some tests, but is also abandoned
https://github.com/hashicorp/terraform-provider-aws/pull/6387

**PR to add tag attribute, NOT filter by tag**
looks like this was merged, BUT it does NOT have the filtering functionality, it only add the tags attribute
https://github.com/hashicorp/terraform-provider-aws/pull/11659

as a workaround, i am looking at using https://registry.terraform.io/providers/hashicorp/external/latest/docs/data-sources/data_source

**Comment by alansaw-trulioo** [comment]
+1

**Comment by jastsai** [comment]
+1

**Comment by TheWallOfDucks** [comment]
+1

**Comment by rromic** [comment]
+1

**Comment by rromic** [comment]
Hey guys, 
I have created this #31453 to add support to filter by tags.
Every suggestion or possible improvements are welcome.

Please add reactions to the PR so it can be reviewed faster :)

Thanks!

**Comment by vishwa-trulioo** [comment]
Hello, we are also running into issues because of this. When is this going to be released? Thanks

**Comment by maharjanSaroj** [comment]
Hello, we are also running into issues because of this. When is this going to be released? Thanks

**Comment by murataksoy83** [comment]
Hi all,

I was stuck with the same issue and figured out the following **workaround**.
You can use the 'aws_resourcegroupstaggingapi_resources' data resource to fetch the certificate by the tag filter:

`
data "aws_resourcegroupstaggingapi_resources" "acm_by_tags" {
  resource_type_filters = ["acm:certificate"]

  tag_filters {
    key    = "key"
    values = ["value"]  
  }
}
`
You can then reference to the ARN of the certificate as follows:

`data.aws_resourcegroupstaggingapi_resources.acm_by_tags.resource_tag_mapping_list[0].resource_arn`

Hope this helps!

Regards,
Murat
