### ISSUE TITLE
Tag error for ECS in govcloud partion using default_tags

### ISSUE THREAD

**Issue by pjaudiomv** [hashicorp/terraform-provider-aws#19185]
Provider version 3.38.0
Terraform 0.15.1

when using `default_tags` feature apply fails as it tries to create tags on ecs resource.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

resource `aws_ecs_service`

* aws_XXXXX

### Terraform Configuration Files
```
provider "aws" {
  default_tags {
    tags = {
      "Name"             = "compliance"
      "workload"        = "prod"
    }
  }
}
  ```

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Panic Output

```
│ Error: error updating ECS Service (arn:aws-us-gov:ecs:us-gov-west-1:1111111111:service/dev) tags: error tagging resource (arn:aws-us-gov:ecs:us-gov-west-1:1111111111:service/dev): InvalidParameterException: Long arn format must be used for tagging operations
│ 
│   with module.egress_proxy[0].aws_ecs_service.service,
│   on .terraform/modules/egress_proxy/ecs.tf line 87, in resource "aws_ecs_service" "service":
│   87: resource "aws_ecs_service" "service" {
│ 
```

### Expected Behavior

resource is created , aws provider should not attempt to tag ecs service on govcloud

### Actual Behavior

Error thrown because listing tags of aws_ecs_cluster is not supported in aws-gov partitions.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I also tried adding an lifecycle ignore tag on the resource and that didnt work

```
  lifecycle {
    ignore_changes = [tags]
  }
  ```

### References

* #0000

**Comment by pjaudiomv** [comment]
different partition but similar ticket https://github.com/hashicorp/terraform-provider-aws/issues/18134

**Comment by pjaudiomv** [comment]
Ahh that makes sense, I will try that. Thank you.

**Comment by anGie44** [comment]
Sure thing! Let us know if you're still seeing the tagging errors even with the workaround.

**Comment by pjaudiomv** [comment]
> Sure thing @pjaudiomv ! Let us know if you're still seeing the tagging errors even with the workaround.

just tested and the workaround worked fine. thanks again.

**Comment by radius314** [comment]
It looks like you can tag `aws_ecs_service` now in `aws-us-gov` partitions.
