### ISSUE TITLE
Imports report successful but have failed

### ISSUE THREAD

**Issue by edgan** [hashicorp/terraform-provider-aws#19194]
I was trying to import a `aws_rds_cluster` and a `aws_rds_cluster_instance`. I expected the id for the resource would be like instance ids and security group ids. So I tried using the `Resource ID` for the cluster and instance. The output said `Import successful!`, but I had nothing in the state. Also `terraform apply` acted like the import did nothing. I then reran with `export TF_LOG=trace` and found the actual error message saying the RDS Cluster instance (X) not found. So the backend knows it failed, but the frontend reports it was successful. I then read the documentation for aws_rds_cluster and aws_rds_cluster_instance to find it wanted their identifiers, not `Resource ID`s. Once I used the identifiers, the resources imported properly.
  
The bug is that an error occurred, but terraform says it was successful.

```2021-05-01T11:38:56.609-0700 [INFO]  provider.terraform-provider-aws_v3.31.0_x5: 2021/05/01 11:38:56 [WARN] RDS Cluster Instance (db-2XXXBKMJFAQLUGUX5XXX274XXX): not found, removing from state.: timestamp=2021-05-01T11:38:56.609-0700```

```
Terraform v0.15.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.31.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

**Comment by ewbankkit** [comment]
@edgan Thanks for raising this issue :clap:.
This is caused by not checking for `d.IsNewResource()` in the resource Read function that resource import uses: https://github.com/hashicorp/terraform-provider-aws/issues/16796.
