### ISSUE TITLE
Error installing provider "aws": openpgp: signature made by unknown entity

### ISSUE THREAD

**Issue by pradeepjykp002** [hashicorp/terraform-provider-aws#19201]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

terraform init is not happening

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Actual Behavior

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Error installing provider "aws": openpgp: signature made by unknown entity.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_amd64

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by badmanski** [comment]
Please make sure you're using one of the latest Terraform releases mentioned in this post: https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570

**Comment by ewbankkit** [comment]
@pradeepbhadani Thanks for raising this issue 👏.
The explanation for this message is covered in #19158.
I'm going to close this issue so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by pradeepjykp002** [comment]
@ewbankkit  
Thanks . Im using the terraform version "Terraform v0.11.13" . Will this version also need to update the GPG file? 
If Yes, under which directory in linux server i have to update the GPG key?
any step by step process to follow?
