### ISSUE TITLE
Glue partition values

### ISSUE THREAD

**Issue by RakeshKopusetti** [hashicorp/terraform-provider-aws#19206]
how to pass multiple year/months to glue partition values ..as of now I defined two partitions ( year and month) and my partitions values ( not able to pass more than two values eg : 2017 ,01)

I haven't seen any example from terrfaorm as well. it would be good if we have some sample code.

**Comment by sepulrator** [comment]
this is the sample I used with projection. hope it helps.
`
parameters = {
    classification = "parquet"
    "projection.enabled" = "true"
    "projection.day.digits" = "2"
    "projection.day.range" = "01,31"
    "projection.day.type" = "integer"
    "projection.month.digits" = "2"
    "projection.month.range" = "01,12"
    "projection.month.type" = "integer"
    "projection.year.range" = "2020,2030"
    "projection.year.type" = "integer"
  }

  partition_keys {
    name = "year"
    type = "int"
  }

  partition_keys {
    name = "month"
    type = "int"
  }

  partition_keys {
    name = "day"
    type = "int"
  }
`

**Comment by DrFaust92** [comment]
Closing for lack if comment. the above solution should suffice.
