### ISSUE TITLE
aws_secretsmanager_secret_version fails to move the AWSCURRENT label

### ISSUE THREAD

**Issue by kjkuan** [hashicorp/terraform-provider-aws#19212]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.10.0
```
### Affected Resource(s)

* aws_secretsmanager_secret_version

### Terraform Configuration Files

Any use of the `aws_secretsmanager_secret_version` resource with `version_stages` set to `[ "AWSCURRENT" ]`.

### Expected Behavior
If `aws_secretsmanager_secret_version` is told to set the `AWSCURRENT` label but the label is currently on a different version (e.g., one that's created by manually updating the secret in Secrets Manager in AWS console), then terraform should move the label back to the version tracked by terraform.

### Actual Behavior
With a plan like this:
```
  ~ resource "aws_secretsmanager_secret_version" "app-config-vars-from-tf" {
        id             = "staging3/workers/configs|DAC17BED-4C85-4187-A6D0-D46CE9D5780A"
      ~ version_stages = [
          + "AWSCURRENT",
        ]
        # (4 unchanged attributes hidden)
    }
```

We got an error like this:
```
Error: error updating Secrets Manager Secret "staging3/workers/configs" Version Stage "AWSCURRENT": InvalidParameterException: The parameter RemoveFromVersionId can't be empty. Staging label AWSCURRENT is currently attached to version 22bcae4b-f6b7-45e4-bf54-48495c69a33b, so you must explicitly reference that version in RemoveFromVersionId.
```

### Steps to Reproduce

1. Set  `version_stages` to `[ "AWSCURRENT" ]` for a `aws_secretsmanager_secret_version` resource
2. `terraform apply`
3. Manually update the secret outside of terraform so that the `AWSCURRENT` label is moved to a different version than the one tracked by terraform.
4. `terraform apply`

### References
- https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_UpdateSecretVersionStage.html#API_UpdateSecretVersionStage_RequestSyntax

**Comment by syndbg** [comment]
@kjkuan Just letting you know that I've opened a PR (referenced) that fixes the issue you reported. 
Works on our end ™️ (and tests'), but if you're blocked, you can also test it.

To maintainers, the issue is also blocking us (SumUp) from using `terraform-provider-aws` with SecretsManager resources.

**Comment by syndbg** [comment]
Any chance we can get this fixed? The referenced PR is still eager to be reviewed 🥳

**Comment by peramnaveen29** [comment]
Any ETA for the fix? this will be useful to force update changes made to secrets outside of terraform

**Comment by zoezhangmattr** [comment]
have the same error

**Comment by viktorradnai** [comment]
This bug also affects us

**Comment by yauhen-sobaleu** [comment]
+1

**Comment by alexku7** [comment]
still isn't fixed :(
