### ISSUE TITLE
Tagging on default resources not supported aws_elasticache_subnet_group

### ISSUE THREAD

**Issue by Luminoth** [hashicorp/terraform-provider-aws#19213]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/aws v3.38.0

### Affected Resource(s)

* aws_elasticache_subnet_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  region  = var.region
  profile = var.profile

  default_tags {
    tags = {
      Name = "terraform-default"
    }
  }
}

resource "aws_elasticache_subnet_group" "default" {
  name        = "default"
  description = "Default CacheSubnetGroup"
  subnet_ids  = data.aws_subnet_ids.public.ids
}
```

### Expected Behavior

I would expect Terraform to skip applying default tags to resources that can't have them.

### Actual Behavior

```
Error: error updating tags: error tagging resource (arn:aws:elasticache:[snip]:subnetgroup:default): InvalidParameterValue: Tagging on default resources is not supported

in resource "aws_elasticache_subnet_group" "default":
resource "aws_elasticache_subnet_group" "default" {
 ```

### Steps to Reproduce

1. `terraform apply`

Related:

* #19119
* #7926

**Comment by anGie44** [comment]
Hi @Luminoth, thank you for reporting this! In the meantime I believe adding a `lifcycle` config block to your config should prevent changes being detected e.g.

```hcl
resource "aws_elasticache_subnet_group" "default" {
  name        = "default"
  description = "Default CacheSubnetGroup"
  subnet_ids  = data.aws_subnet_ids.public.ids

  lifecycle {
    ignore_changes = [tags_all]
  }
}
```

**Comment by Luminoth** [comment]
That workaround worked perfectly. Thank you!
