### ISSUE TITLE
Terraform v0.11 Provider Downloading Error

### ISSUE THREAD

**Issue by WoodProgrammer** [hashicorp/terraform-provider-aws#19222]
Hello,

I have got a terraform stack which is developed with terraformv11.0 before.

The problem is `terraform init` command is returning this error =>>` Error installing provider "aws": openpgp: signature made by unknown entity.`.The first time I've thought the problem is related to my local after that I've moved all actions into different places other Linux distros (eg. Debian, Ubuntu).

Currently, we are installing the terraform-aws-provider plugin manually but we need a proper solution for that.

Thank you 
Best Regards

**Comment by DMeechan** [comment]
Looks like this is a known issue: https://github.com/hashicorp/terraform-provider-aws/issues/19201

[Hashicorp's update](https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570) recommends upgrading to 0.11.15

**Comment by ewbankkit** [comment]
@WoodProgrammer Thanks for raising this issue 👏.
The explanation for this message is covered in #19158.
I'm going to close this issue so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
