### ISSUE TITLE
Add support for CloudFront Functions

### ISSUE THREAD

**Issue by jnerin** [hashicorp/terraform-provider-aws#19226]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS announced a new thing: CloudFront Functions, a way to run lighter Lambda@Edge functions closer to the Edge 😏.

### New or Affected Resource(s)

Cloudfront will need to have support for this added:
* aws_cloudfront_distribution
* aws_lambda_function

### Potential Terraform Configuration

I guess quite similar if not almost identical to the way Lambda@Edge functions are deployed.

### References

- https://aws.amazon.com/blogs/aws/introducing-cloudfront-functions-run-your-code-at-the-edge-with-low-latency-at-any-scale/
- https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-functions.html
- https://docs.aws.amazon.com/cli/latest/reference/cloudfront/create-function.html
- https://docs.aws.amazon.com/cli/latest/reference/cloudfront/publish-function.html

**Comment by jnerin** [comment]
Closed as duplicate of #19225 , by a few minutes 😁

**Comment by chrs-myrs** [comment]
This is closed but the 'duplicate' issue doesn't cover the `aws_cloudfront_distribution` resource, so maybe that needs a separate ticket?
