### ISSUE TITLE
Feature Request: CloudFront Functions

### ISSUE THREAD

**Issue by alexjurkiewicz** [hashicorp/terraform-provider-aws#19225]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for [CloudFront Functions](https://aws.amazon.com/blogs/aws/introducing-cloudfront-functions-run-your-code-at-the-edge-with-low-latency-at-any-scale/)

### New or Affected Resource(s)

* aws_cloudfront_function

### Potential Terraform Configuration

```terraform
resource "aws_cloudfront_function" "default" {
  name = "test"
  runtime = "cloudfront-js-1.0"
  comment = "my function"
  publish = true
  code = file("${path.module}/function.js")
}
```

### References

* Launch blog: https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
* Developer docs: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-functions.html
* API docs: https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateFunction.html

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.38.30](https://github.com/aws/aws-sdk-go/releases/tag/v1.38.30):

* #19224

**Comment by chrs-myrs** [comment]
We have been working with AWS on the private preview here, the above functionality creates the function, but what we urgently need is the ability to assign a function to a CloudFront Behaviour.  We wouldn't use the above suggestion as our functions are deployed and published by a deployment pipeline.  Currently we need to do the Function -> Behaviour assignment manually, but this is the perfect job for Terraform (which currently unassociates the functions every time an apply is made affecting a distribution)

**Comment by dbednall** [comment]
Cloudfront Functions basically get associated to distribution behaviour(s) like Lambda@Edge 

In addition to the proposed new resource is a change is required to `cloudfront_distribution` to have a new config block to manage the function association as part of a Default/Ordered Cache Behaviour configuration.

So taking inspiration from the existing config block for Lambda@Edge: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#lambda-function-association this feature requires the following

```hcl
ordered_cache_behavior {
    # ... other configuration ...

    # zero or more of 
    function_association {
      event_type   = "viewer-request"
      # the specific event to trigger this function. Valid values: viewer-request, viewer-response

      arn   = aws_cloudfront_function.default.arn
      #  e.g. arn:aws:cloudfront::000000000001:function/test
    }
  }
```

Some might say `function_association {}` should be `cloudfront_function_association {}` or similar to fully distinguish from `lambda_function_association {}` but the API doesn't https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_DefaultCacheBehavior.html (see `FunctionAssociations`)

----

Alternatively the config block could be made generic to handle both the association of Lambda@Edge functions AND Cloudfront Functions fuctions and deprecate `lambda_function_association {}`

**Comment by rgant** [comment]
Is there any work around in the meantime that I can use to stop terraform from removing the cloudfront functions from my distributions?

Right now every time my cloudfront distribution is modified it removes the functions without warning me. Even something that warns me would be good.
