### ISSUE TITLE
Error applying aws_s3control_bucket_lifecycle_configuration resource

### ISSUE THREAD

**Issue by andrew-white-nbs** [hashicorp/terraform-provider-aws#19230]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/aws v3.30.0

### Affected Resource(s)

* aws_s3control_bucket_lifecycle_configuration

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket" "my_bucket" {
  bucket = "my_bucket"
}
resource "aws_s3control_bucket_lifecycle_configuration" "bucket_retention_lifecyle" {
  bucket = aws_s3_bucket.my_bucket.arn

  rule {
      id = "foo"
      filter {
        tags = { bar = "baz" }
      }
      expiration {
        days = 365
      }
  }
}

```

### Expected Behavior

Rules are applied

### Actual Behavior

Error: error parsing S3 Control Bucket ARN (): unknown format

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by anGie44** [comment]
Hi @andrew-white-nbs , thank you for raising this issue and apologies you came across that apply time error. Making an initial pass at the configuration you've provided, I see the `aws_s3_bucket` resource is in use, however, I believe the [`aws_s3control_bucket` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3control_bucket) is necessary for compatibility with the lifecycle configuration resource. Do you mind confirming the Terraform AWS provider S3 bucket resource being used w/the lifecycle configuration?

**Comment by andrew-white-nbs** [comment]
Hi @anGie44 - well, now I feel dumb. Thanks for spotting this. This can be closed, user error

**Comment by anGie44** [comment]
No sweat @andrew-white-nbs , it happens! 😄
