### ISSUE TITLE
Documentation doesn't match implementation for aws_sns_topic_subscription for email protocol

### ISSUE THREAD

**Issue by erd0s** [hashicorp/terraform-provider-aws#19233]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_sns_topic_subscription

### Terraform Configuration Files

```hcl
resource "aws_sns_topic_subscription" "tony" {
  endpoint = "tony@tony.com"
  protocol = "email"
  topic_arn = aws_sns_topic.some_topic.arn
  endpoint_auto_confirms = true
}
```

### Debug Output

```
│ Error: expected protocol to be one of [application http https lambda sms sqs], got email
│
│   with aws_sns_topic_subscription.tony,
│   on tony.tf line 7, in resource "aws_sns_topic_subscription" "tony":
│    7: resource "aws_sns_topic_subscription" "tony" {
│
```

### Expected Behavior

Documentation matches implementation

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The documentation (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_topic_subscription) indicates that `email` is a valid `protocol`

> protocol - (Required) Protocol to use. Valid values are: sqs, sms, lambda, firehose, and application. Protocols email, email-json, http and https are also valid but partially supported. See details below.

...however, the code seems to not include `email` or `email-json` (see. https://github.com/hashicorp/terraform-provider-aws/blob/master/aws/resource_aws_sns_topic_subscription.go#L40-L48)

### References

* #0000

**Comment by anGie44** [comment]
Hi @erd0s , thank you for raising this issue. The documentation in reference maps to the code in the `main` branch, renamed from `master` (apologies for any confusion since the branch is still visible in the repo): https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_sns_topic_subscription.go. Looking at the file history, i believe `v3.33.0` of the provider should be compatible with the `email` protocol. Do you mind confirming which version you are currently working with?

**Comment by erd0s** [comment]
Hah! I thought i was being so helpful finding the spot in code, my bad I was just pinned to an older version of the provider, I'll close this :)
