### ISSUE TITLE
aws_cloudwatch_event_rule creates rules in other accounts but fails to read them with error unexpected format for ID

### ISSUE THREAD

**Issue by masaka3620** [hashicorp/terraform-provider-aws#19234]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/aws v3.37.0
```
### Affected Resource(s)

* aws_cloudwatch_event_rule

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl

resource "aws_cloudwatch_event_permission" "allow_event_forwarder" {
  principal    = "999999999999"
  statement_id = "allow-event-forwarder"
}

resource "aws_cloudwatch_event_rule" "event-forwarder" {
  name           = "event-forwarder"
  description    = "Forwards events from the source event bus to the default bus in the my account"

  event_bus_name = "arn:aws:events:my-region:999999999999:event-bus/source-event-bus" 

  event_pattern = <some pattern>
}
```

The rule is created and the provider exits successfully

### Actual Behavior

The rule was created successfully, however terraform exited with failure.  The failure message, which also happens on subsequent runs of terraform was:

```
Error: error reading CloudWatch Events Rule (arn:arn:aws:events:my-region:999999999999:event-bus/my-rule-in-another-account): unexpected format for ID ("arn:aws:events:my-region:999999999999:event-bus/source-event-bus/event-forwarder"), expected <event-bus-name>/<rule-name> or <rule-name>
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

We were following these guidelines: https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-cross-account.html

In our case, we have an AWS organization.  For simplicity, we'll say we have accounts A & B.  Account A has an event bus that is receiving certain events.  There are IAM permissions that allow anyone in the organization to create rules against that event bus without having to assume a role in that account directly.

### References

In searching around for solution to this, I found https://github.com/hashicorp/terraform-provider-aws/pull/16982, which would have solved my problem, but it appears to have been closed by the contributor.  https://github.com/hashicorp/terraform-provider-aws/pull/19072 was promising, but seemed specific to partner buses, which isn't my use case. 

* https://github.com/hashicorp/terraform-provider-aws/pull/19072
* https://github.com/hashicorp/terraform-provider-aws/pull/16982

**Comment by ewbankkit** [comment]
Related:

* #8759

**Comment by 0nedark** [comment]
I'm experiencing the same issue even when creating rules in the same account

```
Terraform v0.15.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.40.0
```

**Comment by FrancescoFucile-CAZ** [comment]
This PR should fix the issue.
#20312
