### ISSUE TITLE
aws_db_instance engine_version gets updated in-place with every run

### ISSUE THREAD

**Issue by Veluu** [hashicorp/terraform-provider-aws#19240]
Hello,

Whenever `auto_minor_version_upgrade` is disabled with every `terraform apply` it wants to do `engine_version` update in-place.

When `auto_minor_version_upgrade` is enabled it works as expected.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.37.0
```

### Affected Resource(s)

* aws_db_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_db_instance" "default" {
  instance_class             = "db.t3.small"
  license_model              = "license-included"
  maintenance_window         = "sun:03:05-sun:05:00"
  engine                     = "oracle-se2"
  engine_version             = "12.1"
  name                       = "EMXPL"
  auto_minor_version_upgrade = false
  allocated_storage          = 10
  username                   = "foo"
  password                   = "foobarbaz"
  skip_final_snapshot        = true
}
```

### Expected Behavior

Configuration has not changed therefore there should be no update in-place. As long as major version is in order (12.1 matches 12.1.x.y.z) there should not be an update.

### Actual Behavior

With every run Terraform wants to update engine_version as you can see below. In reality it does nothing as anyway it stays pinned to the newest minor version that's actually available in AWS RDS.

Below there's a plan from second run (after it was first created without any problems).

```terraform
aws_db_instance.default: Refreshing state... [id=terraform-20210504214948210400000001]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_db_instance.default will be updated in-place
  ~ resource "aws_db_instance" "default" {
        address                               = "terraform-20210504214948210400000001.ck27w5szo6th.us-east-1.rds.amazonaws.com"
        allocated_storage                     = 10
        arn                                   = "arn:aws:rds:us-east-1:237839530861:db:terraform-20210504214948210400000001"
        auto_minor_version_upgrade            = false
        availability_zone                     = "us-east-1c"
        backup_retention_period               = 0
        backup_window                         = "05:57-06:27"
        ca_cert_identifier                    = "rds-ca-2019"
        character_set_name                    = "AL32UTF8"
        copy_tags_to_snapshot                 = false
        db_subnet_group_name                  = "default"
        delete_automated_backups              = true
        deletion_protection                   = false
        enabled_cloudwatch_logs_exports       = []
        endpoint                              = "terraform-20210504214948210400000001.ck27w5szo6th.us-east-1.rds.amazonaws.com:1521"
        engine                                = "oracle-se2"
      ~ engine_version                        = "12.1.0.2.v23" -> "12.1"
      	# redacted rest of the lines
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform apply`

* #0000

**Comment by obourdon** [comment]
Got exactly the same issue with Postgres version specified as major (aka 12), being instantiated during first apply and stored in state file as "12.5" and following plan/apply always want to modify it.

I think that `auto_minor_version_upgrade` which is a AWS RDS parameter described as follows in the AWS console:
```
Enable auto minor version upgrade
Enabling auto minor version upgrade will automatically upgrade to new minor versions as they are released. The automatic upgrades occur during the maintenance window for the database.
```

should be made completely independent of the code [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/diff_suppress_funcs.go#L45:L69)

However, there is a case for which I do not understand how this is really supposed to behave:

Say I specify `engine=postgres` AND `engine_version=12.5` AND `auto_minor_version_upgrade=true`
what I think will eventually happen is that AWS will at some point in time automatically upgrade my RDS instance to 12.6
However, considering the code mentioned above would then compare 12.5 and 12.6 with the Golang function `strings.HasPrefix` which will obviously fail too ?

Anything I am missing or getting wrong here ?
