### ISSUE TITLE
Cannot specify AddressAllocationids when updating server to EndpointType: VPC

### ISSUE THREAD

**Issue by hello-ish** [hashicorp/terraform-provider-aws#19250]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.12.26
provider "aws" (hashicorp/aws) 3.8.0

### Affected Resource(s)

* aws_transfer_server

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl

resource "aws_transfer_server" "foo" {
  endpoint_details {
    address_allocation_ids = ["eipalloc-..."]
    subnet_ids = ["subnet-..."]
    vpc_id = "vpc-..."
    vpc_endpoint_id = "vpce-..."
  }
  endpoint_type = "VPC"
}
```

### Debug Output
With all required field above given correctly: the Error is as below:

Error: error updating Transfer Server (s-exxxxxxx): InvalidRequestException: Cannot specify AddressAllocationids when updating server to EndpointType: VPC

### Panic Output
Error: error updating Transfer Server (s-exxxxxxx): InvalidRequestException: Cannot specify AddressAllocationids when updating server to EndpointType: VPC

### Expected Behavior

Should have deployed sftp with specified or given elastic ip within EndpointType: VPC

### Actual Behavior
Error: error updating Transfer Server (s-exxxxxxx): InvalidRequestException: Cannot specify AddressAllocationids when updating server to EndpointType: VPC

### Steps to Reproduce

I am not too sure if anyone else have tried the same thing to try deploying sftp with "VPC" endpoint type and static ip. Stuck with above error message.

### References

* #12599
* #11569
When tried manually it works.

**Comment by ewbankkit** [comment]
@hello-ish Thanks for raising this issue.
Whilst looking at merging #13371 I have been taking an in-depth look at this code and think I see the bug (we are not clearing the `AddressAllocationIds` specified for the `UpdateServer` call). I will address this as part of the merge.

**Comment by ewbankkit** [comment]
@hello-ish Diggiing around further I see that this issue has already been noticed in #16556. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
