### ISSUE TITLE
Unable to delete aws_instance if disable_api_termination was true

### ISSUE THREAD

**Issue by tmccombs** [hashicorp/terraform-provider-aws#19275]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform: v0.14.8
Provider: v3.38.0

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_instance" "test" {
  disable_api_termination = true
  # ...
}
```

### Expected Behavior

If I manually enable api termination on instance previously managed by terraform that had `disable_api_termination` set to true, and then apply a change to destroy that instance, the instance should be destroyed, and terraform should not re-enable termination protection as part of the apply.

### Actual Behavior

Apply deletion of an aws_instance always modifies the attribute to match what is in the resource config 

### Steps to Reproduce

1. `terraform apply`

### Cause

I'm pretty sure this was introduced in  commit 0a116d70949241082 with this change:

```
-	// false = enable api termination
-	// true = disable api termination (protected)
-	if !d.Get("disable_api_termination").(bool) {
-		_, err := conn.ModifyInstanceAttribute(&ec2.ModifyInstanceAttributeInput{
-			InstanceId: aws.String(d.Id()),
-			DisableApiTermination: &ec2.AttributeBooleanValue{
-				Value: aws.Bool(d.Get("disable_api_termination").(bool)),
-			},
-		})
+	err := resourceAwsInstanceDisableAPITermination(conn, d.Id(), d.Get("disable_api_termination").(bool))
 
-		if err != nil {
-			log.Printf("[WARN] attempting to terminate EC2 instance (%s) despite error enabling API termination: %s", d.Id(), err)
-		}
+	if err != nil {
+		log.Printf("[WARN] attempting to terminate EC2 instance (%s) despite error enabling API termination: %s", d.Id(), err)
 	}
```
note that it now unconditionally modifies the disable_api_termination attribute, instead of only changing it if disable_api_termination is false.

## Discussion
Would it be better to just always set the attribute to false before terminating? Rather than depending on the disable_api_termination setting. (or maybe the intention here was that if disable_api_termination was true in the config, then it should be changed to false when the instance is destroyed?)

**Comment by tmccombs** [comment]
In case it wasn't clear, this is a regression.

**Comment by tmccombs** [comment]
Is there anything blocking this? This is preventing me from upgrading to a newer version of the provider.

**Comment by tmccombs** [comment]
Why is this marked as `enhancement` instead of `bug`? this was a regression in version 3.38.  In version 3.37, while it didn't automatically change the protection to allow deleting, if the deletion protection was manually disabled, then destroying the resource worked (in other words  it had the behavior of #19276).

**Comment by jakekreider** [comment]
Curious if anyone has a workaround here - Even if we manually disable API termination in the console, the run re-enables it before attempting to delete, resulting in the apply failing and a lot of toil.

**Comment by tmccombs** [comment]
The only workaround I've found is to terminate the instance from the console then refresh the state.

**Comment by tmccombs** [comment]
Possibly you could change the disable_api_termination to false in the terraform config, apply the change, then remove the config and apply that, but I haven't tried it.
