### ISSUE TITLE
AWS Synthetics Canary clean up implicitly created resources

### ISSUE THREAD

**Issue by brendan-sherrin** [hashicorp/terraform-provider-aws#19288]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.30
+ provider.archive v2.1.0
+ provider.aws v3.34.0
+ provider.local v2.1.0

### Affected Resource(s)

Primary: 
aws_synthetics_canary

Implicit resources:
aws_lambda_function
aws_lambda_layer_version

### Terraform Configuration Files

```
resource "aws_synthetics_canary" "canary" {
  for_each = local.site_list
  depends_on = [ data.archive_file.canary-zip, aws_iam_role.canary-execution-role, aws_iam_role_policy_attachment.canary-role_attachment ]
  name                 = lookup(each.value, "friendly_name") 
  artifact_s3_location = "s3://${aws_s3_bucket.<name>.bucket}/"  
  execution_role_arn   = aws_iam_role.canary-execution-role.arn
  handler              = "${lookup(each.value, "friendly_name")}.handler"  
  zip_file             = data.archive_file.canary-zip[each.key].output_path
  runtime_version      = "syn-python-selenium-1.0" 
  start_canary = true

  schedule {
    expression = "rate(1 minute)"
  }
}
```

### Expected Behavior

I expect that when destroying an aws_synthetics_canary, implicitly created resources would be destroyed as well.

### Actual Behavior

Implicitly created resources were not destroyed and I needed to manually clean these up.

### Steps to Reproduce

1.  Create a aws_synthetics_canary resource
2.  Implicit resources:  aws_lambda_function & aws_lambda_layer_version will also be created
3.  Destroy the aws_synthetics_canary resource, the implicit resources created will not be destroyed.

### Important Factoids

Nope

### References

I've read the note in yellow here: 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/synthetics_canary

and the reference here:
https://docs.aws.amazon.com/AmazonSynthetics/latest/APIReference/API_DeleteCanary.html

I know terraform is *aware* of the ARN's of the implicit resources as they are atrributes on the Canary resource:
engine_arn - ARN of the Lambda function that is used as your canary's engine.
source_location_arn - ARN of the Lambda layer where Synthetics stores the canary script code.

The question is why can't these be linked and deleted when the canary is deleted?  Each Lambda Function and layer has a unique UUID appended so I doubt there'd be any shared resources between canaries:  ie. the lambda name is cwsyn-availabilitystatus-8bbe53a9-83a8-4651-8b05-b6e8516eaa83 for canary name availabilitystatus.

Even if the option is a switch on the resource under eg. lifecycle policies "destroy implicit resources = yes"?

* #0000

**Comment by ramachavali** [comment]
The way i found around this is - create 2 python scripts to clean up artifacts and eni devices that are attached to security group using `when = destroy`. 

cleanup by terraform would be useful too.

**Comment by rholland-i360** [comment]
I'm also having this problem. It makes it impossible to cleanly control canaries with TF. 

AWS creates the lambda and layer along with the canary. I can manually import them for existing canaries, but when I create a new canary, I can't track them in state. If I make resources for the lambda and layer in my TF document (getting their UUIDs from the canary resource), TF goes into error, saying they already exist (since AWS created them with the canary.)

@ramachavali, would you please explain how to do your workaround?

**Comment by ramachavali** [comment]
my destroy has 2 null_resources (for s3 objects and enis) 

for s3 objects cleanup: 
```# runs commands on destroy of tf resources
resource "null_resource" "on_destroy_canary_s3" {
  triggers = {
    bucket = var.artifact_s3_location
    name = var.canary_prefix
    source = var.script_source
  }

  provisioner "local-exec" {
    when = destroy
    interpreter = ["bash", "-c"]
    command = <<EOF
python3 ${self.triggers.source}/cleanup_canary_s3_objects.py --delete -b ${self.triggers.bucket} -p ${self.triggers.name}
EOF
  }

  depends_on = [aws_s3_bucket.files_s3]
}```

`cleanup_canary_s3_objects.py` has: 
```function list {
  log INFO "Objects Found:"
  OBJECTLIST=$(/usr/local/bin/aws s3api list-object-versions \
		--bucket "$BUCKET_NAME" \
		--output text \
		--query "[Versions][].{a:Key}" \
		| grep -e "${CANARY_NAME}" | tail -n +2)
}

function delete {
  log INFO "Deleting commands:"
  while read -r key; do
    if [ -n "${key}" ] ; then
      for FUNCTION_NAME in ${key} ; do
        echo "/usr/local/bin/aws s3api delete-object --bucket ${BUCKET_NAME} --key ${key}"
      done
    else
      log INFO "no functions to delete"
    fi
  done < <(for x in ${OBJECTLIST}; do echo "${x}" ; done)
}

```


so when the null_resource get destroyed, it runs the `command`.


caveat: to adding triggers to an existing null_resource that has `when = destroy` , you have to taint the null_resource to have it recreated with updates.
