### ISSUE TITLE
AWS Cloudwatch Synthetic canary minimum timeout value incorrect

### ISSUE THREAD

**Issue by brendan-sherrin** [hashicorp/terraform-provider-aws#19289]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.30
+ provider.archive v2.1.0
+ provider.aws v3.34.0
+ provider.local v2.1.0

### Affected Resource(s)

aws_synthetics_canary

### Terraform Configuration Files

```
resource "aws_synthetics_canary" "canary" {
  for_each = local.site_list
  depends_on = [ data.archive_file.canary-zip, aws_iam_role.canary-execution-role, aws_iam_role_policy_attachment.canary-role_attachment ]
  name                 = lookup(each.value, "friendly_name") #names have to be unique...
  artifact_s3_location = "s3://${aws_s3_bucket.<name>.bucket}/"   
  execution_role_arn   = aws_iam_role.canary-execution-role.arn
  handler              = "${lookup(each.value, "friendly_name")}.handler" 
  zip_file             = data.archive_file.canary-zip[each.key].output_path
  runtime_version      = "syn-python-selenium-1.0"  
  start_canary = true

  schedule {
    expression = "rate(1 minute)"
  }

  run_config {
    timeout_in_seconds = 5  
    memory_in_mb = 960  
  }
}
```

### Expected Behavior

Canary should be created with a timeout of 5 seconds

Per AWS documentation, the minimum is 3 seconds:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-synthetics-canary-runconfig.html
TimeoutInSeconds:
Minimum: 3

### Actual Behavior

The following error message was displayed:
Error: expected run_config.0.timeout_in_seconds to be in the range (60 - 840), got 5

  22:     timeout_in_seconds = 5

### Steps to Reproduce

1.  Create a aws_synthetics_canary resource with a run_config, timeout_in_seconds value of less than 60
2.  Terraform apply

### Important Factoids

Nope

### References

AWS documentation showing minimum value of 3 seconds.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-synthetics-canary-runconfig.html

* #0000

**Comment by ewbankkit** [comment]
Relevant [AWS API Reference](https://docs.aws.amazon.com/AmazonSynthetics/latest/APIReference/API_CanaryRunConfigInput.html#synthetics-Type-CanaryRunConfigInput-TimeoutInSeconds).
