### ISSUE TITLE
IAM Access Control for Apache Kafka on Amazon MSK

### ISSUE THREAD

**Issue by danmcnulty** [hashicorp/terraform-provider-aws#19295]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please implement IAM Access Control for Apache Kafka on Amazon MSK which was recently released as described at https://aws.amazon.com/about-aws/whats-new/2021/05/introducing-iam-access-control-amazon-msk/

### New or Affected Resource(s)

* aws_msk_cluster

### Potential Terraform Configuration

```hcl
resource "aws_msk_cluster" "example" {
  client_authentication {
    sasl {
      iam = true
    }
  }
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2021/05/introducing-iam-access-control-amazon-msk/
* https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.38.35](https://github.com/aws/aws-sdk-go/releases/tag/v1.38.35).

**Comment by hcourse-nydig** [comment]
Currently working on https://github.com/hashicorp/terraform-provider-aws/pull/19404. My experience writing providers is ~ 0 so I could definitely do with some pointers but I think this covers the basics. Currently running the acceptance tests so will update as soon as they're done.

**Comment by raoim** [comment]
We are also desperately looking for IAM feature.. Can someone provide any workaround meanwhile it is fixed.

**Comment by YakDriver** [comment]
Please see #19404.
