### ISSUE TITLE
Support for taints on EKS Managed NodeGroup (aws_eks_node_group)

### ISSUE THREAD

**Issue by petewilcock** [hashicorp/terraform-provider-aws#19310]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Previously requested in [12780](https://github.com/hashicorp/terraform-provider-aws/issues/12780) but closed as no coverage in the API. As of 11/05/21 [this is now supported](https://github.com/aws/containers-roadmap/issues/864#issuecomment-837542987). [Changelog](https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst). 

### New or Affected Resource(s)

* aws_eks_node_group

### Potential Terraform Configuration

taints resource block that can be specified 0 to n times:

```
taints {
    key = "Name of taint"
    value = "Value of taint"
    effect = "NO_SCHEDULE"|"NO_EXECUTE"|"PREFER_NO_SCHEDULE"
}
```

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/12780

* https://github.com/aws/containers-roadmap/issues/864#issuecomment-837542987

* https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst

**Comment by alessio4tech** [comment]
Hi @petewilcock,

I'm interested in this feature and I would like to spend some time working on this enhancement. Could you please assign this to me ?

**Comment by petewilcock** [comment]
> Hi @petewilcock,
> 
> I'm interested in this feature and I would like to spend some time working on this enhancement. Could you please assign this to me ?

I don't have the power to assign but check out the [Contributor Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/CONTRIBUTING.md) for process :)

**Comment by ewbankkit** [comment]
[Announcement](https://aws.amazon.com/about-aws/whats-new/2021/05/amazon-eks-managed-node-groups-adds-support-kubernetes-node-taints/).
[User Guide](https://docs.aws.amazon.com/eks/latest/userguide/node-taints-managed-node-groups.html).
