### ISSUE TITLE
Attribute exported - Redis - primary_endpoint

### ISSUE THREAD

**Issue by evairmarinho** [hashicorp/terraform-provider-aws#19321]
I cannot get the attribute primary_endpoint of resource aws_elasticache_cluster - redis engine.

**Comment by bill-rich** [comment]
Hi @evairmarinho!

Can you please include an example configuration and output to help in troubleshooting?

**Comment by bill-rich** [comment]
I'm going to close this for now since we don't have an example configuration or log files. If you're still experiencing this problem, please recreate the issue and fill in all the fields in the issue template to ensure we have enough information.
