### ISSUE TITLE
Is there a way to prevent userdata from running everytime?

### ISSUE THREAD

**Issue by ado120** [hashicorp/terraform-provider-aws#19345]
I've noticed that the ansible playbook that I run in the userdata is running everytime, even when I have this block inside my TF code?

I think all this block does is prevent the instance from being destroyed when the userdata gets changed, but it is still running everytime I switch out the instance with a new ami-id..

```
  lifecycle {
    ignore_changes = [
      user_data,
    ]
  }
```

**Comment by bill-rich** [comment]
Hi @ado120!

It sounds like you're on the right track, but can you please provide a complete configuration for the resource you're working with?

**Comment by bill-rich** [comment]
Since its been a few days without a response, I'm going to close this issue. If you are still running into this problem, please open a new issue with the complete example config so someone can help you out.
