### ISSUE TITLE
DevOps Guru  resource

### ISSUE THREAD

**Issue by rsgaikwad** [hashicorp/terraform-provider-aws#19355]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Resource for devops_guru is missing.

### New or Affected Resource(s)

- aws_devops_guru

Will also need to attach permissions to the profiling group, unsure if this would be the same resource or another resource, as you attach them after creation.

### Potential Terraform Configuration

```hcl
resource "aws_devops_guru" "default" {
  name = "name"
  status = "enable|disable"
  coverage = "all|stack"
  tags = {tag1 = val1}
}
```

### References

- https://docs.aws.amazon.com/devops-guru/latest/userguide/welcome.html

**Comment by ewbankkit** [comment]
@rsgaikwad Thanks for raising this issue.
It has already been noticed in #17919. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
