### ISSUE TITLE
Support SES v2 PutEmailIdentityConfigurationSetAttributes

### ISSUE THREAD

**Issue by jjshoe** [hashicorp/terraform-provider-aws#19363]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

v2 of the API allows you to associate a configuration set to a domain, or email. This means you don't have to pass in a configuration set everywhere you call the API or add headers to the email body to get it to use a configuration set.

You can NOT do this via the web ui. You CAN do this via the cli:
` aws sesv2 create-email-identity --email-identity ADDRESS-OR-DOMAIN --configuration-set-name CONFIG-SET ; aws sesv2 put-email-identity-configuration-set-attributes --email-identity ADDRESS-OR-DOMAIN --configuration-set-name CONFIG-SET`

Source: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/managing-configuration-sets-default.html

### New or Affected Resource(s)

* aws_ses_domain_identity
* aws_ses_email_identity

### References

 https://docs.aws.amazon.com/ses/latest/DeveloperGuide/managing-configuration-sets-default.html

**Comment by gmx-git** [comment]
I guess this also depends on the use of SESv2 AWS SDK. I see there's a plan and a pull request for that.
Maybe we'll need to vote them up (👍) so they can pick up some traction.
Here are the links:
[https://github.com/hashicorp/terraform-provider-aws/issues/26796](url)
[https://github.com/hashicorp/terraform-provider-aws/pull/26846](url)

Hope this helps move this one forward as well!
