### ISSUE TITLE
aws_lb_listener_rule doesn't allow blank query since 3.40.0

### ISSUE THREAD

**Issue by alext** [hashicorp/terraform-provider-aws#19376]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform: 0.13.6
AWS provider: 3.40.0

### Affected Resource(s)

* aws_lb_listener_rule

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_lb_listener_rule" "bare_domain_redirect" {
  listener_arn = aws_lb_listener.example.arn

  action {
    type = "redirect"

    redirect {
      protocol    = "HTTPS"
      host        = "www.example.com"
      port        = 443
      path        = "/"
      query       = ""
      status_code = "HTTP_301"
    }
  }

  condition {
    host_header {
      values = ["example.com"]
    }
  }
}
```

### Expected Behavior

Terraform should validate this correctly as it did in provider versions prior to 3.40.0.

### Actual Behavior

`terraform validate` produced the following error:

```
Error: expected length of action.0.redirect.0.query to be in the range (1 - 128), got

  on redirect.tf line 12, in resource "aws_lb_listener_rule" "bare_domain_redirect":
  12:       query       = ""
```

### Steps to Reproduce

1. `terraform validate`

### Important Factoids

It's necessary to specify a blank query parameter here to override the default value of `"#{query}"` which will preserve any query parameters in the original request.  In this instance we don't want the redirect destination to include any parameters from the original request.

### References

This looks to have been introduced in #19285 - opening this issue as requested there.

**Comment by julian-alarcon** [comment]
Terraform 0.13.7 is affected too. As a workaround I needed to pin the version

```
    aws = {
      source  = "hashicorp/aws"
      version = "3.39" # Pinned version to avoid bug https://github.com/hashicorp/terraform-provider-aws/issues/19376
    }
```
