### ISSUE TITLE
api_gateway_rest_api with policy and body set

### ISSUE THREAD

**Issue by farnsm1** [hashicorp/terraform-provider-aws#19381]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* api_gateway_rest_api

### Expected Behavior

When applying a plan that sets both api_gateway_rest_api.policy and api_gateway_rest_api.body my expectation would be that the body and the policy would both be applied.

### Actual Behavior

On a private api gateway applying a change with both a body and a policy produced an error.  The body did not define a `x-amazon-apigateway-policy` entry.   Our policy is defined in the `aws_api_gateway_rest_api.policy` field.

The error that was produced was for the api gateway deployment resource and left the remote terraform state file in a locked state.

```
Error: Error creating API Gateway Deployment: BadRequestException: Private REST API doesn't have a resource policy attached to it
 
  with module.development_prod1.module.system.module.layer_base[0].module.apigateway[0].aws_api_gateway_deployment.main,
  on ../../modules/apigateway/aws-api.tf line 54, in resource "aws_api_gateway_deployment" "main":
```
I am not familiar with the internal design of the provider but think this is a bug.  If the body and policy properties are mutually exclusive, the documentation Terraform should be updated and such a condition should in my view be determined in the planning cycle.  If the properties are not mutually exclusive an implementation where the provider merges the two properties prior to applying the change to AWS would resolve the issue.  The provider should also be able to resolve the issue if it applies in order such that the policy property is set after the body has been set.

A workaround that I am testing is to never use the `api_gateway_rest_api.policy` property.  I think that setting the `x-amazon-apigateway-policy` as a property of the body will resolve our issue and once that testing is complete I will update this issue with my findings.

### Steps to Reproduce

1. Define a terraform configuration for a **private** api gateway with body and policy properties.
2. Apply the configuration (it will fail with the the aforementioned error)
3. Apply again (this time it will succeed)
4. Make a change to the body
5. Apply the configuration (it will fail again)
6. Apply again (this time it will succeed).
2. `terraform apply`

### References

* #0000

**Comment by bflad** [comment]
Hi @farnsm1 👋  Sorry you ran into trouble here. Which version of the Terraform AWS Provider is this on (can be found via `terraform providers` or `terraform version`)? We fixed a bug around this scenario a few months ago in version 3.25.0, please see: https://github.com/hashicorp/terraform-provider-aws/issues/14290

**Comment by farnsm1** [comment]
Oh, I can. confirm that I was running version `3.22.0`.

I will retest with the latest version we can close this issue.  I will re-open if it appears we still have a problem.
