### ISSUE TITLE
data/aws_lambda_function retrieve image_uri

### ISSUE THREAD

**Issue by EnriqueEll** [hashicorp/terraform-provider-aws#19383]
After AWS Lambda support to the container, image URI needs to be provided when creating or updating an AWS Lambda Function. If you have multiple image and lambda version running(like running A/B tests), it is important when updating the Lambda doesn't change the image_uri with a fixed image version. Should be interesting to be able to retrieve the image_uri so that the terraform state receives the right image_uri when updating a function using terraform (there are ways to perform it outside terraform and change a terraform variable).

I'm proposing a enhancement on the data/aws_lambda_function to retrieve image_uri like this:

```terraform
data "aws_lambda_function" "lambda-example-data"{
  function_name = "lambda-example"  
}

resource "aws_lambda_function" "lambda-example" {
  function_name     = "lambda-example"
...
  image_uri = data.aws_lambda_function.lambda-example-data.image_uri
 }
```

**Comment by felipesere** [comment]
I could use this too!
After a quick look at the code, I think this should be fairly achievable?
We'd need to:
* add image_uri to the data source here https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/data_source_aws_lambda_function.go
* grab the image_uri from the result of GetFunction somewhere [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/data_source_aws_lambda_function.go#L214)

I'll see if I can at least pop open an MR to get the conversation rolling.
