### ISSUE TITLE
Thoughts on aws_hosted_zones data provider?

### ISSUE THREAD

**Issue by lingrino** [hashicorp/terraform-provider-aws#19395]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello and thank you for all your work on this critical provider!

When creating `alias` records in Route 53 using the `aws_route53_record` resource terraform needs the `zone_id` of the alias target. When the alias target is an AWS-managed resource (alb, global accelerator, cloudfront, etc...) this is always a known and static value that differs by region (or only a single value for global services).

Existing terraform resources already return the correct hosted zone id for the created resource, making it easy to create resources and records side by side. For example, `cloudfront_distribution` returns `hosted_zone_id` and `aws_lb` returns `zone_id`. This is great! But sometimes you need to create a record for a resource that is not managed in terraform and in these cases you need to find the correct static value from the docs.

I'd like for there to be a new data provider that is essentially a map of all AWS hosted zone ids, divided by service and region. Currently terraform provides something similar through [`data.elb_hosted_zone_id`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/elb_hosted_zone_id) and [`data.elastic_beanstalk_hosted_zone`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/elastic_beanstalk_hosted_zone) but these are service-specific and they don't exist for many other services (s3, cloudfront, global accelerator, network load balancer, others).

I am hoping to make this contribution myself if there's agreement that it would be useful. I opened this issue to get thoughts from more experienced contributors. Below is a rough design that I'd like feedback on.

### New or Affected Resource(s)

I'm proposing a new data resource that is not specific to any AWS service called `aws_hosted_zones` (or something similar). This data resource would be extremely simple and make zero network calls. When a user calls this resource it will return a map of AWS services and their associated hosted zone IDs, broken down by region. My usage of the resource would not take any inputs, but we could also have it take a `region` and `service` to filter the returned values.

### Potential Terraform Configuration

Here's a rough idea of what I'm looking for with an example for global accelerator (no region) and NLBs (unique per region). Currently I have something very similar in a module that only outputs a giant constant value named `hosted_zone_ids`. I'm very open to different provider/variables names and means of accessing the data!

```hcl
data "aws_hosted_zones" "zones" {}

resource "aws_route53_record" "ga" {
  zone_id = aws_route53_zone.primary.zone_id
  name    = "ga.example.com"
  type    = "A"

  alias {
    name                   = "ab1234567cdefg89.awsglobalaccelerator.com"
    zone_id                = data.aws_hosted_zones.zones.hosted_zone_ids["global_accelerator"]
    evaluate_target_health = false
  }
}

resource "aws_route53_record" "nlb" {
  zone_id = aws_route53_zone.primary.zone_id
  name    = "nlb.example.com"
  type    = "A"

  alias {
    name                   = "dualstack.nlb-prod.us-west-2.nlb.amazonaws.com."
    zone_id                = data.aws_hosted_zones.zones.hosted_zone_ids["nlb"]["us-west-2"]
    evaluate_target_health = false
  }
}
```

### References

Links to some (not all!) of the AWS static hosted zone IDs:

- https://docs.aws.amazon.com/Route53/latest/APIReference/API_AliasTarget.html
- https://docs.aws.amazon.com/general/latest/gr/elb.html
- https://docs.aws.amazon.com/general/latest/gr/s3.html#s3_website_region_s3_endpoints

**Comment by YakDriver** [comment]
@lingrino Personally, I like the idea and find these sorts of data sources useful. It would be nice if there were a dynamic way to get all information. However, being overly pragmatic about only allowing dynamic-gathered information may be too rigid. In addition to the example you mentioned, SageMaker also has a static information data source: https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/data_source_aws_sagemaker_prebuilt_ecr_image.go

Also, feel free to [open a discussion topic](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33).

**Comment by lingrino** [comment]
I appreciate the response @YakDriver! I'm glad to hear you think it could be useful.

> It would be nice if there were a dynamic way to get all information. However, being overly pragmatic about only allowing dynamic-gathered information may be too rigid.

I've looked quite a bit and I'm not aware of any way to get these values programmatically. I can only find the comprehensive lists in the docs. The values are returned when you create/describe an existing resource but I can't find a way to get them without presupposing a created resource.

I do think the values are useful when separated from an individual resource. And given that AWS promises the values won't change I would be comfortable hardcoding them in a data resource that is updated when new regions and values are added.

> In addition to the example you mentioned, SageMaker also has a static information data source

This is great example. Should I move forward with a PR based on this resource and my proposal or wait for more comments?

Thank you!
