### ISSUE TITLE
aws_lakeformation_permissions column level permission is not working 

### ISSUE THREAD

**Issue by surendarkaniops** [hashicorp/terraform-provider-aws#19409]
aws_lakeformation_permissions column level permission is not working  even i tried wild card value.

resource "aws_lakeformation_permissions" "grantpermission-columns-users_wildcard" {
  count                         = var.columns_wildcard ? 1 : 0
  principal                     = var.user_principal
  permissions                   = var.user_permissions_coloumn
  table_with_columns {
    database_name         = var.user_database
    name                  = var.user_database_table
    excluded_column_names = var.excluded_column_names
    wildcard              = var.columns_wildcard
  }
}

  user_permissions_table       = ["CREATE_TABLE", "ALTER", "DROP"]
  user_permissions_coloumn     = ["CREATE_TABLE", "ALTER", "DROP"]
  columns_wildcard             = true
  excluded_column_names        = ["policyid"] ## must and only when columns_wildcard arguement is enabled
  user_principal               = "arn:aws:iam:::role/LakeFormationAnalyst"
  athena_query_savings         = "supertest-dataprocessed"
  crawler_data_source          = "supertest-datasource"

**Comment by YakDriver** [comment]
@surendarkaniops You cannot apply `CREATE_TABLE` permission this way as it is not a columnar permission. Besides that issue, I have verified that your test case works with #19817. I added a new acceptance test called `TestAccAWSLakeFormation_serial/TableWithColumnsPermissions/columnWildcardExcludedColumnsPermissions` specifically to test that wildcard + excluded column names works.
