### ISSUE TITLE
aws_networkfirewall_rule_group: cannot update suricata rules

### ISSUE THREAD

**Issue by arpyzo** [hashicorp/terraform-provider-aws#19414]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.15.3
+ provider registry.terraform.io/hashicorp/aws v3.40.0

### Affected Resource(s)

* aws_networkfirewall_rule_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_networkfirewall_rule_group" "main" {
  name     = "set1"
  type     = "STATEFUL"
  rules    = file("set1.rules")
  capacity = 100
}
```
Suricata rules `set1.rules` pre-update:
```
pass tls $HOME_NET any -> $EXTERNAL_NET 443 (tls.sni; content:"OLD.example.com"; msg:"FQDN test"; sid:1;)
```

Suricate rules `set1.rules` post-update:
```
pass tls $HOME_NET any -> $EXTERNAL_NET 443 (tls.sni; content:"NEW.example.com"; msg:"FQDN test"; sid:1;)
```

### Debug Output

Running `terraform apply`:
```
Terraform will perform the following actions:

  # aws_networkfirewall_rule_group.main will be updated in-place
  ~ resource "aws_networkfirewall_rule_group" "main" {
        id           = "arn:aws:network-firewall:us-east-1:000000000000:stateful-rulegroup/set1"
        name         = "set1"
      ~ rules        = <<-EOT
          - pass tls $HOME_NET any -> $EXTERNAL_NET 443 (tls.sni; content:"OLD.example.com"; msg:"FQDN test"; sid:1;)
          + pass tls $HOME_NET any -> $EXTERNAL_NET 443 (tls.sni; content:"NEW.example.com"; msg:"FQDN test"; sid:1;)
        EOT
        tags         = {}
        # (5 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

When applied the following occurs:
```
aws_networkfirewall_rule_group.main: Modifying... [id=arn:aws:network-firewall:us-east-1:000000000000:stateful-rulegroup/set1]
╷
│ Error: error updating NetworkFirewall Rule Group (arn:aws:network-firewall:us-east-1:000000000000:stateful-rulegroup/set1): InvalidRequestException: Exactly one of Rules or RuleGroup must be set
│
│   with aws_networkfirewall_rule_group.main,
│   on firewall_rules.tf line 1, in resource "aws_networkfirewall_rule_group" "main":
│    1: resource "aws_networkfirewall_rule_group" "main" {
│
```

### Expected Behavior

Applying this change should update the firewall rule group.

### Actual Behavior

An error was generated, and the rules were not updated in AWS.

Even though an error ocurred, Terraform updated its state. A subsequent plan/apply shows no changes.

### Steps to Reproduce

1. `terraform apply`
2. Update `set1.rules`
3. `terraform apply`
4. Run `terraform apply` again and see that Terraform's state has been updated.

**Comment by anGie44** [comment]
Associated code block causing the error:

https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_networkfirewall_rule_group.go?L504#L504-L524
