### ISSUE TITLE
access_log_settings of aws_apigatewayv2_stage continuously removed

### ISSUE THREAD

**Issue by acerbisgianluca** [hashicorp/terraform-provider-aws#19412]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

- Terraform CLI: v0.15.1
- AWS provider: v3.40.0

### Affected Resource(s)

* aws_apigatewayv2_stage

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_apigatewayv2_api" "this" {
    name = "api test"
    protocol_type = "WEBSOCKET"
    route_selection_expression = "$request.body.action"
}

resource "aws_api_gateway_account" "this" {
    cloudwatch_role_arn = "role arn"
}

resource "aws_apigatewayv2_stage" "this" {
    name = "stage"
    api_id = aws_apigatewayv2_api.this.id
    deployment_id = aws_apigatewayv2_deployment.this.id
    stage_variables = {
        name = "dev"
    }

    // First apply with this enabled, then reapply removing it
    access_log_settings {
        destination_arn = ""
        format = ""
    }

    default_route_settings {
        data_trace_enabled = false
        detailed_metrics_enabled = false
        throttling_burst_limit = 5000
        throttling_rate_limit = 10000
    }
}

resource "aws_apigatewayv2_deployment" "this" {
    api_id = aws_apigatewayv2_api.this.id
    description = "Development deployment"

    triggers = {
        redeployment = ""
    }

    lifecycle {
        create_before_destroy = true
    }
}
```

### Debug Output

[DEBUG LOG](https://gist.github.com/acerbisgianluca/0f39a7eb0f5a380f0d6ed7f22d961269)

### Expected Behavior

Terraform should remove access log settings and disable _custom_ log.

### Actual Behavior

Terraform tries to remove those settings, but actually they still exist (checked using CLI).
The next `terraform apply` retries to remove those settings, so the state is not updated (see [DEBUG LOG](https://gist.github.com/acerbisgianluca/0f39a7eb0f5a380f0d6ed7f22d961269#file-debug-txt-L19)).

### Steps to Reproduce

1. Create a stage with access_log_settings
2. `terraform apply`
3. Remove access_log_settings from the stage
4. `terraform apply` (this will succeed)
5. `terraform plan`: access_log_settings deletion is planned again

**Comment by acerbisgianluca** [comment]
I've just found that AWS CLI has a `delete-access-log-settings` command for `apigatewayv2`. Probably Terraform doesn't call that api when the settings are removed from the configuration.

**Comment by splisson-cn** [comment]
try setting it to null
