### ISSUE TITLE
Cloud9 environment with Custom AMI

### ISSUE THREAD

**Issue by queglay** [hashicorp/terraform-provider-aws#19417]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great to have the ability to specify our own AMI for cloud9 (and have no inbound access, using SSM).  Currently launching a new cloud9 environment is not really immutable in practice - software is usually installed after its deployment, which can produce an inconsistent environment.

### New or Affected Resource(s)

* aws_cloud9_environment

**Comment by astraldawn** [comment]
Without this feature, provider requests can only use the default image which no longer has standard support: https://docs.aws.amazon.com/cloud9/latest/APIReference/API_CreateEnvironmentEC2.html#cloud9-CreateEnvironmentEC2-request-imageId

**Comment by queglay** [comment]
I no longer use cloud 9 in my workflow at all because it cannot have an immutable controlled and customised environment. It is too unreliable for customization without this.
