### ISSUE TITLE
Amazon EBS Multi-Attach for io2 volumes

### ISSUE THREAD

**Issue by arminio** [hashicorp/terraform-provider-aws#19420]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

You can now enable Provisioned IOPS SSD (io2) volumes for Amazon EBS Multi-Attach.
You can enable Multi-Attach for io1 and io2 volumes during creation.
You can also enable Multi-Attach for io2 volumes after they have been created.

**This feature is now in _General Availability_ across many regions.** 
https://aws.amazon.com/about-aws/whats-new/2020/08/aws-announces-gerneral-availability-of-new-provisioned-iops-volume-io2-for-amazon-ebs/

### New or Affected Resource(s)

* aws_ebs_volume

### Potential Terraform Configuration

```hcl
resource "aws_ebs_volume" "example" {
  type = "io2"

  multi_attach_enabled = true
}
```

### References

* #https://github.com/hashicorp/terraform-provider-aws/issues/16847

**Comment by ewbankkit** [comment]
@arminio Thanks for raising this issue.
It has already been noticed in #19751. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
