### ISSUE TITLE
Tags on ECS tasks are not being propagated from the ECS task definition tags

### ISSUE THREAD

**Issue by mimozell** [hashicorp/terraform-provider-aws#19422]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.14.5
Provider version: 3.36.0 and 3.40.0

### Affected Resource(s)

* aws_ecs_task_definition

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource aws_ecs_task_definition service {
  container_definitions = <<-JSON
    [
      {
        "name": "${var.service-name}",
        "image": "${var.image}",
        "essential": true,
        "portMappings": [
          {
            "containerPort": ${var.container_port},
            "hostPort": ${var.container_port}
          }
        ],
        "environment" : ${jsonencode(local.env_vars)},
        "secrets" : ${jsonencode(var.secrets)},
        "logConfiguration": {
          "logDriver": "awslogs",
          "options": {
            "awslogs-group": "${var.awslogs-group}",
            "awslogs-region": "${var.awslogs-region}",
            "awslogs-stream-prefix": "web"
          }
        }
        %{if var.ulimit != null} ,
        "Ulimits": ${jsonencode(var.ulimit)}
        %{endif}
      }
    ]
  JSON

  family = "${var.service-name}-${var.environment}"
  task_role_arn = var.task_role_arn
  execution_role_arn = var.task_role_arn
  requires_compatibilities = ["FARGATE"]
  network_mode = "awsvpc"
  cpu = var.container_cpu
  memory = var.container_memory

  tags = {
    Environment = var.environment
    AppName = var.service-name
  }
}
```

### Expected Behavior
When adding tags to an AWS Task Definition resource, I expect the tags to be added to the task created based on that task definition as described here: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-using-tags.html#tag-resources. That means that the task definition tags should be propagated to the task that is based on it.

### Actual Behavior

Tags are not being propagated as expected.
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by samdbmg** [comment]
Just to check, how are you running this task? The partial example above creates the task definition but doesn't seem to run it on a cluster.

I only ask because I've just run into the same problem, but found tasks get tagged as expected if I set [`propagate_tags = "SERVICE"`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service#propagate_tags) on an ECS Service (my primary use case), or tell it to propagate tags when launching in the AWS Console.

That said if you're launching tasks using CloudWatch Events it won't work - it's under consideration by AWS in https://github.com/aws/containers-roadmap/issues/89

**Comment by mimozell** [comment]
Good point. I run them through an ECS Service, but I didn't know I had to explicitly ask for tag propagation. The documentation led me to believe that happens automatically. I will check it out and close if it works. Thanks!

**Comment by deliaiuga23** [comment]
Thanks @samdbmg , had the same issue! :)

**Comment by breathingdust** [comment]
Hi @mimozell! 👋 Looks like you got your problem resolved, will close this one. If you think there is still an issue, please comment to reopen!
