### ISSUE TITLE
Docs: aws_codebuild_project source field is mislabelled in configuration block detail.

### ISSUE THREAD

**Issue by steven-schmoll-at** [hashicorp/terraform-provider-aws#19433]
In the documentation for the `aws_codebuild_project` resource, the `source` field is currently mislabelled in detail section.

The configuration block is incorrectly listed as `vpc_config`. See screenshot below. There is a second `vpc_config` section below it which is the actual `vpc_config` section.

![aws_codebuild_project docs error](https://user-images.githubusercontent.com/67622352/118753576-9f350280-b8a8-11eb-801f-2e8474972d64.png)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_codebuild_project (docs)

**Comment by erikpaasonen** [comment]
nice catch! came here to report that `source` block is entirely absent, but you're right, it's there just with a bad label.

this Issue needs (and is currently missing) the `documentation` tag, not sure how that didn't get applied automatically.
