### ISSUE TITLE
v3.41.0 broken on registry.terraform.io for linux/amd64

### ISSUE THREAD

**Issue by Packetslave** [hashicorp/terraform-provider-aws#19435]
`hashicorp/aws v3.41.0` seems to be broken on the registry for `linux/amd64`. 

`linux/amd64` is shown as existing for `v3.41.0` here: https://registry.terraform.io/v1/providers/hashicorp/aws/versions

However, the PackageMeta request for `v3.41.0` returns Not Found: https://registry.terraform.io/v1/providers/hashicorp/aws/3.41.0/download/linux/amd64.

`v3.4.1` seems to exist for other platforms, e.g. https://registry.terraform.io/v1/providers/hashicorp/aws/3.41.0/download/linux/386 and the actual `linux/amd64` package exists at https://releases.hashicorp.com/terraform-provider-aws/3.41.0/terraform-provider-aws_3.41.0_linux_amd64.zip, so it appears that only the PackageMeta is broken.

**Comment by Packetslave** [comment]
@breathingdust

**Comment by mccartney** [comment]
Also a minor thing, but confusing for newbies like me:
https://github.com/hashicorp/terraform-provider-aws/blob/1a0c839877b618572e3eb81f69b4355139ed0813/CHANGELOG.md comes with two entries for `3.41.0`.
(no idea if these two things are related, but I thought I rather not create a separate issue for such a minor thing)

**Comment by ewbankkit** [comment]
@mccartney Thanks for pointing out the issue with the duplicate CHANGELOG headers. I have manually corrected that.
#19384 addresses this and (hopefully) will be merged before the next release.

**Comment by ewbankkit** [comment]
Similar:

* https://github.com/hashicorp/terraform-provider-google/issues/9177

**Comment by Packetslave** [comment]
Looks like this might be related to HTTP compression. Here's how we reproduced:

FAILS: curl --compressed https://registry.terraform.io/v1/providers/hashicorp/aws/3.41.0/download/linux/amd64

SUCCEEDS: curl https://registry.terraform.io/v1/providers/hashicorp/aws/3.41.0/download/linux/amd64

My guess is that terraform doesn't set Accept-Encoding, but Chrome does.

**Comment by Packetslave** [comment]
yep, definitely compression. We (facebook) use a custom registry internally that sends HTTP requests to registry.terraform.io behind the scenes using Python's `requests` library. Turns out, requests enables compression by default (and I'm betting the terraform http.client doesn't). Turning it off explicitly fixes this failure:

```
    import requests
    
    url = "https://registry.terraform.io/v1/providers/hashicorp/aws/3.41.0/download/linux/amd64"
    
    headers = {
        "Accept-Encoding": "identity",
    }
    return requests.get(url, headers=headers)
```

without the `headers` parameter, we get 404. With it, we get the expected JSON response.

**Comment by Packetslave** [comment]
@ewbankkit after further testing, seems not to be version (or provider) specific.  I tested:

https://registry.terraform.io/v1/providers/hashicorp/aws/3.40.1/download/linux/amd64
https://registry.terraform.io/v1/providers/hashicorp/aws/3.40.0/download/linux/amd64
https://registry.terraform.io/v1/providers/hashicorp/google/3.68.0/download/linux/amd64

All fail with `curl --compressed` and 404 without it.

**Comment by Packetslave** [comment]
Although interestingly, the first of those links (hashicorp/aws 3.41.0) fails in my Chrome (90.0.4430.212) but the other two work fine. Even though I can see in the network inspector that Chrome is sending `accept-encoding: gzip, deflate, br`

**Comment by ewbankkit** [comment]
@Packetslave While we investigate further, a workaround is to add the `X-Terraform-Version` HTTP header:

```console
$ curl -H 'X-Terraform-Version: 0.13.4' --compressed https://registry.terraform.io/v1/providers/hashicorp/aws/3.41.0/download/linux/amd64
```

succeeds.

**Comment by Packetslave** [comment]
I grabbed the headers from a successful and failed request here:
https://gist.github.com/Packetslave/9d6e973532fb3feb599862a2da2a99bd

One thing I noticed is that the failed request seems to consistently show `x-served-by: cache-dca17751-DCA`

Maybe there's a stale cache entry on that host?

**Comment by ewbankkit** [comment]
Yes, that seems probable; Setting `X-Terraform-Version` will likely bust the cache.

**Comment by Packetslave** [comment]
yep, https://registry.terraform.io/v1/providers/hashicorp/aws/3.41.0/download/linux/amd64?cache-bust=1 (or any other parameter) also works

**Comment by ewbankkit** [comment]
[**v3.42.0**](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3420-may-20-2021) of the Terraform AWS Provider is now available.
@Packetslave can you please verify that this version is downloadable (the [PackageMeta link](https://registry.terraform.io/v1/providers/hashicorp/aws/3.42.0/download/linux/amd64) is working for me in Chrome)?

**Comment by ewbankkit** [comment]
@mwarkentin Which version of the Terraform CLI are you using?
May be related to #19158.

**Comment by mwarkentin** [comment]
@ewbankkit 0.12.30 I think. I'll try updating and see if that resolves it, thanks!

**Comment by mwarkentin** [comment]
@ewbankkit confirmed that bumping to 0.12.31 resolved my issue installing the newest versions of the AWS provider (3.42.0 installed fine). Sorry about that!
