### ISSUE TITLE
SES SMTP password for different regions

### ISSUE THREAD

**Issue by limitusus** [hashicorp/terraform-provider-aws#19434]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`aws_iam_access_key.ses_smtp_password_v4` is calculated from secure and region.
When you accidentally create an access key with a provider (region A) and then notice that SES region should be different (region B), you want to change the provider of `aws_iam_access_key` resource to retrieve SMTP password for region B.
However, `ses_smtp_password_v4` is not re-calculated for region B even after `terraform refresh`.

SMTP password can be re-calculated with Python script that AWS provides, but it should be more convenient if this provider supports region switching.
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-credentials.html

### New or Affected Resource(s)

* aws_iam_access_key

### Potential Terraform Configuration

```hcl
resource "aws_iam_access_key" "mail_sender" {
  user = aws_iam_user.mail_sender.name
}
```

change the provider, and run `terraform refresh`

```hcl
resource "aws_iam_access_key" "mail_sender" {
  provider = aws.ses
  user     = aws_iam_user.mail_sender.name
}
```

### References

* N/A

**Comment by sirantd** [comment]
Also met this problem but seems found a workaround. You can use aliases for provider
```
provider "aws" {
  region = var.region
}

provider "aws" {
  alias  = "ses"
  region = var.ses-region
}
```

and then explicitly select the `provider` for the ses only:
```
resource "aws_ssm_parameter" "smtp_user" {
  provider = aws.ses
  name     = "/gitlab/smtp/user"
  type     = "SecureString"
  value    = aws_iam_access_key.mailsender.id
}

resource "aws_ssm_parameter" "smtp_pass" {
  provider = aws.ses
  name     = "/gitlab/smtp/pass"
  type     = "SecureString"
  value    = aws_iam_access_key.mailsender.ses_smtp_password_v4
}
```
