### ISSUE TITLE
aws_apigatewayv2_integration SQS-SendMessage MessageAttributes parameter unclear

### ISSUE THREAD

**Issue by orthimnas** [hashicorp/terraform-provider-aws#19443]
Reviewing #17348 determined that in order to get Message Attributes set correctly in my `aws_apigatewayv2_integration` I need to set a selection expression - but it isn't clear what shape the content in that selection expression should be in.  I'm stuffing values from incoming request headers into authorizer context (from my custom authorizer lambda) so I can consume it into the SQS message attributes.
Configuration that isn't successfully sending an SQS message:
```hcl
resource "aws_apigatewayv2_integration" "integration" {
  api_id              = aws_apigatewayv2_api.gateway.id
  credentials_arn     = data.aws_iam_role.apigateway_role.arn
  description         = "Send Inbound request to SQS Queue"
  integration_type    = "AWS_PROXY"
  integration_subtype = "SQS-SendMessage"
  connection_type     = "INTERNET"

  request_parameters = {
    "QueueUrl"          = data.aws_sqs_queue.queue.url
    "MessageBody"       = "$request.body"
    "MessageGroupId"    = "static-for-now"
    "MessageAttributes" = "$context.authorizer"
  }
}
```

Content in `$context.authorizer`:
```json
"ArbitraryName": "value-from-request-header"
```

Error message from API Gateway attempting to send message to SQS:
`Unable to resolve property MessageAttributes from source $context.authorizer. Please make sure that the request to API Gateway contains all the necessary fields specified in request parameters.`

**Comment by orthimnas** [comment]
Any feedback on this request?  I'd like to avoid adding a lambda for the express purpose of forwarding a message with attributes to SQS if it can be done via API Gateway.

**Comment by nerochiaro** [comment]
I managed to get this working by using this syntax for MessageAttributes:

```{ "timestamp": { "DataType": "String", "StringValue": "${request.header.x-timestamp}" } }```

This is for example to add a string attribute called `timestamp` with the same value as the request header `x-timestamp`.

Depending on what the `DataType` is you need a different `*Value` key. See the [SendMessage API documentation](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_MessageAttributeValue.html) page for the valid combinations of data types and key names.

Yes, it's very confusing.

**Comment by breathingdust** [comment]
Hi @orthimnas! 👋  It looks like @nerochiaro had a solution for you, I hope this resolved your issue. Will close this as it didn't appear to be a provider issue.

**Comment by yongzhang** [comment]
@nerochiaro You saved my day, thanks!
