### ISSUE TITLE
Resource aws_apprunner_service does not use image_configuration.runtime_environment_variables

### ISSUE THREAD

**Issue by rvanider** [hashicorp/terraform-provider-aws#19469]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_apprunner_service

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_apprunner_service" "runner" {
  service_name = "sample-app-runner-dev-runner"

  source_configuration {
    authentication_configuration {
    }

    image_repository {
      image_configuration {
        port = "8080"

        runtime_environment_variables = {
          PORT = "8080"
          SPF_NET_NAME = "sample-app-runner-dev"
        }
      }

      image_identifier      = "public.ecr.aws/maxird/spf-welcome:3.0.2"
      image_repository_type = "ECR_PUBLIC"
    }

    auto_deployments_enabled = false
  }

  instance_configuration {
    cpu    = 1024
    memory = 2048

    instance_role_arn = aws_iam_role.runner-instance-role.arn
  }

  health_check_configuration {
    healthy_threshold   = 1
    unhealthy_threshold = 5
    interval            = 10
    path                = "/health"
    protocol            = "HTTP"
    timeout             = 5
  }

  tags = {
    Name = ""sample-app-runner-dev-runner"
  }
}

```

### Debug Output

https://gist.github.com/rvanider/3e4dd0b22dc1c125e34543af4a0f2403#file-debug-log

### Panic Output

none

### Expected Behavior

Service should of launched with environment variables.

### Actual Behavior

Service does not launch with environment configured. In this case, it fails due to requiring at least one to be set.

### Steps to Reproduce

The above resource block and sample image do launch when manually configured via the console.

1. `terraform apply`

### Important Factoids

None

### References

* none

**Comment by anGie44** [comment]
Thank you for raising this issue @rvanider ! Can confirm we're not sending that value in the CreateService API request)

Related code missing both `runtime environment variables` and `start command`:

https://github.com/hashicorp/terraform-provider-aws/blob/d055ffd671d92cede712d5355ce4b1d6a9e494b8/aws/resource_aws_apprunner_service.go#L686-L704
