### ISSUE TITLE
An empty environment variable in batch_job_definition always results in a planned change

### ISSUE THREAD

**Issue by Limess** [hashicorp/terraform-provider-aws#19466]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform Version: 0.12.31
AWS Provider Version: 3.39.0

### Affected Resource(s)

* aws_batch_job_definition

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

```
resource "aws_batch_job_definition" "job-definition" {
  name = "some-job-definition"
  type = "container"
  retry_strategy {
    attempts = 3
  }
  container_properties = jsonencode(
    {
      "command" : [],
      "image" : "<some_image>",
      "memory" : 8192,
      "vcpus" : 8,
      "environment" : [
        {
          "name" : "SOME_VARIABLE",
          "value" : ""
        },
      ]
    }
  )

}
```

this always produces a planned output when an environment variable (`SOME_VARIABLE` here) has the value `""`.

### Debug Output

Any time plan is now ran:

```
-/+ resource "aws_batch_job_definition" "job-definition" {
      ~ arn                   = "arn:aws:batch:eu-west-1:655100936961:job-definition/some-job-definition:1" -> (known after apply)
      ~ container_properties  = jsonencode(
          ~ {
                command              = []
              ~ environment          = [
                  + {
                      + name  = "SOME_VARIABLE"
                      + value = ""
                    },
                ]
                image                = "<some_image>"
                memory               = 8192
              - mountPoints          = [] -> null
              - resourceRequirements = [] -> null
              - secrets              = [] -> null
              - ulimits              = [] -> null
                vcpus                = 8
              - volumes              = [] -> null
            } # forces replacement
        )
      ~ id                    = "arn:aws:batch:eu-west-1:655100936961:job-definition/some-job-definition:1" -> (known after apply)
        name                  = "some-job-definition"
      - parameters            = {} -> null
      - platform_capabilities = [] -> null
        propagate_tags        = false
      ~ revision              = 1 -> (known after apply)
        type                  = "container"

        retry_strategy {
            attempts = 3
        }
    }
```

### Expected Behavior

The change should not be reported when planning as nothing has changed in HCL.

### Actual Behavior

The change is reported when planning.

### Steps to Reproduce

1. `terraform plan`

**Comment by ewbankkit** [comment]
@Limess Thanks for raising this issue.
Environment variables with no corresponding values are allowed through the AWS Batch API but it seems that the way to create a job definition with an empty environment variable is to not specify the `value` at all:

```hcl
resource "aws_batch_job_definition" "job-definition" {
  name = "some-job-definition"
  type = "container"
  retry_strategy {
    attempts = 3
  }
  container_properties = jsonencode(
    {
      "command" : [],
      "image" : "<some_image>",
      "memory" : 8192,
      "vcpus" : 8,
      "environment" : [
        {
          "name" : "SOME_VARIABLE"
        },
      ]
    }
  )
}
```

**Comment by Limess** [comment]
Interesting, I'd still expect terraform to not change the value - I'm not 100% sure on the behaviour at batch runtime when something is unset vs set to an empty string. Locally this difference (missing vs "") did change the semantics of our JVM based application code, for example.

**Comment by ewbankkit** [comment]
@Limess It's actually not Terraform that changes the value but the AWS Batch service. The empty value is sent on creation of the job definition but when the job definition is read back, no key (or value) is returned.
This behavior is similar to some other AWS services where sending an environment variable with a blank value is equivalent to deleting that environment variable.
