### ISSUE TITLE
default_tags interfere with other provider configs

### ISSUE THREAD

**Issue by pschulten** [hashicorp/terraform-provider-aws#19467]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
terraform v0.15.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.38.0
```
### Affected Resource(s)

n/a

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  region = var.default_region
  default_tags {
    tags = {
      taga = "a",
      tagb = "b",
    }
  }
}

provider "kubernetes" {
  config_context_cluster = var.cluster_name
  client_certificate     = module.master.kubeconfig.certificate
  client_key             = module.master.kubeconfig.private_key
  insecure               = true
  host                   = module.master.api_endpoint_no_dns
}
```

### Expected Behavior

`terraform plan` works like without `default_tags`

### Actual Behavior

```
Error: Get "http://localhost/api/v1/namespaces/default/serviceaccounts/vault-token-reviewer": dial tcp [::1]:80: connect: connection refused
```

the `host` attribute of our kubernetes provider is no longer taken into account

### Important Factoids

Uncommenting/Deleting the `default_tags` block fixes the issue

**Comment by anGie44** [comment]
Hi @pschulten , thank you for raising this issue. Do you mind providing which version of the kubernetes provider you are working with as well? 

I'm wondering if this open issue might be related https://github.com/hashicorp/terraform-provider-kubernetes/issues/1272 but may be too soon to tell.

**Comment by pschulten** [comment]
I'm using `hashicorp/kubernetes v2.2.0`

I played around with it again today. The `host` value is computed from a datasource (in a very hacky way):
 ```
 data "aws_network_interfaces" "hack" {
  filter {
    name   = "description"
    values = ["ELB ${aws_lb.kube-controller_nlb.arn_suffix}"]
  }
}

data "aws_network_interface" "hack" {
  id = flatten(data.aws_network_interfaces.hack.ids)[0]
}

output "api_endpoint_no_dns" {
  value = "https://${data.aws_network_interface.hack.private_ip}"
}
```

it was introduced to avoid DNS propagation timing issues. If I change the implementation back to the "proper" way (using a `resource`!):
```
output "api_fqdn" {
  value = aws_route53_record.lb_record.fqdn
}
```
and using the fqdn, setting `default_tags` works as expected.

The `datasource` value is not known before apply  and I guess terraform falls back to default `host` value because of this.

This is a very edgy case, so please close the issue, if you want. It's still unclear, why this works when not using `default_tags`, though.
