### ISSUE TITLE
Lakeformation table permissions need to be alphabetically ordered - otherwise aws_lakeformation_permissions stay out of sync

### ISSUE THREAD

**Issue by chrisbulgaria** [hashicorp/terraform-provider-aws#19465]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

3.42

* aws_lakeformation_permissions

### Terraform Configuration Files

```hcl

resource "aws_lakeformation_permissions" "db_perm" {
  count       = var.is_ext == false ? 1 : 0
  principal   = var.read_group
  permissions = ["SELECT","DESCRIBE" ]


  table {
    database_name       = "${var.db_name}_db"
    wildcard = true
  }
}

```

### Expected Behavior

replanning after apply doesnt show changes

### Actual Behavior

 module.database["grp2"].aws_lakeformation_permissions.db_perm[0] must be replaced
-/+ resource "aws_lakeformation_permissions" "db_perm" {
      ~ id                            = "466990021" -> (known after apply)
      ~ permissions                   = [ # forces replacement
          - "DESCRIBE",
            "SELECT",
          + "DESCRIBE",
        ]
      ~ permissions_with_grant_option = [] -> (known after apply)

### Steps to Reproduce

apply above resource and plan again

**Comment by YakDriver** [comment]
@chrisbulgaria Thanks for raising this. A PR to fix this is awaiting review.
