### ISSUE TITLE
Query in redirect block of resource aws_lb_listener_rule can no longer be empty

### ISSUE THREAD

**Issue by ballock** [hashicorp/terraform-provider-aws#19475]
After commit b3c79307cc06fd4f3acbf451b045af737348a0e4 it is no longer possible to create an aws_lb_listener_rule that redirects to another URL and skips the query entirely. It used to be possible to create a "" query. A null query field defaults to "#{query}", which forwards the ?query=string to the new website. Skipping the query value does the same.

### Terraform CLI and Terraform AWS Provider Version

Tested with Terraform 0.15.4. Affected AWS Provider versions from 3.40 to git master.

### Affected Resource(s)

* aws_lb_listener_rule

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_lb_listener_rule" "my_redirect_rule" {
  listener_arn = aws_lb_listener.my_listener.arn
  priority     = 1

  condition {
    host_header {
      values = ["old.example.com"]
    }
  }

  action {
    type             = "redirect"

    redirect {
      protocol    = "HTTPS"
      port        = "443"
      host        = "new.example.com"
      path        = "/"
      query       = ""
      status_code = "HTTP_301"
    }

  }
}
```
### Expected Behavior

The query field in redirect should be set to empty.

### Actual Behavior

```
│ Error: expected length of action.0.redirect.0.query to be in the range (1 - 128), got 
│ 
│   with aws_lb_listener_rule.my_redirect_rule,
│   on example_rules.tf line 19, in resource "aws_lb_listener_rule" "my_redirect_rule":
│  19:       query       = ""
```

### Steps to Reproduce

1. `terraform apply`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ewbankkit** [comment]
@ballock Thanks for raising this issue.
It has already been noticed in #19376. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
