### ISSUE TITLE
aws_msk_cluster does not provide IPs as 

### ISSUE THREAD

**Issue by marafa-sugarcrm** [hashicorp/terraform-provider-aws#19473]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

While attaching the brokers to an aws_lb_target_group_attachment i discovered there was no direct method of using the aws provider to grab the IPs of the brokers in an MSK cluster

### New or Affected Resource(s)

* aws_msk_cluster

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* N/A

**Comment by ewbankkit** [comment]
@marafa-sugarcrm Thanks for raising this issue.
It has already been noticed in #11085. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
