### ISSUE TITLE
The provider hashicorp/aws does not support resource type "aws_synthetics_canary"

### ISSUE THREAD

**Issue by amit601** [hashicorp/terraform-provider-aws#19481]
When i run terraform plan/validate, it gives the error

```
alcon@falcon:~/Documents/Amit_docs/canary$ terraform plan
provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Enter a value: ap-south-1

╷
│ Error: Invalid resource type
│
│   on canary.tf line 1, in resource "aws_synthetics_canary" "some":
│    1: resource "aws_synthetics_canary" "some" {
│
│ The provider hashicorp/aws does not support resource type
│ "aws_synthetics_canary".


```

![image](https://user-images.githubusercontent.com/56498997/119250513-31494d80-bbbe-11eb-94f6-743d3faa6786.png)

AWS CLI is working fine with command 
**aws synthetics describe-canaries**

Any help will be appreciated.

**Comment by ewbankkit** [comment]
@amit601 Thanks for raising this issue 👏.
The `aws_synthetics_canary` resource was added in [**v3.28.0**](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3280-february-12-2021) of the Terraform AWS Provider.
Which version of the provider are you using for your configuration?

**Comment by amit601** [comment]
My bad, 
AWS provider was not updated.

Thanks @ewbankkit , it worked.
