### ISSUE TITLE
Error Removing LBListenerCertificate: Default Certificate Cannot be removed

### ISSUE THREAD

**Issue by akanshajain1** [hashicorp/terraform-provider-aws#19495]
I am using the certificate domain to fetch the acm certificate arn and use it in lb listener certificate.

data "aws_acm_certificate" "alb_certificate_domain"{
domain = var.certificate_domain
statuses = ["ISSUED"]
types       = ["PRIVATE"]
}

But at the time of terraform destroy I am getting error:
Error removing LB Listener certificate OperationNotPermitted: Default Certificate cannot be removed.

**Comment by breathingdust** [comment]
Hi @akanshajain1! 👋  Can you please resubmit this issue using the issue template provided? Without all of the fields provided our engineers and community will not have the information required to help you out. Thanks!
