### ISSUE TITLE
r/aws_ec2_capacity_reservation outpost_arn attribute support

### ISSUE THREAD

**Issue by FireballDWF** [hashicorp/terraform-provider-aws#19509]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

add outpost_arn as a new attribute 

### New or Affected Resource(s)

* aws_ec2_capacity_reservation

### Potential Terraform Configuration

```hcl
 outpost_arn -   The Amazon Resource Name (ARN) of the Outpost on which to create the Capacity Reservation.
```

### References

* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateCapacityReservation.html
* https://aws.amazon.com/about-aws/whats-new/2021/05/aws-outposts-launches-support-for-ec2-capacity-reservations/

**Comment by richardjennings** [comment]
@FireballDWF I am interested in working on this. How can it be tested? Outpost appears to be a non trivial financial commitment.
