### ISSUE TITLE
Lambda Function: "package_type" variable is redundant

### ISSUE THREAD

**Issue by andrewsavino1** [hashicorp/terraform-provider-aws#19508]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
The var "package_type" has two options - "Image" and "Zip".  The correct value of this variable is known by whether the user specified an `image_uri` (Image), or `s3_bucket`/`filename` (Zip).  `package_type` currently defaults to `Zip`, which can create confusing error messages if the user is trying to create a Docker Image Lambda.

### New or Affected Resource(s)

* aws_lambda_function

### Potential Terraform Configuration

(as-is, omitting the `package_type` input)

### References

It may also be helpful to add additional validations, as proposed in https://github.com/hashicorp/terraform-provider-aws/issues/16515.

* #0000

**Comment by ewbankkit** [comment]
@andrewsavino1 Thanks for raising this issue.
Yes, a plan-time validation (via `CustomizeDiff`) would be the way to go here.

**Comment by andrewsavino1** [comment]
Makes sense, I can make a PR to add that plan-time validation.
