### ISSUE TITLE
Publishing dimensions from JSON log events or from space-delimited log events using aws_cloudwatch_log_metric_filter

### ISSUE THREAD

**Issue by alex-polbach-vp** [hashicorp/terraform-provider-aws#19521]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
According to https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html#logs-metric-filters-dimensions, it is possible to publish dimensions with metrics from JSON log events or from space-delimited log events, but is not supported by aws_cloudwatch_log_metric_filter.

### New or Affected Resource(s)

* aws_cloudwatch_log_metric_filter

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html#logs-metric-filters-dimensions

**Comment by ewbankkit** [comment]
[AWS SDK v1.38.46](https://github.com/aws/aws-sdk-go/releases/tag/v1.38.46).

**Comment by justinretzolk** [comment]
Hey @alex-polbach-vp 👋 It looks like this functionality was introduced in [AWS Provider version `3.44.0`](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3440-june-03-2021), so I'll mark this issue as closed. If you feel I've done this in error, please do let me know.
