### ISSUE TITLE
Terraform not deleting rds autoscaled instances

### ISSUE THREAD

**Issue by khvr** [hashicorp/terraform-provider-aws#19536]
I am trying to create a rds aurora global database with autoscaling enabled based on CPU threshold but when I try to destroy the autoscaled instances that are not deleted by terraform is this a bug? Is there a workaround or am I missing something?

I used this module https://registry.terraform.io/modules/umotif-public/rds-aurora/aws/latest
which uses aws_appautoscaling_target and aws_appautoscaling_policy resources

But the autoscaled rds is left hanging and the writer and reader instances are deleted

Error message: Error: error deleting RDS Cluster InvalidDBClusterStateFault: Cluster cannot be deleted, it still contains DB instances in non-deleting state. status code: 400, request id: b62f33ee-57d8-4887-9cad-3cbf6229b4ac

Error: Error deleting DB parameter group: InvalidDBParameterGroupState: One or more database instances are still members of this parameter group my-parameter-group, so the group cannot be deleted status code: 400, request id: 8a501e66-39e5-4365-ba33-7667894b9cf6

**Comment by circa10a** [comment]
I've seen similar behavior recently where terraform says `aws_autoscaling_groups` are deleted, but they in fact weren't

- Terraform version `0.14.11`
- terraform-provider-aws version `3.42.0`
