### ISSUE TITLE
aws_ecs_task_definition always displays “has been changed”

### ISSUE THREAD

**Issue by acdha** [hashicorp/terraform-provider-aws#19549]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.42.0
+ provider registry.terraform.io/hashicorp/dns v3.1.0
+ provider registry.terraform.io/hashicorp/http v2.1.0
```

### Affected Resource(s)

* aws_ecs_task_definition

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ecs_task_definition" "…" {
  tags                     = merge(local.tags, { Service = "…" })
  family                   = "…-${var.environment}"
  requires_compatibilities = ["FARGATE"]
  task_role_arn            = aws_iam_role.task.arn
  execution_role_arn       = aws_iam_role.execution.arn
  network_mode             = "awsvpc"
  cpu                      = 4096
  memory                   = 8192

  volume {
    name = "collection-storage"
    efs_volume_configuration {
      file_system_id     = var.collection_efs_file_system_id
      transit_encryption = "ENABLED"
    }
  }

  container_definitions = templatefile(
    "${path.module}/task-definitions/….json",
    {
      "REGION"          = var.region
      "CONTAINER_NAME"  = "…",
      "ENVIRONMENT"     = var.environment,
      "SENTRY_DSN"      = var.sentry_dsn,
      "CONTAINER_IMAGE" = "${aws_ecr_repository.this["…"].repository_url}:${lookup(var.container_tags, "…", "la
est")}",
      "LOG_GROUP"       = aws_cloudwatch_log_group.this["…"].name,
      "SERVICE_NAME"    = "…"
    }
  )
}
```

### Expected Behavior

Terraform should show that the resource has not changed from the definition

### Actual Behavior

```
# module.search.aws_ecs_task_definition.… has been changed
resource "aws_ecs_task_definition" "…" {
    id                       = "…"
    tags                     = {
        "Service" = "…"
    }
    # (11 unchanged attributes hidden)
  + volume {
      + name = "collection-storage"
      + efs_volume_configuration {
          + file_system_id          = "fs-ee6bf06d"
          + root_directory          = "/"
          + transit_encryption      = "ENABLED"
          + transit_encryption_port = 0
        }
    }
  - volume {
      - name = "collection-storage" -> null
      - efs_volume_configuration {
          - file_system_id     = "fs-ee6bf06d" -> null
          - root_directory     = "/" -> null
          - transit_encryption = "ENABLED" -> null
        }
    }
}
```

### Steps to Reproduce

1. `terraform apply`

**Comment by markbaird** [comment]
Also seeing this in `terraform plan` in addition to `terraform apply`. And in Terraform 1.0 it is also showing in the "Objects have changed outside of Terraform" section.

It appears to be because the EFS `transit_encryption_port` is `null` or otherwise undefined in the template, but appears to be stored as `0` in the state file.

**Comment by InbarRose** [comment]
I am still seeing this issue exactly as it appears above.
using `hashicorp/terraform:1.1.2`

**Comment by huw0** [comment]
To follow up on the code referenced by @wichert in #18010...

https://github.com/hashicorp/terraform-provider-aws/blob/a4ae7730cc55121113c5258e424bcb54edfd50f9/internal/service/ecs/task_definition.go#L1001-L1003

I don't think that `root_directory` should ever be reset like this.

According to the documentation, the root_directory is valid with or without an access point. "_If an access point is specified, the root directory value will be relative to the directory set for the access point. If specified, transit encryption must be enabled in the EFSVolumeConfiguration._"

**Comment by stewartcampbell** [comment]
I thought I was having the same problem after seeing `transit_encryption_port` going from `0` to `null`, however after correcting an env var that was being set to `null`, the problem went away.

Not saying this will solve everyone's issue, but hopefully will help someone who hits this issue.

**Comment by odie5533** [comment]
I made a PR for testing. The documentation is conflicted on whether you can specify a relative root_directory or not. The [AWS doc says](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_EFSVolumeConfiguration.html)

> If an EFS access point is specified in the authorizationConfig, the root directory parameter must either be omitted or set to / which will enforce the path set on the EFS access point.

But the [Python API doc says](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ecs/AuthorizationConfig.html)

> If an access point is specified, the root directory value will be relative to the directory set for the access point. 

And the [TF doc erroneously says](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition)

> If an access point is specified, the root directory value will be relative to the directory set for the access point.

When I manually try, if I pick an Access Point ID, it greys out the box for Root Directory.

It seems like the official doc says you can't specify the directory this way. Did we used to be able to? Does it still work with the CLI?

**Comment by amh-mw** [comment]
I ran this question through our AWS support contract. Response:

> When you create an access point, you can choose to specify a (Root directory path) for the access point. If you do not specify one, the root directory of EFS will be used. Meaning when you mount EFS via access point and there is no (Root directory path) specified. The EFS will be mounted in the root path of EFS. See example in the below link:
> 
> Enforcing a root directory with an access point - https://docs.aws.amazon.com/efs/latest/ug/efs-access-points.html#enforce-root-directory-access-point
> 
> Because EFS access point are created for existing file systems, you can enforce which path/folder inside your EFS you want the access point to use as (Root directory path). If your access point does not specify anything, this means your access point will be mounted the same as mounting the file system in root path.
> 
> Now looking at information you shared: \"If an EFS access point is specified in the authorizationConfig, the root directory parameter must either be omitted or set to / which will enforce the path set on the EFS access point.\" This means if you omit root directory parameter or set to / this will enforce the config you already set for your existing access point.
>
> The second link says: \"If an access point is specified, the root directory value will be relative to the directory set for the access point.\" This also means the config you already have for (Root directory path) when you created the access point will be used.
> 
> Both links are referring to the same thing and are both correct. If you go to EFS console and create an access point, you will see that you have an option to specify (Root directory path) or you can live it blank to use the EFS root path. Both link are saying any config you specify on the access point will be used.

**Comment by amh-mw** [comment]
Workaround? Pick a different transit_encryption_port for each EFS mount using the range proscribed in [efs-utils.conf#L35-L37](https://github.com/aws/efs-utils/blob/71058a0fed32311e67403e18ca715d0283f94282/dist/efs-utils.conf#L35-L37)?
```
# Define the port range that the TLS tunnel will choose from
port_range_lower_bound = 20049
port_range_upper_bound = 21049
```

**Comment by spider-network** [comment]
+1
