### ISSUE TITLE
AWS CodeArtifact repository multiple upstreams

### ISSUE THREAD

**Issue by trinaryouroboros** [hashicorp/terraform-provider-aws#19547]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS CodeArtifact supports multiple upstreams for a repository. For example, you can make a repository and add both local and public repositories in the upstream configuration.

Currently it appears the resource_aws_codeartifact_repository.go only supports a hard set single upstream with key repository_name

According to the documentation this can be a list. However, it doesn't appear there's any way to make a list of upstreams with this method.

Documentation also quotes the following: "A list of upstream repositories to associate with the repository. The order of the upstream repositories in the list determines their priority order when AWS CodeArtifact looks for a requested package version."

How can one define a list of upstreams with priority using this code?

### New or Affected Resource(s)

https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_codeartifact_repository.go#L51-L63

### Potential Terraform Configuration

Desired configuration example:

```
resource "aws_codeartifact_domain" "example_domain" {
  domain = "example"
}

resource "aws_codeartifact_repository" "mylocalrepo" {
  repository = "mylocalrepo"
  domain     = aws_codeartifact_domain.example.domain
}

resource "aws_codeartifact_repository" "npm_public" {
  repository = "npm-store"
  domain     = aws_codeartifact_domain.example.domain

  external_connections {
    external_connection_name = "public:npmjs"
  }
}

resource "aws_codeartifact_repository" "npm_composite" {
  repository = "npm-composite"
  domain     = aws_codeartifact_domain.example.domain

  upstream = {
     repositories = [
      aws_codeartifact_repository.mylocalrepo.repository,
      aws_codeartifact_repository.npm_public.repository
     ]
  }
}
```

### References

https://github.com/hashicorp/terraform-provider-aws/issues/13714

**Comment by ewbankkit** [comment]
@trinaryouroboros Thanks for raising this issue.

```hcl
resource "aws_codeartifact_repository" "npm_composite" {
  repository = "npm-composite"
  domain     = aws_codeartifact_domain.example.domain

  upstream {
    repository_name = aws_codeartifact_repository.mylocalrepo.repository
  }

  upstream {
    repository_name = aws_codeartifact_repository.npm_public.repository
  }
}
```

should do what you are looking for.

**Comment by trinaryouroboros** [comment]
Thank so much @ewbankkit !
