### ISSUE TITLE
ECS capacity provider resource forces new resource when changing `target_capacity`

### ISSUE THREAD

**Issue by rue-nsilverman** [hashicorp/terraform-provider-aws#19542]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/aws v3.42.0
```

### Affected Resource(s)

- aws_ecs_capacity_provider

### Terraform Configuration Files

```hcl
resource "aws_ecs_capacity_provider" "pool_capacity" {
  name     = "general-ecs-pool"

  auto_scaling_group_provider {
    auto_scaling_group_arn         = aws_autoscaling_group.ecs_pool.arn
    managed_termination_protection = "ENABLED"

    managed_scaling {
      maximum_scaling_step_size = 10
      minimum_scaling_step_size = 1
      status                    = "ENABLED"
      instance_warmup_period    = 60
      target_capacity           = 75
    }
  }
  tags = { Name = "general-ecs-pool" }
}
```

### Expected Behavior

The AWS provider should update in place the `target_capacity` for an existing capacity provider. 

### Actual Behavior

The provider forces a new resource and attempts to delete and re-create the existing capacity provider. When applying this change, the AWS provider will timeout and fail if you are running tasks on any instance managed by the capacity provider. The error it returns after failing and timing out is:

```
Error: error waiting for ECS Capacity Provider ([redacted_capacity_provider_arn]) to delete: timeout while waiting for state to become 'INACTIVE' (last state: 'ACTIVE', timeout: 20m0s)
```

Below is an example plan output:

```
  # module.fleet-ecs.aws_ecs_capacity_provider.pool_capacity must be replaced
-/+ resource "aws_ecs_capacity_provider" "pool_capacity" {
      ~ arn      = "[redacted_capacity_provider_arn]" -> (known after apply)
      ~ id       = "[redacted_capacity_provider_arn]" -> (known after apply)
        name     = "general-ecs-pool"
        tags     = {
            "Name" = "general-ecs-pool"
        }
        # (1 unchanged attribute hidden)

      ~ auto_scaling_group_provider {
            # (2 unchanged attributes hidden)

          ~ managed_scaling {
              ~ target_capacity           = 75 -> 100 # forces replacement
                # (4 unchanged attributes hidden)
            }
        }
    }
```

### Steps to Reproduce

1. using the above code example and an associated ASG, plan and apply to create a capacity provider with a specific `target_capacity`.
2. change the `target_capacity`.
3. terraform plan. It will show you that it intends to re-create the capacity provider by forcing a new resource.
4. terraform apply. It will attempt to delete and re-create the existing capacity provider. This will timeout and fail if you are running instances on any instance in the capacity provider.

### Important Factoids

It looks like the go AWS SDK has already implemented [UpdateCapacityProvider](https://docs.aws.amazon.com/sdk-for-go/api/service/ecs/#ECS.UpdateCapacityProvider) as of [v1.35.34](https://github.com/aws/aws-sdk-go/releases/tag/v1.35.34) so it should be possible to include in the AWS provider for terraform already.

**Comment by ewbankkit** [comment]
@rue-nsilverman Thanks for raising this issue.
It has already been noticed in #16943. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by rue-nsilverman** [comment]
@ewbankkit Ah, perfect, I could not find an existing issue with the search terms I was using, thanks!
