### ISSUE TITLE
aws_default_vpc_dhcp_options does not work when shared VPCs are present

### ISSUE THREAD

**Issue by oblogic7** [hashicorp/terraform-provider-aws#19558]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

v0.15.4

### Affected Resource(s)

* aws_default_vpc_dhcp_options

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource aws_default_vpc_dhcp_options default {}
```

### Debug Output

https://gist.github.com/oblogic7/6f257461e1e054084613b60c50c606fb

### Expected Behavior

Since no option is available on `aws_default_vpc_dhcp_options` to scope the lookup to a specific vpc_id or owner_id, then shared resources from other accounts should not be included in the lookup.

### Actual Behavior

```
│ Error: Multiple default DHCP Options Sets found
│ 
│   with module.vpc.aws_default_vpc_dhcp_options.default,
│   on ../../vpc/vpc.tf line 13, in resource "aws_default_vpc_dhcp_options" "default":
│   13: resource aws_default_vpc_dhcp_options default {}
```

### Steps to Reproduce

1. Share VPC resources between multiple accounts
1. `terraform apply`

### Important Factoids

Manual import of correct DHCP options set is a valid work around.

### References

It appears that options to scope this lookup existed on older versions of the provider according to this issue: https://github.com/hashicorp/terraform-provider-aws/issues/6630

* #0000

**Comment by eissko** [comment]
The same on my side. Any workaround?
