### ISSUE TITLE
aws_cloudwatch_metric_alarm metric_query fields should be validated

### ISSUE THREAD

**Issue by cfstras** [hashicorp/terraform-provider-aws#19567]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `aws_cloudwatch_metric_alarm` resource permits adding multiple `metric_query` entries which can be combined to create complex alarms.
However, there seems to be no validation on the individual fields.

For example, [the `stat` field](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_metric_alarm#stat) is documented to support `SampleCount`, `Average`, `Sum`, `Minimum`, `Maximum`, but does not validate this value. If you get it wrong, AWS unhelpfully tells you `Creating metric alarm failed: ValidationError: Invalid metrics list` without specifying any details.

### New or Affected Resource(s)

* aws_cloudwatch_metric_alarm

### Potential Terraform Configuration

```hcl
resource "aws_cloudwatch_metric_alarm" "errors" {
  alarm_name        = "alarm_errors"
  alarm_description = "..."

  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = "2"
  threshold           = 10

  metric_query {
    id = "m1"

    label       = "ErrorRate"
    expression  = "errs + userErrs"
    return_data = true
  }

  metric_query {
    id = "errs"
    metric {
      metric_name = "5xxErrorRate"
      namespace   = "AWS/CloudFront"
      period      = "300"
      stat        = "Avg" # Error on `terraform apply`. Should already error on `terraform validate`
    }
  }
  metric_query {
    id = "userErrs"
    metric {
      metric_name = "4xxErrorRate"
      namespace   = "AWS/CloudFront"
      period      = "300"
      stat        = "Average"
    }
  }
}
```

### References

* Issue https://github.com/hashicorp/terraform-provider-aws/issues/8421 ran into the error with "Average"

**Comment by philnichol** [comment]
Hi :wave: @cfstras ,  I would like to have a crack at this if that's OK with you?

**Comment by philnichol** [comment]
Ah nice one @DrFaust92, all yours 😄
