### ISSUE TITLE
Amazon S3 Bi Directional Replication via Replica Modification Sync and Delete markers

### ISSUE THREAD

**Issue by Kanikamiglani31** [hashicorp/terraform-provider-aws#19560]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_s3_bucket

### Potential Terraform Configuration

```hcl
      source_selection_criteria {
        sse_kms_encrypted_objects {
          enabled = "true"
        }
        replica_modifications {
          enabled = "true"
        }
      }
```

### References

* #0000

**Comment by ewbankkit** [comment]
@Kanikamiglani31 Thanks for raising this issue.
It has already been noticed in #16539 and #16250. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by Kanikamiglani31** [comment]
Sure @ewbankkit .
Also meanwhile we can achieve this using `local-exec` and `template_file` in terraform with aws-cli.

The solution is present in the answer below :
https://stackoverflow.com/questions/67729643/how-can-we-enable-amazon-s3-replication-modification-sync-in-terraform/67792274#67792274
