### ISSUE TITLE
aws_autoscaling_group - setting suspended processes to empty list attaches all processes instead

### ISSUE THREAD

**Issue by pscadiz** [hashicorp/terraform-provider-aws#1957]
### Terraform Version
v0.10.4

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_autoscaling_group

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
variable "load_balancers" {
  default = ""
}

variable "target_group_arns" {
  default = ""
}

variable "suspended_processes" {
  default = ""
}

resource "aws_autoscaling_group" "autoscaling_group" {
  [...]
  load_balancers       = ["${split(",",var.load_balancers)}"]
  target_group_arns    = ["${split(",",var.target_group_arns)}"]
  suspended_processes  = ["${split(",",var.suspended_processes)}"]
}
```

### Expected Behavior
terraform plan outputs the following:
```
aws_autoscaling_group.autoscaling_group
      load_balancers.#:      "0" => "1"
      load_balancers.0:      "" => ""
      suspended_processes.#: "0" => "1"
      suspended_processes.0: "" => ""
      target_group_arns.#:   "0" => "1"
      target_group_arns.0:   "" => ""
```

Supposedly an update would not change anything. Will not set load balancers, target groups or suspended processes

### Actual Behavior
rerunning terraform plan after applying outputs:
```
aws_autoscaling_group.autoscaling_group
      load_balancers.#:               "0" => "1"
      load_balancers.0:               "" => ""
      suspended_processes.#:          "9" => "1"
      suspended_processes.0:          "" => ""
      suspended_processes.1107475368: "AddToLoadBalancer" => ""
      suspended_processes.2115719875: "Launch" => ""
      suspended_processes.2282213524: "ScheduledActions" => ""
      suspended_processes.2954045122: "RemoveFromLoadBalancerLowPriority" => ""
      suspended_processes.3905370587: "AlarmNotification" => ""
      suspended_processes.3999558323: "Terminate" => ""
      suspended_processes.4273030806: "ReplaceUnhealthy" => ""
      suspended_processes.658532077:  "AZRebalance" => ""
      suspended_processes.997436260:  "HealthCheck" => ""
      target_group_arns.#:            "0" => "1"
      target_group_arns.0:            "" => ""
```

As above, target groups and load balancers remain empty, but suspended processes have apparently added all possible processes in suspended_processes

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`
3. `terraform plan`

**Comment by dmnavarro** [comment]
Experiencing the same thing. Kindly fix this

**Comment by deanillfeld** [comment]
I was able to work around this with the following;

`suspended_processes = ["${compact(split(",", lookup(var.workers[count.index], "suspended_processes", "")))}"]`

**Comment by wonderphil** [comment]
Any update on when this will be fixed??

**Comment by pcp-tcp** [comment]
Really could use an update on this

**Comment by pol1000000** [comment]
rly strange behavior :confused: 

I was able to handle this using v0.12.29 and the below example:
[vars](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/master/variables.tf#L243-L247) and [asg](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/master/main.tf#L90)
