### ISSUE TITLE
aws_glue_catalog_database with  target_database but without location_uri stays permanently out of sync

### ISSUE THREAD

**Issue by chrisbulgaria** [hashicorp/terraform-provider-aws#19585]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

3.42
### Affected Resource(s)

* aws_glue_catalog_database

### Terraform Configuration Files

```hcl
resource "aws_glue_catalog_database" "ext_db" {
    name  = "${var.db_name}_db"
    target_database {
      catalog_id    = var.ext_acct
      database_name = var.ext_db
    }
}

```

### Debug Output

Plan:

  ~ resource "aws_glue_catalog_database" "ext_db" {
        id           = "xxxxx"
      - location_uri = "yyyyyy" -> null
        name         = "zzzz"
        # (3 unchanged attributes hidden)
        # (1 unchanged block hidden)
    }

### Expected Behavior

No change detected

### Actual Behavior

It seems to pull in the location_uri from the target_db (which is not in the resource def) and then stays permanently out of sync.

target_database support was recently added:
https://github.com/hashicorp/terraform-provider-aws/issues/15296

**Comment by DrFaust92** [comment]
seems like `location_uri` needs to be computed here. as a workaround you can add the following block meanwhile:

```
lifecycle {
  ignore_changes = [location_uri]
}
```
