### ISSUE TITLE
aws_ecs_service -> launch_type needs to have EXTERNAL added

### ISSUE THREAD

**Issue by nicwise** [hashicorp/terraform-provider-aws#19586]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With the launch of ECS Anywhere, there is a new `launch_type` - `EXTERNAL` as well as `EC2` and `FARGATE`. This is missing from either Terraform/AWS or the AWS API.

### New or Affected Resource(s)

* aws_ecs_service

### Potential Terraform Configuration

```hcl
resource "aws_ecs_service" "external_ups" {
  name    = "foo"

  cluster              = aws_ecs_cluster.cluster.id
  task_definition = "..."

  launch_type = "EXTERNAL" <------

  scheduling_strategy = "DAEMON"

}
```

Note that the task definition may also need `EXTERNAL` in it's `requiresCompatibilities` key

```
{
	"requiresCompatibilities": [
		"EXTERNAL"
	],
```
### References

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_types.html

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-anywhere.html

```
Amazon ECS capacity providers aren't supported. To create a service or run a standalone task on your external instances, use the EXTERNAL launch type.
```

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-anywhere-runtask.html

**Comment by gdavison** [comment]
Thanks for raising this, @nicwise. We've merged #19557 to address this and expect to release it soon.
