### ISSUE TITLE
aws_vpc_ipv4_cidr_block_association: cidr block 100.64.0.0/10 should be allowed as is it commonly used for EKS deployments

### ISSUE THREAD

**Issue by ecerulm** [hashicorp/terraform-provider-aws#19595]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.42.0
```

### Affected Resource(s)

* aws_vpc_ipv4_cidr_block_association

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_vpc_ipv4_cidr_block_association" "eks_vpc_secondary_cidr" {
  vpc_id = "anyvpcid"
  cidr_block = "100.64.0.0/10"
}
```

### Expected Behavior

I was expecting to be able to associate the 100.64.0.0/10 cidr / ip range to my VPC.
This range is supported by AWS  and it's usually used with EKS as the ip range for pods: 
*  [Amazon EKS now supports additional VPC CIDR blocks](https://aws.amazon.com/about-aws/whats-new/2018/10/amazon-eks-now-supports-additional-vpc-cidr-blocks/)
* [VPC and subnets](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.html#vpc-resize)
  * Permitted CIDR block associations: Any publicly routable IPv4 CIDR block (non-RFC 1918), **,or a CIDR block from the 100.64.0.0/10 range.**

### Actual Behavior

It refuses to add 100.64.0.0/10 because the network prefix /10 is not allowed...
```
╷
│ Error: expected "cidr_block" to contain a network Value with between 16 and 28 significant bits, got: 10
│ 
│   with aws_vpc_ipv4_cidr_block_association.eks_vpc_secondary_cidr,
│   on main.tf line 170, in resource "aws_vpc_ipv4_cidr_block_association" "eks_vpc_secondary_cidr":
│  170:   cidr_block = "100.64.0.0/10"

```

### Steps to Reproduce

1. terraform plan (with a aws_vpc_ipv4_cidr_block_association that uses the 100.64.0.0/10 block)

### Important Factoids

Creating a VPC with a secondary cidr block 100.64.0.0/10 for AWS EKS  [CNI custom networking](https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html)

### References

* #0000

**Comment by gdavison** [comment]
Implementation note: see the table "IPv4 CIDR block association restrictions" at https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.html#vpc-resize

**Comment by ecerulm** [comment]
> Implementation note: see the table "IPv4 CIDR block association restrictions" at https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.html#vpc-resize

Yes, this is the document I linked as "VPC and subnets" in the body of the issue. 
I think the key part of the document is actually the section titled [IPv4 CIDR block association restrictions](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.html#add-cidr-block-restrictions)
https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.html#add-cidr-block-restrictions
where it says:

> **Permitted CIDR block associations**
> Any other CIDR from the 10.0.0.0/8 range that's not restricted.
> Any publicly routable IPv4 CIDR block (non-RFC 1918), **or a CIDR block from the 100.64.0.0/10 range.**

**Comment by philnichol** [comment]
@gdavison @ecerulm apologies if this is incorrect, but I had a look at this, and unless I'm mistaken it appears the limit of max size of `/16` still applies.
Even via console, attempting anything larger than `100.46.0.0/16` fails with 
```
Failed to add IPv4 CIDR: 100.64.0.0/10
The CIDR '100.64.0.0/10' is invalid.
```
I think maybe that doc us just a bit misleading? Or their validation is incorrect?

**Comment by ecerulm** [comment]
I think you are right, it still a limit of  `/16` but it can be chosen from that `100.64.0.0/10` range. So `100.64.0.0/16`, `100.65.0.0/16`, `100.66.0.0/16`,...
