### ISSUE TITLE
terraform-aws-modules/terraform-aws-alb#160  This PR is merged. But not apply in terraform site

### ISSUE THREAD

**Issue by paikend** [hashicorp/terraform-provider-aws#19590]
### Description

 This PR is merged. But not apply in terraform site
 
`lambda_multi_value_headers_enabled` is null
 until the PR was megged

The changes were not reflected in the document.

### New or Affected Resource(s)

* /docs/providers/aws/d/alb_target_group.html 

### References

https://github.com/terraform-aws-modules/terraform-aws-alb/pull/160

**Comment by gdavison** [comment]
Hi @paikend, thanks for raising this. terraform-aws-modules/terraform-aws-alb is not maintained by this project, so the changes in that PR would not affect the AWS provider documentation. However, this is a helpful update to the provider documentation.
