### ISSUE TITLE
AWS WorkMail service - no documentation nor resource/data blocks

### ISSUE THREAD

**Issue by grodzik** [hashicorp/terraform-provider-aws#19607]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As mentioned in the referencecd pull request, AWS WorkMail service is integrated into Terraform AWS provider. However there is no documentation for it, it's not searchable [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/). Or maybe it's not ready yet and it still requires data and resource blocks to be coded? What's the status of support for AWS WorkMail? This one service is quite cruicial to me to be able to handle it via Terraform.

### References
New Service: WorkMail  ->  #11958

* #0000

**Comment by ewbankkit** [comment]
@grodzik Thanks for raising this issue.
#11958 made the changes required when any new AWS service is added to the provider but did not add any AWS WorkMail resources or data sources.
If you have suggestions for the resources/data sources that should be added, please go ahead and append them to this issue.

**Comment by grodzik** [comment]
Ok, so I misunderstood PR title. Anyway, I would  start with those:

Resources:
- aws_workmail_organization
- aws_workmail_user
- aws_workmail_group
- aws_workmail_alias
- aws_workmail_resource

Additional data block (including above as data blocks as well):
 - aws_workmail_mailbox

**Comment by khadersyed** [comment]
I started on `aws_workmail_organization` with this PR #23465
