### ISSUE TITLE
Support for checkpoint records (Report Batch Item Failure) on Lambda with Kinesis Stream

### ISSUE THREAD

**Issue by cvarjao** [hashicorp/terraform-provider-aws#19600]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has a feature for Optimizing batch processing with custom checkpoints in AWS Lambda which is currently not available via terraform.

* aws_lambda_event_source_mapping

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "aws_lambda_event_source_mapping" "kinesis" {
  event_source_arn  = aws_kinesis_stream.stream1
  function_name     = aws_lambda_function.lambda1
  parallelization_factor = 2
  starting_position = "LATEST"
  batch_size = 10000
  maximum_batching_window_in_seconds = 60
  function_response_types = [ "ReportBatchItemFailures" ]
}
```

### References

- https://aws.amazon.com/about-aws/whats-new/2020/12/aws-lambda-launches-checkpointing-for-amazon-kinesis-and-amazon-dynamodb-streams/
- https://aws.amazon.com/blogs/compute/optimizing-batch-processing-with-custom-checkpoints-in-aws-lambda/
### New or Affected Resource(s)
- https://docs.aws.amazon.com/lambda/latest/dg/API_CreateEventSourceMapping.html#SSS-CreateEventSourceMapping-request-FunctionResponseTypes
- https://docs.aws.amazon.com/cli/latest/reference/lambda/create-event-source-mapping.html
* #0000

**Comment by ewbankkit** [comment]
@cvarjao Thanks for raising this issue.
It has already been noticed in #16787. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
