### ISSUE TITLE
`aws_cloudwatch_event_target` input constantly detects whitespace diff in heredoc JSON

### ISSUE THREAD

**Issue by dimisjim** [hashicorp/terraform-provider-aws#19604]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

- terraform: `0.15.1`
- aws provider: `3.41`

### Affected Resource(s)

* aws_cloudwatch_event_target

### Terraform Configuration Files

```
resource "aws_cloudwatch_event_target" "ecs_scheduled_task" {
  rule     = aws_cloudwatch_event_rule.event_rule.name
  role_arn = var.scheduled_role_arn
  arn      = var.ecs_cluster_arn
  input    = <<-EOF
  {
    "taskRoleArn": "${var.task_role_arn}"
  }
  EOF

  ecs_target {
    task_definition_arn = aws_ecs_task_definition.td.arn
    task_count          = var.task_count
    platform_version    = var.platform_version
    launch_type         = "FARGATE"

    network_configuration {
      subnets         = var.subnets
      security_groups = var.security_groups
    }
  }
}
```

### Actual Behavior

I have changed nothing but terraform still thinks that there's a change in that resource:

```hcl
~ resource "aws_cloudwatch_event_target" "ecs_scheduled_task" {
        id             = "terraform-20210531191617686000000001"
      ~ input          = jsonencode( # whitespace changes
            {
                taskRoleArn = "arn:aws:iam::xxxxxxxxx:role/role-name"
            }
        )
```

### Expected Behavior

Show no diff

### References

Probably related issue:

* https://github.com/hashicorp/terraform-provider-aws/issues/12056

**Comment by ewbankkit** [comment]
I see this comment in the code

https://github.com/hashicorp/terraform-provider-aws/blob/07a311d92a916c85f503b33c525b3ebfec2a786a/aws/resource_aws_cloudwatch_event_target.go#L69-L75

even though the [AWS API reference](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_Target.html#eventbridge-Type-Target-Input) states

> Valid JSON text passed to the target.

**Comment by dimisjim** [comment]
So this means that this particular provider resource implementation is incorrect?
