### ISSUE TITLE
Tags not changing on aws_elasticache_cluster resource when using default_tags at provider level

### ISSUE THREAD

**Issue by krynczak** [hashicorp/terraform-provider-aws#19614]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With hashicorp aws provider version v.3.38.0 we were able to start tagging resources at the provider level. However, I noticed two problems when changing tags on a single-node Redis instance (`aws_elasticache_cluster`):

* 1. Adding new tags to the `tags` block which is inside `default_tags` at `provider "aws"` doesn't generate a configuration drift when running `terraform plan` and/or `terraform apply`, so the additional tag isn't added to the resource `aws_elasticache_cluster`.

* 2. Removing tags from a `tags` block which is inside `default_tags` at `provider "aws"` detect a drift in configuration when running `terraform plan` and/or `terraform apply`, and if you apply it even says that it succesfully removed the tag (ie. it changed to `null`), but the tag remains on the resource `aws_elasticache_cluster` after the `terraform apply` command finishes (you can see it on the AWS console).

Default tags is supported and mentioned on the `aws_elasticache_cluster` [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_cluster#tags)

### Terraform CLI and Terraform AWS Provider Version

```
➜ terraform -v
Terraform v0.15.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.42.0
```

### Affected Resource(s)

* `aws_elasticache_cluster`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.42.0"
    }
  }
  required_version = ">= 0.15"
}

provider "aws" {
  region = "us-east-2"
  default_tags {
    tags = {
      TagA = "TagA"
      TagB = "TagB"
    }
  }
}

resource "aws_elasticache_cluster" "example" {
  cluster_id           = "cluster-example"
  engine               = "redis"
  node_type            = "cache.t2.micro"
  num_cache_nodes      = 1
  parameter_group_name = "default.redis6.x"
  engine_version       = "6.x"
  subnet_group_name    = "subnetgroup-private"
}
```

### Expected Behavior

1. When adding new tags at the `tag` block inside `default_tags` on `provider "aws"`, it would actually add the tag to the resource `aws_elasticache_cluster`.

2. When removing tags from the `tag` block inside `default_tags` on `provider "aws"`, it would actually remove the tag from the resource `aws_elasticache_cluster`.

### Actual Behavior

1. Adding tags detects no changes when running `terraform plan` and/or `terraform apply`.
```
➜ terraform apply
aws_elasticache_cluster.example: Refreshing state... [id=cluster-example]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```
2. Removing tags detects changes when running `terraform plan` and/or `terraform apply` and even says it removed it from the resource itself when you apply the change, but checking against the actual resource at AWS shows that the removed tag is still present. Rerunning `terraform apply` after the previous one ends will detect the same actions as the previous run and try to apply the same actions again (without doing anything to the actual resource).

```
➜ terraform apply
aws_elasticache_cluster.example: Refreshing state... [id=cluster-example]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # aws_elasticache_cluster.example has been changed
  ~ resource "aws_elasticache_cluster" "example" {
        id                       = "cluster-example"
      + tags                     = {
          + "TagB" = "TagB"
        }
        # (19 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_elasticache_cluster.example will be updated in-place
  ~ resource "aws_elasticache_cluster" "example" {
        id                       = "cluster-example"
      ~ tags                     = {
          - "TagB" = "TagB" -> null
        }
        # (19 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_elasticache_cluster.example: Modifying... [id=cluster-example]
aws_elasticache_cluster.example: Modifications complete after 2s [id=cluster-example]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

### Steps to Reproduce

1. Create a redis cluster resource (`aws_elasticache_cluster`) including its tags with `terraform apply` (example provided above);
2. Add or remove any tags to `default_tags -> tags` block (ie: adding `TagC = "TagC"` or removing `TagB = "TagB"`);
3. Run `terraform apply` again.

**Comment by ewbankkit** [comment]
It looks like the resource's `CustomizeDiff` method

https://github.com/hashicorp/terraform-provider-aws/blob/0152d0ba7256bbeae1c38b6cd03f4ce82549c5e5/aws/resource_aws_elasticache_cluster.go#L264-L271

is missing [`SetTagsDiff`](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/contribution-checklists.md#resource-tagging-code-implementation).

**Comment by anGie44** [comment]
I'll put up a PR to add that one in @ewbankkit
