### ISSUE TITLE
Add Support for Amazon Location Service

### ISSUE THREAD

**Issue by pocket7878** [hashicorp/terraform-provider-aws#19629]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Amazon Location Service provides affordable data, tracking and geofencing capabilities, and native integrations with AWS services, so you can create sophisticated location-enabled applications quickly, without the high cost of custom development. You retain control of your location data with Amazon Location, and you can combine proprietary data with data from the service. Amazon Location provides cost-effective location-based services (LBS) using high-quality data from global, trusted providers Esri and HERE. 

### New or Affected Resource(s)

* aws_location_tracker
* aws_location_tracker_association
* aws_location_map
* aws_location_place_index
* aws_location_route_calculator
* aws_location_geofence_collection

### Potential Terraform Configuration

```hcl
/* Geofence */
resource "aws_location_geofence_collection" "geofence_collection" {
  name = "sample_geofence_collection"
  description = "just a sample"
  kms_key_id = "xxxxxxxxxxxxxxxx:yyyyyyyyyyyy:zzzzzz"
  pricing_plan {
    plan = "RequestBasedUsage"
    data_source = "Esri"
  }
  tags = {
    Name = "Sample Amazon Location Geofence Collection"
  }
}

/* Tracker */
resource "aws_location_tracker" "tracker" {
  name = "sample_tracker"
  description = "just a sample"
  pricing_plan "RequestBasedUsage"
  pricing_data_source = "Ersi"
  kms_key_id = "xxxxxxxxxxxxxxxx:yyyyyyyyyyyy:zzzzzz"
  tags = {
    Name = "Sample Amazon Location Tracker"
  }
}

resource "aws_location_tracker_association" "tracker_association" {
  tracker_name = "sample_tracker"
  consumer_arn = amazon_location_geofence_collection.geofence_collection.arn
}

/* Map */
resource "aws_location_map" "sample_map" {
  name = "sample"
  description = "just a sample"
  pricing_plan "RequestBasedUsage"
  map_configuration {
    style = "RasterEsriImagery"
  }
  tags = {
    Name = "Sample Amazon Location Map"
  }
}

/* Places */
resource "aws_location_place_index" "sample_place_index" {
  name = "sample place index"
  description = "just a sample"
  pricing_plan "RequestBasedUsage"
  data_source = "Esri"
  data_source_configuration {
    intended_use = "SingleUse"
  }
  map_configuration {
    style = "RasterEsriImagery"
  }
  tags = {
    Name = "Sample Amazon Location Place Index"
  }
}

/* Route */
resource "aws_location_route_calculator" "sample_route_calculator" {
  name = "sample place index"
  description = "just a sample"
  pricing_plan "RequestBasedUsage"
  data_source = "Esri"
  tags = {
    Name = "Sample Amazon Location Route Calculator"
  }
}
```

### References

* https://docs.aws.amazon.com/location/

**Comment by kamilturek** [comment]
I'll give it a try soon.

**Comment by kamilturek** [comment]
## Progress Checklist

### Resources
- [X] `aws_location_map`
- [ ] `aws_location_tracker`
- [ ] `aws_location_tracker_association`
- [ ] `aws_location_place_index`
- [ ] `aws_location_route_calculator`
- [ ] `aws_location_geofence_collection`
- [ ] `aws_location_geofence`

### Data Sources
- [ ] `aws_location_map`
- [ ] `aws_location_tracker`
- [ ] `aws_location_place_index`
- [ ] `aws_location_route_calculator`
- [ ] `aws_location_geofence_collection`
- [ ] `aws_location_geofence`

**Comment by kamilturek** [comment]
The Geofence resource has a quite specific form.
https://docs.aws.amazon.com/location/latest/APIReference/API_PutGeofence.html

I might come up with a schema for that but I'd rather hear an opinion/proposal from a person that actively uses geofences on how the schema should look like. Therefore, I vote to skip these resources/data sources for now.

**Comment by dev-airmaxx** [comment]
For **aws_location_place_index** should be field region, cause not all regions have location api service

**Comment by thebitrock** [comment]
@pocket7878 For aws_location_place_index should be field region, cause not all regions have location api service
