### ISSUE TITLE
Data source to list MSK nodes for OpenMonitoring

### ISSUE THREAD

**Issue by shousper** [hashicorp/terraform-provider-aws#19638]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In order to create a Prometheus scrape configuration for the MSK nodes, we need to be able to get a list of all the broker nodes (not just the bootstrap set). This could be done via the `ListNodes` API from the AWS SDK, per [the AWS docs](https://docs.aws.amazon.com/msk/latest/developerguide/open-monitoring.html)

### New or Affected Resource(s)

* aws_msk_nodes - to provide complete node list.

### Potential Terraform Configuration

```hcl
data "aws_msk_nodes" "example" {
  cluster_name = "example"
}
```

### References

* https://docs.aws.amazon.com/msk/latest/developerguide/open-monitoring.html

**Comment by AlbertoPeon** [comment]
This would be great to have!

Basically, changes that are required for each Kafka broker (e.g. open monitoring, network rules, etc) cannot be done through Terraform. 

Additionally, the fact that `BoostrapServers` yield a different list of brokers each time (when # of brokers > 3) causes Terraform to make pointless changes in each run.
