### ISSUE TITLE
Import of aws_iam_policy with policy from a file is failing  tf=0.15.4. 

### ISSUE THREAD

**Issue by buchs** [hashicorp/terraform-provider-aws#19635]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

tf -v
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.42.0
+ provider registry.terraform.io/hashicorp/null v3.1.0

### Affected Resource(s)

* aws_iam_policy

### Terraform Configuration Files

```hcl
resource "aws_iam_policy" "simdis" {
    name = "stop-simpad"
    path = "/"
    policy = file("iam-policy.json")
}

resource "aws_iam_group" "group" {
    name = "simpad_destroyers"
}

resource "aws_iam_group_policy_attachment" "grouppol" {
    group = aws_iam_group.group.name
    policy_arn = aws_iam_policy.simdis.arn
}
```

### Expected Behavior

I created an IAM group and policy and attached the policy to the group via the AWS Portal. Now trying to import into TF state. The group imports fine. The policy does not.

### Actual Behavior

```bash
$ tf import aws_iam_policy.simdis stop-simpad
aws_iam_policy.simdis: Importing from ID "stop-simpad"...
aws_iam_policy.simdis: Import prepared!
  Prepared aws_iam_policy for import
aws_iam_policy.simdis: Refreshing state... [id=stop-simpad]
╷
│ Error: error reading IAM policy stop-simpad: InvalidParameter: 1 validation error(s) found.
│ - minimum field size of 20, GetPolicyInput.PolicyArn.
```

### Steps to Reproduce

1. Terraform import

**Comment by gdavison** [comment]
Hi, @buchs. To import an `aws_iam_policy`, you need to pass the ARN, not the name. You can check the "Import" section at the bottom of each resource's documentation page, e.g. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy#import, since it varies by resource type.
