### ISSUE TITLE
aws_api_gateway_integration resource used for lambda proxy integration on api gateway , doesnt let lambda_name passed from stage variables

### ISSUE THREAD

**Issue by swagsb** [hashicorp/terraform-provider-aws#19645]
On the aws console , I can create a api gateway resource and in the integration ,  I can specify lambda proxy integration and then  pass the lambda function from stage variables , see screenshot. [](url)
<img width="890" alt="aws_api_gateway_integration" src="https://user-images.githubusercontent.com/66527484/120668094-c3e5c880-c4ab-11eb-94a6-207a0a8f4c5c.PNG">

But when I try to do same using terraform , see snippet below:-

```terraform
resource "aws_api_gateway_integration" "delegate_integration" {
  rest_api_id = module.api.id
  credentials  = "arn:aws:iam::${data.aws_caller_identity.identity.account_id}:role/$stageVariables.api_gw_role"
  http_method = aws_api_gateway_method.delegate_method.http_method
  resource_id = aws_api_gateway_resource.delegate_resource.id
  type = "AWS_PROXY"
  uri  = "arn:aws:apigateway:${data.aws_region.region.name}:lambda:path/2015-03-31/functions/\\$\\{stageVariables.lambda_name}/invocations"
  integration_http_method   = "ANY"
}
```

I get below error:-
Error: Error creating API Gateway Integration: BadRequestException: **Invalid lambda function**
  on ../lambda-proxy.tf line 14, in resource "aws_api_gateway_integration" "delegate_integration":
  14: resource "aws_api_gateway_integration" "delegate_integration" {

I have tried diff combinations like passing the whole uri from stage variable or using $stageVariables instead of ${stageVariables} , nothing worked.  This is a bug and should be fixed.  Since its allowed on aws console , it should work out in terraform as well

**Comment by gdavison** [comment]
Hi, @swagsb. Can you tell me which type of API Gateway you created in the Console? REST APIs use the API Gateway v1, and the `aws_api_gateway_` resources, and Websocket and HTTP APIs use API Gateway v2, and the `aws_apigatewayv2_` resources (see https://docs.aws.amazon.com/apigateway/latest/developerguide/api-ref.html).

From looking at the AWS documentation on stages, it looks like the stage variables should be included as `${stageVariables.<variable>}`, not as `\\$\\{stageVariables.<variable>}` or `$stageVariables.<variable>` like in your sample above.

The [`terraform import`](https://www.terraform.io/docs/cli/import/index.html) command can be helpful for configuring resources manually and then managing them with Terraform if the suggestions above don't work.
