### ISSUE TITLE
aws_imagebuilder_image_recipe can't be replaced due to dependency on aws_imagebuilder_image_pipeline

### ISSUE THREAD

**Issue by Dogers** [hashicorp/terraform-provider-aws#19642]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

TF 0.15.1
AWS 3.38.0

### Affected Resource(s)

* aws_imagebuilder_image_recipe
* aws_imagebuilder_image_pipeline

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_imagebuilder_image_recipe" "recipe" {
...
  component {
    component_arn = "arn:aws:imagebuilder:eu-west-1:aws:component/aws-cli-version-2-linux/1.0.0"
  }
}

resource "aws_imagebuilder_image_pipeline" "pipeline" {
  image_recipe_arn                 = aws_imagebuilder_image_recipe.recipe.arn
...
}
```

Have the above applied, then add an additional component:

```hcl
resource "aws_imagebuilder_image_recipe" "recipe" {
...
  component {
    component_arn = "arn:aws:imagebuilder:eu-west-1:aws:component/aws-cli-version-2-linux/1.0.0"
  }
  component {
    component_arn = "arn:aws:imagebuilder:eu-west-1:aws:component/chrony-time-configuration-test/1.0.0"
  }
}

resource "aws_imagebuilder_image_pipeline" "pipeline" {
  image_recipe_arn                 = aws_imagebuilder_image_recipe.recipe.arn
...
}
```

### Expected Behavior

Terraform plan appears fine, it wants to add the component to the recipe (requires a replacement) and update the pipeline with the new recipe ARN.
```
  # aws_imagebuilder_image_pipeline.pipeline will be updated in-place
  ~ resource "aws_imagebuilder_image_pipeline" "pipeline" {
        id                               = "arn:aws:imagebuilder:eu-west-1:<snip>:image-pipeline/testing-pipeline"
      ~ image_recipe_arn                 = "arn:aws:imagebuilder:eu-west-1:<snip>:image-recipe/testing-recipe/1.0.0" -> (known after apply)
        name                             = "component_testing-Pipeline"
...

  # imagebuilder.aws_imagebuilder_image_recipe.recipe must be replaced
-/+ resource "aws_imagebuilder_image_recipe" "recipe" {
      ~ arn          = "arn:aws:imagebuilder:eu-west-1:<snip>:image-recipe/testing-recipe/1.0.0" -> (known after apply)
...
        component {
            component_arn = "arn:aws:imagebuilder:eu-west-1:aws:component/aws-cli-version-2-linux/1.0.0"
        }
      + component { # forces replacement
          + component_arn = "arn:aws:imagebuilder:eu-west-1:aws:component/chrony-time-configuration-test/1.0.0"
        }
```

### Actual Behavior

When applying however, TF cannot remove the recipe as the pipeline is referencing it, causing the apply to fail. To work around this, the pipeline has to be manually `terraform taint`'ed after which the apply will work as expected.

```
aws_imagebuilder_image_recipe.recipe: Destroying... [id=arn:aws:imagebuilder:eu-west-1:<snip>:image-recipe/testing-recipe/1.0.0]

Error: error deleting Image Builder Image Recipe (arn:aws:imagebuilder:eu-west-1:<snip>:image-recipe/testing-recipe/1.0.0): ResourceDependencyException: Resource dependency error: The resource ARN 'arn:aws:imagebuilder:eu-west-1:<snip>:image-recipe/testing-recipe/1.0.0' has other resources depended on it.
```

Seems that the update of the `image_recipe_arn` attribute in the pipeline should cause the pipeline to be automatically replaced.

### Steps to Reproduce

1. `terraform apply`

**Comment by Xyaren** [comment]
Possibly related: #17137

**Comment by Xyaren** [comment]
Seems to work for me IF:
1. you set ```lifecycle {
    create_before_destroy = true
  }``` on the `aws_imagebuilder_image_recipe` 
2. change the recipe version whenever you change the recipe.
    Otherwise you'll get :   `error creating Image Builder Image Recipe: ResourceAlreadyExistsException: The following resource 'ImageRecipe' already exists:...`

**Comment by Dogers** [comment]
Yeah, that would look to be related - the problem is the recipe arn isn't changing, so there's no update needed on the pipeline, however the component amendment requires the recipe to be recreated, but it's locked by being in use in the pipeline :(

I wonder if maybe the recipe can be updated in place rather than having to be destroyed and recreated..? Can't remember now from when I was looking at this in the API..

**Comment by schultetwin** [comment]
FWIW, I think this is also an issue with `aws_imagebuilder_component`.

**Comment by stpierre** [comment]
I've used @Xyaren's workaround and that works for me as well. But it's a PITA to update the versions every time, so it'd still be nice if this could work more like other things.

**Comment by eugene-riabchuk** [comment]
> Seems to work for me IF:
> 
> 1. you set `lifecycle { create_before_destroy = true   }` on the `aws_imagebuilder_image_recipe`
> 2. change the recipe version whenever you change the recipe.
>    Otherwise you'll get :   `error creating Image Builder Image Recipe: ResourceAlreadyExistsException: The following resource 'ImageRecipe' already exists:...`

This is worked for me as well, thanks !

**Comment by danieltharp** [comment]
While I see this in the upgrade notes for 3.67, I'm not clear on what I should be doing differently to fix the issue. I'm on 3.74.x and still running into the same issue as above.
