### ISSUE TITLE
aws_lakeformation_permissions inconsistent result after apply

### ISSUE THREAD

**Issue by phzietsman** [hashicorp/terraform-provider-aws#19643]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.15.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.43.0
```

### Affected Resource(s)
* aws_lakeformation_permissions

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_lakeformation_permissions" "data_producer_database" {

  provider = aws.lf_data_producer

  principal = var.org_arn

  permissions                   = ["DESCRIBE"]
  permissions_with_grant_option = ["DESCRIBE"]
  
  database {
    name       = aws_glue_catalog_database.data_producer.name
    catalog_id = data.aws_caller_identity.lf_data_producer.account_id
  }
}

variable "org_arn" {
  default = "arn:aws:organizations::xxx:organization/o-zzzzzz"
}

```

### Expected Behavior
Permissions to be added to the Glue database that gives the entire AWS Organization `DESCRIBE` access and the changes to be reflected in the state file.

### Actual Behavior
The changes are applied in the AWS, but the state does not reflect the changes. This only occurs when applying permissions to organizations and organizational units, when giving access to other accounts, this error does not occur.

Subsequent applies creates another resource in AWS and give the same error, resulting in multiple permission entries for the same Org/OU.

```bash
aws_lakeformation_permissions.data_producer_database: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to aws_lakeformation_permissions.data_producer_database, provider
│ "provider[\"registry.terraform.io/hashicorp/aws\"].lf_data_producer" produced an
│ unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue
│ tracker.
```

### Steps to Reproduce

1. `terraform apply`

**Comment by ramprasadtx** [comment]
We are using * provider.aws: version = "~> 3.42". PFA attached build file with error

Step 1 (worked FINE)
resource "aws_lakeformation_permissions" "test_athenalf_table" {
principal = "arn:aws:iam::ACCCT:role/app-athena-lf-user"
permissions = ["SELECT"]

table_with_columns {
database_name = "lffix"
name = "lffix"
column_names=["amt","age"]
}
}

When we Changed to :

resource "aws_lakeformation_permissions" "test_athenalf_table" {
principal = "arn:aws:iam::ACCCT:role/app-athena-lf-user"
permissions = ["SELECT"]

table_with_columns {
database_name = "lffix"
name = "lffix"
column_names=["amt"]
}
}

It FAILED with 
This is a bug in the provider, which should be reported in the provider's own issue tracker.
2021/06/04 19:34:01 [ERROR] <root>: eval: *terraform.EvalSequence, err: Provider produced inconsistent result after apply: When applying changes to aws_lakeformation_permissions.test_athenalf_table, provider "registry.terraform.io/-/aws" produced an unexpected new value for was present, but now absent.

**Comment by YakDriver** [comment]
This bug would be reproduced by the `testAccAWSLakeFormationPermissions_tableWithColumns()` acceptance test in #19817. That verifies that the bug is resolved with that PR.
