### ISSUE TITLE
Support ECS FSxWindowsFileServerVolumeConfiguration

### ISSUE THREAD

**Issue by sbutler** [hashicorp/terraform-provider-aws#19652]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS supports [using FSx volumes for Windows containers](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/wfsx-volumes.html) since [Nov 2020](https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-ecs-supports-use-of-amazon-fsx-windows-file-server/). This is done as a new volume configuration block for task definitions.

- ECS [RegisterTaskDefinition](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RegisterTaskDefinition.html)
- ECS [Volume](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_Volume.html#ECS-Type-Volume-fsxWindowsFileServerVolumeConfiguration)
- ECS [FSxWindowsFileServerVolumeConfiguration](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_FSxWindowsFileServerVolumeConfiguration.html)

### New or Affected Resource(s)

* aws_ecs_task_definition

### Potential Terraform Configuration

```hcl
resource "aws_ecs_task_definition" "service" {
  family                = "service"
  container_definitions = file("task-definitions/service.json")

  volume {
    name = "service-storage"

    fsx_windows_file_server_volume_configuration {
      file_system_id = aws_fsx_windows_file_system.fs.id
      root_directory = "\\data"
      authorization_config {
        credentials_parameter = aws_ssm_parameter.fs_creds.name
        domain                = "ad.example.org"
      }
    }
  }
}
```

**Comment by DrFaust92** [comment]
ill take a crack at this
