### ISSUE TITLE
aws_cloudwatch_metric_alarm metric_query validation does not allow percentiles (3.44 regression)

### ISSUE THREAD

**Issue by tdmalone** [hashicorp/terraform-provider-aws#19665]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.12.31
+ provider.aws v3.44.0
```

### Affected Resource(s)

* aws_cloudwatch_metric_alarm

### Expected Behavior

Plan containing a stat of p99 to continue to validate.

### Actual Behavior

```
Error: expected metric_query.1.metric.0.stat to be one of [SampleCount Average Sum Minimum Maximum], got p99

  on ../../modules/cloudwatch-alarm/main.tf line 38, in resource "aws_cloudwatch_metric_alarm" "metric_math":
  38: resource "aws_cloudwatch_metric_alarm" "metric_math" {
```

### Steps to Reproduce

1. `terraform apply`

### References

* Caused by https://github.com/hashicorp/terraform-provider-aws/issues/19567 / https://github.com/hashicorp/terraform-provider-aws/pull/19571
* Potential fix at https://github.com/hashicorp/terraform-provider-aws/pull/19571#issuecomment-854306716

**Comment by ewbankkit** [comment]
Relevant AWS documentation:

* [CloudWatch Statistics](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html#Statistic)
* [CloudWatch Percentiles](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html#Percentiles)
