### ISSUE TITLE
Management of individual account resource tags in AWS Orgs

### ISSUE THREAD

**Issue by DmitriSmirnovCTL** [hashicorp/terraform-provider-aws#19660]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Is it possible to add management of individual organizational account tags? This is could be useful in cases where accounts in the org are created outside of Terraform, for example using Account Factory in ControlTower. These tags can be added in AWS Console using Organizations service (same as 'aws organizations tag-resource'?)

### New or Affected Resource(s)

aws_organizations_account_tags

### Potential Terraform Configuration

```hcl
resource "aws_organizations_account_tag" "example" {
  resource_id = aws_organizations_account.id
  key         = "Name"
  value       = "Hello World"
}
```

### References

* #0000

**Comment by PCjrBasic** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/11511 - looking for a data provider for the info.

**Comment by sbkg0002** [comment]
Did you find a way to do this?
