### ISSUE TITLE
Wrong validation for`aws_cloudwatch_event_target` `input_transformer.input_paths` maximum size

### ISSUE THREAD

**Issue by kromol** [hashicorp/terraform-provider-aws#19698]
According to [AWS documentation](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_InputTransformer.html#API_InputTransformer_Contents) maximum number of items in `InputTransformer.InputPathsMap` is 100. Provider limits it to 10.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.13.7

### Affected Resource(s)

* `aws_cloudwatch_event_target`

### Expected Behavior
100 items in `input_transformer.input_paths` should be allowed.

### Actual Behavior
Error is thrown:
```
Error: expected number of items in input_transformer.0.input_paths to be less than or equal to 10, got 27
```

### Steps to Reproduce
Create event target resource and pass more than 10 items in input_paths: 
```
variable "sns_targets" {
  type = list(object({
    sns_topic_arn = string
    input_transformer = object({
      input_paths     = map(string)
      input_templates = string
    })
  }))
  description = "List of SNS topics ARNs"
}

resource "aws_cloudwatch_event_target" "sns_targets" {
  for_each = {
    for index, value in var.sns_targets : index => value
  }

  arn            = each.value.sns_topic_arn
  rule           = aws_cloudwatch_event_rule.event_rule.name
  event_bus_name = "default"

  dynamic "input_transformer" {
    for_each = each.value.input_transformer == null ? [] : [each.value.input_transformer]

    content {
      input_paths    = input_transformer.value.input_paths
      input_template = input_transformer.value.input_templates
    }
  }
}
```

**Comment by anGie44** [comment]
Hi @kromol , thank you for raising this issue. Looks like the AWS service has changed since the last time that validation check was added, but it's definitely adjustable within the resource code here:

https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_cloudwatch_event_target.go#L259-L266

`MaxMapItems` can be increased to 100 👍 

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/10912.

**Comment by kromol** [comment]
Yeah, thanks for the hint
I am going to raise a PR today to fix it
