### ISSUE TITLE
aws_autoscaling_policy predictive_scaling_configuration requires resource_label to be defined

### ISSUE THREAD

**Issue by jwhitcraft** [hashicorp/terraform-provider-aws#19700]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.31
+ provider.aws v3.44.0
+ provider.external v2.0.0
+ provider.local v2.1.0
+ provider.null v3.1.0
+ provider.random v3.1.0
+ provider.template v2.2.0

### Affected Resource(s)

* aws_autoscaling_policy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_autoscaling_policy" "predictive" {
  count = var.predicitive_scale != null ? 1 : 0
  name                   = "${var.name}s-policy_predictive"
  policy_type            = "PredictiveScaling"
  autoscaling_group_name = aws_autoscaling_group.autoscaling_group.name
  predictive_scaling_configuration {
    metric_specification {
      target_value = lookup(var.predicitive_scale, "scaling_metric_target", 50)
      predefined_metric_pair_specification {
        predefined_metric_type = lookup(var.predicitive_scale, "scaling_metric_type", "ASGCPUUtilization")
        resource_label = lookup(var.predicitive_scale, "scaling_metric_label", null)
      }
    }
    mode                         = lookup(var.predicitive_scale, "mode", "ForecastOnly")
    scheduling_buffer_time       = lookup(var.predicitive_scale, "scheduling_buffer_time", 0)
    max_capacity_breach_behavior = lookup(var.predicitive_scale, "max_capacity_breach_behavior", null)
    max_capacity_buffer          = lookup(var.predicitive_scale, "max_capacity_buffer", null)
  }
}
```

### Debug Output

```
Error: Missing required argument

  on ../../../terraform_modules/tf-module-autoscaling/predective_scale.tf line 11, in resource "aws_autoscaling_policy" "predictive":
  11:         resource_label = lookup(var.predicitive_scale, "scaling_metric_label", null)
```

### Expected Behavior

Since the values are marked as optional, in the docs on both Terraform and AWS, it should allow null to be passed

### Actual Behavior

It errored out saying the value was required

### Steps to Reproduce

1. `terraform apply`

### References

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_policy#predefined_metric_type

**Comment by anGie44** [comment]
Hi @jwhitcraft , thank you for raising this issue (and the PR linked!). While the AWS API documentation does show that `resource_label` is not required (as well as the terraform provider docs), looks like the API request does require that field else the following errors occur:
```
Error: Error putting scaling policy: InvalidParameter: 3 validation error(s) found.
        - minimum field size of 1, PutScalingPolicyInput.PredictiveScalingConfiguration.MetricSpecifications[0].PredefinedLoadMetricSpecification.ResourceLabel.
        - minimum field size of 1, PutScalingPolicyInput.PredictiveScalingConfiguration.MetricSpecifications[0].PredefinedMetricPairSpecification.ResourceLabel.
        - minimum field size of 1, PutScalingPolicyInput.PredictiveScalingConfiguration.MetricSpecifications[0].PredefinedScalingMetricSpecification.ResourceLabel.
```

We should, instead, update our documentation to ensure the `resource_label` is listed as `Required` as seen in the resource's schema 👍

**Comment by jwhitcraft** [comment]
Hey @anGie44, thanks for the response.

My 2¢ is that is still incorrect as I can use the go-sdk to generate a `predefined_metric_pair_specification` for `ASGCPUUtilization` and not pass it the resource-label and it works fine.  I think the issue is, that the resource is always adding that strut even if it's nil.

I know AWS just ignores that value, but it seems like something that doesn't need to be set unless using `ALBTargetGroupRequestCount` as the metric_type.

I need to fix my local machine to test this theory fully, but once I do, I'll report back on what my finding is and if I come up with a more correct fix, and if not I'll just correct the docs to reflect it being required.

**Comment by anGie44** [comment]
Ahh makes sense @jwhitcraft ...well in the future we will eventually adopt the v2, but yep for the time being we'll have to hold-off and just make sure our docs match 👍

**Comment by jwhitcraft** [comment]
@anGie44 just update the PR with the documentation changes.
