### ISSUE TITLE
aws_autoscaling_policy predefined_load_metric_specification documentation is incorrect

### ISSUE THREAD

**Issue by jedioncrk** [hashicorp/terraform-provider-aws#19706]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

> terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/-/aws v3.44.0
+ provider registry.terraform.io/-/null v3.1.0
+ provider registry.terraform.io/-/random v3.1.0
+ provider registry.terraform.io/-/template v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.44.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

Your version of Terraform is out of date! The latest version
is 0.15.5. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

* aws_autoscaling_policy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_autoscaling_policy" "mail_asp" {
  name                    = "mail_asp"
  policy_type             = "PredictiveScaling"
  adjustment_type         = "ChangeInCapacity"
  
  predictive_scaling_configuration {
    metric_specification {
      target_value = 45.0
      predefined_load_metric_specification {
        predefined_metric_type  = "ASGTotalCPUUtilization"
      }
    }
  }
  
  cooldown                = 300
  autoscaling_group_name  = module.mail-asg.this_autoscaling_group_name
}
```

### Debug Output

Error: Missing required argument

  on svc-starmail.tf line 55, in resource "aws_autoscaling_policy" "starmail_asp":
  55:       predefined_load_metric_specification {

The argument "resource_label" is required, but no definition was found.

### Expected Behavior

Documentation here says that the resource_label is optional, when in fact, it is required.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_policy#predictive_scaling_configuration

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by anGie44** [comment]
Relates #19700
