### ISSUE TITLE
v15.4 always prints plan to console when apply or destroy are called.

### ISSUE THREAD

**Issue by greenbeast** [hashicorp/terraform-provider-aws#19711]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.15.4 on linux_amd64

### Affected Resource(s)

* None

This is an issue with the Terraform CLI command options, not a resource. However, I am using Terraform with the vsphere provider and that version is the latest, v1.26.0.

### Terraform Configuration Files

I recently upgraded from Terraform 14.9 to 15.4.

In v14.9, I could use the `-auto-approve` option when calling the `apply` or `destroy` commands that would also stop Terraform printing its plan to the console window. However, v15.4 no longer does this, instead choosing to output the whole plan and there is no way to turn it off. This unnecessary printing slows down the process when deploying a lot of resources and for what I am doing, I am not interested in what it is saying. Therefore, I prefer the 14.9 behaviour.

The standard vsphere configuration files, as given on the hashicorp website is sufficient for this issue. This can be viewed from [here](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs).

My CLI command line entries are as follows:

```hcl
v14.9
>terraform init
>terraform apply -auto-approve
>terraform destroy -auto-approve
```
These commands worked fine. However, entering the same commands into v15.4 causes the terraform plan to now print to the console window. Therefore, from viewing the Hashicorp's content on [apply](https://www.terraform.io/docs/cli/commands/apply.html) and the associated [automation](https://learn.hashicorp.com/tutorials/terraform/automate-terraform?in=terraform/automation&utm_source=WEBSITE&utm_medium=WEB_IO&utm_offer=ARTICLE_PAGE&utm_content=DOCS) I modified the command calls to the following. However, it still prints the plan to the console window:

```hcl
v15.4
>terraform init -input=false
>terraform plan -lock-timeout=3s -out=tfplan -input=false
>terraform apply -lock-timeout=3s -input=false tfplan
>terraform destroy -auto-approve
```
The call to both plan and destroy commands result in the plan being presented in the console window

### Expected Behavior

The call to plan, apply or command should not result in the plan being printed either when the `auto-approve` or `-input=false` options are set.

### Actual Behavior

The plan is printed to the console that for a large deployment causes a significant delay to the deployment process.

### Steps to Reproduce

1. Refer to the Terraform Configuration files section, above

### Important Factoids

none.

**Comment by anGie44** [comment]
Hi @greenbeast , thank you taking the time to raise the above issue. Since this relates to the terraform CLI, I would recommend creating a new issue within the [terraform repository](https://github.com/hashicorp/terraform/issues) for further consideration as here in the AWS provider repository we do not directly oversee the UI/UX of the terraform CLI to provide appropriate feedback/context associated with the CLI design.

**Comment by greenbeast** [comment]
Thanks anGie44 and I will do as you recommend. Sorry I am new here and I didnt realise this was specifically for AWS provider (makes sense now you say it though...stupid me). All the best

**Comment by anGie44** [comment]
No worries @greenbeast , there's quite a few terraform related repo's out there so it's totally understandable! Happy to redirect 😃
