### ISSUE TITLE
Change to aws_autoscaling_group removed lifecycle hook

### ISSUE THREAD

**Issue by richardgavel** [hashicorp/terraform-provider-aws#19714]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform 0.13.6
provider.aws 3.34.0

### Affected Resource(s)

* aws_autoscaling_group

### Expected Behavior

The lifecycle hook was added via the initial_lifecycle_hook argument on the aws_autoscaling_group resource.

When updating the auto scaling group (in this case, by updating the launch template by updating instance type, which results in updating the auto scaling group to reference the newer version of the launch template, I expect the lifecycle hook to remain on the auto scaling group. Subsequent runs do not recreate the lifecycle hook.

What is also odd is I'm not sure how the lifecycle hook got added in the first place via an update operation. I see nothing in the code (https://github.com/hashicorp/terraform-provider-aws/blob/bf230a0d3debf5f769b7a238f7af451f34a320db/aws/resource_aws_autoscaling_group.go#L984) that would suggest it would add the lifecycle hook, only on a create operation.

### Actual Behavior

The lifecycle hook no longer exists in AWS console. 

* #0000

**Comment by anGie44** [comment]
Hi @richardgavel , thank you for raising this issue. It seems very closely related to https://github.com/hashicorp/terraform-provider-aws/issues/4714 , as I believe a change in the `initial_lifecycle_hook` argument should in fact force a new resource instead of an in-place update.
