### ISSUE TITLE
aws_ssoadmin_account_assignment instance_arn docs mistake

### ISSUE THREAD

**Issue by jasonblanchard** [hashicorp/terraform-provider-aws#19717]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_ssoadmin_account_assignment

The docs show the following:

```
resource "aws_ssoadmin_account_assignment" "example" {
  instance_arn       = data.aws_ssoadmin_permission_set.example.instance_arn
  permission_set_arn = data.aws_ssoadmin_permission_set.example.arn

  principal_id   = data.aws_identitystore_group.example.group_id
  principal_type = "GROUP"

  target_id   = "012347678910"
  target_type = "AWS_ACCOUNT"
}
```

But the docs say `instance_arn` is:

> The Amazon Resource Name (ARN) of the SSO Instance.

So I think in this case, it should be set to `tolist(data.aws_ssoadmin_instances.example.arns)[0]`, instead of the permission set ARN, i.e.:

```
resource "aws_ssoadmin_account_assignment" "example" {
  instance_arn       = tolist(data.aws_ssoadmin_instances.example.arns)[0]
  permission_set_arn = data.aws_ssoadmin_permission_set.example.arn

  principal_id   = data.aws_identitystore_group.example.group_id
  principal_type = "GROUP"

  target_id   = "012347678910"
  target_type = "AWS_ACCOUNT"
}
```

**Comment by posquit0** [comment]
`tolist(data.aws_ssoadmin_instances.example.arns)[0]` and `data.aws_ssoadmin_permission_set.example.instance_arn` are same. :)

**Comment by jasonblanchard** [comment]
Ohh I see it now... it was throwing me off that it's getting the instance_arn off the permission set where other examples get it directly from data.aws_ssoadmin_instances. Ignore me!
