### ISSUE TITLE
Cannot create Secrets Manager secret with an empty string as value

### ISSUE THREAD

**Issue by kurtwheeler** [hashicorp/terraform-provider-aws#19731]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.44.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s)

* aws_secretsmanager_secret
* aws_secretsmanager_secret_version

### Terraform Configuration Files

```hcl
variable "raven_dsn" {
  default = ""
}

variable "raven_dsn_api" {
  default = ""
}

resource "aws_secretsmanager_secret" "raven_dsn" {
  name_prefix = "data-refinery-${var.user}-${var.stage}-raven-dsn"
}

resource "aws_secretsmanager_secret_version" "raven_dsn" {
  count = var.raven_dsn == "" ? 0 : 1
  secret_id = aws_secretsmanager_secret.raven_dsn.id
  secret_string = var.raven_dsn
}

resource "aws_secretsmanager_secret" "raven_dsn_api" {
  name_prefix = "data-refinery-${var.user}-${var.stage}-raven-dsn-api"
}

resource "aws_secretsmanager_secret_version" "raven_dsn_api" {
  count = var.raven_dsn_api == "" ? 0 : 1
  secret_id = aws_secretsmanager_secret.raven_dsn_api.id
  secret_string = var.raven_dsn_api
}
```

### Debug Output

```
Error: error putting Secrets Manager Secret value: InvalidRequestException: You must provide either SecretString or SecretBinary.

  on secrets.tf line 24, in resource "aws_secretsmanager_secret_version" "raven_dsn":
  24: resource "aws_secretsmanager_secret_version" "raven_dsn" {



Error: error putting Secrets Manager Secret value: InvalidRequestException: You must provide either SecretString or SecretBinary.

  on secrets.tf line 33, in resource "aws_secretsmanager_secret_version" "raven_dsn_api":
  33: resource "aws_secretsmanager_secret_version" "raven_dsn_api" {
```

### Expected Behavior

Terraform should have created a secret with a value of an empty string.

### Actual Behavior

Terrform complained I didn't provide SecretString, despite my configuration setting the `secret_string = var.raven_dsn_api`

### Steps to Reproduce

1. Create an aws_secretsmanager_secret and aws_secretsmanager_secret_version
2. Set the version's value to a variable that has value `""`
3. `terraform apply`

**Comment by droberts-sea** [comment]
Looks like this is AWS behavior, not Terraform. Using the AWS console and attempting to create an empty secret yields this error:

![image](https://user-images.githubusercontent.com/21064499/159581869-fb5f660d-9246-456e-b9fb-b7960cb39df9.png)
