### ISSUE TITLE
aws_glue_catalog_table fails modification due to implicit column values

### ISSUE THREAD

**Issue by dylanhellems** [hashicorp/terraform-provider-aws#19739]
I've just recently started to work with Glue tables in terraform, and I'm running into a problem with the Glue schema registry integration. I saw the following comment while searching for solutions in other issues, and I think it does a good job of describing the problem.

---

There is a specific issue relating to `aws_glue_catalog_table` [...] because only `schema_reference` OR `columns` can be specified - it's invalid to specify both. If I specify `schema_reference`, any future updates to the resource pulls back an implicit value for columns, so that updates *attempts* to set both values, even though only 1 is explicitly set in my tf files. This appears fine in the plan phase, but in the apply phase you'll see:

```
aws_glue_catalog_table.my_table: Modifying... [id=<AWS-ACCOUNT-ID>:<database-name>:<table-name>]

Error: Error updating Glue Catalog Table: InvalidInputException: Both SchemaReference and Columns are populated, only one of them should be populated.
```

This issue is causing any modifications to the table to require me to taint the resource, causing it to destroy and re-create.

_Originally posted by @jeremyolliver in https://github.com/hashicorp/terraform-provider-aws/issues/19157#issuecomment-857357493_

**Comment by DrFaust92** [comment]
Im able to reproduce this, fix coming up.

**Comment by DrFaust92** [comment]
Opened #19742 to address this issue.
