### ISSUE TITLE
Amazon CloudWatch Synthetics support for environment variables 

### ISSUE THREAD

**Issue by anilkumarkodali** [hashicorp/terraform-provider-aws#19733]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

CloudWatch Synthetics now supports the use of [environment variables](https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-cloudwatch-synthetics-supports-environment-variables/) with canaries. This allows you to save time by using a single canary script to create different canaries that have a similar task. 

This provider is not updated to support that feature yet and hence creating this request to start supporting it.

### New or Affected Resource(s)

* aws_synthetics_canary

### Potential Terraform Configuration

```hcl
Elem: &schema.Resource{
	Schema: map[string]*schema.Schema{
		"active_tracing": {
			Type:     schema.TypeBool,
			Optional: true,
		},
		"memory_in_mb": {
			Type:     schema.TypeInt,
			Optional: true,
			Computed: true,
			ValidateFunc: validation.All(
				validation.IntDivisibleBy(64),
				validation.IntAtLeast(960),
			),
		},
		"timeout_in_seconds": {
			Type:         schema.TypeInt,
			Optional:     true,
			ValidateFunc: validation.IntBetween(3, 14*60),
			Default:      840,
		},
		"environment_variables": {
			Type:     schema.TypeMap,
			Computed: true,
			Elem:     &schema.Schema{Type: schema.TypeString},
		},
	},
},
```

### References

* #0000

**Comment by ewbankkit** [comment]
@anilkumarkodali Thanks for raising this issue.
It has already been noticed in #17948. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
