### ISSUE TITLE
default_tags and resource tags should be allowed to be identical

### ISSUE THREAD

**Issue by jrobison-sb** [hashicorp/terraform-provider-aws#19760]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

If a resource has a set of tags which are identical to the set of `default_tags`, that should be allowed and not cause an error. Currently it causes `terraform plan` to produce an error saying `Error: "tags" are identical to those in the "default_tags" configuration block of the provider: please de-duplicate and try again`.

It's possible to `merge({a="b"}, {a="b"})` and get the expected output of `{"a" = "b"}`, so `default_tags` and a resource's `tags` attribute should behave similarly.

### New or Affected Resource(s)

* default_tags, and every resource

### Potential Terraform Configuration

```
provider "aws" {
  default_tags {
    tags = {
      Environment = "production"
    }
  }
}

resource "aws_sns_topic" "foo" {
  name  = "whatever"
  tags = {
    Environment = "production"
  }
}
```

**Comment by anGie44** [comment]
Hi @jrobison-sb , thank you raising this issue. It's definitely something we're exploring and there is an open issue https://github.com/hashicorp/terraform-provider-aws/issues/19204 that tracks the issue users are facing as well provides more context behind the design choice. I'm going to close this as a duplicate, butp please refer to https://github.com/hashicorp/terraform-provider-aws/issues/19204 for future updates!
