### ISSUE TITLE
AWS Private NAT Gateway

### ISSUE THREAD

**Issue by nicoaws** [hashicorp/terraform-provider-aws#19763]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/nat_gateway

* aws_nat_gateway

### Potential Terraform Configuration

```hcl
resource "aws_nat_gateway" "private_nat_gw" {
  subnet_id     = aws_subnet.example.id
  connectivity_type = "private"
  tags = {
    Name = "Private NAT-GW"
  }
}

resource "aws_nat_gateway" "public_nat_gw" {
  subnet_id     = aws_subnet.example.id
  allocation_id = aws_eip.nat.id
  connectivity_type = "public"
  tags = {
    Name = "Public NAT-GW"
  }
}
```

### References

* https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html

**Comment by ewbankkit** [comment]
@xxx Thanks for raising this issue.
Support has been merged in #19758 which will be available in **v3.45.0** of the Terraform AWS Provider, planned to be released later today.
