### ISSUE TITLE
Increased limit for key-value pairs in input_transformer argument of aws_cloudwatch_event_target

### ISSUE THREAD

**Issue by rsotogar** [hashicorp/terraform-provider-aws#19775]
Hi, it'd be really useful for me to increase the limit of selected key-value pairs in this argument. Using only 10 really limits my application since some of my input records contain dozens of fields. Thanks!

**Comment by anGie44** [comment]
Hi @rsotogar 👋 Our you referring to the limit set on `input_paths`?  Our latest release of the provider (`v3.45.0`) now sets the limit fo `input_paths` to `100` key/value pairs (per the AWS API specs).

**Comment by anGie44** [comment]
Sounds good! Closing this as fixed 👍
