### ISSUE TITLE
aws_apprunner_service is unable to detect an existing apprunner service deployed by another terraform

### ISSUE THREAD

**Issue by eduard93** [hashicorp/terraform-provider-aws#19776]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.44.0
```

### Affected Resource(s)

* aws_apprunner_service

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-east-2"
  profile = "ABC"
}

resource "aws_apprunner_service" "nginx" {
  service_name = "nginx"
  

  source_configuration {
    auto_deployments_enabled = false
    image_repository {
      image_configuration {
        port = "80"
      }
      image_identifier      = "public.ecr.aws/nginx/nginx:latest"
      image_repository_type = "ECR_PUBLIC"
    }
  }

  tags = {
    Name = "nginx-apprunner-service"
  }
}
```

### Debug Output

- [apply on server 1](https://gist.githubusercontent.com/eduard93/c71dfa1dd458df6f8df538d5ad0dabe7/raw/286260e0fdc86a0534cb48f8c5212263feed1dc7/apply1.log) - works
- [apply again on server 1](https://gist.githubusercontent.com/eduard93/ff6bdc09d26a24b8f14a6d972038c87f/raw/73f03c44477e77526a97f99728bceda4e550f21a/apply2) - works
- [apply on server 2](https://gist.githubusercontent.com/eduard93/22a058748b8c1e77c54404d1eebebe08/raw/c301d5649c4e5cb7ff33835cfd5104f37ba2b699/apply_new_server.log) - fails

### Expected Behavior

Terraform automatically detects that apprunner service with the same already exists and does not attempt to create it again.
`Apply on server 2` is equal to `apply again on server 1`. 

### Actual Behavior

Terraform on server 2 does not see AppRunner Service deployed by Server 1 and tries to deploy it again. It fails with:

```
│ Error: error creating App Runner Service (nginx): InvalidRequestException: Service with the provided name already exists: nginx.
│
│   with aws_apprunner_service.nginx,
│   on main.tf line 6, in resource "aws_apprunner_service" "nginx":
│    6: resource "aws_apprunner_service" "nginx" {
│
```

### Steps to Reproduce

1. `terraform apply`
2. Copy `main.tf` to another server (or folder) and go into that new server/folder
3. Run `terraform apply` there

### Important Factoids

I want to deploy the same apprunner service from two different hosts, however a second host does not see an apprunner service deployed by a first host, tries to deploy it again and fails.

### References

- [aws_apprunner_service](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apprunner_service)
- [nginx on Public ECR Gallery](https://gallery.ecr.aws/nginx/nginx)

**Comment by ewbankkit** [comment]
Related:

* #14394
