### ISSUE TITLE
Unable to run full aws_vpc test suite without getting `panic: test timed out after 10m0s`

### ISSUE THREAD

**Issue by obourdon** [hashicorp/terraform-provider-aws#19783]
### Community Note

Running the following command in my local Terraform AWS git repository always result in failure

```
AWS_DEFAULT_REGION=eu-west-1 AWS_PROFILE=olivier TF_ACC=1 go test ./aws -v -parallel 1 -run='TestAccAWSVpc_'
```

I can not run with more than `parallel 1` because of AWS resources quota on VPCs in my account

I remember running this test suite successfully over a year ago, and as expected it is not always the same test
which fails but seems like it happens around 18th-22nd test run in each and every case

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.12.31
Terraform AWS provider 3.45.0
```

### Affected Resource(s)

* aws_vpc

### Terraform Configuration Files

As this relates to the test suite and besides what is written above nothing special to mention here.

### Panic Output

[https://gist.github.com/obourdon/e90368de2603c9e4b1f82f38c87477d7](https://gist.github.com/obourdon/e90368de2603c9e4b1f82f38c87477d7)

### Expected Behavior

Test suite should run successfully

### Actual Behavior

Panic in test timeout (see above)

### Steps to Reproduce

See above

### References

None I could find which seems close to this one

**Comment by ewbankkit** [comment]
@obourdon Thanks for raising this issue.
To increase the timeout you can either pass the `-timeout` flag to `go run`, e.g.

```
AWS_DEFAULT_REGION=eu-west-1 AWS_PROFILE=olivier TF_ACC=1 go test ./aws -v -parallel 1 -run='TestAccAWSVpc_' -timeout 60m
```
or use the `testacc` make target with `ACCTEST_PARALLELISM` set to 1, e.g.

```
AWS_DEFAULT_REGION=eu-west-1 AWS_PROFILE=olivier ACCTEST_PARALLELISM=1 make testacc TEST=./aws TESTARGS='-run=TestAccAWSVpc_`
```

which will use the default test timeout of `180m`.

**Comment by obourdon** [comment]
Many thanks for this answer @ewbankkit, will give it a try right away

**Comment by obourdon** [comment]
I think I got the `panic timeout` wrongly interpreted on my side. The whole test suite takes more than 10mn therefore the timeout not the single test therefore my mistake. Many thanks again for clarifying all this
