### ISSUE TITLE
Expose usage metrics information on service-quotas data source

### ISSUE THREAD

**Issue by tomelliff** [hashicorp/terraform-provider-aws#19787]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The service-quotas ListServiceQuotas endpoint can return the usage metrics that can be used to track the usage of a quota. Exposing this in the [`aws_servicequotas_service_quota` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/servicequotas_service_quota) would allow people to more easily set Cloudwatch alarms when a quota is close to being hit.

### New or Affected Resource(s)

* aws_servicequotas_service_quota data source

### Potential Terraform Configuration

```hcl
data "aws_servicequotas_service_quota" "standard_spot" {
  service_code = "ec2"
  quota_name   = "All Standard (A, C, D, H, I, M, R, T, Z) Spot Instance Requests"
}

resource "aws_cloudwatch_metric_alarm" "cpu_quota_standard_spot" {
  alarm_name = "cpu-quota-standard-spot"

  metric_query {
    id = "cpu_quota_usage"

    metric {
      metric_name = data.aws_servicequotas_service_quota.standard_spot.usage_metric.metric_name
      namespace   = data.aws_servicequotas_service_quota.standard_spot.usage_metric.metric_namespace
      period      = "600"
      stat        = "Maximum"
      unit        = "Count"

      dimensions = {
        Service  = data.aws_servicequotas_service_quota.standard_spot.usage_metric.metric_dimensions.service
        Class    = data.aws_servicequotas_service_quota.standard_spot.usage_metric.metric_dimensions.class
        Type     = data.aws_servicequotas_service_quota.standard_spot.usage_metric.metric_dimensions.type
        Resource = data.aws_servicequotas_service_quota.standard_spot.usage_metric.metric_dimensions.resource
      }
    }
  }

  metric_query {
    return_data = true

    id         = "relative_cpu_quota_usage"
    expression = "cpu_quota_usage / SERVICE_QUOTA(cpu_quota_usage)"
    label      = "Relative Cpu Quota Usage - Spot"
  }

  comparison_operator = "GreaterThanThreshold"
  threshold           = 0.8
  evaluation_periods  = 3
  datapoints_to_alarm = 2

  alarm_actions             = [var.notification_topic_arn]
  insufficient_data_actions = [var.notification_topic_arn]
  ok_actions                = [var.notification_topic_arn]
}
```

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/9122
* https://github.com/hashicorp/terraform-provider-aws/pull/9177
* https://docs.aws.amazon.com/sdk-for-go/api/service/servicequotas/#MetricInfo

**Comment by samdotci** [comment]
Have just created a PR that would close this issue 😄 #29499
