### ISSUE TITLE
Allow S3 objects to automatically set content-type

### ISSUE THREAD

**Issue by ChristopherDurand** [hashicorp/terraform-provider-aws#19795]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using Terraform to upload the static assets of a website, it does not set the `content-type` at all. This is in contrast to using the AWS CLI, where running `aws s3 rsync ./folder s3://bucket-name --delete` will automatically set the mime types for you. The only way to work around this is to include a large map somewhere in the module, either a variable or data, that maps file extensions to content-types, which is cumbersome.

I think that a potential solution would be to add a boolean flag to the `aws_s3_bucket_object` resource that causes Terraform to infer the content type in the same way that the AWS CLI does, and call it `infer_content_type` or something like that.

Here is a repository with some example code to show this in action: https://github.com/ChristopherDurand/S3_content-type

### New or Affected Resource(s)

I'm not sure which resource to say this is affecting -- probably the object.
* aws_s3_bucket
* aws_s3_bucket_object

### Potential Terraform Configuration

```hcl
locals {
  s3_bucket = "unique-s3-bucket-name-globally"
}

resource "aws_s3_bucket" "frontend" {
  bucket = local.s3_bucket

  website {
    index_document = "index.html"
  }
}

resource "aws_s3_bucket_policy" "frontend" {
  bucket = aws_s3_bucket.frontend.id
  policy = <<-EOF
  {
    "Version":"2012-10-17",
    "Statement":[
      {
        "Sid":"PublicRead",
        "Effect":"Allow",
        "Principal": "*",
        "Action":"s3:GetObject",
        "Resource":["arn:aws:s3:::${local.s3_bucket}/*"]
      }
    ]
  }
  EOF
}

resource "aws_s3_bucket_object" "object" {
  for_each = fileset("../build/", "**")
  bucket   = aws_s3_bucket.frontend.id
  key      = each.value
  source   = "../build/${each.value}"
  etag     = filemd5("../build/${each.value}")
}

output "bucket_endpoint" {
  value = aws_s3_bucket.frontend.website_endpoint
}
```

**Comment by andreidmt** [comment]
Hey @ChristopherDurand, I'm new to Terraform and just stumbled upon this. The workaround I used, like you mentioned, is a local map - via [Uploading File Trees to S3 with Terraform](https://barneyparker.com/posts/uploading-file-trees-to-s3-with-terraform/#mime-type-lookups).

In terms of proposed solution, `infer_content_type` with a default `false` sounds good, keeping backwards compatibility in mind.

Intuitively I expected `aws_s3_bucket_object` to work as `s3 sync` and set the `content-type` automatically with the possibility of overwrite, thinking "static website deployments" use cases greatly outweigh others.
