### ISSUE TITLE
AWS DMS cdc start time non unix timestamp value

### ISSUE THREAD

**Issue by reynaldi-wijaya-dragon** [hashicorp/terraform-provider-aws#19801]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi! I would like to request adding other start time value to dms replication task resource. Currently it is forcing the value to be unix timestamp on (https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_dms_replication_task.go#L113). However, AWS CLI support more than just timestamp https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Task.CDC.html#CHAP_Task.CDC.StartPoint.Native

### New or Affected Resource(s)

aws_dms_replication_task

### Potential Terraform Configuration

Same configuration, however support general string. Not sure if checking should include parsing validation to ensure they are valid string

### References

* https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Task.CDC.html#CHAP_Task.CDC.StartPoint.Native

**Comment by jeremychauvet** [comment]
Hey @reynaldi-wijaya-dragon 👋🏼 
I'm facing the same issue, I'll try to submit a PR to solve it 🚀
