### ISSUE TITLE
Data Source: aws_route53_zone - add associated VPCs list to response

### ISSUE THREAD

**Issue by peter-weiss-prg** [hashicorp/terraform-provider-aws#19811]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be very helpful feature if Data Source: aws_route53_zone returns associated VPCs list in response. It is supported by AWS api which is e.g. documented in boto3 https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/route53.html#Route53.Client.get_hosted_zone under get_hosted_zone operation.

### New or Affected Resource(s)

* Data Source: aws_route53_zone

**Comment by peter-weiss-prg** [comment]
@bill-rich pls anything new on this?

**Comment by peter-weiss-prg** [comment]
this is not enhancement. this is bug.

**Comment by allomov** [comment]
It looks like I recently had an error related to this issue: after I removed the PVC section from aws_route53_zone to change it from private to public, terraform wasn't re-created aws_route53_zone resource, so it was left private. Only manual invasion fixed the issue.
