### ISSUE TITLE
aws_rds_cluster resource: setting engine_version without point version causes a persistent diff

### ISSUE THREAD

**Issue by SarahRiley** [hashicorp/terraform-provider-aws#19814]
The aws resource `aws_db_instance` allows specifying an `engine_version` without the patch (9.6.x) or minor (10.x, 11.x) releases.  This is very useful when you have `auto_minor_version_upgrade` set to true, as then terraform doesn't try to revert you back to a previous point release after aws has upgraded your rds instance.

ie, valid values for `engine_version` on `aws_db_instance` are:
```
"9.6"
"9.6.16"
"11.5"
"11"
```

However, this does not work properly for `aws_rds_cluster`.  Setting `engine_version` to any of the 4 above does plan correctly, and does apply, but subsequent plans show a persistent diff:

```
  # aws_rds_cluster.rds will be updated in-place
    ~ resource "aws_rds_cluster" "rds" {
            apply_immediately                   = true
         ~ engine_version                      = "11.9" -> "11"
        < all other values unchanged>
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.7
hashicorp/aws 3.45.0

### Affected Resource(s)

* aws_rds_cluster

### Terraform Configuration Files

```
resource "aws_rds_cluster" "rds" {
           apply_immediately                   = true
           engine_version                         = "11"
           ...
}
```

### Expected Behavior

Terraform should have set the engine_version to 11 during the apply, and subsequent plans should have no change of `~ engine_version                      = "11.9" -> "11"`

### Actual Behavior

Persistent change of `~ engine_version                      = "11.9" -> "11"` as per the above

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`
3. `terraform plan`

**Comment by ewbankkit** [comment]
This issue has been addressed in https://github.com/hashicorp/terraform-provider-aws/pull/20211, released in [**v3.52.0**](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3520-july-29-2021) of the Terraform AWS Provider.
