### ISSUE TITLE
Error: error waiting for SSO Account Assignment for Principal (xxxxxx-xxxxx-xxxxx-xxxx) to be deleted: unexpected state 'FAILED', wanted target 'SUCCEEDED'. last error: %!s(<nil>)

### ISSUE THREAD

**Issue by javiortizmol** [hashicorp/terraform-provider-aws#19821]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_ssoadmin_account_assignment

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl

provider "aws" {
  version = "~> 3.43.0"

  region = "us-east-1"

  assume_role {
    role_arn = "arn:aws:iam::12345678:role/TerraformAdmin"
  }

  allowed_account_ids = [12345678]
}
```

### Debug Output

2021/06/15 21:11:57 [ERROR] eval: *terraform.EvalApplyPost, err: error waiting for SSO Account Assignment for Principal (9067609ef2-30043087-2abd-4768-8872-4c4f6bcff6f5) to be deleted: unexpected state 'FAILED', wanted target 'SUCCEEDED'. last error: %!s(<nil>)

### Expected Behavior

Account assigment removed.

### Actual Behavior

Error message trying to delete an account assigment. 
`Error: error waiting for SSO Account Assignment for Principal (9067609ef2-30043087-2abd-4768-8872-4c4f6bcff6f5) to be deleted: unexpected state 'FAILED', wanted target 'SUCCEEDED'. last error: %!s(<nil>)`

### Steps to Reproduce

1. Remove the resource aws_ssoadmin_account_assignment of the tf file.
2. `terraform apply`

**Comment by johnbooth** [comment]
Seeing similar issues when trying to remove route table association.

       Error: error waiting for Route Table Association (rtbassoc-03d15a5bdf1d8f10b) delete: unexpected state 'associated', wanted target ''. last error: %!s(<nil>)

**Comment by AntonNguyen97** [comment]
@johnbooth Hey, I've run into the same issue, did you find how to solve it?

**Comment by gdavison** [comment]
Hi @javiortizmol, are you still seeing this error? If so, can you please share the Terraform configuration for the `aws_ssoadmin_account_assignment` resource and include the debug log as described in https://www.terraform.io/internals/debugging?

**Comment by gdavison** [comment]
Since we haven't heard back, we're going to assume that this issue has been resolved in current versions of the provider. If you encounter this error with an up-to-date version of the provider, please open a new issue and include the terraform configuration and the debug log as described in https://www.terraform.io/internals/debugging
