### ISSUE TITLE
Apprunner github connection issue with `aws_apprunner_connection`

### ISSUE THREAD

**Issue by Prashant-jumpbyte** [hashicorp/terraform-provider-aws#19825]
Github connection stuck in pending handshake and service creation failed with "Failed to retrieve the latest commit from your source repository. Be sure you configure your service with a valid connection to your GitHub repository" message

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apprunner_connection As per the doc "After creation, you must complete the authentication handshake using the App Runner console." but complete handshake button is greyed out and it starts getting deleted as soon as GitHub connection is created.

**Comment by bryantbiggs** [comment]
I am not seeing this same behavior - I have been able to create several GitHub connections without issue
