### ISSUE TITLE
aws_lambda_event_source_mapping depends_on not respected in 3.45 version

### ISSUE THREAD

**Issue by alex1x** [hashicorp/terraform-provider-aws#19828]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform 0.13.2
aws provider 3.45

### Affected Resource(s)

`aws_lambda_event_source_mapping`

### Terraform Configuration Files

```hcl
resource "aws_lambda_event_source_mapping" "example" {
  event_source_arn = aws_sqs_queue.example.arn
  function_name    = aws_lambda_function.example.arn

  # Event source cannot be added until the lambda has permission to access the SQS queue
  depends_on = [aws_iam_role_policy.example]
}
```

### Expected Behavior

The depends_on is respected and `aws_lambda_event_source_mapping` is applied correctly

### Actual Behavior

The `depends_on` is ignored, it tries to create the `aws_lambda_event_source_mapping` before the IAM role has the permissions, and this error is produced:

`The provided execution role does not have permissions to call ReceiveMessage on SQS`

### Important Factoids

This works correctly in terraform provider version 3.42, but does not work in 3.45 (have not tested 3.43 or 3.44)

**Comment by ewbankkit** [comment]
@alex1x Thanks for raising this issue.
This is caused by the fix to #14042. It is not actually the `depends_on` that is failing but the fact that the event source mapping creation has to wait for the IAM role to propagate correctly.
I'll submit a fix.
