### ISSUE TITLE
volume_type validation should be allowed to be skipped when running against AWS Snowball Edge

### ISSUE THREAD

**Issue by SebTardif** [hashicorp/terraform-provider-aws#19839]
My AWS target is AWS Snowball Edge, the only two type of volume_type in this environment are: sbg1 (HDD) and sbp1 (SSD)

So when I execute, I get this false error from Terraform:  Error: expected root_block_device.0.volume_type to be one of [standard io1 io2 gp2 sc1 st1 gp3], got sbp1

**Comment by ewbankkit** [comment]
Related:

* #19068
