### ISSUE TITLE
sweeper/aws_backup_vault_policy: Sweeper should not fail on `AccessDeniedException`

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#19848]
The `aws_backup_vault_policy` sweeper should log a warning but not return an error when it receives an `AccessDeniedException`.

### Affected Resource

* aws_backup_vault_policy

**Comment by ewbankkit** [comment]
This may be related to EFS automated backups.
See the [Backup User Guide](https://docs.aws.amazon.com/efs/latest/ug/awsbackup.html#delete-backups).
