### ISSUE TITLE
sweeper/aws_transfer_server: Cannot sweep transfer servers with API Gateway identity provider

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#19850]
The sweeper sets the `force_destroy` parameter before calling the resource Delete operation. When the identity provider is set to `API_GATEWAY`, this fails with the error

> InvalidRequestException: Cannot list users on server with IdP type: API_GATEWAY

Do not set `force_destroy` when identity provider is `API_GATEWAY`. Confirm if `force_destroy` can be set when the identity provider is `AWS_DIRECTORY_SERVICE`.

### Affected Resource

* aws_transfer_server

**Comment by ewbankkit** [comment]
Yes, looking at the [API Reference](https://docs.aws.amazon.com/transfer/latest/userguide/API_CreateServer.html#TransferFamily-CreateServer-request-IdentityProviderType), users can only be listed if `identity_provider_type = "SERVICE_MANAGED"`.
