### ISSUE TITLE
Resource for creating AD users

### ISSUE THREAD

**Issue by GBrawl** [hashicorp/terraform-provider-aws#19853]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm raising this issue to check if there is any interest in a resource for creating ad users using the AWS WorkDocs API.

For our use case we wanted to create new users in a directory and then assign them to a new workspace created with Terraform (using the user_name argument of aws_workspaces_workspace). Using the web UI this was possible, but using Terraform this was rather difficult because there was no resource for creating AD users (except using the ad_user resource, but this requires having a machine running in the same VPC as the AD instance so Terraform can access it).

I already created this resource to show it is possible (see #19769). Please let us know if there is more interest to have this in the provider!

### New or Affected Resource(s)

* aws_ad_user

### Potential Terraform Configuration

```hcl
resource "aws_ad_user" "user" {
  email_address = "user@org.com"
  given_name = "Jane"
  organization_id = "d-********"
  password = "P4SSW0RD"
  surname = "Doe"
  username = "janedoe"
}
```

### References

* #19769

**Comment by wspitaels** [comment]
I need this too, I am currently manually creating every user pls implement!! ☹️

**Comment by LennertMertens** [comment]
Need this as well. Would be very welcome. This way you can automate setup of Amazon Workspaces using simple AD.

**Comment by LennertMertens** [comment]
I really need this, honestly I don't understand why this isn't a priority? It feels like this really is a missing feature, because there is no other way to automate this user creation.

**Comment by klborders** [comment]
Raise your hand if your terraform only deploys workspaces for 'Administrator'.
