### ISSUE TITLE
Macie 2 Classification Export Configuration Support

### ISSUE THREAD

**Issue by gingersnapz** [hashicorp/terraform-provider-aws#19856]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In order to configure where to store Macie's classification export location, a call to `put-classification-export-configuration` is required.

### New or Affected Resource(s)

* aws_macie2_classification_export

### Potential Terraform Configuration

```hcl
data "aws_kms_key" "macie_export" {
  key_id = "mykey/macie"
}

data "aws_s3_bucket" "macie_export" {
  bucket = "macie-classification-export"
}

// New Resource
resource "aws_macie2_classification_export" "test" {
  bucket_name = data.aws_s3_bucket.macie_export.name
  key_prefix  = "macie-folder/"
  kms_key_arn = data.aws_kms_key.macie_export.arn
}
```

### References

* https://docs.aws.amazon.com/fr_fr/cli/latest/reference/macie2/put-classification-export-configuration.html

**Comment by adv4000** [comment]
Workaround is here: https://www.chernsan.com/2021/09/08/terraform-local-exec/
