### ISSUE TITLE
Amazon EventBridge + PagerDuty expects event bus name with '/' which fails validation for aws_cloudwatch_event_bus

### ISSUE THREAD

**Issue by anirban1c** [hashicorp/terraform-provider-aws#19857]
Following on from this merge 
https://github.com/hashicorp/terraform-provider-aws/pull/16484

could the name in 
resource "aws_cloudwatch_event_bus" "sandbox-bot-bus" {
  name = "aws.partner/pagerduty.com/sandbox/incident-bot-event-bus"
}

be allowed '/' as we are using PagerDuty partner integration and it expects a bus name like 
aws.partner/pagerduty.com/{pagerduty-subdomain}-{eventSourceName}

ref: https://support.pagerduty.com/docs/amazon-eventbridge-integration-guide

Having to create the event bus as a manual step makes our entire IaaS and automation very cumbersom

many thanks
-anirban

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

2021-06-17T14:26:17.737Z [INFO]  Terraform version: 1.0.0
2021-06-17T14:26:17.738Z [INFO]  Go runtime version: go1.16.4
2021-06-17T14:26:17.738Z [INFO]  CLI args: []string{"/home/linuxbrew/.linuxbrew/Cellar/tfenv/2.2.1/versions/1.0.0/terraform", "-v"}
2021-06-17T14:26:17.739Z [INFO]  Loading CLI configuration from /home/linuxbrew/.terraformrc
2021-06-17T14:26:17.740Z [INFO]  CLI command args: []string{"version", "-v"}
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.14.1
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

resource "aws_cloudwatch_event_bus" "sandbox-bot-bus" {
  name = "aws.partner/pagerduty.com/sandbox/incident-bot-event-bus"
}

### Debug Output

╷
│ Error: expected value of name to match regular expression "^[a-zA-Z0-9._\\-]+$", got aws.partner/pagerduty.com/sandbox/incident-bot-event-bus
│ 
│   with module.lambda.aws_cloudwatch_event_bus.sandbox-bot-bus,
│   on ../../modules/lambda/lambda.tf line 25, in resource "aws_cloudwatch_event_bus" "sandbox-bot-bus":
│   25:   name = "aws.partner/pagerduty.com/sandbox/incident-bot-event-bus"
│ 
╵
╷
│ Error: expected value of event_bus_name to match regular expression "^[a-zA-Z0-9._\\-]+$", got aws.partner/pagerduty.com/sandbox/incident-bot-event-bus
│ 
│   with module.lambda.aws_cloudwatch_event_rule.pagerduty-webhook,
│   on ../../modules/lambda/lambda.tf line 33, in resource "aws_cloudwatch_event_rule" "pagerduty-webhook":
│   33:   event_bus_name = "aws.partner/pagerduty.com/sandbox/incident-bot-event-bus"
│ 

### Expected Behavior

event_bus_name should allow using '/' as specified by partner services else it breaks automation and introduces manual steps

### Actual Behavior

terraform plan fails on name validation
│ Error: expected value of name to match regular expression "^[a-zA-Z0-9._\\-]+$", got aws.partner/pagerduty.com/sandbox/incident-bot-event-bus
│ 
│   with module.lambda.aws_cloudwatch_event_bus.sandbox-bot-bus,
│   on ../../modules/lambda/lambda.tf line 25, in resource "aws_cloudwatch_event_bus" "sandbox-bot-bus":
│   25:   name = "aws.partner/pagerduty.com/sandbox/incident-bot-event-bus"
│

**Comment by ewbankkit** [comment]
@anirban1c Thanks for raising this issue.
Support for partner event bus names was merged in #19072, available in **v3.39.0** of the Terraform AWS Provider.
Please upgrade your provider version to at least this version.

**Comment by anirban1c** [comment]
thanks @ewbankkit somehow missed this when searching for it, saved me a lot of headache
