### ISSUE TITLE
Development Environment Setup Fails

### ISSUE THREAD

**Issue by KaguraKagura** [hashicorp/terraform-provider-aws#19863]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Environment
terraform version: `Terraform v1.0.0
on linux_amd64`
go version: `go1.16.5 linux/amd64`
OS: `NAME="Amazon Linux"  
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
kernel=5.4.116-64.217.amzn2int.x86_64`

### Expected Behavior
I am following the [Development Environment Setup](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/DEVELOPMENT.md) and its fails at the step of `make tools`

### Actual Behavior
`make tools` outputs: 
`cd awsproviderlint && go install .
cd tools && go install github.com/bflad/tfproviderdocs
go: github.com/terraform-linters/tflint@v0.28.1 requires
        github.com/hashicorp/terraform@v0.15.1 requires
        github.com/tencentcloud/tencentcloud-sdk-go@v3.0.82+incompatible: reading github.com/tencentcloud/tencentcloud-sdk-go/go.mod at revision v3.0.82: unknown revision v3.0.82
make: *** [tools] Error 1`

### Steps to Reproduce

1. `$ mkdir -p $HOME/development/terraform-providers/; cd $HOME/development/terraform-providers/
$ git clone git@github.com:terraform-providers/terraform-provider-aws`
2. `make tools`

Thank you!

**Comment by ewbankkit** [comment]
@KaguraKagura Thanks for raising this issue.
I am unable to reproduce this - Are you still seeing the error?
