### ISSUE TITLE
AWS MQ - RabbitMQ vertical scaling cause cluster recreation

### ISSUE THREAD

**Issue by schrius** [hashicorp/terraform-provider-aws#19874]
According to AWS vertical scaling won't trigger cluster recreation:
https://aws.amazon.com/about-aws/whats-new/2019/09/amazon-mq-introduces-vertical-scaling-for-message-brokers/#:~:text=Vertically%20scaling%20your%20message%20broker,message%20brokers%20in%20the%20cloud.

Based on my experiment, if the instance type was changed via AWS console, e.g. m5.large -> m5.xlarge the cluster would only need to reboot to update the instance type instead of recreating the entire cluster

With Terraform the cluster is forced to recreate when instance type change:
```
# module.rabbitmq_broker.aws_mq_broker.broker must be replaced
 -/+ resource "aws_mq_broker" "broker" {
         apply_immediately          = true
       ~ arn                        = "arn:aws:mq:us-east-1:xxxxxxxx" -> (known after apply)
       ~ authentication_strategy    = "simple" -> (known after apply)
         auto_minor_version_upgrade = false
         broker_name                = "rabbitmq-poc1"
         deployment_mode            = "CLUSTER_MULTI_AZ"
         engine_type                = "RabbitMQ"
         engine_version             = "3.8.11"
       ~ host_instance_type         = "mq.m5.large" -> "mq.m5.xlarge" # forces replacement
       ~ id                         = "xxxxxx" -> (known after apply)
       ~ instances                  = [
           - {
               - console_url = "https://xxxxxx.mq.us-east-1.amazonaws.com"
               - endpoints   = [
                   - "amqps://xxxxxx.mq.us-east-1.amazonaws.com:5671",
                 ]
               - ip_address  = ""
             },
         ] -> (known after apply)
```

**Comment by ewbankkit** [comment]
@schrius Thanks for raising this issue.
It has already been noticed in #13351. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
