### ISSUE TITLE
Default tags causes issues on creation of load balancer listener

### ISSUE THREAD

**Issue by danquack** [hashicorp/terraform-provider-aws#19888]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_lb_listener

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  default_tags {
    tags = {
      test  = "variable"
    }
  }
}


resource "aws_lb" "gateway" {
  name               = "gw-lb"
  internal           = false
  load_balancer_type = "gateway"
  subnets            = var.public_subnets.*.id
}

resource "aws_lb_listener" "gateway" {
  load_balancer_arn = aws_lb.gateway.arn
  tags_all          = {}

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.gateway.arn
  }
}

```

### Debug Output

```ccl
  # aws_lb_listener.gateway will be created
  + resource "aws_lb_listener" "gateway" {
      + arn               = (known after apply)
      + id                = (known after apply)
      + load_balancer_arn = "arn:aws:elasticloadbalancing:xxx:xxxx:loadbalancer/gwy/gw-lb/75e4a91cbbe26624"
      + protocol          = (known after apply)
      + ssl_policy        = (known after apply)
      + tags_all          = {
          + test  = "variable"
        }

      + default_action {
          + order            = (known after apply)
          + target_group_arn = "arn:aws:elasticloadbalancing:xxx:xxxx:loadbalancer/gwy/gw-lb/75e4a91cbbe26624"
          + type             = "forward"
        }
    }

```
### Expected Behavior
Creation

### Actual Behavior
```
error creating ELBv2 Listener (arn:aws-us-gov:elasticloadbalancing:xxxx:xxx:loadbalancer/gwy/gw-lb/75e4a91cbbe26624): ValidationError: You cannot specify tags on creation of a Gateway Load Balancer listener
│ 	status code: 400, request id: c82b732b-422d-438d-acad-bf02c685839a
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ewbankkit** [comment]
Gateway Load Balancer support in US GovCloud [announced this week](https://aws.amazon.com/about-aws/whats-new/2021/06/aws-gateway-load-balancer-is-now-available-in-the-aws-govcloud-us-regions/).

**Comment by derekmwright** [comment]
Default tags are also causing an issue with `aws_lb_target_group` resource with a protocol of GENEVE set:
```
╷
│ Error: error creating LB Target Group: ValidationError: You cannot specify tags on creation of a GENEVE target group
│ 	status code: 400, request id: 8cb319b2-5e64-41de-93a1-216bfd20d41d
│
│   with aws_lb_target_group.firewall,
│   on loadbalancer.tf line 9, in resource "aws_lb_target_group" "firewall":
│    9: resource "aws_lb_target_group" "firewall" {
│
╵
```
This is in govcloud partition as well.
