### ISSUE TITLE
s3 does not allow same events on multiple lambda functions

### ISSUE THREAD

**Issue by hhmahmood** [hashicorp/terraform-provider-aws#19912]
We have a use case in which we have 1 bucket and 2 lambda functions (staging and production) that will be triggered on s3:ObjectCreate event.

It looks like [this example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_notification#trigger-multiple-lambda-functions) is misleading, following is the code snippet that I am applying by following the example in terraform [document](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_notification#trigger-multiple-lambda-functions). 

```
data "aws_s3_bucket" "s3-export" {
  bucket = "ww-export"
}

data "aws_lambda_function" "s3-trigger-staging" {
  function_name = "s3-trigger-staging"
}

data "aws_lambda_function" "s3-trigger-production" {
  function_name = "s3-trigger-production"
}


resource "aws_s3_bucket_notification" "mapp-export" {
  bucket = data.aws_s3_bucket.s3-export.bucket

  lambda_function {
    lambda_function_arn = data.aws_lambda_function.s3-trigger-staging.arn
    events = ["s3:ObjectCreated:*"]
  }
  lambda_function {
    lambda_function_arn = data.aws_lambda_function.s3-trigger-production.arn
    events = ["s3:ObjectCreated:*"]
  }
}
```

When I apply the terraform it gives me the error

`Error: Error putting S3 notification configuration: InvalidArgument: Configurations overlap. Configurations on the same bucket cannot share a common event type.
`
I also tried manually adding the same event on both lambdas manually and received the same error. This link below in the aws forum discussion tells the same thing.

https://forums.aws.amazon.com/thread.jspa?threadID=181878

Can you please verify?

Best,

**Comment by DrFaust92** [comment]
Hi, the documented example uses different filters while your config does not have that differentiator. So s3 might consider it unique enough with different filters while the above isn’t.

**Comment by hhmahmood** [comment]
@DrFaust92  Thanks for the answer, which filters do you mean?

**Comment by DrFaust92** [comment]
I don’t think it’s supported by AWS in this manner(according to the support forum) so obviously the terraform provider can’t either. But! You can use Sns and fan out to several lambdas that might do the trick.

**Comment by hhmahmood** [comment]
Thanks @DrFaust92. I got my answer. I will close the ticket.
