### ISSUE TITLE
need aws_subnet_tag resource

### ISSUE THREAD

**Issue by DonBower** [hashicorp/terraform-provider-aws#19926]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For EKS Cluster helm applications, a service that creates a load balancer, requires subnets to be tagged a certian way., namely:
```
Key: kubernetes.io/cluster/yourEKSClusterName
Value: shared
```

### New or Affected Resource(s)

* aws_subnet cannot be used, because subnets are created via separate process.
* **aws_subnet_tag** would operate similar to `aws_security_group_rule` is external to` aws_security_group`.

### Potential Terraform Configuration

```hcl
resource aws_subnet_tag eksClusterLB {
    for_each = var.subnetIDs
        subnet_id = each.key
        tag {
             key = "kubernetes.io/cluster/yourEKSClusterName"
             value = "shared"
        }
}
```

### References

* [AWS EKS LB troubleshooting](https://aws.amazon.com/premiumsupport/knowledge-center/eks-load-balancers-troubleshooting/)

**Comment by ewbankkit** [comment]
@DonBower The [`aws_ec2_tag`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_tag) resource should provide the functionality you're looking for.

**Comment by DonBower** [comment]
Yes, works perfectly. _ec2_ through me.
