### ISSUE TITLE
aws_cognito_user_pool_client default_redirect_uri validation makes it mandatory

### ISSUE THREAD

**Issue by emulanob** [hashicorp/terraform-provider-aws#19924]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/aws v3.46.0

### Affected Resource(s)

* aws_cognito_user_pool_client

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

Example resource block:
```hcl
variable callback_urls {
  default = []
  type = list(string)
}

variable default_redirect_uri {
  default = ""
}

resource "aws_cognito_user_pool_client" "client" {
  name                 = "client"
  user_pool_id         = aws_cognito_user_pool.pool.id
  callback_urls        = var.callback_urls
  default_redirect_uri = var.default_redirect_url
}
```

### Expected Behavior

The empty values will be ignored and the client will be created without these attributes.
### Actual Behavior

A terraform plan throws the following errors:
```
Error: expected length of default_redirect_uri to be in the range (1 - 1024), got 
Error: invalid value for callback_urls.0 (must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}]+`)
```

### Other info

I'm not sure in which version that validation was introduced because I haven't really touched this particular module in a while, but what it causes is basically making two optional attributes (`default_redirect_uri`) mandatory. This makes writing reusable modules very complicated as the attribute cannot be null nor empty.
The only way I could get rid of the error was by commenting out the attribute, but again, that makes writing a reusable module impossible. 

Maybe I'm missing something here? Please let me know if I can provide any more info.
Thanks.

**Comment by ewbankkit** [comment]
Related: #14935.
