### ISSUE TITLE
Terraform aws provider plugin crashed

### ISSUE THREAD

**Issue by efernandes-dev-ops** [hashicorp/terraform-provider-aws#19930]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.45.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* aws_db_parameter_group
* aws_iam_role_policy_attachment
* aws_route_table_association
* aws_nat_gateway
* aws_subnet
* aws_route_table
* aws_launch_template
* aws_lb
* aws_iam_policy
* aws_iam_role

### Debug Output

https://gist.github.com/efernandes-dev-ops/32b0046ac74fef82484050e1ce7484ec

### Panic Output

https://gist.github.com/efernandes-dev-ops/2dad388d49e3e7de79f4b9b06f248494

### Expected Behavior

I was running a terraform destroy cmd, so the expected behaviour would be to see a list of resources being destroyed

### Actual Behavior

Received Error: Request cancelled on the aws resources above.

### Steps to Reproduce

1. `terraform destroy`

**Comment by ewbankkit** [comment]
```
panic: interface conversion: interface {} is nil, not *aws.AWSClient

goroutine 90 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsLbRead(0xc0007da680, 0x0, 0x0, 0xc022270, 0xc00008c480)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_lb.go:355 +0x848
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0014f7a40, 0x8859ae8, 0xc0007c68c0, 0xc0007da680, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0014f7a40, 0x8859ae8, 0xc0007c68c0, 0xc002142150, 0x0, 0x0, 0xc0007d0700, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00011af30, 0x8859ae8, 0xc0007c68c0, 0xc0007c6900, 0xc0007c68c0, 0x100b665, 0x781f9a0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc001fa1f00, 0x8859b90, 0xc0007c68c0, 0xc0007c5020, 0xc001fa1f00, 0xc001ec9ef0, 0xc0006d9ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x7aefd20, 0xc001fa1f00, 0x8859b90, 0xc001ec9ef0, 0xc0007c4fc0, 0x0, 0x8859b90, 0xc001ec9ef0, 0xc002146000, 0x543)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000723180, 0x887b818, 0xc0017c8600, 0xc001b2c500, 0xc000334690, 0xbfe19d0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000723180, 0x887b818, 0xc0017c8600, 0xc001b2c500, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00051d500, 0xc000723180, 0x887b818, 0xc0017c8600, 0xc001b2c500)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.45.0_x5 plugin crashed!
```

**Comment by ewbankkit** [comment]
Similar:

* #19807
* #19740
* #19601
* #19788

**Comment by efernandes-dev-ops** [comment]
Thanks @ewbankkit . Will close this down.

So I was able to get around this bug, I had a bug in my terraform code that was resulting in an apply not being run successfully. After fixing my terraform code and running apply and then running destroy I didn't get the above error.

**Comment by ewbankkit** [comment]
@efernandes-dev-ops Thanks for responding.

> resulting in an apply not being run successfully

Do you mean that before that `terraform destroy` that crashed you had a `terraform apply` that (partially) failed?
We are seeing a cluster of crashes such as the one you experienced and are trying to find common patterns.

**Comment by efernandes-dev-ops** [comment]
@ewbankkit 
Yes, my `terraform apply` partially failed due to a mistake in my code. After fixing my code I ran `terraform apply` which was successful and then I ran `terraform destroy` again which also ran successfully.
