### ISSUE TITLE
aws_kinesis_firehose_delivery_stream still doesn't save processors configuration properly

### ISSUE THREAD

**Issue by dvishniakov** [hashicorp/terraform-provider-aws#19936]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform: 0.14.11 (doesn't matter much because this is reproduced in other versions)
AWS Provider: 3.41

### Affected Resource(s)

* aws_kinesis_firehose_delivery_stream

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream
resource "aws_kinesis_firehose_delivery_stream" "default" {
  name        = local.firehose_name
  tags        = var.tags
  destination = "extended_s3"

  extended_s3_configuration {
    role_arn   = var.firehose_role_arn
    bucket_arn = var.log_target_s3_bucket_arn

    prefix              = "prefix"
    error_output_prefix = "prefix"

    buffer_size        = var.buffer_size
    buffer_interval    = var.buffer_interval
    compression_format = var.compression_format
    kms_key_arn        = var.kms_key_arn

    # https://docs.aws.amazon.com/firehose/latest/dev/data-transformation.html
    processing_configuration {
      enabled = true

      processors {
        type = "Lambda"

        parameters {
          parameter_name  = "LambdaArn"
          parameter_value = var.log_processing_lambda_arn
        }

        # Up to 3 MB by default
        parameters {
          parameter_name  = "BufferSizeInMBs"
          parameter_value = "3"
        }

        parameters {
          parameter_name  = "BufferIntervalInSeconds"
          parameter_value = "300"
        }
      }
    }
  }

}
```

### Debug Output

      ~ extended_s3_configuration {
            # (8 unchanged attributes hidden)

          ~ processing_configuration {
                # (1 unchanged attribute hidden)

              ~ processors {
                    # (1 unchanged attribute hidden)

                  ~ parameters {
                      ~ parameter_name  = "BufferIntervalInSeconds" -> "BufferSizeInMBs"
                      ~ parameter_value = "300" -> "3"
                    }
                  + parameters {
                      + parameter_name  = "BufferIntervalInSeconds"
                      + parameter_value = "300"
                    }
                    # (1 unchanged block hidden)
                }
            }
            # (1 unchanged block hidden)
        }

### Expected Behavior
No changes in infra

### Actual Behavior
Terraform adds `BufferSizeInMBs` each time.

### Steps to Reproduce

1. `terraform apply`

### References

https://github.com/hashicorp/terraform-provider-aws/issues/4392
- See the previous to last comment there - seems didn't work after merge.

**Comment by tlkamp** [comment]
I am also experiencing this issue. It is also present when using nested `processors` blocks (i.e. under a `splunk_configuration`).

I did some investigating and found that the setting is being applied to the resource properly but the parameter is not being saved in the state file, resulting in the perpetual diff.

**Comment by ewbankkit** [comment]
Related:

* #9827

**Comment by dkujawski** [comment]
We are hitting this bug now.

I am pretty sure there is a bug in [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/firehose/delivery_stream.go#L653) where the default values are being evaluated.  The logic needs to be reviewed, it doesn't seem like this will ever read the actual values from AWS. 

```go
	// It is necessary to explicitly filter this out
	// to prevent diffs during routine use and retain the ability
	// to show diffs if any field has drifted
	defaultLambdaParams := map[string]string{
		"NumberOfRetries":         "3",
		"RoleArn":                 roleArn,
		"BufferSizeInMBs":         "3",
		"BufferIntervalInSeconds": "60",
	}

	processors := make([]interface{}, len(pc.Processors))
	for i, p := range pc.Processors {
		t := aws.StringValue(p.Type)
		parameters := make([]interface{}, 0)

		for _, params := range p.Parameters {
			name := aws.StringValue(params.ParameterName)
			value := aws.StringValue(params.ParameterValue)

			if t == firehose.ProcessorTypeLambda {
				// Ignore defaults
				if v, ok := defaultLambdaParams[name]; ok && v == value {
					continue
				}
			}
```

**Comment by Iguanod** [comment]
@dkujawski the values are read from AWS, if you follow the function calls the `pc` parameter in that function comes from the call to `FindDeliveryStreamByName` in `resourceDeliveryStreamRead`.

The problem is not in removing the values if they match the defaults, the logic is correct and I assume it is necessary to do so according to the comment. Besides, that behaviour is documented in https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream (see the note in the `parameters` block configuration).

The issue here is that the default value for the buffer size is assumed to be 3MB, while in reality it is 1MB. I don't know if the default value was indeed 3MB at some point in the past, but right now new delivery streams are created with 1MB by default (as documented in https://docs.aws.amazon.com/firehose/latest/dev/data-transformation.html).
