### ISSUE TITLE
Optional principals in aws_iam_policy_document

### ISSUE THREAD

**Issue by supergibbs** [hashicorp/terraform-provider-aws#19935]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I have an assume role policy for ecs so I have the folllowing `principals`
```hcl
principals {
  type        = "Service"
  identifiers = ["ecs-tasks.amazonaws.com"]
}
```
In my dev environment, I'd like to allow my developers to assume this role to test locally
```hcl
principals {
  type        = "AWS"
  identifiers = [var.software_engineer_role_arns[var.aws_account_id]]
}
```
With the above I'd like to set the prod account value to `null` or `""` so it doesn't apply but that doesn't work currently. Workaround would be two `aws_iam_policy_document`s and apply the correct one or create a dummy role no one uses and set it to that. Neither are very elegant. I'd be open to an `enabled` attribute too. 

### New or Affected Resource(s)

* aws_iam_policy_document

### Potential Terraform Configuration

Have terraform not include the principal if one of the following is detected.

```hcl
principals {
  type        = "AWS"
  identifiers = [null]
}

principals {
  type        = "AWS"
  identifiers = [""]
}

principals {
  type        = "AWS"
  identifiers = [""]
  enabled = false
}
```

### References

* n/a

**Comment by ewbankkit** [comment]
@supergibbs Thanks for raising this issue.
Have you looked into using a [Terraform `dynamic` block](https://www.terraform.io/docs/language/expressions/dynamic-blocks.html) for the `principals` blocks that you want to swap in an out?

**Comment by supergibbs** [comment]
Ah thanks for that! Yes, that works great. For anyone interested, here is my working example:

```hcl
variable "additional_principals" {
  type    = list(object({ type = string, identifiers = list(string) }))
  default = []
}

data "aws_iam_policy_document" "task_assume_role_ecs_tasks" {
  statement {
    actions = ["sts:AssumeRole"]

    dynamic "principals" {
      for_each = concat([{
        type        = "Service"
        identifiers = ["ecs-tasks.amazonaws.com"]
      }], var.additional_principals)

      content {
        type        = principals.value["type"]
        identifiers = principals.value["identifiers"]
      }
    }
  }
}
```
