### ISSUE TITLE
aws_cognito_user_pool perpetual diff on lambda_config : custom_email_sender, custom_sms_sender

### ISSUE THREAD

**Issue by petewilcock** [hashicorp/terraform-provider-aws#19942]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.15.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.46.0

### Affected Resource(s)

* aws_cognito_user_pool

### Terraform Configuration Files

Creation of Cognito User Pool since v.3.45 (when this feature was introduced) seems to result in a perpetual diff when other lambda_config is specified. e.g.
```hcl
  lambda_config {
    pre_token_generation = var.lambda_pre_token
  }
```

in my configuration, the `var.lambda_pre_token` can be optionally `null` - when set as `null` the following diff is perpetual. 

```hcl
      + lambda_config {
          + custom_email_sender {
              + lambda_arn     = (known after apply)
              + lambda_version = (known after apply)
            }

          + custom_sms_sender {
              + lambda_arn     = (known after apply)
              + lambda_version = (known after apply)
            }
        }
```

### Expected Behavior

When no custom_email_sender or custom_sms_sender is set, do not attempt to any push values. 

### Actual Behavior

Perpetual diff trying to add values for this, even though no configuration block is set for these, and other set configuration is otherwise valid. 

### Steps to Reproduce

1. `terraform apply`

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/16760

**Comment by ewbankkit** [comment]
Related: https://github.com/hashicorp/terraform-provider-aws/pull/16502.

**Comment by Nogginboink** [comment]
Plus one.

**Comment by lgallard** [comment]
https://github.com/hashicorp/terraform-provider-aws/pull/16502 is relataed in the sense it introdecuded the issue.
