### ISSUE TITLE
Add support for replica modification sync in S3

### ISSUE THREAD

**Issue by rafaljanicki** [hashicorp/terraform-provider-aws#19941]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has introduced two way replication configuration on December 1st 2020 (https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-s3-replication-adds-support-two-way-replication/). To enable that, it requires to set `ReplicaModifications` on `SourceSelectionCriteria` under replica configuration

### New or Affected Resource(s)

* aws_s3_bucket

### Potential Terraform Configuration

```hcl
resource "aws_s3_bucket" "source" {
  provider = aws.central
  bucket   = "tf-test-bucket-source-12345"
  acl      = "private"

  versioning {
    enabled = true
  }

  replication_configuration {
    role = aws_iam_role.replication.arn

    rules {
      id     = "foobar"
      prefix = "foo"
      status = "Enabled"

      destination {
        bucket        = aws_s3_bucket.destination.arn
        storage_class = "STANDARD"
      }
    
      source_selection_criteria {
        replica_modifications {
          status = "Enabled"
        }
      }
    }
  }
}
```

**Comment by ewbankkit** [comment]
@rafaljanicki Thanks for raising this issue.
It has already been noticed in #16539. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
