### ISSUE TITLE
Support `PropagateTags` attribute in `cloudwatch_event_target` with `ecs_target`

### ISSUE THREAD

**Issue by dimisjim** [hashicorp/terraform-provider-aws#19948]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The AWS Go SDK was updated yesterday which added supported for propagating tags to the ECS tasks launched from Cloudwatch Events:

https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_EcsParameters.html#eventbridge-Type-EcsParameters-PropagateTags

https://github.com/aws/aws-sdk-go/pull/3974

It would be super cool to have this in terraform as well.

It could also be set by default, as "TASK_DEFINITION" is the only valid value at the moment + it's useful to have anyway.

### New or Affected Resource(s)

* cloudwatch_event_target

### Potential Terraform Configuration

```hcl

resource "aws_cloudwatch_event_target" "ecs_scheduled_task" {
...

  ecs_target {
    task_count          = 1
    task_definition_arn = aws_ecs_task_definition.task_name.arn
    propagate_tags      = "TASK_DEFINITION"
  }

...
}

```

### References

Other related feature requests for `cloudwatch_event_target` and `ecs_target`

* https://github.com/hashicorp/terraform-provider-aws/issues/17185
* https://github.com/hashicorp/terraform-provider-aws/issues/19949

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.38.66](https://github.com/aws/aws-sdk-go/releases/tag/v1.38.66): #19940.
