### ISSUE TITLE
Can not use health_check attribute in aws_lb_target_group

### ISSUE THREAD

**Issue by EdgyEdgemond** [hashicorp/terraform-provider-aws#19950]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.46.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* aws_lb_target_group

### Terraform Configuration Files
```
resource "aws_lb_target_group" "test" {
  name     = "test"
  port     = 80
  protocol = "HTTP"
  health_check = {
     path = "/status"
  }
}

```

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output
```
│ Error: Unsupported argument
│ 
│   on main.tf line 525, in resource "aws_lb_target_group" "test":
│  525:   health_check = {
│ 
│ An argument named "health_check" is not expected here. Did you mean to define a block of type
│ "health_check"?
```

### Expected Behavior

Load balancer is created with healthcheck other than default `/` status check

### Actual Behavior

Can only create load balancer with default health check

### Steps to Reproduce

1. `terraform apply`

**Comment by madhu2852** [comment]
you config should look like below: there should no "=" after health check. It is a block not a parameter.
```hcl
resource "aws_lb_target_group" "gwlb_tg" {
  name     = "gwlb-tg"
  port     = 6081
  protocol = "GENEVE"
  target_type = "instance"
  vpc_id   = var.vpc
  
  tags = {
   "Name" = "test"
 }
  health_check {
    port = 80
    protocol = "HTTP"
    interval = 20
    timeout = 15
    unhealthy_threshold = 10
  }
}
```

**Comment by EdgyEdgemond** [comment]
smh... thanks :D
