### ISSUE TITLE
EKS KMS Envelope Encryption: InvalidParameterException: Encryption is already enabled on the cluster

### ISSUE THREAD

**Issue by petewilcock** [hashicorp/terraform-provider-aws#19968]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform 0.15.5
hashicorp/aws v3.47.0

### Affected Resource(s)

* aws_eks_cluster

### Terraform Configuration Files

Existing EKS cluster 1.19 being upgraded to 1.20. Existing configuration from previous cluster creation:

```hcl
 encryption_config {
    provider {
      key_arn = aws_kms_key.kms.arn
    }
    resources = ["secrets"]
  }
```

### Debug Output

```
module.eks-cluster.aws_eks_cluster.eks: Still modifying... [id=eks-shared-cluster-nonprod, 24m0s elapsed]

Error: error associating EKS Cluster (eks-shared-cluster-nonprod) encryption config: InvalidParameterException: Encryption is already enabled on the cluster
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "cf90ed8e-4ffc-4976-8e84-20cc2a05fd52"
  },
  ClusterName: "eks-shared-cluster-nonprod",
  Message_: "Encryption is already enabled on the cluster"
}
```

### Expected Behavior

Existing KMS association should not be affected by upgrade. 

### Actual Behavior

Error thrown, although a re-run of terraform apply moved past the error on second attempt. 

### Steps to Reproduce

Existing EKS cluster 1.19 being upgraded to 1.20 with existing KMS association. 

1. `terraform apply`

### Important Factoids

Looks to have been introduced in 3.47.0 from referenced issue. 

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/17952

**Comment by ewbankkit** [comment]
@petewilcock Thanks for raising this issue.
I assume that the `encryption_config` wasn't updated in your Terraform code, just the Kubernetes version?
Would you have the output from the `terraform plan` (or equivalent) for the operation that failed?

**Comment by petewilcock** [comment]
> Would you have the output from the `terraform plan` (or equivalent) for the operation that failed?

Sure thing, I don't think it's too verbose to paste inline for the relevant resource:

```
# module.eks-cluster.aws_eks_cluster.eks will be updated in-place
  ~ resource "aws_eks_cluster" "eks" {
        id                        = "eks-shared-cluster-nonprod"
        name                      = "eks-shared-cluster-nonprod"
        tags                      = {
            "ProjectName"      = "**redacted**"
            "eks:cluster_name" = "eks-shared-cluster-nonprod"
            "provisioner"      = "Created by Terraform"
        }
      ~ version                   = "1.19" -> "1.20"
        # (10 unchanged attributes hidden)



        # (3 unchanged blocks hidden)
    }
```

**Comment by ewbankkit** [comment]
I can reproduce this.
I'll investigate and fix...
