### ISSUE TITLE
aws_default_security_group cannot be destroyed when vpc is manually deleted

### ISSUE THREAD

**Issue by ialidzhikov** [hashicorp/terraform-provider-aws#19965]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform version
Terraform v0.12.31
+ provider.aws v3.47.0
```

### Affected Resource(s)

* aws_default_security_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

- main.tf

```hcl
provider "aws" {
  access_key = var.ACCESS_KEY_ID
  secret_key = var.SECRET_ACCESS_KEY
  region     = "eu-west-1"
}

resource "aws_vpc_dhcp_options" "vpc_dhcp_options" {
  domain_name         = "eu-west-1.compute.internal"
  domain_name_servers = ["AmazonProvidedDNS"]
}

resource "aws_vpc" "vpc" {
  cidr_block           = "10.250.0.0/16"
  enable_dns_support   = true
  enable_dns_hostnames = true
}

resource "aws_vpc_dhcp_options_association" "vpc_dhcp_options_association" {
  vpc_id          = aws_vpc.vpc.id
  dhcp_options_id = aws_vpc_dhcp_options.vpc_dhcp_options.id
}

resource "aws_default_security_group" "default" {
  vpc_id = aws_vpc.vpc.id
}
```

### Debug Output

Not applicable.

### Panic Output

Not applicable.

### Expected Behavior

`terraform destroy` to be able to destroy even when the vpc is manually deleted.

### Actual Behavior

`terraform destroy` fails to destroy when the vpc is manually deleted.

### Steps to Reproduce

1. `terraform apply`

```
$ terraform apply -var-file=creds.tfvars

aws_vpc_dhcp_options.vpc_dhcp_options: Creating...
aws_vpc.vpc: Creating...
aws_vpc_dhcp_options.vpc_dhcp_options: Creation complete after 2s [id=dopt-0777c3b2a92db1234]
aws_vpc.vpc: Still creating... [10s elapsed]
aws_vpc.vpc: Creation complete after 19s [id=vpc-06e6705da603f1234]
aws_vpc_dhcp_options_association.vpc_dhcp_options_association: Creating...
aws_default_security_group.default: Creating...
aws_vpc_dhcp_options_association.vpc_dhcp_options_association: Creation complete after 1s [id=dopt-0777c3b2a92db1234-vpc-06e6705da603f1234]
aws_default_security_group.default: Creation complete after 2s [id=sg-0505854f62efb1234]

Apply complete! Resources: 4 added, 0 changed, 0 destroyed.
```

2. Delete manually the created vpc

```
$ aws ec2 delete-vpc --vpc-id vpc-06e6705da603f1234
```

3. Ensure that `terraform destroy` fails to refresh the aws_default_security_group

```
$ terraform destroy -var-file=creds.tfvars
aws_vpc_dhcp_options.vpc_dhcp_options: Refreshing state... [id=dopt-0777c3b2a92db1234]
aws_vpc.vpc: Refreshing state... [id=vpc-06e6705da603f1234]
aws_vpc_dhcp_options_association.vpc_dhcp_options_association: Refreshing state... [id=dopt-0777c3b2a92db1234-vpc-06e6705da603f1234]
aws_default_security_group.default: Refreshing state... [id=sg-0505854f62efb1234]

Error: InvalidGroup.NotFound: The security group 'sg-0505854f62efb1234' does not exist
	status code: 400, request id: <omitted>

```

### References

* #0000

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/af2d5c0ad54f38f35898413300892b5a58f78291/aws/resource_aws_default_security_group.go#L269-L277

Addressed in #18433.
