### ISSUE TITLE
Route53 Record Forces Replacement for Unchanged Name

### ISSUE THREAD

**Issue by crawforde** [hashicorp/terraform-provider-aws#19960]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform: v0.14.5
Provider: v3.46.0

### Affected Resource(s)

aws_route53_record

### Terraform Configuration Files

I am performing a terraform import of some existing route53 records. The record configuration includes a `for_each` loop, but for simplicity, I've shown two record configurations below and I anonymized the data. Note that some records already existed in the terraform state, and others have been imported. Assume here that the record associated with `endpoint1` is already in the state (created by terraform) and that the record associated with `endpoint2` has just been imported. Assume that the route53 domain is `subdomain.company.com`.

```hcl
resource "aws_route53_record" "name1_endpoint1" {
  zone_id = "MYZONEID"
  name    = "name1"
  type    = "A"
  ttl     = "300"
  records = [10.15.99.249]
  set_identifier = "Name1Endpoint1"
  multivalue_answer_routing_policy = true
  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_route53_record" "name1_endpoint2" {
  zone_id = "MYZONEID"
  name    = "name1"
  type    = "A"
  ttl     = "300"
  records = [10.33.80.232]
  set_identifier = "Name1Endpoint2"
  multivalue_answer_routing_policy = true
  lifecycle {
    create_before_destroy = true
  }
}
```

### Expected Behavior

`terraform apply` command should show no diffs.

### Actual Behavior

The problem is that the name field is forcing a replacement of the just-imported record, even though the name is not changing on the actual resource in AWS. If I run `terraform apply`, I get the following output:

```
# aws_route53_record.name1_endpoint2 must be replaced
-/+ resource "aws_route53_record" "name1_endpoint2" {
      + allow_overwrite                  = (known after apply)
      ~ fqdn                             = "name1.subdomain.company.com" -> (known after apply)
      ~ id                               = "MYZONEID_name1_A_Name1Endpoint2" -> (known after apply)
      ~ name                             = "name1.subdomain.company.com" -> "name1" # forces replacement
        # (6 unchanged attributes hidden)
    }
```
As expected, if I try applying it, terraform returns an error because the record already exists.

If I change the configuration so that the full domain name is included (i.e. `name = "name1.subdomain.company.com"`), then I get the some problem with the other non-imported record:

```
-/+ resource "aws_route53_record" "name1_endpoint1" {
      + allow_overwrite                  = (known after apply)
      ~ fqdn                             = "name1.subdomain.company.com" -> (known after apply)
      ~ id                               = "MYZONEID_name1_A_Name1Endpoint1" -> (known after apply)
      ~ name                             = "name1" -> "name1.subdomain.company.com" # forces replacement
        # (6 unchanged attributes hidden)
    }
```

The only solution would be to remove the lifecycle rule, destroy the record, and recreate it, which is not an acceptable option in a production environment.

I suspect the problem stems from the fact that AWS gracefully handles record creation regardless of whether the route53 zone domain is included in the record name or left out. It would be helpful if Terraform also disregarded everything after the first `.` character when comparing record names.

### Steps to Reproduce

1. Create a hosted zone with one A record that has a multivalue routing policy and a unique set identifier.
2. Copy the configuration above and change values to match your specific hosted zone and domain. Make the first record have the same name as the record you created, but give it a different IP address and set identifier.
3. Run `terraform apply --target aws_route53_record.name1_endpoint1` to create the record.
4. Now update the configuration of the second record to match the record you created manually in the first step. Import it with `terraform import aws_route53_record.name1_endpoint1 [USE YOUR SPECIFIC IDENTIFIER HERE]`. (Refer to [docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_record) explaining how to import Route53 records)
5. Run `terraform apply`.

* #0000

**Comment by atrinchillo-mwb** [comment]
I can confirm the issue also on provider registry.terraform.io/hashicorp/aws v3.45.0

**Comment by atrinchillo-mwb** [comment]
I would like to add that this also happens when we use data resource like. 
data "aws_route53_zone" "this" ...
