### ISSUE TITLE
aws_elasticsearch_domain_saml_options subject_key default differs from AWS

### ISSUE THREAD

**Issue by timcosta** [hashicorp/terraform-provider-aws#19966]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```bash
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.47.0
+ provider registry.terraform.io/hashicorp/azuread v1.5.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/phillbaker/elasticsearch v1.5.7
```

### Affected Resource(s)

* aws_elasticsearch_domain_saml_options (new in 3.47.0)

### Terraform Configuration Files

Broken configuration:
```hcl
resource "aws_elasticsearch_domain_saml_options" "main" {
  domain_name = module.elasticsearch.domain_name

  saml_options {
    enabled = true
    roles_key = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"

    idp {
      entity_id = local.saml_entity_id
      metadata_content = chomp(local.config.saml_metadata)
    }
  }
}
```

Working configuration:
```hcl
resource "aws_elasticsearch_domain_saml_options" "main" {
  domain_name = module.elasticsearch.domain_name

  saml_options {
    enabled = true
    roles_key = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"
    subject_key = ""

    idp {
      entity_id = local.saml_entity_id
      metadata_content = chomp(local.config.saml_metadata)
    }
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The new resource sets `NameID` as the [default value](https://github.com/hashicorp/terraform-provider-aws/pull/19497/files#diff-d0a4b19035d79de10be50979509d0dd73c24d2edd958c42f9b35f853b06f7bebR89) which at a glance appears to match the AWS configuration, but is actually different. Here's what AWS says:
![image](https://user-images.githubusercontent.com/3916501/123422422-2fdbbe00-d58c-11eb-92f9-e013c2486968.png)

The difference is the usage of the words `element` and `attribute`.

### Actual Behavior

This module's default behavior is to look for an attribute named `NameID` rather than letting AWS default to looking at an `element` called `NameID`. This caused our Kibana to 500 consistently after the SAML response because it was looking for an attribute that didnt exist.

### Steps to Reproduce

1. Make an AWS ES Cluster
2. Grab some SAML federation data from a SAML provider that uses the NameID element to identify users such as AzureAD
3. Attempt to configure SAML using `aws_elasticsearch_domain_saml_options` and note how the default behavior of the resource results in 500s, but inputting the same exact data on AWS directly results in successful attempts
4. Set `aws_elasticsearch_domain_saml_options::saml_options.subject_key = ""` and see that the terraform resource now allows successful SAML auth

### Important Factoids

Nothing important to know

### References

None that haven't been cited already.

**Comment by Jacendb** [comment]
Hello!
It's been 6 months and the associated PR is still open. It's one line of code and two doc changes.
Any idea of when this could be merged?
