### ISSUE TITLE
ECS capacity provider resource not automate create Services Linked role for ECS

### ISSUE THREAD

**Issue by MaoChhaya** [hashicorp/terraform-provider-aws#19977]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v1.0.1
+ provider registry.terraform.io/hashicorp/aws v3.47.0

```
### Affected Resource(s)
* aws_ecs_capacity_provider

### Terraform Configuration Files
```hcl
resource "aws_ecs_capacity_provider" "main" {
    name = "est-test"

    auto_scaling_group_provider {
        auto_scaling_group_arn         = aws_autoscaling_group.main.arn
        managed_termination_protection = "ENABLED"

        managed_scaling {
            maximum_scaling_step_size = 1000
            minimum_scaling_step_size = 1
            status                    = "ENABLED"
            target_capacity           = 75
        }
    }
}

resource "aws_ecs_cluster" "main" {
    name = "myECSCluster"
    capacity_providers = [
        aws_ecs_capacity_provider.main.name,
    ]

    setting {
        name  = "containerInsights"
        value = "enable"
    }
}
```

### Expected Behavior

The aws provider should automate create the Service linked role for ECS like the resource `aws_ecs_cluster` because  `aws_ecs_cluster` depends on `aws_ecs_capacity_provider` if they are created at the same time.

**Note**: It is possible to create Service Linked role for ECS with provider `aws_iam_service_linked_role` but let's imagine that if I would like to create a new ECS Cluster for testing with the terraform configuration. It gonna error on the resource `aws_iam_service_linked_role` creation AWS Services Linked role. 

### Actual Behavior
`Error: error creating ECS Capacity Provider (est-test): ClientException: ECS Service Linked Role does not exist. Please create a Service linked role for ECS and try again.`

### Steps to Reproduce
1. Using the above terraform code to create ECS Capacity provider and ECS Cluster
2. It is find with `terraform validate` and `terrform plan`
3. Running `terraform apply -auto-approve`. It will be error on creating the capacity provider

### References

* #0000

**Comment by richardj-bsquare** [comment]
FYI: This problem has been around for quite some time, I posted a workaround that should work for you here:

https://github.com/terraform-aws-modules/terraform-aws-ecs/issues/26#issuecomment-730196668

**Comment by irisoliver** [comment]
@richardj-bsquare, I have a solution here, https://github.com/terraform-aws-modules/terraform-aws-ecs/issues/26#issuecomment-966624363 hope this helps

**Comment by richardj-bsquare** [comment]
Yep, that's my workaround that I posted just above yours, not a solution.

**Comment by MaoChhaya** [comment]
Terraform provides a new resource `aws_ecs_cluster_capacity_providers` to fix this issue

**Comment by richardj-bsquare** [comment]
Ah cool, I was 'forced' to introduce that resource as a consequence of moving to AWS provider 4.0 anyway 👍🏻
