### ISSUE TITLE
AWS Transfer Server: VPC-endpoint changed when run terraform apply even resource not modify. 

### ISSUE THREAD

**Issue by udomsak** [hashicorp/terraform-provider-aws#19983]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

*  Terraform `v0.13.6`
*  AWS Provider version  `v3.44.0`

### Affected Resource(s)

* aws_transfer_server 

### Terraform Configuration Files

```hcl
resource "aws_transfer_server" "sftp" {
  endpoint_type = "VPC"
  identity_provider_type = "API_GATEWAY"
  url = "${aws_api_gateway_deployment.prod.invoke_url}${aws_api_gateway_stage.prod.stage_name}"
  invocation_role = aws_iam_role.sftp_identity_provider.arn

  //noinspection MissingProperty
  endpoint_details {
    subnet_ids = var.aws_subnet_id_for_transfer
    vpc_id = var.my_vpc_id
  }
  protocols   = ["SFTP"]
  logging_role = aws_iam_role.sftp_logging.arn
  depends_on = [aws_iam_role.AssumeRoleForUser, aws_api_gateway_deployment.prod]
}
```

### Debug Output

**Can't reproduce because when run it again resource not change.** 

### Expected Behavior

* Must do not modify resource.

### Actual Behavior

* Modify resource (VPC EndPoint) (Create new).

### Steps to Reproduce

1. `terraform plan && terraform apply -auto-approve`

### References

* #0000

**Comment by ewbankkit** [comment]
@udomsak Thanks for raising this issue.
Can you paste the `terraform plan` output that shows the unexpected update?

**Comment by udomsak** [comment]
@ewbankkit  apologize, thought you close this already that I not response. So I can't give you for the terraform plan file sorry (it confidential from my side.  

So you can close it now.
