### ISSUE TITLE
Error: Failed to query available provider packages

### ISSUE THREAD

**Issue by ajinkya933** [hashicorp/terraform-provider-aws#19995]
Here is my main.tf:
```
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "~> 3.1"
    }
  }
}
```

Here is my terraform:
[terraform-ec2.zip](https://github.com/hashicorp/terraform-provider-aws/files/6734752/terraform-ec2.zip)

When i do :
```
$ terraform init
```

I get error:
```
Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 3.1"...
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/aws: could not query
│ provider registry for registry.terraform.io/hashicorp/aws: the request failed after 2 attempts,
│ please try again later: Get "https://registry.terraform.io/v1/providers/hashicorp/aws/versions":
│ net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting
│ headers)
╵
```
How do I resolve this error ?

**Comment by ewbankkit** [comment]
@ajinkya933 Thanks for raising this issue.
Are you still getting this error?

**Comment by ajinkya933** [comment]
@ewbankkit My ISP was somehow blocking this request from hitting the Terraform server. It was very strange since I dont use VPN and my network works well for Google, youtube even pip install works correctly. I am closing this issue as when I tried through different ISP I am able to get success response
