### ISSUE TITLE
Adding new User to an exisiting IAM Group

### ISSUE THREAD

**Issue by dinzpy** [hashicorp/terraform-provider-aws#20032]
I wanted to add a new user in terraform and add it to an existing group

I created _aws_iam_user_ and _aws_iam_user_group_membership_ linking the new user with the existing group by name.
in _terraform plan_, the existing group is showing as created, so am getting the error while _terraform apply_

resource "aws_iam_user" "dinzpy" {
    name = "dinzpy"
    tags = {
      Description = "Terraform test"
    }
}
resource "aws_iam_group" "tf_dinzpy" {
  name = "tf_dinzpy"
}
resource "aws_iam_user_group_membership" "tf_dinzpy_mem" {
    user = aws_iam_user.dinzpy.name
    groups = [aws_iam_group.tf_dinzpy.name,]
}

_terraform apply_

│ Error: Error creating IAM Group tf_dinzpy: EntityAlreadyExists: Group with name tf_dinzpy already exists.
│       status code: 409, request id: 0d4838fd-7a96-4dfa-890d-cb516ccb5eae
│ 
│   with aws_iam_group.tf_dinzpy,
│   on main.tf line 22, in resource "aws_iam_group" "tf_dinzpy":
│   22: resource "aws_iam_group" "tf_dinzpy" {

**Comment by jjshoe** [comment]
```
resource "aws_iam_user" "dinzpy" {
name = "dinzpy"
tags = {
Description = "Terraform test"
}
}

resource "aws_iam_user_group_membership" "tf_dinzpy_mem" {
user = aws_iam_user.dinzpy.name
groups = ["tf_dinzpy"]
}
```

Not a bug.

**Comment by dinzpy** [comment]
Thanks jjshoe
