### ISSUE TITLE
aws_macie2_classification_job: Add support for bucket_criteria to s3_job_definition

### ISSUE THREAD

**Issue by infraredgirl** [hashicorp/terraform-provider-aws#20044]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, the [`s3_job_definition`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/macie2_classification_job#s3_job_definition) argument of the `aws_macie2_classification_job` resource does not support the [`bucket_criteria` object](https://docs.aws.amazon.com/macie/latest/APIReference/jobs.html#jobs-prop-s3jobdefinition-bucketcriteria). This issue is to request addition of it.
### New or Affected Resource(s)

* aws_macie2_classification_job

**Comment by justinretzolk** [comment]
Hey @infraredgirl 👋 This was added with #26160 and released in version `4.26.0` of the provider 🎉. Since this has been addressed, we'll close this issue.
