### ISSUE TITLE
Resource "aws_ecr_replication_configuration" does not support multiple destinations

### ISSUE THREAD

**Issue by dennis-qian** [hashicorp/terraform-provider-aws#20057]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform 1.0.1
hashicorp/aws 3.47.0

### Affected Resource(s)

* aws_ecr_replication_configuration

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

resource "aws_ecr_replication_configuration" "ecr_replication" {
  replication_configuration {
    rule {
      destination {
        region = "us-east-1"
        registry_id = "<aws_account_id>"
      }
    }
  }
}
```

### Expected Behavior

Attribute "rule" is expected to be a list so multiple destinations can be declared.

### Actual Behavior

I can only declared 1 destination.

If I create multiple "aws_ecr_replication_configuration" resources, they will collide and only 1 (I can't figure out the selection criteria) will be actually applied to the private registry.

### Steps to Reproduce

1. `terraform apply`

**Comment by ewbankkit** [comment]
@dennis-qian Thanks for raising this issue.
According to the [AWS API Reference](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_ReplicationConfiguration.html#ECR-Type-ReplicationConfiguration-rules), a single replication configuration can contain only a single rule, but you can configure multiple replication targets for a registry via the AWS Console and query them via the CLI:

```console
% aws --region us-east-1 ecr describe-registry 
{
    "registryId": "12345679012",
    "replicationConfiguration": {
        "rules": [
            {
                "destinations": [
                    {
                        "region": "us-east-2",
                        "registryId": "12345679012"
                    },
                    {
                        "region": "ap-south-1",
                        "registryId": "12345679012"
                    }
                ]
            }
        ]
    }
}

```

**Comment by DrFaust92** [comment]
Not a but, can confirm it works with the multiple destination blocks (not multiple rules):

```
resource "aws_ecr_replication_configuration" "ecr_replication" {
  replication_configuration {
    rule {
      destination {
        region = "us-east-1"
        registry_id = "<aws_account_id>"
      }

      destination {
        region = "us-east-2"
        registry_id = "<aws_account_id>"
      }
    }
  }
}
```

will open a PR for better docs and test for scenario
