### ISSUE TITLE
ecs_service capacity_provider_strategy forces replacement even though CLI doesn not

### ISSUE THREAD

**Issue by richardgavel** [hashicorp/terraform-provider-aws#20059]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform 0.12.31
provider 3.47.0

### Affected Resource(s)

* aws_ecs_service

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
aws_ecs_service foo {
  capacity_provider_strategy {
   base = var.fargate_base
    capacity_provider = "FARGATE"
    weight            = var.fargate_weight
  }
  capacity_provider_strategy {
    capacity_provider = "FARGATE_SPOT"
    weight            = var.fargate_spot_weight
  }
}
```

### Expected Behavior

The ecs service capacity provider strategy is updated in place on the existing service and a new deployment is forced.

### Actual Behavior

Terraform plan shows the need to force replacement.

![image](https://user-images.githubusercontent.com/3877391/124297604-db52b880-db20-11eb-97b4-a1a9c01eaf74.png)

### Important Factoids

When I run the aws ecs update-service call, I can update the capacity provider strategy in place without any issues.
What is odd is that the update method of the provider seems to be coded to handle the possibility of a change in the capacity provider strategy (https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_ecs_service.go#L1113), but the schema does not (https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_ecs_service.go#L42), based on my admittedly limited understanding of providers.

* #0000

**Comment by ewbankkit** [comment]
* [AWS API Reference](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateService.html#ECS-UpdateService-request-capacityProviderStrategy)

**Comment by ewbankkit** [comment]
@richardgavel Thanks for raising this issue.
It has already been noticed in #11351. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
