### ISSUE TITLE
aws_neptune_cluster_parameter_group resource shows adding parameter "neptune_streams" in every plan/apply

### ISSUE THREAD

**Issue by sreeprasadn** [hashicorp/terraform-provider-aws#20056]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform version: 0.13.4 
Installing hashicorp/aws v3.47.0

### Affected Resource(s)
aws_neptune_cluster_parameter_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
locals {
  param = {
    "neptune_enable_audit_log"  = var.neptune_enable_audit_log
    "neptune_lab_mode"          = var.neptune_lab_mode
    "neptune_query_timeout"     = var.neptune_query_timeout
    "neptune_streams"           = 0
  }
}
resource "aws_neptune_cluster_parameter_group" "default" {
  family      = "neptune1"
  name        = var.cluster_identifier
  description = "neptune cluster parameter group"

  dynamic "parameter" {
    for_each = local.param
    content {
      name          = parameter.key
      value         = parameter.value
    }
  }

  tags = merge(
    var.tags,
    {
      "Name" = var.cluster_identifier
    },
  )
}


```

### Debug Output
# module.ss_neptune_db.aws_neptune_cluster_parameter_group.default will be updated in-place
```  
~ resource "aws_neptune_cluster_parameter_group" "default" {
        arn         = "arn:aws:rds:eu-west-1:974871695586:cluster-pg:ss-neptune"
        description = "neptune cluster parameter group"
        family      = "neptune1"
        id          = "ss-neptune"
        name        = "ss-neptune"
        tags        = {
            "Name" = "ss-neptune"
        }
        tags_all    = {
            "Name" = "ss-neptune"
        }

        parameter {
            apply_method = "pending-reboot"
            name         = "neptune_enable_audit_log"
            value        = "1"
        }
        parameter {
            apply_method = "pending-reboot"
            name         = "neptune_lab_mode"
            value        = "false"
        }
        parameter {
            apply_method = "pending-reboot"
            name         = "neptune_query_timeout"
            value        = "900000"
        }
      + parameter {
          + apply_method = "pending-reboot"
          + name         = "neptune_streams"
          + value        = "0"
        }
    }
```

### Expected Behavior

Expected behavior is no changes. Its applied multiple time and the below update is not expected 

```
 + parameter {
          + apply_method = "pending-reboot"
          + name         = "neptune_streams"
          + value        = "0"
```

### Steps to Reproduce

1. Create a Neptune DB parameter group with aws_neptune_cluster_parameter_group including the following keys and values 
``` 
   "neptune_enable_audit_log"  = 1
    "neptune_lab_mode"          = false
    "neptune_query_timeout"     = "90000"
    "neptune_streams"           = 0

```
2. Apply the change two times 

1. `terraform apply`
```
  # module.ss_neptune_db.aws_neptune_cluster_parameter_group.default will be updated in-place
  ~ resource "aws_neptune_cluster_parameter_group" "default" {
        arn         = "arn:aws:rds:eu-west-1:974871695586:cluster-pg:ss-neptune"
        description = "neptune cluster parameter group"
        family      = "neptune1"
        id          = "ss-neptune"
        name        = "ss-neptune"
        tags        = {
            "Name" = "ss-neptune"
        }
        tags_all    = {
            "Name" = "ss-neptune"
        }

        parameter {
            apply_method = "pending-reboot"
            name         = "neptune_enable_audit_log"
            value        = "1"
        }
        parameter {
            apply_method = "pending-reboot"
            name         = "neptune_lab_mode"
            value        = "false"
        }
        parameter {
            apply_method = "pending-reboot"
            name         = "neptune_query_timeout"
            value        = "900000"
        }
      + parameter {
          + apply_method = "pending-reboot"
          + name         = "neptune_streams"
          + value        = "0"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.neptune_load_data.data.aws_iam_policy_document.logs[0]: Reading...
module.neptune_load_data.data.aws_iam_policy_document.logs[0]: Read complete after 0s [id=2170625135]
module.neptune_data_load_invoke_step_function.data.aws_iam_policy_document.logs[0]: Reading...
module.neptune_data_load_invoke_step_function.data.aws_iam_policy_document.logs[0]: Read complete after 0s [id=4268270619]
module.neptune_reset_database.data.aws_iam_policy_document.logs[0]: Reading...
module.neptune_reset_database.data.aws_iam_policy_document.logs[0]: Read complete after 0s [id=462979876]
module.neptune_load_data_status.data.aws_iam_policy_document.logs[0]: Reading...
module.neptune_load_data_status.data.aws_iam_policy_document.logs[0]: Read complete after 0s [id=3966058438]
module.ss_neptune_db.aws_neptune_cluster_parameter_group.default: Modifying... [id=ss-neptune]
module.ss_neptune_db.aws_neptune_cluster_parameter_group.default: Modifications complete after 3s [id=ss-neptune]
```

### References

* #0000

**Comment by bwestleyRV** [comment]
I am experiencing this as well, but with the `neptune_query_timeout` parameter.  Any update on this issue?

**Comment by nagwanidheeraj** [comment]
I am experiencing this with both 

- `aws_neptune_cluster_parameter_group`
   - `neptune_lookup_cache`
   - `neptune_query_timeout`
- `aws_neptune_parameter_group`
   - `neptune_query_timeout`

AWS Provider version - `hashicorp/aws v4.50.0`

**Comment by Penumbra69** [comment]
I'm seeing this with all parameters. 

I made a both a Parameter group and a Cluster parameter group with default values, and every time I plan / apply - those parameters are shown to me as updates.  I have updated "apply_method" to "pending_reboot" -- no change.

I'd prefer not to ignore changes to those parameters, otherwise what good are they?

Any hope of this being addressed?

**Comment by triggan** [comment]
Seems the issue is with the AWS Provider performing a `DescribeDBClusterParameters` API call to check for changes, but only the parameters with non-default settings (filtered by `Source=user`) are being returned.  So if setting a parameter in your template with a default value, it will still appear with a `Source=engine-default`. Terraform will see this as an update being required.  I believe PR #28260 was meant to address this, but I need to validate that.

Ultimately, the behavior needs to be changed to check for changes based on the parameters being defined in the template and their state.
