### ISSUE TITLE
name_prefix misaligns with data sources for a number of resources

### ISSUE THREAD

**Issue by samuelkdavis-mccarthyfinch** [hashicorp/terraform-provider-aws#20067]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

latest
### Affected Resource(s)

launch_configuration, both resource & data.

The Resource for launch configuration states:

> Launch Configurations cannot be updated after creation with the Amazon Web Service API. In order to update a Launch Configuration, Terraform will destroy the existing resource and create a replacement. In order to effectively use a Launch Configuration resource with an AutoScaling Group resource, it's recommended to specify create_before_destroy in a lifecycle block. Either omit the Launch Configuration name attribute, or specify a partial name with name_prefix. Example:

While the data source only allows for a `name` reference, not `name_prefix`. These inconsistencies between resources & data prefixes seem to be wide-spread

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/launch_configuration
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_configuration

### Expected Behavior

Resources supporting name_prefix should have matching data sources allowing for name_prefix

### Actual Behavior

Some data sources allow for name_prefix, others do not

### References
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/launch_configuration
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_configuration

**Comment by gdavison** [comment]
Thanks for submitting this issue, @samuelkdavis-mccarthyfinch.

The `name_prefix` parameters on the resources allows the names to be semi-random, in the form `<prefix>-<random suffix>`. This helps in cases where resources may need to be replaced before the original is deleted, or simply where a name containing randomness is desired. For the data sources, they must match one specific resource, so the `name_prefix` is not applicable.

I'm going to close this issue. If this doesn't clarify the situation, or doesn't describe your use case, please open a new issue with a complete description of your use case.
