### ISSUE TITLE
LogDeliveryConfiguration for Elasticache replication group

### ISSUE THREAD

**Issue by trc-aberg** [hashicorp/terraform-provider-aws#20068]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for slowlog capturing into CloudWatch Logs(/Firehose) for Elasticache replication group -> LogDeliveryConfigurations

### New or Affected Resource(s)

* aws_elasticache_replication_group

### Potential Terraform Configuration

```hcl
# example for cloudwatch logs
resource "aws_elasticache_replication_group" "this" {
  replication_group_description = "elasticache-replication-group with logging"
  replication_group_id =  "elasticache-replication-group"
  log_delivery_configurations {
    log_type = "slow-log"
    destination_type = "cloudwatch-logs"
    log_format = "json"
    destination_details {
      cloudwatch_logs_details {
        log_group = var.log_group_arn
      }
    }
  }
}
```

### References

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-replicationgroup-logdeliveryconfigurationrequest.html

**Comment by IrmantasMarozas** [comment]
Sorry for the follow up, but when can we expect this to be released?
