### ISSUE TITLE
static output not shown when resource targeting is used

### ISSUE THREAD

**Issue by chr-b** [hashicorp/terraform-provider-aws#20069]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.0 
on linux_amd64

provider registry.terraform.io/hashicorp/aws v.3.45.0

### Affected Resource(s)

output variables based on data.aws_region.*

### Terraform Configuration Files

```hcl
terraform {
    required_version = "~> 1.0.0"
    required_providers {
        aws = {
        source  = "hashicorp/aws"
        version = "~> 3.45.0"
        }
    }
}

provider "aws" {
  region  = "eu-west-1"
}

data "aws_region" "current" {}


resource "aws_s3_bucket" "b" {
  acl    = "private"
}


output "aws_region" {
   value       = data.aws_region.current.name
}
output "s3_bucket" {
   value = aws_s3_bucket.b.id
}
```

### Expected Behavior

The command `terraform apply -target=aws_s3_bucket.b` should show both output variables `s3_bucket` and `aws_region`.

### Actual Behavior

The command `terraform apply -target=aws_s3_bucket.b` only shows the output variable `s3_bucket`.
The output `aws_region` is not shown.

I would have expected that the data sections from the aws provider (e.g. aws_region.current) are always propagated to the output, as those are "static".

### Steps to Reproduce

1. `terraform apply -target=aws_s3_bucket.b`

### Important Factoids

Running `terraform apply` (without target) will show all output variables, including `aws_region`.

### References

I am not sure if this is an issue with the AWS provider, or with Terraform core.

**Comment by gdavison** [comment]
Hi @chr-b, this would be related to Terraform Core. You can create an issue at https://github.com/hashicorp/terraform/issues
