### ISSUE TITLE
aws_cloudwatch_event_rule / schedule_expression documentation

### ISSUE THREAD

**Issue by chrisbloe** [hashicorp/terraform-provider-aws#20060]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The [aws_cloudwatch_event_rule / schedule_expression](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_rule#schedule_expression) documentation suggests some examples, but doesn't give a full list.

It would be really helpful if a link to the relevant [AWS documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html) was included in the description.

### New or Affected Resource(s)

* aws_cloudwatch_event_rule

**Comment by jeremy-pereira** [comment]
:+1:
