### ISSUE TITLE
"Resources" nor the resource "aws_workspaces_workspace" does not appear in navigation tree menu

### ISSUE THREAD

**Issue by kodyabbott** [hashicorp/terraform-provider-aws#20074]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_workspaces_workspace

### Terraform Configuration Files

N/A

### Issue

"Resources" does not appear under the "Workspaces" tree menu for the AWS Provider. 
Only "Data Sources" appear under the "Workspaces" tree menu.
The only way to navigate to "[aws_workspaces_workspace](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/workspaces_workspace)" module is via a direct link.

### Expected Behavior

When viewing the AWS Provider, expanding the "Workspaces" tree should show "Resources" and then once that is expanded a link for "[aws_workspaces_workspace](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/workspaces_workspace)" should show as well.

### Actual Behavior

When viewing the AWS Provider, expanding the "Workspaces" tree only shows "Data Sources".

### Steps to Reproduce

Navigate in a web browser to the [AWS Provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs), scroll down and find "Workspaces" near the bottom and expand it.

**Comment by kodyabbott** [comment]
It looks like other "Resources" for "Workspaces" were made as well. Please see this comment [here](https://github.com/hashicorp/terraform-provider-aws/issues/434#issuecomment-733978371) by @bflad.

> Over the past few months, the Terraform AWS Provider has been augmented with WorkSpaces support. As of this writing (version 3.18.0), the following is supported:
Resources:
[aws_workspaces_directory resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/workspaces_directory)
[aws_workspaces_ip_group resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/workspaces_ip_group)
[aws_workspaces_workspace resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/workspaces_workspace)
...

**Comment by sumodirjo** [comment]
- From [3.46.0](https://registry.terraform.io/providers/hashicorp/aws/3.46.0/docs) 2 out of 3 X-ray resources also not listed in the navigation bar
- From [3.47.0](https://registry.terraform.io/providers/hashicorp/aws/3.47.0/docs) X-Ray not listed in navigation. WorkSpaces resources not listed in navigation.

**Comment by breathingdust** [comment]
Manually adding these should not be necessary. We have recently hit 1000 resources and datasources 🎉  but it looks like something in the registry is limiting the display over this number 😢 . I have raised an issue with the registry team and hope to have a resolution soon.

**Comment by kodyabbott** [comment]
> Manually adding these should not be necessary. We have recently hit 1000 resources and datasources 🎉 but it looks like something in the registry is limiting the display over this number 😢 . I have raised an issue with the registry team and hope to have a resolution soon.

Hey @breathingdust I submitted [this PR](https://github.com/hashicorp/terraform-provider-aws/pull/20076) but perhaps it is not needed if what you are saying about the +1000 resources and data sources is true?

**Comment by breathingdust** [comment]
Hi @kodyabbott that's right, thanks for the attempt at fixing it but I'll close it for now. 👍  I'll update this issue when I have a ETA on a fix.

**Comment by breathingdust** [comment]
Hi all, this is now resolved in the registry!

**Comment by kodyabbott** [comment]
> Hi all, this is now resolved in the registry!

Thank you! Wow, looks like that added a LOT of other things too.
