### ISSUE TITLE
Not able to migrate  existing R53 into terraform state 

### ISSUE THREAD

**Issue by jainpratik163** [hashicorp/terraform-provider-aws#20085]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_route53

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

I created below file in port to run ```terraform import ``` command in order to imgrate existing r53 to tf state file.
```hcl
resource "aws_route53_zone" "this" {
  for_each = var.create ? var.zones : {}

  name          = each.key
  comment       = lookup(each.value, "comment", null)
  force_destroy = lookup(each.value, "force_destroy", false)
  vpc {
    vpc_id = lookup(each.value, "vpc_id", null)
  }
  tags = lookup(each.value, "tags", null)

  lifecycle {
    ignore_changes = [
      vpc
    ]
  }
}

```

### Debug Output

It should only update the existing resources.
Plan: 1 to add, 0 to change, 1 to destroy.
### Expected Behavior
It should only update the existing resources.
Plan: 2 to add, 0 to change, 3 to destroy.

### Actual Behavior
it is destroying the resource and creating new one 

### Steps to Reproduce

1. `terraform init`
2. `terraform import aws_route53_record.this <r53_id>_<r53>_SOA`
3. `terraform plan`

### References
we want to migrate our R53 into terraform statefile  for this we import command for importing r53 and state file created successfully but when we run terraform plan we see it is destroying existing resource and we are not getting why it is destroying the whole resource.

* #0000

**Comment by gdavison** [comment]
Hi @jainpratik163, is the problem you're seeing that it's not importing the expected resources or that it is trying to replace them in the `plan`?

To help with diagnosing this, can you please include the following:
* The version of Terraform and the AWS provider that you're using
* The values of the variables `var.create` and `var.zones`
* The output of the `terraform import` command
* The output of the `terraform plan` command

**Comment by jainpratik163** [comment]
Terraform v0.14.5 .
in provider file below is the content 
```
provider "aws" {
  region = "eu-west-1"
}```
I am running this command `terraform import aws_route53_zone.this Z0164055395PYJGV5XHX1`

Below is output of `terraform plan`

```
 terraform plan
aws_route53_zone.this: Refreshing state... [id=Z0164055395PYJGV5XHX1]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # aws_route53_zone.this will be destroyed
  - resource "aws_route53_zone" "this" {
      - comment      = "for testing" -> null
      - id           = "Z0164055395PYJGV5XHX1" -> null
      - name         = "test.corp.amdocs.aws" -> null
      - name_servers = [
          - "ns-0.awsdns-00.com.",
          - "ns-1024.awsdns-00.org.",
          - "ns-1536.awsdns-00.co.uk.",
          - "ns-512.awsdns-00.net.",
        ] -> null
      - tags         = {} -> null
      - tags_all     = {} -> null
      - zone_id      = "Z0164055395PYJGV5XHX1" -> null

      - vpc {
          - vpc_id     = "vpc-0100c890079a1a7fe" -> null
          - vpc_region = "eu-west-1" -> null
        }
      - vpc {
          - vpc_id     = "vpc-bd6a58d9" -> null
          - vpc_region = "eu-west-1" -> null
        }
    }

  # null_resource.route53-validation will be created
  + resource "null_resource" "route53-validation" {
      + id = (known after apply)
    }

  # module.zones.aws_route53_zone.this["test.corp.amdocs.aws"] will be created
  + resource "aws_route53_zone" "this" {
      + comment       = "Managed by Terraform"
      + force_destroy = false
      + id            = (known after apply)
      + name          = "test.corp.amdocs.aws"
      + name_servers  = (known after apply)
      + tags_all      = (known after apply)
      + zone_id       = (known after apply)

      + vpc {
          + vpc_id     = "vpc-0100c890079a1a7fe"
          + vpc_region = (known after apply)
        }
    }

Plan: 2 to add, 0 to change, 1 to destroy.

Changes to Outputs:
  + route53_zone_name_servers = {
      + test.corp.amdocs.aws = (known after apply)
    }
  + route53_zone_zone_id      = {
      + test.corp.amdocs.aws = (known after apply)
    }

------------------------------------------------------------------------
```

and in variables.tf

```
# AWS
variable "region" {
  type        = string
  default     = ""
  description = "The AWS region"
}
# AWS Route53

variable "hosted_zone_name" {
  description = "The name of the hosted zone"
  type        = string
}

variable "vpc_id" {
  description = "The VPC ID"
  type        = string
}

variable "common_tags" {
  type        = map
  default     = {}
  description = "A mapping of tags to assign to the resource"
}

variable "records" {
  description = "List of maps of DNS records"
  type        = any
  default     = []
}
```

**Comment by gdavison** [comment]
Based on the output of `terraform plan`, it looks like the it's going to delete a resource `aws_route53_zone.this` at the root level and going to create a resource `module.zones.aws_route53_zone.this["test.corp.amdocs.aws"]`. It's contained in a module and is also an indexed resource.

When you use `for_each` in a resource block, it will create zero or more instances, indexed by the `key` of the `for_each` (see https://www.terraform.io/docs/language/meta-arguments/for_each.html for more information on `for_each`). When you're importing an indexed resource, you need to include the index, see https://www.terraform.io/docs/cli/commands/import.html#example-import-into-resource-configured-with-for_each

When you're importing a resource that's in a module, you need to pass the full resource address, including the module, see https://www.terraform.io/docs/cli/commands/import.html#example-import-into-module

The GitHub issues for the provider are intended for requesting enhancements and reporting errors in the AWS provider. If you need further assistance on this, I suggest using out community resources, such as the [general Terraform forums](https://discuss.hashicorp.com/c/terraform-core/27) or the [AWS provider forums](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33).

**Comment by jainpratik163** [comment]
Hi @gdavison ,
Thanks for the suggestion.
I also tried to create a state file using the command `terraform import module.zones.aws_route53_zone.this Z0164055395PYJGV5XHX1` and it creates the file and when I run again `terraform plan` it shows me below output

```
module.zones.aws_route53_zone.this: Refreshing state... [id=Z0164055395PYJGV5XHX1]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # null_resource.route53-validation will be created
  + resource "null_resource" "route53-validation" {
      + id = (known after apply)
    }

  # module.zones.aws_route53_zone.this will be destroyed
  - resource "aws_route53_zone" "this" {
      - comment      = "for testing" -> null
      - id           = "Z0164055395PYJGV5XHX1" -> null
      - name         = "test.corp.amdocs.aws" -> null
      - name_servers = [
          - "ns-0.awsdns-00.com.",
          - "ns-1024.awsdns-00.org.",
          - "ns-1536.awsdns-00.co.uk.",
          - "ns-512.awsdns-00.net.",
        ] -> null
      - tags         = {} -> null
      - tags_all     = {} -> null
      - zone_id      = "Z0164055395PYJGV5XHX1" -> null

      - vpc {
          - vpc_id     = "vpc-0100c890079a1a7fe" -> null
          - vpc_region = "eu-west-1" -> null
        }
      - vpc {
          - vpc_id     = "vpc-bd6a58d9" -> null
          - vpc_region = "eu-west-1" -> null
        }
    }

  # module.zones.aws_route53_zone.this["test.corp.amdocs.aws"] will be created
  + resource "aws_route53_zone" "this" {
      + comment       = "Managed by Terraform"
      + force_destroy = false
      + id            = (known after apply)
      + name          = "test.corp.amdocs.aws"
      + name_servers  = (known after apply)
      + tags_all      = (known after apply)
      + zone_id       = (known after apply)

      + vpc {
          + vpc_id     = "vpc-0100c890079a1a7fe"
          + vpc_region = (known after apply)
        }
    }

Plan: 2 to add, 0 to change, 1 to destroy.

Changes to Outputs:
  + route53_zone_name_servers = {
      + test.corp.amdocs.aws = (known after apply)
    }
  + route53_zone_zone_id      = {
      + test.corp.amdocs.aws = (known after apply)
    }
```
if I tried to perform the same thing on r53 which is created by terraform i don't see destroy and this is what I am not getting why this is happening.
And also I am new to terraform.
