### ISSUE TITLE
Add support for other arguments in  aws_dms_endpoint `kinesis_settings`

### ISSUE THREAD

**Issue by ksagle77** [hashicorp/terraform-provider-aws#20083]
### Description

Currently [aws/dms_endpoint](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint) kinesis_settings only supports message_format, service_access_role_arn, and stream_arn. I would like to add support for IncludeNullAndEmpty. I am not sure whether there would be a way to query DMS to discover available settings, or whether IncludeNullAndEmpty should be hard coded in to the [existing kinesis settings block](https://github.com/hashicorp/terraform-provider-aws/blob/b50f66a67be85702b41e7064e21dca2e0a4bf965/aws/resource_aws_dms_endpoint.go#L162).

### New or Affected Resource(s)

*  [aws/dms_endpoint](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint)
*  [kinesis_settings](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint#kinesis_settings-arguments)

### Potential Terraform Configuration

```hcl
provider "aws" {
  region                  = "us-east-2"
  profile                 = "aws"
}

resource "aws_iam_role" "this" {  
  name               = "dms-role"
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": [
          "dms.amazonaws.com"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
}

resource "aws_kinesis_stream" "this" {
  name             = "dms-kinesis"
  shard_count      = 1
}

resource "aws_dms_endpoint" "target" {
  endpoint_id   = "test-kinesis"
  endpoint_type = "target"
  engine_name   = "kinesis"
  ssl_mode      = "none"
  kinesis_settings {
    stream_arn               = aws_kinesis_stream.this.arn
    message_format           = "json"
    service_access_role_arn  = aws_iam_role.this.arn
    include_null_and_empty   = true
  }  
}
```

### References

* #0000

**Comment by vikatskhay** [comment]
Would it be possible to add support for `IncludeTransactionDetails` as well?

**Comment by ksagle77** [comment]
In addition to `IncludeNullAndEmpty` and `IncludeTransactionDetails`, it makes sense to add support for the other available kinesis settings:

`IncludeControlDetails`
`IncludePartitionValue`
`IncludeTableAlterOperations`
`PartitionIncludeSchemaTable`

Will update the PR to reflect that.
