### ISSUE TITLE
aws_rds_cluster and aws_rds_cluster_instance should ignore minor-version only version diffs like aws_db_instance

### ISSUE THREAD

**Issue by pipeworks-asmith** [hashicorp/terraform-provider-aws#20086]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

aws_db_instance began ignoring select diffs in the `engine_version` field if `auto_upgrade_minor_version` was set to true. See the documentation [here](https://github.com/hashicorp/terraform-provider-aws/issues/1198). aws_rds_cluster and aws_rds_cluster_instance should have the same behavior.

Implementation should be nearly synonymous to the [relevant commit in aws_db_instance](https://github.com/hashicorp/terraform-provider-aws/commit/959987eafdab061f812adce62988bfa90e7a58cb)

### New or Affected Resource(s)

* aws_rds_cluster
* aws_rds_cluster_instance

### References

* #1198

**Comment by ewbankkit** [comment]
@pipeworks-asmith Thanks for raising this issue.
It has already been noticed in #19814. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
