### ISSUE TITLE
second fraction used for comparison but ignored in api call

### ISSUE THREAD

**Issue by baniocarpentercode42** [hashicorp/terraform-provider-aws#20087]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/aws v3.48.0

### Affected Resource(s)

* aws_lambda_event_source_mapping

### Terraform Configuration Files
```
resource "aws_lambda_function" "test" {
  description      = "test function"
  filename         = var.test_lambda_jar
  function_name    = "${terraform.workspace}-lambda"
  role             = aws_iam_role.lambda_role.arn
  handler          = "test::test"
  source_code_hash = filesha256(var.test_lambda_jar)
  runtime          = "java11"
  timeout          = var.annotator_lambda_timeout
  memory_size      = var.annotator_lambda_memory
 }

resource "aws_kinesis_stream" "test_stream" {
  name             = "${terraform.workspace}-stream"
  shard_count      = 1
  retention_period = 24
}

resource "aws_kinesis_stream_consumer" "test_consumer" {
  name       = aws_lambda_function.test.function_name
  stream_arn = aws_kinesis_stream.test_stream.arn
}

resource "aws_lambda_event_source_mapping" "test_mapping" {
  event_source_arn            = aws_kinesis_stream_consumer.test_consumer.arn
  function_name               = aws_lambda_function.test.function_name
  starting_position           = "AT_TIMESTAMP"
  parallelization_factor      = 2
  starting_position_timestamp = "2021-05-13T14:43:17Z"
}

```
If you add on centiseconds without changing the actual timestamp like so:
```
resource "aws_lambda_event_source_mapping" "test_mapping" {
  event_source_arn            = aws_kinesis_stream_consumer.test_consumer.arn
  function_name               = aws_lambda_function.test.function_name
  starting_position           = "AT_TIMESTAMP"
  parallelization_factor      = 2
  starting_position_timestamp = "2021-05-13T14:43:17.00Z"
}
```

The mapping will be replaced/destroyed
```
  # aws_lambda_event_source_mapping.annotator must be replaced
-/+ resource "aws_lambda_event_source_mapping" "test_mapping" {
        ...
              starting_position                  = "AT_TIMESTAMP"
      ~ starting_position_timestamp        = "2021-05-13T14:43:17Z" -> "2021-05-13T14:43:17.00Z" # forces replacement
...
    }
```

--->

### Expected Behavior

The timestamp is the same and the mapping should not be replaced

### Actual Behavior

mapping is replaced

### Steps to Reproduce

change the   starting_position_timestamp from:
"2021-05-13T14:43:17Z"
to
"2021-05-13T14:43:17.00Z"

**Comment by ewbankkit** [comment]
@baniocarpentercode42 Thanks for raising this issue.
It has already been noticed in #21567. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
