### ISSUE TITLE
aws_fms_policy Common Security Groups Multiple Security Groups error

### ISSUE THREAD

**Issue by upt-systems-engineering** [hashicorp/terraform-provider-aws#20099]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.48.0

### Affected Resource(s)

* aws_fms_policy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_fms_policy" "ec2_linux" {
  name                        = "fm-policy-${varenvironment}-securitygroup-ec2-linux-${var.region}"
  exclude_resource_tags       = false
  remediation_enabled         = true
  delete_all_policy_resources = false
  resource_type_list          = ["AWS::EC2::NetworkInterface", "AWS::EC2::Instance"]
  resource_tags = {
    "environment" = var.environment,
    "osfamily"    = "rhel"
  }

  include_map {
    account = []
    orgunit = [
      "ou-xxxxxxxx",
      "ou-xxxxxxx",
      "ou-xxxxxxx",
    ]
  }

  security_service_policy_data {
    type = "SECURITY_GROUPS_COMMON"

    managed_service_data = jsonencode({
      type = "SECURITY_GROUPS_COMMON",
      securityGroups = [{
        "id" = aws_security_group.ec2_ssh.id,
        "id" = aws_security_group.ec2_monitoring.id
      }]
      revertManualSecurityGroupChanges         = true
      exclusiveResourceSecurityGroupManagement = false
      applyToAllEC2InstanceENIs                = true
      includeSharedVPC                         = true
    })
  }
```

### Expected Behavior

Multiple Security groups added to the Firewall Manager Policy

### Actual Behavior

Only the first security group is added on the apply. If security groups are added manually in the AWS Management Console, future applies will want to remove all security groups other than the first group listed in the Terraform project. Using a lifecycle ignore_changes = [security_service_policy_data] to mitigate any issues with security group removal after subsequent applies if more than one security group is assigned.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

AWS support case needs to be opened for each AWS Firewall Manager policy for common security groups to be able to add more than one security group.

### References

* #0000

**Comment by gdavison** [comment]
Hi @upt-systems-engineering, I think I may see an error in the `managed_service_data`: the `securityGroups` section has a single element, with the `id` key defined twice.

```
      securityGroups = [{
        "id" = aws_security_group.ec2_ssh.id,
        "id" = aws_security_group.ec2_monitoring.id
      }]
```

I think what you should have is

```
      securityGroups = [
        {"id" = aws_security_group.ec2_ssh.id},
        {"id" = aws_security_group.ec2_monitoring.id}
      }]
```

If that doesn't fix the problem, could you please run Terraform with debug logging enabled, by setting the environment variable `TF_LOG=DEBUG`, and then create a Gist with the output?

**Comment by upt-systems-engineering** [comment]
Thanks, I have made the updates requested and that has resolved the issue. The original issue was me trying to get the json output of the resource from an aws cli to match what I needed from the syntax with Terraform.
