### ISSUE TITLE
Not able to create aws_ssm_maintenance_window_task resources without targets

### ISSUE THREAD

**Issue by timonwalkley** [hashicorp/terraform-provider-aws#20090]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.13.7
provider.aws: version = "3.28"

### Affected Resource(s)

* aws_ssm_maintenance_window_task

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ssm_maintenance_window" "test" {
  name     = "test"
  schedule = "cron(0 12 ? * WED *)"
  duration = 2
  cutoff   = 0
  enabled  = true
}

resource "aws_ssm_maintenance_window_task" "test" {
  window_id        = aws_ssm_maintenance_window.test.id
  task_type        = "AUTOMATION"
  task_arn         = aws_ssm_document.test.name
  priority         = 1
}
```

### Expected Behavior

aws_ssm_maintenance_window_task resource created successfully

### Actual Behavior

Error: Missing required argument
The argument "max_errors" is required, but no definition was found.
The argument "max_concurrency" is required, but no definition was found.

Including these arguments results in:
Error: ValidationException: Maintenance window tasks without targets do not support MaxErrors values. Maintenance window tasks without targets do not support MaxConcurrency values.

### Steps to Reproduce

1. `terraform apply`

### References
https://docs.aws.amazon.com/systems-manager/latest/userguide/maintenance-windows-targetless-tasks.html

It looks like the validation was introduced here https://github.com/hashicorp/terraform-provider-aws/pull/11774

* #0000

**Comment by aqyp90** [comment]
It looks like the target argument was recently set to optional, but the max_concurrency and max_errors arguments are still required.  The workaround should be to make these arguments optional if no target block is provided.

**Comment by catrielgood** [comment]
On Terraform 1.1.6 and AWS Provider 3.74.0 and this is still a problem. Any insight?

**Comment by mervin-hemaraju-cko** [comment]
On Terraform 1.1.7 and AWS Provider 4.1.0 and this is still a problem. Do we have any updates on this?
