### ISSUE TITLE
aws_dynamodb_table_item doens't allow json document as item value

### ISSUE THREAD

**Issue by bostrowski13** [hashicorp/terraform-provider-aws#20096]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform Version:  0.12.29
AWS Provider Version:  3.30.0

### Affected Resource(s)

* aws_dynamodb_table_item

### Terraform Configuration Files

```hcl
data "template_file" "config_json_tpl" {
  template = file("${path.root}/config/config.json.tpl")
  vars = {
    server_url = "some_url_string"
  }
}

resource "aws_dynamodb_table_item" "config_json" {
  depends_on = ["data.template_file.config_json_tpl"]
  table_name = "my_table"
  hash_key   = "id"
  item       = <<ITEM
  {
    "id": {"S": "config"},
    "json": {"S": "${data.template_file.config_json_tpl.rendered}"}
  }
  ITEM
}
```

### Debug Output

What should have happened?

I expect the JSON document to be placed in the dynamodb table Item as a string (which I'm able to do via the console)

What actually happened?

Error:
```
Error: Invalid format of "item": Decoding failed: invalid character '\n' in string literal

  on dynamodb.tf line 41, in resource "aws_dynamodb_table_item" "config_json":
  41:   item       = <<ITEM
  42: {
  43:   "id": {"S": "config"},
  44:   "json": {"S": "${data.template_file.resolver_json_tpl.rendered}"}
  45: }
  46: ITEM
```

Please list the steps required to reproduce the issue.

1. `terraform apply`

### Important Factoids

I'm not trying to read from a json document to upload a set of items to dynamodb, i'm trying to store an entire json document as an item.

This is the JSON document I'm inserting a value into to then put into the table item.

```json
{
  "schema": "iglu:com.snowplowanalytics.iglu/resolver-config/jsonschema/1-0-3",
  "data": {
    "cacheSize": 500,
    "repositories": [
      {
          "name": "Company Iglu repository",
          "priority": 0,
          "vendorPrefixes": [ "com.snowplowanalytics" , "com.company.clickstream"],
          "connection": {
            "http": {
              "uri": "${iglu_server}"
            }
          }
      }
    ]
  }
}
```

**Comment by gdavison** [comment]
Hi @bostrowski13. Since the entire DynamoDB item is already a JSON object, the JSON object that you're embedding into it must be escaped to fit into a JSON string. For example, newlines must be replaced with `\n`, `"` must be replaced with `\"`. The Terraform built-in function [`replace()`](https://www.terraform.io/docs/language/functions/replace.html) can be used for this.
