### ISSUE TITLE
Resource Identifiers and Tags for VPC Security Group Rules

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#20104]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Amazon Virtual Private Cloud (VPC) now supports resource identifiers and tags for security group rules. You can now manage VPC security group rules using the assigned rule IDs and resource tags.

### New or Affected Resource(s)

* [`aws_security_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group)
* [`aws_security_group_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule)
* [`aws_default_security_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_security_group)

### Potential Terraform Configuration

```hcl
resource "aws_security_group_rule" "example" {
  tags = {
    Env = "prod"
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2021/07/amazon-ec2-adds-resource-identifiers-tags-vpc-security-groups-rules/).
[Blog post](https://aws.amazon.com/blogs/aws/easily-manage-security-group-rules-with-the-new-security-group-rule-id/).

Requires [AWS SDK v1.39.2](https://github.com/aws/aws-sdk-go/releases/tag/v1.39.2):

* #20102

**Comment by shortcut-opsadmin** [comment]
Been over a year. Any way we could get tags on these resources?

**Comment by virgofx** [comment]
Adding tags to the above specified resources would be incredibly useful. Seems like this would be an easy fix. Would love to see this get implemented (Been over a two years now!)

**Comment by ewbankkit** [comment]
@virgofx Thanks for your (and everyone else's) interest in the issue.

The delay in addressing this is best summarized in a section from an internal design document we are working on:

### Background

The [`aws_security_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group) resource with in-line `ingress` and (since [Terraform 0.3.7](https://github.com/hashicorp/terraform/tree/v0.3.7/builtin/providers/aws)) `egress` rules has been available since [Terraform 0.1.0](https://github.com/hashicorp/terraform/tree/v0.1.0/builtin/providers/aws) and the [`aws_security_group_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule) resource has been available since [Terraform 0.5.0](https://github.com/hashicorp/terraform/blob/v0.11/CHANGELOG.md#050-may-7-2015). For both of these resources a single rule corresponds to an EC2 [`IpPermission`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_IpPermission.html) structure, a set of one or more individual permissions (protocol, port range and source or destination). Notably the `IpPermission` has no unique resource ID assigned by AWS.

In July 2021 AWS [announced](https://aws.amazon.com/about-aws/whats-new/2021/07/amazon-ec2-adds-resource-identifiers-tags-vpc-security-groups-rules/) [security group rule IDs](https://aws.amazon.com/blogs/aws/easily-manage-security-group-rules-with-the-new-security-group-rule-id/) and tags for security group rules:

> Before this release, you had to reference and manage security group rules based on the rule attributes such as ports, protocols, or IP CIDRs, which can become difficult to incorporate into automation tooling. With the introduction of security group rule IDs, every security group rule is automatically assigned a unique resource ID. You can reference security group rules in your automation tooling by their newly introduced resource IDs to simplify querying, revoking and updating your security group rules at scale. In addition, you can specify tags for security group rules and manage them in a more structured manner with rule-specific metadata.

The [new](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifySecurityGroupRules.html) EC2 APIs use an EC2 [`SecurityGroupRule`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SecurityGroupRule.html) structure which represents a single permission (protocol, port range and source or destination) and has a unique resource ID assigned by AWS.

As there is no 1-to-1 mapping between an `IpPermission` and `SecurityGroupRule`, `aws_security_group_rule` (and `aws_security_group`’s in-line `rule`s) have not implemented rule tagging.

**Comment by ewbankkit** [comment]
With https://github.com/hashicorp/terraform-provider-aws/pull/27828, scheduled to be released in **v4.40.0** of the Terraform AWS Provider, we are adding the `security_group_rule_id` attribute to the `aws_security_group_rule` resource.
If the resource has a single source or destination then the EC2 [`IpPermission`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_IpPermission.html) structure represented by this resource maps 1-to-1 with an EC2 [`SecurityGroupRule`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SecurityGroupRule.html) structure and the `security_group_rule_id` attribute receives the AWS Security Group Rule resource ID. In other cases there is not a 1-to-1 mapping and the attribute will be empty (`""`).

In the case that `security_group_rule_id` has a value, the [`aws_ec2_tag`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_tag) resource can be used to manage Security Group Rule tags. For example:

```hcl
resource "aws_vpc" "test" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_security_group" "test" {
  vpc_id = aws_vpc.test.id
}

resource "aws_security_group_rule" "test" {
  security_group_id = aws_security_group.test.id

  type        = "ingress"
  protocol    = "tcp"
  from_port   = 80
  to_port     = 8000
  cidr_blocks = ["10.0.0.0/8"]
}

resource "aws_ec2_tag" "test" {
  resource_id = aws_security_group_rule.test.security_group_rule_id
  key         = "Name"
  value       = "Hello World"
}
```

**Comment by MrHash** [comment]
This works nice but in the following case where there are multiple rules created i get the error `InvalidParameterValue: Value ( null ) for parameter resourceId is invalid. Null/empty value for resourceId is invalid`. I guess this is because there are multiple security group rule ids created.

```
resource "aws_security_group_rule" "test" {
  security_group_id = aws_security_group.test.id

  type        = "ingress"
  protocol    = "tcp"
  from_port   = 80
  to_port     = 8000
  cidr_blocks = ["10.0.0.0/8", "192.168.0.0/8"]
}

resource "aws_ec2_tag" "test" {
  resource_id = aws_security_group_rule.test.security_group_rule_id
  key         = "Name"
  value       = "Hello World"
}
```

**Comment by MrHash** [comment]
I see that `security_group_rule_id` is not shown in the state of `aws_security_group_rule` resources where there are multiple rules generated from it (eg. more than one `cidr_block`)

**Comment by MrHash** [comment]
Is it not possible to provide an array of security rule group ids from the `aws_security_group_rule` resource if there are multiple rules generated?

**Comment by evandeworp** [comment]
@ewbankkit - Maybe you should add your example to the documentation for aws_security_group_rule.

**Comment by tmccombs** [comment]
What is the impact on the `aws_security_group` resource?  Currently it is the only way to have drift detection, but the diffs can sometimes be very difficult to read due to the rules being treated as a set. Is there any plan to improve how that works using the security group rule ids?  Or allowing specifying tags in inline rules? Perhaps a new way of specifying inline rules that conflicts with the current way, to avoid any backwards incompatibility issues?

Or perhaps have something like https://github.com/hashicorp/terraform-provider-aws/pull/9032#issuecomment-1409207410, but instead of specifying the rules inline, you just include a set of the ids from the new resource that replaces `aws_security_group_rule`.
