### ISSUE TITLE
resource/aws_spot_instance_request: Remove parameter `instance_interruption_behaviour`

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#20101]
Remove the parameter `instance_interruption_behaviour`.

The parameter was deprecated in #20100

### Affected Resource

* aws_spot_instance_request

**Comment by dirk39** [comment]
I'm working on that [here](https://github.com/dirk39/terraform-provider-aws/tree/r/aws_spot_instance_request)

**Comment by anGie44** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-aws/issues/16191
