### ISSUE TITLE
String validation error text doesn't match regex

### ISSUE THREAD

**Issue by chrismarget** [hashicorp/terraform-provider-aws#20117]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform 1.0.1
AWS provider 3.49.0

### Affected Resource(s)

aws_imagebuilder_distribution_configuration

### Debug Output

When specifying that the imagebuilder distribution config apply a name containing a period to the new AMI, the following error is displayed:

`Error: invalid value for distribution.1.ami_distribution_configuration.0.name (must contain only alphanumeric characters, periods, underscores, and hyphens)
`
### Panic Output

n/a

### Expected Behavior

The validation regex is correct in that periods do not seem to be [permitted by AWS](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_CreateDistributionConfiguration.html#API_CreateDistributionConfiguration_RequestSyntax), so the error message should not suggest that periods are permitted in this field.

### Actual Behavior

The error text indicates that periods are allowed. They are not permitted by the validation regex, nor apparently, by the AWS API.

### Steps to Reproduce

Review the regex here:
https://github.com/hashicorp/terraform-provider-aws/blob/bae3b38b6508172254ff696e8ba1126cf8c55ee8/aws/resource_aws_imagebuilder_distribution_configuration.go#L97

### Important Factoids

Note that the regex suggested by the AWS documentation link above (`^[-_A-Za-z-0-9][-_A-Za-z0-9 ]{1,126}[-_A-Za-z-0-9]$`) doesn't seem to be correct because it wouldn't allow inclusion of AWS-side substitutions like `{{ imagebuilder:buildDate }}`
### References

[AWS API guide](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_CreateDistributionConfiguration.html#API_CreateDistributionConfiguration_RequestSyntax)

[Error text which needs "periods" removed](https://github.com/hashicorp/terraform-provider-aws/blob/bae3b38b6508172254ff696e8ba1126cf8c55ee8/aws/resource_aws_imagebuilder_distribution_configuration.go#L97)

**Comment by kamilturek** [comment]
I am going to work on this issue.
