### ISSUE TITLE
Support for max-pods-per-node on aws_eks_node_group

### ISSUE THREAD

**Issue by Aohzan** [hashicorp/terraform-provider-aws#20115]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
`eksctl create nodegroup` provide the option `--max-pods-per-node int` to override default AWS limit based on instance type: https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt
Can you add this parameter on the `aws_eks_node_group` resource ?

### New or Affected Resource(s)

* aws_eks_node_group

### Potential Terraform Configuration

```hcl
resource "aws_eks_node_group" "this" {
  cluster_name = aws_eks_cluster.this.name
  ...
  max_pods_per_node = 80
}
```

Thanks

**Comment by mattburgess** [comment]
Unfortunately, the AWS SDK for EKS doesn't support customising the max-pod-per-node; it appears to be an `eksctl`/bootstrap-only setting. As such, it's unlikely that the Terraform provider will gain this feature. There's some discussion at https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1577 for how you can customise that setting by using a custom userdata script on the launch template for the node group.

**Comment by stevehipwell** [comment]
I'm the author of the PR @mattburgess linked to above. The behaviour in the PR is easy enough to add with or without the _terraform-aws-eks_ module via custom userdata; note the cloudinit requirements for managed node userdata if not specifying the AMI ID. Once the above PR is merged it will be as easy as setting `USE_MAX_PODS=false` in `bootstrap_env` and adding a `--max-pods` flag to `kubelet_extra_args`.
