### ISSUE TITLE
aws_budgets_budget_action creation error timeout waiting for state to become 'EXECUTION_SUCCESS, EXECUTION_FAILURE, PENDING'

### ISSUE THREAD

**Issue by mdasilva** [hashicorp/terraform-provider-aws#20125]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v1.0.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.49.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
```

### Affected Resource(s)

* aws_budgets_budget_action

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_budgets_budget_action" "cost_overrun" {
  count              = var.member_account_enable_cost_budget ? 1 : 0
  provider           = aws.member_account
  account_id         = aws_organizations_account.member.id
  budget_name        = aws_budgets_budget.cost[0].name
  notification_type  = var.member_account_cost_budget_notification_type
  execution_role_arn = aws_iam_role.budget[0].arn
  action_type        = "APPLY_SCP_POLICY"
  approval_model     = "AUTOMATIC"

  action_threshold {
    action_threshold_type  = var.member_account_cost_budget_threshold_type
    action_threshold_value = var.member_account_cost_budget_threshold_value
  }

  definition {
    scp_action_definition {
      policy_id  = aws_organizations_policy.readonly[0].id
      target_ids = [aws_organizations_account.member.id]
    }
  }

  subscriber {
    subscription_type = "EMAIL"
    address           = var.member_account_email
  }
}

```

### Debug Output

`aws_budgets_budget_action.cost_overrun[0]: Creating...
aws_budgets_budget_action.cost_overrun[0]: Still creating... [10s elapsed]
aws_budgets_budget_action.cost_overrun[0]: Still creating... [20s elapsed]
aws_budgets_budget_action.cost_overrun[0]: Still creating... [30s elapsed]
aws_budgets_budget_action.cost_overrun[0]: Still creating... [40s elapsed]
aws_budgets_budget_action.cost_overrun[0]: Still creating... [50s elapsed]
aws_budgets_budget_action.cost_overrun[0]: Still creating... [1m0s elapsed]
aws_budgets_budget_action.cost_overrun[0]: Still creating... [1m10s elapsed]
aws_budgets_budget_action.cost_overrun[0]: Still creating... [1m20s elapsed]
aws_budgets_budget_action.cost_overrun[0]: Still creating... [1m30s elapsed]
aws_budgets_budget_action.cost_overrun[0]: Still creating... [1m40s elapsed]
aws_budgets_budget_action.cost_overrun[0]: Still creating... [1m50s elapsed]
aws_budgets_budget_action.cost_overrun[0]: Still creating... [2m0s elapsed]
╷
│ Error: error waiting for Budget Action (065355634694:60e92055-382c-48df-bdc4-073d3c202876:terraform-20210708174012151400000001) creation: timeout while waiting for state to become 'EXECUTION_SUCCESS, EXECUTION_FAILURE, PENDING' (last state: 'STANDBY', timeout: 2m0s)
│ 
│   with aws_budgets_budget_action.cost_overrun[0],
│   on main.tf line 66, in resource "aws_budgets_budget_action" "cost_overrun":
│   66: resource "aws_budgets_budget_action" "cost_overrun" {
`

### Expected Behavior

`terraform apply` should recognize STANDBY as completed state for resource creation.

### Actual Behavior

`terraform apply` throws a timeout error while waiting for state to become EXECUTION_SUCCESS, EXECUTION_FAILURE, or PENDING

### Steps to Reproduce

1. Define an `aws_budgets_budget_action` resource
2. `terraform apply` to create resource

### References

* #0000

**Comment by yogeshmoharkar** [comment]
error waiting for Budget Action (390365252491:cf624277-9376-4d06-8302-6d18a2c64ec2:budget-ec2-monthly) to create: timeout 
while waiting for state to become 'EXECUTION_SUCCESS, EXECUTION_FAILURE, PENDING' (last state: 'STANDBY', timeout: 2m0s)

while creating aws_budgets_budget_action   .... please share solution

**Comment by KnifeMaster007** [comment]
Already fixed this issue in PR #21664, still waiting for review since 7.11.2021

**Comment by joan-s-molas** [comment]
Facing this issue now as well

**Comment by oliverjfletcher** [comment]
Facing this issue also, can this please be triaged, thanks

![Screenshot 2023-02-05 at 16 01 37](https://user-images.githubusercontent.com/36835356/216802692-5e353153-b3ff-419b-be08-ee60e9ed1cec.png)
