### ISSUE TITLE
Terraform provider is not support aws lambda latest version 14.x

### ISSUE THREAD

**Issue by shuqichen** [hashicorp/terraform-provider-aws#20132]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We are going to upgrade our aws lambda to latest version:14.x,
But seems terraform aws provider is not support AWS latest lambda version: 14.x , would you please help to add this new lambda version 14.x support.
 

### New or Affected Resource(s)

chenshu@C02VVAHYHTD6 tr-fedramp-web-stg-ue2 % terraform plan -target=module.lambda

Error: module.lambda.aws_lambda_function.tr_event_trigger: expected runtime to be one of [dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 go1.x java8 java11 nodejs4.3 nodejs4.3-edge nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x provided python2.7 python3.6 python3.7 python3.8 ruby2.5 ruby2.7], got nodejs14.x

Error: module.lambda.aws_lambda_function.tr_scopelog_merger: expected runtime to be one of [dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 go1.x java8 java11 nodejs4.3 nodejs4.3-edge nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x provided python2.7 python3.6 python3.7 python3.8 ruby2.5 ruby2.7], got nodejs14.x

Error: module.lambda.aws_lambda_function.tr_splunk_forward: expected runtime to be one of [dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 go1.x java8 java11 nodejs4.3 nodejs4.3-edge nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x provided python2.7 python3.6 python3.7 python3.8 ruby2.5 ruby2.7], got nodejs14.x

### Potential Terraform Configuration

// create the lambda to merge scope logs
resource "aws_lambda_function" "tr_scopelog_merger" {
  function_name = "${var.function_name_scopelog_merger}"
  handler       = "index.handler"
  runtime       = **"nodejs14.x"**
  s3_bucket     = "${var.s3_bucket}"
  s3_key        = "${var.s3_key_scopelog_merger}"
  role          = "${var.lambda_role}"
  environment {
    variables {
      "redis_host"  = "${var.redis_host}"
      "redis_port"  = "${var.redis_port}"
    }
  }

Terraform plan returns error as below:
chenshu@C02VVAHYHTD6 tr-fedramp-web-stg-ue2 % terraform plan -target=module.lambda

Error: module.lambda.aws_lambda_function.tr_event_trigger: expected runtime to be one of [dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 go1.x java8 java11 nodejs4.3 nodejs4.3-edge nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x provided python2.7 python3.6 python3.7 python3.8 ruby2.5 ruby2.7], got nodejs14.x

Error: module.lambda.aws_lambda_function.tr_scopelog_merger: expected runtime to be one of [dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 go1.x java8 java11 nodejs4.3 nodejs4.3-edge nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x provided python2.7 python3.6 python3.7 python3.8 ruby2.5 ruby2.7], got nodejs14.x

Error: module.lambda.aws_lambda_function.tr_splunk_forward: expected runtime to be one of [dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 go1.x java8 java11 nodejs4.3 nodejs4.3-edge nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x provided python2.7 python3.6 python3.7 python3.8 ruby2.5 ruby2.7], got nodejs14.x

chenshu@C02VVAHYHTD6 tr-fedramp-web-stg-ue2 % terraform -v
Terraform v0.11.11
+ provider.aws v2.70.0
+ provider.template v2.2.0

Your version of Terraform is out of date! The latest version
is 1.0.2. You can update by downloading from www.terraform.io/downloads.html
chenshu@C02VVAHYHTD6 tr-fedramp-web-stg-ue2 % 

### References

* #0000

**Comment by rpadovani** [comment]
Terraform delegates to [`aws-sdk-go`](https://github.com/aws/aws-sdk-go) checks on validity of runtime for Lambda. 
`aws-sdk-go` introduced support to nodejs14  with release [v1.37.3](https://github.com/aws/aws-sdk-go/commit/65c0691f756ce0f4436b98b5d5690872894454ba).

This provider updated to v1.37.4 [last February](https://github.com/hashicorp/terraform-provider-aws/commit/9df549faf3ef0d21557296d0695bdb6a1a53d401#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6), just in time for release [v3.27.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v3.27.0), so you simply need to update your AWS provider to a recent version.

**Comment by shuqichen** [comment]
Hi @rpadovani 

Thanks for your reply, when I try to upgrade my local AWS provider to v3.27.0, my local returns below error:
my terraform configuration:
provider "aws" {
  region  = "${var.aws_region}"
  profile = "${var.aws_profile}"
  version = "~> 3.27.0"
}
The execution errors:
chenshu@C02VVAHYHTD6 tr-fedramp-web-stg-ue2 % terraform init
Initializing modules...
- module.sg
- module.route53
- module.s3
- module.iam
- module.redis
- module.aurora
- module.kms
- module.lambda

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

No available provider "aws" plugins are compatible with this Terraform version.

From time to time, new Terraform major releases can change the requirements for
plugins such that older plugins become incompatible.

Terraform checked all of the plugin versions matching the given constraint:
    ~> 3.27.0

Unfortunately, none of the suitable versions are compatible with this version
of Terraform. If you have recently upgraded Terraform, it may be necessary to
move to a newer major release of this provider. Alternatively, if you are
attempting to upgrade the provider to a new major version you may need to
also upgrade Terraform to support the new version.

Consult the documentation for this provider for more information on
compatibility between provider versions and Terraform versions.

chenshu@C02VVAHYHTD6 tr-fedramp-web-stg-ue2 % 

Seems it's due to my terraform version is too low? is there any way to upgrade aws provider version to v3.27.0 without upgrade terraform version, because the higher terraform version is not compatible with the lower version terraform version, we may need change our terraform code with huge effort.

**Comment by breathingdust** [comment]
Hi @shuqichen! Unfortunately 0.11 is not a supported version at this time and you will need to update Terraform/AWS Provider to a more recent version in order to take advantage of this feature:

https://www.hashicorp.com/blog/deprecating-terraform-0-11-support-in-terraform-providers
