### ISSUE TITLE
The documented auth > username field does not exist on aws_rds_proxy

### ISSUE THREAD

**Issue by Virakal** [hashicorp/terraform-provider-aws#20146]
This is just a report that the issue in #16379 still exists, even though that issue was closed. The auth > username parameter is documented for the latest provider version but attempting to use it results in the following error: `An argument named "username" is not expected here.`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by kamilturek** [comment]
I am going to work on this.

**Comment by kamilturek** [comment]
I am experiencing weird behaviour. 

So the only allowed value for `AuthScheme` is `SECRETS`. If not specified, it looks like it defaults to `SECRETS` as well. But when I try to set `UserName` next to `AuthScheme`, a following is raised.

```
Error: Error updating DB Proxy: InvalidParameterValue: UserName must not be set in UserAuthConfig when SECRETS AuthScheme is used.
	status code: 400
```

I'd appreciate any advice on this. Also, I suspect that this issue may be a reason why this attribute wasn't implemented until now.
