### ISSUE TITLE
Route Table Association for Internet Gateway Error

### ISSUE THREAD

**Issue by adrianteri** [hashicorp/terraform-provider-aws#20187]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

![Screenshot from 2021-07-14 21-42-16](https://user-images.githubusercontent.com/10687877/125676004-251cd4ec-23ce-4518-aa65-73b81be823d8.png)

### Affected Resource(s)

* aws_route_table_association

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/hashicorp/aws" {
  version     = "3.49.0"
  constraints = "~> 3.0"
  hashes = [
    "h1:Xvsiilfz2CItH9EsDLXzpFf10ARDNmXm0Ey4s/vPluM=",
    "zh:35fa4cf6669ef6d4b002bc1494ef7168c3100c1248e9b7ef4ac1112209455e4d",
    "zh:59742ddcaa52a7279966809c792951f4b4b8e3d5b769205a0598030cd7dcfa89",
    "zh:5b36ae146ad0dc5d228ecb52f5160673ed02cf7e5415fde8da2f99fd8037d37d",
    "zh:61713827833a9411abe1bc46616469a6f1be2395960268e478d901700b2176fa",
    "zh:6726690c72204b542e8fd7bb0d725874ea6c5d21ce1e76afe458fd56ff371a77",
    "zh:a8c222830241d09faaa56e318a305b2af12c80ee675ee5af10cd33cc9ddfa1b9",
    "zh:b41d140ee952ff796c384e9a9f0cbefb80cda5f140595c0bb04b20c4338caf14",
    "zh:b94848e3f2acc3bc899639c546f5d8673cfe9dee1f18138508f6d835b3393de1",
    "zh:c1866f25050c8a408daf30a36ddf87a5d744657a81b88ba2fff77b8b8b8e30c1",
    "zh:f26a7be8b4459fed1786b2752d83bf95eef8862b6b7c4758c30b36bf2f4380f3",
    "zh:f69e4f8c700e9449f2f444784a08c08aa5532d8c269f83740b56b7ac7a478926",
  ]
}
```
### Debug Output

GitHub Gist - https://gist.github.com/adrianteri/1d205c561f72713a2bd67416db5c567c

### Panic Output
**N/A**

### Expected Behavior

Creation of resource success!
### Actual Behavior
Error on creation the association for an internet gateway with a route table.

### Steps to Reproduce

1. `terraform apply` basic_vpc.tf in Github Gist.
**N.B** Account uses the Eu-Central-1 (Frankfurt) region.

### Important Factoids
**N/A**

### References

**N/A**

**Comment by susumutomita** [comment]
I think this issue is related following documentation by AWS.
https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Route_Tables.html#gateway-route-table
```
Rules and considerations
You cannot associate a route table with a gateway if any of the following applies:

:
The route table contains existing routes to CIDR blocks outside of the ranges in your VPC.
```

It looks your terraform file defined a route table that has a route to 0.0.0.0/0 to the internet.
On the other hand the vpc cidr_block is defined "10.0.0.0/16".
Then try to associate the route table to the edge.
```
resource "aws_vpc" "Basic-Vpc" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_support   = "true"
  enable_dns_hostnames = "true"
  instance_tenancy     = "default"

  tags = {
    Project       = "PracticeIACwithTerraform"
    CreatedBy     = "terraform-cli-adrianteri"
    AWS-Component = "Vpc-Eu-Central-1"
  }
}
:
resource "aws_route" "Route-To-Internet" {
  route_table_id         = aws_route_table.Custom-Route-Table.id
  destination_cidr_block = "0.0.0.0/0"
  gateway_id             = aws_internet_gateway.IGW.id
  depends_on             = [aws_route_table.Custom-Route-Table]
}
:
resource "aws_route_table_association" "Route-Table-IGW-Association" {
  gateway_id     = aws_internet_gateway.IGW.id
  route_table_id = aws_route_table.Custom-Route-Table.id
}
```

I also see the same error when I try to associate the route table to edge in AWS Console.
Therefore I think this is not terraform issue but AWS restriction.

FYI I also try to delete the route to the internet-gateway and run terraform then I succeeded to associate the route table to the edge.
```
resource "aws_vpc" "Basic-Vpc" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_support   = "true"
  enable_dns_hostnames = "true"
  instance_tenancy     = "default"

  tags = {
    Project       = "PracticeIACwithTerraform"
    CreatedBy     = "terraform-cli-adrianteri"
    AWS-Component = "Vpc-Eu-Central-1"
  }
}
:
resource "aws_route_table_association" "Route-Table-IGW-Association" {
  gateway_id     = aws_internet_gateway.IGW.id
  route_table_id = aws_route_table.Custom-Route-Table.id
}
```
 
Hopefully this information would helpful to resolve your issue:)

Thanks

**Comment by adrianteri** [comment]
Thanks @susumutomita  for this.

I forgot I opened this issue. I got confused as the resource **terraform** provides to associate both subnets and gateways is the same: ***aws_routetable_association*** whereas in **CloudFormation** there is ***AWS::EC2::SubnetRouteTableAssociation*** and ***AWS::EC2::GateWayRouteTableAssociation***.
 
 A Gateway attachment is sufficient if you don't have Virtual Private Gateways or don't want fine grained  routing control for inbound traffic via the gateway.


From AWS docs:
> A gateway route table associated with an internet gateway supports routes with the following targets:
>    * The default local route
>    * A Gateway Load Balancer endpoint
>    * A network interface for a middlebox appliance

Closing this issue.
