### ISSUE TITLE
Support schedulers value for aws_mwaa_environment resource

### ISSUE THREAD

**Issue by bhushan-chirmade-tm** [hashicorp/terraform-provider-aws#20185]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_mwaa_environment

### Potential Terraform Configuration

```hcl
resource "aws_mwaa_environment" "airflow" {
  schedulers                           = 5
}
```

### References
* https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/mwaa.html#MWAA.Client.create_environment

**Comment by atul-chegg** [comment]
Support for schedulers will allow us to use mwaa version 2 effectively. Any ETA on this issue?

**Comment by tracycarley** [comment]
Any update on this feature?
