### ISSUE TITLE
aws_waf_web_acl  missing from documentation

### ISSUE THREAD

**Issue by Jeinhaus** [hashicorp/terraform-provider-aws#20198]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```console
❯ terraform version
Terraform v1.0.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.49.0

```

### Affected Resource(s)

* aws_waf_web_acl
* aws_wafv2_rule_group
* and possibly more?

### Description

The above mentioned resources are missing from the [official documentation](https://registry.terraform.io/providers/hashicorp/aws/3.49.0/docs/). When you visit the docs for these resources for version 3.48.0, e.g. the [web_acl](https://registry.terraform.io/providers/hashicorp/aws/3.48.0/docs/resources/wafv2_web_acl),  they link to the current documentation but redirect to the documentation's home page.

### Expected Behavior

The documentation should still be available since the resources have not been removed (afaik).

### Actual Behavior

The documentation is not available

### Steps to Reproduce

Go [here](https://registry.terraform.io/providers/hashicorp/aws/3.48.0/docs/resources/wafv2_web_acl) and click the [link to visit the latest documentation
](https://registry.terraform.io/providers/hashicorp/aws/3.49.0/docs).

**Comment by bruceharrison1984** [comment]
wafv2_web_acl is also affected by this. Rolling back to the 4.38.0 documentation makes it appear in the index again.

**Comment by calebplum** [comment]
Also affected:
- aws_wafv2_web_acl_association

> wafv2_web_acl is also affected by this. Rolling back to the 4.38.0 documentation makes it appear in the index again.

I think you mean `3.38.0`

**Comment by PowerShellPat** [comment]
Noticed this today also.

The resource I was after is aws_wafv2_web_acl

URL is working completely fine, but it doesn't appear in the list:

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl

Missing on versions 3.50.0 and 3.49.0 of the documentation.

**Comment by anGie44** [comment]
Hi @Jeinhaus . Thank you for raising this issue, since last week's release I believe a fix to the registry was pushed and the resources in question are now visible from the sidebar. Closing this as fixed, but please reach out if you have any questions!
