### ISSUE TITLE
Unable to provision redshift snapshot copy grant

### ISSUE THREAD

**Issue by omkar-k3** [hashicorp/terraform-provider-aws#20196]
Hello Team,

I am trying to provision redshift snapshot copy grant in us-east-1 region, but encounetring below error.

Error: Provider produced inconsistent result after apply

When applying changes to
aws_redshift_snapshot_copy_grant.RedshiftCopyGrant[0], provider
"registry.terraform.io/-/aws" produced an unexpected new value for was
present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Below is my code

resource "aws_redshift_snapshot_copy_grant" "RedshiftCopyGrant" {
  count = local.create_copy_grant ? 1 : 0
  provider =  aws.east
  snapshot_copy_grant_name = "${var.environment}-grant"
}

**Comment by breathingdust** [comment]
Hi @omkar-k3! Could you use the issue template and create a new issue filling in all required fields so we have the information we need to investigate your issue? Thanks!
