### ISSUE TITLE
Terraform unable to delete the AWS routing table association

### ISSUE THREAD

**Issue by RishiR2** [hashicorp/terraform-provider-aws#20216]
here is the exact error :

**Error: error waiting for Route Table Association (rtbassoc-063***) delete: unexpected state 'associated', wanted target ''. last error: %!s(<nil>)**

note : The VPC and routing table everything created through TF and used "wait" to 2ms to de associate the dependency. But its kind of intermittent issue.
hashicorp/aws v3.50.0 - is the version 
and we use TF 0.15 version.

here is the Creation of route table assiciations
######################################################################
# -------------- Creating Route Tables Associations ------------------
######################################################################
resource "time_sleep" "wait" {
  depends_on = [aws_route_table.prv1_rt,aws_route_table.prv2_rt,aws_route_table.public_rt]
  destroy_duration = "2m"
}

## Frontend AZ A
resource "aws_route_table_association" "fe_subnet_1_association" {
  route_table_id = aws_route_table.prv1_rt.id
  subnet_id      = aws_subnet.module_frontend_subnet_1.id
  depends_on = [time_sleep.wait]
}
## Frontend AZ B
resource "aws_route_table_association" "fe_subnet_2_association" {
  route_table_id = aws_route_table.prv2_rt.id
  subnet_id      = aws_subnet.module_frontend_subnet_2.id
  depends_on = [time_sleep.wait]
}

#Backend AZ A
resource "aws_route_table_association" "be_subnet_1_association" {
  route_table_id = aws_route_table.prv1_rt.id
  subnet_id      = aws_subnet.module_backend_subnet_1.id
  depends_on = [time_sleep.wait]
}
#Backend AZ B
resource "aws_route_table_association" "be_subnet_2_association" {
  route_table_id = aws_route_table.prv2_rt.id
  subnet_id      = aws_subnet.module_backend_subnet_2.id
  depends_on = [time_sleep.wait]
}

## Public
resource "aws_route_table_association" "public_subnet_1_association" {
  route_table_id = aws_route_table.public_rt.id
  subnet_id      = aws_subnet.module_public_subnet_1.id
  depends_on = [time_sleep.wait]
}

## Public
resource "aws_route_table_association" "public_subnet_2_association" {
  route_table_id = aws_route_table.public_rt.id
  subnet_id      = aws_subnet.module_public_subnet_2.id
  depends_on = [time_sleep.wait]
}

**Comment by obourdon** [comment]
We also sometimes get this error but it seems transient (aka it is not always occurring). In our case:
terraform: 0.14.11
aws-provider: 3.48.0

**Comment by obourdon** [comment]
May be changing [the following code](https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/internal/service/ec2/waiter/waiter.go#L373) into
```
Pending: []string{ec2.RouteTableAssociationStateCodeDisassociating, ec2.RouteTableAssociationStateCodeAssociated},
```
would fix the issue

**Comment by obourdon** [comment]
I remember fixing similar issue for placement_group [issue #9915](https://github.com/hashicorp/terraform-provider-aws/issues/9915) with [PR #11671](https://github.com/hashicorp/terraform-provider-aws/pull/11671)
