### ISSUE TITLE
aws_route timeouts do not seem to be respected

### ISSUE THREAD

**Issue by slefki** [hashicorp/terraform-provider-aws#20227]
Timeouts for aws_route resources do not seem to be respected. In my use case, routes are provisioned by looping over a list of ~20 destinations. From time to time, the routes creation times out after 2 minutes while waiting for state to become ready. 
Note that timeouts for creation and deletion are set to 10 minutes.

**Terraform Version:**
```
Terraform v0.15.4 
on linux_amd64
```

**Provider Version:**
`hashicorp/aws v3.48.0 (signed by HashiCorp)`

**HCL:**
```
 resource "aws_route" "route-az1" {
   for_each = toset(local.tgw_routes)
   route_table_id            =  var.route_table_id
   destination_cidr_block    =  each.key
   transit_gateway_id = var.tgw_id
   timeouts {
     create = "10m"
     delete = "10m"
   }
   depends_on = [
     aws_ec2_transit_gateway_vpc_attachment.tgw_vpc_attachment
   ]
}
```
**Error:**
```
module.tgw-attachment.aws_route.route-az1["151.109.0.0/16"]: Still creating... [1m50s elapsed] 
module.tgw-attachment.aws_route.route-az1["151.109.0.0/16"]: Still creating... [2m0s elapsed] 

Error: error waiting for Route in Route Table (rtb-0026655720eae379d) with destination (151.109.0.0/16) to become available: timeout while waiting for state to become 'ready' (timeout: 2m0s) 
on ../30049-aws-terraform-transit-gateway-attachment-module/main.tf line 94, in resource "aws_route" "route-az1": 
94: resource "aws_route" "route-az1" { 

```

**Comment by lorelei-rupp-imprivata** [comment]
I hit this today on us-east-1 with aws provider 3.50.0 and terraform 0.14.7. A 5m create timeout was set, but the error was (timeout2m) `Error: error waiting for Route in Route Table (rtb-xxx) with destination (0.0.0.0/0) to become available: timeout while waiting for state to become 'ready' (timeout: 2m0s)`

**Comment by erashu212** [comment]
I am facing a similar issue and have logged in as #20274

**Comment by slefki** [comment]
@bill-rich Would it make sense to classify this issue as a bug rather than an "enhancement"? Note that the feature is documented here: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route#timeouts but is not working.

**Comment by akataz** [comment]
I'm hitting this issue as well using TF 0.13.5, with a 5 minute timeout timing out at 2 minutes. Same error message as @lorelei-rupp-imprivata.

**Comment by jdcalder9** [comment]
We're running into this bug as well.  Our time-out is set for 5 minutes but it stops processing at the 2 minute mark.  This failure leaves the state-file in a corrupted/partial state which we have to manually fix.  This issue is breaking our automation.

**Comment by diego-ojeda-binbash** [comment]
Hi! We are also having this issue in our automation. Any response will be much appreciated. 🙏

**Comment by exequielrafaela** [comment]
We're having this problem as well. There are any updates on this please?

**Comment by eranelbaz** [comment]
Hi! We are also having this issue in our Terraform stack
changed the timeout to 5m but still
`Error: error waiting for Route in Route Table (rtb-056321e15207720fc) with destination (0.0.0.0/0) to become available: timeout while waiting for state to become 'ready' (timeout: 2m0s)`

**Comment by mkirtanisu** [comment]
Same issue here. We are mitigating this by using [time_sleep](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep)

`
resource "time_sleep" "wait10mins" {
  depends_on = [aws_nat_gateway.nat_gateway]
  create_duration = "10m"
}

resource "aws_route" "private_route" {
  depends_on             = [time_sleep.wait10mins]
  route_table_id         = aws_route_table.private_route_table.id
  destination_cidr_block = "0.0.0.0/0"
  nat_gateway_id         = aws_nat_gateway.nat_gateway.id

  timeouts {
    create = "15m"
    delete = "2h"
  }
}`

**Comment by WayneStallwood** [comment]
Judging by lines 50-53 of resource_aws_route.go the ability to adjust timeouts hasn't been implemented. 

```
		Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(2 * time.Minute),
			Delete: schema.DefaultTimeout(5 * time.Minute),
		},
```

**Comment by jValdron** [comment]
> Judging by lines 50-53 of resource_aws_route.go the ability to adjust timeouts hasn't been implemented.
> 
> ```
> 		Timeouts: &schema.ResourceTimeout{
> 			Create: schema.DefaultTimeout(2 * time.Minute),
> 			Delete: schema.DefaultTimeout(5 * time.Minute),
> 		},
> ```

Seems to me like this is just to provide the default values, it's setup the same way in other resources: https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_instance.go#L47

I am also facing this issue, but often while trying to destroy a route associated to a TGW:
```
Error: error waiting for Route in Route Table (rtb-0906ab731341c3edd) with destination (10.74.128.0/20) to delete: timeout while waiting for resource to be gone (last state: 'ready', timeout: 2m0s)
--

With the following timeouts:
```
  timeouts {
    create = "15m"
    delete = "20m"
  }
```

**Comment by msahihi** [comment]
> Judging by lines 50-53 of resource_aws_route.go the ability to adjust timeouts hasn't been implemented.
> 
> ```
> 		Timeouts: &schema.ResourceTimeout{
> 			Create: schema.DefaultTimeout(2 * time.Minute),
> 			Delete: schema.DefaultTimeout(5 * time.Minute),
> 		},
> ```

I believed this was refactored in https://github.com/hashicorp/terraform-provider-aws/pull/17319 with v3.35.0. I hope my fix will fix the issue
