### ISSUE TITLE
Documentation missing for 3.50.0

### ISSUE THREAD

**Issue by Jeroen-Bode** [hashicorp/terraform-provider-aws#20249]
Hi there,

Forgive me if I'm in the wrong place for this (please point me to the correct location if I'm indeed at the wrong address here :) )
Checking out the documentation on https://registry.terraform.io/providers/hashicorp/aws/latest/docs I noticed that for version 3.50.0, WAFv2 some of the documentation is missing compared to version 3.48.0

3.50.0:
![image](https://user-images.githubusercontent.com/42138207/126348491-473cfa0b-a100-4e91-bc94-25b3a112a129.png)

3.48.0:
![image](https://user-images.githubusercontent.com/42138207/126348909-d797684e-f78f-4d57-b99f-ea286990ad0e.png)

Now obviously I can use the documentation from 3.48.0 ... but I'd expected it to be available also for 3.50.0.
I don't know if this is a normal practise (I'm relatively new with Terraform).

When I look at the source in https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/ the correct documentation seems to be present. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ewbankkit** [comment]
Related: #20074.

**Comment by breathingdust** [comment]
Hi @Jeroen-Bode! This was caused by an issue in the registry that was presenting display of more than 1000 resources/datasources. This has now been resolved!
