### ISSUE TITLE
Amazon MQ now supports updating the maintenance window time 

### ISSUE THREAD

**Issue by cisnerosk** [hashicorp/terraform-provider-aws#20241]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the current configuration, Amazon MQ currently does not support updating the maintenance window. Changes to the maintenance window start time will force a new broker to be created. I believe this has been changed in this recent [post](https://forums.aws.amazon.com/ann.jspa?annID=8810). If that is the case, then hopefully the Terraform configuration can be changed as well.

### New or Affected Resource(s)

* aws_mq_broker

### Potential Terraform Configuration

Changing this [line](https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_mq_broker.go#L238) to false.

```
			"maintenance_window_start_time": {
				Type:     schema.TypeList,
				MaxItems: 1,
				Optional: true,
				Computed: true,
				ForceNew: false,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"day_of_week": {
							Type:         schema.TypeString,
							Required:     true,
							ValidateFunc: validation.StringInSlice(mq.DayOfWeek_Values(), true),
						},
						"time_of_day": {
							Type:     schema.TypeString,
							Required: true,
						},
						"time_zone": {
							Type:     schema.TypeString,
							Required: true,
						},
					},
				},
			},
```

### References

https://forums.aws.amazon.com/ann.jspa?annID=8810

If this is correct, I'm happy to open a PR with the above changes for review, as well as updating the [documentation](https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/mq_broker.html.markdown#maintenance_window_start_time). If the above is not correct, I can close this PR.

Thank you for your time!

**Comment by prateekrastogi-retinai** [comment]
Hi, is there an update on this issue. We are unable to modify the Amazon MQ rabbitmq broker maintenance window, even if we try to modify the window Terraform should prompt us to create a new broker altogether but that is also not the case. Terraform just ignores the maintenance window changes.

**Comment by jonathan-russo** [comment]
I am also experiencing this issue.  What's strange is that a `terraform plan` identifies that a change to the maintenance window is needed and a `terraform apply` appears to apply it(Reports that cluster modifications were made).  However the changes are never applied in AWS.  

I can successfully edit the maintenance window with the AWS CLI so it definitely appears possible.
`aws mq update-broker --broker-id b-7174df33-3d9d-49f1-ac99-fa31f93b7716 --maintenance-window-start-time DayOfWeek=SUNDAY,TimeOfDay=13:00,TimeZone=UTC`

**Comment by Gowiem** [comment]
@cisnerosk looks like you found the culprit and updating that single line will fix it... To move it along I say open the PR!
