### ISSUE TITLE
EKS node_group creation failure not kept in state

### ISSUE THREAD

**Issue by derjust** [hashicorp/terraform-provider-aws#20268]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.15.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.50.0
+ provider registry.terraform.io/hashicorp/helm v2.0.3
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
```

### Affected Resource(s)

* `aws_eks_node_group`

### Debug Output

```
│ Error: error waiting for EKS Node Groupe (xvp-eks-shared-dev:xvp-mindata-api-dev-charming-peacock) to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: %!s(<nil>)
```

### Expected Behavior

If Terraform fails to create an EKS node group it should keep information about that resource around.
If at the next time that Terraform runs & the node group is ACTIVE there should be no need to change anything.
Otherwise Terraform should try to recreate the node group as the resource should be considered `tainted`

### Actual Behavior

If Terraform fails to create an EKS node group it will not update the state file that the node group as an AWS resource exists.
Therefore re-running Terraform will fail as the node group already exists (even if the underlying issue was fixed) 

### Steps to Reproduce

1. `terraform apply`
2. Creation of node group fails, `apply` reports 
    ```
    │ Error: error waiting for EKS Node Groupe (node-group-name) to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: %!s(<nil>)
    ```
3. Optional: Fix the underlying issue 
4. Re-run `terraform apply`
5. Terraform tries to create the `node_group` again and fails with ```
│ Error: error creating EKS Node Group (node-group-name): ResourceInUseException: NodeGroup already exists with name node-group-name and cluster name cluster
```

**Comment by ewbankkit** [comment]
@derjust Thanks for raising this issue.
In such multi-part logical resource creation operations, if any failures occur after the resource ID is set Terraform should mark the resource as [_tainted_](https://www.terraform.io/docs/cli/commands/untaint.html) and propose that the resource is recreated (deleted and then created) during the next plan, so your step 4 should propose such a recreation.
Did `terraform apply` (or `terraform plan`) not show this?

**Comment by derjust** [comment]
No, a subsequent execution of `plan` or `apply` behaved as if the node group doesn't exist (isn't part of the state)
So `plan` shows it as creation, `apply` tries to create the node group and it faills as such a node group already exist in AWS

**Comment by wgj** [comment]
Just popping in to say I saw this behavior (failed AWS resource creation; failed to add to state) with more recent versions than reported:
```
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.4.0
```
