### ISSUE TITLE
Host/Path rewrite support for App Mesh Gateway Routes

### ISSUE THREAD

**Issue by kylie-yamamoto** [hashicorp/terraform-provider-aws#20272]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has released support for being able to rewrite external requests for app mesh. This was being tracked in this [issue](https://github.com/aws/aws-app-mesh-roadmap/issues/73) under the AWS roadmap.
Currently, if you are using a gateway route with a path match type, that match is rewritten to `/`, for our use case, we do not want the request path to be altered. With the update that was released on June 14, 2021 (see announcement [here](https://aws.amazon.com/about-aws/whats-new/2021/06/aws-app-mesh-introduces-enhanced-ingress-traffic-management-capabilities/)), you can override this option to not have the gateway route rewrite the path. 

### New or Affected Resource(s)

* aws_appmesh_gateway_route

### Potential Terraform Configuration

```hcl
resource "aws_appmesh_gateway_route" "gateway_route" {
  name                 = "service1-route"
  mesh_name            = "app-mesh"
  virtual_gateway_name = "virtual-gateway"
  spec {
    http_route {
      match {
        prefix = "/service1/info",
      }
      action {
        target {
          virtual_service {
            virtual_service_name = "virtual-service"
          }
        }
        rewrite {
          prefix {
            defaultPrefix =  DISABLED
          }
        }
      }
    }
  }
}
```

### References

* https://github.com/aws/aws-app-mesh-roadmap/issues/73
* https://aws.amazon.com/about-aws/whats-new/2021/06/aws-app-mesh-introduces-enhanced-ingress-traffic-management-capabilities/
* https://github.com/aws/aws-app-mesh-examples/tree/main/walkthroughs/howto-match-and-rewrite-at-ingress

* #0000

**Comment by jamiepedwards** [comment]
Not having this seriously limits the capabilities of this resource.  You end up having to rewrite the upstream service so it binds to `/`, or you have to do silly/hacky things downstream like rewriting requests to double the path prefix.

**Comment by gallowaystorm** [comment]
Any update on this?  I am in the same boat as @jamiepedwards

**Comment by pmapkiranch** [comment]
Any update on this? I am in the same boat as @gallowaystorm and @jamiepedwards. This will be very useful feature

**Comment by mkielar** [comment]
There's plenty of us on that boat. Looks like AppMesh is not getting too much love, which is sad. There are other features that are missing like Priorities for Gateway Rules (#21345) Response Types for Virtual Nodes (#21389) or a bunch of other settings for GatewayRoutes that are long available via API, but missing from Terraform. The amount of Python I have to write to work-around these lacking features is slowly getting out of hand... :(
