### ISSUE TITLE
Data Source: aws_ec2_instance_type_offerings

### ISSUE THREAD

**Issue by anthonyra** [hashicorp/terraform-provider-aws#20275]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm attempting to mimic the response to this AWS CLI call in Terraform using the aws_ec2_instance_type_offerings. In which it returns the availability zones that the instance is available in depending on the region selected.

```bash
 aws ec2 describe-instance-type-offerings \     
    --filters Name=instance-type,Values=${type}\
    --query "InstanceTypeOfferings[].Location" \
    --region ${region}
```

### New or Affected Resource(s)

* aws_ec2_instance_type_offerings

### Potential Terraform Configuration

```hcl
data "aws_ec2_instance_type_offerings" "availability_zones" {
  filter {
    name   = "instance-type"
    values = ["${local.instance_type}"]
  }

  location_type = "availability-zone"
}
```

However, I think the only available outcomes are `id` and `instance_types`...

### References

* #0000

**Comment by ewbankkit** [comment]
@anthonyra Thanks for raising this issue.
It has already been noticed in #15272. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by anthonyra** [comment]
I swear I tried to find an open issue for this on Github... guess I need to work on my search skills. Thank you for looking into it and I'll be tracking that issue!
