### ISSUE TITLE
Empty `string_attribute_constraints` on user_pool attribute creates no-op update that results in a failure when applied

### ISSUE THREAD

**Issue by k4l397** [hashicorp/terraform-provider-aws#20276]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.3
+ provider registry.terraform.io/hashicorp/aws v3.50.0

### Affected Resource(s)

* aws_cognito_user_pool

### Description

- Problem occurs when updating an existing `user_pool` resource. 
- If the user_pool already contains an attribute in a `schema` block with empty `string_attribute_constraints`, when a new attribute is added it produces a plan that replaces the existing attribute with an equivalent attribute. 
- Instead there should be no update applied to existing attributes, only the new one

### Expected Behavior

- Terraform plan log should output only this update to the user pool
```
      + schema {
          + attribute_data_type      = "String"
          + developer_only_attribute = false
          + mutable                  = true
          + name                     = "something_else"
          + required                 = false

          + string_attribute_constraints {
              + max_length = "320"
              + min_length = "1"
            }
        }
```
- Terraform apply should complete successfully 

### Actual Behavior

- Terraform plan log shows the existing attribute being replaced in addition to the new attribute (you can't replace change / destroy existing attributes)
```
      + schema {
          + attribute_data_type      = "String"
          + developer_only_attribute = false
          + mutable                  = true
          + name                     = "something"
          + required                 = false

          + string_attribute_constraints {}
        }
      - schema {
          - attribute_data_type      = "String" -> null
          - developer_only_attribute = false -> null
          - mutable                  = true -> null
          - name                     = "something" -> null
          - required                 = false -> null

          - string_attribute_constraints {}
        }
      + schema {
          + attribute_data_type      = "String"
          + developer_only_attribute = false
          + mutable                  = true
          + name                     = "something_else"
          + required                 = false

          + string_attribute_constraints {
              + max_length = "320"
              + min_length = "1"
            }
        }
```

- `terraform apply` returns this error:
```
error updating Cognito User Pool (<userpool_id>): cannot modify or remove schema items
```

### Steps to Reproduce

1. Use terraform to create a userpool with this configuration:
```hcl
provider "aws" {
  region = "eu-west-2"
}

resource "aws_cognito_user_pool" "user_pool" {
  name = "test"

  schema {
    attribute_data_type      = "String"
    developer_only_attribute = false
    mutable                  = true
    name                     = "something"
    required                 = false
    string_attribute_constraints {}
  }
}
```
2. Update the configuration by adding a second `schema` block to the `aws_cognito_user_pool` resource, e.g.:
```
  schema {
    attribute_data_type      = "String"
    developer_only_attribute = false
    mutable                  = true
    name                     = "something_else"
    required                 = false
    string_attribute_constraints {
      min_length = 1
      max_length = 320
    }
  }
```
3. Run `terraform plan` - observe actual behaviour mentioned above
4. Run `terraform apply` - apply should error

**Comment by GavinWu1991** [comment]
I submitted a pull request for this bug.

**Comment by rasako** [comment]
I can confirm this issue is still happening with current versions:

Terraform v1.6.6

provider registry.terraform.io/hashicorp/aws v5.31.0

The only workaround I found was to manually create the new attribute. This prevents Terraform from detecting a change in the already-existing attribute that was created with empty `string_attribute_constraints`

**Comment by kuzaxak** [comment]
@GavinWu1991 @gdavison I think the fix didn't cover the existing state and made it broken. 

I have the following in my state file:
```
{
  "attribute_data_type": "String",
  "developer_only_attribute": false,
  "mutable": true,
  "name": "custom:domains",
  "number_attribute_constraints": [],
  "required": false,
  "string_attribute_constraints": [
    {
      "max_length": null,
      "min_length": null
    }
  ]
},
```

And now I have a permanent diff that can't be applied:
```hcl
 + schema {
  + attribute_data_type      = "String"
  + developer_only_attribute = false
  + mutable                  = true
  + name                     = "custom:domains"
  + required                 = false

  + string_attribute_constraints {
        # (2 unchanged attributes hidden)
    }
}
```

In the code, I tried to use the following:
* `string_attribute_constraints: null` 
* `string_attribute_constraints: {max_length: null}` 


Nothing from that works.
