### ISSUE TITLE
Security Group Rule Id Support

### ISSUE THREAD

**Issue by MarZab** [hashicorp/terraform-provider-aws#20282]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS added the option to select the security group rule by id. Adding this will allow the security group to be edited from several stacks cleanly.

### New or Affected Resource(s)

* aws_security_group_rule

### Potential Terraform Configuration

```hcl
resource "aws_security_group_rule" "example" {
  id = "sgr-abcdefghi01234561"
  # ... snip
  security_group_id = "sg-123456"
}
```

### References

* https://aws.amazon.com/blogs/aws/easily-manage-security-group-rules-with-the-new-security-group-rule-id/

**Comment by ewbankkit** [comment]
@MarZab Thanks for raising this issue.
It has already been noticed in #20104. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
