### ISSUE TITLE
Creating an aws_instance using launch template fails when using spot instances and instance_interruption_behavior = "stop"

### ISSUE THREAD

**Issue by jheino** [hashicorp/terraform-provider-aws#20286]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.51.0
```

### Affected Resource(s)

* aws_instance
* aws_launch_template

### Terraform Configuration Files

```hcl
data "aws_ssm_parameter" "ami" {
  name = "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
}

resource "aws_launch_template" "this" {
  image_id = data.aws_ssm_parameter.ami.value
  instance_type = "t3.nano"

  instance_market_options {
    market_type = "spot"

    spot_options {
      instance_interruption_behavior = "stop"
      spot_instance_type             = "persistent"
    }
  }
}

resource "aws_instance" "this" {
  launch_template {
    id      = aws_launch_template.this.id
    version = aws_launch_template.this.latest_version
  }
}
```

### Debug Output

https://gist.github.com/jheino/3cbb1668d66b7ca881a833b68998b21c

### Expected Behavior

Terraform creates a new EC2 instance from the launch template with the instance interruption behavior set to "stop".

### Actual Behavior

Launching the EC2 instance fails with the AWS API error message:

```
Error: Error launching source instance: InvalidParameterCombination: The parameter GroupName within placement information cannot be specified when instanceInterruptionBehavior is set to 'STOP'.
        status code: 400, request id: b5a252e4-4fd5-4a53-9cf9-1f8635139225
```

### Steps to Reproduce

1. `terraform apply`

### References

* #1986

**Comment by gordonbondon** [comment]
Should be fixed by #20372
