### ISSUE TITLE
Skipping the need for AWS creds seems to have broken in 3.51.0

### ISSUE THREAD

**Issue by alikhajeh1** [hashicorp/terraform-provider-aws#20287]
I think prior to [this change](https://github.com/hashicorp/terraform-provider-aws/pull/10807), the `skip_credentials_validation=true` and `skip_requesting_account_id=true` worked as expected. However, in 3.51.0, I'm seeing "error reading Instance Launch Template Id Tag: AuthFailure: AWS was not able to validate the provided access credentials" even when `launch_template` is not used (see following before/after examples). I was under the assumption that the 5 different [`skip_`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#argument-reference) arguments could be used to turn-off the need for AWS creds during testing (we have integration tests in https://github.com/infracost/infracost that started to fail this morning).

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.2 on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.50.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

### Affected Resource(s)

* aws_instance

#### 3.50.0 behavior
With this example, `terraform plan` worked ok:
```

terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.50.0"
    }
  }
}

provider "aws" {
  region                      = "us-east-1"
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  access_key                  = "mock_access_key"
  secret_key                  = "mock_secret_key"
}

resource "aws_instance" "web_app" {
  ami           = "ami-12312312"
  instance_type = "m5.4xlarge"
}
```

#### 3.51.0 behavior, where `terraform plan` fails
```
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.51.0"
    }
  }
}

provider "aws" {
  region                      = "us-east-1"
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  access_key                  = "mock_access_key"
  secret_key                  = "mock_secret_key"
}

resource "aws_instance" "web_app" {
  ami           = "ami-12312312"
  instance_type = "m5.4xlarge"
}
```

`terraform plan` produces this error:
```
│ Error: 1 error occurred:
│ 	* error reading Instance Launch Template Id Tag: AuthFailure: AWS was not able to validate the provided access credentials
│ 	status code: 401, request id: 123123-123123-123123-123-123123
│   with aws_instance.web_app,
│   on main.tf line 18, in resource "aws_instance" "web_app":
│   18: resource "aws_instance" "web_app" {
```

### Expected Behavior

`terraform plan` should have worked as it did in 3.50.0

### Actual Behavior

`terraform plan` failed with "error reading Instance Launch Template Id Tag: AuthFailure: AWS was not able to validate the provided access credentials".

### Steps to Reproduce

1. Create a new TF project with `main.tf` and the previously mentioned examples.
2. Run `terraform init` followed by `terraform apply` and notice how it works ok on 3.50.0 but not on 3.51.0

### References

* #10807

**Comment by gordonbondon** [comment]
Sorry, I did not expect my change to cause this. Currently reading instance tags is the only way to find out whether a launch template was used for its creation. 

This is used only in `CustomizedDiff` and `Read`, and I would not expect these to run during `terraform plan` with an empty state.

Can you please run terraform in [trace mode](https://www.terraform.io/docs/internals/debugging.html) (with `TF_LOG=TRACE` env) and upload logs somewhere, so we can find out where this is happening?

**Comment by alikhajeh1** [comment]
Thanks @gordonbondon - plz see [trace_logs.txt](https://github.com/hashicorp/terraform-provider-aws/files/6886710/trace_logs.txt) for the `3.51.0 behavior, where terraform plan fails` example in the GH issue description.

**Comment by gordonbondon** [comment]
Attempt at fixing this here #20357, please check if it works for you.

**Comment by alikhajeh1** [comment]
@gordonbondon thanks! I tested that PR and it works ok with the example in the GH issue description.
