### ISSUE TITLE
aws_msk_cluster: Unable to change broker instance type or encryption info client_broker without rebuilding the cluster

### ISSUE THREAD

**Issue by aagarwalincontact** [hashicorp/terraform-provider-aws#20292]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
3.38.0

### Affected Resource(s)

* aws_msk_cluster

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Cluster should be updated in place
### Actual Behavior
Cluster is destroyed and recreated

### Steps to Reproduce
Change instance type from one to other 
Or Change the client_broker from plaintext to TLS or vice versa

1. `terraform apply`

### References

* https://docs.aws.amazon.com/msk/latest/developerguide/msk-update-broker-type.html

**Comment by aagarwalincontact** [comment]
Any update on this ? As per Terraform issue https://github.com/hashicorp/terraform-provider-aws/pull/11451 , instance type update should work with latest terraform , but i am still facing this issue . Any suggestions

**Comment by danquack** [comment]
#17447 was supposed to address the instance_type upgrade, Im curious if you could elaborate on the work that would be needed?
