### ISSUE TITLE
Add Permissions Mode support to QLDB Ledger

### ISSUE THREAD

**Issue by gruebel** [hashicorp/terraform-provider-aws#20301]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon QLDB Ledger offers now the possibility to change the permissions mode and set it to the newer and better STANDARD mode.

### Affected Resource(s)

* r/aws_qldb_ledger
* d/aws_qldb_ledger

### Potential Terraform Configuration

```hcl
resource "aws_qldb_ledger" "test" {
  name             = "test-ledger"
  permissions_mode = "STANDARD"
}
```

### References

Docs:
https://docs.aws.amazon.com/qldb/latest/developerguide/getting-started-standard-mode.html

API:
https://docs.aws.amazon.com/qldb/latest/developerguide/API_UpdateLedgerPermissionsMode.html

* #0000

**Comment by kutysam** [comment]
Seems like KMS isn't supported on terraform also
