### ISSUE TITLE
resource/aws_api_gateway_vpc_link: Acceptance tests failing since 10 July 2021

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#20316]
Starting 10 July 2021, the acceptance tests `TestAccAWSAPIGatewayVpcLink_basic`, `TestAccAWSAPIGatewayVpcLink_tags`, `TestAccAWSAPIGatewayVpcLink_disappears`, and `TestAccAWSAPIGatewayUsagePlan_tags` have been failing with the error

```
Error: error waiting for API Gateway VPC Link (a1b2c3) deletion: couldn't find resource (21 retries)
```

### Affected Resource

* aws_api_gateway_vpc_link

**Comment by lorelei-rupp-imprivata** [comment]
I am seeing this consistently in us-west-1 with our API gateway terraform module that uses this resource. Every destroy consistently fails with this. Checking the AWS UI, the link is gone too

**Comment by lorelei-rupp-imprivata** [comment]
@gdavison is that other issue #20221 going to fix this bug?

**Comment by lorelei-rupp-imprivata** [comment]
Im testing out on 3.49.0 aws provider..,could it be related to this change https://github.com/hashicorp/terraform-provider-aws/commit/4d4335d305d3e53e4d9cbcab5f8546443a79f2f3? This fix was not in 3.49.0

**Comment by lorelei-rupp-imprivata** [comment]
pinning to 0.49.0 resolves this issue FYI

**Comment by lorelei-rupp-imprivata** [comment]
@anGie44 @gdavison we still see this issue, related to the prior PR merge potentially... any ideas on a potential fix?

**Comment by anGie44** [comment]
Hi @lorelei-rupp-imprivata , atleast for the `VPCLink` destroy errors you've come across, I believe we can update the waiter function's `Target` status to be empty slice e.g. `[]string{}` instead of the slice with an empty string as seen here:

https://github.com/hashicorp/terraform-provider-aws/blob/0f11ddaa6a0218e6f76e7734c66bdaeb40370b8a/aws/internal/service/apigateway/waiter/waiter.go#L15-L24

**Comment by lorelei-rupp-imprivata** [comment]
Thanks @anGie44  yeah something was definitely with how the return was being processed in our case, it was failing every time
