### ISSUE TITLE
Feature Request: CloudTrail Data Events - Advanced Event Selectors

### ISSUE THREAD

**Issue by sufiyanghori** [hashicorp/terraform-provider-aws#20319]
AWS has recently introduced an option of Advanced Event Selectors in CloudTrail Data Events, so that users can have more granular control of logging data.

The Advanced Events Selector allows users to Log Events based on the specific criteria, for instance, Log Events for specific ARNs or specific event types only, or exclude events from certain ARNs or event type etc. 

**Additional Info**
More details https://docs.amazonaws.cn/en_us/awscloudtrail/latest/userguide/logging-data-events-with-cloudtrail.html#creating-data-event-selectors-advanced

AdvancedEventSelector API: https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_AdvancedEventSelector.html

**Comment by ewbankkit** [comment]
@sufiyanghori Thanks for raising this issue.
It has already been noticed in #18867 (and is addressed via #19368) . I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
