### ISSUE TITLE
Add user_group argument to aws_elasticache_replication_group

### ISSUE THREAD

**Issue by jamesglennan** [hashicorp/terraform-provider-aws#20328]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Recently user and user group resources for elasticache were added to the terraform provider. However there is not currently a way to associate a user group with a replication group.

### New or Affected Resource(s)

Impacted Existing Data Sources

- aws_elasticache_replication_group: will have a new list of user_group_ids to associate user groups with the relevant replication group 

### Potential Terraform Configuration

```
resource "aws_elasticache_replication_group" "test" {
  replication_group_id          = test_replication_group
  replication_group_description = "test description"
  node_type                     = "cache.t3.small"
  port                          = 6379
  apply_immediately             = true
  auto_minor_version_upgrade    = false
  maintenance_window            = "tue:06:30-tue:07:30"
  snapshot_window               = "01:00-02:00"
  user_group_ids                = [aws_elasticache_user_group.test.id]
}

resource "aws_elasticache_user" "test" {
  user_id       = test_user_group
  user_name     = "default"
  access_string = "on ~app::* -@all +@read +@hash +@bitmap +@geo -setbit -bitfield -hset -hsetnx -hmset -hincrby -hincrbyfloat -hdel -bitop -geoadd -georadius -georadiusbymember"
  engine        = "REDIS"
  passwords     = ["password123456789"]
}
resource "aws_elasticache_user_group" "test" {
  user_group_id = test_user_group
  engine        = "REDIS"
  user_ids      = [aws_elasticache_user.test.user_id]
}
```

### References

https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Clusters.RBAC.html
https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateReplicationGroup.html#API_CreateReplicationGroup_RequestParameters

**Comment by jamesglennan** [comment]
I currently have some code that I've been working on for this, so happy to take this on

**Comment by edbighead** [comment]
was very surprised we can add `aws_elasticache_user_group` but can not associate it, waiting for the PR to be merged
