### ISSUE TITLE
aws_acm_certificate - allow validation from a "validation domain"

### ISSUE THREAD

**Issue by scott-doyland-burrows** [hashicorp/terraform-provider-aws#20324]
AWS terraform resource ```aws_acm_certificate```

Can this please be updated to allow a ```validation domain``` to be included when using email validation.

The link below shows the AWS CLI documentation regarding a ```validation domain```

https://docs.aws.amazon.com/cli/latest/reference/acm/resend-validation-email.html

Something like this in Terraform.  This should allow the validation emails to be sent to @example.com rather than @my.example.com

```
resource "aws_acm_certificate" "aws_acm_certificate" {
  domain_name       = "my.example.com"
  validation_method = "EMAIL"
  validation_domain = "example.com"
}
````

**Comment by gdavison** [comment]
The parameter `validation_option` was added in [v4.12.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.12.0) of the provider.

If you have other requests or enhancements to this feature, please open a new issue.
