### ISSUE TITLE
Service Catalog: provisioned_product resource has a 3 minute hard timeout

### ISSUE THREAD

**Issue by ajc86** [hashicorp/terraform-provider-aws#20323]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.0
Provider registry.terraform.io/hashicorp/aws v3.49.0

### Affected Resource(s)

* aws_servicecatalog_provisioned_product

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_servicecatalog_provisioned_product" "testsc" {
  product_id               = "prod-xxxxxxxxxxxxx"
  provisioning_artifact_id = "pa-xxxxxxxxxxx"
  name                     = "AWS-xxx-xxxxxx"
  
  provisioning_parameters {
    key   = "AccountName"
    value = var.account-name
  }
  
  provisioning_parameters {
    key   = "OrgUnitName"
    value = var.ou-name
  }
  
  provisioning_parameters {
    key   = "AccountEmail"
    value = var.account-email
  }
}
```

### Debug Output

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.new-account.aws_servicecatalog_provisioned_product.testsc: Creating...
module.new-account.aws_servicecatalog_provisioned_product.testsc: Still creating... [10s elapsed]
module.new-account.aws_servicecatalog_provisioned_product.testsc: Still creating... [20s elapsed]
module.new-account.aws_servicecatalog_provisioned_product.testsc: Still creating... [30s elapsed]
module.new-account.aws_servicecatalog_provisioned_product.testsc: Still creating... [40s elapsed]
module.new-account.aws_servicecatalog_provisioned_product.testsc: Still creating... [50s elapsed]
module.new-account.aws_servicecatalog_provisioned_product.testsc: Still creating... [1m0s elapsed]
module.new-account.aws_servicecatalog_provisioned_product.testsc: Still creating... [1m10s elapsed]
module.new-account.aws_servicecatalog_provisioned_product.testsc: Still creating... [1m20s elapsed]
module.new-account.aws_servicecatalog_provisioned_product.testsc: Still creating... [1m30s elapsed]
module.new-account.aws_servicecatalog_provisioned_product.testsc: Still creating... [1m40s elapsed]
module.new-account.aws_servicecatalog_provisioned_product.testsc: Still creating... [1m50s elapsed]
module.new-account.aws_servicecatalog_provisioned_product.testsc: Still creating... [2m0s elapsed]
module.new-account.aws_servicecatalog_provisioned_product.testsc: Still creating... [2m10s elapsed]
module.new-account.aws_servicecatalog_provisioned_product.testsc: Still creating... [2m20s elapsed]
module.new-account.aws_servicecatalog_provisioned_product.testsc: Still creating... [2m30s elapsed]
module.new-account.aws_servicecatalog_provisioned_product.testsc: Still creating... [2m40s elapsed]
module.new-account.aws_servicecatalog_provisioned_product.testsc: Still creating... [2m50s elapsed]
module.new-account.aws_servicecatalog_provisioned_product.testsc: Still creating... [3m0s elapsed]
╷
│ Error: error describing Service Catalog Provisioned Product (pp-rsgqpylridt5k): timeout while waiting for state to become 'AVAILABLE' (last state: 'UNDER_CHANGE', timeout: 3m0s)
│ 
│   with module.new-account.aws_servicecatalog_provisioned_product.testsc,
│   on account_module/main.tf line 1, in resource "aws_servicecatalog_provisioned_product" "testsc":
│    1: resource "aws_servicecatalog_provisioned_product" "testsc" {
### Expected Behavior

For Service Catalog provisioned products it is possible that some products take more than 10-20 minutes to be provisioned. Hence, the Terraform Apply should ideally proceed even after 3 minutes and eventually the service catalog product will be provisioned successfully.

### Actual Behavior

The Terraform Apply operation times out after 3 minutes of being triggered. This means if there are service catalog products with stacksets that takes more than 3 minutes to complete will just time out with the below error:

"timeout while waiting for state to become 'AVAILABLE' (last state: 'UNDER_CHANGE', timeout: 3m0s)"

Hence, the timeout of 3 minutes should be increased to say 30 minutes to ensure that the service catalog product will be provisioned successfully. Also it appears that the source code for the resource has 3 minute time out hard coded: https://github.com/hashicorp/terraform-provider-aws/pull/19122/files

### Steps to Reproduce

1. use the terraform resource "aws_servicecatalog_provisioned_product" to provision a service catalog product. You have to test this on a service catalog product that takes more than 3 minutes to provision.

2. `terraform apply`

### Important Factoids

The service catalog product I'm using takes 10 minutes to complete the provisioning.

### References

* #1 https://github.com/hashicorp/terraform-provider-aws/pull/13797
* #2 https://github.com/hashicorp/terraform-provider-aws/issues/15369

**Comment by ewbankkit** [comment]
@ajc86 Thanks for raising this issue.
It has already been noticed in #20253. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

This functionality was implemented via #20254 and released in [**v3.51.0**](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3510-july-22-2021) of the Terraform AWS Provider.
