### ISSUE TITLE
data.aws_subnet_ids has wrong id in tfstate

### ISSUE THREAD

**Issue by non7top** [hashicorp/terraform-provider-aws#20338]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/aws v3.51.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

* data.aws_subnet_ids

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```json
    {
      "mode": "data",
      "type": "aws_subnet_ids",
      "name": "xxxxxxxx",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "filter": null,
            "id": "vpc-xxxxxxxxx",
            "ids": [
              "subnet-xxxxxxx",
              "subnet-xxxxxxx"
            ],
            "tags": {
              "Name": "xxxxxxxxxxxxxxxxxxxxxx*"
            },
            "vpc_id": "vpc-xxxxxxxxxx"
          },
          "sensitive_attributes": []
        }
      ]
    },
```

```hcl
data "aws_subnet_ids" "xxxxxxx" {
  vpc_id = data.aws_vpc.xxxxxxxxxxxxxxxx.id

  tags = {
    Name = "xxxxxxxxxxxxxx*"
  }
}
```

### Expected Behavior

As it is tfstate ends up with multiple resources having same id, that is `data.aws_subnet_ids` and `data.aws_vpc` and probably resource `aws_vpc`. I would not expect `data.aws_subnet_ids` to have that id.
I'm using ids to lookup resource name from the tfstate and when looking for `"id": "vpc-xxxxxxxxxx"` I would expect only a resource representing the vpc.

### Actual Behavior

data.aws_subnet_ids has id matching the id of vpc resource.

### Steps to Reproduce

1. `terraform apply`

### References

* #9381
* #18060

**Comment by ewbankkit** [comment]
@non7top Thanks for raising this issue.
The `aws_subnet_ids` data source will be deprecated in favor of the new `aws_subnets` data source (whose ID will NOT be a VPC ID 😄). You may wish to migrate.
