### ISSUE TITLE
associate event bridge api destination with event rule/target

### ISSUE THREAD

**Issue by farooqte96** [hashicorp/terraform-provider-aws#20343]
AWS has introduced support of API Destination as target type for Event Bridge.

With PR (https://github.com/hashicorp/terraform-provider-aws/pull/18905) resource "aws_cloudwatch_event_api_destination" was introduced. However from "aws_cloudwatch_event_target", there's no option available to support this. Does anyone know how can i associate a resource "aws_cloudwatch_event_api_destination" as target to a cloudwatch_event_rule ?
Thanks

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.13.6
AWS provider version: 3.25.0

**Comment by anGie44** [comment]
Hi @farooqte96, thank you for raising this issue. Please note that the TF AWS discuss page (https://discuss.hashicorp.com/c/terraform-providers/tf-aws) is probably better suited for receiving quicker feedback/best practices for questions around resource usage. 

Nevertheless, making a first pass at the scenario described and referring to the AWS documentation that describes similar behavior but via the AWS console (https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-api-destinations.html#eb-api-destination-create), it seems you can use the `aws_cloudwatch_event_target` resource to reference the `api_destination` via the `target` argument and with the correct permissions (https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-use-identity-based.html#eb-target-permissions), so something along the lines of :
```terraform 
resource "aws_cloudwatch_event_target" "test" {
  rule      = aws_cloudwatch_event_rule.test.name
  target_id = "example"
  arn       = aws_cloudwatch_event_api_destination.test.arn
  role_arn  = aws_iam_role.test.arn
}

resource "aws_cloudwatch_event_rule" "test" {
  name                =  "example"
  schedule_expression = "rate(1 hour)"
}

resource "aws_cloudwatch_event_api_destination" "basic" {
  name                = "example"
  invocation_endpoint = "https://www.example.com/"
  http_method         = "GET"
  connection_arn      = aws_cloudwatch_event_connection.test.arn
}

resource "aws_iam_role" "test" {
  name = "example"

  assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "events.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
POLICY
}

resource "aws_iam_role_policy" "test" {
  name = "example"
  role = aws_iam_role.test.id

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "events:InvokeApiDestination"
      ],
      "Resource": [
        "arn:aws:events:::api-destination/*"
      ],
      "Effect": "Allow"
    }
  ]
}
EOF
}
```

Please note though that the above configuration hasn't been used in practice but hopefully should provide an idea of what is minimally required to communicate between the resources.

**Comment by farooqte96** [comment]
Thanks alot @anGie44 for great help. I really appreciate that. The above configuration works for me now. Thanks again
