### ISSUE TITLE
Add support for AWS Recovery Control Config 

### ISSUE THREAD

**Issue by ankita10051991** [hashicorp/terraform-provider-aws#20353]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
AWS introduced Route 53 Application Recovery Controller, a Amazon Route 53 set of capabilities that continuously monitors an application’s ability to recover from failures and controls application recovery across multiple AWS Availability Zones, AWS Regions, and on premises environments to help you to build applications that must deliver very high availability.

### New or Affected Resource(s)

* aws_route53_recovery_control_config

### Potential Terraform Configuration
TBD

### References

- Announcement https://aws.amazon.com/about-aws/whats-new/2021/07/amazon-route-53-announces-route-53-application-recovery-controller/
- User guide https://docs.aws.amazon.com/r53recovery/latest/dg/what-is-route53-recovery.html
- API docs https://docs.aws.amazon.com/recovery-cluster/latest/api/examples-cli-control.html
- Go SDK https://github.com/aws/aws-sdk-go/releases/tag/v1.40.9
- Blog post https://aws.amazon.com/blogs/aws/amazon-route-53-application-recovery-controller/

### Requires

Requires [AWS SDK v1.40.9](https://github.com/aws/aws-sdk-go/releases/tag/v1.40.9)

**Comment by anGie44** [comment]
Depends on https://github.com/hashicorp/terraform-provider-aws/pull/20348
