### ISSUE TITLE
Add Separate Resource for S3 Replication Configuration

### ISSUE THREAD

**Issue by jonjohnston** [hashicorp/terraform-provider-aws#20360]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

s3 replication configuration should be a separate resource. This will allow the ability to have use terraform to deploy a scenario where 2 buckets are replicating to each other. Right now, having replication in the bucket creation resource, requires the destination bucket to exist. So you can only have replication in 1 direction

### New or Affected Resource(s)

* aws_s3_bucket_replication  or aws_s3_bucket_replication_configuration

**Comment by anGie44** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/4418
