### ISSUE TITLE
aws_elasticache_replication_group with cluster_mode and num_node_groups = 1 doesn't create a redis cluster of one shard

### ISSUE THREAD

**Issue by CyrilDevOps** [hashicorp/terraform-provider-aws#20361]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/aws v3.51.0

### Affected Resource(s)

aws_elasticache_replication_group with 
  cluster_mode {
    replicas_per_node_group = xxx
    num_node_groups         = 1
  }

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

I expect terraform to create a redis cluster with one shard

### Actual Behavior

terraform create a redis non cluster instead

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

aws_elasticache_replication_group with 
  cluster_mode {
    replicas_per_node_group = xxx
    num_node_groups         = 1
  }
create a redis non cluster,
If after I modify num_node_groups to 2, aws refuse the make the change because the redis is non cluster.

aws_elasticache_replication_group with 
  cluster_mode {
    replicas_per_node_group = xxx
    num_node_groups         = 2
  }
it create a redis cluster with 2 shards, then if I modify num_node_groups to 1 and reapply, aws delete a shard
and I have a redis cluster with one shard. Then when I apply a plan I get no new change.

I want to be able to create a redis cluster with only one shard with aws_elasticache_replication_group cluster_mode num_node_groups = 1 directly, not having to create a 2 shards cluster and remove a shard.

We use one shard cluster redis to be able to growth with multiple shard later, but save cost today. Also elasticcache cluster redis behave better than normal redis when doing primary node failver (upgrade/patch...), it doesn't rely on DNS changes.

### References

* #0000

**Comment by gdavison** [comment]
Hi @CyrilDevOps. This is due to changes in the AWS API, some confusing terminology, and a poor attribute name choice in the provider. From the [`aws_elasticache_replication_group` documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group):

> Be aware of the terminology collision around "cluster" for aws_elasticache_replication_group. For example, it is possible to create a ["Cluster Mode Disabled [Redis] Cluster"](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Clusters.Create.CON.Redis.html). With "Cluster Mode Enabled", the data will be stored in shards (called "node groups"). See [Redis Cluster Configuration](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/cluster-create-determine-requirements.html#redis-cluster-configuration) for a diagram of the differences. To enable cluster mode, use a parameter group that has cluster mode enabled. The default parameter groups provided by AWS end with ".cluster.on", for example default.redis6.x.cluster.on.
