### ISSUE TITLE
Add tags to Resource Lex Bot

### ISSUE THREAD

**Issue by AdamTylerLynch** [hashicorp/terraform-provider-aws#20362]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like the ability to add tags to Lex Bots upon creation (can not be updated post-create)

### New or Affected Resource(s)

* aws_lex_bot

### Potential Terraform Configuration

```hcl
resource "aws_lex_bot" "test" {
  child_directed = false
  description    = "Bot to order flowers on the behalf of a user"
  name           = "%s"
  abort_statement {
    message {
      content      = "Sorry, I'm not able to assist at this time"
      content_type = "PlainText"
      group_number = 1
    }
    message {
      content      = "Sorry, I'm not able to assist at this time. Good bye."
      content_type = "PlainText"
      group_number = 1
    }
    response_card = "Sorry, I'm not able to assist at this time"
  }
  intent {
    intent_name    = aws_lex_intent.test.name
    intent_version = aws_lex_intent.test.version
  }
  tags = {
   name = "bot1"
  }
}

```

### References

* https://docs.aws.amazon.com/lex/latest/dg/API_PutBot.html

**Comment by anGie44** [comment]
Relates #15393
