### ISSUE TITLE
aws_emr_cluster ignores `ebs_config` in fleet unless there is exactly one

### ISSUE THREAD

**Issue by peay** [hashicorp/terraform-provider-aws#20378]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.52.0
```

### Affected Resource(s)

* aws_emr_cluster
* aws_emr_instance_fleet

### Terraform Configuration Files

```hcl
resource "aws_emr_cluster" "example" {
  master_instance_fleet {
    instance_type_configs {
      instance_type = "m4.xlarge"

      # Volume 1
      ebs_config {
        size                 = 100
        type                 = "gp2"
        volumes_per_instance = 1
      }
   
      # Volume 2
      ebs_config {
        size                 = 25
        type                 = "gp2"
        volumes_per_instance = 1
      }
    }
    target_on_demand_capacity = 1
  }
  ...
}
```

### Expected Behavior

EMR supports multiple EBS volumes on the fleet instances.

The provider documentation reads:

> Attributes for the EBS volumes attached to each EC2 instance in the master_instance_group and core_instance_group configuration blocks

where the plural *volumes* hints that it should be supported. In addition, the `ebs_config` block is of type set, and we can declare multiple such blocks. The provider should include in the corresponding EBS configuration the two or more volumes requested.

### Actual Behavior

If there are 2 or more `ebs_config` blocks, the plan does show the volumes:

```
              + ebs_config {
                  + size                 = 64
                  + type                 = "gp2"
                  + volumes_per_instance = 1
                }
              + ebs_config {
                  + size                 = 65
                  + type                 = "gp2"
                  + volumes_per_instance = 1
                }	
```

However, the resulting cluster has no EBS volumes configured for the corresponding fleet.

The reason is that in [`expandInstanceTypeConfigs`](https://github.com/hashicorp/terraform-provider-aws/blob/bc48c2178fff1c5b1b142481069e45fcb5870bd5/aws/resource_aws_emr_cluster.go#L2142), there is a weird `v.Len() == 1` condition:

```go
		if v, ok := configAttributes["ebs_config"].(*schema.Set); ok && v.Len() == 1 {
			config.EbsConfiguration = expandEbsConfiguration(v.List())
		}
```

If there are two or more `ebs_config` blocks, then the provider just silently omits any EBS configuration from the `RunJobFlow` API request used to create the cluster. This is especially odd as `expandEbsConfiguration` appears to be able to handle multiple EBS configuration blocks.

### Steps to Reproduce

- Deploy a cluster where one of the fleets' instance config has two EBS volumes
- Check resulting EMR cluster with `aws emr describe-cluster`, or observe API request with `TF_LOG=debug` during `apply`

cc @c4po

**Comment by peay** [comment]
I'll be happy to contribute a PR if someone confirms the diagnosis here, and that there's no particular reason to keep the `v.Len() == 1` condition.

**Comment by danielonthenet** [comment]
@peay I can confirm. I encountered the issue too.

The condition seems wrong.

Should be
```
		if v, ok := configAttributes["ebs_config"].(*schema.Set); ok && v.Len() >= 1 {
			config.EbsConfiguration = expandEbsConfiguration(v.List())
		}
```
