### ISSUE TITLE
updated Terraform but still crashed 

### ISSUE THREAD

**Issue by rumetix** [hashicorp/terraform-provider-aws#20392]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000
[crash.533240070.log](https://github.com/hashicorp/terraform-provider-aws/files/6913437/crash.533240070.log)

**Comment by breathingdust** [comment]
Hi @rumetix! This repository is for the Terraform AWS provider and the above crash log has no reference at all to the provider. It may be an issue in Terraform Core in which case a bug report would be better filled out here: https://github.com/hashicorp/terraform

I would encourage you to fill out the issue template when submitting issues, as a crash log with no context does not give maintainers enough information to reproduce and will normally be closed.
