### ISSUE TITLE
Add sybase_settings configuration block in aws_dms_endpoint

### ISSUE THREAD

**Issue by evairmarinho** [hashicorp/terraform-provider-aws#20400]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The resource aws_dms_endpoint doesn't have **sybase_settings** configuration block.

### New or Affected Resource(s)

aws_dms_endpoint

### Potential Terraform Configuration

```hcl
resource "aws_dms_endpoint" "my_endpoint" {
 ...
  sybase_settings = {
  secrets_manager_access_role_arn = "arn:aws:iam::123456789012:role/dms-secrets-manager-role"
  secrets_manager_secret_id = "my_secrets_manager_secret"
    
  ## To verify other arguments available, access https://docs.aws.amazon.com/cli/latest/reference/dms/create-endpoint.html
  }
...
}
```

### References

https://docs.aws.amazon.com/cli/latest/reference/dms/create-endpoint.html

**Comment by ewbankkit** [comment]
Similar: https://github.com/hashicorp/terraform-provider-aws/issues/20400.
