### ISSUE TITLE
aws_efs_file_system Unsupported attribute (value*)

### ISSUE THREAD

**Issue by azilber** [hashicorp/terraform-provider-aws#20402]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.52.0

### Affected Resource(s)

* aws_efs_file_system

### Terraform Configuration Files
outputs.tf contains:
```hcl
     "size_in_bytes" = aws_efs_file_system.php8devtest.value,
     "bytes_in_ia" = aws_efs_file_system.php8devtest.value_in_ia,
     "bytes_in_standard" = aws_efs_file_system.php8devtest.value_in_standard
```
     

### Debug Output
All 3 values give:
```
Error: Unsupported attribute
│
│   on outputs.tf line 9, in output "efs_php8devtest":
│    9:      "bytes_in_ia" = aws_efs_file_system.php8devtest.value_in_ia,
│
│ This object has no argument, nested block, or exported attribute named "value_in_ia".
```

### Expected Behavior
Value as per: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_file_system#value_in_ia

### Actual Behavior
Error: Unsupported attribute

### Steps to Reproduce
Create outputs.tf with all [Size in Bytes](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_file_system#size-in-bytes) values.

**Comment by ewbankkit** [comment]
@azilber Thanks for raising this issue.
`aws_efs_file_system.php8devtest.size_in_bytes.0.value_in_ia` should be what you need.

**Comment by azilber** [comment]
@ewbankkit bingo!
```
  "value" = "6144"
  "value_in_ia" = "0"
  "value_in_standard" = "6144"
```
That was the secret sauce! 🤩
