### ISSUE TITLE
CacheParameterGroupName is not a valid identifier

### ISSUE THREAD

**Issue by ethervoid** [hashicorp/terraform-provider-aws#20425]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_elasticache_cluster

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "aws_elasticache_cluster" "staging_memcache" {
  cluster_id                   = "staging-memcache"
  engine                       = "memcached"
  node_type                    = "cache.t2.micro"
  num_cache_nodes              = 2
  parameter_group_name         = "default.memcached1.6"
  subnet_group_name            = aws_elasticache_subnet_group.cache_subnet_group.name
  port                         = 11211
  preferred_availability_zones = ["us-east-1a", "us-east-1b"]
  security_group_ids           = [aws_security_group.memcache.id]
}
```

### Debug Output

https://gist.github.com/ethervoid/b51742f4787b9ef2b1521d26ef965cf4
https://gist.github.com/ethervoid/345c4ba5b962d2997b891122541107c4

### Expected Behavior

The update to the new version 1.6 should happen

### Actual Behavior

I'm getting the `CacheParameterGroupName is not a valid identifier` error

### Steps to Reproduce

1. Create elasticache Memcached cluster in version 1.5 using terraform
2. Change the `parameter_group_name` from `default.memcached1.5` to `default.memcached1.6`
3. `terraform plan`
4. `terraform appply`

### References

* #0000

**Comment by gdavison** [comment]
Hi, @ethervoid. I notice that the `engine_version` parameter is not set in the example code that you've included. Do you have it defined in your Terraform configuration?

I tried setting `parameter_group_name` to `default.memcached1.6` when the `engine_version` is `1.5.x`, and it gives the same error message:

> Error: Error updating ElastiCache cluster (tf-acc-test-49249074502282193), error: InvalidParameterValue: The parameter CacheParameterGroupName is not a valid identifier. Identifiers must begin with a letter; must contain only ASCII letters, digits, and hyphens; and must not end with a hyphen or contain two consecutive hyphens.

Unfortunately, this isn't a great error message from the AWS API.

If you want to update the Memcached version, update the value of `engine_version` to the latest 1.6 version, which is `1.6.6` right now. If you're using the default parameter groups, you don't need to specify them.

If that doesn't solve the problem that you're seeing, please open a new issue
