### ISSUE TITLE
terraform-provider-aws_v3.52.0_x5_plugin_crashed

### ISSUE THREAD

**Issue by yannicksiewe** [hashicorp/terraform-provider-aws#20438]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v1.0.2
```

### Affected Resource(s)
* aws_acm
* aws_eks
* aws_iam
* aws_kms
* aws_rds
* aws_efs
* aws_alb
* aws_s3
* aws_route53

### Terraform Configuration Files
```hcl
provider "aws" {
  region = var.aws_region
}
```

### Panic Output

![Screenshot 2021-08-04 at 15 32 13](https://user-images.githubusercontent.com/2368631/128189881-6baeaa99-cff9-4aa9-a15b-64060952abdc.png)

### Expected Behavior

* updated resources

### Actual Behavior

* in the screenshot above

### Steps to Reproduce

1. `terraform apply`
2. `edit tf files`
3. `terraform apply`

**Comment by ewbankkit** [comment]
Similar:

* #20131
* #20015
* #19807
* #19788
* #19740
* #19601

**Comment by justinretzolk** [comment]
Hi @yannicksiewe 👋 Terraform `v1.0.9` was released yesterday which [includes a fix](https://github.com/hashicorp/terraform/blob/v1.0.9/CHANGELOG.md#109-october-13-2021) that should correct this. Can you test again with this newer version to verify that you're no longer experience this issue?

**Comment by Bishop0948** [comment]
> Hi @yannicksiewe 👋 Terraform `v1.0.9` was released yesterday which [includes a fix](https://github.com/hashicorp/terraform/blob/v1.0.9/CHANGELOG.md#109-october-13-2021) that should correct this. Can you test again with this newer version to verify that you're no longer experience this issue?

Just tested,Terraform v1.1.2 still crash.

**Comment by justinretzolk** [comment]
Hey @Bishop0948 👋 Are you still experiencing this behavior, and if so, does the crash log look similar to the one posted in the original issue description?
