### ISSUE TITLE
Add support for the new RDS's Replicating automated backups to another AWS Region

### ISSUE THREAD

**Issue by shamil** [hashicorp/terraform-provider-aws#20439]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](hhttps://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReplicateBackups.html) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for the new RDS's [Replicating automated backups to another AWS Region](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReplicateBackups.html)

### New or Affected Resource(s)

```
aws_db_instance
```

### References

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReplicateBackups.html

**Comment by ericrichtert** [comment]
Is this the same as #16708 ?
