### ISSUE TITLE
password argument on aws_elasticache_user resource exposed in console

### ISSUE THREAD

**Issue by ramekin** [hashicorp/terraform-provider-aws#20430]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform version: 0.14.11 (Also occurs with version 1.0.3.)
provider version: 3.52.0

### Affected Resource(s)

* aws_elasticache_user

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.52"
    }
  }
  required_version = "~> 0.14.0"
}

provider "aws" {
  region  = "us-east-2"
  profile = "myprofile"
}

# from example in the docs
resource "aws_elasticache_user" "test" {
  user_id       = "testUserId"
  user_name     = "testUserName"
  access_string = "on ~app::* -@all +@read +@hash +@bitmap +@geo -setbit -bitfield -hset -hsetnx -hmset -hincrby -hincrbyfloat -hdel -bitop -geoadd -georadius -georadiusbymember"
  engine        = "REDIS"
  passwords     = ["password123456789"]
}
```

### Debug Output

```
$ terraform plan

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_elasticache_user.test will be created
  + resource "aws_elasticache_user" "test" {
      + access_string        = "on ~app::* -@all +@read +@hash +@bitmap +@geo -setbit -bitfield -hset -hsetnx -hmset -hincrby -hincrbyfloat -hdel -bitop -geoadd -georadius -georadiusbymember"
      + arn                  = (known after apply)
      + engine               = "REDIS"
      + id                   = (known after apply)
      + no_password_required = false
      + passwords            = [
          + "password123456789",
        ]
      + tags_all             = (known after apply)
      + user_id              = "testUserId"
      + user_name            = "testUserName"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

### Expected Behavior

The passwords argument should be redacted from the console output.

### Actual Behavior

Password is visible in console output.

### Steps to Reproduce

1. `terraform plan`

**Comment by ewbankkit** [comment]
The `passwords` attribute should be marked as [`Sensitive: true`](https://www.terraform.io/docs/extend/best-practices/sensitive-state.html#using-the-sensitive-flag).
