### ISSUE TITLE
aws_eks_addon resources needs a way to overwrite pre-existing configs

### ISSUE THREAD

**Issue by vchan2002** [hashicorp/terraform-provider-aws#20440]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When putting in an aws_eks_addon resource, the apply fails with the following error.

Apply failed with 2 conflicts: conflicts with "kubectl-client-side-apply" using apps/v1: - .spec.template.spec.containers[name="aws-node"].image - .spec.template.spec.initContainers[name="aws-vpc-cni-init"].image

Doing an apply a second time, seems to take care of it.

It seems that this is a known kubernetes thing because eks is uses the server-side apply feature.

https://docs.aws.amazon.com/eks/latest/userguide/add-ons-configuration.html#add-on-config-management-field-management

It seems that, if managing add ons using eksctl or the aws CLI, there's flags and options to do an --force option or a --resolve-conflict flag that takes care of this at the 1st run. 

My guess is that it has something to do with the ResolveConflicts function within the EKS API call.

### New or Affected Resource(s)

* aws_eks_addon

### Potential Terraform Configuration

```hcl
resource "aws_eks_addon" "vpc-cni" {
  cluster_name = "clustername"
  addon_version = "v1.9.0-eksbuild.1"
  addon_name   = "vpc-cni"
}
```

### References
[https://github.com/weaveworks/eksctl/issues/3414
](url)

[https://docs.aws.amazon.com/eks/latest/APIReference/API_UpdateAddon.html#AmazonEKS-UpdateAddon-request-resolveConflicts](url)

[https://docs.aws.amazon.com/cli/latest/reference/eks/create-addon.html](url)

[https://github.com/aws/aws-sdk-go/blob/v1.40.14/service/eks/api.go#L10634](url)

**Comment by ewbankkit** [comment]
@vchan2002 Thanks for raising this issue.
Did you try setting [`resolve_conflicts = "OVERWRITE"`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_addon#resolve_conflicts)?

**Comment by vchan2002** [comment]
@ewbankkit Thanks for responding.  I see it now in the documentation for eks_add_on.  For some reason I didn't see that as a param in the resource before.  My apologies.
