### ISSUE TITLE
aws_elasticsearch_domain encryption changes force replacement

### ISSUE THREAD

**Issue by Sovietaced** [hashicorp/terraform-provider-aws#20468]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.6
+ provider registry.terraform.io/hashicorp/aws v3.27.0
+ provider registry.terraform.io/hashicorp/vault v2.18.0

Your version of Terraform is out of date! The latest version
is 1.0.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

aws_elasticsearch_domain

### Terraform Configuration Files

original tf
```tf
resource "aws_elasticsearch_domain" "example" {
  domain_name           = "example"
  elasticsearch_version = "7.9"

  cluster_config {
    instance_type = "r4.large.elasticsearch"
  }
}
```

updated tf
```tf
resource "aws_elasticsearch_domain" "example" {
  domain_name           = "example"
  elasticsearch_version = "7.9"

  cluster_config {
    instance_type = "r4.large.elasticsearch"
  }

  encrypt_at_rest {
    enabled = true
  }
}

```
### Expected Behavior

Change should happen in place. Changes should not force replacement and completely recreate cluster. 

### Actual Behavior

Changes forces replacement.

```tf
      ~ encrypt_at_rest {
          ~ enabled    = false -> true # forces replacement
          + kms_key_id = (known after apply)
        }
        
      ~ node_to_node_encryption {
          ~ enabled = false -> true # forces replacement
        }
        

```

### Steps to Reproduce

1. `terraform apply`

**Comment by ewbankkit** [comment]
@Sovietaced Thanks for raising this issue.
It has already been noticed in #17330. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by Sovietaced** [comment]
> @Sovietaced Thanks for raising this issue.
> It has already been noticed in #17330. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
> Please add any additional comments there.

Thanks for linking that. I wasn't able to find that issue in any of my googling :)
