### ISSUE TITLE
tags cause data+resource items to incorrectly trigger json changes to be updated in-place

### ISSUE THREAD

**Issue by olenm** [hashicorp/terraform-provider-aws#20475]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.15.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.52.0
```

### Affected Resource(s)

tested so far:
- aws_iam_policy_document
- aws_iam_policy

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-east-2"

  default_tags {
    tags = {
      tf-test = "wee"
      region  = "us-east-2"
    }
  }
}



locals {
  some_tags = {
    "tf-test" = "wee2"
    "moar-test" = "woo"
    #"moar-test-2" = "wow"
  }
}



data "aws_iam_policy_document" "rsrc" {
  statement {
    sid = "s3ListBucket"
    effect = "Allow"
    actions = [
      "s3:ListBucket",
    ]
    resources = [ aws_s3_bucket.rsrc.arn ]
  }
}



resource "aws_iam_policy" "rsrc" {
  name = "your-favorite-name-formatting-here"
  description = "your-favorite-name-formatting-here"
  policy = data.aws_iam_policy_document.rsrc.json
}



resource "aws_s3_bucket" "rsrc" {
  bucket = "your-favorite-name-formatting-here"
  acl    = "private"
  tags = local.some_tags
}
```

### Expected Behavior

- After applying the first time, adding more tags should not cause the json output to change of the data object, it should not cause the `resource "aws_iam_policy"` to be `be updated in-place`

### Actual Behavior

- both the data and resource of the iam-policy `will be updated in-place` (the actual json) instead of being ignored when tags are modified
- I have noticed that when not using a direct tf-target to the s3-bucket-item within the data iam-policy-document, changing the tags of the s3 bucket does not cause the data-object to be updated in-place.

```
Terraform will perform the following actions:

  # data.aws_iam_policy_document.rsrc will be read during apply
  # (config refers to values not yet known)
 <= data "aws_iam_policy_document" "rsrc"  {
      ~ id      = "1234567890" -> (known after apply)
      ~ json    = jsonencode(
            {
              - Statement = [
                  - {
                      - Action   = "s3:ListBucket"
                      - Effect   = "Allow"
                      - Resource = "arn:aws:s3:::your-favorite-name-formatting-here"
                      - Sid      = "s3ListBucket"
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
      - version = "2012-10-17" -> null

      ~ statement {
          - not_actions   = [] -> null
          - not_resources = [] -> null
            # (4 unchanged attributes hidden)
        }
    }

  # aws_iam_policy.rsrc will be updated in-place
  ~ resource "aws_iam_policy" "rsrc" {
        id          = "arn:aws:iam::123456789012:policy/your-favorite-name-formatting-here"
        name        = "your-favorite-name-formatting-here"
      ~ policy      = jsonencode(
            {
              - Statement = [
                  - {
                      - Action   = "s3:ListBucket"
                      - Effect   = "Allow"
                      - Resource = "arn:aws:s3:::your-favorite-name-formatting-here"
                      - Sid      = "s3ListBucket"
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
        tags        = {}
        # (5 unchanged attributes hidden)
    }

  # aws_s3_bucket.rsrc will be updated in-place
  ~ resource "aws_s3_bucket" "rsrc" {
        id                          = "your-favorite-name-formatting-here"
      ~ tags                        = {
          + "moar-test-2" = "wow"
            # (2 unchanged elements hidden)
        }
      ~ tags_all                    = {
          + "moar-test-2" = "wow"
            # (3 unchanged elements hidden)
        }
        # (9 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform apply`
2. add a new tag to the list
2. `terraform apply`

**Comment by devopsrick** [comment]
Yeah, this has lead to some very anxious applies for us!  Having no idea what it thinks it is doing to an IAM policy just because a referenced s3 bucket resource has tag updates is quite annoying.

**Comment by michaelPotter** [comment]
I suspect this is caused by Terraform's dependency resolution behavior unfortunately. Not the AWS provider :(

Here is a quote from the Terraform docs (rearranged slightly for clarity):
> Data Resource Dependencies
> ...
> In order to ensure that data sources are accessing the most up to date information possible in a wide variety of use cases, arguments directly referencing managed resources are treated the same as if the resource was listed in depends_on. [Setting the depends_on meta-argument within data blocks defers reading of the data source until after all changes to the dependencies have been applied.] This behavior can be avoided when desired by indirectly referencing the managed resource values through a local value.

https://www.terraform.io/docs/language/data-sources/index.html#data-resource-dependencies

**Comment by olenm** [comment]
@michaelPotter interesting, thanks, though creating a local with the value of `data.aws_iam_policy_document.rsrc.json` - then using that local in place of the `policy = ` - the results are the same - mega text spam. 
Really I do think there is another "bug" where the diff is not expanding properly; in the case above there is static-text that should displayed in the diff, instead of "known after apply". The `known after apply` should only be where said explicit resources are utilized within that TF cannot dereference. I did change the s3-acl to `log-delivery-write` and it too, came up with the same problem

attempted workaround; maybe I'm doing it wrong?
``` HCL
locals { 
  jsonblob = data.aws_iam_policy_document.rsrc.json
}

resource "aws_iam_policy" "rsrc" {
  name = "your-favorite-name-formatting-here"
  description = "your-favorite-name-formatting-here"
  #policy = data.aws_iam_policy_document.rsrc.json
  jsonblob = local.jsonblob
}
```

**Comment by michaelPotter** [comment]
TBH I haven't tried the workaround yet, but from my reading of it I think you'd want the local reference to go the other way: the resource values that your aws_iam_policy_document reference get passed through a locals var

For example:
```terraform
locals {
  aws_dynamodb_table-foo-arn = aws_dynamodb_table.foo.arn
}

data "aws_iam_policy_document" "dynamodb-access" {
  // Allow all access, but only to this one table
  statement {
    effect    = "Allow"
    actions   = ["dynamodb:*"]
    resources = [local.aws_dynamodb_table-foo-arn]
  }
}
```

This way the data block isn't directly referencing the managed resource and triggering the "depends_on/read during apply" behavior.

**Comment by olenm** [comment]
yes this is working with suggested change - thanks @michaelPotter !
