### ISSUE TITLE
aws_elasticsearch_domain resource is created without tags

### ISSUE THREAD

**Issue by chaddewitt** [hashicorp/terraform-provider-aws#20498]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.2
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.53.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

* aws_elasticsearch_domain

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = ">= 3.53.0"
    }
    random = {
      source = "hashicorp/random"
      version = ">= 3.1.0"
    }
  }
  backend "s3" {}
}

provider "aws" {
  region = "us-east-1"
  //noinspection HCLUnknownBlockType
  default_tags {
    tags = {
      Billing = "example company"
      Domain  = "example-8-9-2021"
      User    = "example"
    }
  }
}



resource "aws_elasticsearch_domain" "single" {
  count                 = 1
  domain_name           = "example-8-9-2021"
  elasticsearch_version = "7.4"
  cluster_config {
    instance_count           = 1
    instance_type            = "m5.large.elasticsearch"
    dedicated_master_enabled = false
  }
  ebs_options {
    ebs_enabled = true
    volume_type = "gp2"
    volume_size = 40
  }
  snapshot_options {
    automated_snapshot_start_hour = 0
  }
  tags = {
    Billing = "example company"
    Domain  = "example-8-9-2021"
    User    = "example"
    Name    = "example-8-9-2021 Elasticsearch"
  }
}
```

### Debug Output

https://gist.github.com/chaddewitt/e163a6d7bbe16c0743a7916e4b9a5b24

### Panic Output

N/A
### Expected Behavior

Tags were created for the Elasticsearch domain as defined in the main.tf file 
### Actual Behavior

The newly created Elasticsearch domain resource had no tags. 
### Steps to Reproduce

1. `terraform apply -auto-approve`

### Important Factoids

N/A
### References

N/A

**Comment by gdavison** [comment]
Hi @chaddewitt, thanks for reporting this. At first glance, there may be a problem because the three tags in `default_tags` are repeated in the resource, though that would be a bug on our part.

The Gist you included doesn't seem to exist any more, or I don't have access to it.

**Comment by chaddewitt** [comment]
Hi @gdavison, thank you for the follow up. Here is a Gist that does exist 

https://gist.github.com/chaddewitt/e163a6d7bbe16c0743a7916e4b9a5b24

I've also edited initial link to be correct.
