### ISSUE TITLE
aws_cloudwatch_event_connection Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by luisamador** [hashicorp/terraform-provider-aws#20492]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.31
Provider AWS v3.53.0

### Affected Resource(s)

aws_cloudwatch_event_connection

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_cloudwatch_event_connection" "this" {
  name               = "blah"
  description        = "blah blah"
  authorization_type = "BASIC"

  auth_parameters {
    basic {
      username = ""
      password = ""
    }
  }
}
```

### Panic Output

```Error: rpc error: code = Unavailable desc = transport is closing```

### Expected Behavior

If an empty value for the username and password properties is set when authorization_type = "BASIC", it shouldn't error. I should just said that username can't be empty.

### Actual Behavior

Terraform throws an error: Error: rpc error: code = Unavailable desc = transport is closing

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ewbankkit** [comment]
@luisamador Thanks for raising this issue.
This type of error is usually the result of a crash in the provider - Does the output show a stack trace or is there a `crash.log` file produced?
