### ISSUE TITLE
aws_autoscaling_group tags requires set of map of string

### ISSUE THREAD

**Issue by mathisve** [hashicorp/terraform-provider-aws#20508]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.53.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s)

* aws_autoscaling_group

### Terraform Configuration Files

```hcl
provider "aws" {
    region = "eu-central-1"
}

variable "tags" {
    type = map(string)
    default = {
      Environment = "Dev"
    }   
}

resource "aws_launch_template" "test" {
    name = "test-lt"
    image_id = "ami-0453cb7b5f2b7fca2"
    instance_type = "t3.micro"

    tags = var.tags

    block_device_mappings {
        device_name = "/dev/sda1"

        ebs {
            volume_size = 20
        }
    }
}

resource "aws_vpc" "test" {
    cidr_block = "10.0.0.0/16"

    tags = var.tags
}

resource "aws_subnet" "test" {
    vpc_id = aws_vpc.test.id
    cidr_block = "10.0.1.0/24"

    tags = var.tags
}

resource "aws_autoscaling_group" "test" {
    name = "test-ag"
    min_size = 1
    max_size = 2
    vpc_zone_identifier = [aws_subnet.test.id]

    launch_template {
      id = aws_launch_template.test.id
      version = "$Latest"
    }

    tags = var.tags
}
```

### Debug Output
```
│ Error: Incorrect attribute value type
│ 
│   on quick-tracks-ecs-cluster.tf line 112, in resource "aws_autoscaling_group" "this":
│  112:   tags = var.tags
│     ├────────────────
│     │ var.tags is a map of string, known only after apply
│ 
│ Inappropriate value for attribute "tags": set of map of string required.
╵
```
### Expected Behavior
In all other Terraform modules (to my knowledge), the `tags` attribute is a map of string `map(string)`, so as per convention I expected this to be the case here too.

### Actual Behavior
It required me to use a set of map of string `[map(string)]`, which isn't an issue on it's own as I can easily wrap the map with brackets. But it just struck me as odd that this is an outlier among AWS Modules where standardization is the norm.

### Steps to Reproduce

1. `terraform init`
2. `terraform validate`

**Comment by ewbankkit** [comment]
@mathisve Thanks for raising this issue.
The behavior you notice is because of the (unfortunate) fact that AutoScaling service tagging APIs require more than the usual `Key` and `Values` fields (which we can model as a Terraform map), with an additional `PropagateAtLaunch` field.
This means that AutoScaling tags are modeled as a set of objects (and explains why `default_tags` are not yet supported).
