### ISSUE TITLE
Include support for availability-zone-relocation parameter in aws_redshift_cluster to handle new AWS feature that supports cluster relocation across AZs

### ISSUE THREAD

**Issue by IndhuShanmugam** [hashicorp/terraform-provider-aws#20507]
Hi Team, 

AWS introduced a new feature a few months ago which enables Redshift relocation across AZs:
https://docs.aws.amazon.com/redshift/latest/mgmt/managing-cluster-recovery.html

So with this new feature, we can now enable cluster relocation using this CLI command:
aws redshift modify-cluster --cluster-identifier mycluster --availability-zone-relocation

But this feature is not supported by Terraform in 'aws_redshift_cluster' resource or any other related resources. Please implement this new feature so that cluster relocation can be enabled through Terraform and we need not rely only on AWS CLI.

Thanks & Regards,
Indhu S

**Comment by ewbankkit** [comment]
@IndhuShanmugam Thanks for raising this issue.
It has already been noticed in #19098. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
