### ISSUE TITLE
AWS STS Request Post-Sign Timeout

### ISSUE THREAD

**Issue by hlandim** [hashicorp/terraform-provider-aws#20517]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* All

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.53.0"
    }
  }
}

provider "aws" {
  region      = "eu-west-2"
  max_retries = 1
}
```

### Debug Output

[Gist full log](https://gist.github.com/hlandim/d97a8700891e70e307090f40638369d1) (I have removed my credentials from the logs)

```hcl

│ Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: RequestError: send request failed
│ caused by: Post "https://sts.eu-west-2.amazonaws.com/": dial tcp: lookup sts.eu-west-2.amazonaws.com on 192.168.1.254:53: read udp 192.168.1.28:58470->192.168.1.254:53: i/o timeout
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on providers.tf line 1, in provider "aws":
│    1: provider "aws" {
│

```

### Expected Behavior

A plan.

### Actual Behavior

Timeout

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Important Factoids

I haven't changed any configuration on DNS settings.
It was working one day and not working any more on the next day.

### References

* https://github.com/hashicorp/terraform/issues/10354

**Comment by hlandim** [comment]
I've just tested it in another machine using the same tf files, same network ant it worked as expected.
Probably it is some configuration issue on my Mac. 🤔

**Comment by gdavison** [comment]
Hi @hlandim. This part of the error message

> lookup sts.eu-west-2.amazonaws.com on 192.168.1.254:53: read udp 192.168.1.28:58470->192.168.1.254:53: i/o timeout

looks like a DNS timeout. Hopefully that will help you track down the issue.
