### ISSUE TITLE
aws_security_group does not create a security group

### ISSUE THREAD

**Issue by K2Webby** [hashicorp/terraform-provider-aws#20537]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Either the [docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group) are wrong or the resource is broken. I have used this in the past with no issues.
 
### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.53.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Affected Resource(s)

```
Terraform v1.0.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.53.0
```

### Terraform Configuration Files

```hcl
resource "aws_security_group" "allow_tls" {
  name        = "allow_tls"
  description = "Allow TLS inbound traffic"
  vpc_id      = aws_vpc.main.id

  ingress = [
    {
      description      = "TLS from VPC"
      from_port        = 443
      to_port          = 443
      protocol         = "tcp"
      cidr_blocks      = [aws_vpc.main.cidr_block]
      ipv6_cidr_blocks = [aws_vpc.main.ipv6_cidr_block]
    }
  ]

  egress = [
    {
      from_port        = 0
      to_port          = 0
      protocol         = "-1"
      cidr_blocks      = ["0.0.0.0/0"]
      ipv6_cidr_blocks = ["::/0"]
    }
  ]

  tags = {
    Name = "allow_tls"
  }
}
```

### Expected Behavior

- It should create the SG with the rules specified

### Actual Behavior

```
 Error: Incorrect attribute value type
│ 
│   on infra_sec_groups.tf line 141, in resource "aws_security_group" "allow_tls":
│  141:   ingress = [
│  142:     {
│  143:       description      = "TLS from VPC"
│  144:       from_port        = 443
│  145:       to_port          = 443
│  146:       protocol         = "tcp"
│  147:       cidr_blocks      = ["0.0.0.0/0"]
│  148:     }
│  149:   ]
│ 
│ Inappropriate value for attribute "ingress": element 0: attributes "ipv6_cidr_blocks", "prefix_list_ids", "security_groups", and "self" are required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on infra_sec_groups.tf line 151, in resource "aws_security_group" "allow_tls":
│  151:   egress = [
│  152:     {
│  153:       from_port        = 0
│  154:       to_port          = 0
│  155:       protocol         = "-1"
│  156:       cidr_blocks      = ["0.0.0.0/0"]
│  157:       ipv6_cidr_blocks = ["::/0"]
│  158:     }
│  159:   ]
│ 
│ Inappropriate value for attribute "egress": element 0: attributes "description", "prefix_list_ids", "security_groups", and "self" are required.
```

### Steps to Reproduce

1. [Use the example from the docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group) and it does not work.

2. `terraform apply`

**Comment by ewbankkit** [comment]
Relates: #20428.

**Comment by ewbankkit** [comment]
@K2Webby Thanks for raising this issue.
It has already been noticed in #20484. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
