### ISSUE TITLE
aws_wafv2_web_acl does not support all available text_transformation types

### ISSUE THREAD

**Issue by kiwimato** [hashicorp/terraform-provider-aws#20545]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It seems `aws_wafv2_web_acl` `text_transformation` does not support all types from [Amazon docs](https://docs.aws.amazon.com/waf/latest/APIReference/API_TextTransformation.html). Terraform docs also only specify some of the possible values, [not all](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_rule_group#text-transformation)

### New or Affected Resource(s)

* aws_wafv2_web_acl 

### Error

```hcl
 Error: expected rule.1.statement.0.sqli_match_statement.0.text_transformation.2.type to be one of [CMD_LINE COMPRESS_WHITE_SPACE HTML_ENTITY_DECODE LOWERCASE NONE URL_DECODE], got SQL_HEX_DECODE
│ 
│   with module.wafv2.aws_wafv2_web_acl.default[0],
│   on .terraform/modules/wafv2/rules.tf line 85, in resource "aws_wafv2_web_acl" "default":
│   85: resource "aws_wafv2_web_acl" "default" {
│ 
```

### Versions:
```
$ terraform -v
Terraform v1.0.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.53.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```
### References

* #0000

**Comment by brunhil** [comment]
Looks like there is no need for an AWS pkg upgrade, I'll submit a PR for this shortly!
