### ISSUE TITLE
resource/aws_elasticsearch_domain: Now supports tagging on creation

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#20544]
### Description

`aws_elasticsearch_domain` currently adds tags in a separate API call during creation. The `elasticsearch.CreateElasticsearchDomainInput` struct has a `TagList` field to allow a single call to the API.

### Affected Resource

* aws_elasticsearch_domain

### References

* #20498 is about a tagging issue with `aws_elasticsearch_domain`

**Comment by brunhil** [comment]
Looks like a fun one to tackle @gdavison , mind if I take a peek?

**Comment by DrFaust92** [comment]
https://github.com/hashicorp/terraform-provider-aws/pull/18082
