### ISSUE TITLE
Update aws_ssoadmin_account_assignment to output IAM roles created in background by AWS SSO

### ISSUE THREAD

**Issue by mattoneillphx** [hashicorp/terraform-provider-aws#20552]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello!

I am using AWS SSO to integrate with Okta to have one source of truth for users/groups and permissions.

As such, I create multiple `aws_ssoadmin_account_assignment` resources to assign permission sets to accounts.

In the background, AWS SSO creates an IAM role in each account for each one of these resources.

I would like to add an output that houses each of those IAM role ARNs for use in the rest of my terraform codebase, however it seems that `aws_ssoadmin_account_assignment` does not return the IAM role ARN created by AWS SSO.

Is it possible to add this? 

Thanks!

### New or Affected Resource(s)

* aws_ssoadmin_account_assignment

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://www.powerupcloud.com/aws-eks-authentication-and-authorization-using-aws-single-signon/
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssoadmin_account_assignment

**Comment by anGie44** [comment]
Hi @mattoneillphx 👋  Just noting that fetching the IAM role ARNS could potentially be solved with https://github.com/hashicorp/terraform-provider-aws/pull/18585 since I don't believe the SSO API returns that info after Account creation.

**Comment by mattoneillphx** [comment]
@anGie44 Thanks so much, that is exactly what I'm looking for!

Any ideas on when it may get released?

**Comment by anGie44** [comment]
I'm hoping to get the feature in by this week's release of `v3.55.0`, likely this Thursday @mattoneillphx 😃

**Comment by mattoneillphx** [comment]
@anGie44 Awesome work, if I could buy you a beer I would! 🎈

**Comment by anGie44** [comment]
Hi @mattoneillphx! I'm going to close out this issue as it should be resolved with the upcoming provider release. Reach out if you have any questions 😃

**Comment by mattoneillphx** [comment]
@anGie44 I guess I still feel this is behaviour that should happen - the PR you merged is a workaround (although im very grateful for it!)

Why wouldn't this resource give the caller back the roles it created?

I understand this would need to be implemented by AWS though as the API call doesn't return the IAM role arn.

**Comment by anGie44** [comment]
Unfortunately the AWS SSO API only exposes these actions to us https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_Operations.html , and those specific to `AccountAssignment` (Create/List/Delete) don't share the roles created in the response objects, rather the `AccountAssignment` returned only contains a couple attributes as seen here: https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_AccountAssignment.html

So to support having those IAM roles as part of the SSO AccountAssignment resource, it would have to be the same implementation we now have in `aws_iam_roles` which isn't a common practice to have 1 resource call out to more than one AWS service. With that said though, if the upstream SSO API supports returning these IAM roles created behind the scenes in the future, this feature could then be added to the terraform resource 👍
