### ISSUE TITLE
r/aws_storagegateway_smb_file_share: Acceptance tests failing - 'InvalidGatewayRequestException: The specified gateway is out of date'

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#20557]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

All the `aws_storagegateway_smb_file_share` resource acceptance tests are currently failing with errors similar to

```
% make testacc TESTARGS='-run=TestAccAWSStorageGatewaySmbFileShare_Authentication_GuestAccess'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSStorageGatewaySmbFileShare_Authentication_GuestAccess -timeout 180m
=== RUN   TestAccAWSStorageGatewaySmbFileShare_Authentication_GuestAccess
=== PAUSE TestAccAWSStorageGatewaySmbFileShare_Authentication_GuestAccess
=== CONT  TestAccAWSStorageGatewaySmbFileShare_Authentication_GuestAccess
    resource_aws_storagegateway_smb_file_share_test.go:74: Step 1/2 error: Error running apply: exit status 1
        
        Error: error creating Storage Gateway SMB File Share: InvalidGatewayRequestException: The specified gateway is out of date.
        {
          RespMetadata: {
            StatusCode: 400,
            RequestID: "98217e78-7847-4bbd-a3c1-828e9295983a"
          },
          Error_: {
            ErrorCode: "OutdatedGateway"
          },
          Message_: "The specified gateway is out of date."
        }
        
          with aws_storagegateway_smb_file_share.test,
          on terraform_plugin_test.tf line 154, in resource "aws_storagegateway_smb_file_share" "test":
         154: resource "aws_storagegateway_smb_file_share" "test" {
        
--- FAIL: TestAccAWSStorageGatewaySmbFileShare_Authentication_GuestAccess (276.71s)
FAIL
FAIL    github.com/terraform-providers/terraform-provider-aws/aws       280.056s
FAIL
make: *** [testacc] Error 1
```

**Comment by ewbankkit** [comment]
This is because the StorageGateway is being created with the `/aws/service/storagegateway/ami/FILE_S3/latest` AMI, not `/aws/service/storagegateway/ami/FILE_FSX_SMB/latest`.

**Comment by ewbankkit** [comment]
There's nothing that stands out here, especially as all the other file gateway tests are passing.
I'll raise an AWS Support issue.

**Comment by mickey-hariparsad** [comment]
I am experiencing the same failure when creating a fgw with guest access. Originally it said the plan was malformed in the trace. Adding in all options stopped the plan malformed error in the trace logs. Although the plan malformed error is removed, the gateway outdate error remains the same. 


2021-08-16T13:46:34.228+0200 [INFO]  provider.terraform-provider-aws_v3.53.0_x5.exe: 2021/08/16 13:46:34 [DEBUG] [aws-sdk-go] DEBUG: Response storagegateway/CreateSMBFileShare Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 133
Content-Type: application/x-amz-json-1.1
Date: Mon, 16 Aug 2021 11:46:34 GMT

**Comment by ewbankkit** [comment]
> Further, I have also noticed that you have performed a CreateSMBFileShare on “2021-08-13T19:34:28 UTC”. In general, you will be getting an ‘OutdatedGateway’ when you are trying to include some new parameters in your API which is supported only by the latest software version. Unfortunately, since you have already deleted the gateway, I don’t have visibility over your Gateway’s last updated. 
>
> Having said that, I have checked your ‘CreateSMBFileShare’ API call and I could see that you are making the calls from Terraform and it has included the parameter ‘oplocksEnabled’ which is one of the new features available only in our latest software update. Which might be the reason why you have received ‘OutdatedGateway’ error when you made that API call. You can refer the API-call from this link:

Related: #20234.
