### ISSUE TITLE
Amazon EBS Multi-Attach for io2 volumes

### ISSUE THREAD

**Issue by michaelstepner** [hashicorp/terraform-provider-aws#20573]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> You can now enable Provisioned IOPS SSD (io2) volumes for Amazon EBS Multi-Attach.
> You can enable Multi-Attach for io1 and io2 volumes during creation.
> You can also enable Multi-Attach for io2 volumes after they have been created.

### New or Affected Resource(s)

* [`aws_ebs_volume`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ebs_volume)

### Potential Terraform Configuration

```hcl
resource "aws_ebs_volume" "example" {
  type = "io2"

  multi_attach_enabled = true
}
```

### References

* Previously proposed in #16847 by @ewbankkit 
    * [Closed on Dec 22, 2020](https://github.com/hashicorp/terraform-provider-aws/issues/16847#issuecomment-749813548) with note "Currently multi-attach on io2 is available in us-east-2, eu-central-1, and ap-south-1 regions. This is probably not worth tackling until there is wider region support."
    * That condition has now been met: "Multi-Attach for io2 and io2 Block Express volumes is available in all Regions that support those volumes types volumes." — [AWS Documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volumes-multi.html)

**Comment by ewbankkit** [comment]
@michaelstepner Thanks for raising this issue.
It has already been noticed in #19751. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
