### ISSUE TITLE
aws_launch_template network_interfaces block missing source_dest_check

### ISSUE THREAD

**Issue by robgil-okta** [hashicorp/terraform-provider-aws#20596]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_launch_template

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "aws_launch_template" "pan_a" {
  name     = "pan"
  image_id = "ami-d3adb33f"
  instance_type = "c5.xlarge"
  block_device_mappings {
    device_name = "/dev/sda1"

    ebs {
      volume_size = 120
      volume_type = "gp2"
    }
  }
  network_interfaces {
    # Management - eth0
    device_index = 0
    subnet_id    = "subnet-d3adb33f"
    #security_groups = ""
    description = "PAN Management"
  }

  network_interfaces {
    # Private - eth1
    device_index = 1
    subnet_id    = "subnet-d3adb33f
    #security_groups = ""
    description = "PAN Private"
    source_dest_check = false
  }

  network_interfaces {
    # Public - eth2
    device_index = 2
    subnet_id    = "subnet-d3adb33f"
    #security_groups = ""
    description = "PAN Public"
    source_dest_check = false
  }
  monitoring {
    enabled = true
  }
}

```

### Debug Output
```
Error: Unsupported argument

  on ../../../../../terraform-modules/modules/aws_pan_filter/main.tf line 46, in resource "aws_launch_template" "pan_a":
  46:     source_dest_check = false
```

### Expected Behavior
`source_dest_check` should exist in the `aws_launch_template` just as it does in the `aws_network_interface`.

### Actual Behavior
Fails

### Steps to Reproduce
Add `source_dest_check` to the `network_interfaces` block. 

1. `terraform apply`

### References

* #0000

# Use Case
The general use case is to begin using autoscaling groups behind gateway load balancers. For example, load balancing Palo Alto Firewalls.

**Comment by markmartirosian** [comment]
One more suggestion for IPv4 Prefixes and IPv6 Prefixes support for `aws_launch_template` resource's `network_interfaces` block. It is listed in the [user guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-templates.html#create-launch-template) and available in the console.
