### ISSUE TITLE
Optional arguments being requierd 

### ISSUE THREAD

**Issue by adamdaniel2993** [hashicorp/terraform-provider-aws#20599]
Hello I'm trying to create a security group and is giving me this error, even with the example that is in the terraform web page, the weird thing here is that those arguments are optional not requierd as terraform is saying 

` Inappropriate value for attribute "ingress": element 0: attributes "ipv6_cidr_blocks", "prefix_list_ids", "security_groups", and "self" are required.`

This is my terraform code

`module "vpc"{
  source = "./modules/vpc"

}

resource "aws_security_group" "rds-sg" {
  name        = "rds-sg"
  description = "allow trafic"
  vpc_id      = module.vpc.vpc_id

  ingress = [
    {
      description      = "ingress for rds"
      from_port        = 5432
      to_port          = 5432
      protocol         = "tcp"
      cidr_blocks      = ["my-ip/32"]
    }
  ]

  egress = [
    {
      from_port        = 0
      to_port          = 0
      protocol         = "-1"
      cidr_blocks      = ["0.0.0.0/0"]
    }
  ]

  tags = {
    Name = "allow ips to connect to the rds"
  }
}
`

**Comment by ewbankkit** [comment]
@adamdaniel2993 Thanks for raising this issue.
It has already been noticed in #20484. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
