### ISSUE TITLE
Amazon EMR Studio

### ISSUE THREAD

**Issue by GaboFDC** [hashicorp/terraform-provider-aws#20597]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow terraform to create and manage emr studio resources.

### New or Affected Resource(s)

* `aws_emr_studio`

### Potential Terraform Configuration

```hcl
resource "aws_emr_studio" "example" {
  name = "example-studio"
  auth_mode = "SSO"
  vpc_id = <example-vpc-id>
  subnet_ids = ["<subnet-id-1>", "<subnet-id-2>"]
  service_role = <example-studio-service-role-name>
  user-role = <example-studio-user-role-name>
  workspace-security-group-id = <example-workspace-sg-id>
  engine-security-group-id = <example-engine-sg-id>
  default-s3-location = <example-s3-location>
}
```

### References

* https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-studio.html

**Comment by ewbankkit** [comment]
@demolitionmode Please open separate issues for each of the EMR Studio resource.
Thanks.
