### ISSUE TITLE
aws_lambda_permission is missing after aws_lambda_function is replaced

### ISSUE THREAD

**Issue by davidkam** [hashicorp/terraform-provider-aws#20598]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.13.6

- hashicorp/null v3.1.0
- hashicorp/archive v2.2.0
- hashicorp/aws v3.54.0

### Affected Resource(s)

* aws_lambda_permission

### Terraform Configuration Files

We updated a lambda from a zip type:
```hcl
resource  "aws_lambda_function"  "my_lambda" {
  function_name = "my-lambda-handler"
  handler = "main.handler"
  role = aws_iam_role.meta_data_lambda_role.arn
  runtime = "python3.7"
  filename = data.archive_file.lambda_dummy.output_path
  timeout = 900
  memory_size = 2048
}

resource "aws_lambda_permission" my_lambda_lambda_permission" {
  statement_id  = "AllowExecutionFromAPIGateway"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.my_lambda.function_name
  principal     = "apigateway.amazonaws.com"
  source_arn = "${aws_api_gateway_rest_api.meta_data_manager_api.execution_arn}/*/*/*"
}
```
To a container type:
```hcl
resource "aws_lambda_function" "my_lambda" {
  function_name = "my-lambda-handler"
  role          = aws_iam_role.meta_data_lambda_role.arn
  image_uri     = "${aws_ecr_repository.repo.repository_url}@${data.aws_ecr_image.lambda_image.id}"
  package_type  = "Image"
  timeout       = 900
  memory_size   = 2048
}

resource "aws_lambda_permission" my_lambda_lambda_permission" {
  statement_id  = "AllowExecutionFromAPIGateway"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.my_lambda.function_name
  principal     = "apigateway.amazonaws.com"
  source_arn = "${aws_api_gateway_rest_api.meta_data_manager_api.execution_arn}/*/*/*"
}
```

Which causes the `aws_lambda_function` resource to be replaced.

### Expected Behavior
The `aws_lambda_permission` should be attached to the replaced `aws_lambda_function` resource.

### Actual Behavior
There is no `aws_lambda_permission` attached to the `aws_lambda_function` resource.  

### Steps to Reproduce

1. run `terraform apply` with the first block (`aws_lambda_function` using the default package_type of "Zip") to create the resources
2. run `terrraform apply` with the second block (`aws_lambda_function` using a package_type of "Image") to update the resources

### Important Factoids

If you run `terraform plan` before step 2 above, it doesn't show any changes with `aws_lambda_permission` and shows that `aws_lambda_function` will need to be replaced.  If you run `terraform plan` after step 2, it shows that the `aws_lambda_permission` needs to be created, basically saying that `apply` needs to be run twice for this to fully work.

I tried adding a `depends_on` to the `aws_lambda_permission`:
```hcl
resource "aws_lambda_permission" my_lambda_lambda_permission" {
  statement_id  = "AllowExecutionFromAPIGateway"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.my_lambda.function_name
  principal     = "apigateway.amazonaws.com"
  source_arn = "${aws_api_gateway_rest_api.meta_data_manager_api.execution_arn}/*/*/*"
  depends_on = [
    aws_lambda_function.my_lambda
  ]
}
```
But that has no effect either.

### References

Seems similar to #12917

**Comment by ohookins** [comment]
I've also been running into this recently when replacing a bunch of zip-provisioned lambdas with image-provisioned lambdas (which may or may not be relevant). Also end up having to run Terraform twice which is annoying at best - initially I thought my lambdas were all broken and spent a day rolling back and forth between versions.

**Comment by jeffwnelson** [comment]
_Updating here as this issue still occurs with Terraform 1.3.9._
The workaround we use today relies on the Lifecycle option "replace_triggered_by". I believe this was introduced a few months after the above comment was made around May 2022. 

For us, on the `aws_lambda_permission` resource, we can include the following:
```
resource "aws_lambda_permission" "example" {
  # ...
  lifecycle {
    replace_triggered_by = [
      aws_lambda_function.lambda
    ]
  }
}  
```

Essentially, Terraform will trigger a replacement on the `aws_lambda_permission` resource when our `aws_lambda_function` is updated. 

Another approach is to have Terraform replace a resource every time a plan is applied.
Something like this could work:
``` 
resource "null_resource" "always_run" {
  triggers = {
    timestamp = "${timestamp()}"
  }
}

resource "aws_lambda_permission" "example" {
  # ...
  lifecycle {
    replace_triggered_by = [
      null_resource.always_run
    ]
  }
}
```

**Comment by jar-b** [comment]
To re-apply the Lambda permissions on function changes you can either include the `qualifier` argument and set it to the lambda functions `version` attribute (this forces a re-creation every time a new function version is published), or use a `replace_triggered_by` lifecycle block as suggested above.

The resource docs could stand to be improved here to describe this situation.
