### ISSUE TITLE
aws_lambda_function: please support Python3.9 runtime

### ISSUE THREAD

**Issue by BenDenney** [hashicorp/terraform-provider-aws#20590]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

terraform-provider-aws does not yet seem to support the python 3.9 runtime now available for lambda functions.

I cannot see added support in the changelog.

### New or Affected Resource(s)

Running Terraform 0.12.31, aws provider version 2.70.

### Potential Terraform Configuration

Running command:

```
terraform plan -out /tmp/lambda_to_3.9
```

Gives the following error:

```
Error: expected runtime to be one of [dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 go1.x java8 java11 nodejs4.3 nodejs4.3-edge nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x provided python2.7 python3.6 python3.7 python3.8 ruby2.5 ruby2.7], got python3.9

  on .terraform/modules/compute_environment/main.tf line 57, in resource "aws_lambda_function" "submit_job":
  57: resource "aws_lambda_function" "submit_job" {

```

### References

https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by ewbankkit** [comment]
[Announcement](https://aws.amazon.com/about-aws/whats-new/2021/08/aws-lambda-adds-support-python-3-9/).
[Blog post](https://aws.amazon.com/blogs/compute/python-3-9-runtime-now-available-in-aws-lambda/).

The enumeration value was added in [AWS SDK v1.40.21](https://github.com/aws/aws-sdk-go/releases/tag/v1.40.21), merged via #20550.
This functionality will be available in **v3.55.0** of the Terraform AWS Provider.
