### ISSUE TITLE
`aws_transfer_server` doesn't accept custom hostname tags

### ISSUE THREAD

**Issue by ElvenSpellmaker** [hashicorp/terraform-provider-aws#20612]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
TF: Terraform v1.0.2
Provider version: N/A

### Affected Resource(s)

* `aws_transfer_server`

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_transfer_server" "transfer_server" {
  ...

  tags = merge(var.tags, {
    "aws:transfer:route53HostedZoneId": "/hostedzone/${var.dns_zone_id}",
    "aws:transfer:customHostname": "${var.record_name}.${var.dns_zone_name}",
  })
}
```

### Debug Output

│ Error: error updating tags: error tagging resource (arn:aws:transfer:eu-west-1:xxxxxxx:server/s-xxxxxxx): InvalidParameter: 1 validation error(s) found.
│ - minimum field size of 1, TagResourceInput.Tags.
│ 
│ 
│   with module.sftp[0].aws_transfer_server.transfer_server,
│   on ../../../../foo/main.tf line 23, in resource "aws_transfer_server" "transfer_server":
│   23: resource "aws_transfer_server" "transfer_server" {

### Expected Behavior

These two tags are removed by https://github.com/hashicorp/terraform-provider-aws/blob/8c2e8ae9543ae5e84eabf6248982f79476355fd3/aws/internal/keyvaluetags/update_tags_gen.go#L4140 which seemingly causes the error, but it's not very descriptive either way.

These two tags are special and AWS recommends you set them.

See: https://docs.aws.amazon.com/transfer/latest/userguide/requirements-dns.html#tag-custom-hostname-cdk

![image](https://user-images.githubusercontent.com/2286713/129902636-cf18a786-41b9-4509-bf95-185390f2ea54.png)

### Actual Behavior

The cryptic error of `- minimum field size of 1, TagResourceInput.Tags.` appears, which isn't helpful and doesn't mention the fact the `aws:` prefixed tags are being removed.

### Steps to Reproduce

1. `terraform apply`

**Comment by ewbankkit** [comment]
@ElvenSpellmaker Thanks for raising this issue.
It has already been noticed in #18077. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by ElvenSpellmaker** [comment]
> 
> 
> @ElvenSpellmaker Thanks for raising this issue.
> It has already been noticed in #18077. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
> Please add any additional comments there.

Hey, sorry for opening a duplicate, I couldn't find one with search. Thanks. 🙂
