### ISSUE TITLE
For aws_sagemaker_domain aws api while running terraform script i am getting error as  resource type "aws_sagemaker_domain". is not supported but for other apis of aws sagemaker  is working fine

### ISSUE THREAD

**Issue by pravinkusin** [hashicorp/terraform-provider-aws#20624]
**For aws_sagemaker_domain aws api while running terraform script i am getting error as  resource type
"aws_sagemaker_domain". is not supported but for other apis of aws sagemaker  is working fine**

**Terraform**

```
resource "aws_sagemaker_domain" "aws-sagemaker-domain" {
  domain_name = random_string.globalrandom1.result
  auth_mode   = "IAM"
  vpc_id      = aws_vpc.test.id
  subnet_ids  = [aws_subnet.test.id]

  default_user_settings {
    execution_role = aws_iam_role.test.arn
  }
}

resource "aws_iam_role" "aws-iam-role" {
  name               = random_string.globalrandom1.result
  path               = "/"
  assume_role_policy = data.aws_iam_policy_document.aws-iam-policy-document.json
}

data "aws_iam_policy_document" "aws-iam-policy-document" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["sagemaker.amazonaws.com"]
    }
  }
}
```

**Error**

```
Error: Invalid resource type

  on aws-sagemakerdomain.tf line 1, in resource "aws_sagemaker_domain" "aws-sagemaker-domain1":
   1: resource "aws_sagemaker_domain" "aws-sagemaker-domain1" {

The provider provider.aws does not support resource type
"aws_sagemaker_domain".
```

**terraform --version**

```
Your version of Terraform is out of date! The latest version
is 1.0.5. You can update by downloading from https://www.terraform.io/downloads.html
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/aws v3.21.0
+ provider registry.terraform.io/hashicorp/random v2.3.1
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by DrFaust92** [comment]
sagemaker domain was added in provider version 3.24 and you are using 3.21. upgrade provider to use sagemaker domain resource.

https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3240-january-14-2021
