### ISSUE TITLE
aws_ebs_volume doesn't support changing from one iops type to another

### ISSUE THREAD

**Issue by williamlord-wise** [hashicorp/terraform-provider-aws#20622]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/aws v3.46.0

### Affected Resource(s)

* aws_ebs_volume

### Terraform Configuration Files

```hcl
resource "aws_ebs_volume" "default" {
  availability_zone = "eu-central-1a"
  size              = 6
  type              = "io2"
  iops              = 3000
}
```

```hcl
resource "aws_ebs_volume" "default" {
  availability_zone = "eu-central-1a"
  size              = 6
  type              = "io1"
  iops              = 3000
}
```

```
Terraform will perform the following actions:

  # aws_ebs_volume.default will be updated in-place
  ~ resource "aws_ebs_volume" "default" {
        id                   = "vol-0206f26aaa11b28a7"
        tags                 = {}
      ~ type                 = "io2" -> "io1"
        # (8 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behavior

EBS volume should change to io1.

### Actual Behavior

```
aws_ebs_volume.default: Modifying... [id=vol-0206f26aaa11b28a7]
╷
│ Error: InvalidParameterCombination: The parameter iops must be specified for io1 volumes.
│ 	status code: 400, request id: ac1413c8-b8e0-4a60-b216-038b846d9c79
│
│   with aws_ebs_volume.default,
│   on main.tf line 1, in resource "aws_ebs_volume" "default":
│    1: resource "aws_ebs_volume" "default" {
```

### Steps to Reproduce

1. `terraform apply` on the first HCL
2. `terraform apply` on the second HCL

### References

There's no change to the iops argument so iops isn't added to the modify request https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_ebs_volume.go#L186-L188. I believe iops should always be added if there's a change to type and the type is io1, io2 or gp3.

**Comment by ewbankkit** [comment]
@williamlord-wise Thanks for raising this issue.
It has already been noticed in #20536. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
