### ISSUE TITLE
Allow data source `ec2_managed_prefix_list` to return more than one match

### ISSUE THREAD

**Issue by iyesin** [hashicorp/terraform-provider-aws#20636]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I was trying to refer organization-wide shared prefix lists by filtering them by name. Unfortunately, my attempts failed with
`│ Error: more than 1 prefix list matched the given criteria`

### New or Affected Resource(s)

* `data.aws_ec2_managed_prefix_list`

### Potential Terraform Configuration

```hcl
data "aws_ec2_managed_prefix_list" "prod_lists" {
  filter {
    name = "owner-id"
    values = [var.pfx_owner]
  }

  filter {
    name = "prefix-list-name"
    values = ["???_production"]
  }
}
```
This will match two production-related prefix lists.

### References

Underlying API supports enumerating more than one resource at time. See https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeManagedPrefixLists.html .
Same works with aws-cli: `aws ec2 describe-managed-prefix-lists --filter "Name=prefix-list-name,Values=???_$ENVIRONMENT" --filter "Name=owner-id,Values=$OWNER" | grep -c "PrefixListArn"`
> 7

* #0000

**Comment by ewbankkit** [comment]
@iyesin Thanks for raising this issue.
It has already been noticed in #17119. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
