### ISSUE TITLE
aws_appsync_graphql_api resource doesn't support LAMBDA authentication type 

### ISSUE THREAD

**Issue by rkeiii** [hashicorp/terraform-provider-aws#20644]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The aws_appsync_graphql_api resource is missing the new LAMBDA authentication_type that was released on July 30th 2021. This new authentication system makes it much simpler to add entirely custom auth to AppSync (no Cognito/etc. needed).

I might be interested in adding support for this but I've never contributed to this codebase before.

Feature release blog post: https://aws.amazon.com/blogs/mobile/appsync-lambda-auth/

### New or Affected Resource(s)

* aws_appsync_graphql_api

**Comment by bengiddins** [comment]
Suggested implementation (I need this too!):

`additional_authentication_provider {
  authentication_type = "AWS_LAMBDA"

  lambda_config {
    region = "..."
    function_arn = "..."
    auth_ttl = "..."
    token_regex = "..."
  }
}`

Based on AppSync's additional authorization provider UI for AWS Lambda authorization mode.

**Comment by Pharb** [comment]
I am working on a PR for this.

Usage example:

```terraform
resource "aws_appsync_graphql_api" "example" {
  authentication_type = "AWS_LAMBDA"
  name                = "example"

  lambda_authorizer_config {
    authorizer_uri = "arn:aws:lambda:us-east-1:123456789012:function:custom_lambda_authorizer"
  }
}

resource "aws_lambda_permission" "appsync_lambda_authorizer" {
  statement_id  = "appsync_lambda_authorizer"
  action        = "lambda:InvokeFunction"
  function_name = "custom_lambda_authorizer"
  principal     = "appsync.amazonaws.com"
  source_arn    = aws_appsync_graphql_api.example.arn
}
```

**Comment by digitalfiz** [comment]
So I am confused on this. The documentation doesn't show a `authentication_type` of `AWS_LAMBDA` but I can set it to that and I get this error:

```
aws_appsync_graphql_api.chat: Modifying... [id=xx5dy3afyfbnpgujn76tpg2mxi]

Error: error updating AppSync GraphQL API (xx5dy3afyfbnpgujn76tpg2mxi): BadRequestException: Lambda Authorizer Config missing

  with aws_appsync_graphql_api.chat,
  on appsync.tf line 1, in resource "aws_appsync_graphql_api" "chat":
   1: resource "aws_appsync_graphql_api" "chat" {
```

So it does support it but no documentation for it? or is this some passthrough error from aws?

**Comment by lescaudr** [comment]
Any update, would love to use this feature :)

**Comment by filipjakubowski** [comment]
I am waiting for this change. At this moment I am using AWS CLI command in my CI/CD post terraform but still when working form console by myself I find this being a pain. 

` aws appsync update-graphql-api \
            --no-cli-auto-prompt \
            --name "$PROJECT_NAME" \
            --api-id "$APPSYNC_ID" \
            --authentication-type "AWS_LAMBDA" \
            --lambda-authorizer-config "{ \"authorizerResultTtlInSeconds\": 300, \"authorizerUri\": \"$LAMBDA_AUTH_APPSYNC_ARN\" }"`

**Comment by lescaudr** [comment]
thank you @filipjakubowski, based on your cli, I'm using AWS_LAMBDA as second auth type:
```
          aws appsync update-graphql-api \
          --no-cli-auto-prompt \
          --name "$PROJECT_NAME" \
          --authentication-type "API_KEY" \
          --api-id "$APPSYNC_ID" \
          --region us-east-1 \
          --additional-authentication-providers "[ { \"authenticationType\":\"AWS_LAMBDA\", \"lambdaAuthorizerConfig\": { \"authorizerResultTtlInSeconds\": 0, \"authorizerUri\": \"$LAMBDA_AUTH_APPSYNC_ARN\", \"identityValidationExpression\": \"auth\" } } ]"

```
