### ISSUE TITLE
Add aws_default_route resource

### ISSUE THREAD

**Issue by DonBower** [hashicorp/terraform-provider-aws#20663]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Much like the aws_default_route_table, which will assume the existence of the route table with an empty state-file, having a resource that will assume the state of a default route (0.0.0.0/0, ::/0) for a supplied route table, would allow for the modification or creation, as appropriate, of a default route

### New or Affected Resource(s)

* aws_default_route

### Potential Terraform Configuration

```hcl
resource aws_default_route defaultRoute {
  route_table_id            = "rtb-4fbb3ac4"

  ipv4_default_route = {
    gateway_id = aws_internet_gateway.example.id
  }
  
  ipv6_default_route = {
    egress_only_gateway_id = aws_egress_only_internet_gateway.example.id
  }
}
```

**Comment by DonBower** [comment]
An alternative would be to allow for a lifecycle parameter that allows to overwrite the existing route entry, regardless of state.

i.e.:
```
resource "aws_route" "r" {
  route_table_id            = "rtb-4fbb3ac4"
  destination_cidr_block    = "0.0.0.0/0"
  vpc_peering_connection_id = "pcx-45ff3dc1"
  lifecycle {
    overwrite = true
  }
}
```

**Comment by ewbankkit** [comment]
Similar: https://github.com/hashicorp/terraform-provider-aws/issues/21350.
