### ISSUE TITLE
aws_s3_object_copy: default_tags changes are not applied

### ISSUE THREAD

**Issue by Madh93** [hashicorp/terraform-provider-aws#20681]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.55.0
```

### Affected Resource(s)

* aws_s3_object_copy

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "eu-west-1"

  default_tags {
    tags = merge({ Environment = terraform.workspace }, var.tags)
  }
}

resource "aws_s3_object_copy" "this" {
  bucket = "my-destination-bucket-1234"
  key    = "hello.txt"
  source = "my-source-bucket-1234/hello.txt"
}
```

### Terraform Plan

```hcl
Terraform will perform the following actions:

  # aws_s3_object_copy.this will be updated in-place
  ~ resource "aws_s3_object_copy" "this" {
        id                     = "hello.txt"
        tags                   = {}
      ~ tags_all               = {
          + "App"         = "test"
          + "CreatedBy"   = "terraform"
          + "Environment" = "default"
          + "Repository"  = "tf-samples"
        }
        # (14 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behavior

The default tags should be added to the new bucket object.

### Actual Behavior

The change is not applied. So in the next rerun I get the same change to apply. In addition, the S3 console does not show any tags:

![2021-08-25_09-47](https://user-images.githubusercontent.com/5855179/130749407-b7266939-466c-45d7-918f-80aecd65723b.png)

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply` (same result)

**Comment by ewbankkit** [comment]
Similar: https://github.com/hashicorp/terraform-provider-aws/issues/25477.
