### ISSUE TITLE
Cloudwatch Log Group Data Source: Remove extraneous suffix in `arn` attribute

### ISSUE THREAD

**Issue by arsdehnel** [hashicorp/terraform-provider-aws#20721]
My problem is virtually identical to https://github.com/hashicorp/terraform-provider-aws/issues/13509 except I'm having the problem with the Data Source for the CloudWatch Log Group rather than the resource.  As mentioned in that issue the CloudWatch Logs API includes the :* suffix in the value, which represents the ARN for all CloudWatch Log Streams under this CloudWatch Log Group. This inclusion of additional information in the ARN is inconsistent with all other AWS APIs and Terraform resources that provide ARN attributes.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/aws v3.56.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/http v2.1.0

### Affected Resource(s)

data.aws_cloudwatch_log_group

### Terraform Configuration Files

```hcl
resource "aws_flow_log" "all_vpc" {
  iam_role_arn    = "arn:aws:iam::${var.account_id}:role/flow-log-role"
  log_destination = data.aws_cloudwatch_log_group.all_vpc_flow_logs.arn
  traffic_type    = "ALL"
  vpc_id          = aws_vpc.main.id
  tags            = local.standard_tags
}

data "aws_cloudwatch_log_group" "all_vpc_flow_logs" {
  name = "vpc-flow-logs--all"
}
```

### Expected Behavior

This should find my existing log group (created in another piece of Terraform) and provide the proper ARN to the flow log resource for a log destination.

### Actual Behavior

This unexpected ARN value causes Terraform to destroy and recreate the flow log definition every time this runs.  Functionally this ends up working but only because AWS accepts the ARN with the trailing `:*` and removes it when TF calls the API.  The issue here is that I'm constantly having to ignore this destroy/create that results from this bug and ignoring destroy/creates is a very dangerous practice in automated infrastrcture.  

### Steps to Reproduce

1. run this once to create the flow log resource
2. run it again and see that it wants to destroy and re-create that same resource again

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/13509

**Comment by ewbankkit** [comment]
@arsdehnel Thanks for raising this issue.
It has already been noticed in #15073. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by arsdehnel** [comment]
Cool, thanks. Sorry about that my searching was focused on the cloudwatch name so I seem to have missed that one.
