### ISSUE TITLE
Support aws_eks_addon_version data source

### ISSUE THREAD

**Issue by arianvp** [hashicorp/terraform-provider-aws#20725]
### Description

In order to map [`aws_eks_addon`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_addon)'s `version` latest parameter to the  `aws_eks_cluster` `version`;  there is an endpoint  https://docs.aws.amazon.com/eks/latest/APIReference/API_DescribeAddonVersions.html

This would allow me to automatically update EKS addons for my EKS cluster.

### New or Affected Resource(s)

* data.aws_eks_addon_version
* data.aws_eks_addon_versions

### Potential Terraform Configuration

```hcl
resource "aws_eks_cluster" "cluster" {
  name =  "blah"
}

data "aws_eks_addon_version" "vpc_cni" {
  addon_name = "vpc-cni"
  kubernetes_version  = aws_eks_cluster.cluster.version

 // IDK; some filter to select the `defaultVersion`
}

resource "aws_eks_addon" "vpc_cni" {
  cluster_name = aws_eks_cluster.cluster.name
  addon_name = "vpc-cni"
  addon_version =  data.aws_eks_addon_versions.vpc_cni.addon_version
  
}


```

### References

* https://docs.aws.amazon.com/eks/latest/APIReference/API_DescribeAddonVersions.html

* https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1443#issuecomment-893275485

**Comment by daroga0002** [comment]
I think demand for this data source will be quite big as this will solve a lot of issues.

**Comment by michelzanini** [comment]
Any progress with this? This would really help us a lot as it would avoid having to keep track of add-on versions.

**Comment by juozasget** [comment]
Hi, I can try to pick this up in the next few days.

![image](https://user-images.githubusercontent.com/32190964/140490407-fa09ebcf-705a-4483-977d-fc9eab6c7352.png)
Looking at the api response and AWS console UI (above image). I guess it would be useful to get either the default or latest version (according to semantic versioning). So we could have a version field with default value being "default" and also have an option of choosing "latest" (calculated from semantic versioning).

For any other version, most likely you will want to look it up manually.
Also probably no use for returning all the versions with `data.aws_eks_addon_versions`? Let me know if this should be included?

`
data "aws_eks_addon_version" "vpc_cni" {
  addon_name = "vpc-cni"
  kubernetes_version  = aws_eks_cluster.cluster.version
  version = "latest"
}
`

**Comment by daroga0002** [comment]
I think it should be:
```
data "aws_eks_addon_version" "vpc_cni" {
  addon_name = "vpc-cni"
  kubernetes_version  = aws_eks_cluster.cluster.version
  # version = "default" << optional definition as default version is default add on version
}
```

and overwrite to latest by:
```
data "aws_eks_addon_version" "vpc_cni" {
  addon_name = "vpc-cni"
  kubernetes_version  = aws_eks_cluster.cluster.version
  version = "latest"
}
```



probably also in future second datasource will be beneficial `aws_eks_addons` to allow something like:
```
data "aws_eks_addons" "addons" {
  kubernetes_version  = aws_eks_cluster.cluster.version
  version = "latest"
}

data "aws_eks_addon_version" "vpc_cni" {
  for_each = data.aws_eks_addons.addons.name
  
  addon_name = each.key
  kubernetes_version  = aws_eks_cluster.cluster.version
  version = "latest"
}
```

**Comment by michelzanini** [comment]
Regarding detecting the latest version, I believe the API always return them in order, where the first element is the latest:

```
aws eks describe-addon-versions --addon-name vpc-cni --query 'addons[*].addonVersions[*].addonVersion'
```

```
[
        "v1.9.3-eksbuild.1",
        "v1.9.1-eksbuild.1",
        "v1.9.0-eksbuild.1",
        "v1.8.0-eksbuild.1",
        "v1.7.10-eksbuild.1",
        "v1.7.9-eksbuild.2",
        "v1.7.6-eksbuild.2",
        "v1.7.5-eksbuild.2",
        "v1.6.3-eksbuild.2",
        "v1.7.9-eksbuild.1",
        "v1.7.6-eksbuild.1",
        "v1.7.5-eksbuild.1",
        "v1.6.3-eksbuild.1"
]
```

I get the same results with other Add-Ons, it's always sorted...

**Comment by daroga0002** [comment]
in our case we also need a cluster version compatibility so AWS cli will be something like:
```bash
$ aws eks describe-addon-versions --addon-name vpc-cni --query 'addons[*].addonVersions[*].addonVersion' --kubernetes-version 1.20
[
    [
        "v1.9.3-eksbuild.1",
        "v1.9.1-eksbuild.1",
        "v1.9.0-eksbuild.1",
        "v1.8.0-eksbuild.1",
        "v1.7.10-eksbuild.1",
        "v1.7.9-eksbuild.2",
        "v1.7.6-eksbuild.2",
        "v1.7.5-eksbuild.2",
        "v1.6.3-eksbuild.2"
    ]
]
```

**Comment by michelzanini** [comment]
> in our case we also need a cluster version compatibility so AWS cli will be something like:
> 
> ```shell
> $ aws eks describe-addon-versions --addon-name vpc-cni \
>          --query 'addons[*].addonVersions[*].addonVersion' \
>          --kubernetes-version 1.20
> [
>     [
>         "v1.9.3-eksbuild.1",
>         "v1.9.1-eksbuild.1",
>         "v1.9.0-eksbuild.1",
>         "v1.8.0-eksbuild.1",
>         "v1.7.10-eksbuild.1",
>         "v1.7.9-eksbuild.2",
>         "v1.7.6-eksbuild.2",
>         "v1.7.5-eksbuild.2",
>         "v1.6.3-eksbuild.2"
>     ]
> ]
> ```

Yes, correct. I only did it without to be able to see more versions and make they always return sorted.

**Comment by llamahunter** [comment]
Is any motion happening on this issue? We just updated to 1.21 (finally) and none of our add-ons updated.  Was sort of hoping that since we pass 'null' for the version that they would just get the latest ones on upgrade, but nothing happened.

**Comment by charlesakalugwu** [comment]
@llamahunter @daroga0002 @michelzanini @juozasget @arianvp Please take a look at https://github.com/hashicorp/terraform-provider-aws/pull/23157
