### ISSUE TITLE
Support for resizing prefix lists

### ISSUE THREAD

**Issue by jbscare** [hashicorp/terraform-provider-aws#20738]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

https://aws.amazon.com/about-aws/whats-new/2021/08/amazon-vpc-resize-prefix-list/ says that VPC prefix lists can now be resized without destroy and re-creating them.

### New or Affected Resource(s)

* aws_ec2_managed_prefix_list

### Potential Terraform Configuration

Perhaps the `max_entries` parameter could be removed entirely; if the AWS API still requires it, it could be computed on the fly based on the length of the list. Or it could still be required by Terraform, but just allow for a change without destroying and re-creating the list; but if it could be made optional, that'd be a nice feature.

### References

* https://aws.amazon.com/about-aws/whats-new/2021/08/amazon-vpc-resize-prefix-list/

**Comment by anilkumardesai** [comment]
I had opened another issue #20772 but was redirected to this.

We need this modify feature to add new entries to the existing prefix list. This will solve the resize issue as well.

- https://docs.aws.amazon.com/cli/latest/reference/ec2/modify-managed-prefix-list.html
