### ISSUE TITLE
Optional attributes are required in aws_route_table

### ISSUE THREAD

**Issue by jtatum** [hashicorp/terraform-provider-aws#20756]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.56.0

### Affected Resource(s)

* aws_route_table

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_route_table" "test" {
  vpc_id = aws_vpc.test.id

  route = [
      {
          cidr_block = "0.0.0.0/0"
          gateway_id = aws_internet_gateway.test.id
      }
  ]
}
```

### Expected Behavior

Example from documentation should run.

### Actual Behavior

Error from Terraform:

    Inappropriate value for attribute "route": element 0: attributes "carrier_gateway_id", "destination_prefix_list_id", "egress_only_gateway_id", "instance_id",
    "ipv6_cidr_block", "local_gateway_id", "nat_gateway_id", "network_interface_id", "transit_gateway_id", "vpc_endpoint_id", and "vpc_peering_connection_id" are required.

### Steps to Reproduce

1. `terraform plan`

### References

* #17618 - Closed based on documentation examples. The documentation example as it is today is currently broken.
* #20428 - MR that changed docs to have a broken example.

**Comment by dcpc007** [comment]
Same problem here after upgrading the aws provider and adapt several config to the new format described in the doc.

Any ETA ? or recommandation to downgrade the provider and stick with older version ?

**Comment by nate-udacity** [comment]
@dcpc007, give this a try comrade:

https://github.com/hashicorp/terraform-provider-aws/issues/17618#issuecomment-779474842

`resource "aws_route_table" "hmviart" {
  count = var.use_aws

  vpc_id = aws_vpc.hmviart[0].id

  route {
    cidr_block                = "0.0.0.0/0"
    egress_only_gateway_id    = ""
    gateway_id                = aws_internet_gateway.hmviart[0].id
    instance_id               = ""
    #ipv6_cidr_block           = ""
    nat_gateway_id            = ""
    network_interface_id      = ""
    transit_gateway_id        = ""
    vpc_peering_connection_id = ""
  }
}`

**Comment by dcpc007** [comment]
Currently i reinstall v3.46, waiting to see later if they really pass all those attribute optional (with validate thats works), or if really forced to modify all the blocks to add all the attributes with empty value.

Hope it will be the first. Terraform files are enough long like this :)

**Comment by derekrj21** [comment]
`Terraform v1.0.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.58.0`

Same issue here. Had to pass blank attributes to proceed.

**Comment by mikenorton** [comment]
Same issue here on hashicorp/aws v3.58.0

**Comment by alvintownsend** [comment]
The solution provided by @nate-udacity didn't quite work for me for some reason, but following his example, this got me past the issue:

```
resource "aws_route_table" "my_route_table" {
  vpc_id = aws_vpc.my_vpc.id

  route = [
    {
      cidr_block = "0.0.0.0/0"
      gateway_id = aws_internet_gateway.my_gateway.id

      # workaround as suggested here: https://github.com/hashicorp/terraform-provider-aws/issues/20756#issuecomment-913284042
      carrier_gateway_id         = ""
      destination_prefix_list_id = ""
      egress_only_gateway_id     = ""
      instance_id                = ""
      ipv6_cidr_block            = ""
      local_gateway_id           = ""
      nat_gateway_id             = ""
      network_interface_id       = ""
      transit_gateway_id         = ""
      vpc_endpoint_id            = ""
      vpc_peering_connection_id  = ""
    }
  ]

  tags = {
    Name = "my_route_table"
  }
}
```

**Comment by michaelcox** [comment]
Terraform 1.0.5 / AWS 3.56.0

Changing the format to the one suggested by @nate-udacity worked for me and doesn't require me to fill in empty strings for fields I don't care about. To be clear, the part that makes it work is switching away from the array format and instead use the terraform format.

Use this format:

```
route {
 ...
}

route {
 ...
}
```

Instead of:

```
route = [
  { ... }
  { ... }
]
```

**Comment by alvintownsend** [comment]
Good call @michaelcox, I didn't realize the `aws_route_table` could be used with the `route` in a non-array format.
