### ISSUE TITLE
aws_ecs_cluster containerInsights - 'enabled' state not recognised.

### ISSUE THREAD

**Issue by ch-gareth** [hashicorp/terraform-provider-aws#20751]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
CLI version: 0.12.31
AWS Provider version: 3.56.0

### Affected Resource(s)
* aws_ecs_cluster

### Terraform Configuration Files
Deploying a basic ECS cluster with Container Insights enabled:
```hcl
setting {
  name  = "containerInsights"
  value = "enabled"
}
```

### Result
The following change is always showing required - even if it's just been applied, the next plan shows it again:
```
+ setting {
    + name  = "containerInsights"
    + value = "enabled"
}
```

### Expected Behaviour
Following an 'apply', running a 'plan' immediately after should show: `0 to add, 0 to change, 0 to destroy.`

### Actual Behaviour
Following an 'apply', running a 'plan' immediately shows: `0 to add, 1 to change, 0 to destroy.`
Change is:
```
aws_ecs_cluster.my_cluster will be updated in-place
...
...
+ setting {
   + name  = "containerInsights"
   + value = "enabled"
}
...
...
Plan: 0 to add, 1 to change, 0 to destroy.
```

There are no other changes showing to be applied - just this.
Applying the change works correctly. No errors on application.
Container Insights shows as enabled in the AWS console.
But running a plan again - this change shows still required.
This has started happening in the last couple of days.

### Workaround
Working around this for now using:
```
lifecycle {
   ignore_changes = [ setting ]
 }
```

**Comment by ewbankkit** [comment]
@ch-gareth Thanks for raising this issue.
It has already been noticed in #20684. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

The fix will be available in **v3.57.0** of the Terraform AWS Provider, likely later this week.
