### ISSUE TITLE
aws_iam_policy_document fails on apply if sid has dashes

### ISSUE THREAD

**Issue by neilfarmer** [hashicorp/terraform-provider-aws#20767]
Hello Terraform AWS Gurus!

Id like to report a bug with the aws_iam_policy_document. When I add dashes into the terraform sid name it fails when applied. Terraform does not complain/notice till the apply. Examples below

My TF code:
```
data "aws_iam_policy_document" "some_policy_doc" {
  statement {
    sid       = "some-policy-doc"
    effect    = "Allow"
    resources = ["*"]

    actions = ["*"]
  }
}
```

My error code:
```
│ Error: error putting Inline Policy for SSO Permission Set (arn:aws:sso:::permissionSet/ssoins-stuff/ps-stuff): ValidationException: Invalid PermissionsPolicy Document {
│   "Version": "2012-10-17",
│   "Statement": [
│     {
│       "Sid": "some_policy_doc",
│       "Effect": "Allow",
│       "Action": ["*"],
│       "Resource": "*"
│     }
│   ]
│ }.
│ 
│   with aws_ssoadmin_permission_set_inline_policy.some_inline_policy,
│   on file.tf line 26, in resource "aws_ssoadmin_permission_set_inline_policy" "some_inline_policy":
│   26: resource "aws_ssoadmin_permission_set_inline_policy" "some_inline_policy" {
│ 
╵
```

I would expect that when I run a `terraform plan`, terraform would complain to me before I perform my apply.

After converting the sid name to camel case `some-policy-doc` --> `SomePolicyDoc`, it applys fine.

Hopefully this is enough info. 

Thanks!

**Comment by gdavison** [comment]
Thanks for submitting this, @neilfarmer. The [AWS documentation for `sid`](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_grammar.html#policies-grammar-notes) says that in most cases, `sid` can only contain alphanumeric characters, but some services allow other characters. Adding this restriction could cause errors for Terraform configurations which do allow additional characters.

I'm going to close this issue
