### ISSUE TITLE
Implement modify-managed-prefix-list in terraform

### ISSUE THREAD

**Issue by anilkumardesai** [hashicorp/terraform-provider-aws#20772]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Need a functionality to add an entry to a `aws_ec2_managed_prefix_list`

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
resource "modify_managed_prefix_list" "example" {

  id = <>
  name = <>

  entry {
    cidr        = aws_vpc.example.cidr_block
    description = "Primary"
  }
}
```

### References

* https://docs.aws.amazon.com/cli/latest/reference/ec2/modify-managed-prefix-list.html

**Comment by ewbankkit** [comment]
@anilkumardesai Thanks for raising this issue.
It has already been noticed in #20738. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by anilkumardesai** [comment]
@ewbankkit That issue is regarding the size of the prefix list. But this one is specifically talking about adding new entries to the existing prefix list. 
Do you still think it makes sense to combine?

**Comment by jbscare** [comment]
> @ewbankkit That issue is regarding the size of the prefix list. But this one is specifically talking about adding new entries to the existing prefix list.

You can add entries to a managed prefix list with Terraform now, as long as they don't cause the length of the list to exceed the maximum size. Have you found otherwise?

**Comment by anilkumardesai** [comment]
> > @ewbankkit That issue is regarding the size of the prefix list. But this one is specifically talking about adding new entries to the existing prefix list.
> 
> You can add entries to a managed prefix list with Terraform now, as long as they don't cause the length of the list to exceed the maximum size. Have you found otherwise?

@jbscare Can you please point me to the terraform code for that? I couldn't find a way to add entries to an existing prefix list. I dont need to change the size.

**Comment by jbscare** [comment]
I don't have a real life example because we have Python code using Terrascript to generate JSON configs from YAML files, but looking at the [example usage](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_managed_prefix_list#example-usage), if you had something like this:

```
resource "aws_ec2_managed_prefix_list" "example" {
  name           = "All VPC CIDR-s"
  address_family = "IPv4"
  max_entries    = 5

  entry {
    cidr        = aws_vpc.example.cidr_block
    description = "Primary"
  }

  entry {
    cidr        = aws_vpc_ipv4_cidr_block_association.example.cidr_block
    description = "Secondary"
  }
```

I think you'd just add another `entry` block, right? And then `terraform plan` would show that it wanted to add another CIDR to the list, and so on.

**Comment by anilkumardesai** [comment]
No @jbscare , this will create a new Prefix list with those two entries. If you are already creating that prefix list via terraform then you can update that code but that also will replace the prefix list.

**Comment by jbscare** [comment]
That's not how it works for us; we pretty routinely change the `entry` blocks on our prefix lists, and it adds them to the existing list. This diff:
```
[10:49:12] jsmift@mgmt-gold-useast1-control-g1:/home/jsmift/src/terraform-mgmt/mgmt-gold-useast1/misc
+$ git diff -U8 *json
diff --git a/mgmt-gold-useast1/misc/tsumami.tf.json b/mgmt-gold-useast1/misc/tsumami.tf.json
index 7f73ab8..e567197 100644
--- a/mgmt-gold-useast1/misc/tsumami.tf.json
+++ b/mgmt-gold-useast1/misc/tsumami.tf.json
@@ -642,16 +642,19 @@
       "mgmt-gold-useast1-aws-int": {
         "address_family": "IPv4",
         "entry": [
           {
             "cidr": "10.0.0.0/12"
           },
           {
             "cidr": "172.16.0.0/12"
+          },
+          {
+            "cidr": "192.168.0.0/16"
           }
         ],
         "max_entries": 10,
         "name": "mgmt-gold-useast1-aws-int",
         "provider": "aws.us-east-1",
         "tags": {
           "Name": "mgmt-gold-useast1-aws-int",
           "care:class": "gold",

```
produces this `terraform plan` output:
```
Terraform will perform the following actions:

  # aws_ec2_managed_prefix_list.mgmt-gold-useast1-aws-int will be updated in-place
  ~ resource "aws_ec2_managed_prefix_list" "mgmt-gold-useast1-aws-int" {
        id             = "pl-038f2b8c61393d0b3"
        name           = "mgmt-gold-useast1-aws-int"
        tags           = {
            "Name"                  = "mgmt-gold-useast1-aws-int"
            "care:class"            = "gold"
            "care:megaservice"      = "mgmt"
            "care:prodops:tf:repo"  = "terraform-mgmt"
            "care:prodops:tf:tfenv" = "terraform-mgmt/mgmt-gold-useast1/misc"
        }
      ~ version        = 1 -> (known after apply)
        # (4 unchanged attributes hidden)

      - entry {
          - cidr = "10.0.0.0/12" -> null
        }
      + entry {
          + cidr = "10.0.0.0/12"
        }
      - entry {
          - cidr = "172.16.0.0/12" -> null
        }
      + entry {
          + cidr = "172.16.0.0/12"
        }
      + entry {
          + cidr = "192.168.0.0/16"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
It's changing the order of things on the list, but it's updating the list in place, not destroying and re-creating it.

What happens when you try?

**Comment by anilkumardesai** [comment]
@jbscare Apologies for making it not clear.
I am actually doing the operations from two different terraform project.
Project#1, this will create the prefix list, one time.
Projest#2, this project will run as a part of an automated pipeline everytime there is a new account added to our transit gateway setup. So this is where I want to modify the existing prefix list by adding entries.

**Comment by jbscare** [comment]
Ah, ok; that's not really how Terraform works. :^ ) The general idea is that your Terraform configuration describes the state you want to have, not the changes you want to make.

If you have an existing prefix list (or any resource, really) and you want Terraform to manage it, you'd typically want to add it to your Terraform configuration and then import it into your Terraform state, after which point you'd modify the configuration and use Terraform to apply the changes to the resource.

**Comment by anilkumardesai** [comment]
Yeah, its not a best practice but we had a limitation with our design so wanted to split this. But now I have moved both creation and updating into a single project to avoid such conflicts.
