### ISSUE TITLE
EFS: support for Transition out of IA

### ISSUE THREAD

**Issue by acdha** [hashicorp/terraform-provider-aws#20773]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS recently announced support for EFS lifecycle policies which transition files from IA to the standard storage tiers:

https://aws.amazon.com/about-aws/whats-new/2021/09/amazon-elastic-file-system-intelligent-tiering/

### New or Affected Resource(s)

* aws_efs_file_system

### Potential Terraform Configuration

```hcl
resource "aws_efs_file_system" "collection" {
  lifecycle_policy
    transition_to_ia = "AFTER_30_DAYS"
    transition_from_ia = "AFTER_1_ACCESS"
  }
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2021/09/amazon-elastic-file-system-intelligent-tiering/
* https://aws.amazon.com/blogs/aws/new-amazon-efs-intelligent-tiering-optimizes-costs-for-workloads-with-changing-access-patterns/
* https://docs.aws.amazon.com/efs/latest/ug/lifecycle-management-efs.html

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.40.36](https://github.com/aws/aws-sdk-go/releases/tag/v1.40.36).
