### ISSUE TITLE
Have sync config option for route53 healthcheck resource

### ISSUE THREAD

**Issue by enicholson125** [hashicorp/terraform-provider-aws#20786]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating a route53 healthcheck resource like

```hcl
resource "aws_route53_health_check" "ovo_nlb_healthcheck" {
  type                            = "CLOUDWATCH_METRIC"
  cloudwatch_alarm_name           = aws_cloudwatch_metric_alarm.ovo_nlb_healthcheck.alarm_name
  cloudwatch_alarm_region         = local.aws_region
  insufficient_data_health_status = "Unhealthy"
}
```

you have to go into the console to press the "Synchronize configuration" button on each healthcheck for the healthcheck to pick up the monitor configuration and start reporting as healthy. It would be great to have an option to synchronise the configuration as part of the terraform creation/update and not have the manual step.

### New or Affected Resource(s)

* aws_route53_health_check

### Potential Terraform Configuration

```hcl
resource "aws_route53_health_check" "ovo_nlb_healthcheck" {
  type                            = "CLOUDWATCH_METRIC"
  cloudwatch_alarm_name           = aws_cloudwatch_metric_alarm.ovo_nlb_healthcheck.alarm_name
  cloudwatch_alarm_region         = local.aws_region
  insufficient_data_health_status = "Unhealthy"
  synchronize_configuration = true # New option
}
```
Alternatively the synchronization could happen automatically as part of creation or update.

### References

* #0000

**Comment by DrFaust92** [comment]
The sdk does not currently seem to expose such an attribute so im setting this as an upstream issue
