### ISSUE TITLE
aws_cloudhsm_v2_hsm not created unless optional input AZs are included in resource

### ISSUE THREAD

**Issue by mdawn** [hashicorp/terraform-provider-aws#20792]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform version  1.0.3
terragrunt version v0.31.7
aws-cli/2.2.21
aws provider version 3.54.0

### Affected Resource(s)

*aws_cloudhsm_v2_hsm

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_cloudhsm_v2_hsm" "cloudhsm_v2_hsm" {
  cluster_id = aws_cloudhsm_v2_cluster.cloudhsm_v2_cluster.cluster_id
  subnet_id  = "[${join(", ", [for s in var.subnet_ids : format("%q", s)])}]"
}
```

### Expected Behavior

The `aws_cloudhsm_v2_hsm` resource is created using subnets (and avaliability zones are an optional input).

### Actual Behavior

 Creation of `aws_cloudhsm_v2_hsm` errors with message `missing required field, CreateHsmInput.AvailabilityZone`

1. First I created an `aws_cloudhsm_v2_cluster` via `terraform apply` using `subnet_ids`. I can confirm cluster creation in the console.

```hcl
#
# CloudHSM v2 cluster
#

resource "aws_cloudhsm_v2_cluster" "cloudhsm_v2_cluster" {
  hsm_type   = var.hsm_type
  subnet_ids = var.subnet_ids

  tags = merge(
    {
      Name = "${var.environment}-aws_cloudhsm_v2_cluster"
    },
    var.extra_tags,
    var.terragrunt_tags
  )
}
```
2. Next I used the following code to create the `aws_cloudhsm_v2_hsm` device and then initialize the cluster, passing in the same subnets.

```hcl
#
# Creates an HSM module in Amazon CloudHSM v2 cluster
#

resource "aws_cloudhsm_v2_hsm" "cloudhsm_v2_hsm" {
  cluster_id = aws_cloudhsm_v2_cluster.cloudhsm_v2_cluster.cluster_id
  subnet_id  = "[${join(", ", [for s in var.subnet_ids : format("%q", s)])}]"
}
```

Terraform plan is as follows:
```hcl
Terraform will perform the following actions:

  # aws_cloudhsm_v2_hsm.cloudhsm_v2_hsm will be created
  + resource "aws_cloudhsm_v2_hsm" "cloudhsm_v2_hsm" {
      + availability_zone = (known after apply)
      + cluster_id        = "cluster-XXXXXX"
      + hsm_eni_id        = (known after apply)
      + hsm_id            = (known after apply)
      + hsm_state         = (known after apply)
      + id                = (known after apply)
      + ip_address        = (known after apply)
      + subnet_id         = jsonencode(
            [
              + "subnet-XXXXX",
              + "subnet-XXXXX",
              + "subnet-XXXXX",
            ]
        )
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

3. Terraform apply yields the following error:

```bash
aws_cloudhsm_v2_hsm.cloudhsm_v2_hsm: Creating...
╷
│ Error: error creating CloudHSMv2 HSM: InvalidParameter: 1 validation error(s) found.
│ - missing required field, CreateHsmInput.AvailabilityZone.
│ 
│ 
│   with aws_cloudhsm_v2_hsm.cloudhsm_v2_hsm,
│   on main.tf line 22, in resource "aws_cloudhsm_v2_hsm" "cloudhsm_v2_hsm":
│   22: resource "aws_cloudhsm_v2_hsm" "cloudhsm_v2_hsm" {
│ 
╵
Releasing state lock. This may take a few moments...
ERRO[0063] 1 error occurred:
	* exit status 1
```

### References

* [cloudhsm_v2_hsm resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudhsm_v2_hsm)
Relevant language:
`availability_zone - (Optional) The IDs of AZ in which HSM module will be located. Do not use together with subnet_id.`

**Comment by justinretzolk** [comment]
Hey @mdawn 👋 I'm took a look at this, and I believe the issue here is that the `subnet_id` argument is expected to be a single subnet ID. It looks like the suspect bit of code is [here](https://github.com/hashicorp/terraform-provider-aws/blob/b122f84ad78df2b6dabf7620072200b7e3a6feed/internal/service/cloudhsmv2/hsm.go#L95-L100), where a match is never found, and so `input.AvailabilityZone` is `nil`. I'd still consider this to be something we should fix with validation (and a small change to the documentation), but I hope this helps you get past this issue, if you haven't already.
