### ISSUE TITLE
✨ Add `initial_lifecycle_hook` to `aws_eks_node_group`

### ISSUE THREAD

**Issue by bappr** [hashicorp/terraform-provider-aws#20794]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It's currently not possible to add lifecycle_hook to an ASG that is being created by a `aws_eks_node_group` module.
Indeed, there is no `initial_lifecycle_hook` for this resource and if using `aws_autoscaling_lifecycle_hook` module as part of the same flow that created the `aws_eks_node_group` module, we end up with the error
```
The "for_each" value depends on resource attributes that cannot be
determined until apply, so Terraform cannot predict how many instances will
be created. To work around this, use the -target argument to first apply
only the resources that the for_each depends on.
```
I'd like to add the `initial_lifecycle_hook` to the `aws_eks_node_group` module so that we are able to provide default lifecycle hook on the ASGs that are being created. It's similar to the `worker_create_initial_lifecycle_hooks` of the `terraform-aws-eks` module.

The feature request will affect the `aws_eks_node_group` module but it will be backward compatible.

* aws_eks_node_group

**Comment by bappr** [comment]
If approved, I am interested in doing it.

**Comment by mattburgess** [comment]
It doesn't look like the AWS SDK (https://docs.aws.amazon.com/sdk-for-go/api/service/eks/) exposes any way of interacting with the underlying autoscaling group. For reference, [`PutLifecycleHook`](https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#AutoScaling.PutLifecycleHook) is what enables the provider to manipulate them on an `aws_autoscaling_group`. Until such support is available in the SDK, I don't think there's much Terraform can do right now.

@bappr - you might want to reach out to AWS support (or to https://github.com/aws/aws-sdk / https://github.com/aws/aws-sdk-go) to see if there are any features in flight to enable such configuration.

**Comment by bappr** [comment]
Hey @mattburgess thanks for the reply and sorry for the delay.

I reached out to AWS about the initial problem I was trying to fix with Lifecycle Hook -> drain node upon termination of an instance. Managed node groups apparently already do that by default (we are migrating from worker groups to managed node groups).

So I can close this issue. Thanks!
