### ISSUE TITLE
resource "aws_appmesh_mesh"

### ISSUE THREAD

**Issue by cloudcoreai** [hashicorp/terraform-provider-aws#20802]
There is no "namespace" argument for AWS AppMesh.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

➜  us-west-2 terraform -v
Terraform v1.0.4
on darwin_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.11.3
+ provider registry.terraform.io/hashicorp/aws v3.56.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.3.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.4.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

### Affected Resource(s)

resource "aws_appmesh_mesh" "simple" {
  name = "simpleapp"

  spec {
    egress_filter {
      type = "ALLOW_ALL"
    }
  }
}

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appmesh_mesh

* #0000

**Comment by cloudcoreai** [comment]
Also, using "kubectl get mesh" does not show the app mesh info. It does show up in the aws console.

**Comment by ewbankkit** [comment]
@cloudcoreai Thanks for raising this issue.
`namespace` is a Kubernetes-only concept that applies to the [App Mesh Kubernetes CRDs](https://docs.aws.amazon.com/app-mesh/latest/userguide/getting-started-kubernetes.html) and not the underlying AWS resource.
It looks like you would have to use `kubectl` to manage the mesh lifecycle in this case, not `terraform`.
