### ISSUE TITLE
servicecatalog: Default waiter timeouts of 30 minutes are not long enough to provision a product

### ISSUE THREAD

**Issue by DCAL12** [hashicorp/terraform-provider-aws#20808]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.56.0

### Affected Resource(s)

* aws_servicecatalog_provisioned_product

### Terraform Configuration Files
I'm unable to share config files due to some manual Control Tower setup, however this is nearly identical to Issue #20253. Like this issue, I have a Service Catalog product that provisions an AWS account using AWS Control Tower-generated CloudFormation. This provisioning takes longer than 30 minutes due to several CloudFormation Templates used to provision new accounts.

```hcl
resource "aws_servicecatalog_provisioned_product" "account" {
  name                       = "Test-Account-Create"
  product_name               = "AWS Control Tower Account Factory"
  provisioning_artifact_name = "AWS Control Tower Account Factory v1"

    provisioning_parameters {
        ...
    }
    ...
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Terraform waits for the user-specified time for the product to be provisioned before timing out.

### Actual Behavior

Terraform times out after 30 minutes. This value of 30 minutes is still hardcoded (increased from 3 minutes in PR #20254), but should be exposed as a parameter.

Output looks like:

    Error: error describing Service Catalog Provisioned Product (pp-xxxxxxxxxxxx): timeout while waiting for state to become 'AVAILABLE' (last state: 'UNDER CHANGE', timeout: 3m0s)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by dcloud9** [comment]
In `v3.58.0` the actual error that we hit is
```
│ Error: error describing Service Catalog Provisioned Product (pp-xxxxxxxxxxxx): timeout while waiting for state to become 'AVAILABLE' (last state: 'UNDER_CHANGE', timeout: 30m0s)
```

**Comment by DCAL12** [comment]
@ewbankkit, I agree with @dcloud9, this should be labeled a bug.
