### ISSUE TITLE
RDS Aurora: aws_rds_cluster_instance missing `performance_insights_retention_period` variable

### ISSUE THREAD

**Issue by Chainshark** [hashicorp/terraform-provider-aws#20816]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It is not clear to what resource in the AWS API the `aws_rds_cluster_instance` resource links to, but I can only assume it's `create-db-instance`. What is missing but is however present in `aws_db_instance` is the variable `performance_insights_retention_period` which is the barrier between free tier and paid tier which is of course very important.

### New or Affected Resource(s)

* aws_rds_cluster_instance

### Potential Terraform Configuration

```hcl
resource "aws_rds_cluster_instance" "cluster_instances" {
  count              = 2
  identifier         = "aurora-cluster-demo-${count.index}"
  cluster_identifier = aws_rds_cluster.default.id
  instance_class     = "db.r4.large"
  engine             = aws_rds_cluster.default.engine
  engine_version     = aws_rds_cluster.default.engine_version
  performance_insights_enabled = true
}
```
```hcl
resource "aws_rds_cluster_instance" "cluster_instances" {
  count              = 2
  identifier         = "aurora-cluster-demo-${count.index}"
  cluster_identifier = aws_rds_cluster.default.id
  instance_class     = "db.r4.large"
  engine             = aws_rds_cluster.default.engine
  engine_version     = aws_rds_cluster.default.engine_version
   performance_insights_enabled = true
   performance_insights_retention_period = 7 # or 731, only two values allowed.
}
```

**Comment by ewbankkit** [comment]
@Chainshark Thanks for raising this issue.
It has already been noticed in #9307. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
