### ISSUE TITLE
Add support for fixed versions for managed rules in WAFv2

### ISSUE THREAD

**Issue by dennis-grunert** [hashicorp/terraform-provider-aws#20817]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS recently added [versioning to WAFv2 rule groups](https://aws.amazon.com/about-aws/whats-new/2021/08/aws-waf-offers-managed-rule-group-versioning/). You either use the newest version of a rule group (default) or can fix a specific version for your ACL (wanted by this feature request).

Currently, everyone using AWS managed rules has not way in Terraform to prevent AWS from updating the underlying rules and possibly breaking the production environment. This feature will enable you to fix a specific version and later safely upgrade to a new version of the rule group on production when you have already tested it on another stage.

### New or Affected Resource(s)

* aws_wafv2_web_acl
* aws_wafv2_rule_group

### References

* [AWS What's New: AWS WAF now offers managed rule group versioning](https://aws.amazon.com/about-aws/whats-new/2021/08/aws-waf-offers-managed-rule-group-versioning/)
* [AWS Documentation: Version management for managed rule groups ](https://docs.aws.amazon.com/waf/latest/developerguide/waf-managed-rule-groups-versioning.html)

**Comment by galoitsu** [comment]
> New or Affected Resource(s)
> - aws_wafv2_web_acl
> - aws_wafv2_rule_group

Does this affect aws_wafv2_rule_group?
