### ISSUE TITLE
aws_docdb_cluster "unsupported attribute" error for documented attribute "maintenance_window".

### ISSUE THREAD

**Issue by 0mnius** [hashicorp/terraform-provider-aws#20829]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/aws v3.57.0

### Affected Resource(s)

* aws_docdb_cluster

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_docdb_cluster" "self" {
  cluster_identifier = var.cluster_identifier

  db_subnet_group_name = aws_docdb_subnet_group.self.name
  db_cluster_parameter_group_name = (
    var.use_default_cluster_parameter_group ?
    format("default.%s", var.family) :
    join("", aws_docdb_cluster_parameter_group.self[*].name)
  )
  vpc_security_group_ids       = var.cluster_security_groups
  engine                       = var.engine
  engine_version               = var.engine_version
  master_username              = var.master_username
  master_password              = var.master_password
  storage_encrypted            = var.storage_encrypted
  preferred_maintenance_window = var.preferred_maintenance_window
  backup_retention_period      = var.backup_retention_period
  preferred_backup_window      = var.preferred_backup_window
  skip_final_snapshot          = var.skip_final_snapshot

  apply_immediately = var.apply_immediately

  tags = var.tags

  lifecycle {
    ignore_changes = [
      tags["org:deploy:timestamp"]
    ]
  }
}

# output
output "node_endpoint_is_writeable" {
  value = formatlist("%s :: writeable=%s",
    aws_docdb_cluster_instance.self[*].endpoint,
    aws_docdb_cluster_instance.self[*].writer
  )
  description = <<-EOT
    The DNS address for this instance. May not be writable.
    Boolean indicating if this instance is writable. False indicates this instance is a read replica.
  EOT
}

output "maintenance_window" {
  value       = aws_docdb_cluster.self.maintenance_window
  description = "The instance maintenance window."
}
```

### Expected Behavior

Output requested attribute.

### Actual Behavior

```
Error: Unsupported attribute

  on ../../../modules/aws/documentdb/output.tf line 28, in output "maintenance_window":
  28:   value       = aws_docdb_cluster.self.maintenance_window

This object has no argument, nested block, or exported attribute named
"maintenance_window".
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @0mnius 👋 Thank you for opening this issue. On a quick glance over the documentation and provider, it seems like this may be a documentation issue where the attribute should instead be named `preferred_maintenance_window`. 

Can you test this and see if that provides the output that you were looking for?

**Comment by 0mnius** [comment]
Thank you @justinretzolk the `preferred_maintenance_window` works as expected! 👍🏿
