### ISSUE TITLE
Non-existent custom service endpoint definitions?

### ISSUE THREAD

**Issue by lorengordon** [hashicorp/terraform-provider-aws#20823]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
❯ terraform version
Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.57.0
```

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  endpoints {
    prometheusservice     = null
    codestarnotifications = null
  }
}

resource "aws_prometheus_workspace" "demo" {
  alias = "prometheus-test"
}

resource "aws_codecommit_repository" "code" {
  repository_name = "example-code-repo"
}

resource "aws_sns_topic" "notif" {
  name = "notification"
}

data "aws_iam_policy_document" "notif_access" {
  statement {
    actions = ["sns:Publish"]

    principals {
      type        = "Service"
      identifiers = ["codestar-notifications.amazonaws.com"]
    }

    resources = [aws_sns_topic.notif.arn]
  }
}

resource "aws_sns_topic_policy" "default" {
  arn    = aws_sns_topic.notif.arn
  policy = data.aws_iam_policy_document.notif_access.json
}

resource "aws_codestarnotifications_notification_rule" "commits" {
  detail_type    = "BASIC"
  event_type_ids = ["codecommit-repository-comments-on-commits"]

  name     = "example-code-repo-commits"
  resource = aws_codecommit_repository.code.arn

  target {
    address = aws_sns_topic.notif.arn
  }
}
```

### Description of Bug

I was working on a config where every [custom service endpoint](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/custom-service-endpoints#available-endpoint-customizations) is present in the provider config, using a map to lookup the [FIPS endpoint](https://aws.amazon.com/compliance/fips/#FIPS_Endpoints_by_Service), read from a file. If not present, the endpoint value is `null` to use the default. This works fine for every service except two: `prometheusservice` and `codestarnotifications `. For these two, I get an error that the "Argument named <service> is not expected here."

### Actual Behavior

```
❯ terraform plan
╷
│ Error: Unsupported argument
│
│   on main.tf line 3, in provider "aws":
│    3:     prometheusservice     = null
│
│ An argument named "prometheusservice" is not expected here.
╵
╷
│ Error: Unsupported argument
│
│   on main.tf line 4, in provider "aws":
│    4:     codestarnotifications = null
│
│ An argument named "codestarnotifications" is not expected here.
╵
```

### Steps to Reproduce

1. `terraform plan`

**Comment by YakDriver** [comment]
This is all moved now to `internal/conns/conns.go` and should be resolved soon.
