### ISSUE TITLE
AWS RDS aurora cluster / instance - param DeleteAutomatedBackups

### ISSUE THREAD

**Issue by HL-POST-CH** [hashicorp/terraform-provider-aws#20839]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS RDS aurora cluster / instance - param DeleteAutomatedBackups

Hi all
We dont want to delete all automatic snapshots after a rds aurora cluster is destroyed via tfe.

AWS api: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds.html#RDS.Client.delete_db_instance

Can you please check the api request and implement the param DeleteAutomatedBackups?
The default is to remove automated backups immediately after the DB instance is deleted.

I found the function in tf in row 617:
https://github.com/hashicorp/terraform-provider-aws/blob/4eb1bd13d47943e1ed98b1151c8effa1c589e33b/aws/resource_aws_rds_cluster_instance.go

Kind regards, Hannes

### New or Affected Resource(s)

* aws_rds_cluster
* aws_rds_cluster_instance

**Comment by morganchristiansson** [comment]
Hi all.

Deleting all system snapshots is very bad behavior. It's not documented and there is no option to keep snapshots.

`aws_db_instance` already has `delete_automated_snapshots = false` option but `aws_rds_cluster` does not.

**Comment by kaiyuanlim** [comment]
This is really bad... We need to have this param...

**Comment by OneBadSanta** [comment]
+1

**Comment by jfentontyro** [comment]
This issue has now worsened with the release of [AWS Backup Aurora continuous backup support](https://aws.amazon.com/about-aws/whats-new/2023/09/aws-backup-amazon-aurora-continuous-backup/)

After enabling continuous backups for an aurora cluster, we cannot delete the cluster as there is no way to retain the backup vaults continuous backup through terraform. Simply being forced to delete automated backups is now not an option

Steps to recreate:
 - Create a cluster
 - Create a backup plan with a backup rule enabling continuous backups
 - Wait for backup plan to run and the continuous recovery point to appear in the vault
 - Attempt cluster deletion


Example failure response:
`InvalidParameterCombination:` RDS cluster x is associated with the following AwsBackupRecoveryPointArn: arn:aws:backup:x:x:recovery-point:continuous:cluster-xyz. NoDeleteAutomatedBackups must be specified. For more details, see the AWS Backup documentation.`


We need an rds_cluster version of `delete_automated_snapshots = false` to be able to delete the terraform managed clusters

**Comment by xiaxuantan** [comment]
bumped. I think this behavior is really bad.

**Comment by ktomaszx** [comment]
Is there any change it will be added in near future? 
This is so important to have snapshots after cluster deletion.
