### ISSUE TITLE
AWS Config: Add Support During Log Delivery for KMS Keys

### ISSUE THREAD

**Issue by ScottFinlaysonGMSL** [hashicorp/terraform-provider-aws#20836]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS config has added support for using KMS keys to encrypt logs delivered to S3 Currently terraform doesn't support use of a KMS key meaning that all logs are encrypted using SSE-S3.

### New or Affected Resource(s)

* aws_config_delivery_channel

### Potential Terraform Configuration

```hcl
resource aws_config_delivery_channel delivery {
  ...
  s3_key_arn = "key_arn"
  ...
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2021/02/support-for-kms-encryption-on-s3-buckets-used-by-aws-config/
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_delivery_channel

**Comment by ewbankkit** [comment]
@ScottFinlaysonGMSL Thanks for raising this issue.
It has already been noticed in #20600. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by ScottFinlaysonGMSL** [comment]
Ah apologies. I had searched but somehow didn't come across that one, thanks!
