### ISSUE TITLE
Add support for include filters in AWS DataSync task

### ISSUE THREAD

**Issue by shuichiro-makigaki** [hashicorp/terraform-provider-aws#20849]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS DataSync task supports include filters as well as exclude filters.

This enhancement enables us to have greater control over how data is transferred.  Additionally, we can queue multiple executions of a task when the filter settings differ between executions.

### New or Affected Resource(s)

* aws_datasync_task

### Potential Terraform Configuration

```hcl
resource "aws_datasync_task" "sync_subset" {
  excludes {
    filter_type = "SIMPLE_PATTERN"
    value       = "/dir_A|/dir_B"
  }
  includes {
    filter_type = "SIMPLE_PATTERN"
    value       = "/dir_C|/dir_D"
  }
} 
```

### References

* https://aws.amazon.com/about-aws/whats-new/2021/08/aws-datasync-task-filtering-queuing/

**Comment by swiatek25** [comment]
Will that PR be included for the next release?

**Comment by matiu3** [comment]
Shurichiro's PR got approved, but never got merged, and now it's in conflict. I just stole Shuichiro's code and rebased it in the above PR. I hope the tests pass.
