### ISSUE TITLE
aws_wafv2_ip_set fails when addresses are not known until apply

### ISSUE THREAD

**Issue by nsmithuk** [hashicorp/terraform-provider-aws#20843]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```bash
terraform -v
Terraform v1.0.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.57.0
```

### Affected Resource(s)

* aws_wafv2_ip_set

### Terraform Configuration Files

Note - I've used an Elastic IP in the example, but this occurs whenever the IP address is originating from a resource that is not known until the apply.

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

provider "aws" {
  region = "eu-west-2"
}

resource "aws_default_vpc" "default" {}

resource "aws_eip" "example" {
  vpc = true
}

resource "aws_wafv2_ip_set" "example" {
  name               = "example"
  description        = "Example IP set"
  scope              = "REGIONAL"
  ip_address_version = "IPV4"
  addresses          = ["${aws_eip.example.public_ip}/32"]
}

```

### Debug Output

https://gist.github.com/nsmithuk/f51d17cd827885a8c8d4c37b7b0cdc26

### Expected Behavior

An instance of `aws_wafv2_ip_set` is created containing the public IP address of the Elastic IP on the first apply. Note - I've used an Elastic IP in the example, but this occurs whenever the IP address is originating from a resource that is not known until the apply.

### Actual Behavior

On the first apply Terraform fails with the following error:
```text
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for aws_wafv2_ip_set.example to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .addresses: was null, but now cty.SetVal([]cty.Value{cty.StringVal("18.169.222.244/32")}).
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

As the `aws_eip` was created successfully, on subsequent applies, the IP known and included in the plan, resulting in the apply finishing successfully.

### Steps to Reproduce

1. `terraform apply`

**Comment by ajorpheus** [comment]
While the bug in the downstream resource `aws_wafv2_ip_set` is being looked at, here is a workaround:

```
resource "aws_wafv2_ip_set" "aws_ip_addresses" {
  name               = "spp-aws-ip-addresses-${local.deployment_name}"
  description        = "AWS egress IP Addresses"
  scope              = "REGIONAL"
  ip_address_version = "IPV4"
  addresses          = [for ip in split(",", time_sleep.nat_gw.triggers["public_ips"]) : "${ip}/32"]
}

resource "time_sleep" "nat_gw" {
  create_duration = "60s"

  triggers = {
    public_ips = join(",", aws_nat_gateway.main[*].public_ip)
  }
}
```
