### ISSUE TITLE
EC2 Image Builder : ability to use component parameters

### ISSUE THREAD

**Issue by MacPower** [hashicorp/terraform-provider-aws#20855]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has released a new feature to image builder component : parameters. This is extremely useful for shareable templates.

### New or Affected Resource(s)

* aws_imagebuilder_image_recipe
* aws_imagebuilder_component

### Potential Terraform Configuration

Parameters of component could be pass like this : 

```hcl
resource "aws_imagebuilder_image_recipe" "this" {
  [...]
  component {
    component_arn = aws_imagebuilder_component.this.arn
    parameters = {
     "ParameterKey": "ParameterValue", 
     ....
   }
  }
[...]
}
```

### References

* https://aws.amazon.com/fr/about-aws/whats-new/2021/07/ec2-image-builder-supports-parameters-components-creating-custom-images/

**Comment by AmitArie** [comment]
Any updates regarding this PR?
We really need this feature :(
Thanks!

**Comment by kamilturek** [comment]
I am going to work on this.
