### ISSUE TITLE
Documentation doesnt specify that aws_availability_zone is required for creating cloudhsm

### ISSUE THREAD

**Issue by saraheckles** [hashicorp/terraform-provider-aws#20856]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_cloudhsm_v2_hsm
* aws_cloudhsm_v2_cluster

After successfully created a cloudhsm cluster we wanted to create the hsm card. The documentation only says cluster_id is required. Using the code in the documentation didn’t work. We went into the aws console to see what the initiation process looked like. There is a required field for setting aws_availability_zones. Once we added   
```
data "aws_availability_zones" "available" {
  state = "available"
}
```

The hsm card was able to initiate, and we could see the state as active in the console.

Please update the documentation to state that setting the AZ is required for initiating the hsm card.

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
me@me-m01 cloudhsm % terragrunt plan                        
aws_cloudhsm_v2_cluster.cloudhsm_v2_cluster: Refreshing state... [id=cluster-XXXXXXXX]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # aws_cloudhsm_v2_cluster.cloudhsm_v2_cluster will be updated in-place
  ~ resource "aws_cloudhsm_v2_cluster" "cloudhsm_v2_cluster" {
        id                   = "cluster-XXXXXX"
      ~ tags                 = {
          ~ "tg_modified_by" = "arn:aws:iam::942226307530:user/misty.hall" -> "arn:aws:iam::942226307530:user/sarah.eckles"
            # (2 unchanged elements hidden)
        }
      ~ tags_all             = {
          ~ "tg_modified_by" = "arn:aws:iam::942226307530:user/misty.hall" -> "arn:aws:iam::942226307530:user/sarah.eckles"
            # (2 unchanged elements hidden)
        }
        # (7 unchanged attributes hidden)
    }

  # aws_cloudhsm_v2_hsm.cloudhsm_v2_hsm will be created
  + resource "aws_cloudhsm_v2_hsm" "cloudhsm_v2_hsm" {
      + availability_zone = "us-east-1a"
      + cluster_id        = "cluster-XXXXXXXX"
      + hsm_eni_id        = (known after apply)
      + hsm_id            = (known after apply)
      + hsm_state         = (known after apply)
      + id                = (known after apply)
      + ip_address        = (known after apply)
      + subnet_id         = (known after apply)
    }

Plan: 1 to add, 1 to change, 0 to destroy.

```

### Steps to Reproduce

1. `terraform apply`

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudhsm_v2_hsm#cluster_id
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudhsm_v2_cluster
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/availability_zones

* #0000

**Comment by mattburgess** [comment]
It turns out that although `availability_zone` is required by the API, the provider enables you to specify a `subnet_id` instead, and it will then perform a lookup of the `availability_zone`. This, as you rightly pointed out, wasn't clear at all in the docs, but hopefully is from the linked PR.
