### ISSUE TITLE
After AWS change from AWS Elasticsearch Service to AWS Opensearch Service new aws_elasticsearch_domain resources can no longer be created

### ISSUE THREAD

**Issue by astjossem** [hashicorp/terraform-provider-aws#20854]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.11
AWS Provider v3.57.0

### Affected Resource(s)

aws_elasticsearch_domain

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_elasticsearch_domain" "main" {
  provider              = "aws.us-west-2"
  domain_name           = "${var.project}-${var.environment}"
  elasticsearch_version = "7.10"
  ebs_options {
    ebs_enabled = true
    volume_size = 10
  }
  cluster_config {
    instance_count         = 2
    instance_type          = "t2.medium.search"
    zone_awareness_enabled = false
  }
  advanced_options = {
    "rest.action.multi.allow_explicit_index" = true
  }
  vpc_options {
    security_group_ids = [
      aws_security_group.elasticsearch.id
    ]
    subnet_ids = [
      tolist(data.aws_subnet_ids.private.ids)[0]
    ]
  }
  snapshot_options {
    automated_snapshot_start_hour = 23
  }
}

resource "aws_elasticsearch_domain_policy" "main" {
  provider        = "aws.us-west-2"
  domain_name     = aws_elasticsearch_domain.main.domain_name
  access_policies = data.aws_iam_policy_document.domain_policy.json
}

data "aws_iam_policy_document" "domain_policy" {
  provider = "aws.us-west-2"
  statement {
    actions = [
      "es:*"
    ]

    resources = [
      aws_elasticsearch_domain.main.arn,
      "${aws_elasticsearch_domain.main.arn}/*"
    ]

    principals {
      identifiers = [
        aws_iam_role.role.arn
      ]
      type = "AWS"
    }
  }
}

resource "aws_security_group" "elasticsearch" {
  provider    = "aws.us-west-2"
  name        = "${var.project}-${var.environment}-elasticsearch-sg"
  description = "Managed by Terraform"
  vpc_id      = data.aws_vpc.main.id
}

resource "aws_security_group_rule" "elasticsearch" {
  provider          = "aws.us-west-2"
  security_group_id = aws_security_group.elasticsearch.id
  type              = "ingress"
  from_port         = 443
  to_port           = 443
  protocol          = "TCP"
  cidr_blocks = [
    data.aws_vpc.main.cidr_block
  ]
}

data "aws_vpc" "main" {
  provider = "aws.us-west-2"
  tags = {
    Name = "test"
  }
}

data "aws_subnet_ids" "private" {
  provider = "aws.us-west-2"
  vpc_id   = data.aws_vpc.main.id

  tags = {
    Public = "false"
  }
}
```

### Debug Output

Error: Error creating ElasticSearch domain: ValidationException: 1 validation error detected: Value 't2.medium.search' at 'elasticsearchClusterConfig.instanceType' failed to satisfy constraint: Member must satisfy enum value set: [r6gd.12xlarge.elasticsearch, i3.2xlarge.elasticsearch, ultrawarm1.xlarge.elasticsearch, m5.4xlarge.elasticsearch, t3.xlarge.elasticsearch, m6g.xlarge.elasticsearch, i3.4xlarge.elasticsearch, m3.large.elasticsearch, m6g.12xlarge.elasticsearch, r4.16xlarge.elasticsearch, t2.micro.elasticsearch, m4.large.elasticsearch, r6gd.16xlarge.elasticsearch, d2.2xlarge.elasticsearch, t3.micro.elasticsearch, m5.large.elasticsearch, i3.8xlarge.elasticsearch, i3.large.elasticsearch, d2.4xlarge.elasticsearch, t2.small.elasticsearch, c4.2xlarge.elasticsearch, t3.small.elasticsearch, c5.2xlarge.elasticsearch, c4.4xlarge.elasticsearch, c6g.2xlarge.elasticsearch, d2.8xlarge.elasticsearch, c5.4xlarge.elasticsearch, t4g.medium.elasticsearch, c6g.4xlarge.elasticsearch, c6g.xlarge.elasticsearch, m3.medium.elasticsearch, c6g.12xlarge.elasticsearch, c4.8xlarge.elasticsearch, c4.large.elasticsearch, c5.xlarge.elasticsearch, c5.large.elasticsearch, t4g.small.elasticsearch, c4.xlarge.elasticsearch, c5.9xlarge.elasticsearch, c6g.8xlarge.elasticsearch, c6g.large.elasticsearch, d2.xlarge.elasticsearch, ultrawarm1.medium.elasticsearch, t3.nano.elasticsearch, t3.medium.elasticsearch, m6g.2xlarge.elasticsearch, t2.medium.elasticsearch, t3.2xlarge.elasticsearch, c5.18xlarge.elasticsearch, m6g.4xlarge.elasticsearch, i3.xlarge.elasticsearch, r6gd.2xlarge.elasticsearch, i2.xlarge.elasticsearch, r3.2xlarge.elasticsearch, r4.2xlarge.elasticsearch, m5.xlarge.elasticsearch, m4.10xlarge.elasticsearch, r6gd.4xlarge.elasticsearch, r6g.2xlarge.elasticsearch, r3.4xlarge.elasticsearch, r5.2xlarge.elasticsearch, m5.12xlarge.elasticsearch, m4.xlarge.elasticsearch, m6g.8xlarge.elasticsearch, m6g.large.elasticsearch, r4.4xlarge.elasticsearch, m5.24xlarge.elasticsearch, m3.xlarge.elasticsearch, r6g.4xlarge.elasticsearch, i3.16xlarge.elasticsearch, t3.large.elasticsearch, r5.4xlarge.elasticsearch, ultrawarm1.large.elasticsearch, m3.2xlarge.elasticsearch, r6gd.8xlarge.elasticsearch, r6gd.large.elasticsearch, r6g.xlarge.elasticsearch, r3.8xlarge.elasticsearch, r3.large.elasticsearch, r5.xlarge.elasticsearch, m4.2xlarge.elasticsearch, r6g.12xlarge.elasticsearch, r4.8xlarge.elasticsearch, r4.xlarge.elasticsearch, r4.large.elasticsearch, r5.12xlarge.elasticsearch, m5.2xlarge.elasticsearch, r6gd.xlarge.elasticsearch, r6g.8xlarge.elasticsearch, r6g.large.elasticsearch, i2.2xlarge.elasticsearch, r3.xlarge.elasticsearch, r5.24xlarge.elasticsearch, r5.large.elasticsearch, m4.4xlarge.elasticsearch]

  on es.tf line 5, in resource "aws_elasticsearch_domain" "main":
   5: resource "aws_elasticsearch_domain" "main" {

### Expected Behavior

The aws_elasticsearch_domain resource should be created

### Actual Behavior

Terraform apply errored out.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

On September 7th, 2021 AWS changed the name of the service from Amazon Elasticsearch Service to Amazon OpenSearch Service.  Accompanying this change they altered the name of the instance types used for these clusters from something like `t2.medium.elasticsearch` to `t2.medium.search`.  When I specify the instance type (correctly) as the later I get the above error, when I specify the former I get the below error. 

 Error creating ElasticSearch domain: ValidationException: The specified instance type t2.medium is not available for the AZ(s): [us-west-2d]. If your domain is already using this instance type, consider moving to other available instance types.

  on es.tf line 5, in resource "aws_elasticsearch_domain" "main":
   5: resource "aws_elasticsearch_domain" "main" {
   
   
 It seems like there is currently no way to create a new aws_elasticsearch_domain resource.

### References

https://aws.amazon.com/opensearch-service/faqs/

* #0000

**Comment by ewbankkit** [comment]
@astjossem Thanks for raising this issue.
Yes, as you have noticed, for the `aws_elasticsearch_domain` resource the `a.b.elasticsearch` instance types should be specified. Our documentation could be updated on this.
The `us-west-2d` AZ is notorious for having limited instance type availability - Could you please try another instance type?

**Comment by astjossem** [comment]
I confirmed that a different instance type works in `us-west-2d` for `a.b.elasticsearch` instance types, that will get me unstuck for now, thank you.

The other issue that still persists are the instance types of type `a.b.search`  I notice that currently in the AWS console these are the only options when creating a new domain.  I would then expect Terraform to allow those instance types as well.  Unless I am missing something obvious there.

**Comment by ewbankkit** [comment]
@astjossem Thanks for verifying that.
TBH we haven't really thought about how to handle `elasticsearch` vs. `opensearch` yet.
There is a newly opened issue - #20853 - where comments and upvotes will help drive design and prioritization.
