### ISSUE TITLE
terraform detects changes on apply on volume tags even when there are none

### ISSUE THREAD

**Issue by valugi** [hashicorp/terraform-provider-aws#20852]
It happens with the latest 1.0.6 version.
The introspection does not work and it detects changes even though there are none.

```
Terraform will perform the following actions:

  # module.bamboo.aws_instance.this[0] will be updated in-place
  ~ resource "aws_instance" "this" {
        id                                   = "i-xxxxx"
        tags                                 = {
            "Company"          = "SOME"
            "CompanyShort"     = "ENVI"
            "Environment"      = "Production"
            "EnvironmentShort" = "PRD"
            "Name"             = "ENVI-DSO-PRD-Bamboo"
            "Project"          = "DevSecOps"
            "ProjectShort"     = "DSO"
            "TerraformManaged" = "yes"
        }
      ~ volume_tags                          = {
          - "Company"          = "SOME" -> null
          - "CompanyShort"     = "ENVI" -> null
          - "Environment"      = "Production" -> null
          - "EnvironmentShort" = "PRD" -> null
          - "Project"          = "DevSecOps" -> null
          - "ProjectShort"     = "DSO" -> null
            # (1 unchanged element hidden)
```
on the next run the gats are applied correctly back.
Though the message is about the aws_instance, the tags that are changed are on EBS volume attached to the instance. The instance tags stay correct.

Using this module to create the instance.

```
  source  = "terraform-aws-modules/ec2-instance/aws"
  version = "3.1.0"
```

**Comment by kamilturek** [comment]
I could not reproduce the issue. Could you please provide the configuration file?

**Comment by valugi** [comment]
hi @kamilturek ,
Here is the relevant code.

`data "aws_ami" "base_centos7" {
  owners      = [var.account]
  most_recent = true
  filter {
    name   = "name"
    values = ["*TEST-*"]
  }
  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

module "bamboo" {
  source  = "terraform-aws-modules/ec2-instance/aws"
  version = "3.1.0"

  name = "bamboo8"

  ami           = data.aws_ami.base_centos7.id
  instance_type = "t2.xlarge"
  root_block_device = [
    {
      encrypted   = true
      volume_size = 40
    },
  ]
  key_name   = var.key_name
  monitoring = true
  subnet_id  = module.vpc.private_subnets[0]
  vpc_security_group_ids = [
    aws_security_group.remote_access_sg.id,
    aws_security_group.internal_access_sg.id,
    module.vpc.default_security_group.id
  ]
  user_data = file("./files/ebs_mount.sh")
  tags = {
    Name             = join("-", [var.companyShort, var.projectShort, var.environmentShort, "Bamboo"])
    Company          = var.company
    Project          = var.project
    Environment      = var.environment
    CompanyShort     = var.companyShort
    ProjectShort     = var.projectShort
    EnvironmentShort = var.environmentShort
    TerraformManaged = "yes"
  }
}


resource "aws_ebs_volume" "bamboo_volume" {
  availability_zone = var.availability_zones[0]
  encrypted         = true
  iops              = 4000
  size              = 100
  type              = "io1"
  tags = {
    Name             = join("-", [var.companyShort, var.projectShort, var.environmentShort, "Volume-Bamboo"])
    Company          = var.company
    Project          = var.project
    Environment      = var.environment
    CompanyShort     = var.companyShort
    ProjectShort     = var.projectShort
    EnvironmentShort = var.environmentShort
  }
}

resource "aws_volume_attachment" "bamboo_vol_att" {
  device_name = "/dev/sdb"
  volume_id   = aws_ebs_volume.bamboo_volume.id
  instance_id = module.bamboo.id
}
`
The backend is S3 bucket.
`terraform {
  backend "s3" {
    bucket  = "eu-west-1-test-terraform-state"
    key     = "testterraform.tfstate"
    region  = "eu-west-1"
    profile = "test"
    encrypt = true
  }

  required_version = ">= 1.0.5"
}

provider "aws" {
  region  = var.region
  profile = var.profile
}`

Let me know your thoughts.
Regards

**Comment by jlosito** [comment]
I was able to work around this issue by adding a block similar to below since I do not happen to use `volume_tags` in neither the `aws_instance` nor `aws_ebs_volume` resources. I use the regular `tags` in both resources.
```
resource "aws_instance" "my_instance" {
...
tags {
  tag1 = "some_tag1"
  ...
}
lifecycle {
  ignore_changes = [
    volume_tags
  ]
}
}
```
