### ISSUE TITLE
aws_elasticsearch_domain: opensearch support

### ISSUE THREAD

**Issue by aviau** [hashicorp/terraform-provider-aws#20853]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

OpenSearch was now released. The terraform module could consider renaming resources.

Also, OpenSearch supports an `Enable compatibility mode` option. This should probably be exposed from the module.

### New or Affected Resource(s)

* aws_elasticsearch_domain

**Comment by joshedneyaerian** [comment]
Any movement or ETA on this feature request ?

**Comment by mqchau** [comment]
FWIW, I upgrade terraform-provider-aws to version 3.60 and was able to use string `OpenSearch_1.0` in the field of `elasticsearch_version`. 

PR to support OpenSearch in aws-sdk-go: https://github.com/aws/aws-sdk-go/pull/4101

The PR to pull version 1.45 of aws-sdk-go into terraform-provider-aws: https://github.com/hashicorp/terraform-provider-aws/pull/20975

**Comment by mqchau** [comment]
In terms of `Enable compatibility mode` option, I haven't tried this yet but I think you can add

```
resource "aws_elasticsearch_domain" "es" {
  ...
  advanced_options = {
    "override_main_response_version" = "true"
  }
}
```

Source: 
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain#advanced_options
- https://docs.aws.amazon.com/opensearch-service/latest/developerguide/rename.html#rename-upgrade

**Comment by palmajano** [comment]
> FWIW, I upgrade terraform-provider-aws to version 3.60 and was able to use string `OpenSearch_1.0` in the field of `elasticsearch_version`.

3.57 also works upgrading with string OpenSearch_1.0

**Comment by mqchau** [comment]
I'm still using ElasticSearch 7.10 and not OpenSearch 1.0 because of cross cluster replication. But I tried to create a new OpenSearch 1.0 cluster like this

```
provider "aws" {
  region              = "us-west-2"
}

terraform {
  required_version = "1.0.7"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.63.0"
    }
  }
}

resource "aws_elasticsearch_domain" "search_engine_2" {
  domain_name = "test-opensearch"

  elasticsearch_version = "OpenSearch_1.0"

  cluster_config {
    instance_type            = "t3.medium.elasticsearch"
    instance_count           = 1
    dedicated_master_enabled = false
    zone_awareness_enabled = false
  }

  ebs_options {
    volume_size = 50
    volume_type = "gp2"
    ebs_enabled = true
  }

  snapshot_options {
    automated_snapshot_start_hour = 23
  }

  advanced_options = {
    "override_main_response_version" = "true"
  }
}
```

I was able to run `terraform apply` on it

**Comment by Sebor** [comment]
With upgrade from elasticseaarch it is not working either

**Comment by Gowiem** [comment]
Just wanted to highlight that this issue of not supporting `override_main_response_version` as an advanced option blocks a workaround to a perpetual drift issue within the provider as well #21318. Ideally that advanced option would be supported by the `v3.x` provider so this isn't a "wait until 4.x and deal with the upgrade" type of thing.

**Comment by nnovaes** [comment]
Would closing #20433 be sufficient to allow an upgrade to 1.x via terraform or support for this needs to be added specifically for aws opensearch?

**Comment by tmccombs** [comment]
the opensearch API is avaliable in v1 as well: https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.42.33/service/opensearchservice

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

**Comment by YakDriver** [comment]
There are several problems with adding OpenSearch support to the existing Elasticsearch resources in TF AWS provider:

* It looks sort of wonky to have AWS console & docs be predominantly OpenSearch but TF AWS provider being all Elasticsearch
* There are enough differences that it's not clean to simply add the functionality. _E.g._, Elasticsearch versions are `6.9`, `7.1` while OpenSearch versions are `OpenSearch_1.1`, `Elasticsearch_6.9`, `Elasticsearch_7.1`. It's also called `engine_version` now instead of `elasticsearch_version`.
* From a practitioner perspective, ARNs, endpoints, policies are different. AWS makes these backward-compatible mostly but that may change if/when Elasticsearch is deprecated as a service and absorbed by OpenSearch.

We can avoid breaking changes and support OpenSearch by simply following AWS's lead and re-implementing the Elasticsearch service as the OpenSearch service (see #23902). Resources will be named correctly, and the structural changes are not a problem with new resources. It will be clear to practitioners that they are using the OpenSearch service and can, within that, use Elasticsearch or OpenSearch, with the appropriate ARNs, endpoints, and policies.

**Comment by tmccombs** [comment]
That seems like the right move to me as well. Thanks for making PR for that @YakDriver

**Comment by lizsnyder** [comment]
And here are the OpenSearch-specific docs: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearch_domain
