### ISSUE TITLE
Add `dns_name` argument to the `aws_lb` data source

### ISSUE THREAD

**Issue by jeffreymlewis** [hashicorp/terraform-provider-aws#20862]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like to use the `aws_lb` data source to lookup Load Balancer metadata by a load balancer DNS name like the following.

```
2134123412341234213432khke721he7-1234567890.us-east-1.elb.amazonaws.com
```

### New or Affected Resource(s)

* aws_lb

### Potential Terraform Configuration

```hcl
variable "lb_arn" {
  type    = string
  default = ""
}

variable "lb_name" {
  type    = string
  default = ""
}

variable "lb_dns_name" {
  type    = string
  default = ""
}

data "aws_lb" "test" {
  arn      = var.lb_arn
  name     = var.lb_name
  dns_name = var.lb_dns_name
}
```

**Comment by kamilturek** [comment]
I am afraid that ELB API does not allow to use DNS name as a parameter.
https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_DescribeLoadBalancers.html
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2#DescribeLoadBalancersInput
