### ISSUE TITLE
Supports for multiple values in the same key on resource_tags attribute of aws_fms_policy

### ISSUE THREAD

**Issue by fabioviana-hotmart** [hashicorp/terraform-provider-aws#20872]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I've used fms for automate our waf acl policies and now I need to define an isolated policy for some application. My ALBs have a tag named "application" and I've tried to use the resource_tags with a combined values, but resource_tags is a map of string and I can't define the same key with multiple values. On AWS Console it works, there I can define the same key with many different values. The resource_tags would support a map of objects.

### New or Affected Resource(s)

* aws_fms_policy

### Potential Terraform Configuration

```hcl
resource "aws_fms_policy" "policy" {
  name = "policy-test"
  exclude_resource_tags = false
  resource_tags = {
    application = ["app1", "app2"]
    other_tag = "value"
  }
...
}
```

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.10
provider registry.terraform.io/hashicorp/aws v3.58.0

**Comment by zepjedi** [comment]
Has there been any movement on this issue? I am running into this same blocker.
