### ISSUE TITLE
Improve Storage gateway smb file share documentation for valid_user_list  argument

### ISSUE THREAD

**Issue by qfaure** [hashicorp/terraform-provider-aws#20880]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Improve documentation for valid_user_list  argument. Documentation don't explain how to add an Active Directory group in the valid_user_list  argument.

In order to be able to add a group with terraform specify an "@" before the name of the group.

### New or Affected Resource(s)

* aws_storagegateway_smb_file_share

### Potential Terraform Configuration

```hcl
  valid_user_list = ["qfaure"] // Way to specify only Active directory User
  valid_user_list = ["@MY-ACTIVE-DIRECTORY-GROUP"] // Way to specify an Active directory Group
```

**Comment by ewbankkit** [comment]
Closes via #20881.
