### ISSUE TITLE
aws_eks_node_group support IMDS best practices

### ISSUE THREAD

**Issue by kcentralsquare** [hashicorp/terraform-provider-aws#20888]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Update the aws_eks_node_group resource to support restricting access to node IAM role according to best practices issued by Amazon (link below). Entails updating launch template metadata with the following settings:

* Metadata accessible – Enabled
* Metadata version – V2 only (token required)
* Metadata response hop limit – 1

### New or Affected Resource(s)

* aws_eks_node_group

### Potential Terraform Configuration

```hcl
resource "aws_eks_node_group" "this" {
  cluster_name    = var.cluster_name
  node_group_name = var.node_group_name
  restrict_imds = true #Sets the properties specified in description
}
```

### References

* https://docs.aws.amazon.com/eks/latest/userguide/best-practices-security.html

**Comment by mattburgess** [comment]
Is this not already possible with the existing `aws_launch_template` [resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#metadata-options), e.g.:

```
resource "aws_launch_template" "foo" {
  name = "foo"
  ...
  metadata_options {
    http_endpoint               = "enabled"
    http_tokens                 = "required"
    http_put_response_hop_limit = 1
  }
  ...
}

resource "aws_eks_node_group" "bar" {
  cluster_name = var.cluster_name
  ...
  launch_template {
    name = aws_launch_template.foo.name
    version = aws_launch_template.foo.latest_version
  }
  ...
}
```

**Comment by kcentralsquare** [comment]
If you create the launch template yourself, yes. If you're trying to use managed nodes with the default launch template you cannot modify it after creation (without some local-exec provisioners to run aws CLI).

**Comment by mattburgess** [comment]
I think your use case (of using the default launch template) is adequately covered by the docs you linked to which state that it's currently not possible to do that using anything other than `eksctl`, i.e. this provider, which uses the AWS Go SDK under the hood, has no ability to alter such clusters. I'd be amazed, given those docs, if the AWS CLI (which uses the AWS Python SDK under the hood) is able to make such alterations either.

Assuming you're unable to rebuild your existing cluster, I think that running local-exec provisioners to invoke `eksctl` is likely the least-worst option.

**Comment by gdavison** [comment]
Thank you for the suggestion, @kcentralsquare. The implementation of the AWS provider follows the AWS API closely. Since this isn't a parameter option for the AWS API calls to create EKS clusters, we won't be supporting it.

The documentation page you linked says that when using managed nodes with the default launch template, it is "[n]ot possible using any deployment method other than `eksctl`." As @mattburgess suggests, using `local-exec` might work in your use case. Using a custom Launch Template (using the resource [`launch_template`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template)) would definitely work, as well.
