### ISSUE TITLE
Support tags in aws_elasticache_subnet_group &  aws_iam_role_policy

### ISSUE THREAD

**Issue by arghaya** [hashicorp/terraform-provider-aws#20882]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Description**

Service quotas support tags, but the resource doesn't

New or Affected Resource(s)
aws_elasticache_subnet_group
aws_iam_role_policy

### Steps to Reproduce
```


$ terraform version
Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.36.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

$ terraform validate
│ Error: Unsupported argument
│ 
│   on elasticache/main.tf line 43, in resource "aws_elasticache_subnet_group" "elasticache_subnet_group":
│   43:   tags = {
│ 
│ An argument named "tags" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on vpc/main.tf line 387, in resource "aws_iam_role_policy" "vpcflowlogs":
│  387:   tags = {
│ 
│ An argument named "tags" is not expected here.
--->
```

**Comment by screwnet** [comment]
The **_default_tags_** assignment to provider allows tags to be applied to ElastiCache resources also, but a granular level of tagging is missing.

eg:
```
provider "aws" {
  region = var.aws-region
  default_tags {
    tags = var.aws-tags
  }
}
```

**Comment by ewbankkit** [comment]
@arghaya Thanks for raising this issue.

`tags` support for the `aws_elasticache_subnet_group` resources was added in [**v3.38.0** of the Terraform AWS Provider](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3380-april-30-2021).

The `aws_iam_role_policy` resource does not support tagging as the [AWS IAM API does not support it](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags.html). The corresponding `aws_iam_role` can be tagged.
