### ISSUE TITLE
 AWS Lightsail + Userdata Issue

### ISSUE THREAD

**Issue by jmurillo9** [hashicorp/terraform-provider-aws#20909]
### Terraform Version
```bash
[njdevils9@laptop]$ terraform version
Terraform v0.13.6
+ provider registry.terraform.io/hashicorp/aws v3.58.0

Your version of Terraform is out of date! The latest version
is 1.0.6. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files
```terraform
resource "aws_lightsail_instance" "this" {
  depends_on = [
    aws_lightsail_key_pair.this
  ]

  name = var.name
  key_pair_name = aws_lightsail_key_pair.this.id
  user_data = var.user_data

  availability_zone = "us-east-1a"
  blueprint_id      = var.blueprint_id
  bundle_id         = var.bundle_id
}
```
### Expected Behavior
My custom user_data script will run. 

### Actual Behavior
I run `terraform plan --var-file tfvars/dev.tfvars` && `terraform apply --var-file tfvars/dev.tfvars --auto-approve` , the AWS Lightsail instance launches successfully. I login and notice that my custom user_data script did **not** run. 

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan --var-file tfvars/dev.tfvars`
2. `terraform apply --var-file tfvars/dev.tfvars`

### Additional Context
My custom user_data script does **not** run. 

I have tried:
`user_data = file("${path.module}/etc/userdata.sh")`
`user_data = templatefile("${path.module}/userdata.sh")`
`user_data = file("./etc/userdata.sh")`

I can see the `terraform plan` output show that it's reading my `userdata.sh` script but when I actually SSH into my AWS Lightsail WordPress instance, I see nothing in the logs. 

`/var/log/cloud-init.log`
`/var/log/cloud-init-output.log`
`/var/log/messages`
`/var/log/syslog`

I can `grep` for a string/pattern from my userdata and it will output 3 log files but I don't see anything actually in the files... 
```[root@aws_lightsail_instance]$ grep -ril 'TEST' /var/log/*
/var/log/cloud-init.log
/var/log/daemon.log
/var/log/syslog
```

If I manually create a new Lightsail instance from the AWS console and inject my own user_data script, everything works as expected.

**Comment by boydhako** [comment]
Any thing new with this? Work arounds? I'm getting the same issue. Doing the following works to a certain extent. If you try to create files or run the wp wordpress command nothing happens. Can't tell what user the stuff is being run as either.

```
user_date = <<EOF
apt update
EOF
```

**Comment by brittandeyoung** [comment]
@boydhako and @jmurillo9 

I started to take a look at this issue. From my testing, it appears that lightsail and EC2 handle user data very differently. 

EC2 will accept a base64 encoded script, but Lightsail only accepts a single line string. 

That means that the below configuration works:

```
resource "aws_lightsail_instance" "custom" {
  name              = "custom"
  availability_zone = "us-east-1b"
  blueprint_id      = "amazon_linux_2"
  bundle_id         = "nano_1_0"
  user_data         = "sudo yum install -y httpd && echo '<h1>Deployed via Terraform</h1>' | sudo tee /var/www/html/index.html"
  tags = {
    foo = "bar"
  }
}
``` 

While this configuration will not work: 

```
resource "aws_lightsail_instance" "custom" {
  name              = "custom"
  availability_zone = "us-east-1b"
  blueprint_id      = "amazon_linux_2"
  bundle_id         = "nano_1_0"
  user_data         = <<EOT
#! /bin/bash
sudo yum install -y httpd
echo "<h1>Deployed via Terraform</h1>" | sudo tee /var/www/html/index.html
EOT
  tags = {
    foo = "bar"
  }
}
```


I Will be opening a PR to to the Docs to provide an example and specify the limitations of lightsail userdata.
