### ISSUE TITLE
terraform state for imagebuilder resources is out-of-sync with AWS

### ISSUE THREAD

**Issue by cabutlermit** [hashicorp/terraform-provider-aws#20902]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.x (tried 1.0.2, 1.0.4, 1.0.6)
AWS Provider 3.58.0 (also tried earlier versions back to 3.40.0)

### Affected Resource(s)

* aws_imagebuilder_infrastructure_configuration
* aws_imagebuilder_image_recipe

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_imagebuilder_infrastructure_configuration" "config_infra" {
  name                          = "baseimage-infra"
  description                   = "baseimage infrastructure configuration"
  instance_profile_name         = EC2InstanceProfileForImagebuilder
  instance_types                = [ "m5.large" ]
  terminate_instance_on_failure = true
  resource_tags = {
    "terraform" : "true"
  }
  tags = {
    "terraform" : "true"
  }
}

resource "aws_imagebuilder_image_recipe" "image_recipe" {
  block_device_mapping {
    device_name = "/dev/sda1"
    ebs {
      delete_on_termination = true
      volume_size           = 8
      volume_type           = "gp2"
    }
    no_device = false
  }

  component {
    component_arn = "arn:aws:imagebuilder:us-east-1:aws:component/aws-cli-version-2-linux/1.0.0/1"
  }
  component {
    component_arn = "arn:aws:imagebuilder:us-east-1:aws:component/update-linux/1.0.0/1"
  }
  component {
    component_arn = "arn:aws:imagebuilder:us-east-1:aws:component/reboot-test-linux/1.0.0/1"
  }

  name              = baseimage
  description       = "Recipe for baseimage without custom Ansible."
  parent_image      = "arn:aws:imagebuilder:us-east-1:aws:image/ubuntu-server-20-lts-x86/x.x.x"
  working_directory = "/tmp"
  version           = 1.0.0
  tags              ={
    "terraform" : "true"
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

After running `terraform apply` the information in terraform state should match the information in AWS. That is, if I run `terraform plan` immediately after the `terraform apply` there should be no pending changes.

### Actual Behavior

A `terraform plan` immediately after the initial `terraform apply` results in

```bash
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # aws_imagebuilder_infrastructure_configuration.mitlib_infra has been changed
  ~ resource "aws_imagebuilder_infrastructure_configuration" "config_infra" {
        id                            = "arn:aws:imagebuilder:us-east-1:<xxxxxxxxxx>:infrastructure-configuration/baseimage-infra"
        name                          = "baseimage-infra"
      + security_group_ids            = []
        tags                          = {
            "terraform"   = "true"
        }
        # (8 unchanged attributes hidden)
    }
  # aws_imagebuilder_image_recipe.mitlib_recipe has been changed
  ~ resource "aws_imagebuilder_image_recipe" "image_recipe" {
        id                = "arn:aws:imagebuilder:us-east-1:<xxxxxxxxxx>:image-recipe/baseimage/1.0.0"
        name              = "baseimage"
        tags              = {
            "terraform"   = "true"
        }
        # (9 unchanged attributes hidden)

      + block_device_mapping {
          + device_name = "/dev/sda1"
          + no_device   = false

          + ebs {
              + delete_on_termination = "true"
              + iops                  = 0
              + volume_size           = 8
              + volume_type           = "gp2"
            }
        }
      - block_device_mapping {
          - device_name = "/dev/sda1" -> null
          - no_device   = false -> null

          - ebs {
              - delete_on_termination = "true" -> null
              - volume_size           = 8 -> null
              - volume_type           = "gp2" -> null
            }
        }

        # (4 unchanged blocks hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan` immediately and see that there are two changes that were made outside of Terraform.

### Important Factoids

I have tried to include `security_group_ids = []` in my `.tf` file, but when I do that, the `terraform apply` does NOT write that out to AWS or to the remote state. I have tried to include `iops = 0` (to match what AWS wants to do), but that causes `terraform apply` to throw an error that the value of `"0" is outside the expected range of 100 to 1000`.

### References

* #0000

**Comment by mattburgess** [comment]
Hey @cabutlermit - as I've recently been touching the ImageBuilder part of this provider I thought I'd take a look at this. I _think_ this might actually be an upstream [Terraform bug](https://github.com/hashicorp/terraform/issues/28803) rather than something specific to this provider, although I appreciate that probably doesn't help you very much. Reading the comments on that thread suggests that you might stumble across other resources that have similar issues! And, for what it's worth, I've also confirmed this bug is still present in Terraform-v1.1.6 with v4.2.0 of this provider. It'd be good if a Hashicorp dev could swing by and confirm my theory though.

**Comment by cabutlermit** [comment]
@mattburgess Thanks for the check-in. I have seen the [Terraform bug](https://github.com/hashicorp/terraform/issues/28803) you referenced and we have run into that problem with the [GitHub Provider](https://registry.terraform.io/providers/integrations/github/latest) and the [Terraform Cloud Provider](https://registry.terraform.io/providers/hashicorp/tfe/latest).

None of these are showstoppers, but they sure are annoying!
