### ISSUE TITLE
Provider ignore_tags shows in logs "will be updated in-place", but there is no change to be applied

### ISSUE THREAD

**Issue by franklinlevi** [hashicorp/terraform-provider-aws#20903]
I faced following issue and found similar issue was reported back in March https://github.com/hashicorp/terraform-provider-aws/issues/18068
I'm using "ignore_tags" in provider.tf. When there is no change on specific TAG which is part of Ignore_tags, the actual change on AWS resource is not applied, however in a log it shows that the change will take place and "will be updated in-place" will take place. On some resources it's a time consuming operation like EKS nodes
Please advise when this issue will be fixed?

provider.tf     has following code for ignore_tags:
  **ignore_tags {
    keys = ["Creator","launched_by"]
  }**

in the log I see following

Terraform will perform the following actions:

    # module.sg[0].aws_security_group.this[0] will be updated in-place
    ~ resource "aws_security_group" "this" {
          id                     = "sg-05430d455f92ddf15"
          name                   = "tagpr1-dev-EKS_app-sg"
        ~ tags                   = {
            + "Creator"          = "FRANKLINL"
              # (8 unchanged elements hidden)
          }
          # (8 unchanged attributes hidden)
      }

As mentioned the TAG on actual resource in AWS does not change, but in log terraform shows the change will take place and on some resources it is time consuming like EKS Nodes, etc
Please advise when this issue will be fixed?

**Comment by DiegoFlop** [comment]
I'm the same problem with tags generated by AWS backup.

This is my aws provider configuration:
~~~
provider "aws" {
  region = "eu-west-1"
  ignore_tags {
    keys = [
      "backup",
    ]

    key_prefixes = [
      "aws:",
      "FromInstance/",
    ]
  }
}
~~~
However when I try run "terraform plan", its detect changes in root device tags on ec2 instance
~~~
  # aws_instance.gitlab_ec2 will be updated in-place
  ~ resource "aws_instance" "XXX_ec2" {
...
...
      ~ root_block_device {
          ~ tags                  = {
              - "FromInstance/Environment"            = "XXXXX" -> null
              - "FromInstance/OS"                     = "XXXXX" -> null
              - "backup"                              = "XXXXX" -> null
            }
            # (8 unchanged attributes hidden)
        }
        # (4 unchanged blocks hidden)
    }
Plan: 0 to add, 1 to change, 0 to destroy.
~~~
Only I can bypass this problem when I add to resources  a lifecycle with:
~~~
  lifecycle {
    ignore_changes = [ root_block_device[0].tags ]
   }
~~~
This isn't any efficient for me

I would like that block root_block_device detect ignore_tags on provider block for exclude tags changes

It's curious that this problem only affect to block root_block_device but no ebs_block_device
