### ISSUE TITLE
Add support of rate_based_statement into aws_wafv2_rule_group

### ISSUE THREAD

**Issue by martialf** [hashicorp/terraform-provider-aws#20908]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The possibility to add rate based rule into a rule group has been added. The restriction lift is mentionned [in the doc history](https://docs.aws.amazon.com/waf/latest/developerguide/doc-history.html) and is not in [developper guide](https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-groups.html) anymore

I have successfully created a rule group with a rate based rule in the AWS console and also with the aws-cli, but I haven't tested the go sdk.

As the request has been asked by the community several times (#14326, #18573), it would be great to have it.

### New or Affected Resource(s)

* aws_wafv2_rule_group

### Potential Terraform Configuration

```hcl
resource "aws_wafv2_rule_group" "rule_group" {
  capacity = 10
  name     = "test-rule-group"
  scope    = "REGIONAL"

  rule {
    name     = "request-limit"
    priority = 1

    action {
      block {}
    }

    statement {
      rate_based_statement {
        limit              = 500
        aggregate_key_type = "IP"
      }
    }

    visibility_config {
      cloudwatch_metrics_enabled = false
      metric_name                = "request-limit"
      sampled_requests_enabled   = false
    }
  }
}
```

### References

* https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-groups.html
* https://docs.aws.amazon.com/waf/latest/developerguide/doc-history.html
* #14326
* #18573

**Comment by Aeternitaas** [comment]
Just hit this wall as well, we would really appreciate this being added :)
