### ISSUE TITLE
`aws_efs_file_system` add `transition_from_ia` `lifecycle_policy` 

### ISSUE THREAD

**Issue by Anticom** [hashicorp/terraform-provider-aws#20918]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add ability to specify a `transition_from_ia` lifecycle policy for efs file systems.

We can already configure a lifecycle policy to transition infrequently used files **to** IA but none to transition them back from IA to regular storage.

### New or Affected Resource(s)

* aws_efs_file_system

### Potential Terraform Configuration

```hcl
resource "aws_efs_file_system" "foo_with_lifecyle_policy" {
  creation_token = "my-product"

  lifecycle_policy {
    transition_to_ia   = "AFTER_30_DAYS"
    transition_from_ia = "ON_FIRST_ACCESS"
  }
}
```

### References

* https://docs.aws.amazon.com/efs/latest/ug/lifecycle-management-efs.html

**Comment by ewbankkit** [comment]
@Anticom Thanks for raising this issue.
It has already been noticed in #20773. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by Anticom** [comment]
@ewbankkit  I've searched through the issues but wasn't able to find this request already. Thanks for the dedupe.
