### ISSUE TITLE
Add support for OpenSearch (successor of ElasticSearch)

### ISSUE THREAD

**Issue by antonisnyc94** [hashicorp/terraform-provider-aws#20910]
AWS uses OpenSearch at the moment instead of ElasticSearch and i would like to install opensearch 1.0 using terraform

**Comment by justinretzolk** [comment]
Hi @antonisnyc94 👋 Thank you for making this suggestion! In order for us to most effectively track and triage this request, can you reopen it and fill out the feature request form?
