### ISSUE TITLE
Add Access option to aws_transfer_server for Internet Facing with VPC

### ISSUE THREAD

**Issue by lsacco-nutreense** [hashicorp/terraform-provider-aws#20927]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using this template to create an FTP server on AWS it defaults Access to "Internal" when using VPC. However, in the UI you can select "Internet Facing" and then choose an Elastic IP on the subnet for the given VPC. Can this option be added in the future?

### New or Affected Resource(s)

aws_transfer_server

### Potential Terraform Configuration

Suggested approach below with new items commented as `new option`.

```hcl
resource "aws_transfer_server" "my_aws_transfer_server" {
  #Protocols
  protocols   = ["FTPS"]
  certificate = var.acm_certificate_arn
  access      = "Internet Facing" # new option

  #Identity provider
  identity_provider_type = "API_GATEWAY"
  url                    = var.api_gateway_url
  invocation_role        = var.invocation_role_arn

  #Endpoint details
  endpoint_type = "VPC"
  endpoint_details {
    vpc_id             = module.globals.vpc_id
    subnet_ids         = var.public_subnets
    security_group_ids = [aws_security_group.ftp_sg.id]
    elastic_ips        = ["34.34.34.34", "34.44.44.44"] # new option
  }

  #Additional details
  logging_role         = var.logging_role_arn
  security_policy_name = var.security_policy_name

  #Tags
  tags = merge(local.common_tags, { Name = "${local.name_prefix}-subnet" })
}
```

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_server

**Comment by mewa** [comment]
Hey @lsacco-nutreense, at first glance I thought this is a problem as well, but it turns out it's already supported and all you have to do is specify [address_allocation_ids](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_server#address_allocation_ids) attribute.

See example below:

```hcl
# these are only public subnets
data "aws_subnet_ids" "this" {
  vpc_id = var.vpc_id
}

resource "aws_eip" "public_ip" {
  for_each = data.aws_subnet_ids.this.ids

  vpc = true
}

resource "aws_transfer_server" "this" {
  identity_provider_type = "SERVICE_MANAGED"

  security_policy_name = var.security_policy_name

  logging_role = var.logging_role_arn

  endpoint_type = "VPC"
  endpoint_details {
    address_allocation_ids = [for eip in aws_eip.public_ip: eip.id]
    security_group_ids     = var.security_group_ids
    subnet_ids             = data.aws_subnet_ids.this.ids
    vpc_id                 = var.vpc_id
  }

  tags = var.tags
}
```
