### ISSUE TITLE
Datasync Task: ARN account () must match authenticated user

### ISSUE THREAD

**Issue by AlexanderLahutsin** [hashicorp/terraform-provider-aws#20922]
Hello guys,

```
resource "aws_datasync_task" "example" {
  destination_location_arn = data.aws_s3_bucket.example.arn
  name   = "example"
  source_location_arn  = data.aws_efs_file_system.example.arn
}
```

```
│ Error: error creating DataSync Task: InvalidRequestException: Invalid parameter: ARN account () must match authenticated user.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "e***a"
│   },
│   ErrorCode: "InvalidParameter",
│   Message_: "Invalid parameter: ARN account () must match authenticated user."
│ }
```

Maybe this is not a bug, but Google does not say anything about it at all? Any ideas?
How can I understand the error and fix it? Thanks!

**Comment by DrFaust92** [comment]
Hi @AlexanderLahutsin you need to create datasync locations:

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/datasync_location_s3
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/datasync_location_efs
respectively for the above example
