### ISSUE TITLE
ECS Cluster ContainerInsights - Update-in-place

### ISSUE THREAD

**Issue by Guy-Rawsthorn** [hashicorp/terraform-provider-aws#20937]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform --version - v1.0.0
registry.terraform.io/hashicorp/aws - v 3.50.0

### Affected Resource(s)

aws_ecs_cluster

### Summary

My cluster has containerInsights enabled. I can verify this using this cli command
```
aws ecs describe-clusters --cluster abc-cluster --include SETTINGS --profile dev --region eu-west-2
```
Terraform believes this setting is not present and wants to update my cluster as shown below.

### Terraform Configuration Files

```hcl
resource "aws_ecs_cluster" "main" {
  name = "${var.environment}-cluster"

  setting {
    name  = "containerInsights"
    value = "enabled"
  }
}
```

### Expected Behavior

```
terraform plan
0 Infrastructure changes.
```

### Actual Behavior

```
terraform plan

# module.network_efs.aws_ecs_cluster.main will be updated in-place
~ resource "aws_ecs_cluster" "main" {
      id                 = "arn:aws:ecs:eu-west-2:11112222:cluster/abc-cluster"
      name               = "abc-cluster
      # (3 unchanged attributes hidden)

    + setting {
        + name  = "containerInsights"
        + value = "enabled"
      }
  }
```

###

**Comment by ziggythehamster** [comment]
This appears to be the same issue as #20684, due to an upstream change in the AWS API. [See this comment for specifics from an AWS support case.](https://github.com/hashicorp/terraform-provider-aws/issues/20684#issuecomment-908547640)

**Comment by Guy-Rawsthorn** [comment]
Thanks @ziggythehamster, I will look to upgrade my Terraform AWS Provider version to -  v3.57.0
