### ISSUE TITLE
Missing Audit Manager support

### ISSUE THREAD

**Issue by deejanu** [hashicorp/terraform-provider-aws#20930]
According to https://github.com/hashicorp/terraform-provider-aws/pull/18071 the support for AWS Audit Manager was released in version 3.33.0 of the Terraform AWS provider. I'm looking at latest version (3.58.0) and do not see AWS Audit Manager. Even the changelog for 3.33.0 does not mention AWS Audit Manager.

**Comment by breathingdust** [comment]
Hi @deejanu 👋 

#18071 does not cover the addition of the service, just the service client (a prerequisite for adding the service). The issue tracking the feature request is here: https://github.com/hashicorp/terraform-provider-aws/issues/17981 so please upvote if you'd like to see this in provider.

I'll close this in favor of #17981. Thanks!
