### ISSUE TITLE
New resource `aws_kafkaconnect_connector`

### ISSUE THREAD

**Issue by bryantbiggs** [hashicorp/terraform-provider-aws#20942]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Add new resource for provisioning Kafka connectors - requires upgrading aws-sdk-go to [at least v1.40.44](https://github.com/aws/aws-sdk-go/blob/main/CHANGELOG.md#service-client-updates)

### New or Affected Resource(s)

* `aws_kafkaconnect_connector`

### Potential Terraform Configuration

```hcl
resources "aws_kafkaconnect_connector" "example" {
	capacity = "..."
	connector_configuration = "..."
	connector_description = "..."
	connector_name = "..."
	kafka_clsuter = "..."
	kafka_cluster_client_authentication = "..."
	kafka_cluster_encryption_in_transit = "..."
	kafka_connect_version = "..."
	log_delivery = "..."
	plugins = ["..."]
	service_execution_role_arn = "..."
	worker_configuration = "..."
	tags = "..."
}
```

### References

* https://github.com/aws/aws-sdk-go/blob/main/service/kafkaconnect/api.go

**Comment by ewbankkit** [comment]
This new resource should likely be named `aws_kafkaconnect_connector` to match the underlying AWS API service ID.

**Comment by gouline** [comment]
Starting to look into implementing this. What's the thinking behind naming it `aws_kafkaconnect_connector` instead of keeping it consistent with existing `aws_msk_cluster` (whose underlying AWS API service ID is `kafka`) and going with `aws_msk_connector` or `aws_mskconnect_connector`?

**Comment by clocklear** [comment]
Any progress to report on this resource?  Happy to help out if necessary.

**Comment by chadlagore** [comment]
We won’t be working on this since we need a ConfigProvider and MSK connect doesn’t support it.

**Comment by rtim75** [comment]
I'm also starting to look into implementing this. Since the underlying API `kafkaconnect` is different from the `kafka` one which is represented as `msk` service, I think the `aws_mskconnect_` fits perfectly.

**Comment by gdavison** [comment]
Thanks for the supporting PRs, @rtim75. Are you still planning on implementing the `aws_kafkaconnect_connector` resource? If not, no worries.

**Comment by rtim75** [comment]
@gdavison  Yes, I'm writing `kafkaconnect_connector` in my free time. I can create a draft PR for it, if you'd like.

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

**Comment by chrismowbraybv** [comment]
Hey @breathingdust, thanks for the update! is the **Enhancements to Existing Services** in priority order? if thats the case, I guess it would be more towards the end of the quarter for this feature?
