### ISSUE TITLE
New bootstrap_brokers_attached_enis output for aws_msk_cluster

### ISSUE THREAD

**Issue by e-moshaya** [hashicorp/terraform-provider-aws#20940]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am Trying to integrate MSK with NLB for privatelink connectivity using the steps laid out [here](https://aws.amazon.com/blogs/big-data/how-goldman-sachs-builds-cross-account-connectivity-to-their-amazon-msk-clusters-with-aws-privatelink/). This requires me to add each Kafka broker ip address to the NLB target group. For that to work, I will need to get the attached eni id for each broker which is available in the AWS Console via the broker details section.

![image](https://user-images.githubusercontent.com/44640934/133787395-c2918d74-f8af-499d-a653-8edd582d015b.png)

### New or Affected Resource(s)

* aws_msk_list_nodes

### Potential Terraform Configuration

```hcl
resource "aws_msk_list_nodes" "example" {
  cluster_arn           = aws_msk_cluster.example.arn
}
```

### References

* https://aws.amazon.com/blogs/big-data/how-goldman-sachs-builds-cross-account-connectivity-to-their-amazon-msk-clusters-with-aws-privatelink/

**Comment by e-moshaya** [comment]
On second thoughts, I think the list nodes data resource is what we need. Here is the CLI equivalent https://docs.aws.amazon.com/cli/latest/reference/kafka/list-nodes.html

**Comment by ewbankkit** [comment]
@e-moshaya Thanks for raising this issue.
It has already been noticed in #11085. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
