### ISSUE TITLE
aws_cognito_user_pool lambda_config fails to delete

### ISSUE THREAD

**Issue by jrobison-sb** [hashicorp/terraform-provider-aws#20949]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.57.0
```

### Affected Resource(s)

* aws_cognito_user_pool

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```
resource "aws_cognito_user_pool" "foo" {
  lambda_config {
    pre_authentication = aws_lambda_function.preauthentication.arn
  }
  ...
}

```

### Expected Behavior

If you create the above resource with the `lambda_config` trigger, it will create as expected. If you subsequently delete or comment the lambda_trigger block, it should modify the resource and remove the lambda trigger.

### Actual Behavior

If you delete or comment the lambda_config block and run an apply, there are no changes to the resource and the trigger still exists.

### Steps to Reproduce

1. Create the above resource with `terraform apply`
2. Delete or comment the entire `lambda_config` block.
3. Run another apply and see that no changes are proposed.

**Comment by DrFaust92** [comment]
I am able to reproduce the issue, it seems that removing `computed` from `lambda_config` solves the issue. ill confirm it doesnt break anything else and submit a PR.
