### ISSUE TITLE
aws-sagemaker-endpoint_configuration_variant_name doesn't allow to be omitted although it is optional 

### ISSUE THREAD

**Issue by Abdullah-Altahhan** [hashicorp/terraform-provider-aws#20966]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

_**terraform version                                                                                       
Terraform v1.0.7**_  

### Affected Resource(s)

**_aws-sagemaker-endpoint_configuration_production_variants_variant_name_**

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
        **_resource "aws_sagemaker_endpoint_configuration" "ec" {

          production_variants {
            model_name             = "linear-learner"
            initial_instance_count = 1
            instance_type          = "ml.t2.medium"
            // variant_name   is not provided as it is optional and terraform is supposed to generate a random one
          }_**
```

### Debug Output

**_getting error:
│ Error: error creating SageMaker Endpoint Configuration: ValidationException: 1 validation error detected: Value '' at 'pr
oductionVariants.1.member.variantName' failed to satisfy constraint: Member must satisfy regular expression pattern: ^[a-zA
-Z0-9]([\-a-zA-Z0-9]*[a-zA-Z0-9])?_**

### Expected Behavior

**_Terraform should create  a random variant name since the variant name is not provided_**

### Actual Behavior

**_Terraform through an error because it received a null value for the variant name_**

### Steps to Reproduce

**_create a sagemaker endpoint configuration without a variant_name variable inside the production_variants block. Terraform will give you error instead of create a random variant name_**

1. `terraform apply`

### References
**_I reviewed the terraform code here:
https://github.com/hashicorp/terraform-provider-aws/blob/9b0205dd0e9992294ce7ae098e8293d9c7e1774e/aws/resource_aws_sagemaker_endpoint_configuration.go

this block of code below is not correct as the condition is forcing the if statement to apply in all cases
		if v, ok := data["variant_name"]; ok {
			l.VariantName = aws.String(v.(string))
		} else {
			l.VariantName = aws.String(resource.UniqueId())
		}

the if statement should be changed to:
		if v, ok := data["variant_name"]; ok && v.(string) != "" {
or
	if v, ok := d.GetOk(data["variant_name"]); ok {_**

**Comment by DrFaust92** [comment]
not a bug as API requires this 
https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_ProductionVariant.html#sagemaker-Type-ProductionVariant-VariantName

**Comment by jar-b** [comment]
Re-opening. This does appear to be a legitimate bug with configurations that omit the `production_variants.0.variant_name` attribute. e.g.

```hcl
resource "aws_sagemaker_endpoint_configuration" "test" {
  name = "jb-test-sagemaker-config"

  production_variants {
    model_name             = aws_sagemaker_model.test.name
    initial_instance_count = 2
    instance_type          = "ml.t2.medium"
    initial_variant_weight = 1
  }
}

```

```
│ Error: creating SageMaker Endpoint Configuration: ValidationException: 1 validation error detected: Value '' at 'productionVariants.1.member.variantName' failed to satisfy constraint: Member must satisfy r
egular expression pattern: ^[a-zA-Z0-9]([\-a-zA-Z0-9]*[a-zA-Z0-9])?
│       status code: 400, request id: 3ce60b91-4330-40e6-b50f-a8862c592549
│
│   with aws_sagemaker_endpoint_configuration.test,
│   on main.tf line 43, in resource "aws_sagemaker_endpoint_configuration" "test":
│   43: resource "aws_sagemaker_endpoint_configuration" "test" {
```

The unconfigured empty string is passed instead of a generated value.
