### ISSUE TITLE
aws_cloudformation_stack_set not deploying to linked accounts

### ISSUE THREAD

**Issue by awssteph** [hashicorp/terraform-provider-aws#20968]
### Community Note

* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.6
+ provider registry.terraform.io/-/aws v3.59.0
+ provider registry.terraform.io/hashicorp/aws v3.59.0

### Affected Resource(s)

* aws_cloudformation_stack_set

### Terraform Configuration Files

```hcl
resource "aws_cloudformation_stack_set" "multi_account_role" {
    name                    = "${var.prefix}OptimizationManagementDataRoleStack"
    
    auto_deployment {enabled = true }
    capabilities = ["CAPABILITY_NAMED_IAM"]

    template_body = <<TEMPLATE
    AWSTemplateFormatVersion: '2010-09-09'
    Description: Stack that will deployed across all accounts in an org so we can assume to read data using a lambda 
    Outputs:
        LambdaRole:
            Description: OPTICS-Assume-Role-Management-Account for lambda to assume in cost account 
            Value:
                Fn::GetAtt:
                    - LambdaRole
                    - Arn 
    Resources:
        LambdaRole:
            Type: AWS::IAM::Role
            Properties:
              RoleName: !Sub "${var.prefix}Optimization-data-Multi-Account-Role"
              AssumeRolePolicyDocument:
                  Statement:
                  - Action:
                      - sts:AssumeRole
                    Effect: Allow
                    Principal:
                      AWS:
                        -  !Sub "arn:aws:iam::${var.CostAccountID}:root"
                  Version: 2012-10-17
              ManagedPolicyArns:
                  - arn:aws:iam::aws:policy/AWSLambdaExecute
              Path: /
              Policies:
              - PolicyName: "ami"
                PolicyDocument:
                  Version: "2012-10-17"
                  Statement:
                    - Effect: "Allow"
                      Action:
                        - "imagebuilder:ListImages"
                        - "imagebuilder:GetImage"
                      Resource: "*"


TEMPLATE
}
```

### Debug Output

```
Error: error creating CloudFormation StackSet: ValidationError: AutoDeployment is not supported
        status code: 400, request id: d489eeae-da86-4d49-968e-84550053f4ba

  on .terraform/modules/stack/stack_set.tf line 1, in resource "aws_cloudformation_stack_set" "multi_account_role":
   1: resource "aws_cloudformation_stack_set" "multi_account_role" {
```

### Expected Behavior

Stack Set should be deployed and the role it contains should be deployed to all accounts in the org

### Actual Behavior

- without the "auto_deployment" section it deploys to the account but the sets are not deployed out to linked accounts.
- with the  "auto_deployment" it gets the error above

### Steps to Reproduce

1. `terraform apply`

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudformation_stack_set#auto_deployment

**Comment by justinretzolk** [comment]
Hey @awssteph 👋 Thanks for submitting this! I took a look over the resource and noticed that the [auto_deployment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudformation_stack_set#auto_deployment) argument may only be used when using the `SERVICE_MANAGED` permission model. 

The [permission_model](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudformation_stack_set#permission_model) argument (which it looks like you're not explicitly setting) defaults to `SELF_MANAGED`. Can you check to see if that change may be what's causing the error?

**Comment by awssteph** [comment]
I have changed it and it runs now thanks. But it's still not deploying to the linked accounts. It's just a stackset in the management account. What do I need to add to make it do that?

Here is the updated code:
resource "aws_cloudformation_stack_set" "multi_account_role" {
    name                    = "${var.prefix}OptimizationManagementDataRoleStack"
    permission_model = "SERVICE_MANAGED"
    auto_deployment{enabled = true }
    capabilities = ["CAPABILITY_NAMED_IAM"]

    template_body = <<TEMPLATE
    AWSTemplateFormatVersion: '2010-09-09'
    Description: Stack that will deployed across all accounts in an org so we can assume to read data using a lambda 
    Outputs:
        LambdaRole:
            Description: OPTICS-Assume-Role-Management-Account for lambda to assume in cost account 
            Value:
                Fn::GetAtt:
                    - LambdaRole
                    - Arn 
    Resources:
        LambdaRole:
            Type: AWS::IAM::Role
            Properties:
              RoleName: !Sub "${var.prefix}Optimization-data-Multi-Account-Role"
              AssumeRolePolicyDocument:
                  Statement:
                  - Action:
                      - sts:AssumeRole
                    Effect: Allow
                    Principal:
                      AWS:
                        -  !Sub "arn:aws:iam::${var.CostAccountID}:root"
                  Version: 2012-10-17
              ManagedPolicyArns:
                  - arn:aws:iam::aws:policy/AWSLambdaExecute
              Path: /
              Policies:
              - PolicyName: "ami"
                PolicyDocument:
                  Version: "2012-10-17"
                  Statement:
                    - Effect: "Allow"
                      Action:
                        - "imagebuilder:ListImages"
                        - "imagebuilder:GetImage"
                      Resource: "*"


TEMPLATE
}

**Comment by awssteph** [comment]
Hi, any update on this? Thank you

**Comment by justinretzolk** [comment]
Hey @awssteph 👋 I don't want to leave you hanging here, but unfortunately don't have an immediate answer as to why the updated configuration isn't deploying to the linked accounts. I'm going to leave the issue open so that either someone from the team can take a look to determine if this is a bug or some additional configuration change that may need to occur, or in case someone else from the community has a more immediate answer.
