### ISSUE TITLE
AWS Transfer Server:  Can't create SFTP with VPC Endpoint error. InvalidRequestException: Unable to verify VPC Endpoint

### ISSUE THREAD

**Issue by udomsak** [hashicorp/terraform-provider-aws#20972]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_transfer_server

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_version = "~> 0.15.3"
}

provider "aws" {
  region = "ap-southeast-1"
  profile = "me"
}

resource "aws_iam_role" "test_role" {
  name = "apigw-logging-role"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": [
          "apigateway.amazonaws.com"
        ]
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

module "vpc" {
  source = "cloudposse/vpc/aws"
  # Cloud Posse recommends pinning every module to a specific version
  # version = "0.14.1"

  namespace  = "test_issue_"
  name       = "vpc"
  stage      = "_poc_"
  cidr_block = "10.226.0.0/20"
}

locals {
  public_cidr_block  = cidrsubnet(module.vpc.vpc_cidr_block, 1, 0)
  private_cidr_block = cidrsubnet(module.vpc.vpc_cidr_block, 1, 1)
}

module "public_subnets" {
  source = "cloudposse/multi-az-subnets/aws"
  # Cloud Posse recommends pinning every module to a specific version
  # version = "0.14.1"

  namespace           = "test_dev_"
  stage               = "_poc_"
  name                = "issue_poc_network"
  availability_zones  = ["ap-southeast-1a", "ap-southeast-1b", "ap-southeast-1c"]
  vpc_id              = module.vpc.vpc_id
  cidr_block          = local.public_cidr_block
  type                = "public"
  igw_id              = module.vpc.igw_id
  nat_gateway_enabled = "false"
}

module "private_subnets" {
  source = "cloudposse/multi-az-subnets/aws"
  # Cloud Posse recommends pinning every module to a specific version
  # version = "0.14.1"

  namespace           = "test_dev_"
  stage               = "_poc_"
  name                = "_issue_poc_network"
  availability_zones  = ["ap-southeast-1a", "ap-southeast-1b", "ap-southeast-1c"]
  vpc_id              = module.vpc.vpc_id
  cidr_block          = local.private_cidr_block
  type                = "private"
  # az_ngw_ids          = module.public_subnets.az_ngw_ids
}


locals{
  subnet_ids = [for subnet in module.private_subnets.az_subnet_ids: subnet]
}

resource "aws_security_group" "sftp" {
  name = "sg_test"
  description = "SecurityGroup specify rule access for VPC EndPoint"
  vpc_id = module.vpc.vpc_id

  ingress {
    description = "Allow Access to SFTP Endpoint"
    from_port = 22
    protocol = "TCP"
    to_port = 22
    cidr_blocks = []
  }
  // TODO: move to another one resources.

  ingress {
    description = "Allow ICMP type 8 (ping command to use)."
    from_port = 8
    protocol = "ICMP"
    to_port = 0
    cidr_blocks = []
  }
}
resource "aws_api_gateway_rest_api" "create_rest" {
  name        = "dummy_api"
}
resource "aws_api_gateway_resource" "root_resource" {
  parent_id   = aws_api_gateway_rest_api.create_rest.root_resource_id
  path_part   = "dummy"
  rest_api_id = aws_api_gateway_rest_api.create_rest.id
}

resource "aws_api_gateway_method" "create_api_method" {
  authorization = "NONE"
  http_method   = "GET"
  resource_id   = aws_api_gateway_resource.root_resource.id
  rest_api_id   = aws_api_gateway_rest_api.create_rest.id
}
resource "aws_api_gateway_integration" "create_integration" {

  http_method = aws_api_gateway_method.create_api_method.http_method
  resource_id = aws_api_gateway_resource.root_resource.id
  rest_api_id = aws_api_gateway_rest_api.create_rest.id
  type        = "MOCK"
  depends_on = [
    aws_api_gateway_resource.root_resource,
    aws_api_gateway_rest_api.create_rest
  ]
}
resource "aws_api_gateway_deployment" "create_api" {
  rest_api_id = aws_api_gateway_rest_api.create_rest.id
  lifecycle {
     create_before_destroy = true
  }
}

resource "aws_api_gateway_stage" "create_stage" {
  deployment_id = aws_api_gateway_deployment.create_api.id
  rest_api_id   = aws_api_gateway_rest_api.create_rest.id
  stage_name    = "dummy"
}


resource "aws_lb" "sftp_network_load_balance" {
  name = "my-nlb"
  internal = true
  load_balancer_type = "network"
  enable_cross_zone_load_balancing = true
  subnets = local.subnet_ids
}

resource "aws_vpc_endpoint_service" "sftp_vpc_endpoint_service" {
  depends_on = [aws_lb.sftp_network_load_balance]
  acceptance_required = false
  network_load_balancer_arns = [aws_lb.sftp_network_load_balance.id]
}

resource "aws_vpc_endpoint" "sftp_vpc_endpoint" {
  vpc_endpoint_type = "Interface"
  service_name = aws_vpc_endpoint_service.sftp_vpc_endpoint_service.service_name
  vpc_id = module.vpc.vpc_id
  subnet_ids = local.subnet_ids
  depends_on = [
    aws_vpc_endpoint_service.sftp_vpc_endpoint_service,
    aws_security_group.sftp]
  security_group_ids = [aws_security_group.sftp.id]
}

resource "aws_transfer_server" "sftp" {
  endpoint_type = "VPC_ENDPOINT"
  identity_provider_type = "API_GATEWAY"
  url = "${aws_api_gateway_deployment.create_api.invoke_url}${aws_api_gateway_stage.create_stage.stage_name}"
  invocation_role = aws_iam_role.test_role.arn

  endpoint_details {
     vpc_endpoint_id = aws_vpc_endpoint.sftp_vpc_endpoint.id
  }
  protocols   = ["SFTP"]

  depends_on = [
    module.private_subnets,
    aws_vpc_endpoint.sftp_vpc_endpoint]

  // From bug (maybe) prevent it.
  // https://github.com/hashicorp/terraform-provider-aws/issues/19983
  lifecycle {
    prevent_destroy = false
  }
}


```

### Debug Output

https://gist.github.com/udomsak/d86c29736ee5fecd7c75e20628c573f5

### Expected Behavior

**Can create AWS Transfer server with VPC Endpoint / VPC Endpoint Services (AWS PrivateLink).**

### Actual Behavior
```bash
╷
│ Error: error creating Transfer Server: InvalidRequestException: Unable to verify VPC Endpoint vpce-052d85f5b77561fb7
│
│   with aws_transfer_server.sftp,
│   on main.tf line 171, in resource "aws_transfer_server" "sftp":
│  171: resource "aws_transfer_server" "sftp" {
│
╵
```

### Steps to Reproduce

1. `terraform plan && terraform apply -auto-approve`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @udomsak 👋 Thanks for filing this. In taking a look over it, it looks like `vpc_endpoint` type of `VPC_ENDPOINT` is being discontinued ([here's some information on that](https://docs.aws.amazon.com/transfer/latest/userguide/create-server-in-vpc.html#deprecate-vpc-endpoint); it's also mentioned in AWS' [API documentation](https://docs.aws.amazon.com/transfer/latest/userguide/API_CreateServer.html#API_CreateServer_RequestSyntax)) and should instead be `VPC`.

With that in mind, the resource [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_server) for `aws_transfer_server` mentions that the `ec2:DescribeVpcEndpoints` and `ec2:ModifyVpcEndpoint` actions are used when the `endpoint_type` is set to `VPC`. It doesn't look like your  `aws_iam_role.test_role` definition includes those actions. Can you check to see if perhaps that's what's causing the error you're seeing?

**Comment by udomsak** [comment]
Hi @justinretzolk , I follow the [document provider aws_transfer_server](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_server#vpc_endpoint_id) ,  However if I try to change as `VPC`  for `endpoint_type`  got like below. 

`Error: error creating Transfer Server: InvalidRequestException: VPC Endpoint ID unsupported for EndpointType: VPC` 

what the flow that I want is ` Network Load Balancer -> VPC EndPoint Service (PrivateLink) -> VPC EndPoint  ->  Transfer server` is it possible?  

currently from previous I use  `endpoint_detail` like 

```hcl
endpoint_details {
  
    subnet_ids = var.transfer_aws_subnet_id
    vpc_id = var.transfer_aws_sftp_vpc_id
    
  }
```
This  will let  `aws_transfer_server` create  VPC EndPoint automatically and this may lead  in to the problem that sometime `aws_transfer_server` try to create new VPC endpoint that I report at  [VPC Endpoint try to re-create issue](https://github.com/hashicorp/terraform-provider-aws/issues/19983). (for this I can't give more for plan or state file. so I decide to close)

**Comment by justinretzolk** [comment]
Hey @udomsak, thank you for the followup. I see my error now in that the `vpc_endpoint_id` argument may only be used with the `VPC_ENDPOINT` `endpoint_type`. As I'm unfamiliar with this particular resource and don't want to continue to lead you down incorrect paths, I'm going to go ahead and apply the `bug` label so that we can continue to look into this.
