### ISSUE TITLE
AWS Batch - Allow Node Properties configuration

### ISSUE THREAD

**Issue by NunoPinheiro** [hashicorp/terraform-provider-aws#20983]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS added support for multi node jobs. These are configured by using the Node Properties instead of container properties.

### New or Affected Resource(s)

* aws_batch_job_definition

### Potential Terraform Configuration

```hcl
resource "aws_batch_job_definition" "my_job" {
  name = "my_job"
  type = "container"

    node_properties = <<NODE_PROPERTIES
  {
      json configuration here
  }
  NODE_PROPERTIES
}
```

### References

* https://docs.aws.amazon.com/batch/latest/userguide/multi-node-job-def.html
* https://docs.aws.amazon.com/batch/latest/userguide/multi-node-parallel-jobs.html

**Comment by laestrada** [comment]
Is there any workaround method to use terraform to set up a multi-node batch job?
