### ISSUE TITLE
aws_cloudwatch_log_group attributes not properly documented

### ISSUE THREAD

**Issue by unacceptable** [hashicorp/terraform-provider-aws#20985]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
+ provider registry.terraform.io/hashicorp/aws v3.59.0
```

### Affected Resource(s)

* aws_cloudwatch_log_group - missing `name`
* aws_cloudwatch_log_stream - does not appear to have `arn`

**Comment by kamilturek** [comment]
Both `aws_cloudwatch_log_group.name` and `aws_cloudwatch_log_stream` work for me and appear to be documented.

Config:
```
resource "aws_cloudwatch_log_group" "yada" {
  name = "Yada"
}

resource "aws_cloudwatch_log_stream" "foo" {
  name           = "SampleLogStream1234"
  log_group_name = aws_cloudwatch_log_group.yada.name
}

output "log_group_name" {
  value = aws_cloudwatch_log_group.yada.name
}

output "log_stream_arn" {
  value = aws_cloudwatch_log_stream.foo.arn
}
```

Output:
```
Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

log_group_name = "Yada"
log_stream_arn = "arn:aws:logs:eu-central-1:[REDACTED]:log-group:Yada:log-stream:SampleLogStream1234"
```

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group#name
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_stream#arn
