### ISSUE TITLE
generic error message for cloudfront distributions missing restriction field

### ISSUE THREAD

**Issue by mcandre** [hashicorp/terraform-provider-aws#21011]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```console
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.57.0
```

### Affected Resource(s)

* aws_cloudfront_distribution

### Terraform Configuration Files

```hcl
#
#
# comments...
#
#
resource "aws_cloudfront_distribution" "cf" {
}
```

### Expected Behavior

Terraform indicates the correct line of the file missing a `restriction` field.

### Actual Behavior

```console
$ terraform plan
╷
│ Error: Insufficient restrictions blocks
│ 
│   on  line 0:
│   (source code not available)
│ 
│ At least 1 "restrictions" blocks are required.
╵
```

Note that most other errors feature a correct line number.

### Steps to Reproduce

1. `terraform plan`

### References

**Comment by justinretzolk** [comment]
Hey @mcandre 👋 Thank you for filing this. To clarify, is the issue here the error message (`At least 1 "restrictions" block...`), or `line 0` bit seemingly indicating the incorrect line number?
