### ISSUE TITLE
Terraform Elastic Beanstalk Application: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by bolanlesd** [hashicorp/terraform-provider-aws#21012]
I get this error when i try to use the resource "aws_elastic_beanstalk_application"

```╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to aws_elastic_beanstalk_application.default,
│ provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
```
Can I get help with this please?

To Reproduce:
```hcl
resource "aws_elastic_beanstalk_application" "tftest" {
  name        = "tf-test-name"
  description = "tf-test-desc"

  appversion_lifecycle {
    service_role          = aws_iam_role.beanstalk_service.arn
    max_count             = 128
    delete_source_from_s3 = true
  }
}
```

**Comment by anGie44** [comment]
Hi @bolanlesd , thank you for raising this issue. To further investigate, do you mind providing more details regarding which provider version you are working with, as well as the complete configuration?

**Comment by bolanlesd** [comment]
Hello @anGie44 , thank you for your response:

registry.terraform.io/hashicorp/aws, i used v3.57.0 and v3.59.0

As for the complete configuration, let me break it down, perhaps this is what you mean? (But i only have just that one resource)

main.tf:

resource "aws_elastic_beanstalk_application" "default" {
  name        = "test1"
  description = "tf-test-desc"

  appversion_lifecycle {
    service_role          = "arn:aws:iam::XXXXXXXX:role/aws-elasticbeanstalk-service-role"
    max_count             = 128
    delete_source_from_s3 = true
  }
}

I am using Terragrunt configuration on my terraform.

**Comment by anGie44** [comment]
Hi @bolanlesd , no updates from me atm :/ I'm not able to reproduce this on my end but I do see the error in the text file attached in your previous comment; terraform successfully creates the resource but when it goes to find the application via an API request `DescribeApplications` to the AWS service it's not found for some reason. Are you able to share the IAM service role configuration as well?

**Comment by bolanlesd** [comment]
Thanks for the prompt response @anGie44 !
Please see the JSON policies attached to the service role used for the deployment.


[AWSElasticBeanstalkEnhancedHealth.txt](https://github.com/hashicorp/terraform-provider-aws/files/7253858/AWSElasticBeanstalkEnhancedHealth.txt)
[AWSElasticBeanstalkManagedUpdatesCustomerRolePolicy.txt](https://github.com/hashicorp/terraform-provider-aws/files/7253859/AWSElasticBeanstalkManagedUpdatesCustomerRolePolicy.txt)

**Comment by vrajendra** [comment]
I can reproduce the error, this happens when apply however plan is successfull.


aws_elastic_beanstalk_application.default: Creating...
aws_elastic_beanstalk_application.default: Still creating... [10s elapsed]
aws_elastic_beanstalk_application.default: Still creating... [20s elapsed]
aws_elastic_beanstalk_application.default: Still creating... [30s elapsed]
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to aws_elastic_beanstalk_application.default,
│ provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
Releasing state lock. This may take a few moments...
ERRO[0043] Hit multiple errors:
Hit multiple errors:
exit status 1

**Comment by vrajendra** [comment]
Hi @anGie44 
            I have further checked the aws console and the application still gets creating while the terraform errors out. it creates after some time. So what I have found is the provider is exiting in 30 secs while the application is still creating . can this be resolved by putting a loop in the code till the application gets created. I found a similar issue and fix [here](https://github.com/hashicorp/terraform/issues/20688)

**Comment by HariSankaranarayanan** [comment]
Hi All,
Even I am facing the exact issue as @bolanlesd , I can see for similar issues in other AWS services, there was a bug-fix released in upcoming release. Is there any plan or resolution for this issue?
