### ISSUE TITLE
Tags for AWS resources created implicitly by other resources II

### ISSUE THREAD

**Issue by Benvorth** [hashicorp/terraform-provider-aws#21055]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Like #9061 but with different resource (`aws_ec2_transit_gateway_vpc_attachment`):

I have a TGW in account 1:

```hcl
resource "aws_ec2_transit_gateway" "the_tgw" {
  amazon_side_asn                 = "65501"
  auto_accept_shared_attachments  = "enable"
  default_route_table_association = "disable"
  default_route_table_propagation = "disable"
  description                     = "My TGW in account 1"
  dns_support                     = "enable"
  vpn_ecmp_support                = "enable"
  tags = tomap({
    Name = "TGW"
  })
}
```

And share it via RAM with account 2.

Now I create a `aws_ec2_transit_gateway_vpc_attachment` in account 2 (different terraform-run) for the shared TGW:

```hcl
data "aws_ec2_transit_gateway" "the_tgw" {
  filter {
    name = "options.amazon-side-asn"
    values = ["65501"]
  }
}

# <snip>create a VPC in account 2 with subnets </snip>

resource "aws_ec2_transit_gateway_vpc_attachment" "vpc_attachment_to_tgw" {

  transit_gateway_id = data.aws_ec2_transit_gateway.the_tgw.id
  vpc_id             = ... # my vpc.ID
  subnet_ids         = ... # my subnet.IDs
  tags =tomap({
      "Name" = "TGW attachment for VPC in account 2"
  })
}
```

### Terraform CLI and Terraform AWS Provider Version
```
> terraform -v
Terraform v1.0.3
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.59.0
```
### Affected Resource(s)

* aws_ec2_transit_gateway_vpc_attachment,

### Expected Behavior

Within account 1 the TGW attachment's tags are visible

### Actual Behavior

Attachment's tags not visible in account 1 (empty), only the tgw attachment itself.

### References

* #9061

**Comment by ewbankkit** [comment]
@Benvorth Thanks for raising this issue.

Have you tried using the [`aws_ec2_tag`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_tag) resource in the 2nd account, specifying `aws_ec2_transit_gateway_vpc_attachment.vpc_attachment_to_tgw.id` as the `resource_id`?

**Comment by Benvorth** [comment]
Thanks for the hint. 

I tried this:

```
resource "aws_ec2_tag" "vpc_attachment_to_TGW_Name_Tag" {
  resource_id = aws_ec2_transit_gateway_vpc_attachment.vpc_attachment_to_tgw.id
  key         = "Name"
  value       = "TGW attachment for VPC in account 2"
}
```

Unfortunately the attachments' name in account 1 is still empty...

**Comment by Benvorth** [comment]
>The tags on a resource are separate per account. You would need to apply the tags in both accounts for it to work.

Thanks for the link. Unfortunately AWS seems to use the "name" tag as an "name" identifier for the TGW attachment. That's why I am [80% sure](https://blog.glowforge.com/strong-opinions-loosely-held-might-be-the-worst-idea-in-tech/) that there is at least one scenario where it makes no sense to have the tags account-specific (the [AWS recommended ](https://aws.amazon.com/blogs/mt/best-practices-for-organizational-units-with-aws-organizations/?org_product_gs_bp_OUBlog)multi-accout strategy, the scenario I describe above): 
- Create a TGW in account 1, 
- In acccount 2 fetch TGW by APN
- And add an VPC attachment to it in account 2

--> Now I could add tags in account 2 to this attachment (which works). 

Following the provided "UserGuide" I have to add these tags (in my case name) to the TGW attachment in account 1, too. 

But how would I fetch this resource in account 1 via Terraform? The TGW attachment created in account 2 doesn't have an APN, or a name-tag (yet). Only option would be via identifier or VPC-id - which both are not available in account 1 without manually copy/pasting values between the terraform scripts for account 1 and 2. Such a manual step would break my automatization pipeline.

Any other ideas or is this "just impossible with terraform" up to now and more of a shortcoming in AWS (and worth rising an issue there)?

**Comment by yzguy** [comment]
I would agree. This is something I am currently facing as well (which is how I found this issue). One way I'm considering, is similar to how we do sharing of the TGW to the second account, is that the module that does the sharing has a `local_file` resource that is created, which is placed in the path where account 2 is accepting the TGW. 

## Account 1

```
locals {
  accounts_to_share_to = [
    "abc123",
    "123abc"
  ]
}

resource "aws_ram_principal_association" "tgw" {
  for_each = local.accounts_to_share_to
  
  principal          = each.value
  resource_share_arn = data.aws_ram_resource_share.tgw_ram_rsh.arn
}

resource "local_file" "tgw_data" {
  for_each = local.accounts_to_share_to
  content = yamlencode({
    "tgw_id" : data.aws_ec2_transit_gateway.tgw.id,
    "tgw_name" : local.tgw_name,
    "tgw_ram_arn" : data.aws_ram_resource_share.tgw_ram_rsh.arn,
    "tgw_owner_id": data.aws_caller_identity.current.account_id
  })
  filename = "${path.module}/../../${each.value}/us-east-1/tgw_accept/tgw_data.yml"
}

locals {
  tgw_attachment_data = {
    for account in local.accounts_to_share_to :
     account => fileexists("${path.module}/${account}.yaml") ? yamldecode(file("${path.module}/${account}.yaml")) : {}
  }
}

resource "aws_ec2_tag" "vpc_attachment_tag" {
  for_each = {
    for account, data in local.tgw_attachment_data: account => data if contains(keys(data), "tgw_attachment_id")
  }
  
  resource_id = each.value.tgw_attachment_id
  key         = "Name"
  value       = "TGW attachment for VPC in ${each.key}"
}
```

## Account 2

```
locals {
   tgw_data = yamldecode(file("${path.module}/tgw_data.yml"))
}

resource "aws_ec2_transit_gateway_vpc_attachment" "tgw_attach" {
  subnet_ids = data.aws_subnet_ids.subnets.ids
  transit_gateway_id = local.tgw_data.tgw_id
  ...
}

resource "local_file" "tgw_att_data" {
  content = yamlencode({
    "tgw_attachment_id" : data.aws_ec2_transit_gateway_vpc_attachment.tgw_attach.id,
    "tgw_attachment_vpc": data.aws_vpc.vpc.id
  })
  filename = "${path.module}/../../${local.tgw_data.tgw_owner_id/us-east-1/tgw_share/${data.aws_caller_identity.current.account_id}.yml"
}
```
