### ISSUE TITLE
Unable to create `aws_dms_replication_subnet_group`

### ISSUE THREAD

**Issue by johnnyhuy** [hashicorp/terraform-provider-aws#21067]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform `1.0.7`
AWS provider `3.60.0` and `3.32.0`
### Affected Resource(s)

`aws_dms_replication_subnet_group`

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_dms_replication_subnet_group" "this" {
  replication_subnet_group_description = "test"
  replication_subnet_group_id          = "test"
  subnet_ids                           = data.aws_subnet_ids.test.ids
  tags { Name = "test" }
}
```

### Expected Behavior

Terraform plan and apply should pass.

### Actual Behavior

Throws an error:

```bash
Error: error listing tags for DMS Replication Subnet Group (arn:aws:dms:ap-southeast-2::subgrp:test): InvalidParameterValueException: Invalid resource name:  arn:aws:dms:ap-southeast-2::subgrp:test
│       status code: 400, request id: 922257e0-49b9-4faf-be14-88ba28a73404
│ 
│   with aws_dms_replication_subnet_group.this,
│   on dms.tf line 1, in resource "aws_dms_replication_subnet_group" "this":
│    1: resource "aws_dms_replication_subnet_group" "this" {
```

Looks like it's trying to fetch tags from the ARN. However, the ARN is malformed where the account ID missing.

```bash
# arn:aws:dms:ap-southeast-2:{MISSING ACCOUNT ID}:subgrp:test
arn:aws:dms:ap-southeast-2::subgrp:test
```

We're guessing [resource_aws_dms_replication_subnet_group.go](https://github.com/hashicorp/terraform-provider-aws/blob/ac06ced75cba0daf09fef2938752ad13cc6fff6e/aws/resource_aws_dms_replication_subnet_group.go#L104) is where it's generating the ARN. This is also present in our state file under this resource.

### Steps to Reproduce

After creating the resource through Terraform. Running `apply`, `plan` or `destroy` will throw the same error.

**Comment by justinretzolk** [comment]
Hey @johnnyhuy 👋 Thank you for taking the time to file this. So that we have all of the information needed to investigate, can you update the description to include the version of the AWS provider that you're using?

**Comment by johnnyhuy** [comment]
> Hey @johnnyhuy 👋 Thank you for taking the time to file this. So that we have all of the information needed to investigate, can you update the description to include the version of the AWS provider that you're using?

Hey, I've added the version. Thanks

**Comment by johnnyhuy** [comment]
We've tried this with a previous version before that resource was last modified. Still got the same effect.

Also tried using different AWS profiles from the provider config, environment variables and different profile names.

**Comment by justinretzolk** [comment]
Thank you for the updates! I've marked this issue as a bug so that the team may look into it as time permits. Thank you again for reporting this!

**Comment by johnnyhuy** [comment]
No worries, for people who need to get DMS working in Terraform in the meantime. Just hard-code the subnet group ID on your DMS replication instances

**Comment by bennylu2** [comment]
Ah I see this is provider 3.x. I tested this with the latest version 4.x of the provider and it worked, had to update the tags. Are you able to upgrade to a later version?

```
resource "aws_dms_replication_subnet_group" "this" {
  replication_subnet_group_description = "test"
  replication_subnet_group_id          = "test"
  subnet_ids                           = data.aws_subnets.dms.ids
  tags                                 = { Name = "test" }
}
```

```
aws_dms_replication_subnet_group.this: Creating...
aws_dms_replication_subnet_group.this: Creation complete after 2s [id=test]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by justinretzolk** [comment]
Hey all 👋 It looks like this issue no longer persists in the latest version of the provider, so we'll close this issue out. If you continue to experience this in later versions of the provider, please open a new issue so that we may take another look.
