### ISSUE TITLE
Resource aws_dx_connection seems to be broken after introducing attribute provider_name in version v3.56.0

### ISSUE THREAD

**Issue by klaphi** [hashicorp/terraform-provider-aws#21068]
Hi all,

terrafrom plans to recreate my direct connect connections because of a new attribute `provider_name`  which has been introduced with version v3.56.0. I checked also the documentation on that attribute and its flagged as optional, which should not trigger a replacement of a resource.

Please have a look at attribute definition which is set to true for `Optional:` and `ForceNew:`
https://github.com/hashicorp/terraform-provider-aws/blob/baac4b0338b0500475288cd4e14dc30674530e63/aws/resource_aws_dx_connection.go#L67#L68

https://github.com/hashicorp/terraform-provider-aws/blob/baac4b0338b0500475288cd4e14dc30674530e63/aws/resource_aws_dx_lag.go#L67#L68

I think it should be required or optional. Please check and fix the code or update the documentation accordingly.

Thanks in advance

**Comment by klaphi** [comment]
- Versions <= v3.55.0 the plan works fine
- Version >= v3.56.0 plan triggers a replacement of DX connections

**Comment by ewbankkit** [comment]
@klaphi Thanks for raising this issue.

I assume that the connections/LAGs that were created with the earlier (pre-3.56.0) version of the provider has a provider name set by some means outside Terraform?

**Comment by klaphi** [comment]
Indeed, I just imported the DX connections with an older version of the provider. Currently there is no attribute `provider_name` on the DX resources in the statefile.
