### ISSUE TITLE
Support the new `alb` target_type in `aws_lb_target_group` and `aws_lb_target_group_attachment` for Network Load Balancers

### ISSUE THREAD

**Issue by KyleMarMcTVG** [hashicorp/terraform-provider-aws#21069]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS have added a new feature to Network Load Balancers, whereby they can now target an ALB via the ALB's ARN. This allows NLBs to perform level 4 load balancing and pass traffic directly to an ALB for level 7 load balancing.

### New or Affected Resource(s)

* aws_lb_target_group
* aws_lb_target_group_attachment

### Potential Terraform Configuration

```hcl
resource "aws_lb_target_group" "alb_example" {
  name        = "tf-example-lb-tg"
  port        = 80
  protocol    = "HTTP"
  target_type = "alb"
  vpc_id      = aws_vpc.main.id
}

resource "aws_lb_target_group_attachment" "test" {
  target_group_arn = aws_lb_target_group.alb_example.arn
  target_id        = aws_lb.alb.arn
  port             = 80
}
```

### References

* Blog post announcing new feature: https://aws.amazon.com/blogs/networking-and-content-delivery/application-load-balancer-type-target-group-for-network-load-balancer/
* https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateTargetGroup.html
* https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_RegisterTargets.html
* https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_DeregisterTargets.html
* https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_TargetGroup.html

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.40.50](https://github.com/aws/aws-sdk-go/releases/tag/v1.40.50):

* #21065

As the `target_type` attribute is validated against the `_Values()` enum:

https://github.com/hashicorp/terraform-provider-aws/blob/baac4b0338b0500475288cd4e14dc30674530e63/aws/resource_aws_lb_target_group.go#L263-L269

, rebuilding with the relevant AWS SDK version _should_ enable this feature.

**Comment by ricardosouzamorais** [comment]
What is the expectation to have this ?

**Comment by ewbankkit** [comment]
@ricardosouzamorais It will be available in **v3.61.0** of the Terraform AWS Provider, likely later today.

**Comment by ricardosouzamorais** [comment]
Awesome! :-) Thanks for sharing that.

**Comment by pjaudiomv** [comment]
I just tested this out and works great, was able to swap out one of my lambdas and just use the alb as a target. Thank you.
