### ISSUE TITLE
aws_dx_connection: support macsec

### ISSUE THREAD

**Issue by jdeluyck** [hashicorp/terraform-provider-aws#21082]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS offers macsec encryption support for Direct connect connections (not everywhere yet).

Currently, terraform does not support requesting these connections

The AWS CLI supports requesting these connections, as does boto3

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/directconnect.html#DirectConnect.Client.create_connection

```
response = client.create_connection(
    location='string',
    bandwidth='string',
    connectionName='string',
    lagId='string',
    tags=[
        {
            'key': 'string',
            'value': 'string'
        },
    ],
    providerName='string',
    requestMACSec=True|False
)
```

### New or Affected Resource(s)

* `aws_dx_connection`
* `aws_dx_lag`

### Potential Terraform Configuration

A new boolean could be introduced in the aws_dx_connection resource
```hcl
resource "aws_dx_connection" "hoge" {
  name      = "tf-dx-connection"
  bandwidth = "1Gbps"
  location  = "EqDC2"
  macsec    = true
}
```
### References

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/directconnect.html#DirectConnect.Client.create_connection

* #0000

**Comment by ddericco** [comment]
This is being worked on.
