### ISSUE TITLE
aws_lambda_function

### ISSUE THREAD

**Issue by luisamador** [hashicorp/terraform-provider-aws#21083]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

"Enhanced monitoring" option can't be configured for a Lambda function via Terraform. Would be useful to provide this feature.

### New or Affected Resource(s)

aws_lambda_function

### References

![image](https://user-images.githubusercontent.com/18208396/135250499-156215d7-de61-4e42-99ef-1f47db11893d.png)

https://docs.aws.amazon.com/lambda/latest/dg/monitoring-insights.html#monitoring-insights-enabling-console

**Comment by ewbankkit** [comment]
Enabling Lambda Insights via the AWS CLI: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-Getting-Started-cli.html.
