### ISSUE TITLE
Add option to capture snapshots on destroy of `ebs_volume`

### ISSUE THREAD

**Issue by catsby** [hashicorp/terraform-provider-aws#2109]
Seems like `ebs_volumes` should have a parameter to trigger a snapshot of the volume before deleting, much like [final_snapshot_identifer](https://www.terraform.io/docs/providers/aws/r/db_instance.html#final_snapshot_identifier) in `db_instance`

**Comment by kitsushadow** [comment]
Thanks for opening this issue. If use-case examples are necessary i am happy to provide

**Comment by johananl** [comment]
As far as I know, EBS does not provide this functionality (unlike RDS which does). Do you think Terraform should provide this functionality as a "wrapper" around EBS @catsby? If so, I'd be happy to give this a shot.

**Comment by catsby** [comment]
Basically, yeah. 

In the delete method of `resource_ebs_volume` we just go right to delete:

https://github.com/terraform-providers/terraform-provider-aws/blob/cffdb25abe2bf8c3940864e84b16a767ddb314de/aws/resource_aws_ebs_volume.go#L249-L273

I'm proposing adding an optional attribute to `resource_ebs_volume` e.g. `termination_snapshot_name` or something, to denote that this is the name to give to the snapshot that's created from this volume when terraform destroyed it. 

Then in the `resourceAwsEbsVolumeDelete` method (linked above), check if `termination_snapshot_name` is set (not `""`), and if a name is given, we should then call [CreateSnapshot](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSnapshot.html) for the volume, and wait until it succeeds before we move on to deletion. We should log that we're creating a snapshot and waiting for it to succeed before moving on to normal deletion.

**Comment by johananl** [comment]
Sounds good to me @catsby. I'll give it a shot then - I've been wanting to start contributing to Terraform for a while now, and this seems like a good start to me. Updates will follow.

**Comment by catsby** [comment]
Looking forward to it! Feel free to open an incomplete PR if you need guidance on anything

**Comment by jmaciasluque** [comment]
I'm surprised there is so little traction for this...

**Comment by JaviOverflow** [comment]
any updates on this topic or any workaround? I'm also looking forward to have this feature

**Comment by thatderek** [comment]
@catsby because ebs-volumes don't have an `id` in the rds sense of the term, what about just copying any tags on the drive to the snapshot?

**Comment by AndreKapraty** [comment]
As It's an old topic and we need this feature, updated my PR - https://github.com/hashicorp/terraform-provider-aws/pull/21916
