### ISSUE TITLE
Support for ARM architectures in Lambda Funtions

### ISSUE THREAD

**Issue by jerusdp** [hashicorp/terraform-provider-aws#21098]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has added support for ARM Architecture in the Lambda Service. The default architecture is x86_64. 

The Terraform configuration for aws_lambda_function needs to provide an option to specify the architecture so that functions can avail of ARM based processors, which AWS claims offer a more economic solutions in particular applications.

### New or Affected Resource(s)

* aws_lambda_function

### Potential Terraform Configuration

```hcl
resource "aws_lambda_function" "test_lambda" {
  filename           = "lambda_function_payload.zip"
  function_name = "lambda_function_name"
  role                  = aws_iam_role.iam_for_lambda.arn
  handler            = "index.test"
  architecture     = "arm64"

  # The filebase64sha256() function is available in Terraform 0.11.12 and later
  # For Terraform 0.11.11 and earlier, use the base64sha256() function and the file() function:
  # source_code_hash = "${base64sha256(file("lambda_function_payload.zip"))}"
  source_code_hash = filebase64sha256("lambda_function_payload.zip")

  runtime = "nodejs12.x"

  environment {
    variables = {
      foo = "bar"
    }
  }
}
```

### References

* https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-Runtime
* https://docs.aws.amazon.com/lambda/latest/dg/foundation-arch.html?icmpid=docs_lambda_help

* #0000

**Comment by ewbankkit** [comment]
@jerusdp Thanks for raising this issue.
It has already been noticed in #21090. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
