### ISSUE TITLE
Add architecture option to aws_lambda_function

### ISSUE THREAD

**Issue by nantiferov** [hashicorp/terraform-provider-aws#21096]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon recently [added support for arm64 / Graviton2 architecture](https://aws.amazon.com/about-aws/whats-new/2021/09/better-price-performance-aws-lambda-functions-aws-graviton2-processor/) for Lambda functions, which looks very interesting. 
Would be nice to have support for it in Terraform provider. 

### New or Affected Resource(s)

* aws_lambda_function

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

resource "aws_lambda_function" "test_lambda" {
  ...
  architecture = "arm64" # or "x86_64", with defaults to x86_64 probably
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2021/09/better-price-performance-aws-lambda-functions-aws-graviton2-processor/

**Comment by mitchellrj** [comment]
Further references
- [Relevant API](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-Architectures)
- [aws-sdk-go PR](https://github.com/aws/aws-sdk-go/pull/4115) (v1.40.52)

**Comment by crea** [comment]
Already done in https://github.com/hashicorp/terraform-provider-aws/issues/21090

**Comment by nantiferov** [comment]
Oh, thank you!
I tried to search for already created issues and wasn't able to find anything.
