### ISSUE TITLE
Incorrect 'depends_on' in the example for resource 'aws_securityhub_invite_accepter'

### ISSUE THREAD

**Issue by IskanderNovena** [hashicorp/terraform-provider-aws#21102]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The code-example for the resource `aws_securityhub_invite_accepter` in the Terraform Docs lists an incorrect `depends_on`:
`depends_on = [aws_securityhub_account.accepter]` should be `depends_on = [aws_securityhub_account.invitee]`

### New or Affected Resource(s)

* aws_securityhub_invite_accepter

### Potential Terraform Configuration

```hcl
resource "aws_securityhub_account" "example" {}

resource "aws_securityhub_member" "example" {
  account_id = "123456789012"
  email      = "example@example.com"
  invite     = true
}

resource "aws_securityhub_account" "invitee" {
  provider = "aws.invitee"
}

resource "aws_securityhub_invite_accepter" "invitee" {
  provider   = "aws.invitee"
  depends_on = [aws_securityhub_account.invitee]
  master_id  = aws_securityhub_member.example.master_id
}
```

### References

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_invite_accepter

**Comment by justinretzolk** [comment]
Hey @IskanderNovena 👋 Thank you for filing this issue! I've just merged a fix for the documentation.
