### ISSUE TITLE
Cognito User Pool Signing Certificate (Data Source)

### ISSUE THREAD

**Issue by KyleKotowick** [hashicorp/terraform-provider-aws#21104]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating a [SAML-based Identity Provider for a Cognito User Pool](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-saml-idp.html), it is usually required to provide the signing certificate to the external SAML IdP. Neither of the relevant Terraform resources ([aws_cognito_user_pool](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool), [aws_cognito_identity_provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_identity_provider)) return this certificate as an attribute.

The AWS API provides the [GetSigningCertificate](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GetSigningCertificate.html) endpoint for this purpose, but there is currently no corresponding Terraform data source.

### New or Affected Resource(s)

Data source:
* aws_cognito_user_pool_signing_certificate

### Potential Terraform Configuration

```hcl
data "aws_cognito_user_pool_signing_certificate" "sc" {
    user_pool_id = aws_cognito_user_pool.my_pool.id
}
```

### References

* https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GetSigningCertificate.html

**Comment by danquack** [comment]
I opened a PR to create this data source.
