### ISSUE TITLE
Handling of alternate contacts for the account

### ISSUE THREAD

**Issue by ChristophShyper** [hashicorp/terraform-provider-aws#21118]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

New awscli/boto3 handles now alternate contacts for the account https://docs.aws.amazon.com/cli/latest/reference/account/put-alternate-contact.html
I'm creating new accounts often and this is something that needs to be done manually, which is time-consuming and would be cool if somebody could add it Terraform.

### New or Affected Resource(s)

* `aws_account_alternate_contact`

### References

* delete-alternate-contact https://docs.aws.amazon.com/cli/latest/reference/account/delete-alternate-contact.html
* get-alternate-contact https://docs.aws.amazon.com/cli/latest/reference/account/get-alternate-contact.html
* put-alternate-contact https://docs.aws.amazon.com/cli/latest/reference/account/put-alternate-contact.html

[Announcement](https://aws.amazon.com/about-aws/whats-new/2021/10/programmatically-manage-alternate-contacts-aws-accounts/).
[Blog post](https://aws.amazon.com/blogs/mt/programmatically-managing-alternate-contacts-on-member-accounts-with-aws-organizations/).

Requires [AWS SDK v1.40.53](https://github.com/aws/aws-sdk-go/releases/tag/v1.40.53):

* #21108

**Comment by simonweil** [comment]
Any estimation when this issue may be implemented?
