### ISSUE TITLE
Deleting aws_security_group is impossible

### ISSUE THREAD

**Issue by clever-rob** [hashicorp/terraform-provider-aws#21116]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by clever-rob** [comment]
Terraform won't delete plain vanilla security group 

resource "aws_security_group" "mongo_private_link" {
  vpc_id                 = var.VPC.id
  name                   = "mongo private link"
  tags                   = { Name = "hive-development" }
  revoke_rules_on_delete = true
  ingress {
    from_port   = 1024
    to_port     = 1026
    protocol    = "TCP"
    cidr_blocks = var.VPC.subnet_cidr_blocks
  }
}

**Comment by justinretzolk** [comment]
Hey @clever-rob 👋 Thank you for taking the time to file this issue. Can you provide the output and so that we can take a look into what's causing this?
