### ISSUE TITLE
Support for SES domain and email identity default configuration set

### ISSUE THREAD

**Issue by KyleKotowick** [hashicorp/terraform-provider-aws#21129]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

SES domain and email identities support setting a default configuration set (in the SESv2 API). Currently, Terraform does not support this feature for either of the relevant resources ([aws_ses_domain_identity](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_domain_identity), [aws_ses_email_identity](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_email_identity)).

The AWS API supports both specifying a default configuration set when creating a new email identity ([CreateEmailIdentity](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_CreateEmailIdentity.html)), as well as setting a default configuration set for an existing email identity ([PutEmailIdentityConfigurationSetAttributes](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_PutEmailIdentityConfigurationSetAttributes.html)).

### New or Affected Resource(s)

* [aws_ses_domain_identity](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_domain_identity)
* [aws_ses_email_identity](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_email_identity)

### Potential Terraform Configuration

```hcl
resource "aws_ses_configuration_set" "test" {
  name = "some-configuration-set-test"
}

resource "aws_ses_domain_identity" "example" {
  domain = "example.com"
  default_configuration_set_name = aws_ses_configuration_set.test.name
}

resource "aws_ses_email_identity" "example" {
  email = "email@example.com"
  default_configuration_set_name = aws_ses_configuration_set.test.name
}
```

OR:
```hcl
resource "aws_ses_configuration_set" "test" {
  name = "some-configuration-set-test"
}

resource "aws_ses_domain_identity" "example" {
  domain = "example.com"
}

resource "aws_ses_email_identity" "example" {
  email = "email@example.com"
}

// Since the PutEmailIdentityConfigurationSetAttributes API supports both domain and
// email identities, this resource should be able to support either as well?
resource "aws_ses_email_identity_default_configuration_set" "domain" {
  email_identity = aws_ses_domain_identity.example.domain
  configuration_set_name = aws_ses_configuration_set.test.name
}

resource "aws_ses_email_identity_default_configuration_set" "email" {
  email_identity = aws_ses_email_identity.example.domain
  configuration_set_name = aws_ses_configuration_set.test.name
}
```

### References

* [CreateEmailIdentity](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_CreateEmailIdentity.html)
* [PutEmailIdentityConfigurationSetAttributes](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_PutEmailIdentityConfigurationSetAttributes.html)

**Comment by elif-benli-engin** [comment]
Do you have an estimation on this implementation?

**Comment by mrvladis** [comment]
Any updates?!

**Comment by gmx-git** [comment]
@kamilturek
We're really looking forward for the **default_configuration_set_name** attribute for the 'aws_ses_domain_identity' and 'aws_ses_email_identity' resources.
It would be great if this topic could be picked up again!
Thank you!!!

**Comment by kamilturek** [comment]
I'll try to pick this up again soon 🤞

**Comment by florian-heer** [comment]
Is there any update regarding the estimation of this feature? Currently this is a blocker for our use case to use Terraform :(

**Comment by gmx-git** [comment]
I see there's a plan and a pull request for moving to sesv2.
Maybe we'll need to vote them up (👍) so they can pick up some traction.
Here are the links:
[https://github.com/hashicorp/terraform-provider-aws/issues/26796](url)
[https://github.com/hashicorp/terraform-provider-aws/pull/26846](url)

Hope this helps move this one forward as well!

**Comment by gmx-git** [comment]
Hi there,

@ewbankkit / @kamilturek : This topic reports the issue for both **domain** and **email** identities. I think so far only the email identity was covered. Should the whole issue be closed in this case?

Is there maybe a plan to get the aws_sesv2_domain_identity resource implemented? I'd have a ton of uses for it! :)

**Comment by gmx-git** [comment]
Yeah, looking at the API reference, it makes sense to have a single call to create the SES identity resources.
