### ISSUE TITLE
Lambda MSK Event Source Mapping: Error "invalid or unknown key: topics"

### ISSUE THREAD

**Issue by bravoidea** [hashicorp/terraform-provider-aws#21137]
Trying to map MSK as event source to Lambda function using terraform script. 

**script code:**
resource "aws_lambda_event_source_mapping" "kafka_event_source" {
  event_source_arn = "***"
  function_name     = "***"
  topics                    = ["topic_name"]
  starting_position = "TRIM_HORIZON"
}

**Command**
terraform plan

**Error**
aws_lambda_event_source_mapping.kafka_event_source: : invalid or unknown key: topics

**Installed version**

terraform 0.11

provider "aws" {
  region = "***"
  version = "v2.70.0"
}

Please suggest.

**Comment by ewbankkit** [comment]
@bravoidea Thanks for raising this issue.

The `topics` argument for the `aws_lambda_event_source_mapping` resource was added in [**v3.28.0**](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3280-february-12-2021) of the AWS Provider.
To use this functionality you will need to upgrade to at least this version.

**Comment by bravoidea** [comment]
@ewbankkit 
and v3.28.0 supports only terraform 0.12 or later version and not 0.11, right?
