### ISSUE TITLE
Wrong `kibana_endpoint` attribute on `aws_elasticsearch_domain` with OpenSearch version

### ISSUE THREAD

**Issue by np5** [hashicorp/terraform-provider-aws#21138]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.6
AWS version: 3.60.0

### Affected Resource(s)

* aws_elasticsearch_domain

### Expected Behavior

`kibana_endpoint_url` should be `endpoint` + `/_dashboards/` when `version` is `OpenSearch_*`

### Actual Behavior

`kibana_endpoint_url` [hard coded](https://github.com/hashicorp/terraform-provider-aws/blob/53546e1e6b294f81c91656f974ad6eddcce56961/aws/resource_aws_elasticsearch_domain.go#L1051) to `endpoint` + `/_plugin/kibana/` for all versions

### References

See [AWS docs](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/dashboards.html)

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/53546e1e6b294f81c91656f974ad6eddcce56961/aws/resource_aws_elasticsearch_domain.go#L1050-L1052
