### ISSUE TITLE
aws_ses_configuration_set returns incorrect ARN

### ISSUE THREAD

**Issue by KyleKotowick** [hashicorp/terraform-provider-aws#21131]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.8
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.61.0

### Affected Resource(s)

* [aws_ses_configuration_set](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ses_configuration_set)

### Terraform Configuration Files

```hcl
resource "aws_ses_configuration_set" "test" {
  name = "some-configuration-set-test"
}

output "configuration_set_arn" {
  value = aws_ses_configuration_set.test.arn
}

provider "aws" {
  region  = "us-east-1"
  profile = "my_profile"
}
```

```
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

configuration_set_arn = "arn:aws:email:us-east-1:111111111111:configuration-set/some-configuration-set-test"
```

### Expected Behavior

The output ARN should be in the format "arn:aws:**ses**: ...".

### Actual Behavior

The output ARN is in the format "arn:aws:**email**: ...".

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

While the ARN of a configuration set is not visible in the AWS console, it is clear from the IAM policy editor that a configuration set ARN is supposed to use `ses` as the service, not `email`.

I noticed this issue when using the ARN attribute of this resource in an `aws_iam_policy_document` data source for creating a policy that allowed sending email using the given configuration set.

### References

Screenshot from the IAM policy editor showing that the ARN is supposed to use `ses` and not `email`:

![Screenshot 2021-10-03 142145](https://user-images.githubusercontent.com/5480106/135766784-e6c0bd1e-7e41-4bdd-8a24-b27ccf72b374.jpg)

**Comment by KyleKotowick** [comment]
The workaround (manually constructing the ARN) for anyone else experiencing this issue:

```
data "aws_caller_identity" "current" {}
data "aws_region" "current" {}

resource "aws_ses_configuration_set" "test" {
  name = "some-configuration-set-test"
}

locals {
  configuration_set_arn = "arn:aws:ses:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:configuration-set/${aws_ses_configuration_set.test.name}"
}
```

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/53546e1e6b294f81c91656f974ad6eddcce56961/aws/resource_aws_ses_configuration_set.go#L160-L167

We should use `"ses"` instead of `ses.ServiceName`: https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonses.html#amazonses-resources-for-iam-policies.
