### ISSUE TITLE
Support for MSK Connect

### ISSUE THREAD

**Issue by Sebruck** [hashicorp/terraform-provider-aws#21141]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great to add support for [MSK Connect](https://aws.amazon.com/about-aws/whats-new/2021/09/amazon-msk-connect-run-serverless-scalable-kafka-connect-clusters-amazon-msk/) plugins and connectors.

Is there anything planned yet?

**Comment by ewbankkit** [comment]
@Sebruck Thanks for raising this issue.
It has already been noticed in #20942. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
