### ISSUE TITLE
Support network_card_index in launch_template network_interfaces

### ISSUE THREAD

**Issue by henighan** [hashicorp/terraform-provider-aws#21147]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS cloudformation's `AWS::EC2::LaunchTemplate NetworkInterface` supports a `NetworkCardIndex` parameter, which is distinct from the `NetworkInterfaceID` parameter.
I do not see a `network_card_index` argument in the terraform `aws_launch_template`'s `network_interfaces` block (though there is a `network_interface_id` argument).
To see this in the documentation, please compare [terraform launch_template network_interfaces](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#network-interfaces) to [AWS::EC2::LaunchTemplate NetworkInterface](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-networkinterface.html).
Is `network_card_index` not currently supported, or am I being silly? How difficult/what steps would be required to add support for it?

### New or Affected Resource(s)

* aws_launch_template

### Potential Terraform Configuration

N/A

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#network-interfaces
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-networkinterface.html
* #0000

**Comment by vara-bonthu** [comment]
@justinretzolk  I have raised a [PR](https://github.com/hashicorp/terraform-provider-aws/pull/21555) for this issue/feature. Please do let me know if you need more details.
