### ISSUE TITLE
MSK cluster resource cannot have both SASL and TLS authentication, but is allowed by the AWS API

### ISSUE THREAD

**Issue by thib92** [hashicorp/terraform-provider-aws#21155]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/aws v3.32.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/louy/uptimerobot v0.5.1
```

### Affected Resource(s)

* `aws_msk_cluster`

### Terraform Configuration Files

```hcl
resource "aws_msk_cluster" "kafka_cluster" {
  cluster_name           = var.cluster_name
  kafka_version          = var.kafka_version
  number_of_broker_nodes = var.number_of_broker_nodes

  broker_node_group_info {
    instance_type   = var.broker_instance_type
    ebs_volume_size = var.broker_ebs_volume_size

    client_subnets  = var.client_subnets
    security_groups = [aws_security_group.kafka.id]
  }

  client_authentication {
    sasl {
      scram = true
    }

    tls {
      certificate_authority_arns = []
    }
  }

  encryption_info {
    encryption_in_transit {
      client_broker = "TLS"
      in_cluster    = true
    }
  }

  configuration_info {
    arn      = aws_msk_configuration.kafka_configuration.arn
    revision = var.configuration_revision
  }

  enhanced_monitoring = "DEFAULT"

  open_monitoring {
    prometheus {
      node_exporter {
        enabled_in_broker = true
      }

      jmx_exporter {
        enabled_in_broker = true
      }
    }
  }

  logging_info {
    broker_logs {
      s3 {
        enabled = true
        bucket  = aws_s3_bucket.kafka_logs.bucket
      }
    }
  }

  tags = merge(
    var.tags.default,
    var.tags.extra
  )
}
```

### Actual Behavior

When specifying both `sasl` and `tls` blocks under the `client_authentication` configuration block, I get the following error in my `terraform plan`:

```
Error: ConflictsWith

  on ../../modules/kafka/main.tf line 15, in resource "aws_msk_cluster" "kafka_cluster":
  15:     sasl {

"client_authentication.0.sasl": conflicts with client_authentication.0.tls
```

We tried enabling TLS authentication in the AWS console and then removed it, and it left `certificate_authority_arns = []` in the `tls` block. Now Terraform wants to re-create the MSK cluster because it wants to replace `[]` by `null`.

### Expected Behavior

I should be able to specify both options in my Terraform module, as the AWS API accepts both options at the same time.

### Steps to Reproduce

1. Create a Terraform module with an `aws_msk_cluster` resource, and specify both `sasl` and `tls` configuration blocks under `client_authentication`
1. `terraform apply`
1. Notice the `Error: ConflictsWith` message.

### References

The issue seems to come from this line of code:

https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_msk_cluster.go#L133

I can stil see it in the `main` branch of the repo, even though we are not using the latest version of the provider.

**Comment by ewbankkit** [comment]
@thib92 Thanks for raising this issue.
It has already been noticed in #20956. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by gmanjunath** [comment]
Hello Guys,

Quick question, I'm trying to connect DMS to AWS MSK over SSL port (9094) by setting ssl_mode to _verify-ca_ and I'm getting 
_aws_dms_endpoint.target: InvalidParameterCombinationException: SSL settings are invalid for EngineName 'kafka' and EndpointType 'target'_

I know this thread is not related to DMS, but this is related to SSL/TLS support, so wondering if anyone has tested using DMS to connect to AWS MSK over SSL. Any pointers/suggestions will be really helpful.

Many Thanks
Manju
