### ISSUE TITLE
data "aws_iam_policy_document" and other resources are always read during apply

### ISSUE THREAD

**Issue by dreinhardt-terminus** [hashicorp/terraform-provider-aws#21164]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

*Terraform v0.14.11
*hashicorp/aws v3.61.0

### Affected Resource(s)

* aws_iam_policy_document
* aws_lambda_function

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_elasticsearch_domain_policy" "master-company-es-5" {
  domain_name     = aws_elasticsearch_domain.master-company-es-5.domain_name
  access_policies = data.aws_iam_policy_document.master-company-es-5.json
}

data "aws_iam_policy_document" "master-company-es-5" {
  statement {
    resources = [aws_elasticsearch_domain.master-company-es-5.arn]

    principals {
      type = "AWS"

      identifiers = [
        "arn:aws:iam::AWS_ACCOUNT:root",
        aws_iam_user.master-company-user.arn
      ]
    }

    actions = [
      "es:AddTags",
      "es:DescribeElasticsearchDomain",
      "es:DescribeElasticsearchDomains",
      "es:DescribeElasticsearchDomainConfig",
      "es:ListDomainNames",
      "es:ListTags",
      "es:RemoveTags",
      "es:ESHttpDelete",
      "es:ESHttpGet",
      "es:ESHttpHead",
      "es:ESHttpPost",
      "es:ESHttpPut",
    ]

    condition {
      test     = "IpAddress"
      variable = "aws:SourceIp"

      values = [
        var.rack-vpccidr,
      ]
    }

    effect = "Allow"

    sid = "system-access"
  }
}

data "aws_lambda_function" "datadog-forwarder-arn" {
  function_name = aws_cloudformation_stack.datadog_forwarder.name
}

resource "aws_cloudwatch_log_subscription_filter" "datadog-log-subscription-filter-ads-linkedin" {
  name            = "datadog_log_subscription_filter"
  log_group_name  = "LOG_GROUP_NAME"
  destination_arn = data.aws_lambda_function.datadog-forwarder-arn.arn
  filter_pattern  = ""
}
```

### TF Plan Output
```
  # data.aws_iam_policy_document.***-es-5 will be read during apply
  # (config refers to values not yet known)
 <= data "aws_iam_policy_document" "***-es-5"  {
      ~ id      = "2519247774" -> (known after apply)
      ~ json    = jsonencode(
            {
              - Statement = [
                  - {
                      - Action    = [
                          - "es:RemoveTags",
                          - "es:ListTags",
                          - "es:ListDomainNames",
                          - "es:ESHttpPut",
                          - "es:ESHttpPost",
                          - "es:ESHttpHead",
                          - "es:ESHttpGet",
                          - "es:ESHttpDelete",
                          - "es:DescribeElasticsearchDomains",
                          - "es:DescribeElasticsearchDomainConfig",
                          - "es:DescribeElasticsearchDomain",
                          - "es:AddTags",
                        ]
                      - Condition = {
                          - IpAddress = {
                              - aws:SourceIp = [
                                  - "10.30.0.0/16",
                                ]
                            }
                        }
                      - Effect    = "Allow"
                      - Principal = {
                          - AWS = [
                              - "arn:aws:iam::OUR_AWS_ACCOUNT:root",
                              - "arn:aws:iam::OUR_AWS_ACCOUNT:user/ninja-***",
                            ]
                        }
                      - Resource  = "arn:aws:es:us-east-1:OUR_AWS_ACCOUNT:domain/***-es5"
                      - Sid       = "system-access"
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
      - version = "2012-10-17" -> null

      ~ statement {
          - not_actions   = [] -> null
          - not_resources = [] -> null
            # (4 unchanged attributes hidden)


            # (2 unchanged blocks hidden)
        }
    }

# data.aws_lambda_function.datadog-forwarder-arn will be read during apply
  # (config refers to values not yet known)
 <= data "aws_lambda_function" "datadog-forwarder-arn"  {
      ~ architectures                  = [
          - "x86_64",
        ] -> (known after apply)
      ~ arn                            = "arn:aws:lambda:us-east-1:OUR_AWS_ACCOUNT:function:datadog-forwarder" -> (known after apply)
      + code_signing_config_arn        = (known after apply)
      ~ dead_letter_config             = [] -> (known after apply)
      ~ description                    = "Pushes logs, metrics and traces from AWS to Datadog." -> (known after apply)
      ~ environment                    = [
          - {
              - variables = {
                  - "DD_"                       = "datadoghq.com"
                  - "DD_API_KEY_SECRET_ARN"     = "arn:aws:secretsmanager:us-east-1:OUR_AWS_ACCOUNT:secret:DdApiKeySecret-OUR_DD_API_KEY"
                  - "DD_ENHANCED_METRICS"       = "false"
                  - "DD_FETCH_LAMBDA_TAGS"      = "true"
                  - "DD_S3_BUCKET_***ME"         = "datadog-forwarder-forwarderbucket-p2zdpdcf9syp"
                  - "DD_SITE"                   = "datadoghq.com"
                  - "DD_TAGS_CACHE_TTL_SECONDS" = "300"
                  - "DD_USE_PRIVATE_LINK"       = "false"
                  - "DD_USE_VPC"                = "false"
                }
            },
        ] -> (known after apply)
      ~ file_system_config             = [] -> (known after apply)
      ~ handler                        = "lambda_function.lambda_handler" -> (known after apply)
      ~ id                             = "datadog-forwarder" -> (known after apply)
      ~ invoke_arn                     = "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:OUR_AWS_ACCOUNT:function:datadog-forwarder/invocations" -> (known after apply)
      + kms_key_arn                    = (known after apply)
      ~ last_modified                  = "2021-10-05T17:35:46.000+0000" -> (known after apply)
      ~ layers                         = [
          - "arn:aws:lambda:us-east-1:OUR_AWS_ACCOUNT:layer:Datadog-Forwarder:7",
        ] -> (known after apply)
      ~ memory_size                    = 1024 -> (known after apply)
      ~ qualified_arn                  = "arn:aws:lambda:us-east-1:OUR_AWS_ACCOUNT:function:datadog-forwarder:$LATEST" -> (known after apply)
      ~ reserved_concurrent_executions = 100 -> (known after apply)
      ~ role                           = "arn:aws:iam::OUR_AWS_ACCOUNT:role/datadog-forwarder-ForwarderRole-1JAFORCKRMRC9" -> (known after apply)
      ~ runtime                        = "python3.7" -> (known after apply)
      + signing_job_arn                = (known after apply)
      + signing_profile_version_arn    = (known after apply)
      ~ source_code_hash               = "SOURCE_CODE_HASH" -> (known after apply)
      ~ source_code_size               = 133 -> (known after apply)
      ~ tags                           = {
          - "dd_forwarder_version" = "3.39.0"
        } -> (known after apply)
      ~ timeout                        = 120 -> (known after apply)
      ~ tracing_config                 = [
          - {
              - mode = "PassThrough"
            },
        ] -> (known after apply)
      ~ version                        = "$LATEST" -> (known after apply)
      ~ vpc_config                     = [] -> (known after apply)
        # (1 unchanged attribute hidden)
    }

  # aws_cloudformation_stack.datadog_forwarder will be updated in-place
  ~ resource "aws_cloudformation_stack" "datadog_forwarder" {
        id               = "arn:aws:cloudformation:us-east-1:OUR_AWS_ACCOUNT:stack/datadog-forwarder/105ae3e0-2531-11ec-9302-0e4b061813b3"
        name             = "datadog-forwarder"
      ~ parameters       = {
          ~ "DdApiKey"     = "****" -> "***"
            # (1 unchanged element hidden)
        }
        tags             = {}
        # (6 unchanged attributes hidden)
    }

  # aws_cloudwatch_log_subscription_filter.datadog-log-subscription-filter-account-set-crm must be replaced
-/+ resource "aws_cloudwatch_log_subscription_filter" "datadog-log-subscription-filter-account-set-crm" {
      ~ destination_arn = "arn:aws:lambda:us-east-1:OUR_AWS_ACCOUNT:function:datadog-forwarder" -> (known after apply) # forces replacement
      ~ id              = "cwlsf-2452665111" -> (known after apply)
        name            = "datadog_log_subscription_filter"
      + role_arn        = (known after apply)
        # (2 unchanged attributes hidden)
    }
```
### Expected Behavior

None of the resources were changed so the tf plan should indicate no infrastructure changes

### Actual Behavior

Terraform always states the data blocks will be read during apply and some of the resources (using the aws_lambda_function arn are recreated during apply).

### Steps to Reproduce

1.  terraform plan
2. terraform apply
3. terraform plan (without making any changes)

**Comment by justinretzolk** [comment]
Hey @dreinhardt-terminus 👋 Thank you for taking the time to file this issue. It sounds like you may be using values from the data source that can't be determined until the apply phase, as is described in the [data resource behavior](https://www.terraform.io/docs/language/data-sources/index.html#data-resource-behavior) documentation, but it's a bit difficult to say with certainty with the information we have now. 

Can you update the issue description with the output as well, as noted in the [issue template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md) so that we have all of the necessary information to investigate?

**Comment by dreinhardt-terminus** [comment]
> Hey @dreinhardt-terminus 👋 Thank you for taking the time to file this issue. It sounds like you may be using values from the data source that can't be determined until the apply phase, as is described in the [data resource behavior](https://www.terraform.io/docs/language/data-sources/index.html#data-resource-behavior) documentation, but it's a bit difficult to say with certainty with the information we have now.
> 
> Can you update the issue description with the output as well, as noted in the [issue template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md) so that we have all of the necessary information to investigate?

I added in the tf plan output.

**Comment by justinretzolk** [comment]
Hey @dreinhardt-terminus 👋 Thank you for the update. I've got a bit of a breakdown here that I hope will help some. 

### `data "aws_lambda_function" "datadog-forwarder-arn"`

Based on the configuration, this data source is dependent on `aws_cloudformation_stack.datadog_forwarder.name`. In the plan logs, we see that this resource is being updated in place:

```shell
 # aws_cloudformation_stack.datadog_forwarder will be updated in-place
```

Because this dependent resource is being updated in place, Terraform will defer reading the data source until the apply phase. The `resource "aws_cloudwatch_log_subscription_filter"` resource is in turn dependent on the data source for the `destination_arn` argument, leading to the destroy/recreate.

What's unclear based on the information provided is _why_ `aws_cloudformation_stack.datadog_forwarder ` is being updated - is that happening on every run, which would give an indication as to why the data source is read during apply every time?

### `data "aws_iam_policy_document" "master-company-es-5"`

This data source refreshing is a bit more unclear to me. I do see that there are three interpolations: `aws_elasticsearch_domain.master-company-es-5.arn`, `aws_iam_user.master-company-user.arn`, and `var.rack-vpccidr`, but the plan output doesn't seem to indicate a change in any of these. Are any of these values things that would not be known at plan time, which would cause the change? Alternatively, are any of those resources being changed in any way, which would lead to the same situation as mentioned above?

**Comment by justinretzolk** [comment]
Hey @dreinhardt-terminus I think this issue may be relevant to what you're seeing: https://github.com/hashicorp/terraform-provider-aws/issues/10300

As far as the additional configs that you provided, are any of those showing up in the plan output that may have been omitted what you provided previously? And is that data source being read more of an "this is not nice to look at" issue, or is it causing similar resource replacement on every run?

**Comment by dreinhardt-terminus** [comment]
So @justinretzolk do we have a snake eating it's own tail situation? Is there a workaround for this?

**Comment by justinretzolk** [comment]
Thank you for the udpate @dreinhardt-terminus! Since this seems to have ultimately been a combination of a few things that were configuration related, and doesn't seem to be a (new) bug, we're going to go ahead and close this issue for now. If you feel we've done this in error, please do let us know.
