### ISSUE TITLE
target_type alb support for aws_lb_target_group

### ISSUE THREAD

**Issue by msha7518** [hashicorp/terraform-provider-aws#21167]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

target_type "alb" is now available for network load balancer but not yet supported by the terraform resource - aws_lb_target_group

https://aws.amazon.com/about-aws/whats-new/2021/09/application-load-balancer-aws-privatelink-static-ip-addresses-network-load-balancer/

### New or Affected Resource(s)

* aws_lb_target_group

**Comment by ewbankkit** [comment]
@msha7518 Thanks for raising this issue.
It has already been noticed in #21069. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by ewbankkit** [comment]
This functionality is available in **v3.61.0** of the Terraform AWS Provider.
