### ISSUE TITLE
Terraform fails with "remote" backend (TFC) when using AWS SSO

### ISSUE THREAD

**Issue by Computer15776** [hashicorp/terraform-provider-aws#21179]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.60.0

### Affected Resource(s)

N/A

### Terraform Configuration Files

main.tf
```
# Initiate AWS provider
provider "aws" {
  region = var.region
  default_tags {
    tags = module.tags.default_tags
  }
}
```

backend.tf
```
terraform {
  backend "remote" {
    hostname     = "app.terraform.io"
    organization = "acmecorp"

    workspaces {
      prefix = "acmecorp-"
    }
  }
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.60.0"
    }
  }
}
```

### Expected Behavior

Terraform's AWS Provider should have successfully authenticated with the valid, current AWS SSO credentials stored in ~/.aws/sso/cache after approving the login via the web interface.

### Actual Behavior

Terraform errors with the following:
```
╷
│ Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
│
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│
│ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
│       For verbose messaging see aws.Config.CredentialsChainVerboseErrors
│
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on main.tf line 2, in provider "aws":
│    2: provider "aws" {
│
╵
```
### Steps to Reproduce

1. Sign into AWS SSO web panel
2. Run `aws sso login --profile profilename` where profilename is a preexisting AWS SSO profile (via `aws configure sso`)
3. Run terraform apply with remote backend state
4. Terraform errors that it cannot find the credentials required.

### Important Factoids

The remote state is being provided by Terraform Cloud

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/10851 - AWS SSO support was supposedly introduced resulting from this issue, however I am not sure if this precludes the remote backend state.

**Comment by Computer15776** [comment]
@justinretzolk apologies; this was using local execution process, I forgot to remark on that.

**Comment by justinretzolk** [comment]
Hey @Computer15776 👋 Thank you for that - that definitely changes my perspective a bit. You mentioned that this happens when you use the `remote` backend; does the issue not persist if you aren't using the `remote` backend at all?

(apologies; I don't have a AWS SSO setup readily available or I'd just test myself)
