### ISSUE TITLE
Support new ALB-type target_type for Target Groups

### ISSUE THREAD

**Issue by robinsummerhill** [hashicorp/terraform-provider-aws#21175]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS introduced new ALB-type Load Balancer Target Groups on 2021-09-27. This allows ALBs to be placed behind an NLB to utilize NLB features such as PrivateLink integration and Static IP. The previous official solution required using a Lambda function to update target IP attachments, which was complex and error prone.

Adding support for the `alb` target_type would make this use case much easier to set up using Terraform.

### New or Affected Resource(s)

* `aws_lb_target_group`

### Potential Terraform Configuration

```hcl
resource "aws_lb_target_group" "test" {
  name     = "tf-example-lb-tg"
  target_type = "alb"
  ...
}

```

### References

* https://aws.amazon.com/blogs/networking-and-content-delivery/application-load-balancer-type-target-group-for-network-load-balancer/
* https://docs.aws.amazon.com/elasticloadbalancing/latest/network/application-load-balancer-target.html

**Comment by ewbankkit** [comment]
@robinsummerhill Thanks for raising this issue.
It has already been noticed in #21069. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

This functionality is available in **v3.61.0** of the Terraform AWS Provider.
