### ISSUE TITLE
 An argument named "attach_policy" is not expected here.

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#21182]
AS MENTIONED IN TERRAFORM DOCUMENT I AM USING THE ARGUMENT   attach_policy="true" IN MY TERRAFORM CONFIG FILE. when i run terraform plan i get 

  on bucketterraform.tf line 20, in resource "aws_s3_bucket" "creattestbucketshreyaaftp":
│   20:   attach_policy="true"
│
│ An argument named "attach_policy" is not expected here.

Given below is the terraform version that i am currently using:
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.61.0"
    }
  }
}

**Comment by mattburgess** [comment]
Could you post your `bucketterraform.tf` file please? Or `aws_s3_bucket` config for your `createtestbucketshreyaaftp` bucket please?

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket doesn't mention an `attach_policy` attribute so the error looks correct, but it'd be good to see what it is you're trying to do and where you saw an `attach_policy` example. A quick search of the docs suggest that's not a supported attribute on any resource.

**Comment by shreyashi1209** [comment]
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.61.0"
    }
  }
}

provider "aws"{
    region ="eu-west-1"
}



resource "aws_s3_bucket" "creattestbucketshreyaaftp"{
  bucket="ygrtdo"
  acl="private"
  force_destroy="true"

}


resource "aws_cloudfront_origin_access_identity" "newOAI" {
  comment = "OAI User"
}


locals {
  s3_origin_id = "S3AFTPOrigin"
}

resource "aws_cloudfront_distribution" "s3-distribution"{
origin{
    domain_name=aws_s3_bucket.creattestbucketshreyaaftp.bucket_regional_domain_name
    origin_id=local.s3_origin_id
    s3_origin_config {
      origin_access_identity = aws_cloudfront_origin_access_identity.newOAI.cloudfront_access_identity_path
    }

}
enabled             = true
is_ipv6_enabled     = true
default_root_object = "index.html"
aliases=["example.futuretalentplatform.com"]


default_cache_behavior {
    allowed_methods  = ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = local.s3_origin_id

    forwarded_values {
      query_string = false

      cookies {
        forward = "none"
      }
    }

    viewer_protocol_policy = "allow-all"
    min_ttl                = 0
    default_ttl            = 3600
    max_ttl                = 86400
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
      
    }
  }

    viewer_certificate {
    acm_certificate_arn = "arn:aws:acm:us-east-1:128523434494:certificate/cf938fd1-f6e5-400c-8bf7-b67cc5a2d160"
    ssl_support_method  = "sni-only"
  }
  

}

resource "aws_s3_bucket_policy" "s3policyforOAI" {
 bucket = aws_s3_bucket.creattestbucketshreyaaftp.id
# Terraform's "jsonencode" function converts a
  # Terraform expression's result to valid JSON syntax.
  policy = jsonencode({
   Version = "2012-10-17"
    Id      = "MYBUCKETPOLICY"
    Statement = [
      {
        Sid       = "IPAllow"
        Effect    = "Allow"
        Principal = "*"
        Action    = "s3:*"
        Resource = [
          aws_s3_bucket.creattestbucketshreyaaftp.arn,
          "${aws_s3_bucket.creattestbucketshreyaaftp.arn}/*",
        ]
        }
      
    ]
  })
}

When I try terraform apply i get the below error 

Error putting S3 policy: AccessDenied: Access Denied
│       status code: 403, request id: 3M7XC91APC9P1SBH, host id: gRDLs5xquX9pYDF8EaTI7jBFCJqWuqbtQwzsEhVDwFAhvqvNVxq0kiijUVtdbilF5E6FeyQ8E40=
│
│   with aws_s3_bucket_policy.s3policyforOAI,
│   on bucketterraform.tf line 82, in resource "aws_s3_bucket_policy" "s3policyforOAI":
│   82: resource "aws_s3_bucket_policy" "s3policyforOAI" {

To solve this error I was trying to use the argument attach_policy as mentioned in the document

https://registry.terraform.io/modules/terraform-aws-modules/s3-bucket/aws/latest#input_bucket_prefix
