### ISSUE TITLE
Add `name` as an optional argument to `aws_vpc_endpoint`

### ISSUE THREAD

**Issue by tailaiw** [hashicorp/terraform-provider-aws#21183]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As described in the title. `name` would be a handy argument for `aws_vpc_endpoint` to create AWS VPC endpoint resources with custom names. Actually I'm a bit surprised it is not yet (or I miss something here), because an endpoint name can be set via VPC endpoint UI in AWS Console pretty straightforward. 

### New or Affected Resource(s)

* aws_vpc_endpoint

**Comment by mattburgess** [comment]
This, and a lot of other resources, implicitly support having their name on the AWS Console set by using a `Name` tag.

e.g.

```
resource "aws_vpc_endpoint" "s3" {
  vpc_id       = aws_vpc.main.id
  service_name = "com.amazonaws.eu-west-2.s3"

  tags = {
    Name = "s3"
  }
}
```

**Comment by tailaiw** [comment]
Thank you @mattburgess and @justinretzolk. Super helpful workaround!
