### ISSUE TITLE
aws_eks_node_group.instance_types not respecting order for instance_types

### ISSUE THREAD

**Issue by basert** [hashicorp/terraform-provider-aws#21203]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_eks_node_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_eks_node_group" "eks_cluster_node_group_autoscaler" {
  ...
  instance_types  = [
    "m6i.2xlarge",
    "m5.2xlarge",
    "m4.2xlarge",
    "t3.2xlarge"
  ]
  ...
}
```

### Expected Behavior

Instance types should be set in the order given to the node_group. This ensures order of instances for the autoscaling group and lets AWS fallback in the correct order.

### Actual Behavior

List of instances is converted to a Set internally (I guess to ensure uniqueness?) and the given order is lost.

```
# module.eks.aws_eks_node_group.test will be created
  + resource "aws_eks_node_group" "test" {
      + ami_type               = (known after apply)
      + arn                    = (known after apply)
      + capacity_type          = (known after apply)
      + cluster_name           = (known after apply)
      + disk_size              = (known after apply)
      + id                     = (known after apply)
      + instance_types         = [
          + "m4.2xlarge",
          + "m5.2xlarge",
          + "m6i.2xlarge",
          + "t3.2xlarge",
        ]
      + node_group_name        = (known after apply)
      + node_group_name_prefix = (known after apply)
      + node_role_arn          = "<ARN>"
      + release_version        = (known after apply)
      + resources              = (known after apply)
      + status                 = (known after apply)
      + subnet_ids             = [
          <SUBNETS>
        ]
      + version                = "1.21"

      + launch_template {
          + id      = (known after apply)
          + name    = (known after apply)
          + version = (known after apply)
        }

      + scaling_config {
          + desired_size = 10
          + max_size     = 20
          + min_size     = 1
        }

      + update_config {
          + max_unavailable            = (known after apply)
          + max_unavailable_percentage = (known after apply)
        }
    }
```

### Steps to Reproduce

1. `terraform apply`

**Comment by sylr** [comment]
I confirm the issue and I concured that #20532 might be responsible.

It needs to be reverted.
