### ISSUE TITLE
aws_appmesh_mesh data source not working for shared meshes

### ISSUE THREAD

**Issue by gavinclarkeuk** [hashicorp/terraform-provider-aws#21202]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Summary

You cannot use the `aws_appmesh_mesh` datasource with shared meshes. The data source attempts to load tags for the resource based on the ARN, this fails unless the call is coming from the account that owns the mesh. In this scenario it would be better to simply omit the tags, and just return the available data.

### Terraform CLI and Terraform AWS Provider Version

terraform v1.0.8
provider registry.terraform.io/hashicorp/aws v3.61.0

### Affected Resource(s)

* aws_appmesh_mesh (data source)

### Terraform Configuration Files / Steps to Reproduce

To reproduce you need two AWS accounts in the same org. The owner account and the target account.

First create an appmesh in the owner account and share with the target account via RAM. You can do this by running the following terraform in the owner account.

```hcl
resource "aws_appmesh_mesh" "mesh" {
  name = "my-mesh"
}

resource "aws_ram_resource_share" "mesh-share" {
  name                      = "my-mesh"
  allow_external_principals = false
}

resource "aws_ram_resource_association" "share_assocation" {
  resource_arn       = aws_appmesh_mesh.mesh.arn
  resource_share_arn = aws_ram_resource_share.mesh-share.arn
}

resource "aws_ram_principal_association" "dns_share" {
  principal          = <TARGET_ACCOUNT_ID>
  resource_share_arn = aws_ram_resource_share.mesh-share.arn
}
```

Then in the target account try to use the app mesh data source to access the shared mesh.

```hcl
data "aws_appmesh_mesh" "mesh" {
  name       = "my-mesh"
  mesh_owner = <OWNER_ACCOUNT_ID>
}
```

### Expected Behavior

Data source should be able to load details of the mesh (possibly missing some attributes, like tags).

### Actual Behavior

Get an error as per below

```
Error: error listing tags for App Mesh service mesh (arn:aws:appmesh:*********:************:mesh/my-mesh): AccessDeniedException: 
	status code: 403, request id: c0048e53-bc20-4b3d-83be-c1df7a0a5edf
```

### Additional Notes

It looks like the aws provider is using the ListTagsForResource api call under the covers. When I run this using the AWS CLI I logged in to the Target Account I see the following error

`An error occurred (AccessDeniedException) when calling the ListTagsForResource operation: arn:aws:appmesh:eu-west-1:<OWNER_ACCOUNT_ID>:mesh/my-mesh is an invalid ARN. Invalid account id in the ARN provided : <OWNER_ACCOUNT_ID>`

This suggests that the api won't support getting the tags from a different account, even if the mesh is shared.

**Comment by terranisu** [comment]
We've got the same issue with the `aws_appmesh_virtual_service` resource when using a shared appmesh.

```hcl
data "aws_appmesh_virtual_service" "service_name" {
  name       = "service_name.${var.service_discovery_namespace}"
  mesh_name  = var.appmesh_name
  mesh_owner = var.appmesh_owner
}
```

The error occurs:
```
Error: error listing tags for App Mesh Virtual Service (arn:aws:appmesh:***:***:mesh/***@***/virtualService/service_name): AccessDeniedException: 
  status code: 403, request id: xxx
```

### Terraform CLI and Terraform AWS Provider Version
* Terraform `v0.14.11`
* Provider `registry.terraform.io/hashicorp/aws` `v3.75.2`

**Comment by nandha-emis** [comment]
We are facing this in even in AWS provider version 4.49 and terraform version 1.3.7

seems like the issue is long running? as any one found a work around for this?
