### ISSUE TITLE
The terraform-provider-aws_v3.24.1_x5 plugin crashed

### ISSUE THREAD

**Issue by DzmitryKaraba** [hashicorp/terraform-provider-aws#21217]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.24.1
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Terraform potential  configuration
https://gist.github.com/DzmitryKaraba/486fb67f602169d73fdb8dd7438d1ae4

### Affected Resource(s)

* aws_lambda

### Panic Output

https://gist.github.com/DzmitryKaraba/6317bd2b6d7ac1c419a748cfc9e38f5b

### Expected Behavior

After updating local zip file (with python code in my case) I ran  `terraform plan` and then `terraform apply` and expect to update my infrastructure without crashes.

### Actual Behavior
After updating local zip file (with python code in my case) I ran `terraform plan` and then `terraform apply`. But `terraform apply` crashes. After checking the actual code of my lambda function I see that lambda has updated. If I want to update several lambdas some of them get updated (before crash) some don't. 

### Steps to Reproduce

1. Update local zip file with code
2. `terraform apply`

**Comment by justinretzolk** [comment]
Hey @DzmitryKaraba 👋 Thank you for taking the time to file this issue. So that we have all of the necessary information in order to reproduce and look into this, can you update the issue with a reproduction Terraform configuration as well?

**Comment by DzmitryKaraba** [comment]
Updated
