### ISSUE TITLE
Cannot destroy MSK resources

### ISSUE THREAD

**Issue by emilienbtn** [hashicorp/terraform-provider-aws#21240]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Hi All,

We are making some tests to deploy MSK,
Recently we try to destroy one of our clusters and end up with this panic error.

Any ideas where this could be from?

Thank you for your help :)

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.62.0

### Affected Resource(s)

* aws_msk_cluster
* aws_msk_configuration

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  region = var.aws_region
}

terraform {
  backend "s3" {}
}

resource "aws_msk_cluster" "msk_cluster" {
  cluster_name            = var.cluster_name
  kafka_version           = var.kafka_version
  number_of_broker_nodes  = var.num_broker_nodes
  
  broker_node_group_info {
    instance_type       = var.instance_type
    ebs_volume_size  = var.broker_disk_size
    client_subnets      = var.subnet_ids
    security_groups  = var.security_groups
  }

  encryption_info {
    encryption_in_transit {
      client_broker   = "TLS_PLAINTEXT"
    }
  }

  configuration_info {
    arn = aws_msk_configuration.msk_configuration.arn
    revision = aws_msk_configuration.msk_configuration.latest_revision
  }

  enhanced_monitoring = var.enhanced_monitoring

  logging_info {
    broker_logs {
      cloudwatch_logs {
        enabled   = true
        log_group = var.log_group.name
      }
    }
  }

  open_monitoring {
    prometheus {
      jmx_exporter {
        enabled_in_broker = var.open_monitoring
      }
      node_exporter {
        enabled_in_broker = var.open_monitoring
      }
    }
  }

  lifecycle {
    ignore_changes = [broker_node_group_info["ebs_volume_size"]]
  }

  tags = var.tags
}

# https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_configuration
resource "aws_msk_configuration" "msk_configuration" {
  kafka_versions    = [var.kafka_version]
  name              = var.config_name
  server_properties = var.config_properties

  # Allow the update of the configuration when the kafka version changes
  lifecycle {
    create_before_destroy = true
  }
}

# https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appautoscaling_target
resource "aws_appautoscaling_target" "kafka_storage" {
  max_capacity       = var.storage_scaling_max_capacity
  min_capacity       = 1
  resource_id        = aws_msk_cluster.msk_cluster.arn
  scalable_dimension = "kafka:broker-storage:VolumeSize"
  service_namespace  = "kafka"
}

# https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appautoscaling_policy
resource "aws_appautoscaling_policy" "kafka_broker_scaling_policy" {
  name                  = var.scaling_policy_name
  policy_type        = "TargetTrackingScaling"
  resource_id        = aws_msk_cluster.msk_cluster.arn
  scalable_dimension = aws_appautoscaling_target.kafka_storage.scalable_dimension
  service_namespace  = aws_appautoscaling_target.kafka_storage.service_namespace

  target_tracking_scaling_policy_configuration {
    predefined_metric_specification {
      predefined_metric_type = "KafkaBrokerStorageUtilization"
    }

    target_value = var.storage_scaling_target_value
  }
}
```

### Panic Output

https://gist.github.com/emilienbtn/0c3cebcfd7f2390b61badf95ac9a0f0b

### Expected Behavior

The cluster and its configuration should be destroyed

### Actual Behavior

The provider is encountering errors

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform destroy`

### Important Factoids

We also use Terragrunt to trigger terraform modules

**Comment by justinretzolk** [comment]
Hi @emilienbtn 👋 Terraform `v1.0.9` was released yesterday which [includes a fix](https://github.com/hashicorp/terraform/blob/v1.0.9/CHANGELOG.md#109-october-13-2021) that should correct this issue. Can you test again to verify that you're no longer experience this issue?
