### ISSUE TITLE
bug: route_table reports Amazon FSx for NetApp ONTAP service routes and tag as configuration change

### ISSUE THREAD

**Issue by awsaxeman** [hashicorp/terraform-provider-aws#21246]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v1.0.8
aws v3.62.0

### Affected Resource(s)

* aws_route_table

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_route_table" "PrivateRT" {    
    vpc_id = var.vpc
    route {
    cidr_block = "0.0.0.0/0"             
    nat_gateway_id = aws_nat_gateway.NATgw.id
    }
 }

resource "aws_fsx_ontap_file_system" "fsxontap" {
    storage_capacity    = 1024
    subnet_ids          = [var.privatesubnet_1, var.privatesubnet_2]
    deployment_type     = "MULTI_AZ_1"
    throughput_capacity = 512
    preferred_subnet_id = var.privatesubnet_1
    route_table_ids = [aws_route_table.PrivateRT.id]
}
```

### Expected Behavior

When running a `terraform plan` after deploying an aws_fsx_ontap_file_system resource and specifying a terraform managed route_table the output should be **"No changes. Your infrastructure matches the configuration."**

### Actual Behavior

FSx route that is managed by the Amazon FSx for NetApp ONTAP in route table and FSX tag shows as changed. 

"aws_route_table.PrivateRT will be updated in-place"
~ resource "aws_route_table" "PrivateRT" {
 ~ route            = [
 ~ tags             = {
 ~ tags_all         = {

**"Plan: 0 to add, 1 to change, 0 to destroy."**

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### References

* #20778

**Comment by ewbankkit** [comment]
```hcl
provider "aws" {
  ignore_tags {
    keys = ["AmazonFSx"]
  }
}
```

will fix the `tags` diff.

**Comment by ewbankkit** [comment]
To address the `route` diff you could use a separate [`aws_route`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route) resource for the NAT Gateway route (and have no `route`s specified in `aws_route_table`).

**Comment by ewbankkit** [comment]
I ran a _Whois_ on that address range - https://search.arin.net/rdap/?query=198.19.255.23%2F32 - and:

> Addresses starting with "198.18." or "198.19." are set aside for use in isolated laboratory networks used for benchmarking and performance testing. They should never appear on the Internet and if you see Internet traffic using these addresses, they are being used without permission.

**Comment by awsaxeman** [comment]
These are used internally, not over the internet.
