### ISSUE TITLE
Duplicate aws_api_gateway_base_path_mapping resource in state

### ISSUE THREAD

**Issue by wbeuil** [hashicorp/terraform-provider-aws#21252]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With this kind of hcl code nor Terraform nor AWS will output error and it will create in the state the same resource when in AWS it will only have one base path mapping:

```hcl
resource "aws_api_gateway_base_path_mapping" "foo" {
  api_id      = aws_api_gateway_rest_api.foo.id
  stage_name  = aws_api_gateway_stage.foo.stage_name
  domain_name = aws_api_gateway_domain_name.foo.domain_name
}

resource "aws_api_gateway_base_path_mapping" "bar" {
  api_id      = aws_api_gateway_rest_api.foo.id
  stage_name  = aws_api_gateway_stage.foo.stage_name
  domain_name = aws_api_gateway_domain_name.foo.domain_name
  base_path = ""
}
```

Another use case is you can also write this single resource like that:

```hcl
resource "aws_api_gateway_base_path_mapping" "baz" {
  api_id      = aws_api_gateway_rest_api.foo.id
  stage_name  = aws_api_gateway_stage.foo.stage_name
  domain_name = aws_api_gateway_domain_name.foo.domain_name
  base_path = "(none)"
}
```

But in the state you would see an empty base_path and thus the `terraform plan` will want to update the base_path attribute to `(none)`.

In addition, you could create on top of this resource either one of the two first resources of this issue (foo or bar) without any error and resulting in having the same resource in the state twice.

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v1.0.7
on darwin_amd64
```

### Affected Resource(s)

* aws_api_gateway_base_path_mapping

**Comment by justinretzolk** [comment]
Hey @wbeuil 👋 I'm not sure I follow your question - do you mean that you'd like to take on working on a fix for this? If so, by all means! If this will be your first time contributing to the provider, I'd recommend checking out the [contributing guide](https://github.com/hashicorp/terraform-provider-aws/tree/main/docs/contributing) as well.

**Comment by wbeuil** [comment]
> Hey @wbeuil 👋 I'm not sure I follow your question - do you mean that you'd like to take on working on a fix for this? If so, by all means! If this will be your first time contributing to the provider, I'd recommend checking out the [contributing guide](https://github.com/hashicorp/terraform-provider-aws/tree/main/docs/contributing) as well.

Yes I wanted to ask before I start working on it
