### ISSUE TITLE
Add support for recursive flag on datasource aws_ssm_parameters_by_path

### ISSUE THREAD

**Issue by Xerkus** [hashicorp/terraform-provider-aws#21274]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Data source `aws_ssm_parameters_by_path` currently follows default behavior of `aws ssm get-parameters-by-path --path "/path"`. That is, it would return direct descendants of the specified path but not deeper nested results. 

aws cli and aws api has a flag `--recursive` and `"Recursive": boolean` respectively that allow to fetch all of the parameters matching the path.

I would like the `aws_ssm_parameters_by_path` datasource to introduce `recursive` argument to support recursive lookup of ssm parameters.

### New or Affected Resource(s)

* aws_ssm_parameters_by_path

### Potential Terraform Configuration

```hcl
data "aws_ssm_parameters_by_path" "foo" {
  path      = "/foo"
  recursive = true
}
```

### References

* #9429
* #9615
* #9749
* https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParametersByPath.html#API_GetParametersByPath_RequestSyntax

**Comment by sjonpaulbrown** [comment]
I have worked on this on https://github.com/hashicorp/terraform-provider-aws/pull/22222
