### ISSUE TITLE
Support Custom Packages for Amazon OpenSearch Service (ES)

### ISSUE THREAD

**Issue by slawekm** [hashicorp/terraform-provider-aws#21291]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS allows to configure custom packages like synonyms or stopwords dictionaries to be loaded from S3 bucket in Elasticsearch.

Doesn't look like Terraform AWS provider supports this functionality yet.

### New or Affected Resource(s)

* r/aws_elasticsearch_package
* r/aws_elasticsearch_package_association
* d/aws_elasticsearch_package
* d/aws_elasticsearch_packages

### Potential Terraform Configuration

```hcl
resource "aws_elasticsearch_package" "synonyms" {
 # SEE: https://docs.aws.amazon.com/cli/latest/reference/es/create-package.html
 # SEE: https://docs.aws.amazon.com/cli/latest/reference/es/delete-package.html
  name = "synonyms"
  description = "English synonyms" # optional
  type = "TXT-DICTIONARY" # optional

  source {
    bucket = "my_bucket"
    key = "synonyms-en.txt" 
  }
}

/* Note: 

The AWS Web UI seems to be very strict about source S3 path, with the following error returned:

There was an issue importing test3
1 validation error detected: Value 'synonyms/synonyms-en.txt' at 'packageSource.s3Key' failed to satisfy constraint: 
Member must satisfy regular expression pattern: ^(?!^(\\d{1,3}\\.){3}\\d{1,3}$)([a-z0-9][a-z0-9\\.\\-]+[a-z0-9])$

In other words:

s3://my_bucket/synonyms/synonyms-en.txt  - doesn't seems to work
s3://my_bucket/synonyms-en.txt  - works in UI
 
*/

resource "aws_elasticsearch_package_association" "synonyms" {
	# SEE: https://docs.aws.amazon.com/cli/latest/reference/es/associate-package.html
	# SEE: https://docs.aws.amazon.com/cli/latest/reference/es/dissociate-package.html
	domain_name = aws_elasticsearch_domain.this.name
	package_id = aws_elasticsearch_package.synonyms.id
}

data "aws_elasticseach_package" "synonyms" {
	# SEE: https://docs.aws.amazon.com/cli/latest/reference/es/describe-packages.html

	filter {
		name = "PackageID"
		values = ["someid"]
	}

	// or

	filter {
		name = "PackageName"
		values = ["somename"]
	}

	// or

	filter {
		name = "PackageStatus"
		values = ["somestatus"]
	}
}

data "aws_elasticsearch_packages" "this" {
	# SEE: https://docs.aws.amazon.com/cli/latest/reference/es/list-packages-for-domain.html
	domain_name = aws_elasticsearch_domain.this.name
}

```

### References

* https://docs.aws.amazon.com/opensearch-service/latest/developerguide/custom-packages.html
* https://docs.aws.amazon.com/cli/latest/reference/es/index.html#cli-aws-es

**Comment by nkazarian-spokeo** [comment]
Any movement on this initiative? Just was curious, as this is a valid use-case for us. Thanks.
