### ISSUE TITLE
Get IAM user ssh public key

### ISSUE THREAD

**Issue by rgarrigue** [hashicorp/terraform-provider-aws#21316]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'ld like to be able to retrieve the SSH public key associated with an AWS IAM user, like one  can do with https://docs.aws.amazon.com/cli/latest/reference/iam/get-ssh-public-key.html

### New or Affected Resource(s)

* aws iam_user datasource

### Potential Terraform Configuration

None

### References

None

**Comment by kamilturek** [comment]
I'm going to take care of this.
