### ISSUE TITLE
Terraform isn't retrieving parameters from Parameter Store by parent path

### ISSUE THREAD

**Issue by akramfstg** [hashicorp/terraform-provider-aws#21346]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
````
Terraform v1.0.4
````

### Affected Resource(s)

data.aws_ssm_parameters_by_path

### Terraform Configuration Files
````
data "aws_ssm_parameters_by_path" "params" {
  path = "/backend-dev"
}

output "params_arn"{
  value =  data.aws_ssm_parameters_by_path.params.arns
}

````

On the other hand, if I do:

````
data "aws_ssm_parameters_by_path" "params" {
  path = "/backend-dev/service-file-storage-conf"
}

output "params_arn"{
  value =  data.aws_ssm_parameters_by_path.params.arns
}

````
it will retrieve the list of all parameters arns under /backend-dev/service-file-storage-conf (OK)

### Debug Output
````
Outputs:

params_arn = tolist([])
````
### Expected Behavior

It should retrieve all parameters Arns within /backend-dev path

### Actual Behavior

Retrieving empty list

### Steps to Reproduce

1. terraform apply -target data.aws_ssm_parameters_by_path.params

**Comment by djakielskiadesso** [comment]
Same issue on my site!

``` 
terraform version      
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.63.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.3.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.4.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/innovationnorway/git v0.1.3
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
```
