### ISSUE TITLE
Add support for "priority" parameter in aws_appmesh_gateway_route

### ISSUE THREAD

**Issue by mkielar** [hashicorp/terraform-provider-aws#21345]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow providing priorities for Virtual Gateway Routes, similar to how it's possible for Virtual Router Routes.

### New or Affected Resource(s)

* `aws_appmesh_gateway_route`

### Potential Terraform Configuration

```hcl
resource "aws_appmesh_gateway_route" "example" {
  name                 = "example-gateway-route"
  mesh_name            = "example-service-mesh"
  virtual_gateway_name = aws_appmesh_virtual_gateway.example.name

  spec {
    priority = 7  # <<< new attribute!
  
    http_route {
      action {
        target {
          virtual_service {
            virtual_service_name = aws_appmesh_virtual_service.example.name
          }
        }
      }

      match {
        prefix = "/"
      }
    }
  }

  tags = {
    Environment = "test"
  }
}
```

### References

* https://docs.aws.amazon.com/cli/latest/reference/appmesh/create-gateway-route.html (look for `priority`)

**Comment by ckonefke** [comment]
I think this is more than enhancement.  When you have more than one gateway route, you really need them prioritized so they get matched in the proper order.

**Comment by AdamTylerLynch** [comment]
@justinretzolk I'll pick this up.

**Comment by brandocomando** [comment]
Any updates on this?
