### ISSUE TITLE
Athena: support Glue catalogs from other accounts, and external Hive metastores

### ISSUE THREAD

**Issue by tharradine** [hashicorp/terraform-provider-aws#21358]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Athena Data Catalogs can be created in AWS to support access to a number of things from Athena:

- [AWS Glue data catalogs in other AWS accounts](https://docs.aws.amazon.com/athena/latest/ug/security-iam-cross-account-glue-catalog-access.html)
- [External Hive metastores](https://docs.aws.amazon.com/athena/latest/ug/connect-to-data-source-hive.html)

### New or Affected Resource(s)
New resource:

* aws_athena_data_catalog

### Potential Terraform Configuration
This first example is basically just a front for the `athena:CreateDataCatalog` API endpoint, and how that is structured:

```hcl
# Example cross-account Glue data catalog
resource "aws_athena_data_catalog" "datalake" {
  name        = "datalake"
  description = "Cross-account Glue Data Catalog for Data Lake"

  type = "GLUE"
  parameters = {
    "catalog-id" = "123456789012"
  }

  tags = {
    environment = "production"
  }
}

# Example external Hive metastore
resource "aws_athena_data_catalog" "extern_hive" {
  name        = "extern"
  description = "External hive metastore"

  type = "HIVE"
  parameters = {
    "metadata-function" = aws_lambda_function.hive_metadata.arn
    "sdk-version"       = "1.0"
  }

  tags = {
    environment = "production"
  }
}
```

Perhaps a more ergonomic approach is to be more specific in the configuration about which parameters are allowed, like in the following examples. It could turn out to be harder to maintain, however.

```hcl
# Example cross-account Glue data catalog
resource "aws_athena_data_catalog" "datalake" {
  name        = "datalake"
  description = "Cross-account Glue Data Catalog for Data Lake"

  type = "GLUE"

  # Required when type = "GLUE", disallowed otherwise
  glue_configuration {
    catalog_id = "123456789012"
  }

  tags = {
    environment = "production"
  }
}

# Example external Hive metastore
resource "aws_athena_data_catalog" "extern_hive" {
  name        = "extern"
  description = "External hive metastore"

  type = "HIVE"

  # Required when type = "HIVE", disallowed otherwise
  hive_configuration {
    metadata_function = aws_lambda_function.hive_metadata.arn
    sdk_version       = "1.0"
  }

  tags = {
    environment = "production"
  }
}
```

**Comment by matan129** [comment]
Any updates on this?

**Comment by DrFaust92** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/22968
