### ISSUE TITLE
TF plans show changes to db option groups when there are no changes

### ISSUE THREAD

**Issue by rk7373** [hashicorp/terraform-provider-aws#21367]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.13
+ provider registry.terraform.io/hashicorp/aws v3.63.0

### Affected Resource(s)

* aws_db_option_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

sample config
```hcl
resource "aws_db_option_group" "foo" {
  name = "foo"

  option_group_description = "Terraform Option Group"
  engine_name              = "oracle-se2"
  major_engine_version     = "12.1"

  option {
    option_name = "S3_INTEGRATION"
    version     = "1.0"
  }
}
```

### Expected Behavior

Infrastructure matches the TF plan so no differences should be shown in the tf plan for the RDS option group

### Actual Behavior

TF plan shows the RDS option group has changes and will be updated in place
```hcl
# aws_db_option_group.foo will be updated in-place
 ~ resource "aws_db_option_group" "foo" {
 ...
  - option {
     - db_security_group_memberships  = [] -> null
     - option_name                    = "S3_INTEGRATION" -> null
     - port                           = 0 -> null
     - version                        = "1.0" -> null
     - vpc_security_group_memberships = [] -> null
  }
  + option {
    + db_security_group_memberships  = []
    + option_name                    = "S3_INTEGRATION"
    + version                        = "1.0"
    + vpc_security_group_memberships = []
  }
```

### Steps to Reproduce

1. `terraform plan`

**Comment by mrg2k8** [comment]
I had the same issue and fixed it by updating to Terraform v1.0.11 and provider registry.terraform.io/hashicorp/aws v3.54.0.

**Comment by r2c2** [comment]
I still face the issue with terraform v1.011 and aws provider v3.65.0

**Comment by ChastinaLi** [comment]
facing this with aws provider v5.10.0 and terraform v1.3.0
