### ISSUE TITLE
Provider Release: Update to GitHub Actions powered releases

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#21377]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `awscc` provider uses a new [GitHub actions powered](https://github.com/hashicorp/terraform-provider-awscc/blob/main/.github/workflows/release.yml) provider release process. Once we are comfortable with the new process, we should migrate the `aws` provider over.

**Comment by ewbankkit** [comment]
Implemented in https://github.com/hashicorp/terraform-provider-aws/pull/23102.
