### ISSUE TITLE
aws_neptune_cluster - Changing `engine_version` update in place

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#21378]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_neptune_cluster

Recently my team has encountered a Terraform bug when launching `aws_neptune_cluster` resource with Terraform. Basically, when I try to update `engine_version` field, Terraform will force a replacement of the whole Neptune cluster instead of updating in-place.

As we talked with the AWS Neptune team, the cluster should not be replaced with the engine version update. 

### Expected Behavior

Cluster should be updated in place.

### Actual Behavior

Cluster was replaced.

### Steps to Reproduce

1. Launch a aws_neptune_cluster resource with specified engine_version with Terraform.
2. Change the engine_version in the .tf file.
3. Run terraform apply again. It'll show force replacement in planning and the cluster will be destroyed & recreated.

### References

* [resource_aws_neptune_cluster.go](https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_neptune_cluster.go#L139)
* [Neptune Update Docs](https://docs.aws.amazon.com/neptune/latest/userguide/manage-console-updates.html)
* [Neptune Engine Releases Documentation](https://docs.aws.amazon.com/neptune/latest/userguide/engine-releases.html)

**Comment by dh-nickbilozerov** [comment]
We just faced the same issue :( I guess the only way is to do it manually via aws console
