### ISSUE TITLE
aws_cloudwatch_event_target: Add support for Sagemaker Pipeline Parameters

### ISSUE THREAD

**Issue by crlliao** [hashicorp/terraform-provider-aws#21374]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add ability to specify Sagemaker Pipeline Parameters when adding an Eventbridge Event Target. SageMaker Pipeline parameters are used to execute a SageMaker pipeline. Parameter names are static while parameter values can be either a static value or a dynamic JSON path to the event payload.

### New or Affected Resource(s)

* aws_cloudwatch_event_target

### Potential Terraform Configuration

```hcl
resource "aws_cloudwatch_event_target" "sagemaker_pipeline" {
  arn  = "arn:aws:sagemaker:us-east-1:12345678910:pipeline/my_pipeline"
  role_arn = aws_iam_role.events_pipeline_role.arn
  rule = aws_cloudwatch_event_rule.trigger_my_pipeline.id

  sagemaker_pipeline_target {
      pipeline_parameters = {
          ProcessingInstanceType = "ml.c5.2xlarge",
          TrainingInstanceType   = "ml.c5.xlarge",
          InputData = "$.detail.s3bucket",
          EndpointInstanceType = "ml.m5.large"
         }
    } 
}
```

### References

* https://docs.aws.amazon.com/sagemaker/latest/dg/pipeline-eventbridge.html

**Comment by george-chenvibes** [comment]
any updates on this?

**Comment by DrFaust92** [comment]
working on this
