### ISSUE TITLE
General Support for Amazon Lex v2

### ISSUE THREAD

**Issue by SFMichaelR** [hashicorp/terraform-provider-aws#21375]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon release Lex v2 in Jan 2021, with enhanced feature sets that version 1 was not able to address.  Amazon will only be improving and adding new features to the Lex v2 product.  We would like to see the basic features be added to Terraform.

- Creating a bot
- Adding a language
- Adding intents
- Adding slot types
- Creating custom slot types
- Using multiple values in a slot
- Using a Lambda function

### New or Affected Resource(s)

[Lex v2 API](https://docs.aws.amazon.com/lexv2/latest/dg/API_Operations.html)
* aws_lexv2_bot
* These would be new basic bot features.

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* [Terraform Lex v1](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/lex_bot )
* [Amazon Lex v2 API Reference](https://docs.aws.amazon.com/lexv2/latest/dg/API_Reference.html)
* [aws-samples / aws-lex-v2-cfn-cr](https://github.com/aws-samples/aws-lex-v2-cfn-cr) - Amazon Lex V2 CloudFormation Custom Resource

**Comment by khemtr** [comment]
Hi, Is there any target timeline for this? Would be great if someone can share.

**Comment by georgeeckpwc** [comment]
> Hi, Is there any target timeline for this? Would be great if someone can share.

I am also waiting for this - Do the Devs have any updates or timelines ?

**Comment by Manivannant** [comment]
Same here. Any would be great.

> > Hi, Is there any target timeline for this? Would be great if someone can share.
> 
> I am also waiting for this - Do the Devs have any updates or timelines ?

**Comment by robcoward** [comment]
I would rather not have to go down the route of writing cloudformation templates for LexV2 and wrap them in terraform to deploy if I can help it. Is this actively being worked on or should I give in and go the cloudformation route ?

**Comment by schuylr** [comment]
Hi folks, just wanted to point out as a workaround that Lex V2 is available through the `awscc` provider: https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/data-sources/lex_bot 

This is based on the [AWS Cloud Control API](https://aws.amazon.com/cloudcontrolapi/) which wraps the [AWS::Lex::Bot](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lex-bot.html) CFN resource. `AWS::Lex::Bot` targets [Lex V2 resources](https://docs.aws.amazon.com/lexv2/latest/dg/creating-resources-with-cloudformation.html).

**Comment by bliu13** [comment]
@schuylr, Does this seem like [awscc](https://www.hashicorp.com/blog/announcing-terraform-aws-cloud-control-provider-tech-preview) is probably the preferred choice going forward? If this is HashiCorps' intention, I might start looking into moving away from terraform-provide-aws and start porting the existing Terraform scripts to awscc.

**Comment by gregorycottone** [comment]
I'm also waiting for this AMS Lex V2 resources to be developed. Are there any updates and timelines?

**Comment by GPaoloni** [comment]
Any updates on this? We heavily rely on terraform and would be great to use V2 with an official provider.

**Comment by gregorycottone** [comment]
Hi Gianfranco,
no updates unfortunately. At the end we decided to move to CloudFormation.

Sent from Yahoo Mail for iPhone


On Wednesday, June 7, 2023, 9:55 PM, Gianfranco Paoloni ***@***.***> wrote:




Any updates on this? We heavily rely on terraform and would be great to use V2 with an official provider.

**Comment by DogukanZengin** [comment]
I noticed that a resource named `aws_lexv2models_bot` has been added to the AWS provider. However, it seems to be incomplete as there is no documentation available for `bot_locales` or `intents`.

**Comment by richardkyee** [comment]
What is the status of this. We are also waiting for this support

**Comment by si3mshady** [comment]
Damn shame they are dragging their feet on this. Google Dialogflow is FAR superior to lex. That's what I get for blind faith in AWS. Chatbots are blowing up and this is the shittiest i've ever seen AWS handle a product

**Comment by si3mshady** [comment]
Here's a good article concerning workarounds -> https://aws.plainenglish.io/workaround-for-amazon-lex-v2-with-terraform-87d87b808129

**Comment by surfingdoggo** [comment]
> Damn shame they are dragging their feet on this. Google Dialogflow is FAR superior to lex. That's what I get for blind faith in AWS. Chatbots are blowing up and this is the shittiest i've ever seen AWS handle a product

Thanks for the heads up! I'm neck deep in Lex but would not be against changing.

**Comment by nam054** [comment]
The initial set of resources required for LexV2 support is complete. If there are further resources or datasources required or needed, please open a new issue. Thank you!
