### ISSUE TITLE
PANIC: interface conversion: interface {} is nil, not map[string]interface {} in aws_cloudfront_cache_policy

### ISSUE THREAD

**Issue by zaitsevpavel** [hashicorp/terraform-provider-aws#21397]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.63.0

### Affected Resource(s)

* aws_cloudfront_cache_policy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_cloudfront_cache_policy" "some-cache-policy" {
  name        = "some-cache-policy"
  comment     = "To disable CF caching for some-cf-distribution"
  default_ttl = 0
  max_ttl     = 0
  min_ttl     = 0

  parameters_in_cache_key_and_forwarded_to_origin {
    enable_accept_encoding_brotli = false
    enable_accept_encoding_gzip   = false

    cookies_config {
      cookie_behavior = "none"
      cookies {}
    }
    headers_config {
      header_behavior = "none"
      headers {}
    }
    query_strings_config {
      query_string_behavior = "none"
      query_strings {}
    }
  }
}

```

### Debug Output

https://gist.github.com/zaitsevpavel/9fbcb72c43fab7140bbe699582128228

### Panic Output

There is no crash.log, just:
```
PANIC: interface conversion: interface {} is nil, not map[string]interface {}
```

### Expected Behavior

Resource is created.

### Actual Behavior

Panic, resource is not created

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

We use a new resource instead of a managed data-source, because TF always tries to reach AWS even if the flag ```-refresh=false``` set.
I've tried different versions of aws provider, and the bug has been reproduced in the latest provider version.

**Comment by ewbankkit** [comment]
Relates: https://github.com/hashicorp/terraform-provider-aws/issues/20870.

**Comment by yhakbar** [comment]
I ran into this issue while trying to setup a TF module for aws_cloudfront_cache_policy.

The following is a workaround that prevents this error from popping up when the length of the items field under `cookies`, `headers` or `query_strings` is unknown:

```hcl
cookies_config {
      cookie_behavior = var.cookie_behavior
      # Workaround due to provider bug
      # https://github.com/hashicorp/terraform-provider-aws/issues/21397

      # cookies {
      #   items = var.cookies
      # }

      dynamic "cookies" {
        for_each = length(var.cookies) == 0 ? [] : [var.cookies]
        content {
          items = var.cookies
        }
      }
    }
    headers_config {
      header_behavior = var.header_behavior

      # Workaround due to provider bug
      # https://github.com/hashicorp/terraform-provider-aws/issues/21397

      # headers {
      #   items = var.headers
      # }

      dynamic "headers" {
        for_each = length(var.headers) == 0 ? [] : [var.headers]
        content {
          items = var.headers
        }
      }
    }
    query_strings_config {
      query_string_behavior = var.query_string_behavior

      # Workaround due to provider bug
      # https://github.com/hashicorp/terraform-provider-aws/issues/21397

      # query_strings {
      #   items = var.query_strings
      # }

      dynamic "query_strings" {
        for_each = length(var.query_strings) == 0 ? [] : [var.query_strings]
        content {
          items = var.query_strings
        }
      }
    }
```

I'm guessing what this does is bypass the attempted cast here, that will fail if items is not populated with a valid list of strings, but I'm not sure https://github.com/hashicorp/terraform-provider-aws/blob/de17e735f401949c81193571ecb8cd8c44c9b1e9/internal/service/cloudfront/cache_policy_structure.go#L35.
