### ISSUE TITLE
Provider produced inconsistent final plan: .enable_global_write_forwarding: was cty.False, but now null

### ISSUE THREAD

**Issue by MTB90** [hashicorp/terraform-provider-aws#21392]
After we update to provider.aws with version 3.63.0 in which it was added new optional field `enable_global_write_forwarding`
for recource `aws_rds_cluster` we are getting errors on existing environments. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform Version: 1.0.1
provider.aws: version = "~> v3.63.0"

### Affected Resource(s)

* aws_rds_cluster

### Expected Behavior

No provider error

### Actual Behavior

│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.core_infrastructure.module.main_rds_cluster.aws_rds_cluster.this[0]
│ to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .enable_global_write_forwarding: was cty.False, but now null.

### Steps to Reproduce

1. `terraform apply`

**Comment by pduleba** [comment]
# Resolution/Workaround
The way to handle this issue is to perform resource (`aws_rds_cluster`) re-import under desired provider.

# How to do it
```
terraform state list | grep aws_rds_cluster
terraform state show 'ADDRESS' > before-re-import.json

cat before-re-import.json | grep -i id

terraform state rm 'ADDRESS'

terraform import 'ADDRESS' RDS_CLUSTER_NAME

terraform state show 'ADDRESS' > after-re-import.json
```
