### ISSUE TITLE
tech debt: three identical implementations of detaching and deleting ENIs in EC2, ELB, and ELBv2 packages

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#21406]
The same implementations of detaching and deleting ENIs have been used across the EC2, ELB, and ELBv2 packages. These should be consolidated into one function that can be used across multiple packages.

 Since ENIs are part of EC2, the functions should be located in that package.

### Affected Resources

* aws_elb
* aws_lb
* aws_network_interface
* aws_network_interface_attachment

**Comment by ewbankkit** [comment]
There's also `findPublicNetworkInterfacesForVpcID` in `ec2/internet_gateway.go` 😄.

**Comment by ewbankkit** [comment]
`aws_network_interface` and `aws_network_interface_attachment` addressed in #21265.
