### ISSUE TITLE
DynamoDB plan fails with "stream_view_type must be non-empty when stream_enabled = true"

### ISSUE THREAD

**Issue by rogersd** [hashicorp/terraform-provider-aws#21405]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.3
on darwin_amd64
```

```
AWS Provider 3.53.0
```

### Affected Resource(s)

* aws_dynamodb_table

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_dynamodb_table" "foo" {
  name           = "foo"
  billing_mode   = "PAY_PER_REQUEST"
  hash_key       = "PK"
  range_key      = "SK"
  stream_enabled = true

  server_side_encryption {
    enabled = true
  }

  attribute {
    name = "PK"
    type = "S"
  }

  attribute {
    name = "SK"
    type = "S"
  }
}
```

### Expected Behavior

Plan should succeed.

### Actual Behavior

According to https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table, `stream_view_type` is optional.

However, https://github.com/hashicorp/terraform-provider-aws/commit/d26cf176102c93b0df5a713cc47298e1c38f8e52 has made it so that `terraform plan` will fail if `stream_enabled ` is `true` but `stream_view_type` isn't set.

```
 Error: stream_view_type is required when stream_enabled = true
 
   with aws_dynamodb_table.foo,
   on foo.tf line 1, in resource "aws_dynamodb_table" "foo":
    1: resource "aws_dynamodb_table" "foo" {
 
```

### Steps to Reproduce

1. `terraform plan`

**Comment by ewbankkit** [comment]
AWS API reference: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_StreamSpecification.html#DDB-Type-StreamSpecification-StreamViewType.
