### ISSUE TITLE
data aws_db_instances 

### ISSUE THREAD

**Issue by Karabiy** [hashicorp/terraform-provider-aws#21402]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It is currently impossible in terraform to get all the values which are already served in a dynamic way, for the ec2 there exists aws_instances data, but for databases there's no such
aws_db_instances data 
By using it you can store your alerts in a separate terraform repo which would be dedicated only to the team which supplies and supports alarms, for example, as my particular case is to serve dynamic aws_cloudwatch_metric_alarm. 
### New or Affected Resource(s)

aws_db_instances data 

### Potential Terraform Configuration
data "aws_db_instances" "db-instances-of-t-type"{
  filter {
      name = "instance-type"
      values =  ["*t2*","*t3*"]
    }
}

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by kamilturek** [comment]
I'll take this.
