### ISSUE TITLE
Amazon Location Service support

### ISSUE THREAD

**Issue by rochabr** [hashicorp/terraform-provider-aws#21414]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Are you planning to support Amazon Location Service soon, on Terraform? The service has been released in June 2021 and it'd be grat to support it as well.

**Comment by ewbankkit** [comment]
@rochabr Thanks for raising this issue.
It has already been noticed in #19629. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
