### ISSUE TITLE
Can't apply more than 10 input_paths for "aws_cloudwatch_event_target" (Again)

### ISSUE THREAD

**Issue by lamanotrama** [hashicorp/terraform-provider-aws#21429]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/aws v3.27.0

### Affected Resource(s)

* aws_cloudwatch_event_target

### Terraform Configuration Files

```tf
resource "aws_cloudwatch_event_target" "sns" {
  rule = aws_cloudwatch_event_rule.kuroda-test.name
  arn  = aws_sns_topic.kuroda-test.arn

  input_transformer {
    input_paths = {
      account     = "$.account",
      appId       = "$.detail.appId",
      branch      = "$.detail.branchName",
      detail-type = "$.detail-type",
      id          = "$.id",
      jobId       = "$.detail.jobId",
      region      = "$.region",
      resources   = "$.resources",
      source      = "$.source",
      status      = "$.detail.jobStatus",
      time        = "$.time",
      version     = "$.version"
    }

    input_template = <<-PATTERN
    {
      "version": <version>,
      "id": <id>,
      "detail-type": "Amplify <status> build for <appId>/<branch>. For details, go to https://console.aws.amazon.com/amplify/home?region=<region>#<appId>/<branch>/<jobId> ",
      "detail": "",
      "source": <source>,
      "account": <account>,
      "time": <time>,
      "region": <region>,
      "resources": <resources>
    }
    PATTERN
  }
}
```

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Actual Behavior

```
Error: expected number of items in input_transformer.0.input_paths to be less than or equal to 10, got 12

  on cloudwatch.tf line 21, in resource "aws_cloudwatch_event_target" "sns":
  21:     input_paths = {
  22:       account     = "$.account",
  23:       appId       = "$.detail.appId",
  24:       branch      = "$.detail.branchName",

~ snip ~
```

### Steps to Reproduce

1. Create the target  from the console
2. Import the target to the terraform state
3. `terraform plan`

### Important Factoids

This validation seems to have been valid in the past.

- https://github.com/hashicorp/terraform-provider-aws/pull/15669

However, this limitation has now been relaxed on the AWS side.

Ref: https://docs.aws.amazon.com/pt_br/eventbridge/latest/APIReference/API_InputTransformer.html
> InputPathsMap is an array key-value pairs, where each value is a valid JSON path. You can have as many as **100** key-value pairs. You must use JSON dot notation, not bracket notation.

### References

- #10912

**Comment by jordanfinners** [comment]
@lamanotrama Think this is fixed in later version

There's validation here:
https://github.com/hashicorp/terraform-provider-aws/blob/fadc02ffb1d43d3d3d826aa6240874c7d3105393/internal/service/events/target.go#L362

And the limit is set to 100
https://github.com/hashicorp/terraform-provider-aws/blob/fadc02ffb1d43d3d3d826aa6240874c7d3105393/internal/service/events/consts.go#L10

**Comment by lamanotrama** [comment]
The latest version works for me! Thank you!
