### ISSUE TITLE
aws_ec2_transit_gateway_vpc_attachment does not respect setting default route table options to false

### ISSUE THREAD

**Issue by jooh-lee** [hashicorp/terraform-provider-aws#21438]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.6
aws provider v3.63.0

### Affected Resource(s)

* aws_ec2_transit_gateway_vpc_attachment

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
Assume you have 2 aws accounts and have a provider for each

resource "aws_vpc" "vpc" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_subnet" "subnet" {
  vpc_id     = aws_vpc.vpc.id
  cidr_block = "10.0.1.0/24"
}

resource "aws_ec2_transit_gateway" "gateway" {
  auto_accept_shared_attachments  = "disable"
  default_route_table_association = "disable"
  default_route_table_propagation = "disable"
}

resource "aws_ec2_transit_gateway_vpc_attachment" "attacher" {
  subnet_ids         = [aws_subnet.subnet.id]
  transit_gateway_id = aws_ec2_transit_gateway.gateway.id
  vpc_id             = aws_vpc.vpc.id

  transit_gateway_default_route_table_association = false
  transit_gateway_default_route_table_propagation = false
}

resource "aws_ec2_transit_gateway_vpc_attachment_accepter" "acceptor" {
  provider = aws.other_account

  transit_gateway_attachment_id                   = aws_ec2_transit_gateway_vpc_attachment.attacher.id
  transit_gateway_default_route_table_association = false
  transit_gateway_default_route_table_propagation = false
}
```

### Expected Behavior

When `transit_gateway_default_route_table_association` and `transit_gateway_default_route_table_propagation` are set to false the state for those option should set to fase

### Actual Behavior

The options are not respected and the tf state is kept as true. This in turn causes a perpetually dirty plan.

### Steps to Reproduce

1. create a `aws_ec2_transit_gateway_vpc_attachment_accepter` and `aws_ec2_transit_gateway_vpc_attachment` resource.
2. On both resource set `transit_gateway_default_route_table_association` and `transit_gateway_default_route_table_propagation` to false
3. Plan

### References

* #0000

**Comment by jooh-lee** [comment]
@justinretzolk description updated

**Comment by justinretzolk** [comment]
Hey @jooh-lee 👋 Thank you for getting that updated. I've marked this as a bug so that we can take a look into this as soon as time allows.

**Comment by levenaux** [comment]
related #6670

**Comment by dkewley** [comment]
I hit this today with Terraform 1.4.6 and aws provider 4.67.0 -- the latest versions.
