### ISSUE TITLE
Support for AWS Shield Advance Subscriptions

### ISSUE THREAD

**Issue by maunzCache** [hashicorp/terraform-provider-aws#21430]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to use terraform to manage AWS Shield Advance Subscriptions which are available via [the API](https://docs.aws.amazon.com/waf/latest/DDOSAPIReference/API_CreateSubscription.html), which is part of AWS WAF.
General documentation can be found [here](https://docs.aws.amazon.com/waf/latest/developerguide/enable-ddos-prem.html).
Also find information about the [boto library](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/shield.html#Shield.Client.create_subscription) or the [cli reference](https://docs.aws.amazon.com/cli/latest/reference/shield/create-subscription.html).

### New or Affected Resource(s)

* aws_shield_subscription

### Potential Terraform Configuration

```hcl
resource "aws_shield_subscription" "example" {
  name       = "example"
  auto_renew = false # Or true

  tags = {
    Organization = "ACME"
  }
}
```

The resource is more or less useless because there is no return body for it. Also the auto_renew can only be used with the implementation with [UpdateSubscription](https://docs.aws.amazon.com/waf/latest/DDOSAPIReference/API_UpdateSubscription.html).
As well i do not know if tags are supported. [WAF is listed in general](https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/supported-services.html) but not shield.

### References

None

**Comment by maunzCache** [comment]
Hi Bot, this is still an active request as the like counter is going up. So i'll have to recreate this issue. Thanks.

**Comment by mrbobfrog** [comment]
Ping for activity to keep the bot at bay

**Comment by gavreid** [comment]
+1 - we need this

**Comment by okummer** [comment]
Until the feature is implemented, you can can create a subscription like this:

```
resource "null_resource" "aws_shield_create_subscription" {
  provisioner "local-exec" {
    interpreter = ["bash", "-x", "-c"]
    command     = <<EOF
if [ "$(aws shield get-subscription-state --profile ${var.profile_name} --query SubscriptionState --output text)" == INACTIVE ]; then
  echo Creating AWS Shield Advanced subscription ...
  echo aws shield create-subscription --profile ${var.profile_name}
  echo Done.
else
  echo AWS Shield Advanced subscription is already active.
fi
EOF
  }
}
```

Note that a subscription cannot be removed programmatically. You need to open a support case for that. A subscription can cost thousand of dollars per month, so use this code wisely.
