### ISSUE TITLE
Error: cannot elect new source database for replication

### ISSUE THREAD

**Issue by vadzimkaredzinkokoba** [hashicorp/terraform-provider-aws#21450]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.0
on darwin_amd64

+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.63.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

### Affected Resource(s)

RDS instance

### Terraform Configuration Files

The output of terraform plan after creating master and replica, without changes:
```

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # module.********-environment.aws_db_instance.**********_rds_replica_instance[0] has been changed
  ~ resource "aws_db_instance" "**********_rds_replica_instance" {
        id                                    = "staging-rds-replica-mysql"
        name                                  = "staging_**********_database"
      ~ replicate_source_db                   = "arn:aws:rds:eu-west-2:**********:db:staging-rds-multi-mysql" -> "staging-rds-multi-mysql"
        tags                                  = {
            "LambdaStartStopSchedule" = "true"
        }
        # (47 unchanged attributes hidden)
    }
  # module.********-environment.aws_db_instance.**********_rds_multi_instance[0] has been changed
  ~ resource "aws_db_instance" "**********_rds_multi_instance" {
        id                                    = "staging-rds-multi-mysql"
      ~ latest_restorable_time                = "2021-10-22T13:40:00Z" -> "2021-10-22T13:55:00Z"
        name                                  = "staging_**********_database"
        tags                                  = {
            "LambdaStartStopSchedule" = "true"
        }
        # (46 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.

────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.********-environment.aws_cloudwatch_metric_alarm.**********_cloudwatch_rds_cpu_credits[0] will be updated in-place
  ~ resource "aws_cloudwatch_metric_alarm" "**********_cloudwatch_rds_cpu_credits" {
      ~ alarm_description         = "CPU credit balance on RDS cluster in staging environment over last 10 minutes" -> "CPU credit balance on RDS Replica in staging environment over last 10 minutes"
      ~ dimensions                = {
          ~ "DBInstanceIdentifier" = "staging-rds-multi-mysql" -> "staging-rds-replica-mysql"
        }
        id                        = "staging-0-rds-cpu-credit-balance"
        tags                      = {}
        # (16 unchanged attributes hidden)
    }

  # module.********-environment.aws_cloudwatch_metric_alarm.**********_cloudwatch_rds_replica_memory_free[0] will be updated in-place
  ~ resource "aws_cloudwatch_metric_alarm" "**********_cloudwatch_rds_replica_memory_free" {
      ~ alarm_description         = "Freeable memory on RDS cluster in staging environment over last 10 minutes" -> "Freeable memory on RDS Replica in staging environment over last 10 minutes"
      ~ dimensions                = {
          ~ "DBInstanceIdentifier" = "staging-rds-multi-mysql" -> "staging-rds-replica-mysql"
        }
        id                        = "staging-0-rds-free-memory"
        tags                      = {}
        # (16 unchanged attributes hidden)
    }

  # module.********-environment.aws_db_instance.**********_rds_replica_instance[0] will be updated in-place
  ~ resource "aws_db_instance" "**********_rds_replica_instance" {
        id                                    = "staging-rds-replica-mysql"
        name                                  = "staging_**********_database"
      ~ replicate_source_db                   = "staging-rds-multi-mysql" -> "arn:aws:rds:eu-west-2:**********:db:staging-rds-multi-mysql"
        tags                                  = {
            "LambdaStartStopSchedule" = "true"
        }
        # (47 unchanged attributes hidden)
    }

Plan: 0 to add, 3 to change, 0 to destroy.
```
### Expected Behavior

No changes with RDS instances or RDS instance wouldn't be recreated if no change on tf files

### Actual Behavior

RDS instance got recreated after another apply without any change

### Steps to Reproduce

1. terraform apply
2. RDS instance got created
3. terraform apply without any change
4. RDS instance got changes

**Comment by hila3000** [comment]
Any inputs on this bug? it's still happening

**Comment by justinretzolk** [comment]
Hey all 👋 I noticed in the most recent comment from @vadzimkaredzinkokoba, the value of `replicate_source_db` on the replica is set to the ARN of the source DB. Reading the documentation for [replicate_source_db](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#replicate_source_db), I noted:

> This correlates to the `identifier` of another Amazon RDS Database to replicate (if replicating within a single region) or ARN of the Amazon RDS Database to replicate (if replicating cross-region).

It looks like you're operating in the same region; can you test using the `identifier` rather than the `arn` to see if that has any impact?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
