### ISSUE TITLE
Missing argument in sagemaker domain for studio lifecycle configuration

### ISSUE THREAD

**Issue by maldo91** [hashicorp/terraform-provider-aws#21474]
### Terraform CLI and Terraform AWS Provider Version

Current Terraform Version
Terraform v0.12.31

provider.aws v3.63.0
(latest provider)

### Affected Resource(s)
* aws_sagemaker_domain
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_domain

### Use case
Trying to attach a lifecycle configuration to the jupyter_server_app_settings in sagemaker domain I've found out that there is one argument missing:

In Default User Settings --> Jupyter Server App Settings --> Default Resource Spec the argument LifecycleConfigArn is missing, it is available in several aws sagemaker API commands like:

update-domain: https://docs.aws.amazon.com/cli/latest/reference/sagemaker/update-domain.html
create-domain: https://docs.aws.amazon.com/cli/latest/reference/sagemaker/create-domain.html

**Comment by fatboysalimshady** [comment]
not sure if its too late to add the sagemaker app lifecycle config to this issue.. its missing the same argument...
https://docs.aws.amazon.com/cli/latest/reference/sagemaker/create-app.html

**Comment by maldo91** [comment]
Hello @DrFaust92 Can we merge this PR? It's been approved 25 days ago :)
Thanks
