### ISSUE TITLE
RegexMatchStatement not supported for AWS WAFv2

### ISSUE THREAD

**Issue by diasjorge** [hashicorp/terraform-provider-aws#21492]
According to AWS documentation we can match part of the request to a regex. https://docs.aws.amazon.com/waf/latest/APIReference/API_RegexMatchStatement.html

This is currently unsupported in the current provider.

Note that forcing the usage of a patternset is much more expensive in capacity units

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please implement a way to have AWS WAFV2 rules matching a regex as it is possible to do from the console

### New or Affected Resource(s)

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_rule_group

### Potential Terraform Configuration

```hcl
resource "aws_wafv2_rule_group" "main" {
# ....
  regex_match_statement {
    field_to_match {
      uri_path {}
    }
    regex_string = "(\.php|\.cgi)$"
    text_transformations {}
  }
}
```

### References

* #0000

**Comment by wilkmaia** [comment]
If you're interested in this feature, please 👍 this PR :)

https://github.com/hashicorp/terraform-provider-aws/pull/22452
