### ISSUE TITLE
Unable to create aws_cloudfront_cache_policy due to validation error of not provided optional argument 

### ISSUE THREAD

**Issue by william00179** [hashicorp/terraform-provider-aws#21493]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.8
hashicorp/aws v3.63.0

### Affected Resource(s)

* aws_cloudfront_cache_policy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_cloudfront_cache_policy" "index_policy" {
  name        = "index-policy"
  comment     = "Index policy to cache index in Cloudfront but always force the browser to fetch it"
  default_ttl = 86400
  max_ttl     = 31536000
  min_ttl     = 86400
}
```

### Expected Behavior

The policy should be created according to the required fields in the documentation [parameters_in_cache_key_and_forwarded_to_origin](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_cache_policy#parameters_in_cache_key_and_forwarded_to_origin) is an optional argument and I am not providing it 

### Actual Behavior

```
module.global_cloudfront_qa.aws_cloudfront_cache_policy.index_policy: Creating...
╷
│ Error: InvalidParameter: 4 validation error(s) found.
│ - missing required field, CreateCachePolicyInput.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.CookiesConfig.
│ - missing required field, CreateCachePolicyInput.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.EnableAcceptEncodingGzip.
│ - missing required field, CreateCachePolicyInput.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.HeadersConfig.
│ - missing required field, CreateCachePolicyInput.CachePolicyConfig.ParametersInCacheKeyAndForwardedToOrigin.QueryStringsConfig.
│ 
│ 
│   with module.global_cloudfront_qa.aws_cloudfront_cache_policy.index_policy,
│   on .terraform/modules/global_cloudfront_qa/modules/modules/cloud_front/cloud_front.tf line 47, in resource "aws_cloudfront_cache_policy" "index_policy":
│   47: resource "aws_cloudfront_cache_policy" "index_policy" {
```

### Steps to Reproduce

1. `terraform apply`

**Comment by ewbankkit** [comment]
@william00179 Thanks for raising this issue.
You are correct that the [`parameters_in_cache_key_and_forwarded_to_origin`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_cache_policy#parameters_in_cache_key_and_forwarded_to_origin) argument is noted as `Optional` in the documentation and Terraform schema, however because of the way the CloudFront API works, a value is required.
I will update the documentation.
