### ISSUE TITLE
SageMaker Domain - enable SageMaker Projects 

### ISSUE THREAD

**Issue by tomaszdudek7** [hashicorp/terraform-provider-aws#21490]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

re:Invent's 2020 new service called SageMaker Project needs to be enabled through SageMaker Domain (https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-projects-studio-updates.html). Current Terraform configuration does not allow setting that up.

### New or Affected Resource(s)

`aws_sagemaker_domain`

### Potential Terraform Configuration

```hcl
resource "aws_sagemaker_domain" "sagemaker_domain" {
 # ...
  projects {
    enable_templates_for_account = true
    enable_templates_for_users = true
  }
 # ...
}
```

### References

* #0000

**Comment by tonyszhang** [comment]
This is actually a big issue if you're already using Terraform to manage your SageMaker Domain. Now, if you manually enable SM Project templates, the next terraform apply will actually detect a change and try to replace (destroy, create) the SM Domain and all associated user-profiles. This is quite destructive and not zero-downtime.
