### ISSUE TITLE
Support Route53 Resolver UpdateResolverConfig

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#21507]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With the announcement of [Disable default reverse DNS rules with Route 53 Resolver](https://aws.amazon.com/about-aws/whats-new/2021/10/disable-default-reverse-dns-rules-route-53-resolver/), a new [UpdateResolverConfig](https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_UpdateResolverConfig.html) API is available to disable the auto creation of reverse DNS rules.

### New or Affected Resource(s)

`aws_route53_resolver_config`

### Potential Terraform Configuration

```hcl
resource "aws_route53_resolver_config" "example" {
  resource_id = aws_vpc.example.id
  autodefined_reverse_flag = "DISABLE"
}
```

### References
https://aws.amazon.com/about-aws/whats-new/2021/10/disable-default-reverse-dns-rules-route-53-resolver/
https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_UpdateResolverConfig.html

**Comment by desweil** [comment]
any news here? I still have to do weird "hacks" to make it work. In the past I used local-exec workaround (does not work well with people using sometimes "assume-role" and sometimes not), now I spawn a lambda to do boto call from python (requires some hacks to allow IAM role to be created for lambda to run...).
