### ISSUE TITLE
On second running, Terraform removes iam_instance_profile value for a aws_instance created from launch_template 

### ISSUE THREAD

**Issue by igory-bwr** [hashicorp/terraform-provider-aws#21502]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v1.0.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.63.0
```

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

```hcl
data "aws_vpc" "default" {
    id = "vpc-341166a06c"
}

data "aws_subnet" "e2e_public" {
    vpc_id = data.aws_vpc.default.id
    cidr_block = "172.31.16.0/20"
}

resource "aws_launch_template" "e2e_docker_host_lt" {
    name = "e2e-docker-host-lt"
    update_default_version = true

    image_id = "ami-09e67e426f25ce0d7"
    instance_type = "t3.xlarge"
    block_device_mappings {
        device_name = "/dev/sda1"
        ebs {
            volume_size = 50
        }
    }
    key_name = "jenkins"
    iam_instance_profile {
        arn = "arn:aws:iam::222222222222:instance-profile/AutomatedApplicationDeploymentRole"
	}
    network_interfaces {
        security_groups = [ "sg-02062332dd3652800", "sg-077e1cd5e8e954cca" ]
    } 

    user_data =  base64encode(file("files/user-data-e2e-docker-lt.sh"))

    monitoring {
    	enabled = false
    }
    disable_api_termination = false
}

resource "aws_instance" "stage1-locser1" {
    subnet_id = data.aws_subnet.e2e_public.id
    launch_template {
        id = aws_launch_template.e2e_docker_host_lt.id
    }
    lifecycle {
        ignore_changes = [user_data]
    }
    tags = {
        Name = "stage1-logser1"
    }
}
```

### Panic Output

No

### Expected Behavior

Running `terraform plan` after previously succeeded `terraform apply` shouldn't show any updates required

### Actual Behavior

If previous `terraform apply` was succeed, running `terraform plan` shows that terraform tries to remove `iam_instance_profile` from just created aws_instance on previous stage

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### Important Factoids

It looks like terraform icalculates a state of an aws_instance incorrectly for case creating it from a launch_template. it should take all definitions from a launch_template assigned.

It may be related. If remove `lifecycle` block with ignore user_data declaration from aws_instance declaration, terraform starts to recreate the instance on every apply command because user_data base64encoded hash are updated all the time. 

Tnx a lot!
* #0000

**Comment by jeremyweber-np** [comment]
Also seeing this same behavior during my attempts to migrate from launch configurations to launch templates

```
Terraform v1.1.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.71.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

I would add the following info:

* As @igory-bwr mentioned user_data base64encoded hash is updated even when there are no changes.  Thus the need to use 'lifecycle { ignore_changes = [user_data] }'
* In the launch template when i specify iam_instance_profile such as `iam_instance_profile { name = var.iam_instance_profile }`, terraform aws_instance creations from this launch template do not include the profile.  This sounds like issue: https://github.com/hashicorp/terraform-provider-aws/issues/20938
* In the launch template when i specify iam_instance_profile such as `iam_instance_profile { arn  = 'some.arn'}` terraform aws_instance creations from this launch template **do** include the profile, but subsequent plans will attempt to remove it.

Heres a portion of the debug log:

```
2022-01-11T18:08:16.517-0500 [WARN]  Provider "registry.terraform.io/hashicorp/aws" produced an invalid plan for module.xxx.aws_instance.instance[0], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .get_password_data: planned value cty.False for a non-computed attribute
      - .user_data: planned value cty.StringVal("85d4bacaefeff7ed1ec5dabb60b53658831d21ba") does not match config value cty.StringVal("7f96c559df160707bae8ed0f646a7d81605cbdfe") nor prior value cty.StringVal("7f96c559df160707bae8ed0f646a7d81605cbdfe")
      - .source_dest_check: planned value cty.True for a non-computed attribute
      - .hibernation: planned value cty.False for a non-computed attribute
      - .iam_instance_profile: planned value cty.StringVal("") for a non-computed attribute
      - .credit_specification: block count in plan (1) disagrees with count in config (0)
      - .enclave_options: block count in plan (1) disagrees with count in config (0)
      - .capacity_reservation_specification: block count in plan (1) disagrees with count in config (0)
      - .metadata_options: block count in plan (1) disagrees with count in config (0)
      - .root_block_device: block count in plan (1) disagrees with count in config (0)
```

I'd be happy to provide more data as needed.

**Comment by donwoodruff** [comment]
In similar fashion - if tags were created using tag_specifications and "instance" - they will be stripped on the second run as well.
