### ISSUE TITLE
enabling or disabling IAM sasl for MSK should not recreate the cluster

### ISSUE THREAD

**Issue by marcusramberg** [hashicorp/terraform-provider-aws#21535]
<img width="477" alt="image" src="https://user-images.githubusercontent.com/5526/139248192-60606283-08f1-42d7-9975-a996c35456bb.png">

Cloudformation is able to change this without disruption, and you can also do it through the web interface.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.63.0
```

### Affected Resource(s)

* aws_msk_cluster

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

msk should be changed without disruption

### Actual Behavior

msk cluster is recreated. Total data loss.

### Steps to Reproduce

1. `terraform apply`

### References

* PR #19404 Added this functionality.

**Comment by ewbankkit** [comment]
@marcusramberg Thanks for raising this issue.
It has already been noticed in #20956. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
