### ISSUE TITLE
aws_dms_replication_task missing requireds3_setttings cdc_path parameter

### ISSUE THREAD

**Issue by beau-witter** [hashicorp/terraform-provider-aws#21538]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.0
 + provider registry.terraform.io/hashicorp/aws v3.51.0
```
### Affected Resource(s)

```
aws_dms_replication_task
```
### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_dms_replication_task" "etl_s3_to_pg" {
  migration_type            = "full-load-and-cdc"
  replication_instance_arn  = ****
  replication_task_id       = "${local.environment}-${var.app_prefix}-dms-etl-s3-to-pg"
  replication_task_settings = file("${path.module}/dms-conf/s3-to-pg.json")
  source_endpoint_arn       = ****
  target_endpoint_arn       = ****
  table_mappings            = file("${path.module}/dms-conf/s3-to-pg-table-mappings.json")
  tags                      = local.tags
}
```

### Expected Behavior

That a DMS replication task would be created.

### Actual Behavior

```
Error: InvalidParameterValueException: Parameter cdcPath is required when task is configured for ongoing replication with Amazon S3 as a source.
status code: 400, request id: 58947abe-edbf-4db9-9e7c-ed6cc2559ec4
```
### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_replication_task
* #13491

**Comment by ewbankkit** [comment]
@beau-witter Thanks for raising this issue.
It has already been noticed in #13491. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
