### ISSUE TITLE
Route in aws_default_route_tables requires optional parameters

### ISSUE THREAD

**Issue by quercusilvam** [hashicorp/terraform-provider-aws#21536]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.9
on linux_amd64  
provider registry.terraform.io/hashicorp/aws v3.63.0

### Affected Resource(s)

* aws_default_route_tables
* aws_route_tables

### Terraform Configuration Files

Based on example code from https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_route_table#example-usage

```hcl
resource "aws_default_route_table" "not_working" {
  default_route_table_id = var.default_route_table_id

  route = [
    {
      cidr_block = "0.0.0.0/0"
      gateway_id = var.internet_gateway_id
    }
  ]

  tags = {
    Name = var.name
  }
}
```

### Expected Behavior

Code should works and can be validated/apply

### Actual Behavior

Error:
Inappropriate value for attribute "route": element 0: attributes "destination_prefix_list_id", "egress_only_gateway_id", "instance_id", "ipv6_cidr_block", "nat_gateway_id", "network_interface_id",        
│ "transit_gateway_id", "vpc_endpoint_id", and "vpc_peering_connection_id" are required.

### Steps to Reproduce

1. `terraform validate` or `terraform plan`

### Workaround
I found a workaround:

```hcl
resource "aws_default_route_table" "this_works" {
  default_route_table_id = var.default_route_table_id

  route = [
    {
      cidr_block = "0.0.0.0/0"
      gateway_id = var.internet_gateway_id

      #Workaround: Add all optional parameters as nulls
      egress_only_gateway_id     = null
      instance_id                = null
      nat_gateway_id             = null
      network_interface_id       = null
      transit_gateway_id         = null
      vpc_endpoint_id            = null
      vpc_peering_connection_id  = null
      destination_prefix_list_id = null
      ipv6_cidr_block            = null
    }
  ]

  tags = {
    Name = var.name
  }
}
```

* #0000

**Comment by ewbankkit** [comment]
Related: #20756.

@quercusilvam The syntax

```hcl
  route {
      cidr_block = "0.0.0.0/0"
      gateway_id = var.internet_gateway_id
  }
```

should work.
