### ISSUE TITLE
aws_eks_node_group: Support new Bottlerocket AMI types

### ISSUE THREAD

**Issue by z0rc** [hashicorp/terraform-provider-aws#21548]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

EKS added native support of Bottlerocket to Managed Node Groups https://aws.amazon.com/about-aws/whats-new/2021/10/amazon-eks-nodes-groups-bottlerocket/. `aws_eks_node_group` attribute `ami_type` should support new values `BOTTLEROCKET_ARM_64` and `BOTTLEROCKET_x86_64` according to https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html#AmazonEKS-CreateNodegroup-request-amiType

### New or Affected Resource(s)

* aws_eks_node_group

### Potential Terraform Configuration

```hcl
resource "aws_eks_node_group" "workers" {
  ...
  ami_type        = "BOTTLEROCKET_x86_64"
  release_version = "1.3.0-395b459c"
  ...
}
```

**Comment by stuart-blackler-cko** [comment]
Interested in this support + subbing
