### ISSUE TITLE
Missing output when removing count property from resources

### ISSUE THREAD

**Issue by ytsvetkov** [hashicorp/terraform-provider-aws#21549]
### Short Description
We have `route53` resources, which so far had `count` property. Based on this property, we were creating the resources (or skipping the creation). With a recent restructuring, we removed this property and we started creating these resources unconditionally. On the first run, we saw that `output` value, depending on one of these resources was missing.
### Terraform CLI and Terraform AWS Provider
```
$ terraform --version
Terraform v0.12.31

$ terraform providers                                                                                                                      
.                                                                                                                                              
└── provider.aws 
```
### Affected Resource(s)
- aws_route53_zone
- aws_route53_record
- [output value](https://www.terraform.io/docs/language/values/outputs.html)
### Affected Terraform Configurations Before Changes
```
resource "aws_route53_zone" "zone" {
    count = var.skip_route53_integration ? 0 : 1
    name    = var.dns_hostname
    vpc {
        vpc_id  = var.vpc_id
    }
}

resource "aws_route53_record" "dns" {
    count = var.skip_route53_integration ? 0 : 1

    zone_id = aws_route53_zone.connectivity_hosted_zone[0].zone_id
    name    = var.dns_hostname
    type    = "A"

    alias {
        name                   = aws_lb.connectivity_aws_nlb.dns_name
        zone_id                = aws_lb.connectivity_aws_nlb.zone_id
        evaluate_target_health = true
    }
}

output "conn_host" {
    value = var.skip_route53_integration ? aws_lb.connectivity_aws_nlb.dns_name : join("", aws_route53_record.connectivity_dns.*.name)
}
```
###  Affected Terraform Configurations After Changes
```
resource "aws_route53_zone" "zone" {
    name = var.dns_hostname
    vpc {
        vpc_id  = var.vpc_id
    }
}

resource "aws_route53_record" "dns" {
    zone_id = aws_route53_zone.connectivity_hosted_zone.zone_id
    name    = var.dns_hostname
    type    = "A"

    alias {
        name                   = aws_lb.new_connectivity_aws_nlb.dns_name
        zone_id                = aws_lb.new_connectivity_aws_nlb.zone_id
        evaluate_target_health = true
    }
}

output "conn_host" {
    value = join("", aws_route53_record.connectivity_dns.*.name)
}
```
### Expected Behaviour
```
Outputs:

conn_host = sample.host.from.route53.com
security_groups = [
  "sg-0d677a307d7b762f4",
]
```
### Actual Behavior
```
Outputs:

conn_host = 
security_groups = [
  "sg-0d677a307d7b762f4",
]
```
### Workaround
Reapply the change. Doing so we see the message `Apply complete! Resources: 0 added, 0 changed, 0 destroyed.`, however, the string is now displayed.

### Reproducing the issue
We were unable to make a minimal change, that reproduces the issue. The issue is reproducing consistently (that is, every time), but requires a (seemingly) specific initial setup. Apart from the resources mentioned above, additional resources are being created (`aws_lb`, `aws_lb_target_group`, `aws_lb_target_group_attachment` and `aws_lb_listener`). Not sure which additional files/data would be required, and whether they contain sensitive data.

**Comment by justinretzolk** [comment]
Hey @ytsvetkov 👋 Thank you for taking the time to file this issue. In reviewing it, it reads to me like a Terraform issue rather than an issue with the AWS provider specifically. I noticed that you're using a rather old version of Terraform - is it possible for you to test against a newer version of Terraform to see if the issue persists?

I also noted that you didn't remove the splat reference in the output definition when you removed `count`. I would expect that you may need to remove that as well, since you no longer have multiples of the resource from the `count`, and that you wouldn't need the `join()` anymore. Perhaps I'm misreading this, and you have another reason for retaining that, but based on my read, I'd expect rather than this:

```hcl
output "conn_host" {
    value = join("", aws_route53_record.connectivity_dns.*.name)
}
```

...you may need this:

```hcl
output "conn_host" {
    value = aws_route53_record.connectivity_dns.name
}
```

**Comment by ytsvetkov** [comment]
Hello @justinretzolk, thanks for the response. We kept the older `output` structure because we didn't thought that could cause issues, and it seemed to be (semantically) equivalent. Will retest it (hopefully soon) and share whether it makes any difference.

Regarding the Terraform, this is a bit more tricky.  We have no control over the Terraform version that we use, so will have to communicate with others, whether it is possible to provide/test with newer version.

**Comment by ytsvetkov** [comment]
Just tried to `output` as suggested, but the result is a failure (done again with the same old Terraform). The output is the following (I trimmed it a bit):
```
Error: Unsupported attribute
    | aws_route53_record.connectivity_dns is empty tuple
This value does not have any attributes.
```

**Comment by justinretzolk** [comment]
Hey @ytsvetkov 👋 Thank you for the additional updates. I attempted to reproduce this, but so far haven't been able to. To give you an idea, I'm using Terraform `1.0.10` and AWS provider `3.64.1`. I also used a TXT record for simplicity of the reproduction, but otherwise, I think this is pretty close to what you're doing:

```hcl
provider "aws" {
  region = "us-east-1"
}

variable "zone_id" {
  description = "The Zone ID"
}

variable "name" {
  description = "The name to use for the record"
}

resource "aws_route53_record" "test" {
  zone_id = var.zone_id
  name    = var.name
  type    = "TXT"
  ttl     = 300
  records = ["test"]
}

output "test" {
  value = aws_route53_record.test.name
}
```

After a `terraform apply`, I received:

```shell
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

test = "justinretzolktest.tf-support.hashicorpdemo.com"
```
