### ISSUE TITLE
nlb_tg_attachment with alb as target should wait for alb_listener to be created

### ISSUE THREAD

**Issue by lvthillo** [hashicorp/terraform-provider-aws#21558]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v1.0.10
on darwin_amd64
AWS provider version = ">= 3.63.0 "
```

### Affected Resource(s)

* aws_lb_target_group_attachment

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_lb_target_group" "nlb_tg" {
  name        = var.nlb_tg_name
  port        = var.alb_port
  protocol    = "TCP"
  target_type = "alb"
  vpc_id      = var.vpc_id
}

resource "aws_lb_target_group_attachment" "nlb_tg_attachment" {
  target_group_arn = aws_lb_target_group.nlb_tg.arn
  target_id        = var.alb_arn
  port             = var.alb_port
  depends_on = [
    aws_alb_listener.alb_listener,    # depends_on is needed as workaround
  ]
}

...
resource "aws_alb_listener" "alb_listener" {
  load_balancer_arn = aws_lb.aws_alb.arn
  port              = var.alb_port
  protocol          = "HTTP"

  default_action {
    target_group_arn = aws_lb_target_group.alb_tg.arn
    type             = "forward"
  }
}
```

Without the depends_on I'm facing the following error
```
 Error: Error registering targets with target group: ValidationError: If the target type is ALB, the target must have at least one listener that matches the target group port or any specified port overrides
│       status code: 400, request id: xxx

```

**Comment by justinretzolk** [comment]
Hey @lvthillo 👋 Thank you for taking the time to file this issue. You should be able to remove the `depends_on` in favor of an implicit dependency by changing the `aws_lb_target_group_attachment` resource's `port` argument to `aws_alb_listener.alb_listener.port`. Since you're interpolating `var.alb_port` for both at the moment, this wouldn't change the value you wind up with, but would create that implied dependency you're looking for.

**Comment by lvthillo** [comment]
@justinretzolk .. Thanks, I missed that. It works now!

**Comment by EngZaz** [comment]
it looks like resource "aws_alb_listener" is deprecated and became "aws_lb_listener" so doing aws_lb_listener.alb_listener.port worked with me. Thanks all for the post. it helped a lot.
