### ISSUE TITLE
ELB always shows diff with availability zones

### ISSUE THREAD

**Issue by brikis98** [hashicorp/terraform-provider-aws#2156]
### Terraform Version

Terraform v0.10.7

### Affected Resource(s)

- aws_elb

### Terraform Configuration Files

I have a module that contains the following:

```hcl
resource "aws_elb" "example" {
  name = "${var.name}"

  availability_zones = ["${var.availability_zones}"]
  subnets            = ["${var.subnet_ids}"]
}

variable "subnet_ids" {
  type        = "list"
  default     = []
}

variable "availability_zones" {
  type        = "list"
  default     = []
}
```

When using the module, I'm setting the `subnet_ids` parameter, but not the `availability_zones` parameter.

### Expected Behavior

After running `apply`, there are no diffs on subsequent calls to `plan`.

### Actual Behavior

The `plan` command always shows a diff:

```
  ~ module.foo.aws_elb.example
      availability_zones.#:          "6" => "0"
      availability_zones.1252502072: "us-east-1f" => ""
      availability_zones.1305112097: "us-east-1b" => ""
      availability_zones.2762590996: "us-east-1d" => ""
      availability_zones.3551460226: "us-east-1e" => ""
      availability_zones.3569565595: "us-east-1a" => ""
      availability_zones.986537655:  "us-east-1c" => ""
```

My guess is that AWS automatically fills in the AZ settings but because `var.availability_zones` is set to an empty list, Terraform is trying to remove those AZ settings. 

### Steps to Reproduce

1. `terraform apply`
1. `terraform plan`

### Important Factoids

If you try to set *both* the `availability_zones` and `subnets` parameters in `aws_elb`, you get the error:

```
aws_elb.example: ValidationError: Only one of SubnetIds or AvailabilityZones may be specified
```

So there doesn't seem to be a way to create a reusable module around an ELB that allows both subnets and AZs to be configurable.

**Comment by bharti8085** [comment]
resource "aws_elb" "elb" {
  name               = "${var.name}-lb"
  availability_zones = [var.availability_zones]
  subnets            = [var.subnets]
  security_groups    = [var.security_groups]

I am getting above in my tf file. I get below error.

**Error creating ELB: ValidationError: Only one of SubnetIds or AvailabilityZones may be specified
        status code: 400**

I tried removing availability_zones and keeping only subnets then I get below error. 

**The argument "availability_zones" is required, but no definition was found.**

I need help.
