### ISSUE TITLE
Support Auto Scaling groups Attribute-Based Instance Type Selection for EC2 Auto Scaling (aws_autoscaling_group) and EC2 Fleet (aws_spot_fleet_request)

### ISSUE THREAD

**Issue by jnerin** [hashicorp/terraform-provider-aws#21566]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS improved the way you select instance types for autoscaling or fleets, now instead of passing a list of possible instance types you can set some attributes (like min and max VCpuCount, and min and max MemoryMiB among others) and let the ABS (yeah, they named it like that, from attribute-based instance type selection) choose the instances.

### New or Affected Resource(s)

* aws_autoscaling_group
* aws_spot_fleet_request

### Potential Terraform Configuration

```hcl
resource "aws_autoscaling_group" "example" {
  availability_zones = ["us-east-1a"]
  desired_capacity   = 1
  max_size           = 1
  min_size           = 1

  mixed_instances_policy {
    launch_template {
      launch_template_specification {
        launch_template_id = aws_launch_template.example.id
      }

      override {
        instance_requirements {
          vcpu_count {
            min = "2"
            max = "4"
          }
          memory_mib {
            min = "2048"
          }
        }
      }
    }
  }
}
```

### References

- Announcement https://aws.amazon.com/about-aws/whats-new/2021/10/amazon-ec2-instance-auto-scaling-ec2-spot-fleet/
- Blog post https://aws.amazon.com/blogs/aws/new-attribute-based-instance-type-selection-for-ec2-auto-scaling-and-ec2-fleet/
- User guide https://docs.aws.amazon.com/autoscaling/ec2/userguide/create-asg-instance-type-requirements.html
- API docs https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_InstanceRequirements.html
- Go SDK https://github.com/aws/aws-sdk-go/releases/tag/v1.41.12

### Requires
Requires [AWS SDK v1.41.12](https://github.com/aws/aws-sdk-go/releases/tag/v1.41.12)

**Comment by wosiu** [comment]
+1000, some questions though:
Currently if I don't specify [spot_max_price](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#spot_max_price), it is calculated automatically based on the "on-demand" price (and I hope it gets the cheapest instance type I set in `mixed_instances_policy`->`launch_template`->`override` multiple times). How it's going to be calculated if ABS is provided and no specific instance type to refer to?
Or maybe the default behaviour I described is handled on AWS side and not tf provider?

**Comment by gudlyf** [comment]
+1 for sure on this. We're anxious to move to this model, but really cannot until Terraform supports it.

There are also "Additional Instance Attributes" that will need to be supported as part of this, which could be quite extensive (i.e., CPU manufacturers, Memory per vCPU, Instance generation, Instance storage, etc.). This will likely make the implementation a bit complex.

**Comment by mwos-sl** [comment]
Are there any plans or ETA for this one?

**Comment by ahujarajesh** [comment]
Is there any plan to add this support?

**Comment by AdamTylerLynch** [comment]
This change impacts the following resources (3):

1. aws_autoscaling_group
2. aws_ec2_fleet
3. aws_spot_fleet_request

https://aws.amazon.com/about-aws/whats-new/2021/10/amazon-ec2-instance-auto-scaling-ec2-spot-fleet/
