### ISSUE TITLE
aws_security_group inline ingress/egress with IPv4 and IPv6 does not pass validation

### ISSUE THREAD

**Issue by buchs** [hashicorp/terraform-provider-aws#21573]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```text
$ tf -version
Terraform v1.0.10
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.63.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
$ tf validate
╷
│ Error: Incorrect attribute value type
│
│   on main.tf line 141, in resource "aws_security_group" "tableau_sg":
│  141:   ingress = [
│  142:     {
│  143:     description = "port 443"
│  144:     from_port         = 443
│  145:     to_port           = 443
│  146:     protocol          = "tcp"
│  147:     cidr_blocks       = ["0.0.0.0/0"]
│  148:     ipv6_cidr_blocks = ["0::0/0"]
│  149:   },
│  150:   {
│  151:     description = "port 8850 IPv4"
│  152:     from_port   = 8850
│  153:     to_port     = 8850
│  154:     protocol    = "tcp"
│  155:     cidr_blocks = ["0.0.0.0/0"]
│  156:     ipv6_cidr_blocks = ["0::0/0"]
│  157:   }
│  158:   ]
│
│ Inappropriate value for attribute "ingress": element 0: attributes "prefix_list_ids",
│ "security_groups", and "self" are required.
╵
╷
│ Error: Incorrect attribute value type
│
│   on main.tf line 160, in resource "aws_security_group" "tableau_sg":
│  160:   egress = [
│  161:     {
│  162:     from_port = 0
│  163:     to_port = 0
│  164:     protocol = "-1"
│  165:     cidr_blocks = ["0.0.0.0/0"]
│  166:     ipv6_cidr_blocks = ["::/0"]
│  167:   }
│  168:   ]
│
│ Inappropriate value for attribute "egress": element 0: attributes "description",
│ "prefix_list_ids", "security_groups", and "self" are required.
```

What the error message says is required, specifically security_groups, does not make sense for inline security group rules.

[inline.tf.txt](https://github.com/hashicorp/terraform-provider-aws/files/7456351/inline.tf.txt)

**Comment by justinretzolk** [comment]
Hey @buchs 👋 Thank you for taking the time to file this issue. This looks similar to some other issues that I've seen, that I suspect are part of a larger bug, so I tested a possible workaround. When I added each of the attributes that it's complaining about with a `null` value, the validation issues went away.

Added to `ingress`:

```hcl
      prefix_list_ids  = null
      security_groups  = null
      self             = null
```

Added to `egress`:

```hcl
      description      = null
      prefix_list_ids  = null
      security_groups  = null
      self             = null
```

Can you test to see if this works for you as well?
