### ISSUE TITLE
aws_ebs_volume - iops parameter is lost when EBS type changes from io2 to io1 

### ISSUE THREAD

**Issue by kormikez** [hashicorp/terraform-provider-aws#21583]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_ebs_volume

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

Original:
```hcl
resource "aws_ebs_volume" "example" {
  availability_zone = "eu-west-1a"
  size              = 3072
  iops              = 20000
  type              = "io2"
}
```

Modified:
```terraform
resource "aws_ebs_volume" "example" {
  availability_zone = "eu-west-1a"
  size              = 3072
  iops              = 20000
  type              = "io1"
}
```

(`type` change from `io2` to` io1`)

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

Modification is applied and EBS type changes from io2 to io1.

### Actual Behavior

```
Error: InvalidParameterCombination: The parameter iops must be specified for io1 volumes.
	status code: 400, request id: 41c2cc74-d569-47a8-a2e4-cf5121af092f

  on ebs_io1_test.tf line 1, in resource "aws_ebs_volume" "example":
   1: resource "aws_ebs_volume" "example" {
```

### Steps to Reproduce

1. Create an EBS volume with `type = "io2"` along with required parameters.
2. Update the resource to have type of `io1` and apply.

### Important Factoids

n/a

### References

n/a

### Notes
* AWS API does not prevent such change. You can do it via console or CLI without issues.
* Workaround for this is to modify the volume manually and then update TF code.

**Comment by ewbankkit** [comment]
@kormikez Thanks for raising this issue.
It has already been noticed in #20536. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
