### ISSUE TITLE
circular dependency between aws_lb_listener_rule and aws_lb_target_group when replacing aws_lb_target_group

### ISSUE THREAD

**Issue by khumps** [hashicorp/terraform-provider-aws#21588]
When trying to do anything that causes the target group to be replaced (changing the name, port, etc) It detects that the listener rule can be updated in place but the target group can not be deleted until the listener rule is not depending on it. 

The output of the terraform plan/apply is https://pastebin.com/yN6tHvM8 and will result in the provider timing out trying to delete the target group due to the relationship to the listener rule. To fix this, any change to listener_rule.target_group_arn needs to force replacement of the listener rule

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.48.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)
aws_lb_listener_rule 
aws_lb_target_group

### Terraform Configuration Files

```hcl
resource "aws_lb_target_group" "my_target_group" {
  name     = NAME
  port     = PORT
  protocol = "HTTP"
  vpc_id   = VPC_ID
}

resource "aws_lb_listener_rule" "my_listener_rule" {
  listener_arn = var.listener_arn

  action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.my_target_group.arn
  }

  condition {
    host_header {
      values = ["DOMAIN_NAME"]
    }
  }
}
```

### Terraform logs (with TF_LOG=DEBUG)
https://pastebin.com/CZzrTSEc

**Comment by khumps** [comment]
I believe this would be fixed by adding `ForceNew: true` [here](https://github.com/hashicorp/terraform-provider-aws/blob/11c30baeae6fb960add3fee0580bacc38a06064a/internal/service/elbv2/listener_rule.go#L81)

**Comment by justinretzolk** [comment]
Hey @khumps 👋 Thank you for taking the time to file this issue. Can you update the issue description with debug output as well so that we have all of the information necessary to investigate this? 

Additionally, it looks like you may have redacted/changed some of the Terraform config, based on the output you provided (totally understand needing to do this sometimes!). Can you confirm whether `aws_lb_listener_rule.my_listener_rule.action.target_group_arn` is an interpolation of the other resource, or is a hardcoded ARN?

**Comment by khumps** [comment]
> Hey @khumps 👋 Thank you for taking the time to file this issue. Can you update the issue description with debug output as well so that we have all of the information necessary to investigate this?
> 
> Additionally, it looks like you may have redacted/changed some of the Terraform config, based on the output you provided (totally understand needing to do this sometimes!). Can you confirm whether `aws_lb_listener_rule.my_listener_rule.action.target_group_arn` is an interpolation of the other resource, or is a hardcoded ARN?

Hey Justin, I can definitely get some debug input when I get in tomorrow. `LISTENER_ARN` and `TARGET_ARN` are both just substitutions to redact code. in code they actually are a direct reference to a terraform resource

**Comment by khumps** [comment]
@justinretzolk I have appended the relevant part of the debug logs to OP

**Comment by lindlaaa** [comment]
Any update on this? Having a similar issue but with a Listener instead of a Rule.
