### ISSUE TITLE
Default partition_count is null on aws_placement_group in 3.63.0

### ISSUE THREAD

**Issue by bacoboy-doordash** [hashicorp/terraform-provider-aws#21610]
https://github.com/hashicorp/terraform-provider-aws/pull/15360 introduced `partition_count` as "optional" on `aws_placement_group`, but if the `strategy` is `partitioned` then the default says it should be `2`, but is in fact `null` is applied resulting in a force replacement.

```
+/- resource "aws_placement_group" "origin_nodes" {
      ~ arn                = "arn:aws:ec2:us-east-2:XXXXXX:placement-group/my-pg" -> (known after apply)
      ~ id                 = "my-pg" -> (known after apply)
        name               = "my-pg"
      - partition_count    = 2 -> null # forces replacement
      ~ placement_group_id = "pg-07ee5cfebfa8ee032" -> (known after apply)
        # (2 unchanged attributes hidden)
    }

```

**Comment by ewbankkit** [comment]
@bacoboy-doordash Thanks for raising this issue.
It has already been noticed in #21446. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
