### ISSUE TITLE
Support CloudFront response headers policy

### ISSUE THREAD

**Issue by robmoss2k** [hashicorp/terraform-provider-aws#21613]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS now supports response headers policies. Frequently, AWS users create Lambda@Edge functions to add HTTP security headers such as "Strict-Transport-Security". This is [no longer necessary](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/adding-response-headers.html).

### New or Affected Resource(s)

* aws_cloudfront_distribution
* aws_cloudfront_custom_response_headers_policy
* data.aws_cloudfront_managed_response_headers_policy

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
data "aws_cloudfront_managed_response_headers_policy" "example" {
  name = "SecurityHeadersPolicy"
}
resource "aws_cloudfront_custom_response_headers_policy" "example" {
  comment = "Example response headers policy for the documentation"
  cors_config = {
    access_control_allow_credentials = true
    access_control_allow_headers = {
      items = [
        "X-Custom-HTTP-Header"
      ]
    }
    access_control_allow_methods = {
      items = [
        "GET",
        "OPTIONS"
      ]
    }
    access_control_allow_origins = {
      items = [
        "https://example.com",
        "https://docs.example.com"
      ]
    }
    access_control_expose_headers = {
      items = [
        "*"
      ]
    }
    access_control_max_age_sec = 600
    origin_override = false
  }
  custom_headers_config = {
    item {
      header = "Example-Custom-Header-1"
      override = true
      value = "value-1"
    }
    item {
      header = "Example-Custom-Header-2"
      override = true
      value = "value-2"
    }
  }
  name = "EXAMPLE-Response-Headers-Policy"
  security_headers_config = {
    content_security_policy = {
      content_security_policy = "default-src 'none'; img-src 'self'; script-src 'self'; style-src 'self'; object-src 'none'; frame-ancestors 'none'"
      override = false
    }
    content_type_options = {
      override = false
    }
    frame_options = {
      frame_option = "DENY"
      override = false
    }
    referrer_policy = {
      override = false
      referrer_policy = "same-origin"
    }
    strict_transport_security = {
      access_control_max_age_sec = 63072000
      include_subdomains = true
      override = false
      preload = true
    }
    xss_protection = {
      mode_block = true
      override = false
      protection = true
      report_uri = "https://report-uri.example.com"
    }
  }
}
resource "aws_cloudfront_distribution" "managed" {
  ...
  response_headers_policy_id = data.aws_cloudfront_managed_response_headers_policy.example.id
  ...
}
resource "aws_cloudfront_distribution" "custom" {
  ...
  response_headers_policy_id = aws_cloudfront_custom_response_headers_policy.example.id
  ...
}
```

### References

* #0000

**Comment by vasylenko** [comment]
Thanks for that initiative! I would love to see this feature in the provider as well. This new CloudFront offering greatly simplifies the way people manage the customization of the headers.

**Comment by ewbankkit** [comment]
[Announcement](https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-cloudfront-supports-cors-security-custom-http-response-headers/).
[Blog post](https://aws.amazon.com/blogs/networking-and-content-delivery/amazon-cloudfront-introduces-response-headers-policies/).

Requires [AWS SDK v1.41.16](https://github.com/aws/aws-sdk-go/releases/tag/v1.41.16):

* #21595
