### ISSUE TITLE
policy = null does not remove existing resource policy 

### ISSUE THREAD

**Issue by tekumara** [hashicorp/terraform-provider-aws#21611]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.10
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.63.0

### Affected Resource(s)

* aws_secretsmanager_secret

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {}
  }
}
```

### Expected Behavior

When `policy = null` any existing resource policy should be removed.

### Actual Behavior

The existing resource policy remained.

### Steps to Reproduce

1. Apply the following
```hcl
resource "aws_secretsmanager_secret" "password" {
  name        = "alice"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "SecretReader"
        Effect = "Allow"
        Principal = {
          AWS = "*"
        }
        Action = [
          "secretsmanager:GetSecretValue"
        ]
        Resource = "*"
      }
    ] }
  )

  // force delete, so we can recreate the secret immediately if needed
  recovery_window_in_days = 0
}
```
The above will correctly apply the resource policy.

2. Change to `policy = null`

3. Reapply.

The existing policy is not removed.

**Comment by YakDriver** [comment]
The behavior you are seeing is as designed when an argument is `computed`. Blanking it out is basically seen as "I don't want to fill this out, read the value from AWS." However, in my opinion, the policy argument should not be computed so that you can clear it if you want.
