### ISSUE TITLE
`terraform import` fails to import route53 record when name contains underscore in the subdomain

### ISSUE THREAD

**Issue by seletskiy** [hashicorp/terraform-provider-aws#21614]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.10
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.63.0
```

### Affected Resource(s)

* aws_route53_record

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

`terraform import aws_route53_record.test "ZONEID_mail._domainkey.example.com_TXT"` should successfully import existing record from Route53.

### Actual Behavior

```
│ Error: InvalidInput: 1 validation error detected: Value 'domainkey.example.com' at 'startRecordType' failed to satisfy constraint: Member must satisfy enum value set: [AAAA, A, CAA, NS, SOA, SPF, MX, PTR, CNAME, DS, TXT, SRV, NAPTR]
```

### Steps to Reproduce

1. Add any record (e.g. `TXT` in this example) with subdomain that starts with `_` to the Route53, like this: `mail._domainkey.example.com`
2. Try to import it:
    ```bash
      terraform import aws_route53_record.test "ZONEID_mail._domainkey.example.com_TXT"
3. Observe failure:
    ```
    │ Error: InvalidInput: 1 validation error detected: Value 'domainkey.example.com' at 'startRecordType' failed to satisfy constraint: Member must satisfy enum value set: [AAAA, A, CAA, NS, SOA, SPF, MX, PTR, CNAME, DS, TXT, SRV, NAPTR]
    ```

### Important Factoids

N/A

### References

`ParseRecordID` function does not work correctly for domains containing `_`. It has one corner case for domains starting with `_`, but that's not enough.

https://github.com/hashicorp/terraform-provider-aws/blob/aa380055a21e7f374d12ae0617fcdf1aad95f327/internal/service/route53/record.go#L976-L996

Adding following [unit test case](https://github.com/hashicorp/terraform-provider-aws/blob/aa380055a21e7f374d12ae0617fcdf1aad95f327/internal/service/route53/record_test.go#L93) reproduces the error:

```diff
diff --git a/internal/service/route53/record_test.go b/internal/service/route53/record_test.go
index 9d8c98b6fb..3cd629a51e 100644
--- a/internal/service/route53/record_test.go
+++ b/internal/service/route53/record_test.go
@@ -91,6 +91,7 @@ func TestParseRecordId(t *testing.T) {
                {"ABCDEF_test.example.com._A", "ABCDEF", "test.example.com", "A", ""},
                {"ABCDEF_test.example.com_A_set1", "ABCDEF", "test.example.com", "A", "set1"},
                {"ABCDEF__underscore.example.com_A", "ABCDEF", "_underscore.example.com", "A", ""},
+               {"ABCDEF_test._underscore.example.com_A", "ABCDEF", "test._underscore.example.com", "A", ""},
                {"ABCDEF__underscore.example.com_A_set1", "ABCDEF", "_underscore.example.com", "A", "set1"},
                {"ABCDEF__underscore.example.com_A_set_with1", "ABCDEF", "_underscore.example.com", "A", "set_with1"},
                {"ABCDEF__underscore.example.com_A_set_with_1", "ABCDEF", "_underscore.example.com", "A", "set_with_1"},
```

**Comment by ewbankkit** [comment]
@seletskiy Thanks for raising this issue.
It has already been noticed in #16213. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
