### ISSUE TITLE
Add aws_cloudfront_origin_response_header_policy resource

### ISSUE THREAD

**Issue by ZsoltPath** [hashicorp/terraform-provider-aws#21622]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Response header policies are a new feature to Cloudfront.
https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-cloudfront-supports-cors-security-custom-http-response-headers/
https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateResponseHeadersPolicy.html

The aws_cloudfront_distribution also has to be updated to enable assigning the new policy.

### New or Affected Resource(s)

* aws_cloudfront_origin_response_header_policy 
* aws_cloudfront_distribution 

### Potential Terraform Configuration

```hcl
resource "aws_cloudfront_origin_response_header_policy " "example" {
  name    = "example-policy"
  comment = "example comment"
  cors_config {
      access_control_allow_credentials = true
      access_control_allow_headers {
          items = [
            "header1",
            "header2"
            ]
      }
      access_control_allow_methods {
          items = [
            "method1"
            "method2"
            ]
      }
      access_control_allow_origins {
          items = [
            "origin1"
            "origin2"
        ]
      }
      access_control_expose_headers {
          items = [
            "header1",
            "header2"
        ]
      }
      access_control_max_age_sec = 300
      origin_override = false
  }

   custom_headers_config {
       items = [
           response_headers_policy_custom_header = {
               header = "header"
               override = true
               value = "value"
           }
       ]
   }

   security_headers_config {
      content_security_policy {
         content_security_policy = "policy"
         override = true
      }

      content_type_options {
          override = false 
      }
      
      frame_options {
         frame_option = "option"
         override = false 
      }
      
      referrer_policy {
          referrer_policy = "policy"
          override = false 
      }

      strict_transport_security {
         access_control_max_age_sec = 300
         include_subdomains = true
         override = false
         preload = true
      }

      XSS_protection {
        mode_block = false
        override = false
        protection = false
        report_uri = "uri"
      }
    }
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-cloudfront-supports-cors-security-custom-http-response-headers/
* https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateResponseHeadersPolicy.html

**Comment by ewbankkit** [comment]
@ZsoltPath Thanks for raising this issue.
It has already been noticed in #21613. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
