### ISSUE TITLE
kms_key_id = null does not remove KMS key

### ISSUE THREAD

**Issue by tekumara** [hashicorp/terraform-provider-aws#21623]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.10
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.63.0

### Affected Resource(s)

* aws_secretsmanager_secret

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {}
  }
}
```

### Expected Behavior

When `kms_key_id = null` any existing KMS key should be removed.

### Actual Behavior

The existing KMS key remained.

### Steps to Reproduce

1. Apply the following
```hcl
resource "aws_secretsmanager_secret" "password" {
  name        = "alice"

  kms_key_id = "<your key here>"

  // force delete, so we can recreate the secret immediately if needed
  recovery_window_in_days = 0
}
```
The above will create the secret with the kms key.

2. Change to `kms_key_id = null`

3. Reapply.

The change is detected by terraform as "updated in-place" and completes without error. But the secret still has the old KMS key.

**Comment by tiendungitd** [comment]
Got the same issue if remove kms_key_id.

**Comment by jplanza-gr** [comment]
I came across this issue while trying to remove a KMS key from several secrets.  When you don't provide a KMS key, AWS defaults to using `aws/secretsmanager`, the AWS-managed key.  So `kms_key_id = null` is really `kms_key_id = alias/aws/secretsmanager`.  

If you find yourself trying to clean this up across many secrets, this might help:

`aws secretsmanager list-secrets --output text | grep SECRETLIST | awk '{print $2}' | xargs -n1 -J % aws secretsmanager update-secret --secret-id % --kms-key-id alias/aws/secretsmanager`

This will update the keys, but you'll want to run another `terraform apply` to get your state matching the infrastructure (it will remove the alias).  Also note that I haven't filtered for specific secrets here; this will affect *ALL* secrets in the account / region you're authenticated to.
