### ISSUE TITLE
Provider fails to upgrade MWAA Environments from Airflow version 1.10.12 to 2.0.2

### ISSUE THREAD

**Issue by flyjorgemadrid** [hashicorp/terraform-provider-aws#21640]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.2

AWS Provider Version:

```yaml
terraform providers          

Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/aws]
├── module.airflow_security_group
│   └── provider[registry.terraform.io/hashicorp/aws] >= 2.42.0
├── module.airflow_policy
│   └── provider[registry.terraform.io/hashicorp/aws] >= 3.35.0
└── module.airflow_role
    └── provider[registry.terraform.io/hashicorp/aws] >= 3.34.0

Providers required by state:

    provider[registry.terraform.io/hashicorp/aws]
```

### Affected Resource(s)

- aws_mwaa

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```
resource "aws_mwaa_environment" "this" {
  name                  = "${var.name}"
  dag_s3_path           = "${var.dag_s3_path}"
  requirements_s3_path  = "${var.requirements_s3_path}"
  execution_role_arn    = module.airflow_role.iam_role_arn
  airflow_version       = "2.0.2" # <- Create a cluster using version "1.10.12" first, then try to upgrade to 2.0.2
  max_workers           = var.airflow_max_workers
  min_workers           = var.airflow_min_workers
  source_bucket_arn     = aws_s3_bucket.airflow.arn
  webserver_access_mode = "PUBLIC_ONLY"

  airflow_configuration_options = {}

  logging_configuration {
    dag_processing_logs {
      enabled   = var.airflow_dag_processing_log_enabled
      log_level = var.airflow_dag_processing_log_level
    }

    scheduler_logs {
      enabled   = var.airflow_scheduler_log_enabled
      log_level = var.airflow_scheduler_log_level
    }

    task_logs {
      enabled   = var.airflow_task_log_enabled
      log_level = var.airflow_task_log_level
    }

    webserver_logs {
      enabled   = var.airflow_webserver_log_enabled
      log_level = var.airflow_webserver_log_level
    }

    worker_logs {
      enabled   = var.airflow_worker_log_enabled
      log_level = var.airflow_worker_log_level
    }
  }

  network_configuration {
    security_group_ids = concat(
      [module.airflow_security_group.security_group_id],
      var.security_group_ids
    )
    subnet_ids = var.private_subnet_ids
  }
}
```

### Expected Behavior

It should replace the existing MWAA Environment using version 1.10.12 with a new environment using the requested version 2.0.2. 

### Actual Behavior

Terraform fails to try to apply the requested upgrade.

```yaml
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_mwaa_environment.this will be updated in-place
  ~ resource "aws_mwaa_environment" "this" {
      ~ airflow_version                 = "1.10.12" -> "2.0.2"
        id                              = "myenv-prod"
        name                            = "myenv-prod"
        tags                            = {
            "CreatedBy"    = "my"
            "Environment"  = "production"
            "InfraVersion" = "1.0"
            "Module"       = "airflow"
            "Terraform"    = "true"
        }
        # (18 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_mwaa_environment.this: Modifying... [id=myenv-prod]
╷
│ Error: error updating MWAA Environment (myenv-prod): ValidationException: Airflow version 1.10.12 does not support updates to version 2.0.2.
│ 
│   with aws_mwaa_environment.this,
│   on main.tf line 197, in resource "aws_mwaa_environment" "this":
│  197: resource "aws_mwaa_environment" "this" {
│ 
╵
ERRO[0052] 1 error occurred:
        * exit status 1
          
```

### Steps to Reproduce

1. Create a new MWAA environment using `airflow_version = "1.10.12"`
2. Once the environment is provisioned try to upgrade to version 2.0.2 documented [here](https://registry.terraform.io/modules/idealo/mwaa/aws/latest#input_airflow_version).
3. `terraform plan && terraform apply`

### Related

https://github.com/hashicorp/terraform-provider-aws/issues/19816

**Comment by manugarri** [comment]
Any updates on this? Given how AWS just announced a new Airflow MWAA version (2.4.3) Im sure many Devops will see this error in the following weeks.

**Comment by manugarri** [comment]
**update to my previous message** 

Seems like AWS itself doesnt let us update the MWAA environment version, so seems like is not a terraform issue.
<img width="829" alt="image" src="https://user-images.githubusercontent.com/3670355/211006216-6a3e1b34-0b2a-4e45-a337-eccba337af2a.png">

**Comment by sumeeterito** [comment]
> **update to my previous message**
> 
> Seems like AWS itself doesnt let us update the MWAA environment version, so seems like is not a terraform issue. <img alt="image" width="829" src="https://user-images.githubusercontent.com/3670355/211006216-6a3e1b34-0b2a-4e45-a337-eccba337af2a.png">



> Any updates on this? Given how AWS just announced a new Airflow MWAA version (2.4.3) Im sure many Devops will see this error in the following weeks.
> 
> Im getting the error
> 
> ```
> │ Error: error updating MWAA Environment : ValidationException: Airflow version 2.2.2 does not support updates to version 2.4.3.
> ```

Encountered the same issue. I think the only option is to delete the airflow instance and then reinstantiate to an updated version. A real pain when you have a bunch of stored variables already

**Comment by sumanbk92** [comment]
Is there any update on this issue ?
Even I face the same issue upgrading from `v2.2.2` to `v2.4.3` ?

**Comment by Ravindrakumar383** [comment]
we are also facing same issue upgrading from v2.2.2 to v2.4.3 !!

**Comment by manugarri** [comment]
@sumanbk92  @Ravindrakumar383 There is no issue in terraform. AWS doesnt allow upgrading :(.

**Comment by rchui** [comment]
As of June 5, 2023 in place upgrades are now possible: https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-mwaa-in-place-version-upgrades/

**Comment by sumanbk92** [comment]
> As of June 5, 2023 in place upgrades are now possible in 2.x+ environments: https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-mwaa-in-place-version-upgrades/

This is indeed a great news. Thanks for posting the update

**Comment by MayurHadole** [comment]
Submitted enhancement request. https://github.com/hashicorp/terraform-provider-aws/issues/31825
