### ISSUE TITLE
`aws_route_table` with in-line routes returns error complaining missing route target arguments even though they are optional as long as one is provided

### ISSUE THREAD

**Issue by tailaiw** [hashicorp/terraform-provider-aws#21659]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.64.1
```

### Affected Resource(s)

* aws_route_table

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_vpc" "main" {
  cidr_block = "172.28.0.0/16"
}


resource "aws_subnet" "main" {
  vpc_id     = aws_vpc.main.id
  cidr_block = aws_vpc.main.cidr_block
}

resource "aws_internet_gateway" "main" {
  vpc_id = aws_vpc.main.id
}

resource "aws_route_table" "main" {
  vpc_id = aws_vpc.main.id
  route = [
    {
      cidr_block = "0.0.0.0/0"
      gateway_id = aws_internet_gateway.main.id
    }
  ]
}
```

### Expected Behavior

According to [this](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route_table#argument-reference), only one target argument is required in an in-line route definition. So the configuration above is supposed to work. 

### Actual Behavior

I got the following error
```
Error: Incorrect attribute value type
│ 
│   on vpc.tf line 30, in resource "aws_route_table" "main":
│   30:   route = [
│   31:     {
│   32:       cidr_block = "0.0.0.0/0",
│   33:       gateway_id = aws_internet_gateway.main.id
│   34:     }
│   35:   ]
│     ├────────────────
│     │ aws_internet_gateway.main.id will be known only after apply
│ 
│ Inappropriate value for attribute "route": element 0: attributes "carrier_gateway_id", "destination_prefix_list_id", "egress_only_gateway_id", "instance_id", "ipv6_cidr_block", "local_gateway_id",
│ "nat_gateway_id", "network_interface_id", "transit_gateway_id", "vpc_endpoint_id", and "vpc_peering_connection_id" are required.
```

When I added ALL other target arguments with `null` value, it works. Another workaround is to use `aws_route` to add route instead of in-line definition inside `aws_route_table`.

**Comment by justinretzolk** [comment]
Hey @tailaiw 👋 I've seen a few similar issues reported, and I think this ultimately comes down to something we'll need to look at the documentation on (for potential revision). This seems to be related to the resource being processed in [attributes as blocks](https://www.terraform.io/docs/language/attr-as-blocks.html#arbitrary-expressions-with-argument-syntax) mode.

Rather than defining `route` as a list of objects, can you try to define it as an individual block (multiple times, if needed) and see if that resolves your issue? Based on your example, you'd need to update it to:

```hcl
resource "aws_route_table" "main" {
  vpc_id = aws_vpc.main.id

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.main.id
  }
}
```

**Comment by tailaiw** [comment]
@justinretzolk thanks for looking into this. 

Yes, the nested block format works.

**Comment by lokinegalur** [comment]
I created a new aws_route resource
code:
resource "aws_route" "myapp_r" {
  gateway_id = aws_internet_gateway.myapp_igw.id
  route_table_id            = aws_route_table.myapp_rtb.id
  destination_cidr_block    = "0.0.0.0/0"
}
