### ISSUE TITLE
Instance refresh on AWS auto scaling group stuck on pending

### ISSUE THREAD

**Issue by skymilanis** [hashicorp/terraform-provider-aws#21656]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

0.14, 1.0
### Affected Resource(s)

* aws_autoscaling_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
instance_refresh {
    strategy = "Rolling"
    preferences {
      instance_warmup = var.asg_config["ASG_REFRESH_WARMUP"]     #value-->120
      min_healthy_percentage = var.asg_config["ASH_REFRESH_MINHEALTHY"]     #value-->0
    }
  }
```

### Expected Behavior

The auto scaling group should be refreshed when launch template is changed.
This configuration has worked correctly until today.
### Actual Behavior

The istance refresh task stuck on pending.
I noticed that the configuration of checkpoint feature is changed on AWS and I saw that Terraform set in anomalous way the related parameter (checkpoint delay and checkpoint percentages).
### Steps to Reproduce

1. `terraform apply`
2.  The auto scaling group not refresh the ec2 istances

### References

* #0000

**Comment by realies** [comment]
@skymilanis, might be essential to add the values of `var.asg_config`. I'm seeing the same behaviour when using the [official example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#automatically-refresh-all-instances-after-the-group-is-updated) config, which makes me wonder if I have to manually bring the desired capacity to 2 for the instance refresh to continue:

```
resource "aws_autoscaling_group" "example" {
  availability_zones = ["us-east-1a"]
  desired_capacity   = 1
  max_size           = 2
  min_size           = 1

  launch_template {
    id      = aws_launch_template.example.id
    version = aws_launch_template.example.latest_version
  }

  tag {
    key                 = "Key"
    value               = "Value"
    propagate_at_launch = true
  }

  instance_refresh {
    strategy = "Rolling"
    preferences {
      min_healthy_percentage = 50
    }
    triggers = ["tag"]
  }
}
```

**Comment by skymilanis** [comment]
@realies thank you for your feedback. I update with the real value the description of the issue, but consider that this configuration has worked correctly until today.

**Comment by realies** [comment]
@skymilanis, thanks for the details - it's good to know that you had this working using the same config. Do you know when was the last time instance refresh requests were proceeding without getting stuck at pending?

**Comment by skymilanis** [comment]
@realies , the last time instance refresh requests proceeding were on 4th November. I have read the release that you mentioned in your post and it seems related to my issue. In particular, it seems that the optional parameter checkpoint_percentages and checkpoint_delay are not specified, this AWS parameter was set in an inconsistent way.

**Comment by rajneeshkumar-yadav1** [comment]
we are using default latest aws provider version v3.64.2.

everything was working fine till v3.63.0.

now i have fixed the version to v3.63.0 its started working as expected

**Comment by shahadc** [comment]
Hello,
The root cause of this issue is an error with the AutoScaling service when a blank checkpoint array was included in the input parameters.  We are aware of this issue and working on a fix, once that is deployed the new aws provider version should work correctly with AutoScaling Instance Refresh's

**Comment by realies** [comment]
@shahadc, thanks for the update. When is v3.66.0 to be released?

**Comment by shahadc** [comment]
@realies I am not from Hashicorp, so I'm unsure when any new AWS provider versions will be released.  The change I was referring to was on the AWS side of things.  It will fix the errors that happened when the blank CheckPoint information was added in the new provider version, so no new AWS Provider version will be needed

**Comment by lystopad** [comment]
> @shahadc, thanks for the update. When is v3.66.0 to be released?

Hi, 
It is already released on November 18, 2021.
I tested and it works now as expected.
