### ISSUE TITLE
aws_eks_node_group desired_size config does not update aws

### ISSUE THREAD

**Issue by cdobbyn** [hashicorp/terraform-provider-aws#21668]
### Terraform CLI and Terraform AWS Provider Version
Confirmed in terraform 1.0.10 and 0.14.11
aws provider 3.63.0

### Affected Resource(s)
* aws_eks_node_group

### Terraform Configuration Files
Just use the example from the docs.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
When you change the desired_size, it should actually update that config in aws and not just in terraform state.

### Actual Behavior
Terraform state updates, but if you go look in aws console the configuration did not change. This causes additional problems if you try to increase min size and desired size, terraform will fail indicating that desired size is lower then min size. To update this configuration requires manually updating the console and then making terraform match afterword (which defeats the purpose).

### Steps to Reproduce
1. `terraform apply`
2. update the desired_size to a value higher
3. `terraform apply`
4. run `terraform plan` and verify that no changes are required
5. check aws console to see if desired_size has been updated

### Important Factoids
We have observed this behavior with ASGs as well, this could be an AWS API or SDK issue.

### References
None that I could see.

**Comment by justinretzolk** [comment]
Hey @cdobbyn 👋 Thank you for taking the time to file this issue! So that we have all of the information necessary to look into this, would it be possible for you to update the issue description with debug output (scrubbed, as needed) as well?

**Comment by cdobbyn** [comment]
Hey @justinretzolk sorry for taking so long to get back. I wasn't able to share our debug output with that cluster I was working with when I posted this. I will have a state that is isolated to just a cluster soon and I can get this output from that.

**Comment by mleklund** [comment]
I ran into this today, and unfortunately after running with debug logging there was nothing interesting of note.  It simply did not see a difference after changing desired_size.

```
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.9.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.5.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.10.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/hashicorp/tls v3.3.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
```

**Comment by mattburgess** [comment]
@cdobbyn I'm unable to replicate this using the latest version of the Terraform provider. I started with a desired size of 1, then changed it to 3 and got this output:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated
with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_eks_node_group.example will be updated in-place
  ~ resource "aws_eks_node_group" "example" {
        id              = "example:example"
        tags            = {}
        # (15 unchanged attributes hidden)

      ~ scaling_config {
          ~ desired_size = 1 -> 3
            # (2 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_eks_node_group.example: Modifying... [id=example:example]
aws_eks_node_group.example: Still modifying... [id=example:example, 10s elapsed]
aws_eks_node_group.example: Modifications complete after 14s [id=example:example]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

And, sure enough, the console and TF state shows a desired size of 3 and I see an extra 2 instances spin up shortly thereafter.

Note that the docs do have an [example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#ignoring-changes-to-desired-size) of how to ignore changes to that `desired_size` parameter (useful if you have the cluster autoscaler up and running!) so if you've copied and pasted from there then that might be affecting things.

**Comment by cdobbyn** [comment]
I think the problem occurs when you change multiple settings and not just desired_size. i.e. changing min/max size at the same time. I have also noted that changing desired_size along with min/max size so that desired_size is outside of the original boundary but valid in the new boundary will result in an error indicating it's outside of the size constraint.

I have noted this issue with as recent as 4.49.0 provider.

**Comment by cdobbyn** [comment]
Nevermind, this actually turned out to be related to a module I was using (cloudposse eks node group). Closing.

**Comment by StephanX** [comment]
I've still had to hack the module myself, per https://github.com/hashicorp/terraform-provider-aws/issues/25486 .  I can try and re-test/verify with the latest version.
