### ISSUE TITLE
aws_cloudfront_response_headers_policy doc: Strict Transport Security and XSS

### ISSUE THREAD

**Issue by mhgeay** [hashicorp/terraform-provider-aws#21660]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform Cloud v1.0.7 with AWS provider v3.64.2

### Affected Resource(s)

* [Documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_response_headers_policy) of aws_cloudfront_response_headers_policy

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

In the doc:

- for "XSS Protection", "report_uri" field is a String, not a Boolean and _you cannot specify a ReportUri when ModeBlock is true._ ; source : [AWS docs](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_ResponseHeadersPolicyXSSProtection.html)
- Under "Security Headers Config", the "Strict Transport Security" summary is missing (but the detail is present).

### Actual Behavior

For XSS issue, when I set True for mode_block and report_uri:  
```
xss_protection {
      mode_block = true
      override   = true
      protection = true
      report_uri = false
}
```

I got the AWS API error : 
`Error: error creating CloudFront Response Headers Policy (xxxx): InvalidArgument: The parameter X-XSS-Protection cannot contain both Report URI and Mode block.`

### References

N/A

**Comment by trevorrea** [comment]
I have to agree here @mhgeay that the docs are not very good. There is some weird formatting too where it says

```
referrer_policy - (Optional) **TA setting** that determines whether CloudFront includes the Referrer-Policy HTTP response header and the header’s value. See Referrer Policy for more information.
xss_protection - (Optional) **TSettings** that determine whether CloudFront includes the X-XSS-Protection HTTP response header and the header’s value. See XSS Protection for more information
```
Not sure if Tsettings or TA setting is supposed to mean something? There is also no example for custom_headers which would be helpful.

**Comment by justinretzolk** [comment]
Hey y'all 👋 Thank you for reporting this. I've opened a PR to address some of the concerns here, specifically around the odd formatting, missing references, and that `xss_protection` bit.

**Comment by trevorrea** [comment]
Thanks Jason. Can you add an example for custom_headers_config? This took me such a long time to figure out as the docs say 

custom_headers_config - Object that contains an attribute items that contains a list of Custom Headers See Custom Header for more information.

That doesn't really map to what actually works. I read that as what's below but maybe that's just me :)

```
custom_headers_config {
  items  = [
    {
      header = "X-Permitted-Cross-Domain-Policies"
      override = true
      value = "none"
    },
    {
      header = "X-Test"
      override = true
      value = "none"
    }
  ]
}
```

**Comment by justinretzolk** [comment]
Hey @trevorrea - thanks for that additional input. Did you receive any particular errors when you tried the config that you mentioned in your last comment? Frankly, I read it the same way, and would have expected that to work.

**Comment by mhgeay** [comment]
@justinretzolk, I agree with @trevorrea for `custom_headers_config`, it's not clear how to use items, an example should be great.
I tried the following config without error
```
  custom_headers_config {
    items {
      header   = "Expect-CT"
      value    = "enforce, max-age=3600"
      override = true
    }

    items {
      header   = "Permissions-Policy"
      value    = "accelerometer=()"
      override = true
    }
  }
}
```

**Comment by trevorrea** [comment]
The plan fails with:-

│ Error: Unsupported argument
│
│   on cloudfront_response_headers_policy_this.tf line 5, in resource "aws_cloudfront_response_headers_policy" "this:
│    5:     items  = [
│
│ An argument named "items" is not expected here. Did you mean to define a block of type "items"?
╵
ERROR: Terraform plan failed

**Comment by justinretzolk** [comment]
Thank you to both of you for the additional information! I'll work on getting the `custom_headers_config` bits added to my PR as well; I agree that it seems prudent to include!

**Comment by mhgeay** [comment]
@trevorrea, indeed I got the same "encoded comma" issue.
I just tried trough AWS console and I didn't have the issue. I think it should be another GitHub issue.
