### ISSUE TITLE
Add tls_version_and_cipher_suite to ALB

### ISSUE THREAD

**Issue by ericrichtert** [hashicorp/terraform-provider-aws#21666]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add tls_version_and_cipher_suite to the ALB

### New or Affected Resource(s)

* aws_lb

### Potential Terraform Configuration

```hcl
resource "aws_lb" "test" {
  name               = "test-lb-tf"
  internal           = false
  load_balancer_type = "application"
  security_groups    = [aws_security_group.lb_sg.id]
  subnets            = aws_subnet.public.*.id

  enable_deletion_protection = true

  tls_version_and_cipher_suite = true

  access_logs {
    bucket  = aws_s3_bucket.lb_logs.bucket
    prefix  = "test-lb"
    enabled = true
  }

  tags = {
    Environment = "production"
  }
}```

### References

**Comment by captainfalcon23** [comment]
Super keen on this feature! Following - hopefully your PR gets merged soon.

**Comment by ewbankkit** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/29792.
