### ISSUE TITLE
cannot import aws_cloudwatch_log_subscription_filter 

### ISSUE THREAD

**Issue by daugustus** [hashicorp/terraform-provider-aws#21678]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.64.0

### Affected Resource(s)

* aws_cloudwatch_log_subscription_filter

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
variable "function_name" {
  type        = string
  description = "A unique name for your Lambda Function."
  default    = "myendpoint"
}

resource "aws_lambda_function" "this" {
  function_name = var.function_name
  description   = var.description
}

resource "aws_cloudwatch_log_group" "this" {
  name              = "/aws/lambda/${var.function_name}"
  retention_in_days = var.log_retention
  tags              = local.tags
}

resource "aws_cloudwatch_log_subscription_filter" "this" {
  name            = var.function_name
  role_arn        = var.logging_role_arn
  log_group_name  = aws_cloudwatch_log_group.this.name
  filter_pattern  = var.logging_pattern
  destination_arn = var.logging_stream_arn
  distribution    = "ByLogStream"

  depends_on = [
    aws_cloudwatch_log_group.this
  ]
}
```

### Expected Behavior

running the import command fails:
`terragrunt import module.myendpoint_lambda.aws_cloudwatch_log_subscription_filter.this myendpoint`

### Actual Behavior

`Error: unexpected format of ID ("myendpoint"), expected <log-group-name>|<filter-name>`

I have tried each of these variants without success:
`terragrunt import module.myendpoint_lambda.aws_cloudwatch_log_subscription_filter.this myendpoint`
`terragrunt import module.myendpoint_lambda.aws_cloudwatch_log_subscription_filter.this /var/lambda/myendpoint`

### Steps to Reproduce

1. `terraform import aws_cloudwatch_log_subscription_filter yourLogName `

**Comment by DrFaust92** [comment]
Hi,

Have you tried `terragrunt import module.myendpoint_lambda.aws_cloudwatch_log_subscription_filter.this /var/lambda/myendpoint|myendpoint` ?

**Comment by justinretzolk** [comment]
Hey @daugustus 👋 Thank you for taking the time to file this issue. Based on what you've provided, [it looks like](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_subscription_filter#import) the format that's expected would be as the below example shows, assuming:

-  `/var/lambda/myendpoint` is your log group name (I can't tell what the value is based on the issue description alone, since it's interpolated from `aws_cloudwatch_log_group.this.name`)
- `myendpoint` is the filter-name (same as the other; I can't tell what the actual value is, but it's whatever `var.function_name` expands out to)

Example:

```shell
$ terraform import module.myendpoint_lambda.aws_cloudwatch_log_subscription_filter.this /var/lambda/myendpoint|myendpoint
```

Note: depending on your shell, you may need to wrap the final bit in single quotes so that your shell doesn't interpret the pipe `|` in unexpected ways.

**Comment by daugustus** [comment]
Yes that works.

I am just used to the pipe command NOT being a cli argument and/or the regex value for "OR".

I was able to successfully import the resources using the format suggested.

Thanks!

**Comment by justinretzolk** [comment]
Thanks for confirming that worked @daugustus 👍. Since that resolved it, we'll go ahead and close this issue.
