### ISSUE TITLE
New resource aws_ses_email_dkim

### ISSUE THREAD

**Issue by pikkemans** [hashicorp/terraform-provider-aws#21672]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
In addition of the `aws_ses_domain_dkim` resource also provide a `aws_ses_email_dkim` resource to enable DKIM for an email identity. As a result the `dkim_tokens` can be used to setup the route53 records.

### New or Affected Resource(s)
* aws_ses_email_dkim

### Potential Terraform Configuration

```
resource "aws_ses_email_identity" "example" {
  email = "email@example.com"
}

resource "aws_ses_email_dkim" "example" {
  email = aws_ses_email_identity.example.email
}

resource "aws_route53_record" "example_amazonses_dkim_record" {
  count   = 3
  zone_id = "ABCDEFGHIJ123"
  name    = "${element(aws_ses_email_dkim.example.dkim_tokens, count.index)}._domainkey"
  type    = "CNAME"
  ttl     = "600"
  records = ["${element(aws_ses_email_dkim.example.dkim_tokens, count.index)}.dkim.amazonses.com"]
}

**Comment by bruno-yamada** [comment]
Something worth noting,
- `easy DKIM` is a feature provided by aws, it is domain wide
- meaning the `e-mail DKIM`  for `foo@example.com` has the same value as `domain DKIM` for `example.com`
- `e-mail DKIM` is not available through the AWS console UI anymore, only `domain DKIM`

So it would make sense to not have this resource added, and instead have some note on the documentation regarding how it works

**Comment by pikkemans** [comment]
I agree with you @bruno-yamada. It's also not part of the AWS CLI v2.
