### ISSUE TITLE
cloudfront: cache and origin request policies via id in resource

### ISSUE THREAD

**Issue by Rishats** [hashicorp/terraform-provider-aws#21688]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_cloudfront_origin_request_policy
* aws_cloudfront_cache_policy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "aws_cloudfront_origin_request_policy" "this" {
  id = "88a5eaf4-2fd4-4709-b370-b4c650ea3fcf"
}

data "aws_cloudfront_cache_policy" "this" {
  id = "658327ea-f89d-4fab-a63d-7e88639e58f6"
}

resource "aws_cloudfront_distribution" "s3_distribution" {
  origin {
    domain_name = aws_s3_bucket.b.bucket_regional_domain_name
    origin_id   = local.s3_origin_id

    s3_origin_config {
      origin_access_identity = aws_cloudfront_origin_access_identity.origin_access_identity.cloudfront_access_identity_path
    }
  }

  enabled             = true
  is_ipv6_enabled     = true
  comment             = "cdn Static content"

  default_cache_behavior {
    allowed_methods  = ["GET", "HEAD", "OPTIONS"]
    cached_methods   = ["GET", "HEAD", "OPTIONS"]
    target_origin_id = local.s3_origin_id

    viewer_protocol_policy = "redirect-to-https"
    min_ttl                = 0
    default_ttl            = 3600
    max_ttl                = 86400

    cache_policy_id          = data.aws_cloudfront_cache_policy.this.id
    origin_request_policy_id = data.aws_cloudfront_origin_request_policy.this.id
  }

  # Cache behavior with precedence 0
  ordered_cache_behavior {
    path_pattern     = "/_nuxt/*"
    allowed_methods  = ["GET", "HEAD", "OPTIONS"]
    cached_methods   = ["GET", "HEAD", "OPTIONS"]
    target_origin_id = local.s3_origin_id

    min_ttl                = 0
    default_ttl            = 86400
    max_ttl                = 31536000
    compress               = true
    viewer_protocol_policy = "redirect-to-https"

    cache_policy_id          = data.aws_cloudfront_cache_policy.this.id
    origin_request_policy_id = data.aws_cloudfront_origin_request_policy.this.id
  }
```

### Expected Behavior
After terraform plan expect: Plan: 0 to add, 2 to change, 0 to destroy.

### Actual Behavior
After terraform plan expect: Plan: 0 to add, 0 to change, 0 to destroy.

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### References

* #14373

**Comment by justinretzolk** [comment]
Hey @Rishats 👋 Thank you for taking the time to file this issue. Am I correct in my understanding that you're looking to be able to pull in the data sources for `aws_cloudfront_origin_request_policy` or `aws_cloudfront_cache_policy` by only passing the `id` argument?

If that understanding is correct, I believe we may just need to update the documentation here, as each of these resources appears to have this functionality. For reference, I'll link the lines I'm looking at for each:

-  [`aws_cloudfront_origin_request_policy`](https://github.com/hashicorp/terraform-provider-aws/blob/e4288f2bc4d86240a7c72adfa0b2a6e3e7a4d4ed/internal/service/cloudfront/origin_request_policy_data_source.go#L121-L143)
- [`aws_cloudfront_cache_policy`](https://github.com/hashicorp/terraform-provider-aws/blob/e4288f2bc4d86240a7c72adfa0b2a6e3e7a4d4ed/internal/service/cloudfront/cache_policy_data_source.go#L150-L163)

**Comment by Rishats** [comment]
> Hey @Rishats wave Thank you for taking the time to file this issue. Am I correct in my understanding that you're looking to be able to pull in the data sources for `aws_cloudfront_origin_request_policy` or `aws_cloudfront_cache_policy` by only passing the `id` argument?
> 
> If that understanding is correct, I believe we may just need to update the documentation here, as each of these resources appears to have this functionality. For reference, I'll link the lines I'm looking at for each:
> 
> * [`aws_cloudfront_origin_request_policy`](https://github.com/hashicorp/terraform-provider-aws/blob/e4288f2bc4d86240a7c72adfa0b2a6e3e7a4d4ed/internal/service/cloudfront/origin_request_policy_data_source.go#L121-L143)
> * [`aws_cloudfront_cache_policy`](https://github.com/hashicorp/terraform-provider-aws/blob/e4288f2bc4d86240a7c72adfa0b2a6e3e7a4d4ed/internal/service/cloudfront/cache_policy_data_source.go#L150-L163)

Hello @justinretzolk. 

Yes, you understood correctly :)

I do not think that it is enough to add an ID to the documentation here, since a resource is not created by ID.

P.S

I solved this by creating a resource by specifying the name as a parameter.
```
data "aws_cloudfront_origin_request_policy" "this" {
  name = "Managed-CORS-S3Origin"
}

data "aws_cloudfront_cache_policy" "this" {
  name = "Managed-CachingOptimized"
}
```
