### ISSUE TITLE
Support for User Data in Image Builder Recipes

### ISSUE THREAD

**Issue by jeffadams** [hashicorp/terraform-provider-aws#21684]
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

ImageBuilder supports the use of user data in an image build recipe. This is a necessity for AMIs that don't have SSM preinstalled. The cli supports support this feature with the `userDataOverride` argument. 

### Potential Terraform Configuration

resource "aws_imagebuilder_image_recipe" "myrecipe" {
  user_data_override = <<EOF
#!/bin/bash
etc...
EOF
}

**Comment by justinretzolk** [comment]
Hey @jeffadams 👋 Thank you for taking the time to open this! We'll take a look at this whenever time allows (unless someone from the community beats us to it!). I took a quick glance around in the meantime, and wanted to leave a couple of helpful links for whoever looks at this next:

[`type CreateImageRecipeInput`](https://docs.aws.amazon.com/sdk-for-go/api/service/imagebuilder/#CreateImageRecipeInput) has a [AdditionalInstanceConfiguration](https://docs.aws.amazon.com/sdk-for-go/api/service/imagebuilder/#AdditionalInstanceConfiguration) field, which in turn has a `UserDataOverride` field of type `string`, so this seems like it should be possible.

**Comment by johan-ripoll** [comment]
Hello, is there any timeline available when the PR of @kamilturek will be accepted please?
