### ISSUE TITLE
bid_percentage docs don't match console UI instructions

### ISSUE THREAD

**Issue by carlowahlstedt** [hashicorp/terraform-provider-aws#21691]
The [docs for bid_percentage](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/batch_compute_environment#bid_percentage) say:
> bid_percentage - (Optional) Integer of minimum percentage that a Spot Instance price must be when compared with the On-Demand price for that instance type before instances are launched. For example, if your bid percentage is 20% (20), then the Spot price must be below 20% of the current On-Demand price for that EC2 instance. This parameter is required for SPOT compute environments. This parameter isn't applicable to jobs running on Fargate resources, and shouldn't be specified.

However the console UI says:
> The maximum percentage of On-Demand pricing you want to pay for Spot resources. You will always pay the lowest Spot market price and never more than your maximum percentage. AWS Batch will use 100% as the default maximum price if you leave this field empty.
![image](https://user-images.githubusercontent.com/2687687/140926971-316df439-d6df-4da8-b2e0-5c7bfee369d4.png)

These seem to be opposite of one another and since the console behavior is the source of truth, the tf docs here should be updated to be in line with the console.

**Comment by justinretzolk** [comment]
Hey @carlowahlstedt 👋 Thank you for taking the time to open this issue and for bringing this to our attention! Looking over the [Go SDK documentation](https://docs.aws.amazon.com/sdk-for-go/api/service/batch/#ComputeResource), it looks like you're completely right:

```
// The maximum percentage that a Spot Instance price can be when compared with
// the On-Demand price for that instance type before instances are launched.
// For example, if your maximum percentage is 20%, then the Spot price must
// be less than 20% of the current On-Demand price for that Amazon EC2 instance.
// You always pay the lowest (market) price and never more than your maximum
// percentage. If you leave this field empty, the default value is 100% of the
// On-Demand price.
//
// This parameter isn't applicable to jobs that are running on Fargate resources,
// and shouldn't be specified.
```

I'll work on a pull request to get this updated.
