### ISSUE TITLE
aws_eks_node_group missing suspended_processes support like AZRebalance

### ISSUE THREAD

**Issue by devopsmash** [hashicorp/terraform-provider-aws#21692]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

while the resource `aws_autoscaling_group` has `suspended_processes` like:
```
  suspended_processes = ["AZRebalance"]
```

The resource `aws_eks_node_group` doesn't support `suspended_processes`

It seems that the Managed Autoscale group has this option

![image](https://user-images.githubusercontent.com/22152786/140933174-0b5d0644-80cb-490e-9ff5-801d931ab25e.png)

Can you add this support for the  resource `aws_eks_node_group`?

### New or Affected Resource(s)

* aws_eks_node_group

**Comment by Natalique** [comment]
Any updates on this maybe? 
We've been experiencing some issues with Cluster autoscaler and AZRebalance

**Comment by naor919** [comment]
Same issue for me.

**Comment by eclivus** [comment]
I can't help you on coding it, but it I was able to do it with a null_resource command using
`aws autoscaling suspend-processes --auto-scaling-group-name ${each.value} --scaling-processes AZRebalance`
Auto scaling group names can be accessed through terraform-provider-aws module (I used a data source however for simplicity).

**Comment by mattburgess** [comment]
Unfortunately, there's no support for passing down the desired `suspended_processes` through to the underlying ASG in the EKS API. Given that the underlying ASG isn't managed by Terraform, I think that @eclivus' suggestion is the best option right now. If anyone interested in this feature has a support contract with AWS it might be worth you trying to engage with your TAM to see if the feature can be put on the EKS backlog. There's a related roadmap item https://github.com/aws/containers-roadmap/issues/1453 (with a similar `null_resource` workaround) which it might be worth folks tracking and/or providing input to.
