### ISSUE TITLE
aws_appstream_fleet stream_view does not work

### ISSUE THREAD

**Issue by cicsyd** [hashicorp/terraform-provider-aws#21718]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

1.0.5

### Affected Resource(s)

* aws_appstream_fleet

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_appstream_fleet" "workspace_fleet" {
  name = "workspace-fleet"

  compute_capacity {
    desired_instances = 1
  }

  description                        = "Workspace Fleet"
  idle_disconnect_timeout_in_seconds = 3600
  display_name                       = "workspace-fleet"
  enable_default_internet_access     = true
  fleet_type                         = "ON_DEMAND"
  image_name                         = "AppStream-WinServer2019-10-08-2021"
  instance_type                      = "stream.standard.large"
  stream_view                        = "DESKTOP"
  max_user_duration_in_seconds       = 14400

  vpc_config {
    subnet_ids = [aws_subnet.ir[0].id]
    security_group_ids = [aws_security_group.default.id]
  }

  tags = {
    Name = "${var.region_prefix}-appstream-fleet"
    Customer = "Workspace Fleet"
  }
}
```

### Debug Output

None

### Panic Output

None

### Expected Behavior

Create AWS AppStream Fleet with stream_view set to Desktop

### Actual Behavior

Creates AWS AppStream Fleet with stream_view set to App regardless of setting

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by mbotmcc** [comment]
think all that's missing is

```
if v, ok := d.GetOk("stream_view"); ok {
	input.StreamView = aws.String(v.(string))
}
```

from: https://github.com/coderGo93/terraform-provider-aws/blob/2e321d827963199e0baf554ded94a106900f97a0/aws/resource_aws_appstream_fleet.go#L186

could someone more knowledgable check/raise a MR?
