### ISSUE TITLE
Documentation (or tool?) issue for *aws_route_table* - route parameter does not specify required parameters correctly

### ISSUE THREAD

**Issue by geologic-aws** [hashicorp/terraform-provider-aws#21714]
Document link: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route_table

Only the `cidr_block` parameter in the `aws_route_table`'s route parameter is specified as required. When running `terraform validate` against the sample, we get the following error:

```Inappropriate value for attribute "route": element 0: attributes "carrier_gateway_id", "destination_prefix_list_id", "egress_only_gateway_id", "instance_id", "ipv6_cidr_block", "local_gateway_id", "nat_gateway_id", "network_interface_id", "transit_gateway_id", "vpc_endpoint_id", and "vpc_peering_connection_id" are required.```

The solution is to fill out all of these as empty strings, as referenced here: https://stackoverflow.com/questions/69689262/inappropriate-value-for-attribute-route-element-0-attributes/69689794#69689794

Is this a documentation issue or a tool issue? I hope that the tool gets updated to match what the docs prescribe. Otherwise configs can get bloated.

My terraform version:
```Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.64.2
```

**Comment by justinretzolk** [comment]
Hey @geologic-aws 👋 Thank you for taking the time to file this issue. This is something I've seen a couple of issues filed on and am discussing internally on the best way to approach (currently, my thought is that the documentation should be updated). I discussed this a bit more in a comment on another issue ([here](https://github.com/hashicorp/terraform-provider-aws/issues/21659#issuecomment-963626004)). While that issue was around `aws_route`, it's a different instance of the same issue. Can you verify that switching the configuration as I'd described in that comment sorts out your issues as well?

**Comment by geologic-aws** [comment]
Hi @justinretzolk I'm very grateful for the fast response. I can verify that the redacted code below is accepted and deployable.

I agree with you: the documentation should definitely be updated since we can't modify a released version. In a future version, I hope that we can have the tool default to empty strings when and where appropriate. Adding 11 lines of empty strings to a config for every route in a route table isn't ideal to put it lightly.

I also read the ticket you mentioned and it seems exactly the same as mine (sorry - I couldn't find it via search). If you want to resolve this ticket as a duplicate please go ahead and do so.

Thanks for looking into this.

```
resource "aws_route_table" "*************" {
  vpc_id = aws_vpc.********.id

  route = [
    {
      cidr_block                 = "************"
      gateway_id                 = ""
      carrier_gateway_id         = ""
      destination_prefix_list_id = ""
      egress_only_gateway_id     = ""
      instance_id                = ""
      ipv6_cidr_block            = ""
      local_gateway_id           = ""
      nat_gateway_id             = aws_nat_gateway.****.id
      network_interface_id       = ""
      transit_gateway_id         = ""
      vpc_endpoint_id            = ""
      vpc_peering_connection_id  = ""
    },
    {
      cidr_block                 = "***************"
      gateway_id                 = ""
      carrier_gateway_id         = ""
      destination_prefix_list_id = ""
      egress_only_gateway_id     = ""
      instance_id                = ""
      ipv6_cidr_block            = ""
      local_gateway_id           = ""
      nat_gateway_id             = ""
      network_interface_id       = ""
      transit_gateway_id         = "***********************"
      vpc_endpoint_id            = ""
      vpc_peering_connection_id  = ""
    }
  ]

  tags = {
    Name = "****************"
  }
}
