### ISSUE TITLE
aws_efs_file_system_policy Resource Eventual Consistency Bug

### ISSUE THREAD

**Issue by joelthompson** [hashicorp/terraform-provider-aws#21716]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Latest

### Affected Resource(s)

* aws_efs_file_system_policy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "aws_iam_policy_document" "fs-writer-assume" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]
    principals {
      type = "Service"
      identifiers = [
        "ec2.amazonaws.com"
      ]
    }
  }
}

resource "aws_iam_role" "fs-writer" {
  assume_role_policy = data.aws_iam_policy_document.fs-writer-assume.json
  name               = "fs-writer"
}

resource "aws_efs_file_system" "efs" {
  encrypted = true
}

resource "aws_efs_mount_target" "efs-mt" {
  file_system_id  = aws_efs_file_system.efs.id
  subnet_id       = "subnet-xxxxxx"
  security_groups = ["sg-xxxxxx"]
}

data "aws_iam_policy_document" "efs-policy" {
  statement {
    effect = "Allow"
    principals {
      type = "AWS"
      identifiers = [
        aws_iam_role.fs-writer.arn,
      ]
    }
    actions = [
      "elasticfilesystem:ClientMount",
      "elasticfilesystem:ClientRootAccess",
      "elasticfilesystem:ClientWrite",
      "elasticfilesystem:CreateAccessPoint",
      "elasticfilesystem:DeleteAccessPoint",
    ]
    resources = [
      aws_efs_file_system.efs.arn,
    ]
  }
}

resource "aws_efs_file_system_policy" "efs-policy" {
  file_system_id = aws_efs_file_system.efs.id
  policy         = data.aws_iam_policy_document.efs-policy.json
}
```

### Expected Behavior

This should create an IAM role, `fs-writer`, and an EFS FS with a policy that grants `fs-writer` access to it.

### Actual Behavior

This will frequently fail out on the first run with:

```Error: error putting EFS File System Policy (fs-XXXXXX): InvalidPolicyException: Policy contains invalid Principal block.
 {
   RespMetadata: {
     StatusCode: 400,
     RequestID: "3c57405f-87e8-4b15-8a15-95fcd0b0af46"
   },
   ErrorCode: "InvalidPolicyException",
   Message_: "Policy contains invalid Principal block."
 }

   with aws_efs_file_system_policy.efs-policy,
   on foo.tf line xxx, in resource "aws_efs_file_system_policy" "efs-policy":
  xxx: resource "aws_efs_file_system_policy" "efs-policy" {
```

### Steps to Reproduce

1. `terraform apply` on a clean slate, especially in a busy account. A reapply usually succeeds.

### Important Factoids

Most likely, this is eventual consistency between the IAM role being created and then being available to be used in an FS policy. The underlying resource doesn't have any retries around it to guard against eventual consistency bugs:

https://github.com/hashicorp/terraform-provider-aws/blob/ca2cb2838b07e373baa7ca5bbc5d0778509b493d/internal/service/efs/file_system_policy.go#L48-L68

**Comment by quentin9696** [comment]
Hi, 

Any update for this one ? I hit the same issue here.

As a dirty workaround, I use the time_sleep resource form time provider to delay my EFS policy creation

**Comment by yzislin** [comment]
I am in the same boat. Any resolution for this yet?
It seems like a common task that people would do.

Thanks.

**Comment by jdebbink** [comment]
Looks like someone fixed this over a year ago but still sitting in PR with no one looking at it
https://github.com/hashicorp/terraform-provider-aws/pull/21734

**Comment by harshitp1987** [comment]
Any update for this issue?, Any resolution for this yet?

**Comment by lohrm-stabl** [comment]
This issue still exists. I assume no updates here?

**Comment by yzislin** [comment]
i assume so. I have been using time_sleep resource with success.

**Comment by quentin9696** [comment]
We can say happy birthday to that issue :birthday: 

Do you know if there's a plan to fix that ?

**Comment by nikhilgupta345** [comment]
Bump

**Comment by ig-leonov** [comment]
can someone finally merge the PR?
