### ISSUE TITLE
aws_appstream_stack missing parameter to associate with aws_appstream_fleet

### ISSUE THREAD

**Issue by cicsyd** [hashicorp/terraform-provider-aws#21719]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We can currently create an appstream fleet and appstream stack using terraform code, but there doesn't seem to be an option to associate said stack with said fleet

### New or Affected Resource(s)

* aws_appstream_stack
* aws_appstream_fleet

### Potential Terraform Configuration

```hcl
resource "aws_appstream_fleet" "workspace_fleet" {
  name = "workspace-fleet"

  compute_capacity {
    desired_instances = 1
  }

  description                        = "Workspace Fleet"
  idle_disconnect_timeout_in_seconds = 3600
  display_name                       = "workspace-fleet"
  enable_default_internet_access     = true
  fleet_type                         = "ON_DEMAND"
  image_name                         = "AppStream-WinServer2019-10-08-2021"
  instance_type                      = "stream.standard.large"
  stream_view                        = "DESKTOP"
  max_user_duration_in_seconds       = 14400

  vpc_config {
    subnet_ids = [aws_subnet.ir[0].id]
    security_group_ids = [aws_security_group.default.id]
  }

  tags = {
    Name = "${var.region_prefix}-appstream-fleet"
    Customer = "Workspace Fleet"
  }
}

resource "aws_appstream_stack" "workspace_stack" {
  name         = "workspace-stack"
  description  = "Windows Workstations"
  display_name = "Windows Workstations"
  fleet_association = aws_appstream_fleet.workspace_fleet.id


  storage_connectors {
    connector_type = "HOMEFOLDERS"
  }

application_settings {
    enabled        = true
    settings_group = "SettingsGroup"
  }

  tags = {
    Name = "${var.region_prefix}-appstream-stack"
    Customer = "Workspace Stack"
  }
}
```

### References
* #0000

**Comment by mbotmcc** [comment]
this should be sorted with https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3670-november-25-2021
