### ISSUE TITLE
Changing KMS key on Dynamodb replicas fails

### ISSUE THREAD

**Issue by grahamhar** [hashicorp/terraform-provider-aws#21726]
When changing the KMS key for a replica from the default key to a CMK the following error is reported:

> Error: error updating DynamoDB Table (test-table) SSE: ValidationException: Invalid operation: Customer Managed CMKs on Global Table Version 2019.11.21 replicas cannot be updated through SSESpecification parameter and can only be updated through ReplicaUpdates parameter

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
terraform 1.0.0
aws provider version 3.45.0

### Affected Resource(s)

* aws_dynamodb_table

### Terraform Configuration Files

Given the original table creation

```hcl
resource "aws_dynamodb_table" "test" {
  name = "test-table"
  attribute {
    name = "test"
    type = "S"
  }
  attribute {
    name = "test2"
    type = "S"
  }
  hash_key         = "test"
  range_key        = "test2"
  billing_mode     = "PAY_PER_REQUEST"
  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"
  server_side_encryption {
    enabled = true
  }
  replica {
    region_name = "eu-west-1"
  }

  replica {
    region_name = "eu-central-1"
  }
  lifecycle {
    prevent_destroy = true
  }
}
```

Update to the following produces the error

```hcl
resource "aws_dynamodb_table" "test" {
  name = "test-table"
  attribute {
    name = "test"
    type = "S"
  }
  attribute {
    name = "test2"
    type = "S"
  }
  hash_key         = "test"
  range_key        = "test2"
  billing_mode     = "PAY_PER_REQUEST"
  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"
  server_side_encryption {
    enabled = true
    kms_key_arn = aws_kms_key.dynamodb_us_east_1.arn
  }
  replica {
    region_name = "eu-west-1"
    kms_key_arn = aws_kms_key.dynamodb_eu_west_1.arn
  }

  replica {
    region_name = "eu-central-1"
    kms_key_arn = aws_kms_key.dynamodb_eu_central_1.arn
  }
  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_kms_key" "dynamodb_us_east_1" {
  enable_key_rotation = true
  is_enabled          = true
  policy                  = <redacted>
}

resource "aws_kms_key" "dynamodb_eu_west_1" {
  enable_key_rotation = true
  is_enabled          = true
  policy                  = <redacted>
  provider              = aws.euwest1         
}

resource "aws_kms_key" "dynamodb_eu_central_1" {
  enable_key_rotation = true
  is_enabled          = true
  policy                  = <redacted>
  provider              = aws.eucentral1         
}
```

### Expected Behavior

The KMS key should have been updated from the default to the CMK

### Actual Behavior

The apply failed with the following error

### Steps to Reproduce

1. `terraform apply` # with first code block
2. `terraform apply` # after updating code to be like that in second block

**Comment by atom888888** [comment]
I am trying to do something similar with passing in the kms_key_arn field to the replica at creation time.  The intent is for the TF module to create a dynamoDB table in 2 regions (a global table with US-EAST-1 for primary and US-WEST-2 as a replica).  I have 2 corresponding KMS keys one for east-1 (primary) and a KMS key replica (on US-WEST-2).

TF seems to create the primary table and fail when trying to create the replica (thus converting it to a global table).

I get this error:

`Error: error initially creating DynamoDB Table (simple-table-multiregion) replicas: error creating DynamoDB Table (simple-table-multiregion) replica (us-west-2): ValidationException: One or more parameter values were invalid: KMSMasterKeyId must be specified for each replica.
        status code: 400, request id: 0V4PTODFB8BR3B1H3TLUAANNMRVV4KQNSO5AEMVJF66Q9ASUAAJG`

**Comment by atom888888** [comment]
FYI: In your first half of the example, you are creating a replica in eu-west-1 and eu-central-1.

For anyone trying to run this example you cannot have your primary region in your AWS profile settings set to either of those or you will receive an error.  A working example would end up having a "global table" defined as a primary in some region and replicas in the 2 others (for a total of 3).

Otherwise you will run into this error:
https://github.com/aws/aws-cdk/issues/6287
DynamoDB global table creation fails

**Comment by aa8y** [comment]
Also faced the same issue while using cdktf. The primary region was set to us-west-2 and the replica region to us-east-1. The only workaround I've found is to destroy the currently associated key with the primary table (which also destroys the table) and recreate the table, its replica and the key and its replica.
