### ISSUE TITLE
Outdated documentation for enabled_metrics in aws_autoscaling_group resource

### ISSUE THREAD

**Issue by lekspyl** [hashicorp/terraform-provider-aws#21729]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It seems that AWS has expanded list of Cloudwatch metrics that can be enabled using `enabled_metrics` var in the `aws_autoscaling_group` resource. The supported metrics from docs are missing these ones:
* GroupAndWarmPoolDesiredCapacity
* GroupAndWarmPoolTotalCapacity
* WarmPoolDesiredCapacity
* WarmPoolMinSize
* WarmPoolPendingCapacity
* WarmPoolTerminatingCapacity
* WarmPoolTotalCapacity
* WarmPoolWarmedCapacity

The documentation must include these metrics to the list of supported ones

**Comment by justinretzolk** [comment]
Hey @lekspyl 👋 Thank you for taking the time to open this issue! I've opened a PR to update the documentation to link out to the underlying API documentation so that the list is always up to date.
