### ISSUE TITLE
Lambda layer version max compatible runtimes

### ISSUE THREAD

**Issue by chammock** [hashicorp/terraform-provider-aws#21742]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_lambda_layer_version

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_lambda_layer_version" "layer" {
  filename   = "layer.zip"
  layer_name = "layer"
  compatible_runtimes = [
    "go1.x",
    "nodejs10.x",
    "nodejs12.x",
    "nodejs8.10",
    "python3.9",
    "python3.8",
    "python3.7",
    "python3.6"
  ]
}
```

### Debug Output

https://gist.github.com/chammock/8d87265a368eb60768ca159450cd61c7

### Expected Behavior

Up to 15 runtimes should be supported.

### Actual Behavior

Errors with too many after 5

### Steps to Reproduce

1. `terraform validate`

### Important Factoids

no

### References

* https://docs.aws.amazon.com/lambda/latest/dg/API_PublishLayerVersion.html#SSS-PublishLayerVersion-request-CompatibleRuntimes
* https://github.com/hashicorp/terraform-provider-aws/blob/53686ab8c251ec363580bbdbee3eefc6e2d5283e/internal/service/lambda/layer_version.go#L77

**Comment by Victorp99** [comment]
Hello! I would like to take on this issue!

**Comment by midnight5ohhev** [comment]
Op

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
