### ISSUE TITLE
ConcurrentModificationException when creating multiple glue triggers against a workflow at once

### ISSUE THREAD

**Issue by moreandres** [hashicorp/terraform-provider-aws#21759]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

$ terraform -v
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.65.0

### Affected Resource(s)

- aws_glue_workflow
- aws_glue_trigger
- aws_glue_job

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_glue_workflow" "workflow" {
  name = "test"
}

resource "aws_glue_trigger" "start" {
  name          = "start"
  workflow_name = aws_glue_workflow.workflow.name
  type          = "ON_DEMAND"

  actions {
    job_name = "start"
  }
}

locals {
  names = ["1", "2", "3", "4", "5"]
}

resource "aws_glue_trigger" "trigger" {

  for_each      = toset(local.names)
  name          = each.key
  workflow_name = aws_glue_workflow.workflow.name
  type          = "CONDITIONAL"

  actions {
    job_name = each.key
  }

  predicate {
    conditions {
      job_name = "start"
      state    = "SUCCEEDED"
    }
  }
}
```

### Debug Output

[debugging output](https://gist.github.com/moreandres/d3020bb9810e4b56ed4af8f6334541ed)

### Expected Behavior

Multiple triggers should have been created concurrently and associated with the workflow resource.

### Actual Behavior

Error: error creating Glue Trigger (1): ConcurrentModificationException: Workflow test was modified while adding trigger 1 to it

### Steps to Reproduce

1. `terraform apply -auto-approve`

### Important Factoids

Can be reproduced with jobs besides triggers.

### References

[exception documentation](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-exceptions.html)

**Comment by moreandres** [comment]
Hi! I'm interested in solving this issue, any pointers on where to start? Thanks!

**Comment by caioz7** [comment]
Same problem here

**Comment by stefan-novak-brt** [comment]
Came across this issue as well. Are there any workarounds?

**Comment by rbatorowski-at-pgs** [comment]
As workaround, add depends_on to your triggers, so they'll be created one by one.

**Comment by stagha** [comment]
Using `depends_on` doesn't work if you're creating triggers inside of a `for_each`. `depends_on` requires a static list of resources.
