### ISSUE TITLE
WAFv2: Add support of Captcha into aws_wafv2_web_acl rule action statement

### ISSUE THREAD

**Issue by wedneyyuri** [hashicorp/terraform-provider-aws#21754]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_wafv2_web_acl

### Potential Terraform Configuration

```hcl
resource "aws_wafv2_web_acl" "example" {
  name        = "managed-rule-example"
  description = "Example of a captcha rule"
  scope       = "CLOUDFRONT"

  default_action {
    allow {}
  }

  rule {
    name     = "rule-1"
    priority = 1

    action {
      captcha {}
    }

    statement {
      rate_based_statement {
        limit              = 10000
        aggregate_key_type = "IP"

        scope_down_statement {
          geo_match_statement {
            country_codes = ["US", "NL"]
          }
        }
      }
    }

    visibility_config {
      cloudwatch_metrics_enabled = false
      metric_name                = "friendly-rule-metric-name"
      sampled_requests_enabled   = false
    }
  }

  tags = {
    Tag1 = "Value1"
    Tag2 = "Value2"
  }

  visibility_config {
    cloudwatch_metrics_enabled = false
    metric_name                = "friendly-metric-name"
    sampled_requests_enabled   = false
  }
}
```

### References

* [AWS CLI - create-web-acl
](https://docs.aws.amazon.com/en_us/cli/latest/reference/wafv2/create-web-acl.html#:~:text=Captcha%20-%3E%20(structure))
* [AWS CLI - get-web-acl
](https://docs.aws.amazon.com/en_us/cli/latest/reference/wafv2/get-web-acl.html#:~:text=Captcha%20-%3E%20(structure))
* [sdk-for-go](https://docs.aws.amazon.com/sdk-for-go/api/service/wafv2/#CaptchaAction)
* [aws-sdk-php](https://github.com/aws/aws-sdk-php/releases/tag/3.200.2)
* https://aws.amazon.com/about-aws/whats-new/2021/11/aws-waf-captcha-support/

**Comment by wedneyyuri** [comment]
I'm working on it 👆

**Comment by wedneyyuri** [comment]
Pull request opened, the captcha action looks like the following

![Peek 2021-11-15 10-54](https://user-images.githubusercontent.com/7511692/141794044-1b56d67a-d086-4bdf-865a-fefd34f2c9ce.gif)

**Comment by nodomain** [comment]
Hey, what is the status here? I have great interest in this feature :)

**Comment by nodomain** [comment]
I also don't understand why it takes so long if there is already a PR. Can someone from Hashicorp please shed some light on this?

**Comment by wsj31013** [comment]
+1

**Comment by harrymilne** [comment]
Has anyone looked into defining the custom immunity period for the CAPTCHA action?
