### ISSUE TITLE
aws_cloudfront_cache_policy default_ttl value 0 no longer working after provider version 3.38 -> 3.65

### ISSUE THREAD

**Issue by theherk** [hashicorp/terraform-provider-aws#21788]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```sh
Terraform v1.0.10
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.65.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

* aws_cloudfront_cache_policy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_version = ">= 1.0.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.38" # generating p3.38-no-error
      # version = "3.65" # generating p3.65-with-error
    }
  }
}

provider "aws" {
  region              = "eu-west-1"
  allowed_account_ids = ["redacted"]
}

resource "aws_cloudfront_cache_policy" "this" {
  name        = "debug_policy"
  default_ttl = 0
  max_ttl     = 1
  min_ttl     = 0

  parameters_in_cache_key_and_forwarded_to_origin {
    cookies_config {
      cookie_behavior = "none"
    }
    headers_config {
      header_behavior = "whitelist"
      headers {
        items = ["authorization"]
      }
    }
    query_strings_config {
      query_string_behavior = "none"
    }
  }
}
```

### Debug Output

[terraform debug output for aws_cloudfront_cache_policy issue - gist - 3.38 without error][1]
[terraform debug output for aws_cloudfront_cache_policy issue - gist - 3.65 with error][2]

### Expected Behavior

The `default_ttl` value should be set to 0.

### Actual Behavior

The `default_ttl` value was assumed not given.

### Steps to Reproduce

1. uncomment `version = "3.65"`
2. `terraform init -upgrade`
3. `terraform apply`
4. receive error `InvalidArgument: The parameter DefaultTTL is required.`
5. comment 'version = "3.65"`
6. uncomment `version = "3.38"`
7. `terraform init -upgrade`
8. `terraform apply`
9. see value change to 0 as expected

### References

[1]: https://gist.github.com/theherk/710dc99a45286d503840995da8b25797#file-p3-38-no-error
[2]: https://gist.github.com/theherk/710dc99a45286d503840995da8b25797#file-p3-65-with-error

**Comment by ewbankkit** [comment]
**v3.64.2**: https://github.com/hashicorp/terraform-provider-aws/blob/4bc14149ae38d2cc6d7317383b9665c962ec8f3f/internal/service/cloudfront/cache_policy_structure.go#L141-L148

**v3.65.0**: https://github.com/hashicorp/terraform-provider-aws/blob/f17f423afbb377c7170073719b4ee221d7c6cd86/internal/service/cloudfront/cache_policy.go#L163-L182

[CloudFront API reference](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CachePolicyConfig.html).
