### ISSUE TITLE
New resource: aws_backup_framework

### ISSUE THREAD

**Issue by Kostadin-Lazarov** [hashicorp/terraform-provider-aws#21784]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Backup Framework
A framework is a collection of controls that you can use to evaluate your backup practices. By using pre-built customizable controls to define your policies, you can evaluate whether your backup practices comply with your policies and which resources are not yet in compliance.

### New or Affected Resource(s)

* aws_backup_framework

### Potential Terraform Configuration

```hcl
resource "aws_backup_framework" {
    name = "tf_example_backup_framework"
    description = "tf_example_backup_framework_description"
    controls = [
        {
            name = "tf_example_backup_framework_control_name"
            parameters = [ 
                {
                  name = "foo"
                  value = "bar"
                }
            ]
            scope = {
              ...
            }
        }
    ]
    tags = {
      foo = "bar"
   }
}
```

### References

https://docs.aws.amazon.com/sdk-for-go/api/service/backup/  
https://docs.aws.amazon.com/aws-backup/latest/devguide/API_Framework.html

**Comment by sakar97** [comment]
Hi @Kostadin-Lazarov , @justinretzolk 
I would like to work on this new enhancement for Terraform.
Thanks

**Comment by GlennChia** [comment]
Hi @sakar97, are you still working on this? I would love to give this a go if you're not. Thanks!

**Comment by sakar97** [comment]
@GlennChia Hey, Yeah definitely you can start working on this one.
