### ISSUE TITLE
Redshift relocation feature

### ISSUE THREAD

**Issue by devops-asService** [hashicorp/terraform-provider-aws#21810]
Hi,
I was trying to implement the redshift relocation,  But, unfortunately, it appears to ve terraform aws provider doesn't support the relocation feature as I don't find it in the resource documentation. Thanks

**Comment by ewbankkit** [comment]
@devops-asService Thanks for raising this issue.
It has already been noticed in #19098. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
