### ISSUE TITLE
Cannot create cloudfront through terraform by configuring response header policy without using forwardedvalues parameter.

### ISSUE THREAD

**Issue by Bharath-Patel** [hashicorp/terraform-provider-aws#21828]
Hello,

To configure cache policy for cloudfront,had removed forwarded values. Now when tried to configure response header policy , an error "Parameter forwardedvalues is required" is encountered.

what's the solution ?

**Comment by ewbankkit** [comment]
@Bharath-Patel Thanks for raising this issue.
Could you please paste in Terraform configurations for the CloudFront cache policy and response header policy.
