### ISSUE TITLE
resource/aws_route: aws_route does not respect a high create timeout and gives up always after 21 retries

### ISSUE THREAD

**Issue by ialidzhikov** [hashicorp/terraform-provider-aws#21830]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform version - 0.12.31
provider-aws version - 3.63.0

### Affected Resource(s)

* aws_route

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  access_key = var.ACCESS_KEY_ID
  secret_key = var.SECRET_ACCESS_KEY
  region     = "eu-west-1"
}

resource "aws_vpc" "vpc" {
  cidr_block           = "10.222.0.0/16"
  enable_dns_support   = true
  enable_dns_hostnames = true
}

resource "aws_subnet" "public_utility_z0" {
  vpc_id            = aws_vpc.vpc.id
  cidr_block        = "10.222.96.0/26"
  availability_zone = "eu-west-1a"
}

resource "aws_eip" "eip_natgw_z0" {
  vpc = true
}

resource "aws_nat_gateway" "natgw_z0" {
  allocation_id = aws_eip.eip_natgw_z0.id
  subnet_id     = aws_subnet.public_utility_z0.id
}

resource "aws_route_table" "routetable_private_utility_z0" {
  vpc_id = aws_vpc.vpc.id
}

resource "aws_route" "private_utility_z0_nat" {
  route_table_id         = aws_route_table.routetable_private_utility_z0.id
  destination_cidr_block = "0.0.0.0/0"
  nat_gateway_id         = aws_nat_gateway.natgw_z0.id

  timeouts {
    create = "5m"
  }
}
```

### Expected Behavior

aws_route to respect the configured timeout:
```hcl
  timeouts {
    create = "5m"
  }
```

### Actual Behavior

Route creation always times out after 21 retries (`2m30s`) and does not respect the configured create timeout:

`terraform apply` of the configuration from above potentially fails with:

```
aws_route.private_utility_z0_nat: Creating...
aws_route.private_utility_z0_nat: Still creating... [10s elapsed]
aws_route.private_utility_z0_nat: Still creating... [20s elapsed]
aws_route.private_utility_z0_nat: Still creating... [30s elapsed]
aws_route.private_utility_z0_nat: Still creating... [40s elapsed]
aws_route.private_utility_z0_nat: Still creating... [50s elapsed]
aws_route.private_utility_z0_nat: Still creating... [1m0s elapsed]
aws_route.private_utility_z0_nat: Still creating... [1m10s elapsed]
aws_route.private_utility_z0_nat: Still creating... [1m20s elapsed]
aws_route.private_utility_z0_nat: Still creating... [1m30s elapsed]
aws_route.private_utility_z0_nat: Still creating... [1m40s elapsed]
aws_route.private_utility_z0_nat: Still creating... [1m50s elapsed]
aws_route.private_utility_z0_nat: Still creating... [2m0s elapsed]
aws_route.private_utility_z0_nat: Still creating... [2m10s elapsed]
aws_route.private_utility_z0_nat: Still creating... [2m20s elapsed]
aws_route.private_utility_z0_nat: Still creating... [2m30s elapsed]

Error: error waiting for Route in Route Table (rtb-1234) with destination (0.0.0.0/0) to become available: couldn't find resource (21 retries)

  on tf/main.tf line 245, in resource "aws_route" "private_utility_z0_nat":
 245: resource "aws_route" "private_utility_z0_nat" {

```

### Steps to Reproduce

See above.

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/21525

**Comment by ialidzhikov** [comment]
I would say this issue is much more concrete one and much more precise one than #21525. #21525 lacks any details/logs/steps to reproduce. Closing issues in such way actually does not bring much value. I would appreciate if you can reopen this issue. Thanks in advance!

**Comment by justinretzolk** [comment]
Hey @ialidzhikov, I see where you're coming from in terms of this issue having more of a concrete example and steps to reproduce (and thank you _very_ much for that). The reason behind us closing this one as the duplicate comes down to the fact that the linked issue already has quite a bit of conversation going, and quite a few "👍" reactions to it, which we use to help gauge community interest in a particular issue/PR. 

We also like to keep conversations within a single issue where possible so that there is a single "point of truth" where our engineers can reference when looking into the issue (for what it's worth, the linked issue is already on our radar, which was another reason why I opted to keep that one open). I'm also happy to copy over your information into a comment on the linked issue so that the information is more readily retained without you needing to do so.
