### ISSUE TITLE
Multiple aws_ec2_managed_prefix_list_entry resources fail to create

### ISSUE THREAD

**Issue by davidcomerford** [hashicorp/terraform-provider-aws#21835]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.11 on linux_amd64
provider registry.terraform.io/hashicorp/aws v3.65.0

### Affected Resource(s)

aws_ec2_managed_prefix_list_entry

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
variable "cidr_list" {
  type        = map(any)
  description = "Trusted CIDRs"
  default = { 
  "10.0.0.0/24" = "description 0"
  "10.0.1.0/24" = "description 1"
  "10.0.2.0/24" = "description 2"
  }
}

resource "aws_ec2_managed_prefix_list" "prefixlist" {
  name           = "example prefix list"
  address_family = "IPv4"
  max_entries    = 10
}

resource "aws_ec2_managed_prefix_list_entry" "entry" {
  for_each = var.cidr_list
  cidr           = each.key
  description    = each.value
  prefix_list_id = aws_ec2_managed_prefix_list.prefixlist.id
}
```
### Expected Behavior

Multiple aws_ec2_managed_prefix_list_entry resources should be created.

### Actual Behavior
aws_ec2_managed_prefix_list_entry resources are being created in parallel without checking if the referenced aws_ec2_managed_prefix_list resource is in the correct state.

```
aws_ec2_managed_prefix_list.prefixlist: Creating...
aws_ec2_managed_prefix_list.prefixlist: Creation complete after 2s [id=pl-090f8dc897e491b94]
aws_ec2_managed_prefix_list_entry.entry["10.0.0.0/24"]: Creating...
aws_ec2_managed_prefix_list_entry.entry["10.0.2.0/24"]: Creating...
aws_ec2_managed_prefix_list_entry.entry["10.0.1.0/24"]: Creating...
aws_ec2_managed_prefix_list_entry.entry["10.0.0.0/24"]: Creation complete after 3s [id=pl-090f8dc897e491b94,10.0.0.0/24]
╷
│ Error: error creating EC2 Managed Prefix List Entry (pl-090f8dc897e491b94,10.0.1.0/24): IncorrectState: The request cannot be completed while the prefix list (pl-090f8dc897e491b94) is in the current state (modify-in-progress). Target state is: (modify-in-progress)
│       status code: 400, request id: 28ee67f3-65fc-4642-9c33-5b7033ee622b
│ 
│   with aws_ec2_managed_prefix_list_entry.entry["10.0.1.0/24"],
│   on main.tf line 7, in resource "aws_ec2_managed_prefix_list_entry" "entry":
│    7: resource "aws_ec2_managed_prefix_list_entry" "entry" {
│ 
╵
╷
│ Error: error creating EC2 Managed Prefix List Entry (pl-090f8dc897e491b94,10.0.2.0/24): IncorrectState: The request cannot be completed while the prefix list (pl-090f8dc897e491b94) is in the current state (modify-in-progress). Target state is: (modify-in-progress)
│       status code: 400, request id: 7f8c28c5-e55c-44d7-ac43-7d16539e7826
│ 
│   with aws_ec2_managed_prefix_list_entry.entry["10.0.2.0/24"],
│   on main.tf line 7, in resource "aws_ec2_managed_prefix_list_entry" "entry":
│    7: resource "aws_ec2_managed_prefix_list_entry" "entry" {
```
### Steps to Reproduce

See above.

### References

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/describe-managed-prefix-lists.html
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/modify-managed-prefix-list.html

**Comment by mariuspaliga** [comment]
As a workaround, you can use `-parallelism=1` for the terraform apply command.

**Comment by davidcomerford** [comment]
> As a workaround, you can use `-parallelism=1` for the terraform apply command.

Good to know. Thanks!

**Comment by 2357gi** [comment]
Hello. I faced the same problem.
With `-parallelism=1`, it takes a very long time to generate a prefix list with other resources.
I think it would be better to control the number of api concurrency in the prefix list to one on the aws-provider side.  😊

**Comment by ajaguilar-kyndryl** [comment]
Hi. Same issue over here. Something different from parallelism workaround?

**Comment by iprice-salesforce** [comment]
Experiencing the same

tf version 1.1.4
aws provider 3.74.0

I will randomly encounter this on an apply that creates the resources. a subsequent re-apply will succeed without issue.

**Comment by maiconbaum** [comment]
Same here. =(

**Comment by karivera2** [comment]
Same issue here :(

**Comment by Katellification** [comment]
Also experiencing this consistently when creating `aws_ec2_managed_prefix_list` resources, the parallelism workaround is an okay temporary fix, but would rather not have to have that in the automation.
