### ISSUE TITLE
Amplify: Error downloading #current-cloud-backend.zip from deployment bucket:

### ISSUE THREAD

**Issue by david-wb** [hashicorp/terraform-provider-aws#21839]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Teraform: 1.0.1
AWS Provider: v3.65.0

### Affected Resource(s)

* aws_amplify_backend_environment

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_amplify_app" "core_web_app" {
  name = "core-web-app-${var.env}"
}

resource "aws_amplify_branch" "main" {
  app_id      = aws_amplify_app.core_web_app.id
  branch_name = "main"
}

resource "aws_amplify_domain_association" "core_web_app" {
  app_id      = aws_amplify_app.core_web_app.id
  domain_name = "app.${var.env}.example.com"

  sub_domain {
    branch_name = aws_amplify_branch.main.branch_name
    prefix      = ""
  }
}

resource "aws_amplify_backend_environment" "core_web_app" {
  app_id           = aws_amplify_app.core_web_app.id
  environment_name = var.env

  deployment_artifacts = aws_s3_bucket.core_web_app.id
  stack_name           = "core-web-app-stack"
}

resource "aws_s3_bucket" "core_web_app" {
  bucket = "core-web-app-deployment"
}
```

### Problem Description

After creating an Amplify app with the Terraform code above, I then tried to pull the app using the amplify cli and I get the following error.

```bash
$ amplify pull
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use amplify-dev
? Which app are you working on? d8jlijw8d5yq7
Backend environment 'dev' found. Initializing...
Error downloading #current-cloud-backend.zip from deployment bucket: core-web-app-deployment, the error is: The specified key does not exist.
```

Perhaps I am missing something, but this seems like unintended behavior. Why can I not pull the terraform created amplify app?

**Comment by cemo** [comment]
@david-wb Did you find a workaroud?

**Comment by david-wb** [comment]
@cemo Haha yeah, we're moving away from amplify in favor of custom auth ui and hosting web apps in s3 buckets.

**Comment by magnusbernet** [comment]
I have the same error and a similar configuration. I have tried a few configurations but so far without success. 

@david-wb could you find a solution in the meantime?

**Comment by magnusbernet** [comment]
I have the same error and a similar configuration. I have tried a few configurations but so far without success.

@cemo could you find a solution in the meantime?

**Comment by cemo** [comment]
We completely stopped using amplify. Since we were using only backend parts for our apps, the complex and error prone config files could not be justified on our side. I see no future for Amplify apart from as a prototyping framework. They have potential to break everything in all minor releases.

**Comment by david-wb** [comment]
Agreed. I feel like it could be useful if it focused exclusively on frontend hosting, like firebase, and didn't try to manage a bunch backend resources for you.

**Comment by MikiMullorXjump** [comment]
Running into the same issue.  Amplify does feel flimsy.

**Comment by irSteve** [comment]
Also experiencing issue. We moved from one AWS account and Azure DevOps git repo, to another AWS account and github repo. 

Local build works, Amplify push works, github ci/cd fails. Super frustrating! Build is looking for #current-cloud-backend.zip. 

Going to tear down all the functions, create new, then copy over the previous implementation code. We'll see if that works. 

So, Amplify is for single account, single repo prototypes that cannot transfer anywhere else. Nice...

**Comment by yanlin96** [comment]
running to the same issue on my windows PC, however, could do it using macbook pro. 
My steps:
1. basic React app in github, amplify link it and hosting
2. add a staging environment through amplify console
3. enable `amplify studio`
4. using ```amplify pull --appid xxxxxx --envName staging```
The error shows:
![image](https://user-images.githubusercontent.com/71164436/167136446-87fa2f76-cde4-4143-858b-0f1e39a28363.png)
