### ISSUE TITLE
Cannot get aws_cloudfront_response_headers_policy data source with custom headers

### ISSUE THREAD

**Issue by fattybenji** [hashicorp/terraform-provider-aws#21832]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.65.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s)

* aws_cloudfront_response_headers_policy (data source)

### Terraform Configuration Files

_Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation._

I added my actual code here, but I think any policy with custom headers would break.

```hcl
resource "aws_cloudfront_response_headers_policy" "security" {
  name    = "My-CustomSecurityPolicy"
  comment = "Managed by Terraform"

  security_headers_config {
    content_type_options {
      override = true
    }
  }

  custom_headers_config {
    items {
      header   = "X-Foo"
      override = true
      value    = "bar"
    }
  }
}
```

```hcl
data "aws_cloudfront_response_headers_policy" "security" {
  name = "My-CustomSecurityPolicy"
}
```

### Debug Output

https://gist.github.com/fattybenji/7ed8399d940942a01989a43417b524cf

I could not find anything more than the error message without debug enabled.

### Panic Output

N/A

### Expected Behavior

I should be able to import my data source

### Actual Behavior

Plan fails with an error:

```
│ Error: error setting custom_headers_config: Invalid address to set: []string{"custom_headers_config", "0", "items"}
│
│   with data.aws_cloudfront_response_headers_policy.security,
│   on main.tf line 6, in data "aws_cloudfront_response_headers_policy" "security":
│    6: data "aws_cloudfront_response_headers_policy" "security" {
```

### Steps to Reproduce

1. `terraform plan`

That's about it. When I removed my custom headers configuration, the plan worked.

### Important Factoids

I got the syntax of custom headers from browsing the code, the documentation should probably include examples (it is not easily understood).

I reproduced when editing the policy in the Console (removing the header makes it work, adding it back breaks)

### References

Nothing that I could find

**Comment by ewbankkit** [comment]
##### `aws_cloudfront_response_headers_policy` resource:

https://github.com/hashicorp/terraform-provider-aws/blob/889a92755da81a5fd8102d4d386ef96018df60d0/internal/service/cloudfront/response_headers_policy.go#L109-L138

##### `aws_cloudfront_response_headers_policy` data source:

https://github.com/hashicorp/terraform-provider-aws/blob/889a92755da81a5fd8102d4d386ef96018df60d0/internal/service/cloudfront/response_headers_policy_data_source.go#L93-L112

Missing `items` intermediate block.

@fattybenji Thanks for raising this issue. I'll work on a fix.

**Comment by fattybenji** [comment]
Thank you very much, it works very well. I didn't expect it to be fixed that fast, that was a nice surprise.
