### ISSUE TITLE
ecs_task_definition data source arn

### ISSUE THREAD

**Issue by christiansaiki** [hashicorp/terraform-provider-aws#21841]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I was wondering if it's possible to include the arn of the taskdef in the ecs_task_definition data source?
Because it's one of the outputs of the [aws_ecs_task_definition resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition)

### New or Affected Resource(s)

[Data Source: aws_ecs_task_definition](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ecs_task_definition)

**Comment by Victorp99** [comment]
Hello! I would like to work on this issue!
