### ISSUE TITLE
Route53 Alias Record for S3 VPC Interface Endpoint

### ISSUE THREAD

**Issue by hungran** [hashicorp/terraform-provider-aws#21845]
### Community Note
Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment
### Description

Every time you re-apply the script manually, you will be attend to see the changing of alias record for VPC S3 Interface Endpoint
          
```
    ~ resource "aws_route53_record" "r53_alias_vpc_endpoint" {
      id      = "Zxxx_s3.<region>.amazonaws.com_A"
      name    = "s3.<region>.amazonaws.com"
      # (5 unchanged attributes hidden)

    + alias {
        + evaluate_target_health = true
        + name                   = "*.xxx.s3.<region>.vpce.amazonaws.com"
        + zone_id                = "xxx"
      }
    - alias {
        - evaluate_target_health = true -> null
        - name                   = "\\052.xxx.s3.<region>.vpce.amazonaws.com" -> null
        - zone_id                = "xxx" -> null
      }
    }
```

### New or Affected Resource(s)
aws_route53_record
Potential Terraform Configuration
```tf
resource "aws_route53_record" "r53_alias_vpc_endpoint" {
  zone_id = aws_route53_zone.phz_vpc_endpoints.zone_id
  name    = format("%s.%s.amazonaws.com", contains(split("",var.vpc_endpoint_service_name), ".") ? join(".",[split(".",var.vpc_endpoint_service_name)[1],split(".",var.vpc_endpoint_service_name)[0]]) : var.vpc_endpoint_service_name, data.aws_region.current.name)
  type    = "A"
  alias {
    name                   = aws_vpc_endpoint.vpce.dns_entry[0].dns_name
    zone_id                = aws_vpc_endpoint.vpce.dns_entry[0].hosted_zone_id
    evaluate_target_health = true
  }
}

```
References
###0

**Comment by psipider** [comment]
Just a quick comment to say we're seeing the exact same behaviour and were wondering if there's any news yet, or if we can create a workaround?

Thanks.

**Comment by amenocal** [comment]
So this could be an underlying problem with the SDK and how the AWS console returns the value.

I checked CloudTrail and it seems that the correct value is being sent:

```
"changes": [
                {
                    "action": "CREATE",
                    "resourceRecordSet": {
                        "name": "s3.us-east-1.amazonaws.com",
                        "type": "A",
                        "aliasTarget": {
                            "hostedZoneId": "Z7HUB22UULQXV",
                            "dNSName": "*.vpce-XXXXX-XXXXX.s3.us-east-1.vpce.amazonaws.com",
                            "evaluateTargetHealth": true
                        }
                    }
                }
            ]
```

Tested the S3 record and it worked fine.

However the aws cli when listing the record sets does return `\\052` as the DNSName 😵

**Comment by mliac7** [comment]
i am running into this issue as well. has anyone been able to find a solution?

**Comment by justinretzolk** [comment]
Related: #10843

**Comment by brankodjurkic** [comment]
Would be nice to have this implemented 👍

**Comment by nsergeev-nomihealth** [comment]
Have the same issue on every terraform plan

**Comment by skeggse** [comment]
FYI I think I fixed this in https://github.com/hashicorp/terraform-provider-aws/pull/36699; can anyone repro from v5.44.0 on?

**Comment by ewbankkit** [comment]
Closes via https://github.com/hashicorp/terraform-provider-aws/pull/36699.
