### ISSUE TITLE
MSK public access feature

### ISSUE THREAD

**Issue by mgusiew-guide** [hashicorp/terraform-provider-aws#21859]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is a new API from AWS that enables public connectivity to MSK: https://docs.aws.amazon.com/msk/latest/developerguide/public-access.html

### New or Affected Resource(s)

* aws_msk_cluster

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

resource "aws_msk_cluster" "example" {
  ...
  public_access {
    type = "SERVICE_PROVIDED_EIPS" 
  }
  ...
}

resource "aws_msk_cluster" "example" {
  ...
  public_access {
    type = "DISABLED" 
  }
  ...
}

```

### References

* #0000

**Comment by nuttmeister** [comment]
Writing up tests and the docs. Hopefully done later tonight.
But if anyone are up for testing it the branch can be found here:
https://github.com/nuttmeister/terraform-provider-aws/tree/add-kafka-public-access-support

There are 2 heavy caveats though with this. 1 obvious and 1 less obvious.
The obvious one is that it has to be in a public subnet with an attached igw (makes sense).
The second not at all obvious is that public access can ONLY be enabled on an existing cluster.

I dunno why AWS chose this route, since the default setting is disabled. I hope it will be rectified later...
But for now you need to first create it and then update it with the public_access block.

I added the `public_access block` to the `broker_node_group_info` block so it will correspond more to the API.

To enable simply use

```hcl
resource "aws_msk_cluster" "this" {
  ...
  broker_node_group_info {
    ...
    public_access {
      type = "SERVICE_PROVIDED_EIPS"
    }
  }
}
```

**Comment by mgusiew-guide** [comment]
I think I may know the answer to the update requirement. 

When AWS creates a cluster by default it sets 'allow.everyone.if.no.acl.found' config to true. This basically disables all security on cluster until you add some ACLs which is bit dangerous, especially if you want to expose cluster to Internet. I think the reason why AWS does that is to allow clients to create admin user and give it ACLs via Kafka brokers. This makes it possible to not use Zookeeper which is deprecated and will be removed in future versions of the Kafka. If 'allow.everyone.if.no.acl.found' was set on newly created cluster, then AWS would need to either provide some admin user or the user would have to be created using Zookeeper (this is already deprecated). Hence the requirement: 

"If you are using the SASL/SCRAM or mTLS access-control methods, you must set Apache Kafka ACLs for your cluster. After you set the Apache Kafka ACLs for your cluster, update the cluster's configuration to have the property allow.everyone.if.no.acl.found to false for the cluster. For information about how to update the configuration of a cluster, see Amazon MSK Configuration Operations. If you are using IAM access control and want to apply authorization policies or update your authorization policies, see IAM access control. For information about Apache Kafka ACLs, see Apache Kafka ACLs." 

So for mTLS and SASL/SCRAM the current flow will be sth like this:
1) Create a cluster with allow.everyone.if.no.acl.found set to true and open connectivity disabled
2) Create admin user (SASL/SCRAM) or certificate (mTLS) and set admin ACL using brokers interface
3) Update cluster config to set allow.everyone.if.no.acl.found set to false and enable open connectivity

Hope this makes sense.

**Comment by nuttmeister** [comment]
Ahhh, okay. Interesting! Just thought it was a bit weird and for our use case a bit less nice. Create it to only have to update it directly after. But nice info. 

Will continue with the verifying the tests tonight tomorrow and then opening the PR.

**Comment by ertanden** [comment]
Is there an update on this? Thanks!

**Comment by milangm89** [comment]
When will MSK public access get implemented in terraform?

**Comment by marawu** [comment]
Wait any update:)

**Comment by gneveu** [comment]
Hello, 

This would be great to have this feature indeed, I understand enabling the public access to MSK cannot be done on a fresh new cluster so maybe it would be good to have another resource doin g this that would depend on the execution of `aws_msk_cluster` ?
