### ISSUE TITLE
aws_efs_file_system lifecycle_policy continues to fail with more than one argument

### ISSUE THREAD

**Issue by alvintownsend** [hashicorp/terraform-provider-aws#21862]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
terraform --version
Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.66.0
```

### Affected Resource(s)

* aws_efs_file_system

### Terraform Configuration Files

```hcl
resource "aws_efs_file_system" "my_efs" {
  performance_mode = "generalPurpose"
  throughput_mode  = "bursting"
  encrypted        = "true"

  lifecycle {
    prevent_destroy = true
  }

  lifecycle_policy {
    transition_to_ia                    = "AFTER_30_DAYS"
    transition_to_primary_storage_class = "AFTER_1_ACCESS"
  }

  tags = {
    Name = "my-efs"
  }
}
```

### Expected Behavior

I had an existing Terraform AWS EFS volume without a `lifecycle_policy`. I subsequently added the `lifecycle_policy` as noted above.

It is expected that the `lifecycle_policy` with both the `transition_to_ia` and `transition_to_primary_storage_class` would be set to their respective values.

### Actual Behavior

I received the following error:

```
aws_efs_file_system.my_efs: Modifying... [id=fs-063483dac5b7b61af]

│ Error: error updating EFS file system (fs-xxx) lifecycle configuration: BadRequest: One or more LifecyclePolicy objects specified are malformed.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "9afe1f37-5a77-4988-9ab8-dfca9eeef7dd"
│   },
│   ErrorCode: "BadRequest",
│   Message_: "One or more LifecyclePolicy objects specified are malformed."
│ }
│ 
│   with aws_efs_file_system.my_efs,
│   on efs.tf line 1, in resource "aws_efs_file_system" "my_efs":
│    1: resource "aws_efs_file_system" "my_efs" {
│ 
```

### Steps to Reproduce

1. `terraform plan -out my.plan`
1. `terraform apply my.plan`

### Important Factoids

The `lifecycle_policy` works fine with just one of the values:

```hcl
  lifecycle_policy {
    transition_to_ia                    = "AFTER_30_DAYS"
  }
```
or
```hcl
  lifecycle_policy {
    transition_to_primary_storage_class = "AFTER_1_ACCESS"
  }
```
but never both in the same block.

I've also tried applying with just one (the `transition_to_ia`) and then adding the second (`transition_to_primary_storage_class`) with a second apply, but I get the same error message.

What does work but is unclear from the documentation:

```hcl
  lifecycle_policy {
    transition_to_ia                    = "AFTER_30_DAYS"
  }

  lifecycle_policy {
    transition_to_primary_storage_class = "AFTER_1_ACCESS"
  }
```

### References

* #20953

**Comment by NK74** [comment]
Same issue with aws provider `hashicorp/aws v3.68.0`

**Comment by NK74** [comment]
Hello, any update ?

**Comment by lpossamai** [comment]
Same issue with provider `hashicorp/aws v3.61.0`.

**Comment by lpossamai** [comment]
> Same issue with provider `hashicorp/aws v3.61.0`.

This worked for me, as a workaround:

```
  lifecycle_policy {
    transition_to_ia                    = "AFTER_14_DAYS"
  }

  lifecycle_policy {
    # https://github.com/hashicorp/terraform-provider-aws/issues/21862
    transition_to_primary_storage_class = "AFTER_1_ACCESS"
  }
```

**Comment by jornfranke** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/25482
