### ISSUE TITLE
package_type is not optional when using image_uri

### ISSUE THREAD

**Issue by Aghassi** [hashicorp/terraform-provider-aws#21864]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_lambda_function

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_iam_role" "iam_for_lambda" {
  name = "iam_for_lambda"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

resource "aws_lambda_function" "cdn_migration_lambda" {
  function_name = "app"
  role          = "${aws_iam_role.iam_for_lambda.arn}"
  handler       = "app.handler"
  image_uri     = "ecr.us-west-2.amazonaws.com/lambda-image"
  package_type  = "Image"

  # This is because terraform, but it shouldn't matter because our container is 16
  runtime = "nodejs14.x"
}

```

### Debug Output

```
aws_lambda_function.web: Creating...

Error: error creating Lambda Function: InvalidParameterValueException: Please provide a source for function code.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "d0edd28a-7128-4225-9dd0-9307318bb752"
  },
  Message_: "Please provide a source for function code.",
  Type: "User"
}
```

### Expected Behavior

Terraform should infer the package_type based on image_uri being set, it's not optional

### Actual Behavior

It fails to deploy, but it passes `plan` which is even worse.

### Steps to Reproduce

Create a lambda function that has an `image_uri` but not a `package_type` and see it fail to apply, but pass on plan.

1. `terraform apply`

### References

* [#16664](https://github.com/hashicorp/terraform-provider-aws/issues/16664)
* docs for aws_lambda_function say package_type is optional https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function

**Comment by justinretzolk** [comment]
Hey @Aghassi 👋 This appears to be due to `package_type` defaulting to `zip`, whereas you're using an `image`. Do you feel that a satisfactory resolution would be to add a note indicating that if `image_uri` is passed, `package_type` must be set to `image`?

**Comment by Aghassi** [comment]
Documenting that would be good, but also a `terraform plan` should catch this.

**Comment by tomerghelber** [comment]
Is there a way to make the configuration change by the package type?
The types share some options, but also have different options.
