### ISSUE TITLE
Passing an empty string to data.aws_iam_policy_document.sources_list crashes plugin

### ISSUE THREAD

**Issue by vrih** [hashicorp/terraform-provider-aws#21880]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.10
AWS v3.66.0

### Affected Resource(s)

* data.aws_iam_policy_document

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
locals {
  a = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
      {
          "Effect": "Allow",
          "Action": [
              "ec2:DescribeInstances",
              "iam:GetInstanceProfile",
              "iam:GetRole"
          ],
          "Resource": "*"
      }
    ]
}
EOF
  b = ""
}

data "aws_iam_policy_document" "test" {
  source_policy_documents = [local.a, local.b]
}

resource "aws_iam_policy" "test" {
  name   = "test"
  policy = data.aws_iam_policy_document.test.json
}


```

### Panic Output

Stack trace from the terraform-provider-aws_v3.66.0_x5 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 69 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/iam.dataSourcePolicyDocumentRead(0xc001e82600, 0x89840e0, 0xc001a54000, 0xf42b870, 0xc00008a900)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/iam/policy_document_data_source.go:138 +0x1a7f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000885500, 0xaaffd48, 0xc000115e80, 0xc001e82600, 0x89840e0, 0xc001a54000, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc000885500, 0xaaffd48, 0xc000115e80, 0xc000564880, 0x89840e0, 0xc001a54000, 0xc001a54000, 0xc000564880, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:558 +0xfd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc00011cea0, 0xaaffd48, 0xc000115e80, 0xc000564460, 0xc000115e80, 0x100b665, 0x9593780)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/grpc_provider.go:1105 +0x4d6
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadDataSource(0xc001f90260, 0xaaffdf0, 0xc000115e80, 0xc00180a9b0, 0xc001f90260, 0xc0018428a0, 0xc001fa8ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:247 +0xe5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler(0x9952720, 0xc001f90260, 0xaaffdf0, 0xc0018428a0, 0xc00267e720, 0x0, 0xaaffdf0, 0xc0018428a0, 0xc0005d6540, 0x1ad)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00013ba40, 0xab2aef8, 0xc001c88300, 0xc00017e200, 0xc0019c6a80, 0xf3e9a70, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00013ba40, 0xab2aef8, 0xc001c88300, 0xc00017e200, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0010ae160, 0xc00013ba40, 0xab2aef8, 0xc001c88300, 0xc00017e200)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.66.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
### Expected Behavior

Provider should either fail on empty string or ignore input.

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by jar-b** [comment]
closed by #26640
