### ISSUE TITLE
Add support for graviton fargate

### ISSUE THREAD

**Issue by bacoboy** [hashicorp/terraform-provider-aws#21885]
Support for graviton Fargate containers was recently announced.
We'll need an additional parameter added to specify the architecture in the `aws_ecs_task_definition` resource (as well as the reading via the data source counterpart.

https://aws.amazon.com/blogs/aws/announcing-aws-graviton2-support-for-aws-fargate-get-up-to-40-better-price-performance-for-your-serverless-containers/

**Comment by acdha** [comment]
This looks like a duplicate of #21706

**Comment by bacoboy** [comment]
I wasn't sure -- I guess it depends on the underlying implementation.  Could be that the same PR solves both of these.

**Comment by justinretzolk** [comment]
Hey @acdha 👋 Thanks for taking the time to submit this issue. It looks like this is indeed a duplicate of #21706. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #21706.
