### ISSUE TITLE
`AccessDenied: No AWSAccessKey was presented.` when migrating state to `s3` backend

### ISSUE THREAD

**Issue by jszwedko** [hashicorp/terraform-provider-aws#21883]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.66.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Affected Resource(s)

* `s3` state backend

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_dynamodb_table" "terraform-root-locks" {
  name         = "TerraformRootLocks"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "LockID"

  attribute {
    name = "LockID"
    type = "S"
  }

  lifecycle {
    ignore_changes = [
      read_capacity,
      write_capacity,
    ]
    prevent_destroy = "true"
  }
}

resource "aws_s3_bucket" "state" {
  bucket = "vector-root-state"
  acl    = "private"

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "aws:kms"
      }
    }
  }

  versioning {
    enabled = true
  }
}

terraform {
  backend "s3" {
    bucket         = "vector-root-state"
    key            = "management.tfstate"
    encrypt        = true
    dynamodb_table = "TerraformRootLocks"
  }
}
```

### Debug Output

https://gist.github.com/jszwedko/a04039b196ea3b668bcf21977782f3a2

### Expected Behavior

Terraform migrates the state.

### Actual Behavior

An error about an access key not being provided is returned.

### Steps to Reproduce

1. Comment out the above remote state configuration
2. `terraform apply` to create and store state locally
3. Uncomment remote state configuration
4. `terraform init -migrate-state`

### Important Factoids

You can see in the debug log that the call to STS `GetCallerIdentiy` is successful so it's not clear to me why the later calls are failing with a complaint that there was no access key provided.

I am providing the AWS credentials through environment variables via `aws-vault`.

**Comment by justinretzolk** [comment]
Hey @jszwedko 👋 Thank you for taking the time to file this. This is likely more of a Terraform issue than an AWS provider issue, but a couple of things immediately come to mind to look at regardless. Full disclosure; this may wind up being a situation where we need to refer you over to [hashicorp/terraform](https://github.com/hashicorp/terraform) to file an issue there.

The first would be to validate that running `env | grep "AWS"` shows a value set for both `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` (I think it goes without saying, but just to be explicit, please do _not_ provide the output from that without redacting the values).

I'd also personally check to see if you have anything set up in `~/.aws/credentials` or `~/.aws/config` that might be overriding these values.

Finally, I'd also recommend trying to run `aws s3 ls s3://vector-root-state` to verify that you're not running into permissions issues that might be reporting in a less than ideal way. Can you check these things and let me know if anything jumps out at you?
