### ISSUE TITLE
Feature request: Implementation of subnet CIDR reservation

### ISSUE THREAD

**Issue by mvignesh12** [hashicorp/terraform-provider-aws#21897]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Subnet CIDR reservation functionality is used to reserve subset of CIDR range inside a subnet. It gives more control to assign the subset of CIDR range and also specify IPs to resources without getting auto assigned.

It will be helpful if this can be natively supported in Terraform AWS provider.

### New or Affected Resource(s)

* aws_subnet

### References

* https://docs.aws.amazon.com/vpc/latest/userguide/subnet-cidr-reservation.html

**Comment by georgebuckerfield** [comment]
I've started some work on implementing this as it's something we'd like to use as well - I'll try and get a PR drafted over the next couple of days.
