### ISSUE TITLE
Multiple rules in ECR replication configuration

### ISSUE THREAD

**Issue by sophos-daniels** [hashicorp/terraform-provider-aws#21898]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

ECR now supports up to 10 rules and 25 destinations per rule. Support passing in multiple rules.

### New or Affected Resource(s)

* aws_ecr_replication_configuration

### Potential Terraform Configuration

```hcl
data "aws_caller_identity" "current" {}

resource "aws_ecr_replication_configuration" "example" {
  replication_configuration {
    rule {
      destination {
        region      = "us-west-1"
        registry_id = data.aws_caller_identity.current.account_id
      }

      destination {
        region      = "us-west-2"
        registry_id = data.aws_caller_identity.current.account_id
      }
    }

    rule {
      destination {
        region      = "us-west-1"
        registry_id = "111122223333"
      }

      destination {
        region      = "us-west-2"
        registry_id = "111122223333"
      }
    }
  }
}
```

### References

https://docs.aws.amazon.com/AmazonECR/latest/userguide/registry-settings-examples.html#registry-settings-examples-multiple-rules

**Comment by sjonpaulbrown** [comment]
I have worked on this and created the following https://github.com/hashicorp/terraform-provider-aws/pull/22281

This request requires small changes to the schema of the resource so that the limits match that of the AWS API.
