### ISSUE TITLE
aws_s3_bucket_replication_configuration: event_threshold block in metrics should not be required

### ISSUE THREAD

**Issue by robmp** [hashicorp/terraform-provider-aws#21895]
Thanks for implementing S3 bucket replication as a separate resource. Unfortunately it has the following issue which prevents us from being able to us it: having `metrics` enabled, but `replication_time` not specified or disabled is a perfectly valid configuration in AWS, but is currently impossible to achieve with Terraform AWS provider.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.11
+ provider registry.terraform.io/hashicorp/aws v3.66.0
```

### Affected Resource(s)

* aws_s3_bucket_replication_configuration

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket_replication_configuration" "this" {
  #(...)

  rule {
    destination {
      metrics {
        status = "Enabled"
      }

      # replication_time not specified
    }
  }
}
```
or
```hcl
resource "aws_s3_bucket_replication_configuration" "this" {
  #(...)

  rule {
    destination {
      metrics {
        event_threshold {
          minutes = 15
        }
        status = "Enabled"
      }

      # replication_time not specified
    }
  }
}
```

### Expected Behavior

Replication metrics and notifications should be enabled.

### Actual Behavior

The first configuration result:
```
╷
│ Error: Insufficient event_threshold blocks
│
│   on main.tf line 115, in resource "aws_s3_bucket_replication_configuration" "this":
│  115:       metrics {
│
│ At least 1 "event_threshold" blocks are required.
╵
```
The second configuration result:
```
╷
│ Error: error creating S3 replication configuration for bucket (bucket-name): InvalidArgument: Metrics cannot contain an event threshold when ReplicationTime is not specified or Disabled
│       status code: 400, request id: XXX, host id: XXX=
│
```

### Steps to Reproduce

1. `terraform apply`

**Comment by haytham-salhi** [comment]
@anGie44 this issue still exists! Still we get `Metrics cannot contain an event threshold when ReplicationTime is not specified or Disabled` when enabling the metrics only!!! Please advise.

**Comment by anGie44** [comment]
Hi @haytham-salhi , thank you for your feedback! Do you mind opening a new issue with all the required info (tf config, provider version, tf version, etc.) so we can look into it further? thanks!
