### ISSUE TITLE
aws_lambda_invocation : apply vs destroy

### ISSUE THREAD

**Issue by abruyelles** [hashicorp/terraform-provider-aws#21905]
Hi,

We are using the aws_lambda_invocation datasource from the aws provider as a way to protect some access while letting untrusted users perform the task

To illustrate, we want to create AWS ACM certificate, they require a DNS TXT
Our users are free to create the ACM certificates as well
However, we cannot let them manage the DNS zones
We are using an aws_lambda_invocation as a helper:
- the user creates an aws_acm_certificate resource in its own AWS account
- the user calls an aws_lambda_invocation datasource with, as parameter, the information of the newly created ACM certificate
- the lambda has the right to create the appropriate TXT

So far, so good

However, we have an issue on destroy : the TXT records are not deleted, because we cannot make the difference between an apply and a destroy : datasource parameters are the same

It would be awesome if an extra, optional parameter could be put to make the difference between an apply and a destroy

**Comment by justinretzolk** [comment]
Hey @abruyelles 👋 Thank you for taking the time to raise this! So that we have all of the necessary information to prioritize and investigate this, can you update the issue description with the rest of the information requested in the [feature request template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Feature_Request.md)?

**Comment by abruyelles** [comment]
@justinretzolk Sure, my bad
The affected resource would be `aws_lambda_invocation`
A potential terraform configuration would be something like this:

```
data "aws_lambda_invocation" "example" {
  function_name = aws_lambda_function.lambda_function_test.function_name
  differentiate_on_destroy = "my_custom_field"

  input = <<JSON
{
  "key1": "value1",
  "key2": "value2"
}
JSON
}
```

If `differentiate_on_destroy` is unset (the current, default value), then that json would be sent on all invocations:
```
{
  "key1": "value1",
  "key2": "value2"
}
```

If `differentiate_on_destroy` is set, then the same json would be sent for applies
However, for destroy, it would become:
```
{
  "key1": "value1",
  "key2": "value2",
  "my_custom_field": true
}
```

That new variable would be a string and not a boolean, because a hard-coded field name may overlaps with the user document

Thank you for reviewing
