### ISSUE TITLE
When using the provider to create and manage a svm,... the provider functions but every run we do, the provider want to scratch (rebuild) the svm becaus the file_systems_administrators_group value seems to be not recorded properly in the state....

### ISSUE THREAD

**Issue by philippecotter** [hashicorp/terraform-provider-aws#21919]
When i deploy the 1st time, it's ok, but when any other change is done on anything else, when TF calls the provider 
the error is issuing on the file_system_administrators_group     value and 

the output is like that:

------------------------------
     ~ active_directory_configuration {
            # (1 unchanged attribute hidden)

          ~ self_managed_active_directory_configuration {
              + file_system_administrators_group        = "CHVGGS-APP_NAS_Admins" # forces replacement
                # (5 unchanged attributes hidden)
            }
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.

It will be great if we can have a little help on it or a code debug on this feature !

Thanks to all community for the job ! Very appreciated.

B. r.

Philippe Cotter
philippe.cotter@richemont.com

**Comment by philippecotter** [comment]
Hi to all.

I re-tried this morning to show what was passed from TF:

--------------------------
Terraform v1.0.11
on linux_amd64
Configuring remote state backend...
Initializing Terraform configuration...
...

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_fsx_ontap_storage_virtual_machine.svm_xfls00002 will be created
  + resource "aws_fsx_ontap_storage_virtual_machine" "svm_xfls00002" {
      + arn                        = (known after apply)
      + endpoints                  = (known after apply)
      + file_system_id             = "fs-0d33a074f0ed9a1a1"
      + id                         = (known after apply)
      + name                       = "svm_xfls00002"
      + root_volume_security_style = "UNIX"
      + subtype                    = (known after apply)
      + svm_admin_password         = (sensitive value)
      + tags                       = {
          + "Application"       = "FSX-N pilot"
          + "Description"       = "Pilot of FSX NetApp"
          + "Environment"       = "Pilot"
          + "INC"               = "xxxxxxxxx"
          + "InternetPublished" = "No"
          + "Maison"            = "Richemont"
          + "Name"              = "svm_xfls00002"
          + "PowerPolicy"       = "24/7"
          + "ServiceMapping"    = "12467"
          + "coverage"          = "24/7"
        }
      + tags_all                   = {
          + "Application"       = "FSX-N pilot"
          + "Description"       = "Pilot of FSX NetApp"
          + "Environment"       = "Pilot"
          + "INC"               = "xxxxxxxxx"
          + "InternetPublished" = "No"
          + "Maison"            = "Richemont"
          + "Name"              = "svm_xfls00002"
          + "PowerPolicy"       = "24/7"
          + "ServiceMapping"    = "12467"
          + "coverage"          = "24/7"
        }
      + uuid                       = (known after apply)

      + active_directory_configuration {
          + netbios_name = "XFLS00002"

          **+ **self_managed_active_directory_configuration {
              + dns_ips                                 = [
                  + "10.68.165.178",
                  + "10.68.165.186",
                ]
              + domain_name                             = "RCCAD.NET"
              + file_system_administrators_group        = "CHVGGS-APP_NAS_Admins"
              + organizational_unit_distinguidshed_name = "OU=Unmanaged,OU=EUAWS,OU=Hosting,OU=Servers,DC=rccad,DC=net"
              + password                                = (sensitive value)
              + username                                = "S-EUAWSG.STO-AUTO"****
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

--------------------------


Just after the OU distinguished entries,... the file_system_administrators_group is not sent to AWS from TF....

I think it's why the TF don't have this entry set in the state file and try eternally to rebuild the SVM... :(

I hope it will helps for debut...

Thanks in advance for your help.

B. r.

Philippe

PS: at your disposal if you need more infos

**Comment by philippecotter** [comment]
And.... precision:

We know that's optional but we are not using the Domain Admins default value (if nothing is mentionned), because our IAM department avoid using this AD group for use. Restricted.

We really need to provide our Storage service department account (a specific one).... 

It's why it's very important to have it functional.

Thanks 

Phil

**Comment by DrFaust92** [comment]
See #23314
Closing this as the discussion and details in the above ticket are more informative and contain AWS response.
