### ISSUE TITLE
resource/aws_elasticache_user_group: `TestAccElastiCacheUserGroup_tags` references incorrect resource names

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#21924]
The acceptance test `TestAccElastiCacheUserGroup_tags` fails because the Terraform configuration used for the final step does not use resource names consistent with the first two steps. The first two steps use the resource name `aws_elasticache_user.test` and the final step uses `aws_elasticache_user.test1`

**Comment by drarnold** [comment]
Hey @gdavison 
Thanks for finding this bug.  I'll get a pull request submitted for the fix.

**Comment by drarnold** [comment]
This MR should resolve that broken test! When you have a change give a 👍  if you think the solution is acceptable!  Thanks!
