### ISSUE TITLE
Add aws_network_interface_tag

### ISSUE THREAD

**Issue by nobiit** [hashicorp/terraform-provider-aws#21933]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When I add resource type`aws_nat_gateway`. It will generate`aws_network_interface` by itself. And there is currently no way to customize the tag for the `aws_network_interface` object created this way.
### New or Affected Resource(s)

* aws_nat_gateway
* aws_network_interface

### Potential Terraform Configuration

```hcl
resource "aws_nat_gateway" "example" {
  allocation_id = aws_eip.example.id
  subnet_id     = aws_subnet.example.id

  tags = {
    Name = "gw NAT"
  }
}
```

### References

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/resource-tagging

**Comment by DrFaust92** [comment]
Hi, I think https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_tag can be used to solved this.

**Comment by nobiit** [comment]
Hey @DrFaust92 , Can you give an example to prove it?

**Comment by ewbankkit** [comment]
@nobiit 

```hcl
resource "aws_ec2_tag" "example" {
  resource_id = aws_nat_gateway.example.network_interface_id

  key   = "Name"
  value = "NAT GW ENI"
}
```

will add the `Name` tag with value `NAT GW ENI`.
