### ISSUE TITLE
aws_route53_zone should not sort its name_servers list

### ISSUE THREAD

**Issue by wilkej** [hashicorp/terraform-provider-aws#21965]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

``` bash
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.64.2
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s)

* aws_route53_zone

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl

resource "aws_route53_zone" "route53zone" {
  name     = "my-domain.com"
}

resource "aws_route53_record" "record" {
  name    = "my-domain.com"
  ttl     = 900
  type    = "SOA"
  zone_id = aws_route53_zone.route53zone.zone_id
  records = [
    "${aws_route53_zone.route53zone.name_servers[3]}. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400"
  ]
}
```

### Expected Behavior

This issue is basically a copy of https://github.com/hashicorp/terraform-provider-aws/issues/3447

I'd like to manage the Route 53 SOA record in Terraform, in order to control the negative caching TTL.

The following record would seem to work, except that name_servers[0] is not the primary name server that AWS chooses by default, because the order of name_servers is not preserved by Terraform.

It appears that Terraform sorts the list. Is there a good reason for this? I wouldn't expect AWS to start reordering these arbitrarily.

### Actual Behavior

Nameserver output is sorted

### References

`aws route53 get-hosted-zone --id ...` output is different than 
```hcl 
output "r53_record_test_for_me" {
  value = aws_route53_zone.route53zone.name_servers
}
```

**Comment by jbg** [comment]
I hit this today, also when trying to set up SOA records programmatically.

The sorting is unfortunate, but removing it might cause a lot of unwanted changes in existing configs. Maybe a `primary_name_server` attribute could be added to provide what should be `name_servers[0]` if they were not sorted?
