### ISSUE TITLE
aws_msk_cluster: client_authentication.sasl block is considered removed when client_authentication.tls is used

### ISSUE THREAD

**Issue by juniorz** [hashicorp/terraform-provider-aws#21962]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.67.0
```

### Affected Resource(s)

* aws_msk_cluster

### Terraform Configuration Files

I have a cluster with TLS authentication enabled

```hcl
resource "aws_msk_cluster" "green" {

  client_authentication {
    tls {
      certificate_authority_arns = ["arn:aws:acm-pca:xxx"]
    }
  }

}
```

After some change via the UI, the terraform state now believes a `client_authentication.sasl` block is missing:

```
$ terraform plan
[...]
Terraform will perform the following actions:

  # aws_msk_cluster.green must be replaced
-/+ resource "aws_msk_cluster" "green" {
[...]
      ~ client_authentication {
          - sasl { # forces replacement
              - iam   = false -> null
              - scram = false -> null
            }

            # (1 unchanged block hidden)
        }
[...]
    }
```

It expects an "all false" (no-op) block, but I have an "all null" block (it's absent). However, the validation imposed by the resource prevents me from adding the "all false":

```
$ terraform plan
╷
│ Error: Conflicting configuration arguments
│
│   with aws_msk_cluster.green,
│   on green.tf line 31, in resource "aws_msk_cluster" "green":
│   31:     sasl {
│
│ "client_authentication.0.sasl": conflicts with client_authentication.0.tls
╵
```

### Expected Behavior

The absent `client_authentication.sasl` block (with both properties set to `null`) should be treated similarly to an "all false" block.

Alternatively, the conflict check should be between `client_authentication.0.tls` and any of `client_authentication.0.sasl.iam` or `client_authentication.0.sasl.scram` being equal to `true`.

### Actual Behavior

An absent block is treated differently than an "all false" block, and causes a recreate - which is dangerous).

This can be worked around by ignoring changes to `sasl` (since `tls` is used in this cluster):

```
  lifecycle {
    ignore_changes = [
      client_authentication["sasl"],
    ]
  }
```

### References

* #20956 (may be related to this, but I'm not sure about its scope)

**Comment by ewbankkit** [comment]
@juniorz Thanks for raising this issue.
It has already been noticed in #20956. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
