### ISSUE TITLE
aws_api_gateway_base_path_mapping: API Gateway V1 doesn't support the slash character (/) in base path mappings. To create a multi-level base path mapping, use API Gateway V2

### ISSUE THREAD

**Issue by paulalex** [hashicorp/terraform-provider-aws#21986]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform v0.14.4
hashicorp/aws v3.67.0

### Affected Resource(s)

aws_api_gateway_base_path_mapping

### Terraform Configuration Files

```
resource "aws_api_gateway_base_path_mapping" "api_v1" {
  api_id     = aws_api_gateway_rest_api.api_v1.id
  stage_name = aws_api_gateway_deployment.api_v1.stage_name

  domain_name = local.api_domain
  base_path   = local.api_base_path
}
```

### Expected Behavior

Terraform creates the base path mapping with slashes, I have confirmed this works as expected in the console.

### Actual Behavior

```
Error: Error creating Gateway base path mapping: BadRequestException: API Gateway V1 doesn't support the slash character (/) in base path mappings. To create a multi-level base path mapping, use API Gateway V2.

on api_gateway.tf line 37, in resource "aws_api_gateway_base_path_mapping" "api_v1":
37: resource "aws_api_gateway_base_path_mapping" "api_v1" {
```

### Steps to Reproduce

* Create a regional API gateway custom domain with TLS1.2
* Create a regional API gateway `aws_api_gateway_rest_api`
* Confirm you can create a base path mapping for the domain and API gateway in the AWS console ( mapping needs a forward slash, e.g `service/items`
* Try to create the same base path mapping for the API gateway using terraform

**Comment by paulalex** [comment]
I am not sure if this is actually specifically related to terraform as whilst it works through the AWS console, I gave it a try using the cli:

```
aws apigateway create-base-path-mapping --domain-name "my.domain" --base-path "service/v1" --rest-api-id 7919ihtkbb

An error occurred (BadRequestException) when calling the CreateBasePathMapping operation: API Gateway V1 doesn't support the slash character (/) in base path mappings. To create a multi-level base path mapping, use API Gateway V2.
```

**Comment by justinretzolk** [comment]
Hey @paulalex 👋 Thank you for taking the time to raise this. This is an interesting one because the error you're seeing is coming from AWS (which is backed up by you seeing the same error from the AWS CLI). On the other hand, looking at the [Go SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/apigateway/#BasePathMapping) and the [AWS API](https://docs.aws.amazon.com/apigateway/api-reference/link-relation/basepathmapping-create/) itself, I see no mention of the restriction. Furthermore, when looking into this, I found an [AWS document](https://aws.amazon.com/blogs/compute/using-multiple-segments-in-amazon-api-gateway-base-path-mapping/) indicating that: 

> Multi-level base path mapping works with REST (ApiGatewayV1) and HTTP (ApiGatewayV2) APIs.

Ultimately, this looks like an upstream thing where perhaps the AWS API endpoints aren't in line with reality. I'll leave this one here for now and try to reach out to AWS to see if we can get some more clarity.

**Comment by mickael-coquer** [comment]
Hey guys,

We've had the same issue, coming from AWS obviously. We have got it working by using the V2 API (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_api_mapping), which is working with V1 API fortunately :). Hope this helps.

**Comment by jgibert-at-wiris** [comment]
Hey everyone!
We are suffering the same issue. We can always deploy the API mappings manually after everything else is deployed with terraform, but would obviously like to do it all together. 

@justinretzolk Did you hear anything back from AWS? Any issue we could track on that side?

Thanks a lot!

**Comment by paulalex** [comment]
> Hey everyone! We are suffering the same issue. We can always deploy the API mappings manually after everything else is deployed with terraform, but would obviously like to do it all together.
> 
> @justinretzolk Did you hear anything back from AWS? Any issue we could track on that side?
> 
> Thanks a lot!

Are you using serverless framework? For the time being I have moved this out to my sls config:

```
 customDomain:
    domainName: api.${opt:domain}.company.aws.cloud.io
    basePath: ${opt:base-path}/v1/report
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: "regional"
```

This might be helpful to somebody!

**Comment by justinretzolk** [comment]
Hey y'all 👋 I've heard back from AWS and it seems this may wind up being expected behavior. To summarize what they've told me:

- Multi-level base path mapping _are_ supported for both Rest APIs and HTTP APIs
- ...however, the API call from the CLI that is designed to work with this is in `apigatewayv2`.

- When you create a base path with `/` via console, it calls the `apigatewayv2` API call to accomplish the action.

- For what it's worth, they provided an example CLI command that would work for both Rest and HTTP APIs.:

    ```shell
    $ aws apigatewayv2 create-api-mapping —domain-name “my.domain” —api-id 7919ihtkbb —stage stageName —api-mapping-key service/v1
    ```

**Comment by jgibert-at-wiris** [comment]
Hi again! Thanks @justinretzolk :)
This seems to be in accordance with @mickael-coquer's comment above. We have tried the following, which works fine and creates a multilevel base path mapping for a REST API:

```
resource "aws_api_gateway_rest_api" "this" {
  ...
}

resource "aws_api_gateway_deployment" "this" {
  rest_api_id = aws_api_gateway_rest_api.this.id
  ...
}

resource "aws_api_gateway_stage" "this" {
  deployment_id = aws_api_gateway_deployment.this.id
  rest_api_id   = aws_api_gateway_rest_api.this.id
  stage_name    = var.stage_name
  ...
}

data "aws_route53_zone" "this" {
  name = var.domain
}

data "aws_api_gateway_domain_name" "this" {
  domain_name = "${var.subdomain}.${data.aws_route53_zone.this.name}"
}

resource "aws_route53_record" "this" {
  name    = data.aws_api_gateway_domain_name.this.domain_name
  type    = "A"
  zone_id = data.aws_route53_zone.this.zone_id
  ...
}

resource "aws_apigatewayv2_api_mapping" "this" {
  domain_name     = data.aws_api_gateway_domain_name.this.id
  api_id          = aws_api_gateway_rest_api.this.id
  stage           = aws_api_gateway_stage.this.stage_name
  api_mapping_key = "multi/level/base/path"
}
```



So, even though the REST API is V1, using the V2 API mappings successfully deploys the multilevel base path mapping.
Thanks again!
