### ISSUE TITLE
aws_sns_platform_application Token authentication method for APNS

### ISSUE THREAD

**Issue by stawii** [hashicorp/terraform-provider-aws#22008]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The AWS API support two types of authentication for APNS:
* For APNS and APNS_SANDBOX using certificate credentials, PlatformPrincipal is SSL certificate and PlatformCredential is private key.
* For APNS and APNS_SANDBOX using token credentials, PlatformPrincipal is signing key ID and PlatformCredential is signing key.

However the  `aws_sns_platform_application` resource does not recognize the `PlatformPrincipal` as a signing key ID and fails.
After bit of debugging I've found that payload is missing the `"AuthenticationMethod": "Token"` field in `Attributes`.

Quick and dirty solution might be to check if `platform = "APNS" && len(platform_principal) = 10`, and then add `AuthenticationMethod=Token` attribute.
Alternatively, more elastic and future proof solution is to let user set `AuthenticationMethod` by adding new `authentication_method` parameter to the resource.

### New or Affected Resource(s)

* aws_sns_platform_application

### References

* [AWS API CreatePlatformApplication](https://docs.aws.amazon.com/sns/latest/api/API_CreatePlatformApplication.html)

**Comment by NoumanKhurram** [comment]
Looking at the AWS SNS platform application configuration interface Team ID and Bundle ID are the required fields as well. So will be good to add those as well if it's a token-based authentication.

<img src="https://user-images.githubusercontent.com/59646631/146969557-73c68c77-7827-4f03-bb83-0fb5aa2c05f7.png" width="500" height="450">

**Comment by mdrobny** [comment]
2 additional attributes must be provided as documented here https://docs.aws.amazon.com/sns/latest/api/API_SetPlatformApplicationAttributes.html

> The following attributes only apply to APNs token-based authentication:
ApplePlatformTeamID – The identifier that's assigned to your Apple developer account team.
ApplePlatformBundleID – The bundle identifier that's assigned to your iOS app.

So looks like 2 new arguments (Apple/APNS specific) must be added also to this resource
- `apple_platform_team_id`
- `apple_platform_bundle_id`

---

@stawii I don't see in the AWS SDK SNS docs sign of 
> "AuthenticationMethod": "Token" field in Attributes.

I am checking here https://docs.aws.amazon.com/sdk-for-go/api/service/sns/#SetPlatformApplicationAttributesInput 

So I don't think it's needed 🤔 
just those 2 new attributes that I mentioned are needed

**Comment by mdrobny** [comment]
I created a Pull Request adding support for APNS with token-based authentication, hopefully it will be good enough to close this issue 😄

**Comment by mdrobny** [comment]
I guess we need more 👍 in the pull request to show the maintainers team it should be finally prioritized. 

I see there is a conflict in the PR currently, I will resolve it. 
And ping a maintainer maybe but I don't think it will help

**Comment by mdrobny** [comment]
- PR rebased
- conflicts solved
- maintainer pinged

[The PR](https://github.com/hashicorp/terraform-provider-aws/pull/23147) is 8th most up-voted PR now so maybe it will get prioritised finally

**Comment by mdrobny** [comment]
PR has been approved 🎉  so maybe it will be merged and released soon 🤞🏼
