### ISSUE TITLE
Incorrect documentation for aws_vpc_ipv6_cidr_block_association

### ISSUE THREAD

**Issue by johngmyers** [hashicorp/terraform-provider-aws#22014]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

AWS Provider v3.68.0

### Affected Resource(s)

aws_vpc_ipv6_cidr_block_association

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Actual Behavior

The resource documentation states:

> When a VPC is created, a primary IPv6 CIDR block for the VPC must be specified.

This is not correct. There is no such thing as a "primary" IPv6 CIDR block for a VPC and IPv6 CIDR blocks are entirely optional.

The uses of the words "additional" and "further" in the existing description are similarly inappropriate.

### Steps to Reproduce

Read the resource documentation.

### Important Factoids

N/A

### References

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_VpcIpv6CidrBlockAssociation.html
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Vpc.html

**Comment by johngmyers** [comment]
I also note that the argument `cidr_block` should instead be `ipv6_cidr_block` to correspond to the upstream API's naming.

**Comment by drewmullen** [comment]
👋  thanks for finding this! these docs were copied from the ipv4 resource version and it looks like I missed those. updating now. please lmk if you find anything else!

**Comment by johngmyers** [comment]
I also noticed the new resources weren't included in the release notes.
