### ISSUE TITLE
Add S3 notifications for EventBridge

### ISSUE THREAD

**Issue by chrisandrews7** [hashicorp/terraform-provider-aws#22013]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

S3 notifications [now support EventBridge](https://aws.amazon.com/blogs/aws/new-use-amazon-s3-event-notifications-with-amazon-eventbridge/).   
Add [S3 notification configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_notification) for [EventBridge](https://aws.amazon.com/eventbridge/).

### New or Affected Resource(s)

* [ `aws_s3_bucket_notification`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_notification)

### Potential Terraform Configuration

```hcl
resource "aws_s3_bucket_notification" "bucket_notification" {
  bucket = aws_s3_bucket.bucket.id

  bus {
    bus_arn     = aws_cloudwatch_event_bus.bus.arn
    events        = ["s3:ObjectCreated:*"]
  }
}
```

### References

* [https://aws.amazon.com/blogs/aws/new-use-amazon-s3-event-notifications-with-amazon-eventbridge/](https://aws.amazon.com/blogs/aws/new-use-amazon-s3-event-notifications-with-amazon-eventbridge/)

**Comment by wokuang** [comment]
Hi all,
I just want to use this setting, is it any workaround ?

Thanks,

**Comment by msegurag** [comment]
I enabled EventBridge on an S3 bucket using aws-cli but using `aws_s3_bucket_notification` will disable EventBridge.  My workaround, for now, is to stop using `aws_s3_bucket_notification` and use a `null_resource` instead. Like this one:
```
resource "null_resource" "bucket_notification_mybucket" {
  triggers = {
    bucket = "mybucket"
    notification-configuration=<<-EOF
{
    "LambdaFunctionConfigurations": [
        {
            "Id": "mybucket01",
            "LambdaFunctionArn": "somearn",
            "Events": [
                "s3:ObjectCreated:*"
            ],
            "Filter": {
                "Key": {
                    "FilterRules": [
                        {
                            "Name": "Suffix",
                            "Value": "foo"
                        }
                    ]
                }
            }
        }
    ],
    "EventBridgeConfiguration": {}
}
EOF

  }
  provisioner "local-exec" {
    interpreter = ["bash", "-c"]
    command = <<EOF
aws s3api put-bucket-notification-configuration --bucket ${self.triggers.bucket} --notification-configuration '${self.triggers.notification-configuration}'
EOF
  }
  provisioner "local-exec" {
    interpreter = ["bash", "-c"]
    when    = destroy
    command = <<EOF
aws s3api put-bucket-notification-configuration --bucket ${self.triggers.bucket} --notification-configuration '{ }'
EOF
  }
}
`
``
I hope this option will be available soon.

**Comment by konstankinollc** [comment]
Hi there,

Seems like pretty needed feature. Any prospect on when this can be completed/merged?

Thank you.

**Comment by lparkes** [comment]
The **Potential Terraform Configuration** provided above won't work because the API doesn't support any parameter. I have to admit I had exactly the same idea at first.
IIRC you can't choose the event bus to use because all AWS generated events always go to the default event bus.
Also, you can't choose which events to send and that doesn't matter because they don't cost you any money.
