### ISSUE TITLE
Error: Stack trace from the terraform-provider-random_v3.1.0_x5.exe plugin:Plugin did not respond

### ISSUE THREAD

**Issue by carolinadenapoli** [hashicorp/terraform-provider-aws#22019]
I encountered this bug trying to create a windows VM though terraform.
Terraform v1.0.9
on windows_amd64
How could I workaround this? 

Error: Stack trace from the terraform-provider-random_v3.1.0_x5.exe plugin:Plugin did not respond

│panic: runtime error: makeslice: len out of range

goroutine 114 [running]:
github.com/terraform-providers/terraform-provider-random/internal/provider.generateRandomBytes(0xc0004e75b0, 0xfffffffffffffffe, 0x4, 0x8, 0xa, 0xc000596530,  0x6)
  with random_password.passwd[0],
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-random/internal/provider/string.go:200 +0x4a
│github.com/terraform-providers/terraform-provider-random/internal/provider.createStringFunc.func1(0xc000800800, 0x0, 0x0, 0x0, 0xffffffffffffffff)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-random/internal/provider/string.go:176 +0x75d  on main.tf line 20, in resource "random_password" "passwd":

github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0000f4780, 0xc55538, 0xc00030e340, 0xc000800800, 0x0, 0x0, 0x0, 0x0, 0x0)
│       /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-random/vendor/github.com/hashicorp/terraform-plugin-sd k/v2/helper/schema/resource.go:278 +0x95
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000f4780, 0xc55538, 0xc00030e340, 0xc0007a4230, 0xc0002d82a0, 0x0, 0x0, 0x0, 0x0, 0x0, ...){

│       /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-random/vendor/github.com/hashicorp/terraform-plugin-sd k/v2/helper/schema/resource.go:396 +0x674

github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000ee720, 0xc55538, 0xc00030e340, 0xc00078e370, 0xc00030e340, 0xb3c500, 0xc00078c100)│
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-random/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8efT
he plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
0078c1b0, 0xc00079fba0)╵raform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000067c40, 0xc555e0, 0xc00030e340, 0xc0007a4000, 0xc000067c40, 0xc0

/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-random/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb6
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xb3c500, 0xc000067c40, 0xc555e0, 0xc00078c1b0, 0xc0000868a0, 0x0, 0xc555e0, 0xc00078c1b0, 0xc0007a2300, 0x16f)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-random/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000f2380, 0xc5caf8, 0xc000085b00, 0xc000796000, 0xc0003d2c30, 0x1033b20, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-random/vendor/google.golang.org/grpc/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0000f2380, 0xc5caf8, 0xc000085b00, 0xc000796000, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-random/vendor/google.golang.org/grpc/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0003101a0, 0xc0000f2380, 0xc5caf8, 0xc000085b00, 0xc000796000)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-random/vendor/google.golang.org/grpc/server.go:859 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-random/vendor/google.golang.org/grpc/server.go:857 +0x1fd

Error: The terraform-provider-random_v3.1.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by justinretzolk** [comment]
Hey @carolinadenapoli 👋 Thank you for taking the time to submit this issue. It looks like this is an issue with the [Terraform Random Provider](https://github.com/hashicorp/terraform-provider-random) rather than the AWS provider. 

Since that's the case, we'd recommend that you open an issue on that provider's repository (linked above).
