### ISSUE TITLE
aws_ec2_client_vpn_authorization_rule after 10m0s

### ISSUE THREAD

**Issue by wesleykirklandsg** [hashicorp/terraform-provider-aws#22023]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v3.66.0

### Affected Resource(s)
* aws_ec2_client_vpn_authorization_rule

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ec2_client_vpn_authorization_rule" "vpn_auth_rule" {
  client_vpn_endpoint_id = aws_ec2_client_vpn_endpoint.vpn.id
  #Can be 0.0.0.0/0 for full tunnel
  #0.0.0.0/0 seems to be auto created, so the parameter is required so we just add the VPC cidr. We don't need 0.0.0.0/0 anyways
  //target_network_cidr = data.aws_vpc.legacy_vpc.cidr_block
  target_network_cidr = "0.0.0.0/0"
  access_group_id = var.access_group_id
}
```

### Debug Output

│ Error: error waiting for Client VPN authorization rule "cvpn-endpoint-0e5ea1e7f01bd241b,0.0.0.0/0,Prd" to be active: timeout while waiting for state to become 'active' (last state: 'authorizing', timeout: 10m0s)
│ 
│   with aws_ec2_client_vpn_authorization_rule.vpn_auth_rule,
│   on client_vpn.tf line 78, in resource "aws_ec2_client_vpn_authorization_rule" "vpn_auth_rule":
│   78: resource "aws_ec2_client_vpn_authorization_rule" "vpn_auth_rule" {
│ 
╵

### Expected Behavior

The Terraform AWS provider shouldn't time out after 10 minutes, and should have a configurable timeout block section in the resource block

### Actual Behavior

Terraform times out after 10 minutes and doesn't save the attempt to the state file. This causes a duplicate rule to be created and Terraform time out.

### Steps to Reproduce

Use a standard default VPC in us-east-1 with 6 subnets and configure AWS Client VPN, the assosications take a long time and this rule in specific times out

### Important Factoids

AWS Default VPC - Not by choice
Currently due to the timeout, the only way to correct it is to let the timeout occur. Manually delete the specific resource, wait a few minutes for the delete to go through. And then run terraform again and it doesn't see it in it's state file.

### References

* Similar to https://github.com/hashicorp/terraform-provider-aws/issues/14156

**Comment by ewbankkit** [comment]
@wesleykirklandsg Thanks for raising this issue.
It has already been noticed in #16890. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
