### ISSUE TITLE
Error: failure configuring LB attributes: ValidationError: Load balancer attribute key 'waf.fail_open.enabled' is not recognized - in v3.67 & v3.68

### ISSUE THREAD

**Issue by wwwizards** [hashicorp/terraform-provider-aws#22037]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.68.0

### Affected Resource(s)

aws_alb

### Terraform Configuration Files

```
#----------------------------------------------------------------------
# Primary ALB - AWS Application Load Balancer
#----------------------------------------------------------------------
resource "aws_alb" "alb01" {
  name = "alb01-${var.indicated_workspace}-lb"
  internal        = true
  subnets         = [data.aws_subnet.selected[1].id, data.aws_subnet.selected[0].id]
  security_groups = [aws_security_group.alb01_sg.id]
  tags            = module.label.tags

  lifecycle {
    ignore_changes = [
      tags,
      tags_all,
      access_logs
    ]
  }
}
```

### Expected Behavior

ALB is created

### Actual Behavior

```
╷
│ Error: failure configuring LB attributes: ValidationError: Load balancer attribute key 'waf.fail_open.enabled' is not recognized
│       status code: 400, request id: e671a925-2172-47e0-8bae-10a10a37a75a
│
│   with aws_alb.alb01,
│   on alb01.tf line 4, in resource "aws_alb" "alb01":
│    4: resource "aws_alb" "alb01" {
│
╵
```

### Steps to Reproduce

1. `terraform apply`

### References

service/elbv2/load_balancer: Support WAF fail open #16393
https://github.com/hashicorp/terraform-provider-aws/pull/16393

### Workaround

rolling back to aws provider v3.66.0 fixes the issue 

Joe Negron ~ NYC

**Comment by mrobinet** [comment]
I'm also running into this, specifically in the cn-north-1 region. I'm guessing China does not support this feature yet.

**Comment by wwwizards** [comment]
@mrobinet - I didn't imagine that this could be a regional issue - but I guess that's always  a possibility... For me, my target is us-gov-east-1 - plus my goal is just a plain-vanilla ALB and does not even require that feature. The error is by default. 

@anGie44 - do you know if the test coverage for the pull request on this feature spanned multiple regions/zones???

If not, maybe I can try it in other regions in commercial cloud over the weekend...

**Comment by anGie44** [comment]
Hi @wwwizards @mrobinet thanks for following up on this issue! the tests themselves don't hardcode any regions but on our end they are run in `us-west-2` and `us-gov-west-1` regions. It's very possible there are unsupported regions.. let me see how the test added in #16393 behaves in at least `us-gov-east-1`

**Comment by wwwizards** [comment]
Thank you @anGie44 - I appreciate your time and knowledge. 

Upon further investigation, I have noticed that the ALB actually does get created. It's just that none of the additional configuration(s) that utilize(s) that ALB or more specifically its ID or ARN seem to get applied.  Looking through the console I can see the ALB, but not the listeners, or their rules, SGs, and/or any other related attributes. It is almost as if the failure message and the subsequent errors are a bit misleading. 

looking at the state that is created I see this:

```
$> terraform show | grep alb01

# aws_alb.alb01: (tainted)
resource "aws_alb" "alb01" {
    id                         = "arn:aws-us-gov:elasticloadbalancing:us-gov-east-1:107xxxxxxxx95:loadbalancer/app/alb01-devops-lb/c9c0de0b9bb9ec8e"
    name                       = "alb01-devops-lb"

# aws_cloudwatch_log_group.alb01:
resource "aws_cloudwatch_log_group" "alb01" {
    arn               = "arn:aws-us-gov:logs:us-gov-east-1:10xxxxxxxx95:log-group:alb01"
    id                = "alb01"
    name              = "alb01"

# aws_lb_target_group.alb01_test_tg:
resource "aws_lb_target_group" "alb01_test_tg" {
    arn                                = "arn:aws-us-gov:elasticloadbalancing:us-gov-east-1:10xxxxxxxx95:targetgroup/alb01-devops-lb-tg/181a60a5d767acc0"
    arn_suffix                         = "targetgroup/alb01-devops-lb-tg/181a60a5d767acc0"
    id                                 = "arn:aws-us-gov:elasticloadbalancing:us-gov-east-1:10xxxxxxxx95:targetgroup/alb01-devops-lb-tg/181a60a5d767acc0"
    name                               = "alb01-devops-lb-tg"

# aws_security_group.alb01_sg:
resource "aws_security_group" "alb01_sg" {
    name                   = "comm-qa-mbdt-devops-alb01_alb-sg"
        "Name"                = "alb01-alb-sg-devops"

# aws_security_group_rule.alb01_egress:
resource "aws_security_group_rule" "alb01_egress" {

# aws_security_group_rule.alb01_sg_rule_443:
resource "aws_security_group_rule" "alb01_sg_rule_443" {

# aws_security_group_rule.alb01_sg_rule_80:
resource "aws_security_group_rule" "alb01_sg_rule_80" {
```    
The ALB and other objects are there - but the relationships between the subsequently created objects seem to be missing.

I am not sure if that is valid, but I hope it helps...

Joe Negron ~ NYC

**Comment by bigbluechicken** [comment]
Also, the same issue in both us-gov-east-1 and us-gov-west-1
