### ISSUE TITLE
Support for `routing.http.xff_client_port.enabled` and `routing.http.x_amzn_tls_version_and_cipher_suite.enabled` in ALB

### ISSUE THREAD

**Issue by osiegmar** [hashicorp/terraform-provider-aws#22049]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As described in the [Load balancer attributes](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#load-balancer-attributes) section of ALB documentation there are currently two boolean attributes that are not supported.

#### `routing.http.x_amzn_tls_version_and_cipher_suite.enabled`

> Indicates whether the two headers (x-amzn-tls-version and x-amzn-tls-cipher-suite), which contain information about the negotiated TLS version and cipher suite, are added to the client request before sending it to the target. The x-amzn-tls-version header has information about the TLS protocol version negotiated with the client, and the x-amzn-tls-cipher-suite header has information about the cipher suite negotiated with the client. Both headers are in OpenSSL format. The possible values for the attribute are true and false. The default is false.

#### `routing.http.xff_client_port.enabled`

> Indicates whether the X-Forwarded-For header should preserve the source port that the client used to connect to the load balancer. The possible values are true and false. The default is false.

### New or Affected Resource(s)

* aws_lb

### Potential Terraform Configuration

```hcl
resource "aws_lb" "lb_test" {
  enable_forward_client_port = true
  enable_forward_tls_version_cipher = true
}
```

**Comment by ericrichtert** [comment]
See PR 21667, that one implements enable_forward_tls_version_cipher

I will try to extend this PR with enable_forward_client_port

**Comment by osiegmar** [comment]
Thanks for your feedback. So this ticket partially duplicates #21666 / #21667.

**Comment by ericrichtert** [comment]
Yes, for now it partially duplicates #21666 / #21667.

I'll add the forward_client_port in the near future

**Comment by ericrichtert** [comment]
I added the xff_client_port to #21667

**Comment by ericrichtert** [comment]
Waiting for the merge

**Comment by rogervinas** [comment]
Hi @ericrichtert and @osiegmar in a project we are working we need also `routing.http.xff_header_processing.mode = (Append, Preserve, Remove)` , which is related to this issue. 
How do you think we should proceed? open a new issue? Thanks!
Documentation at https://docs.aws.amazon.com/elasticloadbalancing/latest/application/x-forwarded-headers.html

**Comment by ericrichtert** [comment]
> Hi @ericrichtert and @osiegmar in a project we are working we need also `routing.http.xff_header_processing.mode = (Append, Preserve, Remove)` , which is related to this issue. How do you think we should proceed? open a new issue? Thanks! Documentation at https://docs.aws.amazon.com/elasticloadbalancing/latest/application/x-forwarded-headers.html

My PR is not picked up, so addoing this to the current PR or creating a new one doesn't make much sense unfortunately.

**Comment by nodomain** [comment]
Need also `routing.http.xff_header_processing.mode` - I was wondering that this is not supported yet ;-)
