### ISSUE TITLE
Add support for AWS MSK serverless cluster type

### ISSUE THREAD

**Issue by marcincuber** [hashicorp/terraform-provider-aws#22058]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_msk_cluster

The above resource is affected assuming we will be able to provide `cluster_type` parameter. Possible options would be `serverless` or `provisioned`.

It looks like `func (*Kafka) CreateClusterV2` will need to be used from go sdk.

### References

* https://aws.amazon.com/blogs/aws/amazon-msk-serverless-now-generally-available-no-more-capacity-planning-for-your-managed-kafka-clusters/
* https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-msk-serverless-public-preview/
* SDK: https://docs.aws.amazon.com/sdk-for-go/api/service/kafka/#Kafka.CreateClusterV2

**Comment by trevorpburke** [comment]
Hello, is there any update on this enhancement? Today [MSK Serverless became generally available](https://aws.amazon.com/blogs/aws/amazon-msk-serverless-now-generally-available-no-more-capacity-planning-for-your-managed-kafka-clusters/)

**Comment by nagendran78** [comment]
hi, any update on the above implementation?

**Comment by axw703** [comment]
I am also interested in an update.

**Comment by PavelSusloparov** [comment]
I'm looking for using MSK serverless instead of `provisioned`, however, I need IaaC support

**Comment by vishmule** [comment]
Eagerly waiting for terraform support on MSK serverless. Please update.

**Comment by ddvdozuki** [comment]
Waiting on this, it would be great to be able to swap from provisioned. 👍

**Comment by ewbankkit** [comment]
As _serverless_ cluster configuration is very different from classic, _provisioned_ cluster configuration and to match the CloudFormation [`AWS::MSK::ServerlessCluster`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-msk-serverlesscluster.html) resource type, this has been implemented as a new resource type, `aws_msk_serverless_cluster`.
