### ISSUE TITLE
Support tags for `aws_iam_service_linked_role` resource

### ISSUE THREAD

**Issue by posquit0** [hashicorp/terraform-provider-aws#22057]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please support `tags` variable to `aws_iam_service_linked_role` resource. It is available in AWS management console.

### New or Affected Resource(s)

* aws_iam_service_linked_role

### Potential Terraform Configuration

```hcl
resource "aws_iam_service_linked_role" "elasticbeanstalk" {
  aws_service_name = "elasticbeanstalk.amazonaws.com"
  tags = {
    Name = "hello"
  }
}
```

**Comment by ewbankkit** [comment]
Related: #17594.
