### ISSUE TITLE
Support Amazon S3 Object Ownership（Bucket owner enforced）

### ISSUE THREAD

**Issue by yusuke-takikawa-s** [hashicorp/terraform-provider-aws#22053]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I want to set the following new features (Amazon S3 Object Ownership) with aws provider.
https://aws.amazon.com/jp/about-aws/whats-new/2021/11/amazon-s3-object-ownership-simplify-access-management-data-s3/

### New or Affected Resource(s)

* aws_s3_bucket_ownership_controls

### Potential Terraform Configuration

```
resource "aws_s3_bucket" "example" {
  bucket = "example"
}

resource "aws_s3_bucket_ownership_controls" "example" {
  bucket = aws_s3_bucket.example.id

  rule {
    object_ownership = "BucketOwnerEnforced"
  }
}
```

### References

https://aws.amazon.com/jp/about-aws/whats-new/2021/11/amazon-s3-object-ownership-simplify-access-management-data-s3/

**Comment by ewbankkit** [comment]
@yusuke-takikawa-s Thanks for raising this issue.
It has already been noticed in #21980. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
