### ISSUE TITLE
Support for ReportBatchItemFailures for SQS Event Source Mapping to Lambda

### ISSUE THREAD

**Issue by sohaibsi** [hashicorp/terraform-provider-aws#22068]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

SQS triggers now support ReportBatchItemFailures for partial failures in batch processing. This feature eliminates a lot of pain points of batch processing and would be awesome if TF could support it

### New or Affected Resource(s)

* aws_lambda_event_source_mapping

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References
[Developer guide](https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html#services-sqs-batchfailurereporting)
[Blog post](https://aws.amazon.com/about-aws/whats-new/2021/11/aws-lambda-partial-batch-response-sqs-event-source/)

* #0000

**Comment by mirsilstan** [comment]
The other AWS Terraform provider based on the Cloud Control APi seems to support it already
https://github.com/hashicorp/terraform-provider-awscc/blob/main/docs/resources/lambda_event_source_mapping.md

**Comment by Cristigeo** [comment]
I'm a bit confused as to why there's an open request to support this, when this feature seems to be working already for some time. I'm deploying a Lambda event-source mapping resource (SQS-based) using this definition:

```
resource "aws_lambda_event_source_mapping" "sqs_trigger" {
  event_source_arn                   = var.trigger_queue_arn
  function_name                      = aws_lambda_function.this.arn
  batch_size                         = var.trigger_queue_batch_size
  maximum_batching_window_in_seconds = var.trigger_queue_max_batch_window
  enabled                            = var.trigger_queue_enabled
  function_response_types            = ["ReportBatchItemFailures"]
}
```
with Terraform 1.1 and AWS provider v3.68.0. The deployment succeeds and the AWS portal confirms (on the trigger details) that indeed `functionResponseTypes: ReportBatchItemFailures`. Furthermore, partial failure responses generated by the lambda are treated as expected.

Am I missing something?

**Comment by mattthaber** [comment]
> I'm a bit confused as to why there's an open request to support this, when this feature seems to be working already for some time. I'm deploying a Lambda event-source mapping resource (SQS-based) using this definition:
> 
> ```
> resource "aws_lambda_event_source_mapping" "sqs_trigger" {
>   event_source_arn                   = var.trigger_queue_arn
>   function_name                      = aws_lambda_function.this.arn
>   batch_size                         = var.trigger_queue_batch_size
>   maximum_batching_window_in_seconds = var.trigger_queue_max_batch_window
>   enabled                            = var.trigger_queue_enabled
>   function_response_types            = ["ReportBatchItemFailures"]
> }
> ```
> 
> with Terraform 1.1 and AWS provider v3.68.0. The deployment succeeds and the AWS portal confirms (on the trigger details) that indeed `functionResponseTypes: ReportBatchItemFailures`. Furthermore, partial failure responses generated by the lambda are treated as expected.
> 
> Am I missing something?

Terraform docs still claim "Only available for stream sources (DynamoDB and Kinesis)" and not SQS so that might be why. That doc page is how i ended up here thinking i can't do what i wanted. But will try what you have posted and see if it works for me as well. 

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping#function_response_types

**Comment by BilalIshtiaque** [comment]
Just tested and confirmed, Terraform now supports this as well. The documentation needs to be updated to include SQS as well.

Amazon docs related to supporting `ReportBatchItemFailures` for SQS:
https://aws.amazon.com/about-aws/whats-new/2021/11/aws-lambda-partial-batch-response-sqs-event-source/
https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html#services-sqs-batchfailurereporting
