### ISSUE TITLE
Cloudformation Type Configuration

### ISSUE THREAD

**Issue by webratz** [hashicorp/terraform-provider-aws#22061]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It should be possible to set the configuration of a Cloudformation type. This could be either by extending `aws_cloudformation_type` (see [docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudformation_type) or creating a new resource.
The underlying AWS API is documented at https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_SetTypeConfiguration.html

### New or Affected Resource(s)

* aws_cloudformation_type
* aws_cloudformation_type_config (potential new)

### Potential Terraform Configuration

```hcl
# this already exists, just for reference
resource "aws_cloudformation_type" "datadogdashboard" {
  schema_handler_package = "s3://datadog-cloudformation-resources/datadog-dashboards-dashboard/datadog-dashboards-dashboard-2.0.2.zip"
  type                   = "RESOURCE"
  type_name              = "Datadog::Dashboards::Dashboard"

  lifecycle {
    create_before_destroy = true
  }
}

# the new configuration
resource "aws_cloudformation_type_config" "datadogdashboardconfig" {
  type_arn = aws_cloudformation_type.datadogdashboard.arn
  configuration = jsonencode({
    DatadogCredentials = {
      "ApiURL"         = "https://api.datadoghq.eu",
      "ApiKey"         = "{{resolve:secretsmanager:MySecret:SecretString:SecretAPIKey}}",
      "ApplicationKey" = "{{resolve:secretsmanager:MySecret:SecretString:SecretAppKey}}"
    }
  })
}
```

### References

* AWS API Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_SetTypeConfiguration.html
* Example: activating datadog cloudformation resources. All steps in https://github.com/DataDog/datadog-cloudformation-resources#aws-command-line-interface would then be able to be done within terraform

Example of related aws cli call 
```shell
aws cloudformation set-type-configuration \
    --type-name "${DATADOG_RESOURCE_NAME}" \
    --type RESOURCE \
    --configuration '{"DatadogCredentials": {"ApiURL": "https://api.datadoghq.eu", "ApiKey": "{{resolve:secretsmanager:Datadog:SecretString:APIKey}}", "ApplicationKey": "{{resolve:secretsmanager:Datadog:SecretString:AppKey}}"}}'
```

**Comment by DrFaust92** [comment]
Random semi related comment. While the above might be useful in general. For the datadog example you can use https://registry.terraform.io/providers/DataDog/datadog/latest/docs

**Comment by webratz** [comment]
Thats right, but the use case here is to make it available via cloudformation for some other use case
