### ISSUE TITLE
Enhancement request for "aws_ram_resource_association" to support list of resource ARNs to associate

### ISSUE THREAD

**Issue by desweil** [hashicorp/terraform-provider-aws#22063]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The "aws_ram_resource_association" currently only supports a single resource ARN to associate with a RAM share. That means if you want to associate hundreds of resources to the same share you have to go with "for_each" which creates hundreds of terraform resources. Each refresh takes a long time because you have to refresh hundreds or thousands of these resources. The AWS cli actually does support a list(!) of resource ARNs. I would like to see the same in terraform.

### New or Affected Resource(s)

aws_ram_resource_association

### Potential Terraform Configuration

```hcl
resource "aws_ram_resource_association" "example" {
  resource_arns       = local.listofresourcearns
  resource_share_arn = aws_ram_resource_share.example_share.arn
}
```

**Comment by bondnotanymore** [comment]
👍🏻👍🏻
