### ISSUE TITLE
metric alarm resource does not have support for trimmed mean statistic

### ISSUE THREAD

**Issue by blackknight467** [hashicorp/terraform-provider-aws#22078]
Trying to create a metric alarm with Trimmed Mean (TM) results in the following error

```
│ Error: invalid value for extended_statistic (must specify a value between p0.0 and p100)
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.68.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.7.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
```

### Affected Resource(s)

* aws_cloudwatch_metric_alarm

### Terraform Configuration Files

```
resource "aws_cloudwatch_metric_alarm" "example" {
  ...
  extended_statistic  = "tm99"
  ...
}
```
### Debug Output

This fails the validation step

### Expected Behavior

A metric alarm should be created with trimmed mean

### Actual Behavior

Validation fails

### Steps to Reproduce

Try to create a trimmed mean metric alarm

1. `terraform apply`

### Important Factoids

N/A

### References

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Statistics-definitions.html

**Comment by ewbankkit** [comment]
The _tm99_ and other statistics are show in the Console's drop-down:

<img width="356" alt="Screen Shot 2021-12-07 at 12 06 34 PM" src="https://user-images.githubusercontent.com/2404182/145074118-f52b24cb-9373-4fd2-b91b-ab193757b425.png">

**Comment by xoob** [comment]
It looks like this is caused by the client-side validation at https://github.com/hashicorp/terraform-provider-aws/blob/01132fcc5be7f74575dd5032ed8f233de923f2a6/internal/service/cloudwatch/metric_alarm.go#L238. Would it be feasible to remove the validation and let the AWS API decide what is an acceptable value?

**Comment by EpicWink** [comment]
Please also support the expandable statistics ([docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Statistics-definitions.html#Statistics-syntax)), including one- and two-value arguments, and both percentage and absolute values

**Comment by EpicWink** [comment]
Related: #13622
