### ISSUE TITLE
aws NeptunDB cluster_identifier_endpoint argument wrongly defined in documentation, its actually cluster_endpoint_identifier but in documentation its says cluster_identifier_endpoint

### ISSUE THREAD

**Issue by hemalgadhiya** [hashicorp/terraform-provider-aws#22094]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws__neptune_cluster_endpoint

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by AdamJCavanaugh** [comment]
I see the difference on [neptune_cluster_endpoint](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/neptune_cluster_endpoint) that the example uses `cluster_endpoint_identifier` and the argument reference uses `cluster_identifier_endpoint`. The code and tests clearly use only `cluster_endpoint_identifier`. `cluster_identifier_endpoint` appears at only this 1 point in the documentation. I'll fix it.
