### ISSUE TITLE
Add support for Redshift-managed VPC endpoints

### ISSUE THREAD

**Issue by beyondbill** [hashicorp/terraform-provider-aws#22113]
Would like to see Terraform support for [Redshift-managed VPC endpoints](https://docs.aws.amazon.com/redshift/latest/mgmt/managing-cluster-cross-vpc.html). There are already [AWS APIs](https://docs.aws.amazon.com/redshift/latest/mgmt/managing-cluster-cross-vpc.html#managing-cluster-cross-vpc-api) available (and in [Go SDK](https://github.com/aws/aws-sdk-go/blob/main/service/redshift/api.go) too) for setting up a Redshift-managed VPC endpoint.

**Comment by farshadniayeshpour** [comment]
Is there an update on this?

**Comment by ccom-dev-platform** [comment]
Would love this feature as well!

**Comment by lambbuster** [comment]
Any update on this?

**Comment by ramziyassine** [comment]
+1 for this!
