### ISSUE TITLE
AWS Config Remediation Exception

### ISSUE THREAD

**Issue by chickenmimolette** [hashicorp/terraform-provider-aws#22112]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I cannot configure config remediation exception with current available resources. I would like to be able to prevent automatic remediation for some managed instances.
Create associated data source would be great ! Also data source for referencing SSM/Config resource in remediation exception.

### New or Affected Resource(s)

* Affected: aws_config_remediation_configuration
* OR
* New: aws_config_remediation_exception

### Potential Terraform Configuration

```hcl
resource "aws_config_remediation_configuration" "remediation" {
    config_rule_name = aws_config_config_rule.rule.name
    resource_type    = "AWS::SSM::ManagedInstanceInventory"
    target_type      = "SSM_DOCUMENT"
    # etc.

    parameter {
        name         = "InstanceId"
        resource_value = "RESOURCE_ID"
    }
    parameter {
        name         = "installationType"
        static_value = "Uninstall and reinstall"
    }
    # etc.

    automatic      = true

    # the interresting part:
    exception {
        resource_id = ["mi-0000000000","i-00000001"]
        expiration = "never"
        message = "these resource musn't install software"
    }

}
```
OR

```hcl
resource "aws_config_remediation_exception" "exception" {
    resource_id = "mi-0000000000"
    resource_type = "AWS::SSM::ManagedInstanceInventory"
    config_rule = data.aws_config_config_rule.rule.name
    message = "this resource must not install package because..."
    expiration = "2021-12-08T16:00"

    depends_on = [
        aws_config_remediation_configuration.remediation
    ]
}
```

### References

* #10028
* https://docs.aws.amazon.com/config/latest/APIReference/API_PutRemediationExceptions.html

### Requires

* AWS Terraform provider version >= 3.67

**Comment by megashby** [comment]
Hi! Are there any updates on prioritizing this?
