### ISSUE TITLE
Missing MWAA option (scheduler_count)

### ISSUE THREAD

**Issue by kilianr** [hashicorp/terraform-provider-aws#22129]
Since MWAA 2.0, there is an option from AWS side to configure the number of schedulers ([ref userguide](https://docs.aws.amazon.com/mwaa/latest/userguide/environment-class.html#environment-class-schedulers), [ref CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mwaa-environment.html#cfn-mwaa-environment-schedulers))

This was also mentioned in #19816, but not implemented.

Would be great to have this in terraform as well.

**Comment by ewbankkit** [comment]
@kilianr Thanks for raising this issue.
It has already been noticed in #20185. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
