### ISSUE TITLE
Cloud Control API resource does not use default tags from provider

### ISSUE THREAD

**Issue by princespaghetti** [hashicorp/terraform-provider-aws#22132]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform version: 1.0.11
AWS provider version: v3.68.0
### Affected Resource(s)

* aws_cloudcontrolapi_resource

### Terraform Configuration Files

```hcl
provider "aws" {
  region                  = "us-east-1"
  shared_credentials_file = "~/.aws/creds"

  default_tags {
    tags = {
      Environment = "Dev"
      Service     = "Example"
    }
  }
}

resource "aws_cloudcontrolapi_resource" "example" {
  type_name = "AWS::EC2::VPC"

  desired_state = jsonencode({
      "CidrBlock" : "10.0.0.0/16",
      "EnableDnsSupport" : true,
      "EnableDnsHostnames" : true,
      "Tags" : [
         {"Key" : "stack", "Value" : "dev"}
      ]
  })
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The resource should respect and use the default tags from the provider

### Actual Behavior

The resource only uses tags defined within the resource

### Steps to Reproduce

1. Run terraform plan and see lack of tags_all field on resource

### Important Factoids

N/A

### References

N/A

**Comment by ewbankkit** [comment]
@princespaghetti Thanks for raising this issue.
You are correct that `default_tags` are not propagated through the Cloud Control API.
I have marked this issue as an _enhancement_ as we would need support from the Cloud Control API to know whether an underlying CloudFormation resource type is itself tagable and how to inject the tag keys and values.

**Comment by princespaghetti** [comment]
Thanks @ewbankkit! Looks like the schema value that comes back if none is provided might be another place to start. A generated plan file (and running the show command), shows the schema being part of the resource and has references to the support attributes
