### ISSUE TITLE
Deployments fail when ELB source security group name is not unique

### ISSUE THREAD

**Issue by aqiu95** [hashicorp/terraform-provider-aws#22138]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.13 and AWS provider v3.57.0

### Affected Resource(s)

* aws_elb

### Terraform Configuration Files

```hcl
resource "aws_elb" "bar" {
  name = "foobar-terraform-elb"
  subnets = ["subnet-xxx", "subnet-yyy"]
  security_groups = ["sg-zzz"]

  # some listener here
  # along with the rest of some ELB config
}
```

### Debug Output

```
Error: Error looking up ELB Security Group ID: too many results: wanted 1, got 3 on .terraform/modules/stack.elb/main.tf line 1, in resource "aws_elb" "elb":1: resource "aws_elb" "elb" {
```

### Expected Behavior

Ideally, Terraform and the provider should pick the security group with the owner (account ID) that is the same as the current account.

### Actual Behavior

Terraform and the provider fail to deploy an ELB.

### Steps to Reproduce

1. Create an environment where there are multiple security groups with the same name and VPC (but different owners) - I didn't set this part up so I'm not clear on the finer details but I was told this happens when you have shared subnets across accounts and deploy the same security group to both accounts - the security group from one account will show up in the other, thus creating duplicated security groups with the same name and VPC, but different owners (AWS account IDs).
2. Attempt to provision an ELB.

### Important Factoids

So I believe this all stems from the "source_security_group" and "source_security_group_id" fields in the state file. I believe the AWS provider [tries to lookup the ID](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/elb/load_balancer.go#L427) of the source security group of the ELB since the AWS SDK only returns the name of the source security group. Since this lookup is done via name + VPC, this returns too many results [which returns an error](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ec2/find.go#L601).

This actually worked up until v3.49.0 of the provider because even though it was [also looking up](https://github.com/hashicorp/terraform-provider-aws/blob/v3.49.0/aws/resource_aws_elb.go#L411) the security group via name and VPC, there was logic to just [return the first result](https://github.com/hashicorp/terraform-provider-aws/blob/v3.49.0/aws/resource_aws_elb.go#L875). It seems the enhanced error checking in v3.50.0 (specifically PR #18433) broke this. By "working", I mean this allowed ELBs to be provisioned but is not necessarily correct, since grabbing the first results does not ensure it is grabbing the correct security group ID. However, I'm unaware of anything this breaks (besides the state file potentially having the wrong security group ID).

Ideally, I think adding a filter for owner of the security group is probably the best solution.

**Comment by mtdoyle** [comment]
I have fixed this on a local branch by including the owner-id filter when performing the security group lookup. I am in the early stages of putting together a PR, but am running into difficulties figuring out how to write a test to reflect this scenario since I'd somehow need the test two use two separate accounts and I'm not sure how to do that. 

My fork: https://github.com/mtdoyle/terraform-provider-aws/tree/add-ownerid-filter-to-subnet-search
