### ISSUE TITLE
Add support for S3 Lifecycle rule with Object's size

### ISSUE THREAD

**Issue by cohandv** [hashicorp/terraform-provider-aws#22133]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It seems the provider does not currently support transitioning objects by its size as the AWS documentation states.

### New or Affected Resource(s)

aws_s3_bucket

### Potential Terraform Configuration

```hcl
resource "aws_s3_bucket" "logging" {
  bucket = var.override_logging_bucket_name != null ? var.override_logging_bucket_name : "${var.prefix_bucket_name}-logging-${var.terrain_name}"

  grant {
    id          = data.aws_cloudfront_log_delivery_canonical_user_id.awslogsdelivery.id
    type        = "CanonicalUser"
    permissions = ["FULL_CONTROL"]
  }

  lifecycle_rule {
    id      = "default"
    enabled = true
    object_size {
       greater_than = 500
       less_than = 1024
    }
  }
}
```

### References

https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-configuration-examples.html#lc-size-rules

**Comment by pda** [comment]
> Potential Terraform Configuration
> ```
> object_size {
>   greater_than = 500
>   less_than = 1024
> }
> ```

`greater_than` matches the AWS API calling the rule `ObjectSizeGreaterThan`, however the AWS console calls it “Minimum object size” which implies “greater than or equal to”. I'm pretty sure the API is correct, in which case I agree with `greater_than` for Terraform.

And, I've just run an S3 Inventory Athena query against an existing bucket with object size filtering, and verified that it is indeed behaving as `>` not `>=`. Objects with size equal to `ObjectSizeGreaterThan` are not matching the filter.

So… carry on :)

**Comment by pda** [comment]
This issue actually addresses the same thing as the 9-day-earlier #21953, which proposes:

```
    filter {
      object_size_greater_than = 128000
    }
```

That other issue already has a bit more discussion, so I would suggest we close this as a duplicate.

**Comment by cohandv** [comment]
Sure, makes sense, thanks for replying
