### ISSUE TITLE
FEATURE REQUEST: Consistent naming in buffering properties on aws_kinesis_firehose_delivery_stream

### ISSUE THREAD

**Issue by siggimoo** [hashicorp/terraform-provider-aws#22146]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The buffering properties within the `aws_kinesis_firehose_delivery_stream` resource are named inconsistently across S3, ElasticSearch, and HTTP destinations. They presently are as follows:
* `elasticsearch_configuration.buffering_interval`
* `elasticsearch_configuration.buffering_size`
* `extended_s3_configuration.buffer_interval`
* `extended_s3_configuration.buffer_size`
* `http_endpoint_configuration.buffering_interval`
* `http_endpoint_configuration.buffering_size`

Because these serve the exact same functions in all three blocks (and indeed are named consistently in the [Firehose API](https://docs.aws.amazon.com/firehose/latest/APIReference/API_CreateDeliveryStream.html)), developers can run into validation errors if they aren't paying attention and just copy fields from one block to another.

I recommend changing the `extended_s3_configuration` block to match the other two. The deprecated `s3_configuration` block can remain as is.

### New or Affected Resource(s)

* `aws_kinesis_firehose_delivery_stream`

**Comment by anGie44** [comment]
Hi @siggimoo,  just updating here that the renaming will be part of the **v4.0** release, such that the old argument names will be deprecated (still configurable) and the new argument names will be added. We'll leave the actual removal of the old naming conventions to **v5.0**.
