### ISSUE TITLE
resource/aws_db_instance: DB Instances can be renamed, this should be supported in Terraform

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#22145]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the AWS API, the `DBIdentifier` parameter can be changed by an update. In the AWS Provider, `identifier` is `ForceNew`. The provider should support changing `identifier`.

Note that this may cause other fields to need to be `Computed`. For example, `endpoint` is based on `identifier`

### Affected Resource

* aws_db_instance

**Comment by vicyap** [comment]
What should happen if the `identifier_prefix` is updated? Should this create a new resource or update the current resource with the new value?

**Comment by Kdecherf** [comment]
I think this issue can be closed as duplicate of #507

**Comment by ewbankkit** [comment]
Also #26690.
