### ISSUE TITLE
Network Firewall: please integrate the new Managed Rules Groups

### ISSUE THREAD

**Issue by LuigiClemente-Awin** [hashicorp/terraform-provider-aws#22154]
AWS released recently a new feature for the Network Firewall: Managed Rules Group

https://aws.amazon.com/about-aws/whats-new/2021/12/aws-network-firewall-aws-managed-rules/

It would be great if we could manage this in Terraform instead of just via console.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS released recently a new feature for the Network Firewall: Managed Rules.

`AWS Network Firewall features a flexible rules engine enabling you to define firewall rules that give you fine-grained control over network traffic. Starting today, you can enable managed domain list rules to block HTTP/HTTPS traffic to domains identified as low-reputation or that are known or suspected to be associated with malware or botnets. You can select one or more rule groups to use in your AWS Network Firewall policies. For stateful rules, you can choose to block all requests that match managed domain list rules or use the alert action to see which requests match the rules. Each set of managed rule groups counts as a single rule group toward the maximum number of stateful rule groups per firewall policy.` 

https://aws.amazon.com/about-aws/whats-new/2021/12/aws-network-firewall-aws-managed-rules/

These rules can be added via Console or API but not using Terraform, currently.

### New or Affected Resource(s)

I do not know if we can simply update the aws_networkfirewall_firewall_policy resource or add new resources/data sources to be able to add a managed rule group.
I couldn't find the ARN of these rules or the exact API call to manage them.

### References

https://docs.aws.amazon.com/network-firewall/latest/developerguide/nwfw-managed-rule-groups.html

Thanks,

Luigi

**Comment by justinretzolk** [comment]
Hey @LuigiClemente-Awin 👋 Thank you for taking the time to raise this. So that we and the community have all of the necessary information in order to prioritize this, can you update the issue description with the rest of the information found in the [feature request template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Feature_Request.md)?

**Comment by midestefanis** [comment]
any news about this? i'm having the same issue.

**Comment by nicolas-porta** [comment]
any news on this ? i'm really blocked by it

**Comment by lundbird** [comment]
Per the [FAQ](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/faq.md#how-do-you-decide-what-gets-merged-for-each-release). Please upvote the attached [PR](https://github.com/hashicorp/terraform-provider-aws/pull/22355) to get this prioritized for release.
