### ISSUE TITLE
Links in the release notes point to 404 pages

### ISSUE THREAD

**Issue by wjam** [hashicorp/terraform-provider-aws#22152]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

N/A

### Affected Resource(s)

N/A

### Terraform Configuration Files

N/A

### Expected Behavior

Links in the release notes for each feature, enhancement, etc should point to the relevant pull request.

### Actual Behavior

Clicking on the link goes to the GitHub 404 page, as the URL is https://github.com/hashicorp/terraform-provider-aws/issues/0000 (note the 'issues' segment rather than 'pull')

### Steps to Reproduce

Click on one of the links in a release note

**Comment by ewbankkit** [comment]
@wjam Thanks for raising this issue.
Previously  https://github.com/hashicorp/terraform-provider-aws/issues/0000 would redirect to  https://github.com/hashicorp/terraform-provider-aws/pulls/0000 if _0000_ is a PR rather than an Issue.
Something must have changed...

**Comment by ewbankkit** [comment]
For me I am seeing differences in behavior in Chrome between "normal" and Incognito modes.
Redirects are fine in Incognito but fail in Normal.

**Comment by ewbankkit** [comment]
https://github.com/github/feedback/discussions/8623

**Comment by zhelding** [comment]
GitHub has rolled back this change for now: https://github.com/github/feedback/discussions/8623#discussioncomment-1800510.

CHANGELOG links are now redirecting as expected; closing issue!
