### ISSUE TITLE
 aws_cloudwatch_event_connection failing with UnknownOperationException (govcloud) 

### ISSUE THREAD

**Issue by justinhauer** [hashicorp/terraform-provider-aws#22156]
### Community Note

https://github.com/hashicorp/terraform-provider-aws/pull/21416

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform core version: 1.0.4
AWS Provider version: 3.68.0

### Affected Resource(s)

* aws_cloudwatch_event_connection

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
    required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.68.0"
    }    
    template = {
      source = "hashicorp/template"
      version = "2.2.0"
    }
    tls = {
      source = "hashicorp/tls"
    }
  }

provider "aws" {
  region = "us-gov-west-1"
}

resource "aws_cloudwatch_event_connection" "test" {
  name               = "test-connection"
  description        = "Connection to endpoint"
  authorization_type = "BASIC"

  auth_parameters {
    basic {
      username = "username"
      password = "password"
    }
  }
}
```

### Debug Output
```
Error: error creating EventBridge connection (test-connection): UnknownOperationException: Operation is disabled in this region.
190	status code: 400, request id: XXXXXXX
191  on ../../terraform/main.tf line 31, in resource "aws_cloudwatch_event_connection" "test":
192  31: resource "aws_cloudwatch_event_connection" "test" {
193}
```
### Panic Output

N/A
### Expected Behavior

Resource Creates
### Actual Behavior

Resource doesn't create, appears that issue #21415 and #21416 to Skip CloudWatchEvents sweepers failing with UnknownOperationException (govcloud), did not actually resolve the issue.

### Steps to Reproduce

1. Run `terraform init`, `terraform plan`, and`terraform apply` on the resource above in region us-gov-west-1

### Important Factoids

Running a recent version of the Terraform version, 1.0.4 and latest aws provider 3.68.0. It appears that release 3.64.0 did not resolve this issue.

### References

* https://github.com/hashicorp/terraform-provider-aws/pull/21416
* https://github.com/hashicorp/terraform-provider-aws/issues/21415

**Comment by justinhauer** [comment]
@anGie44 I have opened this issue and am tagging you as you closed the last story out.

**Comment by anGie44** [comment]
Hi @justinhauer , thank you for raising the new issue! Just for context of the issue you linked back to (#21416), that was meant to address the `UnknownOperationException` during resource deletion as the sweepers are used for deleting resources in our test accounts, though the error received on create in gov cloud makes a lot of sense if delete isn't working as well.

**Comment by justinhauer** [comment]
upon further inspection from comparing a commercial account to a gov cloud account, there is a service limitation on api connection resources. This is available in commercial but not gov cloud. This being said, this issue can probably be closed. When the feature becomes available in govcloud, hopefully it can quickly be added to the AWS or AWSCC terraform provider. @anGie44 Thanks for looking at this quickly.

**Comment by anGie44** [comment]
No problem @justinhauer ! If and when gov cloud supports doe become available, no further action should be needed for the resource to just work but do reach out if something comes up 👍
