### ISSUE TITLE
imagebuilder: specify "systems_manager_agent/uninstall_after_build" parameter in aws_imagebuilder_image_recipe

### ISSUE THREAD

**Issue by Paladin-Dranser** [hashicorp/terraform-provider-aws#22159]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**aws_imagebuilder_image_recipe** resource should provide the possibility to set _additionalInstanceConfiguration_ section (AWS Documentation: [AWS API request](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_CreateImageRecipe.html#imagebuilder-CreateImageRecipe-request-additionalInstanceConfiguration) and [Data Type](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_AdditionalInstanceConfiguration.html)).

### New or Affected Resource(s)

* aws_imagebuilder_image_recipe

### Potential Terraform Configuration

```hcl
resource "aws_imagebuilder_image_recipe" "example" {
    systems_manager_agent {
      uninstall_after_build = false
    }

  ...
}
```

**Comment by justinretzolk** [comment]
Hey @Paladin-Dranser 👋 Thank you for taking the time to raise this! So that we and the community have all the necessary information in order to investigate and prioritize this, can you update the issue description with the rest of the information found in the [bug template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?

**Comment by Paladin-Dranser** [comment]
> Hey @Paladin-Dranser wave Thank you for taking the time to raise this! So that we and the community have all the necessary information in order to investigate and prioritize this, can you update the issue description with the rest of the information found in the [bug template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?

Hey @justinretzolk, I updated description using the feature request. As I understood it is a feature if a new parameter/resource should be added. Please let me know if I'm wrong.

**Comment by justinretzolk** [comment]
Hey @Paladin-Dranser 👋 Thank you for doing that! And apologies for the incorrect link there; you're absolutely correct that this would be a feature request and not a bug 😅

**Comment by kamilturek** [comment]
Hey @Paladin-Dranser, the user data can be set since v3.73.0 (https://github.com/hashicorp/terraform-provider-aws/pull/21763).

**Comment by Paladin-Dranser** [comment]
> Hey @Paladin-Dranser, the user data can be set since v3.73.0 (#21763).

Thanks for info.

Updated description of the issue in order to add _uninstall_after_build_ parameter for a SSM agent.
