### ISSUE TITLE
 Unsupported block type runtime_platform for aws_ecs_service

### ISSUE THREAD

**Issue by georgikoemdzhiev** [hashicorp/terraform-provider-aws#22153]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.69.0    
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* aws_ecs_service

### Terraform Configuration Files

```
resource "aws_ecs_service" "spr_service" {
  name                               = "${var.app_name}-spr-service"
  cluster                            = aws_ecs_cluster.cluster.id
  task_definition                    = "${aws_ecs_task_definition.spr_production_service.family}:${max(aws_ecs_task_definition.spr_production_service.revision, data.aws_ecs_task_definition.spr_production_service_td.revision)}"
  desired_count                      = 1
  deployment_minimum_healthy_percent = 100
  deployment_maximum_percent         = 200
  launch_type                        = "FARGATE"
  scheduling_strategy                = "REPLICA"
  enable_ecs_managed_tags            = true
  # force_new_deployment               = true

  runtime_platform {
    operating_system_family = "WINDOWS_SERVER_2019_CORE"
    cpu_architecture        = "X86_64"
  }
  network_configuration {
    subnets = var.application_subnets
    assign_public_ip = true
    security_groups = [
      aws_security_group.spr_production_service_sg.id,
    ]
  }
}
```

### Panic Output
N/A

### Expected Behavior

The `runtime_platform` configuration should be applied to my ECS service

### Actual Behavior

An error is thrown after I perform `terraform apply` :
```
Error: Unsupported block type
│ 
│   on ..\..\modules\ecs\main.tf line 183, in resource "aws_ecs_service" "spr_service":
│  183:   runtime_platform {
│ 
│ Blocks of type "runtime_platform" are not expected here.
╵
```

### Steps to Reproduce

1. Use `runtime_platform` configuration block in a `aws_ecs_service` resource
2. `terraform apply`

### Important Factoids

N/A

### References

* #22016

**Comment by ewbankkit** [comment]
@georgikoemdzhiev Thanks for raising this issue.
The CHANGELOG entry for #22016 is incomplete. The resource that implements the `runtime_platform` functionality is [`aws_ecs_task_definition`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition), not `aws_ecs_service`.
I'll correct the CHANGELOG.

**Comment by georgikoemdzhiev** [comment]
No problem. Thank you :)
