### ISSUE TITLE
networkfirewall/resource_policy: Disappears test failing

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#22174]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Relates #16774
Relates #16780

### Affected Test(s)

* aws_networkfirewall_resource_policy - TestAccNetworkFirewallResourcePolicy_disappears

NOTE: The other tests are passing. I don't see anything obviously wrong with it and there are other disappears tests that are working.

### Expected Behavior

* tests should be passing in commerical

### Actual Behavior

* Tests erroring with:
```
resource_policy_test.go:114: Step 1/1 error: Check failed: Check 2/2 error: error deleting resource: error deleting NetworkFirewall Resource Policy (for resource: arn:aws:network-firewall:us-west-2:123456789012:firewall-policy/tf-acc-test-1738147754193226966): InvalidResourcePolicyException: The supplied policy does not match RAM managed permissions.
    testing_new.go:70: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: error deleting NetworkFirewall Resource Policy (for resource: arn:aws:network-firewall:us-west-2:123456789012:firewall-policy/tf-acc-test-1738147754193226966): InvalidResourcePolicyException: The supplied policy does not match RAM managed permissions.
```

**Comment by anGie44** [comment]
Looks like an `eventual consistency`-ish behavior b/c if i add a retry condition on that error message
```
err := resource.RetryContext(ctx, iam.PropagationTimeout, func() *resource.RetryError {
		_, err := conn.DeleteResourcePolicyWithContext(ctx, input)
		if err != nil {
			if tfawserr.ErrMessageContains(err, networkfirewall.ErrCodeInvalidResourcePolicyException, "The supplied policy does not match RAM managed permissions") {
				return resource.RetryableError(err)
			}
			return resource.NonRetryableError(err)
		}
		return nil
	})
```
 the delete will eventually succeed 😕 if there was a way to check on the resource policy during create we could probably do the handling there but atm I don't see an API method that we can work with
