### ISSUE TITLE
Provider Fails to get token from SSO because cant parse UTC timestamp

### ISSUE THREAD

**Issue by hellupline** [hashicorp/terraform-provider-aws#22176]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v1.1.0
on linux_amd64
```

### Affected Resource(s)

* provider "aws"

### Terraform Configuration Files

```hcl
**provider "aws" {
  region  = "us-east-1"
  profile = "my_sso_profile"
}

resource "aws_s3_bucket" "b" {
  bucket = "my-tf-test-bucket"
  acl    = "private"

  tags = {
    Name        = "My bucket"
    Environment = "Dev"
  }
}
```

AWS sso cache file generated by aws sso login:

```json
{"startUrl": "REDACTED", "region": "REDACTED", "accessToken": "REDACTED", "expiresAt": "2021-12-11T07:18:18UTC"}
```

### Debug Output

```
│ Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
│ 
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│ 
│ Error: SSOProviderInvalidToken: the SSO session has expired or is invalid
│ caused by: expected RFC3339 timestamp: parsing time "2021-12-11T07:18:18UTC" as "2006-01-02T15:04:05Z07:00": cannot parse "UTC" as "Z07:00"
│ 
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on providers.tf line 1, in provider "aws":
│    1: provider "aws" {
```

### Expected Behavior

Correctly parse `2021-12-11T07:18:18UTC`

### Actual Behavior

Error parsing `2021-12-11T07:18:18UTC`

### Steps to Reproduce

1. `aws --profile my_sso_profile sso login`
2. `terraform init`
3. `terraform plan`

### Important Factoids

if I tweak the SSO cachefile changing the `expiresAt` key to `2021-12-11T07:15:18-03:00` , terraform successfully parses

**Comment by ewbankkit** [comment]
https://github.com/aws/aws-sdk-go/blob/e2d6cb448883e4f4fcc5246650f89bde349041ec/aws/credentials/ssocreds/provider.go#L128-L143

Relates: https://github.com/aws/aws-sdk-go/issues/3324.
Relates: https://github.com/boto/botocore/pull/2250.
Relates: https://github.com/boto/botocore/issues/1808.

**Comment by hellupline** [comment]
can confirm , error source is older version of AWS-CLI generating incorrect value for the field, correct value should have `Z` instead of `UTC`, 

upgrading AWS-CLI fixed the issue


I will close this issue
