### ISSUE TITLE
AWS Route: failed to respond to plugin.(*GRPCProvider).ApplyResourceChange

### ISSUE THREAD

**Issue by aviatrixLeon** [hashicorp/terraform-provider-aws#22177]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

% terraform -v                                         
Terraform v0.15.5
on darwin_amd64
+ provider registry.terraform.io/aviatrixsystems/aviatrix v2.19.0
+ provider registry.terraform.io/hashicorp/aws v3.68.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/hashicorp/tls v3.1.0

### Affected Resource(s)

* aws_XXXXX
 Error: Plugin did not respond
│ 
│   with module.aws-vpc-onprem_west1.aws_vpn_connection_route.route[1],
│   on .terraform/modules/aws-vpc-onprem_west1/main.tf line 243, in resource "aws_vpn_connection_route" "route":
│  243: resource "aws_vpn_connection_route" "route" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.aws-vpc-onprem_west1.aws_vpn_connection_route.route[0],
│   on .terraform/modules/aws-vpc-onprem_west1/main.tf line 243, in resource "aws_vpn_connection_route" "route":
│  243: resource "aws_vpn_connection_route" "route" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v3.68.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6ef62fd]

goroutine 920 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.resourceVPNConnectionRouteCreate.func1(0xc000ca0ee0, 0xc000ca0ea0, 0x0, 0x0, 0x2, 0x1)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/ec2/vpn_connection_route.go:70 +0x9d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1(0xc001d3c900, 0xc002a2a540, 0xc00005c3c0, 0xc002552600, 0xc0001d4460, 0xc0001d4438)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/resource/state.go:110 +0x2e9
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/resource/state.go:83 +0x1c6

Error: The terraform-provider-aws_v3.68.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

#### THIS IS THE LINE WHICH CAUSE THE CRASH ####
resource "aws_vpn_connection_route" "route" {
  count                  = length(var.static_route_cidr)
  vpn_connection_id      = aws_vpn_connection.vpn.id
  destination_cidr_block = var.static_route_cidr[count.index]
}

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.
I have a module called "aws-vpc-onprem", which includes the resource "asw_vpc_connection_route "route" {....}. When I have only one of this module, everything works as expected. However, when. have two of the module, it caused the crash. Below is the module in the .terraform folder

### start of the module ###

# Main.tf for testbed-onprem module
data "aws_region" "current" {}

terraform {
    required_providers {
        aviatrix = {
            source = "AviatrixSystems/aviatrix"
            version = "2.19.0"
        }
        aws = {
            source = "hashicorp/aws"
        }
    }
    required_version = ">=0.13"
}

resource "aws_vpc" "onprem_vpc" {
    cidr_block = var.onprem_vpc_cidr

    tags    = {
        Name  = "${var.resource_name_label}-onprem-vpc-${data.aws_region.current.name}"
        Owner = var.owner
    }
}

resource "aws_subnet" "public_subnet" {
    vpc_id            = aws_vpc.onprem_vpc.id
    cidr_block        = var.pub_subnet_cidr
    availability_zone = var.pub_subnet_az != null ? var.pub_subnet_az : ""

    tags    = {
        Name  = var.pub_subnet_az != null ? "${var.resource_name_label}-onprem-public-subnet-${var.pub_subnet_az}" : "${var.resource_name_label}-onprem-public-subnet-${data.aws_region.current.name}"
        Owner = var.owner
    }
}

resource "aws_subnet" "private_subnet" {
    vpc_id            = aws_vpc.onprem_vpc.id
    cidr_block        = var.pri_subnet_cidr
    availability_zone = var.pri_subnet_az != null ? var.pri_subnet_az : ""

    tags    = {
        Name  = var.pri_subnet_az != null ? "${var.resource_name_label}-onprem-private-subnet-${var.pri_subnet_az}" : "${var.resource_name_label}-onprem-private-subnet-${data.aws_region.current.name}"
        Owner = var.owner
    }
}

resource "aws_internet_gateway" "igw" {
  vpc_id = aws_vpc.onprem_vpc.id

    tags = {
        Name  = "${var.resource_name_label}-onprem-igw-${data.aws_region.current.name}"
        Owner = var.owner
    }
}

resource "aws_route_table" "public_rtb" {
    vpc_id                = aws_vpc.onprem_vpc.id

    route {
        cidr_block = "0.0.0.0/0"
        gateway_id = aws_internet_gateway.igw.id
    }

    lifecycle {
        ignore_changes = all
    }

    tags = {
        Name  = "${var.resource_name_label}-onprem-public-rtb-${data.aws_region.current.name}"
        Owner = var.owner
    }
}

resource "aws_route_table" "private_rtb" {
    vpc_id                = aws_vpc.onprem_vpc.id

    lifecycle {
        ignore_changes = all
    }

    tags = {
        Name  = "${var.resource_name_label}-onprem-private-rtb-${data.aws_region.current.name}"
        Owner = var.owner
    }
}

resource "aws_route_table_association" "public_rtb_associate" {
    subnet_id      = aws_subnet.public_subnet.id
    route_table_id = aws_route_table.public_rtb.id
}

resource "aws_route_table_association" "private_rtb_associate" {
    subnet_id       = aws_subnet.private_subnet.id
    route_table_id  = aws_route_table.private_rtb.id
}

resource "aws_security_group" "sg" {
    name        = "onprem_allow_ssh_and_icmp"
    description = "Allow SSH connection and ICMP to ubuntu instances."
    vpc_id      = aws_vpc.onprem_vpc.id

    ingress {
    # SSH
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
    }

    ingress {
    # ICMP
    from_port   = -1
    to_port     = -1
    protocol    = "icmp"
    cidr_blocks = ["0.0.0.0/0"]
    }

    egress {
    # Allow all
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
    }

    tags    = {
        Name  = "${var.resource_name_label}-onprem-security-group-${data.aws_region.current.name}"
        Owner = var.owner
    }
}

resource "random_id" "key_id" {
    byte_length = 4
}

# Key pair is used for all ubuntu instances
resource "aws_key_pair" "key_pair" {
    key_name   = "${var.resource_name_label}-onprem-ubuntu-key-${random_id.key_id.dec}"
    public_key = var.public_key
}

resource "aws_instance" "public_instance" {
    # Ubuntu
    ami = var.ubuntu_ami != null ? var.ubuntu_ami : local.ubuntu_ami[data.aws_region.current.name]
    instance_type               = "t2.micro"
    disable_api_termination     = var.termination_protection
    associate_public_ip_address = true
    subnet_id                   = aws_subnet.public_subnet.id
    private_ip = cidrhost(aws_subnet.public_subnet.cidr_block, var.pub_hostnum)
    vpc_security_group_ids      = [aws_security_group.sg.id]
    key_name                    = aws_key_pair.key_pair.key_name

    tags = {
        Name  = "${var.resource_name_label}-onprem-public-ubuntu-${aws_subnet.public_subnet.availability_zone}"
        Owner = var.owner
    }
}

resource "aws_eip" "eip" {
    instance    = aws_instance.public_instance.id
    vpc         = true
    tags    = {
        Name  = "${var.resource_name_label}-onprem-public-instance-eip-${data.aws_region.current.name}"
        Owner = var.owner
    }
}

resource "aws_instance" "private_instance" {
    # Ubuntu
    ami = var.ubuntu_ami != null ? var.ubuntu_ami : local.ubuntu_ami[data.aws_region.current.name]
    instance_type           = "t2.micro"
    disable_api_termination = var.termination_protection
    subnet_id               = aws_subnet.private_subnet.id
    private_ip = cidrhost(aws_subnet.private_subnet.cidr_block, var.pri_hostnum)
    vpc_security_group_ids = [aws_security_group.sg.id]
    key_name = aws_key_pair.key_pair.key_name

  tags  = {
    Name  = "${var.resource_name_label}-onprem-private-ubuntu-${aws_subnet.private_subnet.availability_zone}"
    Owner = var.owner
  }
}

resource "time_sleep" "wait_240_seconds" {
  depends_on = [aws_internet_gateway.igw]

  create_duration = "240s"
}

resource "aviatrix_gateway" "avtx_gw" {
    depends_on = [
        time_sleep.wait_240_seconds
    ]
    cloud_type          = 1
    account_name        = var.account_name
    gw_name             = "${var.resource_name_label}-${var.gw_name}"
    vpc_id              =  aws_vpc.onprem_vpc.id
    vpc_reg             = data.aws_region.current.name
    gw_size             = "t3.micro"
    subnet              = aws_subnet.public_subnet.cidr_block
    single_ip_snat      = true
}

resource "aws_customer_gateway" "aws_cgw" {
  depends_on = [
      aviatrix_gateway.avtx_gw
  ]
  bgp_asn     = 65000
  ip_address  = aviatrix_gateway.avtx_gw.eip
  type        = "ipsec.1"

  tags = {
    Name  = "${var.resource_name_label}-main-cgw-${data.aws_region.current.name}"
    Owner = var.owner
  }
}

resource "aws_vpn_gateway" "aws_vgw" {
    amazon_side_asn = var.asn

    tags  = {
      Name  = "${var.resource_name_label}-onprem-vgw-${data.aws_region.current.name}"
      Owner = var.owner
    }
}

resource "aws_vpn_connection" "vpn" {
    depends_on = [
        aws_customer_gateway.aws_cgw
    ]
    customer_gateway_id = aws_customer_gateway.aws_cgw.id
    vpn_gateway_id     = aws_vpn_gateway.aws_vgw.id
    static_routes_only = true
    type               = "ipsec.1"

    tags = {
        Name  = "${var.resource_name_label}-onprem-vpn-${data.aws_region.current.name}"
        Owner = var.owner
    }
}

resource "aws_vpn_connection_route" "route" { # <<<<<<<<---------- this is the line which caused crash
  count                  = length(var.static_route_cidr)
  vpn_connection_id      = aws_vpn_connection.vpn.id
  destination_cidr_block = var.static_route_cidr[count.index]
}

resource "aviatrix_site2cloud" "onprem_s2c" {
  vpc_id          = aws_vpc.onprem_vpc.id
  connection_name = "${var.resource_name_label}-${var.s2c_connection_name}"
  connection_type            = "unmapped"
  remote_gateway_type        = "generic"
  tunnel_type                = "route"
  primary_cloud_gateway_name = aviatrix_gateway.avtx_gw.gw_name
  remote_gateway_ip          = aws_vpn_connection.vpn.tunnel1_address
  pre_shared_key             = aws_vpn_connection.vpn.tunnel1_preshared_key
  remote_subnet_cidr         = join(",", var.remote_subnet_cidr)
    local_subnet_cidr        = join(",", var.local_subnet_cidr)
}

### end of the module ###

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior
the expected behavior should be done successfully without an error.

the two onprem and all associated VMs, route, vpn connection should be created 

### Actual Behavior

Crash was seen and error message as below

 Error: Plugin did not respond
│ 
│   with module.aws-vpc-onprem_west1.aws_vpn_connection_route.route[1],
│   on .terraform/modules/aws-vpc-onprem_west1/main.tf line 243, in resource "aws_vpn_connection_route" "route":
│  243: resource "aws_vpn_connection_route" "route" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.aws-vpc-onprem_west1.aws_vpn_connection_route.route[0],
│   on .terraform/modules/aws-vpc-onprem_west1/main.tf line 243, in resource "aws_vpn_connection_route" "route":
│  243: resource "aws_vpn_connection_route" "route" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v3.68.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6ef62fd]

goroutine 920 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.resourceVPNConnectionRouteCreate.func1(0xc000ca0ee0, 0xc000ca0ea0, 0x0, 0x0, 0x2, 0x1)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/ec2/vpn_connection_route.go:70 +0x9d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1(0xc001d3c900, 0xc002a2a540, 0xc00005c3c0, 0xc002552600, 0xc0001d4460, 0xc0001d4438)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/resource/state.go:110 +0x2e9
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/resource/state.go:83 +0x1c6

Error: The terraform-provider-aws_v3.68.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce

1)use the above module to create two onprems on either the same or different regions.
2) after the terraform is created, do terraform init and apply
3) it will consistently crash whenever the code hits to create "laws_vpn_connection_route"

1. `terraform apply`

### References

* #0000

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/dcf737e886dd689544350b41ad0ee28f4def85e8/internal/service/ec2/vpn_connection_route.go#L65-L71

https://github.com/hashicorp/terraform-provider-aws/blob/dcf737e886dd689544350b41ad0ee28f4def85e8/internal/service/ec2/vpn_connection_route.go#L134-L164

`findConnectionRoute` return `nil, nil` if the route is not found.

**Comment by aviatrixLeon** [comment]
when I had only one route, it worked well. However, if I have two routes, somehow it got crashed.
