### ISSUE TITLE
Documentation: Outdated aws_lightsail_instance attributes reference

### ISSUE THREAD

**Issue by heanzyzabala** [hashicorp/terraform-provider-aws#22184]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_lightsail_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Upon checking generated state. Exported attributes are actually more than what the documentation has mentioned.
```
  "attributes": {
    "arn": "arn:aws:lightsail:ap-southeast-1:********:Instance/8226c820-8f2c-4273-964a-0f1d9140c53e",
    "availability_zone": "ap-southeast-1a",
    "blueprint_id": "amazon_linux_2",
    "bundle_id": "micro_2_0",
    "cpu_count": 1,
    "created_at": "2021-12-12T07:23:23Z",
    "id": "k3s_agent",
    "ipv6_address": "2406:da18:e5:5800:4bba:cea6:84b:f990",
    "ipv6_addresses": [
      "2406:da18:e5:5800:4bba:cea6:84b:f990"
    ],
    "is_static_ip": false,
    "key_pair_name": "LightsailDefaultKeyPair",
    "name": "k3s_agent",
    "private_ip_address": "172.26.15.95",
    "public_ip_address": "---",
    "ram_size": 1,
    "tags": null,
    "tags_all": {},
    "user_data": "#!/bin/bash\n\nsudo yum -y update\n\ncurl -sfL https://get.k3s.io | K3S_URL=https://172.26.12.205:6443 K3S_TOKEN=token sh -\n",
    "username": "ec2-user"
  },
```

### Actual Behavior

Documentation only shows partial exported attributes, would be nice to update it

### Steps to Reproduce

1. `terraform apply`

### References

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_instance

**Comment by justinretzolk** [comment]
Hey @heanzyzabala 👋 Thank you for taking the time to open this issue! I'll work up a quick pull request to get these additional attributes documented.

Notes:
https://docs.aws.amazon.com/sdk-for-go/api/service/lightsail/#Instance
https://docs.aws.amazon.com/sdk-for-go/api/service/lightsail/#InstanceHardware
