### ISSUE TITLE
Add support for AWS Direct Connect Sitelink

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform-provider-aws#22187]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Added [DX Sitelink support](https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-aws-direct-connect-sitelink/) which requires updates to DX VIF resources.

### New or Affected Resource(s)

* aws_dx_hosted_private_virtual_interface
* aws_dx_hosted_public_virtual_interface
* aws_dx_hosted_transit_virtual_interface
* aws_dx_private_virtual_interface
* aws_dx_public_virtual_interface
* aws_dx_transit_virtual_interface

### Potential Terraform Configuration

```hcl
resource "aws_dx_private_virtual_interface" "foo" {
  connection_id = "dxcon-zzzzzzzz"

  name            = "vif-foo"
  vlan            = 4094
  address_family  = "ipv4"
  bgp_asn         = 65352
  enable_sitelink = true
}
```

**Comment by NetDevAutomate** [comment]
This is item is being worked on.

**Comment by NetDevAutomate** [comment]
The PR will add support for:

- aws_dx_private_virtual_interface
- aws_dx_transit_virtual_interface

As hosted and private VIFs aren't supported.

I'm waiting to run the acceptance tests as I need some additional permissions to on my test account.
