### ISSUE TITLE
Unchanged data.aws_ssoadmin_instances.arns causes recreation of permission sets and account assignments

### ISSUE THREAD

**Issue by mimozell** [hashicorp/terraform-provider-aws#22188]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v1.0.11
on darwin_arm64
provider registry.terraform.io/hashicorp/aws v3.68.0
provider registry.terraform.io/hashicorp/azuread v2.12.0

### Affected Resource(s)

* aws_ssoadmin_instances

### Terraform Configuration Files
Using the following module to create AWS SSO permission sets and assign them to AWS Accounts and replicated Azure AD groups: https://github.com/avlcloudtechnologies/terraform-aws-sso.

### Expected Behavior

I would expect permission sets and account assignments not to be marked for replacement since the `data.aws_ssoadmin_instances.arns` don't change.

### Actual Behavior
Whenever I add a new permission set or make changes to the account assignments, all the permission sets and assignments are destroyed, because of the change to data which isn't an actual change since those parameters will remain the same for every read.

<img width="762" alt="Screenshot 2021-12-13 at 16 27 32" src="https://user-images.githubusercontent.com/40452559/145840067-c1b28b7c-3777-4415-aa84-388a98f34316.png">

<img width="1461" alt="Screenshot 2021-12-13 at 16 03 11" src="https://user-images.githubusercontent.com/40452559/145838593-1c423c78-1727-45ff-b429-19bbeb1e70df.png">

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @mimozell 👋 Thank you for taking the time to file this issue! My gut reaction is that this may be expected behavior, as the `aws_ssoadmin_permission_set` resources are referring to the data source that is showing as having values not known until apply time. That said, I generally wouldn't expect a data source to behave this way unless you were passing arguments to the data source itself that weren't known until after the plan phase, so I've marked this as a bug so that we can look into it as time allows.

**Comment by mimozell** [comment]
Thanks @justinretzolk :) I'm kinda worried that this change to the arns (when arns doesn't actually change in aws) that causes the recreation of permission set assignments to accounts might create some issues with user access.

**Comment by frankpengau** [comment]
I agree, this issue is quite prevalent and what has happened in my case is that during the recreation process, there is a throttling exception because of the number of api calls made to aws sso, even though there is no change in the ARNs for the SSO Instance and Permission Set. 

Is it necessary for the Force Replacement to occur, despite no changes to the permission set?

**Comment by uceimmp** [comment]
Any more updates on this? :) I am facing the same issue as well.

**Comment by jagnk** [comment]
Happening in our project as well. We are referencing Permissions Sets ARNs in k8s, so every time Terraform recreates the roles, we need to change manually in k8s auth-config. It is not ideal. Is there any short term workaround for this?

**Comment by jagnk** [comment]
Hi @justinretzolk! Thank you for coming back to me.
We are using https://github.com/cloudposse/terraform-aws-sso/tree/0.6.2 module to create permission sets and account assignments. 

`module "account_assignments" {
  source     = "cloudposse/sso/aws//modules/account-assignments"
  version    = "0.6.2"
  depends_on = [module.permission_sets]

  account_assignments = [
    {
      account             = local.accounts.platform,
      permission_set_arn  = module.permission_sets.permission_sets[local.permission_sets.admin].arn,
      permission_set_name = local.permission_sets.admin,
      principal_type      = local.principal_type,
      principal_name      = local.principal_names.devops
    }
  ]
}

module "permission_sets" {
  source  = "cloudposse/sso/aws//modules/permission-sets"
  version = "0.6.2"

  permission_sets = [
    { 
     name               = local.permission_sets.admin,
      session_duration   = local.session_duration,
      description        = local.description,
      relay_state        = local.relay_state,
      tags               = local.tags,
      inline_policy      = data.aws_iam_policy_document.policy_admin_access.json,
      policy_attachments = ["arn:aws:iam::aws:policy/AdministratorAccess"]
    }
  ]
}
`

Indeed the module contains data source for `aws_ssoadmin_instances` and it is called when we run `terraform plan`. We raised the issue on the module as well: https://github.com/cloudposse/terraform-aws-sso/issues/29

Is there any workaround to prevent recreation of the permissions sets ARNs?
