### ISSUE TITLE
Support Real-User Monitoring (RUM) for Amazon CloudWatch

### ISSUE THREAD

**Issue by mura-s** [hashicorp/terraform-provider-aws#22201]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* AWS recently released [CloudWatch RUM](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-RUM.html).

> With CloudWatch RUM, you can perform real user monitoring to collect and view client-side data about your web application performance from actual user sessions in near real time.

* To set up CloudWatch RUM, you need to create an `app monitor`, but currently terraform-provider-aws doesn't seem to support the feature.

### New or Affected Resource(s)

New Resource

* aws_rum_app_monitor

### References

* https://aws.amazon.com/jp/blogs/aws/cloudwatch-rum/
* https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-RUM-get-started-create-app-monitor.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rum-appmonitor.html
* https://docs.aws.amazon.com/cloudwatchrum/latest/APIReference/API_CreateAppMonitor.html
* https://docs.aws.amazon.com/cloudwatchrum/latest/APIReference/API_GetAppMonitor.html
* https://docs.aws.amazon.com/cloudwatchrum/latest/APIReference/API_UpdateAppMonitor.html
* https://docs.aws.amazon.com/cloudwatchrum/latest/APIReference/API_DeleteAppMonitor.html

**Comment by PabloL007** [comment]
As we would also like to have it, I'm going to try implementing it. I've submitted a PR for adding the Go SDK service client as it seems to be the procedure before starting to add resources ([source](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/contribution-checklists.md#new-service))

**Comment by jon-armen** [comment]
@PabloL007 , how is your work progressing on adding the resource?  If you need, I may be able to jump in and assist.

**Comment by PabloL007** [comment]
Hi @jon-armen, that would be awesome, unfortunately my priorities have shifted and I can't dedicate much time to this. [This](https://github.com/hashicorp/terraform-provider-aws/compare/main...PabloL007:aws-cloudwatchrum-app-monitor?expand=1) is as far as I got with it, note that some acceptance tests are missing to be compliant with [this](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/running-and-writing-acceptance-tests.md#resource-acceptance-testing), feel free to take it.
