### ISSUE TITLE
aws_networkfirewall_rule_group - Cant reference rule_variables/ip_sets or port_sets from rules_source/stateful_rule

### ISSUE THREAD

**Issue by paullemon** [hashicorp/terraform-provider-aws#22209]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform allows me to create rule_variables/ip_sets and rule_variables/port_sets but I am not seeing a way to reference these from rules_source/stateful_rule.  I can do so in the GUI/Console just by using the rule_variable name in a "Source" or "Destination" column. 

 I have noticed this type of functionality exists for the rules_source/rules_string options which point to a suricata rules file, but just doesn't appear to exist/work for the rules_source/stateful_rule.  

### Example ip_set / port_set
```terraform
resource "aws_networkfirewall_rule_group" "example" {
  capacity = 100
  name     = "example"
  type     = "STATEFUL"
  rule_group {
    rule_variables {
      ip_sets {
        key = "WEBSERVERS_HOSTS"
        ip_set {
          definition = ["10.0.0.0/16", "10.0.1.0/24", "192.168.0.0/16"]
        }
      }
      ip_sets {
        key = "EXTERNAL_HOST"
        ip_set {
          definition = ["1.2.3.4/32"]
        }
      }
      port_sets {
        key = "HTTP_PORTS"
        port_set {
          definition = ["443", "80"]
        }
      }
    }
  }
}
```
### Example stateful rule:
```terraform
resource "aws_networkfirewall_rule_group" "example" {
  capacity = 100
  name     = "example"
  type     = "STATEFUL"
  rule_group {
    rules_source {
      stateful_rule {
        action = "DROP"
        header {
          destination      = "124.1.1.24/32"
          destination_port = 53
          direction        = "ANY"
          protocol         = "TCP"
          source           = "1.2.3.4/32"
          source_port      = 53
        }
        rule_option {
          keyword = "sid:1"
        }
      }
    }
  }
}
```
### New or Affected Resource(s)

resource "aws_networkfirewall_rule_group"

### Potential Terraform Configuration

Would like to see something like this:
```
  rule_group {
    rules_source {
      stateful_rule {
        action = "PASS"
        header {
          destination      = WEBSERVERS_HOST
          destination_port = HTTP_PORTS
          direction        = "ANY"
          protocol         = "TCP"
          source           = EXTERNAL_HOSTS
          source_port      = "ANY"
        }
      }
    }
  }
```
### References
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/network-firewall/index.html#cli-aws-network-firewall
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkfirewall_rule_group

**Comment by justinretzolk** [comment]
Hey @paullemon 👋 Thank you for taking the time to raise this! This functionality was released in [version 4.4.0 of the AWS Provider](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#440-march-04-2022). With that in mind, we'll close this issue. If you feel we've done this in error, please do let us know.
