### ISSUE TITLE
Add new resource/data_source for aws_connect_lambda_association

### ISSUE THREAD

**Issue by dax-hurley** [hashicorp/terraform-provider-aws#22210]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Create a resource for the AssociateLambdaFunction endpoint of the Amazon Connect APIs to enable the invoking of Lambda function in Contact flows created through terraform.

### New or Affected Resource(s)

* aws_connect_lambda_association
* data/aws_connect_lambda_association

### Potential Terraform Configuration
**Resource:**
```hcl
resource "aws_connect_lambda_association" "crm_lookup_lambda_association" {
  instance_id = "97afc98d-101a-ba98-ab97-ae114fc115ec"
  lambda_arn = "arn:aws:lambda:us-west-2:123456789012:function:connectCrmLookupLambda
}
```
**Data:**
```hcl
data "aws_connect_lambda_association" "crm_lookup_association" {
  instance_id = "97afc98d-101a-ba98-ab97-ae114fc115ec"
  lambda_arn = "arn:aws:lambda:us-west-2:123456789012:function:connectCrmLookupLambda
}
```

### References

* [#Amazon Connect Docs](https://docs.aws.amazon.com/connect/latest/APIReference/API_AssociateLambdaFunction.html)

**Comment by anGie44** [comment]
Hi @dax-hurley , thank you for raising this issue, however, this has recently been addressed in https://github.com/hashicorp/terraform-provider-aws/issues/21047 and the resource and data source will be available with v3.70.0 of the provider, likely out this Thursday evening (EST) 😃 .
