### ISSUE TITLE
aws_cloudfront_response_headers_policy resource reference is missing cors_config.origin_override on Argument Reference

### ISSUE THREAD

**Issue by LegendaryMM** [hashicorp/terraform-provider-aws#22220]
The cors_config.origin_override argument is shown in the example on the [aws_cloudfront_response_headers_policy resource reference page](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_response_headers_policy#example-usage). But the cors_config.origin_override is missing in the cors_config Argument Reference section.

**Comment by Lucifer0x17** [comment]
Hey, if no one is working on the issue I would like to work on it.

**Comment by LegendaryMM** [comment]
I would like to fix it myself if I can. What repo is this issue located on?

**Comment by LegendaryMM** [comment]
Looks like origin_override also needs to be added on the data page https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/cloudfront_response_headers_policy

Also, the documentation lists access_control_max_age_sec as required when I think it might be optional and just default to 600 when not provided.
