### ISSUE TITLE
Support DnsProperties (TTL) in aws_service_discovery_private_dns_namespace

### ISSUE THREAD

**Issue by NRachakonda** [hashicorp/terraform-provider-aws#22225]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently DnsProperties (TTL) is not supported in the creation of terraform aws_service_discovery_private_dns_namespace resource. We just want to be able to specify this to modify the TTL according to our requirements. 

### New or Affected Resource(s)

* aws_service_discovery_private_dns_namespace

### Potential Terraform Configuration

```hcl
resource "aws_service_discovery_private_dns_namespace" "dns" {
  name        = "local.example.com"
  description = "xxx Service Namespace"
  vpc         = example.vpcid
  dns_properties  { 
        soa   {
           ttl = 10
         }
   }
}
```

**Comment by 4dz** [comment]
I think this AWS issue (now resolved) explains the feature which is not yet supported by terraform, https://github.com/aws/aws-app-mesh-roadmap/issues/221

Also, https://docs.aws.amazon.com/cloud-map/latest/api/API_CreatePrivateDnsNamespace.html and https://docs.aws.amazon.com/cloud-map/latest/api/API_UpdatePrivateDnsNamespace.html
