### ISSUE TITLE
Terraformer import of aws_sqs_queue fails with terraform-provider-aws interface panic

### ISSUE THREAD

**Issue by MartinAkram** [hashicorp/terraform-provider-aws#22233]
Attempting to generate Terraform config files from existing infrastructure (using Terraformer) results in the following terraform-provider-aws interface panic:

`plugin.terraform-provider-aws_v2.70.0_x4: panic: interface conversion: interface {} is nil, not *aws.AWSClient`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
terraform v1.0.4 on darwin_amd64
terraform aws provider 2.70.0
terraformer version 0.8.18
```
### Affected Resource(s)

- aws_sqs_queue

### Terraform Configuration Files

No Terraform config files available. We were trying to generate the files using Terraformer when we encountered the terraform-provider-aws interface panic.

### Debug Output

[Debug Output](https://gist.github.com/MartinAkram/2b6233dd1b16d8d08442a5fff6cd248c)

### Panic Output

[Panic Output](https://gist.github.com/MartinAkram/03f874b14b41efa6d447c33634c0edd2)

### Expected Behavior

SQS queue from AWS account has Terraform config generated locally

### Actual Behavior

Despite being able to identify the correct number of available sqs queues in the AWS account ([line 18 of the Debug Output](https://gist.github.com/MartinAkram/2b6233dd1b16d8d08442a5fff6cd248c#:~:text=2021/12/14%2013%3A30%3A33%20Number%20of%20resources%20for%20service%20sqs%3A%2021)), even with full IAM perms, we kept running into an unexpected terraform-provider-aws interface panic ([line 20 of the Debug Output](https://gist.github.com/MartinAkram/2b6233dd1b16d8d08442a5fff6cd248c#:~:text=2021%2D12%2D14T13%3A30%3A33.825%2D0800%20%5BDEBUG%5D%20plugin.terraform%2Dprovider%2Daws_v2.70.0_x4%3A%20panic%3A%20interface%20conversion%3A%20interface%20%7B%7D%20is%20nil%2C%20not%20*aws.AWSClient)).

### Steps to Reproduce

1. Install aforementioned versions of Terraform and Terraformer
2. Run the following command in a directory where Terraform was initialized:
`terraformer import aws --resources=sqs --regions=us-east-1 --profile "mycoolprofile" -v --filter=sqs=mycoolqueue`

[Documentation](https://github.com/GoogleCloudPlatform/terraformer/blob/master/docs/aws.md) on Terraformer use for aws

### Important Factoids

None

### References

None

**Comment by anGie44** [comment]
Hi @MartinAkram , thank you raising this issue. Looking around our past issues, including https://github.com/hashicorp/terraform-provider-aws/issues/21215 , the comments indicate this has luckily been addressed in terraform core as of terraform CLI version `1.0.9`. Do you mind testing again with this newer version to verify that you're no longer experiencing this issue? thanks!

**Comment by MartinAkram** [comment]
@anGie44 Thank you for the quick reply! I'll test per your recommendation and respond asap.

**Comment by MartinAkram** [comment]
Apologies for the delayed response on this @anGie44! Things got away from me around the hectic holiday schedule.

I tested with the newer version of terraform CLI like you suggested, and that did resolve the `panic` I saw earlier, thank you!

However, now I'm seeing a more generic and much less specific error, seen [here](https://gist.github.com/MartinAkram/9bd0482027a6e68663b683ca119303e3). The same thing happens as the first instance when I reported the bug: terraformer is able to see the count and names of the queues (20), but is unable to proceed with importing the queues due to a plugin error.

`plugin.terraform-provider-aws_v2.70.0_x4: 2021/12/30 10:56:54 ERROR Found AccessDenied`

My authenticated user has the correct IAM permissions.

Please let me know if anything else comes to mind or if I can try something else you recommend. Thank you for the help!
