### ISSUE TITLE
Typo in argument reference for aws_fsx_ontap_storage_virtual_machine resource

### ISSUE THREAD

**Issue by k1ngkhan** [hashicorp/terraform-provider-aws#22238]
When attempting to add the argument "organizational_unit_distinguished_name" under the aws_fsx_ontap_storage_virtual_machine resource

terraform returns the following error:

`An argument named "organizational_unit_distinguished_name" is not expected here. Did you mean
│ "organizational_unit_distinguidshed_name"?`

Using the suggested name (organizational_unit_distinguidshed_name) works when pushing the changes to AWS. This is a typo as this argument is referenced as `organizational_unit_distinguished_name` in the terraform documentation [https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_ontap_storage_virtual_machine#organizational_unit_distinguished_name](url)

Can this be corrected?

**Comment by ewbankkit** [comment]
@k1ngkhan Thanks for raising this issue.
It has already been noticed in #21987. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
