### ISSUE TITLE
New Service: AWS Data Exchange

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#22237]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Data Exchange makes it easy to find, subscribe to, and use third-party data in the cloud. Qualified data providers include category-leading brands such as Reuters, who curate data from over 2.2 million unique news stories per year in multiple languages; Change Healthcare, who process and anonymize more than 14 billion healthcare transactions and $1 trillion in claims annually; Dun & Bradstreet, who maintain a database of more than 330 million global business records; and Foursquare, whose location data is derived from 220 million unique consumers and includes more than 60 million global commercial venues.

### New or Affected Resource(s)

* aws_dataexchange_dataset
* aws_dataexchange_job
* aws_dataexchange_event_action
* aws_dataexchange_revision

### References

* [AWS Data Exchange](https://aws.amazon.com/data-exchange/)
* [API Reference](https://docs.aws.amazon.com/data-exchange/latest/apireference/welcome.html)
* #10926

**Comment by DrFaust92** [comment]
Ill be looking into implementing this this week.
