### ISSUE TITLE
Dynamically generated queues

### ISSUE THREAD

**Issue by CodeWithOz** [hashicorp/terraform-provider-aws#22232]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like to have the ability to subscribe to dynamically generated queues, either by consuming from all queues bound to an exchange, or by specifying the queue to initiate the event source at the moment that the queue is generated.

### New or Affected Resource(s)

* AmazonMQ
* AWS Lambda

### Potential Terraform Configuration

```hcl
resource "aws_lambda_event_source_mapping" "example" {
  batch_size       = 10
  event_source_arn = aws_mq_broker.example.arn
  enabled          = true
  function_name    = aws_lambda_function.example.arn
  queues           = [] # <== blank at creation time but I want a way to add to it when a new queue is generated

  source_access_configuration {
    type = "BASIC_AUTH"
    uri  = aws_secretsmanager_secret_version.example.arn
  }
}
```

**Comment by anGie44** [comment]
Hi @CodeWithOz , thank you for raising this issue. Atm, it looks like this is still a limitation of the upstream lambda service as [only a single queue can be specified at Create](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateEventSourceMapping.html#SSS-CreateEventSourceMapping-request-Queues) time and the [Update functionality](https://docs.aws.amazon.com/lambda/latest/dg/API_UpdateEventSourceMapping.html#API_UpdateEventSourceMapping_RequestSyntax) doesn't seem to offer input for updating those values afict.

**Comment by CodeWithOz** [comment]
Okay thank you for the response.
