### ISSUE TITLE
Exported attribute for resource aws_glue_user_defined_function differs from documentation 

### ISSUE THREAD

**Issue by michaelplehm** [hashicorp/terraform-provider-aws#22230]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

- Terraform 1.1.0
- Provider 3.69.0 (assuming >3.50.0)

### Affected Resource(s)

* aws_glue_user_defined_function
* AWS region eu-central-1

### Terraform Configuration Files

```hcl
output "glue_user_defined_function_create_date" {
  description = "The time at which the function was created."
  value       = element(concat(aws_glue_user_defined_function.glue_user_defined_function.*.create_date, [""]), 0)
}
```

Found in https://github.com/hashicorp/terraform-provider-aws/blob/a498222f7751d588b4642677f569e46ebf7d0b03/internal/service/glue/user_defined_function.go#L83

### Expected Behavior

Output is usable with attribute `create_date` according to documentation (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_user_defined_function#create_date) but most probably it should be `create_time` in documentation as  the API is using `CreateTime`. 

### Actual Behavior

Error is reported:

```
Error: Unsupported attribute
│ 
│   on ../terraform-aws-glue/outputs.tf line 3, in output "glue_user_defined_function_create_date":
│  3:   value       = element(concat(aws_glue_user_defined_function.glue_user_defined_function.*.create_date, [""]), 0)
│ 
│ This object does not have an attribute named "create_date".
```

Attribute is named `create_time` in implementation. 

### Steps to Reproduce

1. `terraform plan`

### References

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_user_defined_function#create_date
* https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/glue/user_defined_function.go
* https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-catalog-functions.html

**Comment by devesh-badal** [comment]
I would like to work on this issue.
