### ISSUE TITLE
Savings Plan Expiration Alert

### ISSUE THREAD

**Issue by maicon-ganex** [hashicorp/terraform-provider-aws#22240]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I don't know if already has how to configure the savings plan expiration alert by terraform, but I haven't found it, if has, please let me know. I need to set up an alert to notify me when the savings plan is about to expire.
A new feature to add this savings plan alerts settings by terraform will be helpful.

### New or Affected Resource(s)

AWS EC2 Savings Plans

**Comment by justinretzolk** [comment]
Hey @maicon-ganex 👋 Thank you for taking the time to file this! I took a look over the [Savings Plan](https://docs.aws.amazon.com/sdk-for-go/api/service/savingsplans/) section of the AWS Go SDK, any it seems that this isn't something that's currently supported by the underlying API. As this is the case, we'll close this issue for now, but would be happy to revisit it this becomes something that's supported by AWS in the future.
