### ISSUE TITLE
New resource: aws_kms_multi_region_key to define both primary and replica keys

### ISSUE THREAD

**Issue by lnattrass** [hashicorp/terraform-provider-aws#22243]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

aws_secretsmanager_secret allows you to specify regions to replicate secrets to within the resource itself.

aws_kms_replica_key does not follow this pattern, even though the API call is made against the Primary key's region.

Given it's not possible to for_each over providers, I think makes sense to support specifying additional regions without having to instantiate a new provider in the target region.

### New or Affected Resource(s)

* aws_kms_replica_key

### Potential Terraform Configuration

```hcl
resource "aws_kms_key" "primary" {
  description             = "Multi-Region primary key"
  deletion_window_in_days = 30
  multi_region            = true
}

resource "aws_kms_replica_key" "replica" {
  description             = "Multi-Region replica key"
  deletion_window_in_days = 7
  primary_key_arn         = aws_kms_key.primary.arn
  region = "us-west-2"
}
```

or this:

```hcl
resource "aws_kms_key" "mrk" {
  description             = "Multi-Region primary key"
  deletion_window_in_days = 30
  multi_region            = true
  replica {
    region = "us-west-2"
  }
}
```
### References

* #0000

**Comment by ewbankkit** [comment]
@lnattrass Please see [this comment](https://github.com/hashicorp/terraform-provider-aws/issues/19896#issuecomment-948729737) about the possibility of adding a `aws_kms_multi_region_key` (or similar) resource which would encapsulate the primary and replica keys of a multi-region KMS key.
If that idea sounds right, please re-title this PR and we can use it to gather upvotes and comments.

**Comment by lnattrass** [comment]
I could swear I searched - yes that would definitely do what I think we need

**Comment by bacoboy-doordash** [comment]
It would help with creation of the replica keys, but you'd still have to have region specific providers to set the regional `aws_kms_alias` is one thought I had.

This might also help with my particular issue of creating the replicas using an already assumed role since `aws_kms_replica_key` seems to fail on the second role assumption -- so I'm kinda stuck w/o this as a workaround:
```
aws_kms_replica_key.data-key-use2: Creating...
╷
│ Error: error creating AWS session: SharedConfigErr: only one credential type may be specified per profile: source profile, credential source, credential process, web identity token, or sso
│
│   with aws_kms_replica_key.data-key-use2,
│   on kms.tf line 17, in resource "aws_kms_replica_key" "data-key-use2":
│   17: resource "aws_kms_replica_key" "data-key-use2" {

```
I can import this key once created and apparently modify it too, but not create outright.  Should probably file a bug - but I suppose there isn't a direct fix.
