### ISSUE TITLE
aws_s3_bucket_public_access_block incorrect documentation

### ISSUE THREAD

**Issue by gurchik** [hashicorp/terraform-provider-aws#22257]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.62.0
```

### Affected Resource(s)

* aws_s3_bucket_public_access_block

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_s3_bucket_public_access_block" "example" {
  bucket = "foobar"

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
```

### Expected Behavior

* the documentation says the exported attribute `id` is an `AWS account ID`
* the documentation says you import using the `AWS account ID, e.g. 123456789012`

I tried to import with my account ID and got an error that the resource could not be found on AWS.

### Actual Behavior

Running the following reveals that actually the `ID` is the name of the bucket:

```
$ terraform console

> aws_s3_bucket_public_access_block.example
{
    "block_public_acls" = true
    "block_public_policy" = true
    "bucket" = "foobar"
    "id" = "foobar"
    "ignore_public_acls" = true
    "restrict_public_buckets" = true
}
```

I was able to successfully import by using the name of the bucket.

**Comment by anGie44** [comment]
Hi @gurchik , thank you for raising an issue here. Do you mind referencing which documentation seems out of sync with actual behavior? 

I'm currently looking at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_public_access_block which mentions something different but expected; the `id` is the name of the bucket and `import` states you can use the bucket name.

**Comment by gurchik** [comment]
You're right, I was accidentally reading the docs for `s3_account_public_access_block` which is very similar. Sorry!

**Comment by anGie44** [comment]
no worries @gurchik , they are certainly super similar!
