### ISSUE TITLE
terraform init not working: Failed to Query available provider packages

### ISSUE THREAD

**Issue by sohailanjum97** [hashicorp/terraform-provider-aws#22251]
I am using Terraform v1.1.1. 

When I am trying to run terraform init I always found this error:
![image](https://user-images.githubusercontent.com/48083468/146340155-4fa9078a-4567-41c7-ae05-bee47addb44f.png)
I tried to solve but I am not able to solve this bug. Here is my code of .tf file.

![image](https://user-images.githubusercontent.com/48083468/146340034-ad48252c-7971-4079-8102-001614b60a9f.png)

**Comment by ewbankkit** [comment]
@sohailanjum97 Thanks for raising this issue.
You have a typo - _hashicrop_ - in your `provider.tf`, this should be _hashicorp_.

**Comment by sohailanjum97** [comment]
Thanks :(
