### ISSUE TITLE
aws provider 2.70.1 is failing due to 

### ISSUE THREAD

**Issue by komealy** [hashicorp/terraform-provider-aws#22258]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
❯ terraform -version
Terraform v0.11.14
+ provider.aws v2.70.0
```

### Affected Resource(s)

* aws provider version 2.70.1

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  version = "2.70.1"
}
```

### Expected Behavior

```
❯ terraform init  -reconfigure -upgrade=true

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (2.70.1)...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

### Actual Behavior

```
❯ terraform init -reconfigure -upgrade=true

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Error installing provider "aws": openpgp: signature made by unknown entity.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/darwin_amd64
```

### Steps to Reproduce

1. `terraform init`

### Important Factoids

Reproduced in linux via AWS codebuild as well where we actually wrap terraform inside of terragrunt.

```
2021/12/16 20:33:41 Running command: terraform init -lock-timeout=60m -no-color -input=false
--
720 |  
721 | Error installing provider "aws": openpgp: signature made by unknown entity.
722 |  
723 | Terraform analyses the configuration and state and automatically downloads
724 | plugins for the providers used. However, when attempting to download this
725 | plugin an unexpected error occured.
726 |  
727 | This may be caused if for some reason Terraform is unable to reach the
728 | plugin repository. The repository may be unreachable if access is blocked
729 | by a firewall.
730 |  
731 | If automatic installation is not possible or desirable in your environment,
732 | you may alternatively manually install plugins by downloading a suitable
733 | distribution package and placing the plugin's executable file in the
734 | following directory:
735 | terraform.d/plugins/linux_amd64
```

### References

I found no existing open issues

**Comment by justinretzolk** [comment]
Hey @komealy 👋 Thanks for taking the time to open this. This relates to HashiCorp rotating the release signing key a while back. More information can be found [here](https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570), however, to save you a click, I've confirmed that upgrading to at least Terraform `0.11.15` will resolve the issue (this is ultimately a Terraform thing, rather than a provider issue).

With that information in mind, I'll close this issue as well. If you feel I've done this in error, please do let me know.
