### ISSUE TITLE
Invalid AWS Region: ap-southeast-3

### ISSUE THREAD

**Issue by jbg** [hashicorp/terraform-provider-aws#22252]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.0
on linux_arm64
provider registry.terraform.io/hashicorp/aws v3.69.0

### Affected Resource(s)

`aws_*`

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "ap-southeast-3"
}
```

### Expected Behavior

The provider initialises correctly.

### Actual Behavior

```
│ Error: Invalid AWS Region: ap-southeast-3
│   with provider["registry.terraform.io/hashicorp/aws"]
```

### Steps to Reproduce

1. `terraform apply`

### References

https://aws.amazon.com/blogs/aws/now-open-aws-asia-pacific-jakarta-region/

**Comment by ewbankkit** [comment]
@jbg Thanks for raising this issue.
Until support for the new `ap-southeast-3` Region has been [added to the provider](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/contribution-checklists.md#new-region) you can use the [`skip_region_validation`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#skip_region_validation) argument:

```hcl
provider "aws" {
  region = "ap-southeast-3"

  skip_region_validation = true
}
```

**Comment by ewbankkit** [comment]
The upcoming **v3.70.0** release will use [AWS SDK v1.42.23](https://github.com/aws/aws-sdk-go/releases/tag/v1.42.23) (#22203) which adds `ap-southeast-3` to the list of regions for the standard AWS partition. The `aws_region` data source will then support the new region.

**Comment by aashari** [comment]
@ewbankkit I still can't use `data "aws_region" "current" {}`, it is shown this error
```
│ Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid
│       status code: 403, request id: d8b2cf3a-9f9f-4933-944b-1d5aa308575a
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on backend.tf line 10, in provider "aws":
│   10: provider "aws" {
│
```

here is my code
```
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.70.0"
    }
  }
}

provider "aws" {
  region = "ap-southeast-3"
  skip_region_validation=true
}

data "aws_region" "current" {
}

output "region_name" {
  description = "The name of the selected region."
  value       = data.aws_region.current.id
}
```

I also have tried removing `skip_region_validation=true` attribute but still don't work, i'm using terraform `1.0.0`, can you help elaborate?

**Comment by jbg** [comment]
You probably need to enable the region (as with all new AWS regions). Note that if you run Terraform in a separate AWS account from your resources, you need to enable the region in both accounts.

**Comment by aashari** [comment]
> AWS



> You probably need to enable the region (as with all new AWS regions). Note that if you run Terraform in a separate AWS account from your resources, you need to enable the region in both accounts.

I have enabled the region in my account, all works fine without `data "aws_*"` block

**Comment by jbg** [comment]
We also use `data "aws_region"` and it's working fine in `ap-southeast-3` here. Check that you enabled the STS token endpoint as well as the region.

**Comment by jbg** [comment]
Since `3.70.0` is out I think this can be closed.

**Comment by YiGene** [comment]
you may still get same error on terraform s3, add skip region check resolved this 
terraform {
  backend "s3" {
      skip_region_validation = true
      .....

}

Terraform v1.1.4
