### ISSUE TITLE
Bug with Update Launch template version 

### ISSUE THREAD

**Issue by coopengo-glecomte** [hashicorp/terraform-provider-aws#22264]
## Description

Hello, I found an issue on LT version update. when I apply a change on LT, it's generate a new version and terraform display an error following this version update.

## Versions

 - Terraform: 1.1.1

 - Provider(s): registry.terraform.io/hashicorp/aws v3.70.0

 - Module: terraform-aws-modules/autoscaling/aws

## Reproduction

Steps to reproduce the behavior: Just try to modify a Launch template and terraform apply

## Expected behavior

Apply LT update without error and update default LT version

## Actual behavior

Display the following error message when the parameter "update_default_version" is true :

```
 Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.asg_gitlab_runner_manager.aws_autoscaling_group.this[0] to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .launch_template[0].version: was cty.StringVal("4"), but now cty.StringVal("5").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

If we do a second time a terraform apply we don't have error displayed, but the LT template isn't update

**Comment by ewbankkit** [comment]
@coopengo-glecomte Thanks for raising this issue.
It has already been noticed in #22015. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
