### ISSUE TITLE
terraform init failing when using aws provider 2.70.1

### ISSUE THREAD

**Issue by gnewson** [hashicorp/terraform-provider-aws#22267]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform 0.11.7
AWS provider version 2.70.1

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {                                                                                        
  region  = "${var.region}"                                                                             
  version = "~> 2.0"                                                                                    
} 
```

### Expected Behavior

terraform init should have pulled the latest 2.x aws provider and initialised the directory with it.

### Actual Behavior

The init command failed with the following output

```
06:58:38  Initializing provider plugins...
06:58:38  - Checking for available provider plugins on https://releases.hashicorp.com...
06:58:38  
06:58:38  Error installing provider "aws": openpgp: signature made by unknown entity.
06:58:38  
06:58:38  Terraform analyses the configuration and state and automatically downloads
06:58:38  plugins for the providers used. However, when attempting to download this
06:58:38  plugin an unexpected error occured.
06:58:38  
06:58:38  This may be caused if for some reason Terraform is unable to reach the
06:58:38  plugin repository. The repository may be unreachable if access is blocked
06:58:38  by a firewall.
06:58:38  
06:58:38  If automatic installation is not possible or desirable in your environment,
06:58:38  you may alternatively manually install plugins by downloading a suitable
06:58:38  distribution package and placing the plugin's executable file in the
06:58:38  following directory:
06:58:38      terraform.d/plugins/linux_amd64
```

### Steps to Reproduce

1. `terraform init`

### Important Factoids

Run from a jenkins server against a number of jobs.
As suggested in the error text, this was worked around by copying the 2.70.0 version of the provider into terraform.d/plugins/linux_amd64

**Comment by justinretzolk** [comment]
Hey @gnewson 👋 Thanks for taking the time to open this. This relates to HashiCorp rotating the release signing key a while back. More information can be found [here](https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570), however, to save you a click I've confirmed that upgrading to at least Terraform `0.11.15` will resolve the issue (this is ultimately a Terraform thing, rather than a provider issue).

With that information in mind, I'll close this issue as well. If you feel I've done this in error, please do let me know.

**Comment by gnewson** [comment]
Hi @justinretzolk , thanks for the swift response.  More than happy for this to be closed.
I had a look prior to raising this and found https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512 but didn't follow all of the links so missed the page you shared.

Now to go and discuss, pin the provider or upgrade the terraform version ...

**Comment by Nithya22rc** [comment]
Hi,

also facing the provider issue for terraform.
TF version  “0.11.13” with provider version “2.70.0” for AWS.

error:
Error installing provider "aws": openpgp: signature made by unknown entity.
Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

**Comment by justinretzolk** [comment]
Hi @Nithya22rc 👋 I would indeed expect this to affect `0.11.13` as well; `0.11.15` was the only release from the `0.11.x` series to contain the updated key, as it was the only one in the series to occur after the codecov exposure. Upgrading to `0.11.15` should resolve the error you're seeing as well. Can you test that and let me know if you see further issues?
