### ISSUE TITLE
Order lost in `aws_iam_role` causing endless plan updates due to ordering of principals in `aws_iam_policy_document`

### ISSUE THREAD

**Issue by jw-maynard** [hashicorp/terraform-provider-aws#22274]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v1.1.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.70.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* aws_iam_policy_document

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

locals {
  ingress_account_list = [
    "XXXXXXXXXXXX",
    "YYYYYYYYYYYY",
    "XXXXXXXXXXXX",
  ]
}

data "aws_iam_policy_document" "workspace_ingress_role_trust" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      identifiers = formatlist("arn:aws:iam::%s:root", local.ingress_account_list)
      type        = "AWS"
    }
  }
}

resource "aws_iam_role" "workspace_ingress" {
  name               = "aws_amp_ingest_role"
  assume_role_policy = data.aws_iam_policy_document.workspace_ingress_role_trust.json
}

output "workspace_ingress_role" {
  sensitive = false
  value     = aws_iam_role.workspace_ingress
}
```

### Expected Behavior

When running multiple plans with no changes to the terraform code terraform should detect no changes
### Actual Behavior

When running multiple plans the outputs are updated on every plan due to reordering of the principals

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`
3. `terraform plan`

### References

* #11801
* #21016
* #22259

**Comment by mludvig** [comment]
Same issue described here with `aws_ecr_repository_policy`: https://stackoverflow.com/questions/68870558/make-terraform-ignore-the-order-of-list-items-returned-from-the-service

**Comment by AnthonyFoiani-at** [comment]
Should we continue collecting places where this bites us, or would you prefer independent bugs?

I don't think I've seen this case mentioned yet. (This was in the "changes made outside of Terraform" portion of the output.)

```
  ~ resource "aws_alb" "rollbar_lambda_webhook_handler_alb" {
      + desync_mitigation_mode     = "defensive"
      + drop_invalid_header_fields = false
      + enable_waf_fail_open       = false
        id                         = "arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/rollbar-lambda/deadbeef"
        name                       = "rollbar-lambda"
        tags                       = {}
      + tags_all                   = {}
        # (13 unchanged attributes hidden)


      + subnet_mapping {
          + subnet_id = "subnet-xxxxxxxx6742c23a4"
        }
      + subnet_mapping {
          + subnet_id = "subnet-yyyyyyyyb0c2bf4c7"
        }
      - subnet_mapping {
          - subnet_id = "subnet-xxxxxxxx6742c23a4" -> null
        }
      - subnet_mapping {
          - subnet_id = "subnet-yyyyyyyyb0c2bf4c7" -> null
        }

        # (2 unchanged blocks hidden)
    }
```

**Comment by akloss-cibo** [comment]
Me too.  Many differences in plan reported now that did not report differences in terraform 0.13.

Version info:

Terraform v1.1.4
on linux_amd64
+ provider registry.terraform.io/alexkappa/auth0 v0.26.1
+ provider registry.terraform.io/hashicorp/aws v3.74.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/integrations/github v4.19.2

**Comment by Synohara** [comment]
Hi! I've created a Pull Request to fix this Issue.
https://github.com/hashicorp/terraform-provider-aws/pull/23060

**Comment by hoxu** [comment]
I think #22314 and #22560 are also examples of diffs being shown because AWS APIs don't sort things properly.
