### ISSUE TITLE
Event Subscription fails to create, but only intermittently

### ISSUE THREAD

**Issue by gclough** [hashicorp/terraform-provider-aws#22273]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v1.1.1
on linux_amd64
```

### Affected Resource(s)

* `aws_db_event_subscription`

```
resource "aws_db_event_subscription" "postgres" {
  sns_topic   = aws_sns_topic.alarm_topic.arn
  source_type = "db-instance"
  source_ids  = [aws_db_instance.postgres.id]
  name        = "${aws_db_instance.postgres.id}-instance-subscription"

  event_categories = [
    "failover",
    "failure",
    "deletion",
    "low storage",
    "notification",
    "read replica",
    "recovery",
    "restoration"
  ]
  tags = merge(local.tags, { Name = "${local.db_code_name}-instance_subscription" })
}
```

### Terraform Configuration Files

I can't give a simple test-case, as it only seems to happen when we run a pipeline which creates 10+ databases in parallel.

### Debug Output

https://gist.github.com/gclough/10eab92a43c31b08b4697940166e15f2

### Panic Output

None.

### Expected Behavior

Event subscription should be created, and registered in the state file

### Actual Behavior

Event subscription is created, but is NOT registered in the state file, and fails with this error:

```
Error: Error creating RDS Event Subscription dbname-instance-subscription: InvalidParameterValue: Unable to find an event subscription matching the resource name: arn:aws:rds:us-east-1:123456789012:es:dbname-instance-subscription
	status code: 400, request id: c1b6c330-6219-4fd9-81e6-beea5b87c45b
```

Subsequent terraform plan/apply also fails, because the Event Subscription isn't in the state file, but already exists.  The only workaround is to either manually add it to the state file, or delete it and then plan/apply.

### Steps to Reproduce

It doesn't always fail, and only seems to happen when we are creating 10 databases concurrently.

1. `terraform apply`

### Important Factoids

None.

### References

None.

**Comment by gclough** [comment]
It's anecdotal evidence, but if I run Terraform from the same region as the deployed database, then it seems to be 100% reliable.

I can theorise that there is a small delay between when AWS creates the event subscription, and when it's visible in the catalog for all other regions.  I'm thinking that we could add some logic just before the test which confirms the event subscription exists:

```
for <wait_time> in 1 1 2 3 5 8 13 21
  if <subscription exists> exit for loop
  sleep <wait_time>
```

That way it would wait almost 1 minute for it to appear before it fails, but would not slow it down in the scenario where it's available quickly.

**Comment by jonathan-russo** [comment]
@gclough interestingly enough I am seeing this same bug when creating an event subscription through Python's Boto3.  So it appears to not be related to Terraform but an AWS API issue?

**Comment by gclough** [comment]
@jonathan-russo , thanks for the observation.  It does seem to be an API issue with AWS, but if we put a delay in before we check that it exists after creation, then that should effectively "solve" the problem.  We may never be able to fix the AWS API, as I'm sure the delay is related to data replication somewhere, and is likely inherent in their architecture.
