### ISSUE TITLE
Support `PERSISTENT_2` in `aws_fsx_lustre_file_system`

### ISSUE THREAD

**Issue by jrykr** [hashicorp/terraform-provider-aws#22279]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `aws_fsx_lustre_file_system` resource currently supports the following values for `deployment_type`:

- `SCRATCH_1`
- `SCRATCH_2`
- `PERSISTENT_1`

As of approximately November 2021, AWS introduced the `PERSISTENT_2` deployment type. This introduces a number of new features in FSx for Lustre, including the ability to create many data repository associations for a given file system. Unlike earlier `PERSISTENT_1` data repositories, these associations can be configured to export data back to the source S3 bucket.[^1]

The current resource has `import_path` and `export_path` attributes. These would not be applicable to a `PERSISTENT_2` deployment. For `PERSISTENT_2` file system, its repository associations would need to be configured after the file system is created.

[^1]: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/fsx/create-data-repository-association.html

### New or Affected Resource(s)

* aws_fsx_lustre_file_system
* aws_fsx_lustre_data_repository_association (new)

### Potential Terraform Configuration

```hcl
resource "aws_fsx_lustre_file_system" "example" {
  storage_capacity = 1200
  subnet_ids       = [aws_subnet.example.id]
  deployment_type  = "PERSISTENT_2"
}

resource "aws_fsx_lustre_data_repository_association" "example" {
  file_system_id       = aws_fsx_lustre_file_system.example.id
  file_system_path     = "/example"
  data_repository_path = "s3://${aws_s3_bucket.example.bucket}"
  
  s3 {
    auto_import_policy = "NEW_CHANGED_DELETED"
    auto_export_policy = "NEW_CHANGED_DELETED"
  }  
}
```

### References

* [API Reference: Create Data Repository Association](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/fsx/create-data-repository-association.html)
* [Documentation Revision 2021-11-30](https://docs.aws.amazon.com/fsx/latest/LustreGuide/doc-history.html)
* [Documentation: Persistent file systems](https://docs.aws.amazon.com/fsx/latest/LustreGuide/using-fsx-lustre.html#persistent-file-system)

**Comment by vicyap** [comment]
Hello, I just made a PR for this here: https://github.com/hashicorp/terraform-provider-aws/pull/22291

I worked on this before I noticed you filed this issue so it’s slightly different.
