### ISSUE TITLE
Provider produced inconsistent result after apply error when changing SNS topic resource name

### ISSUE THREAD

**Issue by NicholasPurdy** [hashicorp/terraform-provider-aws#22275]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
terraform v1.1.1 on linux_amd64
hashicorp/aws v3.70.0

### Affected Resource(s)

* aws_sns_topic
### Steps to Reproduce

1. `terraform apply` to create the infrastructure
2. Change the resource name from `old_sns_topic` to `new_sns_topic` on lines 12, 17, and 40.
3. `terraform apply` again to get the error message

### Terraform Configuration Files

```hcl
terraform {
  backend "s3" {
    region = "us-east-1"
    key = "snsbug-main.tfstate"
  }
}

resource "aws_sqs_queue" "my_test_sqs_queue" {
  name = "my_test_sqs_queue"
}

resource "aws_sns_topic" "old_sns_topic" {
  name = "my_sns_topic"
}

resource "aws_sns_topic_subscription" "sqs_subscription" {
  topic_arn = aws_sns_topic.old_sns_topic.arn
  protocol  = "sqs"
  endpoint  = aws_sqs_queue.my_test_sqs_queue.arn
  raw_message_delivery = true
}

resource "aws_sqs_queue_policy" "sns_queue_policy" {
  queue_url = aws_sqs_queue.my_test_sqs_queue.id
  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Id": "sqspolicy",
  "Statement": [
    {
      "Sid": "First",
      "Effect": "Allow",
      "Principal": {
        "Service": "sns.amazonaws.com"
      },
      "Action": "sqs:SendMessage",
      "Resource": "${aws_sqs_queue.my_test_sqs_queue.arn}",
      "Condition": {
        "ArnEquals": {
          "aws:SourceArn": "${aws_sns_topic.old_sns_topic.arn}"
        }
      }
    }
  ]
}
POLICY
}
```

### Actual Behavior
The "old" SNS topic is destroyed, and terraform fails to create the "new" one.
```
aws_sns_topic_subscription.sqs_subscription: Destroying... [id=arn:aws:sns:us-east-1:555555555555:my_sns_topic:3f270f07-2497-4feb-b629-eaab47941f9e]
aws_sns_topic_subscription.sqs_subscription: Still destroying... [id=arn:aws:sns:us-east-1:555555555555:my_s...c:3f270f07-2497-4feb-b629-eaab47941f9e, 10s elapsed]
aws_sns_topic_subscription.sqs_subscription: Still destroying... [id=arn:aws:sns:us-east-1:555555555555:my_s...c:3f270f07-2497-4feb-b629-eaab47941f9e, 20s elapsed]
aws_sns_topic_subscription.sqs_subscription: Still destroying... [id=arn:aws:sns:us-east-1:555555555555:my_s...c:3f270f07-2497-4feb-b629-eaab47941f9e, 30s elapsed]
aws_sns_topic_subscription.sqs_subscription: Still destroying... [id=arn:aws:sns:us-east-1:555555555555:my_s...c:3f270f07-2497-4feb-b629-eaab47941f9e, 40s elapsed]
aws_sns_topic_subscription.sqs_subscription: Still destroying... [id=arn:aws:sns:us-east-1:555555555555:my_s...c:3f270f07-2497-4feb-b629-eaab47941f9e, 50s elapsed]
aws_sns_topic_subscription.sqs_subscription: Destruction complete after 58s
aws_sns_topic.old_sns_topic: Destroying... [id=arn:aws:sns:us-east-1:555555555555:my_sns_topic]
aws_sns_topic.new_sns_topic: Creating...
aws_sns_topic.old_sns_topic: Destruction complete after 0s
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to aws_sns_topic.new_sns_topic, provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

```

### Expected Behavior
Only the terraform resource name is changing, so in the real world, one should probably manually remove and re-import their resources. But the fact that the apply command fails and leaves your infrastructure in a non-functional state is pretty annoying. 

It'd be nice if Terraform could either execute the plan to completion, or detect that the underlying infrastructure has not changed and only the state needs to be updated to account for the new resource name (I'm sure the latter is probably a harder ask).

**Comment by ewbankkit** [comment]
`aws_sns_topic` needs the `d.IsNewResource()` check added - https://github.com/hashicorp/terraform-provider-aws/issues/16796.
