### ISSUE TITLE
fsx ontap Org Distinguished Field Update Causing Replacement of SVM

### ISSUE THREAD

**Issue by khan-belal** [hashicorp/terraform-provider-aws#22286]
There was a typo in the aws_fsx_ontap_storage_virtual_machine resource. The documented field `organizational_unit_distinguished_name` was actually recognized as `organizational_unit_distinguidshed_name`

The typo has been corrected in tf version 3.70, however updating my IaC to use the new value (organizational_unit_distinguished_name) is forcing a replacement of my SVM. Leaving the value "as is" is resulting in a warning when pushing infrastructure.

Replacement is not ideal, as I have already made configuration changes on the SVM.

The expected behaviour should be that terraform recognizes that both values mean the same thing and that no changes are required.

See my example below:

~ self_managed_active_directory_configuration {
              - organizational_unit_distinguidshed_name = "OU=MyOrgDetails" -> null # forces replacement
              + organizational_unit_distinguished_name  = "OU=MyOrgDetails" # forces replacement

**Comment by ewbankkit** [comment]
Relates: #22246.
Relates: #21987.
