### ISSUE TITLE
Resource: aws_elasticsearch_domain - Cannot use gp3 volume type inside

### ISSUE THREAD

**Issue by bursztyn-pl** [hashicorp/terraform-provider-aws#22299]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform version: Terraform v 1.1.0
AWS Provider version: terraform-provider-aws_v3.68.0_x5
### Affected Resource(s)

* aws_elasticsearch_domain

### Debug Output

│ Error: expected ebs_options.0.volume_type to be one of [standard gp2 io1], got gp3
│ 
│   with aws_elasticsearch_domain.opensearch-prod,
│   on main.tf line 45, in resource "aws_elasticsearch_domain" "opensearch-prod":
│   45:     volume_type = "gp3"

### Expected Behavior
Terraform can create AWS elasticsearch with gp3 volume type

### Actual Behavior
volume_type of gp3 is nor supported (only supported are standard (magnetic), gp2 and io1)

### Steps to Reproduce

Set up ebs_options with volume_type = "gp3"

**Comment by mattburgess** [comment]
From the looks of it, ElasticSearch doesn't yet support the GP3 volume type. See https://github.com/aws/aws-sdk-go/blob/v1.42.28/service/elasticsearchservice/api.go#L14812-L14816.

It might be worth you getting in touch with your AWS support rep to see if there are any plans to add such support. Once that support is added to the SDK then the TF provider will automatically support it through the use of that ` VolumeType_Values()` function.

**Comment by justinretzolk** [comment]
Hey @bursztyn-pl 👋 Thank you for taking the time to raise this. As @mattburgess mentioned above, this appears to be a limitation of the underlying SDK, and would be resolved automatically by an update to the SDK to include the `gp3` volume type in the `VolumeType` enum. Since this is a limitation of the underlying SDK, we'll close this issue for now. If the SDK is updated in the future and any additional action is needed on our part, we'd be happy to take a look at this again.
