### ISSUE TITLE
aws_rds_cluster aurora serverless scaling_configuration missing autoscaling timeout value

### ISSUE THREAD

**Issue by tsposato** [hashicorp/terraform-provider-aws#22292]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When utilising aws_rds_cluster with engine_mode as serverless there is an additional scaling_configuration section which comes available. Currently, there is no way to specify the autoscaling timeout value for when timeout_action will trigger. I'm requesting we add an additional field called 'seconds_until_autoscaling_timeout'.

### New or Affected Resource(s)

aws_rds_cluster - scaling_configuration

### Potential Terraform Configuration

```hcl
scaling_configuration {
    auto_pause               = true
    max_capacity             = 256
    min_capacity             = 2
    seconds_until_auto_pause = 300
    timeout_action           = "ForceApplyCapacityChange"
    seconds_until_autoscaling_timeout = 600
```
seconds_until_autoscaling_timeout = proposed new setting - accepts int between 60 and 600 as per below.

### References
According to the Go SDK/API - the documentation is:
```
    // The amount of time, in seconds, that Aurora Serverless tries to find a scaling
    // point to perform seamless scaling before enforcing the timeout action. The
    // default is 300.
    //
    // Specify a value between 60 and 600 seconds.
    SecondsBeforeTimeout *int64 `type:"integer"`
```

**Comment by mikrammo** [comment]
any update on this ? Or any workarround ?
because this feature is very helpful
