### ISSUE TITLE
Move AWS lightsail to its own provider

### ISSUE THREAD

**Issue by brittandeyoung** [hashicorp/terraform-provider-aws#22290]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to recommend that we move AWS lightsail to its own provider, similarly to how this is done for cloudformation. The vastness of AWS services will always be higher voted than lightsail changes.  

I feel that making the aws lightsail it's own provider would allow for faster development and contributions to aws lightsail services. Additionally lightsail has its own suite of services that are constantly being added to.

I personally have a few Aws lightsail pull requests open and would be happy to continue contributing to get more terraform support for aws lightsail.

### New or Affected Resource(s)

* aws_lightsail_XXXXX

### Potential Terraform

```hcl
provider "awslightsail" {} 
```

### References

An example of how lightsail is a separate provider for cloudformation

https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-lightsail

**Comment by brittandeyoung** [comment]
I have already started this process here: 
* https://github.com/DeYoungTech/terraform-provider-awslightsail 
* https://registry.terraform.io/providers/DeYoungTech/awslightsail/latest
I currently have resource parity with existing lightsail resources.

**Comment by armanm** [comment]
@brittandeyoung I'm so glad I came across this issue. I was just about to pull up my sleeves and propose changes to bring support for Lightsail Containers. Thank you for this suggestion and also following up with it.

**Comment by brittandeyoung** [comment]
I have been working on brining more Lightsail resources to the official AWS provider. This issue is no longer needed.
