### ISSUE TITLE
r/aws_kinesis_firehose_delivery_stream: Deprecate root-level `s3_configuration` and add nested `s3_configuration` blocks in-line with API

### ISSUE THREAD

**Issue by anGie44** [hashicorp/terraform-provider-aws#22309]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Both the AWS documentation and our resource documentation (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream#s3_configuration) note that `s3_configuration` is deprecated and `extended_s3_configuration` should be used instead for the case of `s3` destinations. For other available destinations such as `elasticsearch` and to avoid confusion with the deprecation notice, it's possible to include an `s3_configuration` nested block per applicable destination.

### Expected Changes
The changes would include:
1. deprecate the root-level `s3_configuration` as expected (later to be removed in 4.0 milestone)
2. add `s3_configuration` blocks where needed to match the [upstream API ](https://docs.aws.amazon.com/firehose/latest/APIReference/API_CreateDeliveryStream.html#API_CreateDeliveryStream_RequestSyntax)
  a. in `elasticsearch_configuration`
  b. in `http_endpoint_configuration` 
  c. in `redshift_configuration`
  d. in `splunk_configuration`

### Affected issues
* https://github.com/hashicorp/terraform-provider-aws/issues/7997
* https://github.com/hashicorp/terraform-provider-aws/issues/7953

**Comment by umpa385** [comment]
agreed same issue here as well, can't use extended_s3_configuration with splunk_configuration.

**Comment by johnsonaj** [comment]
Closed in #31138
