### ISSUE TITLE
Updating default_tags after apply causes the provider to fail for aws_vpc

### ISSUE THREAD

**Issue by xorxsan** [hashicorp/terraform-provider-aws#22301]
Provider fails with an error after adding the following tag to `default_tags`:

`Creation = timestamp()`

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.2
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.70.0

### Affected Resource(s)

* aws_vpc

### Terraform Configuration Files

```hcl
provider "aws" {
  region  = "eu-west-2"

  default_tags {
    tags = {
      Team     = "My Team"
      Reason   = "A reason"
    }
  }
}

resource "aws_vpc" "my_vpc" {
  cidr_block           = "10.3.0.0/19"
  enable_dns_support   = false
  enable_dns_hostnames = false

  tags = {
    Name = "My VPC"
  }
}
```

### Debug Output

https://gist.github.com/xorxsan/b90a0399426860eed0f9ba295eccd280

### Expected Behavior

VPC should have been updated with the new tag.

### Actual Behavior

Terraform fails with the following messages:

│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for aws_vpc.my_vpc to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "Creation" has appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for aws_vpc.my_vpc to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "Reason" has appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for aws_vpc.my_vpc to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "Team" has appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Steps to Reproduce

1. `terraform apply`
2. Update the script to add the following tag on the provider's `default_tags` property:
    `Creation = timestamp()`
3. Run `terraform apply` again. 

### Important Factoids

None

### References

None

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by xorxsan** [comment]
In fact this is also happening on the first apply with the following configuration:
```hcl
provider "aws" {
  region  = "eu-west-2"

  default_tags {
    tags = {
      Team     = "My Team"
      Reason   = "A reason"
      Creation = timestamp()
    }
  }
}

resource "aws_vpc" "my_vpc" {
  cidr_block           = "10.3.0.0/19"
  enable_dns_support   = false
  enable_dns_hostnames = false

  tags = {
    Name = "My VPC"
  }
}
```

**Comment by ewbankkit** [comment]
@xorxsan Thanks for raising this issue.
It has already been noticed in #19583. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by ewbankkit** [comment]
@xorxsan As `timestamp()` will be re-evaluated every time a `terraform plan` is run (and have a distinct value), you may want to look at the Terraform [time provider](https://registry.terraform.io/providers/hashicorp/time/latest/docs) to generate a single, static timestamp value.

**Comment by xorxsan** [comment]
I tried your suggestion like the following:
```hcl
resource "time_static" "creation_time" {}

provider "aws" {
  region  = "eu-west-2"
  profile = "default@admin"

  default_tags {
    tags = {
      Team     = "My Team"
      Reason   = "A reason"
      Creation = time_static.creation_time.rfc3339
    }
  }
}

resource "aws_vpc" "my_vpc" {
  cidr_block           = "10.3.0.0/19"
  enable_dns_support   = false
  enable_dns_hostnames = false

  tags = {
    Name = "My VPC"
  }
}
```

but I got the same result :(

**Comment by xorxsan** [comment]
Doing some more tests I found out that if I remove the `tags` from the `aws_vpc` resource, then it works fine (even with my first set up, that is using the `timestamp()` function.

**Comment by bassmanitram** [comment]
There are a large number of similar reports of this, the most active in terms of comments appears to be https://github.com/hashicorp/terraform-provider-aws/issues/19583
