### ISSUE TITLE
SQS support of dead-letter queue (DLQ) redrive to source queue

### ISSUE THREAD

**Issue by calvernaz** [hashicorp/terraform-provider-aws#22318]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_sqs_queue

### References

* https://aws.amazon.com/about-aws/whats-new/2021/12/amazon-sqs-dead-letter-queue-management-experience-queues/

**Comment by ewbankkit** [comment]
@calvernaz Thanks for raising this issue.
It has already been noticed in #22249. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by ewbankkit** [comment]
This has been addressed via #22282 and will be released in **v3.71.0** of the Terraform AWS Provider.
