### ISSUE TITLE
aws_launch_template does not properly trigger updates of dependent objects when a change occurs

### ISSUE THREAD

**Issue by jw-maynard** [hashicorp/terraform-provider-aws#22329]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_launch_template

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

resource "aws_launch_template" "eks_minion_node_groups" {
  for_each               = var.worker_node_group_configurations
  name_prefix            = "${aws_eks_cluster.cluster.name}-${substr(each.key, 0, 8)}-"
  image_id               = each.value.use_bottlerocket ? local.ami_id.bottlerocket : local.ami_id.al2
  ebs_optimized          = true
  instance_type          = each.value.instance_type
  key_name               = var.keyname
...
}

resource "aws_eks_node_group" "eks_minion_node_group" {
  for_each        = aws_launch_template.eks_minion_node_groups
  cluster_name    = aws_eks_cluster.cluster.name
  node_group_name = "${aws_eks_cluster.cluster.name}-${each.key}"
  node_role_arn   = aws_iam_role.minion_role_node_groups.arn
  subnet_ids      = aws_eks_cluster.cluster.vpc_config[0].subnet_ids

  launch_template {
    id      = each.value.id
    version = each.value.latest_version
  }
...
}
```

### Panic Output

N/A

### Expected Behavior

Whenever anything is done to the LT that would cause AWS to create a new version of the LT then the `latest_version` variable should be updated to "known after apply" so that downstream resources that depend on the LT version can be properly updated.

Also, when `update_default_version` is `true` the provider should not cause the following error:
```
Error: Provider produced inconsistent final plan
When expanding the plan for module.kubernetes_cluster.aws_eks_node_group.eks_minion_node_group["frontend"] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .launch_template[0].version: was cty.StringVal("9"), but now cty.StringVal("10"). This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Actual Behavior

The `latest_version` seems to be updated behind the scenes without indicating that it will be changed in the plan. If you rerun a `plan` a second time the downstream resources notice the change and report that they will be updated. This is inconsistent behavior with how Terraform is expected to work.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

There is a good discussion about what might be happening with @apparentlymart  in the Terraform Core issue linked below.

### References

* [Terraform Core Issue #30227](https://github.com/hashicorp/terraform/issues/30227)
* Possibly #19411

**Comment by ewbankkit** [comment]
@jw-maynard Thanks for raising this issue.
It has already been noticed in #22015. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
