### ISSUE TITLE
Multi-attach is now enabled on AWS EBS for io2

### ISSUE THREAD

**Issue by jkstenzel95** [hashicorp/terraform-provider-aws#22326]
https://aws.amazon.com/about-aws/whats-new/2020/12/multi-attach-support-now-available-on-amazon-ebs-provisioned-iops-volume-type-io2/

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
terraform version
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.70.0

Your version of Terraform is out of date! The latest version
is 1.1.2. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* aws_ebs_volume

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform
terraform {
    backend "s3" { 
        bucket          = locals.BUCKET_NAME
        key             = "global/s3/terraform.tfstate"
        region          = "us-east-2"

        dynamodb_table  = locals.DYNAMODB_NAME
        encrypt         = true
    }
    
    required_providers {
        aws = {
            source  = "hashicorp/aws"
            version = "~> 3.70"
        }
    }

    required_version = ">= 1.0.11"
}

provider aws {
    profile = "default"
    region  = "${var.server_region}"
}
```

### Expected Behavior

```
resource "aws_ebs_volume" "volume" {
    availability_zone = "us-east-2b"
    size = 200
    type = "io2"
    multi_attach_enabled = true
    iops = 200

    tags = {
        Name = "jks-gs-blahblahblah-data-volume"
    }
}
```
Should not fail because of the type=io2 and multi_attach_enabled=true

### Actual Behavior

```
│ Error: 'multi_attach_enabled' must not be set when 'type' is 'io2'
│
│   with module.game-servers.module.ark_cluster.module.shared_data_volume.module.volume.aws_ebs_volume.volume,
│   on game-servers/modules/volume/main.tf line 3, in resource "aws_ebs_volume" "volume":
│    3: resource "aws_ebs_volume" "volume" {
```

### Steps to Reproduce

1. Create a similar volume with a backend of your choice. 
2. terraform init
3. terraform plan

### Important Factoids

Executing commands on Running on WSL

### References

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

**Comment by ewbankkit** [comment]
@jkstenzel95 Thanks for raising this issue.
It has already been noticed in #19751. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
