### ISSUE TITLE
dimensions is not supported in "aws_cloudwatch_log_metric_filter"

### ISSUE THREAD

**Issue by akramdhiabii** [hashicorp/terraform-provider-aws#22323]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v1.1.2 on linux_amd64
provider registry.terraform.io/hashicorp/aws v3.36.0

### Affected Resource(s)

resource "aws_cloudwatch_log_metric_filter" 

### Terraform Configuration Files

```
resource "aws_cloudwatch_log_metric_filter" "app-metrics" {
  name           = "XXXX"
  pattern        = "YYYY"
  log_group_name = aws_cloudwatch_log_group.frontend_logs.name 
  metric_transformation {
    name      = "WWWW"
    namespace = "${local.prefix}-metrics"
    value     = "ZZZZ"
    dimensions ={
      // the value is a metric filter pattern
      Tag    = "$.tag"
      Action = "$.meta.action"
    }
  }
}
```
### Expected Behavior

It should create CW metrics resources.

### Actual Behavior
`````
Error: Unsupported argument
│ 
│   on cloudwatch-metrics.tf line 383, in resource "aws_cloudwatch_log_metric_filter" "app-metrics":
│  383:     dimensions ={
│ 
│ An argument named "dimensions" is not expected here.
`````
### Steps to Reproduce

 terraform plan -target aws_cloudwatch_log_metric_filter.app-metrics

### References

[https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_metric_filter](url)

**Comment by wedge-jarrad** [comment]
Support for that argument was added in v3.44.0. Looks like you're using 3.36.0. #19625

**Comment by justinretzolk** [comment]
Hey @akramdhiabii 👋 As @wedge-jarrad mentioned above, it looks like you'll need to upgrade to at least `v3.44.0` in order to use the `dimensions` argument. Can you upgrade your provider version and let us know if that resolves the issue?

**Comment by akramdhiabii** [comment]
Yes that has been done thanks.
