### ISSUE TITLE
Allow aws:PrincipalOrgPaths as a possible condition key to aws_cloudwatch_event_permission

### ISSUE THREAD

**Issue by Kermie5000** [hashicorp/terraform-provider-aws#22327]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow aws:PrincipalOrgPaths as a possible condition key to aws_cloudwatch_event_permission

### New or Affected Resource(s)

aws_cloudwatch_event_permission

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by sjonpaulbrown** [comment]
According to the [AWS documentation ](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_Condition.html)for the `PutPermission` api call, it seems that the only supported condition key is `aws:PrincipalOrgID`. Until AWS supports this, I do not think this will be possible.

https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/events/permission.go#L100

**Comment by justinretzolk** [comment]
Hey @Kermie5000 👋 Thank you for taking the time to raise this. As mentioned above, this appears to be a limitation of the underlying API. Given that's the case, we'll close this issue for now. If the underlying API is updated to support `aws:PrincipalOrgPaths` in the future, we'd be happy to take another look.
