### ISSUE TITLE
AWS Inspector2 Enable Service Feature 

### ISSUE THREAD

**Issue by rhelwatkar** [hashicorp/terraform-provider-aws#22330]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Editor's Note

The AWS link provided by op in references is for "Inspector V2" or "Inspector2". I've changed the issue title to clarify that we're talking about 2 since none of this make sense in context of v1.

### Description

AWS has recently launched new aws Inspector, we can enable the service via CLI.

This feature is missing and can be added to enable Inspector Service.

### New or Affected Resource(s)

* aws_inspector_enable

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

resource "aws_inspector_enable" "enable_service" {
    account_id = []
    client_token = ""
    resource_types = []
}
```

### References
AWS Documentation page - https://awscli.amazonaws.com/v2/documentation/api/latest/reference/inspector2/enable.html

**Comment by autarchprinceps** [comment]
It's a little more complicated. Yes, you can just enable it, but you'd typically either set it on root account, or set a delegate on the root account, and then in that root/security account you associate other accounts.
Not that simple enable in the current account shouldn't also work, but it would be great to see the actual main use case thought about too.

**Comment by bismark** [comment]
Would also be nice to have support for managing suppression rules.

**Comment by james-green-affinity** [comment]
This feature definitely should support the ability be able to delegate within the Terraform to an Audit account.

**Comment by snemetz** [comment]
This should be changed to supporting inspector2.
Doing only 1 api of the newer inspector2 service will not be useful
I need all of these to just get started
```
aws inspector2 enable [--account-ids X] --resource_types "ECR"
aws inspector2 enable-delegated-admin-account --delegated-admin-account-id ID
aws inspector2 update-organization-configuration --auto-enable ec2=false,ecr=true
```

**Comment by breathingdust** [comment]
Hi all 👋 Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

**Comment by YakDriver** [comment]
### `aws_inspector2_organization_configuration`

* [DescribeOrganizationConfiguration](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/inspector2#Client.DescribeOrganizationConfiguration)
* [UpdateOrganizationConfiguration](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/inspector2#Client.UpdateOrganizationConfiguration)

### `aws_inspector2_delegated_admin_account`

* [DisableDelegatedAdminAccount](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/inspector2#Client.DisableDelegatedAdminAccount)
* [EnableDelegatedAdminAccount](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/inspector2#Client.EnableDelegatedAdminAccount)
* [GetDelegatedAdminAccount](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/inspector2#Client.GetDelegatedAdminAccount)
* [ListDelegatedAdminAccounts](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/inspector2#Client.ListDelegatedAdminAccounts)

### `aws_inspector2_enabler`

* [Disable](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/inspector2#Client.Disable)
* [Enable](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/inspector2#Client.Enable)

**Comment by ajardan** [comment]
Are there any news when this is going to be released ? Is there anything that we can help to speed things up ?
