### ISSUE TITLE
r/aws_instance.metadata_options should support http_protocol_ipv6 in order to enable IPv6 IMDS

### ISSUE THREAD

**Issue by nodakai** [hashicorp/terraform-provider-aws#22332]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`r/aws_instance.metadata_options` should support `http_protocol_ipv6 = "enabled"` _etc._ in order to enable IPv6 IMDS

### New or Affected Resource(s)

* `r/aws_instance`

### Potential Terraform Configuration

```hcl
resource "aws_instance" "worker" {
  ...
    metadata_options {
    http_protocol_ipv6 = "enabled"
  }
}
```

### References

* https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-ipv6-only-subnets-and-ec2-instances/
> Accessing local instance services over IPv6 Endpoints
...
> --metadata-options "HttpEndpoint=enabled,HttpProtocolIpv6=enabled"

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#metadata-options
* https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#ModifyInstanceMetadataOptionsInput

https://github.com/hashicorp/terraform-provider-aws/blob/393773acd4b794fc8056e9e65bfa987f3cc5682a/internal/service/ec2/instance.go#L1556

* `r/aws_launch_template.metadata_options` already seems to support it, I'm going to try it as a workaround: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#http_protocol_ipv6
  * but `r/aws_instance.metadata_options` seems more flexible and convenient

**Comment by ewbankkit** [comment]
Relates: #20768.
Relates: #20796.

**Comment by michal-kosinski** [comment]
I found this issue while configuring the ALB with instances in ipv6 only subnets. Are you aware of an existing issue for allowing setting IP address = ipv6 type during creation of TG with Target Type = IP?
