### ISSUE TITLE
DMS task modification lifecycle

### ISSUE THREAD

**Issue by chrisjharding** [hashicorp/terraform-provider-aws#2236]
When a DMS task is updated with either task settings or table mappings whilst it is still in the running state in AWS, terraform will fail. 

```
bash-3.2$ terraform -v
Terraform v0.10.8
```

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_dms_replication_task

### Debug Output
```
* aws_dms_replication_task.oms_odbms_dynamo: InvalidResourceStateFault: Replication Task cannot be modified while it is running state
	status code: 400, request id: xxxxx
```

### Expected Behavior
It should stop the task, modify and restart/resume.

### Actual Behavior
Tries to modify a running task and fails.

### Steps to Reproduce
Setup a dms task and ensure it is in the running phase, then run `terraform apply`

Looking for advice on this @stack72 @radeksimko . Is it agreed that this should be the intended behavior? If so, what would be the best way of implementing this? I presume it would follow something similar to the dms replication instance provisioning where it waits for a state change before marking that resource as complete. I've attached a first attempt PR.

**Comment by ramziyassine** [comment]
I noticed there is a fork solving this maybe https://github.com/chrisjharding/terraform-provider-aws/pull/1/files I am very interested to see if this is something that will be part of the 12 release? Thank you

**Comment by nmodhipallise** [comment]
Any updates on this?

**Comment by bryantbiggs** [comment]
4 years, oof

**Comment by olegflo** [comment]
I second this initiative or any change that would allow changing task state via TF.

**Comment by toptaljj** [comment]
seems likely that if we know we are going to apply a change to a task that we know we need to stop it to apply it and then attempt to resume it.  whether to resume or restart could be an option, or restart a fallback (like the cli handles it).  stop task, modify task, resume task = feasible workflow.

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

**Comment by fermezz** [comment]
I'm very interested in this feature. I will try to pull off a PR if nobody has anything on their way. Please reach out if you do.

**Comment by fermezz** [comment]
Hi, @breathingdust. First of all, sorry for the ping. I know how annoying can those be :). I'd really appreciate some feedback on my PR, which I consider to be ready to be reviewed. I have performed quite a lot of testing and adapted automated acceptance tests for this case in particular as well.
