### ISSUE TITLE
Bug with Update Launch template versionrraform-provider-aws - Bug with Update Launch template version

### ISSUE THREAD

**Issue by venkikonda** [hashicorp/terraform-provider-aws#22374]
Hello, I found an issue on LT version update. when I apply a change on LT, it's generate a new version and terraform display an error following this version update.

kindly look into it and suggest us or provide solution if we have

Versions:

Terraform: ">= 0.13"
Provider(s): registry.terraform.io/hashicorp/aws "~> 3.0"
Module: terraform-aws-modules/autoscaling/aws

Reproduction:
Steps to reproduce the behavior: Just try to modify a Launch template and terraform apply

Expected behaviour:

Apply LT update without error and update default LT version

Actual behavior:

Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.asg_gitlab_runner_manager.aws_autoscaling_group.this[0] to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .launch_template[0].version: was cty.StringVal("4"), but now cty.StringVal("5").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by venkikonda** [comment]
Kindly look into it.
or if we have any workaround

**Comment by altcatalin** [comment]
Hi @venkikonda, please check #22015. The issue seems to be resolved in v3.71.0 (unreleased).

**Comment by venkikonda** [comment]
Thanks for update.
I used provider version 3.67 fixed LT version issue.
let us know once v3.71 released and usable.

**Comment by ewbankkit** [comment]
@venkikonda Thanks for raising this issue.
It has already been noticed in #22015. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
