### ISSUE TITLE
aws_s3_object_copy fails to copy objects bigger than 5GB

### ISSUE THREAD

**Issue by mgstoyanov** [hashicorp/terraform-provider-aws#22379]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
terraform -v
Terraform v1.1.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v3.70.0
```
### Affected Resource(s)

```
* aws_s3_object_copy
```
### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_s3_object_copy" "this" {
  bucket = "somebucket"
  key    = "somedestination/hugefile"
  source = "samebucket/source/hugefile"
}

```

### Debug Output

```
╷
│ Error: error copying S3 object (bucket: REDACTED; key: REDACTED; source: REDACTED): InvalidRequest: The specified copy source is larger than the maximum allowable size for a copy source: 5368709120
│       status code: 400, request id: YD54NVSC4QMWCKBE, host id: qYr+JsGyUxAPU/ZWC+SqpEMQmiPkKAMwest/fZ6VGPjNwL7OKv5Rd5okAH2MIZp620r0/NQPcEQ=
│
│   with aws_s3_object_copy.this
│   on main.tf line 94, in resource "aws_s3_object_copy" "this":
│   94: resource "aws_s3_object_copy" "this" {
│
╵
Releasing state lock. This may take a few moments...

```

### Expected Behavior

Objects of any size up to 5TB to be copied

### Actual Behavior

Objects bigger than 5GB are not copied

### Steps to Reproduce

Upload a file over 5GB to s3 and attempt to copy it with the aws_s3_object_copy resource

1. `terraform apply`

### References

https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.CopyObject
https://docs.aws.amazon.com/AmazonS3/latest/userguide/CopyingObjectsMPUapi.html

* #0000

**Comment by ewbankkit** [comment]
Relates: #788.
