### ISSUE TITLE
launch_template dependency not recognised in autoscaling_group.  Trying to trigger instance_refresh on version change

### ISSUE THREAD

**Issue by crabby345** [hashicorp/terraform-provider-aws#22390]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.2
hashicorp/aws v.3.70.0

### Affected Resource(s)

* aws_launch_template
* aws_autoscaling_group

### Terraform Configuration Files

```hcl
resource "aws_launch_template" "foobar" {
  name_prefix   = "foobar"
  image_id      = "ami-1a2b3c"
  instance_type = "t2.micro"
}

resource "aws_autoscaling_group" "bar" {
  availability_zones = ["us-east-1a"]
  desired_capacity   = 1
  max_size           = 1
  min_size           = 1

  launch_template {
    id      = aws_launch_template.foobar.id
    version = aws_launch_template.foobar.latest_version
  }
}
```

This configuration is used to trigger an instance_refresh on update of launch_template by it causing a config change on autoscaling group.  If the version = "$Latest" is aws parameter setting causes the autoscaling group to always reference latest, but doesn't trigger the instance refresh on change.

### Debug Output

This was causing an inconsistent result in cty.String for the launch_template version param in autoscaling.  A few executions generated to paste the result here haven't triggered the error.  It still ignores the change until the second apply, but doesn't actually trigger a go error.

Will paste in a comment if I get the error again

### Expected Behavior

When plan detects a change to aws_launch_template it should create a dependent change in aws_autoscaling_group and the verison value should be <known_on_apply>.  

### Actual Behavior

aws_autoscaling_group reads the pre-plan state for launch_template.version and uses that for the plan.  The change in aws_launch_template does not trigger a change in aws_autoscaling_group.

At apply time an inconsistent state results because the actual value of version in aws_launch_template.latest_version is not the value applied.

### Steps to Reproduce

1. Change a value in aws_launch_template eg. userdata
2. `terraform apply`
3. Plan will detect change in aws_launch_template only, and only look to change that one resource
4. `y`
5. On apply the inconsistent result will occur as autoscaling_group.launch_template.latest_version needs to change.

### Workaround

A further apply will read the updated value in aws_launch_template and trigger the change in aws_autoscaling_group on 2nd apply.  This requires multiple executions to achieve consistent state so is undesirable, particular given this is a frequently changing part of our configuration (and one we want to trigger from an automates codebuild/packer pipeline as gold build ami's change.

### References

There are a number of issues raised with launch_templates giving inconsistent results in different use cases.  I couldn't find any about those issues reflecting in autoscaling, not sure if they're related.

**Comment by ewbankkit** [comment]
@crabby345 Thanks for raising this issue.
It has already been noticed in #22015. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by crabby345** [comment]
Apologies.  I thought I'd done a decent search!  Clearly not
