### ISSUE TITLE
Argument "support_ipv6" is not expected in "transit_gateway_vpc_attachment"

### ISSUE THREAD

**Issue by christian-vdz** [hashicorp/terraform-provider-aws#22393]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v1.1.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v3.70.0
```

### Affected Resource(s)

* aws_ec2_transit_gateway_vpc_attachment

### Terraform Configuration Files

```terraform
# EC2 Transit Gateway
resource "aws_ec2_transit_gateway" "tgw" {
  description = "tgw"
}

# VPC
module "vpc_1" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 3.0"

  name = "vpc-1"
  cidr = "10.1.0.0/16"

  azs             = ["eu-west-1a"]
  private_subnets = ["10.1.0.0/24"]

  enable_ipv6                                    = true
  private_subnet_assign_ipv6_address_on_creation = false
  private_subnet_ipv6_prefixes                   = [1]
  create_egress_only_igw                         = false
}

# VPC attachement
resource "aws_ec2_transit_gateway_vpc_attachment" "vpc_1" {
  depends_on = [aws_ec2_transit_gateway.tgw, module.vpc_1]

  vpc_id     = module.vpc_1.vpc_id
  subnet_ids = module.vpc_1.private_subnets

  support_ipv6 = enable

  transit_gateway_id                              = aws_ec2_transit_gateway.tgw.id
  transit_gateway_default_route_table_association = false
  transit_gateway_default_route_table_propagation = false
}
```
Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

```terraform
2022-01-03T17:16:53.967+0100 [ERROR] AttachSchemaTransformer: No provider config schema available for provider["terraform.io/builtin/terraform"]
2022-01-03T17:16:54.234+0100 [ERROR] vertex "aws_ec2_transit_gateway_vpc_attachment.vpc_1" error: Unsupported argument
╷
│ Error: Unsupported argument
│ 
│   on vpc.tf line 26, in resource "aws_ec2_transit_gateway_vpc_attachment" "vpc_1":
│   26:   support_ipv6 = enable
│ 
│ An argument named "support_ipv6" is not expected here.
```

### Expected Behavior

Terraform should have created the ressource with `support_ipv6` set to enable.

### Actual Behavior

Terraform had the preview error

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by wedge-jarrad** [comment]
Looks like you have it backwards. It's named `ipv6_support` :)

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_transit_gateway_vpc_attachment#ipv6_support

**Comment by christian-vdz** [comment]
> Looks like you have it backwards. It's named `ipv6_support` :)
> 
> https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_transit_gateway_vpc_attachment#ipv6_support

Thanks, you are right.. 
My bad ! Sorry, I didn't see it.
