### ISSUE TITLE
Refactor: remove id from the top level of resource and data source schemas

### ISSUE THREAD

**Issue by GlennChia** [hashicorp/terraform-provider-aws#22404]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Proposed changes

- Remove `id` from the top-level of resource and data source schemas.

### Affected Resource(s)

From a search through the provider code, there are several resoureces that specify `id` in the top-level of their respective `schemas`. This issue proposes a simple refactor to remove those top-level `id` attributes.

Here are some examples (**non-exhaustive**) of the affected resources.

* [data.aws_api_gateway_api_key.test_key](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/apigateway/api_key_data_source.go)
* [data.aws_api_gateway_vpc_link.vpc_link](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/apigateway/vpc_link_data_source.go)
* [data.aws_cloudfront_cache_policy](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/cloudfront/cache_policy_data_source.go)
* [aws_route53_resolver_dnssec_config](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/route53resolver/dnssec_config.go)

**Comment by ewbankkit** [comment]
An explicit `id` attribute should be superfluous for resources but unfortunately you may find that there are data sources where `id` is being used as an input argument (so `Optional` and `Computed` are both true). In these cases, `id` is not the ideal name for the argument (should be `<resource type>_id`) but we should retain for backwards compatibility.

**Comment by GlennChia** [comment]
Thanks for the explanation. From a search through the provider code, there are only 2 resources that have the ID in schema. I'll raise a PR for these

1. [aws_route53_resolver_dnssec_config](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/route53resolver/dnssec_config.go)
2. [aws_route53_resolver_firewall_rule_group](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/route53resolver/firewall_rule_group.go)
