### ISSUE TITLE
resource/aws_vpc_ipam_pool_cidr_allocation fix validation parameters for `netmask_length` and styling updates

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform-provider-aws#22401]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_vpc_ipam_pool_cidr_allocation

A couple of misses were discovered in the big PR with various IPAM resources.
- `ValidateFunc` on netmask_length should match the API valid values, see [context](https://github.com/hashicorp/terraform-provider-aws/pull/22341/files#r775554658)
- CRUD function names were not updated to match the new service organizational structure. They are being unnecessarily exported: https://github.com/hashicorp/terraform-provider-aws/blob/f445f5e1980a8b4a6581b2964b8ba70b80330128/internal/service/ec2/vpc_ipam_pool_cidr_allocation.go#L20

### References

* https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md

**Comment by rahul-amzn** [comment]
looking into it
