### ISSUE TITLE
EKS: add support to kubernetes_network_config for ipFamily

### ISSUE THREAD

**Issue by todd-dsm** [hashicorp/terraform-provider-aws#22407]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

RFE to get IPv6 addressing support for pods. 

![image](https://user-images.githubusercontent.com/2463935/148125552-d6046c0a-1727-4e60-a03f-74fe6df5e372.png)

Perhaps it could be added as an argument to the existing construct:

```hcl
resource "aws_eks_cluster" "kube-test" {
  name     = "kube-test"
...
  kubernetes_network_config {
    ipFamily = "IPv6"                      <-- please add this bit
  }
```

_NOTE: this is very much emergent so it's understandable that it could take some time to implement._

### New or Affected Resource(s)

Assuming the IPv6 networking has been enabled, the only affected resources should be the `aws_eks_cluster` above.

```hcl
resource "aws_vpc" "vpc_network" {
  cidr_block                       = var.host_cidr
  enable_dns_hostnames             = true
  enable_dns_support               = true
  assign_generated_ipv6_cidr_block = true <-- here

  tags = {
    "Name"                                      = var.project
  }
}

# Create Subnets within the VPC
resource "aws_subnet" "vpc_network" {
  count                           = var.minDistSize
  assign_ipv6_address_on_creation = true <-- here

  # Get AZs from Region
  availability_zone = data.aws_availability_zones.available.names[count.index]
  cidr_block        = cidrsubnet(var.host_cidr, 2, count.index)
  ipv6_cidr_block   = cidrsubnet(aws_vpc.vpc_network.ipv6_cidr_block, 8, count.index) <-- here
  vpc_id            = aws_vpc.vpc_network.id
...
}
```

### Potential Terraform Configuration

```hcl
resource "aws_eks_cluster" "kube-test" {
  name     = "kube-test"
  role_arn = aws_iam_role.kube-test-cluster.arn

  vpc_config {
    security_group_ids = [aws_security_group.kube-test-cluster.id]
    subnet_ids         = aws_subnet.vpc_network.*.id
  }

  kubernetes_network_config {
    ipFamily = "IPv6"
  }
```

### References

The `awscli` supports it (in the [video]) - although this appears to be an early/internal release of the `awscli`; the latest publically available version does not have an `aws ipv6` sub-command. 
The `aws eks create-cluster` does support `kubernetesNetworkConfig` but does not support the `ipFamily` bit.
[Plumi supports] it; not sure how that works if it's not in the `awscli`/api though 🤔 

[video]:https://youtu.be/MvKmNdx8Osw?t=878
[Plumi supports]:https://www.pulumi.com/registry/packages/aws-native/api-docs/eks/cluster/#clusterkubernetesnetworkconfig

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.42.28](https://github.com/aws/aws-sdk-go/releases/tag/v1.42.28).

**Comment by mKeRix** [comment]
I'm trying to write a pull request for this currently - first time contributing, but the change should be small enough hopefully.

**Comment by mKeRix** [comment]
Pull request #22485 should address this.

**Comment by todd-dsm** [comment]
Just a personal comment...

I love Open Source software/sensibilities for exactly this reason. 

You guys are the greatest.

**Comment by breathingdust** [comment]
Hi @todd-dsm! 👋  We release every Thursday.
