### ISSUE TITLE
Unable to pass multiple bootstrap actions in aws emr using Terraform

### ISSUE THREAD

**Issue by amamidwar** [hashicorp/terraform-provider-aws#22416]
I am trying to pass multiple bootstrap actions in aws emr using terraform with below code block -

 **_bootstrap_action {[
    {
      path = "s3://${var.emrS3LogUri}/folder1/folder2/emr1.sh"
      name = "emr1"
      args = ["s3://${var.emrS3LogUri}/folder1/certs/", var.s3BucketRegion]
    },
    {
      path = "s3://${var.emrS3LogUri}/folder1/folder2/emr2.sh"
      name = "emr2"
    }
  ]}_**

But I am getting below error after execution of **terraform init** command -

 **| Error: Argument or block definition required
│
│ On ../modules/terraform-aws-emr/main.tf line 298: An argument or block definition is required here.**

Also, I have tried below workarounds to solve this issue, but no luck.
Like,
1. Added only square brackets with multiple bootstrap actions, like **bootatrap_action = [{}]** & **bootstrap_action {[]}**, but it is failing at same **terraform init**.
2. Added '=' sign after bootstrap action to read arguments. This time, it works till **terraform init**. But when I am executing **terraform plan**, it is giving me error as : 

**│ Error: Unsupported argument
│
│   on ../modules/terraform-aws-emr/main.tf line 298, in resource "aws_emr_cluster" "emr":
│  298:   bootstrap_action = [
│
│ An argument named "bootstrap_action" is not expected here. Did you mean to define a block of type "bootstrap_action"?**

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request

**Comment by DrFaust92** [comment]
Hi @amamidwar.

It should probably look more like this:

```

bootstrap_action {
path = "s3://${var.emrS3LogUri}/folder1/folder2/emr1.sh"
name = "emr1"
args = ["s3://${var.emrS3LogUri}/folder1/certs/", var.s3BucketRegion]
}

bootstrap_action {
path = "s3://${var.emrS3LogUri}/folder1/folder2/emr2.sh"
name = "emr2"
}
```

**Comment by amamidwar** [comment]
@DrFaust92 Thank you. It worked.
