### ISSUE TITLE
Problem changes on launch template does not trigger changes on aws eks managed nodes

### ISSUE THREAD

**Issue by joaolgn1985** [hashicorp/terraform-provider-aws#22419]
I'm investigate why changes on launch template does not trigger changes on aws eks managed nodes

In my example I'm adding a new Security Group and when I apply the change manually using `terragrunt apply` it will provision the new Security Group, but it doesn't add to Auto Scaling Groups under Security Group IDs and it also doesn't apply the new version to Launch Template.
In this case I will have to manually rerun the `terragrunt apply` a second time for it to apply these changes.

The bad thing is that all my flow runs on top of a pipeline and I can't keep running the terragrunt twice manually, it has to be done automatically.
Do you have any solution for my problem or have you gone through a similar situation?
Am I forgetting something?

Regards,
João Lobo

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ewbankkit** [comment]
@joaolgn1985 Thanks for raising this issue.
It has already been noticed in #22015. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
