### ISSUE TITLE
Set public ECR repository alias via ecrpublic_repository 

### ISSUE THREAD

**Issue by pollosp** [hashicorp/terraform-provider-aws#22412]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When  I'm using the resource `ecrpublic_repository` looks like terraform is not able to set an alias for or get the alias from output.

Option im talking about via UI:

![Screenshot 2022-01-05 at 12 36 41](https://user-images.githubusercontent.com/1783343/148211820-40cca573-ba23-419f-92c6-d394063b8dd2.png)

### New or Affected Resource(s)

* ecrpublic_repository

### Potential Terraform Configuration

```hcl
resource "aws_ecrpublic_repository" "public" {
  provider = aws.us_east_1

  repository_name = "xxx-wow"
  repository_alias= "my_company_name" ### <--- would be nice to have this interface
    
  catalog_data {
    about_text        = "My company testing public containers repo"
    architectures     = ["ARM","ARM 64","x86-64"]
    description       = "Description"
    operating_systems = ["Linux"]
    usage_text        = "XXXXXXXXXXXXXXXX"
  }
}
```

**Comment by mattburgess** [comment]
Aliases are set on the registry, not on individual repositories within it, not that my pedantry particularly helps you :)

Reading https://docs.aws.amazon.com/AmazonECR/latest/public/public-registry-settings.html](https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html) alongside https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.42.28/service/ecrpublic#ECRPublic suggests that one can't interact very much with the registry itself through the API; as the docs note, both the public and private registries are "provided" to an account, they're not things that one creates/deletes yourself.

Those docs also strongly hint that the custom alias can only be requested via the console and goes through some kind of manual verification/validation process.

If you have an AWS support contract, it might be worth you speaking to them about whether there are plans for supporting automation of custom registry aliases. Alternatively, perhaps just raising an issue against https://github.com/aws/containers-roadmap/issues might get some traction?

As it stands currently, I don't think there's a reasonable way for Terraform to support this. But, I'm not a Hashicorp dev so don't speak for them at all and I'd love to be proved wrong!

As for Terraform not supporting getting the alias from an output, there looks to be just enough support in the API to support that, but it would probably makes sense to be done via a `aws_ecrpublic_registry` data source. If the maintainers here are happy, I don't mind giving implementing that a go, but we'd probably need to figure out what your use case is for such a thing to ensure it behaves correctly.
