### ISSUE TITLE
cannot create beanstalk with ALB (elbv2)

### ISSUE THREAD

**Issue by tcirakyopploans** [hashicorp/terraform-provider-aws#22423]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform -v
Terraform v0.13.7
+ provider registry.terraform.io/-/local v2.1.0
+ provider registry.terraform.io/hashicorp/aws v3.70.0
+ provider registry.terraform.io/hashicorp/local v2.1.0

### Affected Resource(s)

* aws_elastic_beanstalk_environment

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_elastic_beanstalk_environment" "resource" {
  application         = "name"
  name                = "name"
  solution_stack_name = var.elasticbeanstalk_solution_stack_name
...
setting {
    namespace = "aws:elasticbeanstalk:environment"
    name      = "EnvironmentType"
    value     = "LoadBalanced"
  }

  setting {
    namespace = "aws:elasticbeanstalk:environment"
    name      = "LoadBalancerType"
    value     = "application"
  }

  setting {
    namespace = "aws:elbv2:listener:default"
    name      = "Protocol"
    value     = "http"
  }
  setting {
    namespace = "aws:elbv2:listener:443"
    name      = "Protocol"
    value     = "http"
  }
}
```

### Debug Output

```
2022/01/05 11:26:02 [ERROR] eval: *terraform.EvalSequence, err: ConfigurationValidationException: Configuration validation exception: Invalid option specification (Namespace: 'aws:elbv2:listener', OptionName: 'ListenerProtocol'): Unknown configuration setting.
        status code: 400, request id: 6a3d6488-991c-4567-b380-af4c579ee8fa

Error: ConfigurationValidationException: Configuration validation exception: Invalid option specification (Namespace: 'aws:elbv2:listener', OptionName: 'ListenerProtocol'): Unknown configuration setting.
        status code: 400, request id: 6a3d6488-991c-4567-b380-af4c579ee8fa
```

### Expected Behavior

Terraform should have sent the request with the Protocol OptionName

### Actual Behavior

Terraform sent the request with the invalid ListenerProtocol OptionName

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @tcirakyopploans 👋 Thank you for taking the time to file this. So that we have all of the necessary information to look into this, can you update the issue description with the full (redacted as necessary) debug logs?
