### ISSUE TITLE
New EC2 Reserved Instances resource

### ISSUE THREAD

**Issue by algotech-informatique** [hashicorp/terraform-provider-aws#22422]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It will be very fine to create an EC2 Reserved Instances resources

### New or Affected Resource(s)

Exemple : 

aws_instance_reserved

### References

[AWS-API-REF](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/OperationList-query-ec2.html)

Reserved Instances

- AcceptReservedInstancesExchangeQuote
- CancelReservedInstancesListing
- CreateReservedInstancesListing
- DeleteQueuedReservedInstances
- DescribeReservedInstances
- DescribeReservedInstancesListings
- DescribeReservedInstancesModifications
- DescribeReservedInstancesOfferings
- GetReservedInstancesExchangeQuote
- ModifyReservedInstances
- PurchaseReservedInstancesOffering

**Comment by YakDriver** [comment]
In thinking about full support for EC2 reserved instances, I'm going to plunk down this list here for future reference:

* [AcceptReservedInstancesExchangeQuote](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.AcceptReservedInstancesExchangeQuote)
* [CancelReservedInstancesListing](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.CancelReservedInstancesListing)
* [CreateReservedInstancesListing](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.CreateReservedInstancesListing)
* [DeleteQueuedReservedInstances](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DeleteQueuedReservedInstances)
* [DescribeReservedInstances](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DescribeReservedInstances)
* [DescribeReservedInstancesListings](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DescribeReservedInstancesListings)
* [DescribeReservedInstancesModifications](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DescribeReservedInstancesModifications)
* [DescribeReservedInstancesOfferings](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DescribeReservedInstancesOfferings)
* [GetReservedInstancesExchangeQuote](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.GetReservedInstancesExchangeQuote)
* [ModifyReservedInstances](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.ModifyReservedInstances)
* [PurchaseReservedInstancesOffering](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.PurchaseReservedInstancesOffering)
