### ISSUE TITLE
Support AWS CloudTrail Lake

### ISSUE THREAD

**Issue by christophetd** [hashicorp/terraform-provider-aws#22434]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS just announced https://aws.amazon.com/blogs/mt/announcing-aws-cloudtrail-lake-a-managed-audit-and-security-lake/

It would be great to have Terraform support for it.

### References

https://aws.amazon.com/blogs/mt/announcing-aws-cloudtrail-lake-a-managed-audit-and-security-lake/

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.42.28](https://github.com/aws/aws-sdk-go/releases/tag/v1.42.28) - #22430.

**Comment by bschaatsbergen** [comment]
Would love to see this being implemented!

**Comment by bschaatsbergen** [comment]
Done, #22490 is ready for review.

**Comment by bschaatsbergen** [comment]
Released under 4.2.0

**Comment by DrFaust92** [comment]
Closed via #22490
