### ISSUE TITLE
data_source/aws_vpc_ipam_pool acceptance tests are failing in CI due to parallelism

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform-provider-aws#22438]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_vpc_ipam_pool

The data source for IPAM pool searches is failing because it currently returns the first pool it finds that matches its criteria. Due to low availability of `filters`, its finding the incorrect pool from other CI tests and then the DS `arn` does not match the API returned `arn`. 

- [ ] add an implicit reference `ipam_pool_id = aws_vpc_ipam_pool.test.id` [here](https://github.com/hashicorp/terraform-provider-aws/blob/63d5a9c8cf8cc82ca8e88f77b426b40b2e448786/internal/service/ec2/vpc_ipam_pool_data_source_test.go#L69) so the DS finds the specific one we built in CI
- [ ] remove the explicit `depends_on` from the acc test config
- [ ] add an error to the resource if it finds more than 1 pool based on search criteria, [example](https://github.com/hashicorp/terraform-provider-aws/blob/63d5a9c8cf8cc82ca8e88f77b426b40b2e448786/internal/service/ec2/vpc_data_source.go#L174)

This change will make this DS less useful for accounts with more than 1 pool but that is currently due to a limitation with the API

**Comment by jpalan-amazon** [comment]
@drewmullen I picked this up.
