### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Pranava29** [hashicorp/terraform-provider-aws#22433]
The documentation on https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/secretsmanager_secret_version can be improved to avoid confusion. 
The `example` resource is being referred again in the data construct. 

![Screenshot from 2022-01-06 13-15-38](https://user-images.githubusercontent.com/10139286/148347425-2ab53939-65ac-4935-bc09-4d5122b7195c.png)

**Comment by kamilturek** [comment]
I believe it can be closed.

**Comment by Pranava29** [comment]
Thanks for addressing this. I'm closing the issue
