### ISSUE TITLE
FSx Error: expected per_unit_storage_throughput to be one of [12 40 50 100 200], got 125

### ISSUE THREAD

**Issue by olileach** [hashicorp/terraform-provider-aws#22446]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

➜  terraform terraform -v
Terraform v1.1.2
on darwin_arm64
provider registry.terraform.io/hashicorp/aws v3.70.0

### Affected Resource(s)

*  aws_fsx_lustre_file_system

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {
  region = "us-east-1"
}

resource "aws_fsx_lustre_file_system" "fsx-filesystem-1" {
  import_path      = "s3://bucket-us-east-1"
  storage_capacity = 1200
  storage_type = "SSD"
  per_unit_storage_throughput = "125"
  deployment_type = "PERSISTENT_1"
  subnet_ids       = ["subnet-xxxxx"]
}
```

### Debug Output

Here is the output of the plan

```
➜  terraform terraform plan
╷
│ Error: expected per_unit_storage_throughput to be one of [12 40 50 100 200], got 125
│
│   with aws_fsx_lustre_file_system.fsx-filesystem-1,
│   on fsx.tf line 19, in resource "aws_fsx_lustre_file_system" "fsx-filesystem-1":
│   19:   per_unit_storage_throughput = "125"
```

### Expected Behavior

AWS Provider should be able to except the new FSx options being rolled out in AWS, starting with us-east-1

Throughput per unit of storage Info
Throughput (MB/s) per unit of storage (TiB)
125 MB/s/TiB
250 MB/s/TiB
500 MB/s/TiB
1000 MB/s/TiB

### Actual Behavior

Did not except my value of 125 as it's not an expected option ([12 40 50 100 200])

### Steps to Reproduce

1. Take the example tf file above.
2. `terraform plan | apply`

**Comment by oliverleach** [comment]
If I run terraform using an expected config, it does create the FSx File system using the latest options available in that region.

```
resource "aws_fsx_lustre_file_system" "fsx-filesystem-1" {
  import_path      = "s3://bucket-us-east-1"
  storage_capacity = 1200
  storage_type = "SSD"
  per_unit_storage_throughput = "100"
  deployment_type = "PERSISTENT_1"
  subnet_ids       = ["subnet-xxxx"]
}```

What gets deployed in the UI:

Throughput per unit of storage = 100 MB/s/TiB
Total throughput = 120 MB/s

Seems like this is a cosmetic but breaking change.

**Comment by olileach** [comment]
It looks like these values are hardcoded, coming from https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/fsx/lustre_file_system.go#L144 

```
			"per_unit_storage_throughput": {
				Type:     schema.TypeInt,
				Optional: true,
				ForceNew: true,
				ValidateFunc: validation.IntInSlice([]int{
					12,
					40,
					50,
					100,
					200,
				}),
			},
```
