### ISSUE TITLE
Even though configured "Region is required", when provider configuration is in module.

### ISSUE THREAD

**Issue by amritpalnagrame** [hashicorp/terraform-provider-aws#22459]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```sh
terraform -v
```
> Terraform v1.1.2
> on darwin_amd64
> + provider registry.terraform.io/hashicorp/aws v3.70.0
> + provider registry.terraform.io/hashicorp/azurerm v2.46.1
> + provider registry.terraform.io/hashicorp/google v4.5.0

### Affected Resource(s)

* provider configuration

### Terraform Configuration Files

- config.tf
```hcl
terraform {
  required_version = "~> 1.1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }

    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 2.46.0"
    }

    google = {
      source  = "hashicorp/google"
      version = "~> 4.5.0"
    }
  }
}
```
- main.tf
```hcl
module "aws" {
  source = "./aws"
}
```
- aws/config.tf
```hcl
provider "aws" {
  region = "ap-south-1"
}

# Special AWS provider
provider "aws" {
  region = "us-east-1"
  alias  = "northern-virginia"
}
```
- aws/route53_zone.tf
```hcl
resource "aws_route53_zone" "amritpalnagrame" {
	name         = "amritpalnagra.me"
	comment      = "Root domain for amritpalnagra.me"
}
```

### Debug Output

https://gist.github.com/amritpalnagrame/a16c24b3702a288f5c957890ba4c02cd

### Expected Behavior
- Resource creation in configured region

### Actual Behavior
- Error
```
╷
│ Error: Missing required argument
│
│ The argument "region" is required, but was not set.
╵
```

### Steps to Reproduce
1. Configure credentials for provider.

1. `terraform apply`

### Important Factoids
- Already getting correct error in case region is not configured.
```
╷
│ Error: Missing required argument
│
│   on aws/config.tf line 2, in provider "aws":
│    2: provider "aws" {
│
│ The argument "region" is required, but no definition was found.
╵
```

### References

* #9989

**Comment by justinretzolk** [comment]
Hey @amritpalnagrame 👋 Thank you for taking the time to file this! I copied your sample configuration directly (aside from the domain, which I swapped for one I own) and ran a `terraform apply` and was not able to reproduce this. I noticed in the issue you linked in the references that there were some comments about running into this due to moving parts the configuration to different modules, and things like that -- have you done anything like that, or is this configuration being run for the first time?

**Comment by amritpalnagrame** [comment]
Hello @justinretzolk 👋

I was trying to re-structure large code base into modules, when I came across this error message.
Then I wrote this code specified here, to check the reasoning.
It turns out that I cannot use provider configuration inside of module.
I was able to work around the error by setting environment variable like:
```sh
export AWS_DEFAULT_REGION="ap-south-1"
```
So, it seems like if provider configuration file is inside a module then terraform wouldn't initialise it or something like that.
Then later I faced very similar issue with `azurerm` provider as well.
So, may be it's expected behaviour that I am not aware of.
If so, then I believe this issue is good to be closed.

**Comment by justinretzolk** [comment]
Hey @amritpalnagrame 👋 It sounds like you're running into some of the things that are described in the [Providers Within Modules](https://www.terraform.io/language/modules/develop/providers) documentation; I agree that the refactor probably played a part in the errors you ran into. I'll leave this issue open for now, in case that document doesn't clarify things for you. If you read over that and feel comfortable with me closing it, I'd be happy to do so.

**Comment by amritpalnagrame** [comment]
Hello @justinretzolk 👋
Sorry, for delayed response.
Thank you for providing the link 👍.

Sorry 😞, I should have read the docs before creating issue.
