### ISSUE TITLE
expected origin.0.custom_origin_config.0.origin_read_timeout to be in the range (1 - 60), got 180

### ISSUE THREAD

**Issue by MrC0ns1st3nt** [hashicorp/terraform-provider-aws#22469]
When running Terraform Apply we see:

expected origin.0.custom_origin_config.0.origin_read_timeout to be in the range (1 - 60), got 180. I believe this was originally fixed back in 2017, but reintroduced in 3.71.0

The same Terraform executed yesterday using 3.70.0 works as expected in our CloudFront module.

**Comment by ewbankkit** [comment]
@MrC0ns1st3nt Thanks for raising this issue.
This has been fixed via #22461 which will be released in **v3.72.0** of the Terraform AWS Provider.
