### ISSUE TITLE
Codebuild project update in gov cloud gives unsupported operation error with 3.71.0

### ISSUE THREAD

**Issue by cm94242-work** [hashicorp/terraform-provider-aws#22473]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
terraform -v
Terraform v1.1.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.71.0
```

### Affected Resource(s)

* aws_codebuild_project

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_iam_role" "example" {
  name = "example"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "codebuild.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
}

resource "aws_codebuild_project" "example" {
  name          = "test-project"
  description   = "test_codebuild_project"
  build_timeout = "5"
  service_role  = aws_iam_role.example.arn

  artifacts {
    type = "NO_ARTIFACTS"
  }

  environment {
    compute_type                = "BUILD_GENERAL1_SMALL"
    image                       = "aws/codebuild/standard:1.0"
    type                        = "LINUX_CONTAINER"
    image_pull_credentials_type = "CODEBUILD"

  }

  source {
    type            = "GITHUB"
    location        = "https://github.com/mitchellh/packer.git"
    git_clone_depth = 1

    git_submodules_config {
      fetch_submodules = true
    }
  }

  source_version = "master"
}
```

### Debug Output

https://gist.github.com/cm94242-work/f7472997282c6215644bbd31451dad89

### Expected Behavior

I should be able to idempotently apply a codebuild project and it should complete without error

### Actual Behavior

On *updates*, I get the following error in gov cloud:

```
│ Error: Error updating CodeBuild project (arn:aws-us-gov:codebuild:us-gov-west-1:XXXXXXXXXX:project/test-project) visibility: InvalidInputException: Unknown Operation UpdateProjectVisibility

```

### Steps to Reproduce

1. `terraform apply` in gov cloud
2. This worked the first time, subsequent applications give the above error

### Important Factoids

I think the key here is that it is gov cloud.  It lags behind commercial, but maybe it'd be possible to disable this update visibility API call when it isn't supported

### References

* #0000

**Comment by DrFaust92** [comment]
From what i see from the debug log, we probably need to change the "visibility" field to be computed as its not being returned in govcloud /:

**Comment by diamondlee7** [comment]
I am also having this issue. I attempted to add `project_visibility = "PRIVATE"` to my codebuild terraform and it did not work. Following this issue.

**Comment by estebane-frb** [comment]
Does anyone have a workaround? Does downgrading to a previous terraform version help? I downgraded the aws provider version and still get the same issue. However since the first terraform apply run worked fine but subsequent runs gave this error, I feel that this will happen with any terraform version.

**Comment by ejohn20** [comment]
I downgraded to provider version 3.70.0 and was able to get our deployment working again.

**Comment by estebane-frb** [comment]
Does anyone know whether this was resolved with the latest release? Tested it with v. 4.4 and the error is no longer showing up

**Comment by fdamstra** [comment]
This appears to only happen on the _second_ apply. First apply works correctly. @estebane-frb , can you confirm whether your codebuild state is still working on subsequent applies?

**Comment by geofflancaster** [comment]
I got around this by ignoring the visibility changes

`lifecycle {
  ignore_changes = [project_visibility]
}`

**Comment by skgnova007** [comment]
We observed the same issue for the china region as well, and ignoring changes helped there.
