### ISSUE TITLE
Network Firewall Rule Group allow ip sets and port sets variables for Source/Dest IP and Ports 

### ISSUE THREAD

**Issue by kpsudhakar31** [hashicorp/terraform-provider-aws#22483]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Network Firewall Rule Group allows to use ip set and port set variables to be used as part of Source/Destination IP and Source/Destination Port. Need this feature via terraform as well.

### New or Affected Resource(s)

Resource: aws_networkfirewall_rule_group

### Potential Terraform Configuration

```hcl
resource "aws_networkfirewall_rule_group" "example3" {
  capacity = 100
  name     = "example3"
  type     = "STATEFUL"
  rule_group {
    rule_variables {
      ip_sets {
        key = "WEBSERVERS_HOSTS"
        ip_set {
          definition = ["10.0.0.0/16", "10.0.1.0/24", "192.168.0.0/16"]
        }
      }
      ip_sets {
        key = "EXTERNAL_HOST"
        ip_set {
          definition = ["1.2.3.4/32"]
        }
      }
      port_sets {
        key = "HTTP_PORTS"
        port_set {
          definition = ["443", "80"]
        }
      }
    }
    rules_source {
      stateful_rule {
        action = stateful_rule.value["action"]
        header {
          destination       =   "$EXTERNAL_HOST"
          destination_port  =  "$HTTP_PORTS"
          protocol          =  TLS
          direction         =  both
          source_port       =  ANY
          source            =  "$WEBSERVERS_HOSTS"
        }
        rule_option {
          keyword    = "sid:1"
        }
       }
      }
    }
  }
  tags = {
    Tag1 = "Value1"
    Tag2 = "Value2"
  }
}
```

### References

https://docs.aws.amazon.com/network-firewall/latest/APIReference/API_RuleVariables.html

* #0000

**Comment by justinretzolk** [comment]
Hey @kpsudhakar31 👋 Thank you for taking the time to file this issue. To clarify, are you looking specifically at using the `rule_variables` for the `destination`, `destination_port`, and `source` arguments for `aws_networkfirewall_rule_group.example3.rule_group.rules_source.stateful_rule.header`?

Assuming so, I took a look over the [API documentation](https://docs.aws.amazon.com/network-firewall/latest/APIReference/API_Header.html) as well as the [Go SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/networkfirewall/#Header), which both seem to indicate that the required values are string formatted CIDR blocks. Perhaps I'm misunderstanding, but based on that, it doesn't seem that the API supports using the rule variables here. Can you also provide a bit of clarification around your mentioning that this is possible outside of Terraform?

**Comment by kpsudhakar31** [comment]
@justinretzolk  - Yes thats right. I wanted to use ip sets variable for Src/Dest IP and port sets for Src/Dest Port. After reviewing the documentation, I believe its API is not available yet. Wish its supported!! Thanks a lot for the quick reply, Justin!! Much Appreciated!

**Comment by justinretzolk** [comment]
Hey @kpsudhakar31 👋 Thanks for confirming! Since this looks like it is indeed an API limitation at this point, we'll close this issue for now. If the API is updated to allow this in the future, we'd be happy to take another look.
