### ISSUE TITLE
Unable to update `aws_mskconnect_custom_plugin`

### ISSUE THREAD

**Issue by bryantbiggs** [hashicorp/terraform-provider-aws#22481]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.71.0
```

### Affected Resource(s)

* aws_mskconnect_custom_plugin

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket" "example" {
  bucket = "example"
}

resource "aws_s3_bucket_object" "example" {
  bucket = aws_s3_bucket.example.id
  key    = "debezium.zip"
  source = "debezium.zip"
}

resource "aws_mskconnect_custom_plugin" "example" {
  name         = "debezium-example"
  content_type = "ZIP"
  location {
    s3 {
      bucket_arn = aws_s3_bucket.example.arn
      file_key   = aws_s3_bucket_object.example.key
    }
  }
}
```

### Expected Behavior

- Able to update the connect custom plugin

### Actual Behavior

- Unable to modify/update custom plugin

### Steps to Reproduce

1. `terraform apply`
2. Update the plugin description & re-apply => will throw an error upon trying to update about name conflict

### Important Factoids

None

### References

- https://awscli.amazonaws.com/v2/documentation/api/latest/reference/kafkaconnect/index.html

ℹ️ - Note: this appears to be an issue that is more for the upstream AWS API but posting here since I assume others will stumble across this issue as well (and for tracking when they hopefully release the update/delete API endpoints)

### [Update 2022.03.26]

- Delete functionality implemented with https://github.com/hashicorp/terraform-provider-aws/pull/23544 - issue has been updated to capture just missing update functionality

**Comment by 1968mnelson** [comment]
Any updates on this issue? Im seeing the same behavior...were constrained to >v4 aws tf provider BUT I tested with v4/6 and still unable to delete the plugin. As reported above...TF thinks its deleted BUT doesn NOT get deleted

**Comment by bryantbiggs** [comment]
I believe this is now resolved with #23544 - correct @gungoren?

Reference: https://github.com/hashicorp/terraform-provider-aws/pull/23544/files#diff-36021aaf158e45b92c6321627663f4d9d45e3156f74fd73eb07e70086e108079R2

**Comment by gungoren** [comment]
- Delete function implemented.
- Update functionality is not exists in aws sdk for custom_plugin.

**Comment by bryantbiggs** [comment]
Thanks for the info - updated issue to remove `delete` and focus on just `update`

**Comment by gungoren** [comment]
There is no update feature for custom_plugin. For this reason, neither the aws console nor the sdk has this feature.

**Comment by bryantbiggs** [comment]
ah ok, I guess I'll just close this out for now then. thanks

**Comment by 1968mnelson** [comment]
Yep fwiw the worker configuration resource is the same… in fact you can’t
even delete the worker config from the console. No cli methods to do so
Feels like AWS kinda rushed this one out the door
