### ISSUE TITLE
Version 3.71: error creating EC2 Subnet: InvalidParameter: The parameter ipv6Native is not recognized

### ISSUE THREAD

**Issue by aswad-finaccel** [hashicorp/terraform-provider-aws#22498]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.71.0

### Affected Resource(s)

* aws_subnet

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  version = "= 3.71"
}

resource "aws_subnet" "test" {
  vpc_id     = "vpc-xxx"
  cidr_block = "172.31.80.0/20"
}
```

### Debug Output

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_subnet.test will be created
  + resource "aws_subnet" "test" {
      + arn                                            = (known after apply)
      + assign_ipv6_address_on_creation                = false
      + availability_zone                              = (known after apply)
      + availability_zone_id                           = (known after apply)
      + cidr_block                                     = "172.31.80.0/20"
      + enable_dns64                                   = false
      + enable_resource_name_dns_a_record_on_launch    = false
      + enable_resource_name_dns_aaaa_record_on_launch = false
      + id                                             = (known after apply)
      + ipv6_cidr_block_association_id                 = (known after apply)
      + ipv6_native                                    = false
      + map_public_ip_on_launch                        = false
      + owner_id                                       = (known after apply)
      + private_dns_hostname_type_on_launch            = (known after apply)
      + tags_all                                       = (known after apply)
      + vpc_id                                         = "vpc-xxx"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_subnet.test: Creating...

Error: error creating EC2 Subnet: InvalidParameter: The parameter ipv6Native is not recognized
        status code: 400, request id: xxx

  on main.tf line 5, in resource "aws_subnet" "test":
   6: resource "aws_subnet" "test" {

```

### Expected Behavior

AWS subnet should be created without error.

### Actual Behavior

Failed with error as above.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Using older version ie `3.70` did not produce any error and the subnet resource was created successfully. So the issue is only on version `3.71`

**Comment by ewbankkit** [comment]
@aswad-finaccel Thanks for raising this issue.
Which AWS Partition (Commercial, China, US GovCloud etc.) are you using?

**Comment by ewbankkit** [comment]
If the `Ipv6Native` parameter is not supported in some AWS Partitions then the solution would be to only set the parameter on subnet creation if it's `true`: https://github.com/hashicorp/terraform-provider-aws/blob/a3692e015f5623d6da40c232293ac6c029e8c6b0/internal/service/ec2/subnet.go#L147-L153

**Comment by aswad-finaccel** [comment]
I am using new region `ap-southeast-3`. Do you mean, this parameter `Ipv6Native`, depends on which region we are using. I will do some test with other regions tomorrow. Thanks for the info.

**Comment by aswad-finaccel** [comment]
I tested with older region `ap-southeast-1` (Singapore), version 3.71 works fine. Seems like this new region `ap-southeast-3` (Jakarta) still does not support ipv6 subnets, as stated in following link:
https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-ipv6-only-subnets-and-ec2-instances/

I wonder if the code could be modified so that if we do not provide `ipv6_native` parameter then it will be ignored rather than set to false. Therefore we can use newer version of this provider in regions which still does not support ipv6 subnets.

**Comment by aashari** [comment]
thanks @aswad-finaccel for raising this issue, reverting back to 3.70 solved for now, looking forward for this changes to be released
