### ISSUE TITLE
Terraform for AWS Resource Group unable to have multi Tag Filter 

### ISSUE THREAD

**Issue by veronicalim** [hashicorp/terraform-provider-aws#22504]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform 0.13
### Affected Resource(s)

* aws_resourcegroups_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
variable "workstream_names" {
type = list
default = ["Tester","Development"]
}

variable "env_list" {
type = list
default = ["DEV","SIT"]
}

resource "aws_resourcegroups_group" "resource-group" {
count = length(var.workstream_names)
name = "${var.workstream_names[count.index]}-${var.env_list}"

resource_query {
query = <<JSON
{
"ResourceTypeFilters": ["AWS::AllSupported"],
"TagFilters": [
{
"Key": "Workstream",
"Values": ["${var.workstream_names[count.index]}"]
},
{
"Key": "Environment",
"Values": ["${var.env_list[count.index]}"]
},
]
}
JSON
}
}
```

### Debug Output

~ resource_query {
~ query = <<~EOT
{
"ResourceTypeFilters": ["AWS::AllSupported"],
"TagFilters": [
{
"Key": "Workstream",
"Values": ["Tester"]
- }
+ },
+ {
+ "Key": "Environment",
+ "Values": ["SIT"]
+ },
]
}
EOT
type = "TAG_FILTERS_1_0"
}
}
### Expected Behavior

Terraform can applied and have both "Environment" and "Workstream" tag filter at resource group. I've tested via UI - this can be done but from terraform I cannot make it.
### Actual Behavior

Error: error updating resource query for resource group (resource-group): BadRequestException: Query not valid: Query format not valid: check JSON syntax
### Steps to Reproduce

1. `Create terraform files as above`
2. `terraform apply`

### References

I'm also trying to have workstream map with environment variable to be like this:
["Tester","DEV"]
["Tester","SIT"]
["Development","DEV"]
["Development","SIT"]

I've followed #22263 and managed to get the expected output however when I put to the resource group terraform it keep returning invalid JSON syntax

https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/API_GetResources.html

* #0000

**Comment by justinretzolk** [comment]
Hey @veronicalim 👋 Thank you for taking the time to raise this issue. Before going to deep into testing this, I took a look at the JSON for the resource query and it looks like you have a trailing here that might be what's causing the error to be thrown:

```json
{
  "Key": "Environment",
  "Values": ["${var.env_list[count.index]}"]
},
```

**Comment by hansmohob** [comment]
Yes this is the issue, I noticed this too. I tested after fix and works fine.

```
resource_query {
query = <<JSON
{
"ResourceTypeFilters": ["AWS::AllSupported"],
"TagFilters": [
{
"Key": "Workstream",
"Values": ["${var.workstream_names[count.index]}"]
},
{
"Key": "Environment",
"Values": ["${var.env_list[count.index]}"]
}
]
}
JSON
}
}
```

**Comment by veronicalim** [comment]
Thanks @justinretzolk  and @hansmohob for spotting that !

After I removed the trailing, terraform can be run however it still not working as per expected as I tried to have the mapping to be like this :
["Tester","DEV"]
["Tester","SIT"]
["Development","DEV"]
["Development","SIT"]

Currently based on that I got like this:
["Tester","DEV"]
["Development","SIT"]

Any advise to achieve that mapping? 

Appreciate your help!

**Comment by justinretzolk** [comment]
Hey @veronicalim I think [this document](https://www.terraform.io/language/functions/setproduct#finding-combinations-for-for_each) might be just what you're looking for!
