### ISSUE TITLE
aws_ecs_service does not update service after v3.68.0 upgrade

### ISSUE THREAD

**Issue by timomeinen** [hashicorp/terraform-provider-aws#22508]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

* Terraform v1.1.3
* terraform-provider-aws 3.68.0

### Affected Resource(s)

* aws_ecs_service

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ecs_service" "bridge-service" {
  name = "bridge-service"
  tags = merge(
    var.tags,
    tomap({ git = var.git_commit_hash_short })
  )

  launch_type     = "FARGATE"
  cluster         = aws_ecs_cluster.bridge-cluster.arn
  task_definition = aws_ecs_task_definition.ecs-bridge-task-definition.arn

  deployment_maximum_percent         = 100
  deployment_minimum_healthy_percent = 0
  desired_count                      = 1
  force_new_deployment               = true

  network_configuration {
    assign_public_ip = false
    security_groups  = [aws_security_group.bridge.id]
    subnets          = [var.private_subnet_1_id, var.private_subnet_2_id]
  }
}
```
### Expected Behavior

We want to force a new deployment as stated in the documentation, because the docker image tag always is :latest. For this we simulate a change in the resource with the tag `git` that contains the current git commit hash.

Up to and including version 3.67.0 this worked fine.

### Actual Behavior

After upgrading to 3.68.0 the resource is shown as changed, but no service update is triggered in AWS ECS.

### Steps to Reproduce

1. Create ECS and use a stable tag name as Docker image: For example :latest
2. Set `force_new_deployment = true`
3. `terraform apply`
4. Note: This will deploy the current version of the Docker image
4. Change tag value of aws_ecs_service
5. `terraform apply`
6. No new deployment is triggered although resource is modified

**Comment by justinretzolk** [comment]
Hey @timomeinen 👋 Thank you for taking the time to file this issue. So that we have all of the necessary information in order to look into this, can you update the issue description with the, redacted as necessary, debug logs?

**Comment by timomeinen** [comment]
Hi @justinretzolk, Thank you very much for your help. Highly appreciated. I have created the two log files - one working (v.3.67) and one failing (v.3.71). I can see that with v.3.67 the ECS is updated:

```
[INFO]  Starting apply for module.test-xxx.aws_ecs_service.bridge-service
[DEBUG] module.test-xxx.aws_ecs_service.bridge-service: applying the planned Update change
[INFO]  provider.terraform-provider-aws_v3.67.0_x5: 2022/01/11 22:33:49 [DEBUG] Updating ECS Service (arn:aws:ecs:eu-central-1:xxx:service/avi-test-ecs-xxx--bridge-cluster/avi-test-ecs-xxx--bridge-service): {
  Cluster: "arn:aws:ecs:eu-central-1:xxx:cluster/avi-test-ecs-xxx--bridge-cluster",
  ForceNewDeployment: true,
  NetworkConfiguration: {
    AwsvpcConfiguration: {
      AssignPublicIp: "DISABLED",
      SecurityGroups: ["sg-xxx"],
      Subnets: ["subnet-xxx","subnet-xxx"]
    }
  },
  Service: "arn:aws:ecs:eu-central-1:xxx:service/avi-test-ecs-xxx--bridge-cluster/avi-test-ecs-xxx--bridge-service"
}: timestamp=2022-01-11T22:33:49.172+0100
```

And in v.3.71 the last [INFO] line is missing:
```
[INFO]  Starting apply for module.test-xxx.aws_ecs_service.bridge-service
[DEBUG] module.test-xxx.aws_ecs_service.bridge-service: applying the planned Update change
```

Unfortunately, I am a little bit unsure of posting the logs as a public gist - as I don't want to publish secrets or credentials unintentionally. Is it possible to send you the logs (or gist URL) on a different means?

**Comment by trevorrea** [comment]
@timomeinen - I'm not sure of the exact behaviour of that flag but there are a number of other issues raised about it. Have you thought of doing this?

Note this is not a complete example - but if you modify the task definition and set a spurious environment variable to the value of var.git_commit_hash_short then when the value of that changes a new ECS task definition will be created and as a consequence of that the ECS service will update.  It would accomplish the same thing you are aiming for in a slightly different way

```
resource "aws_ecs_task_definition" "ecs-bridge-task-definition" {
  family = "${var.environment}-ecs-bridge-task-definition"
  container_definitions = jsonencode([
    {
      name      = "ecs-bridge-task-definition",
      essential = true
      environment = [
        {
          name  = "GIT_HASH"
          value = var.git_commit_hash_short
        }
      ]
```

Does that help you? I know it doesn't solve the bug/issue you're seeing but it seems like a decent workaround.

Thanks,
Trevor

**Comment by timomeinen** [comment]
@trevorrea Thank you very much for the tipp. We already tried this as a workaround, but the disadvantage of this approach is, that on every commit a new ECS Task Definition is being created, which is not our intention.

Although I have used 3.71 in my example, I can spot the error to appear in 3.68 as 3.67 is updating the service just fine. So the change must be part of the 3.68 release.

**Comment by trevorrea** [comment]
I guess there are umpteen workarounds to this but it worked before then it should work now. 

No worries - I was looking for another issue and came across yours and decided to add my 2 cents :)

**Comment by timomeinen** [comment]
@trevorrea That's great - as it is a real workaround.

I see a lot of tickets regarding the force_new_deployment option open. So I thought - with this one it should be able to find the point in time, when it failed to work. v3.68

**Comment by justinretzolk** [comment]
Hey @timomeinen 👋 

> Unfortunately, I am a little bit unsure of posting the logs as a public gist - as I don't want to publish secrets or credentials unintentionally. Is it possible to send you the logs (or gist URL) on a different means?

I totally understand this! One option would be to encrypt the logs using our GPG public key (found on [keybase](https://keybase.io/hashicorp)). If that won't work for you either, let me know and we can try to figure something else out.

**Comment by obataku** [comment]
any luck @timomeinen? I can't see anything between v3.67.0 and v3.68.0 that would account for this break. looking at your unencrypted logs, we have
>     [DEBUG] Updating ECS Service (arn:aws:ecs:eu-central-1:xxx:service/avi-test-ecs-xxx--bridge-cluster/avi-test-ecs-xxx--bridge-service): {
>       Cluster: "arn:aws:ecs:eu-central-1:xxx:cluster/avi-test-ecs-xxx--bridge-cluster",
>       ForceNewDeployment: true,
>       NetworkConfiguration: {
>         AwsvpcConfiguration: {
>           AssignPublicIp: "DISABLED",
>           SecurityGroups: ["sg-xxx"],
>           Subnets: ["subnet-xxx","subnet-xxx"]
>         }
>       },
>       Service: "arn:aws:ecs:eu-central-1:xxx:service/avi-test-ecs-xxx--bridge-cluster/avi-test-ecs-xxx--bridge-service"
>     }
from what I can tell, your pre-67 updates were triggered by a `NetworkConfiguration` change, since `tags` changes skip the call to `UpdateService` entirely:
https://github.com/hashicorp/terraform-provider-aws/blob/v3.67.0/internal/service/ecs/service.go#L1141-L1144
```go
	if d.HasChange("network_configuration") {
		updateService = true
		input.NetworkConfiguration = expandEcsNetworkConfiguration(d.Get("network_configuration").([]interface{}))
	}
	...
	if updateService {
		log.Printf("[DEBUG] Updating ECS Service (%s): %s", d.Id(), input)
		...
	}
	...
	if d.HasChange("tags_all") {
		...
	}

```
I suspect something subtle changed in the diffing of `network_configuration` although I don't see an obvious culprit
