### ISSUE TITLE
Terraform AWS IAM Inline Role Policy Producing Stale State Values

### ISSUE THREAD

**Issue by sernst** [hashicorp/terraform-provider-aws#22525]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

- This issue has been reproduced using:
   - terraform versions: `1.1.3`, `1.1.1` and `1.0.11`.
   - aws provider versions: `3.71.0`, `3.67.0` and `3.52.0`
 
### Affected Resource(s)

- `aws_iam_role`
- `aws_iam_role_policy`

### Terraform Configuration Files

Here is a [Gist](https://gist.github.com/sernst/6b9c1734c73a94da3548308c30c2ca4a)
of a minimal example that reproduces this issue. It includes a [README.md](https://gist.github.com/sernst/6b9c1734c73a94da3548308c30c2ca4a#file-readme-md) that contains all output and state file
information observed in reproducing the issue.

### Debug Output

The output is viewable in the [Gist README.md](https://gist.github.com/sernst/6b9c1734c73a94da3548308c30c2ca4a#file-readme-md) mentioned above.

### Expected Behavior

Changes made to an `aws_iam_role_policy.policy` attribute should be reflected in the
state and not seen as out-of-terraform drift.

### Actual Behavior

The state file records the pre-applied `aws_iam_role_policy.policy` value and then
sees the correctly-applied state from the terraform apply as drift.

### Steps to Reproduce

The steps to reproduce are outlined in the [Gist README.md](https://gist.github.com/sernst/6b9c1734c73a94da3548308c30c2ca4a#file-readme-md) mentioned above. The short
version is:

1. `terraform apply`

the minimal example and then compare the value of the `instances[0].attributes.inline_policy[0].policy`
in the state file for the `aws_iam_role.access` resource with the value expected by the `outputs.policy`
and `aws_iam_role_policy` 

2. Modify `suffix = "a" -> suffix = "b"` in the `terraform.tfvars file.
3. `terraform apply`

Note that once again the state of the `aws_iam_role`'s `inline_policy` is the pre-applied version and
not the post-applied version reflected by the `outputs.policy` and `aws_iam_role_policy` in the same
state file.

### References

There seem to be other inline policy issues that manifest in similar cases:

* #22336
* #19444
* #20961

that could certainly be related manifestations of this issue. Until my team and I 
dug into the state file the presentation of the issue seemed like something else
was the cause.

**Comment by abatilo** [comment]
I think I'm having the same problem and it seems to be a regression introduced between `3.69.0` and `3.70.0`
