### ISSUE TITLE
Error decoding "aws_dynamodb_table.state_lock" from previous state: unsupported attribute "kms_key_arn"

### ISSUE THREAD

**Issue by KIVagant** [hashicorp/terraform-provider-aws#22534]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.71.0
+ provider registry.terraform.io/hashicorp/external v2.2.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Affected Resource(s)

* aws_dynamodb_table

### Terraform Configuration Files

```hcl
provider "aws" {
  region              = "XXXXXX"
  allowed_account_ids = ["XXXXXXX"]
}

# see https://www.terraform.io/docs/backends/types/s3.html#lock_table
resource "aws_dynamodb_table" "state_lock" {
  name           = "TerraformState"
  hash_key       = "LockID"
  read_capacity  = 3
  write_capacity = 3

  attribute {
    name = "LockID"
    type = "S"
  }
}

terraform {
  backend "s3" {
    acl            = "bucket-owner-full-control"
    bucket         = "XXXXXXXXXX-XXXXXXX"
    key            = "production/terraform1.1.tfstate"
    region         = "us-east-1"
    dynamodb_table = "TerraformState"
  }
}

```

### Debug Output

I couldn't find any additional useful info in the debug output related to the issue.

### Expected Behavior

`Apply` works

### Actual Behavior

```
╷
│ Error: Failed to decode resource from state
│
│ Error decoding "aws_dynamodb_table.state_lock" from previous state: unsupported attribute "kms_key_arn"
╵
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I feel like this issue may be related to the PR:

https://github.com/hashicorp/terraform-provider-aws/pull/21334

Here's the part of our state file that probably causes the issue. I found many `kms_key_arn` mentions across the state file.

```json
{
      "mode": "managed",
      "type": "aws_dynamodb_table",
      "name": "state_lock",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 1,
          "attributes": {
            "arn": "arn:aws:dynamodb:us-east-1:XXXXXXXXXXXX:table/TerraformState",
            "attribute": [
              {
                "name": "LockID",
                "type": "S"
              }
            ],
            "billing_mode": "PROVISIONED",
            "global_secondary_index": [],
            "hash_key": "LockID",
            "id": "TerraformState",
            "local_secondary_index": [],
            "name": "TerraformState",
            "point_in_time_recovery": [
              {
                "enabled": false
              }
            ],
            "range_key": null,
            "read_capacity": 3,
            "replica": [],
            "restore_date_time": null,
            "restore_source_name": null,
            "restore_to_latest_time": null,
            "server_side_encryption": [],
            "stream_arn": "",
            "stream_enabled": false,
            "stream_label": "",
            "stream_view_type": "",
            "table_class": "",
            "tags": {},
            "tags_all": {},
            "timeouts": {
              "create": null,
              "delete": null,
              "update": null
            },
            "ttl": [
              {
                "attribute_name": "",
                "enabled": false,
                "kms_key_arn": ""
              }
            ],
            "write_capacity": 3
          },
          "sensitive_attributes": []
        }
      ]
    },
```

### References

* #19344 (May be related)

**Comment by justinretzolk** [comment]
Hey @KIVagant 👋 Thank you for taking the time to file this issue. So that we have all of the necessary information in order to investigate this, can you add the rest of the information requested in the [issue template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?

**Comment by KIVagant** [comment]
Hi @justinretzolk . Sorry, I felt like I filled the template, but I forgot to copy-n-paste TF configs. Updated adding them, please check if there's anything else I can add to provide more info.

**Comment by KIVagant** [comment]
Workaround for the problem: rollback `hashicorp/aws` in `.terraform.lock.hcl` to **3.70.0**

```hcl
provider "registry.terraform.io/hashicorp/aws" {
  version = "3.70.0"
  hashes = [
    "h1:E5IKHXzPGGSizZM5rHKzNCzpwQ7lWPXmmJnms82uzDk=",
    "h1:Kv3xMsXoICUYTEXeyhdXiJSMfydCbkJCQOjeVhs3EAc=",
    "h1:jn4ImGMZJ9rQdaVSbcCBqUqnhRSpyaM1DivqaNuP+eg=",
    "h1:nUJfymSecxxYgW+Vc3tqv9Ymlqc91ZeGk5t4vnRaC3c=",
    "zh:0af710e528e21b930899f0ac295b0ceef8ad7b623dd8f38e92c8ec4bc7af0321",
    "zh:4cabcd4519c0aae474d91ae67a8e3a4a8c39c3945c289a9cf7c1409f64409abe",
    "zh:58da1a436facb4e4f95cd2870d211ed7bcb8cf721a4a61970aa8da191665f2aa",
    "zh:6465339475c1cd3c16a5c8fee61304dcad2c4a27740687d29c6cdc90d2e6423d",
    "zh:7a821ed053c355d70ebe33185590953fa5c364c1f3d66fe3f9b4aba3961646b1",
    "zh:7c3656cc9cc1739dcb298e7930c9a76ccfce738d2070841d7e6c62fbdae74eef",
    "zh:9d9da9e3c60a0c977e156da8590f36a219ae91994bb3df5a1208de2ab3ceeba7",
    "zh:a3138817c86bf3e4dca7fd3a92e099cd1bf1d45ee7c7cc9e9773ba04fc3b315a",
    "zh:a8603044e935dfb3cb9319a46d26276162c6aea75e02c4827232f9c6029a3182",
    "zh:aef9482332bf43d0b73317f5909dec9e95b983c67b10d72e75eacc7c4f37d084",
    "zh:fc3f3cad84f2eebe566dd0b65904c934093007323b9b85e73d9dd4535ceeb29d",
  ]
}
```

**Comment by LukaszRacon** [comment]
Different workaround (switch to recent version 3.73.0)
- edit state file and remove `, "kms_key_arn": ""` from `aws_dynamodb_table`'s `ttl` 
```
{
      "mode": "managed",
      "type": "aws_dynamodb_table",
      "name": "something",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
...
            "ttl": [
              {
                "attribute_name": "",
+                "enabled": false
-                "enabled": false,
-                "kms_key_arn": ""
              }
            ],
...
      ]
    },
```
- (if you use dynamodb for locking) run `terraform apply` which will fail with invalid md5 hash. Copy/paste hash into dynamodb table.

**Comment by gcmanriq** [comment]
I tried to downgrade to v3.70.0 and got others errors in different modules. Also tried upgrading to 3.73.0, but then I don't have access to state files so my solution was to downgrade Terraform CLI to version 1.0.11, using tfswitch and that worked.

**Comment by Miguel-KD** [comment]
Another workaround for newer versions and safer than touch the state file.
 Delete the file from the state and import it again. For example:
```
terraform state rm aws_dynamodb_table.my_table my_table_name
terraform import aws_dynamodb_table.my_table my_table_name
```

**Comment by KamalAman** [comment]
I am experiencing a number of these issues lately after updating azurerm from v2 to v3. 

Also appears in [#16611](https://github.com/hashicorp/terraform-provider-azurerm/issues/16611)

It seems like `terraform refresh` should resolve the issue  [refresh](https://www.terraform.io/cli/commands/refresh)

**Comment by sachsgiri** [comment]
`terraform refresh` solved this for me as well.

**Comment by goodspark** [comment]
Ran into this as well. The pointer to the refresh command was helpful, but wanted to highlight this from [Terraform's docs](https://www.terraform.io/cli/commands/refresh):

> This command is deprecated, because its default behavior is unsafe if you have misconfigured credentials for any of your providers.

> If you have misconfigured credentials for one or more providers, Terraform may be misled into thinking that all of the managed objects have been deleted, causing it to remove all of the tracked objects without any confirmation prompt.
> Instead, we recommend using the following command in order to get the same effect but with the opportunity to review the changes that Terraform has detected before committing them to the state:
> `terraform apply -refresh-only`

This was introduced in TF 0.15.4. For people on older CLI versions, the old refresh command is the only option, with it's given caveats and risks.

**Comment by mohsinhijazee** [comment]
Terraform refresh didn't work for me and between version upgrades, terraform probably constantly refactoring how they store the state but not having an upgrade/transformation for the older state versions, I ended up doing the surgery myself and writing it down for someone coming back to this

First pull the state locally.

```
terraform state pull > state.json
```
Edit the state file and remove following attributes (keys from the JSON file):

* `enable_network_address_usage_metrics`
* `timeout`
* `context`
* `custom_key_store_id`
* `ip_address_type`
* `final_snapshot`
* `disable_api_stop`
* `connection_termination`
* `ipv4_ipam_pool_id`
* `enable_dns64`
* `enable_resource_name_dns_a_record_on_launch`
* `ipv4_netmask_length`
* `ipv6_cidr_block_network_border_group`
* `ipv6_ipam_pool_id`
* `cookie_name`
* `default_instance_warmup`
* `enable_resource_name_dns_aaaa_record_on_launch`
* `ipv6_native`
* `private_dns_hostname_type_on_launch`
* `ipv6_netmask_length`
* `desync_mitigation_mode`
* `enable_waf_fail_open`
* `preserve_host_header`
* `instance_requirements`
* `maintenance_options`
* `private_dns_name_options`

There could be more attributes depending upon the shape and resources of your infrastructure but this should give you a head start. Next, the "serial" key should be incremented and then:

```
terraform state push state.json
```

Once all done, you should be good to go. If anyone knows anything better or more "by the book" way, please do let us know.

**Comment by justinretzolk** [comment]
Hey y'all 👋 Looks like this is resolved by a `terraform apply -refresh-only` (with some additional steps required depending on the backend being used). Given that's the case, I'll close this issue out. If you feel I've done this in error, please do let me know.
