### ISSUE TITLE
New Datasource: aws_appstream_image

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#22536]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Note: When this is implemented, acceptance tests with hard-coded images should be updated

### New or Affected Resource(s)

* aws_appstream_image

### References

* #6508

**Comment by maunzCache** [comment]
As the description is a little bit sparse: Here is at least the API reference https://docs.aws.amazon.com/appstream2/latest/APIReference/API_DescribeImages.html
