### ISSUE TITLE
Error creating new DynamoDB Table

### ISSUE THREAD

**Issue by charleneaid** [hashicorp/terraform-provider-aws#22558]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform 1.1.1/1.1.3
Terragrunt v0.35.16
aws = {
      source  = "hashicorp/aws"
      version = "~>3.69.0"
}

### Affected Resource(s)

* aws_dynamodb_table

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_dynamodb_table" "some_name" {
  name = "some_name"
  hash_key = "some_key"

  attribute {
    name = "some_key"
    type = "S"
  }
}
```

### Debug Output

[Output (partial)](https://gist.github.com/charleneaid/7c1d9f28db19957397aeb6eb7c3bf614#file-ddb_creation_error-txt)

### Panic Output

N/A

### Expected Behavior

(proposed solutions)

- Create the new dynamodb table with a default r/w capacity
OR
- Error complaining that `billing_mode` was not set (make this a required field)

### Actual Behavior

Error complaining about a field that was not explicitly set

### Steps to Reproduce

Attempt to create a new dynamodb table with only required fields set:
```hcl
resource "aws_dynamodb_table" "some_name" {
  name = "some_name"
  hash_key = "some_key"

  attribute {
    name = "some_key"
    type = "S"
  }
}
```
1. `terraform apply`

### Important Factoids

This was first discovered via a build in AWS Codebuild, using Terragrunt v0.35.16, and Terraform v1.1.3. Also reproduced using Terraform v1.1.1 on a local environment.

### References

* #[13693](https://github.com/hashicorp/terraform-provider-aws/issues/13693) - the same error, different scenario

**Comment by KhimairaCrypto** [comment]
What is your aws plugin version? Did you upgrade the plugin on your project `terraform init -upgrade`

**Comment by charleneaid** [comment]
This is the provider:
```
aws = {
  source = "hashicorp/aws"
  version = "~>3.69.0"
}
```

And I tried running `terraform init -upgrade` but it gives me the same error.

```
 Error: write capacity must be > 0 when billing mode is PROVISIONED
│ 
│   with aws_dynamodb_table.some_name,
│   on codepipeline.tf line 74, in resource "aws_dynamodb_table" "some_name":
│   74: resource "aws_dynamodb_table" "some_name" {
│ 
╵
```

I think it would be an easy fix to make billing_mode into a required field.
