### ISSUE TITLE
Data source aws_vpcs should not fail if no VPCs are found

### ISSUE THREAD

**Issue by chrisrecla** [hashicorp/terraform-provider-aws#22555]
If I run the aws_vpcs module on an account/region with empty VPC list using a tags filter, the data source returns an error:

```
data "aws_vpcs" "vpc_list" {
  tags = {
    Project = "test"
  }
}

│ Error: no matching VPC found
│
│   with data.aws_vpcs.vpc_list,
│   on vpc.tf line 5, in data "aws_vpcs" "vpc_list":
│    5: data "aws_vpcs" "vpc_list" {
```
It seems this issue was already fixed, but then the file where it was fixed has been redesigned/replaced. #13951 #13982

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.70.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.7.1
+ provider registry.terraform.io/hashicorp/tls v3.1.0

### Affected Resource(s)

Data Source: aws_vpcs

### Proposal

data source "aws_vpcs" should return an empty list, like the aws cli:

```
aws ec2 describe-vpcs --filters Name=tag:Project,Values=test
{
    "Vpcs": []
}
```

**Comment by ewbankkit** [comment]
@chrisrecla Thanks for raising this issue.
It has already been noticed in #13951. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
