### ISSUE TITLE
Support for NewerNoncurrentVersions for S3 Bucket

### ISSUE THREAD

**Issue by firstval** [hashicorp/terraform-provider-aws#22561]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

- aws_s3_bucket

### Description

* This is to support adding the NewerNonCurrentVersions  or Number of newer versions to retain for Non-Current Version within LifeCycle Configuration in S3 Bucket that already supported by AWS SDK, and CloudFormation 

### References

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfig-rule-noncurrentversionexpiration.html
* https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#bucketlifecycleconfiguration
* https://docs.aws.amazon.com/AmazonS3/latest/userguide/intro-lifecycle-rules.html#intro-lifecycle-rules-actions

**Comment by glenwinters** [comment]
I'm looking to contribute for the first time, and this seems doable. I'll try to open a PR soon.

**Comment by firstval** [comment]
I'll close this now as it supported on Terraform v4
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration#newer_noncurrent_versions
