### ISSUE TITLE
aws_cloudfront_distribution custom_origin_config origin_read_timeout validation error - when account limit is greater than 60s an error occurs

### ISSUE THREAD

**Issue by whwiz** [hashicorp/terraform-provider-aws#22567]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v1.1.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.71.0
```

### Affected Resource(s)
* aws_cloudfront_distribution

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_cloudfront_distribution" "example" {
  origin {
      custom_origin_config {
        http_port              = "80"
        https_port             = "443"
        origin_protocol_policy = "https-only"
        origin_read_timeout    = "180"
        origin_ssl_protocols   = ["TLSv1.2", "TLSv1.1", "TLSv1"]
      }
      domain_name = "example.com"
      origin_id   = "example"
  }

  enabled             = true

  default_cache_behavior {
    allowed_methods  = ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "example"

    forwarded_values {
      query_string = false

      cookies {
        forward = "none"
      }
    }

    viewer_protocol_policy = "allow-all"
    min_ttl                = 0
    default_ttl            = 3600
    max_ttl                = 86400
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }
}
```

### Debug Output
[debug output](https://gist.github.com/whwiz/fcae07033f70ab09699bd54b18b84597)

### Expected Behavior
The `terraform apply` should have succeeded without the validation error. My account has a larger than default 60s value for the `origin_read_timeout`    

### Actual Behavior
The `terraform apply` fails with error:
```
╷
│ Error: expected origin.0.custom_origin_config.0.origin_read_timeout to be in the range (1 - 60), got 180
│
│   with aws_cloudfront_distribution.example,
│   on main.tf line 5, in resource "aws_cloudfront_distribution" "example":
│    5: resource "aws_cloudfront_distribution" "example" {
│
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Important Factoids
We have , via a support request, increased the limit for CloudFront origin read timeouts from the default value of `60` to `180`.

**Comment by ewbankkit** [comment]
@whwiz Thanks for raising this issue.
It has already been noticed in #22469. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
