### ISSUE TITLE
aws_backup_selection - selection_tag (Not Backing Up) - Different AWS API response

### ISSUE THREAD

**Issue by jimsmith** [hashicorp/terraform-provider-aws#22568]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_backup_selection

Backup tag not working as expected, different AWS API parameters being passed for **tag-based** backups, **listOfTags** is passed to AWS but nothing is triggered, creating manually in AWS console gives a different parameters passed over - cloudtrail logs captured.

- What is the way to have this backing up for tag-based backups ?

- It looks like this could solve my issue, when will this be released ?
```
resource/aws_backup_selection: Add condition configuration block and not_resources argument in support of fine-grained backup plan resource assignment (#22074)
```
https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#:~:text=resource/aws_backup_selection%3A%20Add%20condition%20configuration%20block%20and%20not_resources%20argument%20in%20support%20of%20fine%2Dgrained%20backup%20plan%20resource%20assignment%20(%2322074)

### Terraform Configuration Files

```
Terraform v1.0.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.71.0
```

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

Information stripped out sensitive parts.

```hcl
resource "aws_backup_selection" "ab_selection" {
  iam_role_arn = var.iam_role_arn
  name         = var.name
  plan_id      = aws_backup_plan.ab_plan.id

  resources = var.resources

  selection_tag {
    type  = "STRINGEQUALS"
    key   = "aws:ResourceTag/BackupProjectA"
    value = "true"
  }
```

I did try different combinations including the below and also two and three tags.

```
    type  = "STRINGEQUALS"
    key   = "Backup"
    value  = true"
```

### Debug Output

CloudTrail - created with Terraform
```
    "requestParameters": {
        "backupPlanId": "REDACTED,
        "backupSelection": {
            "selectionName": "selection-1",
            "iamRoleArn": "arn:aws:iam::REDACTED:role/aws-backup-plan-ProjectA-tags-based-plan-role",
            "resources": [
                "arn:aws:ec2:*:*:instance/*"
            ],
            "listOfTags": [
                {
                    "conditionType": "STRINGEQUALS",
                    "conditionKey": "aws:ResourceTag/BackupProjectA",
                    "conditionValue": "true"
                }
            ]
        }
    },
```

CloudTrail - created in AWS Web Console UI
```
    "requestParameters": {
        "backupPlanId": "REDACTED",
        "backupSelection": {
            "selectionName": "test1",
            "iamRoleArn": "arn:aws:iam::REDACTED:role/aws-backup-plan-ProjectA-tags-based-plan-role",
            "resources": [
                "arn:aws:ec2:*:*:instance/*"
            ],
            "notResources": [],
            "conditions": {
                "stringEquals": [
                    {
                        "conditionKey": "aws:ResourceTag/BackupProjectA",
                        "conditionValue": "true"
                    }
                ],
                "stringNotEquals": [],
                "stringLike": [],
                "stringNotLike": []
            }
        },
```

**AWS Console** (when creating manually works as expected) notice **Tags - equal**
![image](https://user-images.githubusercontent.com/2676701/149351053-48e72c60-7f16-4225-bdea-a296c57d0436.png)

---

**Terraform** (not working as expected) notice **Tags**
<img width="169" alt="image" src="https://user-images.githubusercontent.com/2676701/149348815-55bb24e7-c096-4572-9fd7-7f13357a65f9.png">

---
---
---

### Expected Behavior

AWS Backup starts backing up resources with those tags

### Actual Behavior

Nothing happens

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @jimsmith 👋 I believe the team will be starting the process to release `v3.72.0` a bit later today. Would you mind testing again once that release is out to see if the change that you referenced does indeed resolve the issue?

**Comment by jimsmith** [comment]
Hi @justinretzolk absolutely 👍

**Comment by antonosmond** [comment]
Hi we've just noticed that terraform wants to recreate all our backup plans (using the newly released 3.72.0 provider).
I can't comment on whether or not it will actually stop any backups working as we haven't applied the plan yet but I think we'll hold off applying until we know the outcome of this issue

**Comment by jimsmith** [comment]
my use case is different there are no backups in place (resources being destroyed part of development)

**Comment by jimsmith** [comment]
Hi @justinretzolk 

> Hi we've just noticed that terraform wants to recreate all our backup plan selections (using the newly released 3.72.0 provider). I can't comment on whether or not it will actually stop any backups working as we haven't applied the plan yet but I think we'll hold off applying until we know the outcome of this issue

I happen to spot this https://github.com/leonenkoa/terraform-provider-aws/blob/main/internal/service/backup/selection.go#L51

So I wouldn't hold off of the outcome from my use case.

**Comment by jimsmith** [comment]
hey @justinretzolk having difficulties with it allowing two `string_equals`

**Terraform plan**

```
  # module.REMOVED_aws_backup.aws_backup_selection.ab_selection[0] will be created
  + resource "aws_backup_selection" "ab_selection" {
      + iam_role_arn = (known after apply)
      + id           = (known after apply)
      + name         = "iac"
      + plan_id      = (known after apply)
      + resources    = [
          + "arn:aws:ec2:*:*:instance/*",
        ]

      + condition {
          + string_equals {
              + key   = "aws:ResourceTag/Backup"
              + value = "true"
            }
        }
      + condition {
          + string_equals {
              + key   = "aws:ResourceTag/Project"
              + value = "REMOVED"
            }
        }
    }
```

**Cloudtrail**

```
    "requestParameters": {
        "backupPlanId": "REMOVED",
        "backupSelection": {
            "selectionName": "iac",
            "iamRoleArn": "arn:aws:iam::REMOVED:role/aws-backup-plan-REMOVED-tags-based-plan-role",
            "resources": [
                "arn:aws:ec2:*:*:instance/*"
            ],
            "listOfTags": [],
            "notResources": [],
            "conditions": {
                "stringEquals": [
                    {
                        "conditionKey": "aws:ResourceTag/Backup",
                        "conditionValue": "true"
                    }
                ]
            }
        }
    },
```

**Tag equals** does show up but only one condition

![image](https://user-images.githubusercontent.com/2676701/149538927-c00b8818-54c6-431b-b1ea-e1fd0e12d1ba.png)

When re-running plan:

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # module.REMOVED_aws_backup.aws_backup_selection.ab_selection[0] has been changed
  ~ resource "aws_backup_selection" "ab_selection" {
        id            = "REMOVED"
        name          = "iac"
      + not_resources = []
        # (3 unchanged attributes hidden)

      - condition {
          - string_equals {
              - key   = "aws:ResourceTag/Project" -> null
              - value = "REMOVED" -> null
            }
        }
        # (1 unchanged block hidden)
    }
  # module.REMOVED_aws_backup.aws_iam_policy.ab_tag_policy[0] has been changed
  ~ resource "aws_iam_policy" "ab_tag_policy" {
        id          = "arn:aws:iam::REMOVED:policy/aws-backup-plan-REMOVED-tags-based-plan-role"
        name        = "aws-backup-plan-REMOVED-tags-based-plan-role"
      + tags        = {}
        # (6 unchanged attributes hidden)
    }
  # module.REMOVED_aws_backup.aws_iam_role.ab_role[0] has been changed
  ~ resource "aws_iam_role" "ab_role" {
        id                    = "aws-backup-plan-REMOVED-tags-based-plan-role"
      ~ managed_policy_arns   = [
          + "arn:aws:iam::REMOVED:policy/aws-backup-plan-REMOVED-tags-based-plan-role",
          + "arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup",
          + "arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForRestores",
        ]
        name                  = "aws-backup-plan-REMOVED-tags-based-plan-role"
        tags                  = {
            "Backup"                   = "true"
            "Project"                  = "REMOVED"
        }
        # (8 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.



Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.REMOVED_aws_backup.aws_backup_selection.ab_selection[0] must be replaced
-/+ resource "aws_backup_selection" "ab_selection" {
      ~ id            = "REMOVED" -> (known after apply)
        name          = "iac"
      - not_resources = [] -> null
        # (3 unchanged attributes hidden)

      + condition { # forces replacement
          + string_equals {
              + key   = "aws:ResourceTag/Project"
              + value = "REMOVED"
            }
        }
        # (1 unchanged block hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

**Comment by jimsmith** [comment]
Hey @justinretzolk this resolves my issue (can safely ignore the above, minor TF logic needed changing about)
all good for me

**Comment by justinretzolk** [comment]
Hey @jimsmith thanks for letting me know! I'll go ahead and close this one out with that in mind.

@antonosmond -- I think your issue might be a bit different than this one. We try to keep (GitHub) issues scoped to a single (provider) issue, so we'll want to continue that conversation in a different (GitHub) issue. That said, I think you might be running into the same thing as https://github.com/hashicorp/terraform-provider-aws/issues/22595?

**Comment by jimsmith** [comment]
Thanks, I do have a nuisance though on getting the the conditions ie strings_equals be read from in .tfvars as it errors on there is no = sign

How can I get it being read from .tfvars as trying different combinations I'm hitting issues with.

**Comment by justinretzolk** [comment]
Hey @jimsmith 👋 Since things have presumably changed a little based on your previous comment of updating the logic of your configuration, would you mind sending over your current configuration and how you're attempting to configure the `.tfvars` file so that I can get a better idea of how you currently have things set up?
