### ISSUE TITLE
Cannot use SQS `redrive_allow_policy` correctly without creating a cycle

### ISSUE THREAD

**Issue by davecardwell** [hashicorp/terraform-provider-aws#22577]
The [Example Usage](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue#example-usage) for `aws_sqs_queue` shows a “source queue” with both a `redrive_policy` and a `redrive_allow_policy` set, however as per [the AWS docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html#:~:text=The%20redrive%20allow%20policy%20specifies%20which%20source%20queues%20can%20access%20the%20dead%2Dletter%20queue.%20This%20policy%20applies%20to%20a%20potential%20dead%2Dletter%20queue.) the “byQueue” `redrive_allow_policy` belongs on the dead letter queue itself:

> The redrive allow policy specifies which source queues can access the dead-letter queue. This policy applies to a potential dead-letter queue.

Since you set a `redrive_policy` on the source queue which points to a dead letter queue, and a `redrive_allow_policy` on the dead letter queue restricting which source queues can redrive to it, it is not possible to represent this relationship in Terraform without creating a cycle.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v1.1.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v3.71.0
```

### Affected Resource(s)

* aws_sqs_queue

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_sqs_queue" "source_queue" {
    name = "source_queue"

    redrive_policy = jsonencode({
        deadLetterTargetArn = aws_sqs_queue.dead_letter_queue.arn
    })
}

resource "aws_sqs_queue" "dead_letter_queue" {
    name = "dead_letter_queue"

    redrive_allow_policy = jsonencode({
        redrivePermission = "byQueue"
        sourceQueueArns = ["${aws_sqs_queue.source_queue.arn}"]
    })
}
```

### Debug Output

https://gist.github.com/davecardwell/236f84642a90536d442cbfc4434f8da1

### Panic Output

N/A

### Expected Behavior

Success. It should be possible to configure a `RedriveAllowPolicy` without creating a circular dependency.

### Actual Behavior

```
Error: Cycle: aws_sqs_queue.dead_letter_queue, aws_sqs_queue.source_queue
```

### Steps to Reproduce

1. `terraform validate`

### Important Factoids

N/A

### References

* [AWS SQS dead letter queue docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html#:~:text=The%20redrive%20allow%20policy%20specifies%20which%20source%20queues%20can%20access%20the%20dead%2Dletter%20queue.%20This%20policy%20applies%20to%20a%20potential%20dead%2Dletter%20queue.)

**Comment by sgabenov** [comment]
I think it would be good to move DLQ redrive to a separate resource, so it can be dependant on normal queue and DLQ and do not create a cycle loop. 
Also, example in docs of terraform resource would be very helpfull

**Comment by nandorholozsnyak** [comment]
Hey, we are also facing this issue, any news on it?

**Comment by rbresson-edfx** [comment]
Facing the same issue, I had to put redrivePermission = "allowAll" in order to make it work, but not satisfaisant

**Comment by ramooncamacho** [comment]
I tested it in version 1.1.7 because I was facing the same problem, and realized that the dead letter sqs queue needs to be implemented first.

You have to create arn string "arn:aws:sqs:region:account_number:mysqsqueue" in the redrive_allow_policy of the sqs dead letter queue. And at the main sqs queue you can point to the dead letter queue using arn attribute. This way the main sqs queue will depend on the sqs dead letter queue (you could also use depends_on, but it is not required in this case).

**Comment by iwt-krzysztofpodkalicki** [comment]
Hi @ramooncamacho, thanks for that idea!
Unfortunately this doesn't really seem to be working for me.
 DLQ:
```terraform
locals {
  dlq_name = "some-dlq.fifo"
}

resource "aws_sqs_queue" "deadletter_queue" {
  name                        = local.dlq_name
  ...

  redrive_allow_policy = jsonencode({
    redrivePermission = "byQueue",
    sourceQueueArns   = [aws_sqs_queue.queue.arn]
  })
  ...
}
```

`redrive_policy` of main queue
```terraform
redrive_policy = jsonencode({
  deadLetterTargetArn = "arn:aws:sqs:${var.region}:${var.account_id}:${local.dlq_name}"
  maxReceiveCount     = 2
})
```
When I'm running `terraform apply` I'm getting an error:
```
RedrivePolicy is invalid. Reason: Dead letter target does not exist.
```

**Comment by taylor-knapp** [comment]
It would be nice if you could directly reference the name from the main queues, as TF can know that before applying.

```terraform
resource "aws_sqs_queue" "main_queue" {
  name                       = "main-queue"
  redrive_policy             = jsonencode({
    deadLetterTargetArn = aws_sqs_queue.dead_letter.arn
    maxReceiveCount     = 10
  })
}

resource "aws_sqs_queue" "dead_letter" {
  name                       = "dead-letter-queue"
  redrive_allow_policy       = jsonencode({
    redrivePermission = "byQueue",
    sourceQueueArns   = [
      # Required to either hard code or use a local for the name variable to avoid the cycle error.
      "arn:aws:sqs:${var.region}:${var.account_id}:main-queue",
      # Would be nice to just reference the already known name.
      "arn:aws:sqs:${var.region}:${var.account_id}:${aws_sqs_queue.main_queue.name}"
    ]
  })
}
```

**Comment by dynamicnet** [comment]
same as @taylor-knapp , with the last AWS provider to date (4.24.0), this code led to cycle error

```terraform
resource "aws_sqs_queue" "queue" {
  name                       = "queue"

  redrive_policy = jsonencode({
    deadLetterTargetArn = aws_sqs_queue.dlq_queue.arn
    maxReceiveCount     = 36
  })
}

resource "aws_sqs_queue" "dlq_queue" {
  name                       = "dlq_queue"

  redrive_allow_policy = jsonencode({
    redrivePermission = "byQueue",
    sourceQueueArns   = [aws_sqs_queue.queue.arn]
  })
}
```

**Comment by techotron** [comment]
Same workaround as https://github.com/hashicorp/terraform-provider-aws/issues/22577#issuecomment-1183810999 I had to construct the `sourceQueueArns` manually:

```
  redrive_allow_policy  = jsonencode({
    redrivePermission = "byQueue",
    sourceQueueArns   = ["arn:aws:sqs:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:my-queue"]
  })  
```

**Comment by stepintooracledba** [comment]
Hi,
I've tried the same redrive_policy using Provider(4.32.0) still get same cycle error.

**Comment by timothyclarke** [comment]
@ewbankkit Please re-open this one as it is currently unsolved.
Following the [example usage](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue) currently version 4.36.1 still generates a circular dependency error per the [original post](https://github.com/hashicorp/terraform-provider-aws/issues/22577#issue-1102275924) at the start of this thread

**Comment by chuong-tran** [comment]
The solution is to create separate redrive_allow_policy resource like the example in URL below
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue_redrive_allow_policy

**Comment by timothyclarke** [comment]
@chuong-tran The docs for the `aws_sqs_queue` resource still need to be updated as they are giving an invalid example

**Comment by chuong-tran** [comment]
@timothyclarke I see. Thanks!

**Comment by hsteidel** [comment]
> The docs for the aws_sqs_queue resource still need to be updated as they are giving an invalid example https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue_redrive_allow_policy

I was facing an issue with the sample provided at
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue_redrive_allow_policy

Where I went wrong was by deviating. I had...
```
resource "aws_sqs_queue" "inbound_message_dlq" {
  name = "inbound-dlq"
}
resource "aws_sqs_queue_redrive_allow_policy" "inbound_message_dlq_redrive" {
```
And that gave me an AWS 400 Resource Error on the source queue `InvalidParameterValue: Value RedrivePolicy`

However, once I named both the DLQ and the RedriveAllowPolicy the same, it worked. 

```
resource "aws_sqs_queue" "inbound_message_dlq" {
  name = "inbound-dlq"
}

resource "aws_sqs_queue_redrive_allow_policy" "inbound_message_dlq" {
```
