### ISSUE TITLE
Private Endpoint Type Support in GovCloud

### ISSUE THREAD

**Issue by ajgrowney** [hashicorp/terraform-provider-aws#22583]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of the most recent version of terraform, the docs specify:
"Must be declared as REGIONAL in non-Commercial partitions".
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_rest_api#types

Request: Allow PRIVATE as a type in non-Commercial partitions

### New or Affected Resource(s)

* aws_api_gateway_rest_api

### Potential Terraform Configuration

```hcl

resource "aws_api_gateway_rest_api" "SampleAPI-private" {
  ...
  endpoint_configuration {
    types = ["PRIVATE"]
    ...
  }
}
```

### References
None

**Comment by tburow** [comment]
add SC2S to this issue

**Comment by tburow** [comment]
label:needs-triage

**Comment by ewbankkit** [comment]
@ajgrowney Thanks for raising this issue 👏.
The restriction to `REGIONAL` is **NOT** enforced by the provider for non-Commercial partitions (at least not in the latest, **v4.53.0**, version) so you should be able to set `types` to `["PRIVATE"]` and run `terraform apply`.

I have verified with an existing acceptance test in `us-gov-west-1`:

```console
% make testacc TESTARGS='-run=TestAccAPIGatewayRestAPI_Endpoint_private' PKG=apigateway ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/apigateway/... -v -count 1 -parallel 3  -run=TestAccAPIGatewayRestAPI_Endpoint_private -timeout 180m
=== RUN   TestAccAPIGatewayRestAPI_Endpoint_private
=== PAUSE TestAccAPIGatewayRestAPI_Endpoint_private
=== CONT  TestAccAPIGatewayRestAPI_Endpoint_private
--- PASS: TestAccAPIGatewayRestAPI_Endpoint_private (15.65s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/apigateway	21.048s
```

I can't test in ISO(B).

I'll update the `aws_api_gateway_rest_api` documentation.
