### ISSUE TITLE
Multi region for module

### ISSUE THREAD

**Issue by lyc0221** [hashicorp/terraform-provider-aws#22586]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Info

* The provider aws is undefined, but I have defined in the `providers.tf`
* Vpc_id `data.aws_vpc.default.id` only get the value from the region `us-east-1`, not `us-west-1`

```
2022-01-14T12:15:51.751+0800 [TRACE] Context.Input: Prompting for provider arguments
2022-01-14T12:15:51.751+0800 [TRACE] Context.Input: Provider provider.aws declared at providers.tf:1,1-15
2022-01-14T12:15:51.751+0800 [TRACE] Context.Input: Provider provider.aws.usw1 declared at providers.tf:7,1-15
2022-01-14T12:15:51.751+0800 [TRACE] Context.Input: Provider provider.terraform implied by data block at data.tf:5,1-45
2022-01-14T12:15:51.752+0800 [TRACE] Context.Input: Input for provider.aws.usw1: map[string]cty.Value{}
2022-01-14T12:15:51.752+0800 [TRACE] Context.Input: No schema available for provider type "terraform"
2022-01-14T12:15:51.752+0800 [TRACE] Context.Input: Input for provider.aws: map[string]cty.Value{}

╷
│ Warning: Provider aws is undefined
│
│   on main.tf line 253, in module "security_group2":
│  253:     aws = aws.usw1
│
│ Module module.security_group2 does not declare a provider named aws.
│ If you wish to specify a provider configuration for the module, add an entry for aws in the required_providers block within the module.
╵
```

### Affected Resource(s)

aws_security_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

backend.tf
```
terraform {
  required_version = ">= 0.13"
  required_providers {
    aws = {
      source = "hashicorp/aws"
      configuration_aliases = [ aws.usw1 ]
    }
  }

  backend "s3" {
    bucket     = "terraform"
    key        = "terraform_prod-sg.tfstate"
    region     = "ap-southeast-1"
    access_key = "xxxxxx"
    secret_key = "xxxxxx"
    encrypt    = "true"
  }
}
```
data.tf
```
data "aws_vpc" "default" {
  default = true
}
```
main.tf
```
locals {
  ingress_rules = {
    consul = ["consul-tcp", "consul-webui-tcp", "consul-dns-tcp", "consul-dns-udp"]
    consul-2 = ["consul-serf-lan-tcp", "consul-serf-lan-udp", "consul-serf-wan-tcp", "consul-serf-wan-udp"]
    demo = ["mongodb-tcp"]
  }
  ingress_cidr_blocks = {
    consul = concat(
      ["172.31.96.0/22"],
    )
    consul-2 = concat(
      ["172.31.96.0/22"],
    )
    demo = concat(
      ["172.31.96.0/22"],
    )
  }
  ingress_with_cidr_blocks = {
    consul = []
    consul-2 = []
    demo = []
  }
  ingress_ipv6_cidr_blocks = {
    consul = []
    consul-2 = []
    demo = []
  }
  egress_rules        = {
    consul = []
    consul-2 = []
    demo = []
  }
}

variable "access_key" {
}

variable "secret_key" {
}

variable "user" {
  default = "lyc"
}

variable "groups_use1" {
  default     = [
    "consul",
    "consul-2",
  ]
}

variable "groups_usw1" {
  default     = [
    "demo",
  ]
}

variable "environment" {
  default = "prod"
}

variable "region" {
  default = {
    "consul": "us-east-1",
    "consul-2": "us-east-1",
    "demo": "us-west-1",
  }
}

variable "project" {
  default = "app"
}

module "security_group" {
  for_each    = toset(var.groups_use1)

  source      = "../../modules/aws-security-group"

  service     = format("%s-%s", var.project, trimsuffix(each.key, "-2"))
  environment = var.environment
  region      = substr(each.key, -2, -1) == "-2" ? format("%s-%s", var.region[each.key], "2") : var.region[each.key]
  description = format("Security group for %s", trimsuffix(each.key, "-2"))
  vpc_id      = data.aws_vpc.default.id

  ingress_rules            = local.ingress_rules[each.key]
  ingress_cidr_blocks      = local.ingress_cidr_blocks[each.key]
  ingress_with_cidr_blocks = local.ingress_with_cidr_blocks[each.key]
  ingress_ipv6_cidr_blocks = local.ingress_ipv6_cidr_blocks[each.key]
  egress_rules             = local.egress_rules[each.key]
}
  
module "security_group2" {
  for_each    = toset(var.groups_usw1)

  source      = "../../modules/aws-security-group"

  service     = format("%s-%s", var.project, trimsuffix(each.key, "-2"))
  environment = var.environment
  region      = substr(each.key, -2, -1) == "-2" ? format("%s-%s", var.region[each.key], "2") : var.region[each.key]
  description = format("Security group for %s", trimsuffix(each.key, "-2"))
  vpc_id      = data.aws_vpc.default.id

  ingress_rules            = local.ingress_rules[each.key]
  ingress_cidr_blocks      = local.ingress_cidr_blocks[each.key]
  ingress_with_cidr_blocks = local.ingress_with_cidr_blocks[each.key]
  ingress_ipv6_cidr_blocks = local.ingress_ipv6_cidr_blocks[each.key]
  egress_rules             = local.egress_rules[each.key]

  providers = {
    aws = aws.usw1
  }
}
```
providers.tf
```
provider "aws" {
  region = "us-east-1"
  access_key = var.access_key
  secret_key = var.secret_key
}

provider "aws" {
  alias  = "usw1"
  region = "us-west-1"
  access_key = var.access_key
  secret_key = var.secret_key
}
```

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @lyc0221 👋 Thank you for taking the time to raise this. I went through a bit of digging and was able to figure out what's going on here. The document that ultimately gave me the information necessary was found [here](https://www.terraform.io/language/modules/develop/providers#passing-providers-explicitly).

Currently, you have the `configuration_aliases = [ aws.usw1 ]` in the root module. This would only be needed (within the module's provider requirement -- more on that below) if you had a module that needed an aliased provider (e.g. the module itself was affecting two different regions), and so may be omitted entirely in this case.

This is probably easier described by showing you the test configuration that I used to verify my findings, so I'll outline that below.

My configuration directory is laid out as follows:

```shell
.
├── aws
│   └── main.tf
└── main.tf
```

The `main.tf` for the root module contains the following:

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

provider "aws" {
  region = "us-west-1"
  alias = "usw1"
}

module "east" {
  source = "./aws"
}

module "west" {
  source = "./aws"
  providers = {
    aws = aws.usw1
  }
}

output "east" {
  value = module.east.region
}

output "west" {
  value = module.west.region
}
```

Note that I have a "regular" version of the AWS provider defined (e.g. no `alias`) as well as an aliased one. Note also that when I'm calling the modules, only one of them has the `providers` block. This is because the non-aliased one will be inherited by the child module automatically, whereas the aliased one must be explicitly passed to the child module.

The module itself has the following in its `main.tf`:

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

data "aws_region" "current" {}

output "region" {
  value = data.aws_region.current
}
```

Note that in the module, we explicitly require the AWS provider as well. The lack of this explicit requirement is why you're receiving the error that the AWS provider is not defined in your module.

When this configuration is applied, the following is output:

```shell
Outputs:

east = {
  "description" = "US East (N. Virginia)"
  "endpoint" = "ec2.us-east-1.amazonaws.com"
  "id" = "us-east-1"
  "name" = "us-east-1"
}
west = {
  "description" = "US West (N. California)"
  "endpoint" = "ec2.us-west-1.amazonaws.com"
  "id" = "us-west-1"
  "name" = "us-west-1"
}
```

I hope this helps clear up any confusion. If you have any additional questions after reading this and the linked document, please do let me know and I'll be happy to take another look.

**Comment by lyc0221** [comment]
OK, thank you for you reply.

How can I use one modules for two region ? like this ?

```
module "we" {
  for_each = toset(["east", "west"])

  source = "./aws"
  providers = {
    aws =  each.key == "west" ? aws.usw1 : aws
  }
}
```

**Comment by lyc0221** [comment]
any update ?

**Comment by justinretzolk** [comment]
Hey @lyc0221 I looked into this a bit more, and it doesn't look like interpolation for the `providers` block within a module can be interpolated like that, so you'll most likely need to call the module separately for each aliased version of the provider as I'd done in my example above. This is mentioned in the documentation I linked on my last reply here:

> Since the association between resources and provider configurations is static, module calls using for_each or count cannot pass different provider configurations to different instances. If you need different instances of your module to use different provider configurations then you must use a separate module block for each distinct set of provider configurations

If the module will _always_ interact with two separate regions, you can approach it two ways. One method would be to allow the module to inherit the default (non-aliased) provider and also explicitly pass an aliased provider. To do so, you'd need to add the `terraform.required_providers` block within the module (in my example above, this would be within `aws/main.tf` as follows:

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      configuration_aliases = [
        aws.usw1
      ]
    }
  }
}
```

When calling the module, you'd then need to pass a `providers` block that fulfilled this alias requirements, such as:

```hcl
module "test" {
  source = "./aws"
  providers = {
    aws.usw1 = aws.usw1
  }
}
```

The updated version of my sample configuration would then look something like this: 


```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      configuration_aliases = [
        aws.usw1
      ]
    }
  }
}

data "aws_region" "east" {}

data "aws_region" "west" {
  provider = aws.usw1
}

output "east" {
  value = data.aws_region.east
}

output "west" {
  value = data.aws_region.west
}
```

And the `main.tf` in the root configuration would look something like this: 

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

provider "aws" {
  region = "us-west-1"
  alias = "usw1"
}

module "test" {
  source = "./aws"
  providers = {
    aws.usw1 = aws.usw1
  }
}

output "east" {
  value = module.test.east
}

output "west" {
  value = module.test.west
}
```

An alternate approach would be to explicitly set a configuration alias within the module to include the two (or more) separate regions. The `terraform.required_providers` block within the module would then look like this: 

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      configuration_aliases = [
        aws.usw1
        aws.use1
      ]
    }
  }
}
```

And when calling the module, you would need to explicitly set these aliases as follows:

```hcl
module "test" {
  source = "./aws"
  providers = {
    # Since the east region wasn't configured with an alias in the root module, 
    # when calling the module, it's value is just `aws`. Within the module, it will
    # be referred to as `aws.use1`.
    aws.use1 = aws
    aws.usw1 = aws.usw1
  }
}
```

One important thing to note is that taking this path would mean that every resource would need to be given a `provider` block to determine what version of the provider it should use. For example:

```hcl
data "aws_region" "east" {
  provider = aws.use1
}

data "aws_region" "west" {
  provider = aws.usw1
}
```

I hope this helps clear up any lingering confusion! If you have additional questions, it may be better to discuss this in a thread on the [AWS Discuss Forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33); it's generally better suited for questions and ongoing discussion than the comment threads here.

**Comment by rpattcorner** [comment]
@justinretzolk Thanks so much!  After a day of fairly confusing documentation with few examples, you've cleared it up beautifully.  The key thing that isn't as clear as it might be from the doc is that the module receiving the providers needs its own required_modules section with the slightly variant mapping.  Much appreciated.
