### ISSUE TITLE
aws_backup_selection continuously re-creating

### ISSUE THREAD

**Issue by devonbleak** [hashicorp/terraform-provider-aws#22595]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

$ terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.72.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* aws_backup_selection

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_backup_selection" "fox_default_tags" {
  plan_id      = aws_backup_plan.fox_default.id
  name         = "${local.backup_strategy_name}-tags"
  iam_role_arn = aws_iam_role.backup.arn

  selection_tag {
    type  = "STRINGEQUALS"
    key   = "BackupPlan"
    value = local.backup_strategy_name
  }
}
```

### Expected Behavior

No change to this resource after apply if there are no changes to the code

### Actual Behavior

Terraform re-creates the resource on every plan

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`
3. `terraform plan`

**Comment by bootswithdefer** [comment]
Seeing the same, the condition tag is not defined in my config but it always forces replacement.

```
-/+ resource "aws_backup_selection" "tag" {
      ~ id            = "..." -> (known after apply)
        name          = "tag"
      - not_resources = [] -> null
      - resources     = [] -> null
        # (2 unchanged attributes hidden)

      - condition { # forces replacement
        }

        # (1 unchanged block hidden)
    }
```

**Comment by justinretzolk** [comment]
Hey @devonbleak 👋 Thank you for taking the time to raise this. So that we have all of the information we need in order to look into this, can you update the issue description to include debug logs as well?

**Comment by tdmalone** [comment]
Probably caused by https://github.com/hashicorp/terraform-provider-aws/pull/22074

**Comment by leonenkoa** [comment]
I'm not sure that this can be considered as a bug,`condition` and `not_resources` are the same fields as `selection_tag` and `resources`, I mean they have the same logic, moreover as far as I know `selection_tag`(ListOfTags on AWS API side) is an old approach. I think if you will add empty variables `condition` and `not_resources` to your terraform resource the diff will be disappeared.

**Comment by sergey-sml** [comment]
>I think if you will add empty variables `condition` and `not_resources` to your terraform resource the diff will be disappeared.

I can confirm that after addind empty "condition" variable resource stopped recreating. Thanks!

**Comment by rcjames** [comment]
If this is not a bug, then the documentation is not correct as these fields now seem to be required.
https://github.com/hashicorp/terraform-provider-aws/blob/0c9bceeb91afe371c93ad54d4e0103e2b3792a5a/internal/service/backup/selection.go#L48-L52

Defining an empty block for these fields seems like a workaround for a bug rather than a missing piece of configuration, and is probably not good practice.

**Comment by jobwat** [comment]
I'm having the same issue.
```
  # aws_backup_selection.clients[0] must be replaced
-/+ resource "aws_backup_selection" "clients" {
      ...
      - not_resources = [] -> null
        # (3 unchanged attributes hidden)

      - condition { # forces replacement
        }
    }
```
But unlike what's been said earlier, I can't seem to patch it quiet with empty values... 😒 
 
To get it to pass, I added a dummy condition:
```
 condition {
    string_equals {
      key   = "aws:ResourceTag/Project"
      value = var.project_name
    }
  }
```
  
```
Terraform v1.1.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.72.0
```

**Comment by 1robroos** [comment]
I am adding this lifecycle policy , as a workaround. It works for me.
```
lifecycle { 
    ignore_changes = [ 
      condition 
    ] 
  }
```

**Comment by AntonUspehov** [comment]
I'm having the same issue and it's very confusing because it appears every time you ran `tf plan`.
IMHO it's a bug because it recreates resources each time without any reasons for it.

**Comment by ewbankkit** [comment]
Related:

* #22744
* #22627

**Comment by ewbankkit** [comment]
We'll need to make `condition` and `not_resources` _Computed_.

**Comment by frankfong0208** [comment]
> I am adding this lifecycle policy , as a workaround. It works for me.
> 
> ```
> lifecycle { 
>     ignore_changes = [ 
>       condition 
>     ] 
>   }
> ```

I applied this same fix as well with terraform 0.13.5 and it worked for the first time. Then rerunning later it started to fail, complaining about "This object has no argument, nested block, or exported attribute named
"condition""

**Comment by devops-csft** [comment]
Adding condition {} with TF 1.0.2 and aws-provider 3.73.0 worked for me.

**Comment by hyei** [comment]
Adding condition {} with TF 1.0.2 and aws-provider 3.73.0 worked for me.

**Comment by frankfong0208** [comment]
Adding condition {} with TF 0.13.5 and aws-provider 3.23 didn't work for me. It said: 
Blocks of type "condition" are not expected here.

**Comment by mattgirdler** [comment]
> Adding condition {} with TF 0.13.5 and aws-provider 3.23 didn't work for me. It said: Blocks of type "condition" are not expected here.

@frankfong0208 You'll need to use aws-provider version >3.72.0.

**Comment by andreimcristof** [comment]
> I am adding this lifecycle policy , as a workaround. It works for me.
> 
> ```
> lifecycle { 
>     ignore_changes = [ 
>       condition 
>     ] 
>   }
> ```

For me it works with:
```
lifecycle { 
      ignore_changes = [ 
        condition , resources
      ] 
    }
```

**Comment by stratusjerry** [comment]
tangentially related Terraform [is still reporting](https://github.com/hashicorp/terraform-provider-aws/issues/19727#issuecomment-872959198) the derived value **_aws_backup_vault_** : **_recovery_points_** changes as "Objects have changed outside of Terraform"
