### ISSUE TITLE
error creating API Gateway v2 integration: BadRequestException: Unable to retrieve listener port and load balancer DNS name from ELB listener

### ISSUE THREAD

**Issue by piotrkorlaga** [hashicorp/terraform-provider-aws#22590]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Sometimes (not always) I'm getting an error:
```
error creating API Gateway v2 integration: BadRequestException: Unable to retrieve listener port and load balancer DNS name from ELB listener
```
 for some `aws_apigatewayv2_integration` resources. The interesting part is that the other `aws_apigatewayv2_integration` resources, which uses the same load balancer, are created without any issue. 

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v1.1.0
on darwin_amd64
```
### Affected Resource(s)

* aws_apigatewayv2_integration

### Terraform Configuration Files

```
resource aws_apigatewayv2_vpc_link link {
  name = "${var.service_name}-${var.environment}"
  security_group_ids = var.security_group_ids
  subnet_ids = var.subnet_ids
}

resource aws_apigatewayv2_api http {
  name = "${var.service_name}-${var.environment}"
  protocol_type = "HTTP"
}

resource aws_apigatewayv2_integration integration {
  api_id = aws_apigatewayv2_api.http.id
  integration_type = "HTTP_PROXY"
  integration_method = "ANY"
  integration_uri = var.lb_listener_arn
  connection_id = aws_apigatewayv2_vpc_link.link.id
  connection_type = "VPC_LINK"
}
```

### Panic Output

```╷
│ Error: error creating API Gateway v2 integration: BadRequestException: Unable to retrieve listener port and load balancer DNS name from ELB listener arn arn:aws:elasticloadbalancing:*********:835811189142:listener/app/dev-internal-lb-19/c375e0568dc81f07/5d05e413e9dfc123. Please check that ELB listener exists in account 835811189142
│ 
│   with module.apps.module.uns[0].module.proxy.aws_apigatewayv2_integration.integration,
│   on ../../../http_proxy/main.tf line 58, in resource "aws_apigatewayv2_integration" "integration":
│   58: resource aws_apigatewayv2_integration integration {
│ 
╵
```

### Expected Behavior

API gateway should be created with private integration with ALB listener

### Actual Behavior

I'm getting an error ` error creating API Gateway v2 integration: BadRequestException: Unable to retrieve listener port and load balancer DNS name from ELB listener`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
The ALB listener exists but it is creating before the script with `aws_apigatewayv2_integration`. May it be there is some implicit time dependency between those two resources?

**Comment by justinretzolk** [comment]
Hey @piotrkorlaga 👋 Thank you for taking the time to raise this. So that we have all of the necessary information in order to look into this, can you add the debug output to the issue description as requested in the [bug template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?
