### ISSUE TITLE
aws_cognito_user_pool_client  data source missing 'name' attribute

### ISSUE THREAD

**Issue by keitharogers** [hashicorp/terraform-provider-aws#22593]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```bash
Terraform v1.1.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.72.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/integrations/github v4.14.0
```

### Affected Resource(s)

* aws_cognito_user_pool_client (datasource)
* aws_cognito_user_pool_clients (datasource)

### Terraform Configuration Files

```hcl
data "aws_cognito_user_pool_clients" "tools" {
  user_pool_id = aws_cognito_user_pool.tools.id
}

data "aws_cognito_user_pool_client" "tools" {
  for_each     = data.aws_cognito_user_pool_clients.tools.client_ids
  client_id    = each.value
  user_pool_id = aws_cognito_user_pool.tools.id
}

output "names" {
  value = data.aws_cognito_user_pool_client.tools.*.name
}
```

### Expected Behaviour

Output should list all Cognito user pool app-client names for given user pool.

### Actual Behaviour

```bash
Error: Invalid for_each argument
│
│   on opensearch.tf line 6, in data "aws_cognito_user_pool_client" "tools":
│    6:   for_each     = data.aws_cognito_user_pool_clients.tools.client_ids
│     ├────────────────
│     │ data.aws_cognito_user_pool_clients.tools.client_ids is list of string with 2 elements
│
│ The given "for_each" argument value is unsuitable: the "for_each" argument must be a map, or set of strings, and you have provided a value of type list of string.
```

Tried to fix this error by utilising `toset` as follows:

```hcl
data "aws_cognito_user_pool_client" "tools" {
  for_each     = toset(data.aws_cognito_user_pool_clients.tools.client_ids)
  client_id    = each.value
  user_pool_id = aws_cognito_user_pool.tools.id
}
```

Which appeared to get past the first error, but then I encountered an `unsupported attribute` error instead:

```bash
Error: Unsupported attribute
│
│   on opensearch.tf line 12, in output "names":
│   12:   value = data.aws_cognito_user_pool_client.tools.*.name
│
│ This object does not have an attribute named "name".
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

This is a brand new datasource released yesterday.

### References

* https://github.com/hashicorp/terraform-provider-aws/pull/22477

**Comment by keitharogers** [comment]
@danquack : Thanks for implementing this datasource, but appears there is a bug with it (unless I'm missing something). I've raised this issue accordingly.

**Comment by danquack** [comment]
This is bad documentation on my part. `data "aws_cognito_user_pool_client" "tools"` is outputting as `{clientId: client properties}`. Ive solved this in the past with looping, but I am not sure that's the cleanest way. 

I just ran this locally and was able to get a list of client ids, but there might be a cleaner solution:
```terraform
resource "aws_cognito_user_pool" "pool" {
  name = "pool"
}

data "aws_cognito_user_pool_clients" "main" {
  user_pool_id = aws_cognito_user_pool.pool.id
}

data "aws_cognito_user_pool_client" "client" {
  for_each     = toset(data.aws_cognito_user_pool_clients.main.client_ids)
  client_id    = each.value
  user_pool_id = aws_cognito_user_pool.pool.id
}

output "names" {
  value = [
      for k,v in data.aws_cognito_user_pool_client.client : v
  ].*.name
}
```

**Comment by keitharogers** [comment]
@danquack : I've copied and pasted what you put in your output section changing it out for my use case and it's returned exactly what I needed. Thanks for that!!

**Comment by danquack** [comment]
Any chance you can PR the improve the docs with your code? 
https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/d/cognito_user_pool_client.markdown

**Comment by keitharogers** [comment]
Yep, I was planning on it, more than happy to do!

**Comment by keitharogers** [comment]
Thanks @danquack . Yep, I was still planning on contributing, although due to a bit of a chicken and egg situation, my solution is breaking the traditional good practices of how Terraform should work and it's quite messy!! I only just came up with it yesterday as well so wanted to review it again before committing to putting something out there, but yes, very much looking to contribute where I can, just want to make sure it's understandable and following best practice so I don't muddy any waters :-)

Thanks again for your help with all this!
