### ISSUE TITLE
Failed to delete the RDS Options Group using module

### ISSUE THREAD

**Issue by nutakkimurali** [hashicorp/terraform-provider-aws#22598]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.10
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.68.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* aws_db_option_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
module "db" {
  source = "./modules/rds"

  identifier = "${local.identifier}"

  engine            = var.engine
  engine_version    = var.engine_version
  instance_class    = var.instance_class
  allocated_storage = var.allocated_storage
  storage_encrypted = var.storage_encrypted
  kms_key_id        = "arn:aws:kms:${var.aws_region}:${var.account_id}:key/${data.aws_ssm_parameter.kms_keyid.value}"
  ##license_model     = "${var.license_model}"

  # Make sure that database name is capitalized, otherwise RDS will try to recreate RDS instance every time
  name                                = "${upper(local.identifier)}"
  username                            = var.username
  password                            = data.aws_ssm_parameter.rds_password.value
  #password                            = var.password
  port                                = var.port
  ##iam_database_authentication_enabled = false

  vpc_security_group_ids = [var.sg_mysql_rds]
  
  maintenance_window     = var.maintenance_window
  backup_window          = var.backup_window
  
  multi_az            = var.multi_az
  
  # disable backups to create DB faster
  copy_tags_to_snapshot  = var.copy_tags_to_snapshot

  # disable backups to create DB faster
  backup_retention_period = var.backup_retention_period

  tags = "${local.tags}"

  # disable RDS Minor version upgrade
  auto_minor_version_upgrade = "false"
  
  #enabled_cloudwatch_logs_exports = ["audit", "general"]

  # DB subnet group
  subnet_ids = var.priv_subnets

  # DB parameter group
  family = "mysql8.0"
  
  # DB option group
  major_engine_version = "8.0"

  # Snapshot name upon DB deletion
  final_snapshot_identifier = "xxxxxxxx"
  
  # See here for support character sets https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.OracleCharacterSets.html
  ##character_set_name = "AL32UTF8"
  
 
  parameters = [
    {
      name = "log_bin_trust_function_creators"
      value = "1"	  
    },
	{
      name = "max_heap_table_size"
      value = "4294967296"
    }
	
  ]
  
}
```

### Expected Behavior

If Terraform Destroy is applied, the RDS DB Options Group should be removed.

### Actual Behavior

Terraform destroy failed with the following message:

Error Deleting DB Option Group: InvalidOptionGroupStateFault: The option group 'xxxxxxxx-20220114191446065900000002' cannot be deleted because it is in use.
│       status code: 400, request id: xxxx-xxxx-xxxx-xxxx-xxxxxxx

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @nutakkimurali 👋 Thank you for taking the time to raise this. So that we have all of the necessary information in order to look into this, can you update the issue description to include the Terraform configuration, provider and Terraform versions, and debug logs?

**Comment by nutakkimurali** [comment]
@justinretzolk Updated the requested details. Terraform was unable to complete the destruction due to options groups being used by the final snapshot. It would be helpful if Terraform could somehow internally associate a final snapshot with the default option group to avoid locking resources within the same state file.

**Comment by nutakkimurali** [comment]
@justinretzolk This issue needs to be moved under the terraform-aws-rds module/repository.

**Comment by justinretzolk** [comment]
Hey @nutakkimurali -- thanks for the update. As far as moving the issue, that would require permissions that I don't believe any of us have (if I recall correctly, you have to be an admin on both repos in order to move an issue, or something like that). You'll likely need to open a new issue under that repository in order to move it over there. Do you feel this issue should be closed, or kept open in the meantime?

**Comment by nutakkimurali** [comment]
@justinretzolk Just opened an issue under the terraform-aws-rds module/repository for proper tracking and closing this issue

https://github.com/terraform-aws-modules/terraform-aws-rds/issues/371
