### ISSUE TITLE
Resource aws_glue_connection missing vpd id attribute

### ISSUE THREAD

**Issue by reachbadal** [hashicorp/terraform-provider-aws#22607]
Resource aws_glue_connection has a placeholder block physical_connection_requirements
From the console it is possible to associate a vpc for this connection.

The physical_connection_requirements documentation does not seem to have an attribute for vpc id.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_connection

Is this just a documentation error. If so whats the name of the attribute for specifying the vpc ?

**Comment by DrFaust92** [comment]
Hi @reachbadal the vpc is infred via the relevant subnet when passing https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_connection#subnet_id

**Comment by reachbadal** [comment]
@DrFaust92 Thanks.. You are right.. When I provided the subnet_id, it inferred the associated VPC and I see that in the terraform plan trace.
