### ISSUE TITLE
Migrate from Keybase's Go OpenPGP crypto fork to ProtonMail's

### ISSUE THREAD

**Issue by nikolay** [hashicorp/terraform-provider-aws#22602]
[Keybase's Go crypto fork](https://github.com/keybase/go-crypto) is unmaintained having its last commit dated Jan 23, 2020. The active major fork is [ProtonMail's](https://github.com/ProtonMail/go-crypto). The upstream's library has been frozen and deprecated and [ProtonMail's fork](https://github.com/ProtonMail/go-crypto) is [listed](https://github.com/golang/go/issues/44226) as one of the two recommendations. In addition to migrating to an active and popular fork, new features like ECC support would be added 'for free.'

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_iam_access_key
* aws_iam_user_login_profile

### References

* #15384

**Comment by ewbankkit** [comment]
Relates: #9769.
