### ISSUE TITLE
aws_appstream_fleet_stack_association not working correctly

### ISSUE THREAD

**Issue by pmcenery-bl** [hashicorp/terraform-provider-aws#22625]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `aws_appstream_fleet_stack_association`

### Terraform Configuration Files

The example provided [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appstream_fleet_stack_association) does not seem to create an `aws_appstream_fleet_stack_association` in the state, yet the association itself seems to be created in AWS.

```hcl
resource "aws_appstream_stack" "stack" {
  count = local.appstream.create_as ? 1 : 0

  name         = "Stack"

  tags = local.tags
}

resource "aws_appstream_fleet" "fleet" {
  count = local.appstream.create_as ? 1 : 0

  name                               = "Fleet"
  image_name                         = "Firefox-Image"
  instance_type                      = "stream.standard.small"
  idle_disconnect_timeout_in_seconds = 3600
  enable_default_internet_access     = false
  fleet_type                         = "ALWAYS_ON"

  compute_capacity {
    desired_instances = 2
  }

  vpc_config {
    subnet_ids         = module.vpc.private_subnets
  }

  tags = local.tags
}

resource "aws_appstream_fleet_stack_association" "stack_fleet" {
  count = local.appstream.create_as ? 1 : 0

  fleet_name = aws_appstream_fleet.fleet.0.name
  stack_name = aws_appstream_stack.stack.0.name
}
```

### Expected Behavior

The association should be created in the state

### Actual Behavior

Terraform believes that the association was not created in a subsequent run, and then tries to create it - but finds that it already exists. You then have to import the resource manually.

If you then update or taint a stack, there appears to be a missing dependency to re-create the association.

### Steps to Reproduce

1. Create the resources in the example or the above code.
2. Update the stack definition or taint it.
3. Try to apply it

### Output (new resource)

```text
Error: error reading AppStream Fleet Stack Association (Stack/Fleet): No stack "Fleet" associated with fleet "Stack"
```

### Output (updating stack resource)

```text
aws_appstream_stack.stack[0]: Destroying... [id=Stack]

Error: error deleting Appstream Stack (Stack): ResourceInUseException: Cannot delete stack Stack. This stack has fleets associated with it. Only stacks with no fleets associated with it can be deleted.
```

Looking at the creating a resource error output, it looks like "fleet_name" and "stack_name" are somehow inverted somewhere in the logic. I have double checked my references and they are correct - which leads me to believe they might be swapped in the logic of the provider somehwere...

**Comment by hblackmcn** [comment]
I am facing the exact issue! any solution to resolve this issue?

**Comment by pmcenery-bl** [comment]
> I am facing the exact issue! any solution to resolve this issue?

The workaround appears to be to import the resource. It seems to create correctly, but never end up in the state. After you import it, the state seems consistent.

**Comment by tonnamb** [comment]
A temporary workaround (until this bug is fixed), that I'm testing is:
```
resource "null_resource" "anno_associate_fleet_stack" {
  # Requires the fleet and stack to be provisioned first. This also ensures
  # that the disassociation occurs before the fleet and stack are destroyed.
  depends_on = [aws_appstream_fleet.fleet,
                aws_appstream_stack.stack]

  triggers = {
    appstream_fleet = aws_appstream_fleet.fleet.id
    appstream_stack = aws_appstream_stack.stack.id
  }

  provisioner "local-exec" {
    command = "aws appstream associate-fleet --fleet-name Fleet --stack-name Stack"
  }

  provisioner "local-exec" {
    when = destroy
    command = "aws appstream disassociate-fleet --fleet-name Fleet --stack-name Stack"
  }
}
```

**Comment by zulizzi-cfg** [comment]
Moved my comment from the duplicate issue.

The bug seems to be caused by this line:
https://github.com/hashicorp/terraform-provider-aws/blob/60bd245a93893c6eefae9a84f72f3a22ed7c2305/internal/service/appstream/fleet_stack_association.go#L69

Where the arguments to `EncodeStackFleetID` are not in the right order.

The function for reference:
```
func EncodeStackFleetID(fleetName, stackName string) string {
	return fmt.Sprintf("%s/%s", fleetName, stackName)
}
```

**Comment by joshmears169** [comment]
Any update on this at all? Appreciate any help!

**Comment by rednevals** [comment]
I have the same issue, maybe...

When I build a fleet/stack, including the stack association resource, the apply runs and I get this error:
```
Error: error reading AppStream Fleet Stack Association (My-Stack/My-Fleet): No stack "My-Fleet" associated with fleet "My-Stack"
```
When viewing from the AWS console, the stack and fleet are associated correctly. Next I tried to add a dependency in attempt to give Terraform some "guidance".
```
resource "aws_appstream_fleet_stack_association" "fleet_stack_association" {
  stack_name = aws_appstream_stack.my_stack.name
  fleet_name = aws_appstream_fleet.my_fleet.name

  depends_on = [aws_appstream_stack.my_stack, aws_appstream_fleet.my_fleet]
}
```

I still get the error. When destroying, I get these errors:
```
Error: error deleting Appstream Fleet (My-Fleet): ResourceInUseException: The fleet My-Fleet is associated with a stack. To delete the fleet, you must dissociate it from the stack.

Error: error deleting Appstream Stack (My-Stack): ResourceInUseException: Cannot delete stack My-Stack. This stack has fleets associated with it. Only stacks with no fleets associated with it can be deleted.
```

I have been using [arnvid/terrafrom-provider-appstream](https://github.com/arnvid/terraform-provider-appstream) without this issue. I was trying to convert to using hashicorp/aws but this issue is a blocker for sure.

**Comment by maati55** [comment]
I have the same issue 
using: hashicorp/aws v4.6.0

```
resource "aws_appstream_fleet_stack_association" "example" {
   fleet_name = aws_appstream_fleet.this.name
   stack_name = aws_appstream_stack.stack.name
}
```

`Error: error reading AppStream Fleet Stack Association (AppStreamStack/wav-dev-asf): No stack "wav-dev-asf" associated with fleet "AppStreamStack"`

Any update on this, please?

**Comment by rednevals** [comment]
> A temporary workaround (until this bug is fixed), that I'm testing is:
> 
> ```
> resource "null_resource" "anno_associate_fleet_stack" {
>   # Requires the fleet and stack to be provisioned first. This also ensures
>   # that the disassociation occurs before the fleet and stack are destroyed.
>   depends_on = [aws_appstream_fleet.fleet,
>                 aws_appstream_stack.stack]
> 
>   triggers = {
>     appstream_fleet = aws_appstream_fleet.fleet.id
>     appstream_stack = aws_appstream_stack.stack.id
>   }
> 
>   provisioner "local-exec" {
>     command = "aws appstream associate-fleet --fleet-name Fleet --stack-name Stack"
>   }
> 
>   provisioner "local-exec" {
>     when = destroy
>     command = "aws appstream disassociate-fleet --fleet-name Fleet --stack-name Stack"
>   }
> }
> ```
> 
> EDIT: from testing, this works some times, but it's still flaky with some inconsistent terraform state errors.

This worked for me... But we really need a permanent fix. It's only one line of code ;)

**Comment by hasnain-tahir** [comment]
this issue is still open @rednevals  has find this quick fix which I tested and it is working

**Comment by rednevals** [comment]
FYI: I sent an email with details to one of the contributors of the commit that caused this issue. Hopefully they will respond. I will create a PR if needed...

**Comment by nieldejonghe** [comment]
Just chiming in here to say I have the same issue and would like to see this solved :)

**Comment by nieldejonghe** [comment]
@hasnain-tahir you mean you fixed it by using the workaround provided by @rednevals ?

**Comment by hasnain-tahir** [comment]
Correct.

**Comment by PatriQ1414** [comment]
Any update on this?
