### ISSUE TITLE
aws_backup_plan enable_continuous_backup rule with no schedule set causes permanent diff

### ISSUE THREAD

**Issue by tomelliff** [hashicorp/terraform-provider-aws#22627]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_backup_plan

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_backup_plan" "example" {
  name = "example"

  rule {
    rule_name                = "continuous"
    target_vault_name        = "Default"
    enable_continuous_backup = true
    # schedule                 = "cron(0 5 ? * * *)"

    lifecycle {
      delete_after       = 35
    }
  }
}
```

### Expected Behavior

With the `schedule` commented out, it should apply and not have a diff.

### Actual Behavior

With the `schedule` not set or commented out it applies but then there is a perpetual diff as Terraform attempts to force it to remove the schedule that AWS automatically sets when it's not present even when that doesn't make sense, such as with a continuous backup rule:

```
  # aws_backup_plan.example will be updated in-place
  ~ resource "aws_backup_plan" "example" {
        id       = "aeb67d66-c6a8-4144-83ea-13e14c576824"
        name     = "example"
        tags     = {}
        # (3 unchanged attributes hidden)

      - rule {
          - completion_window        = 180 -> null
          - enable_continuous_backup = true -> null
          - recovery_point_tags      = {} -> null
          - rule_name                = "continuous" -> null
          - schedule                 = "cron(0 5 ? * * *)" -> null
          - start_window             = 60 -> null
          - target_vault_name        = "Default" -> null

          - lifecycle {
              - cold_storage_after = 0 -> null
              - delete_after       = 35 -> null
            }
        }
      + rule {
          + completion_window        = 180
          + enable_continuous_backup = true
          + rule_name                = "continuous"
          + start_window             = 60
          + target_vault_name        = "Default"

          + lifecycle {
              + delete_after = 35
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Uncommenting the `schedule` parameter makes the diff go away.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ewbankkit** [comment]
Related:

* #22744
* #22595
