### ISSUE TITLE
aws_kinesis_firehose_delivery_stream support for dynamic partitioning including multi record deaggregation

### ISSUE THREAD

**Issue by exeding** [hashicorp/terraform-provider-aws#22623]
**Community Note**
- Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment
**Terraform CLI and Terraform AWS Provider Version**
```
Terraform v1.1.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.72.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/integrations/github v4.14.0
```
**Affected Resource(s)**
- aws_cognito_user_pool_client (datasource)
- aws_cognito_user_pool_clients (datasource)

**Terraform Configuration Files**
```
resource "aws_kinesis_firehose_delivery_stream" "extended_s3_stream" {
  name        = "terraform-kinesis-firehose-extended-s3-test-stream"
  destination = "extended_s3"

  extended_s3_configuration {
    role_arn   = aws_iam_role.firehose_role.arn
    bucket_arn = aws_s3_bucket.bucket.arn

    processing_configuration {
      enabled = "true"

      processors {
        type = "Lambda"

        parameters {
          parameter_name  = "LambdaArn"
          parameter_value = "${aws_lambda_function.lambda_processor.arn}:$LATEST"
        }
      }
    }
  }
}
```

**Expected Behaviour**
Currently its not possible to create the resource with extended dynamic partitioning 
As described within the aws documetion (1) it would a new feature to also enable the dynamic partitioning including to configure the "multi record deaggregation" set to "JSON"

**References**
- (1) https://docs.aws.amazon.com/firehose/latest/dev/dynamic-partitioning.html

**Comment by zhudotexe** [comment]
It looks like there is a way to use multi record deaggregation without any additional changes to the provider - it's just not documented at the moment. I found that `extended_s3_configuration.processing_configuration` was a reflection of the `ExtendedS3DestinationConfiguration.ProcessingConfiguration` key in the [CreateDeliveryStream API](https://docs.aws.amazon.com/firehose/latest/APIReference/API_CreateDeliveryStream.html), and that multi record deaggregation was configured here. 

By using [DescribeDeliveryStream](https://docs.aws.amazon.com/firehose/latest/APIReference/API_DescribeDeliveryStream.html) on a stream with multi record deaggregation enabled that we had created manually, I was able to find the correct configuration to enable this:
```terraform
processing_configuration {
  enabled = true

  # Multi record deaggregation = enabled, Multi record deaggregation type = JSON
  processors {
    type = "RecordDeAggregation"
    parameters {
      parameter_name  = "SubRecordType"
      parameter_value = "JSON"
    }
  }

  # New line delimiter = enabled
  processors {
    type = "AppendDelimiterToRecord"
  }

  # dynamic partitioning keys
  processors {
    type = "MetadataExtraction"
    parameters {
      parameter_name  = "MetadataExtractionQuery"
      parameter_value = "{combat_id:.combat_id}"
    }
    parameters {
      parameter_name  = "JsonParsingEngine"
      parameter_value = "JQ-1.6"
    }
  }
}
```
This configuration creates the following resource as seen on the AWS console:

<img width="725" alt="Screenshot 2022-02-14 at 11 37 29" src="https://user-images.githubusercontent.com/8866981/153936224-a0a749d6-7302-4084-9801-362948a515a8.png">

Hope this helps!

**Comment by RamonReis** [comment]
This feature should be documented ASAP on the `aws_kinesis_firehose_delivery_stream` resource. I almost gave up on trying to use it on Terraform because I couldn't find the documentation
