### ISSUE TITLE
When using an existing aws_security_group cannot use aws_security_group_rule together

### ISSUE THREAD

**Issue by spstarr** [hashicorp/terraform-provider-aws#22642]
### Terraform CLI and Terraform AWS Provider Version
3.59.0
Terraform v0.13.7

### Affected Resource(s)
aws_security_group_rule

### Terraform Configuration Files
```
resource "aws_security_group" "my_external_sg" {
    name = "${var.env}-external-sg"
    description = "My External"
    vpc_id = aws_vpc.my_vpc.id
    depends_on = [aws_vpc.my_vpc]

    egress {
        from_port = 0
        to_port = 0
        protocol = -1 
        cidr_blocks = ["0.0.0.0/0"]
    }

    ingress {
        description = "Allow HTTPS connections from somewhere
        from_port = 443
        to_port = 443
        protocol = "tcp"
        security_groups = [aws_security_group.main_security_sg.id]
    }

    ingress {
         description = "Prefix List - Connections from secure places"
         from_port = 443
         to_port = 443
         protocol = "tcp"
         prefix_list_ids = [aws_ec2_managed_prefix_list.my_vpc_pl.id]
    }

    ingress {
        description = var.env == "production" ? "Service from Production" : "Service from Staging"
        from_port = 443
        to_port = 443
        protocol = "tcp"
        cidr_blocks = var.env == "production" ? ["1.2.3.4/32"] : ["8.8.8.8/32"]
    }

    ingress {
        description = var.env == "production" ? "My Other service Production" : "My Other service Development"
        from_port = 443
        to_port = 443
        protocol = "tcp"
        cidr_blocks = var.env == "production" ? ["1.1.1.1/32"] : ["4.4.4.4/32"]
    }

    tags = merge(
      local.common_tags,
      map(
        "additional_tag", "info"
      )
    )
}

# A production only
resource "aws_security_group_rule" "a_sg_rule" {
  security_group_id = aws_security_group.my_external_sg.id
  count     = var.env== "production" ? 1 : 0
  description = "A production"
  type      = "ingress"
  from_port = 443
  to_port   = 443
  cidr_blocks = ["7.8.9.0/32"]
  protocol  = "tcp"
}

# B production only
resource "aws_security_group_rule" "b_sg_rule" {
  security_group_id = aws_security_group.my_external_sg.id
  count     = var.env== "production" ? 1 : 0
  description = "B production"
  type      = "ingress"
  from_port = 443
  to_port   = 443
  cidr_blocks = ["3.4.5.6/32"]
  protocol  = "tcp"
}
```

### Debug Output
Terraform provider will not append both rules to the security group, if I run terraform add/remove them each time ran.

### Expected Behavior
Both rules get appended to the main security group

### Actual Behavior
Terraform adds the additional rules, run terraform again, removes rules.

### Steps to Reproduce
See code

**Comment by spstarr** [comment]
This seems to reference https://github.com/hashicorp/terraform/issues/5147 ... cannot mix them still.

**Comment by spstarr** [comment]
Has there been any movement on this functionality or plans?

**Comment by justinretzolk** [comment]
Hey @spstarr 👋 This behavior is how we would expect these resources to interact at the moment. This is called out in the `aws_security_group` and `aws_security_group_rule` documentation as:

> Terraform currently provides both a standalone Security Group Rule resource (a single `ingress` or `egress` rule), and a Security Group resource with `ingress` and `egress` rules defined in-line. At this time you cannot use a Security Group with in-line rules in conjunction with any Security Group Rule resources. Doing so will cause a conflict of rule settings and will overwrite rules.

I don't believe there are any plans to change this any time soon, as the inline rules assumes that _all_ rules will be defined inline, and so mixing the two resource types would result in two separate [Terraform] resources attempting to manage the same [AWS] resource(s). We're always open to input though, so if you have additional input, we'd be happy to hear it!

**Comment by spstarr** [comment]
I've converted to blank **aws_security_group** just with vpc + name, tags and all the entries as **aws_security_group_rule**

I wish though Terraform's parser would be able to pre-process things first, map the existing rules inside a **aws_security_group** and associate with its own pointer to the **aws_security_group_rule** entries, conflicts would error of course if both the **aws_security_group** contained duplicated rules.

Since the tfstate file is Terraform's own syntax it could be done

**Comment by spstarr** [comment]
I can close this though as the solution found elsewhere works.
