### ISSUE TITLE
aws_secretsmanager_secret_version data source unable to retrieve secret value

### ISSUE THREAD

**Issue by divyakarthik33** [hashicorp/terraform-provider-aws#22653]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
terraform 0.12.31
aws provider 3.72.0
lacework 0.14.0

### Affected Resource(s)

* aws_secretsmanager_secret_version data source
* The issue is that I am unable to retrieve the secret when I specify an ARN in my IAM policy. It only works when I set resources to "*" -  but I do not want to do this.

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "aws_secretsmanager_secret_version" "my_api_keys" {
  secret_id = var.ssm_secret_name
}
provider "lacework" {
  alias      = "lacework_alias"
  account    = "myaccountname"
  subaccount = var.sub_account 
  api_key    = jsondecode(data.aws_secretsmanager_secret_version.my_api_keys.secret_string)["api_key"]
  api_secret = jsondecode(data.aws_secretsmanager_secret_version.my_api_keys.secret_string)["api_secret"]
}
```

### Expected Behavior

Retrieve secret 

### Actual Behavior

`error reading Secrets Manager Secret Version: AccessDeniedException: User: arn:aws:sts::<account number>:assumed-role/<iam-role>/<instance id> is not authorized to perform: secretsmanager:GetSecretValue on resource: <resoruce_name> because no identity-based policy allows the secretsmanager:GetSecretValue action
`
### Steps to Reproduce

Run terraform plan on given terraform code, with IAM permissions restricted to arn of secret.Secret has no rotation enabled and uses default encryption. 

1. `terraform apply`

### Important Factoids

My IAM permissions are as follows. Again on terraform this only works when resources is "*", on the AWS CLI it works with ARN specified, so I believe this is a terraform related issue. 
```
"secretsmanager:List*",
"secretsmanager:Get*"
```
### References

* #0000

**Comment by justinretzolk** [comment]
Hey @divyakarthik33 👋 Thank you for taking the time to raise this. So that we have all of the necessary information in order to look into this, can you update the issue description with the rest of the information requested in the [bug template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?

**Comment by divyakarthik33** [comment]
@justinretzolk Updated.

**Comment by divyakarthik33** [comment]
Hi is there any update on this? Thanks. @justinretzolk

**Comment by divyakarthik33** [comment]
Resolevd: Secret was stored in different region than aws provider.
