### ISSUE TITLE
appstream stack has issue with setting user_settings

### ISSUE THREAD

**Issue by hblackmcn** [hashicorp/terraform-provider-aws#22652]
Hi team, when trying to apply terraform plan to create appstream stack, I got following error which shows there is a bug in the provider. This is a blocker for our project, please kindly assist and look into this:

_│ learned so far during apply, provider "registry.terraform.io/hashicorp/aws"                                                                                    
│ produced an invalid new value for .user_settings: actual set element                                                                                           
│ cty.ObjectVal(map[string]cty.Value{"action":cty.StringVal("PRINTING_TO_LOCAL_DEVICE"),                                                                         
│ "permission":cty.StringVal("ENABLED")}) does not correlate with any element                                                                                    
│ in plan.                                                                                                                                                       
│                                                                                                                                                                
│ This is a bug in the provider, which should be reported in the provider's                                                                                      
│ own issue tracker.                                                                                                                                             
╵                                                                                                                                                                
╷                                                                                                                                                                
│ Error: Provider produced inconsistent final plan                                                                                                               
│                                                                                                                                                                
│ When expanding the plan for aws_appstream_stack.main to include new values                                                                                     
│ learned so far during apply, provider "registry.terraform.io/hashicorp/aws"                                                                                    
│ produced an invalid new value for .user_settings: block set length changed                                                                                     
│ from 4 to 7.                                                                                                                                                   
│                                                                                                                                                                
│ This is a bug in the provider, which should be reported in the provider's                                                                                      
│ own issue tracker.                                                                                                                                             
╵_

**Comment by justinretzolk** [comment]
Hey @hblackmcn 👋 Thank you for taking the time to raise this. So that we have all of the information necessary to look into this, can you update the issue description with the information requested in the [bug template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?
