### ISSUE TITLE
IOT: Add resource for domain configurations

### ISSUE THREAD

**Issue by strati1991** [hashicorp/terraform-provider-aws#22654]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the aws console in the settings panel of AWS Iot Core service it is possible to add domain configurations to provide a cname entry that routes to the iot endpoint. 
It would be great to have a terraform resource for defining such a domain name configuration.

### Potential Terraform Configuration

```hcl
# Where the name of the resource is unique and several domain name configurations can be created.
resource "aws_iot_domain_name_configuration" "example" {
  name = "example"
  domain_name = "example.dev.com"
  server_certificate_arns = ["arn1", "arn2"]
}

```

### References

This resource can be created via the aws cli command: https://docs.aws.amazon.com/cli/latest/reference/iot/create-domain-configuration.html

* #0000

**Comment by lohrm-stabl** [comment]
There is a PR implementing exactly this, which I think is basically finished and ready to be merged: https://github.com/hashicorp/terraform-provider-aws/pull/24765

```terraform
resource "aws_iot_domain_configuration" "iot" {
  name         = "iot-"
  domain_name  = "iot.example.com"
  service_type = "DATA"
  server_certificate_arns = [
    aws_acm_certificate.cert.arn
  ]
}
```

**Comment by aitormontenegro** [comment]
Any updates on this? I need this feature for a project I'm working on.
