### ISSUE TITLE
 aws_api_gateway_rest_api should provide warning output (#4274 repeat)

### ISSUE THREAD

**Issue by paulgear** [hashicorp/terraform-provider-aws#22674]
This is a repeat of #4274 as a bug, because that's what I think it is.  There are many semantic errors which can be made when importing or updating an OpenAPI/Swagger spec (using the `body` argument), and these are never surfaced by the `aws_api_gateway_rest_api` resource.

This is because the provider calls [APIGateway.PutRestApi](https://docs.aws.amazon.com/sdk-for-go/api/service/apigateway/#APIGateway.PutRestApi) without specifying FailOnWarnings (which defaults to false) in the [PutRestApiInput](https://docs.aws.amazon.com/sdk-for-go/api/service/apigateway/#PutRestApiInput):

- https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/apigateway/rest_api.go#L217
- https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/apigateway/rest_api.go#L598

This violates the principle of least astonishment because the body reported in the resource output is what was provided to the resource, but it is rejected by the AWS APIs and never applied to the API Gateway.  This means it's impossible to debug using only terraform.  (I ended up expanding the template manually into a file and attempting to import this into API Gateway to debug it.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.10
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.72.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s)

* aws_api_gateway_rest_api

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

- [main.tf](https://gist.github.com/paulgear/7bce944430fe48011a3e3aa598915bfe)
- [api.json](https://gist.github.com/paulgear/59bf1dc41b7924969a5e6a30a9709c8f)
- [default_policy.json](https://gist.github.com/paulgear/df549ef38cedc9d6238bd74c1eaaa3b9)
- [Documentation from Auth0 about the solution](https://auth0.com/docs/customize/integrations/aws/aws-api-gateway-custom-authorizers), for additional context, if needed

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

- We should be able to see why our API body import is failing.

### Actual Behavior

- terraform plan/apply completes successfully with no errors, but our API body changes were not imported.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

- The current [AWS API docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-authorizer.html) are out-of-date with respect to OpenAPI 3.x (specifically with respect to the [naming and placement of `securityDefinitions`](https://swagger.io/docs/specification/authentication/), and working from the examples provided there results in a non-functional API gateway authorizer, which makes it all the more important that terraform provide a way to debug it.

### References

* #4274
* I'll attempt a draft PR on this shortly, but as a non-native golang speaker, I expect it will need some assistance to make it through the PR process.

**Comment by paulgear** [comment]
@justinretzolk Gotta say I'm a bit disappointed with the classification of enhancement, especially since I clearly indicated in the overview that I didn't think it was one. At least without any clarifying comment it feels like a bit of a slap in the face after the 2 days of debugging I spent on it this week.

**Comment by justinretzolk** [comment]
Hey @paulgear -- that was definitely an oversight on my part; I apologize for that misclassification. I agree this seems like a bug, and have added the appropriate tag to reflect that.

**Comment by paulgear** [comment]
Thanks @justinretzolk - I'll try to do some more work on getting the PR in shape this week.
