### ISSUE TITLE
aws_mwaa_environment missing Scheduler count option

### ISSUE THREAD

**Issue by ramarthuluru** [hashicorp/terraform-provider-aws#22704]
aws_mwaa_environment resource is missing **Scheduler count** option for **Environment class** section. It is using the default value of 2.

**Comment by wedge-jarrad** [comment]
Duplicate of #20185.

**Comment by DrFaust92** [comment]
Duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/20185.
