### ISSUE TITLE
Add aws_athena_data_catalog resource

### ISSUE THREAD

**Issue by hrabeale** [hashicorp/terraform-provider-aws#22714]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add a new aws resource for creating data catalog as documented here

https://docs.aws.amazon.com/athena/latest/APIReference/API_CreateDataCatalog.html

Thank you, kind regards

### New or Affected Resource(s)

* aws_athena_data_catalog

**Comment by bschaatsbergen** [comment]
I'll pick this one up

**Comment by bschaatsbergen** [comment]
Done, #22968 is ready for review (please note the 2 comments)

**Comment by DrFaust92** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/22968
