### ISSUE TITLE
Add support for SageMaker Serverless Endpoint Configuration

### ISSUE THREAD

**Issue by elwinarens** [hashicorp/terraform-provider-aws#22710]
### Description

The SageMaker Endpoint Configuration feature now supports serverless endpoints by defining a `ServerlessConfig` on the variant:

![create_endpoint](https://user-images.githubusercontent.com/1883694/150499077-3255fb75-7469-48b8-a1ed-c1be66825bd2.PNG)

### New or Affected Resource(s)

* `aws_sagemaker_endpoint_configuration`

### Potential Terraform Configuration

```hcl
resource "aws_sagemaker_endpoint_configuration" "ec" {
  name = "my-endpoint-config"

  production_variants {
    variant_name           = "variant-1"
    model_name             = aws_sagemaker_model.m.name
 
    serverless_config {
      max_concurrency   = 10
      memory_size_in_mb = 2048
    }
  }

  tags = {
    Name = "foo"
  }
}
```

Suggestion to make the (provisioned) instance related configuration `instance_type` and `initial_instance_count` xor with the serverless config.

### References

* https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateEndpointConfig.html#API_CreateEndpointConfig_RequestSyntax
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_endpoint_configuration

**Comment by DrFaust92** [comment]
Serverless seems to be in preview and a lot of the non-serverless features are not supported at this time and subject ot change, https://docs.aws.amazon.com/sagemaker/latest/dg/serverless-endpoints.html.

**Comment by mbragg02** [comment]
It is now generally available 🎉 [https://aws.amazon.com/blogs/aws/amazon-sagemaker-serverless-inference-machine-learning-inference-without-worrying-about-servers/](https://aws.amazon.com/blogs/aws/amazon-sagemaker-serverless-inference-machine-learning-inference-without-worrying-about-servers/

**Comment by repl-jeffrey-miiller** [comment]
Any update on this?

**Comment by ronnyb2017** [comment]
We urgently need this :) Any idea by when this will get integrated ?

**Comment by DrFaust92** [comment]
looking into this
