### ISSUE TITLE
Import of aws_vpc_dhcp_options_association fails in v3.73.0

### ISSUE THREAD

**Issue by kanor1306** [hashicorp/terraform-provider-aws#22716]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

aws_provider: v3.73.0
terraform: v1.1.4

### Affected Resource(s)

* aws_vpc_dhcp_options_association

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

The actual issue is while importing resources:

`terraform import module.vpc.aws_vpc_dhcp_options_association.dns_resolver <vpc-id>`

Below manifest could create the needed resources for this import.

```hcl
data "aws_region" "current" {}

resource "aws_vpc" "customer_vpc" {
  cidr_block           = "10.43.4.0/22"
  enable_dns_hostnames = true
  enable_dns_support   = true
}

resource "aws_vpc_dhcp_options" "default_dhcp_options" {
  domain_name         = format("%s%s", data.aws_region.current.name, ".compute.internal")
  domain_name_servers = ["AmazonProvidedDNS"]
}

resource "aws_vpc_dhcp_options_association" "dns_resolver" {
  vpc_id          = aws_vpc.customer_vpc.id
  dhcp_options_id = aws_vpc_dhcp_options.default_dhcp_options.id
}


```

### Expected Behavior

After executing `terraform import module.vpc.aws_vpc_dhcp_options_association.dns_resolver <vpc-id>` the resource should be imported.

### Actual Behavior

After executing `terraform import module.vpc.aws_vpc_dhcp_options_association.dns_resolver <vpc-id>` this error is received:

`Error: unexpected format for ID (default-vpc-0466d39c84de5c49b), expected DHCPOptionsID-VPCID`

Verified that it does work in v3.72.0 of the provider

**Comment by ewbankkit** [comment]
@kanor1306 Thanks for raising this issue.

The bug is here: https://github.com/hashicorp/terraform-provider-aws/blob/6ff11f8f805806d2cfc0bc2177f959b532f9f6f7/internal/service/ec2/vpc_dhcp_options_association.go#L157-L162

If the DHCP Options ID is `default` (which is a valid Options ID) then there are only 3 parts when splitting by `-`.
The previous version of the code used `vpc_id` directly: https://github.com/hashicorp/terraform-provider-aws/blob/b3b3743f54f22cc5424e9bb441f265953e13bf6f/internal/service/ec2/vpc_dhcp_options_association.go#L93

This is a regression and I will fix it ASAP.

**Comment by kanor1306** [comment]
Great! Thanks for the quick action @ewbankkit

**Comment by ryanhestin** [comment]
@ewbankkit I am experiencing this bug on 3.75.1 during an upgrade from `~> 2.0` on 0.12.31.

If I pin the provider to 3.72.0, it passes a plan fine. On everything higher, it fails:

```
Error: unexpected format for ID (dopt-5159a234), expected DHCPOptionsID-VPCID
```
