### ISSUE TITLE
aws_networkfirewall_rule_group: Cannot reference ip_sets in source/destination in header for a stateful rule

### ISSUE THREAD

**Issue by vineetsk50** [hashicorp/terraform-provider-aws#22727]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.72.0

### Affected Resource(s)

* aws_networkfirewall_rule_group

### Terraform Configuration Files

```
resource "aws_networkfirewall_rule_group" "example" {
  capacity = 100
  name     = "example"
  type     = "STATEFUL"
  rule_group {
    rule_variables {
      ip_sets {
        key = "WEBSERVER_HOSTS"
        ip_set {
          definition = ["10.0.0.0/16", "10.0.1.0/24", "192.168.0.0/16"]
        }
      }
    }
    rules_source {
        stateful_rule {
            action = "PASS"
            header {
                destination = "$WEBSERVER_HOSTS"
                source = "0.0.0.0/0"
                destination_port = "443"
                source_port = "ANY"
                protocol = "TCP"
                direction = "ANY"
            }
            rule_option {
                keyword: "sid:1"
            }
        }
    }
  }
}

```

### Expected Behavior

The source/destination in the header should be able to reference the ip_set. This works via AWS Console, AWS CLI, and CloudFormation. This is not working via Terraform

### Actual Behavior

 ```
 Error: "$WEBSERVER_HOST" is not a valid CIDR block: invalid CIDR address: $WEBSERVER_HOST
 ```

### References
Similar issue resolved for ip_set - https://github.com/hashicorp/terraform-provider-aws/issues/22268
AWS Documentation on accepted patterns for source/destination - https://docs.aws.amazon.com/network-firewall/latest/APIReference/API_Header.html

**Comment by midestefanis** [comment]
any news about this? i'm having the same issue

**Comment by midestefanis** [comment]
Hi @vineetsk50, has this worked for you? I keep having problems, now it tells me another error:

`Error: error creating NetworkFirewall Rule Group allowed-private: InvalidRequestException: MEDIADIORES cannot be null or empty, context: RulesSource.RuleVariables.IPSets.MEDIADIORES`

@ewbankkit @jordanfelle Guys, could you put an example in the documentation? Thanks

**Comment by midestefanis** [comment]
@jordanfelle @ewbankkit @vineetsk50 Does anyone know if it is possible to pass two variables in some way? Don't leave me this way:

```
resource "aws_networkfirewall_rule_group" "example" {
  capacity = 100
  name     = "example"
  type     = "STATEFUL"
  rule_group {
    rule_variables {
      ip_sets {
        key = "WEBSERVER_HOSTS_2"
        ip_set {
          definition = ["10.48.208.0/23"]
        }
      }
      ip_sets {
        key = "WEBSERVER_HOSTS"
        ip_set {
          definition = ["10.0.0.0/16", "10.0.1.0/24", "192.168.0.0/16"]
        }
      }      
    }
    rules_source {
        stateful_rule {
            action = "PASS"
            header {
                destination = "$WEBSERVER_HOSTS$WEBSERVER_HOSTS_2"
                source = "0.0.0.0/0"
                destination_port = "443"
                source_port = "ANY"
                protocol = "TCP"
                direction = "ANY"
            }
            rule_option {
                keyword: "sid:1"
            }
        }
    }
  }
}
```

Error:

```
InvalidRequestException: stateful rule is invalid, ***** , reason: not every address block was properly closed in "[***", 1 missing closing brackets (]). Note: problem might be in a variable.
```
