### ISSUE TITLE
Cannot import EKS cloudwatch log group into state

### ISSUE THREAD

**Issue by antonisnyc94** [hashicorp/terraform-provider-aws#22738]
Hello im using terraform `0.14.11` and aws provider `3.73` and for some reason whenever i import an existing cloudwatch log group for EKS control plane logging im getting the following error.

`terraform import module.eks-cluster.aws_cloudwatch_log_group.eks-logs "/aws/eks/eks-cluster/cluster"`

```
module.eks-cluster.aws_cloudwatch_log_group.eks-logs: Importing from ID "/aws/eks/eks-cluster/cluster"...
module.eks-cluster.aws_cloudwatch_log_group.eks-logs: Import prepared!
  Prepared aws_cloudwatch_log_group for import
module.eks-cluster.aws_cloudwatch_log_group.eks-logs: Refreshing state... [id=/aws/eks/eks-cluster/cluster]

Error: Missing required argument

The argument "address" is required, but was not set.
config within module
```

```
resource "aws_cloudwatch_log_group" "eks-logs" {
  name = "/aws/eks/${var.cluster-name}/cluster"
  #retention_in_days = var.eks-log-retention
}
```

This issue can be reproduced by enabling the EKS logging for an existing EKS cluster from the aws console and furthermore trying to import it in statefile using terraform.

any ideas?

Thanks,
Tony

**Comment by justinretzolk** [comment]
Hey @antonisnyc94 👋 Thank you for taking the time to raise this. So that we have all of the necessary information to look into this, can you update the issue description with the rest of the information found in the [bug template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?

**Comment by bryantbiggs** [comment]
Relates to https://github.com/hashicorp/terraform-provider-aws/issues/17839
