### ISSUE TITLE
ECS Task Definitions module uses deprecated dependency

### ISSUE THREAD

**Issue by kvcpr** [hashicorp/terraform-provider-aws#22739]
Module ECS Task Definitions uses deprecated `hashicorp/template` dependency  that's block usage in arm based setup.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.4
on darwin_arm64
```

```
Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/aws] ~> 3.73
├── provider[registry.terraform.io/hashicorp/random] ~> 3.1.0
├── provider[registry.terraform.io/kvcpr/template] 2.2.0-arm
├── module.ecs_service
│   └── provider[registry.terraform.io/hashicorp/aws]
├── module.ecs_task_definitions
│   ├── provider[registry.terraform.io/hashicorp/template]
│   └── provider[registry.terraform.io/hashicorp/aws]
├── module.elasticache
│   └── provider[registry.terraform.io/hashicorp/aws]
├── module.parameter_store
│   ├── provider[registry.terraform.io/hashicorp/aws]
│   └── provider[registry.terraform.io/hashicorp/random]
├── module.s3
│   └── provider[registry.terraform.io/hashicorp/aws]
├── module.cloudfront
│   └── provider[registry.terraform.io/hashicorp/aws]
├── module.ec2
│   └── provider[registry.terraform.io/hashicorp/aws]
├── module.ecr
│   └── provider[registry.terraform.io/hashicorp/aws]
├── module.elb
│   └── provider[registry.terraform.io/hashicorp/aws]
├── module.ecs_cluster
│   └── provider[registry.terraform.io/hashicorp/aws]
└── module.pg
    └── provider[registry.terraform.io/hashicorp/aws]

Providers required by state:

    provider[registry.terraform.io/hashicorp/aws]

    provider[registry.terraform.io/hashicorp/random]

    provider[registry.terraform.io/kvcpr/template]
```

### Affected Resource(s)

* ecs_task_definitions

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
    required_version = ">= 1.0"
    
    required_providers {
        aws = {
            source = "hashicorp/aws"
            version = "~> 3.73"
        }

        random = {
            version = "~> 3.1.0"
        }

        template = {
            source  = "kvcpr/template"
            version = "= 2.2.0-arm"
        }
    }
}
```

### Debug Output
-

### Panic Output
-

### Expected Behavior
Successful `terraform init`

### Actual Behavior
```
➜ terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 3.73"...
- Finding hashicorp/random versions matching "~> 3.1.0"...
- Finding kvcpr/template versions matching "2.2.0-arm"...
- Finding latest version of hashicorp/template...
- Installing hashicorp/aws v3.73.0...
- Installed hashicorp/aws v3.73.0 (signed by HashiCorp)
- Installing hashicorp/random v3.1.0...
- Installed hashicorp/random v3.1.0 (signed by HashiCorp)
- Installing kvcpr/template v2.2.0-arm...
- Installed kvcpr/template v2.2.0-arm (self-signed, key ID EF5C9E0F7A5758E1)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have
│ different platforms supported.
╵
```

### Steps to Reproduce

1. `terraform init` on arm

### Important Factoids

Using m1 processor

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @kvcpr 👋 Thank you for taking the time to raise this. I wasn't able to determine exactly which module you are using for `ecs_task_definition`, but you'll need to file an issue within that module's repository in order to have this addressed, as this isn't an issue with the AWS Provider itself. I'll leave this issue open for now in case you have any followup questions.

As a note, the [`template` provider](https://registry.terraform.io/providers/hashicorp/template/2.2.0) has been deprecated in favor of using the [`templatefile` function](https://www.terraform.io/language/functions/templatefile) or the [`Cloudinit` provider](https://registry.terraform.io/providers/hashicorp/cloudinit/2.2.0), so the module will need to be updated with that in mind.

**Comment by tibbon** [comment]
I've encountered this too today. I might try to put together a PR on Monday to fix this, as it's currently blocking me. 

I see some usage of it here, but that's an example, which doesn't really make sense to me https://github.com/hashicorp/terraform-provider-aws/blob/ac06ced75cba0daf09fef2938752ad13cc6fff6e/examples/ecs-alb/main.tf#L56
