### ISSUE TITLE
aws_acm_certificate_validation documentation code example specifies domain_name value in subject_alternative_names

### ISSUE THREAD

**Issue by ScottG489** [hashicorp/terraform-provider-aws#22734]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

Documentation for [`aws_acm_certificate_validation`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate_validation) and possibly the documentation for [`acm_certificate`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate) and a bug with the resource itself.

### Issue
There is a [code example in the documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate_validation#alternative-domains-dns-validation-with-route-53) for `aws_acm_certificate_validation` which uses the same value for `domain_name` as a value in the `subject_alternative_names` list as seen here:
```HCL
resource "aws_acm_certificate" "example" {
  domain_name               = "example.com"
  subject_alternative_names = ["www.example.com", "example.org"]
  validation_method         = "DNS"
}
...
```
I don't believe the domain name should be specified here as it's a list for "alternative" names to the domain itself.

Particularly, specifying the domain name here causes the `acm_certificate` resource to recreate itself. It's possible that this is because the domain can't be stored in AWS as an alternative, so when the resource refreshes, terraform doesn't see it there and thinks it needs to add it.

**This may also indicate that this is actually a bug with the resource itself**, where it either should throw an error if the user tries to specify the domain as an alternative or perhaps terraform should ignore the existence of the domain name appearing in the `subject_alternative_names` list when accounting for state. If this is the case then a separate issue can be created for that.

**Comment by mattburgess** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/19790 covers that recreation problem you mention. The example you link to looks OK to me though; `www.example.com` and `example.com` are different. Given that provided config I'd expect that the cert will end up with 1 domain name (obviously) and 3 SANs: `example.com` (added by AWS automatically), `www.example.com`, and `example.org`.

**Comment by ScottG489** [comment]
Good catch, I missed the `org` rather than the `com` in the SAN.

That issue you linked seems to summarize what I was trying to get at. It also mentions that there should be something in the documentation about this. There's nothing in the `acm_certificate` `subject_alternative_names` documentation specifying the domain name shouldn't also exist in the SAN list.

Happy to close this issue in favor of #19790 if we'd like?

**Comment by justinretzolk** [comment]
(commenting in the interest of not closing without saying something) Given the above conversation, closing in favor of #19790.
