### ISSUE TITLE
DynamoDB_Table_Item implies a DynamoDB_Table exported attribute that doesn't exist (hash_key)

### ISSUE THREAD

**Issue by Zak-Alford** [hashicorp/terraform-provider-aws#22742]
On [the DynamoDB_Table_Item page](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table_item), the example code implies you can use `hash_key   = aws_dynamodb_table.example.hash_key`, but `aws_dynamodb_table` has no hash_key terraform attribute per the [DynamoDB_Table page](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#attributes-reference)

**Comment by Zak-Alford** [comment]
It also implies that you can do `table_name = aws_dynamodb_table.example.name` when really it should be `table_name = aws_dynamodb_table.example.id`

**Comment by justinretzolk** [comment]
Hey @Zak-Alford 👋 Thank you for taking the time to raise this. While `hash_key` and `name` are not _attributes_ of the `aws_dynamodb_table` resource, they are _arguments_ of the resource, which may also be referenced by other resources via interpolation. Based on this, the documentation looks to be correct from my read, but I am always open to additional input if you feel I've missed any key factors.
