### ISSUE TITLE
Elasticache Global Datastore (aws_elasticache_global_replication_group) modify shards (resharding)

### ISSUE THREAD

**Issue by bnckobe** [hashicorp/terraform-provider-aws#22752]
I am trying to do is using global datastore for cross region replication. I have created Redis primary and secondary cluster in 2 regions with multi shards ([elasticache_replication_group with cluster mode](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#cluster_mode)). They are control by global datastore. I need to scale up/down (resharding) when needed. Problem is shard is control by global datastore after created. I am not able to make the change on either primary or secondary. And for now [aws_elasticache_global_replication_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_global_replication_group#argument-reference) is not providing any argument to do so.  

Could anybody tell me is it anyway I can achieve that currently please? Or  aws_elasticache_global_replication_group need to be enhanced to handle that? Appreciate it!

**Comment by justinretzolk** [comment]
Hey @bnckobe 👋 Thank you for taking the time to raise this! It looks like this may be more of a question than a bug report. If I'm correct in that interpretation, you may have better luck asking in the [AWS Provider Discuss Forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33). If I'm incorrect in that assumption, and you feel this may be a bug, can you update the issue description to include the information requested in the [bug template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?

**Comment by bnckobe** [comment]
Thanks a lot @justinretzolk for your reply. TBH I don't think this is question or bug but feature request or enhancement. Any way I did what you asked for. I created post from the forum also filled up the bug report form. Let me know if I missed anything please. Thanks again for your help.
