### ISSUE TITLE
Update documentation on aws_s3_bucket_policy page

### ISSUE THREAD

**Issue by nijdarshan** [hashicorp/terraform-provider-aws#22772]
The import command at the end of the [aws_s3_bucket_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_policy) documentation says 

```hcl
$ terraform import aws_s3_bucket_policy.example my-bucket-name
```

But, since the name of the `aws_s3_bucket_policy` is `allow_access_from_another_account`, the command should be as follows:

```hcl
$ terraform import aws_s3_bucket_policy.allow_access_from_another_account my-bucket-name
```

**Comment by justinretzolk** [comment]
Hey @nijdarshan 👋 Thank you for taking the time to raise this! There doesn't seem to be much consistency in how we document the imports of resources -- some examples use the resource identifier from the examples, while some don't. That said, I think that in this case, the change makes sense, and so have opened a documentation pull request to change this.
