### ISSUE TITLE
Cannot remove `aws_ec2_client_vpn_endpoint` an entry to `dns_servers`

### ISSUE THREAD

**Issue by nitrocode** [hashicorp/terraform-provider-aws#22778]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `aws_ec2_client_vpn_endpoint`

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
  ~ resource "aws_ec2_client_vpn_endpoint" "default" {
      ~ dns_servers            = [
          - "10.88.0.2",
        ]
    }
```

### Panic Output

N/A

### Expected Behavior

The update should have removed the dns server

### Actual Behavior

```hcl
module.ec2_client_vpn.aws_ec2_client_vpn_endpoint.default[0]: Modifying... [id=cvpn-endpoint-snip]
╷
│ Error: Error modifying Client VPN endpoint: InvalidParameterValue: DNS servers config is conflicting
│ 	status code: 400, request id: 96cc6efb-20b3-4287-9d9f-ab6a21c70949
│
│   with module.ec2_client_vpn.aws_ec2_client_vpn_endpoint.default[0],
│   on .terraform-mdev/modules/ec2_client_vpn/main.tf line 143, in resource "aws_ec2_client_vpn_endpoint" "default":
│  143: resource "aws_ec2_client_vpn_endpoint" "default" {
│
╵
Releasing state lock. This may take a few moments...
exit status 1
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

N/A

**Comment by ewbankkit** [comment]
@nitrocode Thanks for raising this issue.
I have been able to reproduce this when removing all DNS servers from a client VPN endpoint and we are working on a fix.
