### ISSUE TITLE
Updating aws_cloudfront_public_key encoded_key with the same value forces replacement 

### ISSUE THREAD

**Issue by RishiR2** [hashicorp/terraform-provider-aws#22777]
### Expected Behavior

storing the encoded key in Azuredevops Secure file and referencing to the module. since there is no change in the file it should consider no change in key group

### Actual Behavior

but it doing force replacement in every run and it keep failing its try to destroy the key.
  # module.cloudfront-keygroup.aws_cloudfront_public_key.key must be replaced
-/+ resource "aws_cloudfront_public_key" "key" {
      ~ caller_reference = "terraform-20211208065423134700000001" -> (known after apply)
      ~ encoded_key      = <<-EOT # forces replacement
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxMRzpdJx0YwCB59fRoG6

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. Main.tf 
  resource "aws_cloudfront_public_key" "key" {
  name        = "my-cf-pubkey"
  encoded_key =  var.encoded_key
}

2. .tfvars
encoded_key          = "my-publickey.pem"

3. version -  hashicorp/aws v3.53.0 and TF version 1.0.2

**Comment by kwv** [comment]
Almost wonder if it's the lack of a `name_prefix` causing the subsequent key to be recreated as "unique" 

https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/cloudfront/public_key.go#L66

**Comment by justinretzolk** [comment]
Hey @RishiR2 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description with the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?

**Comment by victoruyy** [comment]
Hi, there was any solution to this? To me is happening the same, after the first execution of the code the aws_cloudfront_public_key resources prompts me to be replaced every apply, and gets stucked at the moment of destroying, because of the dependancy with the keygroup

│ Error: PublicKeyInUse: The Cloudfront public key is currently associated with either Key Group or a field level encryption profile. Please disassociate the key before deleting.
│       status code: 409, request id: a67ff22f-fc28-47ef-9617-2bc345841b0e
│

any ideas to avoid this recreation??

**Comment by mogadanez** [comment]
same for me.
```
data "aws_ssm_parameter" "public_key_pem" {
  name = "cf_keypair_public"
}

resource "aws_cloudfront_public_key" "cf_key" {
	encoded_key = data.aws_ssm_parameter.public_key_pem.value
}

# note the random name
resource "aws_cloudfront_key_group" "cf_keygroup" {
	items = [aws_cloudfront_public_key.cf_key.id]
	name  = "cf_keygroup"
}

```

this cause  on each run  replacement 


```
  # module.cloudfront.aws_cloudfront_key_group.cf_keygroup will be updated in-place
  ~ resource "aws_cloudfront_key_group" "cf_keygroup" {
        id    = "1fc5f010-dddd-4323-dddd-6adddd2bcfb"
      ~ items = [
          - "KRXXXXXXXXAAW",
        ] -> (known after apply)
        name  = "cf_keygroup"
        # (1 unchanged attribute hidden)
    }

  # module.cloudfront.aws_cloudfront_public_key.cf_key must be replaced
-/+ resource "aws_cloudfront_public_key" "cf_key" {
      ~ caller_reference = "terraform-20231017141146946400000002" -> (known after apply)
      - comment          = "" -> null
      ~ encoded_key      = (sensitive) # forces replacement
      ~ etag             = "E5A885S6HGD8O" -> (known after apply)
      ~ id               = "KRXXXXXXXXAAW" -> (known after apply)
      ~ name             = "tf-20231017141146946300000001" -> (known after apply)
      + name_prefix      = (known after apply)


```

**Comment by flightlesstux** [comment]
Hi, I found the solution to this problem! Here is the explanation: this is not a terraform behavior; it's all about AWS! When terraform applies again, the AWS is always accepts the key in EOT format. Here is my output below:

```
  # module.cloudfront.aws_cloudfront_public_key.this[0] must be replaced
-/+ resource "aws_cloudfront_public_key" "this" {
      ~ caller_reference = "terraform-20240118203726052400000001" -> (known after apply)
      ~ comment          = "CloudFront public key" -> "CloudFront public key by Terraform"
      ~ encoded_key      = <<-EOT # forces replacement
            -----BEGIN PUBLIC KEY-----
          - MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzV0iKGfIAgh3TYCphzs8
          - o8hltBehpqszB6FVBP46+ShAdYyk99zXb0hMwj+P9gGRUjghvXMXhaj8kDm7eYe2
          - gnUqDUSpCMItE5Y7Qi5VM9jG2F4W0SVDw4XqPR4PoEN2jzyubntK2ZLzCQpZhGFd
          - 8ZbuG2KHEuKkpIuvRg01Ulw51/ox286l4aLqyGBozPgu24urriJhxVaCgv8eNSAA
          - Bily+AUU6U8BaP0rq2AThNLwahKcJKkPrGDyBof4uWGKKp2tzXPuAYtku+nf4Xjk
          - DXrdnS/zYvaihQzbeWm2/5jLGfezBe4Dx/6uQ7hoP0UdlHXOHZ790/rY3sqGtUYZ
          - owIDAQAB
          + MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzV0iKGfIAgh3TYCphzs8o8hltBehpqszB6FVBP46+ShAdYyk99zXb0hMwj+P9gGRUjghvXMXhaj8kDm7eYe2gnUqDUSpCMItE5Y7Qi5VM9jG2F4W0SVDw4XqPR4PoEN2jzyubntK2ZLzCQpZhGFd8ZbuG2KHEuKkpIuvRg01Ulw51/ox286l4aLqyGBozPgu24urriJhxVaCgv8eNSAABily+AUU6U8BaP0rq2AThNLwahKcJKkPrGDyBof4uWGKKp2tzXPuAYtku+nf4XjkDXrdnS/zYvaihQzbeWm2/5jLGfezBe4Dx/6uQ7hoP0UdlHXOHZ790/rY3sqGtUYZowIDAQAB
            -----END PUBLIC KEY-----
        EOT
      ~ etag             = "E1BQZRBB4L9FUS" -> (known after apply)
      ~ id               = "K3CNOYX08R3CXZ" -> (known after apply)
        name             = "Test-public-key-0"
      + name_prefix      = (known after apply)
    }
```

# What I did?

First of all, I used:

```
variable "backend_cf_public_key" {
  type = string
  default = "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzV0iKGfIAgh3TYCphzs8o8hltBehpqszB6FVBP46+ShAdYyk99zXb0hMwj+P9gGRUjghvXMXhaj8kDm7eYe2gnUqDUSpCMItE5Y7Qi5VM9jG2F4W0SVDw4XqPR4PoEN2jzyubntK2ZLzCQpZhGFd8ZbuG2KHEuKkpIuvRg01Ulw51/ox286l4aLqyGBozPgu24urriJhxVaCgv8eNSAABily+AUU6U8BaP0rq2AThNLwahKcJKkPrGDyBof4uWGKKp2tzXPuAYtku+nf4XjkDXrdnS/zYvaihQzbeWm2/5jLGfezBe4Dx/6uQ7hoP0UdlHXOHZ790/rY3sqGtUYZowIDAQAB\n-----END PUBLIC KEY-----"
}
```

I just replaced my single line key to *multi-line strings* and it worked!

```
variable "backend_cf_public_key" {
  type    = string
  default = <<-EOT
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzV0iKGfIAgh3TYCphzs8
    o8hltBehpqszB6FVBP46+ShAdYyk99zXb0hMwj+P9gGRUjghvXMXhaj8kDm7eYe2
    gnUqDUSpCMItE5Y7Qi5VM9jG2F4W0SVDw4XqPR4PoEN2jzyubntK2ZLzCQpZhGFd
    8ZbuG2KHEuKkpIuvRg01Ulw51/ox286l4aLqyGBozPgu24urriJhxVaCgv8eNSAA
    Bily+AUU6U8BaP0rq2AThNLwahKcJKkPrGDyBof4uWGKKp2tzXPuAYtku+nf4Xjk
    DXrdnS/zYvaihQzbeWm2/5jLGfezBe4Dx/6uQ7hoP0UdlHXOHZ790/rY3sqGtUYZ
    owIDAQAB
    -----END PUBLIC KEY-----
  EOT
}
```

Also, you can use with the "line break" below:

```
variable "backend_cf_public_key" {
  type    = string
  default = "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzV0iKGfIAgh3TYCphzs8\no8hltBehpqszB6FVBP46+ShAdYyk99zXb0hMwj+P9gGRUjghvXMXhaj8kDm7eYe2\ngnUqDUSpCMItE5Y7Qi5VM9jG2F4W0SVDw4XqPR4PoEN2jzyubntK2ZLzCQpZhGFd\n8ZbuG2KHEuKkpIuvRg01Ulw51/ox286l4aLqyGBozPgu24urriJhxVaCgv8eNSAA\nBily+AUU6U8BaP0rq2AThNLwahKcJKkPrGDyBof4uWGKKp2tzXPuAYtku+nf4Xjk\nDXrdnS/zYvaihQzbeWm2/5jLGfezBe4Dx/6uQ7hoP0UdlHXOHZ790/rY3sqGtUYZ\nowIDAQAB\n-----END PUBLIC KEY-----\n"
}
```

Voila! 🥳

**Comment by justinretzolk** [comment]
With the above in mind, closing. Thanks for the great info @flightlesstux!
