### ISSUE TITLE
RStudio support for SageMaker Domain

### ISSUE THREAD

**Issue by dsturnbull** [hashicorp/terraform-provider-aws#22789]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Support for specifying RStudio domain settings when creating via the aws_sagemaker_domain resource.

https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateDomain.html

https://docs.aws.amazon.com/sdk-for-go/api/service/sagemaker/#DomainSettings

In the potential config below,

Specifying "rstudio_server_settings" enables the feature, assuming a licence is found.

default_user_settings's rstudio_settings configures the default user interaction with RStudio Pro server.

### New or Affected Resource(s)

* aws_sagemaker_domain

### Potential Terraform Configuration

```hcl
resource "aws_sagemaker_domain" "domain" {
  domain_name = "domain"
  auth_mode   = "IAM"
  vpc_id      = aws_vpc.vpc.id
  subnet_ids  = aws_subnet.public_subnets.*.id

  rstudio_server_settings = {
    domain_execution_role_arn = "..."
  }

  default_user_settings {
    execution_role = aws_iam_role.default_execution_role.arn
    rstudio_settings = {
      access_status  = "ENABLED"
      user_group     =  R_STUDIO_USER"
    }
  }
}
```

**Comment by KTamas** [comment]
This is something we're really missing as well.
