### ISSUE TITLE
Unable to update s3 bucket tags

### ISSUE THREAD

**Issue by reddyskp** [hashicorp/terraform-provider-aws#22782]
terraform version - 1.0.6
AWS provider - 3.73.0

I am using generic s3 bucket with kms encryption terraform code  and I am getting KMS key from data source. and importing that module and applying terraform. I am trying to update s3 tags for existing bucket.  terraform apply was showing successful but tags are not getting updated. below is the DEBUG log.

Provider "provider[\"registry.terraform.io/hashicorp/aws\"].sz_no_default_tags" produced an unexpected new value for module.config_s3_bucket.aws_s3_bucket.this, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .tags: element "Build Pipeline" has vanished
      - .tags: element "Build Version" has vanished
      - .tags: element "Business Unit" has vanished
      - .tags: element "Compliance" has vanished
      - .tags: element "Cost Centre" has vanished
      - .tags: element "Creator" has vanished
      - .tags: element "Data Classification" has vanished
      - .tags: element "Data Residency" has vanished
      - .tags: element "Service Level" has vanished
      - .tags: element "Work Order" has vanished
2022-01-26T21:51:20.500Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"

**Comment by justinretzolk** [comment]
Hey @lonecoder433 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to investigate this, can you update the issue description with the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?
