### ISSUE TITLE
S3 backend in ap-southeast-3 isn't supported.

### ISSUE THREAD

**Issue by alexleyn** [hashicorp/terraform-provider-aws#22791]
I try to init S3 backend in Jakarta region (ap-southeast-3) and get error
```terraform init
Initializing modules...

Initializing the backend...
╷
│ Error: Invalid AWS Region: ap-southeast-3
│
│
╵
```

Terraform version: 1.1.4
AWS provider version: 3.73.0

I tried to compile aws-provider with bumped aws-sdk-go version to 1.42.42 and nothing changed.

Resource _aws_s3_bucket_ works correctly. I can manage buckets in ap-southeast-3 region.

**How to reproduce.**
Just add backend configuration like this:
```
  backend "s3" {
    bucket = "my-terraform"
    key    = "jakarta/terraform.tfstate"
    region = "ap-southeast-3"
    dynamodb_table = "my-terraform"
  }
```

**Comment by dimazyuwono** [comment]
hi @alexleyn , have you tried to adjust the `backend "s3"` block by adding `skip_region_validation = true ` ?

I've also working with `ap-southeast-3` region and it seems we need to add additional configuration since the region is fairly new.

```
terraform {
  backend "s3" {
    bucket                 = "s3-bucket-jakarta-region"
    dynamodb_table         = "dynamodb-jakarta-region"
    key                    = "key-path/terraform.tfstate"
    region                 = "ap-southeast-3"
    skip_region_validation = true
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.74.0"
    }
  }
}

provider "aws" {
  region                 = "ap-southeast-3"
}
```

**Comment by alexleyn** [comment]
Yes. I've tried. I got error
`Error: error configuring S3 Backend: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.` I checked credential via aws-cli `aws s3 ls --profile jakarta` and everything was okay.

**Comment by justinretzolk** [comment]
Hey @alexleyn 👋 Terraform `v1.1.5` was just realized with [support for the ap-southeast-3 region for the S3 backend](https://github.com/hashicorp/terraform/blob/v1.1/CHANGELOG.md#115-february-02-2022). Can you update to this latest version and test to see if that resolves your issue?
