### ISSUE TITLE
Documentation describes mandatory field set_identifier as optional for multivalue_answer_routing_policy

### ISSUE THREAD

**Issue by realflash** [hashicorp/terraform-provider-aws#22822]
On the [Terraform website](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_record) set_identifier is documented thusly:

> set_identifier - (Optional) Unique identifier to differentiate records with routing policies from one another. Required if using `failover`, `geolocation`, `latency`, or `weighted` routing policies documented below.

The implication being that the one routing policy for which this is not needed is `multivalue_answer_routing_policy`. If you don't set this field when using that policy, record creation fails with the error:

```
Error: provider.aws: aws_route53_record: something.com: "set_identifier": required field is not set when "multivalue_answer_routing_policy" is set
```

So it presumably isn't optional (any more?). If I set this field the record is created as expected. [AWS documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html) for `SetIdentifier` says:

> Resource record sets that have a routing policy other than simple

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

N/A

### Affected Resource(s)

aws_route53_record

### Terraform Configuration Files

```
resource "aws_route53_record" "some_record" {
  zone_id = <some_zone_id>
  name    = "something.com"
  type    = "A"
  ttl     = "5"
  records = ["1.1.1.1"]
  multivalue_answer_routing_policy = true
  health_check_id = aws_route53_health_check.some_hc.id
}
```

### Debug Output

N/A

### Expected Behavior

Document told me to do the right thing

### Actual Behavior

Document told me to do the wrong thing

**Comment by justinretzolk** [comment]
Hey @realflash 👋 Thank you for taking the time to open this! I've opened a pull request to correct the documentation to include `multivalue_answer_routing_policy` in the list within the `set_identifier` documentation, as `set_identifier` is indeed required for all but `simple` routing policies.
