### ISSUE TITLE
Deprecate support for `AWS_METADATA_URL` in favour of official `AWS_EC2_METADATA_SERVICE_ENDPOINT`

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#22825]
Historically, [`aws-sdk-go-base`](https://github.com/hashicorp/aws-sdk-go-base) supported the non-standard environment variable `AWS_METADATA_URL` to override the EC2 Metadata Service endpoint. The AWS SDK for Go v2 has supported the official environment variable `AWS_EC2_METADATA_SERVICE_ENDPOINT` from the start, and the AWS SDK for Go v1 added support in v1.40.0.

Update provider documentation to indicate the deprecation of the old environment variable and usage of the new one.

Functional deprecationwill be handled by https://github.com/hashicorp/aws-sdk-go-base/issues/89

**Comment by YakDriver** [comment]
I picked up `ec2_metadata_service_endpoint` and `...mode` in #22804
