### ISSUE TITLE
Add provider parameter `ec2_metadata_service_endpoint`

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#22826]
Add a provider configuration parameter `ec2_metadata_service_endpoint` to allow specifying the EC2 Metadata Service endpoint in Terraform.

Document the parameter as well as the ability to set the value in the AWS shared configuration file.

Environment variable documentation is updated in #22825

Depends on https://github.com/hashicorp/aws-sdk-go-base/issues/90

**Comment by anGie44** [comment]
param support added in https://github.com/hashicorp/terraform-provider-aws/pull/22804

**Comment by YakDriver** [comment]
Closed by #22804
