### ISSUE TITLE
Fail fast when aws_api_gateway_stage cache_cluster_enabled is false but cache_cluster_size is set and greater than zero.

### ISSUE THREAD

**Issue by bpar476** [hashicorp/terraform-provider-aws#22841]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating an API Gateway Stage, the provider will wait for the `cacheClusterStatus` to be `AVAILABLE` if either `cache_cluster_enabled` or `cache_cluster_size` are set. However, if `cache_cluster_size` is set but `cache_cluster_enabled` is false then the stage will never create successfully because the cache cluster will never be in the `AVAILABLE` state. I propose that a validation be added before attempting resource creation that if `cache_cluster_size` is set and `cache_cluster_enabled` is false then the plan should fail because these parameter values are incompatible.

### Affected Resources

`aws_api_gateway_stage`

**Comment by bpar476** [comment]
I'd be happy to contribute the change to this with a bit of guidance on how this might be implemented. I haven't contributed here before.

**Comment by danquack** [comment]
@bpar476 have you looked at https://www.terraform.io/plugin/sdkv2/resources/customizing-differences before?

**Comment by bpar476** [comment]
Thanks for the pointer @danquack I've raised https://github.com/hashicorp/terraform-provider-aws/pull/22861

**Comment by bpar476** [comment]
Closing this issue as the same problem will be resolved by https://github.com/hashicorp/terraform-provider-aws/issues/22866
