### ISSUE TITLE
AWS Shield Advanced Enablement - DRT Role 

### ISSUE THREAD

**Issue by dawsonpaul** [hashicorp/terraform-provider-aws#22848]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### AWS Terraform Provider doesn’t yet have the function to associate the created shield DRT role with Advanced Shield.

This was raised [here](https://github.com/hashicorp/terraform-provider-aws/issues/10319) some time ago but remains outstanding. It is not possible to complete the Advanced Shield setup without doing this manually in the console 

1. 'Configure AWS SRT Support' :

![image](https://user-images.githubusercontent.com/16097474/151787266-3e5046ab-2e59-4c00-a165-c71f553103ba.png)

2. Manually configure final step (missing from the provider):

![image](https://user-images.githubusercontent.com/16097474/151788763-69a6f10d-121d-40b4-9556-943b642747ac.png)

or with:

```
aws shield associate-drt-role --role-arn arn:aws:iam::XXXXXXXXXXXX:role/shield-drt-role
```

The $3000 pcm cost of enabling the Shield Advanced service may be prohibitive to its development. As we have Advanced Shield requirement for hundreds of sub-accounts and need this functionality within the organisation, I am happy to work with anyone in developing and testing the provider. 

### New or Affected Resource(s)

* aws_shield_drt_role_association
### Potential Terraform Configuration

```hcl
resource "aws_shield_drt_role_association" "shield_drt" {
  role_arn = "${aws_iam_role.shield_drt.arn}"
}
```

### References

*https://github.com/hashicorp/terraform-provider-aws/issues/10319

**Comment by wfgamal** [comment]
i have the same issue, trying to attach the role with terraform but can't.

**Comment by moopsha** [comment]
Is there any update on this issue?
I'm trying to automate shield advanced setup using terraform, but there is no proper documentation available.

**Comment by UrfTheManatee** [comment]
Is there any update on this?

**Comment by ewbankkit** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/33328.
