### ISSUE TITLE
Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by ColinHillIRESS** [hashicorp/terraform-provider-aws#22851]
Error: Provider produced inconsistent final plan

When expanding the plan for module.cloud-front.aws_cloudfront_distribution.cf to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .origin: planned set element cty.ObjectVal(map[string]cty.Value{"connection_attempts":cty.NumberIntVal(3), "connection_timeout":cty.NumberIntVal(10), "custom_header":cty.SetValEmpty(cty.Object(map[string]cty.Type{"name":cty.String, "value":cty.String})), "custom_origin_config":cty.ListValEmpty(cty.Object(map[string]cty.Type{"http_port":cty.Number, "https_port":cty.Number, "origin_keepalive_timeout":cty.Number, "origin_protocol_policy":cty.String, "origin_read_timeout":cty.Number, "origin_ssl_protocols":cty.Set(cty.String)})), "domain_name":cty.StringVal("ui.hostplusorigination.technet-dev-uk.iress.online.s3.eu-west-2.amazonaws.com"), "origin_id":cty.StringVal("hostplusoriginationServ.ui.technet.origin"), "origin_path":cty.NullVal(cty.String), "origin_shield":cty.ListValEmpty(cty.Object(map[string]cty.Type{"enabled":cty.Bool, "origin_shield_region":cty.String})), "s3_origin_config":cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"origin_access_identity":cty.StringVal("origin-access-identity/cloudfront/E3NMCN6WBAX11E")})})}) does not correlate with any element in actual.
  | │
  | │ This is a bug in the provider, which should be reported in the provider's own issue tracker.
  | ╵
  | ╷
  | │ Error: Error creating API Gateway Stage: ConflictException: Stage already exists
  | │
  | │   with module.api_gateway_bff.aws_api_gateway_stage.api_stage,
  | │   on modules/api-gateway/main.tf line 49, in resource "aws_api_gateway_stage" "api_stage":
  | │   49: resource "aws_api_gateway_stage" "api_stage" {
  | │
  | ╵

**Comment by ColinHillIRESS** [comment]
**Version information**

- Terraform 1.0.4
- Installed hashicorp/aws v3.74.0

**Comment by ColinHillIRESS** [comment]
**### Error when trying to delete Pipeline**

Stack trace from the terraform-provider-aws_v3.74.0_x5 plugin:
  |  
  | panic: interface conversion: interface {} is nil, not *conns.AWSClient
  |  
  | goroutine 43 [running]:
  | github.com/hashicorp/terraform-provider-aws/internal/service/apigateway.resourceDeploymentRead(0xc0024ffd00, 0x0, 0x0, 0xf0f1910, 0xc000074400)
  | /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/apigateway/deployment.go:104 +0xe05
  | github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0001f5dc0, 0xa507158, 0xc00261e340, 0xc0024ffd00, 0x0, 0x0, 0x0, 0x0, 0x0)
  | /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:346 +0x1ee
  | github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0001f5dc0, 0xa507158, 0xc00261e340, 0xc00261c410, 0x0, 0x0, 0xc002185c88, 0x0, 0x0, 0x0)
  | /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x1cb
  | github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c0d8, 0xa507158, 0xc00261e340, 0xc00261e380, 0x95a66e1, 0x12, 0x0)
  | /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x47d
  | github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00107e180, 0xa507200, 0xc00261e340, 0xc0024d18c0, 0x0, 0x0, 0x0)
  | /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x322
  | github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x930e3e0, 0xc00107e180, 0xa507200, 0xc002610cc0, 0xc0024d1860, 0x0, 0xa507200, 0xc002610cc0, 0xc001e83380, 0x194)
  | /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
  | google.golang.org/grpc.(*Server).processUnaryRPC(0xc0010fa700, 0xa533c18, 0xc00162f680, 0xc001df1800, 0xc0019309c0, 0xf0b1bf0, 0x0, 0x0, 0x0)
  | /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
  | google.golang.org/grpc.(*Server).handleStream(0xc0010fa700, 0xa533c18, 0xc00162f680, 0xc001df1800, 0x0)
  | /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
  | google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc001c34b40, 0xc0010fa700, 0xa533c18, 0xc00162f680, 0xc001df1800)
  | /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
  | created by google.golang.org/grpc.(*Server).serveStreams.func1
  | /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
  |  
  | Error: The terraform-provider-aws_v3.74.0_x5 plugin crashed!
  |  
  | This is always indicative of a bug within the plugin. It would be immensely
  | helpful if you could report the crash with the plugin's maintainers so that it
  | can be fixed. The output above should help diagnose the issue.

**Comment by justinretzolk** [comment]
Hey @ColinHillIRESS 👋 Thank you for taking the time to raise this! So that we have all of the information necessary in order to investigate this, can you update the issue description with the information requested in the [bug template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?
