### ISSUE TITLE
Changes to DB parameter group apply_method only takes effect if DB parameter value changes

### ISSUE THREAD

**Issue by shanem-canva** [hashicorp/terraform-provider-aws#22857]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform: v0.14.11
AWS Provider: v3.72.0

### Affected Resource(s)

* aws_db_parameter_group

### Terraform Configuration Files

```hcl

locals {
  dynamic_parameters = ["collation_server", ...]
 }

resource "aws_db_parameter_group" "this" {
  count = var.enabled ? 1 : 0
  name = "test-group"
  family = var.mysql_family

  dynamic "parameter" {
    for_each = [
      "collation_server",
      ...
    ]
    content {
      name = parameter.value
      value = "utf8mb4_unicode_ci"
      apply_method = contains(local.dynamic_parameters, parameter.value) ? "immediate" : "pending-reboot"
    }
  }
```

### Expected Behavior

Whenever a `terraform plan` is run it should flag that there are no changes to the DB parameter group.

### Actual Behavior

When running `terraform plan` it shows the following will change:
```
Terraform will perform the following actions:

  # module.rds_parameter_group.aws_db_parameter_group.this[0] will be updated in-place
  ~ resource "aws_db_parameter_group" "this" {
        id          = "test-group"
        name        = "test-group"
        tags        = {}

      + parameter {
          + apply_method = "immediate"
          + name         = "collation_server"
          + value        = "utf8mb4_unicode_ci"
        }
      - parameter {
          - apply_method = "pending-reboot" -> null
          - name         = "collation_server" -> null
          - value        = "utf8mb4_unicode_ci" -> null
        }
        # (1 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. Create the parameter group and ensure that `value` = "utf8mb4_unicode_ci", `apply_method` = "pending-reboot" for parameter "collation_server". This can be done via terraform or using the AWS CLI.

2. Run `terraform plan` with the above HCL and note that output should match the output above.

3. Run `terraform apply` and note that the changes appear to have been made with output similar to:
```
module.rds_parameter_group.aws_db_parameter_group.this[0]: Modifying... [id=test-group]
module.rds_parameter_group.aws_db_parameter_group.this[0]: Modifications complete after 1s [id=test-group]
```

4. Subsequently running `terraform plan` flag that the "collation_server" parameter will be updated as was previously reported.

5. Querying the group using the AWS CLI will result in:
```
aws rds describe-db-parameters --db-parameter-group-name test-group
{
    "ParameterName": "collation_server",
    "ParameterValue": "utf8mb4_unicode_ci",
    "Source": "user",
    "ApplyType": "dynamic",
    "DataType": "string",
    "AllowedValues": "<removed>",
    "IsModifiable": true,
    "ApplyMethod": "pending-reboot"
},
```

### Important Factoids

Using only the AWS CLI my testing shows that the `apply_method` value will only change if the actual DB parameter value is changing; if only the `apply_method` is changing, and the actual DB parameter isn't, then running the appropriate command will appear to have worked but the value of `apply_method` won't have changed.

1. Create the DB parameter group with parameter "collation_server" = "utf8mb4_unicode_ci" and "apply_method" = "pending-reboot". This can be done either by creating the group, or copying an existing one.

2. Query the DB parameter group:
```
$ aws rds describe-db-parameters --db-parameter-group-name test-group
{
    "ParameterName": "collation_server",
    "ParameterValue": "utf8mb4_unicode_ci",
    "Source": "user",
    "ApplyType": "dynamic",
    "DataType": "string",
    "AllowedValues": "<removed>"
    "IsModifiable": true,
    "ApplyMethod": "pending-reboot"
},
```

3. Modify only "apply_method":
```
$ aws rds modify-db-parameter-group --db-parameter-group-name test-group --parameters "ParameterName='collation_server',ParameterValue='utf8mb4_unicode_ci',ApplyMethod=immediate"
{
    "DBParameterGroupName": "test-group"
}
```
Note that the parameter value needs to be specified for the command to work. However, the `apply_method` was changed from "pending-reboot" to "immediate".

4. Query the DB parameter group:
```
$ aws rds describe-db-parameters --db-parameter-group-name test-group
{
    "ParameterName": "collation_server",
    "ParameterValue": "utf8mb4_unicode_ci",
    "Source": "user",
    "ApplyType": "dynamic",
    "DataType": "string",
    "AllowedValues": "<removed>"
    "IsModifiable": true,
    "ApplyMethod": "pending-reboot"
},
```
Note that the ApplyMethod value hasn't changed and is still "pending-reboot".

5. Modify the DB parameter value and "apply_method":
```
$ aws rds modify-db-parameter-group --db-parameter-group-name test-group --parameters "ParameterName='collation_server',ParameterValue='utf8mb4_general_ci',ApplyMethod=immediate"
{
    "DBParameterGroupName": "test-group"
}
```

Note that the parameter value has changed from "" to "", and the `apply_method` 

6. Query the DB parameter group

```
$ aws rds describe-db-parameters --db-parameter-group-name test-group
{
    "ParameterName": "collation_server",
    "ParameterValue": "utf8mb4_general_ci",
    "Source": "user",
    "ApplyType": "dynamic",
    "DataType": "string",
    "AllowedValues": "<removed>"
    "IsModifiable": true,
    "ApplyMethod": "immediate"
},
```
Note that the ApplyMethod value has changed.

**Comment by stanhu** [comment]
What's worse, I found that if I created a parameter group with no `count` parameter then **later** add a `count` parameter, then the whole parameter group would be deleted. But if you update a single parameter, the parameter group would be updated in-place properly.

**Comment by sgavinio** [comment]
Update: the terraform documentation has been updated to acknowledge this issue: https://github.com/hashicorp/terraform-provider-aws/pull/24737 which is apparently an AWS API-specific behavior.

**Comment by justinretzolk** [comment]
In this case, it looks like this is indeed a limitation of the underlying API, and not something that we can solve in the Terraform AWS provider. Since this has been noted in the documentation at this point, and there's no further action that we can take at this time, we're going to close this issue. If there are changes to the API that would allow us to change this behavior, we'd be happy to take another look.
