### ISSUE TITLE
Please add support for setting object ownership during initial S3 bucket creation

### ISSUE THREAD

**Issue by absa-rsuarez** [hashicorp/terraform-provider-aws#22873]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for setting the ObjectOwnership parameter in the CreateBucket API call. Without this, the recommended SCP from AWS will not work: https://docs.aws.amazon.com/AmazonS3/latest/userguide/ensure-object-ownership.html

### New or Affected Resource(s)

* resource aws_s3_bucket

### Potential Terraform Configuration

```hcl
resource "aws_s3_bucket" "example" {
  bucket = "example"
  object_ownership = "BucketOwnerPreferred"
}
```

### References

* #0000

**Comment by mattburgess** [comment]
I raised PR #21994 to do this a while back but it was closed in favour of using the existing `aws_s3_bucket_ownership_controls` resource. At the time, I conceded that preferring a) one way of doing things and b) using separated out resources were understandable, I'd failed to consider that SCP use case so didn't bother pursuing the PR any more.

If the Hashicorp devs are happy for me to do so, I can dust that PR off and get it in a mergeable state, perhaps with some additional docs to state why you'd want to use one method over the other.
