### ISSUE TITLE
Parameter SessionTimeoutHours is missing for AWS Client VPN

### ISSUE THREAD

**Issue by obounaim** [hashicorp/terraform-provider-aws#22899]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Client VPN CreateClientVpnEndpoint API supports SessionTimeoutHours. Customizing the session timeout value will help organizations save some costs when closing unused sessions earlier. The default value is 24h.
This parameter is missing in Terraform resource aws_ec2_client_vpn_endpoint 

### New or Affected Resource(s)

* aws_ec2_client_vpn_endpoint 

### Potential Terraform Configuration

```hcl
resource "aws_ec2_client_vpn_endpoint" "example" {
  description            = "terraform-clientvpn-example"
  server_certificate_arn = aws_acm_certificate.cert.arn
  client_cidr_block      = "10.0.0.0/16"

  authentication_options {
    type                       = "certificate-authentication"
    root_certificate_chain_arn = aws_acm_certificate.root_cert.arn
  }

  session_timeout_hours = 8
}
```

### References

* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateClientVpnEndpoint.html
* https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/cvpn-working-max-duration.html

**Comment by ewbankkit** [comment]
@obounaim Thanks for raising this issue.
It has already been noticed in #22720. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
