### ISSUE TITLE
r/aws_autoscaling_attachment: Remove deprecated parameter `alb_target_group_arn`

### ISSUE THREAD

**Issue by anGie44** [hashicorp/terraform-provider-aws#22904]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `alb_target_group_arn` was deprecated in v4.0 (https://github.com/hashicorp/terraform-provider-aws/pull/22662) to help users migrate to the new argument `lb_target_group_arn`. `alb_target_group_arn` should therefore be removed in the next major version.

**Comment by Sinjo** [comment]
Hey, I just went through the process of moving to the non-deprecated attribute today, and found it was relatively involved.

If you just update the attribute name, Terraform wants to destroy/recreate the resource. I ended up having to edit our Terraform state files by hand to avoid temporarily removing the target group attachments.

I was wondering if you'd consider adding a [state migration](https://www.terraform.io/plugin/sdkv2/resources/state-migration) for this attribute change to ease the transition for people who are already using this resource.

**Comment by mmcguinn** [comment]
Ran into the same issue as @Sinjo above while fixing some noticed deprecations. In a large environment with many load balancers across many deployments manually fixing state in this way is not practical (and could be very error-prone). 

A state migration would definitely be preferred, but currently `aws_autoscaling_attachment` lacks even any state import instructions in the docs to address the issue within terraform at least instead of manually editing state files.

**Comment by gazelliz** [comment]
> Hey, I just went through the process of moving to the non-deprecated attribute today, and found it was relatively involved.
> 
> If you just update the attribute name, Terraform wants to destroy/recreate the resource. **I ended up having to edit our Terraform state files by hand to avoid temporarily removing the target group attachments.**
> 
> I was wondering if you'd consider adding a [state migration](https://www.terraform.io/plugin/sdkv2/resources/state-migration) for this attribute change to ease the transition for people who are already using this resource.

@Sinjo did you document the steps you took to make this work? I would appreciate some guidance as I am running into the same issue :(

**Comment by Sinjo** [comment]
@gazelliz I didn't I'm afraid. It was "just" a case of editing the state files to have the correct attribute name, but as @mmcguinn points out that's error-prone and you need to be really careful to get it right.

**Comment by et304383** [comment]
This should be handled more gracefully.  The deprecation tells you to change an argument that triggers replacement.  That's not great.

**Comment by jar-b** [comment]
Closed by #30828, merged to `main` via #31392
