### ISSUE TITLE
data-source/iam_policy_document: Remove `source_json` and `override_json`

### ISSUE THREAD

**Issue by anGie44** [hashicorp/terraform-provider-aws#22906]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`source_json` and `override_json` were deprecated in v4.0 (https://github.com/hashicorp/terraform-provider-aws/pull/22890), thus should be removed in the next major milestone (v5.0)

Removing these arguments will impose a small burden on practitioners in updating their configurations. See below for an example of updating a configuration.

### New or Affected Resource(s)

* data-source/aws_iam_policy_document

#### Pre-deprecation

```hcl
data "aws_iam_policy_document" "source_json_example" {
  source_json = data.aws_iam_policy_document.source.json
}
```

#### Post-deprecation

```hcl
data "aws_iam_policy_document" "source_json_example" {
  source_policy_documents = [data.aws_iam_policy_document.source.json]
}
```

Reference:
* https://github.com/hashicorp/terraform-provider-aws/issues/17555

**Comment by jar-b** [comment]
Closed by #30829, merged to `main` via #31392
