### ISSUE TITLE
Firehose Delivery Stream missing docs on dynamic partitioning

### ISSUE THREAD

**Issue by DrFaust92** [hashicorp/terraform-provider-aws#22934]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Docs are missing `dynamic_partitioning_configuration` argument reference

### New or Affected Resource(s)

* aws_kinesis_firehose_delivery_stream

### Potential Terraform Configuration

None

### References

#20769

**Comment by afrazchelsea** [comment]
I would like to work on this issue.

**Comment by DrFaust92** [comment]
Close via #22779
