### ISSUE TITLE
Enable fine-grained access control in Opensearch 1.1 for existing clusters

### ISSUE THREAD

**Issue by glangho** [hashicorp/terraform-provider-aws#22955]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of Opensearch 1.1, fine-grained access control can be enabled on existing clusters.  Currently, the existing aws_elasticsearch_domain resource will not allow fine-grained access control to be enabled even when the version is set to Opensearch_1.1.  

### New or Affected Resource(s)

* aws_elasticsearch_domain

### References

* https://aws.amazon.com/about-aws/whats-new/2022/01/amazon-opensearch-fine-grained-access-control/
* https://docs.aws.amazon.com/opensearch-service/latest/developerguide/fgac.html
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain#advanced_security_options

**Comment by jimishs** [comment]
Hi, to add some clarification on version support for fine-grained access control on existing domains. It is not only supported for OpenSearch domains, but also certain versions of Elasticsearch domains. See below.

You can enable fine-grained access control on existing domains running OpenSearch or Elasticsearch 6.7 or later.

You can find this information here in the official documentation - https://docs.aws.amazon.com/opensearch-service/latest/developerguide/fgac.html
