### ISSUE TITLE
Service Managed Stackset Instances can't be imported

### ISSUE THREAD

**Issue by pshuman-heb** [hashicorp/terraform-provider-aws#22956]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As far as I can tell from the [documentation here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudformation_stack_set_instance#import), the behavior for `terraform import` for non Self-Managed stackset instances isn't currently defined, even those that feature was added to aws_cloudformation_stack_set_instance in #21193. The current documented import command requires you to pass in a "target account ID" which isn't defined in this case. 

I'm unsure what the correct behavior would be, but it's unhelpful to have a command seemingly be undefined.

### New or Affected Resource(s)

* aws_cloudformation_stack_set_instance

### Potential Terraform Configuration

```hcl
resource "aws_cloudformation_stack_set_instance" "example" {
  deployment_targets {
    organizational_unit_ids = [aws_organizations_organization.example.roots[0].id]
  }

  region         = "us-east-1"
  stack_set_name = aws_cloudformation_stack_set.example.name
}
```

### References

* #21193

**Comment by justinretzolk** [comment]
Hey @pshuman-heb 👋 Thank you for taking the time to raise this! I took a look around and I _believe_ based on [this comment from the resource's read function](https://github.com/hashicorp/terraform-provider-aws/blob/dbb210eaad43012007d7011ed531464bbce1e8c4/internal/service/cloudformation/stack_set_instance.go#L205-L207) that you should be able to import using the ID passed to `deployment_targets.organizational_unit_ids` in the place of where the documentation calls for "target AWS account ID".

**Comment by pshuman-heb** [comment]
@justinretzolk, thanks for that! That's somewhat what I assumed would work, but then:

1. The docs need to be updated to explain that.
2. I'm also a little unsure what I pass in if I've passed in an array of OU IDs? Would it just look like this:
```
terraform import aws_cloudformation_stack_set_instance.example example,[ou-sdas-123987,ou-sdas-9879893,...],us-east-1
```

It's possible all of this is obvious if I'd imported a lot of other resources, but I'm not sure the pattern.

**Comment by justinretzolk** [comment]
Hey @pshuman-heb 👋 I'm revisiting this and working on a documentation update now. For an array of OU IDs, you'd want to pass them in, split by `/` characters. Using the example you provided, this would look something like:

```shell
terraform import aws_cloudformation_stack_set_instance.example example,ou-sdas-123987/ou-sdas-9879893,us-east-1
```
