### ISSUE TITLE
aws_cognito_user_pool_client => token_validity_units An argument named "token_validity_units" is not expected here. 

### ISSUE THREAD

**Issue by noisygerman** [hashicorp/terraform-provider-aws#22961]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

CLI: Latest (alpine/terragrunt:latest image)
Provider: Tried with 3.32, 3.74

### Affected Resource(s)

* aws_cognito_user_pool_client

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_cognito_user_pool" "user_pool" {
  name                = "main-user-pool"
  alias_attributes    = [ "email" ]
  auto_verified_attributes = [ "email" ]

}

resource "aws_cognito_user_pool_domain" "sub_domain" {
  domain       = "auth-api-example-com"
  user_pool_id = aws_cognito_user_pool.user_pool.id
}


resource "aws_cognito_user_pool_client" "client" {
    name            = "UserAuthFlows"
   user_pool_id    = aws_cognito_user_pool.user_pool.id
   generate_secret = false

  allowed_oauth_flows_user_pool_client = true
  
  allowed_oauth_flows = [
    "code",
    "implicit"
  ]
    
  explicit_auth_flows = [
    "ALLOW_USER_SRP_AUTH",
    "ALLOW_CUSTOM_AUTH",
    "ALLOW_REFRESH_TOKEN_AUTH"
  ]

  allowed_oauth_scopes = [
    "phone",
    "email",
    "openid",
    "profile",
    "aws.cognito.signin.user.admin"
  ]

  prevent_user_existence_errors = "ENABLED"

  access_token_validity  = 5
  id_token_validity      = 5
  refresh_token_validity = 10

  token_validity_units = {
    refresh_token = "minutes"
  }

  enable_token_revocation = true
  callback_urls                      = ["http://localhost"]
  logout_urls                         = ["http://localhost"]
}
```

### Expected Behavior

`token_validity_units` should be supported as documented in  https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool_client#token_validity_units

### Actual Behavior

```bash
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 140, in resource "aws_cognito_user_pool_client" "client":
│  140:   token_validity_units = {
│ 
│ An argument named "token_validity_units" is not expected here. Did you mean
│ to define a block of type "token_validity_units"?
╵
```
### Steps to Reproduce

1. `terraform plan`

### Important Factoids

- Running in gitlab runner with alpine/terragrunt:latest image

**Comment by DrFaust92** [comment]
Hi @noisygerman, it should be:

```
  token_validity_units {
    refresh_token = "minutes"
  }
```

without the `=`

**Comment by noisygerman** [comment]
🤦🏼 Thanks - blaming sleep deprivation 😆
