### ISSUE TITLE
tests/cloudformation_stack: Erroring with `The provider hashicorp/aws does not support resource type "aws_s3_website_configuration".`

### ISSUE THREAD

**Issue by anGie44** [hashicorp/terraform-provider-aws#22974]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Tests:

* TestAccCloudFormationStack_WithURL_withParams
* TestAccCloudFormationStack_WithURLWithParams_noUpdate

### Description

* The correct resource is `aws_s3_bucket_website_configuration` 

Relates:

* #22648 
* #22614

**Comment by marboxvel** [comment]
👍
