### ISSUE TITLE
Apple M1 not supported

### ISSUE THREAD

**Issue by chrissewell1234** [hashicorp/terraform-provider-aws#22985]
When running terraform init, I receive the following error:

`
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform,
│ darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other
│ versions of this provider may have different platforms supported.
╵
`

**Comment by justinretzolk** [comment]
Hey @chrissewell1234 👋 As @wedge-jarrad mentioned, the `template` provider has been deprecated in favor of the options listed at the link provided in their comment. This deprecation happened prior to the release of the M1, and so the provider was never released for that platform. With that in mind, we'll close this issue for now. If you feel we've done this in error, please do let me know.
