### ISSUE TITLE
aws_default_route_table does not create all route table entries and leaves route table inconsistent

### ISSUE THREAD

**Issue by kderck** [hashicorp/terraform-provider-aws#22989]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```bash
Terraform v1.1.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v3.74.0
```

### Affected Resource(s)

* aws_default_route_table

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
route_to = ["10.200.33.0/24", "10.200.34.0/24", "10.200.32.0/24"]
```

```hcl
# main.tf
module "add_routes_to_client_vpn" {
  for_each   = toset(var.route_to)
  source     = "./modules//aws_route_table"
  from_vpc   = module.vpn_vpc.vpc_id
  to_vpc     = var.vpc_to_peer_with
  cidr_block = each.key
  peering_id = module.vpn_vpc_peering_requests.peering_id
}
```

```hcl
# /modules//aws_route_table"
resource "aws_default_route_table" "route_table" {
    default_route_table_id          = data.aws_vpc.from_vpc.main_route_table_id
    route {
        cidr_block                  = var.cidr_block
        vpc_peering_connection_id   = var.peering_id
    } 
}


```
### Expected Behavior

Terraform should create **all** entries inside of the main vpc route table.

### Actual Behavior

Terraform timeout on creating multiple route table entries and deletes entries. Terraform seems not able to correctly add to the route table without removing entries therefore leaving itself in a consistently inconsistent and undesired state.

```bash
Error: error waiting for Route in Route Table (rtb-0f2b0a90993fcd470) with destination (172.1.3.0/24) to become available: timeout while waiting for state to become 'ready' (timeout: 2m0s)
```

```
  # module.add_routes_to_client_vpn["10.200.32.0/24"].aws_default_route_table.route_table will be updated in-place
  ~ resource "aws_default_route_table" "route_table" {
        id                     = "rtb-07867b14b30e7fd04"
      ~ route                  = [
          + {
              + cidr_block                 = "10.200.32.0/24"
              + destination_prefix_list_id = ""
              + egress_only_gateway_id     = ""
              + gateway_id                 = ""
              + instance_id                = ""
              + ipv6_cidr_block            = ""
              + nat_gateway_id             = ""
              + network_interface_id       = ""
              + transit_gateway_id         = ""
              + vpc_endpoint_id            = ""
              + vpc_peering_connection_id  = "pcx-0e6228868d99f660e"
            },
          - {
              - cidr_block                 = "10.200.33.0/24"
              - destination_prefix_list_id = ""
              - egress_only_gateway_id     = ""
              - gateway_id                 = ""
              - instance_id                = ""
              - ipv6_cidr_block            = ""
              - nat_gateway_id             = ""
              - network_interface_id       = ""
              - transit_gateway_id         = ""
              - vpc_endpoint_id            = ""
              - vpc_peering_connection_id  = "pcx-0e6228868d99f660e"
            },
        ]
        tags                   = {}
        # (6 unchanged attributes hidden)
    }

  # module.add_routes_to_client_vpn["10.200.34.0/24"].aws_default_route_table.route_table will be updated in-place
  ~ resource "aws_default_route_table" "route_table" {
        id                     = "rtb-07867b14b30e7fd04"
      ~ route                  = [
          - {
              - cidr_block                 = "10.200.33.0/24"
              - destination_prefix_list_id = ""
              - egress_only_gateway_id     = ""
              - gateway_id                 = ""
              - instance_id                = ""
              - ipv6_cidr_block            = ""
              - nat_gateway_id             = ""
              - network_interface_id       = ""
              - transit_gateway_id         = ""
              - vpc_endpoint_id            = ""
              - vpc_peering_connection_id  = "pcx-0e6228868d99f660e"
            },
          + {
              + cidr_block                 = "10.200.34.0/24"
              + destination_prefix_list_id = ""
              + egress_only_gateway_id     = ""
              + gateway_id                 = ""
              + instance_id                = ""
              + ipv6_cidr_block            = ""
              + nat_gateway_id             = ""
              + network_interface_id       = ""
              + transit_gateway_id         = ""
              + vpc_endpoint_id            = ""
              + vpc_peering_connection_id  = "pcx-0e6228868d99f660e"
            },
        ]
        tags                   = {}
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```

[Debug Output](https://gist.github.com/kderck/ff4e0f9382a987173ffd215d9739da5a)

### Steps to Reproduce

`terraform apply`

`terraform apply -target=module.add_routes_to_client_vpn`

### Important Factoids

`N/A`

### References

`N/A`

**Comment by justinretzolk** [comment]
Hey @kderck 👋 Thanks for taking the time to raise this! I believe this comes down to the use of `for_each` for the module that is using `aws_default_route_table`. Looking at the [`aws_default_route_table` documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_route_table), it notes: 

> Every VPC has a default route table that can be managed but not destroyed. When Terraform first adopts a default route table, it **immediately removes all defined routes**. It then proceeds to create any routes specified in the configuration. This step is required so that only the routes specified in the configuration exist in the default route table.

My read on this is that for each of the module calls, the `aws_default_route_table` resource is removing the routes that were created by the other module calls. 

I think you could get around this by moving from a `for_each` statement in the module to a [dynamic block](https://www.terraform.io/language/expressions/dynamic-blocks) within the module itself (though I don't know if there's any other complexities within the module that might prevent you from doing so. This might look something like as follows (note: this is untested and is more of a suggestion of how you might approach this. That is to say, it may or may not work, but should be pretty close 😅):

```hcl
# main.tf
module "add_routes_to_client_vpn" {
  source     = "./modules//aws_route_table"
  from_vpc   = module.vpn_vpc.vpc_id
  to_vpc     = var.vpc_to_peer_with
  cidr_block = toset(var.route_to)
  peering_id = module.vpn_vpc_peering_requests.peering_id
}
```

```hcl
# /modules//aws_route_table"
resource "aws_default_route_table" "route_table" {
  default_route_table_id = data.aws_vpc.from_vpc.main_route_table_id

  dynamic "route" {
    for_each = var.cidr_block

    content {
      cidr_block                = route.value
      vpc_peering_connection_id = var.peering_id
    }
  }
}
```
