### ISSUE TITLE
resource/aws_guardduty_detector: Kubernetes events with GuardDuty

### ISSUE THREAD

**Issue by parente** [hashicorp/terraform-provider-aws#22987]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

GuardDuty now supports Elastic Kubernetes Service (EKS) audit log monitoring. Can the `aws_guardduty_detector` resource support a boolean switch to turn it on / off like it does for S3?

### New or Affected Resource(s)

* `aws_guardduty_detector`

### Potential Terraform Configuration

```hcl
resource "aws_guardduty_detector" "my_detector" {
  enable = true

  datasources {
    s3_logs {
      enable = true
    }
    eks_logs {
      enable = true
    }
  }
}
```

### References

- Announcement: https://aws.amazon.com/about-aws/whats-new/2022/01/amazon-guardduty-elastic-kubernetes-service-clusters/
- API documentation, for individual or organization setups: https://docs.aws.amazon.com/guardduty/latest/ug/kubernetes-protection.html
-  How this was implemented for S3 events: #14607

**Comment by mathewmoon** [comment]
Absolutely. I see this more as an important bug.

**Comment by woz5999** [comment]
any progress on this?

**Comment by danh-git** [comment]
Any update please?
