### ISSUE TITLE
aws_lb_target_group health_check timeout wont go below 5 sec

### ISSUE THREAD

**Issue by paullemon** [hashicorp/terraform-provider-aws#22995]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/aws v3.74.0

### Affected Resource(s)

- `aws_lb_target_group`

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_lb" "this" {
  drop_invalid_header_fields       = false
  enable_http2                     = true
  idle_timeout                     = 60
  enable_cross_zone_load_balancing = true
  enable_deletion_protection       = false
  load_balancer_type               = "gateway"
  name                             = "this"
  dynamic "subnet_mapping" {
    for_each = toset(["us-gov-west-1a"])
    content {
      subnet_id = data.aws_subnet.this[subnet_mapping.value].id
    }
  }
  timeouts {}
}

resource "aws_lb_target_group" "this" {
  port                 = 6081
  protocol             = "GENEVE"
  vpc_id               = data.aws_vpc.this.id
  target_type          = "instance"
  deregistration_delay = 10
  health_check {
    enabled             = true
    port                = 443
    protocol            = "HTTPS"
    interval            = 5
    timeout             = 2
    healthy_threshold   = 3
    unhealthy_threshold = 3
  }

resource "aws_lb_listener" "this" {
  load_balancer_arn = aws_lb.this.id
  default_action {
    target_group_arn = aws_lb_target_group.this.id
    type             = "forward"
  }
}
```

### Expected Behavior

The terraform documentation says the timeout can be between 2 and 120.  I can also use 2 for the timeout in the GUI.  

### Actual Behavior

When I set interval to 5 and timeout to 2 and apply it sets the timeout to 5.  

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @paullemon 👋 Thank you for taking the time to raise this! So that we have all of the information we may need to investigate this, can you supply (sanitized as needed) debug logs as well?
