### ISSUE TITLE
Cross Region RDS replica timing out

### ISSUE THREAD

**Issue by kiran251** [hashicorp/terraform-provider-aws#22990]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.12.31
+ provider.aws v3.66.0
```

### Affected Resource(s)

`aws_db_instance`

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_db_instance" "shard01" {
  # Name of instance
  identifier = "shard01"

  # Storage Specs
  allocated_storage     = 2000
  storage_type          = "io1"
  iops                  = 6000
  storage_encrypted     = true
  max_allocated_storage = 3000
  kms_key_id            = arn of the KMS key

  replicate_source_db = arn of the source DB

  #mysql
  engine         = "mysql"
  engine_version = "5.7.33"
  instance_class = "db.m5.4xlarge"
  username       = sampleuser

  backup_retention_period = 7
  maintenance_window      = "sat:09:05-sat:10:05"
  deletion_protection     = true

  db_subnet_group_name = aws_db_subnet_group.shard01.id
  option_group_name    = aws_db_option_group.shard01.id
  vpc_security_group_ids = [
    aws_security_group.mysql.id,
  ]

  parameter_group_name = aws_db_parameter_group.shard01.id
  monitoring_interval  = 60
  monitoring_role_arn  = data.aws_iam_role.rds-monitoring.arn

  multi_az                        = false
  auto_minor_version_upgrade      = false
  copy_tags_to_snapshot           = true
  performance_insights_enabled    = true
  enabled_cloudwatch_logs_exports = ["general", "slowquery"]

  apply_immediately = true
}
```

### Panic Output

No Crash logs on this

### Expected Behavior

The cross region RDS replicas should have created successfully with the specified RDS configurations without TF getting timed out and tainting the resources in the state file

### Actual Behavior

Terraform times out waiting for the RDS replica state and does not build the replicas with the all the specified configurations but rather the RDS replicas get created after a while (even after TF is timed out) with incomplete settings and also the RDS resources in the state file are marked as tainted

```
Error: timeout while waiting for state to become 'available, storage-optimization' (last state: 'creating', timeout: 40m0s)

  on rds.shard01.tf line 4, in resource "aws_db_instance" "shard01":
   4: resource "aws_db_instance" "shard01" {
```

We have about 10 RDS replicas with similar configuration that we need to create with the source DB in another region. So, we try to create all these RDS replicas at one time and Terraform times out with out fully applying the changes to them. So right now we are  doing an `terraform untaint` & another Terraform apply after verifying the replicas are in available state on the AWS console to apply the other configurations to the RDS replicas
### Steps to Reproduce

1. Create a Cross region replica with the source DB in different AWS region using the configuration above
2. `terraform apply`

Not sure if this can reproduce the issue

### Important Factoids

None

### References

None

* #0000

**Comment by sealneaward** [comment]
This seems to be an actual bug in the RDS console itself.
If you try to create a multi az Postgres RDS database with a read-replica instance, it hangs after it creates the first instance.
The second instance is never created.

You have to manually go in and create the read-replica after the first primary instance is created.

**Comment by kiran251** [comment]
@sealneaward That's not the case for me. The RDS replicas (10) will be created after terraform is timed out but with incomplete configurations and also taints the resources in the state file

**Comment by sealneaward** [comment]
I get the same bug in terraform as described in the issue in terraform.
I do not get the replica instance created though, it just times out both in terraform and in console.
I'm just trying to give a possible cause for the timeout, which seems to be RDS console related.

**Comment by sealneaward** [comment]
I think I may have had the wrong understanding of the order of operations.
Read replicas are not automatically created when creating multi az instances.
I'm going to try and replicate this issue more formally today.

What I was experiencing was timeouts of the initial multi az primary instance.
The resource for the read-replica was never created.
