### ISSUE TITLE
aws_elasticsearch_domain_saml_options default subject_key cause dashboard 500 internal error

### ISSUE THREAD

**Issue by soloradish** [hashicorp/terraform-provider-aws#23058]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_elasticsearch_domain_saml_options

### Terraform Configuration Files

OpenSearch version: `AWS managed OpenSearch 1.1`

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
 # We use opensearch custom domain name
 saml_options {
    #subject_key             = ""   # comment out let provider use default value `NameID`
    enabled                 = true
    session_timeout_minutes = 1440
    master_user_name        = "aaa@bbb.com"
    master_backend_role     = aws_iam_role.opensearch_admin.arn

    idp {
      entity_id = local.idp_entity_id
      metadata_content = data.local_file.idp_meta.content
    }
  }
```

### Panic Output

After success login in IDP side, browser redirect back to `https://opensearch_domain/_dashboards/_opendistro/_security/saml/acs`, and we got this error.
```
{"statusCode":500,"error":"Internal Server Error","message":"Internal Error"}
```

### Expected Behavior

Provider should use empty string `""` as `subject_key`'s default value, not `NameID`.

### Actual Behavior
Provider use `NameID` as `subject_key`'s default value cause `500 internal error`.

AND also cause we can not click `SAVE` button in `Edit security configuration` aws console page. 
error message we get `Subject key cannot be NameID. Leave this field empty to use the NameID element of the SAML assertion for the username.`

After we supply a empty string as `subject_key` param, error was gone and we can success login dashboard

```hcl
 # We use opensearch custom domain name
 saml_options {
    subject_key             = ""   # empty string as param
    enabled                 = true
    session_timeout_minutes = 1440
    master_user_name        = "aaa@bbb.com"
    master_backend_role     = aws_iam_role.opensearch_admin.arn

    idp {
      entity_id = local.idp_entity_id
      metadata_content = data.local_file.idp_meta.content
    }
  }
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by bodgit** [comment]
I ran into this and after liaising with AWS support, found out the cause. Setting the `subject_key` to `null` causes the literal `"NameID"` string to be configured, setting it to `""` fixes it.
