### ISSUE TITLE
resource "aws_ssm_maintenance_window_task" not filling in values for optional parameters, also can we pass a script as value?

### ISSUE THREAD

**Issue by Newbie112222** [hashicorp/terraform-provider-aws#23071]
Hi All,
I have been able to terraform the maintenance window task but i am running into a few issues as reported earlier in the below thread as well:
https://github.com/hashicorp/terraform-provider-aws/issues/4408

It looks like optional parameters like Working Directory, Execution Timeout are not being filled, the values are being passed in the code.
![image](https://user-images.githubusercontent.com/51801670/153239298-255e4850-8c98-459a-a9ec-eab32cacd27c.png)

Also, i want to pass in a shell script in the commands but i cant figure out a way, it says required values is a set of strings. Any ideas?

Code:

```hcl
resource "aws_ssm_maintenance_window_task" "task" {
  max_concurrency = 1
  max_errors      = 5000
  priority        = 1
  task_arn        = "AWS-RunShellScript"
  task_type       = "RUN_COMMAND"
  window_id       = aws_ssm_maintenance_window.Window.id

  targets {
    key    = "WindowTargetIds"
    values = [aws_ssm_maintenance_window_target.target.id]
  }

  task_invocation_parameters {
    run_command_parameters {
      timeout_seconds      = 600

      parameter {
        name   = "commands"
        values = ["date"] //want to pass a shell-script here, how do we do that?
      }
      parameter {
        name   = "Execution Timeout"
        values = ["3600"] //this value is not being filled in when checked in console
      }
    }
  }

  service_role_arn = var.ssm_arn
}
```

**Comment by justinretzolk** [comment]
Hey @Newbie112222 👋 Thank you for taking the time to raise this! When you have a moment, would you mind updating the issue description to include the rest of the information from the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md) to ensure we have all of the information we may need to look into this, and to help the community to contribute?

I took a look around and it looks like you may need to update your parameter name for the execution timeout. This took a bit of digging, but I found reference to the the correct value in an [AWS CLI document](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ssm/get-maintenance-window-task.html). It appears that for execution timeout, the appropriate parameter name is `executionTimeout`, while the working directory can be set using the `workingDirectory` parameter name.

As far as running a shell script, while I'm not personally well versed in maintenance window tasks, I found [this AWS document](https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-plugins.html#aws-runShellScript) that _seems_ to be what you're looking for. Namely: 

> runCommand
> Specify the commands to run or the path to an existing script on the instance.

Based on this, it would seem that the `commands` parameter may contain:

- A list of commands to run (the list of strings you'd mentioned, e.g. `["echo foo", "echo bar"]`)
- A path to an existing script on the instance (e.g. `["/path/to/script.sh"]`)

**Comment by Newbie112222** [comment]
Hi @justinretzolk i can try the suggestions which you gave and check of changing the parameter names fixes the issue. 

For passing the shell script perspective this worked for me:

data "local_file" "script" {
  filename = "run_command.sh"
}

  parameter {
        name   = "commands"
        values = ["${data.local_file.script.content}"]
      }

**Comment by Newbie112222** [comment]
Hi @justinretzolk i did try the parameters which you suggested and it has fixed the issue. Closing this issue. Thanks for you help on this!
