### ISSUE TITLE
Add support for App Runner VPC Connectors

### ISSUE THREAD

**Issue by jvisker** [hashicorp/terraform-provider-aws#23090]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Add support for VPC connectors in App Runner.

### New or Affected Resource(s)

* aws_apprunner_service
* aws_apprunner_vpc_connector

### Potential Terraform Configuration

```hcl
//New resource
resource "aws_apprunner_vpc_connector" "connector" {
  vpc_connector_name = "name"
  subnets            = ["subnet1", "subnet2"]
  security_groups    = ["sg1", "sg2"] // optional
  
  // Needs to at least output the arn
}

resource "aws_apprunner_service" "service" {
  // Add new section here to existing resource
  network_configuration {
    egress_configuration {
      egress_type       = "VPC"                                     // OR "DEFAULT"
      vpc_connector_arn = aws_apprunner_vpc_connector.connector.arn //Only valid if egress_type is VPC
    }
  }
}
```

### References

* https://aws.amazon.com/blogs/aws/new-for-app-runner-vpc-support/

**Comment by Yoshiitaka** [comment]
I am just currently working on this issue with @[Synohara](https://github.com/Synohara)-san.

**Comment by andymac4182** [comment]
Thanks @Yoshiitaka @Synohara-san. Excited to get this :)

**Comment by Yoshiitaka** [comment]
We've created a Pull Request to fix this Issue.
https://github.com/hashicorp/terraform-provider-aws/pull/23173
