### ISSUE TITLE
`aws_s3_bucket_lifecycle_configuration` MalformedXML error with `transition days` set to 0

### ISSUE THREAD

**Issue by idanoo** [hashicorp/terraform-provider-aws#23117]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.5
AWS Provider 4.0.0

### Affected Resource(s)

* aws_s3_bucket_lifecycle_configuration

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket" "bucket" {
  bucket = "tests3bucket"
}

resource "aws_s3_bucket_acl" "bucket_acl" {
  bucket = aws_s3_bucket.bucket.id
  acl    = "private"
}

resource "aws_s3_bucket_lifecycle_configuration" "s3_lifecycle" {
  bucket = aws_s3_bucket.bucket.bucket

  rule {
    id = "IntelligentTiering"
    status = "Enabled"

    abort_incomplete_multipart_upload {
        days_after_initiation = 1
    }

    noncurrent_version_transition {
      noncurrent_days = 0
      storage_class   = "INTELLIGENT_TIERING"
    }

    transition {
      days          = 0
      storage_class = "INTELLIGENT_TIERING"
    }
  }
}
```

### Panic Output

```shell
│ Error: error creating S3 Lifecycle Configuration for bucket (<hidden>): MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
│ 	status code: 400, request id: <hidden>, host id: <hiddne>
│ 
│   with module.site.aws_s3_bucket_lifecycle_configuration.s3_lifecycle,
│   on .terraform/modules/site/main.tf line 95, in resource "aws_s3_bucket_lifecycle_configuration" "s3_lifecycle":
│   95: resource "aws_s3_bucket_lifecycle_configuration" "s3_lifecycle" {
│ 
```

### Expected Behavior

Terraform applies policy successfully. This worked previously in-line with AWS Provider < 4.0.0.

The issue comes from:
```hcl
    transition {
      days          = 0
      storage_class = "INTELLIGENT_TIERING"
    }
```

It specifies this requires a positive integer and using `1` works, however we currently have 0 setup which is allowed in the UI. 

`noncurrent_version_transition` still allows 0 in AWS Provider 4.0.0

![image](https://user-images.githubusercontent.com/9691551/153525064-b52d3828-02be-42e1-af48-b54f73426d7b.png)

![image](https://user-images.githubusercontent.com/9691551/153525087-f09910a2-2e84-436b-af70-b658c2b4a5ee.png)

Further investigation lets me set 0 days using awscli with the following command

```shell
aws s3api put-bucket-lifecycle-configuration --bucket <bucket_name> --lifecycle-configuration '{
    "Rules": [
        {
            "ID": "IntelligentTiering",
            "Prefix": "",
            "Status": "Enabled",
            "Transitions": [
                {
                    "Days": 0,
                    "StorageClass": "INTELLIGENT_TIERING"
                }
            ],
            "NoncurrentVersionTransitions": [
                {
                    "NoncurrentDays": 0,
                    "StorageClass": "INTELLIGENT_TIERING"
                }
            ],
            "AbortIncompleteMultipartUpload": {
                "DaysAfterInitiation": 1
            }
        }
    ]
}'
```
### Actual Behavior

Errors applying policy with MalformedXML trying to set 0 during terraform apply.

### Steps to Reproduce

Run `terraform apply` with the above `aws_s3_bucket_lifecycle_configuration` configuration.

**Comment by Rajendraladkat1919** [comment]
Can you please check you have proper permission to create life cycle configuration. I can see `status code: 400` . Please confirm the same.

**Comment by idanoo** [comment]
I have just re-confirmed full admin IAM user and receive the same error. I suspect AWS is returning a 400 Bad Request as the http code for Malformed XML.

**Comment by anGie44** [comment]
Thank you for reporting this @idanoo . can confirm the resource doesn't send the value in the request; the resource only sends values `> 0` seen here:

https://github.com/hashicorp/terraform-provider-aws/blob/419f146bc64a8a74a0d1d44b069bce0467546823/internal/service/s3/flex.go#L350-L372

**Comment by idanoo** [comment]
Do you know which cases will return a MalformedXML? This function appears to only handle items in the tfMap["transition"] map which seem to accept a date or >= 0.

Happy to submit a patch for this @anGie44

**Comment by anGie44** [comment]
Hi @idanoo , one case is when you want to specify the `date` in the `transition` block but not the `days`. with the patch provided, the API request will have both the `date` and `days` configured and ends in the ` MalformedXML` error. 

E.g. Test:

```go
func TestAccS3BucketLifecycleConfiguration_DateTransition(t *testing.T) {
	rName := sdkacctest.RandomWithPrefix(acctest.ResourcePrefix)
	resourceName := "aws_s3_bucket_lifecycle_configuration.test"
	currTime := time.Now()
	date := time.Date(currTime.Year(), currTime.Month()+1, currTime.Day(), 0, 0, 0, 0, time.UTC).Format(time.RFC3339)

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:     func() { acctest.PreCheck(t) },
		ErrorCheck:   acctest.ErrorCheck(t, s3.EndpointsID),
		Providers:    acctest.Providers,
		CheckDestroy: testAccCheckBucketLifecycleConfigurationDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccBucketLifecycleConfiguration_DateTransitionConfig(rName, date),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckBucketLifecycleConfigurationExists(resourceName),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccBucketLifecycleConfiguration_DateTransitionConfig(rName, transitionDate string) string {
	return fmt.Sprintf(`
resource "aws_s3_bucket" "test" {
  bucket = %[1]q
}

resource "aws_s3_bucket_acl" "test" {
  bucket = aws_s3_bucket.test.id
  acl    = "private"
}

resource "aws_s3_bucket_lifecycle_configuration" "test" {
  bucket = aws_s3_bucket.test.bucket

  rule {
    id     = "IntelligentTiering"

	abort_incomplete_multipart_upload {
	  days_after_initiation = 1
	}

    noncurrent_version_transition {
      noncurrent_days = 0
      storage_class   = "INTELLIGENT_TIERING"
    }

    transition {
      date          = %[2]q
      storage_class = "INTELLIGENT_TIERING"
    }

    status = "Enabled"
  }
}
`, rName, transitionDate)
}
```

**Comment by thinkbrown** [comment]
So FWIW I just ran into the same thing, and I think it might be an issue with how the XML body of the request is being created.

My rule looks like the following:
```
resource "aws_s3_bucket_lifecycle_configuration" "hotfolder-uploads" {
  bucket = aws_s3_bucket.hotfolder-uploads.id
  rule {
    id     = "intelligent-tiering"
    status = var.s3_tiering ? "Enabled" : "Disabled"
    transition {
      days          = 0
      storage_class = "INTELLIGENT_TIERING"
    }
  }
}
```
but the resulting request (captured with `TF_LOG=DEBUG`) doesn't include a Days field. 

```
<LifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Rule>
        <Transition>
            <StorageClass>INTELLIGENT_TIERING</StorageClass>
        </Transition>
        <Filter>
            <Prefix></Prefix>
        </Filter>
        <ID>intelligent-tiering</ID>
        <Status>Enabled</Status>
    </Rule>
</LifecycleConfiguration>
```

Meanwhile, I tested the same rule with provider v3.60.0 and got this:
```
<LifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Rule>
        <ID>intelligent-tiering</ID>
        <Filter>
            <Prefix></Prefix>
        </Filter>
        <Status>Enabled</Status>
        <Transition>
            <Days>0</Days>
            <StorageClass>INTELLIGENT_TIERING</StorageClass>
        </Transition>
    </Rule>
</LifecycleConfiguration>
```

**Comment by idanoo** [comment]
Thank you @anGie44 - The new commit looks good to me
