### ISSUE TITLE
Selecting Backups By Conditions: AWS_Backup_Selection returns unexpected block

### ISSUE THREAD

**Issue by oldManLemon** [hashicorp/terraform-provider-aws#23118]
### Issue
Just following the instructions for creating a condition based backup lifecycle in AWS, when I attempt to use the condition block which is referenced in the documentation it returns an error stating the condition block was not expected?

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_selection#selecting-backups-by-conditions

### Affected Resource(s)

* aws__Backup_Selection

### Terraform Configuration Files

There are more but at this point even the example is just returning the error

```hcl
resource "aws_backup_selection" "our_chosen_resources" {
  iam_role_arn = aws_iam_role.aws_backup_role.arn
  name         = "my_selected_resources"
  plan_id      = aws_backup_plan.daily_backup_rention_policy.id

  condition {
    string_equals {
      key   = "aws:ResourceTag/Component"
      value = "rds"
    }
    string_like {
      key   = "aws:ResourceTag/Application"
      value = "app*"
    }
    string_not_equals {
      key   = "aws:ResourceTag/Backup"
      value = "false"
    }
    string_not_like {
      key   = "aws:ResourceTag/Environment"
      value = "test*"
    }
  }
}
```

### Expected Behavior

Accepts the existence of the condition code block

### Actual Behavior

```
ar.snapshot_tags - *terraform.NodeRootVariable
------
e: "aws_backup_selection.our_chosen_resources" waiting on "aws_iam_role.aws_backup_role"
2022/02/11 02:52:59 [ERROR] <root>: eval: *terraform.EvalValidateResource, err: Unsupported block type: Blocks of type "condition" are not expected here.
2022/02/11 02:52:59 [ERROR] <root>: eval: *terraform.EvalSequence, err: Unsupported block type: Blocks of type "condition" are not expected here.
2022/02/11 02:52:59 [TRACE] [walkValidate] Exiting eval tree: aws_backup_selection.our_chosen_resources
2022/02/11 02:52:59 [TRACE] vertex "aws_backup_selection.our_chosen_resources": visit complete
2022/02/11 02:52:59 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2022/02/11 02:52:59 [TRACE] dag/walk: upstream of "provider.aws (close)" errored, so skipping
2022/02/11 02:52:59 [TRACE] dag/walk: upstream of "root" errored, so skipping

Error: Unsupported block type

  on main.tf line 101, in resource "aws_backup_selection" "our_chosen_resources":
 101:   condition {

Blocks of type "condition" are not expected here.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

* #0000

**Comment by ewbankkit** [comment]
Relates #22074.

@oldManLemon Thanks for raising this issue.
Which version of the Terraform AWS Provider are you using?
The `aws_backup_selection.condition` block was added in [**v3.72.0**](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3720-january-13-2022).

**Comment by celso-vts** [comment]
I came across this issue and having the wrong pinned version for `hashicorp/aws` was the problem. Updating to the latest did the trick for me.
