### ISSUE TITLE
Resource churn with v4 S3 refactoring

### ISSUE THREAD

**Issue by acdha** [hashicorp/terraform-provider-aws#23129]
While working through the changes for the S3 refactoring in v4, I noticed two resource classes still report changes after refactoring my code and importing the corresponding resources.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.0.0
+ provider registry.terraform.io/hashicorp/dns v3.2.1
+ provider registry.terraform.io/hashicorp/external v2.2.0
+ provider registry.terraform.io/hashicorp/http v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Affected Resource(s)

* aws_s3_bucket_acl
* aws_s3_bucket_lifecycle_configuration

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket_acl" "logs" {
  bucket = aws_s3_bucket.logs.id
  acl    = "log-delivery-write"
}

resource "aws_s3_bucket_lifecycle_configuration" "logs" {
  bucket = aws_s3_bucket.logs.id

  rule {
    id     = "log-expiration"
    status = "Enabled"
    prefix = ""

    transition {
      days          = 30
      storage_class = "STANDARD_IA"
    }

    transition {
      days          = 180
      storage_class = "GLACIER"
    }
  }
}
```

### Expected Behavior

No changes

### Actual Behavior

```hcl
  # aws_s3_bucket_acl.logs will be updated in-place
  ~ resource "aws_s3_bucket_acl" "logs" {
      + acl    = "log-delivery-write"
        id     = "MYPROJECT-development-logs"
        # (1 unchanged attribute hidden)

        # (1 unchanged block hidden)
    }

  # aws_s3_bucket_lifecycle_configuration.logs will be updated in-place
  ~ resource "aws_s3_bucket_lifecycle_configuration" "logs" {
        id     = "MYPROJECT-development-logs"
        # (1 unchanged attribute hidden)

      ~ rule {
            id     = "log-expiration"
            # (1 unchanged attribute hidden)

          - filter {
              - object_size_greater_than = 0 -> null
              - object_size_less_than    = 0 -> null
            }

            # (2 unchanged blocks hidden)
        }
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform plan`

### References

* #23106

**Comment by anGie44** [comment]
Hi @acdha , thank you for reporting this issue! Just to get some initial background info and verify one of the imports, when importing the `acl` resource into state, was the `acl` value provided in the id as well e.g. `MYPROJECT-development-logs,log-delivery-write` ?

**Comment by acdha** [comment]
> Hi @acdha , thank you for reporting this issue! Just to get some initial background info and verify one of the imports, when importing the `acl` resource into state, was the `acl` value provided in the id as well e.g. `MYPROJECT-development-logs,log-delivery-write` ?

Ooooh, that's probably it — I just imported the resource itself.  The documentation template's 3 column breakpoints mean that the end of the resource name is clipped to make room for the side columns and since it imported without an error using the `terraform import aws_s3_bucket_acl.example example` form I never thought to see if there was more past the end of the bucket identifier.

![Screen Shot 2022-02-11 at 12 01 34 PM](https://user-images.githubusercontent.com/46565/153635450-fb1ddee8-6c80-4ad5-99c9-561f91e1f1f1.png)

**Comment by anGie44** [comment]
understood, thanks for clarifying! the upgrade just shows one example of import for brevity but if needed there are several options documented in https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_acl#import as well
