### ISSUE TITLE
error waiting for KMS Key() description propagation 

### ISSUE THREAD

**Issue by alekspickle** [hashicorp/terraform-provider-aws#23136]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_kms_key

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_kms_key" "key" {
  description             = "Key"
  tags                    = local.tags
  is_enabled              = true
  deletion_window_in_days = 7
}

// in variables.tf
variable "tags" {
type = map
default = {}
}

locals {
     test_tags = if var.env == "test" ? {
         "group" :  false
     } : null
     tags = merge(var.tags, local.test_tags)
}
```

### Panic Output

```
Error: error waiting for KMS Key (_) description propagation: timeout while waiting for state to become 'TRUE' (last state: 'FALSE', timeout: 5m0

```
### Expected Behavior

This is rather copy of [this post](https://discuss.hashicorp.com/t/error-waiting-for-kms-key-terraform-aws-provider-3-70/35597) in discuss
I want to upgrade to 4.3.0 because of some fixes but keep having error on apply.

### Actual Behavior

My tests are running in parallel and both use `terraform apply` when one passes second one fails with the error and leaves mess.
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Nothing special.

### References

A couple of discussion posts for context
[discuss 1](https://discuss.hashicorp.com/t/error-waiting-for-kms-key-timeout-while-waiting-for-state-to-become-true/33956/3)
[discuss 2](https://discuss.hashicorp.com/t/aws-kms-provider-not-working/28341)

* #20588
* #21225

I am deploying my project myself and reproduce this 100% with version 3.70.
But the main difference from others is that they  set policy explicitly while I don't set it at all.
Now I am on 4.3.0 and not able to repoduce it 100% but it still reproduced

From what I understand, there seems to be a bug introduced in `terraform-aws-provider` 3.52. And it seems to be still present, but rather avoided because of rarity.

Any ideas?

**Comment by tbugfinder** [comment]
It would be convenient if the resource would allow changes to the timeout in case it just takes too long.

**Comment by justinretzolk** [comment]
Hey @alekspickle 👋 Thank you for taking the time to raise this, and for the helpful links for context! So that we have all of the information we may need to look into this, can you update the issue description with the rest of the information requested in the [bug template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?

**Comment by trallnag** [comment]
> I just noticed major release 4.0.0! Gj guys, I'll try that and will let you know how if it stayed.

Note that there are quite a few breaking changes. Currently stuck with version 3

**Comment by trallnag** [comment]
Btw also not working for me

**Comment by alekspickle** [comment]
as of version 4.3.0 issue resolved. |_(-_-)_|
