### ISSUE TITLE
aws_dms_endpoint postgres source kms_key_arn is ignored

### ISSUE THREAD

**Issue by oeuftete** [hashicorp/terraform-provider-aws#23143]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```text
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.7.0
+ provider registry.terraform.io/cloudposse/utils v0.17.12
+ provider registry.terraform.io/datadog/datadog v3.8.1
+ provider registry.terraform.io/hashicorp/aws v3.73.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s)

* `aws_dms_endpoint`

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_dms_endpoint" "source_database" {

  # generic configurations
  endpoint_id   = "${local.name_prefix}-dms-cdc-source"
  endpoint_type = "source"
  engine_name   = "postgres"
  kms_key_arn   = aws_kms_key.source_database.arn

  database_name = var.source_database_name
  server_name   = var.source_database_hostname
  port          = var.source_database_port
  username      = var.source_database_username
  password      = data.aws_secretsmanager_secret_version.database_password.secret_string
  ssl_mode      = "require"

  extra_connection_attributes = local.source_extra_connection_attributes
}
```

### Debug Output

https://gist.github.com/oeuftete/bf314b8ddcda4beac1c94f31c5daad07

Note the lack of `KmsKeyId` in the structure.

### Expected Behavior

The key should have been passed to `dms/CreateEndpoint`.

### Actual Behavior

The key was not passed to `dms/CreateEndpoint`!  Subsequent `plan`s want to recreate the endpoint with the `kms_key_arn` provided to the resource, because it is initially created with AWS default `aws/dms` key.  That doesn't work because it gets recreated again with the default.  Lather, rinse, repeat.

### References

* The offending case statement missing `kms_key_arn`: https://github.com/hashicorp/terraform-provider-aws/blob/470002f3d3a7d9b349da7cadeadcb99ff7dfffff/internal/service/dms/endpoint.go#L530-L552
* The `default` case statement block that made this work before: https://github.com/hashicorp/terraform-provider-aws/blob/470002f3d3a7d9b349da7cadeadcb99ff7dfffff/internal/service/dms/endpoint.go#L579-L581
* Looks to have been introduced in https://github.com/hashicorp/terraform-provider-aws/pull/19040, so versions `<3.70.0` are probably ok?

**Comment by oeuftete** [comment]
In case others run into it, an effective but tedious workaround is to destroy the endpoint, create a bare minimum of the resource by hand (make sure the id and key are correct so that it can be updated, instead of re-created), then import it.

**Comment by YakDriver** [comment]
@oeuftete Thank you for raising this! It looks like what happened is that before #19040, Postgres didn't have its own case, as you note. Before it would use the `default` and the key would be set. Now, the key will not be set for any named cases (DynamoDB, OpenSearch, Kafka, Kinesis, Oracle, Postgres, or S3) with the exception of MongoDB, since it is required. We'll work on a fix for this!
