### ISSUE TITLE
Pass additional parameters to s3 api.

### ISSUE THREAD

**Issue by YuriGal** [hashicorp/terraform-provider-aws#23155]
Is there a way to pass additional parameters to the AWS API when creating `aws_s3_bucket` resource, namengly `CreateBucketConfiguration/LocationConstraint` ?

**Comment by justinretzolk** [comment]
Hey @YuriGal 👋 Thank you for taking the time to raise this. For what it's worth, questions like this that are not an issue or feature request are often better served by creating a new topic on the [Discuss forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33).

That said, there's not really a way to pass additional values that aren't mapped in some way to arguments in the provider. With regards to `CreateBucketConfiguration/LocationConstraint` specifically, however, this is handled by the provider [here](https://github.com/hashicorp/terraform-provider-aws/blob/a65002b873e17df5d0f19a6d16ff53d0c91a5aab/internal/service/s3/bucket.go#L676-L685). Essentially, the `LocationConstraint` is set to whatever region the AWS Provider is configured for (there's a special case in there for `us-east-1`, which is the default and not an accepted value for the API).

If you'd like to specifically create an S3 bucket in a region other than the region configured in the AWS Provider, the best method would be to use a second, [aliased](https://www.terraform.io/language/providers/configuration#alias-multiple-provider-configurations) instance of the AWS Provider with a different region configured.

**Comment by ljluestc** [comment]
Terraform doesn't provide a direct way to set the LocationConstraint for an S3 bucket, as it typically uses the region configured in the AWS provider block. However, you can work around this limitation by using the AWS CLI or AWS SDK in a script (Python, for example) to create the S3 bucket with the desired LocationConstraint
```
import boto3

# Specify your desired region here
desired_region = 'us-west-2'

# Create an S3 client with the desired region
s3_client = boto3.client('s3', region_name=desired_region)

# Define the bucket name and LocationConstraint
bucket_name = 'your-unique-bucket-name'
location_constraint = desired_region

# Create the S3 bucket with the desired LocationConstraint
try:
    response = s3_client.create_bucket(
        Bucket=bucket_name,
        CreateBucketConfiguration={
            'LocationConstraint': location_constraint
        }
    )
    print(f"Bucket {bucket_name} created successfully in region {desired_region}")
except Exception as e:
    print(f"Error creating bucket: {str(e)}")

```

**Comment by justinretzolk** [comment]
Given the information provided, closing this as answered. If there are follow up questions, please open a new issue.
