### ISSUE TITLE
Documentation error: import command of aws_cognito_user_pool misses a parameter

### ISSUE THREAD

**Issue by wzyboy** [hashicorp/terraform-provider-aws#23158]
The [Import](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool#import) section of `aws_cognito_user_pool` resource currently reads:

> Cognito User Pools can be imported using the id, e.g.,
> `$ terraform import aws_cognito_user_pool.pool`

It should be:

> Cognito User Pools can be imported using the id, e.g.,
> `$ terraform import aws_cognito_user_pool.pool us-west-2_abc123`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by wzyboy** [comment]
A similar error exists in the [Import](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool_client#import) section of `aws_cognito_user_pool_client`.

**Comment by ericrichtert** [comment]
@wzyboy See https://github.com/hashicorp/terraform-provider-aws/tree/main/website/docs/r and below
