### ISSUE TITLE
AWS "aws_fsx_windows_file_system" Not accepting aliases param 

### ISSUE THREAD

**Issue by almero2020** [hashicorp/terraform-provider-aws#23170]
### Terraform CLI and Terraform AWS Provider Version

Terraform v0.15.5
AWS v3.36.0

### Affected Resource(s)

aws_fsx_windows_file_system

### Terraform Configuration Files

terraform {
  required_version = "0.15.5"
}

resource "random_pet" "tfc_refresh_upgrades" {
  keepers = {
    refresh : "2"
  }
}

### Expected Behavior

Alias is a documented param for FSX since AWS provider 3.5 . 
why is it not expected ? 

How do I give the FSX a dns friendly name . 
Also tried overriding default default out dns_name , but TF wants me to declare that. 
That DNS is my private on prem dns so cant declare that . 

### Actual Behavior

Error: Unsupported argument
│
│   on fsx_sft_npr.tf line 67, in resource "aws_fsx_windows_file_system" "SFTnonprodFSX":
│   67:   aliases             = [myfsx.sanitize.com]
│
│ An argument named "aliases" is not expected here.

### Steps to Reproduce

1. `terraform  validate and plan `

resource "aws_fsx_windows_file_system" "SFTnonprodFSX" {
  provider            = aws.africa 
  active_directory_id = var.aws_dsid_af
  deployment_type     = "SINGLE_AZ_1"
  kms_key_id          = var.kms_key.af.data
  storage_capacity    = 100
  subnet_ids          = var.fsx_subnet_ids_1az
  throughput_capacity = 64
  storage_type        = "SSD"
  security_group_ids  = aws_security_group.SFTnonprod_sg.id
  aliases             = [myfsx.sanitize.com]

### References

* #0000

**Comment by DrFaust92** [comment]
Closing for lack of response.
