### ISSUE TITLE
Documentation of aws_mq_broker incorrect

### ISSUE THREAD

**Issue by ericrichtert** [hashicorp/terraform-provider-aws#23171]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

`λ terraform version
Terraform v1.1.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.0.0`

### Affected Resource(s)

* aws_mq_broker

### Terraform Configuration Files

```hcl
resource "aws_mq_broker" "tf-mq-broker" {
  broker_name = var.brokername

  configuration {
    id       = aws_mq_configuration.tf-mq-configuration.id
    revision = aws_mq_configuration.tf-mq-configuration.latest_revision
  }

  engine_type        = "ActiveMQ"
  engine_version     = "5.16.3"
  host_instance_type = var.brokerinstancetype
  security_groups = [
    aws_security_group.tf-sg-mq-broker.id
  ]

  user {
    username       = "admin"
    password       = sensitive("MindNothingElse")
    console_access = true
  }

  encryption_options {
    kms_key_id        = aws_kms_key.tf-kms-key-broker.arn
    use_aws_owned_key = false
  }

  authentication_strategy = "ldap"
  ldap_server_metadata {
    hosts                    = ["ldaphost"]
    service_account_username = var.ldapbinduser
    service_account_password = var.ldapbindpasswords[var.environment]
    role_base                = "OU=else,DC=somewhere,DC=com"
    role_search_subtree      = true
    user_base                = "OU=else,DC=somewhere,DC=com"
    user_search_subtree      = true
  }
  auto_minor_version_upgrade = false

  publicly_accessible = false
  deployment_mode     = "ACTIVE_STANDBY_MULTI_AZ"
  storage_type        = "EFS"
  subnet_ids = [
    data.aws_subnet.tf-ohra-eu-west-1a.id,
    data.aws_subnet.tf-ohra-eu-west-1b.id
  ]

  logs {
    audit   = true
    general = true
  }
  apply_immediately = true
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

According to https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mq_broker#role_search_matching , the role_search_matching argument is optional.

### Actual Behavior
`
│ Error: InvalidParameter: 2 validation error(s) found.
│ - missing required field, CreateBrokerRequest.LdapServerMetadata.RoleSearchMatching.
│ - missing required field, CreateBrokerRequest.LdapServerMetadata.UserSearchMatching.
`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
As soon as I have everything working, I can create a PR for the documentation. Please let me know.

**Comment by justinretzolk** [comment]
Hey @ericrichtert 👋 Thank you for taking the time to raise this! It looks like these values may have been updated to be set to `required` as of AWS Go SDK version 1.39.2. I'd like to leave this open so that we can look into it as a bug rather than a documentation fix, in case there's anything in the provider that actually needs to be changed.

**Comment by ericrichtert** [comment]
The provider is working fine, as far as I can see. The AWS console is clear about required and optional settings:
Required:
![image](https://user-images.githubusercontent.com/54763328/154014430-917af849-65bb-43e4-9794-686a9778f29a.png)
Optional:
 
![image](https://user-images.githubusercontent.com/54763328/154014469-d0186b8f-38ff-451f-a38f-f461bf4b5af4.png)
