### ISSUE TITLE
[docs] aws_launch_template.metadata_options.http_endpoint isn't optional

### ISSUE THREAD

**Issue by PabloL007** [hashicorp/terraform-provider-aws#23174]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

- Terraform: 1.0.2
- AWS provider: 3.63.0

### Affected Resource(s)

* aws_launch_template

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "aws_launch_template" "workers" {
  ...
  dynamic "metadata_options" {
    for_each = try([each.value.metadata_put_response_hop_limit], [])

    content {
      http_put_response_hop_limit = metadata_options.value # Set to 2 when pods need access to AWS IMDS
    }
  }
  ...
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The [documentation](https://registry.terraform.io/providers/hashicorp/aws/3.63.0/docs/resources/launch_template#metadata-options) states that the `http_endpoint` attribute is optional and that the default value is "enabled" so I would expect it to use that value when I don't override it in my config.

### Actual Behavior

The apply failed with the following output:
```
╷
│ Error: error creating Launch Template (<OMITTED>) Version: InvalidParameterValue: A value of ‘’ is not valid for http-endpoint. Valid values are ‘enabled’ or ‘disabled’.
│ 	status code: 400, request id: <OMITTED>
│ 
│   with module.eks_cluster.aws_launch_template.workers["<OMITTED>"],
│   on ../../eks_cluster/node_group.tf line 54, in resource "aws_launch_template" "workers":
│   54: resource "aws_launch_template" "workers" {
│ 
╵
```

### Steps to Reproduce

1. Create a launch template with a `metadata-options` block that only sets the `http_put_response_hop_limit` attribute
1. `terraform apply`

### Important Factoids

None

### References

None

**Comment by justinretzolk** [comment]
Hey @PabloL007 👋 Thank you for taking the time to raise this! On an initial pass, I'm wondering if this may be an actual bug rather than a documentation issue. As such, I've marked it as a bug so that we can take a look into it.

To whomever picks this up: if you come to the determination that this indeed a docs issue, I'd be happy to open a PR to correct the documentation.

**Comment by justinretzolk** [comment]
Related: #12564
