### ISSUE TITLE
Tagging support for AMP workspaces

### ISSUE THREAD

**Issue by mhausenblas** [hashicorp/terraform-provider-aws#23172]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support [tagging AMP workspaces](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP_tagging.html).

### New or Affected Resource(s)

* `aws_prometheus_workspace`

### Potential Terraform Configuration

```hcl
resource "aws_prometheus_workspace" "tf-tag" {
  alias = "tf-tag"

  tags = {
    Environment = "prod"
    Owner = "mh9"
  }
}
```

**Comment by mhausenblas** [comment]
FYI: I'm working on this ATM so feel free to assign to me.

**Comment by mhausenblas** [comment]
@ewbankkit thank you so much! Can you please advise when this feature will be available (IOW: when is the next release planned that includes the tagging support)?

**Comment by ewbankkit** [comment]
@mhausenblas We are intending to release **v4.1.0**, including this enhancement, later today.
