### ISSUE TITLE
Error: GuardDuty admin account cannot be changed

### ISSUE THREAD

**Issue by cdaniluk** [hashicorp/terraform-provider-aws#23215]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.74.2
+ provider registry.terraform.io/rhythmictech/errorcheck v3.0.0
```

### Affected Resource(s)

- aws_guardduty_organization_admin_account

### Terraform Configuration Files

```hcl
resource "aws_guardduty_organization_admin_account" "guardduty" {
  admin_account_id = "123456789012"
}

resource "aws_guardduty_organization_configuration" "guardduty" {
  auto_enable = true
  detector_id = aws_guardduty_detector.guardduty.id

  depends_on = [aws_guardduty_organization_admin_account.guardduty]
}
```

### Expected Behavior

When changing the admin account ID, Terraform should call the `disable-organization-admin-account` API before calling the `enable-organization-admin-account` API. It does not. Docs:

https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_organizations.html#delegated-admin-dereg

### Actual Behavior

By not disabling first, the subsequent call fails:

```shell
│ Error: error enabling GuardDuty Organization Admin Account (688506813760): BadRequestException: The request failed because another account is already enabled as GuardDuty delegated administrator for the organization.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "9c4cfe50-2de5-48f2-b1e9-4f3aa924b858"
│   },
│   Message_: "The request failed because another account is already enabled as GuardDuty delegated administrator for the organization.",
│   Type: "InvalidInputException"
│ }
│
│   with aws_guardduty_organization_admin_account.guardduty,
│   on guardduty.tf line 5, in resource "aws_guardduty_organization_admin_account" "guardduty":
│    5: resource "aws_guardduty_organization_admin_account" "guardduty" {
```

### Steps to Reproduce

1. Configure a GuardDuty admin account in TF and apply.
2. Change the account ID in TF and apply again.

If you manually click Remove in console (or run `aws guardduty disable-organization-admin-account --account-id=[OLD_ACCOUNT]` in between steps 1 and 2, this works as expected.

**Comment by justinretzolk** [comment]
Hey @cdaniluk 👋 Thank you for taking the time to raise this! So that we have all of the information necessary to investigate this, can you supply (sanitized as necessary) debug logs as well?
