### ISSUE TITLE
aws_msk_cluster resource creation times out and taints resource after successful creation

### ISSUE THREAD

**Issue by josiegd-verrency** [hashicorp/terraform-provider-aws#23217]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.12.31
+ provider.aws v4.0.0

### Affected Resource(s)

* aws_msk_cluster

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_msk_cluster" "msk_green" {
  count                  = var.enable_green_stack ? 1 : 0
  cluster_name           = "kafka-green"
  kafka_version          = "2.6.2"
  number_of_broker_nodes = 3
  enhanced_monitoring = "PER_TOPIC_PER_BROKER"

  configuration_info {
    arn = aws_msk_configuration.msk_green[0].arn
    revision = aws_msk_configuration.msk_green[0].latest_revision
  }

  broker_node_group_info {
    instance_type  = var.instancetype_green
    ebs_volume_size = var.disksize_green
    client_subnets = split(",", data.aws_ssm_parameter.private_subnet_ids.value)
    security_groups = [ aws_security_group.msk.id ]
  }

  client_authentication {
    tls {
      certificate_authority_arns = [data.aws_ssm_parameter.acm_arn.value]
    }
# TO BE REENABLED WHEN TF SUPPORTS THIS CONCURRENTLY WITH TLS
#    sasl {
#      scram = true
#    }
  }

  encryption_info {
    encryption_at_rest_kms_key_arn = aws_kms_key.msk.arn
    encryption_in_transit {
        client_broker = "TLS"
        in_cluster    = true
    }
  }

}
```

### Expected Behavior

MSK stack creation using aws provider 3.x normally takes around 30 minutes.  Once the resource was created in AWS, terraform writes a creation complete message and continues with creation of the other dependent resources.  

Output from one such one is shown.

```


Initializing the backend...
--
...
  | Initializing provider plugins...
  | - Checking for available provider plugins...
  | - Downloading plugin for provider "aws" (hashicorp/aws) 3.74.0...
...
  |  
  | * provider.aws: version = "~> 3.74"
...
  | aws_msk_cluster.msk_green[0]: Creating...
  | aws_msk_cluster.msk_green[0]: Still creating... [10s elapsed]
  | aws_msk_cluster.msk_green[0]: Still creating... [20s elapsed]
...
  | aws_msk_cluster.msk_green[0]: Still creating... [31m1s elapsed]
  | aws_msk_cluster.msk_green[0]: Still creating... [31m11s elapsed]
  | aws_msk_cluster.msk_green[0]: Creation complete after 31m18s [id=arn:aws:kafka:us-east-2:123456789012:cluster/dev-kafka-green/12345689-1234-1234-1234-123445567889-3]
...
  |  
  | Apply complete! Resources: 23 added, 0 changed, 0 destroyed.
  |  
```

### Actual Behavior

Resource creation in AWS took around 30 minutes, as per previous experience.    With v4.0 aws provider, it seems that the terraform process didn't detect creation was complete, or wasn't signalled somehow, so continued to print progress, right up until the STS token expired.

At this point, after re-running the plan, the `aws_msk_cluster` resource was marked as tainted.

Some output from the buildkite job that creates the MSK stack.  

```
  | aws_msk_cluster.msk_green[0]: Still creating... [1h7m10s elapsed]
  | aws_msk_cluster.msk_green[0]: Still creating... [1h7m20s elapsed]
  | aws_msk_cluster.msk_green[0]: Still creating... [1h7m30s elapsed]
  | aws_msk_cluster.msk_green[0]: Still creating... [1h7m40s elapsed]
  | aws_msk_cluster.msk_green[0]: Still creating... [1h7m50s elapsed]
  | aws_msk_cluster.msk_green[0]: Still creating... [1h8m0s elapsed]
  | aws_msk_cluster.msk_green[0]: Still creating... [1h8m10s elapsed]
  | aws_msk_cluster.msk_green[0]: Still creating... [1h8m20s elapsed]
  |  
  | Error: error waiting for MSK Cluster (arn:aws:kafka:us-east-2:123456789012:cluster/dev-kafka-green/12345689-1234-1234-1234-123445567889-3) create: ExpiredTokenException:
  |  

```

### Steps to Reproduce

1. `terraform plan`
1. `terraform apply`

### Important Factoids

After failure, the `aws_msk_cluster` was marked as tainted.  SInce the resource was created in AWS, I untainted the resource and continued on with the creation of other dependent resources.

### References

* #0000

**Comment by carl34** [comment]
Experienced the same issue with `ExpiredTokenException` errors which appeared to occur after 15 minutes. Confirmed that AWS credentials had not expired and that raw AWS CLI commands could be run from outside of TF.

The version which was exhibiting the issue for me was `provider.terraform-provider-aws_v4.1.0_x5`, downgraded to `3.74.2` and was able to create an MSK cluster without timing out.

**Comment by HammerNL89** [comment]
We are experiencing the same issue (on a different resource): 
`DEBUG: Validate Response eks/DescribeNodegroup failed, attempt 0/25, error ExpiredTokenException:`

For us it's happening when Terraform tries to create resource `"aws_eks_node_group" `after it created `resource "aws_eks_cluster"`

Node group is created successfully, but Terraform doesn't receive the status because of the ExpiredTokenException. 

We downgrade from 4.1.0 back to 3.74.0 and the problem seems to have disappeared.
