### ISSUE TITLE
Region validation still fails for some regions in v4.1.0

### ISSUE THREAD

**Issue by nozaq** [hashicorp/terraform-provider-aws#23223]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.1.0
```

### Affected Resource(s)

* `region` argument for `provider` block

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "ap-northeast-3"
}

data "aws_caller_identity" "current" {}
```

### Debug Output

https://gist.github.com/nozaq/adc37bf9913a6f245b709561b5ddf1f3

### Expected Behavior

`terraform plan` does not product any error.

### Actual Behavior

The following error returned.

```
│ Error: Invalid AWS Region: ap-northeast-3
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on main.tf line 10, in provider "aws":
│   10: provider "aws" {
```

### Steps to Reproduce

1. `terraform init`
1. `terraform plan`

### Additional Context

#23191 tried to resolve this issue by updating `aws-sdk-go-base` to `v2.0.0-beta.7`, but it seems the necessary changes are not included in [this version](https://github.com/hashicorp/aws-sdk-go-base/blob/v2.0.0-beta.7/internal/endpoints/endpoints.go) though already merged into `main` branch.
We need to update `aws-sdk-go-base` to the next version when released.

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/23116
* https://github.com/hashicorp/terraform-provider-aws/pull/23191

**Comment by gdavison** [comment]
This functionality has been released in [v4.2.0 of the Terraform AWS Provider](https://github.com/hashicorp/terraform-provider-aws/blob/v4.2.0/CHANGELOG.md).
