### ISSUE TITLE
Add missing EMR cluster applications

### ISSUE THREAD

**Issue by cpinamtz** [hashicorp/terraform-provider-aws#23226]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi here, I'm trying to see how can I install JupyterEnterpriseGateway in EMR cluster which is using EMR release 6.2.0 or higher. As it's warned by AWS in its [EMR Notebooks Considerations docs](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-managed-notebooks-considerations.html#considerations-limitations):

> Important
For EMR release versions 5.32.0 and later, or 6.2.0 and later, your cluster must also be running the Jupyter Enterprise Gateway application in order to work with EMR Notebooks.

However, based on the `aws_emr_cluster` resource's `applications` attribute, JupyterEnterpriseGateway is not in those possible values hence I'm stuck using the 6.1.0 version.

Besides the request, I'm curious about how this `applications` attribute is translated into something understandable by Terraform to initialize the cluster properly but I've not seen any reference [apart from the docs and README in this repository](https://github.com/hashicorp/terraform-provider-aws/search?q=JupyterHub) or [the organization code](https://github.com/search?q=org%3Ahashicorp+JupyterHub&type=code) to any sort of function or method related to this translation mechanism (if it exists).

Thanks in advance!

### New or Affected Resource(s)

* `aws_emr_cluster`

**Comment by justinretzolk** [comment]
Hey @cpinamtz 👋 Thank you for taking the time to raise this! I took a look over it, and it appears that the list of possible values for the `applications` argument is a bit out of date, but the provider code does not seem to have any validation built in that would force the values to be in the list of documented options, so I believe this is possible without any provider code changes. 

Assuming the [most recent EMR release](https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-650-release.html), my read is that you'd need to set the `release_label` argument to `"emr-6.5.0"` and then `applications` could be set to `["JupyterEnterpriseGateway"]`.

If that does indeed work as I would expect based on my read, I would be more than happy to work on a documentation pull request to provide a more clear description of the possible values (likely by way of just linking to the AWS documentation).

**Comment by cpinamtz** [comment]
Works like a charm! So yes, it's needed only to update docs. Thanks for your help @justinretzolk
