### ISSUE TITLE
New Resource: Add aws_subnet_tag resource

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#23230]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add a "tag-only" resource for AWS Subnet. Similar model to `aws_ec2_tag` and `aws_autoscaling_group_tag` for adding tags to a resource managed outside of Terraform.

### New or Affected Resource(s)

* aws_subnet_tag

### Potential Terraform Configuration

```hcl
resource "aws_subnet_tag" "example" {
  resource_arn = [subnet ARN]
  key         = "Name"
  value       = "Hello World"
}
```

### References

* [aws_ecs_tag](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_tag)
* [aws_ec2_tag](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_tag)
* [aws_autoscaling_group_tag](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group_tag)

**Comment by ewbankkit** [comment]
This should already be possible with the `aws_ec2_tag` resource, passing the subnet ID in the `resource_id` argument.

**Comment by scalp42** [comment]
Already possible:

```hcl
resource "aws_ec2_tag" "dev_eks_subnets" {
  provider    = aws.us-west-2
  for_each    = toset(aws_subnet.public.*.id)
  resource_id = each.key
  key         = "kubernetes.io/cluster/${aws_eks_cluster.dev.name}"
  value       = "shared"
  depends_on  = [aws_eks_cluster.dev]
}
```
