### ISSUE TITLE
Add support for disabling default reverse DNS rules to Route53 Resolver

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#23233]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_route53_resolver_config

### Potential Terraform Configuration

```hcl
resource "aws_route53_resolver_config" "example" {
  resource_id = aws_vpc.example.id
  autodefined_reverse_flag = "ENABLE"
}
```

### References

* [UpdateResolverConfigAPI](https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_UpdateResolverConfig.html#Route53Resolver-route53resolver_UpdateResolverConfig-request-AutodefinedReverseFlag)

**Comment by ewbankkit** [comment]
Similar: https://github.com/hashicorp/terraform-provider-aws/issues/21507.
