### ISSUE TITLE
Unable to add dynamic block for versioning_configuration for aws s3 in version 4.0.0

### ISSUE THREAD

**Issue by dheerajkumar96** [hashicorp/terraform-provider-aws#23246]
When trying to add dynamic block for aws s3 versioning configuration , I'm getting the error 'versioning_configuration' argument is required. please find below code instance and suggest the best answer. 

```terraform
resource "aws_s3_bucket_acl" "firehose_to_s3" {
  bucket = aws_s3_bucket.firehose_to_s3.id
  acl    = "private"
}
resource "aws_s3_bucket_versioning" "firehose_to_s3" {
  bucket = aws_s3_bucket.firehose_to_s3.id

  dynamic "versioning_configuration" {
#value of replicate is false and true.
    for_each = var.replicate ? ["yes"] : []
    content {
      status = "Enabled"
    }

  }
}
```

below is the error I'm getting
The argument "versioning_configuration" is required, but no definition was
found.

**Comment by anGie44** [comment]
Hi @dheerajkumar96 , thank you for reporting this issue. While `versioning` was once optional in the `aws_s3_bucket` resource (pre v4.0 of the aws provider), now within the independent resource `aws_s3_bucket_versioning`, the `versioning_configuration` block itself is indeed `required` as suggested in the terraform CLI output. Thus, the block must be explicitly specified in the terraform configuration and cannot be optional as implied with `for_each = var.replicate ? ["yes"] : []`

With that said, if the intent is to optionally put versioning on a bucket based on a variable, may I suggest moving the `for_each` to the root-level of the resource e.g.

```terraform
resource "aws_s3_bucket_versioning" "firehose_to_s3" {
  for_each = var.replicate ? ["yes"] : []
 
  bucket = aws_s3_bucket.firehose_to_s3.id

  versioning_configuration {
      status = "Enabled"
  }
}
```

**Comment by dheerajkumar96** [comment]
@anGie44 Thank you for the response. But I'm looking for more of adding a dynamic block since the values for var.replicate will be added/called from two different instances and not from a direct set or map or array that contains true, false values.

The error I'm getting is ```
The given "for_each" argument value is unsuitable: the "for_each" argument
must be a map, or set of strings, and you have provided a value of type list
of string.
```
If i tried to convert it to map then I'm getting another error 
```
Invalid value for "v" parameter: cannot convert bool to map of any single
type.
```

Could you please help me resolve this? Is it not possible to add dynamic block for required arguments?

**Comment by anGie44** [comment]
Hi @dheerajkumar96 , so technically you could use a `dynamic` block with a `required` field but only if the `for_each` value always guarantees the block in question will be present e.g.

```terraform
variable "replicate" {
  default = true
}

resource "aws_s3_bucket_versioning" "test" {
  bucket = aws_s3_bucket.test.id

  dynamic "versioning_configuration" {
    for_each = var.replicate ? toset(["yes"]) : []

    content {
      status = "Enabled"
    }
  }
}
```

In this example, if `replicate` is set to `false`, terraform will error with:
```
│ Error: Insufficient versioning_configuration blocks
│
│   on main.tf line 10, in resource "aws_s3_bucket_versioning" "test":
│   10: resource "aws_s3_bucket_versioning" "test" {
│
│ At least 1 "versioning_configuration" blocks are required.
```

From my understanding, however, I don't believe it's common practice to use `dynamic` in this way.

**Comment by dheerajkumar96** [comment]
thank you @gdavison @anGie44 able to resolve it. 
I'm facing another issue. Below is the code for rule in aws_s3_bucket_replication_configuration. 

`rule {
    id = "ReplicateOut"
    prefix = "out"
    status = "Enabled"

    destination {
      bucket  = var.replication_bucket_arn
      account = var.replication_account_id
      # Despite the paramter being suffixed "_id" this does have to be the ARN

      encryption_configuration {
        replica_kms_key_id = var.replication_key_arn
      }

      access_control_translation {
        owner = "Destination"
      }
    }

    source_selection_criteria {
      sse_kms_encrypted_objects {
        status = "Enabled"
      }
    }
  }`

Below is the error I'm getting 
`Error: Missing required argument

  on ../modules/firehose-to-s3/main.tf line 243, in resource "aws_s3_bucket_replication_configuration" "firehose_to_s3":
 243: resource "aws_s3_bucket_replication_configuration" "firehose_to_s3" {

The argument
"rule.0.destination.0.encryption_configuration.0.replica_kms_key_id" is
required, but no definition was found.


Error: Missing required argument

  on ../modules/firehose-to-s3/main.tf line 245, in resource "aws_s3_bucket_replication_configuration" "firehose_to_s3":
 245:   role = var.replication_role_arn

The argument "role" is required, but no definition was found.`

I have declared all the variables in a variable file but not sure to resolve above error. version 4.0.0.

**Comment by dheerajkumar96** [comment]
After upgrading the code, it is mentioned to import the new resources. The import should be done after 'terraform apply' or before 'terraform apply'. when should we run the import commands?

**Comment by dheerajkumar96** [comment]
I have added empty filter block to lifecycle_configuration and when I run terraform plan it is saying it should change or update empty filter everytime. Do I need to import the resource after it has been created?
