### ISSUE TITLE
S3 Bucket Region Error after upgrading to 4.1.0

### ISSUE THREAD

**Issue by crearys** [hashicorp/terraform-provider-aws#23248]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ exec /usr/local/sbin/tini -g -- /bin/sh -c terraform -v
Terraform v1.1.4
on linux_amd64
```

### Affected Resource(s)

* aws_s3_bucket_server_side_encryption_configuration
* aws_s3_bucket_acl

### Terraform Configuration Files

```
provider "aws" {
  alias  = "eu-west-2"
  region = "eu-west-2"
}

resource "aws_s3_bucket" "example" {
  provider = aws.eu-west-2

  bucket = "example.${var.aws_account_id}"
}

resource "aws_s3_bucket_server_side_encryption_configuration" "example" {
  bucket = aws_s3_bucket.example.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_acl" "example" {
  bucket = aws_s3_bucket.example.id
  acl    = "private"
}
```

backend.tfvars

```
bucket = "terraform-state"
region = "eu-west-1"
```

versions.tf 

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.1.0"
    }
  }
}
```

### Expected Behavior

It should have no functional changes and update state. 

### Actual Behavior

We are having issues since attempting to update to the v4.1.0 AWS provider from v3.37.0.

We have a state bucket in the `eu-west-1` region, whilst the S3 buckets we update are in the `eu-west-2` region.

I have followed the upgrade guide and created the new S3 related resources. 

We are seeing errors for the `server-side encryption configuration` and the `ACL`. 

Errors around incorrect region when trying to apply S3 resource updates for v4 of the provider. 

```
Error: error creating S3 bucket (bucketname) server-side encryption configuration: BucketRegionError: incorrect region, the bucket is not in 'eu-west-1' region at endpoint '', bucket is in 'eu-west-2' region
```

```
Error: error creating S3 bucket ACL for bucketname: BucketRegionError: incorrect region, the bucket is not in 'eu-west-1' region at endpoint '', bucket is in 'eu-west-2' region
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by anGie44** [comment]
Hi @crearys , thank you for taking the time to report this issue. Please note though it has been reported in https://github.com/hashicorp/terraform-provider-aws/issues/23221. I'm going to close this as a duplicate, but please subscribe to #23221 for more information/recommendations/discussion around the topic.
