### ISSUE TITLE
Terraform 4.1 RDS Fails to Restore from Snapshot

### ISSUE THREAD

**Issue by charles-d-burton** [hashicorp/terraform-provider-aws#23251]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
➜  ~ terraform -v
Terraform v1.1.5
on linux_amd64

Provider version 4.1

### Affected Resource(s)

aws_rds_cluster

### Terraform Configuration Files

```hcl
module "cluster" {
  source           = "../../modules/cluster"
  cluster_name     = local.cluster_name
  vpc_id           = data.aws_vpc.vpc.id
  subnet_ids       = data.aws_subnet_ids.private.ids
  postgres_version = var.postgres_version

  #This should probably be locked down at some point
  inbound_cidr_blocks         = [data.aws_vpc.vpc.cidr_block]
  username_parameter_path     = "nope"
  password_parameter_path     = "nonpe2electricboogaloo"
  iam_roles                   = []
  database_name               = "masterdata"
  allow_major_version_upgrade = false
  skip_final_snapshot         = true
  deletion_protection = false

  restore_from_snapshot = true
  snapshot_arn          = data.aws_db_cluster_snapshot.master_data_snapshot.db_cluster_snapshot_arn
}

resource "aws_rds_cluster" "company_master_cluster" {
  cluster_identifier              = var.cluster_name
  engine                          = "aurora-postgresql"
  engine_version                  = data.aws_rds_engine_version.postgres_version.version
  database_name                   = var.database_name
  master_username                 = data.aws_ssm_parameter.username.value
  master_password                 = data.aws_ssm_parameter.password.value
  backup_retention_period         = 35
  kms_key_id                      = aws_kms_key.master_data_key.arn
  storage_encrypted               = true
  db_cluster_parameter_group_name = aws_rds_cluster_parameter_group.cluster_parameter_group.name

  # Necessary to allow database upgrades
  db_instance_parameter_group_name    = "default"
  db_subnet_group_name                = aws_db_subnet_group.cluster_subnet_group.name
  deletion_protection                 = var.deletion_protection
  iam_database_authentication_enabled = var.allow_major_version_upgrade ? false : true
  iam_roles                           = var.iam_roles
  vpc_security_group_ids              = [aws_security_group.aurora_sg.id]
  snapshot_identifier                 = var.restore_from_snapshot ? var.snapshot_arn : null
  allow_major_version_upgrade         = var.allow_major_version_upgrade
  skip_final_snapshot                 = var.skip_final_snapshot

  lifecycle {
    ignore_changes = [
      availability_zones,
    ]
  }
}
```

### Panic Output

The resource creates in the AWS Console and is green/available.  Terraform never finishes running and eventually times out or the token used to create it expires.
╷
│ Error: Error waiting for RDS Cluster state to be "available": ExpiredToken: The security token included in the request is expired
│ 	status code: 403, request id: 35e32e6b-856d-4252-840c-d3de0476fe4f
│ 
│   with module.cluster.aws_rds_cluster.company_master_cluster,
│   on ../../modules/cluster/main.tf line 52, in resource "aws_rds_cluster" "company_master_cluster":
│   52: resource "aws_rds_cluster" "company_master_cluster" {
│ 
╵
Releasing state lock. This may take a few moments...
### Expected Behavior

It should go green and move on to the next resources.

### Actual Behavior

Fails with the above error

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
The parameters need filled in and you need to restore from a snapshot.  Interesting note is what I think is happening is the v4.1 provider isn't making the attempt to restore from a snapshot.  I tried with the 3.x provider and it seems to have different behavior.  The restore from snapshot takes a lot longer for the 3.x versions of terrraform and if I had to guess I would say that the 4.1 provider is not passing that request on.  In fact the 3.x finishes just fine.

**Comment by justinretzolk** [comment]
Hey @charles-d-burton 👋 Thank you for taking the time to raise this! So that we have all of the information necessary to look into this, can you supply (redacted as necessary) debug logs as well?
