### ISSUE TITLE
Describe or list all rules for an ELB listener 

### ISSUE THREAD

**Issue by MaoChhaya** [hashicorp/terraform-provider-aws#23267]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

List all rules with priority in a listener
### New or Affected Resource(s)

* aws_lb_listener_rules

### Potential Terraform Configuration

```hcl
data "aws_lb_listener_rules" "main" {
 listener_arn = "xxxxxx"
}
```

### References

N/A

**Comment by bschaatsbergen** [comment]
If we decide to support this, I'll happily pick it up.

> https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_DescribeRules.html

**Comment by kamilturek** [comment]
I'll give it a try.
