### ISSUE TITLE
ACM certificate issue, when I try to add subject_alternative_names , domain_validation_options is removed.

### ISSUE THREAD

**Issue by dpa456** [hashicorp/terraform-provider-aws#23269]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform : 1.1.5
aws : version = ">= 3"

### Affected Resource(s)

* aws_acm_certificate

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

I think there should be no change in domain_validation_options when add subject_alternative_names to aws_acm_certificate
```
aws_acm_certificate.xtrm_roots_2 must be replaced
       subject_alternative_names = [ # forces replacement
          + "E",
            # (3 unchanged elements hidden)
        ]
```

### Actual Behavior

```
aws_acm_certificate.xtrm_roots_2 must be replaced
 domain_validation_options = [
          - {
              - domain_name           = "A"
              - resource_record_name  = "..."
              - resource_record_type  = "CNAME"
              - resource_record_value = "..."
            },
          - {
              - domain_name           = "B"
              - resource_record_name  = "..."
              - resource_record_type  = "CNAME"
              - resource_record_value = "..."
            },
          - {
              - domain_name           = "C"
              - resource_record_name  = "..."
              - resource_record_type  = "CNAME"
              - resource_record_value = "..."
            },
          - {
              - domain_name           = "D"
              - resource_record_name  = "..."
              - resource_record_type  = "CNAME"
              - resource_record_value = "..."
            },
            # (5 unchanged elements hidden)
       subject_alternative_names = [ # forces replacement
          + "E",
            # (3 unchanged elements hidden)
        ]
```

### Steps to Reproduce

1. There must be a pre-deployed acm environment.

```
resource "aws_acm_certificate" "xtrm_roots_2" {   
    provider = aws
    domain_name               = "A"   
    subject_alternative_names = ["B", "C", "D"]   
    validation_method         = "DNS"    

    lifecycle {     create_before_destroy = false   } } 
```

2. Add E san to subject_alternative_names list
```
resource "aws_acm_certificate" "xtrm_roots_2" {   
    provider = aws
    domain_name               = "A"   
    subject_alternative_names = ["B", "C", "D", "E"]   
    validation_method         = "DNS"    

    lifecycle {     create_before_destroy = false   } } 
```

3. terraform init & plan

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @dpa456 👋 Thank you for taking the time to raise this! In looking into this, I think this is less a factor of there being a change in `domain_validation_options`, and more a factor of changes to `subject_alternative_names` forcing replacement of the resource. Looking at the documentation for the `domain_validation_options` attribute: 

> Set of domain validation objects which can be used to complete certificate validation. Can have more than one element, e.g., if SANs are defined. Only set if DNS-validation was used.

Since you're defining an additional SAN, this set will have to be updated. Since the operation is a _replacement_, Terraform displays this as removing all of the items in the set, which will then be replaced with the new set when the resource is recreated.
