### ISSUE TITLE
Add Support for WAFv2 Managed Rule Group Configuration

### ISSUE THREAD

**Issue by cyn110** [hashicorp/terraform-provider-aws#23287]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Add Support for WAFv2 Managed Rule Group Configuration

WAFv2 recently added [AWS WAF Fraud Control account takeover prevention (ATP)](https://docs.aws.amazon.com/waf/latest/developerguide/waf-atp.html) feature as a new aws managed rule group. In order to use this managed rule group, some configuration is required to be put in, which is a new data structure that the current `aws_wafv2_rule_group` resource doesn't support.

### New or Affected Resource(s)

* aws_wafv2_rule_group

### References

* https://aws.amazon.com/about-aws/whats-new/2022/02/aws-waf-fraud-control-login-credential-attacks/
* https://docs.aws.amazon.com/waf/latest/developerguide/waf-atp.html

**Comment by justinretzolk** [comment]
Related: #23290

**Comment by fillz-noh** [comment]
I am sad that I am unable to integrate the ATP. Could you please progress this issue?

**Comment by adrianosela** [comment]
+1 on sadness, please prioritize :(

**Comment by marianod92** [comment]
Hello everyone!

Has anyone been able to solve this problem with some workaround through **aws-cli** for example?

I tried to activate Account Takeover Prevention through Terraform with a **_null_resource_** and **_aws-cli_**, but I did not find this option in the documentation and reference examples!

Thanks!

**Comment by hermes-pimentel** [comment]
you're a lifesaver @maiconbaum! Thank you.
