### ISSUE TITLE
Perpetual diffs / Objects have changed outside of Terraform (v3.70.0+)

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#23288]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Only reports after v3.70.0

Many of these issues were fixed with a collection of changes shown in #21968, v3.70.0. The purpose of this issue is to separate the older reports that may or may not be fixed from problems seen in v3.70.0+.

Unfortunately, these differences can be caused by a variety of problems. To have any chance of tackling them, we need to organize exactly what's still a problem, and what exactly the problems are. The causes are nuanced so we need specificity.

### Main Causes

1. **Eventual consistency** - AWS reports different things over time. We may need to wait for in certain places for things to settle down.
2. **Eqivalent but not equal** - AWS responds with different equivalent answers that the provider does not recognize as equivalent.
3. **Response disconnect** - Various disagreements between AWS and the Provider cause this:
    * Some arguments are not marked `computed` that should be
    * An AWS `nil` is interpretted as an empty string or vice versa
4. **Defaults** - AWS returns default values sometimes. The AWS Provider also has default values. Sometimes these match, sometimes they've changed.

### Affected Services and Resources

1. [`aws_backup_plan`](https://github.com/hashicorp/terraform-provider-aws/issues/22627) - `rule` without `schedule`
1. [`aws_backup_region_settings`](https://github.com/hashicorp/terraform-provider-aws/issues/22627) - `not_resources`, `resources`, `condition`
1. [`aws_codeartifact_domain_permissions_policy`](https://github.com/hashicorp/terraform-provider-aws/issues/23288#issuecomment-1103167851) - Principals order
1. [`aws_codeartifact_repository_permissions_policy`](https://github.com/hashicorp/terraform-provider-aws/issues/23288#issuecomment-1103167851) - Principals order
1. [`aws_dms_endpoint`](https://github.com/hashicorp/terraform-provider-aws/issues/19667) - `extra_connection_attributes` conflicting with `s3_settings`
2. [`aws_iam_policy`](https://github.com/hashicorp/terraform-provider-aws/issues/23288#issuecomment-1175361016) - Empty `tags` ([also](https://github.com/hashicorp/terraform-provider-aws/issues/23288#issuecomment-1276612174))
1. [`aws_iam_role`](https://github.com/hashicorp/terraform-provider-aws/issues/20107#issuecomment-985204259) - Order in `assume_role_policy` principals
3. [`aws_iam_role`](https://github.com/hashicorp/terraform-provider-aws/issues/23288#issuecomment-1175361016) - Empty `tags` ([also](https://github.com/hashicorp/terraform-provider-aws/issues/23288#issuecomment-1276612174))
1. [`aws_iam_role`](https://github.com/hashicorp/terraform-provider-aws/issues/23336) - Empty `inline_policy`
1. [`aws_mq_configuration`](https://github.com/hashicorp/terraform-provider-aws/issues/21619) - `data` XML argument
1. [`aws_s3_bucket_policy`](https://github.com/hashicorp/terraform-provider-aws/issues/22030) - principals in policy
1. [`aws_sqs_queue`](https://github.com/hashicorp/terraform-provider-aws/issues/23288#issuecomment-1087557101) - order in `policy`
4. [`aws_ssoadmin_permission_set_inline_policy`](https://github.com/hashicorp/terraform-provider-aws/issues/28834) - this seems different than many of the others because of actual substantive changes
1. [`aws_wafv2_web_acl `](https://github.com/hashicorp/terraform-provider-aws/issues/19727#issuecomment-1017952112) - `AWSManagedRulesAmazonIpReputationList`

#### Provider References (Open)

* #6107
* #19727
* #24338

#### Provider References (Closed)

* #11801
* #13144
* #17024
* #18878
* #19245
* #19365
* #19444
* #19627
* #20107
* #20456
* #20665
* #20781

#### Other References
* hashicorp/awspolicyequivalence#1
* hashicorp/awspolicyequivalence#7
* https://github.com/hashicorp/awspolicyequivalence
* hashicorp/terraform-plugin-framework#70
* hashicorp/terraform-plugin-sdk#801
* jen20/awspolicyequivalence#10
* hashicorp/terraform#22931
* hashicorp/terraform#27880
* hashicorp/terraform#28803
* hashicorp/terraform#29685

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-plugin-sdk/pull/882, available in the next [Terraform Plugin SDK v2](https://github.com/hashicorp/terraform-plugin-sdk) release should offer a way forward on some of these.

**Comment by jhancock93** [comment]
I can confirm that I am still seeing issues with drift on aws_iam_role assume_role_policy principals with provider 3.74.0.

**Comment by wuetz** [comment]
I can confirm that I am still seeing issues with diffs on aws_iam_role assume_role_policy principals with provider v4.5.0

**Comment by ad-m-ss** [comment]
I can confirm that I am still seeing issues with diffs on aws_iam_role assume_role_policy principals with provider v4.7.0.

**Comment by jcogilvie** [comment]
Echoing @jhancock93 with an example:

```
- Installing hashicorp/aws v3.75.1...
```

It detects this as drift that happened outside of terraform:

```
  # module....iam.aws_iam_role.engineer has been changed
!   resource "aws_iam_role" "engineer" {
!       assume_role_policy    = jsonencode(
!           {
!               Statement = [
!                   {
!                       Principal = {
!                           AWS = [
-                               "arn:aws:iam::136...:root",  # this isn't removed; just appears at the bottom of the list now.
                                "arn:aws:iam::119...:root",
+                               "arn:aws:iam::136...:root",
                            ]
                        }
                        # (3 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        id                    = "engineer"
        name                  = "engineer"
        tags                  = {
            "ManagedBy" = "https://github.com/..."
            "Name"      = "engineer"
            "Shared"    = "True"
            "Team"      = "SRE"
        }
        # (8 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

**Comment by forty** [comment]
Terraform 1.1.7 Provider AWS 4.8.0

We still have order problem for aws `aws_iam_role` - Order in `assume_role_policy`

We also have the this one which is not listed:

`aws_sqs_queue`-  Order in `policy`

**Comment by nitrocode** [comment]
Also seeing this with `aws_codeartifact_domain_permissions_policy`

Empty strings are empty because they are redacted

```hcl
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_codeartifact_domain_permissions_policy.main[0] will be updated in-place
  ~ resource "aws_codeartifact_domain_permissions_policy" "main" {
        id              = "arn:aws:codeartifact:us-west-2:312851193143:domain/default"
      ~ policy_document = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = {
                          ~ AWS = [
                              - "",
                              - "",
                              - "",
                              - "",
                              - "",
                              + "",
                                "",
                              - "",
                              + "",
                              + "",
                              + "",
                              + "",
                                "",
                              + "",
                              + "",
                              + "",
                                "",
                              - "",
                              - "",
                            ]
```

**Comment by ad-m-ss** [comment]
I have perpetual diff for `aws_ssoadmin_permission_set_inline_policy`. 

Environment:
* Terraform v1.1.7 on darwin_arm64
* registry.terraform.io/hashicorp/aws version = "4.7.0"

Example output: 
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_ssoadmin_permission_set_inline_policy.developer["1"] will be updated in-place
  ~ resource "aws_ssoadmin_permission_set_inline_policy" "developer" {
        id                 = "arn:aws:sso:::permissionSet/ssoins-6684bd07964ad0f4/ps-f7fa08c3ff7c1943,arn:aws:sso:::instance/ssoins-6684bd07964ad0f4"
      ~ inline_policy      = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Action   = [
                          - "logs:StartQuery",
                          - "logs:FilterLogEvents",
                          + "redshift:ViewQueriesFromConsole",
                          + "redshift:ListTables",
                          + "redshift:ListSchemas",
                          + "redshift:ListDatabases",
                          + "redshift:GetClusterCredentials",
                          + "redshift:FetchResults",
                          + "redshift:ExecuteQuery",
                          + "redshift:DescribeTable",
                          + "redshift:DescribeQuery",
                          + "redshift:DescribeClusters",
                          + "redshift:CancelQuery",
                        ]
                      ~ Resource = "arn:aws:logs:us-east-2::log-group:/aws/rds/instance/postgres-test-data/postgresql:*" -> "*"
                        # (2 unchanged elements hidden)
                    },
                  ~ {
                      ~ Action   = [
                          - "sns:List*",
                          - "sns:Get*",
                          + "redshift-data:ListTables",
                          + "redshift-data:ListSchemas",
                          + "redshift-data:ListDatabases",
                          + "redshift-data:ExecuteStatement",
                          + "redshift-data:DescribeTable",
                        ]
                      ~ Resource = "arn:aws:logs:us-east-2::log-group:/aws/rds/instance/postgres-test-data/postgresql:*" -> "*"
                        # (2 unchanged elements hidden)
                    },
                  ~ {
                      ~ Action   = [
                          - "cloudwatch:List*",
                          - "cloudwatch:Get*",
                          - "cloudwatch:Describe*",
                          + "redshift-data:ListStatements",
                          + "redshift-data:GetStatementResult",
                          + "redshift-data:DescribeStatement",
                          + "redshift-data:CancelStatement",
                        ]
                      ~ Resource = "arn:aws:logs:us-east-2::log-group:/aws/rds/instance/postgres-test-data/postgresql:*" -> "*"
                        # (2 unchanged elements hidden)
                    },
                  ~ {
                      ~ Action   = "autoscaling:Describe*" -> [
                          + "s3:ListMultipartUploadParts",
                          + "s3:ListBucketVersions",
                          + "s3:ListBucketMultipartUploads",
                          + "s3:ListBucket",
                          + "s3:GetReplicationConfiguration",
                          + "s3:GetObjectVersionTorrent",
                          + "s3:GetObjectVersionTagging",
                          + "s3:GetObjectVersionForReplication",
                          + "s3:GetObjectVersionAcl",
                          + "s3:GetObjectVersion",
                          + "s3:GetObjectTorrent",
                          + "s3:GetObjectTagging",
                          + "s3:GetObjectRetention",
                          + "s3:GetObjectLegalHold",
                          + "s3:GetObjectAcl",
                          + "s3:GetObject",
                          + "s3:GetMetricsConfiguration",
                          + "s3:GetLifecycleConfiguration",
                          + "s3:GetJobTagging",
                          + "s3:GetInventoryConfiguration",
                          + "s3:GetEncryptionConfiguration",
                          + "s3:GetBucketWebsite",
                          + "s3:GetBucketVersioning",
                          + "s3:GetBucketTagging",
                          + "s3:GetBucketRequestPayment",
                          + "s3:GetBucketPublicAccessBlock",
                          + "s3:GetBucketPolicyStatus",
                          + "s3:GetBucketPolicy",
                          + "s3:GetBucketOwnershipControls",
                          + "s3:GetBucketObjectLockConfiguration",
                          + "s3:GetBucketNotification",
                          + "s3:GetBucketLogging",
                          + "s3:GetBucketLocation",
                          + "s3:GetBucketCORS",
                          + "s3:GetBucketAcl",
                          + "s3:GetAnalyticsConfiguration",
                          + "s3:GetAccessPointPolicyStatus",
                          + "s3:GetAccessPointPolicy",
                          + "s3:GetAccelerateConfiguration",
                          + "s3:DescribeJob",
                        ]
                      ~ Resource = "arn:aws:logs:us-east-2::log-group:/aws/rds/instance/postgres-test-data/postgresql:*" -> [
                          + "arn:aws:s3:::select-star-audit-log-test/*",
                          + "arn:aws:s3:::select-star-audit-log-test",
                        ]
                        # (2 unchanged elements hidden)
                    },
                  - {
                      - Action   = [
                          - "logs:TestMetricFilter",
                          - "logs:StopQuery",
                          - "logs:List*",
                          - "logs:Get*",
                          - "logs:Describe*",
                        ]
                      - Effect   = "Allow"
                      - Resource = "arn:aws:logs:us-east-2:672751098944:log-group:/aws/rds/instance/postgres-test-data/postgresql:*"
                      - Sid      = ""
                    },
                  - {
                      - Action   = "logs:GetQueryResults"
                      - Effect   = "Allow"
                      - Resource = "arn:aws:logs:*:*:log-group::log-stream:"
                      - Sid      = ""
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        # (2 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by jhenry82** [comment]
I am seeing a similar issue with tags on IAM role and policy resources. Is that the same thing being discussed here or should I open a new issue? Example:

```
resource "aws_iam_policy" "test" {
  name        = "test"
  description = "test"
}

```

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

# aws_iam_policy.test has changed
  ~ resource "aws_iam_policy" "test" {
        id          = "redacted"
        name        = "test"
      + tags        = {}
        # (6 unchanged attributes hidden)
    }

```

If I explicitly set `tags = {}` on the policy, I get the same result.

Provider: v4.21.0
Terraform: v1.2.3

**Comment by cshen-confluent** [comment]
Seeing related issue with change detection:

```text
  # module.aws_iam_role.some_user_role will be updated in-place
~ resource "aws_iam_role" "some_user_role" {
      ~ assume_role_policy    = jsonencode(
            {
              - Statement = [
                  - {
                      - Action    = "sts:AssumeRoleWithSAML"
                      - Condition = {
                          - IpAddress    = {
                              - aws:SourceIp = [
                                  - "0.0.0.0/0",
                                ]
                            }
                          - StringEquals = {
                              - SAML:aud = "https://signin.aws.amazon.com/saml"
                            }
                        }
                      - Effect    = "Allow"
                      - Principal = {
                          - Federated = "arn:aws:iam::000000000000:saml-provider/provider"
                        }
                      - Sid       = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
        id                    = "administrator"
        name                  = "administrator"
        # (8 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```
Some information redacted.

I just added a blank line in code and this update plan will be generated among a lot other similar ones, and apply them won't make any actual change. Add another blank line will trigger the same plan.
We did some work to pinpoint the issue on `Condition.IpAddress` that if we don't put anything there it is fine.

**Comment by nestorcolt** [comment]
I have the problem with empty `+ tags = {}` from `aws_iam_policy` and `aws_iam_role`

```
  # aws_iam_role.lalala_poweruser has changed
  ~ resource "aws_iam_role" "lalala_poweruser" {
        id                    = "lalala_poweruser"
        name                  = "lalala_poweruser"
      + tags                  = {}
        # (11 unchanged attributes hidden)
    }
```

All my roles and policies are detecting this false drift with the tags property.

Terraform -v 1.3.2
AWS provider -v 4.34.0

**Comment by YakDriver** [comment]
We will close this issue soon after doing more work and research. This way we can determine how much of an issue this continues to be.

**Comment by YakDriver** [comment]
### Thank you for your comments!

At this point we have fixed many of these issues. However, with a big issue like crossing services, it's difficult to assess what's fixed and what still remains as time passes. Because of the amount of issues fixed, and tests to back the fixes up, we feel confident closing this issue in order to then be able to focus on what remains.

In other words, if you have perpetual diffs / `Objects have changed outside of Terraform` going forward, see if there is an existing issue for the specific resource and service you're concerned about. If there isn't one, let us know with a new issue!

**Comment by ad-m-ss** [comment]
I don't know the project code well, but I wonder why users have to report such things. The project has integration tests, so it seems to me that after each "apply" in the tests, you can introduce a subtest that will check whether the plan is clean. Many of the cases reported here are quite basic use cases.

The tests look like they have a similar structure, so you can either modify some core element from the test framework, or make a bulk refactor and add such a subtest.

**Comment by YakDriver** [comment]
@ad-m-ss I too would think this was easily tested. Unfortunately, though we run 1000s of tests, and specifically re-apply over and over to check this very thing, we don't run across the same problems. There may be other variables like age of accounts or regions at play but since we have a difficult time reproducing the problem despite heavy testing, we also have difficulty pinpointing a fix.

**Comment by nitrocode** [comment]
Yes, seconded. I've been waiting a long time for this to be resolved. You have shown great fortitude through your hard work and we appreciate it. Thank you!
