### ISSUE TITLE
MalformedXML: The XML you provided was not well-formed or did not validate against our published schema (aws_s3_bucket_lifecycle_configuration)

### ISSUE THREAD

**Issue by escanzano** [hashicorp/terraform-provider-aws#23296]
I get this error when running TF 1.1.6 and these versions

Installing hashicorp/random v3.1.0...
Installing hashicorp/external v2.2.0...
Installing hashicorp/aws v4.2.0...

Error: error creating S3 Lifecycle Configuration for bucket (test-master-deadletters): MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
12:26:30 	status code: 400, request id: ZHJK7AH24EXY85MC, host id: tj2hcv/f4GIhLmgx415nVsG0SDbbgCsCQJdAg4HqcU7wP8hDaDyzUAC2V0h/SWTNqlQjfZLeMqM=
12:26:30 
12:26:30   with module.s3.aws_s3_bucket_lifecycle_configuration.test_deadletters,
12:26:30   on ../../modules/s3/bucket_deadletters.tf line 6, in resource "aws_s3_bucket_lifecycle_configuration" "test_deadletters":
12:26:30    6: resource "aws_s3_bucket_lifecycle_configuration" "test_deadletters" {

This is my code

`resource "aws_s3_bucket" "test_deadletters" {
  bucket = "test-${var.env}-deadletters"
  tags = var.tags
}

resource "aws_s3_bucket_lifecycle_configuration" "test_deadletters" {
    bucket = aws_s3_bucket.test_deadletters.bucket

    rule {
        id = "exp"

        expiration {
            days = 90
        }

        filter {
            and {
                prefix = "queue="
            }
        }
        status = "Enabled"
    }
}

resource "aws_s3_bucket_public_access_block" "test_deadletters" {
  bucket = aws_s3_bucket.test_deadletters.bucket
  restrict_public_buckets = true
  ignore_public_acls = true
  block_public_acls = true
  block_public_policy = true
}

resource "aws_s3_bucket_policy" "test_deadletters" {
  count = var.aws_account != var.master_account_id ? 1 : 0
  bucket = aws_s3_bucket.test_deadletters.bucket
  policy = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Effect" : "Allow",
        "Principal" : {
          "AWS" : "arn:aws:iam::${var.master_account_id}:root"
        },
        "Action" : [
          "s3:GetObject",
          "s3:ListBucket"
        ],
        "Resource" : [
          "arn:aws:s3:::${aws_s3_bucket.test_deadletters.bucket}",
          "arn:aws:s3:::${aws_s3_bucket.test_deadletters.bucket}/*"
        ]
      }
    ]
  })
}

resource "aws_s3_bucket_inventory" "test_deadletters" {
  bucket = aws_s3_bucket.test_deadletters.bucket
  name = "athena"
  included_object_versions = "Current"
  schedule {
    frequency = "Daily"
  }
  destination {
    bucket {
      format = "Parquet"
      bucket_arn = aws_s3_bucket.test_events.arn
      prefix = "inventory"
    }
  }
  optional_fields = [
    "Size",
    "LastModifiedDate",
    "StorageClass",
    "ETag",
    "IsMultipartUploaded",
    "ReplicationStatus",
    "EncryptionStatus",
    "ObjectLockRetainUntilDate",
    "ObjectLockMode",
    "ObjectLockLegalHoldStatus",
    "IntelligentTieringAccessTier"
  ]
}

resource "aws_s3_object" "test_deadletters_cloudwatch_alarm_marker" {
  bucket = aws_s3_bucket.test_deadletters.bucket
  key = "cloudwatch-alarm-marker"
  content = ""
}`

**Comment by skajvitler** [comment]
+1 

I am having the same issue.

**Comment by escanzano** [comment]
I fixed this by changing the lifecycle resource to this below. Apparently, the filter section was a problem.

resource "aws_s3_bucket_lifecycle_configuration" "test_deadletters" {
    bucket = aws_s3_bucket.test_deadletters.bucket

    rule {
        id = "expiration"
        prefix = "queue="
        status = "Enabled"
        expiration {
            days = 90
        }
    }
}

**Comment by escanzano** [comment]
The use of and in the filter is a v4.0.0 feature but has been eliminated in 4.2. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3control_bucket_lifecycle_configuration

This is the old V4.0 doc link https://registry.terraform.io/providers/hashicorp/aws/4.0.0/docs/resources/s3_bucket_lifecycle_configuration
