### ISSUE TITLE
Significant slowdowns running terraform for WAF resources on AWS provider ~> 3.0

### ISSUE THREAD

**Issue by ficofer** [hashicorp/terraform-provider-aws#23300]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.6
on darwin_amd64

hashicorp/aws v3.74.3

### Affected Resource(s)

Non specific, the problem seems to be once if finished refreshing the state and start calculating the diffs to be apllied with the remote tfstate file.

### Terraform Configuration Files

The modules are all written following https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_ip_set

```hcl
resource "aws_wafv2_ip_set" "ipv4_addresses" {
  name               = "ipv4-addresses-${local.short_name}"
  scope              = "REGIONAL"
  ip_address_version = "IPV4"
  addresses          = var.allow_inbound_cidr_v4_addresses
}

resource "aws_wafv2_ip_set" "ipv6_addresses" {
  name               = "ipv6-addresses-${local.short_name}"
  scope              = "REGIONAL"
  ip_address_version = "IPV6"
  addresses          = var.allow_inbound_cidr_v6_addresses
}
```

vars allow_inbound_cidr_v4_addresses and allow_inbound_cidr_v6_addresses are a lists of around 1015 and 1961 items each, passed via .tfvars files from Terragrunt.

Once one of this two var are set to only 2 items, the time to run the plan is reduced from ~3 hours to 
```
149.03s user 6.05s system 134% cpu 1:55.56 total
```

### Debug Output

```
2022/02/21 13:28:12 [TRACE] dag/walk: vertex "module.example.module.waf.aws_wafv2_rule_group.ipv4_ipv6_rule_group (expand)" is waiting for "module.example.module.waf.aws_wafv2_ip_set.ipv6_addresses (expand)"
2022/02/21 13:28:12 [TRACE] dag/walk: vertex "module.example.module.waf.aws_wafv2_web_acl.ipv4_ipv6_web_acl (expand)" is waiting for "module.example.module.waf.aws_wafv2_rule_group.ipv4_ipv6_rule_group (expand)"
2022/02/21 13:28:12 [TRACE] dag/walk: vertex "meta.count-boundary (EachMode fixup)" is waiting for "module.example (close)"
2022/02/21 13:28:12 [TRACE] dag/walk: vertex "module.example.module.waf (close)" is waiting for "module.example.module.waf.aws_wafv2_web_acl_association.ipv4_ipv6_web_acl_association (expand)"
2022/02/21 13:28:12 [TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"
```

### Expected Behavior

The plan should render out the difference in a logic amount of time (as its expected to be two text files of (81Kb and 21Kb) getting compared to each other 

### Actual Behavior

The terraform plan command get stuck for hours at this output after refreshing remote state:

```
------------------------------------------------------------------------
```

### References

Seems like the same bug described here https://github.com/hashicorp/terraform-provider-aws/issues/14062 but it did not resolved by updating the terraform version.

**Comment by percygrunwald** [comment]
We need to do a little bit more investigation, but upgrading to Terraform `0.14.11` appeared to resolve this issue, but then upgrading again to Terraform `1.1.7` appears to bring this issue back up. In both cases, `v3.75.1` of the provider were used.

**Comment by percygrunwald** [comment]
Update on the above, it appears that my observation was pure luck. We subsequently ran into the same issue even on TF `0.14.11`. We now hypothesize our issue is related to our container's CPU limits and the `GOMAXPROCS` setting. It appears as though explicitly setting `GOMAXPROCS` results in the success of `plan` where previously there was consistent failure.
