### ISSUE TITLE
automation: Add upgrade check for versions of `tflint-ruleset-aws`

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#23320]
The [`tflint`](https://github.com/terraform-linters/tflint) tool has moved provider-specific rulesets to plugins, such as [`tflint-ruleset-aws`](https://github.com/terraform-linters/tflint-ruleset-aws). While the `tflint` core can be upgraded using Dependabot, there is no equivalent tracking for the plugins.

Add a GitHub Action to check for a new version and create a new PR

Relates #23303

**Comment by PatMyron** [comment]
also relates https://github.com/terraform-linters/tflint/issues/1181
