### ISSUE TITLE
aws_ssm_patch_baseline patch_filter argument documentation incorrect

### ISSUE THREAD

**Issue by joemilacek** [hashicorp/terraform-provider-aws#23323]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_ssm_patch_baseline

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ssm_patch_baseline" "name" {
  name                              = "name"
  approved_patches_compliance_level = "MEDIUM"
  operating_system                  = "CENTOS"

  approval_rule {
    approve_after_days  = 7
    compliance_level    = "MEDIUM"
    enable_non_security = true

    patch_filter {
      key    = "PRODUCT"
      values = ["CentOS7.9"]
    }

    patch_filter {
      key    = "CLASSIFICATION"
      values = ["Security", "Bugfix"]
    }

    patch_filter {
      key    = "MSRC_SEVERITY"
      values = ["Important", "Critical"]
    }
  }
}
```

### Expected Behavior

Update patch baseline with severity filter.

### Actual Behavior

Error: error updating SSM Patch Baseline (pb-xxxxxxx): ValidationException: Unknown Filter Key: MSRC_SEVERITY
        status code: 400, request id: xxxxxxx

### Steps to Reproduce

Above.

###

The argument name is incorrect. It should just be "SEVERITY", which works.

**Comment by justinretzolk** [comment]
Hey @joemilacek 👋 I started to work on a PR for a documentation update, but determined that the current documentation is accurate, though perhaps misleading in some ways so I wanted to follow up with you to discuss how best to clarify. 

The list of valid `approval_rule.patch_filter` keys [varies based on the operating system](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_PatchFilter.html). Valid keys may be found using the [DescribePatchProperties](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_DescribePatchProperties.html) command (or at the linked document). 

In the case of the [AWS Provider] documentation, the operating system used is `WINDOWS`, for which `MSRC_SEVERITY` is a valid key. On the other hand, in your example, `CENTOS` is used, which does have `SEVERITY`, but not `MSRC_SEVERITY`. This is why you saw the error that you did.

That said, this is where I think the documentation could use a little work. For `approval_patch.patch_filter`, it states: 

> Valid Keys are` PATCH_SET | PRODUCT | CLASSIFICATION | MSRC_SEVERITY | PATCH_ID`

My view is that this list of keys should be removed, leaving only the link to the `DescribePatchProperties` documentation. Given your experience with the current documentation, do you feel that would clarify things a bit more?
