### ISSUE TITLE
Change in behaviour on how credentials are picked up in v4.2

### ISSUE THREAD

**Issue by sunuaj** [hashicorp/terraform-provider-aws#23337]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

cli version 1.0.0
provider version 4.2.0

### Affected Resource(s)

aws provider

### Terraform Configuration Files

```hcl
provider "aws" {
         profile = "default"
}

terraform {
  required_providers {
      aws = "= 4.2"
  }
}

data "aws_caller_identity" "current" {}

output "account_id" {
  value = data.aws_caller_identity.current.account_id
}
```

### Expected Behavior

Noticed a change in behaviour on how AWS Provider picks up account credentials with v3.74 and v4.2

The account id in the output should be the account id of the credentials exported as env variables not the one in the credential file. according to [AWS Config Global Settings](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-global)

### Actual Behavior

It picks the account id of the credentials in the credential file. The behaviour changes to expected behaviour when `profile = "default"` is removed from provider config

### Steps to Reproduce
1. set the credentials for AWSAccount1 in the credentials file.
``` text
[default]
aws_access_key_id=XXX
aws_secret_access_key=XXX
aws_session_token=XXX 
```
2. export the env variable to set the credential for AWSAccount2
3. `terraform init`
4. `terraform apply`
5. Observe that the output is AWSAccount1
6. Change the aws provider version to 3.74
7. `terraform init --upgrade`
8. `terraform apply`
9. Observe that the output is AWSAccount2

**Comment by DrStrangepork** [comment]
I am seeing similar problems in a different context. We deploy Terraform templates via Jenkins, and we are seeing errors like this:

```
Error: error reading EventBridge Rule (windows-password-reset-lambda-cloudwatch-rule): AccessDeniedException: User: arn:aws:sts::999991910361:assumed-role/gentium-eks-cluster-linux-node-role-prod/i-07adcc37e80939cf1 is not authorized to perform: events:DescribeRule on resource: arn:aws:events:eu-west-1:999991910361:rule/windows-password-reset-lambda-cloudwatch-rule because no identity-based policy allows the events:DescribeRule action
	status code: 400, request id: 704e1638-feb1-4d1e-833e-75cf792bf518

Error: error reading SNS Topic (arn:aws:sns:eu-west-1:999981254214:windows-password-reset-lambda-999981254214-SNS-Topic): AuthorizationError: User: arn:aws:sts::999991910361:assumed-role/gentium-eks-cluster-linux-node-role-prod/i-07adcc37e80939cf1 is not authorized to perform: SNS:GetTopicAttributes on resource: arn:aws:sns:eu-west-1:999981254214:windows-password-reset-lambda-999981254214-SNS-Topic because no resource-based policy allows the SNS:GetTopicAttributes action
	status code: 403, request id: 70dc30a0-65c8-507a-884e-6a30f8b55da3
```
In both cases, you can see that the assumed-role used is the role of the Jenkins worker, not the role that we query for with `data "aws_caller_identity" "current" {}`.

I have confirmed this error does not occur v3.74. It only occurs with v4.x.

**Comment by gdavison** [comment]
Hi @sunuaj. This is now the expected behaviour and brings it in line with the AWS CLI and language SDKs. See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade#changes-to-authentication for more information.

When using the AWS CLI, if you define `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` and also pass `--profile`, for example `aws ec2 describe-instances --profile default`, the CLI will use the profile `default`.

In this case, because you are specifying the `profile` in the provider configuration, those are the credentials used.
