### ISSUE TITLE
Problems updating aws_wafv2_rule_group referenced in a aws_wafv2_web_acl

### ISSUE THREAD

**Issue by martin-viggiano** [hashicorp/terraform-provider-aws#23334]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

> Terraform v1.1.6
> on darwin_amd64
> + provider registry.terraform.io/hashicorp/aws v4.2.0

### Description

Changing the capacity (or any other parameter that forces a new resource) an aws_wafv2_rule_group resource that is being referenced in an aws_wafv2_web_acl resource will fail to apply because the aws_wafv2_rule_group resource that needs to be destroyed is referenced by the aws_wafv2_web_acl and can't be destroyed until that reference is deleted.

### Affected Resource(s)

* aws_wafv2_rule_group
* aws_wafv2_web_acl

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_wafv2_rule_group" "example_rg" {
  name     = "example_rg"
  scope    = "CLOUDFRONT"
  capacity = 4

  visibility_config {
    cloudwatch_metrics_enabled = false
    metric_name                = "friendly-metric-name"
    sampled_requests_enabled   = false
  }
}

resource "aws_wafv2_web_acl" "example" {
  name        = "managed-rule-example"
  description = "Example of a managed rule."
  scope       = "CLOUDFRONT"

  default_action {
    allow {}
  }

  rule {
    name     = "rule-1"
    priority = 1

    override_action {
      count {}
    }

    statement {
      rule_group_reference_statement {
        arn = resource.aws_wafv2_rule_group.example_rg.arn
      }
    }

    visibility_config {
      cloudwatch_metrics_enabled = false
      metric_name                = "friendly-rule-metric-name"
      sampled_requests_enabled   = false
    }
  }

  visibility_config {
    cloudwatch_metrics_enabled = false
    metric_name                = "friendly-metric-name"
    sampled_requests_enabled   = false
  }
}
```

### Debug Output

terraform plan output before failing:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aws_wafv2_rule_group.example_rg must be replaced
-/+ resource "aws_wafv2_rule_group" "example_rg" {
      ~ arn        = "arn:aws:wafv2:us-east-1:xxxxx:global/rulegroup/example_rg/cfc4e4c3-100b-4618-8f99-195682433605" -> (known after apply)
      ~ capacity   = 4 -> 5 # forces replacement
      ~ id         = "cfc4e4c3-100b-4618-8f99-195682433605" -> (known after apply)
      ~ lock_token = "4a353028-49b7-4aaa-ba93-aa70921b386e" -> (known after apply)
        name       = "example_rg"
      - tags       = {} -> null
      ~ tags_all   = {} -> (known after apply)
        # (1 unchanged attribute hidden)

        # (1 unchanged block hidden)
    }

  # aws_wafv2_web_acl.example will be updated in-place
  ~ resource "aws_wafv2_web_acl" "example" {
        id          = "326f2eba-16cc-4ce0-8cf1-ab06fb20cf70"
        name        = "managed-rule-example"
        tags        = {}
        # (6 unchanged attributes hidden)


      - rule {
          - name     = "rule-1" -> null
          - priority = 1 -> null

          - override_action {
              - count {}
            }

          - statement {

              - rule_group_reference_statement {
                  - arn = "arn:aws:wafv2:us-east-1:xxxx:global/rulegroup/example_rg/cfc4e4c3-100b-4618-8f99-195682433605" -> null
                }
            }

          - visibility_config {
              - cloudwatch_metrics_enabled = false -> null
              - metric_name                = "friendly-rule-metric-name" -> null
              - sampled_requests_enabled   = false -> null
            }
        }
      + rule {
          + name     = "rule-1"
          + priority = 1

          + override_action {
              + count {}
            }

          + statement {

              + rule_group_reference_statement {
                  + arn = (known after apply)
                }
            }

          + visibility_config {
              + cloudwatch_metrics_enabled = false
              + metric_name                = "friendly-rule-metric-name"
              + sampled_requests_enabled   = false
            }
        }

        # (2 unchanged blocks hidden)
    }

Plan: 1 to add, 1 to change, 1 to destroy.
```
### Expected Behavior

The rule that references the aws_wafv2_rule_group in the aws_wafv2_web_acl should be destroyed. Then the aws_wafv2_rule_group should be destroyed and created again. Finally the rule in the aws_wafv2_web_acl should be created again referencing the new aws_wafv2_rule_group.

### Actual Behavior

Terraform gets stuck at trying to delete the aws_wafv2_rule_group and timeouts after 5 minutes.

### Steps to Reproduce

1. `terraform apply`
2. Change the aws_wafv2_rule_group capacity.
3. `terraform apply`

### References

* #0000

**Comment by martin-viggiano** [comment]
Here is a workarround for this issue that I found:

```hcl
resource "aws_wafv2_rule_group" "example_rg2" {
  name     = "example_rg2_${random_integer.priority.result}"
  scope    = "CLOUDFRONT"
  capacity = var.example_rg2_capacity

  lifecycle {
    create_before_destroy = true
  }

  visibility_config {
    cloudwatch_metrics_enabled = false
    metric_name                = "friendly-metric-name"
    sampled_requests_enabled   = false
  }
}

resource "random_integer" "priority" {
  min = 1
  max = 50000

  keepers = {
    "rg" = var.example_rg2_capacity
  }
}

variable "example_rg2_capacity" {
  type    = number
  default = 10
}
```

It consists on adding a random (integer in this case) string to the rule group's name using a random_integer that has the capacity of the rule group as a keeper and setting the `create_before_destroy` lifecycle parameter of the rule group to true. Changing the rule group's capacity will force the creation of a new rule group, allowing the rules that reference the older rule group to be deleted and thus, allowing the deletion of the old rule group.

**Comment by codezninja** [comment]
Would love to see if there is way we can have provider fix this without the need for the workaround.

**Comment by ankon** [comment]
FWIW: This should be handled by using `name_prefix`, but rule groups didn't support that. See https://github.com/hashicorp/terraform-provider-aws/pull/33206 for a fairly mechanical "do that, then!" PR.
