### ISSUE TITLE
Update block_device_mappings datatype from set to list type, to make nested set values accessible

### ISSUE THREAD

**Issue by TG-KK** [hashicorp/terraform-provider-aws#23347]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This is continuation of #6775 since that one got closed.

I'm using latest AWS provider v4.2.0 & latest terraform v1.1.6 on mac, but still not able to individually lookup values inside `block_device_mappings` object for AWS AMI data source.

If I just dump that entire data as output, it looks/feels like the `block_device_mappings` is a list for sure, but when I try to reference it using the index, I get "Invalid Index" error.

Fortunately, other values like `root_device_name` & `root_snapshot_id` are accessible, which is great & partially solves my problem. But for suppressing or overriding the properties for the second or further volumes that are defined in AMI, I need to have access to the `device_name` and other nested values, so that I can configured them in a `aws_launch_template` resource.

### New or Affected Resource(s)

* data.aws_ami

### Potential Terraform Configuration

```hcl
# main.tf

data "aws_ami" "eks_ami" {
  owners           = ["self"]

  filter {
    name   = "image-id"
    values = ["ami-REDACTED"]
  }
}


# output.tf

output "ami_data" {
	value = data.aws_ami.eks_ami
}

output "ami_root_device_name" {
	value = data.aws_ami.eks_ami.root_device_name
}


output "ami_root_snapshot_id" {
	value = data.aws_ami.eks_ami.root_snapshot_id
}

# Above ones work

# This one doesn't
output "ami_second_device_name" {
	value = data.aws_ami.eks_ami.block_device_mappings[1].device_name
}

```

This is the error I get for that last output:

<img width="1675" alt="image" src="https://user-images.githubusercontent.com/6836944/155429263-e3e5f0d5-c592-4d7f-8cb5-cf79331cede2.png">

And here is the output for the ami_data variable:

![image](https://user-images.githubusercontent.com/6836944/155431107-b3f0bd7c-a52f-48ed-b08d-f35c2861ba9e.png)

### References

* #6775
* https://registry.terraform.io/providers/hashicorp/aws/4.2.0/docs/data-sources/ami#block_device_mappings

**Comment by justinretzolk** [comment]
Hey @TG-KK 👋 Thank you for taking the time to raise this! I did a bit of testing and found that you can use the output as is by utilizing `tolist()`:

```hcl
output "ami_second_device_name" {
  value = tolist(data.aws_ami.eks_ami.block_device_mapping)[1].device_name
}
```

With that in mind, would that resolve this issue for you?
