### ISSUE TITLE
aws_route.destination_cidr_block being evaluated in plan after 4.2.0 update - even if count evaluates to 0

### ISSUE THREAD

**Issue by rodrigoechaide** [hashicorp/terraform-provider-aws#23343]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.2.0
```

### Affected Resource(s)

* aws_route

### Terraform Configuration Files

```hcl
resource "aws_route" "global_ad" {
  count = local.main.global_ad_subnet != null ? 2 : 0

  route_table_id            = tolist([module.routing_tables.back_subnet_rt, module.routing_tables.nat_subnet_rt])[count.index]
  destination_cidr_block    = local.main.global_ad_subnet
  vpc_peering_connection_id = data.terraform_remote_state.vpc[terraform.workspace].outputs.global_ad_peering_id
}
```

**Note:** The problem happens when the value of ` local.main.global_ad_subnet` is `null`. Because of this, the `count` is set to `0` so `destination_cidr_block` should not be evaluated at all.

### Expected Behavior

`terraform plan` succeeds.

### Actual Behavior

```hcl
Acquiring state lock. This may take a few moments...
Releasing state lock. This may take a few moments...
╷
│ Error: Invalid combination of arguments
│ 
│   with aws_route.global_ad,
│   on 09_route_tables.tf line 23, in resource "aws_route" "global_ad":
│   23: resource "aws_route" "global_ad" {
│ 
│ "destination_prefix_list_id": one of `destination_cidr_block,destination_ipv6_cidr_block,destination_prefix_list_id` must be specified
╵
╷
│ Error: Invalid combination of arguments
│ 
│   with aws_route.global_ad,
│   on 09_route_tables.tf line 23, in resource "aws_route" "global_ad":
│   23: resource "aws_route" "global_ad" {
│ 
│ "destination_ipv6_cidr_block": one of `destination_cidr_block,destination_ipv6_cidr_block,destination_prefix_list_id` must be specified
╵
╷
│ Error: Invalid combination of arguments
│ 
│   with aws_route.global_ad,
│   on 09_route_tables.tf line 27, in resource "aws_route" "global_ad":
│   27:   destination_cidr_block    = local.main.global_ad_subnet
│ 
│ "destination_cidr_block": one of `destination_cidr_block,destination_ipv6_cidr_block,destination_prefix_list_id` must be specified
```

### Steps to Reproduce

1. `terraform plan`

### References

* #13003

**Comment by YakDriver** [comment]
This results from a combination:
* #22928 made `ExactlyOneOf` `destination_cidr_block`, `destination_ipv6_cidr_block`, or `destination_prefix_list_id` required
* Terraform is evaluating `ExactlyOneOf` before `count`

**Comment by YakDriver** [comment]
@rodrigoechaide Thank you for raising this issue! What you are doing should be possible as it was before. However, an upstream check is attempting to validate even when `count = 0`. We are considering the possible solutions and have raised this upstream as well (see hashicorp/terraform-plugin-sdk#894).
