### ISSUE TITLE
CloudFormation StackSet fails when no accounts are in target OU

### ISSUE THREAD

**Issue by davidbailey** [hashicorp/terraform-provider-aws#23349]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
terraform -v
Terraform v1.0.11
on darwin_amd64

Your version of Terraform is out of date! The latest version
is 1.1.6. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

aws_cloudformation_stack_set_instance

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudformation_stack_set_instance

### Terraform Configuration Files

```
resource "aws_cloudformation_stack_set_instance" "test" {
  deployment_targets {
    organizational_unit_ids = ["ou-abc123"]
  }

  region         = "us-west-2"
  stack_set_name = aws_cloudformation_stack_set.test.name
}
```

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

│ Error: unexpected format for ID (Test,,us-west-2), expected STACKSETNAME,ACCOUNDID,REGION

### Expected Behavior

StackSet should be created.

### Actual Behavior

StackSet is not created. Terraform State becomes corrupted.

### Steps to Reproduce

1. `terraform apply`

**Comment by sbutler** [comment]
I believe I'm seeing this same issue but I get a different error message. I'm also trying to deploy a bunch of stack set instances and the only ones that are failing are ones with no accounts in the OU:

```
Terraform v1.1.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.11.0

...

│ Error: error reading CloudFormation StackSet Instance (example,,us-west-1): ValidationError: 2 validation errors detected: Value '' at 'stackInstanceAccount' failed to satisfy constraint: Member must have length greater than or equal to 12; Value '' at 'stackInstanceAccount' failed to satisfy constraint: Member must satisfy regular expression pattern: ^[0-9]{12}$
│ 	status code: 400, request id: (removed)
│ 
│   with aws_cloudformation_stack_set_instance.main["example:us-west-1"],
│   on stacksets.tf line 58, in resource "aws_cloudformation_stack_set_instance" "main":
│   58: resource "aws_cloudformation_stack_set_instance" "main" {

```

**Comment by sbutler** [comment]
After digging into it, I think my issue relates to this part of the code:

https://github.com/hashicorp/terraform-provider-aws/blob/1fcfa970fab5ac66fcda2cb3df60e365ad6c06cd/internal/service/cloudformation/stack_set_instance.go#L269-L281

There's a lot of odd things going on in there. I understand that the deployment_targets stack instances aren't a traditional AWS resource you lookup, so there's some pivot to an account to get additional attributes (like `StackId`). However...

- Now the resource ID is tied to a particular account in one of the deployment OU's, whereas it started out as containing the deployment targets. What if that account it's tied to get moved to another OU? I imagine it creates unnecessary plan/apply churn.
- This fails badly when there are no accounts in the OU, as we've seen. To fix this I had to not only move accounts into the OU, but also `terraform state rm` and then `terraform import` (to fix the missing AccountID element in the resource ID).

I feel like the correct thing is to not at all lookup accounts when deployment_targets are used and to leave attributes like stack_id and account_id empty.

**Comment by skurtEnd** [comment]
**Produced the same issue with a different scenario:**

 -  StackSet and StackSet instances created successfully although the terraform failed due to a different issue
 -  Deleted the StackSet instances and the StackSet manually (because of the failure in the previous step)
 -  Ran terraform again and got: 
        - error finding CloudFormation StackSet Instance (<stack set details>) Account: couldn't find resource

Because the StackSet and StackSet instances are already in the TF state, terraform is expecting the StackSet to exist so that it can remove the StackSet instance and re-create it but it's already hitting that error in the destroy step

**Expected behaviour:**
Terraform to remove the StackSet and StackSet instance resource from state

**Comment by vishal0511** [comment]
Hi,

Any update on this request.
