### ISSUE TITLE
ssoadmin_permission_set_inline_policy documentation example is incorrect

### ISSUE THREAD

**Issue by awilson-payit** [hashicorp/terraform-provider-aws#23367]
Hello,

The documentation example for (ssoadmin_permission_set_inline_policy)(https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssoadmin_permission_set_inline_policy] has a minor error. 

```
resource "aws_ssoadmin_permission_set_inline_policy" "example" {
  inline_policy      = data.aws_iam_policy_document.example.json
  instance_arn       = aws_ssoadmin_permission_set.example.instance_arn
  permission_set_arn = aws_ssoadmin_permission_set.example.arn
}
```
The `instance_arn` should be `tolist(data.aws_ssoadmin_instances.example.arns)[0]`

**Comment by justinretzolk** [comment]
Hey @awilson-payit 👋 Thank you for taking the time to file this! I took a look over the documentation, and it appears that it is correct in its current form. Looking at the example in the documentation, I see the following (parts have been omitted for brevity):

```hcl
resource "aws_ssoadmin_permission_set" "example" {
  name         = "Example"
  instance_arn = tolist(data.aws_ssoadmin_instances.example.arns)[0]
}

...

resource "aws_ssoadmin_permission_set_inline_policy" "example" {
  inline_policy      = data.aws_iam_policy_document.example.json
  instance_arn       = aws_ssoadmin_permission_set.example.instance_arn
  permission_set_arn = aws_ssoadmin_permission_set.example.arn
}

```

In this configuration, the `instance_arn` argument of the `aws_ssoadmin_permission_set_inline_policy` resource is referencing the `instance_arn` argument of the `aws_ssoadmin_permission_set`, whose value is `tolist(data.aws_ssoadmin_instances.example.arns)[0]`. This is [valid interpolation](https://www.terraform.io/language/expressions/references#references-to-resource-attributes), and is effectively the same thing as passing `tolist(data.aws_ssoadmin_instances.example.arns)[0]` directly to the `instance_arn` argument of the `aws_ssoadmin_permission_set_inline_policy` resource.
