### ISSUE TITLE
aws_s3_bucket_object_lock_configuration documentation bad or confusing

### ISSUE THREAD

**Issue by grimm26** [hashicorp/terraform-provider-aws#23363]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.2.0
```

### Affected Resource(s)

* aws_s3_bucket_object_lock_configuration
* aws_s3_bucket

#### aws_s3_bucket documentation
- The [object_lock_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#object_lock_configuration) documentation shows that object locks are enabled in this resource but the configuration of the object locking takes place in the `aws_s3_bucket_object_lock_configuration` resource. 
 
#### aws_s3_bucket_object_lock_configuration documentation
-  references a `token` argument that is not really explained or given as an example. A link to the API doc that mentions it would be nice.
- lists [object_lock_enabled](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_object_lock_configuration#object_lock_enabled) as a parameter, but the example shows that that is part of the `aws_s3_bucket` resource. Do we enable locking both here and in aws_s3_bucket?

Some clarification is required as to what portion of the object locking configuration goes with what resource.

**Comment by anGie44** [comment]
Thank you for reporting this issue @grimm26 . 

I'll add to the documentation in an upcoming PR to clarify. 

My understanding is that if you are creating a new S3 bucket and want to configure object lock settings, 

(1) set `object_lock_configuration.object_lock_enabled = "Enabled"` in the `aws_s3_bucket` resource

(2) create the `aws_s3_bucket_object_lock_configuration` resource with the settings you would like, with no need to specify `object_lock_enabled` as it already defaults to `Enabled` and that is the only valid value.

If you already have an existing s3 bucket, and this includes buckets that are created on the same `terraform apply` as the `aws_s3_bucket_object_lock_configuration` resource , then you must contact AWS support as noted in the docs. It's not clear if AWS Support gives you a `token` though 😅 , but that is my assumption by looking at the SDK docs https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#PutObjectLockConfigurationInput . I'll look around some more in the AWS S3 User guide.
