### ISSUE TITLE
aws_cloudformation_stack_set SERVICE_MANAGED apply error on a delegated administrator account

### ISSUE THREAD

**Issue by sburgosl** [hashicorp/terraform-provider-aws#23378]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.5
+ provider registry.terraform.io/hashicorp/aws v4.2.0

### Affected Resource(s)

* aws_cloudformation_stack_set

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_cloudformation_stack_set" "example" {
  name             = "example-stackset"
  permission_model = "SERVICE_MANAGED"
  call_as          = "DELEGATED_ADMIN"
}
```

### Expected Behavior

The resource is created and terraform apply ends successfully.

### Actual Behavior

The resource is created, but terraform apply fails.
It seems that the function that search the StackSet is not adding the --call-as option.

```
aws_cloudformation_stack_set.example: Creating...
╷
│ Error: error reading CloudFormation StackSet (example-stackset): couldn't find resource
│
│   with aws_cloudformation_stack_set.example,
│   on stackset.tf line 1, in resource "aws_cloudformation_stack_set" "example":
│    1: resource "aws_cloudformation_stack_set" "example" {
│
╵
```
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Service Managed Stackset in a delegated administrator account.

### References

* Function that searches for the stackset: https://github.com/hashicorp/terraform-provider-aws/blob/ad87be9505e25889a1392681906d57b22e6ad648/internal/service/cloudformation/find.go#L148
* AWS CLI reference: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/describe-stack-set.html 
* The call-as support was added in #19736 #22440

**Comment by albertorm95** [comment]
Hey @sburgosl We are already working in that fix! 

- https://github.com/hashicorp/terraform-provider-aws/pull/23339

**Comment by Galvin-wjw** [comment]
Hi @albertorm95 

I still have the same problem as this issue.

**Version**:
- Terraform v1.1.5
- provider registry.terraform.io/hashicorp/aws v4.2.0

```
│ Error: error reading CloudFormation StackSet (BaseRole): couldn't find resource
│ 
│   with module.cfn_stacksets_roles.aws_cloudformation_stack_set.deploy_operation_role,
│   on modules/cfn-stacksets-init/main.tf line 5, in resource "aws_cloudformation_stack_set" "deploy_operation_role":
│    5: resource "aws_cloudformation_stack_set" "deploy_operation_role" {
```
Hi @sburgosl , Have you solved your issue?
