### ISSUE TITLE
aws_cognito_user_pool_client supported identity should reference Cognito User Pool

### ISSUE THREAD

**Issue by hfiorillo** [hashicorp/terraform-provider-aws#23374]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi team,

The documentation example for aws_cognito_user_pool_client [supported_identity_providers](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool_client#supported_identity_providers) could do with a reference / example of setting '`supported_identity_providers = ["COGNITO"]`' when using Cognito User Pool as the identity provider. Without this value being set, the app client will not have an identity provider and the hosted UI will not be available by default despite having a domain resource. This process will save users from having to manually update the app client in the console to reference the Cognito User Pool which is available in the drop down menu.

I couldn't find any references in the documentation to the setting so thought it would be a nice addition.

### New or Affected Resource(s)

- aws_cognito_user_pool_client

**Comment by justinretzolk** [comment]
Hey @hfiorillo 👋 Thank you for taking the time to raise this! It sounds like having an example of this in addition to the current examples could be beneficial. I'm not personally familiar with Cognito; do you happen to have an example of what this might look like readily available? If not, I'm happy to dig into it and work on a documentation update, but figured it was worth asking!

**Comment by hfiorillo** [comment]
Hello @justinretzolk 👋🏼  Thats great, I'm happy to help. 

Let me know if the example below is of any use!

```hcl
resource "aws_cognito_user_pool_client" "userpool_client" {
  name = var.name

  user_pool_id                         = aws_cognito_user_pool.userpool.id
  callback_urls                        = var.callback_urls
  allowed_oauth_flows_user_pool_client = var.allowed_oauth_flows_user_pool_client
  allowed_oauth_flows                  = var.allowed_oauth_flows
  allowed_oauth_scopes                 = var.allowed_oauth_scopes
  supported_identity_providers         = ["COGNITO"]
}

```

**Comment by justinretzolk** [comment]
Hey @hfiorillo 👋 Thanks for that! I'm going to spend a bit of time familiarizing myself with Cognito a bit more before making this PR so that I can make sure to do it justice. I'll make sure to update you here when I get the PR opened, in case you'd like to take a look.

**Comment by justinretzolk** [comment]
Hey @hfiorillo 👋 Thank you for your patience while I worked on prioritizing finding the time to dive deeper into Cognito 🙂. I've opened a PR to add an example to the documentation (#24230), and wanted to touch base with you, as promised. If you happen to have the time to share any thoughts on the suggested changes, I'd love to hear them!
