### ISSUE TITLE
Question: Why dose terraform recreate aws_ecs_task_definition every time even if there is no change in state

### ISSUE THREAD

**Issue by Rishang** [hashicorp/terraform-provider-aws#23379]
Every time i perform terrafrom apply for ecs fargate service, aws_ecs_task_definition registers a new task defination every time. it feels wierd why even if there is no change in state of entire it updates the task defination.

**Comment by justinretzolk** [comment]
Hey @Rishang 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to investigate this, can you update the issue description with the rest of the information found in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?

**Comment by vitalykarasik** [comment]
I'm now 100% sure that it's the same issue, but seems really similar (I just asked in forum https://discuss.hashicorp.com/t/question-or-bug-terraform-false-drift-detection-in-task-definition-version/36559):

Really weird thing: “Terraform plan” reports drift for all task definitions, for instance:

~ task_definition = "arn:aws:ecs:us-east-1:xxxxxxxx:task-definition/my-service:4" -> "arn:aws:ecs:us-east-1:xxxxxxxx:task-definition/my-service:3"
I.e. Terrafrom wants to deploy the previous version of my task. But - both in the ECS cluster and in the Terrafrom state JSON I see the 4th version of my task definition. And obviously “3” isn’t hardcoded (version number is different for each service).

**Comment by Rishang** [comment]
Looks like it been fixed in latest provider relese

**Comment by justinretzolk** [comment]
Thanks for the update @Rishang 👍 @vitalykarasik -- are you seeing the same, that this was fixed in the most recent release?

**Comment by vitalykarasik** [comment]
@justinretzolk  - sorry for delay. Yes, it seems OK now, many thanks!
Vitaly

**Comment by justinretzolk** [comment]
Thanks for letting me know! With that in mind, I'll mark this as closed. If anyone runs into this again in the future, please open a new issue to report.
