### ISSUE TITLE
aws_imagebuilder_image container support

### ISSUE THREAD

**Issue by josjaf** [hashicorp/terraform-provider-aws#23380]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Can we get this to support container images? We can pass in this parameter container_recipe_arn
### New or Affected Resource(s)
Either allow for the container_recipe_arn parameter or make a new resource aws_imagebuilder_container_image

* aws_imagebuilder_image

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by kamilturek** [comment]
I'll take care of that.

**Comment by kamilturek** [comment]
Getting close, stay tuned! 😅

**Comment by josjaf** [comment]
Awesome, thank you!
