### ISSUE TITLE
aws_lb_target_group support IPv6 target groups

### ISSUE THREAD

**Issue by tophercullen** [hashicorp/terraform-provider-aws#23386]
### Description

Target groups can support either ipv4 or ipv6 via the `IpAddressType` attribute. If unspecified, which appears to be the case with the provider, it defaults to ipv4. 

### New or Affected Resource(s)

* aws_lb_target_group

### Potential Terraform Configuration

```hcl
resource "aws_lb_target_group" "ip-example" {
  name        = "tf-example-lb-tg"
  port        = 80
  protocol    = "HTTP"
  target_type = "ip"
  ipaddress_type = "ipv6"
  vpc_id      = aws_vpc.main.id
}
```

### References

* https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateTargetGroup.html

**Comment by Iced-Sun** [comment]
It seems the PR #21973 has a fix for this issue, yet to merge.

**Comment by yann-soubeyrand** [comment]
Hello, it’s been implemented in https://github.com/hashicorp/terraform-provider-aws/pull/26320.
