### ISSUE TITLE
Add a way to assign a cognito user to a group

### ISSUE THREAD

**Issue by tooxie** [hashicorp/terraform-provider-aws#23400]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There should be a way to include a user in a group, for example:

```tf
resource "aws_cognito_user" "root" {
  user_pool_id = aws_cognito_user_pool.users.id
  username = "RootUser"
  password = random_password.root_user_password.result

  # This is the missing part
  groups = [
    aws_cognito_user_group.admin_users.arn
  ]
}

resource "aws_cognito_user_group" "admin_users" {
  name = "AdminUsersGroup"
  user_pool_id = aws_cognito_user_pool.users.id
  description = "Admin users group"
  precedence = 10
  role_arn = aws_iam_role.cognito_admin_user.arn

  # Another option would be to list the users here:
  users = [
    aws_cognito_user.root.arn
  ]
}
```

Currently it is not possible to assign a user to a group with terraform. The closest one can get to a similar behavior is to create 2 different identity pools with distinct "authenticated" roles, but the application should then try to authenticate against all existing identity pools to figure out whether the user is admin or not.

### New or Affected Resource(s)

* `aws_cognito_user`
* `aws_cognito_user_group`

**Comment by danquack** [comment]
Is this the same as #23442?

**Comment by cemo** [comment]
Another option would be:

```
aws_cognito_user_to_group user{
     username =  "string"
     group_name = "string"
     user_pool_id = "id"
}
```

I think this is probably easier since it seems the api is already in separated. 

https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminAddUserToGroup.html
