### ISSUE TITLE
aws_api_gateway_integration imposes limit on timeout_milliseconds

### ISSUE THREAD

**Issue by bret-peterson** [hashicorp/terraform-provider-aws#23417]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I need Terraform to not block me from setting a value higher than the standard default output. This was implemented in v2 gateways - can this be ported to the REST version as well? See https://github.com/hashicorp/terraform-provider-aws/pull/16017

A warning would be fine - the AWS CLI allows this without any messaging.

### New or Affected Resource(s)

* aws_api_gateway_integration 

### Potential Terraform Configuration

```hcl
resource "aws_api_gateway_integration" "lambda" {
  rest_api_id             = aws_api_gateway_rest_api.XXX.id
  resource_id             = aws_api_gateway_resource.proxy.id
  http_method             = aws_api_gateway_method.proxy.http_method
  integration_http_method = "POST"
  type                    = "AWS_PROXY"
  uri                     = aws_lambda_function.XXX.invoke_arn
  timeout_milliseconds    = 60000
}
```

**Comment by bret-peterson** [comment]
So... not going to remove the restriction?

**Comment by chainchad** [comment]
Looks like AWS bumped the hard limit from 29 seconds on REST API Gateways. See the [post](https://aws.amazon.com/about-aws/whats-new/2024/06/amazon-api-gateway-integration-timeout-limit-29-seconds/) and [docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html#api-gateway-execution-service-limits-table).
