### ISSUE TITLE
.net 6.0 support

### ISSUE THREAD

**Issue by SamuelCox** [hashicorp/terraform-provider-aws#23415]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Native support for .net 6.0 as a lambda runtime. This is already done by a dependabot PR, it just needs to be merged:
https://github.com/hashicorp/terraform-provider-aws/pull/23405
I suspect as its a dependabot pr it's not getting the attention it normally would.

### New or Affected Resource(s)

* aws_lambda_function

### Potential Terraform Configuration

```hcl
resource "aws_lambda_function" "lambda" {
runtime          = "dotnet6.0"
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2022/02/aws-lambda-adds-support-net6/).

**Comment by PhbsSmn** [comment]
I guess its comming?
https://github.com/hashicorp/terraform-provider-aws/pull/23422

**Comment by JT-Bruch** [comment]
@ewbankkit Is it possible for this to be added to the v3 of the provider? I am dependent on https://github.com/milliHQ/terraform-aws-next-js/issues/286 being updated before I can upgrade?
