### ISSUE TITLE
No tags enabled in the following AWS registry-modules

### ISSUE THREAD

**Issue by sandeepgopi** [hashicorp/terraform-provider-aws#23428]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

We find that tags are not enabled in the below repos. Hence we are unable to track and audit AWS resources generated in our environment when calling them in our custom terraform modules. Please can the below to tag enabled. Or if you like I can enable them and raise a PR. Thank you!
* terraform-aws-cloudwatch-logs
Resource - aws_cloudwatch_log_group
Resource Name- default

* terraform-aws-config: 
Resource - aws_config_configuration_aggregato
Resource Name-  this
Resource - aws_config_aggregate_authorization
Resource Name- child
Resource - aws_config_aggregate_authorization
Resource Name-  central

* terraform-aws-eventbridge
Resource - aws_cloudwatch_event_target
Resource Name-  this

* terraform-aws-lambda → modules -> docker-build
Resource - aws_ecr_repository
Resource Name-  this

* terraform-aws-step-functions
Resource - aws_iam_policy
Resource Name-  service
Resource - aws_iam_policy
Resource Name-  additional_json
Resource - aws_iam_policy
Resource Name-  additional_jsons
Resource - aws_iam_policy
Resource Name-  additional_inline
Resource - aws_iam_policy
Resource Name-  logs

* terraform-aws-vpc
Resource -  aws_elasticache_subnet_group
Resource Name- elasticache

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @sandeepgopi 👋 It looks like you might be referencing some modules, perhaps from the Terraform Registry, is that correct? You'll need to file an issue against the repository for each of the modules if that's the case, so that the module author can add tags to the resources.

**Comment by sandeepgopi** [comment]
Hey Justin. Hope you are doing well. Thank you for your update. Yes I am referencing modules on Github. Shall follow uo with the relevant author of that repo to request tag enablement. Regards :)

**Comment by justinretzolk** [comment]
Hey @sandeepgopi 👋 I hope you're well as well, and thank you for the follow up! With that in mind, I'll close this issue out. If you feel I've done this in error, or have follow up questions, please do let me know!
