### ISSUE TITLE
Documentation missing for import ID of `aws_s3_bucket_versioning` and related resources

### ISSUE THREAD

**Issue by jbg** [hashicorp/terraform-provider-aws#23420]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_s3_bucket_versioning
* aws_s3_bucket_lifecycle_configuration
* aws_s3_bucket_server_side_encryption_configuration
* (perhaps other similar resources too)

### Documentation bug

The documentation for `aws_s3_bucket_versioning` says:

```
S3 bucket versioning can be imported using the bucket and expected_bucket_owner separated by a comma (,), e.g.
$ terraform import aws_s3_bucket_versioning.example bucket-name,123456789012
```

and the other similar resources have similar text.

In fact, when the `expected_bucket_owner` attribute is not set, the resource should be imported using only the bucket name, e.g.

```
$ terraform import aws_s3_bucket_versioning.example bucket-name
```

**Comment by anGie44** [comment]
Hi @jbg , thank you for raising this issue. In general, these `aws_s3_bucket_*` resources can be imported with just the `bucket` value as seen in the documentation examples when `expected_bucket_owner` does not differ from the AWS account ID that the Terraform AWS Provider is configured with. Is there additional clarification you think would be helpful when deciding which import syntax to use?

**Comment by jbg** [comment]
Sorry if I wasn't clear in the issue description. The problem is exactly that the documentation does not mention what you just wrote. It only mentions the `bucket-name,account-id` syntax when in fact if `expected_bucket_owner` is not being used (i.e. the owner is the same as the provider account), the syntax is just `bucket-name`. It's not so much that it needs clarifying, it's just missing from the docs entirely.

**Comment by anGie44** [comment]
I see! yep that's a good point. We can certainly add a note to all the affected resources 👍
