### ISSUE TITLE
origin_keepalive_timeout is restricted to 180 seconds for aws_cloudfront_distribution resource

### ISSUE THREAD

**Issue by Brianpro** [hashicorp/terraform-provider-aws#23437]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

* Terraform v1.1.6
* provider registry.terraform.io/hashicorp/aws v4.2.0

### Affected Resource(s)

* aws_cloudfront_distribution

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```terraform
resource "aws_cloudfront_distribution" "site" {
  origin {
    domain_name = var.domain-name
    origin_id   = "${var.origin-id-prefix}-${var.domain-name}"

    custom_origin_config {
      http_port  = 80
      https_port = 443

      origin_protocol_policy   = "https-only"
      origin_keepalive_timeout = 600
      origin_read_timeout      = 31

      origin_ssl_protocols = ["TLSv1.2"] # TLS 1.2 is required for PCI compliance
    }
```
### Debug Output

```
Error: expected origin.0.custom_origin_config.0.origin_keepalive_timeout to be in the range (1 - 180), got [600]
 
  with module.cdn-site.aws_cloudfront_distribution.site,
  on ../../../modules/cdn/site/site.tf line 33, in resource "aws_cloudfront_distribution" "site":
  33: resource "aws_cloudfront_distribution" "site" {
```

### Expected Behavior

We should be able to allow any value for origin_keepalive_timeout. It's up to AWS to restrict really high values not terraform since you can negotiate with AWS to allow high values in certain cases.  

### Actual Behavior

Error running terraform plan only allowing a max value of 180.

### Steps to Reproduce

Set origin_keepalive_timeout to something higher then 180 seconds. 

1. `terraform apply`

### References
Reference to code. 
* https://github.com/hashicorp/terraform-provider-aws/blob/ad87be9505e25889a1392681906d57b22e6ad648/internal/service/cloudfront/distribution.go#L543

**Comment by justinretzolk** [comment]
Hey @Brianpro 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include the rest of the information from the [bug template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?

**Comment by Brianpro** [comment]
> 

Done. Thanks
