### ISSUE TITLE
Unable to create s3 backend

### ISSUE THREAD

**Issue by asksmruti** [hashicorp/terraform-provider-aws#23439]
Hello,

I am running the following command to create S3 backend however on terraform/aws version 4.x.x, I am getting below error,
and it works fine on 3.x.x 

```
terraform init -backend-config="bucket=<ACCOUNTID>-eu-west-2-tfstate" -backend-config="region=eu-west-2" -backend-config="key=terraform-abc-eu-west-2.tfstate" -backend-config="profile=temp_abc" -backend=true -force-copy -get=true -input=false
```

**ERROR**

```
Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Error: Failed to get existing workspaces: S3 bucket does not exist.

The referenced S3 bucket must have been previously created. If the S3 bucket
was created within the last minute, please wait for a minute or two and try
again.

Error: NoSuchBucket: The specified bucket does not exist
        status code: 404, request id: QQMFP5XR6N8F2EW5, host id: B4D+crOg2V95BAsckjko1nlkwnBKIaCd9DkP4/nDLxNH/v3luTYnlo9TDhaJZoFzFBsPe7FxXU=

```
Same command work when required provider version set to 3.x.x

```
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.74.3”    <<==== init work fine 
    }
  }
}
```

```
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = “4.x.x”    <<==== init command fail with above error
    }
  }
}
```
NOTE: This issue is same as https://github.com/hashicorp/terraform/issues/30406

**Comment by justinretzolk** [comment]
Hey @asksmruti 👋 Thank you for taking the time to raise this, and for bringing the issue over here from the Terraform Core repo! I did a bit of testing and so far haven't been able to reproduce this. I'll outline what I did below, in case there's anything I'm missing.

Initially, I created an S3 bucket (I tested in `us-east-1`, `eu-west-1`, and `eu-west-2` to try to make sure it wasn't a locality issue) using the following configuration (note: this is intentionally pretty basic, and so auth and region information was set elsewhere):

```hcl
resource "aws_s3_bucket" "state" {
  bucket = "jretzolk-test-bucket-eu-west-2-23439"
}
```

After creating the bucket, I then tested a `terraform init` using the following configuration:

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.0.0"
    }
  }

  backend "s3" {
    bucket  = "jretzolk-test-bucket-eu-west-2-23439"
    region  = "eu-west-2"
    key     = "eu-west-2-terraform.tfstate"
    profile = "<REDACTED>"
  }
}
```

When running the init, I received the expected output:

```shell
> terraform init

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/aws versions matching "4.0.0"...
- Installing hashicorp/aws v4.0.0...
- Installed hashicorp/aws v4.0.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

There are a few questions that come to mind that I'd be interested in:

- Are you running Terraform via the CLI, or in something like a CI/CD tool, which may run Terraform in a container?
- Using the same profile that you've configured in your Terraform configuration, are you able to run AWS CLI commands against the bucket? For example an `aws s3 ls`, or similar?
- I noticed in your CLI arguments, you passed the bucket name as `<ACCOUNTID>-eu-west-2-tfstate` -- does the bucket actually have the account ID prepended, or was that added for another reason?

**Comment by gdavison** [comment]
@asksmruti are you using any environment variables, such as `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`? Starting with version 4 of the AWS provider, the precedence rules for configuration has changed, while the precedence rules for the S3 remote state backend have not.

The provider now follows the default behaviour used by the AWS CLI and AWS SDKs. The S3 backend prioritizes the environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
