### ISSUE TITLE
Add aws_cognito_user_to_group 

### ISSUE THREAD

**Issue by cemo** [hashicorp/terraform-provider-aws#23442]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

#19919 is merged but group feature seems missing.

### Potential Terraform Configuration

```hcl
aws_cognito_user_to_group user{
     username =  "string"
     group_name = "string"
     user_pool_id = "id"
}
```

### References

- https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminAddUserToGroup.html

**Comment by danquack** [comment]
Is this the same as #23400?

**Comment by tooxie** [comment]
Yes, it seems to be a duplicate. @cemo would you mind closing this issue and giving a 👍 on #23400? Thanks!
