### ISSUE TITLE
Get Organisation Unit from Account ID

### ISSUE THREAD

**Issue by YuriGal** [hashicorp/terraform-provider-aws#23468]
Not sure if this is a feature request or something like this exists already:

In terraform is there a way (data source etc.) to extract Organization Unit (OU) from ID of the account that belongs to that OU?

I can extract various pieces of information from
```
data "aws_caller_identity" "current" {}
```
or
```
data "aws_iam_session_context" "current" {}
```
But no OU.

**Comment by justinretzolk** [comment]
Hey @YuriGal 👋 Typically questions like this are best served by opening a new topic on the [AWS Provider Discuss forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33). That said, I took a look around, and if I'm understanding the documentation correctly, I believe you can accomplish this by using the [`aws_organizations_organization` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/organizations_organization) paired with the [`aws_organizations_organizational_unit` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/organizations_organizational_unit). Unfortunately I don't currently have an easy way of testing this, so I hope that helps some!

**Comment by YuriGal** [comment]
@justinretzolk  Thanks for the reply! I had checked those, but from what I understand they won't be enough in this use-case. I will experiment more though and ask on the forum, like you suggested.

**Comment by justinretzolk** [comment]
Sounds good! With that in mind, I'll close this issue for now. If you aren't able to get the information you need from those sources, feel free to come back and open an issue using our feature request template, and we'll gladly look into it 🙂.
