### ISSUE TITLE
 AWS_connect_instance Issue

### ISSUE THREAD

**Issue by ramankaur172** [hashicorp/terraform-provider-aws#23461]
Hi Team,

I am trying   to create the AWS_connect_instance  via TFE workspace in “EU-WEST-2”  i.e London  region  and I am getting the error: Dead line exceeded  occurred. However the same set of code ran successfully in “EU-CENTRAL-1”
i.e.  Frankfurt region .  is there any Firewalls or some config setting on AWS specific region or something related to TFE workspace [aws-recp-connect-tyl-test](https://prod-tfe.web.rbsgrp.net/app/CTO/workspaces/aws-recp-connect-tyl-test) which needs to be fix .

**Comment by justinretzolk** [comment]
Hey @ramankaur172 👋 Thanks for taking the time to raise this! If you suspect that this is an issue with firewalls affecting your TFE installation, you'll need to work with whoever is managing your TFE installation (likely someone within your organization). If you think this might be an issue with the AWS Provider itself, can you update the issue to include the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?
