### ISSUE TITLE
aws_rds_cluster add new multi-AZ cluster deployment options

### ISSUE THREAD

**Issue by cdobbyn** [hashicorp/terraform-provider-aws#23475]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Add the ability to provision Multi-AZ cluster deployment MySQL or PostgreSQL instances.

It looks like aws-sdk-go added this in `1.43.9`.

```
To create a Multi-AZ DB cluster by using the RDS API, call the [CreateDBCluster](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBCluster.html) operation. Specify the DBClusterIdentifier. For the Engine parameter, specify either mysql or postgresql.
```

### New or Affected Resource(s)

aws_rds_cluster

### Potential Terraform Configuration

```hcl
resource "aws_rds_cluster" "asdf" {
  # ....
  engine = "postgres"
  # ....
}
```

### References
* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/create-multi-az-db-cluster.html
* https://aws.amazon.com/blogs/aws/amazon-rds-multi-az-db-cluster/
* https://github.com/aws/aws-sdk-go/commit/4adef3588ff234c55aa0afb9cb33772660906758

**Comment by bschaatsbergen** [comment]
Picking this uo

**Comment by bschaatsbergen** [comment]
Hmm there's a few other parameters to be added, AllocatedStorage, Iops and StorageTypeId

**Comment by bschaatsbergen** [comment]
Next to the `postgres` and `mysql` engine compatibility that's required to add, we also need to add the following attributes:

`storage_type`, `allocated_storage`, `iops` and `db_cluster_instance_class`.
