### ISSUE TITLE
Issue with aws_s3_bucket_logging resource if target_bucket value set to S3 arn

### ISSUE THREAD

**Issue by alkeshdagade** [hashicorp/terraform-provider-aws#23498]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
* AWS Provider version: 4.3.0
### Affected Resource(s)

* aws_s3_bucket_logging

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket_logging" "test_bucket_logging" {
  bucket = aws_s3_bucket.test_bucket.id

  target_bucket = arn:aws:s3:::my-test125-for-logging
  target_prefix = "log/"
}
```

### Debug Output
Error: error putting S3 bucket (dev-test125-us-east-1) logging: InvalidTargetBucketForLogging: The target bucket for logging does not exist
│ 	status code: 400, request id: FMWDYQTTTTTK7T, host id: XXXXX/XXXXXXXXXXXXXXXXXXrkyXXXXXX/YYYYY=
│ 
│   with module.s3.aws_s3_bucket_logging.test_bucket_logging,
│   on ../modules/s3/main.tf line 33, in resource "aws_s3_bucket_logging" "test_bucket_logging":
│   33: resource "aws_s3_bucket_logging" "test_bucket_logging" {

### Expected Behavior
- If  target_bucket value is set to arn then resource should be created without any issue.

### Actual Behavior

- If  target_bucket value is set to arn then terraform execution is failing with error target bucket doesn't exist although its exist. 

Note: If I set target bucket value as id then its working fine for same target bucket for which arn was set. 

### Steps to Reproduce

1. `terraform apply`

**Comment by anGie44** [comment]
Hi @alkeshdagade, thank you for raising this issue. I believe only the bucket name (`bucket` or `id` argument in `aws_s3_bucket`) works for `target-bucket` in this resource. The examples in the registry docs use `id` for example but we can clarify this in the argument documentation.

**Comment by alkeshdagade** [comment]
@anGie44 thanks for your quick response. I would like to store logs in S3 bucket created in different account hence looking for arn.

**Comment by anGie44** [comment]
Oh i see @alkeshdagade . In that case it looks like using Cloudtrail instead of S3 maybe the way to go since it appears cross-account log-delivery is only supported there : https://docs.aws.amazon.com/AmazonS3/latest/userguide/logging-with-S3.html

**Comment by alkeshdagade** [comment]
@anGie44 thanks for the clarification, closing the ticket.

Thanks once again for your quick response.
