### ISSUE TITLE
aws_cloudwatch_event_rule Event Pattern < or > Created as Unicode e.g. "\u003e"

### ISSUE THREAD

**Issue by stewartcampbell** [hashicorp/terraform-provider-aws#23496]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.2.0
```

### Affected Resource(s)

```
aws_cloudwatch_event_rule
```

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_cloudwatch_event_rule" "ecs" {
  name          = "test-ecs-event"
  is_enabled    = false
  event_pattern = <<EOF
{
  "detail-type": [
    "ECS Task State Change"
  ],
  "detail": {
    "containers": {
      "exitCode": [
        { "numeric": [ ">", 0 ] }
      ]
    }
  }
}
EOF
}
```

### Expected Behavior

EventBridge pattern created like
```
{
  "detail": {
    "containers": {
      "exitCode": [{
        "numeric": [">", 0]
      }]
    }
  },
  "detail-type": ["ECS Task State Change"]
}
```

### Actual behaviour

EventBridge pattern created like
```
{
  "detail": {
    "containers": {
      "exitCode": [{
        "numeric": ["\u003e", 0]
      }]
    }
  },
  "detail-type": ["ECS Task State Change"]
}
```

### Steps to Reproduce

1. `terraform apply`

### References

The only reference I can find is an old Pulumi issue at https://github.com/pulumi/pulumi-aws/issues/1009

**Comment by kikyomits** [comment]
I encountered this issue as well. I guess this is related to this issue https://github.com/hashicorp/terraform/issues/26110
