### ISSUE TITLE
Modifying an `aws_amplify_app`'s repository attribute unnecessarily forces the resource to be destroyed and recreated

### ISSUE THREAD

**Issue by mmourick** [hashicorp/terraform-provider-aws#23499]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_amplify_app

### Expected Behavior

The `aws_amplify_app` should be updated in place when modifying the `repository` attribute.

### Actual Behavior

Changing the `repository` attribute forces the entire resource to be recreated.

### Steps to Reproduce

1. Deploy an `aws_amplify_app` with the `repository` url set.
2. Change the `repository` attribute.
3. Run `terraform plan`
4. See that terraform wants to replace the existing app and create a new one.

### Important Factoids

The reason for wanting the repository url to be updated in place is to prevent downtime and potential loss of data.

The repository URL can successfully be updated using the AWS CLI:
`aws amplify update-app --app-id APP_ID --repository REPO_URL--access-token ACCESS_TOKEN`

### References

* #0000

**Comment by bschaatsbergen** [comment]
Good idea, it's a pain that the amplify app including it's downstream dependent services (e.g. DynamoDB) is being recreated..
