### ISSUE TITLE
Terraform errors for adding asterisk at beginning of the namesapce name in AWS cloudmap

### ISSUE THREAD

**Issue by srini-nangunuri** [hashicorp/terraform-provider-aws#23502]
I'm able to create a domain name under AWS cloudmap service manually without any issues (example: *.<subdomain>.<domain>.local), however Terraform code fails if i try to add asterisk (*) at the beginning of the namespace name. I tried to add an unicode for asterisk as "u002A" and "\*" but no luck. Any suggestions or bug fix is much appreciated. Thanks in advance.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @srini-nangunuri 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include the rest of the information requested in the template?
