### ISSUE TITLE
Use one aws_cloudwatch_event_target for multiple aws_cloudwatch_event_rule - same like "aws events put-targets"

### ISSUE THREAD

**Issue by youwalther65** [hashicorp/terraform-provider-aws#23503]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

$ terraform -v
Terraform v1.1.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.3.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/http v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

### Affected Resource(s)

AWS proivder
resource aws_cloudwatch_event_target
resource aws_cloudwatch_event_rule

Following:
https://github.com/aws/aws-node-termination-handler#4-create-amazon-eventbridge-rules

I want to create multiple EventBridge rules which use the same SQS as a target target.
Using AWS CLI "aws events pu-targets" I can use the same target ID and SQS ARN fo rmultiple event rules. Using Terraform I get an error

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
$ cat nth-eventbridge.tf
resource "aws_cloudwatch_event_rule" "karpenter_nth_SpotTermRule" {
  count = var.enable_karpenter ? 1 : 0

  name        = "${local.name}-SpotTermRule"
  description = "Capture EC2 Spot Instance Interruption Warnings"

  event_pattern = <<-EOF
  {
    "source": ["aws.ec2"],
    "detail-type": ["EC2 Spot Instance Interruption Warning"]
  }
EOF
}

resource "aws_cloudwatch_event_target" "karpenter_nth_target1" {
  count = var.enable_karpenter ? 1 : 0

  rule      = aws_cloudwatch_event_rule.karpenter_nth_SpotTermRule[0].name
  target_id = "SendToSQS1"
  arn       = aws_sqs_queue.karpenter_nth_queue[0].arn
}

resource "aws_cloudwatch_event_rule" "karpenter_nth_RebalanceRule" {
  count = var.enable_karpenter ? 1 : 0

  name        = "${local.name}-SpotTermRule"
  description = "Capture EC2 Instance Rebalance Recommendations"

  event_pattern = <<-EOF
  {
    "source": ["aws.ec2"],
    "detail-type": ["EC2 Instance Rebalance Recommendation"]
  }
EOF
}

resource "aws_cloudwatch_event_target" "karpenter_nth_target2" {
  count = var.enable_karpenter ? 1 : 0

  rule      = aws_cloudwatch_event_rule.karpenter_nth_RebalanceRule[0].name
  target_id = "SendToSQS2"
  arn       = aws_sqs_queue.karpenter_nth_queue[0].arn
}

resource "aws_cloudwatch_event_rule" "karpenter_nth_InstanceStateChangeRule" {
  count = var.enable_karpenter ? 1 : 0

  name        = "${local.name}-SpotTermRule"
  description = "Capture EC2 Instance State-change Notifications"

  event_pattern = <<-EOF
  {
    "source": ["aws.ec2"],
    "detail-type": ["EC2 Instance State-change Notification"]
  }
EOF
}

resource "aws_cloudwatch_event_target" "karpenter_nth_target3" {
  count = var.enable_karpenter ? 1 : 0

  rule      = aws_cloudwatch_event_rule.karpenter_nth_InstanceStateChangeRule[0].name
  target_id = "SendToSQS3"
  arn       = aws_sqs_queue.karpenter_nth_queue[0].arn
}
```

### Expected Behavior

Using same target for multiple EventBridge rules

### Actual Behavior

error message
╷
│ Error: error creating EventBridge Rule (git-eks-demo-ipv4-SpotTermRule): ConcurrentModificationException: com.amazon.aws.platform.tagris.client.exception.TagrisClientException: A resource with the same resourceName but a different internalId already exists: 86bbb8d2-b6a5-39d6-5813-5474a616804d
│
│   with aws_cloudwatch_event_rule.karpenter_nth_RebalanceRule[0],
│   on nth-eventbridge.tf line 23, in resource "aws_cloudwatch_event_rule" "karpenter_nth_RebalanceRule":
│   23: resource "aws_cloudwatch_event_rule" "karpenter_nth_RebalanceRule" {
│

**Comment by justinretzolk** [comment]
Hey @youwalther65 👋 Thank you for taking the time to raise this! Based on the error logged, I suspect this is due to your having multiple `aws_cloudwatch_event_rule` resources that have the same value for the `name` argument. Can you try setting the `name` argument to a unique value and test to verify that resolves the issue?

**Comment by youwalther65** [comment]
Hey @justinretzolk thank you very much, appreciate your fast response AND resolution. Sorry for that - never codify in a call and have someone look at your code if you are not sure ;-) Issue solved, worked great , thx again
