### ISSUE TITLE
aws_appconfig_hosted_configuration_version can't use the profile created becasue the configuration profile id generated doesn't follow regular expression required

### ISSUE THREAD

**Issue by syz51** [hashicorp/terraform-provider-aws#23508]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.7
on windows_386
provider registry.terraform.io/hashicorp/aws v4.3.0

### Affected Resource(s)

* aws_appconfig_hosted_configuration_version
* aws_appconfig_configuration_profile

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_appconfig_application" "test" {
  name        = "test"
  description = "Appconfig application"
}

resource "aws_appconfig_configuration_profile" "shows" {
  application_id = aws_appconfig_application.test.id
  description    = "Configuration for the shows to fetch"
  name           = "shows-details-config"
  location_uri   = "hosted"
}

resource "aws_appconfig_hosted_configuration_version" "content" {
  application_id           = aws_appconfig_application.test.id
  configuration_profile_id = aws_appconfig_configuration_profile.shows.id
  content                  = jsonencode(file("${path.module}/config.json"))
  content_type             = "application/json"
  description              = "configuration file"
}
```

### Debug Output

https://gist.github.com/syz51/367ec920eecff2bbc3c65c6f0203a405

### Expected Behavior

create the hosted configuration version

### Actual Behavior

![image](https://user-images.githubusercontent.com/54097388/156818609-5b919041-05d8-44a6-967c-99889e92c992.png)

when the appconfig configuration profile is created, the id generated  doesn't seem to work because it doesn't follow the regular expression pattern required

### Steps to Reproduce

1. `terraform apply`

**Comment by justinretzolk** [comment]
Hey @syz51 👋 I took a quick look over the [documentation for `aws_appconfig_configuration_profile`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appconfig_configuration_profile) and think I may have figured this out. It looks like there's two separate attributes that are somewhat similar:

- `id`: The AppConfig configuration profile ID and application ID separated by a colon (`:`).
- `configuration_profile_id`: The configuration profile ID.

Based on that, it looks like your configuration would work if you updated `aws_appconfig_configuration_profile.shows.id` to `aws_appconfig_configuration_profile.shows.configuration_profile_id`.

**Comment by syz51** [comment]
Oh sry about that. I tried that and it seems to work. Thanks for your help!
