### ISSUE TITLE
'teraform apply' shows unexpected changes and throws error when optional parameter 'port' is not specified for aws_route53_health_check

### ISSUE THREAD

**Issue by adityadhole24** [hashicorp/terraform-provider-aws#23512]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.31
AWS Provider v3.70.0

### Affected Resource(s)

* aws_route53_health_check

### Terraform Configuration Files

```hcl
resource "aws_route53_health_check" "test" {

  fqdn = "www.some-valid-domain.com"
  type = "HTTP"
  request_interval = 30

}

```

### Debug Output

Gist for the 2nd `terraform apply` debug output - 
https://gist.github.com/adityadhole24/877b6aa15e0307b8b00f617a97975c77

### Expected Behavior

The first `terraform apply` command with the given configuration should lead to successful creation of the Route53 health check.
A second `terraform apply` command (*without* making any changes to the configuration externally of course), **should detect no changes**

### Actual Behavior

The behavior for the first 'terraform apply' command matches with the expected behavior. The health check is created successfully.

However, for the 2nd 'terraform apply' command, Terraform **(wrongly) detects a change** in the configuration - It detects that the value for 'port' has changed from null to 80 (default value that is configured by AWS for HTTP Health Checks), and **tries to force the value back** to null. 
![1](https://user-images.githubusercontent.com/51427819/156829929-9c44afdd-0677-436e-821e-63aa0c1fcade.png)

If this update-in-place is approved, Terraform fails with a validation error from AWS which states that a minimum value of 1 is required for the Port field. The error can be seen below -
![Inked2_LI](https://user-images.githubusercontent.com/51427819/156831102-5cc2633a-ec04-4def-a587-92af73399191.jpg)

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply` (without any modifications made to the configuration)

### Important Factoids

1. **Specifying a value for Port is optional when creating a Route53 Health Check of 'type' = HTTP/HTTPS through the AWS CLI as well**. A default value of 80/443 is configured by AWS for the parameter when creating Health Checks of type HTTP/HTTPS respectively. 

2. The same AWS-defaults are configured when the `port` parameter is skipped in Terraform and the resource gets created successfully in the 1st `terraform apply` command. However, the problem lies in the fact that Terraform **detects a change** in the subsequent `apply` (when there is no real change) and tries to **incorrectly revert it**, resulting in a error.

3. Note that specifying a 'port' value is mandatory for TCP Health Checks when creating through AWS CLI, and skipping it in Terraform for health checks of type = 'TCP' causes AWS to throw an error during resource-creation itself, which is expected and consistent with the CLI behavior. This issue pertains only to HTTP/HTTPS health checks.

### References

*  AWS CLI command 'create-health-check' reference - https://awscli.amazonaws.com/v2/documentation/api/latest/reference/route53/create-health-check.html

**Comment by adityadhole24** [comment]
@justinretzolk Any visibility on if/when this can be fixed?

**Comment by justinretzolk** [comment]
Hey  👋 Thank you for checking in on this. Unfortunately, I'm not able to provide an estimate on when this will be looked into due to the potential of shifting priorities. We prioritize work by count of ":+1:" reactions, as well as a few other things. A larger prioritization document is in the works, but in the meantime additional information may be found in our [issue lifecycle document](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/issue-reporting-and-lifecycle.md#issue-lifecycle).
