### ISSUE TITLE
Add dotnet6 runtime to the runtime list

### ISSUE THREAD

**Issue by dbraaten42** [hashicorp/terraform-provider-aws#23519]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS recently released .Net 6 Lambda support.  Runtime name is "dotnet6" I would like to publish my .Net 6 Lambdas using Terraform.

Currently getting this error

$ terraform plan
╷
│ Error: expected runtime to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x java8 java8.al2 java11 python2.7 python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2], got dotnet6

### New or Affected Resource(s)

resource "aws_lambda_function"

* aws_lambda_function

### Potential Terraform Configuration

runtime = "dotnet6"

From based on the HelloWorld example
```hcl
resource "aws_lambda_function" "hello_world" {
  function_name = "HelloWorld"

  s3_bucket = aws_s3_bucket.lambda_bucket.id
  s3_key    = aws_s3_object.lambda_hello_world.key

  runtime = "dotnet6"
  handler = "hello.handler"

  source_code_hash = data.archive_file.lambda_hello_world.output_base64sha256

  role = aws_iam_role.lambda_exec.arn
}
```

### References
https://aws.amazon.com/blogs/compute/introducing-the-net-6-runtime-for-aws-lambda/ 

* #0000

**Comment by bschaatsbergen** [comment]
I'll happily pick this up as fast as possible.
