### ISSUE TITLE
Can't set an `aws_eip` name with Terraform

### ISSUE THREAD

**Issue by chriskuech** [hashicorp/terraform-provider-aws#23529]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

1.1.7

### Affected Resource(s)

* aws_eip

### Terraform Configuration Files

N/A (problem with schema, not implementation)

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Schema should allow setting the name (or name prefix) of an Elastic IP, just as the Name can be set in the AWS Console
<img width="423" alt="image" src="https://user-images.githubusercontent.com/3680671/156897994-046ccab7-c9ec-4cbf-b5a2-260f0b292628.png">

### Actual Behavior

The schema for `aws_eip` does not support a `name` or `name_prefix` property.

### Steps to Reproduce

N/A

### Important Factoids

N/A

### References

N/A

**Comment by bschaatsbergen** [comment]
Set a 'Name' as part of the tags.

resource "aws_eip" "example" {
  # ... other configuration ...

  tags = {
    Name = "MyVPC"
  }
}
```

**Comment by gdavison** [comment]
Hi @chriskuech, thanks for submitting this issue.

When designing resources for the AWS Provider, we [follow the AWS API closely](https://www.terraform.io/plugin/hashicorp-provider-design-principles#resource-and-attribute-schema-should-closely-match-the-underlying-api). As @bschaatsbergen notes above, the name for an EIP (and most EC2 resources) is set using the `Name` tag.

**Comment by chriskuech** [comment]
Thank you @bschaatsbergen and @gdavison .  Does this seem weird for AWS to use tags in this manner compared to the rest of its API?  If not, do you see any consistency for when I can expect tags to be used in this manner?

**Comment by gdavison** [comment]
@chriskuech, most EC2 resources use the `Name` tag for the resource name. Other AWS services have an explicit name parameter.
