### ISSUE TITLE
aws_lb_listener_rule - cannot create forward rule to one target with target group stickiness

### ISSUE THREAD

**Issue by Zuroslaw** [hashicorp/terraform-provider-aws#23537]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.4
on linux_amd64
provider registry.terraform.io/hashicorp/aws v4.4.0

### Affected Resource(s)

* aws_lb_listener_rule

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_lb" "load_balancer" {
  name = "lb"
  internal = false
  load_balancer_type = "application"

  # ...security groups & subnets omitted...
}

resource "aws_lb_listener" "lb_listener_https" {
  load_balancer_arn = aws_lb.load_balancer.arn
  port = 443
  protocol = "HTTPS"

  default_action {
    type = "forward"
    target_group_arn = aws_lb_target_group.front_target_group.arn
  }

  # ... certificate arn omitted...
}

resource "aws_lb_listener_rule" "lb_rule_api" {
  listener_arn = aws_lb_listener.lb_listener_https.arn

  condition {
    host_header {
      values = ["api.example.com"]
    }
  }

  action {
    type = "forward"
    # adding here "target_group_arn" field does not change anything
    forward {
      stickiness {
        enabled = true
        duration = 8 * 60 * 60
      }
      target_group {
        arn = aws_lb_target_group.api_target_group.arn
      }
    }
  }
}
```

### Expected Behavior

After `terraform apply` Terraform should create an ALB rule that forwards requests to api_target_group with target group stickiness set to 8 hours. This is possible to do in AWS Console.

### Actual Behavior

An error occurs:

```
│ Error: Insufficient target_group blocks
│ 
│   on alb.tf line 100, in resource "aws_lb_listener_rule" "lb_rule_api_ws":
│  100:     forward {
│ 
│ At least 2 "target_group" blocks are required.
```
indicating that forward block should have at least 2 target_group blocks. As documented in aws provider docs, when we want only one target group we should use "target_group_arn" argument, however in that case it is not possible, without "forward" block, to add group level stickiness.

### Steps to Reproduce

1. `terraform apply`

**Comment by rirze** [comment]
This issue is more general:

Specifying only one target group even without stickiness throws this error. 

In my case, the Terraform in JSON looks like this:
```json
"app-external-443-https-proxy-forward": {
        "action": [
          {
            "forward": {
              "target_group": [
                {
                  "arn": "${aws_lb_target_group.external_app.arn}"
                }
              ]
            },
            "type": "forward"
          }
        ],
        "condition": [
          {
            "host_header": {
              "values": [
                "some_url"
              ]
            }
          }
        ],
        "listener_arn": "${aws_lb_listener.app-external-443-https.arn}",
        "priority": 1
      }


```

**Comment by rirze** [comment]
Welp, turns out it's pointed out earlier here https://github.com/hashicorp/terraform-provider-aws/issues/13636
No resolution yet there.

**Comment by biagolini** [comment]
I faced the same issue, and I found that documentation may leading you to this confusion (see: https://github.com/hashicorp/terraform-provider-aws/issues/31712)

You soul try somthing like:
```
resource "aws_lb_listener_rule" "lb_rule_api" {
  listener_arn = aws_lb_listener.lb_listener_https.arn
  action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.api_target_group.arn
  }
  condition {
    host_header {
      values = ["api.example.com"]
    }
  }
}
```

**Comment by supervirginia** [comment]
I can confirm that this issue is still open in:
Terraform v1.5.6
+ provider registry.terraform.io/hashicorp/aws v5.15.0

Although the [AWS terraform provider documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_rule#stickiness) states:
![image](https://github.com/hashicorp/terraform-provider-aws/assets/16543028/6d0f52d4-88f2-4266-be4c-57fcc0673f55)

I can change the stickiness value for a rule in the AWS console manually and this change is also not recognized by terraform. 
Please prioritize this inconsistency!
Thanks in advance.
Br, Virginia

**Comment by bmaluff** [comment]
Facing the same issue here! Any workaround?

**Comment by LucStr** [comment]
This issue has been resolve together with #13636 I believe this can be closed
