### ISSUE TITLE
Add a `skip_destroy` parameter to `aws_lambda_layer_version_permission`

### ISSUE THREAD

**Issue by KyleKotowick** [hashicorp/terraform-provider-aws#23547]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The [aws_lambda_layer_version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_layer_version) resource has a `skip_destroy` parameter, which allows you to keep old versions of the layer when you create new ones.

However, the [aws_lambda_layer_version_permission](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_layer_version_permission) resource does not have a corresponding parameter. When this resource is replaced due to a change in the `version_number` parameter, it removes the policy from the old version and creates the policy for the new version.

There is no way, as far as I can tell, to create a new layer version and new corresponding permission without deleting the permission from the old layer version. The workaround for this is to remove the `aws_lambda_layer_version_permission` resources from the state file prior to running the apply with the new layer version, but clearly that's not a great approach.

### New or Affected Resource(s)

* aws_lambda_layer_version_permission

### Potential Terraform Configuration

```hcl
resource "aws_lambda_layer_version" "lambda_layer" {
  filename   = "lambda_layer_payload.zip"
  layer_name = "lambda_layer_name"
  compatible_runtimes = ["nodejs12.x"]
  skip_destroy = true
}

resource "aws_lambda_layer_version_permission" "lambda_layer_permission" {
  layer_name     = aws_lambda_layer_version.lambda_layer.layer_arn
  version_number = aws_lambda_layer_version.lambda_layer.version
  principal      = "*"
  action         = "lambda:GetLayerVersion"
  statement_id   = "public-access"

  // This would be the new parameter.
  skip_destroy = aws_lambda_layer_version.lambda_layer.skip_destroy
}
```

**Comment by James-DeLorenzo** [comment]
hi, I've created the above [PR](https://github.com/hashicorp/terraform-provider-aws/pull/29571) that should fix this.
