### ISSUE TITLE
Add destroy invocation to aws_lambda_invocation resource

### ISSUE THREAD

**Issue by KyleKotowick** [hashicorp/terraform-provider-aws#23555]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The [aws_lambda_invocation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_invocation) resource is quite new, and is an excellent addition. However, it does not offer the ability to invoke a Lambda upon destruction of the resource, which limits its usefulness.

For example, I'd like to use this resource to automatically create database users when I create RDS clusters in a private VPC that cannot be accessed from the machine running Terraform. I can now do that by creating a Lambda in that VPC that can create users, and then using this resource to invoke that Lambda once for each user I'd like to create.

But then, how can I delete the database users if I no longer need them? Ideally, I'd be able to set a `destruction` configuration block which would allow me to do that, similar to the `local-exec` provisioner with `when = destroy`. If this configuration block is provided, the Lambda would be invoked again upon destruction with the associated configuration.

### New or Affected Resource(s)

* [aws_lambda_invocation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_invocation) (resource)

### Potential Terraform Configuration

```hcl
resource "aws_lambda_invocation" "example" {
  function_name = aws_lambda_function.db_user_manager.function_name
  qualifier = "$LATEST"

  input = jsonencode({
    db_host = "db.host.com"
    db_port = "5432"
    username = local.username 
    action = "mydbuser"
  })

  destroy {
    function_name = self.function_name
    qualifier = self.qualifier
    input = jsonencode({
      db_host = self.input .db_host
      db_port = self.input .db_port
      username = self.input .username 
      action = "DESTROY"
   })
  }
}
```

**Comment by ugurzongur** [comment]
We have recently developed a provider to address this, along with some other issues, if you'd like to check: https://registry.terraform.io/providers/thetradedesk/lambdabased

**Comment by skorfmann** [comment]
> We have recently developed a provider to address this, along with some other issues, if you'd like to check: https://registry.terraform.io/providers/thetradedesk/lambdabased

That's quite nice, thanks for sharing! 

Would love to see the something like the [finalizer](https://registry.terraform.io/providers/thetradedesk/lambdabased/latest/docs/resources/lambdabased_resource#finalizer) in the aws provider resource as well.

**Comment by kaushal02** [comment]
> We have recently developed a provider to address this, along with some other issues, if you'd like to check: https://registry.terraform.io/providers/thetradedesk/lambdabased

This seems to have been moved to a private repo now.
