### ISSUE TITLE
Resource aws_iam_user_login_profile "forces replacement" after upgrade to aws provider v4x

### ISSUE THREAD

**Issue by Arisfx** [hashicorp/terraform-provider-aws#23567]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- aws_iam_user_login_profile

Hi team, as the title says, the resource aws_iam_user_login_profile breaks after the upgrade to AWS provider v4x.

While the terraform code dictates `password_reset_required = true` and in the state file i can see that `"password_reset_required": true,` (in the aws console of course its enabled). 
When i am running terraform apply i get the `~ password_reset_required = false -> true # forces replacement` 

I understand that the upgrade to aws provider v4x is introducing many breaking changes but i wasn’t able to find anything useful in the upgrade documentation [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade)

### Terraform CLI and Terraform AWS Provider Version

P.S We are not using multiple providers, there is only 1 piece of code that this provider is declared:
```
  required_providers {
aws = {
  source  = "hashicorp/aws"
  version = "4.4.0"
 }
}
```
Am i missing something?
Thanks!

**Comment by rustige** [comment]
Had the same issue. Worked around it by explicitly ignoring changes on password_reset_required by lifcycle policy on the resource. Which should be the case automatically according to the manual.

Workaround:
`  lifecycle {
    ignore_changes = [password_reset_required]
  }`

**Comment by rowleyaj** [comment]
Is this possibly related to https://github.com/hashicorp/terraform-provider-aws/pull/12384/? The default value for `password_reset_required` was removed and it was changed to a computed field in that PR.

I've tested `4.0.0` and this issue doesn't happen, but in `4.1.0` which included that PR the issue does happen.

cc @DrFaust92 as the PR author as I'm unsure on the context for that change

**Comment by amontalban** [comment]
I'm having the same problem, unfortunately, I am using [terraform-aws-iam](https://github.com/terraform-aws-modules/terraform-aws-iam) module and I cannot do the workaround without creating a fork.

Is this behavior expected @DrFaust92? If so, I will ask for help in terraform-aws-modules/terraform-aws-iam#244

**Comment by nikolay** [comment]
@amontalban I created https://github.com/terraform-aws-modules/terraform-aws-iam/pull/271, please, 👍🏻 it - I am in the same boat, the upgrade of the AWS provider from v3 to v4 created a huge mess and locked out of AWS a bunch of people.

**Comment by bryantbiggs** [comment]
> @amontalban I created [terraform-aws-modules/terraform-aws-iam#271](https://github.com/terraform-aws-modules/terraform-aws-iam/pull/271), please, 👍🏻 it - I am in the same boat, the upgrade of the AWS provider from v3 to v4 created a huge mess and locked out of AWS a bunch of people.

This is not applicable here - this issue is asking for it to be addressed in the provider

**Comment by nikolay** [comment]
@bryantbiggs I agree. Still, it's a vastly popular module, which also does not work due to the upstream issue, which does not seem to be getting fixed anytime soon!

**Comment by fractos** [comment]
Seeing this as an issue with a client. Any movement on it?

**Comment by LDVSOFT** [comment]
Got hit by it today while migrating 3.x -> 4.x. This change can be worked through but needs to be documented. Don't see any movement here.

**Comment by sierra-alpha** [comment]
It caught me out to so I submitted a PR to at least update the docs. https://github.com/hashicorp/terraform-provider-aws/pull/35601
