### ISSUE TITLE
Ressource `aws_s3_bucket_lifecycle_configuration` > `object_size_greater_than` doesn’t work when used at Filter level

### ISSUE THREAD

**Issue by flibustier** [hashicorp/terraform-provider-aws#23575]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform 0.14 but reproduced with 0.15 and 1.0 
AWS provider 4.4.0 and 4.3.0

### Affected Resource(s)

* [aws_s3_bucket_lifecycle_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration#filter) (filter field)

### Terraform Configuration Files

This code doesn’t update the real infrastructure, it keeps planning the same change over and over
```hcl
resource "aws_s3_bucket_lifecycle_configuration" "my_bucket_lifecycles" {
  bucket = aws_s3_bucket.my_bucket.id

  rule {
    status = "Enabled"
    id     = "to-intelligent-tiering"

    filter {
      object_size_greater_than = 5242880
    }

    transition {
      days          = 1
      storage_class = "INTELLIGENT_TIERING"
    }
  }
```

### Debug Output

The output produced
```
  ~ resource "aws_s3_bucket_lifecycle_configuration" "my_bucket_lifecycles" {
        id     = "my-bucket"
        # (1 unchanged attribute hidden)

      ~ rule {
            id     = "to-intelligent-tiering"
            # (1 unchanged attribute hidden)

          ~ filter {
              + object_size_greater_than = "5242880"
            }

            # (1 unchanged block hidden)
        }
        # (3 unchanged blocks hidden)
    }
```

The output stay the same when applying multiple times (as it doesn’t change the real infrastructure)

### Panic Output

If I manually modify the corresponding field in the AWS console (I put 2MB of object size minimal), I got the following panic when terraform is planning the changes :

`Error: error setting rule: rule.0.filter.0.object_size_greater_than: '' expected type 'string', got unconvertible type 'int', value: '2097152'`

### Quick fix

It’s possible to avoid this using the `and` clause :
```hcl
filter {
      and {
        object_size_greater_than = 5242880
      }
}
```

It produced a working output (we can observe that the int type is here, instead of string in the faulty case)
```
  ~ resource "aws_s3_bucket_lifecycle_configuration" "my_bucket_lifecycles" {
        id     = "my-bucket"
        # (1 unchanged attribute hidden)

      ~ rule {
            id     = "to-intelligent-tiering"
            # (1 unchanged attribute hidden)

          ~ filter {
              + and {
                  + object_size_greater_than = 5242880
                }
            }

            # (1 unchanged block hidden)
        }
        # (3 unchanged blocks hidden)
    }
```

And the real infrastructure is changed 🎉 

### References

I guess this code seems incriminated : https://github.com/hashicorp/terraform-provider-aws/blob/1d268ac5efe1f86a342dfba78807275cda823983/internal/service/s3/bucket_lifecycle_configuration.go#L95

**Comment by anGie44** [comment]
Hi @flibustier , thank you for raising this issue. Just wanted to quickly note that I think this PR (https://github.com/hashicorp/terraform-provider-aws/pull/23441) should fix this as it addresses the panic your are seeing.

**Comment by flibustier** [comment]
Awesome ! I will track the progress of the PR then :) Thanks !!
