### ISSUE TITLE
service/macie: Handle EOL of `aws_macie_` resources 

### ISSUE THREAD

**Issue by anGie44** [hashicorp/terraform-provider-aws#23584]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

According to AWS documentation:
> Amazon Macie Classic (macie) has been discontinued and is no longer available. 
A new Amazon Macie (macie2) is now available with significant design improvements and additional features.

### New or Affected Resource(s)

* aws_macie_member_account_association
* aws_macie_s3_bucket_association

### Potential List of Changes

- [ ] Add note in documentation about EOL
- [ ] Skip acceptance tests 
- [ ] Deprecate resources for removal

### References

* https://github.com/aws/aws-sdk-go/releases/tag/v1.43.12

**Comment by ewbankkit** [comment]
We have confirmed with AWS that there are no customers still on Macie Classic, so we will move straight to removal for `v5.0.0`.

**Comment by jar-b** [comment]
Closed by #31058, merged to `main` via #31392
