### ISSUE TITLE
AWS ECS service propagate_tags without destroy & recreate

### ISSUE THREAD

**Issue by jawon-benchling** [hashicorp/terraform-provider-aws#23581]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, changing the value of aws_ecs_service.propagate_tags triggers a destroy & recreate of the entire service. It looks like there is now a way to update this value through the UpdateService API
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateService.html#API_UpdateService_RequestSyntax

Would it be possible to make it so that propagate_tags can be changed in terraform without destroy & recreate?

### New or Affected Resource(s)

* aws_ecs_service

### References

* https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateService.html#API_UpdateService_RequestSyntax

**Comment by md5** [comment]
SDK support seems to have landed in 1.43.13 as part of https://github.com/aws/aws-sdk-go/pull/4305
