### ISSUE TITLE
ECS service - update load_balancer without destroy & recreate

### ISSUE THREAD

**Issue by mignaulo** [hashicorp/terraform-provider-aws#23596]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, changing the value of aws_ecs_service.load_balancer triggers a destroy & recreate of the entire service. AWS added support for updating the service in-place in a recent API update.

### New or Affected Resource(s)

* aws_ecs_service

### References

* AWS Go SDK was updated https://github.com/aws/aws-sdk-go/pull/4305 
* Blog post announcement https://aws.amazon.com/about-aws/whats-new/2022/03/amazon-ecs-service-api-updating-elastic-load-balancers-service-registries-tag-propagation-ecs-managed-tags/
* Similar ticket https://github.com/hashicorp/terraform-provider-aws/issues/23581

**Comment by ewbankkit** [comment]
Requires: https://github.com/hashicorp/terraform-provider-aws/pull/23597.
