### ISSUE TITLE
Providing availability zone in datasource aws_subnet

### ISSUE THREAD

**Issue by springland** [hashicorp/terraform-provider-aws#23595]
I would like to get to know in which availability zones I have subnets deployed in a vpc.  I can get subnets by using data object.  However it does not tell me which az it is in. It seems there is no way to get that information

**Comment by mattburgess** [comment]
Could you provide the Terraform config that shows this behaviour please? The documentation at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/subnet says that the subnet allows you to provide a `availability_zone` argument, then under `Attributes Reference` it says:

> In addition to the attributes above, the following attributes are exported:

So you should be able to reference something like `data.aws_subnet.my_subnet.availability_zone`

**Comment by springland** [comment]
Thanks Matt. I missed that part that all of the arguments are available as attributes. Only checked the attributes list.
