### ISSUE TITLE
aws_lambda_permission source_arn doesn't allow IAM global condition context keys

### ISSUE THREAD

**Issue by scalp42** [hashicorp/terraform-provider-aws#23590]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.4.0
```

### Affected Resource(s)

* aws_lambda_permission

### Terraform Configuration Files

```hcl
resource "aws_lambda_permission" "allow_eventbridge" {
  statement_id  = "AllowExecutionFromEventBridge"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.ecr_image_actions.id
  principal     = "events.amazonaws.com"
  source_arn    = "arn:aws:events:us-west-2:$${aws:PrincipalAccount}:rule/ecr_image_actions"
}
```

### Expected Behavior

IAM context keys should be allowed.

### Actual Behavior

A regular expression prevents using IAM context keys:

```
╷
│ Error: "source_arn" (arn:aws:events:us-west-2:${aws:PrincipalAccount}:rule/ecr_image_actions) is an invalid ARN: invalid account ID value (expecting to match regular expression: ^(aws|\d{12})$)
│
│   with module.lambda.aws_lambda_permission.allow_eventbridge,
│   on lambda/ecr_image_actions.tf line 30, in resource "aws_lambda_permission" "allow_eventbridge":
│   30:   source_arn    = "arn:aws:events:us-west-2:$${aws:PrincipalAccount}:rule/ecr_image_actions"
│
╵
```

Thanks in advance 🙌

**Comment by justinretzolk** [comment]
Leaving this open for additional input, but based on the documentation of the [underlying API](https://docs.aws.amazon.com/lambda/latest/dg/API_AddPermission.html) I suspect this may not be possible.

> [SourceArn](https://docs.aws.amazon.com/lambda/latest/dg/API_AddPermission.html#API_AddPermission_RequestSyntax)
> Pattern: `arn:(aws[a-zA-Z0-9-]*):([a-zA-Z0-9\-])+:([a-z]{2}(-gov)?-[a-z]+-\d{1})?:(\d{12})?:(.*)`

**Comment by scalp42** [comment]
You're correct, closing. Thanks for the quick feedback, much appreciated 🙌
