### ISSUE TITLE
InvalidClientTokenId: The security token included in the request is invalid

### ISSUE THREAD

**Issue by deiga** [hashicorp/terraform-provider-aws#23617]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.74.3
```

### Affected Resource(s)

* aws_iam_role

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl

module "lambda" {
  source = "terraform-aws-modules/lambda/aws"

  function_name = "foo-bar-baz"
  description   = "Foo Bar Baz"
  handler       = "index.handler"
  runtime       = "nodejs14.x"

  lambda_at_edge = true

  source_path = "${path.module}/lambdas/foo-bar-baz"
}
```

### Debug Output

https://gist.github.com/deiga/bc0cbeab3779336e4aa20a11d3a00300

### Expected Behavior

`terraform apply` should have succeeded

### Actual Behavior

`terraform apply` failed with an error `InvalidClientTokenId: The security token included in the request is invalid`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I am using temporary security credentials for authentication. Sometimes the AWS_SECRET_ACCESS_KEY includes special characters like `+` and `/` 

### References

- This issue seems to indicate this has to do with special characters in the AWS_SECRET_ACCESS_KEY https://github.com/hashicorp/terraform/issues/2972
- These issues might be related https://github.com/hashicorp/terraform-provider-aws/issues/12111 https://github.com/hashicorp/terraform-provider-aws/issues/23370

**Comment by justinretzolk** [comment]
Hey @deiga 👋 Thank you for taking the time to raise this! A couple of the linked issues seem to indicate that they were experiencing errors as soon as a Terraform plan was started. Given that your debug logs seem to indicate that the plan is successful, but throws the credential error when you attempt to progress to the apply phase, I suspect this may be a different issue from theirs.

You mentioned that you're using temporary credentials for authentication; is it possible that the credentials expired between the plan and apply? Additionally, can you give a bit more detail (as much as you can, I know this can get sensitive quickly) as to how you're retrieving those credentials and supplying them to Terraform?

**Comment by deiga** [comment]
@justinretzolk Yeah, it's possible that the linked issues only seem to be related. I linked them in the case that they are related.
I did notice that once a colleague had applied the changes then `terraform plan` started failing with a similar output
```
Error: error reading IAM Role (foo-bar-baz): InvalidClientTokenId: The security token included in the request is invalid
│       status code: 403, request id: 4ca5cd54-8a61-42ff-b849-9169463d1c73
```

I use an application Leapp, which modifies `.aws/credentials` on the fly. Contents of that file when I'm logged in to a session
```
[terraform-staging]
aws_access_key_id=XXXXXXXXXXXXXXXXXXX
aws_secret_access_key=YYYYYYYYYYYYYYYYYYYY
aws_session_token="ZZZZZZZZZZZZZZZZZZ"
region=VVVVVV
```

I just tested to use that profile locally, and actually got the same error. Apparently, that profile gets quotes in the AWS_SESSION_TOKEN where others don't. I didn't realize this before, since that profile works for other resources than IAM and other profiles work for IAM as well.

So, this doesn't seem to be an issue with your provider.

**Comment by justinretzolk** [comment]
Hey @deiga 👋 Thank you for following up with that information! Given that it seems this isn't an issue with the provider, I'll close this issue out. If you feel I've done this in error, or further digging points back to this being an issue with the AWS Provider, please do let me know.

**Comment by deiga** [comment]
To give more context here, for people who might stumble upon this issue.

The actual issue was using Temporary Security Credentials without MFA enabled. AWS restricts accessing IAM in this case. This could have been a lot more clear from the error message, but that is again not this providers fault, it's the AWS clients fault AFAIK.
