### ISSUE TITLE
`aws_s3_bucket_lifecycle_configuration` : Overwrite Bug v4.4.0

### ISSUE THREAD

**Issue by jordancparker** [hashicorp/terraform-provider-aws#23612]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.4.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
+ provider registry.terraform.io/hashicorp/template v2.2.0

Your version of Terraform is out of date! The latest version
is 1.1.7. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

aws_s3_bucket_lifecycle_configuration

Currently when you run two separate `aws_s3_bucket_lifecycle_configuration` they overwrite each other, however in my below example i am look to define a default policy set, that can then be expanded up and built up over time to build bespoke policies. 

Although these rules can be added into a single resources, this behaviour causes a taint during a change, however using id should be sufficient enough as an index.  

### Bug Recreation

```terrafrom
resource "aws_s3_bucket_lifecycle_configuration" "example1" {
  bucket = aws_s3_bucket.this.id

  rule {
    id = "default_version_expiration_7_days"

    filter {}

    noncurrent_version_expiration {
      newer_noncurrent_versions = 2
      noncurrent_days           = 1
    }

    status = var.enabled ? "Enabled" : "Disabled"
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "example2" {
  bucket = aws_s3_bucket.this.id

  rule {
    id = "default_version_expiration_1_year"

    filter {}

    noncurrent_version_expiration {
      newer_noncurrent_versions = 1
      noncurrent_days           = 365
    }

    status = var.enabled ? "Enabled" : "Disabled"
  }
  depends_on = [aws_s3_bucket_lifecycle_configuration.example1]
}
```

### Expected Behavior

building multiple resources of aws_s3_bucket_lifecycle_configuration should increase the rules on the bucket, not overwrite the initial lifecycle rule. 

AWS Console 

aws_s3_bucket_lifecycle_configuration 
- ID = example1
- ID = example2

### Actual Behavior

AWS Console 

aws_s3_bucket_lifecycle_configuration 
- ID = example2

**Comment by anGie44** [comment]
Hi @jordancparker 👋 , thank you for raising this issue. This particular resource and `aws_s3_bucket_*` resources, in general, depend on S3 API calls that utilize an HTTP `PUT` action in order to modify the target S3 bucket so for `aws_s3_bucket_lifecycle_configuration`, with the underlying API method `PutBucketLifecycleConfiguration`, each new resource configured in Terraform will either 
> Creates a new lifecycle configuration for the bucket or replaces an existing lifecycle configuration.

Therefore, overwrites will occur by design of the upstream S3 API.
With that said, we could better document this 1:1 relationship between an S3 bucket and its configuration settings (`lifecycle_configuration`, `replication_configuration`, etc.) to prevent unexpected behaviors.

Reference: https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketLifecycleConfiguration.html

**Comment by jordancparker** [comment]
A suggestion would be to use the notes like `aws_s3_bucket_notification` as this was very clear for me to understand how to best utilise the resources, specially with debugging the dependency to get to overwrite itself.  

`NOTE:
S3 Buckets only support a single notification configuration. Declaring multiple aws_s3_bucket_notification resources to the same S3 Bucket will cause a perpetual difference in configuration. See the example "Trigger multiple Lambda functions" for an option.`

Thanks Again
