### ISSUE TITLE
Please release a 3.74.X patch release that includes the dotnet6 runtime

### ISSUE THREAD

**Issue by wattdave** [hashicorp/terraform-provider-aws#23635]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
For various reasons, we cannot move forward from the 3.x provider to the 4.x provider. We'd be grateful for a 3.74 patch release that includes the dotnet6 runtime, if possible.

### New or Affected Resource(s)

* aws_lambda_function

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by anGie44** [comment]
Hi @wattdave , the fix will be available in `v3.75.0` of the provider , which will be out later today.
