### ISSUE TITLE
Manage SSO/SAML users/groups for Amazon Managed Grafana (AMG)

### ISSUE THREAD

**Issue by andreaswittig** [hashicorp/terraform-provider-aws#23665]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS extended the API for Amazon Managed Grafana (AMG) which allows to configure authentication and authorization. For example, by mapping AWS SSO users and groups to Grafana (see https://docs.aws.amazon.com/grafana/latest/APIReference/API_UpdatePermissions.html).

### New or Affected Resource(s)

* `aws_grafana_user_association`

**Comment by AlexanderSchiff** [comment]
I believe this is specific to SSO and not SAML. I will work on this.

**Comment by andreaswittig** [comment]
@AlexanderSchiff You are correct, my description was not clear on that. Sorry.

**Comment by AlexanderSchiff** [comment]
In order to be consistent with the [SAML configuration resource](https://github.com/hashicorp/terraform-provider-aws/pull/23712) I think we should call the new resource `aws_grafana_workspace_sso_configuration`

**Comment by AlexanderSchiff** [comment]
I think this name makes sense. Starting to work on this
