### ISSUE TITLE
aws_dlm_lifecycle_policy does not have an option to exclude root volume snapshots

### ISSUE THREAD

**Issue by nazeemmohammed** [hashicorp/terraform-provider-aws#23677]
While creating dlm policies using AWS UI, there is an option to exclude root volumes from snapshot. There doesn't seem to be similar option available while creating using terraform aws_dlm_lifecycle_policy module.

**Comment by justinretzolk** [comment]
Hey @nazeemmohammed 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include the information requested in the [feature request template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Feature_Request.md)?

**Comment by nazeemmohammed** [comment]
Hi @justinretzolk below is my 

```
variable "tags" {
    default = ["instance1", "instance2", "instance3"]
}
resource "aws_dlm_lifecycle_policy" "DLMCredcas_prd" {
    for_each = toset(var.tags)
    description = "DLM_${each.value}"
    execution_role_arn = "arn:aws:iam::xxxx:role/service-role/AWSDataLifecycleManagerDefaultRole"
    policy_details {
      resource_types = ["INSTANCE"]
      schedule {
        name = "${each.value}-snapshot-12hours"
        create_rule {
          interval      = 12
          interval_unit = "HOURS"
          times         = ["23:00"]
        }         
      retain_rule { count = 28 }
      copy_tags = false
    }
    target_tags = {
      Name = "${each.value}"
    }
   }
}
```
AWS provides below option to exclude root volumes which I do not find in terraform documentation. 

Parameters:
          ExcludeBootVolume: True

Also as per terraform documentation resource_types only allows VOLUME type which is not correct - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dlm_lifecycle_policy#resource_types
