### ISSUE TITLE
RDS: Cross-region automated backups

### ISSUE THREAD

**Issue by cdobbyn** [hashicorp/terraform-provider-aws#23673]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
In RDS it is possible to enable snapshots to be saved in another region besides the region the instance is in. This is helpful from a disaster recovery standpoint.

### New or Affected Resource(s)
* aws_db_instance
* aws_rds_cluster

### Potential Terraform Configuration

```hcl
resource "aws_db_instance" "default" {
  ...
  backup_replication_region = "us-west-2"
  backup_replication_period = 7
  backup_replication_kms_key_id = "11111111-aaaa-1111-aaaa-111111111111"
  ...
}
```

### References
* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReplicateBackups.html
* https://github.com/aws/aws-sdk-go/pull/3675

**Comment by bschaatsbergen** [comment]
I'll happily check this out and pick it up.

**Comment by bschaatsbergen** [comment]
@ewbankkit something we would want to treat as a new resource or make it part of the existing `aws_db_instance` resource? 

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReplicateBackups.html#AutomatedBackups.Replicating.Enable

**Comment by bschaatsbergen** [comment]
I find this specific API to be designed a bit poorly. The API exposes a DestinationRegion and SourceRegion which are both not sent over the wire. 

By looking at the CLI documentation it's expected that you treat the `--region` flag as the destination region. 


(Below shows how to replicate automated backups from us-east-1 to us-west-2)
```
aws rds start-db-instance-automated-backups-replication \
    --region us-west-2 \ <---- destination region
    --source-db-instance-arn "arn:aws:rds:us-east-1:123456789012:db:new-orcl-db" \
    --backup-retention-period 14
```

I was hoping that we could use the region in the provider block as the source region, so one can create a resource and set a `destination_region` as attribute in the resource. But this doesn't seem possible unfortunately.
