### ISSUE TITLE
EnableMFADevice Support to pair with iam_virtual_mfa_device

### ISSUE THREAD

**Issue by cdimino** [hashicorp/terraform-provider-aws#23680]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like to associate the MFA device I've created with `iam_virtual_mfa_device` to an account, but there doesn't seem to be a corresponding `iam_enable_mfa_device` resource to use.  The `EnableMFADevice` API seems like a good fit, and there is at least one test that seems to successfully work with a virtual MFA device, here: https://github.com/hashicorp/terraform-provider-aws/blob/611b4737168f4f0051bb63ef221f0e76f156f392/internal/service/iam/user_test.go#L619

### New or Affected Resource(s)

* iam_enable_mfa_device

### Potential Terraform Configuration

```hcl
resource "iam_enable_mfa_device" "example" {
  virtual_mfa_device = iam_virtual_mfa_device.example.arn
}
```

### References

* https://docs.aws.amazon.com/IAM/latest/APIReference/API_EnableMFADevice.html

**Comment by gdavison** [comment]
The `EnableMFADevice` API requires TOTP authentication codes generated by an authenticator application using the code returned by `iam_virtual_mfa_device` in either `base_32_string_seed` or `qr_code_png`. As @DrFaust92 mentioned, the authentication codes need to be passed to `EnableMFADevice` immediately after generation. This cannot be performed in Terraform.

On the other hand, you can use the AWS CLI command [`aws iam enable-mfa-device`](https://docs.aws.amazon.com/cli/latest/reference/iam/enable-mfa-device.html) or a tool using the `EnableMFADevice` API call along with the `arn` and the TOTP authentication codes to enable the virtual MFA device.
