### ISSUE TITLE
Increase time to deploy aws_ec2_transit_gateway_connect_peer

### ISSUE THREAD

**Issue by mtarnoci** [hashicorp/terraform-provider-aws#23689]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform v1.1.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.4.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.7.2 --->

* aws_ec2_transit_gateway_connect_peer 

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior
AWS Provider should wait longer time while waiting for state to become 'available' for aws_ec2_transit_gateway_connect_peer

### After 10 minutes, when connect peeri is not "available" yet, terraform fails with error:
Error: error waiting for EC2 Transit Gateway Connect Peer (tgw-connect-peer-0f161e72b4b6df78a) create: timeout while waiting for state to become 'available' (last state: 'pending', timeout: 10m0s)
│ 
│   with aws_ec2_transit_gateway_connect_peer.gre-01-cedge-black["cpe01_vpn2"],
│   on 01_ngena-transit-gateway.tf line 270, in resource "aws_ec2_transit_gateway_connect_peer" "gre-01-cedge-black":
│  270: resource "aws_ec2_transit_gateway_connect_peer" "gre-01-cedge-black" 
After five more minutes is connect peer availble (via console)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ewbankkit** [comment]
@mtarnoci Thanks for raising the issue 👏.
The [creation timeout](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_transit_gateway_connect_peer#create) can be increased via a resource-level [`timeouts` block](https://www.terraform.io/language/resources/syntax#operation-timeouts):

```hcl
resource "aws_ec2_transit_gateway_connect_peer" "example" {
  ...

  timeouts {
    create = "60m"
  }
}
```
