### ISSUE TITLE
aws_networkfirewall_rule_group: Cannot reference multiple ip_sets in source/destination in header for a stateful rule

### ISSUE THREAD

**Issue by midestefanis** [hashicorp/terraform-provider-aws#23686]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_networkfirewall_rule_group

### Potential Terraform Configuration

```hcl
resource "aws_networkfirewall_rule_group" "example" {
  capacity = 100
  name     = "example"
  type     = "STATEFUL"
  rule_group {
    rule_variables {
      ip_sets {
        key = "WEBSERVER_HOSTS_2"
        ip_set {
          definition = ["10.48.208.0/23"]
        }
      }
      ip_sets {
        key = "WEBSERVER_HOSTS"
        ip_set {
          definition = ["10.0.0.0/16", "10.0.1.0/24", "192.168.0.0/16"]
        }
      }      
    }
    rules_source {
        stateful_rule {
            action = "PASS"
            header {
                destination = "$WEBSERVER_HOSTS$WEBSERVER_HOSTS_2"
                source = "0.0.0.0/0"
                destination_port = "443"
                source_port = "ANY"
                protocol = "TCP"
                direction = "ANY"
            }
            rule_option {
                keyword: "sid:1"
            }
        }
    }
  }
}
```

### Expected Behavior

The source/destination in the header should be able to reference multiple ip_set. This works via AWS Console. This is not working via Terraform

### Actual Behavior

InvalidRequestException: stateful rule is invalid, ***** , reason: not every address block was properly closed in "[***", 1 missing closing brackets (]). Note: problem might be in a variable.

### References

* #22727

**Comment by mike-morris-emis** [comment]
try the following, add a comma between the ip_set variables $WEBSERVER_HOSTS,$WEBSERVER_HOSTS_2

```hcl
resource "aws_networkfirewall_rule_group" "example" {
  capacity = 100
  name     = "example"
  type     = "STATEFUL"
  rule_group {
    rule_variables {
      ip_sets {
        key = "WEBSERVER_HOSTS_2"
        ip_set {
          definition = ["10.48.208.0/23"]
        }
      }
      ip_sets {
        key = "WEBSERVER_HOSTS"
        ip_set {
          definition = ["10.0.0.0/16", "10.0.1.0/24", "192.168.0.0/16"]
        }
      }      
    }
    rules_source {
        stateful_rule {
            action = "PASS"
            header {
                destination = "$WEBSERVER_HOSTS,$WEBSERVER_HOSTS_2"
                source = "0.0.0.0/0"
                destination_port = "443"
                source_port = "ANY"
                protocol = "TCP"
                direction = "ANY"
            }
            rule_option {
                keyword: "sid:1"
            }
        }
    }
  }
}```
