### ISSUE TITLE
Provider produced inconsistent final plan - aws_s3_bucket_replication_configuration

### ISSUE THREAD

**Issue by barakseri1** [hashicorp/terraform-provider-aws#23690]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform version: 1.0.5
aws provider version: 4.5.0
### Affected Resource(s)

* aws_s3_bucket_replication_configuration

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
.
.
.
resource "aws_s3_bucket" "source" {
    provider = aws.source
    bucket = "${var.source_bucket_name}-${var.source_region}"
    tags = var.tags
}

resource "aws_s3_bucket" "destination" {
    bucket = "${var.source_bucket_name}-${var.dc}"
    tags = var.tags
}
.
.
.
resource "aws_s3_bucket_replication_configuration" "replication" {
  depends_on = [aws_s3_bucket_versioning.source]
  provider = aws.source
  role   = aws_iam_role.replication.arn
  bucket = aws_s3_bucket.source.id


  rule {
    filter {}
    status = "Enabled"
    priority = 1
    delete_marker_replication {
      status = "Enabled"
    }

    destination {
      bucket        = aws_s3_bucket.destination.arn
    }
  }
}
```

### Debug Output

https://gist.github.com/barakseri1/53b2a8d3f3887ebc363d7a84c4f6d277

### Steps to Reproduce

First apply creates the resources as expected.
Following applies result in the error provided

1. `terraform apply`

### References

* #0000

**Comment by anGie44** [comment]
Likely related to https://github.com/hashicorp/terraform-provider-aws/issues/23487

**Comment by anGie44** [comment]
One way to work around this for the time being is to provide an `id` for the rule at creation time so that the upstream AWS API doesn't calculate one for you and thus prevent a diff in terraform

**Comment by barakseri1** [comment]
Thanks @anGie44 , sorry for missing that duplicate issue.
Indeed the first apply was with v4.3.0 and the consequent with 4.5.0.

I will try to delete the replication and try again both with 4.5.0, and also will try the workaround you suggested
