### ISSUE TITLE
aws fms ploicy with security goup content audit

### ISSUE THREAD

**Issue by anoora17** [hashicorp/terraform-provider-aws#23696]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
v3.74.3

### Affected Resource(s)

* aws_fms_policy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_fms_policy" "content_audit" {

  name                        = "test"
  delete_all_policy_resources = true
  exclude_resource_tags       = false
  remediation_enabled         = false
  resource_type_list          = ["AWS::EC2::SecurityGroup", "AWS::EC2::Instance"]
 
  include_map {
    account = ["xxxxxxxxxxxxx"]
  }

  security_service_policy_data {
    type = "SECURITY_GROUPS_CONTENT_AUDIT"

    managed_service_data = jsonencode({
      type                = "SECURITY_GROUPS_CONTENT_AUDIT"
      securityGroups      = ["sg-xxxxxxx"]
      securityGroupAction = "DENY"
     
    })
  }
}
```

### Panic Output

```
Error: Creating Policy Failed: InvalidInputException: Error in the SecurityServiceData.ManagedServiceData at [Source: (String)"{"securityGroupAction":"DENY","securityGroups":["sg-xxxxxxxxxxxxx"],"type":"SECURITY_GROUPS_CONTENT_AUDIT"}"; line: 1, column: 24]
```

### Expected Behavior

The terraform plan works fine

### Steps to Reproduce

1. `terraform apply` has error

```
Error: Creating Policy Failed: InvalidInputException: Error in the SecurityServiceData.ManagedServiceData at [Source: (String)"{"securityGroupAction":"DENY","securityGroups":["sg-xxxxxxxxxxxxx"],"type":"SECURITY_GROUPS_CONTENT_AUDIT"}"; line: 1, column: 24]
```

### References

*[terraform go api](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/fms/fms_test.go) if you check the test there is no test case for the security audit type only waf
*[ #aws api](https://docs.aws.amazon.com/fms/2018-01-01/APIReference/API_SecurityServicePolicyData.html)
*[ #terform api](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fms_policy#security_service_policy_data-configuration-block)

**Comment by justinretzolk** [comment]
Hey @anoora17 👋 Thank you for taking the time to raise this! The [documentation for `aws_fms_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fms_policy) links out to an [AWS document](https://docs.aws.amazon.com/fms/2018-01-01/APIReference/API_SecurityServicePolicyData.html) that discusses the formatting expected here. From that document, I found this line that was relevant to what you're trying to do:

> Example: SECURITY_GROUPS_CONTENT_AUDIT
> `"{\"type\":\"SECURITY_GROUPS_CONTENT_AUDIT\",\"securityGroups\":[{\"id\":\"sg-000e55995d61a06bd\"}],\"securityGroupAction\":{\"type\":\"ALLOW\"}}"`
>
> The security group action for content audit can be ALLOW or DENY. For ALLOW, all in-scope security group rules must be within the allowed range of the policy's security group rules. For DENY, all in-scope security group rules must not contain a value or a range that matches a rule value or range in the policy security group.

Based on that, it looks like you're missing a bit on the `securityGroups` key. The `managed_service_data` block should instead read:

```hcl
    managed_service_data = jsonencode({
      type                = "SECURITY_GROUPS_CONTENT_AUDIT"
      securityGroups      = [{
        id = "sg-xxxxxxx"
      }]
      securityGroupAction = "DENY" 
    })
```

**Comment by anoora17** [comment]
@justinretzolk I tried  your suggestd code and still getting the same error 

```
Error modifying FMS Policy Rule: InvalidInputException: Error in the SecurityServiceData.ManagedServiceData at [Source: (String)"{"securityGroupAction":"DENY","securityGroups":[{"id":"sg-xxxxxxxxxxx"}],"type":"SECURITY_GROUPS_CONTENT_AUDIT"}"; line: 1, column: 24]
```

````
resource "aws_fms_policy" "content_audit" {

  name                                   = "test"
  delete_all_policy_resources = true
  exclude_resource_tags        = false
  remediation_enabled          = false
  resource_type_list               = ["AWS::EC2::SecurityGroup", "AWS::EC2::Instance"]

  include_map {
    account = ["xxxxxxxxxxx"]
  }

  security_service_policy_data {
    type = "SECURITY_GROUPS_CONTENT_AUDIT"

    managed_service_data = jsonencode({
      type                = "SECURITY_GROUPS_CONTENT_AUDIT"
      securityGroupAction = "DENY"
      securityGroups = [{
        id = "sgxxxxxxxx"
      }]
    })
  }
}
````

**Comment by anoora17** [comment]
@justinretzolk it look like the jsonencode function causing the issue if I change it to 
managed_service_data = "{\"type\":\"SECURITY_GROUPS_CONTENT_AUDIT\",\"securityGroups\":[{\"id\":\"sg-xxxxxxxxxxx\"}],\"securityGroupAction\":{\"type\":\"DENY\"}}" this will work

**Comment by anoora17** [comment]
@justinretzolk your post helped I was able to solve it by 
```
managed_service_data = jsonencode({
      type                = "SECURITY_GROUPS_CONTENT_AUDIT"
      securityGroupAction = { type = "DENY"}
      securityGroups = [{
        id = "sg-xxxxxxxxxxxxxxxxx"
      }]
    })
```

**Comment by anoora17** [comment]
The issue get solve by adding extra curly brackets to match aws [docs](https://docs.aws.amazon.com/fms/2018-01-01/APIReference/API_SecurityServicePolicyData.html)

**Comment by justinretzolk** [comment]
Hey @anoora17 👋 I'm really glad you were able to get this resolved (and apologies that I missed the extra changes around `secrurityGroupAction`)! And an extra huge _thank you_ for coming back and posting exactly _how_ you got this resolved in case anyone runs into this again, that's extremely helpful!
