### ISSUE TITLE
ec2 Instance recreates on every apply when security groups configured

### ISSUE THREAD

**Issue by vaspahomov** [hashicorp/terraform-provider-aws#23693]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
bash-5.1$ terraform version
Terraform v1.0.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.3.0
+ provider terraform-registry.storage.yandexcloud.net/hashicorp/aws v4.3.0
````
### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

```json
{
   "provider":{
      "hashicorp":{
         "region":"eu-north-1"
      }
   },
   "resource":{
      "aws_instance":{
         "instance1":{
            "ami":"ami-0820d427f94ae9361",
            "instance_type":"t3.micro",
            "key_name":"public-key",
            "lifecycle":{
               "prevent_destroy":true
            },
            "security_groups":[
               "sg-0af9b6156d394566c"
            ],
            "subnet_id":"subnet-064555a93bc098d19",
            "tags":{
               "crossplane-kind":"instance.ec2.aws.jet.crossplane.io",
               "crossplane-name":"instance1",
               "crossplane-providerconfig":"default"
            }
         }
      }
   },
   "terraform":{
      "required_providers":{
         "hashicorp":{
            "source":"hashicorp/aws",
            "version":"4.3.0"
         }
      }
   }
}
```

### Debug Output

Terraform plan of apply:

https://gist.github.com/vaspahomov/d91b0f618b5339d0906fbf5f45626e5d

### Expected Behavior

 Resource should not be recreated. And security group should be already attached to instance.

### Actual Behavior

Provider trying to recreate resource on every apply.

### Steps to Reproduce

```shell
# Create resource
terraform apply
# Call plan on next call
terraform plan
```

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @vaspahomov 👋 Thank you for taking the time to raise this. In looking at the logs provided, I see the following:

```plaintext
...
      ~ security_groups                      = [ # forces replacement
          + "sg-0af9b6156d394566c",
        ]
...
      ~ vpc_security_group_ids               = [
          - "sg-0af9b6156d394566c",
        ] -> (known after apply)
...
```

Looking at the documentation for [the `aws_instance` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance), I see the following note with regards to the `security_groups` argument:

> [security_groups](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#security_groups) - (Optional, EC2-Classic and default VPC only) A list of security group names to associate with.
> NOTE:  If you are creating Instances in a VPC, use `vpc_security_group_ids` instead.

With that note and the clipping from the logs in mind, is the subnet defined (`"subnet_id":"subnet-064555a93bc098d19",`) in the default VPC, or in a separate VPC that you've created?

**Comment by vaspahomov** [comment]
Thanks!

This is the subnet from the VPC I created. I've change `security_groups` to `vpc_security_group_ids` and now everything is ok. 

May be we can add validation here? (If user creating instance in a VPC and defining `security_groups` fall with validation error)

**Comment by justinretzolk** [comment]
Hey @vaspahomov 👋 Thanks for getting back to me and letting me know that helped! With that information, and your mention of a potential validation, I've marked this as an enhancement so that we can take a look to determine if that's something that could be done.

**Comment by serhiiromaniuk** [comment]
Hi folks!
As I understood `vpc_security_group_ids` stands for newer functionality.
For historical reasons (August 15, 2022 retire, [info](https://aws.amazon.com/blogs/aws/ec2-classic-is-retiring-heres-how-to-prepare/)) it should replace the default (across a lot of resource) meaning -> `security_groups` and use for instance `classic_security_group_ids`.
