### ISSUE TITLE
Renaming Security Group, doesn't remove old SG's from resource first

### ISSUE THREAD

**Issue by misilot** [hashicorp/terraform-provider-aws#23708]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.5.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Affected Resource(s)

* aws_security_group
* aws_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

Original Config
```hcl
resource "aws_security_group" "public-http-https" {
  name_prefix = "lib"
  vpc_id = var.LibVPC
  tags = {
    Name = "http/https public"
    terraform = "Managed by Terraform"

  }
  ingress = [
    {
      cidr_blocks = [
        "0.0.0.0/0",
      ]
      description      = "Public HTTP Traffic"
      from_port        = 80
      to_port          = 80
      protocol         = "tcp"
      ipv6_cidr_blocks = []
      prefix_list_ids  = []
      security_groups  = []
      self             = false
    },
    {
      cidr_blocks = [
        "0.0.0.0/0",
      ]
      description      = "Public HTTPS Traffic"
      from_port        = 443
      to_port          = 443
      protocol         = "tcp"
      ipv6_cidr_blocks = []
      prefix_list_ids  = []
      security_groups  = []
      self             = false
    }
  ]

  egress {
    from_port        = 0
    to_port          = 0
    protocol         = "-1"
    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }
}
```

```hcl
resource "aws_security_group" "public-http-https" {
  name = "libHttpHttpsPublic"
  vpc_id = var.LibVPC
  tags = {
    Name = "http/https public"
    terraform = "Managed by Terraform"

  }
  ingress = [
    {
      cidr_blocks = [
        "0.0.0.0/0",
      ]
      description      = "Public HTTP Traffic"
      from_port        = 80
      to_port          = 80
      protocol         = "tcp"
      ipv6_cidr_blocks = []
      prefix_list_ids  = []
      security_groups  = []
      self             = false
    },
    {
      cidr_blocks = [
        "0.0.0.0/0",
      ]
      description      = "Public HTTPS Traffic"
      from_port        = 443
      to_port          = 443
      protocol         = "tcp"
      ipv6_cidr_blocks = []
      prefix_list_ids  = []
      security_groups  = []
      self             = false
    }
  ]

  egress {
    from_port        = 0
    to_port          = 0
    protocol         = "-1"
    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }
}
```

### Debug Output
n/a

### Expected Behavior

1. Create new security group
2. add security group to ec2 instance
3. remove old SG from ec2 instance
4. Delete old SG

### Actual Behavior

1. Attempts to delete old security group, without removing from instances

```
aws_security_group.public-http-https: Destroying... [id=sg-0836b287d3f086048]
aws_security_group.public-http-https: Still destroying... [id=sg-0836b287d3f086048, 10s elapsed]
aws_security_group.public-http-https: Still destroying... [id=sg-0836b287d3f086048, 20s elapsed]
aws_security_group.public-http-https: Still destroying... [id=sg-0836b287d3f086048, 30s elapsed]
aws_security_group.public-http-https: Still destroying... [id=sg-0836b287d3f086048, 40s elapsed]
aws_security_group.public-http-https: Still destroying... [id=sg-0836b287d3f086048, 50s elapsed]
aws_security_group.public-http-https: Still destroying... [id=sg-0836b287d3f086048, 1m0s elapsed]
aws_security_group.public-http-https: Still destroying... [id=sg-0836b287d3f086048, 1m10s elapsed]
aws_security_group.public-http-https: Still destroying... [id=sg-0836b287d3f086048, 1m20s elapsed]
aws_security_group.public-http-https: Still destroying... [id=sg-0836b287d3f086048, 1m30s elapsed]
aws_security_group.public-http-https: Still destroying... [id=sg-0836b287d3f086048, 1m40s elapsed]
aws_security_group.public-http-https: Still destroying... [id=sg-0836b287d3f086048, 1m50s elapsed]
aws_security_group.public-http-https: Still destroying... [id=sg-0836b287d3f086048, 2m0s elapsed]
aws_security_group.public-http-https: Still destroying... [id=sg-0836b287d3f086048, 2m10s elapsed]
```

What happens is the security group attempts to get deleted before being removed from ec2 instances that are defined with the security group. If I go and remove the SG from the instance in the EC2 console, it continues as expected and eventually deletes it, creates the new one, and attaches it to the ec2 instance.

### Steps to Reproduce

1. `terraform apply`

**Comment by md5** [comment]
It looks like you can work around this limitation by using the [`create_before_destroy`](https://www.terraform.io/language/meta-arguments/lifecycle#create_before_destroy) parameter in the security group resource's `lifecycle` configuration.

Be aware that this is only safe to do when changing the `name` of your security group or when using `name_prefix` instead of `name`. If you are using `name` and the destroy is triggered by changing `description` or `vpc_id`, then you will get an `InvalidGroup.Duplicate` error.

**Comment by bigmikes** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/713ff0a6bb341227eba0664c977ae31e6a506e3d/internal/service/ec2/security_group.go#L434-L453

Today, the Security Group resource delete handler does not seem to handle this use-case. That is, it does not detach the SG from its NICs before deleting it. For other use-cases, this is probably handled in the EC2 NIC handler itself. 

But at line 439 the handler does delete the attachments for the NICs that Lambda implicitly creates. Should we do something similar even for non-Lambda NICs?

**Comment by bigmikes** [comment]
After a closer look, I am not sure how we can fix this in code. Terraform's default behavior is to delete the resource and then create the new one. AWS does not allow to leave a NIC with no Security Group associated. Ideally, the new SG should be created first, then associated to the NICs where the old SG is assigned to and finally delete the old SG. 

So the [create_before_destroy](https://www.terraform.io/language/meta-arguments/lifecycle#create_before_destroy) parameter is the right solution in this case. I've verified it. I am thinking of improving the doc.

**Comment by misilot** [comment]
Thanks for this. Just want to make sure I am following correctly. 

I have to use the `create_before_destory` option, do a `terraform apply` and than remove the `create_before_destroy` and perform another `terraform apply`?

**Comment by bigmikes** [comment]
No need to remove the `create_before_destroy` parameter aftet. Just add it to your security_group resource:

```
```
