### ISSUE TITLE
aws_s3_bucket_acl does not like "_" in bucket name

### ISSUE THREAD

**Issue by driskillb43** [hashicorp/terraform-provider-aws#23702]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform: 0.14.10
AWS Provider: 4.5.0

### Affected Resource(s)

aws_s3_bucket_acl

### Terraform Configuration Files

```hcl
data "aws_canonical_user_id" "current_user" {}

resource "aws_s3_bucket" "this" {
  bucket = "test_bucket"
}

resource "aws_s3_bucket_acl" "this" {
  bucket = "test_bucket"
  access_control_policy {
    owner {
      id = data.aws_canonical_user_id.current_user.id
    }
    grant {
      permission = "FULL_CONTROL"
      grantee {
        type = "CanonicalUser"
        id = data.aws_canonical_user_id.current_user.id
      }
    }
}
```

### Expected Behavior

I am able to successfully apply the above or import the test_bucket acl

### Actual Behavior

I get the error:

```
unexpected format for ID (test_bucket), expected BUCKET or BUCKET,EXPECTED_BUCKET_OWNER or BUCKET,ACL or BUCKET,EXPECTED_BUCKET_OWNER,ACL
```

### Steps to Reproduce

1. Create bucket with "_" in the name
2. Use the template above and do a `terraform import aws_s3_bucket_acl.this test_bucket`
3. Run a `terraform plan`

**Comment by anGie44** [comment]
Hi @driskillb43 , thank you for raising this issue. A similar issue was opened (https://github.com/hashicorp/terraform-provider-aws/issues/23676) and has been addressed to help support bucket names that were once created with underscores. This will be released with `v4.6.0` of the AWS provider, likely out this Thursday.
