### ISSUE TITLE
aws_s3_bucket_versioning cannot disable versioning

### ISSUE THREAD

**Issue by skeggse** [hashicorp/terraform-provider-aws#23718]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.5.0
```

### Affected Resource(s)

* `aws_s3_bucket_versioning`

### Terraform Configuration Files

There is no valid Terraform configuration corresponding to 

```hcl
resource "aws_s3_bucket_versioning" "bucket" {
  bucket = aws_s3_bucket.bucket.bucket

  versioning_configuration {
    status = "Disabled"
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The resource should support a disabled state for bucket versioning. The only way to handle such buckets in v4 appears to be to omit the resource entirely, which results in the versioning being _unmanaged_ rather than actively disabled. Despite the fact that the action operation to transition a bucket from versioned to unversioned isn't supported by AWS, it's still important to track these changes using the standardized tooling that Terraform provides. Moreover, this blocks `import`s of existing buckets during the migration process lazily forced upon Terraform users in https://github.com/hashicorp/terraform-provider-aws/issues/23106, and makes it impossible to check for drift in that portion of a bucket's configuration.

### Actual Behavior

```sh
╷
│ Error: expected versioning_configuration.0.status to be one of [Enabled Suspended], got Disabled
│
│   with aws_s3_bucket_versioning.bucket,
│   on test.tf line 5, in resource "aws_s3_bucket_versioning" "bucket":
│    5:     status = "Disabled"
│
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

* #5132

**Comment by anGie44** [comment]
Hi @skeggse , thank you for raising this issue. From what I've gathered from the AWS documentation (https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html#versioning-states) , versioning cannot be disabled  but MfaDelete for example can. 

> Buckets can be in one of three states:
>
> Unversioned (the default)
>
> Versioning-enabled
>
> Versioning-suspended
>
> You enable and suspend versioning at the bucket level. After you version-enable a bucket, it can never return to an unversioned state. But you can suspend versioning on that bucket.

Perhaps versioning _can_ be disabled via a request to AWS Support though.

**Comment by skeggse** [comment]
@anGie44 Thanks for clarifying. I see the problem, though I think I perhaps mis-stated my need. I'm less concerned about actually disabling bucket versioning, and more concerned about detecting that drift: sure, if we have to make the change manually, we'll do that, but if we don't even know that a drift has occurred, then we don't know that an action needs to be taken.

Can we add a disabled state anyway, even though we know it won't work? That way, Terraform's core functionality - the diff - still works.

As an aside, I'm also seeing that we can't import a versioning resource if the bucket is unversioned, which is a related problem - I'd like to be able to import these resources for unversioned buckets.

**Comment by anGie44** [comment]
I see what you mean now, thanks for the additional info @skeggse . So it looks the `GetBucketVersioning` API method will actually return a non-nil output when the bucket is unversioned/disabled and has an empty string status which we can for our purposes rebrand as something like `"Unversioned"`. We can include this new "state" as a valid target state, that way every time the resource is refreshed, `versioning_configuration` will be stored in state as the following instead of timing out with ` Error: error waiting for S3 Bucket Versioning status for bucket (tf-test-bucket-yada-yada): timeout while waiting for state to become 'Enabled, Suspended' (timeout: 1m0s)`

```
 "versioning": [
130               {
131                 "enabled": false,
132                 "mfa_delete": false
133               }
134             ],
```

I wonder though, if we can better represent the "disabled" state of bucket versioning by using a data source instead? that way you could detect a change and not worry about the singular data source erroring out.

Because the change describe above would affect the UX for create/update vs. import (e.g. we'll need to allow `versioning_configuration` to be Optional to support import but it cannot be left unspecified during create/update), and thus possibly confuse practitioners, I'd like wait and see more community interest before working on potential code changes within the `aws_s3_bucket_versioning` and am also happy to hear other potential solutions you or the community may have.

**Comment by skeggse** [comment]
> I wonder though, if we can better represent the "disabled" state of bucket versioning by using a data source instead? that way you could detect a change and not worry about the singular data source erroring out.

I'm not familiar with this pattern of tracking resource changes - if the data source has changed, Terraform will still say that there are no changes, because it's a data source instead of a `resource`, right? So Terraform would prompt no action, and the change would go unnoticed.

If I'm not mistaken, this is a regression from the aws provider v3, because we _used_ to be able to see this change:

```
Terraform will perform the following actions:

  # aws_s3_bucket.bucket will be updated in-place
  ~ resource "aws_s3_bucket" "bucket" {
        # (11 unchanged attributes hidden)

      ~ versioning {
          ~ enabled    = true -> false
            # (1 unchanged attribute hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

I'm not sure I understand why we overhauled the buckets in v4, and it seems weird that we would have done that while also taking steps backwards.

In light of this being a regression, I'd like to consider a quicker fix. We're trying to upgrade from v3 to v4, and this is a blocker. It's odd to me that we shipped this regression.

**Comment by anGie44** [comment]
> In light of this being a regression, I'd like to consider a quicker fix. We're trying to upgrade from v3 to v4, and this is a blocker. It's odd to me that we shipped this regression.

Not to worry @skeggse , please refer to https://github.com/hashicorp/terraform-provider-aws/issues/23106. We're currently working on moving the `aws_s3_bucket` resource back to how it was previously as suggested in #2 (e.g versioning in this example will be configurable again), so the upgrade shoudn't be as painful for practitioners as is currently.
