### ISSUE TITLE
Add support for AWS Cloud Quest

### ISSUE THREAD

**Issue by myoung34** [hashicorp/terraform-provider-aws#23721]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would like to automate my drop-in to the metaverse: https://www.aboutamazon.com/news/aws/two-new-free-aws-initiatives-help-build-foundational-cloud-skills

### New or Affected Resource(s)

* aws_cloud_quest

### References

https://www.aboutamazon.com/news/aws/two-new-free-aws-initiatives-help-build-foundational-cloud-skills

**Comment by justinretzolk** [comment]
Hey @myoung34 👋 Thank you for taking the time to raise this! It doesn't look like there's any API support for Cloud Quest, and thus no support for it in the AWS Go SDK. Because of this, we'll close this issue for now, but if the APIs are added in the future, we'd be happy to take another look!
