### ISSUE TITLE
Error when trying to create glue catalog database

### ISSUE THREAD

**Issue by mgermy** [hashicorp/terraform-provider-aws#23728]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.74.3
```

### Terraform Configuration Files

I'm trying to create a simple glue catalog database (no crawlers, just a simple database to be later populated) 
```terraform
resource "aws_glue_catalog_database" "mydb" {
  name = "examplegluedb"
}
```

### Expected Behavior

Create a glue catalog database 

### Actual Behavior
```shell
╷
│ Error: Error creating Catalog Database: InvalidParameter: 1 validation error(s) found.
│ - minimum field size of 1, CreateDatabaseInput.CatalogId.
│ 
│ 
│   with module.glue.aws_glue_catalog_database.mydb,
│   on ../modules/glue/glue-db.tf line 6, in resource "aws_glue_catalog_database" "mydb":
│    6: resource "aws_glue_catalog_database" "mydb" {
│ 
╵
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

I tried changing version of the AWS provider as suggested in #9503 but without success. Could it be a problem for M1?
### References

Similar to: #9503  & #16069

**Comment by justinretzolk** [comment]
Hey @mgermy 👋 I attempted to reproduce this (for what it's worth, also on an M1 based Mac), using the same AWS Provider version, and have not been able to do so. In this case, the (redacted as necessary) debug logs may be particularly useful. Is that something you're able to provide?

**Comment by bschaatsbergen** [comment]
By looking at the CreateDataBaseInput coming from the SDK only the name is required, we seem to reflect this properly in our scheme for glue databases too.

```
type CreateDatabaseInput struct {
	_ struct{} `type:"structure"`

	// The ID of the Data Catalog in which to create the database. If none is provided,
	// the Amazon Web Services account ID is used by default.
	CatalogId *string `min:"1" type:"string"`

	// The metadata for the database.
	//
	// DatabaseInput is a required field
	DatabaseInput *DatabaseInput `type:"structure" required:"true"`
}
```

Note the comment on the `CatalogId`

> " If none is provided, the Amazon Web Services account ID is used by default."

**Comment by mgermy** [comment]
Hi @justinretzolk! Thanks a lot for trying to reproduce it. I investigated it a bit deeper and realized that I was running these scripts on localstack. When I tried to create the db with my regular AWS credentials everything worked fine. I'm closing this issue since it's not a problem with terraform itself, but localstack. Again, thanks a lot!
