### ISSUE TITLE
error creating RDS cluster: InvalidParametersValue: The engine mode serverless you requested is currently unavailable.

### ISSUE THREAD

**Issue by aroseca15** [hashicorp/terraform-provider-aws#23762]
I have gone over and compared my terraform code over and over I cannot see where I went wrong in the engine_mode params. I checked my region vars to make sure they were set and they are. In face, terraform works perfectly in my other configs so far. I check the availability region lists on aws aurora serverless postgresql, my default region was added for serverless postgresql as of 2019. Lastly, I used two commands to check the serverless engines available. One command gave my a list of engine versions available for my region. The other returned empty arrays for every region I put in. I am at a loss, are there any ideas? I need postgres aurora and I need it to be serverless. Any help would be greatly appreciated. I will add screenshots of the error and command responses. Also, here is a snippet of the db config: 

resource "aws_rds_cluster" "default" {
  cluster_identifier = "aurora-cluster-${local.prefix}-db"
  database_name      = "aurora-db"
  engine             = "aurora-postgresql"
  engine_mode        = "serverless"
  engine_version     = "13.4"

  db_subnet_group_name    = aws_db_subnet_group.main.name
  master_username         = var.db_username
  master_password         = var.db_password
  storage_encrypted       = true
  kms_key_id              = aws_kms_key.kms-key.arn
  backup_retention_period = 7
  preferred_backup_window = "01:00-03:00"
  backtrack_window        = 0
  deletion_protection    = false
  skip_final_snapshot    = true
  vpc_security_group_ids = [aws_security_group.rds.id]

  scaling_configuration {
    auto_pause               = true
    min_capacity             = 2
    max_capacity             = 384
    seconds_until_auto_pause = 300
    timeout_action           = "ForceApplyCapacityChange"
  }

  tags = merge(
    local.common_tags,
    tomap({ "Name" = "${local.prefix}-main" })
  )
}
![Quick Idea](https://user-images.githubusercontent.com/69179642/159107281-5b9e2e19-8eae-4189-a600-b87dae60f950.JPG)
![One command says](https://user-images.githubusercontent.com/69179642/159107286-e4818aca-dc1a-40bc-afb6-5d8a5d99ba4c.JPG)
![Other command says](https://user-images.githubusercontent.com/69179642/159107289-925dd43f-6b17-43c3-938d-6497230cba81.JPG)

**Comment by md5** [comment]
Aurora Serverless v1 apparently doesn't support a PostgreSQL 13 mode, only PostgreSQL 10.12 (assuming the documentation is up-to-date): https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Concepts.AuroraFeaturesRegionsDBEngines.grids.html#Concepts.Aurora_Fea_Regions_DB-eng.Feature.Serverless

**Comment by justinretzolk** [comment]
Hey @aroseca15 👋 As @md5 mentioned above, it looks like this is related to the `engine_version` you're passing. In addition to the linked document above, the following variation on the command you were using returns only `10.14` (I built this call using the syntax described [here](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/rds/describe-db-engine-versions.html)):

```shell
$ aws rds describe-db-engine-versions --engine aurora-postgresql --filters Name=engine-mode,Values=serverless --output text --query "DBEngineVersions[].EngineVersion"
```

**Comment by aroseca15** [comment]
Hi @justinretzolk,
 Yes, I see that it returns that for you. However, the command returned something different for me.

**Comment by aroseca15** [comment]
@md5 @justinretzolk, There is one more thing I am confused with. When I create an aurora-postgresql 3.14 db on the aws platform manually it allows me to check off auto scaling. My assumption for the docs that I was given by @md5  is that they are not serverless. If this is true, then how is it possible to reflect the auto scale option in terraform for a non-serverless aurora-postgresql 3.14 db? The scaling config found in the docs for terraform, for aws_rds_cluster, are only for serverless.   

I very much appreciate the help. Looking forward to hearing from you.

**Comment by md5** [comment]
@aroseca15 the command you ran in the screenshot was missing the `--filters` argument that @justinretzolk included. If you look closely at your output, you'll see that 10.14 is listed twice, once for `serverless` and once for `provisioned` (which you could see by changing to `--query DBEngineVersions[].[EngineVersion, SupportedEngineModes]`).

As for what you're seeing with auto-scaling, I can't say for sure what the issue is, but I don't think it indicates that `serverless` is compatible with versions other than 10.14.

**Comment by aroseca15** [comment]
@md5 Thank you for pointing the filters out. That was not clearly explained on the AWS docs. Lastly, I am looking to make a provisioned aurora postgres db auto scalable similar to what the serverless auto scale does. The read replicas help but it is a different concept from auto scale. How can this be accomplished?

**Comment by md5** [comment]
@aroseca15 I'm afraid your question is a bit of scope for this issue tracker

**Comment by md5** [comment]
@aroseca15 the question you have about how to configure your database is an AWS question, not a Hashicorp question.

**Comment by aroseca15** [comment]
@md5 Very well, I will speak to them too. I was referring to the terraform config for something like that.

**Comment by aroseca15** [comment]
@md5 I'm happy to take your advice. I am just very interested in creating my own config with terraform. I will put my question/request for information on this wherever you see fit.

**Comment by md5** [comment]
@aroseca15 you probably want to have a look at this: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appautoscaling_policy#aurora-read-replica-autoscaling

**Comment by aroseca15** [comment]
@md5 Great, I will look at that again. Thank you :)

**Comment by md5** [comment]
If you get stuck, this module seems to cover most of what you'd want for this scenario: https://registry.terraform.io/modules/cloudposse/rds-cluster/aws/0.21.0

You could either try using it directly or have a look at the internals to see how it works

**Comment by aroseca15** [comment]
Awesome! Thank you again!

**Comment by justinretzolk** [comment]
Hey @aroseca15 👋 I know this issue is closed out already, but I wanted to take a moment to mention the [AWS Provider Discuss Forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) -- that would be a perfect place to ask for help with additional questions that might be a bit out of scope for the issue tracker, if you're still looking! 🙂

**Comment by aroseca15** [comment]
@justinretzolk Awesome! Thank you, I check this out. 😃
