### ISSUE TITLE
aws_launch_template no longer setting device_index=0 on network_interface

### ISSUE THREAD

**Issue by fcheung** [hashicorp/terraform-provider-aws#23766]
As of 4.6.0 creating a launch template seems to result in a network interface with no device index

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.6.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
```
### Affected Resource(s)

* aws_launch_template

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {}

terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "4.6.0"
    }
  }
  required_version = "~> 1.1.7"
}


resource "aws_launch_template" "this" {
  name_prefix = "test"

  network_interfaces {
    security_groups             = []
    delete_on_termination       = true
  }
}
```

### Expected Behavior

A launch template should be created with a network interface that has a device index of 0. This is the behaviour observed with version 4.5.0 of the provider. 

<img width="1457" alt="Screenshot 2022-03-19 at 20 30 24" src="https://user-images.githubusercontent.com/5927/159137825-b303a8bc-31a1-4426-8727-7905043a45fc.png">

### Actual Behavior

A launch template is created but the network interface has no device index. Trying to associate such a launch template with an autoscaling group ( : Incompatible launch template: Each network interface requires a unique device index. )

<img width="1449" alt="Screenshot 2022-03-19 at 20 33 54" src="https://user-images.githubusercontent.com/5927/159137821-2c7910af-3538-4cd1-8360-448758365458.png">

### Steps to Reproduce

1. `terraform apply`

### References

This seems like a regression of #4475 . It looks like commit a4cebe51 in #23365 reinstated a check that device index is not 0: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ec2/launch_template.go#L1432

**Comment by vara-bonthu** [comment]
I have hit the same issue today with the latest provider version

**Comment by yanivomc** [comment]
same here and solved by going back to 4.5

**Comment by bschaatsbergen** [comment]
Checking this out

**Comment by mperalta-1988** [comment]
I have the same issue from my side :/. I have issues creating autoscaling groups when the launch template doesn't have the device index assigned

**Comment by DmytroMorhulDevPro** [comment]
@mperalta-1988 
 ```
terraform {
  required_providers {
    aws = {
      version = "4.5.0"
    }
  }
}
```
Going back to 4.5.0 wil fix the issue

**Comment by Whimby** [comment]
4.6 more like 4.miss

**Comment by marek-obuchowicz** [comment]
I see that 4.7.0 and 4.8.0 should have fix for this issue, however it seems that a launch template created by 4.6.0 affected by bug is still used. I've used 4.6.0 which created launch template v10, then failed to assign it to autoscaling group because of missing device index. Now version 4.8.0 fails with the same problem:

```
aws_autoscaling_group.nodes-k1-lekkerland-cdbd-c-korekontrol-net: Modifying... [id=nodes.k1.lekkerland-cdbd.c.korekontrol.net]
aws_launch_template.master-eu-central-1a-masters-k1-lekkerland-cdbd-c-korekontrol-net: Modifying... [id=lt-03ed47bf77717844b]
aws_launch_template.master-eu-central-1c-masters-k1-lekkerland-cdbd-c-korekontrol-net: Modifying... [id=lt-04eb5c11201cb2804]
aws_launch_template.master-eu-central-1b-masters-k1-lekkerland-cdbd-c-korekontrol-net: Modifying... [id=lt-0d8787290a4572b22]
aws_launch_template.master-eu-central-1a-masters-k1-lekkerland-cdbd-c-korekontrol-net: Modifications complete after 0s [id=lt-03ed47bf77717844b]
aws_launch_template.master-eu-central-1c-masters-k1-lekkerland-cdbd-c-korekontrol-net: Modifications complete after 0s [id=lt-04eb5c11201cb2804]
aws_autoscaling_group.master-eu-central-1a-masters-k1-lekkerland-cdbd-c-korekontrol-net: Modifying... [id=master-eu-central-1a.masters.k1.lekkerland-cdbd.c.korekontrol.net]
aws_autoscaling_group.master-eu-central-1c-masters-k1-lekkerland-cdbd-c-korekontrol-net: Modifying... [id=master-eu-central-1c.masters.k1.lekkerland-cdbd.c.korekontrol.net]
aws_launch_template.master-eu-central-1b-masters-k1-lekkerland-cdbd-c-korekontrol-net: Modifications complete after 0s [id=lt-0d8787290a4572b22]
aws_autoscaling_group.master-eu-central-1b-masters-k1-lekkerland-cdbd-c-korekontrol-net: Modifying... [id=master-eu-central-1b.masters.k1.lekkerland-cdbd.c.korekontrol.net]

Error: Error updating Auto Scaling Group: InvalidQueryParameter: Incompatible launch template: Each network interface requires a unique device index.
	status code: 400, request id: fa01aa64-1f4a-4df5-9fe6-dcd0bc8d9174

  on kubernetes.tf line 198, in resource "aws_autoscaling_group" "master-eu-central-1a-masters-k1-lekkerland-cdbd-c-korekontrol-net":
 198: resource "aws_autoscaling_group" "master-eu-central-1a-masters-k1-lekkerland-cdbd-c-korekontrol-net" {
 ```

and I see in AWS console, that for mentioned `aws_autoscaling_group` the last created version is on Mar 22 (when I was using 4.5.0). It seems that 4.8.0 for some reason didn't create new launch template versions and recognises those incorrect ones as latest.
