### ISSUE TITLE
Data source for aws_s3_account_public_access_block

### ISSUE THREAD

**Issue by gingersnapz** [hashicorp/terraform-provider-aws#23783]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A data source type for aws_s3_account_public_access_block that will return the current public block settings for the account in order to make dynamic decisions against access blocks of individual buckets.

### New or Affected Resource(s)

* aws_s3_account_public_access_block

### Potential Terraform Configuration

```hcl
data "aws_s3_account_public_access_block" "current_settings" {}
```

### References

* #0000

**Comment by sasidhar-aws** [comment]
I’ll be picking this one up.
