### ISSUE TITLE
AWS Client VPN Resource Timeouts are too low

### ISSUE THREAD

**Issue by jalavoy** [hashicorp/terraform-provider-aws#23787]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform: 1.1.7
AWS Provider Version: 4.5.0

### Affected Resource(s)

* aws_ec2_client_vpn_authorization_rule
* aws_ec2_client_vpn_route

### Terraform Configuration Files

```hcl
resource "aws_ec2_client_vpn_authorization_rule" "remote" {
  for_each               = { for role in local.roles : "${role.role}-${role.cidr}" => role }
  client_vpn_endpoint_id = aws_ec2_client_vpn_endpoint.vpn.id
  target_network_cidr    = each.value.cidr
  access_group_id        = each.value.role
  description            = "${each.value.role}-${each.value.cidr}"
}

resource "aws_ec2_client_vpn_route" "route_1" {
  for_each               = toset(var.peer_cidrs)
  client_vpn_endpoint_id = aws_ec2_client_vpn_endpoint.vpn.id
  destination_cidr_block = each.value
  target_vpc_subnet_id   = tolist(module.base_infrastructure_state.private_subnet_ids)[0]
}
```

### Expected Behavior

Resources would be created/deleted cleanly. Timeout needs to be raised on these resources to 2 minutes or more. This can be done in hcl, but the default should be increased.

### Actual Behavior

The timeout on these resources is hard coded to 1m. In my tests, creating and destroying these resources can take anywhere from 50-75 seconds. So about half the time the transaction fails. Which results in tainted resources that have to be destroyed and created again. When you have a number of routes/auth rules, this basically can never complete successfully.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Raising this value with the `timeouts` metadata block to 2m solved this issue for me.

* #0000

**Comment by nitrocode** [comment]
Previous possibly related issues

* https://github.com/hashicorp/terraform-provider-aws/issues/15680
* https://github.com/hashicorp/terraform-provider-aws/issues/19750

**Comment by asaf400** [comment]
https://github.com/hashicorp/terraform-provider-aws/pull/30552
