### ISSUE TITLE
Support protobuf for aws_glue_schema

### ISSUE THREAD

**Issue by mdimas** [hashicorp/terraform-provider-aws#23811]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Glue Schema Registry added support for Protocol Buffer schemas in February 2022. It would be great if the terraform resource could add support as well.

### New or Affected Resource(s)

* aws_glue_schema

### References

* https://aws.amazon.com/about-aws/whats-new/2022/02/aws-glue-schema-registry-protocol-buffers/

**Comment by bschaatsbergen** [comment]
I'm pretty sure that `data_format` already accepts `PROTOBUF` as a value by judging from the source code. I'll test it out for you and get back to you.

**Comment by mdimas** [comment]
Sorry, I should have dug into the source or tried it. I was just going off the documentation.

**Comment by bschaatsbergen** [comment]
All good, happy to help!
I'll update the documentation accordingly, thanks for raising awareness.

**Comment by bschaatsbergen** [comment]
@mdimas, a Protobuf example schema definition is as following: 

```terraform
resource "aws_glue_schema" "example" {
  schema_name       = "example"
  registry_arn      = aws_glue_registry.test.arn
  data_format       = "PROTOBUF"
  compatibility     = "NONE"
  schema_definition = "syntax = \"proto2\";\n\npackage tutorial;\n\noption java_multiple_files = true;\noption java_package = \"com.example.tutorial.protos\";\noption java_outer_classname = \"AddressBookProtos\";\n\nmessage Person {\n  optional string name = 1;\n  optional int32 id = 2;\n  optional string email = 3;\n\n  enum PhoneType {\n    MOBILE = 0;\n    HOME = 1;\n    WORK = 2;\n  }\n\n  message PhoneNumber {\n    optional string number = 1;\n    optional PhoneType type = 2 [default = HOME];\n  }\n\n  repeated PhoneNumber phones = 4;\n}\n\nmessage AddressBook {\n  repeated Person people = 1;\n}""
}
```

**Comment by mdimas** [comment]
Thanks for the quick response!
