### ISSUE TITLE
Intra-Region Peering seems not to work for TGW

### ISSUE THREAD

**Issue by kapi76** [hashicorp/terraform-provider-aws#23828]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

`aws_ec2_transit_gateway_peering_attachment`

* aws_v4.2.0

### Terraform Configuration Files

```hcl
resource "aws_ec2_transit_gateway_peering_attachment" "tgw-controltower-peering-attachment" {
   provider                           = aws.aws-shared-network-virginia
   peer_account_id    = var.controltower_account_id
   transit_gateway_id = aws_ec2_transit_gateway.central-tgw-virginia-prod-01.id
   peer_transit_gateway_id = aws_ec2_transit_gateway.central-tgw-virginia-dev-controltower.id
   peer_region        = var.virginiaregion
}


resource "aws_ec2_transit_gateway_peering_attachment_accepter" "accept-peer-in-ctower" {
  provider                           = aws.aws-shared-network-virginia
  transit_gateway_attachment_id = aws_ec2_transit_gateway_peering_attachment.tgw-controltower-peering-attachment.id
}
```

### Debug Output

```
> terraform apply

[...]
aws_ec2_transit_gateway_peering_attachment.tgw-controltower-peering-attachment: Refreshing state... [id=tgw-attach-0b620cfc4210df426]
[...]
aws_ec2_transit_gateway_peering_attachment_accepter.accept-peer-in-ctower: Creating...
[...]

2-----------------------------------------------------: timestamp=2022-03-23T13:44:16.655+0100
2022-03-23T13:44:16.655+0100 [DEBUG] provider.terraform-provider-aws_v4.2.0_x5: [aws-sdk-go] <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Cannot accept tgw-attach-0b620cfc4210df426 as the source of the peering request.</Message></Error></Errors><RequestID>5d8cdf5a-e576-4be2-888c-1e12d5f357f4</RequestID></Response>: timestamp=2022-03-23T13:44:16.655+0100
2022-03-23T13:44:16.655+0100 [DEBUG] provider.terraform-provider-aws_v4.2.0_x5: [aws-sdk-go] DEBUG: Validate Response ec2/AcceptTransitGatewayPeeringAttachment failed, attempt 0/25, error InvalidParameterValue: Cannot accept tgw-attach-0b620cfc4210df426 as the source of the peering request.
        status code: 400, request id: 5d8cdf5a-e576-4be2-888c-1e12d5f357f4: timestamp=2022-03-23T13:44:16.655+0100
2022-03-23T13:44:16.984+0100 [DEBUG] provider.terraform-provider-aws_v4.2.0_x5: [aws-sdk-go] DEBUG: Response ec2/CreateTransitGatewayRoute Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 Bad Request
Connection: close
Transfer-Encoding: chunked
```

### Error Output

│ Error: error accepting EC2 Transit Gateway Peering Attachment: InvalidParameterValue: Cannot accept tgw-attach-0b620cfc4210df426 as the source of the peering request.
│       status code: 400, request id: 34a05039-80b5-4098-8257-d586378383a5
│
│   with aws_ec2_transit_gateway_peering_attachment_accepter.accept-peer-in-ctower,
│   on tgw.tf line 90, in resource "aws_ec2_transit_gateway_peering_attachment_accepter" "accept-peer-in-ctower":
│   90: resource "aws_ec2_transit_gateway_peering_attachment_accepter" "accept-peer-in-ctower" {
│

### Expected Behavior

tgw-attach-0b620cfc4210df426 (aws_ec2_transit_gateway_peering_attachment.tgw-controltower-peering-attachment) as the source of the peering request should be accepted. 

### Actual Behavior

It seems intra-region peering attachments are not accepted?
https://aws.amazon.com/blogs/networking-and-content-delivery/aws-transit-gateway-now-supports-intra-region-peering/#:~:text=Intra%2Dregion%20peering%20allows%20direct,infrastructure%20more%20efficiently%20and%20securely.

**Comment by paullemon** [comment]
Can this be fixed in latest provider 3.x as well?  I'm getting a similar error with intra region peering between accounts using 3.75.1.

**Comment by bigmikes** [comment]
Taking a look.

**Comment by bigmikes** [comment]
You are missing a piece of configuration. The TGW Peering Attachment creates two attachment resources, i.e. the local and peer attachments, which have different IDs. The Attachment Acceptor needs to be configured with the peer attachment's ID, not the local attachment's. 

To find the peer attachment you need to use a data source. Try the below. 

```terraform
resource "aws_ec2_transit_gateway_peering_attachment" "example_source_peering" {
  peer_region             = var.aws_region
  transit_gateway_id      = aws_ec2_transit_gateway.example_tgw_1.id
  peer_transit_gateway_id = aws_ec2_transit_gateway.example_tgw_2.id
  tags = {
    Name = "terraform-example"
    Side = "Creator"
  }
}

data "aws_ec2_transit_gateway_peering_attachment" "example_destination_peering_data" {
  depends_on = [aws_ec2_transit_gateway_peering_attachment.example_source_peering]
  filter {
    name   = "transit-gateway-id"
    values = [aws_ec2_transit_gateway.example_tgw_2.id]
  }
}

resource "aws_ec2_transit_gateway_peering_attachment_accepter" "example_accpeter" {
  transit_gateway_attachment_id = data.aws_ec2_transit_gateway_peering_attachment.example_destination_peering_data.id
  tags = {
    Name = "terraform-example"
    Side = "Acceptor"
  }
}
```

**Comment by karthick-ponnusamy** [comment]
Hey @bigmikes , using this data source works for the first time. But on subsequent retries, it is confusing to pick between the two attachment resources as we are only filtering by transit_gateway_id.
Please let me know if we are doing anything wrong. We followed the same approach you suggested.

**Comment by bigmikes** [comment]
Can you clarify what you mean by "on subsequent retries"?

I agree it is confusing. Today AWS API do not seem to provide a precise way to find the attachment that it gets created for intra-region peering. I'll investigate.

**Comment by geof2001** [comment]
Have had no issue with inter region peering but intra-region peering uses different attachment-id's, If you have more than a single attachment in a region you'll need to have a more precise filter to find the peering attachment's ID.   Issue i'm seeing if with multiple peering attachments from the same account with some in another region.  The in region peering connection fails if you use a tags:Name filter as the tag isn't set until after it's accepted.  You need the tags:Name filter after though to specifically ID the right attachment id after it's been accepted.  I'm not sure how to use a filter only when a tag:Key, value are set and not use that filter when it doesn't exist.  If you could also filter by region of requester and accepter that would give better results so you don't require a tag being set after the resource is created.

**Comment by jaimehrubiks** [comment]
I'm seeing the same issue. TGW peering attachment creates 2 attachment (requester and accepter), and the resource only provides the ID to the requester, which is not what the "tgw peering attachment accepter resource" needs.

The datasource doesn't work either if you have other attachments (even VPC attachments, as filtering doesn't allow you to set peering "type" according to AWS API).

**Comment by jaimehrubiks** [comment]
Uhmm I will verify this as soon as I can, but I would bet it won't work in all situations. If there are other types of attachments that reference tgw2, the data source filter won't be enough to filter out all the others and it will complain it found two or more attachments...
