### ISSUE TITLE
Missing GP3 Block type in EMR Ebs_config parameter

### ISSUE THREAD

**Issue by bollohz** [hashicorp/terraform-provider-aws#23831]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The EMR_CLUSTER resource does not have the `gp3` value as one of the possible choices inside `ebs_config` block.
AWS release for the EMR clusters the general availability of gp3 on February 2020 as describe here:

https://github.com/aws/aws-sdk/issues/29

Here is the link to Terraform docs where is missing the `gp3` as possible choice: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emr_cluster#ebs_config

### New or Affected Resource(s)

* aws_emr_cluster

### References

https://github.com/aws/aws-sdk/issues/29
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emr_cluster#ebs_config

**Comment by bschaatsbergen** [comment]
Checking this out, will pick it up.

**Comment by dacort** [comment]
Per https://github.com/aws/aws-sdk/issues/29#issuecomment-1172671844 this is now supported in the API. 

It looks like the [2022-06-29](https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2022-06-29) release of aws-sdk-go-v2 (`github.com/aws/aws-sdk-go-v2/service/emr v1.19.0`) supports this as well as the [1.44.45](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.45) v1 version.

Docs and other SDK/CLI support are still rolling out.

**Comment by bschaatsbergen** [comment]
Hi @dacort, thanks for taking the time to track this. I'll get onto it as soon as possible.
