### ISSUE TITLE
Not possible to provide "architectures" for aws_lambda_function resource 

### ISSUE THREAD

**Issue by juliandecoss** [hashicorp/terraform-provider-aws#23858]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.7  on darwin_arm64
hashicorp/aws v4.6.0

### Affected Resource(s)

Lambda- "architectures

* aws_lambda

### Terraform Configuration Files

```hcl
module "lambda_testing" {
  source = ""
  function_name = "lambda-testing"
  description   = "testing lambda"
  package_type  = "Zip"
  account = "main"
  role = "arn:aws:iam::180477243137:role/lambda-default-role"
  source_file = "./build/lambda-testing.zip"
  handler = "src.routes.login.index.handler"
  runtime = "python3.8"
  architectures = ["arm64"]
  versioning = true
  memory_size = 128
  timeout = 60
  environment = { # 'null' if you don't want to set env vars
    ENV = var.env
  }
  tags = {
    managedBy = "terraform"
  }
}
variable "env" {}

######## OUTPUTS #######
output "lambda_testing_version" {
  value = module.lambda_testing.version
}
```

### Debug Output

```plaintext
│ Error: Unsupported argument
│
│   on lambda-testing.tf line 11, in module "lambda_testing":
│   11:   architectures = ["arm64"]
│
│ An argument named "architectures" is not expected here.
```

**Comment by justinretzolk** [comment]
Hey @juliandecoss 👋 Thank you for taking the time to raise this! It looks like the error you're getting is that the module that you're calling doesn't take an `architectures` argument. This would be something that you'd need to file an issue in the repository that hosts the module to have addressed. Since this isn't an issue with the AWS Provider itself, I'll close this issue for now. If you feel I've done this in error, please do let me know.

**Comment by juliandecoss** [comment]
Sorry do you know which repository hosts this module?
