### ISSUE TITLE
Access key got printed in logs for terraform apply failure

### ISSUE THREAD

**Issue by SaiKrishnaMaddu** [hashicorp/terraform-provider-aws#23867]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.6.0

also tried on 

Terraform v1.0.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.6.0

### Affected Resource(s)

* aws_ec2 

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

https://gist.github.com/SaiKrishnaMaddu/c4e031567680370b566b4d37cae3a1a4

### Debug Output

https://gist.github.com/SaiKrishnaMaddu/4661d58ef99efad9c429d9a45a43e533

### Panic Output

N/A

### Expected Behavior

Logs should not contain credentials information or the credentials should be masked in the logs.

### Actual Behavior

Logs are printing accessKey 
```2022-03-25T10:26:39.620+0530 [DEBUG] provider.terraform-provider-aws_v4.6.0_x5: [aws-sdk-go-v2] Request
POST / HTTP/1.1
Host: sts.us-east-1.amazonaws.com
User-Agent: APN/1.0 HashiCorp/1.0 Terraform/1.1.7 (+https://www.terraform.io) terraform-provider-aws/dev (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go-v2/1.15.0 os/linux lang/go/1.17.6 md/GOOS/linux md/GOARCH/amd64 api/sts/1.16.0
Content-Length: 43
Amz-Sdk-Invocation-Id: 18598015-b084-4939-9ba7-910bfa828f86
Amz-Sdk-Request: attempt=1; max=25
Authorization: AWS4-HMAC-SHA256 Credential=AK**************/20220325/us-east-1/sts/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date, Signature=1d91b44fd17e78083122ccde853ab1a79ab6ad00b7b1aeca00fbda6b023a3737
Content-Type: application/x-www-form-urlencoded
X-Amz-Date: 20220325T045639Z
Accept-Encoding: gzip

Action=GetCallerIdentity&Version=2011-06-15: timestamp=2022-03-25T10:26:39.620+0530
2022-03-25T10:26:40.642+0530 [DEBUG] provider.terraform-provider-aws_v4.6.0_x5: [aws-sdk-go-v2] Response
HTTP/1.1 403 Forbidden
Content-Length: 306
Content-Type: text/xml
Date: Fri, 25 Mar 2022 04:56:39 GMT
X-Amzn-Requestid: b78340ce-119c-40e0-b7d6-dd4bd2137d82

<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidClientTokenId</Code>
    <Message>The security token included in the request is invalid.</Message>
  </Error>
  <RequestId>b78340ce-119c-40e0-b7d6-dd4bd2137d82</RequestId>
</ErrorResponse>: timestamp=2022-03-25T10:26:40.642+0530
```

I have masked accessKey for sharing. 

### Steps to Reproduce

1. `terraform apply`
terraform apply cmd failed with expected errors however in such a case the access key information got printed in debug logs
![terraform_apply_failure](https://user-images.githubusercontent.com/38233507/160060003-af1b9d90-89d3-49b2-a7df-e6c636b8c5af.png)

note: we have also tried with AWS_SHARED_CREDENTIALS_FILE instead of provider block as below 
location : ~/.aws/credentials
content:

```
[default]
aws_access_key_id=*****
aws_secret_access_key=*****
```

### References
N/A

* #0000

**Comment by justinretzolk** [comment]
Hey @SaiKrishnaMaddu 👋 Thank you for taking the time to raise this! Ultimately, the request/response the are being printed here come from the AWS Go SDK, so it's unclear to me at this time how we might be able to control that. That said, we have an open issue to look into some logging changes, so I'll link to it below so that these issues are linked when that work gets underway, and the team can look into this.

Possibly related: #24165
