### ISSUE TITLE
Edit route Target for local route entry on aws_route_table

### ISSUE THREAD

**Issue by rhanielborromeo** [hashicorp/terraform-provider-aws#23866]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

On the AWS UI after creating a route table a user can go back to the "local" route that gets automatically created and point it to a different route target (i.e. a vpcendpoint), as of now there is no option for Terraform to do this, and creating a route with a similar subnet gives an error: 

Terraform v0.14.11
Initializing plugins and modules...
aws_route_table.eu-nat-a: Modifying...<redacted>

Error: error creating Route in Route Table <redacted> with destination (172.30.16.0/23): RouteAlreadyExists: The route identified by 172.30.16.0/23 already exists.
	status code: 400, request id: <redacted>

  on main.tf line 765, in resource "aws_route_table" "eu-nat-a":
 765: resource "aws_route_table" "eu-nat-a" {

### New or Affected Resource(s)
aws_route_table

### Potential Terraform Configuration
  route {
    cidr_block = "172.30.16.128/25"
    vpc_endpoint_id = tolist(aws_networkfirewall_firewall.eu-fw.firewall_status[0].sync_states)[1].attachment[0].endpoint_id
  }
# Copy-paste your Terraform configurations here - for large Terraform configs,
resource "aws_route_table" "eu-nat-a" {
  provider   = aws.emeawest2
  vpc_id = aws_vpc.jbeu-c2c.id
  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.jbeu-gw-1.id
  }
  route {
    cidr_block = "172.30.16.0/23"
    vpc_endpoint_id = tolist(aws_networkfirewall_firewall.eu-c2c-fw.firewall_status[0].sync_states)[1].attachment[0].endpoint_id
  }
  tags = {
    Name = "gw-nat-a"
  }
}

### References

* #0000

**Comment by ewbankkit** [comment]
@rhanielborromeo Thanks for raising this issue.
It has already been noticed in #21350. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
