### ISSUE TITLE
Plan is waiting for resources indefinitely when in another country 

### ISSUE THREAD

**Issue by marvin-kolja** [hashicorp/terraform-provider-aws#23889]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.4
on darwin_arm64
+ provider registry.terraform.io/cookielab/postgresql v1.14.0
+ provider registry.terraform.io/hashicorp/aws v3.62.0
+ provider registry.terraform.io/hashicorp/google v3.90.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/mietz-gmbh/process v0.1.3
```

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Not complete logs but this is the last refreshing that gets it "stuck".
https://gist.github.com/marvin-kolja/9ae0916445685a6b515ecd7b01dfdf24

### Expected Behavior

That the plan finishes 😀

### Actual Behavior

**Note:** _We have everything hosted in Frankfurt._

It's waiting for some resources indefinitely. When in Germany I can run `terraform plan` and `terraform apply` without any hustle. As soon as I tried to do it from Switzerland or Namibia it doesn't work. We use a ssh tunnel to connect to our DB, so I could imagine it has something to do with that, however, it worked before.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @marvin-kolja 👋 Thank you for taking the time to raise this! To get a better idea, does this happen consistently, or does it seem to be an intermittent issue (aside from the obvious of it only occurring when away from Germany 😅)? Additionally, can you give us an idea of the end result -- does the apply eventually time out?
