### ISSUE TITLE
OpenSearch "Service software version" not recognized by aws_elasticsearch_domain resource. Unexpected downgrade on apply

### ISSUE THREAD

**Issue by babbottscott** [hashicorp/terraform-provider-aws#23881]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v1.1.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.8.0

### Affected Resource(s)

* aws_elasticsearch_domain

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Not really sure.  The "service software version" is a new feature AWS has added in the wake of the log4j vulnerability.  At minimum, expect terraform to recognize that the unpatched version should not be the desired target.  Still experimenting to isolate actual/expected behavior

### Actual Behavior

Domain is downgraded to the unpatched `elasticsearch_version`

### Steps to Reproduce

1. Confirm an aws_elasticsearch_domain has been updated to a patched `service software version`
2. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @babbottscott 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you supply the Terraform configuration(s) and (redacted as necessary) debug logs?

**Comment by marpada** [comment]
Apologies for hijacking the issue, I think the question is whether it's possible to perform a Service Software update using the aws provider, as it seems the Service Software version it's not an attribute of the ES domain but it has its own API for triggering the upgrade

https://docs.aws.amazon.com/opensearch-service/latest/developerguide/configuration-api.html#configuration-api-actions-startupdate
