### ISSUE TITLE
aws_iam_role and aws_iam_role_policy not updating properly

### ISSUE THREAD

**Issue by AlexWang-16** [hashicorp/terraform-provider-aws#23894]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

* Terraform v1.1.7 on darwin_amd64
* AWS Provider 4.5.0

### Affected Resource(s)

* aws_iam_role
* aws_iam_role_policy 

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_iam_role" "glue_etl" {
  name = var.glue_etl_role_name
  description = "A role used by AWS Glue service to execute glue jobs and connect to redshift cluster."

  assume_role_policy = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Effect" : "Allow",
        "Principal" : {
          "Service" : "glue.amazonaws.com"
        },
        "Action" : "sts:AssumeRole"
      }
    ]
  })
}

resource "aws_iam_role_policy" "this" {
  name = "glue-connection-secrets-access"
  role = aws_iam_role.glue_etl.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid = "AllowSecretsManagerAccess"
        Action = [
          "secretsmanager:GetSecretValue"
        ]
        Effect = "Allow"
        Resource = [
          module.connection_properties_credential.secret_arn
        ]
      }
    ]
  })

  depends_on = [
    module.connection_properties_credential,
  ]
}```

### Debug Output
<!---
Please provide a link to a GitHub Gist containing the complete debug output. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

To obtain the debug output, see the [Terraform documentation on debugging](https://www.terraform.io/docs/internals/debugging.html).
--->

No Debug Output needed as Terraform faithfully completes the action. 
It shows that the resource has changed successfully. Performing a 
`terraform plan -refresh-only` shows that the state is up to date with 
the current AWS environment.

### Expected Behavior
<!--- What should have happened? --->
The iam role description and iam role inline policy should have been updated.

### Actual Behavior
<!--- What actually happened? --->
The description in iam role was not added and iam policy changes no reflected.

### Steps to Reproduce
<!--- Please list the steps required to reproduce the issue. --->
1. Make changes in terraform code base
2. `terraform plan -out plan`
3. `terraform apply plan`

**Comment by justinretzolk** [comment]
Hey @AlexWang-16 👋 Thank you for taking the time to raise this! Can you give an idea of what values were changed in the configuration? Based on your description of the issue, it sounds like you updated the `aws_iam_role.glue_etl.description`, but it sounds like you were also updating something within `aws_iam_role_policy.this` that wasn't described here.

In this case, debug logs may still wind up being necessary, but if that's a trickier thing for you to provide, we can start with the above information and go from there.

**Comment by AlexWang-16** [comment]
Hi @justinretzolk, let me provide a new example as divulging in the details of the previous one relates to something I'm working on for my employer.

```
resource aws_iam_role "this" {
  name = "test-iam-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = "sts:AssumeRole"
        Principal = {
          Service = "ec2.amazonaws.com"
        }
      }
    ]
  })
}

resource aws_iam_role_policy "this" {
  name = "test-policy"

  role = aws_iam_role.this.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
         "s3:GetObject",
        ]
        Resource = "*"
      }
    ]
  })
}
```

# Steps To Reproduce
1. Create this test IAM role and iam_role_policy using the script above.
2. Change the action of the iam_role_policy by adding "s3:PutObject" as an additional action.
3. Perform `terraform plan` and `terraform apply` as normal.
4. Verify in AWS that the inline policy of test-iam-role has not changed.

**Comment by justinretzolk** [comment]
Hey @AlexWang-16 👋 Thank you for supplying that reproduction configuration. I went through the reproduction steps that you mentioned, and while it did take a couple of minutes for `s3:PutObject` to show up in the policy in the console, I did eventually see it appear. Is it possible the the configuration applied as expected, but you checked the console before the update had a chance to appear?

**Comment by AlexWang-16** [comment]
Thanks for raising this point. You're probably right in that IAM service may take some time to update. I will close this issue.
