### ISSUE TITLE
Cloudwatch Synthetic Canaries - pageLoadBlueprint.handler

### ISSUE THREAD

**Issue by marianafalcho** [hashicorp/terraform-provider-aws#23907]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.6.0
```

### Affected Resource(s)

* aws_synthetics_canary

### Terraform Configuration Files

```hcl
resource "aws_synthetics_canary" "synthetic_canaries_test" {
  name = "testmariana"
  artifact_s3_location = "s3://test-cwsync/"
  execution_role_arn   = "arn:aws:iam::xxxxxxxx:role/CloudWatchSyntheticCanariesRole"
  handler              = "pageLoadBlueprint.handler"
  runtime_version      = "syn-nodejs-puppeteer-3.4"
  success_retention_period = "31"
  failure_retention_period = "31"
  start_canary =true
  
  vpc_config {
      subnet_ids = local.private_ds_subnets
      security_group_ids = local.default_security_group
    
  } 
  schedule {
    expression = "rate(5 minutes)"
  }
}
```

### Expected Behavior

Creation of cloudwatch syntetic canaries

### Actual Behavior

Terraform plan produces the expected behavior but `terraform  apply` throughs an error.

### Steps to Reproduce

1. `terraform apply`

```plaintext
Terraform will perform the following actions:

  # aws_synthetics_canary.synthetic_canaries_test will be created
  + resource "aws_synthetics_canary" "synthetic_canaries_test" {
      + arn                      = (known after apply)
      + artifact_s3_location     = "s3://test-cwsync/"
      + engine_arn               = (known after apply)
      + execution_role_arn       = "arn:aws:iam::xxxxxxxx:role/CloudWatchSyntheticCanariesRole"
      + failure_retention_period = 31
      + handler                  = "pageLoadBlueprint.handler"
      + id                       = (known after apply)
      + name                     = "testmariana"
      + runtime_version          = "syn-nodejs-puppeteer-3.4"
      + source_location_arn      = (known after apply)
      + start_canary             = true
      + status                   = (known after apply)
      + success_retention_period = 31
      + tags_all                 = {
          + "Source" = "ManagedByTerraform"
        }
      + timeline                 = (known after apply)

      + run_config {
          + active_tracing        = (known after apply)
          + environment_variables = (known after apply)
          + memory_in_mb          = (known after apply)
          + timeout_in_seconds    = (known after apply)
        }

      + schedule {
          + expression = "rate(5 minutes)"
        }

      + vpc_config {
          + security_group_ids = [
              + "sg-xxxxx",
            ]
          + subnet_ids         = [
              + "subnet-xxxxx",
              + "subnet-xxxxxx,
            ]
          + vpc_id             = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_synthetics_canary.synthetic_canaries_test: Creating...
╷
│ Error: error creating Synthetics Canary (testmariana): InvalidParameter: 2 validation error(s) found.
│ - minimum field size of 1, CreateCanaryInput.Code.S3Bucket.
│ - minimum field size of 1, CreateCanaryInput.Code.S3Key.
│ 
│ 
│   with aws_synthetics_canary.synthetic_canaries_test,
│   on main.tf line 8, in resource "aws_synthetics_canary" "synthetic_canaries_test":
│    8: resource "aws_synthetics_canary" "synthetic_canaries_test" {
│ 
╵
```

### Important Factoids

- Nothing weird in our environment. 
- I am under the impression that there is no real support for pageLoadBlueprint.handler. To terraform this I ended up importing to the state file, my canaries.
- Also, looks like we are missing a feature to add alarms in this resource.

**Comment by marianafalcho** [comment]
I addition, this feature needs an endpoint and there was no option to added it.

**Comment by justinretzolk** [comment]
Hey @marianafalcho 👋 Thank you for taking the time to raise this! I took a look over the API Documentation for [`CreateCanary`](https://docs.aws.amazon.com/AmazonSynthetics/latest/APIReference/API_CreateCanary.html), which states that it requires a [`Code`](https://docs.aws.amazon.com/AmazonSynthetics/latest/APIReference/API_CanaryCodeInput.html) block.

Terraform adds this block to the input it ultimately passes to the `CreateCanary` call [here](https://github.com/hashicorp/terraform-provider-aws/blob/e9a4de60518064511fd15376a5042caca42cdc8a/internal/service/synthetics/canary.go#L273-L277), by using a helper function that is defined [here](https://github.com/hashicorp/terraform-provider-aws/blob/e9a4de60518064511fd15376a5042caca42cdc8a/internal/service/synthetics/canary.go#L573-L596).

Based on my read of these things, you must set _either_ `zip_file` _or_ `s3_bucket`, `s3_key`, and `s3_version` in order to successfully apply. Can you try setting one of these groups of arguments to verify that this clears up the issues you ran into during apply?

Note: I'm planning to leave this open as an enhancement, as I would expect that if neither of these groups of arguments are passed, that an error is thrown during plan time.

**Comment by marianafalcho** [comment]
Hi @justinretzolk!
Thanks for responding. 

Reading the description on the documentation, it says:
```
[s3_key]- (Optional) S3 key of your script. 
[s3_version]- (Optional) S3 version ID of your script. 
```
What script it is referring to?

Also, I am using this to monitor an api endpoint. There is no argument to add the endpoint. Where should I add it? In addition, where do you configure alarms?

**Comment by marianafalcho** [comment]
Hi @justinretzolk,

I figured it out. I was missing:
```
dimensions = {
    CanaryName = "NAME_OF_CANARY"
  }
```

Thanks!
