### ISSUE TITLE
Allow filter in data.aws_s3_bucket

### ISSUE THREAD

**Issue by jlosito** [hashicorp/terraform-provider-aws#23905]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like the ability to lookup S3 buckets based on tags, similar to how one can using data.aws_vpc.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/vpc#filter

### New or Affected Resource(s)

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/s3_bucket
* data.aws_s3_bucket

**Comment by simonweil** [comment]
This is still a missing feature... Can it be reopened?
