### ISSUE TITLE
Feature: Enable/Disable SagemakerServicecatalogPortfolio

### ISSUE THREAD

**Issue by ndewijer** [hashicorp/terraform-provider-aws#23917]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In certain scenarios where a SageMaker domain and users are created fully via Terraform where notebook sharing is enabled, the users it provisions fail to fully initialise. The user profile is created and terraform succeeds but in the AWS console, its status will be "Failed."

The used resources are: 
* aws_sagemaker_domain
* aws_sagemaker_user_profile

This is due to a missing imported AWS Service Catalog Portfolio. When the domain gets setup by hand via the console, this portfolio is imported in the background but this is not done via the Terraform resources.

There are two API's to enable and disable the portfolio which are:
https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_EnableSagemakerServicecatalogPortfolio.html
https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_DisableSagemakerServicecatalogPortfolio.html

So a workaround is in place by using a local-exec and using the aws cli with the following commands:
aws sagemaker enable-sagemaker-servicecatalog-portfolio --region $region
aws sagemaker disable-sagemaker-servicecatalog-portfolio --region $region

To make the provider more complete, we should be able to do this with native resources in the provider. 

this could be done by adding it as an option within aws_sagemaker_domain or as a seperate resource called aws_sagemaker_servicecatalog_portfolio (as example)

### New or Affected Resource(s)

Option A: 
* aws_sagemaker_servicecatalog_portfolio

Option B: 
* aws_sagemaker_domain

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sagemaker/enable-sagemaker-servicecatalog-portfolio.html
* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sagemaker/disable-sagemaker-servicecatalog-portfolio.html
* #0000

**Comment by dod38fr** [comment]
In my case, I also need to associate principal with the portfolio. E.g.:

```python
    response = sc_client.associate_principal_with_portfolio(
        PortfolioId=portfolio_id,
        PrincipalARN=STUDIO_ROLE_ARN,
        PrincipalType='IAM'
    )

```

I don't know if this should be handled with this ticket or if another ticket is needed.
