### ISSUE TITLE
docs/aws_glue_catalog_table: Add note about `partition_index`

### ISSUE THREAD

**Issue by anGie44** [hashicorp/terraform-provider-aws#23929]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* Add note about destroy/create behavior and/or add note to point users to the independent `aws_glue_partition_index` resource

### Reference

* https://discuss.hashicorp.com/t/adding-partition-index-block-to-aws-glue-catalog-table-resource-destroys-the-table-instead-of-updating-in-place/36932

**Comment by AdamJCavanaugh** [comment]
I'll work at the documentation update from the reference.

**Comment by anGie44** [comment]
Thanks @AdamJCavanaugh
