### ISSUE TITLE
documentation: meaning of protect_from_scale_in

### ISSUE THREAD

**Issue by FlorinAndrei** [hashicorp/terraform-provider-aws#23926]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

This page...

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group

...has this definition:

_[protect_from_scale_in](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#protect_from_scale_in) (Optional) Allows setting instance protection. The Auto Scaling Group will not select instances with this setting for termination during scale in events._

That is not correct. It does not "allow setting instance protection". What it actually does is - it enables scale-in protection on all new instances created by the cluster. All new instances that come up have scale-in protection enabled automatically.

The AWS Console has a better definition for the same thing:

_If protect from scale in is enabled, newly launched instances will be protected from scale in by default._

Also see here:

https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-instance-protection.html?icmpid=docs_ec2as_help_panel

Please change the doc, it is misleading right now.

**Comment by mattburgess** [comment]
How about something like this, directly from the [AWS SDK docs](https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#CreateAutoScalingGroupInput):

> Indicates whether newly launched instances are protected from termination
> by Amazon EC2 Auto Scaling when scaling in. For more information about preventing
> instances from terminating on scale in, see Using instance scale-in protection
> (https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-instance-protection.html)
> in the Amazon EC2 Auto Scaling User Guide.

If you're happy with that, I'll prepare the PR.

**Comment by FlorinAndrei** [comment]
I would only add one word: "Indicates whether newly launched instances are **automatically** protected from termination". That's what threw me off - the fact that the flag is set automatically for each new instance, and it took a while to figure out why.

Other than that, it sounds great.
