### ISSUE TITLE
Error: Provider produced inconsistent final plan - invalid new value for .rule: planned set element

### ISSUE THREAD

**Issue by joegajeckyj-ecs** [hashicorp/terraform-provider-aws#23936]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.8.0
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/local v2.2.2
+ provider registry.terraform.io/hashicorp/null v3.1.1

### 

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

### Actual Behavior

│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.wafv2-acl[0].aws_wafv2_web_acl.acl to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an
│ invalid new value for .rule: planned set element
...
does not correlate with any element in actual.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

When I add the "version" value to the .rule i can get most of the managed rules to update, however one particular AWS managed rule set which has no "Version" value the error happens "AWSManagedRulesAmazonIpReputationList"

I have tried with "Default" set as version value but the resource is not found

### References

Reason for trying to fix with adding the undocumented value "version" was found following related article https://github.com/hashicorp/terraform-provider-aws/pull/21732

* #0000

**Comment by vinoth-nus** [comment]
Workaround: 
Since the issue is experienced only when there is a change in wafv2 acl config, the new resource creation doesnt have the issue.
As a workaround you can delete the WAFv2 ACL manually using the AWS console or CLI and re-run terraform to create the acl again with the respective tags as you need

**Comment by tgip-work** [comment]
Also for Terraform AWS Provider 4.15.1

**Comment by janeklb** [comment]
Also for
```
Terraform v1.0.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.18.0
```
