### ISSUE TITLE
aws_eks_identity_provider_config: Blocks of type "timeouts" are not expected here

### ISSUE THREAD

**Issue by timblaktu** [hashicorp/terraform-provider-aws#23935]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.7
on linux_amd64
```

We're using providers.tf:

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.7.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.8.0"
    }
  }
}

provider "aws" {
  region = var.account_config.region.name
}

provider "kubernetes" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)

  exec {
    api_version = "client.authentication.k8s.io/v1alpha1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", local.cluster_name]
  }
}
```

### Affected Resource(s)

aws_eks_identity_provider_config

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

My resource declaration looks like this:

```hcl
resource "aws_eks_identity_provider_config" "okta" {
  cluster_name = module.eks.cluster_id

  oidc {
    client_id = "*****"
    # This appears in this cluster's list of identity providers, so doesn't need differentiation
    identity_provider_config_name = "okta"
    issuer_url                    = "*****"
    # As described here: https://developer.okta.com/blog/2021/10/08/secure-access-to-aws-eks#add-okta-as-an-oidc-provider-on-your-eks-cluster
    # We must use the following values for Okta integration.
    username_claim = "email"
    groups_claim   = "groups"
    # Resource creation takes about 30 minutes, but destroy/disassociation sometimes times out at 40 minutes.
    # The Create/Destroy timeouts each default to 40 minutes:
    #   https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_identity_provider_config#timeouts
    timeouts {
      create = "60m"
      delete = "60m"
    }
  }
}
```

### Expected Behavior

The `aws_eks_identity_provider_config` resource declaration should expect and accept a `timeouts {}` block [as documented](https://registry.terraform.io/providers/hashicorp/aws/4.7.0/docs/resources/eks_identity_provider_config#timeouts):

### Actual Behavior

Using v4.7.0 (and v4.8.0) of aws provider, both `terraform validate` and `terraform apply` produce an error when there is a timeout block in an `aws_eks_identity_provider_config` resource, which [is documented to be supported for these versions](https://registry.terraform.io/providers/hashicorp/aws/4.7.0/docs/resources/eks_identity_provider_config#timeouts):

```
│ Error: Unsupported block type
│ 
│   on okta.tf line 19, in resource "aws_eks_identity_provider_config" "okta":
│   19:     timeouts {
│ 
│ Blocks of type "timeouts" are not expected here.
```

### Steps to Reproduce

1. `terraform validate` or `terraform apply` a config that includes the above `aws_eks_identity_provider_config` resource config, which includes a nested `timeouts {}` block.

### References

* [This issue](https://github.com/aws/containers-roadmap/issues/1438#issuecomment-1082506039) tracks the problem that creating/destroying id providers takes a very long time. This is relevant because if that issue were fixed we would not need to customize `timeouts {}` block.

**Comment by justinretzolk** [comment]
Hey @timblaktu 👋 Thank you for taking the time to raise this! It looks like you've misplaced the `timeouts` blocks in this case -- with the example provided, you've defined the timeouts under `aws_eks_identity_provider_config.okta.oidc.timeouts`, while it should instead be in under `aws_eks_identity_provider_config.okta.timeouts`.  I copied your sample configuration, moved `timeouts` to its own block, and then was able to successfully run `terraform validate`. Can you test and verify that you see the same?

**Comment by timblaktu** [comment]
@justinretzolk thanks for the sanity check and sorry for my error! I will close this once I confirm that moving the timeouts block fixes my issue.

**Comment by timblaktu** [comment]
Yep, I'm all good. Thanks again!
