### ISSUE TITLE
Close Organization Account on Deletion 

### ISSUE THREAD

**Issue by danquack** [hashicorp/terraform-provider-aws#23930]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Accounts can now be deleted as a matter of closing accounts. https://github.com/aws/aws-sdk-go/pull/4338

Currently accounts are just [removed from the org](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/organizations/account.go#L279-L281). With the new API they can be deleted.

### New or Affected Resource(s)

* aws_organizations_account

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2022/03/aws-organizations-central-account-closure-lifecycle-management/).
[Blog post](https://aws.amazon.com/blogs/mt/aws-organizations-now-provides-a-simple-scalable-and-more-secure-way-to-close-your-member-accounts/).

**Comment by 0x91** [comment]
please for the love of god. i've waited years for this

**Comment by uday-projectn** [comment]
it seems updating terraform aws provider to 4.9.0 is deleting the account from terraform itself. But, when I check in aws console, it is showing as suspended, not as deleted. When I click on remove, it is showing the same error again.
```

ConstraintViolationException
The member account must be configured with a valid payment method, such as a credit card.
```

**Comment by mettke** [comment]
@uday-projectn 
There is no delete account in aws. Accounts are always suspended first for 90 days and then they are deleted. That way its possible for AWS to restore an account for that given time. 

The `remove` button you mentioned does not `delete` the account but it removes it from the organization. And that's of course only possible when the account has a payment method.

In other words, if the account is marked as `suspended` after you ran `terraform destroy` with `close_on_deletion: true` then everything worked as its supposed to. Wait 90 days and it will be gone (give or take)
