### ISSUE TITLE
aws_dlm_lifecycle_policy | data lifecycle manager rules interval

### ISSUE THREAD

**Issue by abheeshtan** [hashicorp/terraform-provider-aws#23939]
Hi,

Not sure if this was reported already, but I am having trouble following page at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dlm_lifecycle_policy#interval_unit

when it comes to dlm create rule it allows only interval type to Hours. Which makes it difficult to set rules for weekly backup using terraform.

AWS allows the users to set rules for daily, weekly and cron type of interval.
Current Terraform Version

terraform version: Terraform 0.13+
provider version: 4.8.0
Use-cases

Eg:

```
resource "aws_dlm_lifecycle_policy" "example" {
description = "example DLM lifecycle policy"
execution_role_arn = aws_iam_role.dlm_lifecycle_role.arn
state = "ENABLED"

policy_details {
resource_types = ["VOLUME"]

schedule {
  name = "2 weeks of daily snapshots"

  create_rule {
    interval      = 24
    **interval_unit = "HOURS"**              # HOURS is currently the only allowed value and also the default value
    times         = ["23:45"]
  }

  retain_rule {
    count = 14
  }

  tags_to_add = {
    SnapshotCreator = "DLM"
  }

  copy_tags = false

  cross_region_copy_rule {
    target    = "us-west-2"
    encrypted = true
    cmk_arn   = aws_kms_key.dlm_cross_region_copy_cmk.arn
    copy_tags = true
    retain_rule {
      interval      = 30
      interval_unit = "DAYS"
    }
  }
}

target_tags = {
  Snapshot = "true"
}

}
}
```

Proposal

Requesting the team to add the days and cron type interval for dlm rules, helps in solving issues

**Comment by justinretzolk** [comment]
Hey @abheeshtan 👋 Thank you for taking the time to raise this! Fortunately, a PR was recently merged (#23880) that introduces (among other things) the `cron_expression` argument that you're looking for. This will be released in the next version of the provider, version `4.9.0`. With that in mind, I'll close this issue. If you feel I've done this in error, please do let me know.
