### ISSUE TITLE
Add resources for ComputeOptimizer Recommendation Preferences

### ISSUE THREAD

**Issue by chrisgilmerproj** [hashicorp/terraform-provider-aws#23945]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has a service named [AWS Compute Optimizer](https://aws.amazon.com/compute-optimizer/). It allows you to turn on enhanced infrastructure metrics for EC2 instances and Auto Scaling Groups. To do so you have to use the [AWS CLI computeoptimizer put-recommendation-preferences](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/compute-optimizer/put-recommendation-preferences.html) command or manage these preferences manually in the AWS Console. I would like to see a resource in terraform aws provider that let's me manage this.

There is already a [Golang API in the SDK for Compute Optimizer](https://aws.amazon.com/compute-optimizer/).

### New or Affected Resource(s)

* aws_computeoptimizer_recommendation_preferences

### Potential Terraform Configuration

```hcl
resource "aws_computeoptimizer_recommendation_preferences" "prefs" {
  enchanced_infrastructure_metrics = "Active" # default
  inferred_workload_types          = "Active" # default
  resource_type                    = "AutoScalingGroup"
  scope = {
    name  = "ResourceARN"
    value = aws_autoscaling_group.web.arn
  }
}
```

### References

* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/compute-optimizer/put-recommendation-preferences.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/computeoptimizer/#ComputeOptimizer.PutRecommendationPreferences
* https://aws.amazon.com/compute-optimizer/

**Comment by f0xtek** [comment]
Hello.

As per [Pull Request 27310](https://github.com/hashicorp/terraform-provider-aws/pull/27310#issuecomment-1286260229), the AWS Compute Optimizer service was added to [v4.36.0](https://github.com/hashicorp/terraform-provider-aws/blob/v4.36.0/CHANGELOG.md) of this AWS provider.

However, the change log for that release, or any releases since, don't appear to have added support for that service. The [Terraform AWS provider documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs) also does not have this service available.

Am I missing something? Or was this functionality not included in the provider?

**Comment by iangrunt** [comment]
Hello @f0xtek, I just wanted to confirm that I cannot see this functionality in the v4.57.1 provider, thank you!

**Comment by sahaqaa** [comment]
Please advice - does Terraform AWS provider supports AWS Compute Optimizer?

**Comment by nicolaei** [comment]
From what I can see in #27310, @sasidhar-aws didn't actually add any resources 🤔

The PR only adds the Compute Optimizer SDK as a dependency and configures it. The only thing present in the compute optimizer package is a README.md.

**Comment by hunttom** [comment]
I would like to try to solve this.

**Comment by hunttom** [comment]
Status update - Sorry for the delay. I've opened a PR request, I have some open questions prior to a merge with main branch.

Questions can be seen here: https://github.com/hashicorp/terraform-provider-aws/pull/35349.
