### ISSUE TITLE
aws_codebuild_project require s3_logs location to include object key prefix

### ISSUE THREAD

**Issue by thaim** [hashicorp/terraform-provider-aws#23956]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.8.0
```

### Affected Resource(s)

* aws_codebuild_project

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_codebuild_project" "example" {
  name         = "example"
  service_role = aws_iam_role.example.id
  source {
    type            = "GITHUB"
    location        = "https://github.com/mitchellh/packer.git"
    git_clone_depth = 1
  }
  artifacts {
    type = "NO_ARTIFACTS"
  }
  environment {
    compute_type = "BUILD_GENERAL1_SMALL"
    image        = "aws/codebuild/standard:1.0"
    type         = "LINUX_CONTAINER"
  }

  logs_config {
    s3_logs {
      status   = "ENABLED"
      location = "example-bucket"
    }
  }
}

resource "aws_iam_role" "example" {
  name = "example"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "codebuild.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
}
```

### Debug Output

https://gist.github.com/thaim/aaf009eaf530c19567ab0638ba722287

### Expected Behavior

able to run terraform plan

### Actual Behavior
got following error

```
$ terraform plan
╷
│ Error: "logs_config.0.s3_logs.0.location" does not match pattern ("^[a-z0-9][^/]*\\/(.+)$"): "example-bucket"
│ 
│   with aws_codebuild_project.example,
│   on codebuild.tf line 25, in resource "aws_codebuild_project" "example":
│   25:       location = "example-bucket"
│ 
╵
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

I use only bucket name for `logs_config.0.s3_logs.0.location`. When I include object key prefix such as `location = "example-bucket/log"`, I am able to run terraform plan as expected.

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @thaim 👋 Thank you for taking the time to raise this! Based on the [provider documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codebuild_project#location), it appears that the expected format for the `logs_config.0.s3_logs.0.location` argument is indeed `bucket-name/key-name`. I also confirmed this by looking over the [type definition in the AWS Go SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/codebuild/#S3LogsConfig) and the [AWS API Documentation](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_S3LogsConfig.html) for the underlying API call.

Based on these links, this seems to be working as expected. Is there something outside of this that led you to believe only passing the bucket name should work, that we may need to look into?

**Comment by thaim** [comment]
I've tried to create codebuild project using AWS management console, awscli and CloudFormation. Despite the document requires object prefix key, these tools accept request without object prefix key.
Since I've already created the codebuild project resource with other tools, it would be nice that terraform accept a resource without object prefix key.

**Comment by justinretzolk** [comment]
Hey @thaim 👋 That's interesting information, so I appreciate you presenting it! I'm going to leave this open as an enhancement with that in mind, so that we can take a look to see if perhaps a request needs to be submitted to have the AWS documentation updated, and subsequently the provider needs to be modified to allow not passing a prefix. Out of curiosity, when you've created projects with no prefix set, does it seem that AWS is automatically setting a prefix that the logs are forwarded to?

**Comment by thaim** [comment]
Any of the way(AWS management console, awscli and CloudFormation) put prefix when I create a project with no prefix.
In my project with no prefix specified, all the logs are located to the root of the S3 bucket.
