### ISSUE TITLE
aws_sagemaker_model support for ModelPackage ARN

### ISSUE THREAD

**Issue by mateuszboryn** [hashicorp/terraform-provider-aws#23968]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It is possible to create SageMaker Model with aws_sagemaker_model by specifying `image` and `model_data_url`.
However it is not possible to specify ModelPackageName (according to https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_ContainerDefinition.html#sagemaker-Type-ContainerDefinition-ModelPackageName)
Also, according to the mentioned document, image is an optional field, but in Terraform it is marked as required field.

### New or Affected Resource(s)

Resources:
* aws_sagemaker_model

### Potential Terraform Configuration

```hcl
resource "aws_sagemaker_model" "example" {
  name               = "my-model"
  execution_role_arn = aws_iam_role.example.arn

  primary_container {
    model_package = "arn:aws:sagemaker:eu-west-1:123456789:model-package/abalonemodelpackagegroup-example/2"
  }
}
```

**Comment by mateuszboryn** [comment]
Hi, I can see PR open, which is great. When can I expect merging it and appear in provider release?

**Comment by abajorat** [comment]
Hi, any chance of this being merged soon?

**Comment by daipra** [comment]
Any updates on this?

**Comment by michaelrod64** [comment]
Any updates on this?

**Comment by michaelrod64** [comment]
Also, has anyone come up with a workaround to this issue? I'd like to create an endpoint for a model with package arn:
`arn:aws:sagemaker:us-east-1:865070037744:model-package/j2-jumbo-instruct-v1-1-033-87b797db88313edf9c3851adf6fc371f`

Would rather not have to do it manually

**Comment by daipra** [comment]
I had to work around it by using a `null_resource` that calls `local-exec` with the Python script. In the Python code, there's a boto3 call to client.sagemaker.create_model() method.

**Comment by michaelrod64** [comment]
@daipra , would you mind sharing a code sample?

**Comment by bschaatsbergen** [comment]
Thanks for picking this up @holly-evans, we're closing to having your PR merged 🥇
