### ISSUE TITLE
ERROR on terminate_blue_instances_on_deployment_success action "KEEP_ALIVE" on Blue/green deployment

### ISSUE THREAD

**Issue by akramfstg** [hashicorp/terraform-provider-aws#23995]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
````
Terraform v1.1.5
on linux_amd64
````
### Affected Resource(s)
```
aws_codedeploy_deployment_group
````
### Terraform Configuration Files
````
resource "aws_codedeploy_deployment_group" "api_blue_green" {
  count                       = local.prefix == "staging" ? 1 : 0
  app_name               = aws_codedeploy_app.api[count.index].name
  deployment_group_name  = "${local.prefix}-dg-api"
  service_role_arn       = data.aws_iam_role.codedeploy.arn
  deployment_config_name = aws_codedeploy_deployment_config.api_canary[count.index].id

  auto_rollback_configuration {
    enabled = true
    events  = ["DEPLOYMENT_FAILURE"] 
  }

  blue_green_deployment_config {
    deployment_ready_option {
      action_on_timeout = "CONTINUE_DEPLOYMENT"
    }

    terminate_blue_instances_on_deployment_success {
      action                           = "KEEP_ALIVE"
      termination_wait_time_in_minutes = 5 
    }
  }
  deployment_style {
    deployment_option = "WITH_TRAFFIC_CONTROL"
    deployment_type   = "BLUE_GREEN"
  }
...
}
````
### Expected Behavior

It should work.

### Actual Behavior
````
error updating CodeDeploy deployment group XXXX: 
InvalidBlueGreenDeploymentConfigurationException: 
Target termination action can only be TERMINATE and not KEEP_ALIVE for the ECS blue green deployment
````

### Steps to Reproduce
````
terraform apply -target aws_codedeploy_deployment_group.api_blue_green
````

### References
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codedeploy_deployment_group#terminate_blue_instances_on_deployment_success

**Comment by justinretzolk** [comment]
Hey @akramfstg 👋 Thank you for taking the time to raise this! I started to look into this a bit more, but am curious -- are there additional arguments that you're passing which have been omitted by the `...` in your reproduction example? If so, can you supply those details as well?

**Comment by akramfstg** [comment]
Hey @justinretzolk the remaining properties are not a big deal but I am going to supply them:
````
resource "aws_codedeploy_deployment_group" "api_blue_green" {
  count                  = local.prefix == "staging" ? 1 : 0
  app_name               = aws_codedeploy_app.api[count.index].name
  deployment_group_name  = "${local.prefix}-dg-api"
  service_role_arn       = data.aws_iam_role.codedeploy.arn
  deployment_config_name = aws_codedeploy_deployment_config.api_canary[count.index].id

  auto_rollback_configuration {
    enabled = true
    events  = ["DEPLOYMENT_FAILURE", "DEPLOYMENT_STOP_ON_ALARM"] 
  }

  alarm_configuration {
    alarms  = ["${local.prefix}-api-latency"]
    enabled = true
  }

  blue_green_deployment_config {
    deployment_ready_option {
      action_on_timeout = "CONTINUE_DEPLOYMENT"
    }

    terminate_blue_instances_on_deployment_success {
      action                           = "KEEP_ALIVE"
      termination_wait_time_in_minutes = 5
    }
  }

  deployment_style {
    deployment_option = "WITH_TRAFFIC_CONTROL"
    deployment_type   = "BLUE_GREEN"
  }
  ecs_service {
    cluster_name = aws_ecs_cluster.main.name
    service_name = aws_ecs_service.api[count.index].name
  }
  load_balancer_info {
    target_group_pair_info {
      prod_traffic_route {
        listener_arns = [aws_lb_listener.api_https.arn]
      }
      target_group {
        name = aws_lb_target_group.blue_api[count.index].name
      }

      target_group {
        name = aws_lb_target_group.green_api[count.index].name
      }
    }
  }
}
````
What actually confuses me is when CodeDeploy rollbacks a deployment when the alarm is triggered, the old (blue) task definition is deactivated on the ECS side that is why I want to keep it alive.
How can I make a proper rollback? what needs to be tuned above?

Thanks

**Comment by justinretzolk** [comment]
Hey @akramfstg 👋 Thank you for the additional configuration information. I spent a bit of time looking into this and found some information that I think will be helpful.

In looking for information around why `KEEP_ALIVE` would not be accepted, I noticed that any resources I found around blue/green deployments for ECS _always_ used `TERMINATE` as the action for `terminate_blue_instances_on_deployment_success`. (for example, [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/create-blue-green.html)). I then stumbled on [this document](https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-groups-create-ecs.html), which describes creating a deployment group for ECS, and noted in step 13:

> For Original revision termination, choose the number of days, hours, and minutes to wait after a successful deployment before the original task set in your Amazon ECS service is terminated.

I also noted that in [this guide around deployments on ECS](https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-steps-ecs.html), there's never a mention of a way to keep alive -- it states that after a successful deployment, the original task set is removed. With all of this in mind, my read is that there is not a way to use `KEEP_ALIVE` with ECS deployments, which lines up with the error message reported.

As far as the rollback question that you had in your most recent update, in the guide around deployments on ECS linked in the previous paragraph above, I found the following note that seems relevant:

> In all cases, the new or rolled-back deployment is assigned its own deployment ID.

**Comment by slamotte** [comment]
Hi @justinretzolk,

I am just running into this as well. I noticed these in the various CodeDeploy docs:

https://docs.aws.amazon.com/codedeploy/latest/APIReference/API_BlueInstanceTerminationOption.html
https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/CodeDeploy/Types/BlueInstanceTerminationOption.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codedeploy-deploymentgroup-blueinstanceterminationoption.html

So it seems that leaving the old task set running after a successful blue/green deploy _should_ be possible. Or that a bunch of AWS docs are wrong. The former seems more likely. That said, I don't see an option to control this in the CodeDeploy console.

Question: is the error I'm getting:
```
Error: error updating CodeDeploy deployment group (<guid>): InvalidBlueGreenDeploymentConfigurationException: 
Target termination action can only be TERMINATE and not KEEP_ALIVE for the ECS blue green deployment.
```

generated by Terraform or by an AWS API call behind the scenes?
