### ISSUE TITLE
Support metadata aws_imagebuilder_infrastructure_configuration 

### ISSUE THREAD

**Issue by youanden** [hashicorp/terraform-provider-aws#24006]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At the moment, version 4.8 of this module doesn't support the metadata fields in infrastructure configuration. Screenshot:

![CleanShot 2022-04-03 at 00 32 37](https://user-images.githubusercontent.com/183880/161411646-04eaff00-7407-493d-958c-af80826fa354.png)

Without these, it's not possible to use instance metadata in components via [this](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html).

### Potential Terraform Configuration

Perhaps we can use this configuration

```hcl
resource "aws_imagebuilder_infrastructure_configuration" "this" {
  ...
  metadata_options {
    http_tokens                 = "required" # required|optional
    http_put_response_hop_limit = 1
  }
}
```

**Comment by kamilturek** [comment]
I'll take care of it.
