### ISSUE TITLE
ECS ManagedScalingInstanceWarmupPeriod minimum is 0 not 1

### ISSUE THREAD

**Issue by Vlaaaaaaad** [hashicorp/terraform-provider-aws#24003]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.8.0
```

### Affected Resource(s)

* aws_ecs_capacity_provider

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

Happy to share the whole code (LaunchTemplate, ASG, ECS Cluster, VPC, and all the jazz), but the relevant part is:
```hcl
resource "aws_ecs_capacity_provider" "autoscaling_group" {
  name = "example"

  auto_scaling_group_provider {
    auto_scaling_group_arn         = aws_autoscaling_group.asg.arn
    managed_termination_protection = "ENABLED"

    managed_scaling {
      instance_warmup_period    = 0
      maximum_scaling_step_size = 100
      minimum_scaling_step_size = 1
      target_capacity           = 90
      status                    = "ENABLED"
    }
  }
}
```

### Expected Behavior

A minimum value of `0` should be allowed, as per [aws-sdk-go](https://github.com/aws/aws-sdk-go/blob/ff47cc69ac8090f6328c5ed4fff02c595739ec26/models/apis/ecs/2014-11-13/api-2.json#L2332-L2336):
```go
"ManagedScalingInstanceWarmupPeriod": {
      "type": "integer",
      "max": 10000,
      "min": 0
    },
```

### Actual Behavior

A minimum value of `1` is required based on the provider code in [service/ecs/capacity_provider.go](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ecs/capacity_provider.go#L57-L62):
```go
"instance_warmup_period": {
  Type:         schema.TypeInt,
  Optional:     true,
  Computed:     true,
  ValidateFunc: validation.IntBetween(1, 10000),
},
```

### Steps to Reproduce

1. `terraform apply`

**Comment by bschaatsbergen** [comment]
Clear, will pick this up.
