### ISSUE TITLE
aws_s3_bucket_intelligent_tiering_configuration: tiering blocks should not be required

### ISSUE THREAD

**Issue by aviau** [hashicorp/terraform-provider-aws#24010]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.8.0
```

### Affected Resource(s)

* aws_s3_bucket_intelligent_tiering_configuration

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket_intelligent_tiering_configuration" "test" {
  bucket = aws_s3_bucket.test.bucket
  name   = "test"
}
```

### Expected Behavior

This configuration should apply.

### Actual Behavior

Terraform says `At least 1 "tiering" blocks are required.`. Using any of the tiering blocks would result in enabling the optional archive and deep archive overrides. I just want to use the default with none of them activated.

See the documentation:
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/intelligent-tiering-overview.html

The `Archive Access tier` and the `Deep Archive Access tier` are **optional**.

> Only activate the Archive Access tier for 90 days if you want to bypass the Archive Instant Access tier. The Archive Access tier delivers slightly lower storage cost with minute to hour retrieval times. The Archive Instant Access tier delivers millisecond access and high throughput performance.

> Activate the Archive Access and Deep Archive Access tiers only if your objects can be accessed asynchronously by your application. If the object that you are retrieving is stored in the Archive Access or Deep Archive Access tiers, first restore the object using RestoreObject. For more information, see [Restoring objects from the S3 Intelligent-Tiering Archive Access and Deep Archive Access tiers](https://docs.aws.amazon.com/AmazonS3/latest/userguide/intelligent-tiering-managing.html#restore-data-from-int-tier-archive)

**Comment by justinretzolk** [comment]
Hey @aviau 👋 Thank you for taking the time to raise this! In looking over this resource, it uses the `PutButcketIntelligentTieringConfiguration` function from the AWS Go SDK to manage this particular configuration. The [input](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketIntelligentTieringConfiguration.html) for this function and the [API documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketIntelligentTieringConfiguration.html) for the underlying API call indicate that the `Tiering` field is required. The valid values for `Tiering.AccessTier` [are documented](https://docs.aws.amazon.com/AmazonS3/latest/API/API_Tiering.html) as `ARCHIVE_ACCESS` and `DEEP_ARCHIVE_ACCESS`.

Based on your description, I'm assuming that you're wanting to use frequent access, infrequent access, and/or archive instant access tiers; is that correct? If so, these are automatic and do not require use of the `aws_s3_bucket_intelligent_tiering_configuration` resource, as discussed in [this AWS document](https://docs.aws.amazon.com/AmazonS3/latest/userguide/intelligent-tiering-overview.html).

**Comment by aviau** [comment]
Ahhh. You are correct. Sorry for the noise.

For those that look for the same feature, what I needed was simply:
```hcl
resource "aws_s3_bucket_lifecycle_configuration" "test" {
  bucket = aws_s3_bucket.test.id
  rule {
    id     = "rule-intelligent-tiering"
    status = "Enabled"
    transition {
      storage_class = "INTELLIGENT_TIERING"
    }
  }
}
```

Which will enable intelligent tiering by default to objects in the bucket.
