### ISSUE TITLE
Not able to set idle_disconnect_timeout_in_seconds to 0 (disable)

### ISSUE THREAD

**Issue by murataksoy83** [hashicorp/terraform-provider-aws#24014]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

aws_appstream_fleet

### Terraform Configuration Files

```hcl
resource "aws_appstream_fleet" "test_fleet" {
  name = "test-fleet"

  compute_capacity {
    desired_instances = 1
  }

  description                        = "test fleet"
  idle_disconnect_timeout_in_seconds = 0
  display_name                       = "test-fleet"
  enable_default_internet_access     = false
  fleet_type                         = "ON_DEMAND"
  image_name                         = "Amazon-AppStream2-Sample-Image-02-04-2019"
  instance_type                      = "stream.standard.large"
  max_user_duration_in_seconds       = 600

  vpc_config {
    subnet_ids = ["subnet-06e9b13400c225127"]
  }

  tags = {
    TagName = "tag-value"
  }
}
```

### Debug Output

Error: expected idle_disconnect_timeout_in_seconds to be in the range (60 - 3600), got 0
  on appstream/appstream.tf line xx, in resource "aws_appstream_fleet" "appstream_fleet":
  58:   idle_disconnect_timeout_in_seconds = 0

### Expected Behavior

It should allow to set the value to 0 as this disables the idle timeout. 

### Actual Behavior

It expects a value within the range 60 - 3600. So it is not possible to disable the idle timeout

### Steps to Reproduce

1. Try the create aws_appstream_fleet with  idle_disconnect_timeout_in_seconds set to 0

### References

AWS documentation:
https://docs.aws.amazon.com/appstream2/latest/developerguide/set-up-stacks-fleets.html#set-up-stacks-fleets-create

**Comment by swoeste** [comment]
Hi, 

we were facing the same problem since we recently moved from `arnvid/appstream` to the official AWS terraform provider, but today we found some sort of a workaround to disable the `idle_disconnect_timeout_in_seconds`, we just need to set it to `null`.

So in our terraform module we have something like this now:

```YAML
resource "aws_appstream_fleet" "this" {

  idle_disconnect_timeout_in_seconds = var.fleet_idle_disconnect_timeout == 0 ? null : var.fleet_idle_disconnect_timeout
 
}
```

kind regards
Sebastian

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/34453.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/35173.
