### ISSUE TITLE
I cannot deploy broker on a specific subnet.

### ISSUE THREAD

**Issue by zeusal** [hashicorp/terraform-provider-aws#24019]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.7
Terraform AWS Provider 3.69.0

### Affected Resource(s)

* aws_mq_broker

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_mq_broker" "default" {
  broker_name                = join("-", ["rabbitmq-broker", var.suffix_name])
  engine_type                = "RabbitMQ"
  engine_version             = "3.9.13"
  storage_type               = "ebs"
  host_instance_type         = "mq.t3.micro"
  authentication_strategy    = "simple"
  deployment_mode            = var.deployment_mode
  apply_immediately          = false
  auto_minor_version_upgrade = false
  publicly_accessible        = false
  security_groups            = [join("", aws_security_group.default.*.id)]
  subnet_ids                 = var.deployment_mode == "SINGLE_INSTANCE" ? [var.database_subnets_cidr_blocks[0]] : var.database_subnets_cidr_blocks
  tags                       = var.tags

  user {
    username = var.username
    password = random_password.password.result
  }

  maintenance_window_start_time {
    day_of_week = var.maintenance_window_start_time.day_of_week
    time_of_day = var.maintenance_window_start_time.time_of_day
    time_zone   = var.maintenance_window_start_time.time_zone
  }
}
```
The values is:
```hcl
Non default VPC:
 CIDRs:
    database_subnets_cidr_blocks: ["30.10.1.0/24", "30.10.2.0/24"]
--
deployment_mode: SINGLE_INSTANCE
```
### Debug Output

2022-04-04T17:38:11.585+0200 [INFO]  provider.terraform-provider-aws_v3.72.0_x5: 2022/04/04 17:38:11 [INFO] Creating MQ Broker: {
  AuthenticationStrategy: "simple",
  AutoMinorVersionUpgrade: false,
  BrokerName: "rabbitmq-broker-test",
  CreatorRequestId: "tf-rabbitmq-broker-test20220404153811585400000001",
  DeploymentMode: "SINGLE_INSTANCE",
  EngineType: "RabbitMQ",
  EngineVersion: "3.9.13",
  HostInstanceType: "mq.t3.micro",
  MaintenanceWindowStartTime: {
    DayOfWeek: "MONDAY",
    TimeOfDay: "22:45",
    TimeZone: "Europe/Dublin"
  },
  PubliclyAccessible: false,
  SecurityGroups: ["sg-0297310ccc74151c9"],
  StorageType: "ebs",
  SubnetIds: ["30.10.1.0/24"],
  Tags: {
  },
  Users: [{
      ConsoleAccess: false,
      Groups: [],
      Password: "********",
      Username: "root"
    }]
}: timestamp=2022-04-04T17:38:11.585+0200
2022-04-04T17:38:11.586+0200 [INFO]  provider.terraform-provider-aws_v3.72.0_x5: 2022/04/04 17:38:11 [DEBUG] [aws-sdk-go] DEBUG: Request mq/CreateBroker Details:
### Expected Behavior

I was expecting that the broker is created in the  VPC of given subnet.
In the AWS documentation, it is allowed to select a specific VPC and its corresponding subnet, however, in the terraform resource documentation, I do not see the possibility to indicate a VPC.

### Actual Behavior

╷
│ Error: BadRequestException: Subnets must belong to the same VPC.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "15beb1ae-788c-439d-9384-46f1c10ba8cf"
│   },
│   ErrorAttribute: "subnetIds",
│   Message_: "Subnets must belong to the same VPC."
│ }
│ 
│   with module.activemq[0].aws_mq_broker.default,
│   on activemq/main.tf line 68, in resource "aws_mq_broker" "default":
│   68: resource "aws_mq_broker" "default" {

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @zeusal 👋 Thank you for taking the time to raise this! On a quick look, I noticed that for `security_groups`, you're passing `[join("", aws_security_group.default.*.id)]`, and then in your description of the subnets, you called out that this was a non-default VPC. Am I correct in assuming that the security groups are in the default VPC? If so, I believe that may be the issue -- that the subnet and security groups belong to different VPCs.

**Comment by zeusal** [comment]
> Hey @zeusal wave Thank you for taking the time to raise this! On a quick look, I noticed that for `security_groups`, you're passing `[join("", aws_security_group.default.*.id)]`, and then in your description of the subnets, you called out that this was a non-default VPC. Am I correct in assuming that the security groups are in the default VPC? If so, I believe that may be the issue -- that the subnet and security groups belong to different VPCs.

Hi  @justinretzolk I have not shared all the code, that reference is to a resource defined in the same TF.

```hcl
resource "aws_security_group" "default" {
  name        = join("-", ["csg", var.suffix_name_sg])
  description = "Security Group for MQ"
  vpc_id      = var.vpc_id
}


resource "aws_security_group_rule" "egress" {
  type              = "egress"
  description       = "Allow all egress traffic"
  from_port         = 0
  to_port           = 0
  protocol          = "-1"
  cidr_blocks       = ["0.0.0.0/0"]
  security_group_id = join("", aws_security_group.default.*.id)
}

resource "aws_security_group_rule" "ingress_security_groups_mq" {
  count                    = length(var.security_groups)
  type                     = "ingress"
  description              = "Allow inbound traffic from existing Security Groups"
  from_port                = "5671"
  to_port                  = "5671"
  protocol                 = "tcp"
  source_security_group_id = element(var.security_groups, count.index)
  security_group_id        = join("", aws_security_group.default.*.id)
}

resource "aws_security_group_rule" "ingress_cidr_blocks_mq" {
  type              = "ingress"
  count             = length(var.cidr_blocks) > 0 ? 1 : 0
  description       = "Allow inbound traffic from CIDR blocks"
  from_port         = "5671"
  to_port           = "5671"
  protocol          = "tcp"
  cidr_blocks       = var.cidr_blocks
  security_group_id = join("", aws_security_group.default.*.id)
}

resource "aws_security_group_rule" "ingress_security_groups_https" {
  count                    = length(var.security_groups)
  type                     = "ingress"
  description              = "Allow inbound traffic from existing Security Groups"
  from_port                = "443"
  to_port                  = "443"
  protocol                 = "tcp"
  source_security_group_id = element(var.security_groups, count.index)
  security_group_id        = join("", aws_security_group.default.*.id)
}

resource "aws_security_group_rule" "ingress_cidr_blocks_https" {
  type              = "ingress"
  count             = length(var.cidr_blocks) > 0 ? 1 : 0
  description       = "Allow inbound traffic from CIDR blocks"
  from_port         = "443"
  to_port           = "443"
  protocol          = "tcp"
  cidr_blocks       = var.cidr_blocks
  security_group_id = join("", aws_security_group.default.*.id)
}

resource "aws_mq_broker" "default" {
  broker_name                = join("-", ["rabbitmq-broker", var.suffix_name])
  engine_type                = "RabbitMQ"
  engine_version             = "3.9.13"
  storage_type               = "ebs"
  host_instance_type         = "mq.t3.micro"
  authentication_strategy    = "simple"
  deployment_mode            = var.deployment_mode
  apply_immediately          = false
  auto_minor_version_upgrade = false
  publicly_accessible        = false
  security_groups            = [join("", aws_security_group.default.*.id)]
  subnet_ids                 = var.deployment_mode == "SINGLE_INSTANCE" ? [var.database_subnets_cidr_blocks[0]] : var.database_subnets_cidr_blocks
  tags                       = var.tags

  user {
    username = var.username
    password = random_password.password.result
  }

  maintenance_window_start_time {
    day_of_week = var.maintenance_window_start_time.day_of_week
    time_of_day = var.maintenance_window_start_time.time_of_day
    time_zone   = var.maintenance_window_start_time.time_zone
  }
}
```

My VPC has two CIDRs:

Non default VPC:
CIDRs:
cidr_blocks: "10.10.0.0/16"
secondary_cidr_blocks: [""20.10.0.0/22"]
private_subnets: ["10.20.64.0/18", "10.20.128.0/18"]
secondary_blocks:  30.10.0.0/22
database_subnets: ["30.10.1.0/24", "30.10.2.0/24"]
deployment_mode: SINGLE_INSTANCE

Both CIDRs is into the same VPC, all default account resources have been deleted, from VPCs to SG.

**Comment by zeusal** [comment]
Hello again, I have solved this ticket, because it was a coding mistake for my part, I was passing the cidr instead of the subnet id.

Regards!
