### ISSUE TITLE
Same cidr range and route table cant exists even different VPC is used on aws_ec2_transit_gateway_route

### ISSUE THREAD

**Issue by seanlok** [hashicorp/terraform-provider-aws#24015]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_ec2_transit_gateway_route

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Same transit gateway route table and cidr but different vpc should have a unique id when creating with `aws_ec2_transit_gateway_route`.

### Actual Behavior

`id` was the same even different vpc is used in the resource `aws_ec2_transit_gateway_route` and cause only single resource being created.

### Steps to Reproduce

1. Create two route entry with `aws_ec2_transit_gateway_route` on same RT and different VPC
2. Perform `terraform plan`
3. Perform `terraform apply`, same id was generated for both entry.
4. Perform `terraform plan` again, only one of the entry will be created and it will be switching one another unless a different cidr entry is used or different state file is used. 

### References

Related to: https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/issues/71

**Comment by justinretzolk** [comment]
Hey @seanlok 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?

**Comment by seanlok** [comment]
@justinretzolk updated the description and provided a PR.

**Comment by ewbankkit** [comment]
@seanlok Are you able to create two routes with the same destination CIDR?

I get an error like:

```
aws_ec2_transit_gateway_route.test2: Creating...
╷
│ Error: error creating EC2 Transit Gateway Route (tgw-rtb-0129954f9d94fd992_0.0.0.0/0): RouteAlreadyExists: Route 0.0.0.0/0 already exists in Transit Gateway Route Table tgw-rtb-0129954f9d94fd992.
```

if I try this.

**Comment by gdavison** [comment]
Since it's been over a year with no response, I'm going to close this issue. If you're still seeing the problem, please open a new issue and include all of the requested information
