### ISSUE TITLE
CloudFront KeyGroup resource update to eTag on associated CloudFront Distribution not captured in state

### ISSUE THREAD

**Issue by frankloye** [hashicorp/terraform-provider-aws#24033]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_cloudfront_distribution
* aws_cloudfront_public_key
* aws_cloudfront_key_group

### Terraform Configuration Files

```hcl
terraform {
  backend "azurerm" {}
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.53.0"
    }
  }
}

resource "aws_cloudfront_public_key" "key" {
  encoded_key = file(var.encoded_key)
  name_prefix = "key-${var.xxx}-${var.yyy}-${var.zzz}-"
  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_cloudfront_key_group" "key_group" {
  items = [aws_cloudfront_public_key.key.id]
  name  = "key-group-${local.xxx}-${var.yyy}-${var.zzz}"
}
```

### Expected Behavior

The CloudFront KeyGroup resource should not directly update the CloudFront Distribution. Only the CloudFront Distribution module should update the CloudFront Distribution with the new Key Group values and update the associated eTags.

### Actual Behavior

Every time the CloudFront KeyGroup value is changed, the CloudFront KeyGroup module will update the associated CloudFront Distribution with the new PublicKey and KeyGroup values, and change the eTags on the CloudFront Distribution. The updated eTags are not being captured in the state file of the associated CloudFront Distribution, and when an update is needed on the CloudFront Distribution, the update request fails because the eTag values in state do not match the eTag values on the CloudFront Distribution with the following error: Error: error updating CloudFront Distribution (XXXXX): PreconditionFailed: The request failed because it didn't meet the preconditions in one or more request-header fields.status code: 412

### Steps to Reproduce

1. `terraform apply`

**Comment by enzolupia** [comment]
Hi, same issue here when updating an _aws_cloudfront_cache_policy_ or an _aws_cloudfront_cache_policy_ linked to a Cloudfront distribution.
During update, the _aws_cloudfront_cache_policy_ and _aws_cloudfront_cache_policy_ are updated first, then when the Cloudfront distribution gets updated it fails with "Error: error updating CloudFront Distribution (XXXXX): PreconditionFailed: The request failed because it didn't meet the preconditions in one or more request-header fields.status code: 412".

**Comment by aholthagerty** [comment]
correct me if I'm wrong, but it appears the issue outlined by @enzolupia is also affecting `aws_cloudfront_response_headers_policy` resource.

is there a workaround for this?  as it stands, it doesn't appear that these resources can be updated in subsequent terraform `apply` calls, else we end up with:

```
Error: error updating CloudFront Distribution (XXXXX): PreconditionFailed: The request failed because it didn't meet the preconditions in one or more request-header fields.status code: 412
```

**Comment by aholthagerty** [comment]
Best workaround I have currently is to let the first `terraform apply` fail with `PreconditionFailed`, then run a `terraform refresh`, then run `terraform apply` again.

**Comment by frankloye** [comment]
@aholthagerty that is the same workaround I am using
