### ISSUE TITLE
network_card_index support in aws_instance and aws_network_interface_attachment

### ISSUE THREAD

**Issue by nkorobko** [hashicorp/terraform-provider-aws#24043]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Missing network_card_index attribute in network_interface block. This is needed in order to create ec2 nodes that have more than 1 network card (dl1.24xlarge). Due to the fact that you can not attach more than 1 EFA on a single network card - it is impossible to create an ec2 from dl1.24xlarge type with 4 EFA adapters attached using aws_instance. The only workaround for this is to create aws_launch_template, where network_card_index is supported in the network_interface  block

### New or Affected Resource(s)

* aws_instance
* aws_network_interface_attachment

### Potential Terraform Configuration

```hcl
Currently, this is only supported by aws_launch_template. I would like to see this support in aws_instance and in aws_network_interface_attachment

 network_interfaces {
    network_interface_id        = var.mgmt_efa_host_list[2]
    device_index                = 2
    **network_card_index**          = 2
  }
```

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#network-interfaces
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#network-interfaces

* #0000

**Comment by ewbankkit** [comment]
`device_index` is already available in the `aws_network_interface_attachment` resource: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/network_interface_attachment#device_index

**Comment by ewbankkit** [comment]
Relates: https://github.com/hashicorp/terraform-provider-aws/issues/21147.

**Comment by nkorobko** [comment]
@ewbankkit yes, I'm aware of that, the missing attribute is **network_card_index**. This is not the same as **device_index**

**Comment by zeroflaw** [comment]
When using network_interface block in aws_spot_instance_request i'm now getting the error:

`Error: Error requesting spot instances: UnknownParameter: The parameter NetworkCardIndex is not recognized
│       status code: 400, request id: 904aa9a5-fc2f-4668-b9a4-4fc0e8cef3e5` 

I'm not sure how to work around the issue.
