### ISSUE TITLE
Lambda environment variables that have a computed value based on remote state are ignored

### ISSUE THREAD

**Issue by sblask** [hashicorp/terraform-provider-aws#24041]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.8.0
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/time v0.7.2
```

### Affected Resource(s)

* aws_lambda_function

### Terraform Configuration Files

The code looks like this, but it's not easily reproducible because there is remote state involved and the original code uses nested modules:

```hcl
terraform {
  backend "s3" {
    bucket = "terraform.testing.foobar.net"
    key    = "foobar.tfstate"
    region = "ap-southeast-2"

    role_arn = "arn:aws:iam::XXXXXXXXXXXX:role/terraform-admin"
  }
}

provider "aws" {
  assume_role {
    role_arn = "arn:aws:iam::XXXXXXXXXXXX:role/terraform-admin"
  }
}

data "terraform_remote_state" "aws_accounts" {
  backend = "s3"
  config = {
    bucket = "terraform.management.foobar.net"
    key    = "aws-accounts.tfstate"
    region = "ap-southeast-2"

    role_arn = "arn:aws:iam::YYYYYYYYYY:role/developer"
  }
}

locals {
  account_alias = one([
    for account_id, account_alias in data.terraform_remote_state.aws_accounts.outputs.account_aliases : account_alias
    if account_id == data.aws_caller_identity.current.account_id
  ])
}

data "aws_s3_object" "lambda_archive" {
  bucket = "archive.foobar.net"
  key    = "lambda/tenants-log-to-splunk/snapshot/add-logging-lambda/tenants-log-to-splunk.zip"
}

data "aws_iam_policy_document" "assume_execution_role" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "execution_role" {
  name               = "foo-execution-role"
  assume_role_policy = data.aws_iam_policy_document.assume_execution_role.json
}

resource "aws_lambda_function" "lambda" {
  s3_bucket         = data.aws_s3_object.lambda_archive.bucket
  s3_key            = data.aws_s3_object.lambda_archive.key
  s3_object_version = data.aws_s3_object.lambda_archive.version_id

  function_name = "foo"
  handler       = "handler.handler"
  runtime       = "python3.9"
  memory_size   = 1024
  role          = aws_iam_role.execution_role.arn

  vpc_config {
    subnet_ids         = ["subnet-123", "subnet-456", "subnet-789"]
    security_group_ids = ["sg-123"]
  }

  environment {
    variables = {
      FOO                    = "BAR"
      ENVIRONMENT = local.account_alias
    }
  }

}
```

### Debug Output

The full output can be found here: https://gist.github.com/sblask/bd24f37cc245bb5f25f1ad05e77df964 but I believe the relevant bit is this:

```
2022-04-06T16:59:48.872+1200 [WARN]  Provider "registry.terraform.io/hashicorp/aws" produced an invalid plan for module.cloudfront.module.logging_lambda.aws_lambda_function.lambda, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .layers: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .tags: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
      - .code_signing_config_arn: planned value cty.StringVal("") for a non-computed attribute
      - .kms_key_arn: planned value cty.StringVal("") for a non-computed attribute
      - .publish: planned value cty.False for a non-computed attribute
      - .reserved_concurrent_executions: planned value cty.NumberIntVal(-1) for a non-computed attribute
      - .image_uri: planned value cty.StringVal("") for a non-computed attribute
      - .package_type: planned value cty.StringVal("Zip") for a non-computed attribute
      - .environment[0].variables: planned value cty.MapVal(map[string]cty.Value{"IENVIRONMENT":cty.StringVal("BAR"), "SPLUNK_TOKEN_PARAMETER":cty.StringVal("/splunk/hec-token/lambda-to-splunk")}) does not match config value cty.MapVal(map[string]cty.Value{"ENVIRONMENT":cty.NullVal(cty.String), "IENVIRONMENT":cty.StringVal("BAR"), "SPLUNK_TOKEN_PARAMETER":cty.StringVal("/splunk/hec-token/lambda-to-splunk")}) nor prior value cty.MapVal(map[string]cty.Value{"ENVIRONMENT":cty.StringVal("testing"), "SPLUNK_TOKEN_PARAMETER":cty.StringVal("/splunk/hec-token/lambda-to-splunk")})
      - .ephemeral_storage: block count in plan (1) disagrees with count in config (0)
      - .tracing_config: block count in plan (1) disagrees with count in config (0)
```

### Expected Behavior

Environment variables should be used as declared.

### Actual Behavior

Environment variables are being ignore and not added, if I add it manually in the AWS Console it is getting removed:

```

  # module.cloudfront.module.logging_lambda.aws_lambda_function.lambda will be updated in-place
  ~ resource "aws_lambda_function" "lambda" {
        id                             = "tenants-logging-lambda"
        tags                           = {}
        # (22 unchanged attributes hidden)

      ~ environment {
          ~ variables = {
              - "ENVIRONMENT"            = "testing" -> null
                # (1 unchanged element hidden)
            }
        }



        # (3 unchanged blocks hidden)
    }

```

### Steps to Reproduce

1. `terraform plan`

**Comment by sblask** [comment]
Of course, 5 minutes after I opened the issue i found the problem that I couldn't find in the two hours before. I had a bug so that:

```
account_alias = one([
    for account_id, account_alias in data.terraform_remote_state.aws_accounts.outputs.account_aliases : account_alias
    if account_id == data.aws_caller_identity.current.account_id
  ])
```
would make `account_alias` `null` and that got silently ignored.

Is there a way to add a warning for situations like this?

**Comment by justinretzolk** [comment]
Hey @sblask 👋 the behavior where `null` is returned for `account_alias` looks to be due to your use of the [`one` function](https://www.terraform.io/language/functions/one), which returns `null` if the list that is passed to it is empty. If you were to remove the `one()` call and then make the following change:

```hcl
ENVIRONMENT = local.account_alias[0]
```

...an error would be thrown if `account_alias` was an empty list, which should give the warning that you're looking for.

**Comment by sblask** [comment]
@justinretzolk sure, I should probably get rid of the `one` but there are probably other ways to by accident pass in a `null` value to an environment variable? Kind of "silently" removing the environment variable doesn't seem like the right way to handle that?

**Comment by justinretzolk** [comment]
Hey @sblask 👋 By silently removing the environment variable, are you referencing the last bit of your issue description, where after modifying the variable in the AWS console, Terraform attempts to set the value to `null` on the next run? If so, that'd be Terraform attempting to reconcile what it sees as drift -- where the definition in the Terraform configuration does not match the configuration in reality, so Terraform attempts to "correct" it (in case you're unfamiliar, we have [a document](https://www.hashicorp.com/blog/detecting-and-managing-drift-with-terraform) about this).

**Comment by sblask** [comment]
I mean that both, removing an existing environment variable when the value changes to `null` and not adding a new environment variable with a value `null`, are not ideal. AWS does not support `null` values so there should be an error like I get when using the CLI:

```
$ aws ec2 create-tags --resources i-abc --tags Key=test

An error occurred (InvalidParameterValue) when calling the CreateTags operation: Value ( test ) for parameter value is invalid. Tag value cannot be null. Use empty string instead.
```

**Comment by justinretzolk** [comment]
That makes sense to me. I've marked this as a bug due to lack of an error when the tag value is `null` -- that definitely seems like something we should address.
