### ISSUE TITLE
new values learned so far during apply

### ISSUE THREAD

**Issue by stijndehaes** [hashicorp/terraform-provider-aws#24059]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform version: 1.1.7
aws provider: 4.8.0

### Affected Resource(s)

all resources supporting tags

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_sqs_queue" "foo" {
  name = "foo"
}
resource "aws_sqs_queue" "bar" {
  name = "bar"
  tags = {
    "foo": aws_sqs_queue.foo.arn
  }
}
provider "aws" {
  default_tags {
    tags = {
      "Terraform" = "true",
    }
  }
}
```

### Panic Output

no panic

### Expected Behavior

To create the resources.

### Actual Behavior

The second resourecs bar, will not be created instead applying will fail:

```
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for aws_sqs_queue.bar to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "foo" has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

nothing special
### References

* #0000

**Comment by bassmanitram** [comment]
There are a large number of duplicates of this - the most active in terms of comments appears to be https://github.com/hashicorp/terraform-provider-aws/issues/19583
