### ISSUE TITLE
SSL_Policy is ignored in ALB module

### ISSUE THREAD

**Issue by weberChristian** [hashicorp/terraform-provider-aws#24058]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

$ terragrunt -v
terragrunt version v0.28.7
$ terraform -v
Terraform v1.0.0

### Affected Resource(s)

terraform-aws-modules/alb/aws/alb

### Terraform Configuration Files

```hcl
module "alb" {
    source = "terraform-aws-modules/alb/aws"
    version = "~> 6.8.0"

    ...

    listener_ssl_policy_default = "ELBSecurityPolicy-FS-1-2-Res-2019-08"

    https_listeners = [
        {
            port = 443
            protocol = "HTTPS"
            certificate_arn = var.tls_certificate_arns[0]
            target_group_index = 0
            ssl_policy = "ELBSecurityPolicy-FS-1-2-Res-2019-08"
        }
    ]

    ...
}
```

### Expected Behavior

When I configure ssl_policy/listener_ssql_policy_default I expect that the security policies will be configured in my alb.

### Actual Behavior

I recently configured an ssl_policy with listener_ssl_policy_default however if I execute an terragrunt plan no changes will be executed. 
When I destroy and recreate the alb, the ssl_policy is still the unwanted default-value.

I highly suspect that I overlooked something, however I am unable to identify my mistake. Most of the time the provided example helped me out or the documentation, but no luck this time.

### Steps to Reproduce

1. `terraform apply`

### References

https://registry.terraform.io/modules/terraform-aws-modules/alb/aws/latest
https://docs.amazonaws.cn/en_us/elasticloadbalancing/latest/application/create-https-listener.html

* #0000

**Comment by justinretzolk** [comment]
Hey @weberChristian 👋 Thank you for taking the time to raise this! So that we have all of the necessary information to look into this, can you supply the version of the AWS Provider that you're using, as well as (redacted as needed) debug logs?

**Comment by weberChristian** [comment]
Hello @justinretzolk thank you for taking time for my issue.. But I think found the error, and of course it was me.. 😬

(Just to document the error): I tried to apply the changes via terragrunt-source Option but messed up the configuration and from the error-message itself it wasn't clear that something was wrong with the configuration. It is more an "inaccessibility" in error-handling from terragrunt than an terraform ALB module issue.. So sorry for making you the culprit first 😅.
