### ISSUE TITLE
False positive drift on aws_route and aws_route_table resources

### ISSUE THREAD

**Issue by luispabon** [hashicorp/terraform-provider-aws#24150]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

cli 1.1.8
aws 4.9.0

### Affected Resource(s)
 * `aws_route`
 * `aws_route_table`

### Terraform Configuration Files

```hcl

resource "aws_route" "route-private-nat-gw-vpc" {
  count                  = length(var.azs)
  route_table_id         = element(var.vpc-private-route-tables-ids, count.index)
  destination_cidr_block = "0.0.0.0/0"
  nat_gateway_id         = element(aws_nat_gateway.nat-gw-vpc.*.id, count.index)
}

resource "aws_route_table" "private" {
  vpc_id = aws_vpc.vpc.id

  count = length(var.azs)
  tags  = merge(
    var.tags,
    {
      "Name" = format(
        "%s-private-%s-vpc",
        var.environment,
        element(var.azs, count.index),
      )
    },
  )
}

```

### Debug Output

```
**Note: Objects have changed outside of Terraform**

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # module.nat-gateway.aws_route.route-private-nat-gw-vpc[1] has changed
  ~ resource "aws_route" "route-private-nat-gw-vpc" {
        id                     = "r-rtb-XXX"
        # (5 unchanged attributes hidden)
    }

  # module.vpc.aws_route_table.private[0] has changed
  ~ resource "aws_route_table" "private" {
        id               = "rtb-XXX"
      ~ route            = [
          + {
              + carrier_gateway_id         = ""
              + cidr_block                 = "0.0.0.0/0"
              + core_network_arn           = ""
              + destination_prefix_list_id = ""
              + egress_only_gateway_id     = ""
              + gateway_id                 = ""
              + instance_id                = ""
              + ipv6_cidr_block            = ""
              + local_gateway_id           = ""
              + nat_gateway_id             = "nat-XXX"
              + network_interface_id       = ""
              + transit_gateway_id         = ""
              + vpc_endpoint_id            = ""
              + vpc_peering_connection_id  = ""
            },
          - {
              - carrier_gateway_id         = ""
              - cidr_block                 = "0.0.0.0/0"
              - core_network_arn           = null
              - destination_prefix_list_id = ""
              - egress_only_gateway_id     = ""
              - gateway_id                 = ""
              - instance_id                = ""
              - ipv6_cidr_block            = ""
              - local_gateway_id           = ""
              - nat_gateway_id             = "nat-XXX"
              - network_interface_id       = ""
              - transit_gateway_id         = ""
              - vpc_endpoint_id            = ""
              - vpc_peering_connection_id  = ""
            },
        ]
        tags             = {
            "Environment"      = "XXX"
            "Name"             = "XXX-private-XXX-vpc"
            "Region"           = "XXX"
            "Terraform"        = "true"
            "user:Environment" = "XXX"
        }
        # (5 unchanged attributes hidden)
    }

```

### Panic Output

n/a

### Expected Behavior

No changes at all.

### Actual Behavior

These changes have shown up after upgrading from aws provider 4.8.0 to 4.9.0. There are no terraform code changes on my end and there's been no drift on the resources. Reverting to 4.8.0 removes the drift warning.
 
 * `aws_route_table` as you can see, the diff is incorrect - the segments highlighted for change are in fact identical, as it is to be expected since no changes to code have been made, and there isn't any drift on the resource itself.
 * `aws_route` that's even more puzzling. They're marked as drift, but with no changes at all detected (not even a non-diff diff)

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

n/a

### References
n/a

**Comment by gdavison** [comment]
Hi @luispabon. I've done some investigation on this issue. This was caused by an error in Terraform, and no longer occurs in the latest version of Terraform, v1.2.3.

**Comment by luispabon** [comment]
Thank you @gdavison
