### ISSUE TITLE
Cannot manage default x-ray group

### ISSUE THREAD

**Issue by jon-armen** [hashicorp/terraform-provider-aws#24155]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.0
AWS Provider 4.9.0

### Affected Resource(s)

* aws_xray_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_xray_group" "default" {
  group_name        = "default"

  insights_configuration {
    insights_enabled      = true
    notifications_enabled = true
  }
}
```

### Expected Behavior

The default group can be updated to enable insights and / or notifications

### Actual Behavior

The default group name is reserved

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

May need to consider creating a new resource, such as "aws_default_xray_group" to adopt control of the default xray group, much like adoption of a default vpc with "aws_default_vpc"

### References

* #23409 - Related to managing default xray configuration

**Comment by DrFaust92** [comment]
as a workaround you can import this config to manage it.
