### ISSUE TITLE
Unable to update aws_cloudformation_stack_set with max_concurrent_percentage field set

### ISSUE THREAD

**Issue by faurel** [hashicorp/terraform-provider-aws#24161]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```bash
$ terraform -v
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.9.0
```

### Affected Resource(s)

* aws_cloudformation_stack_set 

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_cloudformation_stack_set" "this" {
....
  operation_preferences {
    failure_tolerance_percentage = 100
    max_concurrent_percentage    = 100
    region_concurrency_type      = "PARALLEL"
  }
}
```

### Debug Output

```
│ Error: error updating CloudFormation StackSet (my-stackset): InvalidParameter: 1 validation error(s) found.
│ - minimum field value of 1, UpdateStackSetInput.OperationPreferences.MaxConcurrentCount.
│ 
│ 
│   with aws_cloudformation_stack_set.this,
│   on main.tf line 1, in resource "aws_cloudformation_stack_set" "this":
│    1: resource "aws_cloudformation_stack_set" "this" {
````

### Expected Behavior

Stack Set should be successfully updated and deployed according to operation preferences.
Stack set operation preferences accept 2 ways of defining deployment strategy either based on percentage either based on fixed limit.
Hence we should be able to choose between `max_concurrent_percentage`  and `max_concurrent_count` depending on our strategy.

### Actual Behavior

Terraform is failing because it is expecting both arguments `max_concurrent_percentage`  and `max_concurrent_count`.
And if I set both it complains that I have to choose between one or the other.
```
╷
│ Error: Conflicting configuration arguments
│ 
│   with aws_cloudformation_stack_set.this,
│   on main.tf line 20, in resource "aws_cloudformation_stack_set" "this":
│   20:     max_concurrent_percentage    = 100
│ 
│ "operation_preferences.0.max_concurrent_percentage": conflicts with operation_preferences.0.max_concurrent_count
╵
╷
│ Error: Conflicting configuration arguments
│ 
│   with aws_cloudformation_stack_set.this,
│   on main.tf line 21, in resource "aws_cloudformation_stack_set" "this":
│   21:     max_concurrent_count         = 2000
│ 
│ "operation_preferences.0.max_concurrent_count": conflicts with operation_preferences.0.max_concurrent_percentage
```

### Steps to Reproduce

Create stack set based on given sample code and run `terraform apply`

### References

https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_StackSetOperationPreferences.html

**Comment by jnixon-blue** [comment]
I see how this was introduced with my PR #23908, I'm happy to work on a fix but I'm having trouble figuring out why the validators seem to be running on optional attributes when they have not been set. Are there any devs who can give me some review or quick guidance?

**Comment by MarkCBell** [comment]
This issue appears to stem from the `expandCloudFormationOperationPreferences` always expanding and validating the `max_concurrent_count` and `max_concurrent_percentage` parameters. I've submitted PR #24202 which changes the expansion to use `else if` so if one of these parameters is provided then the other is not attempted to be validated. The same applies to `failure_tolerance_count` and `failure_tolerance_percentage`.

**Comment by jnixon-blue** [comment]
Thanks for the quick PR and assistance Mark!

**Comment by MarkCBell** [comment]
I have notice that the changes that have been merged in by @ewbankkit do not support `operation_preferences` where `failure_tolerance_percentage = 0` or `failure_tolerance_count = 0`. I have opened PR #24250 to address this.
