### ISSUE TITLE
aws_eks_cluster created_at timestamp is not what it supposed to be

### ISSUE THREAD

**Issue by endrec** [hashicorp/terraform-provider-aws#24183]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Does not really matter, it seems to be the same from the beginning of time...
```
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.9.0
```

### Affected Resource(s)

* aws_eks_cluster

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
variable "cluster_id" {
  description = "An exiting EKS cluster's id"
}

data "aws_eks_cluster" "cluster" {
  name = var.cluster_id
}

output "cluster_created_at" {
  value = data.aws_eks_cluster.cluster.created_at
}
```

### Expected Behavior

According to the documentation (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/eks_cluster), `data.aws_eks_cluster.cluster.created_at` should be a `Unix epoch time stamp in seconds`.

### Actual Behavior

`data.aws_eks_cluster.cluster.created_at` returns a string, in a format which is not even compatible with `formatdate`.

### Steps to Reproduce

1. Have an existing EKS cluster.
2. `export TF_VAR_cluster_id=<your cluster id>`
3. `terraform apply`

### Important Factoids

My use case: EKS clusters created before April 16, 2020 require AmazonEKSServicePolicy, so I wanted to compare my cluster's creation date to decide if it needs this policy, or not. 
Workaround: `tonumber(replace(substr(data.aws_eks_cluster.cluster.created_at, 0, 10), "-", "")) < 20200416`, which works with the format now, but as it is not a standard format, nothing guarantees it won't break in the next version.

### References

* https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/eks/cluster_data_source.go#L166

**Comment by mkilchhofer** [comment]
I have the exact same use case ;-)

**Comment by stevehipwell** [comment]
I'm formatting the date with the first pattern below but I suspect that the date is always UTC so it could be simplified to the second pattern.

```terraform
locals {
  cluster_created_at = replace(replace(aws_eks_cluster.default.created_at, "/^(\\d{4}-\\d{2}-\\d{2})\\s(\\d{2}:\\d{2}:\\d{2})\\.\\d+\\s(\\+\\d{4}).+$/", "$${1}T$${2}$${3}"), "+0000", "Z")
}
```

```terraform
locals {
  cluster_created_at = replace(aws_eks_cluster.default.created_at, "/^(\\d{4}-\\d{2}-\\d{2})\\s(\\d{2}:\\d{2}:\\d{2}).+$/", "$${1}T$${2}Z")
}
```

The actual fix would be pretty simple, the following code would need to be modified to use the correct format.

https://github.com/hashicorp/terraform-provider-aws/blob/986a637f45b1f1bc4de00f0b0facf59dadff106b/internal/service/eks/cluster_data_source.go#L209

```go
 d.Set("created_at", aws.TimeValue(cluster.CreatedAt).Format(time.RFC3339)) 
```

**Comment by bryantbiggs** [comment]
@endrec is this still an issue or can we close this out now?

**Comment by stevehipwell** [comment]
@bryantbiggs it's still an issue for me as the suggest patch above or an alternative hasn't been applied.
