### ISSUE TITLE
OpenSearch cold_storage_options not expected

### ISSUE THREAD

**Issue by stevesimpson418** [hashicorp/terraform-provider-aws#24195]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.9.0

### Affected Resource(s)

* aws_opensearch_domain

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_opensearch_domain" "opensearch" {
  domain_name    = "opensearch-test"
  engine_version = "OpenSearch_1.2"

  auto_tune_options {
    desired_state = "ENABLED"
    rollback_on_disable = "DEFAULT_ROLLBACK"

    maintenance_schedule {
      start_at  = "2022-01-01T03:00:00.00Z"
      cron_expression_for_recurrence = "0 3 * * 7"
      duration {
          value = 3
          unit  = "HOURS"
      }
    }
  }

  cluster_config {
    dedicated_master_count = 0
    dedicated_master_enabled = false
    dedicated_master_type  = "r6g.large.search"
    instance_type = "r6g.large.search"
    instance_count = 1
    warm_count = 0
    warm_enabled  = false
    warm_type = "ultrawarm1.large.search"
    zone_awareness_enabled = false

    cold_storage_options {
      enabled = false
    }

    zone_awareness_config {
      availability_zone_count = 3
    }
  }

  ebs_options {
    ebs_enabled = true
    volume_size = 30
  }

  vpc_options {
    subnet_ids = ["subnet-foo", "subnet-bar"]
    security_group_ids = [aws_security_group.opensearch.id]
  }
}
```

### Expected Behavior

`cold_storage_options` should be applied as detailed in the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearch_domain#cold_storage_options)

### Actual Behavior
```
╷
│ Error: Unsupported block type
│
│   on main.tf line 50, in resource "aws_opensearch_domain" "opensearch":
│   50:     cold_storage_options {
│
│ Blocks of type "cold_storage_options" are not expected here.
╵
ERRO[0020] 1 error occurred:
	* exit status 1
```

### Steps to Reproduce

1. `terraform plan`

**Comment by justinretzolk** [comment]
Related: #19713
