### ISSUE TITLE
r/ecr_replication_configuration: destination should be optional

### ISSUE THREAD

**Issue by jbg** [hashicorp/terraform-provider-aws#24211]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.8
provider registry.terraform.io/hashicorp/aws v3.75.1

Whilst I'm not using the latest provider version, I have verified that the issue is [extant in current git master](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ecr/replication_configuration.go#L44).

### Affected Resource(s)

* aws_ecr_replication_configuration

### Terraform Configuration Files

```hcl
resource "aws_ecr_replication_configuration" "example" {
  replication_configuration {
    rule {
      repository_filter {
        filter_type = "PREFIX_MATCH"
        filter = "example"
      }
    }

    rule {
      destination {
        region = "us-east-1"
        registry_id = data.aws_caller_identity.current.account_id
      }
    }
  }
}
```

### Expected Behavior

The first rule should be created with a repository filter but no destination, with the effect that repositories matching the filter are not replicated anywhere, and all other repositories are replicated to us-east-1.

### Actual Behavior

The provider rejects the first rule due to it having no destination, despite that being [valid according to the AWS API documentation](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_ReplicationRule.html#API_ReplicationRule_Contents).

**Comment by DrFaust92** [comment]
But docs state the destination are required

<img width="723" alt="Screen Shot 2022-04-14 at 9 49 06" src="https://user-images.githubusercontent.com/33663870/163329650-fe6ba289-93d4-4d11-8df4-6efc6ec8a3bc.png">

**Comment by jbg** [comment]
As the screenshot you provided clearly states, the field is required but the minimum number of items in the array is 0.

**Comment by DrFaust92** [comment]
I can confirm by testing locally an empty list can be passed but when trying to work on this i get the following issue:

```
          # aws_ecr_replication_configuration.test will be updated in-place
          ~ resource "aws_ecr_replication_configuration" "test" {
                id          = "******"
                # (1 unchanged attribute hidden)
        
              ~ replication_configuration {
                  ~ rule {
                      + destination {}
                    }
                }
            }
```

**Comment by jbg** [comment]
Can you clarify? I'm not sure what you mean. I linked to the [exact source location of the bug](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ecr/replication_configuration.go#L44) in the first comment. It's fairly simple — the TF provider is just applying validation logic that differs from what AWS actually requires.

**Comment by DrFaust92** [comment]
Ive made change to the code locally and ran some tests, but passing an empty destination causes a perpetual diff, i thought this is a quick fix but doesnt seem to be. i wont be looking into it. if anyone else wants i can share my branch with my current test where they can continue from there.
