### ISSUE TITLE
aws_vpc_endpoint_service errors on service="organizations"

### ISSUE THREAD

**Issue by rollwagen** [hashicorp/terraform-provider-aws#24216]
### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.8
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.9.0

### Affected Resource(s)

* aws_vpc_endpoint_service

### Terraform Configuration Files
AWS_REGION=eu-central-1
```hcl
 data "aws_vpc_endpoint_service" "interface" {
  service_type = "Interface"

  # service = "securityhub"  - works just fine

  service = "organizations"
  # this produces: error reading VPC Endpoint Service
  # (com.amazonaws.eu-central-1.organizations): InvalidServiceName: The Vpc
  # Endpoint Service 'com.amazonaws.eu-central-1.organizations' does
  #  not exist
}
output "interface"{
  value = data.aws_vpc_endpoint_service.interface
}

```

### Actual Behavior

The actual correct service endpoint for 'organizations' should be returned.

The Service Endpoints for AWS Organization for eu-central-1 are:

- organizations.us-east-1.amazonaws.com
- organizations-fips.us-east-1.amazonaws.com
- organizations.us-east-1.amazonaws.com

See ‘Service endpoints’ section at <https://docs.aws.amazon.com/general/latest/gr/ao.html>

### Steps to Reproduce

Run `terraform plan` on above sample hcl (region/account in eu-central-1)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by justinretzolk** [comment]
Hey @rollwagen 👋 Thank you for taking the time to raise this! I don't have the necessary resources available to easily test this, but did notice the following note in the [`aws_vpc_endpoint_service`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/vpc_endpoint_service) data source documentation:

> Specifying `service` will not work for non-AWS services or AWS services that don't follow the standard `service_name` pattern of `com.amazonaws.<region>.<service>`.

With that in mind, I tested the following two options (using an endpoint service that _was_ more easily accessible to me,  and that doesn't fit the `com.amazonaws.<region>.<service>` pattern -- `sagemaker`), and am curious as to whether either works in your case as well.

**Option 1:**

```hcl
data "aws_vpc_endpoint_service" "interface" {
  service_type = "Interface"
  service_name = "organizations.us-east-1.amazonaws.com"
}
```

**Option 2:**

```hcl
data "aws_vpc_endpoint_service" "interface" {
  filter {
    name = "service-name"
    values = ["organizations.us-east-1.amazonaws.com"]
  }

  filter {
    name = "service-type"
    values = ["Interface"]
  }
}
```

**Comment by rollwagen** [comment]
Thanks a lot, @justinretzolk for looking into this, and especially for the suggested workarounds.
Tried both of them, unfortunately, not much success:

**Option 1**
```
Error: error reading VPC Endpoint Service (com.amazonaws.us-east-1.organizations): InvalidServiceName: The Vpc Endpoint Service 'com.amazonaws.us-east-1.organizations' does not exist

Error: error reading VPC Endpoint Service (organizations.us-east-1.amazonaws.com): InvalidServiceName: The Vpc Endpoint Service 'organizations.us-east-1.amazonaws.com' does not exist
```
 **Option 2**
```
 Error: no matching VPC Endpoint Service found
```
What also confused me a bit to be honest, although AWS lists the organizaitons endpoint services here: <https://docs.aws.amazon.com/general/latest/gr/ao.html>, they are not included/listed when running:
`aws ec2 describe-vpc-endpoint-services`
