### ISSUE TITLE
Suppress output for OpenAPI api_gateway_rest_api

### ISSUE THREAD

**Issue by s16tom** [hashicorp/terraform-provider-aws#24217]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm using the api_gateway_rest_api resource with an OpenAPI body param. The body is read from a file in S3 at runtime using a template into which some variables are injected. The template file has about 75 endpoints and is about 10,000 lines long. I've got 5 such APIs in my Terraform module.

Whenever this file is read or updated as part of a terraform plan, the usefulness of the console output from terraform is severely diminished - it is very hard to actually find what is changing in the config, to do so takes a lot of scrolling and searching, and that's if changes in the output aren't missing due to terminal buffer limits.

My suggestion is either that there is a way to suppress the output of this particular resource so that the whole file is not dumped to the console, or that the output only displays lines that will / might be changed.

### New or Affected Resource(s)

- aws_api_gateway_rest_api

**Comment by AdamTylerLynch** [comment]
Using the OpenAPI Import feature defers the validation and change management outside of Terraform and to the AWS Control Plane for API Gateway. If the user would prefer the Terraform plan outputs in the Terraform plan/diff format, the recommendation would be to use OpenAPI Specification for the resource/method/integrations, and use Terraform HCL configuration for endpoints (and other top level configurations).
