### ISSUE TITLE
Cannot create RDS parameter groups with static or dynamic variables

### ISSUE THREAD

**Issue by david-b8-ncsc** [hashicorp/terraform-provider-aws#24219]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.6
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.41.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

aws_db_parameter_group
aws_rds_cluster_parameter_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```
resource "aws_rds_cluster_parameter_group" "aurora-cluster-parameter-group" {
  name        = var.db_parameter_group
  family      = "aurora-mysql5.7"
  description = "RDS cluster parameter group"

  dynamic "parameter" {
    for_each = var.db_parameters
    content {
      name         = parameter.value.name
      value        = parameter.value.value
      apply_method = parameter.value.apply_method
    }
  }
}
```

### Expected Behavior

RDS parameter group created

### Actual Behavior

module.partymanager_aurora.aws_db_parameter_group.aurora-instance-parameter-group: Still creating... [53m50s elapsed]
Error: error modifying DB Cluster Parameter Group: InternalFailure: An internal error has occurred. Please try your query again at a later time.
status code: 500, request id: 5784a910-05a2-4743-92b9-9ad687e52358

**Comment by mattk-ce** [comment]
I've confirmed this is still a problem on 4.30.0.  I tried to create the `rds.enable_plan_management` parameter, but I get this `Error: error modifying DB Cluster Parameter Group: InvalidParameterCombination: cannot use immediate apply method for static parameter`

**Comment by allisonphillips** [comment]
What happens if you aren't using dynamic blocks? This reads like it could be an issue with the config or modifications you're dynamically defining. Have you tried replacing `var.db_parameter_group` with an actual string, validating the correctness of the db_parameters you're iterating over, or temporarily reduced your set of db_parameters to 1 param to see if you can get it to succeed? 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_parameter_group
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Modifying.html
