### ISSUE TITLE
`aws_ec2_client_vpn_network_association`: expose description argument 

### ISSUE THREAD

**Issue by guidoiaquinti** [hashicorp/terraform-provider-aws#24212]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
The `aws_ec2_client_vpn_network_association` resource currently doesn't support the description definition.

### Potential Terraform Configuration
It could be nice to be able to do something like this:
```hcl
resource "aws_ec2_client_vpn_network_association" "vpn_subnets" {
  for_each = data.aws_subnet_ids.target.ids
  description = "Associate VPN network to VPC subnet ${each.value}"
  client_vpn_endpoint_id = aws_ec2_client_vpn_endpoint.vpn.id
  subnet_id = each.value
}
```

**Comment by justinretzolk** [comment]
Hey @guidoiaquinti 👋 Thank you for taking the time to raise this! Looking at this resource, it [uses](https://github.com/hashicorp/terraform-provider-aws/blob/8393fa93c38d802a52d923022d4a5de04f299a88/internal/service/ec2/client_vpn_network_association.go#L82) `ec2.AssociateClientVpnTargetNetwork` to create the association. This function takes a [type of `ec2. AssociateClientVpnTargetNetworkInput`](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#AssociateClientVpnTargetNetworkInput), which does not have a `description` field, so unfortunately we're limited by the underlying SDK in this case. With that in mind, we'll close this request, however, if there are changes in the future that allow for the addition of a `description` argument, we'd be happy to take another look!

**Comment by guidoiaquinti** [comment]
Thank you for your reply @justinretzolk and sorry as I've probably saw the wrong type earlier. I'll reopen this if/when the underlying SDK will support it. Thank you!
