### ISSUE TITLE
Can't Use aws_backup_selection Condition even  in AWSProvider 4.9.0

### ISSUE THREAD

**Issue by jzdzg** [hashicorp/terraform-provider-aws#24235]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

**AWSProvider version:** 
    4.7.0/4.8.0/4.9.0 

**Terraform version:**
    1.1.8

### Affected Resource(s)

- aws_backup_selection

**Symptoms**

When I define aws_backup_selection condition and apply, it failed with error message:

    Error: error creating Backup Selection: InvalidParameterValueException: Invalid backup selection. Either 'ListOfTags' or 'Resources' section must be non-empty.

### Terraform Configuration Files
 
Entire code:
    https://app.box.com/s/x9lngkpdaglns2mq90fzelxtamky8mj5

**Code snippet:**

```hcl
resource "aws_backup_selection" "selection" {
  iam_role_arn = aws_iam_role.default.arn
  name         = "tf_example_backup_selection"
  plan_id      = aws_backup_plan.plan.id
      
  condition {
    string_equals {
      key   = "aws:ResourceTag/Component"
      value = "rds"
    }
    string_like {
      key   = "aws:ResourceTag/Application"
      value = "app*"
    }
    string_not_equals {
      key   = "aws:ResourceTag/Backup"
      value = "false"
    }
    string_not_like {
      key   = "aws:ResourceTag/Environment"
      value = "test*"
    }
  }
}
```
### Debug Output:
  https://gist.github.com/jzdzg/3dd380063ccf61cb2edd4797cf8bca8a

### Steps to Reproduce
1.  configure aws profile
2.  terraform init
3.  terraform apply

**Comment by justinretzolk** [comment]
Hey @jzdzg 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)? I'm particularly interested in debug logs (redacted as necessary), if at all possible.

**Comment by jzdzg** [comment]
Hi @justinretzolk , Thanks for your quick response. I have updated the issue description accordingly. Please let me know if you need anything more.

**Comment by getSurreal** [comment]
Regarding the condition section, it appears that it's structure does not allow for it to be variablized.  Trying to make it a dynamic block with for_each is not possible.  Trying to use a here-string is not possible.  Am I missing something?  How would pass in custom conditions to this resource in a module?

**Comment by jzdzg** [comment]
> Regarding the condition section, it appears that it's structure does not allow for it to be variablized. Trying to make it a dynamic block with for_each is not possible. Trying to use a here-string is not possible. Am I missing something? How would you pass in custom conditions to this resource in a module?

You can refer to the entire code at https://app.box.com/s/x9lngkpdaglns2mq90fzelxtamky8mj5

I just did exactly the same as what is mentioned in the documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_selection

**Comment by getSurreal** [comment]
@jzdzg I looked at your module and you did not use a variable for condition, you just use the hardcoded values.

**Comment by jzdzg** [comment]
> @jzdzg I looked at your module and you did not use a variable for condition, you just use the hardcoded values.

The code is for quick demo of the problem. Even the hard coding can't work, no saying passing the value via a variable.

**Comment by jzdzg** [comment]
@weel  @justinretzolk  It works by adding  resources = ["*"].
But it is inconsistent with the contents in the AWS provider documentation below. I got the error by following the documentation. The documentation needs to be modified.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_selection
