### ISSUE TITLE
Resource aws_fsx_ontap_file_system allow deployment type Single AZ

### ISSUE THREAD

**Issue by varunrai** [hashicorp/terraform-provider-aws#24231]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As per the update to FSx for NetApp ONTAP, the file system now supports Single AZ deployment mode.

Currently, the option for selecting the deployment type in the provider is limited to MULTI_AZ_1.

### New or Affected Resource(s)

* aws_fsx_ontap_file_system

### Potential Terraform Configuration

```hcl
resource "aws_fsx_ontap_file_system" "fsx_ontap_fs" {
  storage_capacity    = 1024
  subnet_ids          = [aws_subnet.fsxsubnet01.id]
  deployment_type     = "SINGLE_AZ_1"
  throughput_capacity = 128
  preferred_subnet_id = aws_subnet.fsxsubnet01.id
}
```

### References
[Release News](https://aws.amazon.com/about-aws/whats-new/2022/04/amazon-fsx-netapp-ontap-single-availability-zone-deployment/)
[Documentation](https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/high-availability-AZ.html)

**Comment by DrFaust92** [comment]
Related https://github.com/hashicorp/terraform-provider-aws/pull/24234
