### ISSUE TITLE
support to add tags

### ISSUE THREAD

**Issue by gopi-rafay** [hashicorp/terraform-provider-aws#24238]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

aws console is showing tags option to add the tags for the grafana workspace but couldn't add tags using the terraform

Error: Unsupported argument
│ 
│   on AMG/main.tf line 9, in resource "aws_grafana_workspace" "grafana_workspace":
│    9:   tags = merge(
│ 
│ An argument named "tags" is not expected here.

terraform version used v1.1.7
aws provider version 4.9.0

### New or Affected Resource(s)

- aws_grafana_workspace

**Comment by dirk39** [comment]
Let me have a look at it
