### ISSUE TITLE
add tags to security_group_rule

### ISSUE THREAD

**Issue by akornatskyy** [hashicorp/terraform-provider-aws#24241]
[Amazon EC2 adds Resource Identifiers and Tags for VPC Security Group Rules](https://aws.amazon.com/about-aws/whats-new/2021/07/amazon-ec2-adds-resource-identifiers-tags-vpc-security-groups-rules/)

**Comment by ewbankkit** [comment]
@akornatskyy Thanks for raising this issue.
It has already been noticed in #20104. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
