### ISSUE TITLE
Crash attempting to update `aws_shield_protection_group`

### ISSUE THREAD

**Issue by t-davies** [hashicorp/terraform-provider-aws#24245]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_shield_protection_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_servicequotas_service_quota" "eips" {
  quota_code   = "L-0263D0A3"
  service_code = "ec2"
  value        = length(local.azs) * 2
}

##############################################
# EIP / Cluster
##############################################

resource "aws_eip" "cluster" {
  count      = length(local.private_subnet_ids)
  depends_on = [aws_servicequotas_service_quota.eips]

  vpc = true

  tags = {
    Name = join("-", [
      module.default_tags.aws_name_prefix,
      "eip",
      "nlb",
      join("", [
        module.default_tags.aws_name_suffix,
        replace(element(local.azs, count.index), var.aws_region, "")
      ])
    ])
  }
}

##############################################
# Shield / Cluster
##############################################

data "aws_caller_identity" "current" {}

resource "aws_shield_protection" "cluster" {
  count = length(aws_eip.cluster)

  name = aws_eip.cluster[count.index].tags_all.Name
  resource_arn = join(":", [
    "arn:aws:ec2",
    var.aws_region,
    data.aws_caller_identity.current.account_id,
    "eip-allocation/${aws_eip.cluster[count.index].id}"
  ])
}

resource "aws_shield_protection_group" "cluster_eips" {
  protection_group_id = join("-", [
    module.default_tags.aws_shield_protection_group_name_prefix,
    "apps-nlb"
  ])

  aggregation   = "SUM"
  pattern       = "BY_RESOURCE_TYPE"
  resource_type = "ELASTIC_IP_ALLOCATION"
}
```

### Panic Output

https://gist.github.com/t-davies/4279b11910a5fc57552151d0226a3e34

### Expected Behavior

 - There are no changes to the `aws_shield_protection_group` resource, should have applied and changed nothing.

### Actual Behavior

 - Crashed during apply, state left out-of-sync.

### Steps to Reproduce

1. `terraform apply` (initial provision is ok)
2. `terraform apply`

### Important Factoids

 - AWS Shield Advanced is enabled on the account.

**Comment by justinretzolk** [comment]
Hey @t-davies 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you supply (redacted as needed) debug logs as well?

**Comment by t-davies** [comment]
Thanks, annoyingly (for the purposes of this issue at least..) I destroyed the `aws_shield_protection_group` and reprovisioned it and now can't seem to replicate this to get the debug logs. I don't know if maybe it was in some weird state on the AWS side and returning bad data?

**Comment by anGie44** [comment]
@t-davies @justinretzolk looks like we actually have the arn set to `protection_group_arn` in the resource schema but at this line we're calling just "arn" so the panic occurs as it's not defined. updating the line below to `protection_group_arn` should prevent this.

https://github.com/hashicorp/terraform-provider-aws/blob/2fb8c18cc841189160bbfa298cb9538bb8673eb0/internal/service/shield/protection_group.go#L189

**Comment by t-davies** [comment]
Great spot, thanks for the fix @anGie44!
