### ISSUE TITLE
Delete of S3 bucket triggers GuardDuty

### ISSUE THREAD

**Issue by ericrichtert** [hashicorp/terraform-provider-aws#24257]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v1.1.8
on windows_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.75.1

### Affected Resource(s)

* aws_bucket
* aws_s3_bucket_logging

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket" "tf-statebucket" {
  bucket = "somename"
}
resource "aws_s3_bucket_logging" "tf-statebucket-logging" {
  bucket = aws_s3_bucket.tf-statebucket.bucket

  target_bucket = "somelogbucket"
  target_prefix = "somename"
}
```

### Expected Behavior
Bucket being deleted, without triggering GuardDuty

### Actual Behavior
When we destroy a bucket, the terraform way of working is:
1) destroy the aws_s3_bucket_logging object
2) destroy the bucket

After step 1, GuardDuty will be triggered, because the accesslog config is removed.

Is it possible to delete the bucket first, and then remove the other "aws_bucket_*" objects for the same bucket from the state?

### Steps to Reproduce

1. `terraform destroy`

**Comment by justinretzolk** [comment]
Hey @ericrichtert 👋

> Is it possible to delete the bucket first, and then remove the other "aws_bucket_*" objects for the same bucket from the state?

One option is to remove the `aws_bucket_*` resources from the state and configuration _before_ destroying the S3 bucket itself. Those resources will all be deleted along with the S3 bucket itself, and removing them from the state and configuration will mean that Terraform has no "knowledge" of those resources, and won't attempt to delete them in an order that is undesirable.

**Comment by ljluestc** [comment]
```
# Remove the logging configuration first
resource "aws_s3_bucket_logging" "tf-statebucket-logging" {
  bucket = aws_s3_bucket.tf-statebucket.bucket

  target_bucket = "somelogbucket"
  target_prefix = "somename"
  # Other logging configurations here
}

# Then remove the bucket
resource "aws_s3_bucket" "tf-statebucket" {
  bucket = "somename"
  # Other bucket configurations here

  # Depends on the logging resource
  depends_on = [aws_s3_bucket_logging.tf-statebucket-logging]
}

```
