### ISSUE TITLE
Can't create both DynamoDB table and index write autoscaling policy at the same time

### ISSUE THREAD

**Issue by xuandong-openai** [hashicorp/terraform-provider-aws#24282]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

* aws_appautoscaling_target
* aws_appautoscaling_policy

### Terraform Configuration Files
```
resource "aws_appautoscaling_target" "table_write_target" {
  max_capacity       = 500
  min_capacity       = 100
  resource_id        = "table/{my_table}"
  scalable_dimension = "dynamodb:table:WriteCapacityUnits"
  service_namespace  = "dynamodb"
}

resource "aws_appautoscaling_policy" "table_write_policy" {
  name               = "DynamoDBWriteCapacityUtilization:${table_write_target.resource_id}"
  policy_type        = "TargetTrackingScaling"
  resource_id        = aws_appautoscaling_target.table_write_target.resource_id
  scalable_dimension = aws_appautoscaling_target.table_write_target.scalable_dimension
  service_namespace  = aws_appautoscaling_target.table_write_target.service_namespace

  target_tracking_scaling_policy_configuration {
    predefined_metric_specification {
      predefined_metric_type = "DynamoDBWriteCapacityUtilization"
    }

    target_value = 70
  }
}

resource "aws_appautoscaling_target" "index_write_target" {
  max_capacity       = 500
  min_capacity       = 100
  resource_id        = "table/{my_table}/index/{my_index}"
  scalable_dimension = "dynamodb:index:WriteCapacityUnits"
  service_namespace  = "dynamodb"
}

resource "aws_appautoscaling_policy" "index_write_policy" {
  name               = "DynamoDBWriteCapacityUtilization:${aws_appautoscaling_target.index_write_target.resource_id}"
  policy_type        = "TargetTrackingScaling"
  resource_id        = aws_appautoscaling_target.index_write_target.resource_id
  scalable_dimension = aws_appautoscaling_target.index_write_target.scalable_dimension
  service_namespace  = aws_appautoscaling_target.index_write_target.service_namespace

  target_tracking_scaling_policy_configuration {
    predefined_metric_specification {
      predefined_metric_type = "DynamoDBWriteCapacityUtilization"
    }

    target_value = 70
  }
}
```

### Debug Output

```
Error: Failed to create scaling policy: Error putting scaling policy: ValidationException: Only one TargetTrackingScaling policy for a given metric specification is allowed.

  with aws_appautoscaling_policy.index_write_policy,
```

### Expected Behavior

I expect those I can create autoscaling policy for my table and its GSI at the same time on WCU.

### Actual Behavior
The terraform apply failed and showed me the above error message.

### Steps to Reproduce

1. `terraform apply`

**Comment by justinretzolk** [comment]
Hey @woshilxd912 👋 Thank you for taking the time to raise this! The error you're seeing is coming from the AWS API, rather than from the AWS provider itself, so I'm not certain that this is an issue with the provider in this case. That said, I found a [StackOverflow post](https://stackoverflow.com/questions/57766669/validation-error-only-one-targettrackingscaling-policy-for-a-given-metric-specif) where someone ran into a similar issue that may be of some assistance. If that doesn't help, can you supply full debug logs (redacted as needed) so that we can take a look and see if there's any additional information within that that may point to why you're receiving these errors?
