### ISSUE TITLE
iamInstanceProfile.name is invalid Error

### ISSUE THREAD

**Issue by NetAgent** [hashicorp/terraform-provider-aws#24281]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000
│ Error: Error launching source instance: InvalidParameterValue: Value (demo-avi-controller) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name
│       status code: 400, request id: 7ee1cc0d-1b64-4427-83f1-de0ee5c3cd22
│
│   with aws_instance.avi-controller[0],
│   on avicontroller.tf line 15, in resource "aws_instance" "avi-controller":
│   15: resource "aws_instance" "avi-controller" {

**Comment by justinretzolk** [comment]
Hey @NetAgent 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the bug report template?
