### ISSUE TITLE
Activate AWS User-Defined Cost Allocation Tags using terraform

### ISSUE THREAD

**Issue by sindhu890** [hashicorp/terraform-provider-aws#24307]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There doesn't seem to be anyway of activating the newly created tags by terraform. So I still need to log into my payer account and manually click a button or two to activate the tags.

This seems like a glaringly obvious shortcoming.

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by iamgeef** [comment]
Unless I can't find it, there doesn't appear to be an available AWS API method to "activate User-Defined Cost Allocation Tags" - which would be required for Terraform to support it.
