### ISSUE TITLE
`aws_efs_file_system` when change `performance_mode` will be recreate

### ISSUE THREAD

**Issue by leonardobiffi** [hashicorp/terraform-provider-aws#24301]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.2
+ provider registry.terraform.io/hashicorp/aws v4.10.0

### Affected Resource(s)

* aws_efs_file_system

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

- Create
```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_efs_file_system" "foo" {
  performance_mode = "generalPurpose"
  throughput_mode  = "bursting"
}
```

- Update
```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_efs_file_system" "foo" {
  performance_mode = "maxIO"
  throughput_mode  = "provisioned"
  provisioned_throughput_in_mibps = 100
}
```

### Expected Behavior

Change `performance_mode` without recreate EFS

### Actual Behavior
```
~ performance_mode                = "generalPurpose" -> "maxIO" # forces replacement
```
### Steps to Reproduce

1. `terraform apply`

**Comment by DrFaust92** [comment]
PerformanceMode is not a valid argument for EFS UpdateFileSystem function so this is not possible to implement in the provider.

**Comment by leonardobiffi** [comment]
Hi @DrFaust92 , what do you mean?
In the provider's documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_file_system#performance_mode

I sent PR removing the `ForceNew`, and in my tests this work.

**Comment by DrFaust92** [comment]
https://docs.aws.amazon.com/efs/latest/ug/API_UpdateFileSystem.html performace mode is not updateable though so im not sure how you tested it. removing force new is not enough

**Comment by leonardobiffi** [comment]
@DrFaust92 I understand now,
```
You set the performance mode when you create a file system, and you can't change it after it is created.
```
https://docs.aws.amazon.com/efs/latest/ug/performance.html#performancemodes

Thank you for explanation, was to close this issue
