### ISSUE TITLE
aws_s3_bucket `object_lock_enabled` values not properly documented

### ISSUE THREAD

**Issue by ioah86** [hashicorp/terraform-provider-aws#24311]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v1.1.8
on linux_amd64

### Affected Resource(s)

* aws_s3_bucket

### Issue

I found a small ambiguity in the documentation which should be addressed.
For the aws_s3_bucket, there is a top-level [`object_lock_enabled`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#object_lock_enabled) parameter, which seems to be boolean, and one inside the [`object_lock_configuration`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#object_lock_configuration), which seems to be only taking `Enabled` as parameter according to the documentation. The reader may be confused about the top-level argument while reading: Is it supposed to be "true", or "Enabled"?

Hence, whatever the correct use is should be more carefully documented.

**Comment by AdamJCavanaugh** [comment]
I'll take a look at this.

**Comment by anGie44** [comment]
Hi @ioah86 @AdamJCavanaugh thank you for your feedback on this issue. I think what has worked in the past is to provide users with the list of possible valid values in the documentation to prevent plan/apply time errors. 

So for the root-level `object_lock_enabled` parameter, it's defined in the schema as a boolean value so the valid values we could be more explicit about are `true` or `false`.

For the nested `object_lock_enabled` parameter within the `object_lock_configuration` block, it's defined as a String and AWS only supports the value `Enabled` at this time.

**Comment by AdamJCavanaugh** [comment]
I tested in my account for the root-level `object_lock_enabled` parameter and only `"Enabled"` worked for me.

```
│ Error: expected object_lock_configuration.0.object_lock_enabled to be one of [Enabled], got true
│
│   with aws_s3_bucket.example,
│   on test.tf line 5, in resource "aws_s3_bucket" "example":
│    5:     object_lock_enabled = true
```

**Comment by anGie44** [comment]
Ahh i see. So by root-level, i intended the following configuration:
```terraform
resource "aws_s3_bucket" "example" {
  bucket = "my-tf-example-bucket"

  object_lock_enabled = true
  
  #  ... other configuration ...
}
```

And then "nested" param within the object_lock_configuration block would be the example you've provided. Maybe we can update the word choice if used in the public docs as well.

**Comment by AdamJCavanaugh** [comment]
You know, I know exactly what you meant and just mistakenly copy/pasted from example in the document, sorry. I dug through the Data Handling and Conversion guide and specific use cases, and guess I had the same confusion then, too... :/

I've updated my draft PR with valid values of true and false (which is what I would have expected, reading the documentation before having gotten myself confused by this issue).

I think the fact that the default is false implies that it's a boolean and the only other option is true, but I don't mind having it explicit, I guess.
