### ISSUE TITLE
aws_placement_group: Terraform supports 0 value also for partition_count parameter but as per terraform documentation valid value should be 1-7 only

### ISSUE THREAD

**Issue by chennagouda14** [hashicorp/terraform-provider-aws#24318]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.31
AWS Provider v3.70.0

### Affected Resource(s)

* aws_placement_group

### Details
•	partition_count parameter accepts valid values from 1 – 7 only as per terraform documentation. This parameter must be specified only when strategy parameter is set to "partition". Default value is 2.
•	Placement group resource ideally supports values from 1-7 only, AWS CLI & AWS console also accepts valid values from 1-7 only (0 is not accepted).
•	But we have observed that terraform also supports 0 value along with values 1 – 7.

### Terraform Configuration Files

partition_count parameter is specified with 0 & strategy parameter is set to "partition".

resource "aws_placement_group" "test" {
  name            = "test-placement-group01"
  partition_count = 0
  strategy        = "partition"
}

### Expected Behavior

First terraform apply should throw an error if 0 value is specified for this parameter, as the allowed values are only 1-7 for this resource.

### Actual Behavior

First terraform apply is successfully done, but the partition_count value is set with 2 instead of 0 because the default value for partition_count parameter is 2
terraform apply does not throw any error when 0 value is provided to this parameter. 
 
![image](https://user-images.githubusercontent.com/90911826/164166147-2d35a8a5-e58c-493d-b192-5ee49bd8988a.png)

Second Terraform apply output:  
![image](https://user-images.githubusercontent.com/90911826/164166254-a5cd2eca-64d2-46b8-8c48-786f23af2f6b.png)

If second terraform apply is done, then terraform detects a change as the previously applied parameter value was 0. Therefore, terraform does force replacement of this resource, this will happen in every consecutive terraform apply’s & this goes on a loop, but the actual value is not getting applied on the AWS console i.e 0.

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply (without any modifications made to the configuration)`

### References
https://registry.terraform.io/providers/hashicorp/aws/3.70.0/docs/resources/placement_group

**Comment by chennagouda14** [comment]
@justinretzolk Any updates on this issue?

**Comment by justinretzolk** [comment]
Hey @chennagouda14 👋 Thank you for checking in on this. Unfortunately, I'm not able to provide an estimate on when this will be looked into due to the potential of shifting priorities (we prioritize work by count of ":+1:" reactions, as well as a few other things). A larger prioritization document is in the works, but in the meantime additional information may be found in our [issue lifecycle document](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/issue-reporting-and-lifecycle.md#issue-lifecycle).
