### ISSUE TITLE
aws_eks_node_group's "source_security_group_ids" attribute not applying to EC2 instance

### ISSUE THREAD

**Issue by catherinelam** [hashicorp/terraform-provider-aws#24324]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_eks_node_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_eks_node_group" "eks_nodegroup" {
  cluster_name    = var.cluster_name
  node_group_name = var.node_group_name
  node_role_arn   = var.node_role
  subnet_ids      = var.subnets
  instance_types  = ["t3.small"]
  scaling_config {
    desired_size = var.ng_desired_size
    max_size     = var.ng_max_size
    min_size     = var.ng_min_size
  }
  
  remote_access {
    ec2_ssh_key               = "EKS_Cluster_Key_Pair"
    source_security_group_ids = [data.terraform_remote_state.state.outputs.sg_a,data.terraform_remote_state.state.outputs.sgb]
  }

  depends_on = [aws_eks_cluster.eks_cluster]

}
```

### Expected Behavior

The node group should have been spun up with one EC2 instance with sg_a and sg_b as part of the security group listing.

### Actual Behavior

The EC2 instance that represents the node group's node is spun up, but does not have the proper remote access sg's attached to it as specified in the remote_access block. Only the cluster sg's are attached.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @catherinelam👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you supply (redacted as necessary) debug logs as well?

**Comment by catherinelam** [comment]
I don't know why the downloaded log has all of those strange characters, but this is what the apply log loogs like. And I have configured in the plan log that the .sg_a and .sg_b values expand to what I expect. Is this helpful? I couldn't figure out how to get debug logs. 


`
Terraform v1.1.7
on linux_amd64
Configuring remote state backend...
Initializing Terraform configuration...

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  [32m+[0m create
[0m
Terraform will perform the following actions:

[1m  # aws_eks_cluster.eks_cluster[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "aws_eks_cluster" "eks_cluster" {
      [32m+[0m [0m[1m[0marn[0m[0m                   = (known after apply)
      [32m+[0m [0m[1m[0mcertificate_authority[0m[0m = (known after apply)
      [32m+[0m [0m[1m[0mcreated_at[0m[0m            = (known after apply)
      [32m+[0m [0m[1m[0mendpoint[0m[0m              = (known after apply)
      [32m+[0m [0m[1m[0mid[0m[0m                    = (known after apply)
      [32m+[0m [0m[1m[0midentity[0m[0m              = (known after apply)
      [32m+[0m [0m[1m[0mname[0m[0m                  = "terraformEKS_cl"
      [32m+[0m [0m[1m[0mplatform_version[0m[0m      = (known after apply)
      [32m+[0m [0m[1m[0mrole_arn[0m[0m              = "arn:aws-us-gov:iam::<ID>:role/eksClusterRole"
      [32m+[0m [0m[1m[0mstatus[0m[0m                = (known after apply)
      [32m+[0m [0m[1m[0mtags_all[0m[0m              = (known after apply)
      [32m+[0m [0m[1m[0mversion[0m[0m               = (known after apply)

      [32m+[0m [0mkubernetes_network_config {
          [32m+[0m [0m[1m[0mip_family[0m[0m         = (known after apply)
          [32m+[0m [0m[1m[0mservice_ipv4_cidr[0m[0m = (known after apply)
        }

      [32m+[0m [0mvpc_config {
          [32m+[0m [0m[1m[0mcluster_security_group_id[0m[0m = (known after apply)
          [32m+[0m [0m[1m[0mendpoint_private_access[0m[0m   = true
          [32m+[0m [0m[1m[0mendpoint_public_access[0m[0m    = false
          [32m+[0m [0m[1m[0mpublic_access_cidrs[0m[0m       = (known after apply)
          [32m+[0m [0m[1m[0msecurity_group_ids[0m[0m        = [
              [32m+[0m [0m"sg-0707edb3d7c47b687",
              [32m+[0m [0m"sg-0db4845394a371218",
            ]
          [32m+[0m [0m[1m[0msubnet_ids[0m[0m                = [
              [32m+[0m [0m"subnet-015b8e44e0fabd60e",
              [32m+[0m [0m"subnet-0b5f50664c97619b8",
              [32m+[0m [0m"subnet-0e6c8dd6171b0d4a1",
            ]
          [32m+[0m [0m[1m[0mvpc_id[0m[0m                    = (known after apply)
        }
    }

[1m  # aws_eks_node_group.eks_nodegroup[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "aws_eks_node_group" "eks_nodegroup" {
      [32m+[0m [0m[1m[0mami_type[0m[0m               = (known after apply)
      [32m+[0m [0m[1m[0marn[0m[0m                    = (known after apply)
      [32m+[0m [0m[1m[0mcapacity_type[0m[0m          = (known after apply)
      [32m+[0m [0m[1m[0mcluster_name[0m[0m           = "terraformEKS_cl"
      [32m+[0m [0m[1m[0mdisk_size[0m[0m              = (known after apply)
      [32m+[0m [0m[1m[0mid[0m[0m                     = (known after apply)
      [32m+[0m [0m[1m[0minstance_types[0m[0m         = [
          [32m+[0m [0m"t3.small",
        ]
      [32m+[0m [0m[1m[0mnode_group_name[0m[0m        = "nodegroup_cl"
      [32m+[0m [0m[1m[0mnode_group_name_prefix[0m[0m = (known after apply)
      [32m+[0m [0m[1m[0mnode_role_arn[0m[0m          = "arn:aws-us-gov:iam::921714618144:role/AmazonEKSNodeRole"
      [32m+[0m [0m[1m[0mrelease_version[0m[0m        = (known after apply)
      [32m+[0m [0m[1m[0mresources[0m[0m              = (known after apply)
      [32m+[0m [0m[1m[0mstatus[0m[0m                 = (known after apply)
      [32m+[0m [0m[1m[0msubnet_ids[0m[0m             = [
          [32m+[0m [0m"subnet-015b8e44e0fabd60e",
          [32m+[0m [0m"subnet-0b5f50664c97619b8",
          [32m+[0m [0m"subnet-0e6c8dd6171b0d4a1",
        ]
      [32m+[0m [0m[1m[0mtags_all[0m[0m               = (known after apply)
      [32m+[0m [0m[1m[0mversion[0m[0m                = (known after apply)

      [32m+[0m [0mremote_access {
          [32m+[0m [0m[1m[0mec2_ssh_key[0m[0m               = "EKS_Cluster_Key_Pair"
          [32m+[0m [0m[1m[0msource_security_group_ids[0m[0m = [
              [32m+[0m [0m"<sg_a>",
              [32m+[0m [0m"<sg_b>",
            ]
        }

      [32m+[0m [0mscaling_config {
          [32m+[0m [0m[1m[0mdesired_size[0m[0m = 1
          [32m+[0m [0m[1m[0mmax_size[0m[0m     = 1
          [32m+[0m [0m[1m[0mmin_size[0m[0m     = 1
        }

      [32m+[0m [0mupdate_config {
          [32m+[0m [0m[1m[0mmax_unavailable[0m[0m            = (known after apply)
          [32m+[0m [0m[1m[0mmax_unavailable_percentage[0m[0m = (known after apply)
        }
    }

[0m[1mPlan:[0m 2 to add, 0 to change, 0 to destroy.
[0m
`

**Comment by justinretzolk** [comment]
Hey @catherinelam 👋 Thanks for getting back to us so fast! I apologize for not providing information on enabling debugging in my first reply. Unfortunately that didn't quite provide the level of detail we'll need, so we'll still need to get debug logs. Since it looks like you might be using a remote backend, I tracked down one of the articles that our Support folks wrote for enabling debugging in various scenarios. That document may be found [here](https://support.hashicorp.com/hc/en-us/articles/360001113727-Enabling-debug-and-trace-run-logs-in-Terraform-CLI-Cloud-or-Enterprise).

**Comment by catherinelam** [comment]
Hi @justinretzolk! Here is a gist link - https://gist.github.com/catherinelam/09edfa7fad66d5d30a8d07d548c4c6d0

Kind of a Github noob, so let me know if it looks right. I cut off the apply at 5 minutes because the EC2 instance had come up, and currently having issues with ng joining the cluster, so it was just going to repeat for 26 minutes.

**Comment by catherinelam** [comment]
That was due to redaction efforts. The full security group ID was shown before I redacted. They were in the format sg-#########

**Comment by bigmikes** [comment]
Hi @catherinelam, 

> The EC2 instance that represents the node group's node is spun up, but does not have the proper remote access sg's attached to it as specified in the remote_access block. Only the cluster sg's are attached.

Let's call the _cluster sg_ `sg-c`. Can you check if the `sg-a` and `sg-b` are specified as source in one ingress rule of `sg-c`? This ingress rule should allow TCP traffic on port 22 (SSH).

My understanding of [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#remote_access-configuration-block) is that the Security Group IDs you specify in `source_security_group_ids` are not expected to be attached to the EC2 instance, but rather configured in some ingress rule to allow SSH traffic from those Security Groups. I'd guess that this rule is configured on the cluster's SG.

**Comment by catherinelam** [comment]
Hi, Guilio:

You’re correct! It does show up as the source! But…. Now what I don’t understand is why I can’t SSH into the node with my specified key. As it stands when I spin it up, those security groups I mentioned in this ticket do show up under sg-c’s (called “eks-remoteAccess-#########”) inbound rules as individual security group rules. So in this scenario, no SSH access.

BUT. If I add those sg-a’s and sg-b’s manually to the EC2 instance, then SSH access is successfully established. Is there a setting I am missing here?

Thanks so much for your wise advice 😊

Catherine

From: Giulio Micheloni ***@***.***>
Sent: Sunday, April 24, 2022 11:59 AM
To: hashicorp/terraform-provider-aws ***@***.***>
Cc: Lam, Catherine ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [hashicorp/terraform-provider-aws] aws_eks_node_group's "source_security_group_ids" attribute not applying to EC2 instance (Issue #24324)


This message is from an EXTERNAL SENDER - be CAUTIOUS of links and attachments. THINK BEFORE YOU CLICK.
________________________________


Hi @catherinelam<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcatherinelam&data=05%7C01%7Ccatherine.lam%40accenturefederal.com%7C88441adcd5a64254e2a808da260b6535%7C0ee6c63b4eab4748b74ad1dc22fc1a24%7C0%7C0%7C637864127655578182%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0tDuj%2BRI91g9OeCetz3imYGlI4NR5Jj7J4wlpk%2BjXro%3D&reserved=0>,

The EC2 instance that represents the node group's node is spun up, but does not have the proper remote access sg's attached to it as specified in the remote_access block. Only the cluster sg's are attached.

Let's call the cluster sg sg-c. Can you check if the sg-a and sg-b are specified as source in one ingress rule of sg-c? This ingress rule should allow TCP traffic on port 22 (SSH).

My understanding of documentation<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fregistry.terraform.io%2Fproviders%2Fhashicorp%2Faws%2Flatest%2Fdocs%2Fresources%2Feks_node_group%23remote_access-configuration-block&data=05%7C01%7Ccatherine.lam%40accenturefederal.com%7C88441adcd5a64254e2a808da260b6535%7C0ee6c63b4eab4748b74ad1dc22fc1a24%7C0%7C0%7C637864127655734410%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mPFNEMq3QXKZlAuT9NHGQ3EmBgQXvOc4eDLNiJ1n%2BQc%3D&reserved=0> is that the Security Group IDs you specify in source_security_group_ids are not expected to be attached to the EC2 instance, but rather configured in some ingress rule to allow SSH traffic from those Security Groups. I'd guess that this rule is configured on the cluster's SG.

**Comment by bigmikes** [comment]
> Now what I don’t understand is why I can’t SSH into the node with my specified key.
It depends on whether the SSH connection is initiated from one of those two Security Groups. Are you trying to connect to the node from your laptop or from another EC2 instance assigned to either `sg-a` or `sg-b`?

> BUT. If I add those sg-a’s and sg-b’s manually to the EC2 instance, then SSH access is successfully established. Is there a setting I am missing here?
It depends on what rules `sg-a` and `sg-b` have. It is possible that one of them has an ingress rule open SSH traffic from 0.0.0.0/0. Can you check? If that isn't the case, then can you provide more details on the security rules and where the SSH connection source?
