### ISSUE TITLE
aws_default_security_group does not delete manually added rules if you do not define an ingress / egress

### ISSUE THREAD

**Issue by T00mm** [hashicorp/terraform-provider-aws#24321]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

* Terraform v1.1.3
* AWS provider 4.9.0

### Affected Resource(s)

* aws_default_security_group

### Terraform Configuration Files

```hcl
resource "aws_default_security_group" "default" {
    vpc_id = var.default_vpc
}
```

### Debug Output

```hcl
Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # aws_default_security_group.default has changed
  ~ resource "aws_default_security_group" "default" {
      ~ egress                 = [
          + {
              + cidr_blocks      = [
                  + "127.0.0.0/32",
                ]
              + description      = "manualstuff"
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 65535
            }
        ]
        id                     = "sg-05545834985"
        name                   = "default"
        tags                   = {}
        # (7 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo
or respond to these changes.

───────

No changes. Your infrastructure matches the configuration.
```

### Expected Behavior

All security group rules not defined in Terraform should be deleted.

### Actual Behavior

It will import the manually added rules to the tfstate.

### Steps to Reproduce

1.  Add a manual rule to the default security group 
2. `terraform apply`

**Comment by bigmikes** [comment]
Hi @T00mm, can you try to set the `egress` argument to an empty list? For example:

```terraform
resource "aws_security_group" "test" {
  egress  = []
  ingress = []
  tags = {
    Name = "terraform-testacc-security-group-ingress-config-mode"
  }

  vpc_id = aws_vpc.test.id
}
```

`egress` and `ingress` are optional arguments, so if you don't specify them, Terraform will ignore them during the diff calculation. Setting both arguments to empty list make sense, as the explicit user intention is to have no rules on the Security Group. If this intention is not provided, Terraform cannot make any assumption for optional fields.

**Comment by T00mm** [comment]
Hi, that indeed works. 

Was not aware this was possible as the documentation talks about ingress/egress as dictionary but when looking at the `terraform plan` it does seem to be a list with dicts inside of it.

Thank for the information.
