### ISSUE TITLE
aws_devicefarm_upload

### ISSUE THREAD

**Issue by hamidre13** [hashicorp/terraform-provider-aws#24329]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000
Hi, I am new here working with aws_devicefarm_upload.
The URL that is returning cannot upload the files and I am getting a signature mismatch error but when I make a request from the API the URL works fine. I am suspecting that terraform is formatting the signature part of the query parameter and changing it. The rest of the query string parameters seesms to be the same.

**Comment by justinretzolk** [comment]
Hey @hamidre13 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the bug report template? It looks like you've got the template in the issue description already, but the information within the template is missing.

**Comment by justinretzolk** [comment]
Since we haven't heard back, we'll close this issue for now. If you're still experiencing this, please feel free to open a new issue (or add an upvote to the issue linked to this one).
