### ISSUE TITLE
AWS CloudFront S3 Redirect Domain

### ISSUE THREAD

**Issue by subaquatic-pierre** [hashicorp/terraform-provider-aws#24332]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

There is an error when creating AWS CloudFront distribution linked to AWS S3 bucket which is configured to redirect all requests.

The cloudfront does not point to the correct origin domain.

### Terraform Version

Terraform v1.1.8
on linux_amd64

### Terraform Configuration Files

This iis the part of the config with an error.

```hcl
resource "aws_cloudfront_distribution" "redirect" {
  origin {

    # ------- Error here ----------
    # 
    # Manual configuration in AWS console to this value works as expected
    # eg. DOC-EXAMPLE-BUCKET.s3-website-us-east-1.amazonaws.com
    # 
    # domain_name = aws_s3_bucket_website_configuration.redirect.website_endpoint
    # 
    # --------- Error here ----------

    domain_name = aws_s3_bucket.redirect.bucket_domain_name

    origin_id = local.s3_origin_id_redirect
```

github repo: https://github.com/subaquatic-pierre/pwa-infrastructure

### Expected Behavior

WWW cloudfront should redirect to root domain

### Actual Behavior

Receive access denied error.

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

**Comment by justinretzolk** [comment]
Hey @subaquatic-pierre 👋 Thank you for taking the time to raise this! For a bit of clarity, are you receiving access denied errors when creating these resources with Terraform, or is the error that you're receiving once you've created the resources and are attempting to use them?

**Comment by subaquatic-pierre** [comment]
Hey @justinretzolk, sorry for the confusion. It is from the resource once create, it is the XML response from the bucket / cloudfront.

Similar to this error.

https://aws.amazon.com/premiumsupport/knowledge-center/s3-website-cloudfront-error-403/

**Comment by justinretzolk** [comment]
Hey @subaquatic-pierre -- thanks for that additional info! It sounds like this is probably more of a configuration issue, so you may have better luck using one of our [community resources](https://www.terraform.io/docs/extend/community/index.html) or the [AWS Provider Discuss forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). That said, since I don't know for certain, I'm happy to keep looking at it with you here if you prefer. It may be helpful if you could supply some of the error logs you mentioned seeing (redacted as necessary), so that I can get a better idea of what errors are being thrown.
