### ISSUE TITLE
Error in transit_gateway_vpc_attachment resource: .tags_all

### ISSUE THREAD

**Issue by nl-brett-stime** [hashicorp/terraform-provider-aws#24343]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

% terraform_1 -v
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.75.1

### Affected Resource(s)

* aws_ec2_transit_gateway_vpc_attachment

### Expected Behavior

Transit gateway attachment provisioned without error.

### Actual Behavior

Terraform throws the following error: 

> │ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.tgw_attachment_ambigress.aws_ec2_transit_gateway_vpc_attachment.this to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "Name" has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by nl-brett-stime** [comment]
One thing that might be a factor is that we're using provider-level tags in our config:

```
provider "aws" {
  region = "eu-west-2"

  ignore_tags {
    key_prefixes = ["AutoTag_"]
  }

  default_tags {
    tags = merge(module.init_data.common_tags, {
      environment = local.app_instance
    })
  }
}
```

**Comment by nicoodle** [comment]
We've experienced the same issue. We have also got tags set at a provider level with `default_tags`. 

Some resources have extra tags added via tags. Like so: 
```hcl
  tags = merge(local.tags, {
    Name                                            = "${module.eks_control_plane.cluster_name}${each.key}NodeGroup"
    "k8s.io/cluster-autoscaler/enabled"             = each.value["autoscaling"]
    "k8s.io/cluster-autoscaler/${var.cluster_name}" = "owned"
  })
```

Producing the following error:
```
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.okp.aws_eks_node_group.private["BaseM5AD"] to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "Name" has appeared.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

A second run after the initial failure succeeds. 

```
Terraform v1.0.11
on darwin_arm64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.11.0
+ provider registry.terraform.io/hashicorp/helm v2.5.1
+ provider registry.terraform.io/hashicorp/http v2.1.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.10.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/hashicorp/tls v3.3.0
```

**Comment by ajoga** [comment]
This issue looks similar or to duplicate #19583
