### ISSUE TITLE
Add support for AWS Glue autoscaling feature

### ISSUE THREAD

**Issue by m4t22** [hashicorp/terraform-provider-aws#24356]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has added new feature for AWS Glue - autoscaling: https://aws.amazon.com/about-aws/whats-new/2022/04/autoscaling-aws-glue-now-generally-available/ 
It would be nice to be able to define it using terraform.

### New or Affected Resource(s)

* aws_glue_job

### Potential Terraform Configuration

```hcl
resource "aws_glue_job" "example" {
  name     = "example streaming job"
  role_arn = aws_iam_role.example.arn
  use_autoscaling = true

  command {
    name            = "gluestreaming"
    script_location = "s3://${aws_s3_bucket.example.bucket}/example.script"
  }
}
```

**Comment by DrFaust92** [comment]
There is currently no such argument in the aws go sdk for glue job resouce.
