### ISSUE TITLE
The import example is broken in the CloudWatch Dashboard resource reference.

### ISSUE THREAD

**Issue by nyagato-00** [hashicorp/terraform-provider-aws#24355]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_cloudwatch_dashboard

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

- provider version : 4.10.0
- terraform version: 1.1.7

### Expected Behavior
The import example is displayed correctly.

|before|after|
|---|---|
|![スクリーンショット 2022-04-22 16 52 28](https://user-images.githubusercontent.com/12161701/164643224-b21353df-795b-40d4-94fd-7312de1350dd.png)|![スクリーンショット 2022-04-22 16 52 54](https://user-images.githubusercontent.com/12161701/164643242-9dcc09de-6d9c-4457-9788-d5c1424e7c2e.png)|

### Actual Behavior
The command shown in the import example is incomplete.
> CloudWatch dashboards can be imported using the dashboard_name, e.g.,

but the dashboard_name is missing from the example.

https://github.com/hashicorp/terraform-provider-aws/blob/8ce7445406242446a7bff6aa17d07b0f906c61c6/website/docs/r/cloudwatch_dashboard.html.markdown?plain=1#L72-L78

### Steps to Reproduce
Please browse the page at the URL below.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_dashboard#import

### suggestion
I would be willing to create and modify a PR if you would just modify it as follows

```diff
- $ terraform import aws_cloudwatch_dashboard.sample <dashboard_name>
+ $ terraform import aws_cloudwatch_dashboard.sample dashboard_name
```

**Comment by DrFaust92** [comment]
Thanks [nyagato-00](https://github.com/nyagato-00). PR is appreciated!
