### ISSUE TITLE
Error provisioning Service Catalog Product: InvalidParametersException: Multiple Provisioning Artifact with name AWS Control Tower Account Factory found.

### ISSUE THREAD

**Issue by rambhaskark** [hashicorp/terraform-provider-aws#24362]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.75.1
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v2.2.0

Your version of Terraform is out of date! The latest version
is 1.1.9. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

* aws_service_catalog

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_version = ">= 1.0.0"
    required_providers {
    aws      = "~> 3.75.0"    
    local    = "~> 1.4"
    template = "~> 2.1"
    tls      = "~> 2.1"
  }
  backend "s3" {}
}

provider "aws" {  
  region  = var.region
}

resource "aws_servicecatalog_provisioned_product" "account_factory" {
  name = var.name
 product_name = var.product_name
 provisioning_artifact_name = var.provisioning_artifact_name
  
  provisioning_parameters {
        key = "AccountEmail"
        value = var.account_email
  }
  provisioning_parameters {
        key = "AccountName"
        value = var.account_name
  }
  provisioning_parameters {
        key = "ManagedOrganizationalUnit"
        value = var.managed_ou    
  }
  provisioning_parameters {
        key = "SSOUserEmail"
        value = var.sso_user_email      
  }
  provisioning_parameters {
        key = "SSOUserFirstName"
        value = var.sso_first_name   
  }
  provisioning_parameters {
        key = "SSOUserLastName"
        value = var.sso_last_name 
  }

  tags = var.tags

}
```

### Expected Behavior

Though there are multiple versions of the provisioning artifact for the given product exists, only the default or active one should be picked and created.

### Actual Behavior

received following error:

```plaintext
Error: error provisioning Service Catalog Product: InvalidParametersException: Multiple Provisioning Artifact with name AWS Control Tower Account Factory found.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @rambhaskark 👋 Thank you for taking the time to raise this! It looks like this error is coming from the underlying API, however, I noticed that you mentioned that there are multiple versions with the same name. My read of the documentation is that in situations such as this, you can opt to use `provisioning_artifact_id` rather than `provisioning_artifact_name` in order to pass the ID of the appropriate choice. Is that something that might work for you in this case?

**Comment by rambhaskark** [comment]
Hi @justinretzolk , thanks for the suggestion. The fact I wanted to use the provisioning_artifact_name is to get rid of the hardcoded provisioning_artifact_id which may become obsolete as new versions get rolled out. This would also mean losing out on the latest product updates. Moreover, the script would fail if the mentioned provisioning_artifact_id is no longer available due to new changes at the product.

**Comment by brhankel** [comment]
This is also occurring directly via the AWS CLI.
'An error occurred (InvalidParametersException) when calling the ProvisionProduct operation: Multiple Provisioning Artifact with name AWS Control Tower Account Factory found.' 

Raising an issue with AWS as it could be an API issue.
