### ISSUE TITLE
Flaky bug: error reading EventBridge Rule

### ISSUE THREAD

**Issue by Veetaha** [hashicorp/terraform-provider-aws#24376]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

- terraform CLI: `v1.1.7`
- AWS provider:  `v4.8.0`

### Affected Resource(s)

* aws_cloudwatch_event_rule

### Terraform Configuration Files

```hcl
locals {
  schedules = {
    "15minutes" = "cron(0/15 * * * ? *)"
    "30minutes" = "cron(0/30 * * * ? *)"
    "1hour" = "cron(0 * * * ? *)"
    "12hours" = "cron(0 0/12 * * ? *)"
    "daily"   = "cron(0 0 * * ? *)"
    "weekly"  = "cron(0 0 * * ? *)"
    "monthly" = "cron(0 0 * * ? *)"
  }
  component = "scheduler"
  tags = {
    "elastio:component" = local.component
  }
}

resource "aws_cloudwatch_event_rule" "schedule" {
  for_each = local.schedules

  name        = "elsatio-schedule-${each.key}"
  description = "A rule to invoke the scheduler lambda with specific rate"

  schedule_expression = each.value

  tags = local.tags
}
```

### Debug Output

Unfortunately, there aren't logs with `TF_LOG=debug` available. This bug reproduced only once our CI, where we don't have verbose debug logging enabled because it produces too much output... However, here is the output of regular terraform logs captured in the gist.

It also includes very little amount of additional logs from the automation script wrapped around it.
This includes `terraform init` with the remote s3+dynamodb backend and `terraform apply`.

The AWS account ID was replaced with `{REDACTED_ACCOUNT_ID}` in the output just for additional privacy

https://gist.github.com/Veetaha/eb49781bb57b441bcccfe45413c2440c

### Expected Behavior

There must be no problems deploying an EventBridge rule...

### Actual Behavior

We run a lot of deployments with terraform on our CI every day, and see a lot of flakiness like this.
In this case it is an error deploying the event rules as described above, and it reproduced only once.

```
╷
│ Error: error reading EventBridge Rule (elastio-schedule-monthly): couldn't find resource
│
│   with module.region.module.inner.module.scheduler.aws_cloudwatch_event_rule.schedule["monthly"],
│   on ../modules/scheduler/main.tf line 32, in resource "aws_cloudwatch_event_rule" "schedule":
│   32: resource "aws_cloudwatch_event_rule" "schedule" {
│
╵
╷
│ Error: error reading EventBridge Rule (elastio-schedule-1hour): couldn't find resource
│
│   with module.region.module.inner.module.scheduler.aws_cloudwatch_event_rule.schedule["1hour"],
│   on ../modules/scheduler/main.tf line 32, in resource "aws_cloudwatch_event_rule" "schedule":
│   32: resource "aws_cloudwatch_event_rule" "schedule" {
│
╵
```

### Steps to Reproduce

Do a fresh deployment from scratch (non-incremental).

You can get a `.tar.gz` with all `.tf` source files from our [public s3 bucket](https://us-east-1.console.aws.amazon.com/s3/object/elastio-artifacts-us-east-2?region=us-east-2&prefix=release-candidate/region/0.14.0/terraform.tar.gz ) if you really need this, but there are a lot of them (and it also depends on additional cloudformation stack to be deployed before this, so probably really not useful).

1. `terraform init`
1. `terraform apply` 

You must be lucky if you can reproduce it at all. I am not sure how likely it is to trigger this error.

**Comment by jordanfinners** [comment]
Reading up on the AWS Docs
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html

It does state it may take some time for rules to take affect. I wonder the Read Rule function needs to retry for a time period before erroring.
