### ISSUE TITLE
r/aws_batch_compute_environment: Additional attributes can be updated in-place

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#24374]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

From the [recent AWS announcement](https://aws.amazon.com/about-aws/whats-new/2022/04/aws-batch-adds-improvement-updatecomputeenvironment-api/):

> AWS Batch now expands the Compute environment (CE) configuration parameters that can be updated without having to recreate compute environments. Previously customers used UpdateComputeEnvironment API to change CE state, desired CPU count, min and max vCPU count, and service role. To update additional configuration parameters, customers have to create new CEs. With this launch, customers can use the UpdateComputeEnvironment API to dynamically update CE configuration parameters such as AMI, EC2 launch templates, instance types, and more. Rather than having to manually create a new CE to use the updated configurations, Batch will use the updated CE configuration while launching new instances and terminate instances using old CE configuration once the jobs running on them are completed.

### New or Affected Resource(s)

* [`aws_batch_compute_environment`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/batch_compute_environment)

### References

[AWS Batch User Guide](https://docs.aws.amazon.com/batch/latest/userguide/updating-compute-environments.html).

**Comment by nicholastulach** [comment]
In the meantime, how do we work around this if we want to update our compute environments in terraform?
