### ISSUE TITLE
Updates to aws_instance.security_groups forces update on apply

### ISSUE THREAD

**Issue by jlongo62** [hashicorp/terraform-provider-aws#24393]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.7
on windows_386
+ provider registry.terraform.io/hashicorp/aws v4.11.0
+ provider registry.terraform.io/hashicorp/time v0.7.2

### Affected Resource(s)

aws_instance

### Terraform Configuration Files

```
data "aws_security_group" "VMCommon" {
  vpc_id = data.aws_vpc.VPC.id
  tags = {
    Name = "VMCommon"
  }
}
data "aws_security_group" "MiddleTier" {
  vpc_id = data.aws_vpc.VPC.id
  tags = {
    Name = "MiddleTier"
  }
}

resource "aws_instance" "TouchWorks-IIS-004" {

  ami               = data.aws_ami.Windows_Server-2019-English-Full-Base.id
  security_groups   = [ data.aws_security_group.VMCommon.id, data.aws_security_group.MiddleTier.id ]
...
  lifecycle {
    ignore_changes = [
      root_block_device[0].kms_key_id,
      instance_type,
      ami,
      key_name,
      user_data,
      get_password_data,
      root_block_device,
      ebs_block_device
    ]
  }
```

```hcl
  # module.modules.aws_instance.xxx-IIS-004[0] must be replaced
-/+ resource "aws_instance" "xxx-IIS-004" {
      ~ ami                                  = "ami-00d1b5cc1e5341681" -> "ami-0f54dbe65fd969bbd"
...
      ~ security_groups                      = [ # forces replacement
          + "sg-01a3fdde0e5fafad9",
          + "sg-045a124ad29afb196",
        ]
```

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

If changes to SecurityGroup property, aws_instance wil be updated
If NO  changes to SecurityGroup property, no action will be taken on aws_instance 

### Actual Behavior

If the  SecurityGroup property is set to anything other than NULL, terraform forces a Destroy/Create

### Steps to Reproduce

Create an aws_instance via terraform apply. Run apply a 2nd time.

### Important Factoids

the SecurityGroup id's in the state file match the Id's of the SecurityGroup resources. 

### References

n/a

* #0000

**Comment by justinretzolk** [comment]
Hey @jlongo62 👋 Thank you for taking the time to raise this. To clarify a bit here, are you adding the security groups to the `security_groups` argument on the second apply, are are you seeing this behavior with no configuration changes at all, leading to a replacement on every run?
