### ISSUE TITLE
Athena Databases not build on Linux

### ISSUE THREAD

**Issue by amamidwar** [hashicorp/terraform-provider-aws#24417]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

The `aws_athena_database` resource is not creating when running Terraform on Linux. This started failing in the last few days running 1.1.5 and we have since tried on both 1.1.5 and 1.1.9. We have proved this out using a minimum config of our modules (see attached code snippet) and this works fine on both Mac (Arm) and Windows running 1.1.5 and 1.1.9 but when running on Linux, the resource hangs for over an hour and times out compared to taking <10 seconds on Mac.
The attached code snippet called athenaerror includes the 2 modules along with a skeleton implementation in athenatest/main.tf which can be executed on different versions of terraform to prove out the error.
Please note we are currently pinning to version 3.74.1 of the AWS provider but have also proven out the issue on the latest version of 4.x seemingly pointing to a core binary bug.

### Affected Resource(s)

- aws_athena_database

### Terraform Configuration Files

Code:

```hcl
#S3 Bucket Creation
module "buckets" {
  source = "/xxx/terraform-aws-s3buckets"
  deploymentId      = "amittest"
  domainName        = "xxx"
  primaryS3Region   = "xxx"
  secondaryS3Region = "xxxx"
  providers = {
    aws.primary = aws
    aws.secondary = aws.secondary
  }
}
output "buckets" {
  value = module.buckets
}
module "athena" {
  source = "xxx/terraform-aws-athena"
  deploymentName = "xxxx"
  athenaS3BucketName  = module.buckets.primaryS3Bucket
  s3EncryptionKey     = module.buckets.s3KmsKey
}
output "athena" {
  value = module.athena
}
```

![image (2)](https://user-images.githubusercontent.com/92709567/165316207-6848d840-71f0-426f-a64a-ecab83655275.png)

Log - 
```
aws_athena_database.athena: Creating...
aws_athena_database.athena: Still creating... [10s elapsed]
aws_athena_database.athena: Still creating... [20s elapsed]
aws_athena_database.athena: Still creating... [30s elapsed]
aws_athena_database.athena: Still creating... [40s elapsed]
aws_athena_database.athena: Still creating... [50s elapsed]
aws_athena_database.athena: Still creating... [1m0s elapsed]
aws_athena_database.athena: Still creating... [1m10s elapsed]
..
..
..
```

This is on Windows - 
![image](https://user-images.githubusercontent.com/92709567/165317155-d74d978e-88b1-47c2-bf81-2734ef85e0b0.png)

**Comment by justinretzolk** [comment]
Hey @amamidwar 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include debug logs (redacted as necessary) as well?

**Comment by amamidwar** [comment]
Please find the attached debug log..
[applyDebugLog.txt](https://github.com/hashicorp/terraform-provider-aws/files/8569536/applyDebugLog.txt)

**Comment by amamidwar** [comment]
> Hey @amamidwar 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include debug logs (redacted as necessary) as well?
@[justinretzolk](https://github.com/justinretzolk) please find the attached debug and trace log..
[applyDebugLog.txt](https://github.com/hashicorp/terraform-provider-aws/files/8569536/applyDebugLog.txt)

**Comment by amamidwar** [comment]
Got the issue. Someone internally had created a private endpoint for Athena which is why this suddenly stopped working. Our Mac/Windows test machines were not in AWS but the linux box was, and HTTPS access was working everywhere else hence our confusion. this can now be closed out.
