### ISSUE TITLE
GP3 EBS Type by default instead of GP2

### ISSUE THREAD

**Issue by mmi-fbx** [hashicorp/terraform-provider-aws#24410]
---
name: 🚀 Feature Request GP3 EBS Type by default Instead of GP2
about: I have a suggestion (and might want to implement myself 🙂)!
labels: enhancement
---

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Actually GP3 is more efficent and costless than GP2. But we have to explicitly set to gp3 instead of default GP2

Terraform doc : (Optional) The type of EBS volume. Can be standard, gp2, gp3, io1, io2, sc1 or st1 (Default: gp2).
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ebs_volume
### New or Affected Resource(s)

Every EC2/EBS related deployment.

* aws_ebs_volume
* aws_launch_configuration

### References

https://aws.amazon.com/fr/ebs/volume-types/

**Comment by justinretzolk** [comment]
Hey @mmi-fbx 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description with the information requested in the [feature request template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Feature_Request.md?plain=1)?

**Comment by mmi-fbx** [comment]
@justinretzolk Hello, this is done. 
The feature request is pretty simple. 
Thank you,

**Comment by bschaatsbergen** [comment]
Judging from the API documentation, `gp2` is still the default for EBS volumes. 
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVolume.html#API_CreateVolume_RequestParameters 

See the `VolumeType` request parameter.

**Comment by mmi-fbx** [comment]
Oh, i thought it was a terraform side parameter.
I will check this with my aws account manager for feature request on AWS side.
Thank you @bschaatsbergen

**Comment by bschaatsbergen** [comment]
> Oh, i thought it was a terraform side parameter. I will check this with my aws account manager for feature request on AWS side. Thank you @bschaatsbergen

It's always possible to change on our side but we try to be in line with the AWS API as much as possible. For now I would recommend to explicitly overwrite/set the VolumeType paramter to `gp3` yourself until it becomes the new EBS VolumeType default :+1:

**Comment by justinretzolk** [comment]
Hey @mmi-fbx 👋 With the information that Bruno provided above in mind, we'll close this issue for now. If you feel we've done this in error, please do let us know!
