### ISSUE TITLE
AWS App Mesh: Gateway Route: add exact and regex path to http2 route 

### ISSUE THREAD

**Issue by gurudatta-carbon** [hashicorp/terraform-provider-aws#24415]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

- Add Exact and Regex match type to app mesh gateway route terraform provider for http2 spec.
- Currently it supports only prefix match
<img width="631" alt="image" src="https://user-images.githubusercontent.com/81990237/165301279-90837e4c-b19c-4fbd-83de-f7ac3a89377d.png">

### New or Affected Resource(s)

* [aws_appmesh_gateway_route](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appmesh_gateway_route)

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "aws_appmesh_gateway_route" "example" {
  name                 = "test-route"
  mesh_name            = "test"
  virtual_gateway_name = "gateway"

  spec {
    http2_route {
      action {
        target {
          virtual_service {
            virtual_service_name = ""
          }
        }
      }
      match {
        prefix = ""
        // missing
        exact  = ""
        // missing
        regex  = ""
      }
    }
  }

  tags = {
    Environment = "test"
  }
}

```

### References

* #0000

**Comment by ewbankkit** [comment]
Related: https://github.com/hashicorp/terraform-provider-aws/issues/23041.

**Comment by mkielar** [comment]
This is supported by AWS for both `http2_route` and `http_route`. And very much needed in both...

**Comment by mkielar** [comment]
Also, since AWS API uses dedicated `Path` section for this, I'd like to suggest slightly different syntax to what @gurudatta-carbon originally proposed. See below:
```hcl
  http_route {
    match {
      # The old way
      # prefix = "/users"

      # The new way
      path {
        # exact = "/users"
        regex = "/users/(\d+)/change-password"
      } 
    }
  }

  http2_route {
    match {
      # The old way
      # prefix = "/users"

      # The new way
      path {
        # exact = "/users"
        regex = "/users/(\d+)/change-password"
      } 
    }
  }

```
