### ISSUE TITLE
Request for Data Source: aws_secretsmanager_secrets (plural)

### ISSUE THREAD

**Issue by johnathan99j** [hashicorp/terraform-provider-aws#24421]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be very useful to be able to retrieve a list of aws_secretsmanager_secrets by applying a filter, akin to aws_vpc***s*** (vs aws_vpc).

This would be useful for the same reasons that other plural data sources are useful elsewhere but as a specific example, a list of secrets could be used when creating a `aws_db_proxy` resource where the proxy needs 20 existing secrets attached to it, the ability to have all these retrieved at once in a single data source list via filter is vastly superior to making many single data sources.

As mentioned in https://github.com/hashicorp/terraform-provider-aws/issues/13304#issuecomment-716058103 (#13304), the `filter` attribute doesn't follow the same vein as for other data sources so would unfortunately require a bit more work to accomplish but I still believe it's a worthwhile feature for the provider to have.

### New or Affected Resource(s)

- aws_secretsmanager_secrets data source

**Comment by kamilturek** [comment]
I'll take this one.

**Comment by johnathan99j** [comment]
Thanks for the prompt work on this @kamilturek!
