### ISSUE TITLE
Transfer Family - Tag Resource

### ISSUE THREAD

**Issue by k-brooks** [hashicorp/terraform-provider-aws#24426]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add a new resource to support tagging of Transfer Family resources / servers
This should begin to / address #6956.
Similar: https://github.com/hashicorp/terraform-provider-aws/issues/18077.

### New or Affected Resource(s)

* aws_transfer_tag_resource

### Potential Terraform Configuration

```hcl
resource "aws_transfer_tag_resource" "custom_hostname" {
  resource_arn = aws_transfer_server.server.arn
  tags = {
    "aws:transfer:customHostname" = aws_route53_record.custom_hostname.name
    "aws:transfer:route53HostedZoneId" = "/hostedzone/${aws_route53_record.custom_hostname.zone_id}"
  }
}
```

### References
API Docs -> https://docs.aws.amazon.com/transfer/latest/userguide/API_TagResource.html
* #6956

**Comment by C123R** [comment]
Hi there,

Looks like it's not assigned yet! Can I give a shot?

**Comment by cesarpball** [comment]
Hi @C123R , are you picking up this one?

**Comment by C123R** [comment]
@cesarpball I can take it over, I have some bandwidth for next few weeks 👍
