### ISSUE TITLE
S3 Replication Configuration MalformedXML Error

### ISSUE THREAD

**Issue by brijshah** [hashicorp/terraform-provider-aws#24427]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform:1.0.2
aws v4.4.0

### Affected Resource(s)

* `aws_s3_bucket_replication_configuration`

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket" "runner_cache" {
  bucket = format("%s-gitlab-runner-cache", var.cluster_name)
  tags   = var.tags
}

resource "aws_s3_bucket_lifecycle_configuration" "runner_cache_lifecycle" {
  bucket = aws_s3_bucket.runner_cache.id

  rule {
    id = "log"

    expiration {
      days = 30
    }

    noncurrent_version_expiration {
      noncurrent_days = 30
    }

    filter {
      prefix = "gitlab-runner/"
    }

    status = "Enabled"

  }

}

resource "aws_s3_bucket_server_side_encryption_configuration" "runner_cache_sse" {
  bucket = aws_s3_bucket.runner_cache.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_versioning" "runner_cache_versioning" {
  bucket = aws_s3_bucket.runner_cache.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_acl" "runner_cache_acl" {
  bucket = aws_s3_bucket.runner_cache.id
  acl    = "private"
}

resource "aws_s3_bucket_public_access_block" "runner_cache" {
  bucket = aws_s3_bucket.runner_cache.id

  block_public_acls       = true
  block_public_policy     = true
  restrict_public_buckets = true
  ignore_public_acls      = true
}

resource "aws_s3_bucket_replication_configuration" "cross_region" {
  role   = aws_iam_role.replication.arn
  bucket = var.s3_source_bucket_id

  rule {
    id = "cache-replication"

    filter {
      prefix = "gitlab-runner"
    }

    status = "Enabled"

    destination {
      bucket        = var.s3_destination_bucket_arn
      storage_class = "STANDARD"
    }
    delete_marker_replication {
      status = "Enabled"
    }
    existing_object_replication {
      status = "Enabled"
    }
  }
}
```

### Debug Output

https://gist.github.com/brijshah/caa4fe5a93756e5845170d9d7ce73eba

### Expected Behavior

Added Replication Configuration for the bucket successfully.

### Actual Behavior

```
Error: error creating S3 replication configuration for bucket (xxxxxxx): MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
│ 	status code: 400, request id: 46PWWWSGN32T3FVJ, host id: rvM69Ua+TYctWF3FxwCQp5VPWEcl+lOtw+CBFJX2gW0/Lnrk8MspKaeXVR1ChbzbVDsqtDlOik8=
```

### References

https://github.com/hashicorp/terraform-provider-aws/issues/23206

**Comment by anGie44** [comment]
Hi @brijshah thank you for raising this issue. Making an initial pass here it looks like this results from the use of the `existing_object_replication` configuration block which we found to be problematic/not currently supported in https://github.com/hashicorp/terraform-provider-aws/issues/23803 as well. The documentation as of `v4.7.0` should reflect this with a yellow note which can be found @ https://registry.terraform.io/providers/hashicorp/aws/4.7.0/docs/resources/s3_bucket_replication_configuration#rule. If feasible, I would remove that block for now and re-apply,  and then reach out if you're seeing any new error.

**Comment by brijshah** [comment]
yep, that did it! Thank you.
