### ISSUE TITLE
Support individual names for security_group_rule

### ISSUE THREAD

**Issue by HelixSpiral** [hashicorp/terraform-provider-aws#24437]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has the ability to name Security Group Rules individually, it would be nice if Terraform could support this field

### New or Affected Resource(s)

* aws v4.11.0 and older

### Potential Terraform Configuration

```hcl
resource "aws_security_group_rule" "new_sg_rule" {
    name = "IngressRule1" # This is the new field
    description = "Ingress on port 443"
    type = "ingress"
    from_port = 443
    to_port = 443
    protocol = "tcp"
    cidr_blocks = [ "0.0.0.0/0" ]
    ipv6_cidr_blocks = [ "::/0" ]
}
```

### References

* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/security-group-rules.html

**Comment by ewbankkit** [comment]
@HelixSpiral Thanks for raising this issue.
It has already been noticed in #20104. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
