### ISSUE TITLE
`aws_acm_certificate_validation` wrongly reporting invalid `certificate_arn` on v4.12.0

### ISSUE THREAD

**Issue by lauren-themis** [hashicorp/terraform-provider-aws#24452]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

1.1.8, and the just-released v4.12.0

### Affected Resource(s)

`aws_acm_certificate_validation`

### Terraform Configuration Files

```hcl
resource "aws_route53_zone" "test" {
  name = "some-zone."
}

resource "aws_acm_certificate" "test" {
  domain_name       = "*.some-zone"
  validation_method = "DNS"
}

resource "aws_route53_record" "test-a-record" {
  zone_id = aws_route53_zone.test.zone_id
  name    = aws_route53_zone.test.name
  type    = "A"
  alias {
    name                   = some_target_hostname
    zone_id                = lb_zone
    evaluate_target_health = true
  }
  
  lifecycle {
    ignore_changes = [records, ttl]
  }
}

resource "aws_route53_record" "test" {
  for_each = {
    for dvo in aws_acm_certificate.test.domain_validation_options : dvo.domain_name => {
      name   = dvo.resource_record_name
      record = dvo.resource_record_value
      type   = dvo.resource_record_type
    }
  }

  allow_overwrite = true
  name            = each.value.name
  records         = [each.value.record]
  ttl             = 60
  type            = each.value.type
  zone_id         = aws_route53_zone.test.zone_id
}

resource "aws_acm_certificate_validation" "test" {
  certificate_arn         = aws_acm_certificate.test.arn
  validation_record_fqdns = [for record in aws_route53_record.test : record.fqdn]
}
```

### Expected Behavior

Terraform plan should have found no changes on my `aws_acm_certificate_validation` resource in this case.

### Actual Behavior

![image](https://user-images.githubusercontent.com/102002103/165863930-57667e26-1f0d-4347-aef5-9fc2840aa10a.png)
```
Error: reading ACM Certificate (2022-04-25 20:00:08.983 +0000 UTC): 
ValidationException: 1 validation error detected: Value '2022-04-25 20:00:08.983 +0000 UTC' at 'certificateArn' failed to satisfy constraint: 
Member must satisfy regular expression pattern: arn:[\w+=/,.@-]+:acm:[\w+=/,.@-]*:[0-9]+:[\w+=,.@-]+(/[\w+=,.@-]+)*
```

(it errors out reading the `aws_acm_certificate_validation`'s `certificate_arn`)

&nbsp;

### Steps to Reproduce

`terraform plan` with an existing, unchanged `aws_acm_certificate_validation` in state, after upgrading to `v4.12.0`

This did NOT occur on any previous releases (I hadn't version locked my providers yet for this new setup, and it just started.)

Locking my version to `v4.11.0` *resolved the issue*, plan worked as expected.

**Comment by ahilmathew** [comment]
Can confirm that I am also facing the same issue on `v4.12.0`
```
╷
│ Error: reading ACM Certificate (2022-03-15 01:00:45.675 +0000 UTC): ValidationException: 1 validation error detected: Value '2022-03-15 01:00:45.675 +0000 UTC' at 'certificateArn' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:[\w+=/,.@-]+:acm:[\w+=/,.@-]*:[0-9]+:[\w+=,.@-]+(/[\w+=,.@-]+)*
│ 
│   with module.spoke_network.module.acm.aws_acm_certificate_validation.default[0],
│   on ../modules/acm/main.tf line 30, in resource "aws_acm_certificate_validation" "default":
│   30: resource "aws_acm_certificate_validation" "default" {
│ 
╵
Releasing state lock. This may take a few moments..
```

**Comment by jufemaiz** [comment]
+1 this.

Will lock to v4.11.0.

Seems like a pretty bad break?

**Comment by MatthewFagan** [comment]
Same issue here. The certificatearn output is giving the certificate issue date instead of the arn. It breaks everything

**Comment by MatthewFagan** [comment]
The value in the tfstate file (as obtained through terraform state show) contains the correct arn

**Comment by jufemaiz** [comment]
![image](https://user-images.githubusercontent.com/16481/165879381-22754f94-1a5d-4c14-ada7-400c9d97bb7b.png)

https://github.com/hashicorp/terraform-provider-aws/compare/v4.11.0...v4.12.0#diff-da27748319004d756e8526be1691fbfad4b2e7a5c2ffccf691e6447ea945a42dR98-R107

This is the problem.

**Comment by nodomain** [comment]
Same here - eagerly wanted to try out Serverless RDS Aurora v2 and hit the wall.
Waiting for the fix :)

**Comment by manfro3** [comment]
Same issue... waiting for a faster-than-light fix ;)

**Comment by neugeeug** [comment]
The same here ;)

**Comment by msmmatevans** [comment]
+1

**Comment by mediapills** [comment]
+1

**Comment by muhan-fixter** [comment]
+1

**Comment by mateuszkrasucki** [comment]
+1

**Comment by queeno** [comment]
+1

**Comment by schrill** [comment]
I can see that the pull request has been [approved](https://github.com/hashicorp/terraform-provider-aws/pull/24453/files/37957902d44e43b03a1afccde18512856f3e4172) for fixing this but changes are not into effect in the provider tag version v4.12.0

**Comment by FernandoMiguel** [comment]
> I can see that the pull request has been [approved](https://github.com/hashicorp/terraform-provider-aws/pull/24453/files/37957902d44e43b03a1afccde18512856f3e4172) for fixing this but changes are yet to reflect compiled provider with tag v4.12.0

4.12.0 **introduced** the issue
I would never expect for the fix to be released to the same tag

**Comment by edwardofclt** [comment]
> ![image](https://user-images.githubusercontent.com/16481/165879381-22754f94-1a5d-4c14-ada7-400c9d97bb7b.png)
> 
> https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate_validation
> 
> [v4.11.0...v4.12.0diff-da27748319004d756e8526be1691fbfad4b2e7a5c2ffccf691e6447ea945a42dR98-R107](https://github.com/hashicorp/terraform-provider-aws/compare/v4.11.0...v4.12.0diff-da27748319004d756e8526be1691fbfad4b2e7a5c2ffccf691e6447ea945a42dR98-R107)
> 
> This is the problem.

I almost wonder if in the next major release should change the `id` attribute name to `last_issued`. 🤔

**Comment by svanharmelen** [comment]
Is v4.13.0 going to be released as a hotfix for this? Or are you going to hold off on the release for now and add more changes to it? As we are also pretty stuck on this one for the moment...

**Comment by jeffwnelson** [comment]
For the time being, just add the following to your terraform provider block.
`terraform {
  required_version = ">= 1.1.9"

  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "= 4.11.0"
    }
  }
}`

That will pin the aws provider to the previous version.

**Comment by svanharmelen** [comment]
I know, but we have like a "gazillion" repos so that would be quite some work to be honest...

**Comment by svanharmelen** [comment]
No, we're perfectly fine with it and prefer to use latest. But it would be a shame if I spend the time to pin everything and then 5 minutes later `v4.13.0` is released and I can revert the pinning again...

Hence my question about the expected release frame, just so I can make an educated guess if it worth the efforts.

**Comment by ewbankkit** [comment]
We are planning on releasing a `v4.12.1` patch release with this (and maybe one other) bug fix later today.

**Comment by nodomain** [comment]
Thanks for the great news 😎

**Comment by lauren-themis** [comment]
Fix confirmed! Just tried the same resources on `4.12.1`, everything worked ✅ 

Thanks for the quick fix y'all!
