### ISSUE TITLE
Support for provisioned throughput in aws_msk_cluster

### ISSUE THREAD

**Issue by ryan-dyer-sp** [hashicorp/terraform-provider-aws#24464]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

aws_msk_cluster is missing support for the provisioned throughput storage functionality

### New or Affected Resource(s)

aws_msk_cluster

### Potential Terraform Configuration
broker_node_group_info {
    instance_type   = var.instance_type
    ebs_volume_size = var.ebs_volume_size
    ebs_provisioned_throughput = X # if defined, enabled provisioned throughput with corresponding value.
  }

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

https://aws.amazon.com/about-aws/whats-new/2022/01/amazon-msk-scale-storage-1000-broker/
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/kafka@v1.17.4/types#BrokerEBSVolumeInfo

**Comment by gregswift** [comment]
Would the expectation of supporting this be full provision and re-configure/provision at a later time?

**Comment by AdamTylerLynch** [comment]
I'm going to pick this issue up.

**Comment by AdamTylerLynch** [comment]
> Would the expectation of supporting this be full provision and re-configure/provision at a later time?

My intended implementation is to allow existing clusters to upgrade their storage to provisioned storage without resource recreation (destroy/create).
