### ISSUE TITLE
Version 4.12.0 confuses id and certificate arn of resource aws_acm_certificate_validation

### ISSUE THREAD

**Issue by christiangeiger-bayer** [hashicorp/terraform-provider-aws#24470]
I applied a terraform script using an aws_acm_certificate_validation. The resource already exists in the terraform state. When the terraform apply refreshed the state the following error is given:

aws_acm_certificate_validation.main: Refreshing state... [id=2021-08-16 14:39:01 +0000 UTC]

│Error: reading ACM Certificate (2021-08-16 14:39:01 +0000 UTC): ValidationException: 1 validation error detected: Value '2021-08-16 14:39:01 +0000 UTC' at 'certificateArn' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:[\w+=/,.@-]+:acm:[\w+=/,.@-]*:[0-9]+:[\w+=,.@-]+(/[\w+=,.@-]+)*
│ 
│   with aws_acm_certificate_validation.main,
│   on route53.tf line 44, in resource "aws_acm_certificate_validation" "main":
│   44: resource "aws_acm_certificate_validation" "main" {

Executing a terraform apply on the script using version 4.11.0 does not lead to an error.

**Comment by cjol** [comment]
Reverting to 4.11.0 has worked for me, so seems like a small range to bisect.

**Comment by ewbankkit** [comment]
@christiangeiger-bayer Thanks for raising this issue.
It has already been noticed in #24452. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
