### ISSUE TITLE
New Service: Support for AWS Textract

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#24478]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

_Amazon Textract is a machine learning (ML) service that automatically extracts text, handwriting, and data from scanned documents. It goes beyond simple optical character recognition (OCR) to identify, understand, and extract data from forms and tables. Today, many companies manually extract data from scanned documents such as PDFs, images, tables, and forms, or through simple OCR software that requires manual configuration (which often must be updated when the form changes). To overcome these manual and expensive processes, Textract uses ML to read and process any type of document, accurately extracting text, handwriting, tables, and other data with no manual effort. You can quickly automate document processing and act on the information extracted, whether you’re automating loans processing or extracting information from invoices and receipts. Textract can extract the data in minutes instead of hours or days. Additionally, you can add human reviews with Amazon Augmented AI to provide oversight of your models and check sensitive data._

### New or Affected Resource(s)

* aws_textract_document_analysis
* aws_textract_expense_analysis
* aws_textract_document_text_detection

### References

* [AWS Textract](https://aws.amazon.com/textract/)
* [Textract API](https://docs.aws.amazon.com/textract/latest/dg/API_Operations.html)

**Comment by johnsonaj** [comment]
After review of the service and the ability of the API, it was determined that this does not fit the Terraform model. This service is solely for performing an action instead of creating a resource that can be managed. Additionally, it lacks the ability to be queried longterm and would limit Terraform's ability to track a state.

Guidelines for [Infrastructure as code suitability](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/provider-design.md#infrastructure-as-code-suitability)
