### ISSUE TITLE
Support conditional resources

### ISSUE THREAD

**Issue by bouchardmathieu-qc** [hashicorp/terraform-provider-aws#24485]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform, as its actual form as a basic declarative language doesn't really support the use case where a resource can be optional. For example, if we want to create a reusable module to create an S3 bucket, we may want to provide an optional input variable to pass a kms key id. If the key id is not provided, we may want to create the key in the module.

As of now, the only way to do it is to use the "count" attribute. But we do not want to create a number of kms key. We want to maybe create one key if the variable is null.

As of now, this would create an error where terraform will say that it cannot compute the value (The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply only the resources that the count depends on.), but in fact, it can.

For example, if we first create the key and then call the module with the key, terraform should be able to know that the key will be created and then the count should be 1

### New or Affected Resource(s)

Any terraform resource

### Potential Terraform Configuration

```hcl
resource "aws_kms_key" "example" {
  description              = "Example"
}

module "example" {
  source = "example"
  key_arn = aws_kms_key.example.arn
}
```

In the module code:
```hcl
variable "key_arn" {
  type ="string"
  default = null
}

resource "aws_kms_key" "cle_s3" {
  count = var.key_arn != null ? 1 : 0
}
```

### Workaround

Instead of the above code, we may use an array of keys as an input variable (which is totally not what's intended since the user of the module will need to pass an array of only one key (which should not be an array):
```hcl
variable "key_arn" {
  type = list(string)
  default = []
}

resource "aws_kms_key" "cle_s3" {
  count = length(var.key_arn) > 0 ? 0 : 1
}
```

Or, we need to pass a second value (ex : boolean) to control wether the variable is null or not:
```hcl
module "modele" {
  source = "example"

  key_arn = null
  not needed_variable = false
}
```

```hcl
resource "aws_kms_key" "example" {
  count = var.not_needed_variable ? 0 : 1
}
```

**Comment by justinretzolk** [comment]
Hey @bouchardmathieu-qc 👋 Thank you for taking the time to raise this! In this case, this is something that would need to be supported by Terraform itself before this could work, at which point it would work with no changes to the AWS Provider itself. With that in mind, you'd want to open an issue in the [Terraform Core repository](https://github.com/hashicorp/terraform) to request this type of a change.

Given that this is a Terraform Core request rather than a request for the AWS Provider, I'm going to close this issue for now. If you feel I've done this in error, please do let me know and I'd be glad to continue the conversation.
