### ISSUE TITLE
Redshift datashare feature

### ISSUE THREAD

**Issue by rescuder** [hashicorp/terraform-provider-aws#24499]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Implement redshift datashare feature

It would be interesting if the redshift resource supports datashare

### New or Affected Resource(s)

* aws_redshift

### References

https://docs.aws.amazon.com/redshift/latest/dg/datashare-overview.html

**Comment by DrFaust92** [comment]
Datashares dont have a direct api but can be created via the redshift data api which is now supported via https://github.com/hashicorp/terraform-provider-aws/pull/25104

also see https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_DATASHARE.html
