### ISSUE TITLE
AWS Redshift Serverless support

### ISSUE THREAD

**Issue by alex-dolbik** [hashicorp/terraform-provider-aws#24501]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi there,

I checked terraform documentation and don't see any way to create AWS Redshift Serverless endpoint. Looks like terraform supports only redshift clusters creation.

https://aws.amazon.com/redshift/redshift-serverless

### New or Affected Resource(s)

* [x] [`aws_redshiftserverless_namespace `](https://github.com/hashicorp/terraform-provider-aws/pull/25889)
* [x] [`aws_redshiftserverless_workgroup`](https://github.com/hashicorp/terraform-provider-aws/pull/26467)
* [ ] `aws_redshiftserverless_endpoint_access`

**Comment by Olaktal** [comment]
Any idea when it will be available ? We have projects using this promising service and we cannot deploy it into production if there is no terraform support :(

**Comment by DrFaust92** [comment]
will try to look into this in the coming weeks

**Comment by DrFaust92** [comment]
FYI serverless doesnt seem to have an API yet (probably because its no GA)

**Comment by tomknight-cloudreach** [comment]
We'd also be very keen to use terraform to deploy this as soon as it's GA, but given there's no API or CF available yet I can't expect miracles. I can just hope for them ;-)

**Comment by rachekalmir** [comment]
Seems like the build issue has been fixed upstream in Release v1.44.45 (on 29 June 2022), is it possible to attempt a re-merge as this is not available in 4.21.0 as the bot states above?

**Comment by pjroth** [comment]
Should this issue be reopened as well since the merge was reverted?  

Any updates on when this will be re-merged or if there is anything myself or others could do to help move this along (create PRs, testing, etc)?

**Comment by ewbankkit** [comment]
Amazon Redshift Serverless is now GA: https://aws.amazon.com/about-aws/whats-new/2022/07/amazon-redshift-serverless-generally-available/.

**Comment by Olaktal** [comment]
Hello

Thanks for the `aws_redshiftserverless_namespace` resource !
It seems we do not have a workgroup attached to the serverless redshift, it requires a manual step.
@alex-dolbik you mentioned a new resource `aws_redshiftserverless_workgroup`, when do you think it could be released ?

Thanks for your work !

**Comment by DrFaust92** [comment]
im working on workgroup resource

**Comment by Olaktal** [comment]
Thanks @DrFaust92 !

**Comment by Olaktal** [comment]
Hello @DrFaust92 
Just to be sure you heard [Amazon Redshift Serverless now supports resource tagging](https://aws.amazon.com/fr/about-aws/whats-new/2022/10/amazon-redshift-serverless-supports-resource-tagging/) :)

**Comment by DrFaust92** [comment]
[Olaktal](https://github.com/Olaktal) can you open a new issue for this so i can prioritize?

**Comment by DrFaust92** [comment]
[Olaktal](https://github.com/Olaktal) now that ive taken another look tagging seems to be supported already in resources
