### ISSUE TITLE
aws_prometheus_workspace data source

### ISSUE THREAD

**Issue by evandam** [hashicorp/terraform-provider-aws#24503]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be very helpful to have a data source for `aws_prometheus_workspace`, particularly so we can use the resulting endpoint URL in other configurations (ex: Prometheus remote writes, Grafana data sources, etc.).

### New or Affected Resource(s)

* aws_prometheus_workspace

### Potential Terraform Configuration

```hcl
data "aws_prometheus_workspace" "test" {
  name = "test-workspace"
} 

locals {
  remote_write_url = "${data.aws_prometheus_workspace.test.endpoint}/api/v1/remote_write"
} 
```

**Comment by jeromeinsf** [comment]
Is this not already covered by https://github.com/hashicorp/terraform-provider-aws/pull/16882 ?
