### ISSUE TITLE
aws_s3_bucket_lifecycle_configuration `rule`s require `id`

### ISSUE THREAD

**Issue by joe-a-t** [hashicorp/terraform-provider-aws#24505]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_s3_bucket_lifecycle_configuration

### Expected Behavior

The change from `id` being [optional in v3](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#id) to [required in v4](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration#id) should have been documented in [the upgrade guide](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade#lifecycle_rule-argument)

### Actual Behavior

Upgrade guide does not mention this change.

### Steps to Reproduce

1. Have working bucket without `id` set using v3 of provider
2. Follow upgrade docs and try to upgrade to v4
3. Get error because `id` is now required

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @joe-a-t 👋 Thank you for taking the time to raise this! I've opened a PR to add a note around this to the upgrade guide.
