### ISSUE TITLE
aws_ssm_maintenance_window_task doesn't have argument for SNS IAM role

### ISSUE THREAD

**Issue by joemilacek** [hashicorp/terraform-provider-aws#24506]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

any

### Affected Resource(s)

aws_ssm_maintenance_window_task

### Terraform Configuration Files

```hcl
task_invocation_parameters {
    run_command_parameters {
      output_s3_bucket     = aws_s3_bucket.example.bucket
      output_s3_key_prefix = "output"
      service_role_arn     = aws_iam_role.example.arn
      timeout_seconds      = 600

      notification_config {
        notification_arn    = aws_sns_topic.example.arn
        notification_events = ["All"]
        notification_type   = "Command"
      }

      parameter {
        name   = "commands"
        values = ["date"]
      }
    }
  }
```

### Expected Behavior

Ability to configure IAM role for notification_config. In console, there is an option for "IAM role: Specify a role to trigger SNS Notifications". This is required if you use a separate IAM role to allow SSM to use SNS to send patching notifications.

<img width="815" alt="Screen Shot 2022-05-02 at 4 00 29 PM" src="https://user-images.githubusercontent.com/95373071/166317808-ae6762e5-0df4-406e-8aa4-1356435f8f28.png">

### Actual Behavior

Cannot configure. Notifications fail because of lack of IAM role.

**Comment by kamilturek** [comment]
I'll have a look at it.

**Comment by kamilturek** [comment]
By looking into the docs & code, it seems that the argument is already there. If I understand correctly, the `task_invocation_parameters.run_command_parameters.service_role_arn` is the ARN of the role used to publish to SNS.

https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_MaintenanceWindowRunCommandParameters.html#systemsmanager-Type-MaintenanceWindowRunCommandParameters-ServiceRoleArn
<img width="712" alt="image" src="https://user-images.githubusercontent.com/22010517/166564495-a16dbaa9-36f0-4b3d-9be3-706453ef5609.png">

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_maintenance_window_task
![image](https://user-images.githubusercontent.com/22010517/166564021-d38e4d10-6eaa-426e-8053-412be6778cf2.png)

@joemilacek Could you please confirm this? If that's correct, I believe we could improve the documentation then.

**Comment by joemilacek** [comment]
@kamilturek That does work!

The way that is written and where it is placed in the docs makes it sound like it is the role for the whole task, as shown here:


![Screen Shot 2022-05-04 at 10 18 37 AM](https://user-images.githubusercontent.com/95373071/166704872-5788cbf3-d774-4a0c-9d0d-6b8b98f9d4c0.png)

However, I just tried it and it does appear to only be setting it for the SNS section.

Thanks for the response and clarification!
