### ISSUE TITLE
allow_major_version_upgrade for Neptune

### ISSUE THREAD

**Issue by mrtngrbmn** [hashicorp/terraform-provider-aws#24512]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I tried to update a Neptune cluster from 1.0.2.2 to 1.1.1.0 but got the message
Error: Failed to modify Neptune Cluster (...): InvalidParameterCombination: The AllowMajorVersionUpgrade flag must be present when upgrading to a new major version.
        status code: 400, request id: c965c5fe-ccca-4a42-91f3-e238a022bf5e

There is no allow_major_version_upgrade for aws_neptune_cluster available (like in aws_db_instance)

After that it was possible to upgrade using the AWS console

### New or Affected Resource(s)

aws_neptune_cluster 

using terraform 0.15.5 and aws v3.75.1, but also the latest version documentation for 4.12.1 does not show such an argument.

**Comment by deividferreira-hotmart** [comment]
I also tried to upgrade a Neptune cluster from 1.0.5.1 to 1.1.0.0 and got the same message.
