### ISSUE TITLE
Allow name_prefix for aws_s3_bucket data source

### ISSUE THREAD

**Issue by EmmanuelOgiji** [hashicorp/terraform-provider-aws#24544]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like the AWS S3 bucket data source to allow you to get details of an S3 bucket or buckets by passing in the name_prefix. Since you can create buckets using that, it makes sense to be able to read it the other way. This could also just be a new data source aws_s3_buckets.
### New or Affected Resource(s)

data source: aws_s3_bucket https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/s3_bucket

data source: aws_s3_buckets

### Potential Terraform Configuration

```hcl
data "aws_s3_buckets" "hello_bucket" {
   name_prefix = "hello-world-"
}

output "hello_bucket_arns" {
  value = data.aws_s3_bucket.hello_bucket.*.arn
}
```

**Comment by teddylear** [comment]
I can take a look into this if that's alright

**Comment by EmmanuelOgiji** [comment]
Also it would be good if this allowed you get the origin region of the bucket as well

**Comment by teddylear** [comment]
@justinretzolk Opened a PR for this issue. As it's my first PR for this repo, please let me know if I should change anything. 

@EmmanuelOgiji I'll add the origin bucket in another PR, just want to keep changes to a minimum as this is my first PR to repo.

**Comment by EmmanuelOgiji** [comment]
@teddylear Thanks. I had a quick look. It all looks good but I'm not a go lang expert so we'll see what others say

**Comment by justinretzolk** [comment]
Hey @teddylear 👋 Thank you for taking the time to do that! On a quick glance, everything seems to be in order on the PR. For now, everything should be fine as is until one of our engineers is able to review the PR 🙂.

**Comment by teddylear** [comment]
@justinretzolk awesome thanks!
