### ISSUE TITLE
Cannot ignore changes of `aws_cloudfront_distribution.origin.*.origin_path`

### ISSUE THREAD

**Issue by PolarPayne** [hashicorp/terraform-provider-aws#24546]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.12.1
+ provider registry.terraform.io/hashicorp/tls v3.3.0
```

### Affected Resource(s)

* aws_cloudfront_distribution

### Terraform Configuration Files

```hcl
resource "aws_cloudfront_distribution" "distribution" {
  # ... omitted ...

  lifecycle {
    ignore_changes = [origin.0.origin_path]
  }

  origin {
    domain_name = var.content_bucket.bucket_domain_name
    origin_id   = "default"
    origin_path = var.path

    s3_origin_config {
      origin_access_identity = aws_cloudfront_origin_access_identity.origin_access_identity.cloudfront_access_identity_path
    }
  }
}
```

### Output

```
Error: Cannot index a set value

  on ../modules/cdn/cloudfront.tf line 40, in resource "aws_cloudfront_distribution" "cf_distribution":
  40:     ignore_changes = [origin.0.origin_path]

Block type "origin" is represented by a set of objects, and set elements do not have addressable keys. To find elements matching specific criteria, use a "for" expression with an "if" clause.
```

### Expected Behavior

I would expect to be able to ignore changes to origins `origin_path` but as the origins are a set it is not possible. It is also **not** possible to use an if expression with an if clause in a lifecycle block.

**Comment by justinretzolk** [comment]
Hey @PolarPayne 👋 This is more of an issue within Terraform Core itself rather than one with the AWS Provider. I see you also commented over on https://github.com/hashicorp/terraform/issues/26359 -- that will be a much better avenue to discuss this, so I'll close this issue. If you feel I've done this in error, please do let me know.
