### ISSUE TITLE
Data Source: aws_security_group (with tags) force old data to be replaced when new element are added to a for_each

### ISSUE THREAD

**Issue by egarbi** [hashicorp/terraform-provider-aws#24542]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.9.0
+ provider registry.terraform.io/hashicorp/random v3.1.2
```
### Affected Resource(s)

* Data Source: aws_security_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
variable "environment_names" {
  type = list
  description = "List of Environments to be managed"
  default = ["env1", "env2"]
}

data "aws_security_group" "BeanstalkInstances" {
  for_each = toset(var.environment_names)
  depends_on = [
    module.StagingWebElasticBeanstalkEnvironment
  ]

  tags = {
    "aws:cloudformation:logical-id" = "AWSEBSecurityGroup"
    "Name"                          = each.key
  }
}
```

### Debug Output

```
# data.aws_security_group.BeanstalkInstances["env2"] will be read during apply
  # (config refers to values not yet known)
 <= data "aws_security_group" "BeanstalkInstances"  {
      + arn         = (known after apply)
      + description = (known after apply)
      + id          = (known after apply)
      + name        = (known after apply)
      + tags        = {
          + "Name"                          = "env2"
          + "aws:cloudformation:logical-id" = "AWSEBSecurityGroup"
        }
      + vpc_id      = (known after apply)
    }

# data.aws_security_group.BeanstalkInstances["env1"] will be read during apply
  # (config refers to values not yet known)
 <= data "aws_security_group" "BeanstalkInstances"  {
      ~ arn         = "arn:aws:ec2:eu-central-1:12345678910:security-group/sg-0dccXXXXXXXc158f33" -> (known after apply)
      ~ description = "VPC Security Group" -> (known after apply)
      ~ id          = "sg-0dccXXXXXXXX" -> (known after apply)
      ~ name        = "awseb-e-xxxxxxxx-stack-AWSEBSecurityGroup-XXXXXXXXX" -> (known after apply)
      ~ tags        = {
          + "aws:cloudformation:logical-id"     = "AWSEBSecurityGroup"
          - "elasticbeanstalk:environment-id"   = "e-xxxxxxxx -> null
          - "elasticbeanstalk:environment-name" = "env1" -> null
            # (1 unchanged element hidden)
        }
      ~ vpc_id      = "vpc-xxxxxx" -> (known after apply)
    }
```
### Expected Behavior

Only the data source to be added "env2" for this example should be added to the state
### Actual Behavior

The old data already in the state is trying to be recreated forcing my dependent resources to be replaced.
This only happens when new elements are added to the list `var.environment_names`, otherwise no changes are shown
Example
```
# module.redis_security_group["env1"].aws_security_group_rule.ingress_with_source_security_group_id[0] must be replaced
-/+ resource "aws_security_group_rule" "ingress_with_source_security_group_id" {
      - cidr_blocks              = [] -> null
      ~ id                       = "sgrule-1234567" -> (known after apply)
      - ipv6_cidr_blocks         = [] -> null
      ~ source_security_group_id = "sg-xxxxxxxxxxxxxxxxxx" -> (known after apply) # forces replacement
```

### Steps to Reproduce

1. set `var.environment_names` as `["env1"]
2. terraform apply
3. add "env2" to `var.environment_names` to have  ["env1", "env2"]
4. terraform plan
### Important Factoids

In my use case, I'm reading the data for SGs created by Beanstalk by default, that's the reason why I have a dependency defined. I don't think this is an impediment to reproducing the issue but I didn't check it.

**Comment by justinretzolk** [comment]
Hey @egarbi 👋 Thank you for taking the time to raise this! I did a bit of testing and haven't been able to reproduce this behavior. I suspect there's something additional about the configuration that I'm not seeing based on what you've provided here. Is the sample configuration provided exactly what you have in your configuration, or a similar, but not necessarily 1:1 representation of your configuration?

It may also help if you're able to provide (redacted as necessary) debug logs.  That may give a better idea of what is meant by the `(config refers to values not yet known)` message.
