### ISSUE TITLE
resource "aws_sagemaker_app" should support app_type "Canvas"

### ISSUE THREAD

**Issue by Janne-Nykanen** [hashicorp/terraform-provider-aws#24573]
Seems like the latest provider is missing app type "Canvas":
```
│ Error: expected app_type to be one of [JupyterServer KernelGateway TensorBoard RStudioServerPro RSessionGateway], got Canvas
│
│   with module.sagemaker.aws_sagemaker_app.sagemaker_canvas,
│   on ../_modules/sagemaker/main.tf line 257, in resource "aws_sagemaker_app" "sagemaker_canvas":
│  257:   app_type          = "Canvas"
```

Something I'm missing?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_sagemaker_app

### Potential Terraform Configuration

```hcl
resource "aws_sagemaker_app" "sagemaker_canvas" {
  domain_id         = aws_sagemaker_domain.sagemaker_domain.id
  user_profile_name = aws_sagemaker_user_profile.sagemaker_canvas.user_profile_name
  app_name          = "my-canvas"
  app_type          = "Canvas"

```

### References

* #0000

**Comment by bschaatsbergen** [comment]
Hi @Janne-Nykanen,

Thanks for raising this issue.

The only supported AppTypes for SageMaker Apps are:

- JupyterServer
- KernelGateway
- TensorBoard
- RStudioServerPro
- RSessionGateway

Canvas does not seem to be supported by judging from the AWS Go SDK (https://github.com/bschaatsbergen/aws-sdk-go/blob/main/service/sagemaker/api.go#L93889).

There's a starter guide on setting up SageMaker Canvas here: https://docs.aws.amazon.com/sagemaker/latest/dg/canvas-setting-up.html

I would recommend to go over this and hopefully in the nearby future we can add support for this in the provider.
