### ISSUE TITLE
Error describing Service Catalog Provisioned Product (pp-*******): unexpected state 'TAINTED', wanted target 'AVAILABLE'. last error: %!s(<nil>) & Not able to run update or destroy after this state

### ISSUE THREAD

**Issue by kush-sumit** [hashicorp/terraform-provider-aws#24574]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.12.1
+ provider registry.terraform.io/hashicorp/random v3.1.3

### Affected Resource(s)

* aws_servicecatalog_provisioned_product

### Service Catalog Product Yaml File

```hcl
AWSTemplateFormatVersion: 2010-09-09
Description: Sumit Initial CloudFormation script

Parameters:
  AwsLogicalAccountNameLowerCase:
    Description: Logical AWS account name e.g. kush
    Type: String

Resources:
################S3 Buckets################
  KushResourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['', [!Ref AwsLogicalAccountNameLowerCase, '-learning-1000-resouces']]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
          BlockPublicAcls: True
          BlockPublicPolicy: True
          IgnorePublicAcls: True
          RestrictPublicBuckets: True

################S3 Bucket Policies################
  KushResourceBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref KushResourceBucket
      PolicyDocument:
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: '*'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref AwsLogicalAccountNameLowerCase, '-learning-1000-resouces/*']]
            Condition:
              Bool:
                aws:SecureTransport: false
          - Sid: DenyIncorrectEncryptionHeader
            Effect: Deny
            Principal: '*'
            Action:
              - s3:PutObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref AwsLogicalAccountNameLowerCase, '-learning-1000-resouces/*']]
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: AES256
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: '*'
            Action:
              - s3:PutObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref AwsLogicalAccountNameLowerCase, '-learning-1000-resouces/*']]
            Condition:
              'Null':
                s3:x-amz-server-side-encryption: true
          - Sid: DenyUnwantedCannedACLs
            Effect: Deny
            Principal: '*'
            Action:
              - s3:PutObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref AwsLogicalAccountNameLowerCase, '-learning-1000-resouces/*']]
            Condition:
              StringEquals:
                s3:x-amz-acl:
                  - public-read
                  - public-read-write
                  - aws-exec-read
                  - authenticated-read
                  - bucket-owner-read
                  - log-delivery-write


```

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl

# version.tf

terraform {
  // Fix version to ensure future compatibility if an updates is deployed
  required_version = ">= 1.1.9"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.74"
    }
  }
  }
```
```hcl
# provider.tf

provider "aws" {
  region = "eu-central-1"
}
```

```hcl
# variables.tf

variable "product_id" {
  description = "Enter Product_Id"
  type        = string
  default     = "prod-f***********"
}

variable "provisioning_artifact_id" {
  description = "Enter provisioning_artifact_id"
  type        = string
  default     = "pa-k**************"
}

variable "aws_logical_account_name_lower_case" {
  description = "Enter aws_logical_account_name_lower_case"
  type        = string
  default     = "kush3"
}

variable "provisioned_product_name" {
  description = "Enter provisioned_product_name"
  type        = string
  default     = "Test_Bucket_Creation"
}

```

```hcl
# main.tf


resource "aws_servicecatalog_provisioned_product" "s3_bucket" {
  // Product Name
  name         = var.provisioned_product_name

  # Service catalog parameters
  product_id                = var.product_id
  provisioning_artifact_id  = var.provisioning_artifact_id
  // Service catalog provisioning parameters

  provisioning_parameters {
    key   = "AwsLogicalAccountNameLowerCase"
    value = var.aws_logical_account_name_lower_case
  }

}

# Give all the outputs exported from service catalog
output "Provisioned_Product_Outputs" {
  value = aws_servicecatalog_provisioned_product.s3_bucket.outputs
}

```

### Expected Behaviour

Terraform should provide the actual error message which is encountered during provisioning/deployment of product.

### Actual Behaviour

Error: error describing Service Catalog Provisioned Product (pp-*********): unexpected state 'TAINTED', wanted target 'AVAILABLE'. **last error: %!s(<nil>)**
│

### Steps to Reproduce

1. `terraform init`
2. `terraform plan `
3.  `terraform apply`

Once the bucket is created, Create an aws bucket in the account by name “kush-learning-1000-resouces”.
now update your variable "aws_logical_account_name_lower_case" value to kush and then hit apply.

4.  `terraform apply`

you will see that deployment fails with error as a bucket is already present by this name and put the product in tainted state and all you will get is the error message 

Error: error describing Service Catalog Provisioned Product (pp-*********): unexpected state 'TAINTED', wanted target 'AVAILABLE'. **last error: %!s(<nil>)**

now if you try to revert back the value to "kush3" and hit terraform apply you will only get Error and same is case with below terraform destory

6. `terraform destroy`

### Important Factoids

There are two bugs as below.

1. Once while provisioning the product, if during provisioning of product an error is encountered terraform throws the error shown in Actual behaviour, which is highly confusion. The expectation is to display actual error in the field of **last error: ** instead of **%!s(<nil>)**,

I tried simply running the aws cli command [AWS CLI Documentation](https://docs.aws.amazon.com/cli/latest/reference/servicecatalog/describe-provisioned-product.html)
aws servicecatalog describe-provisioned-product --id pp-*****  and as per the output the value from "StatusMessage" should be displayed.

2. **Major Bug** is once the product goes into the tainted or Error state and then when we try to run an update/destroy of product by applying **terraform apply**, post making changes in input which caused the provisioning to fail. Terraform fails to apply update to the product and simply throws same error **Error: error describing Service Catalog Provisioned Product (pp-*********): unexpected state 'TAINTED', wanted target 'AVAILABLE'. last error: %!s(<nil>)**

### References

* #0000

**Comment by kush-sumit** [comment]
I am still getting the same below 2 issue.

1) Not able to run any updates using terraform apply or terraform destroy in case of provisioned products goes into tainted and error state.
2) Error Message is not displayed properly its just says  **last error: %!s(<nil>)**, it should rather display value obtained in **status message field** of describe provisioned product api.

terraform -version

Please find below screenshot for reference

<img width="1440" alt="Screenshot 2022-05-13 at 00 17 28" src="https://user-images.githubusercontent.com/104900576/168177078-f94f82b1-7635-47ac-bd50-fd9d35b63175.png">

**Comment by kush-sumit** [comment]
@anGie44 @justinretzolk : 

I tried to test scenarios for the bugs raises with latest release version 4.14
 
We are still getting same issue, where in we are not able to run update or destroy on the provisioned product whose state has become either tainted/error, Could you please open the issue again.
 
The other issue about populating the error message is solved, we could now see the error message.
please find below screenshot for reference:
<img width="1437" alt="ErrorMessage" src="https://user-images.githubusercontent.com/104900576/168346065-2bf2857d-d4fc-4458-a833-80ae8bacf89e.png">

**Comment by anGie44** [comment]
Hi @kush-sumit , thanks for your reply here. Can you confirm which errors you're seeing now with `v4.14.0` of the aws provider. Does it include one or both of the following:
* `error describing Service Catalog Provisioned Product (<product-name>): unexpected state...`
* `error describing Service Catalog Provisioned Product (<product-name>) Record (<record-id>): <error>

Thanks in advance!

**Comment by kush-sumit** [comment]
> Hi @kush-sumit , thanks for your reply here. Can you confirm which errors you're seeing now with `v4.14.0` of the aws provider. Does it include one or both of the following:
> 
> * `error describing Service Catalog Provisioned Product (<product-name>): unexpected state...`
> * `error describing Service Catalog Provisioned Product (<product-name>) Record (<record-id>): unexpected state...`
> 
> Thanks in advance!

@anGie44 : Thanks for quick acknowledgement, when i hit terraform apply i could see only this one which is second one in your list

aws_servicecatalog_provisioned_product.s3_bucket: Refreshing state... [id=pp-ixoexjt2mopy2]
╷
│ Error: error describing Service Catalog Provisioned Product (pp-ixoexjt2mopy2) Record (rec-7ye5hezyooqu4): unexpected state 'FAILED', wanted target 'SUCCEEDED, AVAILABLE'. last error: 1 error occurred:
│       * : Errors from CloudFormation: [{LogicalResourceId : SC-514039224447-pp-ixoexjt2mopy2, ResourceType : AWS::CloudFormation::Stack, StatusReason : The following resource(s) failed to update: [KushResourceBucket]. }, {LogicalResourceId : KushResourceBucket, ResourceType : AWS::S3::Bucket, StatusReason : kush2-learning-1000-resouces already exists}, {LogicalResourceId : KushResourceBucket, ResourceType : AWS::S3::Bucket, StatusReason : Requested update requires the creation of a new physical resource; hence creating one.}, {LogicalResourceId : SC-514039224447-pp-ixoexjt2mopy2, ResourceType : AWS::CloudFormation::Stack, StatusReason : User Initiated}, {LogicalResourceId : KushResourceBucketPolicy, ResourceType : AWS::S3::BucketPolicy, StatusReason : Resource creation Initiated}, {LogicalResourceId : KushResourceBucket, ResourceType : AWS::S3::Bucket, StatusReason : Resource creation Initiated}, {LogicalResourceId : SC-514039224447-pp-ixoexjt2mopy2, ResourceType : AWS::CloudFormation::Stack, StatusReason : User Initiated}]

**Comment by anGie44** [comment]
I see, thanks for confirming which error message you're most recently running in to @kush-sumit ! I'll re-open this on account that it's related to the original issue, just occurring a bit further down in the resource code:

https://github.com/hashicorp/terraform-provider-aws/blob/6e8fe78d5d52229122afc6748d6ff021c4409ab3/internal/service/servicecatalog/provisioned_product.go#L420-L429

**Comment by kush-sumit** [comment]
Hi @anGie44: Thanks for working on the issue and releasing the fixes.
I Just now tried to test the fix and below are my findings.

1) Error Message display issue --> **Fixed**
2) Terraform update or destroy run on provisioned product state (tainted or error) --> **Fixed**

**Issue Introduced or Still Exists**
**_Now when the product goes into tainted states instead of throwing that as error terraform is now displaying the product to be in available state, where as on aws console we could see the error, this was working fine after first fix for error message display was release._**

I assume this is happening as you have added tainted also into **wanted target** instead of **unexpected state**.

Could you please re-open this ticket and fix the issue.

please find below snippet for your reference. 

**Wrong Status from Terraform Console**
<img width="1437" alt="Screenshot 2022-05-28 at 01 38 40" src="https://user-images.githubusercontent.com/104900576/170801098-3d93949b-970f-4880-a442-60292cdf1a9c.png">


**Actual Status in AWS Console**
<img width="1150" alt="Screenshot 2022-05-28 at 01 42 27" src="https://user-images.githubusercontent.com/104900576/170800887-3d7e1714-23c4-4847-8385-2b8ea0c05438.png">


**Error Message in AWS Console**
<img width="603" alt="Screenshot 2022-05-28 at 01 43 52" src="https://user-images.githubusercontent.com/104900576/170801028-db2372d4-93fc-43e0-8b13-27882b41a38e.png">



please let me know any inputs further required from my end.

Regards
Mahi

**Comment by kush-sumit** [comment]
Hi @anGie44: While doing the update of a provisioned product, if the there is a failure and product becomes tainted with the recent changes as part of fix terraform thinks that the deployment was successfull and as you could see in first screenshot it simply outputs modification got completed and 1 changed successfully. 

The request would be to just move tainted stated from list of wanted state and we could just keep available there like before. This would then automatically throw the error record like it was doing after first fix where as the product went into tainted state terraform throwed the output stating product is in tainted state and displayed the error record.

**Comment by kush-sumit** [comment]
Hi @anGie44: Thanks for releasing the fix. I did a round of testing and all seems to be working fine now. Thanks for your help on this issue

**Comment by YakDriver** [comment]
I apologize for the back and forth on this and that this was closed when the error is still happening. We have a new fix in the works. However, please note that now this resource will continue to function when a stack has a `TAINTED` status. This is because the stack is in a

> Stable state, ready to perform any operation. The stack has completed the requested operation but is not exactly what was requested. For example, a request to update to a new version failed and the stack rolled back to the current version.

You can use `status` and `status_message` or logging to find out more about if this happens to your stack.

This seems like the right and only way forward but please let us know if you disagree.
