### ISSUE TITLE
aws_cloudtrail documentation bug for logging all S3 data events

### ISSUE THREAD

**Issue by cacack** [hashicorp/terraform-provider-aws#24596]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_cloudtrail documentation (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail)

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

The following example is provided under "Logging All S3 Object Events By Using Basic Event Selectors" of https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail

Incorrect:
```hcl
resource "aws_cloudtrail" "example" {
  # ... other configuration ...

  event_selector {
    read_write_type           = "All"
    include_management_events = true

    data_resource {
      type   = "AWS::S3::Object"
      values = ["arn:aws:s3:::"]
    }
  }
}
```

Correct:
```hcl
resource "aws_cloudtrail" "example" {
  # ... other configuration ...

  event_selector {
    read_write_type           = "All"
    include_management_events = true

    data_resource {
      type   = "AWS::S3::Object"
      values = ["arn:aws:s3"]
    }
  }
}
```

### Expected Behavior

Organizational CloudTrail is created which correctly tracks data-plane events.

### Actual Behavior

Organization CloudTrail is created and from the Console summary page it appears to track data-plane events for current and all future buckets.  However, if you click the edit button for S3 data events, the attributes within reveal S3 data events are not configured correctly when specifying `arn:aws:s3:::` for the event selector value.

Using `arn:aws:s3` (without the trailing `:::`) results in the proper configuration.

### Important Factoids

AWS just updated the CloudFormation documentation to reflect this: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudtrail-trail-dataresource.html

**Comment by AdamJCavanaugh** [comment]
I see the same in the AWS documentation and can do the requested provider documentation update.
