### ISSUE TITLE
Data Source: aws_ecs_task_definition not returning containerDefinitions.image

### ISSUE THREAD

**Issue by diepes** [hashicorp/terraform-provider-aws#24666]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
for the data source  aws_ecs_task_definition
return more information.

### New or Affected Resource(s)
data source:
 * aws_ecs_task_definition

### Potential Terraform Configuration

When deploying and re-deploying ecs container tasks, that are also updated outside terraform, eg. updates of image,  we need to find the image used in the latest deployment.

```hcl
data "aws_ecs_task_definition" "this" {
  task_definition = aws_ecs_task_definition.this.family
}

resource "aws_ecs_task_definition" "this" {
  container_definitions = jsonencode([
    {
      image = data.aws_ecs_task_definition.this.containerDefinitions[0].image
    }
}
```

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @diepes 👋 Thank you for taking the time to raise this! I took a bit of time to look into this, and I believe that the [`aws_ecs_container_definition` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ecs_container_definition) may be what you're looking for.

Both `aws_ecs_container_definition` and `aws_ecs_task_definition` use [`ecs.DescribeTaskDefinition`](https://docs.aws.amazon.com/sdk-for-go/api/service/ecs/#ECS.DescribeTaskDefinition) to get the requested information, but `aws_ecs_container_definition` pulls out the [`ContainerDefinitions`](https://docs.aws.amazon.com/sdk-for-go/api/service/ecs/#ContainerDefinition) data that matches the `container_name` that is supplied.

**Comment by diepes** [comment]
Thanks @justinretzolk , that is just what i was missing.
