### ISSUE TITLE
`aws_fsx_data_repository_association` failure when creating 2 or more in parallel 

### ISSUE THREAD

**Issue by scottblack1** [hashicorp/terraform-provider-aws#24678]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

* Terraform v0.14.6
* Provider version 3.75.1

### Affected Resource(s)

* `aws_fsx_data_repository_association`

### Terraform Configuration Files

Any Terraform code that creates 2 or more `aws_fsx_data_repository_association` in parallel will result in this bug.

The code I am executing is below.

```hcl
resource "aws_fsx_lustre_file_system" "fsx_lustre" {
  storage_type                      =  "SSD"
  deployment_type                   = "PERSISTENT_2"
  per_unit_storage_throughput       = 125
  storage_capacity                  = 1200
  subnet_ids                        = ["subnet-032e3e4ec6932a1239"]
  kms_key_id                        = var.kms_key_id
  security_group_ids                = aws_security_group.fsx_sg.*.id
  timeouts {
    create = var.create_timeout
    delete = var.delete_timeout
  }
  tags = local.tags
}

resource "aws_fsx_data_repository_association" "fsx_lustre_data_repository_association_1" {
  file_system_id                   = aws_fsx_lustre_file_system.fsx_lustre.id
  data_repository_path             = "s3://bucket1"
  file_system_path                 = "/path1"
  s3 {
    auto_import_policy {
      events = ["NEW", "CHANGED", "DELETED"]
    }
    auto_export_policy {
      events = ["NEW", "CHANGED", "DELETED"]
    }
  }

  timeouts {
    create = var.create_timeout
    delete = var.delete_timeout
  }

  tags       = local.tags
}

resource "aws_fsx_data_repository_association" "fsx_lustre_data_repository_association_2" {
  file_system_id                   = aws_fsx_lustre_file_system.fsx_lustre.id
  data_repository_path             = "s3://bucket2"
  file_system_path                 = "/path2"
  s3 {
    auto_import_policy {
      events = ["NEW", "CHANGED", "DELETED"]
    }
    auto_export_policy {
      events = ["NEW", "CHANGED", "DELETED"]
    }
  }

  timeouts {
    create = var.create_timeout
    delete = var.delete_timeout
  }

  tags       = local.tags
}
```

### Output

running `terraform apply`

https://gist.github.com/scottblack1/ce312981df133c76ee02939572328f09

running `terraform apply -parallelism=1`

https://gist.github.com/scottblack1/c485eee9e0ae0b2715f22ee07696ef36

### Expected Behavior

Terraform should create both of the data repository associations for FSX and they should be in `AVAILABLE` state.

You should not have the run with parallelism=1 in order for this to succeed as this significantly slows down the terraform apply.

### Actual Behavior

Each `aws_fsx_data_repository_association` resource seems to get stuck creating. They will fail with the following output:

```
Error: error waiting for FSx Lustre Data Repository Association (dra-07a1bc53dc89a16b0) create: timeout while waiting for state to become 'AVAILABLE' (last state: 'CREATING', timeout: 40m0s)

  on ..\main.tf line 210, in resource "aws_fsx_data_repository_association" "fsx_lustre_data_repository_association_1":
 210: resource "aws_fsx_data_repository_association" "fsx_lustre_data_repository_association_1" {



Error: error waiting for FSx Lustre Data Repository Association (dra-0212727ea308733e3) create: unexpected state 'FAILED', wanted target 'AVAILABLE'. last error: Amazon FSx does not have the required permissions for the S3 bucket. Verify that FSx has correct permissions by checking the bucket policy.

  on ..\main.tf line 231, in resource "aws_fsx_data_repository_association" "fsx_lustre_data_repository_association_2":
 231: resource "aws_fsx_data_repository_association" "fsx_lustre_data_repository_association_2" {
```

Note that here, the dra that timed out will eventually create. The issue here is one of them fails on permissions. It is important to note that the S3 bucket policys do have the correct permissions. This can be proved by executing the same code with a sequential apply using the `-parallelism=1` flag. This will result in successful execution. The bug therefore seems to be with creating these resources in parallel.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

* The S3 bucket policies **do** have the correct permission for FSX. This is proven as the apply works if the creation of the resources is done sequentially
* This error only manifests when these resources are creating in parallel. Running the `terraform apply -parallelism=1` will result in successful creation of both data repository associations
* I have validated this is **not** an AWS issue as I called the same API calls from the CLI in parallel and observed success.
* I have ran this scenario multiple times and it consistently fails when creation is being done in parallel. It consistently succeeds when done sequentially.

**Comment by gdavison** [comment]
Thanks for reporting this, @scottblack1. I have one question for clarification before investigating. Are you creating the S3 bucket or updating its permissions as part of the same `terraform apply`, or are they pre-existing?

**Comment by scottblack1** [comment]
@gdavison I have found that this does not matter. I have tested having the S3 buckets pre-existing (i.e. created by a previous apply) and having the S3 buckets created in the same apply.

In both tests it has failed with the issue I mention above.

For example in my latest run my steps were as follows:

1. Run an apply which creates two s3 buckets.
2. Run a second apply which will create the fsx, data_repository_association etc. In this apply I hardcode the S3 bucket arns in the data_repository_associations. 
3. second apply fails with he following:

`Error: error waiting for FSx Lustre Data Repository Association (dra-xxxx) create: unexpected state 'FAILED', wanted target 'AVAILABLE'. last error: Amazon FSx does not have the required permissions for the S3 bucket. Verify that FSx has correct permissions by checking the bucket policy.`

**Comment by superbspeed** [comment]
We are also running into this. Is there an update to this issue?

**Comment by ewbankkit** [comment]
Creation can be made serial using the [`depends_on`](https://developer.hashicorp.com/terraform/language/meta-arguments/depends_on) meta-argument:

```hcl
resource "aws_fsx_data_repository_association" "fsx_lustre_data_repository_association_1" {
  file_system_id                   = aws_fsx_lustre_file_system.fsx_lustre.id
  data_repository_path             = "s3://bucket1"
  file_system_path                 = "/path1"
  s3 {
    auto_import_policy {
      events = ["NEW", "CHANGED", "DELETED"]
    }
    auto_export_policy {
      events = ["NEW", "CHANGED", "DELETED"]
    }
  }

  timeouts {
    create = var.create_timeout
    delete = var.delete_timeout
  }

  tags       = local.tags
}

resource "aws_fsx_data_repository_association" "fsx_lustre_data_repository_association_2" {
  file_system_id                   = aws_fsx_lustre_file_system.fsx_lustre.id
  data_repository_path             = "s3://bucket2"
  file_system_path                 = "/path2"
  s3 {
    auto_import_policy {
      events = ["NEW", "CHANGED", "DELETED"]
    }
    auto_export_policy {
      events = ["NEW", "CHANGED", "DELETED"]
    }
  }

  timeouts {
    create = var.create_timeout
    delete = var.delete_timeout
  }

  tags       = local.tags

  depends_on = [aws_fsx_data_repository_association.fsx_lustre_data_repository_association_1]
}
```
