### ISSUE TITLE
Support for Athena Prepared Statements

### ISSUE THREAD

**Issue by ldmoose** [hashicorp/terraform-provider-aws#24684]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Athena has a new resource available called ['Prepared Statements'](https://docs.aws.amazon.com/athena/latest/ug/querying-with-prepared-statements.html). I would like to be able to control these resources within terraform.

### New or Affected Resource(s)

aws_athena_prepared_statement

### Potential Terraform Configuration

```hcl
resource "aws_athena_prepared_statement" "query_some_table" {
   name = "query_some_table"
   description = "Running a query with filter parameters"
   workgroup = aws_athena_workgroup.my_workgroup.id
   query = "SELECT * FROM my_table WHERE come_column = ?"
}
```

### References

API references: 
https://docs.aws.amazon.com/athena/latest/APIReference/API_CreatePreparedStatement.html
- https://docs.aws.amazon.com/athena/latest/APIReference/API_UpdatePreparedStatement.html
- https://docs.aws.amazon.com/athena/latest/APIReference/API_GetPreparedStatement.html
- https://docs.aws.amazon.com/athena/latest/APIReference/API_DeletePreparedStatement.html

Prepared statement use:
https://docs.aws.amazon.com/athena/latest/ug/querying-with-prepared-statements.html

**Comment by yurib** [comment]
This option is probably more useful for real application, compare to already supported option of `aws_athena_named_query`. Please implement it.
