### ISSUE TITLE
aws_subnet on creation improperly handles IPv6 CIDR pending association state

### ISSUE THREAD

**Issue by moses-aronov** [hashicorp/terraform-provider-aws#24681]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.12.1
```
### Affected Resource(s)

* aws_subnet

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
locals { 
    azs =  { "us-west-2a" : 0, "us-west-2b" : 1, "us-west-2c" : 2 }
    vpc_main_cidr = "10.0.0.0/16"
}

resource "aws_vpc" "main" {
  cidr_block                       = local.vpc_main_cidr
  assign_generated_ipv6_cidr_block = true
  enable_dns_support               = true
  enable_dns_hostnames             = true

  tags = {
    Name          = "${terraform.workspace}-main"
  }
}

resource "aws_subnet" "subnet" {
  for_each = local.azs

  vpc_id            = aws_vpc.main.id

  availability_zone = each.key
  cidr_block        = cidrsubnet(aws_vpc.main.cidr_block, 8, each.value)
  ipv6_cidr_block   = cidrsubnet(aws_vpc.main.ipv6_cidr_block, 8, each.value)

  map_public_ip_on_launch         = true #Need an IPv4 public
  assign_ipv6_address_on_creation = true #IPv6 Please Sir

  tags = {
    Name           = "${terraform.workspace}-main-public"
  }
}

```

### Debug Output

This is a dev environment and the output has been modified/redacted 
https://gist.github.com/moses-aronov/3ea2124e5d7a51998a0a5480fa30dc79

### Expected Behavior

It should successfully create the subnet. 

### Actual Behavior

There is an intermittent error. 
The subnet fails to fully create. 

```
│ Error: error associating EC2 Subnet (subnet-0162ef609ddae733e) IPv6 CIDR block (2600:1f13:9cd:e501::/64): InvalidSubnet.Conflict: The CIDR '2600:1f13:9cd:e501::/64' conflicts with another subnet
│       status code: 400, request id: 75c51f61-1542-4dd0-b94e-2fca79f8e804
│
│   with aws_subnet.main_public_rgn_3["us-west-2b"],
│   on vpc_us_west_2.tf line 80, in resource "aws_subnet" "main_public_rgn_3":
│   80: resource "aws_subnet" "main_public_rgn_3" {
```

### Steps to Reproduce

1. `terraform apply`
2.  You may get the following error
```
│ Error: error associating EC2 Subnet (subnet-0162ef609ddae733e) IPv6 CIDR block (2600:1f13:9cd:e501::/64): InvalidSubnet.Conflict: The CIDR '2600:1f13:9cd:e501::/64' conflicts with another subnet
│       status code: 400, request id: 75c51f61-1542-4dd0-b94e-2fca79f8e804
│
│   with aws_subnet.main_public_rgn_3["us-west-2b"],
│   on vpc_us_west_2.tf line 80, in resource "aws_subnet" "main_public_rgn_3":
│   80: resource "aws_subnet" "main_public_rgn_3" {
```

### Important Factoids

If the subnet is available but the IPv6 CIDR block is still associating, we will run into this error.

After we create subnet we wait for the IPv6 CIDR block to become associated. Once associated we return the subnet object without updating the IPv6 cidr association.

https://github.com/hashicorp/terraform-provider-aws/blob/25a5ad33014830744b832d593c63486df5d38dda/internal/service/ec2/vpc_subnet.go#L197

This will cause problems later in the creation process as we check for associated CIDRs

https://github.com/hashicorp/terraform-provider-aws/blob/25a5ad33014830744b832d593c63486df5d38dda/internal/service/ec2/vpc_subnet.go#L405

### References

* #0000

**Comment by ewbankkit** [comment]
We have been seeing this error in nightly CI:

```
=== RUN   TestAccEC2SubnetCidrReservation_ipv6
=== PAUSE TestAccEC2SubnetCidrReservation_ipv6
=== CONT  TestAccEC2SubnetCidrReservation_ipv6
vpc_subnet_cidr_reservation_test.go:53: Step 1/2 error: Error running apply: exit status 1
Error: error associating EC2 Subnet (subnet-0b96a077b2c236dc8) IPv6 CIDR block (2600:1f14:8bf:c901::/64): InvalidSubnet.Conflict: The CIDR '2600:1f14:8bf:c901::/64' conflicts with another subnet
  status code: 400, request id: 49620341-403f-412e-940d-c39c4edda2dc
with aws_subnet.test,
on terraform_plugin_test.tf line 11, in resource "aws_subnet" "test":
11: resource "aws_subnet" "test" {
--- FAIL: TestAccEC2SubnetCidrReservation_ipv6 (53.78s)
```
