### ISSUE TITLE
Default_tags causes issue on aws_s3_object

### ISSUE THREAD

**Issue by ericrichtert** [hashicorp/terraform-provider-aws#24692]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v1.1.9
on windows_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.13.0

### Affected Resource(s)
* aws_s3_object

### Terraform Configuration Files
Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  default_tags {
    tags = {
      "tag1" = "value1"
      "tag2" = "value"
      "tag3" = "value"
      "tag4" = "value"
      "tag5" = "value"
      "tag6" = "value"
      "tag7" = "value"
      "tag8" = "value"
      "tag9" = "value"
      "tag10" = "value"
      "tag11" = "value"
    }
  }
}

resource "aws_s3_object" "some-bucket" {
  bucket  = "bucket"
  key     = "key"
  content = "hello world"
}

```

### Expected Behavior
Not sure what an acceptable expected behavior is:
* plan time validation on the number of tags for an aws_s3_object?
* only apply the first 10 entries of the map to the aws_s3_object?
* don't apply default_tags on aws_s3_object if the number of tags > 10?  <- The best solution for us....
* don't apply default_tags on aws_s3_object? 

We love the default_tags config in the provider, but we want to extend the number of tags to > 10, and that's not possible because of the use of aws_s3_object.
We don't care about tags on aws_s3_object, so no default_tags on aws_s3_object is fine with us.

The number of 10 tags on an aws_s3_object is a hard limit for AWS.

### Actual Behavior

│ Error: error updating tags: error setting resource tags (bucket/key): BadRequest: Object tags cannot be greater than 10
│ 	status code: 400, request id: XXXX, host id: XXX

### Steps to Reproduce

1. `terraform apply`

**Comment by ewbankkit** [comment]
@ericrichtert Thanks for raising this issue.
It has already been noticed in #21273. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
