### ISSUE TITLE
aws_dynamodb_table removes tags created by aws_dynamodb_tag 

### ISSUE THREAD

**Issue by coolbananas118** [hashicorp/terraform-provider-aws#24702]
We recently started using aws_dynamodb_tag to tag our Dynamo tables instead of using the tags argument on the aws_dynamodb_table resource. But we are finding that the table resource keeps removes the tags which the tags resource is creating. It seems to roughly happen on alternate terraform applys. The first time it deploys correctly then on the 2nd run we see:
```
Terraform detected the following changes made outside of Terraform since the last "terraform apply":
~ tags             = {
...
}
~ tags_all         = {
...
}
```
and then after the warning the apply shows `will be updated in-place...` and removes the tags. As for the `aws_dynamodb_tag` resource it shows no plan activity because they of course exist.

On the next run aws_dynamodb_tag detects they are missing and adds them back and round and round we go.

**Comment by justinretzolk** [comment]
Hey @coolbananas118 👋 Thank you for taking the time to raise this! In this case, I believe this is expected behavior, based on the note found in the [`aws_dynamodb_tag` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_tag) documentation. To save you a click, it has the following two notes:

> Manages an individual DynamoDB resource tag. This resource should only be used in cases where DynamoDB resources are created outside Terraform (e.g., Table replicas in other regions).

and

> This tagging resource should not be combined with the Terraform resource for managing the parent resource. For example, using `aws_dynamodb_table` and `aws_dynamodb_tag` to manage tags of the same DynamoDB Table in the same region will cause a perpetual difference where the `aws_dynamodb_cluster` resource will try to remove the tag being added by the `aws_dynamodb_tag` resource.

**Comment by coolbananas118** [comment]
Hi @justinretzolk thanks for the feedback. That's a shame. We are trying to use the solution to solve the issue where we create a global DB and the replica is un-tagged because AWS don't copy the tags to replicas on Global Dynamo DBs. I guess we're going to have to find another hack 😞

**Comment by justinretzolk** [comment]
Hey @coolbananas118 -- Are you able to provide a sample of the configuration for your `aws_dynamodb_table` and `aws_dynamodb_tag` that you were attempting to use? Based on your description in your last comment, that seems pretty similar to the [example provided](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_tag#example-usage) on the `aws_dynamodb_tag` resource documentation, so I'd be happy to look into a possible solution if you're able to provide a bit more information.

**Comment by coolbananas118** [comment]
Hi @justinretzolk our use case is very similar to that example although we have separate workspaces for EU vs US deployments because the EU needs to deploy first and only after some time the replica is ready after which we can do the US deployment. From the US deployment we do a data lookup e.g. `data "aws_dynamodb_table" "my_table" {name = "xyz"}` and then try to tag it. Would you like me to mock up a simple test case project?

**Comment by coolbananas118** [comment]
@justinretzolk we've managed to solve it quite simply in the end with the following:
`resource "aws_dynamodb_table" "xyz-table" { count        = var.aws_region == "eu-west-1" ? 1 : 0 ... tags = vars.tags }`
and
`resource "aws_dynamodb_tag" "xyz-table_tags" { for_each = var.aws_region == "us-east-2" ? vars.tags : {} ...}`
It works because the EU deployment creates the table and the tags only get applied for the US.
