### ISSUE TITLE
Feature Request: nodejs16.x support for aws_lambda_function

### ISSUE THREAD

**Issue by willfarrell** [hashicorp/terraform-provider-aws#24714]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Nodejs v16 runtime has been released for Lambda. Official announcement coming soon.

Currently returns:
```
Error: expected runtime to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x java8 java8.al2 java11 python2.7 python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 dotnet6 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2], got nodejs16.x
```

I expect it to be resolved when the go SDK is updated, and no change needed.

### New or Affected Resource(s)

- aws_lambda_function

### References

* https://github.com/aws/aws-lambda-base-images/issues/14#issuecomment-1120864028)
* https://github.com/hashicorp/terraform-provider-aws/issues/17450
* [Announcement](https://aws.amazon.com/about-aws/whats-new/2022/05/aws-lambda-adds-support-node-js-16/)
* [Blog post](https://aws.amazon.com/blogs/compute/node-js-16-x-runtime-now-available-in-aws-lambda/)

Requires [AWS SDK for GO v1.44.13](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.13): https://github.com/hashicorp/terraform-provider-aws/pull/24768.

**Comment by ewbankkit** [comment]
We will need to wait for the [AWS SDK for Go](https://github.com/aws/aws-sdk-go) release that adds the enumeration value.

**Comment by xfournet** [comment]
@ewbankkit this has been released in v1.44.13 (2022-05-12)

**Comment by wilcoxmd** [comment]
Hi 👋 . Will Node.js 16 support only be available in v4 of the provider? Or is there a chance of compatibility coming to v3 as well?

**Comment by willfarrell** [comment]
I don't think it's coming to v3 :(. But hopefully an easier migration path to v4 becomes available. https://github.com/hashicorp/terraform-provider-aws/issues/23106

**Comment by RobvH** [comment]
I'd like to encourage the team to make this available for v3.

**Comment by wilcoxmd** [comment]
> I'd like to encourage the team to make this available for v3.

Same. 

As additional context, Node.js 16 support is especially important now that more engineers are working on new laptops with Apple silicon. Previous Node versions aren't compatible with the local environments on those dev machines. It would be a huge help if we could get support for it in v3 of the provider so that our local environments could start to match our deployed ones more quickly while we continue to work toward a v4 upgrade.

**Comment by samwisekind** [comment]
@wilcoxmd @willfarrell @RobvH This was just released for in `v3.75.2`:

https://github.com/hashicorp/terraform-provider-aws/releases/tag/v3.75.2

**Comment by wilcoxmd** [comment]
Amazing! Thanks to all for helping make this happen!

**Comment by anGie44** [comment]
FYI: `v3.75.2` is not yet available as we ran into an issue during the release but we'll likely get the release out on releases.hashicorp.com later today (https://github.com/hashicorp/terraform-provider-aws/issues/24901)
