### ISSUE TITLE
Error when creating RDS MAZ cluster with custom parameter group

### ISSUE THREAD

**Issue by cxystras** [hashicorp/terraform-provider-aws#24721]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform core version: 1.1.8
Terraform provider version: ~>4.10

### Affected Resource(s)

* aws_rds_cluster

RDS MAZ cluster (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/multi-az-db-clusters-concepts.html#multi-az-db-clusters-concepts-overview)

### Terraform Configuration Files

main.tf snippet:
```hcl
....

resource "aws_rds_cluster_parameter_group" "rds_maz_cluster_mysql_pg" {
  name        = "pg-rds-maz-cluster"
  family      = "mysql8.0"
  description = "rds multi az cluster parameter group"
}


resource "aws_rds_cluster" "RDS_MAZ_cluster-mysql" {
  cluster_identifier              = "rds-maz-cluster-mysql"
  availability_zones              = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
  engine                          = "mysql"
  engine_version                  = "8.0.28"
  db_cluster_instance_class       = "db.m6gd.large"
  storage_type                    = "io1"
  allocated_storage               = 100
  iops                            = 1000
  db_subnet_group_name            = "db-subnetgroup"
  db_cluster_parameter_group_name = aws_rds_cluster_parameter_group.rds_maz_cluster_mysql_pg.name
  storage_encrypted               = true
  skip_final_snapshot             = true
  master_username                 = "user"
  master_password                 = "password"
}

....
```

### Debug Output

Error: Error waiting for RDS Cluster state to be "available": unexpected state 'rebooting', wanted target 'available'. last error: %!s(<nil>)
  with aws_rds_cluster.RDS_MAZ_cluster-mysql,
  on [main.tf](http://main.tf/) line 153, in resource "aws_rds_cluster" "RDS_MAZ_cluster-mysql":
 153: resource "aws_rds_cluster" "RDS_MAZ_cluster-mysql" {

### Panic Output

N/A

### Expected Behavior

Terraform should recognise the `rebooting` state as an expected one

### Actual Behavior

Terraform apply breaks with the unexpected state.

### Additional feedback
The reason why this happens is because when the RDS cluster's Parameter Group (PG) is set to a custom one the cluster needs to reboot for the change to be applied (static change). In this case (creating the RDS MAZ cluster with a custom PG) the cluster gets created and as soon as it becomes available it is rebooting, providing a different state back to terraform. Some might classify this as a race-condition. An easy fix would be to add additional logic to handle the rebooting state (additional timeout for waiting the reboot to be completed) and wait  for the cluster to be set back to the `available` one, or add the `rebooting` state to the list of expected states.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

Similar issues:
https://github.com/hashicorp/terraform-provider-aws/issues/2781 (https://github.com/hashicorp/terraform/pull/4490) -> same resource, different target state

**Comment by nadivravivz** [comment]
Hi,

I'm having the same problem with
aws provider: hashicorp/aws v4.20.1
terraform provider: Terraform v1.2.2

This is the error I'm getting:
Error: Error waiting for RDS Cluster state to be "available": unexpected state 'rebooting', wanted target 'available'. last error: %!s(<nil>)

**Comment by matharoo** [comment]
I am getting same error when setting up a postgres rds cluster even with default parameter group.

rds cluster version I am trying to setup:
```
availability_zones = ["us-east-2a", "us-east-2b", "us-east-2c"]
engine = "postgres"
engine_mode = "provisioned"
engine_version = "13.4"
db_cluster_instance_class = "db.m5d.large"
```

my terraform version:
```
terraform {
  required_version = ">= 1.0.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.17.0"
    }
    null = {
      source  = "hashicorp/null"
      version = ">= 2.0"
    }
  }
}
```

Error during terraform apply:
```
Error: Error waiting for RDS Cluster state to be "available": unexpected state 'rebooting', wanted target 'available'. last error: %!s(<nil>)
```
I have a PR to fix this https://github.com/hashicorp/terraform-provider-aws/pull/25718
