### ISSUE TITLE
Can't enable multi attach on io2 volume

### ISSUE THREAD

**Issue by j4ys0n** [hashicorp/terraform-provider-aws#24731]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_ebs_volume

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ebs_volume" "shared-ebs" {
  size = 250
  availability_zone = "us-east-2c"
  type = "io2"
  iops = "3000"
  multi_attach_enabled = true

  tags = {
    Name = "shared-volume"
  }
}
```

### Expected Behavior

multi attach should be enabled on io2 volumes

### Actual Behavior

```hcl
╷
│ Error: 'multi_attach_enabled' must not be set when 'type' is 'io2'
│
│   with module.kafka.aws_ebs_volume.shared-ebs,
│   on file.tf line 78, in resource "aws_ebs_volume" "shared-ebs":
│   78: resource "aws_ebs_volume" "shared-ebs" {
│
╵
```

### Steps to Reproduce

1. `terraform apply`

### References

aws docs: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volumes-multi.html
```
Multi-Attach for io1 volumes is available in the following Regions only: us-east-1, us-west-2, eu-west-1, and ap-northeast-2.
Multi-Attach for io2 and io2 Block Express volumes is available in all Regions that support those volumes types volumes.
```

* #0000

**Comment by ewbankkit** [comment]
@j4ys0n Thanks for raising this issue.
It has already been noticed in #19751. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by j4ys0n** [comment]
ah. i searched but didn't come across that one. thanks!
