### ISSUE TITLE
aws_grafana_workspace_saml_configuration resource editor_role_values not honoring spaces

### ISSUE THREAD

**Issue by bwmetcalf** [hashicorp/terraform-provider-aws#24761]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.3
provider registry.terraform.io/hashicorp/aws v4.8.0

### Affected Resource(s)

aws_grafana_workspace_saml_configuration

### Terraform Configuration Files

```
resource "aws_grafana_workspace_saml_configuration" "default" {
  admin_role_values  = var.okta_admin_group_names
  editor_role_values = var.okta_editor_group_names
  groups_assertion   = "groups"
  idp_metadata_xml   = okta_app_saml.default.metadata
  role_assertion     = "groups"
  workspace_id       = aws_grafana_workspace.default.id
}
```
`okta_editor_group_names = ["Flight", "Software Developers"]`

### Expected Behavior

Once applied, `Flight, Software Developers` should be the value for this field. 

### Actual Behavior

`Flight, Software, Developers` is the value that is getting stored and leads to the following perpetual diff
```
  ~ resource "aws_grafana_workspace_saml_configuration" "default" {
      ~ editor_role_values      = [
            "Flight",
          - "Software",
          - "Developers",
          + "Software Developers",
        ]
        id                      = "g-df5d02ef0e"
        # (10 unchanged attributes hidden)
    }
```

**Comment by drewmullen** [comment]
Hello! Thank you for opening this issue. According to the API docs both the `editor_role_values` and `admin_role_values` only accept specific strings from the Go SDK `RoleValues`: https://docs.aws.amazon.com/sdk-for-go/api/service/managedgrafana/#RoleValues

```go
const (
    // RoleAdmin is a Role enum value
    RoleAdmin = "ADMIN"

    // RoleEditor is a Role enum value
    RoleEditor = "EDITOR"

    // RoleViewer is a Role enum value
    RoleViewer = "VIEWER"
)
```

Also it looks like the resource branches from the API. instead of `{admin,editor}_role_values` it should be
```terraform
role_values {
  admin = [""]
  editor = [""]
}
```

A PR is incoming to add validation, add the new argument to the schema, and deprecation for the 2 older arguments

**Comment by bwmetcalf** [comment]
@drewmullen any update on this?  Anything I can do to help?

**Comment by drewmullen** [comment]
its been picked up by a colleague! I'm not sure status but ill ping them. 

The implementation will fix the split-by-space problem, add a deprecation warning to the `{admin, editor}_role_values` arguments, and introduce the correct arguments to align with the API calls

```terraform
role_values {
  admin = [""]
  editor = [""]
}
```
