### ISSUE TITLE
Documentation on https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_platform_application#argument-reference could be clearer

### ISSUE THREAD

**Issue by Zak-Alford** [hashicorp/terraform-provider-aws#24760]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Didn't really see a place to provide feedback on Terraform documentation, so I'll make something here and get routed to a more appropriate place as, well, appropriate.

SNS Platform Application has arguments around role arns and SNS topics on failure but doesn't really explain that those are used to configure Cloudwatch logging and/or what the logging would look like. Even just referencing [this article](https://aws.amazon.com/premiumsupport/knowledge-center/troubleshoot-failed-sns-deliveries/) would help.

**Comment by justinretzolk** [comment]
Hey @Zak-Alford 👋 Thank you for taking the time to raise this! I've opened a PR to add a bit of additional information in the hopes of providing a bit of additional clarity around the arguments for `aws_sns_platform_application`.
