### ISSUE TITLE
Plugin crashed Terraform v1.0.2 on windows_amd64

### ISSUE THREAD

**Issue by Rudya93** [hashicorp/terraform-provider-aws#24786]
╷
│ Error: Plugin did not respond
│
│   with module.eks.aws_eks_cluster.this[0],
│   on .terraform\modules\eks\main.tf line 11, in resource "aws_eks_cluster" "this":
│   11: resource "aws_eks_cluster" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.eks.module.eks_managed_node_group["bottlerocket_arm"].aws_eks_node_group.this[0],
│   on .terraform\modules\eks\modules\eks-managed-node-group\main.tf line 272, in resource "aws_eks_node_group" "this":
│  272: resource "aws_eks_node_group" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may   
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.eks.module.eks_managed_node_group["bottlerocket_arm"].aws_security_group.this[0],
│   on .terraform\modules\eks\modules\eks-managed-node-group\main.tf line 362, in resource "aws_security_group" "this":
│  362: resource "aws_security_group" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.eks.module.eks_managed_node_group["bottlerocket_arm"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"],
│   on .terraform\modules\eks\modules\eks-managed-node-group\main.tf line 447, in resource "aws_iam_role_policy_attachment" "this":
│  447: resource "aws_iam_role_policy_attachment" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.eks.module.eks_managed_node_group["bottlerocket_arm"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"],
│   on .terraform\modules\eks\modules\eks-managed-node-group\main.tf line 447, in resource "aws_iam_role_policy_attachment" "this":
│  447: resource "aws_iam_role_policy_attachment" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.eks.module.eks_managed_node_group["bottlerocket_arm"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"],
│   on .terraform\modules\eks\modules\eks-managed-node-group\main.tf line 447, in resource "aws_iam_role_policy_attachment" "this":
│  447: resource "aws_iam_role_policy_attachment" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.eks.module.fargate_profile["default"].aws_iam_role.this[0],
│   on .terraform\modules\eks\modules\fargate-profile\main.tf line 31, in resource "aws_iam_role" "this":
│   31: resource "aws_iam_role" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin    
│ logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v4.12.1_x5.exe plugin:

panic: interface conversion: interface {} is nil, not *conns.AWSClient

goroutine 71 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/eks.resourceNodeGroupRead({0xa2027e0, 0xc00206b3e0}, 0x1be6c6e2ea8, {0x0, 0x0})
        github.com/hashicorp/terraform-provider-aws/internal/service/eks/node_group.go:374 +0x1585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000b39a40, {0xa2027e0, 0xc00206b3e0}, 0xd, {0x0, 
0x0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000b39a40, {0xa2027e0, 0xc00206b3e0}, 0xc0019d3ba0, {0x0, 0x0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0000058f0, {0xa202738, 0xc002774c40}, 0xc002775240)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/grpc_provider.go:613 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc001b35f40, {0xa2027e0, 0xc00206a3c0}, 0xc001c276e0)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:746 +0x48c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x8ec2fa0, 0xc001b35f40}, 
{0xa2027e0, 0xc00206a3c0}, 0xc001c27680, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000232e00, {0xa30dd50, 0xc000705860}, 0xc001d87560, 0xc001b54ea0, 0xfe9a970, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc000232e00, {0xa30dd50, 0xc000705860}, 0xc001d87560, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x294

Error: The terraform-provider-aws_v4.12.1_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by Rudya93** [comment]
Hi @bcarranza, yes I have it:
`module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = var.cluster_name
  cluster_version = "1.22"
  # subnets         = var.subnets
  subnet_ids  = module.vpc.private_subnets
  vpc_id      = module.vpc.vpc_id
  enable_irsa = true
  
  eks_managed_node_groups = {
    bottlerocket = {
      create_launch_template = false
      launch_template_name   = ""
      
      ami_type = "BOTTLEROCKET_x86_64"
      platform = "bottlerocket"
      name                          = "${var.cluster_name}"
      instance_types                = [var.instance_type]
      asg_desired_capacity          = 1
      asg_max_size                  = 2
      subnet_ids = module.vpc.public_subnets
    }
    bottlerocket_arm = {
      create_launch_template = false
      launch_template_name   = ""
      
      ami_type = "BOTTLEROCKET_ARM_64"
      platform = "bottlerocket"
      name                          = "${var.cluster_name}-arm"
      instance_types                = [var.instance_type_arm]
      asg_desired_capacity          = 1
      asg_max_size                  = 2
      subnet_ids = module.vpc.public_subnets
    }
  }
  cluster_addons = {
    # Note: https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html#fargate-gs-coredns
    coredns = {
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {}
    vpc-cni = {
      resolve_conflicts = "OVERWRITE"
    }
  }
  fargate_profiles = {
    default = {
      name = "default"
      selectors = [
        {
          namespace = "default"
        }
      ]
    }
  }
`

**Comment by justinretzolk** [comment]
Hey @Rudya93 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?

**Comment by Rudya93** [comment]
---
name: 🐛 Plugin crashed Terraform v1.0.2 on windows_amd64
about: Error: The terraform-provider-aws_v4.12.1_x5.exe plugin crashed!

---





### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment



### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.2
on windows_amd64

### Affected Resource(s)

│ Error: Plugin did not respond
│
│ with module.eks.aws_eks_cluster.this[0],
│ on .terraform\modules\eks\main.tf line 11, in resource "aws_eks_cluster" "this":
│ 11: resource "aws_eks_cluster" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ with module.eks.module.eks_managed_node_group["bottlerocket_arm"].aws_eks_node_group.this[0],
│ on .terraform\modules\eks\modules\eks-managed-node-group\main.tf line 272, in resource "aws_eks_node_group" "this":
│ 272: resource "aws_eks_node_group" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ with module.eks.module.eks_managed_node_group["bottlerocket_arm"].aws_security_group.this[0],
│ on .terraform\modules\eks\modules\eks-managed-node-group\main.tf line 362, in resource "aws_security_group" "this":
│ 362: resource "aws_security_group" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ with module.eks.module.eks_managed_node_group["bottlerocket_arm"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"],
│ on .terraform\modules\eks\modules\eks-managed-node-group\main.tf line 447, in resource "aws_iam_role_policy_attachment" "this":
│ 447: resource "aws_iam_role_policy_attachment" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ with module.eks.module.eks_managed_node_group["bottlerocket_arm"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"],
│ on .terraform\modules\eks\modules\eks-managed-node-group\main.tf line 447, in resource "aws_iam_role_policy_attachment" "this":
│ 447: resource "aws_iam_role_policy_attachment" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ with module.eks.module.eks_managed_node_group["bottlerocket_arm"].aws_iam_role_policy_attachment.this["arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"],
│ on .terraform\modules\eks\modules\eks-managed-node-group\main.tf line 447, in resource "aws_iam_role_policy_attachment" "this":
│ 447: resource "aws_iam_role_policy_attachment" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin
│ logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ with module.eks.module.fargate_profile["default"].aws_iam_role.this[0],
│ on .terraform\modules\eks\modules\fargate-profile\main.tf line 31, in resource "aws_iam_role" "this":
│ 31: resource "aws_iam_role" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin
│ logs may contain more details.

### Terraform Configuration Files



Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Panic Output

Stack trace from the terraform-provider-aws_v4.12.1_x5.exe plugin:

panic: interface conversion: interface {} is nil, not *conns.AWSClient

goroutine 71 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/eks.resourceNodeGroupRead({0xa2027e0, 0xc00206b3e0}, 0x1be6c6e2ea8, {0x0, 0x0})
github.com/hashicorp/terraform-provider-aws/internal/service/eks/node_group.go:374 +0x1585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000b39a40, {0xa2027e0, 0xc00206b3e0}, 0xd, {0x0,
0x0})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000b39a40, {0xa2027e0, 0xc00206b3e0}, 0xc0019d3ba0, {0x0, 0x0})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0000058f0, {0xa202738, 0xc002774c40}, 0xc002775240)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/grpc_provider.go:613 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc001b35f40, {0xa2027e0, 0xc00206a3c0}, 0xc001c276e0)
github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:746 +0x48c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x8ec2fa0, 0xc001b35f40},
{0xa2027e0, 0xc00206a3c0}, 0xc001c27680, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000232e00, {0xa30dd50, 0xc000705860}, 0xc001d87560, 0xc001b54ea0, 0xfe9a970, 0x0)
google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc000232e00, {0xa30dd50, 0xc000705860}, 0xc001d87560, 0x0)
google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.45.0/server.go:919 +0x294

Error: The terraform-provider-aws_v4.12.1_x5.exe plugin crashed!

### Expected Behavior

Destroy all resources in state 

### Actual Behavior

Got error when destroying 

### Steps to Reproduce

1. `terraform destroy --auto-approve`

**Comment by mattburgess** [comment]
@Rudya93 - sorry it's taken us a while to take a look at this. Are you still able to reproduce this? And have you tried with a more recent version of the AWS provider plugin?

**Comment by Rudya93** [comment]
Hello I didn't see such an issue more time.

**Comment by mattburgess** [comment]
Great; thanks for letting us know.
