### ISSUE TITLE
Secret keys should not be stored in immutable objects

### ISSUE THREAD

**Issue by a108439** [hashicorp/terraform-provider-aws#24794]
(https://github.com/hashicorp/terraform-provider-aws/blob/cc9f5305541f79da101d6e7791dee54696aabf55/internal/provider/provider.go#L329)
(https://github.com/hashicorp/terraform-provider-aws/blob/cc9f5305541f79da101d6e7791dee54696aabf55/internal/provider/provider.go#L330)

(https://stackoverflow.com/questions/36720693/immutable-strings-in-go)

Storing sensitive data in immutable objects creates a vulnerability for data leakage because they are stored in memory as plain text.  Reconsider using something more secure.

**Comment by eastebry** [comment]
Hello, thanks for the report!

In short, we do not consider this to be a security issue. Protecting against memory analysis of a running Terraform process or provider is outside of Terraform's threat model. If an attacker is able to inspect the memory state of a running Terraform process then the confidentiality of data may be compromised, Terraform does not attempt to defend against this particular threat.

The ability to access Terraform's process memory implies that the attacker is already in a highly privileged position. In this position, there would be multiple avenues for accessing the sensitive data, variables, or configuration. We recommend only running Terraform in an environment where you are confident about the security of the underlying host.

**Comment by a108439** [comment]
That's a terrible way to think of it.  Mishandling data in code is absolutely the position of the programmer to fix it.   Access to the memory location doesn't have to be granted by the terraform admin, example, if another process is running on the machine say, java, and someone doesn't patch/fix a java vulnerability, it grants access to the terraform application from another program... USE THE PROPER data structures.  there is a reason why they exists, and there's reasons why other programming languages protect against it.
