### ISSUE TITLE
Feature Request: nodejs16.x support for aws_lambda_function

### ISSUE THREAD

**Issue by Giuseppedes** [hashicorp/terraform-provider-aws#24793]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Nodejs v16 runtime has been released for Lambda.

Currently returns:

`Error: expected runtime to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x java8 java8.al2 java11 python2.7 python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 dotnet6 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2], got nodejs16.x`

### New or Affected Resource(s)

* aws_lambda_function

### References

https://aws.amazon.com/blogs/compute/node-js-16-x-runtime-now-available-in-aws-lambda/

**Comment by justinretzolk** [comment]
@sergioUjo We generally release on Thursdays, so barring any delays, 4.15.0 should be out this Thursday, the 19th.

**Comment by Giuseppedes** [comment]
Perfect, thank you @justinretzolk ! :-)|

**Comment by ewbankkit** [comment]
@Giuseppedes Thanks for raising this issue.
It has already been noticed in #24714. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
