### ISSUE TITLE
Support `aws_s3_bucket` in partitions without S3 Object Lock option available

### ISSUE THREAD

**Issue by Simple-Analysis** [hashicorp/terraform-provider-aws#24809]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.0
aws-provider hashicorp/aws v4.10.0

### Affected Resource(s)

* aws_s3_bucket

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_s3_bucket" "test" {
   bucket = "tf-test-bucket"
}
```

### Debug Output

```
...
Error: error creating S3 Bucket (tf-test-bucket): InvalidBucketState: Object Lock headers are not supported for target bucket endpoint.
      status code: 409,
...
```

### Expected Behavior

In partitions that do not support S3 Object Lock, the S3 Bucket will be created when `object_lock_enabled` parameter is not declared.

### Actual Behavior

The `aws_s3_bucket` resource is not created because the  S3 Object Lock is expected to be queried.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The S3 Bucket is being provisioned on a partition that does not have S3 Object Lock available. 

The only workaround seems to be creating the S3 Bucket and using the data source for resources that are dependent on the exported attributes.

**Comment by scotthesterberg** [comment]
Is there any news on this, it seems to have gotten stale, but a fix would be quite helpful.

**Comment by Simple-Analysis** [comment]
Possibly related to refactor effort https://github.com/hashicorp/terraform-provider-aws/issues/23106
