### ISSUE TITLE
aws_security_group cannot be deleted because aws_vpc_endpoint references it

### ISSUE THREAD

**Issue by Kieran-Bacon** [hashicorp/terraform-provider-aws#24820]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.9
on windows_386
+ provider registry.terraform.io/hashicorp/aws v4.13.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.11.0
+ provider registry.terraform.io/hashicorp/tls v3.3.0

### Affected Resource(s)

* aws_security_group 
* aws_vpc_endpoint 

### Expected Behavior

When updating the security group such that it needs to be replaced that is referenced by a `aws_vpc_endpoint` resource, that the plan either deleted the endpoint first before replacing the SG and then creating the endpoint again, or, create a new SG and updating the assigned SG before deleting the old SG.

### Actual Behavior

The SG is to be replaced and the `aws_vpc_endpoint` is to be updated, the terraform process will not halt as it waits for a SG to be deleted that cannot be deleted since it is assigned to the `aws_vpc_endpoint`

### Steps to Reproduce

Define and endpoint and SG
```
# Create security group for kinesis endpoint
resource "aws_security_group" "KinesisEndpointSG" {
  name        = "${local.cluster_name}-Kinesis-Endpoint-SG"
  description = "Allow traffic from vpc to kinesis"
  vpc_id      = aws_vpc.Main.id

  ingress {
    cidr_blocks      = [aws_vpc.Main.cidr_block]
    protocol         = "-1"  # All protocols
    from_port        = 0
    to_port          = 0
  }

  egress {
    cidr_blocks      = ["0.0.0.0/0"]
    from_port        = 0
    to_port          = 0
    protocol         = "-1"
  }

  tags = {
    Name = "${local.cluster_name}-Kinesis-Endpoint-SG"
    Owner = "${local.cluster_name}-Kinesis-Endpoint"
  }
}

# Create Kinesis endpoint service
resource "aws_vpc_endpoint" "kinesis" {
  vpc_id       = "${aws_vpc.Main.id}"
  service_name = "com.amazonaws.eu-west-2.kinesis-streams"
  vpc_endpoint_type = "Interface"

  security_group_ids = [
    "${aws_security_group.KinesisEndpointSG.id}",
  ]

  subnet_ids          = [data.aws_subnets.Private.ids[0],data.aws_subnets.Private.ids[1]]
  private_dns_enabled = true

  tags = {
      Name = "${local.cluster_name}-Kinesis-Endpoint"
    # Environment = "test"
  }
}
```

1. `terraform apply`
2. update the name of the security group
3. `terraform apply`
4. terraform timeout changes.

```
╷
│ Error: Error deleting security group: DependencyViolation: resource sg-009a8fcf161a6b0b6 has a dependent object
│       status code: 400, request id: d9fba914-2bb2-4fd9-85e7-3c843315cc55
```

**Comment by mattburgess** [comment]
This is, unfortunately, a long standing issue. https://github.com/hashicorp/terraform-provider-aws/issues/1671 is probably the oldest incarnation of this. This [comment](https://github.com/hashicorp/terraform-provider-aws/issues/1671#issuecomment-367304669) might help you out.

**Comment by justinretzolk** [comment]
Hey @Kieran-Bacon 👋 Thank you for taking the time to raise this! As Matt mentioned above, it looks like this is a duplicate of #1671. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #1671.
