### ISSUE TITLE
`aws_cognito_identity_pool_provider_principal_tag` Read operations appears to use wrong value for identityPoolId when using OIDC provider

### ISSUE THREAD

**Issue by bellis-ai** [hashicorp/terraform-provider-aws#24834]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
AWS v4.13.0
Terraform v1.1.9

### Affected Resource(s)

* aws_cognito_identity_pool_provider_principal_tag

### Terraform Configuration Files

```hcl
resource "aws_iam_openid_connect_provider" "idp" {
  url = "https://${var.issuer}"

  client_id_list = [
    var.audience
  ]

  thumbprint_list = [var.idp_thumbprint]
}

resource "aws_cognito_identity_pool" "pool" {
  identity_pool_name               = var.deployment_name
  allow_unauthenticated_identities = false
  allow_classic_flow               = false

  openid_connect_provider_arns = [
    aws_iam_openid_connect_provider.idp.arn
  ]
}

resource "aws_cognito_identity_pool_provider_principal_tag" "mapping" {
  identity_pool_id       = aws_cognito_identity_pool.pool.id
  identity_provider_name = aws_iam_openid_connect_provider.idp.arn
  use_defaults           = false
  principal_tags = {
    username = "preferred_username"
  }
}
```

### Debug Output
Not posting the full output because I've got a lot of components and making sure everything is redacted is tedious. Here's a relevant snippet however:
```
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: cognito-identity.us-east-1.amazonaws.com
User-Agent: APN/1.0 HashiCorp/1.0 Terraform/1.1.9 (+https://www.terraform.io) terraform-provider-aws/dev (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go/1.44.4 (go1.17.6; linux; amd64)
Content-Length: 164
Authorization: AWS4-HMAC-SHA256 Credential=ASDFASDFASDFASDF/123123123/us-east-1/cognito-identity/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date;x-amz-target, Signature=[redacted]
Content-Type: application/x-amz-json-1.1
X-Amz-Date: 20220518T014600Z
X-Amz-Target: AWSCognitoIdentityService.GetPrincipalTagAttributeMap
Accept-Encoding: gzip

{"IdentityPoolId":"us-east-1:aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee:arn:aws:iam::XXXXXXXXXXXX:arn:aws:iam::XXXXXXXXXXXX","IdentityProviderName":"oidc-provider/my.idp.url.com"}
```

### Expected Behavior

Apply and Read operations occur just fine

### Actual Behavior
The resource is created, but the create ends up failing with this message:

```
Error: reading Amazon Cognito Identity Pool Provider Principal Tag (us-east-1:aaaaaaaa-bbbb-cccc-dddd-
eeeeeeeeeeee:arn:aws:iam::XXXXXXXXXXXX:oidc-provider/my.idp.url.com): ValidationException: 2 validation errors detected: Value 
'us-east-1:aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee:arn:aws:iam::XXXXXXXXXXXX' at 'identityPoolId' failed to satisfy constraint: 
Member must satisfy regular expression pattern: [\w-]+:[0-9a-f-]+; Value 'us-east-1:aaaaaaaa-bbbb-cccc-dddd-
eeeeeeeeeeee:arn:aws:iam::XXXXXXXXXXXX' at 'identityPoolId' failed to satisfy constraint: Member must have length less than or 
equal to 55
```

This error also reoccurs on reapply/plan/refresh

### Steps to Reproduce

1. `terraform apply`
2. `terraform refresh`

### Important Factoids

This was only tested when using an OIDC type identity provider, using Okta as the idp

**It is also appears that  identity_provider_name must be set to the OIDC provider ARN in order to have any effect. This factoid is absent from both Terraform provider and official AWS documentation.**

**Comment by bellis-ai** [comment]
Temporary workaround

```
resource "null_resource" "mapping" {
  triggers = {
    tags = jsonencode({
      username = "preferred_username"
    })
    region            = var.aws_region
    profile           = var.aws_profile
    pool_id           = aws_cognito_identity_pool.pool.id
    identity_provider = aws_iam_openid_connect_provider.idp.arn
  }
  provisioner "local-exec" {
    when    = create
    command = "aws cognito-identity set-principal-tag-attribute-map --identity-pool-id ${self.triggers.pool_id} --identity-provider-name ${self.triggers.identity_provider} --principal-tags '${self.triggers.tags}' --profile ${self.triggers.profile} --region ${self.triggers.region}"
  }
  provisioner "local-exec" {
    when    = destroy
    command = "aws cognito-identity set-principal-tag-attribute-map --identity-pool-id ${self.triggers.pool_id} --identity-provider-name ${self.triggers.identity_provider} --no-use-defaults --profile ${self.triggers.profile} --region ${self.triggers.region}"
  }
}
```

**Comment by danquack** [comment]
The constraints to this come from the docs:
> [IdentityPoolId](https://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_SetPrincipalTagAttributeMap.html#API_SetPrincipalTagAttributeMap_ResponseSyntax)

    The ID of the Identity Pool you want to set attribute mappings for.
    Type: String
    Length Constraints: Minimum length of 1. Maximum length of 55.
    Pattern: [\w-]+:[0-9a-f-]+ 
>
And are applied here: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/cognitoidentity/pool_provider_principal_tag.go#L36-L38

It appears the sdk has a similar regex check: https://github.com/aws/aws-sdk-go/blob/e2d6cb448883e4f4fcc5246650f89bde349041ec/models/apis/cognito-identity/2014-06-30/api-2.json#L685-L689

I'm curious how the cli work. Maybe its not doing the same validation?

**Comment by fmasuhr** [comment]
I was just running into the same issue. The problem here is about how the internal IT is created and decoded. 
The id is create [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/cognitoidentity/pool_provider_principal_tag.go#L84) by concatenating the `poolId` with the `providerName` using `:`. However the `providerName` can contain a colon itself breaking the decoding of id over [here](https://github.com/hashicorp/terraform-provider-aws/blob/268b2a15c30e588f78362c7700c4d708d7d45c65/internal/service/cognitoidentity/pool_provider_principal_tag.go#L178)
