### ISSUE TITLE
Add new AWS Pinpoint resource aws_pinpoint_phone_number

### ISSUE THREAD

**Issue by JamesMarino** [hashicorp/terraform-provider-aws#24855]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the Amazon Pinpoint [resources](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/provider/provider.go#L1714-L1724) are lacking and mostly just contain functions from the base [Pinpoint API](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/pinpoint/index.html). My plan is to add functionality from the [recently added](https://github.com/aws/aws-sdk-go/blob/main/CHANGELOG.md#release-v14330-2022-03-31) [Pinpoint SMS Voice V2 API](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/pinpoint-sms-voice-v2/index.html) which will allow the creation of phone numbers in Amazon Pinpoint. 

A new provider will need to be added - `github.com/aws/aws-sdk-go/service/pinpointsmsvoicev2` as this is currently not in the providers generated files. The `aws_pinpoint_phone_number` resource will currently be the only resource for this specific provider so far.

**Note:** I've currently made a start on this feature request and should have a PR up soon with the changes.

### New or Affected Resource(s)

* aws_pinpoint_phone_number

### Potential Terraform Configuration

```hcl
resource "aws_pinpoint_phone_number" "test" {
  iso_country_code = "US"
  message_type     = "TRANSACTIONAL"
  number_type      = "TOLL_FREE"

  number_capabilities = [
    "SMS"
  ]
}
```

**Note:** More parameters will need to be added to the resource as per the API documentation below.

### References

* [Describe Phone Numbers](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/pinpoint-sms-voice-v2/describe-phone-numbers.html)
* [Request Phone Numbers](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/pinpoint-sms-voice-v2/request-phone-number.html)
* [Update Phone Numbers](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/pinpoint-sms-voice-v2/update-phone-number.html)
* [Release Phone Numbers](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/pinpoint-sms-voice-v2/release-phone-number.html)

**Comment by crosbymichael1** [comment]
Any update on this @JamesMarino ? This is a helpful utility.

**Comment by JamesMarino** [comment]
> Any update on this @JamesMarino ? This functionality will be helpful.

Hey @crosbymichael1 I have a PR ready to go here - https://github.com/hashicorp/terraform-provider-aws/pull/25036 - just waiting on approval by the Hashicorp team. Giving the PR a 👍🏼 should move it up the queue in terms of priority. Thanks!
