### ISSUE TITLE
DocumentDB - Performance insights

### ISSUE THREAD

**Issue by Aur0nd** [hashicorp/terraform-provider-aws#24857]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I believe this is a new DocumentDB feature, Performance Insights, which is something we cannot manage via terraform, it would be wonderful to have that as part of our terraform code instead of manually enabling/disabling it.

### New or Affected Resource(s)

aws_docdb_cluster_instance

### Potential Terraform Configuration

```hcl
resource "aws_docdb_cluster_instance" "docdb" {
  performance_insights_enabled = true/false
 }
```

### References

* #0000

**Comment by rahul-amzn** [comment]
will look into it.

**Comment by daftkid** [comment]
Hello, I've tried to take a look on it too and that's what I've found out:
- AWS SDK for Go has been updated for `docdb`: both fields have been added to `CreateDBInstanceInput` [here](https://github.com/aws/aws-sdk-go/blob/7f8f9a3d36b6a6ec4b02c6e89193288f2427c154/service/docdb/api.go#L7113) and [here](https://github.com/aws/aws-sdk-go/blob/7f8f9a3d36b6a6ec4b02c6e89193288f2427c154/service/docdb/api.go#L7131). So it is possible to create an instance with Performance Insights configuration
- However, `DBInstance` [struct](https://github.com/aws/aws-sdk-go/blob/7f8f9a3d36b6a6ec4b02c6e89193288f2427c154/service/docdb/api.go#L8604) (which is used to get values back from AWS resource) hasn't been updated with these fields so IMO it's not possible to read them back and maintain these values in the state.

**Comment by meetreks** [comment]
I am working on the issue, will keep posted.

**Comment by meetreks** [comment]
PR out for review and merge. Watch this space.

**Comment by daftkid** [comment]
@meetreks Could you please your PR to the issue? It's hard to find it...

**Comment by meetreks** [comment]
@daftkid here it comes, https://github.com/hashicorp/terraform-provider-aws/pull/24948/

**Comment by Aur0nd** [comment]
Hey guys @meetreks @daftkid I see that you've done 99.0% of the work - is there anything I can do to help finalize this feature? I think it's ready for merge

**Comment by meetreks** [comment]
@Aur0nd it is ready for merge, but guess we need to puss this with Hashi to get it merged.

**Comment by adamstirk-ct** [comment]
Is there any update on this? We'd like to enable performance insights using Terraform
