### ISSUE TITLE
Can't manage the default stage of aws_apigatewayv2_api

### ISSUE THREAD

**Issue by dgholz** [hashicorp/terraform-provider-aws#24852]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.75.1
```

Although I have also tried it with `4.14.0`

### Affected Resource(s)

* `aws_apigatewayv2_api`
* `aws_apigatewayv2_stage`

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Boilerplate to create all the resources mentioned in the actual problem

resource "aws_iam_role" "iam_for_lambda" {
  name = "iam_for_lambda"
  
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

resource "aws_lambda_function" "test_lambda" {
  function_name = "lambda_function_name"
  role          = aws_iam_role.iam_for_lambda.arn
  image_uri     = "${aws_ecr_repository.lambda_image.repository_url}:latest"

  package_type  = "Image"

  environment {
    variables = {
      foo = "bar"
    }
  } 
}     

resource "aws_cloudwatch_log_group" "api_lamdba_logs" {
  name = "logs-for-api-and-lambda"
}

resource "aws_apigatewayv2_api" "api_for_lambda" {
  name          = "my-gateway"
  protocol_type = "HTTP"
  target        = aws_lambda_function.test_lambda.arn
}

### Here's where the problem is

resource "aws_apigatewayv2_stage" "default" {
  api_id = aws_apigatewayv2_api.api_for_lambda.id
  name   = "$default"
  access_log_settings {
    destination_arn = aws_cloudwatch_log_group.api_lamdba_logs.arn
    format          = "$context.identity.sourceIp - - [$context.requestTime] \"$context.httpMethod $context.routeKey $context.protocol\" $context.status $context.responseLength $context.requestId $context.integrationErrorMessage"
  }
}
```

### Expected Behavior

Access log settings for the automatically-created `$default` stage should have been updated

### Actual Behavior

`terraform` fails with:
```
aws_apigatewayv2_stage.default: Creating...
╷
│ Error: error creating API Gateway v2 stage: ConflictException: Stage already exists
│ 
│   with aws_apigatewayv2_stage.default,
│   on api_gateway.tf line 7, in resource "aws_apigatewayv2_stage" "default":
│    7: resource "aws_apigatewayv2_stage" "default" {
│ 
╵
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

API Gateway always automatically creates a stage called `$default` for an HTTP API; there's no option to prevent it. I think this should be handled in the same sort of way as [a default VPC: if it already exists, update it instead of trying to create it](https://github.com/hashicorp/terraform-provider-aws/blob/2d251f4f3411174bc5a3b3e82abf8249663b94fa/internal/service/ec2/vpc_default_vpc.go#L164).

**Comment by justinretzolk** [comment]
Hey @dgholz 👋 I took a quick look over this and found a bit of information that might help. The first clue I found was a note at the bottom of the `aws_apigatewayv2_stage` documentation, just [under the import information](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_stage#import). To save you a click, the note says:

> The API Gateway managed stage created as part of [quick_create](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-basic-concept.html#apigateway-definition-quick-create) cannot be imported.

Looking at the `quick_create` documentation that it links to, it looks like that's what creates the `$default` stage you're looking to manage here. With that in mind, I took a look over the docs for [`aws_apigatewayv2_api`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_api) and noticed several arguments that had the note "Part of quick create," one of which is `target`, which you've specified here. This is leading to the default integration, stage, and route being created.

If I've understood the documentation correctly, this should mean that if you remove the `target` argument from your `aws_apigatewayv2_api` resource and replace it with appropriately configured `aws_apigatewayv2_integration`, `aws_apigatewayv2_route`, and `aws_apigatewayv2_stage` resources (perhaps `aws_apigatewayv2_integration_response` as well; I'm honestly not entirely certain), you should be able to replicate the quick create behavior, but with Terraform-managed resources.

**Comment by dgholz** [comment]
@justinretzolk yes, that is currently what I'm doing. I'm just amazed that the provider has code to exclude this resource from management when it's extremely possible to modify settings (like access logging) via the AWS Console. I'd love to be able to add access logging via Terraform without having to recreate all the quick_create configuration.

I saw the caveat on importing, thanks.

**Comment by dgholz** [comment]
> It seems like this is a limitation on AWS' side, but to confirm, are you seeing behavior that's different than when I saw in my testing?

So you're correct about the stage being managed by the API Gateway service, but in my use case I want to add access logging for that stage. That's configured under Monitoring, and I can enable it even for managed stages. There's no limitation from AWS on this. Here's my stage:
![image](https://user-images.githubusercontent.com/1451750/169509342-38aa3441-caea-4a85-8a4f-870161c19f26.png)
and here's me enabling access logging on it:
![image](https://user-images.githubusercontent.com/1451750/169509394-e51a2521-ede5-4cfa-91bd-ef291be53a09.png)

The provider exposes the monitoring settings on the `api_gatewayv2_stage` resource (`access_log_settings`), but refuses to attempt to set them when it sees the `apiGatewayManaged` attribute on the stage, even though the API would allow it. I feel like I'd prefer that the provider would attempt updates to the resource regardless of the `apiGatewayManaged` attribute, and report back the API errors if I attempted to modify a managed setting.

**Comment by dgholz** [comment]
There's the additional problem that I can't manipulate the `$default` stage via Terraform, since it's automatically-created when the `api_gatewayv2_api` resource is created & no `api_gatewayv2_stage` resource is recorded in the state file. Hence my original request to treat the `$default` stage in a similar way to the default VPC: if it's not in the state file and needs to be created, first try finding it and updating it.

I see now there's another issue in that the update function for `api_gatewayv2_stage` checks for the `apiGatewayManaged` attribute and refuses to import or update it. I feel like I'd prefer for the AWS API to tell me I'm not allowed to do it, instead of the provider.

**Comment by justinretzolk** [comment]
Hey @dgholz -- I appreciate your additional context here! That's very helpful, and is something I'd not taken into account (the adding the logging configuration bit, I mean). With that in mind, I'm going to mark this as an enhancement so that our maintainers can take a look at this as soon as time allows.

**Comment by alxsavard** [comment]
Hi! I'm also facing this issue. Did anyone managed to find a way around it? RIght now I'm creating a second stage and adding logs to this one instead, but then the $default stage is juste sitting there useless so it's a bit anoying.

**Comment by bryanmehall** [comment]
@alxsavard 

(for v2 http apis)
I removed the "target" field for the `aws_apigatewayv2_api` resource and then changed the name of the `aws_apigatewayv2_stage` resource to `"$default"` (see @justinretzolk s answer above) That worked along with using the `aws_apigatewayv2_api_mapping` resource.
