### ISSUE TITLE
aws_ami support for TPM2.0 

### ISSUE THREAD

**Issue by dbeecham** [hashicorp/terraform-provider-aws#24860]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS released TPM2.0 ("NitroTPM") support for EC2 a couple of days ago. With this, EC2 instances can store private keys in the TPM2.0 enclave instead of on-disk, which is really neat stuff.

### New or Affected Resource(s)

* aws_ami

### Potential Terraform Configuration

Maybe something like

```hcl
resource "aws_ami" "example" {
  name                = "terraform-example"
  virtualization_type = "hvm"
  root_device_name    = "/dev/xvda"
  boot_mode = "uefi"
  tpm_support = "v2.0"

  ebs_block_device {
    device_name = "/dev/xvda"
    snapshot_id = "snap-xxxxxxxx"
    volume_size = 8
  }
}
```

### References

* Announcement: https://aws.amazon.com/about-aws/whats-new/2022/05/amazon-ec2-nitrotpm-uefi-secure-boot/
* Blog post: https://aws.amazon.com/blogs/aws/amazon-ec2-now-supports-nitrotpm-and-uefi-secure-boot/
* Deep dive blog from December 2021: https://aws.amazon.com/blogs/compute/deep-dive-into-nitrotpm-and-uefi-secure-boot-support-in-amazon-ec2/
* Docs on creating an AMI with TPM2.0 support: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enable-nitrotpm-support-on-ami.html

**Comment by nialdaly** [comment]
I'll take a look at this one! Thanks!
