### ISSUE TITLE
aws_cloudformation_stack_set fails when auto_deployment block is defined but enabled is false

### ISSUE THREAD

**Issue by erhudy** [hashicorp/terraform-provider-aws#24879]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.14.0
```

### Affected Resource(s)

* aws_cloudformation_stack_set

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

(see reproduce steps for additional context on this resource)

```hcl
resource "aws_cloudformation_stack_set" "this" {
  name = "bloop-blorp"
  description = "bloop"
  capabilities = ["CAPABILITY_IAM"]
  permission_model = "SERVICE_MANAGED"
  template_body = <<EOF
[...template goes here...]
EOF

  auto_deployment {
    enabled = false
  }

  parameters = {
    [...parameters go here...]
  }
}
```

### Debug Output

Cannot provide debug output at this time because it contains unanonymizable information.

### Panic Output

N/A

### Expected Behavior

Terraform should be able to create/update the StackSet with auto_deployment off.

### Actual Behavior

Terraform fails with the error message

```
│ Error: error updating CloudFormation StackSet (bloop-blorp): ValidationError: Can only set RetainStacksOnAccountRemoval if AutoDeployment is enabled.
│       status code: 400, request id: 8c0783c5-7d71-4171-a039-1b2c89051af6
│ 
│   with aws_cloudformation_stack_set.this,
│   on main.tf line 19, in resource "aws_cloudformation_stack_set" "this":
│   19: resource "aws_cloudformation_stack_set" "this" {
│
```

Terraform should only be attempting to set RetainStacksOnAccountRemoval if explicitly provided, but it always passes False if the `auto_deployment` block is provided, even if `retain_stacks_on_account_removal` is omitted or set to `null`.

### Steps to Reproduce

Reproducing this is straightforward but requires a somewhat elaborate AWS account set up with Organizations in order to properly execute the CloudFormation StackSet setup. My instructions to reproduce detail exactly what I've been doing (I understand that controlling CFn from TF is kind of weird but it's because we have some StackSets that drive account provisioning from Control Tower/Service Catalog).

1. Have an AWS account that is the root of an Organization.
2. Create a StackSet through the console; the only details that matter are that the permission model is "service-managed" in order to enable the auto-deployment features and auto-deployment is not enabled. You can pick a random template.
3. Complete the StackSet creation; it will begin to automatically run against the target org/OU. You can cancel it or let it go, doesn't matter.
4. Import the StackSet into Terraform with `terraform import aws_cloudformation_stack_set.this bloop-blorp`
5. Run an apply
6. Get the error message about RetainStacksOnAccountRemoval

### Important Factoids

This should be a pretty simple fix (just omit the relevant setting from the POST unless it's explicitly set) and I'm happy to work up the change if you're willing to accept the PR.

### References

* #0000

**Comment by svalevka** [comment]
This bug has been opened for a year.
Is there a chance it can be fixed?
