### ISSUE TITLE
problem with passing ip sets in dynamic suricata rule group

### ISSUE THREAD

**Issue by sharatotapally** [hashicorp/terraform-provider-aws#24884]
I am trying to create ip sets and port sets to pass and use them as values in my source/dest/port fields in the following TF code. But I am getting an error saying the ipsets are not valid IP blocks

**ERROR:** 

$PRODWEST" is not a valid CIDR block: invalid CIDR address: $PRODWEST ; Error: expected rule_group.0.rules_source.0.stateful_rule.0.header.0.destination to be one of [ANY], got $PRODWEST ; Error: "$PRODEAST" is not a valid CIDR block: invalid CIDR address: $PRODEAST ; Error: expected rule_group.0.rules_source.0.stateful_rule.0.header.0.source to be one of [ANY], got $PRODEAST
—

**MY IP AND PORT SETS** 

{
   "ip_sets" : {
      "PRODWEST" : ["10.0.1.0/24", "10.0.2.0/24"],
      "PRODEAST" : ["10.0.3.0/24"]
   },

   "port_sets" : {
      "WEB" : ["443", "80"],
      "SQL" : ["3306", "8082"]
   },

   "xrulegroup":[
      {
         "action":"PASS",
         "destination":"$PRODWEST",
         "destination_port":"$WEB",
         "direction":"FORWARD",
         "protocol":"IP",
         "source":"$PRODEAST",
         "source_port":"ANY"
      }
   ]
}

**This is my TF code**

resource "aws_networkfirewall_rule_group" "xrulegroup" {
  type  = "STATEFUL"
  name        = "xrulegroup"
  capacity    = 5000
  rule_group {
    stateful_rule_options {
        rule_order = "STRICT_ORDER"
    }
    
    rule_variables {
          dynamic "ip_sets" {
            for_each = var.ip_sets
            content {
              key = ip_sets.key
              ip_set {
                definition = ip_sets.value
              }
            }
          }
          dynamic "port_sets" {
            for_each = var.port_sets
            content {
              key = port_sets.key
              port_set {
                definition = port_sets.value
              }
            }
          }
    
    }
    
    rules_source {
      dynamic "stateful_rule" {
        for_each = var.cross-environment-rulegroup
        content {
          action = stateful_rule.value.action
          header {
            destination      = stateful_rule.value.destination
            destination_port = stateful_rule.value.destination_port
            direction        = stateful_rule.value.direction
            protocol         = stateful_rule.value.protocol
            source           = stateful_rule.value.source
            source_port      = stateful_rule.value.source_port
          }
          rule_option {
            keyword = "sid:${stateful_rule.key + 1}"
          }
          rule_option {
            keyword = "gid:${stateful_rule.key + 1}"
          }
        }
      }
    }
  }
  lifecycle {
    create_before_destroy = true
  }
}

**Comment by justinretzolk** [comment]
Hey @sharatotapally 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?

**Comment by victorjulien** [comment]
Just happened to see this bug by chance. I'm not familiar with this project but I am developing Suricata.

This looks suspicious to me: `"PRODWEST" : ["10.0.1.0/24", "10.0.2.0/24"],`, as Suricata address notation does not allow the double quotes inside the brackets.

I would suspect that something like `[10.0.1.0/24, 10.0.2.0/24]` or `"[10.0.1.0/24, 10.0.2.0/24]"` would make Suricata more happy.

Entirely possible I'm missing something here, but perhaps worth a try.

**Comment by sharatotapally** [comment]
Thank you. I think this is because our TF was on an earlier version of the code . I had to upgrade it to 4.4 . Version upgrade solved the issue for me. Thanks for your quick response though Victor. Although I am seeing a different issue with TF rules. They are not appearing in AWS GUI in the same order we are passing it through TF. Do you have any clue about this? 

Thanks 
Sharadwi Totapally

**Comment by justinretzolk** [comment]
Hey @sharatotapally 👋 I'm glad to hear you were able to work past this! I saw you opened #24977 to address the ordering of the rules, so wanted to mention that here so that we could try to keep the conversations limited to the issue they're addressing. Given that this issue was resolved, I'll mark it as such. If you feel I've done this in error, please do let me know! 🙂
