### ISSUE TITLE
datasource/aws_iam_policy: lookup by name_prefix

### ISSUE THREAD

**Issue by rumeshmadhusanka** [hashicorp/terraform-provider-aws#24892]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Requesting to add the capability to filter iam policies using name prefix

### New or Affected Resource(s)

* datasource/aws_iam_policy

### Potential Terraform Configuration

```hcl
data "aws_iam_policy" "example" {
  name_prefix = "test_policy_prefix"
}
```

**Comment by ewbankkit** [comment]
@rumeshmadhusanka Thanks for raising this issue.
You should be able to use the [`path_prefix`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy#path_prefix) argument introduced in [**v3.38.0**](https://github.com/hashicorp/terraform-provider-aws/blob/v3.38.0/CHANGELOG.md) via https://github.com/hashicorp/terraform-provider-aws/pull/6084.
