### ISSUE TITLE
aws_organizations_account (v4.15.0): Create Account Status does not validate

### ISSUE THREAD

**Issue by xmj** [hashicorp/terraform-provider-aws#24897]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform v1.0.10
terraform-provider-aws v4.15.0 (latest release)

### Affected Resource(s)

* aws_organizations_account

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl

resource "aws_organizations_account" "account" {
  name                       = var.account_name
  email                      = local.account_tags.account_email
  iam_user_access_to_billing = "ALLOW"
  parent_id                  = local.parent_id
  role_name                  = var.organization_role
  tags                       = local.account_tags
  close_on_deletion          = true

  lifecycle {
    ignore_changes = [
      role_name,
      iam_user_access_to_billing
    ]
  }
}

```

### Panic Output

```
2022-05-20T07:43:02.902Z [DEBUG] provider.terraform-provider-aws_v4.15.0_x5: [aws-sdk-go] {"Parents":[{"Id":"X","Type":"ORGANIZATIONAL_UNIT"}]}: timestamp=2022-05-20T07:43:02.902Z
2022-05-20T07:43:02.902Z [DEBUG] provider.terraform-provider-aws_v4.15.0_x5: [aws-sdk-go] DEBUG: Request organizations/DescribeCreateAccountStatus Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: organizations.us-east-1.amazonaws.com
User-Agent: APN/1.0 HashiCorp/1.0 Terraform/1.0.10 (+https://www.terraform.io) terraform-provider-aws/dev (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go/1.44.15 (go1.17.6; linux; amd64) TFE/v202204-2
Content-Length: 41
Authorization: AWS4-HMAC-SHA256 Credential=XXX/20220520/us-east-1/organizations/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date;x-amz-target, Signature=XXX
Content-Type: application/x-amz-json-1.1
X-Amz-Date: 20220520T074302Z
X-Amz-Target: AWSOrganizationsV20161128.DescribeCreateAccountStatus
Accept-Encoding: gzip

-----------------------------------------------------: timestamp=2022-05-20T07:43:02.902Z
2022-05-20T07:43:02.934Z [DEBUG] provider.terraform-provider-aws_v4.15.0_x5: [aws-sdk-go] DEBUG: Response organizations/DescribeCreateAccountStatus Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 162
Content-Type: application/x-amz-json-1.1
Date: Fri, 20 May 2022 07:43:02 GMT
X-Amzn-Requestid: X

-----------------------------------------------------: timestamp=2022-05-20T07:43:02.934Z
2022-05-20T07:43:02.934Z [DEBUG] provider.terraform-provider-aws_v4.15.0_x5: [aws-sdk-go] {"__type":"InvalidInputException","Message":"You provided a value that does not match the required pattern.","Reason":"INVALID_PATTERN:CREATE_ACCOUNT_REQUEST_ID"}: timestamp=2022-05-20T07:43:02.934Z
2022-05-20T07:43:02.934Z [DEBUG] provider.terraform-provider-aws_v4.15.0_x5: [aws-sdk-go] DEBUG: Validate Response organizations/DescribeCreateAccountStatus failed, attempt 0/25, error InvalidInputException: You provided a value that does not match the required pattern.
{
RespMetadata: {
StatusCode: 400,
RequestID: "X"
},
Message_: "You provided a value that does not match the required pattern.",
Reason: "INVALID_PATTERN:CREATE_ACCOUNT_REQUEST_ID"
}: timestamp=2022-05-20T07:43:02.934Z
2022-05-20T07:43:02.936Z [DEBUG] provider.terraform-provider-aws_v4.15.0_x5: [aws-sdk-go] DEBUG: Response organizations/DescribeCreateAccountStatus Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 162
Content-Type: application/x-amz-json-1.1
Date: Fri, 20 May 2022 07:43:02 GMT
X-Amzn-Requestid: X

```

### Expected Behavior

Terraform Plan works for the AWS Organization

### Actual Behavior

Terraform fails with the following error:
```
 Error: finding AWS Organizations Create Account Status (X): InvalidInputException: You provided a value that does not match the required pattern. { RespMetadata: { StatusCode: 400, RequestID: "XXX" }, Message_: "You provided a value that does not match the required pattern.", Reason: "INVALID_PATTERN:CREATE_ACCOUNT_REQUEST_ID" } 
```
### Steps to Reproduce

1. `terraform plan`

### Important Factoids

We have two AWS Organizations. One of them works fine with v4.15.0, the other works fine with v4.14.0 but crashes as described above.

### References

* #0000

**Comment by srgustafson8** [comment]
Seeing this today also - plans that don't do a refresh pass for us, but a refresh+plan fails

**Comment by linkvt** [comment]
I just created a PR to fix this (see reference above), but am not really confident in contributing here after reading the docs only now.

A detailed explanation can be found in the PR, but this is definitely a bug caused by account reads from AWS using some logic that only works after creating an account.
I cannot see how this would work for anyone with an existing account by looking at the code, @xmj  are you really sure that refreshing works for one of your orgs?

**Comment by xmj** [comment]
Hi,
It worked once in the morning. Now we tried to create new accounts - this does not work (same error as for existing ones), the pipeline fails.

Resource gets marked tainted, a re-run will cause the (created!) AWS Account to be suspended, and another Account will be created.

This then also fails, because the eMail to create the account (`local.account_tags.account_email` above) is already in use.


Hope that helps

**Comment by ewbankkit** [comment]
It looks like this was caused by https://github.com/hashicorp/terraform-provider-aws/pull/24447.

**Comment by AjkayAlan** [comment]
Seeing the same problem with our account creation process.

Terraform: 1.1.x
AWS Provider: v4.15.0

**Comment by srgustafson8** [comment]
We added a `!= 4.15.0` pin to our provider version definition and that seems to be a valid workaround currently

**Comment by rssnyder** [comment]
FWIW I was able to rescue an account that was in limbo after encountering this issue on creation by removing it from state, rolling back to `< 4.15.0`, then importing it:

```
terraform state rm <resource path>
terraform import <resource path> <account id>
```

**Comment by zuBux** [comment]
I can confirm the above behavior as well

Terraform: 1.1.x
AWS Provider: v4.15.0

**Comment by xmj** [comment]
Thanks everyone 🥳
