### ISSUE TITLE
The terraform-provider-logicmonitor_v2.0.1.exe plugin crashed!

### ISSUE THREAD

**Issue by PatriQ1414** [hashicorp/terraform-provider-aws#24904]
This ran successfully when I was testing it with a few lines of code, but as soon as I started customizing the code, using "for_each" statements, the plugin would just crash

`│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with data.logicmonitor_data_resource_aws_external_id.my_external_id,
│   on LM_demo.tf line 28, in data "logicmonitor_data_resource_aws_external_id" "my_external_id":
│   28: data "logicmonitor_data_resource_aws_external_id" "my_external_id" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-logicmonitor_v2.0.1.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7110ec]

goroutine 47 [running]:
terraform-provider-logicmonitor/client/device_group.(*GetDeviceGroupByIDOK).GetPayload(...)
        terraform-provider-logicmonitor/client/device_group/get_device_group_by_id_responses.go:61
terraform-provider-logicmonitor/logicmonitor/resources.getDeviceGroupById(0xaf40cc, 0x124044c0, 0x1246e780, 0x92ada0, 0x121fa6a0, 0x124044c0, 0x122836b8, 0x19bafc)
        terraform-provider-logicmonitor/logicmonitor/resources/device_group_resource.go:128 +0x2ac
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x124b75e0, 0xaf408c, 0x1209c1a0, 0x1246e780, 0x92ada0, 0x121fa6a0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:347 +0x11f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x124b75e0, 0xaf408c, 0x1209c1a0, 0x12404100, 0x92ada0, 0x121fa6a0, 0x122836a8, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:624 +0x158
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1226aa70, 0xaf408c, 0x1209c1a0, 0x1209c1e0, 0x1209c1a0, 0x199726, 0x9a2640)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:575 +0x352
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0x124020d8, 0xaf40ec, 0x1209c1a0, 0x1266e1b0, 0x124020d8, 0x12559401, 0x126701e0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0xd4
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x9c0e80, 0x124020d8, 0xaf40ec, 0x126701e0, 0x1266e180, 0x0, 0xaf40ec, 0x126701e0, 0x12559400, 0x4b6)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x199
google.golang.org/grpc.(*Server).processUnaryRPC(0x1210c120, 0xaf8d34, 0x12134100, 0x125d8090, 0x124020f0, 0xf4bda8, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x4ea
google.golang.org/grpc.(*Server).handleStream(0x1210c120, 0xaf8d34, 0x12134100, 0x125d8090, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xa71
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x12400110, 0x1210c120, 0xaf8d34, 0x12134100, 0x125d8090)
        google.golang.org/grpc@v1.32.0/server.go:859 +0x92
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1b0

Error: The terraform-provider-logicmonitor_v2.0.1.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
![lm_plugin](https://user-images.githubusercontent.com/84413633/169570043-9366d020-dfc9-4d2d-93ca-92826ebfcc68.PNG)
`

**Comment by justinretzolk** [comment]
Hey @PatriQ1414 👋 It looks like this crash is related to the logicmonitor Terraform provider, rather than the AWS Provider. In order to best address the issue, you'll need to open an issue in the [repository for terraform-provider-logicmonitor](https://github.com/logicmonitor/terraform-provider-logicmonitor).

Since this isn't an issue with the AWS Provider, we'll close this issue. If you feel we've done this in error, please do let us know.

**Comment by PatriQ1414** [comment]
Thanks
