### ISSUE TITLE
Flaky bug: error waiting for DynamoDB PITR update: unexpected state 'DISABLED', wanted target 'ENABLED'

### ISSUE THREAD

**Issue by Veetaha** [hashicorp/terraform-provider-aws#24903]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

- terraform CLI: `v1.1.7`
- AWS provider: `v4.8.0`

### Affected Resource(s)

* aws_dynamodb_table

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

<details>
<summary>Terraform code (under spoiler due to size)</summary>

```hcl
resource "aws_dynamodb_table" "this" {
  name         = "elastio-vaults'
  billing_mode = "PAY_PER_REQUEST"

  point_in_time_recovery {
    enabled = true
  }

  tags = {
      "elastio:resource": "true"	
  }

  hash_key  = "pk"
  range_key = "sk"

  attribute {
    name = "pk"
    type = "S"
  }

  attribute {
    name = "sk"
    type = "S"
  }

  attribute {
    name = "gsi1_pk"
    type = "S"
  }

  attribute {
    name = "gsi1_sk"
    type = "S"
  }

  attribute {
    name = "gsi2_pk"
    type = "S"
  }

  attribute {
    name = "gsi2_sk"
    type = "S"
  }

  attribute {
    name = "gsi3_pk"
    type = "S"
  }

  attribute {
    name = "gsi3_sk"
    type = "S"
  }

  attribute {
    name = "gsi4_pk"
    type = "S"
  }

  attribute {
    name = "gsi4_sk"
    type = "S"
  }

  attribute {
    name = "gsi5_pk"
    type = "S"
  }

  attribute {
    name = "gsi5_sk"
    type = "S"
  }

  global_secondary_index {
    name            = "gsi1"
    hash_key        = "gsi1_pk"
    range_key       = "gsi1_sk"
    projection_type = "ALL"
  }

  global_secondary_index {
    name            = "gsi2"
    hash_key        = "gsi2_pk"
    range_key       = "gsi2_sk"
    projection_type = "ALL"
  }

  global_secondary_index {
    name            = "gsi3"
    hash_key        = "gsi3_pk"
    range_key       = "gsi3_sk"
    projection_type = "ALL"
  }

  global_secondary_index {
    name            = "gsi4"
    hash_key        = "gsi4_pk"
    range_key       = "gsi4_sk"
    projection_type = "ALL"
  }

  global_secondary_index {
    name            = "gsi5"
    hash_key        = "gsi5_pk"
    range_key       = "gsi5_sk"
    projection_type = "ALL"
  }
}
```

</details>

### Debug Output

Unfortunately, there aren't logs with `TF_LOG=debug` available. This bug reproduced only once our CI, where we don't have verbose debug logging enabled because it produces too much output...

The stderr of `terraform apply` :

```
 ╷
  │ Error: error enabling DynamoDB Table (elastio-exp-1653068446-rvolxt-catalog-vaults) point in time recovery: error waiting for DynamoDB PITR update: unexpected state 'DISABLED', wanted target 'ENABLED'. last error: %!s(<nil>)
  │ 
  │   with module.catalog_region.aws_dynamodb_table.this,
  │   on ../../../modules/catalog/region/dynamodb_table.tf line 4, in resource "aws_dynamodb_table" "this":
  │    4: resource "aws_dynamodb_table" "this" {
  │ 
  ╵
```

### Expected Behavior

The table should've been deployed without any problems

### Actual Behavior

We run a lot of deployments with terraform on our CI every day, and see a lot of flakiness like this.
However, we enable PITR only in release builds which occur roughly every two weeks.
In this case, it is an error deploying the DynamoDB table, and it reproduced only once.

### Steps to Reproduce

The deployment is clean (it a non-incremental `apply`).

1. `terraform apply`

**Comment by xnick123** [comment]
I have the problem too, just started in the past 1-3 weeks. It's annoying because pipeline stops and when i try to rerun plan+apply, Creating Amazon DynamoDB Table (xxxxxx): ResourceInUseException: Table already exists

**Comment by YakDriver** [comment]
Related #26552 
Related #28814
