### ISSUE TITLE
ASG create fail: ValidationError: valid fully-formed launch template Invalid IAM Instance Profile ARN

### ISSUE THREAD

**Issue by riddhi89** [hashicorp/terraform-provider-aws#24910]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Error:

```
Error: updating Auto Scaling Group (xyz): ValidationError: You must use a valid fully-formed launch template. Value (arn:aws:iam::012345678901:instance-profile/node-xyz) for parameter iamInstanceProfile.arn is invalid. Invalid IAM Instance Profile ARN
```

### Terraform CLI and Terraform AWS Provider Version
Terraform version: 0.12.23
Terraform AWS Provider Version: [v2.70.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v2.70.0)

### Affected Resource(s)

aws_iam_instance_profile
aws_launch_template
aws_autoscaling_group

### Repeat of an earlier reported issue
Similar Terraform configuration, behavior and error as reported in https://github.com/hashicorp/terraform-provider-aws/issues/5217

The issue was fixed in 1.34.0 (https://github.com/hashicorp/terraform-provider-aws/pull/5633)

Could we consider bumping the propagation timeout to mitigate this further? https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/autoscaling/consts.go#L10

**Comment by justinretzolk** [comment]
Hey @riddhi89 👋 Thank you for taking the time to raise this! I noticed you mentioned you're using AWS Provider version `2.70.0`. In that version of the provider, [the timeout was still `1 * time.Minute`](https://github.com/hashicorp/terraform-provider-aws/blob/2f23a59662cc53a1c9403517dc1312d2846b5434/aws/resource_aws_autoscaling_group.go#L635), however, in subsequent versions, it uses `2 * time.Minute`, as seen in the link you provided to the `propagationTimeout` constant. This change happened in AWS Provider version `3.35.0` with https://github.com/hashicorp/terraform-provider-aws/pull/17811. Can you upgrade to a later version that has this change and see if that improves the behavior?

**Comment by stevehipwell** [comment]
This is still an issue (or has regressed) in `v4.56.0`.

**Comment by arianvp** [comment]
This is still an issue in `5.1.0`:

```
updating Auto Scaling Group (hub-asg-example): ValidationError: You must use a valid fully-formed launch template. Value (arn:aws:iam::0000000000:instance-profile/instance_hub-asg-example) for parameter iamInstanceProfile.arn is invalid. Invalid IAM Instance Profile ARN
```

**Comment by arianvp** [comment]
Reproducer that doesn't work:

```hcl
data "aws_iam_policy_document" "assume" {
    statement {
        actions = [ "sts:AssumeRole" ]
        principals {
            type = "Service"
            identifiers = [ "ec2.amazonaws.com" ]
        }
    }
}

resource "aws_iam_role" "this" {
    name = "my-role"
    assume_role_policy = data.aws_iam_policy_document.assume.json
}

resource "aws_iam_instance_profile" "this" {
    name = "my-instance-profile"
    role = aws_iam_role.this.name
}

resource "aws_launch_template" "this" {
    name = "my-launch-template"
    image_id = "ami-0ff8a91507f77f867"
    instance_type = "t2.micro"
    iam_instance_profile { name = aws_iam_instance_profile.this.name }
}

resource "aws_autoscaling_group" "this" {
    name = "my-autoscaling-group"
    min_size = 1
    max_size = 1
    desired_capacity = 1
    launch_template { id = aws_launch_template.this.id }
    vpc_zone_identifier = [ "subnet-12345678" ]
}
```


The equivalent Amazon CDK works fine and is able to create the auto scaling group fine:

```ts
    const vpc = new ec2.Vpc(this, "Vpc")
    new autoscaling.AutoScalingGroup(this, "AutoScalingGroup", {
      vpc,
      launchTemplate: new ec2.LaunchTemplate(this, "LaunchTemplate", {
        machineImage: new ec2.AmazonLinuxImage(),
        instanceType: new ec2.InstanceType("t2.micro"),
        instanceProfile: new iam.InstanceProfile(this, "InstanceProfile"),
      }),
    })
```

**Comment by stevehipwell** [comment]
@justinretzolk 👀
