### ISSUE TITLE
r/aws_dms_endpoint: Secrets manager secret for aws_dms_endpoint with engine_name = 'redshift' 

### ISSUE THREAD

**Issue by adamlarsonlee** [hashicorp/terraform-provider-aws#24911]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Use of secret manager secrets for aws_dms_endpoint configuration is better practice than entering credentials into tf. Currently there is only support for oracle and postgres endpoints. I would like to add support for Redshift.

### New or Affected Resource(s)

* aws_dms_endpoint with engine_name = 'redshift'

```hcl
resource "aws_dms_endpoint" "aurora-with-secrets" {
  endpoint_id                     = "some-id"
  endpoint_type                   = "target"
  engine_name                     = "redshift"
  secrets_manager_access_role_arn = aws_iam_role.some.arn
  secrets_manager_arn             = aws_secretsmanager_secret.some.id
}
```

### References

* #24845
* #23463)
* #22405

**Comment by daftkid** [comment]
Hi, I will take a look
