### ISSUE TITLE
Creating data block which can access all resources using certain tag

### ISSUE THREAD

**Issue by krishnaduttPanchagnula** [hashicorp/terraform-provider-aws#24928]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

lets say that we have different resources like RDS, some EC2 an EKS in a single account with one of two tags, Dev or Prod. I Would like to get the arns and names of all resources with Dev tag.

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @krishnaduttPanchagnula 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you add a bit more details in the description? For example, are you looking to just get a list of all resources that are using the specified tag, or are you looking for more detail, such as ARNs, etc.?

**Comment by krishnaduttPanchagnula** [comment]
@justinretzolk lets say that we have different resources like RDS, some EC2 an EKS in a single account with one of two tags, Dev or Prod. I Would like to get the arns and names of all resources with Dev tag.
