### ISSUE TITLE
db_instance_role_association IAM eventual consistency

### ISSUE THREAD

**Issue by williamlord-wise** [hashicorp/terraform-provider-aws#24963]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.12.1
```

### Affected Resource(s)

* db_instance_role_association
* rds_cluster_role_association

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_iam_role" "example" {
  name = "example"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Sid    = ""
        Principal = {
          Service = "rds.amazonaws.com"
        }
      },
    ]
  })
}

resource "aws_db_instance" "example" {
  allocated_storage    = 10
  engine               = "mysql"
  engine_version       = "5.7"
  instance_class       = "db.t3.micro"
  name                 = "mydb"
  username             = "foo"
  password             = "foobarbaz"
  parameter_group_name = "default.mysql5.7"
  skip_final_snapshot  = true
}

resource "aws_db_instance_role_association" "example" {
  db_instance_identifier = aws_db_instance.example.id
  feature_name           = "S3_INTEGRATION"
  role_arn               = aws_iam_role.example.arn
}
```

### Debug Output

https://gist.githubusercontent.com/williamlord-wise/74fcc0f2f88a647f6ff63da85246f9da/raw/d4b6c88848fcf6aa1f7f6562e86dd882c23e66d2/terraform-provider-aws-db-instance-role-association-debug

### Expected Behavior

Role should be associated with the DB instance.

### Actual Behavior

```
Error: error associating RDS DB Instance (example) IAM Role (arn:aws:iam::example:role/example): InvalidParameterValue: IAM role ARN value is invalid or does not include the required permissions for: AWS_ROLE_INTEGRATION
```

The IAM service is eventually consistent and the resource only tries to associate the role once https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/rds/instance_role_association.go#L69.

Solution looks to be to add retry functionality to the resource, similar to other resources that use eventually consistent APIs, eg. https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/accessanalyzer/analyzer.go#L85 (Organization API).

### Steps to Reproduce

1. IAM role and and DB instance association both to be created
2. `terraform apply`

### References

* Similar to https://github.com/hashicorp/terraform-provider-aws/issues/7646 or any other eventual consistency issue with IAM service

**Comment by davorceman** [comment]
I have the same error.

```
Error: error associating RDS DB Instance (example) IAM Role (arn:aws:iam::123456789:role/example-s3-integration): InvalidParameterValue: IAM role ARN value is invalid or does not include the required permissions for: AWS_ROLE_INTEGRATION
        status code: 400, request id: 42f2473b-ee9a-4a78-b242-50356c4909f8
```

I was able to associate manually the same role via AWS Console, and then to import that association to my terraform state.
But again when I tried to redeploy my stack I'm getting the same error.

My policies are
```
data "aws_iam_policy_document" "s3_integration_assume" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]
    principals {
      type = "Service"
      identifiers = [
        "rds.amazonaws.com"
      ]
    }
    condition {
      test     = "StringEquals"
      variable = "aws:SourceAccount"
      values = [
        data.aws_caller_identity.current.id
      ]
    }
    condition {
      test = "StringEquals"

      variable = "aws:SourceArn"
      values = [
        aws_db_instance.rds.arn
      ]
    }
  }
}

data "aws_iam_policy_document" "s3_integration" {
  statement {
    effect = "Allow"
    actions = [
      "s3:GetObject",
      "s3:ListBucket",
      "s3:PutObject"
    ]
    resources = [
      aws_s3_bucket.s3_integration.arn,
      format("%s/*", aws_s3_bucket.s3_integration.arn)
    ]
  }
}

resource "aws_iam_role_policy" "s3_integration" {
  name   = format("%s-s3-integration", var.name)
  role   = aws_iam_role.s3_integration.id
  policy = data.aws_iam_policy_document.s3_integration.json
}

resource "aws_iam_role" "s3_integration" {
  name                 = format("%s-s3-integration", var.name)
  assume_role_policy   = data.aws_iam_policy_document.s3_integration_assume.json
  permissions_boundary = data.aws_iam_policy.iam_permission_boundary.arn

}

resource "aws_db_instance_role_association" "s3_integration" {
  db_instance_identifier = aws_db_instance.rds.id
  feature_name           = "S3_INTEGRATION"
  role_arn               = aws_iam_role.s3_integration.arn
}
```

```
terraform --version
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/aws v3.74.2
```
