### ISSUE TITLE
[Latest]TransferSecurityPolicy-2022-03 policy is not available for security_policy_name in aws_transfer_server Resource

### ISSUE THREAD

**Issue by jadhavswapnil71** [hashicorp/terraform-provider-aws#24967]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- aws_transfer_server 

input variable  "security_policy_name" does not have provision to assign latest **TransferSecurityPolicy-2022-03** security policy via terraform .
<img width="685" alt="Screenshot 2022-05-24 at 5 59 07 PM" src="https://user-images.githubusercontent.com/46022137/170034924-e67bffa1-363f-4f8d-b3ef-235b565ebd11.png">

Currently on AWS Console  UI interface has the option to select from drop down  **TransferSecurityPolicy-2022-03** security policy  under transfer service.
<img width="804" alt="Screenshot 2022-05-24 at 6 00 38 PM" src="https://user-images.githubusercontent.com/46022137/170035113-95d46897-811a-4f21-b471-b9ae846b0a98.png">

### References

- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_server

**Comment by meetreks** [comment]
PR out for review and merge. Watch this space!
