### ISSUE TITLE
aws_backup_plan - Invalid lifecycle. DeleteAfterDays cannot be less than 1 or more than 36500 days

### ISSUE THREAD

**Issue by chary1112004** [hashicorp/terraform-provider-aws#24960]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_backup_plan

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
module "aws_backup_example" {

  source = "lgallard/backup/aws"

  # Vault
  vault_name = "vault-3"

  # Plan
  plan_name = "complete-plan"

  # Multiple rules using a list of maps
  rules = [
    {
      name                     = "weekly"
      schedule                 = "cron(0 22 ? * 7 *)"
      target_vault_name        = null
      start_window             = 120
      completion_window        = 360
      enable_continuous_backup = true
      lifecycle = {
        cold_storage_after = 0
        delete_after       = 84
      }
    }
  ]

  # Multiple selections
  #  - Selection-1: By resources and tag
  #  - Selection-2: Only by resources
  #  - Selection-3: By resources and conditions
  selections = [
    {
      name          = "selection-3"
      resources     = ["*"]
      not_resources = []
      conditions = {
        string_equals = [
          {
            key   = "aws:ResourceTag/Component"
            value = "rds"
          }
        ,
          {
            key   = "aws:ResourceTag/Project"
            value = "Project1"
          }
        ]
        string_like = [
          {
            key   = "aws:ResourceTag/Application"
            value = "app*"
          }
        ]
        string_not_equals = [
          {
            key   = "aws:ResourceTag/Backup"
            value = "false"
          }
        ]
        string_not_like = [
          {
            key   = "aws:ResourceTag/Environment"
            value = "test*"
          }
        ]
      }
    }
  ]

  tags = {
    Owner       = "backup team"
    Environment = "production"
    Terraform   = true
  }
}
```

### Expected Behavior

I create aws backup plan with daily, weekly.
- For backup daily and retention after 1 day then it is success
- For backup weekly and retention after 12 weeks (84 days) then it is fail. So with the information from error then valid DeleteAfterDays range day in in [1, 36500] days so 84 days should be in valid DeleteAfterDays range day. Then rule should be created without error.

### Actual Behavior

```hcl
Error: error updating Backup Plan (5c560302-ed39-45a4-9e26-b35f8bcb1180): InvalidParameterValueException: Error in rule weekly : Invalid lifecycle. DeleteAfterDays cannot be less than 1 or more than 36500 days.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "388631ef-c2ff-4f99-ae7c-1b89dbe7cf1a"
  },
  Code_: "ERROR_3015",
  Context: "[\"weekly\",\"Invalid lifecycle. DeleteAfterDays cannot be less than 1 or more than 36500 days.\"]",
  Message_: "Error in rule weekly : Invalid lifecycle. DeleteAfterDays cannot be less than 1 or more than 36500 days."
}
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by chary1112004** [comment]
Hi @justinretzolk ,

thank you for feedback. I have tried to increase to 90 days as you suggest. However it is still same error as below:

$ terraform plan

![image](https://user-images.githubusercontent.com/76929085/170208214-360ffb20-8d28-47f7-b5d9-988059db94d3.png)

$ terraform apply

![image](https://user-images.githubusercontent.com/76929085/170208098-216305c6-bc10-423a-915b-2db62c4d1b7d.png)

**Comment by chary1112004** [comment]
Hi @justinretzolk ,

when I am trying to work around by run terraform first and after manual modify it in aws management console. Then I recognize that I have enabled continuous backup then it is only allowed the range between 1 and 35 days.

![image](https://user-images.githubusercontent.com/76929085/170247866-a213bbb3-cc80-457b-9f2a-f2323d25a79a.png)

After I set enable_continuous_backup = false then it works as expect.

However I think the output message from terraform provider should be corrected.

Thanks,
Uyen Vu

**Comment by justinretzolk** [comment]
Hey @chary1112004 👋 I'm glad you were able to get past this, and really appreciate you following up! Unfortunately, that error message is coming from the AWS API, rather than from the provider, so I'm not sure that we'd be able to fix it at the provider level. If it was returning a more specific error code, we'd be able to handle it differently, but all that's returned in this case is a `InvalidParameterValueException`.

Since you've sorted out the issue, and we're limited in how we could mitigate this, I'll close this issue out. If you feel I've done this in error, please do let me know.

**Comment by chary1112004** [comment]
Hi @justinretzolk,

thank you. Yes, we could close this ticket!
