### ISSUE TITLE
Implement IoT policy version pruning

### ISSUE THREAD

**Issue by Octogonapus** [hashicorp/terraform-provider-aws#24979]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The original plan for IoT support included a policy prune during each update to `aws_iot_policy` (see https://github.com/hashicorp/terraform-provider-aws/issues/143).
This is necessary to ensure the update succeeds, as each update creates a new policy version and a given policy cannot have more than five versions.
This feature request is to implement this pruning as originally planned.

Without this feature, after you have iterated on the same policy more than five times, you will get this error:
```
aws_iot_policy.foo: Modifying... [id=foo]
╷
│ Error: error updating IoT Policy (foo): VersionsLimitExceededException: The policy foo already has the maximum number of versions (5)
│ 
│   with aws_iot_policy.foo,
│   on main.tf line 13, in resource "aws_iot_policy" "foo":
│   13: resource "aws_iot_policy" "foo" {
│ 
╵
```

### New or Affected Resource(s)

* aws_iot_policy

### Potential Terraform Configuration

```hcl
resource "aws_iot_policy" "pubsub" {
  name = "PubSubToAnyTopic"
  policy = <<EOF
{
  "Version": "2012-10-17", 
  "Statement": [{
    "Effect": "Allow",
    "Action": ["iot:*"],
    "Resource": ["*"]
  }]
}
EOF
}
```

### References

* #143

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/9540.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/30314.
