### ISSUE TITLE
Terraform is changing the rule order of aws network firewall rules

### ISSUE THREAD

**Issue by sharatotapally** [hashicorp/terraform-provider-aws#24977]
We are using Terraform to manage AWS Network Firewall's stateful rules. However, Terraform is changing the rule order when passing it to AWS.

**TF repo**

```hcl
resource "aws_networkfirewall_rule_group" "cross-environment-rulegroup" {
  type  = "STATEFUL"
  name        = "cross-environment-rulegroup"
  capacity    = 5000
  rule_group {
    stateful_rule_options {
        rule_order = "STRICT_ORDER"
    }
    rule_variables {
          dynamic "ip_sets" {
            for_each = merge(var.ip_sets,local.local_ip_sets)
            content {
              key = ip_sets.key
              ip_set {
                definition = ip_sets.value
              }
            }
          }
          dynamic "port_sets" {
            for_each = var.port_sets
            content {
              key = port_sets.key
              port_set {
                definition = port_sets.value
              }
            }
          }
    }
    rules_source {
      dynamic "stateful_rule" {
        for_each = var.cross_environment_rules
        content {
          action = stateful_rule.value.action
          header {
            destination      = stateful_rule.value.destination
            destination_port = stateful_rule.value.destination_port
            direction        = stateful_rule.value.direction
            protocol         = stateful_rule.value.protocol
            source           = stateful_rule.value.source
            source_port      = stateful_rule.value.source_port
          }
          rule_option {
            keyword = "sid"
            settings = [
              (stateful_rule.key) + 1
            ]
          }
          rule_option {
            keyword = "msg"
            settings = [
              (stateful_rule.value.msg)
            ]
          }
        }
      }
    }
  }
  lifecycle {
    create_before_destroy = true
  }
```

**TFVARS**

```hcl
cross_environment_rules": [
      {
         "action":"PASS",
         "destination":"$PRODWEST,$PRODEAST",
         "destination_port":"$WEB",
         "direction":"FORWARD",
         "protocol":"IP",
         "source":"$PRODEAST",
         "source_port":"ANY",
         "msg" : "\"TEST rule. To be deleted\""
      },
      {
         "action":"PASS",
         "destination":"10.0.0.0/8",
         "destination_port":"ANY",
         "direction":"FORWARD",
         "protocol":"ICMP",
         "source":"10.0.0.0/8",
         "source_port":"ANY",
         "msg" : "\"allow-icmp\""
      },
      {
         "action":"PASS",
         "destination":"10.0.0.0/8",
         "destination_port":"$HTTPS",
         "direction":"FORWARD",
         "protocol":"TCP",
         "source":"$SKI_PROD",
         "source_port":"ANY",
         "msg" : "\"allow traffic from ski_prod to port 443. Need to limit destination\""
      },
      {
         "action":"PASS",
         "destination":"10.1.0.0/16",
         "destination_port":"$HTTPS",
         "direction":"FORWARD",
         "protocol":"TCP",
         "source":"$SKI_PROD",
         "source_port":"ANY",
         "msg" : "\"allow traffic from ski_prod to port 443. Need to limit destination\""
      }
   ]
}
```

Actual rule order:

![after-change](https://user-images.githubusercontent.com/94722650/170103116-dea3b405-f095-4f1f-ad8a-4671e465fba2.png)

**Comment by sharatotapally** [comment]
hi @teamterraform I would like to get an update on this issue. It's been more than a week since the issue was created.

**Comment by thenoid** [comment]
This just bit us as well.

**Comment by smcglincy** [comment]
This affected us too...
Had to use firewall groups to work around the bug.

**Comment by haytemEffectual** [comment]
this has been a pain now for us as well, is there any update on this ?

**Comment by haytemEffectual** [comment]
I was able to work around this through Suricata rules, by entering the rules in the Suricata format with the order with the required order:

resource "aws_networkfirewall_rule_group" "firewall-rule-group" {
  capacity = 10
  name     = "my-Rule-Group"
  type     = "STATEFUL"

  rule_group {
      stateful_rule_options {
        rule_order = "STRICT_ORDER"
      }
      rule_variables {
        ip_sets {
          key = "WEBSERVERS_HOSTS"
          ip_set {
            definition = ["${data.aws_subnet.firewallsubnet.cidr_block}","${data.aws_subnet.subnet1ID.cidr_block}"]
          }
        }
        ip_sets {
          key = "PREEXISTING_ENV"
          ip_set {
            definition = ["10.10.10.10/32","10.10.10.20/32","10.10.10.30/32"]
          }
        }
      }

    rules_source {
       rules_string = <<EOF
       pass ip 10.0.0.0/8 any -> any any (sid:10;)
       pass ip any any -> $PREEXISTING_ENV any (sid:20;)
       pass ip any any -> $WEBSERVERS_HOSTS any (sid:30;)
       drop ip any any -> any any (sid:40;)
      EOF

**Comment by tmccombs** [comment]
I think the problem here is that `stateful_rule` is uses `TypeSet` for it's type, which loses the order information.

**Comment by tmccombs** [comment]
Also worth noting this is probably only a problem if you are using STRICT_ORDER.

**Comment by mike-morris-emis** [comment]
would be a good qol fix

**Comment by floryut** [comment]
@tmccombs I've tested your fix and it works fine, care to address the PR CI issue (and change it to ready) to make it in the next release ? or do you want me to create another PR if you don't have the time ?
