### ISSUE TITLE
Conflicting aws_s3_bucket acl config after migrating to v4.15.1

### ISSUE THREAD

**Issue by chelis** [hashicorp/terraform-provider-aws#24976]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.12.31
+ provider.aws v4.15.1

### Affected Resource(s)

* aws_s3_bucket
* aws_s3_bucket_acl

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

#### Initial configuration 
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp


resource "aws_s3_bucket" "b" {
  bucket = "csb-8938b4c0-d67f-4c34-9f68-a66deef99b4d"
  acl    = "public-read"

  versioning {
    enabled = true
  }
}
```
#### Changing to standalone resources
```hcl
resource "aws_s3_bucket" "b" {
  bucket = "csb-8938b4c0-d67f-4c34-9f68-a66deef99b4d"
  tags = {
      pcf-instance-id = "8938b4c0-d67f-4c34-9f68-a66deef99b4e"
  }

}

resource "aws_s3_bucket_acl" "example_bucket_acl" {
  bucket = aws_s3_bucket.b.id
  acl    = "public-read"
}

resource "aws_s3_bucket_versioning" "versioning_example" {
  bucket = aws_s3_bucket.b.id
  versioning_configuration {
    status = "Enabled"
  }
}
```

#### Changing acl
```hcl
resource "aws_s3_bucket" "b" {
  bucket = "csb-8938b4c0-d67f-4c34-9f68-a66deef99b4d"
  tags = {
      pcf-instance-id = "8938b4c0-d67f-4c34-9f68-a66deef99b4e"
  }

}

resource "aws_s3_bucket_acl" "example_bucket_acl" {
  bucket = aws_s3_bucket.b.id
  acl    = "public-read-write"
}

resource "aws_s3_bucket_versioning" "versioning_example" {
  bucket = aws_s3_bucket.b.id
  versioning_configuration {
    status = "Enabled"
  }
}
```

### Debug Output

https://gist.github.com/chelis/8c295e28308cdb53c44eb8173205cd06

### Expected Behavior

`acl` property in the state should be "public-read"

### Actual Behavior

`acl` property for the `aws_s3_bucket` shows as `public-read` in the state file. It does have a new resource created for the standalone acl with the right acl (`public-read-write`), but it is conflicting with the bucket property and it has the wrong grants (AllUsers group only gets READ)

```
"resources": [
    {
      "mode": "managed",
      "type": "aws_s3_bucket",
      "name": "b",
      "provider": "provider.aws",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "acceleration_status": "",
            "acl": "public-read",
....

  {
      "mode": "managed",
      "type": "aws_s3_bucket_acl",
      "name": "example_bucket_acl",
      "provider": "provider.aws",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "access_control_policy": [
              {
                "grant": [
                  {
                    "grantee": [
                      {
                        "display_name": "",
                        "email_address": "",
                        "id": "",
                        "type": "Group",
                        "uri": "http://acs.amazonaws.com/groups/global/AllUsers"
                      }
                    ],
                    "permission": "READ"
                  },
                  {
                    "grantee": [
                      {
                        "display_name": "pcf-services-enablement",
                        "email_address": "",
                        "id": "*****",
                        "type": "CanonicalUser",
                        "uri": ""
                      }
                    ],
                    "permission": "FULL_CONTROL"
                  }
                ],
                "owner": [
                  {
                    "display_name": "pcf-services-enablement",
                    "id": "****"
                  }
                ]
              }
            ],
            "acl": "public-read-write",
````

### Steps to Reproduce

1. `terraform apply` with the initial configuration
2. `terraform apply` with the second configuration that changes to use the standalone resources
3. `terraform apply` with the third configuration updating the acl

This happens when creating and updating the resource with the latest provider version. But also if creating with version 3.75.2 and then upgrading to 4.15.1.
Our scenario is trying to migrate from latest 3.x.x to 4.15.1 and this could turn into a blocker for addressing such migration.

**Comment by justinretzolk** [comment]
Hey @chelis 👋 Thank you for taking the time to raise this! Can you confirm whether the correct ACL is applied to the bucket, despite what's in the state file? I was able to reproduce the state file behavior, but in my reproduction, the bucket _was_ updated as expected.

As far as the mismatch between what's seen for the `grant` values in the `aws_s3_bucket` resource and `aws_s3_bucket_acl` resource, I suspect that what's happening with that is that the refresh/read of the `aws_s3_bucket` resource is happening before the `aws_s3_bucket_acl` resource is able to make the change to the bucket. In my reproduction, after seeing the difference, I ran a `terraform apply -refresh-only` to refresh the state, at which point it reflected the correct values. I'd like to leave that part of the question to one of our maintainers, as they'll likely have a better idea of whether that behavior is to be expected or not, and what change needs to be made, if any.

**Comment by chelis** [comment]
Hi @justinretzolk , I've just tested this and can confirm that the confusing values in the state, the bucket is updated as expected.
