### ISSUE TITLE
Support `disable_api_stop` for EC2 instances.

### ISSUE THREAD

**Issue by samjo-nyang** [hashicorp/terraform-provider-aws#25018]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
https://aws.amazon.com/about-aws/whats-new/2022/05/amazon-ec2-enables-protect-instances-unintentional-stop-actions/

Please support stop protection for EC2 instances!

### New or Affected Resource(s)

* aws_instance

### Potential Terraform Configuration

```hcl
resource "aws_instance" "foo" {
  ami              = "ami-1234567890"
  instance_type    = "t3.micro"
  disable_api_stop = true # added
}
```

### References
- Details: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Stop_Start.html#Using_StopProtection

**Comment by ewbankkit** [comment]
Requires [AWS SDK for Go v1.44.21](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.21): #25023.
