### ISSUE TITLE
aws_ebs_encryption_by_default allow setting of region

### ISSUE THREAD

**Issue by mbassett** [hashicorp/terraform-provider-aws#25021]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Currently with a setup like this

resource "aws_ebs_default_kms_key" "default" {
  key_arn = aws_kms_key.volume_encryption.arn
}

resource "aws_ebs_encryption_by_default" "default" {
  enabled = true
}

EBS encryption is only enabled for whatever region my provider is set to.

It would be nice if we could add a region like:

etc.
### New or Affected Resource(s)

aws_ebs_encryption_by_default.region

* aws_XXXXX

### Potential Terraform Configuration

```hcl

resource "aws_ebs_encryption_by_default" "eu_west" {
  enabled = true
  region = "eu-west-1"
}

resource "aws_ebs_encryption_by_default" "eu_west_2" {
  enabled = true
  region = "eu-west-2"
}

```

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @mbassett 👋 Thank you for taking the time to raise this! The `aws_ebs_encryption_by_default` resource uses the [`ec2.EnableEbsEncryptionByDefault` function](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.EnableEbsEncryptionByDefault), which doesn't accept a `region` argument, as it only affects the current region (the underlying API documentation can be found [here](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_EnableEbsEncryptionByDefault.html), and has a bit of additional information).

That said, by using a [provider `alias`](https://www.terraform.io/language/providers/configuration#alias-multiple-provider-configurations), you can achieve this functionality with no changes to the provider. This would look something like:

```hcl
provider "aws" {
  region = "eu-west-1"
}

provider "aws" {
  alias  = "euw2"
  region = "eu-west-2"
}

resource "aws_ebs_encryption_by_default" "eu-west-1" {
  enabled = true
}

resource "aws_ebs_encryption_by_default" "eu-west-2" {
  provider = aws.euw2
  enabled  = true
}
```

**Comment by mbassett** [comment]
Thanks I will give that a try!

**Comment by mbassett** [comment]
Worked great, thank you!
