### ISSUE TITLE
 Add support for stateful_rule_group_reference override in AWS managed rules

### ISSUE THREAD

**Issue by buzen247** [hashicorp/terraform-provider-aws#25032]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
As a follow up to https://github.com/hashicorp/terraform-provider-aws/pull/22355, kindly add support for Override in the `stateful_rule_group_reference` for aws_networkfirewall_firewall_policy resource.

**Currently supported**
```
resource "aws_networkfirewall_firewall_policy" "example" {
  name = "example"

  firewall_policy {
    stateless_default_actions          = ["aws:pass"]
    stateless_fragment_default_actions = ["aws:drop"]
    stateless_rule_group_reference {
      priority     = 1
      resource_arn = aws_networkfirewall_rule_group.example.arn

    stateful_rule_group_reference {
      priority     = 2
      resource_arn = aws_networkfirewall_rule_group.example.arn
    }
  }`
```

 **feature request**
```
resource "aws_networkfirewall_firewall_policy" "example" {
  name = "example"

  firewall_policy {
    stateless_default_actions          = ["aws:pass"]
    stateless_fragment_default_actions = ["aws:drop"]
    stateless_rule_group_reference {
      priority     = 1
      overrride {
             action = ["DROP_TO_ALERT"]
      }
      resource_arn = aws_networkfirewall_rule_group.example.arn

    stateful_rule_group_reference {
      priority     = 2
      overrride {
             action = ["DROP_TO_ALERT"]
      }
      resource_arn = aws_networkfirewall_rule_group.example.arn
    }
  }`
```

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/network-firewall.html
        'StatefulRuleGroupReferences': [
            {
                'ResourceArn': 'string',
                'Priority': 123,
                'Override': {
                    'Action': 'DROP_TO_ALERT'
                }
            },
        ],
```

### References

* #0000

**Comment by teddylear** [comment]
@justinretzolk Hey! I can try to take a look into this

**Comment by teddylear** [comment]
@buzen247 Looking into this more, I can only do this for [StatefulRuleGroupReferences](https://docs.aws.amazon.com/sdk-for-go/api/service/networkfirewall/#StatefulRuleGroupReference) and not [StatelessRuleGroupReferences](https://docs.aws.amazon.com/sdk-for-go/api/service/networkfirewall/#StatelessRuleGroupReference) as Stateless Rules Groups do not have an override field like the stateful ones do (at least on the aws sdk for golang). 

Also I'm leaning towards going with something like this because it appears there can only be one override actin per policy: 
```terraform

resource "aws_networkfirewall_firewall_policy" "example" {
  name = "example"

  firewall_policy {
    stateless_default_actions          = ["aws:pass"]
    stateless_fragment_default_actions = ["aws:drop"]

    stateful_rule_group_reference {
      priority     = 1
      overrride_action = "DROP_TO_ALERT"
      resource_arn = aws_networkfirewall_rule_group.example.arn
    }
}
```

**Comment by teddylear** [comment]
@justinretzolk Opened a PR for this, pleas let me know if I'm missing anything or anything else I should update.

**Comment by buzen247** [comment]
> @buzen247 Looking into this more, I can only do this for [StatefulRuleGroupReferences](https://docs.aws.amazon.com/sdk-for-go/api/service/networkfirewall/#StatefulRuleGroupReference) and not [StatelessRuleGroupReferences](https://docs.aws.amazon.com/sdk-for-go/api/service/networkfirewall/#StatelessRuleGroupReference) as Stateless Rules Groups do not have an override field like the stateful ones do (at least on the aws sdk for golang).
> 
> Also I'm leaning towards going with something like this because it appears there can only be one override actin per policy:
> 
> ```terraform
> resource "aws_networkfirewall_firewall_policy" "example" {
>   name = "example"
> 
>   firewall_policy {
>     stateless_default_actions          = ["aws:pass"]
>     stateless_fragment_default_actions = ["aws:drop"]
> 
>     stateful_rule_group_reference {
>       priority     = 1
>       overrride_action = "DROP_TO_ALERT"
>       resource_arn = aws_networkfirewall_rule_group.example.arn
>     }
> }
> ```
Thats all that is needed for this, stateless managed rules are not supported (yet). Thanks

**Comment by praddc** [comment]
Hi @justinretzolk, just wondering if you could take a look at this to see if we can merge it, or need changes. This is a bit of a blocker for us, as we can't put any of the firewall resources in TF since without the override it will change our setup once we import it into the state. Thanks!

**Comment by justinretzolk** [comment]
Hey @praddc  👋 Thank you for checking in on this! Unfortunately, I'm not able to provide an estimate on when this will be merged/reviewed due to the potential of shifting priorities (we prioritize work by count of ":+1:" reactions, as well as a few other things). For more information on how we prioritize, check out out [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/).
