### ISSUE TITLE
Update Directory Services Resource to Configure Number of Domain Controllers

### ISSUE THREAD

**Issue by kclinden** [hashicorp/terraform-provider-aws#25050]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It is not possible to configure a Directory Service to use more than two domain controllers today. The go SDK supports this via UpdateNumberOfDomainControllers.

### New or Affected Resource(s)

* aws_directory_service_directory

### Potential Terraform Configuration

```hcl
# Create AWS Domain Service - Managed Active Directory
resource "aws_directory_service_directory" "directory" {
  name        = var.directory_name
  description = "AWS Managed Active Directory for UEM"
  password    = jsondecode(data.aws_secretsmanager_secret_version.password.secret_string)[var.sm_secret_key]
  edition     = "Standard"
  type        = "MicrosoftAD"
  DomainControllerCount = 3 #update to desired count

  vpc_settings {
    vpc_id     = var.management_vpc_id
    subnet_ids = var.management_private_subnet_ids
  }
}
```

### References

* https://docs.aws.amazon.com/sdk-for-go/api/service/directoryservice/#DirectoryService.UpdateNumberOfDomainControllers

**Comment by teddylear** [comment]
I can take a look into this if that's alright

**Comment by teddylear** [comment]
@justinretzolk Ok this should be ready for review, please let me know if there's anything else I should change.
