### ISSUE TITLE
Add root_block_device property to launch_template

### ISSUE THREAD

**Issue by paololazzari** [hashicorp/terraform-provider-aws#25068]
The [EC2 launch template](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template) does not have a `root_block_device` property. Why is that?

**Comment by justinretzolk** [comment]
Hey @paololazzari 👋 Thank you for taking the time to raise this! The `aws_launch_template` resource [uses `ec2.CreateLaunchTemplate()`](https://github.com/hashicorp/terraform-provider-aws/blob/e70faae038841b83dc077de02ab7a07bb7c6726e/internal/service/ec2/ec2_launch_template.go#L969) to create the launch template in AWS. This function takes a [type `CreateLaunchTemplateInput`](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#CreateLaunchTemplateInput), which ultimately takes the launch template data in its `LaunchTemplateData` field. This field is of [type `RequestLaunchTemplateData`](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#RequestLaunchTemplateData), which is where the majority of the arguments passed to the `aws_launch_template` resource wind up. This type does not have a `RootBlockDevice` (or similar) field, so the provider is unable to have that as an argument. Instead, it has a `BlockDeviceMappings` field, which the provider exposes as the `block_device_mappings` argument.

With that said, you can adjust the root block device by specifying a `block_device_mappings.device_name` that matches the root block device name as found by using [`ec2 describe-images`](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-images.html) and inspecting the `RootDeviceName`, or by using the [`aws_ami` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami) and using the `root_device_name` attribute.
