### ISSUE TITLE
destroy order - aws_iam_user & aws_iam_policy_attachment

### ISSUE THREAD

**Issue by brunobritodev** [hashicorp/terraform-provider-aws#25074]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
terraform -v
Terraform v1.1.2
+ provider registry.terraform.io/hashicorp/aws v4.15.1
```
### Affected Resource(s)

* aws_iam_policy_attachment
* aws_iam_user

### Terraform Configuration Files

```hcl
resource "aws_iam_user" "powerusers" {
  for_each = toset(["user_a", "user_b"])
  name     = each.key
}

resource "aws_iam_policy_attachment" "powerusers" {
  name       = "iam-codebuild-powerusers"
  users      = keys({ for k, v in aws_iam_user.powerusers : k => v })
  policy_arn = "arn:aws:iam::aws:policy/AWSCodeCommitPowerUser"
}
```

### Expected Behavior

1. Remove policy attachment
2. Remove user

### Actual Behavior

1. Remove user
2. Remove policy attachment

It must remove policy attachment first, then remove user. Actually it tries to remove user first.

```sh
aws_iam_user.powerusers["user_b"]: Destroying... [id=user_b]
Error: Error deleting IAM User user_b: DeleteConflict: Cannot delete entity, must detach all policies first.
       status code: 409, request id: ....
```

### Steps to Reproduce

1. `terraform apply`
4. Remove `user_b` from list
5. `terraform apply`

**Comment by justinretzolk** [comment]
Hey @brunohbrito 👋 I looked into this a bit and came across [this helpful comment](https://github.com/hashicorp/terraform-provider-aws/issues/5417#issuecomment-509499061) that gave a breakdown on why this happens and how to get around it. Can you take a look over that and let me know if it helps you get past this issue?

**Comment by brunobritodev** [comment]
@justinretzolk In this case no. Even if we set `force_destroy = true` on `aws_iam_users` the same error happens.

The destroy order here is important. So a workaround is first run a `terraform apply -target=aws_iam_policy_attachment.powerusers`, then `terraform apply`, so the users are removed.
