### ISSUE TITLE
aws_iam_policy_document doesn't support conditions with multiple keys

### ISSUE THREAD

**Issue by fszymanski-blvd** [hashicorp/terraform-provider-aws#25071]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

While working on implementing an IAM policy that limits KMS access to only RDS Performance Insights, I found that the [AWS documentation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights.access-control.html#USER_PerfInsights.access-control.cmk-policy) creates a single `ForAnyValue:StringEquals` condition with multiple keys. According to the IAM documentation on [Creating a condition with multiple keys or values](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_multi-value-conditions.html), `A Condition element can contain multiple conditions, and each condition can contain multiple key-value pairs.`

### New or Affected Resource(s)

* aws_iam_policy_document

### Potential Terraform Configuration

```hcl
data "aws_iam_policy_document" "deny_iam_and_data_read" {
  source_json = local.deny_data_read_json
  statement {
    actions = [
        "kms:Decrypt",
        "kms:GenerateDataKey"
    ]
    resources = "*"
    condition {
      test = "ForAnyValue:StringEquals"
      values = [
         {
            variable = "kms:EncryptionContext:aws:pi:service"
            values = ["rds"]
         },
         {
            variable = "kms:EncryptionContext:service"
            values = ["pi"]
         }
      ]
  }
}
```

### References

* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights.access-control.html#USER_PerfInsights.access-control.cmk-policy
* https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_multi-value-conditions.html

**Comment by justinretzolk** [comment]
Hey @fszymanski-blvd 👋 Thank you for taking the time to raise this! It looks like if you break the `condition` out into two separate `condition` blocks with the same `test` value, you can achieve what you're looking for. To show this, I created the following configuration based on your sample:

```hcl
data "aws_iam_policy_document" "deny_iam_and_data_read" {
  statement {
    actions = [
      "kms:Decrypt",
      "kms:GenerateDataKey"
    ]

    resources = ["*"]

    condition {
      test     = "ForAnyValue:StringEquals"
      variable = "kms:EncryptionContext:service"
      values   = ["pi"]
    }

    condition {
      test     = "ForAnyValue:StringEquals"
      variable = "kms:EncryptionContext:aws:pi:service"
      values   = ["rds"]
    }

  }
}

output "json" {
  value = data.aws_iam_policy_document.deny_iam_and_data_read.json
}
```

Running a `terraform apply` gave me the following output:

```plaintext
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

json = <<EOT
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Action": [
        "kms:GenerateDataKey",
        "kms:Decrypt"
      ],
      "Resource": "*",
      "Condition": {
        "ForAnyValue:StringEquals": {
          "kms:EncryptionContext:aws:pi:service": "rds",
          "kms:EncryptionContext:service": "pi"
        }
      }
    }
  ]
}
```

**Comment by fszymanski-blvd** [comment]
Thanks for the details on this. That is not clear from the documentation that it's possible.

**Comment by justinretzolk** [comment]
Hey @fszymanski-blvd -- Thank you for that feedback! I agree that this wasn't entirely clear from the documentation, so I've opened a pull request to add an additional example to the documentation to illustrate how to do this.
