### ISSUE TITLE
`aws_lb` data source does not find lb, while `aws_elb` data source does

### ISSUE THREAD

**Issue by applike-ss** [hashicorp/terraform-provider-aws#25081]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
terraform `1.1.9`
aws provider `4.15.1`

### Affected Resource(s)

* data source aws_lb

### Expected Behavior
It should find my load balancer by name

### Actual Behavior
It does not find my load balancer by name

It seems terraform aws provider is using the most recent api version and that this version does not find load balancers by name (or under certain conditions?).

I can verify with my aws cli that this works:
`aws elb describe-load-balancers --load-balancer-names my-lb-name`
and this doesn't:
`aws elbv2 describe-load-balancers --names my-lb-name`

### Steps to Reproduce

Use a data source aws_lb to find an (internal) load balancer by name only.
That should fail, but if you now rename aws_lb to aws_elb in your definition it will suddenly work (assuming that that one uses the old api version).

### Important Factoids
We are trying to find an internal load balancers btw.

Executing like this works `Action=DescribeLoadBalancers&LoadBalancerNames.member.1=my-lb-name&Version=2012-06-01`
Executing like this doesn't work `Action=DescribeLoadBalancers&Names.member.1=my-lb-name&Version=2015-12-01`

### References
* https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_DescribeLoadBalancers.html#API_DescribeLoadBalancers_Examples
* https://docs.aws.amazon.com/elasticloadbalancing/2012-06-01/APIReference/API_DescribeLoadBalancers.html#API_DescribeLoadBalancers_Examples

**Comment by justinretzolk** [comment]
Hey @applike-ss 👋 Thank you for taking the time to raise this! You're correct in your assumption that the `aws_lb` and `aws_elb` data sources use different versions under the hood. `aws_lb` [uses `elbv2`](https://github.com/hashicorp/terraform-provider-aws/blob/e70faae038841b83dc077de02ab7a07bb7c6726e/internal/service/elbv2/load_balancer_data_source.go#L9), while `aws_elb` [uses `elb` (v1)](https://github.com/hashicorp/terraform-provider-aws/blob/e70faae038841b83dc077de02ab7a07bb7c6726e/internal/service/elb/load_balancer_data_source.go#L9).

Which data source you use is dependent on the type of load balancer you're looking up. For "classic" load balancers, you'd need to use `aws_elb`, while network and application load balances can be looked up using `aws_lb` (regardless of whether or not they're internal).

**Comment by applike-ss** [comment]
Hi @justinretzolk thanks for pointing this out!

I did take aws_lb as a successor that was merging functionality of managing classic/network/application load balancers - which does not seem to be the case.

Sorry for wasting your time!

Since it is resolved from my end, i would close this issue now.
