### ISSUE TITLE
Support for start session in AWS Systems Manager Session Manager

### ISSUE THREAD

**Issue by sumanayanamandra** [hashicorp/terraform-provider-aws#25110]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of Hashicorp Terraform aws provider version 4.15.1,  aws start session resource is not yet supported in AWS System Manager Session Manager. It is good to have this feature added soon as this is new approach AWS recommends and its useful for the port forwarding feature within AWS Session Manager.

New or Affected Resource(s)
aws_4.15.1

**Comment by rahul-amzn** [comment]
Adding reference link - https://aws.amazon.com/about-aws/whats-new/2022/05/aws-systems-manager-support-port-forwarding-remote-hosts-using-session-manager/
