### ISSUE TITLE
aws_transfer_server allow setting hostname

### ISSUE THREAD

**Issue by SpootyMcSpoot** [hashicorp/terraform-provider-aws#25119]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We would like to be able to set the hostname of the SFTP servers via the aws_transfer_server terraform resource. There is nothing in the documentation that shows an argument for this value.

Example:
![sftp-no-hostname](https://user-images.githubusercontent.com/6732450/171232939-dc8bd5f7-3c48-4d63-905e-2df885b30083.PNG)

### New or Affected Resource(s)

aws_transfer_server

### Potential Terraform Configuration

resource "aws_transfer_server" "xxxx" {
  server_hostname                    = xxxx <-------------- new optional argument to set server hostname by instance.
  identity_provider_type           = "xxxx"
  logging_role                     = aws_iam_role.xxxx
  protocols                        = ["xxxx"]
  security_policy_name             = "xxxx"
  endpoint_type                    = "xxxx"

}
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by ewbankkit** [comment]
@SpootyMcSpoot Thanks for raising this issue.
It has already been noticed in #18077. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
