### ISSUE TITLE
Enable resource sharing within AWS Organizations for RAM

### ISSUE THREAD

**Issue by bebold-jhr** [hashicorp/terraform-provider-aws#25115]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I couldn't find a way to enable resource sharing for AWS Resource Access Manager (RAM) on organization level. See [documentation](https://docs.aws.amazon.com/ram/latest/userguide/getting-started-sharing.html#getting-started-sharing-orgs). It would be great if this would be supported as well.

### New or Affected Resource(s)

* aws_ram_organization_resource_sharing (proposed name)

### Potential Terraform Configuration

```hcl
resource "aws_ram_organization_resource_sharing" "this" {
  enabled = true
}
```

Alternatively if there are more settings to be expected maybe something like this

```hcl
resource "aws_ram_organization_settings" "this" {
  resource_sharing_enabled = true
}
```

**Comment by Hronom** [comment]
Hey is there plans to add this?
