### ISSUE TITLE
AWS provider no more able to fall back to AWS environment variables when profile is not available

### ISSUE THREAD

**Issue by sdesousa86** [hashicorp/terraform-provider-aws#25129]
**Community Note**

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Description**
Since I'm using v4 of the aws provider, Terraform is no more able to automatically switch from AWS profile (for local deployments) to AWS environment variables (for Jenkins deployments), when aws profile does not exist.

**Terraform CLI and Terraform AWS Provider Version**
- Terraform CLI: v1.1.6
- Terraform AWS Provider Version: 4.16.0

**Affected Resource(s)**
- All AWS resources

```
terraform {
  required_version = ">= 1.0.0"

  backend "s3" {}

    aws = {
      source  = "hashicorp/aws"
      version = "4.16.0"
    }

  }
}

provider "aws" {
  profile = var.aws_cli_profile
  region  = var.region
}
```

**Expected Behavior**
Terraform should be able to automatically fall back to AWS environment variables (as it was done before the v4 of the aws provider) when the AWS CLI profile does not exist.

**Actual Behavior**
Terraform raises an error if the provider profile does not exist.

**Steps to reproduce**
1. Set AWS CLI profile
2. Try to deploy your AWS resources (it works)
3. Move to an environment where AWS CLI profile is not set, but AWS credentials env. variables are set
4. Try to deploy your AWS resources (it's not working)

````
│ Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: bea08029-0eb6-465a-83cd-6fa0bade246a, api error InvalidClientTokenId: The security token included in the request is invalid.
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on 02_provider.tf line 30, in provider "aws":
│   30: provider "aws" {
````

**References**
https://discuss.hashicorp.com/t/error-error-configuring-terraform-aws-provider-failed-to-get-shared-config-profile-default/39417

**Current workaround**
````
variable "is_aws_profile_used" {
  description = "Indicate if you are using an aws-cli profile or not (for local deployment only, must be equal to false on Jenkins)"
  type        = bool
  default     = false
}

terraform {
  required_version = ">= 1.0.0"

  backend "s3" {}

    aws = {
      source  = "hashicorp/aws"
      version = "4.16.0"
    }

  }
}

provider "aws" {
  profile = var.is_aws_profile_used ? var.aws_cli_profile : null
  region  = var.region
}
````

**Comment by gdavison** [comment]
Thanks for submitting this issue, @sdesousa86. As of v4.0 of the AWS provider, this is the expected behaviour. Please see https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade#changes-to-authentication and https://registry.terraform.io/providers/hashicorp/aws/latest/docs#authentication-and-configuration for more details. This behaviour now matches how the AWS CLI and AWS SDKs work.
