### ISSUE TITLE
aws_appflow_flow error setting trigger_config

### ISSUE THREAD

**Issue by MattCWheeler** [hashicorp/terraform-provider-aws#25172]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.17.0

I also tested and got this error with Terraform v1.2.2 with aws v4.14.0, v4.16.0, v4.17.0.

### Affected Resource(s)

* aws_appflow_flow

### Terraform Configuration Files

```hcl

resource "aws_appflow_flow" "solar_projects_incremental" {
  name = "foo"

  source_flow_config {
    connector_type = "Salesforce"
    source_connector_properties {
      salesforce {
        object = "foo"
      }
    }
  }

  destination_flow_config {
    connector_type = "S3"
    destination_connector_properties {
      s3 {
        bucket_name = var.landing_bucket_name
      }
    }
  }

  task {
    source_fields = [ "foo" ]
    task_type         = "Filter"
  }

  trigger_config {
    trigger_properties {
      scheduled {
        schedule_expression = "rate(1hours)"
      }
    }
    trigger_type = "Scheduled"
  }
}
```

### Debug Output

https://gist.github.com/MattCWheeler/0f1e6c5fead9ed31959511c387a53c7d

### Expected Behavior

Resource should be created

### Actual Behavior
Resource is not created, with error:

```
error setting trigger_config: Invalid address to set: []string{"trigger_config", "0", "trigger_properties", "0", "trigger_properties"}
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

It seems that the example given here https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appflow_flow#trigger-config is also incorrect. When I try that, I get 

```
│ Error: Missing required argument
│ 
│   on ../modules/dataset_flow_pair_v2/main.tf line 43, in resource "aws_appflow_flow" "projects_incremental":
│   43:   trigger_config {
│ 
│ The argument "trigger_type" is required, but no definition was found.
╵
╷
│ Error: Unsupported block type
│ 
│   on ../modules/dataset_flow_pair_v2/main.tf line 44, in resource "aws_appflow_flow" "projects_incremental":
│   44:     scheduled {
│ 
│ Blocks of type "scheduled" are not expected here.
```

**Comment by johnr-odusa** [comment]
I am also encountering this error. After looking through the source code, I believe the I may have found the issue:

main branch, file internal/service/appflow/flow.g, line 3540 in func `flattenTriggerProperties`.  The specific line in question would be:

```
3540			m["trigger_properties"] = []interface{}{flattenScheduled(v)}  
```
I believe that this line should actually be:
```
3540			m["scheduled"] = []interface{}{flattenScheduled(v)}  
```

I'm pasting that function and its calling function here for context:

```
3514	func flattenTriggerConfig(triggerConfig *appflow.TriggerConfig) map[string]interface{} {
3515		if triggerConfig == nil {
3516			return nil
3517		}
3518	
3519		m := map[string]interface{}{}
3520	
3521		if v := triggerConfig.TriggerProperties; v != nil {
3522			m["trigger_properties"] = []interface{}{flattenTriggerProperties(v)}   // "trigger_properties" is set here
3523		}
3524	
3525		if v := triggerConfig.TriggerType; v != nil {
3526			m["trigger_type"] = aws.StringValue(v)
3527		}
3528	
3529		return m
3530	}
3531	
3532	func flattenTriggerProperties(triggerProperties *appflow.TriggerProperties) map[string]interface{} {
3533		if triggerProperties == nil {
3534			return nil
3535		}
3536	
3537		m := map[string]interface{}{}
3538	
3539		if v := triggerProperties.Scheduled; v != nil {
3540			m["trigger_properties"] = []interface{}{flattenScheduled(v)}          // "scheduled" should be set here
3541		}
3542	
3543		return m
3544	}
```

**Comment by johnr-odusa** [comment]
Created a pull request to implement the change described above: #26240
