### ISSUE TITLE
Misleading password error with aws_iam_role_policy_attachment

### ISSUE THREAD

**Issue by tommyallieri** [hashicorp/terraform-provider-aws#25207]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
$ terraform -v
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.15.1

### Affected Resource(s)

* aws_iam_role_policy_attachment

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "aws_lambda_function" "this" {
  function_name = "my_lambda"
}

resource "aws_iam_policy" "this" {
  name = "policy_name"
  policy = jsonencode([...])
}

resource "aws_iam_role_policy_attachment" "this" {
  role       = data.aws_lambda_function.this.role
  policy_arn = aws_iam_policy.this.arn
}
```

### Expected Behavior

Either of
* Policy attached to role (would be nice to accept arn as well as role name)
* ValidationError - The specified value for the *role name* is invalid.

### Actual Behavior

```
│ Error: Error attaching policy arn:aws:iam::*****:policy/policy_name to IAM Role arn:aws:iam::*****:role/role_name ValidationError: The specified value for password is invalid. It must contain only printable ASCII characters.
```
The error pointing to an invalid password is misleading, the problem is with the role name.

### Steps to Reproduce

1. `terraform apply`

**Comment by gdavison** [comment]
Hi @tommyallieri, does your policy JSON make any reference to a password? The error message `ValidationError: The specified value for password is invalid. It must contain only printable ASCII characters` is being returned by the AWS API.

**Comment by tommyallieri** [comment]
hi @gdavison, no password or anything similar in the policy, we tried something along the lines of
```
  policy = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Action" : [
          "ssm:GetParameter"
        ],
        "Resource" : "*",
        "Effect" : "Allow"
      }
    ]
  })
}
```

Sounded more like the wrong validation error was sent back. The problem was that the provider expects a role name and not arn, which the lambda data resource doesn't have available. The fix was to extract the role name from the arn (don't judge the way it was done 😂)

```
resource "aws_iam_role_policy_attachment" "this" {
  role       = split(":role/", data.aws_lambda_function.this.role)[1]
  policy_arn = aws_iam_policy.this.arn
}
```

To confirm, the policy had no mention of a password and its content was irrelevant to the error
