### ISSUE TITLE
Documentation: Error in example (`role` -> `principal`)

### ISSUE THREAD

**Issue by chroche** [hashicorp/terraform-provider-aws#25202]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

AWS Provider `v4.17.1`

### Affected Resource(s)

Documentation page for resource: [aws_lakeformation_permissions](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lakeformation_permissions)

### Actual Behavior

When using the example titled [Grant Permissions For A Glue Catalog Database](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lakeformation_permissions#grant-permissions-for-a-glue-catalog-database), the following error is generated:
```
│ Error: Missing required argument
│
│   on s3-storage-lens.tf line 44, in resource "aws_lakeformation_permissions" "s3_storage_lens":
│   44: resource "aws_lakeformation_permissions" "s3_storage_lens" {
│
│ The argument "principal" is required, but no definition was found.
╵
╷
│ Error: Unsupported argument
│
│   on s3-storage-lens.tf line 45, in resource "aws_lakeformation_permissions" "s3_storage_lens":
│   45:   role        = aws_iam_role.s3_storage_lens.arn
│
│ An argument named "role" is not expected here.
```

### Important Factoids

The example should be, just like [the one above it](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lakeformation_permissions#grant-permissions-for-a-lake-formation-s3-resource):
```hcl
resource "aws_lakeformation_permissions" "example" {
  principal   = aws_iam_role.workflow_role.arn
  permissions = ["CREATE_TABLE", "ALTER", "DROP"]

  database {
    name       = aws_glue_catalog_database.example.name
    catalog_id = "110376042874"
  }
}
```

**Comment by justinretzolk** [comment]
Hey @chroche 👋 Thank you very much for bringing this to our attention! I've opened a PR to correct this 👍
