### ISSUE TITLE
Support UserAttributeUpdateSettings in aws_cognito_user_pool resource

### ISSUE THREAD

**Issue by dseravalli** [hashicorp/terraform-provider-aws#25228]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It does not look like the Cognito User Pool resource currently supports `UserAttributeUpdateSettings` in version 4.17.1

https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UserAttributeUpdateSettingsType.html

### New or Affected Resource(s)

* aws_cognito_user_pool

### Potential Terraform Configuration

```hcl
resource "aws_cognito_user_pool" "example" {
  # ... other configuration ...

  user_attribute_update_settings = {
    attributes_require_verification_before_update = ["email", "phone_number"]
  }
}
```

**Comment by dwightbiddle-ef** [comment]
Yes please!

**Comment by John9570** [comment]
could definitely use this

**Comment by ewbankkit** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/27129.
