### ISSUE TITLE
aws_transfer_workflow creation never end in case of bad configuraiton

### ISSUE THREAD

**Issue by remy-bresson** [hashicorp/terraform-provider-aws#25269]
---
name: 🐛 Bug Report
about: If something isn't working as expected 🤔.

---

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.18.0

### Affected Resource(s)

* aws_transfer_workflow

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "~> 4.18.0"
    }
  }
  required_version = ">= 0.14.9"
}

provider "aws" {
  profile = "default"
  region = "eu-west-3"
}

resource "aws_transfer_workflow" "workflowArchive" {
  description = "testWorkflow"
  steps {
    tag_step_details {
      name = "deleteUploaded"
      source_file_location = "$${original.file}"
    }
    type = "DELETE"
  }
}
```

### Expected Behavior

Must raise an error as "tag_step_details" could not be associated with type = "DELETE". Also you may think of removing the type as it is a doublon with the inner block "*step_details"

### Actual Behavior

The terraform client never finish (I kill it after 20 minutes)

### Steps to Reproduce

1 `terraform init`
2 `terraform apply --auto-approve`

**Comment by justinretzolk** [comment]
Hey @remy-bresson 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?

**Comment by remy-bresson** [comment]
> Hey @remy-bresson 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?

Thanks for your feedback, I update the issue.
