### ISSUE TITLE
aws_sagemaker_domain resource is replaced when default_user_settings argument is updated

### ISSUE THREAD

**Issue by giuliogaliero** [hashicorp/terraform-provider-aws#25266]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.2.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.17.1

### Affected Resource(s)

* aws_sagemaker_domain

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

#### Before

```hcl
resource "aws_sagemaker_domain" "example" {
  domain_name = "example"
  auth_mode   = "IAM"
  vpc_id      = aws_vpc.test.id
  subnet_ids  = [aws_subnet.test.id]

  default_user_settings {
    execution_role = aws_iam_role.test.arn
  }
}

resource "aws_iam_role" "example" {
  name               = "example"
  path               = "/"
  assume_role_policy = data.aws_iam_policy_document.example.json
}

data "aws_iam_policy_document" "example" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["sagemaker.amazonaws.com"]
    }
  }
}
```

#### After (Updating default_user_settings in aws_sagemaker_domain)

```hcl
resource "aws_sagemaker_domain" "example" {
  domain_name = "example"
  auth_mode   = "IAM"
  vpc_id      = aws_vpc.test.id
  subnet_ids  = [aws_subnet.test.id]

  default_user_settings {
    execution_role = aws_iam_role.test.arn
    sharing_settings {
      notebook_output_option = "Allowed"
      s3_kms_key_id = aws_kms_key.sagemaker_notebook_kms_cmk.arn
    }
  }
}
```

### Expected Behavior

aws_sagemaker_domain resource should be updated in place when default_user_settings argument is updated, as specified here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-domain.html#cfn-sagemaker-domain-defaultusersettings

### Actual Behavior
aws_sagemaker_domain resource is replaced when default_user_settings argument is updated

### References
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-domain.html#cfn-sagemaker-domain-defaultusersettings

* #0000

**Comment by farhanangullia** [comment]
I believe some of the properties, including the sharing_settings, for this resource has the ForceNew field set to True.. removing this should fix this behaviour.
