### ISSUE TITLE
Eventbridge: Support Invocation Rate > 300 

### ISSUE THREAD

**Issue by jordanfinners** [hashicorp/terraform-provider-aws#25276]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

[Eventbridge API Destination Invocation Rate](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_api_destination#invocation_endpoint) currently has a [maximum limit of 300 requests per second in the validation](https://github.com/hashicorp/terraform-provider-aws/blob/8196817bdf7702d3fa78cf86bb3e21029288c5b3/internal/service/events/api_destination.go#L49)

However, this rate can actually be increased if you contact [AWS via Service Quotas](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-quota.html)

### New or Affected Resource(s)

* aws_cloudwatch_event_api_destination

**Comment by meetreks** [comment]
I am looking into this issue

**Comment by jordanfinners** [comment]
> I am looking into this issue

@meetreks I've already added a PR for this 😊
https://github.com/hashicorp/terraform-provider-aws/pull/25277
