### ISSUE TITLE
Support updateToLatestImageVersion in aws_batch_compute_environment#compute_resources

### ISSUE THREAD

**Issue by aaleksandrov** [hashicorp/terraform-provider-aws#25285]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Since April 2022 AWS Batch supports `updateToLatestImageVersion` argument in aws_batch_compute_environment
 https://docs.aws.amazon.com/batch/latest/APIReference/API_ComputeResourceUpdate.html#Batch-Type-ComputeResourceUpdate-updateToLatestImageVersion

### New or Affected Resource(s)

* aws_batch_compute_environment (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/batch_compute_environment#compute_resources)

### Potential Terraform Configuration

```hcl
update_to_latest_image_version = true/false
```

### References

* https://aws.amazon.com/blogs/hpc/aws-batch-updates-higher-compute-utilization-aws-privatelink-support-and-updatable-compute-environments/
* https://docs.aws.amazon.com/batch/latest/userguide/updating-compute-environments.html

**Comment by aaleksandrov** [comment]
Hi @bulususb I closed it myself because it's a duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/24374

**Comment by bulususb** [comment]
Thank you!
