### ISSUE TITLE
"dimension" attribute not expected here cost explorer monitor

### ISSUE THREAD

**Issue by reskin89** [hashicorp/terraform-provider-aws#25295]
### Terraform Configuration Files
```terraform
resource "aws_ce_anomaly_monitor" "billing_anomalies" {
  name         = "BillingAnomalies"
  monitor_type = "DIMENSIONAL"
  dimension    = "SERVICE"

  tags = {
    purpose     = "billing anomalies"
    environment = "all"
    region      = "global"
  }
}
```

### Expected Behavior
The monitor should be created

### Actual Behavior
During plan:

```
│ Error: Unsupported argument
│ 
│   on cost_monitors.tf line 4, in resource "aws_ce_anomaly_monitor" "billing_anomalies":
│    4:   dimension    = "SERVICE"
│ 
│ An argument named "dimension" is not expected here.
```

If `dimension` is removed the plan succeeds however the apply fails as dimension is required:

```
╷
│ Error: If Monitor Type is DIMENSIONAL, dimension attrribute is required
│ 
│   with aws_ce_anomaly_monitor.billing_anomalies,
│   on cost_monitors.tf line 1, in resource "aws_ce_anomaly_monitor" "billing_anomalies":
│    1: resource "aws_ce_anomaly_monitor" "billing_anomalies" {
│ 
╵
```

The [documentation example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ce_anomaly_monitor#dimensional-example) shows:

```
resource "aws_ce_anomaly_monitor" "service_monitor" {
  name      = "AWSServiceMonitor"
  type      = "DIMENSIONAL"
  dimension = "SERVICE"
}
```

### Steps to Reproduce

1. Create a `aws_ce_anomaly_monitor` resource as the documentation example shows
2. Attempt a terraform plan

### Additional Context

Attempting to create a cost explorer anomaly monitor fails as terraform doesn't expect an attribute that is required to create one, the `dimension` attribute when the type is `DIMENSIONAL`.

On top of this, the documentation states the attribute `type` is required, however, terraform is expecting this argument to be `monitor_type` instead.

**Comment by justinretzolk** [comment]
Hey @reskin89 👋 Thank you for taking the time to raise this! It looks like there's a couple of different errors in the documentation -- I'll work on a pull request shortly to have those corrected. In the meantime, it looks like the correct arguments are [`monitor_dimension`](https://github.com/hashicorp/terraform-provider-aws/blob/fc8305ac6f5f665df3195f1a2dd8ac22e3adef91/internal/service/ce/anomaly_monitor.go#L36) and [`monitor_type` (as you called out)](https://github.com/hashicorp/terraform-provider-aws/blob/fc8305ac6f5f665df3195f1a2dd8ac22e3adef91/internal/service/ce/anomaly_monitor.go#L57).
