### ISSUE TITLE
Add support for Route 53 IP Based Routing Policy

### ISSUE THREAD

**Issue by mendhak** [hashicorp/terraform-provider-aws#25321]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has introduced a new Route 53 IP Based Routing Policy, see: https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-ip-based-routing-for-amazon-route-53/

It seems there is a pre-step to using it though. 
First you have to create a CIDR Collection, and associate some CIDRs with it
Then you can create a Route 53 record with a value for the above collection, and another value for '*'. 

### New or Affected Resource(s)

* aws_route53_record

### References

* https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-ip-based-routing-for-amazon-route-53/
* https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy-ipbased.html

**Comment by bschaatsbergen** [comment]
I'll see if I can figure this one out..

**Comment by bschaatsbergen** [comment]
I think that we're going to create a new route53 resource called `aws_route53_cidr_collection` which can be used to refer to a CIDR location in the IP-based routing policy (the IP-based routing policy is to be added as part of the `aws_route53_record` resource.

**Comment by bschaatsbergen** [comment]
Started to actively work on this as of now.

**Comment by bschaatsbergen** [comment]
> On hold for a moment; checking together with @ewbankkit on how to nicely integrate this with the existing Route53 CidrCollection API.

**Comment by Hexta** [comment]
Hello @bschaatsbergen 
Sorry for pinging you. 
Is there any chance this feature will be implemented?

**Comment by ewbankkit** [comment]
I think we'll go with 2 new resource:

* `aws_route53_cidr_collection`
* `aws_route53_cidr_location`
