### ISSUE TITLE
Firewall Manager (FMS): Support Protocol Lists

### ISSUE THREAD

**Issue by jdeluyck** [hashicorp/terraform-provider-aws#25323]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

FMS (Firewall Manager) has protocol lists, which can be used in security group content audit mode to verify that only allowed protocols are enabled.

### New or Affected Resource(s)

aws_fms_policy
aws_fms_protocol

### Potential Terraform Configuration

```hcl
Proposal:

resouce "aws_fms_protocol" "protocol-list" {
  name  = protocolListName
  protocols = [proto1, proto2, ...]
}
```

### References

```bash
$ aws fms list-protocols-lists --max-results  10
{
    "ProtocolsLists": [
        {
            "ListArn": "arn:aws:fms:eu-west-1:xxx:protocols-list/36a2e5e3-6032-41f4-836d-123456789",
            "ListId": "36a2e5e3-6032-41f4-836d-123456789",
            "ListName": "AllowedProtos",
            "ProtocolsList": [
                "TCP"
            ]
        }
    ],
    "NextToken": "36a2e5e3-6032-41f4-836d-123456789"
```

https://docs.aws.amazon.com/waf/latest/developerguide/working-with-managed-lists.html

* #0000

**Comment by rajdeephayer** [comment]
waiting for this feature
