### ISSUE TITLE
aws_ssm_parameter not allowing overwrite = true

### ISSUE THREAD

**Issue by zerosync-net** [hashicorp/terraform-provider-aws#25335]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.2.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.18.0

### Affected Resource(s)

* aws_ssm_parameter

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "~> 4.18.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
  profile = "develop"
}

variable "environment" {
  default = "develop"
}

resource "aws_ssm_parameter" "environment" {
  name = "/Global/Env"
  description = "Storage of environment variable (develop,staging,prod)"
  type = "String"
  value = var.environment
  overwrite = true
}
```

### Expected Behavior

Overwrite any previously existing parameter store value

### Actual Behavior

```shell
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_ssm_parameter.environment will be created
  + resource "aws_ssm_parameter" "environment" {
      + arn         = (known after apply)
      + data_type   = (known after apply)
      + description = "Storage of environment variable (develop,staging,prod)"
      + id          = (known after apply)
      + key_id      = (known after apply)
      + name        = "/Global/Env"
      + overwrite   = true
      + tags_all    = (known after apply)
      + tier        = (known after apply)
      + type        = "String"
      + value       = (sensitive value)
      + version     = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_ssm_parameter.environment: Creating...
╷
│ Error: error creating SSM Parameter (/Global/Env): ParameterAlreadyExists: The parameter already exists. To overwrite this value, set the overwrite option in the request to true.
│ 
│   with aws_ssm_parameter.environment,
│   on main.tf line 19, in resource "aws_ssm_parameter" "environment":
│   19: resource "aws_ssm_parameter" "environment" {
│ 
╵
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Only observed the incorrect behaviour while running aws provider v4.18.0, rolling back to v4.17.0 overwrite = true seems to function normally.  Once the build has overwritten in v4.17.0, switching back to v4.18.0 obviously no longer needs the overwrite value as its managing properly.  

### References

Nothing I could find for the current release.

**Comment by bschaatsbergen** [comment]
I can take a quick look at this

**Comment by bschaatsbergen** [comment]
@gdavison, judging by https://github.com/hashicorp/terraform-provider-aws/commit/226cd4f55e572f733d8790484d8d79ba72c4ba92 

It seems that we broke some existing functionality here. Was there any specific reason to remove this?

**Comment by aavileli** [comment]
waiting for a fix. Otherwise need to pin provider version. Thanks

**Comment by kavyasam** [comment]
I pin down to 4.17.1 version and it was working fine .. waiting for the fix

**Comment by bwasjr** [comment]
Just to add more information... I had the same issue with v4.25.0.

**Comment by posquit0** [comment]
Same issue with v4.27.0.

<img src="https://media0.giphy.com/media/aX2P8kEFqt8u4/giphy.gif"/>

**Comment by loganl098** [comment]
Same issue with v4.29.0.

**Comment by JoergHeinicke5005** [comment]
This issue has been confirmed to be a regression more than 2 months ago. Is there any reason why it is not being fixed?

**Comment by aavileli** [comment]
Add **Overwrite: aws.Bool(ShouldUpdateParameter(d))** to **paramInput** [struct](https://github.com/hashicorp/terraform-provider-aws/blob/v4.30.0/internal/service/ssm/parameter.go#L149..L154) back,  if a variable was created out of terraform then user should be allowed to overwrite. [Documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_parameter) needs to be updated with workaround to import ssm but this will be a pain if there are large number of SSM parameters.

**Comment by danballance** [comment]
I'm seeing this same issue in v4.30.0.

**Comment by bschaatsbergen** [comment]
I'll happily take a look at this regression issue in the coming few days.

**Comment by bschaatsbergen** [comment]
Fix is ready for review :+1:

**Comment by funes79** [comment]
Same issue in v4.31.0
