### ISSUE TITLE
sweepers: DocDB resources missing sweepers

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#25343]
The DocDB service is missing the following sweepers:

- [ ] `aws_docdb_cluster_instance`
- [ ] `aws_docdb_cluster_parameter_group`
- [ ] `aws_docdb_cluster_snapshot`
- [ ] `aws_docdb_cluster`
- [ ] `aws_docdb_event_subscription`
- [ ] `aws_docdb_subnet_group`

**Comment by bschaatsbergen** [comment]
I'll happily pick this up :+1:

**Comment by gdavison** [comment]
> I'll happily pick this up 👍

Thanks!
