### ISSUE TITLE
Updating tags for aws_kinesis_firehose_delivery_stream also updates the Redshift delivery settings

### ISSUE THREAD

**Issue by statlus** [hashicorp/terraform-provider-aws#25396]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

- Terraform CLI version  1.2.3
- Terraform AWS Provider Version 4.18.0

### Affected Resource(s)

* aws_kinesis_firehose_delivery_stream

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_kinesis_firehose_delivery_stream" "example" {
  name        = "example_stream"
  destination = var.kinesis_destination_configuration

  s3_configuration {
    role_arn           = aws_iam_role.role.arn
    bucket_arn         = data.aws_s3_bucket.bucket.arn
    prefix             = var.s3_path
    buffer_size        = var.kinesis_buffer_size
    compression_format = "GZIP"
  }

  redshift_configuration {
    role_arn        = aws_iam_role.role.arn
    cluster_jdbcurl = local.cluster_jdbcurl

    username = "username"
    password = "password"

    data_table_name    = var.data_table_name
    copy_options       = var.data_copy_options
    data_table_columns = join(", ", var.data_table_columns)

    processing_configuration {
      enabled = "false"
    }
    cloudwatch_logging_options {
      enabled         = true
      log_group_name  = aws_cloudwatch_log_group.log_group.name
      log_stream_name = aws_cloudwatch_log_stream.redshift.name
    }
  }

  lifecycle {
    ignore_changes = [
      redshift_configuration.0.username,
      redshift_configuration.0.password,
    ]
  }
}
```

### Expected Behavior

Terraform should just apply the tags without making any other changes.

### Actual Behavior

Tags were applied but the password for the `redshift_configuration` was blanked out, so the stream started to fail to deliver any content to Redshift.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

We set the username and password to placeholder values that we then change manually in the AWS Management Console. We do this to keep credentials out of Terraform state, where it can be extracted. We believe that when the Terraform AWS Provider goes to update tags, it also goes to update delivery settings, which then sets the credentials to the placeholder values.

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @statlus 👋 Thank you for taking the time to raise this! It's a bit hard to say for certain without logging, but it sounds like what's happening here is that Terraform is [detecting the drift](https://learn.hashicorp.com/tutorials/terraform/resource-drift) between the configuration and reality, and attempting to reconcile it by updating the password to what's defined in the Terraform configuration. You should be able to get around this by specifying a [`lifecycle.ignore_changes` block](https://www.terraform.io/language/meta-arguments/lifecycle#ignore_changes) to tell Terraform to ignore this drift. Can you test that and verify that it corrects the issue you're running into?

**Comment by statlus** [comment]
Hi @justinretzolk, thanks for the quick response! The Terraform config I posted above was the original code that we applied (with namings and some variables changed for privacy reasons). That includes the `lifecycle.ignore_changes` block already specified. In addition, the change we were making at the time was only to introduce provider-level tags. The plan from that change only showed the addition of tags on that particular resource.

**Comment by ewbankkit** [comment]
Need to add to use of [`if d.HasChangesExcept("tags", "tags_all")`](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/contribution-checklists.md#resource-tagging-code-implementation) to https://github.com/hashicorp/terraform-provider-aws/blob/1644f0171903703fcbc36ae054dc7accce94403f/internal/service/firehose/delivery_stream.go#L2714

**Comment by justinretzolk** [comment]
@statlus Apologies for missing that you already had the `lifecycle` block configured! I totally glossed over that on my initial read 🙃. I've marked this as a bug so that we can look into it as soon as time allows.
