### ISSUE TITLE
Feature Request: aws_imagebuilder_distribution_configuration support fastLaunchConfigurations

### ISSUE THREAD

**Issue by jgard** [hashicorp/terraform-provider-aws#25397]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

[CreateDistributionConfiguration](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_CreateDistributionConfiguration.html) and [UpdateDistributionConfiguration](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_UpdateDistributionConfiguration.html) support [`fastLaunchConfigurations`](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_Distribution.html#imagebuilder-Type-Distribution-fastLaunchConfigurations), so the resulting Windows AMIs take advantage of [EC2 Fast Launch](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/win-ami-config-fast-launch.html).

### New or Affected Resource(s)

* `resource aws_imagebuilder_distribution_configuration`
* `data aws_imagebuilder_distribution_configuration`

### Potential Terraform Configuration

```hcl
resource "aws_imagebuilder_distribution_configuration" "example" {
  name = "example"
  distribution {
    ami_distribution_configuration {
      #...
    }
    launch_template_configuration {
      #...
    }
    region = "us-east-1"
    fast_launch_configuration {
      account_id = "123456789012"
      enabled    = true
      launch_template {
        #One of launch_template_id or launch_template_name required
        launch_template_id = "lt-0aaa1bcde2ff3456"
        #launch_template_name = "my_launch_template"
        launch_template_version = 2
      }
      max_parallel_launches = 5
      snapshot_configuration {
        target_resource_count = 10
      }
    }
  }
}
```

### References
* [AWS Announces New Launch Speed Optimizations for Microsoft Windows Server Instances on Amazon EC2](https://aws.amazon.com/about-aws/whats-new/2022/01/aws-speed-optimizations-windows-instances-ec2/)

**Comment by kamilturek** [comment]
I'll take it.
