### ISSUE TITLE
iso/elasticache: Replication group panic, nil pointer

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#25430]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Relates #18593

### Affected Resource(s)

* aws_elasticache_replication_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_elasticache_subnet_group" "cache_subnet_group" {
  name = "raves-${var.ENV}-cache-subnet"
  subnet_ids = data.terraform_remote_state.vpc.outputs.private_persistence_subnet_ids
}
 
resource "aws_elasticache_replication_group" "cache_replication_group_v2" {
  replication_group_id          = "raves-${var.ENV}-cache-002"
  description                   = "Redis cluster for RAVES ${var.ENV}"
  node_type                     = var.elasticache_redis_node_type
  num_cache_clusters            = "2"
  port                          = "6379"
  parameter_group_name          = "default.redis5.0"
  security_group_ids            = [[aws_security_group.raves-internal.id](http://aws_security_group.raves-internal.id/)]
  snapshot_retention_limit      = "0"
  subnet_group_name             = [aws_elasticache_subnet_group.cache_subnet_group.name](http://aws_elasticache_subnet_group.cache_subnet_group.name/)
  automatic_failover_enabled    = "true"
  auto_minor_version_upgrade    = "true"
  maintenance_window            = "sun:05:00-sun:09:00"
  transit_encryption_enabled    = true
  at_rest_encryption_enabled    = true
  apply_immediately             = true
  tags = var.custom_tags
}
```

### Panic Output

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x47f29a]
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by blafrisch** [comment]
I can confirm that [this PR](https://github.com/hashicorp/terraform-provider-aws/pull/25429) has indeed resolved the panic.
