### ISSUE TITLE
Retrieve subnets arn using aws_subnets datasource

### ISSUE THREAD

**Issue by littlejo** [hashicorp/terraform-provider-aws#25441]
Datasource improvement:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/subnets

We only have ids of subnets outputs. It could be good to also have arns of subnets.

A workaround is: 
`subnets_arns              = [for subnet_id in data.aws_subnets.this.ids : "arn:aws:ec2:${var.region}:${data.aws_caller_identity.this.account_id}:subnet/${subnet_id}"]`

But it's dirty.

**Comment by justinretzolk** [comment]
Hey @littlejo 👋 Thank you for taking the time to raise this! In this case, you can combine the use of the `aws_subnets` data source with the [`aws_subnet` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/subnet) to retrieve the ARNs in a bit more of a clean way. A similar example is displayed in the [example usage](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/subnets#example-usage) section of the `aws_subnets` data source, but I've also created a sample configuration and output below.

Configuration:

```hcl
data "aws_subnets" "subnets" {
  filter {
    name   = "vpc-id"
    values = [var.vpc_id]
  }
}

data "aws_subnet" "subnet" {
  for_each = toset(data.aws_subnets.subnets.ids)
  id       = each.value
}

output "subnet" {
  value = [for subnet in data.aws_subnet.subnet : subnet.arn]
}
```

Output:

```shell
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

subnet = [
  "arn:aws:ec2:us-east-1:<redacted>:subnet/subnet-01d1a1a91e7e1376c",
  "arn:aws:ec2:us-east-1:<redacted>:subnet/subnet-022608653ad7daa6e",
  "arn:aws:ec2:us-east-1:<redacted>:subnet/subnet-09626f446d74686d4",
  "arn:aws:ec2:us-east-1:<redacted>:subnet/subnet-0cf090040fc8afd53",
]
```

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
