### ISSUE TITLE
aws_vpc_ipam_pool data source fails to return when ID is specified

### ISSUE THREAD

**Issue by rvodden** [hashicorp/terraform-provider-aws#25465]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.2.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.19.0

```

### Affected Resource(s)

* aws_vpc_ipam_pool

### Terraform Configuration Files

```
terraform {
    required_providers {
      aws = {
      } 
    }
}

provider "aws" {
    region = "eu-west-2"
}

data "aws_vpc_ipam_pool" "pool" {
    id = "ipam-pool-0655155938e5e611c"
}

output "pool" {
    value = data.aws_vpc_ipam_pool.pool
}
```

### Debug Output

https://gist.github.com/rvodden/d44906f3b8d8e0321ce6ec6c956e5069

### Expected Behavior

successful plan

### Actual Behavior

```
> terraform plan
data.aws_vpc_ipam_pool.pool: Reading...

Error: multiple IPAM Pools matched; use additional constraints to reduce matches to a single IPAM pool

  with data.aws_vpc_ipam_pool.pool,
  on main.tf line 12, in data "aws_vpc_ipam_pool" "pool":
  12: data "aws_vpc_ipam_pool" "pool" {

```

### Steps to Reproduce

1. Create an IPAM and two pools
2. Wait for both pools to be in "Create-Complete" state
3. Run `terraform plan`

### Important Factoids

This can be meaningfully worked around by filtering on the ipam id like this:

```
data "aws_vpc_ipam_pool" "pool" {
    id = "ipam-pool-010f0341798fba4bb"
    filter {
      name = "ipam-pool-id"
      values = ["ipam-pool-010f0341798fba4bb"]
    }
}
```

### References

* [VPC Ipam resouce documentation](https://registry.terraform.io/providers/hashicorp%20%20/aws/latest/docs/data-sources/vpc_ipam_pool)
* The ec2/api.go is too big for the go docs to render, so the [comments in the raw file have to be read](https://raw.githubusercontent.com/aws/aws-sdk-go/v1.44.37/service/ec2/api.go)

**Comment by rvodden** [comment]
I think that this is a documentation issue. When `ipam_pool_id` is specified then everything works correctly. 

However `id` is permitted as a parameter to the data source - the only reason the acceptance test is passing is because only a single ipam_pool is created.

**Comment by justinretzolk** [comment]
Hey @rvodden 👋 Thank you for taking the time to raise this! I've opened a PR to update the documentation so that `ipam_pool_id` is properly documented, and moved `id` down to the attributes section (and documented it as such).
