### ISSUE TITLE
S3 access logging configuration, inconsistent with tfstate.

### ISSUE THREAD

**Issue by takuya-takahash1** [hashicorp/terraform-provider-aws#25500]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Hello,
I have created a resource to add access logging settings to multiple existing S3 buckets. applying adds the settings, but applying again results in `logging -> null`. This does not happen for all buckets, only some.
When I check tfstate, I get the impression that `"logging":[]` is in the description of some of those buckets, and that null is overwritten each time I do an apply. Other buckets with normal access logging did not have `"logging":[]`.
I thought that applying would update the tfstate description and keep it, but some buckets' `"logging":[]` was not updated.
Is this a bug? I would appreciate it if you could let me know.

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v1.0.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.75.2
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.3.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s)

* aws_s3_bucket
* aws_s3_bucket_logging

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_s3_bucket" "aclogging_target" {
  bucket   = "${var.name}-${var.environment}-access-logging-target"
  lifecycle_rule {
    enabled = true
    transition {
      days          = 0
      storage_class = "INTELLIGENT_TIERING"
    }
  }
  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }
}
resource "aws_s3_bucket_public_access_block" "aclogging_target" {
  bucket                  = "${var.name}-${var.environment}-access-logging-target"
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
data "aws_iam_policy_document" "aclogging_target_policy" {
  statement {
    sid = "S3AccessLoggingPolicy"
    actions = [
      "s3:PutObject",
    ]
    resources = [
      "arn:aws:s3:::${var.name}-${var.environment}-access-logging-target/*"
    ]
  principals {
      type = "Service"
      identifiers = [
        "logging.s3.amazonaws.com"
      ]
    }
  condition {
    test = "StringEquals"
    variable = "aws:SourceAccount"
    values = [
    "${data.aws_caller_identity.current.account_id}"
    ]
  }
  condition {
      test     = "ArnLike"
      variable = "aws:SourceArn"
      values = [
      "arn:aws:s3:::*" 
      ]
    }
   }
}
resource "aws_s3_bucket_policy" "aclogging_target" {
  bucket = "${var.name}-${var.environment}-access-logging-target"
  policy = data.aws_iam_policy_document.aclogging_target_policy.json
}
resource "aws_s3_bucket_logging" "aclogging_source" {
  for_each = toset(var.access_logging_enable_s3buckets)
  bucket   = each.key
  target_bucket = "aws_s3_bucket.${var.name}-${var.environment}-access-logging-target.id"
  target_prefix = "${var.name}-${var.environment}-access-logging-target/${each.key}"
}
```

### Actual Behavior

1. terraform apply
```
+logging {
+target_bucket = "access-logging-target"
+target_prefix = "access-logging-target/log-export"
        }
```
2. 2nd terraform apply
```
-logging {
-target_bucket = "logging-target" ->null
-target_prefix = "access-logging-target/log-export" ->null
        }
```
3. tfstate of the bucket whose setting is null
```
"id": "example bucket",
            "lifecycle_rule": [
              {
                "abort_incomplete_multipart_upload_days": 0,
                "enabled": true,
                "expiration": [],
                "id": "tf-s3-lifecycle-",
                "noncurrent_version_expiration": [],
                "noncurrent_version_transition": [],
                "prefix": "",
                "tags": {},
                "transition": [
                  {
                    "date": "",
                    "days": 0,
                    "storage_class": "INTELLIGENT_TIERING"
                  }
                ]
              }
            ],
            "logging": [],
            "object_lock_configuration": [],
            "object_lock_enabled": false,
            "policy": "",### Steps to Reproduce
```
4. tfstate of the bucket for which access logging was set up without problems
```
"target_bucket": "access-logging-target",
            "target_grant": [],
            "target_prefix": "logging-target/example"
          },
```
### Steps to Reproduce

1. `terraform init --upgrade`
2.  `making resource`
6. `terraform plan`
7. `terraform apply(+logging)`
8. `terraform apply(-logging)`
9. Logging settings are removed when applied.

### References

* #0000

**Comment by jornfranke** [comment]
See here on canned ACL: https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl

**Comment by takuya-takahash1** [comment]
I tried again based on the information you gave me, but it still did not work...

**Comment by jacobmargasonrga** [comment]
> specifying the `lifecycle.ignore_changes` block

This link is broken, how do you reference "server access logging" in the lifecycle.ignore_changes block?

_lifecycle {
    ignore_changes = [
      logging,
    ]
  }_

???

**Comment by justinretzolk** [comment]
Hey @jacobmargasonrga 👋 Sorry about that! I've edited my above comment to fix the link.

**Comment by justinretzolk** [comment]
Hi all 👋 It looks like this came down to the need to specify an `ignore_changes` block with pre-`4.0.0` versions of the AWS provider. As such, I'll close this issue out for now. If you're seeing this and experiencing behavior not outlined in the document referenced above, please do open a new issue so we can take another look.
