### ISSUE TITLE
Terraform AWS Module Developer Documentation

### ISSUE THREAD

**Issue by baberrehman** [hashicorp/terraform-provider-aws#25504]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am looking into the documentation and code to find the calls to AWS Go SDK from this module but haven't been very successful with that. I feel like the current documentation could be improved to explain code modules, or perhaps there's already enough documentation that I have missed.

Could someone please guide where can I find the calls to AWS Go SDK in this module? Or perhaps if there's some documentation which explains the code architecture and where to find the code which calls AWS Go SDKs? 

I am more interested to look for how Terraform structs are converted to JSON (or another format) to be passed to the AWS Go SDK. Thank you in advance.

### New or Affected Resource(s)

* aws_XXXXX

### References

* #0000

**Comment by baberrehman** [comment]
Could someone please guide where can I find the calls to AWS Go SDK in this module? Or perhaps if there's some documentation which explains the code architecture and where to find the code which calls AWS Go SDKs?

**Comment by justinretzolk** [comment]
Hey @baberrehman 👋 Thank you for taking the time to raise this. Most of the information regarding contributing to the provider can be found in the [contributing guide](https://github.com/hashicorp/terraform-provider-aws/tree/main/docs/contributing). This guide details the provider design as well as all of the information regarding the lifecycle of contributions.

If you're not looking to contribute at this point, and are just interested in inspecting the source code for various resources, that code is largely located in the [`/internal/service/` directory](https://github.com/hashicorp/terraform-provider-aws/tree/main/internal/service) of the repository, with each subdirectory of representing a given service in the AWS Go SDK. Outside of the aforementioned contribution guide, most of this is not documented elsewhere, as generally speaking folks using the provider won't need to get into the details of what underlying calls to the SDK are being made.

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. As a note, those guides have [since moved](https://hashicorp.github.io/terraform-provider-aws/).
