### ISSUE TITLE
AWS Opensearch ISM support

### ISSUE THREAD

**Issue by ellisroll-b** [hashicorp/terraform-provider-aws#25527]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With AWS supporting index state management in OpenSearch, many of us could remove home grown processing to manage older data. The new ISM functionality supports additional AWS hosted functionality supports a number of features that are attractive, many would be desirable to configure at deployment.

### New or Affected Resource(s)

aws_elasticsearch_domain 

Potentially new resources for ISM configuration, as your design sees fit.

### References

https://docs.aws.amazon.com/opensearch-service/latest/developerguide/ism.html

* #0000

**Comment by jackson-theisen** [comment]
I have also opened https://github.com/phillbaker/terraform-provider-elasticsearch/issues/299 and https://github.com/opensearch-project/opensearch-ci/issues/177 which I feel would be worth coordinating with some of the maintainers on to determine what pieces belong where.
