### ISSUE TITLE
API pass-through for aws_acmpca_certificate

### ISSUE THREAD

**Issue by pielu** [hashicorp/terraform-provider-aws#25520]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Implement API pass-through parameter to allow e.g. subordinate CA to use extensions, like name restriction.

### New or Affected Resource(s)

* aws_acmpca_certificate

### Potential Terraform Configuration

```hcl
resource "aws_acmpca_certificate" "this" {
  certificate_authority_arn      = aws_acmpca_certificate_authority.root.arn
  certificate_signing_request    = aws_acmpca_certificate_authority.this.certificate_signing_request
  signing_algorithm              = "SHA512WITHRSA"
  template_arn                   = "arn:${data.aws_partition.current.partition}:acm-pca:::template/SubordinateCACertificate_PathLen0_APIPassthrough/V1"
  api_passthrough = <<-EOF
{
  "Extensions": {
    "CustomExtensions": [
      {
        "ObjectIdentifier": "2.5.29.30",
        "Value": "bXl0ZXN0LmNvbQ==",
        "Critical": true
      }
    ]
  }
}
EOF


  validity {
    type  = "YEARS"
    value = 15
  }
}
```

### References

* https://docs.aws.amazon.com/acm-pca/latest/userguide/PcaIssueCert.html
* https://docs.aws.amazon.com/acm-pca/latest/userguide/JavaApi-CustomExtensions.html#Sub_CA_NameConstraints

**Comment by StupidScience** [comment]
Hi. I'm interested in implementation. Is there any consensus on how `api_passthrough` parameter should look like? Since e.g. `Value` in custom extensions should expected to be base64 of valid ASN.1 that can be a bit problematic for user to produce. Should it be encoded by provider or should provider expect user to provide correct value (like originally defined in this issue)?
