### ISSUE TITLE
Query ami by id

### ISSUE THREAD

**Issue by sayurin** [hashicorp/terraform-provider-aws#25521]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

[`aws_ami` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami) requires `owners` argument. Buf if `image-id` is known, it should be query without `owners`.

### Motivation

[`aws_imagebuilder_image` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/imagebuilder_image) can query latest ami. It returns `image` and `account_id`. But sometimes `account_id` is empty. Or AMI public parameters can get `image-id` only.

Then [`aws_imagebuilder_image_recipe` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/imagebuilder_image_recipe) can set ebs parameters. When specify root volume, `device_name` is required. But root's `device_name` is not fixed, and it depends on ami. It can query only `aws_ami` data source.

### New or Affected Resource(s)

* aws_ami (data source)
* aws_ami_by_id (data source)

### Potential Terraform Configuration

```hcl
data "aws_ami" "parent" {
  owners = null
  filter {
    name   = "image-id"
    values = ["ami-XXX"]
  }
}

# or simply,

data "aws_ami_by_id" "parent" {
  image_id = "ami-XXX"
}
```

### References

* [Calling AMI public parameters](https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-public-parameters-ami.html)
* [Device names on Linux instances](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html)

**Comment by DrFaust92** [comment]
i was able to test the owners arg is not required, ill take this + add a few more improvements
