### ISSUE TITLE
aws_ec2_transit_gateway_vpc_attachment creates diff on each plan

### ISSUE THREAD

**Issue by bebold-jhr** [hashicorp/terraform-provider-aws#25539]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.7
registry.terraform.io/hashicorp/aws v4.19.0

### Affected Resource(s)

* aws_ec2_transit_gateway_vpc_attachment

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ec2_transit_gateway_vpc_attachment" "this" {
  subnet_ids                                      = values(aws_subnet.attachment).*.id
  transit_gateway_id                              = data.aws_ec2_transit_gateway.this.id
  vpc_id                                          = aws_vpc.this.id
  ipv6_support                                    = "disable"
  transit_gateway_default_route_table_association = false
  transit_gateway_default_route_table_propagation = false
}
```

[terraform-provider-aws/examples/transit-gateway-cross-account-vpc-attachment](https://github.com/hashicorp/terraform-provider-aws/tree/main/examples/transit-gateway-cross-account-vpc-attachment) for remaining resources.

### Expected Behavior

No changes when executing plan after apply.

### Actual Behavior

Tries to set default route properties from `true` to `false` on each subsequent plan.
```
aws_ec2_transit_gateway_vpc_attachment.this will be updated in-place
  ~ resource "aws_ec2_transit_gateway_vpc_attachment" "this" {
        id                                              = "tgw-attach-#########"
      ~ transit_gateway_default_route_table_association = true -> false
      ~ transit_gateway_default_route_table_propagation = true -> false
        # (8 unchanged attributes hidden)
    }
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### References

* #0000

**Comment by ewbankkit** [comment]
@bebold-jhr Thanks for raising this issue.
It has already been noticed in #21438. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
