### ISSUE TITLE
Update the Terraform resource: AWS DMS Endpoints to include Oracle settings

### ISSUE THREAD

**Issue by eryklawyd** [hashicorp/terraform-provider-aws#25551]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
When you're configurating the AWS DMS endpoint by terraform there isn't any "tags" for **oracle_settings** like **s3_settings** for example.
To use endpoint settings "key: values" from terraform this must be configured on resource aws_dms_endpoint.

Many Oracle databases use ASM keys for security and Secret DB Encryption as default, so to pass this arguments using the terraform we need to update the resource **aws_dms_endpoint** for been like the doc of AWS.
Here the official doc AWS for creating a DMS endpoint by AWS CLI: https://docs.aws.amazon.com/cli/latest/reference/dms/create-endpoint.html 

Here the official doc Hasicorp for creating DMS endpoint:  by Terraform:  https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint

### New or Affected Resource(s)

* aws_dms_endpoint

### Potential Terraform Configuration

```hcl
resource "aws_dms_endpoint" "test" {
  database_name               = "test"
  endpoint_id                 = "test-dms-endpoint-tf"
  endpoint_type               = "source"
  engine_name                 = "oracle"
  extra_connection_attributes = "<this will be depecrated in future>"
  kms_key_arn                 = "arn:aws:kms:us-east-1:123456789012:key/12345678-1234-1234-1234-123456789012"
  secrets_manager_arn         = aws_secretsmanager_secret.example_secrets.arn
  secrets_manager_access_role_arn = "arn:aws:iam::123456789012:role/example-role-name"
  ssl_mode                    = "none"
  **oracle_settings** {
    add_supplemental_logging 	        =  boolean # true | false 
    archived_log_dest_id 	            =  integer # 123456
    additional_archived_log_dest_id 	=  integer # 123456
    extra_archived_log_dest_ids	        =  list # [ ]
    allow_select_nested_tables 	        =  boolean # true | false 
    parallel_asm_read_threads        	=  integer # 123456
    read_ahead_blocks 	                =  integer # 123456
    access_alternate_directly 	        =  boolean # true | false 
    use_alternate_folder_for_online	    =  boolean # true | false 
    oracle_path_prefix 	                = string # "example"
    use_path_prefix                  	= string # "example"
    replace_path_prefix 	            =  boolean # true | false 
    enable_homogenous_tablespace 	    =  boolean # true | false 
    direct_path_no_log 	                =  boolean # true | false 
    archived_logs_only 	                =  boolean # true | false 
    asm_password 	                    = string # "example"
    asm_server	                        = string # "example"
    asm_user 	                        = string # "example"
    char_length_semantics 	            = string # "example"
    database_name 	                    = string # "example"
    direct_path_parallel_load           =  boolean # true | false 
    fail_tasks_on_lob_truncation     	=  boolean # true | false 
    number_datatype_scale 	            =  integer # 123456
    password 	                        = string # "example"
    port                             	=  integer # 123456
    read_table_space_name 	            =  boolean # true | false 
    retry_interval 	                    =  integer # 123456
    security_db_encryption	            = string # "example"
    security_db_encryption_name	        = string # "example"
    server_name	                        = string # "example"
    standby_delay_time 	                =  integer # 123456
    username	                        = string # "example"
    use_b_file	                        =  boolean # true | false 
    use_direct_path_full_load	        =  boolean # true | false 
    use_logminer_reader	                =  boolean # true | false 
    secrets_manager_access_role_arn    	= string # "example"
    secrets_manager_secret_id       	= string # "example"
    secrets_manager_oracle_asm_access_role_arn 	= string # "example"
    secrets_manager_oracle_asm_secret_id	    = string # "example"
  }
  tags = {
    Name = "test"
  }
}
```

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint
https://docs.aws.amazon.com/cli/latest/reference/dms/create-endpoint.html
--->

* #0000

**Comment by ewbankkit** [comment]
@eryklawyd Thanks for raising this issue.
It has already been noticed in #20397. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
