### ISSUE TITLE
S3 logging - Error: Provider produced inconsistent final plan - ELB + terraform-aws-modules/s3-bucket + logging

### ISSUE THREAD

**Issue by good92** [hashicorp/terraform-provider-aws#25558]
### Terraform CLI and Terraform AWS Provider Version
Terraform CLI:  1.2.2 and 1.2.3 
AWS Provider Version: 4.19.0 and 4.20.0

using "terraform-aws-modules/s3-bucket/aws"
version = ">= 3.3.0"

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
  # S3 must have access logging enabled.
  logging = {
    target_bucket = module.logging_for_buckets.s3_bucket_id
    target_prefix = "log/${local.name_hyphened}-elbs-access-logs/"
  }
```

### Debug Output

│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.alb_external.aws_lb.this[0] to include
│ new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .access_logs[0].bucket: was cty.StringVal(""), but now
│ cty.StringVal("###-cluster-elbs-access-logs").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵

### Panic Output
Logs extract failure: ref: 1540444

2022-06-24T11:27:27.926Z [DEBUG] provider.terraform-provider-aws_v4.20.0_x5: [aws-sdk-go] <?xml version="1.0" encoding="UTF-8"?>
<PublicAccessBlockConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><BlockPublicAcls>true</BlockPublicAcls><IgnorePublicAcls>true</IgnorePublicAcls><BlockPublicPolicy>true</BlockPublicPolicy><RestrictPublicBuckets>true</RestrictPublicBuckets></PublicAccessBlockConfiguration>: timestamp=2022-06-24T11:27:27.926Z
module.logging_for_buckets.aws_s3_bucket_public_access_block.this[0]: Creation complete after 1s [id=cluster-buckets-access-logging]
2022-06-24T11:27:27.979Z [DEBUG] provider.terraform-provider-aws_v4.20.0_x5: [aws-sdk-go] DEBUG: Response s3/PutPublicAccessBlock Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 409 Conflict
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Fri, 24 Jun 2022 11:27:27 GMT
Server: AmazonS3
X-Amz-Id-2: #######################
X-Amz-Request-Id: #######################
-----------------------------------------------------: timestamp=2022-06-24T11:27:27.979Z
2022-06-24T11:27:27.980Z [DEBUG] provider.terraform-provider-aws_v4.20.0_x5: [aws-sdk-go] <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>OperationAborted</Code><Message>A conflicting conditional operation is currently in progress against this resource. Please try again.</Message><RequestId>#######################</RequestId><HostId>#######################</HostId></Error>: timestamp=2022-06-24T11:27:27.979Z
2022-06-24T11:27:27.980Z [DEBUG] provider.terraform-provider-aws_v4.20.0_x5: [aws-sdk-go] DEBUG: Validate Response s3/PutPublicAccessBlock failed, attempt 2/25, error OperationAborted: A conflicting conditional operation is currently in progress against this resource. Please try again.
	status code: 409, request id: ZA5J429G4GGQRRVQ, host id: #######################
timestamp=2022-06-24T11:27:27.979Z
2022-06-24T11:27:27.995Z [DEBUG] provider.terraform-provider-aws_v4.20.0_x5: [aws-sdk-go] DEBUG: Response s3/PutBucketEncryption Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 0
Date: Fri, 24 Jun 2022 11:27:28 GMT
Server: AmazonS3
X-Amz-Id-2: #######################
X-Amz-Request-Id: #######################

### Expected Behavior
Success

### Actual Behavior

Error: Provider produced inconsistent final plan

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

* #0000

**Comment by HyperMe1200** [comment]
Faced the same issue. It makes impossible to use bucket_prefix which is very important for S3.
