### ISSUE TITLE
`aws_emrcontainers_virtual_cluster` incorrect field validation

### ISSUE THREAD

**Issue by applike-ss** [hashicorp/terraform-provider-aws#25560]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
tf: 1.1.9
provider: 4.20.0

### Affected Resource(s)
* `aws_emrcontainers_virtual_cluster`

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.
```hcl
resource "aws_emrcontainers_virtual_cluster" "emr-on-eks" {
  container_provider {
    id   = module.eks_cluster.eks_cluster_id
    type = "EKS"

    info {
      eks_info {
        namespace = "emr"
      }
    }
  }

  name = "${var.environment}-name"
}
```

### Expected Behavior
import should be possible

### Actual Behavior
import throws output:
```
tf import aws_emrcontainers_virtual_cluster.emr-on-eks sandbox-name
aws_emrcontainers_virtual_cluster.emr-on-eks: Importing from ID "sandbox-name"...
aws_emrcontainers_virtual_cluster.emr-on-eks: Import prepared!
  Prepared aws_emrcontainers_virtual_cluster for import
aws_emrcontainers_virtual_cluster.emr-on-eks: Refreshing state... [id=sandbox-name]
╷
│ Error: reading EMR Containers Virtual Cluster (sandbox-name): ValidationException: 1 validation error detected: Value 'sandbox-name' at 'id' failed to satisfy constraint: Member must satisfy regular expression pattern: [0-9a-z]+
│ 
│ 
╵


```

### Steps to Reproduce
* terraform import aws_emrcontainers_virtual_cluster.emr-on-eks

### Important Factoids
The documentation for this resource in the import paragraph is also missing that you (obviously) want to supply the name in the example command.

### References
Please check api regex pattern for fields:

https://docs.aws.amazon.com/emr-on-eks/latest/APIReference/API_CreateVirtualCluster.html

**Comment by applike-ss** [comment]
@thehunt33r could you take a look? Sorry for directly pinging you, but it seems this issue does not get any attention and i saw that your PR was adding this resource.

**Comment by rajaie-sg** [comment]
Confirmed this exists with `registry.terraform.io/hashicorp/aws v4.21.0`

**Comment by rajaie-sg** [comment]
@applike-ss Looking into this a little more, it seems that the real bug here is the docs specifying that the import should be done with the `name`. Instead, the docs should say that the import needs to be done with the `id.

You can try running 

`aws emr-containers describe-virtual-cluster --id your-cluster-name`, you will get a similar failure that Terraform is throwing.

To import the cluster into Terraform, get the ID for your cluster with `aws emr-containers list-virtual-clusters` and then use the `id` field of the cluster.

**Comment by applike-ss** [comment]
since the describe-virtual-cluster sub command requires me to know the id already, i used `aws emr-containers list-virtual-clusters` and indeed then the import worked with `tf import aws_emrcontainers_virtual_cluster.cluster m.................`

**Comment by applike-ss** [comment]
So indeed there needs to be a fix in the docs to mention that it is not imported by the name, but rather the ID. 
As well the import statement at the bottom of the page needs to be fixed.

Should i leavee this one open for someone to add a pr?
