### ISSUE TITLE
resource/eip: Does not set default tags on Create

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#25567]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource

* aws_eip

### Description

If `default_tags` are set on the provider, but no tags are set on the `aws_eip` resource, tags are not set.

**Comment by sbocinec** [comment]
I tried with the `aws` provider version `4.22.0` and `4.26.0` and confirm the issue is present. I also noticed, when you run `terraform apply` second time, the tags are properly added - this is the only workaround I found to have the EIPs tagged, to apply the config twice.

**Comment by sbocinec** [comment]
I've just created [a PR with a fix proposal](https://github.com/hashicorp/terraform-provider-aws/pull/26308) for this issue - testing the fix using locally compiled provider binary helped me to fix the issue.
