### ISSUE TITLE
The latest (4.20.0) provider is breaking the aws_default_vpc_dhcp_options resource

### ISSUE THREAD

**Issue by absa-rsuarez** [hashicorp/terraform-provider-aws#25561]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform 1.1.6
AWS Provider Version: 4.20.0

### Affected Resource(s)

aws_default_vpc_dhcp_options

### Terraform Configuration Files

```
resource "aws_default_vpc_dhcp_options" "default_dhcp_options" {
  owner_id = data.aws_caller_identity.service_consumer_account.account_id
}
```

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

### Expected Behavior

Normal use of the resource

### Actual Behavior
```hcl
│ Error: Failed to decode resource from state
│ 
│ Error decoding "aws_default_vpc_dhcp_options.default_dhcp_options" from
│ previous state: missing expected [
╵
╷
│ Error: missing expected [
│ 
│   with aws_default_vpc_dhcp_options.default_dhcp_options,
│   on vpc.tf line 20, in resource "aws_default_vpc_dhcp_options" "default_dhcp_options":
│   20: resource "aws_default_vpc_dhcp_options" "default_dhcp_options" {
│ 
╵
plan: error: failed to plan Terraform configuration in .
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Locking the provider to 4.19.0 resolved the issue and the plan and apply were able to complete

### References

* #0000

**Comment by ewbankkit** [comment]
I can reproduce this with a new acceptance test case:

```console
% make testacc TESTARGS='-run=TestAccVPCDefaultVPCDHCPOptions_serial/v4.20.0_regression' PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccVPCDefaultVPCDHCPOptions_serial/v4.20.0_regression -timeout 180m
=== RUN   TestAccVPCDefaultVPCDHCPOptions_serial
=== RUN   TestAccVPCDefaultVPCDHCPOptions_serial/v4.20.0_regression
    vpc_default_vpc_dhcp_options_test.go:87: Step 2/2 error: Error running pre-apply refresh: exit status 1
        
        Error: missing expected [
        
          with aws_default_vpc_dhcp_options.test,
          on terraform_plugin_test.tf line 2, in resource "aws_default_vpc_dhcp_options" "test":
           2: resource "aws_default_vpc_dhcp_options" "test" {
        
    testing_new.go:73: Error retrieving state, there may be dangling resources: exit status 1
        Failed to marshal state to json: missing expected [
--- FAIL: TestAccVPCDefaultVPCDHCPOptions_serial (45.27s)
    --- FAIL: TestAccVPCDefaultVPCDHCPOptions_serial/v4.20.0_regression (45.27s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	49.169s
FAIL
make: *** [testacc] Error 1
```
