### ISSUE TITLE
VPC Endpoint Service "Primary DNS Name" unset issue

### ISSUE THREAD

**Issue by Roxyrob** [hashicorp/terraform-provider-aws#25579]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.2.2 on linux_amd64
registry.terraform.io/hashicorp/aws v4.20.1

### Affected Resource(s)

`aws_vpc_endpoint_service`

### Terraform Configuration Files

```hcl
resource "aws_vpc_endpoint_service" "this" {
  network_load_balancer_arns = [nlb_arn]
  acceptance_required = false
  private_dns_name    = "www.abc.net"
}
```

### Debug Output
none

### Panic Output
none

### Expected Behavior

**step2** should produce a **change** for **Private DNS name**
Previously Private DNS Name should be cleared

### Actual Behavior

**stape2** changes **nothing**
Previously **Private DNS Name set not changed/removed** (need to do that on AWS Console)

### Steps to Reproduce

```hcl

(Step1)
resource "aws_vpc_endpoint_service" "this" {
  network_load_balancer_arns = [nlb_arn]
  acceptance_required = false
  private_dns_name    = "www.abc.net"
}
terraform apply

(Step2)
resource "aws_vpc_endpoint_service" "this" {
  network_load_balancer_arns = [nlb_arn]
  acceptance_required = false
}
terraform apply
```

**Comment by ewbankkit** [comment]
##### v4.20.1:

https://github.com/hashicorp/terraform-provider-aws/blob/e624f5ee38669a68a545acdca21d26314472e03c/internal/service/ec2/vpc_endpoint_service.go#L282-L284

##### v4.19.0:

https://github.com/hashicorp/terraform-provider-aws/blob/e624f5ee38669a68a545acdca21d26314472e03c/internal/service/ec2/vpc_endpoint_service.go#L282-L284
