### ISSUE TITLE
AWS App Runner ObservabilityConfiguration resource support

### ISSUE THREAD

**Issue by yimipeng** [hashicorp/terraform-provider-aws#25575]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for AWS App Runner new top level resource ObservabilityConfiguration. (Released in 2022/4)

### New or Affected Resource(s)

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-observabilityconfiguration.html

* aws_apprunner_observabilityconfiguration

### Potential Terraform Configuration

aws_apprunner_observabilityconfiguration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-observabilityconfiguration.html
* https://docs.aws.amazon.com/apprunner/latest/dg/manage-configure-observability.html

**Comment by bschaatsbergen** [comment]
Done, removed draft status from the PR.

**Comment by yimipeng** [comment]
I do not see doc update in https://registry.terraform.io/providers/hashicorp/aws/latest/docs to include new resource. Can someone help catch it up? Thanks.

**Comment by bschaatsbergen** [comment]
> I do not see doc update in https://registry.terraform.io/providers/hashicorp/aws/latest/docs to include new resource. Can someone help catch it up? Thanks.

https://github.com/hashicorp/terraform-provider-aws/pull/25591#issuecomment-1170248983
