### ISSUE TITLE
 Error: string is required when create resource aws_default_vpc_dhcp_options

### ISSUE THREAD

**Issue by rollcabbage** [hashicorp/terraform-provider-aws#25581]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.2.3
on darwin_amd64

### Affected Resource(s)

* aws_default_vpc_dhcp_options

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl

module "my_module" {
  source = "../../modules/platform/default_vpc"
}

module "default_vpc" {
  source = "trussworks/destroy-default-vpc/aws"
  region = "ap-northeast-1"
  azs    = ["a", "c", "d"]
}
```

### Expected Behavior

terraform plan without error

### Actual Behavior

```
Error: Failed to decode resource from state
Error decoding
"module.my_module.module.default_vpc.aws_default_vpc_dhcp_options.default"
from previous state: string is required
Error: string is required
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Occurred after using v4.20.1

https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.20.1

issue #25562 also be experienced.

### References

* #25562

**Comment by rollcabbage** [comment]
@ewbankkit Thanks for your replay.

> which version of the Terraform AWS Provider was used

I used [v4.20.1](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.20.1)

Below is my tfstate.

```
{
      "module": "module. my_module.module.default_vpc",
      "mode": "managed",
      "type": "aws_default_vpc_dhcp_options",
      "name": "default",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "arn": "arn:aws:ec2:ap-northeast-1:*********:dhcp-options/dopt-0789ca4a7049f9141",
            "domain_name": "ap-northeast-1.compute.internal",
            "domain_name_servers": [
              "AmazonProvidedDNS"
            ],
            "id": "dopt-0789ca4a7049f9141",
            "netbios_name_servers": [],
            "netbios_node_type": "",
            "ntp_servers": [],
            "owner_id": "***********",
            "tags": {
              "Automation": "terraform",
              "Name": "default"
            },
            "tags_all": {
              "Automation": "terraform",
              "Name": "default"
            }
          },
          "sensitive_attributes": [],
          "private": "bnVsbA==",
          "dependencies": [
            "module. my_module.module.default_vpc.aws_default_vpc.default"
          ]
        }
      ]
    },
```

**Comment by ewbankkit** [comment]
@rollcabbage Thanks for the response.
The error you experienced will be just for those `aws_default_vpc_dhcp_options` resources created with **v4.20.0** of the Terraform Provider, before **v4.20.1** was available.
Due to the short time window that this bug could have been caused in and the fact that deleting an `aws_default_vpc_dhcp_options` resource doesn't delete the underlying AWS DHCP Options Set, just removes the Terraform resource from state, please remove the affected resource (e.g. `terraform destroy -target module.my_module.module.default_vpc.aws_default_vpc_dhcp_options.default`) and then create it again with **v4.20.1**.

**Comment by rollcabbage** [comment]
@ewbankkit  Thank you so much. I fixed this issue by your way.
