### ISSUE TITLE
Data Source for aws_iam_access_key

### ISSUE THREAD

**Issue by paunis** [hashicorp/terraform-provider-aws#25585]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The scenario: We need to create some AWS IAM user and access key in the process of creation of an EKS cluster. When there is an update in the cluster config and ran the TF a new aws_iam_access_key is created for the aws_iam_user and we get an error for exceeding quota for AccessKeyPerUser. The only way to skip this iam_access_key creation is by having a count attribute which is based on the condition if the access_key exists or not. But there is no aws_iam_access_key data source.

### New or Affected Resource(s)

aws_iam_access_key

### Potential Terraform Configuration

```hcl
data "aws_iam_access_key" "admin_user_key" {
  user_name = var.admin_user
}
resource "aws_iam_access_key" "admin_user_key" {
  count = data.aws_iam_access_key.admin_user_key.id != ""? 1 : 0
  user     = aws_iam_user.admin_user.name
  provider = aws.region
  status = var.status
  lifecycle {
    ignore_changes = all
  }
}
```

**Comment by kamilturek** [comment]
Given that a single user can have more than one IAM access key, the singular data source may be slightly indeterministic (we can only [get the last used key](https://docs.aws.amazon.com/IAM/latest/APIReference/API_GetAccessKeyLastUsed.html)). However, a plural data source `aws_iam_access_keys` (using [ListAccessKeys](https://docs.aws.amazon.com/IAM/latest/APIReference/API_ListAccessKeys.html) API action) with `user` as an argument might fulfill the requirement as well.

```terraform
data "aws_iam_access_keys" "admin_user_keys" {
  user = var.username
}
```

**Comment by tmatilai** [comment]
I made a PR to add the `aws_iam_access_keys` data source: #29278 

The condition in the issue PR description could be e.g.
```terraform
  count = length(data.aws_iam_access_keys.admin.access_keys) == 0 ? 1 : 0
```
