### ISSUE TITLE
Bug report: Provider produced inconsistent final plan for aws_cloudwatch_metric_alarm: invalid value for .tags_all

### ISSUE THREAD

**Issue by mjheitland** [hashicorp/terraform-provider-aws#25580]
Hi team,
when I set default_tags in the provider 

provider "aws" {
  default_tags {
    tags = {
      example          = "aws/alb/complete"
      "ops/managed-by" = "terraform"
    }
  }
}

and set later a calculated tag "Name" in aws_cloudwatch_metric_alarm 

  tags = merge(var.tags, {
    Name     = "${var.load_balancer_name}-rejected-connections"
  })

I am getting the following error message:

  Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.alb_cloudwatch.aws_cloudwatch_metric_alarm.alb_rejected_connections[0] to
│ include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an
│ invalid new value for .tags_all: new element "Name" has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

My code consists of three files (I've add ".txt" to the attachments as GitHub doesn't support all file extensions): 

```
my_folder\ 
|- alb\ 
    |- lb.tf
    |- examples\ 
        |- complete\ 
            |- main.tf
|- alb_clouwatch\ 
    |- module.tf
```
[lb.tf.txt](https://github.com/hashicorp/terraform-provider-aws/files/8990393/lb.tf.txt)
[main.tf.txt](https://github.com/hashicorp/terraform-provider-aws/files/8990394/main.tf.txt)
[module.tf.txt](https://github.com/hashicorp/terraform-provider-aws/files/8990395/module.tf.txt)

**Comment by mjheitland** [comment]
If I had just used a static name like

tags = merge(var.tags, {
Name = "rejected-connections" 
})

it would have worked.
So it really is the combination of setting default_tags on the provider AND adding a calculated tag later that comes from another resource.
This provider cannot cope with that setup.

**Comment by ajoga** [comment]
This issue looks similar or to duplicate https://github.com/hashicorp/terraform-provider-aws/issues/19583
