### ISSUE TITLE
Profile configuration takes precedence over environment variables 

### ISSUE THREAD

**Issue by kamaz** [hashicorp/terraform-provider-aws#25596]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.20.1

### Affected Resource(s)

* aws_organizations_account

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_organizations_account" "account" {
  name              = "Test"
  email             = "test@example.com"
  close_on_deletion = true
}
```

### Debug Output

```text
2022-06-28T08:25:13.153+0100 [WARN]  ValidateProviderConfig from "module.organisation.provider[\"registry.terraform.io/hashicorp/aws\"]" changed the config value, but that value is unused
2022-06-28T08:25:13.154+0100 [WARN]  provider.terraform-provider-aws_v4.20.1_x5: A Profile was specified along with the environment variables "AWS_ACCESS_KEY_ID" and "AWS_SECRET_ACCESS_KEY". The Profile is now used instead of the environment variable credentials. This may lead to unexpected behavior.: timestamp=2022-06-28T08:25:13.154+0100
2022-06-28T08:25:13.154+0100 [DEBUG] provider.terraform-provider-aws_v4.20.1_x5: Using profile from configuration: "default": timestamp=2022-06-28T08:25:13.154+0100
2022-06-28T08:25:13.155+0100 [INFO]  provider.terraform-provider-aws_v4.20.1_x5: Retrieved credentials from "SharedConfigCredentials: /Users/kamaz/.aws/credentials": timestamp=2022-06-28T08:25:13.155+0100
2022-06-28T08:25:13.155+0100 [DEBUG] provider.terraform-provider-aws_v4.20.1_x5: Trying to get account information via sts:GetCallerIdentity: timestamp=2022-06-28T08:25:13.155+0100
```

### Expected Behavior

According to the [Authentication and Configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#authentication-and-configuration) section of provider the `aws` provider should use environment variables over *shared configuration files*

### Actual Behavior

Uses *shared configuration file* instead of using environment variables.

Maybe worth adding if I downgrade to version `~> 3.0` all works as expected.

### Steps to Reproduce

1. Configure `default` credentials in by using `aws configure`
2. Create new credentials using `sts` with `MFA` and add them to the environment variables
3. Try creating resource and you will get following error

```text
│ Error: error creating AWS Organizations Account (xxxxx: AccessDeniedException: You don't have permissions to access this resource.
│
│   with module.organisation.aws_organizations_account.account,
│   on ../../modules/organization/main.tf line 6, in resource "aws_organizations_account" "account":
│    6: resource "aws_organizations_account" "account" {
```

**Comment by gdavison** [comment]
Hi @kamaz. From looking at the debug output, namely

```
A Profile was specified along with the environment variables "AWS_ACCESS_KEY_ID" and "AWS_SECRET_ACCESS_KEY". The Profile is now used instead of the environment variable credentials. This may lead to unexpected behavior.: timestamp=2022-06-28T08:25:13.154+0100
Using profile from configuration: "default": timestamp=2022-06-28T08:25:13.154+0100
```

it looks like you're specifying both a profile name in the provider configuration along with the environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`. In this case, the provider will prioritize values set in the provider configuration over environment variables. This is item #1 at https://registry.terraform.io/providers/hashicorp/aws/latest/docs#authentication-and-configuration.

If you don't have a profile set in the provider configuration block, can you please share how you've configured the provider?

**Comment by sabban** [comment]
Hi,

This is bad. Let me explain why.

We often use scm managed directory to handle the set of terraform files. Then provider configuration is one of them, and configured for most of the co-workers. We should be given a way to override this configuration to suit one's need, and environment variable is the perfect way as it is managed by the user launching terraform.

Regards,

**Comment by gdavison** [comment]
@kamaz, since you haven't responded, I assume that your problem is resolved.

@sabban, can you please create a new issue showing how you are configuring the provider?
