### ISSUE TITLE
aws_elasticache_user_group: User group needs to contain a user with the user name default.

### ISSUE THREAD

**Issue by LuPan2015** [hashicorp/terraform-provider-aws#25593]
terraform code:
```
resource "aws_elasticache_user_group" "this" {
  engine        = "REDIS"
  user_group_id = var.user_group_id
}
```
input
```
user_group_id = "test"
```
get error:
```
Error: creating ElastiCache User Group (test): DefaultUserRequired: User group needs to contain a user with the user name default.
│       status code: 400, request id: 98e0723e-13c0-4091-9df0-4b2fd12d3070
```

**Comment by justinretzolk** [comment]
Hey @LuPan2015 👋 Thank you very much for taking the time to raise this! Can you elaborate a bit on the issue that you're reporting so that we can look into it?

**Comment by jbod** [comment]
Hello,

Just happened to have the same issue here. It is not possible to create a group without the "default" user within.

In Terraform:
```
resource "random_password" "redis" {
  length = 32
}

resource "aws_elasticache_user" "redis" {
  user_id       = "myuser"
  user_name     = "My User"
  access_string = "on ~* +@all"
  engine        = "REDIS"
  passwords     = [random_password.redis.result]
}

resource "aws_elasticache_user_group" "redis" {
  engine        = "REDIS"
  user_group_id = "mygroup"
  user_ids      = [aws_elasticache_user.redis.user_id]
}
```
This fails with the following error:
```
│ Error: creating ElastiCache User Group (mygroup): DefaultUserRequired: User group needs to contain a user with the user name default.
│       status code: 400, request id: 23b9a797-a586-4173-bc71-eceecc54868d
│ 
```
Also attempted this, same error:
```
resource "aws_elasticache_user_group" "redis" {
  engine        = "REDIS"
  user_group_id = "mygroup"
}

resource "aws_elasticache_user_group_association" "redis" {
  user_group_id = aws_elasticache_user_group.redis.user_group_id
  user_id       = aws_elasticache_user.redis.user_id
}
```
However, this works:
```
resource "aws_elasticache_user_group" "redis" {
  engine        = "REDIS"
  user_group_id = "mygroup"
  user_ids      = [aws_elasticache_user.redis.user_id, "default"]
}
```

Something interesting to note is that the same error happens on the AWS Console! Just attempt to create a new User Group on ElastiCache, add some users but not the "default" user. This ends with an error "The user group needs to contain a user with the user name default." displayed when trying to click on the "Create" button. And the "default" user cannot be either deleted or modified...

It looks like the "default" user is required to be part of any User Group created in ElastiCache. On the Terraform side, this might end with a little note about that in the documentation. On the AWS side, even if the "default" user has no password set, I think this might be a security hole, as this user has full access to the database (`on ~* +@all`)...

Note that this is my first try with AWS, I don't have any past experience that could have confirmed a change of behavior on the AWS API about that...

Hope that helps!

**Comment by neidiom** [comment]
example in the terraform docs

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_user_group_association#example-usage

**Comment by justinretzolk** [comment]
Hey @LuPan2015 👋 Based on the additional comments here, it looks like the requirement to have a "default" user is expected behavior. With that, and the examples provided above in mind, I'm going to close this issue. If you feel I've done this in error, please do let me know.
