### ISSUE TITLE
aws_fsx_windows_file_system throughput and storage capacity increase

### ISSUE THREAD

**Issue by dtns2** [hashicorp/terraform-provider-aws#25607]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
~ % terraform -v
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.75.1
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
```

### Affected Resource(s)

* aws_fsx_windows_file_system

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_fsx_windows_file_system" "rds_storage" {
  tags    = {...}
  aliases = ["rds-storage.example.internal"]

  storage_type        = "SSD"
  storage_capacity    = 300
  throughput_capacity = 16
  active_directory_id = "xxxx"
  deployment_type     = "MULTI_AZ_1"
  subnet_ids          = ["xxxx","xxxx","xxxx"]
  preferred_subnet_id = "xxxx"
  security_group_ids  = ["xxxx","xxxx"]

  daily_automatic_backup_start_time = "01:23"
  weekly_maintenance_start_time     = "2:09:37"
}
```

### Expected Behavior

```
Terraform will perform the following actions:

  # aws_fsx_windows_file_system.rds_storage will be updated in-place
  ~ resource "aws_fsx_windows_file_system" "rds_storage" {
        id                                = "fs-xxxx"
      ~ storage_capacity                  = 32 -> 300
      ~ throughput_capacity               = 8 -> 16
        # (22 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

This should just work all in one sweep.

### Actual Behavior

```
│ Error: error updating FSx Windows File System (fs-0aad69af143b92d32): BadRequest: Unable to perform the storage capacity update. Updating storage capacity requires your file system to have at least 16 MB/s of throughput capacity.
│ 
│   with aws_fsx_windows_file_system.rds_storage,
│   on windows-jumphosts.tf line 262, in resource "aws_fsx_windows_file_system" "rds_storage":
│  262: resource "aws_fsx_windows_file_system" "rds_storage" {
```

It appears one has to first update the `throughput_capacity` in a separate `terraform apply`. Then, one can update the `storage_capacity` in a second `terraform apply`. 

### Steps to Reproduce

1. Create a `aws_fsx_windows_file_system` with:
    - `storage_capacity` = 32
    - `throughput_capacity` = 8
1. `terraform apply`
1. Update `aws_fsx_windows_file_system` to:
    - `storage_capacity` = 32 -> 300
    - `throughput_capacity` = 8 -> 16
1. Watch it fail

### Important Factoids

* The AWS FSX has a formula for determining what throughput is needed for certain capacity sizes. Meaning, to increase the capacity one will also have to increase the throughput at a certain point.
    * https://docs.aws.amazon.com/fsx/latest/WindowsGuide/performance.html 

### References

* #0000

**Comment by ewbankkit** [comment]
Similar: https://github.com/hashicorp/terraform-provider-aws/issues/20646.
