### ISSUE TITLE
Incorrect bucket reference in documentation for aws_s3_bucket_cors_configuration

### ISSUE THREAD

**Issue by mbacchi** [hashicorp/terraform-provider-aws#25604]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Minor documentation inconsistency related to the reference for the bucket in the `aws_s3_bucket_cors_configuration` resource [document](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_cors_configuration).

It currently indicates the bucket should be:

```
bucket = aws_s3_bucket.example.bucket
```

But just like all the other S3 resource documentation such as [aws_s3_bucket_lifecycle_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration), this should instead be:

```
bucket = aws_s3_bucket.example.id
```

**Comment by justinretzolk** [comment]
Hey @mbacchi 👋 Thank you for taking the time to raise this! I've opened a PR to switch over to using `id` so that we're consistent in our examples. While `bucket` _would_ work in this case, I agree that it's more idiomatic to use `id` instead.
