### ISSUE TITLE
add spread_level to aws_placement_group resource

### ISSUE THREAD

**Issue by silvaalbert** [hashicorp/terraform-provider-aws#25614]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Placement groups now support the 'SpreadLevel' parameter for Outposts. Requesting it's incorporation into the aws_placement_group resource.

### New or Affected Resource(s)

* aws_placement_group

### Potential Terraform Configuration

```hcl
resource "aws_placement_group" "web" {
  name     = "hunky-dory-pg"
  strategy = "cluster"
  spread_level = "host"
}
```

### References

* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreatePlacementGroup.html
* https://aws.amazon.com/about-aws/whats-new/2022/06/amazon-ec2-placement-groups-support-host-level-spread-aws-outposts-rack/

**Comment by silvaalbert** [comment]
I am currently working on this

**Comment by ewbankkit** [comment]
Requires [AWS SDK for Go v1.44.44](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.44): https://github.com/hashicorp/terraform-provider-aws/pull/25612.
