### ISSUE TITLE
Support Google Cloud Storage as a `aws_datasync_location`

### ISSUE THREAD

**Issue by antoinelyset** [hashicorp/terraform-provider-aws#25633]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello, this is my first feature request, I hope I won't make mistakes.

AWS DataSync [now supports](https://aws.amazon.com/blogs/aws/new-for-aws-datasync-move-data-between-aws-and-google-cloud-storage-or-aws-and-microsoft-azure-files/) Google Cloud Storage (and Microsoft Azure Files) as locations. It would be nice to have it in Terraform

### New or Affected Resource(s)

* aws_datasync_location

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

None

**Comment by bschaatsbergen** [comment]
I'll happily look into this for GCS.

**Comment by rickard-von-essen** [comment]
This is actually another type of resource and should be named `aws_datasync_location_objectstorage`. This is requested in #22533 (which this duplicates).

**Comment by johnjelinek** [comment]
This is implemented by https://github.com/hashicorp/terraform-provider-aws/pull/23154
