### ISSUE TITLE
Import aws_rds_cluster using a cluster_identifier_prefix forces replacement

### ISSUE THREAD

**Issue by jrobison-sb** [hashicorp/terraform-provider-aws#25634]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform --version
Terraform v1.2.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.13.0
```

### Affected Resource(s)

* aws_rds_cluster

### Terraform Configuration Files

```
resource "aws_rds_cluster" "warehouse" {
  cluster_identifier_prefix = "sandbox3-warehouse-20220630221641363100000002"

  # Note, I also tried it like this, but with no different results:
  # cluster_identifier_prefix = "sandbox3-warehouse-"
  ...
}
```

### Debug Output

NA

### Panic Output

NA

### Expected Behavior

If I import an RDS cluster where the Terraform code uses `cluster_identifier_prefix` as seen above, and the deployed resource that I import uses the above identifier, Terraform should import the resource and not propose recreating it on the next plan/apply cycle.

### Actual Behavior

If I import an RDS cluster where the Terraform code uses `cluster_identifier_prefix` as seen above, and the deployed resource that I import uses the above identifier, Terraform does propose recreating it on the next plan/apply cycle.

### Steps to Reproduce

1. Create an RDS cluster out of band from Terraform, and give it an identifier of `sandbox3-warehouse-20220630221641363100000002`.
2. Write the terraform code seen above, using `cluster_identifier_prefix`, and not using `cluster_identifier`.
3. Import the cluster into the management of Terraform
4. Run a plan and see that Terraform wants to recreate the resource.

```
  # module.sandbox3_application.aws_rds_cluster.warehouse[0] must be replaced
-/+ resource "aws_rds_cluster" "warehouse" {
      ...
      ~ cluster_identifier                  = "sandbox3-warehouse-20220630221641363100000002" -> (known after apply)
      + cluster_identifier_prefix           = "sandbox3-warehouse-20220630221641363100000002" # forces replacement
      ...
}
```

### Important Factoids

NA

### References

NA

**Comment by max-rocket-internet** [comment]
I have the same problem. Here's an annoying workaround...

1. Run `terraform state pull > state.json`
2. Open the `state.json` and search for the attribute `cluster_identifier_prefix`, it will be `null`
3. Set `cluster_identifier_prefix` to the original prefix, this string will be the non-number part of the `cluster_identifier` attribute.
4. Save the file and run `terraform state push state.json`

**Comment by max-rocket-internet** [comment]
This problem actually effects many resources, details in https://github.com/hashicorp/terraform-provider-aws/issues/9574
