### ISSUE TITLE
Impossible to select a metric arn for an alarm ?

### ISSUE THREAD

**Issue by neogeogre** [hashicorp/terraform-provider-aws#25653]
### Terraform CLI and Terraform AWS Provider Version

```shell
Terraform v1.2.2
on linux_amd64
```
### Affected Resource(s)

* aws_cloudwatch_metric_alarm

### Terraform Configuration Files

```hcl
resource "aws_cloudwatch_metric_alarm" "certificate-expiration-alarm" {
  alarm_name          = "certificate-expiration"
  comparison_operator = "LessThanOrEqualToThreshold"
  period              = "86400"
  evaluation_periods  = "1"
  threshold           = "150"
  namespace           = "AWS/CertificateManager"
  metric_name         = "DaysToExpiry"
  statistic           = "Average"
  alarm_description   = "This metric monitors certificate expiration"
  actions_enabled     = "true"
  alarm_actions       = [
    aws_sns_topic.certificate-alarm.arn
  ]
}
```

### Expected Behavior

By creating an alarm in cloud watch manually I can have something like:

![expected](https://user-images.githubusercontent.com/20304426/176912632-a6778707-09b5-4bc5-a1f0-75367d1fd595.png)

### Actual Behavior

By creating an alarm via terraform I cannot select on what to apply the alarm (the certificate Arn in this case):

![current1](https://user-images.githubusercontent.com/20304426/176914264-253fbb76-a786-4f1d-abff-67c5b4cedf56.png)

### Steps to Reproduce

According to the documentation there is no way to select a specific metric arn, just the namespace and the metric name:
 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_metric_alarm#threshold

So this aws UI button action is not possible via terraform:

![select](https://user-images.githubusercontent.com/20304426/176914630-45f3184d-66c4-4e90-92c7-663c0f465874.png)

**Comment by justinretzolk** [comment]
Hey @neogeogre 👋 Thank you for taking the time to raise this! I believe what you're looking for is the [`dimensions` argument](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_metric_alarm#dimensions). The information regarding CloudWatch metrics for ACM may be found in [this AWS document](https://docs.aws.amazon.com/acm/latest/userguide/cloudwatch-metrics.html). That configuration would look something like this (based on your provided example):

```hcl
resource "aws_cloudwatch_metric_alarm" "certificate-expiration-alarm" {
  alarm_name          = "certificate-expiration"
  comparison_operator = "LessThanOrEqualToThreshold"
  period              = "86400"
  evaluation_periods  = "1"
  threshold           = "150"
  namespace           = "AWS/CertificateManager"
  metric_name         = "DaysToExpiry"
  statistic           = "Average"
  alarm_description   = "This metric monitors certificate expiration"
  actions_enabled     = "true"
  alarm_actions       = [
    aws_sns_topic.certificate-alarm.arn
  ]
  dimensions = {
    CertificateArn = <arn_goes_here>
  }
}
```

**Comment by neogeogre** [comment]
Ha ok!
Thank you very much it's not super obvious from the doc.
