### ISSUE TITLE
aws_acmpca_certificate_authority causes panic if revocation_configuration is specified but empty

### ISSUE THREAD

**Issue by MJDrgn** [hashicorp/terraform-provider-aws#25674]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_acmpca_certificate_authority

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_acmpca_certificate_authority" "root" {
  type = "ROOT"
  enabled = true

  certificate_authority_configuration {
    key_algorithm     = "RSA_4096"
    signing_algorithm = "SHA512WITHRSA"

    subject {
      common_name = "domain.example"
      country = "NZ"
    }
  }

  revocation_configuration {

  }

  permanent_deletion_time_in_days = 30
}
```

### Panic Output

Stack trace from the terraform-provider-aws_v3.75.2_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 134 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/acmpca.expandAcmpcaRevocationConfiguration(0xc0021725e0, 0x1, 0x1, 0x8269b00)
	github.com/hashicorp/terraform-provider-aws/internal/service/acmpca/certificate_authority.go:636 +0x137
github.com/hashicorp/terraform-provider-aws/internal/service/acmpca.resourceCertificateAuthorityCreate(0xc0005c5c00, 0x9061800, 0xc00001b500, 0x2, 0xffffffffffffffff)
	github.com/hashicorp/terraform-provider-aws/internal/service/acmpca/certificate_authority.go:305 +0x26c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000aaec40, 0xb3a6e58, 0xc000a4eec0, 0xc0005c5c00, 0x9061800, 0xc00001b500, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:329 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000aaec40, 0xb3a6e58, 0xc000a4eec0, 0xc000379e10, 0xc0005c5a00, 0x9061800, 0xc00001b500, 0x0, 0x0, 0x0, ...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00059a048, 0xb3a6e58, 0xc000a4eec0, 0xc002239db0, 0xa3f41d7, 0x12, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xacf
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000334b00, 0xb3a6f00, 0xc000a4eec0, 0xc0001b8cb0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x465
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xa14f3c0, 0xc000334b00, 0xb3a6f00, 0xc002456ae0, 0xc0008afe60, 0x0, 0xb3a6f00, 0xc002456ae0, 0xc0022baa00, 0x4ca)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000edb180, 0xb3d4938, 0xc000362600, 0xc002946300, 0xc0017c4030, 0x1005ee00, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000edb180, 0xb3d4938, 0xc000362600, 0xc002946300, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0012128c0, 0xc000edb180, 0xb3d4938, 0xc000362600, 0xc002946300)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

### Expected Behavior

Default configuration for the revocation_configuration block was used, OR a parse error was displayed

### Actual Behavior

terraform crashes with a stack trace

### Steps to Reproduce

1. Define a aws_acmpca_certificate_authority with an empty revocation_configuration block inside.
2. `terraform apply`

**Comment by mattburgess** [comment]
Confirmed with the latest 4.21.0  release; I'll take a look at a fix.
