### ISSUE TITLE
AWS App Runner ObservabilityConfiguration setup

### ISSUE THREAD

**Issue by Nighthawk14** [hashicorp/terraform-provider-aws#25677]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A new `aws_apprunner_observability_configuration` was added as part of release 4.21.0 (https://github.com/hashicorp/terraform-provider-aws/pull/25591). However the configuration inside the main aws_apprunner_service is missing to apply the observability configuration to the service. So the current feature only allows us to create observability configurations without using them.

### New or Affected Resource(s)

* aws_apprunner_service

### Potential Terraform Configuration

```hcl
resource "aws_apprunner_service" "example" {
  observability_configuration_arn = "..."
}
```

### References

* [#25575](https://github.com/hashicorp/terraform-provider-aws/issues/25575)

**Comment by bschaatsbergen** [comment]
As I picked up the creation of the observability configuration I'll jump onto supporting this too.
