### ISSUE TITLE
aws_ce_anomaly_subscription type of subscriber address must be a "list"

### ISSUE THREAD

**Issue by voksaymd** [hashicorp/terraform-provider-aws#25685]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In a "subscription" in AWS Cost Anomaly Detection consol I can use up to 10  email addresses:
  "Alert recipients
   Use a comma to separate between email addresses. You can have up to 10 email recipients."
But in aws_ce_anomaly_subscription type of variable "address" is a "string". Must be a list(string).
@brittandeyoung

### New or Affected Resource(s)

aws_ce_anomaly_subscription

### Potential Configuration

```hcl
			"subscriber": {
				Type:     schema.TypeSet,
				Required: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"address": {
							Type:     schema.TypeList,
							Required: true,
						},
```

### References

#25224
#16137

**Comment by voksaymd** [comment]
@brittandeyoung  thanks for good example with multiple subscriber blocks! This resolve my problem, because I was'nt understant how to add several email addresses for one subscription.. For example I also use resourse aws_budgets_budget, that also has similar subscription, and email addresses are passed easily as a list(string).
Yes, a documentation update with an example of multiple subscribers  will be great!

**Comment by voksaymd** [comment]
Another question(probblem). I wrote a terraform module for CostAnomalyDeteсtion and I have many AWS accounts in AWS Organisation. Every account has a self terraform directory and use this module. Module has variables.tf with default values. Module example:
```hcl
resource "aws_ce_anomaly_monitor" "service_monitor" {
  name                         = var.cad_name
  monitor_type             = var.cad_monitor_type
  monitor_dimension    = var.cad_monitor_dimension
}

resource "aws_ce_anomaly_subscription" "my_test_subscr" {
    name                 = var.cad_subscr_name
    threshold           = var.cad_subscr_threshold
    frequency          = var.cad_subscr_frequency
    monitor_arn_list = [resource.aws_ce_anomaly_monitor.service_monitor.arn]
    subscriber {
        address = var.cad_subscr_address
        type       = var.cad_subscr_type
    }
    subscriber {
        address = var.cad_subscr_address_1
        type       = var.cad_subscr_type_1
    }
}
```

Example of usage:
```hcl
module "cad" {
  source = "./cad_mod"
  cad_subscr_address  = "***@gmail.com"
}
```
Some accounts have 1 subscription email, others have 2 subscription emails. In this case 1 email is a problem, because terraform expects "required" second subscriber variables. I tried to use "null" values, but not working. How to easily resolve this situation?

**Comment by DrFaust92** [comment]
[voksaymd](https://github.com/voksaymd) you can use dynamic to create an n number of subscriber blocks. as this is not and issue with the provider and the question was answered im closing this ticket
