### ISSUE TITLE
AWS Transfer SFTP Internet Facing

### ISSUE THREAD

**Issue by z-mani** [hashicorp/terraform-provider-aws#25682]
---
name: 🚀 Feature Request
about: I have a suggestion (and might want to implement myself 🙂)!
labels: enhancement
---

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I’m setting up an SFTP server using Terraform in AWS. I am wanting to set VPC type SFTP server to use internet facing. When manually setting this up in AWS using the Console UI, there is an option to use internet facing or internal. In Terraform, there doesn't seem to be an option to specify internet facing or internal, instead it just defaults to internal.

I would like this feature to be added into the resource aws_transfer_server so that we can have an option of enabling internet facing for an SFTP server using VPC as the endpoint type.

Thanks

### New or Affected Resource(s)

* aws version 4.18.0

### Potential Terraform Configuration

```hcl
resource "aws_security_group" "sftp_vpc" {
  count       = var.sftp_type == "VPC" && lookup(var.endpoint_details, "security_group_ids", null) == null ? 1 : 0
  name        = "sftp-vpc-${var.sftp_server_name}"
  description = "Security group for SFTP VPC"
  vpc_id      = lookup(var.endpoint_details, "vpc_id")

  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = var.ingress_cidr_block
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = var.egress_cidr_block
  }
}

resource "aws_eip" "sftp_vpc" {
  count = var.sftp_type == "VPC" && lookup(var.endpoint_details, "address_allocation_ids", null) == null ? length(lookup(var.endpoint_details, "subnet_ids")) : 0
  vpc   = true
  tags  = var.tags
}

resource "aws_transfer_server" "vpc" {
  endpoint_type = var.sftp_type
  protocols     = var.protocols
  certificate   = var.certificate_arn

  endpoint_details {
    vpc_id                 = lookup(var.endpoint_details, "vpc_id", null)
    vpc_endpoint_id        = lookup(var.endpoint_details, "vpc_endpoint_id", null)
    subnet_ids             = lookup(var.endpoint_details, "subnet_ids", null)
    security_group_ids     = lookup(var.endpoint_details, "security_group_ids", aws_security_group.sftp_vpc.*.id)
    address_allocation_ids = lookup(var.endpoint_details, "address_allocation_ids", aws_eip.sftp_vpc.*.allocation_id)
  }

  identity_provider_type = var.identity_provider_type
  url                    = var.api_gw_url
  invocation_role        = var.invocation_role
  directory_id           = var.directory_id
  function               = var.function_arn

  logging_role         = var.logging_role == null ? join(",", aws_iam_role.logging.*.arn) : var.logging_role
  force_destroy        = var.force_destroy
  security_policy_name = var.security_policy_name
  host_key             = var.host_key

  tags = merge({
    Name = var.sftp_server_name
  }, var.tags)
}

locals {
  server_id = var.sftp_type == "PUBLIC" ? join(",", aws_transfer_server.public.*.id) : join(",", aws_transfer_server.vpc.*.id)
  server_ep = var.sftp_type == "PUBLIC" ? join(",", aws_transfer_server.public.*.endpoint) : join(",", aws_transfer_server.vpc.*.endpoint)
}
```

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @z-mani 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description with the information requested in the [feature request template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Feature_Request.md?plain=1)?

**Comment by z-mani** [comment]
@justinretzolk Hi Justin, I have added some more info including Terraform config! Thanks

**Comment by justinretzolk** [comment]
Related #20927

Hey @z-mani 👋 I stumbled across this again while doing some triaging, and happened across the issue I linked above. I'm _actually_ linking it here for tracking, but I wanted to give you a heads up that there's a comment on that issue that might help you out as well (though you seem to be passing the argument they mentioned, so your mileage may vary).

**Comment by ewbankkit** [comment]
[User Guide](https://docs.aws.amazon.com/transfer/latest/userguide/create-server-in-vpc.html#create-internet-facing-endpoint).

**Comment by ewbankkit** [comment]
See https://github.com/hashicorp/terraform-provider-aws/issues/20927#issuecomment-957687360.
