### ISSUE TITLE
apply_immediately missing default

### ISSUE THREAD

**Issue by janboll** [hashicorp/terraform-provider-aws#25711]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/aws v3.75.2
```

### Affected Resource(s)

* aws_db_instance

### Terraform Configuration Files

Setting apply_immediately to true:
```hcl
resource "aws_db_instance" "default" {
    allocated_storage    = 10
    engine ="postgres"
    engine_version = "12.8"
    apply_immediately = true
    instance_class       = "db.t3.micro"
    name                 = "test"
    username             = "test"
    password             = "foobarbaz"
    parameter_group_name = "default.postgres12"
    skip_final_snapshot  = true
    db_subnet_group_name =  "app-sre-stage-rds-subnet-group"
}
```

Removing it:
```hcl
resource "aws_db_instance" "default" {
    allocated_storage    = 10
    engine ="postgres"
    engine_version = "12.9"
    instance_class       = "db.t3.micro"
    name                 = "test"
    username             = "test"
    password             = "foobarbaz"
    parameter_group_name = "default.postgres12"
    skip_final_snapshot  = true
    db_subnet_group_name =  "app-sre-stage-rds-subnet-group"
}
```
### Debug Output

See following plan, it shows apply_immediately is set to true even though I did not set it anymore:

```
  # aws_db_instance.default will be updated in-place
  ~ resource "aws_db_instance" "default" {
...
        apply_immediately                     = true
...
      ~ engine_version                        = "12.8" -> "12.9"

```

### Expected Behavior

I would have expected that the setting is set to false if it is not set, as explained in the documentation

### Actual Behavior

apply_immediately is set to the last set value. If for instance, I set it manually to false in the statefile, the plan will set it to false as well.

**Comment by kwilczynski** [comment]
Hi @ewbankkit, sorry to summon you out of the blue here! I wanted to ask whether it would be possible for you to pick this for the next release and also, if possible, as a back-port to the [v3.75.3](https://github.com/hashicorp/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+milestone%3Av3.75.3)?

This problem has a really tiny fix. However, without it, I have seen this race with AWS' API on occasion, which leads to some odd semantics when applying changes against an RDS instance. Thus, this is borderline somewhere between annoying behaviour and potentially dangerous.

What do you think? Would it be possible to get this in? I would be very grateful, plus I am sure some other users have issues with this now and then too.
