### ISSUE TITLE
S3 FIPS Endpoint not working with latest AWS Provider

### ISSUE THREAD

**Issue by kjenney** [hashicorp/terraform-provider-aws#25717]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.21.0
```

### Affected Resource(s)

* aws_s3_bucket
* aws_s3_bucket_acl

### Terraform Configuration Files

To reproduce the issue:

1. Clone my git repo `git clone https://github.com/kjenney/terraform-aws-fips-s3-broken` or copy the code below.
2. Run `terraform init`
3. Run `terrafform apply`

```hcl
 variable "use_fips_endpoint" {
  description = "Whether to use FIPS endpoints for AWS API requests"
  default     = "true"
}

provider "aws" {
  use_fips_endpoint = var.use_fips_endpoint == "true" ? true : false
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.21.0"
    }
  }
  required_version = "~> 1.1.0"
}

resource "aws_s3_bucket" "b" {
  bucket = "my-tf-test-bucket.myawesomeexample.com"

  tags = {
    Name        = "My bucket"
    Environment = "Dev"
  }
}

resource "aws_s3_bucket_acl" "example" {
  bucket = aws_s3_bucket.b.id
  acl    = "private"
}

```

### Debug Output

Debug Output in Gist: https://gist.github.com/kjenney/bec38f66def81500df5719232f526428

### Expected Behavior

The bucket would be created/provisioned with the ACL.

### Actual Behavior

Nothing was created/provisioned.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @kjenney 👋 Thank you for taking the time to raise this! I see from the repo that you linked that you're using a proxy, and the errors seem to be DNS related. Given that we've not seen an influx of reports of similar issues, would it be possible to test without the proxy to see if you encounter the same issues?

**Comment by kjenney** [comment]
NSLookup can not find it either - which makes sense:

```
$ nslookup s3-fips.us-east-1.amazonaws.com
Server:		10.130.12.25
Address:	10.130.12.25#53

Non-authoritative answer:
*** Can't find s3-fips.us-east-1.amazonaws.com: No answer
```

**Comment by kjenney** [comment]
I'm checking with AWS support right now as this does not seem to be a Terraform issue.

**Comment by kjenney** [comment]
I just got off of a call with AWS support. Apparently you can't create an S3 bucket with the FIPS endpoint.  So you'd need to use a separate provider for say aws_s3_bucket_object  (fips) vs aws_s3_bucket (standard).
