### ISSUE TITLE
new feature instance_requirements for aws_autoscaling_group not working

### ISSUE THREAD

**Issue by tarp2699** [hashicorp/terraform-provider-aws#25728]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform version 1.2.4
Terraform AWS Provider 4.21.0

### Affected Resource(s)

* aws_autoscaling_group

### Terraform Configuration Files
```hcl
data "aws_ssm_parameter" "ecs_ami" {
  name = "/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id"
}

data "template_file" "cluster_user_data" {
  template = file("user-data/user-data.tpl")

  vars = {
    cluster_name       = local.cluster_name
    metricbeat_version = var.metricbeat_version
    filebeat_version   = var.filebeat_version
  }
}

resource "aws_launch_template" "cluster_launch_template" {
  name                                 = "${local.cluster_name}_launch_template"
  image_id                             = data.aws_ssm_parameter.ecs_ami.value
  instance_type                        = "c5.large"
  instance_initiated_shutdown_behavior = "terminate"
  user_data                            = base64encode(data.template_file.cluster_user_data.rendered)
  key_name                             = var.key_name

  vpc_security_group_ids = [
    aws_security_group.ephemeral_ports.id,
    var.deere_network_ssh
  ]

  iam_instance_profile {
    name = "IsgopsEC2ContainerServiceforEC2Role"
  }

  monitoring {
    enabled = true
  }

  tag_specifications {
    resource_type = "instance"
    tags           = local.default_tags
  }

  tag_specifications {
    resource_type = "volume"
    tags           = local.default_tags
  }

  tags = local.default_tags
}

resource "aws_autoscaling_group" "cluster_asg" {
  name                  = "${local.cluster_name}_asg"
  max_size              = local.asg_max
  min_size              = local.asg_min
  availability_zones    = ["us-east-1d"]

  mixed_instances_policy {
    launch_template {
      launch_template_specification {
        launch_template_id = aws_launch_template.cluster_launch_template.id
        version            = aws_launch_template.cluster_launch_template.latest_version
      }

      override {
        instance_requirements {
          memory_mib {
            min = 4000
            max = 512000
          }
          vcpu_count {
            min = 4
          }
        }
      }
    }
  }

  tags = [
    {
      key                 = "component"
      value               = local.cluster_name
      propagate_at_launch = true
    },
    {
      key                 = "Name"
      value               = local.cluster_name
      propagate_at_launch = true
    },
  ]
}
```

### Expected Behavior

The new feature for implementing instance_requirements isn't working.  It's complaining about the error below, but that is not set.  The example I included is almost directly from your documentation.  One note is there is an existing ASG group that it's modifying.  Could that be the issue?

### Actual Behavior

╷
│ Error: updating Auto Scaling Group (isgops-ecs-cluster_asg): ValidationError: Invalid input for OnDemandAllocationStrategy. The prioritized allocation strategy is not compatible with Instance Requirements.
│ 	status code: 400, request id: a7cc53c4-8cec-4fa2-a5c7-8a90a408bba7
│ 
│   with aws_autoscaling_group.cluster_asg,
│   on asg.tf line 49, in resource "aws_autoscaling_group" "cluster_asg":
│   49: resource "aws_autoscaling_group" "cluster_asg" {
│ 
╵

### Steps to Reproduce

1. `terraform apply`

### References

* #0000
[logs_ISGAWSSupport_ecs-cluster_206_1_5.log](https://github.com/hashicorp/terraform-provider-aws/files/9064590/logs_ISGAWSSupport_ecs-cluster_206_1_5.log)

**Comment by sauryadas** [comment]
@tarp2699 Based on the error message below, it looks like you are trying to use Attribute-based instance type selection with an incompatible ‘prioritized’ On-Demand allocation strategy. Attribute-based instance type selection is only compatible with ‘lowest-price’ On-Demand allocation strategy. Setting that strategy should resolve the issue. Documentation for reference - https://docs.aws.amazon.com/autoscaling/ec2/userguide/create-asg-instance-type-requirements.html#use-attribute-based-instance-type-selection-limitations

**Comment by tarp2699** [comment]
@sauryadas, I appreciate the comment, I'm not using on-demand but yet I need to define an on-demand allocation strategy.  Once I did that it works as expected.
TF, this looks like the documentation just needs to be gone through.
