### ISSUE TITLE
Redshift FIPS Endpoint resolving to an incorrect endpoint the latest Provider

### ISSUE THREAD

**Issue by kjenney** [hashicorp/terraform-provider-aws#25732]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

$ terraform -v
Terraform version: 0.13.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.21.0

### Affected Resource(s)

* aws_redshift_cluster

### Terraform Configuration Files

```hcl
variable "use_fips_endpoint" {
  description = "Whether to use FIPS endpoints for AWS API requests"
  default     = "true"
}

provider "aws" {
  use_fips_endpoint = var.use_fips_endpoint == "true" ? true : false
}

resource "aws_redshift_cluster" "example" {
  cluster_identifier = "tf-redshift-cluster"
  database_name      = "mydb"
  master_username    = "exampleuser"
  master_password    = "Mustbe8characters"
  node_type          = "dc1.large"
  cluster_type       = "single-node"
}
```

### Debug Output

GIST Debug Output: https://gist.github.com/kjenney/4cfcc44482e1720d4e96340e8cb1d7d5

### Expected Behavior

Redshift Cluster is provisioned and Terraform exits with status code 0.

### Actual Behavior

Terraform shows and error, does not provision the redshift cluster, and exists with status code 1.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids

Running in us-gov-west-1

### References

The AWS FIPS documentation has the Redshift endpoint listed at redshift.us-gov-west-1.amazonaws.com while Terraform is trying to reach it at redshift-fips.us-gov-west-1.amazonaws.com.

* #0000

**Comment by kjenney** [comment]
A workaround is to override the endpoint:

```
provider "aws" {
  use_fips_endpoint = var.use_fips_endpoint == "true" ? true : false
  endpoints {
    redshift = "https://redshift.us-gov-west-1.amazonaws.com"
  }
}
```

**Comment by ewbankkit** [comment]
Similar(ish): https://github.com/hashicorp/terraform-provider-aws/issues/25717.
