### ISSUE TITLE
Documentation issue: AWS Cloudtrail Event Data Store docs contradictory on what's required

### ISSUE THREAD

**Issue by douglasnaphas** [hashicorp/terraform-provider-aws#25730]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

AWS Cloudtrail Event Data Store

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail_event_data_store

* aws_cloudtrail_event_data_store

### Terraform Configuration Files

The docs say:

> The most simple event data store configuration requires us to only set the name and retention_period attributes.

But they also say:

> [advanced_event_selector](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail_event_data_store#advanced_event_selector) - (Required) The advanced event selectors to use to select the events for the data store. For more information about how to use advanced event selectors, see [Log events by using advanced event selectors](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-data-events-with-cloudtrail.html#creating-data-event-selectors-advanced) in the CloudTrail User Guide.

and

> [retention_period](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail_event_data_store#retention_period) - (Optional) The retention period of the event data store, in days. You can set a retention period of up to 2555 days, the equivalent of seven years. Default: 2555

The docs should consistently say what is required and what is optional. All parts of the docs for this resource should agree with the Argument Reference.

```hcl
resource "aws_cloudtrail_event_data_store" "example" {
  name             = "example-event-data-store"
  retention_period = 7
}
```

![Screen Shot 2022-07-07 at 11 26 19 AM](https://user-images.githubusercontent.com/5433410/177811742-f786d06f-19d5-4aaa-848e-448339beba8d.png)
![Screen Shot 2022-07-07 at 11 26 42 AM](https://user-images.githubusercontent.com/5433410/177811744-f34d6f34-29cf-467a-9f5e-68fe25e3f26d.png)
![Screen Shot 2022-07-07 at 11 26 33 AM](https://user-images.githubusercontent.com/5433410/177811746-012c506c-0e93-4601-9cc3-8c9325897361.png)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @douglasnaphas 👋 Thank you for taking the time to raise this! I'll work on a PR to get the documentation corrected.
