### ISSUE TITLE
4.22.0 -> Error: timeout while waiting for plugin to start

### ISSUE THREAD

**Issue by deutmeyerbrianpfg** [hashicorp/terraform-provider-aws#25748]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
 TF: 1.1.9
Provider 4.22.0

### Affected Resource(s)

Unknown.  After pulling in the lastest 4.22.0 release, our pipeline started failing with `Error: timeout while waiting for plugin to start`.  

### Expected Behavior

The plan should run.

### Actual Behavior

```
Releasing state lock. This may take a few moments...
Error: timeout while waiting for plugin to start

Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

### Steps to Reproduce

terraform plan

### Important Factoids

This just started with the 4.22.0 bump.

**Comment by justinretzolk** [comment]
Hey @deutmeyerbrianpfg 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you supply debug logs (redacted as needed) as well?

**Comment by deutmeyerbrianpfg** [comment]
The issue is sporadic and the trace outputs weren't valuable.  Closing for now.
