### ISSUE TITLE
Can't upload an object immediately after creating an S3 bucket

### ISSUE THREAD

**Issue by fabricetriboix** [hashicorp/terraform-provider-aws#25747]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```sh
$ terraform -v
Terraform v1.2.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.22.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
```

### Affected Resource(s)

* aws_s3_bucket
* aws_s3_object

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

locals {
  bucket_name = "mybucket-yadi-yada"
}

resource "aws_s3_bucket" "bucket" {
  bucket = local.bucket_name
}

resource "aws_s3_object" "file" {
  bucket = local.bucket_name
  key = "hello.txt"
  content = "Hello, World!"
}
```

### Debug Output

```
aws_s3_object.file: Creating...
aws_s3_bucket.bucket: Creating...
aws_s3_bucket.bucket: Creation complete after 3s [id=mybucket-yadi-yada-4]
╷
│ Error: Error uploading object to S3 bucket (mybucket-yadi-yada-4): NoSuchBucket: The specified bucket does not exist
│ 	status code: 404, request id: NW5JQS0N7ZG9F6NY, host id: g1nvaj595VL29vJa4d4HToc/YKvbBVFTK9mIRPIMWlgMH3a7Kdgi2K5zDejjfFO55OmPhsHln5c=
│ 
│   with aws_s3_object.file,
│   on test1.tf line 24, in resource "aws_s3_object" "file":
│   24: resource "aws_s3_object" "file" {
```

### Expected Behavior

Terraform should create the S3 object.

### Actual Behavior

Terraform does not create the S3 object, complaining that the S3 bucket does not exist.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids

The workaround is to introduce a delay before the S3 object is created:

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

locals {
  bucket_name = "mybucket-yadi-yada"
}

resource "aws_s3_bucket" "bucket" {
  bucket = local.bucket_name
}

resource "time_sleep" "wait_for_bucket" {
  depends_on = [aws_s3_bucket.bucket]
  create_duration = "30s"
}

resource "aws_s3_object" "file" {
  depends_on = [time_sleep.wait_for_bucket]
  bucket = local.bucket_name
  key = "hello.txt"
  content = "Hello, World!"
}
```

**Comment by kurtmc** [comment]
@fabricetriboix I believe this is happening to you because terraform does not know there is a dependency between `aws_s3_object.file` and `aws_s3_bucket.bucket`. Try the following:

```terraform
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

locals {
  bucket_name = "mybucket-yadi-yada"
}

resource "aws_s3_bucket" "bucket" {
  bucket = local.bucket_name
}

resource "aws_s3_object" "file" {
  bucket  = aws_s3_bucket.bucket.id
  key     = "hello.txt"
  content = "Hello, World!"
}
```

This will add an implicit dependency between the resources and therefor attempt to create them in the correct order.

**Comment by fabricetriboix** [comment]
Yes, that worked! Thanks, @kurtmc!

**Comment by justinretzolk** [comment]
Hey @fabricetriboix 👋 Thank you for taking the time to raise this, and thank you to @kurtmc for providing the solution! An additional option, if you prefer to use the `local` for the `bucket` argument for the `aws_s3_object` resource would be to add an explicit dependency by using the [`depends_on` meta argument](https://www.terraform.io/language/meta-arguments/depends_on). Either way should work just fine 🙂.

Since this has been resolved, we'll close this issue for now. If you feel we've done this in error, please do let us know.
