### ISSUE TITLE
Support capacity unit types for aws_ec2_fleet and aws_spot_fleet_request

### ISSUE THREAD

**Issue by c3pmark** [hashicorp/terraform-provider-aws#25777]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For `aws_ec2_fleet` and `aws_spot_fleet_request`, it's possible (in the AWS API) to specify that the requested capacity is in units of `vcpu`, `memory-mib`, or (the default) `units`, using the `TargetCapacityUnitType` key.  This doesn't seem to be supported by the AWS provider currently.

This would be especially useful when using attribute-based instance type selection (see AWS blog article below.)  For my workload, I want to allocate 32 vCPUs, but it doesn't matter whether I have, say, 16 `large` or 1 `8xlarge`.  

### New or Affected Resource(s)

* aws_spot_fleet_request
* aws_ec2_fleet (target_capacity_specification block)

### Potential Terraform Configuration

```hcl
resource "aws_ec2_fleet" "my_ec2_fleet" {
  # ...
  target_capacity_specification {
    default_target_capacity_type = "spot"
    total_target_capacity = 32
    target_capacity_unit_type = "vcpu"
  }
}

resource "aws_spot_fleet_request" "my_spot_fleet" {
  # ...
  target_capacity = 32
  target_capacity_unit_type = "vcpu"
}
```

### References

* https://aws.amazon.com/blogs/compute/implementing-attribute-based-instance-type-selection-using-terraform/
* [TargetCapacityUnitType for spot fleet request](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SpotFleetRequestConfigData.html#:~:text=Required%3A%20Yes-,TargetCapacityUnitType,-\(request\)%2C%20targetCapacityUnitType%20\(response)
* [TargetCapacityUnitType for EC2 fleet request](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_TargetCapacitySpecificationRequest.html#:~:text=TargetCapacityUnitType)

**Comment by teddylear** [comment]
I can try to take a ok into this if that's alright.

**Comment by teddylear** [comment]
@justinretzolk Opened linked PR to add this feature to both resources, please let me know if there is anything else I should add/change.

**Comment by c3pmark** [comment]
Thanks for implementing this, @teddylear!  You really helped me out :heart:
