### ISSUE TITLE
aws_db_instance_automated_backups_replication timeouts

### ISSUE THREAD

**Issue by dhruvp92** [hashicorp/terraform-provider-aws#25776]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.2.3
on linux_amd64

### Affected Resource(s)

aws_db_instance_automated_backups_replication
aws_db_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_db_instance_automated_backups_replication" "cross_region" {
   count = local.cross_region_condition ? 1 : 0

   source_db_instance_arn = aws_db_instance.rds_master_instance.arn
   kms_key_id             = aws_kms_replica_key.cross_region[0].arn

   provider = aws.replica
}
```
### Panic Output

```hcl
module.production_rds.aws_db_instance_automated_backups_replication.cross_region[0]: Still creating... [19m59s elapsed]
Error: error waiting for DB instance automated backup (arns:XXX) create: timeout while waiting for state to become 'replicating' (last state: 'pending', timeout: 20m0s)
 
with module.production_rds.aws_db_instance_automated_backups_replication.cross_region[0],
on ../../modules/rds/main.tf line 145, in resource "aws_db_instance_automated_backups_replication" "cross_region":
145: resource "aws_db_instance_automated_backups_replication" "cross_region" {
```
I am following the documentation :https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance_automated_backups_replication

However, it times out after 20 minutes and there is no custom timeouts block for the above resource to accommodate. Snapshot size is roughly 150 GB. It works for the snapshots having a smaller size.

**Comment by bschaatsbergen** [comment]
I'll pick this one up.

**Comment by dhruvp92** [comment]
Thank you @bschaatsbergen . Yeah it would be more sustainable on moving forward with timeouts block.
