### ISSUE TITLE
When specifying more than one authentication_options block it forces replacement

### ISSUE THREAD

**Issue by jjulianprin** [hashicorp/terraform-provider-aws#25800]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_ec2_client_vpn_endpoint

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

The apply whenever the resource contains more than one "authentication_options" block should not be forcing a replacement of the whole vpn endpoint.

### Actual Behavior

When the client vpn endpoint has more than one **authentication_options** block it is forcing a replacement of the vpn endpoint. which is definitely not the expected behavior.

### Steps to Reproduce

1.define a new vpn endpoint resource, for example 
resource "aws_ec2_client_vpn_endpoint" "app_vpn"
2. use different authentication_options blocks
for example to support the certificate-authentication and the federated-authentication in the same vpn endpoint
3. run `terraform apply` and you'll replicate the issue

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @jjulianprin 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you supply a sample configuration as well as debug logs (redacted as needed) as well?

**Comment by jjulianprin** [comment]
@justinretzolk Any updates here?
Thanks in advance

**Comment by a0s** [comment]
I am trying to specify two different `certificate-authentication`,  got `error creating EC2 Client VPN Endpoint: InvalidParameterValue: More than one authentication mechanism with the same type are specified`. Is it possible ?

**Comment by jjulianprin** [comment]
> a0s

> I am trying to specify two different certificate-authentication, got error creating EC2 Client VPN Endpoint: InvalidParameterValue: More than one authentication mechanism with the same type are specified. Is it possible ?

no, that's not possible. If that's the certificate for the VPN connection, what's the use case in which you would like to have two different certificates for your VPN?

**Comment by a0s** [comment]
@jjulianprin
> no, that's not possible. If that's the certificate for the VPN connection, what's the use case in which you would like to have two different certificates for your VPN?

I am trying to separate vpn clients. I found [this document](https://aws.amazon.com/premiumsupport/knowledge-center/client-vpn-multiple-users-same-endpoint/) but didn't understand how to do it with terraform.

**Comment by ewbankkit** [comment]
`authentication_options` is defined as `TypeList`, which means that order is significant (and so if the order changes then the resource is recreated). It seems that the AWS API is not returning the options in the order specified during creation, which tiggers the forced replacement.
I see that our acceptance test case for this is in fact failing  😞:

```
=== CONT  TestAccClientVPNEndpoint_serial/Endpoint_msADAuthAndMutualAuth
vpnclient_endpoint_test.go:268: Step 1/2 error: Check failed: Check 3/6 error: aws_ec2_client_vpn_endpoint.test: Attribute 'authentication_options.0.type' expected "directory-service-authentication", got "certificate-authentication"
```

The fix is to change to `TypeSet` - order is not significant.
This should be relatively simple to fix and test.

**Comment by jjulianprin** [comment]
thanks for the input @ewbankkit , yes, that makes sense, i am not really performing changes in the order i am declaring the blocks, so there must be the problem

**Comment by jjulianprin** [comment]
I confirm this has been fixed, once i upgraded my provider version, it's not reporting re-creation need now.

Thanks guys.
![image](https://user-images.githubusercontent.com/36163030/220683251-cc3af14d-93dc-4920-9b62-51893d965abb.png)
