### ISSUE TITLE
Update Documentation to Use Version 4 or Add Note for Shared Config Files

### ISSUE THREAD

**Issue by DC4JG** [hashicorp/terraform-provider-aws#25813]
Greetings,
I stumbled upon a version mismatch in the [provider documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs).

The first example code block uses `version = "~> 3.0"` which seems to be outdated in relation to the `shared_config_files` and `shared_credentials_files` arguments explained later on the page.

I suggest either updating the example code version to 4 or add a small note to the argument text stating the version when config/credentials `file` became `files`. This could help avoid confusion.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```sh
$ terraform -v
Terraform v1.2.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.75.2
```

### Affected Resource(s)

* aws

### Terraform Configuration Files

- Omitting the actual config and credential files as well as the `profile` name specifier, since they are not relevant for the issue
- The used file paths are irrelevant, hence I used the default values
- `region` is included to avoid the interactive question about it to the user
- the VPC is a trivial example to have something for `terraform plan`

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

provider "aws" {
  region                   = "eu-west-1"
  shared_config_files      = ["$HOME/.aws/config"]
  shared_credentials_files = ["$HOME/.aws/credentials"]
}

resource "aws_vpc" "test_vpc" {
  cidr_block = "10.0.0.0/16"
}
```

### Debug Output

Sorry, not doing a Gist for these few lines.

```hcl
$ terraform plan
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 12, in provider "aws":
│   12:   shared_config_files      = ["$HOME/.aws/config"]
│ 
│ An argument named "shared_config_files" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 13, in provider "aws":
│   13:   shared_credentials_files = ["$HOME/.aws/credentials"]
│ 
│ An argument named "shared_credentials_files" is not expected here. Did you mean "shared_credentials_file"?
╵
```

### Panic Output

None

### Expected Behavior

No error as this was copied from the official terraform documentation about the provider, despite being just an example. Documentation should be kept in sync with itself to help beginners.

### Actual Behavior

Error message about argument not expected and suggestion to use `shared_credentials_file` instead, which is marked as deprecated.

### Steps to Reproduce

Use `shared_config_files` or `shared_credentials_files` with aws provider version 3.

1. `terraform init`
2. `terraform plan`

Changing the version to 4 or removing it yields `v4.22.0` as of today, which works fine.

### Important Factoids

Nothing in particular.

Terraform installed and version managed by [asdf-vm](https://github.com/asdf-vm/asdf), host operating system Win10 (x64 10.0.19043), issue occurred inside WSL2 Ubuntu-20.04 used via VSCode (1.69.1).

**Comment by justinretzolk** [comment]
Hey @DC4JG 👋 Thank you for taking the time to raise this! I've opened a PR to update that document to version `~> 4.0`.
