### ISSUE TITLE
Resource aws_dynamodb_table using replica configuration block without explicit point_in_time_recovery triggers a change every time 

### ISSUE THREAD

**Issue by terlar** [hashicorp/terraform-provider-aws#25812]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/aws v4.22.0

### Affected Resource(s)

* aws_dynamodb_table

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_dynamodb_table" "example" {
  name             = "example"
  hash_key         = "TestTableHashKey"
  billing_mode     = "PAY_PER_REQUEST"
  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "TestTableHashKey"
    type = "S"
  }

  replica {
    region_name = "us-east-2"
  }
}
```

### Expected Behavior

A plan after an apply should not show any changes. A default value for replica.*.point_in_time_recovery should be properly tracked in the state.

### Actual Behavior

A plan after an apply shows changes, every-time a `terraform apply` is done the replica table will be recreated.

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### References

Before the merge of the addition of `replica.*.point_in_time_recovery` things work. It is possible to work-around the issue by explicitly setting `replica.*.point_in_time_recovery`, e.g. to the default value `false`.

* #25659

**Comment by bwhaley** [comment]
I ran in to a perpetual diff with a replica too, but in my case it was with the `kms_key_arn` attribute rather than `point_in_time_recovery`.

**Comment by YakDriver** [comment]
I cannot reproduce this with #29102. I added a part of an extra part to the `TestAccDynamoDBTable_Replica_single` test which has the exact same configuration. It applies multiple times and does an extra refresh to check for diffs.
