### ISSUE TITLE
aws_security_group_rule doesn't seem to support security groups from multiple aws accounts

### ISSUE THREAD

**Issue by devilchac** [hashicorp/terraform-provider-aws#25811]
```hcl
resource "aws_security_group_rule" "port443_service" {
  type                     = "ingress"
  to_port                  = 443
  protocol                 = "tcp"
  from_port                = 443
  source_security_group_id = data.aws_security_group.XXXXX-main-awseuc1-XX-standard.id (Another AWS Account security Group)
  security_group_id        = aws_security_group.allow_traffic_for_443.id
}
```

Every subsequent run of terraform recreates the security group rules which is disruptive and unnecessary.

**Comment by ewbankkit** [comment]
@devilchac Thanks for raising this issue.
Cross-account security group references should include the AWS Account ID of the referenced security group's owner: https://docs.aws.amazon.com/vpc/latest/peering/vpc-peering-security-groups.html.

Could you please try a configuration like:

```hcl
resource "aws_security_group_rule" "port443_service" {
  type                     = "ingress"
  to_port                  = 443
  protocol                 = "tcp"
  from_port                = 443
  source_security_group_id = "123456789012/${data.aws_security_group.XXXXX-main-awseuc1-XX-standard.id}"
  security_group_id        = aws_security_group.allow_traffic_for_443.id
}
```

**Comment by devilchac** [comment]
@ewbankkit Thanks for quick response. But this doesn't resolve my problem. After including the AWS Account ID value with **source_security_group_id**  parameter, gives me the same option, that security group will be updated in-place
![terraform_AWS_error](https://user-images.githubusercontent.com/58611493/179015352-a75bffbd-24d8-46e6-9ca4-150006d3eccf.png)

**Comment by aidanmelen** [comment]
Make sure you have vpc-peering between your accounts. Cross account source SG's only work with peering
