### ISSUE TITLE
aws_subnet_ids and aws_subnets updates where there are no changes

### ISSUE THREAD

**Issue by fabricionoda** [hashicorp/terraform-provider-aws#25820]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.10
+ provider registry.terraform.io/hashicorp/aws v3.74.2
```

### Affected Resource(s)

* aws_subnet

### Terraform Configuration Files

```hcl
data "aws_subnet_ids" "private" {
  vpc_id = data.aws_vpc.vpc.id
  filter {
    name = "tag:Name"
    values = [
      "private-1a-1", 
      "private-1b-1",
      "private-2a-1",
      "private-2b-1",
    ]
  }
}
```

### Expected Behavior

It's expected no changes on ids values running `plan` once it has already run `apply`.

### Actual Behavior

It's appearing update where has no changes, by running `plan`, even ids being exactly the same as the previous apply.

```
  # module.restapi["foo/v1"].module.lambda-proxy[0].data.aws_subnet_ids.private will be read during apply
  # (config refers to values not yet known)
 <= data "aws_subnet_ids" "private"  {
      ~ id     = "vpc-0524e27a403bb5015" -> (known after apply)
      ~ ids    = [
          - "subnet-051da50889858312f",
          - "subnet-0e3242f7e74d92ccf",
        ] -> (known after apply)
      + tags   = (known after apply)
      ~ vpc_id = "vpc-0126c21a405cb8018" -> (known after apply)        # (1 unchanged block hidden)
    } 

```
### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### Important Factoids

I have already tried also to change deprecated `aws_subnet_ids` to `aws_subnets`, just to make sure, but I got the same unexpected behavior.

* #0000

**Comment by justinretzolk** [comment]
Hey @fabricionoda 👋 Thank you for taking the time to raise this! It looks like what you're running into here is that the data source must be read at apply time due to the dependency on `data.aws_vpc.vpc.id`. More information can be found in the [Data Resource Behavior](https://www.terraform.io/language/data-sources#data-resource-behavior) documentation. What led me to this was this note in the plan logs...:

```shell
  # module.restapi["foo/v1"].module.lambda-proxy[0].data.aws_subnet_ids.private will be read during apply
  # (config refers to values not yet known)
```

...along with this being the only interpolated value in the resource definition:

```hcl
data "aws_subnet_ids" "private" {
  vpc_id = data.aws_vpc.vpc.id
  # omitted for brevity
}

**Comment by fabricionoda** [comment]
Thanks! @justinretzolk, after many tries, we figured out that the issue was due the datasource statement inside modules, when moved the datasource statement to the root, it works avoiding `will be read during apply (config refers to values not yet known)` occurrences.
