### ISSUE TITLE
AWS Cloud WAN

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#25835]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Today, AWS announced the general availability of AWS Cloud WAN, a wide area networking (WAN) service that helps you build, manage, and monitor a unified global network.

### New or Affected Resource(s)

* `aws_networkmanager_core_network`
* ...

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2022/07/general-availability-aws-cloud-wan/).
[Blog post](https://aws.amazon.com/blogs/aws/new-cloud-wan-a-managed-wan-service/).

Related:

* https://github.com/hashicorp/terraform-provider-aws/pull/24368

**Comment by tjstansell** [comment]
Thanks for linking me to this issue. Not sure how I didn't notice it. So then I take it the plan is to eventually fully support this via this provider just like what was requested in #23782?

**Comment by sleerssen** [comment]
Would love to see this make its way into the released provider as well.

**Comment by mpanicker** [comment]
yes eagerly waiting this change as this could be a game changer for Organization wide networking

**Comment by ewbankkit** [comment]
#### TODO

* `aws_networkmanager_site_to_site_vpn_attachment`
* `aws_networkmanager_connect_attachment`
* Accepting attachment types other than `VPC`
* Core Network resource in the AWS Provider (currently available only in the [AWS Cloud Control Provider](https://github.com/hashicorp/terraform-provider-awscc)) - requires some design around policy versioning
