### ISSUE TITLE
Terraform Lambda Layers Management

### ISSUE THREAD

**Issue by kbmdev** [hashicorp/terraform-provider-aws#25837]
Context:
We have a lambda function with custom layers that are actively deployed and published via a CI/CD pipeline.

Issue:
Although the lambda function creation terraform script, doesn't include "layers" field whenever terraform apply is run, it removes the attached layers which are managed outside of terraform.

Expected Result:
Terraform shouldn't manage layers and shouldn't trigger removal of layers from lambda.

How can the Lambda Layer management be decoupled?

**Comment by justinretzolk** [comment]
Hey @kbmdev 👋 Thank you for taking the time to raise this! Terraform will attempt to correct drift when it runs (we have a [blog post](https://www.hashicorp.com/blog/detecting-and-managing-drift-with-terraform) that discusses this in detail). If you're modifying the Lambda function outside of Terraform, then the next time that it runs, it will attempt to "correct" this drift. It sounds like this is what you're running into with the layers being removed on subsequent runs. There are a couple of approaches you can take to mitigate this.

One option would be to add the layers to the `aws_lambda_function` configuration's `layers` argument by gathering the data around the layers created by your CI/CD pipeline using the [`aws_lambda_layer_version` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/lambda_layer_version) and interpolating the results.

Another option would be to add an [`ignore_changes` block](https://www.terraform.io/language/meta-arguments/lifecycle#ignore_changes) to ignore changes to the `layers` argument. Note that if there are additional changes that would trigger an update to the Lambda function, you may still run into the same issues. For this reason, I would not generally recommend this approach given your scenario.

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
