### ISSUE TITLE
aws_backup_selection selection_tag only supports STRINGEQUALS

### ISSUE THREAD

**Issue by hikarunoryoma** [hashicorp/terraform-provider-aws#25867]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would expect the following resource definition to work: 
```
resource "aws_backup_selection" "testing" {
  iam_role_arn = <arn>
  name         = "testing"
  plan_id      = aws_backup_plan.testing_backup_plan.id

  resources = ["*"]

  condition {
    string_equals {
      key   = "aws:ResourceTag/Component"
      value = "DynamoDB"
    }
  }

  selection_tag {
    type  = "NOVALUES"
    key   = "customer"
  }
}
```

to work.  It seems like the only type of `selection_tag` supported is "STRINGEQUALS".  Are there plans to support other selection tag types to bring this to feature parity with what is supported by the aws backup console?

This is the error my console prints: `Error: expected selection_tag.0.type to be one of [STRINGEQUALS], got NOVALUES`

### New or Affected Resource(s)

* aws_backup_selection

Let me know if you need further information.  I didn't want to copy over my terraform config set-up, but I can probably make a smaller P.o.C set-up.  Hopefully the codeblock above is enough information!

**Comment by justinretzolk** [comment]
Hey @hikarunoryoma 👋 Thank you for taking the time to raise this! It looks like the limitation of `selection_tag` only supporting `StringEquals` comes from the underlying SDK/API ([API reference](https://docs.aws.amazon.com/aws-backup/latest/devguide/API_BackupSelection.html), [SDK reference](https://docs.aws.amazon.com/sdk-for-go/api/service/backup/#Selection)). The `condition` argument supports additional options (`StringEquals`, `StringLike`, `StringNotEquals`, and `StringNotLike`); I see that you're already using `condition` elsewhere -- is there additional functionality that I'm perhaps overlooking?

**Comment by hikarunoryoma** [comment]
Hi @justinretzolk thanks for the reply.  I actually ended up resolving this issue on my end by just using conditions as opposed to selection_tag.  I think I have some confusion between the difference of `selection_tag` and `condition`.  The documentation states that selection_tag is tag based condition, but it appears that those rules aren't really used and condition is the better option to use.  

If `selection_tag` indeed works as expected perhaps linking on the documentation page what other expected options exist.  The error message suggests that there is only 1 possible option and on the documentation page this is all that is listed: `[type](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_selection#type) - (Required) An operation, such as StringEquals, that is applied to a key-value pair used to filter resources in a selection.`

See link: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_selection#type.
