### ISSUE TITLE
error creating EC2 Transit Gateway VPC Attachment: DuplicateTransitGatewayAttachment: tgw-xxx has non-deleted Transit Gateway Attachments with same VPC ID

### ISSUE THREAD

**Issue by udxiaoxin** [hashicorp/terraform-provider-aws#25868]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform version: 0.14.11
AWS Provider version: 3.73.0

### Affected Resource(s)

* aws_ec2_transit_gateway_vpc_attachment

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Terraform should not make change to existing attachment

### Actual Behavior

error creating EC2 Transit Gateway VPC Attachment: DuplicateTransitGatewayAttachment: tgw-xxx has non-deleted Transit Gateway Attachments with same VPC ID

We have compared the tf plan,  the 'new' attachment already exists in the account. 
We even try to import the issue attachment, but it still try to delete the existing attachment and create a new one. However,  their attributes exactly the same. See below

```shell
# aws_ec2_transit_gateway_vpc_attachment.tgw_test will be destroyed
  - resource "aws_ec2_transit_gateway_vpc_attachment" "tgw_test" {
      - appliance_mode_support                          = "disable" -> null
      - dns_support                                     = "enable" -> null
      - id                                              = "tgw-attach-093df41f59d8a4a26" -> null
      - ipv6_support                                    = "disable" -> null
      - subnet_ids                                      = [
          - "subnet-03f17805e2e3cc98a",
          - "subnet-0b8e56e8a53712126",
          - "subnet-0fccdd2a26c06c38b",
        ] -> null
      - tags                                            = {
          - "TGW" = "Internal"
        } -> null
      - tags_all                                        = {
          - "TGW" = "Internal"
        } -> null
      - transit_gateway_default_route_table_association = true -> null
      - transit_gateway_default_route_table_propagation = true -> null
      - transit_gateway_id                              = "tgw-xxx635" -> null
      - vpc_id                                          = "vpc-xxx7163" -> null
      - vpc_owner_id                                    = "877973707015" -> null
    }

  # aws_ec2_transit_gateway_vpc_attachment.tgw_test["vpc-xxx7163"] will be created
  + resource "aws_ec2_transit_gateway_vpc_attachment" "tgw_test" {
      + appliance_mode_support                          = "disable"
      + dns_support                                     = "enable"
      + id                                              = (known after apply)
      + ipv6_support                                    = "disable"
      + subnet_ids                                      = [
          + "subnet-03f17805e2e3cc98a",
          + "subnet-0b8e56e8a53712126",
          + "subnet-0fccdd2a26c06c38b",
        ]
      + tags                                            = {
          + "TGW" = "Internal"
        }
      + tags_all                                        = {
          + "TGW" = "Internal"
        }
      + transit_gateway_default_route_table_association = true
      + transit_gateway_default_route_table_propagation = true
      + transit_gateway_id                              = "tgw-xxx635"
      + vpc_id                                          = "vpc-xxx7163"
      + vpc_owner_id                                    = (known after apply)
    }
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @udxiaoxin 👋 Thank you for taking the time to raise this! Something you mentioned here was a bit unclear to me:

> We have compared the tf plan, the 'new' attachment already exists in the account.
We even try to import the issue attachment, but it still try to delete the existing attachment and create a new one. However, their attributes exactly the same. See below

Are you saying that the transit gateway currently exists within AWS, but is not within the Terraform state file? I also noted that the two resources in the plan supplied have different addresses:

- `aws_ec2_transit_gateway_vpc_attachment.tgw_test`
- `aws_ec2_transit_gateway_vpc_attachment.tgw_test["vpc-xxx7163"]`

If you could supply the Terraform configuration where this resource is defined, as well as any information on how you are attempting to import the resource, that may give me a better idea of why you're seeing unexpected behavior.

**Comment by ewbankkit** [comment]
@udxiaoxin Thanks for raising this issue.
It has already been noticed in #10852. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
