### ISSUE TITLE
Support for Sagemaker Studio & Sagemaker Ground truth resources

### ISSUE THREAD

**Issue by kodalikranthi** [hashicorp/terraform-provider-aws#25873]
There are no resources for Sagemaker studio & Sagemaker Ground truth. I would like to have these resources

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @kodalikranthi 👋 Thank you for taking the time to raise this! Can you give me a better idea of what types of resources you're looking for with regards to Sagemaker Studio and Ground Truth? On a quick look at the AWS Go SDK, the only Studio related methods seem to relate to Sagemaker Studio lifecycle configurations (for which there is [an existing resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_studio_lifecycle_config)). I'm not particularly familiar with Ground Truth, but couldn't find any obvious methods relating to that either.

This may be a limitation of the underlying SDK/API, but I'd be happy to take another look once I have a better idea of what you're looking to achieve.

**Comment by DrFaust92** [comment]
Sagemaker studio resources are supported. for specific ground truth resource please open a new ticket with specific resources (some are already supported)
