### ISSUE TITLE
Refreshing aws_redshiftdata_statement after query result expires fails

### ISSUE THREAD

**Issue by nickroberts** [hashicorp/terraform-provider-aws#25882]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
terraform -v
Terraform v1.2.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.22.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
```

### Affected Resource(s)

* aws_redshiftdata_statement

### Terraform Configuration Files

```hcl
provider "aws" {
  profile = "my_aws_profile"
  region  = "us-east-1"
  assume_role {
    role_arn = "assumed_role_arn"
  }
}

data "local_file" "foo" {
  filename = "${path.module}/foo.sql"
}

resource "aws_redshiftdata_statement" "example" {
  cluster_identifier = "redshift_cluster"
  database           = "redshift_db"
  db_user            = "redshift_user"
  sql                = data.local_file.foo.content
}
```

### Expected Behavior

`terraform plan` should work correctly.

### Actual Behavior

`terraform plan` throws an error after the initial statement query result expires.

```
terraform plan
data.local_file.foo: Reading...
data.local_file.foo: Read complete after 0s [id=a20f78b1806718fc9b70c7b91fb7ba07f6b2dd46]
aws_redshiftdata_statement.example: Refreshing state... [id=284bfee4-49dc-4ad1-ac90-0bba0580d568]
╷
│ Error: reading Redshift Data Statement (284bfee4-49dc-4ad1-ac90-0bba0580d568): ValidationException: Could not retrieve the query result as it has expired after 1658071606.
│
│   with aws_redshiftdata_statement.example,
│   on main.tf line 17, in resource "aws_redshiftdata_statement" "example":
│   17: resource "aws_redshiftdata_statement" "example" {
│
╵
```

### Steps to Reproduce

1. `terraform apply`
2. wait until the query result expires (3 days, it looks like), or change id in state to an already expired query result id (this is what I did in order to test this).
3. `terraform plan`

### References

* #https://github.com/pulumi/pulumi-aws/issues/2055

**Comment by rockpunk** [comment]
This seems to be a fundamental issue with redshift-data service.  The `describe-statement` API does not return statement info after several days.

```
❯ terraform state show 'aws_redshiftdata_statement.create_schema'
# aws_redshiftdata_statement.create_schema:
resource "aws_redshiftdata_statement" "create_schema" {
    cluster_identifier = "<cluster_id>"
    database           = "<db>"
    db_user            = "<user>"
    id                 = "346a11c9-9e89-476b-a68a-995a1d3f3a39"
    sql                = <<-EOT
        DROP SCHEMA IF EXISTS some_schema;
        CREATE SCHEMA some_schema;
    EOT
}

❯ aws redshift-data describe-statement --id 346a11c9-9e89-476b-a68a-995a1d3f3a39

An error occurred (ValidationException) when calling the DescribeStatement operation: Could not retrieve the query result as it has expired after 1660423725.
```

I created #26343 to address this, though it does mean that these expired statements will now be re-run.

If users do not want the statement to be re-run, they will need to either

1. make sure statements are idempotent
2. use lifecycle ignore_changes
