### ISSUE TITLE
SSO: Support for permission boundary policies 

### ISSUE THREAD

**Issue by kuuji** [hashicorp/terraform-provider-aws#25893]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

https://aws.amazon.com/about-aws/whats-new/2022/07/aws-single-sign-on-aws-sso-aws-identity-access-management-iam-customer-managed-policies-cmps/ both just got released to AWS SSO. These improve the flexibility over the current inline policy + aws managed.

### New or Affected Resource(s)

As it is, the inline and managed policy attachments are designed to attach to an existing permission set. So this addition shouldn't impact existing resources

### Potential Terraform Configuration

I suppose the interface would be very similar to the current aws managed policy https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssoadmin_managed_policy_attachment

```hcl
data "aws_ssoadmin_instances" "example" {}

resource "aws_ssoadmin_permission_set" "example" {
  name         = "Example"
  instance_arn = tolist(data.aws_ssoadmin_instances.example.arns)[0]
}

resource "aws_ssoadmin_customer_managed_policy_attachment" "example" {
  instance_arn       = tolist(data.aws_ssoadmin_instances.example.arns)[0]
  customer_managed_policy_arn = "<policy_arn>"
  permission_set_arn = aws_ssoadmin_permission_set.example.arn
}
```

### References

edit: changing this issue to be specific to permission boundary since there's another issue for CMPs

**Comment by justinretzolk** [comment]
Related: #25904

**Comment by lorengordon** [comment]
Since #25904 is specific to customer managed policies, perhaps this issue can be updated so it is specific to only the permission boundary?

**Comment by kuuji** [comment]
I can do that @lorengordon .

**Comment by lorengordon** [comment]
Here are the API references for the permissions boundary:

* https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_PutPermissionsBoundaryToPermissionSet.html
* https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_DeletePermissionsBoundaryFromPermissionSet.html
* https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_GetPermissionsBoundaryForPermissionSet.html

**Comment by odg0318** [comment]
Let's discuss the code interface to add boundary policy. The parameters are found in [this document](https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_PutPermissionsBoundaryToPermissionSet.html).

### parameters
```json
{
   "InstanceArn": "string",
   "PermissionsBoundary": {
      "CustomerManagedPolicyReference": {
         "Name": "string",
         "Path": "string"
      },
      "ManagedPolicyArn": "string"
   },
   "PermissionSetArn": "string"
}
```

### Suggested code
One of `customer_managed_policy_name` and `managed_policy_arn` must be set here. When I look at the AWS GUI, there is no field for `CustomerManagedPolicyReference.Path` on UI so it can be assigned to `null`.

```hcl
data "aws_ssoadmin_instances" "example" {}

resource "aws_ssoadmin_permission_set" "example" {
  name         = "Example"
  instance_arn = tolist(data.aws_ssoadmin_instances.example.arns)[0]
}

resource "aws_ssoadmin_permission_set_boundary_policy" "example" {
  instance_arn       = tolist(data.aws_ssoadmin_instances.example.arns)[0]
  permission_set_arn = aws_ssoadmin_permission_set.example.arn

  customer_managed_policy_name = "<policy_name>"
  customer_managed_policy_path = "<policy_path>"
  managed_policy_arn           = "<policy_arn>"
}
```

**Comment by josemdav** [comment]
Perhaps having the interface to specify the boundary in a similar way that the AWS SSO API it's more consistent. The same was done in the [ssoadmin_customer_managed_policy_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssoadmin_customer_managed_policy_attachment)

```
data "aws_ssoadmin_instances" "example" {}

resource "aws_ssoadmin_permission_set" "example" {
  name         = "Example"
  instance_arn = tolist(data.aws_ssoadmin_instances.example.arns)[0]
}

resource "aws_ssoadmin_permission_set_boundary_policy" "example" {
  instance_arn       = tolist(data.aws_ssoadmin_instances.example.arns)[0]
  permission_set_arn = aws_ssoadmin_permission_set.example.arn

  permissions_boundary  {
    customer_managed_policy_reference {
      name = "policy_name"
      path = "/"
    }
  }
}
```
or
```
data "aws_ssoadmin_instances" "example" {}

resource "aws_ssoadmin_permission_set" "example" {
  name         = "Example"
  instance_arn = tolist(data.aws_ssoadmin_instances.example.arns)[0]
}

resource "aws_ssoadmin_permission_set_boundary_policy" "example" {
  instance_arn       = tolist(data.aws_ssoadmin_instances.example.arns)[0]
  permission_set_arn = aws_ssoadmin_permission_set.example.arn

  permissions_boundary  {
    managed_policy_arn = "managed_policy_arn"
  }
}
```

I wonder how to conditionally go with one option or the other when creating modules using this resource
