### ISSUE TITLE
Support for AWS SSO permission sets with customer managed policies

### ISSUE THREAD

**Issue by tylersmith34** [hashicorp/terraform-provider-aws#25904]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for using customer managed policies (CMP) with AWS SSO permission sets.  This feature was released on July 19, 2022, [blog post for release](https://aws.amazon.com/about-aws/whats-new/2022/07/aws-single-sign-on-aws-sso-aws-identity-access-management-iam-customer-managed-policies-cmps/), [SSO documentation](https://docs.aws.amazon.com/singlesignon/latest/userguide/howtocmp.html).

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
resource "aws_ssoadmin_permission_set_customer_managed_policy" "example" {
  policy_arn         = "arn:aws:iam::000000000000:policy/my-policy"
  instance_arn       = aws_ssoadmin_permission_set.example.instance_arn
  permission_set_arn = aws_ssoadmin_permission_set.example.arn
}
```

### References

* #0000

**Comment by oakbramble** [comment]
I have started writing a solution for this, as I work a lot with the SSO, however I have not worked in Go before, so maybe someone else will be much more efficient at completing this. 

Regarding the config, the inputs are slightly different than for the AWS managed policy, having this `CustomerManagedPolicyReference` rather than `ManagedPolicyArn`:
```   "CustomerManagedPolicyReference": { 
      "Name": "string",
      "Path": "string"
   },
```
is that something we would want to preserve, or were you thinking to derive those inputs from the ARN?

**Comment by tylersmith34** [comment]
Good question, I hadn't driven into the API for it but the console appears to want the policy name.  That tells me the policy path is irrelevant (as is the path for a role, it's not part of the name).  The managed policy arn attachment is a separate resource which is why my example showed it that way but I'm also OK with a config block inside the policy set.

**Comment by oakbramble** [comment]
Ok, I am aiming for the following, in line with the current `aws_ssoadmin_managed_policy_attachment`:

```
resource "aws_ssoadmin_customer_managed_policy_attachment" "example" {
  customer_managed_policy_name         = aws_iam_policy.example.name
  customer_managed_policy_path         = "/" # optional
  instance_arn       = tolist(data.aws_ssoadmin_instances.example.arns)[0]
  permission_set_arn = aws_ssoadmin_permission_set.example.arn
}
```
(though if the learning curve I'm having working with Go and the provider for the first time means I'll manage this, remains to be seen :smile: )

**Comment by lorengordon** [comment]
Here are the API references:

* https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_AttachCustomerManagedPolicyReferenceToPermissionSet.html
* https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_DetachCustomerManagedPolicyReferenceFromPermissionSet.html
* https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_ListCustomerManagedPolicyReferencesInPermissionSet.html

**Comment by oakbramble** [comment]
Ok, the linked PR I wrote should be ready. Not sure if I need to take any further action to make sure this gets looked at, or I just need to wait. (I also didn't see the branch naming conventions until I'd started the PR, so not sure if this is lowering its visibility?)
Anyway, please let me know if there is anything I should be doing to make sure the PR is seen by the right people. Thanks.

**Comment by jjshoe** [comment]
@danquack any bandwidth to help get this over the line? :heart:

**Comment by danashsparkbeyond** [comment]
:+1:

**Comment by shacharlevy1991** [comment]
+1
