### ISSUE TITLE
`aws_launch_template` not configuring `metadata_options` 

### ISSUE THREAD

**Issue by phzietsman** [hashicorp/terraform-provider-aws#25909]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/aws v4.22.0
+ provider registry.terraform.io/hashicorp/helm v2.6.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.12.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.4.0

Your version of Terraform is out of date! The latest version
is 1.2.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* aws_launch_template

### Terraform Configuration Files

```hcl
resource "aws_launch_template" "node_group_launch_template" {
  for_each               = var.eks_node_subnet_map
  name                   = "${local.cluster_base_name}-${each.key}-lt"
  user_data              = data.template_cloudinit_config.cluster_node_group_user_data.rendered
  key_name               = aws_key_pair.node_group_key_pair.key_name
  vpc_security_group_ids = [aws_security_group.cluster_sg.id]
  update_default_version = true

  block_device_mappings {
    device_name = "/dev/xvda"
    ebs {
      delete_on_termination = "true"
      volume_size           = each.value["disk_size"]
      volume_type           = "gp2"
    }
  }

  metadata_options {
    http_tokens                 = "required"
    http_put_response_hop_limit = 2
    instance_metadata_tags      = "disabled"
  }

  # lifecycle {
  #   ignore_changes = [metadata_options]
  # }

  tag_specifications {
    resource_type = "instance"
    tags          = local.deployment_tags
  }
}
```

### Expected Behavior

The metadata options are set on the launch template after apply.

### Actual Behavior

The metadata options are NOT set on the launch template after apply. On a new plan TF detects that options are not set and want to make the required changes, but it has not effect.

### Steps to Reproduce

1. `terraform apply`

**Comment by ewbankkit** [comment]
Similar: https://github.com/hashicorp/terraform-provider-aws/issues/25896.

**Comment by bevanbennett** [comment]
To be more specific, it appears that aws_instance supports `instance_metadata_tags` as part of metadata_options, but aws_launch_configuration does not. This is a huge blocker for a project of ours.

**Comment by kruftmeister** [comment]
> To be more specific, it appears that aws_instance supports `instance_metadata_tags` as part of metadata_options, but aws_launch_configuration does not. This is a huge blocker for a project of ours.

Launch Configuration != Launch Template

**Comment by amille44420** [comment]
I confirm meeting such issue as well ; since we are providing configurations for  `metadata_options` every deployment will create new versions for our launch templates which sadly trigger updates on our EKS node pools.

We met this issue as soon as we added `metadata_options` to our definitions.

**Comment by seanamos** [comment]
For those running into this, it seems to be as a result of a terraform bug when `http_endpoint` isn't explicitly set.

Setting `http_endpoint = "enabled"` makes things work as expected.

**Comment by ohookins** [comment]
The documentation says that `http_endpoint` defaults to enabled, but this doesn't seem to be the reality of what is implemented.

**Comment by good92** [comment]
https://github.com/hashicorp/terraform-provider-aws/pull/29024

**Comment by good92** [comment]
https://github.com/hashicorp/terraform-provider-aws/pull/24774

**Comment by good92** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/178

**Comment by good92** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1785
