### ISSUE TITLE
Documentation missing for "aws_lambda_event_source_mapping" with AWS MSK

### ISSUE THREAD

**Issue by mkielar** [hashicorp/terraform-provider-aws#25911]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `aws_lambda_event_source_mapping`

### Terraform Configuration Files
N/A
### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
I'd expect the `SASL_SCRAM_512_AUTH` type to be documented for `source_access_configuration`.

### Actual Behavior
Instead, the doc states that, I quote:
>  For Self Managed Kafka you will need to supply blocks for type VPC_SUBNET and VPC_SECURITY_GROUP.

That's not only missing docs, but also confusing.

### Steps to Reproduce
1. See: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping#source_access_configuration-configuration-block

### References
* https://github.com/hashicorp/terraform-provider-aws/issues/17825

**Comment by Tr1monster** [comment]
I really like to see a documentation for that. I tooks me 3h to figure out how to configure this feature request leads me to the solution.
