### ISSUE TITLE
AWS: Allow for Glue Marketplace Connector-type Connections

### ISSUE THREAD

**Issue by barel166** [hashicorp/terraform-provider-aws#25928]
AWS Glue Studio allows for the creation of Glue Connections that use an AWS Marketplace Connector for Glue.
When we try to create a Glue Connection that uses a marketplace connector (Google Bigquery connector for AWS Glue) we're unable to define it in TF because the only [supported connection types](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_connection#connection_type) do not include the type "MARKETPLACE" or the ability to select an existing marketplace connector.

Affected resource: aws_glue_connection

![image](https://user-images.githubusercontent.com/75643982/180332234-d638040e-4ca3-4069-a50a-5f83b422c3cb.png)

**Comment by justinretzolk** [comment]
Hey @barel166 👋 Thank you for taking the time to raise this! It looks like this is a matter of the documentation being out of date, as the resource does support the `MARKETPLACE` connection type. I've opened a PR to correct the documentation.

I'm not very familiar with setting up a Glue connection, but my read is that the connector settings would be passed in with the `connection_properties` argument. Valid values for the keys of that argument may be found in the [AWS API documentation](https://docs.aws.amazon.com/glue/latest/webapi/API_ConnectionInput.html).

**Comment by barel166** [comment]
Thanks for the quick response! We realized `MARKETPLACE` was allowed now, but like you said, seems like it works along with special connection_properties. For now we just get this error in Terraform when attempting to create a MARKETPLACE type connection: InvalidInputException: Validation for connection properties failed. So definitely points to a different set of connection properties that needs to be set for those types of connections, and AWS does not seem to have those all documented for when using a marketplace connector.
We'll find those out somehow.
Thanks!
