### ISSUE TITLE
Transit Gateway Flowlogs

### ISSUE THREAD

**Issue by Jamie-Leon** [hashicorp/terraform-provider-aws#25940]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add the ability to enable and configure Transit Gateway Flow logs

### New or Affected Resource(s)

* aws_ec2_transit_gateway (it may be this or it may be another new resource)

### References

* https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-vpc-flow-logs-for-aws-transit-gateway/

**Comment by ewbankkit** [comment]
This functionality has been implemented via https://github.com/hashicorp/terraform-provider-aws/pull/25913 and is available in [**v4.23.0**](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#4230-july-22-2022) of the Terraform AWS Provider.
