### ISSUE TITLE
Use DynamoDB TTL for Removing Stale State Locks?

### ISSUE THREAD

**Issue by celestialorb** [hashicorp/terraform-provider-aws#25947]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm not terribly familiar with DynamoDB myself, but I believe the TTL feature of it could be utilized to automatically unlock Terraform states that failed or otherwise error'd during execution.

I'd like to be able to have a Terraform state that is locked in DynamoDB be automatically unlocked after some amount of time (say 24 hours or so) in case there was an issue with unlocking the state in DynamoDB during execution. I don't currently see a way of doing this as the AWS provider doesn't provide any kind of expiration field in the DynamoDB table entry itself.

I would not expect a feature like this to be enabled by default. I would expect it to require additional configuration in order for it to be enabled.

### Use Case

Back when I used Terragrunt I'd occasionally have to kill it with Ctrl+C multiple times to actually get it to terminate without having to wait for the underlying Terraform processes to finish (which would take quite a while in our setup). I believe this sometimes had the adverse effect of not properly releasing the lock(s) on our Terraform state(s) and would cause them to be locked indefinitely until someone manually unlocked it.

Regardless of Terragrunt (or similar) usage though, I believe this could happen to any Terraform process that terminates unexpectedly or encounters an unexpected error.

### Potential Terraform Configuration

I feel this could be accomplished by adding a few additional (optional) fields to the AWS provider. One provider field could specify the field in the DynamoDB table that defines the expiration timestamp of the lock, and another provider field could specify the duration of the lock. Then I believe the DynamoDB table would only need to have TTL enabled on that expiration field, and the provider would need to provide the proper timestamp to the field itself.

A proposed example AWS S3 backend configuration is given below.
```hcl
terraform {
  backend "s3" {
    bucket = "my-terraform-bucket"
    key    = "my-terraform-state-key"
    region = "us-east-1"

    dynamodb_table                    = "my-terraform-state-locks"
    dynamodb_lock_expiration_field    = "ExpirationTimestamp"
    dynamodb_lock_expiration_duration = "24h"
  }
}
```

**Comment by DrFaust92** [comment]
this is unrelated to the the aws provider as the backend config is a core TF feature.

**Comment by celestialorb** [comment]
Ah, of course. I'll make an issue over in the Terraform repository. Thanks!

**Comment by celestialorb** [comment]
Looks like there's already an open issue for this feature: https://github.com/hashicorp/terraform/issues/21671
