### ISSUE TITLE
aws_appstream_stack.access_endpoints argument documentation missing

### ISSUE THREAD

**Issue by rymancl** [hashicorp/terraform-provider-aws#25950]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_appstream_stack

`aws_appstream_stack` [documentation page](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appstream_stack) is missing documentation for the `access_endpoints` argument.

![image](https://user-images.githubusercontent.com/3211227/180496538-261f7e43-8a32-454a-98a2-8e970432c42b.png)

https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/appstream/stack.go#L38
https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/appstream_stack.html.markdown

**Comment by justinretzolk** [comment]
Hey @rymancl 👋 Thank you for taking the time to raise this! I've opened a PR to add the relevant information to the documentation.

**Comment by rymancl** [comment]
> Hey @rymancl 👋 Thank you for taking the time to raise this! I've opened a PR to add the relevant information to the documentation.

Thanks! For some reason I thought the docs were auto-generated and there might be an issue somewhere, hence why I didn't just update it myself. Next time I see something like this I'll fix it myself! 🙃
