### ISSUE TITLE
When multiple providers, show provider for each resource in the plan.

### ISSUE THREAD

**Issue by waltervargas** [hashicorp/terraform-provider-aws#25979]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When working with multiple AWS providers under the same state, it will help to show provider details for each resource, or group the plan by provider, example: 

```hcl
Terraform will perform the following actions:

  # data.aws_iam_policy_document.sns_topic_policy will be read during apply
  # (config refers to values not yet known)
  # provider: master
 <= data "aws_iam_policy_document" "sns_topic_policy"  {
+       id   = (known after apply)
+       json = (known after apply)

+       statement {
+           actions   = [
+               "SNS:Publish",
            ]
+           effect    = "Allow"
+           resources = [
+               (known after apply),
            ]

+           principals {
+               identifiers = [
+                   "events.amazonaws.com",
                ]
+               type        = "Service"
            }
        }
    }

  # aws_cloudwatch_event_rule.console will be created 
  # provider: master
+ resource "aws_cloudwatch_event_rule" "console" {
+       arn            = (known after apply)
+       description    = "Capture each AWS Console Sign In"
+       event_bus_name = "default"
+       event_pattern  = jsonencode(
            {
+               source = [
+                   "aws.signin",
                ]
            }
        )
+       id             = (known after apply)
+       is_enabled     = true
+       name           = "capture-aws-sign-in"
+       name_prefix    = (known after apply)
    }

  # aws_cloudwatch_event_target.console will be created
  # provider: child-account
+ resource "aws_cloudwatch_event_target" "console" {
+       arn            = (known after apply)
+       event_bus_name = "default"
+       id             = (known after apply)
+       rule           = "health-rds-sns"
+       target_id      = "ConsoleSNS"
    }
```

### New or Affected Resource(s)

* aws_* (All resources)

**Comment by justinretzolk** [comment]
Hey @waltervargas 👋 Thank you for taking the time to raise this! This is a really interesting idea, however, I think that it's probably better suited as a feature request for Terraform Core, since this would be something that would be helpful for _any_ aliased providers. Can you instead open an issue in the [Terraform Core repository](https://github.com/hashicorp/terraform)?

**Comment by justinretzolk** [comment]
Closing, preferring the aforementioned direction of opening an issue in the Terraform Core repository.
