### ISSUE TITLE
Cannot use provider version higher than 3.75.0

### ISSUE THREAD

**Issue by m477r1x** [hashicorp/terraform-provider-aws#25984]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Summary
I am having a weird issue with using the aws provider. I am trying to use the latest version of the provider but i am receiving the below error output. I have tried deleting the `.terraform.lock.hcl` file and allowing it to regenerate the file. I have also tried removing the version tag form the provider config completely, and in this case rather than automatically downloading the latest version of the provider, terraform downloads version 3.75.0.

### Terraform CLI and Terraform AWS Provider Version
```Terraform v1.1.9
on darwin_arm64
+ provider registry.terraform.io/datadog/datadog v3.14.0
+ provider registry.terraform.io/hashicorp/aws v3.75.2
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/labd/commercetools v0.31.0

Your version of Terraform is out of date! The latest version
is 1.2.5. You can update by downloading from https://www.terraform.io/downloads.html
````

### Terraform Configuration Files

```required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.23.0"
    }
```

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

### Debug Output

https://gist.github.com/m477r1x/92e5177b0ae33364b7173fde4303ef0a

### Expected Behavior

Terraform to download version 4.23.0 or higher of the aws provider

### Actual Behavior

Errored with the debug in the gist.

### Steps to Reproduce

1. `terraform init`

**Comment by justinretzolk** [comment]
Hey @m477r1x 👋 Thank you for taking the time to raise this! Based on the message you received (in the debug logs), it looks like you may have a module that's [requiring](https://www.terraform.io/language/providers/requirements#requiring-providers) an older version of the provider. To check where those requirements are coming from, you can use the [`terraform providers` command](https://www.terraform.io/cli/commands/providers). The output will look something like this (which came from a sample configuration I just created that has the same issue):

```shell
$ terraform providers

Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/aws] ~> 4.0
└── module.test
    └── provider[registry.terraform.io/hashicorp/aws] 3.75.0
```
