### ISSUE TITLE
Need a way to detect if a role or policy has changed

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform-provider-aws#25980]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Roles and Policies in AWS are eventually consistent - they often take around 10 seconds to take effect. Frequently however it is desirable in terraform to use a role/policy that you have just created to then do some action that the role/policy allows. For example we create a role called foo, apply policy bar to it, wait 10 seconds, and then use foo to do something else, all in the same terraform run. 

Generally speaking this works well, and we use a time_sleep resource to wait 10 seconds, depending on the role/policy etc. 

This all works the first time round, but if the role or policy changes then we need to re-trigger the time_sleep resource to wait another 10 seconds, before downstream objects are to be applied (with the new policy). This creates the question - how can we trigger when a role changes?

I started off using:

```
resource "time_sleep" "ready" {
  triggers = {
    id = aws_iam_role_policy.this.id
    role_policy = aws_iam_role_policy.this.policy
  }
  create_duration = "10s"
  depends_on = [
    aws_iam_role_policy.this
  ]
}
```

And this seems to work fine - when the policy changes, the time_sleep also gets replaced, causing a 10s delay and it all works. 

However in a recent provider version upgrade of aws, whitespace changes were introduced into the policy document which caused all time_sleeps to get replaced - because they thought the policies had changed, even though they are just whitespace changes. 

This rather breaks the model, and suddenly most of the infrastructure is being rebuilt because of a whitespace change. 

I would like a foolproof way of detecting whether the _FUNCTIONAL CONTENT_ of a policy has changed so I can trigger on it.

I am also going to raise this in terraform-core because it might be a good case for a function to wrap around a policy rather than in the resources themselves. 

Some of my colleagues suggested eTags are pretty standard way to detect differences, but I'd only want to detect functional differences.

### New or Affected Resource(s)

* aws_iam_role
* aws_iam_role_policy
* aws_iam_policy

### Potential Terraform Configuration

If there was a function or attribute which could take a json policy, and deep sort all map keys, and standardise around the difference between `{ AWS: foo }` and `{ AWS: [ foo ] }` which are also functionally identical - and then output a standardised document or even better - a checksum/hash, that would be very handy.

If implementing in the resource itself, it would be need to be done on all policy types, e.g. assume_role_policy, policy etc. - but personally speaking I think a datasource in the aws-provider which could take some json content and spit out a standardised version (bearing in mind the aws dialect idiosyncrasies above) then that might be the ideal solution - mainly because I dont think terraform-core are going to want to create a generic function which has to bear in mind the aws idiosyncrasies.

**Comment by justinretzolk** [comment]
Hey @gtmtech 👋 Thank you for taking the time to raise this! I really appreciate you laying out all of this information, however, I'm not sure that I completely understand what you're looking to achieve/what is leading the current undesirable behavior. My initial thought is that this might be solved by using a `depends_on` block, but I'd like to get a better idea so that we can take a look at what actions might need to be taken. By chance, can you provide a sample Terraform configuration where you're currently needing to use the `time_sleep` resource?
