### ISSUE TITLE
aws guardduty detector configuration enable malware protection as data source

### ISSUE THREAD

**Issue by nickyamanaka** [hashicorp/terraform-provider-aws#25994]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

https://docs.aws.amazon.com/guardduty/latest/ug/malware-protection.html

NOTE: This deals *only* with the detector configuration
Requires update to 1.44.63 

### New or Affected Resource(s)

* aws_guardduty_detector

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.



resource "aws_guardduty_detector" "self" {
  enable                       = true
  finding_publishing_frequency = "FIFTEEN_MINUTES"

  datasources {

    malware_protection {
      scan_ec2_instance_with_findings {
        ebs_volumes {
          enable = true
        }
      }
    }
  }
}


```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2022/07/malware-protection-feature-amazon-guardduty/).
[Blog post](https://aws.amazon.com/blogs/aws/new-for-amazon-guardduty-malware-detection-for-amazon-ebs-volumes/).

* #22859
* #22987

**Comment by cyn110** [comment]
This is a duplicate with https://github.com/hashicorp/terraform-provider-aws/issues/25992

**Comment by nickyamanaka** [comment]
@cyn110 is not, one is detector, one is organization config
