### ISSUE TITLE
aws_mq_broker | mixing audit with general logging

### ISSUE THREAD

**Issue by valugi** [hashicorp/terraform-provider-aws#25996]
### Terraform CLI and Terraform AWS Provider Version
0.11.11

### Affected Resource(s)
aws_mq_broker

### Terraform Configuration Files

```hcl
resource "aws_mq_broker" "aws_mq_rabbit_dev" {
  broker_name = "TEST-MQ"
  engine_type        = "RabbitMQ"
  engine_version     = "3.8.6"
  host_instance_type = "mq.t3.micro"
  user {
    username = "admin"
    password = "${var.rabbitmq_password}"
    console_access = true
  }
  apply_immediately          = true
  auto_minor_version_upgrade = false
  deployment_mode    = "SINGLE_INSTANCE"
  encryption_options {}
  logs {
    general = true
  }
  maintenance_window_start_time {
    day_of_week = "SUNDAY"
    time_of_day = "02:00"
    time_zone = "CET"
  }
  publicly_accessible  = false
  security_groups    = ["${aws_security_group.mq_sg.id}"]
  subnet_ids         = ["${module.network.private_subnets[0]}"]

}
```

### Expected Behavior

To enables general logging via CloudWatch.

### Actual Behavior
Complains about audit log not being available. But audit log is another option that defaults to false. I did not ask for that.

```STDERR: * aws_mq_broker.aws_mq_rabbit_dev: BadRequestException: Audit logging is not supported for RabbitMQ brokers.```

### Steps to Reproduce

1. `terraform apply`

**Comment by justinretzolk** [comment]
(noting for tracking, waiting on response on #26000)

**Comment by valugi** [comment]
Upgraded to 0.13.6 to make it work. Documentation could be better.
