### ISSUE TITLE
aws_mq_broker | encryptionOptions is not supported for RabbitMQ brokers

### ISSUE THREAD

**Issue by valugi** [hashicorp/terraform-provider-aws#25998]
### Terraform CLI and Terraform AWS Provider Version
0.11.11 - but irrelevant - this is a documentation issue. 
AWS specifies that this is not an option, but your documentation does not.
https://docs.aws.amazon.com/cli/latest/reference/mq/create-broker.html
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mq_broker#encryption_options

### Affected Resource(s)

* aws_mq_broker

### Terraform Configuration Files

```hcl
  encryption_options {}
```

### Expected Behavior

Encrypt service or document that is not possible.

### Actual Behavior

Error:
` STDERR: * aws_mq_broker.aws_mq_rabbit_dev: BadRequestException: encryptionOptions is not supported for RabbitMQ brokers`

### Steps to Reproduce

1. `terraform apply`

**Comment by justinretzolk** [comment]
(noting for tracking, waiting on response on #26000)

**Comment by levinotik** [comment]
Noticed this as well. Documentation [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mq_broker#encryption_options) should be updated:

**Comment by valugi** [comment]
Upgraded to 0.13.6 to make it work. Documentation could be better.
