### ISSUE TITLE
will support for CloudWAN resources be included in this provider?

### ISSUE THREAD

**Issue by tjstansell** [hashicorp/terraform-provider-aws#26018]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Will the resources required to manage CloudWAN be natively supported in this provider?  This was originally brought up in #23782 but subsequently closed without explanation.  The resources are currently supported in the `awscc` provider, but will that always be required to manage CloudWAN resources?  

### New or Affected Resource(s)

* `aws_networkmanager_core_network`
* `aws_networkmanager_vpc_attachment`
* etc...

### References

* #23782 - this was closed by #24368 even though it only implemented a single data source, not all resources.

**Comment by ewbankkit** [comment]
@tjstansell Thanks for raising this issue.
It has already been noticed in #25835. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
