### ISSUE TITLE
loadbalancer missing attribute routing.http.preserve_host_header.enabled

### ISSUE THREAD

**Issue by mikebollandajw** [hashicorp/terraform-provider-aws#26024]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please can you add the ability to set the additional attributes on the load balancer

In this case routing.http.preserve_host_header.enabled as described here https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html

### New or Affected Resource(s)

* aws_lb

### Potential Terraform Configuration

```hcl
resource "aws_lb" "example" {
  name               = "example"
  load_balancer_type = "network"

  subnet_mapping {
    subnet_id     = aws_subnet.example1.id
    allocation_id = aws_eip.example1.id
  }

  subnet_mapping {
    subnet_id     = aws_subnet.example2.id
    allocation_id = aws_eip.example2.id
  }

  preserve_host_header = true
}
```

**Comment by bschaatsbergen** [comment]
Picking this up
