### ISSUE TITLE
AWS Global Accelerator IPv6 Support

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#26023]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Starting today, you can provide better network performance by routing IPv6 traffic through Global Accelerator to your application endpoints running in AWS Regions.

### New or Affected Resource(s)

* [`aws_globalaccelerator_accelerator`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/globalaccelerator_accelerator)

### Potential Terraform Configuration

```hcl
resource "aws_globalaccelerator_accelerator" "example" {
  name            = "Example"
  ip_address_type = "DUAL_STACK"
}
```

### References

[Blog post](https://aws.amazon.com/blogs/aws/new-for-aws-global-accelerator-internet-protocol-version-6-ipv6-support/).

Requires [AWS SDK for Go v1.44.64](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.64):

* #26017

**Comment by bschaatsbergen** [comment]
I'll happily pick this up

**Comment by bschaatsbergen** [comment]
As v1.44.64+ is part of main now, I've updated the PR accordingly.
