### ISSUE TITLE
provider: Add scrubbing for sensitive data in logs

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#26029]
When the log level is set to `TRACE`, the AWS Provider is logging sensitive values such as access keys.

The AWS SDKs for Go provide some scrubbing for logs, but more checks need to be added.

Determine what is leaking the sensitive values. If needed, evaluate hashicorp/terraform-plugin-sdk#1006, which will be released in `terraform-plugin-sdk` v2.20.0. This will require adding the option to set the HTTP transport in `aws-sdk-go-base`.

### References

* Depends on hashicorp/aws-sdk-go-base#323
* Related to #26028

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/pull/26732 introduce CodeQL code scanning which scans for [_Clear-text logging of sensitive information_](https://codeql.github.com/codeql-query-help/go/go-clear-text-logging/) - log statements that print structures containing password fields.
We will continue to ensure that such logging is removed but this does not handle any other sensitive data.

**Comment by gdavison** [comment]
Depends on #15090 to use `context.Context` everywhere
