### ISSUE TITLE
provider: To support VCR-style testing, allow setting HTTP Transport in `aws-sdk-go-base` configuration

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#26028]
VCR-style testing requires overriding the HTTP Transport to read from locally stored responses. The HTTP Transport is currently configured inside [`aws-sdk-go-base`](https://github.com/hashicorp/aws-sdk-go-base).

Update provider configuration to support setting the HTTP Transport during acceptance testing.

### References

* Depends on hashicorp/aws-sdk-go-base#323

**Comment by ewbankkit** [comment]
Supported via #25587.
