### ISSUE TITLE
Support for gp3 on aws_elasticsearch_domain ebs_options volume_type

### ISSUE THREAD

**Issue by ryan-dyer-sp** [hashicorp/terraform-provider-aws#26045]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Elasticsearch now supports GP3 volume types.  Please add functionality to support gp3 as a volume type.

### New or Affected Resource(s)

aws_elasticsearch_domain

### Potential Terraform Configuration

```hcl
resource "aws_elasticsearch_domain" "domain" {
	ebs_options {
		volume_type = "gp3"
	}
}
```

### References

https://docs.aws.amazon.com/opensearch-service/latest/developerguide/limits.html#ebsresource

**Comment by justinretzolk** [comment]
Hey @ryan-dyer-sp 👋 Thank you for taking the time to raise this! The `aws_elasticsearch_domain` resource [uses `elasticsearch.VolumeType_Values()`](https://github.com/hashicorp/terraform-provider-aws/blob/55571a4e22864eeb30da7ccc3888aa4ae2a22aea/internal/service/elasticsearch/domain.go#L396) to validate the value passed to the `volume_type` argument. This function was [updated yesterday](https://github.com/aws/aws-sdk-go/pull/4494) in AWS Go SDK version `1.44.65` to include `gp3`, so this should work automatically in AWS Provider `4.25.0` when it's released.

**Comment by ReadyElbow** [comment]
@justinretzolk Thanks for quickly acting on this. Do you know if Terraform supports the advanced configuration options that GP3 supports?

Within the AWS GUI, we can control IOPs/Throughput but I don't think TF will currently support them

**Comment by ewbankkit** [comment]
@ReadyElbow The `throughput` attribute will need to be added to the `ebs_options` configuration block.
