### ISSUE TITLE
Error setting SNS Topic Invalid parameter: Policy Error: PrincipalNotFound

### ISSUE THREAD

**Issue by sparkmuse** [hashicorp/terraform-provider-aws#26041]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.2.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.23.0

### Affected Resource(s)

* aws_sns_topic
* aws_sns_topic_policy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  region = "eu-central-1"
}

resource "aws_sns_topic" "topic" {
  name = "sample-topic"
}

locals {
  accounts = [111111111111, 222222222222]
}

resource "aws_sns_topic_policy" "access" {
  count  = length(local.accounts) == 0 ? 0 : 1
  arn    = aws_sns_topic.topic.arn
  policy = data.aws_iam_policy_document.access.json
}

data "aws_iam_policy_document" "access" {
  statement {
    actions = [
      "sns:Subscribe"
    ]
    effect = "Allow"
    resource = [
       "arn:aws:sns:eu-central-1:333333333333:sample-topic"
    ]
    principals {
      identifiers = toset([for i in local.accounts : "arn:aws:iam::${i}:root"])
      type        = "AWS"
    }
  }
}
```

### Debug Output
Here is the debug output [debug.txt](https://gist.github.com/sparkmuse/52484427bfb46e841a1b0fbb6483b811)

### Expected Behavior
A topic with a access policy like below is created.
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::111111111111:root",
          "arn:aws:iam::222222222222:root"
        ]
      },
      "Action": "sns:Subscribe",
      "Resource": "arn:aws:sns:eu-central-1:333333333333:sample-topic"
    }
  ]
}
```

### Actual Behavior
An error occurred. 

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids

I am running from the terminal with a profile set for AWS.

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @sparkmuse 👋 Thank you for taking the time to raise this! So that we have all of the information to help us to look into this, can you update the issue description with debug logs (redacted as needed)?

**Comment by sparkmuse** [comment]
@justinretzolk I have updated the ticket with the requested information.

**Comment by sparkmuse** [comment]
It seems that there is some check that the account must exist for the resource to create a valid policy. I had it changed from my dummy to a real account and now everything works.

Maybe a message would point to the people to the solution.
