### ISSUE TITLE
Terraform fails to request sts/GetCallerIdentity but aws sts get-caller-identity succeeds

### ISSUE THREAD

**Issue by joelbiffin** [hashicorp/terraform-provider-aws#26043]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v1.1.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.23.0
```
### Affected Resource(s)

* Any aws resources
* aws_s3_bucket

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
    required_providers {
        aws = {
            source  = "hashicorp/aws"
            version = "~> 4.0"
        }
    }
}

provider "aws" {
    access_key = var.aws_access_key
    region     = var.aws_region
    secret_key = var.aws_secret_key
}

resource "aws_s3_bucket" "lambda_bucket" {
    bucket = "lambda-source-code"
}
```

### Debug Output

[Here's a gist](https://gist.github.com/joelbiffin/1830a553c5d23196d28de918bd463566) containing the output from `TF_LOG=DEBUG TF_LOG_PATH="debug.log" terraform plan -var-file=".secrets.tfvars"`

### Panic Output

N/A

### Expected Behavior

I should have received the plan output for provisioning an S3 bucket in AWS

### Actual Behavior

The `terraform plan` command hangs and returns the following error message:

```
│ Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: operation error STS: GetCallerIdentity, exceeded maximum number of attempts, 9, https response error StatusCode: 0, RequestID: , request send failed, Post "https://sts.eu-west2.amazonaws.com/": dial tcp: lookup sts.eu-west2.amazonaws.com on 194.168.4.100:53: no such host
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on main.tf line 11, in provider "aws":
│   11: provider "aws" {
│ 
```

From inspection of the log files, it looks like the HTTP request to `https://sts.eu-west2.amazonaws.com/` never receives a response and times out. This request is then made 10 times in total before the `terraform plan` process returns the above error message.

I have verified that using the same credentials via the `aws` CLI, the request to STS succeeds:

```
$ aws sts get-caller-identity
{
    "UserId": "A*******************O",
    "Account": "2**********9",
    "Arn": "arn:aws:iam::2**********9:user/TerraformInfrastructureManager"
}
```

It's worth noting that the `TerraformInfrastructureManager` user is an IAM user with `AdministrativeAccess`.

I have attempted to debug a DNS related issue with `dig` based on the error message (although I am a little out of my depth when it comes to debugging these network issues):

```
$ dig @194.168.4.100 https://sts.eu-west2.amazonaws.com/ 

; <<>> DiG 9.10.6 <<>> @194.168.4.100 https://sts.eu-west2.amazonaws.com/
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 36178
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;https://sts.eu-west2.amazonaws.com/. IN	A

;; AUTHORITY SECTION:
.			9470	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2022072900 1800 900 604800 86400

;; Query time: 21 msec
;; SERVER: 194.168.4.100#53(194.168.4.100)
;; WHEN: Fri Jul 29 11:13:21 BST 2022
;; MSG SIZE  rcvd: 139
```

### Steps to Reproduce

1. Create some `.secrets.tfvars` file with the following variables:
    ```
    aws_access_key = "<redacted>"
    aws_secret_key = "<redacted>"
    aws_region = "eu-west2"
    ```
2. `terraform init`
3. `terraform plan -var-file=".secrets.tfvars"`

### Important Factoids

- I am running an out-of-the-box AWS setup with no existing services provisioned.
- The only change that has been made to AWS prior to running `terraform plan` is to create the IAM user with `AdministrativeAccess` called `TerraformInfrastructureManager`.
- I have no local Firewall running on my machine, nor on my local network
- STS is enabled across all AWS regions (as well as globally) on my account

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/15534
* https://github.com/hashicorp/terraform-provider-aws/issues/5419
* https://discuss.hashicorp.com/t/terraform-hangs-on-terraform-plan/7858

**Comment by joelbiffin** [comment]
To eliminate the DNS lookup issue, I still see the same issue when using cellular data on a different network.

**Comment by justinretzolk** [comment]
Hey @joelbiffin 👋 Thank you for taking the time to raise this! I believe you've got a typo in there -- `eu-west2` rather than `eu-west-2`

**Comment by joelbiffin** [comment]
> Hey @joelbiffin 👋 Thank you for taking the time to raise this! I believe you've got a typo in there -- `eu-west2` rather than `eu-west-2`

Thank you - what a stupid.mistake on my part. Sorry for wasting your time! I really appreciate your help!

**Comment by joelbiffin** [comment]
Closing due to local environment typo

**Comment by justinretzolk** [comment]
Happens to the best of us @joelbiffin! I blame Friday 🙂. Have a good weekend!
