### ISSUE TITLE
SQS Queue import fails with 403 Forbidden

### ISSUE THREAD

**Issue by mshebeko-twist** [hashicorp/terraform-provider-aws#26044]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.2.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.22.0

### Affected Resource(s)

* aws_sqs_queue

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
  resource "aws_sqs_queue" "this" {
      name                                         = "MyQueue"
      delay_seconds                         = 90
      max_message_size                 = 2048
      message_retention_seconds = 86400
      receive_wait_time_seconds   = 10
}
```

### Debug Output
https://gist.github.com/mshebeko-twist/2c8bbb35f232463f122d456e5c468203

### Expected Behavior

Terraform should be able to import SQS Queue

### Actual Behavior
Forbidden response is returned.

### Steps to Reproduce
Deploy sqs queue from AWS Console, and try to import it.

### Important Factoids

I'm an admin of the account and have access to this SQS via console. This module manages multiple resources that would be unavailable to me if I would assume wrong role etc...

**Comment by bschaatsbergen** [comment]
Hi @mshebeko-twist, thanks for taking the time to raise this issue. I've tried to reproduce this but it **seems to work fine** for me.

I would recommend to double check the credentials you're using when invoking the terraform binary - I assume you're either using temporary/static credentials or that originate from a user in your account (double check the permissions for that user).

![Peek 2022-07-30 11-46](https://user-images.githubusercontent.com/58337159/181904934-03f84f51-95c6-46ee-98a9-48d82d43bde6.gif)

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
