### ISSUE TITLE
link broken in documentation

### ISSUE THREAD

**Issue by JustLolo** [hashicorp/terraform-provider-aws#26059]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_object#tags_all

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

the link [default_tags configuration block](https://registry.terraform.io/docs/providers/aws/index#default_tags-configuration-block). it's broken.

[tags_all](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_object#tags_all) - Map of tags assigned to the resource, including those inherited from the provider [default_tags configuration block](https://registry.terraform.io/docs/providers/aws/index#default_tags-configuration-block).

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by bschaatsbergen** [comment]
Hi @JustLolo, thanks for taking the time to raise this issue. I'll prep a PR for it.

**Comment by bschaatsbergen** [comment]
It seems to be broken in many other pages too, will see what I can do.
