### ISSUE TITLE
Provider assumes roles multiple times if ~/.aws/config and assume_role block are both present

### ISSUE THREAD

**Issue by ryancausey** [hashicorp/terraform-provider-aws#26063]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.2.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.24.0
```

### Affected Resource(s)

* provider "aws"

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# main.tf
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}

provider "aws" {
  region = var.aws_region

  assume_role {
    role_arn     = var.assume_role_arn
    session_name = var.assume_role_session_name
  }
}

data "aws_caller_identity" "current" {}

# variables.tf
variable "aws_region" {
  type        = string
  description = "The AWS region to use for any AWS resources or actions."
}

variable "assume_role_session_name" {
  type        = string
  description = "The session name to use when assuming the role required to perform AWS operations"
}

variable "assume_role_arn" {
  type        = string
  description = "The ARN of the role to assume."
}

# local.tfvars

assume_role_session_name = "test-assume-role-precedence"
assume_role_arn          = "arn:aws:iam::<account number>:role/<role name>"
aws_region               = "us-west-2"
```

### Expected Behavior

According to the [version 4 upgrade guide](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade#changes-to-authentication) the `assume_role` block should have taken precedence over the assume role configuration in the `~/.aws/config` file. Thus, only the role in the `assume_role` configuration block should try to be assumed.

### Actual Behavior

The provider first assumes the role as specified in the `[default]` configuration in the `~/.aws/config` file, and then tries to assume the role specified by the `assume_role` block in the provider itself. This fails with a 403 error.

### Steps to Reproduce

1. create an `~/.aws/credentials` file looking something like this:

```ini
[default]
aws_access_key_id=<access key ID here>
aws_secret_access_key=<aws secret access key here>
```

2. create an `~/.aws/config` file looking something like this:

```ini
[default]
role_arn=arn:aws:iam::<account ID here>:role/<role name here>
source_profile=default
role_session_name=config-file-assume-role
region=us-west-2
```

3. take the minimum reproduction code above and place into a folder
4. cd into that folder
5. run `terraform init`
6. change the values in `local.tfvars` for the role arn and session name to some other role and some other session name that is not the same as what is configured in the `~/.aws/config` file.
7. run `terraform plan -var-file local.tfvars`

**Comment by ryancausey** [comment]
@ewbankkit any idea if this will be picked up soon?

**Comment by ryancausey** [comment]
Is there any chance of this being picked up soon?

**Comment by gdavison** [comment]
Hi @ryancausey, thanks for submitting this. This is the expected behaviour for the provider. When a role is assumed, it always starts from some base authentication. If a specific profile or an access key id and secret access key are not provided, it tries the `default` profile. In your case, since the `default` profile already includes assuming a role, it does that before trying to assume the role specified in the provider configuration.
