### ISSUE TITLE
new resource aws_account_primary_contact

### ISSUE THREAD

**Issue by kurtmc** [hashicorp/terraform-provider-aws#26077]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Create a new resource for the newly release API that allows updating the primary contact information:
- https://aws.amazon.com/about-aws/whats-new/2022/07/programmatically-manage-primary-contact-information-aws-accounts
- https://docs.aws.amazon.com/accounts/latest/reference/manage-acct-update-contact-primary.html

### New or Affected Resource(s)

* aws_account_primary_contact

### Potential Terraform Configuration

```hcl
resource "aws_account_primary_contact" "owner" {
  address_line_1     = "123 Any Street"
  city               = "Seattle"
  company_name       = "Example Corp, Inc."
  country_code       = "US"
  district_or_county = "King"
  full_name          = "Saanvi Sarkar"
  phone_number       = "+15555550100"
  postal_code        = "98101"
  state_or_region    = "WA"
  website_url        = "https://www.examplecorp.com"
}

```

**Comment by moogly81** [comment]
We could then remove a manual step when creating an aws account.  It's always nice when that happens.
