### ISSUE TITLE
New resource: Transit Gateway policy table

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#26093]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Transit gateway dynamic routing uses policy tables to route network traffic for AWS Cloud WAN.

### New or Affected Resource(s)

* `aws_ec2_transit_gateway_policy_table`
* `aws_ec2_transit_gateway_policy_table_association`

### Potential Terraform Configuration

```hcl
resource "aws_ec2_transit_gateway_policy_table" "example" {
  transit_gateway_id = aws_ec2_transit_gateway.example.id
}

resource "aws_ec2_transit_gateway_policy_table_association" "example" {
  transit_gateway_policy_table_id = aws_ec2_transit_gateway_policy_table.example.id
  transit_gateway_attachment_id   = aws_ec2_transit_gateway_vpc_attachment.example.id
}
```

### References

Relates https://github.com/hashicorp/terraform-provider-aws/issues/25835.
[User Guide](https://docs.aws.amazon.com/vpc/latest/tgw/tgw-policy-tables.html).
[API reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTransitGatewayPolicyTable.html).

**Comment by bschaatsbergen** [comment]
👀 , I'll happily pick this up.
