### ISSUE TITLE
A duplicate Security Group rule was found

### ISSUE THREAD

**Issue by DBankx** [hashicorp/terraform-provider-aws#26125]
Hi

We tried to apply a new build to our app using terraform and we are now getting an error as seen below

![Screen Shot 2022-08-04 at 6 54 57 AM](https://user-images.githubusercontent.com/61208493/182830397-68ea312c-080b-470c-bea1-648e62008699.png)

This was not happening before and i would like to ask what does terraform do when reapplying formations, does it destroy the current component and creates a new one or is it the other way round. if its the latter i do not see why this issue should exist as it would delete it before it tries to create a new one. But if it creates before deleting could i try to force terraform to use the delete before create method?. Also do you think if i manually delete the security group rules it will make this work? Please i need this help!.

Here is our code to create security group:
```
resource "aws_security_group" "console" {
  name        = "${var.name_prefix}-console"
  description = "${var.name_prefix}-console-access"
  vpc_id      = var.vpc.vpc_id

  tags = {
    Name = "${var.name_prefix}-console"
  }
}

resource "aws_security_group_rule" "all_outbound" {
  security_group_id = aws_security_group.console.id
  type              = "egress"
  from_port         = "0"
  to_port           = "0"
  protocol          = "-1"
  cidr_blocks       = ["0.0.0.0/0"]
  description       = "Allow all outbound traffic"
}


resource "aws_security_group_rule" "default" {
  security_group_id = aws_security_group.console.id
  type              = "ingress"
  from_port         = "22"
  to_port           = "22"
  protocol          = "tcp"
  cidr_blocks       = var.allowed_ssh_ips
  description       = "Access to ssh 22"

  
}
```

**Comment by RealFatCat** [comment]
Hi,
We've got the same issue, but with other resources.
Can you please check, if the `resources` in your `terraform.tfstate` file is empty?
If so, this can be the same issue: https://github.com/hashicorp/terraform-provider-aws/issues/26021
