### ISSUE TITLE
aws_api_gateway_usage_plan with both throttle_settings and throttle generate bad request exception

### ISSUE THREAD

**Issue by xdsl34** [hashicorp/terraform-provider-aws#26128]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.2.6
 provider registry.terraform.io/hashicorp/aws v4.24.0

### Affected Resource(s)

* aws_api_gateway_usage_plan

### Terraform Configuration Files

```hcl
resource "aws_api_gateway_usage_plan" "webhook" {
  for_each = local.webhook_access
  name     = "${each.key}-${terraform.workspace}"

  throttle_settings {
    burst_limit = 100
    rate_limit  = 50
  }
  api_stages {
    api_id = aws_api_gateway_rest_api.gateway.id
    stage  = aws_api_gateway_stage.live.stage_name

    throttle {
      path        = "*/*"
      burst_limit = 25
      rate_limit  = 50
    }
  }
}
```

### Debug Output

https://gist.github.com/xdsl34/12efa3663ecf8ce2229237c3f8658ecb

### Expected Behavior

The plan is applied and throttle is set on the usage plan and at the Resource/Method level

### Actual Behavior

```
│ Error: error updating API Gateway Usage Plan: BadRequestException: Can not define fine grain throttling if usage plan throttle is not defined.
│ 
│   with aws_api_gateway_usage_plan.webhook["pppp-webhook"],
│   on api_gateway.tf line 80, in resource "aws_api_gateway_usage_plan" "webhook":
│   80: resource "aws_api_gateway_usage_plan" "webhook" {
```

### Steps to Reproduce

1. `terraform apply`

### Notes

If we apply first the throttle settings at the usage plan level and after we add the configuration at the Method/Ressource level and we apply again it works well

**Comment by meetreks** [comment]
I am having a look at this issue.
