### ISSUE TITLE
aws_fms_policy always modify resource_type_list

### ISSUE THREAD

**Issue by F-Xu** [hashicorp/terraform-provider-aws#26131]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.2.6 
provider registry.terraform.io/hashicorp/aws v4.24.0

### Affected Resource(s)

* aws_fms_policy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_fms_policy" "sample" {
  name                        = "sample"
  exclude_resource_tags       = false
  remediation_enabled         = false
  delete_all_policy_resources = true
  resource_type_list = [
    "AWS::ElasticLoadBalancingV2::LoadBalancer"
  ]
...
}
```

### Debug Output

`terraform apply`
  aws_fms_policy.sample will be updated in-place
  ~ resource "aws_fms_policy" "sample" {
        id                                 = "8b3e3e0e-d1ab-4660-822d-9b0549c2fc8d"
        name                               = "sample"
      ~ resource_type_list                 = [
          **+ "AWS::ElasticLoadBalancingV2::LoadBalancer",**
        ]
        tags                               = {}
        # (9 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

### Expected Behavior

no updates if run `terraform apply` with the same code repeatedly.

### Actual Behavior

run `terraform apply` with the same code repeatedly updates the resource_type_list to add  "AWS::ElasticLoadBalancingV2::LoadBalancer" each time

### Steps to Reproduce

1. run `terraform apply`

**Comment by neilfarmer** [comment]
Can confirm this bug with:
Terraform: 1.2.3
Aws-provider: 4.16.0

After adding a new `resource_type_list` resource and running an apply, I do not see the aws_fms_policy updated in the AWS Console.
After rerunning the plan, I see it tries to add the `resource_types_list` again.
If I add the resource type manually via the console, then run the plan, terraform has no changes.

So it appears terraform applies the code to the state file but does not update the resource in AWS
