### ISSUE TITLE
Activate AWS User-Defined Cost Allocation Tags using terraform

### ISSUE THREAD

**Issue by Papina** [hashicorp/terraform-provider-aws#26139]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There doesn't seem to be anyway of activating the newly created tags by terraform. So I still need to log into my payer account and manually click a button or two to activate the tags.

There is now an API that can be used to do this: https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_UpdateCostAllocationTagsStatus.html#API_UpdateCostAllocationTagsStatus_RequestSyntax

### New or Affected Resource(s)

aws_account_XXXX

### Potential Terraform Configuration

```hcl
resource "aws_account_costallocationtagsstatus" "example" {
   content = <<EOF
      {
         "Status": "Service",
         "TagKey": "Active"
      },
      {
         "Status": "Centre",
         "TagKey": "Inactive"
      }
EOF
}
```

### References
https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_UpdateCostAllocationTagsStatus.html#API_UpdateCostAllocationTagsStatus_RequestSyntax

https://github.com/hashicorp/terraform-provider-aws/issues/24307

**Comment by justinretzolk** [comment]
Hey @Papina 👋 Thank you for taking the time to raise this! It looks like this functionality was added in provider version `4.20.0` as the [`aws_ce_cost_allocation_tag` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ce_cost_allocation_tag). Since it looks like this functionality has already been added, I'll close this issue out. If you feel I've done this in error, please do let me know.
