### ISSUE TITLE
Terraform destroy of log configuration for WAF does not remove the old log group from the service linked role

### ISSUE THREAD

**Issue by paulalex** [hashicorp/terraform-provider-aws#26165]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.2.4
on darwin_amd64
```

### Affected Resource(s)

* `aws_wafv2_web_acl_logging_configuration`

### Terraform Configuration Files

```hcl
* aws_wafv2_web_acl
* aws_cloudwatch_log_group
* aws_wafv2_web_acl_logging_configuration
```

### Expected Behavior

Running a terraform destroy removes the log group created as part of the `terraform apply` from the service linked role used for aws logs.

### Actual Behavior

The role stays updated with the log group name even though a `terraform destroy` has been applied, for example in the following output from running the command:

`aws logs describe-resource-policies | jq -r '.[] | select(.[].policyName == "AWSLogDeliveryWrite20150319") | .[].policyDocument' | jq`

```
"arn:aws:logs:eu-west-2:123:log-group:aws-waf-logs-paul-new-env:log-stream:*",
"arn:aws:logs:eu-west-2:123:log-group:aws-waf-logs-totally-new-env:log-stream:*",
"arn:aws:logs:eu-west-2:123:log-group:aws-waf-logs-totally-totally-new-env:log-stream:*"
```
In the above snippet all 3 environments have been deleted already, but this meant that reapplying terraform due to a permissions issue with the pipeline role was not consistent because if the service linked role had already been updated at some point successfully with the log group the build would pass, if however it was for a totally new environment we would get a permissions error (unrelated to this bug) due to IAM changes. 

However, the effect of this is that some environments did rebuild ok because the service role was never updated to remove the old log group.

The following error would present for new environments (again not caused by this bug, just confused by it):

```
Error: error putting WAFv2 Logging Configuration for resource (arn:aws:wafv2:eu-west-2:123:regional/webacl/waf-acl-totally-new-env/dc15772a-69b9-4c9f-b39e-4865a23ab37a): WAFLogDestinationPermissionIssueException: Unable to deliver logs to the configured destination. You might need to grant log delivery permissions for the destination. If you're using S3 as your log destination, you might have exceeded your bucket limit.

  with aws_wafv2_web_acl_logging_configuration.waf_acl_lc,

  on main.tf line 190, in resource "aws_wafv2_web_acl_logging_configuration" "waf_acl_lc":

 190: resource "aws_wafv2_web_acl_logging_configuration" "waf_acl_lc" {
```
### Steps to Reproduce

1. `terraform apply`
2. `aws logs describe-resource-policies | jq -r '.[] | select(.[].policyName == "AWSLogDeliveryWrite20150319") | .[].policyDocument' | jq`
3. `terraform destroy`
4. `aws logs describe-resource-policies | jq -r '.[] | select(.[].policyName == "AWSLogDeliveryWrite20150319") | .[].policyDocument' | jq`
5. Observe that the now destroyed and non existent log group created by step 1 and destroyed by step 3 is still present in the role.

**Comment by sam-delap** [comment]
[#14750](https://github.com/hashicorp/terraform/issues/14750) in the main terraform GitHub might shed some light on this... sometimes the last set of info to be pushed to logs is pushed AFTER `terraform destroy` finishes running. If you've given the role that pushes data to your log group `CreateLogGroup` permissions, this will re-create the log group and, thus, keep it as existing. 

The solutions in that example are more workarounds than anything, you either need to remove permissions from the role to create log groups & create the groups manually, or double-check that each log group stays destroyed after `terraform destroy` finishes running. Hope they can help!

**Comment by justinretzolk** [comment]
Hey @paulalex 👋 Thank you for taking the time to raise this, and thank you to @sam-delap for linking to that helpful related issue! Based on that linked issue, it seems this is due to a quirk with the AWS API. With that in mind (and given that there are workarounds provided in the linked issue), we'll close this issue out for now. If you feel we've done this in error, please do let us know.
