### ISSUE TITLE
Error waiting for KMS Key tag propagation: timeout while waiting for state to become 'TRUE' -- KMS tag bug

### ISSUE THREAD

**Issue by arzietlow** [hashicorp/terraform-provider-aws#26174]
### Community Note
  
  * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
  * Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
  * If you are interested in working on this issue or have submitted a pull request, please leave a comment
  
### Terraform CLI and Terraform AWS Provider Version
  
  Terraform Version: v0.13.4
  Terraform AWS Provider version: 4.9.0
  
### Affected Resource(s)
  
  * aws_kms_key
  
### Terraform Configuration Files
  
  ```hcl
  
  locals {  
    test_tags = {
      "tagkey2"          = "Tagvalue2"
      "addTagtest1"      = "addTagtest1"
    }
  }
  
  resource "aws_kms_key" "tag_timeout_test" {
    tags                    = local.test_tags
  }
  
  ```
 
### Debug Output
[Gist here](https://gist.github.com/arzietlow/b59d192dec8af27d725aec4f15b8cb4c)
 
### Expected Behavior
  
Terraform updates the KMS key's tags without producing a timeout error
  
### Actual Behavior
 
Terraform times out after 10 minutes
  
### Steps to Reproduce
    
  1.  Add or remove tags on an existing KMS key managed by terraform
  2. `terraform apply`
 
  
### References
  
Related to issue [#23592](https://github.com/hashicorp/terraform-provider-aws/issues/23592) where the solution back then was to increase the timeout from 5m to 10m

Note: a location in S3 is the backend used for the statefile

**Comment by Snowisnticecream** [comment]
Is there any update on this one? Our teams run into this on almost a daily basis and it feels like it is starting to happen more due to the number of reports we are seeing. It would be great if the limit was increased again or if the underlying problem was resolved. Currently teams have their pipelines fail regularly due to this and then need to run a fresh pipeline and new TF Apply that then passes.

**Comment by Wolfsrudel** [comment]
+1 due to running into the same problem.
In my case it's happening when trying to add ignoring changes on a special tag (everything configured at the provider level).
