### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Teeworks1** [hashicorp/terraform-provider-aws#26202]
Hi i get this error when i run terraform plan:
Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: operation error STS: GetCallerIdentity, https response error StatusCode: 400, RequestID: 73390445-95df-48e8-b897-1e06913a4946, api error IncompleteSignature: '/20220809/us-east-1/sts/aws4_request' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 Credential=SAKIA5GT5RFZMSQI2BR6V /20220809/us-east-1/sts/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date, Signature=a0011c33fdf04a7739ed5ed4421c3ea2ba6ad3f3365cde8d07e7c5c319ed5d3e'.

What am i doing wrong ?

**Comment by justinretzolk** [comment]
Hey @Teeworks1 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?

**Comment by Teeworks1** [comment]
Thanks for your email . Am I to fill in all the information as stated in
the template ? I’m new on the forum as this is my first day here so I’m
really not sure if that’s what yoh want me to do . I can see it’s numbers
1-89. I am trying to create an ec2 server amd when I entered all the
required inputs and configuration and executed terraform plan . It
displayed that error

**Comment by good92** [comment]
Activate you AccessKey: https://aws.amazon.com/premiumsupport/knowledge-center/create-access-key/

**Comment by justinretzolk** [comment]
@Teeworks1 welcome to the community! 🎉 The template is indeed 89 lines long, but quite a bit of it is notes to help give an idea of the information we're looking for. This information helps us to understand better what is occurring. That said, the error message seems to indicate that there's an issue with the credentials that you provided to the provider, so I'd recommend starting with verifying that you have supplied valid credentials. If you're still having issues at that point, the additional information provided in the template will help us to point you in the right direction.

**Comment by gdavison** [comment]
Hi @Teeworks1. Since you haven't responded, I'm going to close this issue. If you're still having trouble, please open a new issue and complete the template
