### ISSUE TITLE
aws_glue_job provide execution class flex

### ISSUE THREAD

**Issue by jornfranke** [hashicorp/terraform-provider-aws#26203]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
AWS recently introduced the [Glue flex](https://aws.amazon.com/de/blogs/big-data/introducing-aws-glue-flex-jobs-cost-savings-on-etl-workloads/) feature, which allows to save costs on Glue jobs that are not time critical. The TF resource aws_glue_job needs to support this new feature.

This means it needs to have a new attribute: execution_class which can be STANDARD (Default) or FLEX. If the execution_class is Flex then glue_version must be minimal "3.0"

### New or Affected Resource(s)

* aws_glue_job

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "aws_glue_job" "example" {
  name     = "example"
  role_arn = aws_iam_role.example.arn
  execution_class = "FLEX"
  command {
    script_location = "s3://${aws_s3_bucket.example.bucket}/example.py"
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2022/08/aws-glue-supports-flex-execution-option/).
[Blog post](https://aws.amazon.com/blogs/big-data/introducing-aws-glue-flex-jobs-cost-savings-on-etl-workloads/).

Requires [AWS SDK for Go v1.44.71](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.71): #26181.

**Comment by moreandres** [comment]
Related to #26188
