### ISSUE TITLE
Provider with assume_role sporadically timing out with STS

### ISSUE THREAD

**Issue by amancevice** [hashicorp/terraform-provider-aws#26216]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.2.6
on darwin_amd64

### Affected Resource(s)

* aws (provider)

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-east-1"
  assume_role { role_arn = var.AWS_ROLE_ARN }
  default_tags { tags = local.tags }
}
```

### Debug Output

_Issue is non-predictable so no debug logs available_

### Expected Behavior

This just started happening recently (maybe in the past 3-4 months), but I routinely get timeout errors with AWS STS using a provider that assumes a role.

After running `terraform apply` I would expect the application to finish successfully every time, assuming the configuration is valid.

### Actual Behavior

The plan will proceed accordingly but the apply will _sometimes_ fail with this message:

```
Error: error configuring Terraform AWS Provider: IAM Role (arn:aws:iam::[redacted]:role/[redacted]) cannot be assumed.

There are a number of possible causes of this - the most common are:
  * The credentials used in order to assume the role are invalid
  * The credentials do not have appropriate permission to assume the role
  * The role ARN is not valid

Error: operation error STS: AssumeRole, https response error StatusCode: 0, RequestID: , request send failed, Post "https://sts.us-east-1.amazonaws.com/
 dial tcp: lookup sts.us-east-1.amazonaws.com on 192.168.1.1:53: read udp 192.168.1.68:64362->192.168.1.1:53: i/o timeout
```

It's very possible this is an issue on AWS' side, I'm not sure, but I think the solution would be to add some kind of retry with backoff for the STS API call or extending any that already exist.

### Steps to Reproduce

1. `terraform apply`
2. Occasionally see error
3. Retry step 1

### Important Factoids

For context, I am using Terraform Cloud (with local provisioning) as my remote state.

**Comment by tgoodsell-tempus** [comment]
I think this is some sort of network level throttle which is occurring, I've seen the same issue when doing a large plan process with several accounts in a short period of time. 

IMO, a valid solution is checking for HTTP Status Code == `0` and including that as a retryable error.

**Comment by tgoodsell-tempus** [comment]
To the above point, since HTTP status code `0` isn't real and is usually the result of the HTTP call not responding / something failing. So I'm more thinking the check would be for instances when that occurs.

**Comment by amancevice** [comment]
I haven't experienced this in some time, so closing it out
