### ISSUE TITLE
Please add support for EMR Public Block Access

### ISSUE THREAD

**Issue by absa-rsuarez** [hashicorp/terraform-provider-aws#26215]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
As described in this closed issue:  https://github.com/hashicorp/terraform-provider-aws/issues/9853 

### New or Affected Resource(s)

* aws_emr_block_public_access_configuration

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

resource "aws_emr_block_public_access_configuration" "example" {
  block_public_security_group_rules = true

  permitted_public_security_group_rule_range {
    min_range = 22
    max_range = 22
  }

  permitted_public_security_group_rule_range {
    min_range = 100
    max_range = 101
  }
}

```

### References

* [AWS Documentation](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-block-public-access.html)

**Comment by bschaatsbergen** [comment]
Hi @absa-rsuarez, thanks for taking the time to raise this feature request. I'll happily look into it.
