### ISSUE TITLE
Terraform plan for aws_ssm_parameter outputs insecure_value as sensitive on hashicorp/aws v4.25.0

### ISSUE THREAD

**Issue by abhishekshukla247** [hashicorp/terraform-provider-aws#26225]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

{
  "terraform_version": "1.2.7",
  "platform": "darwin_amd64",
  "provider_selections": {
    "registry.terraform.io/hashicorp/aws": "4.25.0"
  },
  "terraform_outdated": false
}

### Affected Resource(s)

* aws_ssm_parameter

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ssm_parameter" "test" {
  name        = "test"
  description = "SSM test param"
  type        = "String"
  insecure_value = "this_is_test_value"
  overwrite = true
}
```

### Expected Behavior

plan output should **NOT** have - value          = (sensitive value)

### Actual Behavior

Terraform will perform the following actions:

  # aws_ssm_parameter.test will be created
  + resource "aws_ssm_parameter" "test" {
      + arn            = (known after apply)
      + data_type      = (known after apply)
      + description    = "checkov test param"
      + id             = (known after apply)
      + insecure_value = "this_is_test_value"
      + key_id         = (known after apply)
      + name           = "test"
      + overwrite      = true
      + tags_all       = (known after apply)
      + tier           = (known after apply)
      + type           = "String"
      + value          = (sensitive value)
      + version        = (known after apply)
    }

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### References

Based on issue https://github.com/hashicorp/terraform-provider-aws/issues/9090 the fix was added for insecure_value in provider version 4.22.0 but when I add insecure_value for type String, the plan output still mentions **+ value          = (sensitive value)**

* #9090

**Comment by justinretzolk** [comment]
Hey @abhishekshukla247 👋 Thank you for taking the time to raise this! In this case, the `insecure_value` argument is _never_ marked as sensitive, while the `value` is _always_ marked as sensitive, and you're only able to specify one or the other.

If you have a need for the value to not be marked as sensitive, supply the `insecure_value` argument, which will then show the actual value in the plan (as your example output shows). You can then also refer to this value by using `aws_ssm_parameter.test.insecure_value`.

**Comment by abhishekshukla247** [comment]
> Hey @abhishekshukla247 👋 Thank you for taking the time to raise this! In this case, the `insecure_value` argument is _never_ marked as sensitive, while the `value` is _always_ marked as sensitive, and you're only able to specify one or the other.
> 
> If you have a need for the value to not be marked as sensitive, supply the `insecure_value` argument, which will then show the actual value in the plan (as your example output shows). You can then also refer to this value by using `aws_ssm_parameter.test.insecure_value`.

I did supply on insecure_value in my resource definition. I have posted the same in my problem statement above. I will re-post it - 
```
resource "aws_ssm_parameter" "test" {
  name        = "test"
  description = "SSM test param"
  type        = "String"
  insecure_value = "this_is_test_value"
  overwrite = true
}
```
Please let me know what is wrong with this.

**Comment by posquit0** [comment]
@abhishekshukla247 The result is reasonable because the `value` output has a sensitive property even if no value is set! :)

**Comment by justinretzolk** [comment]
Hey @abhishekshukla247 👋 The `value` parameter is [both `Optional` and `Computed`](https://github.com/hashicorp/terraform-provider-aws/blob/ba986c9ec5fc1db0e8deb4028e799e05be1bfa35/internal/service/ssm/parameter.go#L104-L106). This means that if a value is not supplied, it will be computed automatically, and whether or not you use a `insecure_value` or a `value`, both will always appear in the plan/apply logs as you're seeing here. I hope that clarifies a bit, but if you have additional questions, I'm more than happy to continue the conversation! 🙂
