### ISSUE TITLE
Add support for networkmanager to peer with AWS Transit Gateway

### ISSUE THREAD

**Issue by NetDevAutomate** [hashicorp/terraform-provider-aws#26222]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add a new networkmanager resource to create a peering request from a Core Network to AWS Transit Gateway.

### New or Affected Resource(s)

* aws_networkmanager_transit_gateway_peering_attachment

### Potential Terraform Configuration

```hcl
resource "aws_networkmanager_transit_gateway_peering_attachment" "example" {
  global_network_id           = aws_networkmanager_global_network.example.id
  peer_account_id              = aws_ec2_transit_gateway.peer.owner_id
  peer_region                      = data.aws_region.peer.name
  transit_gateway_id          = aws_ec2_transit_gateway.local.id
}
```

Relates https://github.com/hashicorp/terraform-provider-aws/issues/25835.

**Comment by drewmullen** [comment]
I'm working on an `attachment_acceptor` resource that will pair with this proposal. however, the tgw type will have to be added to the acceptor

**Comment by ewbankkit** [comment]
New resource(s) added in #26264:

* `aws_networkmanager_transit_gateway_peering`
* `aws_networkmanager_transit_gateway_route_table_attachment`
