### ISSUE TITLE
aws_s3_object data source fails on destroy with a 404 if object does not exist

### ISSUE THREAD

**Issue by c4milo** [hashicorp/terraform-provider-aws#26228]
This happens during `terraform destroy`, when Terraform is refreshing the state. The expected behavior is for the `terraform destroy` operation to be idempotent by having the providers ignore read errors since the object is already deleted or missing.

**Comment by teddylear** [comment]
@ewbankkit I can try to take a look into this if that's alright.

**Comment by c4milo** [comment]
@ewbankkit, please let me know if we can help fixing this.

**Comment by teddylear** [comment]
@c4milo @ewbankkit Looking more into this, is this for the data source or resource? I'm not finding a delete for the `aws_s3_object` data source.

**Comment by c4milo** [comment]
@teddylear, during `terraform destroy` operations, terraform refreshes state and that's when data sources fail, literally any data source missing its remote objects will fail. I verified the GCP provider and their object datasource will also fail.

**Comment by teddylear** [comment]
@c4milo Is this WIP PR I attached the behavior you want? With this the `aws_s3_object` data source will not throw an error if the key does not exist. However, this will not throw an error on initial creation of the data source object. Also if this does look good, I can do the same if the bucket does not exist. 

If this does look good, @ewbankkit for testing this should I add a unit test for a clean delete in this case? Or are these types of situations not tested currently.

**Comment by c4milo** [comment]
On apply, it should throw an error. It should only ignore 404s or don’t read the source on destroy.

**Comment by teddylear** [comment]
@c4milo Can you please give an example of one of the ec2 data sources that has the behavior that you want? Looking at `aws_s3_object` data source file [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/s3/object_data_source.go), I'm not sure how this would work as there is only a `Read` function for the data source which is used for terraform applies and refreshes.

**Comment by c4milo** [comment]
@teddylear, I'm not aware of data source resources that work like that to be honest. I only know that their current behavior break idempotency of destroy operations.

**Comment by c4milo** [comment]
This may have been introduced here: https://github.com/hashicorp/terraform/pull/27408
