### ISSUE TITLE
Support for linux settings on EKS node groups

### ISSUE THREAD

**Issue by carlos4ndre** [hashicorp/terraform-provider-aws#26221]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, in order to custom things such as sysctl (e.g., net.ipv4.tcp_keepalive_time) at the host level, I believe one has to explicitly tailor the `UserData` section in the [EC2 launch template](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#launch_template) with the desired changes to the node and then run the [/etc/eks/bootstrap.sh](https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh) script.

I wonder if it would be possible to expose some attributes to achieve this, similar to what we have for [AKS](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster_node_pool#linux_os_config) and [GKE](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#linux_node_config)?

### New or Affected Resource(s)

* aws_eks_node_group

**Comment by mattburgess** [comment]
Hi @carlos4ndre - the AWS API for EKS currently doesn't expose such settings for us to configure. If you have a support contract with AWS it might be worth asking them if there are any plans to introduce such a feature, as it sounds a lot easier to use than the current bootstrap process. I guess the other option might be to bake those sysctl settings into a custom AMI then configure your launch template to use that.
