### ISSUE TITLE
r/`aws_networkmanager_vpc_attachment`

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform-provider-aws#26226]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_networkmanager_vpc_attachment

### Potential Terraform Configuration

```hcl
resource "aws_networkmanager_vpc_attachment" "example" {
  subnet_arns             = [aws_subnet.example.arn]
  core_network_id         = awscc_networkmanager_core_network.example.id
  vpc_arn                 = aws_vpc.example.arn

  options {
    ipv6_support =  false
  }

  tags = {
    "Name" : "my-vpc",
    "segment": "example"
  }
}
```

### References

* https://github.com/hashicorp/terraform-provider-awscc/issues/586

**Comment by Hemant40** [comment]
Hi Folks,

i am testing this new feature added regarding to (https://github.com/hashicorp/terraform-provider-aws/pull/26227). i can now accept the VPC attachment with the new provided **"aws_networkmanager_attachment_accepter"** module.
But i cannot accept other kind of attachments with this module, like **site_to_site_vpn** kind of attachments.
Please suggest.

In my opinion, the module **"aws_networkmanager_attachment_accepter"** should accept all kind of attachments regardless from its **attachment type (VPC/site_to_site)** etc.

Code:
resource "aws_networkmanager_attachment_accepter" "vpn_acc" {
  attachment_id   = awscc_networkmanager_site_to_site_vpn_attachment.vpn_attachment.id
  attachment_type = awscc_networkmanager_site_to_site_vpn_attachment.vpn_attachment.attachment_type
}

Error details:
╷
│ Error: expected attachment_type to be one of [VPC], got SITE_TO_SITE_VPN
│ 
│   with aws_networkmanager_attachment_accepter.vpn_acc,
│   on cloud_wan.tf line 63, in resource "aws_networkmanager_attachment_accepter" "vpn_acc":
│   63:   attachment_type = awscc_networkmanager_site_to_site_vpn_attachment.vpn_attachment.attachment_type

![image](https://user-images.githubusercontent.com/91174172/185867351-f5787a58-01c2-4867-b228-121014a5d3c7.png)

**Comment by drewmullen** [comment]
> In my opinion, the module "aws_networkmanager_attachment_accepter" should accept all kind of attachments

We agree:

https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/networkmanager/attachment_accepter.go#L40-L49

support for the other types has to be written. I believe most cloudwan gaps are currently WIP
