### ISSUE TITLE
resource/aws_ec2_transit_gateway_policy_table_association for cloudwan

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform-provider-aws#26247]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_ec2_transit_gateway_policy_table_association

### Potential Terraform Configuration

```hcl
resource "aws_ec2_transit_gateway_policy_table_association" "example" {
    transit_gateway_policy_table_id = <>
    transit_gateway_attachment_id  = <>
}
```

### References

* cli docs: https://docs.aws.amazon.com/cli/latest/reference/ec2/associate-transit-gateway-policy-table.html
* api docs: https://docs.aws.amazon.com/goto/WebAPI/ec2-2016-11-15/AssociateTransitGatewayPolicyTable

**Comment by ewbankkit** [comment]
@drewmullen Thanks for raising this issue.
It has already been noticed in #26093. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
