### ISSUE TITLE
Activate cost allocation tags

### ISSUE THREAD

**Issue by glenjamin** [hashicorp/terraform-provider-aws#26268]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has recently released an API for activating user-defined cost allocation tags

https://aws.amazon.com/about-aws/whats-new/2022/06/aws-cost-allocation-tag-api/
https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_UpdateCostAllocationTagsStatus.html

It would be great to add support for this to the provider

### New or Affected Resource(s)

As the API is a bulk-update API, it probably makes sense to mirror that in the resource?

* aws_cost_allocation_tags

### Potential Terraform Configuration

Here's an initial strawman for how it could work

```hcl
resource "aws_cost_allocation_tags" "tags" {
  tag {
    key = "role"
    status = "Active" # optional
  }
  tag {
    key = "name"
    status = "Inactive"
}
```

### References

* Previous request, from before an API existed #24307
* https://aws.amazon.com/about-aws/whats-new/2022/06/aws-cost-allocation-tag-api/
* https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_UpdateCostAllocationTagsStatus.html

**Comment by justinretzolk** [comment]
Hey @glenjamin👋 Thank you for taking the time to raise this! It looks like this functionality was added in provider version `4.20.0` as the [`aws_ce_cost_allocation_tag` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ce_cost_allocation_tag). Since it looks like this functionality has already been added, I'll close this issue out. If you feel I've done this in error, please do let me know.
