### ISSUE TITLE
resource/aws_db_instance: Modifying only the `final_snapshot_identifier` returns error in v4.26.0

### ISSUE THREAD

**Issue by gcardonag** [hashicorp/terraform-provider-aws#26280]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform Version: 1.1.6
Provider Version: 4.26.0

### Affected Resource(s)

* aws_db_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_db_instance" "rds_db_instance" {
  ...
  final_snapshot_identifier = "${var.db_name}-FINALSNAPSHOT-${formatdate("YYYY-MM-DD-hh-mm", timestamp())}"
  skip_final_snapshot         = false
```

### Debug Output

```
module.rds_instance["INSTANCE_NAME"].aws_db_instance.rds_db_instance[0] will be updated in-place
  ~ resource "aws_db_instance" "rds_db_instance" {
      ~ final_snapshot_identifier             = "INSTANCE_NAME-FINALSNAPSHOT-2022-08-12-17-56" -> (known after apply)
        id                                    = "INSTANCE_NAME"
        name                                  = "NAME"
        tags                                  = {...}
        # (60 unchanged attributes hidden)
    }
...
module.rds_instance["INSTANCE_NAME"].aws_db_instance.rds_db_instance[0]: Modifying... [id=INSTANCE_ID]
Error: updating RDS DB Instance (INSTANCE_NAME): InvalidParameterCombination: No modifications were requested
```

### Expected Behavior

Terraform should apply the change without any error. This was the case as of 3 days ago with version 4.25.0 of the provider.

### Actual Behavior

Terraform starts to apply the change, then immediately fails with `Error: updating RDS DB Instance (INSTANCE_NAME): InvalidParameterCombination: No modifications were requested`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

N/A

**Comment by gcardonag** [comment]
A follow-up test today confirms that using v4.25.0 still works when performing this change. I started looking into the diff between the two releases but don't see anything obvious that would cause this error.

**Comment by ewbankkit** [comment]
@gcardonag Thanks for raising this issue 👏.
Without finding the exact line(s) changed I'm pretty sure this is caused by a change I made from `d.HasChanges(...)` to `d.HasChangesExcept(...)` in `resourceInstanceUpdate`.
We'll look at getting this fixed ASAP.

**Comment by ewbankkit** [comment]
I can reproduce this in a (modified) acceptance test case:

```console
%  make testacc TESTARGS='-run=TestAccRDSInstance_finalSnapshotIdentifier' PKG=rds
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20  -run=TestAccRDSInstance_finalSnapshotIdentifier -timeout 180m
=== RUN   TestAccRDSInstance_finalSnapshotIdentifier
=== PAUSE TestAccRDSInstance_finalSnapshotIdentifier
=== CONT  TestAccRDSInstance_finalSnapshotIdentifier
    instance_test.go:641: Step 2/2 error: Error running apply: exit status 1
        
        Error: updating RDS DB Instance (tf-acc-test-8351385303729901448): InvalidParameterCombination: No modifications were requested
        	status code: 400, request id: b467ac80-c6dd-453f-ab5a-7ccb000f27c8
        
          with aws_db_instance.test,
          on terraform_plugin_test.tf line 15, in resource "aws_db_instance" "test":
          15: resource "aws_db_instance" "test" {
        
--- FAIL: TestAccRDSInstance_finalSnapshotIdentifier (898.60s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/rds	906.601s
FAIL
make: *** [testacc] Error 1
```
