### ISSUE TITLE
Slight error in S3 bucket lifecycle config documentation

### ISSUE THREAD

**Issue by lazarillo** [hashicorp/terraform-provider-aws#26294]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Irrelevant

### Affected Resource(s)

* aws_s3_bucket_lifecycle_configuration

### Documentation Typo

There is nothing to debug, but noting that there is a mistake in the documentation for the [aws_s3_bucket_lifecycle_configuration](https://registry.terraform.io/providers/hashicorp/aws%20%20/latest/docs/resources/s3_bucket_lifecycle_configuration#id).

In the [section discussing versioning](https://registry.terraform.io/providers/hashicorp/aws%20%20/latest/docs/resources/s3_bucket_lifecycle_configuration#creating-a-lifecycle-configuration-for-a-bucket-with-versioning), it says:

```tf
resource "aws_s3_bucket_lifecycle_configuration" "versioning-bucket-config" {
  # Must have bucket versioning enabled first
  depends_on = [aws_s3_bucket_versioning.versioning]

  bucket = aws_s3_bucket.versioning_bucket.bucket
```

but that last line should say:

```tf
  bucket = aws_s3_bucket.versioning_bucket.id
```

### Note

I'm happy to fix this, but haven't checked the procedure.  Can I fork the repo and make a PR back into it?

**Comment by breathingdust** [comment]
@lazarillo yes! We'd happily accept a PR to fix this! 👍

**Comment by shijiadong2022** [comment]
Is this still a valid issue? Can I make a PR for it?

**Comment by mhaoda** [comment]
Already in process on this issue.
