### ISSUE TITLE
VPC deploy Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by malcolmm83** [hashicorp/terraform-provider-aws#26309]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.15.5
- Installing hashicorp/aws v4.26.0...

### Affected Resource(s)

* aws_vpc_endpoint
* aws_subnet
* aws_vpc
* data "aws_vpc_endpoint_service"
* data "aws_subnet_ids"

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

apply is successful

### Actual Behavior

Error: Provider produced inconsistent final plan

When expanding the plan for
module.cigna-golden-vpc.aws_vpc_endpoint.interfaces[2] to include new values
learned so far during apply, provider "registry.terraform.io/hashicorp/aws"
produced an invalid new value for .subnet_ids: actual set element
cty.StringVal("subnet-0c5b3442dacfd2f8c") does not correlate with any element
in plan.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for
module.cigna-golden-vpc.aws_vpc_endpoint.interfaces[2] to include new values
learned so far during apply, provider "registry.terraform.io/hashicorp/aws"
produced an invalid new value for .subnet_ids: actual set element
cty.StringVal("subnet-0cf1d0725486abbe4") does not correlate with any element
in plan.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for
module.cigna-golden-vpc.aws_vpc_endpoint.interfaces[2] to include new values
learned so far during apply, provider "registry.terraform.io/hashicorp/aws"
produced an invalid new value for .subnet_ids: length changed from 4 to 6.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

... more like this

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This occured after adding a new CIDR (and 2 new subnets) to my VPC configuration.  Apply worked after the additions, but now gets above errors.  vpc-endpoints are meant to be configured with all subnets, but actual resources only show original 4.

I've tried this with TF versions 0.15.5 and 1.2.0, and with provider versions 4.25, 4.26, 4.20 and 3.69 with no change.

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @malcolmm83 👋 Thank you for taking the time to raise this! In order to effectively investigate this, we'll need an example Terraform configuration that is able to reproduce the issue. Are you able to supply that for us to take a look into?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
