### ISSUE TITLE
support IPv6 targets in aws_lb_target_group

### ISSUE THREAD

**Issue by markmartirosian** [hashicorp/terraform-provider-aws#26312]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently there is no way to select IPv6 address type for IP address target groups.

### Affected Resource(s)

* aws_lb_target_group
* aws_lb_target_group_attachment

### References

[Create a target group](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-target-group.html)
[Register targets with your target group
](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-register-targets.html)

**Comment by bschaatsbergen** [comment]
Hi @markmartirosian, thanks for taking the time to raise this issue. I'll look into it.
