### ISSUE TITLE
Incorrect enable syntax documented for aws_guardduty_organization_configuration

### ISSUE THREAD

**Issue by andrew-ar** [hashicorp/terraform-provider-aws#26329]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

* terraform 1.0.11
* hashicorp/aws v4.26.0

### Affected Resource(s)

* aws_guardduty_organization_configuration

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Enable GuardDuty and SecurityHub in the Security account
resource "aws_guardduty_detector" "this" {
  enable = true
}

resource "aws_guardduty_organization_configuration" "this" {
  auto_enable = true
  detector_id = aws_guardduty_detector.this.id

  datasources {
    s3_logs {
      auto_enable = true
    }
    kubernetes {
      audit_logs {
        enable = true
      }
    }
    malware_protection {
      scan_ec2_instance_with_findings {
        ebs_volumes {
          enable = true
        }
      }
    }
  }
}
```

i.e. what's documented [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_detector#scan-ec2-instance-with-findings) (actually on closer inspection it looks like the same issue exists for the s3_logs data source too - I forget where I found the example configuration originally but anyway it looks like there are two mistakes in the docs where `enable` should be `auto_enable`)

I omitted the tfstate boilerplate from the above but can add it if needed, though the issue is fairly clear without that.

### Debug Output

* https://gist.github.com/andrew-ar/3b05db2ac5d46b37cbfb0211edace315

### Panic Output

* N/A

### Expected Behavior

* A successful terraform plan showing creation of the aws_guardduty_organization_configuration

### Actual Behavior

An error message occurred:

```
│ Error: Missing required argument
│ 
│   on main.tf line 62, in resource "aws_guardduty_organization_configuration" "this":
│   62:         ebs_volumes {
│ 
│ The argument "auto_enable" is required, but no definition was found.
╵
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 63, in resource "aws_guardduty_organization_configuration" "this":
│   63:           enable = true
│ 
│ An argument named "enable" is not expected here.
```

It appears the docs are incorrect and the attribute should be named `auto_enable`. 

### Steps to Reproduce

1. `terraform plan` or `terraform apply` on the sample terraform shown using the specified versions

### Important Factoids

I can't think of anything particularly unusual

### References

The code added [here](https://github.com/hashicorp/terraform-provider-aws/pull/25997/files#diff-f16322be26d336adb5a6a1ab403a4c25562954f3986efcc2e237f412039bebf0R95) looks relevant.

**Comment by breathingdust** [comment]
You are correct, at the top level the schema is defined as [auto_enable](https://github.com/hashicorp/terraform-provider-aws/blob/3b5f78dad14106af38140f6ed9209b318a42a50e/internal/service/guardduty/organization_configuration.go#L27) but documented as [enable](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_detector#enable) and within the [malware_protection](https://github.com/hashicorp/terraform-provider-aws/blob/3b5f78dad14106af38140f6ed9209b318a42a50e/internal/service/guardduty/organization_configuration.go#L95) block a `auto_enable` is documented as [enable](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_detector#enable). This will need a documentation correction.
