### ISSUE TITLE
Amazon Cloudfront has added support for HTTP/3

### ISSUE THREAD

**Issue by EkkertRBX** [hashicorp/terraform-provider-aws#26330]
Amazon has added support for HTTP/3 protocol and appears it's just a new key value for "HttpVersion".  
The new value appears as "http2and3" when modifying a distribution.

Release Link: https://aws.amazon.com/about-aws/whats-new/2022/08/amazon-cloudfront-supports-http-3-quic/

        "WebACLId": "arn:aws:wafv2:xxxxxxxx:global/webacl/Test/xxxxxxxxxxxxxx",
        "HttpVersion": "http2and3",
        "IsIPV6Enabled": true

Thanks.

**Comment by mbamber** [comment]
Fixed in https://github.com/hashicorp/terraform-provider-aws/pull/26313 I think

**Comment by ewbankkit** [comment]
@EkkertRBX Thanks for raising this issue.
It has already been noticed in #26321. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
