### ISSUE TITLE
Resource aws_redshiftdata_statement support for Redshift Serverless

### ISSUE THREAD

**Issue by manypozo** [hashicorp/terraform-provider-aws#26346]
Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Create support for Redshift Serverless connections in resource `aws_redshiftdata_statement`.

Redshift serveless connections are made using workgroups instead of cluster identifiers. This translates also in a change of endpoints for connection:
- Redshift: `cluster.<aws-random-account-redshift-prefix>.<region>.redshift.amazonaws.com:5439/dev`
- Redshift Serverless: `cluster.<account-id>.<region>.redshift-serverless.amazonaws.com:5439/dev`

### New or Affected Resource(s)

`aws_redshiftdata_statement`

### Potential Terraform Configuration

The resource can look like this:
```hcl
resource "aws_redshiftdata_statement" "sql" {
  workgroup_name = "default"
  database           = "dev"
  secret_arn = aws_secretsmanager_secret.secrets.arn
  sql            = "select * from stl_query limit 1"
  statement_name = "Initialization"
  with_event     = null
}
```

which would be equivalent to the AWS CLI command:
```
aws redshift-data execute-statement --region=region --secret=secret-arn --workgroup-name=default --database=dev --sql "select * from stl_query limit 1" 
```

### References
* Terraform resource aws_redshiftdata_statement documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshiftdata_statement#example-usage
* AWS CLI Redshift Data documentation: https://docs.aws.amazon.com/cli/latest/reference/redshift-data/execute-statement.html
* Go implementation of the resource: https://github.com/hashicorp/terraform-provider-aws/tree/main/internal/service/redshiftdata

**Comment by juanarmond** [comment]
Hi, guys.

Any update on this ticket?

Regards, 
Juan Armond

**Comment by abcydybcy** [comment]
I'd be really nice to have...

**Comment by jamesyanyuk** [comment]
Is there any ETA on `aws_redshiftdata_statement ` support for Redshift Serverless?

**Comment by igordrnobrega** [comment]
Hey guys any news on this support?

**Comment by bennylu2** [comment]
I've opened a PR for this, hopefully it looks alright and someone can review soon
