### ISSUE TITLE
terraform-provider-aws_v4.26.0_x5.exe threw Out of Memory error

### ISSUE THREAD

**Issue by mike-decaro** [hashicorp/terraform-provider-aws#26356]
Running 6 state plan statements in parallel, 5 succeeded and one threw the following error:
``` Error: Request cancelled
with provider["registry.terraform.io/hashicorp/aws"],
on providers.tf line 1, in provider "aws":
1: provider "aws" {
The plugin.(*GRPCProvider).ValidateProviderConfig request was cancelled.
Stack trace from the terraform-provider-aws_v4.26.0_x5.exe plugin:
fatal error: out of memory
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
terraform_version: 1.1.3,
AWS Provider version: hashicorp/aws v4.26.0 (signed by HashiCorp)

### Affected Resource(s)

* aws provider

### Terraform Configuration Files

As stated below, I cannot reproduce the bug.  The error log kindly asked me to submit a bug:
```
This is always indicative of a bug within the plugin. It would be immensely helpful if you could report the crash with the plugin's maintainers so that it can be fixed. The output above should help diagnose the issue.
```

### Panic Output

https://gist.github.com/mike-decaro/2ad6c614d93606b73c0ecefe0b29a4dd

### Expected Behavior

Terraform plan succeeded

### Actual Behavior

Fatal error

### Steps to Reproduce

Cannot; previous and subsequent plan steps have succeeded

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @mike-decaro 👋 Thank you very much for taking the time to submit this issue! It sounds like on all subsequent plans/applies, you're not running into the same issue, with no other changes to the configuration or environment -- is that a  correct assessment?

**Comment by mike-decaro** [comment]
@justinretzolk that is correct.  Looked like a one-time thing.  Simply hit try again through Octopus Deploy (which I am using to plan/apply my Terraform in this case) and took with no issue
