### ISSUE TITLE
Log Configuration for FIS Experiment Templates

### ISSUE THREAD

**Issue by dannycheung-nozomi** [hashicorp/terraform-provider-aws#26365]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Unable to set the logConfiguration field of `aws_fis_experiment_template` resource

### New or Affected Resource(s)

* aws_fis_experiment_template

### Potential Terraform Configuration

```hcl
resource "aws_fis_experiment_template" "my_exp_template" {
  description = "My experiment template"
  role_arn  = "arn:aws:...."
  ...
  log_configuration {
    cloudwatch_logs_configuration {
      log_group_arn = "arn:aws::..."
    }
    s3_configuration {
      bucket_name = "my-bucket"
      prefix = "/my-prefix"
  },
  log_schema_version = 1
  }
}
```

### References

* https://docs.aws.amazon.com/fis/latest/userguide/monitoring-logging.html

**Comment by spotter9** [comment]
Is there any update on this functionality?
