### ISSUE TITLE
Site-to-Site VPN Tunnel logs

### ISSUE THREAD

**Issue by SantiMunoz** [hashicorp/terraform-provider-aws#26389]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS recently enabled sending the VPN Tunnel logs to Cloudwatch. This request is to include this feature in the AWS Terraform provider.

### New or Affected Resource(s)

* `aws_vpn_connection`

[Announcement](https://aws.amazon.com/about-aws/whats-new/2022/08/aws-site-vpn-connection-logs-amazon-cloudwatch/).

**Comment by ewbankkit** [comment]
Requires [AWS SDK for Go v1.44.80](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.80): https://github.com/hashicorp/terraform-provider-aws/pull/26385.

**Comment by bschaatsbergen** [comment]
Hi @SantiMunoz, thanks for raising this issue. I'll happily look into it.

**Comment by vinceoan** [comment]
We also need this feature. Do we have a good timeline when this will be released? Currently we either have to use AWS CLI to enable the log feature or do it manually from the console.

**Comment by bschaatsbergen** [comment]
Hi @vinceoan, the PR is ready to be reviewed - just need to sort an issue out with the acceptance test.

**Comment by vinceoan** [comment]
great! thanks for making great progress! @bschaatsbergen
