### ISSUE TITLE
aws_appflow_connector_profile creation fails with error - ValidationException: Validation exception: AuthCode cannot be blank for connector: SALESFORCE

### ISSUE THREAD

**Issue by Rafno** [hashicorp/terraform-provider-aws#26396]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.2.7
+ provider registry.terraform.io/hashicorp/aws v4.26.0

### Affected Resource(s)

* aws_appflow_connector_profile

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_appflow_connector_profile" "salesforce_connector" {
  name            = "salesforce-connector"
  connector_type  = "Salesforce"
  connection_mode = "Private" #Does not matter if it is public or private, error occurs on both
  kms_arn         = var.kms_key_arn
  connector_profile_config {
    connector_profile_credentials {
      salesforce {
        client_credentials_arn = aws_secretsmanager_secret.appflow_salesforce_credentials.arn
      }
    }

    connector_profile_properties {
      salesforce {
        instance_url           = var.salesforce_url
        is_sandbox_environment = true
      }
    }
  }
}


```

### Debug Output

Link to [gist](https://gist.github.com/Rafno/2640822c9f57d83bd21206cab1634250)

### Expected Behavior

Connector is created.

### Actual Behavior

Connector does not create

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Attempting to add an empty oauth block crashes the plugin, make this change to the code to force it to crash.
``` hcl
connector_profile_credentials {
      salesforce {
        client_credentials_arn = aws_secretsmanager_secret.appflow_salesforce_credentials.arn
        oauth_request {

        }
      }
    }
```

**Comment by rakeshagarwal0292** [comment]
Why do we have to add auth_code initially? What if we do not want to involve user interaction in the process of creating Salesforce connector.
As per salesforce, if we choose the grant_type as CLIENT_CREDENTIALS, then we can get the access token using just clientId and clientSecret only.
AWS cli also do not enforce to use the auth code, in this case.
This seems to be a bug from Terraform implementation.
