### ISSUE TITLE
Error creating API Gateway deployment with private API managed by Terraform resources (instead of OpenAPI specification)

### ISSUE THREAD

**Issue by tailaiw** [hashicorp/terraform-provider-aws#26394]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_api_gateway_rest_api

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_vpc_endpoint" "api_gw" {
  vpc_id            = aws_vpc.main.id
  service_name      = "com.amazonaws.us-west-2.execute-api"
  vpc_endpoint_type = "Interface"

  security_group_ids = [
    aws_security_group.sg1.id,
  ]
}

resource "aws_api_gateway_rest_api" "rest_api" {
  name = "my_api"
  endpoint_configuration {
    types = ["PRIVATE"]
    vpc_endpoint_ids = [aws_vpc_endpoint.api_gw.id]
  }
}

resource "aws_api_gateway_resource" "api_gw_resource" {
  rest_api_id = aws_api_gateway_rest_api.rest_api.id
  parent_id   = aws_api_gateway_rest_api.rest_api.root_resource_id
  path_part   = "my_path"
}

resource "aws_api_gateway_method" "api_gw_method" {
  rest_api_id   = aws_api_gateway_rest_api.rest_api.id
  resource_id   = aws_api_gateway_resource.api_gw_resource.id
  http_method   = "GET"
  authorization = "NONE"
}

resource "aws_lambda_function" "my_lambda_function" {
  function_name = "my_lambda_function"
  # some more config of the Lambda function
}

resource "aws_lambda_permission" "api_gw_lambda" {
  statement_id  = "AllowExecutionFromAPIGateway"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.my_lambda_function.function_name
  principal     = "apigateway.amazonaws.com"
  source_arn    = "arn:aws:execute-api:${var.aws_region}:${var.aws_account_id}:${aws_api_gateway_rest_api.rest_api.id}/*/${aws_api_gateway_method.api_gw_method.http_method}${aws_api_gateway_resource.api_gw_resource.path}"
}

resource "aws_api_gateway_integration" "api_gw_integration" {
  rest_api_id             = aws_api_gateway_rest_api.rest_api.id
  resource_id             = aws_api_gateway_resource.api_gw_resource.id
  http_method             = aws_api_gateway_method.api_gw_method.http_method
  integration_http_method = "POST"
  type                    = "AWS_PROXY"
  uri                     = aws_lambda_function.my_lambda_function.invoke_arn
}

resource "aws_api_gateway_deployment" "deployment" {
  rest_api_id = aws_api_gateway_rest_api.rest_api.id
  triggers = {
    redeployment = sha1(jsonencode([
      aws_api_gateway_rest_api.rest_api,
      aws_api_gateway_resource.api_gw_resource,
      aws_api_gateway_method.api_gw_method,
      aws_api_gateway_integration.api_gw_integration
    ]))
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

### Expected Behavior

I expect this implementation is equivalent to configuring the REST API with OpenAPI specification via the `body` argument, and it should perform similar to [this example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_rest_api#openapi-specification-with-private-endpoints).

### Actual Behavior

I got the following error, which seems to indicate that the deployment doesn't catch up with the terraform resources (resources `aws_api_gateway_resource resource`, methods `aws_api_gateway_method resource`, integrations `aws_api_gateway_integration resource` etc.) to my understanding.

`Error: Error creating API Gateway Deployment: BadRequestException: Private REST API doesn't have a resource policy attached to it`

I see in the doc only includes a single example of private API and it uses OpenAPI specification instead of Terraform resources to manage the API. I'm not sure if that is the only supported way but not explicitly stated in the docs (I didn't find any statement like that).

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor documentation? For example:
--->

[This one](https://github.com/hashicorp/terraform-provider-aws/issues/14290) _seems_ related but I'm not quite sure.

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
