### ISSUE TITLE
Terraform creates t3.medium instead of t4g.medium eks worker node

### ISSUE THREAD

**Issue by kderck** [hashicorp/terraform-provider-aws#26397]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
kyle.davies@ip-192-168-86-51 ~ % terraform -v
Terraform v1.1.1
on darwin_arm64
```

### Affected Resource(s)

* aws_eks_node_group 

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_eks_node_group" "node_group" {
instance_types = ["t4g.medium"]
}
```

### Debug Output

N/A

### Expected Behavior

Terraform should create a worker node of t4g.medium.

### Actual Behavior

Terraform created a t3.medium worker node.

### Steps to Reproduce

1: Create a eks worker node in Terraform and use `t4g.medium`. 
2: terraform plan -out plan
3: terraform apply plan

### References

* https://repost.aws/questions/QUfyli6u0vSEK7Pn47mZNBQg/eks-issue-when-adding-node-group-with-t-4-g-class-instance

**Comment by mattburgess** [comment]
I'm unable to reproduce this with the following config using Terraform 1.3.1 and AWS Provider 4.33.0. In case this is a region-specific issue, which the linked reference suggests it might be, I'm running this in eu-west-2:

```hcl
resource "aws_eks_node_group" "t4g" {
  cluster_name    = aws_eks_cluster.example.name
  node_group_name = "example"
  node_role_arn   = aws_iam_role.eks_node_group.arn

  scaling_config {
    desired_size = 1
    min_size     = 1
    max_size     = 3
  }

  subnet_ids     = aws_subnet.private.*.id
  instance_types = ["t4g.medium"]
  ami_type       = "AL2_ARM_64"

  lifecycle {
    ignore_changes = [scaling_config[0].desired_size]
  }

  depends_on = [
    aws_iam_role_policy_attachment.eks-node-group-AmazonEKSWorkerNodePolicy,
    aws_iam_role_policy_attachment.eks-node-group-AmazonEKS_CNI_Policy,
    aws_iam_role_policy_attachment.eks-node-group-AmazonEC2ContainerRegistryReadOnly,
  ]
}
```

@kderck are you still hitting this, and if so, are there any more details you can provide that might help me to try and reproduce this?

**Comment by mattburgess** [comment]
Yes - the instance type is t4g.medium in both the terraform state and in the console.

Can you post the full configuration for your `aws_eks_node_group` resource please and I'll try to see if that helps me reproduce it.

**Comment by kderck** [comment]
Hi @mattburgess - I've not tried this out yet - But I believe this happens when ` ami_type = "AL2_ARM_64"` is not set.

**Comment by kderck** [comment]
Looks like this might have been resolved in a recent upgrade now get the error message `InvalidParameterException: [t4g.medium] is not a valid instance type for requested amiType AL2_x86_64`.
