### ISSUE TITLE
Provider config not assuming role

### ISSUE THREAD

**Issue by sidekick-eimantas** [hashicorp/terraform-provider-aws#26398]
```hcl
provider "aws" {
  alias = "ireland"

  region              = "eu-west-1"
  allowed_account_ids = ["311418037500"]
}

resource "aws_organizations_account" "sidekickmoney_security" {
  provider = aws.ireland

  name                       = "sidekickmoney-security"
  email                      = "test@example.com"
  parent_id                  = aws_organizations_organizational_unit.sidekick_money.id
  role_name                  = "OrganizationAccountAccessRole"
}

provider "aws" {
  alias = "sidekickmoney-security"

  region              = "eu-west-1"
  allowed_account_ids = ["364327525413"]
  assume_role {
    role_arn = "arn:aws:iam::${aws_organizations_account.sidekickmoney_security.id}:role/${aws_organizations_account.sidekickmoney_security.role_name}"
  }
}

resource "aws_iam_user" "iam_admin" {
  provider = aws.sidekickmoney-security

  name          = "iam-admin"
}
```

After deploying the above, if I change the `aws_organizations_account.sidekickmoney_security.name` attribute, the `aws.sidekickmoney-security` provider stops assuming the role it's told to, unless I replace the string interpolated `account id` in the `role_arn` with a static one.

**Comment by justinretzolk** [comment]
Hey @sidekick-eimantas 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
