### ISSUE TITLE
AccessDeniedException on aws_lambda_invocation Resourcce

### ISSUE THREAD

**Issue by rizkimhd** [hashicorp/terraform-provider-aws#26391]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* [aws_lambda_invocation resource](https://registry.terraform.io/providers/hashicorp/aws/3.75.2/docs/resources/lambda_invocation)
* [aws_lambda_invocation data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/lambda_invocation)

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "time_static" "prerun" {
  triggers = {
    deployment = timestamp()
  }
}

resource "time_static" "postrun" {
  triggers = {
    startTime = time_static.prerun.rfc3339
  }
}

resource "aws_lambda_invocation" "orgemp" {
  triggers = {
    endTime = time_static.postrun.rfc3339
  }

  function_name = "var.function_name"
  input = jsonencode({
    source       = "deployment.custom"
    startTime    = formatdate(local.date_format, time_static.prerun.rfc3339)
    endTime      = formatdate(local.date_format, time_static.postrun.rfc3339)
    status       = "Succeeded"
  })
}
```

### Debug Output

Terraform Apply Debug Log: https://gist.github.com/rizkimhd/1f2e215c34101264775a9dfdb6bb47c2
Terraform Apply Output:
```
Error: Lambda Invocation () failed: AccessDeniedException: 
        status code: 403, request id: 6bfa9c14-c789-420a-bb29-1341a62d95f5
```

### Expected Behavior

It should invoke the Lambda function.

### Actual Behavior
It should invoke the affected Lambda Function

Got `AccessDeniedException` when applying the terraform.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

When invoking the same lambda through AWS CLI (using the same role and payload) it succeeded, although when I use AWS CLI **with** `--qualifier` option I got the same `Forbidden/AccessDenied` issue. However when I invoke the lambda function through AWS CLI **without** providing `--qualifier` it succeeded

### References

- [Terraform Registry Doc](https://registry.terraform.io/providers/hashicorp/aws/3.75.2/docs/resources/lambda_invocation)
- [AWS Lambda Function Doc](https://docs.aws.amazon.com/lambda/latest/dg/configuration-versions.html)
- [AWS CLI Doc](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/invoke.html)
* #0000

**Comment by justinretzolk** [comment]
Hey @rizkimhd 👋 Thank you for taking the time to raise this! On a quick glance, I notice that you passed `"var.function_name"` as the `function_name` argument. Since you wrapped this in quotes, you're passing that as a string literal, rather than interpolating the value. That said, the debug logs didn't seem as though this was the case -- was that perhaps a typo in the issue report?

Ultimately, the error you're receiving is coming directly from AWS, and with your mention that passing the `--qualifier` option in the CLI reproduced the issue, I suspect this is not a Terraform issue, but rather one of the permissions or configuration itself.

**Comment by rizkimhd** [comment]
Hi @justinretzolk thank you for the response, so currently the permission to do `lambda:Invokefunction` is to allow both the qualified and unqualified ARN, any advise on how to properly set the permission to allow invoking through terraform `aws_lambda_invocation` resource?
```
Action    = "lambda:InvokeFunction"
Effect    = "Allow" 
Resources = [
  "arn:aws:lambda:<region>:<account_id>:function:<function_name>:*",
  "arn:aws:lambda:<region>:<account_id>:function:<function_name>"
]
```

**Comment by rizkimhd** [comment]
Since the [qualifier](https://github.com/hashicorp/terraform-provider-aws/blob/3ede5dfc231c2f8c3a2471d3f39e3673c2951f75/internal/service/lambda/invocation.go#L33-L38) is `Optional`, would it be possible and okay to remove the `Default` value?
```
"qualifier": {
    Type:     schema.TypeString,
    Optional: true,
    ForceNew: true,
    Default:  FunctionVersionLatest,
},
```
