### ISSUE TITLE
aws_imagebuilder_distribution_configuration does not allow kms_key_id argument in resource block

### ISSUE THREAD

**Issue by sfpwhite** [hashicorp/terraform-provider-aws#26401]
Hi! The documentation for `aws_imagebuilder_distribution_configuration` lists an optional `kms_key_id` argument for the resource block, but adding this argument makes the configuration invalid. The API definition doesn't include a KMS key field at the resource level, so perhaps the documentation lists this argument erroneously. 
 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.2.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.27.0
```

### Affected Resource(s)

* aws_imagebuilder_distribution_configuration

### Terraform Configuration Files

```hcl
resource "aws_kms_key" "example" {
  description             = "KMS test"
  deletion_window_in_days = 10
}

resource "aws_imagebuilder_distribution_configuration" "example" {
  name       = "ec2-image-builder-distribution"
  kms_key_id = aws_kms_key.example.arn

  distribution {
    region = "us-east-1"
  }
}
```

### Debug Output

https://gist.github.com/sfpwhite/b816ea0b2da3ac5b9d18f1b894f52ec1

### Expected Behavior

Terraform configuration should be successfully validated.

### Actual Behavior

Terraform throws an unsupported argument error:

```
│ Error: Unsupported argument
│ 
│   on main.tf line 8, in resource "aws_imagebuilder_distribution_configuration" "example":
│    8:   kms_key_id = aws_kms_key.example.arn
│ 
│ An argument named "kms_key_id" is not expected here.
```

### Steps to Reproduce

1. `terraform validate`

### References

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/imagebuilder_distribution_configuration
* https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_CreateDistributionConfiguration.html

**Comment by justinretzolk** [comment]
Hey @sfpwhite 👋 Thank you very much for taking the time to raise this! I've opened a PR to remove the reference to the `kms_key_id` argument, as it doesn't exist within the schema. I appreciate you taking the time to point this out! 🎉

**Comment by bschaatsbergen** [comment]
Hi, @sfpwhite & @justinretzolk - the `kms_key_id` should be part of the `ami_distribution_configuration` block which is part of the `distribution` block.

```terraform
data "aws_region" "current" {}

resource "aws_kms_key" "default" {
  deletion_window_in_days = 7
}

resource "aws_imagebuilder_distribution_configuration" "default" {
  name = "example"

  distribution {
    ami_distribution_configuration {
      kms_key_id = aws_kms_key.default.arn
    }

    region = data.aws_region.current.name
  }
}
```
