### ISSUE TITLE
aws_transfer_ssh_key doesn't wait for aws_transfer_user

### ISSUE THREAD

**Issue by rjhornsby** [hashicorp/terraform-provider-aws#26403]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v1.2.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.24.0
```
### Affected Resource(s)

* `aws_transfer_user` 
* `aws_transfer_ssh_key`

### Terraform Configuration Files

```hcl
resource "aws_transfer_user" "floppy_mcdoodle_ear" {
  role      = aws_iam_role.floppy-xfer.arn
  server_id = aws_transfer_server.floppy-xfer.id
  user_name = "floppy"
  home_directory_type = "LOGICAL"
  home_directory_mappings {
    entry  = "/"
    target = "<some s3 bucket>"
  }
}

resource "aws_transfer_ssh_key" "floppy_mcdoodle_ear" {
  body      = "<some format-valid ssh public key>"
  server_id = aws_transfer_server.floppy-xfer.id
  user_name = "floppy"
}
```

### Expected Behavior

Terraform should try to wait until the user is actually created before trying to create the ssh key.

### Actual Behavior

TF creates the user and immediately tries to create the ssh key. This results in `Error: Error importing ssh public key: ResourceNotFoundException: Unknown user`:

```
aws_transfer_ssh_key. floppy_mcdoodle_ear: Creating...
aws_transfer_user. floppy_mcdoodle_ear: Creating...
aws_transfer_user. floppy_mcdoodle_ear: Creation complete after 1s [id=s-5ccfxxxxxxx/floppy_mcdoodle_ear]
╷
│ Error: Error importing ssh public key: ResourceNotFoundException: Unknown user
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "xxxx-e563-4908-aee0-xxx"
│   },
│   Message_: "Unknown user",
│   Resource: "floppy_mcdoodle_ear",
│   ResourceType: "User"
│ }
│
│   with aws_transfer_ssh_key.floppy_mcdoodle_ear,
│   on users.tf line 21, in resource "aws_transfer_ssh_key" "floppy_mcdoodle_ear":
│   21: resource "aws_transfer_ssh_key" "floppy_mcdoodle_ear" {
│
```

This can be worked-around by waiting a few seconds, and then running `terraform apply` again - but that's obviously not ideal. 

### Steps to Reproduce

Using the above referenced TF as an example:

1. `terraform apply`

**Comment by ericrichtert** [comment]
I guess this is an easy fix and not a bug:
`resource "aws_transfer_user" "floppy_mcdoodle_ear" {
  role      = aws_iam_role.floppy-xfer.arn
  server_id = aws_transfer_server.floppy-xfer.id
  user_name = "floppy"
  home_directory_type = "LOGICAL"
  home_directory_mappings {
    entry  = "/"
    target = "<some s3 bucket>"
  }
}

resource "aws_transfer_ssh_key" "floppy_mcdoodle_ear" {
  body      = "<some format-valid ssh public key>"
  server_id = aws_transfer_server.floppy-xfer.id
  #user_name = "floppy"
  user_name = aws_transfer_user.floppy_mcdoodle_ear.user_name
}`

**Comment by rjhornsby** [comment]
hmm. I think you’re right. In my real (not scrubbed) code, I’m getting the username from a data block in both resources. By instead referencing the username value from the transfer user resource in the ssh key resource, that should create the necessary dependency and allow Terraform to do its thing correctly. That’s probably the right way to solve this.

thanks @ericrichtert for catching my mistake.
