### ISSUE TITLE
New python version 3.9 is not supported. python_version can only be either 2 or 3.

### ISSUE THREAD

**Issue by jirojo2** [hashicorp/terraform-provider-aws#26428]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_glue_job

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_glue_job" "example" {
  name     = "example"
  role_arn = "arn:REDACTED:"
  max_capacity = 0.0625
  execution_class = "STANDARD"

  command {
    name = "pythonshell"
    python_version = "3.9"
    script_location = "s3://${aws_s3_object.glue_script.bucket}/example/main.py"
  }

  default_arguments = {
    "--class" = "GlueApp"
    "--enable-job-insights" = "false"
    "--job-language" = "python"
  }
}
```

### Expected Behavior

The version "3.9" should be accepted as a valid value for `python_version`, as suggested by the terraform plan changes, and as per the Glue UI nomenclature.

### Actual Behavior

Only version "3" is supported by the terraform provider. This selects the old python 3.6

### Steps to Reproduce

1. `terraform apply` (with the valid version 3)
2. Go to the Glue UI and change the python version to 3.9
3. `terraform apply` and notice the change: ` ~ python_version  = "3.9" -> "3"`

### References

* #0000

**Comment by ewbankkit** [comment]
@jirojo2 Thanks for raising this issue.
It has already been noticed in #26350. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
