### ISSUE TITLE
Please add a Data source for listing all Network Firewall policies

### ISSUE THREAD

**Issue by antonisnyc94** [hashicorp/terraform-provider-aws#26435]
---
name: 🚀 Feature Request
about: Please add a Data source for listing all Network Firewall policies
labels: enhancement
---

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

we are using Firewall Manager Service and there is the limitation that once you create a shared Network Firewall policy across the AWS Organization the Name is random and we cannot use the current provided data sources to find the Fms created policies based on Tags.

### New or Affected Resource(s)

* aws_networkfirewall_firewall_policy

### Potential Terraform Configuration

what I’d like to do would be to run the below code to get a list of the policies created by FMS.

```
data “aws_networkfirewall_policies” “list” {
filter = {
name = “tagName: FMSManaged”
value = “true”
}
}
```

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @antonisnyc94 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description with the information requested in the [feature request template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Feature_Request.md?plain=1)?

**Comment by japm94** [comment]
@justinretzolk I guess it should it be service/networkfirewall instead
