### ISSUE TITLE
assume role not being used by datasources when a provider alias is used

### ISSUE THREAD

**Issue by SteveTalt** [hashicorp/terraform-provider-aws#26437]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.2.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.20.1

### Affected Resource(s)

The following datasources are in my tf ( my sample here is just caller-identity ):
* aws_caller_identity
* aws_availability_zones
* aws_vpc
* aws_subnets
* aws_security_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
variable "terraform_execution_role" {
  type        = string
  description = "AWS IAM Role used to assume to deploy infrastructure"
  default     = ""
}

provider "aws" {
  region = "us-west-2"

  dynamic "assume_role" {
    for_each = length(var.terraform_execution_role) == 0 ? [] : [1]
    content {
      role_arn = var.terraform_execution_role
    }
  }

  alias = "usw2"
}

data "aws_caller_identity" "current" {}

output "identity" {
   value = data.aws_caller_identity.current
}

```

### Debug Output

https://gist.github.com/SteveTalt/e985127364ea32171ee43178f01ad50c

### Expected Behavior

Use the assume role arn provided

### Actual Behavior

Not assuming the role at all

### Steps to Reproduce

1.  Have aws config set up to auth against one account with a role that can assume the terraform_execution_role in a second account
2. `terraform init`
3. `terraform apply`

### Important Factoids

if alias is commented out it works...if not it doesn't

With Alias:
```
data.aws_caller_identity.current: Read complete after 2s [id=REDACTED-AUTH-ACCT]

Changes to Outputs:
  + identity = {
      + account_id = "REDACTED-AUTH-ACCT"
      + arn        = "arn:aws:sts::REDACTED-AUTH-ACCT:assumed-role/REDACTED-AUTH-ROLE/REDACTED"
      + id         = "REDACTED-AUTH-ACCT"
      + user_id    = "REDACTED"
    }
```

Without alias:
```
data.aws_caller_identity.current: Reading...
data.aws_caller_identity.current: Read complete after 2s [id=REDACTED-ASSUMED-ACCT]

Changes to Outputs:
  + identity = {
      + account_id = "REDACTED-ASSUMED-ACCT"
      + arn        = "arn:aws:sts::REDACTED-ASSUMED-ACCT:assumed-role/REDACTED-ASSUMED-ROLE/aws-go-sdk-REDACTED"
      + id         = "REDACTED-ASSUMED-ACCT"
      + user_id    = "REDACTED"
    }
```

### References

* #0000

**Comment by justinretzolk** [comment]
Hey @SteveTalt 👋 Thank you for taking the time to raise this! So that we have all of the information that might be necessary in order to look into this, are you able to supply debug logs (redacted as needed) as well?
