### ISSUE TITLE
Lambda Qualified Invoke ARN

### ISSUE THREAD

**Issue by fishcharlie** [hashicorp/terraform-provider-aws#26439]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the Lambda resource has `qualified_arn` and `invoke_arn`. But there is no Invoke ARN for the Qualified ARN. This means when passing it into API Gateway, it doesn't use the provisioned capacity you might have set.

You can work around this by doing: `replace(aws_lambda_function.function.invoke_arn, aws_lambda_function.function.arn, aws_lambda_function.function.qualified_arn)`, but that is a really ugly hack.

### New or Affected Resource(s)

NA

### Potential Terraform Configuration

NA

### References

NA

**Comment by teddylear** [comment]
@fishcharlie @justinretzolk I can take a look at this if that's alright

**Comment by fishcharlie** [comment]
@teddylear Good with me. I haven't really looked at this code base at all, so it'd be greatly appreciated!

**Comment by teddylear** [comment]
@fishcharlie Created a PR to hopefully resolve issue. Please let me know if there are any questions or concerns.
