### ISSUE TITLE
Enable support for pythonshell with Python 3.9 in aws_glue_job

### ISSUE THREAD

**Issue by mateuszboryn** [hashicorp/terraform-provider-aws#26443]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for AWS Glue Python Shell job with Python 3.9.

### New or Affected Resource(s)

Possibly, only this line needs to be modified:
https://github.com/teraken0509/terraform-provider-aws/blob/master/aws/resource_aws_glue_job.go#L57

* aws_glue_job

### Potential Terraform Configuration

```hcl
resource "aws_glue_job" "job" {
  name          = "job"
  command {
    script_location = "s3://bucket/key.py"
    name            = "pythonshell"
    python_version  = "3.9"
  }
}
```

### References

* https://aws.amazon.com/blogs/big-data/aws-glue-python-shell-now-supports-python-3-9-with-a-flexible-pre-loaded-environment-and-support-to-install-additional-libraries/

**Comment by ewbankkit** [comment]
@mateuszboryn Thanks for raising this issue.
It has already been noticed in #26350. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
