### ISSUE TITLE
Valid values for aws_elb interval parameter are not specified in the terraform documentation.

### ISSUE THREAD

**Issue by swateja123** [hashicorp/terraform-provider-aws#26458]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.12.31
AWS Provider v3.70.0

### Affected Resource(s)

* aws_elb

### Details
•	The resource aws_elb contains a parameter interval in the access_logs block which is used to specify the interval for publishing 
         a log file for each load balancer.
•	This is observed as the interval parameter accepts the value of only 5 or 60.
•	AWS console and CLI accepts the interval value of only 5 or 60. But it is not mentioned in Terraform documentation as valid 
        values for interval parameter.
•	The values for interval parameter are also specified in AWS documentation but not specified in terraform documentation.

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```# Create a new load balancer
resource "aws_elb" "bar" {
  name               = "foobar-terraform-elb"
  availability_zones = ["us-west-2a", "us-west-2b", "us-west-2c"]

  access_logs {
    bucket        = "foo"
    bucket_prefix = "bar"
    interval      = 10
  }

  listener {
    instance_port     = 8000
    instance_protocol = "http"
    lb_port           = 80
    lb_protocol       = "http"
  }

  listener {
    instance_port      = 8000
    instance_protocol  = "http"
    lb_port            = 443
    lb_protocol        = "https"
    ssl_certificate_id = "arn:aws:iam::123456789012:server-certificate/certName"
  }

  health_check {
    healthy_threshold   = 2
    unhealthy_threshold = 2
    timeout             = 3
    target              = "HTTP:8000/"
    interval            = 30
  }

  instances                   = [aws_instance.foo.id]
  cross_zone_load_balancing   = true
  idle_timeout                = 400
  connection_draining         = true
  connection_draining_timeout = 400

  tags = {
    Name = "foobar-terraform-elb"
  }
}
```

### Debug Output
```
 Error: "access_logs.0.interval" contains an invalid Access Logs interval "10". Valid intervals are either 5 or 60 (minutes).
with aws_elb.bar,
on aws_elb.tf line 9, in resource "aws_elb" "bar":
9:     interval      = 10
```
### Expected Behavior

As per the AWS console and CLI interval value should be 5 or 60 (minutes). but it is not mentioned in the Terraform documentation. it should be mentioned that the interval value should be 5 or 60.

### Actual Behavior
Interval parameter accepts the value 5 or 60, if we specify any value other than this then it will give error saying that valid values are 5 or 60.

### References
• Terraform reference
https://registry.terraform.io/providers/hashicorp/aws/3.70.0/docs/resources/elb
• AWS CLI command 'put-logging-configuration’ reference
https://docs.aws.amazon.com/cli/latest/reference/waf/put-logging-configuration.html
• AWS API reference for access_logs
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/access-log-collection.html

**Comment by justinretzolk** [comment]
Hey @swateja123 👋 Thank you for taking the time to raise this! I've opened a PR to clarify that only `5` and `60` are valid values for `aws_elb.access_logs.interval`.
