### ISSUE TITLE
aws_dx_connection data source: add VLAN ID

### ISSUE THREAD

**Issue by rjouhann** [hashicorp/terraform-provider-aws#26461]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In order to automate the Direct Connect Connection provisioning, could we add the VLAN ID in the data source output?

<img width="1000" alt="Screen Shot 2022-08-23 at 23 41 38" src="https://user-images.githubusercontent.com/25542366/186349625-38071566-d9af-4e91-ad45-76d7faf7f502.png">

### New or Affected Resource(s)

* [aws_dx_connection](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/dx_connection)

### Potential Terraform Configuration

```hcl
data "aws_dx_connection" "example" {
  name = "tf-dx-connection"
}
```

Returning VLAN ID in the output.

**Comment by KevinSJ** [comment]
Hello, can I work on this? Thanks!
