### ISSUE TITLE
Spell miss in accessanalyzer_archive_rule

### ISSUE THREAD

**Issue by mathken029** [hashicorp/terraform-provider-aws#26463]
In below page, "analyser_name" is wrong.
"analyzer_name" is correct.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/accessanalyzer_archive_rule

**Comment by justinretzolk** [comment]
Hey @mathken029 👋 Thank you for taking the time to raise this! I've opened a PR to fix the documentation in question.
