### ISSUE TITLE
aws_eks_addon needs timeouts block

### ISSUE THREAD

**Issue by pdeva** [hashicorp/terraform-provider-aws#26474]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
AWS Privider <~ 4.0
Terrafrom CLI 1.2.8

### Affected Resource(s)

aws_eks_addon

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_eks_addon" "eks" {
  for_each = { for k, v in local.cluster_addons : k => v }

  cluster_name = aws_eks_cluster.this.name
  addon_name   = try(each.value.name, each.key)

  addon_version     = lookup(each.value, "addon_version", null)
  resolve_conflicts = lookup(each.value, "resolve_conflicts", null)
}

```

### Debug Output

```
Error: unexpected EKS Add-On (mytest:coredns) state returned during creation: timeout while waiting for state to become 'ACTIVE' (last state: 'DEGRADED', timeout: 20m0s) [WARNING] Running terraform apply again will remove the kubernetes add-on and attempt to create it again effectively purging previous add-on configuration
with module.eks.aws_eks_addon.eks["coredns"]
on ../../../modules/eks/main.tf line 136, in resource "aws_eks_addon" "eks":
```
### Expected Behavior

there should be a `timeouts` block in this resource since it can take a very long time to create.

### Actual Behavior

resource times out..

### Steps to Reproduce

create a bunch of addons and atleast 1 will timeout..

### References

* #0000

**Comment by timothyjrogers** [comment]
I picked this up and have  PR open for it.

**Comment by ewbankkit** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/26629.
