### ISSUE TITLE
[aws_flow_log] The log_destination parameter forces replacement for CloudWatch log ARN due to trimmed suffix :*

### ISSUE THREAD

**Issue by Nachiket-K** [hashicorp/terraform-provider-aws#26479]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform 0.12.31 
AWS Provider 3.70.0 

### Affected Resource(s)

* aws_flow_log 

### Terraform Configuration Files

```hcl
resource "aws_flow_log" "this" { 
  eni_id                   = "eni- xxxxxxxxxxxxxxxxx " 
  traffic_type             = "ALL" 
  iam_role_arn             = "arn:aws:iam::xxxxxxxxxxxx:role/log-group-role" 
  log_destination_type     = "cloud-watch-logs" 
  log_destination          = "arn:aws:logs:us-east-1:xxxxxxxxxxxx:log-group:my-log-group:*" 
} 
```

### Expected Behavior

- As per the fix implemented in  [#6377](https://github.com/hashicorp/terraform-provider-aws/pull/6377), Terraform trims the :*  suffix added by the API for greater compatibility with other AWS services that do not accept the suffix. 

 

- However, after trimming the suffix, the difference should be suppressed to avoid the force replacement as per the following comment: https://github.com/hashicorp/terraform-provider-aws/issues/6373#issuecomment-436416942

### Actual Behavior

- If the CloudWatch Log ARN is passed with the suffix (as returned by the API) or, if the ‘aws_cloudwatch_log_group’ DataSource is used (for provider version 3.70.0) then: 

- Terraform trims the ARN by removing :* but, shows a difference in the consecutive apply command. This leads to a force replacement of the resource. 

```
> terraform apply 
aws_flow_log.this: Refreshing state... [id=fl- xxxxxxxxxxxxxxxxx] 
An execution plan has been generated and is shown below. 
Resource actions are indicated with the following symbols: 
-/+ destroy and then create replacement 

Terraform will perform the following actions: 

  # aws_flow_log.this must be replaced 
-/+ resource "aws_flow_log" "this" { 
      ~ arn                      = "arn:aws:ec2:us-east-1: xxxxxxxxxxxx:vpc-flow-log/fl- xxxxxxxxxxxxxxxxx " -> (known after apply) 
        eni_id                   = "eni- xxxxxxxxxxxxxxxxx " 
        iam_role_arn             = "arn:aws:iam:: xxxxxxxxxxxx:role/log-group-role" 
      ~ id                       = "fl- xxxxxxxxxxxxxxxxx " -> (known after apply) 
      ~ log_destination          = "arn:aws:logs:us-east-1: xxxxxxxxxxxx:log-group:my-log-group" -> "arn:aws:logs:us-east-1: xxxxxxxxxxxx:log-group:my-log-group:*"  
# forces replacement 
        log_destination_type     = "cloud-watch-logs" 
      ~ log_format               = "${version} ${account-id} ${interface-id} ${srcaddr} ${dstaddr} ${srcport} ${dstport} ${protocol} ${packets} ${bytes} ${start}  
${end} ${action} ${log-status}" -> (known after apply) 
      ~ log_group_name           = "my-log-group" -> (known after apply) 
        max_aggregation_interval = 600 
      - tags                     = {} -> null 
      ~ tags_all                 = {} -> (known after apply) 
        traffic_type             = "ALL" 
    } 

Plan: 1 to add, 0 to change, 1 to destroy. 

```
### Steps to Reproduce

1. `terraform apply`(where the log_destination parameter contains the ARN of a CloudWatch group as returned by the API i.e., with the :* suffix) 
2. `terraform apply`

### Important Factoids

- In 3.70.0 provider version, the resource ‘aws_cloudwatch_log_group’  returns the ARN without a suffix. 

- However, the DataSource ‘aws_cloudwatch_log_group’ continues to return ARN with the suffix :* for provider versions < 4.0.0 

### References

- https://registry.terraform.io/providers/hashicorp/aws/3.70.0/docs/resources/cloudwatch_log_group#arn

**Comment by justinretzolk** [comment]
Hey @Nachiket-K 👋 Thank you for taking the time to raise this! There's been quite a few updates to the provider between `3.70.0` and now that I suspect might improve the behavior here. Are you able to test with a newer version of the provider/Terraform?

**Comment by Nachiket-K** [comment]
- As suggested, I have tested the log_destination parameter in the latest provider version (4.28.0) However, the issue still persists.

- If the log_destination parameter consists of CloudWatch Log ARN with the suffix :* , then, it gets trimmed in the first apply which leads to a force replacement in consecutive apply commands (The change in the ARN after trimming :* doesn't get suppressed)
