### ISSUE TITLE
terraform failing with "connection is shutdown"

### ISSUE THREAD

**Issue by kumaran85** [hashicorp/terraform-provider-aws#26480]
Using terraform version 0.11.15, when we create the peering , main.tf file has about 20 modules. 
it's failing with "connection is shutdown".
when using less modules, more or less 5 , it's passing without issues.

our terraform running on  ECS FARGATE containers.
Please help us to fix the issue.

**Comment by justinretzolk** [comment]
Hey @kumaran85 👋 Thank you for taking the time to raise this! This sounds like what I would typically expect to see when Terraform encounters an out of memory error. Given that you're seeing this exclusively when using additional modules, I'm fairly confident in saying that if you increased the memory allocation, the issue would likely disappear. If not, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
