### ISSUE TITLE
tf plan/apply with aws_lambda_function in me-central-1 throws errors

### ISSUE THREAD

**Issue by muellerc** [hashicorp/terraform-provider-aws#26486]
Community Note

    Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
    Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
    If you are interested in working on this issue or have submitted a pull request, please leave a comment

As announced [here](https://aws.amazon.com/blogs/publicsector/aws-launching-new-region-in-uae-in-2022/), AWS is launching a new region in UAE in 2022 and more are in the [works](https://aws.amazon.com/blogs/aws/category/regions/).    
While testing the region in UAE (region code me-central-1), I'm getting the same error as reported in issue [22692](https://github.com/hashicorp/terraform-provider-aws/issues/22692), as Code Signer is not available yet.

**Terraform CLI and Terraform AWS Provider Version**

Terraform v1.2.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.27.0
+ provider registry.terraform.io/hashicorp/archive v2.2.0

**Affected Resource(s)**

    aws_lambda_function

**Terraform Configuration Files**

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```
data "archive_file" "function_zip" {
  type        = "zip"
  source_file = "function/demo_function.py"
  output_path = "function/demoFunction.zip"
}

resource "aws_lambda_function" "demo_function" {
  filename      = "function/demoFunction.zip"
  function_name = "demo-function"
  runtime       = "python3.8"
  handler       = "lambda_function.lambda_handler"
  role          = aws_iam_role.lambda_role.arn
  source_code_hash = data.archive_file.function_zip.output_base64sha256
  timeout       = 5
}

resource "aws_iam_role" "lambda_role" {
  name = "lambda_role"
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}
```

**Expected Behavior**

No errors should be printed
Actual Behavior

terraform throws error, however lambda gets created

```
|
│ Error: error getting Lambda Function (demo-function) code signing config AccessDeniedException: 
│       status code: 403, request id: 7ce55dac-feea-47a3-895e-06436d81f5e8
│ 
│ 
|
```

Steps to Reproduce

    Create lambda resource in me-central-1
    terraform apply

**Comment by muellerc** [comment]
Could you please take a look at this fix and consider it for inclusion into the next release.

**Comment by MoeltnerM** [comment]
+1

**Comment by muellerc** [comment]
The region me-central-1 went public today.
Every user of Terraform who wants to deploy a Lambda function in this region will hit this issue.

**Comment by ewbankkit** [comment]
After merging https://github.com/hashicorp/terraform-provider-aws/pull/26590 I can reproduce this:

```console
% AWS_DEFAULT_REGION=me-central-1 make testacc TESTARGS='-run=TestAccLambdaFunction_basic' PKG=lambda ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 2  -run=TestAccLambdaFunction_basic -timeout 180m
=== RUN   TestAccLambdaFunction_basic
=== PAUSE TestAccLambdaFunction_basic
=== CONT  TestAccLambdaFunction_basic
    function_test.go:46: Step 1/2 error: Error running apply: exit status 1
        
        Error: error getting Lambda Function (tf_acc_lambda_func_basic_8m8zxsrq) code signing config AccessDeniedException: 
        	status code: 403, request id: c8993f50-3b64-45fd-9b07-179097ba639c
        
          with aws_lambda_function.test,
          on terraform_plugin_test.tf line 134, in resource "aws_lambda_function" "test":
         134: resource "aws_lambda_function" "test" {
        
--- FAIL: TestAccLambdaFunction_basic (33.87s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/lambda	40.681s
FAIL
make: *** [testacc] Error 1
```
