### ISSUE TITLE
Amazon Aurora supports IPv6

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#26487]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> [Amazon Aurora](https://aws.amazon.com/rds/aurora/) now offers customers the option to use Internet Protocol version 6 (IPv6) addresses in their Amazon Virtual Private Cloud (VPC) on new and existing Amazon Aurora instances.

### New or Affected Resource(s)

* `aws_rds_cluster`
* `aws_rds_cluster_instance`

### Potential Terraform Configuration

```hcl
resource "aws_rds_cluster" "example" {
  network_type = "DUAL"
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2022/08/amazon-aurora-supports-ipv6/).
[User guide](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_VPC.WorkingWithRDSInstanceinaVPC.html#USER_VPC.IP_addressing).
Relates: https://github.com/hashicorp/terraform-provider-aws/issues/24822.

**Comment by bschaatsbergen** [comment]
I'll happily pick this up.
