### ISSUE TITLE
Add Origin Access Control (OAC) to CloudFront

### ISSUE THREAD

**Issue by vincentclee** [hashicorp/terraform-provider-aws#26490]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon CloudFront now offers Origin Access Control, a new feature that enables CloudFront customers to easily secure their S3 origins by permitting only designated CloudFront distributions to access their S3 buckets. Customers can now enable [AWS Signature Version 4](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html) (SigV4) on CloudFront requests to S3 buckets with the ability to set when and if CloudFront should sign requests. Additionally, customers can now use [SSE-KMS](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingKMSEncryption.html) when performing uploads and downloads through CloudFront.

### New or Affected Resource(s)

* [aws_cloudfront_distribution](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution)
* aws_cloudfront_origin_access_control ?

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* [Amazon CloudFront launches Origin Access Control (OAC)](https://aws.amazon.com/about-aws/whats-new/2022/08/amazon-cloudfront-origin-access-control)
* [Blog post](https://aws.amazon.com/blogs/networking-and-content-delivery/amazon-cloudfront-introduces-origin-access-control-oac/)

<img width="751" src="https://user-images.githubusercontent.com/5388077/186774256-cd3c82b8-051a-430d-ad9e-f1c8aa2c11dc.png">

**Comment by roberth-k** [comment]
I'll pick this up.
