### ISSUE TITLE
aws_s3_bucket_website_configuration causes creating forever bug until eventual timeout

### ISSUE THREAD

**Issue by breisig** [hashicorp/terraform-provider-aws#26492]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.2.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.28.0
### Affected Resource(s)

aws_s3_bucket_website_configuration

### Terraform Configuration Files

Here is my configuration file

```hcl

# Initialize AWS Provide credentials
provider "aws" {
  region                  = var.region
  shared_credentials_files = ["~/.aws/credentials"]
  profile                 = var.aws_cli_profile

  endpoints {
    ec2 = "https://ec2-fips.ca-central-1.amazonaws.com"
    kms = "https://kms-fips.ca-central-1.amazonaws.com"
    s3  = "https://s3-fips.ca-central-1.amazonaws.com"
    rds = "https://rds-fips.ca-central-1.amazonaws.com"
  }
}

resource "aws_s3_bucket" "s3_bucket_processed" {
  bucket = "my-bucket-name"
  force_destroy = true

 # Depends on the KMS key first being generated in order before running this.
 depends_on = [ var.kms_key_arn ]
}


resource "aws_s3_bucket_acl" "s3_bucket_processed_acl" {
  bucket = aws_s3_bucket.s3_bucket_processed.id
  #acl    = "private"
  acl    = "public-read"
}

resource "aws_s3_bucket_website_configuration" "public_bucket" {
  bucket = aws_s3_bucket.s3_bucket_processed.bucket

  index_document {
    suffix = "index.html"
  }

  error_document {
    key = "404.html"
  }

}


resource "aws_s3_bucket_server_side_encryption_configuration" "s3_bucket_processed" {
  bucket = aws_s3_bucket.s3_bucket_processed.bucket

  rule {
    apply_server_side_encryption_by_default {
      kms_master_key_id = var.kms_key_arn
      sse_algorithm     = "aws:kms"
    }
  }
}
```

### Expected Behavior

Create a static website s3 bucket and not sit at 'creating' forever until it eventually times out.

### Actual Behavior

aws_s3_bucket_website_configuration.public_bucket: Still creating... [10s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [20s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [30s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [40s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [50s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [1m0s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [1m10s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [1m20s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [1m30s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [1m40s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [1m50s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [2m0s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [2m10s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [2m20s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [2m30s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [2m40s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [2m50s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [3m0s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [3m10s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [3m20s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [3m30s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [3m40s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [3m50s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [4m0s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [4m10s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [4m20s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [4m30s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [4m40s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [4m50s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [5m0s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [5m10s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [5m20s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [5m30s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [5m40s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [5m50s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [6m0s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [6m10s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [6m20s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [6m30s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [6m40s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [6m50s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [7m0s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [7m10s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [7m20s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [7m30s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [7m40s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [7m50s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [8m0s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [8m10s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [8m20s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [8m30s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [8m40s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [8m50s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [9m0s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [9m10s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [9m20s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [9m30s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [9m40s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [9m50s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [10m0s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [10m10s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [10m20s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [10m30s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [10m40s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [10m50s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [11m0s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [11m10s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [11m20s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [11m30s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [11m40s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [11m50s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [12m0s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [12m10s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [12m20s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [12m30s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [12m40s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [12m50s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [13m0s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [13m10s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [13m20s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [13m30s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [13m40s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [13m50s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [14m0s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [14m10s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [14m20s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [14m30s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [14m40s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [14m50s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [15m0s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [15m10s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [15m20s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [15m30s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [15m40s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [15m50s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [16m0s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [16m10s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [16m20s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [16m30s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [16m40s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [16m50s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [17m0s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [17m10s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [17m20s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [17m30s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [17m40s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [17m50s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [18m0s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [18m10s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [18m20s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [18m30s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [18m40s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [18m50s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [19m0s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [19m10s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [19m20s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [19m30s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [19m40s elapsed]
aws_s3_bucket_website_configuration.public_bucket: Still creating... [19m50s elapsed]
╷
│ Error: error getting S3 Bucket (my-bucket-name) Location: RequestCanceled: request context canceled
│ caused by: context deadline exceeded
│
│   with aws_s3_bucket_website_configuration.public_bucket,
│   on .main.tf line 178, in resource "aws_s3_bucket_website_configuration" "public_bucket":
│  178: resource "aws_s3_bucket_website_configuration" "public_bucket" {
│

### Steps to Reproduce

`terraform apply`

* #0000

**Comment by justinretzolk** [comment]
Hey @breisig 👋 Thank you for taking the time to raise this! So that we have all of the information that might be helpful in investigating this, are you able to supply debug logs (redacted as necessary) as well?

**Comment by breisig** [comment]
@justinretzolk What's the best way to get that for you?

**Comment by breisig** [comment]
@justinretzolk Ok. I did some *further* testing and can now trace down how to trigger it.

1) If I *remove* the FIPS S3 endpoint from the config, it works without issue
```
provider "aws" {
  region                  = var.region
  shared_credentials_files = ["~/.aws/credentials"]
  profile                 = var.aws_cli_profile

  endpoints {
    ec2 = "https://ec2-fips.ca-central-1.amazonaws.com"
    kms = "https://kms-fips.ca-central-1.amazonaws.com"
    #s3  = "https://s3-fips.ca-central-1.amazonaws.com"
    rds = "https://rds-fips.ca-central-1.amazonaws.com"
  }
}
```
2) Or if I continue to enable/use the FIPS S3 endpoint *but* disable the resource [resource "aws_s3_bucket_website_configuration" "public_bucket"], it works but of course the s3 bucket is not a static website.

resource "aws_s3_bucket_website_configuration" "public_bucket" {
  bucket = aws_s3_bucket.s3_bucket_processed.bucket

  index_document {
    suffix = "index.html"
  }

  error_document {
    key = "404.html"
  }

}

I would really like to continue using the FIPS S3 url endpoint as it's a requirement from our clients
