### ISSUE TITLE
Terraform S3 backend does not use sso credentials

### ISSUE THREAD

**Issue by dbalan** [hashicorp/terraform-provider-aws#26504]
### Terraform Version

```shell
Terraform v1.2.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.27.0
```

### Terraform Configuration Files

```terraform
terraform {
  backend "s3" {
    bucket  = "bucket"
    key     = "infra"
    profile = "awssso"
    region  = "us-west-2"
  }
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.27"
    }
  }
}
```

### Debug Output

```
Initializing the backend...
Error refreshing state: AccessDenied: Access Denied
	status code: 403, request id: 2B42Q2DQK35X81PV, host id: wtDRvg3/JiTiug8ai5IVjDUSXeb5xHayVcM4wh/psVCfIoLIuwwlTSnf9/iPgm2sIjR1lpVuAVA=
```

### Expected Behavior

Terraform should be able to init state with AWS credentials

### Actual Behavior

Access denied.

### Steps to Reproduce

1. `terraform init` with aws cli2 and an sso login profile
2. 

### Additional Context

AWS CLI is configured using `aws configure sso`

**Comment by justinretzolk** [comment]
Hey @dbalan 👋 I'm the community manager for the AWS Provider. I transferred your issue over here because I've seen some other authentication related issues filed recently and felt like this may be related, despite being the S3 backend.

**Comment by dbalan** [comment]
Hey! I was mistaken about the back-end and state requests were failing because of a restrictive bucket policy. (
