### ISSUE TITLE
In "ce_anomaly_subscription#basic-example" , type      = "DIMENSIONAL" → monitor_type      = "DIMENSIONAL"

### ISSUE THREAD

**Issue by mathken029** [hashicorp/terraform-provider-aws#26505]
It would be good to change the wording of the following sample page as follows The wording before the change was not successful.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ce_anomaly_subscription#basic-example

type      = "DIMENSIONAL"
↓
monitor_type      = "DIMENSIONAL"

**Comment by mathken029** [comment]
The same applies below.

dimension = "SERVICE"
↓
monitor_dimension = "SERVICE"

**Comment by justinretzolk** [comment]
Hey @mathken029 👋 Thank you for taking the time to raise this! I've raised a PR to correct the documentation.
