### ISSUE TITLE
TF FIS enhance to support template name

### ISSUE THREAD

**Issue by dhartford** [hashicorp/terraform-provider-aws#26519]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for template 'name'.

(alternatively, 'template_name' would work as well)

### New or Affected Resource(s)

* aws_fis_experiment_template

### Potential Terraform Configuration

```hcl
resource "aws_fis_experiment_template" "named_fis_template" {
  description = "Test chaos scenario 101010"
  name = "chaos_scenario_42"
  ...
```

### References

Current AWS Console view of TF deployed FIS template:

![image](https://user-images.githubusercontent.com/2898108/187217377-535e3752-9c1e-42c5-a03a-425e2ae0111d.png)

* #0000

**Comment by spotter9** [comment]
You can configure this by using `tags` within the `aws_fis_experiment_template` resource block:
```
  tags = {
    Name = "This is the Name of my experiment"
  }
```

![image](https://user-images.githubusercontent.com/67321245/201691438-7f125a64-b427-4bdd-9dfa-315fa795d62e.png)
