### ISSUE TITLE
Terraform throws an error for azurerm_postgresql_flexible_server after replacement in 2nd terraform apply for create_mode = PointInTimeRestore

### ISSUE THREAD

**Issue by MayuriD89** [hashicorp/terraform-provider-aws#26518]
**Terraform and Azure Provider Version**

- Terraform v1.0.0
- Azure Provider Version v3.20.0

**Affected Resource**

- azurerm_postgresql_flexible_server

**Expected Behavior**

- azurerm_postgresql_flexible_server should get created successfully after showing one change in private DNS zone because of case sensitivity issue in resource group.

**Actual behavior**

- for create_mode - PointInTimeRestore, azurerm_postgresql_flexible_server gets created successfully after 1st apply command but tags and high_availability parameter doesn't get applied in that.
- During 2nd apply it shows 1 replacement for private dns zone and try to add tags and high_availability values and it fails and gives following error -
`Error: waiting for creation of the Postgresql Flexible Server "postgres-flex-sv-test04" (Resource Group "TERAIA_PUNE_TEST_RG"): Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: 'bbedc118-e9d2-4eb5-ad95-0d4180007a2e'"
`
- replacement for private dns zone is expected because there is a case sensitivity issue in the ARN (resource group name is converted into lower case after server creation)
- If we try the same configuration with lower case of private dns zone that means there is no force replacement only modification resource gets created successfully after 2nd apply too.

**terraform configuration we have used -**

```
`azurerm_postgresql_flexible_server = {
  postgres-flex-sv-test04 = {
    DataSource = {
    delegated_subnet_id = {
        resource_group_name  = "RG"
        name                 = "snet-test01"
        virtual_network_name = "vnet-test01"
      }
      private_dns_zone_id = {
        resource_group_name = "RG"
        name                = "trial01.private.postgres.database.azure.com"
      }
      source_server_id = {
        resource_group_name = "RG"
        name                = "test-flex-sv"
      }
    }
    location                          = "JapanEast"
    resource_group_name               = "RG"
    name                              = "postgres-sv-test04"
    backup_retention_days             = 7
   geo_redundant_backup_enabled      = true
    create_mode                       = "PointInTimeRestore"
    point_in_time_restore_time_in_utc = "2022-08-29T9:45:27Z"
    sku_name                          = "GP_Standard_D2s_v3"
   storage_mb                        = 32768
    zone                              = 2
     high_availability = {
      mode                      = "ZoneRedundant"
      standby_availability_zone = 1
     }
    maintenance_window = {
      day_of_week  = 0
      start_hour   = 3
      start_minute = 20
    }
    tags = {
      Name          = "postgres-sv-test04"
    }
  }
}
`
```
- We have also tried by keeping only required parameters -

```
`azurerm_postgresql_flexible_server = {
  postgres-flex-sv-test04 = {
    DataSource = {
      source_server_id = {
        resource_group_name = "RG"
        name                = "test-flex-sv"
      }
    }
    location                          = "JapanEast"
    resource_group_name               = "RG"
    name                              = "postgres-sv-test04"
    create_mode                       = "PointInTimeRestore"
    point_in_time_restore_time_in_utc = "2022-08-29T9:45:27Z"
  }
}`

```
- But for this also after 1st apply resource gets created successfully but for 2nd apply terraform does a force replacement for delegated_subnet_id which got attach to server after 1st apply and it fails after replacement and gives same error mentioned above.

- **We also tried different timestamps for  point_in_time_restore_time_in_utc parameter as with same time from Azure portal server gets created successfully but not from terraform, so this might be the reason for destruction and error.** 

**Steps to Reproduce**

- terraform apply (after resource creation i.e 2nd terraform apply)

**Comment by justinretzolk** [comment]
Hey @MayuriD89 👋 Thank you for taking the time to raise this! It looks like this is actually an issue with the Azure provider, so you'll want to open an issue in the [`terraform-provider-azurerm` repository](https://github.com/hashicorp/terraform-provider-azurerm). With that in mind, we'll go ahead and close this issue out.
