### ISSUE TITLE
Enable commenting in Network Firewall Suricata compatible IPS rules

### ISSUE THREAD

**Issue by matekuzdi** [hashicorp/terraform-provider-aws#26517]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v1.2.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.25.0
```

### Affected Resource(s)

* aws_networkfirewall_rule_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  region = "eu-central-1"
}

terraform {
  required_version = ">= v1.0.11"
}
```

### Debug Output

│ Error: error updating NetworkFirewall Rule Group (arn:aws:network-firewall:eu-central-1:*:stateful-rulegroup/*suricata-nwfw-rule-group): InvalidReque, reason: Illegal rule syntax: #kommentrule: #komment

### Expected Behavior

Comments should be enabled in suricata rules

### Steps to Reproduce

Rule source is:

```
#this is a comment
pass tcp $WEBSERVERS_HOSTS any <> $EXTERNAL_HOST $HTTP_PORTS (sid:210003;)
```

**Comment by schuylr** [comment]
I modified the `TestAccNetworkFirewallRuleGroup_Basic_rules` test to have the following rule source [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/networkfirewall/rule_group_test.go#L155):

```
	rules := `#test comment
alert http any any -> any any (http_response_line; content:"403 Forbidden"; sid:1;)`
```

And ran `make testacc TESTARGS='-run=TestAccNetworkFirewallRuleGroup_Basic_rules' PKG=networkfirewall` with the following output:

```
terraform-provider-aws % make testacc TESTARGS='-run=TestAccNetworkFirewallRuleGroup_Basic_rules' PKG=networkfirewall
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/networkfirewall/... -v -count 1 -parallel 20  -run=TestAccNetworkFirewallRuleGroup_Basic_rules -timeout 180m
=== RUN   TestAccNetworkFirewallRuleGroup_Basic_rulesSourceList
=== PAUSE TestAccNetworkFirewallRuleGroup_Basic_rulesSourceList
=== RUN   TestAccNetworkFirewallRuleGroup_Basic_rules
=== PAUSE TestAccNetworkFirewallRuleGroup_Basic_rules
=== CONT  TestAccNetworkFirewallRuleGroup_Basic_rulesSourceList
=== CONT  TestAccNetworkFirewallRuleGroup_Basic_rules
--- PASS: TestAccNetworkFirewallRuleGroup_Basic_rules (143.35s)
--- PASS: TestAccNetworkFirewallRuleGroup_Basic_rulesSourceList (143.80s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/networkfirewall	147.834s
```

It's possible that this may have been an upstream error with the AWS Network Firewall service that was fixed since this issue was posted.

@matekuzdi Can you verify that this is still reproducible on your end?
