### ISSUE TITLE
Flag to minify aws_iam_policy_document data source

### ISSUE THREAD

**Issue by nitrocode** [hashicorp/terraform-provider-aws#26531]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be nice to minify the policy document json to keep within policy limits.

### New or Affected Resource(s)

* `aws_iam_policy_document`

### Potential Terraform Configuration

```hcl
data "aws_iam_policy_document" "default" {
  minify = true

  statement {
    sid = "1"

    actions = [
      "s3:ListAllMyBuckets",
      "s3:GetBucketLocation",
    ]

    resources = [
      "arn:aws:s3:::*",
    ]
  }
}
```

Workaround is to do the following

```hcl
  jsonencode(jsondecode(data.aws_iam_policy_document.default.json))
```

### References

* Related to https://github.com/hashicorp/terraform-provider-aws/issues/25988

**Comment by lorengordon** [comment]
Not stale

**Comment by nitrocode** [comment]
Hi @lorengordon, this might have been fixed by the recent addition of the `minified_json` attribute via PR https://github.com/hashicorp/terraform-provider-aws/pull/35677 in https://github.com/hashicorp/terraform-provider-aws/blob/v5.49.0/CHANGELOG.md

Ref https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document#minified_json

**Comment by lorengordon** [comment]
Oh! I didn't see any refs from linked prs. Close away, if there's a reasonable way forward!

> Hi @lorengordon, this might have been fixed by the recent addition of the `minified_json` attribute via PR https://github.com/hashicorp/terraform-provider-aws/pull/35677 in https://github.com/hashicorp/terraform-provider-aws/blob/v5.49.0/CHANGELOG.md
> 
> Ref https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document#minified_json
