### ISSUE TITLE
AWS Lambda Node.js 12 Runtime Deprecation - Update docs, examples, and acceptance tests to use a newer Node.js runtime

### ISSUE THREAD

**Issue by scottwestover** [hashicorp/terraform-provider-aws#26576]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Node.js 12 runtime reached the end of life status on April 30th, 2022, and as a result AWS will stop supporting this runtime in AWS Lambda. The deprecation is done in phases, with the first phase targeting Nov 14, 2022 and the second phase is targeting Dec 14, 2022. Once phase two starts, you will not be able to create or update any AWS Lambda functions that use that runtime.

As a result, this will break a number of acceptance tests have been built since those tests use this runtime. To avoid the issue in the future, the tests can be updated to a newer version of the Node.js runtime.

Also, there are a few examples and documentation references that reference the `nodejs12.x` runtime.

### New or Affected Resource(s)

* aws_lambda_function
* any resource that is reference the `aws_lambda_function` resource

Note: this would not affect the resource itself, and would only affect the acceptance tests and docs that reference the `nodejs12.x` runtime.

### Potential Terraform Configuration

No changes to existing resource configurations.

### References

AWS Lambda Runtime Support Policy: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy
Node.js 12 EOL: https://nodejs.org/es/blog/release/v12.22.12/

**Comment by scottwestover** [comment]
I would be interested in working on this issue.

**Comment by justinretzolk** [comment]
Looks like this was fixed with #26967. As such, closing.
