### ISSUE TITLE
the parameter day_of_week of maintenance_start_time in aws_storagegateway_gateway source block can't be 0

### ISSUE THREAD

**Issue by beyu2022** [hashicorp/terraform-provider-aws#26597]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v1.2.8 on darwin_amd64
AWS Provider Version 4.28.0

### Affected Resource(s)

* aws_storagegateway_gateway

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_storagegateway_gateway" "storage-gateway" {
  gateway_ip_address = aws_instance.server.public_ip
  gateway_name       = "awsdev-storagegateway"
  gateway_timezone   = "GMT-8:00"
  gateway_type       = "FILE_S3"

  # How long to wait for gateway activation and connection to Storage Gateway
  timeouts {
    create = "5m"
  }

  #maintenance start time sunday 08:30
  maintenance_start_time {
    day_of_week = 0
    hour_of_day = 8
    minute_of_hour = 30
  }
}
```

### Debug Output
if set parameter day_of_week not zero value (1-6),terraform can apply successfully with correct update on aws.
try run by using aws cli ,it can use zero value. conside can't use zero value via terraform.

aws --profile eng storagegateway    update-maintenance-start-time  --gateway-arn arn:aws:storagegateway:us-west-2:xxxxxxxxxxxxx:gateway/sgw-XXXXXXXX  --day-of-week 0 --hour-of-day 8 --minute-of-hour 30
{
    "GatewayARN": "arn:aws:storagegateway:us-west-2:xxxxxxxxxxxx:gateway/sgw-XXXXXXXX"
}

### Panic Output
│ Error: error updating Storage Gateway Gateway (arn:aws:storagegateway:us-west-2:xxxxxxxxxxxx:gateway/sgw-XXXXXXXX) maintenance start time: InvalidGatewayRequestException: Either one of DayOfMonth or DayOfWeek must be specified
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "69176e4f-2a7b-4103-a03f-xxxxxxxxxxxx"
│   },
│   Error_: {
│     ErrorCode: "InvalidParameters"
│   },
│   Message_: "Either one of DayOfMonth or DayOfWeek must be specified"
│ }
│
│   with aws_storagegateway_gateway.storage-gateway,
│   on main.tf line 48, in resource "aws_storagegateway_gateway" "storage-gateway":
│   48: resource "aws_storagegateway_gateway" "storage-gateway" {
│
╵
Releasing state lock. This may take a few moments...

### Expected Behavior
based on document, if set parameter day_of_week = 0 , after terraform apply, it should update the maintenance start time of storagegateway to Sunday 08:30.

### Actual Behavior
get the panic output  with errorCode "InvalidParameters" and massage "Either one of DayOfMonth or DayOfWeek must be specified"

### Steps to Reproduce

1. `terraform apply`

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/storagegateway_gateway

**Comment by dublinsubway** [comment]
I can try to tackle it if folks are okay with me taking (reasonably) long time.

**Comment by sodle** [comment]
https://github.com/hashicorp/terraform-provider-aws/pull/34015 will fix this.
