### ISSUE TITLE
aws_acm_certificate not returning certificate valid time stamps

### ISSUE THREAD

**Issue by ThePrankMonkey** [hashicorp/terraform-provider-aws#26605]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.2.8 on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.24.0
```

### Affected Resource(s)

* aws_acm_certificate

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_acm_certificate" "project_domain" {
  certificate_body  = file("${path.module}/files/cert/body.crt")
  certificate_chain = file("${path.module}/files/cert/chain.crt")
  private_key       = file("${path.module}/files/cert/private.key")
}
# ...
output "step-06-cert_notes" {
  value     = aws_acm_certificate.project_domain.not_after
}
```

### Expected Behavior

I expect to see an expiration date, per the documentation.

Neither `.not_after` or `.not_before` work for output. I can get `.status` and others.

### Actual Behavior

```
Error: Unsupported attribute
│ 
│   on outputs.tf line 47, in output "step-06-cert_notes":
│   47:   value = aws_acm_certificate.project_domain.not_after
│ 
│ This object has no argument, nested block, or exported attribute named "not_after".
```

### Steps to Reproduce

1. `terraform apply`

### References

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate#not_after
* #0000

**Comment by scottwestover** [comment]
@ThePrankMonkey The `not_after` and `not_before` were recently added in the in the `4.27.0` version of provider.  More details here in the changelog here: https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.27.0.

You mentioned using version `4.24.0`. Can you please try updating your provider version to see if that resolves the issue?

**Comment by ThePrankMonkey** [comment]
Duh, that was it. I don't think I had ran `terraform init --upgrade` recently.
