### ISSUE TITLE
New Resource: aws_identitystore_user

### ISSUE THREAD

**Issue by justinretzolk** [hashicorp/terraform-provider-aws#26607]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As mentioned in the "tracked in" issue, Identity Store now has API operations to create/update/delete users. A new resource should be created to support this.

### New or Affected Resource(s)

* aws_identitystore_user

### Potential Terraform Configuration

```hcl
resource "aws_identitystore_user" "this" {
  display_name      = "Example User"
  identity_store_id = tolist(data.aws_ssoadmin_instances.example.arns)[0]

  emails {
    primary = true
    type    = "work"
    value   = "example@example.com
  } 

  # Likely additional arguments
}
```

### References

* #26598
* API References:
  * [Create](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_CreateUser.html)
  * [Update](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_UpdateUser.html)
  * [Delete](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_DeleteUser.html)

**Comment by bschaatsbergen** [comment]
I'll happily check this out.

**Comment by mitchellharvey97** [comment]
This would also solve https://github.com/hashicorp/terraform-provider-aws/issues/18812

**Comment by roberth-k** [comment]
I'll pick this up.

**Comment by antonioned** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/26598

**Comment by tatsuo48** [comment]
https://github.com/hashicorp/terraform-provider-aws/pull/26948

**Comment by ewbankkit** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/26948.
