### ISSUE TITLE
aws_transfer_ssh_key multiple keys per user

### ISSUE THREAD

**Issue by georgegil** [hashicorp/terraform-provider-aws#26601]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As part of the File Transfer Family, configuring SSH users, it will be quire useful to be able to specify more than one SSH public key in the resource as in AWS console one can have more then one SSH key per user.

### New or Affected Resource(s)

* aws_transfer_ssh_key

### Potential Terraform Configuration

```hcl

variable "users" {
  description = "Users needing access to this SFTP server"
  type = map(object({
    ssh_pub_key = list(string)
    }
  ))
}

resource "aws_transfer_ssh_key" "ssh" {
  for_each  = var.users
  server_id = aws_transfer_server.sftp_svr.id
  user_name = aws_transfer_user.usr[each.key].user_name
  body      = each.value.ssh_pub_key
}

```

```
users = {
    gglabs = {
      ssh_pub_key = ["rsa-ssh hjkdfhskjdfhsdj...", "rsa jsdfrsandfjn..."]
    }
  }

```

**Comment by justinretzolk** [comment]
Hey @georgegil 👋 Thank you for taking the time to raise this! I took a quick look, and it looks like this is limited by the underlying [SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/transfer/#ImportSshPublicKeyInput) / [API](https://docs.aws.amazon.com/transfer/latest/userguide/API_ImportSshPublicKey.html).

That said, I believe you can achieve this functionality using a combination of [`for` expressions](https://www.terraform.io/language/expressions/for) and the [`merge()` function](https://www.terraform.io/language/functions/merge). I did a quick with that in mind and came up with the following.

```hcl
variable "users" {
  description = "Users needing access to this SFTP server"
  type = map(object({
    ssh_pub_key = list(string)
    }
  ))
}

locals {
  user_certificates = merge([
    for user, values in var.users : {
      for key_index, key_data in values.ssh_pub_key : "${user}.${key_index}" => key_data
    }
  ]...)
}

resource "aws_transfer_ssh_key" "ssh" {
  for_each  = local.user_certificates
  server_id = aws_transfer_server.sftp_svr.id
  user_name = aws_transfer_user.usr[each.key].user_name
  body      = each.value
}
```

To illustrate this, I used a `random_pet` resource with a similar structure. The test configuration is:

```hcl
variable "users" {
  type = map(object({
    ssh_pub_key = list(string)
  }))
  default = {
    justin = {
      ssh_pub_key = ["one", "two"]
    },
    not_justin = {
      ssh_pub_key = ["three", "four"]
    }
  }
}

locals {
  user_certificates = merge([
    for user, values in var.users : {
      for key_index, key_data in values.ssh_pub_key : "${user}.${key_index}" => key_data
    }
  ]...)
}

# Using the username and "ssh pub key data" as the prefix as an example to show retrieving both
resource "random_pet" "this" {
  for_each = local.user_certificates
  prefix = "${each.key}-${each.value}-"
}
```

When running `terraform plan`, the following is the output:

```shell
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # random_pet.this["justin.0"] will be created
  + resource "random_pet" "this" {
      + id        = (known after apply)
      + length    = 2
      + prefix    = "justin.0-one-"
      + separator = "-"
    }

  # random_pet.this["justin.1"] will be created
  + resource "random_pet" "this" {
      + id        = (known after apply)
      + length    = 2
      + prefix    = "justin.1-two-"
      + separator = "-"
    }

  # random_pet.this["not_justin.0"] will be created
  + resource "random_pet" "this" {
      + id        = (known after apply)
      + length    = 2
      + prefix    = "not_justin.0-three-"
      + separator = "-"
    }

  # random_pet.this["not_justin.1"] will be created
  + resource "random_pet" "this" {
      + id        = (known after apply)
      + length    = 2
      + prefix    = "not_justin.1-four-"
      + separator = "-"
    }

Plan: 4 to add, 0 to change, 0 to destroy.
```

**Comment by georgegil** [comment]
Sir you are my hero! 

`for` expressions are my nemisis. 

Thank you!
