### ISSUE TITLE
New Resource: aws_identitystore_group

### ISSUE THREAD

**Issue by justinretzolk** [hashicorp/terraform-provider-aws#26606]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As mentioned in the "tracked in" issue, Identity Store now has API operations to create/update/delete groups. A new resource should be created to support this.

### New or Affected Resource(s)

* aws_identitystore_group

### Potential Terraform Configuration

```hcl
resource "aws_identitystore_group" "this" {
  description       = "Example description"
  display_name      = "example_group"
  identity_store_id = tolist(data.aws_ssoadmin_instances.example.arns)[0]
}
```

### References

* #26598
* API References:
  * [Create](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_CreateGroup.html)
  * [Update](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_UpdateGroup.html)
  * [Delete](https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_DeleteGroup.html)

**Comment by bschaatsbergen** [comment]
Picking this one up.

**Comment by bschaatsbergen** [comment]
Pending #[26621](https://github.com/hashicorp/terraform-provider-aws/pull/26621)
