### ISSUE TITLE
data.aws_lambda_function invoke_arn invalid after upgrade to 4.29.0

### ISSUE THREAD

**Issue by tqc** [hashicorp/terraform-provider-aws#26619]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform 1.0.6
Provider 4.29.0

### Affected Resource(s)

data.aws_lambda_function

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "aws_lambda_function" "authorizer" {
  function_name = "auth-service-${var.environment}-${local.function_name}"
}

output "invoke_uri" {
  value = data.aws_lambda_function.authorizer.invoke_arn
}
```

### Expected Behavior

invoke_arn should return a value without the function version as specified in https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-authorizer.html

### Actual Behavior

invoke arn now includes a version number and all apis are failing with "Execution failed due to configuration error: Invalid permissions on Lambda function"

### Steps to Reproduce

1. `terraform apply`

### References

Appears to be caused by #11195 which has the side effect of making FunctionArn always include a version number. Suspect the fix is to update https://github.com/hashicorp/terraform-provider-aws/blob/5688414a8afbe92b7e5b38332a127b01d881d824/internal/service/lambda/function_data_source.go#L299 to explicitly use the unqualified arn

**Comment by officel** [comment]
FYI

We had the same problem too.
Just in case anyone else is affected and looks at this issue.
I'll write about a simple workaround.

```
 resource "aws_api_gateway_authorizer" "this" {
   name                             = local.authorizer_name
   rest_api_id                      = aws_api_gateway_rest_api.this.id
-  authorizer_uri                   = data.aws_lambda_function.authorizer.invoke_arn
+  authorizer_uri                   = replace(data.aws_lambda_function.authorizer.invoke_arn, "/\\:\\d{1,3}\\/invocations/", "/invocations")
```

**Comment by arohter** [comment]
Confirmed.  We've pinned to `4.28.0` for now.

**Comment by arohter** [comment]
For the record, we've successfully pinned to `v4.28.0` to work around this bug, so definitely introduced by #11195

**Comment by nikmash** [comment]
Ran into this issue today. Thanks for the workaround @officel. Hopefully this issue gets prioritized.

**Comment by sherifabdlnaby** [comment]
Was affected by this issue too, use `replace()` to mitigate.
