### ISSUE TITLE
Prefix List ressource won't allow adding an entry and changing the maximum number of entries at the same time

### ISSUE THREAD

**Issue by ingoaf** [hashicorp/terraform-provider-aws#26639]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

windows_amd64
terraform v1.2.7

terraform providers
Providers:
├── provider[[registry.terraform.io/hashicorp/aws](http://registry.terraform.io/hashicorp/aws)] 4.29.0

### Affected Resource(s)

* aws_ec2_managed_prefix_list

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ec2_managed_prefix_list" "my_prefix_list" {
  name           = "my-prefix-list"
  address_family = "IPv4"
  max_entries    = 1

  entry {
    cidr        = "172.217.0.0/32"
    description = "test-block-1"
  }
}
```

### Expected Behavior

The execution of terraform apply + confirmation should have worked.

### Actual Behavior

Received an error: error updating EC2 Managed Prefix List (pl-0625f89a976b5cd): InvalidParameterCombination: You cannot modify the entries and the maximum entries for the prefix list in the same request.

### Steps to Reproduce

1. `terraform apply`, confirm
2. change the terraform configuration to 
```hcl
resource "aws_ec2_managed_prefix_list" "my_prefix_list" {
  name           = "my-prefix-list"
  address_family = "IPv4"
  max_entries    = 2 // increased by one

  entry {
    cidr        = "172.217.0.0/32"
    description = "test-block-1"
  }

  // added this entry
  entry {
    cidr        = "216.58.190.0/32"
    description = "test-block-2"
  }
}
```
3.  `terraform apply`, confirm

**Comment by drewmullen** [comment]
The API will not allow updating max entries and entry changes at the same time. the resource code needs to account for:

- if MaxEntries is increasing, call Modify to increase prior to adding entries
- if MaxEntries is decreasing, call Modify to decrease after removing entries

This means that if MaxEntries and Entries are changing in the same call, terraform will need to make 2 modify calls

**Comment by kevindashton** [comment]
related to #25235

**Comment by kevindashton** [comment]
Seems like this is a bug/defect, as we were blocked from being able to apply a simple addition inline entry due to these EC2 API errors.  A potential work around was to use the `aws_ec2_managed_prefix_list_entry` resources, but that causes rather extreme performance issues and timeouts during `terraform apply` due to EC2 API service throttling caused by managing each prefix list entry independently.
