### ISSUE TITLE
aws_security_group_rule support name

### ISSUE THREAD

**Issue by omerfeldman2** [hashicorp/terraform-provider-aws#26638]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_security_group_rule

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by trevorrea** [comment]
Is description not the attribute you need to set? See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule#description

**Comment by omerfeldman2** [comment]
In addition to description there is possibility to add name to the rule (in the console it’s possible)

**Comment by ericrichtert** [comment]
The name is a tag, and the Aws provider does not support tags in a securitygroup rule (yet).

**Comment by omerfeldman2** [comment]
Is it possible to support tags to this resource?

**Comment by ericrichtert** [comment]
According to https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md: It will be done sone in #20104

**Comment by ewbankkit** [comment]
@omerfeldman2 Thanks for raising this issue.
It has already been noticed in https://github.com/hashicorp/terraform-provider-aws/issues/20104 (the security group rule's name is the value of its `Name` tag). I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
