### ISSUE TITLE
aws_lakeformation_lf_tag throws schema validation error Too many list items, even though soft limit is increased in AWS account.

### ISSUE THREAD

**Issue by bharatbolisetty** [hashicorp/terraform-provider-aws#26633]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Terraform
  - Terraform v0.15.4
  on darwin_amd64

#### AWS Provider
  - hashicorp/aws v4.22.0

### Affected Resource(s)

* aws_lakeformation_lf_tag

### Terraform Configuration Files

```hcl
provider "aws" {
  region  = "us-west-2"
  version = "~> 4.22.0"
}

resource "aws_lakeformation_lf_tag" "lftags" {
  key      = "module"
  values   = ["module1",  "module2",  "module3",  "module4",  "module5",  "module6",  "module7",  "module8",  "module9",  "module10",  "module11",  "module12",  "module13",  "module14",  "module15",  "module16",  "module17"]
}
```

### Debug Output

https://gist.github.com/bharatbolisetty/8fa114f712d48705a4b66718e8c621ad

### Expected Behavior

For aws_lakeformation_lf_tag number of values for a tag is 15 which is soft limit, this can be increased using service quota request.   Should not have max count validation on values attribute of aws_lakeformation_lf_tag resource.

### Actual Behavior

When values attribute have more than 15 elements it throws `Too many list items` error in `terraform validate`. Complete error below

```
Error: Too many list items
│ 
│   with aws_lakeformation_lf_tag.lftags,
│   on main.tf line 24, in resource "aws_lakeformation_lf_tag" "lftags":
│   24:   values   = ["module1",  "module2",  "module3",  "module4",  "module5",  "module6",  "module7",  "module8",  "module9",  "module10",  "module11",  "module12",  "module13",  "module14",  "module15",  "module16",  "module17"]
│ 
│ Attribute supports 15 item maximum, but config has 17 declared.
╵
```

### Steps to Reproduce

1. `terraform init`
2. `terraform validate`

### Important Factoids

We placed service quota increase request on lake formation Number of values per tag and  the soft limit on number of values per tag 15 is increased to 100. 

### References

https://docs.aws.amazon.com/general/latest/gr/lake-formation.html

**Comment by bharatbolisetty** [comment]
Hi @justinretzolk,

I think this PR https://github.com/hashicorp/terraform-provider-aws/pull/26546 fixes this issue, can you please check and do the needful.

**Comment by bbolisetty-gh** [comment]
Hi @justinretzolk,

Can you prioritise reviewing this this PR https://github.com/hashicorp/terraform-provider-aws/pull/26546.

**Comment by justinretzolk** [comment]
Hey @bharatbolisetty and @bbolisetty-gh 👋 Thank you for checking in on this. Unfortunately, I'm not able to provide an estimate on when #26546 will be reviewed/merged due to the potential of shifting priorities (we prioritize work by count of ":+1:" reactions, as well as a few other things). For more information on how we prioritize, check out out [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/).
