### ISSUE TITLE
desiredcapacityType seems to be missing

### ISSUE THREAD

**Issue by hsmade** [hashicorp/terraform-provider-aws#26641]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Multiple resources mention setting the `desiredcapacityType`, but there's no parameter for it anywhere.
I also can't find it in the code of the autoscaling, for example.

### New or Affected Resource(s)

* aws_autoscaling_group
* aws_launch_template

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by hsmade** [comment]
I'm more than happy to do a PR to add this. Just need to know if I'm missing something here ;o)

**Comment by ajayOO8** [comment]
I have submitted a PR(#28658 )suggesting the change for this flag
