### ISSUE TITLE
aws_ecr_repository: add `newest_image_tag` for improving experience with tag immutability 

### ISSUE THREAD

**Issue by francardoso93** [hashicorp/terraform-provider-aws#26658]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`data.aws_ecr_repository.service` could have the tag of the newest pushed image as an attribute. That would grant a dynamic experience when working with **immutable** tags.

See this example that works fine when dealing with **mutable** tags:

```
resource "aws_lambda_function" "lambda_function" {
  package_type  = "Image"
  image_uri  = "${data.aws_ecr_repository.service.repository_url}:${var.image_version}"
  ...
}
```

Now, if I can't set `image_version` to `latest`, how to make sure `terraform apply` will keep up to date with newest image? To keep updating the `image_version` value manually seems like unnecessary work and poor experience.

Tag immutability should be used in production for hardening security, a better experience in doing so could drive that change in many systems.

### New or Affected Resource(s)

`aws_ecr_repository`

### Potential Terraform Configuration

```
resource "aws_lambda_function" "lambda_function" {
  package_type  = "Image"
  image_uri        = "${data.aws_ecr_repository.service.repository_url}:${data.aws_ecr_repository.service.newest_image_tag}"
  ...
}
```

or even better:

```
resource "aws_lambda_function" "lambda_function" {
  package_type  = "Image"
  image_uri        = "${data.aws_ecr_repository.service.newest_image_uri}"
  ...
}
```

### References

https://sysdig.com/blog/toctou-tag-mutability/
https://aquasecurity.github.io/tfsec/v1.15.0/checks/aws/ecr/enforce-immutable-repository/

**Comment by anitakrueger** [comment]
We are running into exactly this issue with a Fargate task definition. The definition is in terraform and originally creates the resource with the latest image tag. A github workflow then updates the task definition when a new image gets deployed. The workflow does move the latest tag as well, but it also creates a specific version on release, which is what I want to set my image in the task definition to. Now running terraform again, overwrites that and I have no way of querying what the latest image is.

**Comment by iRevive** [comment]
I have a similar issue. I use Terraform to provision the resources (ECS, EC2, etc). But deployments are managed by the GitLab pipeline: the script updates the task definition with a new tag.

To prevent Terraform from reverting the tag, I ignore changes in the task_defition:
```terraform
resource "aws_ecs_service" "service" {
  ...
  lifecycle {
    ignore_changes = [task_definition, desired_count]
  }
}
```

This approach works fine until something apart from the image tag needs to be changed in the task definition (e.g. add a new environment variable).
