### ISSUE TITLE
resource/aws_db_instance: `identifier` and `identifier_prefix` should be modifiable

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#26690]
Currently, `identifier` and `identifier_prefix` are marked `ForceNew`. The DB Identifier is modifiable in the AWS Console as well as in the API using the field `NewDBInstanceIdentifier` in `ModifyDBInstanceInput`.

Possibly related to #25634

### Affected Resource

* aws_db_instance

**Comment by ewbankkit** [comment]
Relates: https://github.com/hashicorp/terraform-provider-aws/issues/507.
