### ISSUE TITLE
Cognito user pool settings for verification at attribute updates

### ISSUE THREAD

**Issue by aengelhorn** [hashicorp/terraform-provider-aws#26726]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is a quite fresh option (was published in June 2022) for Cognito user pools: "Keep original attribute value active when an update is pending" (in the AWS Console only visible when selecting the "Sign-up experience" and hitting "Edit"). This is crucial as leaving this unchecked can even lead to security vulnerabilities (see [here for details](https://newsroom.bedefended.com/secure-aws-cognito-configuration)). 

At the moment there is no way to configure this setting via terraform.

This corresponds to the (new) "AttributesRequireVerificationBeforeUpdate" setting in Cognito API, see 
[Cognito API documentation](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UserAttributeUpdateSettingsType.html#CognitoUserPools-Type-UserAttributeUpdateSettingsType-AttributesRequireVerificationBeforeUpdate
)

### New or Affected Resource(s)

* aws_cognito_userpool

### Potential Terraform Configuration

There should be an optional bool setting that enables the "Keep original attribute value active when an update is pending" behaviour if changing of verified attributes like email or phone is enabled.

**Comment by loesak** [comment]
Reviewing the changes in the associated PR, specifically the documentation, I realize my issue was actually with not having a value set for `auto_verified_attributes` set. I wasn't understanding the purpose of that setting correctly. Adding the following configuration to my `aws_cognito_user_pool` resource above, resolved my specific issue.

```
auto_verified_attributes = ["email"] 
```
