### ISSUE TITLE
Documentation: `client_secret` not documented as part of attributes of `aws_cognito_user_pool_client`

### ISSUE THREAD

**Issue by ScottFinlaysonGMSL** [hashicorp/terraform-provider-aws#26728]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_cognito_user_pool_client

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

`client_secret` should be listed as an available attribute via
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/cognito_user_pool_client

terraform correctly returns this value so it's already supported within code but just not documented.

### Actual Behavior

terraform correctly retrieves the `client_secret` and makes the value available for consuming services (using aws provider v4.27.0)

### References

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/cognito_user_pool_client

**Comment by justinretzolk** [comment]
Hey @ScottFinlaysonGMSL 👋 Thank you for taking the time to raise this! I've opened a PR to add the `client_secret` attribute to the documentation.
