### ISSUE TITLE
VPC Flow Logs can now be delivered to Amazon Kinesis Firehose

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#26730]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> You can now deliver Amazon Virtual Private Cloud (VPC) Flow Logs directly to Amazon Kinesis Firehose, allowing you to stream your flow logs real-time to [destinations supported by Amazon Kinesis Firehose](https://docs.aws.amazon.com/firehose/latest/dev/create-destination.html) or [downstream logging solutions](https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-amazon-vpc-flow-logs-kinesis-data-firehose/) via custom HTTP endpoints.

### New or Affected Resource(s)

* [`aws_flow_log`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/flow_log)

### Potential Terraform Configuration

```hcl
resource "aws_flow_log" "example" {
  log_destination_type = "kinesis-data-firehose"

  deliver_cross_account_role = "..."
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2022/09/amazon-vpc-flow-logs-delivered-amazon-kinesis-firehose/).
[Blog post](https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-amazon-vpc-flow-logs-kinesis-data-firehose/).

Requires [AWS SDK for Go v1.44.94](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.94): https://github.com/hashicorp/terraform-provider-aws/pull/26720.

**Comment by sasidhar-aws** [comment]
I am looking into this.
