### ISSUE TITLE
Significant memory usage at init with 4.29.0 provider

### ISSUE THREAD

**Issue by gavinelder** [hashicorp/terraform-provider-aws#26742]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When carrying out a terraform plan we see an increase in the number of terraform-aws-providers in line with number of the providers within the terraform manifest before the plan begins, after the plan begins we see a reduction of provider processes in line with the parallelism value , for example if we have `parallelism=1` we would expect to see one provider process running at a time, however with our current configuration we see roughly 400 provider processes spawn causing the system to OOM, on a system with sufficient memory to run the plan we see these processes spawn at the start of the plan fully close down then the plan begins, we're seeing our average memory usage for a terraform run go from 2Gb to 100Gb at init and 2Gb during the plan.  

Please provide guidance on any debug output you may require in this regard , I have a horrible feeling it may be related to the following changes https://github.com/hashicorp/aws-sdk-go-base/pull/128 & https://github.com/hashicorp/terraform-provider-aws/pull/26590 where the validation stage of the provider profiles is done without respect of the plan parallelism resulting in lots of concurrent loading of the providers into memory. 

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.2.8
Terraform-provider-aws 4.29.0

### Affected Resource(s)

* aws_XXXXX

### Debug Output

Debug output from 4.28.0 & 4.29.0

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by Roxyrob** [comment]
I faced this issue too. Documented in #29631. I close my issue to help this one solution path

**Comment by antonylucisano** [comment]
+1

**Comment by rjinski** [comment]
Related to: https://github.com/hashicorp/terraform-provider-aws/issues/31722
