### ISSUE TITLE
New Datasources: aws_identitystore_users & aws_identitystore_groups (plural)

### ISSUE THREAD

**Issue by awoimbee** [hashicorp/terraform-provider-aws#26770]
Fixes https://github.com/hashicorp/terraform-provider-aws/issues/17279

> I'd appreciate both singular and plural data sources (e.g. `aws_identitystore_group` and `aws_identitystore_groups`), [...].

_Originally posted by @lorengordon in https://github.com/hashicorp/terraform-provider-aws/issues/17279#issuecomment-1030210907_

`aws_identitystore_group` & `aws_identitystore_user` were made to fetch a single user or group. It would be nice to have the same resources but plural. These would return a list (with 0, 1 or many elements).

Current workaround:
```hcl
locals {
  aws_sso_users = {
    # aws identitystore list-users --identity-store-id d-xxxxxxxxxx --query 'Users[].[UserName,UserId]' --output text | awk '{print "\""$1"\" = \""$2"\","}'
    "toto@example.com"           = "1234567891-90825474-0913-xxxx-wwww-abdc5783ff98",
    "jojo@example.com"           = "1234567891-42349857-7836-yyyy-zzzz-192837465302",
    # ...
  }
}
```

Proposed solution:
```hcl
data "aws_identitystore_users" "every_user" {
  identity_store_id = tolist(data.aws_ssoadmin_instances.example.identity_store_ids)[0]
}
```

**Comment by JanKoppe** [comment]
AWS has recently released new functionality for the Identity Store API, solving many painpoints. This, and much more should now be possible, previously it just was not.

https://aws.amazon.com/blogs/security/announcing-new-aws-iam-identity-center-apis-to-manage-users-and-groups-at-scale/
