### ISSUE TITLE
Cost Category rules out of order 

### ISSUE THREAD

**Issue by apeduru-patreon** [hashicorp/terraform-provider-aws#26774]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform provider version 4.29

### Affected Resource(s)

* aws_ce_cost_category

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

I've redacted some of the `values` as those are company sensitive. Apart from that, this is the terraform configuration that is being used.

```hcl
resource "aws_ce_cost_category" "cost_center" {
  name         = "Cost Center"
  rule_version = "CostCategoryExpression.v1"

  default_value = "uncategorized"

  rule {
    type  = "REGULAR"
    value = "prod-roles"
    rule {
      and {
        dimension {
          key           = "LINKED_ACCOUNT"
          values        = [local.production]
          match_options = ["EQUALS"]
        }
      }
      and {
        tags {
          key = "role"
          values = ["..."]
          match_options = ["EQUALS"]
        }
      }
    }
  }

  rule {
    type  = "REGULAR"
    value = "rnd-roles"
    rule {
      and {
        dimension {
          key           = "LINKED_ACCOUNT"
          values        = [local.development]
          match_options = ["EQUALS"]
        }
      }
      and {
        tags {
          key = "role"
          values = ["..." ]
          match_options = ["EQUALS"]
        }
      }
    }
  }

  rule {
    type  = "REGULAR"
    value = "rnd-accounts"
    rule {
      dimension {
        key = "LINKED_ACCOUNT"
        values = ["..." ]
        match_options = ["EQUALS"]
      }
    }
  }

  rule {
    type  = "REGULAR"
    value = "prod-env"
    rule {
      tags {
        key = "environment"
        values = [
          "production",
          "prod",
        ]
        match_options = ["EQUALS"]
      }
    }
  }

  rule {
    type  = "REGULAR"
    value = "rnd-env"
    rule {
      tags {
        key = "environment"
        values = [
          "development",
          "dev",
          "staging",
        ]
        match_options = ["EQUALS"]
      }
    }
  }

}

```

### Expected Behavior

When I define these rules in Terraform, I'm expecting the rules that are defined in order in Terraform to also show up in the same order in the cost category rules editor. 
i.e.
```
1. prod-roles
2. rnd-roles
3. rnd-accounts
4. prod-env
5. rnd-env
```

### Actual Behavior

When the Terraform is applied and the rules are processed in AWS, I'm seeing these rules are out of order. It looks like this in the rules editor

```
1. prod-roles
2. prod-env
3. rnd-roles
4. rnd-accounts
5. rnd-env
```
### Steps to Reproduce

1. `terraform apply`

**Comment by throwaway8787** [comment]
@justinretzolk this is not an enahncement, but is indeed a bug, this ticket should be labeled as such. The functionality of billing categories breaks if rules are out of defined order. This comes into play heavily when using matches of contains, starts with, and ends with.

**Comment by jnancel** [comment]
Hello guys,

This issue is actually critical for us because we need that feature in order to be able to properly allocate cloud costs to users.

Thanks

**Comment by bradwood** [comment]
I'm also having exactly the same issue right now. While the workaround that @jnancel mentioned looks cool, I'd rather have a clean solution to this.

Any updates on when we can get a fix for this?

**Comment by kohlmanj** [comment]
I tried the solution @jnancel referred to and it did not work in my case. Specifically, I am using dynamic blocks like this
`resource "aws_ce_cost_category" "MyUberCoolCostCategory" {
  name            = "MyUberCoolCostCategory"
  rule_version    = "CostCategoryExpression.v1"
  effective_start = local.effective_start_date

  dynamic "rule" {
    for_each = local.ordered_rules #The key uses the trick for getting keys like "000", "001", "002", "003" { for key,rule in var.listOfRule : format("%.4d",key) => rule }
    content {

      value = rule.value.label #this is the name of the rule "000_rule name 1, etc" I was hoping maybe if the rule names were in alphabetical order it would help but nothing.
      type = "REGULAR"


      rule {
        dynamic "and" {
          for_each = rule.value.combined_rules #this allows the code to create this account_link with "and" ONLY when the rule has other dimensions
          content{
            dimension {
                key = "LINKED_ACCOUNT"
                values = [local.account_map[rule.value.account_code]]
                match_options = [
                  "EQUALS"]
              }
          }
        }

        dynamic "and" {
          for_each = rule.value.services #this allows the code to only create this dimension when services is populated
          content{
              dimension {
                key = "SERVICE_CODE"
                values = rule.value.services
                match_options = [
                  "EQUALS"]
              }
          }
        }
        dynamic "and" {
          for_each = rule.value.tags #this allows the code to only create this dimension when tags is populated
          content{
              tags {
                key = "tags"
                values = rule.value.tags
                match_options = [
                  "EQUALS"]
              }
          }
        }

        dynamic "dimension" {
          for_each = rule.value.account_only #this allows the code to create this account_link WITHOUT "and" when there are NO other dimensions for the rule
          content{
                key = "LINKED_ACCOUNT"
                values = [local.account_map[rule.value.account_code]]
                match_options = [
                   "EQUALS"] 
          }
        }
      }
    }
  }`

The order of the rules seemingly has no order whatsoever. The order of the dimensions for each given rule is also all over the place. Furthermore, terraform plan, actually shows the order of the dimension for each rule in a consistent fashion account -> service -> tag. AND the order of the rules is alphabetical using those three fields. This would be workable for our purposes as it creates all of one account then all of the next account. With in an account if a service and tag is specified, we get all the service->tag combinations first (alpha by tag name), then the rule with just account and service. This would be workable . . . such a disappointment when terraform apply then creates the rules is a seemingly completely haphazard way. The rules don't seem to follow any discernable order. Even the order of the dimensions, for any given rule, are in different order!!

**Comment by bnightstar** [comment]
Hey all any plans for this to be solved anytime soon ? We are also needing this functionality but so fat Terraform creates this out of order. Any plans for someone to solve this.
