### ISSUE TITLE
AppFlow missing support for custom connectors

### ISSUE THREAD

**Issue by daniepett** [hashicorp/terraform-provider-aws#26780]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.30.0
```

### Affected Resource(s)

* aws_appflow_connector_profile

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_appflow_connector_profile" "test" {
  name            = "salesforce_marketing_cloud"
  connector_type  = "CustomConnector"
  connection_mode = "Public"
  connector_label = "SalesforceMarketingCloud"
  connector_profile_config {
    connector_profile_credentials {
      custom_connector {
        authentication_type = "OAUTH2"
        oauth2 {
          client_id     = "testID"
          client_secret = "testSecret"
          oauth_request {
            redirect_uri = "https://test1234.rest.marketingcloudapis.com/"
          }
        }
      }
    }
    connector_profile_properties {
      custom_connector {
        oauth2_properties {
          oauth2_grant_type = "CLIENT_CREDENTIALS"
          token_url         = "https://test1234.auth.marketingcloudapis.com/v2/token"
        }
        profile_properties = {
          "instanceUrl" = "https://test1234.rest.marketingcloudapis.com/"
        }
      }
    }
  }
}

```

### Expected Behavior

Resource created according to documentation

### Actual Behavior

Error: creating AppFlow Connector Profile: ValidationException: connectorProfileConfig: properties/credentials is null for ConnectorType: CUSTOMCONNECTOR

Debug JSON

```json
{
    "connectionMode": "Public",
    "connectorLabel": "SalesforceMarketingCloud",
    "connectorProfileConfig": {
        "connectorProfileCredentials": {
            "CustomConnector": {
                "authenticationType": "OAUTH2"
            }
        },
        "connectorProfileProperties": {}
    },
    "connectorProfileName": "salesforce_marketing_cloud",
    "connectorType": "CustomConnector"
}

```

### Steps to Reproduce

1. `terraform apply`

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appflow_connector_profile#custom-connector-profile-credentials

* #26665 
* #26766

**Comment by dude0001** [comment]
It looks like a rather small change #26766 is needed for this and ready to go. @daniepett @justinretzolk what else is needed to get this on a release?
