### ISSUE TITLE
resource/aws_spot_fleet_request: Add `instance_interruption_behavior` and deprecate `instance_interruption_behaviour` 

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#26794]
The resource `aws_spot_fleet_request` defines the parameter `instance_interruption_behaviour` which does not match with the AWS API parameter `InstanceInterruptionBehavior`. Add correct spelling `instance_interruption_behavior` and deprecate `instance_interruption_behaviour` .

### Affected Resource

* aws_spot_fleet_request

**Comment by ewbankkit** [comment]
**N.B.** This attribute was _NOT_ deprecated in `v4.0.0` of the Terraform AWS Provider. It will be deprecated in `v5.0.0`.

**Comment by ewbankkit** [comment]
Not worth doing due to https://github.com/hashicorp/terraform-provider-aws/issues/30975.
