### ISSUE TITLE
SESv2 Plan

### ISSUE THREAD

**Issue by kamilturek** [hashicorp/terraform-provider-aws#26796]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

# SESv2

This issue contains a plan for SESv2 service implementation. It includes a list of planned resources along with proposed sample schemas. Any feedback is very appreciated.

Not all SESv2 API actions are covered. Attention was primarily paid to main SESv2 resources and the most up-voted SES(v2)-related issues. Although, the remaining SESv2 resources might be also implemented in the future.

This issue also aims to track the progress of SESv2 service implementation.

## Table of Contents

- [Resource List](#resource-list)
    - <s>[aws_sesv2_configuration_set](#awssesv2configurationset)</s>
    - <s>[aws_sesv2_configuration_set_event_destination](#awssesv2configurationseteventdestination)</s>
    - <s>[aws_sesv2_dedicated_ip_pool](#awssesv2dedicatedippool)</s>
    - <s>[aws_sesv2_dedicated_ip_assignment](#awssesv2dedicatedipassignment)</s>
    - <s>[aws_sesv2_contact_list](#awssesv2contactlist)</s>
    - [aws_sesv2_contact](#awssesv2contact)
    - [aws_sesv2_custom_verification_email_template](#awssesv2customverificationemailtemplate)
    - [aws_sesv2_deliverability_test_report](#awssesv2deliverabilitytestreport)
    - <s>[aws_sesv2_email_identity](#awssesv2emailidentity)</s>
    - [aws_sesv2_email_identity_policy](#awssesv2emailidentitypolicy)
    - <s>aws_sesv2_email_identity_feedback_attributes</s>
    - <s>aws_sesv2_email_identity_mail_from_attributes</s>
    - [aws_sesv2_email_template](#awssesv2emailtemplate)
    - [aws_sesv2_import_job](#awssesv2importjob)
    - [aws_sesv2_suppressed_destination](#awssesv2suppresseddestination)
    - [aws_sesv2_account](#awssesv2account)
- [Related](#related) 

## Resource List

This section lists all service resources with proposed schemas and relevant AWS
API actions. Corresponding data sources (singular and plural) are skipped in the
list but also should be implemented.

<details>
<summary>Click here to expand</summary>

#### Schema

```terraform
resource "aws_sesv2_configuration_set" "example" {
    configuration_set_name = "example"

    delivery_options {
        sending_pool_name = aws_sesv2_dedicated_ip_pool.example.pool_name
        tls_policy        = "REQUIRE"
    }

    reputation_options {
        last_fresh_start           = "timestamp"
        reputation_metrics_enabled = true
    }

    sending_options {
        sending_enabled = true
    }

    suppression_options {
        suppressed_reasons = ["BOUNCE", "COMPLIANT"]
    }

    tracking_options {
        custom_redirect_domain = "example.com"
    }
}
```

#### API Actions

- [CreateConfigurationSet](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_CreateConfigurationSet.html)
- [DeleteConfigurationSet](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_DeleteConfigurationSet.html)
- [GetConfigurationSet](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetConfigurationSet.html)
- [ListConfigurationSets](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_ListConfigurationSets.html)
- [PutConfigurationSetDeliveryOptions](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_PutConfigurationSetDeliveryOptions.html)
- [PutConfigurationSetReputationOptions](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_PutConfigurationSetReputationOptions.html)
- [PutConfigurationSetSendingOptions](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_PutConfigurationSetSendingOptions.html)
- [PutConfigurationSetSuppressionOptions](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_PutConfigurationSetSuppressionOptions.html)
- [PutConfigurationSetTrackingOptions](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_PutConfigurationSetTrackingOptions.html)

#### Schema

```terraform
resource "aws_sesv2_configuration_set_event_destination" "example" {
    configuration_set_name = aws_sesv2_configuration_set.example.name
    event_destination_name = "example"

    event_destination {
        enabled = true
        
        matching_event_types = ["BOUNCE", "COMPLIANT"]
        
        cloud_watch_service_destination {
             dimension_configuration {
                 default_dimension_value = "example"
                 dimension_name          = "example"
                 dimension_value_source  = "MESSAGE_TAG"
             }
        }
    
        kinesis_firehose_destination {
            delivery_stream_arn = "arn"
            iam_role_arn        = "arn"
        }
        
        pinpoint_destination {
            application_arn = "arn"
        }

        sns_destination {
            topic_arn = "arn"
        }
    }
}
```
#### API Actions
- [CreateConfigurationSetEventDestination](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_CreateConfigurationSetEventDestination.html)
- [DeleteConfigurationSetEventDestination](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_DeleteConfigurationSetEventDestination.html)
- [GetConfigurationSetEventDestinations](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetConfigurationSetEventDestinations.html)
- [UpdateConfigurationSetEventDestination](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_UpdateConfigurationSetEventDestination.html)

#### Schema

```terraform
resource "aws_sesv2_dedicated_ip_pool" "example" {
    pool_name = "example"
}
```

#### API Actions

- [CreateDedicatedIpPool](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_CreateDedicatedIpPool.html)
- [DeleteDedicatedIpPool](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_DeleteDedicatedIpPool.html)
- [ListDedicatedIpPools](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_ListDedicatedIpPools.html)

#### Schema

```terraform
resource "aws_sesv2_dedicated_ip_assignment" "example" {
    ip = "ip"
    destination_pool_name = aws_sesv2_dedicated_ip_pool.example.pool_name
}
```

#### API Actions
- [PutDedicatedIpInPool](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_PutDedicatedIpInPool.html)
- [GetDedicatedIp](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetDedicatedIp.html)
- [GetDedicatedIps](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetDedicatedIps.html)

#### Schema

```terraform
resource "aws_sesv2_contact_list" "example" {
    contact_list_name = "example"
    description       = "description"

    topic {
        default_subscription_status = "OPT_OUT"
        description                 = "description"
        display_name                = "example"
        topic_name                  = "exmaple"
    }
}
```

#### API Actions

- [CreateContactList](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_CreateContactList.html)
- [DeleteContactList](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_DeleteContactList.html)
- [GetContactList](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetContactList.html)
- [ListContactLists](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_ListContactLists.html)
- [UpdateContactList](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_UpdateContactList.html)

#### Schema

```terraform
resource "aws_sesv2_contact" "example" {
    contact_list_name = aws_sesv2_contact_list.example.contact_list_name
    attributes_data   = "example"
    email_address     = "example@example.com"
    unsubscribe_all   = false

    topic_preference {
        subscription_status = "OPT_IN"
        topic_name		    = "exmaple"
    }
}
```

#### API Actions

- [CreateContact](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_CreateContact.html)
- [DeleteContact](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_DeleteContact.html)
- [GetContact](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetContact.html)
- [ListContacts](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_ListContacts.html)
- [UpdateContact](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_UpdateContact.html)

### aws_sesv2_custom_verification_email_template

To use this feature, your Amazon SES account has to be out of the sandbox.

#### Schema

```terraform
resource "aws_sesv2_custom_verification_email_template" "example" {
    from_email_address = "example@example.com"

    failure_redirection_url = "url"
    success_redirection_url = "url"

    template_content = "content"
    template_name    = "name"
    template_subject = "subject"
}
```

#### API Actions

- [CreateCustomVerificationEmailTemplate](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_CreateCustomVerificationEmailTemplate.html)
- [DeleteCustomVerificationEmailTemplate](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_DeleteCustomVerificationEmailTemplate.html)
- [GetCustomVerificationEmailTemplate](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetCustomVerificationEmailTemplate.html)
- [ListCustomVerificationEmailTemplates](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_ListCustomVerificationEmailTemplates.html)
- [UpdateCustomVerificationEmailTemplate](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_UpdateCustomVerificationEmailTemplate.html)

### aws_sesv2_deliverability_test_report

The test is available after 24 hours. It is unclear how the provider plugin should behave in this case.

#### Schema

TBC

#### API Actions

- [CreateDeliverabilityTestReport](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_CreateDeliverabilityTestReport.html)
- [GetDeliverabilityTestReport](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetDeliverabilityTestReport.html)
- [ListDeliverabilityTestReports](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_ListDeliverabilityTestReports.html)

#### Schema

```terraform
resource "aws_sesv2_email_identity" "example" {
    configuration_set_name = aws_sesv2_configuration_set.example.configuration_set_name

    dkim_signing_attributes {
        domain_signing_private_key = "a"
        domain_signing_selector	   = "b"

        # next_signing_key_length = "RSA_1024_BIT"
    }

    email_identity = "example@example.com"
}
```

#### API Actions

- [CreateEmailIdentity](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_CreateEmailIdentity.html)
- [DeleteEmailIdentity](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_DeleteEmailIdentity.html)
- [GetEmailIdentity](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetEmailIdentity.html)
- [ListEmailIdentities](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_ListEmailIdentities.html)
- [PutEmailIdentityConfigurationSetAttributes](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_PutEmailIdentityConfigurationSetAttributes.html)
- [PutEmailIdentityDkimAttributes](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_PutEmailIdentityDkimAttributes.html)
- [PutEmailIdentityDkimSigningAttributes](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_PutEmailIdentityDkimSigningAttributes.html)

#### Schema

```terraform
resource "aws_sesv2_email_identity_policy" "example" {
    email_identity = aws_sesv2_email_identity.example.email_identity
    policy_name    = "name"

    policy = <<EOT
{
  "Id":"ExampleAuthorizationPolicy",
  "Version":"2012-10-17",
  "Statement":[
    {
      "Sid":"AuthorizeAccount",
      "Effect":"Allow",
      "Resource":"arn:aws:ses:us-east-1:123456789012:identity/example.com",
      "Principal":{
        "AWS":[
          "123456789012"
        ]
      },
      "Action":[
        "ses:SendEmail",
        "ses:SendTemplatedEmail",
        "ses:SendRawEmail",
        "ses:SendBulkTemplatedEmail"
      ]
    }
  ]
}
EOT
}
```

#### API Actions

- [CreateEmailIdentityPolicy](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_CreateEmailIdentityPolicy.html)
- [DeleteEmailIdentityPolicy](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_DeleteEmailIdentityPolicy.html)
- [GetEmailIdentityPolicies](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetEmailIdentityPolicies.html)
- [UpdateEmailIdentityPolicy](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_UpdateEmailIdentityPolicy.html)

#### Schema

```terraform
resource "aws_sesv2_email_template" "example" {
    template_name = "example"

    template_content {
        html    = "html"
        text    = "text"
        subject = "subject"
    }
}
```

#### API Actions

- [CreateEmailTemplate](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_CreateEmailTemplate.html)
- [DeleteEmailTemplate](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_DeleteEmailTemplate.html)
- [GetEmailTemplate](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetEmailTemplate.html)
- [ListEmailTemplates](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_ListEmailTemplates.html)
- [UpdateEmailTemplate](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_UpdateEmailTemplate.html)

#### Schema

```terraform
resource "aws_sesv2_import_job" "example" {
    import_data_source {
        data_format = "CSV"
        s3_url      = "s3://url"
    }

    import_destination {
        contact_list_destination {
            contact_list_import_action = "PUT"
            contact_list_name = aws_sesv2_contact_list.example.contact_list_name
        }

        suppression_list_destination {
            suppression_list_import_action = "DELETE"
        }
    }
}
```

#### API Actions

- [CreateImportJob](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_CreateImportJob.html)
- [GetImportJob](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetImportJob.html)
- [ListImportJobs](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_ListImportJobs.html)

#### Schema

```terraform
resource "aws_sesv2_suppressed_destination" "example" {
    email_address = "example@example.com"
    reason 	      = "reason"
}
```

#### API Actions

- [DeleteSuppressedDestination](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_DeleteSuppressedDestination.html)
- [GetSuppressedDestination](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetSuppressedDestination.html)
- [ListSuppressedDestinations](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_ListSuppressedDestinations.html)
- [PutSuppressedDestination](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_PutSuppressedDestination.html)

### aws_sesv2_account

This is only a data source.

#### Schema

```terraform
data "aws_sesv2_account" "example" {}
```

#### API Actions

- [GetAccount](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetAccount.html)

</details>

## Related
https://github.com/hashicorp/terraform-provider-aws/issues/14320
https://github.com/hashicorp/terraform-provider-aws/issues/10703
https://github.com/hashicorp/terraform-provider-aws/issues/17570
https://github.com/hashicorp/terraform-provider-aws/issues/21129

**Comment by JoshiiSinfield** [comment]
Can I ask why you're planning new schemas / resource names? 

There's not a SESv2 service, or any other difference within the console or resources within AWS. It's purely an SDK / API thing.

No one using Terraform will choose between a v1 or v2 resouces. It's just "ses resources".

Also, shameless plug  but I've done the ground work & email identity work in here:

https://github.com/hashicorp/terraform-provider-aws/pull/26604

**Comment by jar-b** [comment]
How would you feel about converting `aws_sesv2_dedicated_ip` to a data source and renaming the proposed resource to indicate assignment to a pool (`aws_sesv2_dedicated_ip_assignment`)? The justification being the IP itself must be created via an AWS support case (both [when AWS provides it](https://docs.aws.amazon.com/ses/latest/dg/dedicated-ip-case.html), or [bringing your own](https://docs.aws.amazon.com/ses/latest/dg/dedicated-ip-byo.html)), and the `_assignment` suffix describes the action of assigning the IP to a pool versus "creating" it.

**Comment by kamilturek** [comment]
@jar-b That makes sense. Sounds good to me! 👍

**Comment by JoshiiSinfield** [comment]
@kamilturek @jar-b  FYI https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-ses-model-provisioning-managing-dedicated-ips/
Probably changes things.

**Comment by JoshiiSinfield** [comment]
@kamilturek  judging by your 27260 shall I close mine then ?

**Comment by jar-b** [comment]
Thanks for the link @JoshiiSinfield! 

Sounds like this will require a new [`scaling_mode` attribute](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_CreateDedicatedIpPool.html) on the `aws_sesv2_dedicated_ip_pool` resource to allow creation of managed pools. I believe the proposed `aws_sesv2_dedicated_ip_assignment` resource can remain because IP assignment will still be necessary for standard (non-managed) pools.

**Comment by F21** [comment]
Would definitely love to see `aws_sesv2_email_identity_mail_from_attributes` implemented. It's a separate endpoint in Amazon's SESv2 API, but would it make sense to put it as an attribute under `aws_sesv2_email_identity`?

**Comment by kamilturek** [comment]
Hey @F21, thanks for your view on this! 🙌 

As you mentioned, `CreateEmailIdentity` API action does not support specifying Mail From attributes but it can be done through a separate endpoint. I'd say we should avoid mixing the [`PutEmailIdentityMailFromAttributes`](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_PutEmailIdentityMailFromAttributes.html) into `aws_sesv2_email_identity` CRUD cycle as it increases its complexity and drifts it away from the AWS API design. If we keep adding more and more attributes to `aws_sesv2_email_identity` that are managed by different API actions, it can become really bloated, error-prone, and hard to maintain.

There is a general tendency of splitting out PUT APIs into their own resources in cases like that. `aws_s3_bucket_*` resources are a great example of this.

**Comment by F21** [comment]
I have been testing out the `aws_sesv2_configuration_set` resource, and I think `suppressed_reasons` in `suppression_options` should have it's `MinItems` set to `0` rather than `1`: https://github.com/kamilturek/terraform-provider-aws/blob/753ff2aacae8a69f897b64564211b728ad2c3d8c/internal/service/sesv2/configuration_set.go#L109

By setting it to `0`, we can use the following:
```hcl
resource "aws_sesv2_configuration_set" "my_config_set" {
  configuration_set_name = "my-config-set"
  suppression_options {
    suppressed_reasons = []
  }
}
```
This will allow for the case where we want to override the account-level suppression option and disable the suppression list for this configuration set.

**Comment by EderNorivalSouza** [comment]
Hi, trying use resource -> "aws_sesv2_contact_list" but received the error.
Error: Invalid resource type
│ 
│   on ../../modules/contact-list/main.tf line 6, in resource "aws_sesv2_contact_list" "contact-list":
│    6: resource "aws_sesv2_contact_list" "contact-list" {
│ 
│ The provider hashicorp/aws does not support resource type "aws_sesv2_contact_list".

version
Terraform v1.3.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.5.0

Maybe this is a ISSUE? Or already being implented?
Thanks

**Comment by jar-b** [comment]
Hi @EderNorivalSouza - `aws_sesv2_contact_list` has not been implemented yet. This issue is tracking the plan for proposed `sesv2` resources, but only those with a strikethrough in the Table of Contents have been completed to this point.

**Comment by gmx-git** [comment]
Hi, I'm trying to configure a sesv2 based verified domain identity.

How can we configure notifications (Bounce, Complaint, Delivery) using SESv2 resources?
I haven't been able to figure it out using [aws_sesv2_email_identity](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_email_identity).

Or, is there a different resource that should be used instead?

Thank you!

**Comment by kamilturek** [comment]
Hey @gmx-git, maybe [`aws_sesv2_configuration_set_event_destination`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_configuration_set_event_destination) is what you're looking for.

**Comment by Scifire** [comment]
@kamilturek I guess I´m missing the same setting as @gmx-git.
The configuration sets are something different than the feedback notifications.

The feedback notifications are configured in each verified identity under notifications 
![image](https://user-images.githubusercontent.com/17220258/221898053-279d06fc-77b8-4c44-9f59-f187f9029377.png)
For this I couldn´t find any TF setting.

The configuration sets are an own topic and could be configured as you linked.

**Comment by kamilturek** [comment]
Hey @Scifire. Thank you, I haven't seen that.

Looking at [this guide](https://docs.aws.amazon.com/ses/latest/dg/configure-sns-notifications.html#configure-feedback-notifications-api), I think it is available only for API v1. I can't find its equivalent in the API v2 specification. I believe it can be achieved by using the configuration set event destination and configuration set assigned to the email identity.

**Comment by gmx-git** [comment]
Hey guys,

I've done some research on my own on this topic as well. The APIv1 indeed contained the SetIdentityNotificationTopic[https://docs.aws.amazon.com/ses/latest/APIReference/API_SetIdentityNotificationTopic.html](url), while there's no correspondence in the APIv2.

I've noted a hint while creating a SES identity (see screenshot below). To me it looks like AWS wants to fade out the notifications at the identity level and recommends shifting to notifications on the configuration set level. We can create/set a default configuration set for an SES identity. The default config set will be used by default when sending emails using the SES identity. We don't need to specify it, but the sender should have the rights to use both the SES identity and the default configuration set assigned to it.

![image](https://user-images.githubusercontent.com/22165229/221982472-0e677355-77bb-4f33-ac42-5c0e6f090390.png)

On my side I'll review my current design and shift the notifications to the default configuration sets.

Hope this helps!

**Comment by Manouchehri** [comment]
This is a bit off-topic, but not sure where else to write this note/warning...

Be very careful when migrating from a SESv1 domain identity to SESv2. Destroying the identity doesn't actually instantly cause it to be removed; it seems to stick around, and blocks you from creating a new identity with the exact same domain name. I managed to work around it by manually messing with the state, but it wasn't something I'd recommend repeating.

I don't think Terraform can address this edge case, since it's straight up the AWS API response that's returning confusing information. (i.e. it can sometimes return a 200 when creating a new identity, and then fail right after when you try go get that identity..)

**Comment by mattbnz** [comment]
Is there any reason why the ability to request sandbox removal / production migration from Terraform doesn't seem to be mentioned in any of the plans above?

Currently I find this to be a very tedious and manual addition to our otherwise nicely declarative process for turning up in a new region.

Specifically I'm looking for a resource that matches the https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_PutAccountDetails.html API call.

**Comment by jar-b** [comment]
Hey @mattbnz 👋 - Seems reasonable to me. If you could open a [New Resource issue](https://github.com/hashicorp/terraform-provider-aws/issues/new?assignees=&labels=needs-triage&projects=&template=03_new_resource.yml&title=%5BNew%5D%3A+) and link back to this one I can add it to the Meta-issue list. 

Also, to set expectations, implementation of these resources has largely been community driven thus far as this issue is not currently on the maintainer roadmap.

**Comment by kamilturek** [comment]
As core SESv2 resources have been already implemented and it's becoming quite difficult to follow and manage the work through a single GitHub issue, I suggest closing this one and opening new fine-grained issues for remaining resources as needed.

I'll keep it open for a few more days in case there are any objections.

**Comment by jeremyatenovis** [comment]
Is `aws_sesv2_domain_identity` implemented? I can't seem to find it. Additionally, I'd very much like a way to associate a default configuration set to an SES identity.

**Comment by kamilturek** [comment]
Hey @jeremyatenovis, the `aws_sesv2_email_identity` resource allows you to manage both email address identities and domain identities. Also, there is a way to associate a default configuration set to it.

Please have a look at the documentation page. Let me know if you have any questions.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_email_identity

**Comment by shamx9ir** [comment]
We are currently using `aws_ses_domain_identity` and would like to use `aws_sesv2_email_identity` to be able to assign default configuration set. How do we approach this without accidentally dropping the existing domain identity? Do we have a guide somewhere?

**Comment by raffraffraff** [comment]
Since there isn't a resource `aws_sesv2_email_identity_policy` yet, I assume there's no way to create an SESv2 policy that can [allow a Cognito pool to send email via SESv2](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-settings-ses-authorization-to-send-email.html). The AWS cli has `create-email-identity-policy`, so I suppose I could do some nasty `null-resource` that calls a script (like I had to do with OpenSearch endpoint authorization). I really don't want to have to do that again, because I'm now looking at having to redo my OpenSearch stuff now that it's finally supported in the provider.

**Comment by kamilturek** [comment]
@raffraffraff I opened a PR with `aws_sesv2_email_identity_policy` resource. I should be able to finalize it soon.
https://github.com/hashicorp/terraform-provider-aws/pull/35486

**Comment by pspot2** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/22655

**Comment by Scifire** [comment]
@nightpool I´d recommend use SESv2. For normal setups everything should work there. I´ve started with SES but reworked it on v2 shortly later cause there are more recent features available.

**Comment by kamilturek** [comment]
Answering a few comments - it was a concious decision to keep SESv1 and SESv2 as separate services preceded by discussions and agreements. The same thing was done for `apigatewayv2`, `elbv2` etc. The goal is to keep the provider resources aligned with how AWS structures their APIs, SDKs and the CLI.

As announced a few months agowith core SESv2 resources already implemented, I am closing this issue and encourage to open new fine-grained issues for remaining resources as needed.
