### ISSUE TITLE
aws_eks_addon tolerations

### ISSUE THREAD

**Issue by ndegory** [hashicorp/terraform-provider-aws#26811]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Use case: coredns managed with the cluster_addons block of the eks module, on a cluster where all nodegroups have taints.

This currently results in the `coredns` pod in pending state, because they don't tolerate the taints of my infra nodes.

### New or Affected Resource(s)

* aws_eks_addon

### Potential Terraform Configuration

eks module:

```hcl
  cluster_addons = {
    coredns = {
      resolve_conflicts = "OVERWRITE"
      tolerations_keys  = "node.kubernetes.io/infra"
    }
  }
```

aws_eks_addon resource:

```hcl
resource "aws_eks_addon" "example" {
  cluster_name    = aws_eks_cluster.example.name
  addon_name      = "coredns"
  toleration_keys = "node.kubernetes.io/infra"
}
```

**Comment by mattburgess** [comment]
Hi @ndegory. It doesn't look like the EKS API supports passing in custom tolerations to addons just yet. I got bitten by this myself a while ago with the EBS CSI driver addon. For that _specific_ case, the request to enable custom tolerations was made under https://github.com/aws/containers-roadmap/issues/1706. https://github.com/aws/containers-roadmap/issues/1706#issuecomment-1227622306 is of particular interest for your more general case which suggests that improvements to the EKS API will be made at some point to enable tolerations to be passed in. Until that time, though, there's not much we can do on the TF provider side.

**Comment by parjun8840** [comment]
I also got bitten by the CSI driver and CoreDNS add-on. The best alternative I have found so far is described below.
@ndegory meanwhile you can use the null resources to get the things done, 
```
resource "null_resource" "add_tolerations_dns" {
provisioner "local-exec" {
    command = <<EOF
    kubectl patch deploy -n kube-system coredns --type='json' -p='[{"op": "add", "path": "/spec/template/spec/tolerations/-", "value": {"operator": "Equal", "key": "node.type/role", "value": "critical-components","effect": "NoSchedule"}}]'
EOF
  }
  }
```

**Comment by bharathnoddy** [comment]
Tolerations are supported starting wit :
EBS CSI Driver : v1.16.0-eksbuild.1
CoreDNS EKS Addon : v1.9.3-eksbuild


with terraform you can use something like this to get this done
`resource "aws_eks_addon" "core_dns" {
  cluster_name                = aws_eks_cluster.main.name
  addon_name                  = "coredns"
  addon_version               = "v1.9.3-eksbuild.3"
  resolve_conflicts_on_create = "OVERWRITE"

  configuration_values = jsonencode({
    tolerations: [
    {
      key: "dedicated",
      operator: "Equal",
      value: "admin",
      effect: "NoSchedule"
    }
  ]
  })
}`

**Comment by bryantbiggs** [comment]
This is not an issue related to the provider - as more values are exposed by EKS addons, they will be exposed through the `configuration_values` argument. And as those values are added to the configuration values schema, those will happen in newer versions of the addon. So as @bharathnoddy has shown, this is available today with newer versions of the addons and no provider level changes are required here

**Comment by justinretzolk** [comment]
Given the most recent comments indicating that this is now possible, closing as resolved.
