### ISSUE TITLE
[Docs]: data.aws_ssm_parameters_by_path confusing and copy/paste from aws_ssm_parameter incorrectly

### ISSUE THREAD

**Issue by freimer** [hashicorp/terraform-provider-aws#26840]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ssm_parameters_by_path

### Description

Current documentation is unclear, and mostly a copy/paste from aws_ssm_parameter with incorrect information.  It should be made clear that aws_ssm_parameters_by_path is designed to retrieve all of the parameters under a path location, with the recursive option, and not a single parameter.  aws_ssm_parameters_by_path will retrieve empty lists if a full path to an actual parameter is specified for the `path` parameter.  The two notes under the example confuse the issue, as they are copied from the aws_ssm_parameter page, and do not even refer to the correct resource.

Recommend changing both aws_ssm_parameter and aws_ssm_parameters_by_path in the following ways:

1. For aws_ssm_parameter make clear that the name can include the full path to the secret, such as `name = "/my/full/path/to/myparameter"`, or even `name = "/aws/service/eks/optimized-ami/1.23/amazon-linux-2/recommended/image_id"`.
2. For aws_ssm_parameters_by_path make clear that it retrieves all parameters under the specified path into the set of lists arns, names, types, and values, optionally recursively.
3. For aws_ssm_parameters_by_path either completely remove the notes, or update them for proper reference and examples for aws_ssm_parameters_path.
4. For both, if the note about sensitive values remains, update it to give an example of using nonsensitive to remove sensitive markings for values which are know to be non sensitive, since all are marked sensitive.

### Would you like to implement a fix?

No

**Comment by acwwat** [comment]
I've submitted a PR that aims to at least bring the doc to parity with AWS API documentation. Some comments about the points made in the original post:

1. I've added a note in the `path` argument description that briefly explains the behavior when the path is a parameter name and not a hierarchy.
2. Hopefully the description of the attributes clarify that the arguments are a list of the param from the values. I am not sure why there shouldn't just be a list attribute of param objects but is instead broken into four list attributes.
3. The notes are still relevant to the data source. I've reworded the notes a bit to give more context.
4. I've added a note explaining situations where the `nonsensitive` function might be appropriate for the `values` attribute.
