### ISSUE TITLE
[Bug]: aws_glue_connection resource: no option for SSL Required?  

### ISSUE THREAD

**Issue by jeffrose-relay** [hashicorp/terraform-provider-aws#26841]
### Terraform Core Version

Terraform v1.2.8 on darwin_amd64

### AWS Provider Version

version = ">= 4.28.0"

### Affected Resource(s)

aws_glue_connection

### Expected Behavior

Should be able to fill in a value for Require SSL connection

### Actual Behavior

Cannot find any way to fill in Require SSL connection

### Terraform Configuration Files

```hcl
resource "aws_glue_connection" "redshift_glue_connection" {
  name            = "redshift_conn_${terraform.workspace}"
  description     = "Glue connection to redshift"
  connection_type = "JDBC"
  connection_properties = {
    # connection_type = "JDBC"
    JDBC_CONNECTION_URL = "jdbc:redshift://${var.redshift_host}:5439/${var.redshift_db_name}"
    USERNAME            = var.redshift_username
    password            = ""
  }

  physical_connection_requirements {
    availability_zone      = data.aws_subnet.redshift_subnet.availability_zone
    security_group_id_list = tolist(data.aws_security_groups.security_groups.ids)
    subnet_id              = var.redshift_subnet_id
  }

}
```

### Steps to Reproduce

terraform init
terraform apply

### Important Factoids

Looking through https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_connection, I don't see any reference to the Require SSL connection option that is visible in the console. There should be some way to fill this value in with terraform but I cannot find it. I have also search stackoverflow but cannot find any solutions to this.

![image](https://user-images.githubusercontent.com/96207770/190679629-d5379e88-c08c-42dd-bebe-9dd576ce5488.png)

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_connection

**Comment by justinretzolk** [comment]
Hey @jeffrose-relay 👋 Thank you for taking the time to raise this! [It looks like](https://docs.aws.amazon.com/glue/latest/webapi/API_ConnectionInput.html) there's another connection property, `JDBC_ENFORCE_SSL`, that I believe will allow you to configure SSL requirement. Can you review the linked document and verify if that's what you're looking for?

**Comment by jeffrose-relay** [comment]
Hey @justinretzolk that worked for me.  Thanks for sharing this.  Those connection properties are not listed on the documention page, so I was not aware of them.  Thanks! https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_connection#connection_properties
