### ISSUE TITLE
[Enhancement]: Add Filter to aws_rds_engine_version

### ISSUE THREAD

**Issue by frugecn** [hashicorp/terraform-provider-aws#26867]
### Description

Within the Console in AWS, when selecting Aurora, there is a section for filters:

Show versions that support the global database feature
Allows a single Amazon Aurora database to span multiple AWS Regions.

Show versions that support the parallel query feature
Improves the performance of analytic queries by pushing processing down to the Aurora storage layer.

Show versions that support Serverless v2
Offers instance scaling for even the most demanding workloads.

The Data resource aws_rds_engine_version should have these same options to return the default version within the filters defined where version and preferred version are not defined.

### Affected Resource(s) and/or Data Source(s)

data aws_rds_engine_version

### Potential Terraform Configuration

```terraform
data "aws_rds_engine_version" "test" {
  engine             = "mysql"
  filter = ["global", "parallel", "serverless v2"]
}
```

**Comment by mhaoda** [comment]
Hi, is this issue still waiting for a PR? can I work on this enhancement?

**Comment by samirbehara** [comment]
I am working on this issue.

**Comment by md5** [comment]
I didn't notice this issue until today, but I've had a PR open that covers this scope for over a month: https://github.com/hashicorp/terraform-provider-aws/pull/26923
