### ISSUE TITLE
[Docs]: cloudwatch_metric_stream

### ISSUE THREAD

**Issue by RobertAtTegus** [hashicorp/terraform-provider-aws#26861]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_metric_stream#import

### Description

The example "import" statement is missing an argument (stream name). It should be something like:

```
$ terraform import aws_cloudwatch_metric_stream.sample Sample-Stream-Name
```

### Would you like to implement a fix?

No

**Comment by pknanduri** [comment]
I will work on this and submit PR.
