### ISSUE TITLE
[New Data Source]: Timestream Write API

### ISSUE THREAD

**Issue by rpf3** [hashicorp/terraform-provider-aws#26865]
### Description

The resources added in #19354 seem to be missing their corresponding data sources.  It would be useful to be able to query details of Timestream databases and tables.

### Requested Resource(s) and/or Data Source(s)

* aws_timestreamwrite_database
* aws_timestreamwrite_table

### Potential Terraform Configuration

``` hcl
data "aws_timestreamwrite_database" "example" {
  database_name = "database-example"
}

data "aws_timestreamwrite_table" "example" {
  database_name = data.aws_timestreamwrite_database.example.database_name
  table_name    = "example"
}
```

### References

https://docs.aws.amazon.com/timestream/latest/developerguide/API_Operations_Amazon_Timestream_Write.html

**Comment by hunttom** [comment]
I would like to work on this one.
