### ISSUE TITLE
[New Resource]: aws advanced shield - EnableApplicationLayerAutomaticResponse 

### ISSUE THREAD

**Issue by lifeofguenter** [hashicorp/terraform-provider-aws#26873]
### Description

* https://docs.aws.amazon.com/waf/latest/DDOSAPIReference/API_EnableApplicationLayerAutomaticResponse.html
* https://aws.amazon.com/blogs/aws/aws-shield-advanced-update-automatic-application-layer-ddos-mitigation/

### Requested Resource(s) and/or Data Source(s)

* aws_shield_advanced_automatic_layer_protection

### Would you like to implement a fix?

No

**Comment by Pixxle** [comment]
I want to take a stab at implementing this! :)

**Comment by Pixxle** [comment]
Created a pull-request on this topic, but need some guidance on how to proceed due to AWS modifying web_acl resource when the aws_shield_advanced_automatic_layer_protection is enabled and disabled. Resulting in problem with optimistic locking in web_acl resource.

**Comment by nodomain** [comment]
How is this topic planned to be continued?

**Comment by cgagnon-crakmn** [comment]
I was looking for this and found out you closed your PR. Why did you close it?
