### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by mohammadreza490** [hashicorp/terraform-provider-aws#26877]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_faq

### Description

The code blocks uses `source_s3_path` even though in the description, it's mentioned that `s3_path` block should be used. Using `source_s3_path` for the FAQ resource causes these errors: `Blocks of type "source_s3_path" are not expected here.` and `At least 1 "s3_path" blocks are required.`

The same block can be used for [aws_kendra_thesaurus resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_thesaurus) without a problem.

The difference between these two resources can cause incostintency in the code

**Comment by justinretzolk** [comment]
Hey @mohammadreza490 👋 Thank you for taking the time to raise this! I've opened a PR to correct the reference in the examples to `s3_path` rather than `source_s3_path`.

**Comment by mohammadreza490** [comment]
@justinretzolk happy to help!
