### ISSUE TITLE
[Docs]: Resource: aws_msk_cluster

### ISSUE THREAD

**Issue by 365CryptoServiceAccount** [hashicorp/terraform-provider-aws#26884]

**Comment by justinretzolk** [comment]
Hey @365CryptoServiceAccount 👋 It looks like you've submitted a blank issue. If you're looking to report an issue with the `aws_msk_cluster` resource documentation, you may do so using the [Report a Documentation Error](https://github.com/hashicorp/terraform-provider-aws/issues/new?assignees=&labels=documentation%2Cneeds-triage&template=01_documentation.yml&title=%5BDocs%5D%3A+) issue template.
