### ISSUE TITLE
[New Resource]: EBS Volume Detachment and ec2 stop and start

### ISSUE THREAD

**Issue by nittuve** [hashicorp/terraform-provider-aws#26893]
### Description

I did not find any resource to detach the existing root/other EBS volumes in AWS
Also to stop or start the EC2 instance.
use case:
i have root volume / other volumes which are encrypted with default aws encryption key.
Now i would like to make use of custom encryption key.
manual steps i followed.
1. created ec2
2. created snapshot of attached root volume
3. created encrypted volume from the above snapshot
next steps 
1. stop the ec2 
2. detach existing root volume
3. attach the encrypted volume

### Requested Resource(s) and/or Data Source(s)

aws_volume_detachment

### Potential Terraform Configuration

```terraform
aws_volume_attachment
```

**Comment by justinretzolk** [comment]
Related #22
