### ISSUE TITLE
[Bug]: Keyspaces Cluster Key Ordering

### ISSUE THREAD

**Issue by TravisHanna** [hashicorp/terraform-provider-aws#26891]
### Terraform Core Version

1.2.7

### AWS Provider Version

4.28.0

### Affected Resource(s)

Keyspaces for Cassandra

### Expected Behavior

The order in which clustering keys are defined is critically important.  When including cluster keys in a where clause, you cannot skip a key and use a key that follows.  For example a table defined as follows:

entity_id (partition_key)
event_id (first clustering key)
occurred_at (second clustering key)

is NOT equivalent to:

entity_id (partition_key)
occurred_at (first clustering key) 
event_id (second clustering key)

In the first case, I can query by entity_id, entity_id & event_id, or entity_id & event_id & occurred at.  I cannot query by entity_id & occurred_at.

The expected behavior is that changing the order in which clustering keys are defined in the .tf file will be reflected in the table definition.  Alternately, a new attribute could be introduced to control the order in which clustering keys are defined.

### Actual Behavior

Changing the order in the .tf file has no impact on which cluster key appears first in the table definition.

### Relevant Error/Panic Output Snippet

```shell
An example error message is as follows:

"PRIMARY KEY column "occurred_at" cannot be restricted as preceding column "event_id" is not restricted"
```

### Terraform Configuration Files

resource "aws_keyspaces_table" "events" {
  keyspace_name = aws_keyspaces_keyspace.eval_keyspace.name
  table_name    = "events"

  schema_definition {
    column {
      name = "entity_id"
      type = "text"
    }

    column {
      name = "occurred_at"
      type = "timestamp"
    }

    column {
      name = "event"
      type = "text"
    }

    column {
      name = "message"
      type = "text"
    }

    partition_key {
      name = "entity_id"
    }

    clustering_key {
      name     = "occurred_at"
      order_by = "DESC"
    }

    clustering_key {
      name     = "event"
      order_by = "ASC"
    }
  }
}

### Steps to Reproduce

Change the order in which the clustering keys appear in the .tf file.  Destroy and re-apply.  The order in which the keys are defined does not change.

### References

https://www.baeldung.com/cassandra-keys

(see 4.3 Clustering Keys)

_What's important to note here is that the where clause should contain the columns in the same order as defined in the primary key clause._

**Comment by ewbankkit** [comment]
@TravisHanna Thanks for raising this issue.
It has already been noticed in #26276. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
