### ISSUE TITLE
[New Data Source]: aws_appmesh_virtual_router

### ISSUE THREAD

**Issue by ChrisMKinsella** [hashicorp/terraform-provider-aws#26908]
### Description

Could we request a new **aws_appmesh_virtual_router** data source so we can lookup the resources by attitbutes or tags. 

### Requested Resource(s) and/or Data Source(s)
aws_appmesh_virtual_router

### Potential Terraform Configuration

```terraform
data "aws_appmesh_virtual_router" "sample_filtered_on_name" {
    name = "simpleapp"
}

data "aws_appmesh_virtual_router" "sample_filtered_on_tag_name" {
   tags = {
    myTag = "simpleapp_virtual_router"
   }
}
```

### Would you like to implement a fix?

No

**Comment by vijal-patel** [comment]
Could I pick this one up?

**Comment by alowder94** [comment]
Planning to poke at this one

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/17590.
