### ISSUE TITLE
[New Data Source]: aws_appmesh_virtual_gateway

### ISSUE THREAD

**Issue by ChrisMKinsella** [hashicorp/terraform-provider-aws#26907]
### Description

Could we please have a new data source to allow us to lookup **aws_appmesh_virtual_gateway** resources without having to use remote state

### Requested Resource(s) and/or Data Source(s)

aws_appmesh_virtual_gateway

### Potential Terraform Configuration

```terraform
data "aws_appmesh_virtual_gateway" "sample_filtered_on_name" {
    name = "simpleapp"
}

data "aws_appmesh_virtual_gateway" "sample_filtered_on_tag_name" {
   tags = {
    myTag = "simpleapp_virtual_gateway"
   }
}
```

### Would you like to implement a fix?

No

**Comment by AhmedGrati** [comment]
Hey, is this issue still waiting for a PR? can I work on it?
