### ISSUE TITLE
[New Data Source]: aws_appmesh_virtual_node

### ISSUE THREAD

**Issue by ChrisMKinsella** [hashicorp/terraform-provider-aws#26909]
### Description

Could we please have a new data source to allow us to lookup aws_appmesh_virtual_node resources without having to use remote state

### Requested Resource(s) and/or Data Source(s)

aws_appmesh_virtual_node

### Potential Terraform Configuration

```terraform
data "aws_appmesh_virtual_node" "sample_filtered_on_name" {
    name = "simpleappnode"
}

data "aws_appmesh_virtual_node" "sample_filtered_on_tag_name" {
   tags = {
    myTag = "simpleapp_virtual_node"
   }
}
```

### Would you like to implement a fix?

No

**Comment by shogohida** [comment]
Hi @ChrisMKinsella and @justinretzolk, can I work on this?

**Comment by justinretzolk** [comment]
Hey @shogohida absolutely!

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/17590.
