### ISSUE TITLE
[Bug]: data.aws_ssm_parameter - Non SecureString SSM parameters marked as sensitive

### ISSUE THREAD

**Issue by agupta94** [hashicorp/terraform-provider-aws#26915]
### Terraform Core Version

0.15.5

### AWS Provider Version

4.31.0

### Affected Resource(s)

data.aws_ssm_parameter

### Expected Behavior

Non SecureString Values should not be flagged sensitive

### Actual Behavior

All values are being flagged sensitive

### Terraform Configuration Files

```
data "aws_ssm_parameter" "logging_name" {
  name = "/logging_name"
}

name = data.aws_ssm_parameter.logging_name.value
```

### Steps to Reproduce

Create `/logging_name` SSM parameter of type `String`.

1. terraform init
2. terraform plan

### Debug Output

```
logging {
          # Warning: this attribute value will be marked as sensitive and will not
          # display in UI output after applying this change. The value is unchanged.
          ~ name = (sensitive)
            # (1 unchanged attribute hidden)
        }
```

### References

Based on issue https://github.com/hashicorp/terraform-provider-aws/issues/9090 the fix was added for insecure_value in provider version 4.22.0 but `data.aws_ssm_parameter` was left out.

**Comment by gab-despreslaberge** [comment]
Possibility would be to add a `insecure_value` attribute, like it was done for the resource.

**Comment by Jno21** [comment]
Hello, I just did an implementation using `insecure_value` like the one that was made for the resource. Let's see if we can move this forward.
