### ISSUE TITLE
[New Data Source]: aws_appmesh_route

### ISSUE THREAD

**Issue by ChrisMKinsella** [hashicorp/terraform-provider-aws#26911]
### Description

Could we please have a new data source to allow us to lookup aws_appmesh_route resources without having to use remote state

### Requested Resource(s) and/or Data Source(s)

aws_appmesh_route

### Potential Terraform Configuration

```terraform
data "aws_appmesh_route" "sample_filtered_on_name" {
  name                = "serviceB-route"
  mesh_name           = aws_appmesh_mesh.simple.id
  virtual_router_name = aws_appmesh_virtual_router.serviceb.name
}

data "aws_appmesh_route" "sample_filtered_on_tag_name" {
   tags = {
    myTag = "simpleapp_route_unique_value"
   }
}
```

### Would you like to implement a fix?

No

**Comment by stefangrosaru** [comment]
There is already a PR open for this: #26695
