### ISSUE TITLE
[New Data Source]: aws_appmesh_gateway_route

### ISSUE THREAD

**Issue by ChrisMKinsella** [hashicorp/terraform-provider-aws#26910]
### Description

Could we please have a new data source to allow us to lookup aws_appmesh_gateway_route resources without having to use remote state

### Requested Resource(s) and/or Data Source(s)

aws_appmesh_gateway_route

### Potential Terraform Configuration

```terraform
data "aws_appmesh_gateway_route" "sample_filtered_on_name" {
  name                 = "example-gateway-route"
  mesh_name            = "example-service-mesh"
  virtual_gateway_name = aws_appmesh_virtual_gateway.example.name
}

data "aws_appmesh_gateway_route" "sample_filtered_on_tag_name" {
   tags = {
    myTag = "aws_appmesh_gateway_route_unique_value"
   }
}
```

### Would you like to implement a fix?

No

**Comment by shogohida** [comment]
Hi @ChrisMKinsella and @justinretzolk, can I work on this?

**Comment by justinretzolk** [comment]
Hi @shogohida, absolutely!

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/17590.
