### ISSUE TITLE
[Docs]: Resource: aws_budgets_budget

### ISSUE THREAD

**Issue by sry9681** [hashicorp/terraform-provider-aws#26921]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/budgets_budget

### Description

The possible valid options that can be put in the cost_filter values list is non-existent (specifically for a _budget-type = "COST"_, and a _cost_filter { name = "Service"}_).

### References

The filters (which are also not present on the AWS documentation [here](https://docs.aws.amazon.com/cost-management/latest/userguide/budgets-create-filters.html)) that can only be seen if you attempt to manually create a Cost budget on the AWS GUI and click Filters to add a new filter have names that do not match what the Terraform module expects.

**Comment by hamburml** [comment]
I also think the docu could be improved. I need to set a budget and the only filter is TagKeyValue.
How do I do this?

```
resource "aws_budgets_budget" "ec2" {
  name              = "budget-ec2-monthly"
  budget_type       = "COST"
  limit_amount      = "1200"
  limit_unit        = "USD"
  time_period_end   = "2087-06-15_00:00"
  time_period_start = "2017-07-01_00:00"
  time_unit         = "MONTHLY"

  cost_filter {
    name = "Service"
    values = [
      "tagkey:tagvalue",
    ]
  }

  notification {
    comparison_operator        = "GREATER_THAN"
    threshold                  = 100
    threshold_type             = "PERCENTAGE"
    notification_type          = "FORECASTED"
    subscriber_email_addresses = ["test@example.com"]
  }
}
```
Or this?
```
resource "aws_budgets_budget" "ec2" {
  name              = "budget-ec2-monthly"
  budget_type       = "COST"
  limit_amount      = "1200"
  limit_unit        = "USD"
  time_period_end   = "2087-06-15_00:00"
  time_period_start = "2017-07-01_00:00"
  time_unit         = "MONTHLY"

  cost_filter {
    name = "Service"
    TagKeyValue = [
      "tagkey:tagvalue",
    ]
  }

  notification {
    comparison_operator        = "GREATER_THAN"
    threshold                  = 100
    threshold_type             = "PERCENTAGE"
    notification_type          = "FORECASTED"
    subscriber_email_addresses = ["test@example.com"]
  }
}
```
