### ISSUE TITLE
[Enhancement]: Support new aws_lakeformation_data_lake_settings argument for credentials vending

### ISSUE THREAD

**Issue by simonvdk** [hashicorp/terraform-provider-aws#26932]
### Description

The upstream API added new arguments for the data lake settings (see [doc](https://docs.aws.amazon.com/cli/latest/reference/lakeformation/put-data-lake-settings.html)) necessary for [credentials vending](https://docs.aws.amazon.com/lake-formation/latest/dg/using-cred-vending.html) that could be added to the `aws_lakeformation_data_lake_settings` resource and datasource:

- `AllowExternalDataFiltering` (boolean): could become an `allow_external_data_filtering` (Optional boolean) argument/attribute
- `ExternalDataFilteringAllowList` (list of struct with only one `DataLakePrincipalIdentifier` key): could become an `external_data_filtering_allow_list` (Optional list of principal identifiers) argument/attribute
- `AuthorizedSessionTagValueList` (list): could become an `authorized_session_tag_value_list` (Optional list of strings) argument/attribute

### Affected Resource(s) and/or Data Source(s)

`aws_lakeformation_data_lake_settings` (resource and data source)

### Potential Terraform Configuration

```terraform
resource "aws_lakeformation_data_lake_settings" "example" {
  admins = [aws_iam_user.test.arn, aws_iam_role.test.arn]

  create_database_default_permissions {
    permissions = ["SELECT", "ALTER", "DROP"]
    principal   = aws_iam_user.test.arn
  }

  create_table_default_permissions {
    permissions = ["ALL"]
    principal   = aws_iam_role.test.arn
  }

  allow_external_data_filtering      = true
  external_data_filtering_allow_list = [data.aws_caller_identity.current.account_id]
  authorized_session_tag_value_list  = ["engine1"]
}
```

### References

https://docs.aws.amazon.com/cli/latest/reference/lakeformation/put-data-lake-settings.html

**Comment by DominikVollandTNG** [comment]
Since ~November 2022 (AWS CLI version 2.8.13), the API now also accepts the `Parameters` argument, which allows to set the `CrossAccountVersion`. It would be great if this could also be added to the pull request #27042 before merging it.
