### ISSUE TITLE
[Docs]: Docs for importing web_acl are incorrect

### ISSUE THREAD

**Issue by tolidano** [hashicorp/terraform-provider-aws#26938]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_web_acl

### Description

It says:
```
WAF Web ACL can be imported using the id, e.g.,

$ terraform import aws_waf_web_acl.main 0c8e583e-18f3-4c13-9e2a-67c4805d2f94
```
But this is not true:
```
 > terraform import module.cm15.aws_wafv2_web_acl.this a5208dce-5a45-49ce-bfe4-dcbe66ee953a
module.cm15.aws_wafv2_web_acl.this: Importing from ID "a5208dce-5a45-49ce-bfe4-dcbe66ee953a"... 

Error: Unexpected format of ID ("a5208dce-5a45-49ce-bfe4-dcbe66ee953a"), expected ID/NAME/SCOPE
```

The correct declaration is:
```
 > terraform import module.cm15.aws_wafv2_web_acl.this a5208dce-5a45-49ce-bfe4-dcbe66ee953a/dev-cm15-waf/REGIONAL
module.cm15.aws_wafv2_web_acl.this: Importing from ID "a5208dce-5a45-49ce-bfe4-dcbe66ee953a/dev-cm15-waf/REGIONAL"...
module.cm15.aws_wafv2_web_acl.this: Import prepared!
  Prepared aws_wafv2_web_acl for import
module.cm15.aws_wafv2_web_acl.this: Refreshing state... [id=a5208dce-5a45-49ce-bfe4-dcbe66ee953a]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```
Note that it must include the name and the scope (being CLOUDFRONT or REGIONAL)

### Would you like to implement a fix?

No

**Comment by scottwestover** [comment]
@tolidano From the example you provided, it looks like you are using the `aws_wafv2_web_acl` resource, but you shared a link to the `waf_web_acl` resource. The `waf_web_acl` resource does support just providing the `id` when you import the resource, but the `aws_wafv2_web_acl` resource expects the full `ID/Name/Scope` string when you do the import.

<img width="681" alt="Screen Shot 2022-09-29 at 7 14 12 PM" src="https://user-images.githubusercontent.com/9931822/193158180-8886e16f-ccd4-4f98-b76b-1845567b6b9e.png">

From the docs here: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl#import

**Comment by justinretzolk** [comment]
Hey @tolidano 👋 Thank you for taking the time to raise this! As mentioned above, it looks like this is a difference in importing the [`aws_waf_web_acl` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/waf_web_acl#import) vs. the [`aws_wafv2_web_acl` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl#import).

Given that's the case, we'll close this issue for now. Please do let me know if you feel I've done this in error, and thank you again for taking the time to raise this, regardless of the outcome!
