### ISSUE TITLE
[Bug]: aws_placement_group forces recreate without optional spread_level arg

### ISSUE THREAD

**Issue by jonathanstockton** [hashicorp/terraform-provider-aws#26958]
### Terraform Core Version

1.3.0

### AWS Provider Version

4.31.0

### Affected Resource(s)

aws_placement_group

### Expected Behavior

When **re-applying after initial creation**, no changes should be made:

```
resource "aws_placement_group" "thing" {
  name     = "thing"
  strategy = "spread"
}
```

### Actual Behavior

Resource is marked for recreation with changes in optional parameters:

```
resource "aws_placement_group" "proxy_placement" {
  ~ arn                = "xxxx" -> (known after apply)
  ~ id                 = "thing" -> (known after apply)
    name               = "thing"
  ~ partition_count    = 0 -> (known after apply)
  ~ placement_group_id = "pg-034752b34588fb238" -> (known after apply)
  - spread_level       = "rack" -> null # forces replacement
  - tags               = {} -> null
  ~ tags_all           = {} -> (known after apply)
    # (1 unchanged attribute hidden)
}
```

### Terraform Configuration Files
```
terraform {
  required_version = "= 1.3.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.31.0"
    }
  }
}

provider "aws" {
  region = "eu-west-1
}

resource "aws_placement_group" "thing" {
  name     = "thing"
  strategy = "spread"
}
```
### Steps to Reproduce

Apply terraform containing "aws_placement_group" resources without optional "spread_level" parameter multiple times

### Would you like to implement a fix?

No

**Comment by DoctorPolski** [comment]
Probably as a result of: https://github.com/hashicorp/terraform-provider-aws/pull/25615
