### ISSUE TITLE
[Bug]: Plan Works but Apply fails with Validation Error while creating send-spot-instance-interruptions template

### ISSUE THREAD

**Issue by kranthi-paidi** [hashicorp/terraform-provider-aws#26950]
### Terraform Core Version

1.3.0

### AWS Provider Version

4.31.0

### Affected Resource(s)

* aws_fis_experiment_template

### Expected Behavior

Experiment Template should be created

### Actual Behavior

`terraform plan` works but `terraform apply` fails with the following error message: 

**Error**: creating AWS FIS (Fault Injection Simulator) Experiment Template (Send Spot Instance Interruptions): operation error fis: CreateExperimentTemplate, https response error StatusCode: 400, RequestID: 860c106e-bbae-4d1a-bad6-f1fb6f63feb1, ValidationException: Unexpected target "Instances" found in action "Send-Spot-Instance-Interruptions".

### Relevant Error/Panic Output Snippet

```shell
Error: creating AWS FIS (Fault Injection Simulator) Experiment Template (Send Spot Instance Interruptions): operation error fis: CreateExperimentTemplate, https response error StatusCode: 400, RequestID: 860c106e-bbae-4d1a-bad6-f1fb6f63feb1, ValidationException: Unexpected target "Instances" found in action "Send-Spot-Instance-Interruptions".
```

### Terraform Configuration Files

```hcl

terraform {
  required_version = ">= 0.12.0"
  required_providers {
    aws = ">= 2.0.0"
  }
}

provider "aws" {
  region = "us-west-2"
}

# AWS EC2 FIS Experiment - Send Spot Instance Interruptions
resource "aws_fis_experiment_template" "ec2_send_spot_instance_interruptions" {
  description = "Send Spot Instance Interruptions"
  role_arn    = var.fis_role_arn
  stop_condition {
    source = "none"
  }

  action {
    action_id   = "aws:ec2:send-spot-instance-interruptions"
    name        = "Send-Spot-Instance-Interruptions"
    description = "Send Spot Instance Interruptions"

    target {
      key   = "Instances"
      value = "send-spot-instance-interruptions-target"
    }

    parameter {
      key   = "durationBeforeInterruption"
      value = "PT${var.duration_before_spot_interruption}M"
    }
  }

  target {
    name           = "send-spot-instance-interruptions-target"
    resource_type  = "aws:ec2:spot-instance"
    selection_mode = "PERCENT(${var.send_spot_instance_interruptions_percentage})"

    resource_tag {
      key   = var.send_spot_instance_interruptions_target_tags.key
      value = var.send_spot_instance_interruptions_target_tags.value
    }
  }
}

``````

### Steps to Reproduce

1. `terraform plan` - should produce **Plan**: 1 to add, 0 to change, 0 to destroy.
2. `terraform apply`

**Comment by keithalpichi** [comment]
I ran into this issue myself today. `action.target.key` should be `SpotInstance` but it looks like the resource doesn't support this target type at the moment. It's [missing](https://github.com/hashicorp/terraform-provider-aws/blob/8f85d62f1aaf0375f8028445b5916b1f28614089/internal/service/fis/experiment_template.go#L818).

I am interested in contributing to this issue and adding support for spot instances.

**Comment by mitch-thompson** [comment]
We ran into this same issue today running terraform 1.1.9 and aws provider 4.34.0.  I went ahead and updated the `validExperimentTemplateActionTargetKey()`, and I was able to successfully deploy our terraform with a aws_fis_experiment_template for SpotInstances.

Please let me know if there is anything else I need to do to get this in.
