### ISSUE TITLE
Terraform v1.3.0: Import fails with `Error writing state file: Failed to serialize resource instance in state: Instance <...> has status ObjectPlanned, which cannot be saved in state.`

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#26962]
In Terrafrom `v1.3.0`, we are seeing an error on `terraform import`:

> Error writing state file: Failed to serialize resource instance in state: Instance <...> has status ObjectPlanned, which cannot be saved in state.

**Terraform versions lower than `v1.3.0` do not have this error.**

See hashicorp/terraform#31851 for details.

**Comment by pin007** [comment]
Terraform v1.3.1 fixed that issue for me

**Comment by ewbankkit** [comment]
Fixed via https://github.com/hashicorp/terraform/pull/31871.
