### ISSUE TITLE
[New Resource]: aws_config_organization_custom_policy

### ISSUE THREAD

**Issue by ghimire** [hashicorp/terraform-provider-aws#26989]
### Description

The https://docs.aws.amazon.com/config/latest/APIReference/API_PutOrganizationConfigRule.html API supports `OrganizationCustomPolicyRuleMetadata` which allows setting AWS Config Custom Policy as AWS Cloudformation guard policy text. This feature is available with the [aws_config_config_rule](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_config_rule#custom-policies) but is not available for the `aws_config_organisation_*`.

### Requested Resource(s) and/or Data Source(s)

* aws_config_organization_custom_policy

### Potential Terraform Configuration

```terraform
resource "aws_config_organization_custom_policy" "example-organisation-config-rule" {
	name = "example-organisation-config-rule-name"

	organisation_config_rule_trigger_types = ["ConfigurationItemChangeNotification"]
	maximum_execution_frequency = "Twelve_Hours"

	policy_runtime = "guard-2.x.x"
	policy_text = << EOF
	rule tableisactive when
	resourceType == "AWS::DynamoDB::Table" {
		configuration.tableStatus == ['ACTIVE']
	}

	rule checkcompliance when
	resourceType == "AWS::DynamoDB::Table"
	tableisactive {
		supplementaryConfiguration.ContinuousBackupsDescription.pointInTimeRecoveryDescription.pointInTimeRecoveryStatus == "ENABLED"
	}
	EOF

}
```

### References

- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_config_rule#custom-policies
- https://docs.aws.amazon.com/config/latest/APIReference/API_OrganizationCustomPolicyRuleMetadata.html#config-Type-OrganizationCustomPolicyRuleMetadata-PolicyText

### Would you like to implement a fix?

No

**Comment by dtserekhman-starz** [comment]
Hi, when is this pull request expected to be approved and merged?

**Comment by gpetrovgeorgi** [comment]
Hello, I am also awaiting for this implementation to take place. When this could happen ?
