### ISSUE TITLE
[Enhancement]: add "TLS version and cipher headers" and "Client port preservation" flags to aws_lb

### ISSUE THREAD

**Issue by LeoSpyke** [hashicorp/terraform-provider-aws#26988]
### Description

It would be amazing to have the possibility to set the following attributes in the `aws_lb` resource creation:
- TLS version and cipher headers 
- Client port preservation

In this scenario I need to enable these two flags during the creation of an Application Load Balancer.

### Affected Resource(s) and/or Data Source(s)

`aws_lb` and `aws_alb`

### Potential Terraform Configuration

```terraform
resource "aws_lb" "alb" {
  name = "enhancement-alb"
  load_balancer_type = "application"
  # [...]

  tls_version_and_cipher_headers = true
  client_port_preservation = true 
}
```

### References

Related docs:
- https://docs.aws.amazon.com/elasticloadbalancing/latest/application/x-forwarded-headers.html
- https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-application-load-balancer.html

### Would you like to implement a fix?

No

**Comment by LeoSpyke** [comment]
Any news about this feature?

**Comment by markitovtr1** [comment]
Hello.

I think you can close this issue now as there are "enable_xff_client_port" and "enable_tls_version_and_cipher_suite_headers" properties in "aws_lb" resource.
