### ISSUE TITLE
[Bug]: Provider issue in using ASSUME_ROLE_WITH_WEB_IDENTITY with envrionment variables

### ISSUE THREAD

**Issue by eitah** [hashicorp/terraform-provider-aws#27019]
### Terraform Core Version

1.2.7

### AWS Provider Version

v4.32.0

### Affected Resource(s)

We're migrating to use assume_role_with_web_identity on our AWS providers. When we provide hardcoded roles and identity files they work. Or, when we omit the assume_role_with_wb_identity block entirely and instead export AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE the credentials work.

### Expected Behavior
We expect to be able to specify the role_arn in the provider configuration block while inheriting the AWS_WEB_IDENTITY_TOKEN_FILE credentials from the environment as documented in https://registry.terraform.io/providers/hashicorp/aws/latest/docs#assume-role-with-web-identity-configuration-reference

This is useful to us because we have a single root module that needs to use multiple AWS roles, but identical AWS_WEB_IDENTITY_TOKEN_FILE arguments, so inheriting the token file from the environment would DRY up our provider configuration.

### Actual Behavior

When we omit just the `web_identity_token_file` argument from the assume_role_with_web_identity block, the variable is ignored and the provider throws an error about not specifying said token file.

Could it be that because we are using AWS Provider > 4 we are hitting an issue where the provider will not use the aws environment variables like it did in V3 provider versions? https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade#changes-to-authentication

### Relevant Error/Panic Output Snippet

```shell
│ Error: Invalid combination of arguments
│
│   with provider["registry.terraform.io/hashicorp/aws"].zro,
│   on terraform.tf line 52, in provider "aws":
│   52:   assume_role_with_web_identity {
│
│ "assume_role_with_web_identity.0.web_identity_token_file": one of
│ `assume_role_with_web_identity.0.web_identity_token,assume_role_with_web_identity.0.web_identity_token_file`
│ must be specified
```

### Terraform Configuration Files

```
provider "aws" {
  region = my-region

  assume_role_with_web_identity {
    role_arn = "arn:aws:iam::123456789012:role/my-role"
    web_identity_token_file = ".identity"
  }
}
```

### Steps to Reproduce

export AWS_ROLE_ARN="arn:aws:iam::123456789012:role/my-role"
export AWS_WEB_IDENTITY_TOKEN_FILE=".identity"

Fully providing or fully omitting the provider configuration for `assume_role_with_web_identity` works, but when you omit one or the other of the config file arguments expecting it to be inherited, the provider doesn't recognize them.

**Comment by gdavison** [comment]
Thanks for raising this, @eitah. We use the authentication features from the AWS SDK for Go v2 for the provider. We will look into support there.

As a workaround, you could provide the shared token file as a variable to your configuration. This could be set using an environment variable, such as `TF_VAR_ web_identity_token_file`

**Comment by eitah** [comment]
Thanks! Is there a corresponding issue in the AWS SDK that I can use to track the progress of support there?

**Comment by joe-a-t** [comment]
@marshallford yes, we are using the TF_VAR workaround. 

@gdavison @breathingdust is there any update on this issue or link to the corresponding AWS SKE issue that you could share?

**Comment by gdavison** [comment]
Hi @eitah and @joe-a-t. To clarify, what you're trying to do is authenticate multiple instances of the provider, each with different roles, but using a common web identity token file, something like the following:

```terraform
provider "aws" {
  ...
  assume_role_with_web_identity {
    role_arn = "arn:aws:iam::123456789012:role/my-role"
  }
}

provider "aws" {
  alias = "second"
  ...
  assume_role_with_web_identity {
    role_arn = "arn:aws:iam::123456789012:role/second-role"
  }
}

provider "aws" {
  alias = "third"
  ...
  assume_role_with_web_identity {
    role_arn = "arn:aws:iam::123456789012:role/third-role"
  }
}
```
 
And you'd like to specify the location of the web identity token file using the environment variable `AWS_WEB_IDENTITY_TOKEN_FILE`?

We currently have validation in the the provider, which is the error that you're seeing about one of the two fields `assume_role_with_web_identity.0.web_identity_token` or `assume_role_with_web_identity.0.web_identity_token_file` being required.

The AWS SDK for Go v2 also appears to expect both the Role ARN and the token file parameters to be set using the same method (i.e. direct configuration, environment variables, or from the shared configuration file). However, according to the documentation for the AWS CLI, the environment variable should override the shared configuration file. The SDK and CLI should handle configuration the same, so this looks like an error in the AWS SDK.

**Comment by gdavison** [comment]
The AWS SDK issue https://github.com/aws/aws-sdk-go-v2/issues/2015

**Comment by marshallford** [comment]
Anyone able to get `assume_role_with_web_identity` working with `role_arn` in the provider config and the `AWS_WEB_IDENTITY_TOKEN_FILE` env var set? I'm using the latest version of the aws provider (v4.64.0) and I'm still getting the `Invalid combination of arguments` terraform error.

**Comment by gdavison** [comment]
Hi everyone, thanks for your patience on this issue. After reviewing the options and some discussion with AWS, we're going to close this issue as one we won't address in the way suggested above.

The AWS CLI and SDKs don't allow mixing-and-matching of parameters between configuration files and environment variables. So all of the parameters must be specified either in the configuration file, with environment variables, or in the provider configuration block. The AWS Provider follows this practice so that the same configurations can be used with the AWS CLI, other AWS tooling, and the provider.

The most straightforward option for sharing a single token file across multiple identities without hardcoding it would be to use a [Terraform input variable](https://developer.hashicorp.com/terraform/language/values/variables) and use the [`assume_role_with_web_identity`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#assume-role-with-web-identity-configuration-reference) block in provider configuration. E.g.

```terraform
variable "token_file" {
  type = string
}

provider "aws" {
  # ...
  assume_role_with_web_identity {
    role_arn                = "arn:aws:iam::123456789012:role/ROLE_NAME"
    session_name            = "A session"
    web_identity_token_file = var.token_file
  }
}


provider "aws" {
  alias = "other"
  # ...
  assume_role_with_web_identity {
    role_arn                = "arn:aws:iam::123456789012:role/OTHER_ROLE_NAME"
    session_name            = "Another session"
    web_identity_token_file = var.token_file
  }
}
```
