### ISSUE TITLE
[Docs]: Missing Environment Variable column in `assume_role` table

### ISSUE THREAD

**Issue by joe-a-t** [hashicorp/terraform-provider-aws#27016]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs#assume-role-configuration-reference

### Description

All of the other similar tables have columns for `Setting`, `Provider`, `Environment Variable`, and `Shared Config`. The `assume_role` table is missing the `Environment Variable` column despite the fact that environment variables can be used to set several of the settings. The relevant values for this column should mostly be able to be copied from the https://registry.terraform.io/providers/hashicorp/aws/latest/docs#assume-role-with-web-identity-configuration-reference table.

**Comment by shijiadong2022** [comment]
can you assign this issue to me?

**Comment by justinretzolk** [comment]
Thanks for offering to take a look at this @shijiadong2022 👏. I've assigned it to you, as requested.

**Comment by shijiadong2022** [comment]
@justinretzolk appreciate if you can help review this PR.
