### ISSUE TITLE
[Enhancement]: aws_key_pair import should fetch public key material

### ISSUE THREAD

**Issue by tmccombs** [hashicorp/terraform-provider-aws#27023]
### Description

The documentation for importing an aws_key_pair states:

> The AWS API does not include the public key in the response, so terraform apply will attempt to replace the key pair. There is currently no supported workaround for this limitation.

This might have been true when that was written, but it is no longer the case. At least, it doesn't have to be. 

The request for DescribeKeyPairs includes an "IncludePublicKey" property. If this is set to true, then the the response includes the Public Key. 

This could also make it so that terraform can track if the public key matches the configuration. 

### Affected Resource(s) and/or Data Source(s)

* aws_key_pair

### Potential Terraform Configuration

```terraform
N/A, this would just make it so that importing an aws_key_pair would work as expected
```

### References

* AWS API documentation: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeKeyPairs.html
* Go SDK documentation: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2#DescribeKeyPairsInput

It does look like this would require using the aws-sdk-go v2 branch. I'm not sure if there is already an issue or pull request tracking migrating to that (it's kind of a difficult thing to search for in github issues), or if it would be feasible to incrementally switch to the new provider. 

I might be willing to implement this, if I had some guidance on how to approach the aws-sdk-go-v2 situation.

### Would you like to implement a fix?

No

**Comment by msharran** [comment]
I am interested in this issue

**Comment by nicolasnoel** [comment]
Would it be possible to check if it is really resolved ?

Maybe the aws_key_pair datasource now contains the public key material, but importing an aws_key_pair resource still doesn't store the public key material in the state, leading terraform to detect a change in the resource

(tested with provider 5.49)

**Comment by tmccombs** [comment]
It looks like this isn't actually resolved. 

But I think https://github.com/hashicorp/terraform-provider-aws/pull/37713 would fix it.
