### ISSUE TITLE
[Bug]: aws_cloudwatch_log_group fails when using retention policies and tag-based IAM

### ISSUE THREAD

**Issue by jgoldschrafe** [hashicorp/terraform-provider-aws#27028]
### Terraform Core Version

1.2.1

### AWS Provider Version

4.25.0

### Affected Resource(s)

* aws_cloudwatch_log_group

### Expected Behavior

When the AWS IAM principal used to apply the Terraform run is configured with tag-based `PutRetentionPolicy` permissions, `terraform apply` should successfully create a new `aws_cloudwatch_log_group` without generating an error.

### Actual Behavior

`CreateLogGroup` creates the resource and applies the specified tags, but tag application is eventually consistent, and `CreateLogGroup` returns before the tags are present on the resource. The provider subsequently calls `PutRetentionPolicy`, which fails because the tags on the resource do not (yet) match the ones considered by the IAM policy.

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: AccessDeniedException: User: arn:aws:sts::[redacted]:assumed-role/[redacted]/aws-go-sdk-1664487268507221449 is not authorized to perform: logs:PutRetentionPolicy on resource: arn:aws:logs:[redacted]:[redacted]:log-group:/aws/eks/[redacted]/cluster:log-stream: because no identity-based policy allows the logs:PutRetentionPolicy action
│ 	status code: 400, request id: 0d94c39a-944e-40a6-a9ab-2830b2658ba3
│ 
│   with module.eks.module.eks.aws_cloudwatch_log_group.this[0],
│   on .terraform/modules/eks.eks/main.tf line 76, in resource "aws_cloudwatch_log_group" "this":
│   76: resource "aws_cloudwatch_log_group" "this" {
│
```

### Terraform Configuration Files

N/A

### Steps to Reproduce

With an AWS IAM policy that grants `logs:PutRetentionPolicy` when `aws:ResourceTag/Application` `StringEquals` `serviceA`:

```
resource "aws_cloudwatch_log_group" "yada" {
  name = "Yada"

  tags = {
    Environment = "production"
    Application = "serviceA"
  }

  retention_in_days = 90
}
```

When applying your resource, you will receive an `AccessDeniedException` similar to the one above. This causes the resource to acquire a taint in the state file. After untainting the resource and applying again, the retention policy change is applied successfully.

**Comment by ewbankkit** [comment]
Looks like an IAM eventual consistency issue for the `PutRetentionPolicy` call.
