### ISSUE TITLE
Issue with updating security group attached to the EKS cluster: error creating EKS Cluster:.... Cluster already exists with name:....

### ISSUE THREAD

**Issue by gdubs** [hashicorp/terraform-provider-aws#27030]
### Description

We have an existing cluster that was created using the eks module. As months went by we wanted to update the security group so we can manage the rules attached to it. Now that we're trying to apply it, I stumbled upon a few things:

1. When doing a `terraform plan` we're getting the following 

`Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp 127.0.0.1:80: connect: connection refused`

2. Fixed that issue by adding `-refresh=false` on the statement. 

3. Problem is with the `terraform apply`, now it's attempting to create a new EKS cluster. The only thing i see in the plan that needs to be updated is the `module.eks.aws_eks_cluster.this[0]` needing to update `certificate_authority`

Error after adding `-refresh=false` 

` Error: error creating EKS Cluster (my-eks-name): ResourceInUseException: Cluster already exists with name: my-eks-name
│ {
│   RespMetadata: {
│     StatusCode: 409,
│     RequestID: "xxxxxxxx"
│   },
│   ClusterName: "my-eks-name",
│   Message_: "Cluster already exists with name: my-eks-name"
│ }
│
│   with module.eks.aws_eks_cluster.this[0],
│   on .terraform/modules/eks/cluster.tf line 9, in resource "aws_eks_cluster" "this":
│    9: resource "aws_eks_cluster" "this" {`

So I'm unsure how to proceed. As the version 18 seems to bring breaking changes and prefer not to do that where I have to destroy my cluster and rebuild it again.

**Comment by justinretzolk** [comment]
Hey @gdubs 👋 Thank you for taking the time to raise this! So that we have the information necessary to look into this, can you supply a sample of the Terraform configuration, including what module you're referring to?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
