### ISSUE TITLE
[Bug]: IAM role should assume itself in Trust Relationships

### ISSUE THREAD

**Issue by tunguyen9889** [hashicorp/terraform-provider-aws#27034]
### Terraform Core Version

1.2.9

### AWS Provider Version

4.26.0

### Affected Resource(s)

* aws_iam_role

### Expected Behavior

According to AWS announcement https://aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/, starting September 21st, 2022:

As of today, for any new role, or any role that has not recently assumed itself while relying on the old behavior, IAM administrators must modify the previously shown role trust policy as follows to allow RoleA to assume itself, regardless of the privileges granted by its identity-based policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::123456789012:role/RoleB",
                    "arn:aws:iam::123456789012:role/RoleA"
                ]
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```

### Actual Behavior

When I write the Terraform code to create/update IAM role with its `assume_role_policy` like this:

```
resource "aws_iam_role" "roleA" {
  name = "roleA"
  path = "/"

  assume_role_policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Action": "sts:AssumeRole",
            "Principal": {
               "Service": "ec2.amazonaws.com"
            },
            "Effect": "Allow"
        },
        {
            "Sid": "",
            "Action": "sts:AssumeRole",
            "Principal": {
                "AWS": [
                  "${aws_iam_role.roleB.arn}",
                  "${aws_iam_role.roleA.arn}"
                ]
            },
            "Effect": "Allow"
        }
    ]
}
EOF
}
```

This error happened as below:

### Relevant Error/Panic Output Snippet

```shell
│ Error: Self-referential block
│ 
│   on aws_iam.tf line 23, in resource "aws_iam_role" "roleA":
│   23:                   "${aws_iam_role.roleA.arn}"
│ 
│ Configuration for aws_iam_role.roleA may not refer to itself.
```

### Terraform Configuration Files

```
terraform {
  required_version = ">= 1.0.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.26.0"
    }
  }
}

provider "aws" {
  region     = "ca-central-1"
  access_key = "INSERT_ACCESS_KEY"
  secret_key = "INSERT_SECRET_KEY"
  token      = "INSERT_ROLE_TOKEN"
}

resource "aws_iam_role" "roleB" {
  name = "roleB"
  path = "/"

  assume_role_policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Action": "sts:AssumeRole",
            "Principal": {
               "Service": "ec2.amazonaws.com"
            },
            "Effect": "Allow"
        }
    ]
}
EOF
}

resource "aws_iam_role" "roleA" {
  name = "roleA"
  path = "/"

  assume_role_policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Action": "sts:AssumeRole",
            "Principal": {
               "Service": "ec2.amazonaws.com"
            },
            "Effect": "Allow"
        },
        {
            "Sid": "",
            "Action": "sts:AssumeRole",
            "Principal": {
                "AWS": [
                  "${aws_iam_role.roleB.arn}",
                  "${aws_iam_role.roleA.arn}"
                ]
            },
            "Effect": "Allow"
        }
    ]
}
EOF
}
```

### Steps to Reproduce

Try create/update an IAM role which assumes itself in Trust Relationships (`assume_role_policy`).

### Important Factoids

For a workaround, I have to tweak my Terraform code to avoid error: change `${aws_iam_role.roleA.arn}` to `"arn:aws:iam::${local.aws_account_id}:role/roleA"`

```
data "aws_caller_identity" "current" {}

locals {
  aws_account_id = data.aws_caller_identity.current.account_id
}

resource "aws_iam_role" "roleA" {
  name = "roleA"
  path = "/"

  assume_role_policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Action": "sts:AssumeRole",
            "Principal": {
               "Service": "ec2.amazonaws.com"
            },
            "Effect": "Allow"
        },
        {
            "Sid": "",
            "Action": "sts:AssumeRole",
            "Principal": {
                "AWS": [
                  "${aws_iam_role.roleB.arn}",
                  "arn:aws:iam::${local.aws_account_id}:role/roleA"
                ]
            },
            "Effect": "Allow"
        }
    ]
}
EOF
}
```

**Update 3rd Oct 2022**: the work around only works if roleA already exists. If newly create, following error occurs:

```
│ Error: failed creating IAM Role (sre-teleport-cloud-a7ppdev1): MalformedPolicyDocument: Invalid principal in policy: "AWS":"arn:aws:iam::<account_id>:role/roleA"
│ 	status code: 400, request id: 5d98b8ba-794a-453d-ba12-f9dc662a6456
│ 
│   with aws_iam_role.roleA,
│   on aws_iam.tf line 1, in resource "aws_iam_role" "roleA":
│    1: resource "aws_iam_role" "roleA" {
│ 
```

### References

AWS announcement https://aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/ on September 21st, 2022.

**Comment by pbygrave-lucid** [comment]
A workaround (adopted from this comment https://aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/#comment-5997054738) is to pass the role as an evaluated conditional, which isn't checked at policy creation. Example below:

```
data "aws_caller_identity" "current" {}

locals {
  aws_account_id = data.aws_caller_identity.current.account_id
}

resource "aws_iam_role" "roleA" {
  name = "roleA"
  path = "/"

  assume_role_policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Action": "sts:AssumeRole",
            "Principal": {
               "Service": "ec2.amazonaws.com"
            },
            "Effect": "Allow"
        },
        {
            "Sid": "",
            "Action": "sts:AssumeRole",
            "Principal": {
                "AWS": "${aws_iam_role.roleB.arn}",
            },
            "Effect": "Allow"
        },
        {
            "Sid": "",
            "Action": "sts:AssumeRole",
            "Principal": {
                "AWS": "arn:aws:iam::${local.aws_account_id}:root
            },
            "Effect": "Allow",
            "Condition": {"ArnEquals": {"aws:PrincipalArn": "arn:aws:iam::${local.aws_account_id}:role/roleA}}
        }
    ]
}
EOF
}
```

**Comment by blaargh** [comment]
I'll put this on the list of reasons why we will stop using Terraform and move to a real "IaC" tool... This is in effect since June 2022, why does Terraform not have a simple parameter like assume_self = true for trust relationships. It is natively possible on AWS, why do I need a workaround in Terraform? Really annoying

**Comment by martynassateika** [comment]
Have recently bumped into this as well.

In my case the role was set up inside a Terraform module that was previously used to set up other roles. To introduce a new role without altering existing ones, I temporarily placed the "assume role" statement in a `dynamic` block, like so:

```hcl
data "aws_iam_policy_document" "assume_role_policy" {
  # ...
  dynamic "statement" {
    for_each = var.role_name == "my_new_role" ? [] : [1]
    content {
      effect  = "Allow"
      actions = ["sts:AssumeRole"]
      principals {
        type        = "AWS"
        identifiers = ["arn:aws:iam::${var.aws_account}:role/${var.role_name}"]
      }
    }
  }
}
```
This produces a plan with no changes to any of the existing roles' policies, and you can safely create the new role, then move the `dynamic` statement to a regular one again.

**Comment by johnsonaj** [comment]
Thank you for the continued interest and solutions regarding self assuming roles on this resource. As mentioned in a previous comment, the inability to add a role to itself is a technical limitation of the AWS API, which verifies all roles, in a statement, exist before creation. Additionally, manipulating the policy within the provider would cause unexpected drift for the resource since the config would not match what is ultimately in state.

We will close this issue since the problem lies in an upstream limitation. Thank you for your understanding.
