### ISSUE TITLE
[New Data Source]: aws_vpc_ipam_pool_cidrs

### ISSUE THREAD

**Issue by philstephenson** [hashicorp/terraform-provider-aws#27040]
### Description

Requesting a data source that will basically run `get-ipam-pool-cidrs` on a particular pool and return a list of all provisioned CIDRs. Then you could use this in your child accounts to attach to the route table etc.

### Requested Resource(s) and/or Data Source(s)

data aws_vpc_ipam_pool_cidrs

**Comment by drewmullen** [comment]
This is a good request:

```hcl
data "aws_vpc_ipam_pool_cidrs" "mypoolcidrs" {
  ipam_pool_id = <>
  filters = <> 
}
```

will return output of: https://docs.aws.amazon.com/cli/latest/reference/ec2/get-ipam-pool-cidrs.html
