### ISSUE TITLE
[Bug]: C2S CreateVpcEndpoint UnsupportedOperation: The operation is not supported in this region!

### ISSUE THREAD

**Issue by montaguethomas** [hashicorp/terraform-provider-aws#27048]
### Terraform Core Version

`>= 1.0.0`

### AWS Provider Version

`>= 2.53.0`

### Affected Resource(s)

* `aws_vpc_endpoint`

### Expected Behavior

VPC Endpoint is created.

### Actual Behavior

Error is thrown and VPC Endpoint cannot be created.

### Relevant Error/Panic Output Snippet

```shell
Error: UnsupportedOperation: The operation is not supported in this region!
```

### Terraform Configuration Files

```
resource "aws_vpc_endpoint" "s3" {
  vpc_id       = data.aws_vpc.cluster_vpc.id
  service_name = "com.amazonaws.${var.region}.s3"
}
```

### Steps to Reproduce

`terraform apply`

### Important Factoids

When using a `aws_vpc_endpoint` resource with aws terraform provider >= 2.53.0 in the C2S regions (`us-iso*`), an error is thrown stating `UnsupportedOperation`.

### References

Was able to determine this is due to the commit b6be447b8cee8303ab0eeb8543fb57ccccbbfe2e which introduced always setting the `ec2.CreateVpcEndpointInput.TagSpecifications` field. When this is not set, the API call succeeds.

**Comment by mrburrito** [comment]
This is critical functionality. We just upgraded our providers from 2.45.0 to 4.40 and are now unable to create VPC Endpoints for new deployments. Debugging definitely shows tag-on-create is the missing capability as attempting to create an endpoint using the `aws` CLI fails if the `--tag-specifications` attribute is provided.

Please revert to the legacy <2.53.0 behavior for this resource when the partition is `aws-iso` and/or region is `us-iso-east-1` and, if tags are specified in the HCL, create the endpoint first, then apply tags.

**Comment by mrburrito** [comment]
Hacky workaround for those stuck until this is resolved:

```
locals {
  vpce_tags = {
    Name = "my-vpce"
    Environment = "dev"
    MyOtherTag = "Some Value"
  }
}

resource "aws_vpc_endpoint" "s3" {
  vpc_id = <vpc_id>
  service_name = <s3 service name>
  policy = <endpoint policy>
  lifecycle {
    ignore_changes = [tags]
  }
}

resource "aws_ec2_tag" "s3_endpoint_tag" {
  for_each = local.vpce_tags
  resource_id = aws_vpc_endpoint.s3.id
  key = each.key
  value = each.value
}
```

**Comment by jar-b** [comment]
We've merged #31801 in hopes of resolving this (to be released tomorrow in `v5.2.0`). Without the ability to test in ISO partitions, we will keep this issue open until confirmation of the fix is received. Please let us know if this resolves the issue!

**Comment by jrsherry** [comment]
@jar-b I can confirm that this issue is now resolved.  Thanks!

**Comment by jar-b** [comment]
Thanks for confirmation, @jrsherry! With this report, we'll close out the issue.
