### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by nuriza007** [hashicorp/terraform-provider-aws#27074]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/identitystore_group

### Description

```
resource "aws_identitystore_group" "this" {
  display_name      = "Example group"
  description       = "Example description"
  identity_store_id = tolist(data.aws_ssoadmin_instances.example.arns)[0]
}
```
This block is incorrect because "identity_store_id" has a value as an arn. 

```
The following changes made it work
resource "aws_identitystore_group" "this" {
  display_name      = "Example group"
  description       = "Example description"
  identity_store_id = tolist(data.aws_ssoadmin_instances.example.identity_store_ids)[0]
}
```

**Comment by ewbankkit** [comment]
@nuriza007 Thanks for raising this issue 👏.
The relevant documentation has been corrected via https://github.com/hashicorp/terraform-provider-aws/pull/27052 and will be available after **v4.34.0** of the Terraform AWS Provider has been released.
