### ISSUE TITLE
[Repo]: apply `hacktoberfest` label

### ISSUE THREAD

**Issue by strugee** [hashicorp/terraform-provider-aws#27078]
### Description

Basically what the title says - my impression is that Hashicorp is down with Hacktoberfest since several other repositories in the org have the label, and there have been several references to Hacktoberfest in previous issues here. So the label just needs to be applied.

### References

Repos need the `hacktoberfest` label to opt-in since 2020: https://hacktoberfest.com/participation/#pr-mr-details

### Would you like to implement a fix?

No

**Comment by breathingdust** [comment]
Hey @strugee! As you've probably figured out we aren't participating in Hacktoberfest this year though we have done in the past, maybe next year!
