### ISSUE TITLE
[Enhancement]: Support enabling IMDSv2 by default for AMIs

### ISSUE THREAD

**Issue by christophetd** [hashicorp/terraform-provider-aws#27083]
### Description

AWS Just introduced the capability to enable IMDSv2 when an EC2 instance is created from specific AMIs: 
https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-machine-images-support-instance-metadata-service-version-2-default/

### Affected Resource(s) and/or Data Source(s)

* [aws_ami](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ami)
* [aws_ami_copy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ami_copy)
* [aws_ami_from_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/aws_ami_from_instance)

### Potential Terraform Configuration

```terraform
resource "aws_ami" "example" {
  name                = "terraform-example"
  virtualization_type = "hvm"
  root_device_name    = "/dev/xvda"
  imds_support        = "v2.0"

  ebs_block_device {
    device_name = "/dev/xvda"
    snapshot_id = "snap-xxxxxxxx"
    volume_size = 8
  }
}
```

### References

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RegisterImage.html#API_RegisterImage_RequestParameters (see parameter `ImdsSupport`)

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-IMDS-new-instances.html#configure-IMDS-new-instances-ami-configuration

### Would you like to implement a fix?

Yes

**Comment by ewbankkit** [comment]
Requires [AWS SDK for Go v1.44.110](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.110): https://github.com/hashicorp/terraform-provider-aws/pull/27080.
