### ISSUE TITLE
[Docs]: In aws_rds_cluster data source not is exported "tags_all" parameter, it's exported "tag" parameter.

### ISSUE THREAD

**Issue by tomas-pablos** [hashicorp/terraform-provider-aws#27090]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/rds_cluster

### Description

In the _Attribute Reference_ section, it is indicated that "_See the RDS Cluster Resource for details on the returned attributes - they are identical._" but the "**tags_all**" parameter is not returned in the data resource, "**tag**" is returned.

```
Error: Unsupported attribute
  
      on outputs.tf line 25, in output "instance_tags":
      25:     value = try(data.aws_db_instance.instance[0].tags, data.aws_rds_cluster.cluster[0].tags_all,"")
  
    This object has no argument, nested block, or exported attribute named
    "tags_all".
```

**Comment by thomasgouveia** [comment]
I'm working on a fix for this !
