### ISSUE TITLE
Inline EBS block device modification on AWS instance not working

### ISSUE THREAD

**Issue by szczad** [hashicorp/terraform-provider-aws#2709]
### Terraform Version
Terraform v0.11.1
+ provider.aws v1.6.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- aws_ebs_volume (potentially)

### Terraform Configuration Files
Example configuration that should work. Modifications around "delete_on_termination" (true, false) and "volume_size" (ie. from 100 to 200):
```hcl
resource "aws_instance" "instance" {
  ami                     = "${aws_ami.my.id}"
  instance_type           = "t2.small"
  availability_zone       = "${aws_subnet.private.availability_zone}"
  subnet_id               = "${aws_subnet.private.id}"

  ebs_block_device = [
    {
      device_name           = "/dev/sdb"
      encrypted             = true
      volume_type           = "gp2"
      volume_size           = 100
      delete_on_termination = false
    },
    {
      device_name           = "/dev/sdc"
      encrypted             = true
      volume_type           = "gp2"
      volume_size           = 100
      delete_on_termination = false
    },
  ]
}
```

### Debug Output
```
------------------------------------------------------------------------         
                                                                                 
An execution plan has been generated and is shown below.                         
Resource actions are indicated with the following symbols:                       
  ~ update in-place                                                              
                                                                                 
Terraform will perform the following actions:                                    
                                                                                 
  ~ aws_instance.instance
      ebs_block_device.#:                                "2" => "2"
      ebs_block_device.2554893574.delete_on_termination: "true" => "false"
      ebs_block_device.2554893574.device_name:           "/dev/sdc" => "/dev/sdc"
      ebs_block_device.2554893574.encrypted:             "true" => "true" 
      ebs_block_device.2554893574.snapshot_id:           "" => <computed>
      ebs_block_device.2554893574.volume_size:           "100" => "100"
      ebs_block_device.2554893574.volume_type:           "gp2" => "gp2"
      ebs_block_device.2576023345.delete_on_termination: "true" => "false"
      ebs_block_device.2576023345.device_name:           "/dev/sdb" => "/dev/sdb"
      ebs_block_device.2576023345.encrypted:             "true" => "true"
      ebs_block_device.2576023345.snapshot_id:           "" => <computed>
      ebs_block_device.2576023345.volume_size:           "100" => "100"
      ebs_block_device.2576023345.volume_type:           "gp2" => "gp2"

Plan: 0 to add, 1 to change, 0 to destroy.                                                                              
```

### Expected Behavior
Modyfing EBS volume's volume_size or delete_on_termination attributes TF shall modify underlying volumes. This bug might affect other EBS block devices' attributes as well (not tested)

### Actual Behavior
If modifying AWS instance's EBS volumes inline Terraform generates change plan which does nothing when applied.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -out output.plan`
2. `terraform apply output.plan`
3. `terraform plan -out output.plan`

**Comment by duckfez** [comment]
Current docs say these types of changes are not currently detected by Terraform and would require a taint against the instance itself (https://www.terraform.io/docs/providers/aws/r/instance.html) 

> NOTE: Currently, changes to *_block_device configuration of existing resources cannot be automatically detected by Terraform. After making updates to block device configuration, resource recreation can be manually triggered by using the taint command.

From what I can tell attempting to reproduce this, the behaviour of Terraform is working as per the docs.

**Comment by camerondavison** [comment]
even if this is working as documented, i feel like maybe it should not output the fact that something is going to change.

**Comment by duckfez** [comment]
That wasn't the behavior I saw when trying to reproduce this.  I got a no-change plan.    (Or at least I think I did, it's been a short bit)  @szczad can you attempt to reproduce this with latest TF and AWS provider and see what you get?

**Comment by KyMidd** [comment]
Team, could we keep this open since this behavior is unexpected (updating a nested EBS disk shouldn't cause an instance rebuild) and potentially catastrophic (updating a nested EBS disk shouldn't destroy all other disks and rebuild)? 

For anyone else running into this issue, you can avoid by using separate EBS resource. I created a relatively built-out ec2 instance module that does this for you, I manage several hundred instances using this module. 

[Github module link](https://github.com/KyMidd/Terraform-AWS-EC2-Instance-Module)
[Blog about it](https://faun.pub/lets-do-devops-terraform-aws-ec2-module-required-b80180dc13ec)
[Paywall bypass link](https://faun.pub/lets-do-devops-terraform-aws-ec2-module-required-b80180dc13ec?source=friends_link&sk=4b3733850e896939bd1fdb8f4417260a)
