### ISSUE TITLE
resource/aws_elasticache_replication_group: Add plan-time validation for `automatic_failover_enabled` and number of cache clusters

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#27116]
### Description

The resource `aws_elasticache_replication_group` should have a plan-time validation to ensure that there are at least 2 cache clusters when `automatic_failover_enabled` is `true`

### Affected Resource(s) and/or Data Source(s)

* aws_elasticache_replication_group

**Comment by g3sppadrq64y66c7** [comment]
This breaks our cluster-mode enabled single-instance (testing) environments:

> │ Error: modifying ElastiCache Replication Group ([redacted]): operation error ElastiCache: ModifyReplicationGroup, https response error StatusCode: 400, RequestID: [redacted], InvalidParameterCombination: Turning off automatic failover for replication group with cluster mode enabled is not supported.
