### ISSUE TITLE
[Docs]: Output section missing

### ISSUE THREAD

**Issue by spirosag** [hashicorp/terraform-provider-aws#27122]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_cluster

### Description

Is it me or for every aws terraform resource there used to be a section in the documentation with the output values that this resource would expose?
Also you could navigate to the same documentation page of a previous version of aws provider but this is missing too.

**Comment by mattburgess** [comment]
1. I think that's covered under the [Attributes Reference](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_cluster#attributes-reference) section, which starts: "In addition to all arguments above, the following attributes are exported:"
2. There's a link underneath the search box where you can change the version of the docs you're viewing, it looks like "Providers / hashicorp / aws / Version 4.33.0"

**Comment by gdavison** [comment]
Thank you for responding to this, @mattburgess
