### ISSUE TITLE
[Enhancement]: aws_grafana_workspace id attribute not being able to be in the output

### ISSUE THREAD

**Issue by maxkoko-co** [hashicorp/terraform-provider-aws#27126]
### Description

Id of aws_grafana_workspace is in terraform state already but reading it via terraform is not exposed which blocks me from using grafana provider data source which is finding aws_grafana_workspace by id. 

### Affected Resource(s) and/or Data Source(s)

aws_grafana_workspace

**Comment by bschaatsbergen** [comment]
Hi @maxkoko-co, thanks for raising this issue. Could you please provide some more information and concrete examples, this makes it easier for us to both understand and debug your issue.

Thanks!
