### ISSUE TITLE
[Enhancement]: Support enabling NAU metrics in "aws_vpc" resource

### ISSUE THREAD

**Issue by mkielar** [hashicorp/terraform-provider-aws#27139]
### Description

AWS has just released two new CloudWatch Metrics for VPC to measure and track network address usage. More here:
- [Announcement][announcement]
- [Documentation][docs]

Long story short, you can now enable additional metrics by running [modify-vpc-attribute](https://docs.aws.amazon.com/cli/latest/reference/ec2/modify-vpc-attribute) on the VPC and specifying additional flag: `--enable-network-address-usage-metrics`. 

There's also [relevant change in API][api] - new `bool` attribute: `EnableNetworkAddressUsageMetrics`.

Since other flags managed by this API call are already managed by Terraform `aws_vpc` resource (e.g. `enable_dns_support`), it feels only right to extend existing implementation with new flag.

[announcement]: https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-virtual-private-cloud-vpc-now-supports-new-cloudwatch-metrics-measure-track-network-address-usage/
[docs]: https://docs.aws.amazon.com/vpc/latest/userguide/vpc-cloudwatch.html
[api]: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyVpcAttribute.html

### Affected Resource(s) and/or Data Source(s)

* `aws_vpc`

### Potential Terraform Configuration

```terraform
resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"

  enable_network_address_usage_metrics = true   ### New flag.
}
```

### References

- [Announcement][announcement]
- [Documentation][docs]
- [API][api]

[announcement]: https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-virtual-private-cloud-vpc-now-supports-new-cloudwatch-metrics-measure-track-network-address-usage/
[docs]: https://docs.aws.amazon.com/vpc/latest/userguide/vpc-cloudwatch.html
[api]: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyVpcAttribute.html

**Comment by bschaatsbergen** [comment]
Thanks for raising this issue @mkielar, I'll pick this up.

**Comment by bschaatsbergen** [comment]
Requires [v1.44.111  ](https://github.com/aws/aws-sdk-go/pull/4576) of the [aws-sdk-go](https://github.com/aws/aws-sdk-go).

**Comment by bschaatsbergen** [comment]
PR is ready for review 👍
