### ISSUE TITLE
[Bug]: datasource aws_identitystore_user does no longer work with provider 4.34

### ISSUE THREAD

**Issue by andreas-moor** [hashicorp/terraform-provider-aws#27145]
### Terraform Core Version

1.2.3

### AWS Provider Version

4.34

### Affected Resource(s)

data.aws_identitystore_user

### Expected Behavior

read the data source

### Actual Behavior

│ Error: setting AWS SSO Identity Store User Data Source (996718ce8d-f3c5e163-2e16-4b3a-ab10-b0957038a5f5): external_ids.0.id: '' expected type 'bool', got unconvertible type 'string', value: '91d3e866-dc1e-4adf-b1ec-194ac982464b'
│
│   with module.sso_customers["xxx"].data.aws_identitystore_user.sso_admin_users["xxxx"],
│   on .terraform/modules/sso_customers/main.tf line 19, in data "aws_identitystore_user" "sso_admin_users":
│   19: data "aws_identitystore_user" "sso_admin_users" {

### Terraform Configuration Files
locals {
 sso_admin_user_list = ["xxxx"]
}

data "aws_identitystore_user" "sso_admin_users" {
  for_each = toset(local.sso_admin_user_list)

  identity_store_id = var.sso_identity_store_id

  alternate_identifier {
    unique_attribute {
      attribute_path = "UserName"
      # workaround because UserName is cut off at 54 characters (most likely by azure scim sync)
      attribute_value = substr(each.value, 0, 54)
    }
  }
}

### Steps to Reproduce

try to use https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/identitystore_user with aws  provider 4.34

### References

PR which broke it:
https://github.com/hashicorp/terraform-provider-aws/pull/27053/files#diff-104abae312dd3297b48407435c9b297e4c7293291fb6c0de28949fee509dd0be

**Comment by demolitionmode** [comment]
Likely cause is https://github.com/hashicorp/terraform-provider-aws/pull/27053/files#diff-104abae312dd3297b48407435c9b297e4c7293291fb6c0de28949fee509dd0beR141 being set to `TypeBool` instead of `TypeString`

**Comment by bschaatsbergen** [comment]
I'll see if I can prep a quick fix for this.

**Comment by bschaatsbergen** [comment]
Prepping a fix for this.
