### ISSUE TITLE
[Bug]: aws_cloudwatch_log_metric_filter name is deprecated

### ISSUE THREAD

**Issue by jrobison-sb** [hashicorp/terraform-provider-aws#27152]
### Terraform Core Version

1.3.2

### AWS Provider Version

4.34.0

### Affected Resource(s)

* aws_cloudwatch_log_metric_filter

### Expected Behavior

Attributes should not be both required and deprecated

### Actual Behavior

An attribute is indeed required and also deprecated.

### Relevant Error/Panic Output Snippet

```shell
The attribute "name" is deprecated. Refer to the provider documentation for details
```

### Terraform Configuration Files

```
resource "aws_cloudwatch_log_metric_filter" "foo" {
  name = "foo"
  ...
}
```

### Steps to Reproduce

Try to use a `name` attribute with `aws_cloudwatch_log_metric_filter`, which is a required attribute. You'll get a deprecation warning saying:

```
The attribute "name" is deprecated. Refer to the provider documentation for details.
```

Then if you get rid of the `name` attribute to appease the deprecation warning, you get a blocking error because `name` is a required attribute:

```
│ Error: Missing required argument
│ 
│ The argument "name" is required, but no definition was found.
```

### Important Factoids

Note that this situation only surfaced upon upgrading to Terraform 1.3.2. Previously when I was on 1.2.0 I was able to use the `name` attribute without any deprecation warnings or errors.

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @jrobison-sb 👋 Thank you for taking the time to raise this! Can you test with Terraform 1.3.3 as well, to see if the issue persists? I don't see anything in the changelog that necessarily indicates that 1.3.3 might fix it, but I've seen a couple of other issues that (if I recall correctly) were cleared up with this upgrade. The `name` argument hasn't been deprecated, so that error message certainly seems a bit odd.

**Comment by jrobison-sb** [comment]
@justinretzolk thanks for your reply.

Upon further review, this is just poor reading comprehension on my part. I have a `aws_cloudwatch_log_metric_filter` resource which uses interpolation of other resources to set the names of each filter, like this:

```
resource "aws_cloudwatch_log_metric_filter" "foo" {
  name           = "${aws_db_instance.foo.name}-metric"
  ...
}
```

The deprecation warning flagged that `name` was deprecated and that the deprecation involved `aws_cloudwatch_log_metric_filter`. But I now see that `name` is deprecated for `aws_db_instance` (the resource I am interpolating from, not the `aws_cloudwatch_log_metric_filter` resource that is being built with the above code).

So I just need to fix my `aws_db_instance` name attributes. I'll close this now. Thanks for taking a look.
