### ISSUE TITLE
[Enhancement]: Availability of "Target failover" and "Flow stickiness" under aws_lb_target_group resource

### ISSUE THREAD

**Issue by saurabh19n** [hashicorp/terraform-provider-aws#27153]
### Description

AWS released two new attributes for Gateway load balancer target group. Request to add those under aws_lb_target_group resource in terraform provider similar to deregistration_delay parameter.

Documentation: https://docs.aws.amazon.com/elasticloadbalancing/latest/gateway/target-groups.html#target-group-attributes

![image](https://user-images.githubusercontent.com/76001430/194580641-553f5c43-3eda-4448-b378-fb80d4ec3754.png)

![image](https://user-images.githubusercontent.com/76001430/194581315-b642d988-7536-40d5-8ece-f43310525bcc.png)

### Affected Resource(s) and/or Data Source(s)

aws_lb_target_group

### Potential Terraform Configuration

```terraform
resource "aws_lb_target_group" "test" {
  name     = "tf-example-lb-tg"
  port     = 80
  protocol = "HTTP"
  target_failover = "rebalance"   ##Probable values## "rebalance" or "no-rebalance"
  stickiness {
     enabled = "true"
     type = "source_ip_dest_ip"  ##Probable values## "source_ip_dest_ip", "source_ip_dest_ip_proto"
     }
  vpc_id   = <id>
}
```

**Comment by ddericco** [comment]
This is being worked on.

**Comment by saurabh19n** [comment]
Thanks @ddericco

**Comment by saurabh19n** [comment]
Thanks @ewbankkit for the quick release.
