### ISSUE TITLE
[Bug]: Unexpected behavior in aws_instances module 

### ISSUE THREAD

**Issue by dasanirban834** [hashicorp/terraform-provider-aws#27167]
### Terraform Core Version

1.2.4

### AWS Provider Version

4.34.0

### Affected Resource(s)

While trying to fetch instance-ids of couple of servers using this TF resource, it' simply showing blank.  Using 'ids' as an attribute, I was trying to get instance ids.

```terraform
// =================
// data.tf :
// =================

data "aws_instances" "this_ec2" {
  filter {
    name   = "tag:Name"
    values = ["vm-public", "vm-private"]
  }
}
```

```terraform
// =================
// output.tf
// =================

output "v" {
  value = data.aws_instances.this_ec2.ids
}
```

```shell
# =================
# Terraform Output:
# =================

$ terraform plan
data.aws_instances.this_ec2: Reading...
data.aws_instances.this_ec2: Read complete after 1s [id=us-east-1]

Changes to Outputs:
  + v = []

You can apply this plan to save these new output values to the Terraform state, without changing any real
infrastructure.
```

### Expected Behavior

It should provide instance ids of two mentioned instances above.

### Actual Behavior

It's giving blank. Let me know if I have made any mistakes.

$ terraform plan
data.aws_instances.this_ec2: Reading...
data.aws_instances.this_ec2: Read complete after 1s [id=us-east-1]

Changes to Outputs:
  + v = []

You can apply this plan to save these new output values to the Terraform state, without changing any real
infrastructure.

### Terraform Configuration Files

```terraform 
// =================
// data.tf :
// =================

data "aws_instances" "this_ec2" {
  filter {
    name   = "tag:Name"
    values = ["vm-public", "vm-private"]
  }
}
```

```terraform
// =================
// output.tf
// =================

output "v" {
  value = data.aws_instances.this_ec2.ids
}
```

### Steps to Reproduce

terraform init >> terraform plan

**Comment by justinretzolk** [comment]
Hey @dasanirban834 👋 Thank you for taking the time to raise this! Would it be possible to supply debug logs as well (redacted as necessary), so that we have a bit more information to try to look into this?
