### ISSUE TITLE
[Bug]: `aws_security_group` always shown as changed, if `cidr_blocks` is omitted from ingress/egress rules

### ISSUE THREAD

**Issue by johanneskastl** [hashicorp/terraform-provider-aws#27196]
### Terraform Core Version

1.3.2

### AWS Provider Version

4.34.0

### Affected Resource(s)

- aws_security_group

### Expected Behavior

As the parameter `cidr_blocks` is not required for `ingress`/`egress` and is stated as optional [in the documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group), omitting it should result in it being added with the default value of `["0.0.0.0/0"]`. And the security group should only be created once and never be modified afterwards.

### Actual Behavior

The security group is shown as changed, each time `terraform apply` is being run:

```
aws_vpc.terraform: Refreshing state... [id=vpc-01b3a292077d7afd3]
aws_security_group.terraform: Refreshing state... [id=sg-0b74d8a09a24d6d5b]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_security_group.terraform will be updated in-place
  ~ resource "aws_security_group" "terraform" {
      ~ egress                 = [
          + {
              + cidr_blocks      = []
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
        id                     = "sg-0b74d8a09a24d6d5b"
      ~ ingress                = [
          + {
              + cidr_blocks      = []
              + description      = ""
              + from_port        = 22
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 22
            },
        ]
        name                   = "Allow SSH"
        tags                   = {}
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:
```

This can be repeated endlessly (not that I tested it that long).

## Working (i.e. resource not shown as changed on subsequent runs)
```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

provider "aws" {
  region = "eu-central-1"
}

resource "aws_vpc" "terraform" {
  cidr_block = "172.16.0.0/16"
}

resource "aws_security_group" "terraform" {
  name        = "Allow SSH"
  vpc_id      = aws_vpc.terraform.id

  ingress {
    from_port        = 22
    to_port          = 22
    protocol         = "tcp"
    cidr_blocks      = ["0.0.0.0/0"]
  }

  egress {
    from_port        = 0
    to_port          = 0
    protocol         = "all"
    cidr_blocks      = ["0.0.0.0/0"]
  }
}
```

## Non-working Example (resource shown as changed on each subsequent run)

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

provider "aws" {
  region = "eu-central-1"
}

resource "aws_vpc" "terraform" {
  cidr_block = "172.16.0.0/16"
}

resource "aws_security_group" "terraform" {
  name        = "Allow SSH"
  vpc_id      = aws_vpc.terraform.id

  ingress {
    from_port        = 22
    to_port          = 22
    protocol         = "tcp"
  }

  egress {
    from_port        = 0
    to_port          = 0
    protocol         = "all"
  }
}
```

### Steps to Reproduce

Run `terraform apply` twice, on the first run VPC and security group will be created. On the second run there is a difference.

If `cidr_blocks` is set, no change is necessary and all is up to date.

If `cidr_blocks` is omitted, the security group is shown as changed.

**Comment by aidanmelen** [comment]
There is a note in the docs that the AWS API automatically add egress all 0.0.0.0/0 and this resource removes it. You will need to explicitly add it.

I would expect this resource produce nothing when supplied with empty lists. I am surprised that it didn't trigger an error like when passing null.

**Comment by johanneskastl** [comment]
> There is a note in the docs that says the EC2 API will create a security group with the egress all to 0.0.0.0/0 and this TF resource removes it. You will need to explicitly add it.

I read that, but I understood it that an `egress` rule is not being added automatically by Terraform, if the user does not specify one.
The example above does specify one, so that should not be the reason.

In addition, also the `ingress` rule is being shown as changed.

```
  # aws_security_group.terraform will be updated in-place
  ~ resource "aws_security_group" "terraform" {
      ~ egress                 = [
[...]
      ~ ingress                = [
[...]
```
