### ISSUE TITLE
[Docs]: Typo in arguments for aws_network_interface

### ISSUE THREAD

**Issue by ryan-cpi** [hashicorp/terraform-provider-aws#27251]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/network_interface#attachment

### Description

`ipv6_address_list_enable` should be `ipv6_address_list_enabled` for the people who blindly copy paste

```
│ Error: Unsupported argument
│ 
│ An argument named "ipv6_address_list_enable" is not expected here. Did you
│ mean "ipv6_address_list_enabled"?
```

**Comment by jar-b** [comment]
Thanks for reporting @ryan-cpi 👍
