### ISSUE TITLE
[Bug]: Support pagination for data source aws_ec2_managed_prefix_list

### ISSUE THREAD

**Issue by sl-miguelmichee** [hashicorp/terraform-provider-aws#27255]
### Terraform Core Version

1.3.2

### AWS Provider Version

4.22.0

### Affected Resource(s)

data source: aws_ec2_managed_prefix_list

### Expected Behavior

iterating on over 100 results to return with a single call

### Actual Behavior

Error: no managed prefix lists matched the given criteria

  with data.aws_ec2_managed_prefix_list.this,
  on data.tf line 32, in data "aws_ec2_managed_prefix_list" "this":
  32: data "aws_ec2_managed_prefix_list" "this" {

### Terraform Configuration Files

data "aws_ec2_managed_prefix_list" "this" {
  filter {
    name   = "prefix-list-name"
    values = ["internal.aviv_ipv4"]
  }
}

### Steps to Reproduce

terraform plan with over 100 prefixlists on the AWS account

### References

MaxResults
The maximum number of results to return with a single call. To retrieve the remaining results, make another call with the returned nextToken value.

Type: Integer

Valid Range: Minimum value of 1. Maximum value of 100.

Required: No

doc: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeManagedPrefixLists.html

**Comment by ewbankkit** [comment]
@sl-miguelmichee Thanks for raising this issue.

The underlying problem was fixed via https://github.com/hashicorp/terraform-provider-aws/pull/26683 and released in [**v4.30.0** of the Terraform AWS Provider](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#4300-september--9-2022).
