### ISSUE TITLE
[Enhancement]: dynamodb import table from S3

### ISSUE THREAD

**Issue by bengisc** [hashicorp/terraform-provider-aws#27250]
### Description

It is now possible to [import Amazon S3 data into a new table](https://aws.amazon.com/blogs/database/amazon-dynamodb-can-now-import-amazon-s3-data-into-a-new-table/). The API is also [up-to-date](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_ImportTable.html).

I am already using the import in production and I identified some important considerations:
- import can take a long time (IE; for "only" 10 Gb it takes up to 2 hours); how to handle very long imports ?
- the import leads to the creation of a brand new table. The `import_table` block must be interpreted only at the first deployment; further applies should only take into account the other arguments of the `aws_dynamodb_table` resource

At the moment, the only way to import a table from S3 and to manage it using terraform is to create the table outside terraform (manually / cli / api / sdks), and to import it in the state.

### Affected Resource(s) and/or Data Source(s)

aws_dynamodb_table

### Potential Terraform Configuration

```terraform
resource "aws_dynamodb_table" "test-import-table" {
  name             = "my-imported-table"
  hash_key         = "id"

  billing_mode   = "PROVISIONED"
  write_capacity = 5
  read_capacity  = 5

  attribute {
    name = "id"
    type = "S"
  }

  ttl {
    attribute_name = "date"
    enabled        = true
  }

  import_table {
    client_token = "some_random_string"
    input_compression_type = "GZIP"
    input_format = "DYNAMODB_JSON"

    s3_bucket_source {
      s3_bucket = "my_s3_bucket"
      s3_key_prefix = "some_prefix/"
      s3_bucket_owner = "some_account"
    }
  }
}
```

### References

[API Reference](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_ImportTable.html)
[AWS Blog Article](https://aws.amazon.com/blogs/database/amazon-dynamodb-can-now-import-amazon-s3-data-into-a-new-table/)

### Would you like to implement a fix?

Yes

**Comment by aaqibjaved** [comment]
Hey team , any update on this feature? Any ETA when it can be available? Our project needs a similar solution urgently.
