### ISSUE TITLE
[Bug]: aws_sagemaker_app still get persisted in spite of failure state

### ISSUE THREAD

**Issue by hungluong5791** [hashicorp/terraform-provider-aws#27265]
### Terraform Core Version

1.2.9

### AWS Provider Version

4.34.0

### Affected Resource(s)

During the provisioning of `aws_sagemaker_app` if there is an error that put the App in a `Failed` state (i.e a Lifecycle Configuration script error), the `aws_sagemaker_app` is still persisted in the Terraform state. This results in error trying to refresh its status in subsequent runs

### Expected Behavior

`aws_sagemaker_app` in a `Failed` state should not be persisted in the Terraform state

### Actual Behavior

`aws_sagemaker_app` in a `Failed` stabe persisted in the Terraform state, requiring manual removal to re-create

### Relevant Error/Panic Output Snippet

```shell
│ Error: waiting for SageMaker App (redacted) to create: unexpected state 'Failed', wanted target 'InService'. last error: %!s(<nil>)
│ 
│   with aws_sagemaker_app.jupyter,
│   on sagemaker.tf line 60, in resource "aws_sagemaker_app" "jupyter":
│   60: resource "aws_sagemaker_app" "jupyter" {

---

aws_sagemaker_app.jupyter: Refreshing state... [redacted]
╷
│ Error: listing tags for SageMaker App (redacted): ValidationException: 
│       status code: 400, request id: redacted
│ 
│   with aws_sagemaker_app.jupyter,
│   on sagemaker.tf line 60, in resource "aws_sagemaker_app" "jupyter":
│   60: resource "aws_sagemaker_app" "jupyter" {
```

### Terraform Configuration Files

https://gist.github.com/hungluong5791/4836adc3832c8b285dab635d6cf32d91

### Steps to Reproduce

- Plan + apply the configuration with error in the lifecycle configuration script- 
- Observe the error stating failure in waiting for SageMaker App
- Plan + apply the configuration again
- Observe the bug:
- a) the failed SageMaker app is in the state and still get refreshed
- b) an error listing tags for the failed SageMaker app (as it doesn't exists due to failure in provisioning)

**Comment by DrFaust92** [comment]
Hi [hungluong5791](https://github.com/hungluong5791), would you mind sharing an example for a failing config to reproduce?

**Comment by hungluong5791** [comment]
Hi @DrFaust92, working config is here: [Gist](https://gist.github.com/hungluong5791/4836adc3832c8b285dab635d6cf32d91)

**Comment by JohnPaton** [comment]
I'm hitting the same issue, any workaround? I tried to `ignore_changes = [tags]`, but that was not enough to stop this query which is 400ing.

**Comment by hungluong5791** [comment]
Hi @JohnPaton, the only workaround I have is delete the App in question and recreate, using `-target` option i.e

    terraform plan -destroy -target aws_sagemaker_app.jupyter
