### ISSUE TITLE
Resource: aws_ec2_transit_gateway_connect_peer incorrect argument type

### ISSUE THREAD

**Issue by LvrongLin** [hashicorp/terraform-provider-aws#27268]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_transit_gateway_connect_peer

### Description

In the example the argument is a string. 
  inside_cidr_blocks            = "169.254.100.0/29"

When running tf code with exact same type, it returns an error to exepct for a set. Changing resource to set didn't fix the error. However, tf takes the value with type list. 
  inside_cidr_blocks            = ["169.254.100.0/29"]

The type  and error seems to be incorrect. I would expect terraform to accept string for this argument.

**Comment by bschaatsbergen** [comment]
Fixed in https://github.com/hashicorp/terraform-provider-aws/pull/27168. Can be closed @justinretzolk ✌️

**Comment by bschaatsbergen** [comment]
Thanks for raising this issue @LvrongLin.
