### ISSUE TITLE
Feature request: Support Api Gateway Canary release

### ISSUE THREAD

**Issue by lemaral** [hashicorp/terraform-provider-aws#2727]
There is now additional support to Api Gateway for Canary deployment as described here:
https://docs.aws.amazon.com/apigateway/latest/developerguide/canary-release.html
It would be great to have this in Terraform too.
Thanks

**Comment by AlexRudd** [comment]
This should be added to `aws_api_gateway_stage` and `aws_api_gateway_deployment` to match api https://docs.aws.amazon.com/apigateway/api-reference/link-relation/deployment-create/

**Comment by azizbodal** [comment]
Is this working yet?

**Comment by codigube** [comment]
is feature included in Terraform?

**Comment by SanjuMLGeek** [comment]
is this feature included in Terraform?

**Comment by jeromevdl** [comment]
What is the status of this request? Doesn't look available.

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!
