### ISSUE TITLE
[Bug]: Unable to create ecs service with external controller and loadbalancers configuration block

### ISSUE THREAD

**Issue by rsmolinski** [hashicorp/terraform-provider-aws#27291]
### Terraform Core Version

1.3.1

### AWS Provider Version

4.35.0

### Affected Resource(s)

aws_ecs_service

### Expected Behavior

Load balancer is attached to the service

### Actual Behavior

Creating ecs service with  external deployment controller and load_balancer  configuration: 

 `Error: error creating ECS service (test): InvalidParameterException: LoadBalancers must be empty or null.`

### Terraform Configuration Files

```
resource "aws_ecs_service" "test" {
  name            = "test"
  cluster         = aws_ecs_cluster.tf-test-cluster.id
  desired_count   = 2

  network_configuration {
    security_groups = [aws_security_group.tf-test-tasks.id]
    subnets         = var.vpc_private_subnets
  }

  deployment_controller {
    type = "EXTERNAL"
  }

  load_balancer {
    target_group_arn = aws_alb_target_group.tf-test-tg.arn
    container_name   = "test"
    container_port   = 3000
  }

  depends_on = [
    aws_alb_listener.tf-test-listener
  ]
}
```

### Steps to Reproduce

Deploy ecs service with  external deployment controller and configuration block for load balancers

**Comment by WillGreen** [comment]
I'm having a similar issue that started today (2022-10-18). But our deployment controller type is CodeDeploy:

```YAML
 deployment_controller {
    type = "CODE_DEPLOY"
  }
```

In a possibly related issue, we're also seeing issues updating existing ECS services (despite not making any changes to our Terraform configuration):

```shell
Error: modifying ELBv2 Listener (arn:aws:elasticloadbalancing:us-west-2:****): ValidationError: A target group ARN must be specified
```

I have retested with Terraform 1.3.2 and AWS Provider 4.35.0 but am still having issues.

**Comment by ferschubert-hm** [comment]
I am also seeing this, the behavior I have is that previously CodeDeploy kept both targets associated with the ALB listener, with different weights (100% active, 0% secondary) and now the secondary (not active) Target Group is simply removed. 

This started somewhere in the last week or so, I do not see changes related to this in the TF AWS provider 4.35.0 so my assumption goes to something changed on AWS CodeDeploy service (but could not find any clear evidence/changelog).
