### ISSUE TITLE
[Bug]: aws_fis_experiment_template should support resource of type EKS Cluster

### ISSUE THREAD

**Issue by dhishanbbg** [hashicorp/terraform-provider-aws#27314]
### Terraform Core Version

1.0.4

### AWS Provider Version

4.35

### Affected Resource(s)

`aws_fis_experiment_template` should allow targets of type EKS cluster for the fis action 'aws:eks:inject-kubernetes-custom-resource`. Currently the resource only supports the types [Clusters DBInstances Instances SpotInstances Nodegroups Roles] and does not support the type "Cluster" for selecting a aws eks resource. 

### Expected Behavior

EKS clusters should be allowed to be targeted in aws fis templates as documented here: https://docs.aws.amazon.com/fis/latest/userguide/fis-actions-reference.html#inject-kubernetes-custom-resource. This is different than the NodeGroups which targets only node groups of the eks clusters

### Actual Behavior

│ Error: expected action.0.target.0.key to be one of [Clusters DBInstances Instances SpotInstances Nodegroups Roles], got Cluster
│
│   with aws_fis_experiment_template.fis_eks_fault["terminate-pod"],
│   on fis-eks-faults.tf line 1, in resource "aws_fis_experiment_template" "fis_eks_fault":
│    1: resource "aws_fis_experiment_template" "fis_eks_fault" {
│
╵

### Terraform Configuration Files

resource "aws_fis_experiment_template" "fis_eks_fault" {
  description = format("Inject %s Fault Into EKS Cluster",var.kubernetes_kind)
  role_arn    = var.fis_role_arn 

  action {
    name      = var.kubernetes_kind
    action_id = "aws:eks:inject-kubernetes-custom-resource"

    target {
      key   = "Cluster" # Errors out
      value = "eksCluster"
    }

    parameter {
      key   = "kubernetesApiVersion"
      value = "chaos-mesh.org/v1alpha1"
    }

    parameter {
      key   = "kubernetesKind"
      value = var.kubernetes_kind
    }

    parameter {
      key   = "kubernetesNamespace"
      value = var.kubernetes_namespace
    }

    parameter {
      key   = "kubernetesSpec"
      value = jsonencode(var.kubernetes_spec)
    }

    parameter {
      key   = "maxDuration"
      value = var.max_duration
    }
  }

  target {
    name           = "eksCluster"
    resource_type  = "aws:eks:cluster"
    selection_mode = "ALL"
    resource_arns  = [var.eks_cluster_arn]
  }
}

### Steps to Reproduce

Try to deploy an fis experiment for an eks cluster. Document:
https://docs.aws.amazon.com/fis/latest/userguide/fis-actions-reference.html#inject-kubernetes-custom-resource

**Comment by akshaychopra5207** [comment]
We ran into this same issue today running terraform 1.3.2 and aws provider 4.3420. I went ahead and updated the validExperimentTemplateActionTargetKey() and tested with acceptance tests, and I was able to successfully deploy our terraform with a aws_fis_experiment_template for EKS Cluster.

Please let me know if there is anything else needed for this.
