### ISSUE TITLE
[Bug]: create glue crawler with delta_target without connection_name

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [hashicorp/terraform-provider-aws#27331]
### Terraform Core Version

1.1.5

### AWS Provider Version

4.24.0

### Affected Resource(s)

aws_glue_crawler

### Expected Behavior

I believe I should be able to create a Glue Crawler that uses a `delta_target` without specifying the `connection_name`; however it is required:
https://github.com/hashicorp/terraform-provider-aws/blob/5b85a5788722607826f2cf8ccc3a84b7cc0c9ffd/internal/service/glue/crawler.go#L225-L228

An [AWS blog post describes this as being optional](https://aws.amazon.com/blogs/big-data/crawl-delta-lake-tables-using-aws-glue-crawlers/#:~:text=An%20optional%20connection%20name). Furthermore, I have manually setup a crawler in the console to use a delta target, the UI shows this connection as being optional:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/8518288/196732826-5a36e515-623b-44f2-b5d9-7c2dce524ba4.png">

The crawler I've setup, without a connection name, successfully crawls S3; introspecting that crawler with `aws glue get-crawler --name "foo" --output json` shows:
```
{
    "Crawler": {
        "Name": "foo",
        "Role": "foo",
        "Targets": {
            "S3Targets": [],
            "JdbcTargets": [],
            "MongoDBTargets": [],
            "DynamoDBTargets": [],
            "CatalogTargets": [],
            "DeltaTargets": [
                {
                    "DeltaTables": [
                        "s3://test-cs-glue-crawler/data/"
                    ],
                    "WriteManifest": true
                }
            ]
        },
        "DatabaseName": "foo",
        "Classifiers": [],
        "RecrawlPolicy": {
            "RecrawlBehavior": "CRAWL_EVERYTHING"
        },
        "SchemaChangePolicy": {
            "UpdateBehavior": "UPDATE_IN_DATABASE",
            "DeleteBehavior": "DEPRECATE_IN_DATABASE"
        },
        "LineageConfiguration": {
            "CrawlerLineageSettings": "DISABLE"
        },
        "State": "READY",
        "CrawlElapsedTime": 0,
        "CreationTime": 1665598443.0,
        "LastUpdated": 1665599113.0,
        "LastCrawl": {
            "Status": "SUCCEEDED",
            "LogGroup": "/aws-glue/crawlers",
            "LogStream": "foo",
            "MessagePrefix": "foo",
            "StartTime": 1665619047.0
        },
        "Version": 2,
        "LakeFormationConfiguration": {
            "UseLakeFormationCredentials": false,
            "AccountId": ""
        }
    }
}
```

Notice how `DeltaTargets` does not return any ConnectionName

### Actual Behavior

Omitting connection_name produces terraform error:
```terraform
╷
│ Error: Missing required argument
│ 
│   on crawler.tf line 60, in resource "aws_glue_crawler" "this":
│   60:   delta_target {
│ 
│ The argument "connection_name" is required, but no definition was found.
╵
```

### Terraform Configuration Files

NA

### Steps to Reproduce

apply resource

### Would you like to implement a fix?

yes

**Comment by olenm** [comment]
a workaround for this is to create a new connection, attach it to: vcp, subnet, and security group giving it full ingress+egress

**Comment by ConstantinoSchillebeeckx** [comment]
FWIW you can provide a blank connection name
```terraform
resource "aws_glue_crawler" "this" {
  database_name = "foo"
  name          = "bar"
  role          = module.crawler_role.iam_role_arn

  delta_target {
    connection_name = ""
    delta_tables    = ["buckets"]
    write_manifest  = true
  }
}
```

**Comment by olenm** [comment]
@ConstantinoSchillebeeckx  thanks, yes this worked for our setup as well. seems like easiest fix currently would be to update documentation then do code-magic later
