### ISSUE TITLE
[Enhancement]:  Support for "Tasks" in AWS FIS Action targets

### ISSUE THREAD

**Issue by sohanj33** [hashicorp/terraform-provider-aws#27353]
### Description

As per the release from 1 march 2022 FIS now supports ECS stop task which take **TASKS** as the Action targets , at presend i dont see that is added .

ERROR : 
│ Error: expected action.0.target.0.key to be one of [Clusters DBInstances Instances SpotInstances Nodegroups Roles], got Tasks
│
│   with module.fis_templates.aws_fis_experiment_template.example[1],
│   on ..\modules\terraform-aws-FIS\lb-w-cw.tf line 1, in resource "aws_fis_experiment_template" "example": 
│    1: resource "aws_fis_experiment_template" "example" {

### References

aws document : https://docs.aws.amazon.com/fis/latest/userguide/actions.html

**Comment by yipsmith** [comment]
any updates?
