### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by su3010** [hashicorp/terraform-provider-aws#27356]
### Description

DataSync options' configuration needs to be enhanced. Please!

### Affected Resource(s) and/or Data Source(s)

DataSync

### References

Please check this implementation and enhance terraform module. at least CopyObjects should be provided. 
https://github.com/hashicorp/terraform-provider-awscc/blob/main/internal/aws/datasync/task_resource_gen.go#L507

**Comment by bschaatsbergen** [comment]
Hi @su3010, thanks for taking the time to raise this issue. Please enhance this issue too with the necessary details to make it easier for someone to pick this up. This also increases your chance of this issue being flagged and picked up faster :)!
