### ISSUE TITLE
[Docs]: cloudfront_distribution

### ISSUE THREAD

**Issue by rajivrnair** [hashicorp/terraform-provider-aws#27357]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution

### Description

The first example on this page contains a resource description for: `resource "aws_cloudfront_distribution" "s3_distribution"` . Under this there is a minor typo,
```
origin {
    ...
    origin_id   = locals.s3_origin_id

    ...
    }
```

`locals.s3_origin_id` should be `local.s3_origin_id` (singular not plural).

### Would you like to implement a fix?

Yes

**Comment by bschaatsbergen** [comment]
Thanks for flagging this @rajivrnair, feel free to open a pull request for this and link it to this issue.
