### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by mahendra3web** [hashicorp/terraform-provider-aws#27359]
### Description

We use terraform for our Infrastructure as Code(IaC), and for the aws_elasticache_cluster resource it would be helpful to be able to specify the reserved-cache-node-id as per reference below as an argument to the aws_elasticache_cluster resource to take advantage of the cost savings.

### Affected Resource(s) and/or Data Source(s)

aws_elasticache_cluster

### Potential Terraform Configuration

```terraform
resource "aws_elasticache_cluster" "example" {
  cluster_id           = "cluster-example"
  reserved_cache_node_id = "myreservationIDprepurchased"
}
```

### References

[AmazonElastiCache Reserved Nodes](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/CacheNodes.Reserved.html)

**Comment by gdavison** [comment]
Thanks for the PR, @mahendra3web. We have issue #20231 open for this issue, so I'm going to close this one. If you believe that your request is different, please open a new issue and give more details
