### ISSUE TITLE
[Bug]:  aws_ecs_service fails with "Family should not be null or empty."

### ISSUE THREAD

**Issue by durnote** [hashicorp/terraform-provider-aws#27362]
### Terraform Core Version

0.12.31

### AWS Provider Version

4.35

### Affected Resource(s)

AWS ECS - CreateService fails when you try to create ECS service that uses EXTERNAL deployment controller

  deployment_controller {
    type = "EXTERNAL"
  }

### Expected Behavior

ECS Service should be created.

### Actual Behavior

Error: error creating ECS service (service-name): InvalidParameterException: Family should not be null or empty.

### Relevant Error/Panic Output Snippet

```shell
Error: error creating ECS service (svc-name): InvalidParameterException: Family should not be null or empty.
```

### Terraform Configuration Files

```
resource "aws_ecs_service" "my_service_test" {
  name          = "svc-name"
  cluster       = "cluster-name"
  desired_count = 0

  scheduling_strategy = "REPLICA"
  deployment_controller {
    type = "EXTERNAL"
  }

  deployment_maximum_percent = "100"   
  deployment_minimum_healthy_percent = "0"
  propagate_tags = "TASK_DEFINITION"

  tags = {
    Name     = "svc-name"
    testing  = "yes"
  }
}
```

### Steps to Reproduce

As you probably know, when using EXTERNAL deployment controller on ECS you should not provide task definition to the ECS during the creation of service.  From AWS Cloud Trail logs I could confirm that latest Terraform provider still sends taskDefiniton as empty string. Looks like this was workinig fine until few days ago.

It seems that AWS updated ECS api recently and now requires that taskDefinition element is strictly not present in JSON request.  I could confirm this by creating the same ECS service using AWS Cli and providing JSON without taskDefinition element.

`aws ecs create-service --cluster cluster-name--service-name svc-name --region us-east-1 --cli-input-json file://ecsaws.json `

If taskDefinition field is present in JSON file it fails with the same error:

`"An error occurred (InvalidParameterException) when calling the CreateService operation: Family should not be null or empty."`

### Debug Output

Just attaching Cloud Trail log that confirms Terraform providers is sending taskDefinition in API request as empty string "".

`"taskDefinition": ""`

Full event
```
{
    "eventVersion": "1.08",
    "eventTime": "2022-10-17T17:52:47Z",
    "eventSource": "ecs.amazonaws.com ",
    "eventName": "CreateService",
    "awsRegion": "us-east-1",
    "userAgent": "APN/1.0 HashiCorp/1.0 Terraform/0.12.31 (+https://www.terraform.io ) terraform-provider-aws/dev (+https://registry.terraform.io/providers/hashicorp/aws ) aws-sdk-go/1.44.114 (go1.18.4; linux; amd64)",
    "errorCode": "InvalidParameterException",
    "errorMessage": "Family should not be null or empty.",
    "requestParameters": {
        "capacityProviderStrategy": [],
        "cluster": "cluster-name",
        "deploymentConfiguration": {
            "maximumPercent": 100,
            "minimumHealthyPercent": 0
        },
        "deploymentController": {
            "type": "EXTERNAL"
        },
        "desiredCount": 0,
        "enableECSManagedTags": false,
        "enableExecuteCommand": false,
        "propagateTags": "TASK_DEFINITION",
        "schedulingStrategy": "REPLICA",
        "serviceName": "svc-name",
        "createdBy": "arn:aws:iam::--SENSITIVE-REMOVED--",
        "taskDefinition": ""

    },
    "responseElements": null,
    "requestID": "96483ddc-a949-4d04-b557-7f775836d914",
    "eventID": "f8d4c080-5121-45ad-90ad-eae7b26bd92a",
    "readOnly": false,
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "recipientAccountId": "SENSITIVE-REMOVED",
    "eventCategory": "Management",
    "tlsDetails": {
        "tlsVersion": "TLSv1.2",
        "cipherSuite": "ECDHE-RSA-AES128-GCM-SHA256",
        "clientProvidedHostHeader": "ecs.us-east-1.amazonaws.com "
    }
}
```

**Comment by durnote** [comment]
I hope this should be easy fix, all we need is to make sure when Terraform uses EXTERNAL deployment controller to not provide taskDefinition at all.

**Comment by durnote** [comment]
Update: Just confirmed the issue is also present on latest Terraform v1.3.3  using latest aws provider (4.35). 

`Error: error creating ECS service (svc-name): InvalidParameterException: Family should not be null or empty.`

Please note - this issue blocks anyone to create ECS service that uses EXTERNAL deploy controller. I think it should be prioritized accordingly.

**Comment by sgirones** [comment]
hit this issue yesterday when switching from ECS to EXTERNAL deployment for all our environments. Had to update several stacks manually. I guess I couldn't have a worse timing :)

**Comment by aoskotsky-amplify** [comment]
I am also seeing this bug for my EXTERNAL deployment controller services

**Comment by jusunglee** [comment]
Yikes— can't even pass a valid task definition name as a parameter to workaround this issue

**Comment by sgirones** [comment]
here is a fix if you want to upvote: https://github.com/hashicorp/terraform-provider-aws/pull/27390

tested myself and works

**Comment by walter-hernandez** [comment]
Currently experiencing the same bug.  Let's wait for the maintainers to merge your PR https://github.com/hashicorp/terraform-provider-aws/pull/27390 @sgirones

**Comment by durnote** [comment]
Thanks everyone!
