### ISSUE TITLE
[Enhancement]: special tags in provider config block for "only for resources that are in plan"

### ISSUE THREAD

**Issue by schollii** [hashicorp/terraform-provider-aws#27381]
### Description

I would like to be able to define some tags that only get updated on resources that are planned for creation, update, or replacement. 

Eg if a tf config defines resources A, B, C to F, but provider determines that only resources A, B and C are going to be created, updated, or replaced:
- the provider would additionally inject a set of tags of my choosing in A, B, and C. 
- If C is a resource that doe snot support AWS tags, then only A and B would have those tag updates in the plan. 
- Objects that were not planned for creation, update or replacement, ie D, E, and F, would not get the new tag values. 

Extending the above example further based on the aws provider configuration example provided below, and assuming the plan will be applied by the same aws user that ran `terraform apply` last time, then on A and B resources, 
- the `tf_applied_date` tag would be in all those resources 
- the `tf_applied_by_aws_user` would not be in the plan since its value is unchanged from current state

Attempted Solutions:

Generate a plan via plan command, read it using python or go, add/modify tags, output the modified plan, run terraform apply on the modified plan.

### Affected Resource(s) and/or Data Source(s)

This would be configured in the provider configuration block, and would cause all resources that are planned for change to have the given tags new values. 

### Potential Terraform Configuration

```terraform
provider "aws" {
  tags_on_changed_resources {
    tf_applied_by_aws_user = var.tf_applier
    tf_applied_date = timestamp()
  }
}
```

### References

https://github.com/hashicorp/terraform/issues/32018

### Would you like to implement a fix?

Yes

**Comment by olivers-xaxis** [comment]
This would be great to have
