### ISSUE TITLE
[New Data Source]: List of AWS Organizations accounts filtered by OU

### ISSUE THREAD

**Issue by HyperMe1200** [hashicorp/terraform-provider-aws#27397]
### Description

It will be useful to have a Data Source that returns a list of AWS Organizations accounts that belong to a specific OU. For example, to manage permissions sets assignments.

### Requested Resource(s) and/or Data Source(s)

aws_organizations_accounts

### Potential Terraform Configuration

```terraform
data "aws_organizations_accounts" "this" {
  parent_id = "123456" # by OU name would be better if possible
}

resource "aws_ssoadmin_account_assignment" "this" {
  count = length(data.aws_organizations_accounts.this)

  instance_arn       = tolist(data.aws_ssoadmin_instances.this.arns)[0]
  permission_set_arn = aws_ssoadmin_permission_set.this.arn

  principal_id   = aws_identitystore_group.this.group_id
  principal_type = "GROUP"

  target_id   = data.aws_organizations_accounts.this[count.index].id
  target_type = "AWS_ACCOUNT"
}
```

### References

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/organizations#Client.ListAccountsForParent
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/organizations#Client.ListChildren

**Comment by abelgvidal** [comment]
I am working on this

**Comment by ewbankkit** [comment]
This functionality is available via the [`aws_organizations_organizational_unit_descendant_accounts`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/organizations_organizational_unit_descendant_accounts) data source.
