### ISSUE TITLE
[Enhancement]: Prefix Lists in AWS Network Firewall Stateful Rule Groups

### ISSUE THREAD

**Issue by nicolavolpini** [hashicorp/terraform-provider-aws#27421]
### Description

A new feature has been recently (30th of September 2022) added to AWS Network Firewall, whereby it is now possible to reference existing Prefix Lists in the Stateful Rules. 
This is done in the AWS web gui by picking existing prefix-lists from a pre-populated dropdown list.
A maximum of 4 references per rule are allowed.

From the linked AWS blog post:
_"Previously you needed to update individual [AWS Network Firewall](https://aws.amazon.com/network-firewall/) rules when scaling your network to add new IP addresses. The release of this new feature means that you can update the relevant prefix list, and all of the Network Firewall rule groups that reference the prefix list are automatically updated. Both customer-managed and AWS-managed prefix lists can be referenced in the stateful firewall rule. Both 5-tuple and Suricata-compatible IPS rule types support referencing prefix lists"_

A similar approach to what is done with "rule variables" could be adopted.

Thank you!

### Affected Resource(s) and/or Data Source(s)

aws_networkfirewall_rule_group

### Potential Terraform Configuration

```terraform
resource "aws_networkfirewall_rule_group" "example" {
  capacity = 100
  name     = "example"
  type     = "STATEFUL"
  rule_group {
    # just an idea. The naming is potentially very confusing (reference vs references)
    ip_set_references {
      ip_set_reference {
     key = "ON_PREM_NETWORKS"         # IP set reference variable name
     definition = "pl-123456abcdef"   # IP set prefix list ID
   }
   ip_set_reference {
     key = "BRANCH_OFFICE_1_NETWORKS" # IP set reference variable name
     definition = "pl-7890abcdef"     # IP set prefix list ID
   }
 }
}
}
```

### References

https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-prefix-lists-in-aws-network-firewall-stateful-rule-groups/

### Would you like to implement a fix?

No

**Comment by mike-morris-emis** [comment]
will be using ip_sets in the meantime, but will use this feature if implemented

**Comment by meetreks** [comment]
I have picked this up, an will advise when completed.

**Comment by meetreks** [comment]
Raised a PR and will progress the PR with Hashi and close the loop. Watch this space.

**Comment by ewbankkit** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/28335.
