### ISSUE TITLE
[Bug]: Provider produced inconsistent result after apply [aws_dms_replication_subnet_group]

### ISSUE THREAD

**Issue by mttradebyte** [hashicorp/terraform-provider-aws#27420]
### Terraform Core Version

1.0.0

### AWS Provider Version

4.36.1

### Affected Resource(s)

aws_dms_replication_subnet_group

### Expected Behavior

An AWS DMS Replication Subnet Group should have been created

### Actual Behavior

No subnet group created, and an error is thrown.

### Relevant Error/Panic Output Snippet

```shell
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to aws_dms_replication_subnet_group.dms-replication-group, provider
│ "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Terraform Configuration Files
```
resource "aws_dms_replication_subnet_group" "dms-replication-group" {
  replication_subnet_group_description = "Subnet group for DBRO replication"
  replication_subnet_group_id          = "dbro-replication"

  subnet_ids = [
    data.aws_subnets.private.ids[0]
  ]
}
```
### Steps to Reproduce

Just try to create a subnet group.

### Plan output
```
  # aws_dms_replication_subnet_group.dms-replication-group will be created
  + resource "aws_dms_replication_subnet_group" "dms-replication-group" {
      + id                                   = (known after apply)
      + replication_subnet_group_arn         = (known after apply)
      + replication_subnet_group_description = "Subnet group for DBRO replication"
      + replication_subnet_group_id          = "dbro-replication"
      + subnet_ids                           = [
          + "subnet-xxxx",
        ]
      + tags_all                             = {
          ... snip ... 
        }
      + vpc_id                               = (known after apply)
    }
```

**Comment by mttradebyte** [comment]
On further investigation, it seems to be caused by attempting to use a single AZ in the TF. It appears a subnet group must contain >1 subnets:
![image](https://user-images.githubusercontent.com/33697686/197475544-de15ba17-fb4d-4602-84b5-1ce9743a698a.png)

**Comment by MacoAccount** [comment]
We encounter the same issuer. Is there anyone following this item ?

**Comment by Dawn-cz** [comment]
I also encounter the same issuer！！！

**Comment by BryanStenson-okta** [comment]
On version `v4.37.0`, I'm seeing this issue, even when passing subnets in >1 availability zone.

**Comment by BryanStenson-okta** [comment]
so in my case, i'm taking the list of subnet ids from an output of a remote state object.  if i cast this output to a list, this works:

```
resource "aws_dms_replication_subnet_group" "this" {
  replication_subnet_group_description = "postgres-to-kinesis"
  replication_subnet_group_id          = "postgres-to-kinesis"

  subnet_ids = tolist(data.terraform_remote_state.rds_platformdb.outputs.rds_platformdb_subnet_ids)

  tags = merge(local.common_tags,
    {
      Name = "postgres-to-kinesis"
    }
  )

}
```

without the `tolist(...)`, it fails.

**Comment by klaidaslekavicius** [comment]
After turning on `TF_LOG=debug` I found this error message appearing in debug logs:

```
2022-11-11T12:20:57.230Z [DEBUG] provider.terraform-provider-aws_v4.33.0_x5: [DEBUG] [aws-sdk-go] {"__type":"AccessDeniedFault","message":"The IAM Role arn:aws:iam::047729596285:role/dms-vpc-role is not configured properly."}

2022-11-11T12:20:57.231Z [DEBUG] provider.terraform-provider-aws_v4.33.0_x5: [DEBUG] [aws-sdk-go] DEBUG: Validate Response dms/CreateReplicationSubnetGroup failed, attempt 0/25, error AccessDeniedFault: The IAM Role arn:aws:iam::047729596285:role/dms-vpc-role is not configured properly.
```

The issue is related to the [special role that AWS tries to create when creating a subnet group](https://github.com/hashicorp/terraform-provider-aws/issues/11025). Apparently, the provider doesn't create this role automatically, so you need to create this IAM role as well:

```
resource "aws_iam_role" "dms_vpc_iam_role" {
  name        = "dms-vpc-role"
  description = "Allows Database Migration Service to manage VPC"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Principal = {
          Service = "dms.amazonaws.com"
        }
        Action = "sts:AssumeRole"
      },
    ]
  })
}

resource "aws_iam_role_policy_attachment" "dms_vpc_iam_role_policy_attachment" {
  role       = aws_iam_role.dms_vpc_iam_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonDMSVPCManagementRole"
}
```

Let me know if this fixes the issue!

**Comment by YakDriver** [comment]
We should add this to the documentation: [👆](https://github.com/hashicorp/terraform-provider-aws/issues/27420#issuecomment-1311684672)

**Comment by YakDriver** [comment]
There are 3 different problems described here:

1. Inconsistent result error: This happens because of a code bug after one of the errors below (or another) happens.
2. Not using subnets that cover 2 AZs.
3. Not having the IAM role `dms-vpc-role` in place. (Relatedly, if creating at the same time, you'll need an explicit `depends_on` for the policy-role assignment rather than the role.)

Solving 1, as pointed out by @ewbankkit, requires a code change. 2 and 3 are documentation issues.
