### ISSUE TITLE
[Bug]: aws_ecs_service External Deployment Controller unusable

### ISSUE THREAD

**Issue by jamiepedwards** [hashicorp/terraform-provider-aws#27428]
### Terraform Core Version

0.14.11

### AWS Provider Version

4.34.0

### Affected Resource(s)

* aws_ecs_service

### Expected Behavior

Creation of an ECS service resource with the deployment controller mode set to EXTERNAL

### Actual Behavior

Failed to create ECS service with an error message.

### Relevant Error/Panic Output Snippet

```shell
Error: error creating ECS service (<service name>): InvalidParameterException: Family should not be null or empty.
```

### Terraform Configuration Files

Used the exact example shown in the documentation at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service#external-deployment-controller

### Steps to Reproduce

Just try to create a service using the example given in the documentation for External Deployment Controller

### Important Factoids

When analyzing the values passed to the AWS API in CloudTrail, it revealed that even though I'm not specifying the `task_definition` argument, the provider is including it in the API call as a blank string.  The existence of the blank string seems to be tripping some kind of validation logic on AWS's side, which causes the `CreateService` call to fail.  When you're using the external deployment controller mode, you cannot specify the task definition at all.

Here's a snippet of the Cloud Trail log entry from the `CreateService` call:

```
{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "AssumedRole",
        "principalId": "<redacted>",
        "arn": "<redacted>",
        "accountId": "<redacted>",
        "accessKeyId": "<redacted>",
        "sessionContext": {
            "sessionIssuer": {
                "type": "Role",
                "principalId": "<redacted>",
                "arn": "<redacted>",
                "accountId": "<redacted>",
                "userName": "<redacted>"
            },
            "webIdFederationData": {},
            "attributes": {
                "creationDate": "2022-10-20T20:35:34Z",
                "mfaAuthenticated": "false"
            }
        }
    },
    "eventTime": "2022-10-20T20:37:59Z",
    "eventSource": "ecs.amazonaws.com",
    "eventName": "CreateService",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "<redacted>",
    "userAgent": "APN/1.0 HashiCorp/1.0 Terraform/0.14.11 (+https://www.terraform.io) terraform-provider-aws/dev (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go/1.44.110 (go1.18.4; linux; amd64)",
    "errorCode": "InvalidParameterException",
    "errorMessage": "Family should not be null or empty.",
    "requestParameters": {
        "capacityProviderStrategy": [],
        "clientToken": "terraform-20221020203759144900000001",
        "cluster": "<redacted>",
        "deploymentConfiguration": {
            "maximumPercent": 200,
            "minimumHealthyPercent": 100
        },
        "deploymentController": {
            "type": "EXTERNAL"
        },
        "desiredCount": 1,
        "enableECSManagedTags": false,
        "enableExecuteCommand": false,
        "schedulingStrategy": "REPLICA",
        "serviceName": "<redacted>",
        "createdBy": "<redacted>",
        "taskDefinition": ""
    },
    "responseElements": null,
    "requestID": "84bdb92c-19c7-4b7c-9529-1e56110b31f5",
    "eventID": "84dece41-2e0a-402b-8423-cdc005133d9f",
    "readOnly": false,
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "recipientAccountId": "<redacted>",
    "eventCategory": "Management",
    "tlsDetails": {
        "tlsVersion": "TLSv1.2",
        "cipherSuite": "ECDHE-RSA-AES128-GCM-SHA256",
        "clientProvidedHostHeader": "ecs.us-east-1.amazonaws.com"
    }
}
```

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@jamiepedwards Thanks for raising this issue.
It has already been noticed in #27362. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
