### ISSUE TITLE
[Bug]: aws_kms_key: tag propagation: timeout while waiting for state to become 'TRUE' (last state: 'FALSE', timeout: 5m0s)

### ISSUE THREAD

**Issue by tahchiev** [hashicorp/terraform-provider-aws#27422]
### Terraform Core Version

1.3.2

### AWS Provider Version

4.33.0,4.35.0

### Affected Resource(s)

aws_kms_key

### Expected Behavior

Terraform should wait for the policy to fully apply and not time out.

### Actual Behavior

Terraform is not waiting long enough for the KMS key policy to propagate and is timing out. Generally there is no change in the policy just order of the accounts so normally it shouldn't even show difference and need to apply changes.

### Terraform Configuration Files

```terraform
resource "aws_kms_key" "imwildcardcert" {
  customer_master_key_spec = "SYMMETRIC_DEFAULT"
  is_enabled   = "true"
  key_usage    = "ENCRYPT_DECRYPT"
  multi_region = "true"
  policy       = <<POLICY
{
 .......
}
POLICY

  tags = {
    Name = "aws-*-kms-z-imwildcardcert-z"
  }
}
```

### Steps to Reproduce

terraform plan and you see it is trying to add and remove same account . So i guess issue is in order of account on an existing KMS key.
terraform apply

### Debug Output

```
-----------------------------------------------------
2022-10-24T11:41:49.794+0300 [DEBUG] [aws-sdk-go] {}
╷
│ Error: error waiting for KMS Key (mrk-3b113360d5d541f484250ed15ebfc6e3) policy propagation: timeout while waiting for state to become 'TRUE' (last state: 'FALSE', timeout: 5m0s)
│
│   with module.kms.aws_kms_key.imwildcardcert,
│   on modules\kms\main.tf line 134, in resource "aws_kms_key" "imwildcardcert":
│  134: resource "aws_kms_key" "imwildcardcert" {
│
╵
╷
│ Error: error waiting for KMS Key (mrk-32e567e825584bd1a3850d0cff40cd6b) policy propagation: timeout while waiting for state to become 'TRUE' (last state: 'FALSE', timeout: 5m0s)
│
│   with module.kms.aws_kms_key.pdqsvc,
│   on modules\kms\main.tf line 240, in resource "aws_kms_key" "pdqsvc":
│  240: resource "aws_kms_key" "pdqsvc" {
│

.....
2022-10-24T11:41:50.866+0300 [DEBUG] [aws-sdk-go] {}
2022-10-24T11:41:50.867+0300 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2022-10-24T11:41:50.919+0300 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/aws/4.35.0/windows_amd64/terraform-provider-aws_v4.35.0_x5.exe pid=27240
2022-10-24T11:41:50.920+0300 [DEBUG] provider: plugin exited
```

### Panic Output

N/A

### Important Factoids

Another strange thing is that we don't have changes in the policy. Terraform just see the list order differently and is trying to remove and add one and same accounts. It shouldn't do it 

 ```
  jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = {
                          ~ AWS = [
                              **+ "arn:aws:iam::372240753xxx:root",**
                               - "arn:aws:iam::552537787yyy:root",
                                **"arn:aws:iam::372240753xxx:root",**
                              + "arn:aws:iam::552537787yyy:root",

                            ]
                        }
                        # (5 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
```

### References

From what I can see this is a similar to the following issue: https://github.com/hashicorp/terraform-provider-aws/issues/23592
The terraform code from which error is coming is here:
https://github.com/hashicorp/terraform-provider-aws/blob/040f37e8d6a1b13fe796c5cdbfebbebb833ae90a/aws/internal/service/kms/waiter/waiter.go#L96-L122
Latest: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/kms/wait.go

**Comment by breisig** [comment]
Im having the EXACT same issue.

**Comment by jhwal47** [comment]
This is complete blocker for me..

**Comment by sciencepal** [comment]
Folks please upvote this PR -> Terraform will wait for 10m for Policy Propagation https://github.com/hashicorp/terraform-provider-aws/pull/28636

**Comment by gdavison** [comment]
@tahchiev, in the diff that Terraform reported, it's not clear if it's just reordering the items or adding an additional `"arn:aws:iam::372240753xxx:root"`.

From the `+`s and `-`s in the listing, it looks like it might be trying to add an additional ``"arn:aws:iam::372240753xxx:root"`` and moving the `"arn:aws:iam::552537787yyy:root"`. Is that what you're seeing?

```
jsonencode(
         ~ {
             ~ Statement = [
                 ~ {
                     ~ Principal = {
                         ~ AWS = [
                             **+ "arn:aws:iam::372240753xxx:root",**
                              - "arn:aws:iam::552537787yyy:root",
                               **"arn:aws:iam::372240753xxx:root",**
                             + "arn:aws:iam::552537787yyy:root",

                           ]
                       }
                       # (5 unchanged elements hidden)
                   },
               ]
               # (1 unchanged element hidden)
           }
       )
```

**Comment by gdavison** [comment]
As of v4.55.0 of the AWS Provider, released 16 February 2023, the timeout has been extended to 10 minutes.

@tahchiev, if you're still seeing the unexpected diff, please open a new issue including the debug log
