### ISSUE TITLE
[Enhancement]: aws_cognito_user_pool Deletion Protection Setting

### ISSUE THREAD

**Issue by imaginaryCorn** [hashicorp/terraform-provider-aws#27435]
### Description

A Deletion Protection setting has been made available for User Pools in Cognito, released Oct 24, 2022:
> You can now activate deletion protection for your Amazon Cognito user pools. When you configure a user pool with deletion protection, the pool cannot be deleted by any user. Deletion protection is now active by default for new user pools created through the AWS Console. You can activate or deactivate deletion protection for an existing user pool in the AWS Console, the AWS Command Line Interface, and API. Deletion protection prevents you from requesting the deletion of a user pool unless you first modify the pool and deactivate deletion protection.

### Affected Resource(s) and/or Data Source(s)

* `aws_cognito_user_pool`

### Potential Terraform Configuration

```terraform
resource "aws_cognito_user_pool" "example" {
  deletion_protection = "ACTIVE" # or "INACTIVE"

  mfa_configuration          = "ON"
  sms_authentication_message = "Your code is {####}"

  sms_configuration {
    external_id    = "example"
    sns_caller_arn = aws_iam_role.example.arn
  }

  software_token_mfa_configuration {
    enabled = true
  }
}
```

### References

- [Full Announcement](https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-cognito-console-user-pool-deletion-protection/)
- [AWS API Reference](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserPool.html#CognitoUserPools-UpdateUserPool-request-DeletionProtection)

### Would you like to implement a fix?

No

**Comment by DrFaust92** [comment]
ill take a look
