### ISSUE TITLE
[Bug]:  An argument named "role_arn" is not expected here in sagemaker_device

### ISSUE THREAD

**Issue by SebastianUA** [hashicorp/terraform-provider-aws#27434]
### Terraform Core Version

1.2.x

### AWS Provider Version

4.35.x

### Affected Resource(s)

...
- Finding hashicorp/aws versions matching "4.35.0"...
...
- Installing hashicorp/aws v4.35.0...
- Installed hashicorp/aws v4.35.0 (signed by HashiCorp)
...
│ Error: Unsupported argument
│ 
│   on .terraform/modules/service_sagemaker.sagemaker.sagemaker/sagemaker_device.tf line 8, in resource "aws_sagemaker_device" "sagemaker_device":
│    8:   role_arn          = var.sagemaker_device_role_arn
│ 
│ An argument named "role_arn" is not expected here.

### Expected Behavior

The code is here https://github.com/SebastianUA/terraform-aws-sagemaker/issues/6

### Actual Behavior

The code is here https://github.com/SebastianUA/terraform-aws-sagemaker/issues/6

### Terraform Configuration Files

https://github.com/SebastianUA/terraform-aws-sagemaker/blob/master/sagemaker_device.tf#L8

Off doc: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_device

### Steps to Reproduce

Get module from https://github.com/SebastianUA/terraform-aws-sagemaker and turn on the stack.

**Comment by aliwinter** [comment]
+1

**Comment by justinretzolk** [comment]
Hey @SebastianUA 👋 Thank you for taking the time to raise this! In reviewing the [resource schema](https://github.com/hashicorp/terraform-provider-aws/blob/1cc3df8cb69be164206aef7142c4e1e118b4eafe/internal/service/sagemaker/device.go#L28-L71), it looks like this is a documentation error. It does not appear that this resource takes a `role_arn` argument. Additionally, the underlying function's [input](https://docs.aws.amazon.com/sdk-for-go/api/service/sagemaker/#RegisterDevicesInput) does not take a role are, so I don't believe this an argument that needs to be added.

I'll raise a pull request to remove the `role_arn` argument from the documentation for this resource.

**Comment by SebastianUA** [comment]
Hi @justinretzolk 

Thank you!
