### ISSUE TITLE
[Docs]: aws_secretsmanager_secret Rotation Configuration broken AWS links

### ISSUE THREAD

**Issue by ryan-cpi** [hashicorp/terraform-provider-aws#27455]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/secretsmanager_secret

### Description

[Rotate Secrets section in the Secrets Manager User Guide](https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets_strategies.html) links to a dead AWS page it should be pointing at https://docs.aws.amazon.com/secretsmanager/latest/userguide/getting-started.html#rotation-strategy

**Comment by abelgvidal** [comment]
i am working on this

**Comment by abelgvidal** [comment]
ok it is fixed in #27425
