### ISSUE TITLE
[Enhancement]: AWS Batch for Amazon Elastic Kubernetes Service

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#27466]
### Description

> Today, AWS Batch introduced support for Amazon Elastic Kubernetes Service (Amazon EKS), enabling customers to run their jobs on Amazon EKS clusters as Kubernetes pods.

### Affected Resource(s) and/or Data Source(s)

* [`aws_batch_compute_environment`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/batch_compute_environment)

### Potential Terraform Configuration

```terraform
resource "aws_batch_compute_environment" "example" {
  compute_environment_name = "example"

  eks_configuration {
    eks_cluster_arn = aws_eks_cluster.example.arn
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2022/10/aws-batch-supports-amazon-eks/).
[Blog post](https://aws.amazon.com/blogs/aws/aws-batch-for-amazon-elastic-kubernetes-service/).

Requires [AWS SDK for Go v1.44.122](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.122): https://github.com/hashicorp/terraform-provider-aws/pull/27441.

**Comment by bschaatsbergen** [comment]
I'll happily pick this up.
