### ISSUE TITLE
[Bug]: resource/aws_lb_target_group - Forces replacement of resource after importing

### ISSUE THREAD

**Issue by posquit0** [hashicorp/terraform-provider-aws#27463]
### Terraform Core Version

1.3.3

### AWS Provider Version

4.36.1

### Affected Resource(s)

* resource/aws_lb_target_group

### Expected Behavior

After importing the existing IP target group(IPv4 address type), it should be safe from replacement by Terraform.

### Actual Behavior

After importing the existing IP target group(IPv4 address type), Terraform always makes a plan to forcibly replace the target group.

```
  # module.nlb_ip_target_group["nlb-ip-traefik"].aws_lb_target_group.this must be replaced
-/+ resource "aws_lb_target_group" "this" {
      ~ arn                                = "arn:aws:elasticloadbalancing:ap-northeast-2:xxxxxxxxxx:targetgroup/nlb-ip-traefik/dddd" -> (known after apply)
      ~ arn_suffix                         = "targetgroup/nlb-ip-traefik/dddd" -> (known after apply)
      ~ id                                 = "arn:aws:elasticloadbalancing:ap-northeast-2:xxxxxxxx:targetgroup/nlb-ip-traefik/dddd" -> (known after apply)
      + ip_address_type                    = "ipv4" # forces replacement
      + lambda_multi_value_headers_enabled = false
      + load_balancing_algorithm_type      = (known after apply)
        name                               = "nlb-ip-traefik"
      + protocol_version                   = (known after apply)
      + slow_start                         = 0
        tags                               = {
```

### Terraform Configuration Files

```tf
resource "aws_lb_target_group" "this" {
  ...

  target_type     = "ip"
  ip_address_type = "ipv4"
  ...
}
```

### Steps to Reproduce

- Create NLB IP target group with IPv4 address type.
- Import the target group to terraform.
- Execute `terraform plan`.
- You can see that terraform will try to replace the target group.

### References

- https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.27.0

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/26320.

**Comment by bschaatsbergen** [comment]
Being picked up by @brittandeyoung in #27464
