### ISSUE TITLE
[Docs]: The documentation link on AWS provider no longer takes you to the versioned docs

### ISSUE THREAD

**Issue by jimmyR** [hashicorp/terraform-provider-aws#27461]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/3.75.2

### Description

On the documentation page for AWS 3.75.2 provider, the Documentation page take you to the docs for the latest version of the provider, not the 3.75.2 provider docs.

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @jimmyR 👋 Can you expand a bit on what you mean? I followed the link you provided to get to the version `3.75.2` landing page and then clicked "Documentation", which brought me to:

https://registry.terraform.io/providers/hashicorp/aws/3.75.2/docs

I don't believe I'm able to reproduce, but I'd be happy to try again.

**Comment by justinretzolk** [comment]
Hey @jimmyR 👋 I notified the team about the odd behavior on the Terraform Registry, and it appears that they've fixed it. Can you take a look again to confirm you're seeing the correct behavior now?

**Comment by dev-slatto** [comment]
Hey @justinretzolk! 👋🏼 
Don't know if you also want to await Jimmy's response, but I also had this issue and it looks like it's resolved for me now as well. I guess this issue can be closed 😄

**Comment by jimmyR** [comment]
It’s fixed for me too. Many thanks.
