### ISSUE TITLE
[Bug]: Can't enable logging configuration for existing AWS Prometheus workspace

### ISSUE THREAD

**Issue by romich** [hashicorp/terraform-provider-aws#27472]
### Terraform Core Version

1.3.2

### AWS Provider Version

4.36.1

### Affected Resource(s)

aws_prometheus_workspace

### Expected Behavior

Logging is enabled for existing workspace

### Actual Behavior

Error is produced:
```
Error: updating Prometheus Workspace (ws-...) logging configuration: ResourceNotFoundException: Workspace logging configuration not found.
```

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: updating Prometheus Workspace (ws-...) logging configuration: ResourceNotFoundException: Workspace logging configuration not found.
│ {
│   RespMetadata: {
│     StatusCode: 404,
│     RequestID: "..."
│   },
│   Message_: "Workspace logging configuration not found.",
│   ResourceId: "ws-.../logging",
│   ResourceType: "AWS::APS::LoggingConfiguration"
│ }
│
│   with aws_prometheus_workspace.amp,
│   on amp.tf line 5, in resource "aws_prometheus_workspace" "amp":
│    5: resource "aws_prometheus_workspace" "amp" {
│
╵
```

### Terraform Configuration Files

Step 1:
```
resource "aws_prometheus_workspace" "amp" {}
```
Step 2:
```
resource "aws_cloudwatch_log_group" "amp" {
  name = "/aws/vendedlogs/prometheus"
}

resource "aws_prometheus_workspace" "amp" {
  logging_configuration {
    log_group_arn = "${aws_cloudwatch_log_group.amp.arn}:*"
  }
}
```

### Steps to Reproduce

1. Apply terraform config from Step 1.
2. Apply terraform config from Step 2, observe error.

### Important Factoids

Enabling logs with aws cli works fine with resources created at step 2, and after this `terraform plan` reports that there are no changes.
```
❯ aws amp create-logging-configuration --workspace-id ws-... --log-group-arn 'arn:aws:logs:us-east-1:...:log-group:/aws/vendedlogs/prometheus:*'
{
    "status": {
        "statusCode": "CREATING"
    }
}
```

### Would you like to implement a fix?

No

**Comment by TheJacobWalters** [comment]
I would like to fix this bug. It has effected me and I have tracked down the cause. This will be my first contribution.

**Comment by TheJacobWalters** [comment]
This area of code shows that when a workspace is getting updated, if there has been a change to "logging_configuration", the code will do one of two things. 
1. call UpdateWorkspaceAliasWithContext
2. call DeleteLoggingConfigurationWithContext

https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/amp/workspace.go#L192

In order to address this bug, we need to add a call to CreateLoggingConfigurationWithContext

**Comment by TheJacobWalters** [comment]
@ewbankkit I think this is ready to go

**Comment by TheJacobWalters** [comment]
@ewbankkit would you run the tests again ?
