### ISSUE TITLE
[Enhancement]: Allow Tags in SES Configuration Set

### ISSUE THREAD

**Issue by seanlok** [hashicorp/terraform-provider-aws#27475]
### Description

Current resources in terraform unable to [tag](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ses/configuration_set.go) the configuration set. 

### Affected Resource(s) and/or Data Source(s)

aws_ses_configuration_set

### Potential Terraform Configuration

```terraform
resource "aws_ses_configuration_set" "test" {
  name = "some-configuration-set-test"

  delivery_options {
    tls_policy = "Require"
  }

  tags = {
    Environment = "test"
  }

}
```

### References

https://docs.aws.amazon.com/ses/latest/dg/creating-configuration-sets.html

```
{
    "configuration-set-name": "sample-configuration-set",
    "tracking-options": {
        "CustomRedirectDomain": "some.domain.com"
    },
    "delivery-options": {
        "TlsPolicy": "REQUIRE",
        "SendingPoolName": "sending pool"
    },
    "reputation-options": {
        "ReputationMetricsEnabled": true,
        "LastFreshStart": timestamp
    },
    "sending-options": {
        "SendingEnabled": true
    },
    "tags": [
        {
            "Key": "tag key",
            "Value": "tag value"
        }
    ],
    "suppression-options": {
        "SuppressedReasons": ["BOUNCE","COMPLAINT"]
    }
}
```

**Comment by kamilturek** [comment]
Hey @seanlok, the SES (v1) does not allow specifying tags. But you can use the `aws_sesv2_configuration_set` that lets you manage the same resource through the SES v2 API which allows tags.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_configuration_set

**Comment by seanlok** [comment]
noted. so have to be moved into a different resources in this case.
