### ISSUE TITLE
[Docs]: aws_appsync_datasource

### ISSUE THREAD

**Issue by raphaelfavier** [hashicorp/terraform-provider-aws#27498]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appsync_datasource#http_config

### Description

Hello,

Not really an error but a very welcome precision on one option:

[service_role_arn](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appsync_datasource#service_role_arn) is marked as optional.

However this is mandatory if the type of the data source is HTTP and [authorization_config](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appsync_datasource#authorization_config) is used with [authorization_type](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appsync_datasource#authorization_type) set to AWS_IAM (default).

In case service_role_arn is not set, the user will see an error message which is pretty vague:
_(BadRequestException) when calling the CreateDataSource operation: The validated string is empty_

Adding this precision in the documentation might save a lot of headaches for future users.
I think mentioning something like "_requires service_role_arn to be set_" in authorization_type would suffice.

**Comment by acwwat** [comment]
The [AWS:AppSync:DataSource CF template reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-datasource.html#cfn-appsync-datasource-servicerolearn) has a decent description on the condition. I'll copy the wordings to the resource doc and submit a PR.
