### ISSUE TITLE
r/aws_acmpca_certificate_authority: `SHORT_LIVED_CERTIFICATE` mode

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#27491]
### Description

> [AWS Private Certificate Authority](https://aws.amazon.com/private-ca/) (AWS Private CA) now offers short-lived certificate mode, a lower cost mode of AWS Private CA designed for issuing short-lived certificates.

### Affected Resource(s) and/or Data Source(s)

* [`aws_acmpca_certificate_authority`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acmpca_certificate_authority)

### Potential Terraform Configuration

```terraform
resource "aws_acmpca_certificate_authority" "example" {
  usage_mode = "SHORT_LIVED_CERTIFICATE"
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2022/10/aws-private-certificate-authority-introduces-mode-short-lived-certificates/).
[User guide](https://docs.aws.amazon.com/privateca/latest/userguide/short-lived-certificates.html).

Requires [AWS SDK for Go v1.44.122](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.122): https://github.com/hashicorp/terraform-provider-aws/pull/27441.

**Comment by bschaatsbergen** [comment]
I'll happily pick this up.
