### ISSUE TITLE
setting source_dest_check to false not working for spot instances

### ISSUE THREAD

**Issue by bbayani** [hashicorp/terraform-provider-aws#2751]
### Affected Resource(s)
Please list the resources as a list, for example:
- aws_spot_instance_request
- aws_instance

### Terraform Configuration Files
No specific config

### Output
<img width="1149" alt="source_dest_check" src="https://user-images.githubusercontent.com/10231863/34257150-97999298-e67e-11e7-95f4-354219ce7185.png">

### Expected Behavior
If I set the source_dest_check as false while defining resource aws_spot_instance_request, the created instance should have Source/Dest Check = False in AWS console. 

### Actual Behavior
Whether i set source_dest_check = false / source_dest_check = "false" / source_dest_check = 0, the Source/Dest Check for created instances is always shown as true in AWS console.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create file say 'instance.tf'. Copy below code into it:
`
provider "aws" {}

resource "aws_spot_instance_request" "worker" {
  count = "1"
  instance_type = "t2.micro"
  ami = "\<AMI_ID\>"
  spot_price = "1"
  spot_type = "one-time"
  key_name = "\<KEY_NAME\>"
  source_dest_check = false
  root_block_device {
     "volume_type" = "standard"
     "volume_size" = "15"
     "delete_on_termination" = "true"
  }
}
`

2. Export AWS credentials
export AWS_REGION=us-east-1
export AWS_SECRET_ACCESS_KEY=\<VALUE\>
export AWS_SESSION_TOKEN=\<VALUE\>
export AWS_ACCESS_KEY_ID=\<VALUE\>

3. Run `terraform apply`

4. Check the value of 'Source/Dest Check' attribute for created EC2 instance on AWS console. Its always True even if we set it to 'false' in .tf file

**Comment by loivis** [comment]
The `aws_spot_instance_request` resource doesn't seem to mention `source_dest_check` at all.

From [RequestSpotLaunchSpecification API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RequestSpotLaunchSpecification.html), I didn't find this property either.

However, the issue https://github.com/hashicorp/packer/issues/5239 shows that this property might come from ami.

Did you try with an ami that is created from an instance with `source_dest_check` disabled?

**Comment by bbayani** [comment]
The documentation for aws_spot_instance_request mentions that it supports all the same arguments as aws_instance:
https://www.terraform.io/docs/providers/aws/r/spot_instance_request.html

aws_instance resource does have source_dest_check attribute. https://www.terraform.io/docs/providers/aws/r/instance.html#source_dest_check

The attribute does work for aws_instance, but not for aws_spot_instance_request!

We would not want to tweak the attribute at AMI level.

**Comment by bbayani** [comment]
The reason i think setting source_dest_check  on aws_instance works is aws_instance create calls aws_instance update as well internally and that sets the source_dest_check to correct value. API used in this flow here is https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyInstanceAttribute.html

for aws_spot_instance_request, the aws_spot_instance_request create calls aws_instance create, but aws_instance update  is not called in this flow. Only aws_spot_instance_request update is called which just sets spot instance specific attributes.

**Comment by bbayani** [comment]
Is anyone looking into this issue?

**Comment by carlosonunez** [comment]
I'm also experiencing this behavior.

**Comment by jaredvacanti** [comment]
This still seems to revert to `source_dest_check = true` in the console with a spot request in terraform.

**Comment by rhysjtevans** [comment]
I'm still seeing this 
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.32.0
