### ISSUE TITLE
Tests: Use `SHORT_LIVED_CERTIFICATE` ACMPCA CAs to reduce costs

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#27524]
Following the merge of https://github.com/hashicorp/terraform-provider-aws/pull/27496 investigate the use of `SHORT_LIVED_CERTIFICATE` ACMPCA CAs in acceptance tests to reduce AWS billing costs.

See https://aws.amazon.com/about-aws/whats-new/2022/10/aws-private-certificate-authority-introduces-mode-short-lived-certificates/.

**Comment by bschaatsbergen** [comment]
Picking this one up..
