### ISSUE TITLE
[Docs]: AWS EKS Node group formatting issue

### ISSUE THREAD

**Issue by MariuszGajewski** [hashicorp/terraform-provider-aws#27531]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#example-usage

### Description

The formatting of the documentation is wrong, due to that ithe documentation is unreadable. It should look more or less like for the previous version: https://registry.terraform.io/providers/hashicorp/aws/4.36.1/docs/resources/eks_node_group

**Comment by mattburgess** [comment]
Hi @MariuszGajewski - could you perhaps provide a description (or even a screenshot) showing the formatting issues you see? The only minor issue I see is that the code sample under [Tracking the latest EKS Node Group AMI releases](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#tracking-the-latest-eks-node-group-ami-releases) isn't syntax highlighted which I'll fix up.

**Comment by mattburgess** [comment]
Ah, looks like I completely messed my edits up a few releases ago. @MariuszGajewski I reckon any remaining issues will be fixed up on this week's release thanks to https://github.com/hashicorp/terraform-provider-aws/commit/716f8ed41b686457f0f2c23a5cc4e9600e2145ab (thanks @justinretzolk!)

**Comment by mattburgess** [comment]
Closing; this was fixed in 4.40.0.
