### ISSUE TITLE
[Docs]: looking for rds creation timeouts document

### ISSUE THREAD

**Issue by niteen05** [hashicorp/terraform-provider-aws#27530]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance.html#timeouts

### Description

As per the earlier issues : https://github.com/hashicorp/terraform-provider-aws/issues/27
https://github.com/hashicorp/terraform/issues/5831
https://github.com/hashicorp/terraform/issues/5161

Issue i fixed by introducing timeout option. Its not working for me while creating rds. when checked document getting error 
Page Not Found
This documentation page doesn't exist for version 4.37.0 of the aws provider.

### Would you like to implement a fix?

No

**Comment by niteen05** [comment]
I have added timeout for creating db from snapshot, still it’s timing out after 1h20m.

RDS takes lot time in Storage Optimisation state.

Sent from my iPhone

On 31 Oct 2022, at 11:56 pm, Prakash Nath Jha ***@***.***> wrote:

﻿

I think the correct link is: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#timeouts<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fregistry.terraform.io%2Fproviders%2Fhashicorp%2Faws%2Flatest%2Fdocs%2Fresources%2Fdb_instance%23timeouts&data=05%7C01%7C%7C3533ce1a913045f1c37c08dabb3f4d8f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638028177825870230%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=chPmKT6VW12qx9k8sxQxRkyd9S4O%2FDtjo19GQEgvtLs%3D&reserved=0>

**Comment by niteen05** [comment]
Thanks for the link Prakash. It worked.

**Comment by niteen05** [comment]
It took 14h 40m to become rds available from Storage Optimisation state. In console rds is in available state. We called terraform script from jenkins, in jenkins console, terraform is still waiting for available signal. Looks like its going to be timed out again. Terraform not able to recognise rds state. Did anyone face similar issue?

aws_db_instance.rds_mysql: Still creating... [15h7m11s elapsed]
aws_db_instance.rds_mysql: Still creating... [15h7m21s elapsed]

**Comment by taisytran** [comment]
Yes, I am facing this issue too. I am using TF version 1.1.1 and aws-provider is 3.42.0

It seems to be like the status of TF RDS resource can't be synced anymore, it's stuck. AWS console said RDS was available at 50m but TF was still waiting for creating until reaching timeout cfg
