### ISSUE TITLE
[Enhancement]: Support for Amazon MSK Tiered storage

### ISSUE THREAD

**Issue by prithvi514** [hashicorp/terraform-provider-aws#27540]
### Description

Amazon MSK now supports tiered storage with S3 backend.
Terraform aws_msk_cluster should provide an option to pass `[--storage-mode <value>]` to the MSK cluster create call.

### Affected Resource(s) and/or Data Source(s)

* aws_msk_cluster

### Potential Terraform Configuration

```terraform
broker_node_group_info {
    instance_type = "kafka.m5.large"
    client_subnets = [
      aws_subnet.subnet_az1.id,
      aws_subnet.subnet_az2.id,
      aws_subnet.subnet_az3.id,
    ]
    storage_info {
      ebs_storage_info {
        volume_size = 1000
      }
      storage_mode = "TIERED"
    }
}
```

### References

https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-msk-offers-low-cost-storage-tier-scales-virtually-unlimited-storage/
https://docs.aws.amazon.com//cli/latest/reference/kafka/create-cluster.html

**Comment by bschaatsbergen** [comment]
Requires [v1.44.124](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.124) of the aws-sdk-go
https://github.com/aws/aws-sdk-go/blob/v1.44.124/service/kafka/api.go#L11902
