### ISSUE TITLE
[Enhancement]: CloudWAN core_network_id support for aws_vpn_connection

### ISSUE THREAD

**Issue by erwinchong** [hashicorp/terraform-provider-aws#27544]
### Description

Current aws_vpn_connection resource only support transit_gateway_id or vpn_gateway_id. Please add support to core_network_id for the new AWS CloudWAN.

### Affected Resource(s) and/or Data Source(s)

aws_vpn_connection

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/26420.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/25835.
