### ISSUE TITLE
[Bug]: aws_ip_ranges services is now case sensitive

### ISSUE THREAD

**Issue by 56KBs** [hashicorp/terraform-provider-aws#27554]
### Terraform Core Version

1.3.3

### AWS Provider Version

4.36.1, 4.37.0

### Affected Resource(s)

`aws_ip_ranges`

### Expected Behavior

When setting the `services` section, the documentation lists lowercase values, then links to the Amazon documentation for additional values, which are uppercase.

I would expect the services section to be case insensitive - As this is the behaviour seen in 4.35.0.

### Actual Behavior

The services section is no longer case insensitive - This causes no CIDRs to be identified.

### Terraform Configuration Files

```terraform
data "aws_ip_ranges" "amazon" {
  regions  = ["eu-west-2"]
  services = ["AMAZON"]
}

output "amazon_ips" {
  value = data.aws_ip_ranges.amazon
}
```

### Steps to Reproduce

```bash
terraform init
terraform apply
```

### Debug Output

```
Changes to Outputs:
  + aws_ips = {
      + cidr_blocks      = []
      + create_date      = "2022-10-29-08-43-06"
      + id               = "1667032986"
      + ipv6_cidr_blocks = []
      + regions          = null
      + services         = [
          + "AMAZON",
        ]
      + sync_token       = 1667032986
      + url              = "https://ip-ranges.amazonaws.com/ip-ranges.json"
    }

```

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/27221.
