### ISSUE TITLE
[Bug]:  we are not able to see the include option in datasync task

### ISSUE THREAD

**Issue by BhargaviPandugayala26** [hashicorp/terraform-provider-aws#27557]
### Terraform Core Version

2.2.0

### AWS Provider Version

4.2.0

### Affected Resource(s)

aws_datasync_task 

### Expected Behavior

![datasync includes](https://user-images.githubusercontent.com/110160308/199024697-8b12574e-31e0-4420-b996-47b9735dc4e6.png)

### Actual Behavior

![datasync includes](https://user-images.githubusercontent.com/110160308/199024850-b041f787-9e05-44ed-81f4-2f69f8ee15ed.png)

### Terraform Configuration Files

```terraform
resource "aws_datasync_task" "datasync_task" {
  destination_location_arn = var.datasync_s3_destination_arn //aws_datasync_location_nfs.datasync_nfs_destination.arn
  name                     = var.name
  source_location_arn      = var.datasync_nfs_source_arn //aws_datasync_location_s3.datasync_s3_source.arn
  #cloudwatch_log_group_arn = aws_cloudwatch_log_group.datasync_logs.arn


  excludes {
    filter_type = "SIMPLE_PATTERN"
    value       = ""
  }

  includes {
    filter_type = "SIMPLE_PATTERN"
    value       = "/data"
  }

  /*schedule {
    schedule_expression = "cron(0 12 ? * SUN,WED *)"
  }*/


}
```

while iam putting the cursor on the includes it is showing like  unknown block type includes...issue

### Steps to Reproduce

use above code

**Comment by justinretzolk** [comment]
Hey @BhargaviPandugayala26 👋 Thank you for taking the time to raise this! It looks like the `includes` argument [was added in `4.24.0`](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#4240-july-29-2022), so you'll need to upgrade your AWS provider version in order to take advantage of it.
