### ISSUE TITLE
[New]: Support for Redshift aws_redshift_authorize_endpoint_access Resource

### ISSUE THREAD

**Issue by joshuabaird** [hashicorp/terraform-provider-aws#27593]
### Description

#25073 ([link](https://github.com/hashicorp/terraform-provider-aws/pull/25073)) introduced the `aws_redshift_endpoint_access` resource which allows you to define a Redshift-managed VPC endpoint.

This is all you need for creating a managed VPC endpoint that is used in the same AWS account.  But, if you want to share the cluster with an external account, you need to "grant" access to the external account.  This is accomplished using the [AuthorizeEndpointAccess](https://docs.aws.amazon.com/sdk-for-go/api/service/redshift/#Redshift.AuthorizeEndpointAccess) API -- which is not currently supported by the AWS provider.

### Requested Resource(s) and/or Data Source(s)

* aws_redshift_authorize_endpoint_access

### Potential Terraform Configuration

```terraform
resource "aws_redshift_authorize_endpoint_access" "this" {
  cluster = aws_redshift_cluster.this.id
  account = "12345678" # External account ID
  vpc_ids = ["12345678"] # External account VPC requesting access
}
```

### References

https://docs.aws.amazon.com/sdk-for-go/api/service/redshift/#Redshift.AuthorizeEndpointAccess

**Comment by DrFaust92** [comment]
ill take a look
