### ISSUE TITLE
[Bug]: aws_eks_addon is taking at least 15 minutes to create addon and sometime hits timeout. 

### ISSUE THREAD

**Issue by sarveshpat** [hashicorp/terraform-provider-aws#27591]
### Terraform Core Version

1.1.0

### AWS Provider Version

3.72

### Affected Resource(s)

aws_eks_addon

### Expected Behavior

If we create manually, it takes very less time. so expectation is like it should take as it takes during manual creation. 

### Actual Behavior

If we create manually, it takes very less time but via terraform it takes at least 15 minutes. 

### Relevant Error/Panic Output Snippet

```shell
Error: unexpected EKS Add-On (xyz:aws-ebs-csi-driver) state returned during creation: timeout while waiting for state to become 'ACTIVE' (last state: 'CREATING', timeout: 20m0s)
```

### Terraform Configuration Files

i am creating EKS cluster and it is using kubernets version 1.23 which requires CSI driver addon creation first. But creation via terraform takes way longer time. 

### Steps to Reproduce

Create resource aws_eks_addon via terraform.

**Comment by sarveshpat** [comment]
Please let us know if there is any work around ?

**Comment by justinretzolk** [comment]
Hey @sarveshpat 👋 Thank you for taking the time to raise this! Based on the message you pasted, it seems that the API is returning that the cluster is indeed still in the `CREATING` state, so I'm not certain that this is something that's a bug with the provider. That said, can you supply a sample Terraform configuration and debug logs (redacted as needed), and we can take another look to confirm that thought?

**Comment by mattburgess** [comment]
My suspicion here is that the `aws_eks_addon` resource hard-codes the cluster name, rather than referencing the `aws_cluster.your_cluster_resource.name` attribute which would help Terraform create the cluster _before_ trying to create the addon. @sarveshpat if you could post at least what your `aws_eks_addon` resource configuration looks like please, that'd help us out. Thanks!

**Comment by tabnul** [comment]
Same here, eks_addon deployment takes exactly 15 minutes. 
I also think its an AWS issue, the addon deployment stays on 'CREATING' this whole time.

AWS needs to fix this in their backend. It should be way faster, basically they only apply some YAML to the API server. (we dont have a nodegroup running at the moment we enable this addon, it should be a few seconds imo.)

```
resource "aws_eks_addon" "vpc-cni" {
  cluster_name             = aws_eks_cluster.eks.name
  resolve_conflicts        = "OVERWRITE"
  addon_name               = "vpc-cni"
  service_account_role_arn = aws_iam_role.eks.arn

  # https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html
  addon_version = var.eks_addon_vpc-cni_version
}
```

**Comment by tabnul** [comment]
fyi i did a bump of the eks addon above, now it deploys in 2 minutes!
formerly: v1.12.0-eksbuild.1

now: v1.12.1-eksbuild.1

**Comment by tabnul** [comment]
> fyi i did a bump of the eks addon above, now it deploys in 2 minutes! formerly: v1.12.0-eksbuild.1
> 
> now: v1.12.1-eksbuild.1

reply to self; today it takes 15 minutes again. seems like a backend issue on AWS side..

**Comment by tabnul** [comment]
Thinking about a solution here; lets assume that the provisioning succeeds on AWS side , as long as configuration is accepted and validated.
Something like we have in the hel_release resource could help here; adding an option wait=false ?

**Comment by justinretzolk** [comment]
Hi all 👋 It seems like this might be on the AWS side of things rather than an issue with the provider. As such, I'll close this issue out for now. If you feel I've done this in error, please do let me know.
