### ISSUE TITLE
[Bug]: inconsistent final plan in aws_security_group dynamic egress when referencing another sg id.

### ISSUE THREAD

**Issue by molet-j** [hashicorp/terraform-provider-aws#27614]
### Terraform Core Version

1.3.4

### AWS Provider Version

4.37.0

### Affected Resource(s)

aws_security_group

### Expected Behavior

The aws provider should be able to produce a consistant plan for both security groups. 
The second one, WebServer's sg should be able to plan its ingress rules and leave only the field "security_groups" to "(known after apply)".

### Actual Behavior

While building a module to handle the creation of multiple security groups with custom ports to open.
The LoadBalancer's security group get its plan perfectly with the different port being translated into ingress rules, with the cidr "0.0.0.0/0" to be open to internet.
The same logic does not return a consistent plan for the WebServer's security group, which retake the same ports but open to only the LoadBalancer's security group. Only **1 ingress rule** is shown in the plan, with all information "(known after apply)", when it should be able to plan the different ingress rule and only the "security_groups" list member should be "(known after apply)". 

The apply fails during the creation of the second SG. 
Relaunching apply a second time, gets a clean plan and succeed.

### Relevant Error/Panic Output Snippet

```shell
plan output for the WebServer's security group:
+ ingress                = [
          + {
              + cidr_blocks      = (known after apply)
              + description      = (known after apply)
              + from_port        = (known after apply)
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = (known after apply)
              + security_groups  = (known after apply)
              + self             = (known after apply)
              + to_port          = (known after apply)
            },
        ]


----------------------------
error during apply:
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.websvr_sg.aws_security_group.security_group to include new values learned so far
│ during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .ingress: length
│ changed from 1 to 6.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

### Terraform Configuration Files

[bug_provider_sg.zip](https://github.com/hashicorp/terraform-provider-aws/files/9926908/bug_provider_sg.zip)

### Steps to Reproduce

The provided terraform code has been cleaned up to reproduce the bug. 
You'll just need some AWS credentials for the provider
- terraform init
- terraform plan --var-file test.tfvars
- (optional) terraform apply --var-file test.tfvars

### Important Factoids

I am using locals to prepare the ingress rules depending on the list of ports/protocols given in the variable.
I use list creation with for loop and if, to select and separate the UDP & TCP ports.
The logic works well on the LB sg, but not on the Web sg as it depends on the output of the former.

**Comment by justinretzolk** [comment]
Hey @molet-j 👋 Thank you for taking the time to raise this! This behavior seems like it's related to Terraform configuration, rather than an issue with the provider itself. With that in mind, you'll likely have better luck asking in one of our community resources, such as the [AWS provider forums](https://discuss.hashicorp.com/c/terraform-providers/tf-aws).

I'll leave the issue open for now in case you have any follow up questions before we close this one out.

**Comment by ljluestc** [comment]
```
terraform {
  required_version = "~> 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

# Create a local value for ingress rules
locals {
  web_sg_ingress = [
    {
      description = "Allow incoming HTTP traffic"
      from_port   = 80
      to_port     = 80
      protocol    = "tcp"
      cidr_blocks = [aws_security_group.lb_sg.id]
    },
    {
      description = "Allow incoming HTTPS traffic"
      from_port   = 443
      to_port     = 443
      protocol    = "tcp"
      cidr_blocks = [aws_security_group.lb_sg.id]
    },
    # Add more rules as needed
  ]
}

# Create a Security Group for LoadBalancer
resource "aws_security_group" "lb_sg" {
  name        = "LoadBalancerSecurityGroup"
  description = "Security Group for Load Balancer"
}

# Create a Security Group for WebServer
resource "aws_security_group" "web_sg" {
  name        = "WebServerSecurityGroup"
  description = "Security Group for Web Servers"
}

# Define ingress rules for WebServer Security Group
resource "aws_security_group_rule" "web_sg_ingress" {
  count                   = length(local.web_sg_ingress)
  type                    = "ingress"
  from_port               = local.web_sg_ingress[count.index].from_port
  to_port                 = local.web_sg_ingress[count.index].to_port
  protocol                = local.web_sg_ingress[count.index].protocol
  cidr_blocks             = local.web_sg_ingress[count.index].cidr_blocks
  security_group_id       = aws_security_group.web_sg.id
}

# Output the IDs of the Security Groups for reference
output "lb_sg_id" {
  value = aws_security_group.lb_sg.id
}

output "web_sg_id" {
  value = aws_security_group.web_sg.id
}

```
