### ISSUE TITLE
[Docs]: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_cluster Does not work

### ISSUE THREAD

**Issue by Iranganti** [hashicorp/terraform-provider-aws#27625]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_cluster

### Description

the link does not work.. keeps hourglassing

**Comment by Mattie112** [comment]
You can see the docs here if you need them: https://github.com/hashicorp/terraform-provider-aws/tree/main/website/docs/r

**Comment by ewbankkit** [comment]
https://status.hashicorp.com/incidents/vbr6hdbp9y4g

**Comment by justinretzolk** [comment]
Hey y'all 👋 This was due to an incident with the Terraform Registry that [has now been resolved](https://status.hashicorp.com/incidents/vbr6hdbp9y4g), so we'll close this issue. If you have further issues with the Terraform Registry, please do let us know.
