### ISSUE TITLE
[Docs]: guardduty_detector documentation does not load

### ISSUE THREAD

**Issue by lisenet** [hashicorp/terraform-provider-aws#27627]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_detector

### Description

The page does not load.

### Would you like to implement a fix?

No

**Comment by Mattie112** [comment]
Not only that one but also others (if nog all), for example https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration
&
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket

**Comment by Mattie112** [comment]
Ah it seems there are multiple issues, this is the first one: https://github.com/hashicorp/terraform-provider-aws/issues/27623

**Comment by Mattie112** [comment]
@lisenet https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/guardduty_detector.html.markdown

**Comment by ewbankkit** [comment]
https://status.hashicorp.com/incidents/vbr6hdbp9y4g

**Comment by justinretzolk** [comment]
Hey y'all 👋 This was due to an incident with the Terraform Registry that [has now been resolved](https://status.hashicorp.com/incidents/vbr6hdbp9y4g), so we'll close this issue. If you have further issues with the Terraform Registry, please do let us know.
