### ISSUE TITLE
[Docs]: Document  page not opening 

### ISSUE THREAD

**Issue by brijeshyadav310** [hashicorp/terraform-provider-aws#27629]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_cluster

### Description

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_cluster

this page is not opening only showing loading icon.

when i saw a network there i found that api.min.css is not loading.

**Comment by ewbankkit** [comment]
https://status.hashicorp.com/incidents/vbr6hdbp9y4g

**Comment by justinretzolk** [comment]
Hey @brijeshyadav310 👋 This was due to an incident with the Terraform Registry that [has now been resolved](https://status.hashicorp.com/incidents/vbr6hdbp9y4g), so we'll close this issue. If you have further issues with the Terraform Registry, please do let us know.
