### ISSUE TITLE
[Docs]: Documentation site is not loading 

### ISSUE THREAD

**Issue by dmeadows** [hashicorp/terraform-provider-aws#27623]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/3.49.0/docs/resources/acm_certificate

### Description

Sites are not loading the docs.

**Comment by kenfusion** [comment]
It's not just AWS provider, BTW

**Comment by bearrito** [comment]
Replicated on Chrome and Firefox. Not behind any firewall, proxy or content filtering.

**Comment by Mattie112** [comment]
You can see the docs here if you need them: https://github.com/hashicorp/terraform-provider-aws/tree/main/website/docs/r

**Comment by lisenet** [comment]
Just FYI, Azure docs are also not loading.

**Comment by kenfusion** [comment]
https://status.hashicorp.com/incidents/vbr6hdbp9y4g

**Comment by justinretzolk** [comment]
Hey y'all 👋 This was due to an incident with the Terraform Registry that [has now been resolved](https://status.hashicorp.com/incidents/vbr6hdbp9y4g), so we'll close this issue. If you have further issues with the Terraform Registry, please do let us know.
