### ISSUE TITLE
[Bug]: Documentation page for data_aws_iam_policy_document is not loading

### ISSUE THREAD

**Issue by ChristosDragios** [hashicorp/terraform-provider-aws#27628]
### Terraform Core Version

-

### AWS Provider Version

-

### Affected Resource(s)

webpage https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document 
does not load.

### Expected Behavior

load the documentation page.

### Actual Behavior

page is hanging in loading without showing the documentation part.

### Terraform Configuration Files

-

### Steps to Reproduce

launch https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document

**Comment by asosnovsky** [comment]
it actually seems like this is the case for all documentation including older versions

**Comment by pavelpp-topia** [comment]
it looks like a global issue for all providers

**Comment by ewbankkit** [comment]
https://status.hashicorp.com/incidents/vbr6hdbp9y4g

**Comment by justinretzolk** [comment]
Hey y'all 👋 This was due to an incident with the Terraform Registry that [has now been resolved](https://status.hashicorp.com/incidents/vbr6hdbp9y4g), so we'll close this issue. If you have further issues with the Terraform Registry, please do let us know.
