### ISSUE TITLE
[Docs]: aws_ecs_cluster documentation not loading

### ISSUE THREAD

**Issue by calebvarghese** [hashicorp/terraform-provider-aws#27626]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_cluster

### Description

network panel says its an API error
<img width="1001" alt="Screen Shot 2022-11-03 at 10 44 08 AM" src="https://user-images.githubusercontent.com/85652661/199752294-2da39f4d-642f-47cd-9935-6cdfcdc00586.png">

### Would you like to implement a fix?

No

**Comment by Mattie112** [comment]
You can see the docs here if you need them: https://github.com/hashicorp/terraform-provider-aws/tree/main/website/docs/r

**Comment by justinretzolk** [comment]
Hey @calebvarghese 👋 There's currently an issue with the Terraform Registry site as a whole. The status may be tracked here: https://status.hashicorp.com/incidents/vbr6hdbp9y4g. I'll follow up to let you know when the incident has been resolved.

**Comment by justinretzolk** [comment]
Just as I say that, the issue has been resolved, so I'll close this issue for now. Please do let us know if you experience further troubles with the Terraform Registry.
