### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by jamny1** [hashicorp/terraform-provider-aws#27630]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_versioning

### Description

Any time I try to access any of the aws provider documentation it is just clocking - never displaying the content.
![terraformawsregistrynotresponding](https://user-images.githubusercontent.com/11352252/199758454-54cba04c-2f40-4a49-81db-233f8073b9b4.JPG)

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @jamny1 👋 This incident [has now been resolved](https://status.hashicorp.com/incidents/vbr6hdbp9y4g), so we'll close this issue. If you have further issues with the Terraform Registry, please do let us know.
