### ISSUE TITLE
[Docs]: EventBridge Resources & Data Sources documentation pages don't load

### ISSUE THREAD

**Issue by Gumdro** [hashicorp/terraform-provider-aws#27633]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_target

### Description

The pages don't load for any of the version of the documentation

**Comment by justinretzolk** [comment]
Hey @Gumdro 👋 This was due to an incident with the Terraform Registry that [has now been resolved](https://status.hashicorp.com/incidents/vbr6hdbp9y4g), so we'll close this issue. If you have further issues with the Terraform Registry, please do let us know.
