### ISSUE TITLE
[Docs]: AWS s3_bucket_lifecycle_configuration not loading

### ISSUE THREAD

**Issue by skargoodrx** [hashicorp/terraform-provider-aws#27635]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration

### Description

Page will not load. Had colleagues verify on their end using various browsers. Able to replicate behavior.

most of the documentation links are not loading"

1. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_intelligent_tiering_configuration
2. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_cors_configuration

**Comment by tmauricio-imaginary** [comment]
Hi, https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy_attachment and several others the same is happening. UI loading infinitely:
![image](https://user-images.githubusercontent.com/86302079/199766347-4f17c419-6028-4217-bb55-1f11288bdeee.png)
