### ISSUE TITLE
[Docs]: AWS ASG Page not loading

### ISSUE THREAD

**Issue by loadedmind** [hashicorp/terraform-provider-aws#27634]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group

### Description

Page will not load. Had colleagues verify on their end using various browsers. Able to replicate behavior.

**Comment by DimitrijeManic** [comment]
Not only related to ASG, all resources are broken across providers.

**Comment by jar-b** [comment]
https://status.hashicorp.com/incidents/vbr6hdbp9y4g
