### ISSUE TITLE
[Docs]:  cloudwatch_log_group doesn't load

### ISSUE THREAD

**Issue by jeremiahlukus** [hashicorp/terraform-provider-aws#27631]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group

### Description

Url does not load 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group

**Comment by ewbankkit** [comment]
https://status.hashicorp.com/incidents/vbr6hdbp9y4g

**Comment by justinretzolk** [comment]
Hey @jeremiahlukus 👋 This was due to an incident with the Terraform Registry that [has now been resolved](https://status.hashicorp.com/incidents/vbr6hdbp9y4g), so we'll close this issue. If you have further issues with the Terraform Registry, please do let us know.
