### ISSUE TITLE
[Docs]: Terraform for AWS S3 Bucket Lifecycle Configuration does not open

### ISSUE THREAD

**Issue by markharrison4848** [hashicorp/terraform-provider-aws#27636]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration

### Description

Documentation Hangs and doesn't open. I have tried using older versions via the alongside-Picklist, but I get the same response. 

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration

### Would you like to implement a fix?

No

**Comment by NivEz** [comment]
This is occuring across other providers not only AWS

**Comment by justinretzolk** [comment]
Hey y'all 👋 This was due to an incident with the Terraform Registry that [has now been resolved](https://status.hashicorp.com/incidents/vbr6hdbp9y4g), so we'll close this issue. If you have further issues with the Terraform Registry, please do let us know.
