### ISSUE TITLE
[Enhancement]: Add resource timeouts for aws_sfn_state_machine

### ISSUE THREAD

**Issue by sairamkotapati-github** [hashicorp/terraform-provider-aws#27673]
### Description

Currently aws_sfn_state_machine does not provide access to timeouts block and defaults to 5 minutes. But in some cases deleting a state machine can take more than 5 minutes. This feature would add customizable timers for create/update/delete to service/sfn similar to this: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#timeouts

### Affected Resource(s) and/or Data Source(s)

aws_sfn_state_machine

### Potential Terraform Configuration

```terraform
resource "aws_sfn_state_machine" "example" {
  # ...

  timeouts {
    create = "20m"
    delete = "20m"
  }
}
```

### Would you like to implement a fix?

No

**Comment by jasonarewhy** [comment]
It would also be nice if this acted more like the API for delete and performed the operation async, rather than waiting for the delete to finish. Even without running executions, the state machine resource can take several minutes to disappear, and this adds a lot of unnecessary time to an apply.
