### ISSUE TITLE
[Bug]: Route 53 Resolver resources got created but not working

### ISSUE THREAD

**Issue by foxlzl** [hashicorp/terraform-provider-aws#27694]
### Terraform Core Version

1.2.4

### AWS Provider Version

4.37.0

### Affected Resource(s)

Route 53 Resolver:
aws_route53_resolver_endpoint
aws_route53_resolver_rule
aws_route53_resolver_rule_association

### Expected Behavior

I use the following 3 resources to create an OUTBOUND endpoint and rule to resolve an internal domain.

aws_route53_resolver_endpoint
aws_route53_resolver_rule
aws_route53_resolver_rule_association

It works perfectly when I create them via console UI, so I copied the exact same values (VPC, subnet, SG etc.) and created the following TF codes (some info has been replaced by placeholders). The resources got created successfully and look identical to what I have done via UI. However, the internal domain is not getting resolved properly within the SG.

```terraform
resource "aws_route53_resolver_endpoint" "outbound" {
  name      = "rslvr-out-corps"
  direction = "OUTBOUND"

  security_group_ids = var.security_group_ids

  dynamic "ip_address" {
    for_each = toset(var.subnet_ids)
    content {
      subnet_id = ip_address.key
    }
  }

  tags = var.tags
}

resource "aws_route53_resolver_rule" "fwd_corp" {
  domain_name  = "xxxxxxx.com"
  name                 = "CORP"
  rule_type          = "FORWARD"
  resolver_endpoint_id = aws_route53_resolver_endpoint.outbound.id

  target_ip {
    ip   = "x.x.x.1"
  }
  target_ip {
    ip   = "x.x.x.2"
  }

  tags = var.tags
}

resource "aws_route53_resolver_rule_association" "fwd_corp" {
  resolver_rule_id = aws_route53_resolver_rule.fwd_corp.id
  vpc_id           = var.vpc_id
}
```

### Actual Behavior

The resolver endpoint and rules got created successfully but not working as expected, as the internal domain is still not getting resolved. If I create the same resources from console UI directly, they work.

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws        = {
      source  = "hashicorp/aws"
      version = "4.37.0"
    }
  }
}
```

### Steps to Reproduce

1. modify the above snippet to create aws_route53_resolver_endpoint, aws_route53_resolver_rule, and aws_route53_resolver_rule_association
2. try resolving the given domain within the given SG and it will fail by reporting "Could not resolve host: xxxxx"
3. remove the resources created by Terraform and recreate them manually from Console UI.
4. repeat step2 and it works

**Comment by justinretzolk** [comment]
Hey @foxlzl 👋 Thank you for taking the time to raise this! Given that you're not seeing any errors (that you've mentioned), I suspect that there may be something amiss in the configuration. With that in mind, you might have better luck asking in the [AWS provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws), as we try to keep GitHub Issues scoped to feature enhancements and bugs with the provider.

If I've misunderstood and this seems to be a bug with the provider, we'd absolutely be happy to take a look as time permits.

**Comment by foxlzl** [comment]
Hi @justinretzolk , Thanks for your reply. I'm closing this as it turned out to be some DNS glitch from our infra side..
