### ISSUE TITLE
Add IPv6 support to ElastiCache

### ISSUE THREAD

**Issue by bschaatsbergen** [hashicorp/terraform-provider-aws#27700]
### Description

AWS recently announced the support of the IPv6 protocol in ElastiCache. IPv6 is supported for workloads using Redis engine version 6.2 onward or Memcached engine version 1.6.6 on all instances built on the Nitro system.

### Affected Resource(s) and/or Data Source(s)

aws_elasticache_cluster

### Potential Terraform Configuration

```terraform
resource "aws_elasticache_cluster" "example" {
 # .... other configuration ....
 ip_discovery = "ipv6"
}
```

### References

Announcement: https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-elasticache-supports-ipv6/
API: https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateCacheCluster.html

### Would you like to implement a fix?

Yes, together with @jms200

**Comment by jms200** [comment]
Will pick this up and begin working on it.
