### ISSUE TITLE
[Enhancement]: Add gp3 storage_type support to aws_db_instance

### ISSUE THREAD

**Issue by katdev** [hashicorp/terraform-provider-aws#27702]
### Description

As of November 4(ish), [the gp3 storage type is now supported on RDS](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/WhatsNew.html), but it's not yet supported by the latest version of the AWS provider. Attempting to specify gp3 results in:
```terraform
│ Error: expected storage_type to be one of [standard gp2 io1], got gp3
│ 
│   with aws_db_instance.db_instance,
│   on .terraform/main.tf line 67, in resource "aws_db_instance" "db_instance":
│   67:   storage_type                        = "gp3"
```
Please add support to the AWS provider for this storage type, along with support for the advanced settings available with gp3, `Provisioned IOPS` and `Storage throughput`.

### Affected Resource(s) and/or Data Source(s)

aws_db_instance

### Potential Terraform Configuration

```terraform
resource "aws_db_instance" "default" {
  ...
  allocated_storage    = 10
  storage_type         = "gp3"
  provisioned_iops     = 12000
  storage_throughput   = 500
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-rds-general-purpose-gp3-storage-volumes/).
[User guide](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html#Concepts.Storage.GeneralSSD).

### Would you like to implement a fix?

No, thank you

**Comment by bschaatsbergen** [comment]
Hi @katdev, thanks for raising this issue. I'll pick it up 👍

**Comment by bschaatsbergen** [comment]
Fixed by @erz4 in #27670 👏

**Comment by theintz** [comment]
> The same issue lies in Ansible rds_instance module too. It is not supporting creation of new RDS instance when passing storage type as gp3. Any fixes for that ?

You should probably ask that question in the Ansible repo :)

**Comment by rodrigoechaide** [comment]
Hello! What about this issue? Is somebody working on it?

**Comment by etiennechabert** [comment]
See this PR and comment: https://github.com/hashicorp/terraform-provider-aws/pull/27670#pullrequestreview-1185132040

My understanding is that @gdavison and his team might take over the PR that @erz4 started

**Comment by DanielViglione** [comment]
talk about perfect timing! gp3 for rds is exactly what I wanted.

**Comment by etiennechabert** [comment]
Foremost, thanks a lot for bringing this change that quickly @ewbankkit, and @erz4 as well as everyone involved 👏 

Sadly, it seems that there is a bug for existing RDS instances blocking the switch from gp2 to gp3, you will most likely be blocked by this error:
```
InvalidParameterCombination: You can't specify IOPS or storage throughput for engine postgres and a storage size less than 400
```

FYI, an issue already exists for this bug: https://github.com/hashicorp/terraform-provider-aws/issues/28160

Maybe you want to give your 👍 there, if this is also a blocker for you.
