### ISSUE TITLE
Is there a way to skip or ignore "DHCP options" and "association" manual changes (AWS Console) in terraform?

### ISSUE THREAD

**Issue by pj020620** [hashicorp/terraform-provider-aws#27710]
### Description

```terraform
resource "aws_vpc_dhcp_options" "this" {
  domain_name_servers = [
    "AmazonProvidedDNS",
  ]

  lifecycle {
    ignore_changes = all
  }
}

resource "aws_vpc_dhcp_options_association" "this" {
  dhcp_options_id = aws_vpc_dhcp_options.this.id
  vpc_id          = module.vpc.vpc_id
  lifecycle {
    ignore_changes = [
      vpc_id, # vpc id
      id, # id
      dhcp_options_id # dhcp id
    ]
  }
}
```

**Comment by justinretzolk** [comment]
Hey @pj020620 👋 Can you provide a bit of additional context to help me understand what you're looking to achieve?

**Comment by pj020620** [comment]
> 

Hi Justin, thanks for quick response,.

I’ve a requirement to ignore DHCP Options, association settings from terraform which has manually modified the changes in AWS console,.

we create the vpc, dhcp options and the association using terraform, sometimes our clients create a new dhcp options and use their own NTP, dns resolver based on their requirement and associate to the vpc which is originally created by terraform, so the requirement here is to ignore /skip only the dhcp options and associations settings(user modified through AWS console) in next terraform plan and apply. 

thanks 
Pj
