### ISSUE TITLE
[Enhancement]: Support ECDSA certificates for aws_acm_certificate resources

### ISSUE THREAD

**Issue by robmoss2k** [hashicorp/terraform-provider-aws#27715]
### Description

As of 2022-11-08, ACM supports ECDSA certificates. Please add support for this parameter.

### Affected Resource(s) and/or Data Source(s)

[aws_acm_certificate resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate)
[aws_acm_certificate data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/acm_certificate)

### Potential Terraform Configuration

```terraform
resource "aws_acm_certificate" "ecdsa" {
  ...
  key_algorithm = "EC_prime256v1"
}
```

### References

https://aws.amazon.com/about-aws/whats-new/2022/11/aws-certificate-manager-elliptic-curve-digital-signature-algorithm-tls-certificates/
https://docs.aws.amazon.com/acm/latest/userguide/acm-certificate.html#algorithms
https://docs.aws.amazon.com/acm/latest/APIReference/API_RequestCertificate.html#API_RequestCertificate_RequestSyntax

### Would you like to implement a fix?

I wouldn't know how.

**Comment by ewbankkit** [comment]
Requires [AWS SDK for Go v1.44.133](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.133): #27712.

**Comment by JamesJJ** [comment]
PR #27781 should resolve this for the `aws_acm_certificate` resource, and allow you to request ECDSA certificates from ACM.

Personally, I'd suggest combining the existing data source with the [`tls_certificate`](https://registry.terraform.io/providers/hashicorp/tls/latest/docs/data-sources/certificate) data source if you need to determine the algorithm of an ACM certificate that was created/imported outside of terraform, for example:

```
data "aws_acm_certificate" "example" {
  domain    = "www.example.com"
  types     = ["AMAZON_ISSUED"]
  key_types = ["RSA_2048", "EC_prime256v1", "EC_secp384r1"]
}

data "tls_certificate" "example" {
  content = data.aws_acm_certificate.example.certificate
}

output "signature_algorithm" {
  value = data.tls_certificate.example.certificates[0].signature_algorithm
}
```

```
Outputs:

signature_algorithm = "ECDSA-SHA256"
```
