### ISSUE TITLE
[New Service]: AWS Resource Explorer

### ISSUE THREAD

**Issue by jkrnak** [hashicorp/terraform-provider-aws#27717]
### Description

AWS has release a new service that helps finding resources in accounts. It indexes all resource on regions it is set up and then one can query for resource types, by tags, missing tags etc...

From their doc:
> AWS Resource Explorer is a resource search and discovery service. By using Resource Explorer, you can explore your resources using an internet search engine-like experience. Examples of resources include Amazon Relational Database Service (Amazon RDS) instances, Amazon Simple Storage Service (Amazon S3) buckets, or Amazon DynamoDB tables. You can search for your resources using resource metadata like names, tags, and IDs. Resource Explorer can search across all of the AWS Regions in your account in which you turn the service on, to simplify your cross-Region workloads.

It seems that the Go SDK doesn't yet support this feature, it came out yesterday (8th Nov)

### Requested Resource(s) and/or Data Source(s)

This may not be the best way to split it up.

#### Resources

* [x] [`aws_resourceexplorer2_index`](https://github.com/hashicorp/terraform-provider-aws/pull/28144)
* [x] [`aws_resourceexplorer2_view`](https://github.com/hashicorp/terraform-provider-aws/pull/28841)

#### Data Sources

* `aws_resourceexplorer2_query`

### References

https://aws.amazon.com/blogs/aws/introducing-aws-resource-explorer-quickly-find-resources-in-your-aws-account/
https://docs.aws.amazon.com/resource-explorer/latest/apireference/Welcome.html

**Comment by adzuci** [comment]
Looks like https://github.com/hashicorp/terraform-provider-aws/pull/27712 has merged.  Any ideas on the LOE of getting support added to the provider?

**Comment by lutemartin** [comment]
+1

**Comment by breathingdust** [comment]
Resolved as of [`v4.51.0`](https://github.com/hashicorp/terraform-provider-aws/blob/v4.51.0/CHANGELOG.md)
