### ISSUE TITLE
[Docs]: Typo in sesv2_configuration_set

### ISSUE THREAD

**Issue by rwky** [hashicorp/terraform-provider-aws#27727]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_configuration_set

### Description

Example says:

```
sendig_options {
    sending_enabled = true
  }
```
Should be

```
sending_options {
    sending_enabled = true
  }
```

`n` is missing from `sending`

**Comment by justinretzolk** [comment]
Hey @rwky 👋 Thanks for taking the time to raise this! I've opened a PR to fix the typo.
