### ISSUE TITLE
[Bug]: App Runner Observability catch-22

### ISSUE THREAD

**Issue by emarref** [hashicorp/terraform-provider-aws#27733]
### Terraform Core Version

1.3.4

### AWS Provider Version

4.38.0

### Affected Resource(s)

* aws_apprunner_service

### Expected Behavior

I should be able to omit the `observability_configuration` block entirely if I do not want observability, or at least disable it with the `observability_enabled = false` option within that block without specifying an arn.

### Actual Behavior

I created an App Runner service manually via the console (with no observability configured). I then imported it into my terraform configuration.

When I run `terraform plan` I get a diff notifying `observability_enabled = false -> null`.

<img width="479" alt="image" src="https://user-images.githubusercontent.com/556594/200937079-176920e9-fb5b-4e6e-8334-71aca15b87f7.png">

When I add the block to set this value to false then run `terraform plan` again, I get an error telling me that `observability_configuration_arn` is required.

<img width="636" alt="image" src="https://user-images.githubusercontent.com/556594/200937219-ea34990e-120f-4521-89d7-847648158b39.png">

When I try again with `observability_enabled = null` instead of false, I get the same error:

<img width="845" alt="image" src="https://user-images.githubusercontent.com/556594/200937514-b800e707-c1d0-4ea8-b93a-bde7ed876c61.png">

I think it is an issue with the validation. If `observability_enabled` is set to false, `observability_configuration_arn` should not be required.

### Relevant Error/Panic Output Snippet

```shell
Terraform will perform the following actions:

  # aws_apprunner_service.staging will be updated in-place
  ~ resource "aws_apprunner_service" "staging" {
        id                             = "arn:aws:apprunner:us-east-1:669859274049:service/mss-test/b394ed30588645e2b3ff9a98a3c3277e"
        tags                           = {}
        # (7 unchanged attributes hidden)

      - observability_configuration {
          - observability_enabled = false -> null
        }

        # (4 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Terraform Configuration Files

```terraform
resource "aws_apprunner_service" "staging" {
  service_name = "staging"

  source_configuration {
    auto_deployments_enabled = true

    authentication_configuration {
      access_role_arn = data.aws_iam_role.app_runner_service_role.arn
    }

    image_repository {
      image_identifier      = "${aws_ecr_repository.staging.repository_url}:latest"
      image_repository_type = "ECR"

      image_configuration {
        port = 3000
      }
    }
  }
}
```

### Steps to Reproduce

terraform apply

**Comment by bschaatsbergen** [comment]
Good catch, thanks @emarref :+1:
