### ISSUE TITLE
[Bug]: error creating ElastiCache Replication Group: InvalidParameterCombination: Expected a parameter group of family redis7 but found one of family redis6.x

### ISSUE THREAD

**Issue by wgaldino** [hashicorp/terraform-provider-aws#27748]
### Terraform Core Version

1.3.4

### AWS Provider Version

4.38.0, 4.37.0, 4.36.0, 4.35.0, 4.34.0

### Affected Resource(s)

* aws_elasticache_replication_group

### Expected Behavior

I noticed that since yesterday any `aws_elasticache_replication_group` resource that before could have been created with the code below was failing.

```terraform
resource "aws_elasticache_replication_group" "service" {
  count = local.count

  replication_group_id = "service-${local.some_sufix}"
  description          = "Service Regional Redis cluster"
  engine               = "redis"
  node_type = var.node_type
  automatic_failover_enabled = true

  parameter_group_name = "default.redis6.x.cluster.on"
  
  subnet_group_name  = aws_elasticache_subnet_group.service[0].name
  security_group_ids = [data.aws_security_group.default.id]
  num_node_groups    = var.node_count
  apply_immediately  = true
}
```

### Actual Behavior

Apply fails with the following message:

```bash
Error: error creating ElastiCache Replication Group: InvalidParameterCombination: Expected a parameter group of family redis7 but found one of family redis6.x
```

### Terraform Configuration Files

```terraform
resource "aws_elasticache_replication_group" "service" {
  count = local.count

  replication_group_id = "service-${local.some_sufix}"
  description          = "Service Regional Redis cluster"
  engine               = "redis"
  node_type = var.node_type
  automatic_failover_enabled = true

  parameter_group_name = "default.redis6.x.cluster.on"
  
  subnet_group_name  = aws_elasticache_subnet_group.service[0].name
  security_group_ids = [data.aws_security_group.default.id]
  num_node_groups    = var.node_count
  apply_immediately  = true
}
```

### Steps to Reproduce

Terraform init
Terraform apply

### Important Factoids

Today after some investigation I could extract the following facts:

- In 1 (`eu-central-1`) out of 4 regions succeeded and all resources got successfully created.
- Doesn't matter which version of the provider is used the outcome remains the same.
- The documentation is somehow outdated for this edge case since it implies that `engine_version` is optional, however if you are using the `parameter_group_name` argument it will fail. Mainly because if the `engine_version` is not defined it will get the latest (redis7) and that will clash with whatever is set in `parameter_group_name`.

The way to solve this issue was to add the `engine_version` argument to the resource definition. That's exactly the behaviour you get when creating the cluster through the GUI, you cannot set `parameter_group_name` as  `default.redis6.x.cluster.on` if you select a different `engine_version`.

Possible ways of fixing it would be:

1. Update the documentation so that is states that you cannot arbitrarily set `parameter_group_name` when `engine_version` is omitted. Enforce that those need to match somehow.
2. Since the documentation states that `engine_version` is optional, why not infer the engine based on the `parameter_group_name` value? Doesn't it make sense? Is that really tricky?

**Comment by justinretzolk** [comment]
Related #27709

**Comment by trevorrea** [comment]
Hi,

This isn't a bug. 

You need to set the engine_version parameter as otherwise it defaults to the latest which is 7.x - this was released on November 8th which corresponds to roughly the time this started happening.

See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#engine_version and https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/WhatsNew.html

e.g.

```
resource "aws_elasticache_replication_group" "service" {
  count                      = local.count
  replication_group_id       = "service-${local.some_sufix}"
  description                = "Service Regional Redis cluster"
  engine                     = "redis"
  engine_version             = "6.x"
  node_type                  = var.node_type
  automatic_failover_enabled = true
  parameter_group_name       = "default.redis6.x.cluster.on"
  subnet_group_name          = aws_elasticache_subnet_group.service[0].name
  security_group_ids         = [data.aws_security_group.default.id]
  num_node_groups            = var.node_count
  apply_immediately          = true
  lifecycle {
    ignore_changes = [
      engine_version
    ]
  }
}
```

Engine version will be 6.x or 6.0 or 6.2 depending on your preferences.

Thanks,
Trevor
