### ISSUE TITLE
[Enhancement]: allow kms data source to reference aws created key by alias

### ISSUE THREAD

**Issue by lordz-md** [hashicorp/terraform-provider-aws#27746]
### Description

When using 
`data "aws_kms_key" "by_alias" {
  key_id = "alias/my-key"
}`

if you use

`data "aws_kms_key" "by_alias" {
  key_id = "aws/dynamodb"
}`

to reference the AWS default key, you will the following error
` Error: "key_id" must be one of the following patterns: [A-Za-z0-9-]+, arn:[^:]+:kms:[^:]+:[^:]+:key/[A-Za-z0-9-]+, alias/[a-zA-Z0-9:/_-]+ or arn:[^:]+:kms:[^:]+:[^:]+:alias/[a-zA-Z0-9:/_-]+`

**Comment by mtt88** [comment]
It's possible to access an 'AWS Managed Key' using the `aws_kms_key` datasource by prefixing `alias/` infront of the service. I.e.

```
data "aws_kms_key" "dynamodb" {
  key_id = "alias/aws/dynamodb"
}
```

See [about aliases](https://docs.aws.amazon.com/kms/latest/developerguide/alias-about.html)

**Comment by lordz-md** [comment]
> 

Thanks.
