### ISSUE TITLE
[Docs]: resource/aws_autoscaling_group: Add price-capacity-optimized spot_allocation_strategy

### ISSUE THREAD

**Issue by lachlancooper** [hashicorp/terraform-provider-aws#27759]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#spot_allocation_strategy

### Description

AWS recently added a new spot allocation strategy (which is now recommended for most workloads) called `price-capacity-optimized`. This should be added to the documentation for the `mixed_instances_policy` `instances_distribution` block.

### References

- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-fleet-allocation-strategy.html
- https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_InstancesDistribution.html
- [Announcement](https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-ec2-price-capacity-optimized-allocation-strategy-provisioning-ec2-spot-instances/)

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
Requires [AWS SDK for Go v1.44.135](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.135): https://github.com/hashicorp/terraform-provider-aws/pull/27755.
