### ISSUE TITLE
[New Service]: EventBridge Scheduler

### ISSUE THREAD

**Issue by roberth-k** [hashicorp/terraform-provider-aws#27760]
### Description

EventBridge Scheduler [1] is a new capability from [Amazon EventBridge](https://aws.amazon.com/eventbridge/) that allows you to create, run, and manage scheduled tasks at scale.

As of 11 Nov 2022, it doesn't look like this has landed yet in any of the SDK-s or CLI-s. Based on how they've structured documentation and some of the links, my guess is this is considered to be a new service (short name `scheduler`) rather than part of EventBridge or CloudWatch Events.

### Requested Resource(s) and/or Data Source(s)

* `aws_scheduler_schedule` _or_ `aws_cloudwatch_event_schedule`
* `aws_scheduler_schedule_group` _or_ `aws_cloudwatch_event_schedule_group`

### Potential Terraform Configuration

```terraform
// https://docs.aws.amazon.com/scheduler/latest/APIReference/API_CreateScheduleGroup.html
resource "aws_scheduler_schedule_group" "example" {
  name = "example-schedule-group"
}

// https://docs.aws.amazon.com/scheduler/latest/APIReference/API_CreateSchedule.html
resource "aws_scheduler_schedule" "example" {
  group_name          = aws_scheduler_schedule_group.example.name 
  description         = "This is an example."
  schedule_expression = "rate(1 day)"
  state               = "ENABLED"

  target {
    arn = aws_sqs_queue.example.arn

    sqs_parameters {
      message_group_id = "example-message-group"
    }
  }
}
```

### References

- [1] Announcement: https://aws.amazon.com/blogs/compute/introducing-amazon-eventbridge-scheduler/
- [2] User Guide: https://docs.aws.amazon.com/scheduler/latest/UserGuide/what-is-scheduler.html
- [3] API Documentation: https://docs.aws.amazon.com/scheduler/latest/APIReference/Welcome.html

### Would you like to implement a fix?

_Yes_

**Comment by roberth-k** [comment]
I'll pick this up as soon as it lands in the SDK-s.

**Comment by ewbankkit** [comment]
Requires [AWS SDK for Go v1.44.135](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.135): https://github.com/hashicorp/terraform-provider-aws/pull/27755.

Let's go with `aws_scheduler_...` to match the API package name.

**Comment by atsushi-ishibashi** [comment]
@roberth-k 
How about `aws_scheduler_schedule`? Can I develop?

**Comment by atsushi-ishibashi** [comment]
If you have anything under development about to completion, please let me know. I'll close PR🙋

**Comment by atsushi-ishibashi** [comment]
If you have anything under development about to completion, please let me know. I'll close PR🙋

**Comment by roberth-k** [comment]
> If you have anything under development about to completion, please let me know. I'll close PR🙋

Hi @atsushi-ishibashi. Indeed, I’m working on the `aws_scheduler_schedule` resource. With any luck it should be ready by the next release.

**Comment by roberth-k** [comment]
> Oh, I see.
> 
> > With any luck it should be ready by the next release.
> 
> I'd like to use scheduler on my work at the next release so could I take on this implementation? I finished main logic🙋‍♂️ Sorry for bother

Hi,

Factoring in acceptance tests and documentation, I'm probably a bit closer to wrapping this up -- only a few of the templated targets remain. I'll publish the PR as soon as possible.
