### ISSUE TITLE
[Bug]: expected storage_type to be one of [standard gp2 io1], got gp3 for RDS storage type

### ISSUE THREAD

**Issue by markvdlaan93** [hashicorp/terraform-provider-aws#27782]
### Terraform Core Version

1.2.1

### AWS Provider Version

4.39.0

### Affected Resource(s)

* aws_db_instance

### Expected Behavior

It should be possible to adjust storage_type to gp3.

### Actual Behavior

expected storage_type to be one of [standard gp2 io1], got gp3

### Terraform Configuration Files

```
resource "aws_db_instance" "this" {
  ......
  storage_type = "gp3"
  ......
}

### Steps to Reproduce

Run `terraform plan` on a `aws_db_instance` resource with storage_type value gp3

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-rds-general-purpose-gp3-storage-volumes/

### Would you like to implement a fix?

_No response_

**Comment by ewbankkit** [comment]
@markvdlaan93 Thanks for raising this issue.
It has already been noticed in #27702. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
