### ISSUE TITLE
[Docs]: Confirmation regarding deprecate_rule block from aws_dlm_lifecycle_policy resource

### ISSUE THREAD

**Issue by MayuriD89** [hashicorp/terraform-provider-aws#27786]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/3.70.0/docs/resources/dlm_lifecycle_policy

### Description

In v3.70.0 of dlm_lifecycle_policy, deprecate_rule block was added which can be specified only for AMI policy types.
We have confirmed the behavior from terraform and CLI too. This is mentioned in the AWS CLI and API documents. Please refer following documentation for the same -

> https://docs.aws.amazon.com/cli/latest/reference/dlm/create-lifecycle-policy.html

v3.70.0 creates only EBS snapshot types policy and not AMI policies, deprecate_rule is not supported by EBS snapshot policy types, so why in the first place deprecate_rule block was added when it was of no use.

**NOTE:** In latest version policy types parameter is added where we can specify types of policy and hence deprecate_rule block can be specified in that version.

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @MayuriD89 👋 Thanks for taking the time to raise this! I took a look over the PR that added the `deprecate_rule` argument, and it looks like it was added while adding [support for cross-region copy a couple of years ago](https://github.com/hashicorp/terraform-provider-aws/pull/12868). It wasn't specifically discussed in the pull request, so it's hard to say why the argument was added at that point if it wasn't possible to use it. I wish I had a more useful answer than that!

Given that the appropriate arguments have been added to make the `deprecated_rule` useful in the more recent versions of the provider, I'm going to close this issue. If you feel I've done this in error, please do let me know.
