### ISSUE TITLE
[Bug]: create rds mariadb failed

### ISSUE THREAD

**Issue by johanwinter1** [hashicorp/terraform-provider-aws#27792]
### Terraform Core Version

1.2.5

### AWS Provider Version

4.39

### Affected Resource(s)

aws rds

### Expected Behavior

create rds maridb

### Actual Behavior

Error: expected engine to be one of [aurora aurora-mysql aurora-postgresql mysql postgres], got mariadb

### Relevant Error/Panic Output Snippet

```shell
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
╷
│ Error: expected engine to be one of [aurora aurora-mysql aurora-postgresql mysql postgres], got mariadb
│
│ with aws_rds_cluster.this,
│ on dbcluster.tf line 76, in resource "aws_rds_cluster" "this":
│ 76: engine = "mariadb"
│
```

### Terraform Configuration Files

resource "aws_rds_cluster" "this" {
cluster_identifier = "${var.name}-${var.env}-cluster"
engine = "mariadb"
engine_version = "10.6"
... snip

### Steps to Reproduce

terraform plan

**Comment by gdavison** [comment]
Hi @johanwinter1. AWS does not support the MariaDB engine when creating an `aws_rds_cluster`. To use MariaDB, use the resource type `aws_db_instance`.

**Comment by johanwinter1** [comment]
thank very much for your answer.
