### ISSUE TITLE
[Docs]: engine_version for OpenSearch is documented incorrectly

### ISSUE THREAD

**Issue by varfrog** [hashicorp/terraform-provider-aws#27796]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearch_domain

### Description

In the [Elasticsearch vs. OpenSearch](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearch_domain#elasticsearch-vs-opensearch) section,
`Versions are specified differently - e.g., Elasticsearch_7.10 with OpenSearch vs. 7.10 for Elasticsearch.`

That seems to be incorrect as for OpenSearch the engine_version is prefixed with `OpenSearch`, not `Elasticsearch`. E.g. `engine_version = "OpenSearch_1.3"` unless I am missing something.

Also, below in examples engine_version seems to be correct:
```
resource "aws_opensearch_domain" "example" {
  domain_name    = var.domain
  engine_version = "OpenSearch_1.0"
```

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @varfrog 👋 Thanks for taking the time to raise this! The section that you're looking at is actually referring to the differences between Terraform configurations using the [`aws_elasticsearch_domain`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain) and [`aws_opensearch_domain`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearch_domain) resources.

On the `aws_elasticsearch_domain` resource, the `elasticsearch_version` argument takes a value that looks like `1.5`, while the `aws_opensearch_domain` resource's `version` argument accepts values such as `Elasticsearch_7.10` or `OpenSearch_1.0` (keeping in mind that OpenSearch supports both [OpenSearch and certain OSS Elasticsearch versions](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/what-is.html#choosing-version)).
