### ISSUE TITLE
[Enhancement]: add support for GP3 EBS volumes in RDS instances

### ISSUE THREAD

**Issue by IdanYaffe** [hashicorp/terraform-provider-aws#27809]
### Description

Following this announcement:
https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-rds-general-purpose-gp3-storage-volumes/

it would be great to be able to create RDS instances with GP3 EBS volumes.

 

### Affected Resource(s) and/or Data Source(s)

- aws_rds_cluster
- aws_rds_cluster_instance

### Potential Terraform Configuration

```terraform
resource "aws_rds_cluster_instance" "cluster_instance" {
   storage_type = "gp2"/"gp3"
   storage_size = "100Gb" 
   storage_iops = ""
   ....
}
```

### References

https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-rds-general-purpose-gp3-storage-volumes/

**Comment by ewbankkit** [comment]
@IdanYaffe Thanks for raising this issue.
It has already been noticed in #27702. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
