### ISSUE TITLE
[New]: AWS SSO Application Resource

### ISSUE THREAD

**Issue by sherifkayad** [hashicorp/terraform-provider-aws#27853]
### Description

Hello, I couldn't find a resource for managing SSO Applications (Application Assignments) as per the AWS Console. Check my screenshot attached.

![image](https://user-images.githubusercontent.com/8362784/202398148-ecf0ed1a-6fc3-46a4-b358-a6c4d9f417c2.png)

### Requested Resource(s) and/or Data Source(s)

`aws_sso_application` or `aws_identitystore_application` maybe?

### Would you like to implement a fix?

No

**Comment by jd-sandk** [comment]
Can we get something like the requested: `aws_sso_application` or `aws_identitystore_application`, please 😄 

-Thanks!

**Comment by garym-krrv** [comment]
BUMP.. needing this also!

**Comment by TomSp** [comment]
needed as well

**Comment by fbeering** [comment]
Same Here

**Comment by AxelFulop** [comment]
Same here

**Comment by kruc** [comment]
Same here

**Comment by vibhuyadav** [comment]
We need this

**Comment by trickyearlobe** [comment]
Bump... also need this.
Need to be able to assign apps to large number of people/groups

**Comment by AyoubUmoru** [comment]
Same here - need this

**Comment by ugurcancaykara** [comment]
+1

**Comment by garym-krrv** [comment]
Problem is I don't think it's available in the AWS SDK.

**Comment by JeroenRijks** [comment]
Is there a standardised process for asking AWS to publishing API endpoints & SDK methods for this?

**Comment by oleksandrsv** [comment]
I just got reply from AWS Support that it is not possible to assign to AWS SSO Application users or groups, sounds urgent to implement, wdyt?
