### ISSUE TITLE
[Bug]: aws_apprunner_service returns empty value for "service_url"

### ISSUE THREAD

**Issue by pabloB2sys** [hashicorp/terraform-provider-aws#27861]
### Terraform Core Version

1.1.0

### AWS Provider Version

>=4.38.0

### Affected Resource(s)

aws_apprunner_service

### Expected Behavior

service_url is not empty

### Actual Behavior

service_url = null

### Relevant Error/Panic Output Snippet

```shell
aws_apprunner_service.this[0].service_url
```

### Terraform Configuration Files

[apprunner-error.zip](https://github.com/hashicorp/terraform-provider-aws/files/10034297/apprunner-error.zip)

### Steps to Reproduce

decompress the zip file and run:

terraform apply

**Comment by sgrilux** [comment]
It looks the error is not in the aws provider nor in the sdk. It's in AWS api.
Despite what the documentation says, when you call DescribeService it does not return ServiceUrl as it's documented, however it does if you call ListServices.

**Comment by pabloB2sys** [comment]
What do you recomend me to do ? 
Because I'm working with terraform and the code needs this information as an output.

**Comment by sgrilux** [comment]
I think this will take time. I am going to raise an issue in the SDK repo hoping this will passed along the teams and fix it. 
In the meantime you can probably use a `null_resource` with `local-exec` provisioner to call `ListService` and filtering out with --query or jq.

**Comment by sgrilux** [comment]
After digging a bit more, it looks the problem occurs only if the service is deployed privately and not publicly accessible. However the console returns the Url in any case.

**Comment by pabloB2sys** [comment]
That is correct the amazon console returns the proper URL in both cases. 
As a requirement we have to move the service to a private vpc and have problems with security groups and open ports

**Comment by sgrilux** [comment]
https://github.com/aws/aws-sdk-go/issues/4635

**Comment by carlduevel** [comment]
I worked around this by using the dns_target attribute of the [aws_apprunner_custom_domain_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apprunner_custom_domain_association) resource.
