### ISSUE TITLE
[Enhancement]: Eventbridge Scheduler

### ISSUE THREAD

**Issue by roberto-nascimento** [hashicorp/terraform-provider-aws#27864]
### Description

Hello, please consider to add new features for aws eventbridge.

Scheduler and Scheduler group

### Affected Resource(s) and/or Data Source(s)

aws_cloudwatch_event_*

### References

https://aws.amazon.com/pt/blogs/compute/introducing-amazon-eventbridge-scheduler/
https://docs.aws.amazon.com/scheduler/latest/UserGuide/what-is-scheduler.html

**Comment by ewbankkit** [comment]
@roberto-nascimento Thanks for raising this issue.
It has already been noticed in #27760. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
