### ISSUE TITLE
[Bug]: Impossible to add Organizational Unit on existing aws_cloudformation_stack_set_instance

### ISSUE THREAD

**Issue by florenp** [hashicorp/terraform-provider-aws#27877]
### Terraform Core Version

1.3.1

### AWS Provider Version

4.39.0

### Affected Resource(s)

* aws_cloudformation_stack_set_instance

### Expected Behavior

Adding a new Organization Unit to list of organizational_unit_ids should deploy the stack_set_instance to the new OU.

### Actual Behavior

```shell
aws_cloudformation_stack_set_instance.my-stack-set-instance["us-west-2"] will be updated in-place
  ~ resource "aws_cloudformation_stack_set_instance" "my-stack-set-instance" {
        id                     = "xxxxxxx,xxxxxxxxxx,us-west-2"
        # (8 unchanged attributes hidden)

      ~ deployment_targets {
          ~ organizational_unit_ids = [
              + "ou-xxxxxxxxx",
                # (1 unchanged element hidden)
            ]
        }

        # (2 unchanged blocks hidden)
    }
```

### Relevant Error/Panic Output Snippet

```shell
Error: error updating CloudFormation StackSet Instance (xxxxxxx,123456789012,us-west-2): ValidationError: Organizational unit ou-xxxxxxxxx not found in StackSet
│       status code: 400, request id: 1826eb23-8df6-4538-ad5c-1b0563701c8b
│
│   with aws_cloudformation_stack_set_instance.my-stack-set-instance["us-west-2"],
│   on stack-set.tf line 66, in resource "aws_cloudformation_stack_set_instance" "my-stack-set-instance":
│   66: resource "aws_cloudformation_stack_set_instance" "my-stack-set-instance" {
```

### Terraform Configuration Files

.

### Steps to Reproduce

Create a stack set & stack set instance applying to an Organizational Unit.

Try to modify the stack set instance adding a new OU to the list of targets

**Comment by hellokhush** [comment]
What is the solution for this, is that resolved?

**Comment by rkno82** [comment]
We are also facing the issue. Any ideas?

**Comment by hellokhush** [comment]
I have found the work around for this, I have added stack in existing cloudformation stackset for other OU and deployed cloudformation through that manualy using aws console, and then I ran "Terraform apply command". It worked for me

![image](https://user-images.githubusercontent.com/28684004/208414064-64f2a3d1-1dc0-440f-922c-92b52b5f5f93.png)

**Comment by jjf130** [comment]
Manual workaround resolves the issue, but would be nice if there was an automated workaround (or better yet a fix). Trying to manage an AWS organization with consistent baseline tooling in accounts deployed with stacksets becomes very tedious because of this issue.

**Comment by cedricbastin** [comment]
As it is not possible to update the target OUs you can use this workaround which creates a separate StackSet instance for each OU such that no update API calls are used

old code which throws the error: `ValidationError: Organizational unit ou-xx-xxx has no instances in [eu-central-1]`
```
resource "aws_cloudformation_stack_set_instance" "instance" {
  deployment_targets {
    organizational_unit_ids = var.target_ous
  }
}
```

new code which uses a loop to create a StackSet instance for every OU:
```
resource "aws_cloudformation_stack_set_instance" "instance" {
  for_each = toset(var.target_ous)
  deployment_targets {
    organizational_unit_ids = [each.key]
  }
}
```

**Comment by jvanenckevort** [comment]
Any update on this?

**Comment by framirezcruz** [comment]
any updates on this

**Comment by jgarcia-pluralsight** [comment]
Any updates on this?

**Comment by aglittle** [comment]
Any updates on this bug?

**Comment by evantlueck** [comment]
I found a solution for this. I put it on a similar ticket here: https://github.com/hashicorp/terraform-provider-aws/issues/33785#issuecomment-1780233282

**Comment by evantlueck** [comment]
> @evantlueck in your comment you are talking about parent and child OUs. For me this happens to every OU I later add, without them having an inheritance relationship. So this does not solve this issue.

Yes, the issue you're speaking of is resolved by this line:
```
for_each       = { for ou in local.final_ous : ou => [ou] }
```
within the `aws_cloudformation_stack_set_instance` resource.

The OU parent/child relationship discussion is a whole separate issue I ran into after using the above solution.
Which incited the need to use this:
```
locals {
  deduped_ous = distinct(var.target_ous)
}

data "aws_organizations_organizational_unit_descendant_accounts" "targeted_accounts" {
  for_each = { for ou in local.deduped_ous : ou => ou }
  parent_id = each.key
}

locals {
  ou_descendants_map = { for ou, child_accounts in data.aws_organizations_organizational_unit_descendant_accounts.targeted_accounts : ou => [ for account in child_accounts.accounts : account.id ] }
  # Identify OUs whose account list is a subset of any other OU's account list
  subset_ous = [for ou_id, accounts in local.ou_descendants_map :
    ou_id if length([
      for other_ou_id, other_accounts in local.ou_descendants_map :
        other_ou_id if (other_ou_id != ou_id && length(setsubtract(accounts, other_accounts)) == 0)
    ]) > 0
  ]
  # list of OUs which are not a subset of any other OU's account list which should each have their own aws_cloudformation_stack_set_instance resource.
  final_ous = setsubtract(local.deduped_ous, local.subset_ous)
}
```

Which helps mitigate it. But the underlying issue is with the provider so only so much can be done.

**Comment by franciscojose-sanchezsanchez** [comment]
I know that there are several workarounds, but all of them involve, in many cases, low-level solutions that are bad and can break certain operations of previously deployed stacksets.

However, I would like to know if there is any information on the progress to fix this bug. I think it's an important issue to resolve, whenever possible.

Thanks

**Comment by tabasku** [comment]
Seems like there was an attempt to change `deployment_targets` to force new resource if changed but it is not currently working : https://github.com/hashicorp/terraform-provider-aws/commit/c6965befe6cd31a7b1584289290a43fc3f2cac3a

In my opinion this makes sense as `aws_cloudformation_stack_set_instance` or at least `deployment_targets` is immutable. Any following updates are done against all existing stack instances.

**Comment by aiell0** [comment]
I am also having this problem and would love a solution here.

**Comment by ollytheninja** [comment]
I'm using the same workaround as @cedricbastin but boy is this one a doozy. I'm glad I'm only managing IAM roles which can easily be re-created but it would be fantastic if there was a better solution!
