### ISSUE TITLE
[Enhancement]: ADD AppSyncJS for aws_appsync_function

### ISSUE THREAD

**Issue by antoineVIVIES** [hashicorp/terraform-provider-aws#27873]
### Description

It's now possible to use AppSyncJS or VTL to write resolver for AppSync.
Right now on terraform-provider-aws only VTL is available as it was the only option available.

### Affected Resource(s) and/or Data Source(s)

aws_appsync_function

### Potential Terraform Configuration

```terraform
For VTL:
resource "aws_appsync_function" "function" {
  api_id                    = "apiId"
  data_source               = "datasource"
  name                      = "name"
  request_mapping_template  = file("PATH_TO_VTL")
  response_mapping_template = file("PATH_TO_VTL")
}

for JS:
resource "aws_appsync_function" "function" {
  api_id        = "apiId"
  data_source   = "datasource"
  name          = "name"
  function_code = file("PATH_TO_JS")
}
```

### References

[Here is the announcement](https://aws.amazon.com/about-aws/whats-new/2022/11/aws-appsync-javascript-graphql-api-resolvers/)
[Here is the blog article](https://aws.amazon.com/blogs/aws/aws-appsync-graphql-apis-supports-javascript-resolvers/)

**Comment by ewbankkit** [comment]
Requires [AWS SDK for Go v1.44.140](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.140): https://github.com/hashicorp/terraform-provider-aws/pull/27868.

**Comment by lushc** [comment]
The `aws_appsync_resolver` resource may be affected as well.

**Comment by DrFaust92** [comment]
something is not 100% with the api when adding all of the args

```
        Error: Error creating AppSync Function: InvalidParameter: 1 validation error(s) found.
        - minimum field size of 1, CreateFunctionInput.RequestMappingTemplate.
```

even though its now optional according to docs

**Comment by juanoi** [comment]
Really looking forward to this being released. PR is almost 2 weeks old now - any estimates on a tentative release date?
