### ISSUE TITLE
[Enhancement]: nodejs18.x support for aws_lambda_function

### ISSUE THREAD

**Issue by jbarop** [hashicorp/terraform-provider-aws#27878]
### Description

[Node18 runtime](https://github.com/aws/aws-cdk/pull/22964) for AWS Lambda has been released with [CDK 2.51.0](https://github.com/aws/aws-cdk/releases/tag/v2.51.0) and [aws-sdk-go v1.44.140](https://github.com/aws/aws-sdk-go/pull/4626)

Creating an `aws_lambda_function` currently returns in plan-stage:
```
Error: expected runtime to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x nodejs16.x java8 java8.al2 java11 python2.7 python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 dotnet6 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2], got nodejs18.x
```

### Affected Resource(s) and/or Data Source(s)

* aws_lambda_function

### References

https://github.com/aws/aws-cdk/releases/tag/v2.51.0
https://github.com/aws/aws-cdk/pull/22964
https://github.com/aws/aws-sdk-go/pull/4626
[Announcement](https://aws.amazon.com/about-aws/whats-new/2022/11/aws-lambda-support-node-js-18/)

**Comment by ewbankkit** [comment]
Requires [AWS SDK for Go v1.44.140](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.140): https://github.com/hashicorp/terraform-provider-aws/pull/27868.

**Comment by rarous** [comment]
Already on v1.44.141 https://github.com/hashicorp/terraform-provider-aws/pull/27887
