### ISSUE TITLE
[Enhancement]: gp3 'storage_type' support for 'aws_db_instance'

### ISSUE THREAD

**Issue by ShawnUCD** [hashicorp/terraform-provider-aws#27884]
### Description

AWS has made GP3 support for RDS generally available.  Please update the AWS provider to include this option, along with `iops` (already supported for `io1` storage type) and `throughput`, as those are now definable parameters.

### Affected Resource(s) and/or Data Source(s)

aws_db_instance

### Potential Terraform Configuration

```terraform
resource "aws_db_instance" "default" {
  allocated_storage    = 10
  db_name              = "mydb"
  engine               = "mysql"
  engine_version       = "5.7"
  instance_class       = "db.t3.micro"
  storage_type         = "gp3"
  iops                 = 3000
  throughput           = 125
  username             = "foo"
  password             = "foobarbaz"
  parameter_group_name = "default.mysql5.7"
  skip_final_snapshot  = true
}
```

### References

https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-rds-general-purpose-gp3-storage-volumes/

**Comment by ewbankkit** [comment]
@ShawnUCD Thanks for raising this issue.
It has already been noticed in #27702. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
