### ISSUE TITLE
[Enhancement]: Resource: aws_imagebuilder_image

### ISSUE THREAD

**Issue by harelkhafi777** [hashicorp/terraform-provider-aws#27906]
### Description

hi !
from a check i made it seems that i cant put an AMI ID on the The parent_image argument in the imagebuilder_recipe component (link-https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/imagebuilder_image_recipe),
 
 although the image builder service provide this option when you do it manualy, for example i want to take an AMI ID from the aws market place and use it like my base image in my image builder recepie, there is an option to do that in the image builder cosole by insert the AMI ID but it seems that in terraform this option dosent exit.
 waiting for your respond, 
thank you (:
 

### Affected Resource(s) and/or Data Source(s)

Resource: aws_imagebuilder_image

**Comment by kamilturek** [comment]
It is possible to use AMI ID in the `parent_image` argument. The configuration below works for me.

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}

provider "aws" {
  region  = "eu-west-1"
}

resource "aws_imagebuilder_image_recipe" "example" {
  name         = "TestRecipe"
  parent_image = "ami-01cae1550c0adea9c"
  version      = "1.0.0"

  component {
    component_arn = "arn:aws:imagebuilder:eu-west-1:aws:component/update-linux/x.x.x"
  }
}
```

The argument description in the documentation is wrong though, it should be corrected.
https://github.com/hashicorp/terraform-provider-aws/blob/5cae4979cecb8ad61c10bb930cd26d5c241bb47f/website/docs/r/imagebuilder_image_recipe.html.markdown?plain=1#L53

**Comment by jwlogemann** [comment]
> The argument description in the documentation is wrong though, it should be corrected.
> 
> https://github.com/hashicorp/terraform-provider-aws/blob/5cae4979cecb8ad61c10bb930cd26d5c241bb47f/website/docs/r/imagebuilder_image_recipe.html.markdown?plain=1#L53

I've created a PR for this: https://github.com/hashicorp/terraform-provider-aws/pull/28000

**Comment by harelkhafi777** [comment]
thanks !!

**Comment by breathingdust** [comment]
I've merged the documentation update, it looks like you should be unblocked now @harelkhafi777 so will close this issue. Thanks @kamilturek and @jwlogemann for the help!
