### ISSUE TITLE
[Docs]: `website_endpoint` is not listed as deprecated

### ISSUE THREAD

**Issue by klovelyPhraseHealth** [hashicorp/terraform-provider-aws#27908]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#website_endpoint

### Description

Attempting to use this attribute yields

```
│ Warning: Deprecated attribute
│
│   on .terraform/modules/cloudfront_web_app/cloudfront.tf line 16, in resource "aws_cloudfront_distribution" "s3_site_cdn":
│   16:     domain_name = aws_s3_bucket.main_bucket.website_endpoint
│
│ The attribute "website_endpoint" is deprecated. Refer to the provider documentation for details.
```

other documentation gives better info

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade#website-website_domain-and-website_endpoint-arguments

### Would you like to implement a fix?

nahh

**Comment by tmccombs** [comment]
The error also says to refer to the provider documentation, but isn't immediately clear what you should use instead, there are no references to deprecation anywhere near any reference of `website_endpoint`. 

I assume the intention is that you should isntead use an `aws_s3_bucket_website_configuration` and use the `website_endpoint` on that.
