### ISSUE TITLE
[Enhancement]: aws_amplify_app add support for platform = "WEB_COMPUTE"

### ISSUE THREAD

**Issue by nicholasrobertson** [hashicorp/terraform-provider-aws#27907]
### Description

# Context
I am building a React front end with NextJS for server side rendering.
I use AWS Amplify for hosting and provision the resources using terraform cloud.

As of November 2022, AWS supports NextJS version 12 and 13 via and new Amplify Platform Type called "WEB_COMPUTE"
The terraform provider does not support this value and will error when a plan is run.

### ERROR
```
{"@level":"info","@message":"Terraform 1.3.5","@module":"terraform.ui","@timestamp":"2022-11-20T07:40:43.158542Z","terraform":"1.3.5","type":"version","ui":"1.0"}
{"@level":"error","@message":"Error: expected platform to be one of [WEB WEB_DYNAMIC], got WEB_COMPUTE","@module":"terraform.ui","@timestamp":"2022-11-20T07:40:46.855878Z","diagnostic":{"severity":"error","summary":"expected platform to be one of [WEB WEB_DYNAMIC], got WEB_COMPUTE","detail":"","address":"aws_amplify_app.frontend","range":{"filename":"amplify.tf","start":{"line":64,"column":35,"byte":1466},"end":{"line":64,"column":48,"byte":1479}},"snippet":{"context":"resource \"aws_amplify_app\" \"frontend\"","code":"  platform                      = \"WEB_COMPUTE\"","start_line":64,"highlight_start_offset":34,"highlight_end_offset":47,"values":[]}},"type":"diagnostic"}
```

# Expectation
GIVEN I am configuring the aws_amplify_app resource
AND I have set the value of `platform` to the string `WEB_COMPUTE`
WHEN I start a new run
THEN the plan will succeed

## Note
I hardly trust myself to may changes to my own code, also I have barely touched GO lang, so I dont think that I am best to make the required changes.

### Affected Resource(s) and/or Data Source(s)

aws_amplify_app

### Potential Terraform Configuration

```terraform
resource "aws_amplify_app" "frontend" {
  name          = "${var.project_name}-${var.organization}"
  repository    = var.github_repository
  access_token  = var.github_token

  build_spec = <<-EOT
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm ci
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: unit

  EOT

  environment_variables = {
      AMPLIFY_MONOREPO_APP_ROOT   = var.app_root,
      AMPLIFY_DIFF_DEPLOY         = "false",
      _LIVE_UPDATES               = <<-EOT
        [{"pkg":"next-version","type":"internal","version":"latest"}]
        EOT
    }
  
  enable_auto_branch_creation   = false
  enable_branch_auto_build      = false
  enable_branch_auto_deletion   = false
  platform                      = "WEB_COMPUTE"
  iam_service_role_arn          = aws_iam_role.amplify_role.arn

  #Amplify will automatically add custom_rules after initial deployment. This ensures your subsequent terraform runs don't break your amplify deployment.
  lifecycle {
    ignore_changes = [
      custom_rule,
    ]
  }

  custom_rule {
    source = "/<*>"
    status = "404-200"
    target = "/index.html"  
  }

  tags = {
    Environment = var.organization
    Project     = var.project_name
  }
}
```

### References

https://docs.aws.amazon.com/cli/latest/reference/amplify/create-app.html?highlight=amplify

https://docs.aws.amazon.com/amplify/latest/userguide/update-app-nextjs-version.html

### Would you like to implement a fix?

No

**Comment by TimRuebP** [comment]
Since `WEB_COMPUTE` is already present in the [aws go sdk](https://github.com/aws/aws-sdk-go/blob/main/service/amplify/api.go#L10384), I assume it will automatically be available in the next release of the aws terraform provider. At the moment, the terraform provider [directly references to all available values from the go sdk](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/amplify/app.go#L275).

**Comment by ewbankkit** [comment]
Requires [AWS SDK for Go v1.44.140](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.140): https://github.com/hashicorp/terraform-provider-aws/pull/27868.
