### ISSUE TITLE
[New Resource]: copy-db-cluster-snapshot similar to db_snapshot_copy

### ISSUE THREAD

**Issue by mirzazeyrek** [hashicorp/terraform-provider-aws#27926]
### Description

I am looking for a functionality like:

```
aws rds copy-db-cluster-snapshot 
--region eu-central-1 
--source-db-cluster-snapshot-identifier "arn:aws:rds:eu-west-1:..."
--target-db-cluster-snapshot-identifier "arn:aws:rds:eu-central:..."
```

There is a method but it is not compatible with cluster db snapshots:

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_snapshot_copy

### Requested Resource(s) and/or Data Source(s)

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_snapshot_copy

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cluster_db_snapshot_copy (not exists)

### Potential Terraform Configuration

```terraform
resource "aws_db_instance" "frankfurt" {
  allocated_storage = 10
  engine            = "aurora-mysql"
  engine_version    = "8.0.mysql_aurora.3.02.2"
  instance_class    = "db.r6g.2xlarge"
  name              = "baz"
  password          = "barbarbarbar"
  username          = "foo"
}

resource "aws_db_snapshot" "ireland" {
  db_instance_identifier = aws_db_instance.example.id
  db_snapshot_identifier = "testsnapshot1234"
}

resource "aws_cluster_db_snapshot_copy" "example" {
  source_db_snapshot_identifier = aws_db_snapshot.example.db_snapshot_arn
  target_db_snapshot_identifier = "testsnapshot1234-copy"
}
```

**Comment by mirzazeyrek** [comment]
Is there any progress on this ? :upside_down_face:

**Comment by sabinayakc** [comment]
Any update on this one?

**Comment by ryan-keswick** [comment]
Any update on this?

**Comment by RFHold** [comment]
@jar-b, I didn't see that this got assigned to you. I believe https://github.com/hashicorp/terraform-provider-aws/pull/40398 contains everything needed. I intend on testing and finishing that PR tomorrow. Any assistance appreciated if you'd like me to continue

**Comment by jar-b** [comment]
Hey @RFHold - thanks for your work on this! 

As of October 2023, all net-new resources are required to be implemented with Terraform Plugin Framework ([see this pinned issue](https://hashicorp.github.io/terraform-provider-aws/terraform-plugin-development-packages/#which-plugin-version-should-i-use) for additional context). I'll plan to pick up on your PR as the tests and documentation can be used as-is, but will refactor the resource implementation to use Terraform Plugin Framework instead. Thanks for the heads up!
