### ISSUE TITLE
Cannot Alter Existing Default Route in aws_default_route_table

### ISSUE THREAD

**Issue by coofercat** [hashicorp/terraform-provider-aws#27929]
### Description

Summary: This may be a request to clarify the documentation, or it may be a request for enhancement to add a capability to the provider. As such, some triage before categorising as either would be appreciated.

I have a VPC with a second CIDR range associated with it (via aws_vpc_ipv4_cidr_block_association). In my case, this second CIDR range is 10.1.0.0/16. I have additionally created some subnets in that CIDR range. All of this works just fine.

By default AWS creates a default route table which looks like this:

```
Destination    Target    Status   Propagated
10.0.72.0/21   local     Active   No
10.1.0.0/16    local     Active   No
```

I'd like to change the second of those routes to use an ENI as the 'Target' instead of 'local' (which I can do in the Web console). To do this, I 'adopt' the default route table, which the documentation states will remove all pre-existing rules, but also states, "Note that the default route, mapping the VPC's CIDR block to "local", is created implicitly and cannot be specified."

With this in mind, setting `route = []` to empty the table does not touch the two 'local' routes. eg:
```
resource "aws_default_route_table" "route_table" {
  default_route_table_id = module.vpc.vpc_main_route_table_id

  route = []
}
```

However, I'd like to modify the rule that's already there, so attempt to create a "new" route for the secondary CIDR range:
```
resource "aws_network_interface" "blackhole" {
  subnet_id       = "subnet-1234"
  security_groups = [aws_security_group.blackhole.id]
}
resource "aws_default_route_table" "route_table" {
  default_route_table_id = module.vpc.vpc_main_route_table_id
  route {
    cidr_block           = "10.1.0.0/16"
    network_interface_id = aws_network_interface.blackhole.id
  }
}
```
However, this (somewhat expectedly) fails:
```
module.layer0.aws_default_route_table.route_table: Modifying... [id=rtb-03244beb9738eee46]
╷
│ Error: error creating Route in Route Table (rtb-03244beb9738eee46) with destination (10.1.0.0/16): RouteAlreadyExists: The route identified by 10.1.0.0/16 already exists.
│ 	status code: 400, request id: 05551873-66d8-402a-be48-371233335199
│
│   with module.layer0.aws_default_route_table.route_table,
│   on ../../../modules/layers/layer0/isolated_subnets.tf line 45, in resource "aws_default_route_table" "route_table":
│   45: resource "aws_default_route_table" "route_table" {
│
```
I haven't found a way to 'import' an existing route, or for Terraform to really acknowledge their existence in any way, other than to error out as above.

This all looks like it's working as documented, although maybe some additional clarification in there might be useful to say "Note that the default route, mapping the VPC's CIDR block to "local", is created implicitly and cannot be specified, nor can these routes be modified with Terraform".

However, the modification *is* possible with awscli (or web console):
```
aws ec2 replace-route --route-table-id rtb-1234 --destination-cidr-block 10.1.0.0/16 --network-interface-id eni-1234
```
With that in mind, is an enhancement possible? I'm not sure how best to specify one if it is an option (happy to give it a try if you like though).

By way of justification for such a change... Being able to change these routes is very useful when trying to put firewalls or other intermediaries between VPC traffic. In my case, I'm actually blackholing the traffic to create "isolated" subnets that can't route to anything, but that's possible more niche than other use-cases.

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_route_table

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
Similar:

* https://github.com/hashicorp/terraform-provider-aws/issues/20663
* https://github.com/hashicorp/terraform-provider-aws/issues/21350
