### ISSUE TITLE
resource/aws_rds_cluster/aws_rds_cluster_instance: Remove default value from `engine` parameter

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#27960]
### Description

The resource `aws_rds_cluster` defines a default value of `aurora` for the `engine` parameter. The AWS API treats this parameter as required and does not define a default. Additionally, `aurora` creates a MySQL-5.6-compatible cluster, while `aurora-mysql` is used for MySQL-5.7- and MySQL-8.0-compatible clusters.

- [ ] `aws_rds_cluster`: Remove the default value and make `engine` a required parameter.
- [ ] `aws_rds_cluster_instance`: Remove the default value and make `engine` a required parameter.

### Affected Resource(s) and/or Data Source(s)

aws_rds_cluster

**Comment by jar-b** [comment]
With Aurora MySQL Version 1 now at EOL, it appears `aurora` (the current default value) has been removed as a valid value for the `Engine` argument in APIs like `CreateDBCluster`:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/14969179/229138963-a1c69be7-aa1b-4b37-82b8-28fd5ffc9b3d.png">

As part of these breaking changes, we should remove this constant to ensure plan time validation matches the AWS valid values going forward.

https://github.com/hashicorp/terraform-provider-aws/blob/5f5949ff97841390c2b3d667a1d1fb24fb29b282/internal/service/rds/consts.go#L110

Ref:
- https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.MySQL56.EOL.html
- https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBCluster.html
- Relates #30355

**Comment by jar-b** [comment]
Closed by #31112, merged to `main` via #31392
