### ISSUE TITLE
[Enhancement]: Glue Classifier support for CustomDatatypes in CSV Classifiers

### ISSUE THREAD

**Issue by matschundbrei** [hashicorp/terraform-provider-aws#27971]
### Description

AWS Glue Classifier does support custom datatypes (i.e. a list of datatypes to be forced on a specific column).

In order to work with CSV classifiers in particular and any classifiers downstream in glue workflows, we would have to be able to easily add them to crawlers. The currently supported format of `aws_glue_crawler` is to pass a list of names to the parameter `classifiers`.

### Affected Resource(s) and/or Data Source(s)

* aws_glue_classifier

### Potential Terraform Configuration

```terraform
resource "aws_glue_classifier" "example" {
  name = "example"

  csv_classifier {
    allow_single_column    = false
    contains_header        = "PRESENT"
    delimiter              = ","
    disable_value_trimming = false
    header                 = ["example1", "example2"]
    quote_symbol           = "'"
    custom_datatypes_used  = true
    custom_datatypes       = ["string", "long" ]
  }
}
```

### References

* Classifiers are mentioned in #18682
* [CSV Classifier reference in current aws go sdk](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/glue@v1.35.0/types#CreateCsvClassifierRequest)

### Would you like to implement a fix?

No

**Comment by DrFaust92** [comment]
[matschundbrei](https://github.com/matschundbrei) can i ask you to open a dedicate issue for the new datasource? its usually preferred to have a single change request per ticket/PR

**Comment by matschundbrei** [comment]
relevant parts removed and filed again in #28069
