### ISSUE TITLE
[Enhancement]: Add support for SNS FilterPolicyScope attribute

### ISSUE THREAD

**Issue by vghero** [hashicorp/terraform-provider-aws#27997]
### Description

Hey guys,
[recently AWS announced support](https://aws.amazon.com/blogs/compute/introducing-payload-based-message-filtering-for-amazon-sns/) for filter policies based on the message payload - not just attributes. I was wondering if it would be much effort to add support for the [FilterPolicyScope](https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html#sns-message-filtering-scope) attribute on a subscription to allow the switch between attributes/body filtering. As it is of course not yet supported [here](https://registry.terraform.io/providers/hashicorp/aws/2.55.0/docs/resources/sns_topic_subscription#argument-reference). AWS also provides some examples of [CLI invocations](https://docs.aws.amazon.com/sns/latest/dg/message-filtering-apply.html) in their docs.
I think this feature could be quite of interest for AWS users soon.

Thanks!

### Affected Resource(s) and/or Data Source(s)

aws_sns_topic_subscription

### Potential Terraform Configuration

```terraform
resource "aws_sns_topic_subscription" "sns-topic" {
  provider  = "aws.sns2sqs"
  topic_arn = aws_sns_topic.sns-topic.arn
  protocol  = "sqs"
  endpoint  = aws_sqs_queue.sqs-queue.arn
  filter_policy = "<some-json-filter>"
  **filter_policy_scope = "MessageAttributes|MessageBody"**
}
```

### References

Announcement: https://aws.amazon.com/blogs/compute/introducing-payload-based-message-filtering-for-amazon-sns/
FilterPolicyScope: https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html#sns-message-filtering-scope
CLI examples: https://docs.aws.amazon.com/sns/latest/dg/message-filtering-apply.html

### Would you like to implement a fix?

No

**Comment by cwadley** [comment]
Hi folks, it looks like this change has broken SNS subscriptions in China AWS, which doesn't have filter policy scopes implemented yet:

`Error: setting SNS Topic Subscription (arn:aws-cn:sns:cn-northwest-1:999999999999:my-sns-topic:39705df4-d64a-4939-bce9-a041f0b0b8d5) attribute (FilterPolicyScope): InvalidParameter: Invalid parameter: AttributeName`

It would be great if we could set the `filter_policy_scope` field to null and not have it default to `MessageAttributes`

**Comment by roberth-k** [comment]
Hi @cwadley --

Could you check if the latest v4.46.0 fixes this for you?

**Comment by cwadley** [comment]
@roberth-k Yep, that fixed it. Thank you!
