### ISSUE TITLE
[Bug]: Cannot enable or disable SageMaker JumpStart templates

### ISSUE THREAD

**Issue by aahmedj** [hashicorp/terraform-provider-aws#27990]
### Terraform Core Version

1.2.3

### AWS Provider Version

v4.40.0, v4.39.0, v4.38.0

### Affected Resource(s)

aws_sagemaker_domain

### Expected Behavior

Successfully able to update domain settings by enabling `SageMaker Projects and JumpStart`. Currently the terraform resource does not support doing this. 

### Actual Behavior

After successful sagemaker_domain provisioning, if you want to enable SageMaker jumpStart poject templates and submit validation error is thrown. 

ValidationException
2 validation errors detected

    Value '' at 'defaultSpaceSettings.executionRole' failed to satisfy constraint: Member must have length greater than or equal to 20
    Value '' at 'defaultSpaceSettings.executionRole' failed to satisfy constraint: Member must satisfy regular expression pattern: ^arn:aws[a-z\-]*:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$

### Relevant Error/Panic Output Snippet

```shell
After successful sagemaker_domain provisioning, if you want to enable SageMaker jumpStart poject templates and submit validation error is thrown. 


ValidationException
2 validation errors detected

    Value '' at 'defaultSpaceSettings.executionRole' failed to satisfy constraint: Member must have length greater than or equal to 20
    Value '' at 'defaultSpaceSettings.executionRole' failed to satisfy constraint: Member must satisfy regular expression pattern: ^arn:aws[a-z\-]*:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$


POST API call from the web-console suggests DefaultSpaceSettings for `ExecutionRole` is empty


`{"DomainId":"d-xxxxx","DefaultUserSettings":{"ExecutionRole":"arn:aws:iam::xxxxxx:role/sagemaker-default-execution-role","SharingSettings":{"NotebookOutputOption":"Disabled","S3OutputPath":"s3://sagemaker-studio-xxxxxx"},"JupyterServerAppSettings":{"DefaultResourceSpec":{"SageMakerImageArn":"arn:aws:sagemaker:eu-central-1:xxxxxx:image/jupyter-server-3","InstanceType":"system"}}},"DefaultSpaceSettings":{"ExecutionRole":""}}`
```

### Terraform Configuration Files

```
resource "aws_sagemaker_domain" "sagemaker_domain" {
  domain_name = "sagemamker-domain"
  auth_mode   = "IAM"
  vpc_id      = module.vpc.vpc_id
  subnet_ids  = module.vpc.private_subnets

  default_user_settings {
    execution_role = aws_iam_role.sagemaker_execution_role.arn
  }

}

resource "aws_iam_role" "sagemaker_execution_role" {
  name               = "sagemaker-default-exec-role"
  path               = "/"
  assume_role_policy = data.aws_iam_policy_document.sagemaker_exec_policy.json
 managed_policy_arns = ["arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"]
}

data "aws_iam_policy_document" "sagemaker_exec_policy" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["sagemaker.amazonaws.com"]
    }
  }
}
```

### Steps to Reproduce

1. Create `aws_sagemaker_domain` 
2. Try to update domain settings by enabling/ disabling `SageMaker Projects and JumpStart` and it fails due to validation exception.

### References

Related to https://github.com/hashicorp/terraform-provider-aws/issues/21490

**Comment by DrFaust92** [comment]
at the time of writing according to docs https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateDomain.html DefaultSpaceSettings is not a valid arg (same in the golang sdk)

**Comment by pawelpesz** [comment]
I have a similar problem with a domain with SSO (aka IAM Identity Center).
When it's created afresh the `Enable Amazon SageMaker project templates and Amazon SageMaker JumpStart for Studio users` option is disabled even though I'm creating all the required `AmazonSageMakerServiceCatalogProducts*` service roles.
It seems the only way to enable it is via the UI 😞

**Comment by DrFaust92** [comment]
[pawelpesz](https://github.com/pawelpesz) what you are describing is a different issue and from the comment in the PR its not a TF issue as it doesnt seem to be support by AWS according your CLI error
