### ISSUE TITLE
[Bug]: ValidationError when specifying KMS CMK replica key arn for DynamoDB table replica

### ISSUE THREAD

**Issue by adamham-gt** [hashicorp/terraform-provider-aws#28010]
### Terraform Core Version

1.3.3

### AWS Provider Version

4.37.0

### Affected Resource(s)

aws_dynamodb_table_replica

### Expected Behavior

I can specify a `aws_kms_replica_key` arn as the `kms_key_arn` field value of the `aws_dynamodb_table_replica` resource.

### Actual Behavior

The table replica is created, the KMS key replica is correctly linked but the following error is returned on `apply`:

```
Error: updating Amazon DynamoDB Table Replica (<table>:<aws_region>): ValidationException: One or more parameter values were invalid: KMSMasterKeyId must be specified for each replica.
│ 	status code: 400, request id: <some id>
```

... and the resource is tainted, and must be manually untainted otherwise it gets replaced on a subsequent apply.

### Terraform Configuration Files

n/a

### Steps to Reproduce

- Create a multi region KMS CMK in region 1
- Create a DDB table in region 1 and encrypt with the above key arn
- Create a KMS CMK key replica in region 2
- Create a DDB table replica in region 2 with the above replica key arn.

### Would you like to implement a fix?

No

**Comment by julieerle** [comment]
@breathingdust, Is this related to https://github.com/hashicorp/terraform-provider-aws/issues/21726?

**Comment by nickkomen** [comment]
I am experiencing the same issue with AWS Provider version 4.49.0, so it appears to not be resolved.

**Comment by koolbaar** [comment]
I am experiencing the same issue with AWS Provider version 4.51.0. Waiting for the solution.
Use Case: 
Execution 1: 
Step 1: Create a KMS CMK in us-east-1
Step 2: Create DynamoDB Table in us-east-1 applying the KMS CMK created in Step 1
Execution 2:
Step 3: Create a KMS CMK in us-east-2.
Step 4: Create Replica as an independent request for region us-east-2 applying the CMK created in the above step.
              Note: This is where I receive the above mentioned error
Execution 3:
Step 5: Later in time, we may want to add replica to another region as we start supporting more regions.
