### ISSUE TITLE
[Bug]: data.aws_s3_object using bucket domain as access point when using custom  s3 endpoint url

### ISSUE THREAD

**Issue by germanamz** [hashicorp/terraform-provider-aws#28015]
### Terraform Core Version

1.3.4

### AWS Provider Version

4.38.0

### Affected Resource(s)

data aws_s3_object

### Expected Behavior

When using a custom S3 endpoint-url it should use `S3 path access point` instead of domain-based when getting the body of the object.

Expected endpoint form to download: `<protocol>://<custom-host>/<bucket-name>/<path-to-the-obect>`
Eg.
`http://localhost:5000/the-bucket/theVersion/lambdas/some-lambda.zip.checksum`

### Actual Behavior

The form of the URL currently used: `<protocol>://<bucket-name>.<custom-host>/<path-to-the-object>`

Eg

`http://the-bucket.localhost:5000/firstPart/lambdas/some-lambda.zip.checksum`

### Terraform Configuration Files

https://github.com/germanamz/resource_aws_s3_object/tree/main

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.38.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
  access_key = "test_AWS_ACCESS_KEY_ID"
  secret_key = "test_AWS_SECCRET_ACCESS_KEY_ID"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    s3             = "http://localhost:5000"
  }
}

data "aws_s3_object" "test" {
  bucket = "the-bucket"
  key = "test.json"
}

output "json" {
  value = data.aws_s3_object.test.body
}

```

### Steps to Reproduce

Mount an S3 in any AWS-mock project and run the terraform config.

Here's an example repo with all required setup  https://github.com/germanamz/resource_aws_s3_object/tree/main

**Comment by breathingdust** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/ef1fc32d4f006c0332c54f4cf0797fd93c2e4b3e/internal/conns/config.go#L330-L339

**Comment by germanamz** [comment]
This issue can be solved by adding `s3_use_path_style` to the provider configuration.
