### ISSUE TITLE
[Docs]: aws_controltower_control no import documentation

### ISSUE THREAD

**Issue by CalvinRodo** [hashicorp/terraform-provider-aws#28020]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/controltower_control

### Description

There is no import command for this control

### Would you like to implement a fix?

No

**Comment by neilfarmer** [comment]
Added documentation here https://github.com/hashicorp/terraform-provider-aws/pull/28132.
Waiting on approvals
