### ISSUE TITLE
[Docs]: aws_apprunner_vpc_connector's attribute is wrong

### ISSUE THREAD

**Issue by kennygt51** [hashicorp/terraform-provider-aws#28023]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apprunner_vpc_connector

### Description

`vpc_connector_arn` is listed as an attribute of `ARN of VPC Connector`, but I think it's `arn` correctly.

### Would you like to implement a fix?

Yes

**Comment by bennylu2** [comment]
Appears it has been fixed https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apprunner_vpc_connector#arn
