### ISSUE TITLE
[Enhancement]: Add support for data protection in cloudwatch logs

### ISSUE THREAD

**Issue by marcincuber** [hashicorp/terraform-provider-aws#28036]
### Description

> We are excited to announce data protection in Amazon CloudWatch Logs, a new set of capabilities that leverage pattern matching and machine learning capabilities to detect and protect sensitive log data-in-transit.

### Affected Resource(s) and/or Data Source(s)

`aws_cloudwatch_log_data_protection_policy`

### Potential Terraform Configuration

```hcl
resource "aws_cloudwatch_log_data_protection_policy" "example" {
  log_group_arn = aws_cloudwatch_log_group.example.arn

  policy_document = <<EOS
{
}
EOS
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2022/11/data-protection-amazon-cloudwatch-logs-detect-protect-sensitive-data-in-transit/).
[Blog post](https://aws.amazon.com/blogs/aws/protect-sensitive-data-with-amazon-cloudwatch-logs/).

Requires [AWS SDK for Go v1.44.146](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.146): #28033.

**Comment by roberth-k** [comment]
I'll pick this up.

Based on the API, this would involve:

- Adding a new resource, `aws_cloudwatch_log_group_data_protection_policy`.
- Adding a new data source, `aws_cloudwatch_log_group_data_protection_policy_document` (mimicking `aws_iam_policy_document`).
- Adding the computed attribute `data_protection_status` to `aws_cloudwatch_log_group`.

**Comment by marcincuber** [comment]
closing as already released
