### ISSUE TITLE
Amazon RDS Blue/Green Deployments

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#28042]
> [Amazon Relational Database Service (Amazon RDS)](https://aws.amazon.com/rds/) now supports Amazon RDS Blue/Green Deployments to help you with safer, simpler, and faster updates to your Amazon Aurora and Amazon RDS databases.

[Announcement](https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-rds-blue-green-deployments-safer-simpler-faster-updates/).
[Blog post](https://aws.amazon.com/blogs/aws/new-fully-managed-blue-green-deployments-in-amazon-aurora-and-amazon-rds/).

Requires [AWS SDK for Go v1.44.146](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.146): https://github.com/hashicorp/terraform-provider-aws/pull/28033.

**Comment by kmonroe0723** [comment]
Hello,

Has anyone seen this error hitting the create staging environment button:

CreateBlueGreenDeployment is not supported?

**Comment by aditya-ambati** [comment]
@ewbankkit  Does this feature support Aurora DB as well or is it only for RDS ?

**Comment by ferschubert-hm** [comment]
@aditya-ambati seems not if you use `aws_rds_cluster_instance` as currently only `aws_db_instance` resource has the `blue_green_update` option.

**Comment by PackiarajSakkananGW** [comment]
Is there any way to get `blue_green_update`  to work with `aws_rds_cluster_instance`. As per the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_instance) `aws_rds_cluster_instance` is the recommended way to manage aurora instance. If that is the case, then `blue_green_update`  does not work with Auroa.
