### ISSUE TITLE
[Enhancement]: Support EFS Elastic Throughput

### ISSUE THREAD

**Issue by markbaird** [hashicorp/terraform-provider-aws#28050]
### Description

Add support for the new `elastic` throughput mode of Elastic File Systems (EFS). 

The `throughput_mode` argument would support a third option of `elastic` in addition to the current `bursting` and `provisioned` values.

### Affected Resource(s) and/or Data Source(s)

* aws_efs_file_system

### Potential Terraform Configuration

```terraform
resource "aws_efs_file_system" "foo" {
  creation_token = "my-product"
  throughput_mode = "elastic"
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-elastic-file-system-elastic-throughput/)
[Blog post](https://aws.amazon.com/blogs/aws/new-announcing-amazon-efs-elastic-throughput/)

Requires [AWS SDK for Go v1.44.146](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.146): https://github.com/hashicorp/terraform-provider-aws/pull/28033.

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
We will pick up the new `throughput_mode` value when we build with the updated AWS SDK for Go.
I'll make sure that the relevant documentation is updated.
