### ISSUE TITLE
[New Resource]: Support for ElastiCache Reserved Nodes

### ISSUE THREAD

**Issue by mousavian** [hashicorp/terraform-provider-aws#28060]
### Description

Like EC2 and [RDS](https://github.com/hashicorp/terraform-provider-aws/pull/26025), Amazon's ElastiCache also allows the purchase of [reserved nodes](https://aws.amazon.com/elasticache/reserved-cache-nodes/) which are used if compatible ElastiCache nodes are spun up. It'd be great if the AWS provider supported the creation of these!

### Requested Resource(s) and/or Data Source(s)

Data Sources:
* aws_elasticache_reserved_cache_node_offering

Resources:
* aws_elasticache_reserved_cache_node

### Potential Terraform Configuration

```terraform
data "aws_elasticache_reserved_cache_node_offering" "redis_micro" {
  db_instance_class   = "cache.t1.micro"
  duration            = 31536000
  offering_type       = "No Upfront"
  product_description = "redis"
}

resource "aws_elasticache_reserved_cache_node" "example" {
  offering_id    = data.aws_rds_reserved_instance_offering.redis_micro.offering_id
  reservation_id = "optionalCustomReservationID"
  node_count     = 3
}
```

### References

- [aws . elasticache . describe-reserved-cache-nodes-offerings](https://docs.aws.amazon.com/cli/latest/reference/elasticache/describe-reserved-cache-nodes-offerings.html) 
- [aws . elasticache . purchase-reserved-cache-nodes-offering](https://docs.aws.amazon.com/cli/latest/reference/elasticache/purchase-reserved-cache-nodes-offering.html)

### Would you like to implement a fix?

Yes

**Comment by kseniyashaydurova** [comment]
Hi! Is it planned any progress on this?

**Comment by swarner1033** [comment]
Could this be actioned considering that a fix has been written? https://github.com/hashicorp/terraform-provider-aws/pull/29832
This would be very useful as its easy to make mistakes in the console when purchasing.
