### ISSUE TITLE
[Bug]: CognitoUserPoolClient CallbackUrls is marked as computed

### ISSUE THREAD

**Issue by andrewbaxter** [hashicorp/terraform-provider-aws#28073]
### Terraform Core Version

any

### AWS Provider Version

master

### Affected Resource(s)

CognitoUserPoolClient

### Expected Behavior

CallbackUrls (and LogoutUrls actually) should not be computed.  These are both user specified during creation and update, and are not provided by AWS.

### Actual Behavior

Both are marked as computed.

### Terraform Configuration Files

None

### Steps to Reproduce

None

### References

https://github.com/hashicorp/terraform-provider-aws/pull/20065 - set as computed here, but doesn't seem relevant to the PR

**Comment by andrewbaxter** [comment]
I couldn't find any reference for why this was changed. I'm happy to undo the change if it would get this out faster.

API docs https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPoolClient.html

I triple checked the documentation on `Computed` to make sure I wasn't missing anything, but let me know if I misunderstood this field.

**Comment by DrFaust92** [comment]
they are now also computed, not just computed. you can still set those values. as they are also optional.

**Comment by andrewbaxter** [comment]
Okay I searched around and I do see specific mentions of optional+computed in various other places, so I think you're right.  But I can't find any documentation regarding what it actually means.

[This](https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-behaviors) only implicitly allows it, and offers no description of what it might mean.

It's confirmed to be allowed here: https://github.com/hashicorp/terraform-plugin-framework/issues/31

**Comment by andrewbaxter** [comment]
So I guess
* Required -> Provided by user
* Optional -> Provided by user
* Computed -> provided by upstream
* Computed + optional -> Provided by user, but filled in with non-default/empty value by upstream if not provided by user

It would be nice to see an official enumeration but I think this is resolved.  Thanks! I had no idea optional+computed was a special case.
