### ISSUE TITLE
[Enhancement]: Please add support for Lambda SnapStart

### ISSUE THREAD

**Issue by jwilmoth-nc** [hashicorp/terraform-provider-aws#28079]
### Description

AWS recently announced support for SnapStart to reduce startup times (see https://aws.amazon.com/blogs/aws/new-accelerate-your-lambda-functions-with-lambda-snapstart/).  There are a number of use-cases that would benefit from this additional configuration flexibility.

p.s. I'm opening this request as it pre-requisite for support in https://github.com/terraform-aws-modules/terraform-aws-lambda.

### References

- https://aws.amazon.com/blogs/aws/new-accelerate-your-lambda-functions-with-lambda-snapstart/
- https://aws.amazon.com/about-aws/whats-new/2022/11/aws-lambda-snapstart-java-functions/
- https://docs.aws.amazon.com/lambda/latest/dg/snapstart.html

**Comment by ewbankkit** [comment]
@jwilmoth-nc Thanks for raising this issue.
It has already been noticed in #28071. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
