### ISSUE TITLE
[Bug]: Can not store stat in eu-central-2

### ISSUE THREAD

**Issue by Ufoton** [hashicorp/terraform-provider-aws#28072]
### Terraform Core Version

1.3.5

### AWS Provider Version

4.42.0

### Affected Resource(s)

  backend "s3" {
    # Replace this with your bucket name!
    bucket         = "example"
    key              = "example/tfstate"
    region          = "eu-central-2"

    # Replace this with your DynamoDB table name!
    dynamodb_table = "example"
    encrypt        = true
  }

### Expected Behavior

state stored in s3

### Actual Behavior

Error: Invalid AWS Region: eu-central-2

### Relevant Error/Panic Output Snippet

```shell
Upgrading modules...
- ec2-ami in modules/ec2-ami
- s3 in modules/s3
- vpc in modules/vpc

Initializing the backend...
region
  AWS region of the S3 Bucket and DynamoDB Table (if used).

  Enter a value: eu-central-2

╷
│ Error: Invalid AWS Region: eu-central-2
│ 
│ 
╵
```

### Terraform Configuration Files

terraform {
  backend "s3" {
    # Replace this with your bucket name!
    bucket         = "example"
    key            = "terraform.tfstate"

    # Replace this with your DynamoDB table name!
    dynamodb_table = "example"
    encrypt        = true
  }
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}

### Steps to Reproduce

store state in s3 eu-central-2

**Comment by ewbankkit** [comment]
Similar: https://github.com/hashicorp/terraform-provider-aws/issues/27917.

**Comment by ewbankkit** [comment]
@Ufoton Thanks for raising this issue 👏.

It is the [Terraform S3 Backend](https://developer.hashicorp.com/terraform/language/settings/backends/s3) that is reporting this error, not the Terraform AWS Provider.
Until a version of the Terraform CLI that supports this AWS Region has been released you can use the [`skip_region_validation`](https://developer.hashicorp.com/terraform/language/settings/backends/s3#skip_region_validation) configuration setting to suppress this error:

```hcl
terraform {
  backend "s3" {
    skip_region_validation = true
  }
}
```

**Comment by justinretzolk** [comment]
This region is supported in Terraform as of version 1.6.0 after the [S3 backend overhaul](https://github.com/hashicorp/terraform/blob/v1.6/CHANGELOG.md#160-october-4-2023). With that in mind, closing.
