### ISSUE TITLE
[Bug]: Waf default behavior change

### ISSUE THREAD

**Issue by emily-ganze** [hashicorp/terraform-provider-aws#28077]
### Terraform Core Version

1.1.8

### AWS Provider Version

2.8.2

### Affected Resource(s)

aws_wafv2_web_acl

### Expected Behavior

Change the default waf behavior from allow to block

### Actual Behavior

Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.waf.aws_wafv2_web_acl.wafv2_acl to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an
│ invalid new value for .rule: planned set element
│ 

...

│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Relevant Error/Panic Output Snippet

```shell
Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.waf.aws_wafv2_web_acl.wafv2_acl to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an
│ invalid new value for .rule: planned set element
```

### Terraform Configuration Files

MODULE:

resource "aws_wafv2_web_acl" "wafv2_acl" {
  name  = "${var.name}_${var.env}"
  scope = "REGIONAL"

  lifecycle {
    create_before_destroy = true
  }

  default_action {
    dynamic "allow" {
      for_each = var.default_action == "allow" ? [1] : []
      content {}
    }
    dynamic "block" {
      for_each = var.default_action == "block" ? [1] : []
      content {}
    }
  }
.....

CONFIG
module "waf" {
  source                    = "git::https://github.com/WAF_module"
  account_id             = local.account
  env                          = local.env
  name                       = local.name
  ip_allowlist_action = local.action
  default_action        = "block"
.......

### Steps to Reproduce

change an existing waf default behavior from allow to block

**Comment by ewbankkit** [comment]
@emily-ganze Thanks for raising this issue.
It has already been noticed in #27273. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
