### ISSUE TITLE
[Bug]: aws_lb_target_group stickiness not reflected in plan diff

### ISSUE THREAD

**Issue by nwalters512** [hashicorp/terraform-provider-aws#28083]
### Terraform Core Version

1.3.5

### AWS Provider Version

4.40.0

### Affected Resource(s)

aws_lb_target_group

### Expected Behavior

When I enable and configure target group stickiness outside of Terraform (for instance, via the AWS Console), I would expect that I would see a diff during `terraform plan` if my corresponding Terraform resource doesn't correctly include stickiness configuration.

### Actual Behavior

`terraform plan` produces a clean diff.

### Terraform Configuration Files

This snippet is taken straight from https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group:

```hcl
resource "aws_lb_target_group" "test" {
  name     = "tf-example-lb-tg"
  port     = 80
  protocol = "HTTP"
  vpc_id   = aws_vpc.main.id
}

resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
}
```

### Steps to Reproduce

1. Apply the above config to create the target group.
2. In the AWS console, manually enable stickiness.
3. Run `terraform plan` with the above; observe that no diff is created.

### References

It's possible that this is related to #15144; the problem described there seems to be similar.

**Comment by gdavison** [comment]
Related to #22526
