### ISSUE TITLE
Provider accesses DescribeVpcClassicLink API calls when ClassicLink is disabled

### ISSUE THREAD

**Issue by pavan-datazip** [hashicorp/terraform-provider-aws#28089]
### Description

Hi, this issue is the same as https://github.com/hashicorp/terraform-provider-aws/issues/15107 . Could not re-open that issue.
The details goes as follows: I am trying to create a EKS cluster and it works well with the ap-south-1 region but facing this problem when i switch the region to ap-southeast-1 or any other one. This happens although my account does not have classic link enabled or even if I mention the enable_classic_link as false. 

Terraform CLI and Terraform AWS Provider Version
Terraform v1.3.5
* hashicorp/aws: version = ">=4.0" provider is latest : 4.43.0

Affected Resource(s)
aws_vpc

Terraform Configuration Files

```hcl
resource "aws_vpc" "vpc" {
  cidr_block                       =  19.17.0.0/16
  enable_classiclink               = false
  enable_classiclink_dns_support   = false
  assign_generated_ipv6_cidr_block = false
  tags = {
    Name        = format("%s-%s-vpc", var.app_name, var.app_environment)
    Environment = var.app_environment
  }
}
```

Debug Output:

![image](https://user-images.githubusercontent.com/112616497/204777677-8091e07d-08fd-444a-b3be-d6a94f1f7524.png)

Panic Output
N/A

Expected Behavior
It should create a EKS cluster in the specified region ( eg: ap-southeast-1 and us-east-1 -- i have tried)

Actual Behavior
Terraform calls out to DescribeVpcClassicLink when creating a VPC that has ClassicLink disabled

**Comment by jar-b** [comment]
Closed by #30966, merged to `main` via #31392
