### ISSUE TITLE
[Bug]: aws_vpc_ipam_pool_cidr fails refresh if pool has been deleted

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform-provider-aws#28095]
### Terraform Core Version

1.3.x

### AWS Provider Version

4.28.x

### Affected Resource(s)

aws_vpc_ipam_pool_cidr

### Expected Behavior

should recreate on all but destroys, should remove from state gracefully

### Actual Behavior

aws_vpc_ipam_pool_cidr.test: Refreshing state... [id=172.2.0.0/16_ipam-pool-<>]
╷
│ Error: InvalidIpamPoolId.NotFound: The ipam-pool ID 'ipam-pool-<>' does not exist
│       status code: 400, request id: <>

### Terraform Configuration Files

n/a

### Steps to Reproduce

n/a

### Would you like to implement a fix?

Yes

**Comment by ewbankkit** [comment]
I _think_ this was fixed via https://github.com/hashicorp/terraform-provider-aws/pull/27590, released in **v4.38.0** of the Terraform AWS Provider.

**Comment by drewmullen** [comment]
correct, thank you, kit
