### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nefnohack** [hashicorp/terraform-provider-aws#28094]
### Terraform Core Version

1.15.3,0.15.0

### AWS Provider Version

latest

### Affected Resource(s)

aws_sns_topic_subscription

### Expected Behavior

Run aws Subscribe in AWS china region, It shouble be successfully

### Actual Behavior

but there is error: 
aws_sns_topic_subscription.results_updates_sqs_target: Creating...
╷
│ Error: creating SNS Topic Subscription: InvalidParameter: Invalid parameter: Attributes Reason: Unknown attribute FilterPolicyScope

check Cloudtrail, found auto add the parameter FilterPolicyScope, but china region now don't support this parameter

### Relevant Error/Panic Output Snippet

```shell
│ Error: creating SNS Topic Subscription: InvalidParameter: Invalid parameter: Attributes Reason: Unknown attribute FilterPolicyScope
```

### Terraform Configuration Files

```hcl
resource "aws_sns_topic_subscription" "results_updates_sqs_target" {
    topic_arn = "${aws_sns_topic.results_updates.arn}"
    protocol  = "sqs"
    filter_policy = jsonencode(
    {
      "InitiatorCompanyRegion" = ["cn-north-1"]
    },)
    endpoint  = "${aws_sqs_queue.results_updates_queue.arn}"
}
```

### Steps to Reproduce

just terrform apply

### Would you like to implement a fix?

Yes

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/28004.
