### ISSUE TITLE
[Enhancement]: Amazon Kinesis Data Analytics now supports Apache Flink v1.15

### ISSUE THREAD

**Issue by jinbal-zego** [hashicorp/terraform-provider-aws#28096]
### Description

You can now build and run streaming applications using Apache Flink version 1.15 in Amazon Kinesis Data Analytics for Apache Flink.

### Affected Resource(s) and/or Data Source(s)

* aws_kinesisanalyticsv2_application

### Potential Terraform Configuration

```terraform
resource "aws_kinesisanalyticsv2_application" "example" {
  name                   = "example-flink-application"
  runtime_environment    = "FLINK-1_15"
}
```

### References

https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-kinesis-data-analytics-apache-flink-supports-flink-version-1-15/

**Comment by ewbankkit** [comment]
This value was added in [AWS SDK for Go v1.44.144](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.144), https://github.com/hashicorp/terraform-provider-aws/pull/27964, which was incorporated into [Terraform AWS Provider v4.41.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.41.0).
I'll make sure that the documentation is updated.

**Comment by ewbankkit** [comment]
@jinbal-zego Thanks for raising this issue 👏.
If you use a version of the Terraform AWS Provider greater than or equal to **v4.41.0** the `"FLINK-1_15"` value will be accepted.
