### ISSUE TITLE
[Enhancement]: ECS Service Connect Configuration

### ISSUE THREAD

**Issue by mlautur** [hashicorp/terraform-provider-aws#28101]
### Description

AWS has just announced support for service connect configuration. The configuration is supported in [Cloudformation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-serviceconnectconfiguration).

### Affected Resource(s) and/or Data Source(s)

aws_ecs_service

### Potential Terraform Configuration

```terraform
service_connect_configuration {
    namespace = "svc-namespace"
    services {
      port_name = "webui-port"
      client_aliases {
        port     = 80
        dns_name = "webui"
      }
    }
  }
```

### References

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-serviceconnectconfiguration.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-serviceconnectservice.html

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@mlautur Thanks for raising this issue.
It has already been noticed in #28043. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
