### ISSUE TITLE
[Enhancement]: Add ECR Registry Permissions Resource

### ISSUE THREAD

**Issue by dimisjim** [hashicorp/terraform-provider-aws#28115]
### Description

I would like to be able to define the registry permissions JSON, which is necessary for cross account replication on the destination end. So https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_replication_configuration covers the origin part, but not the destination one.

### Affected Resource(s) and/or Data Source(s)

* aws_ecr_replication_configuration (not per se affected, but related)

**Comment by DrFaust92** [comment]
aws_ecr_registry_policy ?

**Comment by dimisjim** [comment]
Indeed @DrFaust92. Closing this.
