### ISSUE TITLE
[New Resource]: CloudWatch Internet Monitor

### ISSUE THREAD

**Issue by xremming** [hashicorp/terraform-provider-aws#28118]
### Description

[CloudWatch Internet Monitor](https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-cloudwatch-internet-monitor-preview/) was released a few days ago to Preview. It would be nice to have that available in the AWS Terraform provider, for now I have created it manually through the web console.

### Requested Resource(s) and/or Data Source(s)

* aws_cloudwatch_internet_monitor

### Potential Terraform Configuration

```terraform
resource "aws_cloudwatch_internet_monitor" "webshop" {
  name = "WebShop"
  // also support name_prefix as the name needs to be unique
  // name_prefix = "WebShop"

  // repeatable, min: 1
  resource {
    arn = "arn:aws:ec2:us-east-1:111122223333:vpc/vpc-11223344556677889"
  }
  // could also be
  // resource_arns = ["arn:aws:ec2:us-east-1:111122223333:vpc/vpc-11223344556677889"]
  // but I would imagine that is much less future proof
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-cloudwatch-internet-monitor-preview/
* https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-InternetMonitor.html

### Would you like to implement a fix?

No

**Comment by DrFaust92** [comment]
i dont see this is supported yes by go sdk

**Comment by jabrks** [comment]
This appears to be supported by the Go SDK now as of the latest release: https://docs.aws.amazon.com/sdk-for-go/api/service/internetmonitor/

**Comment by DrFaust92** [comment]
[bobsut](https://github.com/bobsut) yep, ill also take a look at adding support for this
