### ISSUE TITLE
Provider produces inconsistent final plan[Bug]: 

### ISSUE THREAD

**Issue by pmreddy87** [hashicorp/terraform-provider-aws#28121]
### Terraform Core Version

Terraform v1.3.5

### AWS Provider Version

aws-cli/2.7.25 

### Affected Resource(s)

Unable to create resources 

### Expected Behavior

create resources- upload artifats to S3 bucket

### Actual Behavior

Provider produces inconsistent final plan - showing as bug of provider

### Relevant Error/Panic Output Snippet

```shell
Provider produces inconsistent final plan - showing as bug of provider
```

### Terraform Configuration Files

Provider produces inconsistent final plan - showing as bug of provider

### Steps to Reproduce

Provider produces inconsistent final plan - showing as bug of provider

### Debug Output

Provider produces inconsistent final plan - showing as bug of provider

### Panic Output

Provider produces inconsistent final plan - showing as bug of provider

### Important Factoids

Provider produces inconsistent final plan - showing as bug of provider

### References

Provider produces inconsistent final plan - showing as bug of provider

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @pmreddy87 👋 Thank you for taking the time to raise this. Unfortunately, there's not enough information here for us to look into the error you're seeing, so we'll close this issue for now. If you have additional information that you might be able to provide, please feel free to open a new bug report and fill out the template to supply it.
