### ISSUE TITLE
[Enhancement]: Streaming Experience Settings for aws_appstream_stack

### ISSUE THREAD

**Issue by szemkhel** [hashicorp/terraform-provider-aws#28147]
### Description

Streaming experience settings for the appstream stack are not defined in terraform documentation, so I believe they are not available but should be part of the configuration as they are available via the AWS console, API, and CLI:

### Affected Resource(s) and/or Data Source(s)

aws_appstream_stack

### Potential Terraform Configuration

```terraform
resource "aws_appstream_stack" "example" {
    <...>
    streaming_experience = "UDP"
    /*
    Choose either TCP or UDP. The default is TCP.
    UDP streaming when using VPC endpoints is not supported.
    UDP streaming is currently only supported in the Windows native client.
    */
}
```

### References

- AWS documentation: https://docs.aws.amazon.com/appstream2/latest/developerguide/client-system-requirements-feature-support.html?cmpid=docs_appstream2_helppanel

- AWS CLI option: https://docs.aws.amazon.com/cli/latest/reference/appstream/create-stack.html#:~:text=%2D%2Dstreaming%2Dexperience%2Dsettings%20(structure)

- AWS API option: https://docs.aws.amazon.com/appstream2/latest/APIReference/API_CreateStack.html#API_CreateStack_RequestSyntax

### Would you like to implement a fix?

None

**Comment by mihneaspirescu** [comment]
I'll pick this one up!
