### ISSUE TITLE
[Enhancement]: EventBridge Pipes

### ISSUE THREAD

**Issue by bradwood** [hashicorp/terraform-provider-aws#28153]
### Description

Please add support for EventBridge Pipes -- see https://aws.amazon.com/eventbridge/pipes/

### Would you like to implement a fix?

No

**Comment by ad-m-ss** [comment]
FTR: Anybody interested to give a shot to AWS EventBridge Pipes may use temporary `aws_cloudformation_stack` and https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pipes-pipe.html as a workaround.

**Comment by roberth-k** [comment]
Apologies, this is still in progress... Some of the sources and targets have invisible, un-documented default parameter values, which has been difficult to reconcile with Terraform's diffs under some combinations of resource updates. I'm slowly inching towards solving the edge cases, but it may yet be some time before this is complete.

**Comment by gianlo** [comment]
The best docs I found are on the CLI's documentation:
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/pipes/create-pipe.html

**Comment by SolomonHD** [comment]
@roberth-k Your changes were merged into main a couple of months ago; did this make it to a new terraform version?

**Comment by brittandeyoung** [comment]
Looks like this issue did not get closed with the PR merge. Closing it out as the resource in the pr covers the request.

**Comment by brittandeyoung** [comment]
@roberth-k was this left open intentionally? I want to make sure I am only closing the issue if it’s actually completed.

**Comment by roberth-k** [comment]
Hi @brittandeyoung -- https://github.com/hashicorp/terraform-provider-aws/pull/30538 is a partial implementation, so this issue should remain open.

**Comment by jordanfinners** [comment]
Working with @roberth-k on filling out the parameters etc :) 
There's an awful lot of sources and targets, so bear with us!

**Comment by jordanfinners** [comment]
Working through the tests now! Hopefully shouldn't be too much longer :)

**Comment by jordanfinners** [comment]
I've got a PR open, if you give it thumbs up, it'll help get prioritised https://github.com/hashicorp/terraform-provider-aws/pull/31607#issue-1728257255
