### ISSUE TITLE
[Docs]: aws_apigatewayv2_deployment sample uses deprecated and now deleted "list" function

### ISSUE THREAD

**Issue by fdaugan** [hashicorp/terraform-provider-aws#28157]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_deployment

### Description

Replace `list` by `tolist` in the following sample:

Replace:
``` hcl
resource "aws_apigatewayv2_deployment" "example" {
  api_id      = aws_apigatewayv2_api.example.id
  description = "Example deployment"

  triggers = {
    redeployment = sha1(join(",", list(
      jsonencode(aws_apigatewayv2_integration.example),
      jsonencode(aws_apigatewayv2_route.example),
    )))
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

By:
``` hcl
resource "aws_apigatewayv2_deployment" "example" {
  api_id      = aws_apigatewayv2_api.example.id
  description = "Example deployment"

  triggers = {
    redeployment = sha1(join(",", tolist([
      jsonencode(aws_apigatewayv2_integration.example),
      jsonencode(aws_apigatewayv2_route.example),
    ])))
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

### References

From the terraform ouput:
``` log
Call to function "list" failed: the "list" function was deprecated in Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to write a literal list.
```

### Would you like to implement a fix?

Yes

**Comment by xasterKies** [comment]
Hello @fdaugan , is this issue still open?

**Comment by fdaugan** [comment]
Yes this issue is still open.
Current [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_deployment):
<img width="504" alt="image" src="https://user-images.githubusercontent.com/579170/207571760-36055d3b-583f-4669-b0bb-d1622d50fd5a.png">

**Comment by xasterKies** [comment]
ok thanks. I am currently new to the project codebase and will like to know if I need to change this in the codebase and make a pull request?

**Comment by xasterKies** [comment]
Yes please I will love to be pointed too it if possible

**Comment by fdaugan** [comment]
I just found the right place of documentation to update:
https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/apigatewayv2_deployment.html.markdown

I am creating the pull request for this issue

**Comment by xasterKies** [comment]
Ohh wow, Thank you very much for the help @fdaugan . I know how to navigate it now :)
