### ISSUE TITLE
[Bug]: Engine version not supported when engine is aurora-postgresql in aws_rds_global_cluster 

### ISSUE THREAD

**Issue by rutujachaudhari124** [hashicorp/terraform-provider-aws#28189]
### Terraform Core Version

0.12.31

### AWS Provider Version

3.70.0

### Affected Resource(s)

aws_rds_global_cluster

### Expected Behavior

As per the AWS documentation, for engine parameter as aurora-postgresql, engine versions 10.14 and higher, 12.4 and higher or 11.9 and higher versions should be supported.

### Actual Behavior

But after testing we found out that only version 13.4 and higher are supported as engine version when value for engine parameter is aurora-postgresql.

### Relevant Error/Panic Output Snippet

```shell
Error: error creating RDS Global Cluster: InvalidParameterValue: The requested engine version was not found or does not support global functionality
```

### Terraform Configuration Files

```terraform
resource "aws_rds_global_cluster" "example_2" {
    global_cluster_identifier = "******************"
    deletion_protection       = false
    force_destroy             = false
    database_name             = "***************"
    engine                    = "aurora-postgresql"
    engine_version            = "12.4"
    storage_encrypted         = false
}
```

### Steps to Reproduce

1.terraform plan
2.terraform apply

### References

AWS documentation: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Concepts.Aurora_Fea_Regions_DB-eng.Feature.GlobalDatabase.html#Concepts.Aurora_Fea_Regions_DB-eng.Feature.GlobalDatabase.amy

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @rutujachaudhari124 👋 Thank you for taking the time to raise this! Based on the error that you pasted, this looks like it's coming from the AWS API. That said, can you supply debug logs (redacted as needed) so that we can take a better look at this?

**Comment by rutujachaudhari124** [comment]
Closing this issue as it is invalid, this is because AWS has announced that the versions mentioned in this issue (engine versions 10.14 and higher, 12.4 and higher) are deprecated by Amazon RDS.

**Comment by rutujachaudhari124** [comment]
Closing this issue as it is invalid, this is because AWS has announced that the versions mentioned in this issue (engine versions 10.14 and higher, 12.4 and higher) are deprecated by Amazon RDS.
