### ISSUE TITLE
r/aws_medialive_multiplex_program: Remove deprecated `statemux_settings` attribute

### ISSUE THREAD

**Issue by jar-b** [hashicorp/terraform-provider-aws#28190]
### Description

Issue for tracking the removal of the deprecated `statemux_settings` attribute in the `v5.0.0` provider release.

https://github.com/hashicorp/terraform-provider-aws/blob/627c16060ccd4e4d61624e64bec6c63fbc44ff26/internal/service/medialive/multiplex_program.go#L112-L142

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/27223.

**Comment by johnsonaj** [comment]
Closed in #31034
