### ISSUE TITLE
[Bug]: aws_ecs_service refreshing state stuck 

### ISSUE THREAD

**Issue by KamranBiglari** [hashicorp/terraform-provider-aws#28194]
### Terraform Core Version

1.3.6

### AWS Provider Version

4.45.0

### Affected Resource(s)

After upgrading to AWS 4.45.0 , it only handles 10 aws_ecs_service refreshing state each time and sleeps for 2 - 3 minutes and then updates the next 10 aws_ecs_service.

also, I'm getting errors when try to destroy aws_ecs_service.
`Error decoding "aws_ecs_service.calc-step3[\"13\"]" from previous state: unsupported attribute "service_connect_configuration"`trying

### Expected Behavior

Act faster like the older versions

### Actual Behavior

Slow with error

### Terraform Configuration Files

```terraform
resource "aws_ecs_service" "calc-step3" {
#   for_each = {for k,pair in local.Calc3pairs : k => join(":",pair)}
  for_each = aws_ecs_task_definition.calc-step3
  name            = "cryptofeed-calculation-step3-${each.key}-service"
  cluster         = local.ECS.cluster_name
  task_definition = aws_ecs_task_definition.calc-step3[each.key].arn
  desired_count   = 1
  launch_type     = "FARGATE"
  depends_on      = [aws_ecs_task_definition.calc-step3, local.ECR, local.ECS]

  deployment_maximum_percent         = 200
  deployment_minimum_healthy_percent = 100
  enable_execute_command             = true

  platform_version = "1.4.0"
  network_configuration {
    assign_public_ip = false
    security_groups  = local.SECURITY_GROUPS
    subnets          = local.PRIVATE_SUBNETS
  }

  tags = { Name = "cryptofeed-calculation-step3-${each.key}-service" }
  
}
```

### Steps to Reproduce

terraform init

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @KamranBiglari 👋 Thank you for taking the time to raise this! So that we have the necessary information in order to look into this, can you supply debug logs (redacted as needed) as well?
