### ISSUE TITLE
[Enhancement]: Add msk cluster uuid as an output 

### ISSUE THREAD

**Issue by rmccooey** [hashicorp/terraform-provider-aws#28196]
### Description

It would be great if we could add the msk cluster uuid as an output to the MSK cluster provider: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_cluster

the cluster uuid is used to build other iam policies on topics and consumer groups so it would be great if it were exported on it's own not just exported as a part of the cluster arn 

another option would be to be able to export the topic arn and the consumer group arn that are used to construct iam policies: https://docs.aws.amazon.com/msk/latest/developerguide/security_iam_service-with-iam.html 

examples: 
cluster arn: arn:aws:kafka:us-east-1:{account_number}:cluster/{msk_cluster_name}/58888ed9-755e-4f66-9e30-7ba0651dd24f-23

cluster_uuid: 58888ed9-755e-4f66-9e30-7ba0651dd24f-23

### Affected Resource(s) and/or Data Source(s)

msk_cluster: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_cluster 

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Cluster ARN format: https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonmanagedstreamingforapachekafka.html#amazonmanagedstreamingforapachekafka-resources-for-iam-policies.
