### ISSUE TITLE
[Enhancement]: aws_guardduty_detector RDS support

### ISSUE THREAD

**Issue by cvlc** [hashicorp/terraform-provider-aws#28229]
### Description

[Amazon GuardDuty RDS protection is now in feature preview](https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-guardduty-rds-protection-preview/) but the Terraform resource does not yet support it. 

It would be great if it was supported by the Terraform resource so it could be easily enabled for those using GuardDuty and the most popular IaaC tool.

### Affected Resource(s) and/or Data Source(s)

* resource: aws_guardduty_detector
* data: aws_guardduty_detector

### Potential Terraform Configuration

```terraform
resource "aws_guardduty_detector" "MyDetector" {
  enable = true

  datasources {
    s3_logs {
      enable = true
    }
    rds {
      enable = true
    }
    kubernetes {
      audit_logs {
        enable = false
      }
    }
    malware_protection {
      scan_ec2_instance_with_findings {
        ebs_volumes {
          enable = true
        }
      }
    }
  }
}
```

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_detector
https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-guardduty-rds-protection-preview/
https://docs.aws.amazon.com/guardduty/latest/ug/rds-protection.html

### Would you like to implement a fix?

None

**Comment by javierbeaumont** [comment]
Please, same enhancement for `aws_guardduty_organization_configuration` resource.

**Comment by pippin-wallace** [comment]
Does this need to be out of preview prior to being supported?

**Comment by theonlysinjin** [comment]
Is the issue that there is no API on it?
If I look at the [aws api docs](https://docs.aws.amazon.com/guardduty/latest/APIReference/API_UpdateDetector.html) it's not listed either.

**Comment by lawliet89** [comment]
This feature has gone GA: https://aws.amazon.com/about-aws/whats-new/2023/03/amazon-guardduty-rds-protection-aurora-generally-available/

**Comment by lawliet89** [comment]
At the time of writing, this option is missing from the API and is not possible to implement: https://docs.aws.amazon.com/guardduty/latest/APIReference/API_DataSourceConfigurations.html

**Comment by sakojun** [comment]
The use of `dataSources` is deprecated and the use of `features` is recommended.
https://docs.aws.amazon.com/guardduty/latest/ug/guardduty-feature-object-api-changes-march2023.html

**Comment by Galal-Eltfawy** [comment]
any plans for adding RDS protection and EKS runtime monitoring?

**Comment by cookiesowns** [comment]
Bump. Would be great to get the EKS runtime monitoring flags for guardduty  As otherwise the EKS guardduty addon resource will fail to create in terraform if you don't already have it enabled.

**Comment by cyn110** [comment]
Bump please now that GuardDuty RDS is officially launched.

**Comment by ewbankkit** [comment]
You will be able to use the upcoming `aws_guardduty_detector_feature` resource (https://github.com/hashicorp/terraform-provider-aws/pull/31463):

```hcl
resource "aws_guardduty_detector" "example" {
  enable = true
}

resource "aws_guardduty_detector_feature" "example" {
  detector_id = aws_guardduty_detector.example.id
  name        = "RDS_LOGIN_EVENTS"
  status      = "ENABLED"
}
```
