### ISSUE TITLE
[Bug]: Error: waiting for QLDB Ledger (ledger) delete: timeout while waiting for resource to be gone (last state: 'DELETING', timeout: 5m0s)

### ISSUE THREAD

**Issue by arvenil** [hashicorp/terraform-provider-aws#28231]
### Terraform Core Version

1.3.2

### AWS Provider Version

4.33.0

### Affected Resource(s)

* aws_qldb_ledger

### Expected Behavior

Resource should get destroyed but instead I get timeout. How can I increase this timeout?

### Actual Behavior

│ Error: waiting for QLDB Ledger (ledger) delete: timeout while waiting for resource to be gone (last state: 'DELETING', timeout: 5m0s)

**Comment by dgalichet** [comment]
I see that issue has been closed. Is there a fix ?
I've tested with latest provider and still have the issue.

**Comment by dgalichet** [comment]
Hi there, any insights regarding this issue ?
