### ISSUE TITLE
[Bug]: Unable to specify the same subnet twice for aws_route53_resolver_endpoint

### ISSUE THREAD

**Issue by bodgit** [hashicorp/terraform-provider-aws#28233]
### Terraform Core Version

1.3.6

### AWS Provider Version

4.45.0

### Affected Resource(s)

* aws_route53_resolver_endpoint

### Expected Behavior

You should be able to specify the same subnet ID twice

### Actual Behavior

`Attribute ip_address requires 2 item minimum, but config has only 1 declared.`

### Terraform Configuration Files

```
resource "aws_route53_resolver_endpoint" "test" {
  name      = "test"
  direction = "INBOUND"

  security_group_ids = [
    ...,
  ]

  ip_address {
    subnet_id = "subnet-XXX" # Same subnet ID
  }

  ip_address {
    subnet_id = "subnet-XXX" # Same subnet ID
  }
}
```

### Steps to Reproduce

See the above configuration

### Important Factoids

I'm trying to deploy Route53 resolver endpoints to a VPC that intentionally only has one AZ/subnet. AWS require you to have at least two IP addresses, normally in separate AZs/subnets, however it's perfectly valid to put both IP addresses in the same subnet. The AWS UI allows you to do this, Terraform seemingly does not.

### Would you like to implement a fix?

None

**Comment by bodgit** [comment]
So it looks like this is because the `ip_address` is considered a set. By only specifying the subnet ID, both `ip_address` blocks hash to the same value so they're considered identical.

The only way to allow the same subnet ID is to explicitly declare IP addresses, (which in >= 4.40.0 will work, thanks to #25708), but I'm loathe to do this as this resource is in a module which is used in lots of accounts so a) I don't know the address ranges and b) I don't know what IP addresses have already been allocated so I can't just say something like "the 13th and 14th addresses in the subnet" because in one account one/both of those will be allocated already.

Perhaps this shouldn't be a set?

**Comment by DrFaust92** [comment]
@bodgit if it wont be a set there will a diffs because it will assume order of a list /:
