### ISSUE TITLE
[Enhancement]: VPC support for Grafana workspaces

### ISSUE THREAD

**Issue by arkadiyt** [hashicorp/terraform-provider-aws#28244]
### Description

AWS Managed Grafana workspaces can be spun up inside VPCs:
- https://docs.aws.amazon.com/grafana/latest/userguide/AMG-configure-vpc.html

but the terraform resource does not support this configuration:
- https://docs.aws.amazon.com/grafana/latest/APIReference/API_CreateWorkspace.html
- https://docs.aws.amazon.com/grafana/latest/APIReference/API_UpdateWorkspace.html

### Affected Resource(s) and/or Data Source(s)

- aws_grafana_workspace

### Potential Terraform Configuration

Sample:

```terraform
resource "aws_grafana_workspace" "example" {
  account_access_type      = "CURRENT_ACCOUNT"
  authentication_providers = ["SAML"]
  permission_type          = "SERVICE_MANAGED"
  role_arn                 = aws_iam_role.assume.arn
  vpc_configuration {
    security_group_ids = ["group1", "group2"]
    subnet_ids = ["subnet1", "subnet2"]
  }
}
```

### References

- https://docs.aws.amazon.com/grafana/latest/userguide/AMG-configure-vpc.html
- https://docs.aws.amazon.com/grafana/latest/APIReference/API_CreateWorkspace.html
- https://docs.aws.amazon.com/grafana/latest/APIReference/API_UpdateWorkspace.html

### Would you like to implement a fix?

None

**Comment by DrFaust92** [comment]
looking into this
