### ISSUE TITLE
[Enhancement]: Support `PlacementStrategy` in `aws_cloudwatch_event_target` with `ecs_target`

### ISSUE THREAD

**Issue by longwave** [hashicorp/terraform-provider-aws#28259]
### Description

CloudWatch / EventBridge provides the option to specify task placement strategies in an ECS Task target, which is currently not supported in Terraform.

### Affected Resource(s) and/or Data Source(s)

* aws_cloudwatch_event_target

### Potential Terraform Configuration

```terraform
resource "aws_cloudwatch_event_target" "ecs_scheduled_task" {
...

  ecs_target {
    ...

    ordered_placement_strategy {
      type  = "spread"
      field = "attribute:ecs.availability-zone"
    }

    ordered_placement_strategy {
      type  = "binpack"
      field = "memory"
    }

  }

}
```

### References

* #27068
* aws/aws-sdk-go#3974
* https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_EcsParameters.html#eventbridge-Type-EcsParameters-PlacementStrategy

### Would you like to implement a fix?

None

**Comment by mihneaspirescu** [comment]
I'll pick this one up!
