### ISSUE TITLE
[New]: Data source aws_s3control_multi_region_access_point

### ISSUE THREAD

**Issue by jamesmudd** [hashicorp/terraform-provider-aws#28251]
### Description

There currently a resource `aws_s3control_multi_region_access_point` but no corresponding data source. It seems like a common use case that you might want to get data about a S3 multi region access point in a separate TF configuration so the data source would be required. I thin looking up the access point by name should be possible and the simplest to use.

If you attempt this at the moment you received the following error
```
│ Error: Invalid data source
│ 
│   on exisitng.tf line 21, in data "aws_s3control_multi_region_access_point" "web_server_db_access_point":
│   21: data "aws_s3control_multi_region_access_point" "web_server_db_access_point" {
│ 
│ The provider hashicorp/aws does not support data source "aws_s3control_multi_region_access_point".
│ 
│ Did you intend to use the managed resource type "aws_s3control_multi_region_access_point"? If so, declare this using a "resource" block instead of a "data" block.
```

### Requested Resource(s) and/or Data Source(s)

data "aws_s3control_multi_region_access_point"

### Potential Terraform Configuration

```terraform
data "aws_s3control_multi_region_access_point" "web_server_db_access_point" {
  name = "web-server-db-ap"
}
```

### Would you like to implement a fix?

No

**Comment by tiborhercz** [comment]
I will pick this one up

**Comment by bschaatsbergen** [comment]
Good stuff @tiborhercz, looking forward to the PR.
