### ISSUE TITLE
[Docs]: Resource: aws_cognito_risk_configuration

### ISSUE THREAD

**Issue by quetonix** [hashicorp/terraform-provider-aws#28250]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_risk_configuration#test_body

### Description

```
notify email type:

[test_body] - The email text body

```
 *Should be:* 

```
notify email type:

[text_body] - The email text body

```

te**s**t_body needs to be changed to te**x**t_body

### References

https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/set-risk-configuration.html

Shows that the emails contain:

Subject -> (string) The email subject.
HtmlBody -> (string) The email HTML body.
**TextBody** -> (string) The email text body.

### Would you like to implement a fix?

None

**Comment by DrFaust92** [comment]
Sure thing, go ahead
