### ISSUE TITLE
[Enhancement]: ad connector support for aws_workspaces_directory

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#28278]
### Description

When creating an AWS Workspace Directory it will be good to have support for AD connectors.

### Affected Resource(s) and/or Data Source(s)

aws_workspaces_directory

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
