### ISSUE TITLE
[Bug]: After switching an RDS instance from gp2 to gp3, following apply will fail if IOPS is not specified

### ISSUE THREAD

**Issue by etiennechabert** [hashicorp/terraform-provider-aws#28271]
### Terraform Core Version

1.2.3

### AWS Provider Version

4.46.0

### Affected Resource(s)

- aws_db_instance

### Expected Behavior

If specifying `iops` is mandatory when choosing `gp3`:
- You should not be able to apply the change without specifying it, a validator is missing

If IOPS is NOT mandatory when choosing `gp3`:
- You should not be blocked during further apply, and your plan should not describe a change about `iops`

### Actual Behavior

The first apply was successful, allowing me to switch an existing RDS instance from GP2 to GP3. But now my pipeline is blocked with the following plan/error
```
  ~ resource "aws_db_instance" "this" {
        id                                    = "a_db"
      ~ iops                                  = 3000 -> 0
        name                                  = "a_db"

....

│ Error: updating RDS DB Instance (a_db): operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: 61792e08-c93b-4834-a35c-eb029b29ba30, api error InvalidParameterCombination: You can't specify IOPS or storage throughput for engine postgres and a storage size less than 400.
```

I can work around the error by adding to my resource the optional `iops` parameter with a value of `3000`, unblocking my pipeline by avoiding the change:
```
  resource "aws_db_instance" "this" {
      id                                    = "a_db"
      iops                                  = 3000
      name                                  = "a_db"
        
...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Terraform Configuration Files

```
resource "aws_db_instance" "default" {
  ...
  allocated_storage  = 20
  storage_type       = "gp2"
}
```

After first apply (you have an RDS instance on gp2), change storage_type, and apply two times: after the 1st apply you are on gp3, but now the 2nd (and following) applies will fail:
```
resource "aws_db_instance" "default" {
  ...
  allocated_storage  = 20
  storage_type       = "gp3"
}
```

### Steps to Reproduce

- Create an RDS instance (postgres might be important), with a gp2 volume of 20 GB
- After first apply, switch it to gp3 without specifying the IOPS parameter
- Try to apply again, you should now see an unexpected change:
  -  0 → 3000 IOPS
  - Your apply will fail with the following error: 
  - `api error InvalidParameterCombination: You can't specify IOPS or storage throughput for engine postgres and a storage size less than 400`

### Would you like to implement a fix?

None

**Comment by etiennechabert** [comment]
Related to: 
- https://github.com/hashicorp/terraform-provider-aws/issues/27702
- https://github.com/hashicorp/terraform-provider-aws/issues/28160

Should have been fixed by:
- https://github.com/hashicorp/terraform-provider-aws/pull/28243

**Comment by ewbankkit** [comment]
@etiennechabert Thanks for raising this issue.
In your Terraform configuration do you have an explicit `iops = 0` or are you omitting that attribute completely?

**Comment by etiennechabert** [comment]
@ewbankkit during the first apply, the one that succeeded initially, switching my instance from gp2 to gp3, my terraform configuration was not specifying anything for IOPS... but I realize now that the module we are using is setting `iops` to a default value of `0`:
- https://registry.terraform.io/modules/terraform-aws-modules/rds/aws/latest/submodules/db_instance#input_iops
- Effectively, I am having `iops = 0` sent to the `aws_db_instance` resource because of this ⚠️ 

### First apply
- In my plan during this apply, there were no changes regarding `iops` described
  - That's probably because at this point, my database is still a gp2, therefor the remote IOPS is equal to `0`
- The apply is successful, my database is now using a `gp3` volume

### Following applies
During the following apply, the ones that failed, my terraform configuration was still not defining `iops`, but the default value of `terraform-aws-modules/rds` been `0`, this is now probably clashing with the remote state of my database and causing the change:
- My plan is now showing the following change `iops = 3000 -> 0`
- The apply is failing with the error: `You can't specify IOPS or storage throughput for engine postgres and a storage size less than 400.`
  - Kind of unrelated error with the actual issue in my opinion.
- My pipeline is blocked

### Workaround
I am now forced to set `iops = 3000` in my Terraform configuration to avoid the invalid change, unblocking my pipeline.

## Proposal to avoid this
Should the provider do a `max(3000, var.iops)` when `allocated_storage == 'gp3'`? 

My understanding is that a `gp3` volume cannot have less than 3000 IOPS according to the documentation, that would probably avoid this issue all together.

### Open question
With that been said, I am not sure anymore if this problem should actually be reported to https://github.com/terraform-aws-modules/terraform-aws-rds or is actually about the AWS Provider.

**Comment by etiennechabert** [comment]
Actually reading one more time the documentation of the module we are using, I think I can answer this question myself: https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/modules/db_instance/variables.tf#L24-L28

```
If you specify 'io1' or 'gp3' , you must also include a value for the 'iops' parameter...
```

Seems like by switching from gp2 to gp3, I am now using the module the wrong way...

Happy to close this issue if you say so.

**Comment by etiennechabert** [comment]
@TomWizen can you please share if you are using this module on top of the AWS Provider: https://github.com/terraform-aws-modules/terraform-aws-rds

**Comment by etiennechabert** [comment]
I started over again all my tests in this messages my results for creation tests (in next message I will put my transition test results):
- Create a `mariadb` with `gp3` 🟢 
- Create a `mariadb` with `gp3` while setting IOPS to 3000 🟥 
- Create a `mariadb` with gp3 while setting IOPS to 3000 and storage_throughput to 125 🟥 

Note: same results with a `postgres`

## Create a mariadb with gp3: 🟢 
```
resource "aws_db_instance" "default_gp3" {
  identifier           = "default-gp3"
  allocated_storage    = 20
  db_name              = "direct_gp3"
  engine               = "mariadb"
  engine_version       = "10.3"
  instance_class       = "db.t3.micro"
  username             = "foo"
  password             = "foobarbaz"
  parameter_group_name = "default.mariadb10.3"
  skip_final_snapshot  = true
  apply_immediately    = true
  storage_type         = "gp3"
}
```
Just works

## Create a mariadb with gp3 while setting IOPS to 3000 🟥 
```
resource "aws_db_instance" "default_gp3" {
  identifier           = "default-gp3"
  allocated_storage    = 20
  db_name              = "direct_gp3"
  engine               = "mariadb"
  engine_version       = "10.3"
  instance_class       = "db.t3.micro"
  username             = "foo"
  password             = "foobarbaz"
  parameter_group_name = "default.mariadb10.3"
  skip_final_snapshot  = true
  apply_immediately    = true
  storage_type         = "gp3"
  iops                 = 3000
}
```
Error:
```
InvalidParameterCombination: You can't specify IOPS or storage throughput for engine mariadb and a storage size less than 400
```

## Create a mariadb with gp3 while setting IOPS to 3000 and storage_throughput to 125  🟥 
```
resource "aws_db_instance" "default_gp3" {
  identifier           = "default-gp3"
  allocated_storage    = 20
  db_name              = "direct_gp3"
  engine               = "mariadb"
  engine_version       = "10.3"
  instance_class       = "db.t3.micro"
  username             = "foo"
  password             = "foobarbaz"
  parameter_group_name = "default.mariadb10.3"
  skip_final_snapshot  = true
  apply_immediately    = true
  storage_type         = "gp3"
  iops                 = 3000
  storage_throughput   = 125
}
```
Error:
```
InvalidParameterCombination: You can't specify IOPS or storage throughput for engine mariadb and a storage size less than 400
```

Note: I know that the creation is not what was initially the topic of this issue, but I still find it interesting and probably connected to this issue

**Comment by etiennechabert** [comment]
Now about transitions: 
- Create a mariadb with `gp2` and transition it to `gp3` 🟢 
- Create a mariadb with `gp2` and transition it to `gp3` with IOPS to 3000 🟥 


## Create a mariadb with `gp2` and transition it to `gp3` 🟢 
Start with 
```
resource "aws_db_instance" "default_gp2_to_gp3" {
  identifier           = "default-gp2-to-gp3"
  allocated_storage    = 20
  db_name              = "gp2_to_gp3"
  engine               = "mariadb"
  engine_version       = "10.3"
  instance_class       = "db.t3.micro"
  username             = "foo"
  password             = "foobarbaz"
  parameter_group_name = "default.mariadb10.3"
  skip_final_snapshot  = true
  apply_immediately    = true
  storage_type         = "gp2"
}
```
Then change
```
  storage_type         = "gp3"
```
Works

## Create a MariaDB with `gp2` and transition it to `gp3` with IOPS to 3000 🟥 
Start with 
```
resource "aws_db_instance" "default_gp2_to_gp3" {
  identifier           = "default-gp2-to-gp3"
  allocated_storage    = 20
  db_name              = "gp2_to_gp3"
  engine               = "mariadb"
  engine_version       = "10.3"
  instance_class       = "db.t3.micro"
  username             = "foo"
  password             = "foobarbaz"
  parameter_group_name = "default.mariadb10.3"
  skip_final_snapshot  = true
  apply_immediately    = true
  storage_type         = "gp2"
}
```
Then change
```
  storage_type         = "gp3"
  iops                 = 3000
```
Error:
```
InvalidParameterCombination: You can't specify IOPS or storage throughput for engine mariadb and a storage size less than 400
```

**Comment by TomWizen** [comment]
> @TomWizen can you please share if you are using this module on top of the AWS Provider: https://github.com/terraform-aws-modules/terraform-aws-rds

Yes

**Comment by etiennechabert** [comment]
As a conclusion, my feeling is that there is a bug with the AWS Provider module:
- It's possible to switch to `gp3`
- But you cannot modify your volume to use `storage_type = gp3` in combination with the parameters  `iops`/`storage_throughput` if your volume is smaller than `400GB`

This bug is turning to be quite blocking for the users using: https://github.com/terraform-aws-modules/terraform-aws-rds, as explained by @TomWizen, since you cannot have a valid configuration without 2x PRs

**Comment by LDVSOFT** [comment]
I've hit the same with AWS RDS module because it has explicit `variable "iops" { default = 0 }`, specifying `iops = null` explicitly makes clean plans.

**Comment by etiennechabert** [comment]
Agreed that this is a good workaround for the people using `AWS RDS Terraform module` ☝️ 

Allowing:
- A smooth transition from gp2 → gp3
- A clean plan without any changes during the following apply

**Comment by etiennechabert** [comment]
Regarding `AWS RDS Terraform module`, the version `5.2.1` will fix the default value of `IOPS`: 

https://github.com/terraform-aws-modules/terraform-aws-rds/pull/456#issuecomment-1351435350

**Comment by ewbankkit** [comment]
@etiennechabert Thanks for the very thorough write-up of your failing scenarios 👏.
I think the most maintainable answer here is to add to the [`aws_db_instance` resource documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance) noting that `iops` and `storage_throughput` cannot be specified with certain combinations of `engine` and `allocated_storage` (and to link to relevant AWS documentation) so that practitioners are warned that they may have to remove these attributes' values from Terraform code. Trying to add further logic to the provider to deal with configured values that should be ignored (rather than computed values returned from the RDS API) will further complicate an already large resource.

**Comment by ewbankkit** [comment]
@cdl-danielchapman Please open a new GitHub Issue. Thanks.
