### ISSUE TITLE
[Bug]: aws_ecrpublic_authorization_token breaks if region != us-east-1

### ISSUE THREAD

**Issue by draeath** [hashicorp/terraform-provider-aws#28281]
### Terraform Core Version

1.3.6

### AWS Provider Version

4.46.0

### Affected Resource(s)

* aws_ecrpublic_authorization_token

### Expected Behavior

The data source should cause a call to `api.ecr-public.us-east-1.amazonaws.com` as "ECR-public actions are only supported in the us-east-1 region"

### Actual Behavior

Data source triggers a lookup to a region-specific endpoint that does not actually exist, ie `api.ecr-public.us-east-2.amazonaws.com`

### Relevant Error/Panic Output Snippet

```shell
data.aws_ecrpublic_authorization_token.token: Still reading... [10s elapsed]
data.aws_ecrpublic_authorization_token.token: Still reading... [20s elapsed]
╷
│ Error: error getting Public ECR authorization token: RequestError: send request failed
│ caused by: Post "https://api.ecr-public.us-east-2.amazonaws.com/": dial tcp: lookup api.ecr-public.us-east-2.amazonaws.com on REDACTED:53: no such host
│ 
│   with data.aws_ecrpublic_authorization_token.token,
│   on main.tf line 54, in data "aws_ecrpublic_authorization_token" "token":
│   54: data "aws_ecrpublic_authorization_token" "token" {}
│ 
╵

# $ dig @8.8.8.8 api.ecr-public.us-east-2.amazonaws.com
# 
# ; <<>> DiG 9.11.36-RedHat-9.11.36-5.el8_7.2 <<>> @8.8.8.8 api.ecr-public.us-east-2.amazonaws.com
# ; (1 server found)
# ;; global options: +cmd
# ;; Got answer:
# ;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 19307
# ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
# 
# ;; OPT PSEUDOSECTION:
# ; EDNS: version: 0, flags:; udp: 512
# ;; QUESTION SECTION:
# ;api.ecr-public.us-east-2.amazonaws.com.	IN A
# 
# ;; AUTHORITY SECTION:
# us-east-2.amazonaws.com. 5	IN	SOA	dns-external-master.amazon.com. root.amazon.com. 2374 180 60 2592000 5
# 
# ;; Query time: 36 msec
# ;; SERVER: 8.8.8.8#53(8.8.8.8)
# ;; WHEN: Fri Dec 09 13:08:26 EST 2022
# ;; MSG SIZE  rcvd: 135
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 1.3"
  required_providers {
    aws       = {
      source  = "hashicorp/aws"
      version = "~> 4.46"
    }
  }
}

provider "aws" {
  region = "us-east-2"
}

data "aws_ecrpublic_authorization_token" "token" {}
```

### Steps to Reproduce

Configure the aws provider (by ~/.aws/config or explicitly in terraform) to use a region other than `us-east-1` and try to use the data source in any way.

### Debug Output

[debug.log](https://github.com/hashicorp/terraform-provider-aws/files/10197181/debug.log)

### References

Comment in a similar bug reported to aws-cli itself: https://github.com/aws/aws-cli/issues/5917#issuecomment-774317587

> Thanks for writing in! For right now, it appears ECR-public actions are only supported in the us-east-1 region. adding a `--region us-east-1` to the end of your commands (including batch-delete-image and delete-repository) should do the trick. I've linked the existing [documentation](https://docs.aws.amazon.com/AmazonECR/latest/public/getting-started-cli.html), but I'm going to look into this a bit further, because a few things seem unclear.

Documentation showing you *must* use `us-east-1` specifically for this: https://docs.aws.amazon.com/AmazonECR/latest/public/getting-started-cli.html#cli-authenticate-registry

> The Amazon ECR Public registry requires authentication in the `us-east-1` Region, so you need to specify `--region us-east-1` each time you authenticate. 

### Would you like to implement a fix?

None

**Comment by draeath** [comment]
Workaround tested:

```hcl
terraform {
  required_version = "~> 1.3"
  required_providers {
    aws       = {
      source  = "hashicorp/aws"
      version = "~> 4.46"
    }
  }
}

provider "aws" {
  region = "us-east-2"
}

provider "aws" {
  region = "us-east-1"
  alias = "virginia"
}

data "aws_ecrpublic_authorization_token" "token" {
  provider = aws.virginia
}
```

**Comment by claytonchew** [comment]
@draeath workaround works

but it's triggering replacement on the helm_release provider each time it is run, due to change of ecr public token, seem like there are some underlying issue with terraform aws provider itself.

**Comment by aliahmedmytoys** [comment]
hello everyone any news regarding this ticket?

**Comment by claytonchew** [comment]
terraform provider helm recently released v2.8.0 with added support for configuring OCI registries inside provider block.

Tested Solution:

> Note: You need to upgrade your helm provider to `v2.8.0`.

```hcl
terraform {
  # ...
  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.8.0"
    }
  }
  # ...
}
```

```hcl
provider "helm" {
  kubernetes {
    host                   = data.aws_eks_cluster.default.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.default.certificate_authority[0].data)
    token                  = data.aws_eks_cluster_auth.default.token
  }
  registry {
    url      = "oci://public.ecr.aws"
    username = data.aws_ecrpublic_authorization_token.token.user_name
    password = data.aws_ecrpublic_authorization_token.token.password
  }
}

# Temporary workaround due to AWS Public ECR only supporting us-east-1
# https://github.com/aws/karpenter/issues/3015#issuecomment-1344646211
provider "aws" {
  region = "us-east-1"
  alias  = "virginia"
}

data "aws_ecrpublic_authorization_token" "token" {
  provider = aws.virginia
}
```

```hcl
resource "helm_release" "karpenter" {
  namespace        = "karpenter"
  create_namespace = true

  name       = "karpenter"
  repository = "oci://public.ecr.aws/karpenter"
  chart      = "karpenter"
  version    = "v0.20.0"

  # ...
}
```

**Comment by aliahmedmytoys** [comment]
great but this work around wont work why AWS Public ECR only supporting us-east-1?

**Comment by draeath** [comment]
@aliahmedmytoys that's just the way AWS has it implemented - they only have the API endpoint in that region.

**Comment by Raboo** [comment]
I don't understand. So it's solved in a way that we no longer need to do this?

```hcl
provider "aws" {
  region = "us-east-1"
  alias = "virginia"
}

data "aws_ecrpublic_authorization_token" "token" {
  provider = aws.virginia
}
```

or that it's documented somewhere? If ECR Public is hardcoded to one region only, then the AWS provider should also hard code it IMO.
