### ISSUE TITLE
control of allowed_account_ids   using environement variable

### ISSUE THREAD

**Issue by KabRevel** [hashicorp/terraform-provider-aws#28280]
### Description

Hi , 
It is possible to fail the terraform build if the provided allowed_account_ids in the provider configuration  does not match a declared environement variable ?
In som way il want to have allowed_account_ids  required,  and during build if it is different from a  value of my env variable le build fails

### Would you like to implement a fix?

None

**Comment by JamesJJ** [comment]
Hello @KabRevel,
You can use a Terraform variable for the value of `allowed_account_ids` in your provider configuration. Terraform variables can be set using environment variables, as [described here](https://developer.hashicorp.com/terraform/cli/config/environment-variables#tf_var_name). 

Here is an example terraform config:
```
provider "aws" {
  allowed_account_ids = var.allowed_account_ids
}

variable "allowed_account_ids" {
  type    = list(string)
  default = ["0"]
}

output "allowed_account_ids" {
  value = var.allowed_account_ids
}

data "aws_region" "current" {
}

output "aws_region" {
  value = data.aws_region.current.name
}
```

With environment variable `TF_VAR_allowed_account_ids` unset, or set to a different account ID, commands will not succeed:
```
$ terraform apply
╷
│ Error: AWS account ID not allowed: 123456789123
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on main.tf line 1, in provider "aws":
│    1: provider "aws" {
│ 
╵
```

However if we set the environment variable `TF_VAR_allowed_account_ids` to the list of allowed account IDs, the commands will succeed. For example if the allowed account ID should be `123456789123`:
```
$ export TF_VAR_allowed_account_ids='[ "123456789123" ]'

$ terraform apply
data.aws_region.current: Reading...
data.aws_region.current: Read complete after 0s [id=us-west-2]

Changes to Outputs:
  + allowed_account_ids = [
      + "123456789123",
    ]
  + aws_region          = "us-west-2"

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 
```

**Comment by justinretzolk** [comment]
Given the excellent answer above, and the time since the last response here, closing.
