### ISSUE TITLE
[New Resource]: aws_lightsail_instance_public_ports.port_info should contain "cidrListAliases" too

### ISSUE THREAD

**Issue by suchanpark-koioi** [hashicorp/terraform-provider-aws#28285]
### Description

The documentation, for example [here](https://docs.aws.amazon.com/cli/latest/reference/lightsail/put-instance-public-ports.html), shows that we can write "cidrListAliases"

This can be used to set "port 22 should be only open to Lightsail Web RDP".

### Requested Resource(s) and/or Data Source(s)

* `aws_lightsail_instance_public_ports.port_info` should contain `cidr_list_aliases` too

### Potential Terraform Configuration

```terraform
resource "aws_lightsail_instance_public_ports" "main" {
  instance_name = aws_lightsail_instance.main.name

  port_info {
    protocol  = "tcp"
    from_port = 22
    to_port   = 22
    cidr_list_aliases = [
      "lightsail-connect"
    ]
  }
}
```

### References

https://docs.aws.amazon.com/cli/latest/reference/lightsail/put-instance-public-ports.html

### Would you like to implement a fix?

No

**Comment by bschaatsbergen** [comment]
@justinretzolk can we rename the title of the ticket to indicate that it's an enhancement

**Comment by bschaatsbergen** [comment]
API reference: https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_PortInfo.html#Lightsail-Type-PortInfo-cidrListAliases
