### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by petereitz** [hashicorp/terraform-provider-aws#28304]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_usage_plan_key

### Description

example code references `aws_api_gateway_deployment` instead of `aws_api_gateway_stage` in `api_stages`, below `aws_api_gateway_usage_plan`.  

see [here](https://stackoverflow.com/questions/72824688/terraform-unable-to-link-api-gateway-usage-plan-to-stage-api-stages-0-stage/72824794#72824794).

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
#29914 already fixed the doc, so this issue can be closed.
