### ISSUE TITLE
[Enhancement]:  Add basic auth to self-managed kafka on aws_lambda_event_source_mapping

### ISSUE THREAD

**Issue by 0xDjole** [hashicorp/terraform-provider-aws#28312]
### Description

[Here is the stackoverflow question I asked ](https://stackoverflow.com/questions/74710684/lambda-and-self-managed-kafka-authentication)

Currently self-managed kafka event source doesn't support BASIC_AUTH and it has to be connected to the VPC.

AWS GUI does support it, but that option is not available with terraform. It's kinda important in my opinion.

![2022-12-07_01-55](https://user-images.githubusercontent.com/36204260/207140918-1adaa056-86f2-4c16-81b9-546bf885c123.png)

### Affected Resource(s) and/or Data Source(s)

aws_lambda_event_source_mapping

### Would you like to implement a fix?

No

**Comment by DrFaust92** [comment]
Hi @0xDjole , `source_access_configuration` seems to support this via its `type` arg. it should support:
```
		SourceAccessTypeBasicAuth,
		SourceAccessTypeVpcSubnet,
		SourceAccessTypeVpcSecurityGroup,
		SourceAccessTypeSaslScram512Auth,
		SourceAccessTypeSaslScram256Auth,
		SourceAccessTypeVirtualHost,
		SourceAccessTypeClientCertificateTlsAuth,
		SourceAccessTypeServerRootCaCertificate,
```

**Comment by 0xDjole** [comment]
It works damn. We are good.
