### ISSUE TITLE
[Enhancement]: Add new resource_type of LAMBDA to aws_inspector2_enabler resource

### ISSUE THREAD

**Issue by pjroth** [hashicorp/terraform-provider-aws#28329]
### Description

AWS CLI/SDK added a new `resource_type` of `LAMBDA` which is not listed in the docs for the aws_inspector2_enabler resource.  

See [AWS Inspector V2 resource_types docs](https://docs.aws.amazon.com/inspector/v2/APIReference/API_Enable.html#inspector2-Enable-request-resourceTypes) which shows the already supported `ECR` and `EC2` resource types and the new `LAMBDA` type not yet supported by this terraform resource.

### Affected Resource(s) and/or Data Source(s)

* aws_inspector2_enabler

### Potential Terraform Configuration

```terraform
resource "aws_inspector2_enabler" "example" {
  account_ids    = ["012345678901"]
  resource_types = ["EC2", "LAMBDA", "ECR"]
}
```

### References

https://docs.aws.amazon.com/inspector/v2/APIReference/API_Enable.html#inspector2-Enable-request-resourceTypes

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @pjroth 👋 Thank you for taking the time to raise this! It looks like we're pulling the list of valid values from an enum, which has already been updated, so this should work as expected after the next release of the provider. I'll work on a documentation update so that the documentation is updated accordingly at that time.

**Comment by pjroth** [comment]
Thanks for the quick response @justinretzolk!  

I do see some enum usage but I also see code that looks to be hard coded to have only the existing types such as here:

https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/inspector2/enabler.go#L247

I'm not an expert in this code so I might be misunderstanding but it looks like to me like some of this code might need to be updated a little more than docs and version update?

**Comment by pjroth** [comment]
@justinretzolk was my analysis of the code incorrect and it was only a docs update required?
