### ISSUE TITLE
[Enhancement]: Use Correct API's for CloudWatch Logs Tagging

### ISSUE THREAD

**Issue by AMMullan** [hashicorp/terraform-provider-aws#28322]
### Description

We got notified by AWS that we were using now out of development API's and found that it was Terraform that was making these calls. 

This is the breakdown from AWS:

> We identified that you are using tagging APIs and recommend use the following new APIs that have “Resource” as the suffix, instead of “LogGroup”.
> 
> logs:TagResource
> logs:UntagResource
> logs:ListTagsForResource
> 
> The CloudWatch Logs team will not remove previous tagging APIs but the following APIs will no longer be actively developed:
> TagLogGroup
> UntagLogGroup
> ListTagsLogGroup

Presumably Terraform should be using the newer APIs so that it's following AWS best practices?

(NB: CloudFormation is also using these old APIs lol!)

### Affected Resource(s) and/or Data Source(s)

aws_cloudwatch_log_group

### Potential Terraform Configuration

```terraform
No Change
```

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_TagLogGroup.html:

<img width="975" alt="Screen Shot 2022-12-14 at 8 12 05 AM" src="https://user-images.githubusercontent.com/2404182/207604395-374bfcee-e994-4b72-a1aa-e4584341b1b7.png">
