### ISSUE TITLE
[Enhancement]: Add Host name argument in route53 health check when using ip_address

### ISSUE THREAD

**Issue by SmaugPool** [hashicorp/terraform-provider-aws#28337]
### Description

Add `hostname` argument to `aws_route53_health_check`.

This variable is optional and useful only when `ip_address` is used.

According to https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/health-checks-creating-values.html#health-checks-creating-values-host-name:

> Host name ("Specify endpoint by IP address" Only, HTTP and HTTPS Protocols Only)
> 
>     The value that you want Route 53 to pass in the Host header in HTTP and HTTPS health checks. 

### Affected Resource(s) and/or Data Source(s)

* aws_route53_health_check

### Potential Terraform Configuration

```terraform
resource "aws_route53_health_check" "example" {
  ip_address        = "1.2.3.4"
  hostname          = "example.com"
  port              = 80
  type              = "HTTP"
  resource_path     = "/"
  failure_threshold = "5"
  request_interval  = "30"

  tags = {
    Name = "tf-test-health-check"
  }
}
```

### References

https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/health-checks-creating-values.html#health-checks-creating-values-host-name

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @SmaugPool 👋 Thanks for taking the time to raise this! It looks like the argument you're looking for is [`fqdn`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_health_check#fqdn).

**Comment by SmaugPool** [comment]
> Hey @SmaugPool wave Thanks for taking the time to raise this! It looks like the argument you're looking for is [`fqdn`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_health_check#fqdn).

Hi @justinretzolk, I missed the fact that `fqdn` could also be used to fill the `Host` header in the HTTP requests when using an IP address. If this is the case then it's perfect and nothing more is needed, except maybe improving the documentation to make it more clear?

What misled me was the fact that AWS has 2 different properties: `Domain name` and `Host name` and I didn't expect them to be grouped under the same `fqdn` property:

https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/health-checks-creating-values.html#health-checks-creating-values-host-name

**Comment by justinretzolk** [comment]
Hey @SmaugPool 👋 I definitely get where you're coming from! I took a look into the document you sent as well as the Go SDK reference to see if there were any indications as far as the design decision to group `hostname` and `domain_name` into a single `fqdn` argument, and it turns out there is! Looking at the [AWS Go SDK reference][1], it mentions (I've cut out a _lot_ of information here, so may be worth looking at the actual document if you're interested in more detail):

```go
    // Amazon Route 53 behavior depends on whether you specify a value for IPAddress.
    //
    // If you specify a value for IPAddress:
    //
    // Amazon Route 53 sends health check requests to the specified IPv4 or IPv6
    // address and passes the value of FullyQualifiedDomainName in the Host header
    // for all health checks except TCP health checks. This is typically the fully
    // qualified DNS name of the endpoint on which you want Route 53 to perform
    // health checks.
    //
    // ... omitted for brevity ...
    //
    // If you don't specify a value for FullyQualifiedDomainName, Route 53 substitutes
    // the value of IPAddress in the Host header in each of the preceding cases.
    //
    // If you don't specify a value for IPAddress:
    //
    // Route 53 sends a DNS request to the domain that you specify for FullyQualifiedDomainName
    // at the interval that you specify for RequestInterval. Using an IPv4 address
    // that DNS returns, Route 53 then checks the health of the endpoint.
```

Would an update to the documentation that looks like the following make things a bit more clear from your perspective?

> `fqdn` - (Optional) The fully qualified domain name of the endpoint to be checked. If a value is set for `ip_address`, the value set for `fqdn` will be passed in the `Host` header.

[1]: https://docs.aws.amazon.com/sdk-for-go/api/service/route53/#HealthCheckConfig

**Comment by SmaugPool** [comment]
@justinretzolk I think the documentation update you propose would be perfect. 
The issue could then be closed from my point of view.
