### ISSUE TITLE
[Docs]: incorrect block type referenced for app runner ingress

### ISSUE THREAD

**Issue by h3r2on** [hashicorp/terraform-provider-aws#28360]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apprunner_service#ingress_configuration

### Description

the docs reference "The `encryption_configuration` block supports the following argument:"

but it should be the `ingress_configuration` 

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @h3r2on 👋 Thanks for taking the time to raise this! It looks like this was fixed with https://github.com/hashicorp/terraform-provider-aws/pull/28268, so we'll go ahead and close this issue out. If you feel we've done this in error, please do let us know.
