### ISSUE TITLE
[Enhancement]: aws_athena_workgroup support executionRole for PySpark engine

### ISSUE THREAD

**Issue by djleeam** [hashicorp/terraform-provider-aws#28386]
### Description

I'm trying to create a new `aws_athena_workgroup` resource running with the new `PySpark engine version 3`. When trying to create the workgroup, I get the following error:

```│ Error: error creating Athena WorkGroup: InvalidRequestException: executionRole is null or empty
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "fb9f14fa-2197-4b31-8bac-c147b082900c"
│   },
│   AthenaErrorCode: "INVALID_INPUT",
│   Message_: "executionRole is null or empty"
│ }
│
│   with aws_athena_workgroup.athena_spark_wg,
│   on athena.tf line 23, in resource "aws_athena_workgroup" "athena_spark_wg":
│   23: resource "aws_athena_workgroup" "athena_spark_wg" {
```
This appears to me that some of the new properties (at least execution role) that a Spark enabled Athena workgroup is dependent on has not yet been defined for the `aws_athena_workgroup` resource.

Is this enhancement already on the roadmap? If not, is there anything I can do to help move it along?

### Affected Resource(s) and/or Data Source(s)

* aws_athena_workgroup

### Potential Terraform Configuration

```terraform
resource "aws_athena_workgroup" "athena_spark_wg" {
  name        = local.athena_spark_wg_name
  description = "Analytics workgroup with PySpark engine v3"
  role        = aws_iam_role.athena_spark_execution_role.id

  configuration {
    enforce_workgroup_configuration    = false
    publish_cloudwatch_metrics_enabled = true

    engine_version {
      selected_engine_version = "PySpark engine version 3"
    }

    result_configuration {
      output_location = "s3://${aws_s3_bucket.my_bucket.bucket}/logs/athena_spark/"
    }
  }
}
```
```


### References

https://docs.aws.amazon.com/cli/latest/reference/athena/create-work-group.html

### Would you like to implement a fix?

None

**Comment by bschaatsbergen** [comment]
Hi @djleeam, thanks for raising this issue. I'll pick it up 👍 .

**Comment by bschaatsbergen** [comment]
Relevant API reference: https://docs.aws.amazon.com/athena/latest/APIReference/API_WorkGroupConfiguration.html#athena-Type-WorkGroupConfiguration-ExecutionRole

**Comment by djleeam** [comment]
Thanks @bschaatsbergen for picking this up! Let me know if I can help in anyway.

**Comment by bschaatsbergen** [comment]
@djleeam :)!
