### ISSUE TITLE
[Enhancement]: Support tags attribute in aws_appautoscaling_policy

### ISSUE THREAD

**Issue by RJKeane2000** [hashicorp/terraform-provider-aws#28391]
### Description

The aws_appautoscaling_policy resource creates CloudWatch metric alarms on our behalf. We're able to retrieve the arns of these alarms through the alarm_arns output attribute. CloudWatch metric alarms support tagging. 

Can you add the "tags" attribute to the aws_appautoscaling_policy resource so that it can pass the tags to the generated CloudWatch metric alarms? Currently I run script in our pipeline to retrieve the alarm arns and execute the AWS CLI to tag each alarm accordingly.

I've also tried setting default_tags on the AWS provider but they do not carry forward to the CloudWatch metric alarms created by the aws_appautoscaling_policy resource. 

**Note about tags from cloudwatch_metric_alarm documentation:**
[tags](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_metric_alarm#tags) - (Optional) A map of tags to assign to the resource. If configured with a provider [default_tags configuration block](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#default_tags-configuration-block) present, tags with matching keys will overwrite those defined at the provider-level.

### Affected Resource(s) and/or Data Source(s)

* aws_appautoscaling_policy

### Potential Terraform Configuration

```terraform
resource "aws_appautoscaling_policy" "ecs_policy" {
  name               = "scale-down"
  policy_type        = "StepScaling"
  resource_id        = aws_appautoscaling_target.ecs_target.resource_id
  scalable_dimension = aws_appautoscaling_target.ecs_target.scalable_dimension
  service_namespace  = aws_appautoscaling_target.ecs_target.service_namespace

  step_scaling_policy_configuration {
    adjustment_type         = "ChangeInCapacity"
    cooldown                = 60
    metric_aggregation_type = "Maximum"

    step_adjustment {
      metric_interval_upper_bound = 0
      scaling_adjustment          = -1
    }
  }

  tags = var.common_tags
}
```

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
> Application Auto Scaling now supports resource tagging

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2023/03/application-auto-scaling-resource-tagging/).
* [User guide](https://docs.aws.amazon.com/autoscaling/application/userguide/resource-tagging-support.html)

Requires [AWS SDK for Go v1.44.225](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.225): https://github.com/hashicorp/terraform-provider-aws/pull/30146.
