### ISSUE TITLE
[Enhancement]: Windows EKS managed node group

### ISSUE THREAD

**Issue by bryantbiggs** [hashicorp/terraform-provider-aws#28438]
### Description

Support for Windows based nodes on EKS Managed Node groups

Note: to support this, it just requires updating the aws-sdk version to at least [v1.44.161](https://github.com/aws/aws-sdk-go/commit/a9faefa96cb9bee57d55d9702b6e7de4aad69bc0) which contains the update for the [new AMI Types](https://github.com/aws/aws-sdk-go/commit/a9faefa96cb9bee57d55d9702b6e7de4aad69bc0#diff-82c4fbf044fbe6056f6770a826da919bf16d0d905a183f1e34a4d2bd24d04813R588-R591)

Ref:
```
Error: expected ami_type to be one of [AL2_x86_64 AL2_x86_64_GPU AL2_ARM_64 CUSTOM BOTTLEROCKET_ARM_64 BOTTLEROCKET_x86_64 BOTTLEROCKET_ARM_64_NVIDIA BOTTLEROCKET_x86_64_NVIDIA], got WINDOWS_CORE_2022_x86_64
```

### Affected Resource(s) and/or Data Source(s)

* aws_eks_node_group

### References

https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-eks-automated-provisioning-lifecycle-management-windows-containers/

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Requires [AWS SDK for Go v1.44.161](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.161): https://github.com/hashicorp/terraform-provider-aws/pull/28445.
