### ISSUE TITLE
Using terraform Plan is not fetching the result i want.

### ISSUE THREAD

**Issue by Solidator123** [hashicorp/terraform-provider-aws#28443]
### Description

after initializing terraform successfully. When i  write terraform plan i am getting the below error.

```shell
╷
│ Error: configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: b16fc6b2-becc-46e0-8c3b-37b58e5f4202, api error InvalidClientTokenId: The security token included in the request is invalid.
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on Provider.tf line 1, in provider "aws":
│    1: provider "aws" {
│
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @Solidator123 👋 Thank you for taking the time to raise this! It looks like the credentials that you're passing to the provider for authentication aren't being accepted. I'd recommend taking a look over the [authentication and configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#authentication-and-configuration) section of the provider documentation.

**Comment by justinretzolk** [comment]
Since we haven't heard back in a while, I'm going to close this issue out. If you're still having troubles, or have future issues with the AWS Provider, please feel free to open a new issue (referencing this one for context as needed).
