### ISSUE TITLE
[New Data Source]: OpenSearch Serverless Security Config

### ISSUE THREAD

**Issue by mattburgess** [hashicorp/terraform-provider-aws#28466]
### Description

Amazon OpenSearch Serverless is a preview service enabling OpenSearch clusters to be spun up without having to be concerned about the compute or storage requirements.

Security Configs let you use third-party identity providers, that use the SAML 2.0 standard, to sign in to OpenSearch Dashboards to index and search data.

### Requested Resource(s) and/or Data Source(s)

* `aws_opensearchserverless_security_config`

### Potential Terraform Configuration

```terraform
data "aws_opensearchserverless_security_config" "example" {
  id = "some ID"
}
```

### References

* https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearchserverless@v1.0.2

### Would you like to implement a fix?

None

**Comment by joshjluo** [comment]
@johnsonaj Have you started work on this issue already? I can also pick this up if you haven't started working on it.

**Comment by johnsonaj** [comment]
@joshjluo I have no started this. All yours
