### ISSUE TITLE
[New Data Source]: OpenSearch Serverless VPC Endpoint

### ISSUE THREAD

**Issue by mattburgess** [hashicorp/terraform-provider-aws#28468]
### Description

Amazon OpenSearch Serverless is a preview service enabling OpenSearch clusters to be spun up without having to be concerned about the compute or storage requirements.

VPC Endpoints create a private connection between your VPC and OpenSearch Serverless. You can access your collections as if they were in your VPC without the use of an internet gateway, NAT device, VPN connection, or AWS Direct Connect connection.

### Requested Resource(s) and/or Data Source(s)

* `aws_opensearchserverless_vpc_endpoint`

### Potential Terraform Configuration

```terraform
data "aws_opensearchserverless_vpc_endpoint" "example" {
  id = "some id"
}
```

### References

* https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearchserverless@v1.0.2

### Would you like to implement a fix?

None

**Comment by johnsonaj** [comment]
> @johnsonaj I see that you have started some of the other OpenSearch Serverless data sources. I'm interested in picking this up if you or anyone else is not already close to completion.

@joshjluo not currently working on this one. It's all yours!
