### ISSUE TITLE
[New Resource]: OpenSearch Serverless VPC Endpoint

### ISSUE THREAD

**Issue by mattburgess** [hashicorp/terraform-provider-aws#28467]
### Description

Amazon OpenSearch Serverless is a preview service enabling OpenSearch clusters to be spun up without having to be concerned about the compute or storage requirements.

VPC Endpoints create a private connection between your VPC and OpenSearch Serverless. You can access your collections as if they were in your VPC without the use of an internet gateway, NAT device, VPN connection, or AWS Direct Connect connection.

### Requested Resource(s) and/or Data Source(s)

* `aws_opensearchserverless_vpc_endpoint`

### Potential Terraform Configuration

```terraform
resource "aws_opensearchserverless_vpc_endpoint" "example" {
  name               = "example"
  subnet_ids         = [ aws_subnet.private.id ]
  vpc_id             = aws_vpc.example.id
  security_group_ids = [ aws_security_group.example.id ]
}
```

### References

* https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearchserverless@v1.0.2

### Would you like to implement a fix?

None

**Comment by aka-somix** [comment]
I know this may not be the right place to ask, but is there a resource to create an Opensearch managed VPC Endpoint for not serverless OpenSearch clusters?

I cannot find anything but this Issue and it does not seem to be documented if it exists.
May be the case of creating a new resource request for that too?

**Comment by mattburgess** [comment]
@aka-somix I think you're after this: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/vpc-interface-endpoints.html

The OpenSearch service (non-serverless) can be accessed using a VPC Interface Endpoint. These can be created using the [aws_vpc_endpoint](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint#interface-endpoint-type) resource in Terraform.

**Comment by jinfanzon** [comment]
+1 this new "feature"
