### ISSUE TITLE
[New Data Source]: OpenSearch Serverless Collection

### ISSUE THREAD

**Issue by mattburgess** [hashicorp/terraform-provider-aws#28463]
### Description

Amazon OpenSearch Serverless is a preview service enabling OpenSearch clusters to be spun up without having to be concerned about the compute or storage requirements.

Collections are used to manage a group of indices that work together to support a given workload.

### Requested Resource(s) and/or Data Source(s)

* `aws_opensearchserverless_collection`

### Potential Terraform Configuration

```terraform
data "aws_opensearchserverless_collection" "example" {
  name        = "example"
}
```

### References

* https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearchserverless@v1.0.2

### Would you like to implement a fix?

None

**Comment by tkawachi** [comment]
OpenSearch Serverless is now generally available!

https://aws.amazon.com/jp/about-aws/whats-new/2023/01/amazon-opensearch-serverless-available/
