### ISSUE TITLE
[Enhancement]: aws_networkfirewall_rule_group Reference Sets to be limited to 5

### ISSUE THREAD

**Issue by meetreks** [hashicorp/terraform-provider-aws#28464]
### Description

Currently aws_networkfirewall_rule_group allows IP Reference Sets to be created. The current implementation does not limit the no of reference sets at Plan time, but at runtime the API limits the # to 5. This issue is raised to cater for limiting the Reference set creation to 5 to match the API experience. 

### Affected Resource(s) and/or Data Source(s)

* aws_networkfirewall_rule_group

### Potential Terraform Configuration

```terraform
resource "aws_networkfirewall_rule_group" "test" {
  capacity = 100
  name     = "Test"
  type     = "STATEFUL"
  rule_group {
    reference_sets {
      ip_set_references {
        key = "example11"
        ip_set_reference {
          reference_arn = aws_ec2_managed_prefix_list.example1.arn
        }
      }
      ip_set_references {
        key = "example21"
        ip_set_reference {
          reference_arn = aws_ec2_managed_prefix_list.example2.arn
        }
      }
      ip_set_references {
        key = "example31"
        ip_set_reference {
          reference_arn = aws_ec2_managed_prefix_list.example3.arn
        }
      }
    }
    rules_source {
      rules_source_list {
        generated_rules_type = "ALLOWLIST"
        target_types         = ["HTTP_HOST"]
        targets              = ["test.example.com"]
      }
    }
  }
}
```

### References

https://docs.aws.amazon.com/network-firewall/latest/developerguide/rule-groups-ip-set-references.html#rule-groups-ip-set-reference-limits

### Would you like to implement a fix?

None

**Comment by noelukwa** [comment]
I would like to give this a shot @AdamTylerLynch

**Comment by kEDIT** [comment]
@AdamTylerLynch is there anything to do here besides just adjust the list capacity to `5` here? https://github.com/hashicorp/terraform-provider-aws/blob/1076f598ee88175e7409c5887edcf87e6cbeab20/internal/service/networkfirewall/rule_group.go#L65

I'd be happy to submit a PR if so.
