### ISSUE TITLE
[New Resource]: OpenSearch Serverless Collection

### ISSUE THREAD

**Issue by mattburgess** [hashicorp/terraform-provider-aws#28462]
### Description

Amazon OpenSearch Serverless is a preview service enabling OpenSearch clusters to be spun up without having to be concerned about the compute or storage requirements.

Collections are used to manage a group of indices that work together to support a given workload.

### Requested Resource(s) and/or Data Source(s)

* `aws_opensearchserverless_collection`

### Potential Terraform Configuration

```terraform
resource "aws_opensearchserverless_collection" "example" {
  name        = "example"
  type        = "timeseries"
  description = "example"
}
```

### References

* https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearchserverless@v1.0.2

### Would you like to implement a fix?

Yes

**Comment by iiro** [comment]
This just went GA: https://aws.amazon.com/about-aws/whats-new/2023/01/amazon-opensearch-serverless-available/

**Comment by omerf-hmcts** [comment]
@mattburgess it states all opensearch serverless resources are in 4.48.0 but this is never released and there is no documentation about resources too.  Can you clarify if this feaute released or not?

**Comment by mattburgess** [comment]
@omerf-hmcts unfortunately that's a slight misunderstanding of the release note. That change implemented the basic scaffolding/support code to enable the Terraform AWS provider to use the OpenSearch Serverless APIs. The actual implementation of resources is being tracked under the following PRs:

* #28470
* #28518
* #28651
* #28776

Support for `aws_opensearch_serverless_collections` is dependent on the security_policy and access_policy resources so that PR can't be raised until the other 2 are merged.

**Comment by abiodunakande** [comment]
Any update on timelines relating to these resources?

**Comment by jiro-farah-cko** [comment]
Any chance the opensearch serverless resources going to be released soon?

**Comment by JBartlett86** [comment]
Is there any update on possible timelines for this?

**Comment by mattburgess** [comment]
@JBartlett86 - not much of an update, unfortunately. The hashicorp folks are really busy gearing up for the 5.0 release. The Opensearch Serverless PRs are very much still on their radar though, so I'm hoping once that work is wrapped up these can all be picked up.

**Comment by ryanflomenco** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/28313 suggests this work is complete? Is that true? I don't see any references to it being supported yet.
