### ISSUE TITLE
[Enhancement]: AuthenticationMode for ElastiCache User

### ISSUE THREAD

**Issue by darkwizard242** [hashicorp/terraform-provider-aws#28471]
### Description

AWS ElastiCache now provides the capability for IAM based authentication. An ElastiCache user can be created with `AuthenticationMode` type set to `iam`.

This may require a new attribute (something like `authentication_mode` in the `aws_elasticache_user` resource).

### Affected Resource(s) and/or Data Source(s)

**aws_elasticache_user**

### Potential Terraform Configuration

```terraform
resource "aws_elasticache_user" "test" {
  user_id             = "testUserId"
  user_name           = "testUserName"
  access_string       = "on ~app::* -@all +@read +@hash +@bitmap +@geo -setbit -bitfield -hset -hsetnx -hmset -hincrby -hincrbyfloat -hdel -bitop -geoadd -georadius -georadiusbymember"
  authentication_mode = "iam"
  engine              = "REDIS"
  passwords           = ["password123456789"]
}
```

### References

**Announcement**:
https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-elasticache-supports-iam-authentication-redis-clusters/

**Docs**:
https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/auth-iam.html
https://aws.amazon.com/blogs/database/simplify-managing-access-to-amazon-elasticache-for-redis-clusters-with-iam/

**API reference**:
https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateUser.html
https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_AuthenticationMode.html

### Would you like to implement a fix?

No

**Comment by Wobbley** [comment]
Related to: https://github.com/hashicorp/terraform-provider-aws/issues/28471 ?
