### ISSUE TITLE
[Enhancement]: Add support for credentials SecretArn attribute in quicksight_data_source 

### ISSUE THREAD

**Issue by grzegorzb1990** [hashicorp/terraform-provider-aws#28484]
### Description

According to the [AWS API documentation](https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateDataSource.html), it is possible to create a new data source, using credentials stored in Secret Manager . This way I would not have to store credentials in plain text in the terraform state.
![image](https://user-images.githubusercontent.com/19983241/208633360-151febfd-f43d-4a3b-bb2f-9954f0c05580.png)

### Affected Resource(s) and/or Data Source(s)

quicksight_data_source

### Potential Terraform Configuration

```terraform
resource "aws_quicksight_data_source" "snowflake" {
  data_source_id = "snowflake"
  name           = "SNOWFLAKE"

  type = "SNOWFLAKE"

  parameters {
    snowflake {
      database  = "SNOWFLAKE"
      host      = "snowflakecomputing.com"
      warehouse = "SNOWFLAKE_WH"
    }
  }

  credentials {
    secret_arn = "arn:aws:secretsmanager:us-west-2:123456789012:secret:my-path/my-secret-name-1a2b3c"
  }
}
```

### References

https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateDataSource.html
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DataSourceCredentials.html#QS-Type-DataSourceCredentials-SecretArn

### Would you like to implement a fix?

No

**Comment by alfredgamulo** [comment]
There's a PR for this. Can it be reviewed, please?

**Comment by shahriteshj** [comment]
@justinretzolk : Who can help review this PR or is there anything pending because of which PR is not being reviewed?
