### ISSUE TITLE
[Enhancement]: Allow use of S3 Multi region AP for state storage

### ISSUE THREAD

**Issue by jamesmudd** [hashicorp/terraform-provider-aws#28490]
### Description

In order to make sure the TF state is redundantly available in 2 or more regions it would be nice to be able to use a [S3 multi region access point](https://docs.aws.amazon.com/AmazonS3/latest/userguide/MultiRegionAccessPoints.html) (MRAP) as the S3 state store, with the buckets backing the MRAP setup with replication. It can automatically handle fail over and routing to the closest bucket (which would improve state access performance for global teams). Currently if you try to use a MRAP in place of the bucket S3 provider parameter you receive the following error
```
Error refreshing state: InvalidARNError: invalid ARN
caused by: invalid Amazon s3 ARN, region not set, arn:aws:s3::1234567890:accesspoint/abc123abc123.mrap
```
Its correct that there is no region that's the point of MRAPs

There is a chance of accessing inconsistent state if a TF job ends and another begins routed to a different backing bucket before replication completes, however this would be mitigated by using state locking with a [DynamoDB global table](https://aws.amazon.com/dynamodb/global-tables/) (technically eventually consistent but very fast)

### Affected Resource(s) and/or Data Source(s)

s3 backend

### Potential Terraform Configuration

```terraform
terraform {
  backend "s3" {
    accessPoint = "arn:aws:s3::1234567890:accesspoint/abc123abc123.mrap"
    key    = "path/to/my/key"
  }
}
```

### References

A very similar issue is here #22494 where the same error is received

### Would you like to implement a fix?

No

**Comment by jamesmudd** [comment]
Relates to https://github.com/hashicorp/terraform/issues/32190 and https://github.com/hashicorp/terraform/issues/32080

**Comment by gdavison** [comment]
Thanks for submitting this, @jamesmudd. The `s3` backend is maintained as part of the [hashicorp/terraform](https://github.com/hashicorp/terraform) repo, so the two issues that you linked above cover this request.
