### ISSUE TITLE
[Enhancement]: ECS Service deployment alarms

### ISSUE THREAD

**Issue by mkielar** [hashicorp/terraform-provider-aws#28511]
### Description

Implement the possibility to configure Deployment Alarms in ECS Service.

AWS just released a feature in ECS allowing to configure custom CloudWatch Alarms, that the ECS Service Deployment will observe, and roll back the deployment if any of the alarm goes into an ALARM state.

### Affected Resource(s) and/or Data Source(s)

* `aws_ecs_service`

### Potential Terraform Configuration

```terraform
resource "aws_ecs_service" "example" {
  name    = "example"
  cluster = aws_ecs_cluster.example.id

  deployment_controller {
    # Note! ECS is currently the only supported controller for `deployment_alarms`. 
    # Pretty sure AWS will validate it, though.
    type = "ECS" 
  }

  # Potential new configuration
  deployment_alarms {
    enabled     = true
    rollback    = true
    alarm_names = [
      "my_custom_alarm_1",
      "my_custom_alarm_2",
    ] 
  }
}
```

### References

1. Announcement:  
  https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-ecs-cloudwatch-alarms-safety-deployments/
2. API:  
  https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DeploymentAlarms.html

### Would you like to implement a fix?

No

**Comment by bschaatsbergen** [comment]
I'll pick this up :+1:
