### ISSUE TITLE
[Enhancement]: Add cis-aws-foundations-benchmark v1.4.0 under resource aws_securityhub_standards_subscription

### ISSUE THREAD

**Issue by nokiomanz** [hashicorp/terraform-provider-aws#28522]
### Description

The cis-aws-foundations-benchmark/v/1.4.0 has been available for over a year. But the resource aws_securityhub_standards_subscription does not support it's available ARN. 

See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_standards_subscription

Could it be possible to add the ARN to that element which is 
arn:aws:securityhub:::standards/cis-aws-foundations-benchmark/v/1.4.0

### Affected Resource(s) and/or Data Source(s)

aws_securityhub_standards_subscription

### Potential Terraform Configuration

```terraform
resource "aws_securityhub_standards_subscription" "cis_v1_4_0" {
   standards_arn = "arn:aws:securityhub:::standards/cis-aws-foundations-benchmark/v/1.4.0"
 }
```

### References

How to enable it through the ARN
https://github.com/awslabs/aws-securityhub-multiaccount-scripts/tree/master/cis14-enable

Information about it
https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls-1.4.0.html

Difference with 1.2
https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-cis1.4-vs-cis1.2.html

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
The ARN for CIS AWS Foundations Benchmark v1.4.0 includes the region unlike that of v1.2.0. You could use the following:

`arn:aws:securityhub:${local.region}::ruleset/cis-aws-foundations-benchmark/v/1.4.0`

Where `local.region` is a local value derived from the `aws_region` data source (e.g. `data.aws_region.this.name`).

**Comment by nokiomanz** [comment]
Ho, interesting. I just tested it and indeed with a region it work. I missed that part. Super sorry for that.

Could it be usefull though to add it into the resource documentation here: 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_standards_subscription
