### ISSUE TITLE
[Bug]: aws_sagemaker_app drops existing resources from state on refresh

### ISSUE THREAD

**Issue by JohnPaton** [hashicorp/terraform-provider-aws#28535]
### Terraform Core Version

1.2.8, 1.3.6

### AWS Provider Version

4.48.0

### Affected Resource(s)

* `aws_sagemaker_app` (when more than 10 are present in the configuration)

### Expected Behavior

After applying the configuration for more than 10 `aws_sagemaker_app`s, the resources should be created and then tracked in the terraform state. Subsequent `plan`s should not plan any changes if there have been no changes to the configuration.

### Actual Behavior

Upon the state refresh that happens before the terraform plan is created, some of of the `aws_sagemaker_app` resources will be removed from the state. This only happens when there are more than 10 Apps. In that case, **the resources that remain in the state are the first 10 from the [SageMaker ListApps](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_ListApps.html) API call**, and apps that appear further down the list of apps will be removed. 

This means that terraform will plan to create the resources again, and the `apply` will fail, because the resources actually already exist.

Since 10 is the default `MaxResults` for SageMaker ListApps, my hypothesis is that the provider is not properly handling the pagination of the ListApps call, and the resources for Apps on subsequent pages are being removed on refresh.

### Relevant Error/Panic Output Snippet

```shell
│ Error: creating SageMaker App: ResourceInUse: App [arn:aws:sagemaker:eu-central-1:123456789012:app/d-sej4gjc7ahs5/jpaton/jupyterserver/default] is currently in [InService] status. To restart the App, wait until it is in Deleted or Failed status.
│ 
│   with module.main.aws_sagemaker_app.jupyter_server["jpaton"],
│   on ../modules/main/sagemaker.tf line 34, in resource "aws_sagemaker_app" "jupyter_server":
│   34: resource "aws_sagemaker_app" "jupyter_server" {
```

### Terraform Configuration Files

```hcl
resource "aws_sagemaker_domain" "example" {
  domain_name = "example"
  auth_mode   = "IAM"
  vpc_id      = aws_vpc.main.id
  subnet_ids  = [aws_subnet.main.id]

  default_user_settings {
    execution_role = aws_iam_role.example.arn
  }
}

### UserProfiles with matching JupyterServers
resource "aws_sagemaker_user_profile" "user_profile" {
  count = 12

  domain_id         = aws_sagemaker_domain.example.id
  user_profile_name = "user_profile_${count.index}"
}

resource "aws_sagemaker_app" "jupyter_server" {
  count = 12  # Issue only appears if this is >10

  app_name          = "default"
  app_type          = "JupyterServer"
  domain_id         = aws_sagemaker_domain.example.id
  user_profile_name = aws_sagemaker_user_profile.user_profile[count.index].user_profile_name
}
```

<details>
<summary>Other config required for domain creation</summary>

```hcl
resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_subnet" "main" {
  vpc_id     = aws_vpc.main.id
  cidr_block = "10.0.1.0/24"
}

resource "aws_iam_role" "example" {
  name               = "example"
  path               = "/"
  assume_role_policy = data.aws_iam_policy_document.example.json
}

data "aws_iam_policy_document" "example" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["sagemaker.amazonaws.com"]
    }
  }
}
```
</details>

### Steps to Reproduce

1. `terraform apply` - should **succeed**, 12 JupyterServer Apps created
2. `terraform state show aws_sagemaker_app.jupyter_server[0]` - should show the state of the app
3. `terraform plan`  - refresh will be triggered, some apps will be lost from the state, plan will show some (probably 2) Apps to be created even though we just created them in step 1
4. `terraform apply` - will **fail** with `ResourceInUse: App [...] is currently in [InService] status. To restart the App, wait until it is in Deleted or Failed status.`
5. `terraform state show aws_sagemaker_app.jupyter_server[x]` (where `x` is the number of one of the Apps terraform tried to recreate) - Will complain `No instance found for the given address!`. The state has been lost during the refresh. 

### Important Factoids

- As mentioned, this issue should only affect users who are creating more than 10 (11 or more) `aws_sagemaker_apps`
- I've only tested this with `JupyterServer` Apps, one per matching UserProfile

### References

- [SageMaker ListApps](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_ListApps.html) API reference documenting `MaxResults` and `NextToken`. It doesn't document the default value of `MaxResults`, but you can easily verify that it's 10 by creating more than 10 Apps in an account and listing them
- The [`listAppsByName`](https://github.com/hashicorp/terraform-provider-aws/blob/v4.48.0/internal/service/sagemaker/find.go#L276L294) function in `internal/service/sagemaker/find.go` where I believe pagination should be handled (I could be wrong about this but it's a starting point)
- [Some other function](https://github.com/hashicorp/terraform-provider-aws/blob/v4.48.0/internal/service/directconnect/gateway_data_source.go#L41L55) in the codebase that _is_ handling pagination with `NextToken`
- This looks similar to #26863, which is reporting losing missing data if there are more than 100 relevant resources due to suspected pagination issues

### Would you like to implement a fix?

None

**Comment by JohnPaton** [comment]
This issue only pertains to `service/sagemaker`, but I guess the bot labelled it with `iam` and `vpc` because of my example config - those can be removed

**Comment by DrFaust92** [comment]
ill take a llok

**Comment by DrFaust92** [comment]
almost sure https://github.com/hashicorp/terraform-provider-aws/issues/28548 and this come from same issue, opening PR

**Comment by JohnPaton** [comment]
FYI if anyone else is stuck with this we are currently working around it by using [`awscc_sagemaker_app`](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/sagemaker_app) instead.

**Comment by benriou** [comment]
Hello, we are also impacted by this issue. 

Additionally to this case, the AWS Provider considers that it fails to create an aws_sagemaker_app with the following message : 

`│ Error: waiting for SageMaker App (arn:aws:sagemaker:eu-central-1:XXXXXXX:app/d-s9j4jfkieqvo/YYYYYYYYYY/jupyterserver/default) to create: couldn't find resource (21 retries)`

It just timeout after 2 minutes 30 seconds...  Despite the fact that the application is correctly created at AWS but with a longer delay required.
