### ISSUE TITLE
[Enhancement]: Support for ElastiCache NetworkType

### ISSUE THREAD

**Issue by ngoyal16** [hashicorp/terraform-provider-aws#28558]
### Description

Should be able to deploy ElastiCache cluster in diffrent types on Network like IPv6, Dualstack, IPv6

### Affected Resource(s) and/or Data Source(s)

`aws_elasticache_replication_group`

### Potential Terraform Configuration

```terraform
allow to launch redis cluster in differnt Networks i.e. ipv4, ipv6 or dualstack
```

### References

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-replicationgroup.html#cfn-elasticache-replicationgroup-networktype

Relates https://github.com/hashicorp/terraform-provider-aws/issues/27700.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/27856.

### Would you like to implement a fix?

None

**Comment by ngoyal16** [comment]
https://github.com/hashicorp/terraform-provider-aws/pull/28306

**Comment by ewbankkit** [comment]
@ngoyal16 Thanks for raising this issue.
It has already been noticed in #28131. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
