### ISSUE TITLE
[Bug]: terraform keep trying to create spot_fleet_request whenever target_capacity changed

### ISSUE THREAD

**Issue by ppshein** [hashicorp/terraform-provider-aws#28555]
### Terraform Core Version

1.3.6

### AWS Provider Version

4.48.0

### Affected Resource(s)

aws_spot_fleet_request

### Expected Behavior

spot_fleet_request should be modified instead of deleting old request and creating a new one.

### Actual Behavior

I was trying to update `target_capacity` and apply afterwards, I found that terraform tried to delete old spot_fleet_request and create new the request again everytime.

### Terraform Configuration Files

```terraform
resource "aws_spot_fleet_request" "azdevops_agent" {
  iam_fleet_role                      = aws_iam_role.ec2_fleet_role[count.index].arn
  spot_price                          = var.spot_price
  allocation_strategy                 = "diversified"
  fleet_type                          = "request"
  instance_interruption_behaviour     = var.instance_interruption_behaviour
  target_capacity                     = var.spot_fleet_instance_capacity
  valid_until                         = timeadd(timestamp(), var.request_valid_until_minutes)
  terminate_instances_with_expiration = true
  terminate_instances_on_delete       = true
  dynamic "launch_specification" {
    for_each = var.instance_type
    content {
      instance_type            = launch_specification.value
      ami                      = data.aws_ami.this.image_id
      iam_instance_profile_arn = aws_iam_instance_profile.agent_profile[count.index].arn
      subnet_id                = module.vpc_data.subnet_ids[0]
      vpc_security_group_ids   = [aws_security_group.ec2-spot-fleet-sg.id]

      root_block_device {
        encrypted             = true
        kms_key_id            = aws_kms_key.kms_key[count.index].arn
        volume_size           = var.volume_size
        delete_on_termination = true
      }
    }
  }
  tags = {
    Name        = "devops-spot-fleet-agents"
  }
}
```

### Steps to Reproduce

terraform plan and apply

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
hey @ppshein 👋 Thank you for taking the time to raise this! It doesn't look like the `target_capacity` is marked as `ForceNew`, so that behavior definitely seems a bit odd. So that we can take a look into it, can you supply debug logs (redacted as needed) as well?

**Comment by ppshein** [comment]
> hey @ppshein 👋 Thank you for taking the time to raise this! It doesn't look like the `target_capacity` is marked as `ForceNew`, so that behavior definitely seems a bit odd. So that we can take a look into it, can you supply debug logs (redacted as needed) as well?

Hi,
My bad. That issue has been resolved when I added `lifecycle` attribute and add `target_capaticy` as its value.
