### ISSUE TITLE
[Enhancement]: aws_autoscaling_policy Change resource_label required to optional

### ISSUE THREAD

**Issue by tothanhtung0205** [hashicorp/terraform-provider-aws#28597]
### Description

In aws_autoscaling_policy -> predictive_scaling_configuration -> metric_specification
predefined_load_metric_specification/predefined_metric_pair_specification/predefined_scaling_metric_specification
resource_label is required but it is required only when predefined_metric_type = "ALBTargetGroupRequestCount", so it should be optional. When predefined_metric_type is not equal "ALBTargetGroupRequestCount", we expect to config without resource_label.
In AWS document, it is also no required attribute.

### Affected Resource(s) and/or Data Source(s)

* aws_autoscaling_policy

### Potential Terraform Configuration

```terraform
resource "aws_autoscaling_policy" "example" {
  autoscaling_group_name = "my-test-asg"
  name                   = "foo"
  policy_type            = "PredictiveScaling"
  predictive_scaling_configuration {
    metric_specification {
      target_value = 10
      predefined_load_metric_specification {
        predefined_metric_type = "ASGTotalCPUUtilization"
        # resource_label       = "testLabel" This required only when predefined_metric_type = "ALBTargetGroupRequestCount"
      }
    }
  }
}
```

### References

https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-autoscaling-scalingpolicy-predictivescalingpredefinedmetricpair.html

### Would you like to implement a fix?

None

**Comment by tmccombs** [comment]
This seems more like a bug than an enhancement.
