### ISSUE TITLE
Not able to create aws budget alert using historical auto adjust data

### ISSUE THREAD

**Issue by pradeepjestha4** [hashicorp/terraform-provider-aws#28592]
### Description

I am trying to create auto_adjust_data alert, but i am getting an error asking for budget amout.

### Would you like to implement a fix?

None

**Comment by brittandeyoung** [comment]
@pradeepjestha4 would you be able to provide the configuration you are using along with the error message you are receiving?

**Comment by justinretzolk** [comment]
Since we haven't heard back in quite some time, I'm going to close this issue out. If you're still having troubles or have future issues with the AWS Provider, please feel free to open a new issue, referencing this one for context as needed.
