### ISSUE TITLE
[Bug]: aws_secretsmanager_secret saves bad resource policy into state

### ISSUE THREAD

**Issue by jooh-lee** [hashicorp/terraform-provider-aws#28609]
### Terraform Core Version

1.3.4

### AWS Provider Version

4.48.0

### Affected Resource(s)

aws_secretsmanager_secret

### Expected Behavior

When the apply fails with `MalformedPolicyDocumentException: This resource policy contains a syntax error`, the state should not be saved

### Actual Behavior

The state is saved even after `MalformedPolicyDocumentException: This resource policy contains a syntax error`

### Relevant Error/Panic Output Snippet

```shell
encountered: parsing policy 1: parsing statement 1: 1 error(s) decoding:

* '[3]' expected a map, got 'slice'
```

### Terraform Configuration Files

``` hcl
locals {
  policy = {
    Version = "2012-10-17"
    Statement = concat([
        {
          Effect = "Allow"
          Action = [
            "secretsmanager:Delete*",
            "secretsmanager:PutResourcePolicy",
            "secretsmanager:ReplicateSecretToRegions",
            "secretsmanager:RemoveRegionsFromReplication",
            "secretsmanager:StopReplicationToReplica",
            "secretsmanager:TagResource",
            "secretsmanager:UntagResource",
          ]
          Principal = "arn:aws:iam::<AWS_ACCOUNT_ID>:root"
          Resource  = "*"
          }
        },
        {
          Effect = "Allow"
          Action = [
            "secretsmanager:DescribeSecret",
            "secretsmanager:GetResourcePolicy",
            "secretsmanager:RestoreSecret"
          ]
          Principal = {
            AWS = "arn:aws:iam::<AWS_ACCOUNT_ID>:root"
          }
          Resource = "*"
        },
        [
          {
            Effect = "Allow"
            Action = "secretsmanager:GetSecretValue"
            Principal = {
              AWS = "arn:aws:iam::<AWS_ACCOUNT_ID>:root"
            }
            Resource = "*"
          }
        ]
    ])
  }
}

resource "aws_secretsmanager_secret" "secret" {
  name        = "foo"
  description = "bar"
  policy      = jsonencode(local.policy)
}
```

### Steps to Reproduce

1. replace `<AWS_ACCOUNT_ID>` with an actual account id
2. run the code to create the secret
3. you may need to first create a valid secret then apply a wonky resource policy to it

Please note that the example config file is a stripped down and modified version of the actual policy and so the `relevent error` may not look exactly like what you see there.

### Debug Output

none

### Panic Output

none

### References

https://github.com/hashicorp/terraform-provider-aws/issues/22895

That closed issue i think is very closely related to this

### Would you like to implement a fix?

None

**Comment by clalexander** [comment]
I encountered the same issue, which hard-locked my state, except my affected resource was `aws_iam_policy`. My solution was to edit the state file manually and remove the malformed syntax.

- Terraform v1.5.6
- Hashicorp AWS Provider v5.42.0
