### ISSUE TITLE
[Docs]:  appstream_image_builder documentation outdated

### ISSUE THREAD

**Issue by wesleygroen** [hashicorp/terraform-provider-aws#28601]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appstream_image_builder

### Description

the image used in the example: AppStream-WinServer2012R2-07-19-2021 is deprecated and doesn't work anymore

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @wesleygroen 👋 Thank you for taking the time to raise this! I've opened a PR to update the `image_name` to a more modern version.
