### ISSUE TITLE
[New Resource][New Data Source]: AWS Identity Store Application Resource and Data Source

### ISSUE THREAD

**Issue by kamalika-majumder** [hashicorp/terraform-provider-aws#28615]
### Description

Hello,
I would like to request new resource and data source for AWS Identity Store Application for creating custom saml 2.0 apps, configure attributes and also to download the saml metadata. Currently the resources and data sources are available only for users, group and group membership. This make it completely manual process to create application for use in federated authentication like VPN Client(https://aws.amazon.com/blogs/security/authenticate-aws-client-vpn-users-with-aws-single-sign-on/) which is very necessary. 
Please help with this so that the completed function can be automate via IaC. 

### Requested Resource(s) and/or Data Source(s)

aws_identitystore_application

### Potential Terraform Configuration

```terraform
resource "aws_identitystore_application" "custom" {
  display_name      = "Example app"
  description       = "Example description"
  add a custom SAML 2.0 application = true
  application metadata {
     Application ACS URL = "http://127.0.0.1:35001"
     Application SAML audience = "urn:amazon:webservices:clientvpn"
}
 attribute mappings {
    attribute_path = 	"Subject"
    attribute_value = "	${user:email}"
}

data "aws_ssoadmin_instances" "example" {}

data "aws_identitystore_application" "example" {
  identity_store_id = tolist(data.aws_ssoadmin_instances.example.identity_store_ids)[0]
  saml_metadata = "xml file"
  alternate_identifier {
    unique_attribute {
      attribute_path  = "DisplayName"
      attribute_value = "ExampleGroup"
    }
  }
}

output "group_id" {
  value = data.aws_identitystore_group.example.application_id
}
```

### References

https://docs.aws.amazon.com/singlesignon/latest/userguide/samlapps.html

### Would you like to implement a fix?

None

**Comment by mtavaresmedeiros** [comment]
+1

**Comment by andy-smith-tracebit** [comment]
This would be very useful but as far as I can tell AWS do not provide any API to do this.

Main reference I have is this post on the AWS forums: https://repost.aws/questions/QUwi98GR4RSsCvS6LIeK3dBQ/apis-for-creating-custom-saml-2-0-application-in-identity-center

**Comment by benjefferies** [comment]
Thanks for raising this @kamalika-majumder. It looks like your use case is exactly the same as mine for client VPN. Do you have any good workaround for this?

Is this something that will be introduced and are other any timescales on this?

**Comment by kamalika-majumder** [comment]
@jar-b Thanks for adding the resource, have been waiting for this for around a year now.
I saw that the resource description  says  "Terraform resource for managing an AWS SSO Admin Application." Does that mean it cannot be used to actually create the application like I mentioned earlier in the request.
