### ISSUE TITLE
[Docs]:  aws_vpc "provider" argument not documented

### ISSUE THREAD

**Issue by cosminnicula** [hashicorp/terraform-provider-aws#28629]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc

### Terraform Version

```shell
Terraform v1.3.6
on linux_amd64
```

### Affected Pages

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc

### What is the docs issue?

The "provider" argument is not documented, although I can use it in code like this:

```
provider "aws" {
  region = "eu-west-1"
  profile = "default"
  alias = "aws-eu-west-1"
}
```

```
resource "aws_vpc" "vpc-eu-west-1" {
  cidr_block = "10.1.0.0/16"
  provider = aws.aws-eu-west-1
}
```

### Proposal

Document the "provider" argument mentioning that it provides a reference to a provider configuration block.

### Would you like to implement a fix?

None

**Comment by bryantbiggs** [comment]
this is not specific to the AWS provider - this is a Terraform core feature and it is documented https://developer.hashicorp.com/terraform/language/providers/configuration#selecting-alternate-provider-configurations

**Comment by cosminnicula** [comment]
Thank you! It makes sense now. I still have one question: when you say it's a Terraform core feature, does it mean that it applies to other providers such as Azure, GCP, etc.?

**Comment by justinretzolk** [comment]
Hey @cosminnicula 👋 It looks like Bryant was able to answer your question here, so I'm going to close this issue out. If you feel I've done that in error, please do let me know!
