### ISSUE TITLE
[New Resource]: Request for application assignment module in IAM Identity Center

### ISSUE THREAD

**Issue by kusumamurri** [hashicorp/terraform-provider-aws#28633]
### Description

There is no resource to create application in IAM Identity Center (successor to AWS Single sign-on).
Please provide a resource module to integrate an AWS application with SSO .
![screenshot_48](https://user-images.githubusercontent.com/78359384/210345430-53717323-9dae-4863-ac18-afff73cb7677.png)

### Requested Resource(s) and/or Data Source(s)

aws_ssoadmin_application_assignment

### Would you like to implement a fix?

None

**Comment by Fennerr** [comment]
Any update on this resource? It would help integrate IAM Identity Center with an Amazon Cognito user pool.

**Comment by steve-todorov** [comment]
We are also interested in this feature and would like to automate the provisioning of custom SAML applications.

**Comment by mtavaresmedeiros** [comment]
+1

**Comment by duenzo** [comment]
+1

**Comment by ugurcancaykara** [comment]
+1

**Comment by jclRatepay** [comment]
+1

**Comment by jclRatepay** [comment]
Wanted to share the following, latest finding regarding this topic:
We were thinking about getting around the missing Terraform "application assignment module" by setting up a CloudFormation Template for handling this application assignment and execute this Template via Terraform instead. But after checking the CloudFormation Template Reference and finding no entry regarding the Identicy Center Application Assignment here as well, I dived a bit deeper and revealed that the blocker for implementing the requested Terraform module is not on the AWS Provider side, but on the AWS side, as in the [API reference](https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_Operations.html) e.g. the "CreateApplicationInstance" (which is the proper Action Name according to [the IAM documentation](https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiamidentitycentersuccessortoawssinglesign-on.html#awsiamidentitycentersuccessortoawssinglesign-on-CreateApplicationInstance)) is not even listed. So I would guess, that no matter which workaround one might comes up with, automating the Identity Center Application Assignment is jsut not possible atm :(

**Comment by peterbev** [comment]
AWS have **_finally_** provided APIs for application assignments - https://aws.amazon.com/about-aws/whats-new/2023/11/aws-iam-identity-center-apis-automate-access-applications/

Hopefully that unblocks this, and we get an aws_ssoadmin_application_assignment resource 😄

**Comment by jclRatepay** [comment]
This actually are really great news, thanks a lot for sharing it :)

**Comment by deepakbshetty** [comment]
AWS API Ref: 
https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_CreateApplicationAssignment.html

AWS CLI ref: https://docs.aws.amazon.com/cli/latest/reference/sso-admin/create-application-assignment.html

Another use case around this is AWS Sagemaker domain in SSO mode which currently lacks ability to assign users/groups via IaC

This now possible via create_application_assignment: 
`applicationArn = sagemaker_client.describe_domain(domainId = "d-xxx")["SingleSignOnApplicationArn"]
idc_client.create_application_assignment(applicationArn = applicationArn, principalId="userId/groupId", principalType="USER/GROUP")`


Ref: https://aws.amazon.com/blogs/machine-learning/onboard-users-to-amazon-sagemaker-studio-with-active-directory-group-specific-iam-roles/
