### ISSUE TITLE
[Bug]: Custom service-linked role (EKS Nodes)

### ISSUE THREAD

**Issue by phillipstr** [hashicorp/terraform-provider-aws#28644]
### Terraform Core Version

1.3.0

### AWS Provider Version

4.48.0

### Affected Resource(s)

* aws_eks_node_group
* aws_kms_key

### Expected Behavior

KMS key successfully created, allowing node group to create

### Actual Behavior

KMS key (customer managed) fails to create due to role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling not existing in new AWS account. This is the default service-linked role for the aws_eks_node_group resource, and is created when the first Auto Scaling Group is created per [AWS documentation](https://docs.aws.amazon.com/autoscaling/ec2/userguide/autoscaling-service-linked-role.html).

What I'm facing is node groups are created from an EC2 Launch Template, which references a KMS key for EBS encryption (all Terraform managed). 

When Terraform attempts to create the aws_kms_key resource it fails due to the service-linked role not being present, because at that point the node group hasn't created due to it's dependency on the KMS key, thus not creating the AWSServiceRoleForAutoScaling role, which is needed for the key policy. Without the key policy the EKS nodes will fail to boot due to not having permissions on the KMS key.

As a workaround I used the Terraform resource aws_iam_service_linked_role to create the role with a custom suffix and assigned it to the key policy, allowing the key to successfully create. However, the Auto Scaling Group still attempts to use the default role that it creates, leading to the instances not being able to use the key. 

Using Terraform to create the default AWSServiceRoleForAutoScaling role does not seem ideal.

I believe that being able to specify a custom service-linked role in the aws_eks_node_group resource would resolve this issue. 

### Relevant Error/Panic Output Snippet

```shell
aws_kms_key.eks_ebs_vols: Still creating... [1m50s elapsed]
aws_kms_key.eks_ebs_vols: Still creating... [2m0s elapsed]
╷
│ Error: error creating KMS Key: MalformedPolicyDocumentException: Policy contains a statement with one or more invalid principals.
│
│   with aws_kms_key.key,
│   on eks-kms.tf line 16, in resource "aws_kms_key" "key":
│   16: resource "aws_kms_key" "key" {
│
╵
Releasing state lock. This may take a few moments...
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
    }
  }
}

provider "aws" {
  region = "us-east-1"
  profile = "default"
}

data "aws_caller_identity" "current" {}

data "aws_vpc" "vpc" {
  id = "CHANGEME"
}

data "aws_subnets" "all_vpc_subnets" {
  filter {
    name = "vpc-id"
    values = [data.aws_vpc.vpc.id]
  }
}

data "aws_subnet" "vpc_subnets" {
  for_each = toset(data.aws_subnets.all_vpc_subnets.ids)
  id  = each.value
}

data "aws_eks_cluster" "example" {
  name = "CHANGEME"
}

data "aws_ssm_parameter" "eks_ami_id" {
  name = "/aws/service/eks/optimized-ami/${data.aws_eks_cluster.example.version}/amazon-linux-2/recommended/image_id"
}

data "aws_iam_policy_document" "key_policy" {
  statement {
    sid = "Allow service-linked role use of the customer managed key"
    effect = "Allow"

    principals {
      type = "AWS"
      identifiers = [
        "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling"
      ]
    }

    actions = [
        "kms:Encrypt",
        "kms:Decrypt",
        "kms:ReEncrypt*",
        "kms:GenerateDataKey*",
        "kms:DescribeKey"
    ]

    resources = ["*"]
  }

  statement {
    sid = "Allow attachment of persistent resources"
    effect = "Allow"

    principals {
      type = "AWS"
      identifiers = [
        "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling"
      ]
    }

    actions = [
      "kms:CreateGrant"
    ]

    resources = ["*"]

    condition {
      test = "Bool"
      variable = "kms:GrantIsForAWSResource"
      values = ["true"]
    }
  }

  statement {
    sid = "Root Key Management"
    effect = "Allow"

    principals {
      type = "AWS"
      identifiers = [
        "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"
      ]
    }

    actions = [
      "kms:*"
    ]

    resources = ["*"]
  }
}

resource "aws_launch_template" "node_lt" {
  name = "EKS-Node-LaunchTemplate"
  update_default_version = true

  image_id = nonsensitive(data.aws_ssm_parameter.eks_ami_id.value)

  block_device_mappings {
    device_name = "/dev/xvda"

    ebs {
      volume_size = 16
      volume_type = "gp3"
      encrypted = true
      kms_key_id = aws_kms_key.key.arn
      delete_on_termination = true
    }
  }
}

resource "aws_kms_key" "key" {
  description  = "EKS-EBS-Key"
  key_usage = "ENCRYPT_DECRYPT"
  customer_master_key_spec = "SYMMETRIC_DEFAULT"

  policy = data.aws_iam_policy_document.key_policy.json
}

resource "aws_eks_node_group" "example_group" {
  cluster_name  = data.aws_eks_cluster.example.name
  node_group_name = "examplegroup"
  node_role_arn  = aws_iam_role.eks_node_role.arn
  subnet_ids  = [for subnet in data.aws_subnet.vpc_subnets : subnet.id]

  ami_type = "CUSTOM"

  scaling_config {
    desired_size = 2
    max_size = 10
    min_size = 1
  }

  launch_template {
    version = aws_launch_template.node_lt.latest_version
    id  = aws_launch_template.node_lt.id
  }

  lifecycle {
    create_before_destroy = true
    ignore_changes = [scaling_config[0].desired_size]
  }
}

resource "aws_iam_role" "eks_node_role" {
  name = "eks-node-role"

  assume_role_policy = jsonencode({
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {
        Service = "ec2.amazonaws.com"
      }
    }]
    Version = "2012-10-17"
  })
}

resource "aws_iam_role_policy_attachment" "AmazonEKSWorkerNodePolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
  role = aws_iam_role.eks_node_role.name
}

```

### Steps to Reproduce

1. AWS account without role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling)
2. Create VPC
3. Create subnet(s)
4. Deploy EKS cluster
5. Run provided config (replace "CHANGEME" with VPC ID and EKS cluster name)

### Important Factoids

- KMS customer-managed keys required for EBS volumes

### References

- https://docs.aws.amazon.com/autoscaling/ec2/userguide/autoscaling-service-linked-role.html

### Would you like to implement a fix?

None

**Comment by gdavison** [comment]
Hi @phillipstr, thank you for the detailed description.

The default `AWSServiceRoleForAutoScaling` is only created automatically when you use the AWS Console. When using the the AWS APIs, as the AWS Provider does, or the AWS CLI, you need to create the default service-linked role yourself. The resource `aws_iam_service_linked_role` works well for this.

Note that in accounts where the service-linked role already exists, you will need to import it. However, #29318 requests an enhancement to make this transparent.

Additionally, the EKS API does not offer a mechanism to supply a custom autoscaling service-linked role, so the suggested approach will not work.

Since the using the resource `aws_iam_service_linked_role` will address this issue, I'm going to close this issue. If using the resource does not solve the issue for you, please open a new issue.
