### ISSUE TITLE
[New Data Source]: aws_batch_job_definition

### ISSUE THREAD

**Issue by iancward** [hashicorp/terraform-provider-aws#28665]
### Description

I have a project that creates resources in AWS Batch (job queues, job definitions, compute environments), and a separate project that consumes those resources. While I understand that I can rely on Terraform Remote State to convey information from one project to another, in this case I'd like to avoid that and would prefer to use discrete data lookups in the downstream project.

Since Batch Job Definitions support multiple revisions, I would presume by default the data source should retrieve the latest revision.

### Requested Resource(s) and/or Data Source(s)

* data.aws_batch_job_definition

### Potential Terraform Configuration

```terraform
data "aws_batch_job_definition" "main" {
  name = "my-job-definition"
}

data "aws_batch_job_queue" "main" {
  name = "my-job-queue"
}

locals {
  job_def_arn_less_revision = regex("^(.*)(:\\d+)$", data.aws_batch_job_definition.main.arn)
}

data "aws_iam_policy_document" "batch_execute" {
  statement {
    sid       = "AllowBatchExecute"
    actions   = ["batch:SubmitJob"]
    effect    = "allow"
    resources = [
      local.job_def_arn_less_revision,
      data.aws_batch_job_queue.main.arn
    ]
  }
}
```

### Would you like to implement a fix?

None

**Comment by drewmullen** [comment]
proposed HCL

```hcl
data "aws_batch_job_definition" "main" {
  name   = "my-job-definition"
  status = "ACTIVE"
  latest = true

  #optional, coflicting:
  revision = <int>
}
```
