### ISSUE TITLE
[Bug]: SESv2: aws_sesv2_configuration_set does not allow empty list for suppressed_reasons to disable suppression list

### ISSUE THREAD

**Issue by F21** [hashicorp/terraform-provider-aws#28669]
### Terraform Core Version

1.3.6

### AWS Provider Version

4.48.0

### Affected Resource(s)

aws_sesv2_configuration_set

### Expected Behavior

Using the following configuration for the resource should allow a configuration set with the suppression list disabled to be created:

```
resource "aws_sesv2_configuration_set" "example" {
  configuration_set_name = "example"

  suppression_options {
    suppressed_reasons = []
  }
}
```

### Actual Behavior

The resource could not be created, because it expects at least one of `BOUNCE` and or `COMPLAINT` in the `suppressed_reasons` attribute

### Relevant Error/Panic Output Snippet

```shell
│ Error: Not enough list items
│
│   with aws_sesv2_configuration_set.test,
│   on main.tf line 21, in resource "aws_sesv2_configuration_set" "test":
│   21:     suppressed_reasons = []
│
│ Attribute suppression_options.0.suppressed_reasons requires 1 item minimum, but config has only 0 declared.
```
```


### Terraform Configuration Files

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {
  region = "us-east-1"
  access_key = var.access_key
  secret_key = var.secret_key
}

resource "aws_sesv2_configuration_set" "test" {
  configuration_set_name = "example"

  suppression_options {
    suppressed_reasons = []
  }
}

### Steps to Reproduce

Run `terraform apply` with the above configuration file.

### Debug Output

https://gist.github.com/F21/7ce1daa2846d55827d6e19664fcdc0df

### Panic Output

_No response_

### Important Factoids

_No response_

### References

https://github.com/hashicorp/terraform-provider-aws/issues/26796

### Would you like to implement a fix?

None

**Comment by bschaatsbergen** [comment]
Thanks for taking the time to raise this issue @F21, have you tried creating a configuration set without the entire `suppression_options` attribute block?

```
resource "aws_sesv2_configuration_set" "example" {
  configuration_set_name = "example"
}
```

By quickly looking over the provider code it seems that if you specify the argument block, it's expected that you also put something into it, instead of declaring an empty list.

Is there some default value being set by the AWS API if you don't specify an empty list?

**Comment by F21** [comment]
@bschaatsbergen 

If I omit the `suppression_options` block, the created configuration set uses the account's suppression settings. The AWS API allows the following `suppression_reasons` for overriding the account's suppression list settings (I confirmed this using `aws-go-sdk-v2`):
- Empty list (`[]`): Disable the suppression list for the configuration set
- Bounces (`["BOUNCE"]`): Add only bounces to the suppression list for the configuration set
- Complaints (`["COMPLAINT"]`): Add only complaints to the suppression list for the configuration set
- Complaints and bounces (`["BOUNCE", "COMPLAINT"]`) Add both bounces and complaints to the suppression list for the configuration set.

**Comment by bschaatsbergen** [comment]
Thanks for that @F21, that's very useful :+1:
