### ISSUE TITLE
[Bug]: aws_launch_configuration - using name-prefix does not name the instance

### ISSUE THREAD

**Issue by ninjadude333** [hashicorp/terraform-provider-aws#28685]
### Terraform Core Version

1.3.5

### AWS Provider Version

4.48.0

### Affected Resource(s)

```
resource "aws_launch_configuration" "app2_launch_config" {
  name_prefix     = "app2-"
  image_id        = data.aws_ami.amazonLnx.id
  instance_type   = "t2.micro"
  key_name        = aws_key_pair.generated_key.key_name
  security_groups = [aws_security_group.app1-sg.id]
  iam_instance_profile = aws_iam_instance_profile.app2_s3_access.name

  root_block_device {
    delete_on_termination = true
    volume_size           = 8
    volume_type           = "gp2"
  }

  ebs_block_device {
    device_name           = "/dev/sdh"
    volume_size           = 8
    volume_type           = "gp2"
    encrypted             = true
    delete_on_termination = true
  }

  lifecycle {
    create_before_destroy = true
  }

  user_data = <<-EOF
#! /bin/bash
yum update -y
yum install -y amazon-linux-extras
yum install -y awscli
EOF
}
```

### Expected Behavior

the ec2 instances should have a proper name displayed starting with the defined prefix: app2-

### Actual Behavior

the name of the ec2-instance stays blank
![image](https://user-images.githubusercontent.com/22522103/210754528-fb5f0eb1-36ba-4596-8eb0-928171f260a6.png)

### Terraform Configuration Files

```
resource "aws_launch_configuration" "app2_launch_config" {
  name_prefix     = "app2-"
  image_id        = data.aws_ami.amazonLnx.id
  instance_type   = "t2.micro"
  key_name        = aws_key_pair.generated_key.key_name
  security_groups = [aws_security_group.app1-sg.id]
  iam_instance_profile = aws_iam_instance_profile.app2_s3_access.name

  root_block_device {
    delete_on_termination = true
    volume_size           = 8
    volume_type           = "gp2"
  }

  ebs_block_device {
    device_name           = "/dev/sdh"
    volume_size           = 8
    volume_type           = "gp2"
    encrypted             = true
    delete_on_termination = true
  }

  lifecycle {
    create_before_destroy = true
  }

  user_data = <<-EOF
#! /bin/bash
yum update -y
yum install -y amazon-linux-extras
yum install -y awscli
EOF
}
```

### Steps to Reproduce

just create  a aws_launch_configuration resource with name_prefix attribute

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @ninjadude333 👋 Thank you for taking the time to raise this! The `name_prefix` argument for the `aws_launch_configuration` resource sets a name prefix for the launch template itself, rather than the instances that are launched using the launch template. One option for naming the instances would be to add a `Name` tag to an `aws_autoscaling_group` resource with the `propagate_on_launch` argument set to `true`. This would propagate the value of the `Name` tag to the instances created by the ASG.

**Comment by ninjadude333** [comment]
great, 10x, I will give it a try.

**Comment by justinretzolk** [comment]
Since we haven't heard back in quite some time, I'm going to close this issue out. If you're still having troubles or have future issues with the AWS Provider, please feel free to open a new issue, referencing this one for context as needed.
