### ISSUE TITLE
[Bug]: aws_eks_addon_version returns wrong image version

### ISSUE THREAD

**Issue by sealneaward** [hashicorp/terraform-provider-aws#28691]
### Terraform Core Version

1.3.2

### AWS Provider Version

4.1.7

### Affected Resource(s)

data.aws_eks_addon_version

### Expected Behavior

The data source should return "v1.12.0-eksbuild.1".
Based on the recommended versions [here](https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html)

### Actual Behavior

 The data source returns "v1.12.0-eksbuild.2", which does not exist as an image.

### Relevant Error/Panic Output Snippet

```shell
aws_eks_addon_version = "v1.12.0-eksbuild.2"
```

### Terraform Configuration Files

```
provider "aws" {
  region = "us-east-2"
}

terraform {
  required_providers {
    aws = {
      version = "~> 4.48"
    }
  }
}
```

### Steps to Reproduce

```
data "aws_eks_addon_version" "vpc_cni" {
  kubernetes_version = "1.22"
  addon_name         = "vpc-cni"
  most_recent        = "true"
}

output "aws_eks_addon_version" {
  value = data.aws_eks_addon_version.vpc_cni.version
}
```

### Would you like to implement a fix?

None

**Comment by sealneaward** [comment]
Looks like this is a [known issue](https://github.com/weaveworks/eksctl/issues/6027) in the aws eks api.

**Comment by justinretzolk** [comment]
Hey @sealneaward 👋 Looks like this may be upstream, as you mentioned. Using the AWS CLI, I got the following result, which seems to indicate `v1.12.0-eksbuild.2` is the most recent version:

```shell
$ aws eks describe-addon-versions --kubernetes-version 1.22 --addon-name vpc-cni

{
    "addons": [
        {
            "addonName": "vpc-cni",
            "type": "networking",
            "addonVersions": [
                {
                    "addonVersion": "v1.12.0-eksbuild.2",
                    "architecture": [
                        "amd64",
                        "arm64"
                    ],
                    "compatibilities": [
                        {
                            "clusterVersion": "1.22",
                            "platformVersions": [
                                "*"
                            ],
                            "defaultVersion": false
                        }
                    ]
                },
                {
                    "addonVersion": "v1.12.0-eksbuild.1",
                    "architecture": [
                        "amd64",
                        "arm64"
                    ],
                    "compatibilities": [
                        {
                            "clusterVersion": "1.22",
                            "platformVersions": [
                                "*"
                            ],
                            "defaultVersion": false
                        }
                    ]
                },

# trimmed for brevity
```

**Comment by rr-krupesh-savaliya** [comment]
# Same issue

## Terraform Core Version

1.3.5

## AWS Provider Version

4.49.0

## Affected Resource(s)

data.aws_eks_addon_version

## Expected Behavior

when providing the `most_recent=true` flag, it must return the latest version of the addon.

## Actual Behavior

Even if provide the `most_recent=true` flag, the data block does not return the latest available version.

## Addon list that have issue

* kube-proxy
* VPC CNI
* coredns

### EKS version `1.24`

**Comment by bryantbiggs** [comment]
FYI - this is not a Terraform/AWS provider issue. This is just a slow disconnect between the API response and the documentation. The API is the source of truth, and you can verify what that is at anytime by using the CLI

```sh
aws eks describe-addon-versions --kubernetes-version <VERSION> --addon-name <ADDON>
```
