### ISSUE TITLE
[Enhancement]: Support for AWS Eventbridge Schedules

### ISSUE THREAD

**Issue by pmcenery-bl** [hashicorp/terraform-provider-aws#28735]
### Description

In [this blog article](https://aws.amazon.com/blogs/compute/introducing-amazon-eventbridge-scheduler/), AWS have added a new feature to Eventbridge called Schedules. This has some enhancements over the traditional event rules. One feature in particular is for a schedule to allow a timezone to be specified, which was not possible previously. It appears that some new resources would need to be created to support `schedules`.

The blog outlines a new `aws schedules` CLI, rather than the previous `aws events`... so I think there is quite a bit that needs to be done to support schedules.

### Affected Resource(s) and/or Data Source(s)

* aws_

### References

* [New AWS Scheduler](https://aws.amazon.com/blogs/compute/introducing-amazon-eventbridge-scheduler/)

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/27760.

**Comment by ewbankkit** [comment]
@pmcenery-bl Thanks for raising this issue.
The [`aws_scheduler_schedule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/scheduler_schedule) resource was added via #27975 and released in Terraform AWS Provider **v4.41.0**.
This should provide the functionality you are looking for.
