### ISSUE TITLE
[Bug]: Terraform AWS Provider : failed to find installed plugin version 2.70.2

### ISSUE THREAD

**Issue by arthapan33** [hashicorp/terraform-provider-aws#28732]
### Terraform Core Version

0.12.31

### AWS Provider Version

2.70.2

### Affected Resource(s)

After the release of Terraform AWS provider 2.70.2, if consumed we are getting below error.

- Downloading plugin for provider "template" (hashicorp/template) 2.2.0...
2023/01/05 21:25:46 [WARN] found legacy provider "terraform-provider-aws_2.70.2"
- Downloading plugin for provider "archive" (hashicorp/archive) 2.2.0...
2023/01/05 21:25:46 [WARN] found legacy provider "terraform-provider-aws_2.70.2"
[31m
[1m[31mError: [0m[0m[1m**failed to find installed plugin version 2.70.2; this is a bug in Terraform and should be reported[0m**

This issue is occurring when  we run **Terraform init**

### Expected Behavior

Terraform init should be successful.
see below code as to how it worked well for 2.70.1

[0m[1mInitializing provider plugins...[0m
- Checking for available provider plugins...
- Downloading plugin for provider "aws" (hashicorp/aws) 2.70.1...
- Downloading plugin for provider "archive" (hashicorp/archive) 2.2.0...
- Downloading plugin for provider "template" (hashicorp/template) 2.2.0...
- Downloading plugin for provider "local" (hashicorp/local) 1.4.0...
- Downloading plugin for provider "null" (hashicorp/null) 2.1.2...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.archive: version = "~> 2.2"

[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
[0m[32m

### Actual Behavior

- Downloading plugin for provider "template" (hashicorp/template) 2.2.0...
2023/01/05 21:25:46 [WARN] found legacy provider "terraform-provider-aws_2.70.2"
- Downloading plugin for provider "archive" (hashicorp/archive) 2.2.0...
2023/01/05 21:25:46 [WARN] found legacy provider "terraform-provider-aws_2.70.2"
[31m
[1m[31mError: [0m[0m[1m**failed to find installed plugin version 2.70.2; this is a bug in Terraform and should be reported[0m**

### Terraform Configuration Files

Terraform Version :  0.12.31 
Terraform AWS provider version: ~>2.0

### Steps to Reproduce

Run terraform init 

### Panic Output

- Downloading plugin for provider "template" (hashicorp/template) 2.2.0...
2023/01/05 21:25:46 [WARN] found legacy provider "terraform-provider-aws_2.70.2"
- Downloading plugin for provider "archive" (hashicorp/archive) 2.2.0...
2023/01/05 21:25:46 [WARN] found legacy provider "terraform-provider-aws_2.70.2"
[31m
[1m[31mError: [0m[0m[1m**failed to find installed plugin version 2.70.2; this is a bug in Terraform and should be reported[0m**

### Would you like to implement a fix?

Yes

**Comment by rogenjosh** [comment]
this is affecting pretty much all of our stacks. please prioritise

**Comment by ewbankkit** [comment]
@arthapan33 Thanks for raising this issue.
It has already been noticed in #28706. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
