### ISSUE TITLE
[New Resource]: aws_route53domains_ds_association for AssociateDelegationSignerToDomain

### ISSUE THREAD

**Issue by bryceml** [hashicorp/terraform-provider-aws#28749]
### Description

https://docs.aws.amazon.com/Route53/latest/APIReference/API_domains_AssociateDelegationSignerToDomain.html

https://awsapichanges.info/archive/changes/8c3630-route53domains.html

This was released recently, it would be nice if there were a way to use it through terraform.  Not sure if it's better as its own resource, or if it's fine as part of the aws_route53domains_registered_domain resource.  Since you can have multiple keys I'm guessing it would be better as it's own resource.

### Requested Resource(s) and/or Data Source(s)

* aws_route53domains_ds_association

### Potential Terraform Configuration

```terraform
resource "aws_route53domains_ds_association" "example" {
  domain_name = aws_route53domains_registered_domain.example.domain_name
  algorithm   = aws_route53_key_signing_key.example.signing_algorithm_type # default value of 13
  flags       = aws_route53_key_signing_key.example.flag # default value of 257
  public_key  = aws_route53_key_signing_key.example.public_key
}
```

### References

https://docs.aws.amazon.com/Route53/latest/APIReference/API_domains_AssociateDelegationSignerToDomain.html

https://awsapichanges.info/archive/changes/8c3630-route53domains.html

### Would you like to implement a fix?

No

**Comment by Szasza** [comment]
Hi @bryceml ,

I would be interested in working on this issue.

**Comment by bryceml** [comment]
@Szasza good to hear.  Have you made any progress so far?

**Comment by Szasza** [comment]
@bryceml sorry for the delayed response, life came up. I will get to it in the next few days.

**Comment by Szasza** [comment]
@bryceml I have started working on the resource and is making good progress. However I will be AFK for a month from the end of the week. There is a good chance that I won't be able to open the PR beforehand.

**Comment by seanseth7** [comment]
@Szasza Is there any chance that you'll be putting up a PR soon? I could be interested in implementing this as my team would benefit from this resource in a feature we're working on.

**Comment by Szasza** [comment]
@seanseth7 my ETA for a PR would be sometime mid-October. Please feel free to implement it if you need it sooner, however please let me know if so, so there is no double-work done.

**Comment by seanseth7** [comment]
@Szasza Thanks for the quick response! I'll be sure to let you know if I decide to move forward with implementing myself.

**Comment by seanseth7** [comment]
@Szasza just a heads up that I started working on it in #33596. Not sure when I'll finish it, but hopefully soon. This is my first time contributing so still figuring things out.
