### ISSUE TITLE
[Bug]:  Error: creating WAFv2 WebACL Association WAFInvalidParameterException: Error reason: The ARN isn't valid

### ISSUE THREAD

**Issue by IgalSc** [hashicorp/terraform-provider-aws#28753]
### Terraform Core Version

1.3.7

### AWS Provider Version

4.46.0

### Affected Resource(s)

AWS, Cloudfront distribution, WAF ACL with IP set and rule to block all but the listed IPs

### Expected Behavior

Web ACL should be associated with the Cloudfront distribution

### Actual Behavior

An error is being thrown

### Relevant Error/Panic Output Snippet

```shell
aws_wafv2_web_acl_association.app-name: Creating...
╷
│ Error: creating WAFv2 WebACL Association (arn:aws:wafv2:us-east-1:AWS_ACCOUNT:global/webacl/app-name/guid-here,arn:aws:cloudfront::AWS_ACCOUNT:distribution/DISTRIBUTION_ID): WAFInvalidParameterException: Error reason: The ARN isn't valid. A valid ARN begins with arn: and includes other information separated by colons or slashes., field: RESOURCE_ARN, parameter: arn:aws:wafv2:us-east-1:AWS_ACCOUNT:global/webacl/app-name/guid-here
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "65f3b2ea-20e7-4431-88c9-c7f00a04030f"
│   },
│   Field: "RESOURCE_ARN",
│   Message_: "Error reason: The ARN isn't valid. A valid ARN begins with arn: and includes other information separated by colons or slashes., field: RESOURCE_ARN, parameter: arn:aws:wafv2:us-east-1:AWS_ACCOUNT:global/webacl/app-name/guid-here",
│   Parameter: "arn:aws:wafv2:us-east-1:AWS_ACCOUNT:global/webacl/app-name/guid-here",
│   Reason: "The ARN isn't valid. A valid ARN begins with arn: and includes other information separated by colons or slashes."
│ }
│
│   with aws_wafv2_web_acl_association.app-name,
│   on waf_rule_global.tf line 74, in resource "aws_wafv2_web_acl_association" "app-name":
│   74: resource "aws_wafv2_web_acl_association" "app-name" {
│
╵
```
```


### Terraform Configuration Files

```
##############
# Web Application Firewall global (Cloudfront)
##############
#
# IP set for APP-NAME access
#
resource "aws_wafv2_ip_set" "app-name" {
  name = "app-name"
  scope  = "CLOUDFRONT"
  ip_address_version = "IPV4"
  addresses = [
    LIST OF IP ADDRESSES HERE
  ]
}
#
# WAF ACL for app-name
#
resource "aws_wafv2_web_acl" "app-name" {
  name        = "app-name"
  description = "Rule group for app-name"
  scope       = "CLOUDFRONT"

  default_action {
    block {}
  }

  rule {
    name     = "app-name"
    priority = 1

    action {
      allow {}
    }

    statement {
      ip_set_reference_statement {
        arn = aws_wafv2_ip_set.app-name.arn
      }
    }

    visibility_config {
      cloudwatch_metrics_enabled = false
      metric_name                = "aws-waf-logs-blacklisted-ip-rule"
      sampled_requests_enabled   = false
    }
  }

  visibility_config {
    cloudwatch_metrics_enabled = false
    metric_name                = "aws-waf-logs-blacklisted-ip"
    sampled_requests_enabled   = false
  }

  tags = {
    Name = "app-name"
    Cost = "app-name"
    env = "prod"
  }
}
#
#Associate the WAF ACL with the app-name Cloudfront distribution
#

resource "aws_wafv2_web_acl_association" "app-name" {
  resource_arn = aws_cloudfront_distribution.app-name.arn
  web_acl_arn  = aws_wafv2_web_acl.app-name.arn
}

### Steps to Reproduce

terraform apply

### Would you like to implement a fix?

None

**Comment by trevorrea** [comment]
Hi,

You need to use the web_acl_id on the CloudFront distribution itself. See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#web_acl_id for details.

The docs for aws_wafv2_web_acl_association at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl_association say:-

NOTE on associating a WAFv2 Web ACL with a Cloudfront distribution:

Do not use this resource to associate a WAFv2 Web ACL with a Cloudfront Distribution. The [AWS API call backing this resource](https://docs.aws.amazon.com/waf/latest/APIReference/API_AssociateWebACL.html) notes that you should use the [web_acl_id](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#web_acl_id) property on the [cloudfront_distribution](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#web_acl_id) instead.

Thanks,
Trevor
