### ISSUE TITLE
[Enhancement]: Allow aws_db_instance for RDS MSSQL Custom to use Custom Engine Version (CEV)

### ISSUE THREAD

**Issue by juanca-caylent** [hashicorp/terraform-provider-aws#28765]
### Description

This will allow creating a baseline configuration of the OS and database and then lunch whenever RDS MSSQL instances are needed.

### Affected Resource(s) and/or Data Source(s)

aws_db_instance

### References

https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-rds-custom-sql-server-custom-engine-version-resiliency-customizations/
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/custom-cev-sqlserver.create.html

### Would you like to implement a fix?

No

**Comment by maverick1974** [comment]
WE need this as we're switching from fully managed RDS to Custom RDS and need to update our TF to rebuild, currently we're having to use exec commands to run Cloudformation.

**Comment by AdamTylerLynch** [comment]
RDS Custom for SQL Server is supported in the `aws_db_instance` resource.

1. You need to set the `engine` to your CEV engine.
2. You need to set the `engine_version` to your CEV engine_version. 
3. You need to specify the `custom_iam_instance_profile` to your RDSCustom* IAM Instance Role.

The process is substantially similar to how we do it in RDS Custom for Oracle. You can see our module here on the AWS IA GitHub: https://github.com/aws-ia/terraform-aws-rds-custom-for-oracle

If you would like a SQL Server module created, please reach out to your AWS account team and ask them to log a PFR.

**Comment by AdamTylerLynch** [comment]
I added an example to the docs to provide clarity.
