### ISSUE TITLE
[Bug]: aws_subnet fails to assign ipv6_cidr_block from cidrsubnet()

### ISSUE THREAD

**Issue by mahelious** [hashicorp/terraform-provider-aws#28775]
### Terraform Core Version

1.3.6

### AWS Provider Version

4.49.0

### Affected Resource(s)

Developing a new module to deploy AWS VPC and subnets, attempted to set the subnet ipv6 CIDRs using the [cidrsubnet](https://developer.hashicorp.com/terraform/language/functions/cidrsubnet) function passed the `plan` review but returned an error while attempting to create the subnet

```error
Error: error creating EC2 Subnet: InvalidParameterValue: invalid value for parameter ipv6-cidr-block: 2600:1f16:c6:ff10::/60
```

### Expected Behavior

Subnet should create with the requested ipv6 CIDR block

### Actual Behavior

Error InvalidParameterValue halts creation of the subnet and terminates the `apply` action

### Relevant Error/Panic Output Snippet

```shell
│ Error: error creating EC2 Subnet: InvalidParameterValue: invalid value for parameter ipv6-cidr-block: 2600:1f16:c6:ff10::/60
│ 	status code: 400, request id: 47acc71c-db54-4801-96de-d1c10085d996
│
│   with module.test_module_vpc.aws_subnet.subnets-public-a,
│   on ../../../../../tf-modules/wde/vpc/subnets-public.tf line 1, in resource "aws_subnet" "subnets-public-a":
│   23: resource "aws_subnet" "subnets-public-a" {
```

### Terraform Configuration Files

```terraform
locals {
  vpc_cidr_block = "10.1.0.0/16"
}

locals {
  region = "us-east-1"
  subnet_cidrs  = cidrsubnets(local.vpc_cidr_block, 2, 2, 2)
}

resource "aws_vpc" "default" {
  cidr_block            = local.vpc_cidr_block
  assign_generated_ipv6_cidr_block = true
  enable_dns_hostnames  = true
  enable_dns_support    = true
}

resource "aws_subnet" "subnets-public" {
  vpc_id            = aws_vpc.default.id
  availability_zone = "${local.region}a"
  cidr_block        = element(local.subnet_cidrs, 0)
  ipv6_cidr_block   = cidrsubnet(aws_vpc.default.ipv6_cidr_block, 4, 1)
}
```

### Steps to Reproduce

Running the provided code has reproduced the behavior consistently

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @mahelious 👋 It looks like this might be due to this note from the [`aws_subnet.ipv6_cidr_block` description]:

> ... The subnet size must use a /64 prefix length.

As compared to the info from the error message (emphasis mine):

> InvalidParameterValue: invalid value for parameter ipv6-cidr-block: **2600:1f16:c6:ff10::/60**

**Comment by justinretzolk** [comment]
Since we haven't heard back in quite some time, I'm going to close this issue out. If you're still having troubles or have future issues with the AWS Provider, please feel free to open a new issue, referencing this one for context as needed.
