### ISSUE TITLE
[Enhancement]: RDS native secret manager integration

### ISSUE THREAD

**Issue by pdeva** [hashicorp/terraform-provider-aws#28781]
### Description

Please add support for recently released native Secret Manager integration for RDS in rds terraform resource 

### Affected Resource(s) and/or Data Source(s)

aws_rds_cluster

### References

https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-rds-integration-aws-secrets-manager/

### Would you like to implement a fix?

None

**Comment by tmccombs** [comment]
This looks like a duplicate of #28538

**Comment by AdamTylerLynch** [comment]
Duplicate of #28848

**Comment by AdamTylerLynch** [comment]
Duplicate
