### ISSUE TITLE
[Enhancement]: Allow using metric math expressions in `aws_appautoscaling_policy`

### ISSUE THREAD

**Issue by dsech** [hashicorp/terraform-provider-aws#28787]
### Description

The [`customized_metric_specification`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appautoscaling_policy#customized_metric_specification)  block from `aws_appautoscaling_policy` doesn't expose the `Metrics` property from [CustomizedMetricSpecification](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_CustomizedMetricSpecification.html).

Please include this functionality so that metric math expressions could be specified when building target tracking autoscaling policies.

The potential terraform config is inspired from `aws_cloudwatch_metric_alarm` resource.

### Affected Resource(s) and/or Data Source(s)

aws_appautoscaling_policy

### Potential Terraform Configuration

```terraform
resource "aws_appautoscaling_policy" "policy" {
  name               = "custom-policy"
  service_namespace  = aws_appautoscaling_target.target.service_namespace
  scalable_dimension = aws_appautoscaling_target.target.scalable_dimension
  resource_id        = aws_appautoscaling_target.target.resource_id
  policy_type        = "TargetTrackingScaling"

  target_tracking_scaling_policy_configuration {
    target_value = 100

    customized_metric_specification {
      metric_query {
        label = "Get the queue size (the number of messages waiting to be processed)"
        id = "m1"

        metric {
          metric_name = "ApproximateNumberOfMessagesVisible"
          namespace = "AWS/SQS"
          dimensions = {
            QueueName = "my-queue"
          }
        }
      }

      metric_query {
        label = "Get the group size (the number of InService instances)"
        id = "m2"

        metric {
          metric_name = "GroupInServiceInstances"
          namespace = "AWS/AutoScaling"
          dimensions = {
            AutoScalingGroupName = "my-asg"
          }
        }
      }

      metric_query {
        label = "Calculate the backlog per instance"
        id = "e1"
        expression = "m1 / m2"
        return_data = true
      }
    }
  }
}
```

### References

https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-target-tracking-metric-math.html

### Would you like to implement a fix?

No

**Comment by jungseoklee** [comment]
Application Auto Scaling does not support metric math for target tracking policy while EC2 Auto Scaling does.

Note that there is an open PR for EC Auto Scaling: #28560

**Comment by dsech** [comment]
Wow I misread the docs so bad this time. Thank you @jungseoklee !
