### ISSUE TITLE
[Bug]: terraform import aws_iam_server_certificate fails to update state

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#28797]
### Terraform Core Version

1.3.7

### AWS Provider Version

4.49.0

### Affected Resource(s)

* aws_iam_server_certificate

### Expected Behavior

Importing a cert should update the terraform state

### Actual Behavior

The import state reports that it is successful, but the certificate update is still shown as a pending change on the next plan or apply.

### Relevant Error/Panic Output Snippet

```shell
$ terraform apply
...
  # aws_iam_server_certificate.mycert[0] will be created                                                               
  + resource "aws_iam_server_certificate" "mycert" {                                                                   
      + arn               = (known after apply)                                                                        
      + certificate_body  = <<-EOT                                                                                     
...
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.                                                            

$ terraform state list                                   
aws_iam_server_certificate.mycert[0]

$ terraform state rm aws_iam_server_certificate.mycert                                                               
Removed aws_iam_server_certificate.mycert[0]
Successfully removed 1 resource instance(s).

$ terraform state list                                

$ terraform import aws_iam_server_certificate.mycert mycert-29-08-2022                                                                                                                                                                      

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

$ terraform state list                                                 

$ terraform apply
...
  # aws_iam_server_certificate.mycert[0] will be created                                                               
  + resource "aws_iam_server_certificate" "mycert" {                                                                   
      + arn               = (known after apply)                                                                        
      + certificate_body  = <<-EOT                                                                                     
...

$ aws iam list-server-certificates | grep mycert
            "ServerCertificateName": "mycert-29-08-2022"
...
```

### Terraform Configuration Files

```terraform
provider "aws" {
  region = var.aws_region
}

variable "aws_region" {
  default = "eu-west-1"
}

variable "env" {
  default = "dev"
}

variable "cert" {
  default = {
    cert_path  = "mycert/cert.crt"
    chain_path = "mycert/chain.pem"
    key_path   = "mycert/private.key"
    issue_date = "29-08-2022"
  }
}

resource "aws_iam_server_certificate" "mycert" {
  count = var.env == "dev" ? 1 : 0

  name = "mycert-${var.cert["issue_date"]}"

  certificate_body  = file(var.cert["cert_path"])
  certificate_chain = file(var.cert["chain_path"])
  private_key       = file(var.cert["key_path"])
}
```

### Steps to Reproduce

Require valid cert files positioned in subdirectory "mycert" and a properly configured aws account. Then follow similar pattern to commands above. The expected output at the end of the following should list the reimported cert. For me, no resources are listed:

terraform init
terraform apply
terraform state rm aws_iam_server_certificate.mycert
terraform state import aws_iam_server_certificate.mycert mycert-29-08-2022
terraform state list

(Note that this used to work - I can't give you a definite version but certainly at some point in the 0.11.x range.)

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey there 👋 Since you're using `count`, you'll need to import to the specific instance of that resource, e.g.:

```shell
terraform import aws_iam_server_certificate.mycert[0] mycert-29-08-2022
```

Confusingly, I'd expect excluding the `[0]` to result in an error, so I'll be interested to see if that does indeed resolve your issue. If so, might be something we need to report in the Terraform Core repo.

**Comment by jexh** [comment]
(Sorry about change of username - I was accidentally logged in from another account when I created the issue.)
I tried that originally and it didn't work, however, I am using zsh (omz) and the error I got was:

$ terraform import aws_iam_server_certificate.mycert[0] mycert-29-08-2022 
zsh: no matches found: aws_iam_server_certificate.mycert[0]

Originally, I assumed this was zsh being clever but with your comment I tried again from bash to see if that made a difference and it just works so I'm very sorry about that. It turns out it is a zsh or omz problem.
