### ISSUE TITLE
Changes detection for iam user, role and permission set

### ISSUE THREAD

**Issue by adyl-exos** [hashicorp/terraform-provider-aws#28803]
### Description

Terraform version 1.1.9

We have a question, regarding how terraform detect changes for IAM user, IAM role and Permissions Set.

We have the following scenarios:

1. Created IAM user with attached IAM policies by terraform. If we add some IAM policy to created user, terraform do not detect such change during plan.

2. Created IAM role with attached IAM policies by terraform. If we add some IAM policy to created role, terraform detect this change and writing message "Note: Objects have changed outside of Terraform" and showing changes, but do not apply them during terraform apply

3. Created Permission set in IAM Identity Center and attached some IAM policies as Customer managed policies - this action done by terraform. If we add some other IAM policy as Customer managed policies, terrafrom do not detect such change.

So the question is if such behavior is according to design or it's a bug? 

### Would you like to implement a fix?

None

**Comment by YakDriver** [comment]
@adyl-exos This area of the code has changed recently. Which version are you using? We need a config and version (TF & AWS provider) in order to reproduce the problem.

**Comment by adyl-exos** [comment]
Hello,

Code samples and versions for all 3 scenarios, also please note that code mostly like sample, I cannot share actual code.

Scenario 1:
terraform version: 1.1.9
aws provider version: v3.61.0

Terraform code:
=======================================================
resource "aws_iam_user" "test" {
  name     = "test"
  path     = "/"
}

resource "aws_iam_policy" "test_policy" {
  name     = "test_policy"
  path     = "/"
  policy = templatefile("${path.module}/templates/sample_policy.json",
    {
      aws_region          = "us-east-1"
      aws_account_id      = "123456789"
    }
  )
}

resource "aws_iam_user_policy_attachment" "test_user_policy_attachment" {
  policy_arn = aws_iam_policy.test_policy.arn
  user       = aws_iam_user.test.name
}
======================================================

In current scenario, if we manually add AWS or Customer managed policy in AWS console, during terraform plan, terraform do not detect any changes. Simply it not tries to remove from user attached manually policies or not notify that those policies were attached to user.

Scenario 2:
terraform version: 1.1.9
aws provider version: v3.61.0

Terraform code:
=======================================================
resource "aws_iam_role" "test" {
  name     = "test"
  path     = "/"
  assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
POLICY
}

resource "aws_iam_policy" "test_policy" {
  name     = "test_policy"
  path     = "/"
  policy = templatefile("${path.module}/templates/sample_policy.json",
    {
      aws_region          = "us-east-1"
      aws_account_id      = "123456789"
    }
  )
}

resource "aws_iam_role_policy_attachment" "test_role_policy_attachment" {
  policy_arn = aws_iam_policy.test_policy.arn
  role       = aws_iam_role.test.name
}
======================================================

In current scenario, if we manually add AWS or Customer managed policy in AWS console, during terraform plan,terraform detects such changes with the following message "Note: Objects have changed outside of Terraform" and showing that some policies were added outside terraform, but not showing that it will remove it during next apply.

Scenario 3:
terraform version: 1.2.6
aws provider version: v4.51.0

Terraform code:
=======================================================
resource "aws_iam_policy" "test_policy" {
  name     = "test_policy"
  path     = "/"
  policy = templatefile("${path.module}/templates/sample_policy.json",
    {
      aws_region          = "us-east-1"
      aws_account_id      = "123456789"
    }
  )
}

resource "aws_ssoadmin_permission_set" "test" {
  name             = "test"
  instance_arn     = tolist(data.aws_ssoadmin_instances.this.arns)[0]
}


resource "aws_ssoadmin_customer_managed_policy_attachment" "test_attachment" {
  instance_arn       = aws_ssoadmin_permission_set.this.instance_arn
  permission_set_arn = aws_ssoadmin_permission_set.test.arn
  customer_managed_policy_reference {
    name = aws_iam_policy.test_policy.name 
    path = "/"
  }
}
==================================
If we add other Customer Managed policies to this Permission Set manually in AWS console, terraform do not detect that such policies was added.

**Comment by YakDriver** [comment]
I'll describe the scenarios and situation now.

### Scenario 1
This is working as expected. `aws_iam_user` does not offer exclusive management of policies in the same way that `aws_iam_role` does. 

### Scenario 2
This is working as expected in v4.56.0. (I cannot tell in v3.61.0 as we do not support that version.) In order to use the exclusive management feature of `aws_iam_role`, you _must_ use the `managed_policy_arns` or `inline_policy` arguments.  This is specifically addressed at the top of documentation for [`aws_iam_role`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role) in the 2nd NOTE where it states you get "exclusive management" with `managed_policy_arns` or `inline_policy` but _cannot_ use those with `aws_iam_policy_attachment`, `aws_iam_role_policy_attachment`, and `aws_iam_role_policy`.

If you follow this example, and then add a managed policy to the role in AWS console, on the next apply, the extra policy will be removed. 

```terraform
resource "aws_iam_policy" "test" {
  name = "policyname"
  path = "/tf-testing/"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
    "Action": [
      "ec2:Describe*"
    ],
    "Effect": "Allow",
    "Resource": "*"
    }
  ]
}
EOF
}

resource "aws_iam_role" "test" {
  name                = "rolename"
  managed_policy_arns = [aws_iam_policy.test.arn]

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole",
      Principal = {
        Service = "ec2.amazonaws.com",
      }
      Effect = "Allow"
      Sid    = ""
    }]
  })
}
```

### Scenario 3

This is working as designed. `aws_iam_role` is unusual in that it offers exclusive management of policies for the role. `aws_ssoadmin_permission_set` is not designed to have the same functionality. If you are interested in it, please submit an issue with the feature request.
