### ISSUE TITLE
[Bug]: AMI ID (Instance Image) does not get auto assigned/created when creating a ec2 image builder container recipe with terraform

### ISSUE THREAD

**Issue by PatrickKhai-Moodys** [hashicorp/terraform-provider-aws#28805]
### Terraform Core Version

>= 1.10

### AWS Provider Version

`4.49`

### Affected Resource(s)

Instance configuration 
- Image <= This parameters needs AMI ID string usually but if it doesnt it should have been provided by default.

### Expected Behavior

Instance Image should have created an ami ID for the container recipe by default.

### Actual Behavior

Instance image does not get created with the container recipe. Instead it came out blank.

### Terraform Configuration Files

```
resource "aws_imagebuilder_container_recipe" "this" {
  name           = var.name
  container_type = var.container_type
  parent_image   = var.parent_image
  version        = var.recipe_version
  tags           = var.tags

    
  instance_configuration {
    image = var.ami_id #this is to be created default
    block_device_mapping {
      device_name = "/dev/xvda"
      ebs { 
        delete_on_termination = true
        volume_size           = var.ebs_volume_size
        volume_type           = var.ebs_volume_type
        iops                  = var.ebs_iops
        throughput            = var.ebs_throughput 
      }
    }
  }

}

````

### Steps to Reproduce

Usually you can create a container recipe and it should create/assigned ami id automatically but when creating this from terraform code, the ami id does not get created.

### Important Factoids

What should I do to make sure the the AMI ID is provided automatically when using terraform to create the container recipe? 
When I manually create this on AWS console, AMI Id is provided automatically.

Per aws, instanceConfiguration (object) – A group of options that can be used to configure an instance for building and testing container images. However this image object below does not get created through terraform process.
- image (string) – The AMI ID to use as the base image for a container build and test instance. If not specified, Image Builder will use the appropriate Amazon ECS-optimized AMI as a base image.

### References

https://registry.terraform.io/providers/hashicorp/aws/4.49.0/docs/resources/imagebuilder_container_recipe

### Would you like to implement a fix?

None

**Comment by kamilturek** [comment]
Hello 👋  Thank you for your report!

I am afraid that it might be an API limitation. Indeed, when creating a container recipe via the AWS console, the AMI is pre-filled by default and applied even if erased before submitting the form.

<img width="265" alt="image" src="https://user-images.githubusercontent.com/22010517/211640073-0e930dd3-cbdc-444c-bda3-a8c335ce616e.png">

However, when creating a container recipe via API without specifying the AMI ID, the field is not filled and it's blank both in the console and API responses.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/22010517/211640245-2cd4772f-5721-4521-b766-9e3abd6e0bdb.png">

```bash
$ aws --no-cli-pager imagebuilder get-container-recipe --container-recipe-arn $ARN
{
    "requestId": "a5830be5-5d9d-447b-ad28-219c2266e18e",
    "containerRecipe": {
        "arn": "arn:aws:imagebuilder:eu-central-1:XXX:container-recipe/example/1.0.0",
        "containerType": "DOCKER",
        "name": "example",
        "platform": "Linux",
        "owner": "XXX",
        "version": "1.0.0",
        "components": [
            {
                "componentArn": "arn:aws:imagebuilder:eu-central-1:aws:component/update-linux/x.x.x"
            }
        ],
        "instanceConfiguration": {
            "blockDeviceMappings": [
                {
                    "deviceName": "/dev/xvda"
                }
            ]
        },
        "dockerfileTemplateData": "FROM {{{ imagebuilder:parentImage }}}\n{{{ imagebuilder:environments }}}\n{{{ imagebuilder:components }}}\n",
        "encrypted": true,
        "parentImage": "arn:aws:imagebuilder:eu-central-1:aws:image/amazon-linux-x86-latest/x.x.x",
        "dateCreated": "2023-01-10T19:05:58.716Z",
        "tags": {},
        "targetRepository": {
            "service": "ECR",
            "repositoryName": "example"
        }
    }
}
```

Therefore it can't be obtained by the provider.

**Comment by PatrickKhai-Moodys** [comment]
Hi, thank you for the response. 

I assumed it will be this way for a while for this particular resource.
