### ISSUE TITLE
[Enhancement]: App Runner now supports runtime variables from Secrets Manager and SSM

### ISSUE THREAD

**Issue by nowosprz** [hashicorp/terraform-provider-aws#28849]
### Description

AWS announced that App Runner now supports retrieving secrets and configuration from Secrets Manager and Systems Manager. [Announcement](https://aws.amazon.com/about-aws/whats-new/2023/01/aws-app-runner-secrets-configuration-aws-secrets-systems-manager/)

Currently aws_apprunner_service supports the previously existing plain text variables.

It has been very anticipated feature of App Runner, therefore I am bringing this to your attention :)

I've provided the potential configuration, but since the secret 'value' is arn to either SSM or SecretsManager, ~~maybe it can be resolved dynamically behind the scenes.~~ That could interfere with trying to actually supply such arn to the app in App Runner.

### Affected Resource(s) and/or Data Source(s)

* aws_apprunner_service

### Potential Terraform Configuration

```terraform
resource "aws_apprunner_service" "example" {
  source_configuration {
    image_configuration {
      runtime_environment_variables = {
        ENV_VAR_KEY = { type="SECRETSMANAGER", value="arn:aws:secretsmanager:***:***:secret:***"
      }
    }
  }
}
```

### Would you like to implement a fix?

None

**Comment by niallthomson** [comment]
I'll be creating a PR for this soon

**Comment by niallthomson** [comment]
I kept the schema a bit simpler than originally suggested here to keep it in line with the CloudFormation schema.

```hcl
resource "aws_ssm_parameter" "test" {
  name  = "test"
  type  = "String"
  value = "test"
}

resource "aws_apprunner_service" "test" {
  service_name = "test"
  source_configuration {
    auto_deployments_enabled = false
    image_repository {
      image_configuration {
        port = "80"
        runtime_environment_secrets = {
          SSM_PARAMETER = aws_ssm_parameter.test.arn
        }
      }
      image_identifier      = "public.ecr.aws/nginx/nginx:latest"
      image_repository_type = "ECR_PUBLIC"
    }
  }
  instance_configuration {
    cpu               = "1 vCPU"
    instance_role_arn = aws_iam_role.test.arn
    memory            = "3 GB"
  }
}
```
