### ISSUE TITLE
[Bug]: In `aws_lightsail_instance`, `availability_zone` is limited to those belong to the region in `provider "aws"`

### ISSUE THREAD

**Issue by np36** [hashicorp/terraform-provider-aws#28869]
### Terraform Core Version

1.3.7

### AWS Provider Version

4.45.0

### Affected Resource(s)

* aws_lightsail_instance

### Expected Behavior

`availability_zone` in `aws_lightsail_instance` could be set to any one that listed in [Terraform Doc/aws/Resource: aws_lightsail_instance/Availability Zones](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_instance#availability-zones):

```
ap-northeast-1{a,c,d}
ap-northeast-2{a,c}
ap-south-1{a,b}
ap-southeast-1{a,b,c}
ap-southeast-2{a,b,c}
ca-central-1{a,b}
eu-central-1{a,b,c}
eu-west-1{a,b,c}
eu-west-2{a,b,c}
eu-west-3{a,b,c}
us-east-1{a,b,c,d,e,f}
us-east-2{a,b,c}
us-west-2{a,b,c}
```

#### if set `provider` like this:
```
provider "aws" {
  region = "us-east-2"
}
```
#### and set `aws_lightsail_instance` like this:
```
resource "aws_lightsail_instance" "main" {
  ...
  availability_zone = "ap-northeast-2c"
  ...
}
```
#### `terraform apply` would complain:
```
Error: InvalidInputException: The given Availability Zone is invalid. 
It must be one of the following: us-east-2a,us-east-2b,us-east-2c.
```

### Relevant Error/Panic Output Snippet

```shell
aws_lightsail_instance.main[0]: Creating...
╷
│ Error: InvalidInputException: The given Availability Zone is invalid. It must be one of the following: us-east-2a,us-east-2b,us-east-2c.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "xxxxxxxxxxxxxxxxx"
│   },
│   Code_: "InvalidParams",
│   Message_: "The given Availability Zone is invalid. It must be one of the following: us-east-2a,us-east-2b,us-east-2c."
│ }
│ 
│   with aws_lightsail_instance.main[0],
│   on lightsail.tf line 1, in resource "aws_lightsail_instance" "main":
│    1: resource "aws_lightsail_instance" "main" {
│
```

### Terraform Configuration Files

```
provider "aws" {
  region = "us-east-2"
}

resource "aws_lightsail_instance" "main" {
  name = "example"
  availability_zone = "ap-northeast-2c"
  blueprint_id = "wordpress"
  bundle_id = "nano_2_0"
}


```

#### if set `provider` like this:
```
provider "aws" {
  region = "us-east-2"
}
```
#### and set `aws_lightsail_instance` like this:
```
resource "aws_lightsail_instance" "main" {
  ...
  availability_zone = "ap-northeast-2c"
  ...
}
```
#### `terraform apply` would complain:
```
Error: InvalidInputException: The given Availability Zone is invalid. 
It must be one of the following: us-east-2a,us-east-2b,us-east-2c.
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @np36 👋 My read on those docs is that those are the availability zones that currently support Lightsail. You could, however, utilize different regions by using [provider aliasing](https://developer.hashicorp.com/terraform/language/providers/configuration#alias-multiple-provider-configurations) and passing the [`provider` meta-argument](https://developer.hashicorp.com/terraform/language/providers/configuration#selecting-alternate-provider-configurations) to select the provider instantiation in the appropriate region.

**Comment by gdavison** [comment]
We should add validation to the `availability_zone` parameter so that it rejects AZs from other regions.
