### ISSUE TITLE
[Docs]: aws_flow_logs

### ISSUE THREAD

**Issue by umpa385** [hashicorp/terraform-provider-aws#28885]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/flow_log

### Description

On this page here https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/flow_log

for the section below the log destination should be a kinesis delivery stream for direct put or a data stream for the arn, and not a cloudwatch log group arn. 

`[Amazon Kinesis Data Firehose logging](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/flow_log#amazon-kinesis-data-firehose-logging)
resource "aws_flow_log" "example" {
  iam_role_arn    = aws_iam_role.example.arn
  log_destination = aws_cloudwatch_log_group.example.arn`

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @umpa385 👋 Thank you for taking the time to raise this! I've opened PR #28964 to address this.
