### ISSUE TITLE
[Docs]: Certain policy name changed new for AWS Config

### ISSUE THREAD

**Issue by hatanoyoshihiko** [hashicorp/terraform-provider-aws#28904]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_configuration_recorder_status

### Description

A IAM policy for AWS Config seems like to not availavle certain policy name in "Resource: aws_config_configuration_recorder_status".

Old policy name "AWSConfigRole" is no longer available.
New policy name is "AWS_ConfigRole"

- Currently code

```
resource "aws_iam_role_policy_attachment" "a" {
  role       = aws_iam_role.r.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSConfigRole"
}

```

- Proposed amendment

```
resource "aws_iam_role_policy_attachment" "a" {
  role       = aws_iam_role.r.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWS_ConfigRole"
}
```

### References

- AWSConfigRole is deprecated. The replacement policy is AWS_ConfigRole.
https://docs.aws.amazon.com/config/latest/developerguide/security-iam-awsmanpol.html

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @hatanoyoshihiko 👋 Than you for taking the time to raise this! I've opened PR #28938 to correct the documentation.
