### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by deepak-mech** [hashicorp/terraform-provider-aws#28906]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#launch-template-specification

### Description

In the documentation, it should be mentioned that one of the arguments from instance_type & launch_template must be specified to create the ec2 instance.
![Screenshot (984)](https://user-images.githubusercontent.com/65217245/212556916-eb8183d1-6bd9-49b6-bda9-de9be54f61c9.png)

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @deepak-mech 👋 Thank you for taking the time to raise this! I've opened PR #28959 aimed at clarifying the requirements here.
