### ISSUE TITLE
Terraform Aws new region "me-central-1".  error :' Invalid Region"

### ISSUE THREAD

**Issue by atanudas100** [hashicorp/terraform-provider-aws#28909]
### Description

If I use latest terraform version "4.50".. then the code accept the region "me-central-1" but it showing "Error: operation error STS: AssumeRole, https response error StatusCode: 403, RequestID: f4c793eb-0e82-4ce2-aa4e-359d959a9779, api error InvalidClientTokenId: The security token included in the request is invalid"

Using any other version < v4.50 , it is showing "Invalid region me-central-1"

### Would you like to implement a fix?

None

**Comment by xeonic-ant** [comment]
Hi. Problem is really serious, we can not use terraform for new regions

**Comment by joeybenamy** [comment]
We also have this issue and it is blocking us from using Terraform in new regions.

**Comment by zning1994** [comment]
Me too, I cannot use terraform to deploy an EKS Cluster in me-central-1. Is it because of this region release recently?

```shell
│ Error: Invalid AWS Region: me-central-1
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on terraform.tf line 28, in provider "aws":
│   28: provider "aws" {
│ 
```

**Comment by jwenz723** [comment]
I am also experiencing this issue when using an AWS S3 bucket in me-central-1 as the state backend for my module. My module is only creating global resources like IAM roles.

**Comment by jwenz723** [comment]
My problem was due to the terraform cli version not being up to date. I updated to version `1.4.6` and now my issue with accessing a terraform s3 state bucket in me-central-1 is resolved.

**Comment by Onelvis** [comment]
Tried with terraform cli version `1.5.5` and still having same issue.

**Comment by adamdaniel2993** [comment]
I have try with terraform `1.5.5` no luck, I tried with sts_region and endpoint block pointing to the sts URL, and no luck..

**Comment by cisco-ashekham** [comment]
Hello! Is there any update on this?

**Comment by justin-octo** [comment]
You can set your terragrunt.hcl file to "ignore" a region.  This may work for you.
With Terragrunt, you can use this:
```
read_terragrunt_config(find_in_parent_folders("multi_region_common.hcl"))
  regions_to_ignore = "me_central_1"
  all_aws_regions   = [for region in local.multi_region_vars.locals.all_aws_regions : region if region != local.regions_to_ignore]  
  #all_aws_regions   = local.multi_region_vars.locals.all_aws_regions
```

**Comment by ewbankkit** [comment]
Fixed via https://github.com/hashicorp/terraform-provider-aws/pull/26590 in Terraform AWS Provider **v4.29.0**.
