### ISSUE TITLE
[Docs]: resource aws_cur_report_definition with time_unit descriptions

### ISSUE THREAD

**Issue by xshot9011** [hashicorp/terraform-provider-aws#28910]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cur_report_definition#time_unit

### Description

The valid value has 3 possibles values {HOURLY, DAILY, MONTHLY}
From:
[time_unit](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cur_report_definition#time_unit) - (Required) The frequency on which report data are measured and displayed. Valid values are: HOURLY, DAILY.
To:
[time_unit](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cur_report_definition#time_unit) - (Required) The frequency on which report data are measured and displayed. Valid values are: HOURLY, DAILY, `MONTHLY`.

### References

https://docs.aws.amazon.com/cur/latest/userguide/cur-create.html

In section time gra

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @xshot9011 👋 Thank you for taking the time to raise this! I've opened a PR to add `MONTHLY` as a valid value in the documentation 👍.

**Comment by xshot9011** [comment]
@justinretzolk Thank you for what you've done.
