### ISSUE TITLE
[Bug]: Thumbprint length validation for aws_iam_openid_connect_provider

### ISSUE THREAD

**Issue by niraj8** [hashicorp/terraform-provider-aws#28916]
### Terraform Core Version

1.3.4

### AWS Provider Version

4.50.0

### Affected Resource(s)

`aws_iam_openid_connect_provider`

### Expected Behavior

Accept the thumbprint value

### Actual Behavior

I get the below error message when I try and use this value while running `terraform plan`

```
 Error: expected length of thumbprint_list.0 to be in the range (40 - 40), got 25768713d3b459f9382d2a594f85f34709fd2a8930731542a4146ffb246bec69
```

> I don't completely understand Certificate thumbprints so I may be generating the thumbprint incorrectly. I followed [this guide](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc_verify-thumbprint.html) to generate Github's thumbprint

The current thumbprint valid till Nov 7 2023 is `25768713d3b459f9382d2a594f85f34709fd2a8930731542a4146ffb246bec69`, which is 64 characters in length

### Relevant Error/Panic Output Snippet

```shell
Error: expected length of thumbprint_list.0 to be in the range (40 - 40), got 25768713d3b459f9382d2a594f85f34709fd2a8930731542a4146ffb246bec69
```

### Terraform Configuration Files

https://github.com/amberhq/terraform-aws-github-oidc-iam-role

### Steps to Reproduce

```
git clone git@github.com:niraj8/terraform-aws-github-oidc-iam-role.git
cd terraform-aws-github-oidc-iam-role
git checkout thumbprint-length-issue
cd examples/complete/
terraform init
terraform plan
```

### Would you like to implement a fix?

Yes

**Comment by jianbinw** [comment]
I started to have same issue after upgrading my MacOS to "Ventura 13.1". 
The version of openssl is changed and output of `openssl x509 -fingerprint -noout` with AWS certificate is also different (e.g. SHA256 instead of SHA).
But my other machines running Ubuntu are fine with same version of terraform and provider. 

A quick fix would be adding the algorithm (SHA1) into the command:
`openssl x509 -sha1 -fingerprint -noout`

@niraj8 can you provide the OS info?

**Comment by niraj8** [comment]
I am on Ventura 13.1 too, `openssl version` -> LibreSSL 3.3.6
With the `-sha1` flag the hash value is the same as the one mentioned on Github's blogpost

Thanks @jianbinw! I understand the issue now.

I also found an open issue and PR on aws docs related to this
https://github.com/awsdocs/iam-user-guide/issues/287

Closing this issue now.
