### ISSUE TITLE
[Enhancement]: aws_cloudfront_distribution "Continuous deployment"

### ISSUE THREAD

**Issue by ixolt** [hashicorp/terraform-provider-aws#28920]
### Description

[Amazon CloudFront](https://aws.amazon.com/cloudfront/) now supports continuous deployment, a new feature to test and validate the configuration changes with a portion of live traffic before deploying changes to all viewers.

https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-cloudfront-continuous-deployment-support/

### Affected Resource(s) and/or Data Source(s)

resource: aws_cloudfront_distribution
data source: aws_cloudfront_distribution

### Would you like to implement a fix?

No

**Comment by gudlyf** [comment]
A consideration here is that a copy of the original/primary distribution would need to be made first (https://docs.aws.amazon.com/cli/latest/reference/cloudfront/copy-distribution.html) and then a continuous deployment that references that copy and the original/primary distribution.

If a new resource `aws_cloudfront_copy_distribution` is created, it would be re-applied every time the primary/original updated, so you would want to have an `if-match` check for the specific version so it's not created every time.

**Comment by rinconjc** [comment]
I tried updating the "staging" distribution, but it failed with something like:
`Error: updating CloudFront Distribution (xxxx): IllegalUpdate: One or more fields updated are not supported for continuous deployment.
`
Not sure exactly what fields are not allowed to update.
