### ISSUE TITLE
[New Resource]: aws_organizations_delegation_policy

### ISSUE THREAD

**Issue by SolLepel** [hashicorp/terraform-provider-aws#28929]
### Description

Since November 2022 AWS Supports the delegation of Organizational policy management, such as management of SCPs or back up policies, allowing decentralized governing of your AWS Organization.

The policy resource is different from `aws_organizations_policy` since its not created by `organizations:CreatePolicy` but through `organizations:PutResourcePolicy`.  
And  it also doesnt seem to require an attachment for it to take effect.

### Requested Resource(s) and/or Data Source(s)

* aws_organizations_delegation_policy
or
* aws_organizations_resource_policy

### Potential Terraform Configuration

```terraform
resource "aws_organizations_delegation_policy" "example" {
  name = "example"
  content = <<CONTENT
{
"Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Fully_manage_backup_policies",
            "Effect": "Allow",
            "Principal": {
                "AWS": "135791357913"
            }
            "Action": [
                "organizations:DescribeOrganization",
                "organizations:ListAccounts",
                "organizations:CreatePolicy",
                "organizations:DescribePolicy",
                "organizations:UpdatePolicy",
                "organizations:DeletePolicy",
                "organizations:AttachPolicy",
                "organizations:DetachPolicy"
            ],
            "Resource": [
                "arn:aws:organizations::246802468024:root/o-abcdef/r-pqrstu",
                "arn:aws:organizations::246802468024:ou/o-abcdef/*",
                "arn:aws:organizations::246802468024:account/o-abcdef/*",
                "arn:aws:organizations::246802468024:organization/policy/backup_policy/*",
            ],
            "Condition": {
                "StringLikeIfExists": {
                    "organizations:PolicyType": [
                        "BACKUP_POLICY"
                    ]
                }
            }
        }
    ]
}
CONTENT
}
```

### References

https://aws.amazon.com/about-aws/whats-new/2022/11/aws-organizations-delegated-administrator/
https://docs.aws.amazon.com/organizations/latest/userguide/orgs_delegate_policies.html
https://docs.aws.amazon.com/cli/latest/reference/organizations/put-resource-policy.html

### Would you like to implement a fix?

None

**Comment by lorengordon** [comment]
This would be a very useful feature. It's the only way to allow a principal in a member account to view the SCPs.
