### ISSUE TITLE
[Docs]: Resource: aws_securityhub_standards_subscription

### ISSUE THREAD

**Issue by freddo256** [hashicorp/terraform-provider-aws#28954]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_standards_subscription

### Description

`arn:aws:securityhub:${var.region}::ruleset/cis-aws-foundations-benchmark/v/1.4.0` is wrong, this changed to `arn:aws:securityhub:${var.region}::standards/cis-aws-foundations-benchmark/v/1.4.0`.

### References

I can't find any references online. I used the `aws securityhub get-enabled-standards` aws-cli command.

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @freddo256 👋 Thank you for taking the time to raise this! It looks like you're [absolutely correct](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-cis1.4-vs-cis1.2.html#cisv1.4.0-finding-fields). I see that you indicated you'd like to implement a fix -- are you looking to open the pull request to adjust the documentation, or would you prefer I do so?

**Comment by acwwat** [comment]
Apologies, I introduced the incorrect ARN via #28522. I have double checked the ARN and will fix it with another PR.

Also, the [official AWS documentation](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-cis1.4-vs-cis1.2.html#cisv1.4.0-finding-fields) also had an incorrect. There should only be one `:` between `aws` and `securityhub`.
