### ISSUE TITLE
[Docs]: aws_s3_bucket_server_side_encryption_configuration rule

### ISSUE THREAD

**Issue by lgarbo** [hashicorp/terraform-provider-aws#28950]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_server_side_encryption_configuration#rule

### Description

`bucket_key_enabled` key is missing from the rule configuration block

### References

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-serversideencryptionrule.html#cfn-s3-bucket-serversideencryptionrule-bucketkeyenabled

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @lgarbo 👋 Thank you for taking the time to raise this! My understanding of the way that the docs are currently configured is that the bucket in the example is using [AWS KMS vs S3 Bucket Keys](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingKMSEncryption.html), and so the `bucket_key_enabled` argument need not be passed. Is there perhaps a reason that I'm missing for including that argument?

**Comment by justinretzolk** [comment]
Since we haven't heard back in a while, I'm going to close this issue out. If you feel I've misunderstood, please feel free to open a new issue, referencing this one for added context.
