### ISSUE TITLE
[Enhancement]: AWS Network Firewall - Reject action for TCP traffic

### ISSUE THREAD

**Issue by nicoaws** [hashicorp/terraform-provider-aws#28957]
### Description

AWS Network firewall reject action for TCP traffic

### Affected Resource(s) and/or Data Source(s)

* aws_networkfirewall_rule_group
* aws_networkfirewall_firewall_policy

### References

[https://aws.amazon.com/about-aws/whats-new/2023/01/aws-network-firewall-support-reject-action-tcp-traffic/](https://aws.amazon.com/about-aws/whats-new/2023/01/aws-network-firewall-support-reject-action-tcp-traffic/)

### Would you like to implement a fix?
This is likely to require just a change of docs and tests as the validation of the stateful action strings is delegated to the AWS Go SDK who is updated to reflect the support for `reject` and that the later versions of the provider include.

**Comment by ddericco** [comment]
I can take a look at this.
