### ISSUE TITLE
[Enhancement]: Add region support for aws_cloudwatch_metric_alarm 

### ISSUE THREAD

**Issue by cl0udf0x** [hashicorp/terraform-provider-aws#28971]
### Description

Hi, 

I'm not particularly familiar with the Terraform code base so apologies if I'm going about this the wrong way!

- It would be really helpful to be able to specify the `region` when creating alarms using the resource `aws_cloudwatch_metric_alarm`.  

- When implementing Cross-account cross-Region dashboards and alarms there is no way to specify the the region for the metrics that the alarm uses and it defaults to the region of the central dashboarding and alarm AWS account.

 - This isn't an issue with the `aws_cloudwatch_dashboard` resource its possible to specify the region in the template of the dashboard, like this:

```
    "properties": {
                "metrics": [
                    [ "AWS/ApplicationELB", "RequestCount", "LoadBalancer", "${alb}", { "accountId": "${account}" } ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${region}",
                "stat": "Sum",
                "period": 300,
                "title": "RequestCount"
```

- `region` isn't present [in the `aws_cloudwatch_metric_alarm` source code](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/cloudwatch/metric_alarm.go).  

- There is an option in the [AWS CLI to specify `region`](https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/put-metric-alarm.html), which overrides config/env settings.  If its supported by AWS API then can it be supported by the `aws_cloudwatch_metric_alarm` resource?

### Affected Resource(s) and/or Data Source(s)

aws_cloudwatch_metric_alarm

### Potential Terraform Configuration

```terraform
resource "aws_cloudwatch_metric_alarm" "rds_cpu_utilisation" {
  alarm_name                = "High_CPU_Utilisation_RDS_mydatabase"
  comparison_operator       = "GreaterThanThreshold"
  evaluation_periods        = "3"
  threshold                 = "70"
  alarm_description         = "The High CPU Utilisation threshold has been breached."
  insufficient_data_actions = []
  treat_missing_data        = "breaching"
  alarm_actions = [
    aws_sns_topic.myalarm.arn
  ]

  metric_query {
    id          = "m1"
    return_data = "true"
    account_id  = "xxxxxxxx"
    
    metric {
      region = "us-east-1"
      metric_name = "CPUUtilization"
      namespace   = "AWS/RDS"
      period      = "60"
      stat        = "Maximum"
      dimensions = {
        
        DBInstanceIdentifier = "mydatabase"
      }
    }
  }
}
```

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_metric_alarm

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_dashboard

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_xaxr_dashboard.html

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @cl0udf0x 👋 Thank you for taking the time to raise this! The way that you would go about this with the AWS Provider for Terraform would be to use [multiple provider instances with an `alias`](https://developer.hashicorp.com/terraform/language/providers/configuration#alias-multiple-provider-configurations). This might look something like:

```terraform
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

provider "aws" {
  # not declaring an alias here so that us-east-1 is the "default"
  region = "us-east-1"
}

provider "aws" {
  alias = "usw1"
  region = "us-west-1"
}
```

When you create a resource that you'd like to have in a different region, you'd then reference this provider alias:

```terraform
resource "aws_cloudwatch_metric_alarm" "rds_cpu_utilisation" {
  provider = aws.usw1
  # other configuration
}
```
