### ISSUE TITLE
[New]: Add aws_networkmanager_connect_peer resource

### ISSUE THREAD

**Issue by vbobrov** [hashicorp/terraform-provider-aws#28987]
### Description

Hello,
The provider is missing the resource to create CloudWAN Connect Attachment Peer.
There's a resource to create the attachment: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_connect_attachment already.
Connect Peer resource is available in AWSCC provider and it would be good to have it natively supported in AWS provider.
AWSCC resources is documented here: https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/networkmanager_connect_peer

Thank you

### Requested Resource(s) and/or Data Source(s)

aws_networkmanager_connect_peer

### Potential Terraform Configuration

```terraform
resource "aws_networkmanager_connect_peer" "example" {
  connect_attachment_id = aws_networkmanager_connect_attachment.example.id
  inside_cidr_blocks = ["169.254.254.0/29"]
  peer_address = aws_network_interface.example.private_ip
  bgp_options = {
    peer_asn = 65001
  }
}
```

### Would you like to implement a fix?

No

**Comment by juhala-aws** [comment]
I will start working on this issue.
