### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by SteveTalt** [hashicorp/terraform-provider-aws#28995]
### Description

Although its supported in the route53 api, you cannot currently specify more than one target ip in  a resolver rule.    The aws_route53_resolver_rule only takes a single value for target ip 

```resource "aws_route53_resolver_rule" "fwd" {
  domain_name          = "example.com"
  name                 = "example"
  rule_type            = "FORWARD"
  resolver_endpoint_id = aws_route53_resolver_endpoint.foo.id

  target_ip {
    ip = "123.45.67.89"
    port = 53
  }

  tags = {
    Environment = "Prod"
  }
}
```

The [api](https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ResolverRule.html) takes a array of ip addresses as input

### Affected Resource(s) and/or Data Source(s)

aws_route53_resolver_rule

### Potential Terraform Configuration

```terraform
resource "aws_route53_resolver_rule" "fwd" {
  domain_name          = "example.com"
  name                 = "example"
  rule_type            = "FORWARD"
  resolver_endpoint_id = aws_route53_resolver_endpoint.foo.id

  target_ip [
   {
     ip = "123.45.67.89"
     port = 53
   },
   {
     ip = "123.45.67.90"
     port = 53
   },
  ]
  tags = {
    Environment = "Prod"
  }
}
```

### References

API Reference - https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ResolverRule.html

### Would you like to implement a fix?

None

**Comment by lvthillo** [comment]
@SteveTalt I think you should use:

```
resource "aws_route53_resolver_rule" "fwd" {
  domain_name          = "example.com"
  name                 = "example"
  rule_type            = "FORWARD"
  resolver_endpoint_id = aws_route53_resolver_endpoint.foo.id

  target_ip {
    ip   = "123.45.67.89"
    port = 53
  }

  target_ip {
    ip   = "123.45.67.90"
    port = 53
  }

  tags = {
    Environment = "Prod"
  }
}
```

It's also used like that [in some tests](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/route53resolver/rule_test.go#L475-L494).

**Comment by SteveTalt** [comment]
True enough @lvthillo.    And it actually does specify block(s) in the documentation.    May just be good to have the example include more than one target in the documentation (since it is unlikely most people aren't specifying two).
