### ISSUE TITLE
[Enhancement]: aws_appflow_flow missing AWS Glue Data Catalog integration support 

### ISSUE THREAD

**Issue by sanchetanparmar** [hashicorp/terraform-provider-aws#29007]
### Description

Amazon AppFlow now supports AWS Glue Data Catalog integration and that can be setup from console but Glue integration not available form terraform  `aws_appflow_flow` resource. 

Cataloging the data output from an Amazon AppFlow flow from [console](https://docs.aws.amazon.com/appflow/latest/userguide/flows-catalog.html)
same is not available on terraform [appflow_flow](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appflow_flow)

### Affected Resource(s) and/or Data Source(s)

aws_appflow_flow

### Would you like to implement a fix?

None

**Comment by tusharpandit18** [comment]
Hi, When will this be available via terraform?

**Comment by alexpotv** [comment]
Also looking for an estimated date for a fix. Thank you!

**Comment by Zeeshan-Hashicorp-Git** [comment]
any update on this
