### ISSUE TITLE
[Bug]: effective_start on aws_ce_cost_category only applied if no other changes

### ISSUE THREAD

**Issue by gavinclarkeuk** [hashicorp/terraform-provider-aws#29044]
### Terraform Core Version

1.3.7

### AWS Provider Version

4.50.0

### Affected Resource(s)

aws_ce_cost_category recently had a change in https://github.com/hashicorp/terraform-provider-aws/issues/28009 to make the effective_start_date settable, rather than read only. It seems that this only works if there are no other changes to the cost category.

If there are changes to the rule then the effective start date is just set to the beginning of the current month, a second `terraform apply` with no further changes will correctly update the effective start date.

### Expected Behavior

The effective start date should be set even when there are category rule changes

### Actual Behavior

If there are rule changes the effective start date is set to the start of the current month (the default)

### Terraform Configuration Files

```
resource "aws_ce_cost_category" "backstage_cost_categories" {
  name         = "MyRule"
  rule_version = "CostCategoryExpression.v1"
  effective_start = "2022-06-01T00:00:00Z"

  rule {
    type = "INHERITED_VALUE"
    inherited_value {
      dimension_name = "TAG"
      dimension_key  = "MyTag"
    }
  }
}
```

### Steps to Reproduce

Change the logic in the `rule` section and reapply the terraform, you will see the category start date is not set to the one provided. Reapply and the start date will be correct.

### Would you like to implement a fix?

None

**Comment by bebold-jhr** [comment]
I can confirm this for provider version 4.56.0 and 1.4.0.
If we change the ruleset we have to apply a second time. Otherwise the effective start date is set to the start of the current month.
