### ISSUE TITLE
[Enhancement]: S3 -Intelligent Tiering - tiering argument is mandatory

### ISSUE THREAD

**Issue by mayankbigm** [hashicorp/terraform-provider-aws#29052]
### Description

As per the AWS documentation, tiering object should be optional as both Archive_Access and Deep_Archive_Access as mentioned as optional. However in Terraform this is marked as mandatory.

AWS documentation: https://docs.aws.amazon.com/AmazonS3/latest/userguide/intelligent-tiering-overview.html
Terraform documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_intelligent_tiering_configuration#tiering

Can someone please confirm if this is a bug in Terraform & assist here.

_More Context:_ In my use case, I want to use S3-IT to optimize the cost involved without loosing the millisecond object retrieval time. I have a separate lifecycle argument to delete the objects grater than 7 years of age from S3.

### Affected Resource(s) and/or Data Source(s)

aws_s3_bucket_intelligent_tiering_configuration
aws_s3_bucket

### Potential Terraform Configuration

```terraform
resource "aws_s3_bucket_intelligent_tiering_configuration" "example-entire-bucket" {
  bucket = aws_s3_bucket.example.bucket
  name   = "EntireBucket"
}
# Above ideally should be valid terraform
```

### References

AWS documentation: https://docs.aws.amazon.com/AmazonS3/latest/userguide/intelligent-tiering-overview.html
Terraform documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_intelligent_tiering_configuration#tiering

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @mayankbigm 👋 Thank you for taking the time to raise this! According to the [API documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketIntelligentTieringConfiguration.html#API_PutBucketIntelligentTieringConfiguration_RequestSyntax), the way that Terraform currently behaves alines with AWS requirements. My understand of this resource is that you would use it to activate the Archive Access and Deep Archive Access tiers, while the other tiers are enabled by default.

I hope that information helps! If you have any follow up questions, please do let me know.

**Comment by mayankbigm** [comment]
Thanks @justinretzolk . This helps.

**Comment by justinretzolk** [comment]
Glad to be of assistance @mayankbigm! With that in mind, I'll close this issue out. If you feel I've done this in error, please do let me know.
