### ISSUE TITLE
[Bug]: The provider hashicorp/aws does not support resource type "aws_ssm_default_patch_baseline"

### ISSUE THREAD

**Issue by yvak900** [hashicorp/terraform-provider-aws#29069]
### Terraform Core Version

v1.2.9

### AWS Provider Version

<=4.32.0

### Affected Resource(s)

resource "aws_ssm_default_patch_baseline"
The provider hashicorp/aws does not support resource type "aws_ssm_default_patch_baseline".

### Expected Behavior

It should set the existing patch baseline to default

### Actual Behavior

It is throwing an error stating "un supported resource"

### Terraform Configuration Files

```terraform
resource "aws_ssm_default_patch_baseline" "example" {
  baseline_id      = aws_ssm_patch_baseline.example.id
  operating_system = aws_ssm_patch_baseline.example.operating_system
}

resource "aws_ssm_patch_baseline" "example" {
  name             = "example"
  approved_patches = ["KB123456"]
}
```

**Reference:**
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_default_patch_baseline
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_patch_baseline

### Steps to Reproduce

"terraform plan" on above configuration file results in following error.

```shell
│ Error: Invalid resource type
│
│   on patch-base-line.tf line 34, in resource "aws_ssm_default_patch_baseline" "example":
│   34: resource "aws_ssm_default_patch_baseline" "example" {
│
│ The provider hashicorp/aws does not support resource type "aws_ssm_default_patch_baseline".
```

### Would you like to implement a fix?

None

**Comment by ericrichtert** [comment]
That resource does not exist in version 2.9.8. Why are you on such an old version?

**Comment by yvak900** [comment]
> That resource does not exist in version 2.9.8. Why are you on such an old version?

The aws provider version we are currently using is "<=4.32.0"

**Comment by yvak900** [comment]
Checked the same with latest aws provider version "4.51.0". Working fine. Thanks @ericrichtert for your quick and valuable response.

**Comment by justinretzolk** [comment]
Hey @yvak900 👋 The `aws_ssm_default_patch_baseline` resource was added to the provider in [version 4.38.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#4380-november--3-2022), so you'll need to upgrade to at least that version to use the resource.
