### ISSUE TITLE
[Docs]: aws_rds_cluster availability_zones count

### ISSUE THREAD

**Issue by ArturFortunato** [hashicorp/terraform-provider-aws#29067]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster

### Description

`availability_zones` documentation should mention that you can only select 3 AZs.

Something like:

[availability_zones](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#availability_zones) - (Optional) List of EC2 Availability Zones for the DB cluster storage where DB cluster instances can be created. RDS automatically assigns 3 AZs. If less than 3 AZs are configured, which will show as a difference requiring resource recreation next Terraform apply. We recommend specifying 3 AZs or using [the lifecycle configuration block ignore_changes argument](https://www.terraform.io/docs/configuration/meta-arguments/lifecycle.html#ignore_changes) if necessary. A maximum of 3 AZs can be configured.

### Would you like to implement a fix?

No

**Comment by conorshortt** [comment]
I would like to try to work on this and submit a PR later
