### ISSUE TITLE
[Bug]: Breaking change in route53 record for alias setting

### ISSUE THREAD

**Issue by lovrek93** [hashicorp/terraform-provider-aws#29072]
### Terraform Core Version

1.0.9

### AWS Provider Version

4.51.0

### Affected Resource(s)

aws_route53_record

### Expected Behavior

Alias configuration in TF should create Alias configuration.

### Actual Behavior

Getting following error:
```
Error: Too many alias blocks

  on 25-records.tf line 26, in resource "aws_route53_record" "records":
  26:     content {

No more than 1 "alias" blocks are allowed
```

### Relevant Error/Panic Output Snippet

```shell
Error: Too many alias blocks

  on 25-records.tf line 26, in resource "aws_route53_record" "records":
  26:     content {

No more than 1 "alias" blocks are allowed
```

### Terraform Configuration Files

```
"records":{
"test": {
      "name": "test.cdn",
      "type": "A",
      "alias": {
        "fqdn": "example.net.",
        "zone_id": "zoneID",
        "evaluate_target_health": false
      }
    }
}
```
```
  # Alias configuration
  dynamic "alias" {
    iterator = al
    for_each = lookup(var.records[each.key], "alias", {})
    content {
      name                   = lookup(var.records[each.key].alias, "fqdn", null)
      zone_id                = lookup(var.records[each.key].alias, "zone_id", null)
      evaluate_target_health = lookup(var.records[each.key].alias, "evaluate_target_health", null)
    }
  }
```

### Steps to Reproduce

Adding a new record with alias configuration and using newest AWS provider gives the error.

### Important Factoids

This happens only on version 4.51.0 (works on all prior versions).
I found [this](https://github.com/hashicorp/terraform-provider-aws/issues/28771) issue that mentions the breaking change in file [internal/service/route53/record.go](https://github.com/hashicorp/terraform-provider-aws/commit/a1a4f4794b84ab838f0cb9ea070536d0bdf9586b#diff-ea0b4cb951d5a64709edf239caa5a3263bfef74447da3d24159e4fb151704c32) on line 91
It seems to me that this breaking change was already implemented in version 4.51.0 and hence this problem is happening. 
My advice would be revert "alias" for record to previous configuration (like on 4.50.0 for example).

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Changed in https://github.com/hashicorp/terraform-provider-aws/pull/28894.

**Comment by gdavison** [comment]
Hi @lovrek93, thank you for submitting this. The provider was previously failing silently when more than one `alias` block was submitted.

It looks like you're trying to conditionally create the `alias` block if the record in the variable contains an `alias`. Based on the error message returned by Terraform, it looks like the `for_each` statement is returning more than one record.

I've tried debugging this, but I'm not able to simply place the `dynamic` block in an `aws_route53_record` resource because it does not parse. Could you please update this issue with the full `aws_route53_record` resource?

**Comment by gdavison** [comment]
Since we haven't heard back in several months, I'm going to close this issue. If you are still encountering the problem, please open a new issue.
