### ISSUE TITLE
[Bug]: IAM ARN not supported by the provider

### ISSUE THREAD

**Issue by albertollamaso** [hashicorp/terraform-provider-aws#29081]
### Terraform Core Version

1.3.3

### AWS Provider Version

4.51.5

### Affected Resource(s)

aws_iam_policy_document

### Expected Behavior

Terraform don't complaint when using ARN `arn:aws:iam::account:u2f/u2f-token-id`

### Actual Behavior

When applying a an IAM policy.
resource: `aws_iam_policy_document`

using the following resource is not allowed: `arn:aws:iam::account:u2f/u2f-token-id`

Terraform error is:

```shell
Error: updating IAM policy arn:aws:iam::111111111111:policy/IAMSelfManage: MalformedPolicyDocument: IAM resource path must either be "*" or start with user/, federated-user/, role/, group/, instance-profile/, mfa/, server-certificate/, policy/, sms-mfa/, saml-provider/, oidc-provider/, report/, access-report/. status code: 400, request id: XXXXXXXX-XXXXXXX-XXXXXXXf
with aws_iam_policy.iam_self_modify
on main.tf line XX, in resource "aws_iam_policy" "my_policy":
```

### Relevant Error/Panic Output Snippet

```shell
Error: updating IAM policy arn:aws:iam::111111111111:policy/IAMSelfManage: MalformedPolicyDocument: IAM resource path must either be "*" or start with user/, federated-user/, role/, group/, instance-profile/, mfa/, server-certificate/, policy/, sms-mfa/, saml-provider/, oidc-provider/, report/, access-report/. status code: 400, request id: XXXXXXXX-XXXXXXX-XXXXXXXf
with aws_iam_policy.iam_self_modify
on main.tf line XX, in resource "aws_iam_policy" "my_policy":
```

### Terraform Configuration Files

```terraform
data "aws_iam_policy_document" "my_policy" {

  statement {
    sid    = "AllowManageOwnVirtualMFADevice"
    effect = "Allow"

    actions = [
      "iam:CreateVirtualMFADevice",
    ]

    resources = [
      "arn:aws:iam::*:mfa/*",
      "arn:aws:iam::*:u2f/*"
    ]
  }
}
```

### Steps to Reproduce

Try to use resource `arn:aws:iam::account:u2f/u2f-token-id` in a `aws_iam_policy_document`

example:

```terraform
data "aws_iam_policy_document" "my_policy" {

  statement {
    sid    = "AllowManageOwnVirtualMFADevice"
    effect = "Allow"

    actions = [
      "iam:CreateVirtualMFADevice",
    ]

    resources = [
      "arn:aws:iam::*:mfa/*",
      "arn:aws:iam::*:u2f/*"
    ]
  }
}
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @albertollamaso 👋 Thanks for taking the time to raise this! It looks like the error you're getting is coming from the AWS API, so I took a look around, and I'm not certain that it's expected to be able to use `u2f/` as the starting bit of the resource path. Reviewing the following AWS documents ([first][1], [second][2], [third][3]), there's similar IAM policy documents that seem to be aimed at achieving similar functionality to you, but only use the `mfa/` start.

That said, if you have information that I didn't find, I'd be happy to mark this as a bug so that the team can take a look when this gets prioritized.

[1]: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_enable_fido.html
[2]: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_aws_my-sec-creds-self-manage-mfa-only.html
[3]: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_aws_my-sec-creds-self-manage.html

**Comment by albertollamaso** [comment]
hi @justinretzolk thanks for taking a look. [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html) you can see this is part of the supported IAM ARNs.

**Comment by gdavison** [comment]
Hi @albertollamaso, it appears that an IAM ARN containing `u2f/` is a valid ARN according to the [documentation that you pointed to](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html#identifiers-arns). However, according to the error message returned by the AWS IAM API,

> Error: updating IAM policy arn:aws:iam::111111111111:policy/IAMSelfManage: MalformedPolicyDocument: IAM resource path must either be "*" or start with user/, federated-user/, role/, group/, instance-profile/, mfa/, server-certificate/, policy/, sms-mfa/, saml-provider/, oidc-provider/, report/, access-report/. status code: 400, request id: XXXXXXXX-XXXXXXX-XXXXXXXf
with aws_iam_policy.iam_self_modify

an ARN containing `u2f/` cannot be used in an IAM policy document. The error message gives the list of ARN types that can be used, and it is not in this list.

The AWS documentation includes instructions for enabling FIDO (U2F) keys: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_enable_fido.html. Note that in this case, the associated resource ARN is for the user, not the key types themselves. Also note that the same documentation says that U2F has been deprecated.
