### ISSUE TITLE
[Docs]: aws_eks_cluster.<id>.name attribute is undocumented

### ISSUE THREAD

**Issue by danielBingham** [hashicorp/terraform-provider-aws#29095]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster

### Description

The `name` attribute of the `aws_eks_cluster` resource exists (at least in version 4 of the provider) and appears to be equal to the `id` attribute, but is absent from the documentation.

### Would you like to implement a fix?

None

**Comment by mattburgess** [comment]
Hi @danielBingham. The way the documentation is structured means it differentiates between "Arguments" (things you supply in the resource definition to create the resource) and `Attributes` (things that are provided back to you, in addition to what you specify, that the AWS resource has set when creating the resource). As the `name` is something that you need to supply, it's defined under `Argument Reference` on the page you link to:

> [name](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#name) – (Required) Name of the cluster. Must be between 1-100 characters in length. Must begin with an alphanumeric character, and must only contain alphanumeric characters, dashes and underscores (^[0-9A-Za-z][A-Za-z0-9\-_]+$).

For brevity, and to avoid the 2 lists diverging, the Arguments aren't repeated under Attributes even though they're obviously provided back for reading/querying after resource creation.

**Comment by danielBingham** [comment]
That makes sense, and I can see that reasoning. And now that I'm looking for it, I see: 

> In addition to all arguments above

Short of duplicating the documentation, I can't think of a way to make that more obvious.  I just missed it.  Thanks for clarifying!
