### ISSUE TITLE
[Bug]: "aws_api_gateway_integration" keeps reporting 'connection_type = "INTERNET"' change for MOCK integrations

### ISSUE THREAD

**Issue by mkielar** [hashicorp/terraform-provider-aws#29090]
### Terraform Core Version

1.3.1

### AWS Provider Version

4.51.0

### Affected Resource(s)

* `aws_api_gateway_integration`

### Expected Behavior

Terraform should not continously show `MOCK` type integrations as subject to change.

### Actual Behavior

Regardless of which configuration option (see below) we use for the resource, `terraform plan` always shows this bit:

```
  # module.[REDACTED].module.api_gateway_private[0].module.dummy_resource.aws_api_gateway_integration.this will be updated in-place
  ~ resource "aws_api_gateway_integration" "this" {
      + connection_type      = "INTERNET"
        id                   = "agi-[REDACTED]-ANY"
        # (10 unchanged attributes hidden)
    }
```

### Relevant Error/Panic Output Snippet

```shell
N/A
```

### Terraform Configuration Files

Initially, we had this:
```
resource "aws_api_gateway_integration" "this" {
  rest_api_id = var.api_gateway_id
  resource_id = aws_api_gateway_resource.this.id
  http_method = aws_api_gateway_method.this.http_method

  type            = "MOCK"
}
```

Later, we changed it to this:
```
resource "aws_api_gateway_integration" "this" {
  rest_api_id = var.api_gateway_id
  resource_id = aws_api_gateway_resource.this.id
  http_method = aws_api_gateway_method.this.http_method

  type            = "MOCK"
  connection_type = "INTERNET"
}
```

In both cases, the output of `terraform plan` is the same - it shows the change on the `connection_type` attribute.

### Steps to Reproduce

1. Define `aws_api_gateway_integration` resource with `MOCK` type and no `connection_type` in HCL.
2. Run `terraform apply`
3. Run `terraform plan` and observe it wants to set `connection_type` to `INTERNET`
4. Modify HCL to explicitely set `connection_type` to `INTERNET`, and run `terraform apply`
5. Run `terraform plan` again and observe it still wants to set `connection_type` to `INTERNET`

### Debug Output

N/A

### Panic Output

N/A

### Would you like to implement a fix?

None

**Comment by mkielar** [comment]
OK, this may be the same as https://github.com/hashicorp/terraform-provider-aws/issues/28997, but the `type` used there is different.

**Comment by olhrabar** [comment]
Have the same issue:

  ~ resource "aws_api_gateway_integration" "test" {
      **+ connection_type         = "INTERNET"**
        id                      = "agi-test-test-test-test"
        # (13 unchanged attributes hidden)
    }

**Comment by starrago-illuminateed** [comment]
Same issue here: 

~ resource "aws_api_gateway_integration" "test-auth-method-integration" {
      + connection_type         = "INTERNET"
        id                      = "agi-test-test-GET"
        # (12 unchanged attributes hidden)
    }
