### ISSUE TITLE
[Docs]: CIS AWS Foundations Benchmark v1.4.0 incorrect ARN

### ISSUE THREAD

**Issue by quickmute** [hashicorp/terraform-provider-aws#29100]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_standards_subscription

### Description

CIS AWS Foundations Benchmark v1.4.0 ARN in the Argument Reference is wrong. 
It is: `arn:aws:securityhub:${var.region}::ruleset/cis-aws-foundations-benchmark/v/1.4.0`
It should be: `arn:aws:securityhub:${var.region}::standards/cis-aws-foundations-benchmark/v/1.4.0`

### References

Per output from `aws securityhub describe-standards`

### Would you like to implement a fix?

None

**Comment by trevorrea** [comment]
It looks like this has already been fixed in https://github.com/hashicorp/terraform-provider-aws/pull/29031

**Comment by justinretzolk** [comment]
Hey @quickmute 👋 As mentioned above, a fix for this has been merged and will go out with the `4.52.0` release later today. With that in mind, we'll close this issue out.
