### ISSUE TITLE
[Docs]: aws_autoscaling_group - Missing 'lowest-price' valid value in the on_demand_allocation_strategy parameter description

### ISSUE THREAD

**Issue by ShaheenK27** [hashicorp/terraform-provider-aws#29124]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#on_demand_allocation_strategy

### Description

The description of **on_demand_allocation_strategy** parameter in `instances_distribution` block should be updated to include **lowest-price** in its valid values as mentioned in the AWS API/CLI reference.

### References

* **AWS CLI reference:**
[https://docs.aws.amazon.com/cli/latest/reference/autoscaling/create-auto-scaling-group.html](https://docs.aws.amazon.com/cli/latest/reference/autoscaling/create-auto-scaling-group.html)

* **AWS API reference:**
[https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_InstancesDistribution.html#API_InstancesDistribution_Contents](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_InstancesDistribution.html#API_InstancesDistribution_Contents)

### Would you like to implement a fix?

None

**Comment by rahul-amzn** [comment]
will take look.
