### ISSUE TITLE
[Docs]: aws_glue_job: PythonVersion 3.9 is not supported

### ISSUE THREAD

**Issue by devchakraborty** [hashicorp/terraform-provider-aws#29123]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_job

### Description

Documentation for `aws_glue_job` specifies that the allowed values for `python_version` are "2", "3" (for 3.6), and "3.9". However the Glue API returns an error when you try to set `python_version = "3.9"`:

```
Error: creating Glue Job (test): InvalidInputException: PythonVersion 3.9 is not supported. Choose from one of the following: [2, 3]
```

### References

The error I'm seeing is consistent with the Glue API documentation: https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-jobs-job.html#aws-glue-api-jobs-job-JobCommand

### Would you like to implement a fix?

No

**Comment by StephenDunne97** [comment]
Hello, I would like to work on this issue. I can open a PR for the solution later.

**Comment by justinretzolk** [comment]
Hey @devchakraborty 👋 Thank you for taking the time to raise this! I did note that in the Go SDK reference, it's mentioned that [only `2` or `3` are supported](https://docs.aws.amazon.com/sdk-for-go/api/service/glue/#JobCommand), however, I wasn't able to reproduce the issue when using the provider despite attempting to use `2`, `3`, and `3.9`, and running the [acceptance test](https://github.com/hashicorp/terraform-provider-aws/blob/1627fe4817d0f6c6026e20ced96dff13c723c307/internal/service/glue/job_test.go#L660).

Can you verify what version of the AWS Provider you're using and provide a working Terraform reproduction and/or debug logs (redacted as needed)?

**Comment by gdavison** [comment]
Hi @devchakraborty and @StephenDunne97. Adding to what @justinretzolk asked, can you also let us know what region you're using? Sometimes features are not enabled consistently across all regions.

**Comment by raphaelauv** [comment]
No problem on my side for a `pythonshell` with `pythonshell` in  `3.9`

**Comment by pdxcardinal78** [comment]
I am seeing this issue myself. Currently using terraform version 1.4.2 and AWS Provider 4.59.0
Do we have any idea why it works for some and not others?

**Comment by raphaelauv** [comment]
it work for me with 
TF `1.3.8`
hashicorp/aws `v4.59.0`

```yaml
provider "aws" {
  region = "eu-west-1"
}
```

**Comment by pdxcardinal78** [comment]
> it work for me with TF `1.3.8` hashicorp/aws `v4.59.0`
> 
> ```yaml
> provider "aws" {
>   region = "eu-west-1"
> }
> ```

Apart from the region, I tried to use the same TF version and provider version and it didn't work. Thanks for the info though.

**Comment by raphaelauv** [comment]
```hcl
  command {
    name = "pythonshell"
    script_location = "..."
    python_version = "3.9"
  }
  glue_version = "3.0"
}
```
