### ISSUE TITLE
[Bug]: Missing argument for RDS Proxy on Postgres -- need Client Authentication type so Postgresl md5 can be selected

### ISSUE THREAD

**Issue by davisb2** [hashicorp/terraform-provider-aws#29138]
### Terraform Core Version

4.52.0

### AWS Provider Version

4.52.0

### Affected Resource(s)

RDS proxy for Postgres

A argument is needed to you can specify client authetication type

### Expected Behavior

To be able to  specify client authetication type

### Actual Behavior

Missing argument so the client authentication type for authentication in rds proxy always defaults to SCRAM

### Terraform Configuration Files

No logs--just missing argument

### Steps to Reproduce

No step--just missing argument

### Debug Output

No debug output --just missing argument

### Panic Output

No panic output--just missing argument

### Would you like to implement a fix?

None

**Comment by trevorrea** [comment]
@davisb2 - this was added in 4.55.0 so this issue can be closed. 

See https://github.com/hashicorp/terraform-provider-aws/blob/v4.55.0/CHANGELOG.md for details.
