### ISSUE TITLE
[Bug]: RDS cluster gets replaced every time when specifying availability zones.

### ISSUE THREAD

**Issue by Magicloud** [hashicorp/terraform-provider-aws#29149]
### Terraform Core Version

v1.3.7

### AWS Provider Version

~> 4.0

### Affected Resource(s)

aws_rds_cluster

### Expected Behavior

After first creation, the project should be able to be applied any more times without any changes.

### Actual Behavior

Every time I apply the same (without modification) Terraform project, the RDS instance and cluster are requested to be replaced.

### Relevant Error/Panic Output Snippet

```shell
# aws_rds_cluster.perps-main must be replaced
-/+ resource "aws_rds_cluster" "perps-main" {
...
      ~ availability_zones                  = [ # forces replacement
          - "eu-west-3c",
            # (2 unchanged elements hidden)
        ]
...

  # aws_rds_cluster_instance.perps-main[0] must be replaced
-/+ resource "aws_rds_cluster_instance" "perps-main" {
...
      ~ cluster_identifier                    = "perps-main" -> (known after apply) # forces replacement
```

### Terraform Configuration Files

```hcl
data "aws_availability_zones" "available" {
  state = "available"
  exclude_names = ["eu-west-3c"]
}

resource "aws_rds_cluster" "main" {
  cluster_identifier     = "main"
  availability_zones     = data.aws_availability_zones.available.names
  db_subnet_group_name   = aws_db_subnet_group.private.name
  vpc_security_group_ids = [aws_security_group.allow_pgsql.id]
  master_username        = "postgres"
  master_password        = "abcdefg"

  engine         = "aurora-postgresql"
  engine_version = "12"
}

resource "aws_security_group" "allow_pgsql" {
  name   = "allow_pgsql"
  vpc_id = locals.vpc_id

  ingress {
    from_port        = 5432
    to_port          = 5432
    protocol         = "tcp"
    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }

  egress {
    from_port        = 0
    to_port          = 0
    protocol         = "-1"
    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }
}

resource "aws_db_subnet_group" "private" {
  subnet_ids = ["subnet-0fd4420cc36cd29bb"]
}
```

### Steps to Reproduce

Apply the project once, then again.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @Magicloud 👋 Thank you for taking the time to raise this! So that we have all of the information we might need to look into this, can you supply debug logs as well (redacted as needed)?

**Comment by karl-sprig** [comment]
I am a +1 for this as well.

While drafting a post showing the behavior that I am seeing, I found another issue that seems to be a) identical to this and b) pre-dates this.

https://github.com/hashicorp/terraform-provider-aws/issues/25480

**Comment by Magicloud** [comment]
> I am a +1 for this as well.
> 
> While drafting a post showing the behavior that I am seeing, I found another issue that seems to be a) identical to this and b) pre-dates this.
> 
> #25480

Yes, I think that is the same issue.

**Comment by Magicloud** [comment]
@justinretzolk Sorry this is late. 1st.log is the debug log of creating everything. 2nd.log is the debug log of reapplying and wrongly recreating everything.
[1st.log](https://github.com/hashicorp/terraform-provider-aws/files/10713660/1st.log)
[2nd.log](https://github.com/hashicorp/terraform-provider-aws/files/10713661/2nd.log)

**Comment by justinretzolk** [comment]
👋 This looks to be the same issue that was raised in #31558. Can you review my comment [here](https://github.com/hashicorp/terraform-provider-aws/issues/31558#issuecomment-1561915878) and let me know if that resolves your issue?

**Comment by Magicloud** [comment]
@justinretzolk Thanks for the info. I guess this an annoyances from AWS. The reason I used 2 AZs instead of 3, is that the third does not support some RDS function at all. I have to get rid of it.
