### ISSUE TITLE
[Bug]: medialive encodersettings

### ISSUE THREAD

**Issue by chrjoh** [hashicorp/terraform-provider-aws#29159]
### Terraform Core Version

1.3.7

### AWS Provider Version

4.5.2

### Affected Resource(s)

* aws_medialive_channel

In the schema for ms smooth the key for audioOnlyTimecodeControl is sprcified as audio_only_timecodec_control
https://github.com/hashicorp/terraform-provider-aws/blob/ef7761e5e1421bd5d0601e09f3739b9e0629911a/internal/service/medialive/channel_encoder_settings_schema.go#L1090

and the spelling here is  audio_only_timecode_control
https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/medialive/channel_encoder_settings_schema.go#L3109

So we get the following error
```
Terraform v1.3.7
on linux_amd64
Initializing plugins and modules...
aws_security_group.sg: Refreshing state... [id=sg-03500334f2404e471]
aws_medialive_input.input-testa: Refreshing state... [id=8624773]
aws_medialive_input.input-testb: Refreshing state... [id=9597455]
aws_medialive_channel.channel-test: Refreshing state... [id=9736460]
╷
│ Error: setting AWS Elemental MediaLive Channel (9736460): Invalid address to set: []string{"encoder_settings", "0", "output_groups", "0", "output_group_settings", "0", "ms_smooth_group_settings", "0", "audio_only_timecode_control"}
│ 
│   with aws_medialive_channel.channel-test,
│   on cdk.tf.json line 563, in resource.aws_medialive_channel.channel-test:
│  563:       }
│ 
╵
Operation failed: failed running terraform plan (exit 1)
 ```
So we tried just to edit the key in generated terraform and apply to see what happened and get the following error

```
Terraform v1.3.7
on linux_amd64
Initializing plugins and modules...
╷
│ Error: Extraneous JSON object property
│ 
│   on cdk.tf.json line 126, in resource.aws_medialive_channel.channel-test.encoder_settings.output_groups[0].output_group_settings.ms_smooth_group_settings:
│  126:                   "audio_only_timecode_control": "USE_CONFIGURED_CLOCK",
│ 
│ No argument or block type is named "audio_only_timecode_control". Did you
│ mean "audio_only_timecodec_control"?
╵
Operation failed: failed running terraform plan (exit 1)
```
I think there is a spelling misstake in the schema

### Expected Behavior

the fieldname should be audio_only_timecode_control

### Actual Behavior

Since the key is spelled wrong we can not apply any chnages

### Terraform Configuration Files

we just downloaded an existing json setup from medialive
````
 const channel_config = JSON.parse(
                readFileSync(`./channel_config/${channel.file}.json`, 'utf-8'),
            )
            let encoderSetting = <MedialiveChannelEncoderSettings>channel_config['encoderSettings']

```
where we have created two of each MedialiveInput, MedialiveChannelDestinations and MedialiveChannelInputAttachments

````
            new MedialiveChannel(this, 'channel', channel.name), {
                name: channel.name,
                channelClass: 'SINGLE_PIPELINE',
                roleArn: `arn:aws:iam::${accountId}:role/MediaLiveAccessRole`,
                destinations: destinations,
                inputAttachments: attachements,
                inputSpecification: {
                    codec: 'AVC',
                    inputResolution: 'HD',
                    maximumBitrate: 'MAX_50_MBPS',
                },
                encoderSettings: encoderSetting,
                maintenance: {
                    maintenanceDay: channel.maintenance.day,
                    maintenanceStartTime: channel.maintenance.time
                }
            })

### Steps to Reproduce

just try to create a medialive channel with the follwoing outputgroup
msSmoothGroupSettings with audioOnlyTimecodecControl set to "USE_CONFIGURED_CLOCK"

### Would you like to implement a fix?

None

**Comment by stevensdavid** [comment]
This seems to me like it's caused by a spelling error in the schema definition, where the schema calls the property `audio_only_timecodec_control` (see [here](https://github.com/hashicorp/terraform-provider-aws/blob/ef7761e5e1421bd5d0601e09f3739b9e0629911a/internal/service/medialive/channel_encoder_settings_schema.go#L1090)) and the property is used as `audio_only_timecode_control` (see [here](https://github.com/hashicorp/terraform-provider-aws/blob/ef7761e5e1421bd5d0601e09f3739b9e0629911a/internal/service/medialive/channel_encoder_settings_schema.go#L3109)), note the added `c` in `timecodec`/`timecode`.
