### ISSUE TITLE
[Repo]: CHANGELOG too long

### ISSUE THREAD

**Issue by bennylu2** [hashicorp/terraform-provider-aws#29169]
### Description

If you view the changelog from Github UI, it does not display due to `This blob took too long to generate.` Not sure what plans are for this

### References

https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @bennylu2 👋 Thank you for taking the time to raise this! I've brought this up internally so that we can take a look at this.
