### ISSUE TITLE
[Bug]: Cannot import S3 folder

### ISSUE THREAD

**Issue by DerekTBrown** [hashicorp/terraform-provider-aws#29167]
### Terraform Core Version

1.3.6

### AWS Provider Version

4.52.0

### Affected Resource(s)

aws_s3_object

### Expected Behavior

- I have an S3 bucket containing a folder; `s3://my-bucket/my-folder`. 
- I have some Terraform code, designed to create a specific empty folder:

```terraform
resource "aws_s3_object" "my_empty_dir" {
  bucket       = "my-bucket"
  key             = "my-folder"
  content      = ""
  content_type = "application/x-directory"
}
```

- When I run `terraform import 'module.my-project.aws_s3_object.my_empty_dir' 's3://my-bucket/my-folder'`, I expect it to succeed. 

### Actual Behavior

I get an error, indicating that the `aws_s3_object` provider cannot find the directory.

### Relevant Error/Panic Output Snippet

```shell
│ While attempting to import an existing object to "module.my-project.aws_s3_object.my_empty_dir", the provider detected that no object exists with the given id. Only
│ pre-existing objects can be imported; check that the id is correct and that it is associated with the provider's configured region or endpoint, or use "terraform apply" to create a new remote object
│ for this resource.
╵
```

### Terraform Configuration Files

None are required.

### Steps to Reproduce

Steps are provided in bug description above.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @DerekTBrown 👋 Thank you for taking the time to raise this! I wasn't able to reproduce the issue (output below). Are you able to see the bucket/folder by running `aws s3 ls s3://my-bucket/my-folder` with the AWS CLI?

Import reproduction output:

```shell
$ terraform import 'aws_s3_object.my_empty_dir' 's3://jretzolk-20230131202515370600000001/my-folder'
aws_s3_object.my_empty_dir: Importing from ID "s3://jretzolk-20230131202515370600000001/my-folder"...
aws_s3_object.my_empty_dir: Import prepared!
  Prepared aws_s3_object for import
aws_s3_object.my_empty_dir: Refreshing state... [id=my-folder]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```
