### ISSUE TITLE
aws_vpc enable_dns_hostnames inconsistent between import and create

### ISSUE THREAD

**Issue by bchallenor** [hashicorp/terraform-provider-aws#2917]
### Terraform Version
Terraform v0.11.1
+ provider.aws v1.5.0
+ provider.template v1.0.0

### Affected Resource(s)
- aws_vpc

### Terraform Configuration Files
```hcl
resource "aws_vpc" "default" {
  cidr_block = "172.31.0.0/16"
}

resource "aws_vpc" "dmz" {
  cidr_block = "172.31.0.0/16"
}
```

### Actual Behavior
`default` already existed in my AWS account, and I imported it into terraform. `dmz` was created by terraform.

Terraform knows that they have different values for `enable_dns_hostnames`:

```
$ terraform state show aws_vpc.default | grep enable_dns_hostnames
enable_dns_hostnames             = true
$ terraform state show aws_vpc.dmz | grep enable_dns_hostnames
enable_dns_hostnames             = false
```

(and according to the AWS console these values reflect reality, i.e. terraform is reading their values correctly)

But `terraform plan` shows no changes to be made:

```
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

### Expected Behavior
`terraform plan` should reflect this as a change to be made.

### Workaround
Explicitly setting `enable_dns_hostnames = "true"` for both resources causes `terraform plan` to make the change:

```
Terraform will perform the following actions:

  ~ aws_vpc.dmz
      enable_dns_hostnames: "false" => "true"
```

**Comment by bchallenor** [comment]
As an aside, this is a nasty bug for me because I often follow this workflow when trying a new AWS service:

1. Use the AWS Console wizard to create a resource
2. Create some minimal config for it in terraform
3. Import the resource
4. Tweak the terraform config until terraform reports no changes to be made

This bug breaks my assumption that "terraform reports no changes" _only if_ "terraform config matches the real world".

So it would be interesting to know what mechanism is causing this.

**Comment by richardbowden** [comment]
I am trying to understand this problem..its not clear what the actual expected outcome should be.

the default setting for enable_dns_hostnames is false. So for DMZ this is correct, as it's not set in the terraform config, its correct.

is the issue that is not showing a change for enable_dns_hostnames from "true" to "false" for the default given the default for enable_dns_hostnames is false ??

**Comment by bchallenor** [comment]
Yes, given that they have identical config, but non-identical state for `enable_dns_hostnames`, I would expect that terraform plans a change that would bring their states into alignment. And given that the default for `enable_dns_hostnames` is false, in this case it should be `aws_vpc.default` that is changed.

**Comment by bchallenor** [comment]
In fact the bug is not specific to import. I managed to reproduce without `terraform import` as well:

 1. Create two VPCs with terraform:

```
provider "aws" {
  region = "ap-southeast-2"
}

resource "aws_vpc" "x" {
  cidr_block = "172.31.0.0/16"
}

resource "aws_vpc" "y" {
  cidr_block = "172.31.0.0/16"
}
```

 2. Manually set `enable_dns_hostnames` on one of them (i.e. `aws ec2 modify-vpc-attribute --vpc-id <id> --enable-dns-hostnames`).

 3. `terraform plan` shows no changes.

**Comment by richardbowden** [comment]
@bchallenor hey, i have submitted a PR to fix this, seems to simple of a fix, i have tested, could you give this PR a go ?

**Comment by bchallenor** [comment]
Thanks for that. I left comments on the PR.

**Comment by gdavison** [comment]
Hi @bchallenor thanks for submitting this issue and sorry for the delay in responding to it.

Since your configuration doesn't specify a value for `enable_dns_hostnames`, Terraform doesn't perform any change tracking for the parameter, so it leaves it untouched, regardless of the value returned by the AWS API. If you want to enforce a value, your configuration should specify the value you want.

When no value is supplied, the AWS API defaults the Default VPC to enabling DNS hostnames, but other VPCs do not enabled DNS hostnames, which is why you're seeing the two values returned by the API.
