### ISSUE TITLE
[New Resource]: Delegated Administrator for CloudTrail

### ISSUE THREAD

**Issue by posquit0** [hashicorp/terraform-provider-aws#29179]
### Description

- [AWS CloudTrail announces delegated administrator account support for AWS Organizations](https://aws.amazon.com/about-aws/whats-new/2022/11/aws-cloudtrail-delegated-account-support-aws-organizations/)
- AWS provides a CloudTrail API, not AWS Organization, for configuring delegated administrators.

### Requested Resource(s) and/or Data Source(s)

* aws_cloudtrail_organization_admin_account

### Potential Terraform Configuration

```terraform
resource "aws_cloudtrail_organization_admin_account" "example" {
  delegated_admin_account_id = data.aws_caller_identity.delegated.account_id
}

data "aws_caller_identity" "delegated" {
  provider = aws.ipam_delegate_account
}
```

### References

- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_ipam_organization_admin_account
- https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_RegisterOrganizationDelegatedAdmin.html

### Would you like to implement a fix?

None

**Comment by rojones94** [comment]
> ### Description
> * [AWS CloudTrail announces delegated administrator account support for AWS Organizations](https://aws.amazon.com/about-aws/whats-new/2022/11/aws-cloudtrail-delegated-account-support-aws-organizations/)
> * AWS provides a CloudTrail API, not AWS Organization, for configuring delegated administrators.
> 
> ### Requested Resource(s) and/or Data Source(s)
> * aws_cloudtrail_organization_admin_account
> 
> ### Potential Terraform Configuration
> ```terraform
> resource "aws_cloudtrail_organization_admin_account" "example" {
>   delegated_admin_account_id = data.aws_caller_identity.delegated.account_id
> }
> 
> data "aws_caller_identity" "delegated" {
>   provider = aws.ipam_delegate_account
> }
> ```
> 
> ### References
> * https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_ipam_organization_admin_account
> * https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_RegisterOrganizationDelegatedAdmin.html
> 
> ### Would you like to implement a fix?
> None


---
You can delegate admin control in the following way.

``` hcl
resource "aws_organizations_delegated_administrator" "this" {
  account_id        = "your-account-id"
  service_principal = "cloudtrail.amazonaws.com"
}
```

**Comment by posquit0** [comment]
@rojones94 No, there is a dedicated API for registering cloudtrail delegated administrator.
Your suggested AWS Organization API is not working for many AWS services.

https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-delegated-administrator.html

**Comment by jorhett** [comment]
> You can delegate admin control in the following way.
> 
> ```terraform
> resource "aws_organizations_delegated_administrator" "this" {
>   account_id        = "your-account-id"
>   service_principal = "cloudtrail.amazonaws.com"
> }
> ```

Actually, this will not work and will prevent delegation from working. Just to explain how bad this is, if you do the delegation this way it appears to work, but you can't do anything. 

If you try to run this command after applying the resource quoted above you'll see this:

```
An error occurred (AccountRegisteredException) when calling the RegisterOrganizationDelegatedAdmin operation: The specified AWS account 370208956287 is already registered as the CloudTrail delegated administrator.
```

You must delete this resource, apply the change, then run this CLI command to achieve the working solution:

```shell
$ aws cloudtrail register-organization-delegated-admin --member-account-id="123456789012"
```

This is why a new resource utilizing the Cloudtrail APIs is required.

**Comment by AugustoEMoreira** [comment]
> You can delegate admin control in the following way.
> 
> ```terraform
> resource "aws_organizations_delegated_administrator" "this" {
>   account_id        = "your-account-id"
>   service_principal = "cloudtrail.amazonaws.com"
> }
> ```

I'm curious did you have already implemented delegated admin for cloudtrail using this? If so, could you explain? Because AWS has absolutely no documentation on how to do it using the organization's APIs instead of Cloudtrail's

**Comment by AugustoEMoreira** [comment]
@posquit0 After some research, I found the solution.
When enabling delegated administrator access using Organizations API, AWS doesn't create a service-linked role to cloudtrail.
To make this work, you will need to create a new resource like this:

```terraform
resource "aws_iam_service_linked_role" "cloudtrail_service_role" {
    aws_service_name = "cloudtrail.amazonaws.com"
}

This resource should be in your root account. Also, you are going to need to set up s3's policy manually; I will assume you know how to do it, but let me know if you need further help.
