### ISSUE TITLE
[Enhancement]: AWS Glue for Ray is not supported yet

### ISSUE THREAD

**Issue by jrichard8** [hashicorp/terraform-provider-aws#29180]
### Description

It appears that currently the aws_glue_job resource does not support the new AWS GLUE for Ray feature,In particular on the selection of worker type. The resource does not support Z.2X worker type when it is required.
```
╷
│ Error: creating Glue Job: InvalidInputException: Worker type cannot be null and only [Z.2X] worker types are supported for glueray jobs.
│ 
│   with aws_glue_job.exemple,
│   on main.tf line 14, in resource "aws_glue_job" "exemple":
│   14: resource "aws_glue_job" "exemple" {
│ 
╵

```
But when we try to use Z.2X
```bash
╷
│ Error: expected worker_type to be one of [Standard G.1X G.2X G.025X], got Z.2X
│ 
│   with aws_glue_job.exemple,
│   on main.tf line 31, in resource "aws_glue_job" "exemple":
│   31:   worker_type = "Z.2X"
│ 
╵
```
Could you add support of Z.2X worker type in case of glueray job type.

### References

Official documentation: https://docs.amazonaws.cn/en_us/glue/latest/dg/ray-using.html

Extract:
```
--worker-type (WorkerType) – Ray jobs are backed by a new Amazon Graviton-based instance type. This is represented by the value Z.2X. For the Z.2X worker type, each worker maps to 2 DPU (8 vCPU, 64 GB of memory, 128 GB disk), and provides up to 8 Ray workers (one per vCPU) based on the autoscaler.
```

### Would you like to implement a fix?

None

**Comment by jrichard8** [comment]
After some research it seems that limitation come from the AWS SDK for GO itself.
I opened an issue about that on AWS SDK for GO V2:
https://github.com/aws/aws-sdk-go-v2/issues/2002

**Comment by djleeam** [comment]
@jrichard8 , it appears the AWS Glue SDK should be in a good state for this now. I can pick this up.
