### ISSUE TITLE
[Bug]: Terraform saves invalid boundary policy in its state

### ISSUE THREAD

**Issue by svashisht03** [hashicorp/terraform-provider-aws#29185]
### Terraform Core Version

0.37.0

### AWS Provider Version

4.48

### Affected Resource(s)

arn:aws:iam:::policy/platform/pipeline_boundary

### Expected Behavior

The permissions boundary should not have been updated if the policy was invalid. 

 

### Actual Behavior

Tf saved an invalid boundary policy in its state, then couldn't change it, because it did a validation. This was fixed by removing it from the state, and from AWS, which fixed this. However TF does not do a proper state refresh and didn't reattach the boundary policies. 
Changing the state to have an empty boundary policy fixed this

### Relevant Error/Panic Output Snippet

```shell
Error: while setting policy (), encountered: while checking equivalency of existing policy , encountered: parsing policy 1: parsing statement 1: 1 error(s) decoding:
│ 
│ * '[5].Condition' expected a map, got 'slice'
```

### Terraform Configuration Files

```terraform
arn"arn:aws:iam::286059767448:policy/platform/pipeline_boundary"
description""
id"dvb-dvb-testing-sbx""arn:aws:iam::286059767448:policy/platform/pipeline_boundary"
name"pipeline_boundary"
name_prefixnull
path"/platform/"
policy"{\"Statement\":[{\"Action\":\"*\",\"Effect\":\"Allow\",\"Resource\":\"*\",\"Sid\":\"AllowAdminAccess\"},{\"Action\":[\"account:*\",\"savingsplans:*\",\"tax:*\",\"invoicing:*\"],\"Effect\":\"Deny\",\"Resource\":\"*\",\"Sid\":\"DenyAccessToCostAndBilling\"},{\"Action\":[\"iam:DeletePolicy\",\"iam:DeletePolicyVersion\",\"iam:CreatePolicyVersion\",\"iam:SetDefaultPolicyVersion\"],\"Effect\":\"Deny\",\"Resource\":[\"arn:aws:iam::286059767448:policy/platform/workload_boundary\",\"arn:aws:iam::286059767448:policy/platform/pipeline_boundary\"],\"Sid\":\"DenyPermBoundaryIAMPolicyAlteration\"},{\"Action\":[\"iam:DeleteUserPermissionsBoundary\",\"iam:DeleteRolePermissionsBoundary\"],\"Condition\":{\"StringEquals\":{\"iam:PermissionsBoundary\":\"arn:aws:iam::286059767448:policy/platform/workload_boundary\"}},\"Effect\":\"Deny\",\"Resource\":[\"arn:aws:iam::286059767448:user/*\",\"arn:aws:iam::286059767448:role/*\"],\"Sid\":\"DenyRemovalOfPermBoundaryFromAnyUserOrRole\"},{\"Action\":[\"iam:PutUserPermissionsBoundary\",\"iam:PutRolePermissionsBoundary\"],\"Condition\":{\"StringNotEquals\":{\"iam:PermissionsBoundary\":\"arn:aws:iam::286059767448:policy/platform/workload_boundary\"}},\"Effect\":\"Deny\",\"Resource\":[\"arn:aws:iam::286059767448:user/*\",\"arn:aws:iam::286059767448:role/*\"],\"Sid\":\"DenyAccessIfRequiredPermBoundaryIsNotBeingApplied\"},{\"Action\":[\"iam:CreateUser\",\"iam:CreateRole\",\"iam:UpdateUser\",\"iam:UpdateRole\",\"iam:DeleteUserPolicy\",\"iam:AttachUserPolicy\",\"iam:DetachUserPolicy\"],\"Condition\":[{\"ArnNotLike\":{\"aws:PrincipalArn\":\"arn:aws:iam::867002137709:role/platform/TFEPipelineDomainmanagementDefaultPrdRole\"},\"StringNotEquals\":{\"iam:PermissionsBoundary\":\"arn:aws:iam::286059767448:policy/platform/workload_boundary\"}}],\"Effect\":\"Deny\",\"Resource\":[\"arn:aws:iam::286059767448:user/*\",\"arn:aws:iam::286059767448:role/*\"],\"Sid\":\"DenyUserAndRoleCreationWithOutPermBoundary\"},{\"Action\":[\"secretsmanager:*\"],\"Effect\":\"Deny\",\"Resource\":[\"arn:aws:secretsmanager:*:286059767448:secret/platform/*\"],\"Sid\":\"DenyUseOfEnablementPlatformSecretManagerNamespace\"},{\"Action\":[\"kms:*\"],\"Condition\":{\"ForAnyValue:StringLike\":{\"kms:ResourceAliases\":\"alias/platform/*\"}},\"Effect\":\"Deny\",\"Resource\":\"*\",\"Sid\":\"DenyUseOfEnablementPlatformKMSNamespace\"}],\"Version\":\"2012-10-17\"}"
policy_id"ANPAUFGT5U2MJI6NDKHPA"
tags{}
tags_all{}
```

### Steps to Reproduce

1. Create valid JSON permissions boundary but invalid policy
2. Update the permissions boundary attached to the IAM role
3. On running tf apply

 "Error: updating IAM policy arn:aws:iam::286059767448:policy/platform/pipeline_boundary: MalformedPolicyDocument: Syntax errors in policy."

On running again : 
 Error: while setting policy (), encountered: while checking equivalency of existing policy 
│ * '[5].Condition' expected a map, got 'slice'

4. Applied Terraform refresh , did not work. Reattaching the boundaries did not work.
5. Finally fixed it by changing the state to have an empty boundary policy. 

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @svashisht03 👋 Thank you for taking the time to raise this! Can you update the example Terraform configuration to include a working reproduction so that we can test this and verify what version of Terraform you're using?

**Comment by svashisht03** [comment]
Hi Justin,

Thanks for reaching back. 
This was the permission boundary that I attached to my IAM role , which resulted in failure. 

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowAdminAccess",
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        },
        {
            "Sid": "DenyAccessToCostAndBilling",
            "Effect": "Deny",
            "Action": [
                "account:*",
                "savingsplans:*",
                "tax:*",
                "invoicing:*"
            ],
            "Resource": "*"
        },
        {
            "Sid": "DenyPermBoundaryIAMPolicyAlteration",
            "Effect": "Deny",
            "Action": [
                "iam:DeletePolicy",
                "iam:DeletePolicyVersion",
                "iam:CreatePolicyVersion",
                "iam:SetDefaultPolicyVersion"
            ],
            "Resource": [
                "arn:aws:iam::${account_id}:policy/platform/workload_boundary",
                "arn:aws:iam::${account_id}:policy/platform/pipeline_boundary"
            ]
        },
        {
            "Sid": "DenyRemovalOfPermBoundaryFromAnyUserOrRole",
            "Effect": "Deny",
            "Action": [
                "iam:DeleteUserPermissionsBoundary",
                "iam:DeleteRolePermissionsBoundary"
            ],
            "Resource": [
                "arn:aws:iam::${account_id}:user/*",
                "arn:aws:iam::${account_id}:role/*"
            ],
            "Condition": {
                "StringEquals": {
                    "iam:PermissionsBoundary": "arn:aws:iam::${account_id}:policy/platform/workload_boundary"
                }
            }
        },
        {
            "Sid": "DenyAccessIfRequiredPermBoundaryIsNotBeingApplied",
            "Effect": "Deny",
            "Action": [
                "iam:PutUserPermissionsBoundary",
                "iam:PutRolePermissionsBoundary"
            ],
            "Resource": [
                "arn:aws:iam::${account_id}:user/*",
                "arn:aws:iam::${account_id}:role/*"
            ],
            "Condition": {
                "StringNotEquals": {
                    "iam:PermissionsBoundary": "arn:aws:iam::${account_id}:policy/platform/workload_boundary"
                }
            }
        },
        {
            "Sid": "DenyUserAndRoleCreationWithOutPermBoundary",
            "Effect": "Deny",
            "Action": [
                "iam:CreateUser",
                "iam:CreateRole",
                "iam:UpdateUser",
                "iam:UpdateRole",
                "iam:DeleteUserPolicy",
                "iam:AttachUserPolicy",
                "iam:DetachUserPolicy"
            ],
            "Resource": [
                "arn:aws:iam::${account_id}:user/*",
                "arn:aws:iam::${account_id}:role/*"
            ],
            "Condition": [
                {
                    "StringNotEquals": {
                        "iam:PermissionsBoundary": "arn:aws:iam::${account_id}:policy/platform/workload_boundary"
                    },
                    "ArnNotLike": {
                        "aws:PrincipalArn": "arn:aws:iam::867002137709:role/platform/TFEPipelineDomainmanagementDefaultPrdRole"
                    }
                }
            ]
        },
        {
            "Sid": "DenyUseOfEnablementPlatformSecretManagerNamespace",
            "Effect": "Deny",
            "Action": [
                "secretsmanager:*"
            ],
            "Resource": [
                "arn:aws:secretsmanager:*:${account_id}:secret/platform/*"
            ]
        },
        {
            "Sid": "DenyUseOfEnablementPlatformKMSNamespace",
            "Effect": "Deny",
            "Action": [
                "kms:*"
            ],
            "Resource": "*",
            "Condition": {
                "ForAnyValue:StringLike": {
                    "kms:ResourceAliases": "alias/platform/*"
                }
            }
        }
    ]
}`

**Comment by good92** [comment]
Created with TF: 1.3.9, AWS:  5.7.0
Failure Plan on update with TF: 1.4.6, AWS: 5.15.0

Error message summary:

_Error: reading IAM Role Policy -  setting policy: while checking equivalency of existing policy '[2]' expected a map, got 'slice'_

I am facing a similar issue with a broken policy statement (latest) stored in the statefile:
`
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Action": [
				"s3:GetBucketLocation",
				"s3:ListBucket",
				"s3:ListBucketMultipartUploads",
				"s3:HeadBucket"
			],
			"Effect": "Allow",
			"Resource": [
				"arn:aws:s3:::yyyyyyy",
				"arn:aws:s3:::xxxxx"
			]
		},
		{
			"Action": [
				"s3:AbortMultipartUpload",
				"s3:DeleteObject",
				"s3:GetObject",
				"s3:ListMultipartUploadParts",
				"s3:PutObjectTagging",
				"s3:GetObjectTagging",
				"s3:PutObject"
			],
			"Effect": "Allow",
			"Resource": [
				"arn:aws:s3::yyyyy/*",
				"arn:aws:s3:::xxxxxx/*"
			]
		},
		[
			{
				"Action": [
					"logs:PutLogEvents",
					"logs:CreateLogStream"
				],
				"Effect": "Allow",
				"Principal": {
					"Service": "datasync.amazonaws.com"
				},
				"Resource": [
					"*"
				],
				"Sid": "DataSyncLogsToCloudWatchLogs"
			}
		]
	]
}
`

**Comment by melvin-moreno** [comment]
I ran into this issue as well, in my case it was an inline S3 bucket policy. The Statement had also some nesting problems similar to that provided by @good92 above. I also got `expected map, got slice` error as the OP. I fixed it by removing the state, the lock, and the bucket altogether and redeploying,

**Comment by mss** [comment]
Looks like I ran into this as well (using v5.55.0). This was the run which broke the state:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.global.module.iam.aws_iam_role.this["automation-ansible"] will be updated in-place
  ~ resource "aws_iam_role" "this" {
      ~ assume_role_policy    = jsonencode(
          ~ {
              ~ Statement = [
                    {
                        Action    = "sts:AssumeRole"
                        Effect    = "Allow"
                        Principal = {
                            AWS = [
                                "arn:aws:iam::123456789012:user/org-provisioning/sl-automation",
                            ]
                        }
                        Sid       = "AllowAutomationIAMUser"
                    },
                  ~ {
                      ~ Condition = {
                          - ArnLike            = {
                              - "aws:PrincipalArn" = [
                                  - "arn:aws:iam::123456789012:role/Administrator",
                                ]
                            }
                          + "aws:PrincipalArn" = [
                              + "arn:aws:iam::123456789012:role/Administrator",
                              + "arn:aws:iam::123456789012:role/aws-reserved/sso.amazonaws.com/eu-central-1/AWSReservedSSO_ORG-Administrator_*",
                            ]
                        }
                        # (4 unchanged attributes hidden)
                    },
                ]
                # (1 unchanged attribute hidden)
            }
        )
        id                    = "sl-automation-ansible"
        name                  = "sl-automation-ansible"
        tags                  = {
        }
        # (11 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions in workspace "accounts-svc-sandbox-5-account-global"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.global.module.iam.aws_iam_role.this["automation-ansible"]: Modifying... [id=sl-automation-ansible]
╷
│ Error: updating IAM Role (sl-automation-ansible) assume role policy: operation error IAM: UpdateAssumeRolePolicy, https response error StatusCode: 400, RequestID: fa1b54dd-79bb-4b14-b7c1-d9304e8ab36c, MalformedPolicyDocument: Invalid condition prefix: aws
│ 
│   with module.global.module.iam.aws_iam_role.this["automation-ansible"],
│   on .terraform/modules/global/atmos/account-global/modules/iam/main.tf line 22, in resource "aws_iam_role" "this":
│   22: resource "aws_iam_role" "this" {
│ 
╵
exit status 1
```

**Comment by dfloresgonz** [comment]
this issue persists
