### ISSUE TITLE
[Bug]: aws_launch_template metadata_options instance_metadata_tags cannot be enabled

### ISSUE THREAD

**Issue by dossy** [hashicorp/terraform-provider-aws#29209]
### Terraform Core Version

1.3.7

### AWS Provider Version

4.51.0

### Affected Resource(s)

* aws_launch_template

### Expected Behavior

"Allow tags in metadata" in the launch template should be `enabled` when `instance_metadata_tags` in `metadata_options` is set to `enabled`.

### Actual Behavior

"Allow tags in metadata" in the launch template is unset when `instance_metadata_tags` in `metadata_options` is set to `enabled`.

### Relevant Error/Panic Output Snippet

```shell
2023-02-02T04:35:38.647Z [WARN]  Provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected new value for module.api_asg.aws_launch_template.this[0], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .metadata_options[0].instance_metadata_tags: was cty.StringVal("enabled"), but now cty.StringVal("")
```

### Terraform Configuration Files

```
resource "aws_launch_template" "test" {
  name = "asg-template"
  metadata_options {
    instance_metadata_tags = "enabled"
  }
}
```

### Steps to Reproduce

* `terraform init`
* `terraform apply`

### Important Factoids

The comment in this [this code](https://github.com/hynd/terraform-provider-aws/blob/e0407837697eeab92a051eed9f97cb9b5644da77/internal/service/ec2/launch_template.go#L1128-L1157) on line 1141 hints at the solution to the problem: if you set `metadata_options.http_endpoint` to `enabled`, then `instance_metadata_tags` being set to `enabled` works.  Otherwise, it results in the attribute being unset.

Silently ignoring the `instance_metadata_tags` setting is less than ideal - an error or at least a warning should be raised if it's set but will be ignored because `http_endpoint` is disabled.

This is especially frustrating because, according to [the documentation for aws_launch_template](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#http_endpoint), it says:

> [http_endpoint](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#http_endpoint) - (Optional) Whether the metadata service is available. Can be `"enabled"` or `"disabled"`. (Default: `"enabled"`).

However, this appears to be untrue, based on [the code](https://github.com/hynd/terraform-provider-aws/blob/e0407837697eeab92a051eed9f97cb9b5644da77/internal/service/ec2/launch_template.go#L379-L418):

```
						"http_endpoint": {
							Type:         schema.TypeString,
							Optional:     true,
							Computed:     true,
							ValidateFunc: validation.StringInSlice(ec2.LaunchTemplateInstanceMetadataEndpointState_Values(), false),
						},
```

No default value specified.

Good news is if I explicitly set `http_endpoint = "enabled"` then `instance_metadata_tags = "enabled"` works as expected/advertised.

### References

* Add support for EC2 Instance Metadata Tags #22463

### Would you like to implement a fix?

None

**Comment by good92** [comment]
It seems more linked with https://github.com/hashicorp/terraform-provider-aws/issues/25909

**Comment by w564791** [comment]
I had the same problem

**Comment by w564791** [comment]
I had the same problem with v4.56.0

**Comment by pmmalinov01** [comment]
Got the same issue.

**Comment by wzzzrd86** [comment]
I'll take a look at this
