### ISSUE TITLE
[Bug]: aws_api_gateway_integration strips lambda qualifier from invoke arn in uri parameter in 4.52.0

### ISSUE THREAD

**Issue by grimm26** [hashicorp/terraform-provider-aws#29205]
### Terraform Core Version

1.3.7

### AWS Provider Version

4.52.0

### Affected Resource(s)

* aws_api_gateway_integration

### Expected Behavior

No change in plan.

### Actual Behavior

qualifiers were stripped out of the lambda invoke arn in the `uri` parameter value. For example:

```
  # module.odi_apigw.aws_api_gateway_integration.lambda["root/execute_flow/POST"] will be updated in-place
  ~ resource "aws_api_gateway_integration" "lambda" {
        id                      = "agi-245tgrfsxve-f98hju1-POST"
      ~ uri                     = "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:666:function:cool_function-staging:staging/invocations" -> "arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:666:function:cool_function-staging/invocations"
        # (12 unchanged attributes hidden)
    }
```

### Terraform Configuration Files

...

### Steps to Reproduce

Set up an API gateway with a lambda integration with a URI that has a qualifier.

### Important Factoids

The issue happens when upgrading the provider from 4.50.0 to 4.52.0 with no other changes.

### References

I was affected by this bug, https://github.com/hashicorp/terraform-provider-aws/issues/29090, so was excited to upgrade to 4.52.0 but that has made things worse.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @grimm26 👋 Thank you for taking the time to raise this! Can you supply a sample Terraform configuration so that have an idea how you're supplying the `uri` argument and can take a look into this?

**Comment by grimm26** [comment]
I'll try to put an example together when I get off the train. API gateway terraform is complex ☹️

**Comment by grimm26** [comment]
> Hey @grimm26 👋 Thank you for taking the time to raise this! Can you supply a sample Terraform configuration so that have an idea how you're supplying the `uri` argument and can take a look into this?
> 
> Possibly related: #29115

I'm getting the uri data from the invoke_arn output of d/aws_lambda_function

**Comment by grimm26** [comment]
As I started putting together a test case, I found the issue was in a change in behavior in https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/lambda_function but not the same as mentioned in #29115 but definitely caused by https://github.com/hashicorp/terraform-provider-aws/pull/28963. Previously, providing the qualifier like so:
```
data "aws_lambda_function" "hello" {
  function_name = "hello_world"
  qualifier     = "staging"
}
```

would cause the `invoke_arn` attribute to include the qualifier since the qualifier was there as a parameter. Now, it does not include the qualifier and I have to use the `qualified_invoke_arn` attribute if I want that value. Make sense, I suppose, but it is a rather large API breakage for a minor release and there was _NO_ change in documentation.

**Comment by justinretzolk** [comment]
Thank you very much for the updated information @grimm26! It sounds like you're sorted out, but the best course of action might be to update the documentation to be a bit more clear as to what is returned with `invoke_arn` and `qualified_invoke_arn`. Does that seem like the right path forward to you as well? I'd be happy to work on that, if that's the case.

**Comment by grimm26** [comment]
> Thank you very much for the updated information @grimm26! It sounds like you're sorted out, but the best course of action might be to update the documentation to be a bit more clear as to what is returned with `invoke_arn` and `qualified_invoke_arn`. Does that seem like the right path forward to you as well? I'd be happy to work on that, if that's the case.

Yes, an indication in the documentation for the `invoke_arn` attribute that a behavior change happened starting `4.51.0`

**Comment by grimm26** [comment]
@justinretzolk I opened a PR to add a note to the documentation.
