### ISSUE TITLE
[Enhancement]: Support `kms_key_id` for `aws_cloudtrail_event_data_store` resource

### ISSUE THREAD

**Issue by posquit0** [hashicorp/terraform-provider-aws#29219]
### Description

In `create-event-data-store` API of CloudTrail, `kms_key_id` parameter is supported. However, the `aws_cloudtrail_event_data_store` resource of Terraform AWS Provider doesn't support yet.

### Affected Resource(s) and/or Data Source(s)

* `aws_cloudtrail_event_data_store`

### Potential Terraform Configuration

```terraform
resource "aws_cloudtrail_event_data_store" "this" {
  name           = "test"

  kms_key_id = ...
}
```

### References

- [CloudTrail API: create-event-data-store](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudtrail/create-event-data-store.html)

### Would you like to implement a fix?

None

**Comment by bschaatsbergen** [comment]
Thanks for raising this issue @posquit0, I'll pick this up 👍🏼
