### ISSUE TITLE
[Bug]: aws_sagemaker_domain resource has incorrect max number of SubnetIds

### ISSUE THREAD

**Issue by tonyszhang** [hashicorp/terraform-provider-aws#29225]
### Terraform Core Version

0.15.1

### AWS Provider Version

4.52.0

### Affected Resource(s)

* aws_sagemaker_domain

### Expected Behavior

aws_sagemaker_domain is created with 12 subnets (max is 16 according to AWS docs)

### Actual Behavior

Error: creating SageMaker Domain: ValidationException: 1 validation error detected... must have length less than or equal to 10

### Relevant Error/Panic Output Snippet

```shell
│ Error: creating SageMaker Domain: ValidationException: 1 validation error detected: Value '[subnet-0e63526bfadd699fe, subnet-0f0445a86dfd9b86a, subnet-049cc0e57b795ae41, subnet-0ad0668fc6bed6015, subnet-0d888a6c33459db49, subnet-01dcfe014c0fcf61e, subnet-0b61de1dd87ed7ddc, subnet-064babd6c8921c299, subnet-0e12332a301e9b6fe, subnet-0e82846ec7b229d74, subnet-0854c56ecd40e51f4, subnet-02e52c4ecd0aa384e]' at 'subnetIds' failed to satisfy constraint: Member must have length less than or equal to 10
```

### Terraform Configuration Files
```
resource "aws_sagemaker_domain" "hackathon" {
  for_each                = toset(var.sagemaker_domains)
  domain_name             = each.key
  auth_mode               = "IAM"
  app_network_access_type = "VpcOnly"
  vpc_id                  = var.vpc_ids[local.domain_vpc[each.key]]
  subnet_ids              = var.subnet_ids[local.domain_vpc[each.key]]
}
```
### Steps to Reproduce

Create a aws_sagemaker_domain with more than 10 subnet's

### References

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-domain.html#cfn-sagemaker-domain-subnetids says that max is 16 subnetids

### Would you like to implement a fix?

None

**Comment by DrFaust92** [comment]
Hi [tonyszhang](https://github.com/tonyszhang), validation currently (and seemed to before any changes) 16 subnets. are you sure you are passing correct values?

**Comment by DrFaust92** [comment]
Also this seems like a server side error and not client side as it would fail on plan and not on apply

**Comment by DrFaust92** [comment]
Closing for lack of response/action item. @tonyszhang if you still have an issue please reopen with more details
