### ISSUE TITLE
[Bug]: challenge not supported action in aws_wafv2_rule_group, though docs indicate it is

### ISSUE THREAD

**Issue by stevenwilliamson** [hashicorp/terraform-provider-aws#29229]
### Terraform Core Version

v1.3.7

### AWS Provider Version

v4.53.0

### Affected Resource(s)

aws_wafv2_rule_group

### Expected Behavior

The action block in a rule should support the challenge action as documented in the docs https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl.html#challenge

### Actual Behavior

Error reported that challenge block not expected

 Error: Unsupported block type
│ 
│   on test.tf line 279, in resource "aws_wafv2_rule_group" "test":
│  279:       challenge {}
│ 
│ Blocks of type "challenge" are not expected here.

Changing the action type to captcha does work, and allows terraform to create the rule.

Creating the rule with action type captcha i can then change the action in the AWS console to challenge and the rule works as expected.

### Relevant Error/Panic Output Snippet

```shell
Error: Unsupported block type
│ 
│   on test.tf line 279, in resource "aws_wafv2_rule_group" "test":
│  279:       challenge {}
│ 
│ Blocks of type "challenge" are not expected here.
```

### Terraform Configuration Files

Example rule

```
rule {
    name     = "test"
    priority = 41

    rule_label {
      name = "test"
    }
    action {
      challenge {}
    }

    statement {
      not_statement {
        statement {
          geo_match_statement {
            country_codes = [
              "US", # USA
            ]
          }
        }
      }
    }

    visibility_config {
      cloudwatch_metrics_enabled = false
      metric_name                = "test"
      sampled_requests_enabled   = false
    }
  }
```

### Steps to Reproduce

Attempt to create a rule group with a rule that uses the challenge action.

### Would you like to implement a fix?

No

**Comment by stevenwilliamson** [comment]
To follow up on this report i have just realised this is an inconsistency.

aws_wafv2_web_acl resource rules support actions allow, block, count, captcha, challenge

aws_wafv2_rule_group resource rules support allow, block, count, captcha but not challenge


AWS WAF Rule groups do however support the challenge response as it is possible to set this in the AWS console.

**Comment by n11c** [comment]
Just a heads up for those following this issue: I've made a [PR](https://github.com/hashicorp/terraform-provider-aws/pull/29690) to add support for challenge action to the rule groups

Feel free to add thumbs-up to it to try to get it released soon.

**Comment by n11c** [comment]
Hey @justinretzolk, is there anything that can be done to get my PR look at for the next release please?
