### ISSUE TITLE
[Bug]: build_batch_config cannot be removed from aws_codebuild_project

### ISSUE THREAD

**Issue by sff0219** [hashicorp/terraform-provider-aws#29261]
### Terraform Core Version

1.3.7

### AWS Provider Version

4.53.0

### Affected Resource(s)

* aws_codebuild_project

### Expected Behavior

We have a CodeBuild project with batch builds configuration. When updating the CodeBuild project by removing the batch builds configuration `build_batch_config` from `aws_codebuild_project`, during `terraform apply` terraform says: 
```
Terraform will perform the following actions:

  # module.code_build[0].aws_codebuild_project.xxxx_cb will be updated in-place
  ~ resource "aws_codebuild_project" "xxxx_cb" {
        id                     = "arn:aws:codebuild:eu-central-1:xxxxxxxxxxx:project/xxxxxxxxxxx-codebuild"
        name                   = "xxxxxxxxxxx-codebuild"
        tags                   = {
            "Environment" = "Build"
        }
        # (10 unchanged attributes hidden)

      - build_batch_config {
          - combine_artifacts = false -> null
          - service_role      = "arn:aws:iam::xxxxxxxxxxx:role/codebuild-role-xxxxxxxxxxxxxxx" -> null
          - timeout_in_mins   = 480 -> null

          - restrictions {
              - compute_types_allowed  = [] -> null
              - maximum_builds_allowed = 100 -> null
            }
        }

        # (8 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.code_build[0].aws_codebuild_project.xxxx_cb: Modifying... [id=arn:aws:codebuild:eu-central-1:xxxxxxxx:project/xxxxxxxxxxx-codebuild]
module.code_build[0].aws_codebuild_project.xxxx_cb: Modifications complete after 1s [id=arn:aws:codebuild:eu-central-1:xxxxxxxxxxxxxxxxx:project/xxxxxxxxxxx-codebuild]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

```
It is expected that there is no batch configuration anymore in this CodeBuild project.

### Actual Behavior

The batch builds configuration still exists in this CodeBuild project. It is not updated. 
If do `terraform apply` again, the same output of updating `aws_codebuild_project` the will be given again. 

### Terraform Configuration Files

```terraform
resource "aws_codebuild_project" "xxxx_cb" {
  ...

  build_batch_config {
    service_role = aws_iam_role.xxxx_cb_role.arn
  }
}
```

### Steps to Reproduce

1. Create a CodeBuild project with the batch builds (`build_batch_config`)
2. Delete the `build_batch_config` block in the `.tf` file and do `terraform apply`
3. Check the CodeBuild project configuration, and you will see the batch builds configuration is still there

### Would you like to implement a fix?

None

**Comment by digglife** [comment]
It's more like an AWS issue because you can't even remove the batch config settings from AWS console or CLI.

**Comment by digglife** [comment]
I raised a PR(#34121) for fixing this issue.
