### ISSUE TITLE
[Bug]: aws_iam_role can not be created with code from official documentation

### ISSUE THREAD

**Issue by yaroslav-kovalevskyi** [hashicorp/terraform-provider-aws#29265]
### Terraform Core Version

1.3.7

### AWS Provider Version

4.53.0

### Affected Resource(s)

I'm trying to create an IAM Role without permissions using code from documentation without any changes, and it doesn't work as expected.
![image](https://user-images.githubusercontent.com/45822703/217039038-c9c6eb06-9e15-405f-aaa4-6c759c72c87b.png)
^ code from [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role)
![image](https://user-images.githubusercontent.com/45822703/217039395-3d920c7d-330d-4a9c-9c6a-cde26c9b06f7.png)
^ my piece of code
I was trying also to use different arguments such as `managed_policy_arns = []`, `inline_policy` and it doesn't help.
Could you please advise? 

### Expected Behavior

Role created as same as in AWS Web console 
![image](https://user-images.githubusercontent.com/45822703/217043036-87690d93-b849-4223-b155-3802ece5d495.png)
![image](https://user-images.githubusercontent.com/45822703/217043178-36233b73-8e65-408c-a69c-22d27e26f9f1.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/45822703/217042454-5a4ed48b-65a5-4332-a291-945107962285.png)

### Terraform Configuration Files

```terraform
resource "aws_iam_role" "no_permissions" {
  name               = "prod-ci-role"
  description        = "A role with no permissions, which can be assumed by users within the same account"
  assume_role_policy = data.aws_iam_policy_document.empty_policy.json
  managed_policy_arns = []
  inline_policy {}
}

data "aws_caller_identity" "current" {}

data "aws_iam_policy_document" "empty_policy" {
  statement {
    sid     = "Policy Which Might be Assumed by Role With No Permissions"
    actions = ["sts:AssumeRole"]
    principals {
      type = "Service"
      identifiers = [
        "ec2.amazonaws.com"
      ]
    }
  }
}
```

### Steps to Reproduce

terraform init -> terraform plan -> terraform apply

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @yaroslav-kovalevskyi 👋 Thank you for taking the time to raise this! The issue here seems to be the use of invalid characters in the `sid` value. According to [the AWS documentation][1]:

> The `Sid` element supports ASCII uppercase letters (A-Z), lowercase letters (a-z), and numbers (0-9).

[1]: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_sid.html

**Comment by yaroslav-kovalevskyi** [comment]
Hi @justinretzolk 
You are right, it helped to me. I'm closing issue right now
Thank you so much!
