### ISSUE TITLE
[Enhancement]: Redshift restore from snapshot by snapshot ARN

### ISSUE THREAD

**Issue by uvw** [hashicorp/terraform-provider-aws#29293]
### Description

We would like to restore a provisioned cluster from a **serverless** snapshot. However, `snapshot_identifier` expects the name which does not support serverless snapshots, and there is no option to specify the snapshot ARN similar to `--snapshot-arn` of the AWS CLI ([restore-from-cluster-snapshot](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/redshift/restore-from-cluster-snapshot.html#restore-from-cluster-snapshot)) 

Please add the `snapshot_arn` property to the `aws_redshift_cluster` resource with the same behavior as in the AWS CLI.

### Affected Resource(s) and/or Data Source(s)

aws_redshift_cluster

### Potential Terraform Configuration

```terraform
resource "aws_redshift_cluster" "this" {
  cluster_identifier = var.name
  cluster_type       = var.cluster_type
  node_type          = var.node_type
  number_of_nodes    = var.number_of_nodes
  # ...
  snapshot_arn       = "arn:aws:redshift-serverless:us-east-1:012345678901:snapshot/a918d0f6-7b6a-40c9-9744-6223d0daf475"
}
```

### Would you like to implement a fix?

None

**Comment by DrFaust92** [comment]
will look at this after https://github.com/hashicorp/terraform-provider-aws/pull/29500

**Comment by kal1f** [comment]
yep, it would be great to have such option.

**Comment by DrFaust92** [comment]
Looking into it now
