### ISSUE TITLE
[Enhancement]: aws_neptune_cluster has missing arguments master_user, mater_password. 

### ISSUE THREAD

**Issue by rvalivet** [hashicorp/terraform-provider-aws#29298]
### Description

[Enhancement]: aws_neptune_cluster has missing arguments master_user, mater_password. 
Providing a cli command to list all the arguments for a resource will be useful, instead of reference to the registry/documentation.

### Affected Resource(s) and/or Data Source(s)

Aws_neptune_cluster

### Would you like to implement a fix?

None

**Comment by triggan** [comment]
Neither of those parameters are used in Amazon Neptune.  Neptune only supports IAM as an identity provider for authorization.  The master_user and master_password parameters are holdovers from the RDS control plane, which Neptune reuses for management APIs.  These parameters do not apply to Neptune, however.

From the AWS CLI help:
```
       --master-username (string)
          Not supported by Neptune.

       --master-user-password (string)
          Not supported by Neptune.
```

**Comment by justinretzolk** [comment]
Hey @rvalivet 👋 Thank you for taking the time to raise this! Given the information that @triggan supplied above, we'll close this issue out. If you feel we've done this in error, please do let us know.
