### ISSUE TITLE
[Error]error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: operation error  STS: GetCallerIdentity, exceeded maximum number of attempts, 9, https response error StatusCode: 0, RequestID: , request send failed, Post "https://sts.var.aws_region.amazonaws.com/": dial tcp: lookup sts.var.aws_region.amazonaws.com: no such host

### ISSUE THREAD

**Issue by vineeth2207** [hashicorp/terraform-provider-aws#29297]
### Description

I was trying to run `terraform apply` after trying customizing the configuration in both `main.tf` and `variables.tf` files. 

The expected result is 
![image](https://user-images.githubusercontent.com/113631587/217477231-723dece0-3246-41f9-8ca5-5eb14ff48c3f.png)

But the actual result is
![image](https://user-images.githubusercontent.com/113631587/217477328-2a4c9df1-7eb8-46df-a40c-776af42f00b4.png)

I'am following the tutorial in [Terraform website](https://developer.hashicorp.com/terraform/tutorials/configuration-language/variables#parameterize-your-configuration)

### References

[Customize Terraform Configuration with Variables](https://developer.hashicorp.com/terraform/tutorials/configuration-language/variables#list-public-and-private-subnets)
[Git repository](https://github.com/hashicorp/learn-terraform-variables.git)

### Would you like to implement a fix?

None

**Comment by lvthillo** [comment]
How does your provider config look like? It seems it's pointing to "`var.aws_region`" (see sts url) as a string instead of a valid region like `us-east-1`.

Example:
```
provider "aws" {
  region  = "us-east-1"
}
```

Or using variables

```
provider "aws"{
   region = var.aws_region
}
```

**Comment by vineeth2207** [comment]
Mine look like this:
provider "aws"{
   region = var.aws_region
}
