### ISSUE TITLE
[Enhancement]: Enable aws_fsx_ontap_file_system to update route_table_ids without recreating resource

### ISSUE THREAD

**Issue by joshtrutwin** [hashicorp/terraform-provider-aws#29301]
### Description

When you modify aws_fsx_ontap_file_system.route_table_ids it forces the whole resource to be recreated, even though that is not the case via AWS console. 

Route tables for a file system can be changed in the console without a file system rebuild, but a change in terraform to the route_table_ids results in a full file system rebuild which also requires deleting any volumes/svms/etc associated to the file system and incurs a very lengthy rebuild:

![fsx-routes](https://user-images.githubusercontent.com/107627665/217547020-30001d3c-fa03-46bb-a81b-0a41b56c0202.PNG)

Can we update the provider to allow modification to the route table ids without having to tear down the aws_fsx_ontap_file_system resource?

Note it is possible to modify the route tables in AWS and modify the terraform code to match and the infrastructure will match but this is not an ideal solution.

### Affected Resource(s) and/or Data Source(s)

fsx_ontap_file_system

### References

Similar to #26937

https://docs.aws.amazon.com/fsx/latest/APIReference/API_UpdateFileSystemOntapConfiguration.html

### Would you like to implement a fix?

None

**Comment by DrFaust92** [comment]
taking a look, i see API now allows this
