### ISSUE TITLE
[Enhancement]: aws_glue_crawler with delta_target does not contain Create Native Tables option

### ISSUE THREAD

**Issue by GowthamiRamachandran** [hashicorp/terraform-provider-aws#29336]
### Description

```hcl
resource "aws_glue_crawler" "example" {
  database_name = aws_glue_catalog_database.example.name
  name          = "example"
  role          = aws_iam_role.example.arn

  delta_target {
    connection_name = ""
    delta_tables    = ["s3://path/"]
    write_manifest  = false
  }
}
```

For creating AWS Glue crawler with Delta Lake target we can create table for querying with Create Native tables Option in aws_glue_crawler, for delta_target the option is required.
<img width="608" alt="Screenshot 2023-02-09 at 6 49 01 pm" src="https://user-images.githubusercontent.com/104551618/218022335-cf130fc9-d4a0-4a18-b323-971b25972832.png">

### Affected Resource(s) and/or Data Source(s)

Affected Resource: aws_glue_crawler
DataSource: delta_target

### Potential Terraform Configuration

```terraform
delta_target {
    connection_name = ""
    delta_tables    = ["s3://path/"]
    write_manifest  = false
    create_native_delta_table = true
  }
```

### References

https://docs.aws.amazon.com/cli/latest/reference/glue/create-crawler.html
In AWS CLI for `create-crawler` `"CreateNativeDeltaTable" : true` option is available.

### Would you like to implement a fix?

None

**Comment by tomwelsh11** [comment]
I'm interested in working on this issue - will give it a crack

**Comment by tomwelsh11** [comment]
I've opened a PR (2 weeks ago) that will close this issue and provide the required functionality - is there any indication on the time frame for this to be reviewed/merged? Not having this functionality is blocking a high value piece for us.

**Comment by mai-nguyen-coinhako** [comment]
Yes, I am looking forward to this updates too.
