### ISSUE TITLE
[Docs]: OpenSearchServerless Documentation Not Available

### ISSUE THREAD

**Issue by ezzyangel** [hashicorp/terraform-provider-aws#29335]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs

### Description

OpenSearch Serverless is now available and according to issue [#28313](https://github.com/hashicorp/terraform-provider-aws/issues/28313), the functionality has been made available as of v4.48.0.   However, it appears the documentation was not updated to include this new functionality. 

### Would you like to implement a fix?

None

**Comment by mattburgess** [comment]
@ezzyangel that ticket/PR is a pre-requisite for implementing the actual data sources and resources that underpin OpensearchServerless clusters, i.e. it's a bit of scaffolding. The PRs that actually implement the resources are awaiting review and merge; those will include the relevant documentation.

#28470
#28518 
#28651
#28776

The final resource, `aws_opensearchserverless_collection` is dependent on a couple of the other resources above so I'm waiting on those to be reviewed and merged before starting work on that.

**Comment by ezzyangel** [comment]
Thanks for the clarification @mattburgess!
