### ISSUE TITLE
[Bug]: Error reading KMS Grant: grantee principal is invalid

### ISSUE THREAD

**Issue by choppedpork** [hashicorp/terraform-provider-aws#29340]
### Terraform Core Version

1.2.9

### AWS Provider Version

4.54.0

### Affected Resource(s)

aws_kms_grant

### Expected Behavior

Successful plan, no changes detected.

### Actual Behavior

following a long wait:
```
│ Error: reading KMS Grant (xx-xx-xx-xx-xx:xx): grantee principal is invalid: "AROAxxxxx"
│ 
│   with module.ingest-bucket.aws_kms_grant.rw["arn:aws:iam::xxxx:role/xx-xx"],
│   on .terraform/modules/ingest-bucket/main.tf line 404, in resource "aws_kms_grant" "rw":
│  404: resource "aws_kms_grant" "rw" {
```

After downgrading the provider version:
```
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "< 4.54"
    }
```
the plan completes without errors.

### Terraform Configuration Files

The following code resides in a module:

```
resource "aws_kms_grant" "rw" {
  for_each = toset(var.enabled ? var.additional_arns : [])

  name              = join("-", ["rw-grant", md5(each.value)])
  key_id            = aws_kms_key.this[0].key_id
  grantee_principal = each.value
  operations = ["Encrypt", "Decrypt", "ReEncryptFrom", "ReEncryptTo",
    "GenerateDataKey", "GenerateDataKeyWithoutPlaintext",
  "DescribeKey"]
}
```

The module is then called with a single additional ARN which is an IAM role in a different account (I think this _might_ be the crux of the issue as we use the same module in a bunch of other places but I've so far only hit this issue with a cross account grant).

### Steps to Reproduce

`terraform plan`

### References

I'm 99% sure this change in behaviour was introduced in https://github.com/hashicorp/terraform-provider-aws/pull/29245

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@choppedpork Thanks for raising this issue.

For the error text `grantee principal is invalid: "xxx"`, what is the format of _xxx_? e.g. Is an ARN, a raw AWS account ID, ...?

**Comment by choppedpork** [comment]
Apologies - I've initially posted the error with full details and got slightly overzealous with removing them later!
It's a role unique identifier (`AROAxxxxx`).

**Comment by choppedpork** [comment]
Hello,

Bit of an update here - turns out that this error is actually legitimate! We did have some AROA... KMS grants and they _were_ in fact causing our correct grants to be ignored - once we removed them manually using the AWS cli the grants started working correctly (which they weren't - but we haven't realised this yet at the time of creating this ticket).

I am unsure as to the provenance of the invalid grantee principals - this infrastructure is many years old and has seen through terraform versions at least since 0.11 so it's not impossible they were badly created at some point, somehow. I'm wondering whether this issue is more of a case of adding some additional information to the error message for anyone who ends up in a similar situation - the new validation definitely works and does the job, after all... What do you think?

**Comment by ewbankkit** [comment]
@choppedpork Thanks for updating this Issue.

I tried reproducing with a cross-account role but was unable to.
We just had a maintainers discussion where this came up and the only scenario we know of where the unique ID is returned consistently is when the [original IAM principal has been deleted]:

<img width="596" alt="Screen Shot 2023-02-13 at 1 55 22 PM" src="https://user-images.githubusercontent.com/2404182/218548817-57d5f079-5eb6-4b11-8ab4-197c56e86846.png">

Yes, I think I'll add something to the error message calling out potentially deleted principals.

**Comment by ewbankkit** [comment]
Verified that the problem can be reproduced if the IAM role used for `grantee_principal` is deleted:

```
aws_kms_key.test: Refreshing state... [id=549df099-1603-4fae-b047-170ae7bba1a4]
aws_kms_grant.test: Refreshing state... [id=549df099-1603-4fae-b047-170ae7bba1a4:0be0fcb34bffca082efb53fe2ceaeba0704afa8173e67d8768459c26403b06f8]
╷
│ Error: reading KMS Grant (549df099-1603-4fae-b047-170ae7bba1a4:0be0fcb34bffca082efb53fe2ceaeba0704afa8173e67d8768459c26403b06f8): grantee principal is invalid: "AROASXIXB4ZJW2XMQRSYG"
│ 
│   with aws_kms_grant.test,
│   on main.tf line 8, in resource "aws_kms_grant" "test":
│    8: resource "aws_kms_grant" "test" {
│ 
╵
```

**Comment by ewbankkit** [comment]
Updated error message:

```console
aws_kms_key.test: Refreshing state... [id=56926e45-f73e-4fbb-92fc-5fa9f08d275e]
aws_kms_grant.test: Refreshing state... [id=56926e45-f73e-4fbb-92fc-5fa9f08d275e:b0eff8c8649f9a15ef556f0d9b4c534e344b75f2c9f8edaeaee700990cb1e930]
╷
│ Error: reading KMS Grant (56926e45-f73e-4fbb-92fc-5fa9f08d275e:b0eff8c8649f9a15ef556f0d9b4c534e344b75f2c9f8edaeaee700990cb1e930): grantee principal (AROASXIXB4ZJXY4R32LLK) is invalid. Perhaps the principal has been deleted or recreated
│ 
│   with aws_kms_grant.test,
│   on main.tf line 26, in resource "aws_kms_grant" "test":
│   26: resource "aws_kms_grant" "test" {
│ 
╵
```

**Comment by choppedpork** [comment]
Thanks for taking the time to look into this!
