### ISSUE TITLE
d/aws_redshift_service_account: Deprecate

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#29346]
[AWS document](https://docs.aws.amazon.com/redshift/latest/mgmt/db-auditing.html#db-auditing-bucket-permissions) that [a service principal name](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html#principal-services) be used instead of AWS account ID in any relevant IAM policy.
The `aws_redshift_service_account` should now be considered deprecated and will be removed in a future version.

**Comment by jar-b** [comment]
Closed by #31006, merged to `main` via #31392
