### ISSUE TITLE
[Repo]:  Error modifying DB Instance legacy-dms: InvalidParameterCombination: Cannot find upgrade path from 5.7.38 to 5.6.

### ISSUE THREAD

**Issue by SAMTECHsb** [hashicorp/terraform-provider-aws#29361]
### Description

```
 Error: Error modifying DB Instance legacy-dms: InvalidParameterCombination: Cannot find upgrade path from 5.7.38 to 5.6.
│   status code: 400, request id: e7740193-bf98-464c-a1b3-4124d7f5d909
│ 
│   with module.db.module.db_instance.aws_db_instance.this[0],
│   on .terraform/modules/db/modules/db_instance/main.tf line 45, in resource "aws_db_instance" "this":
│   45: resource "aws_db_instance" "this" {
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @SAMTECHsb 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you supply a sample Terraform configuration that exhibits this behavior, as well as debug logs (redacted as needed)?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
