### ISSUE TITLE
[New Resource]: Security Lake

### ISSUE THREAD

**Issue by schuylr** [hashicorp/terraform-provider-aws#29376]
### Description

Looking to add [Security Lake](https://aws.amazon.com/security-lake/) as a new Terraform Resource / Data Source so users with IaC requirements in their production environments can effectively start using this service.

### Requested Resource(s) and/or Data Source(s)

* [x] [`aws_security_lake_data_lake`](https://github.com/hashicorp/terraform-provider-aws/pull/34521)
* [x] [`aws_security_lake_aws_log_source`](https://github.com/hashicorp/terraform-provider-aws/pull/34974)
* [x] [`aws_security_lake_custom_log_source`](https://github.com/hashicorp/terraform-provider-aws/pull/35354)
* [x] [`aws_security_lake_subscriber`](https://github.com/hashicorp/terraform-provider-aws/pull/35981)

### Potential Terraform Configuration

```terraform
resource "aws_security_lake_data_lake" "example" {
  configurations {
    us-east-1 {
      encryptionKey                 = "string"
      replicationDestinationRegions = ["us-west-2"]
      replicationRoleArn            = "string"
      retentionSettings = [
        {
          retentionPeriod = 14
          storageClass    = "GLACIER"
        }
      ]
      tagsMap {
        key = "value"
      }
    }
  }

  enableAll               = true
  metaStoreManagerRoleArn = "string"
  regions                 = ["us-east-1"]
}


resource "aws_security_lake_aws_log_source" "example" {
  enableAllDimensions = {
    string = {
      string = ["string"]
    }
  }
  enableSingleDimension = ["string"]
  enableTwoDimensions = {
    string = ["string"]
  }
  inputOrder = ["string"]
}

resource "aws_security_lake_subscriber" "example" {
  accessTypes = ["LAKEFORMATION"]
  accountId   = "1234567890"
  externalId  = "1234567890"
  sourceTypes = [
    {
      awsSourceType    = "string"
      customSourceType = "string"
    }
  ]
  subscriberDescription = "string"
  subscriberName        = "string"
}
```

### References

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/securitylake 
https://docs.aws.amazon.com/security-lake/latest/APIReference/API_CreateDatalake.html
https://docs.aws.amazon.com/security-lake/latest/APIReference/API_CreateSubscriber.html 
https://docs.aws.amazon.com/security-lake/latest/APIReference/API_CreateAwsLogSource.html
https://docs.aws.amazon.com/security-lake/latest/APIReference/API_CreateCustomLogSource.html 

### Would you like to implement a fix?

Yes

**Comment by aristosvo** [comment]
I am interested in contributing, but as this would be my first issue on the AWS provider this might take a bit longer.

I have a bit of experience with `azurerm` though.

**Comment by AdamTylerLynch** [comment]
> I am interested in contributing, but as this would be my first issue on the AWS provider this might take a bit longer.
> 
> I have a bit of experience with `azurerm` though.

@aristosvo AWS published a workshop on contributing to the AWS provider, I would suggest you start there as a learning path.
https://catalog.workshops.aws/contributing-to-the-terraform-provider

**Comment by markoskandylis** [comment]
I will start working on this resource @aristosvo did you already made any progress? We can always collaborate :)

**Comment by aristosvo** [comment]
Take it away, didn't have the time in the end. Will watch your MR to learn :)

**Comment by markoskandylis** [comment]
Thats great @luescher-aws please ping me internally to connect @mkandyli

**Comment by pfrederiksen** [comment]
Also happy to help if you want to connect internally.

**Comment by meetreks** [comment]
@luescher-aws anyone picked up the log configuration? If not happy to wrap that up, had a look and looks pretty straightforward.

**Comment by markoskandylis** [comment]
Hi @meetreks i am already working on that @luescher-aws you can work on custom logs if you want to pick something

**Comment by meetreks** [comment]
@markoskandylis shall i pick create subscriber then?

**Comment by markoskandylis** [comment]
@meetreks yes that sounds great 🙂

**Comment by gramsa49** [comment]
I wanted to see if progress is being made on aws log sources.  I can pick that up if your work has stalled.

**Comment by markoskandylis** [comment]
Hi @gramsa49 aws log sources is now merged but you can take custom log sources if you want

**Comment by markoskandylis** [comment]
Hi i will stat the work for custom log source

**Comment by kamalika-majumder** [comment]
Anyone working on the securitylake subscriber resources ?

**Comment by luescher-aws** [comment]
Yes, let me check how far we are.

From: Kamalika Majumder ***@***.***>
Reply-To: hashicorp/terraform-provider-aws ***@***.***>
Date: Monday, February 12, 2024 at 1:20 PM
To: hashicorp/terraform-provider-aws ***@***.***>
Cc: "Luescher, Marc" ***@***.***>, Mention ***@***.***>
Subject: Re: [hashicorp/terraform-provider-aws] [New Resource]: Security Lake (Issue #29376)


Anyone working on the securitylake subscriber resources ?

**Comment by markoskandylis** [comment]
Hi @kamalika-majumder currently i am working on it

**Comment by kamalika-majumder** [comment]
Oh great. Any idea which release its going to be added next ?

**Comment by markoskandylis** [comment]
@kamalika-majumder i will aim for the 29th release hopefully a bit faster if posible

**Comment by kclinden** [comment]
Are there any plans to add a resource for managing Org configurations via following:
* Action - CreateDataLakeOrganizationConfiguration
* Action - GetDataLakeOrganizationConfiguration
* Action - DeleteDataLakeOrganizationConfiguration
* DataType - DataLakeAutoEnableNewAccountConfiguration
