### ISSUE TITLE
[Enhancement]: AWS Batch Job Definition property, eksProperties, missing

### ISSUE THREAD

**Issue by eucalibrate** [hashicorp/terraform-provider-aws#29383]
### Terraform Core Version

1.3.5

### AWS Provider Version

4.54.0

### Affected Resource(s)

AWS Batch Job Definition functionality of provisioning jobs inside an EKS cluster is missing.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html -> eksProperties should exist but does not within the Terraform AWS Provider

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/batch_job_definition

### Expected Behavior

able to provision resource of AWS Batch Job Definition with eksProperties

### Actual Behavior

eksProperties not found

### Terraform Configuration Files

any string value for resource's eksProperties, the TF client will throw an error that property is not found.

### Steps to Reproduce

these steps https://docs.aws.amazon.com/batch/latest/userguide/getting-started-eks.html
- namespace in k8s
- clusterRole
- clusterRoleBinding
- role
- roleBinding
- run eksCtl command mentioned in documentation to authenticate into eks cluster
- create AWS Batch ComputeEnvironment
- create AWS Batch Job Queue
- create AWS Batch Job Definition with eksproperties -> runtime will fail property not found

### Would you like to implement a fix?

None

**Comment by calibrateersan** [comment]
I wouldn't mind helping add this in but I am not familiar how to do so in the terraform provider code. I am familiar with AWS Batch functionality though if there were questions how this works. Its relatively new, I believe October 2022, when eksProperties functionality was released.

**Comment by delagoya** [comment]
@ersan-calibrate Issue #27466 provided support for EKS Batch compute environments but missed the job definition updates to the API. Would it be possible for you to review the changes there and implement equivalent for the JD?

**Comment by ersan-calibrate** [comment]
I abandoned working with AWS Batch in ref to this issue. but just for the sake of understanding and learning more, where would I implement this change? could you provide links to the relevant code? I can take a look and throw something up

**Comment by delagoya** [comment]
The linked issue above had commit linked when closed. You can review the files changed at https://github.com/hashicorp/terraform-provider-aws/pull/27499/files

**Comment by pythonking6** [comment]
I am running into this issue now! Do we know if this is going to be fixed soon?

**Comment by pythonking6** [comment]
This is very important!!

**Comment by olenm** [comment]
at this point i feel the `aws_batch_job_definition` does not follow the normal paradigm we are used to; it literally accepts a json blob of input and things like ignore_changes do not work on sub-elements (like image, command, you name it). I would not be surprised if a more feature rich TF resource was exposed for this and would intrinsically cover the eksProperties
