### ISSUE TITLE
[Bug]: aws_cloudwatch_metric_alarm with expression throws: `"period": conflicts with metric_query`

### ISSUE THREAD

**Issue by cmihail** [hashicorp/terraform-provider-aws#29398]
### Terraform Core Version

1.3.1

### AWS Provider Version

4.32.0

### Affected Resource(s)

aws_cloudwatch_metric_alarm

### Expected Behavior

`terraform apply` with success 

### Actual Behavior

I get the error `"period": conflicts with metric_query` even though https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudwatch-alarm-metricdataquery.html mentions that period is now supported inside `MetricDataQuery`

Also using AWS Console I was able to create the alarm manually with the same expression as the one from above configuration.

The error seems to be due to `period` missing from https://github.com/hashicorp/terraform-provider-aws/blob/5857c145b31d41966bef256f669c12ae35cc2486/internal/service/cloudwatch/metric_alarm.go#L599

### Terraform Configuration Files

```
resource "aws_cloudwatch_metric_alarm" "millis_behind" {
  alarm_name          = "MillisBehind alarm for ${var.app_name}"
  alarm_description   = "MillisBehind alarm for ${var.app_name}"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = "3"
  datapoints_to_alarm = "3"
  threshold           = 30000
  treat_missing_data  = "breaching"

  metric_query {
    id          = "mq-millis-behind"
    expression  = "SELECT MAX(MillisBehindLatest) FROM SCHEMA(\"${var.app_name}\", Operation, ShardId) WHERE Operation = 'ProcessTask'"
    period      = "60"
    return_data = "true"
  }
}
```

### Steps to Reproduce

Define `var.app_name` using the name of a KCL kubernates application and then create a new CW alarm with period inside meric_query (see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudwatch-alarm-metricdataquery.html for documentation).

### Debug Output

```
Error: Conflicting configuration arguments

  with module.metrics.aws_cloudwatch_metric_alarm.millis_behind,
  on ../../../../modules/kcl/cloudwatch.tf line 7, in resource "aws_cloudwatch_metric_alarm" "millis_behind":
   7:   period              = "60"

"period": conflicts with metric_query
```

### Would you like to implement a fix?

None

**Comment by gdavison** [comment]
HI @cmihail, thanks for submitting this. To clarify, is the error message that you're seeing the following?

> Error: Unsupported argument
>        
>          on terraform_plugin_test.tf line 14, in resource "aws_cloudwatch_metric_alarm" "test":
>          14:     period      = "60"
>        
>        An argument named "period" is not expected here.

That's what I see when I try the example code.

**Comment by cmihail** [comment]
> HI @cmihail, thanks for submitting this. To clarify, is the error message that you're seeing the following?
> 
> > Error: Unsupported argument
> > ```
> >      on terraform_plugin_test.tf line 14, in resource "aws_cloudwatch_metric_alarm" "test":
> >      14:     period      = "60"
> >    
> >    An argument named "period" is not expected here.
> > ```
> 
> That's what I see when I try the example code.

Hey @gdavison . Yes, sorry, the error I get is:
```
Error: Unsupported argument

  on ../../../../modules/kcl/cloudwatch.tf line 23, in resource "aws_cloudwatch_metric_alarm" "millis_behind_critical":
  23:     period      = "60"

An argument named "period" is not expected here.
```

The previous error was probably from some experimenting code and I copy pasted the wrong error.

Though based on AWS docs `period` in metric query should work. I also tried it now with AWS CLI, and the following code worked:
```
$ aws cloudwatch put-metric-alarm  --region eu-west-1 --alarm-name "test" --evaluation-periods 3 --comparison-operator GreaterThanThreshold --threshold 10000 --metrics '[{"Id": "test", "Period": 60, "ReturnData": true, "Expression": "SELECT MAX(MillisBehindLatest) FROM SCHEMA(\"app-name\", Operation,ShardId)"}]'
```

**Comment by Jetbo** [comment]
@gdavison I can provide some additional context to this bug.

Say I make a CloudWatch Alarm `test` with this expression that uses a custom Metric:

```
SELECT SUM(AuthorizationFailureCount) FROM SCHEMA(CloudTrailMetrics, accountId,region)
```

I can import this alarm and show that state as:

```terraform
❯ terraform import aws_cloudwatch_metric_alarm.test test
❯ terraform state show aws_cloudwatch_metric_alarm.test
# aws_cloudwatch_metric_alarm.test:
resource "aws_cloudwatch_metric_alarm" "test" {
    actions_enabled           = true
    alarm_actions             = []
    alarm_description         = "test"
    alarm_name                = "test"
    arn                       = "arn:aws:cloudwatch:us-east-1:accountId:alarm:test"
    comparison_operator       = "GreaterThanOrEqualToThreshold"
    datapoints_to_alarm       = 1
    dimensions                = {}
    evaluation_periods        = 1
    id                        = "test"
    insufficient_data_actions = []
    ok_actions                = []
    period                    = 0
    tags                      = {}
    tags_all                  = {
        "bu"         = "quip"
        "env"        = "production"
        "managed_by" = "terraform"
    }
    threshold                 = 1
    treat_missing_data        = "notBreaching"

    metric_query {
        expression  = "SELECT SUM(AuthorizationFailureCount) FROM SCHEMA(CloudTrailMetrics, accountId,region)"
        id          = "e1"
        label       = "AuthorizationFailureCount"
        return_data = true
    }
}
```

Notice `period` is set to 0. But when I try to make this exact same resource instead of importing it, I get this error:

```bash

│ Error: Conflicting configuration arguments
│ 
│   with aws_cloudwatch_metric_alarm.test,
│   on cloudwatch.tf line 188, in resource "aws_cloudwatch_metric_alarm" "test":
│  188:   period                    = 0
│ 
│ "period": conflicts with metric_query

```

I would also like to note that with a Metrics Insights query alarm, the period must be between 1 minute and 3 hours. So I have this alarm set to a period of 60 seconds in the AWS Dashboard, but Terraform imported it as 0 for unknown reasons.
