### ISSUE TITLE
[Enhancement]: Resource: aws_launch_template - add AllowedInstanceTypes for Instance Requirements

### ISSUE THREAD

**Issue by rubroboletus** [hashicorp/terraform-provider-aws#29401]
### Description

In launch template, Instance Requirements, add AllowedInstanceTypes field, used to filtering allowed instances types.

### Affected Resource(s) and/or Data Source(s)

aws_launch_template

### Potential Terraform Configuration

```terraform
resource "aws_launch_template" "mytemplate" {
    name = "mytemplate"

    instance_requirements {
        allowed_instance_types = "c*"
        memory_gib {
            min = 8192
            max = 8192
        }
        vcpu_count {
            min = 4
            max = 4
        }
    }
}
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @rubroboletus 👋 Thank you for taking the time to read this! It looks like this was added in version 4.57.0 of the provider with the PR that was linked above. With that in mind, we'll close this issue out. If you feel we've done this in error, please do let us know.
