### ISSUE TITLE
[Enhancement]: Support `TransitEncryptionMode` argument for ElastiCache clusters

### ISSUE THREAD

**Issue by subbotinkv** [hashicorp/terraform-provider-aws#29403]
### Description

Not so long ago, AWS announced ability to enable in-transit encryption for existing ElastiCache clusters. This feature is already available in AWS Console & AWS CLI. 
It would be nice to have in terraform also. It will help to make process of migration to TLS enabled cluster more smooth. 

### Affected Resource(s) and/or Data Source(s)

* aws_elasticache_replication_group

### Potential Terraform Configuration

```terraform
{
   transit_encryption_enabled = true
   transit_encryption_mode = preferred
}
```

### References

- [Amazon ElastiCache for Redis now supports enabling encryption in transit on existing clusters](https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-elasticache-redis-enabling-encryption-transit-existing-clusters/)
- [Enabling in-transit encryption for an existing cluster using the (CLI)
](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/in-transit-encryption.html)
- [Options: --transit-encryption-mode](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/elasticache/create-replication-group.html)

### Would you like to implement a fix?

No

**Comment by dbmurphy** [comment]
PR #26987 is addressing this, isn't it? We are just waiting for it to be prioritised and merged. Maybe in  milestone 5.0, we will finally see this.
