### ISSUE TITLE
[Enhancement]: `aws_rds_cluster` Multi-AZ Cluster performance insights

### ISSUE THREAD

**Issue by tedsmitt** [hashicorp/terraform-provider-aws#29414]
### Description

Add the option to enable performance insights (and associated settings) for a Multi-AZ RDS Cluster.

I have already prepared the code for this, and will submit this shortly.

### Affected Resource(s) and/or Data Source(s)

aws_rds_cluster

### Potential Terraform Configuration

```terraform
resource "aws_rds_cluster" "mysql" {
  ...

  performance_insights_enabled          = true
  performance_insights_kms_key_id       = aws_kms_key.test.arn
  performance_insights_retention_period = 31
}
```

### References

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/create-multi-az-db-cluster.html#create-multi-az-db-cluster-settings
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PerfInsights.Enabling.html

### Would you like to implement a fix?

Yes

**Comment by nApucco** [comment]
What is the holdup with this feature? (It seems the PR has some conflicts and needs a rebase/fix.)

Without this feature, Performance Insights for RDS Multi-AZ Clusters need to be manually enabled.

**Comment by Syndorik** [comment]
We're a year later, any news on this? It seems that we're forced to apply the changes manually for the moment
