### ISSUE TITLE
[Enhancement]: Support WAF in Cognito user pools

### ISSUE THREAD

**Issue by danballance** [hashicorp/terraform-provider-aws#29422]
### Description

Cognito now supports enabling WAF in Cognito:
https://aws.amazon.com/about-aws/whats-new/2022/08/amazon-cognito-enables-native-support-aws-waf/

I've had a look at the latest docs below and I don't think it's supported yet:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool

Are there any plans to support Cognito WAF in the future? Or perhaps I have missed how to enable this with Terraform somewhere?

Many thanks in advance.

### Affected Resource(s) and/or Data Source(s)

aws_cognito_user_pool

### References

https://aws.amazon.com/about-aws/whats-new/2022/08/amazon-cognito-enables-native-support-aws-waf
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-waf.html

### Would you like to implement a fix?

No

**Comment by dtykalowski-tsh** [comment]
This is already working, you need to attach WAF to Cognito from other side: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl_association

The following arguments are supported:

[resource_arn](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl_association#resource_arn) - (Required) The Amazon Resource Name (ARN) of the resource to associate with the web ACL. This must be an ARN of an Application Load Balancer, an Amazon API Gateway stage, or an Amazon Cognito User Pool.

**Comment by justinretzolk** [comment]
Hey @danballance 👋 Thank you for taking the time to raise this! Can you confirm whether the information provided above resolves your issue?

**Comment by kamaz** [comment]
@justinretzolk I can confirm this works as expected. 

I used an example which I've pasted below and it works as expected. I believe it can be closed unless @danballance still has problems configuring it. 

``tf
resource "aws_cognito_user_pool" "main" {
  name = "my-pool"
}
resource "aws_wafv2_web_acl" "main" {
  name  = "my-waf"
  scope = "REGIONAL"

  default_action {
    allow {}
  }

  visibility_config {
    cloudwatch_metrics_enabled = false
    metric_name                = "my-waf"
    sampled_requests_enabled   = false
  }
}

resource "aws_wafv2_web_acl_association" "main" {
  resource_arn = aws_cognito_user_pool.main.arn
  web_acl_arn  = aws_wafv2_web_acl.main.arn
}
```

**Comment by justinretzolk** [comment]
Given the info above, we'll close this issue out. If you feel we've done this in error, please do let us know.
