### ISSUE TITLE
[Enhancement]:  specify "DP" as the input volume type while using aws_fsx_ontap_volume resource

### ISSUE THREAD

**Issue by amit15er** [hashicorp/terraform-provider-aws#29456]
### Description

AWS launched the ability to create DP volumes natively via Console/API (as well as CFN). Unfortunately terraform provider for AWS do not provide that option yet.

### Affected Resource(s) and/or Data Source(s)

aws_fsx_ontap_volume

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_ontap_volume

### Would you like to implement a fix?

None

**Comment by amit15er** [comment]
Past re:Invent, AWS launched the ability to create DP volumes natively via our Console/API (as well as CFN). Refer :
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-fsx-volume-ontapconfiguration.html#cfn-fsx-volume-ontapconfiguration-ontapvolumetype

The golang resource backend is using the Values() function from the SDK :
https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/fsx/ontap_volume.go#L117

But not sure why https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_ontap_volume page do not reflect the same?

**Comment by drewmullen** [comment]
The docs are updated manually. suggest trying the feature out now. if it works, feel free to submit an update to the docs file here: https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/fsx_ontap_volume.html.markdown

**Comment by amit15er** [comment]
I also tried with latest ver of provider as well as terraform binary version, but no luck : 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
terraform {
  required_version = "~> 1.3.8"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.55"
    }
  }
}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Getting below error : 
% terraform validate
╷
│ Error: Value for unconfigurable attribute
│ 
│   with module.fsx_ontap_dev_single_az.aws_fsx_ontap_volume.this,
│   on ../main.tf line 44, in resource "aws_fsx_ontap_volume" "this":
│   44:   ontap_volume_type          = var.volumes[count.index].ontap_volume_type 
│ 
│ Can't configure a value for "ontap_volume_type": its value will be decided automatically based on the result of applying
│ this configuration.

resource definition : 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
resource "aws_fsx_ontap_volume" "this" {
  count = length(var.volumes)

  storage_virtual_machine_id = aws_fsx_ontap_storage_virtual_machine.this.id
  name                       = var.volumes[count.index].name
  junction_path              = var.volumes[count.index].junction_path
  size_in_megabytes          = var.volumes[count.index].size_in_megabytes
  security_style             = var.volumes[count.index].security_style
  storage_efficiency_enabled = var.volumes[count.index].storage_efficiency_enabled
  ontap_volume_type          = var.volumes[count.index].ontap_volume_type 
  tags                       = local.tags
}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

variable declaration : 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
variable "volumes" {
  description = "collection of FSx ONTAP Volumnes "
  type = list(object({
    name                       = string
    junction_path              = string
    size_in_megabytes          = number
    storage_efficiency_enabled = string
    security_style             = string
    tiering_policy_name        = string
    tiering_policy_cooling     = string
    ontap_volume_type          = string 
  }))
}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
