### ISSUE TITLE
[Enhancement]: NAT Gateway support for Secondary EIP allocation IDs

### ISSUE THREAD

**Issue by adampie** [hashicorp/terraform-provider-aws#29471]
### Description

NAT Gateways now support associating up to 8 IPs (1 primary IPv4 address and 7 secondary IPv4 addresses) to increase the concurrent connection limit to a single destination.

### Affected Resource(s) and/or Data Source(s)

- aws_nat_gateway

### Potential Terraform Configuration

```terraform
resource "aws_nat_gateway" "example" {
  allocation_id            = aws_eip.example.id
  secondary_allocation_ids = []
  subnet_id                = aws_subnet.example.id

  tags = {
    Name = "gw NAT"
  }

  # To ensure proper ordering, it is recommended to add an explicit dependency
  # on the Internet Gateway for the VPC.
  depends_on = [aws_internet_gateway.example]
}
```

### References

- https://aws.amazon.com/about-aws/whats-new/2023/02/amazon-nat-gateways-capacity-concurrent-connections-unique-destination/
- https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html#nat-gateway-edit-secondary

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
One potential source of problems here will be how to manage both auto-assigned and manually assigned private IPv4 addresses.

**Comment by arko95** [comment]
can we create a new ressource  "aws_nat_gateway_secondary_ip" that will manage both auto-assigned and manually assigned private IPv4 addresses ?

**Comment by jtomaszon** [comment]
Hello guys, where are we on this feature request? We are suffering right now because of not enough NAT power
