### ISSUE TITLE
Remove deprecated EC2-Classic resources and attributes

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#29480]
Remove the resources and attributes deprecated during EC2-Classic retirement.

Relates https://github.com/hashicorp/terraform-provider-aws/issues/23625.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/26427.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/26525.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/26786.

Deprecated resources:

* `aws_db_security_group`
* `aws_elasticache_security_group`
* `aws_redshift_security_group`

Deprecated resource attributes:

* `aws_db_instance.security_group_names`
* `aws_elasticache_cluster.security_group_names`
* `aws_redshift_cluster.cluster_security_groups`
* `aws_launch_configuration.vpc_classic_link_id`
* `aws_launch_configuration.vpc_classic_link_security_groups`
* `aws_vpc.enable_classiclink`
* `aws_vpc.enable_classiclink_dns_support`
* `aws_default_vpc.enable_classiclink`
* `aws_default_vpc.enable_classiclink_dns_support`
* `aws_vpc_peering_connection.allow_classic_link_to_remote_vpc`
* `aws_vpc_peering_connection.allow_vpc_to_remote_classic_link`
* `aws_vpc_peering_connection_accepter.allow_classic_link_to_remote_vpc`
* `aws_vpc_peering_connection_accepter.allow_vpc_to_remote_classic_link`
* `aws_vpc_peering_connection_options.allow_classic_link_to_remote_vpc`
* `aws_vpc_peering_connection_options.allow_vpc_to_remote_classic_link`

Deprecated data source attributes:

* `aws_db_instance.db_security_groups`
* `aws_elasticache_cluster.security_group_names`
* `aws_redshift_cluster.cluster_security_groups`
* `aws_launch_configuration.vpc_classic_link_id`
* `aws_launch_configuration.vpc_classic_link_security_groups`

**Comment by ewbankkit** [comment]
@bryantbiggs Thanks for the offer of help, but the maintainers have this scheduled already.

**Comment by jar-b** [comment]
Closed by #30966, merged to `main` via #31392
