### ISSUE TITLE
[Bug]: Error: deleting RDS Subnet Group (pgsql-sbnet-REDATED-production): AccessDenied: User: arn:aws:sts::REDATED:assumed-role/TerraformProduction/aws-go-sdk-1676903168369412529 is not authorized to perform: rds:DeleteDBSubnetGroup on resource: arn:aws:rds:$AWS_DEFAULT_REGION:REDATED:subgrp:pgsql-sbnet-REDATED-production because no identity-based policy allows the rds:DeleteDBSubnetGroup action │ 	status code: 403, request id: 4a496db7-7cf2-4e2f-901b-356bc744dec5

### ISSUE THREAD

**Issue by Snehil03** [hashicorp/terraform-provider-aws#29511]
### Terraform Core Version

0.15.5

### AWS Provider Version

4.34.0

### Affected Resource(s)

Not able to delete subnet resource of postgressql db.
I am running pro

### Expected Behavior

It should delete all the created resources like database , inline subnets ,tags, snapshots etc... 

### Actual Behavior

It failed to delete subnet and other network component stating it's not have permission to delete.
In actual as everything created using terraform why it's not able to fail on deleting.

### Relevant Error/Panic Output Snippet

```shell
Error: deleting RDS Subnet Group (pgsql-sbnet-production): AccessDenied: User: arn:aws:sts::REDATED:assumed-role/TerraformProduction/aws-go-sdk-1676903168369412529 is not authorized to perform: rds:DeleteDBSubnetGroup on resource: arn:aws:rds:$AWS_DEFAULT_REGION:REDATED:subgrp:pgsql-sbnet-redated-production because no identity-based policy allows the rds:DeleteDBSubnetGroup action
│ 	status code: 403, request id: 4a496db7-7cf2-4e2f-901b-356bc744dec5
```

### Terraform Configuration Files

`data "sops_file" "secrets" {
  #provider = sops.carlpett
  source_file = "pass-credentials.enc.yaml"
}

locals {
  apps = toset([
    "REDATED"
  ])
}

resource "aws_db_instance" "pgsql" {
  #provider = sops.carlpett
  for_each          = local.apps
  db_name           = each.key
  identifier        = "${each.key}-${var.environment}"
  allocated_storage = 10
  engine            = "postgres"
  engine_version    = "13.7"
  instance_class    = "db.t3.medium"

  username     = data.sops_file.secrets.data["${each.key}.master.username"]
  password     = data.sops_file.secrets.data["${each.key}.master.password"]
  storage_type = "gp2"
  multi_az     = false
  # parameter_group_name = "default.mysql5.7"
  skip_final_snapshot = true
  #availability_zone = var.region
  auto_minor_version_upgrade = true

  max_allocated_storage   = 20
  backup_retention_period = 7
  backup_window           = "04:00-05:00"
  db_subnet_group_name    = aws_db_subnet_group.pgsqlsubnet[each.key].name
  

  

}

resource "aws_db_subnet_group" "pgsqlsubnet" {
  for_each          = local.apps
  name              = "pgsql-sbnet-${each.key}-${var.environment}"
  subnet_ids = var.subnet_ids

  tags = {
    Environment = var.environment
  }
}

resource "aws_security_group" "db" {
  name   = "service-rds-access"
  vpc_id = var.vpc_id
  

  ingress {
    description = "Postgres from VPC"
    from_port   = 5432
    to_port     = 5432
    protocol    = "tcp"
    cidr_blocks = [var.vpc_cidr_block]
    security_groups = var.allowed_security_groups 
    
  }
}

`

### Steps to Reproduce

Created DB via provided module and then then try to delete via terraform you should endup with error of not having access.

### Debug Output

NA

### Panic Output

NA

### Would you like to implement a fix?

None

**Comment by gdavison** [comment]
Hi @Snehil03. From the error message, it looks like the role that you're using (`arn:aws:sts::REDATED:assumed-role/TerraformProduction/aws-go-sdk-1676903168369412529`) doesn't have permissions to perform the operation `rds:DeleteDBSubnetGroup` on your subnet. You'll need to make sure that the policies attached to that role have the permission to perform that operation. If the permissions for that role are also managed by Terraform, you may need to add a [`depends_on` block](https://developer.hashicorp.com/terraform/language/meta-arguments/depends_on) to ensure that it still exists when the subnet is being deleted.

I'm going to close this issue. If you still see this error, please create a new issue with the IAM policy included and let us know how the IAM policy is managed.

**Comment by Snehil03** [comment]
Hello @gdavison 
I would like to know why it states aws-go-sdk-1676903168369412529, it seems invoking an internal component.
Could you please let me know where i know more about it?

Also, this issue i started to face recently with other cluster roles as well .
Thanks,
Snehil

**Comment by gdavison** [comment]
@Snehil03, the role `arn:aws:sts::REDATED:assumed-role/TerraformProduction/aws-go-sdk-1676903168369412529` is the role that you're running Terraform with. It's an IAM role in your AWS account, not something created by the provider.
