### ISSUE TITLE
[Docs]: Website link building for headings.

### ISSUE THREAD

**Issue by theherk** [hashicorp/terraform-provider-aws#29510]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl.html#action

### Description

It seems the html generation for the website documentation doesn't build links the same for `h3` and `h4`. If you see the documentation for [Resource: aws_wafv2_web_acl](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl.html#rule), you should be able to click on `action` to go to the "action" section just below. It is generated via:

```markdown
#### `action`
```

This is correctly linked when viewing the markdown file [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/wafv2_web_acl.html.markdown#action), but not on the website. Since others are, for example [default_action](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl.html#default_action), I assume this is just a difference in website generation.

In summary,

```markdown
### `default_action`
```

generates to:

```html
<h3 id="default_action">
  <a href="#default_action" class="anchor" name="default_action">
    <code>default_action</code>
  </a>
</h3>
```

However,

```markdown
#### `action`
```

generates to:

```html
<h4>
  <code>action</code>
</h4>
```

This should probably yield:

```html
<h4 id="action">
  <a href="#action" class="anchor" name="action">
    <code>action</code>
  </a>
</h4>
```

I have not looked into how this process actually works, but I'd be happy to fix it it should be fixed.

### References

- [Resource: aws_wafv2_web_acl](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl.html#rule)
- [source markdown](https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/wafv2_web_acl.html.markdown#action)
- [working example - default_action](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl.html#default_action)

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @theherk 👋 Thank you for taking the time to raise this! I've opened a documentation pull request to address the issues you mentioned here 🙂
