### ISSUE TITLE
Terraform import inside terraform main.tf

### ISSUE THREAD

**Issue by medusaalb** [hashicorp/terraform-provider-aws#29546]
### Description

Good morning,
Is it possible to add "terraform import" inside a terraform main.tf

Thanks in advance

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @medusaalb 👋 Thank you for taking the time to raise this! We generally try to scope issues in this repository to reporting issues or feature requests for the AWS Provider specifically, so we'll close this one out. With that said, while the functionality that you're requesting is not currently possible, it is one of the features [to be included in Terraform 1.5.0](https://github.com/hashicorp/terraform/blob/v1.5/CHANGELOG.md).
