### ISSUE TITLE
[Enhancement]: ALB. XFF attribute

### ISSUE THREAD

**Issue by AndreiPaulau** [hashicorp/terraform-provider-aws#29565]
### Description

Hello,

Would be great to have a possibility to mange aws_lb attribute XFF header processing mode via [routing.http.xff_header_processing.mode](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/x-forwarded-headers.html), so the user can only get Client IP

Many thanks!

### Affected Resource(s) and/or Data Source(s)

aws_lb

### Potential Terraform Configuration

```terraform
xff_header (optional)
possible values append / preserve / remove
```

### References

[routing.http.xff_header_processing.mode](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/x-forwarded-headers.html)

### Would you like to implement a fix?

None

**Comment by paulz** [comment]
we would love to use this feature to get client IP, so we can have set some reasonable request rate limits.

**Comment by AndreiPaulau** [comment]
Looks like resolved via https://github.com/hashicorp/terraform-provider-aws/pull/29792
need to check
