### ISSUE TITLE
[Enhancement]: opensearch datasource for appsync

### ISSUE THREAD

**Issue by ts-mini** [hashicorp/terraform-provider-aws#29579]
### Description

Currently only "AMAZON_ELASTICSEARCH" is available as a type on appsync datasources - I would like to have `AMAZON_OPENSEARCH_SERVICE` be available, along with its config block

### Affected Resource(s) and/or Data Source(s)

aws_appsync_datasource

### Potential Terraform Configuration

```terraform
resource "aws_appsync_datasource" "search" {
  name             = "_${local.formal_datasource_name}_search"
  api_id           = aws_appsync_graphql_api.appsync.id
  service_role_arn = aws_iam_role.iam_appsync_role.arn
  type             = "AMAZON_OPENSEARCH_SERVICE"

  opensearchservice_config {
    endpoint = aws_opensearch_domain.search.endpoint
  }
}
```

### References

[I've attempted the fix here](https://github.com/hashicorp/terraform-provider-aws/pull/29578)

### Would you like to implement a fix?

Yes

**Comment by roman-grygorovych** [comment]
Please, merge it ASAP
