### ISSUE TITLE
aws_iam_access_key with keybase pgp_key has no attribute encrypted_secret

### ISSUE THREAD

**Issue by simonvanderveldt** [hashicorp/terraform-provider-aws#2958]
### Terraform Version
0.11.2

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_iam_access_key

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aws_iam_access_key" "access_key" {
  user    = "someuser"
  pgp_key = "keybase:<someuser>"
}

output "access_key_secret" {
  value = "${aws_iam_access_key.access_key.encrypted_secret}"
}
```

### Expected Behavior
encrypted_secret should be available

### Actual Behavior
encrypted_secret isn't available
```
Error: Error running plan: 1 error(s) occurred:

* output.access_key_secret: Resource 'aws_iam_access_key.access_key' does not have attribute 'encrypted_secret' for variable 'aws_iam_access_key.access_key.encrypted_secret'
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` or `terraform plan`

### Important Factoids
This does work on 0.10.8
It started failing on 0.11.0 and still fails on 0.11.2

**Comment by bnordbo** [comment]
We saw the same problem on 0.11.2 when creating an `aws_iam_access_key` for a Keybase user that did not have a PGP key. The encrypted secret would then be empty, and Terraform would fail. In our case the solution was to add a PGP key to the Keybase account, taint the resource and re-run.

**Comment by chitopunk** [comment]
@bnordbo  We experienced the same, how did you taint the resource?

**Comment by antdou** [comment]
@chitopunk you have to run  `terraform taint <your ressource>`

**Comment by rhysjtevans** [comment]
Experiencing the same thing in v0.11.8

**Comment by xluffy** [comment]
I don't use keybase, just use pgp base64, same issue

```
> terraform version
Terraform v0.11.11
+ provider.aws v1.60.0
+ provider.local v1.1.0
+ provider.template v2.1.0
```

```
resource "aws_iam_access_key" "default" {
  user = "${aws_iam_user.default.name}"
  pgp_key = "<gpg public key | base64>"
}


output "secret_access_key" {
  description = "The encrypted key of access key"
  value       = "${aws_iam_access_key.default.encrypted_secret}"
}
```

When i run `terraform apply`

```
Error: Error running plan: 1 error(s) occurred:

*output.secret_access_key: Resource 'aws_iam_access_key.default' does not have attribute \
  'encrypted_secret' for variable 'aws_iam_access_key.default.encrypted_secret'
```
