### ISSUE TITLE
[Enhancement]: aws_transfer_workflow doesn't have decrypt type

### ISSUE THREAD

**Issue by DodgeCamaro** [hashicorp/terraform-provider-aws#29606]
### Description

Currently, only four types (COPY, CUSTOM, DELETE, and TAG) of AWS Transfer Family are available for Workflow - I would like to have the DECRYPT type.

### Affected Resource(s) and/or Data Source(s)

aws_transfer_workflow

### Potential Terraform Configuration

```terraform
resource "aws_transfer_workflow" "example" {
  steps {
    decrypt_step_details {
      name                 = "string"
      type                 = "PGP"
      source_file_location = "string"
      overwrite_existing   = bool
      destination_file_location {
        s3_file_location = {
          bucket = "string",
          key    = "string"
        }
        efs_file_location = {
          file_system_id = "string",
          path           = "string"
        }

      }
    }
    type = "DECRYPT"
  }
}
```

### References

AWS Announcement: https://aws.amazon.com/about-aws/whats-new/2022/12/aws-transfer-family-built-in-pgp-decryption-file-uploads/
User Guide: https://docs.aws.amazon.com/transfer/latest/userguide/nominal-steps-workflow.html#decrypt-step-details
AWS CLI doc - https://awscli.amazonaws.com/v2/documentation/api/latest/reference/transfer/create-workflow.html
AWS Transfer Family Guide - https://docs.aws.amazon.com/transfer/latest/userguide/nominal-steps-workflow.html#decrypt-step-details

### Would you like to implement a fix?

None

**Comment by bennylu2** [comment]
What version of provider are you using? I believe the latest version already supports

**Comment by DodgeCamaro** [comment]
The latest version doesn't support Decrypt Workflow

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_workflow#workflow-steps
https://github.com/hashicorp/terraform-provider-aws/blob/v4.56.0/internal/service/transfer/workflow.go

**Comment by bennylu2** [comment]
Ah I see, I can probably pick this up
