### ISSUE TITLE
[Docs]: conflicting information about type under Secondary Artifacts

### ISSUE THREAD

**Issue by vgomez-reis** [hashicorp/terraform-provider-aws#29614]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codebuild_project#arn

### Description

Conflicting information under secondary artifacts.   First it states in some of the block variables if Type is this or that,  but  the type description states only valid value is S3.   So is it true that you can have other types,  or is this whole block only for S3?     Also about documentation  in general ,  all these "variables/parameters" must include in the same description the type.(string, number, list, bool etc) 

[location](Optional) Information about the build output artifact location. If type is set to CODEPIPELINE or NO_ARTIFACTS, this value is ignored. If type is set to S3, this is the name of the output bucket. If path is not also specified, then location can also specify the path of the output artifact in the output bucket

[type]- (Required) Build output artifact's type. The only valid value is S3.

(https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codebuild_project#type) 

### Would you like to implement a fix?

None

**Comment by bennylu2** [comment]
Looks like docs are outdated, will open a PR
