### ISSUE TITLE
[Docs]: aws_appsync_datasource: Value AMAZON_EVENTBRIDGE for argument type is not documented

### ISSUE THREAD

**Issue by andysteinwachs** [hashicorp/terraform-provider-aws#29625]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appsync_datasource

### Description

The resource documentation for resource type `aws_appsync_datasource` is missing information about a value for the argument `type`.

One valid value for argument `type` is `AMAZON_EVENTBRIDGE`. There is no documentation for how this needs to be configured. The Terraform provider does validate correctly if the type attribute is specified as `AMAZON_EVENTBRIDGE`, but it is unclear what further attributes or blocks are required.

I was expecting that a block similar to
```
  eventbridge_config {
    event_bus_arn = var.event_bus.arn
  }
```
could work, following the convention for the other resource type blocks, but Terraform validates this as `Unsupported block type`. 

If the feature is not implemented yet, I am happy to add a feature request.

_Further reads:_

AWS Doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-datasource.html 
AWS Doc for EventBridgeConfig: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-datasource-eventbridgeconfig.html

### Would you like to implement a fix?

None

**Comment by bennylu2** [comment]
It has not been implemented, feel free to open a PR or feature enhancement
