### ISSUE TITLE
Terraform forces replacement on all lambdas and all their dependent resources when there is a change in lambda config

### ISSUE THREAD

**Issue by diana8808** [hashicorp/terraform-provider-aws#29653]
### Terraform Core Version

v1.1.9

### AWS Provider Version

v3.48.0

### Affected Resource(s)

aws_lambda_function

### Expected Behavior

Terraform should be able to update the package type config of existing lambda successfully.

### Actual Behavior

Terraform forces replacement on both lambdas and their dependent resources like cloudwatch log groups, event rules, targets, lambda permissions etc and issue seen when trying to recreate the lambda.

### Terraform Configuration Files

Terraform apply shows error "ResourceConflictException: Function already exist".

```
  **# aws_lambda_function.api must be replaced**
+/- resource "aws_lambda_function" "api" {
      ~ architectures                  = [
          - "x86_64",
        ] -> (known after apply)
      ~ arn                            = "arn:aws:lambda:ap:00000:function:test-api" -> (known after apply)
      + handler                        = "FunctionHandlerAsync"
      ~ id                             = "test-api" -> (known after apply)
      - image_uri                      = "imageuri" -> null
      ~ invoke_arn                     = "gateway" -> (known after apply)
      - kms_key_arn                    = "key" -> null
      ~ last_modified                  = "2023-02-24T13:59:53.000+0000" -> (known after apply)
      - layers                         = [] -> null
      ~ package_type                   = "Image" -> "Zip" **# forces replacement**
      + publish                        = false
      ~ qualified_arn                  = "arn:aws:lambda:ap:00000:function:test-api:8" -> (known after apply)
      ~ qualified_invoke_arn           = "arn:aws:apigateway:ap" -> (known after apply)
      + runtime                        = "dotnetcore3.1"
      + s3_bucket                      = "test-api"
      + s3_key                         = "test-api.zip"
      + s3_object_version              = (known after apply)
      + signing_job_arn                = (known after apply)
      + signing_profile_version_arn    = (known after apply)
      ~ source_code_hash               = "hash" -> "newhash"
      ~ source_code_size               = 0 -> (known after apply)
      - tags                           = {} -> null
      ~ version                        = "8" -> (known after apply)
        # (6 unchanged attributes hidden)
      ~ ephemeral_storage {
          ~ size = 512 -> (known after apply)
        }
      - image_config {
          - command     = [
              - "FunctionHandlerAsync",
            ] -> null
          - entry_point = [] -> null
        }
      - timeouts {}
      ~ tracing_config {
          ~ mode = "PassThrough" -> (known after apply)
        }
      ~ vpc_config {
          ~ vpc_id             = "vpc" -> (known after apply)
            # (2 unchanged attributes hidden)
        }
        # (1 unchanged block hidden)
    }
```
```
Error: creating Lambda Function (scoot-e2e-mmb-api): operation error Lambda: CreateFunction, https response error StatusCode: 409, RequestID: 10fa737f-89dd-4a88-9aa3-5e896436feb7, ResourceConflictException: Function already exist: test-api
with aws_lambda_function.api,
on api.tf line 44, in resource "aws_lambda_function" "api":
44: resource "aws_lambda_function" "api" {
```

### Steps to Reproduce

1. Run terraform apply by adding lambda with type of Image.
2. Change package type config to Zip and runtime to dotnetcore3.1.
3. Terraform plan shows force replacement of lambda and its dependent resources.
4. Terraform apply throws "Error creating Lambda function: ResourceConflictException: Function already exist" when recreating the lambda, instead of updating the lambda.

### References

This issue is related to [hashicorp/terraform/issues/26060](https://github.com/hashicorp/terraform/issues/26060)

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @diana8808 👋 Thank you for taking the time to raise this! I noticed you're using an older version of the AWS provider. Since 3.48.0, there have been numerous updates to the `aws_lambda_function` resource, some of which address issues of errors on creation. Are you able to update to a newer version of the provider to test whether that resolves the issue?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
