### ISSUE TITLE
[Bug]: Sensitivity level parameter is not available in sqli_match_statement (aws_wafv2_web_acl resource

### ISSUE THREAD

**Issue by tamilver-amzn** [hashicorp/terraform-provider-aws#29672]
### Terraform Core Version

latest

### AWS Provider Version

latest

### Affected Resource(s)

aws_waf_web_acl  sqli_match_statement

### Expected Behavior

Since sensitivity parameter is not available, waf sqli_match_statement is creating without SensitivityLevel. This value either it is LOW or HIGH.

Refer: https://aws.amazon.com/about-aws/whats-new/2022/07/aws-waf-sensitivity-levels-sql-injection-rule-statements/

This is available in cloudformation not in terraform.

### Actual Behavior

Since SensitivityLevel parameter is not available, WAF rule is getting creating without that value.

### Terraform Configuration Files

NA

### Steps to Reproduce

terraform init
terraform apply

### Would you like to implement a fix?

None

**Comment by tyler-robbins2** [comment]
Hi there,

We are trying to follow the recommendations from this article: https://docs.aws.amazon.com/en_us/waf/latest/developerguide/waf-rule-statement-type-sqli-match.html

> The HIGH setting detects more SQL injection attacks, and is the recommended setting.

Is there any movement on this enhancement/bug?

We have to manually modify the value to HIGH in the AWS WAF UI, which breaks terraform state and gets overwritten whenever we update.
