### ISSUE TITLE
[Enhancement]: aws_lb missing support for additional LoadBalancerAttributes

### ISSUE THREAD

**Issue by phene** [hashicorp/terraform-provider-aws#29684]
### Description

There are several load balancer attributes described [here](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_LoadBalancerAttribute.html) that are not presently supported by the Terraform resources `aws_lb`:

* `routing.http.xff_client_port.enabled`
* `routing.http.xff_header_processing.mode`
* `routing.http.x_amzn_tls_version_and_cipher_suite.enabled`

### Affected Resource(s) and/or Data Source(s)

* aws_lb

### Potential Terraform Configuration

```terraform
resource "aws_lb" {
  enable_xff_client_port_header = true
  xff_header_processing = "preserve"
  enable_tls_version_and_cipher_suite_headers = true
}
```

### References

https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_LoadBalancerAttribute.html

### Would you like to implement a fix?

No

**Comment by ericrichtert** [comment]
See also #22049

**Comment by mtt88** [comment]
I put a PR in for this without realising there was an existing issue and PR open. I'll leave it open for now, but please feel free to close it in favour of the existing.
