### ISSUE TITLE
[New Service]: AWS Verified Access

### ISSUE THREAD

**Issue by silvaalbert** [hashicorp/terraform-provider-aws#29689]
### Description

Request to have new service + resources created for AWS Verified Access

### Requested Resource(s) and/or Data Source(s)

- [ ] add resource: aws_verifiedaccess_endpoint
- [ ] add resource: aws_verifiedaccess_endpoint_policy
- [ ] #29784
- [ ] #29742
- [ ] add resource: aws_verifiedaccess_instance_logging_configuration
- [ ] #29723
- [ ] #29781

### References

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/operation-list-verified-access.html

### Would you like to implement a fix?

Yes

**Comment by ewbankkit** [comment]
> Today, AWS announces the general availability of AWS Verified Access, ...

[Announcement](https://aws.amazon.com/about-aws/whats-new/2023/04/aws-verified-access-generally-available/).
[Blog post](https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-aws-verified-access-general-availability/).

**Comment by ZsoltPath** [comment]
@ewbankkit is someone working on this?

**Comment by NetDevAutomate** [comment]
Hi folks, I'm picking this up and will be working on this for the instance resources.

**Comment by markoskandylis** [comment]
Hi, I will start working on verified access trust provider resources

**Comment by davidferguson-cr** [comment]
Can we also add data sources for these resources?  Use case: I am sharing a Verified Access Group from another stack/account, which I want to provision an Endpoint in in another stack/account.

**Comment by yob** [comment]
For issue subscribers like me who haven't checked back in a while: I just discovered the core resources required to manage verified access via terraform have been available since late 2023 (over v5.16.2 -> v5.24.0) 🎉
