### ISSUE TITLE
[Bug]: aws_api_gateway_resource - inconsistent requirement for path_part

### ISSUE THREAD

**Issue by saulortega** [hashicorp/terraform-provider-aws#29694]
### Terraform Core Version

1.3.7

### AWS Provider Version

4.56.0

### Affected Resource(s)

aws_api_gateway_resource

### Expected Behavior

Consistent required or not required `path_part`.

#### Scenario 1:

```terraform
resource "aws_api_gateway_resource" "X" {
  rest_api_id = aws_api_gateway_rest_api.YYYY.id
  parent_id   = aws_api_gateway_rest_api.YYYY.root_resource_id
  # No path_part
}
```

```sh
terraform apply

Error: Missing required argument

The argument "path_part" is required, but no definition was found.
```

<br><br>

#### Scenario 2:

```terraform
resource "aws_api_gateway_resource" "X" {
  rest_api_id = aws_api_gateway_rest_api.YYYY.id
  parent_id   = aws_api_gateway_rest_api.YYYY.root_resource_id
  path_part   = "/"
}
```

```sh
terraform apply

Error: updating API Gateway Resource (xxxxxxxx): BadRequestException: Root resource cannot update its pathPart.
```

### Terraform Configuration Files

```terraform

variable "AWS_ACCESS_KEY_ID" {
  type = string
}

variable "AWS_SECRET_ACCESS_KEY" {
  type = string
}

variable "AWS_SESSION_TOKEN" {
  type = string
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.56"
    }
  }
}

provider "aws" {
  region     = "us-west-2"
  access_key = var.AWS_ACCESS_KEY_ID
  secret_key = var.AWS_SECRET_ACCESS_KEY
  token      = var.AWS_SESSION_TOKEN
}

resource "aws_api_gateway_rest_api" "YYYY" {
  name           = "YYYY"
  api_key_source = "HEADER"
}

resource "aws_api_gateway_resource" "X" {
  rest_api_id = aws_api_gateway_rest_api.YYYY.id
  parent_id   = aws_api_gateway_rest_api.YYYY.root_resource_id
}
```

### Steps to Reproduce

1. `terraform apply` without `path_part`.
2. `terraform apply` with `path_part`.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @saulortega 👋 Thank you for taking the time to raise this! Can you provide a bit of clarity on what you're looking to accomplish with the `aws_api_gateway_resource.path_part` set to `null` or `"/"`? The error that you're receiving is coming from the AWS API directly, and the `aws_api_gateway_rest_api` resource already sets up the root resource (as evident by the `root_resource_id` attribute). My understanding is that the `aws_api_gateway_resource` is used to set up additional API resources, and so wouldn't be used to set up the root resource.

**Comment by saulortega** [comment]
Sorry for the late reply.

I imported that resource. When trying to adjust it as it's in AWS, via `terraform apply` (to see what the changes are, what do I need to add), I got those errors.

> Can you provide a bit of clarity on what you're looking to accomplish with the `aws_api_gateway_resource.path_part` set to `null` or `"/"`?

To match as it's in AWS after imported.



> The error that you're receiving is coming from the AWS API directly, and the `aws_api_gateway_rest_api` resource already sets up the root resource (as evident by the `root_resource_id` attribute)

It seems so for Scenario 2 (with path_part). It doesn't seem so to me for Scenario 1 (without path_part). So, it seems to me that `aws_api_gateway_resource.path_part` is flagged as required by Terraform, but it isn't required by AWS.

**Comment by justinretzolk** [comment]
Hey @saulortega 👋 Thank you for the additional clarification. The `aws_api_gateway_resource` resource uses the `CreateResource` function from the AWS Go SDK. The [input type]((https://docs.aws.amazon.com/sdk-for-go/api/service/apigateway/#CreateResourceInput) for that function indicates that the `path_part` field is required, which is why it's a required field in Terraform.

Taking a step back from that, can you give me a better idea of why you're looking to import the root resource to the `aws_api_gateway_resource`? The `aws_api_gateway_rest_api` resource creates the root resource and exposes similar attributes to the `aws_api_gateway_resource` resource, with some minor naming changes:

| Attribute | `aws_api_gateway_rest_api` | `aws_api_gateway_resource` |
| --------- | ----------------------------- | ----------------------------- |
| Resource Identifier | `root_resource_id` | `id` |
| Resource Path | Not exported, but known to be `/` | `path` |

**Comment by saulortega** [comment]
> can you give me a better idea of why you're looking to import the root resource to the `aws_api_gateway_resource`?

Well, why not? It's logical to me to want to import ALL resources. But as per your explanation, maybe you are right, maybe we don't need to import the root resource, only that that should be clarified in docs.

In any case, I'm no longer using `aws_api_gateway_resource`. I decided to use the `body` property of `aws_api_gateway_rest_api` with OpenAPI spec. That method seems to be more handy because I don't need `aws_api_gateway_resource`, nor `aws_api_gateway_method`, nor `aws_api_gateway_integration`, nor `aws_api_gateway_method_response`...

Thank you. I believe you are right, we don't need to import the root resource.
