### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by macqpinto** [hashicorp/terraform-provider-aws#29704]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate

### Description

In the the attribute reference section, the ID is described as ARN value which is not correct. 

[id](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate#id) - ARN of the certificate

This should be changed to 

[id](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate#id) - ID of the certificate

### Would you like to implement a fix?

Yes

**Comment by rahul-amzn** [comment]
will check.

**Comment by mattburgess** [comment]
The `id` and `arn` attributes are equivalent: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/acmpca/certificate.go#L154.

This same pattern and wording in the accompanying documentation is common across a number of resources, e.g. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_topic_subscription#attributes-reference.

**Comment by justinretzolk** [comment]
Hey @macqpinto 👋 Thanks for taking the time to raise this! As Matt mentioned above, in this case, the `id` is set to the ARN, so the documentation is correct as it stands. With that in mind, we'll close this issue out. If you feel I've done this in error, please do let me know.
