### ISSUE TITLE
[Bug]: Getting "The ARN isn't valid" when applying a aws_wafv2_web_acl_logging_configuration resource

### ISSUE THREAD

**Issue by oswaldquek** [hashicorp/terraform-provider-aws#29705]
### Terraform Core Version

~> 1.0

### AWS Provider Version

4.50.0

### Affected Resource(s)

aws_wafv2_web_acl_logging_configuration

### Expected Behavior

Applying that resource should have enabled logging on the WAF I configured.

### Actual Behavior

I get the following error:
```tf
│ Error: error putting WAFv2 Logging Configuration for resource (arn:aws:wafv2:us-east-1:<account-number>:global/webacl/test-product-page-waf/a344345b-6f0c-4f79-82c8-c3c72004ffe0): WAFInvalidParameterException: Error reason: The ARN isn't valid. A valid ARN begins with arn: and includes other information separated by colons or slashes., field: RESOURCE_ARN, parameter: arn:aws:wafv2:us-east-1:<account-number>:global/webacl/test-product-page-waf/a344345b-6f0c-4f79-82c8-c3c72004ffe0
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "16f31468-e597-4852-b5ac-5c8a735f864d"
│   },
│   Field: "RESOURCE_ARN",
│   Message_: "Error reason: The ARN isn't valid. A valid ARN begins with arn: and includes other information separated by colons or slashes., field: RESOURCE_ARN, parameter: arn:aws:wafv2:us-east-1:<account-number>:global/webacl/test-product-page-waf/a344345b-6f0c-4f79-82c8-c3c72004ffe0",
│   Parameter: "arn:aws:wafv2:us-east-1:<account-number>:global/webacl/test-product-page-waf/a344345b-6f0c-4f79-82c8-c3c72004ffe0",
│   Reason: "The ARN isn't valid. A valid ARN begins with arn: and includes other information separated by colons or slashes."
│ }
```

### Terraform Configuration Files

```tf
resource "aws_cloudwatch_log_group" "product_page_waf" {
  provider = aws.us-east-1

  name              = "aws-waf-logs-product-page-${var.environment}"
  retention_in_days = 30
}

resource "aws_wafv2_web_acl" "product_page" {
  provider = aws.us-east-1

  name  = "${local.aws_account}-product-page-waf"
  scope = "CLOUDFRONT"

  default_action {
    allow {}
  }

  visibility_config {
    cloudwatch_metrics_enabled = true
    metric_name                = "waf-cloudfront"
    sampled_requests_enabled   = true
  }

  rule {
    name     = "LimitFiveThousandRequestsEveryFiveMinutes"
    priority = 0

    action {
      block {}
    }

    statement {
      rate_based_statement {
        limit = 5000
      }
    }

    visibility_config {
      cloudwatch_metrics_enabled = true
      metric_name                = "requests-per-five-minutes"
      sampled_requests_enabled   = false
    }
  }
}

resource "aws_wafv2_web_acl_logging_configuration" "product_page" {
  log_destination_configs = [aws_cloudwatch_log_group.product_page_waf.arn]
  resource_arn            = aws_wafv2_web_acl.product_page.arn

  depends_on = [aws_cloudwatch_log_group.product_page_waf, aws_wafv2_web_acl.product_page]
}
```

### Steps to Reproduce

Standard `terraform apply` on the above configuration.

As a workaround, I thought I'd configure the logging directly in the console and try to import the aws_wafv2_web_acl_logging_configuration resource. The configuration worked in the console (see screenshot) but I get the same error when terraform importing it using `terraform import`.

<img width="957" alt="waf-logging-config" src="https://user-images.githubusercontent.com/9698354/221897111-27e56942-b06c-4074-891b-4b3e857edd6a.png">

As another test I deleted the `resource "aws_wafv2_web_acl_logging_configuration" "product_page"` resource, did a `terraform plan` but terraform didn't even pick up that logging should be disabled on the WAF.

### References

I've seen https://github.com/hashicorp/terraform-provider-aws/issues/13955#issuecomment-650142368 but the solution for that is naming the log group correctly for which I have already done.

### Would you like to implement a fix?

None

**Comment by oswaldquek** [comment]
### Steps to Reproduce

Standard `terraform apply` on the above configuration.

As a workaround, I thought I'd configure the logging directly in the console and try to import the aws_wafv2_web_acl_logging_configuration resource. The configuration worked in the console (see screenshot) but I get the same error when terraform importing it using `terraform import`.

<img width="957" alt="waf-logging-config" src="https://user-images.githubusercontent.com/9698354/221897111-27e56942-b06c-4074-891b-4b3e857edd6a.png">


As another test I deleted the `resource "aws_wafv2_web_acl_logging_configuration" "product_page"` resource, did a `terraform plan` but terraform didn't even pick up that logging should be disabled on the WAF.

**Comment by justinretzolk** [comment]
Hey @oswaldquek 👋 Thank you for taking the time to raise this! I'm mostly just triaging this issue for now, but I noticed that you're using an aliased provider for the `aws_cloudwatch_log_group` and `aws_wafv2_web_acl` resourced, but not for the `aws_wafv2_web_acl_logging_configuration` resource. Is this perhaps an issue of the former two being in a different region than the latter is expecting based on the configuration?

**Comment by oswaldquek** [comment]
@justinretzolk Thanks for getting back to me. It looks like that solved the problem! I did use an aliased provider before but it might not have worked because I didn't set the aliased provider on the `aws_cloudwatch_log_group` resource right from the get go and terraform must've somehow got into a bind.
