### ISSUE TITLE
[Enhancement]: Allow list of ipv4 cidr blocks for aws_vpc_security_group_ingress_rule

### ISSUE THREAD

**Issue by jlosito** [hashicorp/terraform-provider-aws#29719]
### Description

It would be nice if one could provide a list of IPv4 CIDR block to the aws_vpc_security_group_ingress_rule as one can do with the aws_security_group and aws_security_group_rule resources . I understand that the aws_vpc_security_group_ingress_rule resource was supposed to fix some of the issues with the other resources, but was there a specific reason as to why the ability of providing multiple cidr blocks was removed?

### Affected Resource(s) and/or Data Source(s)

* aws_vpc_security_group_ingress_rule

### Potential Terraform Configuration

```terraform
resource "aws_vpc_security_group_ingress_rule" "allow_stuff_in" {
  security_group_id = aws_security_group.foobar.id
  cidr_ipv4 = ["10.0.0.5/32", "192.168.0.10/32", "10.0.1.0/24"]
  ip_protocol = "tcp"
  from_port = 0
  to_port = 65535
}
```

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group#cidr_blocks
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_security_group_ingress_rule#cidr_ipv4
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule#cidr_blocks

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@jlosito Thanks for raising this issue 👏.
In fact not supporting lists of CIDR blocks (and other sources or destinations) was exactly one of the uses cases for adding the new resources 😄. The new resources map 1-to-1 with the underlying [EC2 `SecurityGroupRule` object](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SecurityGroupRule.html) (with additional separation by `ingress` and `egress` as they have distinct APIs for authorization).

You can use the Terraform [`for_each` syntax](https://developer.hashicorp.com/terraform/language/meta-arguments/for_each) to a separate rule for each CIDR block in the list.

We should enhance the documentation with some examples showing this.

**Comment by jlosito** [comment]
@ewbankkit I see. Thank you for the explanation.
