### ISSUE TITLE
[Bug]: provider shared_credential_files and profile parameters not working

### ISSUE THREAD

**Issue by tcarecolin** [hashicorp/terraform-provider-aws#29711]
### Terraform Core Version

v1.3.9

### AWS Provider Version

4.56.0

### Affected Resource(s)

provider aws
backend

### Expected Behavior

terraform should be able to authenticat to initialize backend with s3 using a custom aws profile
provider should use aws creds profile according to variables "profile", "shared_credentials_files" or "shared_configuration_files"

### Actual Behavior

i configured my project to use an s3 backend to store the .tfstate
i configured my aws provider with variables "shared_credentials_files" and a "profile" [custom] but it keeps using the profile [default]
(all aws env variables have been previously unset, no hard-coded access-keys are used)

### Relevant Error/Panic Output Snippet

```shell
Error refreshing state: AccessDenied: Access Denied
	status code: 403, request id: XXXXXXXXXXXXXXX, host id: YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.56.0"
    }
  }
  backend "s3" {
    bucket    = "my-tfstate-bucket"
    key         = "terraform/terraform.tfstate"
    encrypt   = true
    region    = "eu-west-1"
  }
}


provider "aws" {
  shared_config_files         = ["~/.aws/config"]
  shared_credentials_files = ["~/.aws/credentials"]
  profile                              = "custom"
  region                              = "eu-west-1"
}
```

### Steps to Reproduce

unset all aws env variables
remove any aws hard coded credentials in .tf file

create a ~/.aws/credentials fil like so : 

```
[default]
aws_access_key_id = xxxxxxxxxxx
aws_secret_access_key = xxxxxxxxxxxxx
[custom]
aws_access_key_id = yyyyyyyyyy
aws_secret_access_key = yyyyyyyyyyyy
```

create a tf configuration that uses an s3 backend, and a provider configured to use [custom] aws profile

### Important Factoids

Important note:

i achieved to make my configuration work, and was able to run `terraform init` by changing my configuration like so:

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.56.0"
    }
  }
  backend "s3" {
    bucket      = "my-tfstate-bucket"
    key           = "terraform/terraform.tfstate"
    encrypt    = true
    region      = "eu-west-1"
    profile      = "custom"
  }
}


provider "aws" {
  region                   = "eu-west-1"
}
```

provider does no longer uses 'shared_credentials_file' or 'ptofile' parameters
the 'profile' parameter has been added to the backend block

that way my configuration works with profile [custom]

so i am not totaly sure if thats a provider bug or a documentation issue on https://registry.terraform.io/providers/hashicorp/aws/latest/docs

### Would you like to implement a fix?

None

**Comment by gdavison** [comment]
Hi @tcarecolin, thank you for submitting this.

The `s3` backend and `aws` provider are configured separately, so you will need to configure both. The documentation for the `s3` backend can be found at https://developer.hashicorp.com/terraform/language/settings/backends/s3.

If that doesn't work, please include the debug log. See https://developer.hashicorp.com/terraform/internals/debugging for instructions on enabling debug logging.

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
