### ISSUE TITLE
[Bug]: aws_ecs_task_definition throws error when task definition is deleted outside of terraform

### ISSUE THREAD

**Issue by nwsparks** [hashicorp/terraform-provider-aws#29749]
### Terraform Core Version

1.3.4

### AWS Provider Version

4.38.0

### Affected Resource(s)

aws_ecs_task_definition 

### Expected Behavior

it should recreate the missing task definition

### Actual Behavior

plans/applies throw an error `Error: ClientException: Unable to describe task definition.`

### Relevant Error/Panic Output Snippet

```shell
data.aws_subnet.subnets["subnet-"]: Read complete after 0s [id=subnet-]
data.aws_subnet.subnets["subnet-"]: Read complete after 0s [id=subnet-]
data.aws_subnet.subnets["subnet-"]: Read complete after 0s [id=subnet-]
╷
│ Error: ClientException: Unable to describe task definition.
│
│   with aws_ecs_task_definition.service,
│   on test.tf line 27, in resource "aws_ecs_task_definition" "service":
│   27: resource "aws_ecs_task_definition" "service" {
│
╵
```

### Terraform Configuration Files

```hcl
resource "aws_ecs_task_definition" "service" {
  family = "test"
  container_definitions = jsonencode([
    {
      name      = "test"
      image     = "service-first"
      cpu       = 10
      memory    = 512
      essential = true
      portMappings = [
        {
          containerPort = 80
          hostPort      = 80
        }
      ]
    }
  ])
}
```

### Steps to Reproduce

1. create a new task def via terraform
2. in the aws console unregister it
3. change the drop down to display unregistered tasks and choose to delete the task
4. change the drop down to display delete in progress tasks and wait 30-60+ minutes
5. once the task disappears from delete in progress run `terraform plan`

### Important Factoids

the delete task definition functionality is new, https://aws.amazon.com/blogs/containers/announcing-amazon-ecs-task-definition-deletion/

before this there was no way to delete task definitions.

### Would you like to implement a fix?

No

**Comment by sarmad-ali-9** [comment]
I'm getting the same error since morning. I did exactly whats mentioned in steps to reproduce section. And now because of this error our whole staging environment is effected.

**Comment by caseyoneill** [comment]
I  am seeing the same issue. The task definitions were manually deleted outside of terraform

**Comment by bploetz** [comment]
Ran into this too (we recently started deleting old task defs as part of our release process) and @caseyoneill 's suggestion fixes the problem (you obviously need to recreate the resource you delete from the state file).

**Comment by JoseAFerrer** [comment]
Hi, everyone! I see the issue and understand the suggestion by @caseyoneill, but sadly I get an error while removing that:
`Error saving the state: unsupported attribute "arn_without_revision"
`
It's weird because I am not using that attribute _anywhere_ in the code... Any idea?

**Comment by bhargavpanth** [comment]
Seem to be running into this issue. In my case, I am running tests (using Terratests to spin up ECS on Localstack). The only way to get around this issue seems to be by removing the task definition from the state. I am using Terraform `v1.4.4` on darwin_arm64`. Is this a case of an un-updated Terraform version?

**Comment by david-hodgson-at-sky** [comment]
Also hit this issue following on from having having an issue with partially deleted task definitions (an AWS "feature" - state goes to DELETE_IN_PROGRESS and it's not deleted).

**Comment by DorisEckel8412** [comment]
Hi,
we run in the same error message, after deleting 1 version of the task definition outside of terraform. 
We use version 1.7.3.

**Comment by justintilson-steeltoad** [comment]
I'm getting the same error with

Terraform: 1.7.4
cdktf: 0.20.3
@cdktf/provider-aws: 19.6.0

**Comment by jani4865** [comment]
I am getting same error with aws provider 5.16.2

**Comment by rogerfar** [comment]
Unfortunately this isn't fixed yet, the issue is that I deleted some task definitions, which then go in the state DELETE_IN_PROGRESS:

```
aws ecs list-task-definitions --status DELETE_IN_PROGRESS
{
    "taskDefinitionArns": [
        "arn:aws:ecs:us-west-2:1234565:task-definition/TaskDefinition:2",
    ]
}```

But when I try to describe it:
```
aws ecs describe-task-definition --task-definition TaskDefinition

An error occurred (ClientException) when calling the DescribeTaskDefinition operation: Unable to describe task definition.
```
I think the provider needs to consider the state of the task before trying to describe it.

**Comment by vivekk-promact** [comment]
+1
