### ISSUE TITLE
[Bug]: wait_for_capacity_timeout is ignored in aws_autoscaling_group in case of insufficient capacity

### ISSUE THREAD

**Issue by akshaypatidar1999** [hashicorp/terraform-provider-aws#29753]
### Terraform Core Version

v0.15.4

### AWS Provider Version

v4.56.0

### Affected Resource(s)

* aws_autoscaling_group

### Expected Behavior

On creating an autoscaling group with multiple availability zones, if instances are not available in one of the zones then terraform should wait for capacity timeout as ASG provisions instances in other availability zones if instances are not available.

### Actual Behavior

Terraform throws `Insufficient capacity error` after 20-30 seconds though `wait_for_capacity_timeout` was set to `10min`

### Relevant Error/Panic Output Snippet

```shell
{
            "ActivityId": "cc161a83-fcb7-d8cf-f0a2-e84643376f39",
            "AutoScalingGroupName": "test-asg",
            "Description": "Launching a new EC2 instance.  Status Reason: Could not launch On-Demand Instances. InsufficientInstanceCapacity - We currently do not have sufficient i3.4xlarge capacity in the Availability Zone you requested (us-east-1f). Our system will be working on provisioning additional capacity. You can currently get i3.4xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1e. Launching EC2 instance failed.",
            "Cause": "At 2023-03-02T06:25:15Z a user request created an AutoScalingGroup changing the desired capacity from 0 to 500.  At 2023-03-02T06:25:21Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 400.",
            "StartTime": "2023-03-02T06:25:23.446000+00:00",
            "EndTime": "2023-03-02T06:25:23+00:00",
            "StatusCode": "Failed",
            "StatusMessage": "Could not launch On-Demand Instances. InsufficientInstanceCapacity - We currently do not have sufficient i3.4xlarge capacity in the Availability Zone you requested (us-east-1f). Our system will be working on provisioning additional capacity. You can currently get i3.4xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1e. Launching EC2 instance failed.",
            "Progress": 100,
            "Details": "{\"Subnet ID\":\"xxxxx\",\"Availability Zone\":\"us-east-1f\"}",
            "AutoScalingGroupARN": "arn:aws:autoscaling:us-east-1:xxxx:autoScalingGroup:ee344eba-98c2-44b9-b8fa-d69dee8b1833:autoScalingGroupName/test-asg"
},



╷
│ Error: waiting for Auto Scaling Group (test-asg) capacity satisfied: 1 error occurred:
│ 	* Scaling activity (b5061a85-2b9a-39fe-c76f-0f2bc2d1c5ba): Failed: Could not launch On-Demand Instances. InsufficientInstanceCapacity - We currently do not have sufficient i3.4xlarge capacity in the Availability Zone you requested (us-east-1f). Our system will be working on provisioning additional capacity. You can currently get i3.4xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1e. Launching EC2 instance failed.
│
│
│
│   with module.aerospike.module.aerospike_asg.aws_autoscaling_group.asg,
│   on .terraform/modules/aerospike.aerospike_asg/main.tf line 1, in resource "aws_autoscaling_group" "asg":
│    1: resource "aws_autoscaling_group" "asg" {
│
╵
```

### Terraform Configuration Files

Will add later

### Steps to Reproduce

Will add later

### References
I think the issue is in the below snippet
https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/autoscaling/group.go#L2165-L2175.
If there is any failed activity in auto scaling group `err` is returned which causes the [WaitForStateContext](https://github.com/hashicorp/terraform-plugin-sdk/blob/main/helper/resource/state.go#L54) to end

I believe this instead of calling `DescribeScalingActivities` terraform should just call `DescribeAutoscalingGroup` and check whether the desired number instances is equal to current instance count. This way we can allow asg to provision instances in different availability zones

_No response_

### Would you like to implement a fix?

Yes

**Comment by tschlechtweg** [comment]
This also happens when using EC2 spot instances. On development deployments, we often get: 
```
Error: waiting for Auto Scaling Group (<redacted>) capacity satisfied: 1 error occurred:
  * Scaling activity (<redacted>): Failed: There is no Spot capacity available that matches your request. Launching EC2 instance failed.
```
This is an error for terraform that makes terraform think the creation of the autoscaling group failed, which is not correct. In case of this error we simply wait, and then we can use the deployment, but reapplying does also fail, because in the terraform state the autoscaling group does not exist, but in reality it does.

**Comment by rheyer** [comment]
I just hit this, is there a workaround?

**Comment by surfd4wg** [comment]
I also hit this. Looking for a workaround. 

===== Error
╷
│ Error: waiting for Auto Scaling Group (production_auto_scaling_group) capacity satisfied: 2 errors occurred:
│ 	* Scaling activity (b1061cfa-7516-d2c2-8618-e7f1421845d6): Failed: Authentication Failure. Launching EC2 instance failed.
│ 	* Scaling activity (14061cfa-7515-071f-dba0-a8e4195bbfa1): Failed: Authentication Failure. Launching EC2 instance failed.
│ 
│ 
│ 
│   with aws_autoscaling_group.ecs-cluster,
│   on auto_scaling.tf line 1, in resource "aws_autoscaling_group" "ecs-cluster":
│    1: resource "aws_autoscaling_group" "ecs-cluster" {
│

**Comment by akshaypatidar1999** [comment]
We are using a workaround for this. We set `wait_for_capacity_timeout` as `0` and then manually wait till number of healthy instances are equal to the desired capacity

**Comment by mengmengmengqiang** [comment]
me too as infor below

`
Error: waiting for Auto Scaling Group (zeus) capacity satisfied: 1 error occurred:
│ 	* Scaling activity (2b361e62-f865-dc3e-25e3-57e26ae6c02f): Failed: The requested configuration is currently not supported. Please check the documentation for supported configurations. Launching EC2 instance failed.
`

**Comment by mr-karan** [comment]
+1 Facing this as well. Is the `wait_for_capacity_timeout = 0` only workaround for now?

**Comment by MadhusaiSomarathi** [comment]
Facing this error . Tried to increase the quota limit of spot requests but no use. If i try to apply terraform files again and again it is provisioning but most of the times it is failing.

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/26377.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/31551.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/25987.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/25986.

**Comment by ewbankkit** [comment]
Given that there are many different error messages that could be ignored I suggest that we add a new ("virtual attribute")[https://hashicorp.github.io/terraform-provider-aws/raising-a-pull-request/#resource-contribution-guidelines] `ignore_failed_scaling_activities` which, if configured to `true`, would cause `statusGroupCapacity` to ignore any `Failed` autoscaling activities and wait for the configured `wait_for_capacity_timeout`.
