### ISSUE TITLE
[Bug]: log_delivery_configuration is not expected in aws_elasticache_cluster where documentation clearly defines it

### ISSUE THREAD

**Issue by yalattas** [hashicorp/terraform-provider-aws#29756]
### Terraform Core Version

v1.3.2

### AWS Provider Version

3.76.1

### Affected Resource(s)

aws_elasticache_cluster

### Expected Behavior

when adding `log_delivery_configuration`, it's expected to provision cluster with log configuration

### Actual Behavior

terraform is throwing unsupported block error

### Relevant Error/Panic Output Snippet

```shell
│ Error: Unsupported block type
│ 
│   on elasticache.tf line 23, in resource "aws_elasticache_cluster" "cache_cluster":
│   23:     log_delivery_configuration {
│ 
│ Blocks of type "log_delivery_configuration" are not expected here.
```

### Terraform Configuration Files

sample of the code

```
resource "aws_elasticache_cluster" "cache_cluster" {
    cluster_id           = "mycluster"
    engine               = "redis"
    node_type            = "cache.t4g.small"
    num_cache_nodes      = 1
    parameter_group_name = "default.redis3.2"
    engine_version       = "5.0.6"
    port                 = 6379
    apply_immediately    = true
    availability_zone    = format("%sb", var.aws_region)
    az_mode              = "single-az"
    maintenance_window   = "sun:14:00-sun:15:00"
    snapshot_window      = "10:00-14:00"
    security_group_ids   = [aws_security_group.cache_security_group.id]
    subnet_group_name    = aws_elasticache_subnet_group.cache_subnet.name

    log_delivery_configuration {
        destination      = aws_cloudwatch_log_group.cache_log.name
        destination_type = "cloudwatch-logs"
        log_format       = "text"
        log_type         = "slow-log"
    }
}
```

### Steps to Reproduce

1. install terraform `Terraform v1.3.2`
2. install aws provider `aws v3.76.1`
3. to to provision elasticache redis cluster with `log_delivery_configuration` to `cloudwatch` or `firehose`

### Important Factoids

Terraform v1.3.2
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.35.0
+ provider registry.terraform.io/hashicorp/aws v3.76.1
+ provider registry.terraform.io/hashicorp/random v3.4.3

Your version of Terraform is out of date! The latest version
is 1.3.9. You can update by downloading from https://www.terraform.io/downloads.html

### References

You can implement the same example mentioned in the below docs to reproduce the error

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_cluster#log_delivery_configuration

### Would you like to implement a fix?

None

**Comment by yalattas** [comment]
just upgraded to latest version of terraform with same issue

```
Terraform v1.3.9
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.35.0
+ provider registry.terraform.io/hashicorp/aws v3.76.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
```

**Comment by justinretzolk** [comment]
Hey @yalattas 👋 It looks like in your follow up comment, you're still using an older version of the AWS Provider -- version `3.76.1`. The `log_delivery_configuration` argument was added to the `aws_elasticache_cluster` resource in [version `4.8.0`](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#480-march-25-2022).
