### ISSUE TITLE
[Bug]: aws_lakeformation_permissions does not support IAMPrincipals

### ISSUE THREAD

**Issue by be-rock** [hashicorp/terraform-provider-aws#29767]
### Terraform Core Version

1.1.8

### AWS Provider Version

4.56.0

### Affected Resource(s)

aws_lakeformation_permissions

### Expected Behavior

`DESCRIBE` permissions granted to all Principals in the account via: `principal = "123456789012:IAMPrincipals" `

### Actual Behavior

A Terraform error is thrown

### Relevant Error/Panic Output Snippet

`Error: "principal" doesn't look like AWS Account ID (exactly 12 digits): "123456789012:IAMPrincipals"`

### Terraform Configuration Files

none to add

### Steps to Reproduce

```hcl
data "aws_caller_identity" "current" {}

resource "aws_glue_catalog_database" "database" {
  name  = "my_test_db"
}

resource "aws_lakeformation_permissions" "local_account_describe" {
  depends_on = [
    aws_glue_catalog_database.database
  ]
  principal   = "${data.aws_caller_identity.current.id}:IAMPrincipals" # <-- this
  permissions = ["DESCRIBE"]
  database {
    name       = aws_glue_catalog_database.database.name
    catalog_id = data.aws_caller_identity.current.id
  }
}

```

### References

- https://docs.aws.amazon.com/lake-formation/latest/dg/granting-db-perms-api.html
- https://docs.aws.amazon.com/lake-formation/latest/dg/granting-location-permissions-external.html
- https://docs.aws.amazon.com/lake-formation/latest/dg/granting-location-permissions-local.html

Each of the 3 Official documentation pages describe an account-level grant that's possible through `123456789012:IAMPrincipals` but using this approach fails with terraform with the provided error message.

A sample `aws` CLI command that works as expected:

```bash
aws lakeformation grant-permissions \
    --principal DataLakePrincipalIdentifier='111122223333:IAMPrincipals' \
    --permissions DESCRIBE \
    --resource '{"Database": {"Name": "my_test_db"} }'
```

### Would you like to implement a fix?

No

**Comment by dacreify** [comment]
For principal use `IAM_ALLOWED_PRINCIPALS` and you should be good.

**Comment by maiconbaum** [comment]
Any news? 😕

**Comment by nickdelnano** [comment]
@maiconbaum @dpandolfo @mebuffet @dacreify there is a fix here, please add your 👍  to it 😄  https://github.com/hashicorp/terraform-provider-aws/pull/38600
