### ISSUE TITLE
Grafana: Support new network access control configuration 

### ISSUE THREAD

**Issue by gingersnapz** [hashicorp/terraform-provider-aws#29760]
### Description

As of 2/16/2023, AWS released a new configuration for an AMG workspace that allows for network access control. This allows access to the workspace to be restricted to a set of managed prefix lists and/or a vpc endpoint.

To use this feature, the existing grafana workspace resource will need to be updated to support it.

### Affected Resource(s) and/or Data Source(s)

aws_grafana_workspace

### Potential Terraform Configuration

```terraform
resource "aws_grafana_workspace" "example" {
  account_access_type      = "CURRENT_ACCOUNT"
  authentication_providers = ["SAML"]
  permission_type          = "SERVICE_MANAGED"
  role_arn                 = aws_iam_role.assume.arn

  network_access_control   {
     vpce_ids = ["vpce-xxxxxxx"]
     prefix_lists_ids  = ["pl-xxxxxxx", "pl-xxxxxxx"]
  }
}
```

### References

https://docs.aws.amazon.com/cli/latest/reference/grafana/create-workspace.html

### Would you like to implement a fix?

None

**Comment by DrFaust92** [comment]
looking into this
