### ISSUE TITLE
[Enhancement]: Add the destination region argument reference for aws_ami_copy

### ISSUE THREAD

**Issue by vineet-nair-itp** [hashicorp/terraform-provider-aws#29815]
### Description

I want to copy an ec2 instance ami to multiple regions, but unable to find a destination region argument in the below specified resource aws_ami_copy, where as it exists in the aws console.

<img width="572" alt="image" src="https://user-images.githubusercontent.com/123387163/223232551-b3ab735d-ff47-44ef-89c1-ac4780ed43c1.png">
 

### Affected Resource(s) and/or Data Source(s)

[aws_ami_copy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ami_copy)

### Potential Terraform Configuration

```terraform
resource "aws_ami_copy" "exam" {
  name              = "amicopy-example"
  description       = "A copy of ami-xxxxxxxx"
  source_ami_id     = aws_ami_from_instance.example.id
  source_ami_region = "ap-south-1"

  # tags = {
  #   Name = "test"
  # }
}
```

### Would you like to implement a fix?

None

**Comment by mattburgess** [comment]
Hi @vineet-nair-itp. The destination region will be implied by the region that your `provider` block is configured for. If you want to copy an AMI to multiple regions you could use a similar approach to [this](https://github.com/tiddnet/terraform-copy-ami) where a common module is instantiated multiple times with a different region specified each time.
