### ISSUE TITLE
[Bug]: Removing the Keyspace from the second attempt

### ISSUE THREAD

**Issue by AlexeyMoiseev** [hashicorp/terraform-provider-aws#29826]
### Terraform Core Version

1.3.9

### AWS Provider Version

4.57.0

### Affected Resource(s)

`aws_keyspaces_keyspace`

### Expected Behavior

Removing Keyspace.

### Actual Behavior

I'm getting such an error:
`Error: waiting for Keyspaces Keyspace (keyspace_db) delete: found resource`
It was successfully removed on the second attempt.

### Terraform Configuration Files

```
resource "aws_keyspaces_keyspace" "keyspace_db" {
  name = "keyspace_db"
}
```

### Steps to Reproduce

No clear way to reproduce.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @AlexeyMoiseev 👋 Thank you for taking the time to raise this! To clarify, are you saying that you received the error on the first Terraform run that was attempting to destroy the resource, but re-running Terraform resulted in successful destruction of it?

**Comment by AlexeyMoiseev** [comment]
Hi @justinretzolk! Yes, correct.

**Comment by ewbankkit** [comment]
@AlexeyMoiseev Thanks for raising this issue 👏.
The `aws_keyspaces_keyspace` resource waits for up to 1 minute for the keyspace to disappear (returning a `ResourceNotFoundExpection` from [`GetKeyspace`](https://docs.aws.amazon.com/keyspaces/latest/APIReference/API_GetKeyspace.html)) after the [`DeleteKeyspace` API](https://docs.aws.amazon.com/keyspaces/latest/APIReference/API_DeleteKeyspace.html) is called.
For certain configurations this may not be sufficient and can be increased via a [`timeouts` block](https://developer.hashicorp.com/terraform/language/resources/syntax#operation-timeouts).
