### ISSUE TITLE
[Announcement] Upcoming Changes in Version 5.0 of the AWS Provider

### ISSUE THREAD

**Issue by marcosentino** [hashicorp/terraform-provider-aws#29842]
Since the last major provider release in February of 2022, we have been listening closely to the community's feedback. The upcoming major release primarily focuses on removing caveats on the Default Tags functionality.

## Summary
A major release is our opportunity to make breaking changes in a scheduled and publicized manner in an attempt to avoid unnecessary churn for our users. We attempt to limit major releases to every 12-18 months. Version v4.0.0 of the AWS provider was released in February of 2022.
Along with more significant changes in behavior detailed below, this release will also remove attributes that have been marked as deprecated. Typically these have been marked as such due to changes in the upstream API, or in some cases the use of the attribute causes confusion. Major release v5.0.0 will not make any changes in support for older versions of Terraform.

### Default Tags Enhancement
The default tags functionality was released in May 2021 due to overwhelming community support. Over its existence as a feature in the provider, we have discovered other limitations which hamper its adoption. New features are now available in [terraform-plugin-sdk](https://developer.hashicorp.com/terraform/plugin/sdkv2/guides/v1-upgrade-guide), and the [terraform-plugin-framework](https://developer.hashicorp.com/terraform/plugin/framework) which means we are now able to remove these caveats and resolve any major issues with its use. Resolving these issues will solve the following:

- **Inconsistent final plans** that cause failures when tags are computed.
- **Identical tags** in both default tags and resource tags.
- **Eliminate perpetual diffs** within tag configurations.

While most of this work is resolving issues with the design of the feature, it does represent a significant change in behavior that we can’t be sure will not be disruptive for users with existing default tag configurations. As a result, it is considered a breaking change. Details of the Default Tags changes can be found in issue #[29747](https://github.com/hashicorp/terraform-provider-aws/issues/29747)

### Remove EC2 Classic Functionality
In 2021 AWS [announced](https://aws.amazon.com/blogs/aws/ec2-classic-is-retiring-heres-how-to-prepare/) the retirement of EC2 Classic Networking functionality. This was scheduled to occur on August 15th, 2022. Support for the functionality was extended until late September when any AWS customers who had qualified for extension finished their migration. At that time those features were marked as deprecated and it is now time to remove them as the functionality is no longer available through AWS. While this is a standard deprecation, this is a major feature removal.

### Updating RDS Identifiers In–Place
Allow DB names to be updated in place. This is now supported by AWS, so we should allow its use. Practitioners will now be able to change names without a recreation. Details for this issue can be tracked in issue [#507](https://github.com/hashicorp/terraform-provider-aws/issues/507).

### Remove Default Value from Engine Parameters
Removes a default value that does not have a parallel with AWS and causes unexpected behavior for end users. Practitioners will now have to specify a value. Details for this issue can be tracked in issue #[27960](https://github.com/hashicorp/terraform-provider-aws/issues/27960).

### Force replacement on snapshot_identifier change for DB cluster resources
Corrects the behavior to create a new database if the snapshot id is changed in line with practitioner expectations. Details for this issue can be tracked in issue #[29409](https://github.com/hashicorp/terraform-provider-aws/pull/29409)

## Follow our Progress
The full contents of the major release and progress towards it can be viewed in the v5.0.0 [milestone](https://github.com/hashicorp/terraform-provider-aws/milestone/226)

## Upgrading
As a major version contains breaking changes, it is considered best practice to pin a provider version to avoid bringing in potentially breaking changes automatically. To remain on v4.* versions of the provider until such time that you are able to accommodate those changes, either pin to any v4.* version:

```terraform
terraform {
  required_providers {
    aws = {
      version = "~> 4.0"
    }
  }
}
```
 
Or a specific version:
 
```terraform
terraform {
  required_providers {
    aws = {
      version = "4.56.0"
    }
  }
}
```

Full documentation on [how to manage versions of a provider can be found on the Terraform Website.](https://www.terraform.io/docs/language/providers/requirements.html#version-constraints)

Your usage patterns will dictate how much effort upgrading to v5.0 will take. We document each breaking change in our upgrade guide which will describe what changes are necessary to existing resources to preserve behavior. The upgrade guide will be available on the day of the release on the Terraform Website.

**Comment by tmccombs** [comment]
Would this be a good time to switch from the old elasticsearch apis to the newer opensearch apis?

**Comment by nikolay** [comment]
Please, don't use "practitioner" as it doesn't fit well into the context.

**Comment by marcosentino** [comment]
[v5.0.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.0.0) of the provider is now released.
