### ISSUE TITLE
Line 91 should be - policy = data.aws_iam_policy_document.example.json [Docs]: 

### ISSUE THREAD

**Issue by AfsarCBE** [hashicorp/terraform-provider-aws#29855]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codebuild_project

### Description

The below block (lines 89 to 91) has an error,
resource "aws_iam_role_policy" "example" {
    role   = aws_iam_role.example.name
    policy = data.**aws_iam_role_policy**.example.json
}

Corrected block,
resource "aws_iam_role_policy" "example" {
    role   = aws_iam_role.example.name
    policy = data.**aws_iam_policy_document**.example.json
}

Instead of aws_iam_role_policy_document, the correct one is aws_iam_policy_document

### Would you like to implement a fix?

None

**Comment by itsRaj27** [comment]
Can I work on this ?

**Comment by AfsarCBE** [comment]
Do you have the access to edit/correct the file?

**Comment by justinretzolk** [comment]
Hey @AfsarCBE and @itsRaj27 👋 I had a PR open to correct a couple of similar issues (we recently had a fairly large rewrite around these), so I've added a correction for this to that PR 🙂.
