### ISSUE TITLE
[Bug]: InvalidParameterValue: No Platform named ... found.

### ISSUE THREAD

**Issue by ineu** [hashicorp/terraform-provider-aws#29856]
### Terraform Core Version

1.3.9

### AWS Provider Version

4.57.1

### Affected Resource(s)

aws_elastic_beanstalk_configuration_template

### Expected Behavior

When a platform is removed from AWS, an error should not be raised

### Actual Behavior

A 400 error is raised:
```
Error: reading Elastic Beanstalk Configuration Template ([skipped]): InvalidParameterValue: No Platform named 'arn:aws:elasticbeanstalk:eu-west-2::platform/Ruby 2.7 running on 64bit Amazon Linux 2/3.6.3' found.
       status code: 400, request id: fccb2c54-8b2f-4d4f-b8e1-9c1bf2996f57
```

There's already an issue with the same problem, which was fixed 6 years ago: https://github.com/hashicorp/terraform-provider-aws/pull/1222

But something has probably changed since then, so it happens again.

### Terraform Configuration Files

```
data "aws_elastic_beanstalk_solution_stack" "ruby_nginx_app" {
  most_recent = true

  name_regex = "^64bit Amazon Linux (.*) Ruby 2.7$"
}

resource "aws_elastic_beanstalk_configuration_template" "eb_main_app_template" {
  for_each            = local.sites
  name                = "tf-main-app-template${local.post}-${each.value}"
  application         = aws_elastic_beanstalk_application.main_web_app[each.key].name
  solution_stack_name = data.aws_elastic_beanstalk_solution_stack.ruby_nginx_app.name
  # here go "setting" blocks
}
```

### Steps to Reproduce

1. Create a template using a stack
2. Wait for AWS to remove the stack
3. Run `plan` or `refresh`
 

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
Relates 37fa01265e83fafc704a28cb294bdb2ad3658577.
