### ISSUE TITLE
[Docs]: aws_iam_policy_attachment

### ISSUE THREAD

**Issue by rolandfuszenecker-seon** [hashicorp/terraform-provider-aws#29858]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy_attachment

### Description

In the example usage under the `aws_iam_policy` the policy refers to an invalid resource.
  `policy      = data.aws_iam_policy.policy.json`
It should be pointed to `data.aws_iam_policy_document.policy.json`.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @rolandfuszenecker-seon 👋 Thank you for taking the time to raise this! I've opened a PR to correct this in the docs 🙂
