### ISSUE TITLE
[Docs]: Typo in code example in appsync_datasource docs

### ISSUE THREAD

**Issue by IanSweeneyKodiak** [hashicorp/terraform-provider-aws#29872]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appsync_datasource

### Description

in `resource "aws_iam_role_policy" "example"`
`policy` should be `data.aws_iam_policy_document.example.json`

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @IanSweeneyKodiak 👋 Thank you for taking the time to raise this! I've opened a PR to correct this in the docs 🙂
