### ISSUE TITLE
[Docs]: [aws_appflow_flow - Example Usage - Incorrect 

### ISSUE THREAD

**Issue by anithapriyanatarajan** [hashicorp/terraform-provider-aws#29878]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appflow_flow

### Description

Example code includes following 3 mistakes:

- 1 
 Incorrect:
resource "aws_s3_bucket" "example_source" {
  bucket = "example_source"
}
Should be corrected to:
resource "aws_s3_bucket" "example_source" {
  **bucket = "example-source"**  #https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html
}
- 2
 Incorrect:
resource "aws_s3_bucket" "example_destination" {
  bucket = "example_destination"
}
Should be corrected to:
resource "aws_s3_bucket" "example_destination" {
  **bucket = "example-destination"** 
}
- 3
Incorrect:
data "aws_iam_policy_document" "example_destination" {
  sid    = "AllowAppFlowDestinationActions"
  effect = "Allow"

  principals {
    type        = "Service"
    identifiers = ["appflow.amazonaws.com"]
  }

  actions = [
    "s3:PutObject",
    "s3:AbortMultipartUpload",
    "s3:ListMultipartUploadParts",
    "s3:ListBucketMultipartUploads",
    "s3:GetBucketAcl",
    "s3:PutObjectAcl",
  ]

  resources = [
    "arn:aws:s3:::example_destination",
    "arn:aws:s3:::example_destination/*",
  ]
}
Should be corrected to:
data "aws_iam_policy_document" "example_destination" {
  **statement {**
  sid    = "AllowAppFlowDestinationActions"
  effect = "Allow"

  principals {
    type        = "Service"
    identifiers = ["appflow.amazonaws.com"]
  }

  actions = [
    "s3:PutObject",
    "s3:AbortMultipartUpload",
    "s3:ListMultipartUploadParts",
    "s3:ListBucketMultipartUploads",
    "s3:GetBucketAcl",
    "s3:PutObjectAcl",
  ]

  resources = [
    "arn:aws:s3:::example_destination",
    "arn:aws:s3:::example_destination/*",
  ]
**}**
}

Even after fixing the above issues, given example will not provision a functioning appflow flow.  If the Task type is "Map" the field mapping is not at all happening still apply is success and state file has the mapping whereas in AWS the mapping is empty and flow execution fails. For Map_all, this works. Apart from this documentation issue, i would raise code bug and tag the reference here.

### References

Bucket Naming rules:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @anithapriyanatarajan 👋 Thank you for taking the time to raise this! I've opened a documentation pull request to correct the issues with the examples.
