### ISSUE TITLE
[Docs]: Add iops support for gp3 volumes created via launch template

### ISSUE THREAD

**Issue by Indresh-Prakash** [hashicorp/terraform-provider-aws#29885]
### Description

Add support for iops for gp3 volumes in docs

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#iops

### Affected Resource(s) and/or Data Source(s)

launch_template

### References

(https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html)

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @Indresh-Prakash 👋 Thanks for catching this! I'll keep an eye out for a follow up documentation PR to close this out. If you decide you're unable to raise the PR, let me know and I'll be happy to do so.

**Comment by Indresh-Prakash** [comment]
> Hey @Indresh-Prakash 👋 Thanks for catching this! I'll keep an eye out for a follow up documentation PR to close this out. If you decide you're unable to raise the PR, let me know and I'll be happy to do so.

Hi @justinretzolk . Thanks for confirmation on this. I'll be happy to raise a PR for the same
