### ISSUE TITLE
[Enhancement]: Support adding tags to the EKS created security group

### ISSUE THREAD

**Issue by lorelei-rupp-imprivata** [hashicorp/terraform-provider-aws#29919]
### Description

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster when creating an eks cluster it creates an EKS created security group, that ends up with a description like "EKS created security group applied to ENI that is attached to EKS Control Plane master nodes, as well as any managed workloads."

We would like to add some custom tags to this resource
Can you hook up the tags that already flow to this aws_eks_cluster resource to also add them to the security group it creates

### Affected Resource(s) and/or Data Source(s)

aws_eks_cluster

### Would you like to implement a fix?

No

**Comment by bryantbiggs** [comment]
FYI - you can do this today using the `aws_ec2_tag` resource. Here is an example https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0a17f655fb7da00640627ed9255f1d96e42fcfd7/main.tf#L93-L99

**Comment by lorelei-rupp-imprivata** [comment]
> FYI - you can do this today using the `aws_ec2_tag` resource. Here is an example https://github.com/terraform-aws-modules/terraform-aws-eks/blob/0a17f655fb7da00640627ed9255f1d96e42fcfd7/main.tf#L93-L99

I am talking about the cluster security group, that AWS automatically creates when you set up a eks cluster here

**Comment by bryantbiggs** [comment]
correct - that is what I am referring to as well

**Comment by a0s** [comment]
@bryantbiggs You saved my code from being ugly! Thank you! It really works.
```typescript
this.eksModule = new Eks(this, "eks", <EksConfig>{
  createClusterPrimarySecurityGroupTags: true,
  clusterSecurityGroupTags: {
    ClusterSecurityGroup: "ClusterSecurityGroup"
  },
})
<img width="403" alt="Screenshot 2023-07-15 at 18 17 01" src="https://github.com/hashicorp/terraform-provider-aws/assets/418868/41aca2ef-7663-428d-a661-d8f0690327e6">

**Comment by omidraha** [comment]
Where is the source code of this message:
```EKS created security group applied to ENI that is attached to EKS Control Plane master nodes, as well as any managed workloads.```

**Comment by sosafe-bastian-bretagne** [comment]
We have the exact same issue. We believe this is aws internal stuff injecting that security-group and we dont have any control over it. It will not be part of the terraform code.

We tried to change the tag Name of that SG in the UI to have it defined and predictible for Karpenter. But aws will override it after some time.

**Comment by jastabilesandbox** [comment]
I think this is what you're looking for:

https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest?tab=outputs
There's a cluster_primary_security_group_id output in eks module
```
resource "aws_ec2_tag" "cluster_primary_security_group" {
  resource_id = module.eks.cluster_primary_security_group_id
  key         = "karpenter.sh/discovery" 
  value       = "${local.cluster_name}"
}
```

**Comment by j-coll** [comment]
@omidraha , that description won't be found on terraform, as this security group is created by the EKS service. 
See https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html

> When you create a cluster, Amazon EKS creates a security group that's named eks-cluster-sg-my-cluster-uniqueID. 

The aws_eks_cluster resource will also have this security group as output:
```
aws_eks_cluster.<name>.vpc_config[0].cluster_security_group_id
```

Then, the EKS module reads that resource output to add `var.tags` and `var.cluster_tags`, exactly as @jastabile suggests

This requires `var.create_cluster_primary_security_group_tags = true` , which is the default

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v20.22.0/main.tf#L122-L133

```terraform
resource "aws_ec2_tag" "cluster_primary_security_group" {
  # This should not affect the name of the cluster primary security group
  # Ref: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2006
  # Ref: https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2008
  for_each = { for k, v in merge(var.tags, var.cluster_tags) :
    k => v if local.create && k != "Name" && var.create_cluster_primary_security_group_tags && v != null
  }

  resource_id = aws_eks_cluster.this[0].vpc_config[0].cluster_security_group_id
  key         = each.key
  value       = each.value
}
```

**Comment by bryantbiggs** [comment]
we should be able to close this issue since this is not a Terraform issue (Terraform has no knowledge of this EKS created security group). Existing solutions have been provided above, otherwise please feel free to track the upstream feature request for this https://github.com/aws/containers-roadmap/issues/977
