### ISSUE TITLE
[Bug]: source_code_hash not getting persisted to tf statefile - causes lambda deployment even if there is no change in etag

### ISSUE THREAD

**Issue by iammukeshm** [hashicorp/terraform-provider-aws#29921]
### Terraform Core Version

1.3.9

### AWS Provider Version

4.58.0

### Affected Resource(s)

aws_lambda_function

### Expected Behavior

Based on source_code_hash, lambda should not be re-deployed / changed if there is no difference in the etag or source_code_hash.

### Actual Behavior

The source_code_hash isnt getting stored to the statefile for some reason. Because of this everytime I run a terraform plan or apply, the lambda gets re-deployed even if there is no new zip upload my s3 bucket.

Ran terraform apply 1st time.
```
Terraform will perform the following actions:

  # module.catalog_lambda.aws_lambda_function.lambda will be updated in-place
  ~ resource "aws_lambda_function" "lambda" {
        id                             = "catalog-lambda"
      ~ last_modified                  = "2023-03-11T04:53:26.000+0000" -> (known after apply)
      ~ source_code_hash               = "Wy8Y63xIwbF/VPCbNo3m374Sec6xepIwxqr1wdpAZ+Y=" -> "66121cb6a3e928951f671916547d622f"   
        tags                           = {}
        # (21 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }
```

Ran terraform apply second time

```
Terraform will perform the following actions:

  # module.catalog_lambda.aws_lambda_function.lambda will be updated in-place
  ~ resource "aws_lambda_function" "lambda" {
        id                             = "catalog-lambda"
      ~ last_modified                  = "2023-03-11T04:53:46.000+0000" -> (known after apply)
      ~ source_code_hash               = "Wy8Y63xIwbF/VPCbNo3m374Sec6xepIwxqr1wdpAZ+Y=" -> "66121cb6a3e928951f671916547d622f"   
        tags                           = {}
        # (21 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }
```

You can see that the source_code_hash is not getting persisted to the tf statefile.

### Terraform Configuration Files

N/A

### Steps to Reproduce

```terraform
resource "aws_lambda_function" "lambda" {
  s3_bucket        = data.aws_s3_object.package.bucket
  s3_key           = data.aws_s3_object.package.key
  source_code_hash = data.aws_s3_object.package.etag
  function_name    = var.function_name
  role             = aws_iam_role.lambda_role.arn
  handler          = var.function_handler
  runtime          = var.runtime
  timeout          = var.timeout_in_seconds
  depends_on = [
    aws_iam_role_policy_attachment.lambda_policy_attachment,
    aws_iam_role.lambda_role,
    data.aws_s3_object.package
  ]

  environment {
    variables = {
      ASPNETCORE_ENVIRONMENT = "Development"
    }
  }
}

data "aws_s3_object" "package" {
  bucket = var.s3_bucket_name
  key    = var.s3_key
}
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Related: #7385
Related: #17884
Related: #25647

Potentially related: #30029

**Comment by SalmaanPV** [comment]
I think the issue still persists, i have used the latest provider version 5.32.0. Still it's the same issue.Terraform re-plan or re-appy is causing the hash values change.
Expected output: No infra change
Actual output: hash value update 
 Why it's trying to update the source code hash?
<img width="1185" alt="Screenshot 2024-01-18 at 5 51 35 PM" src="https://github.com/hashicorp/terraform-provider-aws/assets/144703172/3049e93c-b22e-4cba-af67-782c7d178929">

Below is my source code:
# Check if the object (zip file) exists in the S3 bucket
data "aws_s3_object" "lambda_zip" {
  bucket = var.bucket_name
  key    = "${var.team_name}/${var.project_name}/${var.zip_file_name}.zip"
}

# Create or update Lambda function based on the existence of the Lambda package in S3
resource "aws_lambda_function" "lambda_function" {
  function_name = var.function_name
  handler       = var.handler
  runtime       = var.runtime
  s3_bucket     = var.bucket_name
  s3_key        = "${var.team_name}/${var.project_name}/${var.zip_file_name}.zip"
  role          = aws_iam_role.custom_lambda_execution_role.arn
  timeout       = 30
  tags          = var.tags

  # Configure Lambda to use VPC
  vpc_config {
    subnet_ids         = var.vpc_subnet_ids
    security_group_ids = var.vpc_security_group_ids
  }

  environment {
    variables = var.environment_variables
  }

  # Trigger an update only if the S3 object (zip file) content  changes or Lambda doesn't exist
  source_code_hash = data.aws_s3_object.lambda_zip != null ? data.aws_s3_object.lambda_zip.etag : null
}

Can someone help me out?
