### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by cbaron** [hashicorp/terraform-provider-aws#29969]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_target

### Description

[Cross-Account Event Bus target](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_target#cross-account-event-bus-target)

The following policy document is missing the `statement` wrapper

```
data "aws_iam_policy_document" "assume_role" {
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @cbaron 👋 Thank you for taking the time to raise this! I've opened a pull request to have this example fixed.
