### ISSUE TITLE
[Docs]: openid connect thumbprint is required but shown as an empty list 

### ISSUE THREAD

**Issue by kderck** [hashicorp/terraform-provider-aws#29963]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_openid_connect_provider

### Description

The `thumbprint_list` is shown as `required` but in the example usage it's shown to be empty list. If you run `terraform apply` you'll get `creating IAM OIDC Provider: InvalidInput: Thumbprint list must contain at least one entry.`. 

You should update the example to show an example of a thumbprint.

### Would you like to implement a fix?

No

**Comment by james-callahan** [comment]
This appears to have changed on the AWS side recently. (it used to allow an empty thumbprint list; useful for when you e.g. use an S3 bucket to host the data).
Does anyone know if AWS announced/documented this change in behaviour?
