### ISSUE TITLE
[Enhancement]: `aws_eks_node_group` needs ValidateFunc for `node_group_name` and `node_group_name_prefix` 

### ISSUE THREAD

**Issue by DorukAkinci** [hashicorp/terraform-provider-aws#29974]
### Description

The `aws_eks_node_group` resource doesn't have any ValidateFunc for `node_group_name` and `node_group_name_prefix` variables. We see an error message directly from the AWS client that only tells Node group name cannot be longer than 63 chars. This same error message also throws for `node_group_name_prefix` variable, and that makes no sense in the same context. Users should manually calculate how many chars `node_group_name_prefix` will add after the apply execution. The ValidateFunc feature can fix that, and we can calculate the length in the terraform provider.

### Affected Resource(s) and/or Data Source(s)

* aws_eks_node_group

### Potential Terraform Configuration

```
resource "aws_eks_node_group" "this" {
  cluster_name = aws_eks_cluster.eks.name
  node_group_name_prefix = "this-is-my-really-long-node-group-name-prefix-that-should-fail"
...
...
...
  }
```

### References

[Official AWS Docs: The node group name can't be longer than 63 characters. It must start with letter or digit, but can also include hyphens and underscores for the remaining characters.](https://docs.aws.amazon.com/eks/latest/userguide/create-managed-node-group.html) 

![image](https://user-images.githubusercontent.com/8358478/225101112-136eb722-4107-4d28-8c61-8ea0e7c2738d.png)

![image](https://user-images.githubusercontent.com/8358478/225346040-cda4aa00-adf4-4f92-a7ea-03f3471b72cc.png)

### Would you like to implement a fix?

Yes

**Comment by DorukAkinci** [comment]
I will open the PR once I run the tests and get the output.

**Comment by DorukAkinci** [comment]
The PR is ready #29975

**Comment by ewbankkit** [comment]
<img width="806" alt="Screen Shot 2023-03-15 at 8 32 06 AM" src="https://user-images.githubusercontent.com/2404182/225309738-6332e0c8-e41c-46ec-8f92-d79fdecf46fa.png">

**Comment by DorukAkinci** [comment]
Thank you @ewbankkit for this screenshot. I'm also adding the references section to the first message.
