### ISSUE TITLE
[Enhancement]: DynamoDB "Delete Protection Flag"

### ISSUE THREAD

**Issue by allanchua101** [hashicorp/terraform-provider-aws#29979]
### Description

AWS announced DynamoDB "Delete Protection" flag which prevents accidental deletion of DynamoDBs. It will be cool to have it supported in the latest version of DynamoDB.

### Affected Resource(s) and/or Data Source(s)

DynamoDB

### Potential Terraform Configuration

```tf
resource "aws_dynamodb_table" "basic-dynamodb-table" {
  name                                      = "GameScores"
  billing_mode                         = "PROVISIONED"

  delete_protection_enabled = true
}
```

### References

[Blog about it](https://dev.to/aws-builders/preventing-accidental-deletion-of-dynamodb-using-table-protection-strategy-feature-march-2023-56ck)
[AWS Announcement](https://aws.amazon.com/blogs/database/how-to-use-deletion-protection-to-enhance-your-amazon-dynamodb-table-protection-strategy/)

### Would you like to implement a fix?

Yes, but I'd love to get some coaching guys.

**Comment by ewbankkit** [comment]
@allanchua101 Thanks for raising this issue.
It has already been noticed in #29876. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by allanchua101** [comment]
Thanks @Clete2 and @ewbankkit!! Excited to use it soon 🙏
