### ISSUE TITLE
[Bug]: Updating aws_wafv2_web_acl failed

### ISSUE THREAD

**Issue by calvinbui** [hashicorp/terraform-provider-aws#29977]
### Terraform Core Version

1.2.9

### AWS Provider Version

4.58.0

### Affected Resource(s)

* aws_wafv2_web_acl

### Expected Behavior

Resource updated

### Actual Behavior

Failed apply

### Terraform Configuration Files

[web-acl-bot-control.tf.gpg.zip](https://github.com/hashicorp/terraform-provider-aws/files/10963127/web-acl-bot-control.tf.gpg.zip)

### Steps to Reproduce

terraform apply

### Debug Output

Really long error, see log: 

```
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for aws_wafv2_web_acl.backend_apis to include new
│ values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .rule: planned set element
...
...
...
│ "sampled_requests_enabled":cty.True})})}) does not correlate with any
│ element in actual.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
Operation failed: failed running terraform apply (exit 1)
```

[run-siijZdv6kiBL9Www-apply-log.txt](https://github.com/hashicorp/terraform-provider-aws/files/10963087/run-siijZdv6kiBL9Www-apply-log.txt)

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Related: https://github.com/hashicorp/terraform-provider-aws/issues/23390
Related: https://github.com/hashicorp/terraform-provider-aws/issues/23423
Related: https://github.com/hashicorp/terraform-provider-aws/issues/23992
Related: https://github.com/hashicorp/terraform-provider-aws/issues/24386
Related: https://github.com/hashicorp/terraform-provider-aws/issues/27175
Related: https://github.com/hashicorp/terraform-provider-aws/issues/27273
Related: https://github.com/hashicorp/terraform-provider-aws/issues/27479
Related: https://github.com/hashicorp/terraform-provider-aws/issues/28672
Related: https://github.com/hashicorp/terraform-provider-aws/issues/28191
Related: https://github.com/hashicorp/terraform-provider-aws/issues/29012
Related: https://github.com/hashicorp/terraform-provider-aws/issues/29304
