### ISSUE TITLE
[Docs]: Resource: aws_iam_role_policy_attachment

### ISSUE THREAD

**Issue by grandmaestr** [hashicorp/terraform-provider-aws#29987]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role_policy_attachment

### Description

The data.aws_iam_policy_document.assume_role seems to be missing a statement block. The current example has 

```
data "aws_iam_policy_document" "assume_role" {
  effect = "Allow"

  principals {
    type        = "Service"
    identifiers = ["ec2.amazonaws.com"]
  }

  actions = ["sts:AssumeRole"]
}
```
which fails validation with an"unsupported argument" error. The correct code should be:
```
data "aws_iam_policy_document" "assume_role" {
  statement {
    effect = "Allow"

  principals {
    type        = "Service"
    identifiers = ["ec2.amazonaws.com"]
  }

  actions = ["sts:AssumeRole"]
}
}
```

Tested on Terraform v1.34.0

### Would you like to implement a fix?

None

**Comment by conorshortt** [comment]
I would like to work on this and submit a PR later

**Comment by justinretzolk** [comment]
Thank you for taking the time to submit this @grandmaestr, and thank you to @conorshortt for offering to submit a PR to fix it. I'll keep an eye out for that PR.

**Comment by btanand** [comment]
@justinretzolk  In case this is not resolved , I can pick it up.

**Comment by btanand** [comment]
@justinretzolk Pr has been created for this. Request you to kindly have a look at it.

**Comment by btanand** [comment]
@justinretzolk Just reminding you of the PR for review and approval. Thanks
