### ISSUE TITLE
[Docs]: Wrong example in aws kendra s3 data source

### ISSUE THREAD

**Issue by mohammadreza490** [hashicorp/terraform-provider-aws#29993]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_data_source#s3-connector

### Description

Under the `With Documents Metadata Configuration` section, the `s3_prefix` is used in `s3_configuration` block although this is wrong. The expected way of using `s3_prefix` is to use it within a `documents_metadata_configuration` as mentioned [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_data_source#documents_metadata_configuration)

### Would you like to implement a fix?

None

**Comment by batman9326** [comment]
Thanks for identifying the issue. I was scratching my brain on why my TF apply is failing.

**Comment by mohammadreza490** [comment]
> Thanks for identifying the issue. I was scratching my brain on why my TF apply is failing.

No worries @batman9326. Always good to help the heros ;)
