### ISSUE TITLE
[Docs]: Spelling error

### ISSUE THREAD

**Issue by mohammadreza490** [hashicorp/terraform-provider-aws#29992]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_data_source#documents_metadata_configuration

### Description

There is a spelling error in the doc. The word `Document` was spelled `Ddcument`.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @mohammadreza490 👋 Thank you very much for taking the time to raise this! I've opened a pull request to get this fixed.
