### ISSUE TITLE
[Enhancement]: Support deletion protection on DynamoDB tables

### ISSUE THREAD

**Issue by jfernandoz** [hashicorp/terraform-provider-aws#30004]
### Description

AWS released DynamoDB deletion protection recently ([announcement](https://aws.amazon.com/about-aws/whats-new/2023/03/amazon-dynamodb-table-deletion-protection/)). It would be great to add support for it in terraform (similar to how [deletion protection works for RDS instances](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#deletion_protection)).

### Affected Resource(s) and/or Data Source(s)

aws_dynamodb_table

### References

https://aws.amazon.com/about-aws/whats-new/2023/03/amazon-dynamodb-table-deletion-protection/

### Would you like to implement a fix?

None

**Comment by bschaatsbergen** [comment]
Thanks for raising this issue @jfernandoz 🙇🏼‍♂️. I'll pick this up!

**Comment by bschaatsbergen** [comment]
Actually, this was already picked up in: https://github.com/hashicorp/terraform-provider-aws/pull/29924

**Comment by jfernandoz** [comment]
Awesome, I missed that one. Thanks @bschaatsbergen!
