### ISSUE TITLE
[Docs]:  Wrong value passed to queue_url argument for resource aws_sqs_queue_policy

### ISSUE THREAD

**Issue by EdWrld** [hashicorp/terraform-provider-aws#30021]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue_policy

### Description

The example shows  the resource "aws_sqs_queue_policy" "test" the two arguments are   
  queue_url = aws_sqs_queue.q.id
  policy    = data.aws_iam_policy_document.test.json

the value provided to the the queue_url is not the url but the id of the sqs queue

### Would you like to implement a fix?

Yes

**Comment by teddylear** [comment]
@EdWrld I can fix this if that's alright.

**Comment by bennylu2** [comment]
From the aws_sqs_queue [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue#id) id is the same as url

> [id](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue#id) - The URL for the created Amazon SQS queue.

**Comment by EdWrld** [comment]
Ah I didn't notice that thanks for clearing that up
