### ISSUE TITLE
[Bug]: updating EC2 EIP and terminated instance

### ISSUE THREAD

**Issue by mauriciowillig** [hashicorp/terraform-provider-aws#30028]
### Terraform Core Version

1.4.0

### AWS Provider Version

4.58.0

### Affected Resource(s)

aws_instance
aws_eip

### Expected Behavior

I'm triying to change the AZ on multiple EC2 instance. The configuration remains the same (name of the vm, network interfaces name, etc) the only change is the AZ (and the subnet associated with it). The problem begins when terraform tries to assign the Elastic IP on the new instance (after the old one is deleted), as tries to assign the Elastic IP to the 'north' network interface of the terminated instance instead the network interface of the new instance. It says that the cannot update de EC2 EIP as the terminated instance is no in a valid state for this operation. 

I also added a depends_on in the resource aws_eip  pointing to the module that creates de instances, but it's not working either. 

### Actual Behavior

Failing in allocating the EIP on a networking interface. 

### Relevant Error/Panic Output Snippet

```shell
Error: updating EC2 EIP (eipalloc-XXXXXX): associating: InvalidInstanceID: The terminated instance 'i-><old instance id>' is not in a valid state for this operation.
 	status code: 400, request id: XXXXXXcb3
 
   with module.appgate_sdp.aws_eip.this["sdp02"],
   on .terraform/modules/appgate_sdp/ec2-sdp.tf line 33, in resource "aws_eip" "this":
   33: resource "aws_eip" "this" {
 


 Error: updating EC2 EIP (eipalloc-07ea55acb213c7da1): associating: InvalidInstanceID: The terminated instance '<old instance id>' is not in a valid state for this operation.
 	status code: 400, request id: XXXXXX7bf
 
   with module.appgate_sdp.aws_eip.this["sdp03"],
   on .terraform/modules/appgate_sdp/ec2-sdp.tf line 33, in resource "aws_eip" "this":
   33: resource "aws_eip" "this" {
```

### Terraform Configuration Files

```terraform
 module "sdp_ec2" {
   source  = "terraform-aws-modules/ec2-instance/aws"
   version = "~> 3.0"
 
   for_each = var.sdp_instances
 
   name = "${local.resource_prefix}.${each.key}.vm"
 
   ami           = var.appgate_ami_id #Linux for now
   instance_type = local.instance_type[var.environment]
   key_name      = aws_key_pair.this.key_name != null ? aws_key_pair.this.key_name : null
   monitoring    = true
 
 
   network_interface = [
     {
       device_index         = 0
       network_interface_id = aws_network_interface.south[each.key].id
     },
     {
       device_index         = 1
       network_interface_id = aws_network_interface.north[each.key].id
     }
   ]
   disable_api_termination = true
 
   root_block_device = local.root_block_config[var.environment]
 
 }
 ###### EIP#######
 
 resource "aws_eip" "this" {
   for_each          = var.sdp_instances
   vpc               = true
   network_interface = aws_network_interface.north[each.key].id
 
   depends_on = [module.sdp_ec2]
 }
 
 ###### NICS #######
 
 resource "aws_network_interface" "north" {
 
   for_each          = var.sdp_instances
   subnet_id         = module.sdp_vpc.public_subnets[each.value.az - 1]
   security_groups   = [aws_security_group.north.id]
   source_dest_check = false
   private_ips       = [cidrhost(module.sdp_vpc.public_subnets_cidr_blocks[each.value.az - 1], each.value.instance_number + 4)]
 
   tags = {
     "Name" = "${local.resource_prefix}.${local.app_name}.${each.key}.public.az${each.value.az}.eni"
   }
 }
 
 resource "aws_network_interface" "south" {
   for_each          = var.sdp_instances
   subnet_id         = module.sdp_vpc.intra_subnets[each.value.az - 1]
   security_groups   = [aws_security_group.south.id]
   source_dest_check = false
   private_ips       = [cidrhost(module.sdp_vpc.intra_subnets_cidr_blocks[each.value.az - 1], each.value.instance_number + 4)]
   tags = {
     "Name" = "${local.resource_prefix}.${local.app_name}.${each.key}.private.az${each.value.az}.eni"
   }
 }
```

### Steps to Reproduce

terraform apply

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @mauriciowillig 👋 Thank you for taking the time to raise this! I suspect this may be a configuration issue, rather than a bug with the provider, so you may have better luck asking on the [Discuss forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33). That said, to be certain, can you supply debug logs (redacted as needed) so that we have the information necessary to investigate this?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
