### ISSUE TITLE
[Enhancement]: Add support for Security Hub consolidated control findings

### ISSUE THREAD

**Issue by jeeslo** [hashicorp/terraform-provider-aws#30022]
### Description

Security Hub now supports enabling consolidated control findings, so that a single finding gets generated even though there are multiple security standard controls enabled in the same account that check the same resource configuration.

### Affected Resource(s) and/or Data Source(s)

"aws_securityhub_account"

### Potential Terraform Configuration

```terraform
resource "aws_securityhub_organization_configuration" "example" {
  auto_enable = true
  control_finding_generator = "SECURITY_CONTROL"
}
```

### References

https://aws.amazon.com/about-aws/whats-new/2023/02/aws-security-hub-consolidated-control-findings-view/
https://aws.amazon.com/blogs/security/prepare-for-consolidated-controls-view-and-consolidated-control-findings-in-aws-security-hub/

### Would you like to implement a fix?

None

**Comment by leondkr** [comment]
I need this so badly :) Thanks @jeeslo for requesting this one. It is a must for managing Landing Zone using Terraform or else I have to implement a custom resource for just using AWS CLI to enable them per account.

**Comment by lawliet89** [comment]
This has to be implemented on `aws_securityhub_account` because it's a field in [`EnableSecurityHub`](https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_EnableSecurityHub.html#API_EnableSecurityHub_RequestSyntax)
