### ISSUE TITLE
[Bug]: aws_vpc_security_group_ingress_rule with all protocols and ports fails on update

### ISSUE THREAD

**Issue by bpiper** [hashicorp/terraform-provider-aws#30035]
### Terraform Core Version

1.3.1

### AWS Provider Version

4.58.0

### Affected Resource(s)

* aws_vpc_security_group_egress_rule
* aws_vpc_security_group_ingress_rule

### Expected Behavior

When there are no actual changes to the resource definitions, Terraform shouldn't even detect any changes.

### Actual Behavior

Terraform wants to update the resource:

```
  # aws_vpc_security_group_ingress_rule.test_ingress will be updated in-place
  ~ resource "aws_vpc_security_group_ingress_rule" "test_ingress" {
      ~ from_port              = -1 -> 0
        id                     = "sgr-02992326893858d5f"
      ~ to_port                = -1 -> 65535
        # (6 unchanged attributes hidden)
    }
```

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: updating VPC Security Group Rule (sgr-02992326893858d5f)
│ 
│   with aws_vpc_security_group_ingress_rule.test_ingress,
│   on main.tf line 32, in resource "aws_vpc_security_group_ingress_rule" "test_ingress":
│   32: resource aws_vpc_security_group_ingress_rule "test_ingress" {
│ 
│ InvalidParameterValue: You may not specify all protocols and specific ports. Please specify each protocol and port range combination individually, or all protocols and no port range.
│       status code: 400, request id: 6a28c47c-2a06-4cb9-80a7-952fa4bd76ba
```

### Terraform Configuration Files

```
resource "aws_security_group" "test" {
  name = "test"
  vpc_id = <some-vpc>
}

resource aws_vpc_security_group_ingress_rule "test_ingress" {
  security_group_id = aws_security_group.test.id

  cidr_ipv4   = "0.0.0.0/0"
  from_port   = 0
  to_port     = 65535
  ip_protocol = "-1"
}
```

### Steps to Reproduce

Do an apply to create the security group and rule(s), then run another apply without making any changes.

### Important Factoids

There is evidently some code in `vpc_security_group_rule.go` that handles the all protocols + all ports case and avoids this error, so this probably just needs to be carried over into `vpc_security_group_ingress_rule.go` in some form.

### Would you like to implement a fix?

None

**Comment by GeorgeDavis-TriumphTech** [comment]
@justinretzolk  Would love to see an update on this issue. Having the same errors in a couple of projects and they need fixing. Thank you.

**Comment by ef-klukacs** [comment]
If ip_protocol is set to "-1", it translates at AWS's side to protocol=All, Port range = All thus no from_port/to_port is required. I made the change by omitting to_port and from_port arguments and it did the trick for me.
This has mentioned on https://github.com/hashicorp/terraform/issues/1729#issuecomment-98812660.

**Comment by justinretzolk** [comment]
Hi @bpiper and @GeorgeDavis-TriumphTech 👋 Can you test with the information that @ef-klukacs provided above to validate that it resolves your issues as well?

**Comment by GeorgeDavis-TriumphTech** [comment]
Thank you @ef-klukacs 

@justinretzolk Yes, that seems to have resolved the issue. I wonder if this is something that can be updated in the `aws_vpc_security_group_ingress_rule` and `aws_vpc_security_group_egress_rule` resource documentation. Please advise.

**Comment by bpiper** [comment]
@justinretzolk yes, that works for me, thanks @ef-klukacs .  Perhaps the resource could throw an informative error if `from_port` or `to_port` are specified when the value of `ip_protocol` is `-1`.

**Comment by justinretzolk** [comment]
Thank you for confirming that resolves the issue. From my perspective, I don't think this is something we'd surface as an error in the provider, given that we're not receiving an error from the API itself. On the other hand, this seems like something that absolutely could be included in the documentation, since it seems like an easy situation to fall into.

@GeorgeDavis-TriumphTech -- are you interested in submitting a documentation PR for this? If not, I'm happy to raise one myself.

**Comment by GeorgeDavis-TriumphTech** [comment]
@justinretzolk/@ef-klukacs

Submitted a PR #31617. Thank you for all your help. Have a wonderful day!
