### ISSUE TITLE
[Enhancement]: Additional permissions in KMS keys created by module EKS

### ISSUE THREAD

**Issue by zenbones** [hashicorp/terraform-provider-aws#30032]
### Description

The EKS modules creates a KMS key for the cluster by default (it does for me and I have no specific configuration for this). The key policy for the KMS key contains allow grants for the current aws user and the cluster role defined by...

```
module "eks" {
  iam_role_arn = ...
}
```

...which all makes sense. However, automation may be run by one user, possibly an automation account, and then require intervention or manipulation by other accounts. KMS is kind of special in that, t does not matter if a user in AWS has grants for everything in KMS, or is an admin, or anything else. The KMS policy being created limits access to the current AWS user running the installation and the cluster role. In our case, as the AWS user is an automation user with specific grants and no login, this becomes problematic as attempts to remove the created cluster by *any* other user will be denied based on lack of access to the create KMS key, no matter what their specific grants allow.

What would be preferable is to allow access in the KMS key policy to the cluster role and *any* users with appropriate access granted in IAM. If that's not possible, then a method for adding users to the grants in the policy for the KMS key would be better than the current situation.

I think the key policy should look like this...

```
{
    "Version": "2012-10-17",
    "Statement": [
{
  "Sid": "Enable IAM policies",
  "Effect": "Allow",
  "Principal": {
    "AWS": "arn:aws:iam::111122223333:root"
   },
  "Action": "kms:*",
  "Resource": "*"
},
        {
            "Sid": "KeyUsage",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::825399403826:role/ForioEKSClusterRole"
            },
            "Action": [
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*",
                "kms:Encrypt",
                "kms:DescribeKey",
                "kms:Decrypt"
            ],
            "Resource": "*"
        }
    ]
}
```

...which grants access to the cluster role and also allows IAM on the account to delegate additional responsibilities. According to the KMS documentation...

```
Allows IAM policies to allow access to the KMS key.
The key policy statement shown above gives the AWS account that owns the key permission to use IAM policies, as well as key policies, to allow all actions (kms:*) on the KMS key.

The principal in this key policy statement is the [account principal](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html#principal-accounts), which is represented by an ARN in this format: arn:aws:iam::account-id:root. The account principal represents the AWS account and its administrators.

When the principal in a key policy statement is the account principal, the policy statement doesn't give any IAM principal permission to use the KMS key. Instead, it allows the account to use IAM policies to delegate the permissions specified in the policy statement. This default key policy statement allows the account to use IAM policies to delegate permission for all actions (kms:*) on the KMS key.
```

### Affected Resource(s) and/or Data Source(s)

module eks, I believe.

### References

None. And, to be clear, I left the HCL above blank because I believe the default behavior should be changed and no new HCL should be required.

### Would you like to implement a fix?

None

**Comment by zenbones** [comment]
If someone can point to the module this code is actually in, I would take a crack at fixing it.

**Comment by justinretzolk** [comment]
Hey @zenbones 👋 When [calling a module](https://developer.hashicorp.com/terraform/language/modules/syntax#calling-a-child-module) in Terraform, one of the required arguments is `source`, which should give you and idea of where the module configuration lives. In order to have this addressed, you'll need to file an issue in the repository that houses the module's configuration (or submit a PR, as you'd alluded to), as those are separate from the provider itself. If you have trouble locating the module's source and can supply the `module` section of your Terraform configuration, I'd be happy to try to help point you in the right direction.

**Comment by zenbones** [comment]
II suppose I could just set create_kms_key:false, but this should be corrected. However, on further inspection I see kms_key_enable_default_policy, kms_key_owners, kms_key_administrators, etc. I had not looked for these earlier as I was not setting any kms_* values, and I was the user creating the cluster. I guess the intention here is that these attributes get set on the eks cluster resource, as opposed to directly exposing the kms sub-resource, which I think would have been the better direction, but I'm just looking for something useable. So I'll try adding our admins to kms_key_administrators or kms_key_owners.

**Comment by zenbones** [comment]
The above works, so given there's a way, I'm closing this ticket.

**Comment by zenbones** [comment]
Looking at this a little further, my guess is that the readiness probe was failing, but liveliness was not, which would have failed pod readiness, but not replaced the node, if I understand this correctly? If that's the case, I'm not sure the chosen probes are the most useful, but you have provided the facility to replace those.
