### ISSUE TITLE
[Enhancement]: Output EKS version

### ISSUE THREAD

**Issue by clementblaise** [hashicorp/terraform-provider-aws#30052]
### Description

Currently, only the platform_version is outputted. As we are using Crossplane, the Kubernetes version number would be helpful to act as the observed version of the resource. Without it, we need to rely on the version that is passed from the Claim but changing this value result in the cluster and the node pool being upgraded at the same time, which makes the node pool fail because the control plane is not yet updated.

If access to the observed version of the cluster is given, it could leverage to patch the version of the node pool. This would enable a complete cluster upgrade without any manual intervention.

### Affected Resource(s) and/or Data Source(s)

* aws_eks_cluster

### References

The mechanism was tested using the alternative `crossplane-contrib/provider-aws` provider which exposes the [version in the status](https://github.com/crossplane-contrib/provider-aws/blob/0cb838c3a94ae3d8ba529b2bd97d5050283c49c6/package/crds/eks.aws.crossplane.io_clusters.yaml#L816-L820)

If this enhancement is accepted a PR could be opened on the `upbound/provider-aws` to access the output and pass it to the status.

### Would you like to implement a fix?

None

**Comment by Antvirf** [comment]
Which version are you referring to? The control plane / main kubernetes version [is available](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#version).

```hcl
...

output "kubernetes_version" {
  value = aws_eks_cluster.example.version
}

...


Outputs:

kubernetes_version = "1.26"
```

**Comment by bryantbiggs** [comment]
@clementblaise is this issue still relevant or are we able to close it out now?

**Comment by clementblaise** [comment]
@bryantbiggs yes thanks for checking it can be close
