### ISSUE TITLE
[Enhancement]: Add the ability to the aws_eks_cluster to pull in cluster by arn

### ISSUE THREAD

**Issue by dreinhardt89** [hashicorp/terraform-provider-aws#30065]
### Description

I think this should be a function for all / most aws resources, where when possible you can look something up via arn, or unique name.

The specific case here is that we are pulling in the cluster via it's tags using aws_resourcegroupstaggingapi_resources then doing a data lookup after doing a regex on the arn returned.

It would be nice if we could use arn for the aws_eks_cluster data source *or* the name. Or if not that add tag filters to aws_eks_clusters.

Also would really like the data sources to be more consistent. IE adding the tag filter option when applicable, having the arn or other unique name for the required input (if every resource has a unique arn you should be able to use that arn to look up that resource as a data source barring data sources that return a list or map).

Also in the documentation here (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/eks_clusters) there is a typo in the title. Says "Data Source: aws_eks_cluster" should be "Data Source: aws_eks_clusters"

### Affected Resource(s) and/or Data Source(s)

* aws_eks_cluster
* aws_eks_clusters

### Potential Terraform Configuration

```terraform
data "aws_eks_cluster" "example" {
  arn = "example"
}

# Or if you want to add filters to aws_eks_clusters
data "aws_eks_clusters" "example" {
  tags = {
      Example = "Example"
  }
}
```

### Would you like to implement a fix?

None

**Comment by bryantbiggs** [comment]
The data source supports looking up clusters by a set of `names` now - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/eks_clusters#names

@dreinhardt89 is this issue still relevant or are we able to close it out?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
