### ISSUE TITLE
[Docs]: aws_codepipeline 

### ISSUE THREAD

**Issue by aniruddha-kulkarni24** [hashicorp/terraform-provider-aws#30087]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codepipeline

### Description

In aws_codepipeline  

statement {
    effect   = "Allow"
    actions  = ["codestar-connections:UseConnection"]
    **resource** = [aws_codestarconnections_connection.example.arn]
  }
instead of resource it should be resources .

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @aniruddha-kulkarni24 👋 Thank you for taking the time to raise this! I've opened a PR to fix this typo.
