### ISSUE TITLE
[Enhancement]: Support Feature Group Updates in aws_sagemaker_feature_group

### ISSUE THREAD

**Issue by lsamaha1-chwy** [hashicorp/terraform-provider-aws#30099]
### Description

Amazon SageMaker supports adding features to existing Feature Group schema as of July 2022 (launch announced [here](https://aws.amazon.com/about-aws/whats-new/2022/07/amazon-sagemaker-feature-store-new-features-existing-feature-groups/)). Current Terraform plans handle additional columns as an operation that forces replacement. Please add support for updating existing feature groups with new features.

### Affected Resource(s) and/or Data Source(s)

aws_sagemaker_feature_group

### Would you like to implement a fix?

None

**Comment by DrFaust92** [comment]
Duplicate of #26809
