### ISSUE TITLE
[Enhancement]: OpenSearch Off-Peak Window configuration

### ISSUE THREAD

**Issue by ReillyBrogan** [hashicorp/terraform-provider-aws#30104]
### Description

Configuring off-peak windows does not appear to be possible right now

### Affected Resource(s) and/or Data Source(s)

aws_opensearch_domain

### Potential Terraform Configuration

```terraform
off_peak_window_options {
  enabled: true
  off_peak_window {
    window_start_time {
      hours: 20
      minutes: 0
    }
  }
}
```

### References

https://github.com/aws/aws-sdk-js/blob/df86722c4a11378f4357382cf6bb48b14befaec2/apis/opensearch-2021-01-01.normal.json#L6404

https://docs.aws.amazon.com/opensearch-service/latest/developerguide/off-peak.html

### Would you like to implement a fix?

None

**Comment by benclapp** [comment]
I'm keen to work on this, might have some capacity this week.

**Comment by lockwobr** [comment]
Any chance this could be included in the aws_elasticsearch_domain as well?

**Comment by ReillyBrogan** [comment]
> Looks like `SoftwareUpdateOptions` has been added as well as part of this:
> 
> https://github.com/aws/aws-sdk-js/blob/3ee782cb76c328b1764be35edbec5c2eb8d81832/apis/opensearch-2021-01-01.normal.json#L5612

Way ahead of you #30103
