### ISSUE TITLE
[Bug]: Inspectorv2 enabler takes too long to enable inspector in an account. 

### ISSUE THREAD

**Issue by saad1998** [hashicorp/terraform-provider-aws#30144]
### Terraform Core Version

1.3.6

### AWS Provider Version

4.59.0

### Affected Resource(s)

resource "aws_inspector2_enabler" "example" {
  account_ids    = ["012345678901"]
  resource_types = ["EC2"]
}

### Expected Behavior

It should not take more than a minute to enable inspector with the above mentioned terraform resource.

### Actual Behavior

It takes a minute to enable inspector from the console, and the aws cli, but this terraform resource takes more than 15 minutes, and sometimes it takes hours to enable it in an account.

### Terraform Configuration Files

terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "4.59.0"
    }
  }
}

provider "aws" {
  region = eu-central-1
}

data "aws_caller_identity" "current" {}

resource "aws_inspector2_enabler" "test" {
  account_ids    = [data.aws_caller_identity.current.account_id]
  resource_types = ["ECR", "EC2","LAMBDA"]
}

### Steps to Reproduce

1. Just do terraform apply on the script above, and then you will see that it times out after 15 minutes. 
2. Then open the console, and check whether inspector is enabled or not.

### Would you like to implement a fix?

No

**Comment by gdavison** [comment]
Related to #27644
