### ISSUE TITLE
Migrate acceptance tests to `terraform-plugin-testing`

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#30162]
https://discuss.hashicorp.com/t/announcing-the-terraform-plugin-testing-module/49914:

> [terraform-plugin-testing](https://github.com/hashicorp/terraform-plugin-testing) is a new Go module for testing Terraform providers...
> [Migrating existing provider testing code](https://developer.hashicorp.com/terraform/plugin/testing/migrating) to use the Terraform Plugin Testing module should be relatively straightforward, generally only requiring updates to Go import paths without any expected changes to functionality...
> While both terraform-plugin-framework and terraform-plugin-sdk providers can safely use this module, we encourage the use of the Plugin Framework for all new provider development.

Requires https://github.com/hashicorp/terraform-provider-aws/pull/30155.
Requires https://github.com/hashicorp/terraform-provider-aws/issues/30163.

**Comment by johnsonaj** [comment]
Closed in #31161
