### ISSUE TITLE
[Enhancement]: aws_vpc_ipam_pool_cidr timeout support

### ISSUE THREAD

**Issue by lanecor** [hashicorp/terraform-provider-aws#30165]
### Description

When trying to remove a `aws_vpc_ipam_pool_cidr` resource where IPAM pool CIDR or allocation were recently removed (less than 30 minutes) as part of `terraform destroy`, the below error is encountered:

```
Error: waiting for IPAM Pool CIDR (10.0.0.0/16_ipam-pool-12345678901234567) delete: unexpected state 'failed-deprovision', wanted target ''. last error: : The CIDR has one or more allocations.
```

Currently this resource does not support the `timeouts` configuration block, causing deletion of parent pools to fail, as the IPAM service has not had enough time to cleanup the unused allocations. 

### Affected Resource(s) and/or Data Source(s)

aws_vpc_ipam_pool_cidr

### Potential Terraform Configuration

```terraform
resource "aws_vpc_ipam_pool" "this" {
  address_family      = "ipv4"
  auto_import         = true
  ipam_scope_id       = var.ipam_scope_id
  locale              = "us-east-1"
}

resource "aws_vpc_ipam_pool_cidr" "this" {
  ipam_pool_id = aws_vpc_ipam_pool.this.id
  cidr         = "10.0.0.0/16"
  
  timeouts { 
     delete = "30m" 
  }
}
```

### Would you like to implement a fix?

None

**Comment by drewmullen** [comment]
Can you confirm that the scenario is... An out of band change to deprovision the cidr happens. While its in the process of being deprovisioned (which can take up to 30m) and then the `terraform destroy` attempts to RE-deprovision which fails because the out of band change has already started that process

Is that an accurate understanding of the situation?

**Comment by lanecor** [comment]
Hi Drew, 

In our terraform stack we first create IPAM scope/pools/cidrs, then a VPC is deployed referencing the pool. Normally VPCs would be decoupled from this stack, but for a customer demo it needs to be in one stack. Therefore when running `terraform destroy` the VPC is destroyed first as expected, however, the allocations as you mentioned are typically held for 10-15 minutes in our environment before being released by IPAM service. The CIDR resource will attempt to destroy, retry logic allows some time but still times out. 

We understand this is an edge case not likely to be encountered often in the wild, but others may be in a similar situation where IPAM is deployed along with a VPC in the same stack as well. 

We'd like to enable a timeout for this resource in this case, to allow enough time for IPAM to cleanup the allocation. 

Thanks,
Corey

**Comment by awsml-axiamed** [comment]
Hey Drew,

Below is a sample test stack to recreate the issue and the corresponding error when running a terraform destroy.  It doesn't appear to be honoring the timeout.

```
Plan: 0 to add, 0 to change, 10 to destroy.
aws_vpc_ipam_pool_cidr.parent: Destroying... [id=10.0.0.0/8_ipam-pool-<scrubbed>]
aws_vpc.test: Destroying... [id=vpc-0e7159ea4f2f010be]
aws_vpc.test: Destruction complete after 1s
aws_vpc_ipam_pool_cidr.children[0]: Destroying... [id=10.0.0.0/12_ipam-pool-<scrubbed>]
aws_vpc_ipam_pool_cidr.children[1]: Destroying... [id=10.16.0.0/12_ipam-pool-<scrubbed>]
aws_vpc_ipam_pool_cidr.children[2]: Destroying... [id=10.32.0.0/12_ipam-pool-<scrubbed>]
aws_vpc_ipam_pool_cidr.parent: Still destroying... [id=10.0.0.0/8_ipam-pool-<scrubbed>, 10s elapsed]
aws_vpc_ipam_pool_cidr.children[2]: Still destroying... [id=10.32.0.0/12_ipam-pool-<scrubbed>, 10s elapsed]
aws_vpc_ipam_pool_cidr.children[0]: Still destroying... [id=10.0.0.0/12_ipam-pool-<scrubbed>, 10s elapsed]
aws_vpc_ipam_pool_cidr.children[1]: Still destroying... [id=10.16.0.0/12_ipam-pool-<scrubbed>, 10s elapsed]
aws_vpc_ipam_pool_cidr.children[1]: Destruction complete after 19s
aws_vpc_ipam_pool_cidr.children[2]: Destruction complete after 20s

│ Error: waiting for IPAM Pool CIDR (10.0.0.0/8_ipam-pool-<scrubbed>) delete: unexpected state 'failed-deprovision', wanted target ''. last error: : The CIDR has one or more allocations.

│ Error: waiting for IPAM Pool CIDR (10.0.0.0/12_ipam-pool-<scrubbed>) delete: unexpected state 'failed-deprovision', wanted target ''. last error: : The CIDR has one or more allocations.

```

```
terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

locals {
  enabled_regions = ["us-east-1", "us-east-2", "us-west-2"]
  parent_cidr     = "10.0.0.0/8"
}

resource "aws_vpc_ipam" "main" {
  cascade = true # for debugging purposes

  dynamic "operating_regions" {
    for_each = local.enabled_regions
    content {
      region_name = operating_regions.value
    }
  }
}

resource "aws_vpc_ipam_pool" "parent" {
  address_family = "ipv4"
  description    = "parent_pool"
  ipam_scope_id  = aws_vpc_ipam.main.private_default_scope_id
}

resource "aws_vpc_ipam_pool_cidr" "parent" {
  cidr         = local.parent_cidr
  ipam_pool_id = aws_vpc_ipam_pool.parent.id
}

resource "aws_vpc_ipam_pool" "children" {
  count = length(local.enabled_regions)

  address_family      = "ipv4"
  description         = "child_pool_${local.enabled_regions[count.index]}"
  ipam_scope_id       = aws_vpc_ipam.main.private_default_scope_id
  locale              = local.enabled_regions[count.index]
  source_ipam_pool_id = aws_vpc_ipam_pool.parent.id
}

resource "aws_vpc_ipam_pool_cidr" "children" {
  count = length(local.enabled_regions)

  cidr         = cidrsubnet(local.parent_cidr, 4, count.index)
  ipam_pool_id = aws_vpc_ipam_pool.children[count.index].id
}

resource "aws_vpc" "test" {
  ipv4_ipam_pool_id   = aws_vpc_ipam_pool.children[0].id
  ipv4_netmask_length = 20

  depends_on = [
    aws_vpc_ipam_pool_cidr.children
  ]
}
```

**Comment by mlynch1985** [comment]
Hey Drew,

Below is a sample test stack to recreate the issue and the corresponding error when running a terraform destroy.  It doesn't appear to be honoring the timeout.

```
Plan: 0 to add, 0 to change, 10 to destroy.
aws_vpc_ipam_pool_cidr.parent: Destroying... [id=10.0.0.0/8_ipam-pool-<scrubbed>]
aws_vpc.test: Destroying... [id=vpc-0e7159ea4f2f010be]
aws_vpc.test: Destruction complete after 1s
aws_vpc_ipam_pool_cidr.children[0]: Destroying... [id=10.0.0.0/12_ipam-pool-<scrubbed>]
aws_vpc_ipam_pool_cidr.children[1]: Destroying... [id=10.16.0.0/12_ipam-pool-<scrubbed>]
aws_vpc_ipam_pool_cidr.children[2]: Destroying... [id=10.32.0.0/12_ipam-pool-<scrubbed>]
aws_vpc_ipam_pool_cidr.parent: Still destroying... [id=10.0.0.0/8_ipam-pool-<scrubbed>, 10s elapsed]
aws_vpc_ipam_pool_cidr.children[2]: Still destroying... [id=10.32.0.0/12_ipam-pool-<scrubbed>, 10s elapsed]
aws_vpc_ipam_pool_cidr.children[0]: Still destroying... [id=10.0.0.0/12_ipam-pool-<scrubbed>, 10s elapsed]
aws_vpc_ipam_pool_cidr.children[1]: Still destroying... [id=10.16.0.0/12_ipam-pool-<scrubbed>, 10s elapsed]
aws_vpc_ipam_pool_cidr.children[1]: Destruction complete after 19s
aws_vpc_ipam_pool_cidr.children[2]: Destruction complete after 20s

│ Error: waiting for IPAM Pool CIDR (10.0.0.0/8_ipam-pool-<scrubbed>) delete: unexpected state 'failed-deprovision', wanted target ''. last error: : The CIDR has one or more allocations.

│ Error: waiting for IPAM Pool CIDR (10.0.0.0/12_ipam-pool-<scrubbed>) delete: unexpected state 'failed-deprovision', wanted target ''. last error: : The CIDR has one or more allocations.

```

```
terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

locals {
  enabled_regions = ["us-east-1", "us-east-2", "us-west-2"]
  parent_cidr     = "10.0.0.0/8"
}

resource "aws_vpc_ipam" "main" {
  cascade = true # for debugging purposes

  dynamic "operating_regions" {
    for_each = local.enabled_regions
    content {
      region_name = operating_regions.value
    }
  }
}

resource "aws_vpc_ipam_pool" "parent" {
  address_family = "ipv4"
  description    = "parent_pool"
  ipam_scope_id  = aws_vpc_ipam.main.private_default_scope_id
}

resource "aws_vpc_ipam_pool_cidr" "parent" {
  cidr         = local.parent_cidr
  ipam_pool_id = aws_vpc_ipam_pool.parent.id
}

resource "aws_vpc_ipam_pool" "children" {
  count = length(local.enabled_regions)

  address_family      = "ipv4"
  description         = "child_pool_${local.enabled_regions[count.index]}"
  ipam_scope_id       = aws_vpc_ipam.main.private_default_scope_id
  locale              = local.enabled_regions[count.index]
  source_ipam_pool_id = aws_vpc_ipam_pool.parent.id
}

resource "aws_vpc_ipam_pool_cidr" "children" {
  count = length(local.enabled_regions)

  cidr         = cidrsubnet(local.parent_cidr, 4, count.index)
  ipam_pool_id = aws_vpc_ipam_pool.children[count.index].id
}

resource "aws_vpc" "test" {
  ipv4_ipam_pool_id   = aws_vpc_ipam_pool.children[0].id
  ipv4_netmask_length = 20

  depends_on = [
    aws_vpc_ipam_pool_cidr.children
  ]
}
```

**Comment by drewmullen** [comment]
@awsml-axiamed & @mlynch1985 thanks for both of your inputs

Can you please confirm the version of the provider youre on

**Comment by awsml-axiamed** [comment]
Sure thing.

```
$ tf version
Terraform v1.4.2
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.58.0
```

**Comment by mlynch1985** [comment]
Sure thing.

```
$ tf version
Terraform v1.4.2
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.58.0
```

**Comment by x2lcetins4pa** [comment]
I am getting the same exact error when trying to run a Terraform destroy ->
 Error: waiting for IPAM Pool CIDR (192.168.192.0/18_ipam-pool-0b14282cdda6542b7) delete: unexpected state 'failed-deprovision', wanted target ''. last error: : The CIDR has one or more allocations.

I'm using Terraform 1.4.0 and AWS Provider version "4.67.0"

Code ->

`resource "aws_vpc_ipam" "ipam" {
  description = "${local.unique_name}-ipam"

  dynamic operating_regions {
    for_each = ["eu-west-1","us-east-1"]
    content {
      region_name = operating_regions.value
    }
  }
  tags = var.tags
}

resource "aws_vpc_ipam_pool" "top_level" {
  description    = "${local.unique_name}-top-level-pool"
  address_family = "ipv4"
  ipam_scope_id  = aws_vpc_ipam.ipam.private_default_scope_id

  tags = var.tags

}

resource "aws_vpc_ipam_pool_cidr" "top_level" {
  ipam_pool_id = aws_vpc_ipam_pool.top_level.id
  cidr         = "192.168.0.0/18"

  depends_on = [
    aws_vpc_ipam_pool.top_level
  ]
}
resource "aws_vpc_ipam_pool_cidr" "top_level2" {
  ipam_pool_id = aws_vpc_ipam_pool.top_level.id
  cidr         = "192.168.64.0/18"

  depends_on = [
    aws_vpc_ipam_pool.top_level
  ]
}


resource "aws_vpc_ipam_pool" "regional_west" {
  description                       = "${local.unique_name}-pool"
  address_family                    = "ipv4"
  ipam_scope_id                     = aws_vpc_ipam.ipam.private_default_scope_id
  locale                            = "eu-west-1"
  source_ipam_pool_id               = aws_vpc_ipam_pool.top_level.id
  allocation_default_netmask_length = 27
  allocation_min_netmask_length     = 26
  allocation_max_netmask_length     = 28
  auto_import                       = true
  tags                              = var.tags
}

resource "aws_vpc_ipam_pool" "regional_east" {
  description                       = "${local.unique_name}-pool"
  address_family                    = "ipv4"
  ipam_scope_id                     = aws_vpc_ipam.ipam.private_default_scope_id
  locale                            = "us-east-1"
  source_ipam_pool_id               = aws_vpc_ipam_pool.top_level.id
  allocation_default_netmask_length = 27
  allocation_min_netmask_length     = 26
  allocation_max_netmask_length     = 28
  auto_import                       = true
  tags                              = var.tags
}


resource "aws_vpc_ipam_pool_cidr" "regional_east" {
  ipam_pool_id = aws_vpc_ipam_pool.regional_east.id
  cidr         = "192.168.0.0/18"

  depends_on = [
    aws_vpc_ipam_pool.regional_east
  ]
}

resource "aws_vpc_ipam_pool_cidr" "regionali_west" {
  ipam_pool_id = aws_vpc_ipam_pool.regional_west.id
  cidr         = "192.168.64.0/18"

  depends_on = [
    aws_vpc_ipam_pool.regional_west
  ]
}
`

**Comment by mrtnfchs** [comment]
We are facing the same issue with an IPAM pool structure of GLOBAL pool --> ZONE pools --> REGION pools whereas VPC created by the same stack allocate CIDRs from the REGION pools as well as transit gateway custom-allocating CIDRs from that same pool.

```
│ Error: waiting for IPAM Pool CIDR (10.188.0.0/18_ipam-pool-0600f165b042b33f0) delete: unexpected state 'failed-deprovision', wanted target ''. last error: : The CIDR has one or more allocations.
│ Error: waiting for IPAM Pool CIDR (10.184.0.0/18_ipam-pool-0caef565eed5ba879) delete: unexpected state 'failed-deprovision', wanted target ''. last error: : The CIDR has one or more allocations.
│ Error: waiting for IPAM Pool CIDR (10.176.0.0/18_ipam-pool-07491fad9790e8621) delete: unexpected state 'failed-deprovision', wanted target ''. last error: : The CIDR has one or more allocations.
```

Terraform version: v1.3.5
Terraform AWS Provider: 4.58.0

**Comment by brikis98** [comment]
The problem here is mentioned in the [`aws_vpc_ipam_pool_cidr` docs](aws_vpc_ipam_pool_cidr):

> In order to deprovision CIDRs all Allocations must be released. Allocations created by a VPC take up to 30 minutes to be released. 

So if your `aws_vpc` times out on deletion with the error above (`Error: waiting for IPAM Pool CIDR (xxx) delete: unexpected state 'failed-deprovision', wanted target ''. last error: : The CIDR has one or more allocations.`), a retry ~10 minutes later will succeed. 

An easy solution for this would be to set the `delete` value in `timeouts` to ~35m, but `aws_vpc` doesn't support user-configurable timeouts :(

**Comment by brikis98** [comment]
Here's the hard-coded 20m timeout in the `aws_vpc` code, which is not long enough: https://github.com/hashicorp/terraform-provider-aws/blob/15451a6e60be94f1f4ff7b6d80519b7838799634/internal/service/ec2/vpc_.go#L485C8-L485C38

**Comment by drewmullen** [comment]
This used to be handled gracefully, albeit bluntly. The resource just retried delete until the resource was deleted. I just havent had time to look into it

https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ec2/ipam_pool_cidr.go#L191-L207

Timeouts would be nice for VPC but the resource error is a bug since we **know** it can take up to 20min for an allocation to be deleted

**Comment by brikis98** [comment]
Potential fix: https://github.com/brikis98/terraform-provider-aws/pull/1
