### ISSUE TITLE
AWS Glue studio notebook using terraform

### ISSUE THREAD

**Issue by SivaSuriyanP** [hashicorp/terraform-provider-aws#30171]
### Description

Hi All,

I am trying to create an AWS Glue Studio Notebook using Terraform . but i am unable to find exact resource name for that service in Terraform Website. If anyone having Idea on this please help.

### Would you like to implement a fix?

None

**Comment by TimXL** [comment]
> * 👍

**Comment by justinretzolk** [comment]
Hey @SivaSuriyanP 👋 Unless I'm overlooking it, it doesn't appear that there's an API for interacting with Glue Studio. Without the underlying API, we'll not be able to add resources to the AWS provider for Terraform.
