### ISSUE TITLE
[Enhancement]: aws_ses_domain_identity does not support tags. 

### ISSUE THREAD

**Issue by pawangupta99** [hashicorp/terraform-provider-aws#30215]
### Description

Currently tags are not supported for aws_ses_domain_identity resource. I verified with hashicorp/aws v4.40.0. Its supported in AWS console but when we try using in the resource its throws an error. 
<img width="627" alt="Screenshot 2023-03-22 at 10 43 40 AM" src="https://user-images.githubusercontent.com/4026371/226992572-27549b94-44d1-4736-bec1-63b455b03bcf.png">
<img width="799" alt="Screenshot 2023-03-22 at 10 43 05 AM" src="https://user-images.githubusercontent.com/4026371/226992579-f907476b-b660-4a55-93fb-ab5a1fa86151.png">

### Affected Resource(s) and/or Data Source(s)

aws_ses_domain_identity

### Potential Terraform Configuration

```terraform
resource "aws_ses_domain_identity" "ses" {
  domain = "xx.com" # The domain name to assign to SES.
  tags   = var.common_tags
}
```

### References

https://github.com/hashicorp/terraform-provider-aws/issues/23955

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @pawangupta99 👋 Thank you for taking the time to raise this! Based on #23955, it looks like you can use the [`aws_sesv2_email_identity` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_email_identity), which supports tags.

**Comment by WillyGitty** [comment]
Hello @justinretzolk, 

From my local terraform execution of [aws_sesv2_email_identity resource](https://registry.terraform.io/providers/hashicorp/aws/4.63.0/docs/resources/sesv2_email_identity), It seems that we can define **tags** as a argument(input) in terraform and it sucessfully creates them. 

However, the current docs are not exposing this functionallity in https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_email_identity#argument-reference.

I think adding the **tags** argument (input) in the docs will remove confusion about the ability to add tags.

On a side notes, the **tags** attribute (output) is well defined in the docs.

**Comment by justinretzolk** [comment]
Hey @WillyGitty 👋 Thank you for pointing that out! I've opened a pull request to move the `tags` argument description up to the Arguments section, rather than having it under the Attributes section.

**Comment by tmatilai** [comment]
Maybe I'm missing something, but the domain and email identities both [have their own use cases](https://docs.aws.amazon.com/ses/latest/dg/creating-identities.html). Even though one could use the email identity, IMHO the tags should be an argument for the `aws_ses_domain_identity`, too.
