### ISSUE TITLE
Avoid to delete network interface when destroy a Ec2 instance

### ISSUE THREAD

**Issue by medusaalb** [hashicorp/terraform-provider-aws#30210]
### Description

I'm trying to change ami in a EC2 instance, and it forces to recreate a EC2 but when terraform is destroying the EC2  destroy the network interface too.
How can i save that network interface to assing it to the recreated Ec2 with the new ami?  

i had used in the aws_instance the network interface block:
```terraform
network_interface {
        network_interface_id = var.eni
        device_index         = 0
        delete_on_termination = false
    }
```
but it doesn't prevent to destroy it

Thanks in advance

### Would you like to implement a fix?

None

**Comment by good92** [comment]
Workaround:

1. Create https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/network_interface
You can use https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#prevent_destroy inside it.

3. Attach it to the ec2

```
resource "aws_instance" "app" {
  depends_on = [aws_network_interface.app_eni]

  network_interface {
    device_index         = 0
    network_interface_id = aws_network_interface.app_eni.id
  }
```

**Comment by justinretzolk** [comment]
Hey @medusaalb 👋 Thank you for taking the time to raise this! Were you able to test the option that was provided above to work around the issue?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
