### ISSUE TITLE
[Bug]: aws_iot_topic_rule does not support cloudwatch_logs

### ISSUE THREAD

**Issue by ThomasVdBerge** [hashicorp/terraform-provider-aws#30248]
### Terraform Core Version

1.4.0

### AWS Provider Version

4.60.0

### Affected Resource(s)

aws_iot_topic_rule

### Expected Behavior

an error_action for cloudwatch logs is added.

### Actual Behavior

Error with

"Blocks of type 'cloudwatch_logs' are not expected here 

### Relevant Error/Panic Output Snippet

The error_action block is reported to support cloudwatch_logs in the Terraform documentation here https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_topic_rule.html, However it does not seem to be added at all (https://github.com/kurtmc/terraform-provider-aws/blob/master/aws/resource_aws_iot_topic_rule.go#L457)

### Terraform Configuration Files

```
resource "aws_iot_topic_rule" "test" {
  name = "test_${terraform.workspace}"
  enabled = true
  sql = "SELECT * FROM 'test'"
  sql_version = "2016-03-23"
  
  sqs {
    queue_url = aws_sqs_queue.test.url
    role_arn = aws_iam_role.iam_iot.arn
    use_base64 = false
  }
  error_action {
    cloudwatch_logs {
      log_group_name = test
      role_arn = aws_iam_role.iam_iot.arn
    }
  }
}
```

### Steps to Reproduce

Add Code.
Run with terraform plan.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @ThomasVdBerge 👋 Thank you for taking the time to raise this! Support for `cloudwatch_logs` was added in [version 4.6.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#460-march-18-2022) of the provider with #23440. It looks like you linked to a fork of the AWS provider. The spot in the code where this is implemented on the official provider can be found [here](https://github.com/hashicorp/terraform-provider-aws/blob/14aeb6aad2c4a683deef58827cb622d492656b82/internal/service/iot/topic_rule.go#L268-L286).

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
