### ISSUE TITLE
[New Resource]: Be able to apply tags to AWS Organizations Accounts that were created outside of Terraform

### ISSUE THREAD

**Issue by reifnir** [hashicorp/terraform-provider-aws#30240]
### Description

It is currently possible to tag Accounts in AWS Organizations only when created using the `aws_organizations_account` resource.

For AWS Accounts that are created through Control Tower (or other), there's currently no way to apply these in Terraform without resorting to scripting.

Currently we have to do it procedurally:
```bash
aws organizations tag-resource --resource-id "$ACCOUNT_ID" --tags "Key=$TAG_NAME,Value=$TAG_VALUE"
```

There is already a data source for `aws_organizations_resource_tags`. Having either an `aws_organizations_tag` or `aws_organizations_account_tag` resource (similar to `aws_ec2_tag`) would be a big help.

### Requested Resource(s) and/or Data Source(s)

* aws_organizations_tag

### Potential Terraform Configuration

```terraform
resource "aws_organizations_tag" "environment" {
  resource_id = var.account_id
  key         = "Environment"
  value       = var.environment
}

# Or...
locals {
  tags = {
    "Environment" = var.environment
    "Tag2"        = var.another_tag_property
  }
}
resource "aws_organizations_tag" "account_tags" {
  for_each = local.tags
  resource_id = var.account_id
  key         = each.key
  value       = each.value
}
```

### References

[AWS | Organizations | Tag Resource](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/organizations/tag-resource.html)
(works for both new and existing tags for a given key)
Ex: `aws organizations tag-resource --resource-id "$ACCOUNT_ID" --tags "Key=$TAG_NAME,Value=$TAG_VALUE"`

[AWS | Organizations | List Tags For Resource](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/organizations/list-tags-for-resource.html)
Ex: `aws organizations list-tags-for-resource --resource-id "$ACCOUNT_ID" --output json`

[AWS | Organizations | Untag Resource](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/organizations/untag-resource.html)
Ex: `aws organizations untag-resource --resource-id "$ACCOUNT_ID" --tag-keys "$TAG_NAME"`

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@reifnir Thanks for raising this issue.
It has already been noticed in #19660. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by reifnir** [comment]
I'm glad that you de-duped my issue, but it's not exactly heartening that the one you referenced is over 2 years old.
