### ISSUE TITLE
[Docs]: statement block should wrap data.aws_iam_policy_document.authenticated_role_policy for aws_cognito_identity_pool_roles_attachment resource

### ISSUE THREAD

**Issue by matts009** [hashicorp/terraform-provider-aws#30255]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_identity_pool_roles_attachment

### Description

A statement block should wrap the data.aws_iam_policy_document.authenticated_role_policy resource in the example for an aws_cognito_identity_pool_roles_attachment resource. It is missing and if copied to code, terraform will throw an error.

### Would you like to implement a fix?

Yes

**Comment by mattburgess** [comment]
@matts009 - thanks for reporting, and apologies for introducing this issue. I'm happy to fix this up but as you mentioned in your report that you'd like to implement a fix for it I don't mind leaving it to you. Just let me know.

**Comment by justinretzolk** [comment]
Hey @matts009 👋 Thank you for taking the time to raise this! It looks like this was fixed by #30443, so we'll close this one out.
