### ISSUE TITLE
[Bug]: data aws_route doesn't find a matching route

### ISSUE THREAD

**Issue by johnlister** [hashicorp/terraform-provider-aws#30271]
### Terraform Core Version

1.3.6

### AWS Provider Version

4.60.0

### Affected Resource(s)

data aws_route

### Expected Behavior

When trying to fetch a route using aws_route data resource it should return the corresponding route resource when filtering on a prefix_list destination

### Actual Behavior

Instead of the route resource the following error is returned.
`No routes matching supplied arguments found in Route Table (rtb-01383XXXXXX305f)`

All other routes can be matched, for example using destination_cidr_block, etc. 
Turning on TRACE debugging, I can see the AWS describeRouteTables API call is made for the given route table ID and the response includes the corresponding routes, yet these seem to be filtered out by the provider. Trace output filtered below.
The only difference is the origin field is set to _CreateRoute_ instead of _CreateRouteTable_

### Terraform Configuration Files

```terraform
data "aws_route" "vpce" {
  route_table_id = "rtb-01383XXXXXX305f"
  destination_prefix_list_id = "pl-78XXX011"
}
```

### Steps to Reproduce

do a plan/ apply when fetching a route 

### Debug Output

```xml
<DescribeRouteTablesResponse xmlns="http://ec2.amazonaws.com/doc/2016-11-15/">
    <requestId>5959d9b4-XXXX-XXXX-XXXX-c54424391167</requestId>
    <routeTableSet>
        <item>
            <routeTableId>rtb-01383XXXXXX305f</routeTableId>
            <vpcId>vpc-03880XXXXXXXX28d</vpcId>
            <ownerId>293XXXXX610</ownerId>
            <routeSet>
                <item>
                    <destinationCidrBlock>10.204.32.0/19</destinationCidrBlock>
                    <gatewayId>local</gatewayId>
                    <state>active</state>
                    <origin>CreateRouteTable</origin>
                </item>
                ...
                <item>
                    <gatewayId>vpce-04c6XXXXXXXXbfe1</gatewayId>
                    <destinationPrefixListId>pl-78XXX011</destinationPrefixListId>
                    <state>active</state>
                    <origin>CreateRoute</origin>
                </item>
            </routeSet>
```

### Would you like to implement a fix?

None

**Comment by tamiros** [comment]
It's because of this:
https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ec2/vpc_route_data_source.go#L126-L130
