### ISSUE TITLE
[Docs]: aws_rds_cluster missing storage type "aurora" 

### ISSUE THREAD

**Issue by ffelici-sumo** [hashicorp/terraform-provider-aws#30287]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/4.40.0/docs/resources/rds_cluster#storage_type

### Description

Hi all, we encountered a curious mismatch this morning in our state for the AWS part of **aws_rds_cluster**.

On our state the value that was previously valued at null has been changed by default to "aurora" and now asking us to replace our cluster.

This is a value we can't find on the documentation, the question is, does the value exist and should it be considered?

I will paste the plan, if can be helpful.

```terraform
  module.aurora-db.aws_rds_cluster.rds_cluster must be replaced
-/+ resource "aws_rds_cluster" "rds_cluster" {
      ~ allocated_storage                   = 1 -> (known after apply)
      ~ arn                                 = "------" -> (known after apply)
      ~ availability_zones                  = [
          - "us-west-1a",
          - "us-west-1b",
          - "us-west-1c",
        ] -> (known after apply)
      - backtrack_window                    = 0 -> null
      + cluster_identifier_prefix           = (known after apply)
      ~ cluster_members                     = [
          - "------",
          - "------",
        ] -> (known after apply)
      ~ cluster_resource_id                 = "------" -> (known after apply)
      - db_cluster_instance_class           = "" -> null
      ~ db_cluster_parameter_group_name     = "------" -> (known after apply)
      - enabled_cloudwatch_logs_exports     = [] -> null
      ~ endpoint                            = "------" -> (known after apply)
      ~ engine_version_actual               = "13.9" -> (known after apply)
      - global_cluster_identifier           = "" -> null
      ~ hosted_zone_id                      = "------" -> (known after apply)
      - iam_database_authentication_enabled = false -> null
      ~ iam_roles                           = [] -> (known after apply)
      ~ id                                  = "------" -> (known after apply)
      - iops                                = 0 -> null
      ~ kms_key_id                          = "------" -> (known after apply)
      ~ network_type                        = "IPV4" -> (known after apply)
      ~ port                                = 5432 -> (known after apply)
      ~ preferred_backup_window             = "12:15-12:45" -> (known after apply)
      ~ preferred_maintenance_window        = "sun:08:15-sun:08:45" -> (known after apply)
      ~ reader_endpoint                     = "------" -> (known after apply)
      - replication_source_identifier       = "" -> null
      - snapshot_identifier                 = "" -> null
      ~ storage_type                        = "aurora" -> "" # forces replacement
      - tags                                = {} -> null
        (19 unchanged attributes hidden)
        (1 unchanged block hidden)
    }
```

### Would you like to implement a fix?

None

**Comment by galsolo** [comment]
exact same issue, us-west-1 only.

**Comment by TopoDiFogna** [comment]
same behaviour in eu-south-1

**Comment by SZLforGithub** [comment]
same issue in ap-south-1

**Comment by herber523** [comment]
same issue in ap-south-1

We use 'lifecycle ignore_changes' to workaround this issue.
```
lifecycle {
    ignore_changes = [
        storage_type
    ]
}
```

**Comment by tstraley** [comment]
It is concerning that we had the exact same terraform code with the same provider versions execute earlier in the day with no change to our RDS cluster, and a few hours later, it is now planning to replace our RDS database. I suppose this points to some change in the AWS API that this provider is using to determine this storage type, but maybe this should categorized as more impactful than just "docs" issue?

**Comment by grimm26** [comment]
FYI I have a case open through my company's enterprise support contract and I am trying to get them to roll this back. It was intentional on their part, but it is undocumented and I wouldn't be surprised if it broke Cloudformation stacks as well.

**Comment by nerryc** [comment]
Seems this is now resolved, AWS confirmed the issue and rolled back the change.

**Comment by Ameeduzzama** [comment]
This problem still exists or has it been fixed?

**Comment by grimm26** [comment]
> This problem still exists or has it been fixed?

It has been fixed. AWS rolled back the change.

**Comment by davendarkojha** [comment]
Hi all, fyi this issue has started to happen again.

**Comment by jeremy-albuixech** [comment]
This is happening again, on `ap-south-1`
