### ISSUE TITLE
[Bug]: Security group created with empty rules on RulesPerSecurityGroupLimitExceeded: The maximum number of rules per security group has been reached. 

### ISSUE THREAD

**Issue by good92** [hashicorp/terraform-provider-aws#30289]
### Terraform Core Version

1.3.9

### AWS Provider Version

4.59.0 and 4.60.0

### Affected Resource(s)

 Security group is created with empty inbound/outbound rules on Error: RulesPerSecurityGroupLimitExceeded: The maximum number of rules per security group has been reached. 

### Expected Behavior

Do not create the resource on error or re-destroy the resource before doing anything with it
 and pre-validate the max rules at plan step.

https://github.com/hashicorp/terraform-provider-aws/issues/465 aws_security_group should validate number of rules

### Actual Behavior

Create a broken resource, that fails to be replaced on the second run.

### Relevant Error/Panic Output Snippet

```shell
Error: updating Security Group (sg-XXXXXXXX) ingress rules: authorizing Security Group (ingress) rules: RulesPerSecurityGroupLimitExceeded: The maximum number of rules per security group has been reached.
│ 	status code: 400, request id: XXXXX-XXX-XXXX-XXXX-XXXXXX
│ 
│   with aws_security_group.linux-sg,
│   on 3_create_network_security_groups.tf line 82, in resource "aws_security_group" "linux-sg":
│   82: resource "aws_security_group" "linux-sg" {
```

### Terraform Configuration Files

.

### Steps to Reproduce

.

### Important Factoids

The single Security Group is associated to an ENI with a single private IP address then linked to an EC2

Workaround: 
1. Manually remove the security group with empty inbound/outbound rules, it then allows its re-creation. 
2. Split the security group rules in another Security Group (support multi SGs) in order to be below the RulesPerSecurityGroupLimit max threshold.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @good92 👋 Thank you for taking the time to raise this! So that we have the necessary information to look into this, can you supply a Terraform configuration that reproduces the error, along with debug logs (redacted as needed)?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
