### ISSUE TITLE
[Bug]: instance_requirements blocks not allowed despite being documented as of 4.57

### ISSUE THREAD

**Issue by mikesarfaty** [hashicorp/terraform-provider-aws#30304]
### Terraform Core Version

1.4.2

### AWS Provider Version

4.6.0

### Affected Resource(s)

aws_launch_template

### Expected Behavior

I can configure a launch template like so..

```
resource "aws_launch_template" "main" {
  name_prefix = var.name
  image_id    = data.aws_ami.amazon-linux-2.id

  instance_requirements {
    allowed_instance_types = ["t3.medium", "t2.medium"]
  }

}
```

and the launch template will be created

### Actual Behavior

The launch template will fail to create, saying that the instance_requirements blocks is not supported, despite being mentioned in release notes [here](https://github.com/hashicorp/terraform-provider-aws/blob/v4.57.0/CHANGELOG.md)

> resource/aws_launch_template: Add instance_requirements.allowed_instance_types and instance_requirements.network_bandwidth_gbps arguments (https://github.com/hashicorp/terraform-provider-aws/issues/29140)

### Relevant Error/Panic Output Snippet

```shell
│ Error: Unsupported block type
│
│   on ../modules/asg/launch_template.tf line 17, in resource "aws_launch_template" "main":
│   17:   instance_requirements {
│
│ Blocks of type "instance_requirements" are not expected here.
```

### Terraform Configuration Files

Along with the above block, I was using this data source

```
data "aws_ami" "amazon-linux-2" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["amzn2-ami-hvm*"]
  }
}
```

### Steps to Reproduce

1. Create a Launch Template
2. Try to use the `instance_requirements` block
3. Terraform init + apply with tf1.4.2 and aws-provider 4.6.0

### Debug Output

```
terraform providers

Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/aws] ~> 4.6.0
```

### Important Factoids

It's of note that the documentation on this feature looks incomplete - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#instance-requirements

There are no examples, and it does not give you the code-formatted block `instance_requirements`, which is weird.

### Would you like to implement a fix?

None

**Comment by krishnaduttPanchagnula** [comment]
I tried replicating this error, but am unable to replicate it. Also from the terraform documentation it says that memory_mib and vcpu_count ( atleast the min values for both these blocks) must be specified. I was able to perfectly create aws templetes. Here is my code : 

`terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.60.0"
    }
  }
}

resource "aws_launch_template" "main" {
  name_prefix = "test_templete"
  image_id    = data.aws_ami.amazon-linux-2.id

  instance_requirements {
    allowed_instance_types = ["t3.medium", "t2.medium"]
    memory_mib {
      min = 1
      max = 3
    }
    vcpu_count {
      min = 1
      max = 2

    }
  }

}

data "aws_ami" "amazon-linux-2" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["amzn2-ami-hvm*"]
  }
}`

Here is my result:
![image](https://user-images.githubusercontent.com/84926220/228444329-4d57397e-bed6-4829-aa5e-507f305f2e99.png)

**Comment by mikesarfaty** [comment]
I am embarrassed to say that I was missing a 0 in my provider config, and was using `4.6.0` instead of `4.60.0`

Wow.. just wow. I knew this bug was too ridiculous to be true. Thanks for the response, @krishnaduttPanchagnula 

Closing
