### ISSUE TITLE
[Bug]: If aws_iot_policy already has max number of versions in it, it fails to create a new version.

### ISSUE THREAD

**Issue by AnshulAngaria** [hashicorp/terraform-provider-aws#30314]
### Terraform Core Version

1.4.2

### AWS Provider Version

4.60.0

### Affected Resource(s)

aws_iot_policy

### Expected Behavior

If there are already 5 (max number of version allowed) versions of a policy, delete the oldest non default version and then create new version.

### Actual Behavior

Terraform throws an error that Versions limit has been exceeded.

### Relevant Error/Panic Output Snippet

```shell
│ Error: updating IoT Policy (PubSubToAnyTopic): VersionsLimitExceededException: The policy PubSubToAnyTopic already has the maximum number of versions (5)
│
│   with aws_iot_policy.pubsub,
│   on main.tf line 1, in resource "aws_iot_policy" "pubsub":
│    1: resource "aws_iot_policy" "pubsub" {
```

### Terraform Configuration Files

```
resource "aws_iot_policy" "pubsub" {
  name = "PubSubToAnyTopic"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = [
          "iot:6",
        ]
        Effect   = "Allow"
        Resource = "*"
      },
    ]
  })
}
```

### Steps to Reproduce

Run terraform apply 5 times to create 5 versions of this policy. In each apply, change the topic by just changing the number ("iot:6" here). Now run terraform apply 6th time and you will see error.

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @AnshulAngaria 👋 Thank you for taking the time to raise this! Looking at the AWS API documentation for [CreatePolicyVersion](https://docs.aws.amazon.com/iot/latest/apireference/API_CreatePolicyVersion.html), it mentions that in order to overcome this, you must use `DeletePolicyVersion` to remove one of the existing policy versions before creating a new one. I'm not certain whether this is behavior that we'd be want, or be able to, implement directly in the resource, but I'd like to leave this open as an enhancement request so that the team can look at this once it can be prioritized.

**Comment by AnshulAngaria** [comment]
Thanks @justinretzolk , is there a way to achieve this from terraform, can you point me to some doc.
Also it would be great to have this behavior in the resource itself just like aws_iam_policy.

**Comment by omaric-hw** [comment]
>  is there a way to achieve this from terraform, can you point me to some doc.

Indeed there is. You must destroy and recreate your policy, which can be done with 

```
terraform apply -replace=aws_iot_policy.claim_policy
```

However, if you're like me that won't work and you'll get an error:
```
 DeleteConflictException: The policy cannot be deleted as the policy is attached to one or more principals
```

In that case, you can either try to destroy multiple resources in exactly the right order, or you can just run `terraform destroy` and then `terraform apply` to destroy everything and recreate it again. That's what worked for me.

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/9540.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/24979.
