### ISSUE TITLE
[Bug]: Using File with aws_ecs_service produces "Error: creating ECS Service (nginx): InvalidParameterException: Invalid revision number."

### ISSUE THREAD

**Issue by snmason** [hashicorp/terraform-provider-aws#30313]
### Terraform Core Version

v1.4.2

### AWS Provider Version

v4.60.0

### Affected Resource(s)

aws_ecs_service creation

### Expected Behavior

Expect terraform to deploy service using task definition as output in the plan. This is an example definition taken from AWS samples and creates fine via the JSON import from the console. 

```
`  # aws_ecs_service.cluster[0] will be created
  + resource "aws_ecs_service" "cluster" {
      + cluster                            = "arn:aws:ecs:us-west-1:XXXXXXX:cluster/JenkinsFargateCluster"
      + deployment_maximum_percent         = 200
      + deployment_minimum_healthy_percent = 100
      + desired_count                      = 1
      + enable_ecs_managed_tags            = false
      + enable_execute_command             = false
      + iam_role                           = (known after apply)
      + id                                 = (known after apply)
      + launch_type                        = (known after apply)
      + name                               = "nginx"
      + platform_version                   = (known after apply)
      + scheduling_strategy                = "REPLICA"
      + tags_all                           = (known after apply)
      + task_definition                    = jsonencode(
            {
              + containerDefinitions    = [
                  + {
                      + cpu              = 256
                      + essential        = true
                      + image            = "nginx:latest"
                      + logConfiguration = {
                          + logDriver = "awslogs"
                          + options   = {
                              + awslogs-group         = "awslogs-nginx-ecs"
                              + awslogs-region        = "us-west-1"
                              + awslogs-stream-prefix = "ecs"
                            }
                        }
                      + memory           = 256
                      + name             = "nginx:1"
                      + portMappings     = [
                          + {
                              + containerPort = 80
                              + protocol      = "tcp"
                            },
                        ]
                    },
                ]
              + cpu                     = "256"
              + executionRoleARN        = "arn:aws:iam::XXXXXXXXX:role/aws-service-role/ecs.amazonaws.com/AWSServiceRoleForECS"
              + family                  = "nginx"
              + memory                  = "512"
              + networkMode             = "awsvpc"
              + placementConstraints    = []
              + requiresCompatibilities = [
                  + "FARGATE",
                ]
              + volumes                 = []
            }
        )
      + triggers                           = (known after apply)
      + wait_for_steady_state              = false

      + ordered_placement_strategy {
          + field = "cpu"
          + type  = "binpack"
        }
    }`
```

### Actual Behavior

Errors with the following:

```
│```
 Error: creating ECS Service (nginx): InvalidParameterException: Invalid revision number. Number:  [
│     "FARGATE"
│   ],
│   "containerDefinitions": [
│     {
│       "name": "nginx",
│       "image": "nginx:latest",
│       "memory": 256,
│       "cpu": 256,
│       "essential": true,
│       "portMappings": [
│         {
│           "containerPort": 80,
│           "protocol": "tcp"
│         }
│       ],
│       "logConfiguration":{
│             "logDriver":"awslogs",
│             "options":{
│                "awslogs-group":"awslogs-nginx-ecs",
│                "awslogs-region":"us-west-1",
│                "awslogs-stream-prefix":"ecs"
│             }
│       }
│     }
│   ],
│   "volumes": [],
│   "networkMode": "awsvpc",
│   "executionRoleARN": "arn:aws:iam::xxxxxxxxxx:role/aws-service-role/ecs.amazonaws.com/AWSServiceRoleForECS",
│   "placementConstraints": [],
│   "family": "nginx",
│   "memory": "512",
│   "cpu": "256"
│ }
│
│   with aws_ecs_service.cluster[0],
│   on ecs.tf line 47, in resource "aws_ecs_service" "cluster":
│   47: resource "aws_ecs_service" "cluster" {
```

### Terraform Configuration Files

https://github.com/snmason/cloud-lab-tf

* task definition missing "executionRoleARN" pointing to a service role in my account to avoid committing account id. 

### Steps to Reproduce

terraform apply -lock=false

### References

https://github.com/aws-samples/aws-containers-task-definitions/blob/master/nginx/nginx_fargate.json

### Would you like to implement a fix?

None

**Comment by trevorrea** [comment]
Hi,

The task defintion is not supposed to be defined like that. If you look at the docs at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service#task_definition it expects something like "arn:aws:ecs:eu-west-2:xxxxxxxxxxxxxxxx:task-definition/taskdefinitioname:revision" ie. "arn:aws:ecs:eu-west-2:11111111111111111:task-definition/task:11"

If you want to use jsonencode to create the task definition then use the separate task definition resource at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition and reference this in your ECS service ie. task_definition = aws_ecs_task_definition.task.arn

Thanks,
Trevor

**Comment by justinretzolk** [comment]
Hey @snmason 👋 Thank you for taking the time to raise this! As @trevorrea mentioned above, the `task_definition` argument of the `aws_ecs_service` resource takes either a full ARN or a `family:revision` reference to an existing task definition, which can be created via the [`aws_ecs_task_definition` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition).

**Comment by snmason** [comment]
Thanks all for responding. I actually tried this config as well before posting but hit another error and just posted this one. Apologies for not including this.

The suggesting config 

```
resource "aws_ecs_service" "cluster" {
  count = var.ecs_cluster["JenkinsFargateCluster"].enabled ? 1 : 0

  name = "nginx"
  cluster = aws_ecs_cluster.cluster["JenkinsFargateCluster"].id
  task_definition = aws_ecs_task_definition.cluster.arn
  desired_count = 1

  ordered_placement_strategy {
    type = "binpack"
    field = "cpu"
  }

  depends_on = [ 
    aws_ecs_task_definition.cluster
  ]

  lifecycle {
    ignore_changes = [task_definition]
  }
}

resource "aws_ecs_task_definition" "cluster" {
  count = var.ecs_cluster["JenkinsFargateCluster"].enabled ? 1 : 0

  family = "nginx"
  container_definitions = file("${path.module}/tasks/nginx.json")
}
```

However this gives another error.

│ Error: ECS Task Definition container_definitions is invalid: Error decoding JSON: json: cannot unmarshal object into Go value of type []*ecs.ContainerDefinition
│
│   with aws_ecs_task_definition.cluster,
│   on ecs.tf line 49, in resource "aws_ecs_task_definition" "cluster":
│   49:   container_definitions = file("${path.module}/tasks/nginx.json")

This seems to lineup with what is done in the documentation https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition

```
resource "aws_ecs_task_definition" "service" {
  family                = "service"
  container_definitions = file("task-definitions/service.json")
```

**Comment by trevorrea** [comment]
All that message means is that the file you're referencing is not a valid **container defintion**. It may a valid **task definition** but it's not a **container definition**. These are NOT the same thing. You need to go and review the docs for https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition and match up your code to what the documentation requires.

**Comment by snmason** [comment]
Thanks @trevorrea I was mistaken here, think I was starring at this for too long. Appreciate the help you guys provided. 

This can be closed.
