### ISSUE TITLE
Technical Debt: Fix deprecations in AWS Cost Explorer

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#30326]
### Description

The field `Threshold` from `costexplorer.AnomalySubscription` has been deprecated in favour of `ThresholdExpression`.

- [ ] Remove exclusion from `golanglint-ci` configuration (added by #30307)
- [ ] Add `//nolint` directive to uses of `Threshold`
- [x] Create issue to remove field `threshold` (#30325)

### Would you like to implement a fix?

None

**Comment by jar-b** [comment]
Closed by #30419 and the creation of #30325
