### ISSUE TITLE
[Bug]: Intermittent AWS provider failure when deploying aws_cloudwatch_metric_alarm

### ISSUE THREAD

**Issue by bankarsrahul552** [hashicorp/terraform-provider-aws#30344]
### Terraform Core Version

0.13.4

### AWS Provider Version

2.70.0

### Affected Resource(s)

Resource:
**aws_cloudwatch_metric_alarm**

_Error: Provider produced inconsistent result after apply When applying changes to_ _module.solr_cluster.module.master_ec2_instance_new.aws_cloudwatch_metric_alarm.EBS_75_Percent_Alert[0], provider_ _"registry.terraform.io/-/aws" produced an unexpected new value for was present, but now absent._

### Expected Behavior

Resource should get created in first go.

### Actual Behavior

**Getting intermittent issue** - _Provider produced inconsistent result. Root resource was present, now its absent._

_Error: Provider produced inconsistent result after apply When applying changes to_ _module.solr_cluster.module.master_ec2_instance_new.aws_cloudwatch_metric_alarm.EBS_75_Percent_Alert[0], provider_ _"registry.terraform.io/-/aws" produced an unexpected new value for was present, but now absent._

### Terraform Configuration Files

Below is the script calling terraform plan ::

```shell
function run_terraform(){
  # terraform plan -out=.execution_plan -refresh=false -detailed-exitcode $1 && rc=$? || rc=$?
  terraform plan -out=.execution_plan -detailed-exitcode $1 && rc=$? || rc=$?

  if [ $rc -eq 2 ]; then
    terraform apply --parallelism=5 .execution_plan
    run_terraform "$1"
  elif [ $rc -eq 1 ]; then
    exit 1;
  fi
}
```

### Steps to Reproduce

Run terraform plan.
If we get intermittent error - Retry the plan again and it should succeed.

### References

https://github.com/hashicorp/terraform-provider-aws/issues/21168

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @bankarsrahul552 👋 Thank you for taking the time to raise this! I noticed that you're using quite old versions of Terraform and the AWS provider. Are you able to test on more recent versions to verify if that resolves the issue?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
