### ISSUE TITLE
[Bug]: aws_cloudwatch_log_group invalid value for skip_destroy

### ISSUE THREAD

**Issue by grahamhar** [hashicorp/terraform-provider-aws#30353]
### Terraform Core Version

1.3.9,1.4.2

### AWS Provider Version

4.54.0,4.60.0

### Affected Resource(s)

aws_cloudwatch_log_group

### Expected Behavior

The plan/apply should have completed without error

### Actual Behavior

The apply errored following introduction of the attribute `skip_destroy`

### Relevant Error/Panic Output Snippet

```shell
│ aws_cloudwatch_log_group.log_group
    │ to include new values learned so far during apply, provider
    │ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
    │ .skip_destroy: was cty.False, but now null.
    │
    │ This is a bug in the provider, which should be reported in the provider's
    │ own issue tracker.
```

### Terraform Configuration Files

resource "aws_cloudwatch_log_group" "yada" {
  name         = "Yada"
  skip_destroy = var.skip
}

variable "skip" {
  type    = bool
  default = false
}

### Steps to Reproduce

We could not reproduce when trying the same configuration on a different stack.

### Would you like to implement a fix?

Yes

**Comment by SizZiKe** [comment]
@justinretzolk what's blocking this from being released?
