### ISSUE TITLE
[Docs]: Resource: aws_eks_node_group's update_config is not exist in Argument Reference

### ISSUE THREAD

**Issue by seungheeMa** [hashicorp/terraform-provider-aws#30368]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#update_config-configuration-block

### Description

aws_eks_node_group's update_config is not exist in Argument Reference
But, [update_config Configuration Block] (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#update_config-configuration-block)  is there.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @seungheeMa 👋 Thank you for taking the time to raise this! I've opened a pull request to add the `update_config` argument to the resource's documentation.
