### ISSUE TITLE
[Enhancement]: Improve the aws_autoscaling_policy.resource_label description and/or improve the resource arguments

### ISSUE THREAD

**Issue by speller** [hashicorp/terraform-provider-aws#30361]
### Description

The current description of the `aws_autoscaling_policy.resource_label` attribute says nothing about the value it expects. 
It would be nice to add an example and/or link to the official AWS documentation. It is a composition of a load balancer and target group ARNs. It will be super nice if the `aws_autoscaling_policy` resource will accept full ARNs and combine them into the `resource_label` value internally.

### Affected Resource(s) and/or Data Source(s)

- `aws_autoscaling_policy`

### Potential Terraform Configuration

In case of the resource arguments improvement:

```terraform
resource "aws_autoscaling_policy" "example" {
  policy_type = "TargetTrackingScaling"
  target_tracking_configuration {
    predefined_metric_specification {
      predefined_metric_type = "ALBRequestCountPerTarget"
      resource_label_arns {
        load_balancer_arn = "..."
        load_balancer_target_group_arn = "..."
      }
    }
    target_value = X
  }
}
```

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
The [AWS API reference](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_PredefinedMetricSpecification.html) provides a decent description and example for the resource label. I'll port some of the information to the resource doc along with a link reference and submit a PR.
