### ISSUE TITLE
[Bug]: Index brackets must contain either a literal number or a literal string while importing a module

### ISSUE THREAD

**Issue by cduddikunta** [hashicorp/terraform-provider-aws#30377]
### Terraform Core Version

1.2.9

### AWS Provider Version

0.13

### Affected Resource(s)

aws_organizations_account

### Expected Behavior

Successful import of the module

### Actual Behavior

```shell
terraform import module.test_aws_org.aws_organizations_account.account[\"test org\"] 111111111
╷
│ Error: Invalid character
│ 
│   on <import-address> line 1:
│    1: module.test_aws_org.aws_organizations_account.account[\"test org\"]
│ 
│ This character is not used within the language.
╵

╷
│ Error: Index value required
│ 
│   on <import-address> line 1:
│    1: module.test_aws_org.aws_organizations_account.account[\"test org\"]
│ 
│ Index brackets must contain either a literal number or a literal string.
╵
```

### Terraform Configuration Files

```terraform
locals{
  ous = {
      test = {
      name = "test"

      tags = {
        AccountType = "Production"
      }
    }
  }

  aws_accounts = {
    "Test org" = {
      email = "xxxxxx"
      ou    = local.ous.test.name
      tags  = local.ous.production.tags
    }
  }
}

module "test_aws_org" {
  source = "./modules/aws-org"

  providers = {
    aws = aws.test-central
  }

  aws_accounts = local.aws_accounts
}
```

### Steps to Reproduce

1. `terraform plan`
2.  `terraform import module.test_aws_org.aws_organizations_account.account[\"test org\"] 111111111`

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @cduddikunta 👋 Thank you for taking the time to raise this! This looks like it could be a couple of different things. The first thing I noticed is that you're using an identifier with a space in it (`"Test org"`), which is generally [not recommended](https://developer.hashicorp.com/terraform/language/resources/syntax#resource-syntax), and may outright not work at all, given the following note found on the linked page:

> Note: Resource names must start with a letter or underscore, and may contain only letters, digits, underscores, and dashes.

In addition to that, I'd be interested to know what operating system this is occurring on. Windows in particular has different ways of escaping quotes, so if you're on Windows, you may be running into something with that. I found a particularly helpful discussion around this on our [Discuss forum](https://discuss.hashicorp.com/t/cant-import-resources-with-map-values/42036/12).

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
