### ISSUE TITLE
[New Service]: VPC Lattice

### ISSUE THREAD

**Issue by bryantbiggs** [hashicorp/terraform-provider-aws#30380]
### Description

Support for recently announced VPC Lattice

- https://aws.amazon.com/blogs/aws/simplify-service-to-service-connectivity-security-and-monitoring-with-amazon-vpc-lattice-now-generally-available/
- https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonvpclatticeservices.html
- https://awscli.amazonaws.com/v2/documentation/api/latest/reference/vpc-lattice/index.html?highlight=lattice

### Requested Resource(s) and/or Data Source(s)

- [x] aws_vpclattice_service
- [x] aws_vpclattice_service_network
- [x] aws_vpclattice_service_network_service_association
- [x] aws_vpclattice_service_network_vpc_association
- [x] aws_vpclattice_listener
- [x] aws_vpclattice_listener_rule
- [x] aws_vpclattice_target_group
- [x] aws_vpclattice_access_log_subscription
- [x] [`aws_vpclattice_auth_policy`](https://docs.aws.amazon.com/cli/latest/reference/vpc-lattice/put-auth-policy.html)
- [x] [`aws_vpclattice_resource_policy`](https://docs.aws.amazon.com/cli/latest/reference/vpc-lattice/put-resource-policy.html)
- [x] [`aws_vpclattice_target_group_attachment`](https://docs.aws.amazon.com/cli/latest/reference/vpc-lattice/register-targets.html)

### Potential Terraform Configuration

```terraform
TBD
```

### References

- https://aws.amazon.com/blogs/aws/simplify-service-to-service-connectivity-security-and-monitoring-with-amazon-vpc-lattice-now-generally-available/
- https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonvpclatticeservices.html
- https://awscli.amazonaws.com/v2/documentation/api/latest/reference/vpc-lattice/index.html?highlight=lattice

### Would you like to implement a fix?

None

**Comment by mattburgess** [comment]
I'll take a look at what's required to implement this service. I'll likely create separate tickets for each resource so that progress is more easily tracked.

**Comment by mattburgess** [comment]
Potential order in which the various resources should be tackled based on their dependencies and workflow enablement:

* `aws_vpclattice_service`
* `aws_vpclattice_service_network`
* `aws_vpclattice_service_network_service_association`
  * Depends on `aws_vpclattice_service`
  * Depends on `aws_vpclattice_service_network`
* `aws_vpclattice_service_network_vpc_association`
  * Depends on `aws_vpclattice_service_network`
* `aws_vpclattice_listener`
  * Depends on `aws_vpclattice_service`
* `aws_vpclattice_target_group`
* `aws_vpclattice_rule`
  * Depends on `aws_vpclattice_listener`
  * Depends on `aws_vpclattice_target_group`
* `aws_vpclattice_access_log_subscription`
  * Depends on `aws_vpclattice_service_network`
  * Depends on `aws_vpclattice_service`

**Comment by mattburgess** [comment]
It looked as if it was a duplicate of this one. Is that incorrect? If not, then what does your ticket cover that this one doesn't?

**Comment by bryantbiggs** [comment]
@ewbankkit I believe we need two additional resources for the following - are the proposed names correct or should they be named something different?
1. [`aws_vpclattice_auth_policy_attachment`](https://docs.aws.amazon.com/cli/latest/reference/vpc-lattice/put-auth-policy.html)
2. [`aws_vpclattice_resource_policy_attachment`](https://docs.aws.amazon.com/cli/latest/reference/vpc-lattice/put-resource-policy.html)
3. [`aws_vpclattice_register_targets`](https://docs.aws.amazon.com/cli/latest/reference/vpc-lattice/register-targets.html)

**Comment by ewbankkit** [comment]
I suggest

* `aws_vpclattice_auth_policy`
* `aws_vpclattice_resource_policy`
* `aws_vpclattice_target_group_attachment` -- matches `aws_alb_target_group_attachment`

**Comment by bryantbiggs** [comment]
great work all - really appreciate your efforts, thank you!
