### ISSUE TITLE
[Bug]: AWS Organization - Cloud Trail Central - Delegated Administrator

### ISSUE THREAD

**Issue by jand0manski** [hashicorp/terraform-provider-aws#30387]
### Terraform Core Version

1.3.7

### AWS Provider Version

4.61.0

### Affected Resource(s)

aws_cloudtrail

### Expected Behavior

Cloud trail should correctly started & created in delegated administrator account .

### Actual Behavior

 Error: creating CloudTrail: starting logging: TrailNotFoundException: Unknown trail:

### Terraform Configuration Files

  + resource "aws_cloudtrail" "default" {
      cloud_watch_logs_group_arn    = "XXXX"
      + cloud_watch_logs_role_arn     = "XXXX"
      + enable_log_file_validation    = true
      + enable_logging                = true
      + include_global_service_events = true
      + is_multi_region_trail         = true
      + is_organization_trail         = true
      + kms_key_id                    = "XXXX"
      + name                          = "XXXX"
      + s3_bucket_name                = "XXXX"
    }

### Steps to Reproduce

1.Enable Cloud Trail trusted service in AWS Organization in master account
2.Delegate Administrator to member account
3.Create Cloud Trail in member account

### Would you like to implement a fix?

None

**Comment by dbadrak** [comment]
I can confirm this continues to be a problem in Terrafrom 1.5.6 with AWS provider v5.15.0:

```script
Error: creating CloudTrail: starting logging: TrailNotFoundException: Unknown trail: arn:aws:cloudtrail:us-east-1:123123123123:trail/org-cloudtrail for the user: 123123123123
```

where `123123123123` is the delegated CloudTrail Administrator account.  The trail **did** get created, in the organization master account as `arn:aws:cloudtrail:us-east-1:111111111111:trail/iorg-cloudtrail` where `111111111111` is the account of the organization master.
