### ISSUE TITLE
[Docs]: cloudwatch event target, cloudwatch log groups example missing principle

### ISSUE THREAD

**Issue by GusTheGray** [hashicorp/terraform-provider-aws#30388]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_target#cloudwatch-log-group-usage

### Description

In order for eventbridge to send logs to a log watch group, the iam policy must also include the principle       "delivery.logs.amazonaws.com". Without that principle, invocations of the rule will fail. 

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
Looks like this issue has been addressed by #31792 which was completed in v5.2.0, and thus can be closed.
