### ISSUE TITLE
[New Resource]: aws_vpclattice_service

### ISSUE THREAD

**Issue by mattburgess** [hashicorp/terraform-provider-aws#30408]
### Description

AWS VPC Lattice reached GA recently. A service within VPC Lattice is any independently deployable unit of software that delivers a specific task or function. A service can run on instances, containers, or as serverless functions within an account or a virtual private cloud (VPC).

### Requested Resource(s) and/or Data Source(s)

* aws_vpclattice_service

### Potential Terraform Configuration

```terraform
resource "aws_vpclattice_service" "example" {
  name      = "example-service"
  auth_type = "AWS_IAM"
  certificate_arn = "..."
  custom_domain_name = "test.example.com"
}
```

### References

* API Reference: https://docs.aws.amazon.com/vpc-lattice/latest/APIReference/API_CreateService.html
* API docs: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/vpclattice
* User Guide: https://docs.aws.amazon.com/vpc-lattice/latest/ug/

### Would you like to implement a fix?

Yes

**Comment by meetreks** [comment]
We are looking at this and will submit the PR ASAP

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/30380.
