### ISSUE TITLE
Terraform vpc-flowlog custom log_format is not accepting attributes  like "${version} ${account-id} ${interface-id}". If not define the log_format, it is taking default as  "${version} ${account-id}......."

### ISSUE THREAD

**Issue by atanudas100** [hashicorp/terraform-provider-aws#30412]
### Description

Creating vpc flowlog using terraform.. Below code is working fine with default log_format.
resource "aws_flow_log" "mod_s3" {
  
  log_destination      = "< s3 arn>"
  log_destination_type = "s3"
  traffic_type         = "ALL"
  vpc_id               = "<vpc id>" 
 
}

Using below code for custom log_format-- 
resource "aws_flow_log" "mod_s3" {
  
  log_destination      = "<s3 -arn>"
  log_destination_type = "s3"
  traffic_type         = "ALL"
  vpc_id               = "<vpc_id>"
  log_format ="${version} ${account-id} ${action} ${bytes} ${dstaddr} ${end} ${instance-id} ${interface-id} ${log-status} ${packets} ${pkt-dstaddr} ${pkt-srcaddr} ${protocol} ${region} ${srcaddr} ${srcport} ${dstport} ${start} ${vpc-id} ${subnet-id} ${tcp-flags}"

}

Its thronging error ----

│ Error: Invalid reference
│
│   on .terraform\modules\aws_vpc\tf-vpc\network\main.tf line 60, in resource "aws_flow_log" "mod_s3":
│   60:   log_format ="${version}"
│
│ A reference to a resource type must be followed by at least one attribute
│ access, specifying the resource name.

### Would you like to implement a fix?

None

**Comment by tylerwengerd-cr** [comment]
@atanudas100 when passing this format to AWS through Terraform, you have to use double `$` symbols. For example:

```hcl
resource "aws_flow_log" "mod_s3" {

  log_destination = "<s3 -arn>"
  log_destination_type = "s3"
  traffic_type = "ALL"
  vpc_id = "<vpc_id>"
  log_format ="$${version} $${account-id} [.....] $${tcp-flags}"
}
```

**Comment by atanudas100** [comment]
Thankyou @tylerwengerd-cr , this solution is working..
