### ISSUE TITLE
[New Resource]: aws_vpclattice_service_network_service_association

### ISSUE THREAD

**Issue by mattburgess** [hashicorp/terraform-provider-aws#30410]
### Description

AWS VPC Lattice recently reached GA. A Service Network Service Association allows a VPC Lattice Service Network to be associated with a VPC Lattice Service.

### Requested Resource(s) and/or Data Source(s)

* aws_vpclattice_service_network_service_association

### Potential Terraform Configuration

```terraform
resource "aws_vpclattice_service_network_service_association" "example" {
  service_identifier         = aws_vpclattice_service.example.id
  service_network_identifier = aws_vpclattice_service_network.example.id
}
```

### References

* API Reference: https://docs.aws.amazon.com/vpc-lattice/latest/APIReference/API_CreateServiceNetworkServiceAssociation.html
* API docs: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/vpclattice
* User Guide: https://docs.aws.amazon.com/vpc-lattice/latest/ug/

### Would you like to implement a fix?

None

**Comment by mschwrz** [comment]
@mattburgess Would like to give it a try

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/30380.
