### ISSUE TITLE
[New Resource]: aws_vpclattice_service_network_vpc_association 

### ISSUE THREAD

**Issue by mattburgess** [hashicorp/terraform-provider-aws#30411]
### Description

AWS VPC Lattice recently reached GA. A Service Network VPC Association allows a Service Network to be associated with a VPC. When you associate a VPC with the service network, it enables all the resources within that VPC to be clients and communicate with other services in the service network. 

### Requested Resource(s) and/or Data Source(s)

* aws_vpclattice_service_network_vpc_association

### Potential Terraform Configuration

```terraform
resource "aws_vpclattice_service_network_vpc_association" "example" {
  service_network_identifier = aws_vpclattice_service_network.example.id
  security_group_ids = [aws_security_group.example.id]
  vpc_identifier = aws_vpc.example.id
}
```

### References

* API Reference: https://docs.aws.amazon.com/vpc-lattice/latest/APIReference/API_CreateServiceNetworkVpcAssociation.html
* API docs: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/vpclattice
* User Guide: https://docs.aws.amazon.com/vpc-lattice/latest/ug/

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/30380.
