### ISSUE TITLE
[Enhancement]: Expose GuardDuty Organization configuration option AutoEnableOrganizationMembers

### ISSUE THREAD

**Issue by kevcube** [hashicorp/terraform-provider-aws#30428]
### Description

<img width="1729" alt="image" src="https://user-images.githubusercontent.com/716806/229628558-77d179fd-5e96-4685-80c8-d6cc6ecf6807.png">
source: https://docs.aws.amazon.com/guardduty/latest/ug/doc-history.html

### Affected Resource(s) and/or Data Source(s)

aws_guardduty_organization_configuration
aws_guardduty_member (maybe? see image for affected APIs)
aws_guardduty_detector (maybe?)

### Potential Terraform Configuration

```terraform
resource "aws_guardduty_organization_configuration" "example" {
  auto_enable_organization_members = true
}
```

### References

See Description

### Would you like to implement a fix?

No

**Comment by jar-b** [comment]
Closed by #30736, merged to `main` via #31392
