### ISSUE TITLE
[New Resource]: aws_vpclattice_target_group

### ISSUE THREAD

**Issue by markoskandylis** [hashicorp/terraform-provider-aws#30455]
### Description

AWS VPC Lattice reached GA recently. A target group is a collection of targets, or compute resources that run your application or service. Targets can be EC2 instances, IP addresses, Lambda functions, Application Load Balancers, or Kubernetes Pods. 

### Requested Resource(s) and/or Data Source(s)

aws_vpclattice_target_group

### Potential Terraform Configuration

```terraform
resource "aws_vpclattice_target_group" "this" {
  client_token = "[!-~]+"
  name         = "Example"
  type         = "IP/INSTANCE/ALB"

  config {
    ip_address_type  = "IPV4/IPV6"
    port             = 1 - 65535
    protocol         = "HTTP/HTTPS"
    protocol_version = "HTTP1/HTTP2/GRCP"
    vpc_identifier   = "^vpc-(([0-9a-z]{8})|([0-9a-z]{17}))$"

    health_check {
      enabled             = bool
      interval            = 0 - 300
      timeout             = 0 - 120
      healthy_threshold   = 0 - 10
      unhealthy_threshold = 0 - 10
      matcher             = "(^[0-9-,]+$|(^$))"
      path                = "(^/[a-zA-Z0-9@:%_+.~#?&/=-]*$|(^$))"
      port                = 0 - 65535
      protocol            = "HTTP/HTTPS"
      protocol_version    = "HTTP1/HTTP2"

    }
  }
}
```

### References

    API Reference: https://docs.aws.amazon.com/vpc-lattice/latest/APIReference/API_CreateTargetGroup.html
    API docs: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/vpclattice
    User Guide: https://docs.aws.amazon.com/vpc-lattice/latest/ug/

### Would you like to implement a fix?

Yes

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/30380.
