### ISSUE TITLE
[Bug]: Can't reference Root as orgunit In aws_fms_policy

### ISSUE THREAD

**Issue by kderck** [hashicorp/terraform-provider-aws#30465]
### Terraform Core Version

Terraform v1.4.2

### AWS Provider Version

4.59.0

### Affected Resource(s)

* aws_fms_policy

### Expected Behavior

I should be able to reference the root `ou`.

### Actual Behavior

```
│ Error: updating FMS Policy (ac93be09-2790-4d8f-9ca0-c845f6930d9c): InvalidInputException: Input ORG_UNIT map contains invalid IDs.
│ 
│   with aws_fms_policy.ingress,
│   on firewall_manager_application.tf line 1, in resource "aws_fms_policy" "ingress":
│    1: resource "aws_fms_policy" "ingress" {
```

### Relevant Error/Panic Output Snippet

```shell
N/A
```

### Terraform Configuration Files

N/A

### Steps to Reproduce

`terraform apply`

### Debug Output

N/A

### Panic Output

N/A

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @kderck 👋 Thank you for taking the time to raise this! So that we have the necessary information in order to look into this, can you supply a sample Terraform configuration that can be used to reproduce the issue, as well as debug logs (redacted as necessary)?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
