### ISSUE TITLE
Signing the CLA for contributions

### ISSUE THREAD

**Issue by cscacun** [hashicorp/terraform-provider-aws#30466]
### Description

@marcosentino I had a question about the CLA. 

This page (https://www.hashicorp.com/cla) mentions `Open a pull request ("PR") to any of our open source projects to sign the CLA. A bot will comment on the PR asking you to sign the CLA if you haven't already.`

However, I also found this - https://github.com/hashicorp/terraform-provider-aws/issues/14715 that says `After the repository transfer, the CLA functionality will be disabled for this repository. There are no current plans to enable the CLA requirement, however this may change in the future after the transfer and will be broadly announced.`

Could you please clarify which statement is correct ? I worked on this PR - https://github.com/hashicorp/terraform-provider-aws/pull/28928 - but there was no bot comment asking to sign the CLA. 

Thanks in advance for your help!

### Would you like to implement a fix?

None

**Comment by breathingdust** [comment]
Hi @cscacun 👋 and thanks for the contribution! At present the official Hashicorp maintained Terraform Providers repositories are exempt from the CLA process.
