### ISSUE TITLE
[New Resource]: aws_vpclattice_listener

### ISSUE THREAD

**Issue by mattburgess** [hashicorp/terraform-provider-aws#30494]
### Description

AWS VPC Lattice reached GA recently. A listener checks for connection requests, and routes them to targets in a target group. A service can have up to two listeners, using the HTTP and HTTPS protocols and port numbers from 1 to 65535.

### Requested Resource(s) and/or Data Source(s)

* aws_vpclattice_listener

### Potential Terraform Configuration

```terraform
resource "aws_vpclattice_listener" "example" {
   defaultAction { 
      fixedResponse { 
         statusCode = 200
      }

      forward { 
         targetGroup { 
            { 
               targetGroupIdentifier = "myTGID"
               weight = 1
            }
         }
      }
   }

   name     = "mytargetgroup"
   port     = 443
   protocol = "HTTPS"

   tags { 
      tag1 = "value1" 
   }
}
```

### References

* API Reference: https://docs.aws.amazon.com/vpc-lattice/latest/APIReference/API_CreateListener.html
* API docs: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/vpclattice
* User Guide: https://docs.aws.amazon.com/vpc-lattice/latest/ug/

### Would you like to implement a fix?

None

**Comment by mattburgess** [comment]
Relates #30380

**Comment by ddericco** [comment]
@mattburgess I can work on this unless you already have a WIP.

**Comment by ddericco** [comment]
This is being worked on.
