### ISSUE TITLE
aws_cognito_user_pool_client [Bug]: 

### ISSUE THREAD

**Issue by aloftaizzz** [hashicorp/terraform-provider-aws#30511]
### Terraform Core Version

Terraform v1.4.4

### AWS Provider Version

provider registry.terraform.io/hashicorp/aws v4.61.0

### Affected Resource(s)

when creating aws_cognito_user_pool_client

get the following error

╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to aws_cognito_user_pool_client.client, provider "provider["registry.terraform.io/hashicorp/aws"]" produced an unexpected new value: .write_attributes: was cty.SetValEmpty(cty.String), but now null.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵

### Expected Behavior

should create successfully

### Actual Behavior

gives bug error

╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to aws_cognito_user_pool_client.client, provider "provider["registry.terraform.io/hashicorp/aws"]" produced an unexpected new value: .write_attributes: was cty.SetValEmpty(cty.String), but now null.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵

### Terraform Configuration Files

resource "aws_cognito_user_pool_client" "client" {
  user_pool_id = aws_cognito_user_pool.user_pool.id
  access_token_validity = 1
  allowed_oauth_flows = ["code"]
  allowed_oauth_flows_user_pool_client = true
  allowed_oauth_scopes = ["email", "openid"]
  callback_urls = values(var.cognito_callback_urls)
  default_redirect_uri = var.cognito_callback_urls.aircontrol
  enable_propagate_additional_user_context_data = false
  enable_token_revocation = false
  explicit_auth_flows                  = [
    "ALLOW_CUSTOM_AUTH",
    "ALLOW_REFRESH_TOKEN_AUTH",
    "ALLOW_USER_PASSWORD_AUTH",
    "ALLOW_USER_SRP_AUTH",
  ]
  id_token_validity = 1
  logout_urls                          = values(var.cognito_logout_urls)
  name = local.user-pool.client_name
  read_attributes                      = ["email", "email_verified"]
  refresh_token_validity    = 30
  write_attributes = []
  token_validity_units  {
    access_token  = "days"
    id_token      = "days"
    refresh_token = "days"
  }

 lifecycle {
  ignore_changes = [ enable_token_revocation ]
  }

}

### Steps to Reproduce

after getting error, tried to terraform apply again,
same error msg

afterwards destroyed it
and terraform apply
same error

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@aloftaizzz Thanks for raising this issue.
It has already been noticed in #30257. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
