### ISSUE TITLE
[Bug]: Incorrect defaults for `aws_launch_template.metadata_options`

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#30519]
### Terraform Core Version

N/A

### AWS Provider Version

v.4.60.0

### Affected Resource(s)

aws_launch_template

### Expected Behavior

The default values for fields of the `metadata_options` block should be unspecified, rather than having a specified default. This allows the template  to not specify a value, which is the default condition.

### Actual Behavior

`metadata_options .http_protocol_ipv6` and `metadata_options.instance_metadata_tags` both have specified default values.

### Terraform Configuration Files

N/A

### Steps to Reproduce

N/A

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Relates:

* https://github.com/hashicorp/terraform-provider-aws/issues/29985
* https://github.com/hashicorp/terraform-provider-aws/issues/25227
* https://github.com/hashicorp/terraform-provider-aws/issues/25079
* https://github.com/hashicorp/terraform-provider-aws/issues/12564
