### ISSUE TITLE
[Bug]: Destroying aws_codebuild_webhook does not delete the webhook on GitHub's side

### ISSUE THREAD

**Issue by victorchurikovcommonground** [hashicorp/terraform-provider-aws#30551]
### Terraform Core Version

1.4.2

### AWS Provider Version

4.59.0

### Affected Resource(s)

aws_codebuild_webhook

### Expected Behavior

Expected one of the two following behaviors:

1. The webhooks created by aws_codebuild_webhook on GitHub should have been deleted from https://github.com/org/repo/settings/hooks on terraform destroy of the resource
2. If webhook deletion is not possible for any reason then I expect the resource deletion to wait until the hook is deleted manually and fail with time out after a few minutes if it still exists. That way I can run custom scripts to handle deletion myself

### Actual Behavior

The webhooks created by aws_codebuild_webhook on GitHub have not been deleted from https://github.com/org/repo/settings/hooks and continue to occupy part of the 20 webhooks per repository quota of GitHub, eventually leading to webhook limit reached errors. This is especially problematic for testing environments that get recreated frequently

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: creating CodeBuild Webhook: OAuthProviderException: Failed to create webhook. GitHub webhook limit reached. Please delete a webhook from this repository.
│
│   with module.lambda-call-athena.module.sync_lambda_code_from_git.aws_codebuild_webhook.this,
│   on ../modules/codebuild/main.tf line 81, in resource "aws_codebuild_webhook" "this":
│   81: resource "aws_codebuild_webhook" "this" {
│
╵
```

### Terraform Configuration Files

```terraform
locals {
  filepath_filter_enabled = var.filepath_filter_pattern != null ? [1] : []
}

...

resource "aws_codebuild_source_credential" "this" {
  provider    = aws.env
  auth_type   = "PERSONAL_ACCESS_TOKEN"
  server_type = var.server_type
  token       = var.git_token
}

resource "aws_codebuild_webhook" "this" {
  provider     = aws.env
  project_name = aws_codebuild_project.this.name
  build_type   = "BUILD"
  filter_group {
    filter {
      type    = "EVENT"
      pattern = "PUSH"
    }

    filter {
      type    = "HEAD_REF"
      pattern = "master"
    }

    dynamic "filter" {
      for_each = local.filepath_filter_enabled
      content {
        type    = "FILE_PATH"
        pattern = var.filepath_filter_pattern
      }
    }
  }
}
```

### Steps to Reproduce

1. Create aws_codebuild_webhook resource
2. Destroy the resource
3. Observe that the webhook related to the resource still exists on GitHub

### Important Factoids

GitHub classic access token is used with "repo" scope, and adding "admin:repo_hook" scope did not help

### Would you like to implement a fix?

No

**Comment by victorchurikovcommonground** [comment]
If this is not possible due to limitations on AWS side, I found that **codepipeline** has better support for this: https://docs.aws.amazon.com/cli/latest/reference/codepipeline/deregister-webhook-with-third-party.html

So wrapping the codebuild job in a codepipeline should achieve the same effect but with better support for webhooks that allows deregistering them before deletion. Although I may end up doing that, I think it's worth mentioning in the docs or adding an option like wait_for_deregister so people can implement their own deletions

**Comment by Jitensid** [comment]
I am also exactly facing the same issue @victorchurikovcommonground

**Comment by justinretzolk** [comment]
Hey @victorchurikovcommonground 👋 It looks like you're using a personal access token to handle the authentication between CodeBuild and GitHub. Based on the following note from the `aws_codebuild_webhook` documentation, I believe this may be your issue, and that you may need to set up an OAuth connection (manually, in the console) before the management of webhooks can happen automatically on resource creation/destruction.

> The AWS account that Terraform uses to create this resource must have authorized CodeBuild to access Bitbucket/GitHub's OAuth API in each applicable region. This is a manual step that must be done before creating webhooks with this resource. If OAuth is not configured, AWS will return an error similar to `ResourceNotFoundException: Could not find access token for server type github`. More information can be found in the CodeBuild User Guide for [Bitbucket](https://docs.aws.amazon.com/codebuild/latest/userguide/sample-bitbucket-pull-request.html) and [GitHub](https://docs.aws.amazon.com/codebuild/latest/userguide/sample-github-pull-request.html).

**Comment by victorchurikovcommonground** [comment]
My PAT has the repo and admin:repo_hook read/write OAuth scopes, and the user it was created from has admin access to the github private repository. Github webhook creation was successful with aws_codebuild_source_credential using the PAT, so I was expecting that it would be able also delete the webhooks as well. I did not get the error you mentioned.

After reading your answer, some docs and forum posts on aws repost, I understand that when working with GitHub, aws codebuild credentials should be configured manually from UI due to limitations of codebuild's API. My use case requires this to be fully automated so I will unfortunately have to look for other solutions in that case.

The better solution will be to wrap the codebuild job in a codepipeline and trigger the pipeline instead, I can see from the terraform docs for aws_codepipeline_webhook that we can create the github_repository_webhook ourselves and have codepipeline use it. That way we can also delete it ourselves with terraform destroy. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codepipeline_webhook


Since this is a limitation of AWS codebuild API and there is nothing terraform provider's maintainers can do about it, I am closing this issue. Thanks
