### ISSUE TITLE
[Bug]: cannot set snapshot description lifecycle management policy

### ISSUE THREAD

**Issue by schollii** [hashicorp/terraform-provider-aws#30604]
### Terraform Core Version

1.4.1

### AWS Provider Version

4.58

### Affected Resource(s)

aws_dlm_lifecycle_policy

### Expected Behavior

There should be an argument available in the aws_dlm_lifecycle_policy to set the description of snapshots created by the policy, using $(instance-id) and such. 

### Actual Behavior

There is no way of setting the description, AFAICT. 

### Terraform Configuration Files

n/a

### Steps to Reproduce

n/a

### Important Factoids

Actually I wonder if this should be a feature request... I'm not even sure that AWS DLM policy supports setting this description, I think it is not configurable

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @schollii 👋 Thank you for taking the time to raise this! The `aws_dlm_lifecycle_policy` resource ultimately relies on the [`CreateLifecyclePolicy`](https://docs.aws.amazon.com/dlm/latest/APIReference/API_CreateLifecyclePolicy.html) action from the DLM API. Based on the linked document, it doesn't appear that this is something that's possible at the moment without changes on the AWS side.

**Comment by schollii** [comment]
@justinretzolk Ah ok thanks. Where the best place to post a request for this?

**Comment by justinretzolk** [comment]
@schollii 👋 For that type of request, you'd need to file a ticket with AWS to request that the feature be added, then added to the SDK, at which point we could build the functionality into the provider. If I've missed something, and this functionality exists within AWS today, I'd be happy to take another look around!

**Comment by schollii** [comment]
BTW I found out later that "variable tags" are supported by aws provider. It is not as versatile as setting the snapshot name, but at least the DLM automatically sets tag with the instance ID that the snapshot was created from. I would have preferred the instance Name, but an ec2 instance does not propagate such tag to its volumes so although copy from source = true in the policy, the instance name is lost. 

I'll make a feature request but you can close this if you want.
