### ISSUE TITLE
[Bug]: S3 Bucket Replication Configuration Race Condition

### ISSUE THREAD

**Issue by edwardofclt** [hashicorp/terraform-provider-aws#30646]
### Terraform Core Version

1.3.2

### AWS Provider Version

4.6.2

### Affected Resource(s)

* aws_s3_bucket_replication_configuration

### Expected Behavior

The S3 bucket replication policy should be created and a retry should be implemented should AWS not return the policy immediately after creation.

### Actual Behavior

The S3 bucket replication policy is created and when the provider goes to read the policy at the end of the create method, the policy is not available yet which results in an errored state.

### Relevant Error/Panic Output Snippet

```shell
Error: getting S3 Bucket Replication Configuration for bucket (random-bucket-name): ReplicationConfigurationNotFoundError: The replication configuration was not found
│ 	status code: 404, request id: APR4SP3F92X1TNG3, host id: YpXLH4D6+2AUZR25Q+hbFrB0Npo75lHgEd+7lJ6h6P1gUHycH1GONSUomi3FNrlTfYneNaOVUhqcySL/3sbMLIWe77FOrqHzpB2MPmsCZiU=
│ 
│   with aws_s3_bucket_replication_configuration.replication,
│   on 5c35114c-8473-4778-b08d-d46f1edd0b4d.tf.json line 294, in resource.aws_s3_bucket_replication_configuration.replication:
│  294:       }
```

### Terraform Configuration Files

```json
"aws_s3_bucket_replication_configuration": {
  "replication": {
    "depends_on": [
      "aws_s3_bucket_versioning.source",
      "aws_s3_bucket_versioning.destination"
    ],
    "role": "${aws_iam_role.replication.arn}",
    "bucket": "${aws_s3_bucket.root.id}",
    "rule": [
      {
        "id": "volt",
        "filter": null,
        "status": "Enabled",
        "destination": [
          {
            "bucket": "${aws_s3_bucket.replica.arn}",
            "storage_class": "STANDARD"
          }
        ]
      }
    ]
  }
}
```

### Steps to Reproduce

Happens intermittently by just running the Terraform with a new replication config 

### Would you like to implement a fix?

Yes

**Comment by edwardofclt** [comment]
> Any workarounds for this issue? 

I don't think there is one based on how the logic is written. I'm going to take a swing at a fix this weekend.

**Comment by shaileshaag** [comment]
Most of our Terraform builds are stuck due to this.

**Comment by edwardofclt** [comment]
> Most of our Terraform builds are stuck due to this.

@shaileshaag you and your associates should give a review and a 👍 to the PR I submitted to bring more attention to the issue.
