### ISSUE TITLE
Terraform EKS Cluster security group deletion fails says it associated to ENI  

### ISSUE THREAD

**Issue by rama-vmw** [hashicorp/terraform-provider-aws#30640]
### Terraform Core Version

1.3.9

### AWS Provider Version

4.52.0

### Affected Resource(s)

aws_eks_cluster

created cluster using below code
|

```terraform
resource "aws_eks_cluster" "eks" {
  name    = var.cluster_name
  version = var.cluster_version

  **role_arn= var.cluster_iam_role_arn**
  enabled_cluster_log_types=var.cluster_enabled_log_types

  vpc_config {
    subnet_ids=aws_subnet.private_subnets_controlplane.*.id
    endpoint_private_access=true
    endpoint_public_access=true
  }
  tags = local.tags

  kubernetes_network_config {
    ip_family = "ipv4"
    service_ipv4_cidr = "172.20.0.0/16"
  }

  depends_on = [
    aws_subnet.private_subnets_controlplane // creating in same cluster.tf file before creating cluster
  ]
}
```

cluster_iam_role_arn ,I am taking it as input because it is already created by previous module while creating vpc.
Hence I am using it as input. 

During terraform destroy , the destroy fails **sometimes**.  And it gives the below error.

```shell
DependencyViolation: The subnet 'subnet-0bb3ce3216373269b' has dependencies and cannot be deleted.]
```

I read on of the closed bugs that role_attachment has to be given in depends_on field,Since that roles is coming from already executed model hence i don't think that can be a issue here. 
Please suggest what is the wrong I am doing. 

### Expected Behavior

EKS cluster should get deleted along with security group and the subnet

### Actual Behavior

EKS Cluster is deleted but this security group is not deleted and gives error that it can not delete the subnet in the logs 
[
<img width="1728" alt="Screenshot 2023-04-11 at 6 38 37 PM copy" src="https://user-images.githubusercontent.com/79302008/231173367-fa4fd8b5-3d10-4ff4-8d1a-31f019ed25cc.png">
](url)

### Relevant Error/Panic Output Snippet

```shell
{"@timestamp":"2023-04-11T09:33:59.871Z","@version":"1","message":"Terraform [cluster] [642e6e6447f19512f096eb22] [Error] [\u001B[31m\u001B[0m \u001B[0m\u001B[1m\u001B[31mError: \u001B[0m\u001B[0m\u001B[1m
deleting EC2 Subnet (subnet-0bb3ce3216373269b): DependencyViolation: The subnet 'subnet-0bb3ce3216373269b' has dependencies and cannot be deleted.]","logger_name":"com.*.terraform.TerraformClient","thread_name":"pool-10-thread-1","level":"INFO","level_value":20000}
{"@timestamp":"2023-04-11T09:33:59.873Z","@version":"1","message":"Terraform [cluster] [642e6e6447f19512f096eb22] [Error] [\u001B[31m\u001B[0m \u001B[0m\tstatus code: 400, request id: 9c1d3241-0b1b-436e-8d60-8d1b9e9de0ee
```

### Terraform Configuration Files

```terraform
resource "aws_eks_cluster" "eks" {
  name    = var.cluster_name
  version = var.cluster_version

  role_arn= var.cluster_iam_role_arn
  enabled_cluster_log_types=var.cluster_enabled_log_types

  vpc_config {
    subnet_ids=aws_subnet.private_subnets_controlplane.*.id
    endpoint_private_access=true
    endpoint_public_access=true
  }
  tags = local.tags

  kubernetes_network_config {
    ip_family = "ipv4"
    service_ipv4_cidr = "172.20.0.0/16"
  }

  depends_on = [
    aws_subnet.private_subnets_controlplane
  ]
}
```

### Steps to Reproduce

 create cluster using terraform 
 
```terraform
resource "aws_eks_cluster" "eks" {
  name    = var.cluster_name
  version = var.cluster_version

  role_arn= var.cluster_iam_role_arn
  enabled_cluster_log_types=var.cluster_enabled_log_types

  vpc_config {
    subnet_ids=aws_subnet.private_subnets_controlplane.*.id
    endpoint_private_access=true
    endpoint_public_access=true
  }
  tags = local.tags

  kubernetes_network_config {
    ip_family = "ipv4"
    service_ipv4_cidr = "172.20.0.0/16"
  }

  depends_on = [
    aws_subnet.private_subnets_controlplane
  ]
}
```

### Would you like to implement a fix?

None

**Comment by rama-vmw** [comment]
I am still waiting for a solution here.

**Comment by rama-vmw** [comment]
any help will be appreciated.

**Comment by ksubileau** [comment]
We are experiencing a similar issue since we upgraded Terraform core from `1.5.7` to `1.8.2` and AWS provider from `5.19.0` to `5.47.0` 3 weeks ago. Sometimes the destruction process gets stuck when trying to destroy some resources still in use by an ENI.

```
aws_security_group.a: Still destroying... [id=sg-xxxx, 14m50s elapsed]
aws_security_group.b: Still destroying... [id=sg-xxxx, 14m50s elapsed]
aws_security_group.c: Still destroying... [id=sg-xxxx, 15m0s elapsed]
aws_security_group.d: Still destroying... [id=sg-xxxx, 15m0s elapsed]
aws_security_group.e: Still destroying... [id=sg-xxxx, 15m0s elapsed]
aws_subnet.internal: Still destroying... [id=subnet-xxxx, 15m0s elapsed]
aws_security_group.a: Still destroying... [id=sg-xxxx, 15m0s elapsed]
```

Until it finally times out and throws errors : 
```
 Error: deleting Security Group (sg-xxxx): DependencyViolation: resource sg-xxxx has a dependent object
 status code: 400, request id: xxxx
```

We noticed that the security groups concerned are attached to an ENI which was used by one of the EKS nodes from the managed node pool, but which is not deleted, while all the rest of the cluster is indeed deleted. This ENI appears in the "Available" status in the AWS console.

If we manually delete this ENI, the destruction process is unblocked and continues instantly.

**Comment by bryantbiggs** [comment]
please see https://github.com/hashicorp/terraform-provider-aws/issues/38887 - this is not the responsibility of Terraform but instead of the AWS VPC CNI. To help remediate this issue, I suggest setting `preserve = true` for the AWS VPC CNI addon so that it is not removed too early in the cluster destroy process and allows it time to clean up the ENIs that it has created

**Comment by justinretzolk** [comment]
With the above in mind, closing.
