### ISSUE TITLE
r/aws_ssmincidents_replication_set: Remove custom tag update code

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#30647]
If the solution to https://github.com/hashicorp/terraform-provider-aws/issues/29747 allows empty tag values to be handled correctly, remove the custom `tags` update code from the `aws_ssmincidents_replication_set` resource.

Relates: https://github.com/hashicorp/terraform-provider-aws/pull/30639.
Relates: https://github.com/hashicorp/terraform-provider-aws/issues/24449.

**Comment by jar-b** [comment]
Closed by #31262, merged to `main` via #31392
