### ISSUE TITLE
[New Data Source]:  AWS Organization OU (aws_organizations_ou) 

### ISSUE THREAD

**Issue by rnikoopour** [hashicorp/terraform-provider-aws#30657]
### Description

There is no data source to reference an OU.  The only thing that currently exists is `aws_organizations_organizational_units` which retrieves all units for a given parent.  This requires the user to parse this to find the OU they are looking for.

### Requested Resource(s) and/or Data Source(s)

* aws_ogranizations_ou

### Potential Terraform Configuration

```terraform
data "aws_organizations_ou" "my_ou" {
    parent_id = "ou-1235467890"
    name = "my_ou"
}
```

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@rnikoopour Thanks for raising this issue.
It has already been noticed in #22909. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
