### ISSUE TITLE
[Docs]: VPC IPAM pool default suggests public range 172.2.0.0/16

### ISSUE THREAD

**Issue by fe-ax** [hashicorp/terraform-provider-aws#30675]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_ipam_pool
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc

(all VPC related docs)

### Description

The example range is 172.2.0.0/16. This is a public IP range, and how it's written could give the impression that this is a private address. The actual private range is 172.16.0.0/12.

Suggesting to change this to 172.20.0.0/16 and 172.20.0.0/24

### References

https://www.arin.net/reference/research/statistics/address_filters/

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @fe-ax 👋 Thank you for taking the time to raise this! I've opened a pull request to update these (and and a few other) documents to use a private range instead. Nice catch! Thanks for helping us to keep improving the documentation around the provider 🚀
