### ISSUE TITLE
Tech debt: Deprecate data source `tags_all` attributes

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#30710]
Data sources should not have a `tags_all` attribute.
A couple do:

* `aws_quicksight_data_set`
* `aws_service_discovery_service`

Deprecate and then remove these.
Add a _semgrep_ rule to prevent future cases.

**Comment by johnsonaj** [comment]
Closed in #31162. Merged to `main` in #31392
