### ISSUE TITLE
[Repo]: Missing v4.63.0 Release for Linux AMD64 through the API

### ISSUE THREAD

**Issue by Miroka96** [hashicorp/terraform-provider-aws#30729]
### Description

We are using Renovate for updating Terraform lockfiles, but Renovate cannot get the latest information from the following URL because it returns HTTP 404:
https://registry.terraform.io/v1/providers/hashicorp/aws/4.63.0/download/linux/amd64

Similar URLs work completely fine, e.g.:
https://registry.terraform.io/v1/providers/hashicorp/aws/4.63.0/download/linux/arm64
https://registry.terraform.io/v1/providers/hashicorp/aws/4.62.0/download/linux/amd64

Did something in the release script fail?

### Would you like to implement a fix?

No

**Comment by tgagor** [comment]
We use Artifactory to cache providers downloads (via `.terraformrc` config) and since the release of v4.63.0 we experience same issue. All our Terraform builds fail, with information that Terraform can't download for our architecture. v4.62.0 works fine and is our current workaround.

**Comment by tgagor** [comment]
Looks like today it's fixed and working fine again (at least for us).

**Comment by Miroka96** [comment]
The URL still returns HTTP 404

**Comment by justinretzolk** [comment]
Hey @Miroka96 👋 Thank you for taking the time to raise this! I'm not able to reproduce this. Can you test again and see if you're still running into the same issue?

**Comment by Miroka96** [comment]
The URL no longer returns HTTP 404. Thank you!
