### ISSUE TITLE
[Bug]: AWS Autoscaling Group actions fail in terraform due to historic failures in the ASG activity history.

### ISSUE THREAD

**Issue by n00borama** [hashicorp/terraform-provider-aws#30740]
### Terraform Core Version

1.3.5

### AWS Provider Version

4.63.0

### Affected Resource(s)

aws_autoscaling_group

### Expected Behavior

Terraform should execute ASG changes without failure as all the inputs are correct and the ASG does do the required actions in AWS.

### Actual Behavior

Terraform fails out, repeating an old failure message from the activity history even though AWS carries on correctly.

### Relevant Error/Panic Output Snippet

Failure1 - looking for an AMI which is correct in the launch template but has an activity history failure as below, which repeats the failure message every apply.
```
 activity (91561c38-8191-6d4a-2632-a17aa83d46ef): Failed: The image id '[ami-035c9fa6970e65e0c]' does not exist. Launching EC2 instance failed.
```

Failure2 - Previous failure due to CPU limits in history, then all future interactions with ASG repeat the error and fail terraform.

```
Error: waiting for Auto Scaling Group (name) capacity satisfied: 3 errors occurred:
	* Scaling activity (fcb61bd0-ad30-1cd3-305a-e0fd43baae55): Failed: You have requested more vCPU capacity than your current vCPU limit of 640 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit. Launching EC2 instance failed.
	* Scaling activity (a2361bd0-ac93-c0dd-fb59-f81541c2c2c3): Failed: You have requested more vCPU capacity than your current vCPU limit of 640 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit. Launching EC2 instance failed.
	* Scaling activity (64e61bd0-a91a-40c0-aa3a-d0c409874acb): Failed: You have requested more vCPU capacity than your current vCPU limit of 640 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit. Launching EC2 instance failed.
```

### Terraform Configuration Files

Any ASG configuration.

### Steps to Reproduce

1. Create an ASG successfully.
2. Create a failure scenario such as a missing AMI from a launch template.
3. Execute terraform to get the ASG to fail with the missing AMI. Check that the failure is in activity history.
4. Update the launch template to reference an existing AMI.
5. Exeucte terraform again and see if it incorrectly fails with the same error event from the previous failure.

### Important Factoids

We've seen this on three systems out of many more so not sure how it comes about.
It seems to be randomly scanning activity history looking for failures to report back and fail out terraform, but it's finding historic ones from up to 30days ago.

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@n00borama Thanks for raising this issue.
It has already been noticed in #26377. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
