### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by ralphfrederick** [hashicorp/terraform-provider-aws#30748]
### Description

Consolidated Control Findings and Consolidated Controls View for AWS Security Hub were released on February 24th 2023, so support for all those new APIs and features would be nice to have in the AWS provider.  https://aws.amazon.com/about-aws/whats-new/2023/02/aws-security-hub-consolidated-control-findings-view/

For my use case, I would like to be able to create custom Security Hub Insights filters based on new fields (e.g. ComplianceAssociatedStandardsId).  I assume this will require updates to allowed values in filters for aws_securityhub_insight
https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_AwsSecurityFindingFilters.html
https://docs.aws.amazon.com/securityhub/latest/userguide/asff-changes-consolidation.html

Other users will probably want to be able to turn consolidated findings on or off via terraform for new aws_securityhub_account:
https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_EnableSecurityHub.html
https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_UpdateSecurityHubConfiguration.html

It is unclear to me if the new "batch" APIs for managing security controls across standards will require updates to aws_securityhub_standards_control or not. 

### Affected Resource(s) and/or Data Source(s)

aws_securityhub_insight
aws_securityhub_account
aws_securityhub_organization_configuration
aws_securityhub_standards_control

### Potential Terraform Configuration

```terraform
resource "aws_securityhub_account" "example" {}

resource "aws_securityhub_insight" "example" {

  name = "Summary- Failed CIS v1.4 practices findings by severity"

  filters {
    workflow_status {
      comparison = "NOT_EQUALS"
      value      = "SUPPRESSED"
    }

    record_state {
      comparison = "EQUALS"
      value      = "ACTIVE"

    }

    ComplianceAssociatedStandardsId {
      value      = "standards/cis-aws-foundations-benchmark/v/1.4.0"
      comparison = "EQUALS"
    }

  }

  group_by_attribute = "ComplianceStatus"

}
```

### References

https://aws.amazon.com/about-aws/whats-new/2023/02/aws-security-hub-consolidated-control-findings-view/
https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_AwsSecurityFindingFilters.html
https://docs.aws.amazon.com/securityhub/latest/userguide/asff-changes-consolidation.html
https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_EnableSecurityHub.html
https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_UpdateSecurityHubConfiguration.html
https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_BatchUpdateStandardsControlAssociations.html

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Similar: https://github.com/hashicorp/terraform-provider-aws/issues/30022.
