### ISSUE TITLE
[Enhancement]: add missing attributes to aws_outposts_outpost datasource

### ISSUE THREAD

**Issue by FireballDWF** [hashicorp/terraform-provider-aws#30753]
### Description

Add the attributes missing from the aws_outposts_outpost datasource that are available in the API:

1. [SupportedHardwareType](https://docs.aws.amazon.com/outposts/latest/APIReference/API_Outpost.html#outposts-Type-Outpost-SupportedHardwareType)  is the one that is driving my request
2. [LifeCycleStatus](https://docs.aws.amazon.com/outposts/latest/APIReference/API_Outpost.html#outposts-Type-Outpost-LifeCycleStatus)
3. [SiteArn](https://docs.aws.amazon.com/outposts/latest/APIReference/API_Outpost.html#outposts-Type-Outpost-SiteArn)
4. [Tags](https://docs.aws.amazon.com/outposts/latest/APIReference/API_Outpost.html#outposts-Type-Outpost-Tags)

### Affected Resource(s) and/or Data Source(s)

* aws_outposts_outpost

### References

https://docs.aws.amazon.com/outposts/latest/APIReference/API_GetOutpost.html

### Would you like to implement a fix?

No

**Comment by silvaalbert** [comment]
I will be actively working on this.
