### ISSUE TITLE
[Bug]: Inconsistent final plan with tags_all when using apply time values as resource tags

### ISSUE THREAD

**Issue by ryancausey** [hashicorp/terraform-provider-aws#30756]
### Terraform Core Version

v1.3.9

### AWS Provider Version

v4.63.0

### Affected Resource(s)

* aws_vpc

### Expected Behavior

The final plan should have been consistent and applied correctly.

### Actual Behavior

An error occurred where the apply step failed with an error that the AWS provider produced an inconsistent final plan.

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for aws_vpc.main to include new values learned so
│ far during apply, provider "registry.terraform.io/hashicorp/aws" produced
│ an invalid new value for .tags_all: new element "name" has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
```

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.63.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "3.5.1"
    }
  }
}

provider "aws" {
  region = "us-west-2"

  # Always tag these resourcew as terraform managed and with the envrironment info.
  default_tags {
    tags = {
      group_name        = "test"
      project_name      = "test-vpc-resources"
      terraform_managed = "true"
      environment_name  = "test_env"
      release_version   = "0.0.1"
      deployed_by       = "test_person"
    }
  }
}

# Produce a unique random name. This is mainly to support review apps in GitLab.
resource "random_id" "main_vpc_name" {
  byte_length = 8
  prefix      = "main"
}

# The VPC to instantiate.
resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"

  tags = { name = random_id.main_vpc_name.dec }
}
```

### Steps to Reproduce

1. configure AWS credentials needed to apply the VPC resources.
2. run `terraform init` using the minimal reproduction sample provided.
3. run `terraform plan -out plan.tfplan`.
4. run `terraform apply plan.tfplan

### Important Factoids

Workaround: re-planning and then applying the new plan seems to make the inconsistency error go away. Likely because the random resource would have been applied and the new plan could take its resulting value into account at plan time.

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@ryancausey Thanks for raising this issue.
It has already been noticed in #19583. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
