### ISSUE TITLE
[Enhancement]: add enableLniAtDeviceIndex attribute to aws_subnet datasource

### ISSUE THREAD

**Issue by FireballDWF** [hashicorp/terraform-provider-aws#30779]
### Description

Add the enableLniAtDeviceIndex attribute to the aws_subnet datasource

### Affected Resource(s) and/or Data Source(s)

* aws_subnet

### References

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Subnet.html

### Would you like to implement a fix?

No

**Comment by silvaalbert** [comment]
I am working on implementing a fix.
