### ISSUE TITLE
Category name for aws_ec2_transit_gateway_route_table_association resource has been changed from 4.10.0v onwards

### ISSUE THREAD

**Issue by Shivani2203** [hashicorp/terraform-provider-aws#30792]
### Description

In the terraform documentation of 'aws_ec2_transit_gateway_route_table_association' resource, previously category of this resource was "EC2", but from 4.10.0v onwards Terraform categorizes this resource under "Transit Gateway".

Wanted to know the reason for the change in category of this resource from EC2 to Transit Gateway

### References

Terraform Provider version 4.9.0
https://registry.terraform.io/providers/hashicorp/aws/4.9.0/docs/resources/ec2_transit_gateway_route_table_association

Terraform Provider version 4.10.0
https://registry.terraform.io/providers/hashicorp/aws/4.10.0/docs/resources/ec2_transit_gateway_route_table_association

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @Shivani2203 👋 Thank you for taking the time to raise this! This happened with #24158 as part of a larger effort to split up the EC2 resources into subcategories to make navigating the EC2 section of the documentation a bit more manageable (since there are so many EC2-related resources).

**Comment by Shivani2203** [comment]
Since the question is answered , I am closing the issue.
