### ISSUE TITLE
[Docs]: vpc_identifier inccorectly referering  aws_vpclattice_service ID

### ISSUE THREAD

**Issue by pravinbhande** [hashicorp/terraform-provider-aws#30791]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpclattice_service_network_vpc_association

### Description

VPC_identified displayed in the example "aws_vpclattice_service_network_vpc_association" block in this documentation link refering to "aws_vpclattice_service" resource ID instead of "aws_vpc" resource ID

Existig Block :-
resource "aws_vpclattice_service_network_vpc_association" "example" {
  vpc_identifier             = aws_vpclattice_service.example.id
  service_network_identifier = aws_vpclattice_service_network.example.id
  security_group_ids         = [aws_security_group.example.id]
}

Incorrect Portion  : - 
  vpc_identifier             = **_aws_vpclattice_service_**.example.id

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpclattice_service_network_vpc_association

### Would you like to implement a fix?

Yes

**Comment by bryantbiggs** [comment]
closed in #30796 FYI
