### ISSUE TITLE
[Docs]: aws_mq_broker configuration block says it only supports ActiveMQ, but aws_mq_broker_configuration states that engine_type can be either ActiveMQ or RabbitMQ

### ISSUE THREAD

**Issue by lognarly** [hashicorp/terraform-provider-aws#30797]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mq_broker#configuration

### Description

In the docs for `aws_mq_broker`, the `configuration` [block](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mq_broker#configuration) says it only supports engine_type of "ActiveMQ". However, in the `aws_mq_broker_configuration` [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mq_configuration#engine_type), it references that `engine_type` can be either "ActiveMQ" or "RabbitMQ". Testing the resources, I do get failures when trying to use `aws_mq_broker_configuration` with "RabbitMQ", so I am curious if the docs for that resource should be updated? Or is only referencing this configuration in the `aws_mq_broker` resource available for "ActiveMQ", but the configuration object can still be created for either engine type?

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @lognarly 👋 Thank you for taking the time to raise this! I took a look, and these two resources use two different functions under the hood -- `aws_mq_broker` uses [`CreateBroker`](https://docs.aws.amazon.com/amazon-mq/latest/api-reference/brokers.html), while `aws_mq_configuration` uses [`CreateConfiguration`](https://docs.aws.amazon.com/amazon-mq/latest/api-reference/configurations.html). Both of these operations are relevant to both ActiveMQ and RabbitMQ, however, there are some limitations. One such limitation is the `configuration` block of `aws_mq_broke` / `CreateBroker`, which is only relevant to ActiveMQ. Similarly, there's some limitations on the configurable authentication strategy for `aws_mq_configuration` resources based on the engine type specified.

Based on what I've found, I'm not sure that the documentation needs updating at this point, but if you have points that you think could be more clear, we're always open to feedback!

**Comment by SignalWhisperer** [comment]
Hi, Amazon MQ just released configuration support for RabbitMQ brokers. [See the launch announcement.](https://aws.amazon.com/about-aws/whats-new/2023/07/amazon-mq-managed-configuration-rabbitmq-brokers/) It supports the [delivery acknowledgement timeout setting](https://www.rabbitmq.com/consumers.html#acknowledgement-timeout) and some other [setting to re-enable the operator policies](https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/rabbitmq-configuration-policies.html).

With this announcement, it means that `aws_mq_broker` should mention that `configuration` applies to both `ActiveMQ` and `RabbitMQ`. Also the warning box at the top of the documentation for `aws_mq_broker` should no longer mention that RabbitMQ imposes restrictions on `configuration` blocks.

I'm willing to provide a PR for it if can help.

**Comment by SignalWhisperer** [comment]
As I'm working on the PR, I realize this goes deeper than just a doc change. There's the `CanonicalXML` that needs to have its `CanonicalCuttlefish` equivalent for RabbitMQ. I'm not familiar with Go but I'm willing to give it a try.

**Comment by vicyap** [comment]
@SignalWhisperer - I am interested in enabling configuration support for RabbitMQ. My goal is to be able to configure the `consumer_timeout` setting for RabbitMQ.

How is it going for the PR you are working on? I am ready to try working on this, but I don't want to duplicate work if you're already working on it.

**Comment by SignalWhisperer** [comment]
Hi @vicyap, I sadly did not have any time to work on it. I've been quite sick recently, and then it got out of my mind. I have a draft PR if you're willing to continue working on it. I have not progressed any further on it.
