### ISSUE TITLE
[Enhancement]: Lambda runtime support for Python 3.10

### ISSUE THREAD

**Issue by trevorrea** [hashicorp/terraform-provider-aws#30808]
### Description

AWS recently announced support for Python 3.10 as a Lambda runtime. See https://aws.amazon.com/about-aws/whats-new/2023/04/aws-lambda-python-3-10/ and https://aws.amazon.com/blogs/compute/python-3-10-runtime-now-available-in-aws-lambda/

The AWS Go SDK has also added support for Python 3.10 a few days ago. See https://github.com/aws/aws-sdk-go/commit/98e9083d675c3371d0f1ad97e6a1cbfc9b0293a3

Could this be added to the AWS provider?

Thanks,
Trevor

### Affected Resource(s) and/or Data Source(s)

aws_lambda_function

### References

https://aws.amazon.com/about-aws/whats-new/2023/04/aws-lambda-python-3-10/ https://aws.amazon.com/blogs/compute/python-3-10-runtime-now-available-in-aws-lambda/
https://github.com/aws/aws-sdk-go/commit/98e9083d675c3371d0f1ad97e6a1cbfc9b0293a3

### Would you like to implement a fix?

Yes 

MR at https://github.com/hashicorp/terraform-provider-aws/pull/30809

### Edit

I see dependabot has already bumped the AWS SDK Go version to 1.44.245 in https://github.com/hashicorp/terraform-provider-aws/commit/e456b79d56dc5cf3bd334344351f78f7ac820b14 so I think this just needs a changelog entry created to make folks aware but it should already work out of the box in the next release if I've understood correctly?

**Comment by ewbankkit** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/30781.
