### ISSUE TITLE
[Repo]: Update actions-ecosystem/actions-remove-labels to support NodeJS 16

### ISSUE THREAD

**Issue by maunzCache** [hashicorp/terraform-provider-aws#30814]
### Description

When commenting on issues or PR, Github will trigger some workflows for the user. Even though those actions finish, i got warnings for them like this:

> issue_comment_triage
> Error: failed to remove labels: stale,waiting-response
> 
> issue_comment_triage
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> 
> issue_comment_triage
> failed to remove label: stale: HttpError: Label does not exist
> 
> issue_comment_triage
> failed to remove label: waiting-response: HttpError: Label does not exist

While the first message is a valid error, the others are a warning. I'd take the second one as recommendation to update the referenced action in https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/workflows/community-comment.yml

### References

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

### Would you like to implement a fix?

None

**Comment by maunzCache** [comment]
Just understood what the error was. This issue is blocked by https://github.com/actions-ecosystem/action-remove-labels/issues/413

**Comment by SarahFrench** [comment]
This work may help with this issue: https://github.com/hashicorp/terraform-provider-vsphere/pull/1914
Either as inspiration or something to copy over (once it's reviewed)
