### ISSUE TITLE
[Enhancement]: aws_cur_report_definition to support new split cost allocation data SchemaElement

### ISSUE THREAD

**Issue by C123R** [hashicorp/terraform-provider-aws#30813]
### Description

With recent announcements from CUR service, customer can now receive Split cost allocation data for Amazon ECS and AWS Batch. Customers must either update the existing cur definition report or create a new one specifying SPLIT_COST_ALLOCATION_DATA in AdditionalSchemaElements in order to obtain split cost allocation data.

Currently, as per [CUR API models](https://github.com/aws/aws-sdk-go/blob/7a17fe88dcd0fba24a693a59a7b4b244641ec202/models/apis/cur/2017-01-06/api-2.json#L282), it only accepts `RESOURCES` as AdditionalSchemaElements, however according to the most recent [API reference](https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_cur_ReportDefinition.html) doc, it should accept `RESOURCES | SPLIT_COST_ALLOCATION_DATA | MANUAL_DISCOUNT_COMPATIBILITY`

### Affected Resource(s) and/or Data Source(s)

* aws_cur_report_definition

### Potential Terraform Configuration

```terraform
resource "aws_cur_report_definition" "example_cur_report_definition" {
  report_name                = "example-cur-report-definition"
  time_unit                  = "HOURLY"
  format                     = "textORcsv"
  compression                = "GZIP"
  additional_schema_elements = ["RESOURCES","SPLIT_COST_ALLOCATION_DATA"]
  s3_bucket                  = "example-bucket-name"
  s3_region                  = "us-east-1"
  additional_artifacts       = ["REDSHIFT", "QUICKSIGHT"]
}
```

### References

As the AWS Go SDK still has to be updated, we are currently unable to move forward with the feature. I have already submitted a github issue for this.: https://github.com/aws/aws-sdk-go/issues/4802

API Reference: https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_cur_ReportDefinition.html

### Would you like to implement a fix?

Yes

**Comment by C123R** [comment]
Good news, [AWS Go SDK ](https://github.com/aws/aws-sdk-go/pull/4856)has been updated with the new split cost allocation schemaElement for CUR report. 

Will create PR with the changes shortly.

**Comment by k-nam** [comment]
As enum directly refer those defined in AWS GO SDK, this feature has automatically been fulfilled. I checked with current version (v5.4.0)

**Comment by C123R** [comment]
> 

Yes, It was auto-resolved with the[ latest SDK update](https://github.com/aws/aws-sdk-go/pull/4856) which was requested internally in AWS (I work for AWS). 😄

With this PR #32084, just updating respective doc and tests.

**Comment by C123R** [comment]
> As enum directly refer those defined in AWS GO SDK, this feature has automatically been fulfilled. I checked with current version (v5.4.0)

Yes, It was auto-resolved with the[ latest SDK update](https://github.com/aws/aws-sdk-go/pull/4856) which was requested internally in AWS (I work for AWS). 😄

With this PR #32084, just updating respective doc and tests.
