### ISSUE TITLE
[Bug]: Elastc Beanstalk issue with updating on v4.63.0 of provider

### ISSUE THREAD

**Issue by markrossatos** [hashicorp/terraform-provider-aws#30812]
### Terraform Core Version

1.3.7

### AWS Provider Version

4.63.0

### Affected Resource(s)

aws_elastic_beanstalk_application

### Expected Behavior

Application should be able to be updated, as worked on previous version of the provider

### Actual Behavior

Despite no changes to the Terraform code (only an updated zip file of app to be deployed) redployment which has been working fine now errors with 'Specify at least one of these parameters: TagsToAdd, TagsToRemove.'

### Relevant Error/Panic Output Snippet

```shell
Error: updating tags for Elastic Beanstalk Application (arn removed for security): tagging resource (arn removed for security): MissingParameter: Specify at least one of these parameters: TagsToAdd, TagsToRemove.
```

### Terraform Configuration Files

Cannot share

### Steps to Reproduce

Create Elastic Beanstalk application with provider v4.61.0 then try and amend it with provider 4.63.0

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/30533.

**Comment by ewbankkit** [comment]
I _think_ it was a change from `IgnoreAWS()` to `IgnoreElasticbeanstalk()` in #30643 that caused this.
We need to make sure that the resulting list of tags is not empty.
