### ISSUE TITLE
[Docs]: aws_dynamodb_table_item data source attributes

### ISSUE THREAD

**Issue by mreimer** [hashicorp/terraform-provider-aws#30830]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/dynamodb_table_item

### Description

The attributes reference reads:

> [item] - A map of attribute names to [AttributeValue] objects, as specified by ProjectionExpression.

After struggling with this for a while I figured out that item is actually a json string that I needed to decode. It would be helpful to put that in the doc.

### Would you like to implement a fix?

None

**Comment by pravinbhande** [comment]
Thanks for highlighting.   "Item" which corresponds to "AttributeValue" which is nothing but the data for an attribute. I will check and update this.

**Comment by mreimer** [comment]
Just to be sure that I was clear: my concern is that "item" is described as a map, but it is a string.

**Comment by pravinbhande** [comment]
thanks. I think the better wording for this would be "JSON representation of a map of attribute name/value pairs,
