### ISSUE TITLE
[Enhancement]: Support `PrivateDnsOnlyForInboundResolverEndpoint` on `aws_vpc_endpoint` `dns_options`

### ISSUE THREAD

**Issue by jbg** [hashicorp/terraform-provider-aws#30853]
### Description

VPC endpoints support a `PrivateDnsOnlyForInboundResolverEndpoint` boolean within their DNS options, which optimises costs for services that support both gateway and interface endpoints, by routing traffic to the interface endpoints only from on-premises networks or VPCs in other regions, and using gateway endpoints (which are not billed) for all other traffic.

### Affected Resource(s) and/or Data Source(s)

* aws_vpc_endpoint

### Potential Terraform Configuration

```terraform
resource "aws_vpc_endpoint" "s3_gateway" {
  vpc_id            = aws_vpc.vpc.id
  vpc_endpoint_type = "Gateway"
  service_name      = "com.amazonaws.ap-southeast-1.s3"
  route_table_ids   = [for route_table in aws_route_table.private : route_table.id]
}

resource "aws_vpc_endpoint" "s3_interface" {
  vpc_id              = aws_vpc.vpc.id
  vpc_endpoint_type   = "Interface"
  service_name        = "com.amazonaws.ap-southeast-1.s3"
  security_group_ids  = [aws_security_group.vpc_endpoints.id]
  subnet_ids          = [for subnet in aws_subnet.private_vpc_endpoints : subnet.id]
  private_dns_enabled = true

  dns_options {
    private_dns_only_for_inbound_resolver_endpoint = true
  }
}
```

### References

https://docs.aws.amazon.com/AmazonS3/latest/userguide/privatelink-interface-endpoints.html#private-dns

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DnsOptionsSpecification.html

### Would you like to implement a fix?

None

**Comment by kadrach** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/30041

**Comment by jbg** [comment]
Thanks, I searched `PrivateDnsOnlyForInboundResolverEndpoint` and came up empty. Will close this one!
