### ISSUE TITLE
[Enhancement]: aws_guardduty_detector Lambda Protection support

### ISSUE THREAD

**Issue by oleptho** [hashicorp/terraform-provider-aws#30859]
### Description

[Amazon GuardDuty now supports Lambda Protection](https://aws.amazon.com/about-aws/whats-new/2023/04/amazon-guardduty-aws-lambda/) but the terraform resource for GuardDuty does not yet support it.

It would be great if we could enable GuardDuty Lambda Protection with terraform resource `aws_guardduty_detector`.

### Affected Resource(s) and/or Data Source(s)

* resource: aws_guardduty_detector
* data: aws_guardduty_detector

### Potential Terraform Configuration

```terraform
resource "aws_guardduty_detector" "MyDetector" {
  enable = true

  datasources {
    s3_logs {
      enable = true
    }
    lambda_protection {
      enable = true
    }
    kubernetes {
      audit_logs {
        enable = false
      }
    }
    malware_protection {
      scan_ec2_instance_with_findings {
        ebs_volumes {
          enable = true
        }
      }
    }
  }
}
```

### References

* https://registry.terraform.io/providers/hashicorp/aws/4.64.0/docs/resources/guardduty_detector
* https://aws.amazon.com/about-aws/whats-new/2023/04/amazon-guardduty-aws-lambda/

### Would you like to implement a fix?

None

**Comment by galoitsu** [comment]
[GuardDuty API changes in March 2023#Mapping dataSources to features](https://docs.aws.amazon.com/guardduty/latest/ug/guardduty-feature-object-api-changes-march2023.html#guardduty-feature-enablement-datasource-relation)

According to the official documentation above, it appears that the `DataSources` attribute cannot be used to set Lambda protection and that the `Features` attribute must be used instead.

In addition, this provider does not currently support the `Features` attribute, so you cannot use this provider to set Lambda protection.

See #30303 .

**Comment by ewbankkit** [comment]
You will be able to use the upcoming `aws_guardduty_detector_feature` resource (https://github.com/hashicorp/terraform-provider-aws/pull/31463):

```hcl
resource "aws_guardduty_detector" "example" {
  enable = true
}

resource "aws_guardduty_detector_feature" "example" {
  detector_id = aws_guardduty_detector.example.id
  name        = "LAMBDA_NETWORK_LOGS"
  status      = "ENABLED"
}
```
