### ISSUE TITLE
[Enhancement]: Update to Golang 1.20

### ISSUE THREAD

**Issue by stephen-opal** [hashicorp/terraform-provider-aws#30876]
### Description

Hey folks, when possible can we update to Golang 1.20? Reference [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/.go-version). We're having some DNS over HTTPS issues with using our VPN provider that should be fixed in 1.20.

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Relevant: https://tip.golang.org/doc/go1.20#ports.

**Comment by tristanmorgan** [comment]
Related issue [terraform#32778](https://github.com/hashicorp/terraform/issues/32778)
