### ISSUE TITLE
[Bug]: aws_vpc_endpoint_service_allowed_principal

### ISSUE THREAD

**Issue by robh007** [hashicorp/terraform-provider-aws#30873]
### Terraform Core Version

1.3.4

### AWS Provider Version

4.64.0

### Affected Resource(s)

* aws_vpc_endpoint_service_allowed_principal

### Expected Behavior

You should be able to add multiple allowed principals to an existing `aws_vpc_endpoint_service`

```hcl
resource "aws_vpc_endpoint_service_allowed_principal" "this" {
  vpc_endpoint_service_id = data.aws_vpc_endpoint_service.this.service_id
  principal_arn           = "arn:aws:iam::123456789012:root"
}
```

### Actual Behavior

Change #27640 as introduced a bug.

If you already have an allowed principal attached to a service you can't add another one.

### Relevant Error/Panic Output Snippet

```shell
Error: reading EC2 VPC Endpoint Service (vpce-svc-fake-id) Allowed Principal (arn:aws:iam::123456789012:root): too many results: wanted 1, got 68
 │ 
 │   with aws_vpc_endpoint_service_allowed_principal.this,
 │   on main.tf line 5, in resource "aws_vpc_endpoint_service_allowed_principal" "this":
 │    5: resource "aws_vpc_endpoint_service_allowed_principal" "this" {
 │ 
 ╵
```

### Terraform Configuration Files

```hcl
resource "aws_vpc_endpoint_service_allowed_principal" "this" {
  vpc_endpoint_service_id = aws_vpc_endpoint_service.name.service_id
  principal_arn           = "arn:aws:iam::210987654321:root"
}

resource "aws_vpc_endpoint_service" "name" {
  acceptance_required = true

  network_load_balancer_arns = ["nlb-arn"]

  tags = { Name = "test-001" }

  allowed_principals = ["arn:aws:iam::123456789012:root"]
}
```

### Steps to Reproduce

Create a VPC Endpoint Service with an allowed principal configured.

Try to add an additional principal using 

aws_vpc_endpoint_service_allowed_principal

### Important Factoids

The call to FindVPCEndpointServicePermissions, doesn't look to filter the results and returns all attached Principals.

https://github.com/hashicorp/terraform-provider-aws/blob/746e737d97de45ac1c37d4b114b9c325b80ee98e/internal/service/ec2/find.go#L3348-L3353

### Would you like to implement a fix?

None

**Comment by arthosdevelops** [comment]
Thanks for raising this, we are also facing this issue right now and is it is blocking our pipelines. Are there some workarounds for this? (Prefereably we would like to wait for the bug fix if it would be released soon )

**Comment by thepoppingone** [comment]
@arthosdevelops i think the best way for you now is to roll back to 1 version prior and lock it at that version for the moment
