### ISSUE TITLE
[New Resource]: aws_vpclattice_resource_policy 

### ISSUE THREAD

**Issue by nrajb** [hashicorp/terraform-provider-aws#30900]
### Description

VPC Lattice Resource Policy attaches a resource-based permission policy to a service or service network. The policy must contain the same actions and condition statements as the Amazon Web Services Resource Access Manager permission for sharing services and service networks.

### Requested Resource(s) and/or Data Source(s)

aws_vpclattice_resource_policy

### Potential Terraform Configuration

```terraform
resource "aws_vpclattice_resource_policy" "example" {
  resource_arn = aws_vpclattice_service.example.arn
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action    = [
          "vpc-lattice:CreateServiceNetworkVpcAssociation",
           "vpc-lattice:UpdateServiceNetworkVpcAssociation",
           "vpc-lattice:DeleteServiceNetworkVpcAssociation"
        ]
        Effect    = "Allow"
        Principal = "*"
        Resource  = "*"
        Condition = {
          StringEquals = {
            "vpc-lattice:ServiceNetworkArn" = "arn:aws:vpc-lattice:us-west-2:123456789012:servicenetwork/sn-903004f88example",
            "vpc-lattice:VpcId": "vpc-1a2b3c4d"
          }
        }
      }
    ]
  })
}
```

### References

API Reference: https://docs.aws.amazon.com/vpc-lattice/latest/APIReference/API_PutResourcePolicy.html
API docs: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/vpclattice
User Guide: https://docs.aws.amazon.com/vpc-lattice/latest/ug/

### Would you like to implement a fix?

Yes

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/30380.
