### ISSUE TITLE
[Enhancement]: aws_elasticache_user resource customizable timeouts

### ISSUE THREAD

**Issue by AdrianFarmadin** [hashicorp/terraform-provider-aws#30921]
### Description

The aws_elasticache_user resource has hard-coded 5min timeouts. The user create step can take longer than 5min. It would be great to have an option to increase the timeout with Terraform customizable timeouts.

### Affected Resource(s) and/or Data Source(s)

* aws_elasticache_user

### References

Terraform documentation: https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/retries-and-customizable-timeouts

### Would you like to implement a fix?

None

**Comment by jbiers** [comment]
I would like to contribute to this issue

**Comment by hernandanielg** [comment]
Created a PR #31076 but still needs work, but if you can review it and point out what I could be missing or if it's going in the right direction would be amazing ;) 

![scaler-create-impact](https://user-images.githubusercontent.com/7015094/235379569-19525827-c80b-4525-b9c3-9cc0d5ad9955.gif)

@jbiers I'm sorry I was working on this few days ago but got distracted by real life (kids and wifey), hope you don't mind ✌🏻
