### ISSUE TITLE
[Bug]: configuring Terraform AWS Provider: validating provider credentials:.......no such host

### ISSUE THREAD

**Issue by dreamsjtu** [hashicorp/terraform-provider-aws#30959]
### Terraform Core Version

1.4.4

### AWS Provider Version

4.64.0

### Affected Resource(s)

aws_instance

### Expected Behavior

Instance created successfully

### Actual Behavior

terraform apply result in error:

` Error: configuring Terraform AWS Provider: validating provider credentials: retrieving caller identity from STS: operation error STS: GetCallerIdentity, https response error StatusCode: 0, RequestID: , request send failed, Post "https://sts.us-east-1.amazonaws.com/": dial tcp: lookup sts.us-east-1.amazonaws.com on [2405:da40:4309:dc00::1]:53: no such host
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on main.tf line 1, in provider "aws":
│    1: provider "aws" {
│ 
╵`

### Terraform Configuration Files

```terraform
provider "aws" {
  region  = "us-east-1"
}

resource "aws_instance" "app_server" {
  ami           = "ami-00c39f71452c08778"
  instance_type = "t2.micro"

  tags = {
    Name = "ExampleAppServerInstance"
  }
}
```

### Steps to Reproduce

terraform init
terraform apply

### Important Factoids

I've changed the provider version to v4.61.0 by editing the .terraform.lock.hcl file and it worked. 

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @dreamsjtu 👋 Thank you for taking the time to raise this! On an initial glance, this seems like it could be a local DNS issue, particularly as nothing to do with authentication has changed between these versions. Are you able to provide debug logs (redacted as needed) so that we can see if anything out of the ordinary is revealed in those?

**Comment by dreamsjtu** [comment]
> 

Hey Justin, thanks for your response, I tried today and it just works perfectly, the changes I've made today are the access key and secret key, because I'm using a sandbox environment for learning and the credentials change every day. I would close this issue, but would you mind explain me a bit more about the local DNS issue? I'm curious to know what happened under the hood.
