### ISSUE TITLE
[Bug]: AWS SecutiryGroupRules on different modules

### ISSUE THREAD

**Issue by RonaldoNazo** [hashicorp/terraform-provider-aws#30958]
### Terraform Core Version

1.4.5

### AWS Provider Version

v4.58.0

### Affected Resource(s)

aws_security_group & aws_security_group_rule

### Expected Behavior

I have 2 modules , on module-a i create aws_security_group  , on module-b i create a aws_security_group_rule  for the security_group i created on module-a. I want to be able to add rules from both modules.

### Actual Behavior

The rules that i create on module-b for aws_security_group get destroyed on the next apply , and keeps internating after every plan/apply! It might be a problem since it might cause network failure!

### Terraform Configuration Files

Module-a:
```hcl
resource "aws_security_group" "rds" {
  name        = join("", [var.prefixname, "sg"])
  description = "Security group for rds"
  vpc_id      = data.aws_vpc.main_vpc.id
  dynamic "ingress" {
    for_each = var.security_group_rules

    content {
      description     = lookup(ingress.value, "description", "Default Rule")
      from_port       = coalesce(var.port, local.engine_port[local.engine])
      to_port         = coalesce(var.port, local.engine_port[local.engine])
      protocol        = "tcp"
      cidr_blocks     = lookup(ingress.value, "cidr_blocks", null)
      security_groups = lookup(ingress.value, "security_groups", null)
    }

  }
  tags = merge(var.common_tags, {
    Name = join("", [var.prefixname, "sg"])
  })
}
```

Module-b:
```hcl
resource "aws_security_group_rule" "Rds_lambda" {
  description              = "RDS SG RULE TO ALLOW TRAFFIC FROM LAMBDA ROTATOR"
  type                     = "ingress"
  from_port                = 0
  to_port                  = 0
  protocol                 = "-1"
  source_security_group_id = aws_security_group.Lambda_rotator.id
  security_group_id        = data.aws_db_instance.database.vpc_security_groups[0]
}
```
### Steps to Reproduce

terraform apply twice!

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @RonaldoNazo 👋 Thank you for taking the time to raise this! This is covered in the `aws_security_group` resource documentation with the following note:

> Terraform currently provides a Security Group resource with `ingress` and `egress` rules defined in-line and a [Security Group Rule resource](https://registry.terraform.io/providers/hashicorp/aws/4.64.0/docs/resources/security_group_rule) which manages one or more `ingress` or `egress` rules. Both of these resource were added before AWS assigned a [security group rule unique ID](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/security-group-rules.html), and they do not work well in all scenarios using the `description` and `tags` attributes, which rely on the unique ID. The [aws_vpc_security_group_egress_rule](https://registry.terraform.io/providers/hashicorp/aws/4.64.0/docs/resources/vpc_security_group_egress_rule) and [aws_vpc_security_group_ingress_rule](https://registry.terraform.io/providers/hashicorp/aws/4.64.0/docs/resources/vpc_security_group_ingress_rule) resources have been added to address these limitations and should be used for all new security group rules. You should not use the `aws_vpc_security_group_egress_rule` and `aws_vpc_security_group_ingress_rule` resources in conjunction with an `aws_security_group` resource with in-line rules or with `aws_security_group_rule` resources defined for the same Security Group, as rule conflicts may occur and rules will be overwritten.

To fix the issue you're running into currently, you can update module-a to use distinct `aws_security_group_ingress_rule` resources, rather than defining them inline. Given the note, I'd also recommend updating module-b to use `aws_security_group_ingress_rule` resource(s) (and `aws_security_group_egress_rule` if needed).

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
