### ISSUE TITLE
[Enhancement]: Discourage use of `aws_spot_fleet_request` and `aws_spot_instance_request` resources

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#30975]
### Description

In https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-best-practices.html#which-spot-request-method-to-use, AWS discourages the use of the [`RequestSpotFleet`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RequestSpotFleet.html) and [`RequestSpotInstances`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RequestSpotInstances.html) API calls, corresponding to the `aws_spot_fleet_request` and `aws_spot_instance_request` resources. The resource documentation should note this.

### Affected Resource(s) and/or Data Source(s)

aws_spot_fleet_request
aws_spot_instance_request

### Would you like to implement a fix?

None

**Comment by jar-b** [comment]
Closed by #31108, merged to `main` via #31392
