### ISSUE TITLE
[Bug]: Changes to aws_securityhub_account resource breaks contract

### ISSUE THREAD

**Issue by ctrawick** [hashicorp/terraform-provider-aws#30980]
### Terraform Core Version

v1.3.9

### AWS Provider Version

4.64.0

### Affected Resource(s)

aws_securityhub_account

### Expected Behavior

Missing optional fields should not impact existing resources.

### Actual Behavior

~ resource "aws_securityhub_account" "main" {
(https://gitlab.com/XXXXXX)      ~ control_finding_generator = "STANDARD_CONTROL" -> "SECURITY_CONTROL"

### Relevant Error/Panic Output Snippet

```shell
│ Error: updating Security Hub Account (XXXXX): InvalidAccessException: Request contains configurations that cannot be updated by a member account XXXXX
```

### Terraform Configuration Files

Requires multiple runs across multiple versions

### Steps to Reproduce

1. Implement AWS Security Hub in v4.63
2. Re-apply in v4.64
3. Fail

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @ctrawick 👋 Thank you for taking the time to raise this! Are you able to supply a sample Terraform configuration and debug logs (redacted as necessary) so that we have the necessary information in order to look into this?

**Comment by lorengordon** [comment]
@justinretzolk The issue comes from upgrading an already applied `aws_securityhub_account` from an earlier version of the provider to >= v4.64.0. Here is the plan:

```
Terraform will perform the following actions:

  # aws_securityhub_account.this will be updated in-place
  ~ resource "aws_securityhub_account" "this" {
      ~ auto_enable_controls      = false -> true
      ~ control_finding_generator = "STANDARD_CONTROL" -> "SECURITY_CONTROL"
        id                        = "REDACTED"
        # (2 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

And here is the error:

```
aws_securityhub_account.this: Modifying... [id=REDACTED]
╷
│ Error: updating Security Hub Account (REDACTED): InvalidAccessException: Request contains configurations that cannot be updated by a member account REDACTED
│ {
│   RespMetadata: {
│     StatusCode: 401,
│     RequestID: "21556c54-f1f7-44bd-93f1-0aa7bec22c5d"
│   },
│   Code_: "InvalidAccessException",
│   Message_: "Request contains configurations that cannot be updated by a member account REDACTED"
│ }
│
│   with aws_securityhub_account.this,
│   on main.tf line 1, in resource "aws_securityhub_account" "this":
│    1: resource "aws_securityhub_account" "this" {}
```

**Comment by lorengordon** [comment]
This feature added in this pr is the source of the issue... https://github.com/hashicorp/terraform-provider-aws/pull/30692

**Comment by lorengordon** [comment]
@justinretzolk Anything else you need on this one?

**Comment by justinretzolk** [comment]
Hey @lorengordon 👋 Thank you for checking in on this! Providing a sample Terraform configuration that can reproduce this issue, as well as debug logs (redacted as needed) would be helpful if you're able to provide them. Unfortunately I can't provide an ETA on when this will be looked into due to the potential of shifting priorities. We prioritize by count of :+1: reactions and a few other things (more information on our [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/) if you're interested).

**Comment by lorengordon** [comment]
The plan I posted above basically has the config that is the problem. There isn't much more to it. It seems any version of the aws provider >= 4.64.0 is broken for the aws_securityhub_account resource, when securityhub is managed by the org, and the org has enabled the aggregated securityhub findings.

**Comment by mdolian** [comment]
We are also running into this:

```
resource "aws_securityhub_account" "main" {}
```

Results in:    

```
module.security.module.nyl-securityhub.aws_securityhub_account.main
update
control_finding_generator :
"STANDARD_CONTROL"
change to
"SECURITY_CONTROL"
no-op
id :
"709321817338"


Error: updating Security Hub Account (709321817338): InvalidAccessException: Request contains configurations that cannot be updated by a member account 709321817338 { RespMetadata: { StatusCode: 401, RequestID: "f32fd578-1617-4bca-af5e-19fc5e97d4dc" }, Code_: "InvalidAccessException", Message_: "Request contains configurations that cannot be updated by a member account 709321817338" }
with module.security.module.nyl-securityhub.aws_securityhub_account.main
on .terraform/modules/security/modules/terraform-aws-nyl-securityhub/main.tf line 1, in resource "aws_securityhub_account" "main":
resource "aws_securityhub_account" "main" {}
```

**Comment by calvin-ntier** [comment]
setting it explicitly at member account is a workaround:

resource "aws_securityhub_account" "_" {
  control_finding_generator = "STANDARD_CONTROL"
}
