### ISSUE TITLE
[New Data Resource]: AWS Organizations child OUs

### ISSUE THREAD

**Issue by mbevc1** [hashicorp/terraform-provider-aws#30992]
### Description

Currently `aws_organizations_organizational_units` is only listing all direct child organizational units under a parent organizational unit. This only provides immediate children, not all children.

### Requested Resource(s) and/or Data Source(s)

* aws_organizations_organizational_units_child_ous

### Potential Terraform Configuration

```terraform
data "aws_organizations_organization" "org" {}

data "aws_organizations_organizational_units_child_ous" "ou" {
  parent_id = data.aws_organizations_organization.org.roots[0].id
}
```

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@mbevc1 Thanks for raising this issue 👏.
It sounds like you need a new data source similar to [`aws_organizations_organizational_unit_descendant_accounts`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/organizations_organizational_unit_descendant_accounts)?

**Comment by mbevc1** [comment]
Hey @ewbankkit , indeed that would be close equivalent for listing all child OUs :+1:

**Comment by stewart-newscorp** [comment]
I might look at implementing this
