### ISSUE TITLE
[Bug]: switching from aws_iam_role_policy_attachment to managed_policy_arns DROPS all managed policies

### ISSUE THREAD

**Issue by nicolaschambrier** [hashicorp/terraform-provider-aws#31017]
### Terraform Core Version

1.3.9, 1.4.6

### AWS Provider Version

4.64.0

### Affected Resource(s)

* resource `aws_iam_role` managed policies

### Expected Behavior

In a project we wanted to switch from `aws_iam_role_policy_attachment` to `aws_iam_role.managed_policy_arns` for a lambda's role's managed policies. We read documentation, which clearly states you can use EITHER `aws_iam_role.managed_policy_arns` & `aws_iam_role.inline_policies` OR `aws_iam_role_policy_attachment` & `aws_iam_role_policy`, but not mix both. This was not the case here, we **integraly** switched from one way to another.

When applying the following example, we would have expected no change on the role's final permissions.

We went from this:

```tf
resource "aws_iam_role" "role" {
  ...
}
resource "aws_iam_role_policy_attachment" "attachment" {
  role       = aws_iam_role.role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}
```

We wanted to update to:

```tf
resource "aws_iam_role" "role" {
  ...
  managed_policy_arns   = ["arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"]
}
```

### Actual Behavior

**ALL the managed policies are dropped** in the process.

Note: applying a second time restores them.

### Relevant Error/Panic Output Snippet

```shell
ℹ️ When applying changes first time:

Terraform will perform the following actions:

  # aws_iam_role_policy_attachment.attachment will be destroyed
  # (because aws_iam_role_policy_attachment.attachment is not in configuration)
  - resource "aws_iam_role_policy_attachment" "attachment" {
      - id         = "test1-role-20230427120418506100000001" -> null
      - policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole" -> null
      - role       = "test1-role" -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.

ℹ️ At this point, the role has no managed policies attached AT ALL
ℹ️ When applying changes second time:

Terraform will perform the following actions:

  # aws_iam_role.role will be updated in-place
  ~ resource "aws_iam_role" "role" {
        id                    = "test1-role"
      ~ managed_policy_arns   = [
          + "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
        ]
        name                  = "test1-role"
        tags                  = {}
        # (9 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Terraform Configuration Files

```tf
provider "aws" {
  region  = "eu-west-3"
}

locals {
  prefix = "test1-"
}

# Same assume_role_policy for both
data "aws_iam_policy_document" "assume_role_policy" {
  statement {
    sid     = "LambdaAssumeRole"
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}

# Step 1: apply once
# Step 2: comment lines 25-32 and uncomment 35-39, then apply again => all managed policies are dropped 😭
# Step 3: apply again without changing anything more => managed policies are restored

resource "aws_iam_role" "role" {
  name                  = "${local.prefix}role"
  assume_role_policy    = data.aws_iam_policy_document.assume_role_policy.json
}
resource "aws_iam_role_policy_attachment" "attachment" {
  role       = aws_iam_role.role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

# Step 2: using managed_policy_arns
# resource "aws_iam_role" "role" {
#   name                  = "${local.prefix}role"
#   assume_role_policy    = data.aws_iam_policy_document.assume_role_policy.json
#   managed_policy_arns   = ["arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"]
# }
```

### Steps to Reproduce

1. Apply to create role and its attached policy
2. Comment lines 25-33 and uncomment 36-41, then apply again
3. In AWS console, observe the role has lost its managed policies (if there were more, they would have been dropped too)
4. Without changing anything, apply again: the policies are restored this time

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role_policy

Note: if this is an expected behavior due to incompatibility between those two ways of managing policies, and cannot be fixed, I suggest the documentation should clearly state this risk.

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @nicolaschambrier 👋 Thanks for taking the time to raise this! I think this is more of a Terraform core behavior thing rather than a bug with the AWS provider.

To get around this, you can remove the `aws_iam_role_policy_attachment` resource from the configuration and state (for the latter, you'd use the [`terraform state rm`](https://developer.hashicorp.com/terraform/cli/commands/state/rm) command).

Once that's done, update the `aws_iam_role` resource in the configuration before using the [`-refresh-only`](https://developer.hashicorp.com/terraform/tutorials/state/refresh) flag to plan/apply and update the `aws_iam_role` resource to match reality. This will get around actually modifying the resources in AWS while updating the Terraform configuration to use the alternative method of defining managed policies.

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
