### ISSUE TITLE
[Bug]: aws_lambda_function cannot use s3 access point because of regex constraint

### ISSUE THREAD

**Issue by czhoward** [hashicorp/terraform-provider-aws#31024]
### Terraform Core Version

1.3.5

### AWS Provider Version

4.63.0

### Affected Resource(s)

The `aws_lambda_function` allows providing an `s3_bucket` and `s3_key` to provision the function from a zip file hosted on an S3 bucket in the same region.  The `s3_bucket` parameter doesn't support an s3 access point because the access point includes a `/` and this causes a failure on the `terraform apply` with a regular expression error (note a `terraform plan` succeeds).

### Expected Behavior

If you use a provider alias and specify that alias in the data resource then use the bucket name rather than the access point arn, the  `aws_lambda_function` can copy the file from the s3 bucket successfully.  

Similarly if using an access point and run an `aws s3 cp` command the file can be copied.  

So I think the `aws_lambda_function` should work with an s3 access point passed as the bucket parameter, and it is failing just because of the regex, not because a file cannot be transferred from an s3 bucket in via an access point.

### Actual Behavior

on `terraform apply` at the point of creating the function an error 400 is returned, member must satisfy regular expression pattern.

### Relevant Error/Panic Output Snippet

```shell
Error: creating Lambda Function (my-lambda-function): operation error Lambda: CreateFunction, https response error StatusCode: 400, RequestID: d4e74e57-c198-4b58-9fcb-1018b5b57605, api error ValidationException: 1 validation error detected: Value 'arn:aws:s3:eu-west-2:1234567890:accesspoint/my-ap' at 'code.s3Bucket' failed to satisfy constraint: Member must satisfy regular expression pattern: ^[0-9A-Za-z\.\-_]*(?<!\.)$
```

### Terraform Configuration Files

```terraform
provider "aws" {
    region = "eu-west-2"
}

data "aws_s3_object" "lambda_function" {
  bucket = "arn:aws:s3:eu-west-2:1234:accesspoint/my-ap"
  key       = "helloworld.zip"
}

resource "aws_lambda_function" "my_lambda_function" {
  function_name    = "my-lambda-function"
  role                       = aws_iam_role.lambda_tf_role.arn
  handler                 = "index.handler"
  runtime                 = "nodejs18.x"
  s3_bucket            = data.aws_s3_object.lambda_function.bucket
  s3_key                  = data.aws_s3_object.lambda_function.key
}

resource "aws_iam_role" "lambda_tf_role" {
  name = "tf_lambda_role"
  assume_role_policy = file("${path.module}/lambda-assume-role-policy.json")
}

resource "aws_iam_role_policy" "lambda_tf_role_policy" {
  name = "tf_lambda_role_policy"
  role = aws_iam_role.lambda_tf_role.id
  policy = file("${path.module}/lambda-policy.json")
}
```
lambda-policy.json
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Action": "logs:*",
      "Effect": "Allow",
      "Resource": "*"
    },
    {
      "Sid": "",
      "Action": "s3:*",
      "Effect": "Allow",
      "Resource": "*"
    },
    {
      "Sid": "",
      "Action": "dynamodb:*",
      "Effect": "Allow",
      "Resource": "*"
    },
    {
      "Sid": "",
      "Action": "sqs:*",
      "Effect": "Allow",
      "Resource": "*"
    },
    {
      "Sid": "",
      "Action": "kinesis:*",
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
```
lambda-assume-role-policy.json
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
```

### Steps to Reproduce

I am doing this with two AWS accounts as the idea is to try and have a packaged lambda being deployed into multiple accounts but it should be possible to do this with a single account also I think.  I'll stick with two accounts as that's what I have been doing.

In account one, the account where the lambda will be deployed you need an IAM account with sufficient privileges to deploy the lambda.  It also requires a policy to allow it to access the second account that hosts the zip file.  This policy can be as simple as

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::mys3bucket",
                "arn:aws:s3:::mys3bucket/*",
                "arn:aws:s3:eu-west-2:1234:accesspoint/my-ap",
                "arn:aws:s3:eu-west-2:1234:accesspoint/my-ap/*"
            ]
        }
    ]
}
```

On the second account you require a bucket and this needs a bucket policy something like
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "*",
            "Resource": [
                "arn:aws:s3:::mys3bucket",
                "arn:aws:s3:::mys3bucket/*"
            ],
            "Condition": {
                "StringEquals": {
                    "s3:DataAccessPointAccount": "1234"
                }
            }
        }
    ]
}
```

You then need to create an s3 access point for this bucket with internet access (you don't need to allow public access) and this needs a policy something like

```json
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Sid": "AllowLambdaDeployAccess",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:*",
            "Resource": "arn:aws:s3:eu-west-2:1234:accesspoint/accesspoint/object/*",
            "Condition": {
                "StringLike": {
                    "aws:PrincipalOrgID": "o-xyz"
                }
            }
        }
    ]
}
```

Sorry I have not put these into terraform yet as I was just trying this on the fly.  the `1234` should be the account number for the account that hosts the zip file.  The condition statement probably isn't necessary I am using it to lock down access to accounts within the aws organization.  If I get a chance I'll try and put this with the necessary code for the AP and policies together into a repo along with an example that works when using a provider alias.
Thanks

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @czhoward 👋 Thank you for taking the time to raise this! It looks like the error you're receiving is coming from AWS. The AWS provider uses [`CreateFunction`](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html), and the particular bit that is of importance here is [`FunctionCode.S3Bucket`](https://docs.aws.amazon.com/lambda/latest/dg/API_FunctionCode.html#SSS-Type-FunctionCode-S3Bucket), which has the following note:

> An Amazon S3 bucket in the same AWS Region as your function. The bucket can be in a different AWS account.

**Comment by czhoward** [comment]
Thanks @justinretzolk that makes sense.  Very much appreciated for such a speedy response.  I'll see if I can get anywhere with AWS.  Thanks again.

**Comment by czhoward** [comment]
I appreciate this is closed but wanted to add the response from AWS in case anyone else comes across this.  The answer is to use the access point **alias** instead of the ARN...obvious when you know how! 😄
