### ISSUE TITLE
[Enhancement]: aws_instance and aws_launch_template add/update cpu_options

### ISSUE THREAD

**Issue by GlennChia** [hashicorp/terraform-provider-aws#31036]
### Description

Feature documentation: [CPU features](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/cpu-features.html)

Add support for `amd_sev_snp` argument. This is part of the [cpu_options](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CpuOptionsRequest.html) argument.

### Affected Resource(s) and/or Data Source(s)

* aws_instance
* aws_launch_template

### Potential Terraform Configuration

```terraform
resource "aws_instance" "example" {
  ami           = data.aws_ami.amzn-linux-2023-ami.id
  instance_type = "c6a.2xlarge"
  subnet_id     = aws_subnet.example.id

  cpu_options {
    amd_sev_snp      = "enabled"
    core_count       = 2
    threads_per_core = 2
  }

  tags = {
    Name = "tf-example"
  }
}
```

### References

- [CPU features](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/cpu-features.html)
- [cpu_options](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CpuOptionsRequest.html) argument

### Would you like to implement a fix?

Yes

**Comment by ewbankkit** [comment]
[Announcement](https://aws.amazon.com/about-aws/whats-new/2023/04/amazon-ec2-amd-sev-snp/).
