### ISSUE TITLE
AWS Lambda adds support for Java 17

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#31032]
> AWS Lambda now supports Java 17 as both a managed runtime and a container base image.

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2023/04/aws-lambda-java-17/).

Affected resources:

* `aws_lambda_function`
* `aws_lambda_layer_version`

Requires `aws-sdk-go-v2/service/lambda` module update: https://github.com/hashicorp/terraform-provider-aws/pull/31027.
Requires [AWS SDK for Go v1.44.252](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.252): https://github.com/hashicorp/terraform-provider-aws/pull/31028.

**Comment by psoares** [comment]
Thank you for fixing this so quickly. When can we expect to be able to use it?

**Comment by Clete2** [comment]
@psoares  The provider releases Wednesday evening / Thursday morning weekly. You should see it released in v4.66.0 which will be released next week around this time.
