### ISSUE TITLE
[Bug]: aws_redshiftserverless_workgroup times out creating nearly 100% of the time

### ISSUE THREAD

**Issue by RicePatrick** [hashicorp/terraform-provider-aws#31048]
### Terraform Core Version

1.4.5

### AWS Provider Version

4.64.0

### Affected Resource(s)

aws_redshiftserverless_workgroup

### Expected Behavior

Resource creates successfully

### Actual Behavior

The resource will nearly always timeout during creation while waiting for the resource to become `Available`. This appears to happen because the resource is created then immediately modified, and the timeout is not long enough to account for the modification to complete.

`waiting for Redshift Serverless Workgroup (redshift-serverless-88-workspace) to be created: timeout while waiting for state to become 'AVAILABLE' (last state: 'MODIFYING', timeout: 10m0s)`

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: waiting for Redshift Serverless Workgroup (redshift-serverless-88-workspace) to be created: timeout while waiting for state to become 'AVAILABLE' (last state: 'MODIFYING', timeout: 10m0s)
│ 
│   with aws_redshiftserverless_workgroup.redshift_db_workgroup,
│   on redshift.tf line 22, in resource "aws_redshiftserverless_workgroup" "redshift_db_workgroup":
│   22: resource "aws_redshiftserverless_workgroup" "redshift_db_workgroup" {
│
```

### Terraform Configuration Files

```hcl


resource "aws_redshiftserverless_workgroup" "redshift_db_workgroup" {
  namespace_name = aws_redshiftserverless_namespace.redshift_db_namespace.id

  workgroup_name = "redshift-serverless-${var.usage}-workspace"
  base_capacity  = var.base_redshift_capacity

  // This is intention for business reasons, and is protected by the security group.
  publicly_accessible = true
  security_group_ids  = [aws_security_group.redshift_sg.id]
  subnet_ids          = data.aws_subnets.redshift_subnets.ids
}

````

There are obviously some resources that are populated by data sources or variables, but it's a relatively minimal configuration.

### Steps to Reproduce

Simply apply the configuration and wait 10 minutes.

### Important Factoids

The resource does reach `Available` eventually, it just takes longer than the timeout provides. The resource will occasionally succeed as a result, since the resource will occasionally reach `Available` quickly enough.

Simply allowing for configuring the timeout will resolve this bug, though it's likely increasing the default timeout would also be good to cover a majority of user's cases.

### Would you like to implement a fix?

Yes

**Comment by PatrickRice-KSC** [comment]
Note: there was a previous issue reported around this: #26522 . That resource mentioned that using a dependent resource fixed the issue. I have a resource that depends on the `endpoint` attribute, and that does not resolve the issue. The rate of error has absolutely increased over time, which is likely just related to AWS taking longer to modify the resource.
