### ISSUE TITLE
[Bug]: When replacing a aws_eks_node_group with create_before_destroy fails, the old nodegroup is purged forcefully

### ISSUE THREAD

**Issue by InputObject2** [hashicorp/terraform-provider-aws#31090]
### Terraform Core Version

1.3.6

### AWS Provider Version

4.23.0

### Affected Resource(s)

aws_eks_node_group

### Expected Behavior

When the EKS controlplane enters a failed state (timeouts or error 500) while using create_before_destroy lifecycle argument on an aws_eks_node_group, the old node group waits for the node drain to complete. 

Failure should result in an inconsistent state with both the old and new nodegroup still present and a terraform error saying so.

### Actual Behavior

The old node group is force deleted without waiting for the drain to complete.

Terraform reports "Destruction Complete" on the aws_eks_node_group and continues as if the operation were a success.

### Relevant Error/Panic Output Snippet

```shell
No panic, terraform assumes that everything is working as intended.
```

### Terraform Configuration Files

The reproduction involves hitting the EKS apiserver hard enough for it to become unavaible so this is not quite easily replicated.

### Steps to Reproduce

We triggered this 2-3 times so far on large-ish clusters:
- Create a node group with lifecycle policy `create_before_destroy` enabled.
- Scale up the nodegroup to 20 nodes and deploy some workloads to have around 2000 pods.
- Create a `podDisruptionBudget` that should block any moves (`minAvailable: 1, replica: 1`) on one of the deployments to block drain and prevent the old nodegroup from being deleted
- Change the nodegroup name to force recreation. The amount of pods to re-schedule sometimes overloads the EKS cluster's controlplane.

The old nodes won't be able to fully drain due to the pdb and should stay "online" forever.
If terraform loses access to the cluster's controplane during the delete (drain) phase, it might decide the the old node group no longer has any nodes and continue with deleting it immediately.

### Important Factoids

We've seen the controlplane become unresponsive a couple of times while doing large-scale drains on our clusters to replace nodegroups.

This does not happen with nodegroup AMI rollouts, in which case terraform respects the nodes being drained (and waits for an hour until timing out) unless `force_update_version` is specified.

`force_update_version` is set to false in this scenario.

### Would you like to implement a fix?

No

**Comment by bryantbiggs** [comment]
@InputObject2 is still still relevant or can we close out this issue?

**Comment by InputObject2** [comment]
I'm not sure if this is still relevant, we migrated to Karpenter so we won't be able to test anymore.

**Comment by bryantbiggs** [comment]
no worries! If you don't mind, could you please close out the issue - it helps to keep the focus on active issues that require attention. thank you!
