### ISSUE TITLE
[Bug]: Terraform state is not reflected correctly using cross-account ARN in aws_ec2_network_insights_path. 

### ISSUE THREAD

**Issue by alex-zige** [hashicorp/terraform-provider-aws#31123]
### Terraform Core Version

1.3

### AWS Provider Version

4.46

### Affected Resource(s)

aws_ec2_network_insights_path
aws_ec2_network_insights_analysis

### Expected Behavior

Run terramform apply with the cross account ENI as source and destination (resource ARN)
The terraform state is populated correctly with correct values and mappings. 
Re-run terraform apply will not replace the existing paths. 

### Actual Behavior

When uses cross account `aws_ec2_network_insights_path` features, the source/destination can reference the ARN instead.

ie. "arn:aws:ec2:ap-southeast-2:account-id:network-interface/eni-id". 

However, once the resource is created, the terraform state does not reference the ARN and fallback to the source account source and destination. This causes the Terraform state to become unsynchronized, at the next subsequent terraform  apply, will cause re-creating those path with new resources using the provided cross-account ARN.

### Terraform Configuration Files

```terraform
resource "aws_ec2_network_insights_path" "this" {
  source           = "arn:aws:ec2:ap-southeast-2:src-account-id:network-interface/eni-id"
  destination      = "arn:aws:ec2:ap-southeast-2:dest-account-id:network-interface/eni-id"
  destination_port = "80"
  protocol         = "tcp"
}
```

### Steps to Reproduce

1. Enable Cross Account reachbility analyzer within the org .https://docs.aws.amazon.com/vpc/latest/reachability/multi-account.html
2. Create aws_ec2_network_insights_path with the cross account configuration provided and run terraform apply
3. After the path created, do not change the TF configuration file, and run Terrafrom plan 
4. Review the changes to be updated.
5. Run Terraform apply will create new paths instead. 

### Would you like to implement a fix?

None

**Comment by yoyoman21** [comment]
Is terraform having support for cross account ec2 network insight path resource for latest aws provider version, because  I have the cross account setup done but its not working via terraform. The same thing  works through console. The network path is taking same account id as source and destination even if the instances are in different account.
