### ISSUE TITLE
[Bug]: #30885 introduced a new perpetual diff

### ISSUE THREAD

**Issue by k-brooks** [hashicorp/terraform-provider-aws#31136]
### Terraform Core Version

1.4.5

### AWS Provider Version

4.65.0

### Affected Resource(s)

aws_dms_replication_task

### Expected Behavior

Specifying the EnableLogContext property in the replication task settings should not trigger a perpetual diff.

### Actual Behavior

Specifying the EnableLogContext property in the replication task settings triggers a perpetual diff.

### Terraform Configuration Files

```
resource "aws_dms_replication_task" "example" {
      id                        = "example"
      replication_task_settings = jsonencode(
           {
              Logging  = {
                  EnableLogContext = false
                }
            }
        )
    }
```

### Steps to Reproduce

1. Apply
2. Plan - see diff

### Important Factoids

Introduced by #30885

### References

#19883

### Would you like to implement a fix?

None

**Comment by johnathan99j** [comment]
I'm getting this on provider `4.67.0` as well

**Comment by gfysaris** [comment]
I have the same issue with 
Terraform v1.2.2 on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v5.11.0

**Comment by r-roos** [comment]
Also encountering this issue on Terrafrom v1.3.1 with AWS provider version: 5.17.0 

Is there any known workaround which can be applied.

**Comment by yoni-yad2** [comment]
Waiting for a fix as well.
diffs always show up for historyTimeslotInMinutes + EnableLogContext

**Comment by rameshkumar20** [comment]
Same issue with us as well. Always showing historyTimeslotInMinutes + EnableLogContext as changed.
This lead to DMS task being modified everytime and impacts our CDC data capture effecting our production systems. Appreciate for early resolution.
