### ISSUE TITLE
d/aws_subnet_ids: Remove

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#31134]
The `aws_subnet_ids` data source was deprecated in `v4.0.0` of the Terraform AWS Provider.
It can now be removed.

Relates https://github.com/hashicorp/terraform-provider-aws/pull/22743.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/20592.

**Comment by jar-b** [comment]
Closed by #31140, merged to `main` via #31392
