### ISSUE TITLE
[Enhancement]: Add certificates and sha1_fingerprint as exported attributes to aws_eks_cluster module

### ISSUE THREAD

**Issue by dsaydon90** [hashicorp/terraform-provider-aws#31150]
### Description

Today, in order to create aws_iam_openid_connect_provider to my EKS cluster I need to provide thumbprint_list.
In order to retrieve the thumbprint_list I'll have to use the data source tls_certificate for that.

Example:
```
resource "aws_eks_cluster" "example" {
  # ... other configuration ...
}

data "tls_certificate" "example" {
  url = aws_eks_cluster.example.identity[0].oidc[0].issuer
}

resource "aws_iam_openid_connect_provider" "example" {
  client_id_list  = ["sts.amazonaws.com"]
  thumbprint_list = [data.tls_certificate.example.certificates[0].sha1_fingerprint]
  url             = aws_eks_cluster.example.identity[0].oidc[0].issuer
}
```

From: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#enabling-iam-roles-for-service-accounts

There is any way to avoid from using the **data** source `tls_certificate` by adding the `tls_certificate` **data** (like certificates and sha1_fingerprint) as part of the `aws_eks_cluster` module attributes?

**Comment by justinretzolk** [comment]
Hey @dsaydon90 👋 Thank you for taking the time to raise this! The response that the provider receives when reading the cluster after creation is a AWS Go SDK type [`eks.Cluster`](https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#Cluster). Looking at the reference for that Go type, I don't believe that the information that you're requesting is returned, so this would be a limitation of the API/SDK.

Given that this is an upstream limitation, we'll close this request for now. If this changes in the future, or you feel I've missed a key piece of information, we'd be happy to take another look.
