### ISSUE TITLE
[Enhancement]: AWS Network Firewall - Support for Ingress TLS inspection

### ISSUE THREAD

**Issue by waynechong1995** [hashicorp/terraform-provider-aws#31154]
### Description

AWS Network Firewall [introduced support](https://aws.amazon.com/about-aws/whats-new/2023/03/aws-network-firewall-support-ingress-tls-inspection//) for ingress TLS inspection on Mar 30, 2023.

### Requested Resource(s) and/or Data Source(s)

aws_networkfirewall_tls_inspection_configuration

### Would you like to implement a fix?

None

**Comment by ddericco** [comment]
I can work on this.

**Comment by michaelrechani** [comment]
Any idea when this feature might available?

**Comment by bsaurusrex** [comment]
@ddericco any news?  It would be helpful if minimally the following resourece supported calling the ARN of the inspection policy as there is a limitation with AWS that the inspection policy has to be added to the fw policy during creation. 

aws_networkfirewall_firewall_policy

**Comment by ddericco** [comment]
@bsaurusrex Thanks for the ping - I haven't had the bandwidth to finish this yet, but should be able to finalize in next few weeks unless another contributor can/wants to take it on sooner.

**Comment by mgfink** [comment]
@ddericco I see this ticket references TLS configs for ingress but in the last several months AWS also started supporting egress TLS configs.  Will this ticket address both configurations?

**Comment by ddericco** [comment]
@mgfink the PR covers both ingress and egress.
