### ISSUE TITLE
Remove provider configuration attributes deprecated in V4.X

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#31160]
Remove the provider configuration attributes deprecated in V4.X:

* `assume_role.duration_seconds` - Use `assume_role.duration` instead
* `assume_role_with_web_identity.duration_seconds` - Use `assume_role_with_web_identity.duration` instead
* `s3_force_path_style` - Use `s3_use_path_style` instead
* `shared_credentials_file` - Use `shared_credentials_files` instead
* `skip_get_ec2_platforms` - Remove following the retirement of EC2-Classic

Relates https://github.com/hashicorp/terraform-provider-aws/pull/23080.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/23055.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/23077.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/29480.

**Comment by jar-b** [comment]
Closed by #31155, merged to `main` via #31392
