### ISSUE TITLE
[Enhancement]: aws_db_snapshot_copy support for sharing snapshots

### ISSUE THREAD

**Issue by michemache** [hashicorp/terraform-provider-aws#31212]
### Description

The `aws_db_snapshot` resource supports snapshot sharing with the `shared_accounts` argument since release [v4.58.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.58.0). Would be very helpful if `aws_db_snapshot_copy` got this feature too.

### Affected Resource(s) and/or Data Source(s)

* aws_db_snapshot_copy

### Potential Terraform Configuration

```terraform
resource "aws_db_snapshot_copy" "example" {
  source_db_snapshot_identifier = "arn:aws:rds:..."
  target_db_snapshot_identifier = "copy-snapshot"
  shared_accounts               = ["111122223333", "444455556666"]
}
```

### References

Similar to the implementation for `aws_db_snapshot` here: https://github.com/hashicorp/terraform-provider-aws/pull/28424
A related issue: https://github.com/hashicorp/terraform-provider-aws/issues/14600

### Would you like to implement a fix?

None

**Comment by bschaatsbergen** [comment]
Thanks for raising this issue @michemache, I'm happy to take a stab at it.
