### ISSUE TITLE
[Enhancement]: Allow secondary Elastic IPs in Nat Gateway configuration

### ISSUE THREAD

**Issue by marcincuber** [hashicorp/terraform-provider-aws#31229]
### Description

Allow association of secondary Elastic IPs. I believe you can associate up to six additional ones.

### Affected Resource(s) and/or Data Source(s)

aws_nat_gateway

### Would you like to implement a fix?

None

**Comment by grzechukol** [comment]
Any updates on the ETA for this feature?
Ref. https://aws.amazon.com/about-aws/whats-new/2023/02/amazon-nat-gateways-capacity-concurrent-connections-unique-destination/

**Comment by bschaatsbergen** [comment]
I'll happily pick this up 👍🏼
