### ISSUE TITLE
[Bug]: Scheduling priority

### ISSUE THREAD

**Issue by yushkevicham** [hashicorp/terraform-provider-aws#31226]
### Terraform Core Version

1.4.6

### AWS Provider Version

4.53.0

### Affected Resource(s)

resource "aws_batch_job_definition"
Input parameter support not found "Scheduling priority"

### Expected Behavior

AWS Batch Job must be executed without errors

### Actual Behavior

I get error:
Either schedulingPriority in job definition or schedulingPriorityOverride is required.

### Relevant Error/Panic Output Snippet

```shell
Either schedulingPriority in job definition or schedulingPriorityOverride is required. (Service: AWSBatch; Status Code: 400; Error Code: ClientException; Request ID: 3af3a227-b037-45bf-89f6-102934d79f83; Proxy: null)
```

### Terraform Configuration Files

```terraform
resource "aws_batch_job_definition" "test" {
  name = "tf_test_batch_job_definition"
  type = "container"
  container_properties = jsonencode({
    command = ["ls", "-la"],
    image   = "busybox"

    resourceRequirements = [
      {
        type  = "VCPU"
        value = "0.25"
      },
      {
        type  = "MEMORY"
        value = "512"
      }
    ]

    volumes = [
      {
        host = {
          sourcePath = "/tmp"
        }
        name = "tmp"
      }
    ]

    environment = [
      {
        name  = "VARNAME"
        value = "VARVAL"
      }
    ]

    mountPoints = [
      {
        sourceVolume  = "tmp"
        containerPath = "/tmp"
        readOnly      = false
      }
    ]

    ulimits = [
      {
        hardLimit = 1024
        name      = "nofile"
        softLimit = 1024
      }
    ]
  })
}
```

### Steps to Reproduce

terraform init
terraform apply

### Would you like to implement a fix?

None

**Comment by drewmullen** [comment]
I am unable to recreate this. Using the provided HCL I get the error

```shell
│ Error: creating Batch Job Definition (tf_test_batch_job_definition): ClientException: Error executing request, Exception : Value 0.25 for type VCPU in resourceRequirement is not valid. Please provide a numeric value., RequestId: 09a4a3a9-060b-4b5c-9902-b252d4b815e7
```

If i update VCPU to `"1"`, the execution works fine.

**Comment by kdurolek** [comment]
This is still existing issue. 
It isn't possible to set `schedulingPriority` via terraform for job definition, and if you don't decide to override this setting using `schedulingPriorityOverride` during job submission you will get that error.

I shouldn't be forced to override `schedulingPriority` only because I cannot set it properly in a first place.

By doing it that way we limit our options for more advanced use cases and scenarios.

**Comment by drewmullen** [comment]
I'm happy to take a look. Please provide a full example that i can use to recreate, @kdurolek

**Comment by kdurolek** [comment]
Hi @justinretzolk, 
is there a chance to review that bug in foreseeable future? 
Thank you

**Comment by yushkevicham** [comment]
The example is simple. We have "Scheduling priority" input parameter in AWS console, but we don't have this input parameter in terraform [resource: aws_batch_job_definition](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/batch_job_definition)
![image](https://github.com/hashicorp/terraform-provider-aws/assets/97115964/bc478b46-d86f-41e1-94cf-e48c19de73a8)

**Comment by kdurolek** [comment]
1. We need to setup any compute environment on AWS batch.
2. We need to create queue AND assign "aws_batch_scheduling_policy". That enables fair share scheduling and AWS.
3. From now on you MUST define scheduling priotity on job definition (not availble currently via terraform) or override during job submissions.

**Comment by drewmullen** [comment]
Ah, I thought scheduling priority was part of container properties. I should be able to get this feature added for yall
