### ISSUE TITLE
[New Resource]: Add a resource to manage STS Global Endpoint Security Token

### ISSUE THREAD

**Issue by campaand** [hashicorp/terraform-provider-aws#31244]
### Description

Hi,
I would ask, if possible, the implementation of a resource within the STS or IAM category to have the possibility of managing STS Global Endpoint (Session Tokens from the STS endpoints) which, as per [AWS documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html?icmpid=docs_iam_console#sts-regions-manage-tokens), can take on 2 values (AWS Console View):
- `AWS Regions enabled by default`
- `All AWS Regions`

The API call from AWS CLI to perform the change is the following:
`aws iam set-security-token-service-preferences` and the `--global-endpoint-token-version` parameter can assume only two values, as mentioned [here](https://docs.aws.amazon.com/cli/latest/reference/iam/set-security-token-service-preferences.html#options).

### Requested Resource(s) and/or Data Source(s)

If included in STS category maybe can be `aws_sts_session_security_token`
If included in IAM category maybe can be something like this `aws_iam_session_security_token`

### Potential Terraform Configuration

```terraform
resource "aws_iam_session_security_token" "example" {
  global_endpoint_token_version = "v1Token"
}
```

### References

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html?icmpid=docs_iam_console#sts-regions-manage-tokens

https://docs.aws.amazon.com/cli/latest/reference/iam/set-security-token-service-preferences.html#options

### Would you like to implement a fix?

No

**Comment by bschaatsbergen** [comment]
Thanks for raising this issue @campaand - I would happily take a stab at this.

**Comment by bschaatsbergen** [comment]
Judging by the API call, I would likely propose the name of the resource to be `aws_iam_security_token_service_preference`, which can be set to either `v1token` or `v2token`.
