### ISSUE TITLE
[Docs]: deployment_group route multiple listener error

### ISSUE THREAD

**Issue by myyrakle** [hashicorp/terraform-provider-aws#31243]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/4.66.0/docs/resources/codedeploy_deployment_group#listener_arns

### Description

The documentation says that you can put multiple listeners, but actually putting more than two will cause an error.

Below is the example code.
```
resource "aws_codedeploy_deployment_group" "deployment_group" {
  ...

  load_balancer_info {
    target_group_pair_info {
      prod_traffic_route {
        listener_arns = [aws_lb_listener.https_listener.arn, aws_lb_listener.http_listener.arn] // here
      }
  ...
```

When I run that code I get the following error.
```
Invalid Traffic Routing ConfigurationException: Production traffic route must have exactly one listener Arn
```
![image](https://user-images.githubusercontent.com/16988115/236623820-fc81b77c-a7e3-4021-9d84-eeb5e9afc6a1.png)

### Would you like to implement a fix?

None

**Comment by AdamJCavanaugh** [comment]
I don't see this example on the current documentation. Without digging too deeply into the code, API, or documentation, is this issue complete without this exact non-functional example on the documentation?
