### ISSUE TITLE
[Enhancement]: AWS Network Firewall - Support for policy variables

### ISSUE THREAD

**Issue by taharah** [hashicorp/terraform-provider-aws#31249]
### Description

AWS introduced policy variables for Network Firewall policies in order to allow setting the `HOME_NET` to be able to use of the managed rules when deployed in a centralized inspection VPC.

### Affected Resource(s) and/or Data Source(s)

* aws_networkfirewall_firewall_policy

### References

[AWS Network Firewall now supports Suricata HOME_NET variable override](https://aws.amazon.com/about-aws/whats-new/2023/05/aws-network-firewall-suricata-home-net-variable-override/)

### Would you like to implement a fix?

None

**Comment by ddericco** [comment]
I can work on this.
