### ISSUE TITLE
[New Service]: AWS Codecatalyst 

### ISSUE THREAD

**Issue by stefenAMZ** [hashicorp/terraform-provider-aws#31286]
### Description

Hi,

I am writing to request support for AWS Code Catalyst resources in Terraform. Currently, there is no support for Code Catalyst resources in Terraform, which makes it difficult to use Terraform to manage Code Catalyst projects.

Code Catalyst is a service that helps developers build, test, and deploy cloud applications more quickly and easily. It provides a number of features that can be helpful for Terraform users, such as:

    A centralized repository for storing Terraform modules and configurations
    A built-in CI/CD pipeline for testing and deploying Terraform code
    A set of tools for managing Terraform state

I believe that adding support for Code Catalyst resources to Terraform would be a valuable addition to the Terraform ecosystem. It would make it easier for Terraform users to take advantage of the features that Code Catalyst provides.

I would be happy to help with the development of this feature. Please let me know if you have any questions.

Thank you,
Stefen Orban

### Requested Resource(s) and/or Data Source(s)

aws_codecatalyst_Project
aws_codecatalyst_Space
aws_codecatalyst_AccessToken
aws_codecatalyst_SourceRepositoryBranch
aws_codecatalyst_DevEnvironment

### Potential Terraform Configuration

```terraform
resource "aws_codecatalyst_space" "default" {
  name = "Terraform CodeCatalyst"
  account_id = "111122223333"
}

resource "aws_codecatalyst_project" "default" {
  name = "My Terraform Project"
  space_id = aws_codecatalyst_space.default.id
}

resource "aws_codecatalyst_repo" "default" {
  name = "My Terraform Repository"
  project_id = aws_codecatalyst_project.default.id
  url = "https://github.com/my-username/my-terraform-repo"
}

resource "aws_codecatalyst_environment" "default" {
  name = "My Terraform Environment"
  project_id = aws_codecatalyst_project.default.id
  repo_id = aws_codecatalyst_repo.default.id
  compute_type = "t3.medium"
  memory = 512
  instance_count = 1
}
```

### References

go reference: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/codecatalyst
sdk reference: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-codecatalyst/

### Would you like to implement a fix?

None

**Comment by markoskandylis** [comment]
Thanks for raising this issue we will start working on it :)

**Comment by nrajb** [comment]
@ewbankkit just wanted to check as this issue listed other resources for CodeCatalyst and #32366 addressed DevEnvironment only, should we create different issue for other resources?

**Comment by nrajb** [comment]
Hi @ewbankkit @justinretzolk 3 PRs ready for review 🙏 
#32883
#32886
#32899

FYI: @markoskandylis

**Comment by ewbankkit** [comment]
@nrajb Thanks 👏.
When those 3 are merged can we close this Issue?

**Comment by stefenAMZ** [comment]
This is great thanks everyone

**Comment by nrajb** [comment]
> @nrajb Thanks 👏. When those 3 are merged can we close this Issue?

Yes, Thank you! will create new issue if/when we have new resources/datasource under this Service.
