### ISSUE TITLE
[Bug]: Unable to enable Inspector on both organization administratative account and member account since 4.66.0

### ISSUE THREAD

**Issue by HughNobleWonde** [hashicorp/terraform-provider-aws#31307]
### Terraform Core Version

1.4.6

### AWS Provider Version

4.66.0,4.66.1

### Affected Resource(s)

aws_inspector2_enabler

### Expected Behavior

Inspector to be enabled for org admin account and member accounts.

As of 4.66.0 you get a validation error when attempting to enable AWS Inspector for both the administrative account and other accounts within the organisation.

Previously this worked and AWS handles the configuration so it appears to be a logic issue with the resource. This was introduced with [this commit](https://github.com/hashicorp/terraform-provider-aws/commit/5c2095f5c7eb30712785fd63044747206d682bf6).

### Actual Behavior

Fails to plan with a validation error since 4.66.0.

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: 1 error occurred:
│ 	* "account_ids" can contain either the administrator account or one or more member accounts. Contains [xxxx xxxx]
```

### Terraform Configuration Files

```terraform
resource "aws_inspector2_enabler" "aws_inspector_config" {
  account_ids    = var.account_list
  resource_types = ["ECR"]
}
```

### Steps to Reproduce

Use the `aws_inspector2_enabler` resource to enable Inspector for an organization admin account and a member account.

### Would you like to implement a fix?

None

**Comment by gdavison** [comment]
Thanks for submitting this, @HughNobleWonde. The underlying AWS API supports either enabling on the administrator account or one or more member accounts. When creating the resource with an administrator account and a member account, the API returns an error. Did you enable Inspector manually and `import` the resource?

**Comment by HughNobleWonde** [comment]
Good question @gdavison. It's been a while since we set up Inspector, but there's a good chance that's exactly what we did. We'll look to split it out into a couple of resources instead.
