### ISSUE TITLE
[Enhancement]: Support .net7 managed runtimes for aws_lambda_function

### ISSUE THREAD

**Issue by dogfish182** [hashicorp/terraform-provider-aws#31332]
### Description

'dotnet7' runtime is supported by aws as per  
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

however attempting to use this runtime will result in

```
Error: expected runtime to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x nodejs16.x java8 java8.al2 java11 python2.7 python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 dotnet6 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2 nodejs18.x python3.10 java17], got dotnet7

```

### Affected Resource(s) and/or Data Source(s)

aws_lambda_function

### Potential Terraform Configuration

```terraform
resource "aws_lambda_function" "dotnetSevenFunction" {
  filename      = "dotnetSevenFunction.zip"
  function_name = "dotnetSevenFunction"
  role          = aws_iam_role.dotnetSevenFunction.arn
  runtime       = "dotnet7"
  handler       = "dotnetSevenFunction::dotnetSevenFunction.Function::FunctionHandler"
  architectures = ["x86_64"]
}
```

### References

https://github.com/hashicorp/terraform-provider-aws/issues/28152

### Would you like to implement a fix?

No

**Comment by mattburgess** [comment]
Hi @dogfish182. According to the [docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/build-dotnet7.html#build-dotnet7-prerequisites) and the [api](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/lambda@v1.34.1/types#Runtime), a .NET 7 runtime options isn't available so you have to use the `provided.al2` runtime option. As this [blog post] explains, there's no Lambda managed runtime for .NET 7 as it isn't a Long Term Support (LTS) release.

**Comment by dogfish182** [comment]
Ah apologies I did not understand the page I linked correctly it seems, closing this. Thanks for responding.

**Comment by mattburgess** [comment]
No problem, I don't understand that page either - that list of runtimes has no correlation with the (presumably only) valid values you can pick from the console. I'll leave some feedback with AWS to see if it can be improved at all.

**Comment by mikucat0309** [comment]
There is a tutorial in [AWS compute blog](https://aws.amazon.com/blogs/compute/building-serverless-net-applications-on-aws-lambda-using-net-7/). Maybe its .NET 7 = .NET 7 Native AOT.
