### ISSUE TITLE
[Enhancement]: `aws_pipes_pipe` - Support self managed kafka as a source

### ISSUE THREAD

**Issue by aaronleo28** [hashicorp/terraform-provider-aws#31330]
### Description

On the AWS EventBridge console you can configure a pipe to connect to a Self Managed Apache Kafka instance as a source. You can then choose an authentication type and specify a credentials secret in Secrets Manager so you can successfully connect to a private topic.

As far as I'm aware, this same functionality is not available in the TF `aws_pipes_pipe` resource.

### Affected Resource(s) and/or Data Source(s)

aws_pipes_pipe

### Potential Terraform Configuration

```terraform
resource "aws_pipes_pipe" "example" {
  depends_on = [aws_iam_role_policy.source, aws_iam_role_policy.target]
  name       = "example-pipe"
  role_arn   = aws_iam_role.example.arn
  source     = aws_sqs_queue.source.arn
  target     = aws_sqs_queue.target.arn

  source_parameters {
    self_managed_event_source {
      endpoints = {
        KAFKA_BOOTSTRAP_SERVERS = var.kafka_bootstrap_server
      }
    }

    source_access_configuration {
      type = "BASIC_AUTH"
      uri  = data.aws_secretsmanager_secret.kafka_credentials_secret.arn
    }
  }

  target_parameters {}
}
```

### References

https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-pipes-kafka.html

### Would you like to implement a fix?

None

**Comment by jordanfinners** [comment]
This should be fixed by https://github.com/hashicorp/terraform-provider-aws/issues/28153#issuecomment-1516898932

**Comment by aaronleo28** [comment]
@jordanfinners Thanks for the quick work!
