### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by davidhiebert** [hashicorp/terraform-provider-aws#31344]
### Terraform Core Version

1.4.6

### AWS Provider Version

4.66.1

### Affected Resource(s)

* aws_route_table (data source)
* aws_route_tables (data Source)

### Expected Behavior

A filtered data source would return the documented resource details for one or more (depending on plurality of data source) matching route tables.

### Actual Behavior

AWS API is returning the following error:
```
Error: reading EC2 VPC Route Table: OperationNotPermitted: Unpaginated and unqualified requests are not permitted.
```

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: reading EC2 VPC Route Table: OperationNotPermitted: Unpaginated and unqualified requests are not permitted.
│ 	status code: 400, request id: 9e2b1d1a-ffd9-469e-9884-aee03f15d7c9
│ 
│   with module.tgw.data.aws_route_table.each["subnet-0818b07926ccdeaac"],
│   on modules/tgw/data.tf line 12, in data "aws_route_table" "each":
│   12: data "aws_route_table" "each" {
│ 

```

```
╷
│ Error: error reading EC2 Route Tables: OperationNotPermitted: Unpaginated and unqualified requests are not permitted.
│ 	status code: 400, request id: 777ea82d-40d7-41f1-a984-6151fd556b00
│ 
│   with module.tgw.data.aws_route_tables.this,
│   on modules/tgw/data.tf line 1, in data "aws_route_tables" "this":
│    1: data "aws_route_tables" "this" {
│ 
╵
```

### Terraform Configuration Files

```terraform
data "aws_route_table" "each" {
  for_each = toset(data.aws_subnets.this.ids)

  subnet_id = each.value
}
```

```terraform
data "aws_route_tables" "this" {
  vpc_id = var.vpc_id

  filter {
    name   = "tag:Name"
    values = ["private*"]
  }
}
```

### Steps to Reproduce

Simply create a data source with a matching vpc id, filter and/or tags and try to apply or plan.  I was also able to reproduce this with aws cli.

This fails:

```shell
aws --region us-east-1 ec2 describe-route-tables --filters 'Name=vpc-id,Values=<vpc-id>'
```

This succeeds:

```shell
aws --region us-east-1 ec2 describe-route-tables --filters 'Name=vpc-id,Values=<vpc-id>' --page-size 5
```

### Important Factoids

This seems to simply be an issue with the AWS API now requiring a maximum number of responses per page be specified.  This option is not available in either affected resource.

### Would you like to implement a fix?

None

**Comment by sousmangoosta** [comment]
@davidhiebert I was not able to reproduce this issue, do you still have it ?
Do you have a large number of route tables ?

**Comment by davidhiebert** [comment]
We have 28 routing tables in this account.  Yes, problem still exists.  Below is the response I just got:

```
╷
│ Error: reading EC2 Route Tables: OperationNotPermitted: Unpaginated and unqualified requests are not permitted.
│ 	status code: 400, request id: 4ac95719-3f43-47fc-870e-f109770050e1
│ 
│   with data.aws_route_tables.this,
│   on test.tf line 1, in data "aws_route_tables" "this":
│    1: data "aws_route_tables" "this" {
│ 
╵

```

Below is the data source I used:
```
data "aws_route_tables" "this" {
  vpc_id = data.aws_vpc.this.id

  filter {
    name   = "tag:Name"
    values = ["private*"]
  }
}
```

**Comment by davidhiebert** [comment]
This appears to be something specific to our AWS Account.  Will investigate further with AWS Support.

**Comment by sousmangoosta** [comment]
> This appears to be something specific to our AWS Account. Will investigate further with AWS Support.

Ok thanks, I created 200 route tables and still working, great, thanks for the feedback.
