### ISSUE TITLE
[Enhancement]: Support the shared account in aws_db_cluster_snapshot

### ISSUE THREAD

**Issue by GwonsooLee** [hashicorp/terraform-provider-aws#31359]
### Description

I found that the [aws_db_snapshot](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_snapshot supports `shared_accounts` but aws_db_cluster_snapshot doesn't.

It would be better if aws+db+cluster_snapshot supports `shared_accounts` as well.
Please let me know if I know this wrong. :) 

### Affected Resource(s) and/or Data Source(s)

* aws_db_cluster_snapshot

### Potential Terraform Configuration

```terraform
resource "aws_db_cluster_snapshot" "example" {
  db_cluster_identifier          = aws_rds_cluster.example.id
  db_cluster_snapshot_identifier = "resourcetestsnapshot1234"
  shared_accounts = ["111111111111", "222222222222"]
}
```

### References

- https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-share-snapshot.html

### Would you like to implement a fix?

Yes

**Comment by Paulius0112** [comment]
Hi. Is there any update on this issue?
