### ISSUE TITLE
[Bug]: Launching a i3en or im4gn instance

### ISSUE THREAD

**Issue by shokeeb-yaqub-vcc** [hashicorp/terraform-provider-aws#31353]
### Terraform Core Version

1.4.6

### AWS Provider Version

v4.66.1

### Affected Resource(s)

Tried with two storage backed instance types and they fail to launch with the following message:

```shell
│ Error: creating EC2 Instance: UnsupportedOperation: The instance configuration for this AWS Marketplace product is not supported. Please see the AWS Marketplace site for more information about supported instance types, regions, and operating systems.
```

Using the latest ami: "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"

I am able to launch an instance manually using the same configuration.

In my terraform I tried a few different settings but even with the basic settings I get the same error:

```terraform
resource "aws_instance" "ec2" {
  ami           = "ami-0e4a5294cfbcfd79d"
  instance_type = "i3en.3xlarge"   
  subnet_id              = var.Subnet_ID_Secondary
}
```

Tested on eu-west-1

### Expected Behavior

Instance to be created

### Actual Behavior

```shell
│ Error: creating EC2 Instance: UnsupportedOperation: The instance configuration for this AWS Marketplace product is not supported. Please see the AWS Marketplace site for more information about supported instance types, regions, and operating systems.
```

### Relevant Error/Panic Output Snippet

```shell
│ Error: creating EC2 Instance: UnsupportedOperation: The instance configuration for this AWS Marketplace product is not supported. Please see the AWS Marketplace site for more information about supported instance types, regions, and operating systems.
```

### Terraform Configuration Files

```terraform
resource "aws_instance" "ec2" {
  ami           = "ami-0e4a5294cfbcfd79d"
  instance_type = "i3en.3xlarge"   
  subnet_id              = var.Subnet_ID_Secondary
}
```

### Steps to Reproduce

terraform apply

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @shokeeb-yaqub-vcc 👋 Thank you for taking the time to raise this! So that we have the necessary information in order to look into this, can you supply debug logs (redacted as needed) as well?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
