### ISSUE TITLE
[Bug]: EMR aws_emr_instance_fleet tries to modify a deleted resource and fails when emr was manually terminated.

### ISSUE THREAD

**Issue by capuchon-dev** [hashicorp/terraform-provider-aws#31375]
### Terraform Core Version

1.2.8

### AWS Provider Version

4.67.0

### Affected Resource(s)

aws_emr_instance_fleet

### Expected Behavior

When an EMR with an attached Instance Fleet terminates for a reason or another (failure, end of steps, manual termination from the console or CLI), it also terminates the Instance Fleet. This is the AWS imposed behavior. There is no API to delete an Instance Fleet, when created, its lifecycle is attached to the one of the EMR cluster. This is also written in the AWS Provider documentation for `aws_emr_instance_fleet`.

So when we re-create the same EMR with a `terraform apply`, we expect the AWS provider to know this rule and not trying to modify the no-more existing Instance Fleet.

### Actual Behavior

Until May, 10 2023, this was working perfectly as expected since months everyday (we have a CI/CD that do that).

Then, on May, 11, the same Terraform code, with the same Terraform version and the same AWS Provider fails because it tries to modify the Instance Fleet on `terraform apply`, and this Instance Fleet does not exists anymore because it was destroyed by the preceding cluster "terminate". We suspect that something changed on AWS side because nothing changed on Terraform side. Perhaps it reveals an always-existing bug that was not visible before.

The behavior is systematic and easy to reproduce : provision an EMR cluster and an Instance Fleet (for TASKS) on this EMR with Terraform. Then terminate the EMR from the console/cli/api/whatever. Then re-do a `terraform apply`. The provider tries to modify the Instance Fleet, but it does not exists anymore. The whole `apply` then fails. We think the provider should not fail if the resource does not exists anymore.

Also, the error occurs during a "Destroying" step of the Instance Fleet, which is an impossible action (there is no API to destroy an Instance Fleet). The only actions that exists on an Instance Fleet in the API are: add, modify, list. When created, the lifecycle depends on the EMR cluster on which it is attached. So "destroy" on this resource should be a no-op.

### Relevant Error/Panic Output Snippet

```shell
aws_emr_instance_fleet.emr-task-fleet: Destroying... [id=if-18V3MU5UCXJGI]
╷
│ Error: deleting EMR Instance Fleet (if-18V3MU5UCXJGI): InvalidRequestException: A job flow that is shutting down, terminated, or finished may not be modified.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "495707fb-97ae-425a-afde-74284d8a91d2"
│   },
│   ErrorCode: "INVALID_JOB_SHUT_DOWN",
│   Message_: "A job flow that is shutting down, terminated, or finished may not be modified."
│ }
│ 
│ 
╵
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```

### Terraform Configuration Files

Provisioning an EMR is very long, this requires a lot of resources... And our code is full of specific (unsharable) variables and stack dependencies. We currently have no bandwidth to produce a minimal context independent stack.

### Steps to Reproduce

* Provision a `aws_emr_cluster` and a `aws_emr_instance_fleet` attached to it with Terraform.
* Terminate the EMR cluster with the console, CLI or API.
* Re-apply the same Terraform : it fails because the no more existing resources try to be modified.

### Important Factoids

This was working perfectly until May, 10. Then since May, 11, it fails without any change on Terraform, provider or code. Something may have changed on AWS side, however, AWS Provider should be aware of the special Instance Fleet lifecycle and should behave accordingly (if the emr does not exists anymore, the Instance Fleet does not exists also).

To bypass the problem, we currently cleanup the state by removing the Instance Fleet with a `terraform state rm aws_emr_instance_fleet.emr-task-fleet`. Then we can `apply` successfully.

### Would you like to implement a fix?

No

**Comment by mebuffet** [comment]
Unfortunately the same happened to us, in our pipeline, performing the workaround, even the same, in case of failure of the execution of the job in CI/CD, the automatic removal of the state of the resource (aws_emr_instance_fleet.task).
Terraform version: 1.4.2
AWS provider version: 4.59.0

**Comment by atsalolikhin-spokeo** [comment]
I opened a case with AWS EMR Support and referenced this issue; support escalated the case to the EMR service team and they say nothing changed on their side:

> I have checked with our internal team and principal engineer in the team who has confirmed that there has been made no changes in the EMR side which would result in the above error message as such the error is completely from Terraform side. It can be seen that when re-running "terraform apply" commmand it is sending "ModifyInstanceFleet" api call to EMR cluster for already terminated instance fleet resulting in the error message. The expectations is that if we launch an EMR cluster using terraform script, we have to manage the cluster completely using terraform so that terraform knows current state of the cluster. In our case, we are using terraform to create the cluster but we are terminating it from EMR console due to which terraform would not have information about cluster being already terminated. 

In any case, this will have to be fixed on the Terraform side. Terraform should not try to destroy a task instance fleet seemingly attached to a non-existent cluster.

**Comment by joelthompson** [comment]
Seems like the error message changed as there's existing code to ignore a slightly different error message for precisely this same issue: https://github.com/hashicorp/terraform-provider-aws/blob/f1fca0829fa5108f45a6da8d963ca2e658075701/internal/service/emr/instance_fleet.go#L332-L334

**Comment by Quixotical** [comment]
Also may be worth noting that this issue does not arise with instance groups, just fleets.

I was fighting this issue for most of a day then decided for the short term I would just go with instance groups if they do not have this issue. Switched over to them and verified that they are able to build/destroy/rebuild without error.

So anyone suffering from this issue, if you have the ability to do so and it doesn't violate any of your infra requirements, it might be worthwhile switching to instance groups until this is resolved.

**Comment by garzaa** [comment]
Thanks, this was driving me insane.
