### ISSUE TITLE
[Enhancement]: Support Opensearch domains with standby config

### ISSUE THREAD

**Issue by moritzzimmer** [hashicorp/terraform-provider-aws#31373]
### Description

Support new _Multi-AZ with Standby_ deployment option for AWS Opensearch domains, seems like this is already available in the aws-sdk (see link below).

### Affected Resource(s) and/or Data Source(s)

* aws_opensearch_domain

### Potential Terraform Configuration

```terraform
vpc_options {
// probably here
}
```

### References

* [aws docs](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/managedomains-multiaz.html#managedomains-za-standby)
* [aws sdk](https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.44.262/service/opensearchservice#ClusterConfig.SetMultiAZWithStandbyEnabled)

### Would you like to implement a fix?

No

**Comment by mikekinlock** [comment]
Hey there, from my point of view this seems to be a great entry level contribution issue to work on, just a side note, this would be my first time contributing to Terraform, so I still have to go through the contribution guide and get familiar with your processes. Never the less I would like to raise my hand 🤚 and would like to work on it.

**Comment by mikekinlock** [comment]
Hey there I would need some support, I've create the changes in my local and it seems that it's working fine but I'm not able to push my feature-branch because I'm lacking permissions. Who can provide me the needed permissions for my user to be able to push my changes and create a Pull-Request. I've requested the slack access as well, but I'm still waiting for a response.

**Comment by seanturner026** [comment]
Hey @mikekinlock you'll need to fork the repository and create your branch on the fork

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
