### ISSUE TITLE
[Enhancement]: Add support for tags on AWS IOT RoleAlias and Policy

### ISSUE THREAD

**Issue by nlangowitz** [hashicorp/terraform-provider-aws#31415]
### Description

These two resources have AWS support for tags, but there is no tag argument on the Terraform resource, while other IOT Core resources including aws_iot_topic_rule and aws_iot_thing_group do support a `tags` argument

### Affected Resource(s) and/or Data Source(s)

* aws_iot_role_alias
* aws_iot_policy

### References

https://docs.aws.amazon.com/iot/latest/apireference/API_CreatePolicy.html
https://docs.aws.amazon.com/iot/latest/apireference/API_CreateRoleAlias.html
https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiot.html#awsiot-resources-for-iam-policies

### Would you like to implement a fix?

None

**Comment by fatbasstard** [comment]
Want this!
