### ISSUE TITLE
[Enhancement]: Increase `aws_grafana_workspace` timeout

### ISSUE THREAD

**Issue by daviduash** [hashicorp/terraform-provider-aws#31422]
### Description

Increase aws_grafana_workspace timeout (currently 10m)

### Affected Resource(s) and/or Data Source(s)

```shell
│ Error: waiting for Grafana Workspace (g-db6adfa26d) create: timeout while waiting for state to become 'ACTIVE' (last state: 'CREATING', timeout: 10m0s)
│ 
│   with aws_grafana_workspace.amg_workspace,
│   on grafana-amg.tf line 84, in resource "aws_grafana_workspace" "amg_workspace":
│   84: resource "aws_grafana_workspace" "amg_workspace" {
```

### Would you like to implement a fix?

Yes

**Comment by bschaatsbergen** [comment]
@daviduash I'm happy to prep a fix for this, I noticed you added 'yes' to the 'Would you like to implement a fix?' question, but I'm also happy to do so.
