### ISSUE TITLE
r/aws_acm_certificate failing with `expected validation_method to be one of [EMAIL DNS], got NONE` for imported certificate

### ISSUE THREAD

**Issue by msvbhat** [hashicorp/terraform-provider-aws#31425]
### Terraform Core Version

1.4.4

### AWS Provider Version

4.67.0

### Affected Resource(s)

aws_acm_certificate

### Expected Behavior

The `validation_method = "NONE"` should be a valid value when certificate is imported first into ACM and then this resource is imported to Terraform.

### Actual Behavior

When using `aws_acm_certificate` for imported certificate, `validation_method` can be set to NONE. But this fails with error

```
Error: expected validation_method to be one of [EMAIL DNS], got NONE
```

### Terraform Configuration Files

```terraform
resource "aws_acm_certificate" "cert" {
  domain_name       = "testing.custom-example.com"
  validation_method = "NONE"
}
```

### Steps to Reproduce

* Create a certificate and Import it into ACM manually (outsider of Terraform)
* Now import the ACM resource into Terraform using `terraform import` command.
* Run `terraform plan` to check diff with above resource.

### Would you like to implement a fix?

Yes

**Comment by sousmangoosta** [comment]
@msvbhat
The validation_method `NONE` is not supported anymore, and it's optional.

I did a test by creating an auto-signed certificate, by just removing the validation method it works.

So only the documentation need to be modified.

```
resource "aws_acm_certificate" "cert" {
  domain_name       = "testing.custom-example.com"
}

data "aws_acm_certificate" "cert" {
  domain   = "testing.custom-example.com"
  types = ["IMPORTED"]
  key_types = ["EC_prime256v1"]
}

output "test_cert" {
  value = data.aws_acm_certificate.cert.status
}
```

The output is now :

```
$ terraform plan
data.aws_acm_certificate.cert: Reading...
aws_acm_certificate.cert: Refreshing state... [id=arn:aws:acm:eu-west-1:1234567890:certificate/XXXXX]
data.aws_acm_certificate.cert: Read complete after 0s [id=arn:aws:acm:eu-west-1:1234567890:certificate/XXXXX]

Changes to Outputs:
  + test_cert = "ISSUED"

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply" now.
$
```

**Comment by msvbhat** [comment]
@sousmangoosta Hmm, AWS SDK doesn't support NONE value. As far as I can tell only Terraform supported this until last release. 

This is a special case when the certificate is first import into ACM and then imported into Terraform using `terraform import`. We have such a certificate and when imported the validation method is set to `NONE`. 

As far as I can tell this change was caused by #31296  and in particular this change. https://github.com/hashicorp/terraform-provider-aws/pull/31296/files#diff-e06b2008ab68b9431fa44c86f4a9e419710065f5a4553b0e3187f972fd887152L226

**Comment by sousmangoosta** [comment]
> @sousmangoosta Hmm, AWS SDK doesn't support NONE value. As far as I can tell only Terraform supported this until last release.
> 
> This is a special case when the certificate is first import into ACM and then imported into Terraform using `terraform import`. We have such a certificate and when imported the validation method is set to `NONE`.
> 
> As far as I can tell this change was caused by #31296 and in particular this change. https://github.com/hashicorp/terraform-provider-aws/pull/31296/files#diff-e06b2008ab68b9431fa44c86f4a9e419710065f5a4553b0e3187f972fd887152L226

Hmmm ok , yeah you right, the `certificateValidationMethodNone` disappeared in this change.
But do we need to keep this hack ?

**Comment by msvbhat** [comment]
@sousmangoosta Yeah, I think we can live without this.

When I first import the certificate into ACM manually and then import into Terraform the provider automatically sets `validation_method = "NONE"` in the state. So as long as we don't specify `validation_method` in the resource OR when `validation_method=null` provider doesn't throw error and works as expected. 

But if `validation_method = "NONE"` is set in the `aws_acm_certificate` resource throws the error. So it should be Okay as long as resource documentation is updated not to set this value in the special case.
