### ISSUE TITLE
[Bug]: Provider registry.terraform.io/hashicorp/aws produced an unexpected new value (aws_ecr_registry_scanning_configuration)

### ISSUE THREAD

**Issue by Drozdzufka** [hashicorp/terraform-provider-aws#31423]
### Terraform Core Version

1.4.6

### AWS Provider Version

4.67.0

### Affected Resource(s)

aws_ecr_registry_scanning_configuration

### Expected Behavior

Terraform should apply changes in rules to the given repository.

### Actual Behavior

Exits with an error during apply.

### Relevant Error/Panic Output Snippet

```shell
aws_ecr_registry_scanning_configuration.some_name: Modifying... [id=xxxx]
| Error: Provider produced inconsistent result after apply                                                                                                                                                                                   │ When applying changes to aws_ecr_registry_scanning_configuration.some_name, provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected new value: Root resource was present, but now absent.
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Terraform Configuration Files

```terraform
resource "aws_ecr_registry_scanning_configuration" "test" {
  scan_type = "ENHANCED"

  rule {
    scan_frequency = "SCAN_ON_PUSH"
    repository_filter {
      filter      = "*"
      filter_type = "WILDCARD"
    }
  }

  rule {
    scan_frequency = "CONTINUOUS_SCAN"
    repository_filter {
      filter      = "example"
      filter_type = "WILDCARD"
    }
  }
}
```

### Steps to Reproduce

1. Import aws_ecr_registry_scanning_configuration according to [docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_registry_scanning_configuration)
2. Add multiple rules like in the docs' [example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_registry_scanning_configuration#multiple-rules)
3. Run terraform apply

### Debug Output

```
[DEBUG] provider.terraform-provider-aws_v4.67.0_x5: HTTP Request Sent: http.request.header.x_amz_date=20230516T091715Z tf_req_id=<some_id> tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2@v2.0.0-beta.26/logger.go:90 http.flavor=1.1 http.request_content_length=2 tf_resource_type=aws_ecr_registry_scanning_configuration http.user_agent="APN/1.0 HashiCorp/1.0 Terraform/1.4.6 (+https://www.terraform.io) terraform-provider-aws/4.67.0 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go/1.44.261 (go1.19.8; linux; amd64)" @module=aws aws.sdk=aws-sdk-go http.method=POST http.request.body={} http.request.header.content_type=application/x-amz-json-1.1 http.url=https://api.ecr.eu-west-1.amazonaws.com/ net.peer.name=api.ecr.eu-west-1.amazonaws.com http.request.header.x_amz_target=AmazonEC2ContainerRegistry_V20150921.GetRegistryScanningConfiguration aws.operation=GetRegistryScanningConfiguration aws.region=eu-west-1 aws.service=ECR http.request.header.authorization="<some_header>" http.request.header.x_amz_security_token=<some_token> tf_mux_provider=*schema.GRPCProviderServer tf_provider_addr=registry.terraform.io/hashicorp/aws timestamp=2023-05-16T09:17:15.281+0200
[DEBUG] provider.terraform-provider-aws_v4.67.0_x5: HTTP Response Received
[ERROR] vertex "aws_ecr_registry_scanning_configuration.<some_name>" error: Provider produced inconsistent result after apply
[DEBUG] states/remote: state read serial is: some_line; serial is: some_serial
[DEBUG] states/remote: state read lineage is: some_line; lineage is: some_line
```

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_registry_scanning_configuration#multiple-rules

### Would you like to implement a fix?

None

**Comment by sousmangoosta** [comment]
@rozdzynski I cannot reproduce that issue, the only thing I can see is when we remove all rules or the last rule it send a body with `http.request.body={"scanType":"ENHANCED"}` so the API do not remove the rules.

So on the next run got a warning :

```
[WARN]  Provider "registry.terraform.io/hashicorp/aws" produced an unexpected new value for aws_ecr_registry_scanning_configuration.test during refresh.
      - .rule: actual set element cty.ObjectVal(map[string]cty.Value{"repository_filter":cty.SetVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"filter":cty.StringVal("*"), "filter_type":cty.StringVal("WILDCARD")})}), "scan_frequency":cty.StringVal("SCAN_ON_PUSH")}) does not correlate with any element in plan
      - .rule: block set length changed from 0 to 1
```

or with the 2 rules block

```
2023-05-17T15:41:24.999+0200 [WARN]  Provider "registry.terraform.io/hashicorp/aws" produced an unexpected new value for aws_ecr_registry_scanning_configuration.test during refresh.
      - .rule: actual set element cty.ObjectVal(map[string]cty.Value{"repository_filter":cty.SetVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"filter":cty.StringVal("*"), "filter_type":cty.StringVal("WILDCARD")})}), "scan_frequency":cty.StringVal("SCAN_ON_PUSH")}) does not correlate with any element in plan
      - .rule: actual set element cty.ObjectVal(map[string]cty.Value{"repository_filter":cty.SetVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"filter":cty.StringVal("example"), "filter_type":cty.StringVal("WILDCARD")})}), "scan_frequency":cty.StringVal("CONTINUOUS_SCAN")}) does not correlate with any element in plan
      - .rule: block set length changed from 0 to 2
```

To fix that I removed locally the [if nil return nil](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ecr/registry_scanning_configuration.go#L136-L138)

With this change it send `http.request.body={"rules":[],"scanType":"ENHANCED"}` and it receive `http.response.body={"registryId":"1234567890","scanningConfiguration":{"rules":[],"scanType":"ENHANCED"}}`

I don't know if it's link to your issue but I will open a PR for that.

Do you have any other information on the status you had on the registry before your apply ?

**Comment by rozdzynski** [comment]
Hmm, your case seems different. Tried to provide steps again to reproduce exactly what i'm doing if i missed something.
The registry have "Enhanced scanning configuration" enabled with "*" filter.
1. I run `aws ecr get-registry-scanning-configuration --no-cli-pager --output text --query "registryId"` to get id of the registry.
2. Copy code from the documentation paragraph "Multiple rules". Comment "scan on push" rule
3. Run `terraform init`, then `terraform import aws_ecr_registry_scanning_configuration.test id_from_awscli`
4. `terraform plan` do not produce any difference
5. Uncomment rule "scan on push"
6. `terraform apply`

Today when i was doing it for the first time got an error again. Tried 2nd&3rd time and works perfectly. Changes applies, even when juggling rules multiple times...
If not reproducible by anyone else, maybe that's not the case to investigate.

**Comment by sousmangoosta** [comment]
I tried again 3 times in same order and cannot reproduce it.
I'm really confused 😕
