### ISSUE TITLE
[Docs]: aws_lambda_event_source_mapping - enabled descriptions is not clear

### ISSUE THREAD

**Issue by joselitofilho** [hashicorp/terraform-provider-aws#31433]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping#enabled

### Description

The current description of the `enabled` argument is not clear:

- [`enabled`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping#enabled) - (Optional) Determines if the mapping will be enabled on creation. Defaults to `true`.

It suggests that the mapping will be enabled by default when it is created. However, if we set this up to `false` the mapping will be disabled, otherwise, will be (re)enabled.

My suggestion is to rewrite the description to:

- [`enabled`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping#enabled) - (Optional) Whether the mapping should be enabled (defaults to `true`).

### Would you like to implement a fix?

None

**Comment by AdamJCavanaugh** [comment]
I'm not sure I understand the difference between the current wording (mapping will be enabled) versus what you say happens (mapping is re-enabled)? The actual API documentation states:

> When true, the event source mapping is active. When false, Lambda pauses polling and invocation.

If any change were to be made, I would suggest we use this wording. However, I don't see a lack of clarity to require such an update. Can you help by providing an example of the difference/confusion?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you still feel that the documentation is unclear, please feel free to open a new issue, referencing this one for context as needed.
