### ISSUE TITLE
[Enhancement]: Support Placement Group for AWS Batch Compute Environment Resource

### ISSUE THREAD

**Issue by rileyhun** [hashicorp/terraform-provider-aws#31457]
### Description

We would like to do multi-node parallel batch jobs using AWS Batch, and it would be nice to be able to use placement groups with the `aws_batch_compute_environment`.  The advantage of a placement group in this context is that instances are placed in close proximity for improved network performance and reduced latency, and this is necessary for distributed and parallel computing workloads. This is supported when creating a compute environment from the AWS Console, but seems to be missing in the terraform aws provider. 

### Affected Resource(s) and/or Data Source(s)

* aws_batch_compute_environment

### Potential Terraform Configuration

```terraform
resource "aws_batch_compute_environment" "this" {
  placement_group = aws_placement_group.pg.id
}
```

### Would you like to implement a fix?

None

**Comment by bruceadowns** [comment]
I am putting together a PR today on this issue.

The solution will look like:

```
resource "aws_placement_group" "sample" {
  name     = "sample-placement-group"
  strategy = "cluster"
}

resource "aws_batch_compute_environment" "sample" {
  compute_environment_name = "sample"

  compute_resources {
    instance_role = aws_iam_instance_profile.ecs_instance_role.arn
    instance_type = ["optimal"]

    max_vcpus = 1
    placement_group = aws_placement_group.sample.name
...
```
