### ISSUE TITLE
[Enhancement]: Adding a region for aws_cloudwatch_log_destination

### ISSUE THREAD

**Issue by ramses999** [hashicorp/terraform-provider-aws#31454]
### Description
Terraform does not allow you to specify a region for the "destination" of cloudwatch group AWS

Through the AWS CLI I can do this for example with the following command:

`aws logs put-destination --destination-name "Try2FirehoseDestination" --target-arn "arn:aws:firehose:eu-central-1:222222222222
1:deliverystream/kinesis-firehose-to-splunk" --role-arn "arn:aws:iam::111111111111:role/CloudWatchToSplunkFirehoseTrust" --region "us-east-1"`

Please note that I create a destination in the region **"us-east-1"**, and subscribe to Firehose, which is located in a completely different region **"eu-central-1"**.

When I try to add the undocumented field  `region = "us-east-1" ` to the resource ["aws_cloudwatch_log_destination"](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_destination), I get an error when executing `Error: Unsupported argument
│
│   on main.tf line xxx, in resource "aws_cloudwatch_log_destination" "mydestination":
│  478:   region = "us-east-1"`

### Affected Resource(s) and/or Data Source(s)

cloudwatch_log_destination

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_destination

### Would you like to implement a fix?

None

**Comment by mattburgess** [comment]
From your description/AWS cli command it looks to me like the equivalent Terraform would be to have multiple providers configured, one for each region you need to target. You'd create the firehose delivery stream in us-east-2 and the cloudwatch log destination in eu-central-1 e.g.:

```
provider "aws" {
  region = "us-east-1"
}

provider "aws" {
  region = "eu-central-1"
  alias  = "eu-central-1"
}

resource "aws_iam_role" "example" {
  name = "CloudWatchToSplunkFirehoseTrust"
  ...
}

resource "aws_kinesis_firehose_delivery_stream" "example" {
  provider    = aws.eu-central-1
  name        = "kinesis-firehose-to-splunk"
  destination = "splunk"
  ...
}

resource "aws_cloudwatch_log_destination" "example" {
  name       = "Try2FirehoseDestination"
  role_arn   = aws_iam_role.example.arn
  target_arn = aws_kinesis_firehose_delivery_stream.example.arn
}
```

**Comment by ramses999** [comment]
@mattburgess 
Thank you for your comment, but it did not become clear to me how to correctly change the region from which operations are performed.

I call this code as a module inside terragrant and get the error:

`╷
│ Error: Duplicate provider configuration
│
│   on main.tf line 1:
│    1: provider "aws" {
│
│ A default (non-aliased) provider configuration for "aws" was already given
│ at _providers.tf:2,1-15. If multiple configurations are required, set the
│ "alias" argument for alternative configurations.`

But if I leave the alias I get a runtime error that the test message was not delivered.

It seems that you need to create different providers and completely change the architecture of the code, but what if I want to execute this code in 10+ regions at once?
