### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by omabdulrasheed** [hashicorp/terraform-provider-aws#31461]
### Terraform Core Version

0.12

### AWS Provider Version

3.74.3,4.14.0,4.3

### Affected Resource(s)

AWS Lambda function upgrade to Graviton CPU fails with an Error: Provider produced inconsistent final plan

### Expected Behavior

Successfully complete the terraform apply.

### Actual Behavior

Failure with error Error: Provider produced inconsistent final plan

### Relevant Error/Panic Output Snippet

```shell
+ terraform apply -auto-approve '-input=false'
module.authentication_lambda.data.aws_vpc.vpc: Refreshing state...
module.authentication_lambda.data.aws_s3_bucket.lambda_function_source: Refreshing state...
module.authentication_lambda.data.aws_security_group.nbc_elasticache_sg: Refreshing state...
module.authentication_lambda.data.aws_security_group.vpc_endpoints: Refreshing state...
module.authentication_lambda.aws_security_group.lambda_sg: Refreshing state... [id=sg-07cf6b6ddb9803955]
data.aws_caller_identity.current: Refreshing state...
module.authentication_lambda.aws_security_group_rule.allow_dns_udp_outbound: Refreshing state... [id=sgrule-2773581]
module.authentication_lambda.aws_security_group_rule.allow_outbound: Refreshing state... [id=sgrule-144083268]
module.authentication_lambda.aws_s3_bucket_object.lambda_function_archive: Refreshing state... [id=authentication-lambda]
module.authentication_lambda.aws_security_group_rule.allow_vpc_endpoints_outbound: Refreshing state... [id=sgrule-2279387441]
module.authentication_lambda.aws_security_group_rule.allow_inbound_to_Redis_cache_from_lambda: Refreshing state... [id=sgrule-586182849]
module.authentication_lambda.aws_security_group_rule.allow_outbound_to_Redis_cache: Refreshing state... [id=sgrule-4152151321]
module.authentication_lambda.aws_s3_bucket_object.lambda_function_archive: Modifying... [id=authentication-lambda]
module.authentication_lambda.aws_s3_bucket_object.lambda_function_archive: Modifications complete after 1s [id=authentication-lambda]

Error: Provider produced inconsistent final plan

When expanding the plan for
module.authentication_lambda.aws_lambda_function.lambda_function_with_graviton[0]
to include new values learned so far during apply, provider
"registry.terraform.io/-/aws" produced an invalid new value for
.source_code_hash: was cty.StringVal("c6bc1a757b2128606604d19af83fcb2d"), but
now cty.StringVal("17afbfe7b8a4244a86594eeac736f803-6").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Terraform Configuration Files

Jenkinsfile that runs terraform:

global:
  appCode: nbc
  jenkinsAgent: AWS-Dev
  projectCheckErrorLevel: 3

awsSession:
  envName: cma-dev

artifactory:
  groupId: com.comerica.nbc
  archiveId: nbc-authentication-lambda
  version: 3.0.3
  extension: jar
  fileName: lambda-function.jar
  repository: releases
  command: Download

terraform:
  envModuleDir: nbc/terraform/env/
  envModule: dev/lambda/authentication/create-authentication-lambda
  dockerVersion: 1.5.2

### Steps to Reproduce

Run the Jenkins job in our Dev environment that runs terraform apply to upgrade the AWS Lambda with Graviton CPU.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @omabdulrasheed 👋 Thank you for taking the time to raise this! So that we have the information we need in order to investigate this, can you supply a sample Terraform configuration as well as debug logs (redacted as needed)?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
