### ISSUE TITLE
Need to cache info when building new environment.

### ISSUE THREAD

**Issue by clerskine** [hashicorp/terraform-provider-aws#3149]
As an improvement request.

We build an environment where we create a set of AWS instances by combining scripts and using counts within an aws_instance block.  In our case, we use the same AMI for all the instances that we are creating.  Doing a trace of the output in 1.7.1, it looks like a request is made to get the details of the AMI for every instance created.

This information should be requested once and the used for all requests using that ami.

**Comment by bflad** [comment]
Hi @clerskine! This is certainly a valid enhancement request. Terraform's backend model as it exists today is to handle each resource (and associated data/operations) in its dependency graph independently. I should probably point out that this request is related, but not fully equivalent to the "batching" API requests of #2553.

For your case specifically, does your `aws_instance` configuration currently utilize the `root_block_device` attribute? Briefly looking at the resource code, it seems if you can get rid of that usage then the `ec2.DescribeImage` calls will go away if they're really causing trouble (its used to fetch the root device name of the AMI).

**Comment by clerskine** [comment]
We are using the root_block_device since we have to change the size root device for the different instances.  There is a bug in the root_device code also since it looks like it is parsing the blockDeviceMapping to find the root device name rather than using the stanza.  See [https://github.com/terraform-providers/terraform-provider-aws/issues/3138](url)

**Comment by clerskine** [comment]
Keeping this open
