### ISSUE TITLE
Remove `AWSClient.S3ConnURICleaningDisabled`

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#31501]
https://github.com/aws/aws-sdk-go/pull/4832 deprecates the AWS SDK for Go v1 `config.DisableRestProtocolURICleaning`, used by `AWSClient.S3ConnURICleaningDisabled`.
Remove this custom S3 API client.

Relates https://github.com/hashicorp/terraform-provider-aws/pull/31474.

**Comment by ewbankkit** [comment]
Remove suppression added in https://github.com/hashicorp/terraform-provider-aws/pull/31502.

**Comment by aajtodd** [comment]
NOTE: This change was reverted in v1.44.267 as it introduced a breaking change. We do not recommend using v1.44.265 or v1.44.266 that contain this change.
