### ISSUE TITLE
[Enhancement]: Support nodejs18.x as a compatible runtime for aws_lambda_layer_version

### ISSUE THREAD

**Issue by MukundMohanan** [hashicorp/terraform-provider-aws#31510]
### Description

AWS now supports [nodejs18.x as a compatible runtime for lambda](https://docs.aws.amazon.com/lambda/latest/dg/API_PublishLayerVersion.html#SSS-PublishLayerVersion-request-CompatibleRuntimes). Request is to allow [aws_lambda_layer_version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_layer_version) to pass nodejs18.x as a compatible runtime in [publish_layer_version](https://docs.aws.amazon.com/lambda/latest/dg/API_PublishLayerVersion.html#SSS-PublishLayerVersion-request-CompatibleRuntimes).

Using terraform version:
```bash
terraform --version
Terraform v1.3.6
```

and aws provider:
```terraform
source  = "hashicorp/aws"
version = "~> 4.20.0"
```

Currently terraform errors with:
`Error: expected compatible_runtimes.0 to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x nodejs16.x java8 java8.al2 java11 python2.7 python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 dotnet6 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2], got nodejs18.x`

### Affected Resource(s) and/or Data Source(s)

```terraform
resource "aws_lambda_layer_version" "lambda_layer" {
  filename            = data.archive_file.layer.output_path
  layer_name          = var.lambda_packages_layer_name
  source_code_hash    = data.local_file.nodejs_package.content_base64sha256
  compatible_runtimes = ["nodejs18.x"]
  description         = "Packages layer"
}
```

### References

- [AWS Lambda layer creation now supports runtime nodejs18.x](https://docs.aws.amazon.com/lambda/latest/dg/API_PublishLayerVersion.html#SSS-PublishLayerVersion-request-CompatibleRuntimes)
- [AWS Lambda creation supports runtime nodejs18.x](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-Runtime)

### Would you like to implement a fix?

None

**Comment by trevorrea** [comment]
Support was added in 4.41.0 so you'll have to upgrade your provider version. 

See https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#4410-november-25-2022

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/27923.
