### ISSUE TITLE
[Enhancement]: aws memorydb for redis IAM authentication support

### ISSUE THREAD

**Issue by david1437** [hashicorp/terraform-provider-aws#31528]
### Description

Allow iam authentication support for aws memorydb

### Affected Resource(s) and/or Data Source(s)

resource aws_memorydb_user
data aws_memorydb_user

### Potential Terraform Configuration

```terraform
resource "aws_memorydb_user" "example" {
  user_name     = "my-user"
  access_string = "on ~* &* +@all"

  authentication_mode {
    type      = "IAM"
  }
}
```

### References

![image](https://github.com/hashicorp/terraform-provider-aws/assets/25678781/bbad17f8-bc1b-4e69-a169-248c5b14a71c)

### Would you like to implement a fix?

No

**Comment by exoego** [comment]
Hi. I've opened a PR for this https://github.com/hashicorp/terraform-provider-aws/pull/32027
