### ISSUE TITLE
[Bug]: AppSync Keeps complaining about API Key

### ISSUE THREAD

**Issue by yunxi-zhang** [hashicorp/terraform-provider-aws#31537]
### Terraform Core Version

1.3.7

### AWS Provider Version

4.37.0 or 4.67.0

### Affected Resource(s)

Context:
Used aws_appsync_graphql_api and aws_appsync_api_key to setup the appsync and api key for the 1st time successfully. After manually deleting the AppSync Service and run the same TF scripts again, it keeps showing error in the plan stage.

The error is: `error getting Appsync API Key "4oi7mwwf6barbfpt35zsxplnwq:da2-5aqaharf6jh6hlloapk25etb34": NotFoundException: GraphQL API 4oi7mwwf6barbfpt35zsxplnwq not found.`

The issue remains regardless of commenting out the aws_appsync_api_key or adding dependency in aws_appsync_api_key on aws_appsync_graphql_api. 

This issue occurs even when changing the authentication method to AWS_IAM in aws_appsync_graphql_api.

### Expected Behavior

AppSync should be created without an API key if aws_appsync_api_key  is not given.

### Actual Behavior

Giving the same error in the plan stage, can't setup App Sync

### Terraform Configuration Files

```terraform
resource "aws_iam_role_policy_attachment" "aws_appsync_push_to_cloudwatch_logs" {
  role       = aws_iam_role.appsync_access_aws_services.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSAppSyncPushToCloudWatchLogs"
}

resource "aws_appsync_graphql_api" "zero_zero_one" {
  authentication_type = "API_KEY"
  name                = "appsync001"

#   schema = <<EOF
# schmea {
#   query: Query
# }

# type Query {
#   test: Int
# }
# EOF

  log_config {
    cloudwatch_logs_role_arn = aws_iam_role.appsync_access_aws_services.arn
    field_log_level          = "ALL"
  }

  tags = local.tags
}

//Setup An API Key for AppSync
resource "aws_appsync_api_key" "zero_zero_one" {
  api_id  = aws_appsync_graphql_api.zero_zero_one.id
  expires = "2024-05-21T00:00:00Z"
}
```

### Steps to Reproduce

See context

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @yunxi-zhang 👋 Thank you for taking the time to raise this! So that we have the necessary information in order to look into this, can you supply debug logs (redacted as needed)?

**Comment by yunxi-zhang** [comment]
Found the root cause, forgot to delete remote tfstate in cloud, not an issue anymore.
