### ISSUE TITLE
[Docs]: Missing character in `aws_api_gateway_integration` Lambda example

### ISSUE THREAD

**Issue by fxlui** [hashicorp/terraform-provider-aws#31552]
### Documentation Link

http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-control-access-using-iam-policies-to-invoke-api.html

### Description

In the [Lambda integration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_integration#lambda-integration) of Example usage, the `source_arn` field is missing a slash character:
`source_arn = "arn:aws:execute-api:${var.myregion}:${var.accountId}:${aws_api_gateway_rest_api.api.id}/*/${aws_api_gateway_method.method.http_method}`**/**`${aws_api_gateway_resource.resource.path}"
`

### References

https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-control-access-using-iam-policies-to-invoke-api.html#api-gateway-calling-api-permissions

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Closing this out due to the follow up comment on https://github.com/hashicorp/terraform-provider-aws/pull/31579.
