### ISSUE TITLE
[Bug]: admin_create_user_config configuration block unused_account_validity_days argument not being omitted 

### ISSUE THREAD

**Issue by elize-dolina** [hashicorp/terraform-provider-aws#31553]
### Terraform Core Version

1.3.9

### AWS Provider Version

3.76.1

### Affected Resource(s)

aws_cognito_user_pool

### Expected Behavior

admin_create_user_config configuration block unused_account_validity_days argument should not be in my terraform state file since I have never used admin_create_user_config configuration block unused_account_validity_days argument. I have been using password_policy configuration block temporary_password_validity_days argument from the very start.

### Actual Behavior

admin_create_user_config configuration block unused_account_validity_days argument is showing in terraform state file even though never used before.

### Relevant Error/Panic Output Snippet

```shell
[31m│[0m [0m[0mError decoding "aws_cognito_user_pool.user_pool" from previous state:
[31m│[0m [0munsupported attribute "unused_account_validity_days"
[31m╵[0m[0m
[31m╷[0m[0m
```

### Terraform Configuration Files

```terraform
resource "aws_cognito_user_pool" "user_pool" {
  name = var.pool_name

  password_policy  {
    minimum_length                   = 8
    require_lowercase                = true
    require_numbers                  = true
    require_symbols                  = true
    require_uppercase                = true
    temporary_password_validity_days = 90
  }

  schema {
    attribute_data_type      = "String"
    developer_only_attribute = false
    mutable                  = true
    name                     = "role"
    required                 = false

    string_attribute_constraints  {
      min_length = 1
      max_length = 256
    }
  }

  schema {
    attribute_data_type      = "String"
    developer_only_attribute = false
    mutable                  = true
    name                     = "last_login"
    required                 = false

    string_attribute_constraints {
      max_length = 50
    }
  }

  username_attributes = ["email"]

  admin_create_user_config {

    allow_admin_create_user_only = true
    invite_message_template {
      email_subject = "Subject"
      sms_message   = "sms message"
      email_message = "email message"
    }
  }

  email_configuration {
    reply_to_email_address = var.reply_to_email_address
    source_arn             = "arn:aws:ses:us-east-1:${local.account_id}:identity/${var.reply_to_email_address}"
    email_sending_account  = "DEVELOPER"
  }

  tags = local.tags

  lambda_config {
    custom_message = aws_lambda_function.cognito_lambda_trigger.arn
  }

  lifecycle {
    ignore_changes = [
      tags.ResourceCreatedBy,
      tags.Name
    ]
  }
}
```

### Steps to Reproduce

terraform apply

### References

I know that this is an old bug and it was supposedly fixed in aws provider v2.49.0.

https://github.com/hashicorp/terraform-provider-aws/issues/11858

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @elize-dolina 👋 Thank you for taking the time to raise this! So that we have the information necessary in order to investigate this, can you supply debug logs (redacted as needed) as well?
