### ISSUE TITLE
[Enhancement]: Add support for AWS SDK retry mode

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#31569]
### Description

The AWS SDK for Go v2 supports two retry modes: Standard and Adaptive.

Add a parameter `retry_mode` to the provider configuration block. Should also support the environment variable `AWS_RETRY_MODE` and the shared configuration file parameter `retry_mode`

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/aws-sdk-go-base/issues/147.

**Comment by gdavison** [comment]
Closed by #31745
