### ISSUE TITLE
New Data Source: aws_ecr_pull_through_cache_rule

### ISSUE THREAD

**Issue by vincentclee** [hashicorp/terraform-provider-aws#31578]
### Description

Returns the pull through cache rules for a registry.

My use case is to have terraform check if the pull through cache rule has been setup for `quay.io`, then switch my ECS cluster pulling from `quay.io/rockylinux/rockylinux:9` to pull from the Amazon ECR repository URI `1484931600.dkr.ecr.us-east-1.amazonaws.com/quay.io/rockylinux/rockylinux:9`

### Requested Resource(s) and/or Data Source(s)

* aws_ecr_pull_through_cache_rule

### Potential Terraform Configuration

```terraform
data "aws_ecr_pull_through_cache_rule" "example" {
    ecr_repository_prefix = "quay"
}
```

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/21951
* https://docs.aws.amazon.com/cli/latest/reference/ecr/describe-pull-through-cache-rules.html

### Would you like to implement a fix?

None

**Comment by bschaatsbergen** [comment]
Thank you for raising this issue @vincentclee, I'll happily pick it up 👍🏼
