### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by princeanire** [hashicorp/terraform-provider-aws#31591]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/xray_sampling_rule

### Description

Resource: aws_xray_sampling_rule example usage 

the aws provider documentation gave an example usage for aws_xray_sample_rule resource however terraforms complain about incorrect priority setting when copy and pasting the example resource terraform will output the following error. 

│ Error: expected priority to be in the range (1 - 9999), got 10000
│
│   with aws_xray_sampling_rule.example,
│   on xray.tf line 13, in resource "aws_xray_sampling_rule" "example":
│   13:   priority       = 10000

to fix the error, the priority argument must be set within the range of 1 and 9999, excluding 10000.

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @princeanire 👋  Thank you for taking the time to raise this! I've opened a pull request to set the `priority` to `9999` in the example.
