### ISSUE TITLE
[Bug]: srarted getting Database instance is not in available state

### ISSUE THREAD

**Issue by speller** [hashicorp/terraform-provider-aws#31594]
### Terraform Core Version

1.3.7

### AWS Provider Version

5.0.0

### Affected Resource(s)

rds db instance

### Expected Behavior

Created/updated successfully

### Actual Behavior

I started getting errors on the code that I didn't change last couple on months:

```none
│ Error: updating RDS DB Instance (rev-f-8392-items-cou-m220230526064809808900000008): InvalidDBInstanceState: Database instance is not in available state.
│ 	status code: 400, request id: 8c7b765e-bfc9-4f31-a70b-748cf592918f
│ 
│   with module.magento-db.aws_db_instance.app-db[0],
│   on .terraform/modules/magento-db/main.tf line 101, in resource "aws_db_instance" "app-db":
│  101: resource "aws_db_instance" "app-db" {
```

I have three databases in the deployment and all of them fail with this error.

### Terraform Configuration Files

-

### Steps to Reproduce

I'm creating databases restoring them from snapshots.

### Would you like to implement a fix?

None

**Comment by speller** [comment]
When I retry the deployment, I still always get the `Database instance is not in available state` error. This looks like a critical bug.

**Comment by speller** [comment]
When I try to roll back the provider version, it fails with the `Resource instance managed by newer provider version`...

**Comment by speller** [comment]
After rolling back the provider version and deleting and importing back database instances, our deployments working fine. Really weird issue with the new version.

**Comment by justinretzolk** [comment]
Hey @speller 👋 Thank you for taking the time to raise this, and for coming back with additional information. Are you able to supply debug logs (redacted as needed) so that we can take a look at this?

**Comment by YakDriver** [comment]
Sorry about this! I suspect some or all of this is related to the instance ID changing. When you upgrade from the provider v4 to v5, Terraform _should_ upgrade you from schema version 1 (of the RDS instance) to schema version 2. The only difference is with the ID. In version 1, the ID is the user-provided `identifier`. In version 2, the ID is the DBI resource ID (something along the lines of `db-T0H1IS23A4R5A6N7D8O9M0I1D`).

Somewhere, something may be going wrong with getting the ID where it belongs. If you look at the state (_e.g._, using `terraform state pull`), under `type` of `aws_db_instance`, `instances`, it will show the `schema_version`. You can also see the `id` and if it looks like a DBI resource ID (_should_ be equal to `resource_id`) or if `id` looks like `identifier`.

Assuming you're using the AWS provider v5, this could be a workaround. (WARNING: We don't suggest hand-jamming state as you can mess things up to where Terraform cannot manage your resources!) You could hand jam state by setting `schema_version` to `2`, set `id` to the same thing listed as `identifier`, and `id` as the same thing listed as `resource_id`.

This is a state excerpt:

```json
{
  "version": 4,
  "terraform_version": "1.4.6",
  "serial": 1,
  "lineage": "9689cba5-392d-42b5-ba31-0298a7148abe",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "aws_db_instance",
      "name": "test",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 2,
          "attributes": {
            "address": "timuldo.cy3ltbkfow2g.us-west-2.rds.amazonaws.com",
            "allocated_storage": 10,
            "arn": "arn:aws:rds:us-west-2:153029840061:db:timuldo",
            "db_name": "test",
            "engine": "mysql",
            "engine_version": "8.0.32",
            "engine_version_actual": "8.0.32",
            "id": "db-GP5SZKT7I6N3XUXS2ZDPWSI4AQ",
            "identifier": "timuldo",
            "instance_class": "db.t3.micro",
            "resource_id": "db-GP5SZKT7I6N3XUXS2ZDPWSI4AQ"
          },
          "sensitive_attributes": []
        }
      ]
    }
  ],
  "check_results": null
}
```

**Comment by t3hG04T** [comment]
@justinretzolk  We've also ran into this issue. It seems that provider is emitting an update request as soon as the DB is reported as created. Here is the failed CloudTrail event:

```json
{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "IAMUser",
        "principalId": "foo",
        "arn": "arn:aws:iam::foo:user/foo",
        "accountId": "foo",
        "accessKeyId": "foo",
        "userName": "foo"
    },
    "eventTime": "2023-06-09T14:52:17Z",
    "eventSource": "rds.amazonaws.com",
    "eventName": "ModifyDBInstance",
    "awsRegion": "eu-west-1",
    "sourceIPAddress": "redacted",
    "userAgent": "APN/1.0 HashiCorp/1.0 Terraform/0.12.31 (+https://www.terraform.io) terraform-provider-aws/5.1.0 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go/1.44.273 (go1.19.8; linux; amd64) exec-env/AWS_ECS_EC2",
    "errorCode": "InvalidDBInstanceStateFault",
    "errorMessage": "Database instance is not in available state.",
    "requestParameters": {
        "allowMajorVersionUpgrade": false,
        "dBInstanceIdentifier": "foo-identifier",
        "backupRetentionPeriod": 0,
        "masterUserPassword": "HIDDEN_DUE_TO_SECURITY_REASONS",
        "applyImmediately": true
    },
    "responseElements": null,
    "requestID": "foo-foo-foo-foo",
    "eventID": "foo-foo-foo-foo",
    "readOnly": false,
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "recipientAccountId": "foo",
    "eventCategory": "Management",
    "tlsDetails": {
        "tlsVersion": "TLSv1.2",
        "cipherSuite": "ECDHE-RSA-AES128-GCM-SHA256",
        "clientProvidedHostHeader": "rds.eu-west-1.amazonaws.com"
    }
}
```
And this is the operation we are trying to execute (and which is consistently failing every time since v5:

```terraform
resource "aws_db_instance" "database" {
  snapshot_identifier     = data.aws_db_snapshot.latest_prod_snapshot.id
  instance_class          = "db.t3.micro"
  identifier_prefix       = "${var.target_name}-"
  db_subnet_group_name    = aws_db_subnet_group.db-sg.id
  storage_encrypted       = true
  skip_final_snapshot     = true
  vpc_security_group_ids  = [aws_security_group.db-secgroup.id]
  password                = random_string.password.result
  backup_retention_period = 0
  tags                    = merge(var.tags, map("temporary", "true"))

  lifecycle {
    create_before_destroy = true
  }
}
```

Regarding your concerns about state @YakDriver : I see that `schema_version` in the state is `2`, then `id` is in the new format (so there is no issues with the upgrade, seems like it's a logic error).

Note: for this particular piece of core we are using terraform `0.12` (and because of the provider failing we are prevented from easily upgrading too).

**Comment by setop** [comment]
same with TF 1.5.0

**Comment by t3hG04T** [comment]
I tried to look for obvious reasons for the bug in the source code, but seems like the gist of the logic remains the same. The only difference is using the ID instead of the identifier. I presume AWS API responds faster to these, making the provider assume that the DB is in a ready state prematurely. Simplest change would be start querying by the identifier again in this particular method.

**Comment by johanneswuerbach** [comment]
I might have found the issue https://github.com/hashicorp/terraform-provider-aws/pull/32287 🎉, it seems to be related to using `identifier_prefix`, which some of the code snippets here also include.
