### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by goural** [hashicorp/terraform-provider-aws#31601]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/servicecatalog_product

### Description

Here in  **provisioning_artifact_parameters** it is given that type is optional value, however it is required value as without passing it the terraform throws error . 

terraform resource code -

```terraform
resource "aws_servicecatalog_product" "s3product" {
  name  = "Simple S3 bucket"
  owner = "IT"
  type  = "TERRAFORM_OPEN_SOURCE"
  provisioning_artifact_parameters {
    template_url = "template url here"
  }
  tags = var.tags
}
```

ERROR -
```shell
│ Error: creating Service Catalog Product: InvalidParametersException: The TERRAFORM_OPEN_SOURCE Product Type only supports the following ProvisioningArtifact Types: TERRAFORM_OPEN_SOURCE
│ 
│   with aws_servicecatalog_product.s3product,
│   on main.tf line 8, in resource "aws_servicecatalog_product" "s3product":
│    8: resource "aws_servicecatalog_product" "s3product" {
│ 
```

Document Ref -
[type](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/servicecatalog_product#type) - (Optional) Type of provisioning artifact. See [AWS Docs](https://docs.aws.amazon.com/servicecatalog/latest/dg/API_ProvisioningArtifactProperties.html) for valid list of values.

Code that works -

```terraform
resource "aws_servicecatalog_product" "s3product" {
  name  = "Simple S3 bucket"
  owner = "IT"
  type  = "TERRAFORM_OPEN_SOURCE"

  provisioning_artifact_parameters {
    template_url = "template url here"
    type                        = "TERRAFORM_OPEN_SOURCE"
  }

  tags = var.tags
}
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @goural 👋 Thank you for taking the time to raise this! I took a look at the [schema](https://github.com/hashicorp/terraform-provider-aws/blob/b9e8c729f2b6dacaa5a7a90e5fccdc8c9c59f4d2/internal/service/servicecatalog/product.go#L122-L127) and both the [AWS Go SDK documentation](https://docs.aws.amazon.com/sdk-for-go/api/service/servicecatalog/#ProvisioningArtifactProperties) and [AWS API documentation](https://docs.aws.amazon.com/servicecatalog/latest/dg/API_ProvisioningArtifactProperties.html), all of which point to this being an optional argument.

It appears this is one of those cases where it's required for some configurations, but not all. With that in mind, it appears that the documentation (and current schema behavior) are correct.
