### ISSUE TITLE
[Enhancement]: Add support for Custom keys and Count all rate-limiting criteria in WAF

### ISSUE THREAD

**Issue by lkoniecz** [hashicorp/terraform-provider-aws#31625]
### Description

Rate limiting only supports 2 out of 4 possible aggregation criteria:
https://registry.terraform.io/providers/hashicorp/aws/4.67.0/docs/resources/wafv2_web_acl#aggregate_key_type

### Affected Resource(s) and/or Data Source(s)

aws_wafv2_web_acl

### References

https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-statement-type-rate-based-aggregation-options.html

### Would you like to implement a fix?

None

**Comment by mldevpants** [comment]
We had a feature request with AWS for this, I stopped Nginx in favor of this feature, but I cannot do terraform for it.
The import works great BTW, but it cannot be applied since the provider does not recognize the CUSTOM_KEYS.

**Comment by cesarcelism** [comment]
> We had a feature request with AWS for this, I stopped Nginx in favor of this feature, but I cannot do terraform for it. The import works great BTW, but it cannot be applied since the provider does not recognize the CUSTOM_KEYS.

Besides the `aggregate_key_type`, also it needs to be explicit which will be the aggregate key. The SDK provides [RateBasedStatementCustomKey](https://docs.aws.amazon.com/waf/latest/APIReference/API_RateBasedStatementCustomKey.html) data type to achieve that.

**Comment by peter-hippo** [comment]
A workaround for now when creating a new resource is to do the WAF rule based upon "IP", terraform everything, then manually change to CUSTOM_KEYS + whatever settings, then updating the TF code to say "CUSTOM_KEYS" and there is no diff. It's not perfect but this way one can create the resource with TF and maintain the main lifecycle of it.

**Comment by matthewbae** [comment]
@peter-hippo how did you get around the errors when doing `terraform plan`? I see these errors:

```
Error: expected rule.1.statement.0.rate_based_statement.0.aggregate_key_type to be one of [IP FORWARDED_IP], got CUSTOM_KEYS
```

**Comment by matthewbae** [comment]
Thanks @sakaru. I'm on 4.3.0, so I'll give a bump to the latest version!

**Comment by luqmanMohammed** [comment]
Any ETA on the availability of this feature?
