### ISSUE TITLE
[Bug]: Failed to marshal plan to json, unsupported attribute "override_json"

### ISSUE THREAD

**Issue by kim0** [hashicorp/terraform-provider-aws#31637]
### Terraform Core Version

1.4.6

### AWS Provider Version

5.0.1

### Affected Resource(s)

Converting a saved plan file into json using `terraform show -json` results in this error
`Failed to marshal plan to json: error marshaling prior state: unsupported attribute "override_json"`

Downgrading to anything less than 5.0.0, and the same command works

### Expected Behavior

Plan is converted to json and displayed on the screen

### Actual Behavior

I get the error: `Failed to marshal plan to json: error marshaling prior state: unsupported attribute "override_json"`

### Terraform Configuration Files

Since terraform is not showing which TF code lines are causing this panic, it's not possible to show a snippet of the configs

### Steps to Reproduce

* Try to convert a saved plan file into json and it fails
* 

### Would you like to implement a fix?

None

**Comment by jvisker** [comment]
Maybe related to this change? https://github.com/hashicorp/terraform-provider-aws/issues/22906

**Comment by MaxymVlasov** [comment]
For some reason, `"override_json": null`, when it should be removed from the state

Example:

```json
{
  "version": 4,
  "terraform_version": "1.3.9",
  "serial": 13,
  "lineage": "fe5ffc8a-776c-9548-36c5-0b43c266ccb1",
  "outputs": {},
  "resources": [
    {
      "mode": "data",
      "type": "aws_iam_policy_document",
      "name": "assume_role",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "1642520416",
            "json": "",
            "override_json": null,
            "override_policy_documents": null,
            "policy_id": null,
            "source_json": null,
            "source_policy_documents": null,
            "statement": [],
            "version": "2012-10-17"
          },
          "sensitive_attributes": []
        }
      ]
    },
    {
      "mode": "data",
      "type": "aws_iam_policy_document",
      "name": "iam_access",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "4064693197",
            "json": "",
            "override_json": null,
            "override_policy_documents": null,
            "policy_id": null,
            "source_json": null,
            "source_policy_documents": null,
            "statement": [],
            "version": "2012-10-17"
          },
          "sensitive_attributes": []
        }
      ]
    },
...
```

**Comment by MaxymVlasov** [comment]
Workaround: to fix the state without state manipulations, you need change resources which had the `override_json` field and apply.

IE,
1. for `aws_iam_policy_document`, change `Sid`
2. Run `terraform apply`

**Comment by tomer-ds** [comment]
I have the same issue in TF 1.5.0 with AWS Provider 5.4.0

For me the workaround doesn't work because many of the aws_iam_policy_document data are managed by modules meaning a simple change of SID is not always possible

This is a sever issue and has already impacted a production workspace which seems now nigh on unrecoverable baring some drastic state manipulation 🫰

Any speedy progress would be greatly appreciated!

**Comment by carl-reverb** [comment]
I encountered this while trying to delete from state in Terraform Cloud. As a workaround, I had to first checkout the `main` branch version of my workspace, upgrade to AWS Provider 5, and `terraform state refresh` to fixup the state. Following that I was able to delete resources from state.

**Comment by Mukesh-Sharma-external** [comment]
Hi Team,
We are also facing same issue when running plan for specific resource or module.
Failed to marshal plan to json: error marshaling prior state: unsupported attribute "override_json"
Is there any fix or workaround anyone has for this issue.

**Comment by ferschubert** [comment]
In my case I have managed to make it work by:

- Upgrading providers, previously had AWS version 4.37.0, now on 5.31.0: `terraform init -upgrade`
- Performing a plan and apply - even without changes. In my case I had `"override_json": null` in state. After the upgrade these were gone and I could finish what I was trying to do - a state push.

**Comment by major0** [comment]
Seeing this very consistently when doing a `-target`'ed plan.

**Comment by muhamedkapoevolt** [comment]
I just got this issue

`Failed generating plan JSON
Exit code: 1

Failed to marshal plan to json: error marshaling prior state: unsupported attribute "override_json"
Operation failed: failed generating plan JSON: failed running command (exit 1)`

I have external modules, so Im not able to perform simple SID change. Is there any other way to fix this?

**Comment by muhamedkapoevolt** [comment]
> I just got this issue
> 
> `Failed generating plan JSON Exit code: 1
> 
> Failed to marshal plan to json: error marshaling prior state: unsupported attribute "override_json" Operation failed: failed generating plan JSON: failed running command (exit 1)`
> 
> I have external modules, so Im not able to perform simple SID change. Is there any other way to fix this?

Look like i fixed my issue with running plan+apply on 4.x provider with changed SID in all "aws_iam_policy_document" resources that I handle, get it back on 5.x and it worked!
