### ISSUE TITLE
[Bug]: Migrate aws_s3_object from provider 4 to 5 is not working at first apply

### ISSUE THREAD

**Issue by quentin9696** [hashicorp/terraform-provider-aws#31633]
### Terraform Core Version

1.4.6

### AWS Provider Version

5.0.1, 4.67.0

### Affected Resource(s)

aws_s3_object

### Expected Behavior

Nothing to do to upgrade from provider `4` to `5`

### Actual Behavior

Bump the provider version from `4` to `5` trigger a change in the plan: 
``` text
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_s3_object.this will be updated in-place
  ~ resource "aws_s3_object" "this" {
      - acl                    = "private" -> null
        id                     = "foo"
        tags                   = {}
        # (12 unchanged attributes hidden)
    }
```

And the apply trigger an error: 
```
│ Error: putting S3 object ACL: MissingSecurityHeader: Your request was missing a required header
│ 	status code: 400, request id: QWQSKETKTX6TYF1X, host id: oL9WH0HNofYSqyI0XuMi2wpFJsLmHU3kR05QGt0MUpxHW6OmInyCQy4OU0ocC75Tq7mk+ELV5L0pmWO8u6eoM4Kat5JYtIOumXwNGw3Qd2s=
│ 
│   with aws_s3_object.this,
│   on main.tf line 18, in resource "aws_s3_object" "this":
│   18: resource "aws_s3_object" "this" {
```

### Relevant Error/Panic Output Snippet

```shell
│ Error: putting S3 object ACL: MissingSecurityHeader: Your request was missing a required header
│ 	status code: 400, request id: XXXXXXX, host id: XXXXXXXXXXXXXX
│ 
│   with aws_s3_object.this,
│   on main.tf line 18, in resource "aws_s3_object" "this":
│   18: resource "aws_s3_object" "this" {


Apply a 2nd time will cause an `No changes. Your infrastructure matches the configuration.`
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.0, < 5"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_s3_bucket" "example" {
  bucket = "test-quentin9696"
}

resource "aws_s3_object" "this" {
  bucket = aws_s3_bucket.example.id
  key    = "foo"

  content_base64 = base64encode("Hello World")
  source_hash    = md5(base64encode("Hello World"))
}
```

### Steps to Reproduce

1. Using configuration above, `terraform init`
2. `terraform apply`
3. Change the provider version to pin the version 5 (update `version = ">= 4.0, < 5"` to `version = "> 5"`)
4. `terraform init -upgrade`
5. `terraform apply`
6. Get the error
7. `terraform apply`
8. Get the message `No changes. Your infrastructure matches the configuration.`

### Important Factoids

I think the provider should upgrade the state internally instead of waiting for the double update

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @quentin9696 👋 Thank you for taking the time to raise this! So that we have the information necessary to look into this, can you supply debug logs (redacted as needed) as well?

**Comment by Nuru** [comment]
This happens with first-time creation of an S3 bucket `aws_s3_bucket_acl` with `acl = null` and `access_control_policy` specifying grants, in both provider versions v4.67.0 and v5.5.0. It is not an upgrade problem.

**Comment by naomichi-y** [comment]
I have the same problem.
By adding `acl = private` to `aws_s3_object`, I was able to temporarily avoid it.
Just to be sure, I checked the ACL status with get-object-acl, but it doesn't seem to have changed.

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/27197.

**Comment by robinpecha** [comment]
Running `terraform apply` twice fixed this issue for me.

**Comment by tanerjn** [comment]
Any long term solution for this?

**Comment by grimm26** [comment]
> Any long term solution for this?

yes. https://github.com/hashicorp/terraform-provider-aws/issues/31633#issuecomment-1692415650
