### ISSUE TITLE
[Docs]: How to recognize if a key is a block and not an argument

### ISSUE THREAD

**Issue by islishude** [hashicorp/terraform-provider-aws#31631]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#example-usage

### Description

<img width="700" alt="image" src="https://github.com/hashicorp/terraform-provider-aws/assets/24730006/010daa9d-730e-4a50-96a2-2038a78ab096">

terraform lsp can recognize the origin key is a block, but the documentation doesn't have anything about it.

<img width="955" alt="image" src="https://github.com/hashicorp/terraform-provider-aws/assets/24730006/f478846f-e943-43a5-b10f-3dccacd5ca0c">

it says that all of the keys are argument.

I'm confused about it.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @islishude 👋 Thank you for taking the time to raise this! I'm not quite sure I follow the question here, but I'll try to explain the best I can based on what I've understood. If this doesn't address your question, I'm happy to continue the conversation.

In this case, the `origin` argument is a block that contains each of the arguments outlined in the [Origin Arguments](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#origin-arguments)section of the documentation (including `connection_attempts, `connection_timeout`, etc.) . As the `origin` argument's definition indicates, multiple `origin` blocks may exist at the top level of a `aws_cloudfront_distribution` resource.

Generally, the AWS Provider documentation will indicate when an argument is a block by linking to the section of the documentation that contains that block's arguments.
