### ISSUE TITLE
[Docs]: AWS Amplify - Access token for Github repository only works with classic tokens

### ISSUE THREAD

**Issue by eternaltyro** [hashicorp/terraform-provider-aws#31643]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/amplify_app

### Description

It is not immediately apparent, but AWS Amplify `access_token` seems to work only with Classic tokens (ones that start with `ghp_`) in Github but not fine-grained tokens. 

Can someone please confirm this behaviour and if true, the documentation needs to be updated to reflect that. 

### Would you like to implement a fix?

Yes

**Comment by epomatti** [comment]
Works for me. Can you update with what you're trying to do?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
