### ISSUE TITLE
[Docs]: db_cluster_parameter_group_name  has been removed from rds_cluster document

### ISSUE THREAD

**Issue by mitsuyuki418** [hashicorp/terraform-provider-aws#31650]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/5.0.1/docs/resources/rds_cluster

### Description

`db_instance_parameter_group_name` argument was removed from the `Resource: aws_rds_cluster` page.

I guess it might be removed by accident when solving merge conflicts.

It was removed in this commit.

https://github.com/hashicorp/terraform-provider-aws/commit/f04917944fcfbb2abe696978576a4a272c075af9#diff-9d869fc908da636b09ac45e62cd373de7223e04ab7a2279385d6ea31004fcbacL234a

It brought duplicated `db_cluster_instance_class` which was solved afterwards in this commit 

https://github.com/hashicorp/terraform-provider-aws/commit/6189ffef1f4164332c4ec1f4bd8af7a947e10ec4

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @mitsuyuki418 👋 Thank you for taking the time to raise this! It looks like the `db_instance_parameter_group_name` argument [is still documented](https://registry.terraform.io/providers/hashicorp/aws/5.0.1/docs/resources/rds_cluster#db_instance_parameter_group_name) ([latest documentation at time to writing](https://registry.terraform.io/providers/hashicorp/aws/5.1.0/docs/resources/rds_cluster#db_instance_parameter_group_name) to be thorough).

**Comment by mitsuyuki418** [comment]
Hi 👋  @justinretzolk , thank you for looking into this. I'm sorry, but I wrote a wrong parameter name.

It isn't `db_instance_parameter_group_name ` but `db_cluster_parameter_group_name` which is removed from the doc.  🙇

**Comment by tdharris** [comment]
I too am wondering where `db_cluster_parameter_group_name` went from the [aws_rds_cluster](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#db_instance_parameter_group_name) resource. It started to be missing from the [5.0.0](https://registry.terraform.io/providers/hashicorp/aws/5.0.0/docs/resources/rds_cluster) doc on the registry.
