### ISSUE TITLE
[New Resource]: aws_quicksight_analysis

### ISSUE THREAD

**Issue by comtef** [hashicorp/terraform-provider-aws#31666]
### Description

The `aws_quicksight_analysis` resource will allow practitioners to manage QuickSight Analysis via Terraform.

### Requested Resource(s) and/or Data Source(s)

aws_quicksight_analysis

### Potential Terraform Configuration

```terraform
resource "aws_quicksight_analysis" "example" {
  analysis_id = "example"
  name        = "example"
  source_entity {
    source_template {
      arn = aws_quicksight_template.example.arn
      data_set_references {
        data_set_arn         = aws_quicksight_data_set.example.arn
        data_set_placeholder = "1"
      }
    }
  }
}
```

### References

https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateAnalysis.html
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_UpdateAnalysis.html
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeAnalysis.html
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeAnalysisDefinition.html
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeAnalysisPermissions.html
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DeleteAnalysis.html

### Would you like to implement a fix?

None

**Comment by jar-b** [comment]
closed by #31542
