### ISSUE TITLE
[Bug]: Modifying aws_wafv2_web_acl removes DDoS auto mitigation

### ISSUE THREAD

**Issue by luarx** [hashicorp/terraform-provider-aws#31670]
### Terraform Core Version

v1.2.5

### AWS Provider Version

4.56.0

### Affected Resource(s)

aws_wafv2_web_acl 

### Expected Behavior

When I modify a rule from `aws_wafv2_web_acl` using `terraform apply`, it should not remove the ShieldMitigationRuleGroup 

### Actual Behavior

When I modify a rule from `aws_wafv2_web_acl` using `terraform apply`, it does not indicate that it will remove the ShieldMitigationRuleGroup as before **(https://github.com/hashicorp/terraform-provider-aws/issues/22869),** **but at the end it does it**! :(

So I consider that [this](https://github.com/hashicorp/terraform-provider-aws/issues/22869) is not fixed yet...

I suspect that it is because it tries to re-order, rules in someway

Example of terraform apply output that has removed `ShieldMitigationRuleGroup ` without indicating it:
```
  ~ resource "aws_wafv2_web_acl" "web_acl" {
        id          = "22dfeb14-1eab-41f0-b798-aaafcbff5b77"
        name        = "critical-rule"
        # (6 unchanged attributes hidden)

      - rule {
          - name     = "AWS-AWSManagedRulesAmazonIpReputationList" -> null
          - priority = 0 -> null

          - override_action {

              - none {}
            }

          - statement {

              - managed_rule_group_statement {
                  - name        = "AWSManagedRulesAmazonIpReputationList" -> null
                  - vendor_name = "AWS" -> null

                  - scope_down_statement {

                      - not_statement {
                          - statement {

                              - ip_set_reference_statement {
                                  - arn = "arn:aws:wafv2:us-east-1:1111111111:global/ipset/trusted-companies/aaaaaaaa-cd4a-4f91-b484-8c0df559d215" -> null
                                }
                            }
                        }
                    }
                }
            }

          - visibility_config {
              - cloudwatch_metrics_enabled = true -> null
              - metric_name                = "AWS-AWSManagedRulesAmazonIpReputationList" -> null
              - sampled_requests_enabled   = true -> null
            }
        }
      + rule {
          + name     = "AWS-AWSManagedRulesAmazonIpReputationList"
          + priority = 0

          + override_action {

              + none {}
            }

          + statement {

              + managed_rule_group_statement {
                  + name        = "AWSManagedRulesAmazonIpReputationList"
                  + vendor_name = "AWS"
                }
            }

          + visibility_config {
              + cloudwatch_metrics_enabled = true
              + metric_name                = "AWS-AWSManagedRulesAmazonIpReputationList"
              + sampled_requests_enabled   = true
            }
        }

        # (4 unchanged blocks hidden)
    }

```

### Terraform Configuration Files

*

### Steps to Reproduce

1. Create a `aws_wafv2_web_acl ` resource using Terraform
2. Add Shield L7 protection from the AWS Console (because terraform does not support it yet). It will a  `ShieldMitigationRuleGroup` rule
3. Modify a Terraform managed rule of the `aws_wafv2_web_acl ` resource
4. Execute `terraform apply` (it will not say that it will remove the Shield rule)
5. Check from the AWS Console that the Shield L7 rule has been removed :( 

### Would you like to implement a fix?

None

**Comment by MrHash** [comment]
Updating WAF should not remove the ShieldMitigationGroup rule. The WAF rules need to be read and merged in with mitigation rule before being applied.

**Comment by vini-mw** [comment]
i too am struggling with the very same issue.
there are no references of the ShieldMitigationGroup rule on the state change output yet applying rule modifications on the `aws_wafv2_web_acl` resource removes the shield group rule from it.

i got this using terraform version `1.5.4` and aws provider version `5.12.0`.
