### ISSUE TITLE
[Bug]: `terraform apply` failed to remove resource's tag from state

### ISSUE THREAD

**Issue by 44smkn** [hashicorp/terraform-provider-aws#31695]
### Terraform Core Version

1.4.6

### AWS Provider Version

5.0.1

### Affected Resource(s)

* aws_iam_role

### Expected Behavior

We removed `Environment` and `Product` of the resource's tags and moved them to `default_tags`.
`terraform plan` showed that they are removed from `tags` and added to `tags_all`.
We expected `terraform apply` to reflect that change to the state file.

Plan
```tf
  # aws_iam_role.sample will be updated in-place
  ~ resource "aws_iam_role" "sample" {
        id                    = "sample"
        name                  = "sample"
      ~ tags                  = {
          - "Environment" = "foo" -> null
            "ManagedBy"   = "Terraform"
          - "Product"     = "bar" -> null
        }
        # (11 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Actual Behavior

We found that `terraform apply` failed to remove resource's tag from the state file.
So, `terraform plan` always shows the deletion of the resource's tag.

### Relevant Error/Panic Output Snippet

```shell
None
```

### Terraform Configuration Files

```tf
resource "aws_iam_role" "sample" {
  name               = "sample"
  tags = {
    ManagedBy = "Terraform"
  }
}

locals {
  region         = "ap-northeast-1"
  environment    = "foo"
  product        = "bar"
}

provider "aws" {
  default_tags {
    tags = {
      Environment    = local.environment
      Product        = local.product
    }
  }
  region      = local.region
}
```

### Steps to Reproduce

I wonder if this can be reproduced when some keys are removed from tags when tags and default_tags declared.

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Because IAM has per-resource tagging functions rather than per-service, we cannot use the generic code in the tagging interceptor and these resources aren't getting the benefit of the `default_tags` work done in *v5.0.0*.

**Comment by nathanpreen** [comment]
Hey, I'm seeing this behaviour on several other resources also. Will list them below.
```
aws_kms_key
aws_security_group
aws_acm_certificate
aws_launch_template
```
