### ISSUE TITLE
[Enhancement]: Configure SES region for aws_cognito_user_pool email configuration

### ISSUE THREAD

**Issue by Viriathus1** [hashicorp/terraform-provider-aws#31694]
### Description

When sending emails through Cognito there's currently no option to set SES region through aws_cognito_user_pool.email_configuration in terraform. This can currently only be set manually in the console.

### Affected Resource(s) and/or Data Source(s)

aws_cognito_user_pool.email_configuration

### Potential Terraform Configuration

```terraform
resource "aws_cognito_user_pool" "example" {

  email_configuration = {
    ses_region = data.aws_region.current.name
    source_arn = "${local.default_email_source_arn}"
    reply_to_email_address = "${local.default_email_from_address}"
    from_email_address = "ExampleCompany <no-reply@examplecompany.com>"
    email_sending_account = "DEVELOPER"
  }
}
```

### References

![image](https://github.com/hashicorp/terraform-provider-aws/assets/49337323/452a975b-3564-4dbd-8a5c-bdf10bfd8f33)

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
@Viriathus1 It seems that the region selection in the console is to help fetch the list of FROM email addresses. The selection would form the the `SourceArn` that gets passed to the [underlying API](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_EmailConfigurationType.html), for example:

`"sourceArn": "arn:aws:ses:us-east-1:123456789012:identity/myname@mycompany.com"`

Thus you should be able to change the region that's part of the `source_arn` argument in the `email_configuration` block. Please give it a try and update/close this ticket accordingly. Thanks.
