### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by KlockiLego** [hashicorp/terraform-provider-aws#31704]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#argument-reference

### Description

This tag was only used by Amazon EKS. You can remove the tag without impacting your services. It's not used with clusters that are version 1.15 or later.

[subnet_ids](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#subnet_ids) – (Required) Identifiers of EC2 Subnets to associate with the EKS Node Group. These subnets must have the following resource tag: kubernetes.io/cluster/CLUSTER_NAME (where CLUSTER_NAME is replaced with the name of the EKS Cluster).

### References

https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html

If you created a cluster with Kubernetes 1.14 or earlier, Amazon EKS added the following tag to your VPC:

Key	Value
kubernetes.io/cluster/my-cluster	owned

This tag was only used by Amazon EKS. You can remove the tag without impacting your services. It's not used with clusters that are version 1.15 or later.

### Would you like to implement a fix?

None

**Comment by KlockiLego** [comment]
Wrong reference
Correct one on the bottom: When a Kubernetes cluster that's version 1.18 and earlier was created, Amazon EKS added the following tag to all of the subnets that were specified....

**Comment by justinretzolk** [comment]
Hey @KlockiLego 👋 Thank you for taking the time to raise this! I've opened a documentation pull request to remove reference to that tag.
