### ISSUE TITLE
Replace usages of `actions-ecosystem/action-remove-labels` GitHub action

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#31717]
The `actions-ecosystem/action-remove-labels` GitHub action uses Node 12 which [soon will not be supported](https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/).
Replace our usage of this action.

See https://github.com/hashicorp/terraform-provider-azurerm/pull/22007 for an alternative.

**Comment by justinretzolk** [comment]
I've got a couple of ideas cooking around this; I'll work on prioritizing that so we can get moved over.
