### ISSUE TITLE
RDS: aws_db_instance not assigning custom parameter_group_name

### ISSUE THREAD

**Issue by hitesh-dev19** [hashicorp/terraform-provider-aws#31719]
### Terraform Core Version

Terraform v1.4.0 on darwin_arm64

### AWS Provider Version

4.67.0

### Affected Resource(s)

aws_db_instance

### Expected Behavior

Trying to create Cross Region Replica for Oracle RDS Instance

### Actual Behavior

I am trying to create the cross region replica for Oracle RDS Instance providing custom parameter_group_name, but still it is getting assigned to default parameter group, eventually it is failing with the error , `Error: waiting for RDS DB Instance (******) create: unexpected state 'incompatible-parameters', wanted target 'available, storage-optimization'.` , and when I try to reapply terraform changes, it is showing that the changes for parameter group with the custom one, then it is deleting that instance and creating new instance again with the same default parameter group. 

### Terraform Configuration Files

```terraform
resource "aws_db_instance" "test-replica" {
   identifier             = "mytestinstance"
   replicate_source_db    = "arn:aws:rds:us-east-1:****"
   instance_class         = "db.m5.xlarge"
   apply_immediately      = true
   publicly_accessible    = false
   skip_final_snapshot    = true
   vpc_security_group_ids = [data.aws_security_group.static.id]
   parameter_group_name   = "custom-parameter-group"
   storage_encrypted = true
   iam_database_authentication_enabled = true
   iops = 1000
   tags = {
    Application = "test -replica"
   }
}
```

### Steps to Reproduce

terraform plan

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @hitesh-dev19 👋 Thank you for taking the time to raise this! I did a bit of looking around, and I believe this may be a configuration issue rather than a bug within the provider. I'll link the most relevant documents that I found below.

- [Viewing instance status and recommendations](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/accessing-monitoring.html#Overview.DBInstance.Status)
- [How can I fix an Amazon RDS DB instance that is stuck in the incompatible-parameters status?](https://repost.aws/knowledge-center/rds-incompatible-parameters)

**Comment by hitesh-dev19** [comment]
Hi justinretzolk,
Thanks for the reply, my point is though I am giving the custom parameter group the new replica is still getting attached to default parameter group.

**Comment by justinretzolk** [comment]
Hey @hitesh-dev19 -- I see where you're coming from now. So that we have the relevant information in order to be able to look into this, can you supply debug logs (redacted as needed) as well?

**Comment by hitesh-dev19** [comment]
Hey @justinretzolk , I can refer my issue is very similar to the same issue https://github.com/hashicorp/terraform-provider-aws/issues/218 but there  a subsequent terraform apply changes parameter_group_name to the correct value and do an RDS reboot to apply it too.
But for me  subsequent terraform plan this diff is evident with the correct parameter group, but when I apply it, it is destroying the replica which was created before and recreating new one with the same default parameter group.

**Comment by hitesh-dev19** [comment]
Hello @justinretzolk Did you get a chance to look at my request, let me know if you need more info regarding this.
Thanks

**Comment by hitesh-dev19** [comment]
Hey @justinretzolk ,
I have noticed one more thing that the resource is getting tainted that is the reason it is getting destroyed and recreate all the time with the same default parameter group.
So I have untainted the resource and reapply the same so then the `parameter_group_name` got updated but it required manual reboot to get that applied.

So now its happening in the same way like https://github.com/hashicorp/terraform-provider-aws/issues/218 , but that issue has been resolved in the past but that doesn't look that way.

Can you please confirm this. thanks.

**Comment by hitesh-dev19** [comment]
Hello @justinretzolk ,

I have noticed that with the latest terraform aws provider version update v5.0.0, the oracle replica resource is still failing with the same error `Error: waiting for RDS DB Instance (******) create: unexpected state 'incompatible-parameters', wanted target 'available, storage-optimization'.` But with this latest update the creates resource is not there in the terraform state .
In earlier versions the resource is in taint state at-least which helped to create resource manually . This time it is not the case.
Could you please help me with my case or let me know If I am missing anything.
Thanks.

**Comment by hitesh-dev19** [comment]
Any help appreciated !

**Comment by skeesara02** [comment]
We are also having the same issue with RDS oracle, unable to pass custom parameter group, though we are passing, its taking default parameter group and then the status is going to `**incompatible-parameters**` as we updated a parameter in custom parameter group - **max_string_size** from **STANDARD** to **EXTENDED**. But this feature is working from from AWS CLI

**Comment by koolbaar** [comment]
Is there any update on this bug. This still seems to be happening. Creating a cross region read replica does not respect the Custom parameter group that we pass. If we try to modify the read replica, to fix the same, it tries to delete and re-create.

**Comment by kutttinoti** [comment]
Facing same problem. Curious to know if this is even acknowledged as a bug from hashicorp. 

Interestingly, while the tfl state shows as tainted and we can see that it is associating the default parameter group in AWS console, Tfl state output shows the custom parameter group name. So, custom parameter group is not completely ignored.

Also, aws cli command create-db-instance-read-replica succeeds with exact same parameter group. Hoping to get a resolution sooner on this.

**Comment by hitesh-dev19** [comment]
@justinretzolk can you please look at this bug, its still unresolved.

**Comment by gdavison** [comment]
Hi @hitesh-dev19, can you please share more of your Terraform configuration? Specifically, where you create the parameter group. It would also be helpful to see the configuration that creates the source database and its parameter group.

**Comment by rampalanofficial** [comment]
Hi @gdavison

Attaching two tar files that can be used for reproducing this problem, where parameter group that is passed to aws_db_instance is not used when creating the readreplica instance, especially when extended parameters are used (eg: max_string_size)

hashi-module-rds-oracle.tar.gz => This will create rds-oracle terraform module that can be used to create a RDS Oracle db instance with parameter/option groups.
call_rds_oracle.tar.gz => This will use rds-oracle terraform module twice, one for creating the primary instance and another for creating read replica instance.

[hashi-module-rds-oracle.tar.gz](https://github.com/hashicorp/terraform-provider-aws/files/14339017/hashi-module-rds-oracle.tar.gz)

[call_rds_oracle.tar.gz](https://github.com/hashicorp/terraform-provider-aws/files/14339000/call_rds_oracle.tar.gz)
