### ISSUE TITLE
[Bug]: Terraform AWS provider conflict for EC2-Classic when using EIPs with instances

### ISSUE THREAD

**Issue by pvshingala1997** [hashicorp/terraform-provider-aws#31733]
### Terraform Core Version

Any version more than 0.13 can be used

### AWS Provider Version

5.0.0,5.1.0

### Affected Resource(s)

As of Now AWS EIPs 

### Expected Behavior

Terraform plan should successfully exit 

### Actual Behavior

While using latest terraform provider version for EIPs with instance getting the below error for EC2-Classic retirement also challenge is the modules having dependency with higher provider version.

The issue is started after the provider version 4.67.0 . Till the v4.67.0 everything work as expected.

### Relevant Error/Panic Output Snippet

```shell
Error: with the retirement of EC2-Classic standard domain EC2 EIPs are no longer supported
```

### Terraform Configuration Files

Issue with AWS EIP block.

### Steps to Reproduce

Target the older deployments having EIPs and run them with latest aws provider.

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@pvshingala1997 Thanks for raising this issue 👏.
Do you have an example Terraform configuration that shows this problem?

**Comment by pvshingala1997** [comment]
@ewbankkit I am not sure if it is with few latest deployments as well but haven't came across that.

**Comment by pvshingala1997** [comment]
@ewbankkit Can you please let me know if there is any update on this issue?

**Comment by tsacha** [comment]
Hey, I am facing the same issue when trying to import existing EIP:

```hcl
resource "aws_eip" "gw" {
  for_each = toset(data.aws_availability_zones.available.names)
  domain   = "vpc"
}
```

```fish
❯ tf import 'aws_eip.gw["eu-central-1a"]' 35.x.x.x
data.aws_availability_zones.available: Reading...
data.aws_vpc.vpc: Reading...
data.aws_availability_zones.available: Read complete after 0s [id=eu-central-1]
aws_eip.gw["eu-central-1a"]: Importing from ID "35.x.x.x"...
aws_eip.gw["eu-central-1a"]: Import prepared!
  Prepared aws_eip for import
aws_eip.gw["eu-central-1a"]: Refreshing state... [id=35.x.x.x]
data.aws_subnet.dmz["eu-central-1b"]: Reading...
data.aws_subnet.dmz["eu-central-1c"]: Reading...
data.aws_subnet.dmz["eu-central-1a"]: Reading...
data.aws_subnet.dmz["eu-central-1b"]: Read complete after 0s [id=subnet-xx]
data.aws_subnet.dmz["eu-central-1a"]: Read complete after 0s [id=subnet-xx]
data.aws_subnet.dmz["eu-central-1c"]: Read complete after 0s [id=subnet-xx]
data.aws_vpc.vpc: Read complete after 0s [id=vpc-xxx]
╷
│ Error: with the retirement of EC2-Classic standard domain EC2 EIPs are no longer supported
```

Am I doing something wrong?

**Comment by pvshingala1997** [comment]
Its resolved we can follow below sequence to resolve it

if the resource is existing in current tf state then we need to remove that first from state by

tf state rm 'aws_eip.gw["eu-central-1a"]' 35.x.x.x

After that we need to reimport the same resource with eipassoc-**** of the ip address 35.x.x.x by 

tf import 'aws_eip.gw["eu-central-1a"]' eipassoc-****
