### ISSUE TITLE
[Bug]: Existing aws_dx_connection cannot be decoded from state

### ISSUE THREAD

**Issue by bodgit** [hashicorp/terraform-provider-aws#31732]
### Terraform Core Version

1.3.9

### AWS Provider Version

5.1.0

### Affected Resource(s)

* aws_dx_connection

### Expected Behavior

Existing aws_dx_connection resources should be decoded from state

### Actual Behavior

Using version 5.1.0 of the AWS provider existing aws_dx_connection resources cannot be decoded from state 

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: Failed to decode resource from state
│ 
│ Error decoding "aws_dx_connection.wl_ireland" from previous state: a number
│ is required
╵
╷
│ Error: a number is required
│ 
│   with aws_dx_connection.el_ireland,
│   on main.tf line 60, in resource "aws_dx_connection" "el_ireland":
│   60: resource "aws_dx_connection" "el_ireland" {
│ 
╵
╷
│ Error: a number is required
│ 
│   with aws_dx_connection.wl_ireland,
│   on main.tf line 67, in resource "aws_dx_connection" "wl_ireland":
│   67: resource "aws_dx_connection" "wl_ireland" {
│ 
╵
```

### Terraform Configuration Files

I have these existing resources prior to trying to update to version 5.1.0:
```hcl
resource "aws_dx_connection" "el_ireland" {
  provider  = aws.eu-west-1
  name      = "el-eu-west-1"
  bandwidth = "1Gbps"
  location  = "TCSH"
}

resource "aws_dx_connection" "wl_ireland" {
  provider  = aws.eu-west-1
  name      = "wl-eu-west-1"
  bandwidth = "1Gbps"
  location  = "EqLD5"
}
```

### Steps to Reproduce

Run a plan using these existing resources using version 5.1.0 of the AWS provider.

### Important Factoids

Version 5.0.1 is unaffected.

### References

This looks to have been introduced by #31480

### Would you like to implement a fix?

No

**Comment by Aussie007** [comment]
Hi
I got the same warning/error:

```
Warning: Failed to decode resource from state

Error decoding "aws_dx_connection.aws-rim" from prior state: a number is required

 Error: a number is required

   with aws_dx_connection.aws-rim,
   on Direct-connection.tf line 1, in resource "aws_dx_connection" "aws-rim":
    1: resource "aws_dx_connection" "aws-rim" {
```

Got the error after upgrading AWS Provider from v5.0.1 to v5.1.0

**Comment by thiagolsfortunato** [comment]
I rolled back to `v5.0.1` and works.

```
terraform {
  required_version = ">= 1.3"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0.0"
    }
  }
}
```
