### ISSUE TITLE
[Bug]: Error to access the state after upgrading to v5.1.0

### ISSUE THREAD

**Issue by thiagolsfortunato** [hashicorp/terraform-provider-aws#31743]
### Terraform Core Version

1.4.6

### AWS Provider Version

5.1.0

### Affected Resource(s)

After upgrading the provider from `v4.67.0` to `v5.1.0` the `terraform plan` reproduce an error just for the resource`aws_dx_connection`.

```terraform
╷
│ Warning: Failed to decode resource from state
│ 
│ Error decoding "aws_dx_connection.example" from prior state: a number is required
╵
...
╷
│ Error: a number is required
│ 
│   with aws_dx_connection.example,
│   on dx-connection.tf line 3, in resource "aws_dx_connection" "example":
│    3: resource "aws_dx_connection" "example" {
│ 
╵
```

### Expected Behavior

No changes had been detected in the state.

### Actual Behavior

Error in accessing the resource in the state.

### Terraform Configuration Files

```terraform
terraform {
  required_version = ">= 1.3"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_dx_connection" "example" {
  name      = "example"
  bandwidth = "1Gbps"
  location  = "EqDC2"
}
```

### Steps to Reproduce

```shell
terraform init && terraform apply -auto-approve
```

upgrade the AWS Provider Version Constraint:

```terraform
terraform {
  required_version = ">= 1.3"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.0"
    }
  }
}
```

run:

```shell
terraform init -upgrade && terraform plan
```

### Would you like to implement a fix?

None

**Comment by thiagolsfortunato** [comment]
Will be fixed here https://github.com/hashicorp/terraform-provider-aws/pull/31735

**Comment by ewbankkit** [comment]
@thiagolsfortunato Thanks for raising this issue.
It has already been noticed in #31732. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
