### ISSUE TITLE
[Docs]: kinesis_firehose_delivery_stream documentation doesn't align with validation checks

### ISSUE THREAD

**Issue by faleon** [hashicorp/terraform-provider-aws#31798]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream

### Description

The examples, argument, and attribute references don't align with the latest version of the AWS provider. When using the examples and references in creating a aws_kinesis_firehose_delivery_stream resource I received several errors regarding parameters or blocks not being expected there when the examples explicitly show blocks being nested in certain blocks or parameters references implying certain blocks be nested in others.

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @faleon 👋 Thank you for taking the time to raise this! Can you give me an example of some of the errors you received, and what version of the AWS provider you're using? I ran a quick `terraform validate` on each of the examples and didn't receive any of the block type errors you mentioned (only undeclared resource errors, which I would expect for this type of example).

**Comment by faleon** [comment]
@justinretzolk , my mistake. My terraform was pinned to an older version which caused the example in the docs to not work as it was for the latest version. Updating my aws provider to the latest version resolved the issue.
