### ISSUE TITLE
[Bug]:  aws sqs queue policy no support for Id attribute by terraform

### ISSUE THREAD

**Issue by vishal0511** [hashicorp/terraform-provider-aws#31817]
### Terraform Core Version

1.1.5

### AWS Provider Version

4.66.0

### Affected Resource(s)

aws_sqs_queue
cloudformation sqs queue policy:

```json
{
   "Version": "2012-10-17",
   **"Id": "Queue1_Policy_UUID",**
   "Statement": [{
      "Sid":"Queue1_AnonymousAccess_AllActions_AllowlistIP",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "sqs:*",
      "Resource": "arn:aws:sqs:*:111122223333:queue1",
      "Condition" : {
         "IpAddress" : {
            "aws:SourceIp":"192.0.2.0/24"
         }
      }
   }]
}
```

To convert same in Terraform there is no support for Id

### Expected Behavior

No support for Id in terraform

### Actual Behavior

No support for Id in terraform

### Terraform Configuration Files

No support for Id in terraform

### Steps to Reproduce

No support for Id in terraform

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @vishal0511 👋 Thank you for taking the time to raise this! Are you receiving an error that led you to believe this isn't supported? The [`aws_sqs_queue_policy` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue_policy) has a `policy` argument that takes JSON, so I don't see any reason that you couldn't include an `Id` there. Alternatively, if you're using the [`aws_iam_policy_document` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document#example-of-merging-override-documents) to construct the policy, that data source has a `policy_id` argument that can be used to supply an ID.

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
