### ISSUE TITLE
[Docs]: name is still listed in Arguments Reference of aws_db_instance

### ISSUE THREAD

**Issue by PhiGegner** [hashicorp/terraform-provider-aws#31818]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance

### Description

In the arguments reference of aws_db_instance `name` is still listed as deprecated. In fact it is not available as an argument anymore since version 5.0.0.
See referenced diffs of the pull request where the removal of the `name` argument was done.

`name` should be removed from the arguments reference of aws_db_instance.

### References

Removal of argument `name`: https://github.com/hashicorp/terraform-provider-aws/pull/31232/files#diff-5684e38aee8a02cd8ffe882cacb6fccda55107f3f73d76a5aec501bb07713035L387

Adjustments on documentation: https://github.com/hashicorp/terraform-provider-aws/pull/31232/files#diff-6a5091b97b3df2ae806bf12492d9c100f0f72d90527d0cd45f540bd2043d906e

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @PhiGegner 👋 Thank you for taking the time to raise this! I've opened a pull request to remove that argument from the documentation.
