### ISSUE TITLE
`aws_securityhub_account` resource is broken in the `aws-us-gov` partition since 4.64.0

### ISSUE THREAD

**Issue by lorengordon** [hashicorp/terraform-provider-aws#31822]
Finding that the `aws_securityhub_account` resource is broken in the `aws-us-gov` partition since 4.64.0, since that partition does not yet support `control_finding_generator`. Also somehow the _default_ value the provider is sending through is `SECURITY_CONTROL`, which just seems wrong in general since AWS defaults to `STANDARD_CONTROL` and requires explicitly enabling `SECURITY_CONTROL` in Security Hub.

Minimal reproducing config is just:

```hcl
resource "aws_securityhub_account" "this" {}
```

results in:

```
  # aws_securityhub_account.this will be updated in-place
  ~ resource "aws_securityhub_account" "this" {
      + control_finding_generator = "SECURITY_CONTROL"
```

which _can_ actually apply successfully, somehow, but then results in a perpetual diff

_Originally posted by @lorengordon in https://github.com/hashicorp/terraform-provider-aws/issues/30980#issuecomment-1580871565_

**Comment by lorengordon** [comment]
Th PR that broke things: https://github.com/hashicorp/terraform-provider-aws/issues/30692

**Comment by lorengordon** [comment]
It's been a couple weeks. How do I get something labeled as an actual bug?

**Comment by Apollorion** [comment]
@lorengordon Have you found a work around at all to prevent the perpetual diff?

**Comment by lorengordon** [comment]
@Apollorion No, no workaround. We're still stuck on 4.63.0.
