### ISSUE TITLE
[New Resources] - Support AWS Signer

### ISSUE THREAD

**Issue by bschaatsbergen** [hashicorp/terraform-provider-aws#31830]
### Description

AWS recently announced a new service called AWS Signer. 

There’s various resources that can and should be created in order to properly support this new service.

### Requested Resource(s) and/or Data Source(s)

aws_signer_signing_job
aws_signer_signing_profile_permission
aws_signer_signing_profile

### References

https://docs.aws.amazon.com/signer/latest/api/Welcome.html

### Would you like to implement a fix?

Yes

**Comment by polarctos** [comment]
Some parts of the AWS Signer service are already supported:
* https://github.com/hashicorp/terraform-provider-aws/pull/16383 added: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/signer_signing_profile

To be able to use the [new container signing functionality](https://aws.amazon.com/blogs/containers/announcing-container-image-signing-with-aws-signer-and-amazon-eks/), I think only the new `platform_id` for `Notation-OCI-SHA384-ECDSA` would be needed. This should be a one line fix in the validation requested in https://github.com/hashicorp/terraform-provider-aws/issues/32017.

Afterwards the actual signing happens with the notation CLI tool ([example AWS docs for container signatures](https://docs.aws.amazon.com/signer/latest/developerguide/image-signing-steps.html)), so I am not sure if there is benefit in e.g. adding the [`SignPayload`](https://docs.aws.amazon.com/signer/latest/developerguide/api-signpayload.html) as a resource.

**Comment by bschaatsbergen** [comment]
Solid find, I'm going to close this issue @polarctos.
