### ISSUE TITLE
[Docs]: aws_db_event_subscription `source_type` argument missing reference for `db-proxy` option

### ISSUE THREAD

**Issue by ckarakannas** [hashicorp/terraform-provider-aws#31865]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_event_subscription

### Description

In the `aws_db_event_subscription` resource docs, the `source_type` argument is missing the valid option for `db-proxy`. I have tested that this is a valid option with provider version `4.66.1`, and I presume it will be the same with more recent provider versions, so it seems like it's just missing from the docs (from _at least_ version 4.66.1 to latest)

### References

Relevant AWS docs for RDS Event subscription:

- [AWS RDS CreateEventSubscription API](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateEventSubscription.html#API_CreateEventSubscription_RequestParameters)
- [Working with RDS Proxy events](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.events.html)

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @ckarakannas 👋 Thank you for taking the time to raise this! I've opened a documentation PR to update the list.
