### ISSUE TITLE
[Docs]: FSX OnTap cooling_policy vs cooling_period

### ISSUE THREAD

**Issue by bcorijn** [hashicorp/terraform-provider-aws#31862]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_ontap_volume#cooling_policy

### Description

The docs list `cooling_policy` as value for the cooling period, while in fact this should be `cooling_period` https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/fsx/ontap_volume.go#L110

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @bcorijn 👋 Thank you for taking the time to raise this! I've opened a documentation pull request to correct the argument name.
