### ISSUE TITLE
[Bug]: data source aws_vpclattice.service can't search on anything but Service Identifier

### ISSUE THREAD

**Issue by nicoaws** [hashicorp/terraform-provider-aws#31864]
### Terraform Core Version

1.4.5.

### AWS Provider Version

5.1.0

### Affected Resource(s)

The datasource `aws_vpclattice.service` can't search for services other than by Service Identifier. This is pretty much useless unless the service itself has been created with TF. 
In the case services are created with K8s `httproute` resources, we need to be able to search by name or tags (or - better - both).

### Expected Behavior

See above

### Actual Behavior

See above

### Terraform Configuration Files

None

### Steps to Reproduce

None

### Would you like to implement a fix?

None

**Comment by exoego** [comment]
@nicoaws 
Hi, I've opened a PR for this https://github.com/hashicorp/terraform-provider-aws/pull/32177
If you wish this to happen, please 👍 in the PR so maintainers review.
