### ISSUE TITLE
[Enhancement]:  Create functionality to add an account-wide data protection policy.

### ISSUE THREAD

**Issue by chrisjomaron** [hashicorp/terraform-provider-aws#31907]
### Description

Currently, you can only apply a data protection policy to a specific CloudWatch log group with the _aws_cloudwatch_log_data_protection_policy_ resource.

AWS now allow you to set an account-wide policy. It would be fantastic to have this ability in the Terraform provider.

### Affected Resource(s) and/or Data Source(s)

aws_cloudwatch_log_data_protection_policy

### Would you like to implement a fix?

None

**Comment by mericozkayagan** [comment]
any updates for here ?

**Comment by cronster** [comment]
Please let us know if there is an update here.

**Comment by msteller** [comment]
Is this thing on?  :)

**Comment by mikamboo** [comment]
Hello,
It's now possible since **v5.58.0**

- [x] https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.58.0

![image](https://github.com/user-attachments/assets/355b10b0-1c26-49ce-86a9-2a4340b404e8)

**Comment by ewbankkit** [comment]
Closes via #38328.
