### ISSUE TITLE
[Enhancement]: Add additional parameters for aws_opensearchserverless_collection resource

### ISSUE THREAD

**Issue by balaji-punniyakodi** [hashicorp/terraform-provider-aws#31939]
### Description

Regarding https://github.com/hashicorp/terraform-provider-aws/pull/31091 

Hi Team,

I can see you have recently created aws_opensearchserverless_collection resource https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/opensearchserverless_collection.html.markdown however I dont see the parameter to specify the KMS key, network settings (Public or private with VPCE endpoints) from terraform and resource type.

![resource types](https://github.com/hashicorp/terraform-provider-aws/assets/136547507/03e792ec-ce63-4a57-8a25-e30e22444a32)
![kmskey](https://github.com/hashicorp/terraform-provider-aws/assets/136547507/8711e802-4817-4f5b-8ceb-b0141c397ec2)
![networksettings](https://github.com/hashicorp/terraform-provider-aws/assets/136547507/dacf1e76-49e3-4945-a2ed-c4c7a0a3b36f)

Let us know if you have any further questions.

### Affected Resource(s) and/or Data Source(s)

aws_opensearchserverless_collection

### References

review https://github.com/hashicorp/terraform-provider-aws/pull/31091 and https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/opensearchserverless_collection.html.markdown

### Would you like to implement a fix?

Yes

**Comment by joshjluo** [comment]
@balaji-punniyakodi As @mattburgess mentioned, I believe all of the screenshots you have provided can be addressed by using the [aws_opensearchserverless_security_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearchserverless_security_policy) resource to create encryption and network policies applicable to a collection. https://github.com/hashicorp/terraform-provider-aws/pull/32404 was just merged to provide more examples to do what you mention (e.g. specify your own KMS key, configure public access and VPCE access) as well.

**Comment by justinretzolk** [comment]
With the above notes, marking this as resolved. If additional functionality is desired, please open a new issue with the requisite details.
