### ISSUE TITLE
[Bug]: ECS Task Definition Error Message Incorrect

### ISSUE THREAD

**Issue by austinjohnson14** [hashicorp/terraform-provider-aws#31930]
### Terraform Core Version

v1.4.5

### AWS Provider Version

5.3.0

### Affected Resource(s)

aws_ecs_task_definition

### Expected Behavior

An error message should appear stating that hostPaths are not available on Fargate Enabled services.

### Actual Behavior

When using the Volume block with a fargate service, if you accidentally place a host_path, an error will appear stating that sourcePaths are not available for Fargate enabled task definitions.

### Terraform Configuration Files

n/a

### Steps to Reproduce

Paste the following onto a fargate enabled ecs service and attempt to apply it:
`  volume {
    name      = "foo"
    host_path = "bar"
  }`

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @austinjohnson14 👋 Thank you for taking the time to raise this! So that we have the necessary information in order to look into this, can you supply debug logs (redacted as needed) as well?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
