### ISSUE TITLE
[Enhancement]: aws_ssm_patch_baseline - support new value 'AMAZON_LINUX_2023'

### ISSUE THREAD

**Issue by eballetbaz** [hashicorp/terraform-provider-aws#31974]
### Description

A new value 'AMAZON_LINUX_2023' has been provided by AWS for field 'operating_system' of resource 'aws_ssm_patch_baseline' 

The current list of supported values are AMAZON_LINUX, AMAZON_LINUX_2, AMAZON_LINUX_2022, CENTOS, DEBIAN, MACOS, ORACLE_LINUX, RASPBIAN, REDHAT_ENTERPRISE_LINUX, ROCKY_LINUX, SUSE, UBUNTU, and WINDOWS.

This new value AMAZON_LINUX_2023 should be added to the list of supported values.

### Affected Resource(s) and/or Data Source(s)

aws_ssm_patch_baseline

### References

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-patchbaseline.html

### Would you like to implement a fix?

None

**Comment by mattburgess** [comment]
Requires aws-sdk-go v1.44.282, upgraded in #31986. So should be fixed in the next release. The docs patch is at #31993 but might not be picked up in time for the next release @eballetbaz.
