### ISSUE TITLE
[Docs]: remove shared_credentials_file in available option

### ISSUE THREAD

**Issue by jbareille** [hashicorp/terraform-provider-aws#31975]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference

### Description

The setting "shared_credentials_file" has been removed from provider version 5.0.0 but it is still present in the table "[AWS Configuration Reference](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference), in the panel "Provider" suggesting that is still available.
I suggest to remove it in the mentionned table

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @jbareille 👋 Thank you for taking the time to raise this! I've opened a docs PR to remove that last reference to `shared_credentials_file`.
