### ISSUE TITLE
[Bug]: Terraform plan in v1.5 giving error for import block

### ISSUE THREAD

**Issue by dev-travelex** [hashicorp/terraform-provider-aws#31978]
### Terraform Core Version

1.5.0

### AWS Provider Version

5.3.0

### Affected Resource(s)

Trying the new feature which automatically generates the config file : https://www.hashicorp.com/blog/terraform-1-5-brings-config-driven-import-and-checks

My import block looks like this in my file `import_ec2.tf`:

```
import {
  to = aws_instance.az1-drs-win
  id = "i-09463e8d9bxxx"
}

```

Running terraform plan with `-generate-config-out`:

```
terraform plan -generate-config-out=generated.tf 
╷
│ Error: Too many command line arguments
│ 
│ To specify a working directory for the plan, use the global -chdir flag.
╵

For more help on using this command, run:
  terraform plan -help
```

### Expected Behavior

It should have created a file `generated.tf` with the specs of the ec2-instance resource.

### Actual Behavior

Getting error:

```
Error: Too many command line arguments
│
│ To specify a working directory for the plan, use the global -chdir flag.
```

### Terraform Configuration Files

```
import {
  to = aws_instance.az1-drs-win
  id = "i-09463e8d9bxxx"
}

```

### Steps to Reproduce

1. Create a file with `import` block for an existing ec2 instance.
2. Run `terraform plan -generate-config-out=generated.tf`

### Debug Output

N/A

### Panic Output

N/A

### Important Factoids

N/A

### References

N/A

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @dev-travelex 👋 Thank you for taking the time to raise this! My initial thought is that this is likely an issue more scoped to the Terraform Core repository. That said, so that I can confirm my suspicion, can you supply debug logs (redacted as needed) as well?
