### ISSUE TITLE
[Docs]: Changing abort_incomplete_multipart_upload to abort_incomplete_multipart_upload_days

### ISSUE THREAD

**Issue by dunefro** [hashicorp/terraform-provider-aws#31992]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration#abort_incomplete_multipart_upload

### Description

When trying to use `abort_incomplete_multipart_upload` with a non-zero positive integer value for `days_after_initiation` the following error comes up
```
Error: updating S3 Bucket Lifecycle Configuration (MYBUCKETNAME): InvalidRequest: At least one action needs to be specified in a rule
```
After changing this `abort_incomplete_multipart_upload_days = <positiveint>` it is working fine

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @dunefro 👋 Thank you for taking the time to raise this! I'm not quite following what you've described here, as the schema for this resource includes a `abort_incomplete_multipart_upload` argument, but not a `abort_incomplete_multipart_upload_days` argument. Can you supply a sample Terraform configuration that illustrates your findings?

**Comment by dunefro** [comment]
I was trying to run this
```
module "some_bucket" {
  source  = "terraform-aws-modules/s3-bucket/aws"
  version = "3.13.0"

  bucket        = "BUCKET_NAME_HERE"

  force_destroy = true


  # S3 bucket-level Public Access Block configuration
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true

  lifecycle_rule = [
    {
      id      = "abort-multipart-uploads"
      status  = "Enabled"
      prefix  = ""
      enabled = true

      abort_incomplete_multipart_upload = {
        days_after_initiation = 7
      }
    }
  ]
}
```
and was getting the following error
```
│ Error: updating S3 Bucket Lifecycle Configuration (BUCKET_NAME_HERE): InvalidRequest: At least one action needs to be specified in a rule
│       status code: 400, request id: QRD22QRX035YNWJ5, host id: nqmc4mvzbcMrUYu1Fg2qnNbkWRI6wJH2Q5vgNCiJM5SoexD/HLxjwT/A1P2rX8F7srVjMYO+oMwTgvX76yjXeg==
│ 
│   with module.some_bucket.aws_s3_bucket_lifecycle_configuration.this[0],
│   on .terraform/modules/some_bucket/main.tf line 215, in resource "aws_s3_bucket_lifecycle_configuration" "this":
│  215: resource "aws_s3_bucket_lifecycle_configuration" "this" {
│ 
```
Then I tried to search this [example](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/master/examples/complete/main.tf#L256) and used this `lifecycle_rule`

```
  lifecycle_rule = [
    {
      id      = "abort-multipart-uploads"
      status  = "Enabled"
      prefix  = ""
      enabled = true

      abort_incomplete_multipart_upload_days = 7
    }
  ]
```
It worked seamlessly.

**Comment by divyafun** [comment]
I would like to work on this

**Comment by justinretzolk** [comment]
Hey @dunefro 👋 Thank you for that additional information! It looks like the discrepancy here is due to the way that the module that you're using accepts inputs, rather than a bug with the provider itself. The area of that codebase in particular can be found [here](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/c074ef4870aa981aafa5824f377f493377b7ee7f/main.tf#L228-L235), where it dynamically creates a `abort_incomplete_multipart_upload` block with the value passed to the `lifecycle[].abord_incomplete_multipart_upload_days` argument.

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
