### ISSUE TITLE
[Enhancement]: aws_appflow_flow missing Salesforce Marketing Cloud integration support

### ISSUE THREAD

**Issue by nkazarian-spokeo** [hashicorp/terraform-provider-aws#31994]
### Description

Amazon AppFlow supports Salesforce Marketing Cloud integration and that can be setup from console but it is not available form terraform aws_appflow_flow resource.

### Affected Resource(s) and/or Data Source(s)

```aws_appflow_flow```

### Would you like to implement a fix?

None

**Comment by jar-b** [comment]
Inspecting the network requests while creating a Salesforce Marketing Cloud connection in the AWS console, it appears this workflow actually uses the `CustomConnector` type - which is already available in the `aws_appflow_connector_profile` resource. 

Here is the payload of the sent request to the `CreateConnectorProfile` API. Values for the profile name, instance URL, token URL, and Oauth Client ID/Secret were all provided via a form in the console. 

```json
{
  "connectorProfileName": "<name>",
  "connectionMode": "Public",
  "connectorType": "CustomConnector",
  "connectorLabel": "SalesforceMarketingCloud",
  "connectorProfileConfig": {
    "connectorProfileProperties": {
      "CustomConnector": {
        "profileProperties": {
          "instanceUrl": "<instanceURL>"
        },
        "oAuth2Properties": {
          "tokenUrl": "https://<tokenUrl>.auth.marketingcloudapis.com/v2/token",
          "oAuth2GrantType": "CLIENT_CREDENTIALS",
          "tokenUrlCustomProperties": {}
        }
      }
    },
    "connectorProfileCredentials": {
      "CustomConnector": {
        "authenticationType": "OAUTH2",
        "oauth2": {
          "clientSecret": "<clientSecret>",
          "clientId": "<clientId>"
        }
      }
    }
  }
}
```

I believe this would roughly translate to the following configuration:

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {}

resource "aws_appflow_connector_profile" "example" {
  name            = "<name>"
  connector_type  = "CustomConnector"
  connector_label = "SalesforceMarketingCloud"
  connection_mode = "Public"

  connector_profile_config {
    connector_profile_credentials {
      custom_connector {
        authentication_type = "OAUTH2"
        oauth2 {
          client_id     = "<clientId>"
          client_secret = "<clientSecret>"
        }
      }
    }

    connector_profile_properties {
      custom_connector {
        profile_properties = {
          "instanceUrl" = "<intanceUrl>"
        }
        oauth2_properties {
          token_url         = "https://<tokenUrl>.auth.marketingcloudapis.com/v2/token"
          oauth2_grant_type = "CLIENT_CREDENTIALS"
        }
      }
    }
  }
}
```

Values wrapped in braces (`<>`) should be replaced (`name`, `client_id`, `client_secret`, `instance_url`, and `token_url`).

I do not have a Salesforce Marketing Cloud account to test this configuration with, so I'll leave this issue open for the time being to allow time for community feedback. @nkazarian-spokeo - does the option above solve your need from the original issue?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
