### ISSUE TITLE
[Bug]: Setting `backup_retention_period` on existing `aws_db_instance` fails silently

### ISSUE THREAD

**Issue by tymik** [hashicorp/terraform-provider-aws#32019]
### Terraform Core Version

1.3.7

### AWS Provider Version

5.2.0

### Affected Resource(s)

* `aws_db_instance.backup_retention_period`

### Expected Behavior

`aws_db_instance.backup_retention_period` is set to a non-zero value after adding `backup_retention_period` to the configuration.

OR, at the very minimum, error returned by the provider, what did not happen and because of that I classify this bug as FATAL bug - nobody wants to accidentally find out the snapshots are not available because there was a silent bug in the provider. 

### Actual Behavior

The `backup_retention_period` on consecutive `terraform plan` shows:

```shell
resource "aws_db_instance" "this" {
      ~ backup_retention_period               = 0 -> 35
```

Meaning the value was not changed although previous run showed:

```shell
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

There was no single mention regarding the problem unless trying `TF_LOG=DEBUG terraform apply`

### Relevant Error/Panic Output Snippet

With `TF_LOG=DEBUG` the following WARN message was found:

```shell
2023-06-15T17:11:26.115+0200 [WARN]  Provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected new value for module.db_instance.aws_db_instance.this[0], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .backup_retention_period: was cty.NumberIntVal(35), but now cty.NumberIntVal(0)
```

Some additional lines from the debug log:

```shell
2023-06-15T17:11:26.130+0200 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/aws/5.2.0/linux_amd64/terraform-provider-aws_v5.2.0_x5 pid=528097
User-Agent: APN/1.0 HashiCorp/1.0 Terraform/1.3.7 aws-sdk-go/1.42.35 (go1.19.4; linux; amd64)
```

### Terraform Configuration Files

This is an example taken from [RDS module](https://registry.terraform.io/modules/terraform-aws-modules/rds/aws/latest)
I added the `backup_retention_period = 35` that is commented out below (keep commented on 1st apply, uncomment on second apply, then execute plan to see value was not changed)

```terraform
module "db" {
  source  = "terraform-aws-modules/rds/aws"

  identifier = "demodb"

  engine            = "mysql"
  engine_version    = "5.7"
  instance_class    = "db.t3a.large"
  allocated_storage = 5

  db_name  = "demodb"
  username = "user"
  port     = "3306"

  iam_database_authentication_enabled = true

  vpc_security_group_ids = ["sg-12345678"]

  maintenance_window = "Mon:00:00-Mon:03:00"
  backup_window      = "03:00-06:00"

  # backup_retention_period = 35

  # Enhanced Monitoring - see example for details on how to create the role
  # by yourself, in case you don't want to create it automatically
  monitoring_interval = "30"
  monitoring_role_name = "MyRDSMonitoringRole"
  create_monitoring_role = true

  tags = {
    Owner       = "user"
    Environment = "dev"
  }

  # DB subnet group
  create_db_subnet_group = true
  subnet_ids             = ["subnet-12345678", "subnet-87654321"]

  # DB parameter group
  family = "mysql5.7"

  # DB option group
  major_engine_version = "5.7"

  # Database Deletion Protection
  deletion_protection = true

  parameters = [
    {
      name = "character_set_client"
      value = "utf8mb4"
    },
    {
      name = "character_set_server"
      value = "utf8mb4"
    }
  ]

  options = [
    {
      option_name = "MARIADB_AUDIT_PLUGIN"

      option_settings = [
        {
          name  = "SERVER_AUDIT_EVENTS"
          value = "CONNECT"
        },
        {
          name  = "SERVER_AUDIT_FILE_ROTATIONS"
          value = "37"
        },
      ]
    },
  ]
}
```

Sorry for not having a better example, I've got quite complicated Terragrunt code for that (all the dependencies) and it would take me ages to distill valuable parts without compromising confidential information.

### Steps to Reproduce

1. Have existing `aws_db_instance` resource with `backup_retention_period` not set

### Important Factoids

I use Terragrunt:

```shell
terragrunt --version
terragrunt version v0.42.7
```

```shell
terragrunt version
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.2.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
```

I believe that this is reproducible for all cases where there is `aws_db_instance` already applied, then modified with adding `backup_retention_period = 35` (any non-zero value, I tried also `30`) and applied again.

The worst part is there is no error returned, just `Apply complete` as if anything worked properly - but it didn't.

EDIT:
I tried destroying the instance and recreating it with `backup_retention_period = 35` then changed to `backup_retention_period = 30`, applied and it worked as expected.

### References

Looking for similar issues I have found this:

https://developer.hashicorp.com/terraform/plugin/sdkv2/guides/terraform-0.12-compatibility

Some additional light from Hashicorp:
https://discuss.hashicorp.com/t/tolerating-it-because-the-provider-is-using-the-legacy-plugin-sdk/50356

I have found 1 somewhat similar issue in other provider:
https://github.com/pactflow/terraform-provider-pact/issues/18

I tried to find similar issues that did not result in visible error message, but most I have found, regarding different providers (e.g. helm), gave some error messages back to Terraform, so it was visible that the `apply` command failed, examples:
https://github.com/hashicorp/terraform-provider-aws/issues/30699
https://hashicorp6.rssing.com/chan-74714669/all_p72.html
https://github.com/hashicorp/terraform-provider-aws/issues/29973
https://github.com/hashicorp/terraform-provider-google/issues/6260

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @tymik 👋 Thank you for taking the time to raise this! Based on a quick look, it looks like this may be related to this note at the top of the `aws_rds_instance` documentation: 

> Changes to a DB instance can occur when you manually change a parameter, such as `allocated_storage`, and are reflected in the next maintenance window. Because of this, Terraform may report a difference in its planning phase because a modification has not yet taken place. You can use the `apply_immediately` flag to instruct the service to apply the change immediately (see documentation below).

Looking at the [linked documentation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.DBInstance.Modifying.html), changes to the backup retention period are said to occur:

> If you choose to apply the change immediately, it occurs immediately.
> 
> If you don't choose to apply the change immediately, and you change the setting from a nonzero value to another nonzero value, the change is applied asynchronously, as soon as possible. Otherwise, the change occurs during the next maintenance window.

Can you test setting `apply_immediately` to `true` and verify that the behavior changes to what you're expecting?

**Comment by tymik** [comment]
Hi @justinretzolk, I thought it could be this but when the `aws_db_instance` was created with non-zero `backup_retention_period` in the first place, I changed from 35 to 30 and then back to 35 without `apply_immediately` set to `true` and it worked immediately - I confirmed that in addition with AWS Console to ensure changes were reflected.

I will recreate the database without setting `backup_retention_period` parameter at all, as when initially found the bug and I'll try with the `apply_immediately` set to `true` in a couple of moments to confirm this scenario and also once without that, as in original case, to see in AWS Console if it will say any changes are planned for the next maintenance window.

**Comment by tymik** [comment]
I have verified that and indeed, without the `apply_immediately` set to `true` the change gets queued for the next maintenance window and with the `apply_immediately` set to `true` it works as expected.
Must be related with the fact that without `backup_retention_period` set the automated snapshots are disabled completely.
Apologies for raising the alert.

Is it possible for the provider to return an information if something is to be in the next maintenance window?
It can be done with AWS CLI call:

```
aws rds describe-db-instances --db-instance-identifier $identifier | jq '.DBInstances[].PendingModifiedValues'
```

Perhaps there's a chance to incorporate such check into provider?
It might be helpful to get a message there are pending changes currently.

**Comment by tymik** [comment]
> Is it possible for the provider to return an information if something is to be in the next maintenance window? It can be done with AWS CLI call:
> 
> ```
> aws rds describe-db-instances --db-instance-identifier $identifier | jq '.DBInstances[].PendingModifiedValues'
> ```
> 
> Perhaps there's a chance to incorporate such check into provider?

@justinretzolk does that seem like something possible to implement?
If not, I think we could close this issue as it doesn't seem like anything else, apart from the check, could be done here.

**Comment by justinretzolk** [comment]
Sorry for the long delay in response here! Unfortunately, that information doesn't appear to be returned in the Go SDK, so it's not something we'd be able to integrate into the provider either.
