### ISSUE TITLE
[Enhancement]: aws_signer_signing_profile support for new platform_id for container signing with notation

### ISSUE THREAD

**Issue by polarctos** [hashicorp/terraform-provider-aws#32017]
### Description

The AWS Signer service now also allows to sign container images.

For this a new `platform_id` was introduced, namely ``Notation-OCI-SHA384-ECDSA``

Currently `aws_signer_signing_profile` only allows the [platform_id](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/signer_signing_profile) for Lambda:
https://github.com/hashicorp/terraform-provider-aws/blob/5a7eaa615f910a49234ef02d19bd5720d57cd7e7/internal/service/signer/signing_profile.go#L42-L43

Suggested fix, add the new ``Notation-OCI-SHA384-ECDSA`` value to the validation:

````go
 ValidateFunc: validation.StringInSlice([]string{ 
 	"AWSLambda-SHA384-ECDSA", "Notation-OCI-SHA384-ECDSA"}, 
````

These two are currently exposed via the AWS Console:
API name | Display name
-- | --
AWSLambda-SHA384-ECDSA | AWS Lambda
Notation-OCI-SHA384-ECDSA | Notation for container registries

https://docs.aws.amazon.com/signer/latest/developerguide/console-profile.html

### Affected Resource(s) and/or Data Source(s)

* aws_signer_signing_profile

### Potential Terraform Configuration

```terraform
resource "aws_signer_signing_profile" "notation_test" {
  platform_id = "Notation-OCI-SHA384-ECDSA"
  name        = "notation_test"
}
```

### References

Announcement and docs:
* https://aws.amazon.com/blogs/containers/announcing-container-image-signing-with-aws-signer-and-amazon-eks/
* https://docs.aws.amazon.com/signer/latest/developerguide/image-signing-steps.html

Original AWS Signer resources introduction, including the validation:
* https://github.com/hashicorp/terraform-provider-aws/pull/16383
* https://github.com/hashicorp/terraform-provider-aws/commit/39bc9f833a972a36bd6d7e9a7fe7114dfba50fa3

### Would you like to implement a fix?

No

**Comment by johnsonaj** [comment]
Feature has been merged in #32017. Will be released in `v.5.9.0`
