### ISSUE TITLE
[Bug]: Resource Creation for aws_internet_gateway is failing during apply

### ISSUE THREAD

**Issue by adithyapathipaka** [hashicorp/terraform-provider-aws#32020]
### Terraform Core Version

1.4.6

### AWS Provider Version

4.67.0

### Affected Resource(s)

* aws_internet_gateway

### Expected Behavior

AWS internet gateway need to be created with the tags given.

### Actual Behavior

AWS internet gateway is failing to create during apply with tags info given, with error as below,

> invalid new value for .tags_all: new element "Name" has appeared.

When plan is executing, no errors are found. However, if I rerun the apply this issue doesn't appear.

### Relevant Error/Panic Output Snippet

```shell
{"@level":"error","@message":"Error: Provider produced inconsistent final plan","@module":"terraform.ui","@timestamp":"2023-06-15T19:14:44.180458Z","diagnostic":{"severity":"error","summary":"Provider produced inconsistent final plan","detail":"When expanding the plan for aws_internet_gateway.vpc_igw to include new values learned so far during apply, provider \"registry.terraform.io/hashicorp/aws\" produced an invalid new value for .tags_all: new element \"Name\" has appeared.\n\nThis is a bug in the provider, which should be reported in the provider's own issue tracker."},"type":"diagnostic"}

{"@level":"error","@message":"Error: Provider produced inconsistent final plan","@module":"terraform.ui","@timestamp":"2023-06-15T19:14:44.180608Z","diagnostic":{"severity":"error","summary":"Provider produced inconsistent final plan","detail":"When expanding the plan for aws_internet_gateway.vpc_igw to include new values learned so far during apply, provider \"registry.terraform.io/hashicorp/aws\" produced an invalid new value for .tags_all: new element \"vpc_id\" has appeared.\n\nThis is a bug in the provider, which should be reported in the provider's own issue tracker."},"type":"diagnostic"}
```

### Terraform Configuration Files

Code Gist Link https://gist.github.com/adithyapathipaka/89e71daa2eb14e70c3bde17c4989ef89

### Steps to Reproduce

```{code:shell}
terraform plan -var-file det.tfvars
terraform apply -var-file det.tfvars
```

### Debug Output

[terraform-applu-error-igw.txt](https://github.com/hashicorp/terraform-provider-aws/files/11762326/terraform-applu-error-igw.txt)

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @adithyapathipaka 👋 Thank you for taking the time to raise this! Version 5.0.0 of the provider introduced some pretty significant changes to how tags are handled across the provider. Are you able to test with a newer version to see if that clears up the issues?

**Comment by adithyapathipaka** [comment]
Hello @justinretzolk 
Thanks for you reply. I have tried with newest version. It was able to create without any issue. 
Thanks for you support and explaination.
