### ISSUE TITLE
[Enhancement]: Kinesis Data Firehose adds support for document ID that is auto-generated by Amazon OpenSearch Service

### ISSUE THREAD

**Issue by asvinours** [hashicorp/terraform-provider-aws#32064]
### Description

> [Amazon Kinesis Data Firehose](https://aws.amazon.com/kinesis/data-firehose/) customers can now send data to Amazon OpenSearch Service using OpenSearch Service auto-generated document ID option. This configuration option enables write-heavy operations, such as log analytics and observability, to consume fewer CPU resources at the OpenSearch domain, resulting in improved performance.

from https://aws.amazon.com/about-aws/whats-new/2023/05/amazon-kinesis-data-firehose-document-id-amazon-opensearch-service/

### Affected Resource(s) and/or Data Source(s)

- `aws_kinesis_firehose_delivery_stream`

### Would you like to implement a fix?

No

**Comment by hdryx** [comment]
Any news about this feature ?
