### ISSUE TITLE
[Docs]: aws_security_group few attributes keeps as optional in document 

### ISSUE THREAD

**Issue by vurasandeep0** [hashicorp/terraform-provider-aws#32089]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group#argument-reference:~:text=issue%20during%20upgrade.-,The%20following%20arguments%20are%20optional%3A,-cidr_blocks%20%2D%20(Optional)%20List

### Description

When trying to create a security group with out all optional attributes it is not allowing to create a SG and plan is failed with below error.

`terraform apply
╷
│ Error: Incorrect attribute value type
│ 
│   on sg.tf line 3, in resource "aws_security_group" "webserver_sg":
│    3:   ingress = [
│    4:     {
│    5:     description = "HTTP"
│    6:     from_port = 8080
│    7:     to_port = 8080
│    8:     protocol = "tcp"
│    9:     cidr_blocks = ["0.0.0.0/0"]
│   10:   }
│   11:   ]
│ 
│ Inappropriate value for attribute "ingress": element 0: attributes "ipv6_cidr_blocks", "prefix_list_ids", "security_groups", and "self" are required.`

### Would you like to implement a fix?

None

**Comment by mattburgess** [comment]
Hi @vurasandeep0. As per the note at the top of the page you linked to, you're strongly encouraged to create new Security Group Rules using the [aws_vpc_security_group_egress_rule](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_security_group_egress_rule) and [aws_vpc_security_group_ingress_rule](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_security_group_ingress_rule) resources.

There are legacy codebases out there where migration may be tricky, but if you're creating new SGs + rules then using the separate resources should allow you to avoid a number of bugs that the inline rule configuration has. Unfortunately, the inaccuracy of the docs also affects that resource though. That was raised under https://github.com/hashicorp/terraform-provider-aws/issues/29893.
