### ISSUE TITLE
[Enhancement]: support for AWS Lake Formation and Glue Data Catalog cross-Region table access

### ISSUE THREAD

**Issue by rtoma-btg** [hashicorp/terraform-provider-aws#32099]
### Description

AWS has released a feature to support cross-region Glue table access. Related blog / docs:
- https://aws.amazon.com/about-aws/whats-new/2023/06/aws-lake-formation-glue-data-catalog-cross-region-access/
- https://docs.aws.amazon.com/lake-formation/latest/dg/data-access-across-region.html
- https://docs.aws.amazon.com/lake-formation/latest/dg/setup-cross-region-access.html

Please add support for this feature in the Terraform AWS provider.

### Affected Resource(s) and/or Data Source(s)

* aws_glue_catalog_table

### Potential Terraform Configuration

As of June 20th the API docs for `glue:CreateTable` https://docs.aws.amazon.com/glue/latest/webapi/API_CreateTable.html has not yet been updated, but docs at https://docs.aws.amazon.com/lake-formation/latest/dg/create-resource-link-table.html mention how to do it using the AWS CLI, so we can assume the API is there.

```
$ aws glue create-table —region eu-west-1 —cli-input-json '{
    "CatalogId": "111122223333",
    "DatabaseName": "ireland_db",
    "TableInput": {
        "Name": "rl_useast1salestb_ireland",
        "TargetTable": {
            "CatalogId": "444455556666",
            "DatabaseName": "useast1_salesdb",
            "Region": "us-east-1", <------------------
            "Name":"useast1_salestb"
        }
    }
}‘
```

When I map this to the current Terraform resource I believe the `target_table` parameter (see https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_catalog_table#target_table), needs to be extended with a `region`.

### Would you like to implement a fix?

No

**Comment by DrFaust92** [comment]
looking into this
