### ISSUE TITLE
[Docs]:  rds proxy SQLSERVER

### ISSUE THREAD

**Issue by m0bkrt** [hashicorp/terraform-provider-aws#32092]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_proxy

### Description

Engine family for "SQLSERVER" is been added to aws long time ago, why it's not in the terraform

### References

```terraform
resource "aws_db_proxy" "example" {
  name                   = "example"
  debug_logging          = false
  engine_family          = "SQLSERVER"
  idle_client_timeout    = 1800
  require_tls            = true
  role_arn               = "arn:aws:iam::123456789012:role/example"
  vpc_security_group_ids = ["sg-12345678"]
  vpc_subnet_ids         = ["subnet-12345678"]

  auth {
    auth_scheme = "SECRETS"
    description = "example"
    iam_auth    = "DISABLED"
    secret_arn  = "arn:aws:secretsmanager:us-west-2:123456789012:secret:example"
  }

  tags = {
    Name = "example"
  }
}
```

### Would you like to implement a fix?

None

**Comment by m0bkrt** [comment]
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy-setup.html

**Comment by justinretzolk** [comment]
Hey @m0bkrt 👋 Thank you for taking the time to raise this! I've opened a documentation pull request to get this updated.
