### ISSUE TITLE
[Bug]: aws_ecs_account_setting_default: InvalidParameterException: Invalid setting 'value'

### ISSUE THREAD

**Issue by jrobison-sb** [hashicorp/terraform-provider-aws#32114]
### Terraform Core Version

v1.5.0

### AWS Provider Version

v5.4.0

### Affected Resource(s)

* aws_ecs_account_setting_default

### Expected Behavior

I should be able to enable `tagResourceAuthorization` as described here: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-account-settings.html#tag-resources-setting

### Actual Behavior

Error as seen in Terraform output:

```
│ Error: creating ECS Account Setting Defauilt (tagResourceAuthorization): InvalidParameterException: Invalid setting 'value'
│ 
│   with module.staging_application.aws_ecs_account_setting_default.tag_resource_authorization[0],
│   on ../../modules/aws/application/ecs.tf line 1, in resource "aws_ecs_account_setting_default" "tag_resource_authorization":
│    1: resource "aws_ecs_account_setting_default" "tag_resource_authorization" {
```

Error as seen in Cloudtrail:

```
    "eventName": "PutAccountSettingDefault",
    "awsRegion": "us-east-1",
    "userAgent": "APN/1.0 HashiCorp/1.0 Terraform/1.5.0 (+https://www.terraform.io) terraform-provider-aws/5.4.0 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go/1.44.282 (go1.19.9; darwin; arm64)",
    "errorCode": "InvalidParameterException",
    "errorMessage": "Invalid setting 'value'",
    "requestParameters": {
        "name": "tagResourceAuthorization",
        "value": "enabled"
    },
    "responseElements": null,
```

### Terraform Configuration Files

```
resource "aws_ecs_account_setting_default" "tag_resource_authorization" {
  # https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-account-settings.html#tag-resources-setting
  name  = "tagResourceAuthorization"
  value = "enabled"
}
```

### Steps to Reproduce

`terraform apply` the above HCL config.

### Would you like to implement a fix?

No

**Comment by monelgordillo** [comment]
I need this too.

**Comment by ankon** [comment]
For anyone reading this and thinking "ok, so I only need to update the provider to 5.37.0+?" ... nope, also make sure to use the correct value:  The description says `"enabled"`, but you want `"on"` -- see the actual PR fixing this issue.
