### ISSUE TITLE
[Bug]: AWS Glue Crawler JDBC Target enable_additional_metadata configuration not applied as expected

### ISSUE THREAD

**Issue by mi-my-sf** [hashicorp/terraform-provider-aws#32110]
### Terraform Core Version

1.5.0

### AWS Provider Version

5.4.0

### Affected Resource(s)

In the aws_glue_crawler resource, within the jdbc_target block, there is an optional parameter called enable_additional_metadata.  This parameter is not applied as expected.

```
jdbc_target {
  connection_name = aws_glue_connection.my_glue_connection.name
  path            = "${var.my_database_name}/my_schema/%"

  # Note, this parameter does not apply as expected.
  # I was only able to set this parameter in the AWS
  # console manually and with the Glue SDK programmatically.
  enable_additional_metadata = ["COMMENTS", "RAWTYPES"]
}
```

### Expected Behavior

The following:
`enable_additional_metadata = ["COMMENTS", "RAWTYPES"]`

Should cause the "Comments" and "Raw types" checkboxes to be selected in the Glue Crawler JDBC data source options page in the AWS console, within the "Additional metadata - optional" drop-down list.

### Actual Behavior

There is no effect.

Setting:
`enable_additional_metadata = ["COMMENTS", "RAWTYPES"]`

Results in empty checkboxes within the "Additional metadata - optional" drop-down list.

The Terraform plan indicates that these values should be updated, but nothing happens.

```
~ jdbc_target {
  ~ enable_additional_metadata = [
    + "COMMENTS",
    + "RAWTYPES",
  ]
  # (3 unchanged attributes hidden)
}
```

### Terraform Configuration Files

```
resource "aws_glue_crawler" "my_glue_crawler" {
  name          = "${var.product_name}-glue-crawler"
  database_name = aws_glue_catalog_database.my_glue_catalog.name
  role          = aws_iam_role.my_glue_crawler_role.arn

  jdbc_target {
    connection_name = aws_glue_connection.my_glue_connection.name
    path            = "${var.my_database_name}/my_schema/%"

    # Note, this parameter does not apply as expected.
    # I was only able to set this parameter in the AWS
    # console manually and with the Glue SDK programmatically.
    enable_additional_metadata = ["COMMENTS", "RAWTYPES"]
  }
}
```

### Steps to Reproduce

1. Create a database with tables to crawl and credentials with appropriate grants to read the schema and tables.  I used Amazon Redshift, for example.
2. Create a JDBC Glue Connection to the database using the credentials from Step 1.  Note that network security groups must allow traffic to the database.
3. Create a Glue Crawler using the Glue Connection from Step 2.  See the aws_glue_crawler resource above for an example.  Set the enable_additional_metadata attribute as described above.

### Would you like to implement a fix?

No

**Comment by DrFaust92** [comment]
found the issue, fixing
