### ISSUE TITLE
[Docs]: aws_kinesis_firehose_delivery_stream - 'value' is incorrectly marked as Optional in common_attributes (http_endpoint_configuration)

### ISSUE THREAD

**Issue by ShaheenK27** [hashicorp/terraform-provider-aws#32113]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/4.60.0/docs/resources/kinesis_firehose_delivery_stream#common_attributes

### Description

* The documentation **incorrectly** mentions that the `value` parameter is optional in the **common_attributes** block (under request_configuration in http_endpoint_configuration).

* Not specifying 'value' leads to a ***plan-time error*** because this parameter has been implemented as **required** in the provider source code: [delivery_stream.go#L104](https://github.com/hashicorp/terraform-provider-aws/blob/v4.60.0/internal/service/firehose/delivery_stream.go#L104)

* As per the AWS API reference too, the 'value' parameter is required within CommonAttribute [API_HttpEndpointCommonAttribute](https://docs.aws.amazon.com/firehose/latest/APIReference/API_HttpEndpointCommonAttribute.html)

* The description of the 'value' parameter should be updated to **Required**.

### Would you like to implement a fix?

None

**Comment by McGon-Fid** [comment]
I would love to work on this! I'll open a PR shortly
