### ISSUE TITLE
[Enhancement]: Support for retrieving ARN of multiple instances in aws_instances data source

### ISSUE THREAD

**Issue by srk1195** [hashicorp/terraform-provider-aws#32123]
### Description

I would like to request support for retrieving the ARN (Amazon Resource Name) of multiple EC2 instances when using the aws_instances data source in Terraform. Currently, the data source only allows retrieving specific attributes of individual instances, such as instance_id, private_ip, etc., but it does not provide direct access to the instance ARN.

Being able to retrieve the ARN of multiple instances would be beneficial in various scenarios, such as tagging or referencing instances in policies or other resources.

Thank you for considering this enhancement request. I believe it would greatly benefit the Terraform community and improve the overall experience of working with AWS EC2 instances.

### Affected Resource(s) and/or Data Source(s)

* data.aws_instances

### Potential Terraform Configuration

```terraform
data "aws_instances" "example" {
  instance_tags = {
    Name = "dev-*"
  }
}

output "instance_arns" {
  value = [for instance in data.aws_instances.example.instances : instance.arn]
}
```

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @srk1195 👋 Thank you for taking the time to raise this! While it's not directly in the current data source, this functionality is possible with the current version of the provider by utilizing a combination of the `aws_instances` data source and `aws_instance` data source. This can be achieved as follows:

```terraform
data "aws_instances" "instances" {
  instance_tags = {
    Name = "dev-*"
  }
}

data "aws_instance" "this" {
  for_each = toset(data.aws_instances.instances.ids)
  instance_id = each.key
}

output "instance_arns" {
  value = data.aws_instance.this[*].arn
}
```
