### ISSUE TITLE
[Docs]: AWS provider configuration examples in the version 5.0.0

### ISSUE THREAD

**Issue by jualbacar** [hashicorp/terraform-provider-aws#32131]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs#authentication-and-configuration

### Description

Configuration AWS provider examples in the version 5.0.0 still show v4.0.0 examples.
It would be great to have new ones as there are things pretty differents between versions as for instance, how to use assume_role. Which in v5.0.0 has been removed

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @jualbacar 👋 Thank you for taking the time to raise this! I've opened a pull request to update the documentation as needed.
