### ISSUE TITLE
[Bug]: No tag on ec2's network interface from nodegroup in eks

### ISSUE THREAD

**Issue by tmpm697** [hashicorp/terraform-provider-aws#32151]
### Terraform Core Version

v1.5.0-dev

### AWS Provider Version

5.4.0

### Affected Resource(s)

* aws_eks_node_group

### Expected Behavior

ec2's instance network interface is tag.

when i spin up eks cluster with `aws_eks_cluster`, and create nodegroup with `aws_eks_node_group` that uses `launch_template`.

the `launch_template` has set `tag_specifications` for all three `instance, volume, network-interface`

but the ec2 instance create from `aws_eks_node_group`'s asg that consume from template does not have network interface tagged (instance and volume are tagged correctly)

### Actual Behavior

ec2 instance is tagged, volume is tagged but ec2's network interface is not tagged.

### Terraform Configuration Files

```
resource "aws_launch_template" "test" {
..
  dynamic "tag_specifications" {
    <this block applies tags for three resource_type instance, volume, network-interface>
  }
..
}
resource "aws_eks_node_group" "test" {
..
  launch_template {
    id      = aws_launch_template.test.id
    version = aws_launch_template.test.latest_version
  }
..
}
```

### Steps to Reproduce

tf apply

### Would you like to implement a fix?

None

**Comment by w564791** [comment]
I had the same problem,  in my autoscalinggroup .I lost all my tags .
I tried to find something, in cloudtrail ,when eks CreateAutoScalingGroupInfo , all my tags lost.

**Comment by tmpm697** [comment]
> I had the same problem, in my autoscalinggroup .I lost all my tags . I tried to find something, in cloudtrail ,when eks CreateAutoScalingGroupInfo , all my tags lost.

you can re-tag your asg using this resource `aws_autoscaling_group_tag`, but the network interface resources created from template should inherit tags from `tag_specifications` in template.

if I use standalone asg with launch template, network interface tagged correctly.

**Comment by bryantbiggs** [comment]
@tmpm697 is this still an issue or can we close this out?

**Comment by tmpm697** [comment]
i have no idea about this issue now, better close.
