### ISSUE TITLE
[New Service]: VerifiedPermissions

### ISSUE THREAD

**Issue by nolotz** [hashicorp/terraform-provider-aws#32158]
### Description

In AWS's recent announcements, they've unveiled a new service called VerifiedPermissions, an innovative feature that I believe could be a valuable addition to this provider. I was wondering if there were any plans to support this new service.

- [x] #32198

#### Resources

- [x] [`aws_verifiedpermissions_policy_store`](https://github.com/hashicorp/terraform-provider-aws/pull/32204)
- [x] [`aws_verifiedpermissions_schema`](https://github.com/hashicorp/terraform-provider-aws/pull/32204)
- [x] [`aws_verifiedpermissions_policy_template`](https://github.com/hashicorp/terraform-provider-aws/pull/32205)
- [x] [`aws_verifiedpermissions_policy`](https://github.com/hashicorp/terraform-provider-aws/pull/35413): https://github.com/hashicorp/terraform-provider-aws/issues/35412
- [ ] [`aws_verifiedpermissions_identity_source`](https://github.com/hashicorp/terraform-provider-aws/issues/35801): #35801

#### Data Sources

- [x] [`aws_verifiedpermissions_policy_store`](https://github.com/hashicorp/terraform-provider-aws/pull/32204)

### Potential Terraform Configuration

```terraform
resource "aws_verifiedpermissions_policy_store" "test" {
	validation_settings {
		mode = ""
	}
	schema {
		cedar_json = ""
	}
}

resource "aws_verifiedpermissions_policy_template" "test" {
	policy_store_id = aws_verifiedpermissions_policy_store.test.id

	description = ""
	statement = ""
}

resource "aws_verifiedpermissions_policy" "test" {
	policy_store_id = aws_verifiedpermissions_policy_store.test.id

        static {
	        description = ""
	        statement = ""
        }
        
        template_linked {
	        policy_template_id = aws_verifiedpermissions_policy_template.test.id
        
	        principal {
		        entity_id = ""
		        entity_type = ""
	        }
        
	        resource {
		        entity_id = ""
		        entity_type = ""
	        }
        }
}

resource "aws_verifiedpermissions_identity_source" "test" {
	policy_store_id = aws_verifiedpermissions_policy_store.test.id

	principal_entity_type = ""

	cognito_user_pool_configuration {
		client_ids = [""]
		user_pool_arn = ""
	}
}
```

### References

- https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/verifiedpermissions
- https://aws.amazon.com/verified-permissions/

### Would you like to implement a fix?

Yes

**Comment by ryancausey** [comment]
This should also include the ability to create and update the schema of the policy store:

* https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_PutSchema.html
* https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_GetSchema.html

@justinretzolk is there anything beyond the 👍 on the issue to get this moving sooner?

**Comment by prashant-joshi-25** [comment]
bump!

**Comment by outragedhuman** [comment]
Our organization is very interested in this to aid with automated deployments for AVP policies.

**Comment by ryancausey** [comment]
FYI I've worked around this by using the [awscc provider](https://registry.terraform.io/providers/hashicorp/awscc/latest) which now has support for AVP.

* https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/verifiedpermissions_policy
* https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/verifiedpermissions_policy_store
* https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/verifiedpermissions_policy_template
* https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/verifiedpermissions_identity_source

**Comment by steve-heine** [comment]
bump

**Comment by trp-mike-mckinney** [comment]
We are looking at using verified permissions and terraform support would be very helpful for our implementation

**Comment by jaypeeig** [comment]
bump

**Comment by oleksandr-kinship** [comment]
bump, looking forward to have all resources available in Pulumi AWS provider
