### ISSUE TITLE
[New Resource]: DMS serverless replication

### ISSUE THREAD

**Issue by Oden-Allfader** [hashicorp/terraform-provider-aws#32162]
### Description

On 1st of June AWS announced the release of AWS DMS Serverless replication.
Basically an autoscaling replication service removing the need for users to manage the provisioning and scaling of the replication instances. This is a service I personally would like to move my current replication tasks to use instead.

I have looked through the AWS Go SDK and there does not seem to be any support for it as of now as far as I can tell. Maybe on of you much smarter developers could have a look at.

Basically, instead of creating an `aws_dms_replication_instance` and an `aws_dms_replication_task`, one would only create the new `aws_dms_serverless_replication` for each replication task.

### Requested Resource(s) and/or Data Source(s)

aws_dms_serverless_replication

### References

https://aws.amazon.com/blogs/aws/new-aws-dms-serverless-automatically-provisions-and-scales-capacity-for-migration-and-data-replication/
https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Serverless.html

### Would you like to implement a fix?

No

**Comment by seanamos** [comment]
It looks like support for DMS serverless has recently been added to the Go AWS SDK:

https://github.com/aws/aws-sdk-go-v2/blob/787a81828a3812407a6d90036f07449d77a0f070/service/databasemigrationservice/CHANGELOG.md?plain=1#L17

https://github.com/aws/aws-sdk-go-v2/blob/b3e5b2960dcb85ddcd686954c4c11aab5b7a3323/service/databasemigrationservice/api_op_CreateReplicationConfig.go#L17

https://github.com/aws/aws-sdk-go-v2/blob/b3e5b2960dcb85ddcd686954c4c11aab5b7a3323/service/databasemigrationservice/api_op_StartReplication.go#L20

**Comment by dnascimento** [comment]
Perfect, just on time!

**Comment by DanielRieske** [comment]
As the support got added to the SDK, I'd like to pick this issue up!

**Comment by csbain** [comment]
What is the normal ETA that would be expected to get something like this released? if it's too long how would I go about using the provider based on this branch?

We have an urgent need for this.
