### ISSUE TITLE
[Enhancement]: multi az deployment for aws_redshift_cluster resource

### ISSUE THREAD

**Issue by MemoOR** [hashicorp/terraform-provider-aws#32180]
### Description

when creating an RDS deployment using `aws_db_instance` there is an option to set
```
multi_az = true
```

redshift clusters also supports multi az deployments but i don't see an option to do that in the resource 

### Affected Resource(s) and/or Data Source(s)

aws_redshift_cluster

### Potential Terraform Configuration

```terraform
resource "aws_redshift_cluster" "redshift_cluster" {
  # other configurations

  multi_az = true/false
}
```

### Would you like to implement a fix?

None

**Comment by DrFaust92** [comment]
Hi, this is not currently a supported feature for a redshift cluster as far i can see in the API docs.
