### ISSUE TITLE
[New Resource]: Add in Security Hub Automation Rules

### ISSUE THREAD

**Issue by ld-jmertz** [hashicorp/terraform-provider-aws#32210]
### Description

AWS recently added automation rules to Security Hub https://docs.aws.amazon.com/securityhub/latest/userguide/automation-rules.html

### Requested Resource(s) and/or Data Source(s)

"aws_securityhub_automation_rule"

### Would you like to implement a fix?

None

**Comment by jsaintjoanis** [comment]
Hi! Is anyone currently working on this? If not, @thomaslachaux and I are interested in doing it and submitting a PR!

**Comment by lostdignity** [comment]
I am also interested into this feature. Is there a roadmap for this?

**Comment by SneakerSB** [comment]
Have we an update for this ? would really appreciate this being made available

**Comment by DanielRieske** [comment]
Seeing the community reactions, I'll gladly pick this up.

Adding this will require 2 PR's, migrating the `securityhub` service to `aws-sdk-go-v2` and a follow-up PR to create this resource.

I just created an [issue ](https://github.com/hashicorp/terraform-provider-aws/issues/34692) to migrate the service and I will submit the PR shortly, when this is merged I will start on the `aws_securityhub_automation_rule` resource.

**Comment by runningman84** [comment]
Hey @DanielRieske would you mind looking into this issue too?
https://github.com/hashicorp/terraform-provider-aws/issues/34470

**Comment by DanielRieske** [comment]
Service migration got merged 🎉, I will now start working on the resource.

**Comment by zamirTo1** [comment]
@DanielRieske any updates?

**Comment by ewbankkit** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/34781.
