### ISSUE TITLE
[New]: EC2 Instance Connect Endpoint support

### ISSUE THREAD

**Issue by mszlgr** [hashicorp/terraform-provider-aws#32217]
### Description

EC2 Instance Connect Endpoint was announced  13 June 2023 - https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-ec2-instance-connect-ssh-rdp-public-ip-address/
I would like to be able to manage it using Terrafrom

### Requested Resource(s) and/or Data Source(s)

EC2 Instance Connect Endpoint announcement: https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-ec2-instance-connect-ssh-rdp-public-ip-address/
Doc: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/connect-using-eice.html

### Would you like to implement a fix?

None

**Comment by mattburgess** [comment]
I'll take a look at what's involved with this one.

**Comment by mattburgess** [comment]
@mszlgr - https://github.com/hashicorp/terraform-provider-aws/issues/31858 introduced this new resource. It will be released in 5.6.0, likely Thursday or Friday this week.

**Comment by ewbankkit** [comment]
@mszlgr Thanks for raising this issue.
It has already been noticed in #32011. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
