### ISSUE TITLE
Support Amazon SageMaker Pipelines

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#32225]
> SageMaker Pipelines brings automation and orchestration to ML workflows, enabling you to accelerate machine learning projects and scale up to thousands of models in production.

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/12/introducing-amazon-sagemaker-pipelines-first-purpose-built-ci-cd-service-machine-learning/).
[Blog post](https://aws.amazon.com/blogs/aws/amazon-sagemaker-pipelines-brings-devops-to-machine-learning-projects/).

Start with `aws_sagemaker_pipeline` resource.

Relates https://github.com/hashicorp/terraform-provider-aws/issues/21374.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/31607.

**Comment by DrFaust92** [comment]
Ill try to take a look soon

**Comment by jackvanschijndel1** [comment]
This would be great to have!
