### ISSUE TITLE
[Docs]: aws_cloudwatch_metric_alarm period parameter required

### ISSUE THREAD

**Issue by jboutsicaris** [hashicorp/terraform-provider-aws#32227]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_metric_alarm#period

### Description

period parameter for aws_cloudwatch_metric_alarm is listed as optional, but it is required:

│ Error: creating CloudWatch Metric Alarm (stage-sentry-ec2-disk-used-precent-alarm): ValidationError: Period must not be null
│ 	status code: 400, request id: 1f30f5f0-e4ec-43b3-97b1-888888888888
│ 
│   with module.sentry.aws_cloudwatch_metric_alarm.disk-used-precent-alarm,
│   on ../../modules/sentry/service/alarms.tf line 1, in resource "aws_cloudwatch_metric_alarm" "disk-used-precent-alarm":
│    1: resource "aws_cloudwatch_metric_alarm" "disk-used-precent-alarm" {

This could ether be a documentation issue, or a bug. Thanks

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @jboutsicaris 👋 Thank you for taking the time to raise this! So that we have the information necessary in order to look into this, can you supply a sample configuration and debug logs (redacted as needed) as well?

As an aside, this may be expected behavior based on the following note in the documentation:

> If you specify at least one `metric_query`, you may not specify a `metric_name`, `namespace`, `period` or `statistic`. If you do not specify a `metric_query`, you must specify each of these (although you may use `extended_statistic` instead of `statistic`).

**Comment by jboutsicaris** [comment]
unable to provide debug logs easily. I can answer follow-up questions, but this should be all the info needed to examine this doc discrepancy. Thanks

**Comment by justinretzolk** [comment]
Hey @jboutsicaris 👋 Thank you for providing that information. In reviewing the sample configuration, it appears you are indeed hitting the information outlined in the note from my previous comment in that you're providing `metric_name`, `namespace`, and `statistic`, but not `period`.

In this case, marking `period` as optional in the documentation is correct, as it is not required (and, in fact, not permitted) when passing `metric_query`.

**Comment by jboutsicaris** [comment]
thank you @justinretzolk. I understand this configuration now. not a doc issue, just missed the conditional logic on including metric_query.
