### ISSUE TITLE
[Bug]: aws_servicecatalog_principal_portfolio_association does not correctly clean up IAM_PATTERN principal types

### ISSUE THREAD

**Issue by mc-etcher** [hashicorp/terraform-provider-aws#32229]
### Terraform Core Version

1.5.1

### AWS Provider Version

5.5.0

### Affected Resource(s)

* `aws_servicecatalog_principal_portfolio_association`

### Expected Behavior

When you run a `terraform destroy` the principal type should be disassociated, regardless if it is a type of `IAM` or of `IAM_PATTERN`.  

### Actual Behavior

When you run a `terraform destroy` the principal types of `IAM` are successfully deleted, but the principal types of `IAM_PATTERN` are retained.  

This behavior is explained by how the golang SDK is called.  

If you have a principal type of `IAM_PATTERN` and you call `DisassociatePrincipalFromPortfolio` without specifying a `PrincipalType` of `IAM_PATTERN` in the `DisassociatePrincipalFromPortfolioInput` you'll receive `An error occurred (ResourceNotFoundException) when calling the DisassociatePrincipalFromPortfolio operation`.  

The AWS Provider is treating this resource not found exception as believing the resource is already cleaned up, and skips the removal.  

### Terraform Configuration Files

```terraform
resource "aws_servicecatalog_portfolio" "portfolio" {
  name          = "some_name"
  description   = "some_description"
  provider_name = "some_provider"
}

resource "aws_servicecatalog_principal_portfolio_association" "allowed_spoke_principals" {
  portfolio_id   = aws_servicecatalog_portfolio.portfolio.id
  principal_arn  = "arn:aws:iam:::role/SCEndUser"
  principal_type = "IAM_PATTERN"
}
```

### Steps to Reproduce

* Provision a `aws_servicecatalog_portfolio` resource
* Add an IAM Pattern Principal to the Portfolio using the `aws_servicecatalog_principal_portfolio_association` resource
* Run a `terraform plan` to create the resources
* Run a `terraform destroy` and receive an error
  * `Error: deleting Service Catalog Portfolio (port-************): ResourceInUseException: Portfolio port--************): still has associated Principals`

### Would you like to implement a fix?

Yes

**Comment by davidadixon** [comment]
👍

**Comment by mc-etcher** [comment]
@tanyuzhuo - while I can't comment on a timeline, I can point you to the [Prioritization Guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/) - one of the factors that helps is as follows `We prioritze work based on a number of factors, including community feedback, issue/PR reactions, as well as the source of the request.`

Please be sure to 👍 a PR proposed to address the issue - https://github.com/hashicorp/terraform-provider-aws/pull/32243

**Comment by boxrick** [comment]
Upvoted fix... does anyone have any potential workarounds in the meanwhile? Perhaps an AWS-CLI type command to disassociate on run of destroy?

**Comment by boxrick** [comment]
Workaround for anyone struggling:

```
resource "aws_servicecatalog_principal_portfolio_association" "allow_all_to_launch" {
  for_each       = var.portfolios
  portfolio_id   = aws_servicecatalog_portfolio.this[each.key].id
  principal_arn  = "arn:aws:iam:::role/*"
  principal_type = "IAM_PATTERN"

  ## This is a workaround for this bug, we manually disassociate this principal as we destroy it
  provisioner "local-exec" {
    when    = destroy
    command = "aws servicecatalog disassociate-principal-from-portfolio --portfolio-id ${self.portfolio_id} --principal-type IAM_PATTERN --principal-arn arn:aws:iam:::role/*"
  }
}
```

**Comment by silvaalbert** [comment]
@ewbankkit This is a good fix that would alleviate some pain for some that are having to implement workarounds (see above)
