### ISSUE TITLE
[Enhancement]: Allow aws_sagemaker_user_profile to use group names for SSO access

### ISSUE THREAD

**Issue by kimgri** [hashicorp/terraform-provider-aws#32239]
### Description

Resource in question: `aws_sagemaker_user_profile`

Variables in question: 
- `single_sign_on_user_value`
- `single_sign_on_user_identifier`

As per version v5.50 the only allowed field is `UserName` and this is quite limiting, the aws console allows multiple users and or groups to be added.

Wanted addition:
- Allow list of UserNames to used for `auth_mode = SSO`
- Allow groups to be used for SSO as well

### Affected Resource(s) and/or Data Source(s)

```
aws_sagemaker_user_profile
aws_sagemaker_domain
```

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_user_profile

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @kimgri 👋 Thank you for taking the time to raise this! The `aws_sagemaker_user_profile` resource uses the [`sagemaker.CreateUserProfile` function](https://github.com/hashicorp/terraform-provider-aws/blob/1eb5684240982703e0556283629afacffe8cd9d1/internal/service/sagemaker/user_profile.go#L436) from the underlying AWS SDK. This function takes a type of [`sagemaker.CreateUserProfileInput`](https://docs.aws.amazon.com/sdk-for-go/api/service/sagemaker/#CreateUserProfileInput), which is where the current limitation of needing to set `single_sign_on_user_identifier` to `UserName` and `single_sign_on_user_value` to a specific username comes from, as that is what that Go type expects.

In looking into this, I found an [AWS blog post](https://aws.amazon.com/blogs/machine-learning/team-and-user-management-with-amazon-sagemaker-and-aws-sso/) that seems to corroborate this limitation, so I suspect that this is something that cannot be changed unless the underlying AWS systems change.

Would it be possible in your case to use `for_each` to create `aws_sagemaker_user_profile` resources for each of the users that you need to add?

**Comment by kimgri** [comment]
> Hey @kimgri 👋 Thank you for taking the time to raise this! The `aws_sagemaker_user_profile` resource uses the [`sagemaker.CreateUserProfile` function](https://github.com/hashicorp/terraform-provider-aws/blob/1eb5684240982703e0556283629afacffe8cd9d1/internal/service/sagemaker/user_profile.go#L436) from the underlying AWS SDK. This function takes a type of [`sagemaker.CreateUserProfileInput`](https://docs.aws.amazon.com/sdk-for-go/api/service/sagemaker/#CreateUserProfileInput), which is where the current limitation of needing to set `single_sign_on_user_identifier` to `UserName` and `single_sign_on_user_value` to a specific username comes from, as that is what that Go type expects.
> 
> In looking into this, I found an [AWS blog post](https://aws.amazon.com/blogs/machine-learning/team-and-user-management-with-amazon-sagemaker-and-aws-sso/) that seems to corroborate this limitation, so I suspect that this is something that cannot be changed unless the underlying AWS systems change.
> 
> Would it be possible in your case to use `for_each` to create `aws_sagemaker_user_profile` resources for each of the users that you need to add?



Hello and thanks for the response!
I tried using the `for_each `method however it does not work.
Since we are don't want to use multiple` aws_sagemaker_user_profile` resources but instead assign multiple SSO identifiers to one user profile. A work around would ofc be to use groups, but as the only available field is `UserName `it is not possible to use groups.
This seems like it is a limitation of the AWS SDK then..
