### ISSUE TITLE
[Enhancement]: Support custom ports for Redshift Serverless

### ISSUE THREAD

**Issue by bengaywins** [hashicorp/terraform-provider-aws#32249]
### Description

The docs for this resource allow for specifying a port within a small few ranges.

Adding support for this in the provider would enable this feature.

### Affected Resource(s) and/or Data Source(s)

* aws_redshiftserverless_workgroup

### Potential Terraform Configuration

```terraform
resource "aws_redshiftserverless_workgroup" "example" {
  namespace_name = "concurrency-scaling"
  workgroup_name = "concurrency-scaling"
  config_parameter  [
    port = 5437
  ]
}
```

### References

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/redshift-serverless/create-workgroup.html

### Would you like to implement a fix?

No

**Comment by tschmitt** [comment]
Definitely a value add. When using non-standard Redshift ports today, we have to modify Redshift post-apply, which is obviously not desired.
