### ISSUE TITLE
[Bug]: aws_elasticache_replication_group - Terraform fails when trying to plan or apply when engine version = 7.x

### ISSUE THREAD

**Issue by spirosekulovski** [hashicorp/terraform-provider-aws#32252]
### Terraform Core Version

1.5.1

### AWS Provider Version

5.3.0 -> 5.5.0

### Affected Resource(s)

aws_elasticache_replication_group

### Expected Behavior

Expected behavior is for `aws_elasticache_replication_group` to work as it worked on older versions of the provider. Expected behavior is for Terraform not to complain about the ElastiCache engine version. 
This works correctly on version 5.0.0, 5.1.0, 5.2.0. Breaks with provider version 5.3.0, still broken on 5.5.0.

### Actual Behavior

Terraform fails to plan or apply changes and exits with an error message. Depending on the config, the error message is different. The only workaround we've found is to pin the AWS provider to 5.2.0 or older.

### Relevant Error/Panic Output Snippet

```shell
When `engine_version  = "7.x"`
╷
│ Error: engine_version: Redis versions must match <major>.<minor> when using version 6 or higher, or <major>.<minor>.<patch>
│ 
│   with module.identity_service_redis_cluster.aws_elasticache_replication_group.this,
│   on ../../modules/identity-service-redis-cluster/elasticache.tf line 29, in resource "aws_elasticache_replication_group" "this":
│   29:   engine_version             = "7.x"
│ 
╵ 

When `engine_version  = "7"`
╷
│ Error: engine_version: Redis versions must match <major>.<minor> when using version 6 or higher, or <major>.<minor>.<patch>
│ 
│   with module.identity_service_redis_cluster.aws_elasticache_replication_group.this,
│   on ../../modules/identity-service-redis-cluster/elasticache.tf line 29, in resource "aws_elasticache_replication_group" "this":
│   29:   engine_version             = "7"
│ 
╵

When `engine_version  = "7.0.7"`
╷
│ Error: engine_version: Redis versions must match <major>.<minor> when using version 6 or higher, or <major>.<minor>.<patch>
│ 
│   with module.identity_service_redis_cluster.aws_elasticache_replication_group.this,
│   on ../../modules/identity-service-redis-cluster/elasticache.tf line 29, in resource "aws_elasticache_replication_group" "this":
│   29:   engine_version             = "7.0.7"
│ 
╵

When `engine_version   = "7.0"`

Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: parsing old engine_version: Malformed version: 7.x
│ 
│   with module.identity_service_redis_cluster.aws_elasticache_replication_group.this,
│   on ../../modules/identity-service-redis-cluster/elasticache.tf line 21, in resource "aws_elasticache_replication_group" "this":
│   21: resource "aws_elasticache_replication_group" "this" {
│ 
╵
```

### Terraform Configuration Files
```
resource "aws_elasticache_replication_group" "this" {
  replication_group_id = "${var.application}-${var.environment}"
  description          = "${var.application} ${var.environment}"
  security_group_ids   = [var.sg]
  subnet_group_name    = "elasticache-${var.environment}"

  parameter_group_name       = aws_elasticache_parameter_group.redis7.name
  engine                     = "redis"
  engine_version             = "7.x"
  automatic_failover_enabled = true

  node_type               = "cache.r6g.4xlarge"
  num_node_groups         = var.shards
  replicas_per_node_group = var.shard_replicas

  tags = {
    Name = "${var.application}-${var.environment}"
  }

  lifecycle {
    ignore_changes = [
      num_node_groups
    ]
  }
}
```

### Steps to Reproduce

Switch to AWS provider version 5.3.0 or newer and run `terraform plan` for an `aws_elasticache_replication_group` resource with engine version 7.x.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Potentially related: #31264

**Comment by Maxwell2022** [comment]
Same issue here, tested with `hashicorp/aws - 5.8.0` and all combination possible: **"7"**, **"7.x"**, **"7.0"**, **"7.2"** (even tho that doesn't seems to be an option in Elasticache, [it's a valid option in the tests](https://github.com/hashicorp/terraform-provider-aws/pull/31264/files#diff-f437054220401d520be864767323e80a5f8a5a715eecff20a446f73e7f830b34R147)) and got this same error:

> engine_version: Redis versions must match <major>.<minor> when using version 6 or higher, or <major>.<minor>.<patch>

**Comment by YakDriver** [comment]
Help me understand exactly which version worked before that does not work now. Perhaps there are account or regional differences?

### Redis `7.0` works for me

My testing environment:
```
Terraform v1.5.3
AWS Provider v5.8.0
us-west-2
```

The only valid Redis 7 version in ElastiCache is `7.0`. Do you have access to other versions? For me, `7.0` works in the Terraform AWS provider. In other words, I get no errors with this config:

```terraform
resource "aws_elasticache_replication_group" "test" {
  replication_group_id = "mebrizic"
  description          = "test description"
  node_type            = "cache.t3.small"
  engine_version       = "7.0"
  parameter_group_name = aws_elasticache_parameter_group.test.name
  engine               = "redis"
}

resource "aws_elasticache_parameter_group" "test" {
  name   = "mebrizic"
  family = "redis7"
}
```

### Invalid versions: `7.x`, `7`, `7.2`, `6`

If I remove the version check in the AWS provider, ElastiCache itself responds with an error.

1. ✅ Redis `6.x` _is_ valid. It worked before and works now.
2. ✅ Redis `7.0` _is_ valid. It works now.
3. 🚫 Redis `6` is _not_ valid. It didn't work before and doesn't work now. ElastiCache says, `InvalidParameterCombination: Cannot find version 6 for redis`.
4. 🚫 Redis `7.x` is _not_ valid. It didn't work before and doesn't work now. ElastiCache says, `InvalidParameterCombination: Cannot find version 7.x for redis`. 
5. 🚫 Redis `7` is _not_ valid. It didn't work before and doesn't work now. ElastiCache says, `InvalidParameterCombination: Cannot find version 7 for redis`.
6. 🚫 Redis `7.2` is _not_ valid. It didn't work before and doesn't work now. ElastiCache says, `InvalidParameterCombination: Cannot find version 7.2 for redis`.

### Parameter group families

Below are the available parameter group families I currently see. While `redis7` is valid as a pg family, `7` is not valid as `engine_version`. With `redis6.x`, the corresponding `engine_version` is `6.x`. But, slightly differently, with `redis7`, the corresponding `engine_version` is `7.0`.

1. `memcached1.4`
2. `memcached1.5`
3. `memcached1.6`
4. `redis2.6`
5. `redis2.8`
6. `redis3.2`
7. `redis4.0`
8. `redis5.0`
9. `redis6.x`
10. `redis7`

**Comment by KIVagant** [comment]
I met the same problem. if I understood correctly, here's what happened in our case:

1. We had some of the Redis instances configured in Terraform using the wildcard syntax: `6.x`
2. Someone manually updated Redis engines in AWS Console UI to **7.0.***
3. After the update, the code was updated to `7.x` manually. It worked well with the AWS provider `4.37.0`.
4. When I started working in the same repository, I updated the AWS provider from `4.37.0` to `5.9.0` and faced the problem: neither the `7.x` value nor `7.0` worked. It was either the `Redis versions must match <major>.<minor>...` or `Error: parsing old engine_version: Malformed version: 7.x` error.

But I found a fix for that. I manually edited the remote state in an S3 bucket and patched the relevant DynamoDB table with the proper object "digest".

For those who have never done this: the DynamoDB table may have several artifacts from different Terraform versions, so you'll have to find the proper one:
![image](https://github.com/hashicorp/terraform-provider-aws/assets/517501/8c683c86-9079-41df-ab18-0cf4c7fafe88)

The digest is the S3 object ETag:
![image](https://github.com/hashicorp/terraform-provider-aws/assets/517501/f91ea702-c1b6-4690-be48-f83303af709d)

**Comment by julieerle** [comment]
Terraform v1.5.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v5.11.0
region = "us-east-2"


I was able to reproduce this issue with the following configuration (see engine_version).
```
# errors.tf ----------
resource "aws_elasticache_replication_group" "example" {
  automatic_failover_enabled  = true
  engine_version = "7.0.7"
  preferred_cache_cluster_azs = ["us-east-2a", "us-east-2b"]
  replication_group_id        = var.name
  description = "foobar"
  node_type                   = "cache.m4.large"
  num_cache_clusters          = 2
  port                        = 6379
}

/*
On apply, I see
│ Error: engine_version: Redis versions must match <major>.<minor> when using version 6 or higher, or <major>.<minor>.<patch>
│ 
│   with aws_elasticache_replication_group.example,
│   on main.tf line 20, in resource "aws_elasticache_replication_group" "example":
│   20:   engine_version = "7.0.7"
*/
```


---
The following config allows successful create on apply (only change is the engine_version. In the AWS console, I can see the [engine_version_actual](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#engine_version_actual) is "7.0.7"
```
# works.tf----------
resource "aws_elasticache_replication_group" "example" {
  automatic_failover_enabled  = true
  engine_version = "7.0"
  preferred_cache_cluster_azs = ["us-east-2a", "us-east-2b"]
  replication_group_id        = var.name
  description = "foobar"
  node_type                   = "cache.m4.large"
  num_cache_clusters          = 2
  port                        = 6379
}
```

Here is information from my state file after successful apply
```
            "engine": "redis",
            "engine_version": "7.0",
            "engine_version_actual": "7.0.7",
```

**Comment by YakDriver** [comment]
ElastiCache will not accept `engine_version = "7.0.7"` and will return a 400 error: `InvalidParameterValue: Specific version selection is not allowed for '7.0.7', please use '7.0'`.

**Comment by YakDriver** [comment]
Thank you for your patience on this. The previous error message did not make it clear what was allowed or not. Hopefully this new error message is better. For example:

```
Error: engine_version: 7.0.7 is invalid. For Redis v6 or higher, use <major>.<minor>. For Redis v5 or lower, use <major>.<minor>.<patch>.
```
