### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by buffalmacco** [hashicorp/terraform-provider-aws#32257]
### Documentation Link

The web page for aws_api_gateway_api_key states the lower limit for value is 20, but actually is 30.

### Description

Here:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_api_key.html

If specified, the value must be an alphanumeric string between 20 and 128 characters.

but this code
```
resource "aws_api_gateway_api_key" "this" {
  name  = "${var.envname}-${var.name}-api-key"
  value = var.api_key_value
}
```
with a value 21 characters long gives:

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: expected length of value to be in the range (30 - 128), got 123password0987654321
```

Upstream documentation is confusing. See provided links.

### References

https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-api-usage-plans.html

https://docs.aws.amazon.com/apigateway/latest/developerguide/api-key-file-format.html

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @buffalmacco 👋 Thank you for taking the time to raise this! Can you verify what version of the AWS Provider you're using when encountering these errors? The validation for this field recently changed with #30894, which went out in version 4.65.0 of the provider.

**Comment by buffalmacco** [comment]
My bad I didn't take notice at the time, but I went back in repository to the commit in the project where I encountered this issue, and sure enough the provider had (and still has) this line:
```
version = "~> 4.63.0"
```
