### ISSUE TITLE
[Enhancement]: Missing configurations for actions suppressor in aws_cloudwatch_composite_alarm resource

### ISSUE THREAD

**Issue by posquit0** [hashicorp/terraform-provider-aws#32251]
### Description

The CloudWatch `PutCompositeAlarm` API has additional parameters to configure actions suppressor.

### Affected Resource(s) and/or Data Source(s)

* `aws_cloudwatch_composite_alarm`

### Potential Terraform Configuration

```terraform
resource "aws_cloudwatch_composite_alarm" "example" {
  alarm_description = "This is a composite alarm!"
  alarm_name        = "example-composite-alarm"

  alarm_actions = aws_sns_topic.example.arn
  ok_actions    = aws_sns_topic.example.arn

  alarm_rule = <<EOF
ALARM(${aws_cloudwatch_metric_alarm.alpha.alarm_name}) OR
ALARM(${aws_cloudwatch_metric_alarm.bravo.alarm_name})
EOF

  actions_suppressor {
    alarm = "suppressor-alarm"

    extension_period = 10
    wait_period      = 20
  }
}
```

### References

- [Amazon CloudWatch: PutCompositeAlarm](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutCompositeAlarm.html)

### Would you like to implement a fix?

None

**Comment by DanielRieske** [comment]
I'd like to pick this issue up as my first contribution to this Terraform provider, I will add the PR shortly.
