### ISSUE TITLE
[Docs]: wafv2_web_acl_logging_configuration - name of CloudWatch/Logs log group must start with `aws-waf-logs-`.

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/terraform-provider-aws#32262]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl_logging_configuration

### Description

It is/was not clear from the documentation that WAF *require* the CloudWatch log group to start with `aws-waf-logs-`!

The documentation DO say:
```
  name = "aws-waf-logs-some-uniq-suffix"
```

But it was not clear that it **HAVE** to start with that prefix. A small note about this would be appreciated.

A comment above that line would suffice. Something like:
```
resource "aws_cloudwatch_log_group" "example" {
  # NOTE: Must start with `aws-waf-logs-`!
  name = "aws-waf-logs-some-uniq-suffix"
}
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @FransUrbo 👋 Thank you for taking the time to raise this! I've opened a documentation pull request to try to make this a bit more clear.
