### ISSUE TITLE
Fault Injection Experiment Template[Enhancement]: 

### ISSUE THREAD

**Issue by cristianpirtea** [hashicorp/terraform-provider-aws#32281]
### Description

Hello,

I am trying to deploy an AWS FIS Experiment Template resource for EKS, mentioned in this announcement:

https://aws.amazon.com/about-aws/whats-new/2023/06/aws-fault-injection-simulator-new-actions-amazon-eks-ecs/

Unfortunately, when i try to deploy resource i end-up with this error:

**Error: creating AWS FIS (Fault Injection Simulator) Experiment Template (Stress pod CPU usage): operation error fis: CreateExperimentTemplate, https response error StatusCode: 400, RequestID: 66e47788-f492-49e0-827f-ec4b7ba63af0, ValidationException: TargetResourceType aws:eks:pod does not support tags.**

### Affected Resource(s) and/or Data Source(s)
resource "aws_fis_experiment_template" "fis_eks" {     
      
      + description = "Stress pod CPU usage"
      + id          = (known after apply)
      + role_arn    = "arn:aws:iam::xxxxxxxxxx:role/AmazonFISforEKSRole"
     
      + action {
          + action_id   = "aws:eks:pod-cpu-stress"
          + name        = "pod-cpu-stress"
          + start_after = []

          + parameter {
              + key   = "duration"
              + value = "PT2M"
            }
          + parameter {
              + key   = "fisPodContainerImage"
              + value = "713827034473.dkr.ecr.eu-central-1.amazonaws.com/aws-fis-pod:0.1"
            }
          + parameter {
              + key   = "kubernetesServiceAccount"
              + value = "fis-experiment"
            }
          + parameter {
              + key   = "maxErrorsPercent"
              + value = "0"
            }
          + parameter {
              + key   = "percent"
              + value = "100"
            }
          + parameter {
              + key   = "workers"
              + value = "0"
            }

          + target {
              + key   = "Cluster"
              + value = "EKSpodCPUstress"
            }
        }

      + stop_condition {
          + source = "none"
        }

      + target {
          + name           = "EKSpodCPUstress"
          + resource_arns  = []
          + resource_type  = "aws:eks:pod"
          + selection_mode = "PERCENT(60)"

          + resource_tag {
              + key   = "clusterIdentifier"
              + value = "xxxxx"
            }
          + resource_tag {
              + key   = "namespace"
              + value = "xxxxxx"
            }
          + resource_tag {
              + key   = "selectorType"
              + value = "deploymentName"
            }
          + resource_tag {
              + key   = "selectorValue"
              + value = "xxxxxx"
            }
          + resource_tag {
              + key   = "targetContainerName"
              + value = "xxxxxx"
            }
        }
    }

### Potential Terraform Configuration

```terraform
Based on AWS documentation(Example experiment template chapter),
my expectation would be to have "parameter" option in target configuration block as well, 
but the only options are: "resource_arns" or "resource_tag" 

https://docs.aws.amazon.com/fis/latest/userguide/eks-pod-actions.html#eks-pod-container-images
```

### References

https://docs.aws.amazon.com/fis/latest/userguide/eks-pod-actions.html#eks-pod-container-images

### Would you like to implement a fix?

None

**Comment by haofeif** [comment]
Is there a timeline for this feature ?

**Comment by tmoon8730** [comment]
I am also running into this issue. After taking a quick look into the relevant code I think this could be a simple update to the verification method on the fis experiment resource. 

If nobody else is working on this issue I might be able to dig into it more.

**Comment by debadutta24** [comment]
Has there been any progress on this? I am also facing the same issue.

**Comment by anilg8222** [comment]
> Has there been any progress on this? I am also facing the same issue.

+ facing the same issue

**Comment by gabbler97** [comment]
Is there any progress here?
A workaround would be good also.

**Comment by maheshwarirohit87** [comment]
I am facing the same issue 
│ Error: updating AWS FIS (Fault Injection Simulator) Experiment Template : A target block requires one of resource_arns, resource_tag

**Comment by pexa-dbhatt** [comment]
I am facing same issue where it complains about missing tags and arns while deploying template for eks pod actions
