### ISSUE TITLE
[Enhancement]: There is no connection methods between `aws_cloudwatch_log_resource_policy` and `aws_cloudwatch_log_group`

### ISSUE THREAD

**Issue by shieldnet** [hashicorp/terraform-provider-aws#32308]
### Problem
I have problem to adjust `aws_cloudwatch_log_resource_policy` to `aws_cloudwatch_log_group` to enable CloudWatch Logs with AWS Opensearch Service.

<img width="711" alt="image" src="https://github.com/hashicorp/terraform-provider-aws/assets/9548599/289f50d7-87df-47bf-8f9b-ee359b36c431">

As you can see screenshot that I uploaded upper, we can enable `Slow Search Logs` and 3 other kinds of logs to monitoring AOS clusters.

However, there is no resources or methods for connecting `CloudWatch Access Policy` to specific `CloudWatch Log Group`.
<img width="844" alt="image" src="https://github.com/hashicorp/terraform-provider-aws/assets/9548599/f15ac663-ca13-491e-903a-4fe2ecb8920b">

### Workaround, but not solution with terraform
- I found `aws logs put-resouce-policy` command from [AWS CLI document](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/logs/put-resource-policy.html)

### Conclusion
- I want to connect between `aws_cloudwatch_log_resource_policy` to `aws_cloudwatch_log_group`.
- But, I think harshicorp/aws does not support to make this kind of connection yet.

### Affected Resource(s) and/or Data Source(s)

* aws_cloudwatch_log_resource_policy
* aws_cloudwatch_log_group

### Potential Terraform Configuration

```terraform
resource "aws_elasticsearch_domain" "service-log" {
  provider = aws.apne2
  ..
  log_publishing_options {
    enabled = true
    log_type = "ES_APPLICATION_LOGS"
    cloudwatch_log_group_arn = aws_cloudwatch_log_group.my_log_group.arn
    log_resource_policy = aws_cloudwatch_log_resource_policy.example.arn << # like this.
  }
}


resource "aws_cloudwatch_log_resource_policy" "example" {
  provider = aws.apne2

  policy_name = "example_policy"
  policy_document = {..}

}
```

### References

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/logs/put-resource-policy.html

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
