### ISSUE TITLE
[Bug]: Unable to destroy s3_object in a versioned bucket in 5.6.x

### ISSUE THREAD

**Issue by andyprinceuk** [hashicorp/terraform-provider-aws#32312]
### Terraform Core Version

1.3.9

### AWS Provider Version

5.6.0,5.6.1

### Affected Resource(s)

aws_s3_object

### Expected Behavior

Running destroy for an aws_s3_object in a versioned bucket should delete the object

### Actual Behavior

Destroy fails

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: deleting S3 Bucket (ap-test-bucket-uw2) Object (some-key.json): InvalidArgument: Invalid attribute name specified.
│       status code: 400, request id: ..., host id: ...
│ 
│
```

### Terraform Configuration Files

```
provider "aws" {
  region = "us-west-2"
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.6.1"
    }
  }
}

resource "aws_s3_bucket" "example" {
  bucket = "ap-test-bucket-uw2"
}

resource "aws_s3_bucket_versioning" "example" {
  bucket = aws_s3_bucket.example.id

  versioning_configuration {
    status = "Enabled"
    # status = "Suspended"
  }
}

resource "aws_s3_object" "example" {
  bucket   = aws_s3_bucket.example.id
  content  = jsonencode({
    some = "data"
  })
  key      = "some-key.json"

  depends_on = [ aws_s3_bucket_versioning.example ]
}
```

### Steps to Reproduce

```
terraform apply
terraform destroy
```

### Important Factoids

One difference observed between 5.5.0 and 5.6.0 in the DELETE API call is in the authorization header indicating an additional header:
5.5.0:
```
http.request.header.authorization="AWS4-HMAC-SHA256 Credential=AKIA************VOIA********0/us-west-2/s3/aws4_request, Sign**********host;x-amz-content-sha256;x-amz-date, Signature=*****"
```

5.6.0:
```
http.request.header.authorization="AWS4-HMAC-SHA256 Credential=AKIA************VOIA********0/us-west-2/s3/aws4_request, Sign**********host;x-amz-content-sha256;x-amz-date;x-amz-optional-object-attributes, Signature=*****"
```
with that header being empty:
```
... http.request.body= http.request.header.x_amz_optional_object_attributes= net.peer.name=...
```

Furthermore, this also reproduces if the bucket versioning is set to "Suspended" as well as "Enabled"

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@andyprinceuk Thanks for raising this issue.
It has already been noticed in #32307. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by andyprinceuk** [comment]
Thanks @ewbankkit
