### ISSUE TITLE
[Docs]: aws_securityhub_standards_subscription invalid ARN

### ISSUE THREAD

**Issue by dominic-oconnor** [hashicorp/terraform-provider-aws#32314]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_standards_subscription

### Description

Using the `standards_arn` options in the document results in an error:
```
"standards_arn" (arnawssecurityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0) is an invalid ARN: arn: invalid prefix
```

Each of the examples in the documentation is missing colons:
* `arnawssecurityhub:${var.region}::standards/aws-foundational-security-best-practices/v/1.0.0` should be `arn:aws:securityhub:${var.region}::standards/aws-foundational-security-best-practices/v/1.0.0`
* `arnawssecurityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0` should be `arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0`
* etc.

<img width="586" alt="Screenshot 2023-06-30 at 10 00 50 AM" src="https://github.com/hashicorp/terraform-provider-aws/assets/385739/d34a7079-2b03-417f-8c71-36e431af4975">

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @dominic-oconnor 👋 Thank you for taking the time to raise this! This was a result of a bug in the Terraform Registry that has since been corrected. Since this has been resolved, I'll go ahead and close this issue.
