### ISSUE TITLE
[Bug]: Unclear or misleading warning in plan for `aws_db_instance` resource

### ISSUE THREAD

**Issue by cblkwell** [hashicorp/terraform-provider-aws#32315]
### Terraform Core Version

1.3.6

### AWS Provider Version

4.67, 5.6.1

### Affected Resource(s)

* `aws_db_instance`

### Expected Behavior

When running a plan for an `aws_db_instance`, the `password` value would presumably be listed as a sensitive value and not displayed to in the plan or apply without issue.

Alternatively, we would expect that *if* this error showed up:

```
      # Warning: this attribute value will no longer be marked as sensitive
      # after applying this change.
      ~ password                              = (sensitive value)
```

...then when the plan was next run, the password *would* be displayed (although this is obviously not desired behavior!). It may just be that the documentation needs to be improved or this warning needs to be more clear; the docs for this resource do say:

> [password](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#password) - (Required unless manage_master_user_password is set to true or unless a snapshot_identifier or replicate_source_db is provided or manage_master_user_password is set.) Password for the master DB user. Note that this may show up in logs, and it will be stored in the state file. Cannot be set if manage_master_user_password is set to true.

...but it is unclear how/why this may show up in logs (is the plan a log in this sense, or does that mean that if you are doing more extensive logging it may show up there since it is stored in state?). I suspect this is just a case where what the user should expect should be more clear. It also could be that the way we're supplying this (via a Secrets Manager secret value) is carrying through the `sensitive` flag.

### Actual Behavior

In actuality, this is the plan that we get for this instance:

```
  # module.redoxservices_rds.aws_db_instance.primary_instance will be updated in-place
  ~ resource "aws_db_instance" "primary_instance" {
        id                                    = "REDACTED"
      # Warning: this attribute value will no longer be marked as sensitive
      # after applying this change.
      ~ password                              = (sensitive value)
      ~ tags                                  = {
          ~ "REDACTED_TAG"  = "0" -> "-1"
            # (10 unchanged elements hidden)
        }

        ...
    }
```

After an apply, on a subsequent plan, we get the *same* message, with the value marked as sensitive. It is not clear why that warning pops up, but I suspect it may be related to the fact that the password is a null value in state (see https://github.com/hashicorp/terraform-provider-aws/issues/32159). This caused a bit of concern for users who do not use Terraform often and thought this was going to expose the database password in plans, CICD logs, etc.

### Terraform Configuration Files

This instance is created via a module, where `var.use_existing_password = true` in this code in the module:

```hcl
resource "aws_db_instance" "primary_instance" {
  allocated_storage                   = var.disk_size
  apply_immediately                   = "true"
  auto_minor_version_upgrade          = var.auto_minor_version_upgrade
  allow_major_version_upgrade         = "true"
  backup_retention_period             = var.backup_retention_period
  backup_window                       = var.backup_window
  ca_cert_identifier                  = "rds-ca-2019"
  db_subnet_group_name                = var.subnet_group
  deletion_protection                 = var.deletion_protection
  enabled_cloudwatch_logs_exports     = ["postgresql", "upgrade"]
  engine                              = var.engine
  engine_version                      = var.engine_version
  iam_database_authentication_enabled = "true"
  identifier                          = var.db_name
  instance_class                      = var.instance_type
  monitoring_interval                 = "10"
  monitoring_role_arn                 = data.aws_iam_role.rds_enhanced_monitoring_role.arn
  multi_az                            = var.multi_az
  parameter_group_name                = var.parameter_group_name
  password                            = var.use_existing_password ? jsondecode(data.aws_secretsmanager_secret_version.original_secret[0].secret_string)["master_password"] : jsondecode(aws_secretsmanager_secret_version.new_secret[0].secret_string)["master_password"]

  performance_insights_enabled          = "true"
  performance_insights_retention_period = "731"
  skip_final_snapshot                   = var.skip_final_snapshot
  snapshot_identifier                   = var.snapshot_id
  storage_encrypted                     = "true"
  storage_type                          = var.storage_type
  iops                                  = var.iops
  username                              = var.username
  vpc_security_group_ids                = [data.aws_security_group.rds.id]

  tags = merge(module.base.default_tags, {
    Name = var.db_name
  })
}
```

(Yes, we plan to move to using `manage_master_user_password` in the future)

### Steps to Reproduce

In order to reproduce, you need an existing `aws_db_instance` with a password set, and all that appears to be required after that is changing *another* attribute of the resource (in this case, it was a tag), which prompts it to actually try and manipulate the resource (otherwise, you will get a no-change plan).

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.

For what it's worth, this was likely more of a Terraform Core issue, since that argument is [marked as `Sensitive` in the schema](https://github.com/hashicorp/terraform-provider-aws/blob/6d700adee96b3479caf4852c07a15902aee3278b/internal/service/rds/instance.go#L436).
