### ISSUE TITLE
[Bug]: aws_s3_objects Invalid attribute name specified

### ISSUE THREAD

**Issue by ChauAnhTuan** [hashicorp/terraform-provider-aws#32316]
### Terraform Core Version

v1.5.1

### AWS Provider Version

> v5.6.0

### Affected Resource(s)

data "aws_s3_objects" "kubectl" {
  provider = aws.west

  bucket = "amazon-eks"

  prefix = "1.27"

  max_keys = 10
}

### Expected Behavior

{
      + bucket          = "amazon-eks"
      + common_prefixes = []
      + delimiter       = null
      + encoding_type   = null
      + fetch_owner     = null
      + id              = "amazon-eks"
      + keys            = [
          + "1.27.1/2023-04-19/bin/darwin/amd64/aws-iam-authenticator",
          + "1.27.1/2023-04-19/bin/darwin/amd64/aws-iam-authenticator.md5",
          + "1.27.1/2023-04-19/bin/darwin/amd64/aws-iam-authenticator.sha1",
          + "1.27.1/2023-04-19/bin/darwin/amd64/aws-iam-authenticator.sha256",
          + "1.27.1/2023-04-19/bin/darwin/amd64/kubectl",
          + "1.27.1/2023-04-19/bin/darwin/amd64/kubectl.md5",
          + "1.27.1/2023-04-19/bin/darwin/amd64/kubectl.sha1",
          + "1.27.1/2023-04-19/bin/darwin/amd64/kubectl.sha256",
          + "1.27.1/2023-04-19/bin/linux/amd64/aws-iam-authenticator",
          + "1.27.1/2023-04-19/bin/linux/amd64/aws-iam-authenticator.md5",
        ]
      + max_keys        = 10
      + owners          = []
      + prefix          = "1.27"
      + start_after     = null
    }

### Actual Behavior

╷
│ Error: listing S3 Bucket (amazon-eks) Objects: InvalidArgument: Invalid attribute name specified.
│       status code: 400, request id: 4XA7N78GJ2TRWZZV, host id: u06zP6U+6HwhwEpd8Qc0kq+ZW0Uzq6Gnz2WkAVoDEj9MV2L/FLwhBkmozoTRkCSzGA6gqsrnpv8=
│ 
│   with data.aws_s3_objects.kubectl,
│   on s3.tf line 9, in data "aws_s3_objects" "kubectl":
│    9: data "aws_s3_objects" "kubectl" {
│ 
╵

### Terraform Configuration Files

provider "aws" {
  alias = "west"

  region = "us-west-2"
#  version = "5.5.0"
  version = ">= 5.6.0"
}

data "aws_s3_objects" "kubectl" {
  provider = aws.west

  bucket = "amazon-eks"

  prefix = "1.27"

  max_keys = 10
}

### Steps to Reproduce

terrafrom init
terrafrom apply

### Would you like to implement a fix?

None

**Comment by ednxzu** [comment]
Can confirm, we're seeing this too.

**Comment by ewbankkit** [comment]
@ChauAnhTuan Thanks for raising this issue.
It has already been noticed in #32307. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
