### ISSUE TITLE
[Docs]: aws_wafv2_regex_pattern_set can only handle 10 regular_expression

### ISSUE THREAD

**Issue by FransUrbo** [hashicorp/terraform-provider-aws#32311]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_regex_pattern_set#regular-expression

### Description

I have a module which takes a list of regexp strings. That list is then used by the `aws_wafv2_regex_pattern_set` resource to create one `regular_expression { regex_string = <string> }` per entry:

```
variable "string_match" {
  description                           = "Strings to match and block"
  type                                  = list(string)
  default                               = null
}

resource "aws_wafv2_regex_pattern_set" "string_match" {
  count                         = var.string_match != null ? 1 : 0

  name                          = var.prefix
  description                   = "STRING set - ${var.prefix}"
  scope                         = var.scope

  dynamic "regular_expression" {
    for_each = var.string_match
    content {
      regex_string = regular_expression.value
    }
  }
}
```

When I added the eleventh entry in that list, I got an error from TF/AWS that said it can only handle ten entries.

The solution is to split this up with `chunklist()` in a local and then use that instead:
```
locals {
  # The `aws_wafv2_regex_pattern_set` resource can only handle ten regex entries.
  # So split it up in entries of ten and create a map from that.
  string_match                          = {
    for key, val in chunklist(var.string_match, 10) : key => val
  }
}

resource "aws_wafv2_regex_pattern_set" "string_match" {
  for_each                      = local.string_match

  name                          = "${var.prefix}-${each.key}"
  description                   = "STRING set - ${var.prefix}-${each.key}"
  scope                         = var.scope

  dynamic "regular_expression" {
    for_each = each.value
    content {
      regex_string = regular_expression.value
    }
  }
}
```

This will create one `aws_wafv2_regex_pattern_set` resource for every ten regex entry. Another important update is the `name` attribute. Each resource must be unique, so suffixing it with the number will suffice.

A note about this limitation would suffice, but feel free to use my code as additional example.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @FransUrbo 👋 Thank you for taking the time to raise this! I've opened a pull request to add a note about this to the documentation.
