### ISSUE TITLE
[Bug]: AWS provider issue aws_quicksight_vpc_connection can't process subnet_ids

### ISSUE THREAD

**Issue by CatLava** [hashicorp/terraform-provider-aws#32322]
### Terraform Core Version

v1.5.2

### AWS Provider Version

5.6.2

### Affected Resource(s)

aws_quicksight_vpc_connection
The subnet_ids field has an issue parsing strings

### Expected Behavior

take in a list of strings to indicate subnet ids. 

### Actual Behavior

I get an errror that this is a provider issue

### Relevant Error/Panic Output Snippet

```shell
[dev:account/quicksight] Planning failed. Terraform encountered an error while generating this plan.
[dev:account/quicksight]
[dev:account/quicksight] ╷
[dev:account/quicksight] │ Error: Value Conversion Error
[dev:account/quicksight] │
[dev:account/quicksight] │   with aws_quicksight_vpc_connection.quicksight_to_rds,
[dev:account/quicksight] │   on main.tf line 134, in resource "aws_quicksight_vpc_connection" "quicksight_to_rds":
[dev:account/quicksight] │  134: resource "aws_quicksight_vpc_connection" "quicksight_to_rds" {
[dev:account/quicksight] │
[dev:account/quicksight] │ An unexpected error was encountered while verifying an attribute value
[dev:account/quicksight] │ matched its expected type to prevent unexpected behavior or panics. This is
[dev:account/quicksight] │ always an error in the provider. Please report the following to the
[dev:account/quicksight] │ provider developer:
[dev:account/quicksight] │
[dev:account/quicksight] │ Expected type: types.ObjectType["create":basetypes.StringType,
[dev:account/quicksight] │ "delete":basetypes.StringType, "update":basetypes.StringType]
[dev:account/quicksight] │ Value type: types.ObjectType["create":basetypes.StringType,
[dev:account/quicksight] │ "delete":basetypes.StringType, "update":basetypes.StringType]
[dev:account/quicksight] │ Path: timeouts
```

### Terraform Configuration Files

I'm using terragrunt

### Steps to Reproduce

Try and create the quicksight resource with any array of strings as subnet ids.

### Would you like to implement a fix?

None

**Comment by CatLava** [comment]
This was not an issue in aws provider version = "5.2.0" -> I found this issue occurs in every version post 5.3 and up until current of 5.6.2

**Comment by justinretzolk** [comment]
Hey @CatLava 👋 Thank you for taking the time to raise this! So that we have the necessary information in order to look into this, can you supply a sample Terraform configuration that exhibits this behavior, as well as debug logs (redacted as needed)?

**Comment by CatLava** [comment]
resource "aws_quicksight_vpc_connection" "quicksight_to_rds" {
  vpc_connection_id = "rds-account"
  name              = "rds-account"
  role_arn          = aws_iam_role.quicksight_vpc_connection_role.arn

  security_group_ids = [aws_security_group.quicksight.id]
  subnet_ids         = data.aws_subnets.private.ids

  timeouts {
    create = "5m"
  }

  tags = local.tags
}

I've also plugged in a list of subnet_ids hardcoded ["subnet-1234", "subnet-12345"]
This config deploys great in aws provider 5.2.0 -> does not in any version after.

**Comment by CatLava** [comment]
ahhh double checked after another reference, this is due to the timeouts block not subnets_id. If I remove timeouts, this all deploys fine.

**Comment by bflad** [comment]
@justinretzolk FYI -- https://github.com/hashicorp/terraform-plugin-framework-timeouts/pull/72
