### ISSUE TITLE
[Docs]: Inaccurate documentation for aws_ssm_association parameter max_errors 

### ISSUE THREAD

**Issue by flebotany** [hashicorp/terraform-provider-aws#32320]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_association.html#max_errors

### Description

The statement "[max_errors](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_association.html#max_errors) - (Optional) The number of errors that are allowed before the system stops sending requests to run the association on additional targets. You can specify a number, for example 10, or a percentage of the target set, for example 10%." leads developers to believe that this is the maximum total for a given association. Indeed the variable implies this as well. Unfortunately, the [actual underlying AWS API has](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-state-manager-targets-and-rate-controls.html) this to say "If you specify an **absolute number of three errors, for example, State Manager sends the stop command when the fourth error** is returned. If you specify 0, then State Manager sends the stop command after the first error result is returned." (emphasis added)

Thus:
max_errors = 0 # 1 error
max_errors = 1 # 2 errors

The caveat / clarification should at least be included in the provider documentation to avoid outages (e.g. if someone runs `max_concurrency = 1` and `max_errors = 1` expecting at most 1 of their instances to be down and gets 2, it could be bad for them.

### References

https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-state-manager-targets-and-rate-controls.html

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @flebotany 👋 Thank you for taking the time to raise this! I've opened a documentation PR to try to make this a bit more clear.
