### ISSUE TITLE
[Docs]: Invalid ARN on aws_ssoadmin_managed_policy_attachment resource

### ISSUE THREAD

**Issue by flakronrexhepajreply** [hashicorp/terraform-provider-aws#32337]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssoadmin_managed_policy_attachment

### Description

On the Example Usage section for aws_ssoadmin_managed_policy_attachment resource, there is a typo on the IAM managed policy ARN. In the resource attribute managed_policy_arn, the ARN of the IAM managed policy is "_arnawsiam:awspolicy/AlexaForBusinessDeviceSetup_", which is an invalid AWS ARN. The correct one should be: "_**arn:aws:iam::aws:policy/AlexaForBusinessDeviceSetup**_".

### References

AlexaForBusinessDeviceSetup IAM Managed Policy: https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AlexaForBusinessDeviceSetup.html

### Would you like to implement a fix?

None

**Comment by wasup-yash** [comment]
Hey, I would like to work on this issue, can you provide me the reference file/repo where it needs to be updated so it will be quick :)

**Comment by flakronrexhepajreply** [comment]
@wasup-yash it's here https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/ssoadmin_managed_policy_attachment.html.markdown - but as @mattburgess mentioned in the other ticket, seems to be a rendering issue, rather than anything that needs to be changed on the md file.

**Comment by wasup-yash** [comment]
so seems like i cannot do much in this XD

**Comment by justinretzolk** [comment]
Hey all 👋 Thank you for taking the time to raise this! This was the result of a bug in the Registry which has now been corrected. As such, we'll close this issue out.
