### ISSUE TITLE
[Bug]: `aws_inspector2_enabler` fails to create on 5.6.0 due to incorrect resource type constant

### ISSUE THREAD

**Issue by irth** [hashicorp/terraform-provider-aws#32334]
### Terraform Core Version

1.4.6

### AWS Provider Version

5.6.0, 5.6.2, be00acc

### Affected Resource(s)

* resource `aws_inspector2_enabler`

### Expected Behavior

```terraform
data "aws_caller_identity" "this" {}

resource "aws_inspector2_enabler" "this" {
  account_ids = [data.aws_caller_identity.this.account_id]

  resource_types = ["EC2", "ECR", "LAMBDA"]
}
```

Applying the above configuration should enable Amazon Inspector, enabling scanning EC2 instances, ECR registries and Lambda functions.

### Actual Behavior

The provider correctly enables Inspector with EC2/ECR/Lambda scanning, however after enabling the service, the `resourceEnablerCreate` function (`internal/services/inspector2/enabler.go`) checks if it needs to disable any type of resource scans:

```go
	st, err := waitEnabled(ctx, conn, accountIDs, d.Timeout(schema.TimeoutCreate))
	if err != nil {
		return append(diags, create.DiagError(names.Inspector2, create.ErrActionWaitingForCreation, ResNameEnabler, d.Id(), err)...)
	}

	var disableAccountIDs []string
	for acctID, acctStatus := range st {
		resourceStatuses := acctStatus.ResourceStatuses
		for _, resourceType := range typeEnable {
			delete(resourceStatuses, resourceType)
		}
		if len(resourceStatuses) > 0 {
			disableAccountIDs = append(disableAccountIDs, acctID)
			in := &inspector2.DisableInput{
				AccountIds:    []string{acctID},
				ResourceTypes: maps.Keys(resourceStatuses),
			}

			_, err := conn.Disable(ctx, in)
			if err != nil {
				return append(diags, create.DiagError(names.Inspector2, create.ErrActionUpdating, ResNameEnabler, id, err)...)
			}
		}
	}
```

The `typeEnable` slice contains `["EC2", "ECR", "LAMBDA"]` before the for loop runs, the acctStatus.ResourceStatuses map has the keys `["EC2", "ECR", "LAMBDA", "LAMBDACODE"]`.

After the inner for loop deletes the resource types that should be enabled, we are left with `LAMBDACODE`, which is then passed to the `Disable` API call. At this point, the code fails, because the value should be `LAMBDA_CODE`, so it fails validation on the AWS API side.

This happens because the `AccountStatuses` function (from the same file) used to fetch the values from the API, gets a struct with a `LambdaCode` field, and uses `strings.ToUpper` to convert to a `types.ResourceScanType` constant from `github.com/aws/aws-sdk-go-v2/service/inspector2/types`:

```go
		if a.AccountId == nil || a.State == nil {
			continue
		}
		status := AccountResourceStatus{
			Status:           a.State.Status,
			ResourceStatuses: make(map[types.ResourceScanType]types.Status, len(enum.Values[types.ResourceScanType]())),
		}
		var m map[string]*types.State
		e := mapstructure.Decode(a.ResourceState, &m)
		if e != nil {
			err = multierror.Append(err, e)
			continue
		}
		for k, v := range m {
			status.ResourceStatuses[types.ResourceScanType(strings.ToUpper(k))] = v.Status
		}
		results[aws.ToString(a.AccountId)] = status
```

The correct value for the constant is `LAMBDA_CODE`.

### Relevant Error/Panic Output Snippet

```shell
│ Error: updating Amazon Inspector Enabler ([REDACTED]-EC2:ECR:LAMBDA): operation error Inspector2: Disable, https response error StatusCode: 400, RequestID: [REDACTED], ValidationException: 1 validation error detected: Value at 'resourceTypes' failed to satisfy constraint: Member must satisfy constraint: [Member must satisfy enum value set: [LAMBDA_CODE, LAMBDA, ECR, EC2]]
```

### Terraform Configuration Files

```terraform
data "aws_caller_identity" "this" {}

resource "aws_inspector2_enabler" "this" {
  account_ids = [data.aws_caller_identity.this.account_id]

  resource_types = ["EC2", "ECR", "LAMBDA"]
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.6.0"
    }
  }
}
```

### Steps to Reproduce

1. paste the code into a tf file
2. init & apply on an account with Inspector disabled
3. wait for the error

### Would you like to implement a fix?

Yes

**Comment by irth** [comment]
example fix, no time to do a proper pull request currently unfortunately:

```diff
diff --git a/internal/service/inspector2/enabler.go b/internal/service/inspector2/enabler.go
index 5ca18829f8..b65d4477fb 100644
--- a/internal/service/inspector2/enabler.go
+++ b/internal/service/inspector2/enabler.go
@@ -536,6 +536,9 @@ func AccountStatuses(ctx context.Context, conn *inspector2.Client, accountIDs []
 			continue
 		}
 		for k, v := range m {
+			if k == "LambdaCode" {
+				k = "LAMBDA_CODE"
+			}
 			status.ResourceStatuses[types.ResourceScanType(strings.ToUpper(k))] = v.Status
 		}
 		results[aws.ToString(a.AccountId)] = status
diff --git a/website/docs/r/inspector2_enabler.html.markdown b/website/docs/r/inspector2_enabler.html.markdown
index 64453a5664..38e2279f74 100644
--- a/website/docs/r/inspector2_enabler.html.markdown
+++ b/website/docs/r/inspector2_enabler.html.markdown
@@ -41,7 +41,7 @@ The following arguments are required:
 * `account_ids` - (Required) Set of account IDs.
   Can contain one of: the Organization's Administrator Account, or one or more Member Accounts.
 * `resource_types` - (Required) Type of resources to scan.
-  Valid values are `EC2`, `ECR`, and `LAMBDA`.
+  Valid values are `EC2`, `ECR`, `LAMBDA` and `LAMBDA_CODE`.
   At least one item is required.
 
 ## Attributes Reference
```

**Comment by daveshepherd** [comment]
I'm seeing this issue with provider 5.7.0.

**Comment by faaizzcr** [comment]
Same issue still occurs with provider 5.8.0.

**Comment by ScottCruzen0** [comment]
Also happens with provider 5.10.0

**Comment by ScottCruzen0** [comment]
> example fix, no time to do a proper pull request currently unfortunately:
> ...

This fix worked for me.

**Comment by CyrusTC** [comment]
Also happens in provider 5.16.1

**Comment by p5** [comment]
Thank you for creating the PR for this.  
Also facing the same issue so will be chasing up with our AWS account manager to see if they can do anything to get this looked at.  Hopefully AWS and the maintainers have a good relationship.

**Comment by statlus** [comment]
I'm also seeing this with provider 5.20.0.
