### ISSUE TITLE
[Enhancement]: Add client side timestamps enablement to aws_keyspaces_table resource

### ISSUE THREAD

**Issue by carlduevel** [hashicorp/terraform-provider-aws#32338]
### Description

Client side timestamps are a table level feature (s. https://docs.aws.amazon.com/keyspaces/latest/devguide/client-side-timestamps.html) not yet available in the provider but in the go client (s. https://github.com/aws/aws-sdk-go/blob/v1.44.294/service/keyspaces/api.go#L1780-L1787).

### Affected Resource(s) and/or Data Source(s)

* aws_keyspaces_table

### Potential Terraform Configuration

```terraform
resource "aws_keyspaces_table" "logstore" {
[...]

  client_side_timestamps {
    status = "ENABLED"
  }

}
```

### References

https://docs.aws.amazon.com/keyspaces/latest/devguide/client-side-timestamps-how-to.html

### Would you like to implement a fix?

Yes

**Comment by ewbankkit** [comment]
[Announcement](https://aws.amazon.com/about-aws/whats-new/2023/03/amazon-keyspace-apache-cassandra-client-side-timestamps/).
