### ISSUE TITLE
[Docs]: Inaccurate documentation for aws_eks_node_group aws_iam_role_policy_attachments

### ISSUE THREAD

**Issue by fr-koichi** [hashicorp/terraform-provider-aws#32331]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#ami_type

### Description

Please correct these policy arns.

AS-IS
```
resource "aws_iam_role_policy_attachment" "example-AmazonEKSWorkerNodePolicy" {
  policy_arn = "arnawsiam:awspolicy/AmazonEKSWorkerNodePolicy"
  role       = aws_iam_role.example.name
}

resource "aws_iam_role_policy_attachment" "example-AmazonEKS_CNI_Policy" {
  policy_arn = "arnawsiam:awspolicy/AmazonEKS_CNI_Policy"
  role       = aws_iam_role.example.name
}

resource "aws_iam_role_policy_attachment" "example-AmazonEC2ContainerRegistryReadOnly" {
  policy_arn = "arnawsiam:awspolicy/AmazonEC2ContainerRegistryReadOnly"
  role       = aws_iam_role.example.name
}
```

TO-BE
```
resource "aws_iam_role_policy_attachment" "example-AmazonEKSWorkerNodePolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
  role       = aws_iam_role.example.name
}

resource "aws_iam_role_policy_attachment" "example-AmazonEKS_CNI_Policy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
  role       = aws_iam_role.example.name
}

resource "aws_iam_role_policy_attachment" "example-AmazonEC2ContainerRegistryReadOnly" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
  role       = aws_iam_role.example.name
}
```

### Would you like to implement a fix?

None

**Comment by mattburgess** [comment]
@justinretzolk - I took a quick look at this and it appears to be some kind of rendering/generation error from the source as the code [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/eks_node_group.html.markdown?plain=1#L101-L114). Similar issues have been reported at #32337 and #32358

**Comment by justinretzolk** [comment]
Hey all 👋 Thank you for taking the time to raise this, and to you @mattburgess for collecting that information! The Registry team has pushed a fix for this bug, so this is now resolved. With that in mind, I'll go ahead and close this issue out 🎉
