### ISSUE TITLE
Feature request: IAM Service Specific credentials

### ISSUE THREAD

**Issue by honzous** [hashicorp/terraform-provider-aws#3233]
Hi guys,

Service specific credentials could be used for HTTPS access to CodeCommit right now, assuming wider usage later on.

### Terraform Version
```
Terraform v0.11.2
+ provider.aws v1.8.0
```

### Affected Resource(s)
- aws_iam_user

### Terraform Configuration Files
Could be derived from https://docs.aws.amazon.com/IAM/latest/APIReference/API_ServiceSpecificCredential.html

### Expected Behavior
```hcl
resource "aws_iam_service_specific_credential" "codecommit" {
  service_name = "codecommit"
  username = "my_user"
}
```

**Comment by fbe** [comment]
Need that feature, too. We have a project with high security requirements and no service must call the internet directly (only using http proxies). To work with code commit, auto generated https git credentials are mandatory.

**Comment by colin-lyman** [comment]
+1

**Comment by colin-lyman** [comment]
As a short term workaround for anyone in need:
```
variable "AWS_USERS" {
  description = "List of AWS Users"
  type = "list"
  default = ["name.one","name.two"]
}

resource "aws_iam_user" "users" {
  name = "${element(var.AWS_USERS, count.index)}"
  count = "${length(var.AWS_USERS)}"
  provisioner "local-exec" {
    command = "aws iam create-service-specific-credential --user-name ${element(var.AWS_USERS, count.index)} --service-name codecommit.amazonaws.com >> credentials.txt"
  }
}
```

**Comment by samarone** [comment]
@colin-lyman  thanks for your sugestion, works fine for me. I added more lines to policy entry

```
...
provisioner "local-exec" {
command = "aws iam attach-user-policy --policy-arn arn:aws:iam::aws:policy/AWSCodeCommitFullAccess --user-name ${element(var.AWS_USERS, count.index)}"
}
...
```

**Comment by dekimsey** [comment]
Note, these work-arounds don't really work very well because the API to manipulate the credentials will only display the ServicePassword field once during creation ala iam access keys.

There doesn't seem to be any way I can determine to have terraform hold on to that output since null_resource/local-exec doesn't have a way of saving it's output in the state.

It seems that an API update to include this as a managed resource is definitely required. If someone has a work-around that works well, I'd be very interested to see how it was accomplished.

**Comment by sethbacon** [comment]
@bflad  Any way to bump this up? The work-around won't work on TF Cloud and I'd really like to be able to manage a service account for codecommit with terraform.

**Comment by arihantsurana** [comment]
Service specific credentials are also required to access aws managed cassandra. It would be great if there was a resource similar to aws_iam_access_keys

Expected behaviour:
```
resource "aws_iam_service_specific_credential" "cassuser" {
  user    = "${aws_iam_user.lb.name}"
  pgp_key = "keybase:some_person_that_exists"
  service_name = "cassandra.amazonaws.com"
}

resource "aws_iam_user" "cassuser" {
  name = "cassuser"
  path = "/system/"
}

output "secret" {
  value = "${aws_iam_service_specific_credential.cassuser.encrypted_secret}"
}

```

**Comment by nicolebeaumont** [comment]
This would be a great feature, especially for cassandra

**Comment by samuelfaj** [comment]
Waiting for it!

**Comment by lithiumoxide** [comment]
With Keyspaces now a service on AWS I have a requirement for this feature, along with the option to return a password encrypted with a PGP key.

**Comment by andreynpetrov** [comment]
> There doesn't seem to be any way I can determine to have terraform hold on to that output since null_resource/local-exec doesn't have a way of saving it's output in the state.
@dekimsey You can try to save output of "aws iam create-service-specific-credential..." to aws secret manager with "aws secretsmanager create-secret..." and then get it with terraform: "data.aws_secretsmanager_secret_version.myname"

**Comment by jverce** [comment]
Anyone looking at this? There's already a PR from a few months ago: #16185 
I already took a look and the implementation looks good except for a few details, and it uses the native AWS SDK.

**Comment by sanarena** [comment]
Any update on this one?

**Comment by sanarena** [comment]
worked!
