### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by Sherm4nLC** [hashicorp/terraform-provider-aws#32358]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codedeploy_deployment_group

### Description

malformed arn in documentation snippet
It says
```
policy_arn = "arnawsiam:awspolicy/service-role/AWSCodeDeployRole"
```
where it shoud
```
policy_arn = "arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole"
```
Note missing `:` in first instance

### Would you like to implement a fix?

Yes

**Comment by manmohanmirkar123** [comment]
I am interested in working on this issue.

**Comment by justinretzolk** [comment]
Hey @Sherm4nLC 👋 Thank you for taking the time to raise this! This was the result of a bug on the Registry side of things, which the team has pushed a fix for. Since this has now been resolved, I'll go ahead and close this issue out.
