### ISSUE TITLE
[Bug]: aws_db_proxy_target only allows lowercase characters in db_instance_identifier

### ISSUE THREAD

**Issue by ccarstens** [hashicorp/terraform-provider-aws#32364]
### Terraform Core Version

1.5.2

### AWS Provider Version

5.6.2

### Affected Resource(s)

`aws_db_proxy_target` -> `db_instance_identifier`

### Expected Behavior

The `aws_db_proxy_target ` should accept a db identifier like `db-GFRAFU3HD3G274HD83HE82Z4ID` since it is what has been created and needs to be hooked up.

### Actual Behavior

An error message about there being a lower case constraint on the `db_instance_identifier ` property.

### Relevant Error/Panic Output Snippet

```shell
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: only lowercase alphanumeric characters and hyphens allowed in "db_instance_identifier"
│ 
│   with module.gvc-app.module.db.module.proxy[0].aws_db_proxy_target.dbproxy_target,
│   on ../../modules/dbproxy/main.tf line 40, in resource "aws_db_proxy_target" "dbproxy_target":
│   40:   db_instance_identifier = var.db_instance
│ 
╵
```

### Terraform Configuration Files

[tf.zip](https://github.com/hashicorp/terraform-provider-aws/files/11948267/tf.zip)

### Steps to Reproduce

```shell
cd tf/us-west-2/region && terraform apply
cd tf/us-west-2/staging && terraform apply
```

### Debug Output

Acquiring state lock. This may take a few moments...
module.gvc-app.data.terraform_remote_state.global: Reading...
module.gvc-app.module.db.data.aws_ssm_parameter.db_pass: Reading...
module.gvc-app.module.db.module.proxy[0].data.aws_ssm_parameter.db_pass: Reading...
module.gvc-app.module.db.module.proxy[0].data.aws_security_group.rds_sg: Reading...
module.gvc-app.module.db.module.proxy[0].data.aws_caller_identity.current: Reading...
module.gvc-app.module.db.module.proxy[0].aws_secretsmanager_secret.rds_secret: Refreshing state... [id=arn:aws:secretsmanager:us-west-2:722987513393:secret:gvc-staging-dbproxy-secret-auE2or]
module.gvc-app.module.db.module.proxy[0].aws_iam_role.rds_proxy_role: Refreshing state... [id=gvc-staging_rds_proxy_role]
module.gvc-app.module.execution_rules.aws_cloudwatch_event_rule.every_hour: Refreshing state... [id=gvc-staging-every-hour]
module.gvc-app.module.execution_rules.aws_cloudwatch_event_rule.every_ten_minutes: Refreshing state... [id=gvc-staging-every-ten-minutes]
module.gvc-app.module.execution_rules.aws_cloudwatch_event_rule.daily: Refreshing state... [id=gvc-staging-daily]
module.gvc-app.module.db.module.proxy[0].data.aws_caller_identity.current: Read complete after 1s [id=722987513393]
module.gvc-app.module.redis.data.aws_security_group.redis_sg: Reading...
module.gvc-app.module.db.data.aws_security_group.rds_sg: Reading...
module.gvc-app.module.db.module.proxy[0].data.aws_ssm_parameter.db_pass: Read complete after 1s [id=/gvc-staging/DB_PASS]
module.gvc-app.module.execution_rules.aws_cloudwatch_event_rule.every_five_minutes: Refreshing state... [id=gvc-staging-every-five-minutes]
module.gvc-app.module.db.data.aws_ssm_parameter.db_pass: Read complete after 1s [id=/gvc-staging/DB_PASS]
module.gvc-app.module.db.module.proxy[0].aws_secretsmanager_secret_version.rds_secret: Refreshing state... [id=arn:aws:secretsmanager:us-west-2:722987513393:secret:gvc-staging-dbproxy-secret-auE2or|005BE57C-FEE3-424D-AB70-75306394DEDC]
module.gvc-app.module.db.module.proxy[0].aws_iam_policy.rds_proxy_policy: Refreshing state... [id=arn:aws:iam::722987513393:policy/gvc-staging_rds_proxy_policy]
module.gvc-app.module.db.module.proxy[0].data.aws_security_group.rds_sg: Read complete after 1s [id=sg-0628b7dba2f29e697]
module.gvc-app.data.terraform_remote_state.global: Read complete after 2s
module.gvc-app.module.db.data.aws_subnets.private: Reading...
module.gvc-app.module.redis.data.aws_subnets.private: Reading...
module.gvc-app.module.db.data.aws_subnets.public: Reading...
module.gvc-app.module.db.module.proxy[0].data.aws_subnets.private: Reading...
module.gvc-app.module.db.module.proxy[0].aws_iam_role_policy_attachment.rds_proxy_policy_attach: Refreshing state... [id=gvc-staging_rds_proxy_role-20230111164844648300000001]
module.gvc-app.module.redis.data.aws_security_group.redis_sg: Read complete after 0s [id=sg-0e032352fb1c944dd]
module.gvc-app.module.db.data.aws_security_group.rds_sg: Read complete after 0s [id=sg-0628b7dba2f29e697]
module.gvc-app.module.db.data.aws_subnets.private: Read complete after 0s [id=us-west-2]
module.gvc-app.module.db.aws_db_subnet_group.gvc_rds: Refreshing state... [id=gvc-staging-rds]
module.gvc-app.module.redis.data.aws_subnets.private: Read complete after 1s [id=us-west-2]
module.gvc-app.module.redis.aws_elasticache_subnet_group.gvc_elasticache: Refreshing state... [id=gvc-staging-elasticache]
module.gvc-app.module.db.data.aws_subnets.public: Read complete after 1s [id=us-west-2]
module.gvc-app.module.db.module.proxy[0].data.aws_subnets.private: Read complete after 1s [id=us-west-2]
module.gvc-app.module.db.module.proxy[0].aws_db_proxy.dbproxy: Refreshing state... [id=gvc-staging-dbproxy]
module.gvc-app.module.db.aws_db_instance.db: Refreshing state... [id=db-GFRATR2TWR4FI3GJWTEH62FSZ4]
module.gvc-app.module.redis.aws_elasticache_cluster.redis_cache: Refreshing state... [id=gvc-staging-redis]
module.gvc-app.module.db.module.proxy[0].aws_db_proxy_default_target_group.default: Refreshing state... [id=gvc-staging-dbproxy]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: only lowercase alphanumeric characters and hyphens allowed in "db_instance_identifier"
│ 
│   with module.gvc-app.module.db.module.proxy[0].aws_db_proxy_target.dbproxy_target,
│   on ../../modules/dbproxy/main.tf line 40, in resource "aws_db_proxy_target" "dbproxy_target":
│   40:   db_instance_identifier = var.db_instance
│ 
╵
Releasing state lock. This may take a few moments...

### Would you like to implement a fix?

None

**Comment by trevorrea** [comment]
Could be related to https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-5-upgrade#resourceaws_db_proxy_target and https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-5-upgrade#resourceaws_db_instance ?

**Comment by ccarstens** [comment]
@trevorrea Yes switching to `identifier` fixed it, thank you for pointing this out!

**Comment by trevorrea** [comment]
No worries. Glad to be of help :)
