### ISSUE TITLE
[Docs]: "On This Page" shortcuts section is missing 

### ISSUE THREAD

**Issue by iamgeef** [hashicorp/terraform-provider-aws#32370]
### Documentation Link

Seems to be all pages, but here's an example: 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group

### Description

Unless I'm remembering incorrectly, the documentation always had an "On this Page" shortcut menu on the right hand side with different shortcuts to the Argument references, attribute references, import options etc but it's no longer there. 

### References

Example from other Terraform docs: 
![image](https://github.com/hashicorp/terraform-provider-aws/assets/10751405/ffabeedd-926f-4ab0-aec7-e355ecfc78c7)

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @iamgeef 👋 Thank you for taking the time to raise this! I've raised a ticket with the Registry team internally to have this looked at.

**Comment by justinretzolk** [comment]
The Registry team has updated me to let me know this is now resolved. Thank you again for taking the time to raise this so that we could track down that bug!
