### ISSUE TITLE
[Docs]: ARN colons missing from code examples

### ISSUE THREAD

**Issue by kinghuang** [hashicorp/terraform-provider-aws#32378]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy

### Description

Many of the code examples that use ARNs seem to be missing some colons when viewed on registry.terraform.io. For example, the import statement given for an `aws_iam_policy` resource shows the ARN as:

```
arnawsiam:123456789012policy/UsersManageOwnCredentials
```

But, it should be:

```
arn:aws:iam::123456789012:policy/UsersManageOwnCredentials
```

This problem exists on many (all?) documentation pages. It looks like single colons are being dropped and double colons are being reduced to single colons. Strangely, the colons are all present in the repo, but missing when viewed on `registry.terraform.io`.

<img width="863" alt="image" src="https://github.com/hashicorp/terraform-provider-aws/assets/27340/4644cd6c-1ee1-49e2-979b-f65b0321a2c8">

https://github.com/hashicorp/terraform-provider-aws/blob/3e7fea14ff3116ab7f7d65344b2732cdae56f0ad/website/docs/r/iam_policy.html.markdown?plain=1#L67-L69

### References

[Amazon Resource Names (ARNs)](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference-arns.html)

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @kinghuang 👋 Thank you very much for taking the time to raise this! I've raised a ticket to the Registry team internally so that we can take a look at this.

**Comment by kinghuang** [comment]
Thanks. I've tweaked the title to indicate that this applies to any code examples, not just import code examples.

**Comment by justinretzolk** [comment]
Thank you for the update! The Registry team was able to push a fix for this, so I'll go ahead and close this issue out. Thank you again for taking the time to let us know!
