### ISSUE TITLE
[Docs]: Missing documentation of filter_policy_scope for the aws_sns_topic_subscription

### ISSUE THREAD

**Issue by alexandreczg** [hashicorp/terraform-provider-aws#32403]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/3.6.0/docs/resources/sns_topic_subscription#filter_policy

### Description

Missing documentation on: `filter_policy_scope` argument

It was added [here](https://github.com/hashicorp/terraform-provider-aws/pull/28004)

### Would you like to implement a fix?

None

**Comment by alexandreczg** [comment]
I can work on this issue.

**Comment by justinretzolk** [comment]
Hey @alexandreczg 👋 It looks like you've linked to the documentation for version `3.6.0` of the provider, while this argument was added in version `4.42.0`. Looking at the current version of the documentation, the `filter_policy_scope` [is indeed documented](https://registry.terraform.io/providers/hashicorp/aws/5.7.0/docs/resources/sns_topic_subscription#filter_policy_scope). Given that's the case, we'll close this issue. Thank you for being willing to take a look at this! We're always looking for contributions, especially those that help improve the documentation!
