### ISSUE TITLE
[Docs]: Tree of contents does not behave consistently when navigating through items in the same service section

### ISSUE THREAD

**Issue by Miguel-Henriques** [hashicorp/terraform-provider-aws#32411]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/acm_certificate

### Description

The same documentation page produces different content trees when navigating through resources and data sources under the same service section.

![image](https://github.com/hashicorp/terraform-provider-aws/assets/49489051/21f4e55d-8b52-4eb2-8a21-47f660491a00)

![image](https://github.com/hashicorp/terraform-provider-aws/assets/49489051/8cbf590a-7117-42e2-8842-f42f5ef239f1)

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Potentially related: https://github.com/hashicorp/terraform-provider-aws/issues/32370

Hey @Miguel-Henriques 👋 Thank you for taking the time to raise this! I've raised a ticket with the Registry team internally to have this looked at.

**Comment by justinretzolk** [comment]
The Registry team has updated me to let me know this is now resolved. Thank you again for taking the time to raise this so that we could track down that bug!
