### ISSUE TITLE
[New Resource]: Add `aws_account_region` to manage regions enabled for an account

### ISSUE THREAD

**Issue by cristian98149** [hashicorp/terraform-provider-aws#32415]
### Description

Allow to specify regions to enable in aws organization member account. 

Today this option is configurable in this way: [https://docs.aws.amazon.com/accounts/latest/reference/manage-acct-regions.html#manage-acct-regions-enable-organization](url)

### Affected Resource(s) and/or Data Source(s)

aws_organizations_account

### Potential Terraform Configuration

```terraform
resource "aws_organizations_account" "account" {
  name  = "my_new_account"
  email = "john@doe.org"
  
  # list of regions to enable in this account
  regions = ["a,b,c"]
}
```

### References

https://docs.aws.amazon.com/accounts/latest/reference/manage-acct-regions.html#manage-acct-regions-enable-organization

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@cristian98149 Thanks for raising this issue.
It has already been noticed in #31300. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
