### ISSUE TITLE
[Bug]: aws_servicecatalog_provisioning_artifact - parallel for_each ( creation / destroy issues )

### ISSUE THREAD

**Issue by goural** [hashicorp/terraform-provider-aws#32450]
### Terraform Core Version

1.5.1

### AWS Provider Version

5.7.0

### Affected Resource(s)

when using for_each loop on artifacts (var.artifacts) for creating multiple versions of products artifact together , the loop gets stuck on still creating / destroying and keeps running.

Workaround I found is using parallelism - 
terraform apply -parallelism 1
terraform destroy -parallelism=1

However using the above, when I create launch constraint, aws_servicecatalog_constraint , its not able to finish in first apply run. 

multiple terraform apply and destroy command has to be run

### Expected Behavior

Expected is that on normal terraform apply and terraform destory , the multiple artifacts version be created and destroyed.

### Actual Behavior

After creating 1-2 artifacts for products, terraform get stuck on creating during terraform apply and on destroying in terraform destroy.

If I re-run the terraform apply or terraform destroy , the code successfully works 

### Relevant Error/Panic Output Snippet

```shell
Error: creating Service Catalog Constraint: ResourceNotFoundException: Resource not found.

 Error: associating Service Catalog Product with Portfolio: ResourceNotFoundException: Product prod-xxxx not found.

Error: waiting for Service Catalog Provisioning Artifact (pa-xxxxxx) to be deleted: timeout while waiting for state to become 'NOT_FOUND' (last state: 'AVAILABLE', timeout: 5m0s)
│ 
│ 
╵
╷
│ Error: creating Service Catalog Constraint: InvalidParametersException: Access denied while assuming the role arn:aws:iam::xxxxxx
```

### Terraform Configuration Files

```terraform
resource "aws_servicecatalog_provisioning_artifact" "artifacts" {
  for_each = var.artifacts

  product_id                  = aws_servicecatalog_product.product.id
  name                        = each.value.name
  description                 = each.value.description
  type                        = "TERRAFORM_OPEN_SOURCE"
  disable_template_validation = true
  template_url                = each.value.template_url
  depends_on = [
    aws_servicecatalog_portfolio.portfolio,
    aws_servicecatalog_product.product,
    aws_servicecatalog_product_portfolio_association.product_association
  ]
}

variable "provisioning_artifact_versions_s3" {
  type    = list(object({
    name                     = string
    type                     = string
    template_url             = string
    description              = string
    disable_template_validation = bool
  }))
  default = [
    {
      name                     = "v2"
      type                     = "TERRAFORM_OPEN_SOURCE"
      template_url             = "https://s3bucket.amazonaws.com/Artifacts/s3bucket.tar.gz"
      description              = "version 2"
      disable_template_validation = true
    },
    {
      name                     = "v2"
      type                     = "TERRAFORM_OPEN_SOURCE"
      template_url             = "https://s3bucket.amazonaws.com/Artifacts/s3bucket.tar.gz"
      description              = "version 3"
      disable_template_validation = true
    },
    {
      name                     = "v2"
      type                     = "TERRAFORM_OPEN_SOURCE"
      template_url             = "https://s3bucket.amazonaws.com/Artifacts/s3bucket.tar.gz"
      description              = "version 4"
      disable_template_validation = true
    },
    # Add more versions as needed
  ]
}
```

### Steps to Reproduce

Using the above code if we create -
svc catalog portfolio
2-3 products associated with the portfolio 
2-3 artifact versions associated with each product created above

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @goural 👋 Thank you for taking the time to raise this! So that we have the necessary information in order to look into this, can you supply debug logs (redacted as necessary) as well?

**Comment by abhishekkaulnagarro** [comment]
you can close this ticket
