### ISSUE TITLE
[Enhancement]: How to create an aws_ssm_association with Simple Execution

### ISSUE THREAD

**Issue by fracampit** [hashicorp/terraform-provider-aws#32471]
### Description

I cannot find a way to create an aws_ssm_association with Simple Execution using Terraform. The documentation doesn't include any details on that either.

If I use the following configuration:

```terraform
resource "aws_ssm_association" "start_rds_mondays_7am" {
  name             = "AWS-StartRdsInstance"
  association_name = "${local.name_prefix}-start-rds-mondays-7am"

  automation_target_parameter_name = "InstanceId"

  parameters = {
    "AutomationAssumeRole" = aws_iam_role.ssm_role.arn
    "InstanceId"           = module.rds_postgres.identifier
  }

  schedule_expression = "cron(0 00 7 ? * MON *)"

  apply_only_at_cron_interval = true

  targets {
    key    = "aws:NoOpAutomationTag"
    values = ["AWS-NoOpAutomationTarget-Value"]
  }
}
```

I get an association with a Rate Control execution.

If I remove

```terraform
 automation_target_parameter_name = "InstanceId"

  parameters = {
    "AutomationAssumeRole" = aws_iam_role.ssm_role.arn
    "InstanceId"           = module.rds_postgres.identifier
  }
```

I get `Must specify both Automation Target Parameter Name and Targets` but, if I do that, I get an association with a Rate Control execution, as mentioned above.

### Affected Resource(s) and/or Data Source(s)

aws_ssm_association

### Potential Terraform Configuration

```terraform
I would expect one of the following configurations to create an association with a Simple Execution:


resource "aws_ssm_association" "start_rds_mondays_7am" {
  name             = "AWS-StartRdsInstance"
  association_name = "${local.name_prefix}-start-rds-mondays-7am"

  automation_target_parameter_name = "InstanceId"

  parameters = {
    "AutomationAssumeRole" = aws_iam_role.ssm_role.arn
    "InstanceId"           = module.rds_postgres.identifier
  }

  schedule_expression = "cron(0 00 7 ? * MON *)"

  apply_only_at_cron_interval = true
}
```

or

```terraform
resource "aws_ssm_association" "start_rds_mondays_7am" {
  name             = "AWS-StartRdsInstance"
  association_name = "${local.name_prefix}-start-rds-mondays-7am"

  schedule_expression = "cron(0 00 7 ? * MON *)"

  apply_only_at_cron_interval = true

  targets {
    key    = "InstanceId" # note this is not 'InstanceIds'
    values = [module.rds_postgres.identifier]
  }
}
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @fracampit 👋 Thank you for taking the time to raise this! I did a bit of looking around to try and find and answer for this one, and based on what I found, I think your second option under "Potential Terraform Configurations" is close. Looking at the [API documentation](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateAssociation.html#API_CreateAssociation_RequestSyntax), it seems that setting `automation_target_parameter_name` is what's causing the association to use rate control:

> ... This target is required for associations that use an Automation runbook and target resources by using rate controls. ...

Looking at the reference for `targets`, both in the aforementioned API documentation and the [resource documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_association.html#attribute-reference) (note: there wasn't an anchor link for `targets`, but it's just above "Attribute Reference"), there's a `key` value of `InstanceIds` that can be used to target specific instance(s). In your example, you instead used `InstanceId` for the `key` -- can you try using `InstanceIds` instead, and let me know if that achieves the desired effect?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
