### ISSUE TITLE
Module EKS how can i disable auto create security group

### ISSUE THREAD

**Issue by medusaalb** [hashicorp/terraform-provider-aws#32498]
### Description

I would like to know if it's possible to avoid module eks autocreates nodes security group
Is there a way to assign my own security group to worker nodes?

Thanks in advance

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @medusaalb 👋 Thank you for taking the time to raise this! For questions related to a particular module, you'll want to raise an issue in the repository for the module. If you can give me an idea of what module you're referring to, I'd be happy to help you track down the appropriate repository.

**Comment by danno5230** [comment]
In the [documentation for the module](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest?tab=inputs) there is an input variable "create_node_security_group". Setting that to false should disable node security group creation. To specify your own you can use "node_security_group_id".

**Comment by medusaalb** [comment]
Everything ok
Thanks a lot!
