### ISSUE TITLE
[Enhancement]: Documentation https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_analytics_application#outputs

### ISSUE THREAD

**Issue by pronoyroy** [hashicorp/terraform-provider-aws#32491]
### Description

The documentation is a stub at best and is grossly insufficient. This needs more examples and descriptions of sub-blocks. 

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_analytics_application#outputs

### Affected Resource(s) and/or Data Source(s)

aws_kinesis_analytics_application

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_analytics_application#outputs

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
