### ISSUE TITLE
[aws_security_group] How to manage inline ingress rules via parameters?

### ISSUE THREAD

**Issue by Nuru** [hashicorp/terraform-provider-aws#32521]
### Description

#32424 closed a lot of issues related to inline `aws_security_group` ingress and egress rules, but I do not see how it is a solution. I think they should be reopened or closed on other grounds with a different explanation. The documentation says

> To subsequently remove all managed ingress and egress rules:

```terraform
resource "aws_security_group" "example" {
  name   = "sg"
  vpc_id = aws_vpc.example.id
  ingress = []
  egress  = []
}
```

Does this mean that if I have `var.ingress_rules = list(object(<rules>))` I can write

```terraform
resource "aws_security_group" "example" {
  name   = "sg"
  vpc_id = aws_vpc.example.id
  ingress = var.ingress_rules
}
```

The documentation indicates that this will not work, and instead I have to do something like

```terraform
resource "aws_security_group" "example" {
  name   = "sg"
  vpc_id = aws_vpc.example.id
  dynamic "ingress" {
    for_each = var.ingress_rules
    content {
      description      = ingress.value.description
      ...
    }
  }
}
```

How can I write one block of code that will delete inline ingress rules when they are removed? It looks to me that I still cannot, in which case I think a lot of these issues are still not resolved.

It is fine with me if you say the issues will not be resolved per se and declare inline rules deprecated or insist that people use [aws_vpc_security_group_ingress_rule](https://registry.terraform.io/providers/hashicorp/aws/5.8.0/docs/resources/vpc_security_group_ingress_rule) resources if they are going to change during the life of the security group, but that is a different resolution than #32424 provides.

### References

PR #32424 

Issues it claims to close:

- #660
- #1555
- #4399
- #11059
- #20046

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @Nuru 👋 Thank you for taking the time to raise this! While we strongly recommend using the distinct `aws_vpc_security_group_ingress_rule` and `aws_vpc_security_group_egress_rule` resources for any newly created security groups, the attributes-as-blocks documentation covers this use-case under the header [Arbitrary Expressions with Argument Syntax](https://developer.hashicorp.com/terraform/language/attr-as-blocks#arbitrary-expressions-with-argument-syntax). Can you take a look at that document and let me know if it helps in your scenario?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
