### ISSUE TITLE
[Docs]: WAF logging no longer requires Kinesis Firehose

### ISSUE THREAD

**Issue by milh0use** [hashicorp/terraform-provider-aws#32544]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl_logging_configuration

### Description

As explained in this [AWS Blog Post](https://aws.amazon.com/blogs/mt/analyzing-aws-waf-logs-in-amazon-cloudwatch-logs/), the intermediate resource of Kinesis Firehose stream is no longer required to link WAF logging to a Cloudwatch Log Stream.

> Previously, WAF logs had to be sent via Amazon [Kinesis Data Firehose](https://aws.amazon.com/kinesis/data-firehose/) to [AWS OpenSearch](https://aws.amazon.com/opensearch-service/), third-party solutions for dashboards, or to [Amazon Simple Storage Service (Amazon S3)](https://aws.amazon.com/s3/) paired with [Amazon Athena](https://aws.amazon.com/athena/) for log analysis. Customers would have a high volume of incoming logs, where analyzing logs would become difficult as these configurations required the integration of multiple services for log analysis and dashboards. This was also expensive and customers needed separate teams to keep the solution up to date. To simplify this, logs can now be sent directly to CloudWatch for log analysis, dashboard creation, and viewing alarms in a single pane using CloudWatch features, such as metric filters, Logs Insights, Anomaly detection, and Contributor Insights.

I've successfully linked together resources as follows:
```terraform
resource "aws_cloudwatch_log_group" "waf_logs" {
    provider = // a provider alias in region us-east-1
    name              = "aws-waf-logs-application"
    retention_in_days = 14
}

resource "aws_wafv2_web_acl_logging_configuration" "application" {
  provider = // a provider alias in region us-east-1
  log_destination_configs = [aws_cloudwatch_log_group.waf_logs.arn]
  resource_arn            = aws_wafv2_web_acl.application.arn
}
```

### References

https://aws.amazon.com/blogs/mt/analyzing-aws-waf-logs-in-amazon-cloudwatch-logs/

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @milh0use 👋 Thank you for taking the time to raise this! I've opened a pull request to update the documentation, removing the note on the Kinesis requirement.
