### ISSUE TITLE
[Bug]: AWS Timestreamwrite Table resource does not accept multiple composite partition keys

### ISSUE THREAD

**Issue by saratnulu** [hashicorp/terraform-provider-aws#32560]
### Terraform Core Version

1.0

### AWS Provider Version

5.8.0

### Affected Resource(s)

As per the AWS API reference, we can define a list of composite_partition_keys for a Timestream table
https://docs.aws.amazon.com/ko_kr/timestream/latest/developerguide/API_Schema.html#timestream-Type-Schema-CompositePartitionKey

* aws_timestreamwrite_table resource added as part of PR https://github.com/hashicorp/terraform-provider-aws/pull/32354 restricts defining only one partition key. This is restricting creating tables with multiple composite partition keys.

### Expected Behavior

 As per AWS API reference composite partition keys is a list of maps. So, should accept the code as in below format

```
resource "aws_timestreamwrite_table" "example" {
  database_name = aws_timestreamwrite_database.example.database_name
  table_name    = "example"

  schema {
    composite_partition_key = [
    {
      enforcement_in_record = "REQUIRED"
      name                  = "attr1"
      type                  = "DIMENSION"
    },
    {
      enforcement_in_record = "REQUIRED"
      name                  = "attr2"
      type                  = "DIMENSION"
    }
    ]
  }
}

```

### Actual Behavior

Above syntax is not allowed and also when we try to create composite_partition_keys as multiple blocks inside a schema block, i receive below error
```
No more than 1 "composite_partition_key" blocks are allowed
```

### Terraform Configuration Files

https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/timestreamwrite/table.go#L140

### Steps to Reproduce

No way to define multiple composite partition keys for different dimension attributes

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@saratnulu Thanks for raising this issue 👏.
Although the API schema does allow multiple partition keys in the composite partition key, currently if you try to configure more than 1 there is an error:

```
ValidationException: You have specified too many partition keys to be used in your composite partition key. Only 1 partition keys can be specified.
```

**Comment by saratnulu** [comment]
> @saratnulu Thanks for raising this issue 👏. Although the API schema does allow multiple partition keys in the composite partition key, currently if you try to configure more than 1 there is an error:
> 
> ```
> ValidationException: You have specified too many partition keys to be used in your composite partition key. Only 1 partition keys can be specified.
> ```

is this because of the rrerstrriction in `table_test.go` file or restriction by AWS ?
When i try to create table with multiple partition kets manually it works.

**Comment by ewbankkit** [comment]
@saratnulu That was at the API level (have removed the Terraform schema `MaxItems: 1`).
Can you paste in how you created with multiple partition keys? Thanks.

**Comment by saratnulu** [comment]
@ewbankkit , I did validation post your message again and looks like i created a table by providing list of partition keys in name field as comma seperated values in aws console. I noticied this doesn't work as the attribute name is taken as "attr1, attr2" instead of 2 keys. So, its my ignorance.

I agree with you that it's AWS API limitation where though schema supports, API doesn't support multiple partition keys.

You can close the bug now

**Comment by saratnulu** [comment]
Closing with above comment
