### ISSUE TITLE
[Enhancement]: aws_mq_broker allow creation of cross-region replicated brokers

### ISSUE THREAD

**Issue by pbushko** [hashicorp/terraform-provider-aws#32566]
### Description

[Cross-region replication](https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-mq-cross-region-data-replication-activemq/) for mq brokers was released Jun 23, 2023 but I haven't seen any feature requests for this yet.

The [AWS CLI reference for create-broker](https://docs.aws.amazon.com/cli/latest/reference/mq/create-broker.html) shows updates for mq replication; it would be great if this provider also supported it.  I would imagine the extra fields for this resource could mirror the extra data needed in the CLI call.

### Affected Resource(s) and/or Data Source(s)

aws_mq_broker

### Potential Terraform Configuration

```terraform
resource "aws_mq_broker" "replica_broker" {
  broker_name = "replica_broker"

  configuration {
    id       = aws_mq_configuration.test.id
    revision = aws_mq_configuration.test.latest_revision
  }

  engine_type        = "ActiveMQ"
  engine_version     = "5.15.9"
  host_instance_type = "mq.t2.micro"
  security_groups    = [aws_security_group.test.id]

  user {
    username = "replica_user"
    password = "password_for_replica_user"
    replication_user = true
  }
  ## NEW FIELDS
  data_replication_mode = "CRDR"
  data_replication_primary_broker_arn = aws_mq_broker.primary_broker.arn
}
```

### References

https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-mq-cross-region-data-replication-activemq/
https://docs.aws.amazon.com/cli/latest/reference/mq/create-broker.html
https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/create-replica-broker.html

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
> Amazon MQ now supports cross-region data replication for ActiveMQ brokers.

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-mq-cross-region-data-replication-activemq/)
* [Blog post](https://aws.amazon.com/blogs/compute/introducing-amazon-mq-cross-region-data-replication-for-activemq-brokers/)
