### ISSUE TITLE
[Bug]: r/aws_db_instance_automated_backups_replication: `unexpected state 'Pending'`

### ISSUE THREAD

**Issue by ixl-cchew** [hashicorp/terraform-provider-aws#32597]
### Terraform Core Version

1.5.3

### AWS Provider Version

5.8.0

### Affected Resource(s)

aws_db_instance_automated_backups_replication

### Expected Behavior

Creating the db_instance_automated_backups_replication resource should complete without any error

### Actual Behavior

After creating a primary instance from this [module](https://registry.terraform.io/modules/terraform-aws-modules/rds/aws/latest); when creating db_instance_automated_backups_replication resource, it errors out. 

### Relevant Error/Panic Output Snippet

```shell
Error: waiting for DB instance automated backup (arn:aws:rds:us-west-1:<accountnumber>:auto-backup:ab-<string>) create: unexpected state 'Pending', wanted target 'replicating'. last error: %!s(<nil>)
```

### Terraform Configuration Files

```terraform
provider "aws" {
    profile = "default"
    region = "us-west-2"
    assume_role {
        role_arn     = "<arn of assumed role>"
        session_name = "TerraformAdminSession"
    }

}

provider "aws" {
    profile = "default"
    region = "us-west-1"
    assume_role {
        role_arn     = "<arn of assumed role>"
        session_name = "TerraformAdminSession"
    }
    alias = "cross_replica"
}

module "master" {
    source  = "terraform-aws-modules/rds/aws"
    version = "6.1.0"

  identifier = "test-master"

  engine               = "postgres"
  engine_version       = "14.6"
  family               = "postgres14"
  instance_class       = "db.m5.xlarge"

  allocated_storage     = "2000"
  max_allocated_storage = 3000
  db_name  = "replicaPostgresql"
  username = "replica_postgresql"
  port     = "5432"

  multi_az               = false

  maintenance_window              = "Mon:00:00-Mon:03:00"
  backup_window                   = "03:00-06:00"
  enabled_cloudwatch_logs_exports = ["postgresql", "upgrade"]

  backup_retention_period = 1
  skip_final_snapshot     = true
  deletion_protection     = false

}

resource "aws_kms_key" "default" {
  description = "Encryption key for automated backups"

  provider = aws.cross_replica
}

resource "aws_db_instance_automated_backups_replication" "cross_region_replication" {
    depends_on = [ module.master ]
    source_db_instance_arn = module.master.db_instance_arn
    kms_key_id             = aws_kms_key.default.arn
    
    provider = aws.cross_replica
}
```

### Steps to Reproduce

1. Need to have your ~/.aws/credentials with the appropriate access key to assume a role to the account with the [default] profile
2. Run terraform init and apply

### Would you like to implement a fix?

None

**Comment by ixl-cchew** [comment]
Just want to note that it looks like the resource does get created and originally it will be in the Pending state and then switch over to the Replicating state. However, the error message is concerning to the person running the terraform.

**Comment by ixl-cchew** [comment]
It seems like there is an issue probably because the terraform did not complete because the next time I do a apply, it says the resource is tainted and must be replaced. When it goes destroys the resource and recreate it, I get an error stating 

```
│ Error: starting RDS instance automated backups replication: InvalidDBInstanceState: DB instance is already replicating backups to this region.
│       status code: 400, request id: 2670dc0e-e499-4cac-bd17-40c53c5daa06
```

but the replication has already been deleted.

**Comment by taylorbartley** [comment]
I'm having the exact same issue, with a slightly different setup. My DB already exists in us-east-1, and I'm adding backup replication to us-west-1. 

```
resource "aws_db_instance_automated_backups_replication" "dr_default" {
  source_db_instance_arn = var.source_db_instance_arn
  retention_period       = 1
  kms_key_id             = "arn:aws:kms:us-west-1:614309964512:key/abcd123456
}
```

When I apply, it shows only the replication to be created. 
``` 
  # module.replication.aws_db_instance_automated_backups_replication.dr_default will be created
  + resource "aws_db_instance_automated_backups_replication" "dr_default" {
```
But then I get the same error output, with a tainted status, and also the replication is eventually successful.

I can untaint the replication resource, and everything seems fine.

I've noticed a few other odd behaviors. As a sanity check, I setup cross region snapshot replication manually in console and then I was able to import successfully. After that, on apply there were no changes, so everything is fine. 
However, if I then change the retention, which would force a recreate, the apply fails with a message that the snapshots are not replicating.

**Comment by taylorbartley** [comment]
It appears that the cloudtrail response is definitely `"status": "Pending"` as just the base return. 

The example referenced in the CLI docs reference 'pending' even though the API defines the responses as `active, retained, and creating`.

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/rds/start-db-instance-automated-backups-replication.html
https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DBInstanceAutomatedBackup.html

**Comment by al-nwokedike-imprivata** [comment]
I am also experiencing a similar issue with the following error:
`Error: waiting for DB instance automated backup (arn:aws:rds:??:??:auto-backup:ab-??) create: unexpected state 'Pending', wanted target 'replicating'. last error: %!s(<nil>)`

**Comment by ixl-cchew** [comment]
Thank you two for sharing your experience! 

It looks like there needs to be a change over [here](https://github.com/hashicorp/terraform-provider-aws/blob/3e5d447cfbecab4e478ef971bb18d3ca4dc09f55/internal/service/rds/instance_automated_backups_replication.go#L98C34-L99)?

**Comment by al-nwokedike-imprivata** [comment]
I was able to resolve temporarily by removing the state and importing it back. Since the resource is already replicating, plan shows no changes afterwards

**Comment by ixl-cchew** [comment]
> I was able to resolve temporarily by removing the state and importing it back. Since the resource is already replicating, plan shows no changes afterwards

So you did a terraform state rm <module>.<resourcename> and then just apply it again?

**Comment by taylorbartley** [comment]
> > I was able to resolve temporarily by removing the state and importing it back. Since the resource is already replicating, plan shows no changes afterwards
> 
> So you did a terraform state rm [module].[resourcename] and then just apply it again?

I was having a similar result if I used untaint. You can have mixed results after that, if you try to apply another change too quickly, if the DB isn't actually finished modifying.

**Comment by al-nwokedike-imprivata** [comment]
> > I was able to resolve temporarily by removing the state and importing it back. Since the resource is already replicating, plan shows no changes afterwards
> 
> So you did a terraform state rm [module].[resourcename] and then just apply it again?

terraform state rm [module].[resourcename], then terraform import [module].[resourcename] [resource id]
You can get the id from the console since the resource has already been created

**Comment by vladelleus** [comment]
I am facing the same issue with cross-region automated backups. It failed but also enables the cross-region feature on the target automated backup and starts to creating replica snapshots in another region.

**Comment by vladelleus** [comment]
> This worked! Thank you! And also just for clarity sake, it seems like the [resource id] is simply the ARN of the backup.
I also think it would be better for this resource to contain information about the snapshots it created, not simply the id of the automated backups :(

**Comment by lilia-a-b** [comment]
I'm also facing the same error ,and looking forward to get a fix on this issue as soon as possible

**Comment by ewbankkit** [comment]
It looks like the AWS RDS API status codes change capitalization without any notification 😢.
We can reproduce this in our CI testing.

**Comment by ewbankkit** [comment]
I am working on a fix...

**Comment by sportymsk** [comment]
@ewbankkit - will this fix be propagated to 4.x versions?

**Comment by toadjaune** [comment]
> > > I was able to resolve temporarily by removing the state and importing it back. Since the resource is already replicating, plan shows no changes afterwards
> > 
> > 
> > So you did a terraform state rm [module].[resourcename] and then just apply it again?
> 
> terraform state rm [module].[resourcename], then terraform import [module].[resourcename] [resource id] You can get the id from the console since the resource has already been created

The following also works as a workaround : 
```bash
terraform untaint aws_db_instance_automated_backups_replication.your_resource_name
```

**Comment by lilia-a-b** [comment]
how can I get this update?
