### ISSUE TITLE
[Docs]: RDS identifier change or addition does not force new resource

### ISSUE THREAD

**Issue by pavlospt** [hashicorp/terraform-provider-aws#32590]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#identifier

### Description

Documentation says that `identifier` forces new resource, which is not true, or at least not anymore true. Terraform apply made and also marked the change as `in-place` and was also applied as `in-place`.

### Would you like to implement a fix?

Νο

**Comment by justinretzolk** [comment]
Hey @pavlospt 👋 Thank you for taking the time to raise this! I've opened a documentation pull request to have this addressed.

**Comment by pavlospt** [comment]
@justinretzolk Hello, thank you! Is there a PR link?
