### ISSUE TITLE
[Bug]: Cognito SMS message character limit

### ISSUE THREAD

**Issue by arapower** [hashicorp/terraform-provider-aws#32607]
### Terraform Core Version

1.4.6

### AWS Provider Version

4.63.0

### Affected Resource(s)

* aws_cognito_user_pool

### Expected Behavior

- https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-settings-SMS-message-customization.html

> The maximum length for the message, including the authentication code, is 140 UTF-8 characters.

According to the above page, it is expected that you can enter up to 140 characters.

### Actual Behavior

Actually you can only enter 140 bytes.

### Relevant Error/Panic Output Snippet

```shell
│ Error: "sms_authentication_message" cannot be longer than 140 characters
│ 
│   with module.cognito.aws_cognito_user_pool.user_pool,
│   on ../modules/cognito/user_pool.tf line 17, in resource "aws_cognito_user_pool" "user_pool":
│   17:   sms_authentication_message = <<-EOT
│   18: {####}
│   19: あいうえおかきくけこ
│   20: あいうえおかきくけこ
│   21: あいうえおかきくけこ
│   22: あいうえおかきくけこ
│   23: あいうえおかきくけこ
│   24: あいうえおかきくけこ
│   25: あいうえおかきくけこ
│   26: あいうえおかきくけこ
│   27: あいうえおかきくけこ
│   28: あいうえおかきくけこ
│   29: EOT
```

### Terraform Configuration Files

N/A

### Steps to Reproduce

Execute `terraform apply` using the following configuration file.
```user_pool.tf
resource "aws_cognito_user_pool" "user_pool" {
  name = "user-pool"

~~snip~~

  sms_authentication_message = <<-EOT
{####}
あいうえおかきくけこ
あいうえおかきくけこ
あいうえおかきくけこ
あいうえおかきくけこ
あいうえおかきくけこ
あいうえおかきくけこ
あいうえおかきくけこ
あいうえおかきくけこ
あいうえおかきくけこ
あいうえおかきくけこ
EOT
}
```

### References

- Customizing the SMS message - Amazon Cognito https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-settings-SMS-message-customization.html

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
As goodwill I've also open an AWS support case for the 413 error in my own account. Will report back if there are updates.
