### ISSUE TITLE
[Docs]: aws_cloudtrail advanced_event_selector - equals should be starts_with

### ISSUE THREAD

**Issue by bushju** [hashicorp/terraform-provider-aws#32619]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail

### Description

This is similar to https://github.com/hashicorp/terraform-provider-aws/issues/28582. 
It seems there is still one example left where `equals` needs to be replaced with `starts_with`.

```
field_selector {
      field = "resources.ARN"

      #The trailing slash is intentional; do not exclude it.
      equals = [
        "${data.aws_s3_bucket.important-bucket-1.arn}/",
        "${data.aws_s3_bucket.important-bucket-2.arn}/"
      ]
    }

    field_selector {
      field  = "readOnly"
      equals = ["false"]
    }

    field_selector {
      field  = "resources.type"
      equals = ["AWS::S3::Object"]
    }
  }
 ```

### References

https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_AdvancedFieldSelector.html

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @bushju 👋 Thank you for taking the time to raise this! I've opened a docs pull request in order to get this fixed up.
