### ISSUE TITLE
[Bug]: aws_s3_bucket resource incosistent with provider.aws.default_tags

### ISSUE THREAD

**Issue by floppy-engineer** [hashicorp/terraform-provider-aws#32618]
### Terraform Core Version

1.5.1

### AWS Provider Version

5.8.0

### Affected Resource(s)

Using together provider.aws.default_tags and resource aws_s3_bucket with additional tag give incorrect behavior.

### Expected Behavior

Combine tags: from default_tags + from the resource

### Actual Behavior

1. When there is no s3 bucket - terraform creates the bucket as expected with all tags
2. When the bucket is already exist and have all tags - terraform removes all tags
3. When the bucket exist and have no tags - terraform adds all expected tags.

So, continuous applying the same resource without any changes cause the cycle - 2. -> 3. -> 2. -> 3...

### Terraform Configuration Files

terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

provider "aws" {
  region = "us-east-1"
  default_tags {
    tags = { aaa = "aaa" }
  }
}

resource "aws_s3_bucket" "bucket" {
  bucket              = "bucket1"
  tags                = { bbb = "bbb" }
}

### Steps to Reproduce

Just applying the same source code over and over

### Important Factoids

We use terraform from docker container: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

### Would you like to implement a fix?

None

**Comment by maunzCache** [comment]
Duplicates #31941

**Comment by floppy-engineer** [comment]
Agree. The behavior is just because of empty tag. Thank you very much, @maunzCache!
And I close the issue as it's a duplicate. Sorry.
