### ISSUE TITLE
[Enhancement]: aws_opensearch_outbound_connection - add connection_mode configuration

### ISSUE THREAD

**Issue by atheri** [hashicorp/terraform-provider-aws#32630]
### Description

Opensearch outbound connections have the option of using a new VPC endpoint connection mode, but the resource has no way to select between Direct and VPC endpoint modes.

### Affected Resource(s) and/or Data Source(s)

aws_opensearch_outbound_connection

### Potential Terraform Configuration

```terraform
resource "aws_opensearch_outbound_connection" "foo" {
  connection_alias = "outbound_connection"
  connection_mode  = "VPC_ENDPOINT"         # choose between DIRECT & VPC_ENDPOINT
  local_domain_info {
    ...
  }
  remote_domain_info {
    ...
  }
}
```

### References

announcement: https://aws.amazon.com/about-aws/whats-new/2023/01/amazon-opensearch-service-remote-reindex-vpc-domains/
aws cli - 'connection-mode' parameter: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/opensearch/create-outbound-connection.html

### Would you like to implement a fix?

No

**Comment by DanielRieske** [comment]
I'll gladly pick this issue up, I will add the PR shortly.
