### ISSUE TITLE
[Enhancement]: RDS for MSSQL and self managed AD

### ISSUE THREAD

**Issue by dbbc96** [hashicorp/terraform-provider-aws#32641]
### Description

So AWS recently released the ability to use self managed AD for MSSQL.  Just wanted to make it aware that its available and to put that on your roadmap to add that to terraform. 

### Affected Resource(s) and/or Data Source(s)

aws_db_instance

### References

https://aws.amazon.com/about-aws/whats-new/2023/07/amazon-rds-sql-server-self-managed-active-directory/

### Would you like to implement a fix?

None

**Comment by marcosfreccia** [comment]
👍
