### ISSUE TITLE
[New resource]: Manage AWS OpenSearch custom packages and cluster associations

### ISSUE THREAD

**Issue by VidakovicTrendier** [hashicorp/terraform-provider-aws#32648]
### Description

Amazon OpenSearch Service lets you upload custom dictionary files, such as stop words and synonyms, for use with your cluster. [The workflow to use it is documented here for python](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/custom-packages.html#custom-packages-update-python) and can be summarized as follows:

- Upload custom packages to S3.
- Create custom package in Opensearch service linking it to the file uploaded to S3 in the previous step with [CreatePackage](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearch#Client.CreatePackage)
- Associate this package to an existing OpenSearch domain. This step implies a call to [AssociatePackage](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearch#Client.AssociatePackage) which is an asynchronous process. The association progress can be checked calling [ListPackagesForDomain](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearch#Client.ListPackagesForDomain).
- Packages dissociation can be performed calling [DissociatePackage](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearch#Client.DissociatePackage). Again this is an asynchronous process and can be checked calling [ListPackagesForDomain](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearch#Client.ListPackagesForDomain) and checking the missing entry for the Opensearch domain.

Right now the terraform AWS provider lacks this entire funcionality and it's needed to get a fully functional OpenSearch domain when custom packages are used. Unfortunately I have not experience with Go, so initially I don't see myself developing it. Anyway if I find the time I can try to develop it.

### Requested Resource(s) and/or Data Source(s)

resource aws_opensearch_package
data aws_opensearch_package
resource aws_opensearch_package_association
data aws_opensearch_package_association

### Potential Terraform Configuration

```terraform
resource "aws_s3_bucket" "my_opensearch_packages" {
  bucket = "my-opensearch-packages"
}

resource "aws_s3_bucket_object" "my_dictionary" {
  bucket = aws_s3_bucket.my_opensearch_packages.bucket
  key    = "my_dictionary"
  source = "./my_dictionary"

  etag = filemd5("./my_dictionary")
}

resource "aws_opensearch_package" "my_opensearch_package" {
  package = "my-packge-name"
  description = "This is my OpenSearch custom package"
  source {
    s3_bucket = aws_s3_bucket.my_opensearch_packages.bucket
    key = aws_s3_bucket_object.my_dictionary.key
  }
}

data "aws_opensearch_domain" "my_domain" {
  domain_name = "my-domain-name"
}

resource "aws_opensearch_package_association" "my_package_domain_association" {
  domain_name = data.aws_opensearch_domain.my_domain.domain_name
  package_id = aws_opensearch_package.my_opensearch_package.id
}
```

### References

- [Amazon OpenSearch custom packages documentation](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/custom-packages.html).
- [Sample python code creating package, associating it and dissociating it](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/custom-packages.html#custom-packages-update-python).
- [CreatePackage](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearch#Client.CreatePackage) Go documentation.
- [AssociatePackage](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearch#Client.AssociatePackage) Go documentation.
- [ListPackagesForDomain](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearch#Client.ListPackagesForDomain) Go documentation.
- [DissociatePackage](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearch#Client.DissociatePackage) Go documentation.

### Would you like to implement a fix?

No

**Comment by bschaatsbergen** [comment]
I'll happily support the resources (`aws_opensearch_package` and `aws_opensearch_package_association`)
Lets create a different ticket for the data sources.

**Comment by VidakovicTrendier** [comment]
Thank you very much @bschaatsbergen. Should I open the ticket for the data sources?

**Comment by bschaatsbergen** [comment]
That would be great yes @VidakovicTrendier

**Comment by bschaatsbergen** [comment]
FYI: I aim to finalize the PR for both `aws_opensearch_package` as well as `aws_openseach_package_association` today.
