### ISSUE TITLE
[Bug]: Order lost in `aws_quicksight_data_set` causing endless plan updates due to ordering of principals in `permissions` block

### ISSUE THREAD

**Issue by udidn** [hashicorp/terraform-provider-aws#32645]
### Terraform Core Version

1.5.3

### AWS Provider Version

5.8.0

### Affected Resource(s)

The `permissions` block in `aws_quicksight_data_set` resource

### Expected Behavior

When running multiple plans without changes to the Terraform configuration file, Terraform should detect no changes

### Actual Behavior

When running multiple plans without changes to the Terraform configuration file, changes are detected on every plan due to reordering of the principals

### Terraform Configuration Files

```terraform
locals {
  users = ["Admin/Isengard-udid", "Admin2/Isengard-udid"]
}

data "aws_quicksight_user" "qs_data_set_users" {
  count = length(local.users)

  user_name = local.users[count.index]
}

resource "aws_quicksight_data_set" "test_dataset" {
  data_set_id = "test
  import_mode = "SPICE"
  name        = "test"

  data_set_usage_configuration {
    disable_use_as_direct_query_source = false
    disable_use_as_imported_source     = false
  }

  dynamic "permissions" {
    for_each = data.aws_quicksight_user.qs_data_set_users
    content {
      actions = [
        "quicksight:CancelIngestion",
        "quicksight:CreateIngestion",
        "quicksight:DeleteDataSet",
        "quicksight:DescribeDataSet",
        "quicksight:DescribeDataSetPermissions",
        "quicksight:DescribeIngestion",
        "quicksight:ListIngestions",
        "quicksight:PassDataSet",
        "quicksight:UpdateDataSet",
        "quicksight:UpdateDataSetPermissions",
      ]
      principal = data.aws_quicksight_user.users[permissions.key].arn
    }
  }

  physical_table_map {
    physical_table_map_id = "test"

    relational_table {
      catalog         = "AwsDataCatalog"
      data_source_arn = aws_quicksight_data_source.test_datasource.arn
      name            = "test"
      schema          = "test"

      input_columns {
        name = "name"
        type = "STRING"
      }
    }
  }
}
``` 

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

Notice there's significance to the usernames.
The usernames I'm using in the `users` list are returned in reversed order in `terraform plan` (step 2 above), and this is what's causing the drift.

### References

#22274

### Would you like to implement a fix?

None

**Comment by jar-b** [comment]
`permissions` argument may need converted to `TypeSet`:

https://github.com/hashicorp/terraform-provider-aws/blob/22f8b22448fa6fc8f28e9049bf0647cce3da321d/internal/service/quicksight/data_set.go#L201-L205

**Comment by udidn** [comment]
Thank you for point this out @jar-b.
Is there anyone looking into it and committing the fix?
