### ISSUE TITLE
[Bug]: Typo in Quicksight Pie Chart flattenDataLabelOptions ( 'measure_visibility' -> 'measure_label_visibility' ) 

### ISSUE THREAD

**Issue by MichaelYoung0705** [hashicorp/terraform-provider-aws#32652]
### Terraform Core Version

1.5.3

### AWS Provider Version

5.9.0

### Affected Resource(s)

aws_quicksight_dashboard

### Expected Behavior

For a Pie Chart visual, be able to set the 'Show Metric' option

### Actual Behavior

Exception is thrown when after the resources are created, and state is being written.

### Relevant Error/Panic Output Snippet

```shell
Error: setting definition: Invalid address to set: []string{"definition", "0", "sheets", "0", "visuals", "0", "pie_chart_visual", "0", "chart_configuration", "0", "data_labels", "0", "measure_visibility"}
```

### Terraform Configuration Files

```terraform
resource "aws_quicksight_dashboard" "example" {
  dashboard_id        = "example"
  name                = "example"
  version_description = "1"
  source_entity {
    source_template {
      arn = "arn:aws:quicksight:us-east-1:1111111111111:template/test/version/1"
      data_set_references {
        data_set_arn         = "arn:aws:quicksight:us-east-1:1111111111111:dataset/test"
        data_set_placeholder = "incidentals_stats"
      }
    }
  }
}
```

### Steps to Reproduce

Create a simple analysis with one pie chart visual tied to a test DataSet with numbers.
Under the Data Labels settings, check the 'Show Metric' option.
Plan and Apply and the dashbooard will create, but throw the error while getting state ready to write.

### Debug Output

In the current 5.9.0, the bug is in visual.go on line 1479.  Compared to the sister method, expandDataLabelOptions() and the schema in dataLabelOptionsSchema(), "measure_visibility" should be "measure_label_visibility".

### Panic Output

Error: setting definition: Invalid address to set: []string{"definition", "0", "sheets", "0", "visuals", "0", "pie_chart_visual", "0", "chart_configuration", "0", "data_labels", "0", "measure_visibility"}

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @MichaelYoung0705 👋 Thank you for taking the time to raise this! I'm working on a pull request that will resolve this 👍
