### ISSUE TITLE
[Bug]: Unable to deploy SIP media application in us-west-2

### ISSUE THREAD

**Issue by prabusampath007** [hashicorp/terraform-provider-aws#32678]
### Terraform Core Version

1.1.7

### AWS Provider Version

5.8.0

### Affected Resource(s)

aws_chimesdkvoice_sip_media_application

### Expected Behavior

Able to deploy this resource in us-west-2

### Actual Behavior

Not able to deploy in us-west-2

<img width="1788" alt="image" src="https://github.com/hashicorp/terraform-provider-aws/assets/79634402/bafc26a1-7992-440b-b7da-4e56b6be5924">

### Terraform Configuration Files

```terraform
resource "aws_chimesdkvoice_sip_media_application" "example" {
  aws_region = "us-west-2"
  name       = "example-sip-media-application"
  endpoints {
    lambda_arn = aws_lambda_function.test.arn
  }
}
```

### Steps to Reproduce

Deploy terraform in us-west-2

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @prabusampath007 👋 Thank you for taking the time to raise this! So that we have the necessary information in order to look into this, can you supply debug logs (redacted as needed) as well?

**Comment by prabusampath007** [comment]
Hey @justinretzolk , Are you good to proceed with this or do you need any other info?

**Comment by justinretzolk** [comment]
Hey @prabusampath007 👋 Are you able to supply debug logging, or do you have organizational restrictions that would prevent you from doing so? Unfortunately, the screenshot provided doesn't provide quite enough to be able to definitively say what's happening.

Can you also confirm the steps to reproduce this? Is this a fresh deployment of the resource, or does this occur during a subsequent run? If it's a subsequent run, is anything changing in the configuration during this time?

**Comment by prabusampath007** [comment]
Hey @justinretzolk It happened on first deployment and the subsequent run as well.

We are creating SIP media application (aws_chimesdkvoice_sip_media_application) in the us-west-2 region. While doing so, we received the above attached error.

You can simply do terraform run and see this error.
