### ISSUE TITLE
[Bug]: aws_appautoscaling_target failed to create with - "ValidationException: Tag values cannot be empty or blank"

### ISSUE THREAD

**Issue by shira-lev** [hashicorp/terraform-provider-aws#32677]
### Terraform Core Version

1.4.6

### AWS Provider Version

4.66.1

### Affected Resource(s)

aws_appautosacling_target

### Expected Behavior

Resource should have been created with no errors

### Actual Behavior

When attempting to create the resource with an equal configuration to the one presented in the docs I'm receiving this error - 
**creating Application AutoScaling Target (table/XXX): ValidationException: Tag values cannot be empty or blank**

### Terraform Configuration Files

I am using this module to create an autoscaling target to my DynamoDB - [cloudposse/dynamodb-autoscaler/aws](https://github.com/cloudposse/terraform-aws-dynamodb-autoscaler)
The aws_autoscaling_target configuration is - 
```terraform
resource "aws_appautoscaling_target" "read_target" {
  count              = module.this.enabled ? 1 : 0
  max_capacity       = var.autoscale_max_read_capacity
  min_capacity       = var.autoscale_min_read_capacity
  resource_id        = "table/${var.dynamodb_table_name}"
  scalable_dimension = "dynamodb:table:ReadCapacityUnits"
  service_namespace  = "dynamodb"
}
```
The values to these parameters are -
dynamodb_table_name: XXX 
autoscaleMinReadCapacity: 30
autoscaleMaxReadCapacity: 60

### Steps to Reproduce

run `Terraform plan` successfully and failed with `Terraform apply`

### Important Factoids

I am running terraform with cdktf version `0.15.5`

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @shira-lev 👋 Thank you for taking the time to raise this! So that we have the necessary information in order to look into this, can you supply debug logs (redacted as needed) as well?

**Comment by shira-lev** [comment]
Hi, so we found what caused the problem, we were using default tags at provider level and one of the tags was an empty string by mistake, after we changed its value we were able to run the deploy.

**Comment by justinretzolk** [comment]
Thank you for following up on this one! With that information in mind, we'll close this one out.
