### ISSUE TITLE
[Docs]: Broken syntax of link

### ISSUE THREAD

**Issue by shusann01116** [hashicorp/terraform-provider-aws#32691]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_route_table

### Description

At the bottom of the page. I found a broken link of the document.

<img width="450" alt="image" src="https://github.com/hashicorp/terraform-provider-aws/assets/26602565/447553e4-4c1b-4669-b682-c9110be54bd1">

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @shusann01116 👋 Thank you very much for taking the time to raise this! I've opened a documentation pull request to fix that odd behavior.
