### ISSUE TITLE
[Bug]: EC2 Instance is always recreating on any change.

### ISSUE THREAD

**Issue by tauqueer01** [hashicorp/terraform-provider-aws#32712]
### Terraform Core Version

Terraform v1.5.0

### AWS Provider Version

registry.terraform.io/hashicorp/aws v5.9.0

### Affected Resource(s)

EC2 Instance
EBS Volumes

### Expected Behavior

1. EC2 should not be recreated when I modify ebs_block_deice or root_block_device size.
2. EC2 should not get recreated when tags are added or modified.

### Actual Behavior

EC2 is getting created through terraform with already existing AMI in aws. Now, if I modify the  ebs_block_deice or root_block_device size, terraform force replacing the disk and recreating the instance.

```terraform
resource "aws_instance" "instance_example" {

  ami = "ami-03d1afcb5efdb3a56"
   root_block_device {
        delete_on_termination = false
    #    device_name           = "/dev/sda1"
        encrypted             = true
        iops                  = 3000
        kms_key_id            = "arn:aws:kms:ap-southeast-2:626107101308:key/6a77893b-71d2-4ec9-a537-762be7a81a85"
        tags                  = {}
        throughput            = 125
    #    volume_id             = "vol-0584e73e55d74d5d7"
        volume_size           = 70
        volume_type           = "gp3"
    }
  ebs_block_device {
        delete_on_termination = false
        device_name           = "xvdb"
        encrypted             = false
        iops                  = 3000
        tags                  = {}
        throughput            = 125
    #    volume_id             = "vol-0880b681ce5174d41"
        volume_size           = 130  ==> changing size here
        volume_type           = "gp3"
    }


  instance_type = "t2.micro"

  key_name = "test-kp"
  lifecycle  {
    ignore_changes = ["security_groups", "network_interface"]
  }  
  subnet_id = "subnet-036c71f9cc956fcdb"
  tags = {
    Name = "Target"
    app = "local"
    type = "test"
  }
  vpc_security_group_ids = ["sg-02e7085aecb8ed903"]
}
```

![image](https://github.com/hashicorp/terraform-provider-aws/assets/36665386/97b565a0-77c7-45ed-96cf-68ffc3533dee)

![image](https://github.com/hashicorp/terraform-provider-aws/assets/36665386/dc92d984-6126-4597-a4ac-08a453857858)

### Terraform Configuration Files

```terraform
resource "aws_instance" "instance_example" {

  ami = "ami-03d1afcb5efdb3a56"
   root_block_device {
        delete_on_termination = false
    #    device_name           = "/dev/sda1"
        encrypted             = true
        iops                  = 3000
        kms_key_id            = "arn:aws:kms:ap-southeast-2:626107101308:key/6a77893b-71d2-4ec9-a537-762be7a81a85"
        tags                  = {}
        throughput            = 125
    #    volume_id             = "vol-0584e73e55d74d5d7"
        volume_size           = 70
        volume_type           = "gp3"
    }
  ebs_block_device {
        delete_on_termination = false
        device_name           = "xvdb"
        encrypted             = false
        iops                  = 3000
        tags                  = {}
        throughput            = 125
    #    volume_id             = "vol-0880b681ce5174d41"
        volume_size           = 130  ==> changing size here
        volume_type           = "gp3"
    }


  instance_type = "t2.micro"

  key_name = "test-kp"
  lifecycle  {
    ignore_changes = ["security_groups", "network_interface"]
  }  
  subnet_id = "subnet-036c71f9cc956fcdb"
  tags = {
    Name = "Target"
    app = "local"
    type = "test"
  }
  vpc_security_group_ids = ["sg-02e7085aecb8ed903"]
}
```

### Steps to Reproduce

terraform init
terraform plan
terraform apply

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @tauqueer01 👋 Thank you for taking the time to raise this! When modifying `ebs_block_device`s, I would expect that the instance is recreated, as the [schema](https://github.com/hashicorp/terraform-provider-aws/blob/e518a463d4e138546a62952e7bedaa0c0984ddb0/internal/service/ec2/ec2_instance.go#L278-L283) indicates that this argument requires `ForceNew`. This is called out in [the documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#ebs_block_device) with the following note:

> Block device configurations only apply on resource creation.

With the `root_block_device`, however, I would expect that you're able to modify the volume size without triggering recreation ([schema reference](https://github.com/hashicorp/terraform-provider-aws/blob/e518a463d4e138546a62952e7bedaa0c0984ddb0/internal/service/ec2/ec2_instance.go#L725-L729) and [documentation reference](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#ebs-ephemeral-and-root-block-devices)):

> Modifying the `encrypted` or `kms_key_id` settings of the `root_block_device` requires resource replacement.

I also would not expect changes to `tags` to trigger the resource to be replaced. Can you supply debug logging for scenarios where changes to `root_block_device.volume_size` or `tags` triggered the instance to be recreated?
