### ISSUE TITLE
[Enhancement]: DocumentDB - Major Version Upgrade

### ISSUE THREAD

**Issue by ragclrao** [hashicorp/terraform-provider-aws#32721]
### Description

Add support for Amazon DocumentDB Major Version Upgrade.

### Affected Resource(s) and/or Data Source(s)

allow_major_version_upgrade

### Potential Terraform Configuration

```terraform
allow_major_version_upgrade = true.
```

### Would you like to implement a fix?

None

**Comment by kunagarw** [comment]
This feature is now GA. Can we please help prioritize this? 
https://docs.aws.amazon.com/documentdb/latest/developerguide/docdb-mvu.html
