### ISSUE TITLE
[Bug]: aws_ssm_parameter overwrite deprecation process leads users to get ParameterAlreadyExists error for aws_ssm_parameters created with `overwrite=true`

### ISSUE THREAD

**Issue by ei-grad** [hashicorp/terraform-provider-aws#32736]
### Terraform Core Version

1.5.3

### AWS Provider Version

5.9.0

### Affected Resource(s)

aws_ssm_parameter

### Expected Behavior

During the deprecation of the `overwrite` field in `aws_ssm_parameter` resource, user can continue to operate on existing infrastructure.

i.e. if the resource was managed by terraform, terraform should be able to continue to manage it

### Actual Behavior

User is forced to recreate `aws_ssm_parameter` resources or edit the terraform state manually.

### Relevant Error/Panic Output Snippet

```shell
│ Error: updating SSM Parameter (test): ParameterAlreadyExists: The parameter already exists. To overwrite this value, set the overwrite option in the request to true.
```

### Terraform Configuration Files

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "<5"
    }
  }
}

resource "aws_ssm_parameter" "test" {
  name  = "test"                                                                      
  type  = "String"                                                                    
  overwrite = true
  value = "test value"
}
```

### Steps to Reproduce

1. Run `terraform init && terraform apply` to create the `aws_ssm_parameter.test` with `terraform-provider-aws<5`
2. Update terraform-provider-aws to the latest version (`5.10.0` currently), run `terraform init -upgrade`
3. Run `terraform apply` to see that there is "No changes" and get the deprecation notice on the `overwrite` parameter
4. Remove `overwrite` parameter and run `terraform apply` again
5. Change the `value` parameter of `aws_ssm_parameter.test`
6. Run `terraform apply`, which now results in error

### Important Factoids

`overwrite` parameter docs says:

> If not specified, will default to false if the resource has not been created by terraform to avoid overwrite of existing resource and will default to true otherwise (terraform lifecycle rules should then be used to manage the update behavior).

But as shown via "Steps to Reproduce", this logic doesn't work for resources created with `overwrite`.

### Would you like to implement a fix?

None

**Comment by ei-grad** [comment]
From the referenced issue:

> Lastly, and unfortunately, configurations expecting the standard update flow will need to keep overwrite = true set until this becomes the default behavior in v6.0.0. Removing it in v5.X will result in the default value of false, preventing the parameter value from being updated, causing persistent differences.

Probably this should be added to the docs.

**Comment by justinretzolk** [comment]
Hey @ei-grad 👋 Thank you for taking the time to raise this! Regarding your most recent comment, that's correct. Until version 6.0.0 is released, you'll need to keep `overwrite = true` to maintain consistent behavior. Unfortunately, this means that there will be deprecation warnings in the runs until that point. Once version 6.0.0 is released and the `overwrite` argument is removed, it can be removed from the configuration with no change in functionality.

I'll start working on a documentation edit to try and make this more clear; I think that's absolutely warranted in this case.
