### ISSUE TITLE
[Enhancement]: Transfer Connector SFTP Support

### ISSUE THREAD

**Issue by gbeaven90** [hashicorp/terraform-provider-aws#32741]
### Description

Would like to extend the [aws_transfer_connector](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_connector) resource to support [SFTP Connectors](https://docs.aws.amazon.com/transfer/latest/userguide/transfer-sftp-connectors.html) in addition to the currently supported AS2 type.

### Affected Resource(s) and/or Data Source(s)

[aws_transfer_connector](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_connector)

### Potential Terraform Configuration

```terraform
resource "aws_transfer_connector" "example" {
  access_role = aws_iam_role.test.arn
  sftp_config {
    user_secret_arn = aws_secretsmanager_secret.example.arn
    trusted_host_keys = ["SHA256:d/beT64..."]
  }
  url = "sftp://sftp.some_url.com"
}
```

### Would you like to implement a fix?

No

**Comment by meetreks** [comment]
I am looking at this change, watch this space.

**Comment by CloudOpsPod** [comment]
when this feature will be available to support sftp config rather As2 ?

**Comment by meetreks** [comment]
> when this feature will be available to support sftp config rather As2 ?

Testing in progress, hopefully soon.
