### ISSUE TITLE
[Enhancement]: Support VECTORSEARCH type for aws_opensearchserverless_collection

### ISSUE THREAD

**Issue by mbahri** [hashicorp/terraform-provider-aws#32754]
### Description

AWS recently added vector search as a preview feature for OpenSearch Serverless, with support in the latest Go SDK versions https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearchserverless

Would it be possible to add support for the `VECTORSEARCH` collection type?

### Affected Resource(s) and/or Data Source(s)

* aws_opensearchserverless_collection

### Potential Terraform Configuration

```terraform
resource "aws_opensearchserverless_collection" "collection" {
  name = var.collection_name
  type = "VECTORSEARCH"

  depends_on = [aws_opensearchserverless_security_policy.encryption_policy]
}
```

### References

* https://github.com/aws/aws-sdk-go-v2/blob/service/opensearchserverless/v1.3.1/service/opensearchserverless/types/enums.go#L67C18-L67C18
* https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearchserverless

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/32749.
