### ISSUE TITLE
[Bug]: Lambda Python runtime 3.11

### ISSUE THREAD

**Issue by lizdeika** [hashicorp/terraform-provider-aws#32764]
### Terraform Core Version

1.5.4

### AWS Provider Version

5.10

### Affected Resource(s)

lambda `compatible_runtimes` does not support python 3.11

Announcement:
https://aws.amazon.com/about-aws/whats-new/2023/07/aws-lambda-python-3-11

It can be selected in AWS Console
![311](https://i.ibb.co/d7swPJx/311.jpg)

### Expected Behavior

to support python 3.11

### Actual Behavior

Error: expected compatible_runtimes.0 to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x nodejs16.x java8 java8.al2 java11 python2.7 python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 dotnet6 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2 nodejs18.x python3.10 java17 ruby3.2], got python3.11

### Terraform Configuration Files

-

### Steps to Reproduce

Try to set lambda compatible_runtimes to python3.11

### Would you like to implement a fix?

None

**Comment by Oberon00** [comment]
Would it be possible to (optionally?) not "validate" the runtime at all and just pass the runtime string through as-is to AWS? This would make it possible to use/test new Lambda runtimes as soon as they are available without waiting for a terraform upgrade.

**Comment by g4-otayyan** [comment]
It's already fixed guys just needs to be released (which may be a couple of days I imagine)

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/32726.
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/32729.
