### ISSUE TITLE
[Bug]: Route53 Association retriggering randomly

### ISSUE THREAD

**Issue by ZahwaarHussain** [hashicorp/terraform-provider-aws#32767]
### Terraform Core Version

1.3.4

### AWS Provider Version

4.64.0

### Affected Resource(s)

* aws_route53_zone_association

### Expected Behavior

Route53 zone should associate the zone once to a VPC and then never have to do this again unless the association is removed

### Actual Behavior

Route53 zone in account x is associating itself to a VPC in account y after a plan and apply.
After a further terraform plan is ran, the same zone is trying to associate itself with the same VPC and failing as it has previously associated itself.

### Terraform Configuration Files

N/A

### Steps to Reproduce

N\A

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @ZahwaarHussain 👋 Thank you for taking the time to raise this! So that we have the appropriate information in order to look into this, can you supply a Terraform configuration that can be used to reproduce this behavior, as well as debug logs (redacted as needed)?

**Comment by ZahwaarHussain** [comment]
Closing this issue, it was found to be an AWS rollout on saturday morning which caused this issue. For context:
- The `list-hosted-zones` command return 100 results and then paginates using a 'next token'.
- AWS deployed some backend code which resulted in the `list-hosted-zones` returning a random amount of results in a random order and then never paginating. After a day this value became consistent with displaying 37 results only.
- In turn Terraform during associating a Private hosted zone, uses the `list-hosted-zones` in the backend to understand whether it needs to make any changes.
- As the result was always inconsistent and not a full entry terraform would randomly try to associate a VPC with the PHZ even if this was associated already

Fix:
- AWS have now rolled back their code change from saturday and this issue no longer persists.
Thanks
