### ISSUE TITLE
[Bug]: RDS db_engine = "mysql" have issue with locals resource [The given key does not identify an element in this collection value]

### ISSUE THREAD

**Issue by abusutil** [hashicorp/terraform-provider-aws#32766]
### Terraform Core Version

1.5.4

### AWS Provider Version

5.9.0

### Affected Resource(s)

- aws_db_instance
- aws_security_group

### Expected Behavior

Adapt the security_group need to be deployed by using database port  set in `locals` resource by getting `db_engine` value.

locals.tf:
```terraform
locals {
  default_ports = {
    mysql = 3307
    postgres = 5432
  }
}
```

main.tf
```terraform
resource "aws_security_group" "rds_db_sg" {
  name_prefix = "sg_${var.project_name}-"
  description = "Security Group used by the DB"
  vpc_id      = data.aws_vpc.selected.id

  ingress {
    description = "Allow connection inside VPC"
    from_port   = local.default_ports[var.db_engine]
    to_port     = local.default_ports[var.db_engine]
    protocol    = "tcp"
    cidr_blocks = [data.aws_vpc.selected.cidr_block]
  }
}
```

```terraform
module "db1-db" {
  source = "git@github.com:...module_rds.git"

  #Database resource variables
  db_name                       = "db1"
  db_engine                     = "mysql"                
  db_engine_version             = "8.0"              
}
```

When I running `terraform plan ...` I have the correct output but with an error message 

```shell
# module.devops64-db.aws_db_instance.main_db will be created
  + resource "aws_db_instance" "main_db" {
      + ...
      + engine                                = "mysql"
      + engine_version                        = "8.0"
      + ...
      + tags_all                              = {
          ...
        }
      + ...
    }

Plan: x to add, x to change, x to destroy.
```

### Actual Behavior

locals.tf:
```terraform
locals {
  default_ports = {
    mysql = 3307
    postgres = 5432
  }
}
```

main.tf
```terraform
resource "aws_security_group" "rds_db_sg" {
  name_prefix = "sg_${var.project_name}-"
  description = "Security Group used by the DB"
  vpc_id      = data.aws_vpc.selected.id

  ingress {
    description = "Allow connection inside VPC"
    from_port   = local.default_ports[var.db_engine]
    to_port     = local.default_ports[var.db_engine]
    protocol    = "tcp"
    cidr_blocks = [data.aws_vpc.selected.cidr_block]
  }
}
```

***resource:***
```terraform
module "db1-db" {
  source = "git@github.com:...module_rds.git"

  #Database resource variables
  db_name                       = "db1"
  db_engine                     = "mysql"                
  db_engine_version             = "8.0"              
}
```

When I running `terraform plan ...` I have the correct output but with an error message
```shell
# module.devops64-db.aws_db_instance.main_db will be created

  + resource "aws_db_instance" "main_db" {
      + ...
      + engine                                = "mysql"
      + engine_version                        = "8.0"
      + ...
      + tags_all                              = {
          ...
        }
      + ...
    }

│ Error: Invalid index
│ 
│   on .terraform/modules/db1-db/main.tf line 25, in resource "aws_security_group" "rds_db_sg":
│   25:     from_port   = local.default_ports[var.db_engine]
│     ├────────────────
│     │ local.default_ports is object with 2 attributes
│     │ var.db_engine is "mysql"
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on .terraform/modules/db1-db/main.tf line 26, in resource "aws_security_group" "rds_db_sg":
│   26:     to_port     = local.default_ports[var.db_engine]
│     ├────────────────
│     │ local.default_ports is object with 2 attributes
│     │ var.db_engine is "mysql"
│ 
│ The given key does not identify an element in this collection value.
```

And the plan cannot be applied.

But, if I replace `mysql` by `sql` in : 
- locals.tf
- module.devops64-db : `db_engine = "sql"` I don't have the error anything at the plan, but the db_instance cannot be created because `sql` is not a compatiable `db_engine`

### Relevant Error/Panic Output Snippet

```shell
│ Error: Invalid index
│ 
│   on .terraform/modules/db1-db/main.tf line 25, in resource "aws_security_group" "rds_db_sg":
│   25:     from_port   = local.default_ports[var.db_engine]
│     ├────────────────
│     │ local.default_ports is object with 2 attributes
│     │ var.db_engine is "mysql"
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on .terraform/modules/db1-db/main.tf line 26, in resource "aws_security_group" "rds_db_sg":
│   26:     to_port     = local.default_ports[var.db_engine]
│     ├────────────────
│     │ local.default_ports is object with 2 attributes
│     │ var.db_engine is "mysql"
│ 
│ The given key does not identify an element in this collection value.
```

### Terraform Configuration Files

keybase://public/eonelia/Archive.zip

### Steps to Reproduce

Just run this command `terraform plan --var-file ./envs/global.tfvars --var environment=test --var commit_id=local --var repository_url=local --var project_name=test_rds -out tfplan`

### Debug Output

[Terraform DEBUG output is in the archive](keybase://public/eonelia/Archive.zip).

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @abusutil 👋 Thank you for taking the time to raise this! I may be incorrect here, but I don't believe we're able to access the link you provided for the Terraform configuration. Are you able to provide a publicly accessible link and debug logging (redacted as needed) so that we can take a look into this?

**Comment by abusutil** [comment]
Hi @justinretzolk thanks for your reply and sorry for my mistakes.

I added my files to "Public" and I added into the archives, all Terraform output.

**Comment by justinretzolk** [comment]
Hey @abusutil 👋 Thank you for taking the time to do that! I was able to retrieve the configuration from Keybase, took a look, and I'm fairly confident I know what's happening now.

Looking at the logs you provided above, one thing stuck out to me immediately: the resource that's not throwing an error appeared to be in a different module.

Working:

```console
# module.devops64-db.aws_db_instance.main_db will be created

  + resource "aws_db_instance" "main_db" {
      + ...
      + engine                                = "mysql"
```

Not working:

```console
│ Error: Invalid index
│ 
│   on .terraform/modules/majelan-db/main.tf line 25, in resource "aws_security_group" "rds_db_sg":
```

When I looked at the source configuration, I noted that these two different module calls in the configuration (`devops64-db` and `majelan-db`) have different sources; `devops64-db` is a local source, while `majelan-db` is being sourced from a GitHub repository **at a specific tag** (in this case, `v1.0.4`).

Since the `.git` directory was included, I switched into the `terraform-module-rds` directory, verified that it's origin was the repository being used for the `majelan-db` module call, and then checked out the `v1.0.4` tag. Upon doing so, I inspected `local.tf` and found:

```terraform
locals {
  default_ports = {
    sql = 3307
    postgres = 5432
  }
}
```

So it looks like this is a case of needing to update the `majelan-db` module call to point at a git reference that has an updated `local.tf` file that has `mysql` as one of the keys in the `default_ports` local.

**Comment by abusutil** [comment]
Hi Justin,

Yes, I understand. The tag is wrong. Only working for postgres database (used by my colleague). Any new tests was made for Mysql with this tag last week.

The database that have the issue is `devops64-db`, use the local module. And the error appear only on it (because this DB doesn't exist on our AWS and want to create it).

I find a temporary workaround to work fix this issue but not very clean.
`db_engine = var.db_engine == "sql" ? "mysql", var.db_engine`

**Comment by justinretzolk** [comment]
Hey @abusutil 👋 I'm not sure I follow this:

> The database that have the issue is `devops64-db`, use the local module. And the error appear only on it (because this DB doesn't exist on our AWS and want to create it).

Unless I've missed something, the error message that you've posted is related to the `majelan-db` module:

```shell
│ Error: Invalid index
│ 
│   on .terraform/modules/majelan-db/main.tf line 25, in resource "aws_security_group" "rds_db_sg":
│   25:     from_port   = local.default_ports[var.db_engine]
│     ├────────────────
│     │ local.default_ports is object with 2 attributes
│     │ var.db_engine is "mysql"
│ 
│ The given key does not identify an element in this collection value.
```

I'm looking at this line in particular to make that assessment:

```shell
│   on .terraform/modules/majelan-db/main.tf line 25, in resource "aws_security_group" "rds_db_sg":
```

On the other hand, the `devops64-db` module looks to be working as you'd expect:

```shell
# module.devops64-db.aws_db_instance.main_db will be created

  + resource "aws_db_instance" "main_db" {
      + ...
      + engine                                = "mysql"
```

For that assessment, I'm looking at this line:

```shell
# module.devops64-db.aws_db_instance.main_db will be created
```

**Comment by abusutil** [comment]
By improve our code, this error is fixed.

Thanks for your time about that :)
