### ISSUE TITLE
[Enhancement]: Add Python3.11 Support for Lambda Layer Compatible Runtimes

### ISSUE THREAD

**Issue by gbeaven90** [hashicorp/terraform-provider-aws#32777]
### Description

The documentation for the [aws_lambda_layer_version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_layer_version) resource on the `compatible_runtimes` argument states:

> [compatible_runtimes](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_layer_version#compatible_runtimes) - (Optional) List of [Runtimes](https://docs.aws.amazon.com/lambda/latest/dg/API_PublishLayerVersion.html#SSS-PublishLayerVersion-request-CompatibleRuntimes) this layer is compatible with. Up to 5 runtimes can be specified.

The AWS list of Runtimes shows Python3.11 as a supported type, however, referring to that runtime in the Terraform resource results in a Terraform error:

> Error: expected compatible_runtimes.1 to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x nodejs16.x java8 java8.al2 java11 python2.7 python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 dotnet6 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2 nodejs18.x python3.10 java17 ruby3.2], got python3.11

### Affected Resource(s) and/or Data Source(s)

[aws_lambda_layer_version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_layer_version)

### Potential Terraform Configuration

```terraform
resource "aws_lambda_layer_version" "lambda_layer" {
  filename   = "lambda_layer_payload.zip"
  layer_name = "lambda_layer_name"

  compatible_runtimes = ["python3.11"]
}
```

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/32726.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/32764.
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/32729.
