### ISSUE TITLE
[Bug]: typo in Quicksight InsightConfiguration Flattener ('computations" -> "computation")

### ISSUE THREAD

**Issue by MichaelYoung0705** [hashicorp/terraform-provider-aws#32788]
### Terraform Core Version

1.5.3

### AWS Provider Version

5.10.0

### Affected Resource(s)

aws_quicksight_dashboard

### Expected Behavior

State written to storage

### Actual Behavior

Error when writing state to storage

### Relevant Error/Panic Output Snippet

```shell
Error: setting definition: Invalid address to set: []string{"definition", "0", "sheets", "6", "visuals", "0", "insight_visual", "0", "insight_configuration", "0", "computations"}
```

### Terraform Configuration Files

resource "aws_quicksight_dashboard" "example" {
  dashboard_id        = "example"
  name                = "example"
  version_description = "1"
  source_entity {
    source_template {
      arn = "arn:aws:quicksight:us-east-1:1111111111111:template/test/version/1"
      data_set_references {
        data_set_arn         = "arn:aws:quicksight:us-east-1:1111111111111:dataset/test"
        data_set_placeholder = "example_placeholder"
      }
    }
  }
}

### Steps to Reproduce

Plan and Apply a dashboard resource with visual with the insight visual configuration object.

### Debug Output

In the current 5.10.0, the bug is in visual_insight.go on line 749, method flattenInsightConfiguration(). Compared to the sister method, expandInsightConfiguration() and the schema in insightVisualSchema(), "computations" should be "computation".

### Panic Output

Error: setting definition: Invalid address to set: []string{"definition", "0", "sheets", "6", "visuals", "0", "insight_visual", "0", "insight_configuration", "0", "computations"}

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @MichaelYoung0705 👋 Thank you very much for taking the time to report this! I've opened a pull request aimed at correcting this.
