### ISSUE TITLE
[Bug]: Wrong argument mapping

### ISSUE THREAD

**Issue by vstepanyuk** [hashicorp/terraform-provider-aws#32785]
### Terraform Core Version

1.0.0

### AWS Provider Version

5.10.0

### Affected Resource(s)

* aws_ecs

### Expected Behavior

Expected mapping memory_reservation to MemoryReservation options instead of overriding Memory option.
https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ecs/task_execution_data_source.go#L436

### Actual Behavior

memory_reservation mapped to Memory

### Terraform Configuration Files

–

### Steps to Reproduce

```
data "aws_ecs_task_execution" "before" {
  cluster         = "cluster"
  task_definition = ...
  desired_count   = 1
  launch_type     = "FARGATE"

  overrides {
    container_overrides {
      name    = "container"

      cpu    = 256
      memory = 512
    }

    cpu    = 256
    memory = 512
  }
}
```

### Debug Output
```
"overrides": {
                "containerOverrides": [
                    {
                        "name": "container",
                        "cpu": 256,
                        "memory": 0
                    }
                ],
                "cpu": "256",
                "inferenceAcceleratorOverrides": [],
                "executionRoleArn": "",
                "memory": "512",
                "taskRoleArn": ""
            }
...
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @vstepanyuk 👋 Thank you for taking the time to raise this! I've opened a pull request to correct this.
