### ISSUE TITLE
[Bug]: Terraform crashes importing RDS DBInstance

### ISSUE THREAD

**Issue by KoBrane** [hashicorp/terraform-provider-aws#32781]
### Terraform Core Version

1.5.4

### AWS Provider Version

5.10.0

### Affected Resource(s)

aws_db_instance

### Expected Behavior

terraform to import the configurations of the db instance manually created

### Actual Behavior

Terraform crash report

### Relevant Error/Panic Output Snippet

```shell
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 109 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.20.0/x64/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/Users/runner/hostedtoolcache/go/1.20.0/x64/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x153
panic({0x3034740, 0x4df2840})
	/Users/runner/hostedtoolcache/go/1.20.0/x64/src/runtime/panic.go:890 +0x263
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0xc0009db4a0, {0x3a05ff8, 0xc0004869a0})
	/Users/runner/work/terraform/terraform/internal/terraform/node_resource_plan_instance.go:288 +0x17c6
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0x0?, {0x3a05ff8?, 0xc0004869a0?}, 0x0?)
	/Users/runner/work/terraform/terraform/internal/terraform/node_resource_plan_instance.go:74 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc001c6ca20, {0x3a05ff8, 0xc0004869a0}, {0x2d8a75b8, 0xc0009db4a0})
	/Users/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:143 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x339f680, 0xc0009db4a0})
	/Users/runner/work/terraform/terraform/internal/terraform/graph.go:78 +0x315
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000d19860, {0x339f680, 0xc0009db4a0}, 0xc008192240)
	/Users/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2f6
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/Users/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xdfe
```

### Terraform Configuration Files

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 109 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.20.0/x64/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/Users/runner/hostedtoolcache/go/1.20.0/x64/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x153
panic({0x3034740, 0x4df2840})
	/Users/runner/hostedtoolcache/go/1.20.0/x64/src/runtime/panic.go:890 +0x263
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0xc0009db4a0, {0x3a05ff8, 0xc0004869a0})
	/Users/runner/work/terraform/terraform/internal/terraform/node_resource_plan_instance.go:288 +0x17c6
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0x0?, {0x3a05ff8?, 0xc0004869a0?}, 0x0?)
	/Users/runner/work/terraform/terraform/internal/terraform/node_resource_plan_instance.go:74 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc001c6ca20, {0x3a05ff8, 0xc0004869a0}, {0x2d8a75b8, 0xc0009db4a0})
	/Users/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:143 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x339f680, 0xc0009db4a0})
	/Users/runner/work/terraform/terraform/internal/terraform/graph.go:78 +0x315
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000d19860, {0x339f680, 0xc0009db4a0}, 0xc008192240)
	/Users/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2f6
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/Users/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xdfe

### Steps to Reproduce

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 109 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.20.0/x64/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/Users/runner/hostedtoolcache/go/1.20.0/x64/src/runtime/debug/stack.go:16 +0x19
github.com/hashicorp/terraform/internal/logging.PanicHandler()
	/Users/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x153
panic({0x3034740, 0x4df2840})
	/Users/runner/hostedtoolcache/go/1.20.0/x64/src/runtime/panic.go:890 +0x263
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).managedResourceExecute(0xc0009db4a0, {0x3a05ff8, 0xc0004869a0})
	/Users/runner/work/terraform/terraform/internal/terraform/node_resource_plan_instance.go:288 +0x17c6
github.com/hashicorp/terraform/internal/terraform.(*NodePlannableResourceInstance).Execute(0x0?, {0x3a05ff8?, 0xc0004869a0?}, 0x0?)
	/Users/runner/work/terraform/terraform/internal/terraform/node_resource_plan_instance.go:74 +0x90
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc001c6ca20, {0x3a05ff8, 0xc0004869a0}, {0x2d8a75b8, 0xc0009db4a0})
	/Users/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:143 +0xc2
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x339f680, 0xc0009db4a0})
	/Users/runner/work/terraform/terraform/internal/terraform/graph.go:78 +0x315
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc000d19860, {0x339f680, 0xc0009db4a0}, 0xc008192240)
	/Users/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2f6
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update
	/Users/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xdfe

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform/blob/74adf9bc608ae5a9506a369c57eecb9973ed166d/internal/terraform/node_resource_plan_instance.go#L271-L288

**Comment by ewbankkit** [comment]
@KoBrane Thanks for raising this issue 👏.
Can you paste in the Terraform configuration and commands that cause this crash?

**Comment by KoBrane** [comment]
This issue is resolved. The issue bothers on my import configuration. 
 import {
   to = aws_db_instane.db
   id = ""
}

Which was was not detailed enough
