### ISSUE TITLE
[Enhancement]: Change lambda_event_source_mapping filter_criteria MaxItems size from 5 to 10

### ISSUE THREAD

**Issue by tomaszkrys** [hashicorp/terraform-provider-aws#32806]
### Description

Base on AWS documentation you are able to increase lambda_event_source_mapping filter limit from 5 to 10. With this change having MaxItems set to 5 you are not able to apply more filter.

<img width="1186" alt="image" src="https://github.com/hashicorp/terraform-provider-aws/assets/6449485/e3eadc0d-1ffa-420b-ad98-d2f3c1e89fa8">

### Affected Resource(s) and/or Data Source(s)

lambda_event_source_mapping

### References

https://github.com/hashicorp/terraform-provider-aws/blob/59e9dfdd4ffa1c69b2155dc995079a27a7cb8c19/internal/service/pipes/source_parameters.go#L167C1-L167C1

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @tomaszkrys 👋 Thank you for taking the time to raise this! I've opened a pull request to increase the `MaxItems` to 10.
