### ISSUE TITLE
[Bug]: AWS Lambda - Python 3.11 Runtime

### ISSUE THREAD

**Issue by jordancparker** [hashicorp/terraform-provider-aws#32817]
### Terraform Core Version

1.5.4

### AWS Provider Version

5.10

### Affected Resource(s)

Hi AWS, 

Lambda release Python 3.11, however terraform has a condition to not accept it as a value. Can we add to the next release update python3.11

Error:

Error: expected runtime to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x nodejs16.x java8 java8.al2 java11 python2.7 python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 dotnet6 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2 nodejs18.x python3.10 java17 ruby3.2], got python3.11

### Expected Behavior

Conditional Access deploy a version python3.11

### Actual Behavior

Conditional Rejects deploying a version python3.11

### Relevant Error/Panic Output Snippet

```shell
Error:

Error: expected runtime to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x nodejs16.x java8 java8.al2 java11 python2.7 python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 dotnet6 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2 nodejs18.x python3.10 java17 ruby3.2], got python3.11
```

### Terraform Configuration Files

runtime          = "python3.11"

### Steps to Reproduce

runtime          = "python3.11"

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/32726.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/32764.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/32777.
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/32729.
