### ISSUE TITLE
[Enhancement]: Add metric select feature in cloudwatch_metric_stream resource

### ISSUE THREAD

**Issue by sidnhs** [hashicorp/terraform-provider-aws#32841]
### Description

At the moment, it seems like we are only able to include filters to add specific namespaces which would then pass along all the metrics under it to firehose e.g. but on the console we have an option to select metrics under it that we can send which doesn't seem to be available in terraform:
![image](https://github.com/hashicorp/terraform-provider-aws/assets/85891980/c8d264c2-aa95-4a23-a8c7-98b3f63d5774)

### Affected Resource(s) and/or Data Source(s)

aws_cloudwatch_metric_stream

### Potential Terraform Configuration

```terraform
resource "aws_cloudwatch_metric_stream" "splunk" {
  name          = local.csi
  role_arn      = module.kinesis_firehose_to_splunk_metrics.metric_stream_role_arn
  firehose_arn  = module.kinesis_firehose_to_splunk_metrics.firehose_delivery_stream_arn
  output_format = "json"

 include_filter {
    namespace = "AWS/SQS"
    metrics = ["NumberOfMessagesSent", "ApproximateNumberOfMessagesVisibile"]
  }
}
```

### Would you like to implement a fix?

None

**Comment by dandelo** [comment]
Looks like you can already do this since version 4.67.0:
https://registry.terraform.io/providers/hashicorp/aws/4.67.0/docs/resources/cloudwatch_metric_stream#include_filter

```
  include_filter {
    namespace    = "AWS/EC2"
    metric_names = ["CPUUtilization", "NetworkOut"]
  }
```
