### ISSUE TITLE
[Bug]: Cannot add core.lazy_load_plugins to resource "aws_mwaa_environment"

### ISSUE THREAD

**Issue by lukeyz1** [hashicorp/terraform-provider-aws#32851]
### Terraform Core Version

Terraform v1.5.3

### AWS Provider Version

aws v4.45.0

### Affected Resource(s)

- aws_mwaa_environment

As stated in the terraform docs for mwaa:
This resource supports the following arguments:

[airflow_configuration_options](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mwaa_environment#airflow_configuration_options) - (Optional) The airflow_configuration_options parameter specifies airflow override options. Check the [Official documentation](https://docs.aws.amazon.com/mwaa/latest/userguide/configuring-env-variables.html#configuring-env-variables-reference) for all possible configuration options.

The official documentation states if you are using custom plugins in Airflow Apache v2 you must add
- core.lazy_load_plugins : False as a configuration option.

### Expected Behavior

- core.lazy_load_plugins : False/True is added as a configuration option in MWAA and terraform is able to reference this.

### Actual Behavior

Terraform is unable to reference core.lazy_load_plugins and an invalid reference error is received.

This means, any user using custom plugins will need to add core.lazy_load_plugins manually to the mwaa environment (via the UI added after terraform has applied the configuration.

### Relevant Error/Panic Output Snippet

```shell
│ Error: Invalid reference
│
│   on mwaa_environment.tf line 5, in resource "aws_mwaa_environment" "mwaa":
│    5:     "core.lazy_load_plugins"              = False
│
│ A reference to a resource type must be followed by at least one attribute access, specifying the resource name.
```

### Terraform Configuration Files

```terraform
resource "aws_mwaa_environment" "mwaa" {
  airflow_configuration_options = {
    "core.default_task_retries"           = 3
    "core.parallelism"                    = 20
    "core.lazy_load_plugins"              = False
    "webserver.web_server_master_timeout" = 600
    "webserver.web_server_worker_timeout" = 600
    "min_workers"                         = 2
  }
```

### Steps to Reproduce

- Apply above configuration
- Observe

### Would you like to implement a fix?

None

**Comment by dcabaceira** [comment]
`"core.lazy_load_plugins" : "false"`

Should solve it.

**Comment by lukeyz1** [comment]
Thanks @dcabaceira! I overlooked adding the quotes in, this was my mistake. Closing this thread.
