### ISSUE TITLE
[Enhancement]: aws_ecs_task_set should not be considered created until stability_status is STABLE

### ISSUE THREAD

**Issue by kgonyon** [hashicorp/terraform-provider-aws#32864]
### Description

Right now if you create an `aws_ecs_task_set` resource it will immediately succeed moving on to the next resource. The issue we are having is when you replace a task set with `create_before_destroy = true` the old task_set will still be destroyed before your servers are running.

Right now we are using a provisioner to check if the new task_set has reached stability. I am not sure this is the best solution.

### Affected Resource(s) and/or Data Source(s)

aws_ecs_task_set

### Would you like to implement a fix?

No

**Comment by DanielRieske** [comment]
@kgonyon I looked into this because and it seems there is a bool you can set called `wait_until_stable`
Can you check when setting this bool if that solves your issue?

`wait_until_stable` - (Optional) Whether terraform should wait until the task set has reached `STEADY_STATE`

**Comment by kgonyon** [comment]
Yes, that did solve the issue. I was looking all over those docs and totally missed that somehow. I apologize.
