### ISSUE TITLE
[Bug]: AppStream 2.0 fleet: raise maximum session duration from 360000 to 432000

### ISSUE THREAD

**Issue by dbarlett** [hashicorp/terraform-provider-aws#32874]
### Terraform Core Version

1.5.4

### AWS Provider Version

5.11.0

### Affected Resource(s)

* aws_appstream_fleet

### Expected Behavior

Should be able to create and update a fleet with `max_user_duration_in_seconds` between 600 and 432000.

### Actual Behavior

Validation fails if  `max_user_duration_in_seconds` is greater than 360000.

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: expected max_user_duration_in_seconds to be in the range (600 - 360000), got 432000
│ 
│   with aws_appstream_fleet.test_fleet,
│   on main.tf line 28, in resource "aws_appstream_fleet" "test_fleet":
│   28:   max_user_duration_in_seconds       = 432000
│
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.11.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_appstream_fleet" "test_fleet" {
  name = "test-fleet"

  compute_capacity {
    desired_instances = 1
  }

  description                        = "test fleet"
  idle_disconnect_timeout_in_seconds = 60
  display_name                       = "test-fleet"
  enable_default_internet_access     = false
  fleet_type                         = "ON_DEMAND"
  image_name                         = "Amazon-AppStream2-Sample-Image-03-11-2023"
  instance_type                      = "stream.standard.large"
  max_user_duration_in_seconds       = 432000

  vpc_config {
    subnet_ids = ["subnet-02710b0ca492d7b51"]
  }

}
```

### Steps to Reproduce

1. Create `main.tf` with the provided contents.
2. Run `terraform validate`.

### Important Factoids

https://github.com/hashicorp/terraform-provider-aws/blob/v5.11.0/internal/service/appstream/fleet.go#L91C45-L91C51 is outdated. AWS documentation (see References) was recently updated to reflect the correct maximum value.

### References

- https://docs.aws.amazon.com/appstream2/latest/APIReference/API_CreateFleet.html#AppStream2-CreateFleet-request-MaxUserDurationInSeconds
- https://docs.aws.amazon.com/appstream2/latest/APIReference/API_UpdateFleet.html#AppStream2-UpdateFleet-request-MaxUserDurationInSeconds

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @dbarlett 👋 Thank you for taking the time to raise this! I've opened a pull request to update the validation to accept values up to 432000.
