### ISSUE TITLE
[Bug][service/rds]: Removing restore_to_point_in_time attributes on aws_rds_cluster results in a replacing the cluster.

### ISSUE THREAD

**Issue by charlesm94** [hashicorp/terraform-provider-aws#32888]
### Terraform Core Version

1.3.7

### AWS Provider Version

4.67.0

### Affected Resource(s)

* aws_rds_cluster

### Expected Behavior

When setting dynamic block for restore_to_point_in_time_restore to false the aws_rds_cluster expected behavior is for the restore_to_point_in_time attributes to be set to null with the cluster executing the changes in-place.

```
  dynamic "restore_to_point_in_time" {
    for_each = local.is_point_in_time_restore ? [1] : []
    content {

          source_cluster_identifier     = var.source_identifier
          restore_type                          = 'copy-on-write'
          use_latest_restorable_time = true
      }
  }
```

### Actual Behavior

aws_rds_cluster is being destroyed and recreated instead of updated in place. Is this expected?

```
### Terraform Configuration Files

resource "aws_rds_cluster" "my_cluster" {
  provider                            = aws.primary
  db_subnet_group_name                = aws_db_subnet_group.my_subnet_group.id
  vpc_security_group_ids              = [aws_security_group.my_security_group.id]
  cluster_identifier                  = "mycluster"
  engine                              = "aurora-postgresql"
  engine_version                      = "14.8"
  engine_mode                         = "provisioned"
  database_name                       = "mydb"
  master_username                     = "admin"
  master_password                     = "xxxxx"
  storage_encrypted                   = true
  kms_key_id                          = aws_kms_key.my_kms_key.arn 
  final_snapshot_identifier           = "my-cluster-final"
  backup_retention_period             = 35


  dynamic "restore_to_point_in_time" {
    for_each = local.is_fast_clone ? [1] : []
    content {

          source_cluster_identifier  = var.fast_clone_source_cluster_identifier
          restore_type               = var.fast_clone_restore_type
          use_latest_restorable_time = var.fast_clone_use_latest_restorable_time
      }
  }

}
```
### Steps to Reproduce

Create an aws_rds_cluster using restore_to_point_in_time using the copy-on-write protocol referencing a source Aurora cluster. 

Once the restored cluster is provisioned set local.is_fast_clone on the dynamic block to false. Run Terraform plan. 

### Would you like to implement a fix?

None

**Comment by charlesm94** [comment]
Workaround we found was to use ignore_changes specifying the restore_to_point_in_time dynamic block. That avoided the cluster rebuild. 

Although I'm still interested to see if it's expected behavior for the cluster to rebuild if the restore_to_point_in_time attributes are removed.

**Comment by justinretzolk** [comment]
Hey @charlesm94 👋 Thanks for taking the time to come back and let us know! Upon further review, it looks like this block is indeed [marked as `ForceNew`](https://github.com/hashicorp/terraform-provider-aws/blob/4a16eccf5ad47dff9e3a0a7f5c0504d8286153f7/internal/service/rds/cluster.go#L341), so I would expect this behavior. With that and your most recent comment in mind, we'll close this issue.
