### ISSUE TITLE
[Enhancement]: Add support to time to live (TTL) in SageMaker online Feature Store

### ISSUE THREAD

**Issue by danilko** [hashicorp/terraform-provider-aws#32901]
### Description

Requesting that Terraform add support for time to live (TTL) in SageMaker online Feature Store. SageMaker Feature Store added support for setting up TTL at feature group level for online Feature Store 06/30/2023 (announced [here](https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-sagemaker-feature-store-ttl-online-store/)). 
Docs are ([here](https://docs.aws.amazon.com/sagemaker/latest/dg/feature-store-time-to-live.html)). 

Thanks.

### Affected Resource(s) and/or Data Source(s)

aws_sagemaker_feature_group

### Potential Terraform Configuration

```terraform
resource "aws_sagemaker_feature_group" "customer_feature_group" {
  feature_group_name             = "fg1"
  record_identifier_feature_name = "customer_id"
  event_time_feature_name        = "at"
  role_arn                       = aws_iam_role.feature_group_role.arn
  feature_definition {
    feature_name = "customer_id"
    feature_type = "String"
  } ...
  online_store_config {
    enable_online_store = true
     ttl_duration {
       unit           = "Weeks"
       value          = 4
    }
  } ...
}
```

### References

Docs are ([here](https://docs.aws.amazon.com/sagemaker/latest/dg/feature-store-time-to-live.html)). 

Above code sample is provided based on how AWS Pyhton SDK's code will behave
```
import boto3

sagemaker_client = boto3.client("sagemaker")
feature_group_name = '<YOUR_FEATURE_GROUP_NAME>'

sagemaker_client.update_feature_group(
    FeatureGroupName=feature_group_name,
    OnlineStoreConfig={
        TtlDuration:{
            Unit: "Weeks",
            Value: 4
        }
    }
)
```

### Would you like to implement a fix?

None

**Comment by DrFaust92** [comment]
looking into this
