### ISSUE TITLE
Offer reading doc via JetBrains IDE

### ISSUE THREAD

**Issue by landsman** [hashicorp/terraform-provider-aws#32912]
### Description

Why am I unable to display the documentation reference for a resource?

<img width="387" alt="Screenshot 2023-08-08 at 20 34 57" src="https://github.com/hashicorp/terraform-provider-aws/assets/3184228/795b9253-0098-437a-89be-25abf18330c5">

It's located here: https://registry.terraform.io/providers/hashicorp/aws/latest/docs, but I cannot access it via the IDE. :(
Is this something you can help @jetbrains, or is it unavailable in general? It would be wonderful to work in editor only. This screenshot is from Intellij Idea Ultimate.

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @landsman 👋 Thank you for taking the time to raise this! I'm not familiar with the functionality that you're looking for, but it appears this may be more of a request for JetBrains than an issue with the AWS provider. With that in mind, I'll close this particular issue out. If I've misunderstood, or you feel I've done this in error, please do let me know.
