### ISSUE TITLE
[Enhancement]: Add EKS Runtime monitoring to Guard Duty

### ISSUE THREAD

**Issue by Chainshark** [hashicorp/terraform-provider-aws#32949]
### Description

Guard Duty now supports EKS Runtime monitoring, but it is not configurable in Terraform at the moment.

### Affected Resource(s) and/or Data Source(s)

* aws_guardduty_detector
* aws_guardduty_organization_configuration

### Potential Terraform Configuration

```terraform
It currently allows EKS Audit Logs in the format

resource "aws_guardduty_detector" "MyDetector" {
  enable = true

  datasources {
    s3_logs {
      enable = true
    }
    kubernetes {
      audit_logs {
        enable = false
      }
    }


It would look like 

resource "aws_guardduty_detector" "MyDetector" {
  enable = true

  datasources {
    s3_logs {
      enable = true
    }
    kubernetes {
      audit_logs {
        enable = true
      }
      runtime {
       enabled = true
    }
```

### References

https://docs.aws.amazon.com/guardduty/latest/ug/guardduty-eks-runtime-monitoring.html

### Would you like to implement a fix?

None

**Comment by autarchprinceps** [comment]
This should probably also include not just the runtime, but also the runtime agent deployment:
![image](https://github.com/hashicorp/terraform-provider-aws/assets/239063/f33ff03b-75e2-4581-a770-5db4ee57556b)

**Comment by andrew-ar** [comment]
As EKS Runtime Monitoring is an EKS add-on, I'm wondering if the deployment of the runtime agent would be done by using the existing `aws_eks_addon` resource? It looks like that's designed in a pretty generic way so maybe it won't need changes.

That said, it would be helpful to have a bit of documentation on how to configure the monitoring agent, as it seems like there are at least a few [config options](https://docs.aws.amazon.com/guardduty/latest/ug/eks-protection-configuration.html) and it would be good to have an example. Perhaps the config would sit under the `aws_guardduty_organization_configuration` resource, or perhaps some might end up under `aws_eks_addon`, it would be good to understand where it would go and what it would look like.

**Comment by macmiranda** [comment]
> As EKS Runtime Monitoring is an EKS add-on, I'm wondering if the deployment of the runtime agent would be done by using the existing `aws_eks_addon` resource? It looks like that's designed in a pretty generic way so maybe it won't need changes.
> 
> That said, it would be helpful to have a bit of documentation on how to configure the monitoring agent, as it seems like there are at least a few [config options](https://docs.aws.amazon.com/guardduty/latest/ug/eks-protection-configuration.html) and it would be good to have an example. Perhaps the config would sit under the `aws_guardduty_organization_configuration` resource, or perhaps some might end up under `aws_eks_addon`, it would be good to understand where it would go and what it would look like.

The add-on needs to be enabled for the agent to gather events and send them to Guardduty but the Guardduty feature needs to be enabled [nevertheless](https://docs.aws.amazon.com/guardduty/latest/ug/eks-runtime-monitoring-security-agent-manual.html#:~:text=The%20GuardDuty%20security%20agent%20(EKS%20add%2Don)%20will%20not%20work%20if%20you%20do%20not%20enable%20EKS%20Runtime%20Monitoring.).

Example CLI command:
```
aws guardduty update-detector --detector-id 12abc34d567e8fa901bc2d34e56789f0 --acount-ids 555555555555 --features '[{"Name" : "EKS_RUNTIME_MONITORING", "Status" : "ENABLED", "AdditionalConfiguration" : [{"Name" : "EKS_ADDON_MANAGEMENT", "Status" : "DISABLED"}] ]'
```

**Comment by autarchprinceps** [comment]
> As EKS Runtime Monitoring is an EKS add-on, I'm wondering if the deployment of the runtime agent would be done by using the existing `aws_eks_addon` resource? It looks like that's designed in a pretty generic way so maybe it won't need changes.
> 
> That said, it would be helpful to have a bit of documentation on how to configure the monitoring agent, as it seems like there are at least a few [config options](https://docs.aws.amazon.com/guardduty/latest/ug/eks-protection-configuration.html) and it would be good to have an example. Perhaps the config would sit under the `aws_guardduty_organization_configuration` resource, or perhaps some might end up under `aws_eks_addon`, it would be good to understand where it would go and what it would look like.

No, that is something else. This is the org wide auto enablement of the deployment of that EKS addon and is a guardduty setting. You can of course manually deploy it, but that is not what we are talking about here.

**Comment by ewbankkit** [comment]
You will be able to use the upcoming `aws_guardduty_detector_feature` resource (https://github.com/hashicorp/terraform-provider-aws/pull/31463):

```hcl
resource "aws_guardduty_detector" "example" {
  enable = true
}

resource "aws_guardduty_detector_feature" "example" {
  detector_id = aws_guardduty_detector.example.id
  name        = "EKS_RUNTIME_MONITORING"
  status      = "ENABLED"

  additional_configuration {
    name   = "EKS_ADDON_MANAGEMENT"
    status = "ENABLED"
  }
}
```
