### ISSUE TITLE
[Docs]: aws_lambda_function - supported versions for snap start are not up to date

### ISSUE THREAD

**Issue by jho-di** [hashicorp/terraform-provider-aws#32953]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#snap_start

### Description

The current documentation says the 

> This feature is currently only supported for java11 runtimes.

However, according to the official documentation on https://docs.aws.amazon.com/lambda/latest/dg/snapstart.html#snapstart-runtimes java17 is supported as well.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @jho-di 👋 Thank you for taking the time to raise this, and for helping us to improve our documentation! I've opened a pull request to update the documentation as needed.
