### ISSUE TITLE
[Enhancement]: Provider default_tags and resource tags should merge when its identical 

### ISSUE THREAD

**Issue by andavarv** [hashicorp/terraform-provider-aws#32979]
### Description

Provider default_tags and resource tags should merge when its identical.  but its throwing an error.

```terraform
terraform {
  required_version = ">= 1.0.0, < 2.0.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.41.0, < 5.0.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
  default_tags {
    tags = {
      Name      = "test_defaults_loggroup",
      Component = "test_component"
    }
  }
}

resource "aws_cloudwatch_log_group" "api_log_group" {
  name              = "test"
  retention_in_days = 7
  tags              = { Name = "test_defaults_loggroup" }
}
```

Error

![image](https://github.com/hashicorp/terraform-provider-aws/assets/11995366/690332ad-60ba-4160-9551-38de833491c7)

### Affected Resource(s) and/or Data Source(s)

provider "aws" {
}

### Would you like to implement a fix?

None

**Comment by devopsrick** [comment]
This is fixed in the 5.x release.

**Comment by justinretzolk** [comment]
Hey @andavarv 👋 Can you test this with AWS Provider version 5.0 or later? We did a fairly large overhaul of tags in that major version, and as mentioned above, this should be fixed as of that version.

**Comment by andavarv** [comment]
Yes its working fine when I start using AWS Provider version 5+ 

Thanks
