### ISSUE TITLE
AWS RDS || enable Microsoft SQL Server Windows authentication

### ISSUE THREAD

**Issue by g2r1990** [hashicorp/terraform-provider-aws#32998]
### Description

Hello Team, 

Greetings !!!

 I have a working code of Terraform, which created the AWS RDS instance, but recently, we came-up with the required to enable the  Microsoft SQL Server Windows authentication for the RDS Instance. 

The RDS instance which gets created from the existing Terraform code is with the following configuration.  

SQL Server Standard Edition
Engine version : 15.00.4153.1.v1

I have tried using the "iam_database_authentication_enabled=true"  in my RDS block, but it gives the following error. 

Error: updating RDS DB Instance (instance-name): operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: 156cd799-1726-4df5-8707-e3563808a588, api error InvalidParameterCombination: IAM Database Authentication is not supported for engine sqlserver-se.
│ 
│   with module.apps.module.app_rds_sql.module.rds.module.db_instance.aws_db_instance.this[0],
│   on .terraform/modules/apps.app_rds_sql.rds/modules/db_instance/main.tf line 29, in resource "aws_db_instance" "this":
│   29: resource "aws_db_instance" "this" {
│ 
╵

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @g2r1990 👋 Thank you for taking the time to raise this! I did a bit of reading over [this AWS document](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_SQLServerWinAuth.html), which leads me to believe that the values you'd be looking to update to enable this would be [`domain`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#domain) and [`domain_iam_role_name`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#domain_iam_role_name). Can you take a look over that and see if that resolves your issue? If it does not, please supply a sample Terraform configuration and debug logs (redacted as needed).

**Comment by g2r1990** [comment]
Hello @justinretzolk .
Thank you for sharing the details. 
I have gone through the AWS article and In my case the issue was with the IAM role for the RDS, I have created a specific role for the RDS and the issue got resolved.
