### ISSUE TITLE
[Bug]: Incorrect validation of 'basic_auth' in resource 'aws_pipes_pipe' for self managed Kafka configuration

### ISSUE THREAD

**Issue by danizzvargas** [hashicorp/terraform-provider-aws#33025]
### Terraform Core Version

1.5.5

### AWS Provider Version

5.12.0

### Affected Resource(s)

* `aws_pipes_pipe`, section: `source_parameters.self_managed_kafka_parameters.credentials.basic_auth`

### Expected Behavior

When credentials for a Self Managed Kafka source are configured, the "basic_auth" property should be optional, so that it is not required when configuring TLS or SASL credentials.

### Actual Behavior

Validation fails when the "basic_auth" configuration is omitted.

### Terraform Configuration Files

```tf
resource "aws_pipes_pipe" "example" {
  name     = "example-pipe"
  role_arn = var.role_arn
  source   = var.source
  target   = var.target

  source_parameters {
    self_managed_kafka_parameters {
      additional_bootstrap_servers = [ var.aditional_sever_1, var.aditional_sever_2 ]
      credentials {
        client_certificate_tls_auth = var.client_certificate_tls_auth
      }
      topic_name = var.topic_name
    }
  }
}
```

### Steps to Reproduce

* Configure a new pipe using a Self Managed Kafka as source, with credentials other than "basic_auth". 
* When running `terraform validate`, the following error will be displayed:
```
The argument "basic_auth" is required, but no definition was found.
```

### Important Factoids

The error is in the schema definition, in the following line of code:
https://github.com/hashicorp/terraform-provider-aws/blob/e8931004742d138892921e19456b0b98ae9292a0/internal/service/pipes/source_parameters.go#L447
Since it is defined as `Required`, the "basic_auth" setting is mandatory.

### Would you like to implement a fix?

None

**Comment by erlandsen-tech** [comment]
This is still an issue in 1.7.3
