### ISSUE TITLE
[Docs]: db_instance_arn not working

### ISSUE THREAD

**Issue by KrisAff84** [hashicorp/terraform-provider-aws#33021]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/db_instance

### Description

The db_instance_arn data source is not working. I used arn instead and it worked. 

### Would you like to implement a fix?

None

**Comment by KrisAff84** [comment]
Similarly, db_instance_identifier was also not working for me. Changing to simply identifier worked.

**Comment by justinretzolk** [comment]
Hey @KrisAff84 👋 Thank you for taking the time to raise this! So that we have the information necessary in order to look into this, can you supply a sample Terraform configuration that can be used to reproduce the issue, along with debug logs (redacted as needed)?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
