### ISSUE TITLE
[Bug]: aws_securityhub_account resource is broken in the aws-us-gov partition since 4.64.0

### ISSUE THREAD

**Issue by iamperson347** [hashicorp/terraform-provider-aws#33039]
### Terraform Core Version

1.4.6

### AWS Provider Version

4.64.0,4.67.0,5.12.0

### Affected Resource(s)

aws_securityhub_account 

### Expected Behavior

resource works in govcloud partition

### Actual Behavior

(Copied from #31822 so this gets a bug label)

Finding that the aws_securityhub_account resource is broken in the aws-us-gov partition since 4.64.0, since that partition does not yet support control_finding_generator. Also somehow the default value the provider is sending through is SECURITY_CONTROL, which just seems wrong in general since AWS defaults to STANDARD_CONTROL and requires explicitly enabling SECURITY_CONTROL in Security Hub.

Minimal reproducing config is just:

```terraform
resource "aws_securityhub_account" "this" {}
```

results in:

```shell
  # aws_securityhub_account.this will be updated in-place
  ~ resource "aws_securityhub_account" "this" {
      + control_finding_generator = "SECURITY_CONTROL"
```

which can actually apply successfully, somehow, but then results in a perpetual diff

Originally posted by @lorengordon in https://github.com/hashicorp/terraform-provider-aws/issues/30980#issuecomment-1580871565

### Relevant Error/Panic Output Snippet

```shell
~ resource "aws_securityhub_account" "securityhub" {
      + control_finding_generator = "SECURITY_CONTROL"
```

### Terraform Configuration Files

```terraform
resource "aws_securityhub_account" "this" {}
```

### Steps to Reproduce

terraform init and plan in us-govcloud region in AWS

### References

https://docs.aws.amazon.com/securityhub/latest/userguide/controls-findings-create-update.html

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @iamperson347 👋 We recently had some issues with one of our labeling Actions, and it looks like the issue that you referenced slipped through the cracks, so you raising this one to get our attention was really helpful; thank you for doing that. I've labeled this as a regression as well.

Relates #30692 <- PR introducing the bug, as called out in comments on previous issues
Relates #30980
Relates #31822
