### ISSUE TITLE
Unable to modify db option group || Modifying DB Option Group: InvalidParameterValue

### ISSUE THREAD

**Issue by g2r1990** [hashicorp/terraform-provider-aws#33041]
### Description

Hello Team, 

I have the below terraform code which works perfectly fine, but when I tired to add option for the MSDTC , it fails with the below error message. 

```shell
│ Error: modifying DB Option Group: InvalidParameterValue: At least one security group must be specified for the MSDTC option.
│ 	status code: 400, request id: 6248c234-82d7-4e42-ab45-346758013f96
```

I was able to update the same using the below AWS CLI query. 

```shell
aws rds add-option-to-option-group --option-group-name msdtc --options "OptionName=MSDTC,OptionSettings=[{Name=AUTHENTICATION,Value=MUTUAL},{Name=TRANSACTION_LOG_SIZE,Value=4},{Name=ENABLE_XA,Value=true}],Port=5000,VpcSecurityGroupMemberships=sg-msdtc" --apply-immediately
```

Below is the terraform code. 

```terraform
locals {
  rds_option_settings = [
    {
      option_name = "MSDTC"
      option_settings = [
        {
          name  = "AUTHENTICATION"
          value = "MUTUAL"
        },
        {
          name  = "TRANSACTION_LOG_SIZE"
          value = "4"
        },
        {
          name  = "ENABLE_XA"
          value = "true"
        },

        {
          name  = "ApplyMethod"
          value = "immediate"
        },
        {
          name = "VpcSecurityGroupMemberships"
          value = jsonencode([
            {
              "VpcSecurityGroupId" = "sg-msdtc"
            }
          ])
        },
      ]
    }
  ]
}
module "rds" {
  source  = "terraform-aws-modules/rds/aws"
  version = ">= 5.0"

  providers = {
    aws = aws.mapdba
  }
///// other configuration code
  # DB option group
  create_db_option_group = var.create_rds_option_group
  option_group_name      = var.create_rds_option_group == true ? var.rds_option_group_name : null
  options = var.create_rds_option_group == true ? local.rds_option_settings : []
 ///// other configuration code
```

Note: 
1. The RDS instance is attached with the directory service. 
2. I am able to add the option for MSDTC using AWS console page and AWS CLI cloud shell command. 

Any help will be highly appreciated. 

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @g2r1990 👋 Thanks for taking the time to raise this! In this case, it looks like we can fix this one with a configuration change. I took a look over the [module's configuration](https://github.com/terraform-aws-modules/terraform-aws-rds/blob/8b2f5c5587f88a5694c3668aaf43f175842f9e4f/modules/db_option_group/main.tf#L17-L34) in terms of how it processes the inputs, and noted this line in particular:

```terraform
vpc_security_group_memberships = lookup(option.value, "vpc_security_group_memberships", null)
```

The [`option.vpc_security_group_memeberships` argument](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_option_group#vpc_security_group_memberships) takes a list, so I believe if you change the shape if your `rds_option_settings` local slightly, your applies will succeed.

```terraform
# Note: I added `port` too, since I saw it in your CLI command
locals {
  rds_option_settings = [
    {
      option_name = "MSDTC"
      port = 5000
      vpc_security_group_memberships = [
        "sg-msdtc"
      ]
      option_settings = [
        {
          name  = "AUTHENTICATION"
          value = "MUTUAL"
        },
        {
          name  = "TRANSACTION_LOG_SIZE"
          value = "4"
        },
        {
          name  = "ENABLE_XA"
          value = "true"
        },
        {
          name  = "ApplyMethod"
          value = "immediate"
        },
      ]
    }
  ]
}
```

**Comment by g2r1990** [comment]
hello @justinretzolk 
Yeah , that worked thanks.    One correction in code, the MSDTC doesn't support the apply immediately option. 

{
      option_name = "MSDTC"
      port        = 5000
      vpc_security_group_memberships = [
        "sg-msdtc"
      ]
      option_settings = [
        {
          name  = "AUTHENTICATION"
          value = "MUTUAL"
        },
        {
          name  = "TRANSACTION_LOG_SIZE"
          value = "4"
        },
        {
          name  = "ENABLE_XA"
          value = "true"
        },
      ]
    },
  ]

**Comment by justinretzolk** [comment]
Thanks for the update @g2r1990! I'm happy to hear that got things working. With that in mind, I'll go ahead and close this issue out.
