### ISSUE TITLE
[Bug]: An argument named is not expected here.

### ISSUE THREAD

**Issue by zubeyiro** [hashicorp/terraform-provider-aws#33045]
### Terraform Core Version

1.5.5

### AWS Provider Version

5.0.1

### Affected Resource(s)

aws_elasticache_replication_group

### Expected Behavior

It should have plan the infra

### Actual Behavior

its complaining that arguments -that are being mentioned in docs- are not expected

### Relevant Error/Panic Output Snippet

```shell
│ Error: Unsupported argument
│ 
│   on modules/elasticache/main.tf line 12, in resource "aws_elasticache_replication_group" "example":
│   12:   availability_zones            = ["us-west-2a", "us-west-2b"]
│ 
│ An argument named "availability_zones" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on modules/elasticache/main.tf line 14, in resource "aws_elasticache_replication_group" "example":
│   14:   replication_group_description = "test description"
│ 
│ An argument named "replication_group_description" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on modules/elasticache/main.tf line 16, in resource "aws_elasticache_replication_group" "example":
│   16:   number_cache_clusters         = 2
│ 
│ An argument named "number_cache_clusters" is not expected here.
```

### Terraform Configuration Files

```terraform
resource "aws_elasticache_replication_group" "example" {
  automatic_failover_enabled    = true
  availability_zones            = ["us-west-2a", "us-west-2b"]
  replication_group_id          = "tf-rep-group-1"
  replication_group_description = "test description"
  node_type                     = "cache.m4.large"
  number_cache_clusters         = 2
  parameter_group_name          = "default.redis3.2"
  port                          = 6379

  lifecycle {
    ignore_changes = [number_cache_clusters]
  }
}

resource "aws_elasticache_cluster" "replica" {
  count = 1

  cluster_id           = "tf-rep-group-1-${count.index}"
  replication_group_id = aws_elasticache_replication_group.example.id
}
```

### Steps to Reproduce

`terraform plan` `terraform validate`

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @zubeyiro 👋 Thank you for taking the time to raise this! It looks like the arguments you're attempting to supply are arguments that have been deprecated and subsequently removed. I double checked, and these arguments aren't listed on the [current version documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group). Can you link me to the documentation where you saw these arguments as valid?

**Comment by grimm26** [comment]
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-5-upgrade#resourceaws_elasticache_replication_group

**Comment by zubeyiro** [comment]
> Hey @zubeyiro 👋 Thank you for taking the time to raise this! It looks like the arguments you're attempting to supply are arguments that have been deprecated and subsequently removed. I double checked, and these arguments aren't listed on the [current version documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group). Can you link me to the documentation where you saw these arguments as valid, or supply debug logs (redacted as needed)?

Thanks for the reply, you are right. Search engine results somehow redirected me to older docs and thats how I ended up.
