### ISSUE TITLE
[Bug]: AWS Region set through Provider configuration not working when using AWS_ACCESS_KEY_ID env. variables in Jenkins pipeline

### ISSUE THREAD

**Issue by InderpreetSaini** [hashicorp/terraform-provider-aws#33064]
### Terraform Core Version

0.12.31

### AWS Provider Version

5.12.0

### Affected Resource(s)

 I have a  Jenkins pipeline, which is automating the creation of AWS resources and modules. Earlier it was working fine with AWS Provider version 2+, 3+. Since we have upgraded to AWS Provider version 5.12, our pipeline started failing and we got the error : 
     [ERROR] <root>: eval: *terraform.EvalConfigProvider, err: failed to get shared config profile
To counter this issue as mentioned in the link  [https://discuss.hashicorp.com/t/error-error-configuring-terraform-aws-provider-failed-to-get-shared-config-profile-default/39417](url) , we introduced a flag to handle this as per below provider config:

```
provider "aws" {
  alias   = "default"
  region  = "eu-west-1"
  profile = var.pipeline_run ? null : "myprofile"
}
```
Now we are passing the AWS credentials in the Jenkins pipeline as environment variables, but unfortunately, the AWS region is not getting picked up from the Terraform provider config as eu-west-1. We are getting the below error now when we run the pipeline in the tf apply:

`<root>: eval: *terraform.EvalConfigProvider, err: validating provider credentials: retrieving caller identity from STS: operation error STS: GetCallerIdentity, failed to resolve service endpoint, endpoint rule error, Invalid Configuration: Missing Region`  

Terraform resource that we are deploying is a module.

```
module "my-module" {
  source = "<github-link>"
  providers = {
    aws.default = aws.default
  }
}

```
The module has multiple AWS resources like a S3 bucket, aws_iam_user etc. We are not customizing/providing the provider field in any of these resources, assuming it will pick the provider aws.default automatically.
 

### Expected Behavior

Region should be picked from Terraform Provider Config even if we are specifying the AWS Secret Key and Key ID as environment variables.

### Actual Behavior

It is throwing an error that the Region has not been set.

### Terraform Configuration Files

```
provider "aws" {
  alias   = "default"
  region  = "eu-west-1"
  profile = var.pipeline_run ? null : "myprofile"
}
```

### Steps to Reproduce

1. Create a Jenkins pipeline to automate the creation of AWS resources through pipeline.
2. Provide the AWS credentials as environment variables  AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY  in the pipeline script.
3. Provide the AWS region in the Provider configuration in the Terraform file.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @InderpreetSaini 👋 Thank you for taking the time to raise this! Is the module that you're passing `aws.default` to expecting an aliased version of the provider (using the [`configuration_aliases`](https://developer.hashicorp.com/terraform/language/modules/develop/providers#provider-aliases-within-modules) argument)?

If it's not, Terraform will attempt to use the unaliased instantiation of the provider, which would fall back to the [order of precedence](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#authentication-and-configuration) for authentication configuration. Since you haven't configured a `provider "aws"` block without an alias declared (at least not in the example provided), only the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` would be picked up from the environment, and the provider would not be able to be successfully configured.

**Comment by InderpreetSaini** [comment]
Hi @justinretzolk , The child module that is being used by the root module does not have any configuration_aliases argument set.

```
terraform {
  required_version = ">= 0.12"
}
```

 If I change the module usage to below, it works fine then.

```
module "my-module" {
  source = "<github-link>"
  providers = {
    aws = aws.default
  }
}
```

**Comment by justinretzolk** [comment]
Hey @InderpreetSaini 👋 Thank you for following up and letting me know that change helped things. Am I correct in understanding that this resolves the issue, and that we can close this out?

**Comment by InderpreetSaini** [comment]
Hi @justinretzolk   Thanks for the help and I am closing this issue as resolved.
