### ISSUE TITLE
[Bug]: Terraform  AWS Autoscaling update failed due to pick historic failures in the ASG activity history

### ISSUE THREAD

**Issue by ravi-prajapati** [hashicorp/terraform-provider-aws#33062]
### Terraform Core Version

0.15.5

### AWS Provider Version

4.29.0

### Affected Resource(s)

* aws_autoscaling_group

### Expected Behavior

Just scaling the instances, So Terraform shouldn't pick failure activity from history and it shouldn't fail.

### Actual Behavior

Terraform fails out, repeating an old failure message from the ASG activity history even though AWS carries on correctly.

### Relevant Error/Panic Output Snippet

```shell
* Scaling activity (7d46253b-a802-f74f-ca1f-a9159faf70ee): Failed: Could not launch On-Demand Instances. InsufficientInstanceCapacity - We currently do not have sufficient m5n.xlarge capacity in the Availability Zone you requested (eu-central-1a). Our system will be working on provisioning additional capacity. You can currently get m5n.xlarge capacity by not specifying an Availability Zone in your request or choosing eu-central-1b, eu-central-1c. Launching EC2 instance failed.
17:29:43   	
* Scaling activity (5df6253b-a763-e77e-1718-f870bfeaf9aa): Failed: Could not launch On-Demand Instances. InsufficientInstanceCapacity - We currently do not have sufficient m5n.xlarge capacity in the Availability Zone you requested (eu-central-1a). Our system will be working on provisioning additional capacity. You can currently get m5n.xlarge capacity by not specifying an Availability Zone in your request or choosing eu-central-1b, eu-central-1c. Launching EC2 instance failed.
```

### Terraform Configuration Files

    resource "aws_autoscaling_group" "nuxeo-worker-blue" {
      count = var.WORKER_DEDICATED ? 1 : 0
      name = "${var.CUSTOMER}-${var.STACK_ENVIRONMENT_NAME}-${var.STACK_ID}-worker-blue"
      health_check_grace_period = 60
      health_check_type = "EC2"
      vpc_zone_identifier = split(",",var.PRIVATE_SUBNETS_TO_USE)
      service_linked_role_arn = var.AWS_ASG_ROLE
  
      desired_capacity = var.WORKER_BLUE_ASG_DESIRED
      max_size = var.WORKER_BLUE_ASG_MAX
      min_size = var.WORKER_BLUE_ASG_MIN
  
      mixed_instances_policy {
        instances_distribution {
          on_demand_base_capacity = var.WORKER_BLUE_ASG_MAX != 0 ? var.WORKER_ON_DEMAND_BASE_CAPACITY : 0
          on_demand_percentage_above_base_capacity = var.WORKER_ON_DEMAND_PERCENTAGE_ABOVE_BASE_CAPACITY
          spot_allocation_strategy = var.WORKER_SPOT_ALLOCATION_STRATEGY
        }
  
        launch_template {
          launch_template_specification {
            launch_template_id = aws_launch_template.nuxeo-worker-blue[count.index].id
            version = aws_launch_template.nuxeo-worker-blue[count.index].latest_version
          }
          override {
            instance_type = var.WORKER_INSTANCE_TYPE
          }
        }
      }
  
      enabled_metrics = [
        "GroupMinSize",
        "GroupMaxSize",
        "GroupDesiredCapacity",
        "GroupInServiceInstances",
        "GroupPendingInstances",
        "GroupStandbyInstances",
        "GroupTerminatingInstances",
        "GroupTotalInstances"]
  
      dynamic "tag" {
        for_each = concat(local.default_asg_tags, tolist([
          tomap({"key" = "Name", "value" = "worker-${var.STACK_NAME}-${var.STACK_ENVIRONMENT_NAME}", "propagate_at_launch" = true}),
          tomap({"key" = "deployment-type", "value" = "blue", "propagate_at_launch" = true}),
          tomap({"key" = "service", "value" = "worker", "propagate_at_launch" = true}),
          tomap({"key" = "env", "value" = var.STACK_NAME, "propagate_at_launch" = true}),
        ]))
        iterator = tags
        content {
          key = tags.value["key"]
          value = tags.value["value"]
          propagate_at_launch = tags.value["propagate_at_launch"]
        }
      }
  
  
      lifecycle {
        create_before_destroy = true
      }
    }

### Steps to Reproduce

For reproduce, need any failure on ASG activity history like unsupported instance type or any failure case then pass correct parameter and run terraform, So it will pick failure activity. 

### Debug Output

Error: waiting for Auto Scaling Group (engieaxima-preprod-283-worker-blue) capacity satisfied: 2 errors occurred:
  * Scaling activity (7d46253b-a802-f74f-ca1f-a9159faf70ee): Failed: Could not launch On-Demand Instances. InsufficientInstanceCapacity - We currently do not have sufficient m5n.xlarge capacity in the Availability Zone you requested (eu-central-1a). Our system will be working on provisioning additional capacity. You can currently get m5n.xlarge capacity by not specifying an Availability Zone in your request or choosing eu-central-1b, eu-central-1c. Launching EC2 instance failed. 
  * Scaling activity (5df6253b-a763-e77e-1718-f870bfeaf9aa): Failed: Could not launch On-Demand Instances. InsufficientInstanceCapacity - We currently do not have sufficient m5n.xlarge capacity in the Availability Zone you requested (eu-central-1a). Our system will be working on provisioning additional capacity. You can currently get m5n.xlarge capacity by not specifying an Availability Zone in your request or choosing eu-central-1b, eu-central-1c. Launching EC2 instance failed.

  with module.nuxeo.aws_autoscaling_group.nuxeo-worker-blue[0],
  on ../../modules/instance/worker.tf line 90, in resource "aws_autoscaling_group" "nuxeo-worker-blue":
  90: resource "aws_autoscaling_group" "nuxeo-worker-blue" {

### Important Factoids

Deleting the ASG fixes this error because history is removed.
We're not sure if this error will come back but we've seen it in three separate cases thus far.

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/30740.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/26377.

@ravi-prajapati Thanks for raising this issue.
This was addressed via https://github.com/hashicorp/terraform-provider-aws/pull/31551 -- you will need to upgrade to at least **v5.1.0** of the Terraform AWS provider to pick up the fix.
