### ISSUE TITLE
Terraform can add aws_s3_bucket without import on existing buckets

### ISSUE THREAD

**Issue by nocode99** [hashicorp/terraform-provider-aws#3307]
### Terraform Version
0.10.5

### Affected Resource(s)
aws_s3_bucket

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_s3_bucket" "test" {
  bucket = "test-bucket"
}
```

### Debug Output
https://gist.github.com/nocode99/bcaaabf32c2c1c43ffcb2d0d209d4f79

### Expected Behavior
When running `terraform apply` - it should validate if the bucket exists or not and error.

### Actual Behavior
Terraform "adds" the s3 bucket, but if the bucket has any extra settings (ie bucket policy), they are not overwritten, but they are not detected on subsequent plan/apply

### Steps to Reproduce
1. Have a preexisting bucket
2. Add the hcl code from above
3. Do not import the resource and just run `terraform apply`
4. The resource is "added"

### Important Factoids
I also added a Bucket Policy and used a bare aws_s3_bucket resource and it does not overwrite or detect the Bucket Policy.  This is dangerous unexpected behavior and could cause settings to be overwritten since there is no validation.

**Comment by Chhed13** [comment]
Double checked - it affects us-east-1 zone only. For the rest zones AWS return an error
```
API server listening at: 127.0.0.1:41843
	testing.go:503: Step 0 error: Error applying: 1 error(s) occurred:
		
		* aws_s3_bucket.bucket: 1 error(s) occurred:
		
		* aws_s3_bucket.bucket: Error creating S3 bucket: BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
			status code: 409, request id: 26FBE3B0F6F17C6F, host id: xxxxxxxxxxxxx=
```

Maybe that would be good to check existence on plan?

**Comment by Chhed13** [comment]
To be more precise - it affects us-east-1 provider zone only. This combination:
```
provider "aws" {
  region = "us-east-2"
}

resource "aws_s3_bucket" "test" {
    region = "us-east-1"
    bucket = "tf-test-bucket-3737801584745708147"
}
```
fails with 409 - as should on double creation

**Comment by erikpaasonen** [comment]
This behavior is documented in the AWS API in the `BucketAlreadyOwnedByYou` entry:
https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList

This is a backwards compatibility feature in the AWS API that results in either a `200 OK` or `409 Conflict` response depending on whether the region is `us-east-1` or not.

**Comment by ewbankkit** [comment]
@nocode99 Thanks for raising this issue.
It has been noticed in #13587. I'm going to close this one as a duplicate (as it has fewer upvotes, even though it's older) so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
