### ISSUE TITLE
[Bug]: aws_route53_zone_association removal

### ISSUE THREAD

**Issue by matthewchess** [hashicorp/terraform-provider-aws#33071]
### Terraform Core Version

v1.5.0

### AWS Provider Version

v5.12.0

### Affected Resource(s)

aws_route53_zone
aws_route53_vpc_association_authorization
aws_route53_zone_association

### Expected Behavior

I expect TF to create the route53 zone with the default VPC then add the vpc association for our "shared vpc". Then leave it alone.

### Actual Behavior

TF does create the resources just fine on first plan/apply but on subsequent plan/apply TF wants to remove the shared_vpc id from aws_route53_zone.private. Then once removed it adds it back on third apply and the cycle continues.

### Terraform Configuration Files

```terraform
resource "aws_route53_zone" "private" {
  name = "${var.mcomm_group_email}.awsdev.it.umich.edu"
  vpc {
    vpc_id = data.aws_vpc.default_vpc.id
  }
}

resource "aws_route53_vpc_association_authorization" "vpc_association_authorization" {
  zone_id = aws_route53_zone.private.id
  vpc_id  = data.aws_vpc.shared_vpc.id

  depends_on = [
    aws_route53_zone.private
  ]
}

resource "aws_route53_zone_association" "core_zone_association" {
  zone_id = aws_route53_zone.private.id
  vpc_id  = data.aws_vpc.shared_vpc.id
  provider = aws.core

  depends_on = [
    aws_route53_vpc_association_authorization.vpc_association_authorization
  ]
}
```

### Steps to Reproduce

Run terraform apply multiple times.

I added the depends_on blocks after but I saw the same behavior without them.

### Debug Output

[https://gist.github.com/matthewchess/bd787a95a1fb19bd84373a4df8c49c63](url)

### Important Factoids

The aws_route53_zone_association is cross account, note that it uses a provider alias aws.core. That's a diffrent aws account then the other resources.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @matthewchess 👋 Thank you for taking the time to raise this! This is a caveat that's called out in the documentation of the [`aws_route53_zone` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_zone#private-zone) with the following note:

> Terraform provides both exclusive VPC associations defined in-line in this resource via `vpc` configuration blocks and a separate [Zone VPC Association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_zone_association) resource. At this time, you cannot use in-line VPC associations in conjunction with any `aws_route53_zone_association` resources with the same zone ID otherwise it will cause a perpetual difference in plan output. You can optionally use the generic Terraform resource [lifecycle configuration block](https://www.terraform.io/docs/configuration/meta-arguments/lifecycle.html) with `ignore_changes` to manage additional associations via the `aws_route53_zone_association` resource.

Unfortunately, until this changes, for your use case, you'll need to use the `lifecycle` configuration block as mentioned in this callout.
