### ISSUE TITLE
[Enhancement]: DMS endpoint redshift-serverless support

### ISSUE THREAD

**Issue by chadmyers** [hashicorp/terraform-provider-aws#33075]
### Description

With the introduction of support for Redshift Serverless, support should be added for DMS endpoint target for engine name `redshift-serverless`.

### Affected Resource(s) and/or Data Source(s)

`aws_dms_endpoint`

### Potential Terraform Configuration

```terraform
resource "aws_dms_endpoint" "redshift" {
    endpoint_id                     = "target-my_workgroup_name"
    engine_name                     = "redshift-serverless"
    endpoint_type                   = "target"
    database_name                   = "dev"
    username                        = "dms-user"
    port                            = 5439
    ssl_mode                        = "none"
    extra_connection_attributes     = ""
    server_name                     = data.aws_redshiftserverless_workgroup.main.endpoint
}
```

### References

https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Introduction.Targets.html#CHAP_Introduction.Targets.DataMigration

### Would you like to implement a fix?

None

**Comment by mmccarthy404** [comment]
Potential fix here: https://github.com/hashicorp/terraform-provider-aws/pull/33316
