### ISSUE TITLE
[Bug]:  Error: doesn't support update on aws_lambda_layer_version

### ISSUE THREAD

**Issue by alnemo** [hashicorp/terraform-provider-aws#33081]
### Terraform Core Version

1.2.8

### AWS Provider Version

5.13

### Affected Resource(s)

aws_lambda_layer_version

### Expected Behavior

Layer is updated with new code

### Actual Behavior

Layer fails to update when deployed with provider version 5.13, same layer is deployed when provider version is forced to 5.12

### Relevant Error/Panic Output Snippet

```shell
module.api.aws_lambda_layer_version.lambda_layer_dependencies: Modifying... [id=arn:aws:lambda:us-east-1:XXXXXX:layer:lambda-dependencies:96]

Error: doesn't support update

  with module.api.aws_lambda_layer_version.lambda_layer_dependencies,
  on ../../lambda_api/lambda.tf line 5, in resource "aws_lambda_layer_version" "lambda_layer_dependencies":
   5: resource "aws_lambda_layer_version" "lambda_layer_dependencies" {
```

### Terraform Configuration Files

```terraform
resource "aws_lambda_layer_version" "lambda_layer_dependencies" {
  filename   = var.lambda_dependencies_filepath
  layer_name = "${local.project_name}-dependencies"

  compatible_runtimes = [
    "nodejs16.x"
  ]
  source_code_hash = filebase64sha256(var.lambda_dependencies_filepath)
}
```

### Steps to Reproduce

Deploy a terraform, updating an existing lambda layer to new version

### Panic Output

```shell
module.api.aws_lambda_layer_version.lambda_layer_dependencies: Modifying... [id=arn:aws:lambda:us-east-1:XXXXXX:layer:lambda-dependencies:96]

Error: doesn't support update

  with module.api.aws_lambda_layer_version.lambda_layer_dependencies,
  on ../../lambda_api/lambda.tf line 5, in resource "aws_lambda_layer_version" "lambda_layer_dependencies":
   5: resource "aws_lambda_layer_version" "lambda_layer_dependencies" {
```

### Important Factoids

Error started with provider version 5.13, same project is deployed when provider version is forced to 5.12

### Would you like to implement a fix?

None

**Comment by filol** [comment]
Indroduce by https://github.com/hashicorp/terraform-provider-aws/issues/32535

**Comment by SteffanoP** [comment]
Same problem here!

**Comment by joecolly** [comment]
Also having this issue

**Comment by nhood-nmdp** [comment]
We are also receiving this same error.

│ Error: doesn't support update
│ 
│   with aws_lambda_layer_version.this,
│   on lambda.tf line 1, in resource "aws_lambda_layer_version" "this":
│    1: resource "aws_lambda_layer_version" "this" {
