### ISSUE TITLE
[Bug]: Terraform doesn't send `ColumnIndex` and `RowIndex` fields in API call when using value 0 in `column_index` and `row_index` fields in `definition.sheets.layouts.configuration.grid_layout.format_text.elements` block in `aws_quicksight_analysis` resource, causing QuickSight to incorrectly render the element on the grid

### ISSUE THREAD

**Issue by udidn** [hashicorp/terraform-provider-aws#33108]
### Terraform Core Version

1.5.3

### AWS Provider Version

5.13.1

### Affected Resource(s)

`column_index` and `row_index` fields in `definition.sheets.layouts.configuration.grid_layout.format_text.elements` block in `aws_quicksight_analysis` resource, causing QuickSight to incorrectly render the element on the grid

### Expected Behavior

When specifying 0 as a value in `column_index` and `row_index` fields in `definition.sheets.layouts.configuration.grid_layout.format_text.elements` block in `aws_quicksight_analysis` resource, Terraform should send these fields with 0 value in create or update operations

### Actual Behavior

When specifying 0 as a value in `column_index` and `row_index` fields in `definition.sheets.layouts.configuration.grid_layout.format_text.elements` block in `aws_quicksight_analysis` resource, Terraform doesn't send these fields in create or update operations, causing QuickSight to incorrectly render the element on the grid

### Terraform Configuration Files

```terraform
resource "aws_quicksight_analysis" "test" {
  analysis_id = "test"
  name        = "test"
  theme_arn   = "arn:aws:quicksight::aws:theme/CLASSIC"

  definition {
    data_set_identifiers_declarations {
      identifier   = aws_quicksight_data_set.test.name
      data_set_arn = aws_quicksight_data_set.test.arn
    }

    sheets {
      sheet_id = "sheet-id1"
      description = "Some description"
      name = "Some Name"
      content_type = "INTERACTIVE"
      text_boxes {
        sheet_text_box_id = "textbox-id"
        content = "Some text here"
      }
      layouts {
        configuration {
          grid_layout {
            elements {
              column_index = 0
              column_span  = 36
              element_id   = "element-id1"
              element_type = "TEXT_BOX"
              row_index    = 0
              row_span     = 3
            }
          }
        }
      }
      parameter_controls {
        dropdown {
          parameter_control_id  = "control-id1"
          source_parameter_name = "TestParameter1"
          title                 = "Test Control 1"
          display_options {
            select_all_options {
              visibility = "VISIBLE"
            }
            title_options {
              visibility = "VISIBLE"
              font_configuration {
                font_size {
                  relative = "MEDIUM"
                }
              }
            }
          }
          type = "MULTI_SELECT"
          selectable_values {
            link_to_data_set_column {
              column_name         = "column1"
              data_set_identifier = aws_quicksight_data_set.test.name
            }
          }
        }
      }
      parameter_controls {
        dropdown {
          parameter_control_id  = "control-id2"
          source_parameter_name = "TestParameter2"
          title                 = "Test Control 2"
          display_options {
            select_all_options {
              visibility = "VISIBLE"
            }
            title_options {
              visibility = "VISIBLE"
              font_configuration {
                font_size {
                  relative = "MEDIUM"
                }
              }
            }
          }
          type = "MULTI_SELECT"
          selectable_values {
            link_to_data_set_column {
              column_name         = "column2"
              data_set_identifier = aws_quicksight_data_set.test.name
            }
          }
          cascading_control_configuration {
            source_controls {
              source_sheet_control_id = "control-id1"
              column_to_match {
                column_name         = "column1"
                data_set_identifier = aws_quicksight_data_set.test.name
              }
            }
          }
        }
      }
    }

    analysis_defaults {
      default_new_sheet_configuration {
        interactive_layout_configuration {
          grid {
            canvas_size_options {
              screen_canvas_size_options {
                resize_option             = "FIXED"
                optimized_view_port_width = "1600px"
              }
            }
          }
        }
        sheet_content_type = "INTERACTIVE"
      }
    }
  }
}
```

### Steps to Reproduce

Run `terraform apply` either when creating the `aws_quicksight_analysis` resource from scratch or when updating it (after adding the relevant block)

### Debug Output

After running terraform apply to create or update the `aws_quicksight_analysis` resource, you'll see the following logs (an example from an update operation):
```terraform
2023-08-20T10:53:55.812+0300 [DEBUG] provider.terraform-provider-aws_v5.13.1_x5: HTTP Request Sent: http.url=https://quicksight.us-east-1.amazonaws.com/accounts/111111111111/analyses/test net.peer.name=quicksight.us-east-1.amazonaws.com tf_req_id=<id> aws.service=QuickSight http.request.header.content_type=application/json http.request.body=
```

After the `http.request.body=` there will be the body of the QuickSight `UpdateAnalysis` API call.
Here's the relevant snippet:
```json
"Layouts":
[
    {
        "Configuration":
        {
            "GridLayout":
            {
                "Elements":
                [
                    {
                        "ColumnSpan": 36,
                        "ElementId": "element-id1",
                        "ElementType": "TEXT_BOX",
                        "RowSpan": 3
                    }
                ]
            }
        }
    }
]
```

As you can see, the `ColumnIndex` and `RowIndex` fields aren't present in the `Element` block.
They should be present, with 0 value, since this is what was specified in the Terraform configuration

### Important Factoids

I saw this issue only in the `ColumnIndex` and `RowIndex` fields, but I suppose it'll be recreated also in the `ColumnSpan` and `RawSpan` fields (but I didn't try)

### References

To prove that including the `ColumnIndex` and `RowIndex` fields with 0 value solves the issue, I executed the `UpdateAnalysis` API call using AWS CLI, providing these fields with 0 value.
I then refreshed the QuickSIght Analysis in my browser, and I saw the elements are rendered properly, as expected, in the grid

### Would you like to implement a fix?

None

**Comment by udidn** [comment]
Is there any update on this issue?
It's preventing users from creating a normal QuickSight analysis as the element is incorrectly rendered on the grid

**Comment by atlesp** [comment]
I can confirm this behavior. The rowindex I can workaround just starting everything on 1 instead of zero , but it is harder with columnindex since that will take valuable space, while for rowindex it seems Quicksight to just removes the none used space on the top

**Comment by udidn** [comment]
I couldn't work-around the issue because when setting RowIndex to 1 (or ColumnIndex, I don't remember), I got an error.
However, I found another workaround. My original layout config is below:
```terraform
layouts {
  configuration {
    grid_layout {
      elements {
        element_id   = random_uuid.qs_analysis_eks_insights_sheet_executive_summary_visual_kpi_unmounted_pvs_cost_uuid.id
        element_type = "VISUAL"
        column_index = 30
        column_span  = 6
        row_index    = 3
        row_span     = 3
      }
      elements {
        element_id   = random_uuid.qs_analysis_eks_insights_sheet_executive_summary_text_box_general_spend_and_trends_summary_uuid.id
        element_type = "TEXT_BOX"
        column_index = 0
        column_span  = 36
        row_index    = 0
        row_span     = 3
      }
    }
  }
}
```

The result of this config should be:
1. The text-box should be on the top of the grid, spanning all the way from left to right
2. The visual should be below the text-box, on the right-most side of the grid, spanning 3 rows

I confirm this is working as expected when using AWS CLI (the 0 values are sent).
With Terraform, the 0 values aren't sent, and the end result is:

1. The visual is on top, right-most side of the grid, spanning 3 rows
2. The text-box is below it, spanning all the way from left to right

The workaround I found is:

1. Swap the order in the Terraform config file, so that the text-box element will be first and the visual element second
2. Change the `row_index` of the visual to 0 (which means that Terraform won't sent it)

Config below:
```terraform
layouts {
  configuration {
    grid_layout {
      elements {
        element_id   = random_uuid.qs_analysis_eks_insights_sheet_executive_summary_text_box_general_spend_and_trends_summary_uuid.id
        element_type = "TEXT_BOX"
        column_index = 0
        column_span  = 36
        row_index    = 0
        row_span     = 3
      }
      elements {
        element_id   = random_uuid.qs_analysis_eks_insights_sheet_executive_summary_visual_kpi_unmounted_pvs_cost_uuid.id
        element_type = "VISUAL"
        column_index = 30
        column_span  = 6
        row_index    = 0
        row_span     = 3
      }
    }
  }
}
```

The result is:
1. The text-box is on the top of the grid, spanning all the way from left to right
2. The visual is below the text-box, on the left-most side of the grid, spanning 3 rows

I confirm it behaves the same when I use AWS CLI and in the JSON, I remove the fields that were 0 in Terraform.
The only problem with this workaround is that the visual, for some reason, is placed in the left-most side.
This is although the `column_index` is 30, which should place it on the right-most side.
It looks like when not including the `row_index`, QuickSight just throws the visual to the left-most part for some reason.
The problem here is when I add another visual with `column_index` of 24, it's placed to the right of the previous visual.
I'd expect it would be placed to the left of the visual that has `column_index` of 30, and then eventually as I add visuals that fill the row completely, they'll be ordered as expected.
But this is not the case, and to get to the correct ordering as I intend (when not sending `row_index`), I need to reverse the `column_index` numbers of my visuals, which makes this workaround quite complex.

If anyone is aware of another workaround, I'd be happy to hear

**Comment by udidn** [comment]
Can someone please prioritize this issue?
It should be fixed so that when 0 is used in one of those fields, it is sent in the API call body.
Without this, the visuals in the grid are shifted, and working-around this issue becomes quite complex

**Comment by udidn** [comment]
@atlesp, your workaround works (starting from 1), I just misunderstood initially.
Here's my working configuration:

```terraform
layouts {
  configuration {
    grid_layout {
      elements {
        element_id   = random_uuid.qs_analysis_eks_insights_sheet_executive_summary_text_box_general_spend_and_trends_summary_uuid.id
        element_type = "TEXT_BOX"
        column_index = 1
        column_span  = 35
        row_index    = 1
        row_span     = 3
      }
      elements {
        element_id   = random_uuid.qs_analysis_eks_insights_sheet_executive_summary_visual_kpi_unmounted_pvs_cost_uuid.id
        element_type = "VISUAL"
        column_index = 30
        column_span  = 6
        row_index    = 4
        row_span     = 3
      }
    }
  }
}
```

I see what you mean with the `column_index` issue, there's a small part of the canvas left without any visual in it.
I think I can work with this as a workaround. Thank you for the help!

Still, can someone please prioritize this issue?
