### ISSUE TITLE
[Bug]: Terraform Removes S3 Bucket Grant Permissions Without Code Changes

### ISSUE THREAD

**Issue by dnlchen** [hashicorp/terraform-provider-aws#33100]
### Terraform Core Version

1.2.9

### AWS Provider Version

3.76.1

### Affected Resource(s)

aws_s3_bucket

### Expected Behavior

no change

### Actual Behavior

```shell
      - grant {
          - permissions = [
              - "READ_ACP",
              - "WRITE",
            ] -> null
          - type        = "Group" -> null
          - uri         = "http://acs.amazonaws.com/groups/s3/LogDelivery" -> null
        }
      - grant {
          - id          = "0b05843ef4f7ad23454352435ggwergwerrebd5ebfger3425243gfgh" -> null
          - permissions = [
              - "FULL_CONTROL",
            ] -> null
          - type        = "CanonicalUser" -> null
        }
```

### Terraform Configuration Files

```terraform
resource "aws_s3_bucket" "log_bucket" {
  bucket = "${var.env_prefix}${var.env}-${var.service}.${var.domain}-log"

  logging {
    target_bucket = var.s3_access_logs_bucket_name
    target_prefix = "${var.env_prefix}${var.env}-${var.service}.${var.domain}-log/"
  }

  lifecycle_rule {
    id                                     = "CleanupIncompleteMultiPartUploadsAndExpiredObjectDeleteMarkers"
    enabled                                = true
    abort_incomplete_multipart_upload_days = 7

    expiration {
      expired_object_delete_marker = true
    }
  }
}

resource "aws_s3_bucket_ownership_controls" "log_bucket" {
  bucket = aws_s3_bucket.log_bucket.id
  rule {
    object_ownership = "BucketOwnerPreferred"
  }
}

resource "aws_s3_bucket_acl" "log_bucket" {
  depends_on = [aws_s3_bucket_ownership_controls.log_bucket]

  bucket = aws_s3_bucket.log_bucket.id
  acl    = "log-delivery-write"
}
```

### Steps to Reproduce

The bucket was created a while ago and there was no change.
However the Terraform run showed that some grant permissions would be removed.
Was this change by AWS or TF?

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @dnlchen 👋 Thank you for taking the time to raise this! There have been some somewhat recent changes on the AWS side with regards to bucket permissions (see #28353 for some more information), but I'm unsure if that's what we're seeing here. Are you able to provide debug logs (redacted as needed)?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
