### ISSUE TITLE
[Bug]: AWS quicksight dataset create, row level permission - Namespace parameter should not be specified for Version 2”. 

### ISSUE THREAD

**Issue by sandeepagrawal921** [hashicorp/terraform-provider-aws#33114]
### Terraform Core Version

1.5.5

### AWS Provider Version

5.12.0

### Affected Resource(s)

aws_quicksight_data_set

### Expected Behavior

Should be able to create "aws_quicksight_data_set" with "row_level_permission_data_set" settings.

### Actual Behavior

Error: failed to create QuickSight Data Set - Invalid RowLevelPermissionDataSet. 
Namespace parameter should not be specified for Version 2

### Relevant Error/Panic Output Snippet

```shell
Error: creating QuickSight Data Set: InvalidParameterValueException: Invalid RowLevelPermissionDataSet. Namespace parameter should not be specified for Version 2
│ {
│ RespMetadata: {
│ StatusCode: 400,
│ RequestID: “6864473b-9f92-43a7-b1ba-0629e5fda088”
│ },
│ Message_: “Invalid RowLevelPermissionDataSet. Namespace parameter should not be specified for Version 2”
```

### Steps to Reproduce

Code snippet - 
Under the `aws_quicksight_data_set` resource, added below row_level_permission_settings :- 

  row_level_permission_data_set {
    arn               = aws_quicksight_data_set.create_usergroup_permission_dataset[0].arn
    format_version    = "VERSION_2"
    permission_policy = local.eq_analytics_grant_access_permission_policy
    status            = "ENABLED"
  }

### Debug Output

```shell
Error: creating QuickSight Data Set: InvalidParameterValueException: Invalid RowLevelPermissionDataSet. Namespace parameter should not be specified for Version 2
│ {
│ RespMetadata: {
│ StatusCode: 400,
│ RequestID: “6864473b-9f92-43a7-b1ba-0629e5fda088”
│ },
│ Message_: “Invalid RowLevelPermissionDataSet. Namespace parameter should not be specified for Version 2”
```

### Would you like to implement a fix?

**Comment by sandeepagrawal921** [comment]
Hi, 

want this to look into on priority, please.

**Comment by adona9** [comment]
It seems like this would be an easy fix. The AWS CLI man page for `quicksight create-data-set` states:

```
FormatVersion -> (string)
              The  user  or  group rules associated with the dataset that con-
              tains permissions for RLS.

              By default, FormatVersion is VERSION_1 . When  FormatVersion  is
              VERSION_1 , UserName and GroupName are required. When FormatVer-
              sion is VERSION_2 , UserARN and GroupARN are required, and Name-
              space must not exist.
```

**Comment by madhavnitw84** [comment]
hi, can you prioritize this please. we are also affected by this

**Comment by Dojchinovska** [comment]
Any update on this?

**Comment by mitchbregs** [comment]
bump. any updates?

**Comment by parsable-alex-antonison** [comment]
Bump - any updates?

**Comment by gardiantnikhil** [comment]
Seems that if you use version_1 it works fine but version_2 doesnt work

**Comment by gardiantnikhil** [comment]
What is the work around you guys are using for this ?

**Comment by parsable-alex-antonison** [comment]
We are using a CloudFormation stack resource within Terraform. Not a huge fan because it requires the dataset to complete a load (we are using SPICE which for our largest one can take hours) and for some of our larger datasets, we are currently running into timeout issues.

If it wouldn't be a huge headache to migrate all of the datasets we have deployed this way, I would instead just manage via boto3 Quicksight since CloudFormation has been such a headache to triage and get going and hope that eventually this bug gets fixed so we can do it all in terraform.

For a side project of mine that doesn't require RLS, terraform works like a champ at managing my datasets.
