### ISSUE TITLE
[Enhancement]: Gaurdduty support of eks runtime

### ISSUE THREAD

**Issue by surajtikoo** [hashicorp/terraform-provider-aws#33134]
### Description

Amazon has recently introduced support for the EKS runtime. However, as of now, Terraform does not include support for this new feature. Could you please incorporate this module into the available resources?

### Affected Resource(s) and/or Data Source(s)

resource "aws_organizations_organization" "example" {
  aws_service_access_principals = ["guardduty.amazonaws.com"]
}

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @surajtikoo 👋 I'm not sure I follow exactly what change you're referencing, but on a quick glance, there's no [validation rules](https://github.com/hashicorp/terraform-provider-aws/blob/742b90826aa4f5b92aa84c64db74bee556ba59dd/internal/service/organizations/organization.go#L79-L83) for the argument that you referenced in your example, so I wouldn't expect this to be something we need to make a change to support.

Are you getting errors when trying to use this configuration, and if so, can you supply debug logs (redacted as needed)?

**Comment by surajtikoo** [comment]
@justinretzolk  Thanks for your quick response. I didn't find anything in the documentation. I am refering to this ticket.
https://github.com/hashicorp/terraform-provider-aws/issues/32949

**Comment by justinretzolk** [comment]
Hey @surajtikoo, that's helpful! Just to confirm, are you looking for the same functionality that was mentioned in #32949? If so, we'll want to close this one as a duplicate so that we can keep any additional discussion in one place. I'll wait to hear back before doing so, in case I've misunderstood! 🙂

**Comment by surajtikoo** [comment]
Yes right @justinretzolk .You can close this ticket we can track the other one. By any chance do you know is anyone working on it?

**Comment by justinretzolk** [comment]
Thanks for confirming @surajtikoo 👍. It doesn't look like this one has been picked up be our team yet, and I don't see any community contributions for it just yet. I'll go ahead and close this issue out; further updates can be found on #32949.
