### ISSUE TITLE
[Enhancement]: Add OpenTableFormatInput to AWS Glue Catalog Tables

### ISSUE THREAD

**Issue by okelet** [hashicorp/terraform-provider-aws#33157]
### Description

According to this blog post <https://aws.amazon.com/blogs/big-data/introducing-aws-glue-crawler-and-create-table-support-for-apache-iceberg-format/>, and this API documentation <https://docs.aws.amazon.com/glue/latest/webapi/API_CreateTable.html> there is a new option to initialize Iceberg tables. This new option should be implemented in the `aws_glue_catalog_table` resource.

### Affected Resource(s) and/or Data Source(s)

* aws_glue_catalog_table

### Would you like to implement a fix?

None

**Comment by younggawthorpe-nowpensions** [comment]
Hello, 
I am going to pick up this issue
