### ISSUE TITLE
[Docs]: Missing information about ssmcontacts_plan

### ISSUE THREAD

**Issue by yaroslav-nakonechnikov** [hashicorp/terraform-provider-aws#33174]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssmcontacts_plan

### Description

on published docs there are nothing about using notification channel. 
but i managed to find it in sources: 
https://github.com/hashicorp/terraform-provider-aws/blob/v5.13.1/internal/service/ssmcontacts/plan.go#L59C1-L60C1

and it helped me to create setting
```
target {
      channel_target_info {
        retry_interval_in_minutes = 2
        contact_channel_id        = aws_ssmcontacts_contact_channel.channel.arn
      }
    }
``` 
which is adding missing piece to be able to trigger calls. 

### References

https://discuss.hashicorp.com/t/ssm-incident-manager-doesnt-create-engament-plan-hence-no-call-triggered/57579

### Would you like to implement a fix?

No

**Comment by xyq175com** [comment]
Thank you for raise this, I will work on this and drop a PR later
