### ISSUE TITLE
[Enhancement]: aws_ec2_network_insights_path update to support path destinations same as aws console

### ISSUE THREAD

**Issue by robwdux** [hashicorp/terraform-provider-aws#33182]
### Description

> [destination](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_network_insights_path#destination) - (Required) ID or ARN of the resource which is the source of the path. Can be an Instance, Internet Gateway, Network Interface, Transit Gateway, VPC Endpoint, VPC Peering Connection or VPN Gateway. If the resource is in another account, you must specify an ARN.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_network_insights_path

Update to add current options available through AWS Console.

<img width="270" alt="Screenshot 2023-08-24 at 8 28 22 PM" src="https://github.com/hashicorp/terraform-provider-aws/assets/12086641/50dd69ed-2271-4d37-b6f1-63ef3f4354d0">

Testing internet access is not quite possible especially when using AWS Network Firewall, you are forced to configure GWLB endpoint and do not capture a full network path with intermediates as can be done in AWS Console.

### Affected Resource(s) and/or Data Source(s)

aws_ec2_network_insights_path

### Potential Terraform Configuration

```terraform
resource "aws_ec2_network_insights_path" "internet_access" {
  source           = aws_network_interface.ra_pvt_subnet.id
  destination_ip   = "1.1.1.1"
  destination_port = 443
  protocol         = "tcp"
}
```

### Would you like to implement a fix?

None

**Comment by robwdux** [comment]
API seems to be the issue here.

The API does not require destination however Terraform marks are required. Maybe resolution is to make it optional so one could simply specify destination_ip and destination_port in lieu of a destination as resource id / arn.

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateNetworkInsightsPath.html

**Comment by abhinavgrover15** [comment]
In latest version, still all the destination options are not provided. Is there any ETA on this.

**Comment by michal-kosinski** [comment]
After defining those parameters in the aws_ec2_network_insights_path  resource:

sources
destination_ip
destination_port
protocol

an error appears:

`Error: creating EC2 Network Insights Path: operation error EC2: CreateNetworkInsightsPath, https response error StatusCode: 400, RequestID: c3096b6d-5547-4629-bd38-741f0da76c85, api error MissingParameter: The request must include either the Destination parameter or the FilterAtSource.DestinationAddress parameter. Add the required parameter and retry the request.
`

anyone got a similar error? Does anything else need to be changed? Seems that FilterAtSource.DestinationAddress parameter cannot be added within aws_ec2_network_insights_path resource.

**Comment by JonathanPartain** [comment]
@michal-kosinski I am getting the same error as well.

**Comment by michal-kosinski** [comment]
@JonathanPartain thanks for the confirmation, reported as #38132
