### ISSUE TITLE
[New Resource]: aws rds modify-certificates 

### ISSUE THREAD

**Issue by jrobison-sb** [hashicorp/terraform-provider-aws#33196]
### Description

As of this writing on August 27, 2023, the default RDS CA certificate is `rds-ca-2019`, which expires 2024-08-22. If a user creates a new RDS instance anytime prior to 2024-08-22, and they don't explicitly request a different CA certificate via the `aws_rds_instance.foo.ca_cert_identifier` attribute, then presumably their instance will get this `rds-ca-2019` certificate.

AWS has an API for `aws rds modify-certificates`, which lets you override the account-level default for new RDS instances. It would be useful if Terraform had a resource which supported this API.

If such a resource existed, a person could upgrade all their existing RDS instances to a newer and longer-duration certificate (using the `aws_rds_instance.foo.ca_cert_identifier` attribute), and then use this resource to set the account-level default for new instances so that they no longer have to worry about the old certificate ever being used again.

### Requested Resource(s) and/or Data Source(s)

* `aws_rds_account_default_ca_certficate` (or something along those lines)

### Potential Terraform Configuration

```terraform
resource "aws_rds_account_default_ca_certficate" "account_default" {
  certificate-identifier = "rds-ca-rsa2048-g1"
}
```

### References

https://docs.aws.amazon.com/cli/latest/reference/rds/modify-certificates.html

https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyCertificates.html

### Would you like to implement a fix?

No

**Comment by obounaim** [comment]
Hi, I have PR opened for this new resource here : https://github.com/hashicorp/terraform-provider-aws/pull/35003
