### ISSUE TITLE
[Bug]: file_system_administrators_group causes recreation of the resource

### ISSUE THREAD

**Issue by varunrai** [hashicorp/terraform-provider-aws#33199]
### Terraform Core Version

1.4.5

### AWS Provider Version

5.12.0

### Affected Resource(s)

* aws_fsx_ontap_storage_virtual_machine

### Expected Behavior

Recreate should not happen

### Actual Behavior

Creating an SVM with Active Directory configuration and specifying the property "file_system_administrators_group" causes the subsequent apply operation to re-create the SVM.

### Terraform Configuration Files

```terraform
resource "aws_fsx_ontap_storage_virtual_machine" "fsxsvm1" {
  file_system_id             = aws_fsx_ontap_file_system.fsx_ontap_fs.id
  name                       = "svm01"
  root_volume_security_style = var.fsxn_volume_security_style
  svm_admin_password         = var.fsxn_password

  "active_directory_configuration" {
      netbios_name = "FSXN-SVM1"
      self_managed_active_directory_configuration {
        domain_name                            = var.ad_domain_name
        dns_ips                                = var.ad_dns_ips
        file_system_administrators_group       = var.ad_administrators_group
        organizational_unit_distinguished_name = var.ad_ou
        username                               = var.ad_service_account
        password                               = var.ad_service_account_password
    }
  }
}
```

### Steps to Reproduce

- Create a new security group in Active Directory or use an existing group other than "Domain Admins".
- Create a new SVM with Active Directory configuration (specify - file_system_administrators_group)
- Apply the configuration

- On the next "Apply", the SVM will be detected as a change thus triggering a replacement.

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Similar: https://github.com/hashicorp/terraform-provider-aws/issues/23314.
