### ISSUE TITLE
[Enhancement]: Ability to update SVM active directory configuration

### ISSUE THREAD

**Issue by varunrai** [hashicorp/terraform-provider-aws#33198]
### Description

Currently, once the SVM has been created there is no way to update the configuration to join the Active Directory or if Active Directory configuration change is needed.

**Scenario**: Create an SVM without joining the domain. Subsequently add the configuration in terraform code to include AD configuration. 

**Current Behaviour**: This triggers a re-creation of the volumes and SVM.
**Expected Behaviour**: SVM should not be replaced. Instead the relevant API to be called in AWS to update the configuration.

### Affected Resource(s) and/or Data Source(s)

aws_fsx_ontap_storage_virtual_machine

### References

There was a recent enhancement to the AWS SDK and also Management Console to include the ability for updating the AD configuration.

The AWS SDK was updated to include the SVM AD configuration update.
[API_UpdateSvmActiveDirectoryConfiguration](https://docs.aws.amazon.com/fsx/latest/APIReference/API_UpdateSvmActiveDirectoryConfiguration.html)

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Related #33199
