### ISSUE TITLE
[Bug]: Applying Terraform plans use incorrect provider when destroying IAM resources

### ISSUE THREAD

**Issue by jbuckley057** [hashicorp/terraform-provider-aws#33207]
### Terraform Core Version

v1.5.0

### AWS Provider Version

v5.14.0

### Affected Resource(s)

IAM resources

### Expected Behavior

When running `terraform plan -destroy -out destroy.plan` and `terraform apply "destroy.plan"` the IAM resources are destroyed.

### Actual Behavior

IAM policy and role fails to be destroyed, as it is making the api calls using credentials for Account_1 and not role credentials for Account_2 that contain the resources

`│ Error: deleting IAM Role (test-role): reading IAM Policies attached to Role (test-role): couldn't find resource`

Even worse is if there is a matching role name is found in Account_1, that role will be destroyed instead of the role in Account_2

### Relevant Error/Panic Output Snippet

```shell
$ terraform apply "destroy.plan"
module.test_role.aws_iam_role_policy_attachment.read_access[0]: Destroying... [id=test-role-20230828181825774900000001]
module.test_role.aws_iam_role_policy_attachment.read_access[0]: Destruction complete after 1s
module.test_role.aws_iam_role.this[0]: Destroying... [id=test-role]
╷
│ Error: deleting IAM Role (test-role): reading IAM Policies attached to Role (test-role): couldn't find resource
│ 
│ 
╵
```

### Terraform Configuration Files

```terraform
#main.tf
module "test_role" {
  source = "./modules/account-roles"

  role_names = [
    "test-role"
  ]
  allowed_principals = ["arn:aws:iam::111111111111:root"]

  providers = {
    aws = aws.account_2
  }
}

provider "aws" {
  alias  = "account_2"
  region = "us-east-1"

  assume_role {
    role_arn = "arn:aws:iam::222222222222:role/DelegatedRole"
  }
}
```

```terraform
#modules/account-roles/main.tf
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

data "aws_iam_policy_document" "assume_role" {
  statement {
    sid = "1"
    actions = [
      "sts:AssumeRole"
    ]
    principals {
      type        = "AWS"
      identifiers = var.allowed_principals
    }
  }
}

resource "aws_iam_role" "this" {
  count = length(var.role_names)

  name = var.role_names[count.index]

  assume_role_policy   = data.aws_iam_policy_document.assume_role.json
  max_session_duration = "21600"
}

resource "aws_iam_role_policy_attachment" "read_access" {
  count = length(var.role_names)

  role       = aws_iam_role.this[count.index].id
  policy_arn = "arn:aws:iam::aws:policy/ReadOnlyAccess"
}

variable "role_names" {
  type        = list(any)
  description = "A list of roles to create that can be assumed by any of the provided allowed_aws_principals"
}

variable "allowed_principals" {
  type        = list(any)
  description = "AWS principals allowed to assume the role created with the provided role_name"
}
```

### Steps to Reproduce

1. Log into a role in Account_1 that has access to deploy to Account_2
2. terraform init
3. terraform apply
4. terraform plan -destroy -out destroy.plan
5. terraform apply "destroy.plan"

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @jbuckley057 👋 Thank you for taking the time to raise this! Are you able to supply debug logs (redacted as needed)?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
