### ISSUE TITLE
[Enhancement]: aws_imagebuilder_image

### ISSUE THREAD

**Issue by raghavanrrs** [hashicorp/terraform-provider-aws#33213]
### Description

Enhancement to existing resource aws_imagebuilder_image

Would like to have an option to enable image scanning argument ref.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/imagebuilder_image

boto3 and aws cli api currently supports the arguments config.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/imagebuilder/client/create_image.html

### Affected Resource(s) and/or Data Source(s)

aws_imagebuilder_image

### Potential Terraform Configuration

```terraform
resource "aws_imagebuilder_image" "example" {
  distribution_configuration_arn   = aws_imagebuilder_distribution_configuration.example.arn
  image_recipe_arn                 = aws_imagebuilder_image_recipe.example.arn
  infrastructure_configuration_arn = aws_imagebuilder_infrastructure_configuration.example.arn
  imageScanningConfiguration {
    imageScanningEnabled = <bool>
    ecrConfiguration {
     repositoryName = <string> "my-ecr-repo"
     containerTags = <list(string)> ["string1", "string2", "string3"]
    }
  }

}
```

### References

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/imagebuilder/client/create_image.html

### Would you like to implement a fix?

None

**Comment by DanielRieske** [comment]
Seems like a great issue to pick up, i'll gladly pick this up and will add the PR shortly.
