### ISSUE TITLE
OpenTF support

### ISSUE THREAD

**Issue by skyzyx** [hashicorp/terraform-provider-aws#33224]
### Description

https://opentf.org/announcement

We want to understand how this provider is affected by the OpenTF announcement, and what the plans for support are moving forward.

### Would you like to implement a fix?

None

**Comment by bschaatsbergen** [comment]
The providers would not be affected by OpenTF's fork.

See the FAQ in the link you've shared.

> Will OpenTF work with all the providers and modules Terraform works with?
> Yes

**Comment by skyzyx** [comment]
Thank you for your answer.

From a technical perspective, I expect that it will be a no-op for the time being as OpenTF anticipates maintaining compat/interop for the foreseeable future. (However, OpenTF has stated that _some_ functionality may be added to OpenTF that is a _superset_ of what's in base Terraform. [[source](https://github.com/opentffoundation/roadmap/issues/24)])

From a process perspective:

1. If there is a bug in OpenTF that does not exist in Terraform (or vice-versa), will bug reports (as they pertain to this project) be treated equally on both platforms?

1. Will testing be performed with code targeting both platforms?

1. For OpenTF's potential future "superset" functionality, will that be treated as a first-class citizen?

**Comment by skyzyx** [comment]
I understand that this project exists under the `https://github.com/hashicorp` org. But I don't know how contributions are managed or decided-upon. Hence the questions. :)

**Comment by justinretzolk** [comment]
Hey @skyzyx 👋 Thank you for taking the time to raise this, and for your interest in the Terraform ecosystem. HashiCorp continues to support the AWS provider, there is no change to our support and development plans.
