### ISSUE TITLE
[Bug]: cloudwatch_role_arn is null when importing aws_api_gateway_account

### ISSUE THREAD

**Issue by habuchin** [hashicorp/terraform-provider-aws#33236]
### Terraform Core Version

1.5.6

### AWS Provider Version

5.14.0

### Affected Resource(s)

* aws_api_gateway_account

### Expected Behavior

When `terraform import aws_api_gateway_account.this api-gateway-account` is executed, the cloudwatch_role_arn should import the actual value.

### Actual Behavior

When running `terraform import aws_api_gateway_account.this api-gateway-account` with cloudwatch_role_arn set on AWS, the value is always null.

### Terraform Configuration Files

```
import {
  to = aws_api_gateway_account.this
  id = "api-gateway-account"
}
```

### Steps to Reproduce

Executing `terraform plan -generate-config-out=generated.tf` will generate the following resource.

```
resource "aws_api_gateway_account" "sendgrid_event" {
  cloudwatch_role_arn = null
}
```

Normally, the configured Role ARN should be specified.

### References

https://registry.terraform.io/providers/-/aws/latest/docs/resources/api_gateway_account#cloudwatch_role_arn

### Would you like to implement a fix?

None

**Comment by DrFaust92** [comment]
taking a look

**Comment by DrFaust92** [comment]
able to reproduce and tested a fix, will open a PR shortly
