### ISSUE TITLE
[Enhancement]: aws_instance must support new instance types, e.g. m/r7i(z,-flex), etc

### ISSUE THREAD

**Issue by sahsz123** [hashicorp/terraform-provider-aws#33247]
### Description

Terraform fails on validation on the instance type when I try to use m7i/r7iz instance types

### Affected Resource(s) and/or Data Source(s)

aws_instance

### Potential Terraform Configuration

Using the default configuration providing the instance type should work just fine.

### References

None

### Would you like to implement a fix?

None

**Comment by jar-b** [comment]
Hi @sahsz123 👋 - Can you provide more details on the error you're receiving? A minimal Terraform configuration and the output of `terraform apply` would be most helpful.

The AWS provider does not do plan time validation on the `instance_type` argument (other than checking that `launch_configuration` is not also set), so it's possible this is an error from the upstream AWS API being propagated back. 

https://github.com/hashicorp/terraform-provider-aws/blob/9e31aac25af2fc8a41aad766c3e3db43285cae2a/internal/service/ec2/ec2_instance.go#L461-L466

Given the popularity of this issue (37 votes at the time of this comment), we'd like assist however we can, but require more context to start investigating.

**Comment by jar-b** [comment]
Since we have not received any responses, we'll be closing this issue today.

If you experience an issue you believe is related to this one, please open a new issue with a minimal configuration and include this issue in the references section. Thanks!
