### ISSUE TITLE
[Bug]: required "provisioning_artifact_parameters" in aws_servicecatalog_product blocks imports

### ISSUE THREAD

**Issue by tobias-nawa** [hashicorp/terraform-provider-aws#33253]
### Terraform Core Version

v1.5.4

### AWS Provider Version

v5.14.0

### Affected Resource(s)

* aws_servicecatalog_product

### Expected Behavior

provisioning_artifact_parameters should **not** be required, when using aws_servicecatalog_provisioning_artifact (which have been imported from existing infra).

### Actual Behavior

Since provisioning_artifact_parameters is required it forces a replacement of the product. 
The product cannot be replaced since it's in use.
I created the product through cloudformation, where provisioning_artifact_parameters is an array. This way I was able to create multiple versions/artifacts. This is not possible in Terraform. Therefore I used multiple aws_servicecatalog_provisioning_artifact and imported each from existing infra. Therefore I don't need provisioning_artifact_parameters in the product. But since it's required I need to fill in something, which triggers a replacement. This is blocking me now.

A little more detail:
Before import I had the product and several artifacts. I cannot add several artifacts in provisioning_artifact_parameters. Therefore I'm using aws_servicecatalog_provisioning_artifact to proper import the artifacts. In this case I don't need the provisioning_artifact_parameters on the product. Therefore I think it should not be required.

After importing the product and the several aws_servicecatalog_provisioning_artifact, terraform fails since the product is in use by many accounts through control tower blueprints and cannot be replaced. Now I'm stuck in a deadlock.
Resolution would be that I'm not forced to add something to provisioning_artifact_parameters.

Here is the plan output from the imported product:

```
  # aws_servicecatalog_product.basic_blueprint must be replaced
-/+ resource "aws_servicecatalog_product" "basic_blueprint" {
      + accept_language     = "en"
      ~ arn                 = "arn:aws:catalog:eu-central-1:123456:product/prod-abc" -> (known after apply)
      ~ created_time        = "2023-08-04T12:20:46Z" -> (known after apply)
      + description         = (known after apply)
      + distributor         = (known after apply)
      ~ has_default_path    = false -> (known after apply)
      ~ id                  = "prod-abcd" -> (known after apply)
        name                = "Landingzone Blueprint"
      ~ status              = "CREATED" -> (known after apply)
      + support_description = (known after apply)
      + support_email       = (known after apply)
      + support_url         = (known after apply)
      - tags                = {} -> null
      ~ tags_all            = {
          + "CreatedBy"   = "Terraform"
          + "Environment" = "production"
        }
        # (2 unchanged attributes hidden)

      + provisioning_artifact_parameters { # forces replacement
          + description                 = "Basic account setup." # forces replacement
          + disable_template_validation = false # forces replacement
          + name                        = "BASIC" # forces replacement
          + template_url                = "https://abcd.s3.eu-central-1.amazonaws.com/basic.json" # forces replacement
          + type                        = "CLOUD_FORMATION_TEMPLATE" # forces replacement
        }
    }
```

I'm using multiple aws_servicecatalog_provisioning_artifact. So why do I need to specify the provisioning_artifact_parameters on the product which can only hold one artifact?

```
resource "aws_servicecatalog_provisioning_artifact" "basic_0_2_0" {
  name         = "BASIC 0.2.0"
  description  = "Basic account setup."
  product_id   = aws_servicecatalog_product.basic_blueprint.id
  type         = "CLOUD_FORMATION_TEMPLATE"
  template_url = "https://abcd.s3.eu-central-1.amazonaws.com/basic_0_2_0.json"
}

resource "aws_servicecatalog_provisioning_artifact" "basic_0_2_1" {
  name         = "BASIC 0.2.1"
  description  = "Basic account setup."
  product_id   = aws_servicecatalog_product.basic_blueprint.id
  type         = "CLOUD_FORMATION_TEMPLATE"
  template_url = "https://abcd.s3.eu-central-1.amazonaws.com/basic_0_2_1.json"
}
```

Just for information here is the cloudformation template I used to create the resources:
```
"LandingzoneBlueprintProduct" : {
  "Type" : "AWS::ServiceCatalog::CloudFormationProduct",
  "Properties": {
    "Name": "Landingzone Blueprint",
    "Owner": "Tobias Nawa",
    "ProvisioningArtifactParameters": [
      {
        "Name": "BASIC 0.2.0",
        "Description": "Basic account setup.",
        "Info" : {
          "LoadTemplateFromURL" : { "Ref": "BasicTemplateUrlParameter020" }
        },
        "Type": "CLOUD_FORMATION_TEMPLATE"
      },
      {
        "Name": "BASIC 0.2.1",
        "Description": "Basic account setup.",
        "Info" : {
          "LoadTemplateFromURL" : { "Ref": "BasicTemplateUrlParameter021" }
        },
        "Type": "CLOUD_FORMATION_TEMPLATE"
      },
    ]
  }
},
```

### Terraform Configuration Files

not needed. it's a basic issue.

### Steps to Reproduce

- create service catalog portfolio, product and multiple artifacts in the console
- roll them out so they are in use (which blocks product replacement)
- import them to terraform
- run plan

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
