### ISSUE TITLE
[Enhancement]: default size of the volume attached to cloud9 instance

### ISSUE THREAD

**Issue by sseoussama** [hashicorp/terraform-provider-aws#33256]
### Description

Hello,

i want to change  the size of the volume attached to cloud9 instance (default value: 10GB), and i can't see how can i achieve that

thanks in advance  

### Affected Resource(s) and/or Data Source(s)

resource "aws_cloud9_environment_ec2" "example" {
  instance_type = "t2.micro"
  name          = "example-env"
}

### Would you like to implement a fix?

None

**Comment by DrFaust92** [comment]
This doesnt seem to be supported by api

**Comment by justinretzolk** [comment]
Given this isn't supported by the API, I'm going to close this. If that changes in the future, we'd be happy to take another look.
