### ISSUE TITLE
[Enhancement]: default_tags from environment variables

### ISSUE THREAD

**Issue by jtdoepke** [hashicorp/terraform-provider-aws#33255]
### Description

I would like to be able to configure the `default_tags` of the AWS provider using environment variables.

This would be useful, for example, in Terraform Cloud/Enterprise. If I have a bunch of workspaces organized under a project, I could attach a variable set to the project with an environment variable that would configure a tag like `Owner=my-team` across the entire set of AWS resources under that project.

### Affected Resource(s) and/or Data Source(s)

* aws provider

### Potential Terraform Configuration

```terraform
# Read default_tags from environment variables like:
# TF_AWS_DEFAULT_TAGS_<tag_name>=<tag_value>

provider "aws" {
  # Suppose the following environment variables are set:
  # TF_AWS_DEFAULT_TAGS_Owner=my-team
  # TF_AWS_DEFAULT_TAGS_Application=my-app

  default_tags {
    tags = {
      Application = "foobar" # Explicit configuration should override the env vars.
    }
  }

  # The resulting tags map should be `{ Owner = "my-team", Application = "foobar" }`.
}
```

### References

Pull request to implement this change: https://github.com/hashicorp/terraform-provider-aws/pull/33339

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @jtdoepke 👋 Thank you for taking the time to raise this, and for opening a pull request to implement it! I'll let the team go through their normal review process, but wanted to mention a workaround in the meantime. Terraform has the capability of loading values for variables by reading environment variables [prefixed with `TF_VAR_name`](https://developer.hashicorp.com/terraform/cli/config/environment-variables#tf_var_name). Leveraging that and [`merge()`](https://developer.hashicorp.com/terraform/language/functions/merge), you can achieve a nearly identical result:

```terraform
provider "aws" {
  default_tags {
    # with merge(), if the same key exists in both maps, the later one takes precedence
    tags = merge(var.default_tags, var.additional_default_tags)
  }
}

variable "default_tags" {
  description = "A map where the key is Environment and the value is the environment. Should be read from the environment and not passed directly."
  type = map
  default = null
}

variable "additional_default_tags" {
  description = "A map of tag names to tag values"
  type = map
  default = null
}

resource "aws_s3_bucket" "test" {
  bucket = "test"
}

output "tags" {
  value = aws_s3_bucket.test.tags_all
}
```

With this `terraform.tfvars`: 

```terraform
additional_default_tags = { Terraform = true, Environment = "prod" }
```

The following output occurs (note the override of `Environment`:

```shell
$ TF_VAR_default_tags='{ Environment = "dev" }' terraform plan
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_s3_bucket.test will be created
  + resource "aws_s3_bucket" "test" {
      + acceleration_status         = (known after apply)
      + acl                         = (known after apply)
      + arn                         = (known after apply)
      + bucket                      = "test"
      + bucket_domain_name          = (known after apply)
      + bucket_prefix               = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + object_lock_enabled         = (known after apply)
      + policy                      = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags_all                    = {
          + "Environment" = "prod"
          + "Terraform"   = "true"
        }
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + tags = {
      + Environment = "prod"
      + Terraform   = "true"
    }
```

**Comment by jtdoepke** [comment]
> Hey @jtdoepke 👋 Thank you for taking the time to raise this, and for opening a pull request to implement it! I'll let the team go through their normal review process, but wanted to mention a workaround in the meantime.

Yep, that's a totally valid way to do this. Our usecase here is that we want to add a common set of default_tags for cost control (`Team`, `Project`, etc) into a lot of existing Terraform workspaces, and to be able to change them with relative ease going forward. We could refactor every TF module we deploy to use that workaround pattern, and then implement it in every new module by convention. But it would be nice if we didn't have to.

My company has a lot of teams distributed globally that are using Terraform relatively independently. I think that this feature will also save us time. If any of those teams forget to implement the above workaround pattern in their own TF, we won't have go bother them to change it.

**Comment by bcbrockway** [comment]
Just to add that this would give an additional benefit whereby you don't have to define:

```
variable "additional_default_tags" {
  description = "A map of tag names to tag values"
  type = map
  default = null
}
```

...in every calling module to ensure it gets passed through to wherever the provider block is defined.
