### ISSUE TITLE
[Docs]: aws_vpc_security_group_egress_rule requires one *and only one* attribute.

### ISSUE THREAD

**Issue by edupo** [hashicorp/terraform-provider-aws#33252]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_security_group_egress_rule.html?lang=typescript#argument-reference

### Description

The documentation isn't clear about defining one _and only one_ attribute to define the source of the `aws_vpc_security_group_egress_rule`. We were only notified during the `plan` with an error.

```
│ Error: Missing Attribute Configuration
│ 
│   with module.my_module[0].aws_vpc_security_group_egress_rule.https["kms"],
│   on modules/my_module/security_group.tf line 84, in resource "aws_vpc_security_group_egress_rule" "https":
│   84: resource "aws_vpc_security_group_egress_rule" "asg_https" {
│ 
│ Exactly one of these attributes must be configured:
│ [cidr_ipv4,cidr_ipv6,prefix_list_id,referenced_security_group_id]
```

It was natural for us to assume that the resource would implement the required rules to fulfill any input. I opened a documentation issue but I'm not sure the behavior of the resource is the expected one.

### Would you like to implement a fix?

No

**Comment by acwwat** [comment]
It looks like this issue has already been addressed via #32148. The doc note has a note to indicate that exactly one of the four attributes is required for `aws_vpc_security_group_egress_rule` and `aws_vpc_security_group_ingress_rule`. Thus this issue can be closed.
