### ISSUE TITLE
Request an Enhancement

### ISSUE THREAD

**Issue by surajtikoo** [hashicorp/terraform-provider-aws#33275]
### Description

AWS Transfer for SFTP supports restricting a user's home directory:

"When a home directory is set to "Restricted", your users will not be able to access anything outside of that folder, nor will they be able to see the S3 bucket or folder name."

I couldn't find a way to do this via the Terraform resource (only could restrict access via a policy), but would be helpful to have it available for setting up new accounts.

### New or Affected Resource(s)
aws_transfer_user

### Potential Terraform Configuration

```tf
resource "aws_transfer_user" "testuser" {
  server_id = "${aws_transfer_server.main.id}"
  user_name = "testuser"
  role      = "${aws_iam_role.default_access.arn}"
  home_directory = "/${aws_s3_bucket.default.bucket}"
  restricted = true

  tags = {
    NAME = "testuser"
  }
}
```

### References

![image](https://github.com/hashicorp/terraform-provider-aws/assets/40026947/984903a0-d0f7-4242-b29b-023247c76474)

### Would you like to implement a fix?

None

**Comment by NicoleYarbrough** [comment]
I am working on a PR for this request and will update shortly.

**Comment by honarkhah** [comment]
According to the docs this does not seems to be an API option and the flag in UI is based on https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_user#home-directory-mappings

**Comment by breathingdust** [comment]
As @honarkhah says, this should already be supported via the 

https://docs.aws.amazon.com/transfer/latest/userguide/API_CreateUser.html#TransferFamily-CreateUser-request-HomeDirectoryMappings

> In most cases, you can use this value instead of the session policy to lock your user down to the designated home directory ("chroot"). To do this, you can set Entry to / and set Target to the value the user should see for their home directory when they log in.

> The following is an Entry and Target pair example for chroot.

> [ { "Entry": "/", "Target": "/bucket_name/home/mydirectory" } ]

Will close this issue, but please raise a bug if this is not working correctly.
