### ISSUE TITLE
[Docs]: all docs

### ISSUE THREAD

**Issue by Kikivsantos** [hashicorp/terraform-provider-aws#33288]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket?lang=typescript#argument-reference

### Description

It seems that all the examples of all the documentation are with problem

The ones I looked at:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket?lang=typescript#argument-reference
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_acl?lang=typescript
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance?lang=typescript

Here is the example of one of this links:
```
// DO NOT EDIT. Code generated by 'cdktf convert' - Please report bugs at https://cdk.tf/bug
import { Construct } from "constructs";
import { TerraformStack } from "cdktf";
/*
 * Provider bindings are generated by running `cdktf get`.
 * See https://cdk.tf/provider-generation for more details.
 */
import { S3Bucket } from "./.gen/providers/aws/s3-bucket";
class MyConvertedCode extends TerraformStack {
  constructor(scope: Construct, name: string) {
    super(scope, name);
    new S3Bucket(this, "example", {
      bucket: "my-tf-test-bucket",
      tags: {
        Environment: "Dev",
        Name: "My bucket",
      },
    });
  }
}
```

### Would you like to implement a fix?

None

**Comment by josnabattula** [comment]
Yep, it is not following the anchor link

**Comment by justinretzolk** [comment]
Hey @Kikivsantos 👋 Thank you for taking the time to raise this! Can you give me a better idea of what issue you're seeing here? I think I'm overlooking whatever it is 😅

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
