### ISSUE TITLE
[Docs]: Creating Neptune read replica

### ISSUE THREAD

**Issue by isaac-solvo** [hashicorp/terraform-provider-aws#33283]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/neptune_cluster_instance.html

### Description

The `aws_neptune_cluster_instance` resource is used to create either a main instance in a cluster (read/write) or a read replica (read-only).

When the resource is being created, there's a check whether this is the first instance in the cluster. If yes, then it is set to be the main instance. Otherwise, it is set to be a read replica.

Consider a Terraform template that has two `aws_neptune_cluster_instance` resources connected to the same cluster, each of which has different instance type, different name etc. In that case, the only way to ensure which resource is the main one and which one is the replica, would be to use `depends_on`.

I think that this is an important enough use case to add to the documentation.

### Would you like to implement a fix?

Yes

**Comment by isaac-solvo** [comment]
I understand the rationale. We had a use case that seemed to require this differentiation (setting up a VPN endpoint that would only allow ingress to the read replicas) but that use case have since changed and we don't require that differentiation anymore. This perhaps should be closed.

**Comment by triggan** [comment]
Understood.  If you come across that use case again, I would suggest locking down read access by using IAM Authentication on the Neptune cluster and only allowing access to the associated read/get data access policies (https://docs.aws.amazon.com/neptune/latest/userguide/iam-dp-actions.html).  That should provide a cleaner solution versus locking things down at the network level.
