### ISSUE TITLE
What is considered the "major" version for the aws_rds_cluster.allow_major_version_upgrade when using 5.7-mysq-aurora?

### ISSUE THREAD

**Issue by rquadling** [hashicorp/terraform-provider-aws#33296]
### Description

Just not able to get my head around what is the major.minor.patch when it comes to the automated upgrades on MySQL Aurora in RDS.

What we are experienced recently is an upgrade from `5.7.mysql_aurora.2.10.3` to `5.7.mysql_aurora.2.11.2` as we have set aws_rds_cluster_instance.auto_minor_version_upgrade to true.

The issue is that when we did a small deployment (from a repo that has RDS in it but RDS was not related to the change), the `terraform apply` stopped as the version in our tfvars file didn't exist. Happy that the apply stopped. That was correct.

What we cannot work out is what are we supposed to have setup that allows you to initially nominate the version of MySQL Aurora you want to start with (so, effectively, for MySQL 5.7 or 8.0 but on Aurora), but also allow the upgrades to take place as and when needed and managed by AWS ... AND ... not have Terraform complain about this all.

From what I've read, a LOT of info is about non-Aurora (or I've badly interpreted it).

If there is a clear outline on what should be set to have Terraform accept the upgrades and NOT complain and what the difference between the `allow_major_version_upgrade` and `auto_minor_version_upgrade` options are, and why are they not all managed on the cluster (cluster deals with major, instances deal with minor ... that makes sense ... but how do we define the initial version of the cluster?)

We are NOT able to move the the mysql 8.0 compatible version of Aurora, which I see as Aurora v3, so is that the "major" version? I may have gotten "polluted" with Semantic Versioning and so 2.10.3 to 2.11.2 is a minor version upgrade. It makes sense.

We could add a `lifecycle { ignore_changes = [engine_version] }` to cheat things.

So. Please help. What am I not getting right?

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @rquadling 👋 Thank you for taking the time to raise this, and apologies that it's taken a bit to get back to you. We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. To maintain that, we ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). With that in mind, I'm going to close this issue.

With that said, I found some resources that might help answer your question. 

[This AWS document](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.VersionPolicy.html#Aurora.VersionPolicy.MajorVersions) covers the distinction in `major`.`minor`.`patch`, and what "major version upgrades" are.

The [`engine_version` argument](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#engine_version) is what's used to set the version of the initial version on the cluster.

The `allow_*_version_upgrade` arguments are probably best described with this quote from the [AWS API](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBCluster.html):

    > You must allow major version upgrades when specifying a value for the EngineVersion parameter that is a different major version than the DB cluster's current version.

Essentially, these need to be set to `true` when you're changing the `engine_version` to a higher major version when managing the versioning via Terraform.

As far as having AWS handle version upgrades and not having Terraform output a diff, that would be a case where the `ignore_changes` example you gave would be useful. Terraform will attempt to rectify changes to the configuration if it detects drift, so upgrades happening outside of Terraform will cause that unless ignored.
