### ISSUE TITLE
[Enhancement]: update_behavior is missing "Add new columns only" option in aws_glue_crawler

### ISSUE THREAD

**Issue by hongbo-miao** [hashicorp/terraform-provider-aws#33325]
### Description

Currently for [update_behavior](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_crawler#update_behavior), it only supports `UPDATE_IN_DATABASE` and `LOG`. However, it misses corresponding option for "Add new columns only".

When the crawler detects schema changes in the data store, how should AWS Glue handle table updates in the data catalog?

- Update the table definition in the data catalog (`UPDATE_IN_DATABASE`)
- Add new columns only (<- Missing option for this one)
- Ignore the change and don't update the table in the data catalog (`LOG`)

![image](https://github.com/hashicorp/terraform-provider-aws/assets/3375461/27f7264b-f381-4b99-8bcf-529cea9233e6)

It would be great to support, thanks!

### Affected Resource(s) and/or Data Source(s)

aws_glue_crawler

**Comment by justinretzolk** [comment]
Hey @hongbo-miao 👋 Thank you for taking the time to raise this! This particular argument uses [a function from the AWS Go SDK](https://github.com/hashicorp/terraform-provider-aws/blob/8551305b57f11727994f780c0fc3e249987896f1/internal/service/glue/crawler.go#L410) to validate the supplied values. Looking at the [AWS Go SDK](https://raw.githubusercontent.com/aws/aws-sdk-go/v1.45.3/service/glue/api.go) (apologies, the file is too large for GitHub, so I can only link to the raw content), it looks like it hasn't yet been updated to include the "add new columns only" option. Once that gets updated, it will work with no additional changes on the AWS provider side.

**Comment by hongbo-miao** [comment]
Oh I see, thank you so much @justinretzolk ! ☺️

**Comment by justinretzolk** [comment]
Happy to help @hongbo-miao! Given that there's nothing for the team to do to enable this, I'm going to go ahead and close this one out. If you have any additional questions, or feel I've done this in error, please do let me know.

**Comment by hongbo-miao** [comment]
Hi @justinretzolk I found the way!

Basically based on https://docs.aws.amazon.com/glue/latest/dg/crawler-configuration.html

> If you don't want a crawler to overwrite updates you made to existing fields in an Amazon S3 table definition, choose the option on the console to **Add new columns only** or set the configuration option `MergeNewColumns`. This applies to tables and partitions, unless `Partitions.AddOrUpdateBehavior` is overridden to `InheritFromTable`.

This works:

```
resource "aws_glue_crawler" "my_aws_glue_crawler" {
  # ...
  configuration = jsonencode(
    {
      Version = 1.0,
      CrawlerOutput = {
        Tables     = { AddOrUpdateBehavior = "MergeNewColumns" }
      }
    }
  )
}
```

And `update_behavior` can be removed, as even provided, it will be overwritten by `AddOrUpdateBehavior`. 😃
