### ISSUE TITLE
[Enhancement]: AWS Cloud9 clarifications for custom AMI usage

### ISSUE THREAD

**Issue by Breee** [hashicorp/terraform-provider-aws#33353]
### Description

We want to use Cloud9 to spawn maintenance / temporary environments with a specific toolset, however in the code of this provider, it is not allowed to choose an arbitrary AMI 

https://github.com/hashicorp/terraform-provider-aws/blob/cecb9c0f7c2f5f547a115c64729676482496e2b8/internal/service/cloud9/environment_ec2.go#L62C6-L62C6 

So we do not understand how to create Cloud9 environments with custom tools using terraform. If it is possible, please clarify it.

### Affected Resource(s) and/or Data Source(s)

cloud9_environment_ec2

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @Breee 👋 Thank you for taking the time to raise this! I took a look at this, and it looks like what you're looking for is a [SSH environment](https://docs.aws.amazon.com/cloud9/latest/user-guide/create-environment-ssh.html). Unfortunately, as alluded to by the mention of the CLI limitations at the top of that document, AWS does not provide an API endpoint for creating an SSH environment; only an [EC2 environment](https://docs.aws.amazon.com/cloud9/latest/APIReference/API_CreateEnvironmentEC2.html) (which what the `aws_cloud9_environment_ec2` resource leverages). EC2 environments are not able to be created with a custom AMI, only those listed in the linked document.
