### ISSUE TITLE
[Enhancement]: Add resource_sets to aws_fms_policy

### ISSUE THREAD

**Issue by marcosentino** [hashicorp/terraform-provider-aws#33372]
### Description

Provide the user the ability to use Terraform to create AWS Firewall Manager resource sets. Currently, they are not able to use AWS Firewall Manager effectively to manage policies via Terraform. To do so, the "resource_sets" attribute needs to be added to the "aws_fms_policy" resource to facilitate firewall policy management within AWS Firewall Manager.

### Affected Resource(s) and/or Data Source(s)

aws_fms_policy

### Would you like to implement a fix?

None

**Comment by stumyp** [comment]
For full support of resource sets we need to be able to create them in Terraform as well, not just reference.

https://github.com/hashicorp/terraform-provider-aws/issues/35000
