### ISSUE TITLE
[Bug]: Auto scaling instance refresh fails with validation errors

### ISSUE THREAD

**Issue by mhowell-ims** [hashicorp/terraform-provider-aws#33377]
### Terraform Core Version

1.4.6

### AWS Provider Version

5.16.0

### Affected Resource(s)

aws_autoscaling_group

### Expected Behavior

The instance refresh should not have failed due to validation errors. No values were provided for instance_refresh.preferences.scale_in_protected_instances nor for instance_refresh.preferences.standby_instances, and therefor the documented default values should have been used.

### Actual Behavior

Auto scaling instance refreshes are failing since upgrading from AWS provider 5.15.0 to 5.16.0. Instance refreshes are now failing with:

Error: starting Auto Scaling Group (nexus-20230829195735457800000001) instance refresh: ValidationError: 2 validation errors detected: Value '' at 'preferences.scaleInProtectedInstances' failed to satisfy constraint: Member must satisfy enum value set: [Ignore, Wait, Refresh]; Value '' at 'preferences.standbyInstances' failed to satisfy constraint: Member must satisfy enum value set: [Terminate, Ignore, Wait]

No values were set for either of these preferences in the terraform configuration and so the documented default values should have been used.

### Relevant Error/Panic Output Snippet

```shell
Error: starting Auto Scaling Group (nexus-20230829195735457800000001) instance refresh: ValidationError: 2 validation errors detected: Value '' at 'preferences.scaleInProtectedInstances' failed to satisfy constraint: Member must satisfy enum value set: [Ignore, Wait, Refresh]; Value '' at 'preferences.standbyInstances' failed to satisfy constraint: Member must satisfy enum value set: [Terminate, Ignore, Wait]
```

### Terraform Configuration Files

[aws-provider-bug-33377.tar.gz](https://github.com/hashicorp/terraform-provider-aws/files/12563544/aws-provider-bug-33377.tar.gz)

### Steps to Reproduce

1. Run terraform init and terraform apply.
2. Wait for the auto scaling group to create the 1 EC2 instance.
3. Edit line 40 of instance-init.sh to echo a different value.
4. Run terraform apply again. The change to the userdata script will trigger a change to the launch template and therefor an instance refresh as well. 
5. The terraform apply should succeed as we are using AWS provider v 5.15.0 at this point.
6. Wait for the instance refresh to complete.
7. Edit versions.tf to change the AWS provider version to 5.16.0.
8. Repeat steps 3 and 4 above.
9. terraform apply reports 2 instance refresh validation errors, and no instance refresh is performed.

### Important Factoids

I am using terraform-aws-modules/autoscaling/aws version 6.10.0 (latest as of now) to create the auto scaling group. Based on the code you can see that it's using a dynamic block to the build the instance refresh configuration. No values are provided for instance_refresh.preferences.scale_in_protected_instances nor for instance_refresh.preferences.standby_instances. https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/v6.10.0/main.tf#L669

### Would you like to implement a fix?

None

**Comment by mhowell-ims** [comment]
[aws-provider-bug-33377.tar.gz](https://github.com/hashicorp/terraform-provider-aws/files/12563484/aws-provider-bug-33377.tar.gz)

Here is the terraform code to reproduce the issue.

**Comment by adiospeds** [comment]
I have traced this to changes made in [v5.16.1](https://github.com/hashicorp/terraform-provider-aws/tree/v5.16.1) and have created a Pull request to fix this issue: [#33382](https://github.com/hashicorp/terraform-provider-aws/pull/33382)

**Comment by zm-alex** [comment]
+1 on this issue

This is a blocker for anyone using the aws-autoscaling-group module and instance refresh resources

**Comment by shb-mll** [comment]
+1 on this issue.

**Comment by Nikhilpurva** [comment]
Instance refresh will work if you add `scale_in_protected_instances` in your instance refresh config. For eg:
```hcl
instance_refresh = {
    strategy = "Rolling"
    preferences = {
      min_healthy_percentage = 50
      instance_warmup        = 0
      scale_in_protected_instances = "Ignore"
    }
    triggers = ["launch_template"]
  }
```
