### ISSUE TITLE
[Bug]: Parameters removed when creating Iceberg Glue Tables

### ISSUE THREAD

**Issue by gdowmont-gss** [hashicorp/terraform-provider-aws#33370]
### Terraform Core Version

1.5.0

### AWS Provider Version

5.16.0

### Affected Resource(s)

aws_glue_catalog_table

### Expected Behavior

When modifying existing Glue Table with Iceberg configuration enabled (open_table_format_input) provider should modify configuration of the table while persisting Parameters values for:

```
"Parameters": {
            "metadata_location": "s3://some-path/test2/metadata/00000-fb573dc6-8b72-46eb-8093-6757a808c57e.metadata.json",
            "table_type": "ICEBERG"
        }
```

### Actual Behavior

Parameters metadata_location and table_type are removed and the table is no longer usable as an Iceberg table. 

### Terraform Configuration Files

```hcl
resource "aws_glue_catalog_table" "aws_glue_catalog_table_test" {
  name          = "test"
  database_name = "db_name"
  table_type    = "EXTERNAL_TABLE"

  open_table_format_input {
    iceberg_input {
      metadata_operation = "CREATE"
      version            = 2
    }
  }

  storage_descriptor {
    location = "s3://bucket_name/"
    columns {
      name = "field1"
      type = "string"
    }
  }
}
```

### Steps to Reproduce

1. Create new glue table while specifying: 
```
open_table_format_input {
    iceberg_input {
      metadata_operation = "CREATE"
      version            = 2
    }
}
```
and setting location in storage_descriptor
2. Check that table incudes Parameters: metadata_location and table_type
3. Add/rename column in storage descriptor
4. Apply terraform
5. After successful apply table loses Parameters: metadata_location and table_type

### References

#33157

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/715dc15ebf759edfeefa35b1945016dfa0fdd2b2/internal/service/glue/catalog_table.go#L1094-L1101
