### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by MississippiBrenn** [hashicorp/terraform-provider-aws#33407]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/medialive_channel#input-loss-failover-settings

### Description

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/medialive_channel#input-loss-failover-settings

automatic_failover_conditions should be automatic_failover_condition

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @MississippiBrenn 👋 Thank you for taking the time to raise this! I took a look over the documentation that you linked, and couldn't find an argument of `automatic_failover_conditions`, however, I did find `automatic_input_failover_settings.failover_conditions`, which looks like it should instead be `automatic_input_failover_settings.failover_condition` -- is that what you were looking to report?
