### ISSUE TITLE
[Enhancement]: Security Hub - Support enabling and disabling controls in all standards

### ISSUE THREAD

**Issue by matthewbarreiro** [hashicorp/terraform-provider-aws#33406]
### Description

When using unified security controls, AWS provides a method to [enable or disable a control across all standards.](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-enable-disable-controls.html)

Doing this in Terraform now requires disabling the control in each individual standard, e.g.:
```
"arn:aws:securityhub:us-east-1:111111111111:control/aws-foundational-security-best-practices/v/1.0.0/IAM.14"
"arn:aws:securityhub:us-east-1:111111111111:control/cis-aws-foundations-benchmark/v/1.4.0/1.9",
# etc
```
as opposed to just once (e.g. `"IAM.14"`).

This functionality would likely be implemented by adding a new `aws_securityhub_standards_control` resource, but would be closely related to the `aws_securityhub_standards_control` resource

### Affected Resource(s) and/or Data Source(s)

* aws_securityhub_standards_control
* aws_securityhub_account
* aws_securityhub_standards_subscription

### Potential Terraform Configuration

```terraform
resource "aws_securityhub_account" "example" {
  control_finding_generator = "SECURITY_CONTROL"
}

resource "aws_securityhub_standards_subscription" "cis_aws_foundations_benchmark" {
  standards_arn = "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0"
  depends_on    = [aws_securityhub_account.example]
}

resource "aws_securityhub_security_control" "ensure_iam_password_policy_prevents_password_reuse" {
  security_control_id   = "IAM.16" 
  control_status        = "DISABLED"
  disabled_reason       = "We handle password policies within Okta"

  depends_on = [aws_securityhub_standards_subscription.cis_aws_foundations_benchmark]
}
```

### References

* [Enabling and disabling controls in all standards | AWS Security Hub User Guide](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-enable-disable-controls.html)
* [`BatchUpdateStandardsControlAssociations` | AWS Security Hub API Reference ](https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_BatchUpdateStandardsControlAssociations.html)
    * [Go SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/securityhub/#SecurityHub.BatchUpdateStandardsControlAssociations)
* [`ListStandardsControlAssociations` | AWS Security Hub API Reference ](https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_ListStandardsControlAssociations.html)
    * [Go SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/securityhub/#SecurityHub.ListStandardsControlAssociations)
* [`BatchGetStandardsControlAssociations` | AWS Security Hub API Reference ](https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_BatchGetStandardsControlAssociations.html)
    * [Go SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/securityhub/#SecurityHub.BatchGetStandardsControlAssociations)
* [Disabling Security Hub controls in a multi-account environment | AWS Security Blog](https://aws.amazon.com/blogs/security/disabling-security-hub-controls-in-a-multi-account-environment/)

### Would you like to implement a fix?

No

EDIT: Removed superfluous details

**Comment by fatbasstard** [comment]
Is there any progress in this?

**Comment by nitrocode** [comment]
Yes that makes sense. I had to give the following to disable the control.

```bash
aws securityhub batch-update-standards-control-associations \
  --standards-control-association-updates '[{
      "SecurityControlId": "IAM.16",
      "StandardsArn": "arn:aws:securityhub:us-east-1::standards/aws-foundational-security-best-practices/v/1.0.0",
      "AssociationStatus": "DISABLED",
      "UpdatedReason": "We handle password policies within Okta"
  }]'
```

so a more accurate resource would be

```hcl
resource "aws_securityhub_security_control" "default" {
  security_control_id = "IAM.16" 
  standards_arn       = "arn:aws:securityhub:us-east-1::standards/aws-foundational-security-best-practices/v/1.0.0"
  association_status  = "DISABLED"
  updated_reason      = "We handle password policies within Okta"
}
```

**Comment by nitrocode** [comment]
Sweet, thank you very much
