### ISSUE TITLE
[Docs]: Typo in `id` Attribute Reference: `aws_acmpca_certificate_authority` resource

### ISSUE THREAD

**Issue by 0xabdi** [hashicorp/terraform-provider-aws#33425]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acmpca_certificate_authority#id

### Description

Typo in:

```
id - ARN of the certificate authority.
```

It should be:

```
id - ID of the certificate authority.
```

### Would you like to implement a fix?

Yes

**Comment by stefanfreitag** [comment]
Hi @0xabdi, I think the documentation is correct when stating that the ID field contains as value the  ARN of the created resource. You can try the example below, it  outputs the contents of the ID and ARN fiields.

```hcl
resource "aws_acmpca_certificate_authority" "example" {
  usage_mode = "SHORT_LIVED_CERTIFICATE"
  certificate_authority_configuration {
    key_algorithm     = "RSA_4096"
    signing_algorithm = "SHA512WITHRSA"
    subject {
      common_name = "example.com"
    }
  }
}

output "abc" {
  value       = aws_acmpca_certificate_authority.example.arn
  description = "ARN of the resource"
}

output "def" {
  value       = aws_acmpca_certificate_authority.example.id
  description = "ID of the resource"
}
``` 

On source code level you can find in the func [`resourceCertificateAuthorityCreate`](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/acmpca/certificate_authority.go#L383) following statement.

```go
d.SetId(aws.StringValue(outputRaw.(*acmpca.CreateCertificateAuthorityOutput).CertificateAuthorityArn))
```
