### ISSUE TITLE
[Enhancement]: Support `fargateTaskRetirementWaitPeriod` in ECS account defaults

### ISSUE THREAD

**Issue by moritzzimmer** [hashicorp/terraform-provider-aws#33422]
### Description

Support the configuration of `fargateTaskRetirementWaitPeriod` as an ECS account default. This is already possible using the CLI, see https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-account-settings.html#fargate-retirement-wait-time for details.

Valid values are `0`, `7` and `14`

### Affected Resource(s) and/or Data Source(s)

* aws_ecs_account_setting_default

### References

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-account-settings.html#fargate-retirement-wait-time

### Would you like to implement a fix?

None

**Comment by acdha** [comment]
This is blocked on https://github.com/hashicorp/terraform-provider-aws/pull/33393 which will remove the input validation currently constraining `aws_ecs_account_setting_default.value` to true or false.
