### ISSUE TITLE
[Enhancement]: additional attributes configurations for load balancer target groups (aws_lb_target_group)

### ISSUE THREAD

**Issue by marcaurele** [hashicorp/terraform-provider-aws#33424]
### Description

Terraform does not currently provide a native way to change additional attributes for target groups of a network load balancer. By default target groups that are associated with a network load balancer have a whole list of extra configuration options:

![image](https://github.com/hashicorp/terraform-provider-aws/assets/1081566/490c1a9a-458f-41f0-934f-dd47f25d8ccb)

One of the important option we are looking for is to configure the `target_health_state.unhealthy.connection_termination.enabled`. See key configuration options with the AWS CLI: `aws elbv2 modify-target-group-attributes help`

### Affected Resource(s) and/or Data Source(s)

* aws_lb_target_group

### Potential Terraform Configuration

```terraform
resource "aws_lb_target_group" "test" {
  name     = "tf-example-lb-tg"
  port     = 80
  protocol = "HTTP"
  vpc_id   = aws_vpc.main.id

  proxy_protocol_v2 = true
  deregistration_delay {
    connection_termination = false
  }
  target_health_state {
    unhealthy_connection_termination = false
  }
}

resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
}
```

### References

- https://github.com/hashicorp/terraform-provider-aws/issues/19766

### Would you like to implement a fix?

No

**Comment by acwwat** [comment]
Looking at the latest [`aws_lb_target_group` resource doc](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group), it seems that all the requested features are now available. This issue can probably be closed.

**Comment by marcaurele** [comment]
> Looking at the latest [`aws_lb_target_group` resource doc](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group), it seems that all the requested features are now available. This issue can probably be closed.

Correct, I'm closing the ticket as implemented. Things were added in version `5.62.0`, `5.59.0`.
