### ISSUE TITLE
[Bug]: Updating an aws_iot_topic_rule resource does not retry on temporary IAM exception

### ISSUE THREAD

**Issue by nlangowitz** [hashicorp/terraform-provider-aws#33433]
### Terraform Core Version

1.1.5

### AWS Provider Version

4.60.0

### Affected Resource(s)

* aws_iot_topic_rule

### Expected Behavior

When an `aws_iam_role` resource referenced in an `aws_iot_topic_rule` action block's `role_arn` is updated in a way that requires replacement, the IoT Topic Rule should be updated to use the new role ARN, without error

### Actual Behavior

`terraform apply` failed while updating the IoT Topic Rule, but succeeded when retried.

### Relevant Error/Panic Output Snippet

```shell
│ Error: replacing IoT Topic Rule (<my_resource>): InvalidRequestException: AWS IoT (iot.amazonaws.com) is unable to assume role (sts:AssumeRole) on resource: arn:aws:iam::<my_account>:role/<my_role>.  If the role was just created or updated, please try again in a few seconds.
```

### Terraform Configuration Files

Sorry, I haven't tested a minimal reproduction and am not sure if I can include our actual config, but this has happened consistently, so I think something along the lines of:

```
resource "aws_iam_role" "iot_rule" {
  name = "foo"
  assume_role_policy = data.aws_iam_policy_document.assume_role.json
}

data "aws_iam_policy_document" "assume_role" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["iot.amazonaws.com"]
    }
  }
}

resource "aws_sqs_queue" "queue" {
  name = "foo"
}

resource "aws_iot_topic_rule" "main" {
  name = "my_rule"
  enabled = true
  sql = "SELECT * FROM 'foo/#'"
  sql_version = "2016-03-23"

  sqs {
    queue_url = aws_sqs_queue.queue.url
    role_arn = aws_iam_role.iot_rule.arn
    use_base64 = false
  }
}
```

### Steps to Reproduce

1. `terraform apply` with the starting configuration
2. Change the name on the "aws_iam_role" resource to something different
3. `terraform apply` again -- the IAM role should be replaced, and then the IoT Rule updated, which will fail (may take a few tries since it might not always happen too soon for the IAM update to be propagated, though I'd consistently hit the error)

### Important Factoids

It looks like the provider already checks for this same error in the `resourceTopicRuleCreate` [action](https://github.com/hashicorp/terraform-provider-aws/blob/cd2c2fbaf85651452e44eb0ff2a017ac0824d315/internal/service/iot/topic_rule.go#L1212) but does not do so in `resourceTopicRuleUpdate`, so I suspect there is a trivial fix.

I'd kind of like to implement a fix, but need to go through my employer's review process first, so it might be a while, also I don't use go so while I'm 99% sure copying the code from `resourceTopicRuleCreate` to `resourceTopicRuleUpdate` will fix it, the ramp-up time for me to be able to write a test of that might be too much.

### Would you like to implement a fix?

None

**Comment by nlangowitz** [comment]
I saw "service/sqs" got added automatically, I'd just picked that as an example action using a `role_arn`, I don't believe this  is SQS-specific in any way

**Comment by moonorange** [comment]
I would like to work on it
