### ISSUE TITLE
[Bug]: r/aws_neptune_cluster_instance: engine_version parameter should be ignored

### ISSUE THREAD

**Issue by triggan** [hashicorp/terraform-provider-aws#33467]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.16.2

### Affected Resource(s)

* aws_neptune_cluster_instance

### Expected Behavior

If a user currently provides the `engine_version` parameter on an `aws_neptune_cluster_instance` resource and then goes to perform an engine upgrade of the hosting `aws_neptune_cluster` that owns that instance, Terraform forces an instance replacement for any affected instances in that cluster.

Engine version upgrades in Neptune are handled at a cluster level, and not at an instance level. All instances in a cluster are required (and forced) to be on the same engine version as the hosting cluster.  Upon an engine version upgrade, Neptune will push the latest engine code to each instance and force a reboot of each instance.  There is no present requirement to replace all instances in a cluster when performing an engine upgrade.

Per the AWS CLI man page for `aws neptune create-db-instance` and `aws neptune modify-db-instance`, the `--engine-version` parameter is listed as:
```
       --engine-version (string)
          The version number of the database engine to upgrade to. Currently,
          setting this parameter has no effect. To upgrade your database
          engine to the most recent release, use the
          ApplyPendingMaintenanceAction API.
```

As such, the `aws_neptune_cluster_instance` resource schema needs to be altered to mirror this lack of constraint.

### Actual Behavior

The current functionality forces an instance replacement after changing the `engine_version` parameter on both a cluster and all affected instances within the cluster.

### Terraform Configuration Files

Initial configuration file:
```
resource "aws_neptune_cluster" "new_cluster" {
  cluster_identifier = "neptunetestcluster"
  storage_encrypted = true
  engine_version = "1.2.0.1"
  skip_final_snapshot = true
  neptune_cluster_parameter_group_name = "default.neptune1.2"
}

resource "aws_neptune_cluster_instance" "new_instance_1" {
  cluster_identifier = aws_neptune_cluster.new_cluster.id
  engine             = "neptune"
  instance_class     = "db.r5.large"
  engine_version = "1.2.0.1"
  neptune_parameter_group_name = "default.neptune1.2"
}
```

### Steps to Reproduce

After the initial `apply`, change the `engine_version` parameters for both resources to `1.2.0.2` and notice that Terraform is asking for the instance to be destroyed and replaced.

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Related #29785
