### ISSUE TITLE
[New Resource & Data Source]: Image Block Public Access

### ISSUE THREAD

**Issue by rymancl** [hashicorp/terraform-provider-aws#33473]
### Description

https://aws.amazon.com/about-aws/whats-new/2023/09/amazon-ec2-block-public-access-machine-images/
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sharingamis-intro.html#enable-block-public-access-for-amis

Add new resource and data source for AMI BPA. 

### Requested Resource(s) and/or Data Source(s)

* `aws_ec2_image_block_public_access`
    * or `aws_ami_block_public_access` since you already use the "aws_ami" prefix for other resources

### Potential Terraform Configuration

```terraform
resource "aws_ec2_image_block_public_access" "this" {
  enabled = true
  # enabled = false
}

# or

resource "aws_ec2_image_block_public_access" "this" {
  image_block_public_access_state = "block-new-sharing"
  # image_block_public_access_state = "unblocked"
}
```

### References

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2#Client.EnableImageBlockPublicAccess

### Would you like to implement a fix?

No

**Comment by chilledornaments** [comment]
@justinretzolk  I'd love to tackle this one :)
