### ISSUE TITLE
[Enhancement]: aws_route53_resolver_endpoint does not support DualStack deployment

### ISSUE THREAD

**Issue by archoversight** [hashicorp/terraform-provider-aws#33476]
### Description

`ResolverEndpointType` is not a supported attribute on `aws_route53_resolver_endpoint`.

See https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ResolverEndpoint.html

### Affected Resource(s) and/or Data Source(s)

* aws_route53_resolver_endpoint

### Potential Terraform Configuration

```terraform
resource "aws_route53_resolver_endpoint" "management_internal_outbound" {
  name                   = module.context_route53_management_internal_outbound.name
  tags                   = module.context_route53_management_internal_outbound.tags
  direction              = "OUTBOUND"
  resolver_endpoint_type = "DUALSTACK"
  security_group_ids = [aws_security_group.management_edge_dns.id]

  dynamic "ip_address" {
    for_each = var.vpc_subnets.infrastructure
    content {
      subnet_id = aws_subnet.management_infrastructure[ip_address.key].id
    }
  }
}
```

### References

https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_ResolverEndpoint.html

### Would you like to implement a fix?

No

**Comment by YashrajRathi** [comment]
@justinretzolk  Can I take this issue ?
