### ISSUE TITLE
[Docs]: key_algorithm argument in the tls_cert_request resource is read only

### ISSUE THREAD

**Issue by 0xabdi** [hashicorp/terraform-provider-aws#33481]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acmpca_certificate

### Description

The example usage on [this page](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acmpca_certificate) has the code block below. 

```hcl
resource "tls_cert_request" "csr" {
  key_algorithm   = "RSA"
}
```

However, using such a code in a terraform config (`terraform v1.5.6`) results in the below error:

```shell
│ Error: Invalid Configuration for Read-Only Attribute
│
│   with tls_cert_request.example-csr,
│   on main.tf line 119, in resource "tls_cert_request" "example-csr":
│  119:   key_algorithm   = "RSA"
│
│ Cannot set value for this attribute as the provider has marked it as read-only. Remove the configuration line setting the value.
│
│ Refer to the provider documentation or contact the provider developers for additional information about configurable and read-only attributes that are supported.
```

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acmpca_certificate

### Would you like to implement a fix?

Yes

**Comment by Nayankumar696583** [comment]
i am working on this issue fix.

**Comment by Nayankumar696583** [comment]
@0xabdi I have made the change and you could find them in branch -[ fix_issue_33481](https://github.com/hashicorp/terraform-provider-aws/compare/hashicorp:main...fidelity-contributions:fix_issue_33481?expand=1)

Please review and merge
