### ISSUE TITLE
[Bug]: Terraform doesn't send themeArn field in API call when creating or updating aws_quicksight_analysis

### ISSUE THREAD

**Issue by atlesp** [hashicorp/terraform-provider-aws#33524]
### Terraform Core Version

 1.4.6 

### AWS Provider Version

5.16.2

### Affected Resource(s)

* aws_quicksight_analysis
* aws_quicksight_dashboard

### Expected Behavior

When we set `theme_arn` for `aws_quicksight_analysis` or `aws_quicksight_dashboard` we expect it to be forwarded to the API call to create/update the analysis/dashboard and applied to the analysis/dashboard in Quicksight. 

### Actual Behavior

Instead of forwarding it to the API call it seems to set it back to null, so it is always reset to the default classic theme on every deployment.  

We have tried to set it both to `arn:aws:quicksight::aws:theme/MIDNIGHT` and created a new theme with `aws_quicksight_theme` and linked to that.

I checked the source code for the resource for [create](https://github.com/hashicorp/terraform-provider-aws/blob/dd99384e95b43121c6d97d545c2f366a4ba34c79/internal/service/quicksight/analysis.go#L158) and [update](https://github.com/hashicorp/terraform-provider-aws/blob/dd99384e95b43121c6d97d545c2f366a4ba34c79/internal/service/quicksight/analysis.go#L266C21-L266C40) and they do not include the `themeArn` as they should be based on the GO API docs [CreateAnalysisInput](https://docs.aws.amazon.com/sdk-for-go/api/service/quicksight/#CreateAnalysisInput) and [Update](
https://docs.aws.amazon.com/sdk-for-go/api/service/quicksight/#UpdateAnalysisInput)

### Terraform Configuration Files

```
resource "aws_quicksight_analysis" "test" {
  analysis_id = "test"
  name        = "test"
  theme_arn   = "arn:aws:quicksight::aws:theme/MIDNIGHT"

  definition {
    data_set_identifiers_declarations {
      identifier   = aws_quicksight_data_set.test.name
      data_set_arn = aws_quicksight_data_set.test.arn
    }

    sheets {
      sheet_id     = "sheet-id1"
      description  = "Some description"
      name         = "Some Name"
      content_type = "INTERACTIVE"
      text_boxes {
        sheet_text_box_id = "textbox-id"

      }
      layouts {
        configuration {
          grid_layout {
            elements {
              column_index = 0
              column_span  = 36
              element_id   = "textbox-id"
              element_type = "TEXT_BOX"
              row_index    = 0
              row_span     = 3
            }
          }
        }
      }

    }

    analysis_defaults {
      default_new_sheet_configuration {
        interactive_layout_configuration {
          grid {
            canvas_size_options {
              screen_canvas_size_options {
                resize_option             = "FIXED"
                optimized_view_port_width = "1600px"
              }
            }
          }
        }
        sheet_content_type = "INTERACTIVE"
      }
    }
  }
}

```

### Steps to Reproduce

Set `theme_arn` for a `aws_quicksight_analysis` or `aws_quicksight_dashboard` to any other value than the classic theme, for example `arn:aws:quicksight::aws:theme/MIDNIGHT`, and verify that it is not applied after running `tf apply`.

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/31737.
