### ISSUE TITLE
[Bug]: aws_db_instance ca_cert_identifier field applied but not reflected

### ISSUE THREAD

**Issue by valugi** [hashicorp/terraform-provider-aws#33546]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.14.0

### Affected Resource(s)

aws_db_instance

### Expected Behavior

RDS AWS instance should have rds-ca-rsa2048-g1  CA.

### Actual Behavior

RDS AWS instance remains on rds-ca-2019 .

### Relevant Error/Panic Output Snippet

```shell
There is no error. The changed is detected correctly in plan and apply. According to terraform the change is done, but the value is not changed. 

Rebooting the db does not help. No items are left to install in maintenance.
```

### Terraform Configuration Files

```terraform
resource "aws_db_instance" "db" {
  identifier_prefix                   = "${lower("${var.name}-RDS")}-"
  allocated_storage                   = var.allocated_storage
  max_allocated_storage               = var.max_allocated_storage
  storage_type                        = var.storage_type
  engine                              = var.db_engine
  engine_version                      = var.db_engine_version
  storage_encrypted                   = var.storage_encrypted
  instance_class                      = var.instance_class
  username                            = var.username
  manage_master_user_password         = true
  iam_database_authentication_enabled = true
  db_subnet_group_name                = aws_db_subnet_group.default.name
  multi_az                            = var.multi_az
  copy_tags_to_snapshot               = true
  final_snapshot_identifier           = "${lower("${var.name}-RDS")}-final-snapshot"
  vpc_security_group_ids              = [aws_security_group.rds_sg.id]
  parameter_group_name                = var.parameter_group_name
  backup_retention_period             = "7"
  backup_window                       = "05:00-06:00"
  maintenance_window                  = "Sun:06:00-Sun:07:00"
  auto_minor_version_upgrade          = "true"
  allow_major_version_upgrade         = var.allow_major_version_upgrade
  monitoring_interval                 = var.monitoring_interval
  monitoring_role_arn                 = var.monitoring_role_arn
  deletion_protection                 = var.deletion_protection
  enabled_cloudwatch_logs_exports     = var.enabled_cloudwatch_logs_exports
  ca_cert_identifier                  = "rds-ca-rsa2048-g1"
  port                                = var.db_ingress_port
}
```

### Steps to Reproduce

For a database with current ca_cert_identifier "rds-ca-2019" , update to  "rds-ca-rsa2048-g1".

### Debug Output

build	20-Sep-2023 10:59:14	[0m[0m[1maws_s3_bucket_policy.flow_logs_policy: Modifying... [id=3556xxx-vpc-xxx][0m[0m
build	20-Sep-2023 10:59:14	[0m[1mmodule.rds.aws_db_instance.db: Modifying... [id=db-YMBM3QDXXXX][0m[0m
build	20-Sep-2023 10:59:14	[0m[1maws_s3_bucket_policy.flow_logs_policy: Modifications complete after 0s [id=3556xxx-vpc-0ebb17caaf2062b8c-flow-log-kerr-mg2-dev][0m
build	20-Sep-2023 10:59:24	[0m[1mmodule.rds.aws_db_instance.db: Still modifying... [id=db-YMBM3QDXXXX, 10s elapsed][0m[0m
build	20-Sep-2023 10:59:34	[0m[1mmodule.rds.aws_db_instance.db: Still modifying... [id=db-YMBM3QDXXXX, 20s elapsed][0m[0m
build	20-Sep-2023 10:59:44	[0m[1mmodule.rds.aws_db_instance.db: Still modifying... [id=db-YMBM3QDXXXX, 30s elapsed][0m[0m
build	20-Sep-2023 10:59:54	[0m[1mmodule.rds.aws_db_instance.db: Still modifying... [id=db-YMBM3QDXXXX, 40s elapsed][0m[0m
build	20-Sep-2023 11:00:04	[0m[1mmodule.rds.aws_db_instance.db: Still modifying... [id=db-YMBM3QDXXXX, 50s elapsed][0m[0m
build	20-Sep-2023 11:00:14	[0m[1mmodule.rds.aws_db_instance.db: Still modifying... [id=db-YMBM3QDXXXX, 1m0s elapsed][0m[0m
build	20-Sep-2023 11:00:24	[0m[1mmodule.rds.aws_db_instance.db: Still modifying... [id=db-YMBM3QDXXXX, 1m10s elapsed][0m[0m
build	20-Sep-2023 11:00:34	[0m[1mmodule.rds.aws_db_instance.db: Still modifying... [id=db-YMBM3QDXXXX, 1m20s elapsed][0m[0m
build	20-Sep-2023 11:00:35	[0m[1mmodule.rds.aws_db_instance.db: Modifications complete after 1m21s [id=db-YMBM3QDXXXX][0m

### Panic Output

There is no panic.

### Would you like to implement a fix?

No

**Comment by mgs255** [comment]
Also occurs with 5.17

**Comment by cg2v** [comment]
Rebooting isn't the same thing as having maintenance run. If you want the cert update to take effect before the next RDS maintenance cycle, you must use the `apply_immediately` argument in your aws_db_instance resource. (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#apply_immediately

**Comment by AlexAtkinson** [comment]
For the documentation, it would be supremely helpful if the arguments indicated which would be applied immediately regardless of the 'apply_immediately' setting, and which would be queued up for affect during the next maintenance window unless the apply_immediately setting was true. Though this is likely available in the pits of the aws docs...

For this bug itself, it also affects tf core 1.2.2, and aws provider 5.18.1.

**Comment by mehiltne** [comment]
This is likely to become a more pressing matter as AWS approaches its cert transition:

> Hello,
> 
> You are receiving this message because your AWS Account has one or more Amazon RDS, or Amazon Aurora database instances in the US-WEST-2 Region using an SSL/TLS Certificate that is expiring on August 22, 2024.
> 
> This is a follow-up notification for SSL/TLS CA certification expiration. If you believe you have already finished this work and still received this email it is likely because you created new instances using the 2019 CA. All newly created instances that don’t explicitly specify a different CA will use the 2019 CA until January 25, 2024 when the default will be switched to rds-ca-rsa2048-g1. For information on setting an account level CA override see the modify-certificates API documentation [1].
> 
> If your applications connect to these instances using the Secure Sockets Layer (SSL) or Transport Layer Security (TLS) protocol, you will need to take action before August 22, 2024 to prevent connectivity failures to your existing database instances. Even if you do not currently use SSL for your connections, you could still be affected if your databases server certificate expires, so we still recommend updating your CA.
> 
> ... message continues ...

It looks like reminders are going out monthly, with the most recent one hitting affected accounts last Friday (4 days ago).

**Comment by tbugfinder** [comment]
I'm facing the same issue.
As the "default CA" expires mid 2024, it would be beneficial to get a fix.

**Comment by LasaleFamine** [comment]
Is this still a bug or we can use the `ca_cert_identifier = "rds-ca-rsa2048-g1"` without dealing with dirty states on terraform?

**Comment by LasaleFamine** [comment]
So what's the best way to update the certificate on RDS in this situation? I mean, if we change the certificate with the CLI or from the AWS UI itself, will terraform see the change without broken the pipeline? This seems a bit critical, also because I suppose the certificate update will bring a downtime of the DB.

**Comment by Kammula280** [comment]
Hello
I'm on terraform-provider-aws version 4.27 and Terraform version 1.2.7

From what I have seen is when there is a change in `ca_cert_identifier` variable, Terraform apply works fine and queues it in pending modifications when `apply_immediately` is set to false which is working expected. Issue is that it's just not seen in AWS Console under pending modifications. If we use AWS CLI to list the pending modifications, we can see there is one when there is a change in `ca_cert_identifier`  variable.
`aws rds describe-db-instances --query 'DBInstances[*].{InstanceIdentifier:DBInstanceIdentifier, PendingModifiedValues:PendingModifiedValues}'`

To update `ca_cert_identifier`
1. Just apply Terraform with a change in  `ca_cert_identifier` and you can keep `apply_immediately = false`
2. Check if your certificate change is included in pending modifications using CLI command
`aws rds describe-db-instances --query 'DBInstances[*].{InstanceIdentifier:DBInstanceIdentifier, PendingModifiedValues:PendingModifiedValues}'`
3. Apply your pending modifications using below CLI command
`aws rds modify-db-instance --db-instance-identifier <dbname> --apply-immediately`
4. Check your database now which will have certificate with changed value.


Regarding downtime, it depends on the engine and engine version, you can use below CLI command with desired engine, engine version and check SupportsCertificateRotationWithoutRestart. If SupportsCertificateRotationWithoutRestart is true there will be no downtime.

`aws rds describe-db-engine-versions --engine postgres --engine-version 14.7 --query 'DBEngineVersions[*].SupportsCertificateRotationWithoutRestart'`

From now the terraform state will not have any issues and will match between actual and provided certificate.

Thank you!

**Comment by libsamek** [comment]
We are also experiencing a similar issue when setting up  DocumentDB from scratch.

No matter what we set `ca_cert_identifier` parameter, the default is being used and at the time of writing this is `rds-ca-rsa2048-g1`.

Using `apply_immediately=true` helps, but the initial DocumentDB configuration is started with default CA and after a while certificate is switched to the actual value of `ca_cert_identifier`. This works but it is not ideal ...

**Comment by TVAUGHN2** [comment]
Hi - for me, I confirmed it still applied during the normal maintenance window; however it DID NOT show up in the maintenance window in AWS. 

I ran one of the maintenance window tasks assuming that would apply the entire maintenance window, which did not work. But waiting until after the maintenance window showed the cert updated in AWS

 Which I believe is related to[ this issue on AWS. ](https://repost.aws/questions/QU7Qr4sLjXTrqsMRH35WyJ0Q/applying-new-ca-cert-during-maintenance-but-shows-no-changes-pending)

**Comment by YakDriver** [comment]
While we review this and see if there's anything we can do to improve the experience, you can use `aws_rds_certificate`  here as well:

```terraform
resource "aws_rds_certificate" "example" {
  certificate_identifier = "rds-ca-rsa2048-g1"
}

resource "aws_db_instance" "example" {
  ca_cert_identifier = aws_rds_certificate.example.certificate_identifier
}
```

**Comment by YakDriver** [comment]
I was not able to find a bug with updating certificates. We're planning to close this issue with #40278, that makes no changes but adds a test, for these reasons:

1. I'm adding a test that shows the correct updating behavior, changing `ca_cert_identifier` from `rds-ca-ecc384-g1` to `rds-ca-rsa2048-g1`.
2. This issue is stale because the cert discussed, `rds-ca-2019`, is no longer available, and there is no longer urgency to change that cert since people have already done that--the time has passed.
3. Some of the problem seemed to be related to an AWS issue that may have been resolved.
4. Additional complex behavior, such as applying a cert change immediately when `apply_immediate` is `false` is beyond the scope of a bug issue. We welcome a feature request to this effect, however, if it continues to be an issue.
