### ISSUE TITLE
[Bug]: aws_s3_bucket_versioning & aws_s3_bucket_policy - OperationAbort Error

### ISSUE THREAD

**Issue by kneekeel** [hashicorp/terraform-provider-aws#33552]
### Terraform Core Version

1.2.0

### AWS Provider Version

4.0.0

### Affected Resource(s)

*aws_s3_bucket_policy
*aws_s3_bucket_versioning

### Expected Behavior

We use an internal `s3-module` to simplify provisioning of S3 buckets. The module will provision this set of AWS S3 resources:
* aws_s3_bucket
* aws_s3_bucket_logging
* aws_s3_bucket_acl > depends_on `aws_s3_bucket_ownership_controls` and `aws_s3_bucket_public_access_block`
* aws_s3_bucket_ownership_controls
* aws_s3_bucket_versioning
* aws_s3_bucket_server_side_encryption_configuration
* aws_s3_bucket_public_access_block
* aws_s3_bucket_metric
* aws_s3_bucket_policy

There are no concurrent operations on the S3 bucket while Terraform is running. 

We expect there to be no dependency between the resources `aws_s3_bucket_policy` and `aws_s3_bucket_versioning`.

All S3 resources should be created without errors.

### Actual Behavior

There is an error when provisioning `aws_s3_bucket_policy` and `aws_s3_bucket_versioning` at the same time. We believe that this is due to the AWS S3 API calls `PutBucketVersioning` and `PutBucketPolicy` being executed concurrently on the S3 bucket, at Terraform runtime.

### Relevant Error/Panic Output Snippet

```shell
Error: creating S3 Bucket (cloudwatch-logs-shared-services-invh) Versioning: operation error S3: PutBucketVersioning, https response error StatusCode: 409, RequestID:, HostID:, api error OperationAborted: A conflicting conditional operation is currently in progress against this resource. Please try again.
with module.cloudwatch_log_bucket.aws_s3_bucket_versioning.this
on .terraform/modules/cloudwatch_log_bucket/bucket.tf line 50, in resource "aws_s3_bucket_versioning" "this":
resource "aws_s3_bucket_versioning" "this" {

Error: putting S3 Bucket (cloudwatch-logs-shared-services-invh) Policy: operation error S3: PutBucketPolicy, https response error StatusCode: 409, RequestID:, HostID:, api error OperationAborted: A conflicting conditional operation is currently in progress against this resource. Please try again.
with module.cloudwatch_log_bucket.aws_s3_bucket_policy.this
on .terraform/modules/cloudwatch_log_bucket/bucket.tf line 86, in resource "aws_s3_bucket_policy" "this":
resource "aws_s3_bucket_policy" "this" {
```

### Terraform Configuration Files

# s3-bucket-module

# main.tf
terraform {
  required_version = ">= 1.2.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.0"
    }
  }
}

data "aws_default_tags" "this" {}

# bucket.tf
locals {
  aws_account           = data.aws_default_tags.this.tags["Environment"]
  account_split         = split("-", local.aws_account)
  environment           = element(local.account_split, length(local.account_split) - 1)
  is_prod               = local.environment == "prod" || local.environment == "shared-services"
  bucket_name           = "${var.bucket_prefix}-${local.aws_account}"
  deny_http_policy_doc  = one(data.aws_iam_policy_document.deny_http)
  deny_http_policy_json = local.deny_http_policy_doc == null ? "" : local.deny_http_policy_doc.json
  source_policy_doc     = one(data.aws_iam_policy_document.json_policy_documents)
  source_policy_json    = local.source_policy_doc == null ? "" : local.source_policy_doc.json
}

resource "aws_s3_bucket" "this" {
  bucket = local.bucket_name

  tags = {
    Sensitivity = var.sensitivity,
    Name        = local.bucket_name
  }
}

resource "aws_s3_bucket_logging" "this" {
  bucket = aws_s3_bucket.this.id

  target_bucket = "s3-logs-${local.aws_account}"
  target_prefix = "${local.bucket_name}/"
}

resource "aws_s3_bucket_acl" "this" {
  count = var.sensitivity == "public" ? 1 : 0

  depends_on = [
    aws_s3_bucket_ownership_controls.this,
    aws_s3_bucket_public_access_block.this,
  ]

  bucket = aws_s3_bucket.this.id

  acl = "public-read"
}

resource "aws_s3_bucket_ownership_controls" "this" {
  bucket = aws_s3_bucket.this.id
  rule {
    object_ownership = var.sensitivity == "public" ? "BucketOwnerPreferred" : "BucketOwnerEnforced"
  }
}

resource "aws_s3_bucket_versioning" "this" {
  depends_on = [aws_s3_bucket_policy.this]

  bucket = aws_s3_bucket.this.id

  versioning_configuration {
    status = var.enable_versioning ? "Enabled" : "Disabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "this" {
  bucket = aws_s3_bucket.this.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = var.kms_key_arn == null ? "AES256" : "aws:kms"
      kms_master_key_id = var.kms_key_arn
    }
  }
}

resource "aws_s3_bucket_public_access_block" "this" {
  bucket = aws_s3_bucket.this.id

  block_public_acls       = var.sensitivity == "public" ? false : true
  block_public_policy     = var.sensitivity == "public" ? false : true
  ignore_public_acls      = var.sensitivity == "public" ? false : true
  restrict_public_buckets = var.sensitivity == "public" ? false : true
}

resource "aws_s3_bucket_metric" "this" {
  count  = var.disable_prod_metrics == false && local.is_prod ? 1 : 0
  bucket = local.bucket_name
  name   = "EntireBucket"
}

resource "aws_s3_bucket_policy" "this" {
  bucket = aws_s3_bucket.this.id
  policy = data.aws_iam_policy_document.this.json
}

data "aws_iam_policy_document" "this" {
  source_policy_documents = compact([
    local.deny_http_policy_json,
    local.source_policy_json
  ])
}

data "aws_iam_policy_document" "json_policy_documents" {
  count                   = length(var.json_policy_documents) == 0 ? 0 : 1
  source_policy_documents = var.json_policy_documents
}

data "aws_iam_policy_document" "deny_http" {
  count = var.allow_http_protocol ? 0 : 1
  statement {
    sid    = "DenyHttpProtocol"
    effect = "Deny"

    principals {
      type        = "AWS"
      identifiers = ["*"]
    }

    actions = ["s3:*"]

    resources = [
      aws_s3_bucket.this.arn,
      "${aws_s3_bucket.this.arn}/*",
    ]

    condition {
      test     = "Bool"
      variable = "aws:SecureTransport"
      values   = ["false"]
    }
  }
}

# variables.tf
variable "bucket_prefix" {
  description = "bucket prefix"
  type        = string
}

variable "enable_versioning" {
  description = "Enable file versioning for S3 bucket"
  type        = bool
  default     = true
}

variable "sensitivity" {
  description = "Currently used to determine whether or not a bucket should be have public access"
  type        = string
  default     = "restricted"

  validation {
    condition     = contains(["restricted", "confidential", "internal", "public"], var.sensitivity)
    error_message = "A value of restricted, confidential, internal, or public is required."
  }
}

variable "disable_prod_metrics" {
  type        = bool
  description = "Set to true to disable default metrics on production environemnts"
  default     = false
}

variable "kms_key_arn" {
  type        = string
  description = "KMS Key for server side encryption (Optional)"

  default = null
}

variable "allow_http_protocol" {
  type        = bool
  description = "Allow HTTP protocol to be used with bucket"
  default     = false
}

variable "json_policy_documents" {
  type        = list(string)
  description = "List of IAM policy documents that are merged together into the exported document."
  default     = []
  nullable    = false
}

### Steps to Reproduce

* set-up the s3-bucket-module as an inline module
* execute `terraform apply` using the inline module (attached is an example)

# main.tf
terraform {
  required_version = "~> 1.2"

  required_providers {
    aws = {
      version = "~> 5.1"
      source  = "hashicorp/aws"
    }
  }
}

provider "aws" {
  region = "us-east-1"
  default_tags {
    tags = {
      Component   = "s3-bucket-module-race-condition"
      Environment = "dev"
      Owner       = "cloud"
    }
  }
}

data "aws_caller_identity" "current" {}

module "race_condition_bucket" {
  source        = ./<directory_name>

  bucket_prefix = "cloud-s3-module-race-condition-logs"
  json_policy_documents = [
    data.aws_iam_policy_document.race_condition.json
  ]
}

data "aws_iam_policy_document" "race_condition" {
  statement {
    sid       = "AllowCloudwatchGetBucketAcl"
    actions   = ["s3:GetBucketAcl"]
    effect    = "Allow"
    resources = ["arn:aws:s3:::cloud-s3-module-race-condition-logs-dev-invh"]
    principals {
      identifiers = ["logs.us-east-1.amazonaws.com"]
      type        = "Service"
    }
    condition {
      test     = "StringEquals"
      values   = [data.aws_caller_identity.current.account_id]
      variable = "aws:SourceAccount"
    }
    condition {
      test     = "ArnLike"
      values   = ["arn:aws:logs:us-east-1:${data.aws_caller_identity.current.account_id}:log-group:*"]
      variable = "aws:SourceArn"
    }
  }
}

* execute `terraform destroy`

You may see the error in either `apply` or `destroy` executions.

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@kneekeel Thanks for raising this issue.
It has already been noticed in #33531. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
