### ISSUE TITLE
[Bug]: Error creating aws_medialive_channel input attachment failover: setting AWS Elemental MediaLive Channel (*******): Invalid address to set: []string{"input_attachments", "1", "automatic_input_failover_settings", "0", "failover_conditions"}

### ISSUE THREAD

**Issue by lucas3900** [hashicorp/terraform-provider-aws#33550]
### Terraform Core Version

1.5.7, 1.5.0

### AWS Provider Version

5.17.0, 5.16.0

### Affected Resource(s)

aws_medialive_channel

### Expected Behavior

Adding an `automatic_input_failover_settings` block should create an automatic failover with no errors

### Actual Behavior

`terraform apply` error out with error: 

`ERROR: setting AWS Elemental MediaLive Channel (*****): Invalid address to set: []string{"input_attachments", "1", "automatic_input_failover_settings", "0", "failover_conditions"}`

Going over the UI. I can see that the failover condition was created, but created incorrectly. After the apply all terraform operations  (apply, plan, init, destroy) error out with the above error.

### Relevant Error/Panic Output Snippet

```shell
ERROR: setting AWS Elemental MediaLive Channel (*****): Invalid address to set: []string{"input_attachments", "1", "automatic_input_failover_settings", "0", "failover_conditions"}
```

### Terraform Configuration Files
```tf
resource "aws_medialive_channel" "test_channel" {
  name          = "test_channel"
  channel_class = "SINGLE_PIPELINE"
  role_arn      = aws_iam_role.medialive_iam_role.arn
  tags = {

  }

  destinations {
    id = "dest-full"
    media_package_settings {
      channel_id = aws_media_package_channel.test_channel.id
    }
  }
  destinations {
    id = "dest-ambient"
    settings {
      password_param = aws_ssm_parameter.ssm_ambient.name
      url = aws_media_package_channel.test_channel_ambient.hls_ingest[0].ingest_endpoints[0].url
      username = aws_media_package_channel.test_channel_ambient.hls_ingest[0].ingest_endpoints[0].username
    }
  }
  destinations {
    id = "dest-pa"
    settings {
      password_param = aws_ssm_parameter.ssm_pa.name
      url = aws_media_package_channel.test_channel_pa.hls_ingest[0].ingest_endpoints[0].url
      username = aws_media_package_channel.test_channel_pa.hls_ingest[0].ingest_endpoints[0].username
    }
  }
  destinations {
    id = "dest-pa-ambient"
    settings {
      password_param = aws_ssm_parameter.ssm_pa_ambient.name
      url = aws_media_package_channel.test_channel_pa_ambient.hls_ingest[0].ingest_endpoints[0].url
      username = aws_media_package_channel.test_channel_pa_ambient.hls_ingest[0].ingest_endpoints[0].username
    }
  }


  input_specification {
    codec            = "HEVC"
    input_resolution = "HD"
    maximum_bitrate  = "MAX_20_MBPS"
  }

  # primary input
  input_attachments {
    input_attachment_name = "input_attachment"
    input_id              = aws_medialive_input.test_input.id
    automatic_input_failover_settings {
      secondary_input_id    = aws_medialive_input.test_input_b.id
      input_preference      = "PRIMARY_INPUT_PREFERRED"
      error_clear_time_msec = 30000
      failover_condition {
        failover_condition_settings {
          video_black_settings {
            black_detect_threshold = 0.5
            video_black_threshold_msec = 3000
          }
        }
      }
    } # input failover
   ... rest of attatchment
   }
   input_attachments {
    input_attachment_name = "test_input_attachment_b"
    input_id              = aws_medialive_input.test_input_b.id
   # no failover
   ... rest of attatchment
  }
```

### Steps to Reproduce

1. `terraform apply`
After the terraform apply, all main terraform operations (apply, plan, init, destroy) error out

### Debug Output

ERROR: setting AWS Elemental MediaLive Channel (*****): Invalid address to set: []string{"input_attachments", "1", "automatic_input_failover_settings", "0", "failover_conditions"}

### Important Factoids

The failover incorrectly gets created in my medialive channel as an input loss failover condition. Only way to resolve this is to manually disable the automatic failover in the AWS UI, and then remove the failover code from the IaC.

Additionally, I tried just enabling the automatic failover without any conditions:
```tf
automatic_input_failover_settings {
      secondary_input_id    = aws_medialive_input.input_example.id
      input_preference      = "PRIMARY_INPUT_PREFERRED"
      error_clear_time_msec = 3000
      }
} # input failover
```

Finally, the secondary input I am trying to failover is attached properly. If I take out the automatic failover, everything works as expected

### Would you like to implement a fix?

No

**Comment by evelynhathaway** [comment]
I am also experiencing this error. I've tried importing a channel with failover and I've tried creating from within Terraform.

`failover_condition` is required in the Terraform schema:
https://github.com/hashicorp/terraform-provider-aws/blob/57f32fbb187dc8da7e495be24c03953fd014461d/internal/service/medialive/channel.go#L168C25-L168C25

`failover_conditions` is used when communicating with AWS:

https://github.com/hashicorp/terraform-provider-aws/blob/57f32fbb187dc8da7e495be24c03953fd014461d/internal/service/medialive/channel.go#L1622

https://github.com/hashicorp/terraform-provider-aws/blob/57f32fbb187dc8da7e495be24c03953fd014461d/internal/service/medialive/channel.go#L2052

I believe the documentation issue that this discrepancy is related (#33407). The open PR #33410 does not fix the issue, only switches the documentation from one to another. The field will still not work.
