### ISSUE TITLE
[Docs]: Missing documentation for db_instance_identifier attribute

### ISSUE THREAD

**Issue by pkhunte** [hashicorp/terraform-provider-aws#33555]
### Documentation Link

https://registry.terraform.io/providers/-/aws/5.17.0/docs

### Description

This documentation is missing information about the db_instance_identifier attribute.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @pkhunte 👋 Thank you for taking the time to raise this! Can you give us a link to the resource/data source that you're referencing?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
