### ISSUE TITLE
[Bug]: aws_vpc_ipam_pool_cidr gets replaces when imported first

### ISSUE THREAD

**Issue by litepl** [hashicorp/terraform-provider-aws#33564]
### Terraform Core Version

1.5.1

### AWS Provider Version

5.17.0

### Affected Resource(s)

aws_vpc_ipam_pool_cidr

### Expected Behavior

No Changes on apply when aws_vpc_ipam_pool_cidr imported previously

### Actual Behavior

```shell
terraform import 'aws_vpc_ipam_pool_cidr.this' 10.1.128.0/17_ipam-pool-xxx
```

```
Terraform will perform the following actions:

  # aws_vpc_ipam_pool_cidr.this[0] must be replaced
-/+ resource "aws_vpc_ipam_pool_cidr" "this" {
      ~ cidr              = "10.1.128.0/17" # forces replacement -> (known after apply) # forces replacement
      ~ id                = "10.1.128.0/17_ipam-pool-xxx" -> (known after apply)
      ~ ipam_pool_cidr_id = "ipam-pool-cidr-yyy" -> (known after apply)
        # (1 unchanged attribute hidden)
    }
```

### Terraform Configuration Files

not needed

### Steps to Reproduce

- Create aws_vpc_ipam_pool_cidr definition
- terraform import 'aws_vpc_ipam_pool_cidr.this[0]' 10.1.128.0/17_ipam-pool-xxx
- terraform plan/apply

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @litepl 👋 Thank you for taking the time to raise this! Can you supply a sample Terraform configuration that can be used to reproduce the issue?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
