### ISSUE TITLE
[Enhancement]: provider: Allow SSO endpoint to be configured

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#33576]
### Description

Users can [set custom endpoints](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/custom-service-endpoints) for services. However, that does not currently include SSO but probably should. This would allow users more configuration options. Also, if AWS [gets the SSO URL wrong for FIPS](https://github.com/hashicorp/terraform-provider-aws/issues/29350), for instance, this would allow users a workaround.

### Affected Resource(s) and/or Data Source(s)

* provider

### Potential Terraform Configuration

```terraform
provider "aws" {
  endpoints {
    sso = "http://localhost:4569"
  }
}
```

### References

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/custom-service-endpoints
* #29350
* aws/aws-sdk-go-v2#2166

### Would you like to implement a fix?

None

**Comment by gdavison** [comment]
Closed by #35551
