### ISSUE TITLE
[Bug]: aws_lb_listener ignores the certificate_arn

### ISSUE THREAD

**Issue by hashidave** [hashicorp/terraform-provider-aws#33573]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.17.0

### Affected Resource(s)

aws_lb_listener

### Expected Behavior

when certificate_arn is specified, I expect that it will be part of the plan & will be passed to aws when provisioning the load-balancer.

### Actual Behavior

Terraform fails to provision the load balancer and returns an error stating that a certificate ARN is required.  The plan shows that the certficate_arn has been omitted.  
See screenshots.

![image](https://github.com/hashicorp/terraform-provider-aws/assets/106760442/a5c6f876-939c-4b80-ac35-312348586088)

![image](https://github.com/hashicorp/terraform-provider-aws/assets/106760442/f72ef351-5b62-43f0-bc68-a2bb38e6d93d)

Note:  It works fine if I use the 5.6.2 provider.  I haven't tested all the providers between 5.6.2 and 5.17.0

### Terraform Configuration Files

The specific code is on line 44
https://github.com/hashicorp-modules/terraform-aws-ent-prereq-ingress/blob/main/main.tf

It's being deployed from this repo: https://github.com/hashicorp-modules/terraform-aws-tfe-prerequisites/tree/main/examples/public-tfe-fdo-single-site-aurora-alb

### Steps to Reproduce

terraform apply (after setting variables appropriate to your environment)

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @hashidave 👋 Thank you for taking the time to raise this! On a quick look, I didn't see any major changes to the `aws_lb_listener` resource that directly impacted the `certificate_arn` attribute in recent times, but I'll leave it to someone on the team to take a more detailed look. In the meantime, are you able to supply debug logs (redacted as needed)?

**Comment by justinretzolk** [comment]
Since we haven't heard back, and based on changes to the linked repository, it looks like this may have been configuration related, so I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
