### ISSUE TITLE
[Bug]: new provider version not published on terraform registry

### ISSUE THREAD

**Issue by dhohengassner** [hashicorp/terraform-provider-aws#33588]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.17.0

### Affected Resource(s)

It seems like the provider version 5.18.0 containing some important S3 fixes is not published yet on terraform registry.

https://registry.terraform.io/providers/hashicorp/aws/latest

Did there something happen during the sync/upload?

Thanks a lot!

### Expected Behavior

latest available version of provider can be used

### Actual Behavior

version 5.18.0 cannot be used since it is not completely released yet

### Relevant Error/Panic Output Snippet

```shell
│ Could not retrieve the list of available versions for provider
│ hashicorp/aws: no available releases match the given constraints >= 5.0.0,
│ 5.18.0
```

### Terraform Configuration Files

```shell
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
     version = "5.18.0"
    }
  }
}
```

### Steps to Reproduce

terraform init

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Hmm. The release GHA was successful: https://github.com/hashicorp/terraform-provider-aws/actions/runs/6267061933, and the binaries are in https://releases.hashicorp.com/terraform-provider-aws/5.18.0/.
We'll investigate.
@dhohengassner Thanks for bringing this to our attention 👏.

**Comment by breathingdust** [comment]
Just an update that the registry team is actively investigating. Hopefully we'll have a resolution for you soon.

**Comment by vampirechicken** [comment]
Need the S3 fixes in 5.18. Any updates?

**Comment by el-chazmo** [comment]
> Need the S3 fixes in 5.18. Any updates?

Until this is resolved, you could always just block version v5.17 for now
```terraform
required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.0, != 5.17.0"
    }
  }
```

**Comment by vampirechicken** [comment]
> > Need the S3 fixes in 5.18. Any updates?
> 
> Until this is resolved, you could always just block version v5.17 for now
> 
> ```terraform
> required_providers {
>     aws = {
>       source  = "hashicorp/aws"
>       version = ">= 4.0, != 5.17.0"
>     }
>   }
> ```

My s3 module is consumed by 12 other modules, plus its own tests, and literally countless enterprise projects that consume those 13. Projects that would have to update their code to change their required_providers or to use my new s3 version, and then revert again after this issue is fixed.

The workaround on my side is to just run the apply/destroy a second time.  But I'll have to explain that to people as well. 

The workaround on Hashicorp's end is to manually publish an updated AWS provider versions document, while they fix their automations.

**Comment by danhlee329** [comment]
ETA for provider release? Need to have this in sooner rather than later per https://github.com/hashicorp/terraform-provider-aws/issues/33333

**Comment by jar-b** [comment]
We've addressed the documentation issues on the provider side and are still working with our registry team to resolve the downstream publishing issues. We'll update this issue as soon as we have more information.

**Comment by danhlee329** [comment]
> ETA for provider release? Need to have this in sooner rather than later per #33333

Was able to confirm that the `v5.18.1` is good on my side, thanks!

**Comment by jar-b** [comment]
`v5.18.0` and `v5.18.1` have both been published to the registry. Thank you for your patience!
