### ISSUE TITLE
[Bug]: aws_opensearchserverless_vpc_endpoint fails when changing the 'name'

### ISSUE THREAD

**Issue by baromojm** [hashicorp/terraform-provider-aws#33603]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.17.0

### Affected Resource(s)

aws_opensearchserverless_vpc_endpoint

### Expected Behavior

After creating the resource, changing the 'name' arguments should change the already created resource name

### Actual Behavior

The resource isn't renamed and this error is shown:
Error: Provider produced inconsistent result after apply

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.opensearch.aws_opensearchserverless_vpc_endpoint.example_vpc_endpoint[0], provider
│ "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected new value: .name: was
│ cty.StringVal("dev-vpc-270b7759639ef8150-vpc-ep"), but now cty.StringVal("dev-abcsdftgb-example-vpc-ep").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Terraform Configuration Files

a) Created an VPC endpoint (this works fine)
```
resource "aws_opensearchserverless_vpc_endpoint" "example_vpc_endpoint" {
  count = var.creatable ? 1 : 0

  name               = "dev-abcsdftgb-example-vpc-ep"
  vpc_id             = var.vpc_id
  subnet_ids         = var.subnets_ids
  security_group_ids = [aws_security_group.security_group[0].id]
}
```

b)  Tried to change the name of the VPC endpoint (it should have renamed the resource)
```
resource "aws_opensearchserverless_vpc_endpoint" "example_vpc_endpoint" {
  count = var.creatable ? 1 : 0

  name               = "dev-vpc-270b7759639ef8150-vpc-ep"
  vpc_id             = var.vpc_id
  subnet_ids         = var.subnets_ids
  security_group_ids = [aws_security_group.security_group[0].id]
}
```

### Steps to Reproduce

Create the aws_opensearchserverless_vpc_endpoint resource with any value for argument 'name'

Change the value of argument 'name' to something else, and apply again

The 'Provider produced inconsistent result after apply' error appears

### Important Factoids

No

### Would you like to implement a fix?

No

**Comment by wernerdiers** [comment]
I've just run into this bug. Temporary workaround is to manually update the name and re-run the terraform excecution.
