### ISSUE TITLE
[Bug]: `aws_datasync_location_fsx_ontap_file_system` doesn't recognize `protocol.smb.username` and `protocol.smb.password`

### ISSUE THREAD

**Issue by kylelee24** [hashicorp/terraform-provider-aws#33601]
### Terraform Core Version

v1.5.5

### AWS Provider Version

5.17.0

### Affected Resource(s)

* aws_datasync_location_fsx_ontap_file_system

### Expected Behavior

Creates the AWS DataSync Location for an FSx ONTAP File System using the SMB protocol configured with the domain, username, and password to authenticate to the SMB share on the SVM.

### Actual Behavior

No errors with validation in the plan, but on apply I get a validation from the API. My guess is that the provider is not passing the information to the API properly. 

### Relevant Error/Panic Output Snippet

```shell
aws_datasync_location_fsx_ontap_file_system.shrstor_testing1: Creating...
╷
│ Error: creating DataSync Location FSx for NetApp ONTAP File System: InvalidParameter: 2 validation error(s) found.
│ - missing required field, CreateLocationFsxOntapInput.Protocol.SMB.Password.
│ - missing required field, CreateLocationFsxOntapInput.Protocol.SMB.User.
│
│
│   with aws_datasync_location_fsx_ontap_file_system.shrstor_testing1,
│   on shared-storage.tf line 584, in resource "aws_datasync_location_fsx_ontap_file_system" "shrstor_testing1":
│  584: resource "aws_datasync_location_fsx_ontap_file_system" "shrstor_testing1" {
│
╵
```

### Terraform Configuration Files

```
resource "aws_datasync_location_fsx_ontap_file_system" "smb" {
  security_group_arns         = [aws_security_group.this.arn]
  storage_virtual_machine_arn = aws_fsx_ontap_storage_virtual_machine.this.arn
  subdirectory                = "/vol1/storage/"
  protocol {
    smb {
      domain = "aws.mydomain.com"
      mount_options {
        version = "SMB3"
      }
      password = "MyPassw0rd1"
      user     = "datasyncsa"
    }
  }
}
```

### Steps to Reproduce

Try to create a `aws_datasync_location_fsx_ontap_file_system` resource with the protocol set to smb.

### Would you like to implement a fix?

None

**Comment by kylelee24** [comment]
I understand I didn't provide the complete Terraform code, as i'll need some time to isolate just the components needed to reproduce. 

I still wanted to get it in as I believe the issue will be clear to the owners and easy to reproduce.

**Comment by acwwat** [comment]
Just an educated guess from comparing with other similar functions, but the domain, password, and user attributes are perhaps not passed into the model in the `expandSMB` function. This might also have affected the `nfs` block specifically the `version` attribute, but it's not noticeable because the attribute is optional. This is also why `smb` doesn't complain about the `domain` attribute.

https://github.com/hashicorp/terraform-provider-aws/blob/ceea611bf47c2f69ab5b4ebf728759db7e9d9dbf/internal/service/datasync/common_fsx_protocol_functions.go#L59-L71
