### ISSUE TITLE
[Docs]: aws_wafv2_rule_group

### ISSUE THREAD

**Issue by shaaran1** [hashicorp/terraform-provider-aws#33626]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_rule_group#regex-match-statement

### Description

[Regex Match Statement](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_rule_group#regex-match-statement)

[regex_string] - (Required) The string representing the regular expression. Minimum of 1 and maximum of 512 characters. 

But the AWS Limit documentation - https://docs.aws.amazon.com/waf/latest/developerguide/limits.html mentions "Maximum number of characters in a string match statement" is set to 200.

When I try to implement, It doesn't allow more than 200 characters for each regex pattern.

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
For reference, The AWS API indicates a technical maximum length of 512 matching the schema in Terraform: https://docs.aws.amazon.com/waf/latest/APIReference/API_RegexMatchStatement.html

However the logical maximum length is indeed 200 per the unchangeable quota limit per the documentation and the Service Quotas console:

![image](https://github.com/hashicorp/terraform-provider-aws/assets/5210117/61c1454c-14c2-47c4-bd9c-96b3d6d85a13)

I am also curious as to how this situation should be handled. I can understand the code using 512 for the maximum length following AWS APIs, but in practice 200 is the right number. Maybe it should just be mentioned in the document but not adjusted in the code?
