### ISSUE TITLE
[Enhancement]: Support Grafana version update in place

### ISSUE THREAD

**Issue by gingersnapz** [hashicorp/terraform-provider-aws#33638]
### Description

Based on recent AWS announcements, upgrading in place is supported from 8.4 to 9.4 without requiring a destroy:

[https://aws.amazon.com/about-aws/whats-new/2023/07/amazon-managed-grafana-in-place-update-version-9-4/](https://aws.amazon.com/about-aws/whats-new/2023/07/amazon-managed-grafana-in-place-update-version-9-4/)

AWS GO SDK v1.44.303 was updated to include the new change to allow update in place.

### Affected Resource(s) and/or Data Source(s)

aws_grafana_workspace

### References

[https://aws.amazon.com/about-aws/whats-new/2023/07/amazon-managed-grafana-in-place-update-version-9-4/](https://aws.amazon.com/about-aws/whats-new/2023/07/amazon-managed-grafana-in-place-update-version-9-4/)

AWS SDK Go Release Notes for v1.44.303 to add new refs for 'UpdateWorkspaceConfigurationRequest$grafanaVersion':
[https://github.com/aws/aws-sdk-go/pull/4918/files#diff-6c62629e5c3975d4f56274671eb286df04ae37246226f667e30aad152df560a5R269](https://github.com/aws/aws-sdk-go/pull/4918/files#diff-6c62629e5c3975d4f56274671eb286df04ae37246226f667e30aad152df560a5R269)

### Would you like to implement a fix?

None

**Comment by autotune** [comment]
@gingersnapz when I do a version update it updates in place. Where are you seeing it do a destroy?

**Comment by justinretzolk** [comment]
Since we weren't able to reproduce this, and haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
