### ISSUE TITLE
[Enhancement]: Support region for target_table argument in aws_glue_catalog_table

### ISSUE THREAD

**Issue by raman-aro** [hashicorp/terraform-provider-aws#33639]
### Description

Per the following issue, can region be added to the target_table argument for aws_glue_catalog_table as well?
https://github.com/hashicorp/terraform-provider-aws/issues/32099#issue-1764919771

The fix added it to aws_glue_catalog_database but this doesn't address the case when creating resource links to specific tables rather than whole databases. 

### Affected Resource(s) and/or Data Source(s)

aws_glue_catalog_table

### Potential Terraform Configuration

```terraform
resource "aws_lakeformation_permissions" "lf_grant_on_target" {

  principal = local.arn
  permissions = ["SELECT"]

  table {
    region = "us-east-2"
    catalog_id = local.catalog
    database_name = local.database
    name = local.table
  }
}
```

### References

https://github.com/hashicorp/terraform-provider-aws/issues/32099

### Would you like to implement a fix?

No

**Comment by autotune** [comment]
I am working on this.

**Comment by autotune** [comment]
While this is available in the AWS docs: https://docs.aws.amazon.com/glue/latest/webapi/API_TableIdentifier.html#Glue-Type-TableIdentifier-Region

This is not a supported argument in the go sdk: https://github.com/aws/aws-sdk-go/blob/737322b8f8b54fc78d076334d1e433e2e5f2993d/service/lakeformation/api.go#L13775

When attempting to add it in I get an idempotent error where it constantly tries to force a new replacement. I'll submit what I have so far as a WIP but I'm not sure that this is, in fact, supported.
