### ISSUE TITLE
Please publish 5.18.0 to the registry

### ISSUE THREAD

**Issue by venkatamutyala** [hashicorp/terraform-provider-aws#33634]
I am expecting to see 5.18.0 in the official terraform registry.

### Actual Behavior

The official registry only has 5.17.0 

<img width="504" alt="image" src="https://github.com/hashicorp/terraform-provider-aws/assets/6570292/05e99de6-77af-4270-8c4d-03d1f954e283">

ref: https://registry.terraform.io/providers/hashicorp/aws/latest/docs

**Comment by ewbankkit** [comment]
@venkatamutyala Thanks for raising this issue.
It has already been noticed in #33588. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
