### ISSUE TITLE
[Bug]: Data Source aws_s3_object - Unable to retrieve User Defined metadata

### ISSUE THREAD

**Issue by andremachado94** [hashicorp/terraform-provider-aws#33648]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.17.0,5.18.0,5.18.1

### Affected Resource(s)

* aws_s3_object

### Expected Behavior

We are using the data source `aws_s3_object` to retrieve a User Defined metadata key-value pair:

```
data "aws_s3_object" "package" {
  bucket = var.s3_bucket
  key    = var.s3_key
}
```

Key name: `Hash` (in the object metadata is set as `x-amz-meta-hash`)

**Expected behaviour**:

Calling `data.aws_s3_object.package.metadata.Hash` should return the value of the key `x-amz-meta-hash`

### Actual Behavior

Fails with the following exception:

```
╷
│ Error: Missing map element
│ 
│   on .terraform/modules/utils_sfn.common_lambdas/main.tf line 18, in resource "aws_lambda_function" "lambda":
│   18:   source_code_hash = data.aws_s3_object.package.metadata.Hash
│     ├────────────────
│     │ data.aws_s3_object.package.metadata is map of string with 1 element
│ 
│ This map does not have an element with the key "Hash".
╵

```

### Terraform Configuration Files

```
data "aws_s3_object" "package" {
  bucket = var.s3_bucket
  key    = var.s3_key
}

resource "aws_lambda_function" "lambda" {
  # ...
  s3_bucket        = var.s3_bucket
  s3_key           = var.s3_key
  source_code_hash = data.aws_s3_object.package.metadata.Hash
  # ...
}
```

### Steps to Reproduce

Using provider >= v5.17.0:

1. Create an s3 object wit the metadata tag `x-amz-meta-hash`
2. Create a tf module that uses the data source `aws_s3_object` on that s3 object and with an output block that returns `data.aws_s3_object.<whatever_name_you_gave_it>.metadata.Hash`

### Important Factoids

This was working on `v5.16.2`. The breaking change occurred on the release `v5.17.0`. Maybe from https://github.com/hashicorp/terraform-provider-aws/issues/33358 ?

### References

https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.17.0
https://github.com/hashicorp/terraform-provider-aws/issues/33358

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@andremachado94 Thanks for raising this issue 👏.
I assume that the corresponding S3 object was created/modified outside of Terraform as the `aws_s3_object` resource allows only lowercase metadata keys?

**Comment by andremachado94** [comment]
Hi @ewbankkit !

Yes, it's done outside of terraform (when creating a new release with GH actions). Like this:

```
aws s3 cp $(ZIP_NAME) s3://$(BUCKET_NAME)/$(ZIP_NAME) --metadata hash="$(shell openssl dgst -binary -sha256 $(ZIP_NAME) | openssl base64)"
```

**Comment by ewbankkit** [comment]
The cause is that the AWS SDK for Go v2 [`HeadObject` response](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/s3#HeadObjectOutput) normalizes all keys to lowercase.
As this is a breaking change I will see if there's a way to change this.

**Comment by andremachado94** [comment]
Ok, thanks for the help!
