### ISSUE TITLE
[Enhancement]: aws_efs_file _system resource to support elastic mode option in throught put mode

### ISSUE THREAD

**Issue by skkc2** [hashicorp/terraform-provider-aws#33649]
### Description

Hi All,

At the moment EFS file system resource only supports or take two types of option for throughput mode variable those are Bursting and provisioned. AWS has one more option called elastic which is currently not being supported by the aws_efs_file_system resource module. Please correct me if this option is already available in a different version or else could you please add this feature as well.

Thank you

### Affected Resource(s) and/or Data Source(s)

I've updated the throughput varaible value to elastic and error out as
 Error: expected throughput_mode to be one of [bursting provisioned], got elastic

### Potential Terraform Configuration

```terraform
Terraform v1.0.7
```

### Would you like to implement a fix?

None

**Comment by longwave** [comment]
This was added in #28050

**Comment by justinretzolk** [comment]
Hey @skkc2 👋 Thank you for taking the time to raise this! It looks like this functionality was added in AWS Provider version 4.42.0 via #28054. With that in mind, I'll close this issue. If you have further issues after upgrading, please feel free to open a new issue and link to this one for context.
