### ISSUE TITLE
aws_route is throwing an error on the transit gateway id while existing

### ISSUE THREAD

**Issue by yannickvranckx** [hashicorp/terraform-provider-aws#33650]
### Description

Using the terraform resource "aws_route" to add a route to a route table, it says the transit gateway attachment does not exist, while clearly being active in the account.

Code used:
```
resource "aws_route" "tgw_route" {
  route_table_id         = module.vpc.intra_route_table_ids.0
  destination_cidr_block = "0.0.0.0/0"
  transit_gateway_id     = aws_ec2_transit_gateway_vpc_attachment.sandbox.id
  depends_on             = [module.vpc.vpc_id, aws_ec2_transit_gateway_vpc_attachment.sandbox]
}
```

It will just get stuck in "Still Creating" for about 2-3 minutes and then it will state that the attachment ID does not exist. While i can see it in the account and being active, using the AWS Console it just works.

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
@yannickvranckx It looks like you are passing the TGW attachment ID instead of the TGW ID into `transit_gateway_id`. Passing in `aws_ec2_transit_gateway_vpc_attachment.sandbox.transit_gateway_id` should address the issue.

**Comment by yannickvranckx** [comment]
> @yannickvranckx It looks like you are passing the TGW attachment ID instead of the TGW ID into `transit_gateway_id`. Passing in `aws_ec2_transit_gateway_vpc_attachment.sandbox.transit_gateway_id` should address the issue.

This was the issue, can't believe I missed that one

**Comment by yannickvranckx** [comment]
The issue was the TGW ID being the attachment ID.
