### ISSUE TITLE
[Enhancement]: resource "aws_directory_service_directory" needs custom-users to be created by terraform 

### ISSUE THREAD

**Issue by mayank0202** [hashicorp/terraform-provider-aws#33739]
### Description

As i have created a terraform module called aws workspaces with directories by following the documentation. Here is the github public repo link

https://github.com/sourcefuse/arc-terraform-workspace#important-note

and when you will open this link you will see a section of important note and where i have mentioned the points of using this module. so as we use terraform to get rid of manual work but when directory gets created in aws then it doesnt create workspace and gives error that user doesnt exist so if we give Admin or Administrator then it gets created but if i have to give custom-user-name like mayank.sharma then for that i need to create user manually after directory gets created from terraform and then re-apply terraform apply to create workspace. so in my module i have specified that first you have to keep username empty so that no error will come and directory and other stuff will get created and then go to aws workspaces and create a user by choosing directory and then re run terraform apply to get workspace created.

So the only problem here is manual work of creating a user by going in workspace and by this we have to perform terraform apply two times which is not a good practice. so i really need a solution for this

For more information refer this and read out the points where i mentioned manual work

https://github.com/sourcefuse/arc-terraform-workspace#important-note

 `user_name `  attribute gets failed because its says that directory has no custom-user in it . By default it only takes Admin , Administrators etc etc which are defaults but for custom username i need to create user manually and then this workspace gets created .

So we should create custom users via directory creation 

### Affected Resource(s) and/or Data Source(s)

aws_workspaces_workspace

### Potential Terraform Configuration

```terraform
resource "aws_workspaces_workspace" "workspace" {
  for_each     = var.user_names
  directory_id = var.directory_type == "MicrosoftAD" ? aws_directory_service_directory.microsoftAD[0].id : aws_directory_service_directory.ADConnector[0].id
  bundle_id    = var.bundle_id != null ? var.bundle_id : data.aws_workspaces_bundle.bundle.id
  user_name    = each.key

  root_volume_encryption_enabled = true
  user_volume_encryption_enabled = true
  volume_encryption_key          = var.volume_encryption_key

  workspace_properties {
    compute_type_name                         = var.workspace_properties.compute_type_name
    user_volume_size_gib                      = var.workspace_properties.user_volume_size_gib
    root_volume_size_gib                      = var.workspace_properties.root_volume_size_gib
    running_mode                              = var.workspace_properties.running_mode
    running_mode_auto_stop_timeout_in_minutes = var.workspace_properties.running_mode_auto_stop_timeout_in_minutes
  }


  tags = var.tags
  depends_on = [
    aws_directory_service_directory.microsoftAD,
    aws_workspaces_directory.directory_microsoftAD
  ]
}
```

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/directory_service_directory

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/workspaces_workspace

### Would you like to implement a fix?

None

**Comment by nnsense** [comment]
I'm not involved into the terraform AWS provider, but I would assume adding this would be out of scope for the provider. [There's an (experimental) AD provider by Hashicorp](https://registry.terraform.io/providers/hashicorp/ad/latest) if you want to give it a try. I assume you would still need to run two deployments, since terraform can't read the AD config until it's deployed. Also, you would end up with the problem of having terraform deploying the WS users and another tool to maintain them.

A common workaround is to deploy a first workspace for the `Administrator` user, which is included into any AD deployment, and then use that workspace to manage the additional users. You can then add them to your `user_names` list and deploy all the additional Workspaces you need.

**Comment by mayank0202** [comment]
> I'm not involved into the terraform AWS provider, but I would assume adding this would be out of scope for the provider. [There's an (experimental) AD provider by Hashicorp](https://registry.terraform.io/providers/hashicorp/ad/latest) if you want to give it a try. I assume you would still need to run two deployments, since terraform can't read the AD config until it's deployed. Also, you would end up with the problem of having terraform deploying the WS users and another tool to maintain them.
> 
> A common workaround is to deploy a first workspace for the `Administrator` user, which is included into any AD deployment, and then use that workspace to manage the additional users. You can then add them to your `user_names` list and deploy all the additional Workspaces you need.

Thanks for your reply @nnsense  . In the example folder , we have specified that when `user_names` is null no workspace will get created and rest of the stuff will get created like directory and so on and then we create users manually and specify the users in `user_names` and re-deploy and then this time workspaces gets created via terraform . So  i was just  thinking to get rid of this two times deployment

**Comment by nnsense** [comment]
Yeah, I hear you, I would love to see this feature too, maybe hashicorp will just merge the two providers at some point, who knows? :) Maybe you could use terragrunt, to get the job done? 3 modules, the one for AD, the second for creating the users, the third to deploy WS? Terragrunt can run the 3 modules separately for you, without the need of running each manually, so that your AD provider will find the directory already running to get its parameters and use them to deploy the other modules. Just an idea..

**Comment by justinretzolk** [comment]
Hey y'all 👋 Thank you for taking the time to raise this, and for the great discussion above! Given that it looks like the conclusion here is that this is outside of the scope of the provider, I'm going to go ahead and close this one out. If you feel I've done this in error, please feel free to open a new issue and link back to this one for context, and we can continue the conversation!
