### ISSUE TITLE
[Bug]: column_index and row_index cannot be set to 0

### ISSUE THREAD

**Issue by jackarmorgie** [hashicorp/terraform-provider-aws#33756]
### Terraform Core Version

1.0.0

### AWS Provider Version

5.17.0

### Affected Resource(s)

aws_quicksight_dashboard

### Expected Behavior

Grid layout element to be added to dashboard with column_index = 0 and/or row_index = 0.

### Actual Behavior

Grid layout element is added to dashboard, but doesn't have column_index and/or row_index set.

### Terraform Configuration Files

```
resource "aws_quicksight_dashboard" "example" {
    dashboard_id = random_uuid.dashboard_id.result
    name = "example"
    version_description = "example"
    definition {
        data_set_identifiers_declarations {
            ...
        }
        sheets {
            ...
        }
        layouts {
            configuration {
                elements {
                    element_id = random_uuid.visual_id.result
                    element_type = "VISUAL"
                    column_index = 0
                    column_span = 18
                    row_index = 0
                    row_span = 12
                }
            }
        }
    }
}
```

### Steps to Reproduce

```
terraform init
terraform plan
terraform apply
```

### Important Factoids

I think that the types of these arguments should be changed from `schema.TypeInt` to `nullable.TypeNullableInt` (and 

### Would you like to implement a fix?

Yes

**Comment by atlesp** [comment]
Duplicates https://github.com/hashicorp/terraform-provider-aws/issues/33108 ?
