### ISSUE TITLE
[New Data Source]: aws_rds_cluster_parameter_group and aws_db_parameter_group

### ISSUE THREAD

**Issue by nwsparks** [hashicorp/terraform-provider-aws#33761]
### Description

A data source for parameter groups would be helpful. One specific use case is related to this problem https://github.com/hashicorp/terraform-provider-aws/issues/22857 which cannot be solved via Terraform.

With a data source I could compare parameters that are being set to what the defaults are and avoid trying to set them if the value already matches avoiding the persistent diff occurring as a result of the issue linked above.

### Requested Resource(s) and/or Data Source(s)

* aws_rds_cluster_parameter_group
* aws_db_parameter_group

### Would you like to implement a fix?

No

**Comment by benjamin-wright** [comment]
As of today `aws_db_parameter_group` exists as a data source, and I've had a go at implementing `aws_rds_cluster_parameter_group` and would like to contribute it back.

**Comment by nwsparks** [comment]
@johnsonaj  @benjamin-wright the newly added data sources are not doing what was described in this issue and are not helpful. I'm not sure if there is even a point to their existence. they need to return the parameters and values to be useful.

**Comment by nwsparks** [comment]
also referenced here https://github.com/hashicorp/terraform-provider-aws/pull/13718#issuecomment-1130497852 

if its helpful i can open a new issue to ask for that to be added
