### ISSUE TITLE
[Bug]: AWS DocDB cluster fails to create Invalid DB Engine

### ISSUE THREAD

**Issue by rymaclen** [hashicorp/terraform-provider-aws#33763]
### Terraform Core Version

1.6.0

### AWS Provider Version

5.21.0

### Affected Resource(s)

aws_docdb_cluster

### Expected Behavior

Expect to be able to create a document db cluster with or without the docdb engine specified

### Actual Behavior

Fails to create documentdb cluster citing invalid db engine.  Occurs when the engine field is explicit or implicit.

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: creating DocumentDB cluster: InvalidParameterValue: Invalid DB engine
│       status code: 400, request id: 82bce636-397d-4ec7-8043-f2d96e1abd39
│ 
│   with aws_docdb_cluster.testr,
│   on 07-docdb-cluster-instance.tf line 3, in resource "aws_docdb_cluster" "testr":
│    3: resource "aws_docdb_cluster" "testr" {
```

### Terraform Configuration Files

resource "aws_docdb_cluster" "testr" {
  cluster_identifier     = "testr"
  availability_zones     = ["us-west-1a", "us-west-1c"]
  db_subnet_group_name   = aws_docdb_subnet_group.prod-db-subnet-group.name
  vpc_security_group_ids = [aws_security_group.docdb-access.id]
  engine                 = "docdb"
  master_username        = "test"
  master_password        = "testing123"
  depends_on             = [aws_docdb_subnet_group.prod-db-subnet-group]
}

### Steps to Reproduce

run terraform apply with the below:

```
resource "aws_docdb_cluster" "testr" {
  cluster_identifier     = "testr"
  availability_zones     = ["us-west-1a", "us-west-1c"]
  engine                 = "docdb"
  master_username        = "test"
  master_password        = "testing123"
}
```

### Important Factoids

Not that I know of.  Its new

### References

https://registry.terraform.io/providers/hashicorp/aws/5.19.0/docs/resources/docdb_cluster

### Would you like to implement a fix?

None

**Comment by rymaclen** [comment]
I am able to create the db using aws cli with the same parameters but still no dice on terraform

**Comment by gbw** [comment]
I believe @ewbankkit's changes in #33790 addresses this.

**Comment by rymaclen** [comment]
I am still having this after upgrading to the AWS 5.21.0 version.  

Terraform v1.6.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.21.0
+ provider registry.terraform.io/hashicorp/random v3.5.1

**Comment by ewbankkit** [comment]
@rymaclen It looks like DocumentDB is not available in `us-west-1`: https://docs.aws.amazon.com/documentdb/latest/developerguide/what-is.html.

**Comment by rymaclen** [comment]
Thank you! That would be why.
