### ISSUE TITLE
[Enhancement]: aws_lb support enforce_security_group_inbound_rules_on_private_link_traffic

### ISSUE THREAD

**Issue by evan-cleary** [hashicorp/terraform-provider-aws#33766]
### Description

When AWS introduced Security Group support for network load balancers, they added an additional property to configure whether the inbound rules are enforced for PrivateLink traffic. 

This property is currently not exposed via the aws_lb/aws_alb resources, so all network load balancers default to the behavior in which inbound rules ARE enforced.

### Affected Resource(s) and/or Data Source(s)

* aws_alb
* aws_lb

### Potential Terraform Configuration

```terraform
resource "aws_lb" "nlb_with_sg" {
  name               = "nlb-with-sg"
  load_balancer_type = "network"
  subnets            = [...]
  security_groups    = [aws_security_group.nlb_sg.id]

  enforce_security_group_inbound_rules_on_private_link_traffic = "off"
}
```

### References

- [SetSecurityGroups API Docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_SetSecurityGroups.html)
- [LB Security Group Docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-security-groups.html#update-security-settings)

### Would you like to implement a fix?

Yes

**Comment by cbllopez** [comment]
Is there any consideration to support this feature? We are hitting the same issue with NLBs and Private Links from API gateway.
