### ISSUE TITLE
[Bug]: Error: waiting for delete Amazon S3 Bucket: found resource

### ISSUE THREAD

**Issue by BrianMMcClain** [hashicorp/terraform-provider-aws#33784]
### Terraform Core Version

1.5.7,1.6.0

### AWS Provider Version

5.17.0

### Affected Resource(s)

* aws_s3_bucket

### Expected Behavior

When running a destroy operation on an S3 bucket with at least one object in it, the object should be destroyed followed by the bucket.

### Actual Behavior

While the bucket is deleted from AWS within a few seconds, Terraform continues to wait for it to be deleted for 1 minute. After a minute passes, it reports an error.

### Relevant Error/Panic Output Snippet

```shell
aws_s3_bucket.s3_bucket: Still destroying... [id=terraform-20231005135247710400000001, 1m0s elapsed]
╷
│ Error: waiting for delete Amazon S3 (Simple Storage) Bucket (terraform-20231005135247710400000001): found resource
```

### Terraform Configuration Files

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.19.0"
    }
  }

  required_version = "~> 1.2"
}

provider "aws" {
  region = "us-east-2"
}

resource "aws_s3_bucket" "s3_bucket" {
}

resource "aws_s3_object" "index" {
  bucket       = aws_s3_bucket.s3_bucket.id
  key          = "index.html"
  content      = "Hello World"
  content_type = "text/html"
}
```

### Steps to Reproduce

* `terraform apply`
* `terraform destroy`

### Important Factoids

This has been reproduced by another person with the same config, and seems to have been introduced in 5.17.0. If I use ~> 5.16.0 or earlier, the bucket is deleted as expected. I also tried setting `force_destroy` to `true` in the bucket config but the same behavior persists.

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
We will switch over to use the documented (but previously unused 😄) [configurable `delete`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#timeouts) [timeout](https://developer.hashicorp.com/terraform/language/resources/syntax#operation-timeouts) instead of a hardcoded 1 minute duration.

**Comment by rsheldon-ansira** [comment]
This is a major pain for us, as we build/test/destroy terraform modules as part of our build plan, before deploying the changed module out to real environments (like dev and stage). Without disabling the test in the build plan, we won't be able to push changes through to real envs.

Any idea when 5.21.0 with the fix will be released?

**Comment by gdewitte** [comment]
👋 I can confirm this issue is _resolved_ in **5.21.0**.  But deleting an s3 bucket now takes considerable time compared to previous AWS Provider versions. To compare the same config mentioned in this ticket:

v.5.16.0:
```
aws_s3_bucket.s3_bucket: Destruction complete after 0s
```
v.5.21.0:
```
aws_s3_bucket.s3_bucket: Destruction complete after 4m7s
```
