### ISSUE TITLE
[New Service]: Amazon DataZone

### ISSUE THREAD

**Issue by hossein-siamaknejad-anz** [hashicorp/terraform-provider-aws#33792]
### Description

I am requesting the integration of Amazon DataZone, a powerful data management service that has recently achieved General Availability (GA) status with an official announcement from AWS. 

Amazon DataZone simplifies data cataloging, discovery, sharing, and governance across multiple data sources, both on AWS and external platforms. 

This integration is of paramount importance for large organizations like ours. As large enterprises deal with vast and diverse data landscapes, Amazon DataZone offers a comprehensive solution to centralize data management, ensuring that data security, governance, and accessibility are maintained at scale. By leveraging this service, we can efficiently manage our data assets, adhere to compliance standards, and promote data-driven decision-making across our organization.

### Requested Resource(s) and/or Data Source(s)

aws_datazone_tbd

### References

https://aws.amazon.com/datazone/

### Would you like to implement a fix?

None

**Comment by johnsonaj** [comment]
Closed with PR #36548
