### ISSUE TITLE
[New Service]: Amazon Bedrock 

### ISSUE THREAD

**Issue by skyscrapr** [hashicorp/terraform-provider-aws#33809]
### Description

Implement support for Amazon Bedrock. 

### Requested Resource(s) and/or Data Source(s)

datasources:

- [x] [`aws_bedrock_foundation_models`](https://github.com/hashicorp/terraform-provider-aws/pull/34148)
- [x] [`aws_bedrock_foundation_model`](https://github.com/hashicorp/terraform-provider-aws/pull/34148)
- [x] [`aws_bedrock_custom_models`](https://github.com/hashicorp/terraform-provider-aws/pull/34310)
- [x] [`aws_bedrock_custom_model`](https://github.com/hashicorp/terraform-provider-aws/pull/34310)

resources:

- [x] [`aws_bedrock_custom_model`](https://github.com/hashicorp/terraform-provider-aws/pull/34310)
- [ ] [`aws_bedrock_provisioned_model_throughput`](https://github.com/hashicorp/terraform-provider-aws/pull/35689)
- [x] [`aws_bedrock_model_invocation_logging_configuration`](https://github.com/hashicorp/terraform-provider-aws/pull/34303)

### Potential Terraform Configuration

```terraform
data "aws_bedrock_foundation_models" "test" {
}

data "aws_bedrock_foundation_model" "test" {
  model_arn = "foundationmodelarn"
}

data "aws_bedrock_custom_models" "test" {
}

data "aws_bedrock_custom_model" "test" {
	model_arn = "testmodelarn"
}

resource "aws_bedrock_custom_model" "test" {
  custom_model_name = "test"
  job_name          = "test"
  base_model_arn    = "amazon.titan-text-express-v1"
  hyper_parameters = {
    "epochCount"              = "1"
    "batchSize"               = "1"
    "learningRate"            = "0.005"
    "learningRateWarmupSteps" = "0"
  }
  output_data_config   = "s3://${aws_s3_bucket.output_data.id}/myfolder/"
  role_arn             = aws_iam_role.bedrock_fine_tuning.arn
  training_data_config = "s3://${aws_s3_bucket.training_data.id}/myfolder/training_data.jsonl"
}
```

### References

https://docs.aws.amazon.com/bedrock/latest/APIReference/welcome.html

### Would you like to implement a fix?

Yes

**Comment by blakeromano** [comment]
👍 this would be great

**Comment by oleksandrsv** [comment]
I'd really be happy with this resources in provider.
