### ISSUE TITLE
[Bug]: Computed Security Groups for aws_lb trigger a replacement when load_balancer_type == "network"

### ISSUE THREAD

**Issue by jphelton** [hashicorp/terraform-provider-aws#33813]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.20.0

### Affected Resource(s)

* resource "aws_lb"

## Background

Per the AWS docs (links have been provided in the references section)

* *You can associate security groups with a Network Load Balancer when you create it. If you create a Network Load Balancer without associating any security groups, you can't associate them with the load balancer later on. We recommend that you associate a security group with your load balancer when you create it.*

* *After you create a Network Load Balancer with associated security groups, you can change the security groups associated with the load balancer at any time.*

## Steps and Expected Behavior
* In my `main.tf` I create a security group, and an NLB (with newly created security group attached to it)
* Next I updated my main.tf file to create a *second* security group and attach it to the existing NLB
* From the AWS docs I would **expect** this to be an "in-place" update that doesn't require the creation of a new NLB

### Actual Behavior

When I run `terraform plan` I see that terraform is trying to create a new NLB, instead of updating in place

* This behavior is only present when the `security_groups` field is "computed", i.e. the values are not known at plan time, but will become available at some point during the apply operations
* If I created the Security groups outside of terraform and passed them in as variables this error does not occur.

### Relevant Error/Panic Output Snippet

```shell
~ security_groups = [ # forces replacement
    - "sg-<security groupd id>",
    - "sg-0f9ca20d0cfdce3a4",
  ] -> (known after apply) # forces replacement
```

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "~> 5.19"
    }
  }
}
variable "vpc_id" {
  type=string
}
variable "subnets" {
  type = list(string)
}
variable "num_sgs" {
  type = number
  default = 1
}

resource "aws_security_group" "sg" {
  count = var.num_sgs
  vpc_id = var.vpc_id
}

resource "aws_lb" "lb" {
  subnets = var.subnets
  load_balancer_type = "network"
  security_groups = [ for sg in aws_security_group.sg : sg.id ]
}
```

### Steps to Reproduce

1. Run `terraform apply -auto-approve`
2. Run `terraform plan -var num_sgs=2`

In the plan output you'll see that the NLB is being replaced, even though updating security groups can be done in-place.

### Important Factoids

Looking around in the code the source of the issues appears to be `diff.GetChange("security_groups")`.  When returning a Set object where the values is `Computed`, the default behavior of the terraform provider is to return an empty set.  We could optimize this by also calling `diff.NewValueKnown("security_groups.#")` to determine if the value is computed.

## AWS Reference Docs
- NLB Support is relatively new feature, here's the blog post: [Network Load Balancer now supports security groups](https://aws.amazon.com/about-aws/whats-new/2023/08/network-load-balancer-supports-security-groups/)
- AWS Documentation: [Security groups for your Network Load Balancer](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-security-groups.html)

## Relevant Terraform Provider Links
- Pull Request enabling this feature: #32987 
- Code block responsible for determining if a replacement is required: [internal/service/elbv2/load_balancer.go#L1050-L1058](https://github.com/hashicorp/terraform-provider-aws/blob/v5.20.0/internal/service/elbv2/load_balancer.go#L1050-L1058)

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Closed via #33205
