### ISSUE TITLE
FR: Randomly generate and encrypt DB password to provided PGP key

### ISSUE THREAD

**Issue by jgiles** [hashicorp/terraform-provider-aws#3385]
### Terraform Version
Terraform v0.11.3

### Affected Resource(s)
At least these two:
- aws_db_instance
- aws_rds_cluster

### Expected Behavior
https://www.terraform.io/docs/state/sensitive-data.html suggests that the Terraform resources for creating RDS databases have options for PGP encrypting values in the Terraform state. Presumably, this would work like [aws_iam_access_key's pgp_key option](https://www.terraform.io/docs/providers/aws/r/iam_access_key.html#pgp_key) and would encrypt the password.

### Actual Behavior
There is no such option: https://www.terraform.io/docs/providers/aws/r/db_instance.html

### Important Factoids
Unlike the `aws_iam_access_key` case, we're not just returning a value from AWS. We need to actually send the password as a parameter to AWS.
The best solution would probably be to randomly generate a secure password at provision time. This would be sent to AWS, and then stored encrypted in a new `encrypted_password` attribute.
This approach does require the aws provider to decide what a secure and valid password is. We would need to pick a length, and passwords would need to comply with the various password constraints enforced by different types of databases.

### References
Related issue about "removing" password from Terraform state (very likely infeasible):
https://github.com/terraform-providers/terraform-provider-aws/issues/2332
Long-running Terraform core issue about sensitive values in state, which includes discussion of and workarounds for the DB password problem:
https://github.com/hashicorp/terraform/issues/516

**Comment by Wenzil** [comment]
+1

I was disappointed to see that the [random_string](https://www.terraform.io/docs/providers/random/r/string.html) resource doesn't have the option to pass in a PGP key for encryption, since its arguments otherwise provide nice utilities for password policies (`minUpper`, `minNumeric`, etc.) and re-generation (when `keepers` change)
