### ISSUE TITLE
[Bug]: elasticache/replication_group update is not waiting for replication group in the available state before updating the tags

### ISSUE THREAD

**Issue by yogesh2580** [hashicorp/terraform-provider-aws#33859]
Potentially Related 

* #23219
* #24021
* #29838
* #30444
* #31819
* #33859

### Terraform Core Version

1.5.4

### AWS Provider Version

5.11.0

### Affected Resource(s)

aws_elasticache_replication_group

### Expected Behavior

The Tags on existing replication_group should be updated with the new keys-values and engine version update to 6.0.5

### Actual Behavior

```shell
 Error: listing tags for ElastiCache Replication Group (arn): InvalidReplicationGroupState: Cluster not in available state to perform tagging operations.
status code: 400, request id: 5222cf25-276d-4294-8460-dd4364433d5f
```

### Terraform Configuration Files

```terraform
provider "aws" {
  shared_credentials_file = "CREDENTIAL_FILE"
  profile                 = "AWS_PROFILE"
  region                  = "us-east-1"
}

resource "aws_elasticache_replication_group" "test-redis" {
  replication_group_id          = "test-redis"
  replication_group_description = "test-redis"
  node_type                     = "cache.t4g.micro"
  engine                        = "redis"
  engine_version                = "6.0.5"
  parameter_group_name          = "parameter-grp"
  port                          = 6379
  number_cache_clusters         = 1 
  automatic_failover_enabled    = false

  security_group_ids = ["${var.redis-sg}"]
  subnet_group_name  = "${aws_elasticache_subnet_group.default.name}"

  tags {
    Name        = "TestRedis"
    Environment = "Dev"
    creator = "yogesh"  # adding new tag tagone to the existing resource group
  }
}

resource "aws_elasticache_subnet_group" "default" {
  name       = "test-subnet"
  subnet_ids = ["SUBNET-ID1", "SUBNET-ID2"]
}
```

### Steps to Reproduce

terraform apply
Update aws_elasticache_replication_group tags
terraform apply

### References

Previously the same issue was seen in version 3.74.1 and i got fixed in 4.9.0  
Reference ticket number https://github.com/hashicorp/terraform-provider-aws/issues/23219

### Would you like to implement a fix?

None

**Comment by phene** [comment]
Looks like someone attempted to fix this in the past: https://github.com/hashicorp/terraform-provider-aws/pull/24021

**Comment by brunofarina** [comment]
Hi, 
I'm having the same error when I try to update something of an existent replication group, for instance updating the engine version or even enabling the multi-az.
