### ISSUE TITLE
[Enhancement]: aws_glue_job new worker types

### ISSUE THREAD

**Issue by adaspadas** [hashicorp/terraform-provider-aws#33862]
### Description

Terraform v1.5.7

Seems that terraform supports only 3 worker types:
Error: expected worker_type to be one of [Standard G.1X G.2X G.025X], got G.4X

However, there is 2 new worker types G.4X and G.8X

### Affected Resource(s) and/or Data Source(s)

aws_glue_job

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_job

### Would you like to implement a fix?

None

**Comment by TimNewport** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/31481
