### ISSUE TITLE
[Bug]:  aws_elasticache_replication_group - Terraform fails when trying to plan or apply because of old engine_version

### ISSUE THREAD

**Issue by Louis-Marie-W** [hashicorp/terraform-provider-aws#33867]
### Terraform Core Version

1.5.2

### AWS Provider Version

5.20.0

### Affected Resource(s)

aws_elasticache_replication_group

### Expected Behavior

Expected behavior is for aws_elasticache_replication_group to work as it worked on older versions of the provider.
It was working with AWS provider 5.2.0.
Then, it was broken.

### Actual Behavior

Issue #32252 states that it has been solved, but I still have the problem.

 Error: parsing old engine_version: Malformed version: 7.x
│
│   with aws_elasticache_replication_group.mygroup,
│   on redis-elasticache.tf line 55, in resource "aws_elasticache_replication_group" "mygroup":
│   55: resource "aws_elasticache_replication_group" "mygroup" {

My current engine version on AWS is: 7.0.7
and the value that I put in configuration file is: 7.0

### Terraform Configuration Files

My current configuration:
```
resource "aws_elasticache_replication_group" "mygroup" {
  description                     = "ElastiCache cluster for queues on Redis"
  replication_group_id            = "tf-redis-main"
  engine                          = "redis"
  engine_version                  = "7.0"
  node_type                       = "cache.t4g.small"
  parameter_group_name            = aws_elasticache_parameter_group.redis-parameter-group.id
  maintenance_window              = "sun:03:00-sun:04:00"
  port                            = 6379

  subnet_group_name               = aws_elasticache_subnet_group.tf_redis.name
  security_group_ids              = [aws_security_group.redis.id]
}
```

### Steps to Reproduce

Switch to AWS provider version 5.20.0 or newer 
and run terraform plan for an aws_elasticache_replication_group resource 

### References

Other github issue: #32252

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @Louis-Marie-W 👋 Thanks for taking the time to raise this! Were you by chance using `engine_version = 7.x` prior to upgrading the AWS Provider version? [This comment](https://github.com/hashicorp/terraform-provider-aws/issues/32252#issuecomment-1650830199) indicated a similar experience, and found that the state file had `7.x` in it, rather than `7.0`.
