### ISSUE TITLE
[Bug]: aws_appautoscaling_scheduled_action pulling incorrect values on read from api

### ISSUE THREAD

**Issue by kevincormier-toast** [hashicorp/terraform-provider-aws#33873]
### Terraform Core Version

1.2.9

### AWS Provider Version

3.22.0

### Affected Resource(s)

* aws_appautoscaling_scheduled_action

### Expected Behavior

* Set up scheduled actions with the same name on the same dynamodb table for both table read and write.
* The subsequent plan, terraform should show no changes required.

### Actual Behavior

* Set up scheduled actions with the same name on the same dynamodb table for both table read and write.
* The subsequent plan, terraform show's a diff on the scheduled action for `"ScalableDimension": "dynamodb:index:WriteCapacityUnits"`
  *  Old value matches whatever was set for the ReadCapacityUnits scalable dimension.

### Relevant Error/Panic Output Snippet

```shell
none
```

### Terraform Configuration Files

Will upload later.

### Steps to Reproduce

terraform apply, terraform plan, see diffs.

### Debug Output

n/a

### Panic Output

n/a

### References

> Each scalable target is identified by a service namespace, resource ID, and scalable dimension.
https://docs.aws.amazon.com/cli/latest/reference/application-autoscaling/put-scheduled-action.html#:~:text=Each%20scalable%20target%20is%20identified%20by%20a%20service%20namespace%2C%20resource%20ID%2C%20and%20scalable%20dimension.

When pulling the data from the API, we can see that the call is only querying on name, namespace, and resource_id, but not scalable dimension. 
```
scheduledAction, err := FindScheduledAction(ctx, conn, d.Get("name").(string), d.Get("service_namespace").(string), d.Get("resource_id").(string))
```
https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/appautoscaling/scheduled_action.go#L211

### Would you like to implement a fix?

None

**Comment by kevincormier-toast** [comment]
sorry I didn't include any examples in the original report.  I'll work on putting some together and adding them if folks feel like we need it.  I think the AWS docs and the linked code pretty clearly highlight the discrepancy though.

**Comment by justinretzolk** [comment]
Hey @kevincormier-toast 👋 Thank you for taking the time to raise this! I see that you're using a relatively old version of the AWS Provider. Are you able to test on a more recent version to verify if the issue persists?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
