### ISSUE TITLE
[Docs]: aws_db_option_group: option_settings documentation is non-intuitive and confusing

### ISSUE THREAD

**Issue by evilensky** [hashicorp/terraform-provider-aws#33887]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_option_group#option_settings

### Description

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_option_group#option_settings

> [option_settings](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_option_group#option_settings) - (Optional) List of option settings to apply.

when looking at the provider unit tests for this resource, it appears that this statement means creating multiple blocks of `option_settings {}` with one option each. Since this resource is in the plural this is very unintuitive.

This request is to clear up the documentation to make it clear that `List` doesn't mean `[]`. 

### Would you like to implement a fix?

None

**Comment by network-charles** [comment]
It is actually a list. An option name can have several option settings, for example, the 
[MSDTC](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.SQLServer.Options.MSDTC.html) option name in RDS for Microsoft SQL.
