### ISSUE TITLE
[Bug]: aws_opensearch_domain default timeout create is too short (60m)

### ISSUE THREAD

**Issue by philvarner** [hashicorp/terraform-provider-aws#33897]
### Terraform Core Version

1.5.5

### AWS Provider Version

5.13

### Affected Resource(s)

When creating a aws_opensearch_domain, the default `create` timeout is 60m. However, I frequently see it take longer than 60 min to create a domain. Typically it's not much more than 60m, but when it is, the state and actual AWS resources become out of sync, and it's a hassle to cleanup (requiring a ~30min teardown of the domain) and redeploy. I think 90 minutes is enough time in nearly all cases.

### Expected Behavior

The default timeout should be long enough that there is very rarely a failure.

### Actual Behavior

creating of this resource times out about 1 in 10 times.

### Terraform Configuration Files

Any reasonable configuration for an opensearch domain should do this, but the one I'm using looks like:

```terraform
resource "aws_opensearch_domain" "my_opensearch_domain" {
  domain_name    = var.domain_name
  engine_version = var.opensearch_version

  cluster_config {
    instance_type            = var.opensearch_cluster_instance_type
    instance_count           = var.opensearch_cluster_instance_count
    dedicated_master_enabled = var.opensearch_cluster_dedicated_master_enabled
    dedicated_master_type    = var.opensearch_cluster_dedicated_master_type
    zone_awareness_enabled   = var.opensearch_cluster_zone_awareness_enabled

    zone_awareness_config {
      availability_zone_count = var.opensearch_cluster_availability_zone_count
    }
}
```

### Steps to Reproduce

1. Deploy an aws_opensearch_domain
2. About 1 in 10 times, create takes more than 60 minutes and fails.

### Would you like to implement a fix?

None

**Comment by DanielRieske** [comment]
Hi @philvarner 👋 , I have increased the default timeout during a [refactor](https://github.com/hashicorp/terraform-provider-aws/pull/38901) of this service to 90 minutes.
Keep in mind that you are also able to override the timeouts per operation in the schema.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearch_domain#timeouts

Thanks for raising this issue!
