### ISSUE TITLE
[Docs]: s3_bucket access_control_translation

### ISSUE THREAD

**Issue by FORDBX4** [hashicorp/terraform-provider-aws#33894]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_server_side_encryption_configuration

### Description

An argument of the destination configuration block, access_control_translation, isn't properly defined in the documentation. access_control_translation is recognized as a configuration block, and executing a terraform plan will throw an error if you define it as a regular argument.

Potential revision:
The `destination` configuration block supports the following arguments:
. . .

`access_control_translation` - (Optional) Specifies the overrides to use for object owners on replication . . . (documented below).
. . .

The `access_control_translation` configuration block supports the following arguments:

`owner` - (Required) Specifies the replica ownership . . .

### References

https://github.com/hashicorp/terraform/issues/34064
https://github.com/hashicorp/terraform/issues/23376

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
AFAIK the access control translation settings is relevant to replication configuration, not SSE configuration that the documentation link refers to in the issue description. I can see the description of the `access_control_translation` configuration block in the [`aws_s3_bucket_replication_configuation` resource documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_replication_configuration#access_control_translation), as well as in the [`aws_s3_bucket` resource documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#access_control_translation) for the in-line configuration scenario. The latter can be improved as it does not outline the spec for the configuration block like the former.
