### ISSUE TITLE
[Bug]: TransitEncryptionMode still unsupported after #29403

### ISSUE THREAD

**Issue by mkielar** [hashicorp/terraform-provider-aws#33906]
### Terraform Core Version

1.5.0

### AWS Provider Version

5.20.1

### Affected Resource(s)

* `aws_elasticache_replication_group`

### Expected Behavior

After #29403 was closed, I'd expect the `transit_encryption_mode` attribute to be available for `aws_elasticache_replication_group` resource, with allowed values of `preferred` and `required`.

### Actual Behavior

There's no sign of setting `TransitEncryptionMode` attribute in the API Call, no mention of `transit_encryption_mode` in the code and documentation. As a result, TLS Connections to Redis Cluster still cannot be enforced, and can only be enabled (in "preferred" mode) for these who wish to connect securely.

### Relevant Error/Panic Output Snippet

```shell
N/A
```

### Terraform Configuration Files

N/A

### Steps to Reproduce

N/A

### Debug Output

N/A

### Panic Output

N/A

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @mkielar 👋 Thanks for taking the time to raise this! It looks like this should be addressed with #30403 whenever it gets prioritized and merged.
