### ISSUE TITLE
[Enhancement]: add ipv6 outbound to lambda vpc_config

### ISSUE THREAD

**Issue by bryceml** [hashicorp/terraform-provider-aws#33922]
### Description

https://aws.amazon.com/about-aws/whats-new/2023/10/aws-lambda-ipv6-outbound-connections-vpc/

Add support for this.

### Affected Resource(s) and/or Data Source(s)

aws_lambda_function

### Potential Terraform Configuration

```terraform
vpc_config {
  subnet_ids         = [aws_subnet.subnet_for_lambda.id]
  security_group_ids = [aws_security_group.sg_for_lambda.id]
  ipv6_allowed_for_dual_stack = true
}
```

### References

https://docs.aws.amazon.com/lambda/latest/dg/API_GetFunctionConfiguration.html
https://docs.aws.amazon.com/lambda/latest/dg/API_UpdateFunctionConfiguration.html
https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
Requires [AWS SDK for Go v1.45.25](https://github.com/aws/aws-sdk-go/releases/tag/v1.45.25): https://github.com/hashicorp/terraform-provider-aws/pull/33932.

**Comment by DanielRieske** [comment]
I'll gladly pick this issue up, I will add the PR shortly.
