### ISSUE TITLE
[Enhancement]: aws_db_instance tags are not propagated to enabled_cloudwatch_logs_exports

### ISSUE THREAD

**Issue by good92** [hashicorp/terraform-provider-aws#33946]
### Description

aws_db_instance tags are not propagated to enabled_cloudwatch_logs_exports.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#enabled_cloudwatch_logs_exports

### Affected Resource(s) and/or Data Source(s)

aws_db_instance.enabled_cloudwatch_logs_exports: cloudwatch logs groups tags

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @good92 👋 Thank you for taking the time to raise this! Am I understanding correctly that what you're looking for is to have any tags that are applied to the DB instance be propagated to the logs that get exported to Cloudwatch? As far as I can tell, that doesn't appear to be something that AWS supports. Are you aware of a way to accomplish this in AWS today that I could use to help identify whether this is currently feasible?

**Comment by justinretzolk** [comment]
Since we haven't heard back, and it doesn't look like this is something that AWS currently supports, I'm going to close this issue. If this becomes possible in the future, we'd be happy to take another look.

**Comment by good92** [comment]
Hi [justinretzolk](https://github.com/justinretzolk),

Thanks.
I think it can be implementated as a workaround, by identifying with audit capabilities have beenn enabled and then an update on cloudwatch log group tags can be done.
Maybe a ticket to AWS about this bug can be created and referenced.
