### ISSUE TITLE
[Docs]: ce_anomaly_subscription basic example is not compatible with latest version

### ISSUE THREAD

**Issue by kamilsimek-ecb** [hashicorp/terraform-provider-aws#33947]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ce_anomaly_subscription

### Description

Basic example for ce_anomaly_subscription is not compatible with hashicorp/aws latest (> 5.0.0) as the threshold attribute has been removed. See "resource/aws_ce_anomaly_subscription: The threshold attribute has been removed"(https://github.com/hashicorp/terraform-provider-aws/issues/30374) as part of [change log](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#500-may-25-2023).

### References

https://github.com/hashicorp/terraform-provider-aws/issues/30374

### Would you like to implement a fix?

None

**Comment by NicoleYarbrough** [comment]
Thank you for raising this issue. I will work on this and drop a PR later

**Comment by kamilsimek-ecb** [comment]
Much appreciated @NicoleYarbrough and @jar-b! ❤️ 📜
