### ISSUE TITLE
[Enhancement]: Support for signer:SignPayload in aws_signer_signing_profile_permission

### ISSUE THREAD

**Issue by aii-satoshi-abe** [hashicorp/terraform-provider-aws#33941]
### Description

Currently, aws_signer_signing_profile_permission supports the following actions
* signer:StartSigningJob
* signer:GetSigningProfile
* signer:RevokeSignature

When setting Notation-OCI-SHA384-ECDSA for platform_id in aws_signer_signing_profile, "signer:SignPayload" is required in addition.

### Affected Resource(s) and/or Data Source(s)

aws_signer_signing_profile_permission

### Potential Terraform Configuration

```terraform
resource "aws_signer_signing_profile_permission" "example_profile_permission" {
  profile_name = aws_signer_signing_profile.example_signing_profile.name
  action       = "signer:SignPayload"
  principal    = "123456789012"
}
```

### References

https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssigner.html

### Would you like to implement a fix?

No

**Comment by jbianquetti-nami** [comment]
The error message is like this one: 

```
 Error: adding new Signer Signing Profile Permission for "xxxxxxxx": operation error signer: AddProfilePermission, https response error StatusCode: 400, RequestID: 6be71783-f247-49cd-bf1f-8f75f8596fdb, ValidationException: Action signer:StartSigningJob not supported for platform Notation-OCI-SHA384-ECDSA. Action must be one of [signer:SignPayload, signer:GetSigningProfile, signer:RevokeSignature]
```
