### ISSUE TITLE
[Docs]: CloudHSM - HSM missing fields in doc

### ISSUE THREAD

**Issue by leunamnauj** [hashicorp/terraform-provider-aws#34025]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudhsm_v2_hsm

### Description

In the documentation, only the following fields are listed as attributes :
  * `hsm_id`
  * `hsm_state`
  * `hsm_eni_id`
  
but returned fields are in fact much more:
* `availability_zone`
* `cluster_id`
* `hsm_eni_id`
* `hsm_id`
* `hsm_state`
* `id`
* `ip_address`
* `subnet_id`

Please update the document accordingly because it's a shame not to have this properly described when the functionalities are actually there.

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
Just an observation - between the **Argument Reference** section and the **Attribute Reference** section (which is typically in addition to the argument list in Terraform doc), the doc seems to have accounted for all attributes except for the `id` attribute.

**Comment by yashchaddha** [comment]
Hi @leunamnauj
I would like to contribute on this, Can i please get assigned to it?
Thanks

**Comment by Jgeissler14** [comment]
https://github.com/hashicorp/terraform-provider-aws/pull/35148
Pull request opened
