### ISSUE TITLE
[New Data Source]: aws_cognito_user_group

### ISSUE THREAD

**Issue by jordancparker** [hashicorp/terraform-provider-aws#34024]
### Description

Hi everyone, 

would it be possible to create a data field to filter and query the aws_cognito_user_group. 

Below is an example of the SDK `aws cognito-idp list-groups --user-pool-id ********` 

### Requested Resource(s) and/or Data Source(s)

aws_cognito_user_group

### Potential Terraform Configuration

```terraform
data "aws_cognito_user_group" "this" {
  name = var.cognito_user_pool_id
}
```

### References

https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ListGroups.html

### Would you like to implement a fix?

None

**Comment by bensmith2093** [comment]
I would love this feature, upvoted!!
