### ISSUE TITLE
[Docs]: aws_db_snapshot documentation formatting error, not sure if parameter is supported

### ISSUE THREAD

**Issue by lisakoivu** [hashicorp/terraform-provider-aws#34072]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/db_snapshot

### Description

The documentation states that a "tags" parameter is supported, optional, but it's formatted incorrectly, without a bullet. 
<img width="549" alt="image" src="https://github.com/hashicorp/terraform-provider-aws/assets/43785335/6353531d-775f-4d1f-ab72-1151b977a9b5">

That being said, I can't use tags as a filter. Is it supported, or not? 

Thank you

```
data "aws_db_snapshot" "clone" {
  db_instance_identifier = "ylvoprd"
  snapshot_type = "manual"
  tags = {
    key   = "tag:data-systems:golden-snapshot-date"
    value = "20231022"
  }
}

...

│ Error: Unsupported argument
│ 
│   on main.tf line 48, in data "aws_db_snapshot" "clone":
│   48:   tags = {
│ 
│ An argument named "tags" is not expected here.
```

### Would you like to implement a fix?

None

**Comment by lisakoivu** [comment]
I realized I am using version 4.x of the provider, which does not support this functionality.

**Comment by stefanfreitag** [comment]
Hi @justinretzolk , I was looking  for some work in the documentation space - this issue seems to be resolved. Maybe the issue can be set from open to closed.
