### ISSUE TITLE
[Docs]: glue_crawler -> catalog_target block documentation is missing

### ISSUE THREAD

**Issue by matschundbrei** [hashicorp/terraform-provider-aws#34081]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_crawler

### Description

While the examples show how to attach a `catalog_target` the block definition is missing from the actual documentation.

### References

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-crawler-catalogtarget.html

### Would you like to implement a fix?

No

**Comment by acwwat** [comment]
It looks like the documentation already has a section for the `catalog_target` block specifications, just that the argument description itself is missing. I've submitted a PR to add that in similar to other target types.
