### ISSUE TITLE
[New resource] OpenSearch Serverless Data Lifecycle Policies

### ISSUE THREAD

**Issue by edhgoose** [hashicorp/terraform-provider-aws#34092]
### Description

AWS have announced support for time based deletion in OpenSearch Serverless Time Series Collections.

Please can we add support to Terraform for this.

### Requested Resource(s) and/or Data Source(s)

aws_opensearchserverless_lifecyclepolicy perhaps?

### References

Launch: https://aws.amazon.com/about-aws/whats-new/2023/10/amazon-opensearch-serverless-automated-time-based-data-deletion/

Docs: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-lifecycle.html

### Would you like to implement a fix?

No

**Comment by joshjluo** [comment]
I can pick this up!

**Comment by edhgoose** [comment]
Thank you @joshjluo and @johnsonaj!
