### ISSUE TITLE
[Docs]: Resources `aws_iam_group` and `aws_iam_user` have incorrect id attribute description

### ISSUE THREAD

**Issue by nikpivkin** [hashicorp/terraform-provider-aws#34107]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources

### Description

I expected the resources `aws_iam_user`, `aws_iam_group` and `aws_iam_role` to have the same id attribute description and where it will be said that the id contains the resource name.

There is [no description](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user#attribute-reference) of the `id` attribute for the `aws_iam_user` resource.

The documentation [says](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_group#id) that the resource id attribute `aws_iam_group` contains the id of the group, but this attribute actually contains the name.

### References

- https://github.com/aws/aws-sdk-go/blob/v1.46.3/service/iam/api.go#L40853
- https://github.com/hashicorp/terraform-provider-aws/blob/f606f309645e496595544b222551f8aa33bab44a/internal/service/iam/user.go#L120
- https://github.com/aws/aws-sdk-go/blob/v1.46.3/service/iam/api.go#L27407
- https://github.com/hashicorp/terraform-provider-aws/blob/f606f309645e496595544b222551f8aa33bab44a/internal/service/iam/group.go#L86

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
Overall, the attributes are inconsistent between these IAM resources and data sources. Here's a table listing what the attribute mappings for fields related to IDs and names. Regardless of the inconsistencies, the documentation should be updated to reflect the actual attribute values.

| Resource or data source | Type | Attribute name | Attribute value | Documented correctly? |
|---|---|---|---|---|
| Data source | `iam_group` | `group_id` | The group unique ID | Yes |
| Data source | `iam_group` | `group_name` | The group name | Yes |
| Data source | `iam_group` | `id` | The group unique ID | No - not documented |
| Resource | `iam_group` | `id` | The group name | No - description refers to group ID |
| Resource | `iam_group` | `name` | The group name | Yes | 
| Resource | `iam_group` | `unique_id` | The group unique ID | Yes |
| Data source | `iam_role` | `id` | The role name | Yes |
| Data source | `iam_role` | `name` | The role name | Yes |
| Data source | `iam_role` | `unique_id` | The role unique ID | Yes |
| Resource | `iam_role` | `id` | The role name | Yes |
| Resource | `iam_role` | `name` | The role name | Yes |
| Resource | `iam_role` | `unique_id` | The role unique ID | Yes |
| Data source | `iam_user` | `id` | The user unique ID | No - not documented |
| Data source | `iam_user` | `user_id` | The user unique ID | Yes |
| Data source | `iam_user` | `user_name` | The user name | Yes |
| Resource | `iam_user` | `id` | The user name | No - not documented |
| Resource | `iam_user` | `name` | The user name | Yes |
| Resource | `iam_user` | `unique_id` | The user unique ID | Yes |

**Comment by acwwat** [comment]
This is also somewhat related to #26660.
