### ISSUE TITLE
AWS Cloud WAN Tunnel-less connect

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#34101]
> Today AWS announces Tunnel-less connect, a new feature of AWS Cloud WAN that provides you with a simple and more performant way to build global SD-WAN (Software Defined Wide Area Network).

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2023/10/aws-cloud-wan-tunnel-less-high-performant-global-sd-wans/)
* [Blog post](https://aws.amazon.com/blogs/networking-and-content-delivery/build-global-sd-wans-with-aws-cloud-wan-tunnel-less-connect/)

Requires [AWS SDK for Go v1.46.2](https://github.com/aws/aws-sdk-go/releases/tag/v1.46.2), https://github.com/hashicorp/terraform-provider-aws/pull/34078.

Affected resources:

* [`aws_networkmanager_connect_peer`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_connect_peer)

**Comment by ddericco** [comment]
@ewbankkit this is being worked on
