### ISSUE TITLE
[Enhancement]: add support for codepipeline type(v1,v2)

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/terraform-provider-aws#34122]
### Description

https://aws.amazon.com/about-aws/whats-new/2023/10/aws-codepipeline-parameterized-pipelines/

### Affected Resource(s) and/or Data Source(s)

* aws_codepipeline

### Would you like to implement a fix?

None

**Comment by aaron-launch** [comment]
This forces all previous available features like cloudwatch events into v2 with default being v1. This will break new pipeline deployments if you rely on these features until you can select version in your module. Within my infra, I can manually select v2 after deployment and it behaves as intended.

**Comment by DrFaust92** [comment]
looking into this

**Comment by neruneruo** [comment]
I'm trying to implement a fix.

Enhanced attribute is ```pipeline_type``` and ```variable```.

Code-modify and AccTest-modify completed.

**Comment by romangoldberg** [comment]
Hello,
any updates?
