### ISSUE TITLE
[Docs]: `aws_dynamodb_table` argument `import_table.client_token` errors

### ISSUE THREAD

**Issue by magreenbaum** [hashicorp/terraform-provider-aws#34139]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#client_token

### Description

The documentation indicates `client_token` is an argument: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#client_token

However it looks like the `client_token` from this [PR](https://github.com/hashicorp/terraform-provider-aws/pull/27253/files) which was closed by this [PR](https://github.com/hashicorp/terraform-provider-aws/pull/33802) was not included in the merge to [main](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/dynamodb/table.go#L310-L378). 

```
│ Error: Unsupported argument
│ 
│   on ../../main.tf line 78, in resource "aws_dynamodb_table" "this":
│   78:       client_token = try(import_table.value.client_token, null)
│ 
│ An argument named "client_token" is not expected here.
```

### Would you like to implement a fix?

None

**Comment by jtyrus** [comment]
I can take a look
