### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rockola15** [hashicorp/terraform-provider-aws#34133]
### Terraform Core Version

0.13

### AWS Provider Version

5.23.0

### Affected Resource(s)

aws_lambda_event_source_mapping

### Expected Behavior

We want use Error: aws_lambda_event_source_mapping with document_db

This is the code:

```tf
resource "aws_lambda_event_source_mapping" "example" {
  event_source_arn = var.docdb_arn
  function_name = aws_lambda_function.lambda.function_name
  batch_size = 1
  source_access_configuration {
    type = "BASIC_AUTH"
    uri  = var.secret_arn
  }
  document_db_event_source_config = {
    database_name = var.db_name
    collection_name = var.collection
    full_document = "UpdateLookup"
  }
}
```

### Actual Behavior

```shell
Error: Unsupported argument
│
│   on modules/lambda/main.tf line 53, in resource "aws_lambda_event_source_mapping" "change_stream":
│   53:   document_db_event_source_config = {
│
│ An argument named "document_db_event_source_config" is not expected here. Did you mean to define a block of type "document_db_event_source_config"?
```

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {
  region = "eu-west-1"
  profile = "{{ deploy_profile }}-{{ env }}"
}
```

### Steps to Reproduce

terraform apply

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
`document_db_event_source_config` is a configuration block but in your example it is being set to a map due to the `=` sign. See if removing `=` fixes the error.

**Comment by justinretzolk** [comment]
Since we haven't heard back, and the correct answer was given above, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
