### ISSUE TITLE
[Bug]: changing enable_performance_mode on aws_amplify_branch forces replacement

### ISSUE THREAD

**Issue by KholdStare** [hashicorp/terraform-provider-aws#34130]
### Terraform Core Version

1.5.5

### AWS Provider Version

5.20.0

### Affected Resource(s)

* aws_amplify_branch

### Expected Behavior

Changing `enable_performance_mode` on an `aws_amplify_branch` should cause an update to the resource.

It should be possible because AWS CLI allows it:

```
aws amplify update-branch --app-id APP_ID --branch-name BRANCH_NAME --enable-performance-mode
```

### Actual Behavior

Changing `enable_performance_mode` on an `aws_amplify_branch` forces replacement

### Relevant Error/Panic Output Snippet

```shell
# module.frontend.aws_amplify_branch.branches["REDACTED"] must be replaced
-/+ resource "aws_amplify_branch" "branches" {
      ~ arn                         = "REDACTED" -> (known after apply)
      ~ associated_resources        = [] -> (known after apply)
      ~ custom_domains              = [] -> (known after apply)
      + destination_branch          = (known after apply)
      ~ display_name                = "REDACTED" -> (known after apply)
      - enable_basic_auth           = false -> null
      - enable_notification         = false -> null
      ~ enable_performance_mode     = false -> true # forces replacement
      - environment_variables       = {} -> null
      ~ id                          = "REDACTED" -> (known after apply)
      + source_branch               = (known after apply)
      - tags                        = {} -> null
      ~ tags_all                    = {} -> (known after apply)
      - ttl                         = "5" -> null
        # (6 unchanged attributes hidden)
    }
```

### Terraform Configuration Files

N/A

### Steps to Reproduce

* Add `resource "aws_amplify_app" "app"`
* Add `resource "aws_amplify_branch" "branch"` for the app with `enable_performance_mode = false`
* Deploy with `terraform apply`
* Change `enable_performance_mode = true` in `aws_amplify_branch.branch`
* Run `terraform plan` to see that it forces replacement.

### Would you like to implement a fix?

None

**Comment by naruse666** [comment]
@KholdStare Hi :wave:
I fixed this.
cus enable_performance_mode was included unnecessary scheme.
