### ISSUE TITLE
[Bug]: d/aws_lambda_function issue in aws provider 5.23.0

### ISSUE THREAD

**Issue by jendave** [hashicorp/terraform-provider-aws#34131]
### Terraform Core Version

1.5.5

### AWS Provider Version

5.23.0

### Affected Resource(s)

* aws_lambda_function

### Expected Behavior

Created lambda function. worked under 5.22.0

### Actual Behavior

got error 

```
Error: setting vpc_config: Invalid address to set: []string{"vpc_config", "0", "ipv6_allowed_for_dual_stack"}
```

### Terraform Configuration Files

```
resource "aws_lambda_function" "lambda" {
  function_name = var.function_name
  description   = var.description
  role          = aws_iam_role.lambda.arn
  image_uri     = var.image_uri
  timeout       = var.timeout
  memory_size   = var.memory_size
  package_type  = var.package_type
  tags          = merge(var.tags, local.tags, { Custodian_Lambda_Error_Exclude = "YES PLEASE" })
  environment {
    variables = merge(var.environment_variables, {
      CLOUDWATCH_LOG_GROUP_NAME = aws_cloudwatch_log_group.lambda.name
      ENVIRONMENT               = var.environment
      REGION                    = var.region
    })
  }

  vpc_config {
    subnet_ids                  = var.subnet_ids
    security_group_ids          = var.security_group_ids
  }
}
```

### Steps to Reproduce

Ran the terraform code using AWS provider 5.22.0. It runs fine.
Under AWS provider 5.23.0 I get the error. 

Reverting back to 5.22.0 resolves the issue

### Would you like to implement a fix?

None

**Comment by tb102122** [comment]
I get the same error when using

│ Error: setting vpc_config: Invalid address to set: []string{"vpc_config", "0", "ipv6_allowed_for_dual_stack"}
│ 

```
data "aws_lambda_function" "setup" {
  function_name = var.function_name
}

**Comment by jendave** [comment]
Yes. Thanks. I made a mistake in my original report. I create the lambda as above, then get the error when I use it as a data resource 
```data "aws_lambda_function" "lambda" {
  function_name = "${var.name}-${var.environment}-lambda"
}
```

**Comment by tb102122** [comment]
even after running the create lambda step with the provider 5.23 the error remains so my assumption is that the problem is in the data provider itself.

**Comment by watarukura** [comment]
Me, too.
This error occurs data of lambda_function with VPC Lambda.
Regular Lambda, this error does not occur.

**Comment by grammeaway** [comment]
To make matters more confusing, I'm experiencing this error, but without any patterns related to whether it's a VPC Lambda or not. Some of them deploy without any issues, some of them get this error.

**Comment by razvanonet** [comment]
same for me, we're using data to get a lambda function and this happens:

```
data "aws_lambda_function" "target_lambda_function" {
  for_each = toset(local.lambda_function_needed)

  function_name = each.key
}
```

**Comment by felipem1210** [comment]
Same here with lambda with VPC config

**Comment by bechampion** [comment]
https://github.com/hashicorp/terraform-provider-aws/compare/v5.22.0..v5.23.0#diff-f133cf8f49371b1c6012c91c42f0d578f772c7d399b5a8a46ce941f55ae97424R414

**Comment by bechampion** [comment]
if you drop to `5.22.0` no issues , i guess I'll pin that version for now

**Comment by SebasAnasco1517** [comment]
Same for me, but in our case it shows the error when a lambda with a kafka trigger is created.

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/34045.

**Comment by prowlaiii** [comment]
Me too!
It's happening in several stacks.
I'll pin the provider version.

**Comment by ccassany** [comment]
Documents deployed on release [2023.43.0: Migration K8S to ECS](https://github.com/fulll/document-manager.app/releases/tag/2023.42.3)
