### ISSUE TITLE
[Enhancement]: User Defined IP on VPC endpoints

### ISSUE THREAD

**Issue by ckotil** [hashicorp/terraform-provider-aws#34147]
### Description

AWS recently added support for VPC Endpoints allowing to pick your own IP:
https://aws.amazon.com/about-aws/whats-new/2023/08/aws-privatelink-user-defined-ip-vpc-endpoints/

The Console UI now supports this as well (step 8):
https://docs.aws.amazon.com/vpc/latest/privatelink/create-interface-endpoint.html#create-interface-endpoint-aws

It looks like this new capability has not yet made its way to the AWS Provider yet. 

One approach could be to allow the aws_vpc_endpoint resource to specify the network_interface_ids. Requiring the Network Interfaces to be provisioned before the VPC Endpoint, and allowing users to choose an IP.

```shell
╷
│ Error: Value for unconfigurable attribute
│
│   with aws_vpc_endpoint.this,
│   on main.tf line 3, in resource "aws_vpc_endpoint" "this":
│    3:     network_interface_ids = [
│    4:         aws_network_interface.test1.id,
│    5:         aws_network_interface.test2.id,
│    6:     ]
│
│ Can't configure a value for "network_interface_ids": its value will be decided automatically based on the result of applying this
│ configuration.
```

Thanks,
--Chad

### Affected Resource(s) and/or Data Source(s)

aws_vpc_endpoint

### Potential Terraform Configuration

```terraform
resource "aws_vpc_endpoint" "this" {
    ip_address_type       = "ipv4"
//    network_interface_ids = [
//        aws_network_interface.test1.id
//        aws_network_interface.test2.id
//    ]
    policy                = jsonencode(
        {
            Statement = [
                {
                    Action    = "*"
                    Effect    = "Allow"
                    Principal = "*"
                    Resource  = "*"
                },
            ]
        }
    )
    private_dns_enabled   = true
    route_table_ids       = []
    security_group_ids    = [
        "sg-0707d83e8bad17a68",
    ]
    service_name          = "aws.sagemaker.us-west-2.studio"
    subnet_ids            = [
        "subnet-06fb9377a141332d4",
        "subnet-0b92395c83428cea0",
    ]
    tags                  = {"Name" = "ckotil-test-tf"}
    tags_all              = {}
    vpc_endpoint_type     = "Interface"
    vpc_id                = "vpc-0c5247b14f09aea8a"

    dns_options {
        dns_record_ip_type                             = "ipv4"
        private_dns_only_for_inbound_resolver_endpoint = false
    }

    timeouts {}
}

resource "aws_network_interface" "test1" {
  subnet_id       = "subnet-06fb9377a141332d4"
  private_ips     = ["10.168.184.81"]
  security_groups = ["sg-0707d83e8bad17a68"]
  tags                  = {"Name" = "ckotil-test-tf-1"}
}

resource "aws_network_interface" "test2" {
  subnet_id       = "subnet-0b92395c83428cea0"
  private_ips     = ["10.168.184.243"]
  security_groups = ["sg-0707d83e8bad17a68"]
    tags                  = {"Name" = "ckotil-test-tf-2"}
}
```

### Would you like to implement a fix?

No

**Comment by noneymous** [comment]
What's the current status on this?

**Comment by ckotil** [comment]
> What's the current status on this?

No movement yet. I think the issue needs more upvotes.

**Comment by noneymous** [comment]
Alright, I upvoted it too, there are some upvotes already :) 

I'm not quite sure why this is not implemented or not more popular. The `aws_vpc_endpoint` resource is not practical currently. It leads to race conditions for the same private IPs, competing with other instances (with fixed IPs) defined in the remaining terraform script. Introducing another subnet for the endpoints just to compensate for the unpredictability is a bit of an overhead. 

Furthermore, having an endpoint that has a different IP each time it is (re-)created, is a bit contrary to its purpose. Obviously, other instances have a more or less static configuration trying to connect to it.

**Comment by ddericco** [comment]
This is being worked on.
