### ISSUE TITLE
[Docs]: service_role should not be required for aws_batch_compute_environment

### ISSUE THREAD

**Issue by tvoipio** [hashicorp/terraform-provider-aws#34143]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/batch_compute_environment

### Description

The provider documentation states that the `service_role` argument to `aws_batch_compute_environment is required`: https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/batch_compute_environment.html.markdown?plain=1#L164

The provider does not actually require the argument to be given and works perfectly well without it; the AWS API method `CreateComputeEnvironment` documentation also states that the service role argument is optional, in the case of which AWS creates a service-linked role automatically.

### References

https://docs.aws.amazon.com/batch/latest/APIReference/API_CreateComputeEnvironment.html#Batch-CreateComputeEnvironment-request-serviceRole

### Would you like to implement a fix?

None

**Comment by tvoipio** [comment]
See also: https://github.com/hashicorp/terraform-provider-aws/issues/19178

**Comment by acwwat** [comment]
The `service_role` argument is already defined as optional so it's just a documentation issue.

https://github.com/hashicorp/terraform-provider-aws/blob/c4c48f075b1987385e8036572b1ed11c6c483ec1/internal/service/batch/compute_environment.go#L228-L233
