### ISSUE TITLE
Add data source for engine versions

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#34168]
### Description

The API `DescribeBrokerEngineTypes` can return a list of valid versions for a given engine type. This can be used to make the data source `aws_mq_engine_version`

### Affected Resource(s) and/or Data Source(s)

aws_mq_engine_version

### Would you like to implement a fix?

None

**Comment by danquack** [comment]
Hey @gdavison I noticed you said the long term issue for #34172 was this one. Just wanted to bring this to your attention. Do we need to create a followup issue for updating all the mq test to subscribe to the new data source?

**Comment by gdavison** [comment]
Thanks, @danquack. I've created #35253
