### ISSUE TITLE
[Enhancement]: `r/aws_redshift_cluster`: Support managed master passwords

### ISSUE THREAD

**Issue by jar-b** [hashicorp/terraform-provider-aws#34169]
### Description

The Redshift [Create|Modify]Cluster API's include a `ManageMasterPassword` argument, which is not implemented in the corresponding Terraform resource. Support should be added similar to the implementation for `aws_db_instance`.

> ManageMasterPassword
> If true, Amazon Redshift uses AWS Secrets Manager to manage this cluster's admin credentials. You can't use MasterUserPassword if ManageMasterPassword is true. If ManageMasterPassword is false or not set, Amazon Redshift uses MasterUserPassword for the admin user account's password.
> 
> Type: Boolean
> 
> Required: No

### Affected Resource(s) and/or Data Source(s)

- aws_redshift_cluster

### Potential Terraform Configuration

```terraform
resource "aws_redshift_cluster" "example" {
  cluster_identifier = "tf-redshift-cluster"
  database_name      = "mydb"
  master_username    = "exampleuser"
  node_type          = "dc1.large"
  cluster_type       = "single-node"

  manage_master_password = true
}
```

### References

- https://docs.aws.amazon.com/redshift/latest/APIReference/API_CreateCluster.html
- https://docs.aws.amazon.com/redshift/latest/APIReference/API_ModifyCluster.html
- https://docs.aws.amazon.com/redshift/latest/mgmt/redshift-secrets-manager-integration.html
- Relates #9183 

### Would you like to implement a fix?

None

**Comment by DrFaust92** [comment]
taking a look

**Comment by jar-b** [comment]
@DrFaust92 - Apologies, I've started on this but forgot to assign myself. Should have a PR up in a bit.

**Comment by DrFaust92** [comment]
@jar-b NP, good thing i didnt start running tests as it would've taken a while
