### ISSUE TITLE
[Bug]: GovCloud FIPS endpoint for EC2 ImageBuilder is incorrect

### ISSUE THREAD

**Issue by slapula** [hashicorp/terraform-provider-aws#34171]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.22.0

### Affected Resource(s)

* aws_imagebuilder_component

### Expected Behavior

Successfully create/modify/delete resource using the FIPS enabled endpoint for EC2 Image Builder 

### Actual Behavior

The AWS provider uses an incorrect endpoint for EC2 Image Builder when FIPS is enabled.

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: creating Image Builder Component: RequestError: send request failed
│ caused by: Put "https://imagebuilder-fips.us-gov-west-1.amazonaws.com/CreateComponent": dial tcp: lookup imagebuilder-fips.us-gov-west-1.amazonaws.com on 172.27.144.1:53: no such host
│ 
│   with module.ami-image-builder.aws_imagebuilder_component.example-component,
│   on ami-image-builder/main.tf line 12, in resource "aws_imagebuilder_component" "example-component":
│   12: resource "aws_imagebuilder_component" "example-component" {
│ 
```

### Terraform Configuration Files

We are using default Terraform configuration settings.

### Steps to Reproduce

1. Enable FIPS in the AWS provider:
```
provider "aws" {
  profile = "example-1-creds"
  alias = "example-1"
  region = var.gov_region
  use_fips_endpoint = true 
}
```
2. Create any EC2 Image Builder resources:
```
resource "aws_imagebuilder_component" "example-component" {
  {...}
}
```
3. Run terraform plan/apply

### Important Factoids

It's been a while, but I have contributed to this provider in the past.  I'll make an attempt to write up a fix and post a PR when ready.  Any and all feedback will be appreciated.

### Would you like to implement a fix?

Yes

**Comment by matthill33** [comment]
I am experiencing the same issue, thanks @slapula for raising this.
