### ISSUE TITLE
[Bug]: Adding Tags to S3 Buckets Causes Perpetual Drift

### ISSUE THREAD

**Issue by tomburge** [hashicorp/terraform-provider-aws#34185]
### Terraform Core Version

Terraform v1.6.2 on windows_amd64

### AWS Provider Version

registry.terraform.io/hashicorp/aws v5.23.1

### Affected Resource(s)

S3 buckets

### Expected Behavior

Tags attached to a S3 bucket are created as defined in the variables or an error should be returned that the tags aren't formatted correctly.

### Actual Behavior

2 scenarios

1. I added tags to the resource with one tag being an empty string and it deleted all tags on the resource. This scenario causes perpetual drift and an immediate plan after deploying, shows changes need to be applied.

2. I added tags to the resource with all tags not being empty strings and the tags applied properly.

This behavior does not occur on another resource I am deploying with the same Terraform which is a VPC.

### Terraform Configuration Files

Minimal Configuration

https://gist.github.com/tomburge/65280e05d2bfd308f78c4b5704dfe826

### Steps to Reproduce

Create a new project.
Create the files from the above gist.
Ensure that version 1.6.2 and AWS provider version 5.23.1 are used.
Plan and deploy with first version of tags. Plan again.
Plan and deploy with second version of tags. Plan again.

Screenshot 1 shows no tags:

![s3 console no tags](https://github.com/hashicorp/terraform-provider-aws/assets/39355437/161079db-b68d-47bd-8e83-f102988efcab)

Screenshot 2 shows tags with an empty tag created from the console:

![s3 console tags with an empty tag](https://github.com/hashicorp/terraform-provider-aws/assets/39355437/072b4c9c-b3c1-439d-b3f5-fcd22a84b1b6)

Screenshot 3 shows the same tags on a VPC.

![vpc console tags](https://github.com/hashicorp/terraform-provider-aws/assets/39355437/a6437c57-ade0-4714-ae21-8c4282ae3116)

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Similar: https://github.com/hashicorp/terraform-provider-aws/issues/30801, https://github.com/hashicorp/terraform-provider-aws/issues/31941.
