### ISSUE TITLE
[Bug]:AWS DocumentDB Major Version Upgrade from 3.6 to 5.0

### ISSUE THREAD

**Issue by hasanaltinkaynak** [hashicorp/terraform-provider-aws#34183]
### Terraform Core Version

0.13.5

### AWS Provider Version

5.22.0

### Affected Resource(s)

AWS DocumentDB Cluster

### Expected Behavior

After updating the engine version as newer, it should apply to upgrade only existing cluster engine & parameter group versions without destroying or replacing the cluster. 

### Actual Behavior

Terraform tries to replace the whole cluster with instances. its trying to create the new cluster with new version and will be trying to destroy old one. Even we apply, its failing, since the new DB will have same NAME and its already exist and says DB is already exist.. 

### Terraform Configuration Files

```terraform
resource "aws_docdb_cluster" "db" {
  apply_immediately               = true
  availability_zones              = var.availability_zones
  db_subnet_group_name            = local.db_subnet_group_name
  db_cluster_parameter_group_name = local.db_cluster_parameter_group_name
  engine_version                  = var.engine_version
  engine                          = var.engine
  skip_final_snapshot             = true
  allow_major_version_upgrade     = true
  ......
  ......
```

### Steps to Reproduce

create the Document DB with 3.6 version
change the engine and parameter group versions as 5.0 and APPLY

### Debug Output

similar output for DB instances as well

```shell
  # module.test_upgrade_docdb_50.aws_docdb_cluster.db[0] must be replaced
+/- resource "aws_docdb_cluster" "db" {
        allow_major_version_upgrade     = true
        apply_immediately               = true
      ~ arn                             = "arn:aws:rds:*:*:cluster:XXX-XXX-docdb-3-6-dev-ue1-docdb-cluster" -> (known after apply)
      ~ availability_zones              = [ # forces replacement
            "us-east-1a",
            "us-east-1b",
          - "us-east-1f",
        ]
        backup_retention_period         = 7
        cluster_identifier              = "XXXX-docdb-3-6-dev-ue1-docdb-cluster"
      + cluster_identifier_prefix       = (known after apply)
      ~ cluster_members                 = [
          - "XXX-docdb-3-6-dev-ue1-docdb-cluster-1",
        ] -> (known after apply)
      ~ cluster_resource_id             = "cluster-xxxxx" -> (known after apply)
        db_cluster_parameter_group_name = "xxxx-docdb-3-6-dev-ue1-docdb-cluster"
        db_subnet_group_name            = "xxxx-docdb-3-6-dev-ue1-docdb-cluster"
        deletion_protection             = false
        enabled_cloudwatch_logs_exports = [
            "audit",
        ]
      ~ endpoint                        = "xxxx-docdb-3-6-dev-ue1-docdb-cluster.cluster-clng87gvpoji.us-east-1.docdb.amazonaws.com" -> (known after apply)
        engine                          = "docdb"
      ~ engine_version                  = "3.6.0" -> "5.0.0"
----

--  DBClusterAlreadyExistsFault: DB Cluster already exists
```

### Would you like to implement a fix?

None

**Comment by trevorrea** [comment]
No related to this bug but even if it did work AWS are currently disallowing DocumentDB major version upgrades. See https://docs.aws.amazon.com/documentdb/latest/developerguide/docdb-mvu.html

**Comment by justinretzolk** [comment]
Hey @hasanaltinkaynak 👋 Thank you for taking the time to raise this! Unless I'm misinterpreting something, it looks like in the case of the logs that you provided, the reason that the cluster is being replaced is due to a change in the `availability_zones` argument:

```shell
      ~ availability_zones              = [ # forces replacement
            "us-east-1a",
            "us-east-1b",
          - "us-east-1f",
        ]
```

**Comment by hasanaltinkaynak** [comment]
Thank you, @justinretzolk . I've reproduced the case and it just tried to modify the engine version. BUT got the error below. do u have any idea, is it related to AWS docdb issue[1]?

`Error: modifying DocumentDB Cluster (test-upgrade-docdb-3-6-dev-ue1-docdb-cluster): InvalidParameterCombination: Can't upgrade docdb from 3.6.0 to 5.0.0`

[https://docs.aws.amazon.com/documentdb/latest/developerguide/docdb-mvu.html](url)  [1]

**Comment by justinretzolk** [comment]
Hey @hasanaltinkaynak 👋 It's definitely possible that the error you're receiving is due to the DocDB MVU freeze. Debug logging might have additional information, if you're able to supply those logs (redacted as needed).

**Comment by hasanaltinkaynak** [comment]
Hi, 

AWS has enable the allowing the major version upgrade and I tested the version upgrade from 3.6 to 5.0, but there is an issue here.

the upgraded docdb needs to be attached to the newer parameter group(5.0), and after db cluster upgrade is done, the old parameter could be destroyed. BUT at this point, terraform is trying to destroy the old parameter group before upgrade is completed. since the existing db attached to old parameter group, it can't be destroyed, then the process is failing.

I added the lifecycle for docdb parameter group but terraform is still trying to destroy old parameter group so the whole upgrading is failing. Could you check is there anything I might be missed?

terraform version: 0.13.5
aws provider version: 5.22.0

```
resource "aws_docdb_cluster_parameter_group" "params" {
  count       = var.enabled ? 1 : 0
  name        = "${module.db_naming.id}-50"
  family      = var.parameter_group_family
  description = var.parameter_group_description

  dynamic "parameter" {
    for_each = var.parameter_group_parameters
    content {
      apply_method = lookup(parameter.value, "apply_method", null)
      name         = parameter.value.name
      value        = parameter.value.value
    }
  }

  lifecycle {
    prevent_destroy = true
    create_before_destroy = true
  }
```

```
# module.test_upgrade_docdb_50.aws_docdb_cluster_parameter_group.params[0] (deposed object b8add7ed) will be destroyed
  - resource "aws_docdb_cluster_parameter_group" "params" {
      - arn         = "arn:aws:rds:us-east-1:532796716297:cluster-pg:test-upgrade-docdb-36-dev-ue1-docdb-cluster" -> null
      - description = "Managed by Terraform" -> null
      - family      = "docdb3.6" -> null
      - id          = "test-upgrade-docdb-36-dev-ue1-docdb-cluster" -> null
      - name        = "test-upgrade-docdb-36-dev-ue1-docdb-cluster" -> null
      - tags        = {
          - "Name" = "test-upgrade-docdb-36-dev-ue1-docdb-cluster"
        } -> null
      - tags_all    = {
          - "Name" = "test-upgrade-docdb-36-dev-ue1-docdb-cluster"
        } -> null

      - parameter {
          - apply_method = "immediate" -> null
          - name         = "audit_logs" -> null
          - value        = "enabled" -> null
        }
      - parameter {
          - apply_method = "pending-reboot" -> null
          - name         = "tls" -> null
          - value        = "disabled" -> null
        }
    }
```

**Comment by hasanaltinkaynak** [comment]
added another parameter group for newer version and keep the old parameter version resource. then switch the parameter group to newer one on the docdb cluster resources definition. After completing the upgrade, clean up the old parameter.
