### ISSUE TITLE
[Bug]: Missing support for multiple custom images in sagemaker studio domain

### ISSUE THREAD

**Issue by galko1** [hashicorp/terraform-provider-aws#34198]
### Terraform Core Version

0.14.8

### AWS Provider Version

5.22.0

### Affected Resource(s)

The bug is in `kernel_gateway_app_settings`, which affects every resource that can include it, including `aws_sagemaker_domain` and `aws_sagemaker_user_profile`

### Expected Behavior

AWS lets one define multiple custom image per `kernel_gateway_app_settings`, by setting `custom_images = [custome_image, custom_image, custom_image, ...]`, where `custom_image` contains configuration details of the image such as: `app_image_config_name`, and `image_name`. 

The excepted behavior is the support of multiple custom images in `kernel_gateway_app_settings`. 

### Actual Behavior

In terraform, there isn't a `custom_images` attribute, but the documentation for `custom_image` is misleading and refers to the expected behavior

> [custom_image](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_domain#custom_image) - (Optional) A list of custom SageMaker images that are configured to run as a KernelGateway app. see [Custom Image](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_domain#custom_image) below.

When trying to configure a list of images using either `custom_image` or `custom_images` within a `aws_sagemaker_domain`,  an error is being raised. 

### Relevant Error/Panic Output Snippet

The type of error when trying to set `custom_images`:

```shell
Error: Unsupported argument

  on ../../../../tf_modules/sagemaker_studio/domain/main.tf line 16, in resource "aws_sagemaker_domain" "aws_sagemaker_domain":
  16:       custom_images = [

An argument named "custom_images" is not expected here.
```

When trying to set a list of custom images within `custom_image`, the error we get is

```
Error: Unsupported argument

  on ../../../../tf_modules/sagemaker_studio/domain/main.tf line 16, in resource "aws_sagemaker_domain" "aws_sagemaker_domain":
  16:       custom_image = [

An argument named "custom_image" is not expected here. Did you mean to define
a block of type "custom_image"?
```

### Terraform Configuration Files

configuring `kernel_gateway_app_settings` within `aws_sagemaker_domain` within `default_user_settings`: 

```
    kernel_gateway_app_settings {
      custom_images = [
        for k,v in var.custom_images:
        {
        app_image_config_name = v["app_image_config_name"]
        image_name            = v["image_name"]
        }
      ]
    }
```

or 

```
    kernel_gateway_app_settings {
      custom_image = [
        for k,v in var.custom_images:
        {
        app_image_config_name = v["app_image_config_name"]
        image_name            = v["image_name"]
        }
      ]
    }

```

### Steps to Reproduce

configuring `kernel_gateway_app_settings` within `aws_sagemaker_domain` within `default_user_settings`: 

```
    kernel_gateway_app_settings {
      custom_images = [
        for k,v in var.custom_images:
        {
        app_image_config_name = v["app_image_config_name"]
        image_name            = v["image_name"]
        }
      ]
    }
```

or 

```
    kernel_gateway_app_settings {
      custom_image = [
        for k,v in var.custom_images:
        {
        app_image_config_name = v["app_image_config_name"]
        image_name            = v["image_name"]
        }
      ]
    }

```

### References

https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_KernelGatewayAppSettings.html

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @galko1 👋 Thank you for taking the time to raise this! I believe this will behave like the resources described in the [Dynamic Blocks documentation](https://developer.hashicorp.com/terraform/language/expressions/dynamic-blocks). This passed `terraform validate`:

```terraform
    kernel_gateway_app_settings {
      custom_image {
        app_image_config_name = aws_sagemaker_app_image_config.example.app_image_config_name
        image_name            = aws_sagemaker_image_version.example.image_name
      }

      custom_image {
        app_image_config_name = aws_sagemaker_app_image_config.example.app_image_config_name
        image_name            = aws_sagemaker_image_version.example.image_name
      }
    }
```

If you'd prefer to use a dynamic block, like the `for` loops you provided in the examples, that might look something like:

```terraform
    kernel_gateway_app_settings {
      dynamic "custom_image" {
        for_each = var.custom_images
        content {
          app_image_config_name = custom_image.value["app_image_config_name"]
          image_name            = custom_image.value["image_name"]
        }
      }
    }
```
