### ISSUE TITLE
[Bug]:  aws_rds_global_cluster resource kicks out global_cluster_members when reapplied

### ISSUE THREAD

**Issue by lukevo247** [hashicorp/terraform-provider-aws#34203]
### Terraform Core Version

0.13+, 1.x

### AWS Provider Version

4.x.x, 5.x.x

### Affected Resource(s)

aws_rds_global_cluster, aws_rds_cluster

### Expected Behavior

After creation of aws_rds_global_clusters from an existing DB cluster users should be able to reapply the resource without booting all new global cluster members out of the global cluster. Ignoring all lifecycle changes does not fix behavior.

```terraform
lifecycle {
    ignore_changes = [
      global_cluster_identifier,
      source_db_cluster_identifier,
      engine_version
    ]
  }
```

- User has pre-existing aws_rds_cluster "primary" resource.
- User creates aws_rds_global_cluster resource with argument source_db_cluster_identifier.
- User creates aws_rds_cluster "secondary" resource with argument global_cluster_identifier.
- User is able to reapply all resources without any adverse effects like resource replace/destroy.

### Actual Behavior

Reapplying the `aws_rds_global_cluster` will boot out all new clusters in the resource.

### Relevant Error/Panic Output Snippet

```shell
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aws_rds_global_cluster.this must be replaced
-/+ resource "aws_rds_global_cluster" "this" {
      ~ arn                          = "arn:aws:rds::123456789:global-cluster:example-global-cluster" -> (known after apply)
      - database_name                = "exampledb" -> null # forces replacement
      ~ engine                       = "aurora-postgresql" -> (known after apply)
      ~ engine_version               = "15.2" -> (known after apply)
      ~ engine_version_actual        = "15.2" -> (known after apply)
      ~ global_cluster_members       = [] -> (known after apply)
      ~ global_cluster_resource_id   = "cluster-123456789" -> (known after apply)
      ~ id                           = "example-global-cluster" -> (known after apply)
      ~ storage_encrypted            = true -> (known after apply)
        # (4 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Changes to Outputs:
  ~ global_cluster_arn         = "arn:aws:rds::123456789:global-cluster:example-global-cluster" -> (known after apply)
  ~ global_cluster_id          = "example-global-cluster" -> (known after apply)
  ~ global_cluster_members     = [
      - {
          - db_cluster_arn = "arn:aws:rds:us-west-2:123456789:cluster:example-primary-aurorav2-psql-rds"
          - is_writer      = true
        },
    ] -> (known after apply)
  ~ global_cluster_resource_id = "cluster-123456789" -> (known after apply)
```

### Terraform Configuration Files

```terraform
resource "aws_rds_global_cluster" "this" {
  force_destroy                = var.force_destroy #True or False does not matter
  global_cluster_identifier    = "${var.name}-global-cluster"
  source_db_cluster_identifier = var.source_db_cluster_identifier  #Set this value to the primary rds cluster
  storage_encrypted   = var.storage_encrypted
  deletion_protection = var.deletion_protection
  engine         = var.engine
  engine_version = var.engine_version

  lifecycle {
    ignore_changes = [
      global_cluster_identifier,
      source_db_cluster_identifier,
      engine_version
    ]
  }
}

variable "name" {
  type        = string
  description = "Base identifier to use for naming resources created by this module as created by the identifier-format module."

}

variable "deletion_protection" {
  description = "(Optional) If the Global Cluster should have deletion protection enabled. The database can't be deleted when this value is set to `true`. The default is `true`."
  type        = string
  default     = true
}

variable "engine" {
  description = "(Optional, Forces new resources) Name of the database engine to be used for this DB cluster. Terraform will only perform drift detection if a configuration value is provided. Valid values: aurora, aurora-mysql, aurora-postgresql. Defaults to aurora. Conflicts with source_db_cluster_identifier."
  type        = string
  default     = null
}

variable "engine_version" {
  description = "(Optional) Engine version of the Aurora global database. The engine, engine_version, and instance_class (on the aws_rds_cluster_instance) must together support global databases. See Using Amazon Aurora global databases for more information. By upgrading the engine version, Terraform will upgrade cluster members. NOTE: To avoid an inconsistent final plan error while upgrading, use the lifecycle ignore_changes for engine_version meta argument on the associated aws_rds_cluster resource as shown above in Upgrading Engine Versions example."
  type        = string
  default     = null
}

variable "force_destroy" {
  description = "(Optional) Enable to remove DB Cluster members from Global Cluster on destroy. Required with source_db_cluster_identifier. Default is false."
  type        = string
  default     = false
}

variable "source_db_cluster_identifier" {
  description = "(Optional) Amazon Resource Name (ARN) to use as the primary DB Cluster of the Global Cluster on creation. Terraform cannot perform drift detection of this value."
  type        = string
  default     = null
}

variable "storage_encrypted" {
  description = "(Optional, Forces new resources) Specifies whether the DB cluster is encrypted. The default is false unless source_db_cluster_identifier is specified and encrypted. Terraform will only perform drift detection if a configuration value is provided."
  type        = string
  default     = null
}
```

### Steps to Reproduce

- User has pre-existing aws_rds_cluster "primary" resource.
- User deploys aws_rds_global_cluster resource with argument source_db_cluster_identifier.
- User deploys aws_rds_cluster "secondary" resource with argument global_cluster_identifier.

At this point everything is fine... However, if/when the aws_rds_global_cluster resource is applied again, all global cluster members are booted out of the global cluster.

Note: Each resource is deployed individually from their own terraform modules and not in a single combined module. This is largely due to resource deployment patterns where primary and secondary rds clusters exist in different AWS regions. And the global cluster resource TF exists under a global subdirectory.

### Important Factoids

Global clusters created from an existing DB are only supplied the source_db_cluster_identifier and name. 
All other parameters are intended for usage with new RDS cluster deployments. (i.e. engine, version, etc.)

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @lukevo247 👋 Thank you for taking the time to raise this! It looks like the replacement is coming from a difference between the value stored in state and what is being read from AWS during the planning for `database_name`:

```shell
      - database_name                = "exampledb" -> null # forces replacement
```

This very well may still be a bug (I'll leave that to whoever picks this up to decide), but you may be able to get around this by ignoring changes to `database_name`. There may also be a configuration change that you can make to correct this, but that wasn't immediately obvious to me while triaging.

**Comment by justinretzolk** [comment]
Hey @lukevo247 👋 I wanted to follow up here to see if you're still having issues with this. When reviewing it again before this follow up, I noted that the sample configuration doesn't have `database_name` defined, which may have been the issue in the first place.

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
