### ISSUE TITLE
[Enhancement]: Add Multi-Session support to AppStream Fleets

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#34245]
### Description

AWS recently announced that it has added Multi-session capability to AppStream 2.0 fleets. See References for a link to the blog post.

It would be great to update the aws_appstream_fleet resource to take advantage of this new feature.

The AWS CLI options that handle this are --max-sessions-per-instance and --compute-capacity, as far as I can see.

### Affected Resource(s) and/or Data Source(s)

* aws_appstream_fleet

### Potential Terraform Configuration

```terraform
resource "aws_appstream_fleet" "test_fleet" {
  name = "test-fleet"

  compute_capacity {
    #desired_instances = 1     # existing option for a Single-Session Fleet
    desired_sessions = 1       # New option for a Mutli-Session Fleet (integer)
  }

  <snip>
  max_sessions_per_instance = 5   # New option for a Multi-Session Fleet (integer)
}
```

### References

AWS Blog Post about multi-session Fleets: https://aws.amazon.com/about-aws/whats-new/2023/10/amazon-appstream-2-0-session-fleets-windows-server-os/
AWS CLI Reference link to "create-fleet": https://awscli.amazonaws.com/v2/documentation/api/latest/reference/appstream/create-fleet.html

### Would you like to implement a fix?

No

**Comment by DanielRieske** [comment]
@ElliotPage-EI Thanks for raising this issue, I'll gladly pick it up and will add the PR shortly.
