### ISSUE TITLE
Global Accelerator cross-account endpoints

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#34254]
> Starting today, AWS Global Accelerator supports cross-account endpoints, allowing you to access endpoints in multiple accounts using a single accelerator.

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2023/11/cross-account-support-aws-global-accelerator/)
* [Blog post](https://aws.amazon.com/blogs/networking-and-content-delivery/announcing-cross-account-support-for-aws-global-accelerator/)

Requires [AWS SDK for Go v1.47.1](https://github.com/aws/aws-sdk-go/releases/tag/v1.47.1): https://github.com/hashicorp/terraform-provider-aws/pull/34214.

### New Resource(s)

* `aws_globalaccelerator_cross_account_attachment`

#### Modified Resource(s)

* `aws_globalaccelerator_custom_routing_endpoint_group` -- add `endpoint_configuration. attachment_arn`

**Comment by kathmbeck** [comment]
👋 I've started drafting a PR for this issue.

**Comment by jreynoso-ring** [comment]
I also think it should be added in 

`aws_globalaccelerator_endpoint_group -- endpoint_configuration. attachment_arn`

instead of

`aws_globalaccelerator_custom_routing_endpoint_group -- endpoint_configuration. attachment_arn`

**Comment by rybit** [comment]
Started to add it here: https://github.com/hashicorp/terraform-provider-aws/pull/37269 -- just working through the details. Feel free to lend a hand!
