### ISSUE TITLE
[Enhancement]: Add support for elastic search index lifecycle policy

### ISSUE THREAD

**Issue by vravishvmware** [hashicorp/terraform-provider-aws#34298]
### Description

Add support for index lifecycle policy changes for elasticsearch. This feature should help creating several policies related to periodic purging of data, moving data around different storage etc. 

### Potential Terraform Configuration

```terraform
resource elasticsearch_index_lifecycle_policy "test" {
  name = "terraform-test"
  policy = <<EOF
{
  "policy": {
    "phases": {
      "warm": {
        "min_age": "10d",
        "actions": {
          "forcemerge": {
            "max_num_segments": 1
          }
        }
      },
      "delete": {
        "min_age": "30d",
        "actions": {
          "delete": {}
        }
      }
    }
  }
}
EOF
}
```

### Would you like to implement a fix?

None

**Comment by DrFaust92** [comment]
Hi, i dont think this is in the scope of the AWS provider as this requires work with elasticsearch API directly (AWS does not expose such actions as API calls)

This should work after you create the cluster on AWS and authenticate to that cluster
https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/resources/elasticsearch_index_lifecycle
