### ISSUE TITLE
[Bug]: "blue_green_update.enabled" cannot be set when "engine" is "postgres".

### ISSUE THREAD

**Issue by dpedu** [hashicorp/terraform-provider-aws#34317]
### Terraform Core Version

1.5

### AWS Provider Version

5.24.0

### Affected Resource(s)

* aws_db_instance

### Expected Behavior

Terraform upgrades the db instance using a blue/green deployment

### Actual Behavior

Terraform decides it cannot upgrade the db instance:

```
│ Error: 1 error occurred:
│ 	* "blue_green_update.enabled" cannot be set when "engine" is "postgres".
```

### Relevant Error/Panic Output Snippet

```shell
│ Error: 1 error occurred:
│ 	* "blue_green_update.enabled" cannot be set when "engine" is "postgres".
```

### Terraform Configuration Files

N/a

### Steps to Reproduce

N/a

### Important Factoids

Support for blue/green upgrades for postgres under RDS was introduced recently:

https://aws.amazon.com/blogs/database/new-fully-managed-blue-green-deployment-in-amazon-aurora-postgresql-and-amazon-rds-for-postgresql/

Why the provider previously needed this check instead of bouncing off the aws api is beyond me.

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@dpedu Thanks for raising this issue 👏.
This has been addressed via https://github.com/hashicorp/terraform-provider-aws/pull/34216 which will be released with Terraform AWS Provider **v5.25.0**, likely tomorrow.
