### ISSUE TITLE
Block Public Sharing of Amazon EBS Snapshots

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#34347]
> Amazon Elastic Block Store (EBS) now supports Block Public Access for EBS Snapshots, an account-wide security setting that allows customers to block public sharing of EBS Snapshots in an AWS Region.

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-elastic-block-store-public-access-ebs-snapshots/)
* [Blog post](https://aws.amazon.com/blogs/aws/new-block-public-sharing-of-amazon-ebs-snapshots/)

Requires [AWS SDK for Go v1.47.8](https://github.com/aws/aws-sdk-go/releases/tag/v1.47.8): https://github.com/hashicorp/terraform-provider-aws/pull/34332.

### New Resource(s)

* `aws_ebs_snapshot_block_public_access`

**Comment by Ook3000** [comment]
Any news on this?
