### ISSUE TITLE
[Enhancement]: Local write forwarding

### ISSUE THREAD

**Issue by quentinlacrouts** [hashicorp/terraform-provider-aws#34346]
### Description

AWS recently added a functionality to enable write forwarding within the local cluster
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-mysql-write-forwarding.html#aurora-mysql-write-forwarding-consistency

Could that be implemented in the provider ? 

Thank you

### Affected Resource(s) and/or Data Source(s)

* aws_rds_cluster

**Comment by ewbankkit** [comment]
* [Aurora MySQL announcement](https://aws.amazon.com/about-aws/whats-new/2023/07/amazon-aurora-local-write-forwarding-aurora-mysql/)
* [Aurora Global Database for PostgreSQL announcement](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-aurora-global-database-postgresql-forwarding/)
