### ISSUE TITLE
[Bug]: aws_dms_replication_config always reports as needing modification

### ISSUE THREAD

**Issue by evanstachowiak** [hashicorp/terraform-provider-aws#34348]
### Terraform Core Version

1.6.2

### AWS Provider Version

5.24.0

### Affected Resource(s)

aws_dms_replication_config

### Expected Behavior

After running terraform apply, a subsequent run of terraform plan should indicate no changes needed.

### Actual Behavior

The plan continually requires modifications of the CloudWatchLogGroup and CloudWatchLogStream setting.

This looks like it was resolved for other DMS resources here: https://github.com/hashicorp/terraform-provider-aws/issues/1513

@DanielRieske , maybe you could take a look since you are the author this resource? https://github.com/hashicorp/terraform-provider-aws/issues/32162

### Terraform Configuration Files

    "aws_dms_replication_config": {
      "dms_replication_config": {
        "//": {
          "metadata": {
            "path": "service/dms/dms_replication_config",
            "uniqueId": "dms_replication_config"
          }
        },
        "compute_config": {
          "max_capacity_units": 128,
          "min_capacity_units": 1,
          "multi_az": false,
          "replication_subnet_group_id": "${data.aws_dms_replication_subnet_group.aws_data_dms_replication_subnet_group_private.id}",
          "vpc_security_group_ids": [
            "${aws_security_group.dms.id}"
          ]
        },
        "replication_config_identifier": "service",
        "replication_settings": "{\"BeforeImageSettings\":null,\"ChangeProcessingDdlHandlingPolicy\":{\"HandleSourceTableAltered\":true,\"HandleSourceTableDropped\":true,\"HandleSourceTableTruncated\":true},\"ChangeProcessingTuning\":{\"BatchApplyMemoryLimit\":500,\"BatchApplyPreserveTransaction\":true,\"BatchApplyTimeoutMax\":30,\"BatchApplyTimeoutMin\":1,\"BatchSplitSize\":0,\"CommitTimeout\":1,\"MemoryKeepTime\":60,\"MemoryLimitTotal\":1024,\"MinTransactionSize\":1000,\"StatementCacheSize\":50},\"CharacterSetSettings\":null,\"ControlTablesSettings\":{\"CommitPositionTableEnabled\":false,\"ControlSchema\":\"\",\"FullLoadExceptionTableEnabled\":false,\"HistoryTableEnabled\":false,\"historyTimeslotInMinutes\":5,\"HistoryTimeslotInMinutes\":5,\"StatusTableEnabled\":false,\"SuspendedTablesTableEnabled\":false},\"ErrorBehavior\":{\"ApplyErrorDeletePolicy\":\"IGNORE_RECORD\",\"ApplyErrorEscalationCount\":0,\"ApplyErrorEscalationPolicy\":\"LOG_ERROR\",\"ApplyErrorFailOnTruncationDdl\":false,\"ApplyErrorInsertPolicy\":\"LOG_ERROR\",\"ApplyErrorUpdatePolicy\":\"LOG_ERROR\",\"DataErrorEscalationCount\":0,\"DataErrorEscalationPolicy\":\"SUSPEND_TABLE\",\"DataErrorPolicy\":\"LOG_ERROR\",\"DataTruncationErrorPolicy\":\"LOG_ERROR\",\"EventErrorPolicy\":\"IGNORE\",\"FailOnNoTablesCaptured\":true,\"FailOnTransactionConsistencyBreached\":false,\"FullLoadIgnoreConflicts\":true,\"RecoverableErrorCount\":-1,\"RecoverableErrorInterval\":5,\"RecoverableErrorStopRetryAfterThrottlingMax\":true,\"RecoverableErrorThrottling\":true,\"RecoverableErrorThrottlingMax\":1800,\"TableErrorEscalationCount\":0,\"TableErrorEscalationPolicy\":\"STOP_TASK\",\"TableErrorPolicy\":\"SUSPEND_TABLE\"},\"FailTaskWhenCleanTaskResourceFailed\":false,\"FullLoadSettings\":{\"CommitRate\":10000,\"CreatePkAfterFullLoad\":false,\"StopTaskCachedChangesApplied\":false,\"StopTaskCachedChangesNotApplied\":false,\"TargetTablePrepMode\":\"DROP_AND_CREATE\",\"TransactionConsistencyTimeout\":600,\"MaxFullLoadSubTasks\":8},\"Logging\":{\"CloudWatchLogGroup\":\"dms-serverless-replication-*\",\"CloudWatchLogStream\":\"dms-serverless-serv-res-id-*-vx\",\"EnableLogContext\":false,\"EnableLogging\":true,\"LogComponents\":[{\"Id\":\"TRANSFORMATION\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"SOURCE_UNLOAD\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"IO\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"TARGET_LOAD\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"PERFORMANCE\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"SOURCE_CAPTURE\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"SORTER\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"REST_SERVER\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"VALIDATOR_EXT\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"TARGET_APPLY\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"TASK_MANAGER\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"TABLES_MANAGER\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"METADATA_MANAGER\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"FILE_FACTORY\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"COMMON\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"ADDONS\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"DATA_STRUCTURE\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"COMMUNICATION\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"FILE_TRANSFER\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"}]},\"LoopbackPreventionSettings\":null,\"PostProcessingRules\":null,\"StreamBufferSettings\":{\"CtrlStreamBufferSizeInMB\":5,\"StreamBufferCount\":3,\"StreamBufferSizeInMB\":8},\"TargetMetadata\":{\"BatchApplyEnabled\":false,\"FullLobMode\":false,\"InlineLobMaxSize\":0,\"LimitedSizeLobMode\":true,\"LoadMaxFileSize\":0,\"LobMaxSize\":32,\"LobChunkSize\":64,\"ParallelApplyBufferSize\":0,\"ParallelApplyQueuesPerThread\":0,\"ParallelApplyThreads\":0,\"ParallelLoadBufferSize\":0,\"ParallelLoadQueuesPerThread\":0,\"ParallelLoadThreads\":0,\"SupportLobs\":true,\"TargetSchema\":\"\",\"TaskRecoveryTableEnabled\":false},\"TTSettings\":{\"EnableTT\":false,\"FailTaskOnTTFailure\":false,\"TTRecordSettings\":null,\"TTS3Settings\":null}}",
        "replication_type": "full-load-and-cdc",
        "source_endpoint_arn": "${aws_dms_endpoint.service.endpoint_arn}",
        "start_replication": true,
        "table_mappings": "{\"rules\":[{\"rule-type\":\"selection\",\"rule-id\":\"1\",\"rule-name\":\"1\",\"object-locator\":{\"schema-name\":\"table\",\"table-name\":\"%\"},\"rule-action\":\"include\"}]}",
        "target_endpoint_arn": "${aws_dms_endpoint.service.endpoint_arn}"
      }
    },

### Steps to Reproduce

Deploy aws_dms_replication_config and then run `terraform plan` again.

### Would you like to implement a fix?

None

**Comment by DanielRieske** [comment]
@evanstachowiak Absolutely, I'd love to, the issue you linked seems to be related to the issue you are encountering.

After reading through the comments and the eventual fix, this issue comes from certain properties within `replication_settings` that aren't user configurable and cannot be set on creation nor modified.

In short this means that when we read this particular property we need to remove these values out of the JSON blob as we otherwise have a perpetual change with our current state.

I'll happily pick this up and create a fix for it, I'll create a PR for this later today.

**Comment by suvhotta** [comment]
@DanielRieske Thanks for raising a PR for the fix. I'm also facing the same issue. Is there any temporary stop gap solution that I can implement to remove read-only properties from `replication_settings` to suppress diffs, till the PR is merged?

**Comment by DanielRieske** [comment]
Hi @suvhotta, the only way I can think of is adding a lifecycle to ignore changes/diffs on this particular field.

```
lifecycle {
  ignore_changes = [
    replication_settings
  ]
}
```

Hope this helps while the PR is under review.

**Comment by suvhotta** [comment]
@DanielRieske Thank you for the suggestion. But if we don't have to ignore the replication_settings whole json and need to just ignore the read-only fields, is there a way we can do that?
I tried doing it this way:
```
lifecycle {
  ignore_changes = [
    replication_settings.ControlTablesSettings
  ]
}
```
Its failing because internally the replication_settings is a string representation of the json obj. I also tried with json_decode but that's also not working. 
Any suggestions here?

**Comment by DanielRieske** [comment]
@suvhotta Unfortunatly I don't think there is a way to do this, as far as I know `ignore_changes` work by taking the current value in the state-file in the diff instead of the new value from the read operation.

It doesn't have a concept of what's inside the value as it isn't relevant.
