### ISSUE TITLE
[New Service]: Amazon OpenSearch Ingestion - Service Client

### ISSUE THREAD

**Issue by farhanangullia** [hashicorp/terraform-provider-aws#34341]
### Description

Amazon OpenSearch Ingestion is a new fully managed data ingestion tier that allows you to ingest and process petabyte-scale data before indexing it in OpenSearch-managed clusters or serverless collections. OpenSearch Ingestion provides a no-code capability to filter, transform, redact, and route data prior to indexing it in OpenSearch. OpenSearch Ingestion automatically provisions and scales the underlying resources for even the most demanding and unpredictable workloads. 

Relates to #31364

### Requested Resource(s) and/or Data Source(s)

* aws_osis_pipeline

### References

- https://aws.amazon.com/about-aws/whats-new/2023/04/amazon-opensearch-service-ingestion/
- https://pkg.go.dev/github.com/aws/aws-sdk-go/service/osis

### Would you like to implement a fix?

Yes

**Comment by thunder-spb** [comment]
Hey, guys.
So, is that functionality available or not? No any mention on this in change log and provider documentation... I'm confused, @ewbankkit :)

**Comment by thunder-spb** [comment]
Thanks for the clarification, @farhanangullia !
