### ISSUE TITLE
[Enhancement]: Need to add support for new lambda runtime provided.al2023

### ISSUE THREAD

**Issue by gwsu2008** [hashicorp/terraform-provider-aws#34360]
### Description

Currently aws provider lambda custom runtime does not support provided.al2023. This is a new custom lambda runtime from AWS.
https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html

![image](https://github.com/hashicorp/terraform-provider-aws/assets/11874389/0eb31aee-ec9a-4592-8003-c0b669ffb26b)

```
Initializing provider plugins...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Using previously-installed hashicorp/aws v5.25.0

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Releasing state lock. This may take a few moments...
╷
│ Error: expected runtime to be one of ["nodejs" "nodejs4.3" "nodejs6.10" "nodejs8.10" "nodejs10.x" "nodejs12.x" "nodejs14.x" "nodejs16.x" "java8" "java8.al2" "java11" "python2.7" "python3.6" "python3.7" "python3.8" "python3.9" "dotnetcore1.0" "dotnetcore2.0" "dotnetcore2.1" "dotnetcore3.1" "dotnet6" "nodejs4.3-edge" "go1.x" "ruby2.5" "ruby2.7" "provided" "provided.al2" "nodejs18.x" "python3.10" "java17" "ruby3.2" "python3.11" "nodejs20.x"], got provided.al2023
│
│   with aws_lambda_function.yopass,
│   on lambda.tf line 30, in resource "aws_lambda_function" "yopass":
│   30:   runtime = "provided.al2023"
│
```

### Affected Resource(s) and/or Data Source(s)

provider version: aws v5.25.0

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
Some observations: This custom runtime was added only a few days ago. See [Introducing the Amazon Linux 2023 runtime for AWS Lambda](https://aws.amazon.com/blogs/compute/introducing-the-amazon-linux-2023-runtime-for-aws-lambda/). It looks like the Go SDK change made it to [v1.47.8](https://github.com/aws/aws-sdk-go/pull/5063) and the PR #34331 to upgrade the dependency for the provider is already merged and targeted for v5.26.0.
