### ISSUE TITLE
[Bug]: aws_dynamodb_table with replica and autoscaling creates unmanaged cloudwatch alarms

### ISSUE THREAD

**Issue by tb00-cloud** [hashicorp/terraform-provider-aws#34361]
### Terraform Core Version

v1.6.3

### AWS Provider Version

4.67.0

### Affected Resource(s)

aws_dynamodb_table

### Expected Behavior

All resources created when using the replica block should be managed by Terraform. Including the autoscaling resources.

### Actual Behavior

To use the replica block you have to enable either the autoscaling or pay per request billing modes. When using autoscaling, the replica table will also create Cloudwatch alarms for target tracking which facilitates the autoscale. When destroying, these alarms are left active. 

Presumably, this is because terraform only manages the replica table that is created. AWS automatically generates the other resources that are needed to mirror the primary table. Having said that, I checked the autoscaling resources in my replica region which do appear to have been deleted. I would have expected the respective alarms to be deleted also. 

### Relevant Error/Panic Output Snippet

```shell
N/A
```

### Terraform Configuration Files

I'm deploying DynamoDB via a module. This is the configuration I have for the resource in the module. Note - you also need to deploy autoscaling on the table. 

```
resource "aws_dynamodb_table" "this_autoscaled" {
  count = var.autoscaling_configuration != null ? 1 : 0
  name  = local.table_name
  point_in_time_recovery {
    enabled = var.pitr_enabled
  }
  billing_mode                = var.billing_mode
  read_capacity               = var.capacity.read
  write_capacity              = var.capacity.write
  stream_enabled              = length(var.replica_regions) > 0 ? true : var.streams_enabled
  stream_view_type            = length(var.replica_regions) > 0 ? "NEW_AND_OLD_IMAGES" : var.stream_view_type
  hash_key                    = var.hash_key
  range_key                   = var.range_key
  deletion_protection_enabled = var.protect_from_deletion

  dynamic "server_side_encryption" {
    for_each = var.kms_key_arn != null ? [1] : []
    content {
      enabled     = true
      kms_key_arn = var.kms_key_arn != null ? var.kms_key_arn : null
    }
  }

  dynamic "attribute" {
    for_each = var.attributes
    content {
      name = attribute.key
      type = attribute.value.type
    }
  }

  dynamic "ttl" {
    for_each = var.ttl_attribute_name != null ? [1] : []
    content {
      enabled        = true
      attribute_name = var.ttl_attribute_name
    }
  }

  dynamic "replica" {
    for_each = { for r, replica in var.replica_regions : r => {
      kms_key_arn  = replica.kms_key_arn
      region       = replica.region
      pitr_enabled = replica.pitr_enabled
    } }
    content {
      kms_key_arn            = replica.value.kms_key_arn
      region_name            = replica.value.region
      point_in_time_recovery = replica.value.pitr_enabled
      propagate_tags         = true
    }
  }

  dynamic "global_secondary_index" {
    for_each = var.global_secondary_indexes
    content {
      name               = global_secondary_index.key
      hash_key           = global_secondary_index.value.hash_key
      range_key          = global_secondary_index.value.range_key
      projection_type    = global_secondary_index.value.projection_type
      read_capacity      = global_secondary_index.value.capacity.read
      write_capacity     = global_secondary_index.value.capacity.write
      non_key_attributes = global_secondary_index.value.non_key_attributes
    }
  }

  dynamic "local_secondary_index" {
    for_each = var.local_secondary_indexes
    content {
      name               = local_secondary_index.key
      range_key          = local_secondary_index.value.range_key
      projection_type    = local_secondary_index.value.projection_type
      non_key_attributes = local_secondary_index.value.non_key_attributes
    }
  }

  tags = merge(
    var.tags,
    {
      Name = "${var.env}-${var.identifier}"
    }
  )

  lifecycle {
    ignore_changes = [
      read_capacity,
      write_capacity,
      global_secondary_index
    ]
  }
}
```

### Steps to Reproduce

Due to the issue discussed [here](https://github.com/hashicorp/terraform-provider-aws/issues/25331), you have to use the above configuration in combination with autoscaling rules on the table but exclude the replica block temporarily. Deploy the table and then deploy again but this time with the replica block. 

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @tb00-cloud 👋 Thank you for taking the time to raise this! I can definitely see where you're coming from, however, since those additional resources are created outside of Terraform's control, it's not currently possible to automatically assume control over them. That said, you can use [`import` blocks](https://developer.hashicorp.com/terraform/language/import) to import those resources after the fact to bring them under Terraform's control (and even generate the configuration for the most part, in more recent versions of Terraform).

Since this isn't something that can currently be solved by changes to the AWS Provider, we'll close this issue. If you run into any issues in the future, please do let us know!
