### ISSUE TITLE
[Enhancement]: Adding recently added Interactive Endpoint on AWS EMR Serverless Application

### ISSUE THREAD

**Issue by haraldmeister** [hashicorp/terraform-provider-aws#34377]
### Description

AWS enabled **interactive analytics** on EMR Serverless applications, using the **Interactive Endpoint**. It would be nice to integrate the new feature in the resource **aws_emrserverless_application** in the new provider version, by providing a **true/false** parameter called **interactive_endpoint** (defaulted to false).

This is the configuration on the AWS console:

![interactive_endpoint_emr](https://github.com/hashicorp/terraform-provider-aws/assets/26322042/f60a09ab-21a3-479d-91dc-c0f0a0a4652e)

### Affected Resource(s) and/or Data Source(s)

* aws_emrserverless_application

### Potential Terraform Configuration

```terraform
resource "aws_emrserverless_application" "example" {
  name          = "example"
  release_label = "emr-6.6.0"
  type          = "hive"
  
  interactive_endpoint = true
}
```

### References

[https://aws.amazon.com/about-aws/whats-new/2023/10/amazon-emr-studio-interactive-analytics-amazon-emr-serverless/](https://aws.amazon.com/about-aws/whats-new/2023/10/amazon-emr-studio-interactive-analytics-amazon-emr-serverless/) 

### Would you like to implement a fix?

No

**Comment by jpulgar4** [comment]
Sorry about the useless comment, but any updates on this?

**Comment by tokoko** [comment]
If I didn't miss anything, looks like this is currently impossible to add in terraform. EMR (for whatever reason) never added an option to enable interactive endpoint in emr-serverless rest api (`emr-serverless.<region>.amazonaws.com`). It has only been added to emr-studio api (`emrstudioserver-prod.<region>.amazonaws.com`) which is apparently also a thing that exists.

**Comment by tokoko** [comment]
Interactive configuration has been added both to emr-serverless rest api and the [latest](https://github.com/aws/aws-sdk-go-v2/blob/main/service/emrserverless/CHANGELOG.md#v1200-2024-05-23) go sdk.
