### ISSUE TITLE
[Docs]: incorrect description of the `ssl_support_method` argument

### ISSUE THREAD

**Issue by nikpivkin** [hashicorp/terraform-provider-aws#34388]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#ssl_support_method

### Description

The description of the `ssl_support_method ` argument of the `cloudfront_distribution` resource says that the allowed values are `vip` and `sni-only `. But `static-ip` is also a valid value.

### References

https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_ViewerCertificate.html
https://github.com/hashicorp/terraform-provider-aws/blob/7d8b32f0fd4712c2f3a09b362b9531de08e28faa/internal/service/cloudfront/distribution.go#L714
https://github.com/aws/aws-sdk-go/blob/main/service/cloudfront/api.go#L35866

### Would you like to implement a fix?

No

**Comment by jackedgar24** [comment]
I'm working on a fix for this doc update.
