### ISSUE TITLE
[Enhancement]: Support for Netapp StorageGrid 11.7 S3 ServerSideEncryptionConfigurationNotFoundError message

### ISSUE THREAD

**Issue by fredrikwarfvinge** [hashicorp/terraform-provider-aws#34389]
### Description

Using Netapp StorageGrid's implementation of the S3 system, the error from ServerSideEncryptionConfigurationNotFoundError is slightly different from what is expected in the current implementation of the code.

Currently, the error checks for a specific line of words: "encryption configuration was not found"
On this line: https://github.com/hashicorp/terraform-provider-aws/blob/7d8b32f0fd4712c2f3a09b362b9531de08e28faa/internal/service/s3/bucket.go#L1109

The response from Netapp Storagegrid is: "The server-side encryption request configuration was not found."

So essentially the issue stems from the error only checking for a specific human readable output. A simple fix would probably be to accomodate any error that contains "configuration was not found", but basing the error on human readable output isn't the best in my opinion.

### Affected Resource(s) and/or Data Source(s)

aws_s3_bucket

### Would you like to implement a fix?

No

**Comment by MB175** [comment]
im facing the same issue
