### ISSUE TITLE
[Enhancement]: Add `client_token` argument to `aws_ecs_task_execution`

### ISSUE THREAD

**Issue by jar-b** [hashicorp/terraform-provider-aws#34394]
### Description

The ECS `RunTask` API recently added a `ClientToken` parameter to support idempotent run task requests. Add a corresponding optional argument to the `aws_ecs_task_execution` data source.

### Affected Resource(s) and/or Data Source(s)

- `aws_ecs_task_execution`

### Potential Terraform Configuration

```terraform
data "aws_ecs_task_execution" "example" {
  cluster         = aws_ecs_cluster.example.id
  task_definition = aws_ecs_task_definition.example.arn
  desired_count   = 1
  launch_type     = "FARGATE"
  client_token    = "token-value"
}
```

### References

- https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html
- Depends on #34386

### Would you like to implement a fix?

None

**Comment by jtyrus** [comment]
I can take a look, did a similar change last week (unfortunately on a resource)
