### ISSUE TITLE
[Bug]: ValidationException on creating aws_cur_report_definition

### ISSUE THREAD

**Issue by sdlarsen** [hashicorp/terraform-provider-aws#34391]
### Terraform Core Version

1.5.6

### AWS Provider Version

5.25.0

### Affected Resource(s)

Trying to create a cur report definition (even using the example one from https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cur_report_definition) errors out with

```
╷
│ Error: creating Cost And Usage Report Definition (example-cur-report-definition): ValidationException:
│
│   with module.cluster.module.datadog.aws_cur_report_definition.example_cur_report_definition,
│   on ../../../providers/aws/datadog/main.tf line 117, in resource "aws_cur_report_definition" "example_cur_report_definition":
│  117: resource "aws_cur_report_definition" "example_cur_report_definition" {
│
╵
```

Running with TF_LOG=DEBUG only shows that this is an Exception with no description.

### Expected Behavior

I would have expected the report definition to be created, at least the example one.

### Actual Behavior

I get a ValidationException with no information

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: creating Cost And Usage Report Definition (example-cur-report-definition): ValidationException:
│
│   with module.cluster.module.datadog.aws_cur_report_definition.example_cur_report_definition,
│   on ../../../providers/aws/datadog/main.tf line 117, in resource "aws_cur_report_definition" "example_cur_report_definition":
│  117: resource "aws_cur_report_definition" "example_cur_report_definition" {
│
╵
```

### Terraform Configuration Files

```
resource "aws_cur_report_definition" "example_cur_report_definition" {
  report_name                = "example-cur-report-definition"
  time_unit                  = "HOURLY"
  format                     = "textORcsv"
  compression                = "GZIP"
  additional_schema_elements = ["RESOURCES", "SPLIT_COST_ALLOCATION_DATA"]
  s3_bucket                  = "example-bucket-name"
  s3_region                  = "us-east-1"
  additional_artifacts       = ["REDSHIFT", "QUICKSIGHT"]
}
```

### Steps to Reproduce

terraform apply

### Debug Output

-----------------------------------------------------
2023-11-14T13:45:55.059+0100 [DEBUG] [aws-sdk-go] DEBUG: Response s3/PutObject Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Connection: close
Content-Length: 0
Date: Tue, 14 Nov 2023 12:45:54 GMT
Etag: "92adfd8edceb90ff4d2a41534c87021f"
Server: AmazonS3
X-Amz-Id-2: I8j2pz5A5YQfpFO51V6BVATTPEAF0QM2ZetEAfFmqlZKr10MCz0pzIxuknPqCKPLzJ8GP4JMqRk=
X-Amz-Request-Id: 6NWTSAXV8MA870G5
X-Amz-Server-Side-Encryption: AES256

-----------------------------------------------------
2023-11-14T13:45:55.060+0100 [DEBUG] [aws-sdk-go]
╷
│ Error: creating Cost And Usage Report Definition (example-cur-report-definition): ValidationException:
│
│   with module.cluster.module.datadog.aws_cur_report_definition.example_cur_report_definition,
│   on ../../../providers/aws/datadog/main.tf line 117, in resource "aws_cur_report_definition" "example_cur_report_definition":
│  117: resource "aws_cur_report_definition" "example_cur_report_definition" {
│
╵
2023-11-14T13:45:55.113+0100 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-11-14T13:45:55.136+0100 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/aws/5.25.0/linux_amd64/terraform-provider-aws_v5.25.0_x5 pid=21007
2023-11-14T13:45:55.136+0100 [DEBUG] provider: plugin exited

### Would you like to implement a fix?

None

**Comment by sdlarsen** [comment]
Likely duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/13702

**Comment by sdlarsen** [comment]
Reopening this one. Don't understand why this wouldn't work in a cluster 100% based in us-east-1. Any suggestions appreciated!

**Comment by wilkojd** [comment]
I've had similar issues but the cost report creates successfully on 2nd run. I've yet to confirm this, but I suspect I'm hitting a race condition where Terraform is applying the policy to the new S3 bucket for the report whilst Cost Usage is trying to validate it can write to the bucket.
