### ISSUE TITLE
AWS Provider 'retry_mode' and 'max_retries' configuration issues

### ISSUE THREAD

**Issue by sfxandy** [hashicorp/terraform-provider-aws#34409]
### Description

An issue is being encountered whereby during runs of a CD pipeline to perform EKS node group updates using a new custom AMI, the following error is regularly encountered:

![Google Chrome-2023-11-15 at 08 11 00](https://github.com/hashicorp/terraform-provider-aws/assets/137955820/4be28102-6a45-42d1-9d8f-321e684a4c69)

The Terraform AWS provider configuration has relevant settings to attempt to mitigate this, but seemingly not resolving the issue. The provider configuration is:

```
provider "aws" {

  retry_mode  = "standard"
  max_retries = "10"

}
```

The number for `max_retries` has been upped from 5 to 10 recently but the issue still remains.  I understand there is also an `adaptive` setting for the `retry_mode` parameter.  Is this retry mode fully supported by the Terraform provider? Quoting [official AWS documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-retries.html) (admittedly which is relevant to the AWS CLI)

>  adaptive mode also introduces client-side rate limiting through the use of a token bucket and rate-limit variables that are dynamically updated with each retry attempt. This mode offers flexibility in client-side retries that adapts to the error/exception state response from an AWS service.

From what I understand the AWS Go SDK v2 implements both standard and adaptive retries, however the `InvalidRequestException` returned in the attached screenshot doesn't appear to be one of the "retryable" errors?  Is this an issue with how the Terraform AWS provider handles these exceptions?  

### Would you like to implement a fix?

None

**Comment by sfxandy** [comment]
I have received a response from an issue I raised on the AWS Go SDK GitHub...

https://github.com/aws/aws-sdk-go-v2/issues/2368#issuecomment-1813074501

Is this something that a change in the AWS provider codebase can mitigate?

**Comment by bryantbiggs** [comment]
potentially this is resolved now https://github.com/aws/aws-sdk/issues/652#issuecomment-2221098984

@sfxandy can you confirm?
