### ISSUE TITLE
[Docs]: aws_rds_cluster Aurora Multi-Master Cluster link has been changed

### ISSUE THREAD

**Issue by a-nldisr** [hashicorp/terraform-provider-aws#34414]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#aurora-multi-master-cluster

### Description

Link: 
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-multi-master.html
Now goes to:
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Replication.html

I have no idea if this is the same functionality, was looking into this feature for RDS engine-type instances. But could be possible that the Aurora Multi-Master pages have been MySQL-related all along. 

### References

unknown

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @a-nldisr 👋 Thank you for taking the time to raise this! It looks like we'll need to remove reference to `multimaster` from the documentation altogether, as it's no longer available according to the annotations in [this AWS document](https://aws.amazon.com/about-aws/whats-new/2019/08/amazon-aurora-multimaster-now-generally-available/).
