### ISSUE TITLE
[Bug]: New, undocumented response from the Managed Grafana API

### ISSUE THREAD

**Issue by zhimsel** [hashicorp/terraform-provider-aws#34417]
### Terraform Core Version

1.5.5,1.5.7

### AWS Provider Version

5.23.1

### Affected Resource(s)

* [`aws_grafana_workspace`](https://registry.terraform.io/providers/hashicorp/aws/5.23.1/docs/resources/grafana_workspace#configuration)

### Expected Behavior

No drift when no changes have been made

### Actual Behavior

Persistent drift for the `configuration` argument. The [`DescribeWorkspaceConfiguration` API action](https://docs.aws.amazon.com/grafana/latest/APIReference/API_DescribeWorkspaceConfiguration.html) now responds with additional JSON fields:

```diff
 {
+  "plugins": {
+    "pluginAdminEnabled": false
+  }
   "unifiedAlerting": {
     "enabled": true|false
   }
 }
```

It appears that the new field is always `false` and there is no corresponding setting in the console for this new option.

Also, _applying_ the drift (i.e. calling [`UpdateWorkspaceConfiguration`](https://docs.aws.amazon.com/grafana/latest/APIReference/API_UpdateWorkspaceConfiguration.html) with thew new field) "updates" the workspace, but does not actually change anything; the drift continues to appear in subsequent plans.

### Terraform Configuration Files

n/a

### Steps to Reproduce

nothing, just plan your `aws_grafana_workspace` after today

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
I can reproduce in acceptance tests:

```console
% make testacc TESTARGS='-run=TestAccGrafana_serial/Workspace/configuration' PKG=grafana
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/grafana/... -v -count 1 -parallel 20  -run=TestAccGrafana_serial/Workspace/configuration -timeout 360m
=== RUN   TestAccGrafana_serial
=== PAUSE TestAccGrafana_serial
=== CONT  TestAccGrafana_serial
=== RUN   TestAccGrafana_serial/Workspace
=== RUN   TestAccGrafana_serial/Workspace/configuration
    workspace_test.go:446: Step 1/3 error: Check failed: 1 error occurred:
        	* Check 2/2 error: aws_grafana_workspace.test: Attribute 'configuration' expected "{\"unifiedAlerting\":{\"enabled\":true}}", got "{\"unifiedAlerting\":{\"enabled\":true},\"plugins\":{\"pluginAdminEnabled\":false}}"
        
--- FAIL: TestAccGrafana_serial (310.45s)
    --- FAIL: TestAccGrafana_serial/Workspace (310.45s)
        --- FAIL: TestAccGrafana_serial/Workspace/configuration (310.45s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/grafana	315.995s
FAIL
make: *** [testacc] Error 1
```

**Comment by ewbankkit** [comment]
Grafana community plugins [announcement](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-managed-grafana-community-plugins/).

**Comment by ewbankkit** [comment]
I have verified that after the GA of the plugins functionality you can add JSON like

```json
"plugins": {"pluginAdminEnabled": false}}
```

to `configuration` to suppress the diff.
