### ISSUE TITLE
[Docs]: Misleading attribute documentation on cloudfront_origin_access_identity datasource

### ISSUE THREAD

**Issue by benja-M-1** [hashicorp/terraform-provider-aws#34416]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/cloudfront_origin_access_identity

### Description

Hello, on the https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/cloudfront_origin_access_identity, the description of the `id` attribute specifies `The identifier for the distribution` with an example.
This misled me: I put the id of the cloudfront distribution but it didn't exist. I replaced it with the id of the distribution origin and then it worked.

I suggest something like `The identifier for the origin of the distribution` instead.

### Would you like to implement a fix?

None

**Comment by jtyrus** [comment]
I can update this doc

**Comment by rama280290** [comment]
Can i work on this?
