### ISSUE TITLE
[Enhancement]: Add scope to aws_resourceexplorer2_view for multi-account search

### ISSUE THREAD

**Issue by dandelo** [hashicorp/terraform-provider-aws#34411]
### Description

Yesterday AWS released organisation level views for resource explorer.

Can we have a `scope` argument added to `aws_resourceexplorer2_view ` so we can configure multi-account search?

### Affected Resource(s) and/or Data Source(s)

`aws_resourceexplorer2_view`

### Potential Terraform Configuration

```terraform
resource "aws_resourceexplorer2_view" "org" {
  name = "org"

  included_property {
    name = "tags"
  }

  scope = "o-abc123abcd"
}
```

### References

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2023/11/aws-resource-explorer-multi-account-resource-search/)
* [Blog post](https://aws.amazon.com/blogs/aws/new-multi-account-search-in-aws-resource-explorer/)

Relates https://github.com/hashicorp/terraform-provider-aws/issues/27717.
Requires [AWS SDK for Go v1.47.11](https://github.com/aws/aws-sdk-go/releases/tag/v1.47.11): https://github.com/hashicorp/terraform-provider-aws/pull/34406.

### Would you like to implement a fix?

No

**Comment by ei-grad** [comment]
As a workaround, `aws_cloudcontrolapi_resource` could be used to create `AWS::ResourceExplorer2::View` with `scope`, while it is not supported in `aws_resourceexplorer2_view`.
