### ISSUE TITLE
[Docs]: Correcting "JBDC" Typo to "JDBC" in Terraform Documentation

### ISSUE THREAD

**Issue by tksx1227** [hashicorp/terraform-provider-aws#34421]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/5.25.0/docs/resources/glue_connection

### Description

Hello,

I have noticed a small typo in the Terraform documentation. In a few instances, the word "JDBC" has been incorrectly spelled as "JBDC." This typo might lead to confusion for readers trying to implement JDBC-related configurations or tasks.

I believe correcting this typo will enhance the clarity and accuracy of the documentation. I am willing to make these corrections myself and will submit a pull request with the necessary changes.

Thank you for your attention to this matter.

### References

I searched the repository and found about six of the same typos.

https://github.com/hashicorp/terraform-provider-aws/blob/648f3d705be10da8b6df6e286be91bdfe32eccad/website/docs/r/glue_connection.html.markdown?plain=1#L118

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @tksx1227 👋 Thank you for taking the time to raise this, and for being willing to submit a fix! Just a heads up that you don't need to modify the Python or Typescript versions of the documentation (those are generated from the Native/HCL version of the documents), so it looks like you'll only need to fix it in two places 🙂.
