### ISSUE TITLE
AWS Lambda advanced logging controls

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#34455]
> AWS Lambda announces advanced logging controls that enable you to natively capture logs in JSON structured format, adjust log levels, and select the Amazon CloudWatch log group for your Lambda functions.

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2023/11/aws-lambda-controls-search-filter-aggregate-lambda-function-logs/)
* [Blog post](https://aws.amazon.com/blogs/compute/introducing-advanced-logging-controls-for-aws-lambda-functions/)

**Comment by mmi-fbx** [comment]
Hi,
Here is the AWS documentation to complete the first post : 
[AWS DOCS](https://docs.aws.amazon.com/lambda/latest/dg/monitoring-cloudwatchlogs.html)

**Comment by JamesJJ** [comment]
I can have a go at implementing this, unless anyone else is already working on it?
