### ISSUE TITLE
[Bug]: idle_disconnect_timeout_in_seconds parameter in aws_appstream_fleet ressource doesn't support a value greater than 3600

### ISSUE THREAD

**Issue by got2be71** [hashicorp/terraform-provider-aws#34453]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.25.0

### Affected Resource(s)

aws_appstream_fleet

### Expected Behavior

idle_disconnect_timeout_in_seconds parameter set to a value greater than 3600 seconds, for example 7200

### Actual Behavior

idle_disconnect_timeout_in_seconds parameter cannot be set to a value greater than 3600 seconds.

### Relevant Error/Panic Output Snippet

```shell
Error: expected idle_disconnect_timeout_in_seconds to be in the range (60 - 3600), got 7200
```

### Terraform Configuration Files

```hcl
resource "aws_appstream_fleet" "this" {
  [...]
  idle_disconnect_timeout_in_seconds = 7200
  [...]
}
``` 

### Steps to Reproduce

Create an appstream fleet with idle_disconnect_timeout_in_seconds  parameter set to a value greater than 3600.

### Panic Output

Error: expected idle_disconnect_timeout_in_seconds to be in the range (60 - 3600), got 7200

### Important Factoids

idle_disconnect_timeout_in_seconds parameter can be set to a value greater than 3600 through aws cli : 

```shell
aws appstream update-fleet --name xxxxx --idle-disconnect-timeout-in-seconds 7200
``` 

```shell
aws appstream describe-fleets --name xxxxx  --query 'Fleets[*].IdleDisconnectTimeoutInSeconds'
[
    7200
]
``` 

### Would you like to implement a fix?

None

**Comment by jrang188** [comment]
Hey, I am willing to work on this issue.

**Comment by jrang188** [comment]
I see a discrepancy between the maximum time in the AWS console and the AWS API documentation. 
-  In the AWS console, the maximum time is 600 minutes (36000 seconds)
![image](https://github.com/hashicorp/terraform-provider-aws/assets/59113087/8c542192-c870-4cac-99b4-b07e07221fdc)
- The API documentation shows the current 60 to 3600 seconds. 
![image](https://github.com/hashicorp/terraform-provider-aws/assets/59113087/ca2cd9bd-a807-4f2c-a800-81275a8c8f3b)
[IdleDisconnectTimeoutInSeconds](https://docs.aws.amazon.com/appstream2/latest/APIReference/API_CreateFleet.html#AppStream2-CreateFleet-request-IdleDisconnectTimeoutInSeconds)

Can anyone clarify the correct timeout period?

**Comment by got2be71** [comment]
AWS support informed me that the API documentation will be updated to reflect this change.

**Comment by got2be71** [comment]
Any update on this pls ?
