### ISSUE TITLE
[Enhancement]: aws_ecr_pull_through_cache_rule support CredentialArn and UpstreamRegistry

### ISSUE THREAD

**Issue by willhughes-au** [hashicorp/terraform-provider-aws#34466]
### Description

AWS ECR Pull Through Cache Rules now support two additional parameters: upstreamRegistry and credentialArn 

These are required to support pulling from (for example) Docker Hub and other  types of authenticated upstreams.

### Affected Resource(s) and/or Data Source(s)

aws_ecr_pull_through_cache_rule

### Potential Terraform Configuration

```terraform
resource "aws_ecr_pull_through_cache_rule" "docker-hub" {
  ecr_repository_prefix = "docker-hub"
  upstream_registry_url = "registry-1.docker.io"
  credential_arn = "arn:aws:secretsmanager:us-east-2:111122223333:secret:ecr-pullthroughcache/example1234"
}
```

### References

https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_CreatePullThroughCacheRule.html
https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache-creating-rule.html

### Would you like to implement a fix?

No

**Comment by 0xfabio** [comment]
I could try to implement this if someone from the core maintainers could give some support.

**Comment by AdamTylerLynch** [comment]
Related: #34716

**Comment by honarkhah** [comment]
Do I need to update the CDK doc as well, how the CDK will react to this feature?

**Comment by MrHash** [comment]
The ARN validation is faulty, the example given doesn't work due to ARN static validation, and full ARNs with ID suffix return `UnableToAccessSecretException`
