### ISSUE TITLE
[Enhancement]: Java 21 Lambda support

### ISSUE THREAD

**Issue by moritzzimmer** [hashicorp/terraform-provider-aws#34473]
### Description

> AWS Lambda now supports creating serverless applications using Java 21

see https://aws.amazon.com/about-aws/whats-new/2023/11/aws-lambda-support-java-21/

### Affected Resource(s) and/or Data Source(s)

* aws_lambda_function
* aws_lambda_layer_version

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Available in 11/15/2023 SDKs -- https://github.com/aws/aws-sdk-go-v2/releases/tag/service%2Flambda%2Fv1.47.0.
