### ISSUE TITLE
[Docs]: typo in property name for aws_quicksight_iam_policy_assignment

### ISSUE THREAD

**Issue by reidg44** [hashicorp/terraform-provider-aws#34485]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/quicksight_iam_policy_assignment#identities

### Description

Property "identities.groups" should be "identities.group", without the "s".

See: https://github.com/hashicorp/terraform-provider-aws/blob/cecd9e05a10e6c3c6e59c4ae984062ddf1969b6b/internal/service/quicksight/iam_policy_assignment.go#L106C7-L106C7

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @reidg44 👋 Thank you for taking the time to raise this! I've opened a PR to update the documentation.
