### ISSUE TITLE
[Bug]: aws_launch_template does not apply security groups updates defined in network_interfaces block

### ISSUE THREAD

**Issue by eduardocque** [hashicorp/terraform-provider-aws#34493]
### Terraform Core Version

1.6.4

### AWS Provider Version

5.26.0

### Affected Resource(s)

aws_launch_template, aws_security_group

### Expected Behavior

if i replace my security group or this one makes a new one, the ec2 instances created by the aws_launch_template should change the security group in the network interface associated

### Actual Behavior

aws_security_group keeps waiting forever trying to get it deleted but due that the ec2 instance created by the `aws_launch_template` still referencing to the previous security group, this is blocking the deletion of the security group and the ec2 server gets broken

### Terraform Configuration Files

```
esource "aws_launch_template" "ecs_launch_config" {
  # Name of the launch template
  name          = "${var.project_name}-autoscale-template"
  image_id      = var.instance_image_id
  instance_type = var.instance_type
  user_data     = base64encode(local.value)

  # SSH key pair name for connecting to the instance
  key_name = var.ssh_key_name

  # block_device_mappings {
  #   device_name = "/dev/sda1"

  #   ebs {
  #     # Size of the EBS volume in GB
  #     volume_size = 20

  #     # Type of EBS volume (General Purpose SSD in this case)
  #     volume_type = "gp2"
  #   }
  # }

  iam_instance_profile {
    name = aws_iam_instance_profile.ecs_instance_profile.name
  }

  network_interfaces {
    # Associates a public IP address with the instance
    associate_public_ip_address = true

    # Security groups to associate with the instance
    security_groups = var.security_group_ids
  }

  tag_specifications {
    # Specifies the resource type as "instance"
    resource_type = "instance"

    # Tags to apply to the instance
    tags = {
      Name = "ECS Instance - ec2-${var.project_name}"
    }
  }

  lifecycle {
    create_before_destroy = true
  }

  depends_on = [aws_ecs_cluster.ecs_cluster]
}
```

```
resource "aws_security_group" "plitzi_sg_public" {
  vpc_id      = aws_vpc.main.id
  name_prefix = "${var.project_name}-sg-public-"
  description = "${var.project_environment} Security Group"
  lifecycle {
    create_before_destroy = true
  }
}
```

### Steps to Reproduce

* make an aws_launch_template with his security group associated (be sure to have at least 1 ec2 server online)
* try to update the security group for example updating the description that will force a recreation
* should change to the new SG but keeps stuck

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @eduardocque  👋 Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. To maintain that, we ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). With that in mind, I'm going to close this issue, but I do have a couple of suggestions that might help.

Launch templates [are immutable](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/manage-launch-template-versions.html), so when you update one via Terraform, you're creating a new version. I can't see how your EC2 instances are created with the sample configuration that you provided, but it may be that you're pointing at a specific launch template version. You may also need to consider an autoscaling group and [instance refresh](https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-instance-refresh.html).
