### ISSUE TITLE
[Bug]: `aws_ssm_document` constructs document ARN regardless of type

### ISSUE THREAD

**Issue by jar-b** [hashicorp/terraform-provider-aws#34506]
### Terraform Core Version

1.6.4

### AWS Provider Version

5.26.0

### Affected Resource(s)

- `aws_ssm_document`

### Expected Behavior

I'm not positive in this case. 

The SSM Document APIs do not return an ARN value in the response, so as a convenience the AWS provider constructs the expected value following the document ARN format:

`arn:${Partition}:ssm:${Region}:${Account}:document/${DocumentName}`

This assumption can cause issues under certain conditions. For example, if a document with `type = "Automation"` is used as an input to a resource such as `aws_cloudwatch_event_target`, the expected `arn` value should actually be the `automation-definition` format:

`arn:${Partition}:ssm:${Region}:${Account}:automation-definition/${AutomationDefinitionName}:${VersionId}`

Using a document ARN results in unexpected validation errors, as certain arguments such as the `run_command_targets` block become required for SSM document ARN's. Since AWS does not explicitly return ARN values, it isn't obvious how each document type should compose the ARN. We could either:

1. Do nothing, and document the assumption the `arn` attribute makes.
2. Dynamically construct the ARN based on the document `type`. This would be a breaking change, and we would need high confidence in how the various type options map to available ARN formats.

### Actual Behavior

A document ARN is always returned.

### Relevant Error/Panic Output Snippet

```shell
│ Error: creating EventBridge Target (asg-failure-checker-FHFailedASGDeletion): ValidationException: Parameter RunCommandParameters is not valid for target FHFailedASGDeletion.
│       status code: 400, request id: b4ad2fbc-aa71-4396-b608-bf73cabddcc5
```

### Terraform Configuration Files

```terraform
resource "aws_ssm_document" "example" {
  name            = "example"
  document_type   = "Automation"
  document_format = "YAML"
  content         = <omitted for brevity>
}

resource "aws_cloudwatch_event_target" "example" {
  rule      = aws_cloudwatch_event_rule.example.name
  target_id = "example"

  # aws_ssm_document resource always returns a document ARN. In this
  # case, an automation-definition ARN is expected so it must be manually
  # constructed instead.
  #
  #arn       = aws_ssm_document.example.arn
  arn       = "arn:aws:ssm:us-west-2:012345678901:automation-definition/example"
  role_arn  = aws_iam_role.example.arn

  input_transformer {
    input_paths = {
      "DeploymentID" = "$.detail.deploymentId"
    }
    input_template = "{\"DeploymentID\":[<DeploymentID>]}"
  }
}
```

Additional configuration required to reproduce but not directly relevant to the bug report.

```terraform
resource "aws_cloudwatch_event_rule" "example" {
  name        = "example"
  description = "example"

  event_pattern = jsonencode({
    source = ["aws.codedeploy"],
    detail-type = [
      "CodeDeploy Deployment State-change Notification"
    ],
    detail = {
      "state" : ["FAILURE"]
    }
  })
}

data "aws_iam_policy_document" "example" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["events.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "example" {
  name               = "example"
  assume_role_policy = data.aws_iam_policy_document.example.json
}
```

### Steps to Reproduce

1. Use the configuration above and uncomment the `arn = aws_ssm_document.example.arn` line.
2. Observe validation error.
3. Use manually constructed automation-definition ARN and observe success.

### References

- https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssystemsmanager.html#awssystemsmanager-resources-for-iam-policies
- https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateDocument.html

### Would you like to implement a fix?

None

**Comment by eugercek** [comment]
May I pick this up?
