### ISSUE TITLE
[New Resource]: ECR Repository Creation Template

### ISSUE THREAD

**Issue by davidnortonjr** [hashicorp/terraform-provider-aws#34503]
### Description

When the API is available, please support the [new configuration for repositories that are auto-created via pull-through cache rules](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-ecr-initial-configuration-repositories-pull-through-cache-preview/).

### Requested Resource(s) and/or Data Source(s)

* aws_ecr_repository_creation_template

### Potential Terraform Configuration

```terraform
resource "aws_ecr_repository_creation_template" "template" {
  prefix = "quay"
  description = "default settings for quay.io"
  image_tag_mutability = "IMMUTABLE"
  encryption_configuration = {
    encryption_type = "KMS"
    kms_key = "(arn)"
  }
  policy = "(json)"
  lifecycle_policy = "(json)"
  tags = {
    Foo = "bar"
  }
}
```

### References

- [Announcement on AWS blog](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-ecr-initial-configuration-repositories-pull-through-cache-preview)
- [Manage your repository creation templates](https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-creation-templates.html) on ECR docs

### Would you like to implement a fix?

None

**Comment by weijiany** [comment]
Do we have some updates about this feature? Or we will wait until the AWS  ECR Repository Creation Template become stable. 🤔

**Comment by shrutichaudhary17** [comment]
Are there any update on this feature?

**Comment by mohamed-haidara-cko** [comment]
The API cannot be used at the moment to create the templates since the feature is still in preview: https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-creation-templates.html?icmpid=docs_ecr_hp-registry-private

![Screenshot 2024-04-17 at 13 14 26](https://github.com/hashicorp/terraform-provider-aws/assets/95634348/c7349294-8009-4455-a0ac-6ddb600f1915)

**Comment by sasidhar-aws** [comment]
I will be working on this issue.

**Comment by iarc13** [comment]
Thanks @sasidhar-aws ! Please keep us updated!

**Comment by shrutichaudhary17** [comment]
Hi @sasidhar-aws , any tentative timeline when the feature would become stable ? We are waiting for repository creation template feature do a production roll-out for ECR pull cache.

**Comment by weijiany** [comment]
Yesterday AWS announced [this feature is GA](https://aws.amazon.com/about-aws/whats-new/2024/07/amazon-ecr-repository-creation-templates-generally-available/). Exciting 🎉 🎉 🎉

**Comment by bodgit** [comment]
I've created a PR #38597 that implements this new resource. Please try it out.
