### ISSUE TITLE
[New Resource]: Amazon CloudFront KeyValueStore

### ISSUE THREAD

**Issue by kohbis** [hashicorp/terraform-provider-aws#34512]
### Description

> Amazon CloudFront announces general availability of CloudFront KeyValueStore, a global, low-latency, key value datastore.

* [Announcement](https://aws.amazon.com/blogs/aws/introducing-amazon-cloudfront-keyvaluestore-a-low-latency-datastore-for-cloudfront-functions/)
* [Blog post](https://aws.amazon.com/blogs/aws/introducing-amazon-cloudfront-keyvaluestore-a-low-latency-datastore-for-cloudfront-functions/)

This is the resource creation issue that corresponds to this.

#### Resource(s)

* aws_cloudfront_keyvaluestore

### References

- Added to Go SDK v1.48.2
  - https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.48.2/service/cloudfront
  - https://github.com/aws/aws-sdk-go/releases/tag/v1.48.2

Requires https://github.com/hashicorp/terraform-provider-aws/pull/34514.

### Would you like to implement a fix?

None

**Comment by cbosss** [comment]
👋  - I'm working on this issue. Should have a PR up in the next couple days.

**Comment by jdavidbakr** [comment]
Any chance this PR can get looked at?  Would really like to start using CloudFront Key Value Stores.
