### ISSUE TITLE
[Enhancement]: Transit Gateway Security Group Referencing Support

### ISSUE THREAD

**Issue by phergoualch** [hashicorp/terraform-provider-aws#34541]
### Description

AWS released a much anticipated feature to reference security groups across VPCs attached to a Transit Gateway. They added it to the Transit Gateway documentation and then rolled it back, so I'm not sure if this was a mistake and they are waiting for re:invent (no blog post has been published yet).
Anyway, the feature is available in the GO SDK from version [v1.48.1](https://github.com/aws/aws-sdk-go/releases/tag/v1.48.1): https://github.com/hashicorp/terraform-provider-aws/pull/34492.

### Affected Resource(s) and/or Data Source(s)

* aws_ec2_transit_gateway
* data_aws_ec2_transit_gateway
* aws_ec2_transit_gateway_vpc_attachment
* data_aws_ec2_transit_gateway_vpc_attachment

### Potential Terraform Configuration

```terraform
resource "aws_ec2_transit_gateway" "example" {
  description                        = "example"
  security_group_referencing_support = "enable"
}
```

### References

[https://github.com/aws/aws-sdk-go/releases/tag/v1.48.1](https://github.com/aws/aws-sdk-go/releases/tag/v1.48.1)

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/09/general-availability-security-group-referencing-aws-transit-gateway/)
* [Blog post](https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-security-group-referencing-for-aws-transit-gateway/)

### Would you like to implement a fix?

Yes

**Comment by phergoualch** [comment]
The feature is now GA ! 🎉

https://aws.amazon.com/about-aws/whats-new/2024/09/general-availability-security-group-referencing-aws-transit-gateway/

**Comment by amolkksagar** [comment]
Hi,

https://github.com/hashicorp/terraform-provider-aws/blob/v5.69.0/CHANGELOG.md still shows this version as unreleased. When will it be released?
