### ISSUE TITLE
[New]: S3 server access logging now supports automatic date-based partitioning

### ISSUE THREAD

**Issue by whoamiTodo** [hashicorp/terraform-provider-aws#34555]
### Description

Amazon S3 server access logging now supports automatic date-based partitioning for log delivery. Amazon S3 server access logging provides detailed records for requests made to your S3 buckets including object size, total time, turn-around time, HTTP referer, and more. Now, with date-based partitioning, Amazon S3 automatically generates either event time or delivery time prefixes when delivering access logs to your destination bucket, which allows services like Amazon Athena, Amazon EMR, and Amazon Redshift Spectrum to improve performance and reduce cost when querying logs.

### Requested Resource(s) and/or Data Source(s)

- aws_s3_bucket_logging

### Potential Terraform Configuration

```terraform
resource "aws_s3_bucket_logging" "example" {
  bucket = aws_s3_bucket.example.id

  target_bucket = aws_s3_bucket.log_bucket.id
  target_prefix = "log/"
  partitioning  = true
}
```

### References

https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerLogs.html

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@ewbankkit Thanks for raising this issue.
It has already been noticed in #34518. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by whoamiTodo** [comment]
@ewbankkit thanks!
