### ISSUE TITLE
[Enhancement]: AWS Lambda support for Java 21

### ISSUE THREAD

**Issue by CasaSky** [hashicorp/terraform-provider-aws#34552]
### Description

    You can now develop AWS Lambda functions using Java 21

### Affected Resource(s) and/or Data Source(s)

    [aws_lambda_function](https://www.terraform.io/docs/providers/aws/r/lambda_function.html)
    [aws_lambda_layer_version](https://www.terraform.io/docs/providers/aws/r/lambda_layer_version.html) plus corresponding data source

### Potential Terraform Configuration

```
resource "aws_lambda_function" "example" {
  runtime = "java21"
}
```

### References

Announcements:

    [Java 21](https://aws.amazon.com/about-aws/whats-new/2023/11/aws-lambda-support-java-21/)

**Comment by ewbankkit** [comment]
Closes via https://github.com/hashicorp/terraform-provider-aws/pull/34476.
This functionality will be available in Terraform AWS Provider **v5.27.0**, likely 11/27.
