### ISSUE TITLE
[New Resource]: aws_controltower_landing_zone 

### ISSUE THREAD

**Issue by bschaatsbergen** [hashicorp/terraform-provider-aws#34557]
### Description

AWS Control Tower just announced API availability to manage Landing Zones: https://aws.amazon.com/about-aws/whats-new/2023/11/automate-aws-control-tower-zone-operations-apis/

### Requested Resource(s) and/or Data Source(s)

aws_controltower_landing_zone

### Potential Terraform Configuration

```terraform
resource "aws_controltower_landing_zone" "example" {
  manifest = jsonencode(yamldecode(file("manifest.yaml")))
  version = "v1"
  tags = {
    Foo = "Bar"
  }
}
```

### References

https://docs.aws.amazon.com/controltower/latest/APIReference/API_Operations.html

### Would you like to implement a fix?

Yes, I'll pick this up 🚀

**Comment by bschaatsbergen** [comment]
Picking this up 🚀

**Comment by bschaatsbergen** [comment]
This needs: https://github.com/hashicorp/terraform-provider-aws/pull/34586

**Comment by bschaatsbergen** [comment]
Heya @photosojourn I aim to write the tests today/tomorrow. And informed the core team that I'm almost done implementing the resource.

**Comment by photosojourn** [comment]
Oooh excellent news and thanks!

**Comment by bschaatsbergen** [comment]
Hey @elad-ts - thanks for checking up. We had some internal discussions around the resource specification and I believe that @ewbankkit is rounding up the PR.

**Comment by bschaatsbergen** [comment]
https://github.com/hashicorp/terraform-provider-aws/pull/34595#issuecomment-1913700259

**Comment by bschaatsbergen** [comment]
Update: We made all the changes after our internal discussions, and we plan to merge the pull request once all the checks are complete and successful. 👍🏼
