### ISSUE TITLE
[New]: EKS Pod Identity

### ISSUE THREAD

**Issue by kimxogus** [hashicorp/terraform-provider-aws#34561]
### Description

AWS Announced new EKS Pod Identity feature, and AWS SDK Go v2 has been released including this feature.

### Requested Resource(s) and/or Data Source(s)

- `aws_eks_pod_identity_association`

```terraform
resource "aws_eks_pod_identity_association" "foo" {
  cluster_name = "my_cluster"
  namespace = "my_namespace"
  service_account_name = "foo-sa"
  iam_role_arn = "aws:......:foo"
}
```

### References

https://aws.amazon.com/ko/about-aws/whats-new/2023/11/amazon-eks-pod-identity/
https://aws.amazon.com/ko/blogs/aws/amazon-eks-pod-identity-simplifies-iam-permissions-for-applications-on-amazon-eks-clusters/
https://github.com/aws/aws-sdk-go-v2/blob/main/service/eks/CHANGELOG.md#v1340-2023-11-27
https://github.com/aws/aws-sdk-go-v2/blob/main/service/eksauth/CHANGELOG.md#v100-2023-11-27

### Would you like to implement a fix?

No

**Comment by bryantbiggs** [comment]
I have this already in progress
