### ISSUE TITLE
[New]: ALB Mutual Authentication

### ISSUE THREAD

**Issue by dallasanta** [hashicorp/terraform-provider-aws#34568]
### Description

Given that AWS has launched a new functionality to enable Mutual Authentication on ALBs (https://aws.amazon.com/blogs/aws/mutual-authentication-for-application-load-balancer-to-reliably-verify-certificate-based-client-identities/)

And aws-sdk-go already supports that
And CloudFormation has already implemented that through the following resources:
* [New] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-truststore.html
* [New] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-truststorerevocation.html
* [Updated] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listener.html

Then AWS provider should have its own implementation

### Requested Resource(s) and/or Data Source(s)

* aws_lb_trust_store
* aws_lb_trust_store_revocation

### Would you like to implement a fix?

None

**Comment by matt-mercer** [comment]
Hi @dallasanta  I've created a PR for this  with a minimal implementation : https://github.com/hashicorp/terraform-provider-aws/pull/34584

so far just allowing the creation of a trust_store resource/data source and binding to a load balancer, 
there are some challenges around the trust_store as the s3 object information used to create the trust store is not retained in describe-trust-store .. so I'm envisaging there might be a case to manage the trust_store outside of terraform and bind it to an ALB using the data source ..

**Comment by dallasanta** [comment]
thanks @matt-mercer for the implementation! I think it would be helpful to have the s3 config in the state file as I can see it's a valid use case to modify the trust store. I'm afraid I'm not a reviewer on this project so I don't think I can help getting it over the line.

**Comment by matt-mercer** [comment]
@dallasanta totally agree .. I just don't know there's an easy way to achieve this, I've seen some closed issues that look 'similar' to what it would be good to do ...  on the flip side , it's probably OK, if a modify-trust-store action fires on apply that re-deploys the same CA cert .. just noisy / slightly scary when you're not expecting a change.

**Comment by matt-mercer** [comment]
@dallasanta  actually it works fine .. the ca_certificates_bundle_s3_bucket / ca_certificates_bundle_s3_key are automatically saved into state .. so repeat applys don't trigger change .. think you'd just get an initial one post import ..
