### ISSUE TITLE
[Enhancement]: Config recorder - Periodic recording

### ISSUE THREAD

**Issue by matthill33** [hashicorp/terraform-provider-aws#34577]
### Description

AWS Config now supports periodic recording for config recorders as of 11/26/23 ([https://aws.amazon.com/about-aws/whats-new/2023/11/aws-config-periodic-recording/]). This feature is very useful for lowering config costs. 

### Affected Resource(s) and/or Data Source(s)

aws_config_configuration_recorder

### Potential Terraform Configuration

```terraform
resource "aws_config_configuration_recorder" "foo" {
  name     = "example"
  role_arn = aws_iam_role.r.arn
  recording_mode {
    recording_frequency = DAILY
  }

  recording_group {
    all_supported = false

    exclusion_by_resource_types {
      resource_types = ["AWS::EC2::Instance"]
    }

    recording_strategy {
      use_only = "EXCLUSION_BY_RESOURCE_TYPES"
    }
  }
}
```

### References

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/configservice/put-configuration-recorder.html
https://aws.amazon.com/about-aws/whats-new/2023/11/aws-config-periodic-recording/
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_configuration_recorder 

### Would you like to implement a fix?

None

**Comment by chlunde** [comment]
I'm taking a look at this
