### ISSUE TITLE
[Enhancement]: aws_secretsmanager_secret data source doesn't provide CreatedDate

### ISSUE THREAD

**Issue by paul-civitas** [hashicorp/terraform-provider-aws#34602]
### Description

aws secretsmanager describe-secret returns a CreatedDate which is a useful field for various purposes. In addition aws secretsmanager list-secret-version-ids returns a CreatedDate for the secret versions for a secret.

### Affected Resource(s) and/or Data Source(s)

aws_secretsmanager_secret
aws_secretsmanager_secret_version

### Potential Terraform Configuration

```terraform
resource "aws_secretsmanager_secret_version" "argocd_admin_password" {
  secret_id     = aws_secretsmanager_secret.argocd_admin_password.id
  secret_string = random_password.argocd_admin_password.result
}

resource "kubernetes_secret" "argocd_secret" {
  metadata {
    name = "argocd-secret"
    namespace = "argocd"
  }

  data = {
    "admin.password" = random_password.argocd_admin_password.bcrypt_hash
    "admin.passwordMtime" = formatdate("YYYY-MM-DD'T'hh:mm:ssZ", aws_secretsmanager_secret_version.argocd_admin_password.created_date)
    "dex.github.client-id" = data.aws_secretsmanager_secret_version.github_client_id.secret_string
    "dex.github.client-secret" = data.aws_secretsmanager_secret_version.github_client_secret.secret_string
    "server.secretkey" = data.aws_secretsmanager_secret_version.server_secret.secret_string
  }
}
```

### References

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/secretsmanager/client/get_secret_value.html

References a CreatedDate

### Would you like to implement a fix?

None

**Comment by Siddarthyuvaraj** [comment]
I will work on this and submit PR later

**Comment by Siddarthyuvaraj** [comment]
PR has been raised
https://github.com/hashicorp/terraform-provider-aws/pull/35117
