### ISSUE TITLE
[Enhancement]: Cloudfront Key Value Store

### ISSUE THREAD

**Issue by jdavidbakr** [hashicorp/terraform-provider-aws#34601]
### Description

AWS just introduced CloudFront key value store: https://aws.amazon.com/blogs/aws/introducing-amazon-cloudfront-keyvaluestore-a-low-latency-datastore-for-cloudfront-functions/ - This is huge and I didn't see an issue for adding this in the issues.

### Affected Resource(s) and/or Data Source(s)

This would be a new resource

### Potential Terraform Configuration

```terraform
resource aws_cloudfront_key_value_store {
  name = "name",
  description = "description"
}
```

### References

https://aws.amazon.com/blogs/aws/introducing-amazon-cloudfront-keyvaluestore-a-low-latency-datastore-for-cloudfront-functions/

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@jdavidbakr Thanks for raising this issue.
It has already been noticed in #34512. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
