### ISSUE TITLE
[Enhancement]: Ipam add free tier option

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform-provider-aws#34616]
### Description

AWS announced IPAM free tier, need to add the parameter to ipam https://github.com/aws/aws-sdk-go-v2/blob/main/service/ec2/api_op_CreateIpam.go#L69

### Affected Resource(s) and/or Data Source(s)

* aws_vpc_ipam

### Potential Terraform Configuration

```terraform
resource aws_vpc_ipam main {
  tier = "free"
}
```

### Would you like to implement a fix?

None

**Comment by mmourick** [comment]
I'd like to submit a PR for this!
