### ISSUE TITLE
[Docs]: aws_codebuild_webhook support for tag/release with Github

### ISSUE THREAD

**Issue by 0ssigeno** [hashicorp/terraform-provider-aws#34627]
### Description

From aws documentation, it should be possible to trigger a CodeBuild pipeline when a new tag is created in the Github repository connected to the CodeBuild resource.
```
CODEBUILD_WEBHOOK_TRIGGER
Shows the webhook event that triggered the build. This variable is available only for builds triggered by a webhook. The value is parsed from the payload sent to CodeBuild by GitHub, GitHub Enterprise Server, or Bitbucket. The value's format depends on what type of event triggered the build.

For builds triggered by a pull request, it is pr/pull-request-number.

For builds triggered by creating a new branch or pushing a commit to a branch, it is branch/branch-name.

For builds triggered by a pushing a tag to a repository, it is tag/tag-name.
```

From terraform documentation, from what I read, it should not be possible to configure the `aws_codebuild_webhook` to trigger on a new tag:
```
filter supports the following:

[type](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codebuild_webhook#type) - (Required) The webhook filter group's type. Valid values for this parameter are: EVENT, BASE_REF, HEAD_REF, ACTOR_ACCOUNT_ID, FILE_PATH, COMMIT_MESSAGE. At least one filter group must specify EVENT as its type.
[pattern](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codebuild_webhook#pattern) - (Required) For a filter that uses EVENT type, a comma-separated string that specifies one event: PUSH, PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED, PULL_REQUEST_REOPENED. PULL_REQUEST_MERGED works with GitHub & GitHub Enterprise only. For a filter that uses any of the other filter types, a regular expression.
```

### Affected Resource(s) and/or Data Source(s)

- aws_codebuild
- aws_codebuild_webhook

### Potential Terraform Configuration

```terraform
- aws_codebuild_webhook
   - type -> add the `TAG` to the enum
   - pattern > regular expression (already implemented)
```

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codebuild_webhook#argument-reference

### Would you like to implement a fix?

If requested, sure

**Comment by 0ssigeno** [comment]
From checking the terraform code (that I didn't when opening the issue) I see that is the aws-go sdk that does not support the tag/release type in its own [function](https://github.com/aws/aws-sdk-go/blob/main/service/codebuild/api.go#L17125C32-L17125C32). For this reason, I think that this is a missing feature on the aws side, and not Terraform.

**Comment by justinretzolk** [comment]
Hey @0ssigeno 👋 Thank you for taking the time to raise this and follow up! Once `codebuild.WebhookFilterType_Values()` is updated to return the necessary value, that update to the Go SDK will be pulled in automatically, and this will start to work. With that in mind, I'm going to leave this issue open as a reminder to update the documentation once this occurs.

**Comment by acwwat** [comment]
FYI I checked on the upstream change status and something is off. According to the [CHANGELOG](https://github.com/aws/aws-sdk-go-v2/blob/main/service/codebuild/CHANGELOG.md#v1312-2024-03-20), v1.31.2 was supposed to have support for the new filter types, but the enum still don't have the values.

If I look at the [WebhookFilter](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_WebhookFilter.html) API reference, the _description_ for the `type` field lists `TAG_NAME` and `RELEASE_NAME`, but the _valid values_ list does not. But the [AWS CLI doc](https://docs.aws.amazon.com/cli/latest/reference/codebuild/create-webhook.html) lists the new values since it's matching the API description.

**Comment by acwwat** [comment]
The enum values have been added two days ago to the AWS Go SDK v2 -see [v1.34.0 in the CHANGELOG](https://github.com/aws/aws-sdk-go-v2/blob/2e8999a52f850688e95a1eb247cef1aa46412805/service/codebuild/CHANGELOG.md#v1340-2024-04-09) and the [code blame](https://github.com/aws/aws-sdk-go-v2/blame/2e8999a52f850688e95a1eb247cef1aa46412805/service/codebuild/types/enums.go#L953-L954). And it also looks like this version of the module has been incorporated to the latest version, v5.45.0 of the provider!

@0ssigeno  please upgrade the AWS provider to the latest version, test the `TAG_NAME` webhook filter type with the `aws_codebuild_webhook` resource, and report back on whether it works now.

Meanwhile I will work on a PR to update the documentation.

**Comment by 0ssigeno** [comment]
@acwwat unfortunately I can't test at the moment that the pipeline actually works, but at least  I can confirm that Terraform is now allows to set both `RELEASE_NAME` and `TAG_NAME` and that they are correctly converted in valid `filter_group`

```terraform
  # module.pipeline_tag[0].aws_codebuild_webhook.webhook_tag will be created
  + resource "aws_codebuild_webhook" "webhook_tag" {
      + build_type   = "BUILD"
      + id           = (known after apply)
      + payload_url  = (known after apply)
      + project_name = "intelowl-prod"
      + secret       = (sensitive value)
      + url          = (known after apply)

      + filter_group {
          + filter {
              + exclude_matched_pattern = false
              + pattern                 = "master"
              + type                    = "HEAD_REF"
            }
          + filter {
              + exclude_matched_pattern = false
              + pattern                 = "^([0-9.]+)$"
              + type                    = "RELEASE_NAME"
            }
        }
    }
```
