### ISSUE TITLE
[New]: Request new resource for ElastiCache Serverless

### ISSUE THREAD

**Issue by haraldmeister** [hashicorp/terraform-provider-aws#34629]
### Description

As announced few days ago by AWS here [https://aws.amazon.com/blogs/aws/amazon-elasticache-serverless-for-redis-and-memcached-now-generally-available/](https://aws.amazon.com/blogs/aws/amazon-elasticache-serverless-for-redis-and-memcached-now-generally-available/), there is a new serverless option for Elasticache Redis and Memcached, that allows customers to create a cache in under a minute and instantly scale capacity based on application traffic patterns.

It would be nice to implement the new resource in the followings provider version, as proposed in the followings.

### Requested Resource(s) and/or Data Source(s)

* **aws_elasticache_serverless** (**NEW**)

### Potential Terraform Configuration

```terraform
resource "aws_vpc" "example" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_subnet" "example" {
  vpc_id     = aws_vpc.example.id
  cidr_block = "10.0.1.0/24"

  tags = {
    Name = "my-subnet"
  }
}

resource "aws_elasticache_subnet_group" "example" {
  name       = "my-cache-subnet"
  subnet_ids = [aws_subnet.example.id]

resource "aws_elasticache_user" "default" {
  user_id       = "defaultUserID"
  user_name     = "default"
  access_string = "on ~app::* -@all +@read +@hash +@bitmap +@geo -setbit -bitfield -hset -hsetnx -hmset -hincrby -hincrbyfloat -hdel -bitop -geoadd -georadius -georadiusbymember"
  engine        = "REDIS"
  passwords     = ["password123456789"]
}

resource "aws_elasticache_user_group" "example" {
  engine        = "REDIS"
  user_group_id = "userGroupId"
  user_ids      = [aws_elasticache_user.default.user_id]

  lifecycle {
    ignore_changes = [user_ids]
  }
}


## Redis cluster

resource "aws_elasticache_serverless" "example" {
  cluster_id           = "cluster-example" #mandatory
  engine               = "redis" #mandatory | or "memcached"
  description          = "Description"
  security_group_ids   = ["sg-0exxxxxyyyyzzz"]
  encryption           = "aws/elasticache" # or KMS ARN
  user_group           = aws_elasticache_user_group.example.user_group_id
  subnet_group_name    = aws_elasticache_subnet_group.example.name
  automatic_backup     = false
  usage_limits = {
     memory  =  100 #GB
     compute =  10000 #ECPUs
  }
  tags = {
    Name = "my-serverless-cache"
  }
}
```

### References

* [https://aws.amazon.com/blogs/aws/amazon-elasticache-serverless-for-redis-and-memcached-now-generally-available/](https://aws.amazon.com/blogs/aws/amazon-elasticache-serverless-for-redis-and-memcached-now-generally-available/)
* [https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateServerlessCache.html](https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateServerlessCache.html)

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@haraldmeister Thanks for raising this issue.
It has already been noticed in #34590. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
