### ISSUE TITLE
[Bug]: health_check parameter validation failures when not enabled

### ISSUE THREAD

**Issue by kumarpmd** [hashicorp/terraform-provider-aws#34650]
### Terraform Core Version

0.13.7

### AWS Provider Version

5.28.0

### Affected Resource(s)

aws_lb_target_group

### Expected Behavior

`health_check.path` parameter not validate or validation not fail when `health_check.enabled==false` 
In 5.26.0, validation did not continue of length was 0.  

### Actual Behavior

The latest 5.28.0 (and 5.27.0) aws providers fail 2 validation rules when `health_check.path=""`..  Code and output below.
Expects length(${path}) > 0 and start with "/" prefix.  Breaks the behavior for lambda target_type.  

https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/elbv2/target_group.go#L130-L131 

### Relevant Error/Panic Output Snippet

```shell
 $ terraform plan
Error: expected length of health_check.0.path to be in the range (1 - 1024), got 
  on aw-lb-target-group.tf line 12, in resource "aws_lb_target_group" "lambda":
  12:     path    = ""

Error: "health_check.0.path" must begin with a '/' character, got ""
  on aw-lb-target-group.tf line 12, in resource "aws_lb_target_group" "lambda":
  12:     path    = ""
```

### Terraform Configuration Files

```terraform
provider "aws" {
  version = "5.27.0"
  //  version = "5.26.0"
}

resource "aws_lb_target_group" "lambda" {
  name = "some-test-tg"
  target_type = "lambda"

  health_check {
    enabled = false
    path    = ""
  }
}
```

### Steps to Reproduce

Run `terraform init` and `terraform plan` for the code supplied above..    plan should fail with the error supplied..

### Important Factoids

I believe this behavior started with 5.27.0, where the validation logic was changed and requires a value..
the code snippet provided runs fine in v5.26.0 provider..

### References

https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/elbv2/target_group.go#L130-L131 

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @kumarpmd 👋 Thank you for taking the time to raise this! Unless I'm missing key details, the `path` argument [is optional](https://github.com/hashicorp/terraform-provider-aws/blob/9804b7344a05304723b17ae43643f1fd33c2b09b/internal/service/elbv2/target_group.go#L109) and so can be omitted entirely. In my testing, this fixed the validation errors. Can you verify if that resolves the issue for you as well?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
