### ISSUE TITLE
[New]: Add resources for SecurityHub Central Configuration

### ISSUE THREAD

**Issue by lawliet89** [hashicorp/terraform-provider-aws#34651]
### Description

This is a new feature recently announced: 

- https://aws.amazon.com/blogs/security/introducing-new-central-configuration-capabilities-in-aws-security-hub/
- https://docs.aws.amazon.com/securityhub/latest/userguide/central-configuration-intro.html

`aws_securityhub_organization_configuration` will need new attributes to enable the new mode of configuration: https://docs.aws.amazon.com/securityhub/latest/userguide/start-central-configuration.html

```hcl
resource "aws_securityhub_organization_configuration" "example" {
  auto_enable = false
  
  organization_configuration {
    configuration_type = "CENTRAL"
  }
}
```

New resources will be needed to support 

- Configuration Policies: [GetConfigurationPolicy](https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_GetConfigurationPolicy.html), [ListConfigurationPolicies](https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_ListConfigurationPolicies.html), [UpdateConfigurationPolicy](https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_UpdateConfigurationPolicy.html)
- Policiy Associations: [GetConfigurationPolicyAssociation](https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_GetConfigurationPolicyAssociation.html), [ListConfigurationPolicyAssociations](https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_ListConfigurationPolicyAssociations.html), [StartConfigurationPolicyAssociation](https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_StartConfigurationPolicyAssociation.html), [StartConfigurationPolicyDisassociation](https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_StartConfigurationPolicyDisassociation.html)

### Requested Resource(s) and/or Data Source(s)

- `aws_securityhub_configuration_policy`
- `aws_securityhub_configuration_policy_association`

### References

- https://aws.amazon.com/blogs/security/introducing-new-central-configuration-capabilities-in-aws-security-hub/
- https://docs.aws.amazon.com/securityhub/latest/userguide/central-configuration-intro.html

### Would you like to implement a fix?

None

**Comment by michalz-rely** [comment]
Any news on that? Adding this support will simplify overall security hub deployment in organization.

**Comment by gomezga1** [comment]
Any update on this? supporting this new feature will definitely help us be more granular when deploying different security standards at org level.

**Comment by lawliet89** [comment]
This will also help to reduce RUM in Terraform Cloud when individual controls are being managed across all the accounts via Terraform.

**Comment by twelsh-aw** [comment]
I'm happy to take a stab at implementing this and putting up a PR if no one else has. Probably not able to find enough time until next month though, so if someone can pick up even sooner, would be much appreciated

**Comment by JakubBiel** [comment]
I've started working on `aws_securityhub_configuration_policy`. If I'm not done by next month maybe we can pair @twelsh-aw.

**Comment by hong-yi** [comment]
I've also started working on it @JakubBiel @twelsh-aw , maybe we can pair too?

**Comment by MinhDBui** [comment]
Hello, is there any new update on this issue?

**Comment by JakubBiel** [comment]
I haven't touched it in a while. Thought @twelsh-aw had a good idea how to tackle it, not sure how much he's progressed with it though.

**Comment by twelsh-aw** [comment]
Able to start on this today 🙌 Thanks for the ping

**Comment by twelsh-aw** [comment]
PR is now open for this

It's a doozy 🥴 ... but seems to be working well
