### ISSUE TITLE
[Enhancement]: Add SingleSignOnApplicationArn attribute output to aws_sagemaker_domain when in SSO auth_mode

### ISSUE THREAD

**Issue by deepakbshetty** [hashicorp/terraform-provider-aws#34673]
### Description

Within Sagemaker domain resource, AWS have newly introduced attribute called `SingleSignOnApplicationArn` when resource is created with SSO auth_mode. With the new attribute, this can now be used in conjunction with aws identity centre resource `aws_ssoadmin_application_assignment` [link](https://github.com/hashicorp/terraform-provider-aws/issues/28633) to associate with SSO users and AD groups which was previously not possible [link](https://github.com/hashicorp/terraform-provider-aws/issues/28958)

### Affected Resource(s) and/or Data Source(s)

aws_sagemaker_domain

### Potential Terraform Configuration

```terraform
Expose new attribute reference/output as -
single_sign_on_application_arn - The ARN of the application managed by SageMaker in IAM Identity Center

https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/sagemaker/domain.go#L827
d.Set("single_sign_on_application_arn", domain.SingleSignOnApplicationArn)

https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/sagemaker/domain.go#L728
			"single_sign_on_application_arn": {
				Type:     schema.TypeString,
				Computed: true,
			},
```

### References

AWS CLI Ref: https://docs.aws.amazon.com/cli/latest/reference/sagemaker/describe-domain.html

[SingleSignOnApplicationArn](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_DescribeDomain.html#API_DescribeDomain_ResponseSyntax)
The ARN of the application managed by SageMaker in IAM Identity Center. This value is only returned for domains created after October 1, 2023.
Type: String
Pattern: ^arn:(aws|aws-us-gov|aws-cn|aws-iso|aws-iso-b):sso::[0-9]+:application\/[a-zA-Z0-9-_.]+\/apl-[a-zA-Z0-9]+$

Boto3 reference for usage of `SingleSignOnApplicationArn`:
`applicationArn = sagemaker_client.describe_domain(domainId = "d-xxx")["SingleSignOnApplicationArn"] idc_client.create_application_assignment(applicationArn = applicationArn, principalId="userId/groupId", principalType="USER/GROUP")`

Ref: https://aws.amazon.com/blogs/machine-learning/onboard-users-to-amazon-sagemaker-studio-with-active-directory-group-specific-iam-roles/

### Would you like to implement a fix?

None

**Comment by deepakbshetty** [comment]
Hello @DrFaust92 Wondering if you are interested on this and club with Studio web interface change being worked on

**Comment by DrFaust92** [comment]
Sure, I'll take a look. Thanks for letting me know
