### ISSUE TITLE
[New]: Support for AWS Elasticache Serverless

### ISSUE THREAD

**Issue by mshahmoradi87** [hashicorp/terraform-provider-aws#34685]
### Description

AWS recently announced availability of ElastiCache Serverless for Redis and Memcached.[ Announcement](https://aws.amazon.com/blogs/aws/amazon-elasticache-serverless-for-redis-and-memcached-now-generally-available/)

and looks like it is available in [SDK](https://github.com/aws/aws-sdk-go-v2/blob/service/elasticache/v1.34.1/service/elasticache/api_op_CreateServerlessCache.go)

### Requested Resource(s) and/or Data Source(s)

* aws_elasticache_cluster
  - serverless

### Potential Terraform Configuration

- max_memory
- max_compute

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@mshahmoradi87 Thanks for raising this issue.
It has already been noticed in #34590. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
