### ISSUE TITLE
[Enhancement]: Sagemaker Studio Domain: StudioWebPortal

### ISSUE THREAD

**Issue by jornfranke** [hashicorp/terraform-provider-aws#34689]
### Description

AWS recently released the new AWS Studio Experience with a lot of new functionalities (e.g. cf. [Amazon SageMaker Distribution is now available on Code Editor based on Code-OSS and JupyterLab](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-sagemaker-distribution-code-editor/)  and [New and improved Amazon SageMaker Studio](https://aws.amazon.com/about-aws/whats-new/2023/11/new-improved-amazon-sagemaker-studio/)) and renamed the old one AWS Studio Classic.
One can create/update domains to the new experience by provide in the default user settings block the property StudioWebPortal to Enabled (see also [here](https://docs.aws.amazon.com/sagemaker/latest/dg/studio-updated-migrate.html)).

Hence, it is important that Terraform supports it so that people can migrate to the new experience or create new domains with it.

See also the [AWS CLI documentation related to the propertz StudioWebPortal](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sagemaker/update-domain.html) 

### Affected Resource(s) and/or Data Source(s)

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_domain#default_user_settings

### Potential Terraform Configuration

```terraform
resource "aws_sagemaker_image" "example" {
  image_name = "example"
  role_arn   = aws_iam_role.example.arn
}

resource "aws_sagemaker_app_image_config" "example" {
  app_image_config_name = "example"

  kernel_gateway_image_config {
    kernel_spec {
      name = "example"
    }
  }
}

resource "aws_sagemaker_image_version" "example" {
  image_name = aws_sagemaker_image.example.id
  base_image = "base-image"
}

resource "aws_sagemaker_domain" "example" {
  domain_name = "example"
  auth_mode   = "IAM"
  vpc_id      = aws_vpc.example.id
  subnet_ids  = [aws_subnet.example.id]

  default_user_settings {
    execution_role  = aws_iam_role.example.arn
    studio_web_portal = "ENABLED"
    kernel_gateway_app_settings {
      custom_image {
        app_image_config_name = aws_sagemaker_app_image_config.example.app_image_config_name
        image_name            = aws_sagemaker_image_version.example.image_name
      }
    }
  }
}
```

### References

See initial description

### Would you like to implement a fix?

None

**Comment by suyashdb** [comment]
Can we please work on this sooner...?
