### ISSUE TITLE
[New Resource]: aws_restore_testing_plan for Automatic restore testing and validation

### ISSUE THREAD

**Issue by jeroenhabets** [hashicorp/terraform-provider-aws#34699]
### Description

A new resource to support AWS Backup's new "Restore testing and validation" feature:
https://aws.amazon.com/blogs/aws/automatic-restore-testing-and-validation-is-now-available-in-aws-backup/

### Requested Resource(s) and/or Data Source(s)

- aws_restore_testing_plan
- aws_restore_testing_selection
- aws_restore_testing_assignment

(Originally thought of aws_backup_restore_plan but probably best to follow SDK precedent.)

### Potential Terraform Configuration

```terraform
aws_restore_testing_plan main {
  name = "tf_example_restore_plan"

  test_frequency     = "Daily"
  start_time         = "22:30"
  start_within_hours = 8 
}

aws_restore_testing_selection {
  vault           = null
  excluded_vaults = []
  eligble_recovery_points {
   from_last      = 8
   from_last_unit = "Days"
  }
  include_pitr    = false
}

aws_restore_testing_assignment {
  name               = "tf_example_restore_assignment"
  iam_role           = null
  retention_period   = null

  resource_type      = "EC2"
  included_resources = []
  included_tags      = []
  
  instance_type      = "t4g.large"
  optional_parameters = []
}
```

### References

- [AWS News Blog - Automatic restore testing and validation now available in AWS Backup](https://aws.amazon.com/blogs/aws/automatic-restore-testing-and-validation-is-now-available-in-aws-backup/)

- [GetRecoveryPointRestoreMetadata](https://docs.aws.amazon.com/sdk-for-go/api/service/backup/#Backup.GetRecoveryPointRestoreMetadata) 	
- [GetRestoreJobMetadata](https://docs.aws.amazon.com/sdk-for-go/api/service/backup/#Backup.GetRestoreJobMetadata) 	
- [GetRestoreTestingInferredMetadata](https://docs.aws.amazon.com/sdk-for-go/api/service/backup/#Backup.GetRestoreTestingInferredMetadata) 	
- [GetRestoreTestingPlan](https://docs.aws.amazon.com/sdk-for-go/api/service/backup/#Backup.GetRestoreTestingPlan) 	
- [GetRestoreTestingSelection](https://docs.aws.amazon.com/sdk-for-go/api/service/backup/#Backup.GetRestoreTestingSelection)

### Would you like to implement a fix?

No

**Comment by ankon** [comment]
There is a PR for this, do you need any help here to get this over the finish line?

**Comment by LozanoMatheus** [comment]
We're also looking forward to getting this one out, does anyone have an update?

**Comment by austinlutesswenson-wk** [comment]
Adding my +1 concerning an update, I'm trying to deploy this for our team as well.

**Comment by jeroenhabets** [comment]
@ewbankkit, @Thomas-Franklin, @aristosvo Thanks for all your work 👍 ! PR https://github.com/hashicorp/terraform-provider-aws/pull/37039 is appreciated 💯

**Comment by ankon** [comment]
Thanks a lot indeed!

@ewbankkit could you maybe also close https://github.com/hashicorp/terraform-provider-aws/issues/37662 as duplicate then?
