### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by teaguru** [hashicorp/terraform-provider-aws#34708]
### Terraform Core Version

v1.6.3

### AWS Provider Version

v5.29.0

### Affected Resource(s)

Regression in aws_db_parameter_group When Upgrading from AWS Provider Version 5.27.0 to 5.29.0

Issue: Encountering a failure with aws_db_parameter_group using AWS provider version 5.29.0 in Terraform, which works correctly under version 5.27.0.

Details:

AWS Provider Version: Issue occurs with 5.29.0; works with 5.27.0
Resource: aws_db_parameter_group
Error Description: "missing or corrupted provider plugins" error when applying plan with terraform apply "/tmp/pgnew.pln". The error message indicates that the package for registry.terraform.io/hashicorp/aws 5.29.0 is not cached in .terraform/providers.

### Expected Behavior

We make 
 terragrunt plan --target='aws_db_parameter_group.pg[0]' -out=/tmp/plan.pln
 terragrunt apply /tmp/plan.pln

### Actual Behavior

We want to apply that aws_db_parameter_group.pg[0]' resource
But we get:
 terraform apply "/tmp/plan.pln"
│ registry.terraform.io/hashicorp/aws: there is no package for registry.terraform.io/hashicorp/aws 5.29.0 cached in .terraform/providers
With v5.27.0 it works well

### Terraform Configuration Files

resource "aws_db_parameter_group" "pg" {
  count = var.db_require_ssl ? 1 : 0

  name   = "${local.db_identifier}${var.db_engine_version}"
  family = "${var.db_engine}${var.db_engine_version}"

  parameter {
    # force_ssl for postgres and require_secure_transport for mysql
    name  = var.db_engine == "postgres" ? "rds.force_ssl" : "require_secure_transport"
    value = "1"
  }
}
and
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

with manual  v5.27.0 it works well

### Steps to Reproduce

 terragrunt plan --target='aws_db_parameter_group.pg[0]' -out=/tmp/plan.pln
 terragrunt apply /tmp/plan.pln

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @teaguru 👋 Thank you for taking the time to raise this! It looks like the provider binary is missing from your local directory, which is causing the error:

> there is no package for registry.terraform.io/hashicorp/aws 5.29.0 cached in .terraform/providers

Since this doesn't appear to be an issue with the provider itself, I'm going to close this issue out.
