### ISSUE TITLE
[New Resource]: Resource for aws_servicecatalog_application

### ISSUE THREAD

**Issue by abebars** [hashicorp/terraform-provider-aws#34702]
### Description

AWS Service Catalog Application registry was [announced](https://aws.amazon.com/about-aws/whats-new/2023/11/myapplications-view-manage-applications-aws/) 
This Issue should add a new resource `aws_servicecatalog_application`

### Requested Resource(s) and/or Data Source(s)

New Resource:
- aws_servicecatalog_application

DataSource:
- aws_servicecatalog_application

### Potential Terraform Configuration

```terraform
resource "aws_servicecatalog_application" "example" {
  name = "example"
}

data "aws_servicecatalog_application" "example" {
  name = "example"
}
```

### References

API Docs: https://docs.aws.amazon.com/servicecatalog/latest/dg/API_Operations_AWS_Service_Catalog_App_Registry.html

### Would you like to implement a fix?

Yes

**Comment by fatbasstard** [comment]
This basically enables the automations of the (also new) `myApplications` feature which I'm looking for to get implemented

**Comment by fatbasstard** [comment]
Yes, want and need this ❤️

**Comment by fatbasstard** [comment]
@abebars Any progress on this already?

**Comment by abebars** [comment]
> @abebars Any progress on this already?

@fatbasstard Yeah, I am working on this right now and going to push a PR today or tomorrow and tag you in

**Comment by steffmartin** [comment]
> > @abebars Any progress on this already?
> 
> @fatbasstard Yeah, I am working on this right now and going to push a PR today or tomorrow and tag you in

I'm looking forward to it too
