### ISSUE TITLE
Would be good to sort data_aws_subnet_ids by availability zone

### ISSUE THREAD

**Issue by foreverblue62** [hashicorp/terraform-provider-aws#3471]
We are in the process of rebuilding our accounts in AWS and one of the key components is building private and public subnets. As such the private subnets connect out to 0.0.0.0/0 via the a nat gateway. I have something similar to:

data "aws_subnet_ids" "selected_be" {
  vpc_id = "${module.mainvpc.vpc_id}"
  tags {
    Location = "be"
  }
}

Which will return three subnets tagged as "backend"  - however it appears that these are return sorted by the subnet id. What I'd like to be able to do is get consistency that ${data.aws_subnet_ids.selected_be.ids[0] always returns the same az regardless of the subnetid ordering. So something like:

data "aws_subnet_ids" "selected_be" {
  vpc_id = "${module.mainvpc.vpc_id}"
  tags {
    Location = "be"
  }
 sort_by = "AZ"
}

where sort_by is optional and will default to the existing behaviour.

**Comment by kl4w** [comment]
Would it make sense to add a new field that allows you to filter the subnets by zone? This would also mean that you would have to create separate data resources for each zone though. 

Something like this? https://github.com/kl4w/terraform-provider-aws/tree/filter-subnets-by-az

**Comment by TylerBrock** [comment]
I think the sort is more critical, IMHO. Getting this list order to be stable actually makes it useful downstream. Right now you wind up building subnet lists over and over again in anything remotely complicated to ensure that generated plans are consistent.

**Comment by pranj** [comment]
Here is a quick and dirty workaround that I was able to use

```
data "aws_subnet" "private" {
  count = "${length(data.aws_subnet_ids.private.ids)}"
  id    = "${data.aws_subnet_ids.private.ids[count.index]}"
}

locals {
  subnet_az_to_id   = "${zipmap(data.aws_subnet.private.*.availability_zone, data.aws_subnet.private.*.id)}"
  subnet_az_to_cidr = "${zipmap(data.aws_subnet.private.*.availability_zone, data.aws_subnet.private.*.cidr_block)}"
  sorted_subnet_azs = "${sort(data.aws_subnet.private.*.availability_zone)}"
}

resource "null_resource" "sorted_subnet" {
  count = "${length(data.aws_subnet_ids.private.ids)}"

  triggers {
    id         = "${lookup(local.subnet_az_to_id, local.sorted_subnet_azs[count.index])}"
    cidr_block = "${lookup(local.subnet_az_to_cidr, local.sorted_subnet_azs[count.index])}"
  }
}
```

**Comment by b-luu** [comment]
Slight simplification: based on the idea that `values()` returns the values in the matching order to `keys()` which returns the keys lexically sorted.

```
data "aws_subnet" "private" {
  count = "${length(data.aws_subnet_ids.private.ids)}"
  id    = "${data.aws_subnet_ids.private.ids[count.index]}"
}

locals {
  ids_sorted_by_az   = "${values(zipmap(data.aws_subnet.private.*.availability_zone, data.aws_subnet.private.*.id))}"
  cidr_sorted_by_az = "${values(zipmap(data.aws_subnet.private.*.availability_zone, data.aws_subnet.private.*.cidr_block))}"
}
```

**Comment by yves-vogl** [comment]
Are you sure this will work?

Using ```aws_subnet_ids``` as count with a filter should lead to the error ```value of 'count' cannot be computed```.
