### ISSUE TITLE
[Enhancement]: Add support for the Agentless Collector for Prometheus for EKS Clusters 

### ISSUE THREAD

**Issue by lorrrrrrrenzo** [hashicorp/terraform-provider-aws#34733]
### Description

AWS announced an [agentless collector for Prometheus and EKS](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-managed-service-prometheus-agentless-collector-metrics-eks/?nc1=h_ls) and I would like to see support for it added to Terraform.

### Affected Resource(s) and/or Data Source(s)

- `aws_eks_cluster`

You may also decide to create a new object to manage the Managed Prometheus/EKS relationship, like `aws_eks_prometheus_collector`

### Potential Terraform Configuration

```terraform
resource "aws_prometheus_workspace" "p8s" {
    alias = "feature_request"
    # ... other fields ...
}

resource "aws_eks_cluster" "eks_one" {
    name = "new-cluster"
    # ... other fields ...
    prometheus_collector {
        endpoint = aws_prometheus_workspace.p8s.prometheus_endpoint
        scrape_configuration = "..."
        connection_subnets = ["subnet-exampleid123", "subnet-exampleid456", "subnet-example789"]
        connection_sgs = ["sg-example12345", "sg-example67890"]
    }
}

#-----
#-----
# Alternative implementation
resource "aws_eks_cluster" "eks_two" {
    name = "alternative-new-cluster"
    # ... other fields ...
}

resource "aws_eks_prometheus_collector" "a" {
    scrape_configuration = "..."
    connection_subnets = ["subnet-exampleid123", "subnet-exampleid456", "subnet-example789"]
    connection_sgs = ["sg-example12345", "sg-example67890"]

    eks_cluster_arn = aws_eks_cluster.eks_two.arn
    managed_p8s_arn = aws_prometheus_workspace.p8s.arn
}
```

### References

[Announcement Blog Post](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-managed-service-prometheus-agentless-collector-metrics-eks/?nc1=h_ls)
[Setup Instructions](https://aws.amazon.com/prometheus/faqs/), under "How do I get started..."

### Would you like to implement a fix?

None

**Comment by andrewbcoyle** [comment]
I would love to see this, and personally I prefer the first approach of the two presented.  That's basically how I imagined it working.
