### ISSUE TITLE
[Enhancement]: aws_kinesis_firehose_delivery_stream to support destination: Coralogix

### ISSUE THREAD

**Issue by zviae** [hashicorp/terraform-provider-aws#34759]
### Description

The resource `resource "aws_kinesis_firehose_delivery_stream"` does not support `destination = "coralogix"` although the option exist in AWS - https://docs.aws.amazon.com/firehose/latest/dev/create-destination.html#create-destination-coralogix

Here are the options for destination:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream#destination
```
[destination](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream#destination) – (Required) This is the destination to where the data is delivered. The only options are s3 (Deprecated, use extended_s3 instead), extended_s3, redshift, elasticsearch, splunk, http_endpoint, opensearch and opensearchserverless. is redshift).
```
Could you please add this destination?

### Affected Resource(s) and/or Data Source(s)

AWS provider 5.29.0

### Would you like to implement a fix?

None

**Comment by DrFaust92** [comment]
Hi, There is no coralogx destination type. its http_endpoint and you need pass params as stated in doc, this should be already supported without added functionality
