### ISSUE TITLE
[New Resource]: `aws_ssoadmin_trusted_token_issuer` 

### ISSUE THREAD

**Issue by jar-b** [hashicorp/terraform-provider-aws#34766]
### Description

Manage AWS Identity Center trusted token issuers with Terraform.

### Requested Resource(s) and/or Data Source(s)

- `aws_ssoadmin_trusted_token_issuer`

### Potential Terraform Configuration

```terraform
resource "aws_ssoadmin_trusted_token_issuer" "example" {
  instance_arn = tolist(data.aws_ssoadmin_instances.test.arns)[0]
  name         = "example"
  issuer_type  = "OIDC_JWT"

  issuer_configuration {
    oidc_jwt_configuration {
      claim_attribute_path          = ""
      identity_store_attribute_path = ""
      issuer_url                    = ""
      jwks_retrieval_option         = "OPEN_ID_DISCOVERY"
    }
  }
}
```

### References

- https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_CreateTrustedTokenIssuer.html
- https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_DescribeTrustedTokenIssuer.html
- https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_UpdateTrustedTokenIssuer.html
- https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_DeleteTrustedTokenIssuer.html

### Would you like to implement a fix?

None

**Comment by DanielRieske** [comment]
👋 I'll gladly pick this up, will add the PR shortly.
