### ISSUE TITLE
[New Resource]: `aws_ssoadmin_application_access_scope` 

### ISSUE THREAD

**Issue by jar-b** [hashicorp/terraform-provider-aws#34762]
### Description

Manage AWS Identity Center application access scopes with Terraform.

### Requested Resource(s) and/or Data Source(s)

- `aws_ssoadmin_application_access_scope`

### Potential Terraform Configuration

```terraform
resource "aws_ssoadmin_application_scope" "example" {
  application_arn    = aws_ssoadmin_application.example.application_arn
  authorized_targets = ["", ""]
  scope              = ""
}
```

### References

- https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_PutApplicationAccessScope.html
- https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_GetApplicationAccessScope.html
- https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_DeleteApplicationAccessScope.html
- Relates #34723 

### Would you like to implement a fix?

None

**Comment by DanielRieske** [comment]
👋 I'll gladly pick this up, will add the PR shortly.
