### ISSUE TITLE
[Enhancement]: Add ability to use multiple target groups in CodeDeploy, in place deployments

### ISSUE THREAD

**Issue by wagnerone** [hashicorp/terraform-provider-aws#34779]
### Description

A few months ago AWS announced the ability to manage targets in multiple ALB target groups when doing a CodeDeploy in-place deployment. Currently the provider only manages a single ALB target group for `aws_codedeploy_deployment_group`. Please enhance it to manage multiple ALB target groups.

### Affected Resource(s) and/or Data Source(s)

* `aws_codedeploy_deployment_group`

### Potential Terraform Configuration

```terraform
resource "aws_codedeploy_deployment_group" "default" {
  app_name              = aws_codedeploy_app.app.name
  deployment_group_name = "app deployment group"
  service_role_arn      = aws_iam_role.role_code_deploy.arn

  autoscaling_groups = var.autoscaling_group_names

  deployment_style {
    deployment_option = local.deployment_style
    deployment_type   = "IN_PLACE"
  }

  load_balancer_info {
    target_group_info {[var.target_group_name_alb_01, var.target_group_name_alb_02]}
  }

  auto_rollback_configuration {
    enabled = true
    events  = ["DEPLOYMENT_FAILURE"]
  }
}
```

### References

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2023/10/aws-codedeploy-multiple-load-balancers-amazon-ec2-applications/)
* [Blog post](https://aws.amazon.com/blogs/devops/multiple-load-balance-support-in-codedeploy/)

### Would you like to implement a fix?

None

**Comment by wagnerone** [comment]
What is the next step to get some traction on this request? Thanks!

**Comment by justinretzolk** [comment]
Hey @wagnerone  👋 Thanks for checking in here! We base our prioritization on the count of :+1: reactions and a few other considerations (more information: [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/)).

**Comment by wagnerone** [comment]
@justinretzolk Thank you for that extra info. I'll sit tight for now.

**Comment by vinz94f** [comment]
Hello,

In the AWS web console, it's possible to select several target groups.

<img width="919" alt="Capture d’écran 2024-03-14 à 16 40 05" src="https://github.com/hashicorp/terraform-provider-aws/assets/10788698/5e7f508c-7035-4596-bcb2-0704b2d28f41">

But it's not possible to do this with the "aws_codedeploy_deployment_group" terraform resource.

Regards,

**Comment by ewbankkit** [comment]
I have verified that you can configured multiple target groups on the `aws_codedeploy_deployment_group` resource:

```hcl
  load_balancer_info {
    target_group_info {
      name = "acc-test-codedeploy-dep-group-1"
    }

    target_group_info {
      name = "acc-test-codedeploy-dep-group-2"
    }

    target_group_info {
      name = "acc-test-codedeploy-dep-group-3"
    }
  }
```
