### ISSUE TITLE
[New Resource]: Log Anomaly Detector 

### ISSUE THREAD

**Issue by dwaynebailey** [hashicorp/terraform-provider-aws#34788]
### Description

Log Groups can be associated with an anomoly detector that search for anomalies in the logs.  These anomolies are displayed for further action or the creation of alarms.

These are switched on per log_group or multiple log_groups.  They accept a further optional filter pattern. The anomolies are kept for 21 days before being considered normal operational values. Evaluation is done periodically between 1 and 60 minutes, which can be set by the user.

### Requested Resource(s) and/or Data Source(s)

* aws_cloudwatch_log_anomaly_detector

### Potential Terraform Configuration

```terraform
resource "aws_cloudwatch_log_anomaly_detector" "example" {
  name = "logs-anomaly-example-detector"
  log_groups = ["arn:aws:logs:xx-xxxx-1:NNNNNNNNN:log-group:/yyyyyy"]
  evaluation_frequency_minutes = 5
  pattern = "{ $.kubernetes.namespace_name = "dev" }"
  anomaly_visibility_day = 21
}
```

### References

* https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/LogsAnomalyDetection-Enable.html
* https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_CreateLogAnomalyDetector.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatchlogs/#CloudWatchLogs.CreateLogAnomalyDetector

### Would you like to implement a fix?

No

**Comment by Eslam-mohammed-anwar** [comment]
any progress on that , or i would like to progress that if you can assign it to me

**Comment by Eslam-mohammed-anwar** [comment]
@justinretzolk Can you please assign to me
