### ISSUE TITLE
[Bug]: Incorrect destruction order for dependencies in CloudWatch Composite Alarms

### ISSUE THREAD

**Issue by shonun1** [hashicorp/terraform-provider-aws#34807]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.30.0

### Affected Resource(s)

`aws_cloudwatch_composite_alarm`, `aws_cloudwatch_metric_alarm`

### Expected Behavior

In a scenario where I have a composite alarm in AWS set up via Terraform, which depends on multiple metric alarms, I expect that when one of these dependent metric alarms is destroyed, the Terraform configuration should automatically update the composite alarm rule to reflect this change before attempting to destroy the alarm.

### Actual Behavior

In my current Terraform setup, when I attempt to destroy a metric alarm that is referenced in a composite alarm, the Terraform plan correctly identifies and displays the need to update the composite alarm alongside the destruction of the metric alarm. However, during the application phase, the execution order is not as expected. Terraform tries to destroy the metric alarm before updating the composite alarm to remove its reference. This incorrect order of operations results in a validation error from AWS, as the composite alarm still references the metric alarm that Terraform is attempting to destroy. The error message from AWS explicitly states that a metric alarm that is part of a composite alarm cannot be deleted, indicating a conflict in the dependency management within Terraform’s execution plan.

### Relevant Error/Panic Output Snippet

```shell
│ Error: deleting CloudWatch Metric Alarm (test-alarm-1): ValidationError: Cannot delete test-alarm-1 as there are composite alarm(s) depending on it.
```

### Terraform Configuration Files

[terraform-aws-github-issue.zip](https://github.com/hashicorp/terraform-provider-aws/files/13613416/terraform-aws-github-issue.zip)

### Steps to Reproduce

1. Apply the configuration after providing a valid `instance_id` and `profile` as input variables.
2. Update the `aws_cloudwatch_metric_alarm` count to 1.
3. Apply the configuration again.

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @shonun1 👋 Thank you for taking the time to raise this! In this case, Terraform is working as I would expect it to, and in the way that is called out in the note at the [top of the `aws_cloudwatch_composite_alarm` documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_composite_alarm):

> [!WARNING]
> An alarm (composite or metric) cannot be destroyed when there are other composite alarms depending on it. This can lead to a cyclical dependency on update, as Terraform will unsuccessfully attempt to destroy alarms before updating the rule. Consider using `depends_on`, references to alarm names, and two-stage updates.

One option you might consider is using [targeted applies](https://developer.hashicorp.com/terraform/tutorials/state/resource-targeting). Since this is something that is documented, and cannot be worked around by the provider at this time, closing.
