### ISSUE TITLE
[Bug]: kms_key_id was not imported

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform-provider-aws#34829]
### Terraform Core Version

1.6.4

### AWS Provider Version

4.67.0

### Affected Resource(s)

aws_db_instance

### Expected Behavior

KMS key ID value should be imported because AWS console shows that KMK key ID exists:
![image](https://github.com/hashicorp/terraform-provider-aws/assets/139780495/b3f02cdf-792a-4cc3-8c0a-8d3308bc3231)

### Actual Behavior

![image](https://github.com/hashicorp/terraform-provider-aws/assets/139780495/ea4efe4f-8c0d-4afb-8197-e13e8dc0b355)

![image](https://github.com/hashicorp/terraform-provider-aws/assets/139780495/d3012809-3c82-4892-aa5e-d6f9003b6ed5)

  

### Terraform Configuration Files

```
import {
  to = aws_db_instance.essential
  id = "prd-postgres-v11"
}
```

### Steps to Reproduce

 terraform plan -generate-config-out=essential.tf

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
I believe that your screenshot is referring to the KMS key for the Performance Insights feature, which corresponds to [the `performance_insights_kms_key_id` attribute](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#performance_insights_kms_key_id) in the `aws_db_instance` resource. It is unrelated to `kms_key_id`.

**Comment by EugenKon** [comment]
@acwwat Yes, you are right.
