### ISSUE TITLE
[Enhancement]: New Resource aws_apprunner_start_deployment

### ISSUE THREAD

**Issue by emoshaya** [hashicorp/terraform-provider-aws#34835]
### Description

Due to a limitation where explained [here](https://docs.aws.amazon.com/apprunner/latest/dg/env-variable.html#:~:text=When%20the%20secrets%20and%20parameter%20values%20are%20rotated%20or%20changed%20they%20are%20not%20automatically%20updated%20in%20your%20App%20Runner%20service.%20Redeploy%20your%20App%20Runner%20service%20as%20App%20Runner%20only%20pulls%20secrets%20and%20parameters%20during%20deployment.).

> When the secrets and parameter values are rotated or changed they are not automatically updated in your App Runner service. Redeploy your App Runner service as App Runner only pulls secrets and parameters during deployment.

We have a use case for manually starting the app runner deployment when an environment variable using aws secret manager/ssm parameter store is updated.

We would like a new resource aws_apprunner_start_deployment to start deployment and have it depend on changes in ssm paramter store / secret manager values

We are currently working around this issue by using the aws cli command: aws apprunner start-deployment

https://docs.aws.amazon.com/cli/latest/reference/apprunner/start-deployment.html

### Affected Resource(s) and/or Data Source(s)

aws_apprunner_start_deployment

### Potential Terraform Configuration

```terraform
resource "aws_apprunner_start_deployment" "example" {
  service_arn = aws_apprunner_service.example.arn
}
```

### References

https://docs.aws.amazon.com/cli/latest/reference/apprunner/start-deployment.html

### Would you like to implement a fix?

None

**Comment by bschaatsbergen** [comment]
Hi @emoshaya, thanks for taking the time to raise this issue! 👏🏼  I'll happily pick this up.

**Comment by bschaatsbergen** [comment]
I am configuring the resource to wait until the deployment operation reaches the 'succeeded' status before deeming the creation process successful.

**Comment by emoshaya** [comment]
@bschaatsbergen any update on this feature?

**Comment by bschaatsbergen** [comment]
> @bschaatsbergen any update on this feature?

Thanks for reaching out @emoshaya, I'm rewriting this resource in the coming days to adhere to the new standard of using the Terraform Provider Plugin Framework, shortly after that I would guess this gets merged. I'll keep you updated.

**Comment by bschaatsbergen** [comment]
@emoshaya quick update from my side: the resource implementation is done, I just need to check why the test is failing.

**Comment by emoshaya** [comment]
That's awesome! thank you for your time and effort on this.. greatly appreciated!
