### ISSUE TITLE
[New Resource]: `aws_imagebuilder_lifecycle_policy` 

### ISSUE THREAD

**Issue by seanturner026** [hashicorp/terraform-provider-aws#34854]
### Description

Image Builder recently added a lifecycle manager that would be super handy in preventing the accumulation of AMIs (and EBS Snapshots?) which cost $$.

https://aws.amazon.com/about-aws/whats-new/2023/11/ec2-image-builder-lifecycle-management-deletion/

### Requested Resource(s) and/or Data Source(s)

`aws_imagebuild_lifecycle_policy`

### Potential Terraform Configuration

```terraform
resource "aws_imagebuilder_lifecycle_policy" "this" {
  name          = string
  enabled       = bool
  description   = string
  resource_type = string // AMI_IMAGE | CONTAINER_IMAGE
  iam_role      = string // name or arn in awscli docs

  // Mutually exclusive?
  resource_selection {
    recipes {
      name             = string
      semantic_version = string
    }

    tags {
      key   = string
      value = string
    }
  }

  // See JSON Syntax in awscli docs
  policy_details {
  }

  lifecycle_rules {
    delete_rule    = bool
    deprecate_rule = bool
    disable_rule   = bool
  }

  tags = map(string)
}
```

### References

https://aws.amazon.com/about-aws/whats-new/2023/11/ec2-image-builder-lifecycle-management-deletion/

### Would you like to implement a fix?

No

**Comment by bschaatsbergen** [comment]
Hey @seanturner026 thanks for taking the time to raise this issue! 👏🏼

**Comment by seanturner026** [comment]
Sounds good! Will update the original post to reflect that. I was looking in the AWS Console when I originally started creating this issue which refers to the resource as a lifecycle I believe.

**Comment by bschaatsbergen** [comment]
I'll happily pick this up too 🚀

**Comment by bschaatsbergen** [comment]
Hey @sophiecosgrove, I'm still working on this - it's just in my "todo" of provider tickets I'm currently working on. I aim to have this done next week.

**Comment by bschaatsbergen** [comment]
Just a quick update: We're actively working on the issue in the background. However, it's taking a bit longer than expected because we need to update the entire image builder service in this provider to use the AWS SDK v2. Thanks for your patience.

**Comment by sethbacon** [comment]
Any updates? Trying to wait patiently on this one :) ...

**Comment by nestorcolt** [comment]
a new AWS provider has been introduced "awscc" which hosts this feature with:
https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/imagebuilder_lifecycle_policy

awscc_imagebuilder_lifecycle_policy (Resource)
Resource schema for AWS::ImageBuilder::LifecyclePolicy

**Comment by mobious999** [comment]
any updates?

**Comment by sophiecosgrove** [comment]
Hi, any updates on this please?

**Comment by bschaatsbergen** [comment]
Hey @sophiecosgrove 👋🏼 , thank you for checking in. We’re still awaiting on [this AWS SDK issue](https://github.com/aws/aws-sdk/issues/736). Our pull request is being monitored closely and will be merged as soon as the AWS SDK issue is resolved. For any urgent matters, it’s best to raise them directly in that issue or reach out to AWS support.

**Comment by seanturner026** [comment]
Thanks for this! 

(Corresponding AWS Provider PR is also merged for anyone else following this thread who was also confused https://github.com/hashicorp/terraform-provider-aws/pull/35674)
