### ISSUE TITLE
[Enhancement]: Support for resizing throughput requirements for FSx Lustre

### ISSUE THREAD

**Issue by dkheyman** [hashicorp/terraform-provider-aws#34862]
### Description

Prior to 11/2023, FSx for Lustre did not allow end users to change or modify the throughput requirements for FSxL filesystems; the filesystem had to be destroyed and recreated. That changed based on [this](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-fsx-lustre-adjust-throughput-tier-file-systems/) announcement. Enhancement for support for modifications to the `per_unit_storage_throughput` key without recreation and destruction of the filesystem.

### Affected Resource(s) and/or Data Source(s)

"aws_fsx_lustre_file_system"

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_lustre_file_system.html#per_unit_storage_throughput

### Potential Terraform Configuration

```terraform
No change, aside from ForceNew = false in https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/fsx/lustre_file_system.go.
```

### References

https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-fsx-lustre-adjust-throughput-tier-file-systems/

### Would you like to implement a fix?

No

**Comment by sasidhar-aws** [comment]
I am working on this issue.
