### ISSUE TITLE
[Enhancement]: 'OptInToArchiveForSupportedResources' for aws backup service

### ISSUE THREAD

**Issue by pdahake** [hashicorp/terraform-provider-aws#34880]
### Description

During re:Invent 2023, AWS announced a feature to archive EBS snapshots created via Backup service by setting "OptInToArchiveForSupportedResources" property.
The setting would be part of the aws_backup_plan lifecycle block.

### Affected Resource(s) and/or Data Source(s)

aws_backup_plan - lifecycle

### Potential Terraform Configuration

```terraform
resource "aws_backup_plan" "example" {
  name = "tf_example_backup_plan"

  rule {
    rule_name         = "tf_example_backup_rule"
    target_vault_name = aws_backup_vault.test.name
    schedule          = "cron(0 12 * * ? *)"

    lifecycle {
      cold_storage_after = 90
      optin_to_archive_for_supported_resources = true <-- new property
      delete_after = 14
    }
  }
}
```

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_plan
https://docs.aws.amazon.com/aws-backup/latest/devguide/creating-a-backup-plan.html#plan-options-and-configuration

### Would you like to implement a fix?

None

**Comment by mmourick** [comment]
I'd like to have a go adding this, will submit a PR soon.
