### ISSUE TITLE
[Enhancement]: aws_networkfirewall_firewall needs to support a timeouts block

### ISSUE THREAD

**Issue by patrickcasady** [hashicorp/terraform-provider-aws#34888]
### Description

aws_networkfirewall_firewall needs to support a timeouts block

This cloud resource frequently takes a long time (more than 20 minutes) to destroy when it is loaded up with any rules. The default timeout of 20 minutes is too low/not realistic for AWS Network Firewall. 

### Affected Resource(s) and/or Data Source(s)

aws_networkfirewall_firewall

### Potential Terraform Configuration

```terraform
resource "aws_networkfirewall_firewall" "example" {
  name                = "example"
  firewall_policy_arn = aws_networkfirewall_firewall_policy.example.arn
  vpc_id              = aws_vpc.example.id
  subnet_mapping {
    subnet_id = aws_subnet.example.id
  }

  tags = {
    Tag1 = "Value1"
    Tag2 = "Value2"
  }

  timeouts {
     create = "30m"
     delete = "30m"
  }
}
```

### References

16:53:59  TestBasic 2023-12-11T21:53:59Z logger.go:66: [31m│[0m [0m[1m[31mError: [0m[0m[1mwaiting for NetworkFirewall Firewall (arn:aws:network-firewall:us-east-1:882292917843:firewall/aws-firewall-vpc-test) delete: timeout while waiting for resource to be gone (last state: 'DELETING', timeout: 20m0s)[0m

CDK Deployment
:sparkles: Total time: 363.95s (6 min 4 sec)
CDK Destroy
:sparkles: Total time: 1292s (21 min 32 sec)

Not just terraform, Network Firewall is a slow resource to destroy

### Would you like to implement a fix?

None

**Comment by Kiyo510** [comment]
Hello! @AdamTylerLynch
May I work on this issue?
This is my first time contributing to Terraform, but I think I can implement it in about 10 days.
