### ISSUE TITLE
[Bug]: provider should not silently ignore EKS encryption_config provider arn_key change

### ISSUE THREAD

**Issue by splichy** [hashicorp/terraform-provider-aws#34883]
### Description

Provider should not silently ignore attempts to update [key_arn](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#key_arn) as AWS API doesn't even implement an update method. 

The provider should print at least a warning or it should plan re-create, as silently ignoring that makes the state file to be inconsistent with reality.

Provider instead plans change and then it also reflects new key_arn in the state file, while old key_arn is still used by EKS
```
  # module.eks.aws_eks_cluster.this[0] will be updated in-place
  ~ resource "aws_eks_cluster" "this" {
        id                        = "eks-cluster"
        name                      = "eks-cluster"
        # (11 unchanged attributes hidden)

      ~ encryption_config {
            # (1 unchanged attribute hidden)

          ~ provider {
              ~ key_arn = "arn:aws:kms:us-east-2:111111111111:key/a17cad0e-09fe-41cc-b9c1-db6e5c665bfd" -> "arn:aws:kms:us-east-2:111111111111:key/841942d8-2465-40d5-9adc-a731f4acdd74"
            }
        }

        # (3 unchanged blocks hidden)
    }
```
and after  terraform apply:
```
$ aws eks describe-cluster --name eks-cluster --query 'cluster.encryptionConfig[0].provider.keyArn' --output text
arn:aws:kms:us-east-2:111111111111:key/a17cad0e-09fe-41cc-b9c1-db6e5c665bfd
```

Maybe it can be implemented directly in resource schema, in a similar way as e.g.  https://github.com/hashicorp/terraform-provider-aws/blob/6f7f7bd17064dfb4111d7c7cc12c76399618472a/internal/service/rds/cluster.go#L494C1-L509C6
(which allow the attribute to be set from some value to null without forcing re-create)

@ewbankkit - what do you think? 

### Affected Resource(s) and/or Data Source(s)

aws_eks_cluster

### References

introduced by https://github.com/hashicorp/terraform-provider-aws/pull/19986

### Would you like to implement a fix?

None

**Comment by bryantbiggs** [comment]
have you tried this on the latest provider version? is this still an issue?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
