### ISSUE TITLE
[New]: AWS  EMR Stduo Batch Jobs Only Version

### ISSUE THREAD

**Issue by Simbonggeol** [hashicorp/terraform-provider-aws#34894]
### Description

I want use terraform resource aws_emr_stduio, But Terraform not supprot aws_emr_studio batch jobs only 
Because  now  terraform resource aws_emr_studio auth_mode, default_s3_location, name ,.... 
I need only terraform aws_emr_studio required argument -> name, studio type 
Plz hurry up

### Requested Resource(s) and/or Data Source(s)

aws_emr_studio

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @Simbonggeol 👋 Thank you for taking the time to raise this! Can you provide a sample configuration, as well as a bit more details around what you're requesting for whoever looks into this?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
