### ISSUE TITLE
[Bug]: aws_cloudwatch_log_group resource not compatible with GovCloud

### ISSUE THREAD

**Issue by jgrant-sms** [hashicorp/terraform-provider-aws#34907]
### Terraform Core Version

1.6.5

### AWS Provider Version

5.30.0

### Affected Resource(s)

aws_cloudwatch_log_group

### Expected Behavior

I should be able to deploy the resource to GovCloud.

### Actual Behavior

`5.30.0` introduced the `log_group_class`argument with a default value of "STANDARD".

This is not supported in AWS Gov Cloud.

### Relevant Error/Panic Output Snippet

```shell
│ Error: creating CloudWatch Logs Log Group (test): operation error CloudWatch Logs: CreateLogGroup, https response error StatusCode: 400, RequestID: 9d8ee0c2-6444-493e-b873-a1aa4d8b81e2, InvalidParameterException: Only Standard log class is supported.
│ 
│   with aws_cloudwatch_log_group.test,
│   on main.tf line 14, in resource "aws_cloudwatch_log_group" "test":
│   14: resource "aws_cloudwatch_log_group" "test" {
```

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.30.0"
    }
  }
}

provider "aws" {
  region = "us-gov-east-1"
}

resource "aws_cloudwatch_log_group" "test" {
  name = "test"
}
```

### Steps to Reproduce

```
terraform init
terraform apply
```

Changing the required provider version to 5.29.0 will successfully apply.

### Important Factoids

Late November AWS Releases Infrequency Access Storage Class for CloudWatch Logs: https://aws.amazon.com/blogs/aws/new-amazon-cloudwatch-log-class-for-infrequent-access-logs-at-a-reduced-price/

This is not available in GovCloud

Early December this feature is supported with the AWS Provider: https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.30.0

Even though the provider supplies a default of 'STANDARD', the AWS API in GovCloud does not accept this as a parameter.

### Would you like to implement a fix?

No

**Comment by rsavage-nozominetworks** [comment]
Seeing the same/similar behavior in AWS GOV* accounts after an attempt to upgrade to `v5.30.0`.   In my case, the provider wants to completely replace the existing log group as well.

**Comment by ewbankkit** [comment]
@jgrant-sms Thanks for raising this issue.
It has already been noticed in #34810. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
