### ISSUE TITLE
[Enhancement]: Support for cross-region restores in aws_dynamodb_table

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#34911]
### Description

DynamoDB restores allow restoring a table to a different region. Per AWS [documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/PointInTimeRecovery.Tutorial.html):

> - The sse-specification-override parameter is mandatory for cross-Region restores but optional for restores to the same Region as the source table.

> - The source-table-arn parameter must be provided for cross-Region restores.

> - When performing a cross-Region restore from the command line, you must set the default AWS Region to the desired destination Region. To learn more, see [Command line options](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-options.html) in the AWS Command Line Interface User Guide.

Currently neither `source_table_arn` or `sse_specification_override` are supported by the `aws_dynamodb_resource`

### Affected Resource(s) and/or Data Source(s)

* aws_dynamodb_table

### Potential Terraform Configuration

```terraform
resource "aws_dynamodb_table" "basic-dynamodb-table" {
  restore_source_name                = ""
  restore_date_time                  = ""
  restore_source_table_arn           = "table_arn"
  restore_sse_specification_override = "Enabled=true,SSEType=KMS,KMSMasterKeyId=abcd1234-abcd-1234-a123-ab1234a1b234"
}
```

### References

- https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/PointInTimeRecovery.Tutorial.html

### Would you like to implement a fix?

None

**Comment by johnsonaj** [comment]
`sse_specification_override` is already available via the `server_side_encryption` attribute
