### ISSUE TITLE
[Bug]: aws_cloudwatch_log_group new property log_group_class forces replacement

### ISSUE THREAD

**Issue by raphael-ratepay** [hashicorp/terraform-provider-aws#34924]
### Terraform Core Version

v1.4.4

### AWS Provider Version

5.30

### Affected Resource(s)

aws_cloudwatch_log_group

### Expected Behavior

provider update should not replace log_groups

### Actual Behavior

terraform tries to replace the log_groups

### Relevant Error/Panic Output Snippet

```shell
Terraform plan generates the following output:


 resource "aws_cloudwatch_log_group" "documentdb_cluster_audit_log_group" {
      ~ arn               = "arn:aws:logs:eu-central-1:123456789012:log-group:/aws/docdb/audit" -> (known after apply)
      ~ id                = "/aws/docdb/audit" -> (known after apply)
      + log_group_class   = "STANDARD" # forces replacement
        name              = "/aws/docdb/audit"
      + name_prefix       = (known after apply)
```

### Terraform Configuration Files

```
resource "aws_cloudwatch_log_group" "audit_logs" {
  name = "/aws/docdb/audit"
}
```  

### Steps to Reproduce

* deploy the log-group with version < 5.30
* update provider to latest
* run terraform plan

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Fixed via https://github.com/hashicorp/terraform-provider-aws/issues/34812.
