### ISSUE TITLE
[Enhancement]: Add support for python3.12 lambda runtime

### ISSUE THREAD

**Issue by artkrz** [hashicorp/terraform-provider-aws#34944]
### Description

Add support for python3.12 lambda runtime

### Affected Resource(s) and/or Data Source(s)

- aws_lambda_function
- aws_lambda_layer_version

### Potential Terraform Configuration

```terraform
``
resource "aws_lambda_function" "test_lambda" {
  ...
  runtime = "python3.12"
  ...
}
``
```

### References

https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

### Would you like to implement a fix?

None

**Comment by harshavmb** [comment]
Hi @artkrz ,

Isn't this already supported? The current provider version `5.31.0` seems to be using `v.1.49.5` lambda restapi which supports `python3.12` runtime. 

You could have a look [here](https://github.com/aws/aws-sdk-go-v2/blob/service/lambda/v1.49.5/service/lambda/types/enums.go#L417).

**Comment by artkrz** [comment]
@harshavmb I'll check again, maybe I was not on latest provider version for some reason.
