### ISSUE TITLE
[Bug]: aws_cloudwatch_event_rule not using event_bus_name

### ISSUE THREAD

**Issue by JarrodFolinoFC** [hashicorp/terraform-provider-aws#34949]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.31.0

### Affected Resource(s)

aws_cloudwatch_event_rule

### Expected Behavior

The event bridge rule should be created on "my-event-bridge-bus2" and not on the default bus

### Actual Behavior

Event bridge rule is on the default bus

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
       version = ">= 5.31.0"
    }
  }
}

resource "aws_cloudwatch_event_bus" "event_bridge_bus" {
    name = "my-event-bridge-bus2"
}


# Event Rule to capture events from S3 bucket
resource "aws_cloudwatch_event_rule" "event_rule" {
    depends_on = [aws_cloudwatch_event_bus.event_bridge_bus]
    name        = "my-event-rule"
    description = "Event rule for capturing events from S3 bucket"
    event_bus_name = aws_cloudwatch_event_bus.event_bridge_bus.arn

    event_pattern = <<PATTERN
{
    "source": ["aws.s3"],
    "detail-type": ["AWS API Call via CloudTrail"],
    "detail": {
        "eventSource": ["s3.amazonaws.com"],
        "eventName": ["PutObject", "DeleteObject"]
    }
}
PATTERN
}
```

### Steps to Reproduce

terraform init
terraform plan
terraform apply -auto-approve

### Would you like to implement a fix?

None

**Comment by naruse666** [comment]
@JarrodFolinoFC Hi.
It doesn't reproduce in my environment.
```sh
$ terraform version
Terraform v1.5.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v5.31.0
```

event_rule is correctly associated with `my-event-bridge-bus2`.

**Comment by justinretzolk** [comment]
Hey @JarrodFolinoFC 👋 Thank you for taking the time to raise this! With the above in mind (thanks @naruse666!), can you supply debug logs (redacted as needed) so that whoever picks this up has the necessary information in order to look into it?

**Comment by justinretzolk** [comment]
Given that this wasn't reproducible, and that we haven't heard back with additional logging to aid an investigation, closing this issue. If you have additional issues, please open a new issue, referencing this one where necessary.
