### ISSUE TITLE
[Enhancement]: FSx for NetApp ONTAP scale-out support

### ISSUE THREAD

**Issue by awsaxeman** [hashicorp/terraform-provider-aws#34953]
### Description

AWS released scale-out support for Amazon FSx for NetApp ONTAP. This enhancement will allow support for deploying FSx for ONTAP File Systems with multiple HA Pairs.

### Affected Resource(s) and/or Data Source(s)

- aws_fsx_ontap_file_system

### Potential Terraform Configuration

```terraform
resource "aws_fsx_ontap_file_system" "test" {
  storage_capacity    = 2048
  subnet_ids          = [aws_subnet.test[0].id]
  deployment_type     = "SINGLE_AZ_2"
  ha_pairs            = 2
  throughput_capacity_per_ha_pair = 3072
  preferred_subnet_id = aws_subnet.test[0].id
}
```

### References

https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-fsx-netapp-ontap-scale-out-file-systems/

### Would you like to implement a fix?

Yes

**Comment by awsaxeman** [comment]
Started work on this enhancement

**Comment by pannujat** [comment]
When would v5.32.0 be GA?
