### ISSUE TITLE
[Enhancement]: Amazon Kinesis Data Firehose CloudWatch Logs Decompression

### ISSUE THREAD

**Issue by mikecarr2** [hashicorp/terraform-provider-aws#34958]
### Description

AWS have recently announced the ability to natively decompress CloudWatch logs prior to sending them onto Splunk and S3 destinations. 

### Affected Resource(s) and/or Data Source(s)

- aws_kinesis_firehose_delivery_stream

### Potential Terraform Configuration

```terraform
resource "aws_kinesis_firehose_delivery_stream" "extended_s3_stream" {
  name        = "terraform-kinesis-firehose-extended-s3-test-stream"
  destination = "extended_s3"

  extended_s3_configuration {
    role_arn   = aws_iam_role.firehose_role.arn
    bucket_arn = aws_s3_bucket.bucket.arn

    processing_configuration {
      enabled = "true"
      decompress_cloudwatch_logs = "true"
    }
  }
}
```

### References

- https://aws.amazon.com/about-aws/whats-new/2023/12/amazon-kinesis-data-firehose-decompressed-cloudwatch-logs-destinations/

### Would you like to implement a fix?

No

**Comment by mrmatos6837** [comment]
Apparently, Terraform already supports this, even though the documentation has not been updated yet.
If you simply create a new Processor with type "Decompression" it will generate the Kinesis Firehose with the "CloudWatch Logs Decompression" enabled.

I'm assuming Terraform is simply passing it forward to the AWS CLI, [which is already updated to support that feature](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/firehose/create-delivery-stream.html).

After some testing I figured out that the correct "parameter_name" should be "CompressionFormat" and the "parameter_value" should be "GZIP" but, amazingly, it will also work with anything else (if you put any other _valid_ parameters, upon deployment it changes to these values).

Here's the complete snippet for anyone else that's trying to figure this out:

```
processing_configuration {
  enabled = "true"
  processors {
    type = "Decompression"
    parameters {
      parameter_name  = "CompressionFormat"
      parameter_value = "GZIP"
    }
  }
}
```

You're welcome 😉

**Comment by mikecarr2** [comment]
Amazing, thank you @mrmatos6837!
