### ISSUE TITLE
[Docs]: Error in description of argument ec2_managed_prefix_list_entry 

### ISSUE THREAD

**Issue by aviv-adriengarcia** [hashicorp/terraform-provider-aws#34963]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_managed_prefix_list_entry

### Description

There is a mistake in the description of the prefix_list_id argument:

- [`prefix_list_id`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_managed_prefix_list_entry#prefix_list_id) - (Required) CIDR block of this entry.

Certainly a copy paste of the description of the cidr argument.
Should be something like:

- [`prefix_list_id`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_managed_prefix_list_entry#prefix_list_id) - (Required) ID of the prefix list.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @aviv-adriengarcia 👋 Thank you for taking the time to raise this! I've opened a PR to correct the docs.
