### ISSUE TITLE
Error with aws_sagemaker_user_profile workspace_settings: Unsupported Block Type

### ISSUE THREAD

**Issue by Viswajenny** [hashicorp/terraform-provider-aws#34976]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_user_profile

### Description

Hi Team,

I am getting an error while using the [workspace_settings](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_user_profile#workspace_settings), we are using this setting to specify/update the Amazon S3 path where SageMaker Studio will store artifacts

**Terraform configuration**
```
resource "aws_sagemaker_user_profile" "sagemaker_user" {
  domain_id         = aws_sagemaker_domain.domain_name.id
  user_profile_name = "user"

  workspace_settings {
    s3_artifact_path = aws_s3_bucket.s3bucket-name.arn

    user_settings {
      execution_role = aws_iam_role.iam_role_name.arn

    }
  }
}
```

Error: Unsupported block type

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @Viswajenny 👋 Thank you for taking the time to raise this! It looks like you've got the `user_settings` block nested within the `workspace_settings` block. Looking at the documentation, however, the `workspace_settings` block is a sub-block of `canvas_app_settings`, which is itself a sub-block of `user_settings. That would look more like:

```terraform
resource "aws_sagemaker_user_profile" "sagemaker_user" {
  domain_id         = aws_sagemaker_domain.domain_name.id
  user_profile_name = "user"

  user_settings {
    execution_role = aws_iam_role.iam_role_name.arn

    canvas_app_settings {
      workspace_settings {
        s3_artifact_path = aws_s3_bucket.s3bucket-name.arn
      }
    }
  }
}
```

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.

**Comment by Viswajenny** [comment]
Thank you, its working!
