### ISSUE TITLE
[Docs]: DocumentDB-elastic has errors in the docs 

### ISSUE THREAD

**Issue by artur-coelho-planview** [hashicorp/terraform-provider-aws#34970]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/docdbelastic_cluster

### Description

The argument cluster_name mentioned in the documentation does not exist (I assume the correct one is name) and the argument [preffered_maintenance_window](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/docdbelastic_cluster#preffered_maintenance_window) seems to be misspelled (I assume it is supposed to be preferred_maintenance_window)

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/docdbelastic_cluster#preffered_maintenance_window

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @artur-coelho-planview 👋 Thank you for taking the time to raise this! I've opened a PR to correct the typos.
