### ISSUE TITLE
[Enhancement]: Support Guard Duty ECS runtime monitoring 

### ISSUE THREAD

**Issue by andwrobs** [hashicorp/terraform-provider-aws#34973]
### Description

As of November 26, 2023, AWS Guard Duty supports [Runtime Monitoring for ECS](https://aws.amazon.com/blogs/aws/introducing-amazon-guardduty-ecs-runtime-monitoring-including-aws-fargate/?sc_icampaign=launch_reinvent23-amazon-guardduty-ec2-runtime-monitoring-preview&sc_ichannel=ha&sc_icontent=awssm-3986_launch_reinvent23&sc_iplace=ribbon&trk=8e510520-1260-4c74-95da-ea1b33f0faa8~ha_awssm-3986_launch_reinvent23). 

`aws_guardduty_detector_feature` supports EKS_RUNTIME_MONITORING, but has no option for ECS

### Requested Resource(s) and/or Data Source(s)

aws_guardduty_detector_feature

### Potential Terraform Configuration

```terraform
name = ECS_RUNTIME_MONITORING # add another option to the aws_guardduty_detector_feature -> name param
```

### References

[AWS announcement post](https://aws.amazon.com/blogs/aws/introducing-amazon-guardduty-ecs-runtime-monitoring-including-aws-fargate/#:~:text=GuardDuty%20ECS%20Runtime%20Monitoring%20helps,over%2030%20different%20finding%20types.)

[Current GuardDuty Terraform resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_detector_feature#name)

### Would you like to implement a fix?

None

**Comment by gid0** [comment]
It already kinda works. Using this configuration enables all runtime monitoring features:

```
resource "aws_guardduty_detector_feature" "runtime_monitoring" {
  detector_id = data.aws_guardduty_detector.main.id
  name        = "RUNTIME_MONITORING"
  status      = "ENABLED"

  additional_configuration {
    name   = "ECS_FARGATE_AGENT_MANAGEMENT"
    status = "ENABLED"
  }

  additional_configuration {
    name   = "EKS_ADDON_MANAGEMENT"
    status = "ENABLED"
  }
}

resource "aws_guardduty_organization_configuration_feature" "runtime_monitoring" {
  detector_id = data.aws_guardduty_detector.main.id
  name        = "RUNTIME_MONITORING"
  auto_enable = "ALL"

  additional_configuration {
    name        = "ECS_FARGATE_AGENT_MANAGEMENT"
    auto_enable = "ALL"
  }

  additional_configuration {
    name        = "EKS_ADDON_MANAGEMENT"
    auto_enable = "ALL"
  }
}
```

The only problem that I noticed is that Terraform will try to reorder `additional_configuration` whenever applying changes. I tried putting ECS after EKS and it's the same. The AWS API always returns the additional configuration in the same order that is different from Terraform. Terraform would just need to ignore the order of `additional_configuration` and everything would be nice (this feature just needs a documentation update).

**Comment by cyn110** [comment]
> It already kinda works. Using this configuration enables all runtime monitoring features:
> 
> ```
> resource "aws_guardduty_detector_feature" "runtime_monitoring" {
>   detector_id = data.aws_guardduty_detector.main.id
>   name        = "RUNTIME_MONITORING"
>   status      = "ENABLED"
> 
>   additional_configuration {
>     name   = "ECS_FARGATE_AGENT_MANAGEMENT"
>     status = "ENABLED"
>   }
> 
>   additional_configuration {
>     name   = "EKS_ADDON_MANAGEMENT"
>     status = "ENABLED"
>   }
> }
> 
> resource "aws_guardduty_organization_configuration_feature" "runtime_monitoring" {
>   detector_id = data.aws_guardduty_detector.main.id
>   name        = "RUNTIME_MONITORING"
>   auto_enable = "ALL"
> 
>   additional_configuration {
>     name        = "ECS_FARGATE_AGENT_MANAGEMENT"
>     auto_enable = "ALL"
>   }
> 
>   additional_configuration {
>     name        = "EKS_ADDON_MANAGEMENT"
>     auto_enable = "ALL"
>   }
> }
> ```
> 
> The only problem that I noticed is that Terraform will try to reorder `additional_configuration` whenever applying changes. I tried putting ECS after EKS and it's the same. The AWS API always returns the additional configuration in the same order that is different from Terraform. Terraform would just need to ignore the order of `additional_configuration` and everything would be nice (this feature just needs a documentation update).

Doesn't seem to work for me:
``` expected name to be one of ["S3_DATA_EVENTS" "EKS_AUDIT_LOGS" "EBS_MALWARE_PROTECTION" "RDS_LOGIN_EVENTS" "EKS_RUNTIME_MONITORING" "LAMBDA_NETWORK_LOGS"], got RUNTIME_MONITORING
```
```
expected additional_configuration.0.name to be one of ["EKS_ADDON_MANAGEMENT"], got ECS_FARGATE_AGENT_MANAGEMENT```

**Comment by nronnei** [comment]
@gid0 do you still see the ordering error with this solution? If so, what does your workaround look like?

**Comment by gid0** [comment]
> @gid0 do you still see the ordering error with this solution? If so, what does your workaround look like?

Hey, really sorry to comment on a closed issue... but yes there is still this perpetual resource update issue with the latest provider version as of today (`v5.39.1`):

![Screenshot 2024-03-07 at 16 00 19](https://github.com/hashicorp/terraform-provider-aws/assets/18396223/5a6ac845-31bd-4188-a7ce-95bedc6d22f0)

The order of the `additional_configuration` blocks doesn't matter here. Whether you use this:

```
resource "aws_guardduty_detector_feature" "runtime_monitoring" {
  detector_id = data.aws_guardduty_detector.main.id
  name        = "RUNTIME_MONITORING"
  status      = "ENABLED"

  additional_configuration {
    name   = "ECS_FARGATE_AGENT_MANAGEMENT"
    status = "ENABLED"
  }

  additional_configuration {
    name   = "EKS_ADDON_MANAGEMENT"
    status = "ENABLED"
  }
}
```
or:

```
resource "aws_guardduty_detector_feature" "runtime_monitoring" {
  detector_id = data.aws_guardduty_detector.main.id
  name        = "RUNTIME_MONITORING"
  status      = "ENABLED"

  additional_configuration {
    name   = "EKS_ADDON_MANAGEMENT"
    status = "ENABLED"
  }

  additional_configuration {
    name   = "ECS_FARGATE_AGENT_MANAGEMENT"
    status = "ENABLED"
  }
}
```

terraform plan will always show this change and update the resource.
