### ISSUE TITLE
[New Resource]: Add EKS cluster IAM access management API resources

### ISSUE THREAD

**Issue by seifrajhi** [hashicorp/terraform-provider-aws#34982]
### Description

AWS Announced new EKS feature that simplifies controls for IAM cluster access management,  and AWS SDK Go v2 has been released including this feature.

As a prerequisite the `authenticationMode` of the cluster  should be either `API` or `API_AND_CONFIG_MAP`

### Requested Resource(s) and/or Data Source(s)

1- `access_entry`
```
resource "access_entry" "foo" {
  cluster_name = "my_cluster"
  iam_principal_arn = "IAM_PRINCIPAL_ARN"
}
```

2-  `access_policy_association`
```
resource "access_policy_association" "bar" {
  cluster_name = "my_cluster"
  iam_principal_arn = "IAM_PRINCIPAL_ARN"
  iam_policy_arn = "arn:aws:eks::aws:cluster-access-policy/XXXX"
}
```

where `XXXX`  = `AmazonEKSAdminPolicy` , `AmazonEKSClusterAdminPolicy `, `AmazonEKSEditPolicy` or `AmazonEKSViewPolicy`

### References

1- Announcement: https://aws.amazon.com/about-aws/whats-new/2023/12/amazon-eks-controls-iam-cluster-access-management/

2- Blog post: https://aws.amazon.com/blogs/containers/a-deep-dive-into-simplified-amazon-eks-access-management-controls/

3- AWS SDK go v2 CHANGELOG:  https://github.com/aws/aws-sdk-go-v2/blob/main/service/eks/CHANGELOG.md#v1360-2023-12-18

### Would you like to implement a fix?

None

**Comment by sidewinder12s** [comment]
Likely also need to update the cluster config resources to support setting the authenticationMode right?

**Comment by seifrajhi** [comment]
Hey @sidewinder12s,

Yes, I have mentioned that in the issue description:

> As a prerequisite the authenticationMode of the cluster should be either API or API_AND_CONFIG_MAP

**Comment by bryantbiggs** [comment]
cc @wellsiau-aws / @meetreks - if you want to open the PR now

**Comment by wellsiau-aws** [comment]
@meetreks and @sasidhar-aws is actively working on this

**Comment by gothrek22** [comment]
Access entry requires a lot more params, most of them optional, compared to what's requested here. I.e.:

```terraform
resource aws_eks_access_entry example {
  iam_role = arn:aws:iam::012345678910:role/MyRole
  username = "my-other-username" (optional)
  kubernetes_groups = "my-other-group" (optional)
  type = "" (optional, options are: 
    EC2_LINUX
    EC2_WINDOWS
    FARGATE_LINUX
    STANDARD
  )
}
```

As entries for node bootstrap also need to be supported. Same with `authenticationMode`, which needs a note that it's a one way street if you go from `API_AND_CONFIG_MAP` to `API`. And that should be a new optional param within `aws_eks_cluster` imho. Wit the default of CONFIG_MAP. That way it's backwards compatible.

Here's a good doc on what is covered by this change: https://github.com/aws/containers-roadmap/issues/185#issuecomment-1863025784

**Comment by stevehipwell** [comment]
FYI there are comments on #35037 suggesting that this hasn't been implemented correctly.
