### ISSUE TITLE
[Docs]: resource/aws_cloudwatch_event_rule

### ISSUE THREAD

**Issue by ericrichtert** [hashicorp/terraform-provider-aws#34988]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_rule

### Description

We migrated all aws_cloudwatch_event_rule resources from "is_enabled=true" to "state=ENABLED_WITH_ALL_CLOUDTRAIL_MANAGEMENT_EVENTS". But that stopped all scheduled event_rules from being triggered.
AWS explained this as "works as designed" and will implement an error on the combination of a scheduled event_rule and ENABLED_WITH_ALL_CLOUDTRAIL_MANAGEMENT_EVENTS.

Is this something to:
* write down in the docs?
* add as validation? 
* both?

### References

#34510

### Would you like to implement a fix?

No

**Comment by acwwat** [comment]
Looks like the AWS API is now returning a 400 error for this scenario:

```console
│ Error: creating EventBridge Rule (capture-aws-sign-in): ValidationException: ENABLED_WITH_ALL_CLOUDTRAIL_MANAGEMENT_EVENTS rule state is not supported with scheduled rule expressions.    
│       status code: 400, request id: c8f01078-41a9-4fc0-a7e3-76997c3189bc
```

For good measure, I will add a note in the resource doc.
