### ISSUE TITLE
[Enhancement]: Cloud9 support Amazon Linux 2023

### ISSUE THREAD

**Issue by jornfranke** [hashicorp/terraform-provider-aws#34995]
### Description

Cloud9 supports now Amazon Linux 2023 see [here](https://aws.amazon.com/about-aws/whats-new/2023/12/aws-cloud9-amazon-linux-2023/). 

Currently the [Cloud9 resource](aws_cloud9_environment_ec2) supports providing an image_id, which is passed to the API (cf. https://docs.aws.amazon.com/cloud9/latest/APIReference/API_CreateEnvironmentEC2.html). Unfortunately the Terraform Cloud9 resource does NOT know the new Amazon Linux 2023 images, although they are supported by the AWS API:
* amazonlinux-2023-x86_64
* resolve:ssm:/aws/service/cloud9/amis/amazonlinux-2023-x86_64

This means that you simply should allow also in Terraform those images.

### Affected Resource(s) and/or Data Source(s)

* aws_cloud9_environment_ec2

### Potential Terraform Configuration

```terraform
resource "aws_cloud9_environment_ec2" "example" {
  instance_type = "t2.micro"
  name          = "example-env"
  image_id      = "resolve:ssm:/aws/service/cloud9/amis/amazonlinux-2023-x86_64"
}
```

### References

https://docs.aws.amazon.com/cloud9/latest/APIReference/API_CreateEnvironmentEC2.html

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloud9_environment_ec2

### Would you like to implement a fix?

None

**Comment by JonZeolla** [comment]
I'd like to work on this issue.
