### ISSUE TITLE
[Bug]: VPC IPv6 CIDR Block Association only allows /56 netmask

### ISSUE THREAD

**Issue by kwohlfahrt** [hashicorp/terraform-provider-aws#34992]
### Terraform Core Version

v1.6.6-dev

### AWS Provider Version

v5.31.0

### Affected Resource(s)

aws_vpc_ipv6_cidr_block_association

### Expected Behavior

I expect to be able to provision an IPv6 CIDR block association from an IPAM pool, that has a netmask length of `/60`. For example:

```terraform
resource "aws_vpc_ipv6_cidr_block_association" "test" {
  vpc_id              = resource.aws_vpc.test.id
  ipv6_ipam_pool_id   = data.aws_vpc_ipam_pool.test.id
  ipv6_netmask_length = 60
}
```

### Actual Behavior

I get the following error:

```
expected ipv6_netmask_length to be one of [56], got 60
```

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: expected ipv6_netmask_length to be one of [56], got 60
│ 
│   with aws_vpc_ipv6_cidr_block_association.test,
│   on main.tf line 28, in resource "aws_vpc_ipv6_cidr_block_association" "test":
│   28:   ipv6_netmask_length = 60
│ 
╵
```

### Terraform Configuration Files

`main.tf`

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.31"
    }
  }

  required_version = ">= 1.6.1"
}

provider "aws" {
  region  = "us-east-1"
}

data "aws_vpc_ipam_pool" "test" {
  filter {
    name   = "address-family"
    values = ["ipv6"]
  }
}

resource "aws_vpc" "test" {}

resource "aws_vpc_ipv6_cidr_block_association" "test" {
  vpc_id              = resource.aws_vpc.test.id
  ipv6_ipam_pool_id   = data.aws_vpc_ipam_pool.test.id
  ipv6_netmask_length = 60
}
```

### Steps to Reproduce

An IPv6 IPAM pool must exist in the current region. I can't easily show this in the repro example, since there is an account-wide quota limit of 1 for htis resource.

### References

This is caused by the check [here](https://github.com/hashicorp/terraform-provider-aws/blob/ba227957595c95ef5f5c2b7a34b5c1c7c65a0210/internal/service/ec2/vpc_ipv6_cidr_block_association.go#L62C18-L70), which only allows a `/56` CIDR. [AWS's documentation](https://docs.aws.amazon.com/vpc/latest/userguide/modify-vpcs.html#vpc-associate-ipv6-cidr) however states that values betwen `/44` and `/60` in increments of `/4` are permitted when allocating an IPv6 CIDR from an IPAM pool:

> If there is no default netmask length selected for the IPAM pool, choose a netmask length that's more specific than the netmask length of the IPAM pool CIDR. For example, if the IPAM pool CIDR is /50, you can choose a netmask length between /52 to /60 for the VPC. **Possible netmask lengths are between /44 and /60 in increments of /4.**

### Would you like to implement a fix?

Yes

**Comment by kwohlfahrt** [comment]
IMO the correct fix would be to remove the check on the value of the `ipv6_netmask_length` field (or limit it to the range of 0-128). This would allow some invalid values to be specified (e.g. those not multiples of 4), but on the other hand AWS might change the restrictions in future again, so it doesn't seems sensible to validate this client-side.

**Comment by drewmullen** [comment]
I believe this was changed by the ipam team post service launch and is correctly labeled a bug. The validation should be removed or updated

**Comment by k1rk** [comment]
i created a PR addressing this, but not sure how to get some attention to it 🙂  https://github.com/hashicorp/terraform-provider-aws/pull/35614
