### ISSUE TITLE
[Enhancement]: aws_cognito_user_pool: enable lambda_version for pre_token_generation

### ISSUE THREAD

**Issue by lorchda** [hashicorp/terraform-provider-aws#35007]
### Terraform Core Version

1.5.3

### AWS Provider Version

5.31.0

### Affected Resource(s)

* aws_cognito_user_pool

### Expected Behavior

Amazon Cognito introduced a new User pool trigger version **V2_0** for the pre token generation Lambda:
* https://aws.amazon.com/de/about-aws/whats-new/2023/12/amazon-cognito-user-pools-customize-access-tokens/
* https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-token-generation.html

In the AWS Console, this corresponds to:
* V1_0 Basic features. Your user pool sends a version 1 event to your Lambda function. You can customize identity tokens.
* V2_0 Basic features + access token customization - Recommended. Your user pool sends a version 2 event to your Lambda function. You can customize identity and access tokens.

Expected behavior: I can use the new **V2_0** event version.

### Actual Behavior

The TF provider sets the default version **V1_0**.

### Terraform Configuration Files

```
resource "aws_cognito_user_pool" "my_userpool" {
  name = var.userpool

  lambda_config {
    pre_token_generation = aws_lambda_function.pretokengeneration.arn
  }
  // ... other attributes removed for brevity
}
```

### Steps to Reproduce

1. Create `aws_cognito_user_pool` resource
2. Set `pre_token_generation` attribute

### References

Amazon Cognito introduced a new User pool trigger version **V2_0** for the pre token generation Lambda:
* https://aws.amazon.com/de/about-aws/whats-new/2023/12/amazon-cognito-user-pools-customize-access-tokens/
* https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-token-generation.html

### Would you like to implement a fix?

None

**Comment by SamuelCabralCruz** [comment]
In the meantime, I created a script that I execute as a post job once my infrastructure is deployed (terraform apply)

```bash
#!/usr/bin/env bash
set -euo pipefail

# TODO: temporary measure until https://github.com/hashicorp/terraform-provider-aws/issues/35007 is resolved

USER_POOL_NAME=<YOUR_USERPOOL_NAME>

USER_POOL_ID=$(aws cognito-idp list-user-pools --max-results 1 --query "UserPools[?Name=='${USER_POOL_NAME}'].Id" --output json | jq -r '.[0]')

CURRENT_CONFIG=$(aws cognito-idp describe-user-pool --user-pool-id "${USER_POOL_ID}" | jq -r '.UserPool')
UPDATED_CONFIG=$CURRENT_CONFIG
UPDATED_CONFIG=$(echo "${UPDATED_CONFIG}" | jq 'del(.Id)')
UPDATED_CONFIG=$(echo "${UPDATED_CONFIG}" | jq 'del(.Name)')
UPDATED_CONFIG=$(echo "${UPDATED_CONFIG}" | jq 'del(.Status)')
UPDATED_CONFIG=$(echo "${UPDATED_CONFIG}" | jq 'del(.Arn)')
UPDATED_CONFIG=$(echo "${UPDATED_CONFIG}" | jq 'del(.CreationDate)')
UPDATED_CONFIG=$(echo "${UPDATED_CONFIG}" | jq 'del(.LastModifiedDate)')
UPDATED_CONFIG=$(echo "${UPDATED_CONFIG}" | jq 'del(.CustomDomain)')
UPDATED_CONFIG=$(echo "${UPDATED_CONFIG}" | jq 'del(.Domain)')
UPDATED_CONFIG=$(echo "${UPDATED_CONFIG}" | jq 'del(.EmailConfigurationFailure)')
UPDATED_CONFIG=$(echo "${UPDATED_CONFIG}" | jq 'del(.SmsConfigurationFailure)')
UPDATED_CONFIG=$(echo "${UPDATED_CONFIG}" | jq 'del(.EstimatedNumberOfUsers)')
UPDATED_CONFIG=$(echo "${UPDATED_CONFIG}" | jq 'del(.SchemaAttributes)')
UPDATED_CONFIG=$(echo "${UPDATED_CONFIG}" | jq 'del(.UsernameAttributes)')
UPDATED_CONFIG=$(echo "${UPDATED_CONFIG}" | jq 'del(.UsernameConfiguration)')
UPDATED_CONFIG=$(echo "${UPDATED_CONFIG}" | jq 'del(.AdminCreateUserConfig)')
UPDATED_CONFIG=$(echo "${UPDATED_CONFIG}" | jq '.LambdaConfig.PreTokenGenerationConfig.LambdaVersion = "V2_0"')

aws cognito-idp update-user-pool --user-pool-id "${USER_POOL_ID}" --cli-input-json "${UPDATED_CONFIG}"
```

References:
- https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-updating.html
- https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserPool.html#API_UpdateUserPool_RequestSyntax

**Comment by justinretzolk** [comment]
Hey @lorchda 👋 Thank you for taking the time to raise this! As a heads up, we consider adding additional functionality to existing resources to be an enhancement, so I've adjusted the labels as such.

**Comment by AndresMorelos** [comment]
Hey @justinretzolk 👋🏾 I made the PR #35236 adding this enhancement, could you please take a look and give me feedback if needed?

**Comment by egalev** [comment]
> In the meantime, I created a script that I execute as a post job once my infrastructure is deployed (terraform apply)

Thanks for the reference @SamuelCabralCruz, I used a shorter version of what you posted, if it helps anyone. Also changed `PreTokenGenerationConfig` to support an existing legacy config of `PreTokenGeneration` (the `LambdaArn` attribute must match)
```bash
CURRENT_COGNITO_CONFIG=$(aws cognito-idp describe-user-pool --user-pool-id "${USER_POOL_ID}" | jq -r '.UserPool')
# Strip the config, as described in https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-updating.html#cognito-user-pool-updating-api-cli
STRIPPED_COGNITO_CONFIG=$(echo "${CURRENT_COGNITO_CONFIG}" | jq 'del(.Arn, .CreationDate, .CustomDomain, .Domain, .EmailConfigurationFailure, .EstimatedNumberOfUsers, .Id, .LastModifiedDate, .Name, .SchemaAttributes, .SmsConfigurationFailure, .Status, .AliasAttributes, .AdminCreateUserConfig.UnusedAccountValidityDays)')
UPDATED_COGNITO_CONFIG=$(echo "${STRIPPED_COGNITO_CONFIG}" | jq '.LambdaConfig.PreTokenGenerationConfig = {"LambdaVersion": "V2_0", "LambdaArn": .LambdaConfig.PreTokenGeneration}')

aws cognito-idp update-user-pool --user-pool-id "${USER_POOL_ID}" --cli-input-json "${UPDATED_COGNITO_CONFIG}"
```
