### ISSUE TITLE
[Docs]: Attribute conflicts are not mentioned in the documentation

### ISSUE THREAD

**Issue by hrider** [hashicorp/terraform-provider-aws#35019]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint#secrets_manager_access_role_arn

### Description

resource aws_dms_endpoint has conflicting attributes and are not mentioned in the documentation.

When [secrets_manager_access_role_arn] and [secrets_manager_arn] are coded, then server_name, port, username and password cannot be coded.

Also, [secrets_manager_access_role_arn] need to be created with trust of dms regional endpoint. Word regional is important.

### Would you like to implement a fix?

Yes

**Comment by acwwat** [comment]
The [DocDbSettings data type reference](https://docs.aws.amazon.com/dms/latest/APIReference/API_DocDbSettings.html) linked from the [CreateEndpoint API](https://docs.aws.amazon.com/dms/latest/APIReference/API_CreateEndpoint.html) has a note on this requirement which can be ported into the Terraform documentation.
