### ISSUE TITLE
how do I use an existing IAM role in QuickSight via terraform code.

### ISSUE THREAD

**Issue by ujjainwal770** [hashicorp/terraform-provider-aws#35028]
### Description

│ Error: waiting for QuickSight Data Source (618187721717/Secuirtydashboard-id) to update: unexpected state 'UPDATE_FAILED', wanted target 'UPDATE_SUCCESSFUL'. last error: ACCESS_DENIED: The QuickSight service role required to access your AWS resources has not been created yet.
│

### References

When I am assigning IAM role manually, It is working properly, but when we are applying via terraform getting above error.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @ujjainwal770 👋 Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. To maintain that, we ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). With that in mind, I'm going to close this issue.
