### ISSUE TITLE
[Enhancement]: Support new EKS access api.

### ISSUE THREAD

**Issue by gothrek22** [hashicorp/terraform-provider-aws#35027]
### Description

New API management of access that partially replaces aws-auth has been created. Relevant info here: https://github.com/aws/containers-roadmap/issues/185. This should allow moving access management to this provider via a resource like `aws_eks_access_entry` or something.

This also requires extending the aws_eks_cluster resource to support the new parameter `authenticationMode` which has the options of:
- CONFIG_MAP 
- API_AND_CONFIG_MAP
- API

And should probably warn that the migration to the API is one way.

### Affected Resource(s) and/or Data Source(s)

partially:
- aws_eks_cluster

### Potential Terraform Configuration

As the api requests via AWS CLI looks like so:
aws eks update-access-entry --cluster-name my-cluster \
   --principal-arn arn:aws:iam::012345678910:role/MyRole \
   --username my-other-username
   --kubernetes-groups my-other-group

I'd assume:
```terraform
resource aws_eks_access_entry example {
  iam_role = arn:aws:iam::012345678910:role/MyRole
  username = "my-other-username" (optional)
  kubernetes_groups = "my-other-group" (optional)
  type = "" (optional, options are: 
    EC2_LINUX
    EC2_WINDOWS
    FARGATE_LINUX
    STANDARD
  )
}
```

### References

https://github.com/aws/containers-roadmap/issues/185#issuecomment-1863025784

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@gothrek22 Thanks for raising this issue.
It has already been noticed in #34982. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
