### ISSUE TITLE
[Bug]: Combining ingress in aws_security_group with aws_security_group_rule to add inbound rules

### ISSUE THREAD

**Issue by balu-ce** [hashicorp/terraform-provider-aws#35039]
### Terraform Core Version

1.3.7

### AWS Provider Version

4.66

### Affected Resource(s)

1. aws_security_group
2. aws_security_group_rule

### Expected Behavior

I am using both ingress statement in aws_security_group and aws_security_group_rule for creating inbound rules. The expected behaviour is both rules will be applied 

### Actual Behavior

But it turns only inbound rules under ingress_statement is applied and rest of the security rules got deleted

### Terraform Configuration Files

terraform {
      required_providers {
        aws = {
          source  = "hashicorp/aws"
          version = "< 4.67.0"
        }
      }
    }
    provider "aws" {
    }

### Steps to Reproduce

1. Create a aws resource using aws_security_group with dynamic ingress for adding inbound cidrs
2. Create a aws_security_group_rule resource for adding some other static cidrs as inbound rules and attach the security group created at point 1

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
This is expected, as explained in [NOTE on Security Groups and Security Group Rules](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_security_group_ingress_rule).

**Comment by justinretzolk** [comment]
Hey @balu-ce 👋 Thank you for taking the time to raise this! As mentioned above, this is expected behavior, and can be avoided using the methods outlined in the document linked above. With that in mind, I'm going to close this issue out.
