### ISSUE TITLE
[Enhancement]: support kms_key_id in aws_codecommit_repository

### ISSUE THREAD

**Issue by visit1985** [hashicorp/terraform-provider-aws#35040]
### Description

Please support Customer Managed Key (CMK) in AWS CodeCommit.

### Affected Resource(s) and/or Data Source(s)

* aws_codecommit_repository

### Potential Terraform Configuration

```terraform
resource "aws_kms_key" "a" {}

resource "aws_codecommit_repository" "test" {
  repository_name = "MyTestRepository"
  description     = "This is the Sample App Repository"
  kms_key_id      = aws_kms_key.a.key_id
}
```

### References

https://aws.amazon.com/about-aws/whats-new/2023/12/customer-managed-key-support-aws-codecommit/
https://docs.aws.amazon.com/codecommit/latest/APIReference/API_CreateRepository.html

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Requires [AWS SDK for Go v1.49.8](https://github.com/aws/aws-sdk-go/releases/tag/v1.49.8): https://github.com/hashicorp/terraform-provider-aws/pull/35036.
