### ISSUE TITLE
[Bug]: aws_secretsmanager_secret_version does not detect changes done outside TF

### ISSUE THREAD

**Issue by mariusmanea-selfridges** [hashicorp/terraform-provider-aws#35042]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.31.0

### Affected Resource(s)

aws_secretsmanager_secret_version

### Expected Behavior

When changing the value of the secret in AWS Secret Manager portal, terraform should detect the change and attempt to change the value back to the correct one.

### Actual Behavior

Terraform plan shows no changes

### Relevant Error/Panic Output Snippet

```shell
No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

### Terraform Configuration Files

secret.tf

`variable "example" {
  default = {
    key1 = "value1"
    key2 = "value2"
  }

  type = map(string)
}

resource "aws_secretsmanager_secret" "item" {
  name                           = "test_secret"
  description                    = "Managed by Terraform"
}

resource "aws_secretsmanager_secret_version" "item" {
  secret_id      = aws_secretsmanager_secret.item.id
  secret_string  = jsonencode(var.example)
}`

### Steps to Reproduce

1. Create a AWS secrets manager secret called test_secret, using the code above
2. Go to the AWS portal into AWS Secrets Manager section, locate this secret, edit the secret value to something else, and save.
3. Run terraform plan or apply again after this change

Desired behavior: Terraform should detect the changed value, and attempt to change it back to the correct one.
Actual behavior: Instead, terraform doesn't detect any changes

### Would you like to implement a fix?

None

**Comment by mariusmanea-selfridges** [comment]
Quick update:
Retested using aws provider 5.33.0 and the issue still exists.

**Comment by varkey** [comment]
@mariusmanea-selfridges This is something I ran into yesterday and on investigating, it appears to be working as expected. There is a detailed explanation [here](https://discuss.hashicorp.com/t/confused-about-aws-secretsmanager-secret-version-resource-behaviour/52026/2) on why this is happening.

If you want the source of truth to be terraform, you also need to add the below to the `aws_secretsmanager_secret_version` resource.

```
version_stages = ["AWSCURRENT"]
```

**Comment by mariusmanea-selfridges** [comment]
Hi @varkey , you are correct! Thank you for your help.
I am closing the ticket.
