### ISSUE TITLE
[Enhancement]: Manage EKS cluster access

### ISSUE THREAD

**Issue by ChauAnhTuan** [hashicorp/terraform-provider-aws#35057]
### Description

AWS released a new function of the EKS cluster. That is "Cluster access." (https://aws.amazon.com/about-aws/whats-new/2023/12/amazon-eks-controls-iam-cluster-access-management)
 
Cluster access document: https://docs.aws.amazon.com/eks/latest/userguide/access-entries.html

### Affected Resource(s) and/or Data Source(s)

aws_eks_cluster

### Would you like to implement a fix?

None

**Comment by ponkio-o** [comment]
duplicate?
https://github.com/hashicorp/terraform-provider-aws/issues/34982
