### ISSUE TITLE
[Docs]: aws_quicksight_data_set reports physical_table_map.custom_sql.columns as optional, but is required

### ISSUE THREAD

**Issue by TCY16** [hashicorp/terraform-provider-aws#35052]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/quicksight_data_set#custom_sql

### Description

In the documentation the "columns" variable is required as optional, but when left unfilled it results in this error:

> Error: error creating QuickSight Data Set: ValidationException: 1 validation error detected: Value null at 'physicalTableMap.physical-table-id.member.customSql.columns' failed to satisfy constraint: Member must not be null

This should be changed.

### Would you like to implement a fix?

No

**Comment by rama280290** [comment]
I can update this document

**Comment by rama280290** [comment]
For a physical_table_map item to be valid, only one of custom_sql, relational_table, or s3_source should be configured.

Did we mentioned relational_table or s3_source when we left custom_sql since they have mentioned that one of 3 should be configured.

Kindly share the entire command used so that we can reproduce the issue please

**Comment by TCY16** [comment]
Thanks for your response!

The code I used looks like the following:
```
resource "aws_quicksight_data_set" "data_set_name" {
  data_set_id = "data-set-id"
  name        = "name"
  import_mode = "SPICE"

  physical_table_map {
    physical_table_map_id = "physical-table-id"
    custom_sql {
      data_source_arn = aws_quicksight_data_source.name.arn
      name            = "data-set"

      columns {
        name = "date"
        type = "DATETIME"
      }
      .
      .
      .
      columns {
        name = "number"
        type = "INTEGER"
      }
      sql_query = <<-EOT
        SELECT date, number
        FROM table
        EOT
    }
  }
```

Note that this issue is regarding **inside** the `custom_sql` clause, which can also be seen in the error message in the first comment.
The issue lies in that the linked documentation states that the columns (which are included in my code example above) are marked as optional, but if removed the error in the first comment is returned. This leads me to conclude that one or more column arguments **is** required

**Comment by rama280290** [comment]
Reproduced the issue. Working on creating PR for this one

**Comment by justinretzolk** [comment]
Hey @TCY16 👋 Thank you for taking the time to raise this! I went into a bit more detail in [this comment](https://github.com/hashicorp/terraform-provider-aws/pull/35918#issuecomment-2020843219) on the linked pull request, but the short version is that while the AWS API may require `columns` in certain circumstances, the API/SDK both list it as an optional field. The provider mirrors this behavior, and so the documentation matches the resource schema. With that in mind, I'm opting to keep the documentation as is for now, but would be more than happy to reconsider if there are changes on the AWS side that would make that appropriate.
