### ISSUE TITLE
[Enhancement]:  Read Step Functions Definition From S3

### ISSUE THREAD

**Issue by case-k-git** [hashicorp/terraform-provider-aws#35064]
### Description

 Read Step Functions Definition From S3. Cloud Formation support to read step functions definition from S3 but Terraform does not have that option. I make this request to support by Terraform.

```
DefinitionS3Location
The name of the S3 bucket where the state machine definition is stored. The state machine definition must be a JSON or YAML file.
```
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-definitions3location

### Affected Resource(s) and/or Data Source(s)

aws_sfn_state_machine

### References

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-definitions3location

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sfn_state_machine

### Would you like to implement a fix?

Yes

**Comment by Michagogo** [comment]
This can be accomplished with the `aws_s3_object` data source.

**Comment by case-k-git** [comment]
@Michagogo 
Thank you !  I have checked the document and looks `aws_s3_object` will be able to upload file to S3 bucket. Is this also support to read from S3 bucket?
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_object

**Comment by Michagogo** [comment]
That’s the resource. You want the data source.

**Comment by case-k-git** [comment]
@Michagogo  Thank you I confirmed thank you

**Comment by case-k-git** [comment]
Close this PR
