### ISSUE TITLE
[Bug]: aws_iot_ca_certificate registration_config role_arn type mismatch

### ISSUE THREAD

**Issue by miljanic** [hashicorp/terraform-provider-aws#35079]
### Terraform Core Version

1.6.6

### AWS Provider Version

5.30.0

### Affected Resource(s)

aws_iot_ca_certificate

### Expected Behavior

When I provide the role ARN (a string value) to the `registration_config.role_arn` I expect the `aws_iot_ca_certificate` resource to be created.

### Actual Behavior

I am receiving an error:
```
Inappropriate value for attribute "role_arn": a bool is required.
```

### Terraform Configuration Files

/

### Steps to Reproduce

Follow the example from the documentation and add the `registration_config` block to the `aws_iot_ca_certificate` resource.

```terraform
resource "aws_iam_role" "this" {...}
resource "tls_self_signed_cert" "ca" {...}
resource "tls_private_key" "ca" {...}
resource "tls_cert_request" "verification" {...}
resource "tls_private_key" "verification" {...}
resource "tls_locally_signed_cert" "verification" {...}
data "aws_iot_registration_code" "example" {}

resource "aws_iot_ca_certificate" "example" {
  active                       = true
  ca_certificate_pem           = tls_self_signed_cert.ca.cert_pem
  verification_certificate_pem = tls_locally_signed_cert.verification.cert_pem
  allow_auto_registration      = true
  
  registration_config {
    role_arn = aws_iam_role.this.arn
    template_body = "..."
  }
}
```

### References

I assume this issue is related to the wrong type on the `role_arn` field in the go code [here](https://github.com/hashicorp/terraform-provider-aws/blob/d890de308ad8f671b58cfb6a278a188753ad61f9/internal/service/iot/ca_certificate.go#L79)

```golang
"role_arn": {
	Type:         schema.TypeBool,
	Optional:     true,
	ValidateFunc: verify.ValidARN,
},
```
instead of 

```golang
"role_arn": {
	Type:         schema.TypeString,
	Optional:     true,
	ValidateFunc: verify.ValidARN,
},
```

### Would you like to implement a fix?

No

**Comment by WitoldSlawko** [comment]
Hi.

Bumping attention as well for this bug to be fixed: 
![image](https://github.com/hashicorp/terraform-provider-aws/assets/20817587/71954fbc-84de-4f4d-ad6d-6f6c25c403d1)

as currently it is blocking setting IoT JITP via Terraform :/

**Comment by WitoldSlawko** [comment]
Hi.

Bumping attention as well for this bug to be fixed:
![image](https://github.com/hashicorp/terraform-provider-aws/assets/20817587/f5953c28-5d41-4524-ae36-11db768c77b8)

as currently it is blocking setting IoT JITP via Terraform :/

**Comment by acwwat** [comment]
I'd like to help but I am having trouble finding information about the `registration_config` block. I can't find much in the documentation, and I don't see any options (so far) in the AWS Management Console either. While I can simply fix the data type, the best thing to do is to add a test case to validate a scenario with `registration_config` set.

Could someone please give an exact example of a Terraform config for the `registration_config` block and also explain what the role ARN is used for (what policy it should have for what service)? Thank you.

**Comment by acwwat** [comment]
I think I have what I need after reading up on provisioning template. Since the test case won't be provisioning any devices, I will set up a dummy IOT service role with no policy and a sample JITP template pulled from the AWS doc. They might not work in practice but should be sufficient for testing the Terraform resource.

**Comment by WitoldSlawko** [comment]
hi Anthony

thank you for quick response and setting up PR. You are exactly right on the spot. I also check your PR: https://github.com/hashicorp/terraform-provider-aws/pull/35234 , and for me it looks nice and it's good to go :)
