### ISSUE TITLE
[Docs]: Custom IAM Instance Profile - Wrong Value

### ISSUE THREAD

**Issue by Alvaro-Volker** [hashicorp/terraform-provider-aws#35086]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#rds-custom-for-sql-server

### Description

In RDS Custom for SQL Server shows property custom_iam_instance_profile with the value **AWSRDSCustomSQLServerInstanceRole** and should be **AWSRDSCustomSQLServerInstanceProfile**

### References

  custom_iam_instance_profile = "AWSRDSCustomSQLServerInstanceRole" # Instance profile is required for Custom for SQL Server. See: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/custom-setup-sqlserver.html#custom-setup-sqlserver.iam

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#rds-custom-for-sql-server

### Would you like to implement a fix?

None

**Comment by Michagogo** [comment]
It’s not uncommon for instance profiles to be named identically to the roles they’re associated with, that may be what’s happening here.
