### ISSUE TITLE
Migration of terraform one module to another with dependent resources, which should not impact existing resources deployed  

### ISSUE THREAD

**Issue by fanish3131** [hashicorp/terraform-provider-aws#35081]
### Description

Migration of terraform one module to another with dependent resources, which should not impact existing resources deployed  

We want know, what is best way to achieve this

### Would you like to implement a fix?

None

**Comment by ericrichtert** [comment]
You can use _terraform state mv_ to move your objects in the state file

**Comment by justinretzolk** [comment]
Hey @fanish3131 👋 Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. To maintain that, we ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). With that in mind, I'm going to close this issue.
