### ISSUE TITLE
[Enhancement]: Support for Dynamodb advanced features in AWS backups

### ISSUE THREAD

**Issue by CasaSky** [hashicorp/terraform-provider-aws#35080]
### Description

Terraform fails while creating a backup plan for dynamodb resource type:

`Error: expected advanced_backup_setting.0.resource_type to be one of ["EC2"], got DynamoDB
`

### Affected Resource(s) and/or Data Source(s)

aws_backup_plan

### Potential Terraform Configuration

```terraform
resource "aws_backup_plan" "example" {
  name = "tf_example_backup_plan"

  rule {
    rule_name         = "tf_example_backup_rule"
    target_vault_name = aws_backup_vault.test.name
    schedule          = "cron(0 12 * * ? *)"

    lifecycle {
      delete_after = 14
    }
  }

  advanced_backup_setting {
    backup_options = {
      WindowsVSS = "disabled"
    }
    resource_type = "DynamoDB"
  }
}
```

### References

https://docs.aws.amazon.com/aws-backup/latest/devguide/advanced-ddb-backup.html
https://docs.aws.amazon.com/aws-backup/latest/devguide/restoring-dynamodb.html

### Would you like to implement a fix?

None

**Comment by CasaSky** [comment]
Also is there a possibility to restore a dynamodb table using aws backup recovery point id? In AWS console this is possible via Restore Button

**Comment by aristosvo** [comment]
Hi @CasaSky! You don't need advanced settings on the `aws_backup_plan` for DynamoDB.

Enabling advanced settings should be done by modifying the [regional settings as documented](https://docs.aws.amazon.com/aws-backup/latest/devguide/advanced-ddb-backup.html#advanced-ddb-backup-enable-cli). This is done via [`aws_backup_region_settings`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_region_settings).

**Comment by CasaSky** [comment]
Understood. But what about restoring a backup into a table via terraform? In rds Ressource this is possible via snapshot id. Is there a similar way in terraform dynamodb?

**Comment by aristosvo** [comment]
Thanks, got it. There is already an issue (and an PR) regarding this feature, see #29883 and #32493.

Please add your 👍🏽 on that issue to prioritize it, I think this issue can then be closed.

**Comment by CasaSky** [comment]
muchas gracias. I think this issue can be closed now :)
