### ISSUE TITLE
[Bug] [aws_emr_cluster] hadoop_jar_step requires optional attributes "main_class" and "properties"

### ISSUE THREAD

**Issue by hongbo-miao** [hashicorp/terraform-provider-aws#35090]
### Terraform Core Version

1.6.2

### AWS Provider Version

5.23.1

### Affected Resource(s)

- aws_emr_cluster

### Expected Behavior

Based on https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emr_cluster

`main_class` and `properties` are optional inside `hadoop_jar_step`.

### Actual Behavior

Failed to deploy with error saying `main_class` and `properties` are required.

### Relevant Error/Panic Output Snippet

```shell
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Incorrect attribute value type
│
│   on modules/horizon_amazon_emr_cluster/main.tf line 47, in resource "aws_emr_cluster" "horizon_amazon_emr_cluster":
│   47:   step = var.steps
│     ├────────────────
│     │ var.steps is list of object with 1 element
│
│ Inappropriate value for attribute "step": incorrect list element type: attribute "hadoop_jar_step": element 0: attributes "main_class" and
│ "properties" are required.
```

### Terraform Configuration Files

```hcl
resource "aws_emr_cluster" "hm_amazon_emr_cluster" {
  # ...
  step = [
    {
      name              = "Validate Python Version"
      action_on_failure = "CONTINUE"
      hadoop_jar_step = [
        {
          jar  = "command-runner.jar"
          args = ["spark-submit", "--deploy-mode", "client", "s3://hongbomiao-bucket/amazon-emr/hm-amazon-emr-cluster/validate_python_version.py"]
        }
      ]
    }
  ]
}
```

### Steps to Reproduce

- `terraform apply`

### Workaround Solution

Add `main_class` and `properties`.

```hcl
resource "aws_emr_cluster" "hm_amazon_emr_cluster" {
  # ...
  step = [
    {
      name              = "Validate Python Version"
      action_on_failure = "CONTINUE"
      hadoop_jar_step = [
        {
          jar  = "command-runner.jar"
          args = ["spark-submit", "--deploy-mode", "client", "s3://hongbomiao-bucket/amazon-emr/hm-amazon-emr-cluster/validate_python_version.py"]
          main_class = ""
          properties = {}
        }
      ]
    }
  ]
}
```
### References

There was an ticket opened at https://github.com/hashicorp/terraform-provider-aws/issues/20911
But the issue is still there today.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @hongbo-miao 👋 Thank you for taking the time to raise this! It looks like you're hitting a bit of a niche issue related to the `steps` argument being processed in attributes-as-blocks mode. In this mode, when you define a constant list of objects, all [default values are overridden](https://developer.hashicorp.com/terraform/language/attr-as-blocks#arbitrary-expressions-with-argument-syntax), so all arguments must be explicitly assigned a value, even if it's `null`.

Using block syntax, this behavior can be avoided. The following refactoring of your example passed a `terraform validate`:

```terraform
resource "aws_emr_cluster" "hm_amazon_emr_cluster" {
  # arguments omitted for brevity
  step {
    name              = "Validate Python Version"
    action_on_failure = "CONTINUE"

    hadoop_jar_step {
      jar  = "command-runner.jar"
      args = ["spark-submit", "--deploy-mode", "client", "s3://hongbomiao-bucket/amazon-emr/hm-amazon-emr-cluster/validate_python_version.py"]
    }
  }
}
```

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.

**Comment by hongbo-miao** [comment]
Sorry I missed previous one @justinretzolk , I will test and report back!

**Comment by hongbo-miao** [comment]
Hi @justinretzolk ah, I remembered I was using this to install custom Python 3.11 to EMR, but stuck at https://stackoverflow.com/questions/77754223/failed-to-access-script-runner-jar-in-amazon-emr-cluster

So we gave up on that direction. If have chance to test again in future, I will report back, thanks for helping!
