### ISSUE TITLE
Issue while created RHEL8 machine with Custom Disk size.

### ISSUE THREAD

**Issue by g2r1990** [hashicorp/terraform-provider-aws#35104]
### Description

"Hello,
I've encountered a scenario where Terraform code is effectively handling the RHEL machine build in VMware vSphere, and it works seamlessly for the RHEL 7 template. However, when attempting to create a RHEL 8 machine using the RHEL 8 template.

I have noticed that the custom size I specify for the root, /tmp, or any other mount is not reflected in the created disk. Instead, it defaults to the default disk allocation size.

Did anyone has encounter with similar issue and any insights/solutions to address this discrepancy would be greatly appreciated.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @g2r1990 👋 Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. To maintain that, we ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). With that in mind, I'm going to close this issue.
