### ISSUE TITLE
[Enhancement]: SageMaker Studio now supports local mode and Docker

### ISSUE THREAD

**Issue by deepakbshetty** [hashicorp/terraform-provider-aws#35115]
### Description

Studio users can now run SageMaker processing, training, inference and batch transform jobs locally on their Studio IDE instance. Users can also build and test SageMaker compatible Docker images locally in Studio IDEs. [link](https://aws.amazon.com/about-aws/whats-new/2023/12/sagemaker-studio-local-mode-docker/)

Usage guide - [Link](https://docs.aws.amazon.com/sagemaker/latest/dg/studio-updated-local.html)

@DrFaust92 

### Affected Resource(s) and/or Data Source(s)

aws_sagemaker_domain

### Potential Terraform Configuration

```terraform
resource "aws_sagemaker_domain" "example" {
  domain_name = "example"
  auth_mode   = "IAM"
  vpc_id      = aws_vpc.example.id
  subnet_ids  = [aws_subnet.example.id]

  default_user_settings {
    execution_role  = aws_iam_role.example.arn
    studio_web_portal = "ENABLED"
    kernel_gateway_app_settings {
      custom_image {
        app_image_config_name = aws_sagemaker_app_image_config.example.app_image_config_name
        image_name            = aws_sagemaker_image_version.example.image_name
      }
    }
  }

    domain_settings {
      execution_role_identity_config = "USER_PROFILE_NAME|DISABLED"
      docker_settings {
        enable_docker_access      = "ENABLED|DISABLED"
        vpc_only_trusted_accounts = ["123456789012","111111111111"]
      }
    }  
}
```

### References

Code Reference: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/sagemaker/domain.go#L868

API Reference:
https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateDomain.html
https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_UpdateDomain.html

EnableDockerAccess
Indicates whether the domain can access Docker.
Type: String
Valid Values: ENABLED | DISABLED

VpcOnlyTrustedAccounts
The list of AWS accounts that are trusted when the domain is created in VPC-only mode.
Type: Array of strings
Length Constraints: Fixed length of 12.
Pattern: ^\d+$

### Would you like to implement a fix?

No

**Comment by DrFaust92** [comment]
Hi, ill check this out. currently working on another sagemaker studio PR so should be fine to do within this context

**Comment by deepakbshetty** [comment]
Hi @DrFaust92 👋 , Wondering if you had a chance to look at this. Appreciate you are busy with other priorities.

Thanks in advance,
Deepak

**Comment by rileyhun** [comment]
@deepakbshetty Any progress on this?

**Comment by deepakbshetty** [comment]
Hi @rileyhun, PR pending with provider maintainers.
