### ISSUE TITLE
[Docs]: AWS ACL grant permission - missing valid values list

### ISSUE THREAD

**Issue by mbalc** [hashicorp/terraform-provider-aws#35139]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_acl#grant

### Description

the example included only lists "READ" and "READ_ACP" as possible values for the grant permission here in the link

I have to look up AWS docs to see valid values for this - https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#permissions

idk, at least including the link there would be useful

### Would you like to implement a fix?

None

**Comment by mbalc** [comment]
bonus question here - is it possible to specify a list of permissions? or you need to clone the grant, for example, a combination of "READ" + "READ_ACL"?

**Comment by acwwat** [comment]
Thanks. I've added the list of valid values and a link to the documentation for additional details as you suggested.

**Comment by acwwat** [comment]
> bonus question here, that the docs don't answer - is it possible to specify a list of permissions, when you need sth like a combo of "READ" + "READ_ACL"? Or do you have to hack - specifying the same grantee for each separate permission?

No, because permission is a string value. You will unfortunately need a new `grant` block for each permission to be set.
