### ISSUE TITLE
[Enhancement]: support `type = "ORGANIZATION_UNUSED_ACCESS"` for `aws_accessanalyzer_analyzer` resources

### ISSUE THREAD

**Issue by tinder-tder** [hashicorp/terraform-provider-aws#35145]
### Description

AWS announced organizational unused access support
https://aws.amazon.com/blogs/security/iam-access-analyzer-simplifies-inspection-of-unused-access-in-your-organization/

And currently the provider only supports types ACCOUNT or ORGANIZATION.  The new type is `ORGANIZATION_UNUSED_ACCESS`

### Affected Resource(s) and/or Data Source(s)

* aws_accessanalyzer_analyzer

### Potential Terraform Configuration

```terraform
resource "aws_accessanalyzer_analyzer" "access_analyzer" {

  analyzer_name = "foo"
  type          = "ORGANIZATION_UNUSED_ACCESS"
}
```

### References

https://aws.amazon.com/blogs/security/iam-access-analyzer-simplifies-inspection-of-unused-access-in-your-organization/
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/accessanalyzer/create-analyzer.html

### Would you like to implement a fix?

No

**Comment by alexeiser** [comment]
> According to the AWS SDK for Go v2 [accessanalyzer service CHANGELOG](https://github.com/aws/aws-sdk-go-v2/blob/main/service/accessanalyzer/CHANGELOG.md), support was added in v1.24.0 (2023-11-27), which is pulled into the AWS Terraform Provider v5.27.0.
> 
> Please check whether you are using v5.27.0 or later.

Might just. need a documentation update then as the docs say only ORGANIZATION and ACCOUNT are supported types.
https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/accessanalyzer_analyzer.html.markdown?plain=1#L47

**Comment by acwwat** [comment]
PR submitted. While working on this, I noticed that the [CreateAnalyzer API](https://docs.aws.amazon.com/access-analyzer/latest/APIReference/API_CreateAnalyzer.html#API_CreateAnalyzer_RequestSyntax) now supports a new (optional) attribute called `configuration` which provides additional configuration for the unused access analyzer. A new feature request should be opened to track support for this new attribute.
