### ISSUE TITLE
[Enhancement]: Support for S3 Object Lock on existing buckets

### ISSUE THREAD

**Issue by jkdv** [hashicorp/terraform-provider-aws#35153]
### Description

AWS S3 now supports enabling Object Lock on existing S3 buckets. I would like Terraform to support this feature.

https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-s3-enabling-object-lock-buckets/

### Affected Resource(s) and/or Data Source(s)

* aws_s3_bucket

### References

https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-s3-enabling-object-lock-buckets/

### Would you like to implement a fix?

None

**Comment by Siddarthyuvaraj** [comment]
I will work on this and create a PR later

**Comment by stumyp** [comment]
for what it worth: it is possible to enable object lock configuration on existing bucket via API now:

```bash
11:50 $ aws s3api get-object-lock-configuration --bucket througaway-bucket-q3o4aya3mfi-owkjicgy

An error occurred (ObjectLockConfigurationNotFoundError) when calling the GetObjectLockConfiguration operation: Object Lock configuration does not exist for this bucket

11:50 $ aws s3api put-object-lock-configuration --bucket througaway-bucket-q3o4aya3mfi-owkjicgy   --object-lock-configuration='{ "ObjectLockEnabled": "Enabled", "Rule": { "DefaultRetention": { "Mode": "COMPLIANCE", "Days": 1 }}}'

11:51 $ aws s3api get-object-lock-configuration --bucket througaway-bucket-q3o4aya3mfi-owkjicgy
{
    "ObjectLockConfiguration": {
        "ObjectLockEnabled": "Enabled",
        "Rule": {
            "DefaultRetention": {
                "Mode": "COMPLIANCE",
                "Days": 1
            }
        }
    }
}
```

Current [provider documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_object_lock_configuration#object-lock-configuration-for-an-existing-bucket) requires contacting AWS support to obtain a token. 
As you can see from the example above, token is no longer required.

**Comment by stumyp** [comment]
ok, I've just tested it and simply adding a `aws_s3_bucket_object_lock_configuration` resource enables object lock on the bucket.
Although adding `object_lock_enabled = true` to the `aws_s3_bucket` itself forces replacement.

**Comment by ayoshida5** [comment]
Hello.

I have read that `aws_s3_bucket_object_lock_configuration` is now able to lock objects for existing buckets in Provider version 5.33.0 (Latest).

- [aws_s3_bucket_object_lock_configuration | Resources | hashicorp/aws | Terraform | Terraform Registry](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_object_lock_configuration)
  - `This resource can be used enable Object Lock for new and existing buckets.`

On the other hand, the documentation for Provider version 5.32.1 reads

- [aws_s3_bucket_object_lock_configuration | Resources | hashicorp/aws | Terraform | Terraform Registry](https://registry.terraform.io/providers/hashicorp/aws/5.32.1/docs/resources/s3_bucket_object_lock_configuration)
  - `If you want to enable Object Lock for an existing bucket, contact AWS Support`.

I thought that only Provider version 5.33.0 (Latest) is supported, OK?

Actually, we have confirmed the operation with the following Provider versions,
I have confirmed that terraform apply completes successfully for **all Provider versions**.
And the AWS Management Console displayed "object lock enabled",
Is there any need to increase the Provider version to 5.33.0 (Latest)?

- (OK) Provider version 5.33.0 (Latest)
- (OK) Provider version 5.32.1
- (OK) Provider version 4.67.0

**Comment by johnsonaj** [comment]
@ayoshida5 thank you for checking this functionality. The change for this was on the AWS side so previous version of the provider should work without updating to `v5.33.0` or later.
