### ISSUE TITLE
[Bug]: Running terraform destory doesn't remove aws_kms_alias

### ISSUE THREAD

**Issue by gmisura** [hashicorp/terraform-provider-aws#35161]
### Terraform Core Version

1.6.3

### AWS Provider Version

5.31.0

### Affected Resource(s)

I've created an aws_kms_key and then an aws_kms_alias successfully.

```
resource "aws_kms_key" "my-kms-key" {
  description = "KMS CMK Key for encrypting EKS and EBS"
  key_usage = "ENCRYPT_DECRYPT"
  customer_master_key_spec = "SYMMETRIC_DEFAULT"
  multi_region = true
}

resource "aws_kms_alias" "my-kms-key-alias" {
  target_key_id = aws_kms_key.my-kms-key.id
  name = "alias/my-kms-key"
}
```

I then do a destroy of my plan.

The aws_kms_key is set to "pending deletion" but the alias remains.

I then run `terraform apply` to (re)create the kms key and alias, but I get a failure that the alias already exists (on the pending deletion key).

│ Error: creating KMS Alias (alias/my-kms-key): AlreadyExistsException: An alias with the name arn:aws:kms:west-1:xxxxxxx:alias/my-kms-key-alias already exists

### Expected Behavior

I'd expect the destory to remove the kms key alias.

I had to do this manually via the AWS CLI.

`aws kms delete-alias --alias-name alias/my-kms-key`

### Actual Behavior

The destory logs show the key (and key policy) destruction, but nothing about the key alias:

```
module.kms-cmk.aws_kms_key.my-kms-key: Refreshing state... [id=mrk-xxxxxxxxxxxxxxx]
module.kms-cmk.aws_kms_key_policy.my-kms-key-policy: Refreshing state... [id=mrk-xxxxxxxxxxxxxxx]
  # module.kms-cmk.aws_kms_key.my-kms-key will be destroyed
  # module.kms-cmk.aws_kms_key_policy.my-kms-key-policy will be destroyed
module.kms-cmk.aws_kms_key_policy.my-kms-key-policy: Destroying... [id=mrk-xxxxxxxxxxxxxxx]
module.kms-cmk.aws_kms_key_policy.my-kms-key-policy: Destruction complete after 5s
module.kms-cmk.aws_kms_key.my-kms-key: Destroying... [id=mrk-xxxxxxxxxxxxxxx]
module.kms-cmk.aws_kms_key.my-kms-key: Destruction complete after 0s
```

### Relevant Error/Panic Output Snippet

```shell
│ Error: creating KMS Alias (alias/my-kms-key): AlreadyExistsException: An alias with the name arn:aws:kms:west-1:xxxxxxx:alias/my-kms-key-alias already exists
```

### Terraform Configuration Files

Pretty sure the only relevant configs are the required_providers which i listed above as the aws hashicorp provider at 5.31.0

### Steps to Reproduce

```
terraform apply
terraform destroy
terraform apply
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @gmisura 👋 Thank you for taking the time to raise this! If you wait a bit between the destruction and recreation, does the issue persist? I'm curious if this may be an [eventual consistency](https://docs.aws.amazon.com/kms/latest/developerguide/programming-eventual-consistency.html) thing.

**Comment by justinretzolk** [comment]
Hey @gmisura 👋 I wanted to check in here and see if you were able to test the theory of this being an eventual consistency issue. If waiting between the destroy and next apply for recreation clears up the issue, I'm not certain it's something we'd be able to address with the provider.

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
