### ISSUE TITLE
[Bug]: CodeBuild Project Prompts for Location When Using CodeCommit as Source

### ISSUE THREAD

**Issue by network-charles** [hashicorp/terraform-provider-aws#35171]
### Terraform Core Version

Terraform v1.6.6

### AWS Provider Version

5.31.0

### Affected Resource(s)

aws_codebuild_project

### Expected Behavior

Build a Codebuild project for Codecommit source without requiring a location.

### Actual Behavior

Fails to create the resource.

### Relevant Error/Panic Output Snippet

```shell
Error: creating CodeBuild project: InvalidInputException: Project source location is required
```

### Terraform Configuration Files

https://github.com/network-charles/AWS-Dev-Associate/blob/main/Lab%202/compute.tf

### Steps to Reproduce

source {
    type = "CODECOMMIT"
    location = aws_codecommit_repository.test.clone_url_http
  }
  
For the source argument in the codebuild project resource, comment the "location." 

The last instruction is specified as a comment in the null resource.

Lastly, do a `terraform apply -auto-approve` for the Lab 2 folder.

### Important Factoids

I use Ubuntu 20.04.6 LTS

### Would you like to implement a fix?

No

**Comment by acwwat** [comment]
According to the [CodeBuild API reference](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ProjectSource.html), `location` is required for source code in a CodeCommit repository and it should be the HTTPS clone URL of the repository. Even in the UI, you would select the CodeCommit repo, which likely just gets resolved to the HTTPS clone URL under the cover.

Is there a reason why you believe the source location is not required?

**Comment by network-charles** [comment]
@acwwat, thank you for helping me identify this. I had gotten confused at the part that said “Required: No”
When I reread it now, I saw that it was specified that “For all of the other types, you must specify Location.”
