### ISSUE TITLE
[Bug]: ecr/lifecycle_policy: no changes shown for tagPatternList

### ISSUE THREAD

**Issue by skurtEnd** [hashicorp/terraform-provider-aws#35184]
### Terraform Core Version

v1.5.5

### AWS Provider Version

~> 5.14.0

### Affected Resource(s)

aws_ecr_lifecycle_policy

### Expected Behavior

tagPatternList is a list parameter. When TF plan is ran, it should show the diffs in the plan.

### Actual Behavior

It doesn't show any diffs in the plan when tagPatternList is the only attribute changed therefore, tagPatternList cannot be updated.

![Screenshot 2024-01-08 at 12 08 59](https://github.com/hashicorp/terraform-provider-aws/assets/119338393/f4c28a00-1475-4a4d-8621-260aa42febef)

It only shows the diff when another attribute has been changed - for instance: countNumber changed from 120 to 90

![Screenshot 2024-01-08 at 12 14 18](https://github.com/hashicorp/terraform-provider-aws/assets/119338393/80443207-9f47-455b-8867-ff97cd94a091)

### Terraform Configuration Files

N/A

### Steps to Reproduce

Add aws_ecr_lifecycle_policy with tagPatternList
Run terraform apply 
Add a new element to the tagPatternList attribute
Run plan/apply

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
One can use the following resource definition to troubleshoot this issue:

```
resource "aws_ecr_repository" "foo" {
  name = "bar"
}

resource "aws_ecr_lifecycle_policy" "foopolicy" {
  repository = aws_ecr_repository.foo.name

  policy = jsonencode(
    {
      rules = [
        {
          rulePriority = 1
          description  = "Images to be removed after 120 days"
          selection = {
            tagStatus = "tagged"
            tagPatternList = [
              "*-TEST",
              "*-TEST2"
            ]
            countType   = "sinceImagePushed"
            countUnit   = "days"
            countNumber = 120
          },
          "action" : {
            "type" : "expire"
          }
        }
      ]
    }
  )
}
```

Using this as the baseline, I can confirm that changing `tagPatternList` doesn't cause a change, but changing other attributes such as `countNumber` does. Looking at the code, it does some form of normalization with the policy document for comparison to determine of there are differences. What I can see from the debug log is that `tagPatternList` is NOT in the normalized (or canonical) version of the policy JSON, which explains the observed behavior. Perhaps someone can take a deeper look at the `equivalentLifecyclePolicyJSON` to see if the normalization is correct.

Here are the lines of interest for the debug log when I change `countNumber` to 120 to see what the diff looks like:
```
2024-01-09T13:52:41.632-0500 [DEBUG] provider.terraform-provider-aws_v5.31.0_x5.exe: [DEBUG] Canonical Lifecycle Policy JSONs are not equal.
2024-01-09T13:52:41.632-0500 [DEBUG] provider.terraform-provider-aws_v5.31.0_x5.exe: First: {"rules":[{"rulePriority":1,"description":"Images to be removed after 120 days","selection":{"tagStatus":"tagged","countType":"sinceImagePushed","countUnit":"days","countNumber":120},"action":{}}]}
2024-01-09T13:52:41.632-0500 [DEBUG] provider.terraform-provider-aws_v5.31.0_x5.exe: Second: {"rules":[{"rulePriority":1,"description":"Images to be removed after 120 days","selection":{"tagStatus":"tagged","countType":"sinceImagePushed","countUnit":"days","countNumber":121},"action":{}}]}
```

**Comment by acwwat** [comment]
I believe the cause is that the model for `selection` does not include `tagPatternList`:

https://github.com/hashicorp/terraform-provider-aws/blob/43a9d8d41e2914d9e99cbc3363d83378870459d8/internal/service/ecr/lifecycle_policy.go#L190-L196
