### ISSUE TITLE
[Bug]: aws_iot_indexing_configuration does not support reserved shadows

### ISSUE THREAD

**Issue by PeterBurner** [hashicorp/terraform-provider-aws#35201]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.31.0

### Affected Resource(s)

* `aws_iot_indexing_configuration`

### Expected Behavior

Resource should allow enabling indexing of reserved shadows like `$package`.
Shadow name validation should comply with [AWS specification](https://docs.aws.amazon.com/iot/latest/apireference/API_IndexingFilter.html) (`[$a-zA-Z0-9:_-]+`).

### Actual Behavior

Provider throws a validation error.

### Relevant Error/Panic Output Snippet

```shell
Error: invalid value for `thing_indexing_configuration.0.filter.0.named_shadow_names.0` (must contain only alphanumeric characters, underscores, colons, and hyphens)
```

### Terraform Configuration Files

```terraform
resource "aws_iot_indexing_configuration" "this" {
  thing_indexing_configuration {
    thing_indexing_mode              = "REGISTRY"
    thing_connectivity_indexing_mode = "STATUS"
    device_defender_indexing_mode    = "VIOLATIONS"
    named_shadow_indexing_mode       = "ON"

    filter {
      named_shadow_names = ["$package"] # this is broken
    }
  }

  thing_group_indexing_configuration {
    thing_group_indexing_mode = "OFF"
  }
}
```

### Steps to Reproduce

Create the resource above and apply.

### References

* https://docs.aws.amazon.com/iot/latest/apireference/API_IndexingFilter.html
* https://github.com/hashicorp/terraform-provider-aws/blob/abfaed54ab5f0989481785b5dc87f52d27b5c261/internal/service/iot/indexing_configuration.go#L129C1-L129C158
* https://github.com/hashicorp/terraform-provider-aws/pull/26862

### Would you like to implement a fix?

No

**Comment by acwwat** [comment]
The resource has its own validation and the regex needs updating to support `$`:

https://github.com/hashicorp/terraform-provider-aws/blob/6c6683a868132b99f392776f1e1a6f66eb525171/internal/service/iot/indexing_configuration.go#L114-L135
