### ISSUE TITLE
[Enhancement]: Support new `configuration` attribute for `aws_accessanalyzer_analyzer`

### ISSUE THREAD

**Issue by acwwat** [hashicorp/terraform-provider-aws#35205]
### Description

According to the [CreateAnalyzer API](https://docs.aws.amazon.com/access-analyzer/latest/APIReference/API_CreateAnalyzer.html#API_CreateAnalyzer_RequestSyntax), a new attributed `configuration` has now been added to provide the ability to provide settings to the unused access analyzer. The `aws_accessanalyzer_analyzer` resource should thus be updated to support this new attribute, probably as a configuration block.

### Affected Resource(s) and/or Data Source(s)

* aws_accessanalyzer_analyzer

### Potential Terraform Configuration

```terraform
resource "aws_accessanalyzer_analyzer" "example" {
  analyzer_name = "example"
  type          = "ACCOUNT_UNUSED_ACCESS"
  configuration {
    unused_access {
      unused_access_age = 180
    }
  }
}
```

### References

https://docs.aws.amazon.com/access-analyzer/latest/APIReference/API_CreateAnalyzer.html

### Would you like to implement a fix?

None

**Comment by DanielRieske** [comment]
Hi @acwwat 👋, I'd be happy to pick this issue up, I'll add the PR shortly.
