### ISSUE TITLE
[Enhancement]: Add logging configuration for the event bridge pipe

### ISSUE THREAD

**Issue by srilavanyapaleti** [hashicorp/terraform-provider-aws#35216]
### Description

Logging is [supported](https://aws.amazon.com/blogs/compute/introducing-logging-support-for-amazon-eventbridge-pipes/) for Event bridge pipes since Nov, 2023. How ever, in the current terraform event bridge pipe configuration, the logging is not supported. This enhancement request should add the logging configuration support so that the logging settings are configurable via terraform

### Would you like to implement a fix?

No

**Comment by srilavanyapaleti** [comment]
Hello! 
I am planning to work on this issue.Just a heads up, New to Golang. I am going through the contribution guide and setting up the environment. Let me know if there is something i should know.

**Comment by andreswebs** [comment]
Hello, I'm interested in working on this feature.

**Comment by Wool3673** [comment]
Has this issue been resolved else where? The latest docs suggest it has been, but it doesn't seem to work.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pipes_pipe#cloudwatch_logs_parameters

Sample error:
Error: updating Amazon EventBridge Pipes Pipe (foo): operation error Pipes: UpdatePipe, https response error StatusCode: 400, RequestID: foo, ValidationException: {"ValidationErrorFields":[{"Name":"CloudWatchLogsParameters","Message":"Invalid target parameter provided for target."}]}

**Comment by andreswebs** [comment]
Actually no, it's still pending. The docs you linked refer to using CloudWatch logs as a target. This issue is to enable logging from the pipe, but not as a target.
