### ISSUE TITLE
[Enhancement]: support logging configuration for Lambda

### ISSUE THREAD

**Issue by sterliakov** [hashicorp/terraform-provider-aws#35224]
### Description

Since Nov. 2023, it is possible to alter default log group name and several other parameters. Would be great to support it via Terraform.

In AWS Console, it is configurable in "Configuration > Monitoring and operations tools > Logging configuration" section on the Lambda page. It is `--logging-config` in CLI

### Affected Resource(s) and/or Data Source(s)

* aws_lambda_function

### Potential Terraform Configuration

```terraform
resource "aws_lambda_function" "test" {
    ...
    logging_config {
        log_group_name = "my/custom/log"
        log_format = "text"
    }
}
```

### References

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/create-function.html

https://aws.amazon.com/about-aws/whats-new/2023/11/aws-lambda-controls-search-filter-aggregate-lambda-function-logs/

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@sterliakov Thanks for raising this issue.
It has already been noticed in #34455. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
