### ISSUE TITLE
aws_imagebuilder_components (data source): Add support for owner of "ThirdParty"

### ISSUE THREAD

**Issue by gramsa49** [hashicorp/terraform-provider-aws#35229]
### Description

The data source aws_imagebuilder_components has a parameter, owner, which supports the following values:
Self, Shared and Amazon

The API supports a fourth value:
ThirdParty

This enhancement request is to add support to the data source where owner is 'ThirdParty'

### Affected Resource(s) and/or Data Source(s)

* aws_imagebuilder_components

### Potential Terraform Configuration

```terraform
data "aws_imagebuilder_components" "managed_components" {
  owner     = "ThirdParty"
  filter {
    name   = "name"
    values = ["cis-benchmark-level-1-windows-2019"]
  }
}
```

### References

https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_ListComponents.html#imagebuilder-ListComponents-request-owner

### Would you like to implement a fix?

None

**Comment by cbhoffman** [comment]
I would like to work on this @justinretzolk
