### ISSUE TITLE
[Enhancement]: AWS Network Firewall TLS Inspection Configuration

### ISSUE THREAD

**Issue by ehlaumarc** [hashicorp/terraform-provider-aws#35235]
### Description

I understand that terraform have not add the resource for aws network-firewall - tls inspection configuration, therefore my team and I wanted to create the firewall policy beforehand and import into terraform state for better management. But unfortunely, the backend API will eventually overwrite the current setting and we end up with the same error that we encounterred before.

![image](https://github.com/hashicorp/terraform-provider-aws/assets/71658481/7de6572a-c54c-4802-92cd-c57719f641a4)

Can we ask whether when will terraform has the resource for AWS Network Firewall on TLS inspection configuration?

### Affected Resource(s) and/or Data Source(s)

*aws_network_firewall_policy

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@ehlaumarc Thanks for raising this issue.
It has already been noticed in #31154. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
