### ISSUE TITLE
[Enhancement]: Add `datadog` as a supported destination in the `kinesis_firehose_delivery_stream` resource 

### ISSUE THREAD

**Issue by ktmq** [hashicorp/terraform-provider-aws#35274]
### Description

Add `datadog` as a supported `destination` in the AWS terraform provider for the `kinesis_firehose_delivery_stream` resource [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream#destination). 

This functionality is already supported in the AWS Console UI: **Amazon Kinesis Data Firehose > Data Firehose >
Create delivery stream**. [Link](https://us-east-1.console.aws.amazon.com/firehose/home?region=us-east-1#/create/kds/datadog)

Currently when setting `datadog` as the destination, it results in this error:
```
│ Error: expected destination to be one of ["elasticsearch" "extended_s3" "http_endpoint" "opensearch" "opensearchserverless" "redshift" "splunk"], got datadog
│
│   with aws_kinesis_firehose_delivery_stream.test_stream,
│   on main.tf line 161, in resource "aws_kinesis_firehose_delivery_stream" "test_stream":
│  161:   destination = "datadog"
```

Terraform config used to produce the above error:
```
resource "aws_kinesis_firehose_delivery_stream" "test_stream" {
  name        = "terraform-kinesis-firehose-test-stream"
  destination = "datadog"
}
```

### Affected Resource(s) and/or Data Source(s)

* [kinesis_firehose_delivery_stream](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream)

### Potential Terraform Configuration

```terraform
resource "aws_kinesis_firehose_delivery_stream" "test_stream" {
  name        = "terraform-kinesis-firehose-test-stream"
  destination = "datadog"

  datadog_configuration {
    datadog_url        = "https://awsmetrics-intake.datadoghq.com/v1/input"  // valid endpoints for Metrics listed in the AWS Console UI
    datadog_api_key    = datadog_api_key.foo.key
    retry_duration     = 60  // seconds; min 0, max 7200, recommended 60
    role_arn           = aws_iam_role.firehose_role.arn
    s3_backup_mode     = "FailedDataOnly"

    s3_configuration {
      role_arn           = aws_iam_role.firehose.arn
      bucket_arn         = aws_s3_bucket.bucket.arn
      buffering_size     = 15
      buffering_interval = 600
      compression_format = "GZIP"
    }

    request_configuration {
      content_encoding = "GZIP"

      common_attributes {
        name  = "testname"
        value = "testvalue"
      }

      common_attributes {
        name  = "testname2"
        value = "testvalue2"
      }
    }
  }
}
```

### Would you like to implement a fix?

None

**Comment by caiocqueiroz** [comment]
Hello, please prioritize this. There is a behavior when using metric stream that makes DATADOG to identify that you are using kinesis and metric stream to stream the metrics, when using the destination as http_endoint, datadog cannot identity that you are using this approach.

**Comment by ewbankkit** [comment]
To send to [Datadog](https://docs.aws.amazon.com/firehose/latest/dev/create-destination.html#create-destination-datadog) use the `http_endpoint` destination.
