### ISSUE TITLE
Amazon ECS and AWS Fargate now integrate with Amazon EBS

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#35279]
> [Amazon Elastic Container Service](https://aws.amazon.com/ecs/) (Amazon ECS) and [AWS Fargate](https://aws.amazon.com/fargate/) now integrate with [Amazon Elastic Block Store](https://aws.amazon.com/ebs/) (EBS), allowing you to easily provision and attach EBS volumes to Amazon ECS tasks running on both AWS Fargate and [Amazon Elastic Cloud Compute](https://aws.amazon.com/ec2/) (EC2) using Amazon ECS APIs.

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/01/amazon-ecs-fargate-integrate-ebs/)
* [Blog post](https://aws.amazon.com/blogs/aws/amazon-ecs-supports-a-native-integration-with-amazon-ebs-volumes-for-data-intensive-workloads/)

Requires [AWS SDK for Go v1.49.19](https://github.com/aws/aws-sdk-go/releases/tag/v1.49.19): https://github.com/hashicorp/terraform-provider-aws/pull/35258.

#### Modified Resource(s)

* `aws_ecs_service`

**Comment by magusd** [comment]
this also needs modifications on the resource `aws_ecs_task_definition` 

specifically, the property `volume`.`configured_at_launch` is needed for an `aws_ecs_service` to be able to attach a volume at launch

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specify-ebs-config.html

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html

**Comment by epiehl-it** [comment]
I started this and already tested this with ecs:RunTask here:

https://github.com/epiehl-it/terraform-provider-aws/tree/f-support-ebs-in-ecs-farget

**Comment by omaraltayyan** [comment]
Could this possibly get a bit more attention? It's a really nice and critical feature for ECS, and it's been so long since it was announced

**Comment by JGSweets** [comment]
Any updates on this task? Thanks!

**Comment by Raffledoocious** [comment]
This is also a feature we'd be interested in using once it is implemented.

**Comment by MartinSoto** [comment]
This would be extremely valuable

**Comment by mcarroll1** [comment]
I created a PR for the task definition side of this: https://github.com/hashicorp/terraform-provider-aws/pull/36533 (credit to @epiehl-it for starter code).

**Comment by AlliotTech** [comment]
Although EBS does not currently support persistence, it is still very valuable.

**Comment by clorro** [comment]
A valuable addition for supporting EBS volumes on Fargate but limited use with terraform, this functionality is very useful for my use-case right now!

**Comment by anaptheo** [comment]
I'm also waiting for this one!!!
