### ISSUE TITLE
Amazon Route 53 geoproximity routing policy

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#35277]
> Starting today, Amazon Route 53 supports geoproximity routing as an additional routing policy for DNS records in public and private hosted zones.

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/01/amazon-route-53-expands-geoproximity-routing/)
* [Blog post](https://aws.amazon.com/about-aws/whats-new/2024/01/amazon-route-53-expands-geoproximity-routing/)

Requires [AWS SDK for Go v1.49.18](https://github.com/aws/aws-sdk-go/releases/tag/v1.49.18): https://github.com/hashicorp/terraform-provider-aws/pull/35241.

#### Modified Resource(s)

* `aws_route53_record`

**Comment by Siddarthyuvaraj** [comment]
@ewbankkit  Shall i take this up and raise a PR later?

**Comment by Siddarthyuvaraj** [comment]
@ewbankkit PR has been raised for this issue
https://github.com/hashicorp/terraform-provider-aws/pull/35565
