### ISSUE TITLE
Amazon CloudWatch Logs account level subscription filter

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#35278]
> Amazon CloudWatch Logs now supports account level subscription filter

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/01/amazon-cloudwatch-logs-account-level-subscription-filter/)

Requires [AWS SDK for Go v1.49.18](https://github.com/aws/aws-sdk-go/releases/tag/v1.49.18): https://github.com/hashicorp/terraform-provider-aws/pull/35241.

#### Modified Resource(s)

* `aws_logs_account_policy` (new resource)

**Comment by richcarrot** [comment]
In the meantime, I was able to use this resource
https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/logs_account_policy

```
terraform {
  required_providers {
    ...
    awscc = {
      source = "hashicorp/awscc"
      version = "~> 0.76.0"
    }
  }
}
```

```
resource "awscc_logs_account_policy" "my_cloudwatch_account_level_subscription" {
  policy_name = "MyCloudwatchAccountLevelSubscriptionPolicy"
  policy_type = "SUBSCRIPTION_FILTER_POLICY"
  scope = "ALL"
  policy_document = <<EOF
{
  "RoleArn": "arn:aws:iam::...",
  "DestinationArn": "arn:aws:firehose:...",
  "FilterPattern": ""
}
EOF
}
```
