### ISSUE TITLE
[Bug]: aws_elasticache_serverless_cache - Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by lhegarty** [hashicorp/terraform-provider-aws#35285]
### Terraform Core Version

1.6.6

### AWS Provider Version

5.32.1

### Affected Resource(s)

aws_elasticache_serverless_cache
engine: 'redis'

### Expected Behavior

Should apply with kms key id provided to 
`kms_key_id = aws_kms_key.redis_kms.key_id`

### Actual Behavior

I've replaced the repo url and AWS Account ID in the snippet below.
```
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to aws_elasticache_serverless_cache.redis, provider
│ "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected
│ new value: .kms_key_id: was
│ cty.StringVal("ea8eaec4-d8fb-46db-9707-fda399b2f6[50](PRIVATE_REPO_URL/-/jobs/1338506#L50)"), but now
│ cty.StringVal("arn:aws:kms:eu-west-1:ACCOUNT_ID:key/ea8eaec4-d8fb-46db-9707-fda399b2f650").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
```

### Relevant Error/Panic Output Snippet

```shell
See above
```

### Terraform Configuration Files

Unable to provide this, unfortunately. Jobs are being run in a locked CI/CD runner. The backend is configured to an S3 bucket backed by Dynamo, with a different workspace being selected per development environment; this was being run in a non-default workspace.

### Steps to Reproduce

Create aws_elasticache_serverless_cache on versions above with kms key applied.

### Would you like to implement a fix?

None

**Comment by ajayrockrock** [comment]
I get a similar result with the memcache engine.

**Comment by portos060474** [comment]
try to define "security_group_ids" and "subnet_ids" to type "any".

```
variable "security_group_ids" {
  description = "(Optional) A list of security group names to associate with this redis cluster. Only for ElastiCache clusters in a VPC."
  type        = any
  default     = null
```

**Comment by mshahmoradi87** [comment]
this module need arn not id , try
```
kms_key_id = aws_kms_key.redis_kms.arn
```

**Comment by aasheesh223** [comment]
I got the same error when I defined the KMS Key ID. Terraform was tainting the serverless cache (though it was created successfully with the KMS key) because after the creation of the serverless cache the state file stores the ARN of the KMS key instead of storing the KMS Key ID.

I tried to use KMS Key ID ARN and it did work and the Terraform did not taint the resource. So either the description needs to be changed to provide the KMS Key ARN instead of the KMS Key ID or the behavior needs to be fixed to store the KMS key ID in the state file instead of the ARN.

**Comment by vtstanescu** [comment]
> So either the description needs to be changed to provide the KMS Key ARN instead of the KMS Key ID or the behavior needs to be fixed to store the KMS key ID in the state file instead of the ARN.

The description is correct or was changed since your comment:
> (Optional) ARN of the customer managed key for encrypting the data at rest. If no KMS key is provided, a default service key is used.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_serverless_cache#kms_key_id
