### ISSUE TITLE
[Enhancement]: Additional app types in aws_sagemaker_studio_lifecycle_config

### ISSUE THREAD

**Issue by jmeisele** [hashicorp/terraform-provider-aws#35332]
### Description

Since reinvent and the updated Sagemaker, there are now 2 additional app types that a LifeCycle Configuration can be applied to,`JupyterLab` and `CodeEditor` . Request these 2 additional app types be allowed in resource arg [studio_lifecycle_config_app_type](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_studio_lifecycle_config#studio_lifecycle_config_app_type)

Lifecycle can be created from the aws cli the same but these 2 additional app types are now available in the arg `studio-lifecycle-config-app-type`

https://docs.aws.amazon.com/sagemaker/latest/dg/jl-lcc-create.html
https://docs.aws.amazon.com/sagemaker/latest/dg/code-editor-use-lifecycle-configurations.html 

### Affected Resource(s) and/or Data Source(s)

aws_sagemaker_studio_lifecycle_config

### Potential Terraform Configuration

```terraform
resource "aws_sagemaker_studio_lifecycle_config" "code_editor_example" {
  studio_lifecycle_config_name     = "code_editor_example"
  studio_lifecycle_config_app_type = "CodeEditor"
  studio_lifecycle_config_content  = base64encode("echo Hello")
}

resource "aws_sagemaker_studio_lifecycle_config" "jupyterlab_example" {
  studio_lifecycle_config_name     = "jlab_example"
  studio_lifecycle_config_app_type = "JupyterLab"
  studio_lifecycle_config_content  = base64encode("echo Hello")
}
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @jmeisele 👋 Thank you for taking the time to raise this! The validation for that value [comes from](https://github.com/hashicorp/terraform-provider-aws/blob/b567bdd6eb586854224e647648613f6f9b456aa6/internal/service/sagemaker/studio_lifecycle_config.go#L46) a function from the AWS Go SDK -- `sagemaker.StudioLifecycleConfigAppType_Values()`. 

This function was updated to return the values you mentioned in [release `v1.48.10`](https://github.com/aws/aws-sdk-go/pull/5092). It looks like version of the Go SDK was [pulled in](https://github.com/hashicorp/terraform-provider-aws/pull/34681) for version 5.30.0 of the provider. Can you test with version 5.30.0 or later and verify that this is currently working?

**Comment by jmeisele** [comment]
@justinretzolk absolutely, apologies for the late feedback, will test in the next day or 2

**Comment by jmeisele** [comment]
@justinretzolk worked like a charm, I can update the docs with these additional enums if you can point me in that direction?

```terraform
resource "aws_sagemaker_studio_lifecycle_config" "install_ssh_lab" {
  studio_lifecycle_config_name     = "install-ssh-lab"
  studio_lifecycle_config_app_type = "JupyterLab"
  studio_lifecycle_config_content  = base64encode(file("${path.module}/assets/install-ssh.sh"))
}

resource "aws_sagemaker_studio_lifecycle_config" "install_ssh_code" {
  studio_lifecycle_config_name     = "install-ssh-code"
  studio_lifecycle_config_app_type = "CodeEditor"
  studio_lifecycle_config_content  = base64encode(file("${path.module}/assets/install-ssh.sh"))
}
```

![image](https://github.com/hashicorp/terraform-provider-aws/assets/29043118/98f48808-1b14-4ac2-b37d-256cf8f72598)

![image](https://github.com/hashicorp/terraform-provider-aws/assets/29043118/0d434d12-799d-456b-afe4-0ff57402f725)

**Comment by justinretzolk** [comment]
Hey @jmeisele 👋 Thanks for getting back to us with the results, and for being willing to contribute a docs update! The document you'd need to edit would be [this one](https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/sagemaker_studio_lifecycle_config.html.markdown).

**Comment by jmeisele** [comment]
@justinretzolk  [PR](https://github.com/hashicorp/terraform-provider-aws/pull/35562) for your review when you get a chance
