### ISSUE TITLE
[Enhancement]: aws_mwaa_environment does not allow to chose Endpoint management creation

### ISSUE THREAD

**Issue by renaudhager** [hashicorp/terraform-provider-aws#35339]
### Terraform Core Version

1.2.0

### AWS Provider Version

5.32.1

### Affected Resource(s)

aws_mwaa_environment

### Expected Behavior

The GO AWS SDK allow to set wether or not we want AWS to manage the VPC endpoint required for MWAA ([EndpointManagement](https://github.com/aws/aws-sdk-go/blob/main/service/mwaa/api.go#L1231)) so we expect to be able to do the same using Terraform.

### Actual Behavior

Terraform does not support this field in the resource `aws_mwaa_environment`.

### Terraform Configuration Files

```hcl
resource "aws_mwaa_environment" "airflow_env" {
  dag_s3_path        = "s3://<REDACTED>-mwaa/dags/"
  execution_role_arn = aws_iam_role.mwaa_execution_role.arn
  name               = "<REDACTED>-dev-airflow-test-env"
  
  environment_class  = "mw1.small"
  max_workers        = 10
  min_workers        = 1
 
  network_configuration {
    security_group_ids = [aws_security_group.mwaa_security_group.id]
    subnet_ids         = ["subnet-081<REDACTED>", "subnet-01819<REDACTED>"]
  }
 
  source_bucket_arn = "arn:aws-cn:s3:::<REDACTED>-dev-mwaa"
 
  logging_configuration {
    dag_processing_logs {
      enabled   = true
      log_level = "DEBUG"
    }
 
    scheduler_logs {
      enabled   = true
      log_level = "INFO"
    }
  }
}
```

### Steps to Reproduce

N/A

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @renaudhager 👋 Thank you for taking the time to raise this! We consider requests for additional functionality for existing resources to be a feature request, rather than a bug. With that in mind, I'll update the issue so that whoever looks into this knows what to expect coming in.

**Comment by renaudhager** [comment]
> Hey @renaudhager 👋 Thank you for taking the time to raise this! We consider requests for additional functionality for existing resources to be a feature request, rather than a bug. With that in mind, I'll update the issue so that whoever looks into this knows what to expect coming in.

Hi @justinretzolk,

Sure no worries.
