### ISSUE TITLE
Improve filters for data source aws_autoscaling_group

### ISSUE THREAD

**Issue by obicons** [hashicorp/terraform-provider-aws#3534]
When using aws_autoscaling_group as a data source, I expect to be able to filter autoscaling groups similar to how I can filter other resource (i.e. aws_ami). 

### Terraform Version
Any

### Affected Resource(s)
aws_autoscaling_groups 

### Terraform Configuration Files
```hcl
data "aws_autoscaling_groups" "asgs" {
  filter {
    name = "tag:some-arbitrary-tag"
    values = ["some-arbitrary-value", "some-other-arbitrary-value"]
  }
}
```

### Expected Behavior
Finds AutoScaling groups that have a tag with a key `some-arbitrary-value` and either `some-arbitrary-value` or `some-other-arbitrary-value` as values.

### Actual Behavior
This behavior isn't supported.

### Preliminary Findings
I spent a little time seeing if I could implement this behavior myself. I can see why this isn't currently supported :). The data provider (`terraform-provider-aws/aws/data_source_aws_autoscaling_groups.go`) basically just encapsulates the behavior of the AWS SDK's `DescribeTags()` functionality, which means this data source isn't doing what we (users) would intuitively expect. I see two possible routes to fix this:
1. Increase the complexity of the data source by implementing the desired behavior 
2. Cooperate with Amazon to improve the quality of the SDK in this instance

Option 1 is probably the way to solve the issue fastest, but the real problem is that the SDK doesn't easily support the desired behavior, so option 2 is probably the correct solution. Perhaps we implement a temporary workaround, while looking at how we can improve the SDK to better suit this behavior?

Anyway, I'd be willing to help on this issue of the team provides some feedback on the proper approach.

**Comment by richardbowden** [comment]
this might take a while, as the raw API does not support filters, so AWS will need to update their API endpoint first, before the SDK's can be updated.

A good source for this is the raw API doc's for AWS's API
https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_DescribeAutoScalingGroups.html

**Comment by richardbowden** [comment]
@madmax88 as you mention, going via https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_DescribeTags.html should work, if I get time over the next few days, will get a PR done to test.

**Comment by 2rs2ts** [comment]
This issue is pretty old but the data source supports filters now... however, it only seems to support one tag filter at a time, or maybe it is ORing them together. If you try to do something like filter on Role=myapp, Environment=qa you get everything from Environment=qa and everything from Role=myapp

**Comment by rgherta** [comment]
In case you cannot add a unique label to the asg, you can achieve the desired workaround by making 2 queries and intersecting the result. A simple example:

```
data "aws_autoscaling_groups" "eks_asg_1" {
  filter {
    name   = "key"
    values = ["somekey"]
  }
  filter {
    name   = "value"
    values = ["somevalue"]
  }
}

 data "aws_autoscaling_groups" "eks_asg_2" {
  filter {
    name   = "key"
    values = ["someotherkey"]
  }
  filter {
    name   = "value"
    values = ["someothervalue"]
  }
}

output mvi_asg_name {
   value = element(tolist(setintersection(toset(data.aws_autoscaling_groups.eks_asg_1.names), toset(data.aws_autoscaling_groups.eks_asg_2.names))),0)
 }
```
