### ISSUE TITLE
[New Service]: Amazon Cloudwatch Network Monitor

### ISSUE THREAD

**Issue by juhala-aws** [hashicorp/terraform-provider-aws#35342]
### Description

AWS Cloudwatch Network Monitor helps one to monitor network availability and performance between AWS and your on-premises environment.

### Requested Resource(s) and/or Data Source(s)

Resource: aws_networkmonitor_monitor
Resource: aws_networkmonitor_probe

### Potential Terraform Configuration

```terraform
resource "aws_vpc" "test" {
  cidr_block = "10.0.0.0/16"
}
	
resource "aws_subnet" "test" {
  vpc_id = aws_vpc.test.id
  cidr_block = cidrsubnet(aws_vpc.test.cidr_block, 8, 0)
}

resource "aws_networkmonitor_monitor" "test" {
  aggregation_period = 30
  monitor_name = "test"
}

resource "aws_networkmonitor_probe" "test" {
  monitor_name = aws_networkmonitor_monitor.test.monitor_name
  probe {
    destination = "192.168.0.1"
    destination_port = "80"
    protocol = "TCP"
    source_arn = aws_subnet.test.arn
    packet_size = 100
  }
}
```

### References

API documentation: https://docs.aws.amazon.com/networkmonitor/latest/APIReference/Welcome.html

### Would you like to implement a fix?

Yes

**Comment by vemulkri** [comment]
More References:
 
https://aws.amazon.com/about-aws/whats-new/2023/12/amazon-cloudwatch-network-monitor-generally-available/ 
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/what-is-network-monitor.html

This is supported by the Go SDK: https://docs.aws.amazon.com/sdk-for-go/api/service/networkmonitor/

**Comment by major0** [comment]
Any idea on the timeframe for getting this in? I saw that there was a pending PR, but it doesn't seem to have moved in a few month.

**Comment by fmodarelli** [comment]
Hi team, 
Is there any ETA for this?
We are really very interested in being able to implement this feature through Terraform.
Regards.

**Comment by adpriori** [comment]
When trying to create more than one probe at a time, I get the following error:

"waiting for CloudWatch Network Monitor Probe (Network_Monitor_Core,probe-xxxxxxxxxxxxxxx) create" tf_req_id=1exxxxxxxxxxxxxxxxxxxxxx diagnostic_detail="couldn't find resource (21 retries)"

Anyone else has happened? How could it be solved?
