### ISSUE TITLE
[Enhancement]: aws_redshiftserverless_endpoint_access lacks ownerAccount attribute

### ISSUE THREAD

**Issue by grozdz** [hashicorp/terraform-provider-aws#35347]
### Terraform Core Version

1.6.6

### AWS Provider Version

5.32.1

### Affected Resource(s)

aws_redshiftserverless_endpoint_access

### Expected Behavior

Terraform apply works without any issue.

### Actual Behavior

When trying to create `aws_redshiftserverless_endpoint_access` for the workgroup that is shared from another account, as described in https://docs.aws.amazon.com/redshift/latest/mgmt/serverless-connecting.html, terraform apply fails as follows.
``` 
Error: creating Redshift Serverless Endpoint Access: ResourceNotFoundException: Serverless workgroup xxx not found.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "a6bdab4e-7cfb-451b-97b0-675655ff5d9f"
│   },
│   Message_: "Serverless workgroup xxx not found."
│ }
│ 
```

It looks like API requires ownerAccount attribute (https://docs.aws.amazon.com/redshift-serverless/latest/APIReference/API_CreateEndpointAccess.html) when creating endpoint for shared Redshift. Unfortunately this attribute is not possible to set in actual TF resource: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshiftserverless_endpoint_access

### Terraform Configuration Files

```
 resource "aws_redshiftserverless_endpoint_access" "this" {
   endpoint_name          = "redshift"
   workgroup_name         = "xxxx"
   subnet_ids             = [xxx,xxx]
   vpc_security_group_ids = [xxx]
 }
```

### Steps to Reproduce

1. Follow AWS steps to create Redshift Serverless and grant access to other account: https://docs.aws.amazon.com/redshift/latest/mgmt/serverless-connecting.html
2. Try to create `aws_redshiftserverless_endpoint_access` resource using TF for shared Redshift Workgroup (workgroup is visible on another account)

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @grozdz 👋 Thank you for taking the time to raise this! As a note, we consider adding additional functionality to an existing resource to be an enhancement rather than a bug. I've updated the issue accordingly, but wanted to explain why I did so while triaging 🙂.
