### ISSUE TITLE
[Enhancement]: Implementing the Termination Hook in CodeDeploy's deployment environment

### ISSUE THREAD

**Issue by shblue21** [hashicorp/terraform-provider-aws#35366]
### Description

Hello, last month the CodeDeploy AutoScaling Termination Hook feature was released and I would like to implement it.  
Previously, autoscaling would crash the application when a scale-in event occurred (as the instance was shut down).  
With Hooks, you can now use CodeDeploy's LifeCycle flow to shut down your application normally.

### Affected Resource(s) and/or Data Source(s)

* aws_codedeploy_deployment_group

### Potential Terraform Configuration

``` tf
resource "aws_codedeploy_deployment_group" "example" {
  app_name              = aws_codedeploy_app.example.name
  deployment_group_name = "example-group"
  service_role_arn      = aws_iam_role.example.arn
  autoscaling_groups = "deploy-asg"

...
  termination_hook_enabled = true
...
  
```
}

### References

- Whats new: https://aws.amazon.com/about-aws/whats-new/2023/12/aws-codedeploy-application-stop-hooks-ec2-auto-scaling-group-scale-ins/?nc1=h_ls
- ASG Termionation Flow(**Auto Scaling termination deployments section**): https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html#reference-appspec-file-structure-hooks-run-order
- AWS Docs: https://docs.aws.amazon.com/codedeploy/latest/userguide/integrations-aws-auto-scaling.html#integrations-aws-auto-scaling-behaviors-hook-enable
- GO SDK: https://github.com/aws/aws-sdk-go-v2/blob/service/codedeploy/v1.22.3/service/codedeploy/api_op_CreateDeploymentGroup.go#L134

### Would you like to implement a fix?

Yes

**Comment by Jeff-SearchPilot** [comment]
Is the PR planned to be merged? This feature has been GA for 9 months and there's no way to manage it in tf

**Comment by shblue21** [comment]
@Jeff-SearchPilot I haven't received any feedback from reviewers since adding this feature, so I'll double check.
The Termination Hook is quite useful.
