### ISSUE TITLE
[Docs]: aws_rds_cluster: Incorrect description for enable_http_endpoint Argument

### ISSUE THREAD

**Issue by timdeluxe** [hashicorp/terraform-provider-aws#35370]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#enable_http_endpoint

### Description

The description of that argument says that it is only valid, when engine_mode is set to "serverless", but this is not true anymore. Serverless v2 now also supports Data API for postgresql DBs and neither this module nor the AWS API stops one from doing so, which means code with enable_http_endpoint on engine_mode "provisioned" (= Serverless v2) does work. It is just the documentation which is wrong.

It should say: (Optional) Enable HTTP endpoint (data API). Only valid when engine_mode is set to serverless or (if engine is set to aurora-postgresql) to provisioned.

### References

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Concepts.Aurora_Fea_Regions_DB-eng.Feature.Data_API.html

### Would you like to implement a fix?

No

**Comment by jackedgar24** [comment]
I will make this change and open a PR,
