### ISSUE TITLE
[Enhancement]: eks auth mode change support in aws_eks_cluster

### ISSUE THREAD

**Issue by pdeva** [hashicorp/terraform-provider-aws#35376]
### Description

the new auth mode of eks api is not supported by aws_eks_cluster
https://aws.amazon.com/blogs/containers/a-deep-dive-into-simplified-amazon-eks-access-management-controls/

it still defaults to configmap auth mode. there is no way to change it to 'eks api' mode.

![Screenshot 2024-01-18 at 10 16 43 AM](https://github.com/hashicorp/terraform-provider-aws/assets/3190176/8f5d0d18-566a-471f-89d5-ec0519289b2a)

### Affected Resource(s) and/or Data Source(s)

aws_eks_cluster

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@pdeva Thanks for raising this issue.
It has already been noticed in #34982. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
