### ISSUE TITLE
[Bug]: null_resource fails after Beanstalk ASG replaced - "Provider produced inconsistent final plan"

### ISSUE THREAD

**Issue by zg-genel** [hashicorp/terraform-provider-aws#35375]
### Terraform Core Version

1.6.2

### AWS Provider Version

5.31.0

### Affected Resource(s)

null_resource

### Expected Behavior

We have an Elastic Beanstalk app where we'd like to always enable ASG metrics when the app's underlying ASG changes.  Currently we use `null_resource` with `local-exec` to run the aws cli enabling ASG metrics triggered by a change in the ASG and/or the ASG min/max capacity.

Expected behavior is that the `null_resource` detects an ASG replacement, and runs the aws cli command on the new ASG for the Elastic Beanstalk app.

### Actual Behavior

Terraform plan executes successfully, but for the `null_resource` shows the original ASG.
During `terraform apply`, one of two outcomes happens after the ASG is replaced:
  * the apply fails (final inconsistent plan) due to the plan expecting the original ASG but seeing the new ASG
  * the apply succeeds, but the terraform needs to be reran to apply the `null_resource` on the new ASG
To resolve, `terraform plan` is reran to have `null_resource` pickup the new ASG, and then `terraform apply` succeeds.

### Relevant Error/Panic Output Snippet

```shell
Plan:


  + resource "null_resource" "autoscaling_enable_metrics" {
      + id       = (known after apply)
      + triggers = {
          + "autoscaling_group_name" = "awseb-e-***-stack-AWSEBAutoScalingGroup-***AVS"
          + "aws_profile"            = "***"
          + "aws_region"             = "us-west-2"
          + "instance_max_size"      = "75"
          + "instance_min_size"      = "15"
          + "version"                = "1"
        }
    }
```

Apply: 

```
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.bl-prod-env.module.bookshelf_listings_autoscaling_metrics.null_resource.autoscaling_enable_metrics["awseb-e-***-stack-AWSEBAutoScalingGroup-***AVS"]
│ to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/null" produced an invalid new value for
│ .triggers["autoscaling_group_name"]: was
│ cty.StringVal("awseb-e-***-stack-AWSEBAutoScalingGroup-***AVS"),
│ but now
│ cty.StringVal("awseb-e-***-stack-AWSEBAutoScalingGroup-***ANZ").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

### Terraform Configuration Files

[eb-asg-bug.zip](https://github.com/hashicorp/terraform-provider-aws/files/13980266/eb-asg-bug.zip)

### Steps to Reproduce

1. Replace values in provider.tf and terraform.tfvars with appropriate values for your AWS account
2. In terraform.tfvars, set `solution_stack_name = "64bit Amazon Linux 2 v4.3.15 running Tomcat 8.5 Corretto 8"`
3. Run the terraform to create an eb app and its ASG
4. In Elastic Beanstalk AWS console, select test-app-env then goto `Configuration > Instance traffic and scaling Edit button`, check the `IMDSv1` box to deactivate it
5. In terraform.tfvars, set `solution_stack_name = "64bit Amazon Linux 2 v4.1.3 running Tomcat 8.5 Corretto 8"`
6. Run terraform plan and apply, it should produce an inconsistent plan failure (if succeeds, then a subsequent plan should show `null_resource` still needing to run against new ASG)

### Important Factoids

Triggering AutoScalingGroup replacement for Elastic Beanstalk is finicky.  The way I've done it in the bug doesn't exactly mirror our environment, but it's close enough and fairly consistent to reproduce.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @zg-genel 👋 Thank you for taking the time to raise this! In this case, the "Inconsistent final plan" error is related to the `null_resource` (Null Provider), rather than the AWS Provider, so you'd want to report the bug in that [provider's repository](https://github.com/hashicorp/terraform-provider-null). With that in mind, closing this issue in favor of reporting there.

**Comment by zg-genel** [comment]
Oh hah, I didn't realize `null_resource` was its own provider.   Thanks for the haeds up, I'll move the bug there.
