### ISSUE TITLE
[Bug]: Unsupported argument "target_object_key_format" in resource aws_s3_bucket_logging when using aws-provider v5.31

### ISSUE THREAD

**Issue by dbrat43** [hashicorp/terraform-provider-aws#35396]
### Terraform Core Version

v1.0.11

### AWS Provider Version

v5.31.0

### Affected Resource(s)

```
resource "aws_s3_bucket_logging" "example" {
  bucket = "bucket-1"

  target_bucket = "bucket-2"
  target_prefix = "log/"

  target_object_key_format = {
    partitioned_prefix = {
      partition_date_source = "DeliveryTime"
    }
  }
}
```

### Expected Behavior

The resource should have been able to recognize the target_object_key_format property and configure the partitioned date prefix for server access logs given that this configuration block has been present since aws-provider v5.27 - https://registry.terraform.io/providers/hashicorp/aws/5.31.0/docs/resources/s3_bucket_logging#target_object_key_format

### Actual Behavior

The terraform plan failed as shown below (please note aws provider version in debug logs):

Error: Unsupported argument
│
│ on main.tf line 209, in resource "aws_s3_bucket_logging" "example":
│ 209: target_object_key_format = {
│
│ An argument named "target_object_key_format" is not expected here. Did you
│ mean to define a block of type "target_object_key_format"?
╵
2024-01-18T19:47:47.127Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2024-01-18T19:47:47.138Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/aws/5.31.0/linux_amd64/terraform-provider-aws_v5.31.0_x5 pid=367
2024-01-18T19:47:47.138Z [DEBUG] provider: plugin exited

### Terraform Configuration Files

Assuming buckets "bucket-1" and "bucket-2" exist, the only other required setup to replicate is the resource below. 

```
resource "aws_s3_bucket_logging" "example" {
  bucket = "bucket-1"

  target_bucket = "bucket-2"
  target_prefix = "log/"

  target_object_key_format = {
    partitioned_prefix = {
      partition_date_source = "DeliveryTime"
    }
  }
}
```

### Steps to Reproduce

terraform init
terraform apply

### Debug Output

See above

### Panic Output

See above

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@dbrat43 Thanks for raising this issue 👏.
The correct syntax is

```hcl
  target_object_key_format {
    partitioned_prefix {
      partition_date_source = "DeliveryTime"
    }
  }
```
