### ISSUE TITLE
[Enhancement]:  Add custom images support to SageMaker Studio JupyterLabApplicationSettings

### ISSUE THREAD

**Issue by gilandose** [hashicorp/terraform-provider-aws#35434]
### Description

There is an additional param not available in terraform form `JupyterLabApplicationSettings` nameling `CustomImages` this allows images to be attached to a space with user installed packages

### Affected Resource(s) and/or Data Source(s)

aws_sagemaker_domain

### Potential Terraform Configuration

```terraform

resource "aws_sagemaker_domain" "example" {
...
default_user_settings {
    jupyter_lab_app_settings {
      custom_image [{
        image_name = example
        image_version_number = 1
        app_image_config_name = example_config
       }]
    }
  }
}
```

### References

go library type => https://github.com/aws/aws-sdk-go-v2/blob/857d5277b41f290ab7ba0e0f6f96f940045f69b7/service/sagemaker/types/types.go#L7905

update-domain cli documentation
https://docs.aws.amazon.com/cli/latest/reference/sagemaker/update-domain.html#options

structure exists already on `KernelGatewayApplicationSettings`
https://github.com/hashicorp/terraform-provider-aws/blob/742dcf6831fb531a0e76cdef7dd5c6ead3662aec/internal/service/sagemaker/domain.go#L186

### Would you like to implement a fix?

No

**Comment by gilandose** [comment]
Yeah can confirm it works and the documentation is just missing, so we can convert this to just a documentation update

**Comment by justinretzolk** [comment]
Hi @gilandose 👋 Thank you for taking the time to raise this! I've just opened a pull request to update the documentation.
