### ISSUE TITLE
[Docs]: EKS cluster resource documentation errors

### ISSUE THREAD

**Issue by anshuman-osc** [hashicorp/terraform-provider-aws#35438]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster

### Description

* The access_config section links to control plane logging. See: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#access_config
* There are duplicate encryption_config sections. The first one should probably be called access_config. See: 
  * https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#encryption_config and 
  * https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#encryption_config-1

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
Looks like this is already fixed via #35381 targeted for v5.34.0.
