### ISSUE TITLE
ECS Service Connect traffic encryption

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#35446]
> [Amazon Elastic Container Service](https://aws.amazon.com/ecs/) (Amazon ECS) launches support for automatic traffic encryption with Transport Layer Security (TLS) certificates for its networking capability called ECS Service Connect.

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/01/amazon-ecs-service-connect-automatic-traffic-encryption-tls-certificates/)

Requires [AWS SDK for Go v1.50.1](https://github.com/aws/aws-sdk-go/releases/tag/v1.50.1): https://github.com/hashicorp/terraform-provider-aws/pull/35442.

#### Affected Resource(s)

* `aws_ecs_service`

```hcl
resource "aws_ecs_service" "example" {
  service_connect_configuration {
    service {
      tls {
        ...
      }
    }
  }
}
```

**Comment by dgr237** [comment]
I am happy to work on this Issue

**Comment by dgr237** [comment]
PR: https://github.com/hashicorp/terraform-provider-aws/pull/35684 raised to close this issue

**Comment by izeau** [comment]
Maybe this could also include the new `timeout` parameter as well?

- https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ServiceConnectService.html#ECS-Type-ServiceConnectService-timeout
- https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ecs/types#ServiceConnectService
- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-connect-concepts.html#service-connect-concepts-config

**Comment by dgr237** [comment]
@izeau Will look to add this.
