### ISSUE TITLE
[Docs]: To use an alias on a aws_kms_key data source, make it clear how to do so.

### ISSUE THREAD

**Issue by matthewaerose** [hashicorp/terraform-provider-aws#35465]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/kms_key

### Description

In order to use an alias to look up an aws_kms_key data source, you must prepend the alias with `alias`. This isn't entirely clear from the documentation.

Instead of this as an example
> Alias name. E.g.: alias/my-key

maybe this
> Alias name. Example, for the alias `secrets/my-key`, provide `alias/secrets/my-key`.

### Would you like to implement a fix?

Yes

**Comment by matthewaerose** [comment]
I can update the docs if the suggested replacement looks ok.

**Comment by justinretzolk** [comment]
Hey @matthewaerose 👋 Thank you for taking the time to raise this! In this case, I believe the documentation is accurate as stands, as `alias/` is [always prepended](https://docs.aws.amazon.com/kms/latest/developerguide/alias-about.html). With that in mind, closing this for now. If you have any future suggestions, or run into any issues with the provider in the future, please do let us know, and we'll be happy to take a look!

**Comment by matthewaerose** [comment]
@justinretzolk 
That's all well and good that the AWS docs say that. But the TF docs don't. They state that to use an alias, you should provide `alias/my-key`. 

The AWS docs state you there are two alias formats; ARN and `alias/<alias-name>`. That is much clearer.
