### ISSUE TITLE
[Enhancement]: CodePipeline V2: Add support for pipeline triggers

### ISSUE THREAD

**Issue by ribeiroh** [hashicorp/terraform-provider-aws#35475]
### Description

CodePipeline V2 has added support for pipeline triggers on git tags. At the moment, the `aws_codepipeline` does not support configuring this functionality.

### Affected Resource(s) and/or Data Source(s)

* aws_codepipeline

### Potential Terraform Configuration

```terraform
resource "aws_codepipeline" "codepipeline" {
  name     = "tf-test-pipeline"

  triggers {
    provider_type = "CodeStarSourceConnection"
    git_configuration = {
      source_action_name = "GitHub"
      tags = {
        include = ["good_tag"]
        exclude = ["bad_tag"]
      }
    }
  }
}
```

### References

- [Announcement](https://aws.amazon.com/about-aws/whats-new/2023/10/aws-codepipeline-triggering-git-tags/)
- [Documentation](https://docs.aws.amazon.com/codepipeline/latest/userguide/concepts.html#concepts-triggers)
- [API Reference](https://docs.aws.amazon.com/codepipeline/latest/APIReference/API_PipelineDeclaration.html#CodePipeline-Type-PipelineDeclaration-triggers) 

### Would you like to implement a fix?

No

**Comment by neruneruo** [comment]
@ribeiroh 
Does the following HCL meet your expectations?
Since I have written the source code with this content,  if you are happy with proceeding, I will create a PR.

```HCL
  trigger {
    provider_type = "CodeStarSourceConnection"
    git_configuration {
      source_action_name = "Source"
      push {
        branches {
          includes = ["main", "foobar"]
          excludes = ["feature/*", "issue/*"]
        }
        file_paths {
          includes = ["src/production1", "src/production2"]
          excludes = ["test/production1", "test/production2"]
        }
        tags {
          includes = ["tag1", "tag2"]
          excludes = ["tag11", "tag12"]
        }
      }
      pull_request {
        events = ["OPEN","CLOSED"]
        branches {
          includes = ["main", "foobar"]
          excludes = ["feature/*", "issue/*"]
        }
        file_paths {
          includes = ["src/production1", "src/production2"]
          excludes = ["test/production1", "test/production2"]
        }
      }
    }
  }
```

**Comment by ribeiroh** [comment]
@neruneruo this exceeds my expectations :) Thanks a lot!
