### ISSUE TITLE
Enable Microsoft SQL Server Windows authentication in RDS

### ISSUE THREAD

**Issue by HarikrishnaM1093** [hashicorp/terraform-provider-aws#35476]
### Description

HI team,

Greetings!!

We have a requirement to enable **Microsoft SQL Server Windows authentication with self managed Microsoft AD in RDS** details. We have gone through the issue #32998, but don't have much details to enable it using terraform. 

We have tried by disabling IAM_Database_Authentication and tried many items, but couldnt enable it. Please let us know if any further details to implement.

### Would you like to implement a fix?

Yes

**Comment by HarikrishnaM1093** [comment]
[g2r1990](https://github.com/g2r1990), sorry to trouble you, we could see that you have fixed the issue and enabled MS Authentication in RDS using Terraform. Kindly let us know how it got enabled, it will be much helpful for me.

**Comment by justinretzolk** [comment]
Hey @HarikrishnaM1093 👋 Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. To maintain that, we ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). With that in mind, I'm going to close this issue.
