### ISSUE TITLE
[Bug]: aws_lambda_layer shows perpetual difference when using archive_file

### ISSUE THREAD

**Issue by jamiegosling** [hashicorp/terraform-provider-aws#35478]
### Terraform Core Version

1.6.6

### AWS Provider Version

5.22.0

### Affected Resource(s)

aws_lambda_layer

### Expected Behavior

Using the hash of an `archive_file` data source should not trigger a redeployment of the layer unless the files in `source_dir` of the `archive_file` data source have changed

### Actual Behavior

The layer is redeployed each time, although (as far as I can tell - the files are created within a CI system (Concourse) using `npm ci`, there is a `package-lock.json' file created with the same version of npm) the files in `source_dir` are identical

### Terraform Configuration Files

```
resource "aws_lambda_layer_version" "node_layer" {
  for_each = data.archive_file.node_layer
  filename = data.archive_file.node_layer[each.key].output_path
  source_code_hash = data.archive_file.node_layer[each.key].output_base64sha512
  layer_name = "${var.environment}-${var.workflow}${var.product}-layer"
  compatible_runtimes = [ "nodejs18.x" ]
}

data "archive_file" "node_layer" {
  for_each = local.node_layers

  type        = "zip"
  source_dir  = each.value.file_path
  output_path = "${each.value.file_path}/package.zip"
  excludes = [
    "nodejs/package-lock.json",
    "nodejs/package.json",
    "tsconfig.json",
    "src",
    "tests",
    ".gitignore",
    "package.zip"
  ]
}
```

### Steps to Reproduce

- create a `package.json` and `package-lock.json` file including some npm libraries
- use `npm install` to install the libraries

### Important Factoids

We have a similar setup using the aws_lambd_function resource and it does not redeploy each time:

``` 
data "archive_file" "lambda_zip" {
  type        = "zip"
  source_dir  = "${path.cwd}/${var.lambdafiles}"
  output_path = "${path.cwd}/${var.lambdafiles}/package.zip"
  excludes = [
    "package-lock.json",
    "tsconfig.json",
    "tests",
    ".gitignore",
    "jest.config.js",
    "*.tf",
    "*.zip"
  ]
}

resource "aws_lambda_function" "lambda_function" {
  filename          = data.archive_file.lambda_zip.output_path
  function_name     = "${var.environment}-${var.workflow}${var.product}-${var.lambda_name}-lambda"
  source_code_hash  = data.archive_file.lambda_zip.output_base64sha256  
  description       = var.description
  role              = var.role_arn != "" ? var.role_arn : aws_iam_role.lambda_role[0].arn
  handler           = var.handler != "" ? var.handler : "${var.lambda_name}.lambda_handler"
  runtime           = var.runtime
  timeout           = var.timeout
  memory_size       = var.memory

  layers = concat([ for k,v in data.aws_lambda_layer_version.layers : v.arn ], [ for k,v in data.aws_lambda_layer_version.global_layers : v.arn ])

  environment {
    variables = var.environment_vars
  }
  dynamic vpc_config {

    for_each = toset(length(var.subnets) > 0 ? [null] : [])

    content {
      subnet_ids         = var.subnets
      security_group_ids = var.security_groups
    }
  }
  depends_on = [
    aws_cloudwatch_log_group.lambda_cloudwatch_loggroup
  ]
}
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @jamiegosling 👋 Thank you for taking the time to raise this! Are you able to supply debug logs (redacted as needed) so that we have that information to help with any investigation?

**Comment by jamiegosling** [comment]
Hi @justinretzolk,

Thanks for the response - having had a look at the provider code and looking again at my code I can see it was an error on my part; in the lambda layer I'm using the wrong hash function `output_base64sha512` when I should be using `output_base64sha256`, the same as in the lambda function.  This is already in the documentation as well 
```
[source_code_hash] - (Optional) Used to trigger updates. Must be set to a base64-encoded SHA256 hash
```
 so nothing required on your side; thanks again!

Jamie
