### ISSUE TITLE
[Enhancement]: add managed_draining to aws_ecs_capacity_provider

### ISSUE THREAD

**Issue by remiflament** [hashicorp/terraform-provider-aws#35484]
### Description

AWS [announced](https://aws.amazon.com/fr/about-aws/whats-new/2024/01/amazon-ecs-managed-instance-draining/) a new option activated by default on ECS capacity provider : managed instance draining

It would be nice to configure it by adding a new parameter in the resource.

### Affected Resource(s) and/or Data Source(s)

aws_ecs_capacity_provider

### Potential Terraform Configuration

```terraform
resource "aws_ecs_capacity_provider" "test" {
  # ...

  auto_scaling_group_provider {
    # ...

    managed_draining = "ENABLED"
  }
}
```

### References

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/managed-instance-draining.html#enable-managed-instance-draining

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@remiflament Thanks for raising this issue.
It has already been noticed in #35415. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by remiflament** [comment]
Perfect ! Sorry I missed it despite my research on existing issues 😬
