### ISSUE TITLE
[New Service]: aws_bedrockagent

### ISSUE THREAD

**Issue by jgard** [hashicorp/terraform-provider-aws#35543]
### Description

Support for Bedrock Agent configuration

### Requested Resource(s) and/or Data Source(s)

resources

- [x] [`aws_bedrockagent_agent`](https://github.com/hashicorp/terraform-provider-aws/pull/36851)
- [x] [`aws_bedrockagent_action_group`](https://github.com/hashicorp/terraform-provider-aws/pull/36935)
- [x] [`aws_bedrockagent_agent_alias`](https://github.com/hashicorp/terraform-provider-aws/pull/36905)
- [x] [`aws_bedrockagent_knowledge_base`](https://github.com/hashicorp/terraform-provider-aws/pull/36783)
- [x] [`aws_bedrockagent_agent_knowledge_base_association`](https://github.com/hashicorp/terraform-provider-aws/pull/37185)
- [x] [`aws_bedrockagent_data_source`](https://github.com/hashicorp/terraform-provider-aws/pull/37158)

(and data sources for each)

### Potential Terraform Configuration

```terraform
resource "aws_bedrockagent" "this" {
  name="my_agent"
  instruction="I am a bedrock agent(...)"
  foundation_model="anthropic.claude-instant-v1"
  description="My agent description"
  idle_session_ttl_seconds=1800
  resource_role_arn = "arn:aws:iam:::roles/myagentrole"
  tags {
    mytag="myvalue"
  }
  #customer_encryption_key_arn = ""
  #prompt_override_configuration {}
}

resource "aws_bedrockagent_action_group" "this" {
  name="my_agent_action_group"
  description="My agent action group description"
  parent_action_group_signature = "AMAZON.UserInput"
  action_group_executor {
    lambda="arn:aws:lambda:region:account:function:my-agent-lambda"
  }
  api_schema = {
    s3 {
      bucket_name="my-agent-bucket"
      key = "my-agent.json"
    }
    #payload = jsonencode({}) #alternative, direct upload
  }
  state="ENABLED"
}

resource "aws_bedrockagent_alias" "this" {
  agent_id = aws_bedrock_agent.this.id
  name = "my_agent_alias"
}

resource "aws_bedrockagent_knowledge_base" "this" {
  name = "my_knowledge_base"
  description = "My bedrock knowledge base"
  role_arn = "arn:aws:iam::account:role/AmazonBedrockExecutionRoleForKnowledgeBase_my_agent"
  configuration {
    type = "VECTOR"
    vector_knowledge_base_configuration {
      embedding_model_arn = "arn:aws:bedrock:REGION::foundation-model/my-embedding-model"
    }
  }
  storage_configuration {
    type="OPENSEARCH_SERVERLESS"
    opensearch_serverless_configuration {
      collection_arn = "arn:aws:aoss:REGION:ACCOUNT:collection/my-collection"
      vectorIndexName = "bedrock-knowledge-base-default-index"
      field_mapping {
        vector_field = "bedrock-knowledge-base-default-vector"
        text_field = "AMAZON_BEDROCK_TEXT_CHUNK"
        metadata_field = "AMAZON_BEDROCK_METADATA"
      }
    }
  }
  tags {
    mytag="myvalue"
  }
}

resource "aws_bedrockagent_data_source" "this" {
  knowledge_base_id = aws_bedrock_knowledge_base.this.id
  name = "my_data_source"
  description = "My bedrock datasource"
  configuration {
    type = "S3"
    s3_configuration {
      bucket_arn = "arn:aws:s3:::my-data-source-bucket"
      inclusion_prefixes = ["prefix1","prefix2"]
    }
  }
  #server_side_encryption_configuration {
  #  kms_key_arn = ""
  #}
  vector_ingestion_configuration {
    chunking_configuration {
      chunking_strategy = "FIXED_SIZE"
      fixed_size_chunking_configuration {
        max_tokens = 300
        overlap_percentage = 5
      }
    }
  }
}

resource "aws_bedrockagent_knowledge_base_association" "this" {
  agent_id = aws_bedrock_agent.this.id
  agent_version = "my_agent_version"
  knowledge_base_id = aws_bedrock_agent_knowledge_base.this.id
  description = "helps answer questions for the agent on this specific subject"
  state = "ENABLED"
}
```

### References

* https://docs.aws.amazon.com/bedrock/latest/APIReference/API_Operations_Agents_for_Amazon_Bedrock.html
* https://docs.aws.amazon.com/cli/latest/reference/bedrock-agent/

### Would you like to implement a fix?

None

**Comment by nrnrk** [comment]
Is anyone working on this? If not, I'd like to.

**Comment by ewbankkit** [comment]
The new resources should use `aws_bedrockagent_` as a prefix, not `aws_bedrock_agent`.

**Comment by theolrtpwc** [comment]
I don't see all these terraform resource blocks available on aws-provider [v5.38.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.38.0). 
But it is mentioned [here](https://github.com/hashicorp/terraform-provider-aws/pull/35708#issuecomment-1935093437) that they have been added to v5.36.0.
Can anyone shed some light on this?

**Comment by nrnrk** [comment]
Resource implementations are not done yet. I'm working on aws_bedrockagent_agent resource now.

**Comment by theolrtpwc** [comment]
Do you have any idea of the release date of this feature ?

**Comment by kpx-dev** [comment]
@nrnrk thanks for your awesome work on this. I’m also very interested in adopting this soon. Can you please help share ETA or anything else I can help to speed this up?

**Comment by theolrtpwc** [comment]
I’m eager to adopt it soon. Could you please provide an ETA or any other information that might help accelerate its progress?

**Comment by ixolt** [comment]
it seems to me it was missed `aws_bedrockagent_knowledge_base_data_source` resource

**Comment by purplexed** [comment]
@ixolt I think this is covered by the `aws_bedrockagent_data_source`.

However, there are plenty of issues with that:
1. The documentation is just the default generated template, I raised a ticket for that: https://github.com/hashicorp/terraform-provider-aws/issues/37420
2. The example shown above in the thread is wrong, the resource expects `data_source_configuration` instead of the `configuration` block.
3. The import doesn't look like it's working with just the data source ID.
