### ISSUE TITLE
[Enhancement]:  aws_lakeformation_resource to register an S3 location in Hybrid mode

### ISSUE THREAD

**Issue by prithvi514** [hashicorp/terraform-provider-aws#35548]
### Description

In the current setup there is no option to register S3 location  in LakeFormation `Hybrid mode`. It defaults to `Lake Formation` permission mode.

```terraform
resource "aws_lakeformation_resource" "example" {
  arn = data.aws_s3_bucket.example.arn
}
```

### Affected Resource(s) and/or Data Source(s)

`aws_lakeformation_resource`

### References

https://docs.aws.amazon.com/lake-formation/latest/dg/hybrid-access-mode.html
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lakeformation_resource

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Related #33455
