### ISSUE TITLE
[Bug]: `data.aws_vpc_peering_connections` is recomputed when `aws_vpc` has tag changes

### ISSUE THREAD

**Issue by samuel-phan** [hashicorp/terraform-provider-aws#35544]
### Terraform Core Version

1.7.1

### AWS Provider Version

5.34.0

### Affected Resource(s)

- `data.aws_vpc_peering_connection`
- `data.aws_vpc_peering_connections`

### Expected Behavior

The data sources shouldn't be recomputed upon `aws_vpc` tag changes (as the VPC ID doesn't change).

### Actual Behavior

The data sources are recomputed upon `aws_vpc` tag changes (although the VPC ID doesn't change).

### Relevant Error/Panic Output Snippet

```shell
❯ terraform apply
data.aws_vpcs.bastion: Reading...
aws_vpc.this: Refreshing state... [id=vpc-022dc4398492deff5]
data.aws_vpcs.bastion: Read complete after 1s [id=us-east-1]
data.aws_vpc.bastion[0]: Reading...
data.aws_vpc.bastion[0]: Read complete after 1s [id=vpc-019048aa90df71656]
aws_internet_gateway.this: Refreshing state... [id=igw-001a921980d360295]
aws_route_table.public: Refreshing state... [id=rtb-0c4d6905d5b40f29f]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place
 <= read (data resources)

Terraform will perform the following actions:

  # data.aws_vpc_peering_connections.bastion[0] will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "aws_vpc_peering_connections" "bastion" {
      + id   = (known after apply)
      + ids  = (known after apply)
      + tags = (known after apply)

      + filter {
          + name   = "accepter-vpc-info.vpc-id"
          + values = [
              + "vpc-022dc4398492deff5",
            ]
        }
      + filter {
          + name   = "requester-vpc-info.vpc-id"
          + values = [
              + "vpc-019048aa90df71656",
            ]
        }
    }

  # aws_internet_gateway.this will be updated in-place
  ~ resource "aws_internet_gateway" "this" {
        id       = "igw-001a921980d360295"
      ~ tags     = {
            "Name"                  = "my-vpc-igw-us-east-1"
          ~ "foo"                   = "bar" -> "bar2"
            "gacco:IgnoreVpcSyslog" = "True"
        }
      ~ tags_all = {
          ~ "foo"                   = "bar" -> "bar2"
            # (2 unchanged elements hidden)
        }
        # (3 unchanged attributes hidden)
    }

  # aws_route_table.public will be updated in-place
  ~ resource "aws_route_table" "public" {
        id               = "rtb-0c4d6905d5b40f29f"
      ~ route            = [
          - {
              - carrier_gateway_id         = ""
              - cidr_block                 = "0.0.0.0/0"
              - core_network_arn           = ""
              - destination_prefix_list_id = ""
              - egress_only_gateway_id     = ""
              - gateway_id                 = "igw-001a921980d360295"
              - ipv6_cidr_block            = ""
              - local_gateway_id           = ""
              - nat_gateway_id             = ""
              - network_interface_id       = ""
              - transit_gateway_id         = ""
              - vpc_endpoint_id            = ""
              - vpc_peering_connection_id  = ""
            },
          - {
              - carrier_gateway_id         = ""
              - cidr_block                 = "10.10.0.0/19"
              - core_network_arn           = ""
              - destination_prefix_list_id = ""
              - egress_only_gateway_id     = ""
              - gateway_id                 = ""
              - ipv6_cidr_block            = ""
              - local_gateway_id           = ""
              - nat_gateway_id             = ""
              - network_interface_id       = ""
              - transit_gateway_id         = ""
              - vpc_endpoint_id            = ""
              - vpc_peering_connection_id  = "pcx-0bada2ef3e1e8e935"
            },
          + {
              + carrier_gateway_id         = (known after apply)
              + cidr_block                 = (known after apply)
              + core_network_arn           = ""
              + destination_prefix_list_id = (known after apply)
              + egress_only_gateway_id     = (known after apply)
              + gateway_id                 = (known after apply)
              + ipv6_cidr_block            = (known after apply)
              + local_gateway_id           = (known after apply)
              + nat_gateway_id             = (known after apply)
              + network_interface_id       = (known after apply)
              + transit_gateway_id         = (known after apply)
              + vpc_endpoint_id            = (known after apply)
              + vpc_peering_connection_id  = (known after apply)
            },
        ]
      ~ tags             = {
            "Name"                  = "my-vpc-public-rtb-us-east-1"
          ~ "foo"                   = "bar" -> "bar2"
            "gacco:IgnoreVpcSyslog" = "True"
        }
      ~ tags_all         = {
          ~ "foo"                   = "bar" -> "bar2"
            # (2 unchanged elements hidden)
        }
        # (4 unchanged attributes hidden)
    }

  # aws_vpc.this will be updated in-place
  ~ resource "aws_vpc" "this" {
        id                                   = "vpc-022dc4398492deff5"
      ~ tags                                 = {
            "Name"                  = "my-vpc"
          ~ "foo"                   = "bar" -> "bar2"
            "gacco:IgnoreVpcSyslog" = "True"
        }
      ~ tags_all                             = {
          ~ "foo"                   = "bar" -> "bar2"
            # (2 unchanged elements hidden)
        }
        # (14 unchanged attributes hidden)
    }

Plan: 0 to add, 3 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:
aws_vpc.this: Modifying... [id=vpc-022dc4398492deff5]
aws_vpc.this: Modifications complete after 2s [id=vpc-022dc4398492deff5]
data.aws_vpc_peering_connections.bastion[0]: Reading...
aws_internet_gateway.this: Modifying... [id=igw-001a921980d360295]
data.aws_vpc_peering_connections.bastion[0]: Read complete after 0s [id=us-east-1]
aws_internet_gateway.this: Modifications complete after 1s [id=igw-001a921980d360295]
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for aws_route_table.public to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new
│ value for .route: length changed from 1 to 2.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Terraform Configuration Files

- [`tf-plan-bug-peering-connections/main.tf`](https://gist.github.com/samuel-phan/3ce63d7c854c184c2688b994cdcb528d)
- [`tf-plan-bug-peering-connection/main.tf`](https://gist.github.com/samuel-phan/655fdf833f2c435ab5c09100e175b918)
- [`bastion/main.tf`](https://gist.github.com/samuel-phan/56c4c5283ecce1ee5de656882113d86d)

#### Requirements

- Create the 3 directories `tf-plan-bug-peering-connections`, `tf-plan-bug-peering-connections` and `bastion` with the `main.tf` above.

#### tf-plan-bug-peering-connections

- Go to the `tf-plan-bug-peering-connection` directory and run:

  ```shell
  terraform init
  terraform apply
  ```

  It will create a VPC named `my-vpc` with a route table.

- Go to the `bastion` directory and run:

  ```shell
  terraform init
  terraform apply
  ```

  It will create a VPC named `bastion` and create a VPC peering with the VPC `my-vpc`.

- Go back to the `tf-plan-bug-peering-connection` directory and run:

  ```shell
  terraform apply
  ```

  It will add an entry in the route table for the VPC peering with the VPC `bastion`.

- Now, change in the code `tf-plan-bug-peering-connections/main.tf` the tag `foo = bar2` for example, and run:

  ```shell
  terraform apply
  ```

  You should see this `Error: Provider produced inconsistent final plan`.

- Teardow the `bastion` stack:

  ```shell
  terraform destroy
  ```

- Teardow the `tf-plan-bug-peering-connections` stack:

  ```shell
  terraform destroy
  ```

#### tf-plan-bug-peering-connection

The test protocol is exactly the same as for `tf-plan-bug-peering-connections`. You should see a similar error upon the final `terraform apply`.

### Debug Output

https://gist.github.com/samuel-phan/13ac38f94484ca41cd36044c2ac88257

### Panic Output

N/A.

### Important Factoids

The core issue is this dependency:

```
aws_vpc.this <-- data.aws_vpc_peering_connections.bastion
```

When the `aws_vpc.this` has its tags changed, it triggers a computation on the `data.aws_vpc_peering_connections.bastion` data source even though the none of the attributes has changed, particular this block:

```hcl
  filter {
    name   = "accepter-vpc-info.vpc-id"
    # Issue: When there's a change on the VPC tags, this `data.aws_vpc_peering_connections.bastion` is recomputed even
    #        if the `aws_vpc.this.id` has not changed!
    values = [aws_vpc.this.id]
  }
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @samuel-phan 👋 Thank you for taking the time to raise this! There's two things going on here:

1. The `inconsistent final plan` error
2. The delayed reading of `data.aws_vpc_peering_connections.bastion`

The `inconsistent final plan` error is, as the error indicates, a bug in the provider. I'd like to leave the issue open with that in mind (though I'll need to update the title, and maybe add a bit of info to the body of the issue if that's okay).

As far as the delayed reading of `data.aws_vpc_peering_connections.bastion` when the VPC has tag changes, while it's unfortunate in this case, that's the expected behavior of Terraform Core (the AWS Provider isn't able to influence this). We outline this in the [Data Resource Behavior](https://developer.hashicorp.com/terraform/language/data-sources#data-resource-behavior) section of the Terraform documentation.

> Terraform defers reading data resources in the following situations:
>
> _...omitted for brevity_
> - The data resource depends directly on a managed resource that itself has planned changes in the current plan.

Since the `aws_vpc_peering_connections` resource is directly dependent on the `aws_vpc` resource that has a planned change, the data source must be read at plan time.

**Comment by samuel-phan** [comment]
Thanks for your reply @justinretzolk ! 🙏 

And thanks to the doc you shared, I managed to fix it ! 🎉 

I changed this part in the `data.

```hcl
data "aws_vpc_peering_connections" "bastion" {
  count = length(data.aws_vpcs.bastion.ids) == 1 ? 1 : 0

  filter {
    name   = "requester-vpc-info.vpc-id"
    values = [data.aws_vpcs.bastion.ids[0]]
  }

  filter {
    name = "accepter-vpc-info.vpc-id"
    # Issue: When there's a change on the VPC tags, this `data.aws_vpc_peering_connections.bastion` is recomputed even
    #        if the `aws_vpc.this.id` has not changed!
    values = [aws_vpc.this.id]
  }
}
```

to:

```hcl
data "aws_vpc_peering_connections" "bastion" {
  count = length(data.aws_vpcs.bastion.ids) == 1 ? 1 : 0

  filter {
    name   = "requester-vpc-info.vpc-id"
    values = [data.aws_vpcs.bastion.ids[0]]
  }

  filter {
    name = "accepter-vpc-info.vpc-id"
    # This `local.vpc_id` MUST be kept instead of `aws_vpc.this.id` because of "Data Resource Dependencies".
    # Doc: https://developer.hashicorp.com/terraform/language/data-sources#data-resource-dependencies
    # If the `aws_vpc.this` resource is changed (even if the `aws_vpc.this.id` is not changed), this
    # `data.aws_vpc_peering_connections.bastion` will be refreshed, leading to:
    #
    # Error: Provider produced inconsistent final plan
    #
    # on Route tables & NACLs.
    values = [local.vpc_id]
  }
}

locals {
  vpc_id = aws_vpc.this.id
}
```

As stated from <https://developer.hashicorp.com/terraform/language/data-sources#data-resource-dependencies>:

> Data resources have the same dependency resolution behavior [as defined for managed resources](https://developer.hashicorp.com/terraform/language/resources/behavior#resource-dependencies). Setting the `depends_on` meta-argument within `data` blocks defers reading of the data source until after all changes to the dependencies have been applied.
>
> In order to ensure that data sources are accessing the most up to date information possible in a wide variety of use cases, arguments directly referencing managed resources are treated the same as if the resource was listed in `depends_on`. This behavior can be avoided when desired by indirectly referencing the managed resource values through a `local` value, unless the data resource itself has [custom conditions](https://developer.hashicorp.com/terraform/language/data-sources#custom-condition-checks).

So instead of having these transitive changes:

```
aws_vpc.this (*) <-- data.aws_vpc_peering_connections.bastion (*)

(*) = changes
```

with the `local`, we break the transitive changes:

```
aws_vpc.this (*) <-- local.vpc_id <-- data.aws_vpc_peering_connections.bastion
```

To me, we're good to close this issue then, since there's nothing to do on the `aws` provider side.

Thanks again for your help, @justinretzolk ! 🙏 👍
