### ISSUE TITLE
[Bug]: Cannot use logging_config on aws_lambda_function

### ISSUE THREAD

**Issue by HTV98** [hashicorp/terraform-provider-aws#35552]
### Terraform Core Version

1.1.2

### AWS Provider Version

5.34.0

### Affected Resource(s)

aws_lambda_function

### Expected Behavior

terraform plan successful with the change in logging_config changed.

### Actual Behavior

```
$ terraform112 plan
╷
│ Error: Unsupported block type
│
│   on lbd.tf line 8, in resource "aws_lambda_function" "test_lambda":
│    8:   logging_config {
│
│ Blocks of type "logging_config" are not expected here.
```

### Terraform Configuration Files

````
variable "lambda_function_name" {
  default = "lambda_function_name"
}

resource "aws_lambda_function" "test_lambda" {
  function_name = var.lambda_function_name
  role             = "arn:aws:iam::539756438693:role/alpha_int1_SQS_Role"
  logging_config {
    log_format = "Text"
  }

  depends_on = [
    aws_iam_role_policy_attachment.lambda_logs,
    aws_cloudwatch_log_group.example,
  ]
}


resource "aws_cloudwatch_log_group" "example" {
  name              = "/aws/lambda/${var.lambda_function_name}"
  retention_in_days = 14
}


data "aws_iam_policy_document" "lambda_logging" {
  statement {
    effect = "Allow"

    actions = [
      "logs:CreateLogGroup",
      "logs:CreateLogStream",
      "logs:PutLogEvents",
    ]

    resources = ["arn:aws:logs:*:*:*"]
  }
}

resource "aws_iam_policy" "lambda_logging" {
  name        = "lambda_logging"
  path        = "/"
  description = "IAM policy for logging from a lambda"
  policy      = data.aws_iam_policy_document.lambda_logging.json
}

resource "aws_iam_role_policy_attachment" "lambda_logs" {
  role       = "arn:aws:iam::539756438693:role/alpha_int1_SQS_Role"
  policy_arn = aws_iam_policy.lambda_logging.arn
}
````

### Steps to Reproduce

terraform112 plan

### Would you like to implement a fix?

None

**Comment by network-charles** [comment]
It's still not working. I don't know why the issue is closed.

**Comment by pavemolc-circunomics** [comment]
Is the issue fixed? I keep getting the same error, despite that the documentation says that this setting does exist.

**Comment by Mohsen240** [comment]
I am using terraform V1.7 this facing same error.

**Comment by sachasmart** [comment]
Yeap still not working!

**Comment by pdmtt** [comment]
Still not working in version 5.38.0:
![image](https://github.com/hashicorp/terraform-provider-aws/assets/8582596/c5e519bc-46c5-44a3-9cdc-ceb9f0b42a03)

Though planning shows `logging_config`:
![image](https://github.com/hashicorp/terraform-provider-aws/assets/8582596/c3a14930-84ef-4de2-b283-8df182d97f22)

**Comment by HTV98** [comment]
Hello,
Regarding my issue, I simply have an outdated AWS provider version. I just need to upgrade the AWS provider version. At the very least, it must be version 5.32.0.
