### ISSUE TITLE
[Bug]: AWS CloudSearch provider doesn't support field name "id"

### ISSUE THREAD

**Issue by MoienTajik** [hashicorp/terraform-provider-aws#35564]
### Terraform Core Version

1.7.1

### AWS Provider Version

5.34.0

### Affected Resource(s)

aws_cloudsearch_domain

### Expected Behavior

In a domain, I specified an index_field with name "id". This should have created a new regular field in my cloud search domain.

### Actual Behavior

 Error: "index_field.0.name" must begin with a letter and be at least 3 and no more than 64 characters long

### Terraform Configuration Files

```terraform
resource "aws_cloudsearch_domain" "main" {
  name = "${var.name}-${var.environment}"

  index_field {
    name = "id"
    type = "int"
    return = true
    facet = true
    sort = false
    search = false
  }

  scaling_parameters {
    desired_instance_type     = var.instance_type
    desired_partition_count   = 1
    desired_replication_count = 1
  }
}
```

### Steps to Reproduce

- Configure connectivity to your AWS account
- Run `terraform init`
- Run `terraform plan` with the above configuration

### Important Factoids

The issue stems from the Regex at [this line](https://github.com/hashicorp/terraform-provider-aws/blob/c4cf1a6b9dc373238686548319b3d253d6da8c98/internal/service/cloudsearch/domain.go#L499).

According to the AWS developer guide [here](https://docs.aws.amazon.com/cloudsearch/latest/developerguide/configuring-index-fields.html), Terraform's current behavior is correct. However, if you attempt to create a new index field in a CloudSearch domain using the AWS Console and name the index field "id" or any other name shorter than 3 characters, it doesn't fail. This contradicts both the AWS documentation and Terraform's behavior.

>Regular index field names must start with a letter and be at least 3 but no more than 64 characters long. The permissible characters are: a-z (lower-case letters), 0-9, and _ (underscore). The name 'score' is reserved and cannot be used as a field name. All field and expression names must be unique.

### References

- [Configuring Index Fields for an Amazon CloudSearch Domain](https://docs.aws.amazon.com/cloudsearch/latest/developerguide/configuring-index-fields.html)

### Would you like to implement a fix?

Yes

**Comment by ulyssedsn** [comment]
Hey @MoienTajik! We are also facing the same issue that you did. I opened a PR to fix this. Can you and your team promote this fix by adding a 👍 to the description of my PR #38509 
Thanks so much in advance for your collaboration!
