### ISSUE TITLE
[Docs]: Document 'multi_az_with_standby_enabled' Feature in Docs

### ISSUE THREAD

**Issue by Sarangan0219** [hashicorp/terraform-provider-aws#35578]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/5.34.0/docs/resources/opensearch_domain#cluster_config

### Issue Description

It has come to my attention that the feature `multi_az_with_standby_enabled` is actively implemented in the codebase, but there is no corresponding documentation in the project's documentation resources. This feature is crucial for understanding the high availability setup and should be properly documented for clarity and ease of use.

### References

https://github.com/mikekinlock/terraform-provider-aws/blob/main/internal/service/opensearch/domain.go#L274C8-L274C37

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
Confirm in the official repo that the `multi_az_with_standby_enabled` is supported, will update the doc accordingly.
