### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by okonon** [hashicorp/terraform-provider-aws#35588]
### Terraform Core Version

v1.7.2

### AWS Provider Version

aws v4.64.0

### Affected Resource(s)

I have following resource:
```hcl
resource "aws_cognito_identity_provider" "this" {
  user_pool_id  = aws_cognito_user_pool.pool.id
  provider_name = "bh-${terraform.workspace}-saml-sso"
  provider_type = "SAML"

  provider_details = {
    IDPSignout            = "true"
    MetadataURL           = var.cognito_bh_sso_metadata_url
    SLORedirectBindingURI = var.cognito_bh_sso_login_url
    SSORedirectBindingURI = var.cognito_bh_sso_login_url
  }

  attribute_mapping = {
    "custom:Groups" = "http://schemas.microsoft.com/ws/2008/06/identity/claims/groups"
    email           = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
    family_name     = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname"
    given_name      = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname"
    name            = "http://schemas.microsoft.com/identity/claims/displayname"
  }
}
```

### Expected Behavior

no changes should be detected 

### Actual Behavior

for some reason out of the blue now when i run `terraform apply` following changes are detected:
```
# module.cognito-main-user-auth.aws_cognito_identity_provider.this will be updated in-place
  ~ resource "aws_cognito_identity_provider" "this" {
        id                = "us-east-1_RplR9wClp:bh-dev-saml-sso"
      ~ provider_details  = {
          - "ActiveEncryptionCertificate" = "MIICvTCCAaWgAwIB......" -> null
            # (4 unchanged elements hidden)
        }
        # (5 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Relevant Error/Panic Output Snippet

```shell
N/A
```

### Terraform Configuration Files

n/a

### Steps to Reproduce

n/a

### Debug Output

n/a

### Panic Output

n/a

### Would you like to implement a fix?

None

**Comment by finwo** [comment]
After testing on a non-production-environment, running apply does not brick the provider.

While annoying due to a whole lot of output, in our environment this seems ok work around (do keep reading the changes before saying yes though).

**Comment by Arlington1985** [comment]
it's also happening with `terraform=1.6.5` and `aws-provider~> 4.56.0`

**Comment by jeff-carey** [comment]
I have a PR open for our Terraform code which wrote a plan to a comment on that PR a couple of days ago, which did not exhibit that behavior. Running the PR workflow again today (the PR is still open) **_with the exact same version of Terraform and the AWS provider_** produces a different plan which does exhibit this behavior. There seems to have been a change underlying both Terraform and the AWS provider, presumably within the AWS API.

**Comment by jpiazza35** [comment]
happening the same in terraform 1.4.6

**Comment by kclarkey** [comment]
Seems functionality made it out before the [Docs](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-saml-idp.html)/[Announcement](https://aws.amazon.com/about-aws/whats-new/2024/02/amazon-cognito-signing-encryption-identity-provider-initiated-sso/) which just posted.

**Comment by fabio-sgro-assistdigital** [comment]
happening also with terraform v1.5(.7) and aws v5.32.1

**Comment by jpiazza35** [comment]
should we wait for something , should we add something in the terrsform code , can we merge the code without issues?

**Comment by Arlington1985** [comment]
> should we wait for something , should we add something in the terrsform code , can we merge the code without issues?

Yes, it's safe to run terraform apply

**Comment by jeff-carey** [comment]
Could someone more explicitly explain what has happened here? Why is it safe to apply? Is there a reason other than "we tried it and it didn't seem to cause any problems"?

A workaround is to explicitly specify the value for `ActiveEncryptionCertificate`, as in...

```
provider_details = {
  ...

  ActiveEncryptionCertificate = "put the certificate value observed in your plan here"
}
```

That'll result in a plan with no changes to that value.

**Comment by Arlington1985** [comment]
It's a new feature of AWS which currently not supported by terraform provider. As its readonly value, there is also no way to update it, even terraform tries to do that, nothing changes. That's why you can simply ignore this drift

**Comment by mar-pan** [comment]
Simple fix   
```
lifecycle {
    ignore_changes = [provider_details["ActiveEncryptionCertificate"]]
  }
```

**Comment by jeff-carey** [comment]
> Simple fix
> 
> ```
> lifecycle {
>     ignore_changes = [provider_details["ActiveEncryptionCertificate"]]
>   }
> ```

Thanks for that, @mar-pan! I had already tried `ignore_changes` with no luck, but my syntax must have been wrong (without generating any errors). Yours works.
