### ISSUE TITLE
Add Policy-Min-TLS-1-2-PFS-2023-10 cert to AWS Opensearch Documentation

### ISSUE THREAD

**Issue by rmccarthy-ellevation** [hashicorp/terraform-provider-aws#35580]
### Description

According to [AWS docs](https://docs.aws.amazon.com/opensearch-service/latest/APIReference/API_DomainEndpointOptions.html) the Opensearch endpoint can have 3 different TLS Sec Policies: `Valid Values: Policy-Min-TLS-1-0-2019-07 | Policy-Min-TLS-1-2-2019-07 | Policy-Min-TLS-1-2-PFS-2023-10`.

The [TF Opensearch docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearch_domain#domain_endpoint_options) only list: `Valid values: Policy-Min-TLS-1-0-2019-07 and Policy-Min-TLS-1-2-2019-07`. 

Could the documentation be update? Thanks!

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
I confirmed that the resource supports all 3 values with the current version of the provider, so this is a doc issue. Following other conventions, I will update the doc to point to the AWS documentation for the list of valid values to avoid the doc getting out of date going forward.
