### ISSUE TITLE
Support custom build image in aws_amplify_app resource

### ISSUE THREAD

**Issue by e-simpson** [hashicorp/terraform-provider-aws#35609]
### Description

As of Jan. 2024 there is no way to set a custom build image in the aws_amplify_app resource. 

Recently, the amplify team added support for the `Amazon Linux:2023` build image that resolves some issues using Live Updates and Node 18. However, it’s not set by default. Being able to set it in Terraform would be great.

### Affected Resource(s) and/or Data Source(s)

aws_amplify_app

### Potential Terraform Configuration

```terraform
resource “aws_amplify_app” “amplify” {
   build_image = “Amazon Linux:2023”
}
```

### References

https://github.com/aws-amplify/amplify-hosting/issues/3773#issuecomment-1811288919

### Would you like to implement a fix?

No

**Comment by acwwat** [comment]
Looking at the [App](https://docs.aws.amazon.com/amplify/latest/APIReference/API_App.html), there isn't any setting for the build image in the AWS API, thus there's no settings that the provider can use. However, I noticed that the custom image is set in the `_CUSTOM_IMAGE` environment variable. Other build image settings like `_BUILD_TIMEOUT` and `_LIVE_UPDATES` also seem to be captured that way. Refer to the sample screenshot and output from `aws amplify get-app` below.

Perhaps setting these environment variables using the [`environment_variables`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/amplify_app#environment_variables) argument in the `aws_amplify_app` resource is the way to go. Please try it out and update this ticket with the results. Thanks.

![image](https://github.com/hashicorp/terraform-provider-aws/assets/5210117/036554a2-0fa4-47f0-9098-69c453ffbdcd)

```
$ aws amplify get-app --app-id <redacted>
{
    "app": {
        "appId": "<redacted>",
        "appArn": "<redacted>",
        "name": "test",
        "tags": {},
        "repository": "<redacted>",
        "platform": "WEB",
        "createTime": "2024-02-03T21:46:00.787000+00:00",
        "updateTime": "2024-02-03T21:53:35.992000+00:00",
        "iamServiceRoleArn": "<redacted>",
        "environmentVariables": {
            "AMPLIFY_DIFF_DEPLOY": "false",
            "AMPLIFY_MONOREPO_APP_ROOT": "test-frontend",
            "_BUILD_TIMEOUT": "51",
            "_CUSTOM_IMAGE": "amplify:al2023",
            "_LIVE_UPDATES": "[{\"pkg\":\"@aws-amplify/cli\",\"type\":\"npm\",\"version\":\"latest\"}]"
        },
        "defaultDomain": "<redacted>.amplifyapp.com",
        "enableBranchAutoBuild": false,
        "enableBranchAutoDeletion": false,
        "enableBasicAuth": false,
        "customRules": [],
        "productionBranch": {
            "lastDeployTime": "2024-02-03T21:54:40.169000+00:00",
            "status": "FAILED",
            "branchName": "main"
        },
        "buildSpec": "version: 1\napplications:\n  - frontend:\n      phases:\n        preBuild:\n          commands:\n            - npm ci\n        build:\n          commands:\n            - npm run build\n      artifacts:\n        baseDirectory: dist\n        files:\n          - '**/*'\n      cache:\n        paths:\n          - node_modules/**/*\n    appRoot: test-frontend\n",
        "customHeaders": "",
        "enableAutoBranchCreation": false,
        "repositoryCloneMethod": "TOKEN"
    }
}
```

**Comment by e-simpson** [comment]
Great to hear. Thanks for the detailed response @acwwat. Setting the `_CUSTOM_IMAGE` env variable to `"amplify:al2023"` in my `"aws_amplify_app"` resource worked perfectly.

```
resource "aws_amplify_app" "amplify" {
...
   environment_variables: {
      _CUSTOM_IMAGE: "amplify:al2023"
   }
}
```

![image](https://github.com/hashicorp/terraform-provider-aws/assets/25159851/eb409a0a-5b1e-46cc-a7da-400cb56e621c)
