### ISSUE TITLE
[Enhancement]: add support for assume_role in terraform_remote_state s3 backend

### ISSUE THREAD

**Issue by leonjyq** [hashicorp/terraform-provider-aws#35604]
### Description

Current data resource **terraform_remote_state** doesn't attribute for **assume_role**. We would like to use this secure way to query remote state.
![image](https://github.com/hashicorp/terraform-provider-aws/assets/5651983/1bb1980a-7ffe-4c60-bf46-286738d5f645)

### Affected Resource(s) and/or Data Source(s)

terraform_remote_state

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @leonjyq 👋 Thank you for taking the time to raise this! Issues with the s3 backend should instead be directed to the [Terraform Core repository](https://github.com/hashicorp/terraform), however, I'd be remiss if I didn't mention that I'd expect this to work in most of the more recent versions of Terraform, so it may be worth checking your version as well. With that in mind, I'll be closing this issue.
