### ISSUE TITLE
[Enhancement]: Add nodejs20.x and java21 to runtime of aws_lambda_function

### ISSUE THREAD

**Issue by tibistibi** [hashicorp/terraform-provider-aws#35613]
### Description

This will give me the following error:

`resource "aws_lambda_function" "lincSafe-AES-GET" {
  # If the file is not in the current working directory you will need to include a
  # path.module in the filename.
  filename         = "lincSafe-AES-GET.zip"
  function_name    = "lincSafe-AES-GET"
  role             = aws_iam_role.lincSafe-AES-role.arn
  handler          = "index.handler"
  source_code_hash = data.archive_file.lambda.output_base64sha256
  runtime          = "nodejs20.x"
}`

` Error: expected runtime to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x nodejs16.x java8 java8.al2 java11 python2.7 python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 dotnet6 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2 nodejs18.x], got nodejs20.x`

Same goes for java21

But AWS does support them:

https://docs.aws.amazon.com/lambda/latest/api/API_CreateFunction.html#SSS-CreateFunction-request-Runtime
See the resource list:

`Valid Values: nodejs | nodejs4.3 | nodejs6.10 | nodejs8.10 | nodejs10.x | nodejs12.x | nodejs14.x | nodejs16.x | java8 | java8.al2 | java11 | python2.7 | python3.6 | python3.7 | python3.8 | python3.9 | dotnetcore1.0 | dotnetcore2.0 | dotnetcore2.1 | dotnetcore3.1 | dotnet6 | nodejs4.3-edge | go1.x | ruby2.5 | ruby2.7 | provided | provided.al2 | nodejs18.x | python3.10 | java17 | ruby3.2 | python3.11 | nodejs20.x | provided.al2023 | python3.12 | java21`

Please update the allowed list

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
Node.js v20 support was added via #34401 which went into v5.26.0, while Java v21 support was added via #34476 which went into v5.27.0. Please verify whether you are using v5.27.0 or later of the provider.

**Comment by tibistibi** [comment]
a thanks i use the latest from ubuntu apt get. let me check

`terraform -v
Terraform v1.7.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.4.2
+ provider registry.terraform.io/hashicorp/aws v4.47.0
`
I assume it is the aws 4.47.0 which is old. 
Apt get uses this resource **apt-cache policy**

`https://apt.releases.hashicorp.com jammy/main i386 Packages
     release o=Artifactory,a=jammy,n=jammy,l=Artifactory,c=main,b=i386
     origin apt.releases.hashicorp.com
`

**Comment by tibistibi** [comment]
indeed is see here the latest version is 5.35:
https://releases.hashicorp.com/terraform-provider-aws/

I updated the script to use the newest version. Thanks for the info and sorry to have taken the time
