### ISSUE TITLE
[Bug]: aws_s3_bucket_notification fmt failing with missing filter_suffix / filter_prefix

### ISSUE THREAD

**Issue by sfc-gh-praveensundaram** [hashicorp/terraform-provider-aws#35635]
### Terraform Core Version

1.7.2

### AWS Provider Version

5.35.0

### Affected Resource(s)

Terraform format returns error code 3 when there is no filter_suffix / filter_prefix attached to aws_s3_bucket_notification. 

```shell
$ terraform fmt -check
bckt_ntfy.tf
$ echo $?
3

resource "aws_s3_bucket_notification" "raw_data" {
  for_each = { for index, s in local.lz[var.landing_zone].bucket_suffixes : index => s }
  bucket   = aws_s3_bucket.raw_data[each.key].id
  queue {
    queue_arn     = data.aws_ssm_parameter.app_snowflake_snowpipe_sqs_arn.value
    events        = ["s3:ObjectCreated:*"]
    # filter_suffix = "AWSLogs/"
  }
}__
```

### Expected Behavior

As filter_suffix / filter_prefix are optional for aws_s3_bucket_notification missing this should not be be an error

### Actual Behavior

Error code 3 returned

### Terraform Configuration Files

```terraform
resource "aws_s3_bucket_notification" "raw_data" {
  for_each = { for index, s in local.lz[var.landing_zone].bucket_suffixes : index => s }
  bucket   = aws_s3_bucket.raw_data[each.key].id
  queue {
    queue_arn     = data.aws_ssm_parameter.app_snowflake_snowpipe_sqs_arn.value
    events        = ["s3:ObjectCreated:*"]
    # filter_suffix = "AWSLogs/"
  }
}
```

### Steps to Reproduce

$ terraform fmt -check
bckt_ntfy.tf
$ echo $?
3

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @sfc-gh-praveensundaram 👋 Thanks for taking the time to raise this! I wasn't able to reproduce this. Can you supply debug logging (redacted as necessary) to help whoever looks into this?

Reproduction attempt:

```console
$ cat main.tf
resource "aws_s3_bucket_notification" "raw_data" {
  for_each = { for index, s in local.lz[var.landing_zone].bucket_suffixes : index => s }
  bucket   = aws_s3_bucket.raw_data[each.key].id
  queue {
    queue_arn = data.aws_ssm_parameter.app_snowflake_snowpipe_sqs_arn.value
    events    = ["s3:ObjectCreated:*"]
    # filter_suffix = "AWSLogs/"
  }
}

$ terraform fmt -check && echo "exit code is: "$?
exit code is: 0
```

**Comment by justinretzolk** [comment]
Hey @sfc-gh-praveensundaram 👋 I wanted to follow up here to see if you were still encountering this. If you are, are you able to supply debug logging, since we're not able to reproduce?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
