### ISSUE TITLE
[Enhancement]: Ability to switch from cluster mode disabled to compatible then on

### ISSUE THREAD

**Issue by mwheeler-ep** [hashicorp/terraform-provider-aws#35636]
### Description

The advice to enable cluster mode on a `aws_elasticache_replication_group` is to set the parameter group to one that has cluster mode enabled such as ones ending in `.cluster.on`, however this doesn't permit upgrading a cluster to cluster mode. 
```
The parameter cluster-enabled has a different value in the requested parameter group than the current parameter group. This parameter value cannot be changed for a cache cluster
```
The upgrade can be performed in the console (tested), cli or via the API (untested but documented here https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_ModifyReplicationGroup.html) by switching the cluster to compatible mode followed by on.

It would be good to be able to control the attribute so that migrations to cluster mode can be performed using terraform.

It's possible that I might be missing something that this option already exists through another mechanism? I believe the cluster_mode block was removed in favour of direct arguments. I don't think a block needs to be implemented to obtain this functionality.

### Affected Resource(s) and/or Data Source(s)

aws_elasticache_replication_group

### Potential Terraform Configuration

```terraform
resource "aws_elasticache_replication_group" "example" {
  num_node_groups            = 1
  replicas_per_node_group    = 2
  parameter_group_name       = "default.redis7.cluster.on"
  cluster_mode               = "compatible"
}
```

### References

https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_ModifyReplicationGroup.html#ClusterMode
https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ModifyReplicationGroupInput

### Would you like to implement a fix?

No

**Comment by AlexeyRaga** [comment]
Same issue, hope for a fix ;)
