### ISSUE TITLE
[Docs]: Elasticache Serverless Maximum shows as 5 but requires a value between 1000 and 15000000

### ISSUE THREAD

**Issue by zelahi** [hashicorp/terraform-provider-aws#35648]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_serverless_cache#maximum

### Description

When following the example
│ operation error ElastiCache: CreateServerlessCache, https response error StatusCode: 400, RequestID: xxxxxxxxx, InvalidParameterValue: Invalid value for ECPUPerSecond limit. Must
│ be between 1000 and 15000000. You can set the value to zero to remove the limit.

In the reference here: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_serverless_cache I see that it shows 5.  Although I eventually changed it and it was not too bad, I can update this if it would help 

### Would you like to implement a fix?

Yes

**Comment by zelahi** [comment]
I could also update the docs if people are okay with this

**Comment by justinretzolk** [comment]
If you're up for updating the documentation, we'd gladly take a pull request to do so @zelahi! Thank you for offering 🙂

**Comment by emdneto** [comment]
Hi @justinretzolk Is anyone still working on this fix? otherwise I can handle it. I'm using the aws_serverless_cache resource and the example from the docs isn't working.
