### ISSUE TITLE
[Enhancement]: Support filtering by tags for aws_ec2_transit_gateway Data source

### ISSUE THREAD

**Issue by AliAllomani** [hashicorp/terraform-provider-aws#35649]
### Description

Adding the support to filter transit gateways by tags for aws_ec2_transit_gateway Data source would be beneficial for use-cases where filtering by the available options supported by AWS API is not sufficient 

Filtering by tags can be performed on terraform provider level

### Affected Resource(s) and/or Data Source(s)

* data.aws_ec2_transit_gateway

### Potential Terraform Configuration

```terraform
data "aws_ec2_transit_gateway" "example" {
  tags {
     Name = "tgw"
     Project = "MyProject"
  }
}
```

### Would you like to implement a fix?

None

**Comment by djsd123** [comment]
💯%

I've not tried this yet but would specifying the tag in the filter argument suffice as a workaround?

Like so:
```
data "aws_ec2_transit_gateway" "tgw" {
  filter {
    name   = "tag:Name"
    values = ["tgw-prod"]
  }
}
```

Or 
```
data "aws_ec2_transit_gateway" "tgw" {
  filter {
    name   = "tag:costcode"
    values = ["1234","4321"]
  }
}
```

**Comment by AliAllomani** [comment]
> data "aws_ec2_transit_gateway" "tgw" {
>   filter {
>     name   = "tag:Name"
>     values = ["tgw-prod"]
>   }
> }

Thanks @djsd123 , I have tested it and that works fine !

interestingly the usage of `tag:` as a filter name is not mentioned in AWS docs for `DescribeTransitGateways`

* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeTransitGateways.html
* https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-transit-gateways.html

```bash
aws ec2 describe-transit-gateways --filters "Name=tag:Name,Values=tgw-prod"
```

With that, I'm closing this issue as the current filters argument is sufficient for such use-case
