### ISSUE TITLE
[Bug]: aws_elasticache_serverless_cache: ecpu_per_second without a limit block count changed from 1 to 0.

### ISSUE THREAD

**Issue by maxvisser** [hashicorp/terraform-provider-aws#35660]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.35.0

### Affected Resource(s)

aws_elasticache_serverless_cache

### Expected Behavior

Setting ecpu to 0 would mean unlimited

### Actual Behavior

Its set it to unlimited but I run into an error after apply

### Relevant Error/Panic Output Snippet

```shell
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to aws_elasticache_serverless_cache.nhb-redis-staging-1, provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected new value:
│ .cache_usage_limits[0].ecpu_per_second: block count changed from 1 to 0.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Terraform Configuration Files

```
resource "aws_elasticache_serverless_cache" "xx-redis-staging-1" {
  engine = "redis"
  name   = "xx-redis-staging-1"
  cache_usage_limits {
    data_storage {
      maximum = 5
      unit    = "GB"
    }
    ecpu_per_second {
      maximum = 0
    }
  }
  daily_snapshot_time      = "09:00"
  description              = "Redis for xx Staging"
  major_engine_version     = "7"
  snapshot_retention_limit = 1
  security_group_ids = [aws_security_group.elasticache_sg.id]
  subnet_ids = ["subnet-xx","subnet-xx", "subnet-xx"]
  user_group_id = aws_elasticache_user_group.nhbGroup.user_group_id
}
```

### Steps to Reproduce

apply a aws_elasticache_serverless_cache resource with
    ecpu_per_second {
      maximum = 0
    }

### Would you like to implement a fix?

None

**Comment by meetreks** [comment]
I checked in Console but it does not allow me to put a 0 in Max 
This is thee error I am getting on the console 

ElastiCache Processing Units (ECPUs) limit is out of range.
You can set a maximum limit between 1,000 and 15,000,000 ECPUs per second.

**Comment by mshahmoradi87** [comment]
> I checked in Console but it does not allow me to put a 0 in Max This is thee error I am getting on the console
> 
> ElastiCache Processing Units (ECPUs) limit is out of range. You can set a maximum limit between 1,000 and 15,000,000 ECPUs per second.

true, but if possible with 0, module should not try to set it, as a workaround I have defined this block like below:
```
  dynamic "cache_usage_limits" {
    for_each = (var.max_storage_gb >= 1 || var.max_epu_per_second >= 1000) ? [1] : []

    content {
      dynamic "data_storage" {
        for_each = var.max_storage_gb >= 1 ? [1] : []
        content {
          maximum = var.max_storage_gb
          unit    = "GB"
        }
      }

      dynamic "ecpu_per_second" {
        for_each = var.max_epu_per_second >= 1000 ? [1] : []
        content {
          maximum = var.max_epu_per_second
        }
      }
    }
  }
  ```

**Comment by meetreks** [comment]
If you want I can put a validation which will error on Plan stage, is this Ok @mshahmoradi87

**Comment by meetreks** [comment]
Added limits as mentioned above

**Comment by stegosaurus21** [comment]
Hi, I am also encountering this issue. According to [AWS CLI documentation](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Scaling.html), setting these values to zero seems to be the intended way to indicate unlimited resource cap.

In general, there doesn't seem to be a way in the module at the moment to set only a ECPU or data storage limit without setting the other as well.

**Comment by maxvisser** [comment]
> Hi, I am also encountering this issue. According to [AWS CLI documentation](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Scaling.html), setting these values to zero seems to be the intended way to indicate an unlimited resource cap.
> 
> In general, there doesn't seem to be a way in the module at the moment to set only a ECPU or data storage limit without setting the other as well.

This was indeed the issue that I was having too. Not sure with the current validation fix how to set it to unlimited..
