### ISSUE TITLE
[Bug]: Inconsistent Plan error when updating description for aws_wafv2_web_acl resource

### ISSUE THREAD

**Issue by brgao2** [hashicorp/terraform-provider-aws#35699]
### Terraform Core Version

1.1.8

### AWS Provider Version

5.34.0

### Affected Resource(s)

aws_wafv2_web_acl produce an inconsistent final plan when trying to update the creator tags. I attached the plan below because it is so large, and at the bottom the error message "This is a bug in the provider, which should be reported in the provider's own issue tracker. " shows up. 

### Expected Behavior

Changing description for aws_wafv2_web_acl should succeed

### Actual Behavior

Changing description for aws_wafv2_web_acl throws inconsistent plan error

### Relevant Error/Panic Output Snippet

```shell
Error: Provider produced inconsistent final plan When expanding the plan for aws_wafv2_web_acl.alb_ext_waf[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .rule
```

### Terraform Configuration Files

Attaching a zip file with the configuration for wafv2 resource and full debug logs for terraform init and apply that is encrypted with the haschicorp gpg public key.
[aws_waf_bug_repro.zip](https://github.com/hashicorp/terraform-provider-aws/files/14200080/aws_waf_bug_repro.zip)

### Steps to Reproduce

Create a aws_wafv2_web_acl and then try to change the description, terraform apply will throw the inconsistent plan error

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
