### ISSUE TITLE
[Docs]: Wrong default value for `rotate_immediatley` argument for the resource aws_secretsmanager_secret_rotation

### ISSUE THREAD

**Issue by obounaim** [hashicorp/terraform-provider-aws#35702]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/secretsmanager_secret_rotation#rotate_immediately

### Description

The default value of the `rotate_immediately` argument is set to `True`, but the documentation incorrectly states that it is set to `False`. 
 
Thanks for reporting @MagikHands

### References

PR: https://github.com/hashicorp/terraform-provider-aws/pull/35105
Issue: https://github.com/hashicorp/terraform-provider-aws/issues/34961

Changes: https://github.com/hashicorp/terraform-provider-aws/pull/35105/files#diff-df175ef08fe01b7603aecf59015e992b579428f7ed267c86adf111fa2114aa64

### Would you like to implement a fix?

None

**Comment by rama280290** [comment]
Can i update this document?
