### ISSUE TITLE
[New Resource]: CloudWatch Network Monitor

### ISSUE THREAD

**Issue by ggaugain** [hashicorp/terraform-provider-aws#35705]
### Description

[CloudWatch Network Monitor](https://aws.amazon.com/about-aws/whats-new/2023/12/amazon-cloudwatch-network-monitor-generally-available/) was released a few week ago to Generally Available. It would be nice to have that available in the AWS Terraform provider, for now I have created it manually through the web console.

### Requested Resource(s) and/or Data Source(s)

- aws_cloudwatch_network_monitor

### Potential Terraform Configuration

```terraform
resource "aws_cloudwatch_network_monitor" "check1" {
  name               = "CheckDC1"
  aggregation_period = 30

  subnet_id   = list[...]
  destination = map(string)

  tags            = map(string)
  add_tag_to_prob = true
}
```

### References

https://aws.amazon.com/about-aws/whats-new/2023/12/amazon-cloudwatch-network-monitor-generally-available/
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/nw-monitor-how-it-works.html

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@ggaugain Thanks for raising this issue.
It has already been noticed in #35342. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
