### ISSUE TITLE
[Bug]: sporadic errors in aws_eks_access_policy_association

### ISSUE THREAD

**Issue by pdeva** [hashicorp/terraform-provider-aws#35728]
### Terraform Core Version

1.7.3

### AWS Provider Version

5.36.0

### Affected Resource(s)

- aws_eks_access_policy_association

### Expected Behavior

I am associating AWS SSO created IAM roles to eks access entries using code given below. if this code is going to fail due to `principal_arn` not being found, it should fail during the planning phase itself. it should never be the case that `principal_arn` is found during planning and i get an error of it not being found during application phase, especially if no other changes to aws is made during this time.

### Actual Behavior

Here is a screenshot of this full terraform run. you can see all the `policyArn` this fails on was indeed inferred correctly in the data sources. 
 
![app terraform io_app_astradot_workspaces_staging_runs_run-cJFRJ8CsYzqVbYcL](https://github.com/hashicorp/terraform-provider-aws/assets/3190176/4a3dbf58-0b30-4fd8-9014-0fc28f6317cf)

on just re-running terraform, without making any changes, the errors go away and apply finishes.  its unclear what causes the code to fail in the first place and why it suddenly works next time

![app terraform io_app_astradot_workspaces_staging_runs_run-oWfT14Pchj4z5M8j](https://github.com/hashicorp/terraform-provider-aws/assets/3190176/333c73cc-dc99-4f65-92b3-2d8cc94ce148)

### Terraform Configuration Files

```tf
terraform {
  required_version = ">= 1.0"
  cloud {
    workspaces {
      name = "staging"
    }
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
 
  }
}
```

### Steps to Reproduce

```tf
data "aws_iam_roles" "roles" {
  name_regex  = "AWSReservedSSO_${var.sso_permset_name}_.*"
  path_prefix = "/aws-reserved/sso.amazonaws.com/"
}

locals {
  principal_arn = one(data.aws_iam_roles.roles.arns)
}

resource "aws_eks_access_entry" "this" {
  cluster_name      = var.eks_cluster_name
  principal_arn     = local.principal_arn
  kubernetes_groups = var.kubernetes_groups
}

resource "aws_eks_access_policy_association" "this" {
  count         = length(var.policy_arn) > 0 ? 1 : 0
  cluster_name  = var.eks_cluster_name
  principal_arn = local.principal_arn
  policy_arn    = var.policy_arn
  access_scope {
    type = "cluster"
  }
}

```

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/35535.

**Comment by pdeva** [comment]
so in the runs mentioned above, the roles in question were not updated at all. thats why a data source is used for the role instead of a resource
