### ISSUE TITLE
[Enhancement]: configuring IMDSv2 in aws_emr_cluster resource

### ISSUE THREAD

**Issue by rifler** [hashicorp/terraform-provider-aws#35751]
### Description

Hello!

I'm using `aws_emr_cluster` resource to run EMR cluster. Unfortunately I cannot find any options to set `IMDSv2: required` to underlying EC2 instances (master/core/etc)

### Affected Resource(s) and/or Data Source(s)

* aws_emr_cluster

### Potential Terraform Configuration

```terraform
resource "aws_emr_cluster" "trino_compute" {
  name = 'xxx'
  // ...
  ec2_attributes {
    metadata_options {
      http_tokens = "required"
      http_endpoints = "enabled"
    }
  }
}
```

### Would you like to implement a fix?

None

**Comment by jamesdehart** [comment]
@rifler I happen to come across this issue and found a solution.

```hcl
resource "aws_emr_security_configuration" "this" {
  name_prefix = "emr-sec-config"

  configuration = <<EOF
{
  "EncryptionConfiguration": {...},
  "InstanceMetadataServiceConfiguration" : {
    "MinimumInstanceMetadataServiceVersion": 2,
    "HttpPutResponseHopLimit": 1
   }
}
EOF
}
```

[AWS EMR Security Configuration](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-create-security-configuration.html#emr-security-configuration-imdsv2)

I hope this helps you. This would not be a Terraform bug. Might be nice to add some docs.

**Comment by rifler** [comment]
@jamesdehart omg, thanks a lot! Going to try it soon

**Comment by rifler** [comment]
it works
