### ISSUE TITLE
[Docs]:  aws_instance market_type is actually a required parameter when spot_options is defined 

### ISSUE THREAD

**Issue by JohSchillerEmnify** [hashicorp/terraform-provider-aws#35770]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#market_type

### Description

market_type is no longer an optional parameter, apply fails when trying to apply [the example for spot instances from terraform documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#spot-instance-example) 

Error: 
```hcl
│ Error: creating EC2 Instance: MissingParameter: The request must contain the parameter MarketType.
│ 	status code: 400, request id: `redacted`
│ 
│   with aws_instance.this,
│   on main.tf line 14, in resource "aws_instance" "this":
│   14: resource "aws_instance" "this" {
```

- When `spot_options` are defined, market_type must be set, else executions fails (Plan does not fail -> Expected?)
- When `instance_market_options` is empty, no error occurs.
- When `instance_market_options` are left out completely, no error occurs.
---

## How to reproduce: 
Using 
Terraform Version 1.7.3
terraform-provider-aws Version 5.36.0

1. Copy [the example for spot instances from terraform documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#spot-instance-example)
2. Add terraform block
3. Execute init and apply 
4. Upon apply Instance creation fails with the error mentioned above

### Would you like to implement a fix?

Yes

**Comment by HubbardHarvey3** [comment]
I would like to work on this issue.  
Looking at the documentation, the default for the market_type attribute is "spot".  
My initial approach is to update the market_type schema definition on line 401 of ec2_instance.go by removing "Computed" and adding a "Default" value of "spot".

Let me know if there is a better way.  If that sounds good, I will work on getting it tested and have a PR created this week.
