### ISSUE TITLE
[New Resource]: aws_verifiedpermissions_identity_source 

### ISSUE THREAD

**Issue by peterehik-px** [hashicorp/terraform-provider-aws#35801]
### Description

Add Verified Permission identity source

### Requested Resource(s) and/or Data Source(s)

* aws_verifiedpermission_identity_source

### Potential Terraform Configuration

```terraform
resource "aws_verifiedpermissions_identity_source" "test" {
  policy_store_id = aws_verifiedpermissions_identity_source.test.id

  configuration {
    cognito_user_pool_configuration {
      user_pool_arn = aws_cognito_user_pool.test.arn
      client_ids = []
    }
  }

  principal_entity_type = ""
  
}
```

### References

Relates https://github.com/hashicorp/terraform-provider-aws/issues/32158.

* https://docs.aws.amazon.com/verifiedpermissions/latest/userguide/identity-sources_create.html
* https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_CreateIdentitySource.html

### Would you like to implement a fix?

None

**Comment by hanoj-budime** [comment]
Hi team,

Any thoughts on this road too ?
@ewbankkit
@justinretzolk
@johnsonaj

**Comment by hanoj-budime** [comment]
Hi team,

Just a note : For group membership.. Token claims..
https://docs.aws.amazon.com/cli/latest/reference/verifiedpermissions/create-identity-source.html

![image](https://github.com/hashicorp/terraform-provider-aws/assets/53425981/08f2a102-0bde-4910-8e2f-c2dcc8f1f0ac)

**Comment by hanoj-budime** [comment]
Any updates ?

**Comment by hanoj-budime** [comment]
Hey.. Any updates ?

Include recent changes as well.
``` tf
resource "aws_verifiedpermissions_identity_source" "test" {
  policy_store_id = aws_verifiedpermissions_identity_source.test.id

  configuration {
    cognito_user_pool_configuration {
      user_pool_arn = aws_cognito_user_pool.test.arn
      client_ids = []
      groupConfiguration {
       groupEntityType = ""
      }
    }
  }
  principal_entity_type = ""
}
```

**Comment by cbarensfeld** [comment]
I could really use this one, last piece for full avp deployment through terraform

**Comment by DanielRieske** [comment]
Seeing that this is the last resource needed by the community for this service, I'll happily pick this up and will add the PR shortly.
