### ISSUE TITLE
[Docs]: Mutual TLS Authentication incorrect aws_lb_listener resource definition 

### ISSUE THREAD

**Issue by nithumohandas** [hashicorp/terraform-provider-aws#35809]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener#mutual-tls-authentication

### Description

the resource definition for aws_lb_listener in provided document is incorrect. mutual_authentication is mentioned as an argument type ( with = ) instead of block type

### Would you like to implement a fix?

None

**Comment by rama280290** [comment]
I can work on this
