### ISSUE TITLE
[Bug]: aws_elasticsearch_domain_policy Error: setting Elasticsearch Domain Policy (): ValidationException: A change/update is in progress. Please wait for it to complete before requesting another change

### ISSUE THREAD

**Issue by scott-doyland-burrows** [hashicorp/terraform-provider-aws#35811]
### Terraform Core Version

1.7.3

### AWS Provider Version

5.29.0

### Affected Resource(s)

```aws_elasticsearch_domain``` is created and then triggers ```aws_elasticsearch_domain```, but the second resource fails with:

```
│ Error: setting Elasticsearch Domain Policy (): ValidationException: A change/update is in progress. Please wait for it to complete before requesting another change.
│ 
│   with module.terraform-module-environment.aws_elasticsearch_domain_policy.elastic_search["inf01"],
│   on modules/main/elastic-search.tf line 132, in resource "aws_elasticsearch_domain_policy" "elastic_search":
│  132: resource "aws_elasticsearch_domain_policy" "elastic_search" {
```

Looks like the first resource is not fully up when the second resource runs.

This used to work, and only stopped working a few weeks ago.

### Expected Behavior

apply should work.

The provider should wait for the first resource to be fully up before moving onto the second resource.

### Actual Behavior

apply fails, and a second apply works.

### Relevant Error/Panic Output Snippet

```shell
│ Error: setting Elasticsearch Domain Policy (): ValidationException: A change/update is in progress. Please wait for it to complete before requesting another change.
│ 
│   with module.terraform-module-environment.aws_elasticsearch_domain_policy.elastic_search["inf01"],
│   on modules/main/elastic-search.tf line 132, in resource "aws_elasticsearch_domain_policy" "elastic_search":
│  132: resource "aws_elasticsearch_domain_policy" "elastic_search" {
│
```

### Terraform Configuration Files

```
resource "aws_elasticsearch_domain" "elastic_search" {
  provider = aws.ou

  for_each = local.applications_elastic_search

  domain_name           = "${local.name}-${each.key}"
  elasticsearch_version = each.value.version

  cluster_config {
    instance_type            = each.value.instance_type
    zone_awareness_enabled   = each.value.zone_awareness_enabled // set to true to enable multi AZ.  set to false to set 1xAZ
    instance_count           = each.value.instance_count         // must be multiples of the AZ count, eg 3xAZ means 3/6/9 instances
    dedicated_master_enabled = false

    dynamic "zone_awareness_config" {
      for_each = each.value.zone_awareness_enabled == true ? [0] : []
      content {
        availability_zone_count = each.value.availability_zone_count // must be 2 or 3.  Ignored if zone_awareness_enabled is set to false
      }
    }
  }

  vpc_options {
    subnet_ids = slice(tolist(module.subnets.private_subnet_ids), 0, each.value.zone_awareness_enabled == false ? 1 : each.value.availability_zone_count)

    security_group_ids = [
      aws_security_group.elastic_search_domain[0].id
    ]
  }

  advanced_security_options {
    enabled                        = true
    internal_user_database_enabled = true

    master_user_options {
      master_user_name     = "admin"
      master_user_password = random_password.elastic_search[each.key].result
    }
  }

  encrypt_at_rest {
    enabled = true
  }

  node_to_node_encryption {
    enabled = true
  }

  domain_endpoint_options {
    enforce_https       = true
    tls_security_policy = "Policy-Min-TLS-1-2-2019-07"
  }

  ebs_options {
    ebs_enabled = true
    volume_size = each.value.volume_size
    volume_type = each.value.volume_type
  }

  dynamic "log_publishing_options" {
    for_each = local.elastic_search_logs
    content {
      cloudwatch_log_group_arn = aws_cloudwatch_log_group.elastic_search[log_publishing_options.key].arn
      log_type                 = log_publishing_options.value.log
    }
  }
}
```

```
resource "aws_elasticsearch_domain_policy" "elastic_search" {
  provider = aws.ou

  depends_on = [time_sleep.wait_60_seconds_for_elastic_search]

  for_each = local.applications_elastic_search

  domain_name     = aws_elasticsearch_domain.elastic_search[each.key].domain_name
  access_policies = data.aws_iam_policy_document.elasticsearch[each.key].json
}
```

### Steps to Reproduce

Above code causes the issue, but is quite specific to my environment. The code could be simplified, but we would need to ensure the first resource still took too long to initialize in AWS (ie a simpler version of the resource may initialize quicker).

### Important Factoids

If I implement a delay of 60 seconds between the two resources (using ```time_sleep``` resource), then it works.

### Would you like to implement a fix?

None

**Comment by Karthikraja9** [comment]
We are also facing the same issue. We tried adding the implicit policy, creating the policy as a separate resource and using depends_on to point to the ES domain resource, but no luck. It randomly works and fails.

**Comment by rariyama** [comment]
I'm also facing this issue. I feel like it'll be possible to resolve to check the domain status before updating the policy.
https://github.com/hashicorp/terraform-provider-aws/blob/b9d9303a4d355bd1cc93e7b5e1e708bd571e2799/internal/service/opensearch/domain_policy.go#L93-L96

**Comment by novotnymiro** [comment]
We are facing the same issue using Terraform v1.7.4, AWS provider 5.37.0 on OpenSearch_2.11.

**Comment by vani0123** [comment]
I am also facing the same issue with Terraform v1.7.1, AWS provider 5.34.0 on OpenSearch_2.11

**Comment by vani0123** [comment]
The issue is no more occurring with AWS provider 5.38.0.

**Comment by mgrov-ksc** [comment]
I'm still hitting this issue on AWS provider 5.38.0

**Comment by aksh-sood** [comment]
i was facing a similar issue while creating opensearch . 

i added a sleep condition between `aws_opensearch_domain` and `aws_opensearch_domain_policy`. The `time_sleep` was put dependent on  `aws_opensearch_domain` and `aws_opensearch_domain_policy` dependent on  `time_sleep`. 

The timer was set for 10 mins which i picked randomly but i might work for smaller sleep cycle as well .

Below is the example:

`resource "aws_opensearch_domain" "domain" {
------config-------
}


resource "time_sleep" "delay_10_min" {
  create_duration = "10m"

  depends_on = [ aws_opensearch_domain.domain ]
}

resource "aws_opensearch_domain_policy" "main" {

depends_on = [time_sleep.delay_10_min]
}
`

Hope this helps

**Comment by scott-doyland-burrows** [comment]
> i was facing a similar issue while creating opensearch . 
> 
> i added a sleep condition between `aws_opensearch_domain` and `aws_opensearch_domain_policy`. The `time_sleep` was put dependent on  `aws_opensearch_domain` and `aws_opensearch_domain_policy` dependent on  `time_sleep`. 
> 
> The timer was set for 10 mins which i picked randomly but it might work for shorter sleep cycle as well .
> 
> Below is the example:
> 
> ```
> resource "aws_opensearch_domain" "domain" {
> ------config-------
> }
> 
> 
> resource "time_sleep" "delay_10_min" {
>   create_duration = "10m"
> 
>   depends_on = [ aws_opensearch_domain.domain ]
> }
> 
> resource "aws_opensearch_domain_policy" "main" {
> 
> depends_on = [time_sleep.delay_10_min]
> }
> ```
> 
> Hope this helps
> 

Yes - that's exactly what I did as per the first post in this issue.

**Comment by msmith93** [comment]
I'm still seeing this error on v5.43.0

**Comment by jar-b** [comment]
This fix was applied to both the elasticsearch and opensearch resources. Can you open a new issue with the configuration you're observing this with?
