### ISSUE TITLE
[Docs]: Incorrect regex on EKS cluster name argument

### ISSUE THREAD

**Issue by joshuaking-madtech** [hashicorp/terraform-provider-aws#35843]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_access_entry#cluster_name

### Description

The regex and the description of "clustername" don't match.  If the description is correct and a 1 character name is allowed, the regex should read:
`^[0-9A-Za-z][A-Za-z0-9\-_]*$`
instead of
`^[0-9A-Za-z][A-Za-z0-9\-_]+$`
It's not immediately obvious which is correct, though I'd guess the description.

Edit: This is repeated everywhere the clustername argument appears.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_access_policy_association#cluster_name
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#name

### Would you like to implement a fix?

No

**Comment by mattburgess** [comment]
The [AWS API docs](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html#API_CreateCluster_RequestBody) agree!
