### ISSUE TITLE
[Bug]: aws_ecs_service fails to add tags from AWS provider with "InvalidParameterException: Long arn format must be used for tagging operations"

### ISSUE THREAD

**Issue by roman-verchikov** [hashicorp/terraform-provider-aws#35867]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.37.0

### Affected Resource(s)

* aws_ecs_service

### Expected Behavior

`terraform apply` successfully applies configuration of ECS service with tags defined in `provider`

### Actual Behavior

`terraform apply` fails to apply ECS service config with InvalidParameterException AWS client error

### Relevant Error/Panic Output Snippet

```shell
module.my_module.aws_ecs_service.my_service: Modifying... [id=arn:aws:ecs:us-west-2:<account_id>:service/<service_name>]
╷
│ Error: updating tags for ECS (Elastic Container) Service (arn:aws:ecs:us-west-2:<account_id>:service/<service_name>): tagging resource (arn:aws:ecs:us-west-2:<account_id>:service/<service_name>): InvalidParameterException: Long arn format must be used for tagging operations
│ 
│   with module.my_module.aws_ecs_service.my_service,
│   on modules/my-module/main.tf line 292, in resource "aws_ecs_service" "my_service":
│  292: resource "aws_ecs_service" "my_service" {
```

### Terraform Configuration Files

The code below DOES NOT reproduce the problem, I'm not sure which config option breaks it, and I don't want to share my actual config since it contains PI data. Very roughly, the config I'm applying is as follows:

```
terraform {
  required_version = ">= 1.4.5"

  required_providers {
    aws = {
      version = ">= 5.37"
      source  = "hashicorp/aws"
    }
  }
}

provider "aws" {
  default_tags {
    tags = {
      env = "prod"
    }
  }
}

resource "aws_ecs_task_definition" "my_task" {
  family                = "nginx-task"
  container_definitions = jsonencode([
    {
      name         = "nginx-container"
      image        = "nginx:latest"
      cpu          = 256
      memory       = 512
      portMappings = [
        {
          containerPort = 80
          hostPort      = 80
        }
      ]
    }
  ])
}

resource "aws_ecs_cluster" "my_cluster" {
  name = "my_cluster"
}

resource "aws_ecs_service" "my_service" {
  name                  = "my_service"
  cluster               = aws_ecs_cluster.my_cluster.id
  task_definition       = aws_ecs_task_definition.my_task.arn
  wait_for_steady_state = true
  desired_count = 1
}
```

When `provider` has `default_tags` - I get `InvalidParameterException`. When `provider.default_tags.tags` are commented out - configuration is applied with no problems.

### Steps to Reproduce

 - Run `terraform apply` against the code above (see detailed description)

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
This is probably related to the long ARN settings described in [Accessing Amazon ECS features through account settings](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-account-settings.html), specifically `serviceLongArnFormat` for ECS services. There is a corresponding [aws_ecs_account_setting_default](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_account_setting_default) resource that can be used to set them.

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
