### ISSUE TITLE
[Enhancement]: additional logging_level options for aws api gw to match aws gui options

### ISSUE THREAD

**Issue by susie-idw** [hashicorp/terraform-provider-aws#35863]
### Description

AWS API Gateways offer 4 logging levels in the stage settings:
1. Off
2. Errors only
3. Errors and Info Logs
4. Full request and response logs

Currently, the resource `api_gateway_method_settings` has options for the first 3 but not the 4th. I'm requesting that the option be added to select "Full request and response logs" in the `logging_level` argument for the `api_gateway_method_settings` resource.

### Affected Resource(s) and/or Data Source(s)

api_gateway_method_settings

### Potential Terraform Configuration

```terraform
Currently "The available levels are OFF, ERROR, and INFO" for logging_level. I propose "FULL" be added to configure "Full request and response logs".
```

### References

Terraform resource:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_method_settings

Setting in api gw:
![image (1)](https://github.com/hashicorp/terraform-provider-aws/assets/131711454/8dfbf43c-481f-4344-be45-2031422e029b)

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
According to the [MethodSetting data type](https://docs.aws.amazon.com/apigateway/latest/api/API_MethodSetting.html) in the API reference doc, `loggingLevel` supports only the three value. However, it seems that the UI's fourth option is referring to the `dataTraceEnabled` attribute. The first thing that jumped out is that the argument description in the TF doc is the same as the description in the API reference.

With that assumption, I looked at the backend call that the UI makes when saving the stage settings, and I can see that it's changing `loggingLevel` to `INFO` and `dataTraceEnabled` to `true` per JSON object below.

Based on this, we can assume that the "Full request and response logs" option is the same as setting `logging_level` to `INFO` and `data_trace_enabled` to `true`. Please validate in your Terraform configuration and report back the results - deploy with these two arguments set appropriately, then validate the setting in the UI.

```
{
  "patchOperations": [
    {
      "op": "replace",
      "path": "/*/*/metrics/enabled",
      "value": "false"
    },
    {
      "op": "replace",
      "path": "/*/*/logging/loglevel",
      "value": "INFO"
    },
    {
      "op": "replace",
      "path": "/*/*/logging/dataTrace",
      "value": "true"
    },
    {
      "op": "replace",
      "path": "/tracingEnabled",
      "value": "false"
    },
    {
      "op": "remove",
      "path": "/accessLogSettings",
      "value": ""
    }
  ]
}
```

**Comment by acwwat** [comment]
Actually the TF doc already have the answer. Refer to the **Full Request and Response Logs** option in the [Full Request and Response Logs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_method_settings#cloudwatch-logging-and-tracing) section of the resource doc.

**Comment by susie-idw** [comment]
@acwwat thank you for pointing this out. It works. I tested it with the following code:

```
resource "aws_api_gateway_rest_api" "example" {
  body = jsonencode({
    openapi = "3.0.1"
    info = {
      title   = "example"
      version = "1.0"
    }
    paths = {
      "/path1" = {
        get = {
          x-amazon-apigateway-integration = {
            httpMethod           = "GET"
            payloadFormatVersion = "1.0"
            type                 = "HTTP_PROXY"
            uri                  = "https://ip-ranges.amazonaws.com/ip-ranges.json"
          }
        }
      }
    }
  })

  name = "example"
}

resource "aws_api_gateway_deployment" "example" {
  rest_api_id = aws_api_gateway_rest_api.example.id

  triggers = {
    redeployment = sha1(jsonencode(aws_api_gateway_rest_api.example.body))
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_api_gateway_stage" "example" {
  deployment_id = aws_api_gateway_deployment.example.id
  rest_api_id   = aws_api_gateway_rest_api.example.id
  stage_name    = "example"
  xray_tracing_enabled = true
}

resource "aws_api_gateway_method_settings" "all" {
  rest_api_id = aws_api_gateway_rest_api.example.id
  stage_name  = aws_api_gateway_stage.example.stage_name
  method_path = "*/*"

  settings {
    logging_level      = "INFO"
    metrics_enabled    = true
    data_trace_enabled = true
  }
}
```
As you can see, i was looking for a fourth `logging_level` option and didn't see the `data_trace_enabled` (+ `logging_level = INFO`) combo to achieve this result.
