### ISSUE TITLE
[Enhancement]: Support custom_time_zone and file_extension in extended_s3_configuration block for kinesis_firehose_delivery_stream

### ISSUE THREAD

**Issue by visit1985** [hashicorp/terraform-provider-aws#35957]
### Description

Please support `custom_time_zone` and `file_extension` in `extended_s3_configuration` block for `kinesis_firehose_delivery_stream`.

### Affected Resource(s) and/or Data Source(s)

* kinesis_firehose_delivery_stream

### Potential Terraform Configuration

```terraform
resource "aws_kinesis_firehose_delivery_stream" "example" {
  # ... other configuration ...

  extended_s3_configuration {
    prefix           = "some-custom-prefix/!{timestamp:yyyy/MM/dd}/"
    custom_time_zone = "America/Los_Angeles"

    compression_format = "GZIP"
    file_extension     = ".gz"

    # ... other configuration ...
  }
}
```

### References

https://docs.aws.amazon.com/firehose/latest/APIReference/API_ExtendedS3DestinationConfiguration.html
https://aws.amazon.com/about-aws/whats-new/2024/02/amazon-data-firehose-time-zone-bucket-prefixes/

### Would you like to implement a fix?

No

**Comment by acwwat** [comment]
It doesn't seem like aws-sdk-go-v2 has support for the two new attributes yet, which is required before the resource can be updated.

https://github.com/aws/aws-sdk-go-v2/blob/7095341032d4a2b1fe04aa5e96e254321169e114/service/firehose/types/types.go#L2031-L2081

**Comment by visit1985** [comment]
@acwwat 

https://github.com/aws/aws-sdk-go-v2/blob/7095341032d4a2b1fe04aa5e96e254321169e114/service/firehose/types/types.go#L1009

https://github.com/aws/aws-sdk-go-v2/blob/7095341032d4a2b1fe04aa5e96e254321169e114/service/firehose/types/types.go#L1031

**Comment by acwwat** [comment]
@visit1985 Thanks for pointing out the right block - I quoted the wrong type after seeing it's not there in the IDE while working with the resource code. So we still need to wait until the dependency is updated to aws-sdk-go-v2 v1.25.2 in the next update cycle. I can add the attributes after that (currently it's at v1.25.1).

**Comment by acwwat** [comment]
@visit1985 Thanks for pointing to the right types. Let me look into it.
