### ISSUE TITLE
[Bug]: Error Multiple Import AWS Resources (for each)

### ISSUE THREAD

**Issue by amzar96** [hashicorp/terraform-provider-aws#35968]
### Terraform Core Version

1.6.6

### AWS Provider Version

2.8.1

### Affected Resource(s)

**aws_codecommit_repository**

### Expected Behavior

I want to get a good result after I run `terraform plan` without any erros

### Actual Behavior

Error I get:
```bash
│ Error: Unsupported argument
│
│   on main.tf line 23, in import:
│   23:   for_each = local.repository_name
│
│ An argument named "for_each" is not expected here.
╵
╷
│ Error: Invalid expression
│
│   on main.tf line 24, in import:
│   24:   to = aws_codecommit_repository.this[each.value]
│
│ A single static variable reference is required: only attribute access and indexing with constant keys. No calculations, function calls, template expressions, etc are allowed here.
```

### Terraform Configuration Files

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.16.0"
    }
  }

  required_version = ">= 1.1.0"
}


provider "aws" {
  region  = var.region
  profile = var.profile
}

locals {
  repository_name = toset(["testje"])
}

import {
  for_each = local.repository_name
  to = aws_codecommit_repository.this[each.value]
  id = each.value
}

resource "aws_codecommit_repository" "this" {
  for_each        = local.repository_name
  repository_name = each.value

  tags = {
    Environment = "Staging"
    Project     = "test-02"
  }
}
```

### Steps to Reproduce

`terraform init`
`terraform plan`

### Would you like to implement a fix?

No

**Comment by acwwat** [comment]
`for_each` support for `import` is a core Terraform matter and it seems that there is already a feature request for it - see https://github.com/hashicorp/terraform/issues/33624. There is a PR https://github.com/hashicorp/terraform/pull/33932 merged into v1.7. Since you have Terraform v1.6.6, perhaps you can upgraded to v1.7.4 (the latest version today) and see if it works.
