### ISSUE TITLE
[Bug]: Unable to import aws_route53_record if existing record is a geolocation record

### ISSUE THREAD

**Issue by tom10271** [hashicorp/terraform-provider-aws#35987]
### Terraform Core Version

1.7.0

### AWS Provider Version

5.31.0

### Affected Resource(s)

```HCL
resource "aws_route53_record" "exist_already" {
    alias {
        evaluate_target_health = false
        zone_id                = aws_lb.alb.zone_id
        name                   = aws_lb.alb.dns_name
    }

    zone_id = "Z123123"
    name    = "my.example.com"
    type    = "A"
}
```

### Expected Behavior

Work

### Actual Behavior

X work

### Terraform Configuration Files

?

### Steps to Reproduce

terraform import 'aws_route53_record.exist_already' Z123123_my.example.com_A

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @tom10271 👋 Thank you for taking the time to raise this! Can you supply debug logging (redacted as necessary), or a bit more information about the error message that you received?
