### ISSUE TITLE
[Enhancement]: Support for FileExtension property in S3 Destination Configuration

### ISSUE THREAD

**Issue by dygfloyd** [hashicorp/terraform-provider-aws#35989]
### Description

We are trying to get the Pulumi ExtendedS3Configuration to [support the FileExtension property](https://github.com/pulumi/pulumi-aws/issues/3479), Since that is built on top of terraform-provider-aws, it appears as if we need to start by request support for that feature here first. This property is described in the [AWS Destination Settings documentation](https://docs.aws.amazon.com/firehose/latest/dev/create-destination.html#create-destination-s3). Lack of support causes issues when you are trying to import files in S3 into other systems that require specific file extensions. For example, Datadog log rehydration only supports files with the extension .json.gz.

### References

https://docs.aws.amazon.com/firehose/latest/dev/create-destination.html#create-destination-s3

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@dygfloyd Thanks for raising this issue.
It has already been noticed in #35957. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
