### ISSUE TITLE
[Bug]: aws_wafv2_web_acl_logging_configuration face WAFLogDestinationPermissionIssueException at first time TF apply

### ISSUE THREAD

**Issue by Jack-WangZhe** [hashicorp/terraform-provider-aws#36000]
### Terraform Core Version

1.5

### AWS Provider Version

5.35.0

### Affected Resource(s)

aws_wafv2_web_acl_logging_configuration

### Expected Behavior

Terraform was applied successfully and all required resources have already been created the first time.

### Actual Behavior

Terraform applied with the error exception: WAFLogDestinationPermissionIssueException, **but then re-plan tf scripts and apply, and everything went well.**

### Relevant Error/Panic Output Snippet

```shell
putting WAFv2 WebACL Logging Configuration (arn:aws:wafv2:us-east-1:.....:global/webacl/...): WAFLogDestinationPermissionIssueException: Unable to deliver logs to the configured destination. You might need to grant log delivery permissions for the destination. If you're using S3 as your log destination, you might have exceeded your bucket limit.
```

### Terraform Configuration Files

```
resource "aws_cloudwatch_log_group" "this" {
  count = var.enable_log ? 1 : 0

  name = "aws-waf-logs-customized"
}

resource "aws_wafv2_web_acl_logging_configuration" "this" {
  count = var.enable_log ? 1 : 0

  log_destination_configs = [aws_cloudwatch_log_group.this.arn]
  resource_arn            = aws_wafv2_web_acl.this.arn # The web acl here will be used for CloudFront
}

resource "aws_cloudwatch_log_resource_policy" "this" {
  count = var.enable_log ? 1 : 0

  policy_document = data.aws_iam_policy_document.cw_log_policy_doc.json
  policy_name     = "webacl-policy-customized"
}

data "aws_iam_policy_document" "cw_log_policy_doc" {
  count = var.enable_log ? 1 : 0

  version = "2012-10-17"
  statement {
    effect = "Allow"
    principals {
      identifiers = ["delivery.logs.amazonaws.com"]
      type        = "Service"
    }
    actions   = ["logs:CreateLogStream", "logs:PutLogEvents"]
    resources = ["${aws_cloudwatch_log_group.this.arn}:*"]
    condition {
      test     = "ArnLike"
      values   = ["arn:aws:logs:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:*"]
      variable = "aws:SourceArn"
    }
    condition {
      test     = "StringEquals"
      values   = [tostring(data.aws_caller_identity.current.account_id)]
      variable = "aws:SourceAccount"
    }
  }
}

data "aws_region" "current" {}

data "aws_caller_identity" "current" {}
```

### Steps to Reproduce

* Terraform init - Goes Well
* Terraform plan - Goes Well
* Terraform apply - Failed, error - WAFLogDestinationPermissionIssueException, all the resources created without aws_wafv2_web_acl_logging_configuration
* Terraform plan - Goes Well # Re-plan terraform script
* Terraform apply - Goes Well # The terraform will apply successfully at the second time and just create aws_wafv2_web_acl_logging_configuration resource

### Would you like to implement a fix?

None

**Comment by Jack-WangZhe** [comment]
Hi guys,

We tested several times to set up the web Acl log configurations by terraform script with `aws_wafv2_web_acl_logging_configuration` and found the terraform always applied failed the first time as the above comment said.

Do you face the same problem with us? Or would you mind helping us solve the question?

Thank you! 🙂
Jack

**Comment by AErmie** [comment]
I too am encountering this error, but even re-running `terraform apply` still produces an error.

# Environment Details:
- Cloud: AWS
- CI/CD: Azure Pipelines
- Terraform: v1.7.4
- AWS Provider: v5.38.0

**Error**
`Error: putting WAFv2 WebACL Logging Configuration (arn:aws:wafv2:us-east-1:123456789012:regional/webacl/waf-dev-apigateway/GUID): AccessDeniedException: You don't have the permissions that are required to perform this operation.`

I even granted the Service Account Terraform is using, excessive permissions (ie. `"wafv2:*"`), with no change.

**Comment by justinretzolk** [comment]
Hey @Jack-WangZhe 👋 Thank you for taking the time to raise this! I believe this may be due to your `aws_cloudwatch_log_resource_policy` being created after the `aws_wafv2_web_acl_logging_configuration` resource. It doesn't look like there's any dependency between the two currently, so the order of creation isn't currently guaranteed.

Can you configure [`depends_on`](https://developer.hashicorp.com/terraform/language/meta-arguments/depends_on) to ensure that the `aws_wafv2_web_acl_logging_configuration` is dependent on `aws_cloudwatch_log_resource_policy` and they're created in the correct order?

@AErmie 👋 Your error looks a bit different -- it's throwing `AccessDeniedException` rather than `WAFLogDestinationPermissionIssueException`, the former of which is (almost?) always an issue with the permissions of the user making the request. If you continue to have issues with it after looking into your permissions, I'd recommend opening a separate issue so we can triage it as necessary.

**Comment by justinretzolk** [comment]
Hi all, I wanted to check in here to see if this issue is still happening, or if this is something we can close out.

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
