### ISSUE TITLE
[New]: aws_glue_catalog_database data source

### ISSUE THREAD

**Issue by jamiekt** [hashicorp/terraform-provider-aws#36015]
### Description

We have an `aws_glue_catalog_database` resource, it would seem sensible to have a matching data source too. I think the API supports retrieval of a Glue database: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/glue#Client.GetDatabase

It would return any attributes provided by [`type Database`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/glue@v1.77.1/types#Database) :

* id
* arn
* tags
* CreateTableDefaultPermissions
* CreateTime
* Description
* LocationUri
* Parameters
* TargetDatabase
* FederatedDatabase

### Requested Resource(s) and/or Data Source(s)

* aws_glue_catalog_database (data source)

### Potential Terraform Configuration

```terraform
data "aws_glue_catalog_database" "this" {
 name = "DatabaseName"
}
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @jamiekt 👋 Thank you for taking the time to raise this! It looks like someone has already requested this in #32755, which has an open pull request waiting to be prioritized (#32753). With that in mind, I'll close this one as a duplicate.

**Comment by justinretzolk** [comment]
Duplicate of #32755
