### ISSUE TITLE
This is a bug in the provider, which should be reported in the provider's own │ issue tracker.

### ISSUE THREAD

**Issue by KrishnaVishwakarma27101999** [hashicorp/terraform-provider-aws#36018]
### Description

  # snowflake_database.db will be created
  + resource "snowflake_database" "db" {
      + data_retention_time_in_days = -1
      + id                          = (known after apply)
      + is_transient                = false
      + name                        = "new_database_ts"
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

random_string.random: Destroying... [id=rkgb]
random_string.random: Destruction complete after 0s
snowflake_database.db: Creating...

 Error: Provider produced inconsistent result after apply
 
When applying changes to snowflake_database.db, provider
"provider[\"registry.terraform.io/snowflake-labs/snowflake\"]" produced an
 unexpected new value: Root object was present, but now absent.
 
This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Would you like to implement a fix?

None

**Comment by trevorrea** [comment]
This looks to be an issue you should report at https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues not here.

**Comment by justinretzolk** [comment]
As mentioned above, this looks to be an issue with the snowflake-labs provider, so closing.
