### ISSUE TITLE
[Enhancement]: AWS Batch `job_definition` ecs_properties parameter

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform-provider-aws#36034]
### Description

AWS Batch job definition added a new parameter, ecs_properties

### Affected Resource(s) and/or Data Source(s)

* aws_batch_job_definition

### Potential Terraform Configuration

```terraform
resource "aws_batch_job_definition" "test" {
  name = "tf_test_batch_job_definition"
  type = "container"
  ecs_properties = {}
}
```

### References

- https://docs.aws.amazon.com/batch/latest/APIReference/API_EcsTaskProperties.html

### Would you like to implement a fix?

None

**Comment by JVanAartsen** [comment]
Any implementation plans in motion? Looking for a volunteer?

**Comment by takaishi** [comment]
Hello, I'm interested in working on this issue. I need this parameter.

**Comment by takaishi** [comment]
I opened Pull Request to add properties for ecs_properties.

https://github.com/hashicorp/terraform-provider-aws/pull/37871
