### ISSUE TITLE
ROADMAP.md is outdated - delete?

### ISSUE THREAD

**Issue by inouiw** [hashicorp/terraform-provider-aws#36036]
### Description

The ROADMAP.md file describes changes planned for May 2023 - July 2023. This is outdated.
Should be deleted or updated.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @inouiw 👋 Thank you for taking the time to raise this! We've updated the roadmap, and will look into ways to ensure that's always up to date. With that in mind, we'll close this issue.
