### ISSUE TITLE
[Bug]: Unable to data source an aws_instance in v5.39.0

### ISSUE THREAD

**Issue by lra** [hashicorp/terraform-provider-aws#36037]
### Terraform Core Version

1.7.4

### AWS Provider Version

5.39.0

### Affected Resource(s)

* data.aws_instance

### Expected Behavior

```
$ terraform plan
data.aws_instance.prod_nene_mgmt: Reading...
data.aws_instance.prod_nene_mgmt: Read complete after 2s [id=i-0f7aff3b402e51777]

No changes. Your infrastructure matches the configuration.
```

### Actual Behavior

```
$ terraform plan
data.aws_instance.prod_nene_mgmt: Reading...

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: reading EC2 Instance (i-0f7aff3b402e51777): reading EC2 Instance (i-0f7aff3b402e51777): Invalid address to set: []string{"root_block_device", "0", "tags_all"}
│ 
│   with data.aws_instance.prod_nene_mgmt,
│   on test.tf line 1, in data "aws_instance" "prod_nene_mgmt":
│    1: data "aws_instance" "prod_nene_mgmt" {
│ 
╵

```

### Terraform Configuration Files

```hcl
data "aws_instance" "prod_nene_mgmt" {
  instance_tags = {
    Name = "PROD-NENE-MGMT"
  }
}

provider "aws" {
  region              = "us-east-1"
}
```

### Steps to Reproduce

This simple file is enough to reproduce the issue:
```hcl
data "aws_instance" "prod_nene_mgmt" {
  instance_tags = {
    Name = "PROD-NENE-MGMT"
  }
}

provider "aws" {
  region              = "us-east-1"
}
```

### Important Factoids

- It works with 5.38.0
- It does not work with 5.39.0

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/33769.

**Comment by ewbankkit** [comment]
@lra Thanks for raising this issue.
It has already been noticed in #36038. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
