### ISSUE TITLE
[Bug]: Regression in 5.39.0

### ISSUE THREAD

**Issue by tschmidty69** [hashicorp/terraform-provider-aws#36056]
### Terraform Core Version

1.7.1

### AWS Provider Version

5.39.0

### Affected Resource(s)

EC2 instance, specifically reading ebs tags_all

### Expected Behavior

Reads happen properly

### Actual Behavior

╷
│ Error: reading EC2 Instance (i-123456789): reading EC2 Instance (i-123456789): Invalid address to set: []string{"ebs_block_device", "0", "tags_all"}
│ 
│   with module.environment_stg.module.ebs_volumes["ec2"].data.aws_instance.attachment_target,
│   on .terraform/modules/environment_stg.ebs_volumes/main.tf line 1, in data "aws_instance" "attachment_target":
│    1: data "aws_instance" "attachment_target" {
│ 
╵

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: reading EC2 Instance (i-123456789): reading EC2 Instance (i-123456789): Invalid address to set: []string{"ebs_block_device", "0", "tags_all"}
│ 
│   with module.environment_stg.module.ebs_volumes["ec2"].data.aws_instance.attachment_target,
│   on .terraform/modules/environment_stg.ebs_volumes/main.tf line 1, in data "aws_instance" "attachment_target":
│    1: data "aws_instance" "attachment_target" {
│ 
╵
```

### Terraform Configuration Files

There is a lot of code associated with this and very specific to my use case which would be a great deal of work to anonymize. In any case since it works with 5.38.0 and not with 5.39.0 it does not seem entirely necessary.

### Steps to Reproduce

Running this plan with 5.39.0 results in the above errors, 5.38.0 plans and applies properly.

### Important Factoids

Seems to be a duplicate of this bug https://github.com/hashicorp/terraform-provider-aws/issues/17125

### References

My best guess is one of these commits from @YakDriver who also fixed the previous bug (possible duplicate/regression) https://github.com/hashicorp/terraform-provider-aws/issues/17125

https://github.com/hashicorp/terraform-provider-aws/commit/c9769c96c8b946724ce56feb55880f6eff9e23d4
https://github.com/hashicorp/terraform-provider-aws/commit/4c3e2c570a4b70c0d64832d30fedc8fbce18f0a7

### Would you like to implement a fix?

None

**Comment by YakDriver** [comment]
Thank you for raising this. This is fixed by #36054 and will be available in v5.39.1.
