### ISSUE TITLE
[Bug]: aws_osis_pipeline log_group requires specific pattern.

### ISSUE THREAD

**Issue by patelamol** [hashicorp/terraform-provider-aws#36076]
### Terraform Core Version

1.4.6

### AWS Provider Version

5.36.0

### Affected Resource(s)

aws_osis_pipeline

### Expected Behavior

Should allow any `log_group` name to be used.

### Actual Behavior

Seems like it validates to have a `log_group` name to follow the following pattern;
```
\/aws\/vendedlogs\/[\.\-_/#A-Za-z0-9]+
```

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: creating OpenSearch Ingestion Pipeline (prod-us1-co_data_row)
│ 
│   with module.unity_opensearch.aws_osis_pipeline.msk_ingestion_pipeline[0],
│   on .terraform/modules/unity_opensearch/msk_injestion.tf line 85, in resource "aws_osis_pipeline" "msk_ingestion_pipeline":
│   85: resource "aws_osis_pipeline" "msk_ingestion_pipeline" {
│ 
│ operation error OSIS: CreatePipeline, https response error StatusCode: 400,
│ RequestID: XXXX, ValidationException: 2
│ validation errors detected: Value 'prod-us1-co_data_row' at 'pipelineName'
│ failed to satisfy constraint: Member must satisfy regular expression
│ pattern: [a-z][a-z0-9\-]+; Value
│ 'osis/prod/universal-objects/prod-us1-co_data_row' at
│ 'logPublishingOptions.cloudWatchLogDestination.logGroup' failed to satisfy
│ constraint: Member must satisfy regular expression pattern:
│ \/aws\/vendedlogs\/[\.\-_/#A-Za-z0-9]+
```

### Terraform Configuration Files

You don't need this, the bug is obvious.

### Steps to Reproduce

Create `aws_osis_pipeline` by passing `log_group` name that doesn't have a prefix of `/aws/vendedlogs/`.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @patelamol 👋 Thank you for taking the time to raise this! In this case, the validation and error are both coming from the upstream API itself. The regex used for validation is documented in the [relevant AWS API](https://docs.aws.amazon.com/opensearch-service/latest/APIReference/API_osis_CloudWatchLogDestination.html), and [isn't currently enforced](https://github.com/hashicorp/terraform-provider-aws/blob/e3b903a12acba8e16aafeba2a18cb813cd234f75/internal/service/osis/pipeline.go#L154-L156) by the provider (though one could certainly argue it should be). With that in mind, we'll close this issue.
