### ISSUE TITLE
[Bug]: aws_lambda_function is being silently updated, despite lifecycle ignore_changes

### ISSUE THREAD

**Issue by indy-singh** [hashicorp/terraform-provider-aws#36077]
### Terraform Core Version

1.7.4

### AWS Provider Version

5.37.0

### Affected Resource(s)

```hcl
resource "aws_lambda_function" "storefront_demo" {
  provider      = aws.europe_london
  function_name = "storefront_demo"
  s3_bucket     = "codeweavers-deployed-assets"
  s3_key        = "storefront-dist/7dc0612a45ee79401224ea501e910651b527cc5f/storefront.zip"
  role          = data.aws_iam_role.lambda_execution_role.arn
  handler       = "app/server/main.app"
  memory_size   = 1024
  runtime       = "nodejs20.x"
  timeout       = 10
  architectures = ["arm64"]

  environment {
    variables = {
      ENV    = "configs/env.DEMO.ini"
      LogsOn = true
    }
  }

  logging_config {
    log_format            = "JSON"
    application_log_level = "INFO"
    system_log_level      = "INFO"
  }

  # the lambda code is updated outside of terraform via a github deploy.
  # we need this because we still want to declare and manage the config
  # of the lambda in terraform
  lifecycle {
    ignore_changes = [s3_bucket, s3_key]
  }
}
```

Background:
We basically use Terraform to create and maintain the configuration of the lambda except the actual code itself that is done by github actions and `updatefunctioncode`.

Bug:
Several times over the past day or two we've had the lambda suddenly revert to a very old version (it's attached via s3 object).

After some digging we found in CloudTrail that it was Terraform, which was suprising. We've been using Terraform for years and never had anything like this.

```json
{
	"eventVersion": "1.08",
	"userIdentity": {
		"type": "IAMUser",
		"principalId": "REDACTED",
		"arn": "arn:aws:iam::REDACTED:user/ConfigurationDeployment",
		"accountId": "REDACTED",
		"accessKeyId": "REDACTED",
		"userName": "ConfigurationDeployment"
	},
	"eventTime": "2024-03-04T21:58:16Z",
	"eventSource": "lambda.amazonaws.com",
	"eventName": "UpdateFunctionCode20150331v2",
	"awsRegion": "eu-west-2",
	"sourceIPAddress": "REDACTED",
	"userAgent": "APN/1.0 HashiCorp/1.0 Terraform/1.7.3 (+https://www.terraform.io) terraform-provider-aws/5.37.0 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go-v2/1.25.0 os/windows lang/go#1.21.7 md/GOOS#windows md/GOARCH#amd64 api/lambda#1.50.0",
	"requestParameters": {
		"fullyQualifiedArn": {
			"arnPrefix": {
				"partition": "aws",
				"region": "eu-west-2",
				"account": "REDACTED"
			},
			"relativeId": {
				"functionName": "storefront_demo"
			},
			"functionQualifier": {}
		},
		"functionName": "arn:aws:lambda:eu-west-2:REDACTED:function:storefront_demo",
		"publish": false,
		"s3Key": "storefront-dist/a5c32fee732c6f45bca21af3afd6b851787467a7/storefront.zip",
		"s3ObjectVersion": "Pr6N1oRltxPxhbTySaz9X2GjvpPDdKt1",
		"s3Bucket": "codeweavers-deployed-assets",
		"architectures": [
			"arm64"
		],
		"dryRun": false
	},
	"responseElements": {
		"functionName": "storefront_demo",
		"functionArn": "arn:aws:lambda:eu-west-2:REDACTED:function:storefront_demo",
		"runtime": "nodejs20.x",
		"role": "arn:aws:iam::REDACTED:role/LambdaExecutionRole",
		"handler": "app/server/main.app",
		"codeSize": 25424103,
		"description": "",
		"timeout": 10,
		"memorySize": 1024,
		"lastModified": "2024-03-04T21:58:16.000+0000",
		"codeSha256": "Uvc5sjUahhO6dD/YYfDY+C5dZVaC2j1JUD4bFKfUXkA=",
		"version": "$LATEST",
		"environment": {},
		"tracingConfig": {
			"mode": "PassThrough"
		},
		"revisionId": "bab0a936-adaa-4d9c-af3e-38247eaaac33",
		"state": "Active",
		"lastUpdateStatus": "InProgress",
		"lastUpdateStatusReason": "The function is being created.",
		"lastUpdateStatusReasonCode": "Creating",
		"packageType": "Zip",
		"architectures": [
			"arm64"
		],
		"ephemeralStorage": {
			"size": 512
		},
		"snapStart": {
			"applyOn": "None",
			"optimizationStatus": "Off"
		},
		"runtimeVersionConfig": {
			"runtimeVersionArn": "arn:aws:lambda:eu-west-2::runtime:e06356b9cc317b394b345659ca7fe94e5360e45227db179a224757608b8effe6"
		},
		"loggingConfig": {
			"logFormat": "JSON",
			"applicationLogLevel": "INFO",
			"systemLogLevel": "INFO",
			"logGroup": "/aws/lambda/storefront_demo"
		}
	},
	"requestID": "fc6652b2-e448-4c62-bf9d-a3b102ca9954",
	"eventID": "2dd09ecf-08ad-463f-8726-4a18ffe669f9",
	"readOnly": false,
	"eventType": "AwsApiCall",
	"managementEvent": true,
	"recipientAccountId": "REDACTED",
	"eventCategory": "Management",
	"tlsDetails": {
		"tlsVersion": "TLSv1.3",
		"cipherSuite": "TLS_AES_128_GCM_SHA256",
		"clientProvidedHostHeader": "lambda.eu-west-2.amazonaws.com"
	}
}
```

`terraform plan` doens't show any changes.

And when I do `.\terraform.exe state show module.storefront.aws_lambda_function.storefront_demo`

```hcl
 D:\code\cwEnvConfig\Trunk\CloudConfiguration> .\terraform.exe state show module.storefront.aws_lambda_function.storefront_demo
# module.storefront.aws_lambda_function.storefront_demo:
resource "aws_lambda_function" "storefront_demo" {
    architectures                  = [
        "arm64",
    ]
    arn                            = "arn:aws:lambda:eu-west-2:REDACTED:function:storefront_demo"
    function_name                  = "storefront_demo"
    handler                        = "app/server/main.app"
    id                             = "storefront_demo"
    invoke_arn                     = "arn:aws:apigateway:eu-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-2:REDACTED:function:storefront_demo/invocations"
    last_modified                  = "2024-03-04T21:58:16.000+0000"
    layers                         = []
    memory_size                    = 1024
    package_type                   = "Zip"
    publish                        = false
    qualified_arn                  = "arn:aws:lambda:eu-west-2:REDACTED:function:storefront_demo:2"
    qualified_invoke_arn           = "arn:aws:apigateway:eu-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-2:REDACTED:function:storefront_demo:2/invocations"
    reserved_concurrent_executions = -1
    role                           = "arn:aws:iam::REDACTED:role/LambdaExecutionRole"
    runtime                        = "nodejs20.x"
    s3_bucket                      = "codeweavers-deployed-assets"
    s3_key                         = "storefront-dist/a5c32fee732c6f45bca21af3afd6b851787467a7/storefront.zip"
    skip_destroy                   = false
    source_code_hash               = "Uvc5sjUahhO6dD/YYfDY+C5dZVaC2j1JUD4bFKfUXkA="
    source_code_size               = 25424103
    tags                           = {}
    tags_all                       = {
        "ManagedbyTerraform" = "true"
    }
    timeout                        = 10
    version                        = "2"

    environment {
        variables = {
            "ENV"    = "configs/env.DEMO.ini"
            "LogsOn" = "true"
        }
    }

    ephemeral_storage {
        size = 512
    }

    logging_config {
        application_log_level = "INFO"
        log_format            = "JSON"
        log_group             = "/aws/lambda/storefront_demo"
        system_log_level      = "INFO"
    }

    tracing_config {
        mode = "PassThrough"
    }
}
```

To be clear here; the problematic thing is `a5c32fee732c6f45bca21af3afd6b851787467a7` Terraform should have _never_ issued the request to update the function with that _at all_.

For now, we are going to leverage IAM to deny Terraform UpdateFunctionCode, but this is baffling.

Happy to provide further logs but that will have to be in the morning now.

Cheers,
Indy

### Expected Behavior

See above

### Actual Behavior

See above

### Relevant Error/Panic Output Snippet

```shell
See above
```

### Terraform Configuration Files

See above

### Steps to Reproduce

See above

### Debug Output

See above

### Panic Output

See above

### Would you like to implement a fix?

None

**Comment by indy-singh** [comment]
We've just rolled out an explicit IAM Deny

```json
{
  "Sid": "SeeIssue36077onGitHubTerraformProviderAws",
  "Effect": "Deny",
  "Action": "lambda:UpdateFunctionCode",
  "Resource": "arn:aws:lambda:*:REDACTED:function:storefront_demo"
}
```

And then tested it

```hcl
Error: updating Lambda Function (storefront_demo) code: operation error Lambda: UpdateFunctionCode, https response error StatusCode: 403, RequestID: eca2e288-7754-4f8c-97f6-0dfd9720ad59, api error AccessDeniedException: User: arn:aws:iam::REDACTED:user/ConfigurationDeployment is not authorized to perform: lambda:UpdateFunctionCode on resource: arn:aws:lambda:eu-west-2:REDACTED:function:storefront_demo with an explicit deny in an identity-based policy

  with module.storefront.aws_lambda_function.storefront_demo,
  on storefront\lambda.tf line 9, in resource "aws_lambda_function" "storefront_demo":
   9: resource "aws_lambda_function" "storefront_demo" {
```

So now we wait for the next silent update.

Cheers,
Indy

**Comment by justinretzolk** [comment]
Hey @indy-singh 👋 Thank you for taking the time to raise this! That's certainly unexpected behavior. I noticed that the `a5c32fee732c6f45bca21af3afd6b851787467a7` string that you called out is in the plan and state outputs you provided, but isn't in the example configuration. Was that intentional, or something that's a result of this?

Additional debug logging would be helpful for whoever picks this up to investigate it. If there any recent change in terms of versions of Terraform or the AWS Provider, that information also sometimes proves useful.

**Comment by indy-singh** [comment]
> Was that intentional, or something that's a result of this? 

That is intentional. 

`a5c32fee732c6f45bca21af3afd6b851787467a7` was deployed via Terraform on `29 February 2024 14:44:48 GMT`.

`7dc0612a45ee79401224ea501e910651b527cc5f` was deployed via Terraform on `29 February 2024 14:59:17 GMT`.

And it has stayed locked (in terraform) at `7dc0612a45ee79401224ea501e910651b527cc5f` with the added `lifecycle.ignore_changes` since `29 February 2024 15:21:57 GMT`.

> If there any recent change in terms of versions of Terraform or the AWS Provider, that information also sometimes proves useful.

Yeah, I did upgrade both terraform.exe and the aws provider `5.37.0` _very_ recently, before we began this work.

Since opening this ticket, I've re-read the docs: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function

And updated the `ignore_changes` to include `source_code_hash`:-

>  Used to trigger updates. Must be set to a base64-encoded SHA256 hash of the package file specified with either filename or s3_key. The usual way to set this is filebase64sha256("file.zip") (Terraform 0.11.12 and later) or base64sha256(file("file.zip")) (Terraform 0.11.11 and earlier), where "file.zip" is the local filename of the lambda function source archive.

I've not had time to look into this properly yet, but I've got a feeling it is something to do with missing `source_code_hash` in the lifecycle changes. The wording of "used to trigger updates" leaves some wiggle room for unexpected things to happen.

Cheers,
Indy

**Comment by indy-singh** [comment]
I've replicated the bug! It's when you change the [architectures](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#architectures) argument, it seems to pick the original code from the remote state (guess/theory).

I'll do a write up later (I need to walk the dog).

Cheers,
Indy

**Comment by indy-singh** [comment]
`terraform apply` this:-

```hcl
# not need for repo, just easier to have it someone else repo it.
data "archive_file" "init" {
  type        = "zip"
  source_file = "${path.module}/index.js"
  output_path = "${path.module}/index.zip"
}

resource "aws_lambda_function" "example_lambda" {
  provider         = aws.london
  function_name    = "example_lambda"
  filename         = data.archive_file.init.output_path
  source_code_hash = data.archive_file.init.output_base64sha256
  role             = "arn:aws:iam::999431924810:role/GenericLambdaExecutionRole"
  handler          = "index.handler"
  runtime          = "nodejs20.x"  

  lifecycle {
    ignore_changes = [ source_code_hash ]
  }
}

# not need for repo, just easier to curl to this url
resource "aws_lambda_function_url" "test_latest" {
  provider           = aws.london
  function_name      = aws_lambda_function.example_lambda.function_name
  authorization_type = "NONE"
}

output "url_to_invoke" {
  value = aws_lambda_function_url.test_latest.function_url
}
```
Where index.js is this:-
```js
exports.handler =  async function(event, context) {
  // TODO implement
  console.log(event);
  console.log(context);
  const response = {
    statusCode: 200,
    body: JSON.stringify('Cat says meow'),
  };
  return response;
};
```
Then confirm that the cat says meow using powershell:-
```powershell
$url = (.\terraform.exe output -raw url_to_invoke); curl.exe $url;
```
Then log into the AWS console, change the index.js to says `dog says woof`, deploy using the console and confirm using the above powershell command.

Then go back and change the `architectures` to be `["arm64"]` and do `terraform apply` again.

Note that output says:-

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_lambda_function.example_lambda will be updated in-place
  ~ resource "aws_lambda_function" "example_lambda" {
      ~ architectures                  = [
          - "arm64",
          + "x86_64",
        id                             = "example_lambda"
      ~ last_modified                  = "2024-03-08T15:18:13.000+0000" -> (known after apply)
        tags                           = {}
        # (20 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes
```

Then run the powershell command, and see that it has reverted to "cat says meow" when it should be "dog says woof".

Cheers,
Indy

**Comment by indy-singh** [comment]
Ah, this is interesting. I tried the aws cli;

```
> aws lambda update-function-code --function-name example_lambda --architectures arm64

An error occurred (InvalidParameterValueException) when calling the UpdateFunctionCode operation: Please provide a source for function code.
```
And it makes it _obvious_ that to change the architecture you have to provide the source code; I presume becomes it needs to recompile something?

Cheers,
Indy

**Comment by indy-singh** [comment]
Hunting around for some info; it says this on the lambda page:-

![image](https://github.com/hashicorp/terraform-provider-aws/assets/1906778/6d0247a9-91ce-4e23-8834-ce5627df76f4)

So I guess this isn't a bug per se, but a non-communicated unexpected side-effect.

Especially as Terraform tells you it is going to be update in-place _implying_ the current handler code will be left as is.

Maybe changing architecture property should invoke a destructive warning?

Cheers,
Indy

**Comment by indy-singh** [comment]
Hi @justinretzolk,

Any thoughts on my previous response?

Cheers,
Indy

**Comment by justinretzolk** [comment]
Hey @indy-singh,

Thanks for the additional follow up and perspective here. I'm not sure I agree that a warning is necessary here. I'll have a more long-winded explanation below, but out of respect for your time, the honest summary is that the issue you're running into is a result of using the resource in a way that it's not currently designed, and in a way that I don't believe is currently compatible with the available APIs.

The `source_code_hash` argument is both [optional and computed](https://github.com/hashicorp/terraform-provider-aws/blob/27a5f7c9e3fc73ee14edb14e1974dd00e7478b39/internal/service/lambda/function.go#L375-L376), meaning that you don't have to supply it, but even if you don't, _some_ value will be calculated for it.

The reason this is useful for triggering updates to lambda functions with Terraform is because the AWS API doesn't return the source code itself when reading the lambda function; only a SHA256 hash. By calculating and supplying a base64 encoded SHA256 hash of the source code as the value for `source_code_hash`, you can effectively "tell" Terraform that the lambda function should be updated when changes are made to the code itself.

On the other side of that, when a value is _not_ supplied for `source_code_hash`, if Terraform detects changes between the configuration and the value returned by the read action of the lambda API (i.e. 'drift'), Terraform, by nature of being declarative, triggers an update to reconcile the configuration with reality. This is what you ran into when you added `source_code_hash` to `ignore_changes`, which stopped Terraform from trying to reconcile the drift by updating the state to reconcile the differences. When using the provider to fully manage a lambda function, the detection of changes to `source_code_hash` would be the warning that you're talking about. 

Changes to `architecture` also trigger the source code to be updated, for the reasons we discussed in previous comments. Since the source code is required in order to use `UpdateFunctionCode` (as you noted regarding the CLI), Terraform must include that data in the request. By the design of Terraform being declarative, the source code is defined by the `s3_bucket` and `s3_key` arguments in the configuration, so that's what's included in the `UpdateFunctionCode` call. When using the provider to fully manage the lambda function, this would indeed update the source code, but if the source code was out of sync (as detected by `source_code_hash`), that source code would be updated anyways.

While it's theoretically possible that we could create some kind of "don't manage the code" pseudo argument, that would cause the provider to diverge from the underlying API, and could break other functionality (i.e. being able to update `architectures`). With options like [lambda layers](https://docs.aws.amazon.com/lambda/latest/dg/chapter-layers.html) and its associated Terraform resources available, I don't see us making those kinds of changes.

**Comment by indy-singh** [comment]
Hi @justinretzolk,

Thanks for taking the time to write out the long winded explanation.

I understand where are you are coming. I can't say I agree with Terraform not emitting a warning when the aws cli _does_ 🙂 At the same time I also acknowledge that our use case is esoteric.

For anyone arriving via Google; we've chosen to prevent this in two ways;

1. Explicit IAM deny as described [here](https://github.com/hashicorp/terraform-provider-aws/issues/36077#issuecomment-1978361185).
2. A `postcondition` in the `lifecycle` block inside of `aws_lambda_function`:-
```hcl
postcondition {
  condition     = contains(self.architectures, "arm64")
  error_message = "architectures must be arm64. To change it now would cause the lambda to be replaced with the first version of the source code; see https://github.com/hashicorp/terraform-provider-aws/issues/36077"
}
```

Appreciate the detailed engagement on this issue @justinretzolk. It's always nice when that happens. I'm happy for this issue to be closed/resolved.

Cheers,
Indy
