### ISSUE TITLE
[Enhancement]: Data Sources for Cognito User Pool

### ISSUE THREAD

**Issue by hanoj-budime** [hashicorp/terraform-provider-aws#36087]
### Description

Currently, we lack real-time descriptions of user pool information, which is crucial for end applications and Terraform operations to gather data. This information includes whether the user pool configuration has MFA activated, password patterns, sign-up enablement, required fields, etc.

Similarly, we are also missing real-time descriptions of app client information. This could prove beneficial for end applications, providing insights into whether the app client auth session timeout settings, etc.

### Affected Resource(s) and/or Data Source(s)

``` tf
data "aws_cognito_user_pool" "describe_user_pool"
```
``` json
{
  "UserPool": {
      "MfaConfiguration": "OFF",
      "Name": "MyUserPool",
      "AutoVerifiedAttributes": [
          "email"
      ],
      "Policies": {
          "PasswordPolicy": {
              "RequireLowercase": true,
              "RequireSymbols": true,
              "RequireNumbers": true,
              "MinimumLength": 8,
              "RequireUppercase": true
          }
      },
      "UsernameAttributes": [
          "email"
      ],
      "Id": "us-west-2_aaaaaaaaa",
  }
}
```

### Would you like to implement a fix?

No

**Comment by hanoj-budime** [comment]
Yes, @danquack.

Looking for `data source for a specific user pool`

**Comment by SolomonHD** [comment]
Yes, we need a `data "aws_cognito_user_pool"`, without we can't get the custom domain attribute.  I have to use a pre-existing user pool. 

I've got a hack with the import block and the `resource "aws_cognito_user_pool"` with an `ignore_changes` lifecycle attached, but it requires that I remove it from state before deleting to avoid errors.

**Comment by ikattur-ota** [comment]
It'd be nice to also have the [`endpoint`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool#endpoint) attribute in the data block, @danquack
