### ISSUE TITLE
[Bug]: DescribeOrganizationConfigRules, failed to get rate limit token, retry quota exceeded

### ISSUE THREAD

**Issue by damianarata** [hashicorp/terraform-provider-aws#36094]
### Terraform Core Version

1.7.4

### AWS Provider Version

5.39.1

### Affected Resource(s)

`resource "aws_config_organization_managed_rule" "alb_waf_enabled" {
  name            = "alb_waf_enabled"
  rule_identifier = "ALB_WAF_ENABLED"
  resource_types_scope = [
    "AWS::ElasticLoadBalancingV2::LoadBalancer",
  ]
}`

### Expected Behavior

It should try to create the resource or validate the current status.

### Actual Behavior

When I try to run the plan I get this error message:
`│ Error: reading ConfigService Organization Managed Rule (ALB_WAF_ENABLED): operation error Config Service: DescribeOrganizationConfigRules, failed to get rate limit token, retry quota exceeded, 3 available, 5 requested`

### Terraform Configuration Files

From my security perspective will not provide my log because of the confidential information. It is easy to reproduce creating the aws_config_organization_managed_rule resource.

### Steps to Reproduce

1. Write the resource in a tf file.
2. Run a tf plan

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@damianarata Thanks for raising this issue 👏.
Per [this discussion](https://github.com/hashicorp/terraform-provider-aws/issues/34669#issuecomment-1960428224) could you please either set `retry_mode = "adaptive"` or set `token_bucket_rate_limiter_capacity` to a (very) large value.
We are working on a more satisfactory general solution to this.
