### ISSUE TITLE
[AWS SDK for Go Migration] OpsWorks Service

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#36193]
### Description
To align with the dates described on #32976 the OpsWorks Service requires migration to rely fully on [AWS SDK for Go v2](https://github.com/aws/aws-sdk-go-v2). This change should be mechanical in nature and not introduce any behavior changes.

The maintainer team will be working on these migrations but as always, help from the community is always appreciated. We would require passing acceptance tests for the entire set of resources being migrated. (We will also validate on review)

For further information about the migration, please see the parent issue #32976.

### Resources In Scope for Migration
```
"aws_opsworks_application"
"aws_opsworks_custom_layer"
"aws_opsworks_ecs_cluster_layer"
"aws_opsworks_ganglia_layer"
"aws_opsworks_haproxy_layer"
"aws_opsworks_instance"
"aws_opsworks_java_app_layer"
"aws_opsworks_memcached_layer"
"aws_opsworks_mysql_layer"
"aws_opsworks_nodejs_app_layer"
"aws_opsworks_permission"
"aws_opsworks_php_app_layer"
"aws_opsworks_rails_app_layer"
"aws_opsworks_rds_db_instance"
"aws_opsworks_stack"
"aws_opsworks_static_web_layer"
"aws_opsworks_user_profile"
```

### Data Sources In Scope for Migration
```

```

### References

- #32976

**Comment by DanielRieske** [comment]
Picking this migration up next, will submit a PR tomorrow.

**Comment by DanielRieske** [comment]
In hindsight, I should've taken a look at the deprecation notice for this service.

Considering OpsWorks has been deprecated and [this issue](https://github.com/hashicorp/terraform-provider-aws/issues/35701) exists, can we close this one?

**Comment by ewbankkit** [comment]
@DanielRieske For completeness we will do this migration; We will drop OpsWorks support with **v6.0.0** of the provider.
