### ISSUE TITLE
[AWS SDK for Go Migration] QuickSight Service

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#36198]
### Description
To align with the dates described on #32976 the QuickSight Service requires migration to rely fully on [AWS SDK for Go v2](https://github.com/aws/aws-sdk-go-v2). This change should be mechanical in nature and not introduce any behavior changes.

The maintainer team will be working on these migrations but as always, help from the community is always appreciated. We would require passing acceptance tests for the entire set of resources being migrated. (We will also validate on review)

For further information about the migration, please see the parent issue #32976.

### Resources In Scope for Migration
```
"aws_quicksight_account_subscription"
"aws_quicksight_analysis"
"aws_quicksight_dashboard"
"aws_quicksight_data_set"
"aws_quicksight_data_source"
"aws_quicksight_folder"
"aws_quicksight_folder_membership"
"aws_quicksight_group"
"aws_quicksight_group_membership"
"aws_quicksight_iam_policy_assignment"
"aws_quicksight_ingestion"
"aws_quicksight_namespace"
"aws_quicksight_refresh_schedule"
"aws_quicksight_template"
"aws_quicksight_template_alias"
"aws_quicksight_theme"
"aws_quicksight_user"
"aws_quicksight_vpc_connection"
```

### Data Sources In Scope for Migration
```
"aws_quicksight_data_set"
"aws_quicksight_group"
"aws_quicksight_theme"
"aws_quicksight_user"
```

### References

- #32976

**Comment by Snackeroo** [comment]
I'm working on this issue and have made a PR. When you have the bandwidth, please kindly review my PR:
https://github.com/hashicorp/terraform-provider-aws/pull/36431
