### ISSUE TITLE
[AWS SDK for Go Migration] SDB (SimpleDB) Service

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#36209]
### Description
To align with the dates described on #32976 the SDB (SimpleDB) Service requires migration to rely fully on [AWS SDK for Go v2](https://github.com/aws/aws-sdk-go-v2). This change should be mechanical in nature and not introduce any behavior changes.

The maintainer team will be working on these migrations but as always, help from the community is always appreciated. We would require passing acceptance tests for the entire set of resources being migrated. (We will also validate on review)

For further information about the migration, please see the parent issue #32976.

### Resources In Scope for Migration
```
"aws_simpledb_domain"
```

### Data Sources In Scope for Migration
```

```

### References

- #32976

**Comment by acwwat** [comment]
The AWS SDK for Go V2 doesn't seem to support the SimpleDB service anymore, as I cannot find the package anymore. I've posted a question at https://github.com/aws/aws-sdk-go-v2/discussions/2589 to see if I can get an official answer.

**Comment by bengaywins** [comment]
@acwwat Just because I was bored (not a contributor at all) but SimpleDB was removed as a service in the linked SDK v2 with tag `v0.25.0`. It's there for `v0.24.0` but not `v0.25.0`.

**Comment by ewbankkit** [comment]
Closing as there is no AWS SDK for Go v2 support for the `simpledb` service.
