### ISSUE TITLE
[AWS SDK for Go Migration] SageMaker Service

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#36208]
### Description
To align with the dates described on #32976 the SageMaker Service requires migration to rely fully on [AWS SDK for Go v2](https://github.com/aws/aws-sdk-go-v2). This change should be mechanical in nature and not introduce any behavior changes.

The maintainer team will be working on these migrations but as always, help from the community is always appreciated. We would require passing acceptance tests for the entire set of resources being migrated. (We will also validate on review)

For further information about the migration, please see the parent issue #32976.

### Resources In Scope for Migration
```
"aws_sagemaker_app"
"aws_sagemaker_app_image_config"
"aws_sagemaker_code_repository"
"aws_sagemaker_data_quality_job_definition"
"aws_sagemaker_device"
"aws_sagemaker_device_fleet"
"aws_sagemaker_domain"
"aws_sagemaker_endpoint"
"aws_sagemaker_endpoint_configuration"
"aws_sagemaker_feature_group"
"aws_sagemaker_flow_definition"
"aws_sagemaker_human_task_ui"
"aws_sagemaker_image"
"aws_sagemaker_image_version"
"aws_sagemaker_model"
"aws_sagemaker_model_package_group"
"aws_sagemaker_model_package_group_policy"
"aws_sagemaker_monitoring_schedule"
"aws_sagemaker_notebook_instance"
"aws_sagemaker_notebook_instance_lifecycle_configuration"
"aws_sagemaker_pipeline"
"aws_sagemaker_project"
"aws_sagemaker_servicecatalog_portfolio_status"
"aws_sagemaker_space"
"aws_sagemaker_studio_lifecycle_config"
"aws_sagemaker_user_profile"
"aws_sagemaker_workforce"
"aws_sagemaker_workteam"
```

### Data Sources In Scope for Migration
```
"aws_sagemaker_prebuilt_ecr_image"
```

### References

- #32976

**Comment by DanielRieske** [comment]
Currently working on this issue, I expect to submit a PR today or tomorrow.
