### ISSUE TITLE
[AWS SDK for Go Migration] SES (Simple Email) Service

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#36212]
### Description
To align with the dates described on #32976 the SES (Simple Email) Service requires migration to rely fully on [AWS SDK for Go v2](https://github.com/aws/aws-sdk-go-v2). This change should be mechanical in nature and not introduce any behavior changes.

The maintainer team will be working on these migrations but as always, help from the community is always appreciated. We would require passing acceptance tests for the entire set of resources being migrated. (We will also validate on review)

For further information about the migration, please see the parent issue #32976.

### Resources In Scope for Migration
```
"aws_ses_active_receipt_rule_set"
"aws_ses_configuration_set"
"aws_ses_domain_dkim"
"aws_ses_domain_identity"
"aws_ses_domain_identity_verification"
"aws_ses_domain_mail_from"
"aws_ses_email_identity"
"aws_ses_event_destination"
"aws_ses_identity_notification_topic"
"aws_ses_identity_policy"
"aws_ses_receipt_filter"
"aws_ses_receipt_rule"
"aws_ses_receipt_rule_set"
"aws_ses_template"
```

### Data Sources In Scope for Migration
```
"aws_ses_active_receipt_rule_set"
"aws_ses_domain_identity"
"aws_ses_email_identity"
```

### References

- #32976

**Comment by HubbardHarvey3** [comment]
@kamilturek I didn't think to self assign this issue, but I am ironing out what I hope are the last few failing acceptance tests.  
I would like to finish and post a merge request.  
However, since you were first to assign the issue to yourself, I will stop if you would rather complete it.

**Comment by kamilturek** [comment]
@HubbardHarvey3 Sorry, I had no idea someone is already working on it. Please finish your work. I'll unassign myself.

**Comment by HubbardHarvey3** [comment]
No worries, I should have posted a comment earlier.
Thank you very much for understanding.
