### ISSUE TITLE
[Solved]: aws_ram_principal_association Organizations & Organizations Organization Unit not implemented

### ISSUE THREAD

**Issue by themonnie** [hashicorp/terraform-provider-aws#36254]
### Terraform Core Version

1.7.4

### AWS Provider Version

5.39.1

### Affected Resource(s)

aws_ram_principal_association

### Expected Behavior

According to the documentation 
```hcl
resource "aws_ram_principal_association" "example" {
  principal          = aws_organizations_organization.example.arn 
  resource_share_arn = aws_ram_resource_share.example.arn
}
```

[principal](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ram_principal_association#principal) - (Required) The principal to associate with the resource share. Possible values are an AWS account ID, an AWS Organizations Organization ARN, or an AWS Organizations Organization Unit ARN.

### Actual Behavior

Is not supported, and will not support it according to the source code. There is also a test in go that is exclusively for whole numbers.

Not Supported:

- Organization ID format: o-{10-32 characters}.
- Organizational unit ID format: ou-{4-32 characters}-{8-32 characters}.

### Relevant Error/Panic Output Snippet

```shell
Error: "principal" (ou-a1b2-a1b2c3d4) is an invalid ARN: arn: invalid prefix
│ 
│   with module.IPAM.aws_ram_principal_association.OU-Root-Prod,
│   on IPAM/ram-ipam.tf line 102, in resource "aws_ram_principal_association" "OU-Root-Prod":
│  102:   principal          = "ou-a1b2-a1b2c3d4"
```

### Terraform Configuration Files

# it is correctly described in the documentation unfortunately not implemented 
```hcl
resource "aws_ram_principal_association" "example" {
  principal          = aws_organizations_organization.example.arn 
  resource_share_arn = aws_ram_resource_share.example.arn
}
```

### Steps to Reproduce

# Attention, this only works within an AWS organization where RAM is also active in the organization as a service.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @themonnie 👋 Thanks for coming back and following up! Since you've figured this one out, I'll close it out. If you run into any other issues, please do let us know!
