### ISSUE TITLE
[Docs]: AWS EKS Access Entries setting bootstrap_cluster_creator_admin_permissions is not set to true by default

### ISSUE THREAD

**Issue by gygitlab** [hashicorp/terraform-provider-aws#36259]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#bootstrap_cluster_creator_admin_permissions

### Description

The documentation suggests that the AWS EKS Access Entries setting `bootstrap_cluster_creator_admin_permissions` is set to `true` by default, matching what happens in the AWS console.

This isn't the case. As a result if this setting is missed new AWS EKS clusters are not configured to allow admin access for the Principal that creates the cluster.

The docs also don't mention the clash that happens subsequently with this setting but this has already [been raised separately](https://github.com/hashicorp/terraform-provider-aws/issues/35824) - `ignore_changes` is required basically.

### References

https://docs.aws.amazon.com/eks/latest/userguide/access-entries.html

### Would you like to implement a fix?

No

**Comment by mohammed-bachrouch** [comment]
I noticed this issue as well.
