### ISSUE TITLE
[Enhancement]: Add DedicatedLogVolume to aws_db_instance

### ISSUE THREAD

**Issue by cdobbyn** [hashicorp/terraform-provider-aws#36276]
### Description

When you grow a database beyond 1000GiB on a provisioned IOPS disk with io >= 3000 you can enable a dedicated log volume for transaction logs to improve performance. This capability is missing in this provider. It does appear to be in the aws-sdk-go project from my limited knowledge here:
https://github.com/aws/aws-sdk-go/blob/main/models/apis/rds/2014-10-31/api-2.json#L3687

`DedicatedLogVolume` as an optional boolean

This would be helpful

### Affected Resource(s) and/or Data Source(s)

* aws_db_instance

### Potential Terraform Configuration

```terraform
resource "aws_db_instance" "default" {
  # ... general other db instance config ...
  allocated_storage    = 1000
  iops                 = 3000
  storage_type         = "io1"

  log_volume           = true
}
```

### References

https://github.com/aws/aws-sdk-go/blob/main/models/apis/rds/2014-10-31/api-2.json#L3687

### Would you like to implement a fix?

No

**Comment by askreet** [comment]
I'd like to pick this up to implement. I saw a similar enhancement [here](https://github.com/hashicorp/terraform-provider-aws/pull/36471) which seems like I could use as a template. Expect a PR shortly :).
