### ISSUE TITLE
Amazon VPC DHCPv6 setting to adjust IPv6 preferred lease time

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#36270]
> Today, Amazon VPC added a new feature to its DHCP option set called IPv6 preferred lease time setting, which allows customers to adjust the frequency of IPv6 lease renewals.

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/03/amazon-vpc-dhcpv6-setting-ipv6-lease-time/)
* [API reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateDhcpOptions.html)

#### Affected Resources

* `aws_vpc_dhcp_options`
* `aws_default_vpc_dhcp_options`

```hcl
resource "aws_vpc_dhcp_options" "example" {
  ipv6_preferred_lease_time = 360
}
```

**Comment by ddericco** [comment]
This is being worked on.
