### ISSUE TITLE
[Enhancement]: Add support for IPv6 only network type in Lightsail instances 

### ISSUE THREAD

**Issue by LucienZhang** [hashicorp/terraform-provider-aws#36284]
### Description

AWS now support IPv6 only instance bundles, and the instances with IPv4 address will get charged starting May 1, 2024. Please add support for IPv6 only network type in Lightsail instances

### Affected Resource(s) and/or Data Source(s)

* aws_lightsail_instance

### Potential Terraform Configuration

```terraform
resource "aws_lightsail_instance" "gitlab_test" {
  name              = "custom_gitlab"
  availability_zone = "us-east-1b"
  blueprint_id      = "amazon_linux_2"
  bundle_id         = "nano_1_0"
  key_pair_name     = "some_key_name"
  ip_address_type  = "ipv6"
  tags = {
    foo = "bar"
  }
}
```

### References

https://aws.amazon.com/cn/blogs/compute/announcing-ipv6-instance-bundles-and-pricing-update-on-amazon-lightsail/

### Would you like to implement a fix?

Yes

**Comment by anderson-oki** [comment]
@LucienZhang 

It is a different bundle id, you should use `bundle_id = "nano_ipv6_3_0"` instead.

**Comment by nbensa** [comment]
I think this can be close as I just created a ipv6-only instance 
```
resource "aws_lightsail_instance" "my-ipv6-only-instance" {                                               
  availability_zone = "us-east-2a"                                                                                                                                                                                   
  name              = "my-ipv6-only-instance"
  blueprint_id      = "ubuntu_22_04"
  bundle_id         = "small_ipv6_3_0"
  key_pair_name     = aws_lightsail_key_pair.ansible.name 
  ip_address_type   = "ipv6"
}
```

![image](https://github.com/hashicorp/terraform-provider-aws/assets/2554495/bb71ba7f-332f-4743-b4cb-73131f08377d)

**Comment by LucienZhang** [comment]
> It is a different bundle id, you should use `bundle_id = "nano_ipv6_3_0"` instead.

@anderson-oki 
Thank you, that works, because changing bundle id forces replacement though.
