### ISSUE TITLE
[Bug]: Update the AWS RDS storage_type from gp2 to gp3

### ISSUE THREAD

**Issue by mahi845** [hashicorp/terraform-provider-aws#36293]
### Terraform Core Version

v1.5.7

### AWS Provider Version

v5.40.0

### Affected Resource(s)

AWS RDS Postgres

### Expected Behavior

Change the storage type from gp2 to gp3

### Actual Behavior

We are currently facing challenges in changing the storage type for our PostgreSQL database from gp2 to gp3 using Terraform. 

Scenario:1
We have previously attempted to make to update storage_type from gp2 to gp3 for storage size 20 by utilizing the storage_throughput and provisioned IOPS parameters, as the default IOPS value was 0. However, we encountered difficulties and were unable to achieve the desired outcome it updated the storage type from gp2 to io1

```
provisioned_iops                = 3000
storage_throughput           = 125
```

Scenario:2
Our previous attempts to effect this change by specifying provisioned IOPS and storage throughput parameters, with provisioned_iops set to 3000 and storage_throughput to 125, did not yield the expected results. Furthermore, our investigation has revealed that we are unable to specify IOPS or storage throughput for the PostgreSQL engine when the storage size is less than 400.

In an effort to address this, we conducted tests by increasing the allocated storage to 500 and setting the max_allocated_storage to 700, without specifying the storage_throughput and provisioned IOPS parameters. Additionally, we have also attempted the configuration with an IOPS value of 12000 for the increased storage allocation.

allocated_storage               = 500
max_allocated_storage       = 700

Scenario: 3

Now we have also attempted the configuration with an IOPS value of 12000 for the increased storage allocation

allocated_storage               = 500
max_allocated_storage       = 700
iops                                     = 12000

The storage type remains set as io1 instead of gp3

### Relevant Error/Panic Output Snippet

```shell
.
```

### Terraform Configuration Files

allocated_storage               = 500
max_allocated_storage       = 700
iops                                     = 12000 

### Steps to Reproduce

allocated_storage               = 500
max_allocated_storage       = 700
iops                                     = 12000

### Important Factoids

Kindly request your support and expertise in resolving this issue and facilitating the transition from gp2 to gp3 storage type for our PostgreSQL database using Terraform.

 https://github.com/hashicorp/terraform-provider-aws/issues/28271 reviewed the issue and attempted various steps to rectify the situation, but unfortunately, we have not achieved the desired success

### References
https://github.com/hashicorp/terraform-provider-aws/issues/28271
[[_No response_](https://github.com/terraform-aws-modules/terraform-aws-rds/commit/9c8d21fc07d798203b1e96fa893e68d1fa04058e)](https://github.com/terraform-aws-modules/terraform-aws-rds/commit/9c8d21fc07d798203b1e96fa893e68d1fa04058e)

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @mahi845 👋 Thank you for taking the time to raise this! I saw a somewhat similar issue in the past and wrote up [this answer](https://github.com/hashicorp/terraform-provider-aws/issues/28382#issuecomment-1398942979) that seems to have helped a few people. Can you take a look over that comment and see if it helps in your scenario as well?

**Comment by mahi845** [comment]
"[etiennechabert](https://github.com/etiennechabert)
can you please support here ran to same issue where you mentioned in the issue https://github.com/hashicorp/terraform-provider-aws/issues/28271, initially i tried with setting iops to a default value of 0:

Do we need to specify storage_throughput parameter for updating the storage type to gp3 ?

**Comment by justinretzolk** [comment]
Hey @mahi845 👋 Thanks for trying that out. I think we'll need a bit more information in order to look into this effectively. I've got a couple specific questions:

- Can you supply a sample configuration that can be used to reproduce what you're seeing? I'm particularly interested in what you might have set for `maintenance_window` and/or `apply_immediately`.
- Are you seeing any errors?
