### ISSUE TITLE
[Bug]: private_ip_list does not order the ip's correctly

### ISSUE THREAD

**Issue by jgrammen-agilitypr** [hashicorp/terraform-provider-aws#36300]
### Terraform Core Version

1.7.1

### AWS Provider Version

5.33.0

### Affected Resource(s)

aws_network_interface

### Expected Behavior

ip's assigned to `private_ip_list` when  `private_ip_list_enabled = true` should be added to vm in listed order

### Actual Behavior

private ip's are in wrong order

ip list on the vm
```
ubuntu@vm01:~$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
    link/ether 0a:7f:c8:43:55:ea brd ff:ff:ff:ff:ff:ff
    altname enp0s5
    inet 10.6.150.200/24 brd 10.6.150.255 scope global ens5
       valid_lft forever preferred_lft forever
    inet 10.6.150.201/24 brd 10.6.150.255 scope global secondary dynamic ens5
       valid_lft 3552sec preferred_lft 3552sec
    inet6 fe80::87f:c8ff:fe43:55ea/64 scope link
       valid_lft forever preferred_lft forever
ubuntu@ca06vlhaproxy01:~$ ip route show
default via 10.6.150.1 dev ens5 proto dhcp src 10.6.150.201 metric 100
10.6.150.0/24 dev ens5 proto kernel scope link src 10.6.150.200
10.6.150.1 dev ens5 proto dhcp scope link src 10.6.150.201 metric 100
```
teraform network interface

```terraform
resource "aws_network_interface" "serverEth0" {
  subnet_id       = var.subnet_production["ApiGateway ALL"]
  security_groups = module.ingress_rules.security_group_id
  private_ip_list_enabled = true
  private_ip_list = var.server_ip[count.index]
  tags = {
    Name = "${var.hostname[count.index]}-eth0"
  }
  count     = var.server_count["nodes"]
}
```

variable with list of ip's `.201` should be the primary ip on the vm, with `.200` being the secondary, but `.201` ends up as the secondary

```terraform
variable "server_ip" {

  default = {
    0 = ["10.6.150.201","10.6.150.200"]
    1 = ["10.6.150.202"]
  }
}
```

### Terraform Configuration Files

```terraform
resource "aws_instance" "vm01" {
  key_name      = var.keypair
  ami           = ami-0489f04c874d191e7
  instance_type = "t3.medium"

  network_interface {
    network_interface_id = aws_network_interface.serverEth0[count.index].id
    device_index         = 0
  }
  root_block_device {
    volume_type = "gp3"
    volume_size = 20
  }
}

resource "aws_network_interface" "serverEth0" {
  subnet_id       = var.subnet_production["ApiGateway ALL"]
  security_groups = module.ingress_rules.security_group_id
  private_ip_list_enabled = true
  private_ip_list = var.server_ip[count.index]
  tags = {
    Name = "${var.hostname[count.index]}-eth0"
  }
  count     = var.server_count["nodes"]
}

variable "server_ip" {

  default = {
    0 = ["10.6.150.201","10.6.150.200"]
    1 = ["10.6.150.202"]
  }
}
```

### Steps to Reproduce

spin up vm, with 2 private ip's, notice that ip's in wrong order

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @jgrammen-agilitypr 👋 Thank you for taking the time to raise this! I took a look at your example configuration, and it looks like the result you're getting is due to the order of values in the `server_up` variable. The [`private_ip_list` argument reference](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/network_interface#private_ip_list) mentions this (emphasis mine): 

> List of private IPs to assign to the ENI **in sequential order**.

The [code](https://github.com/hashicorp/terraform-provider-aws/blob/77c7c861d92d78fcc1104ec19a8397f3b8201b9f/internal/service/ec2/vpc_network_interface.go#L1219-L1221) seems to validate this theory -- can you verify with your configuration as well?

**Comment by jgrammen-agilitypr** [comment]
Sorry, I am not sure if I understand correctly what you are saying.
Are you telling me that the list passed to `private_ip_list` will be numerically ordered first, before the ip's are passed to the network interface?
Does this mean there is no way to force a specific ordering of the ip's?

because I am providing the list in `0 = ["10.6.150.201","10.6.150.200"]` order (`.201` as the primary)
but the vm has the ip's in the reverse order (`.200` as the primary)
```
2: ens5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
    link/ether 0a:7f:c8:43:55:ea brd ff:ff:ff:ff:ff:ff
    altname enp0s5
    inet 10.6.150.200/24 brd 10.6.150.255 scope global ens5
       valid_lft forever preferred_lft forever
    inet 10.6.150.201/24 brd 10.6.150.255 scope global secondary dynamic ens5
       valid_lft 3552sec preferred_lft 3552sec
    inet6 fe80::87f:c8ff:fe43:55ea/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by justinretzolk** [comment]
Thanks for the follow up here @jgrammen-agilitypr -- the misunderstanding in this case was on my part 🙂; apologies for that. Looking at the [bit of the code that handles this](https://github.com/hashicorp/terraform-provider-aws/blob/77c7c861d92d78fcc1104ec19a8397f3b8201b9f/internal/service/ec2/vpc_network_interface.go#L1206-L1224) (note: this is just a larger snippet of what I linked to before, if you'd already reviewed that), I would have expected that the first IP in the list would be marked as the primary (so `.201`, like you expected as well).

Since that's not happening, are you able to supply debug logging (redacted as needed) so that whoever picks this issue up to look into it has that as well?

**Comment by jgrammen-agilitypr** [comment]
out of curiosity I did some additional verification and noticed the following:
![image](https://github.com/hashicorp/terraform-provider-aws/assets/22965146/208dc589-22a7-4ba3-9397-a570355153b4)
that is the aws dashboard, which is indicating the ip's were correctly assigned. Yet in the OS, they are still in the incorrect order. I am now not sure if this is a terraform aws provider issue or and Aws cloud init issue.

If you still want debug logs I will gather them, but if this is obviously not a terraform thing then probably should just close the ticket.

**Comment by jgrammen-agilitypr** [comment]
After discussing with AWS support, I have found a solution. This is not a terraform or terraform aws provider bug. 
For future searches the solution is as follows:
disable cloud init networking
```
echo "network: {config: disabled}" | sudo tee /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
```
edit
```
/etc/netplan/50-cloud-init.yaml
```
to contain the correct set of ip's in the order desired
```
network:
ethernets:
ens5:
addresses:
- 10.10.5.15/24
- 10.10.5.16/24
dhcp4: true
dhcp6: false
match:
macaddress: 0a:ef:53:c2:0b:88
set-name: ens5
version: 2
```
or remove the whole addresses section from 50-cloud-init.yaml and create a new file containing the ip's desired in the correct order.

```
- [ sh, -c, "sudo printf 'network:\n  version: 2\n  renderer: networkd\n  ethernets:\n    ens5:\n      addresses:\n%{ for addr in server_ip }      - ${addr}/24\n%{ endfor ~}' > /etc/netplan/60-secondary-ip.yaml" ]
```
this will result in the correct merged output from netplan
```
sudo netplan --debug apply
```
