### ISSUE TITLE
terraform wants to update aws_lambda_function's last_modified even when lifecycle prevents it

### ISSUE THREAD

**Issue by grimm26** [hashicorp/terraform-provider-aws#3630]
My terraform configs are in git and one of several people could clone the repository to make changes through pull requests.  Some of these configs have `aws_lambda_function`s with the function file there in the same directory.  There is a lifecycle rule to ignore changes in the filename since each person may clone the tf config repo into a unique location.  Since v1.10 of the aws provider, we get spammed with plans that insist they will update the last_modfied of the aws_lambda_function but it does not.

### terraform version
```
> $ terraform -v
Terraform v0.11.3
+ provider.archive v1.0.0
+ provider.aws v1.10.0
```

### Affected Resource(s)
- aws_lambda_function

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "aws" {}

resource "aws_lambda_function" "funk" {
  description      = "Bring da funk"
  filename         = "${path.module}/funk.zip"
  function_name    = "funk"
  role             = "arn:aws:iam::643927032162:role/iam_for_lambda"
  handler          = "funk.lambda_handler"
  runtime          = "python3.6"
  source_code_hash = "${data.archive_file.funk_zip.output_base64sha256}"
  timeout          = "300"

  # Ignore changes in path that happen when different people apply.  We have source_code_hash to track actual code changes.
  lifecycle {
    ignore_changes = ["filename"]
  }
}

data "archive_file" "funk_zip" {
  type        = "zip"
  source_file = "${path.module}/funk.py"
  output_path = "${path.module}/funk.zip"
}
```

### Debug Output
https://gist.github.com/grimm26/5380931a0816a5b8e6966083c55d9c6b

### Expected Behavior
Since lifecycle setting informs the resource to not update on filename change, a plan should not indicate that last_modified will be updated.

### Actual Behavior
https://gist.github.com/grimm26/db40de2d562f46dd05c49690f79b6a14

### Steps to Reproduce
1. create a config with an `aws_lambda_function` using the `filename` argument and the function's file in that directory.
2. `terraform apply`
3. copy or  move the config to a new directory and change nothing else.
4. `terraform apply`

**Comment by ChineduUzoka** [comment]
You can (if it helps your case) ignore_changes = ["source_code_hash", "last_modified"].   

It works because im using the following:
resource "null_resource" "lambda_deployment" {
  provisioner "local-exec" "[script that executes pip install -r requirements.txt]"
  triggers {
    lambda_handler_code_file = "${md5(file(local.lambda_handler_code_file))}"
  }
}
data "archive_file" "lambda_deploy" {
  type        = "zip"
  source_dir  = "${local.lambda_build_dir}/"
  output_path = "${local.archive_zip_file}"
  depends_on  = ["null_resource.lambda_deployment"]
}

resource "aws_lambda_function" "....." {
  ...
  ...
  source_code_hash  = "${data.archive_file.lambda_deploy.output_base64sha256}"
  ...
}

So aws_lambda_function is triggered by a trigger in null_resource 

I hope that helps

**Comment by grimm26** [comment]
@ChineduUzoka but I need to ignore filename.  Which I now realize brings up another problem.  If I ignore filename, it doesn't have the proper filename when the hash changes to do a deploy.  This is a a pain.

**Comment by rafalcieslak** [comment]
Doesn't it suffice to `ignore_changes` to *only* `last_modified`?

**Comment by grimm26** [comment]
@rafalcieslak No, that results in this on step 4 of my steps to reproduce:
```
> $ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.archive_file.funk_zip: Refreshing state...
aws_lambda_function.funk: Refreshing state... (ID: funk)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ aws_lambda_function.funk
      filename: "/tmp/mk1/funk.zip" => "/tmp/mk2/funk.zip"


Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------
```

**Comment by quixand** [comment]
> You can (if it helps your case) ignore_changes = ["source_code_hash", "last_modified"].
> 
> It works because im using the following:
> resource "null_resource" "lambda_deployment" {
> provisioner "local-exec" "[script that executes pip install -r requirements.txt]"
> triggers {
> lambda_handler_code_file = "${md5(file(local.lambda_handler_code_file))}"
> }
> }
> data "archive_file" "lambda_deploy" {
> type = "zip"
> source_dir = "${local.lambda_build_dir}/"
> output_path = "${local.archive_zip_file}"
> depends_on = ["null_resource.lambda_deployment"]
> }
> 
> resource "aws_lambda_function" "....." {
> ...
> ...
> source_code_hash = "${data.archive_file.lambda_deploy.output_base64sha256}"
> ...
> }
> 
> So aws_lambda_function is triggered by a trigger in null_resource
> 
> I hope that helps

This unfortunately results in terraform reporting an action, even though there are no changes.
```An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
 <= read (data resources)

Terraform will perform the following actions:

 <= module.mymodule.data.archive_file.my-script
      id:                  <computed>
      output_base64sha256: <computed>
      output_md5:          <computed>
      output_path:         "../../../../Modules/mymodule/script.zip"
      output_sha:          <computed>
      output_size:         <computed>
      source.#:            <computed>
      source_file:         "../../../../Modules/mymodule/script.py"
      type:                "zip"


Plan: 0 to add, 0 to change, 0 to destroy.
```

rather than the much preferable "No changes. Infrastructure is up-to-date."
