### ISSUE TITLE
[Bug]: modification of cache_usage_limits (ecpu_per_second or data_storage maximum) in aws_elasticache_serverless_cache results in replacement

### ISSUE THREAD

**Issue by mshahmoradi87** [hashicorp/terraform-provider-aws#36317]
### Terraform Core Version

1.5.5

### AWS Provider Version

5.40.0

### Affected Resource(s)

aws_elasticache_serverless_cache

### Expected Behavior

Change in limits should not destroy and recreate the cache, but just change the limit

### Actual Behavior

if I change a limit, TF replaces the module, resulting in destroy and creation of the cache. 

### Terraform Configuration Files

```terraform
resource "aws_elasticache_serverless_cache" "example" {
  engine = "redis"
  name = "example"
  
  cache_usage_limits {
    data_storage {
      maximum = 1
      unit = "GB"
    }

    ecpu_per_second {
      maximum = 1000
    }
  }

  daily_snapshot_time = "09:00"
  description = "Test Server"
  kms_key_id = aws_kms_key.test.arn
  major_engine_version = "7"
  snapshot_retention_limit = 1
  security_group_ids = [aws_security_group.test.id]
  subnet_ids = aws_subnet.test[*].id
}
```

### Steps to Reproduce

- create a redics cache and change one or both of the data_storage and ecpu and apply

### Would you like to implement a fix?

No

**Comment by emdneto** [comment]
I'm not sure if it's a bug, as this is defined [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/elasticache/serverless_cache.go#L201).

However, I agree that we don't need to replace the resource when changing the cache_usage_limits since AWS allows to change the limits with in-place updates. 

Can anyone tell me if we really need RequiresReplace() for this case? If not, I can fix by removing this to allow update in-place when we set limits.

**Comment by mshahmoradi87** [comment]
> I'm not sure if it's a bug, as this is defined [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/elasticache/serverless_cache.go#L201).
> 
> However, I agree that we don't need to replace the resource when changing the cache_usage_limits since AWS allows to change the limits with in-place updates.
> 
> Can anyone tell me if we really need RequiresReplace() for this case? If not, I can fix by removing this to allow update in-place when we set limits.

Thanks for checking , it does not need to be replaced and in aws console you can change the limits.
however this has been added [here](https://github.com/hashicorp/terraform-provider-aws/pull/35927/files#diff-7c0d05f98a7e0cbd9b8b72210f2272d1e1434c690ba01a518b48df5effd17e00R201) , to fix the previous bug #35897 , and produced this new bug.

**Comment by mshahmoradi87** [comment]
> I'm not sure if it's a bug, as this is defined [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/elasticache/serverless_cache.go#L201).
> 
> However, I agree that we don't need to replace the resource when changing the cache_usage_limits since AWS allows to change the limits with in-place updates.
> 
> Can anyone tell me if we really need RequiresReplace() for this case? If not, I can fix by removing this to allow update in-place when we set limits.

@ewbankkit can you help to answer this question please.

**Comment by mshahmoradi87** [comment]
@justinretzolk any chance this gets some attention please ?
