### ISSUE TITLE
r/aws_network_acl_rule: Prevent creation of duplicate Terraform resources

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#36324]
Define multiple ACL rules with identical attributes but different Terraform resource names.
Example:

```hcl
resource "aws_network_acl_rule" "original-rule" {
  network_acl_id = aws_network_acl.vpc-test.id
  rule_number = 200
  egress = false
  protocol = "tcp"
  rule_action = "allow"
  cidr_block = "10.0.0.0/24"
  from_port = 22
  to_port = 22
}

resource "aws_network_acl_rule" "new-rule" {
  network_acl_id = aws_network_acl.vpc-test.id
  rule_number = 200
  egress = false
  protocol = "tcp"
  rule_action = "allow"
  cidr_block = "10.0.0.0/24"
  from_port = 22
  to_port = 22
}
```

* Apply the Terraform configuration.
* Delete one of the ACL rules.
* Observe the unexpected removal of the corresponding Network ACL entry from AWS.

The EC2 [`CreateNetworkAclEntry`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateNetworkAclEntry.html) API succeeds on the second resource Create if all attributes are identical. Prevent this.

**Comment by ewbankkit** [comment]
Check also `aws_route` and security group rules.

**Comment by jhenry82** [comment]
So I understand the rationale for fixing the issue of creating duplicate resources. It has left us in a bit of a bind, however. We are using an in-house module that inadvertently created some duplicate `aws_route` resources. Today we upgraded to the latest provider release, and the module began failing on those duplicate routes. I can easily remove one set of routes from the code. But if I do that, Terraform of course wants to delete the route. Then we have to do another plan and apply so it notices the route is gone, and recreates it using the remaining copy of the aws_route resource. Doing this in production will cause an outage. Which I would **really** like to avoid. Finding a breaking change in a minor version release is also frustrating, even if it is technically correct.

Do you have any suggested workarounds? I tried using various `moved{}` blocks in the hopes that would prevent Terraform from deleting the route, but it had no effect. The best I can come up with is making sure we do a "terraform state rm" on the affected routes before applying.

**Comment by ewbankkit** [comment]
@jhenry82 You should be able to use a [`removed` block](https://developer.hashicorp.com/terraform/language/resources/syntax#removing-resources).
