### ISSUE TITLE
[Bug]: Missing support for multiple kernels in sagemaker_image_config_app

### ISSUE THREAD

**Issue by dsradecki** [hashicorp/terraform-provider-aws#36321]
### Terraform Core Version

v1.5.7

### AWS Provider Version

5.40.0

### Affected Resource(s)

aws_sagemaker_app_image_config

### Expected Behavior

`kernel_gateway_image_config` should be able to handle multiple `kernel_specs` as it is stated in the API docs: https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateAppImageConfig.html

This can be achieved with the API call like:

```
{
    "AppImageConfigName": "test-config",
    "KernelGatewayImageConfig": {
        "KernelSpecs": [
            {
                "Name": "1",
                "DisplayName": "1"
            },
            {
                "Name": "2",
                "DisplayName": "2"
            }
        ],
        "FileSystemConfig": {
            "MountPath": "/home/sagemaker-user",
            "DefaultUid": 1000,
            "DefaultGid": 100
        }
    }
}
```

### Actual Behavior

`kernel_gateway_image_config` can handle only a single `kernel_spec`

### Relevant Error/Panic Output Snippet

When trying to add multiple kernel_spec blocks:

```shell
Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + image_arn = (known after apply)
  + image_id  = (known after apply)
╷
│ Error: Too many kernel_spec blocks
│ 
│   on main.tf line 16, in resource "aws_sagemaker_app_image_config" "this":
│   16:       content {
│ 
│ No more than 1 "kernel_spec" blocks are allowed
```

When trying to pass `kernel_specs` as it is in the API docs:

```shell
│ Error: Unsupported argument
│
│  on main.tf line 13, in resource "aws_sagemaker_app_image_config" "this":
│  13:   kernels_specs = var.kernel_specs
│
│ An argument named "kernels_specs" is not expected here.
```

### Terraform Configuration Files

To have multiple `kernel_spec`:

```
resource "aws_sagemaker_app_image_config" "this" {
  app_image_config_name = var.app_image_config_name

  kernel_gateway_image_config {
    kernels_specs = var.kernel_specs

    file_system_config {
      default_gid = var.file_system_config["default_gid"]
      default_uid = var.file_system_config["default_uid"]
      mount_path  = var.file_system_config["mount_path"]
    }
  }
}

```
or to have single param `kernel_specs` accepting a list of `kernel_spec` as it is expected by the API:

```
resource "aws_sagemaker_app_image_config" "this" {
  app_image_config_name = var.app_image_config_name

  kernel_gateway_image_config {
    dynamic "kernel_spec" {
      for_each = var.kernel_specs

      content {
        name         = kernel_spec.value["name"]
        display_name = kernel_spec.value["display_name"]
      }
    }

    file_system_config {
      default_gid = var.file_system_config["default_gid"]
      default_uid = var.file_system_config["default_uid"]
      mount_path  = var.file_system_config["mount_path"]
    }
  }
}
```

### Steps to Reproduce

Configure the above examples.

### Would you like to implement a fix?

None

**Comment by deepakbshetty** [comment]
Should be simple fix to change MaxItems to 5
https://github.com/hashicorp/terraform-provider-aws/blob/6dec0f1742876817018855002610ac51a42fb539/internal/service/sagemaker/app_image_config.go#L123

**Comment by DrFaust92** [comment]
[deepakbshetty](https://github.com/deepakbshetty), would you like to submit a PR with the fix?

**Comment by deepakbshetty** [comment]
Dear @DrFaust92 , I am currently on annual holiday and happy to pick this up mid April when I am back.
