### ISSUE TITLE
Support for Cognito user pool client UI customizations

### ISSUE THREAD

**Issue by rprieto** [hashicorp/terraform-provider-aws#3634]
Hi,

AWS supports [customizing Cognito UserPool app clients](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-ui-customization.html) with CSS and a logo.

<img width="233" alt="image" src="https://user-images.githubusercontent.com/189105/37007653-7bf6d03e-2132-11e8-9131-c71065767291.png">

This can be done in the AWS Console UI and using the CLI. It doesn't seem to be available in CloudFormation yet.

- https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/get-ui-customization.html
- https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/set-ui-customization.html

I don't think the Terraform provider currently supports this. Is this on the roadmap?

- Terraform Version = `0.11.3`
- Affected Resource(s)
  - [cognito_user_pool_client](https://www.terraform.io/docs/providers/aws/r/cognito_user_pool_client.html)

Thanks!

**Comment by jayudhandha** [comment]
Any update on this?

**Comment by gdlx** [comment]
@rprieto @jayudhandha I've just sent a pull request for the feature: #8114 
Does that fit your needs ?

**Comment by rprieto** [comment]
It looks perfect @gdlx, thanks!

**Comment by slaw1980** [comment]
@gdlx Any chance the #8114 PR can be merged soon? 
We're looking at updating our cognito terraform script to set the ui image, so this would be very helpful.

**Comment by gdlx** [comment]
@slaw1980 Sadly, I'm not the one who decides when to merge or not. You can start by adding a 👍 on my PR description, the dev team uses this to prioritize PR reviewing.

**Comment by mack1040** [comment]
Please can we merge this PR??
It would be extremely useful and remove the need to use the CLI as well as terraform/CloudFormation

**Comment by gdlx** [comment]
> Please can we merge this PR??
> It would be extremely useful and remove the need to use the CLI as well as terraform/CloudFormation

@mack1040 As told to @slaw1980, you should upvote on the PR, and explain your use case there (instead of the issue) to help the reviewers prioritize it.
