### ISSUE TITLE
[Bug]: aws_rds_cluster_parameter_group should not provide parameter values already applied to the API call.

### ISSUE THREAD

**Issue by freddycervantes** [hashicorp/terraform-provider-aws#36340]
### Terraform Core Version

1.7.4

### AWS Provider Version

5.39.1

### Affected Resource(s)

This is affecting all AWS provider versions.
* [aws_rds_cluster_parameter_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_parameter_group)
* [aws_db_parameter_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_parameter_group)

### Expected Behavior

Given I am managing a cluster parameter group attached to a database, as shown below, with a static parameter already set

```terraform
terraform {
  required_version = ">= 0.12"
}

provider "aws" {
  region = "us-west-2"
}

resource "aws_rds_cluster_parameter_group" "test" {
  name        = "rds-cluster-pg"
  family      = "aurora-mysql5.7"
  description = "RDS test cluster parameter group"

  parameter {
    name  = "binlog_format"
    value = "ROW"
    apply_method = "pending-reboot"
  }
}
```

When I add a dynamic parameter as shown below

```terraform
resource "aws_rds_cluster_parameter_group" "test" {
  name        = "rds-cluster-pg"
  family      = "aurora-mysql5.7"
  description = "RDS test cluster parameter group"

  parameter {
    name  = "binlog_format"
    value = "ROW"
    apply_method = "pending-reboot"
  }
  parameter {
    name  = "innodb_lock_wait_timeout"
    value = "10"
    apply_method = "pending-reboot"
  }
}
```

Then, the DB cluster parameter attached to my cluster should be in sync, not in the pending reboot state, because I only added a dynamic parameter change.

In short,
the module must filter out already set values from the API call if the value has not changed.

### Actual Behavior

Terraform is not filtering out already-set parameters from the API call to AWS, which causes AWS to reset static parameters that are already set. As a result, the status of the parameter group changes from in sync to pending reboot. AWS has already confirmed that in an API call, if you provide a static parameter with a value, even if it has already been set, the DB parameter group will be sent into a pending reboot state.

### Relevant Error/Panic Output Snippet

```shell
Just to let you know, this has no error associated since apply is successful.
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = ">= 0.12"
}

provider "aws" {
  region = "us-west-2"
}

resource "aws_rds_cluster_parameter_group" "test" {
  name        = "rds-cluster-pg"
  family      = "aurora-mysql5.7"
  description = "RDS test cluster parameter group"

  parameter {
    name  = "binlog_format"
    value = "ROW"
    apply_method = "pending-reboot"
  }
}

```

### Steps to Reproduce

Via Terraform
* Deploy an aurora cluster (mysql for example)
* Manage the cluster parameter group via Terraform
* Set the value for any static parameter, example binlog_format=ROW
* Reboot the instance so that parameter groups are in-sync
* Then add parameter a dynamic one that does not require a reboot. example innodb_lock_wait_timeout=10
* Apply the changes via terraform
* You will see your database parameter group in pending-reboot status

If you do this via AWS UI, you will see that the parameter group does not go into the pending reboot state.

### Debug Output

No Response

### Panic Output

No Response

### Important Factoids

No Response

### References

No Response

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @freddycervantes 👋 Thank you for taking the time to raise this! While triaging, I took a quick glance, and if my read of the [code](https://github.com/hashicorp/terraform-provider-aws/blob/1d69883a6880fd51a2b8702c4bb073595bfbe9d1/internal/service/rds/cluster_parameter_group.go#L226-L281) is correct, the provider should only be updating parameters that are new/changed. With that in mind, are you able to supply debug logs (redacted as needed) in case whoever picks this up needs that information?

**Comment by freddycervantes** [comment]
We can close this, I found it was due to pending-reboot apply method of the dynamic parameter. Even though AWS applies the value immediately, it sends the db param group into pending-reboot state
