### ISSUE TITLE
[New Data Source]: aws_apprunner_service.zone_id  

### ISSUE THREAD

**Issue by 1oglop1** [hashicorp/terraform-provider-aws#36359]
### Description

Loadbalancers have property `zone_id` https://github.com/hashicorp/terraform-provider-aws/blob/4200c762e39be193f02204df986ff799538483db/internal/service/elb/hosted_zone_id_data_source.go#L18C5-L18C29 

It would be great to have the `zone_id` property available for creation of R53 Aliases.

### Requested Resource(s) and/or Data Source(s)

* aws_apprunner_service.zone_id

### References

AWS appruner has very similar functionality and publicly available hosted zone IDs https://docs.aws.amazon.com/general/latest/gr/apprunner.html

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@1oglop1 Thanks for raising this issue 👏.
The new `aws_apprunner_hosted_zone_id` data source has been added via https://github.com/hashicorp/terraform-provider-aws/pull/36288 and will be available in Terraform AWS Provider **v5.41.0**, likely later this week.

**Comment by 1oglop1** [comment]
@ewbankkit wow, thanks!
