### ISSUE TITLE
[Bug]: `aws_instance` wants to do an in-place update upon architecture change

### ISSUE THREAD

**Issue by dhs-rec** [hashicorp/terraform-provider-aws#36376]
### Terraform Core Version

1.7.4

### AWS Provider Version

5.40.0

### Affected Resource(s)

* aws_instance

### Expected Behavior

Instance should be replaced.

### Actual Behavior

`terraform plan` reports an in-place update:
```
Terraform will perform the following actions:

  # module.ec2.module.instances.aws_instance.instances["XXX"] will be updated in-place
  ~ resource "aws_instance" "instances" {
        id                                   = "i-042b03667e5e4ef2c"
      ~ instance_type                        = "m5.2xlarge" -> "m6g.2xlarge"
        tags                                 = {
            "Name"  = "XXX"
        }
        # (31 unchanged attributes hidden)

        # (8 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
Instance type has been changed from Intel to AWS Graviton (ARM) CPU.

### Terraform Configuration Files

```
data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}

resource "aws_instance" "web" {
  ami           = data.aws_ami.ubuntu.id
  instance_type = "t3.micro"

  tags = {
    Name = "Test"
  }

  lifecycle {
    ignore_changes = [
      ami,
      user_data,
    ]
  }
}
```

### Steps to Reproduce

Create instance using above configuration, then change

- `amd64` to `arm64` in the data source
-  `t3` to `t4g`

and run `terraform plan`.

Due to `lifecycle` the AMI change will be ignored and an in-place update will be shown (like the one above). Only if this is also changed an instance replacement will be forced.

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @dhs-rec 👋 Thank you for taking the time to raise this! This is working as expected. As you called out, you've set a `lifecycle` configuration block to ignore changes to the `ami` argument of the `aws_instance`. AWS offers an API for updating an instance's instance type, but does not offer the same for the AMI. When a change is detected only to `instance_type`, a replacement isn't (generally) necessary like it is for the `ami`. This is why your instance isn't forced into replacement until removal of the `lifecycle` block.

From my perspective, building in validation to try to check whether a particular AMI ID is compatible with the given instance type, or attempting to trigger recreation only when the instance type is changed from a certain value to another type of value isn't really the domain of the provider, and is something that could easily get out of sync and be more trouble than beneficial. Ultimately, a misconfiguration like this would fail at the AWS API level; the ultimate source of truth in terms of validating more involved interactions between resources like this. 

With the above in mind, I'm going to close this issue.

**Comment by dhs-rec** [comment]
@justinretzolk, yes, I have configured a `lifecycle` block to ignore AMI changes. However, the change in instance type from `t3`  to `t4g` indicates an architecture change, which should not be ignored and thus force a replacement. Please reopen.

**Comment by dhs-rec** [comment]
> a misconfiguration like this would fail at the AWS API level;

I don't understand. An `aws ec2 describe-instance-types` (and I suppose its language X equivalents, too) reports the supported architecture(s), like, for example:
```
        ...
        {
            "InstanceType": "g5.4xlarge",
            ...
            "ProcessorInfo": {
                "SupportedArchitectures": [
                    "x86_64"
                ],
                "SustainedClockSpeedInGhz": 3.3
            },
            ...
        },
        ...
        {
            "InstanceType": "r6g.16xlarge",
            ...
            "ProcessorInfo": {
                "SupportedArchitectures": [
                    "arm64"
                ],
                "SustainedClockSpeedInGhz": 2.5
            },
            ...
        },
        ...
```
So, terraform should be able to detect the change and act accordingly.

**Comment by YakDriver** [comment]
I'm almost certain there is no way to update an instance type without a new instance. We'll do more research and get back with a fix, if needed.

**Comment by dhs-rec** [comment]
> 4\. Perhaps the best UX would be to check when an `instance_type` changes if that also constitutes an architecture change (extra API call) and only do a "force new" in that situation.

@YakDriver, this is exactly what this issue is all about.

**Comment by YakDriver** [comment]
In the meantime, you can also look at [`replace_triggered_by`](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#replace_triggered_by).

**Comment by dhs-rec** [comment]
Thanks a lot, @YakDriver!
