### ISSUE TITLE
[Enhancement]: aws_fsx_ontap_file_system resource updates

### ISSUE THREAD

**Issue by aaronda-aws** [hashicorp/terraform-provider-aws#36389]
### Description

There are a few updates I'd like to request.

1. Update the documentation for the deployment_type argument to include deployment type of SINGLE_AZ_2.
2. Update the documentation for the storage_capacity argument to allow scaling up to 1PiB of capacity.  Suggested wording on this update would be "The storage capacity (GiB) of the file system. Valid values between 1024 and 196608 for file systems with deployment_type SINGLE_AZ_1 and MULTI_AZ_1. Valid values between 2048 and 1048576 for file systems with deployment_type SINGLE_AZ_2."
3. Update the storage_capacity argument to allow a maximum value of 1048576.
4. Change the throughput_capacity_per_ha_pair argument to allow all valid file system throughput values for both version 1 and version 2 deployment types; 128MB/s - 6144MB/s.

### Affected Resource(s) and/or Data Source(s)

Resource: aws_fsx_ontap_file_system

### References

https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/performance.html
https://docs.aws.amazon.com/fsx/latest/APIReference/API_OntapFileSystemConfiguration.html

### Would you like to implement a fix?

No

**Comment by awsaxeman** [comment]
I am working on this.
