### ISSUE TITLE
[Enhancement]: Include disclaimer about name tag field for aws_lb_listener_rule resource

### ISSUE THREAD

**Issue by dennisasilva** [hashicorp/terraform-provider-aws#36386]
### Description

**What I have found:** Today when I created the AWS ELB listener rule it works but I can't find the instruction to fulfill the the Name Tag. After searching for this option in a AWS console, I notice the name tag had the same value for tags. Of course this is a small improvement, but it can save time during the implementation process.

**What my suggestion:** Include a disclaimer in a lb_listener_rule page to explain to users if they want to use the name tag field they should use the tags.

Thank you.

### Affected Resource(s) and/or Data Source(s)

lb_listener_rule

### Potential Terraform Configuration

```terraform
Not Applicable
```

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_rule

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @dennisasilva 👋 Thank you for taking the time to raise this! I'm not sure I follow the request here. Can you provide a sample configuration, or a bit more detail as to what you'd like to see changed?

**Comment by dennisasilva** [comment]
Hello @justinretzolk, it's my pleasure to have a chance to add something to level up the repo. 

Yes, sure. For instance when you create the load balance listener rule using aws_lb_listener_rule resource and I didn't find the options to insert the name for rule, only priority, condition and so on, however, if you use the tag for deploy the listener rule the same value is reflected in name tag. Maybe it's clear for most users but it wasn't for me and my suggestion is create a note to say that if you want to deploy tag name for aws_lb_listener_rule you should use the tag value.

Please let me know if you want more details,
Thank you.

**Comment by dhull** [comment]
I think I understand this request. When you visit the load balancer listener page in the AWS console there's a "rules" tab that has a list of listener rules. The first column in the list is "Name tag". The UI doesn't make it clear where the value that is shown in the column comes from, but it's from setting a "Name" tag in the `aws_lb_listener_rule` resource. I think that this request is asking for a note in the documentation for `aws_lb_listener_rule` to point this out.

**Comment by Bexanderthebex** [comment]
@justinretzolk I'll take this on if that is ok
