### ISSUE TITLE
[Enhancement]: `aws_batch_job_queue` jobStateTimeLimitActions parameter

### ISSUE THREAD

**Issue by drewmullen** [hashicorp/terraform-provider-aws#36384]
### Description

AWS Batch now supports a Batch Job Queue Blocked CloudWatch Event for jobs stuck in RUNNABLE state. Customers can automate actions using EventBridge to be able to take an action on these stuck jobs. Additionally, customers can configure jobStateTimeLimitActions parameter from the CreateJobQueue and UpdateJobQueue APIs to terminate the stuck job unblocking the jobs behind it within the queue. 

### Affected Resource(s) and/or Data Source(s)

* aws_batch_job_queue

### Potential Terraform Configuration

```terraform
job_state_time_limit_actions {
   reason         = "string" 
   state          = "string"            
   maxTimeSeconds = number     
   action         = "string"            
}
```

### References

- blog post: https://aws.amazon.com/about-aws/whats-new/2024/03/aws-batch-alerts-detect-jobs-runnable-state/
- sdk update: https://github.com/aws/aws-sdk-go/commit/b965d6132d94bb7314bd114e3691a3f7005c191d

### Would you like to implement a fix?

Yes

**Comment by pwyliu** [comment]
@drewmullen Hello - and sorry to pry - I was wondering if the above PR could be finished off to close this issue. It's so close to the finish line and it seems only a minor looking CI issues is blocking.

In my organization we're desperately needing this feature and would benefit greatly, for Batch users operating at large scale it is tremendously useful. I think this is probably true for lots of people, so it's a shame to not be able to manage this in TF. We programatically generate our queues and have very many, so it's really tedious to manage this out of band.

**Comment by rito-sixt** [comment]
Could we have this soon please? Much needed!

**Comment by gusostow** [comment]
ANy chance we could get this merged in?
