### ISSUE TITLE
[Enhancement]: [FSx] Include options which are used when using delete API 

### ISSUE THREAD

**Issue by ashvinsharma** [hashicorp/terraform-provider-aws#36399]
### Description

In the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_openzfs_file_system), terraform takes all the options which are available in the [CreateFileSystemOpenZFS](https://docs.aws.amazon.com/fsx/latest/APIReference/API_CreateFileSystemOpenZFSConfiguration.html) call. 

But [there are fields](https://docs.aws.amazon.com/fsx/latest/APIReference/API_DeleteFileSystemOpenZFSConfiguration.html) which is required when terraform tries to recreate the FSx. Or when a user  really want to delete the filesystem. One such field is options where I want to pass `DELETE_CHILD_VOLUMES_AND_SNAPSHOTS` but I did not find anything in the documentation which would let me use this configuration. 

Can someone please add it? 

### Affected Resource(s) and/or Data Source(s)

fsx_openzfs_file_system

### Potential Terraform Configuration

```terraform
resource "aws_fsx_openzfs_file_system" "fs" {
...
delete_options {
  delete_child_volumes_and_snapshots = true
}
...
}
```

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_openzfs_file_system
https://docs.aws.amazon.com/fsx/latest/APIReference/API_DeleteFileSystemOpenZFSConfiguration.html

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
I've checked in a fix to add the `delete_options` and `final_backup_tags` arguments to the `aws_fsx_openzfs_file_system` resource. Note that Lustre and Windows file systems could also use the `final_backup_tags` argument as specified in [DeleteFileSystem](https://docs.aws.amazon.com/fsx/latest/APIReference/API_DeleteFileSystem.html).

Volumes also has similar settings for ONTAP and OpenZFS as specified in [DeleteVolume](https://docs.aws.amazon.com/fx/latest/APIReference/API_DeleteVolume.html).
