### ISSUE TITLE
[Enhancement]: Support Timestream for InfluxDB

### ISSUE THREAD

**Issue by sentros** [hashicorp/terraform-provider-aws#36398]
### Description

It's now possible to select a different engine for a Timestream database in the aws console. The previous engine is now called LiveAnalytics and a new engine was added called InfluxDB. Terraform has no support for the InfluxDB engine or for its configuration options.

If you plan to add the new engine as an option to the pre existing aws_timestreamwrite_database you could just add new parameters for it as shown in the example. At least the parameter group needs its own new resource. 

Not much is shared between the engines so maybe a whole new resource for InfluxDB type Timestream would be better. For example the RDS resource handles engine types all in the same resource but RDS engine types at least share some configuration options between them as opposed to Timestream for LiveAnalytics vs InfluxDB.

### Affected Resource(s) and/or Data Source(s)

* `aws_timestreamwrite_database`

### Potential Terraform Configuration

```terraform
resource "aws_timestreamwrite_database" "example" {
  database_name = "database-example"
  engine        = "influxdb"

  db_name           = "db-name-example"
  username          = "example-username"
  password          = "example-password"
  organization_name = "example-org"
  bucket_name       = "example-bucket"

  instance_class    = "db.influx.medium"
  storage_type      = "included-3000"
  allocated_storage = 200
  multi_az          = true

  db_subnet_group_name   = aws_db_subnet_group.example.name
  vpc_security_group_ids = [aws_security_group.example.id]
  publicly_accessible    = false

  parameter_group_name = aws_timestreamwrite_parametergroup.example.name
  s3_logs_location     = aws_s3_bucket.example.id

  tags = {
    Name = "value"
  }
}

resource "aws_timestreamwrite_parametergroup" "example" {
  name        = "example-name"
  description = "example-description"

  parameter {
    name  = "flux-log-enabled"
    value = "TRUE"
  }

  parameter {
    name  = "log-level"
    value = "error"
  }

  tags = {
    Name = "value"
  }

}
```

### References

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/03/amazon-timestream-influxdb-available/)
* [Blog post](https://aws.amazon.com/blogs/aws/run-and-manage-open-source-influxdb-databases-with-amazon-timestream/)
* [Developer Guide](https://docs.aws.amazon.com/timestream/latest/developerguide/timestream-for-influx-configuring.html#timestream-for-influx-configuring-create-db-settings)
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/timestreamwrite_database

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
At the API level _Timestream for InfluxDB_ is a [distinct service](https://docs.aws.amazon.com/ts-influxdb/latest/ts-influxdb-api/API_Operations.html).
Following our [naming guidelines](https://hashicorp.github.io/terraform-provider-aws/naming/#resources-and-data-sources) the first resource [should be](https://docs.aws.amazon.com/ts-influxdb/latest/ts-influxdb-api/API_CreateDbInstance.html):

```hcl
resource "aws_timestreaminfluxdb_db_instance" "example" {
  name = "..."
}
```

**Comment by trevorbonas** [comment]
I would like to work on this issue.

**Comment by trevorbonas** [comment]
I am working on the `aws_timestreaminfluxdb_db_instance` resource and will provide updates in the coming weeks.

So far, my implementation differs in a few ways from the proposed implementation.
- I will not be creating an `aws_timestreaminfluxdb_provider_group` resource.
    - Provider groups cannot currently be deleted. To avoid swamping users with unnecessary errors, a provider group ID can be used as an argument for an `aws_timestreaminfluxdb_db_instance` resource; users will have to create this provider group themselves, without Terraform.
- S3 log buckets will follow the format defined by AWS SDK Go V2. Instead of providing an S3 bucket ID for logging, users will provide the following:

    ```
    log_delivery_configuration {
        s3_configuration {
            bucket_name = aws_s3_bucket.example.bucket
            enabled = true
        }
    } 
    ```
