### ISSUE TITLE
Application Load Balancer enables configuring HTTP client keepalive duration

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#36402]
> Application Load Balancer (ALB) now provides flexibility that allows you to configure HTTP client keepalive duration for communication between clients and load balancer.

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/03/application-load-balancer-http-keepalive-duration/)
* [API reference](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_ModifyLoadBalancerAttributes.html)

```hcl
resource "aws_lb" "example" {
  client_keep_alive = 7200
}
```

<img width="1008" alt="Screenshot 2024-03-15 at 8 30 56 AM" src="https://github.com/hashicorp/terraform-provider-aws/assets/2404182/b85202ba-5f6f-41f5-b1c2-0f89a36809d2">

**Comment by obounaim** [comment]
@YakDriver thanks for working on this.
I have been working on this for the last few days. Please check if you have an open PR to avoid double work and wasted effort :)

I have created a PR with a ref to this issue.

Thanks in advance.
