### ISSUE TITLE
[Enhancement]: Add `experiment_option` argument to `aws_fis_experiment_template`

### ISSUE THREAD

**Issue by waditya-jpmc** [hashicorp/terraform-provider-aws#36413]
### Terraform Core Version

1.0

### AWS Provider Version

5.0

### Affected Resource(s)

aws_fis_experiment_template

### Expected Behavior

Terraform Plan getting validated

### Actual Behavior

When I use the experiment_option option while creating FIS experiment (as below), 

```terraform
 experiment-options {
    emptyTargetResolutionMode = "skip"
  }
```

I get below error - 

Blocks of type "experiment_options" are not expected here.

I get similar error when using experiment_option instead of experiment_options. This seems to be a bug. 

### Relevant Error/Panic Output Snippet

```shell
Blocks of type "experiment_options" are not expected here.
```

### Terraform Configuration Files

Provider

```terraform
terraform {
  required_version = ">=1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }
  }
}
```

### Steps to Reproduce

Use below template - 

```terraform
resource "aws_fis_experiment_template" "example" {
  description = "example"
  role_arn    = aws_iam_role.example.arn

  stop_condition {
    source = "none"
  }
experiment_options {
    emptyTargetResolutionMode = "skip"
  }

  action {
    name      = "example-action"
    action_id = "aws:ec2:terminate-instances"

    target {
      key   = "Instances"
      value = "example-target"
    }
  }

  target {
    name           = "example-target"
    resource_type  = "aws:ec2:instance"
    selection_mode = "COUNT(1)"

    resource_tag {
      key   = "env"
      value = "example"
    }
  }
}
```

### Important Factoids

AWS docs - https://docs.aws.amazon.com/cli/latest/reference/fis/create-experiment-template.html
Terraform docs - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fis_experiment_template

### References

AWS docs - https://docs.aws.amazon.com/cli/latest/reference/fis/create-experiment-template.html
Terraform docs - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fis_experiment_template

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @waditya-jpmc 👋 Thank you for taking the time to raise this! We consider expanded functionality of existing resources to be an enhancement rather than a bug, so I'm going to update the issue to match that. No further action is needed from you at this time; I just like to give a heads up before adjusting issue titles.
