### ISSUE TITLE
[Bug]: dynamic ebs_block_device on aws_instance resource not detecting changes when variable is updated

### ISSUE THREAD

**Issue by davidkongthao** [hashicorp/terraform-provider-aws#36417]
### Terraform Core Version

1.7.4

### AWS Provider Version

5.40.0

### Affected Resource(s)

aws_instance

### Expected Behavior

The ebs_block_device should have updated given the change in the variable

### Actual Behavior

After running a plan, it didn't detect any changes, even though the variable has changed.

### Terraform Configuration Files

```
  locals {
      instance_specs = [
          {
              private_ip = "10.10.10.10"
              volumes = [
                  {
                      device_name = "xvdd"
                      volume_size = 100
                  }
              ]
          },
          {
              private_ip = "10.10.10.11"
              volumes = [
                  {
                      device_name = "xvdd"
                      volume_size = 100
                  }
              ]
          }
      ]
  }

  resource "aws_instance" "instances" {
      count               = length(local.instance_specs)
      ami                 = "ami-XXXXXXXXXXX"  
      instance_type       = "t2.micro"
      key_name            = "mykey"
      subnet_id           = "subnet-XXXXXXX"
      private_ip          = local.instance_specs[count.index].private_ip

      root_block_device {
          delete_on_termination = true
          encrypted = true
          kms_key_id = "arn:aws:kms:us-east-1:XXXXXX:key/XXXXXX"
          volume_size = 75
          volume_type = "gp3"
      }

      dynamic "ebs_block_device" {
          for_each = local.instance_specs[count.index].volumes
          content {
              device_name = ebs_block_device.value.device_name
              volume_size = ebs_block_device.value.volume_size
              volume_type = "gp3"
              delete_on_termination = true
              encrypted = true
              kms_key_id = "arn:aws:kms:us-east-1:XXXXXX:key/XXXXXX"
          }
      }

      vpc_security_group_ids = ["sg-XXXXXX"]
  }
```

### Steps to Reproduce

Run an apply to provision a server and then change the volume_size, and then run an apply again.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @davidkongthao 👋 Thank you for taking the time to raise this! Diff detection is generally more on the Terraform Core side of things, but we can take a look over debug logs if you're able to supply them (redacted as necessary) to try to verify that. If we determine it's a Terraform Core issue, we'll need to have you open an issue in [that repository](https://github.com/hashicorp/terraform).

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
