### ISSUE TITLE
[Bug]: aws_eks_access_entry fails for a service linked role

### ISSUE THREAD

**Issue by jalawala** [hashicorp/terraform-provider-aws#36447]
### Terraform Core Version

1.7.4

### AWS Provider Version

5.41.0

### Affected Resource(s)

Below code fails with an error operation error EKS: CreateAccessEntry, https response error StatusCode: 400, RequestID: 2df85c51-3b73-4ff0-a807-e3bd72244e7b, InvalidParameterException: The caller is not allowed to modify access entries with a principalArn value of a Service Linked Role

```
resource "aws_eks_access_entry" "AWSServiceRoleForAmazonEMRContainers" {
  cluster_name      = module.emr_on_eks.cluster_name
  principal_arn     = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/aws-service-role/emr-containers.amazonaws.com/AWSServiceRoleForAmazonEMRContainers"
  kubernetes_groups = ["${var.emr_containers_rbac_group}"]
  type              = "STANDARD"
}
```

### Expected Behavior

expected to create access entry

### Actual Behavior

operation error EKS: CreateAccessEntry, https response error StatusCode: 400, RequestID: 2df85c51-3b73-4ff0-a807-e3bd72244e7b, InvalidParameterException: The caller is not allowed to modify access entries with a principalArn value of a Service Linked Role

### Terraform Configuration Files

```
resource "aws_eks_access_entry" "AWSServiceRoleForAmazonEMRContainers" {
  cluster_name      = module.emr_on_eks.cluster_name
  principal_arn     = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/aws-service-role/emr-containers.amazonaws.com/AWSServiceRoleForAmazonEMRContainers"
  kubernetes_groups = ["${var.emr_containers_rbac_group}"]
  type              = "STANDARD"
}

```

### Steps to Reproduce

add below code in TF

```
resource "aws_eks_access_entry" "AWSServiceRoleForAmazonEMRContainers" {
  cluster_name      = module.emr_on_eks.cluster_name
  principal_arn     = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/aws-service-role/emr-containers.amazonaws.com/AWSServiceRoleForAmazonEMRContainers"
  kubernetes_groups = ["${var.emr_containers_rbac_group}"]
  type              = "STANDARD"
}

```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @jalawala 👋 Thank you for taking the time to raise this! It looks like this error is coming from the AWS API itself, so I suspect this may be something outside of the provider. Are you able to test using the AWS CLI or API directly to see if you're able to make this sort of modification with one of those tools?

**Comment by jalawala** [comment]
@justinretzolk  thanks for the quick response. Yes I got to know this is in the roadmap for EMR on EKS team to support this.

**Comment by justinretzolk** [comment]
Thanks for the follow up @jalawala! Since this is something that's currently not supported by AWS, we'll close this issue for now. If that support changes in the future and it's not something that's automatically enabled by the SDK (as often happens), we'd be happy to take another look.
