### ISSUE TITLE
data source to retrieve a list of all of custom cloudwatch metrics

### ISSUE THREAD

**Issue by tchia04** [hashicorp/terraform-provider-aws#3644]
It would be nice to have a data source for custom cloudwatch metrics. I manually build my own bash shell script to get the list of custom metric by namespace and then use that list to generate the cloudwatch alarms.

**Comment by viesti** [comment]
Same need here, I was looking for rewriting old Ansible script that looks up disk usage metric for all nodes in Redshift cluster and creates alarms for the metrics. A data source that would allow querying Cloudwatch metrics would fit here nicely.

**Comment by viesti** [comment]
I was able to overcome this via [external data source](https://www.terraform.io/docs/providers/external/data_source.html), by querying metrics via aws cli and outputting a `|` delimited string, to overcome the lack of support of arrays in the JSON returned by external data source:

```
data "external" "redshift-nodes-with-disk-usage-metric" {
  program = [
    "aws",
    "cloudwatch",
    "list-metrics",
    "--namespace", "AWS/Redshift",
    "--metric-name", "PercentageDiskSpaceUsed",
    "--dimensions", "Name=ClusterIdentifier,Value=${aws_redshift_cluster.my-cluster.id}",
    "--query", "Metrics[].Dimensions[?Name=='NodeID'].Value[] | {Nodes: join('|', @)}",
    "--out", "json"]
}
```

The JMESPath looks a bit hairy in this case, but anyway, a external data source might be workable solution.

**Comment by wardviaene** [comment]
I spent some time working on a datasource for aws cloudwatch metrics, but it seems to be difficult to write an acceptance test for it. There are no cloudwatch metrics in an AWS account, unless you do a cloudwatch PutMetricData, which is not implemented in any terraform datasource/resource. The WIP code can be found here: https://github.com/terraform-providers/terraform-provider-aws/compare/master...wardviaene:f-aws_cloudwatch_metrics

**Comment by wardviaene** [comment]
Submitted a PR: https://github.com/terraform-providers/terraform-provider-aws/pull/14253
