### ISSUE TITLE
[Bug]: Unable to use single DNS server when using Self-Managed Active Directory for RDS MSSQL

### ISSUE THREAD

**Issue by kostasns** [hashicorp/terraform-provider-aws#36500]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.41.0

### Affected Resource(s)

* aws_db_instance

### Expected Behavior

```shell
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

### Actual Behavior

```shell
Error: Not enough list items
│
│   with module.rds.aws_db_instance.this,
│   on ..\modules\rds\main.tf line 111, in resource "aws_db_instance" "this":
│  436:   domain_dns_ips         = ["10.10.10.10","10.10.10.10"]
│
│ Attribute domain_dns_ips requires 2 item minimum, but config has only 1 declared.
```

### Terraform Configuration Files

```terraform
  domain_fqdn                  = var.domain_fqdn
  domain_ou                     = var.domain_ou
  domain_auth_secret_arn = var.domain_auth_secret_arn
  domain_dns_ips              = ["10.10.10.10","10.10.10.10"]
```

### Steps to Reproduce

- Create RDS MSSQL with Self-Managed Active directory providing single DNS IP for both primary and secondary field.

### References

https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBInstance.html#API_ModifyDBInstance_RequestParameters

DomainDnsIps.member.N
The IPv4 DNS IP addresses of your primary and secondary Active Directory domain controllers.

Constraints:
Two IP addresses must be provided. **If there isn't a secondary domain controller, use the IP address of the primary domain controller for both entries in the list.**

### Would you like to implement a fix?

No

**Comment by halil9** [comment]
Also, I have same issue. When the issue will fix? Could you help for that?

**Comment by kostasns** [comment]
Hello @justinretzolk,
Is there a possibility for someone to look into the PR I've put together ?
