### ISSUE TITLE
Amazon DynamoDB resource-based policies

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#36502]
> Amazon DynamoDB now supports resource-based policies to help you simplify access control for your DynamoDB resources.

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/03/amazon-dynamodb-resource-based-policies/)
* [Blog post](https://aws.amazon.com/blogs/database/simplify-cross-account-access-control-with-amazon-dynamodb-using-resource-based-policies/)

Requires [AWS SDK for Go v1.51.4](https://github.com/aws/aws-sdk-go/releases/tag/v1.51.4): https://github.com/hashicorp/terraform-provider-aws/pull/36497.

### Potential Terraform Configuration

```terraform
resource "aws_dynamodb_resource_policy" "example" {
  resource_arn = aws_dynamodb_table.example.arn

  policy = <<EOF
...
EOF
}
```

**Comment by nicolaschambrier** [comment]
Note we would need an additional `stream_policy` field as the table policies and stream policies are distinct
