### ISSUE TITLE
[Bug]: db_instance not accepting the value provided for option group explicitly.

### ISSUE THREAD

**Issue by ankurwkd** [hashicorp/terraform-provider-aws#36525]
### Terraform Core Version

1.6.6

### AWS Provider Version

5.36

### Affected Resource(s)

AWS_RDS, tried creating the option group for mysql and custom option group doesn't created. Later tried to give custom group explicitly to create mysql rds insrtance, even then it used default option group instead of custom option group.

### Expected Behavior

aws_db_option_group should create custom option group for mysql.
aws_db_instance should use the custom option group explicitly given

### Actual Behavior

Doesn't create custom option group, even doesn't use custom option group in rds creation for mysql

### Relevant Error/Panic Output Snippet

```shell
No error, just no custom option group created and even used in rds creation.

Plan output:
 network_type                          = (known after apply)    
 option_group_name                     = (known after apply)    
 parameter_group_name                  = "bt-ccoe-db-mysql8-pg" 

Custom groups given like below:
## DB Config groups
option_group_name="bt-ccoe-db-mysql8-og1"
parameter_group_name = "bt-ccoe-db-mysql8-pg"
```

## Engine Details
engine = "mysql"
engine_version = "8.0"
major_engine_version = "8.0"
family = "mysql8.0"
instance_class = "db.t3.micro"
identifier = "mysql-db1"
region = "us-west-2"

#Mandatory app Details
app = "tri"
env = "prod"
increment_code=01

#DB & Credentiaal Details
db_name = "mydb"
username = "adminmysql"

## DB Config groups
option_group_name="bt-ccoe-db-mysql8-og1"
parameter_group_name = "bt-ccoe-db-mysql8-pg"

### Storage
storage_type = "gp3"				# Enforce
allocated_storage = 50				# Enforece 50G or more

#### DB subnet group
 db_subnet_group_name = "bt-ccoe-db-subnet-or"    

##### DR Options
# To have multi AZ configured.
multi_az = "false"			# true=Required or false=not required.

##### Maintenance Paramteres
auto_minor_version_upgrade = "true"			# # Security mandate to mark true

#### Mandatory Security Standards
kms_key_id = "arn:aws:kms:us-west-2:990999877410:key/e63ec963-818c-4554-8fba-bdf8a59e54e8"
iam_database_authentication_enabled = "true"		# Enforced
storage_encrypted = true							# Enforced
#vpc_security_group_ids = ["a","b"]					# Provide custom security group or else default will be used.
port     = 3307										# Enforced for non-default port (MySQL-3306)

deletion_protection = false							# Mark true in variables.tf
manage_master_user_password_rotation = "true"		# Enforced
master_user_password_rotation_automatically_after_days = 60		#Enforced

#Backup:
backup_retention_period = 1

## Monitoring
create_cloudwatch_log_group     = true						# Enforced
enabled_cloudwatch_logs_exports = ["audit","error"]			

##Note - "Use security best practices to harden your database" from security document for MySQL RDS is not valid.
# https://confluence.workday.com/display/InfoSec/AWS+Relational+Database+Services+%28RDS%29+Security+Standard

### Steps to Reproduce

(1) Used code from repo - https://github.com/terraform-aws-modules/terraform-aws-rds
(2) Trying creating RDS MySQL 8 using custom option group and parameter group.
(3) Parameter group is accepted, but not custom option group.

### Debug Output

"network_type": "IPV4",
            "option_group_name": "default:mysql-8-0",
            "parameter_group_name": "bt-ccoe-db-mysql8-pg",

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @ankurwkd 👋 Thank you for taking the time to raise this! It looks like this is more related to the module that you're using than a bug with the provider itself, so you'll want to open an issue in the module's repository. With that in mind, I'm going to close this issue.
