### ISSUE TITLE
[New Data Source]: aws_glue_registry as data source

### ISSUE THREAD

**Issue by sralchemab** [hashicorp/terraform-provider-aws#36558]
### Description

Because the AWS Glue Registry is a collection, it would be useful to be able to retrieve a requested Glue Registry in order to then create a Glue Schema in it. In the current plugin version (v5.41.0), Glue Schemas can only be created on new registries.

### Requested Resource(s) and/or Data Source(s)

* aws_glue_registry

### Potential Terraform Configuration

```terraform
data "aws_glue_registry" "example" {
  name = "my_registry_name"
}
```

### Would you like to implement a fix?

None

**Comment by Viriathus1** [comment]
Hey @sralchemab I've created the data source which I require as well with this open pr #37953.
Can you 👍 so it can be prioritised quicker?
