### ISSUE TITLE
[Enhancement]: Support for DynamoDB resource-based policies 

### ISSUE THREAD

**Issue by gmaghera** [hashicorp/terraform-provider-aws#36569]
### Description

AWS released resource-based policies for DynamoDB. https://aws.amazon.com/about-aws/whats-new/2024/03/amazon-dynamodb-resource-based-policies/

### Affected Resource(s) and/or Data Source(s)

* dynamodb_table

### Potential Terraform Configuration

```terraform
resource "aws_dynamodb_table" "basic-dynamodb-table" {
  name           = "AnExample"
  #... 
  
  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::123456789012:user/John"
      },
      "Action": [
        "dynamodb:RestoreTableToPointInTime",
        "dynamodb:GetItem",
        "dynamodb:PutItem"
      ],
      "Resource": "arn:aws:dynamodb:us-east-1:123456789012:table/MusicCollection"
    }
  ]
}
 EOF

  #...
}
```

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@gmaghera Thanks for raising this issue.
It has already been noticed in #36502. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
