### ISSUE TITLE
[Bug]: SecretsManager secret version does not gracefully remove deleted versions from state

### ISSUE THREAD

**Issue by jar-b** [hashicorp/terraform-provider-aws#36607]
### Terraform Core Version

1.8.0-rc1

### AWS Provider Version

5.42.0

### Affected Resource(s)

- `aws_secretsmanager_secret_version`

### Expected Behavior

When a secret version is deleted by the automated AWS cleanup process, the provider should remove the resource from state

### Actual Behavior

The provider throws an error:

```
│ Error: error reading Secrets Manager Secret Version (arn:aws:secretsmanager:us-east-1:<redacted>:secret:example2-o0Q1tI|<redacted>): InvalidRequestException: You can't perform this operation on secret version <redacted> because it was deleted.
```

### Terraform Configuration Files

```hcl
resource "aws_secretsmanager_secret_version" "example" {
  secret_id     = aws_secretsmanager_secret.example.id
  secret_string = "example-string-to-protect"
}
```

### Steps to Reproduce

1. Create a new secret version.
2. Update the secret until more than 100 new versions have been created (out of band). This should trigger AWS's automated cleanup process some time after 24 hours.
  > Secrets Manager removes unlabeled versions when there are more than 100, but it does not remove versions created less than 24 hours ago. 
3. Observe failure on `terraform plan`.

### Important Factoids

The AWS provider includes logic like the following to catch deleted _secrets_ and remove them from state gracefully. However, there is no handling for deleted _secret versions_.

https://github.com/hashicorp/terraform-provider-aws/blob/3532b9f08232c1d277bcf90e98f421b28af3b707/internal/service/secretsmanager/secret_version.go#L328

Updating this check to a shorter portion of the error message should allow for detection of both secrets and secret versions deleted out of band.

### References

- https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_limits.html

### Would you like to implement a fix?

None

**Comment by xnick123** [comment]
I can confirm this error, I struggled to understand the pattern leading to this. It happens across multiple environments on a secret where I perform secret rotation every 4 hours. It did not happen on other secrets which I don't rotate. Hence I believe that the explanation makes sense.
