### ISSUE TITLE
[Enhancement]: r/aws_elasticache_serverless_cache: Support minimum cache usage limits

### ISSUE THREAD

**Issue by jar-b** [hashicorp/terraform-provider-aws#36624]
### Description

AWS now supports setting minimum usage limits for Elasticache serverless caches. Specifically, the `cache_usage_limits.data_storage` and `cache_usage_limits.ecpu_per_second` blocks can now include an optional `minimum` argument.

### Affected Resource(s) and/or Data Source(s)

- `aws_elasticache_serverless_cache`

### Potential Terraform Configuration

```terraform
resource "aws_elasticache_serverless_cache" "example" {
  # other configuration
  
  cache_usage_limits {
    data_storage {
      minimum = 1000
    }
    ecpu_per_second {
      minimum = 1000
    }
  }
}
```

### References

- Depends on #36620
- https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_DataStorage.html
- https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_ECPUPerSecond.html

### Would you like to implement a fix?

None

**Comment by speedhs** [comment]
Hey! I would like to read about this and contribute a solution. Can you assign it to me
