### ISSUE TITLE
[Bug]: module outputs not working

### ISSUE THREAD

**Issue by tirelibirefe** [hashicorp/terraform-provider-aws#36645]
### Terraform Core Version

1.7.5

### AWS Provider Version

5.42.0

### Affected Resource(s)

The [documentation](https://registry.terraform.io/modules/terraform-aws-modules/iam/aws/latest/submodules/iam-user?tab=outputs) lists "iam_user module" outputs but none of them works.

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.42.0"
    }
  }
}

provider "aws" {
  region = "eu-central-1"
}

module "iam_user" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-user"
  version = "5.37.1"

  for_each = toset(["ali", "veli", "osman"])
  name     = each.key

  force_destroy           = true
  password_reset_required = false
}


output "iam_user_arn" {
  description = "The ARN assigned by AWS for this user"
  value       = module.iam_user.iam_user_arn
}
```

```
│ Error: Unsupported attribute
│ 
│   on main.tf line 27, in output "iam_user_arn":
│   27:   value       = module.iam_user.iam_user_arn
│     ├────────────────
│     │ module.iam_user is object with 3 attributes
│ 
│ This object does not have an attribute named "iam_user_arn".
```

### Expected Behavior

outputs are listed.

### Actual Behavior

outputs not listed if module is used; when a "resource" is used, it works.

### Relevant Error/Panic Output Snippet

```shell
│ Error: Unsupported attribute
│ 
│   on main.tf line 27, in output "iam_user_arn":
│   27:   value       = module.iam_user.iam_user_arn
│     ├────────────────
│     │ module.iam_user is object with 3 attributes
│ 
│ This object does not have an attribute named "iam_user_arn".
```
```


### Terraform Configuration Files

```
│ Error: Unsupported attribute
│ 
│   on main.tf line 27, in output "iam_user_arn":
│   27:   value       = module.iam_user.iam_user_arn
│     ├────────────────
│     │ module.iam_user is object with 3 attributes
│ 
│ This object does not have an attribute named "iam_user_arn".
```

### Steps to Reproduce

just run the following super simple sample:

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.42.0"
    }
  }
}

provider "aws" {
  region = "eu-central-1"
}

module "iam_user" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-user"
  version = "5.37.1"

  for_each = toset(["ali", "veli", "osman"])
  name     = each.key

  force_destroy           = true
  password_reset_required = false
}

output "iam_user_arn" {
  description = "The ARN assigned by AWS for this user"
  value       = module.iam_user.iam_user_arn
}
```

### Debug Output

```
│ Error: Unsupported attribute
│ 
│   on main.tf line 27, in output "iam_user_arn":
│   27:   value       = module.iam_user.iam_user_arn
│     ├────────────────
│     │ module.iam_user is object with 3 attributes
│ 
│ This object does not have an attribute named "iam_user_arn".
```

### Panic Output

```
│ Error: Unsupported attribute
│ 
│   on main.tf line 27, in output "iam_user_arn":
│   27:   value       = module.iam_user.iam_user_arn
│     ├────────────────
│     │ module.iam_user is object with 3 attributes
│ 
│ This object does not have an attribute named "iam_user_arn".
```

### Important Factoids

```
│ Error: Unsupported attribute
│ 
│   on main.tf line 27, in output "iam_user_arn":
│   27:   value       = module.iam_user.iam_user_arn
│     ├────────────────
│     │ module.iam_user is object with 3 attributes
│ 
│ This object does not have an attribute named "iam_user_arn".
```

### References

https://registry.terraform.io/modules/terraform-aws-modules/iam/aws/latest/submodules/iam-user?tab=outputs

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
@tirelibirefe This is an issue related to the `terraform-aws-iam` module so you should create it in [this repository](https://github.com/terraform-aws-modules/terraform-aws-iam) instead.

But the issue is likely a usage error based on your description. You are using the `for_each` meta-argument so you technically have a map of three "attributes" - one for each of the users `ali`, `veli` and `usman`. The [`for_each` documentation](https://developer.hashicorp.com/terraform/language/meta-arguments/for_each) should give you more details on how to refer to the named instances (or use a wildcard to get multiple instances/attributes). Hope this helps.

**Comment by tirelibirefe** [comment]
Hello @acwwat Thank you for your advice & feedback. 
I am going to follow your advice.
The issue can be closed.
