### ISSUE TITLE
[Enhancement]: Add `lambda` and `mediapackagev2` options for `origin_access_control_origin_type` to `aws_cloudfront_origin_access_control`

### ISSUE THREAD

**Issue by micchickenburger** [hashicorp/terraform-provider-aws#36660]
### Description

The `aws_cloudfront_origin_access_control` resource has argument `origin_access_control_origin_type` with valid options `s3` and `mediastore`.  However, `lambda` and `mediapackagev2` should also be allowed.

```
 Error: expected origin_access_control_origin_type to be one of ["s3" "mediastore"], got lambda
│ 
│   with module.cloudfront.aws_cloudfront_origin_access_control.oac,
│   on modules/cloudfront/main.tf line 30, in resource "aws_cloudfront_origin_access_control" "oac":
│   30:   origin_access_control_origin_type = "lambda"
```

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-originaccesscontrol-originaccesscontrolconfig.html

### Affected Resource(s) and/or Data Source(s)

* aws_cloudfront_origin_access_control

### Potential Terraform Configuration

```terraform
resource "aws_cloudfront_origin_access_control" "oac" {
  name                              = "oac-lambda"
  description                       = "OAC Policy for lambda function"
  origin_access_control_origin_type = "lambda"
  signing_behavior                  = "always"
  signing_protocol                  = "sigv4"
}
```

### References

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-originaccesscontrol-originaccesscontrolconfig.html

* [Lambda announcement](https://aws.amazon.com/about-aws/whats-new/2024/04/amazon-cloudfront-oac-lambda-function-url-origins/)
* [Elemental MediaPackage announcement](https://aws.amazon.com/about-aws/whats-new/2024/04/amazon-cloudfront-oac-aws-elemental-mediapackage-origin/)

### Would you like to implement a fix?

No

**Comment by micchickenburger** [comment]
Interestingly, other official documentation is also missing the `lambda` and `mediapackagev2` values:
* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudfront/create-origin-access-control.html
* https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateOriginAccessControl.html

Furthermore, the AWS Console does not seem to allow the creation of an OAC for custom or lambda function domains either.

But the AWS CLI is happy to create one:

```shell
$ aws cloudfront create-origin-access-control --origin-access-control-config "Name=oac,SigningProtocol=sigv4,SigningBehavior=always,OriginAccessControlOriginType=lambda"
```

```json
{
    "Location": "https://cloudfront.amazonaws.com/2020-05-31/origin-access-control/XXXXXXXXXXXXX",
    "ETag": "XXXXXXXXXXXXX",
    "OriginAccessControl": {
        "Id": "XXXXXXXXXXXXX",
        "OriginAccessControlConfig": {
            "Name": "oac",
            "SigningProtocol": "sigv4",
            "SigningBehavior": "always",
            "OriginAccessControlOriginType": "lambda"
        }
    }
}
```

This change is reflected in the AWS Console too: 
<img width="1056" alt="image" src="https://github.com/hashicorp/terraform-provider-aws/assets/4521230/644ac870-60fa-4e80-b8ab-df79315fdced">

Manually updating the CloudFront Distribution to associate the OAC with the origin also works successfully, per the documentation here:  https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html

**Comment by jtyrus** [comment]
Did a quick check and looks like v1 cloudfront doesn't have those listed... but the AWS module isn't doing any validation on the string during creation. Ran a test without terraform validation and was able to get it to work. I can make this update.

```go
// Cloudfront V1 api.go
type OriginAccessControlConfig struct {
   OriginAccessControlOriginType *string `type:"string" required:"true" enum:"OriginAccessControlOriginTypes"`
...
}

...
const (
	// OriginAccessControlOriginTypesS3 is a OriginAccessControlOriginTypes enum value
	OriginAccessControlOriginTypesS3 = "s3"

	// OriginAccessControlOriginTypesMediastore is a OriginAccessControlOriginTypes enum value
	OriginAccessControlOriginTypesMediastore = "mediastore"
)

// OriginAccessControlOriginTypes_Values returns all elements of the OriginAccessControlOriginTypes enum
func OriginAccessControlOriginTypes_Values() []string {
	return []string{
		OriginAccessControlOriginTypesS3,
		OriginAccessControlOriginTypesMediastore,
	}
}
```
