### ISSUE TITLE
[Bug]: aws_mskconnect_worker_configuration resource does not implement deletion

### ISSUE THREAD

**Issue by twbecker** [hashicorp/terraform-provider-aws#36672]
### Terraform Core Version

1.7.5

### AWS Provider Version

5.43.0

### Affected Resource(s)

* aws_mskconnect_worker_configuration

### Expected Behavior

Resources of type `aws_mskconnect_worker_configuration` cannot be effectively managed by Terraform, because the provider does not implement updates and implements deletes as a no-op. MSK Connect recently [added support](https://aws.amazon.com/blogs/big-data/introducing-enhanced-functionality-for-worker-configuration-management-in-amazon-msk-connect/) for the deletion of worker configurations, so it should be possible to fix this resource now. 

### Actual Behavior

If you create a `aws_mskconnect_worker_configuration` resource, any changes to its configuration will fail. If you destroy your configuration, subsequently re-creating it will fail because the resource deletion is a no-op: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/kafkaconnect/worker_configuration.go#L26

### Terraform Configuration Files

```terraform
provider "aws" {
  region = "us-east-1"
}

data "aws_region" "current" { }

resource "aws_mskconnect_worker_configuration" "testing" {
  name                    = "testing"
  properties_file_content = <<-EOF
    key.converter=org.apache.kafka.connect.storage.StringConverter
    value.converter=org.apache.kafka.connect.storage.StringConverter
  EOF
}
```

### Steps to Reproduce

1. Apply the above configuration.
2. Change a value in `properties_file_content`
3. Try to apply again - the change is planned as a replacement (correct), but the deletion isn't performed (no-op) and therefore the subsequent re-creation fails.
4. Destroy the configuration. This "succeeds" but again, the resource is not deleted.

### Important Factoids

While I appreciate the provider adding support for features that are half-baked by AWS, this resource is basically unusable in its current form. It would be nice if these limitations were at least called out in the documentation of the resource.

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/36375.
