### ISSUE TITLE
[Enhancement]: Support tagging of MSK Resources

### ISSUE THREAD

**Issue by twbecker** [hashicorp/terraform-provider-aws#36674]
### Description

Several MSK resource types now [support tagging](https://aws.amazon.com/blogs/big-data/introducing-enhanced-functionality-for-worker-configuration-management-in-amazon-msk-connect/). It would be nice if the provider would support this as well. 

### Affected Resource(s) and/or Data Source(s)

* aws_mskconnect_connector
* aws_mskconnect_custom_plugin
* aws_mskconnect_worker_configuration

### Potential Terraform Configuration

```terraform
tags = {
    foo = "bar"
}
```

### References

https://aws.amazon.com/blogs/big-data/introducing-enhanced-functionality-for-worker-configuration-management-in-amazon-msk-connect/

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@twbecker Thanks for raising this issue.
It has already been noticed in #36375. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
