### ISSUE TITLE
[Enhancement]: rename aws_cloudfrontkeyvaluestore_key

### ISSUE THREAD

**Issue by camilbinas** [hashicorp/terraform-provider-aws#36684]
### Description

The [aws_cloudfrontkeyvaluestore_key](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfrontkeyvaluestore_key) resource currently doesn't align with the naming convention of other Cloudfront resources. It should be named "aws_cloudfront_key_value_store_key". Also the resource is located in a separate navigation group in the documentation:  "CloudFront KeyValueStore" instead of "CloudFront" which makes it harder to find the example.

### Affected Resource(s) and/or Data Source(s)

aws_cloudfrontkeyvaluestore_key

### Potential Terraform Configuration

```terraform
resource "aws_cloudfront_key_value_store" "example" {
  name    = "ExampleKeyValueStore"
  comment = "This is an example key value store"
}

resource "aws_cloudfront_key_value_store_key" "example" {
  key_value_store_arn = aws_cloudfront_key_value_store.example.arn
  key                 = "Test Key"
  value               = "Test Value"
}
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @camilbinas 👋 Thank you for taking the time to raise this! While we acknowledge that one might initially expect this resource to be named `aws_cloudfront_key_value_store_key`, naming it `aws_cloudfrontkeyvaluestore_key` more closely matches the SDK and underlying API:

- `aws_cloudfront_*` resources use the [`cloudfront` package](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudfront) ([related API documentation](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_Operations_Amazon_CloudFront.html))
- `aws_cloudfrontkeyvaluestore_*` use the [`cloudfrontkeyvaluestore` package](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudfrontkeyvaluestore) ([related API documentation](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_Operations_Amazon_CloudFront_KeyValueStore.html))

Following the API/SDK as closely as possible is one of the [provider design principles](https://developer.hashicorp.com/terraform/plugin/best-practices/hashicorp-provider-design-principles#resource-and-attribute-schema-should-closely-match-the-underlying-api), and something we try to do where possible (for another example, see [`aws_servicecatalogappregistry_application`](https://github.com/hashicorp/terraform-provider-aws/pull/36277)). With that in mind, I'm going to close this issue.
