### ISSUE TITLE
[Enhancement]: Add ability to specify phone number and address fields

### ISSUE THREAD

**Issue by jogueber** [hashicorp/terraform-provider-aws#36683]
### Description

Adding the ability to specify several  `PhoneNumberFields` in the `aws_wafv2_web_acl` in order to also configure them for the Account takeover prevention ruleset. 
For reference [see here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl)
### Affected Resource(s) and/or Data Source(s)

aws_wafv2_web_acl

### Potential Terraform Configuration

```terraform
#more ommitted for brevity 
  aws_managed_rules_acfp_rule_set {
            creation_path          = "/signin"
            registration_page_path = "/register"

            request_inspection {
              email_field {
                identifier = "/email"
              }

              password_field {
                identifier = "/password"
              }
              phone_number_fields {
                identifiers = ["mobile","landline"]
              }

             
              payload_type = "JSON"

              username_field {
                identifier = "/username"
              }
            }
```

### Would you like to implement a fix?

Yes

**Comment by acwwat** [comment]
It looks like [AddressFields](https://docs.aws.amazon.com/waf/latest/APIReference/API_RequestInspectionACFP.html#WAF-Type-RequestInspectionACFP-AddressFields) are also not supported, so it would be nice to have it added as part of the PR for this issue :) On quick glance the implementation would be similar to that of `PhoneNumberFields`.

**Comment by jogueber** [comment]
@acwwat  I added that as well :) 
thanks for pointing it out :)
