### ISSUE TITLE
Implementation of the new aws_servicecatalogappregistry_application is not working as expected 

### ISSUE THREAD

**Issue by kevindesao** [hashicorp/terraform-provider-aws#36697]
Hello, 
I was really excited to try this out but it turns out I'm not able to make it work smoothly.

The creation of the resource worked fine but the implementation of the ARN as a tag fails to link the resource to the app.

The doc is mentioning the following:
```
resource "aws_servicecatalogappregistry_application" "example" {
  name = "example-app"
}

resource "aws_s3_bucket" "bucket" {
  bucket = "example-bucket"

  tags = {
    awsApplication = aws_servicecatalogappregistry_application.example.arn
  }
}
```

But by looking into the created myApp in the console the tags is not simply the ARN of the myApplication resources.

  - ARN myApplication : `arn:aws:servicecatalog:<region>:<account-id>:/applications/<ramdom_ARN_ID>`
  - Application tag value: `arn:aws:resource-groups:<region>:<account-id>:group/<myApplication_name>/<ramdom_ARN_ID>`

Tag Value tried unsuccessfully:
  - simply the myApplication id : `<ramdom_ARN_ID>`
  - The ARN `arn:aws:servicecatalog:<region>:<account-id>:/applications/<ramdom_ARN_ID>`

So to resume, I think a new attribute is required (and the doc updated): 
  - `application_tag_value` =  `Application tag value` (similare to [awscc_servicecatalogappregistry_application](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/servicecatalogappregistry_application#:~:text=application_tag_value)).

**SOLUTION:** In the meantime the ARN can be reconstructed like this: (Tested)
```
  common_tags = {
    awsApplication = "arn:aws:resource-groups:${data.aws_region.myApplication.name}:${data.aws_caller_identity.myApplication.id}:group/${aws_servicecatalogappregistry_application.this.name}/${aws_servicecatalogappregistry_application.this.id}"
  }
```

_Originally posted by @kevindesao in https://github.com/hashicorp/terraform-provider-aws/issues/36277#issuecomment-2033148058_

**Comment by jar-b** [comment]
Closed by #36647
