### ISSUE TITLE
[Bug]: Terraform Apply Hangs Indefinitely When Creating or Fetching aws_cur_report_definition

### ISSUE THREAD

**Issue by kamliolfa1** [hashicorp/terraform-provider-aws#36701]
### Terraform Core Version

1.7.3

### AWS Provider Version

5.42.0

### Affected Resource(s)

data `"aws_cur_report_definition"`
resource `"aws_cur_report_definition"`

### Expected Behavior

Terraform should successfully create or fetch the aws_cur_report_definition within a reasonable amount of time without hanging.

### Actual Behavior

When attempting to create a new aws_cur_report_definition or fetch data for an existing one, terraform apply hangs indefinitely with no errors reported. The process seems to be stuck at reading the aws_cur_report_definition data, with logs indicating continuous attempts to read the data (e.g., "`Still reading... [9m11s elapsed]`") but never completing.

Relevant Error/Panic Output Snippet
Logs show repeated messages of:
`data.aws_cur_report_definition.report_definition: Still reading... [time elapsed]
`with times ranging from 10s up to over 9 minutes, but no errors are reported.

### Terraform Configuration Files

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.42.0"
    }
  }
}
provider "aws" {
  profile = "xxxxxxxxx"
 region =  "eu-west-1"
}

resource "aws_cur_report_definition" "cost_and_usage_report" {
  report_name                = "my_cost_and_usage_report_test"
  time_unit                  = "HOURLY"
  format                     = "Parquet"
  compression                = "Parquet"
  additional_schema_elements = ["RESOURCES"]
  s3_bucket                  = "cur-grafana-test"
  s3_region                  = "us-east-1" 
  additional_artifacts       = ["ATHENA"]
  s3_prefix                  = "/test"
  report_versioning          = "OVERWRITE_REPORT"
}
```

### Steps to Reproduce

Define an `aws_cur_report_definition `resource or data source in a Terraform configuration.
Run `terraform apply` to apply the configuration.
Observe that the process hangs indefinitely when attempting to create or fetch the `aws_cur_report_definition`.

### Important Factoids

This issue has been consistently reproducible in the eu-west-1 region with the specified provider and Terraform core versions.
The AWS account and Terraform configurations being used have the necessary permissions for creating and accessing CUR report definitions.
No network connectivity issues have been identified that could explain the hanging behavior.

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
I am unable to reproduce the problem with almost the same configuration. The CUR is created within seconds in the `eu-west-1` region for me. I also see that your configuration has `us-east-1` as the S3 bucket region, so for sake of testing I've also tested with the S3 buckets in both regions. Both tests were successful.

I was suspecting that it could be bucket policy issues, but it seems that validation would fail on create if that's the case. The API doesn't seem to return an error message, so maybe the CUR API doesn't handle errors very well.

I can only suggest that you try to enable debug or trace logging and see if there is anything interesting. Furthermore, sometimes if you cancel the process before the timeout, the underlying message might be displayed.
