### ISSUE TITLE
Enhancement for aws_apigatewayv2_route: Enable two-way communication

### ISSUE THREAD

**Issue by marc-woerner-idexx** [hashicorp/terraform-provider-aws#36711]
### Description

There is currently no attribute provided in Terraform to enable two-way communication on a route for an AWS WebSocket Gateway. For example, if I was to implement a ping-pong behavior with a mock integration that is responding a "pong" to a "ping", this would require that the mock integration has two-way communication enabled. However, the AWS provider for apigatewayv2 does not offer a way to do this. Would be great if a route or route response would provide such a possibility, so the route setting does not have to be enabled manually on the AWS console.

### Affected Resource(s) and/or Data Source(s)

aws_apigatewayv2_route
using AWS provider version 5.43.0

### Would you like to implement a fix?

None

**Comment by jtyrus** [comment]
I can work on this

**Comment by jtyrus** [comment]
So the AWS provider doesn't do it on the route, it's applied through a route response. [AWS Docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-route-response.html). I was able to create a route with a route response and can see 2 way communication enabled in the console.

```terraform
provider "aws" {
  region = "us-west-1"
}

resource "aws_apigatewayv2_api" "example" {
  name                       = "example-websocket-api"
  protocol_type              = "WEBSOCKET"
  route_selection_expression = "$request.body.action"
}

resource "aws_apigatewayv2_route" "example" {
  api_id    = aws_apigatewayv2_api.example.id
  route_key = "$default"
}

resource "aws_apigatewayv2_route_response" "example" {
  api_id             = aws_apigatewayv2_api.example.id
  route_id           = aws_apigatewayv2_route.example.id
  route_response_key = "$default"
}
```

**Comment by marc-woerner-idexx** [comment]
Thanks a lot @jtyrus for spending time on my issue. It worked great and as described in your snippet. The route response key must be set to "$default", also when using a different route key (for example "ping"). Since I got stuck when I was searching for "two-way communication" in the Terraform docs, leaving a brief note in https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_route_response
won't be a bad idea. Thanks again for this quick and easy solution.

**Comment by jtyrus** [comment]
@marc-woerner-idexx agreed that it would be helpful if settings affected by specific arguments were mentioned in the docs.
