### ISSUE TITLE
[Enhancement]: FLINK-1_18 support in `aws_kinesisanalyticsv2_application`

### ISSUE THREAD

**Issue by jalilalchy** [hashicorp/terraform-provider-aws#36718]
### Terraform Core Version

1.7.5

### AWS Provider Version

5.43.0

### Affected Resource(s)

The CDKTF Provider for AWS Terraform does not support AWS Kinesis Analytics V2 Applications with FLINK-1_18 resulting in the following error: 

```
Error: expected runtime_environment to be one of ["SQL-1_0" "FLINK-1_6" "FLINK-1_8" "ZEPPELIN-FLINK-1_0" "FLINK-1_11" "FLINK-1_13" "ZEPPELIN-FLINK-2_0" "FLINK-1_15" "ZEPPELIN-FLINK-3_0"], got FLINK-1_18
with aws_kinesisanalyticsv2_application.staging-<redacted>-managed-flink-app
on cdk.tf.json line 222, in resource.aws_kinesisanalyticsv2_application.staging-<redacted>-managed-flink-app:
```

### Expected Behavior

Should have updated the version of the Flink Application. 

### Actual Behavior

```
Error: expected runtime_environment to be one of ["SQL-1_0" "FLINK-1_6" "FLINK-1_8" "ZEPPELIN-FLINK-1_0" "FLINK-1_11" "FLINK-1_13" "ZEPPELIN-FLINK-2_0" "FLINK-1_15" "ZEPPELIN-FLINK-3_0"], got FLINK-1_18
with aws_kinesisanalyticsv2_application.staging-<redacted>-managed-flink-app
on cdk.tf.json line 222, in resource.aws_kinesisanalyticsv2_application.staging-<redacted>-managed-flink-app:
```

### Terraform Configuration Files

```
          runtimeEnvironment: "FLINK-1_18",
```

### Steps to Reproduce

CDKTF synth and upload to terraform cloud

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @jalilalchy 👋 Thanks for taking the time to raise this! We consider additions to existing resources to be an enhancement, rather than a bug. With that in mind, I'm going to update a few things about this issue. There's no further action needed from you at this point, I just like to let people know before making these kinds of modifications.
