### ISSUE TITLE
[Bug]: `aws_resourceexplorer2_search` 401 unauthorized returned when `view_arn` set

### ISSUE THREAD

**Issue by Rickerd0613** [hashicorp/terraform-provider-aws#36721]
### Terraform Core Version

1.5.2

### AWS Provider Version

5.43.0

### Affected Resource(s)

* `aws_resourceexplorer2_search`

### Expected Behavior

`aws_resourceexplorer2_search` uses the specified view_arn to perform the search even if a default view is not set and does not return a 401.

### Actual Behavior

`aws_resourceexplorer2_search` returns a 401 Unauthorized error, similar to if no default view was set and the `view_arn` was not specified.

### Relevant Error/Panic Output Snippet

```shell
data.aws_resourceexplorer2_search.this: Reading...

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: reading AWS Resource Explorer Search Data Source ("test"): operation error Resource Explorer 2: Search, https response error StatusCode: 401, RequestID: aa8881c6-928a-4306-b102-3afa2ca748bc, UnauthorizedException: 
│ 
│   with data.aws_resourceexplorer2_search.this,
│   on main.tf line 17, in data "aws_resourceexplorer2_search" "this":
│   17: data "aws_resourceexplorer2_search" "this" {
│ 
│ operation error Resource Explorer 2: Search, https response error StatusCode: 401, RequestID: aa8881c6-928a-4306-b102-3afa2ca748bc, UnauthorizedException: 
╵
```

### Terraform Configuration Files

```hcl
terraform {

  required_version = ">= 1.5"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region  = "us-east-1"
}

data "aws_resourceexplorer2_search" "this" {
  query_string = "test"
  view_arn = "redacted_arn"
}

output "test" {
  value = data.aws_resourceexplorer2_search.this
}
```

### Steps to Reproduce

Use `aws_resourceexplorer2_search` as expected in an account + region where there is no default view, however, specify the optional parameter `view_arn` in your request.

### Important Factoids

A view + index exists in this region, however, there is no default view. I am aware the documentation says a 401 will be returned if there is no default view and the `view_arn` is not specified, but since I am specifying the `view_arn` I did not expect a 401.

The role being used has permission to query this resource.

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/resourceexplorer2_search#view_arn

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
I am able to reproduce the problem and learn more from the debug logs. It seems that even when `view_arn` is provided, it is not included in the API request payload:

```
2024-04-04T01:54:44.467-0400 [DEBUG] provider.terraform-provider-aws.exe: HTTP Request Sent: net.peer.name=resource-explorer-2.us-east-1.amazonaws.com tf_aws.sdk=aws-sdk-go-v2 tf_data_source_type=aws_resourceexplorer2_search @module=aws http.request_content_length=22 http.request.header.amz_sdk_invocation_id=4ab02989-a978-48eb-9080-b0ecf9b06394 tf_mux_provider="*proto5server.Server" tf_req_id=725d158d-66ae-0a11-c7cb-73cb76b2f91c http.method=POST http.request.header.amz_sdk_request="attempt=1; max=25" http.url=https://resource-explorer-2.us-east-1.amazonaws.com/Search rpc.service="Resource Explorer 2" http.request.header.x_amz_security_token="*****" tf_rpc=ReadDataSource
  http.request.body=
  | {"QueryString":"test"}
   http.request.header.x_amz_date=20240404T055444Z http.user_agent="APN/1.0 HashiCorp/1.0 Terraform/1.6.3 (+https://www.terraform.io) terraform-provider-aws/dev (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go-v2/1.26.1 os/windows lang/go#1.21.8 md/GOOS#windows md/GOARCH#amd64 api/resourceexplorer2#1.10.4" rpc.method=Search tf_aws.signing_region="" aws.region=us-east-1 http.request.header.authorization="AWS4-HMAC-SHA256 Credential=ASIA************GUCD/20240404/us-east-1/resource-explorer-2/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date;x-amz-security-token, Signature=*****" tf_provider_addr=registry.terraform.io/hashicorp/aws rpc.system=aws-api @caller=C:/Users/Anthony/go/pkg/mod/github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.50/logging/tf_logger.go:45 http.request.header.content_type=application/json timestamp=2024-04-04T01:54:44.467-0400
2024-04-04T01:54:44.656-0400 [DEBUG] provider.terraform-provider-aws.exe: HTTP Response Received: http.response.header.access_control_allow_origin="*" rpc.method=Search http.response.header.access_control_expose_headers=Access-Control-Allow-Origin http.response.header.content_type=application/json tf_mux_provider="*proto5server.Server" tf_provider_addr=registry.terraform.io/hashicorp/aws rpc.system=aws-api http.duration=188
  http.response.body=
  | {"message": "Unauthorized" }
   http.response.header.date="Thu, 04 Apr 2024 05:54:42 GMT" rpc.service="Resource Explorer 2" tf_aws.signing_region="" @module=aws http.response.header.x_amzn_errortype=UnauthorizedException tf_rpc=ReadDataSource aws.region=us-east-1 http.response.header.x_amz_apigw_id=Vr8JbEDYoAMERNQ= http.response_content_length=28 http.response.header.x_amzn_requestid=ac072c78-d29d-4654-8b0e-af17fe39eac3 http.status_code=401 tf_aws.sdk=aws-sdk-go-v2 tf_data_source_type=aws_resourceexplorer2_search @caller=C:/Users/Anthony/go/pkg/mod/github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.50/logging/tf_logger.go:45 tf_req_id=725d158d-66ae-0a11-c7cb-73cb76b2f91c timestamp=2024-04-04T01:54:44.656-0400
```

This results in the 401 unauthorized error as documented in the [API reference](https://docs.aws.amazon.com/resource-explorer/latest/apireference/API_Search.html):

> If you don't specify a value for this parameter, then the operation automatically uses the default view for the AWS Region in which you called this operation. If the Region either doesn't have a default view or if you don't have permission to use the default view, then the operation fails with a `401 Unauthorized` exception.

**Comment by acwwat** [comment]
Quite a few things seem to be wrong with this data source from what I can tell:

- `view_arn` is not passed into the request
- Panics due to bad mapping between AWS API model and Terraform model
- `resource_count` is not entered into state data
- State is not persisted/updated after the AWS API call
- `id` likely needs the view_arn in addition to `query_string` (default view could be a special case)
