### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by zokye** [hashicorp/terraform-provider-aws#36741]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appflow_flow

### Description

I'm having trouble finding the correct values to filter fields that are not null. Here's the code I'm using

task{
task_type= "Validate"

conector_operator{
  salesforce="VALIDATE_NOT_NULL"
}

source_fields = ["Title"]

task_properties = {
   VALIDATION_ACTION = ¿? what values fit in here 
}
}

can you help me with this code?

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @zokye 👋 Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. To maintain that, we ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). With that in mind, I'll be closing this issue.
