### ISSUE TITLE
[Enhancement]: Support additional timeout options for 'aws_imagebuilder_image'

### ISSUE THREAD

**Issue by bryant-finney** [hashicorp/terraform-provider-aws#36757]
### Description

# Summary

My team is encountering the following error when using the [aws_imagebuilder_image](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/imagebuilder_image) resource:

> [!CAUTION]
> 
> ```
> │ Error: waiting for Image Builder Image (arn:aws:imagebuilder:us-east-1:************:image/the-image/1.2.3/1) to become available: timeout while waiting for state to become 'AVAILABLE' (last state: 'DISTRIBUTING', timeout: 1h0m0s)
> │ 
> │   with aws_imagebuilder_image.the_image,
> │   on main.tf line 15, in resource "aws_imagebuilder_image" "the_image":
> │   15: resource "aws_imagebuilder_image" "the_image" {
> │ 
> ```

We would like to extend this `1h0m0s` timeout so that `terraform apply` is able to provision the AMI before the timeout is reached.

### Affected Resource(s) and/or Data Source(s)

* [aws_imagebuilder_image](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/imagebuilder_image)
* [aws_imagebuilder_distribution_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/imagebuilder_distribution_configuration)

### Potential Terraform Configuration

```terraform
resource "aws_imagebuilder_image" "the_image" {
  distribution_configuration_arn   = "arn:aws:imagebuilder:us-east-1:************:distribution-configuration/settings"
  infrastructure_configuration_arn = "arn:aws:imagebuilder:us-east-1:************:infrastructure-configuration/settings"
  image_recipe_arn                 = "arn:aws:imagebuilder:us-east-1:************:image-recipe/the-image/1.2.3"

  timeout_minutes = 120
}
```

**Comment by acwwat** [comment]
@bryant-finney I believe that `aws_imagebuilder_image` already supports the [`timeouts` block](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/imagebuilder_image#timeouts), which allows you to override the resource creation timeout. Have you tried this configuration yet?
