### ISSUE TITLE
[Bug]: s3_configuration is not accepted under http_endpoint_configuration

### ISSUE THREAD

**Issue by saurabh1611** [hashicorp/terraform-provider-aws#36796]
### Terraform Core Version

1.7.5

### AWS Provider Version

5.44.0

### Affected Resource(s)

aws_kinesis_firehose_delivery_stream

### Expected Behavior

When creating the stream for Dynatrace, I am using http_endpoint_configuration. s3_configuration is a mandatory field but when we pass that within the block terraform gives the following error -

```console
Error: Unsupported block type
│
│   on kinesis_firehose.tf line 15, in resource "aws_kinesis_firehose_delivery_stream" "demo_delivery_stream":
│   15: s3_configuration {
│
│ Blocks of type "s3_configuration" are not expected here.`
```

### Actual Behavior

It should provision the stream with the bucket. 

### Terraform Configuration Files

```terraform
resource "aws_kinesis_firehose_delivery_stream" "demo_delivery_stream" {
  name        = "${var.kinesis_stream_name}-delivery"
  destination = "http_endpoint"

  http_endpoint_configuration {
    url                = "https://example.com/my-endpoint"
    name               = "Dynatrace"
    access_key         = "TESTKEYHERE'"
    buffering_size     = 3
    buffering_interval = 60
    role_arn           = aws_iam_role.firehose_role.arn
    s3_backup_mode     = "FailedDataOnly"
    retry_duration = 900

    s3_configuration {
      role_arn           = aws_iam_role.firehose_role.arn
      bucket_arn         = aws_s3_bucket.demo_bucket.arn
      buffering_size     = 10
      buffering_interval = 400
      compression_format = "GZIP"
    }

    request_configuration {
      content_encoding = "GZIP"
    }
  }
}
```

### Steps to Reproduce

terraform plan shows the error.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @saurabh1611 👋 Thank you for taking the time to raise this! Your configuration looks valid at first glance, so I think we'll need a bit more information here. Are you able to supply debug logs (redacted as necessary)?

**Comment by parthyp** [comment]
it looks like there is a bug in docs. 

you need to move  `s3_configuration` out of `http_endpoint_configuration` 

we ran into same issue with splunk configuration.

**Comment by smathangi** [comment]
same error in the plan 
`│ Error: Unsupported block type
│   on  resource "aws_kinesis_firehose_delivery_stream" "kinesis_firehose_stream":
│   28:     s3_configuration {
│ Blocks of type "s3_configuration" are not expected here.`

When I moved out of  `http_endpoint_configuration` the plan was okay but terraform apply failed with 

`Error: When destination is http_endpoint, s3_configuration is required`

**Comment by smathangi** [comment]
it looks like it's aws provider version incomparability. For versions **< 5.0.0** "s3_configuration" should be outside of http_endpoint_configuration as per the docs. 
https://registry.terraform.io/providers/hashicorp/aws/4.67.0/docs/resources/kinesis_firehose_delivery_stream#http-endpoint-eg-new-relic-destination

**Comment by justinretzolk** [comment]
@saurabh1611 can you confirm whether your issue may also have been related to the version, as mentioned above?

**Comment by dipanjanforexperian** [comment]
I am also facing similar issue while setting up firehose for Splunk. After coming across this thread, I tried  keeping the s3_configuration outside. But no luck. 
code structure I used:

`resource "aws_kinesis_firehose_delivery_stream" "firehose_test_stream" {
  name        = "firehose-test-stream"
  destination = "splunk"

  s3_configuration {
      role_arn           = aws_iam_role.abc.arn
      bucket_arn         = aws_s3_bucket.demo_bucket.arn
      buffering_size     = 10
      buffering_interval = 400
      compression_format = "GZIP"
    }
  splunk_configuration {
    hec_endpoint               = "https://example.com/my-endpoint"
    hec_token                  = "####"
    hec_acknowledgment_timeout = 600
    hec_endpoint_type          = "Event"
    s3_backup_mode             = "FailedEventsOnly"
  }
}`

Error I am getting:

`Error: Unsupported argument

  on kinesis_firehose.tf line 48, in resource "aws_kinesis_firehose_delivery_stream" "firehose_test_stream":
  48:       buffering_size     = 10

An argument named "buffering_size" is not expected here.

Error: Unsupported argument

  on kinesis_firehose.tf line 49, in resource "aws_kinesis_firehose_delivery_stream" "firehose_test_stream":
  49:       buffering_interval = 400

An argument named "buffering_interval" is not expected here.`
