### ISSUE TITLE
[Meta-Issue]: Autoflex General Availability 

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#36815]
### Description

[Autoflex](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/framework/flex/autoflex.go) is a transparent type mapping component which is currently being used in a number of resources and datasources in the provider. This prevents the need for manual creation and maintenance of mapping functions to be required as part of resource implementation.

This is significant step forward in reducing the time it takes to create (and maintain) a resource, so the end goal is for the team to require its usage for new resources to maximize its effect. In order to do this, a number of tasks need to be completed:

**Comprehensive contributor documentation**

- How to use Autoflex
- How to troubleshoot Autoflex
- How to raise issues related to Autoflex

**Improved Tracing/Logging**

Currently problems with Autoflex can be difficult to pinpoint without detailed knowledge of the component. Problems with Autoflex should be easy to identify.

**Completion of any known Unsupported Types**

- https://github.com/hashicorp/terraform-provider-aws/issues/36508

**Policy Change Announcement**

- A clear timeframe for any policy requiring Autoflex's use need to be communicated to the community ahead of the date it goes into affect.
- This includes any automation/checks required to flag manual flex functions.

### Would you like to implement a fix?

None

**Comment by diofeher** [comment]
+1 on that. I've been writing my first TF resource and it seems besides understanding how schema should be used, the other huge part of the work is to understand expanders and flatters

**Comment by breathingdust** [comment]
Autoflex is now considered GA and is required for use in net-new resources / data-sources. See: https://github.com/hashicorp/terraform-provider-aws/issues/38907
