### ISSUE TITLE
[Bug]: aws_batch_job_definition: After updating the resource the revision, id and arn attributes still show the previous revision

### ISSUE THREAD

**Issue by fergoid** [hashicorp/terraform-provider-aws#36824]
Same as #36865
Relates to #36894
Results from #35149?

### Terraform Core Version

1.7.5

### AWS Provider Version

5.44.0

### Affected Resource(s)

* aws_batch_job_definition

### Expected Behavior

Each update to the job definition created a new revision of the job definition and the attributes should reflect the new revision not the previous one.  For example we would use the ARN attribute in an EventBridge target and we want to update that to target the latest active  revision.

This worked correctly in v5.43.0, it looks like something may have changed on the back of the introduction of [deregister_on_new_revision] in 5.44?(https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/batch_job_definition#deregister_on_new_revision)

### Actual Behavior

* Create a new job definition and  revision, ARN and Id attributes will show revision 1 as expected
* Update the resource and all of the attributes still show revision 1 even though the active resource is now at revision 2.
* Running a subsequent Terraform plan returns the correct revision.

### Terraform Configuration Files

```
resource "aws_batch_job_definition" "test" {
  name = "${terraform.workspace}-foo"
  type = "container"
  container_properties = jsonencode({
    command = ["ls", "-la"],
    image   = "busybox"

    resourceRequirements = [
      {
        type  = "VCPU"
        value = "1"
      },
      {
        type  = "MEMORY"
        value = "512"
      }
    ]

    volumes = [
      {
        host = {
          sourcePath = "/tmp"
        }
        name = "tmp"
      }
    ]

    environment = [
      {
        name  = "VARNAME"
        value = "VARVAL"
      }
    ]

    mountPoints = [
      {
        sourceVolume  = "tmp"
        containerPath = "/tmp"
        readOnly      = false
      }
    ]

    ulimits = [
      {
        hardLimit = 1024
        name      = "nofile"
        softLimit = 1024
      }
    ]
  })
}

output arn {
  value = aws_batch_job_definition.test.arn
}

output id {
  value = aws_batch_job_definition.test.id
}

output revision {
  value = aws_batch_job_definition.test.revision
}
```

### Steps to Reproduce

* Plan/apply an aws_batch_job_definition with outputs for id, ARN and id.  The outputs will be showing revision 1.
* Update the resource (one which does not force new, I was updating the command flipping between 'ls -la' and 'ls -lah')  with plan/apply and outputs will still be showing revision 1 event though the active resource in AWS is now revision 2.
* Run another plan and the outputs will now show revision 2

### Would you like to implement a fix?

Yes

**Comment by theriault** [comment]
Potentially related - any `tags` appear to not get defined on the new revision as well and it requires a rerun for it to add tags to the new revision.

**Comment by MDBox** [comment]
I am also getting this bug. It seems that in version 5.43.0 it does `forces replacement` but in later versions it does an `update in-place` change.

**Comment by epgui** [comment]
I am also seeing this in 5.45.0.

**Comment by PaulDMendoza** [comment]
I'm also seeing this issue
