### ISSUE TITLE
[Docs]: KMS Key Alias Outputs are not all there

### ISSUE THREAD

**Issue by DMEvanCT** [hashicorp/terraform-provider-aws#36842]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs

### Description

	d.Set("name", alias.AliasName)
	d.Set("name_prefix", create.NamePrefixFromName(aws.StringValue(alias.AliasName)))

There is a name and name_prefix attribute for Terraform output that's missing.

### Would you like to implement a fix?

Yes

**Comment by DMEvanCT** [comment]
Created pull request 36843

**Comment by justinretzolk** [comment]
Closed via #36843

Thank you for the contribution!
