### ISSUE TITLE
[Enhancement]: GitLab support on CodeBuild

### ISSUE THREAD

**Issue by Menahem1** [hashicorp/terraform-provider-aws#36852]
### Description

AWS Codebuild can now support Gitlab as source

### Affected Resource(s) and/or Data Source(s)

- aws_codebuild_project

### Potential Terraform Configuration

```
resource "aws_codebuild_project" "example" {
  source {
    type            = "GITLAB"
    location        = "https://gitlab.com/mitchellh/packer.git"
    git_clone_depth = 1
  }
}
```

### References

https://aws.amazon.com/about-aws/whats-new/2024/03/aws-codebuild-gitlab-gitlab-self-managed/?nc1=h_ls

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
@Menahem1 It seems that as of v5.44.0, the provider had the AWS Go SDK v2 dependencies updated in include a version that supports GitLab and GitLab Self Managed. If you are not on this provider version or later, please upgrade and see if setting source `type = "GITLAB"` works. Appreciate if you could report back on the test results.

**Comment by Menahem1** [comment]
> @Menahem1 It seems that as of v5.44.0, the provider had the AWS Go SDK v2 dependencies updated in include a version that supports GitLab and GitLab Self Managed. If you are not on this provider version or later, please upgrade and see if setting source `type = "GITLAB"` works. Appreciate if you could report back on the test results.

It works, thanks :)

**Comment by Menahem1** [comment]
> > @Menahem1 It seems that as of v5.44.0, the provider had the AWS Go SDK v2 dependencies updated in include a version that supports GitLab and GitLab Self Managed. If you are not on this provider version or later, please upgrade and see if setting source `type = "GITLAB"` works. Appreciate if you could report back on the test results.
> 
> It works, thanks :)

Update : With [report_build_status](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codebuild_project#report_build_status) option on GitLab it's not working in my case

**Comment by acwwat** [comment]
> > > @Menahem1 It seems that as of v5.44.0, the provider had the AWS Go SDK v2 dependencies updated in include a version that supports GitLab and GitLab Self Managed. If you are not on this provider version or later, please upgrade and see if setting source `type = "GITLAB"` works. Appreciate if you could report back on the test results.
> > 
> > 
> > It works, thanks :)
> 
> Update : With [report_build_status](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codebuild_project#report_build_status) option on GitLab it's not working in my case

@Menahem1 Could you please open a new issue? I can address the specific case for `report_build_status`. Thanks.

**Comment by Menahem1** [comment]
No problem
https://github.com/hashicorp/terraform-provider-aws/issues/36937
Thanks
