### ISSUE TITLE
[Bug]: Change to aws_batch_job_definition does not trigger replacement of dependent resources since 5.44

### ISSUE THREAD

**Issue by ignatenkobrain** [hashicorp/terraform-provider-aws#36865]
Same as #36824
Relates to #36894
Results from #35149?

### Terraform Core Version

1.8.0

### AWS Provider Version

5.44.0

### Affected Resource(s)

* `aws_batch_job_definition`

### Expected Behavior

With 5.43.0:

```
  # module.jobs.aws_batch_job_definition.this["dbt"] must be replaced
-/+ resource "aws_batch_job_definition" "this" {
      ~ arn                   = "arn:aws:batch:eu-west-1:928420166487:job-definition/xxx-dbt-prod:24" -> (known after apply)
      ~ arn_prefix            = "arn:aws:batch:eu-west-1:928420166487:job-definition/xxx-dbt-prod" -> (known after apply)
      ~ container_properties  = jsonencode(
          ~ {
              ~ environment                  = [
                    # (1 unchanged element hidden)
                  ~ {
                        name  = "DBT_SNOWFLAKE_WAREHOUSE"
                      ~ value = "XXX" -> "YYY"
                    },
…
                ]
            } # forces replacement
        )
```

this was the state before and as `arn` is known after apply.…

```
  # module.dbt_runner.aws_lambda_function.this[0] will be updated in-place
  ~ resource "aws_lambda_function" "this" {
```

### Actual Behavior

However, after upgrade…

```
  # module.jobs.aws_batch_job_definition.this["dbt"] will be updated in-place
  ~ resource "aws_batch_job_definition" "this" {
      ~ container_properties       = jsonencode(
          ~ {
              ~ environment                  = [
                    # (1 unchanged element hidden)
                    {
                        name  = "DBT_SNOWFLAKE_DATABASE"
                        value = "XXX"
                    },
                  ~ {
                        name  = "DBT_SNOWFLAKE_WAREHOUSE"
                      ~ value = "XXX" -> "YYY"
                    },
                    {
                        name  = "DBT_USE_COLORS"
                        value = "false"
                    },
                ]
              - fargatePlatformConfiguration = {
                  - platformVersion = "LATEST"
                }
              - mountPoints                  = []
              - ulimits                      = []
              - volumes                      = []
                # (5 unchanged attributes hidden)
            }
        )
        id                         = "arn:aws:batch:eu-west-1:928420166487:job-definition/xxx-dbt-prod:24"
        name                       = "xxx-dbt-prod"
        tags                       = {}
        # (11 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

The ARN is not changing so it does not propagate anywhere.

### Terraform Configuration Files

Sadly I don't have simple reproducer due to lack of time whilst preparing bugreport but I believe it is described well enough.

### Steps to Reproduce

1. Declare `aws_batch_job_definition` and some other resource that relies on the `arn` variable from the jobdef
2. Try to change jobdef envvars (that will trigger arn change)
3. The arn does not change without "double apply"

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Relates #35149

**Comment by LauH1987** [comment]
We're seeing what I believe is this issue as well after updating from `v5.43.0` to `v5.45.0`.

We're using the `terraform-aws-modules/batch/aws` module and with a trigger akin to this:

```terraform
resource "aws_cloudwatch_event_rule" "every_day" {
  name                = "${local.job_prefix}-every-day"
  description         = "Fires every day at 3:00 UTC"
  schedule_expression = "cron(0 3 * * ? *)"
}

resource "aws_cloudwatch_event_target" "start_batch_job" {
  rule      = aws_cloudwatch_event_rule.every_day.name
  target_id = "${local.job_prefix}-every-day"
  arn       = module.batch.job_queues.queue.arn
  role_arn  = aws_iam_role.event_role.arn

  batch_target {
    job_definition = module.batch.job_definitions.my_job.arn
    job_name       = module.batch.job_definitions.my_job.name
  }
}
```

After updating to `v.5.45.0` our event rule didn't trigger the the job to start. We observed that the event triggered but it didn't start the target. We identified that the revision in the event target was not updated to the newly deployed revision of the Batch job definition:
![2024-04-19_11-13 (resized)](https://github.com/hashicorp/terraform-provider-aws/assets/22587888/c964169b-3310-4fc6-b5e6-e46b13fbb6c6)
![2024-04-19_11-20 (resized)](https://github.com/hashicorp/terraform-provider-aws/assets/22587888/7766582d-d587-45a5-bb70-592430ce8616)


After reverting and pinning to `v5.43.0` we could see from the logs that it once again updated the `aws_cloudwatch_event_target`. This was missing from the deployment with `v5.45.0`:
```
# aws_cloudwatch_event_target.start_batch_job will be updated in-place
~ resource "aws_cloudwatch_event_target" "start_batch_job" {
      id             = "<redacted>-every-day"
      # (5 unchanged attributes hidden)

    ~ batch_target {
        ~ job_definition = "<redacted>job-def:24" -> (known after apply)
          # (3 unchanged attributes hidden)
      }
  }
```
From the AWS Console we could confirm that the revisions between the job definition and event target was matching again:
![After fix 2024-04-19_17-33 (resized)](https://github.com/hashicorp/terraform-provider-aws/assets/22587888/bbd0bf7c-de03-48ce-a47e-702a3ca9b98b)
![2024-04-19_17-34](https://github.com/hashicorp/terraform-provider-aws/assets/22587888/b84edd05-d8a3-4e1e-866f-664c0e4d9003)

I believe this is a similar bug reported in #36824 and as already mentioned this seems to relate to #35149
