### ISSUE TITLE
[Bug]: `make gen` saids no `no type name:` error when type name is set

### ISSUE THREAD

**Issue by teddylear** [hashicorp/terraform-provider-aws#36875]
### Terraform Core Version

1.8.0

### AWS Provider Version

pull request

### Affected Resource(s)

In [this terraform-aws-provider PR](https://github.com/hashicorp/terraform-provider-aws/pull/35634) with upgrading `aws_iam_role` from terraform plugin sdk to terraform plugin framework, when running `make gen` the following error is shown: 
```zsh
Generating tagging tests for internal/service/iam
Skipping tags test for iam.resourceSAMLProvider
Skipping tags test for iam.resourceServerCertificate
no type name: iam.NewResourceRole
exit status 1
```

However in [the upgraded resource](https://github.com/hashicorp/terraform-provider-aws/blob/517bf6732b7abde348e1c7f5d938ff8fb5e8ab30/internal/service/iam/role.go) the appropriate tags are set:
```go
// @FrameworkResource(name="Role")
// @Tags(identifierAttribute="id", resourceType="Role")
func NewResourceRole(_ context.Context) (resource.ResourceWithConfigure, error) {
```

### Expected Behavior

`make gen` would run successfully or if it does fail give a more accurate error message. 

### Actual Behavior

`make gen` fails with an error message that is unclear [relevant documentation](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/resource-tagging.md) does not give a clear answer. Also there are some formatting issues with the linked documentation that I can fix as part of this bug report. 

### Terraform Configuration Files

n/a

### Steps to Reproduce

checkout branch and run `make gen`

### Important Factoids

I'm more than happy to help contribute the fix to documentation and clearer error handling once someone can let me know what the original intent behind error message means. 

### Would you like to implement a fix?

None

**Comment by gdavison** [comment]
Thanks for submitting this, @teddylear. It was missed in the documentation, but the spec for `@FrameworkResource(...)` now requires the type name.

I'll update the documentation and the SDK -> Framework migration tooling
