### ISSUE TITLE
[Bug]: Instance is not destroyed if user_data changed though user_data_replace_on_change is true

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform-provider-aws#36923]
### Terraform Core Version

v1.7.4

### AWS Provider Version

v5.44.0

### Affected Resource(s)

* aws_instance

### Expected Behavior

according to documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#user_data_replace_on_change

> [user_data_replace_on_change](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#user_data_replace_on_change) - (Optional) When used in combination with user_data or user_data_base64 will trigger a destroy and recreate when set to true. Defaults to false if not set.

The terraform should warn if incompatible options provided together: 
```
  user_data_replace_on_change = true
  lifecycle {
    ignore_changes = [user_data]
  }

```

### Actual Behavior

I changed my user_data, but instance was not replace:
```
No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no
differences, so no changes are needed.
```

And no warnings was not issued.

### Terraform Configuration Files

```hcl
resource "aws_instance" "res-13" {
  instance_type           = "c4.large"
  ami                     = data.aws_ami.custom.id
  availability_zone       = "${var.aws_region}c"
  key_name                = var.aws_key_name
  disable_api_termination = true
  ebs_optimized           = true
  hibernation             = false

  root_block_device {
    volume_type           = "gp2"
    volume_size           = 8
    delete_on_termination = true
    tags                  = {}
  }


  vpc_security_group_ids = [
    aws_security_group.www.id,
  ]
  subnet_id                   = aws_subnet.c_prd_plntr.id
  associate_public_ip_address = true
  iam_instance_profile        = aws_iam_instance_profile.www.name
  depends_on                  = [aws_internet_gateway.prd_plntr]

  user_data                   = file("user-data/legacy-res-13.yaml")
  user_data_replace_on_change = true

  lifecycle {
    ignore_changes = [user_data]
  }

}
```

### Steps to Reproduce

Try to configure conflicting options together (they must conflict, but they are not):

```hcl
  user_data_replace_on_change = true
  lifecycle {
    ignore_changes = [user_data]
  }
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @EugenKon 👋 Thank you for taking the time to raise this! The `lifecycle` configuration block is part of Terraform Core, so the provider isn't able to alter that behavior. On the other side of that, there's no channel by which the provider is able to communicate with Terraform that ignoring a particular argument would be incompatible (frankly, it's an extremely niche situation). Since this isn't currently possible, and would need changes from Terraform Core in order to enable it, I'm going to close this issue for now. If there are upstream changes that allow for this type of thing, we'd be happy to take another look.
