### ISSUE TITLE
[Docs]: S3 Object Lock no longer needs a token field

### ISSUE THREAD

**Issue by tanelso2** [hashicorp/terraform-provider-aws#36938]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_object_lock_configuration#token

### Description

Hi there,

The `aws_s3_bucket_object_lock_configuration` object type has a field called `token` that it claims is needed to enable Object Lock on an existing S3 bucket.

This is no longer the case. As of November 2023, AWS allows you to enable Object Lock without specifying a token, and the current versions of the Object Lock documentation makes no reference to the token field.

I just tested this out myself with a quick demo. I was able to add Object Lock to an existing bucket without a token.

We should update the documentation to make it clear that the token is deprecated and no longer needed. The current documentation implies the opposite.

### References

https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock-configure.html
https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-s3-enabling-object-lock-buckets/

Relates https://github.com/hashicorp/terraform-provider-aws/pull/36530.

### Would you like to implement a fix?

Yes

**Comment by Jyots6914** [comment]
I will work on it and I will raise PR

**Comment by tanelso2** [comment]
Fantastic, thanks everyone who worked on this!
