### ISSUE TITLE
[Enhancement]: Add support for KMS Flexible key rotation

### ISSUE THREAD

**Issue by fabio-sv** [hashicorp/terraform-provider-aws#36948]
### Description

Add support for the new flexible automatic KMS key rotation features.

The KMS team has added 3 new features to CMK KMS:
1. customize the rotation period of a KMS key (from 90 days to 2560 days).
2. invoke key rotation on demand for CMK KMS keys.
3. view key rotation history of the given KMS key.

Point no. 2 most likely doesn't make sense to implement, though listing it here for completeness.

### Affected Resource(s) and/or Data Source(s)

* `aws_kms_key`

### Potential Terraform Configuration

```terraform
resource "aws_kms_key" "a" {
  description             = "My awesome key"
  deletion_window_in_days = 10
  enable_key_rotation     = true
  rotation_period_in_days = 90 # new
}
```

### References

Feature announcement: https://aws.amazon.com/about-aws/whats-new/2024/04/aws-kms-automatic-key-rotation/
Updated CLI docs: https://docs.aws.amazon.com/cli/latest/reference/kms/enable-key-rotation.html

### Would you like to implement a fix?

Yes

**Comment by aristosvo** [comment]
As it is a separate API, it probably will be a separate resource.

Probably needs #36178 as well before this new resource can be submitted.
