### ISSUE TITLE
[Enhancement]: Support for AWS WAF v2 body inspection size

### ISSUE THREAD

**Issue by mkwtsec** [hashicorp/terraform-provider-aws#36979]
### Description

AWS WAF v2 now supports a higher default HTTP body inspection size. Additionally it can be increased beyond the new default. 

### Affected Resource(s) and/or Data Source(s)

`aws_wafv2_web_acl_association` 

[The documentation should also be updated to reflect the larger inspection size](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl#oversize_handling)

### Potential Terraform Configuration

```terraform
Perhaps modify the `default_size_inspection_limit` to be a top-level setting in the resource?
```

### References

https://aws.amazon.com/about-aws/whats-new/2024/03/aws-waf-larger-body-inspections-regional-resources/

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
The new setting should be implemented as a `assoication_config` block in the `aws_wafv2_web_acl` resource. See [API reference](https://docs.aws.amazon.com/waf/latest/APIReference/API_CreateWebACL.html#WAF-CreateWebACL-request-AssociationConfig) for details.
