### ISSUE TITLE
[Docs]: aws_auditmanager_framework confusing use of plural "controls"

### ISSUE THREAD

**Issue by medavisjr** [hashicorp/terraform-provider-aws#37000]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/auditmanager_framework#controls

### Description

The `aws_auditmanager_framework` resource uses a [Set Nested Block](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/blocks/set-nested) schema to define the `controls` argument. The slim documentation and the fact that the argument is pluralized has caused some confusion for myself and others on my team.

The doc language for the argument:

> [control_sets](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/auditmanager_framework#control_sets)
[name](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/auditmanager_framework#name) - (Required) Name of the control set.
[controls](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/auditmanager_framework#controls) - (Required) List of controls within the control set. See [controls](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/auditmanager_framework#controls) below.

No example of multiple controls in a `control_sets` object is given, only:

```
resource "aws_auditmanager_framework" "test" {
  name = "example"

  control_sets {
    name = "example"
    controls {
      id = aws_auditmanager_control.test.id
    }
  }
}
```

This, plus the fact that `controls` is pluralized, each `controls` block can accept only one `id`, and the docs describe `controls` as a "List" of controls when it's actually wanting a map(string), could easily confuse a user into thinking they need to do something like this:

```
resource "aws_auditmanager_framework" "test" {
  name = "example"

  control_sets {
    name = "example"
    controls = [
      {
        id = aws_auditmanager_control.test.id
      },
      {
        id = aws_auditmanager_control.test2.id
      }
    ]
  }
}
```
This won't work, of course, and the user will get an error that a missing argument is required. Looking at the source Go code for this resource, the correct usage is to create multiple `controls` blocks:

```
resource "aws_auditmanager_framework" "test" {
  name = "example"

  control_sets {
    name = "example"
    controls {
      id = aws_auditmanager_control.test.id
    }
    controls {
      id = aws_auditmanager_control.test2.id
    }
  }
}
```

This is probably part documentation issue and part code issue as it seems like `controls` should be renamed to `control` if possible, or failing that, something else that's less of a misnomer, as each block of `controls` actually represents a single Audit Manager control and ID.

### References

https://developer.hashicorp.com/terraform/plugin/framework/handling-data/blocks/set-nested

### Would you like to implement a fix?

No

**Comment by acwwat** [comment]
I've submitted a PR to slightly improve the documentation. As for whether the configuration block arguments should be named in singular or plural, I agree that singular is more natural to end-users.

The general cause for the inconsistencies seem to be that AWS APIs tend to use plural as they take a list, but that doesn't translate 1-1 to block constructs in Terraform. I see both usages in the AWS provider.

Fixing the block name might be difficult as it affect backward compatibility, and I think the effort should be more coordinated across the provider. I will perhaps leave this question to a maintainer :)

I hope the documentation update helps a little.
