### ISSUE TITLE
KMS KEY : Require new argument 

### ISSUE THREAD

**Issue by Arulraj23** [hashicorp/terraform-provider-aws#37041]
### Description

For KMS key automatic rotation, I don't find any argument to specify custion rotation period. Ex: rotation_period_in_days = 90 

### Requested Resource(s) and/or Data Source(s)

For KMS key automatic rotation, I don't find any argument to specify custion rotation period. Ex: rotation_period_in_days = 90 

### Potential Terraform Configuration

```terraform
resource "aws_kms_key" "kms_key" {
  
rotation_period_in_days = 90 
}
```

### Would you like to implement a fix?

None

**Comment by aristosvo** [comment]
I think this one is a duplicate of #36948

**Comment by justinretzolk** [comment]
Duplicate of #36948
