### ISSUE TITLE
[Bug]: DependencyViolation with ENIs associated with security group of lambda

### ISSUE THREAD

**Issue by vamshidhar-rapolu** [hashicorp/terraform-provider-aws#37046]
### Terraform Core Version

1.8.1

### AWS Provider Version

5.46.0

### Affected Resource(s)

`aws_security_group`

### Expected Behavior

Terraform destroy of the lambda is expected to be successful with the `aws_security_group` being destroyed successfully. This works using the aws provider version `5.45.0`

### Actual Behavior

Terraform destroy fails to delete the security group of the lambda due to dependency on the network interface eni.
`╷
│ Error: deleting Security Group (sg-xxxxxxxxxxxxxxxxx): DependencyViolation: resource sg-xxxxxxxxxxxxxxxxx has a dependent object
│ 	status code: 400, request id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
│ 
│ 
╵`

Deleting the network interface(s) associated with the security group manually and retrying the terraform destroy works as expected.

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: deleting Security Group (sg-xxxxxxxxxxxxxxxxx): DependencyViolation: resource sg-xxxxxxxxxxxxxxxxx has a dependent object
│ 	status code: 400, request id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
│ 
│ 
╵
```

### Terraform Configuration Files
```
resource "aws_security_group" "this" {
  name   = "Redacted"
  vpc_id = "Redacted"

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["Redacted"]
  }
}

resource "aws_lambda_function" "lambda1" {
  description      = "Redacted"
  filename         = data.archive_file.Redacted.output_path
  function_name    = "Redacted"
  handler          = "Redacted.lambda_handler"
  role             = aws_iam_role.Redacted.arn
  runtime          = "python3.9"
  source_code_hash = data.archive_file.Redacted.output_base64sha256
  timeout          = 30

  vpc_config {
    subnet_ids         = var.subnet_ids
    security_group_ids = [aws_security_group.this.id]
  }
}

resource "aws_lambda_function" "lambda2" {
  description      = "Redacted"
  filename         = data.archive_file.Redacted.output_path
  function_name    = "Redacted"
  handler          = "Redacted.lambda_handler"
  role             = aws_iam_role.Redacted.arn
  runtime          = "python3.9"
  source_code_hash = data.archive_file.Redacted.output_base64sha256
  timeout          = 30

  vpc_config {
    subnet_ids         = var.subnet_ids
    security_group_ids = [aws_security_group.this.id]
  }
}
```

### Steps to Reproduce

Running `terraform destroy` isn't successful with aws provider `5.46.0` due to the `DependencyViolation` error stated above. 

### Important Factoids

There is no issue with the destroy run using the aws provider version `5.45.0`

### References

Relates https://github.com/hashicorp/terraform-provider-aws/pull/32756.

### Would you like to implement a fix?

None

**Comment by aniketcds** [comment]
i am also facing the same issue, security group stucks in still destroying...

**Comment by ewbankkit** [comment]
My guess is that it's this change: https://github.com/hashicorp/terraform-provider-aws/pull/32756/files#diff-70adcd9378e535279bc25fff083ca14942dbd30dbe445ac31fd194b3e61b3533R1467-R1468.

**Comment by vamshidhar-rapolu** [comment]
@ewbankkit The issue seems to be resolved. I don't see any errors with the deletion of security group.
