### ISSUE TITLE
[Bug]: Cannot use 'for_each' meta argument with deployments

### ISSUE THREAD

**Issue by bryant-finney** [hashicorp/terraform-provider-aws#37067]
### Terraform Core Version

1.7.4

### AWS Provider Version

5.44.0

### Affected Resource(s)

[aws_appconfig_deployment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appconfig_deployment)

### Expected Behavior

Consider the following resource:

```hcl
resource "aws_appconfig_deployment" "all" {
  for_each = var.profiles     # e.g. toset(["one", "two", "three"])

  application_id           = aws_appconfig_application.id

  # the following two resources are similarly created using a 'for_each' meta argument
  configuration_profile_id = aws_appconfig_configuration_profile.all[each.key].configuration_profile_id
  configuration_version    = aws_appconfig_hosted_configuration_version.all[each.key].version_number

  deployment_strategy_id   = aws_appconfig_deployment_strategy.instant.id
  environment_id           = aws_appconfig_environment.this.environment_id
}
```

When running `terraform apply` on the above, I would expect all three profiles to each have a deployment to the same environment

### Actual Behavior

I receive the following error:

> [!CAUTION]
>
> ```hcl
> ╷
> │ Error: starting AppConfig Deployment: operation error AppConfig: StartDeployment, https response error StatusCode: 409, RequestID: ****-**-**-**-******, ConflictException: Deployment number 1 already exists
> │ 
> │   with aws_appconfig_deployment.all["two"],
> │   on main.tf line 1, in resource "aws_appconfig_deployment" "all":
> │   1: resource "aws_appconfig_deployment" "all" {
> │ 
> ╵
> ╷
> │ Error: starting AppConfig Deployment: operation error AppConfig: StartDeployment, https response error StatusCode: 409, RequestID: ****-**-**-**-******, ConflictException: Deployment number 1 already exists
> │ 
> │   with aws_appconfig_deployment.all["three"],
> │   on main.tf line 1, in resource "aws_appconfig_deployment" "all":
> │   1: resource "aws_appconfig_deployment" "all" {
> │ 
> ╵
> Error: Process completed with exit code 1.
> ```

### Terraform Configuration Files

See _Expected Behavior_

### Steps to Reproduce

This happens consistently whenever `aws_appconfig_deployment` resources are created with a `for_each` meta argument. It seems that the deployment number does not increment as expected (perhaps due to concurrency?), as re-running `terraform apply` allows the next deployment to succeed.

### Would you like to implement a fix?

No

**Comment by bryant-finney** [comment]
To work around this issue, I had to remove the `for_each` meta argument and specify `depends_on`:

```hcl
resource "aws_appconfig_deployment" "one" {
  application_id           = aws_appconfig_application.id

  configuration_profile_id = aws_appconfig_configuration_profile.all["one"].configuration_profile_id
  configuration_version    = aws_appconfig_hosted_configuration_version.all["one"].version_number

  deployment_strategy_id   = aws_appconfig_deployment_strategy.instant.id
  environment_id           = aws_appconfig_environment.this.environment_id
}

resource "aws_appconfig_deployment" "two" {
  depends_on = [aws_appconfig_deployment.one]

  application_id           = aws_appconfig_application.id

  configuration_profile_id = aws_appconfig_configuration_profile.all["two"].configuration_profile_id
  configuration_version    = aws_appconfig_hosted_configuration_version.all["two"].version_number

  deployment_strategy_id   = aws_appconfig_deployment_strategy.instant.id
  environment_id           = aws_appconfig_environment.this.environment_id
}

resource "aws_appconfig_deployment" "three" {
  depends_on = [aws_appconfig_deployment.two]

  application_id           = aws_appconfig_application.id

  configuration_profile_id = aws_appconfig_configuration_profile.all["three"].configuration_profile_id
  configuration_version    = aws_appconfig_hosted_configuration_version.all["three"].version_number

  deployment_strategy_id   = aws_appconfig_deployment_strategy.instant.id
  environment_id           = aws_appconfig_environment.this.environment_id
}
```

**Comment by justinretzolk** [comment]
Hey @bryant-finney 👋 Thank you for taking the time to raise this! This seems like one of those cases where AWS won't allow concurrency in the way that `for_each` operates (with `for_each`, or without the explicit `depends_on`, Terraform would try to create these resources concurrently). Since I'm not aware of a way to mark resources created by `for_each` as dependent on each other, this is the behavior that I'd expect, and something the AWS provider won't have any control over. With that in mind, I'm going to close this issue.
