### ISSUE TITLE
Guardrails for Amazon Bedrock

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#37086]
> Guardrails for Amazon Bedrock is generally available with new safety & privacy controls

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/04/guardrails-amazon-bedrock-available-safety-privacy-controls/)
* [Blog post](https://aws.amazon.com/blogs/aws/guardrails-for-amazon-bedrock-now-available-with-new-safety-filters-and-privacy-controls/)

Relates https://github.com/hashicorp/terraform-provider-aws/issues/33809.

#### New Resource(s)

* `aws_bedrock_guardrail`

**Comment by sidatcd** [comment]
Any ETA on this?

**Comment by sasidhar-aws** [comment]
I will work on this issue.

**Comment by sasidhar-aws** [comment]
PR is created and waiting for review and merge.
