### ISSUE TITLE
[Enhancement]: Add Dynatrace support to Kinesis Firehose

### ISSUE THREAD

**Issue by MarkRoss-Eviden** [hashicorp/terraform-provider-aws#37102]
### Description

Amazon Firehose supports more destinations than the Terraform provider, Dynatrace is one such endpoint that is missing.

### Affected Resource(s) and/or Data Source(s)

kinesis_firehose_delivery_stream

### Potential Terraform Configuration

```terraform
resource "aws_kinesis_firehose_delivery_stream" "test_stream" {
  name        = "terraform-kinesis-firehose-test-stream"
  destination = "dynatrace"

  #Not complete config but gives an idea
  dynatrace_configuration {
    api_url                    = "https://xyzabc.live.dynatrace.com"
    api_token                  = "51D4DA16-C61B-4F5F-8EC7-ED4301342A4A"
    ingestion_type             = "logs"
    retry_timeout              = 60
  }
}
```

### References

https://aws.amazon.com/blogs/big-data/analyze-logs-with-dynatrace-davis-ai-engine-using-amazon-kinesis-data-firehose-http-endpoint-delivery/#

https://docs.dynatrace.com/docs/observe-and-explore/logs/lma-log-ingestion-via-api/lma-stream-logs-with-firehose

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/35274.

**Comment by ewbankkit** [comment]
To send to [Dynatrace](https://docs.aws.amazon.com/firehose/latest/dev/create-destination.html#create-destination-dynatrace) use the `http_endpoint` destination.
