### ISSUE TITLE
[Bug]: DMS DocumentDB replication config fails with DocumentDB is not supported

### ISSUE THREAD

**Issue by rhanak** [hashicorp/terraform-provider-aws#37110]
### Terraform Core Version

1.66

### AWS Provider Version

5.46.0

### Affected Resource(s)

* aws_dms_replication_config

### Expected Behavior

Expecting the replication config to get successfully created and the terraform apply to succeed.

### Actual Behavior

The replication config is successfully created but the terraform apply fails.

### Relevant Error/Panic Output Snippet

```shell
Error: creating DMS Replication Config (my-db-replication-config): InvalidParameterValueException: Source endpoint of engine type Amazon DocumentDB (with MongoDB compatibility) is not supported status code: 400
```

### Terraform Configuration Files

```hcl
resource "aws_dms_replication_config" "my-db-replication-config" {
  replication_config_identifier = "my-db-replication-config"
  resource_identifier           = "my-db-replication-config"
  replication_type              = "full-load-and-cdc"
  source_endpoint_arn           = aws_dms_endpoint.my-db-source.endpoint_arn
  target_endpoint_arn           = aws_dms_endpoint.my-db-target.endpoint_arn
  table_mappings                = <<EOF
  {
    "rules":[{"rule-type":"selection","rule-id":"1","rule-name":"1","rule-action":"include","object-locator":{"schema-name":"%%","table-name":"%%"}}]
  }
EOF

  start_replication = true

  compute_config {
    replication_subnet_group_id = aws_dms_replication_subnet_group.my-db-subnet-group.replication_subnet_group_id
    vpc_security_group_ids = [
      data.aws_security_group.my_default.id,
    ]
    max_capacity_units           = "64"
    min_capacity_units           = "2"
    preferred_maintenance_window = "sun:23:45-mon:00:30"
  }
}
```

### Steps to Reproduce

Created two dms endpoints for both source and target DocumentDB endpoints.
Created replication instance and config.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @rhanak 👋 Thank you for taking the time to raise this! Are you able to supply debug logs (redacted as necessary) as well? In this case, the error makes me think that this might be related to the configuration rather than a bug with the provider, but logging might help determine for sure.

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
