### ISSUE TITLE
[Bug]: Empty tags on aws_eks_pod_identity_association causes drift

### ISSUE THREAD

**Issue by calvinbui** [hashicorp/terraform-provider-aws#37146]
### Terraform Core Version

1.8.2

### AWS Provider Version

5.47.0

### Affected Resource(s)

* aws_eks_pod_identity_association

### Expected Behavior

No change in resource

```
No changes. Your infrastructure matches the configuration.
```

### Actual Behavior

Change detected in with tags value.

### Terraform Configuration Files

I am using the [terraform-aws-modules/terraform-aws-eks-pod-identity](https://github.com/terraform-aws-modules/terraform-aws-eks-pod-identity/blob/v1.2.0/main.tf#L177-L186) module.

```hcl
resource "aws_eks_pod_identity_association" "this" {
  for_each = { for k, v in var.associations : k => v if var.create }

  cluster_name    = try(each.value.cluster_name, var.association_defaults.cluster_name)
  namespace       = try(each.value.namespace, var.association_defaults.namespace)
  service_account = try(each.value.service_account, var.association_defaults.service_account)
  role_arn        = aws_iam_role.this[0].arn

  tags = merge(var.tags, try(each.value.tags, var.association_defaults.tags, {}))
}
```

### Steps to Reproduce

1. Create `aws_eks_pod_identity_association` with no empty tags (`tags = {}`)

```hcl
  + resource "aws_eks_pod_identity_association" "this" {
      + association_arn = (known after apply)
      + association_id  = (known after apply)
      + cluster_name    = "mycluster"
      + id              = (known after apply)
      + namespace       = "kube-system"
      + role_arn        = "arn:aws:iam::1234567890:role/aws-ebs-csi-driver-20240426012547740300000001"
      + service_account = "ebs-csi-controller-sa"
      + tags            = {}
      + tags_all        = {
          + "ortto.com/env"           = "xxx"
          + "ortto.com/owner"         = "xxx"
          + "ortto.com/project"       = "xxx"
          + "ortto.com/repo"          = "xxx"
          + "ortto.com/role"          = "xxx"
        }
    }
```

2. Run another plan and see the resource has drifted with empty tags, even on subsequent applies.

```hcl
  # module.pod_identity.aws_eks_pod_identity_association.this["xxx"] will be updated in-place
  ~ resource "aws_eks_pod_identity_association" "this" {
        id              = "a-xxx"
      + tags            = {}
        # (7 unchanged attributes hidden)
    }
```

However is `tags` is NOT empty, a tag is created, and the module does not detect a drift on the next run.

The `tags_all` tags from `default_tags` work and are present on the AWS resource.

### References

Same issue faced in https://github.com/terraform-aws-modules/terraform-aws-eks-pod-identity/issues/7 and referred here.

### Would you like to implement a fix?

No

**Comment by aristosvo** [comment]
Hi @calvinbui!

I am not 100% sure this is an resource issue, it might be a configuration issue. Have you tried `null` instead of `{}` already?

**Comment by calvinbui** [comment]
> Hi @calvinbui!
> 
> I am not 100% sure this is an resource issue, it might be a configuration issue. Have you tried `null` instead of `{}` already?

yep that seems like the case.

- `{}` --> drift
- `null` --> no drift
- removed the tag key --> no drift

i'll raise the issue back over in the module repo
