### ISSUE TITLE
[Enhancement]: SageMaker Studio now supports custom images for Code Editor Applications

### ISSUE THREAD

**Issue by michaelneely** [hashicorp/terraform-provider-aws#37153]
### Description

Similarly to JupyterLab and Kernel Gateway apps, AWS Sagemaker now supports using custom images for Code Editor applications, see the docs [here](https://docs.aws.amazon.com/sagemaker/latest/dg/code-editor-custom-images-provide-access.html).

This would be a relatively quick addition to add in the aws_sagemaker_domain resource.

### Affected Resource(s) and/or Data Source(s)

aws_sagemaker_domain

### Potential Terraform Configuration

```terraform
resource "aws_sagemaker_domain" "code_editor_domain" {

  default_user_settings {

    code_editor_app_settings {
      custom_image = [
        app_image_config_name = aws_sagemaker_app_image_config.example.app_image_config_name
        image_name            = aws_sagemaker_image_version.example.image_name
        image_version         = 1
      ]
    }
  }
}
```

### References

1. https://docs.aws.amazon.com/sagemaker/latest/dg/code-editor-custom-images-provide-access.html
2. https://aws.amazon.com/about-aws/whats-new/2024/04/amazon-sagemaker-studio-code-editor-custom-images/

### Would you like to implement a fix?

Yes

**Comment by tkimble-cafeyn** [comment]
Would be cool to add a code_repository block as well. Something like this:

```
code_repository {
  repository_url = "repo_url.git"
}
```

**Comment by damianslee** [comment]
any update sagemaker domain to support codeeditor custom images

app image config already supports codeeditor custom images, but can not use it cause its missing from sagemaker domains
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_app_image_config
