### ISSUE TITLE
[Bug]: Error: updating Amazon EventBridge Pipes - "Invalid target parameter provided for target."

### ISSUE THREAD

**Issue by Wool3673** [hashicorp/terraform-provider-aws#37150]
### Terraform Core Version

0.13

### AWS Provider Version

5.46.0

### Affected Resource(s)

aws_pipes_pipe 
...
target_parameters {
    cloudwatch_logs_parameters {
      log_stream_name = 
    }
  }

#https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pipes_pipe#cloudwatch_logs_parameters

### Expected Behavior

Enabled CloudWatch Logs log stream as a target.

### Actual Behavior

Fails with a 400 error.

### Relevant Error/Panic Output Snippet

```shell
Error: updating Amazon EventBridge Pipes Pipe (my-pipe-foo): operation error Pipes: UpdatePipe, https response error StatusCode: 400, RequestID: d81cfed9-5b21-4a9a-b31f-3accc6eca111, ValidationException: {"ValidationErrorFields":[{"Name":"CloudWatchLogsParameters","Message":"Invalid target parameter provided for target."}]}
```

### Terraform Configuration Files

```
resource "aws_pipes_pipe" "EBPipe" {

  depends_on = [aws_sqs_queue.DeadLetterQueue, aws_kinesis_stream.foo_kinesis_stream, aws_iam_role.pipesrole]

  name       = "${var.app_name}-EB-Pipes-${var.release}-${var.region}"
  role_arn   = aws_iam_role.pipesrole.arn
  source     = aws_kinesis_stream.foo_kinesis_stream.arn
  target     = "arn:aws:lambda:${var.region}:${var.account}:function:lambdafoo-${var.release}-${var.region}"
  

  source_parameters {
    kinesis_stream_parameters {
        starting_position = "LATEST"
        batch_size = 1
        maximum_batching_window_in_seconds = 10
        maximum_record_age_in_seconds = 86400 
        maximum_retry_attempts = -1 
        on_partial_batch_item_failure = "AUTOMATIC_BISECT"
        parallelization_factor = 1
        #starting_position_timestamp = "AT_TIMESTAMP"

        dead_letter_config {
          arn = aws_sqs_queue.DeadLetterQueue.arn
        }
    }
  }

  target_parameters {
    cloudwatch_logs_parameters {
           log_stream_name = #tried various values
    }
  }
}
```

### Steps to Reproduce

Attempt to uses this "target_parameters Configuration Block" withing the "aws_pipes_pipe" resource.
```
...
target_parameters {
    cloudwatch_logs_parameters {
      log_stream_name = 
    }
  }
```

### References

Hashicorp forum post with details - https://discuss.hashicorp.com/t/resource-aws-pipes-pipe-target-parameters-cloudwatch-logs-parameters/66335

### Would you like to implement a fix?

None

**Comment by aristosvo** [comment]
Hey @Wool3673!

I see that you are using a lambda as a target while using CloudWatch `target_paramaters`. This is how it's used in the acceptance tests:
```hcl
resource "aws_pipes_pipe" "example" {
...
  target   = aws_cloudwatch_log_group.target.arn
  ...
  target_parameters {
    cloudwatch_logs_parameters {
        log_stream_name = aws_cloudwatch_log_stream.target.name
      }
  }
..
```

Does this solve your issue?

**Comment by Wool3673** [comment]
> Hey @Wool3673!
> 
> I see that you are using a lambda as a target while using CloudWatch `target_paramaters`. This is how it's used in the acceptance tests:
> 
> ```terraform
> resource "aws_cloudwatch_log_group" "target" {
>   name = "example-target-group"
> }
> 
> resource "aws_cloudwatch_log_stream" "target" {
>   name           = "example-target-stream"
>   log_group_name = aws_cloudwatch_log_group.target.name
> }
> 
> resource "aws_pipes_pipe" "example" {
>   ...
>   target = aws_cloudwatch_log_group.target.arn
>   ...
>   target_parameters {
>     cloudwatch_logs_parameters {
>       log_stream_name = aws_cloudwatch_log_stream.target.name
>     }
>   }
> }
> ```
> 
> Does this solve your issue?

Hello @aristosvo, thanks for replying! 

so it's possible I'm misunderstaning how things are actually working compared with how I think it's working. You are correct we're using a Lambda as the EB Pipes target. However, what we are trying achieve with "cloudwatch_logs_parameters" is logging to CW Logs/Stream, not using it as the place we EB pipes forwards the data to. Have I misunderstood the use of "cloudwatch_logs_parameters"? I've included a screenshot of the AWS Management Console UI where this can be performed. I have been approaching using "cloudwatch_logs_parameters" as the same, is this incorrect?

I had tried using a similar set-up to what you've suggested with the difference being I was still using the Lambda as the target. I recevied the same error.
![CW-Logs](https://github.com/hashicorp/terraform-provider-aws/assets/107929144/7888e75b-ff20-4452-81ed-10d897052b6b)

**Comment by Wool3673** [comment]
So it seems that I've misunderstood the operation. 

If I'm not mistaken, from the sample @aristosvo has provided it means the "cloudwatch_logs_parameters" is only for when using CW log group as the target, not how I was trying to use it. 

I had initially found the enhancement request for CW logging last week but misunderstood it, doh. I even commented haha.
https://github.com/hashicorp/terraform-provider-aws/issues/35216

I will close this bug as it's not a bug, just me being a fool. 

Thanks again for replying @aristosvo, it helped a lot.
