### ISSUE TITLE
[Enhancement]: Default VPC filter on d/aws_vpcs

### ISSUE THREAD

**Issue by rubenandre** [hashicorp/terraform-provider-aws#37175]
### Description

I did a quick search and I didn't find any similar issue.

It would be interesting to d/aws_vpcs have an extra filter that would allow to exclude default vpcs from the result

Right now it's possible to achieve this in the following way, but a more direct way would be benefical

```terraform
data "aws_vpcs" "all_vpcs" {}
data "aws_vpc" "default_vpc" {
  default = true
}

locals {
   non_default_vpcs = setsubtract(data.aws_vpcs.all_vpcs.ids, [data.aws_vpc.default_vpc.id])
}
```

### Affected Resource(s) and/or Data Source(s)

aws_vpcs

### Potential Terraform Configuration

```terraform
# Normal case (all types of vpcs returned)
data "aws_vpcs" "example1" {}

# Only return non-default vpcs
data "aws_vpcs" "example2" {
  default = false
}

# Only return default vpc -> it would return the same as d/aws_vpc with default option set to true
data "aws_vpcs" "example3" {
  default = true
}
```

### Would you like to implement a fix?

None

**Comment by aristosvo** [comment]
Hi @rubenandre !

Is it not possible with `filter`, `name = "is-default"` etc?

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeVpcs.html

**Comment by rubenandre** [comment]
Yes, thanks! I didn't saw that one
