### ISSUE TITLE
[Bug]: Unable to import shared aws_route53_resolver_rule

### ISSUE THREAD

**Issue by packet-blaster** [hashicorp/terraform-provider-aws#37186]
### Terraform Core Version

1.7.3

### AWS Provider Version

5.47.0

### Affected Resource(s)

* aws_route53_resolver_rule

### Expected Behavior

Successful import

### Actual Behavior

Import rejected due to:
```
Error: listing tags for Route 53 Resolver Rule (arn:aws:route53resolver:us-east-1:111:resolver-rule/rslvr-rr-abc123): InvalidParameterException: [RSLVR-00907] You are not authorized to do this operation on shared resource
 {
   RespMetadata: {
     StatusCode: 400,
     RequestID: "xxx-xxx-xxx-xxx-xxx"
   },
   Message_: "[RSLVR-00907] You are not authorized to do this operation on shared resource"
 }
 ```

### Terraform Configuration Files

Basic resource with import block:
```
resource "aws_route53_resolver_rule" "rule1" {

  domain_name          = "example.com"
  name                 = "EXAMPLE-COM"
  rule_type            = "FORWARD"
  resolver_endpoint_id = "rslvr-out-abc123"

  target_ip {
    ip = "1.1.1.1"
  }
}

import {
  to       = aws_route53_resolver_rule.rule1
  id       = "rslvr-rr-abc123"
}
```

### Steps to Reproduce

Try to import an already existing `aws_route53_resolver_rule`.
I've tried with both an import block and the import command. Both give the same 400 eror.

### Important Factoids

The role I'm using to import is an admin role using the predefined `AdministratorAccess` and has the necessary `Route53Resolver.ListTagsForResource` permissions.

### References

There was a similasr issue for the data lookup across accounts, but I'm trying to import a rule within the same account my access is for.
* https://github.com/hashicorp/terraform-provider-aws/issues/10211

### Would you like to implement a fix?

None

**Comment by packet-blaster** [comment]
Same error on latest `terraform 1.8.2`. Provider already on latest version (`aws 5.47.0`)

**Comment by justinretzolk** [comment]
Hey @packet-blaster 👋 Thank you for taking the time to raise this! It looks like this is a permissions issue that our Support team has written [an article about](https://support.hashicorp.com/hc/en-us/articles/1500008434461-Troubleshooting-AWS-Permission-Errors). With the in mind, I'll close this issue out.

**Comment by packet-blaster** [comment]
Hi @justinretzolk, I have already mentioned that all permissions are in place. Im using an AWS provided role that has admin access to everything 

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
```
