### ISSUE TITLE
[Docs]: Enhance the `aws_rds_cluster_endpoint` documentation (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_endpoint) by indicating that this resource is related to Aurora custom endpoints.

### ISSUE THREAD

**Issue by MykKuc** [hashicorp/terraform-provider-aws#37183]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_endpoint

### Description

This is more of a documentation enhancement. In the intro section of documentation ("Manages an RDS Aurora Cluster Endpoint.") I would suggest indicating in some way that this is a resource related to Aurora custom endpoints. Because right now "Aurora Cluster Endpoint" might be a little confusing for newer people who are not familiar with Aurora endpoints. According to AWS documentation (https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Overview.Endpoints.html) there can be "cluster" and "custom" endpoint types. From the section one might think this is related to "cluster" endpoint type and not "custom" endpoint type.

I suggest changing it to "Manages an RDS Aurora Cluster Custom Endpoint" so it is more clearer.

### References
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Overview.Endpoints.html

### Would you like to implement a fix?

No

**Comment by rama280290** [comment]
I will work on this documentation update and raise PR
