### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by pswimalaweera** [hashicorp/terraform-provider-aws#37204]
### Terraform Core Version

1.7.3

### AWS Provider Version

5.47.0

### Affected Resource(s)

aws_dms_endpoint

### Expected Behavior

i was trying to create documentdb source endpoint  (engine monodb) with mongodb_settings.terraform is getting executed without any error .but the changes not reflecting in the  AwS console.

```hcl
mongodb_settings = {
    nesting_level = "one"
    docs_to_investigate = 1000
}
```

### Actual Behavior

in the aws console DMS  endpoint  metadata field should populated with table but it is there with empty field

### Terraform Configuration Files

```hcl
mongodb_settings = {
    nesting_level = "one"
    docs_to_investigate = 1000
}
```

### Steps to Reproduce

create dms end point with  above mongodb settings

### Would you like to implement a fix?

None

**Comment by pswimalaweera** [comment]
please let me know anybody has faced same kind of issue

**Comment by justinretzolk** [comment]
Hey @pswimalaweera 👋 Thank you for taking the time to raise this! Are you able to supple a working reproduction and/or debug logs (redacted as needed) so that whoever picks this up has a bit more information to go off of? Updating the title with something a bit more descriptive would also help to better categorize and triage the issue.

**Comment by stefanfreitag** [comment]
Hi @pswimalaweera ,

I tried to reproduce your issue with a minimal example.
Terraform v1.7.3 and AWS Provider v5.47.0 are used.

```shell
❯ terraform version
Terraform v1.7.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.47.0

Your version of Terraform is out of date! The latest version
is 1.8.2. You can update by downloading from https://www.terraform.io/downloads.html
```

Terraform and provider configuration are as below

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~>5.47.0"
    }
  }
  required_version = "~>1.7.3"
}

provider "aws" {
  alias  = "central"
  region = "eu-central-1"
}
```

`main.tf` is used to create a DMS source endpoint with MongoDB engine. The values in `mongodb_settings` are same as in your setup.

```hcl
resource "aws_dms_endpoint" "source" {
  endpoint_id   = "source"
  endpoint_type = "source"
  engine_name   = "mongodb"
  username      = "admin"
  password      = "password"
  server_name   = "https://test.com"
  port          = 27017
  database_name = "source"
  mongodb_settings {
    docs_to_investigate = 1000
    nesting_level = "one"
  }
}
```
`terraform apply ` was executed. After this one can use AWS CLI to describe the created endpoint

```shell
$ aws dms describe-endpoints 
{
    "Endpoints": [
        {
            "EndpointIdentifier": "source",
            "EndpointType": "SOURCE",
            "EngineName": "mongodb",
            "EngineDisplayName": "MongoDB",
            "Username": "admin",
            "ServerName": "https://test.com",
            "Port": 27017,
            "DatabaseName": "source",
            "ExtraConnectionAttributes": "authMechanism=DEFAULT;authSource=admin;authType=PASSWORD;docsToInvestigate=1000;extractDocId=false;nestingLevel=ONE;",
            "Status": "active",
            "KmsKeyId": "<redacted>",
            "EndpointArn": "<redacted>",
            "SslMode": "none",
            "MongoDbSettings": {
                "Username": "admin",
                "ServerName": "https://test.com",
                "Port": 27017,
                "DatabaseName": "source",
                "AuthType": "password",
                "AuthMechanism": "default",
                "NestingLevel": "one",
                "ExtractDocId": "false",
                "DocsToInvestigate": "1000",
                "AuthSource": "admin",
                "KmsKeyId": "<redacted>"
            }
        }
    ]
}
```

The MongoDB settings have been applied as expected.

In the AWS Management Console the relevant information is also displayed.
![image](https://github.com/hashicorp/terraform-provider-aws/assets/10981698/226f8b5c-88c9-4b48-9def-162837a6c2b4)

Please let me know, if I did something wrong/ different compared with your setup.

**Comment by justinretzolk** [comment]
Since we haven't heard back since the excelling comment above, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
