### ISSUE TITLE
[New Resource]: aws_chatbot_slack_channel_configuration

### ISSUE THREAD

**Issue by madhavvishnubhatta** [hashicorp/terraform-provider-aws#37222]
### Description

A resource to manage Slack Channel Configurations. Relates to https://github.com/hashicorp/terraform-provider-aws/issues/12304.

### Requested Resource(s) and/or Data Source(s)

* aws_chatbot_slack_channel_configuration

### Potential Terraform Configuration

```terraform
resource "aws_chatbot_slack_channel_configuration" "test" {
  slack_team_id = "ID12345"
  slack_channel_id = "CID45678"
  sns_topic_arns = ["arn1", "arn2"]
  iam_role_arn = "arn:aws:iam::123456789012:role/somerole"
  configuration_name = "test-config"
  logging_level = "ERROR"
  guardrail_policy_arns = ["arn1", "arn2"]
  user_authorization_required = true
}
```

### References

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/chatbot/index.html#cli-aws-chatbot

#12304 
#37123 

### Would you like to implement a fix?

Yes

**Comment by sparr** [comment]
Is this meant to replace or coexist with https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/chatbot_slack_channel_configuration ?

**Comment by madhavvishnubhatta** [comment]
> Is this meant to replace or coexist with https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/chatbot_slack_channel_configuration ?

Both will co-exist. The one you point to is part of the [awscc](https://github.com/hashicorp/terraform-provider-awscc) provider that is fully based on the CloudFormation schema, while this is for the [standard provider](https://github.com/hashicorp/terraform-provider-aws). See the differences [here](https://github.com/hashicorp/terraform-provider-awscc/blob/main/contributing/FAQ.md)

**Comment by xnick123** [comment]
Maybe the [Microsoft teams chatbot resource](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/chatbot_microsoft_teams_channel_configuration) could be added too

**Comment by madhavvishnubhatta** [comment]
> Maybe the [Microsoft teams chatbot resource](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/chatbot_microsoft_teams_channel_configuration) could be added too

That will be a separate resource and a separate issue, but I intend to do that too eventually.

**Comment by madhavvishnubhatta** [comment]
@johnorcutt 
I am still working on this Slack Channel Configuration resources. A bit busy this week. But if you want to contribute to the effort you might want to consider Chime or Teams related resources? :-) Or are you interested only in Slack related resources?

**Comment by claudio-vellage** [comment]
Is this still being worked on? Is there already a PR? I would like to use this too.
