### ISSUE TITLE
[Bug]: Using count attribute on aws_s3_bucket_lifecycle_configuration results in only a single lifecycle rule being created

### ISSUE THREAD

**Issue by dwilliams9329** [hashicorp/terraform-provider-aws#37241]
### Terraform Core Version

1.8.2

### AWS Provider Version

5.44.0

### Affected Resource(s)

* aws_s3_bucket_lifecycle_configuration

### Expected Behavior

A number of `aws_s3_bucket_lifecycle_configuration` resources are created matching the value of the `count` attribute.  In the case of the code snippet below, I am expecting two rules - one for 3 days, and one for 30 days.

### Actual Behavior

The terraform plan correctly matched my expectations above.  However only a single rule was created, in this case for 30 days.  The apply creates both `aws_s3_bucket_lifecycle_configuration.test[0]` and `aws_s3_bucket_lifecycle_configuration.test[1]` with a value of 30 days.  I am also seeing two entries in the statefile, both referencing 30 days.  The rule for 3 days is never created.

### Terraform Configuration Files

<pre>variable "s3_lifecycle_expiration_days" {
  description = "The number of days to retain a file in the S3 bucket."
  type        = list(number)
  default    = [3,30]
}

resource "aws_s3_bucket" "test" {
  bucket = "bucket-lifecycle-test"

  lifecycle {
    ignore_changes = [
      replication_configuration
    ]
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "test" {
  count  = length(var.s3_lifecycle_expiration_days)
  bucket = aws_s3_bucket.test[0].id

  rule {
    id     = "delete-objects-after-${var.s3_lifecycle_expiration_days[count.index]}-day(s)"
    status = "Enabled"

    filter {
      tag {
        key   = "ExpirationDays"
        value = var.s3_lifecycle_expiration_days[count.index]
      }
    }

    expiration {
      days = var.s3_lifecycle_expiration_days[count.index]
    }
  }
}</pre>

### Steps to Reproduce

1. Plan and apply using the terraform code above (changing bucket name as needed)
2. Observe the plan wanting to create two unique lifecycle rules for 3 and 30 days respectively
3. Observe the apply creating the same rule twice
4. See both indexes (0 and 1) in the statefile with the same values (30 days)

### Would you like to implement a fix?

None

**Comment by dimaman2001** [comment]
@dwilliams9329 - This is intended behavior per the documentation [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration):


`NOTE:
S3 Buckets only support a single lifecycle configuration. Declaring multiple aws_s3_bucket_lifecycle_configuration resources to the same S3 Bucket will cause a perpetual difference in configuration`

**Comment by dwilliams9329** [comment]
@dimaman2001 Thanks! We ended up doing this using a `dynamic` block and `.value` per iteration, based off the `list(number)` variable.  This keeps it as a single `aws_s3_bucket_lifecycle_configuration` resource with multiple lifecycle rules applied.
