### ISSUE TITLE
[Enhancement]: `r/aws_dynamodb_table`: Support On-Demand Throughput

### ISSUE THREAD

**Issue by jar-b** [hashicorp/terraform-provider-aws#37256]
### Description

The `CreateTable` and `UpdateTable` APIs now support configuration of on-demand throughput for tables and global secondary indexes. The `aws_dynamodb_table` resource should add corresponding arguments. Overrides can also be applied to replication

 - [x] Add `on_demand_throughput` block argument, containing `max_read_request_units` and `max_write_request_units` arguments. #37799
 - [x] Add the ability to configure the same options on global secondary indexes (ie. the same `on_demand_throughput` argument, but nested inside the `global_secondary_index` block).
 - [x] Assess whether the `import_table` and `replica` blocks can incorporate `on_demand_throughput_override` configurations.
 - [x] Add acceptance tests for both cases.
 - [ ] Update registry documentation.

### Affected Resource(s) and/or Data Source(s)

- `aws_dynamodb_table`

### Potential Terraform Configuration

```terraform
resource "aws_dynamodb_table" "example" {
  ### other configuration ###

  on_demand_throughput {
    max_read_request_units  = 1
    max_write_request_units = 1
  }

  global_secondary_index {
    on_demand_throughput {
      max_read_request_units  = 2
      max_write_request_units = 2
    }
  }
}
```

### References

- Depends on #37247
- https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html
- https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateTable.html
- [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/05/dynamodb-configurable-maximum-throughput-on-demand-tables/)
- [Blog post](https://aws.amazon.com/blogs/database/introducing-configurable-maximum-throughput-for-amazon-dynamodb-on-demand/)

### Would you like to implement a fix?

None

**Comment by nirajvbhatt** [comment]
We need this feature asap. Any insights into when will this be prioritised?

**Comment by anthonymag** [comment]
Worth noting this is in AWS's Cloud Control provider, as an alternative in the meantime:
https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/dynamodb_table#on_demand_throughput
