### ISSUE TITLE
[Bug]: InvalidParameterValue when using aws_rds_orderable_db_instance with provider version 5.37 or higher

### ISSUE THREAD

**Issue by An-Owlbear** [hashicorp/terraform-provider-aws#37258]
### Terraform Core Version

1.4.6

### AWS Provider Version

>=5.37

### Affected Resource(s)

* aws_rds_oderable_db_instance

### Expected Behavior

The data source source should be created normally like previous versions.

### Actual Behavior

On provider versions 5.37 and onwards running terraform plan with any instance of `aws_rds_orderable_db_instance` will result in an `InvalidParameterValue` error.

### Relevant Error/Panic Output Snippet

```shell
│ Error: reading RDS Orderable DB Instance Options: InvalidParameterValue: Invalid value 3412 for MaxRecords. Must be between 20 and 1000
│ 	status code: 400, request id: eda61e19-2c4a-4453-ac8d-e8f5fef4bddc
│ 
│   with data.aws_rds_orderable_db_instance.test,
│   on main.tf line 16, in data "aws_rds_orderable_db_instance" "test":
│   16: data "aws_rds_orderable_db_instance" "test" {
```

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  required_version = ">= 1.4.0"
}

provider "aws" {
  region = "eu-west-1"
}

data "aws_rds_orderable_db_instance" "test" {
  engine         = "mysql"
  engine_version = "8.0.36"
  license_model  = "general-public-license"
  storage_type   = "standard"

  preferred_instance_classes = ["db.r6.xlarge", "db.m4.large", "db.t3.small"]
}
```

### Steps to Reproduce

Run `terraform plan` with the previous config.

### Important Factoids

- I don't have the exact time this started happening but it was in the last two weeks, and I believe I was using versions later than 5.37 before that with no issues. For now I've circumvented the issue by downgrading to 5.36.
- I haven't verified every version from 5.37 onwards, but multiple it was the earliest version I could find that produced the error and multiple versions afterwards including the latest version also produce the same error.

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Related #37221
