### ISSUE TITLE
[Bug]: AWS Lambda Runtime - provided.al2023 invalid

### ISSUE THREAD

**Issue by johnsdav** [hashicorp/terraform-provider-aws#37270]
### Terraform Core Version

1.8.2

### AWS Provider Version

5.4.8

### Affected Resource(s)

* aws_lambda_function

### Expected Behavior

When creating a lambda function and setting the `runtime` attribute the value: `provided.al2023` is valid value.

### Actual Behavior

When creating a lambda function and setting the `runtime` attribute the value: `provided.al2023` is reported as invalid. 

However, this is the latest supported OS Runtime for AWS Lambda functions and is valid per AWS documentation: https://docs.aws.amazon.com/lambda/latest/dg/runtimes-provided.html

### Relevant Error/Panic Output Snippet

```shell
Error: expected runtime to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x nodejs16.x java8 java8.al2 java11 python2.7 python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 dotnet6 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2 nodejs18.x python3.10 java17 ruby3.2], got provided.al2023
```

#### Sample Terraform File

```hcl
data "aws_iam_policy_document" "assume_role" {
  statement {
    effect = "Allow"

    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }

    actions = ["sts:AssumeRole"]
  }
}

resource "aws_iam_role" "iam_for_lambda" {
  name               = "iam_for_lambda"
  assume_role_policy = data.aws_iam_policy_document.assume_role.json
}

data "archive_file" "lambda" {
  type        = "zip"
  source_file = "lambda.rust"
  output_path = "lambda_function_payload.zip"
}

resource "aws_lambda_function" "test_lambda" {
  # If the file is not in the current working directory you will need to include a
  # path.module in the filename.
  filename      = "lambda_function_payload.zip"
  function_name = "lambda_function_name"
  role          = aws_iam_role.iam_for_lambda.arn
  handler       = "rust.handler"

  source_code_hash = data.archive_file.lambda.output_base64sha256

  runtime = "provided.al2023"

  environment {
    variables = {
      foo = "bar"
    }
  }
}
```

### Steps to Reproduce

1. Define a lambda function and set the attribute `architectures` to `provided.al2023`
2. Run `plan`

### Important Factoids

Going forward the 

### References

Per AWS Documentation the major difference between OS runtimes are:

> The Amazon Linux 2023 (provided.al2023) runtime provides several advantages over Amazon Linux 2, including a smaller deployment footprint and updated versions of libraries such as glibc.

> The provided.al2023 runtime uses dnf as the package manager instead of yum, which is the default package manager in Amazon Linux 2. For more information about the differences between provided.al2023 and provided.al2, see [Introducing the Amazon Linux 2023 runtime for AWS Lambda](https://aws.amazon.com/blogs/compute/introducing-the-amazon-linux-2023-runtime-for-aws-lambda/) on the AWS Compute Blog.

### Would you like to implement a fix?

No

**Comment by stefanfreitag** [comment]
Hi @johnsdav

if you are using Terraform AWS provider version 5.4.8 then this causes the issue you are facing. The support for the AL2023 runtime was introduced in a later version.
You would need to upgrade to at least 5.26.0. [Here](https://github.com/hashicorp/terraform-provider-aws/blob/3a7abcdefd46ec67f8e4b751fb7c755c7162c69c/CHANGELOG.md#5260-november-16-2023) is a link to the changelog that mentions

> resource/aws_lambda_function: Add support for nodejs20.x and provided.al2023 runtime values (https://github.com/hashicorp/terraform-provider-aws/issues/34401)
