### ISSUE TITLE
[Enhancement]: Add AWS Resource Tagging Standard ARN reference to `aws_securityhub_standards_subscription` resource doc

### ISSUE THREAD

**Issue by acwwat** [hashicorp/terraform-provider-aws#37272]
### Description

AWS has recently added a new [AWS Resource Tagging Standard](https://aws.amazon.com/about-aws/whats-new/2024/04/aws-security-hub-resource-tagging-standard/) which can be used to identify if any of your AWS Resources are missing tag keys required by your organization. To save users from having to look up the ARN, it would be great to have the ARN for this new standard added to the list that already exist in the `aws_securityhub_standards_subscription` resource doc.

### Affected Resource(s) and/or Data Source(s)

`aws_securityhub_standards_subscription`

### Potential Terraform Configuration

```terraform
n/a
```

### References

- https://aws.amazon.com/about-aws/whats-new/2024/04/aws-security-hub-resource-tagging-standard/
- https://docs.aws.amazon.com/securityhub/latest/userguide/standards-tagging.html

### Would you like to implement a fix?

Yes

**Comment by rymancl** [comment]
@acwwat / @justinretzolk - Isn't there more that needs to be done for this new subscription to be fully implemented in the provider? This standard takes in the `requiredTagKeys` parameter, which goes in via the

**Comment by rymancl** [comment]
@acwwat / @justinretzolk - Isn't there more that needs to be done for this new subscription to be fully implemented in the provider? This standard takes in the `requiredTagKeys` parameter, which goes in via the `StandardsInput`.

https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_BatchEnableStandards.html

It seems [the provider](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/securityhub/standards_subscription.go) only allows for the standards ARN to be passed in.

**Comment by acwwat** [comment]
@rymancl You are correct. I have a separate branch in my local with the update, but forgot to follow through with opening a new issue when I was working on other issues. I'll circle back to this one shortly.

**Comment by acwwat** [comment]
I've looked into the requirements in more details and determined that adding `StandardInput` would not help set custom parameters for the security controls. The map parameter pertains to standards not security controls, and it actually just gets reverted to an empty map in the `BatchEnableStandards` response anyway since it's not in use. There's no way to pass the parameters when enabling a standard. Since the "enhancement" is not useful and the behavior would cause confusion, I won't check it in.

Meanwhile, what we need is actually #35447, specifically to have a new `aws_securityhub_security_control` resource to set custom parameters using [`UpdateSecurityControl`](https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_UpdateSecurityControl.html).

As a workaround, you could use the [`aws_securityhub_configuration_policy` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_configuration_policy#security_control_custom_parameter) which supports setting `security_control_custom_parameter`.

**Comment by rymancl** [comment]
I confirmed what you're seeing. 
Hopefully not getting too off-topic here... I find it odd you have to configure those parameters per control and not at the standard level, especially for something like tagging. Am I correct that the only way to set the required tags parameter across all controls in the standard is to explicitly list out each control and set it that way?
