### ISSUE TITLE
[Bug]: IoT Core Provisioning Template Ignores Updates to Pre-Provisioning Hook ARN

### ISSUE THREAD

**Issue by PeterBurner** [hashicorp/terraform-provider-aws#37323]
### Terraform Core Version

1.8.2

### AWS Provider Version

5.47.0

### Affected Resource(s)

* `aws_iot_provisioning_template`

### Expected Behavior

Changing the value of the `pre_provisioning_hook.target_arn` property should update the provisioning template.

### Actual Behavior

Changing the value of the `pre_provisioning_hook.target_arn` property does not update the provisioning template. It continues to contain the old ARN, which breaks functionality. Devices cannot be provisioned anymore.

### Terraform Configuration Files

```hcl
resource "aws_iam_role" "test" {
  name = "test"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Principal = {
          Service = "iot.amazonaws.com"
        }
        Action = "sts:AssumeRole"
      }
    ]
  })
}

resource "aws_iam_role_policy_attachment" "test" {
  role       = aws_iam_role.test.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSIoTThingsRegistration"
}

resource "aws_iot_provisioning_template" "test" {
  name                  = "test"
  provisioning_role_arn = aws_iam_role.test.arn
  enabled               = true

  template_body = jsonencode({
    Parameters = {
      SerialNumber = { Type = "String" }
    }

    Resources = {
      certificate = {
        Properties = {
          CertificateId = { Ref = "AWS::IoT::Certificate::Id" }
          Status        = "Active"
        }
        Type = "AWS::IoT::Certificate"
      }
    }
  })
}
```

### Steps to Reproduce

1. Deploy example
2. Add `pre_provisioning_hook { target_arn = "arn:aws:lambda:eu-central-1:000000000000:function:test" }` to `aws_iot_provisioning_template` resource
3. Deploy again
4. See that provisioning template is missing pre-provisioning hook

### Would you like to implement a fix?

No

**Comment by DanielRieske** [comment]
Hi @PeterBurner 👋, thanks for reporting this issue, I will fix this as part of the `iot` SDKv2 migration PR.
