### ISSUE TITLE
[Enhancement]: SageMaker Endpoints: add `InputAndOutput` capture options mode

### ISSUE THREAD

**Issue by jtornblad** [hashicorp/terraform-provider-aws#37330]
### Description

For SageMaker endpoints, data capture can be configured to capture the Input, Output OR both as "InputAndOutput".  Currently the provider rejects this option setting for "InputAndOutput" with the error message:

Error: expected data_capture_config.0.capture_options.0.capture_mode to be one of [Input Output], got InputAndOutput

For capture_mode, the aws_sagemaker_endpoint_configuration should accept "Input", "Output" OR "InputAndOutput" as valid values.

### Affected Resource(s) and/or Data Source(s)

aws_sagemaker_endpoint_configuration

### Potential Terraform Configuration

```terraform
resource "aws_sagemaker_endpoint_configuration" "my_endpoint_configuration" {
  name        = "my_endpoint_configuration"

  production_variants {
    variant_name           = "variant-1"
    model_name             = aws_sagemaker_model.my_model.name
    initial_instance_count = 1
    instance_type          = "ml.t2.medium"
  }
  data_capture_config {
    initial_sampling_percentage = 100
    destination_s3_uri          = "s3://my_bucket/my_path"
    capture_options {
      capture_mode = "InputAndOutput"
    }
    enable_capture = true
  }
  depends_on = [
    aws_sagemaker_model.my_model
  ]
}
```

### References

See SageMaker allowed values for capture mode in endpoint configuration at https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CaptureOption.html#sagemaker-Type-CaptureOption-CaptureMode

### Would you like to implement a fix?

Yes

**Comment by aayushsss1** [comment]
@justinretzolk @jtornblad 

It looks like this is already supported here - 

https://github.com/hashicorp/terraform-provider-aws/blob/feecd0b738afe3275a54ce2f4c8d3dcb8414014d/internal/service/sagemaker/endpoint_configuration.go#L193

and this function is being called from the `aws-sdk-go`  with the `InputAndOutput` option already defined

```
const (
	// CaptureModeInput is a CaptureMode enum value
	CaptureModeInput = "Input"

	// CaptureModeOutput is a CaptureMode enum value
	CaptureModeOutput = "Output"

	// CaptureModeInputAndOutput is a CaptureMode enum value
	CaptureModeInputAndOutput = "InputAndOutput"
)

// CaptureMode_Values returns all elements of the CaptureMode enum
func CaptureMode_Values() []string {
	return []string{
		CaptureModeInput,
		CaptureModeOutput,
		CaptureModeInputAndOutput,
	}
}
```

**Comment by CrazyFunker** [comment]
@aayushsss1 I have tried `InputAndOutput` today with the latest TF AWS provider (v5.50.0), unfortunately this only applies:
`Data capture options: Prediction request` only, without `Prediction response`.

**Comment by tyegagne** [comment]
We've found that the 'InputAndOutput' argument while [documented as supported on the AWS SDK side](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-endpointconfig-captureoption.html), it appears to throw Validation Errors in CloudTrail when supplied. The workaround we're applying with success in Terraform is documented below:

```
resource "aws_sagemaker_endpoint_configuration" "xx_config" {
  name        = "xx-endpoint-config-${var.stack-name}"
  kms_key_arn = var.kms_key_arn

  production_variants {
    variant_name           = "xx-${var.stack-name}"
    model_name             = aws_sagemaker_model.xx_model.name
    initial_instance_count = 1
    instance_type          = "ml.m5.large"
  }
  data_capture_config {
    initial_sampling_percentage = 100
    destination_s3_uri          = "s3://xx/xx}/inferences/"
    capture_options {
      capture_mode = "Input"
    }
    capture_options {
      capture_mode = "Output"
    }
    enable_capture = true
  }
  depends_on = [
    aws_sagemaker_model.xx_model
  ]
}
```

This approach of supplying 2x capture_options {} one with Input and the other with Output allows for a workaround of capture_options not accepting an array of options and 'InputAndOutput' not functioning as an argument supplied to AWS. A support ticket was opened with AWS, and the support engineer said they are opening up a documentation update with the service team.

When this capture config is supplied the config builds and endpoint is able to inherit the config with Request and Response capture.
