### ISSUE TITLE
[Enhancement]: r/aws_budgets_budget_action: Support tagging

### ISSUE THREAD

**Issue by jar-b** [hashicorp/terraform-provider-aws#37351]
### Description

AWS Budgets now supports tagging for Budget Action resources. The AWS provider should add corresponding `tags` and `tags_all` attributes. 

Note: this will map to the `ResourceTags` field on the AWS CreateBudgetInput struct.

### Affected Resource(s) and/or Data Source(s)

- `aws_budgets_budget_action`

### Potential Terraform Configuration

```terraform
resource "aws_budgets_budget_action" "example" {
  ### other configuration ###

  tags = {
    mykey = "myvalue"
  }
}
```

### References

- Depends on https://github.com/hashicorp/terraform-provider-aws/pull/37340
- Relates #37350 

### Would you like to implement a fix?

None

**Comment by DanielRieske** [comment]
Hi Jared 👋, I'll gladly pick this one up together with https://github.com/hashicorp/terraform-provider-aws/issues/37350
