### ISSUE TITLE
Interpolating name of resource causes recreation when value hasn't changed

### ISSUE THREAD

**Issue by jurajseffer** [hashicorp/terraform-provider-aws#3744]
### Terraform Version
Terraform v0.11.1
+ provider.aws v1.11.0

### Affected Resource(s)
- aws_autoscaling_group

### Terraform Configuration Files
```hcl
resource "aws_autoscaling_group" "asg" {
...
name                      = "${var.a}-${var.b}-${var.c}"
lifecycle {
    create_before_destroy = true
  }
...
}
```
changing to 
```hcl
// var.switch = false

resource "aws_autoscaling_group" "asg" {
...
name                      = "${var.switch ? aws_launch_configuration.lc.name : format("%s-%s-%s", var.a, var.b, var.c)}"
lifecycle {
    create_before_destroy = true
  }
...
}
```
### Expected Behavior
`aws_autoscaling_group` resource is updated without recreating it.

### Actual Behavior
Once we've added the true/false logic with `switch` = `false` and `aws_launch_configuration.lc` needing to be recreated, Terraform thinks the entire ASG needs to be recreated (destroy+create) even though the result of the name interpolation remains the same, i.e. concatenation of a,b and c variables. This seems to happen only once when switching from simple concat to the true/false logic with concat.

**Comment by bflad** [comment]
Hi @jurajseffer! 👋  Sorry you're running into unexpected behavior here.

Two questions:
* Does the line in the plan that says `(forces new resource)` also have `"..." => "<computed>"`?
* When you apply this, does it actually recreate the ASG? (Obviously don't test this in production 😄 )

I have a feeling that Terraform core (nothing in the AWS provider) might be confused about computing the attribute with the ternary operator and showing the unexpected difference.

**Comment by jurajseffer** [comment]
Thanks for your reply @bflad.

Plan shows this for the ASG resource when LC needs to be recreated:
```
name: "a-b-c" => "${var.switch ? aws_launch_configuration.lc.name : format(\"%s-%s-%s\", var.a, var.b, var.c)}" (forces new resource)
id: "a-b-c" => <computed> (forces new resource)
launch_configuration: "***" => "${aws_launch_configuration.lc.id}"
```

Apply fails because it does try to create the new resource first as per my lifecycle policy:
`* aws_autoscaling_group.asg: Error creating AutoScaling Group: AlreadyExists: AutoScalingGroup by this name already exists - A group with the name a-b-c already exists`

**Comment by jurajseffer** [comment]
Also once I've applied the above and it failed, TF created new launch configuration and the next plan shows it wants to update `launch_configuration` property of the ASG as expected, rather than recreating the entire ASG.

**Comment by FrenchBen** [comment]
@jurajseffer can you provide a bit more information on the `aws_launch_configuration.lc.id` switch?
It's usually desirable for the ASG to not be a "computed" value, as the ID is here. 
Did you try to push the var to a local var instead?
```
// var.switch = false

locals {
  asg_name = "${var.switch ? aws_launch_configuration.lc.name : format("%s-%s-%s", var.a, var.b, var.c)}"
}

resource "aws_autoscaling_group" "asg" {
...
name                      = "${local.asg_name}"
lifecycle {
    create_before_destroy = true
  }
...
}
```

**Comment by jurajseffer** [comment]
Hey @FrenchBen, the reason for that interpolation of LC id into ASG name is to provide rolling deploys for ASGs with "create before destroy" and Ansible local-exec to provide transition from old into a new ASG. My twist on it with the switch is because some of our existing ASGs cannot be redeployed this way and we wanted to retain backwards compatibility with existing ASGs.

I've not tried locals with it, good shout, it might be a workaround unless Terraform does lazy evaluation? I.e. it would just take the locals statement and evaluate it within the ASG context anyway.

**Comment by FrenchBen** [comment]
@jurajseffer I may be missing the bigger picture - My understanding of having `aws_launch_configuration.lc.name` is that TF crated it. If it's to re-use an existing one, wouldn't it be easier as a var?
Unsure of the lazy evaluation, although I've had better luck setting ternary operations in locals than in resources.

**Comment by jurajseffer** [comment]
The launch configuration is immutable so AWS recreates it every time we change it. We use `name_prefix` to name it. We then interpolate that LC name into the ASG name so we'd recreate ASG as well to swap all the EC2 instances. My switch deals with the name of the ASG for some ASGs that cannot be recreated so for those we expected update in place, not recreate of the ASG.

**Comment by nevins-b** [comment]
We're seeing this same behavior in terraform `v0.11.11`.
