### ISSUE TITLE
[Bug]: 5.49.0 not working with DynamoDB Local

### ISSUE THREAD

**Issue by agrzegorczyk-leonsoftware** [hashicorp/terraform-provider-aws#37463]
### Terraform Core Version

1.8.2

### AWS Provider Version

5.49.0

### Affected Resource(s)

aws_dynamodb_table

### Expected Behavior

pass terraform plan

### Actual Behavior

Stops with error because DynamoDB Local not supports tag-related operations.

### Relevant Error/Panic Output Snippet

```shell
│ Error: listing tags for DynamoDB Table (arn:aws:dynamodb:ddblocal:000000000000:table/kvstore): operation error DynamoDB: ListTagsOfResource, https response error StatusCode: 400, RequestID: eb65c688-f04c-4a0a-b6d7-b6f41e25d54a, api error UnknownOperationException: Tagging is not currently supported in DynamoDB Local.
│ 
│   with aws_dynamodb_table.kvstore,
│   on table.tf line 1, in resource "aws_dynamodb_table" "kvstore":
│    1: resource "aws_dynamodb_table" "kvstore" {
│ 
╵
```

### Terraform Configuration Files

```
provider "aws" {
  endpoints {
    dynamodb = "http://dynamodb:8000"
  }
  alias                       = "local"
  access_key                  = ""
  region                      = "us-east-1"
  secret_key                  = ""
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
}

resource "aws_dynamodb_table" "kvstore" {

  provider = aws.local

  name         = "kvstore"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "key"

  attribute {
    name = "key"
    type = "S"
  }
}
```

### Steps to Reproduce

```
docker run -it --rm --hostname=dynamodb amazon/dynamodb-local:2.4.0
terraform init
terraform plan
```

### Important Factoids

This works in 5.48.0; I didn't see anything related in 4.59.0 changelog,
but suppose this may be related with updating AWS SDK for GO to v2 for DDB:
https://github.com/hashicorp/terraform-provider-aws/pull/37288/commits/f09cd24c58b3f0a0380251bbcb5211260099cfad

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/37288.
