### ISSUE TITLE
[Bug]: SSM Document does not support the parameter option for "Reboot"

### ISSUE THREAD

**Issue by bl718w** [hashicorp/terraform-provider-aws#37473]
### Terraform Core Version

1.5.5

### AWS Provider Version

Latest

### Affected Resource(s)

The following resource is affected:
- aws_ssm_maintenance_window_task

However, the issue is in the SSM documents:
- About the AWS-RunPatchBaselineAssociation SSM document: https://docs.aws.amazon.com/systems-manager/latest/userguide/patch-manager-aws-runpatchbaselineassociation.html#patch-manager-aws-runpatchbaselineassociation-parameters-norebootoption
- About the AWS-RunPatchBaseline SSM document: https://docs.aws.amazon.com/systems-manager/latest/userguide/patch-manager-aws-runpatchbaseline.html#patch-manager-aws-runpatchbaseline-parameters-norebootoption

Terraform AWS Provider allows for the following reboot options:
- Reboot
- NoReboot
- RebootIfNeeded

### Expected Behavior

Terraform should failed during plan and apply when "Reboot" parameter is selected.  Reboot option should be removed as an option for the SSM Documents (AWS-RunPatchBaselineAssociation & AWS-RunPatchBaseline) as it is not a valid option.

### Actual Behavior

Terraform succeed when the plan and apply is deployed with the "Reboot" parameter is selected.

### Relevant Error/Panic Output Snippet

Terraform plan and apply succeeds when "Reboot" is selected and the resource is provisioned.  However, when the patch is deployed, the following error is reported by the patch:
- execution tasks: The maximum error count was exceeded. 
- task invocation: The specified parameters are incomplete or invalid.

### Terraform Configuration Files

```hcl
resource "aws_ssm_maintenance_window_task" "critical_scan_mta" {
  ...
  task_arn        = "AWS-RunPatchBaselineAssociation"
  task_type       = "RUN_COMMAND"
  ...
  task_invocation_parameters {
    run_command_parameters {
      ...
      parameter {
        name   = "AssociationId"
        values = [aws_ssm_association.critical_as[each.key].id]
      }

      parameter {
        name   = "RebootOption"
        values = ["Reboot"]
      }

      parameter {
        name   = "Operation"
        values = ["Scan"]
      }
    }
  }
}
```

### Steps to Reproduce

1. Enter "Reboot" as SSM Task parameter and plan and apply.
2. Allow the Patch to run from AWS
3. The error will show up in the patch output.

### Would you like to implement a fix?

No

**Comment by stefanfreitag** [comment]
Hi @bl718w,

I was working in the last weeks also with the AWS PatchManager and those SSM documents.

The referenced SSM documents 

* [AWS-RunPatchBaselineAssociation](https://docs.aws.amazon.com/systems-manager/latest/userguide/patch-manager-aws-runpatchbaselineassociation.html#patch-manager-aws-runpatchbaselineassociation-parameters-norebootoption)
* [AWS-RunPatchBaseline](https://docs.aws.amazon.com/systems-manager/latest/userguide/patch-manager-aws-runpatchbaseline.html#patch-manager-aws-runpatchbaseline-parameters-norebootoption)

clearly contain information on the allowed values for the reboot option. Checking the SSM documents  parameter section shows:

```json
    "RebootOption": {
      "type": "String",
      "description": "(Optional) Reboot behavior after a patch Install operation. If you choose NoReboot and patches are installed, the instance is marked as non-compliant until a subsequent reboot and scan.",
      "allowedValues": [
        "RebootIfNeeded",
        "NoReboot"
      ],
      "default": "RebootIfNeeded"
    }
```

One point to note is that _Reboot_ is not an allowed value.

On the other hand, there is the `aws_ssm_maintenance_window_task` that can trigger step functions,  lambdas and e.g run commands.  At this level one needs to be able to specify the command (by task arn)  to execute and to pass required parameters. Here an example from the official documentation, just removed a few lines not relevant to your issue.

```hcl
resource "aws_ssm_maintenance_window_task" "example" {
  task_arn        = "AWS-RunShellScript"
  task_type       = "RUN_COMMAND"
  window_id       = aws_ssm_maintenance_window.example.id
...
  targets {
    key    = "InstanceIds"
    values = [aws_instance.example.id]
  }

  task_invocation_parameters {
    run_command_parameters {
   ...
      parameter {
        name   = "commands"
        values = ["date"]
      }
    }
  }
}
```

As you can see the parameters can be passed using name (string)/ values (list of strings) pairs. 
No validation takes place here - it  is on the user to provide the proper values. In your case you could have passed also "Monday" instead of "Reboot" and would have ended in same situation as both are invalid.

If invalid values are passed - as it happened in your case - an  error message is generated. You provided it in your description:

- execution tasks: The maximum error count was exceeded. 
  One or more tasks failed during the executions, hence error count is >1. 
- task invocation: The specified parameters are incomplete or invalid.
  There was the invalid value for the `RebootOption` specified.

I hope the explanation helps a bit to understand why you ended in that situation.

**Comment by bl718w** [comment]
Can you let me know what version of the hashicorp/aws provider are you using?

Sent from my iPhone

On May 19, 2024, at 12:14 PM, Stefan Freitag ***@***.***> wrote:

﻿

Hi @bl718w<https://github.com/bl718w>,

I was working in the last weeks also with the AWS PatchManager and those SSM documents.

The referenced SSM documents

  *   AWS-RunPatchBaselineAssociation<https://docs.aws.amazon.com/systems-manager/latest/userguide/patch-manager-aws-runpatchbaselineassociation.html#patch-manager-aws-runpatchbaselineassociation-parameters-norebootoption>
  *   AWS-RunPatchBaseline<https://docs.aws.amazon.com/systems-manager/latest/userguide/patch-manager-aws-runpatchbaseline.html#patch-manager-aws-runpatchbaseline-parameters-norebootoption>

clearly contain information on the allowed values for the reboot option. Checking the SSM documents parameter section shows:

    "RebootOption": {
      "type": "String",
      "description": "(Optional) Reboot behavior after a patch Install operation. If you choose NoReboot and patches are installed, the instance is marked as non-compliant until a subsequent reboot and scan.",
      "allowedValues": [
        "RebootIfNeeded",
        "NoReboot"
      ],
      "default": "RebootIfNeeded"
    }

One point to note is that Reboot is not an allowed value.

On the other hand, there is the aws_ssm_maintenance_window_task that can trigger step functions, lambdas and e.g run commands. At this level one needs to be able to specify the command (by task arn) to execute and to pass required parameters. Here an example from the official documentation, just removed a few lines not relevant to your issue.

resource "aws_ssm_maintenance_window_task" "example" {
  task_arn        = "AWS-RunShellScript"
  task_type       = "RUN_COMMAND"
  window_id       = aws_ssm_maintenance_window.example.id
...
  targets {
    key    = "InstanceIds"
    values = [aws_instance.example.id]
  }

  task_invocation_parameters {
    run_command_parameters {
   ...
      parameter {
        name   = "commands"
        values = ["date"]
      }
    }
  }
}

As you can see the parameters can be passed using name (string)/ values (list of strings) pairs.
No validation takes place here - it is on the user to provide the proper values. In your case you could have passed also "Monday" instead of "Reboot" and would have ended in same situation as both are invalid.

If invalid values are passed - as it happened in your case - an error message is generated. You provided it in your description:

  *   execution tasks: The maximum error count was exceeded.
One or more tasks failed during the executions, hence error count is >1.
  *   task invocation: The specified parameters are incomplete or invalid.
There was the invalid value for the RebootOption specified.

I hope the explanation helps a bit to understand why you ended in that situation.

**Comment by stefanfreitag** [comment]
Sure,

my config is as below

```hcl
terraform {
  required_version = "~>1.8"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.49"
    }
  }
}
```
and `terraform version` shows

```shell
❯ terraform version
Terraform v1.8.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.49.0
```

**Comment by bl718w** [comment]
The following is my configuration when I ran across this issue:

- Terraform: terraform v1.0.5
-  Provider:  hashicorp/aws v5.40.0

If the issue has been addressed in hashicorp/aws v5.49.0, then I am good with marking this case as resolved.

Thanks.

Sent from my iPhone

On May 20, 2024, at 7:01 AM, Stefan Freitag ***@***.***> wrote:

﻿

Sure,

my config is as below

terraform {
  required_version = "~>1.8"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.49"
    }
  }
}

and terraform version shows

❯ terraform version
Terraform v1.8.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.49.0

**Comment by stefanfreitag** [comment]
Hi @bl718w,
technically it should also work with your version of the AWS provider.  There is no validation on the parameters provided as part of the run commands parameters. The first validation that takes places is when the SSM document is actually executed.

**Comment by justinretzolk** [comment]
Since it looks like there's no further action to be taken in terms of the provider, I'm going to close this issue out. Thank you both for the great discussion here!
