### ISSUE TITLE
[Docs]: AWS Redshift Serverless - Config Parameter - Parameter Key

### ISSUE THREAD

**Issue by xtinamarie** [hashicorp/terraform-provider-aws#37474]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshiftserverless_workgroup#config-parameter

### Description

According to the Terraform Registry, "require_ssl" is listed as an option for the parameter_key value. However, when attempting to generate a terraform plan for aws_redshiftserverless_workgroup, I get the following error:

`Error: expected config_parameter.0.parameter_key to be one of [datestyle enable_user_activity_logging query_group search_path max_query_execution_time], got require_ssl`

It seems that terraform does not recognize "require_ssl" as an accepted value. Is this a documentation error or is this a bug?

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
@xtinamarie What version of the AWS Terraform provider are you using? I can see that `require_ssl` is supported in the resource code, as do many other parameter keys that are not listed in your error message.

**Comment by xtinamarie** [comment]
@acwwat ah, that would explain the error. we're using an older version. I'll go ahead and mark this as solved
