### ISSUE TITLE
[Docs]: Missed information about TLSv1.3

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform-provider-aws#37502]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#origin_ssl_protocols

### Description

Amazon lists `TLSv1.3` as supported protocol: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html
![image](https://github.com/hashicorp/terraform-provider-aws/assets/139780495/3a322328-ee19-40f0-9bbf-d9693af22ae2)

But in the document it is not listed:
![image](https://github.com/hashicorp/terraform-provider-aws/assets/139780495/7c6a3d51-1ce7-4fa2-a0d8-a3747adbb7eb)

2. In this document also is not clear what is "origin" means. Is this viewer or who?

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
For reference, both the [API reference](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_OriginSslProtocols.html) and AWS Go SDK v2 code seems to have only SSLv3, TLSv1, TLSv1.1, and TLSv1.2 listed.

However, the field is supposed to be for the _minimum_ SSL/TLS protocol which is also known as the _security policy_ described in [Supported protocols and ciphers between viewers and CloudFront](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html). For example, the TLSv1.2 security policies all support TLSv1.3 in the table on this page.

Maybe it's just to make sense of the information and document it properly to avoid confusion.

**Comment by acwwat** [comment]
So there are two sub-paths along the request path that HTTPS is configurable:

1. From the viewer (client) to CloudFront - This corresponds to the `minimum_protocol_version` argument in the `viewer_certificate` block and is as described in [Supported protocols and ciphers between viewers and CloudFront](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html).
2. From CloudFront to a custom origin - This corresponds to the `origin_ssl_protocols` in the `custom_origin_config` block and is as described in [Requiring HTTPS for communication between CloudFront and your custom origin](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-https-cloudfront-to-custom-origin.html). With Terraform, you provide not a minimum SSL/TLS version but a list of SSL/TLS versions you want to support. It looks like it [TLS 1.3 is NOT supported](https://repost.aws/questions/QUzNusy9axTz2iWIyfK1q-nw/feature-cloudfront-origin-tls-v1-3) for this communication segment.

I will update the doc to provide similar description as [OriginSslProtocols](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CustomOriginConfig.html#cloudfront-Type-CustomOriginConfig-OriginSslProtocols) which includes a link to the Developer Guide. Hopefully this clarifies the argument usage a bit.

Nonetheless it's interesting that CloudFront doesn't support TLS1.3 for all scenarios by now. If I have time, I'll open a support case to inquire as I am now curious.
