### ISSUE TITLE
 [Enhancement]: Update `aws_oam_link` to support resource filtering for log groups and metric namespaces

### ISSUE THREAD

**Issue by kieran-lowe** [hashicorp/terraform-provider-aws#37515]
### Description

As of May 1st 2024, CloudWatch supports resource filtering to allow source accounts to only share a subset of metrics/logs with other accounts. It seems the API has been updated to allow configuring this via the CLI as `--link-configuration` and the API as `LinkConfiguration`.

Implementing this would allow source accounts to better control what metrics/logs are sent instead of all of them.

### Affected Resource(s) and/or Data Source(s)

* aws_oam_link 

### Potential Terraform Configuration

```terraform
resource "aws_oam_link" "example" {
  label_template  = "$AccountName"
  resource_types  = ["AWS::CloudWatch::Metric", "AWS::Logs::LogGroup"]
  sink_identifier = aws_oam_sink.test.id
  tags = {
    Env = "prod"
  }

  link_configuration {
    log_group_configuration {
      filter = "LogGroupName IN ('This-Log-Group', 'Other-Log-Group')"
    }

    metric_configuration {
      filter = "Namespace IN ('AWS/EC2', 'AWS/ELB', 'AWS/S3')"
    }
  }
}
```

### References

* Blog Post: <https://aws.amazon.com/about-aws/whats-new/2024/05/amazon-cloudwatch-filtering-cross-account-observability/>
* AWS Docs: <https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Unified-Cross-Account-Setup.html#Unified-Cross-Account-SetupSource-SingleURL>
* AWS CLI Docs: <https://awscli.amazonaws.com/v2/documentation/api/latest/reference/oam/create-link.html>
* AWS API Docs: <https://docs.aws.amazon.com/OAM/latest/APIReference/API_CreateLink.html>
  * LinkConfiguration: <https://docs.aws.amazon.com/OAM/latest/APIReference/API_LinkConfiguration.html>
    * LogGroupConfiguration: <https://docs.aws.amazon.com/OAM/latest/APIReference/API_LogGroupConfiguration.html>
    * MetricConfiguration: <https://docs.aws.amazon.com/OAM/latest/APIReference/API_MetricConfiguration.html>  

### Would you like to implement a fix?

No

**Comment by sp055201** [comment]
[acwwat](https://github.com/acwwat) [ewbankkit](https://github.com/ewbankkit)

resource "aws_oam_link" "source_link" {
  provider        = aws.source
  sink_identifier = aws_oam_sink.central_logging_sink.id
  label_template  = var.account_label
  resource_types  = var.allowed_resource_types
  depends_on      = [aws_oam_sink_policy.central_logging_sink_policy]
  link_configuration {
    log_group_configuration {
      filter = "LogGroupName LIKE '/aws/rds/%'"
    }
    metric_configuration {
      filter = "Namespace = 'AWS/RDS'"
    }
  }
}


Getting error for link configuration.

╷
│ Error: Unsupported block type
│ 
│   on modules/central-logging/main.tf line 33, in resource "aws_oam_link" "source_link":
│   33:   link_configuration {
│ 
│ Blocks of type "link_configuration" are not expected here.

**Comment by kieran-lowe** [comment]
> [acwwat](https://github.com/acwwat) [ewbankkit](https://github.com/ewbankkit)
> 
> 
> 
> resource "aws_oam_link" "source_link" {
> 
>   provider        = aws.source
> 
>   sink_identifier = aws_oam_sink.central_logging_sink.id
> 
>   label_template  = var.account_label
> 
>   resource_types  = var.allowed_resource_types
> 
>   depends_on      = [aws_oam_sink_policy.central_logging_sink_policy]
> 
>   link_configuration {
> 
>     log_group_configuration {
> 
>       filter = "LogGroupName LIKE '/aws/rds/%'"
> 
>     }
> 
>     metric_configuration {
> 
>       filter = "Namespace = 'AWS/RDS'"
> 
>     }
> 
>   }
> 
> }
> 
> 
> 
> 
> 
> Getting error for link configuration.
> 
> 
> 
> ╷
> 
> │ Error: Unsupported block type
> 
> │ 
> 
> │   on modules/central-logging/main.tf line 33, in resource "aws_oam_link" "source_link":
> 
> │   33:   link_configuration {
> 
> │ 
> 
> │ Blocks of type "link_configuration" are not expected here.

I don't think the v5.58 version of the provider has been released yet.
