### ISSUE TITLE
[Bug]: `aws_cloudtrail` always shows changes due to switching `insight_type` values

### ISSUE THREAD

**Issue by snarky** [hashicorp/terraform-provider-aws#37525]
### Terraform Core Version

1.8.3

### AWS Provider Version

5.49.0

### Affected Resource(s)

* aws_cloudtrail

### Expected Behavior

Terraform should recognize that there are no actual changes in the `insight_selector` blocks and should not show any updates in the execution plan.

### Actual Behavior

Terraform shows an in-place update with the `insight_type` values switching:

### Relevant Error/Panic Output Snippet

```shell
~ insight_selector {
    ~ insight_type = "ApiErrorRateInsight" -> "ApiCallRateInsight"
}
~ insight_selector {
    ~ insight_type = "ApiCallRateInsight" -> "ApiErrorRateInsight"
}
```

### Terraform Configuration Files

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail

### Steps to Reproduce

Define an `aws_cloudtrail` resource with `insight_selector` blocks:

``` hcl
resource "aws_cloudtrail" "cloudtrail" {
  name = "XXX"

  insight_selector {
    insight_type = "ApiErrorRateInsight"
  }

  insight_selector {
    insight_type = "ApiCallRateInsight"
  }
}
```
Run `terraform apply` twice.

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
Looks like the order in the AWS API response is not deterministic - sometimes the order is OK, sometimes it's not. In any case, it makes sense to make the argument unordered using a `Set` as a catch-all.
