### ISSUE TITLE
[Docs]: Error: Value for unconfigurable attribute

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform-provider-aws#37541]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/5.49.0/docs/resources/eip#argument-reference

### Description

```
╷
│ Error: Value for unconfigurable attribute
│
│   with aws_eip.manage-cluster,
│   on ec2-static-instances.tf line 367, in resource "aws_eip" "manage-cluster":
│  367:   domain   = "vpc"
│
│ Can't configure a value for "domain": its value will be decided automatically based on
│ the result of applying this configuration.
```

Terraform configuration:
```tf
resource "aws_eip" "manage-cluster" {
  domain   = "vpc"
  instance = aws_instance.res-13.id
}
```

If this value is not configurable, then it should be marked somehow.

![image](https://github.com/hashicorp/terraform-provider-aws/assets/139780495/67d0c662-2103-46df-95e6-2a02c91f97d1)

The examples should be fixed as well:
![image](https://github.com/hashicorp/terraform-provider-aws/assets/139780495/e906bcc3-f64a-4a65-aa14-046fce500f0a)

### Would you like to implement a fix?

None

**Comment by aristosvo** [comment]
Hi @EugenKon 👋🏽 

Which version of the provider are you using? It seems `4.x` only had `domain` as an attribute (https://registry.terraform.io/providers/hashicorp/aws/4.67.0/docs/resources/eip)

**Comment by EugenKon** [comment]
Yeah, for this particular project it is 4.67.

**Comment by aristosvo** [comment]
Then this is expected behavior, see the docs.

I think this issue can be closed, unless there is a different reason to keep it open.
