### ISSUE TITLE
[Bug]: Data displayed in invalid format

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform-provider-aws#37544]
### Terraform Core Version

v1.8.2

### AWS Provider Version

v4.67.0

### Affected Resource(s)

* aws_acm_certificate

### Expected Behavior

It should be shown as set, and not as an array:

### Actual Behavior

```tf
  # aws_acm_certificate.dns-url-redirects will be created
  + resource "aws_acm_certificate" "dns-url-redirects" {
      + arn                       = (known after apply)
      + domain_name               = "xxx.com"
      + domain_validation_options = [
          + {
              + domain_name           = "*.xxx.com"
              + resource_record_name  = (known after apply)
              + resource_record_type  = (known after apply)
              + resource_record_value = (known after apply)
            },
          + {
              + domain_name           = "xxx.gr"
              + resource_record_name  = (known after apply)
              + resource_record_type  = (known after apply)
              + resource_record_value = (known after apply)
            },
          + {
              + domain_name           = "xxx.uk"
              + resource_record_name  = (known after apply)
              + resource_record_type  = (known after apply)
              + resource_record_value = (known after apply)
            },
          + {
              + domain_name           = "xxx.com"
              + resource_record_name  = (known after apply)
              + resource_record_type  = (known after apply)
              + resource_record_value = (known after apply)
            },
        ]
      + id                        = (known after apply)
      + key_algorithm             = (known after apply)
      + not_after                 = (known after apply)
      + not_before                = (known after apply)
      + pending_renewal           = (known after apply)
...
```

If I try to access to it by index `aws_acm_certificate.dns-url-redirects.domain_validation_options[0].resource_record_name` I get the error:
```
│ Error: Invalid index
│
│   on company-redirects.tf line 248, in resource "aws_route53_record" "validation":
│  248:   records = ["${lookup(aws_acm_certificate.dns-url-redirects.domain_validation_options[count.index], "resource_record_value")}"]
│     ├────────────────
│     │ aws_acm_certificate.dns-url-redirects.domain_validation_options is set of object with 4 elements
│     │ count.index is 0
│
│ Elements of a set are identified only by their value and don't have any separate index or key
│ to select with, so it's only possible to perform operations across all elements of the set.
```

Documentation also says that it is the set: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate#domain_validation_options
![image](https://github.com/hashicorp/terraform-provider-aws/assets/139780495/b1850468-ce03-4f51-a24c-313f798a61c2)

### Terraform Configuration Files

I am trying to access it like described here:https://github.com/azavea/terraform-aws-acm-certificate/issues/3#issuecomment-454524135

```tf

resource "aws_route53_record" "validation" {
  provider = "aws.route53_account"
  count    = "${length(var.subject_alternative_names) + 1}"

  name    = "${lookup(aws_acm_certificate.default.domain_validation_options[count.index], "resource_record_name")}"
  type    = "${lookup(aws_acm_certificate.default.domain_validation_options[count.index], "resource_record_type")}"
  zone_id = "${data.aws_route53_zone.selected[count.index].id}"
  records = ["${lookup(aws_acm_certificate.default.domain_validation_options[count.index], "resource_record_value")}"]
  ttl     = "${var.validation_record_ttl}"
}
```

### Steps to Reproduce

Run `terraform plan` for the configuration above.

### Would you like to implement a fix?

None

**Comment by aristosvo** [comment]
Hi @EugenKon!

I think that the issue you are facing is due to this fact, which can be found [here in the docs](https://docs.aws.amazon.com/acm/latest/userguide/dns-validation.html):
> This illustrates that for a wild-card domain, such as *.example.com, the strings created by ACM are the same as those created for its base domain, example.com. 

*.xxx.com and xxx.com deliver the same validation record and name, resulting in the above error. As the domain name differs, it is still an unique entry in the array/set.

**Comment by EugenKon** [comment]
@aristosvo Sorry, I copied a wrong error message. I fixed that. Thank you for pointing that out.

**Comment by aristosvo** [comment]
@EugenKon I added an example in my answer, that might work for you?

**Comment by EugenKon** [comment]
@aristosvo Thank you for the example. I resolved it exactly in this way. But we should skip wildcard domains instead. Eg. if we have `xxx.com, *.xxx.com, yyy.com`. Your example will skip `yyy.com` domain.

Once again, thank you for your example. But here I complain that `terraform plan` shows wrong structure: [] instead of {}. (array instead of set).

**Comment by aristosvo** [comment]
I believe the display of sets in Terraform is as an array, but without duplicates: https://developer.hashicorp.com/terraform/language/functions/toset shows this as well in the examples.

I think that is defined in Terraform, not in the Terraform Provider itself.

**Comment by EugenKon** [comment]
@aristosvo Do you want me to open this PR in the other repo?

**Comment by aristosvo** [comment]
Sure, go ahead if you feel like it 👍

**Comment by EugenKon** [comment]
The issue moved to a different repo
