### ISSUE TITLE
Create ASG EC2 instance with delay of 5 mins

### ISSUE THREAD

**Issue by pb9743** [hashicorp/terraform-provider-aws#37567]
### Description

Below is my code to create delay of 5 mins before launching new EC2 instance from ASG after existing instance stopped manually from EC2 console (testing purpose). But new EC2 instance is launching before 5 mins.
Requirement is to create an Auto Scaling Group (ASG) where new EC2 instances start only after an existing server becomes stopped for 5 minutes. How to achieve it using AWS Terraform.

```hcl
resource "aws_cloudwatch_metric_alarm" "stopped_instances_alarm" {
  alarm_name          = "StoppedInstancesAlarm"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = 1 # 
  metric_name         = "StoppedInstances"
  namespace           = "Custom/EC2"
  period              = 300 # 
  statistic           = "Sum"
  threshold           = 1 
  alarm_description   = "Alarm triggered when number of stopped instances exceeds threshold within 5 minutes"
}
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @pb9743 👋 Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. To maintain that, we ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). With that in mind, I'm going to close this issue.
