### ISSUE TITLE
[Bug]: aws_ssm_patch_group can not contain multiple patch baselines

### ISSUE THREAD

**Issue by tknisch** [hashicorp/terraform-provider-aws#37622]
### Terraform Core Version

1.7.5

### AWS Provider Version

5.50.0

### Affected Resource(s)

aws_ssm_patch_group

### Expected Behavior

If using the `aws_ssm_patch_group` with a for_each in version 5.49.0 and before multiple baselines were added to the patchgroup:

![image](https://github.com/hashicorp/terraform-provider-aws/assets/129748854/15b8356f-42e8-4244-8201-b8d9f7849a21)

### Actual Behavior

With version 5.50.0 only one baseline is assigned to the patch group:

![image](https://github.com/hashicorp/terraform-provider-aws/assets/129748854/024cfec5-082c-4f80-ba6f-69d06514ff16)

### Terraform Configuration Files

```
locals {
  patchgroup_name = "my-Default-PatchGroup"
  os = [
    "AMAZON_LINUX",
    "AMAZON_LINUX_2",
    "AMAZON_LINUX_2022",
    "AMAZON_LINUX_2023",
    "UBUNTU",
    "DEBIAN",
    "RASPBIAN",
    "REDHAT_ENTERPRISE_LINUX",
    "CENTOS",
    "ORACLE_LINUX",
    "SUSE",
    "ROCKY_LINUX",
    "ALMA_LINUX",
    "WINDOWS"
  ]
}


data "aws_ssm_patch_baseline" "all" {
  for_each         = toset(local.os)
  operating_system = each.value
  owner            = "AWS"
  default_baseline = true
}


resource "aws_ssm_patch_group" "my_patchgroup" {
  for_each    = data.aws_ssm_patch_baseline.all
  baseline_id = each.value.id
  patch_group = local.patchgroup_name
}
```

### Steps to Reproduce

Run code with aws provider version 5.49.0 or before and then upgrade to 5.50.0 and apply 

### Debug Output

![image](https://github.com/hashicorp/terraform-provider-aws/assets/129748854/53aa5474-eb5d-4967-b1b1-652366837e4b)

### References

https://github.com/hashicorp/terraform-provider-aws/pull/37481

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
The bug is in the `aws_ssm_patch_baseline` data source's handling of the `default_baseline` argument.
We will fix for this week's release.
