### ISSUE TITLE
[New Resource]: Add support for Grafana Service Account and Token

### ISSUE THREAD

**Issue by gingersnapz** [hashicorp/terraform-provider-aws#37645]
### Description

With the 10.4 version release for AWS Managed Grafana, new APIs were introduced to manage service accounts and service account tokens.

### Requested Resource(s) and/or Data Source(s)

aws_grafana_workspace_service_account
aws_grafana_workspace_service_account_token

### Potential Terraform Configuration

```terraform
resource "aws_grafana_workspace_service_account" "example" {
  grafana_role_name  = "ADMIN"
  name               = "myAdmin"
  workspace_id       = "grafana_workspace_id"
}

resource "aws_grafana_workspace_service_account_token" "tkn" {
  name               = "admin_token_a"
  service_account_id = aws_grafana_workspace_service_account.example.id
  seconds_to_live    = 3600
  workspace_id       = "grafana_workspace_id"
}
```

### References

https://docs.aws.amazon.com/grafana/latest/APIReference/API_Operations.html
https://aws.amazon.com/about-aws/whats-new/2024/05/amazon-managed-grafana-supports-version-10-4/
https://docs.aws.amazon.com/sdk-for-go/api/service/managedgrafana/

### Would you like to implement a fix?

No

**Comment by bonclay7** [comment]
Interested to take this one

**Comment by aristosvo** [comment]
@bonclay7 did you already look at [Go SDK v2 for the Grafana Service](https://github.com/hashicorp/terraform-provider-aws/issues/36185)?

**Comment by bonclay7** [comment]
@aristosvo Thanks for this. I was going to implement only the new resources in v2
