### ISSUE TITLE
[New Service]: AWS Backup Restore Testing

### ISSUE THREAD

**Issue by LozanoMatheus** [hashicorp/terraform-provider-aws#37662]
### Description

On Nov 27 - 2023, [AWS announced the AWS Backup restore testing](https://aws.amazon.com/about-aws/whats-new/2023/11/aws-backup-restore-testing/). This can be used to automate the DR testing based on the AWS Backups. They made [a blog post](https://aws.amazon.com/blogs/aws/automatic-restore-testing-and-validation-is-now-available-in-aws-backup/) showing how it works.

### Resource

* [aws_backup_restore_testing_plan](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/backup/create-restore-testing-plan.html)
* [aws_backup_restore_testing_selection](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/backup/create-restore-testing-selection.html)

### Data

* [aws_backup_restore_testing_plan](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/backup/get-restore-testing-plan.html)
* [aws_backup_restore_testing_selection](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/backup/get-restore-testing-selection.html)
* [aws_backup_restore_testing_plans](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/backup/list-restore-testing-plans.html)
* [aws_backup_restore_testing_selections](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/backup/list-restore-testing-selections.html)

### Potential Terraform Configuration

```terraform
## Resource

resource "aws_backup_restore_testing_selection" "main" {
  iam_role_arn              = aws_iam_role.main.arn
  protected_resource_arns   = ["*"]
  restore_testing_plan_name = aws_backup_restore_testing_plan.main.name
  validation_window_hours   = 0
  name                      = "test" ## Must contain from 1 to 50 alphanumeric characters or underscores
  protected_resource_type   = "RDS"    ## available options: https://docs.aws.amazon.com/aws-backup/latest/devguide/API_RestoreTestingSelectionForCreate.html#Backup-Type-RestoreTestingSelectionForCreate-ProtectedResourceType
  restore_metadata_overrides {         ## available options: https://docs.aws.amazon.com/aws-backup/latest/devguide/restore-testing-inferred-metadata.html
    availability_zone  = "eu-west-1a"
    availability_zones = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
    option_group_name  = "default:mysql-8-0"
  }
}

resource "aws_backup_restore_testing_plan" "main" {
  name = "test" ## Must contain from 1 to 50 alphanumeric characters or underscores
  recovery_point_selection {
    algorithm             = "LATEST_WITHIN_WINDOW"     ## available options: https://docs.aws.amazon.com/aws-backup/latest/devguide/API_RestoreTestingRecoveryPointSelection.html#Backup-Type-RestoreTestingRecoveryPointSelection-Algorithm
    recovery_point_types  = ["CONTINUOUS", "SNAPSHOT"] ## available options: https://docs.aws.amazon.com/aws-backup/latest/devguide/API_RestoreTestingRecoveryPointSelection.html#Backup-Type-RestoreTestingRecoveryPointSelection-RecoveryPointTypes
    exclude_vaults        = []
    include_vaults        = ["*"]
    selection_window_days = 7
  }
  schedule_expression          = "cron(0 12 * * ? *)"
  schedule_expression_timezone = "UTC"
  start_window_hours           = 0
}

## Data

data "aws_backup_restore_testing_plan" "main" {
  name = "test"
}

data "aws_backup_restore_testing_selection" "main" {
  name                      = "test"
  restore_testing_plan_name = aws_backup_restore_testing_plan.main.name
}

data "aws_backup_restore_testing_plans" "main" {}

data "aws_backup_restore_testing_selections" "main" {
  restore_testing_plan_name = aws_backup_restore_testing_plan.main.name
}
```

### AWS Go SDK v2

Create:
* [CreateRestoreTestingPlan](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/backup#Client.CreateRestoreTestingPlan)
* [CreateRestoreTestingSelection](https://github.com/aws/aws-sdk-go-v2/blob/service/backup/v1.34.5/service/backup/api_op_CreateRestoreTestingSelection.go#L35)

Delete:
* [DeleteRestoreTestingPlan](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/backup#Client.DeleteRestoreTestingPlan)
* [DeleteRestoreTestingSelection](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/backup#Client.DeleteRestoreTestingSelection)

Get:
* [GetRestoreTestingInferredMetadata](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/backup#Client.GetRestoreTestingInferredMetadata)
* [GetRestoreTestingPlan](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/backup#Client.GetRestoreTestingPlan)
* [GetRestoreTestingSelection](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/backup#Client.GetRestoreTestingSelection)

List:
* [ListRestoreTestingPlans](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/backup#Client.ListRestoreTestingPlans)
* [ListRestoreTestingSelections](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/backup#Client.ListRestoreTestingSelections)

Update:
* [UpdateRestoreTestingPlan](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/backup#Client.UpdateRestoreTestingPlan)
* [UpdateRestoreTestingSelection](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/backup#Client.UpdateRestoreTestingSelection)

### AWS CLI examples

AWS CLI version `2.15.56`.

Ordered by execution, like create, get, list, update, and delete.

Create:

* CreateRestoreTestingPlan

```bash
aws backup \
    create-restore-testing-plan \
    --restore-testing-plan 'RecoveryPointSelection={Algorithm=LATEST_WITHIN_WINDOW,ExcludeVaults=[],IncludeVaults=[*],RecoveryPointTypes=["SNAPSHOT","CONTINUOUS"],SelectionWindowDays=7},RestoreTestingPlanName="test001",ScheduleExpression="cron(30 0 ? * * *)",ScheduleExpressionTimezone="Europe/Amsterdam",StartWindowHours=8'
```

* CreateRestoreTestingSelection

```bash
aws backup \
    create-restore-testing-selection \
    --restore-testing-plan-name "test001" \
    --restore-testing-selection 'IamRoleArn="arn:aws:iam::<MY_AWS_ACCOUNT_ID>:role/<IAM_ROLE_NAME>",ProtectedResourceArns='["*"]',ProtectedResourceType="RDS",RestoreMetadataOverrides={AvailabilityZones="[\"eu-west-1a\",\"eu-west-1b\",\"eu-west-1c\"]"},RestoreTestingSelectionName="test001",ValidationWindowHours=0'
```

Get:

* GetRestoreTestingPlan

```bash
aws backup \
    get-restore-testing-plan \
    --restore-testing-plan-name "test001"
```

* GetRestoreTestingSelection

```bash
aws backup \
    get-restore-testing-selection \
    --restore-testing-plan-name "test001" \
    --restore-testing-selection-name "test001"
```

List:

* ListRestoreTestingPlans

```bash
aws backup \
    list-restore-testing-plans
```

* ListRestoreTestingSelections

```bash
aws backup \
    list-restore-testing-selections \
    --restore-testing-plan-name "test001"
```

Update:

* UpdateRestoreTestingPlan

```bash
aws backup \
    update-restore-testing-plan \
    --restore-testing-plan-name "test001" \
    --restore-testing-plan 'RecoveryPointSelection={Algorithm=LATEST_WITHIN_WINDOW,ExcludeVaults=[],IncludeVaults=[*],RecoveryPointTypes=["SNAPSHOT"],SelectionWindowDays=7},ScheduleExpression="cron(30 0 ? * * *)",ScheduleExpressionTimezone="UTC",StartWindowHours=1'

# --restore-testing-plan-name ## The name of the restore testing plan to update
# --restore-testing-plan      ## New values you want to update
```

* UpdateRestoreTestingSelection

```bash
aws backup \
    update-restore-testing-selection \
    --restore-testing-plan-name "test001" \
    --restore-testing-selection-name "test001" \
    --restore-testing-selection 'IamRoleArn="arn:aws:iam::<MY_AWS_ACCOUNT_ID>:role/<IAM_ROLE_NAME>",ProtectedResourceArns='["*"]',RestoreMetadataOverrides={AvailabilityZones="[\"eu-west-1a\"]",optionGroupName="default:mysql-8-0"},ValidationWindowHours=3'

# --restore-testing-plan-name       ## The name of the restore-testing plan
# --restore-testing-selection-name  ## The name of the restore testing selection to update 
# --restore-testing-selection       ## New values you want to update
```

Delete:

* DeleteRestoreTestingSelection

This needs to be deleted first, otherwise, you'll get the error `An error occurred (InvalidRequestException) when calling the DeleteRestoreTestingPlan operation: Related restore testing selections must be deleted prior to deleting restore testing plan [test001].`

```bash
aws backup \
    delete-restore-testing-selection \
    --restore-testing-plan-name "test001" \
    --restore-testing-selection-name "test001"
```

* DeleteRestoreTestingPlan

```bash
aws backup \
    delete-restore-testing-plan \
    --restore-testing-plan-name "test001" \
```

### Would you like to implement a fix?

No

**Comment by LozanoMatheus** [comment]
Duplicated with #34699. PR == #37039.

**Comment by ewbankkit** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/37039.
