### ISSUE TITLE
[New Data Source]: DataSource for aws_transfer_connector

### ISSUE THREAD

**Issue by adv4000** [hashicorp/terraform-provider-aws#37675]
### Description

I would like to have a Data Source for resource `aws_transfer_connector` which  can give information about **ServiceManagedEgressIpAddresses**

### Requested Resource(s) and/or Data Source(s)

* aws_transfer_connector

### Potential Terraform Configuration

```terraform
data "aws_transfer_connector" "this" {
  connector_id = "c-xxxxxxxxxxxxxx"
}
```

### References

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/transfer/describe-connector.html

### Would you like to implement a fix?

No

**Comment by aristosvo** [comment]
Depends on #37548
