### ISSUE TITLE
[Bug]: aws_cloudwatch_event_rule doesn't expect state argument anymore (ENABLED or DISABLED values)

### ISSUE THREAD

**Issue by riankrishandi** [hashicorp/terraform-provider-aws#37679]
### Terraform Core Version

0.13.7

### AWS Provider Version

x.y.z

### Affected Resource(s)

aws_cloudwatch_event_rule

### Expected Behavior

terraform apply should be applied successful

### Actual Behavior

terraform apply failed and returned an error that it doesn't accept `state` argument. error log is shared below

### Relevant Error/Panic Output Snippet

```shell
Error: Unsupported argument

  on rule.tf line 5, in resource "aws_cloudwatch_event_rule" "this":
   5:   state               = local.rule_state

An argument named "state" is not expected here.
```

### Terraform Configuration Files

```
resource "aws_cloudwatch_event_rule" "this" {
  name                = "eventbridge_scheduler"
  description         = "eventbridge_scheduler"
  schedule_expression = "cron(0 2 * * ? *)"
  state               = local.rule_state
}
```

### Steps to Reproduce

provision a resource of eventbridge rule with config as above

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @riankrishandi 👋 Thank you for taking the time to raise this! Can you confirm what version of the AWS Provider you're using? That argument appears to have been [added in version `5.27.0`](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#5270-november-27-2023).

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
