### ISSUE TITLE
[New Resource]: AWS Opensearch Index

### ISSUE THREAD

**Issue by vicotrbb** [hashicorp/terraform-provider-aws#37729]
### Description

I would like to have a resource to create AWS opensearch (Serverless) indexes.

### Requested Resource(s) and/or Data Source(s)

aws_opensearchserverless_index

### Would you like to implement a fix?

No

**Comment by acwwat** [comment]
You can use the [OpenSearch Provider](https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs) to create indices in your OpenSearch Serverless domain today. Here is an example for creating an index for Bedrock knowledge base. However, you must use v2.2.0 of the provider for now, as [this issue](https://github.com/opensearch-project/terraform-provider-opensearch/issues/179) causes authentication issue with OSS domains.

```terraform
provider "opensearch" {
  url         = aws_opensearchserverless_collection.forex_kb.collection_endpoint
  healthcheck = false
}

resource "opensearch_index" "forex_kb" {
  name                           = "bedrock-knowledge-base-default-index"
  number_of_shards               = "2"
  number_of_replicas             = "0"
  index_knn                      = true
  index_knn_algo_param_ef_search = "512"
  mappings                       = <<-EOF
    {
      "properties": {
        "bedrock-knowledge-base-default-vector": {
          "type": "knn_vector",
          "dimension": 1536,
          "method": {
            "name": "hnsw",
            "engine": "faiss",
            "parameters": {
              "m": 16,
              "ef_construction": 512
            },
            "space_type": "l2"
          }
        },
        "AMAZON_BEDROCK_METADATA": {
          "type": "text",
          "index": "false"
        },
        "AMAZON_BEDROCK_TEXT_CHUNK": {
          "type": "text",
          "index": "true"
        }
      }
    }
  EOF
  force_destroy                  = true
  depends_on                     = [aws_opensearchserverless_collection.forex_kb]
}
```

**Comment by abriko** [comment]
> @vicotrbb You can use the [OpenSearch Provider](https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs) to create indices in your OpenSearch Serverless domain today. Here is an example for creating an index for Bedrock knowledge base. However, you must use v2.2.0 of the provider for now, as [this issue](https://github.com/opensearch-project/terraform-provider-opensearch/issues/179) causes authentication issue with OSS domains.
> 
> ```hcl
> provider "opensearch" {
>   url         = aws_opensearchserverless_collection.forex_kb.collection_endpoint
>   healthcheck = false
> }
> 
> resource "opensearch_index" "forex_kb" {
>   name                           = "bedrock-knowledge-base-default-index"
>   number_of_shards               = "2"
>   number_of_replicas             = "0"
>   index_knn                      = true
>   index_knn_algo_param_ef_search = "512"
>   mappings                       = <<-EOF
>     {
>       "properties": {
>         "bedrock-knowledge-base-default-vector": {
>           "type": "knn_vector",
>           "dimension": 1536,
>           "method": {
>             "name": "hnsw",
>             "engine": "faiss",
>             "parameters": {
>               "m": 16,
>               "ef_construction": 512
>             },
>             "space_type": "l2"
>           }
>         },
>         "AMAZON_BEDROCK_METADATA": {
>           "type": "text",
>           "index": "false"
>         },
>         "AMAZON_BEDROCK_TEXT_CHUNK": {
>           "type": "text",
>           "index": "true"
>         }
>       }
>     }
>   EOF
>   force_destroy                  = true
>   depends_on                     = [aws_opensearchserverless_collection.forex_kb]
> }
> ```

Thanks @acwwat, it's can work.
