### ISSUE TITLE
[Enhancement]: Add tags to `aws_cur_report_definition` resource and data source

### ISSUE THREAD

**Issue by azbpa** [hashicorp/terraform-provider-aws#37749]
### Description

Resource and data source for `aws_cur_report_definition` are missing the attribute for setting/getting `tags`. Also `default_tags` from provider definition is not applied.

### Affected Resource(s) and/or Data Source(s)

* Resource: `aws_cur_report_definition`: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cur_report_definition
* Data Source: `aws_cur_report_definition`: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/cur_report_definition

### References

- `PutReportDefinition`: https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_cur_PutReportDefinition.html
- `TagResource`: https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_cur_TagResource.html
- `UntagResource`: https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_cur_UntagResource.html

### Would you like to implement a fix?

No

**Comment by acwwat** [comment]
This has already been addressed by #37135 and is available v5.53.0. I think this issue can be closed.
