### ISSUE TITLE
DynamoDB backup functionality?

### ISSUE THREAD

**Issue by bmacauley** [hashicorp/terraform-provider-aws#3775]
Can we add the on demand DynamoDB backup/restore functionality to the AWS provider?
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/BackupRestore.html

I assume this would require it's own resource

**Comment by bflad** [comment]
Hi @bmacauley! 👋  Thanks for submitting this request. You might want to check out #2572 and let us know your thoughts here (at least concerning backups).

**Comment by seppi91** [comment]
Hi,
I think the implementation of the fresh released PITR (Point-In-Time-Recovery) functionality would be an acceptable backup solution for most users.

Source:
https://aws.amazon.com/de/blogs/aws/new-amazon-dynamodb-continuous-backups-and-point-in-time-recovery-pitr/

**Comment by rabbbit** [comment]
+1, would be awesome.

**Comment by akshaybadekar29** [comment]
+1

**Comment by bflad** [comment]
Support for DynamoDB point in time recovery was merged in via #4063 and will release with v1.17.0 of the AWS provider, likely in about two days.

**Comment by brunogf** [comment]
Hi, any news about this issue? 
It would be really useful.
