### ISSUE TITLE
[Bug]: Ambigious terraform plan output for tls_private_key resource

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform-provider-aws#37761]
### Terraform Core Version

v1.8.4

### AWS Provider Version

v5.51.1

### Affected Resource(s)

* tls_private_key

### Expected Behavior

I do not expect to see `rsa_bits` because I used `algorithm = "ED25519"` configuration option. These are two different ciphers.

### Actual Behavior

![image](https://github.com/hashicorp/terraform-provider-aws/assets/139780495/cd6dc0f1-e4d6-4111-b5ef-e04d765ef45d)

### Terraform Configuration Files

```tf
resource "tls_private_key" "pk" {
  algorithm = "ED25519"
}
```

### Steps to Reproduce

1. `terraform plan`

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hi @EugenKon 👋 It looks like you were attempting to report an issue with the TLS provider. The repository for that provider may be found at [hashicorp/terraform-provider-tls](https://github.com/hashicorp/terraform-provider-tls). With that in mind, I'm going to close this issue.
