### ISSUE TITLE
[Bug]: Error deleting Route53 Record. operation error. https response error StatusCode: 400 Tried to delete resource record set but it was not found

### ISSUE THREAD

**Issue by el-chazmo** [hashicorp/terraform-provider-aws#37806]
### Terraform Core Version

1.8.4

### AWS Provider Version

5.52

### Affected Resource(s)

aws_route53_record
aws_route53_zone

### Expected Behavior

When performing terraform destroy - aws_route53 cname record is removed first time.

### Actual Behavior

terraform destroy fails first time
│ Error: deleting Route53 Record  operation error Route 53: ChangeResourceRecordSets, https response error StatusCode: 400, RequestID:xx-xx-xx, InvalidChangeBatch: [Tried to delete resource record set [name='xxxxx.', type='CNAME'] but it was not found]

terraform destroy (2nd time) succeeds

### Terraform Configuration Files

resource "aws_route53_record" "setup" {
  zone_id = local.zoneid
  name    = "example.network.name"
  type    = "A"
  ttl     = 300
  records = ["127.0.0.1"]
}

### Steps to Reproduce

install hashicorp/aws latest version

NOTE: <5.51 causes no errors. Error only seen >= 5.51

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@el-chazmo Thanks for raising this issue.
You example Terraform configuration above shows an `aws_route53_record` of type **A** but the error message is about a **CNAME** record -- could you add the configuration for the CNAME record?

**Comment by el-chazmo** [comment]
> @el-chazmo Thanks for raising this issue. You example Terraform configuration above shows an `aws_route53_record` of type **A** but the error message is about a **CNAME** record -- could you add the configuration for the CNAME record?

Apologies @ewbankkit The above code was incorrect, as suspected. The below is the specific code that is used to generate the Record

resource "aws_route53_record" "certificate" {
  for_each = { for certificate in local.certificates : certificate.domain_name => certificate }

  allow_overwrite = true
  name            = each.value.name
  type            = each.value.type
  zone_id         = aws_route53_zone.zone.zone_id
  records         = [each.value.record]
  ttl             = 60
}

Terraform destroy (1st) shows: -

module.dns.aws_route53_record.certificate["*.example"]: Destroying... [id=XXXXX__yyyyy.example._CNAME]
module.dns.aws_route53_record.certificate["example"]: Destroying... [id=XXXXX__yyyyy.example._CNAME]

│ Error: deleting Route53 Record (XXXXX__yyyyy.example._CNAME): operation error Route 53: ChangeResourceRecordSets, https response error StatusCode: 400, RequestID: xxx-xxx-xxx, InvalidChangeBatch: [Tried to delete resource record set [name='_yyyyy.example.', type='CNAME'] but it was not found]

Terraform destroy (2nd) shows: -

module.dns.aws_route53_zone.zone: Destroying... [id=XXXXX]
module.dns.aws_route53_zone.zone: Destruction complete after 46s
