### ISSUE TITLE
[Bug]: validation error on aws_route53_zone

### ISSUE THREAD

**Issue by Asara** [hashicorp/terraform-provider-aws#37817]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.51.0,5.51.1,5.52.0

### Affected Resource(s)

aws_route53_zone

### Expected Behavior

Should be able to refresh/plan/apply

### Actual Behavior

```
Error: listing tags for Route 53 Hosted Zone (/hostedzone/${HOSTEDZONEID}): operation error Route 53: ListTagsForResource, https response error StatusCode: 400, RequestID: RID, InvalidInput: 1 validation error detected: Value '/hostedzone/${HOSTEDZONEID}' at 'resourceId' failed to satisfy constraint: Member must have length less than or equal to 32
```

I can verify the value of `/hostedzone/${HOSTEDZONEID}`, including the `/hostedzone/` part is a total of 33 characters.

No changes other than upgrading from v5.50.0 to any newer version

### Relevant Error/Panic Output Snippet

```shell
n/a
```

### Terraform Configuration Files

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "= 5.52.0"
    }
  }
}
```

### Steps to Reproduce

- terraform refresh
- terraform plan
- terraform apply

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@Asara Could you please paste in as much of the relevant Terraform configuration as possible? Also, is everything OK with Terraform AWS Provider **v5.50.0**?

**Comment by MichielBijland** [comment]
@ewbankkit, we have the same issue with the provider above v5.50.0; v5.50.0 still works.

**Comment by Asara** [comment]
@ewbankkit honestly not much more to it than that.
```
resource "aws_route53_zone" "priv" {
  name = var.private_domain
  vpc {
    vpc_id = var.vpc_id
  }
}
```
This is the block that is throwing the error.
And yes, v5.50.0 works. We've pinned our tf to this version for now.

**Comment by ewbankkit** [comment]
@MichielBijland @Asara Which version of the Terraform AWS Provider was the `aws_route53_zone` created with?
Do you have the relevant parts Terraform CLI log that you could add to this issue?
Thanks.

**Comment by ewbankkit** [comment]
@Asara Do you have any output like

```
aws_route53_zone. priv: Refreshing state... [id=...]
```

that you could paste in for both error and success (looking for the format of the `id` in state).
Thanks.

**Comment by Asara** [comment]
In both cases
```
aws_route53_zone.priv: Refreshing state... [id=/hostedzone/${ZONEID}]
```

**Comment by ewbankkit** [comment]
With AWS SDK for Go v1, Route53 API URLs were sanitized, removing the leading `/hostedzone/` or `/change/`: https://github.com/aws/aws-sdk-go/blob/ae77b91ecc806411e9c3ebbeebbea036ed908a0d/service/route53/customizations.go#L27.
With AWS SDK for Go v2 it looks like only `GetChange` cleans the API URL: https://github.com/aws/aws-sdk-go-v2/issues/1838.
