### ISSUE TITLE
[Docs]: Resource: aws_detective_organization_configuration import block is not working as mentioned in the official document  

### ISSUE THREAD

**Issue by emansawalhaa** [hashicorp/terraform-provider-aws#37822]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/detective_organization_configuration

### Description

Hello,

We encountered an issue while using the `import block`, as mentioned in the official documentation for the aws_detective_organization_configuration resource. The ID consistently prompted an error message (INVALID_GRAPH_ARN):

```
│   ErrorCode: "INVALID_GRAPH_ARN",
│   ErrorCodeReason: "The requested operation could not be authorized. To proceed with this request, you must specify a valid value for the GraphArn parameter.",
│   SubErrorCode: "INVALID_GRAPH_ARN",
│   SubErrorCodeReason: "The requested operation could not be authorized. To proceed with this request, you must specify a valid value for the GraphArn parameter."
```

Incorrect Usage:

```
import {
  to = aws_detective_organization_configuration.example
  id = "00b00fd5aecc0ab60a708659477e9617"
}
```

Correct Usage:

```
import {
  to = aws_detective_organization_configuration.example
  id = "arn:aws:detective:us-east-1:<accountID>:graph:00b00fd5aecc0ab60a708659477e9617"
}
```
Could you please verify if this behavior aligns with the official documentation?

Thank you,

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
Indeed it should be the behavior graph ARN. I've submitted a PR to fix the documentation.
