### ISSUE TITLE
[Enhancement]: cloud watch logs for Event pipe

### ISSUE THREAD

**Issue by kishan-dhrangadhariya-1998** [hashicorp/terraform-provider-aws#37873]
### Description

We request you to add configurations to aws_pipes_pipe, where we can enable logs to be sent to cloudwatch or S3 or Firehose [**NOT as a Target**] 

Note: pasted SS of similar conifuration on aws console
![aws_pipes_pipe](https://github.com/hashicorp/terraform-provider-aws/assets/111875299/08687813-f915-4f87-aed1-030498fa2b95)

### Affected Resource(s) and/or Data Source(s)

aws_pipes_pipe

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
This has already been addressed by https://github.com/hashicorp/terraform-provider-aws/pull/37135 and is available v5.53.0. I think this issue can be closed.
