### ISSUE TITLE
[Docs]: incomplete sentence for source_action_name

### ISSUE THREAD

**Issue by gardiantnikhil** [hashicorp/terraform-provider-aws#37906]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codepipeline#provider_type

### Description

seems incomplete?

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Yes, there seems to be missing something. In the [Cloudformation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-gitconfiguration.html#cfn-codepipeline-pipeline-gitconfiguration-sourceactionname) one can read

> SourceActionName
>The name of the pipeline source action where the trigger configuration, such as Git tags, is specified. The trigger configuration will start the pipeline upon the specified change only.

In the current documentation available in the provider it is

> The name of the pipeline source action where the trigger configuration.

If its fine, I can look into providing a pull request for this.
