### ISSUE TITLE
[Enhancement]: Add WORKFLOW_JOB_QUEUED Event to aws_codebuild_webhook Resource

### ISSUE THREAD

**Issue by avx-rodmans** [hashicorp/terraform-provider-aws#37904]
### Description

Codebuild has added a new Event type to AWS Codebuild webhooks as described [here](https://docs.aws.amazon.com/codebuild/latest/userguide/action-runner.html). This allows the ability to use AWS Codebuild as a github self-hosted runner. 

### Affected Resource(s) and/or Data Source(s)

* aws_codebuild_webhook

### Potential Terraform Configuration

```terraform
resource "aws_codebuild_webhook" "hook" {
  project_name = aws_codebuild_project.main.name
  build_type   = "BUILD"

  filter_group {
    filter {
      type = "WORKFLOW_JOB_QUEUED" # No need for pattern on this event type
    }
  }
}
```

### References

https://docs.aws.amazon.com/codebuild/latest/userguide/action-runner.html

### Would you like to implement a fix?

None

**Comment by avx-rodmans** [comment]
I see this [Issue](https://github.com/aws/aws-sdk-go-v2/issues/2620) on the AWS SDK

**Comment by garysassano** [comment]
Contrary to AWS CDK, you don't need to add anything new in Terraform since the feature already works out of the box. I made [this project](https://github.com/garysassano/cdktf-aws-codebuild-github-runners) a couple of months ago to test it out.

This is what you need to use:

```tf
resource "aws_codebuild_webhook" "hook" {
  project_name = aws_codebuild_project.main.name

  filter_group {
    filter {
      type = "EVENT",
	  pattern = "WORKFLOW_JOB_QUEUED"
    }
  }
}
```

**Comment by garysassano** [comment]
I opened #38060 to update the docs.
