### ISSUE TITLE
[Docs]: data source aws_route53_zone missing id and name attribute

### ISSUE THREAD

**Issue by wesleung** [hashicorp/terraform-provider-aws#37908]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/5.53.0/docs/data-sources/route53_zone

### Description

Missing attribute id for data source aws_route53_zone

This is used when querying for the zone_id of a route53 zone.  This functionality does work but not stated in the documentation.

```
data "aws_route53_zone" "selected" {
  name         = "test.com."
}

output "zone_id" {
  value = data.aws_route53_zone.id
}

output "zone_name" {
  value = data.aws_route53_zone.name
}

```

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
I can pick this up, but would need clarification before:

- the documentation for the data resource states under section [_Attribute Reference_](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/route53_zone#attribute-reference): 
  > All of the argument attributes are also exported as result attributes. 

  One can find details on `name` in the  _Argument Reference_. So, is an additional entry for `name`  under _Attribute Reference_ really required?

- For the `id` field - as it maps to the already documented Zone Identifier  ([link to source code](https://github.com/hashicorp/terraform-provider-aws/blob/8ac2a3723b27bbcc1d6c3fdf717abb74f5fa3aca/internal/service/route53/zone_data_source.go#L156)): should we add a line to the existing Zone Identifier documentation or explicitly add `id`  to the _Attribute Reference_? I checked other resources but could not identify a pattern.

**Comment by stefanfreitag** [comment]
@justinretzolk is there any kind of standard to follow?
