### ISSUE TITLE
[Bug]: All data.aws_cloudwatch_log_group requests return empty tags object and retention_days of 0

### ISSUE THREAD

**Issue by jinnko** [hashicorp/terraform-provider-aws#37916]
### Terraform Core Version

1.6.1

### AWS Provider Version

5.53.0

### Affected Resource(s)

```
aws_cloudwatch_log_group
```

### Expected Behavior

1. The tags object should contain a list of the assigned tags on the resource.
2. The retention days returns 0

### Actual Behavior

The returned object contains an empty tags object and retention_days of 0.

### Relevant Error/Panic Output Snippet

The result of a lookup, when logged as output, returns the following, where the tags 

```hcl
+ log_group = {
          + arn               = "arn:aws:logs:us-east-1:999999999999:log-group:custom-log-group"
          + creation_time     = 1605109079084
          + id                = "custom-log-group"
          + kms_key_id        = ""
          + log_group_class   = "STANDARD"
          + name              = "custom-log-group"
          + retention_in_days = 0
          + tags              = {}
        }
```

With provider v5.52.0 the output is correct:

```hcl
+ log_group = {
      + arn               = "arn:aws:logs:us-east-1:999999999999:log-group:custom-log-group"
      + creation_time     = 1653392813586
      + id                = "custom-log-group"
      + kms_key_id        = ""
      + log_group_class   = "STANDARD"
      + name              = "custom-log-group"
      + retention_in_days = 731
      + tags              = {
          + AppId              = "custom-log-group"
        }
    }
```

### Terraform Configuration Files

```
data "aws_cloudwatch_log_group" "this" {
  name     = "custom-log-group"
}

output "log_group" {
  value = data.aws_cloudwatch_log_group.this
}
```

### Steps to Reproduce

1. Make sure there's a Cloudwatch LogGroup in your account with tags assigned.  Confirm this via the AWS Web Console.
3. Run the above terraform and observe that the `tags` object is empty and `retention_days` is `0`, while the AWS Web Console shows there are indeed tags.

### Important Factoids

1. This is a critical bug
2. Downgrading to 5.52.0 resolves the issue

### References

I believe this has resulted from the changes in https://github.com/hashicorp/terraform-provider-aws/pull/37668 having been merged.

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
I can reproduce with a modified acceptance test:

```console
% make testacc TESTARGS='-run=TestAccLogsGroupDataSource_basic' PKG=logs
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/logs/... -v -count 1 -parallel 20  -run=TestAccLogsGroupDataSource_basic -timeout 360m
=== RUN   TestAccLogsGroupDataSource_basic
=== PAUSE TestAccLogsGroupDataSource_basic
=== CONT  TestAccLogsGroupDataSource_basic
    group_data_source_test.go:22: Step 1/1 error: Check failed: Check 7/7 error: data.aws_cloudwatch_log_group.test: Attribute "tags.%" not set, but "tags.%" is set in aws_cloudwatch_log_group.test as "1"
--- FAIL: TestAccLogsGroupDataSource_basic (5.02s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/logs	9.604s
FAIL
make: *** [testacc] Error 1
```

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/37886.

**Comment by gdavison** [comment]
I've created #37965 to address the `retention_days` issue
