### ISSUE TITLE
[Enhancement]: Add the GuardDuty S3 bucket malware scanning functionality

### ISSUE THREAD

**Issue by Vahan90** [hashicorp/terraform-provider-aws#37951]
### Description

* [As of now, Amazon GuardDuty supports scanning s3 buckets for malware](https://aws.amazon.com/blogs/aws/introducing-amazon-guardduty-malware-protection-for-amazon-s3/)
* Also as part of that, we now can enable GuardDuty to *exclusively* work as a malware scanner for S3: 
![image](https://github.com/hashicorp/terraform-provider-aws/assets/6980950/f72d2095-4a9b-4961-bc13-1a26bccbfe3d)
* I would like to see the feature implemented to the GuardDuty resource, and also the ability to specify the s3 buckets as part of the `malware_protection`
* Please excuse me as this is the first time I'm opening an Enhancement issue for terraform, and I also don't know whether this is in the roadmap already, or exists in a newer version I don't know about.

### Affected Resource(s) and/or Data Source(s)

* aws_guardduty_detector
* aws_guardduty_detector_feature

### Potential Terraform Configuration

```terraform
resource "aws_guardduty_detector" "MyDetector" {
  enable  = true
  s3_only = true

  datasources {
    s3_logs {
      enable = true
    }
    kubernetes {
      audit_logs {
        enable = false
      }
    }
    malware_protection {
      scan_ec2_instance_with_findings {
        ebs_volumes {
          enable = true
        }
      }
      scan_s3_buckets_with_findings {
        s3_buckets {
          enable  = true
          buckets = [(list of buckets)]
        }
      }
    }
  }
}
```

### References

* https://aws.amazon.com/blogs/aws/introducing-amazon-guardduty-malware-protection-for-amazon-s3/
* https://aws.amazon.com/guardduty/pricing/

### Would you like to implement a fix?

Yes

**Comment by ewbankkit** [comment]
@Vahan90 Thanks for raising this issue.
It has already been noticed in #37918. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
