### ISSUE TITLE
[Bug]:  Plugin did not respond

### ISSUE THREAD

**Issue by pmoosh** [hashicorp/terraform-provider-aws#37983]
### Terraform Core Version

1.7.5

### AWS Provider Version

5.54.0

### Affected Resource(s)

ami datasource

### Expected Behavior

should return an image id or none

### Actual Behavior

Panics

### Relevant Error/Panic Output Snippet

```shell
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.main.data.aws_ami.centos,
│   on ../terraform_modules/postgres/ami.tf line 1, in data "aws_ami" "centos":
│    1: data "aws_ami" "centos" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v5.54.0_x5 plugin:

panic: interface conversion: interface {} is types.ProductCodeValues, not string

goroutine 346 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.amiProductCodesHash({0x22e3d8c0?, 0xc002c221b0})
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/ec2_ami_data_source.go:456 +0x1b5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).hash(0x0?, {0x22e3d8c0?, 0xc002c221b0?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/set.go:221 +0x26
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).add(0xc002c1e680, {0x22e3d8c0, 0xc002c221b0}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/set.go:201 +0x85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).Add(...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/set.go:79
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.flattenAMIProductCodes({0xc004b91de0, 0x1, 0x10?})
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/ec2_ami_data_source.go:391 +0x6d
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.dataSourceAMIRead({0x24e69a28, 0xc0025bb2c0}, 0xc0012d5380, {0x24bee7e0?, 0xc0020505b0})
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/ec2_ami_data_source.go:330 +0xc65
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedDataSource).Read.interceptedHandler[...].func7(0xc0012d5380?, {0x24bee7e0?, 0xc0020505b0})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x24e69a28?, {0x24e69a28?, 0xc0025a8ff0?}, 0xd?, {0x24bee7e0?, 0xc0020505b0?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:818 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc00159a9a0, {0x24e69a28, 0xc0025a8ff0}, 0xc0012d5280, {0x24bee7e0, 0xc0020505b0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:1043 +0x13a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc004084d20, {0x24e69a28?, 0xc0025a8f30?}, 0xc00262cea0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:1434 +0x6b1
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ReadDataSource(0xc0017077a0, {0x24e69a28?, 0xc00262cf00?}, 0xc00262cea0)
	github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ReadDataSource.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc000393220, {0x24e69a28?, 0xc00262c720?}, 0xc000664000)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:688 +0x27d
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x249b96a0, 0xc000393220}, {0x24e69a28, 0xc00262c720}, 0xc0006d7900, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:572 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001500200, {0x24e69a28, 0xc00262c690}, {0x24ebab60, 0xc004b4a000}, 0xc00262e360, 0xc0020e12c0, 0x2de00520, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc001500200, {0x24ebab60, 0xc004b4a000}, 0xc00262e360)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 55
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x125

Error: The terraform-provider-aws_v5.54.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

data "aws_ami" "centos" {
  most_recent = true
  filter {
    name = "product-code"
    values = ["cvugziknvmxgqna9noibqnnsy"]
  }
  owners = ["679593333241"]
}

### Steps to Reproduce

run terraform plan

### Panic Output

[test/ami]$ terraform.1.7.5 plan
data.aws_ami.centos: Reading...

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│ 
│   with data.aws_ami.centos,
│   on test.tf line 39, in data "aws_ami" "centos":
│   39: data "aws_ami" "centos" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v5.54.0_x5 plugin:

panic: interface conversion: interface {} is types.ProductCodeValues, not string

goroutine 31 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.amiProductCodesHash({0x231428c0?, 0xc00205cf00})
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/ec2_ami_data_source.go:456 +0x1b5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).hash(0x0?, {0x231428c0?, 0xc00205cf00?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/set.go:221 +0x26
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).add(0xc003c87ba0, {0x231428c0, 0xc00205cf00}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/set.go:201 +0x85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).Add(...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/set.go:79
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.flattenAMIProductCodes({0xc003ba3160, 0x1, 0x10?})
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/ec2_ami_data_source.go:391 +0x6d
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.dataSourceAMIRead({0x2516ea28, 0xc001dd5320}, 0xc0011ec680, {0x24ef37e0?, 0xc002663ad0})
	github.com/hashicorp/terraform-provider-aws/internal/service/ec2/ec2_ami_data_source.go:330 +0xc65
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedDataSource).Read.interceptedHandler[...].func7(0xc0011ec680?, {0x24ef37e0?, 0xc002663ad0})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x2516ea28?, {0x2516ea28?, 0xc001d8cff0?}, 0xd?, {0x24ef37e0?, 0xc002663ad0?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:818 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0015cc9a0, {0x2516ea28, 0xc001d8cff0}, 0xc0011ec580, {0x24ef37e0, 0xc002663ad0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:1043 +0x13a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc0034d2d20, {0x2516ea28?, 0xc001d8cf30?}, 0xc001d8cc00)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:1434 +0x6b1
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ReadDataSource(0xc0017dac40, {0x2516ea28?, 0xc001d8cc60?}, 0xc001d8cc00)
	github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ReadDataSource.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0003bf0e0, {0x2516ea28?, 0xc001d8c270?}, 0xc001a1c140)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:688 +0x27d
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x24cbe6a0, 0xc0003bf0e0}, {0x2516ea28, 0xc001d8c270}, 0xc0011ec000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:572 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000dac200, {0x2516ea28, 0xc001d8c1b0}, {0x251bfb60, 0xc000c4e300}, 0xc001d8e120, 0xc002706c90, 0x2e105520, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc000dac200, {0x251bfb60, 0xc000c4e300}, 0xc001d8e120)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 30
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x125

Error: The terraform-provider-aws_v5.54.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Important Factoids

Works with earlier version such as 5.53.0

### Would you like to implement a fix?

None

**Comment by OffBy0x01** [comment]
Just wanted to add that it isn't exclusive to data providers - also seeing this error on other resources classes too.

**Comment by JHunsGlobal** [comment]
Latest version 5.54.1 contains a fix.

**Comment by pmoosh** [comment]
It is fixed. It can be closed
