### ISSUE TITLE
[Bug]:  aws_ec2_transit_gateway_route_table_propagation pagination issue when huge number of propagations created for one table

### ISSUE THREAD

**Issue by neshcheretal** [hashicorp/terraform-provider-aws#38009]
### Terraform Core Version

1.1.9

### AWS Provider Version

5.53.0,5.54.0

### Affected Resource(s)

aws_ec2_transit_gateway_route_table_propagation

### Expected Behavior

When I run the Terraform code I expect a clean run for already existing resources created by Terraform.

### Actual Behavior

For some TGW routing tables we have around ~2000 of propagations created, after version 5.53.0 we experience an issue when on the terraform run it tries creating the propagations that were already created with terraform and objects are stored in the state. When freeze my provider version to 5.52.0 I have no changes in the terraform plan, so obviously the issue is that in the resource read phase no we don't have all propagations retrieved via the API.

As I see the propagation functions were changed recently in: 
https://github.com/hashicorp/terraform-provider-aws/commit/6a7670498f380f4fe1a2fbb22d339bd903c0780d#diff-7d2b0b6237899efaca5661c25bda4b37213cebb3a1961eaa4ca8fefe0196bcb8
https://github.com/hashicorp/terraform-provider-aws/commit/69cebffa08d485c1a6dd177b2bb6a53f2de24f6a#diff-551779d3823a252fd19739dcdfcbfc7f686e2c2a706ccd602656ef0c4bd89022

Is it correct that in the pagination function we chek it just once https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ec2/findv2.go#L4141 ?

### Terraform Configuration Files

```
provider "aws" {
  region     = var.aws_region
}

resource "aws_ec2_transit_gateway_route_table_propagation" "route_table_propagation" {
  for_each                       = var.attachment_lists
  transit_gateway_attachment_id  = each.value
  transit_gateway_route_table_id = "<tgw-table-id>"
}
```

### Steps to Reproduce

The issue is reproducible only when you have more than a thousand propagations in one TGW routing table. 

### References

https://github.com/hashicorp/terraform-provider-aws/commit/6a7670498f380f4fe1a2fbb22d339bd903c0780d#diff-7d2b0b6237899efaca5661c25bda4b37213cebb3a1961eaa4ca8fefe0196bcb8
https://github.com/hashicorp/terraform-provider-aws/commit/69cebffa08d485c1a6dd177b2bb6a53f2de24f6a#diff-551779d3823a252fd19739dcdfcbfc7f686e2c2a706ccd602656ef0c4bd89022

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/37710.
