### ISSUE TITLE
[Bug]: missing parameter in sqli_match_statement for Web ACL

### ISSUE THREAD

**Issue by prasad5501** [hashicorp/terraform-provider-aws#38000]
### Terraform Core Version

1.6.1

### AWS Provider Version

5.54.1

### Affected Resource(s)

aws_wafv2_rule_group

### Expected Behavior

When using statement of type sqli_match_statement in rule while creating aws_wafv2_rule_group should support a parameter to set sensitivity as supported in underlying AWS api.

### Actual Behavior

When using statement of type sqli_match_statement in rule while creating aws_wafv2_rule_group does not support a parameter to set sensitivity as supported in underlying AWS api.

### Terraform Configuration Files

```hcl
rule {
    name = "xyz"
    priority = 0

    action {
      block {}
    }

    statement {
      sqli_match_statement {
        text_transformation {
          type = "NONE"
          priority = 0
        }

        field_to_match {
          json_body {
            match_pattern {
              all {}
            }
            match_scope = "ALL"
            oversize_handling = "CONTINUE"
          }
        }
      }
    }
    visibility_config {
      cloudwatch_metrics_enabled = true
      metric_name = "xyz_metrics"
      sampled_requests_enabled = false
    }
  }
```

### Steps to Reproduce

When a rule is created of type sqli_match_statement it defaults to low sensitivity. One needs to manually update it to HIGH from AWS console which is replaced on next terraform run.

### Would you like to implement a fix?

No

**Comment by acwwat** [comment]
I believe this has been fixed in v5.56.0 via #29672. The enhancement should also apply to the `aws_wafv2_rule_group` resource, and you should be able to set the `sensitivity_level` parameter.

However the documentation doesn't seem to have been updated, which I will do with this issue.
