### ISSUE TITLE
[Bug]: EndpointV2 missing in output for aws_opensearch_domain for IPv6 dualstack support

### ISSUE THREAD

**Issue by pioneer2k** [hashicorp/terraform-provider-aws#38012]
### Terraform Core Version

1.8.5

### AWS Provider Version

5.54.1

### Affected Resource(s)

aws_opensearch_domain 

### Expected Behavior

With pull request 37237 https://github.com/hashicorp/terraform-provider-aws/pull/37237 the support of IPv6 dual stack was integrated, which works fine. But for using the dual stack functionality with OpenSearch it provides a different endpoint called EndpointV2. See the AWS docs:
_EndpointV2
If IPAddressType to set to dualstack, a version 2 domain endpoint is provisioned. This endpoint functions like a normal endpoint, except that it works with both IPv4 and IPv6 IP addresses. Normal endpoints work only with IPv4 IP addresses._

### Actual Behavior

The aws_opensearch_domain resource and data source do not output this new endpoint V2, so switching to dual stack with Terraform is kinda useless..

### Terraform Configuration Files

see the docs for aws_opensearch_domain and create a domain with ip_address_type="dualstack". The output endpoint will give you the IPv4 endpoint and there is no way to receive the dual stack endpoint.

### Steps to Reproduce

see above

### Would you like to implement a fix?

None

**Comment by jgronfur** [comment]
This bug makes dualstack support nearly useless. Can the PR be merged asap?
