### ISSUE TITLE
[Docs]: db_subnet_group_name and publicly_accessible interaction

### ISSUE THREAD

**Issue by ben-dov** [hashicorp/terraform-provider-aws#38024]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_instance#db_subnet_group_name

### Description

Copied from hashicorp/terraform#35353
The [document page](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_instance#db_subnet_group_name) mistakenly asserts that `db_subnet_group_name` is required if `publicly_accessible = false` (which is the default), but it seems in the [cli](https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-instance.html):
>If DBSubnetGroupName isn't specified, and PubliclyAccessible isn't specified, the following applies:
> * If the default VPC in the target Region doesn’t have an internet gateway attached to it, the DB instance is private.
> * If the default VPC in the target Region has an internet gateway attached to it, the DB instance is public.

So unless I am misunderstanding the docs, it seems like this section should be changed.

### References

https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-instance.html

### Would you like to implement a fix?

No

**Comment by Jyots6914** [comment]
I will work on it and I will raise PR.
