### ISSUE TITLE
[Bug]: Can't change the configuration from local to central from the delegated administrator account for sechub

### ISSUE THREAD

**Issue by ramongalate** [hashicorp/terraform-provider-aws#38043]
### Terraform Core Version

>= 1.3.0

### AWS Provider Version

5.41.0

### Affected Resource(s)

I have recently started configuring security hub centrally and I have set up an administrator account from the management account. 
The security hub account is working properly with the local configuration, I can set up automations and do other tasks using a role I created from the sechub account that gives the role the following permission:

```hcl
statement {
    sid = "FirewallAdministratorWriteAccess"
    actions = [
      "securityhub:*"
    ]
    resources = ["*"]
    effect    = "Allow"
  }
```

But when I try and add this from the delegated admin account :

```hcl
resource "aws_securityhub_finding_aggregator" "this" {
  linking_mode = "ALL_REGIONS"
}

resource "aws_securityhub_organization_configuration" "this" {
  auto_enable           = false
  auto_enable_standards = "NONE"
  organization_configuration {
    configuration_type = "CENTRAL"
  }

  depends_on = [aws_securityhub_finding_aggregator.this]
}
```

The aggregator works, but the configuration gives the error :

```console
╷
│ Error: updating Security Hub Organization Configuration (------): operation error SecurityHub: UpdateOrganizationConfiguration, https response error StatusCode: 403, RequestID: 32959520-5dde-41d4-a8b4-a2248211b863, AccessDeniedException: You don't have permissions to access this resource.
│ 
│   with module.sechub_standards_config.aws_securityhub_organization_configuration.this,
│   on modules/sechubStandardsConfig/main.tf line 60, in resource "aws_securityhub_organization_configuration" "this":
│   60: resource "aws_securityhub_organization_configuration" "this" {
│ 
╵
```

Do you have any idea as to why this could be happening?

### Expected Behavior

It should have let me modify our configuration from local to central.

### Actual Behavior

Does not let me create the resource and gives a 403 error as bellow.

### Relevant Error/Panic Output Snippet

```console
╷
│ Error: updating Security Hub Organization Configuration (delegated admin account id): operation error SecurityHub: UpdateOrganizationConfiguration, https response error StatusCode: 403, RequestID: 32959520-5dde-41d4-a8b4-a2248211b863, AccessDeniedException: You don't have permissions to access this resource.
│ 
│   with module.sechub_standards_config.aws_securityhub_organization_configuration.this,
│   on modules/sechubStandardsConfig/main.tf line 60, in resource "aws_securityhub_organization_configuration" "this":
│   60: resource "aws_securityhub_organization_configuration" "this" {
│ 
╵
```

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.41.0"
    }
  }
  required_version = ">= 1.3.0"
}
```

### Steps to Reproduce

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.41.0"
    }
  }
  required_version = ">= 1.3.0"
}
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @ramongalate 👋 Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. To maintain that, we ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). With that in mind, I'm going to close this issue, but would be remiss if I didn't mention that it appears that the issue is related to the permissions of the credentials being used to authenticate the provider:

```console
AccessDeniedException: You don't have permissions to access this resource.
```
