### ISSUE TITLE
[Docs]: "This argument supports the following arguments"

### ISSUE THREAD

**Issue by rpdelaney** [hashicorp/terraform-provider-aws#38072]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_security_group_egress_rule

### Description

In various places, docs for resource arguments begin with "This resource supports the following arguments". In others, (such as [`aws_vpc_security_group_egress_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_security_group_egress_rule)) it is written "This argument supports the following arguments".

I don't understand the latter formulation when applied to a resource's top-level arguments, but it occurs frequently enough that I am second guessing whether this could be a simple typo. 
```console
$ grep -r -l -F 'This argument supports the following arguments' . | wc -l
139
```

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @rpdelaney 👋 Thank you for taking the time to raise this! My gut feeling is that this is unintentional, so I'll add it to my list of things to look at with regards to docs.

**Comment by acwwat** [comment]
Indeed the usage is unintentional and I was working on a PR earlier on all occurrences for both resources and data sources.
