### ISSUE TITLE
[ECS]: Running a new task using Terraform without a service in AWS ECS

### ISSUE THREAD

**Issue by berkayalan** [hashicorp/terraform-provider-aws#38106]
### Description

Hi, 

I don't know if it's a duplicated issue but could not find updated answer for my question. I would like to create an ECS task via terraform, not a service. Is it possible to do that via terraform? Because resources I found are so old and they suggest to run aws-cli from the local-exec provisioned.

Thanks in advanced.

### Requested Resource(s) and/or Data Source(s)

ECS

### References

https://stackoverflow.com/a/58124209/13472725

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @berkayalan  👋 Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. To maintain that, we ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws).

With that in mind, I'm going to close this issue, but wanted to mention that I believe the [`aws_ecs_service` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service) may still be what you're looking for. From the description of that resource:

> Provides an ECS service - effectively a task that is expected to run until an error occurs or a user terminates it (typically a webserver or a database).

The definition of the task itself comes from the [`aws_ecs_task_definition` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition)
