### ISSUE TITLE
[Enhancement]: AWS RDS Aurora Serverless V1 'Autoscaling timeout' attribute inclusion

### ISSUE THREAD

**Issue by ajayece02** [hashicorp/terraform-provider-aws#38119]
### Description

Currently there is no attribute to set value for AWS RDS Aurora Serverless V1 'Autoscaling timeout' parameter so table is getting created with default value of 5minutes. Need this attribute to be added to terraform to create table with values other than defaults. 

### Affected Resource(s) and/or Data Source(s)

resource "aws_rds_cluster"

### Potential Terraform Configuration

```terraform
scaling_configuration {
    auto_pause               = true
    max_capacity             = 16
    min_capacity             = 1
    seconds_until_auto_pause = 900
    autoscaling_timeout      = 60
  }
```

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
The **Autoscaling timeout** referenced in the AWS Management Console corresponds to the [`SecondsBeforeTimeout` attribute](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ScalingConfiguration.html) in the API. I will submit a PR to add it.
