### ISSUE TITLE
aws_sagemaker_workteam

### ISSUE THREAD

**Issue by wslayton-GHC** [hashicorp/terraform-provider-aws#38123]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_workteam

### Description

1. Descriptions for workforce name and workteam name are swapped
2. In the example, accessing the user_group in the cognito_member_definition requires aws_cognito_user_group.example.name, not aws_cognito_user_group.example.id. user_group.id prepends "user_pool.name/" to the group name

### Would you like to implement a fix?

Yes

**Comment by Jyots6914** [comment]
I will work on it and submit PR.
@justinretzolk  : I have gone through documentation and looks like modification need to be done in https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_workteam as well as in https://github.com/Fidelity-External-Staging/hashicorp-terraform-provider-aws/blob/main/website/docs/cdktf/python/r/sagemaker_workteam.html.markdown and https://github.com/Fidelity-External-Staging/hashicorp-terraform-provider-aws/blob/main/website/docs/cdktf/typescript/r/sagemaker_workteam.html.markdown . 
so do we need to raise separate issue for that or can be done as part of same issue?
