### ISSUE TITLE
Replication is not creating for the aws secrets in west

### ISSUE THREAD

**Issue by sooraj2589** [hashicorp/terraform-provider-aws#38125]
### Description

We need to create replication for the existing secrets in west region to east region. I have tried multiple options none of them worked as expected. 

I tried to get the secret with data source and pass it for the replica.

Can you please help with a right approach?

### References

Ref: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/secretsmanager_secret
https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/secretsmanager_secret

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @sooraj2589 👋 Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. To maintain that, we ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws). With that in mind, I'm going to close this issue.
