### ISSUE TITLE
[Enhancement]: Add Argument for min & max MWAA Web Server Count 

### ISSUE THREAD

**Issue by skpune** [hashicorp/terraform-provider-aws#38152]
### Description

The current resource argument doesn't provide support for min min_webserver and max_webserver howerver this feture is already available while creating MWAA from AWS console.

Proposed Solution
Add an optional parameter within the aws_mwaa_environment resource. This parameter should accept an integer representing the number of min and max webserver count

Benefits
Provides users with greater control over minimum and maximum number of webservers like as worker and schedulers.

### Affected Resource(s) and/or Data Source(s)

https://docs.aws.amazon.com/mwaa/latest/userguide/mwaa-web-server-autoscaling.html 

### Would you like to implement a fix?

None

**Comment by skpune** [comment]
Hi Team, 

Is any working on this enhancement and what will be the ETA for the enhancement?

Thanks,
Shubham

**Comment by vidyapanchalZS** [comment]
Hello Team,

hope you are doing well!

Writing to follow up on the request regarding the MWAA module in Terraform. We have been frequently using this module to provision MWAA environments, and we have encountered some issues with updating the MWAA environment using Terraform.

To address this, we kindly request you to implement the above enhancement in the MWAA module of Terraform. This will help us avoid facing issues when updating the MWAA environment using Terraform.

Your efforts in addressing this request will be greatly appreciated.

Thank you in advance for your attention to this matter.

**Comment by acwwat** [comment]
This has already been addressed via https://github.com/hashicorp/terraform-provider-aws/pull/37632. The added attributes are `max_webservers` and `min_webservers`.

However as @skpune noted the new arguments are not documented, so I will use this issue to update the documentation.
