### ISSUE TITLE
[Enhancement]: Add support for bootstrapSelfManagedAddons flag in aws_eks_cluster resource

### ISSUE THREAD

**Issue by bdalpe** [hashicorp/terraform-provider-aws#38156]
### Description

The CreateCluster EKS API call has added a new parameter `bootstrapSelfManagedAddons` to configure whether managed add-ons (i.e. `vpc-cni`, `coredns`, and `kube-proxy`) are automatically installed at cluster creation time.

This is an optional flag. Setting the value to `false` disables installation of the managed add-ons. This permits admins to install and manage their cluster add-ons separate from AWS.

### Affected Resource(s) and/or Data Source(s)

* resource `aws_eks_cluster`

### Potential Terraform Configuration

```terraform
resource "aws_eks_cluster" "example" {
  name = "example"
  bootstrap_self_managed_addons = false
  ...
}
```

### References

* https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html#API_CreateCluster_RequestBody
* https://github.com/aws/aws-sdk-js-v3/commit/cdf4fe62048ff8cf926def590432f61bcea565c5
* (added in AWS Go SDK v2 v1.45.0) https://github.com/aws/aws-sdk-go-v2/blame/7c25c211744bdcff47a7203a7a894b1241f9da50/service/eks/api_op_CreateCluster.go#L101-L109

### Would you like to implement a fix?

Yes

**Comment by littlejo** [comment]
It's already on awscc provider: https://github.com/hashicorp/terraform-provider-awscc/blob/main/internal/aws/eks/cluster_resource_gen.go#L116
