### ISSUE TITLE
[Bug]: missing dns_name in aws_fsx_ontap_file_system

### ISSUE THREAD

**Issue by relivnd** [hashicorp/terraform-provider-aws#38179]
### Terraform Core Version

1.9.0

### AWS Provider Version

5.56.0

### Affected Resource(s)

aws_fsx_ontap_file_system

### Expected Behavior

I expect a string containing the DNS name at the dns_name field in the state. The DNS name is visible in the AWS Console.

### Actual Behavior

The field is null and thus can't be used e.g. to mount the file-share via nfs.
![image](https://github.com/hashicorp/terraform-provider-aws/assets/77431277/da67b65f-5f94-403c-9c04-60af87de13df)

### Relevant Error/Panic Output Snippet

```shell
# data.aws_fsx_ontap_file_system.example:
data "aws_fsx_ontap_file_system" "example" {
    arn                               = "arn:aws:fsx:eu-central-1:3*****7:file-system/fs-0*******d"
    automatic_backup_retention_days   = 7
    daily_automatic_backup_start_time = "05:00"
    deployment_type                   = "MULTI_AZ_1"
    disk_iops_configuration           = [
        {
            iops = 3072
            mode = "USER_PROVISIONED"
        },
    ]
    dns_name                          = null
    endpoint_ip_address_range         = "***.***.***.0/24"
    endpoints                         = [
        {
            intercluster = [
                {
                    dns_name     = "intercluster.fs-0****d.fsx.eu-central-1.amazonaws.com"
                    ip_addresses = [
                        "***.***.***.0",
                        "***.***.***.0",
                    ]
                },
            ]
            management   = [
                {
                    dns_name     = "management.fs-0*****d.fsx.eu-central-1.amazonaws.com"
                    ip_addresses = [
                        "***.***.***.0",
                    ]
                },
            ]
        },
    ]
    ha_pairs                          = 1
    id                                = "fs-0****d"
    kms_key_id                        = "arn:aws:kms:eu-central-1:3****7:key/4****-67f8-47de-8c38-*********3"
    network_interface_ids             = [
        "eni-0***e",
        "eni-0***6",
    ]
    owner_id                          = "3******7"
    preferred_subnet_id               = "subnet-0******5"
    route_table_ids                   = [
        "rtb-02aad3a7e884d85f1",
    ]
    storage_capacity                  = 1024
    storage_type                      = "SSD"
    subnet_ids                        = [
        "subnet-0******5",
        "subnet-0******5",
    ]
    tags                              = {
        "Name"                  = "cst-trc-dev-app-server-fsx"
        "managed_by"            = "Terraform"
        "terraform-aws-modules" = "fsx"
    }
    throughput_capacity               = 128
    throughput_capacity_per_ha_pair   = 128
    vpc_id                            = "vpc-0*****6"
    weekly_maintenance_start_time     = "1:06:00"
}
```

### Terraform Configuration Files

terraform {
  required_version = ">= 1.8.4"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }
  }
}

provider "aws" {
  region = "eu-central-1"

  default_tags {
    tags = {
      managed_by = "Terraform"
      repository = "something"
    }
  }
}

data "aws_fsx_ontap_file_system" "example" {
  id = "id-of_deployed_fsx_ontap"
}

### Steps to Reproduce

1. Deploy fsx NetApp ONTAP either manually or with https://github.com/terraform-aws-modules/terraform-aws-fsx/tree/master/modules/ontap
2. set the right fsx id within the data block
3. apply
4. look at element in state `terraform state show data.aws_fsx_ontap_file_system.example`
==> Missing dns_name

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
If I am not mistaken, FSx for ONTAP file systems would only provide DNS names for the management and inter-cluster endpoint. To access the file system and volumes, you need to use a Storage Virtual Machine (SVM), which should provide you with the endpoint (DNS name) to connect to it for different protocols (SMB, NFS, iSCSI). See the [`aws_fsx_ontap_storage_virtual_machine` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_ontap_storage_virtual_machine) for details.

The `aws_fsx_ontap_file_system` resource likely just inherited the `dns_name` attribute that is part of the more general [FileSystem](https://docs.aws.amazon.com/fsx/latest/APIReference/API_FileSystem.html) data type that is common across different flavors of FSx, but not "used" for FSx for ONTAP file systems.

**Comment by relivnd** [comment]
You're right. I resolved it in my case by using the DNS name from `data.aws_fsx_ontap_storage_virtual_machine` and concatenating it with the `junction path` of the volume. Although it might even be slightly cleaner to use the data block for the SVM in the first place, I think it would be better to either:
- remove the DNS name property from `aws_fsx_ontap_file_system`
- make it work, by populating the field with the expected DNS name
- clearly state in the documentation, that the field is not populated with any data, because it's inherited but not used

Otherwise one is just questioning why the code is not working, even though there's an underlying reason.
Currently, the documentation is misleading to:
[dns_name](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/fsx_ontap_file_system#dns_name) - DNS name for the file system (e.g. fs-12345678.corp.example.com).

**Comment by acwwat** [comment]
I think adding a note to the documentation is the most sensible option for now - I've submitted a PR.
