### ISSUE TITLE
[Docs]: resource aws_cloudfront_response_headers_policy with argument `remove_headers_config` needs an example for ease of use

### ISSUE THREAD

**Issue by jmonte-sph** [hashicorp/terraform-provider-aws#38174]
### Documentation Link

https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/cloudfront_response_headers_policy.html.markdown

### Description

While implementing the `remove_headers_config` arguments of resource `aws_cloudfront_response_headers_policy` for the first time, I could not find a working example to reference, unlike the other attributes.

### References

n/a

### Would you like to implement a fix?

Yes

**Comment by bman654** [comment]
I had to find the pull request to [see](https://github.com/hashicorp/terraform-provider-aws/pull/28940/files#diff-53b30435f4c74f84107176ec8bf52a6b4d6b05b1bb761569dcdbaac4a2d663a7R526) how to use this attribute.

It's unusual way to specify multiple items (instead of just being an array).

```hcl
  remove_headers_config {
    items {
      header = "server"
    }

    items {
      header = "x-amz-server-side-encryption"
    }
  }
```

**Comment by Jyots6914** [comment]
I will raise PR for this
