### ISSUE TITLE
Unable to connect to MongoDB from GitHUB action runner(Ubuntu_Latest).

### ISSUE THREAD

**Issue by ravindrainduri** [hashicorp/terraform-provider-aws#38205]
### Description

I'm trying to connect to connect mongo db from Github actions, but i'm unable to connect . Getting below error:
<img width="598" alt="image" src="https://github.com/hashicorp/terraform-provider-aws/assets/45281912/60a01780-aab9-4fea-bbe3-db9f1163b79b">
Kindly please help in fixing this.

The yaml used for the action is:

name: Deployment
on:
  push:
    branches:
      - master
      - dev
env:
  MONGODB_DB_NAME: rmongodb1
jobs:
  test:
    env:
      MONGODB_CLUSTER_ADDRESS: cluster0.hrxed0a.mongodb.net
      MONGODB_USERNAME: mongou1
      MONGODB_PASSWORD: 4512@Mongo
      PORT: 8080
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Mongo DEP
        run: npm install mongodb@4.1
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "Adding new line"

Db file used is:

import { MongoClient } from 'mongodb';

const clusterAddress = process.env.MONGODB_CLUSTER_ADDRESS;
const dbUser = process.env.MONGODB_USERNAME;
const dbPassword = process.env.MONGODB_PASSWORD;
const dbName = process.env.MONGODB_DB_NAME;

const uri = `mongodb+srv://${dbUser}:${dbPassword}@${clusterAddress}/?retryWrites=true&w=majority`;
const client = new MongoClient(uri);

console.log('Trying to connect to db');

try {
  await client.connect();
  await client.db(dbName).command({ ping: 1 });
  console.log('Connected successfully to server');
} catch (error) {
  console.log('Connection failed.');
  await client.close();
  console.log('Connection closed.');
}

const database = client.db(dbName);

export default database;

Let me know if anything else i need to debug the issue. 

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
@ravindrainduri This issue does not seem to be related to the Terraform AWS Provider at all. Did you perhaps cerate it in the wrong repository?
