### ISSUE TITLE
[Bug]: aws_fsx_openzfs_volume always detects tags_all as being changed

### ISSUE THREAD

**Issue by zampettim** [hashicorp/terraform-provider-aws#38229]
### Terraform Core Version

1.9.0

### AWS Provider Version

v5.56.1

### Affected Resource(s)

aws_fsx_openzfs_volume

### Expected Behavior

Running terraform plan for a manifest with the aws_fsx_openzfs_volume resource where nothing changes should result in no planned updates.

### Actual Behavior

The aws_fsx_openzfs_volume resource is always seeing the tags_all parameters as being changed, even though the default_tags on the provider and the data in the AWS resource have not changed. 

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-east-1"
  alias  = "us-east-1"

  profile = "XXXX"

  # Make sure we are working on the right account
  allowed_account_ids = ["XXXXXXX"]

  default_tags {
    tags = {
      TerraformManaged = "YES"
      Environment      = "Development"
    }
  }
}
```

### Steps to Reproduce

Create a manifest that creates the aws_fsx_openzfs_volume resource
Run terraform apply to create the resources
Run terraform plan again, and see that the tags_all is determined to need to be updated.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @zampettim 👋 Thank you for taking the time to raise this! Can you supply a sample Terraform configuration that can be used to reproduce the issue?

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/37346.
