### ISSUE TITLE
[Enhancement]: aws_sagemaker_domain customize user interface

### ISSUE THREAD

**Issue by jmeisele** [hashicorp/terraform-provider-aws#38240]
### Description

You can now customize the sagemaker domain user interface at either the domain level or the user profile level, this request is specifically for the aws_sagemaker_domain level. boto3 equivalent [create](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker/client/create_domain.html) & [update](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker/client/update_domain.html) command has the new argument under DefaultUserSettings 
 > StudioWebPortalSettings

This allows you to "hide" UI elements from your sagemaker domain instance.

```
        'StudioWebPortalSettings': {
            'HiddenMlTools': [
                'DataWrangler'|'FeatureStore'|'EmrClusters'|'AutoMl'|'Experiments'|'Training'|'ModelEvaluation'|'Pipelines'|'Models'|'JumpStart'|'InferenceRecommender'|'Endpoints'|'Projects',
            ],
            'HiddenAppTypes': [
                'JupyterServer'|'KernelGateway'|'DetailedProfiler'|'TensorBoard'|'CodeEditor'|'JupyterLab'|'RStudioServerPro'|'RSessionGateway'|'Canvas',
            ]
        }
```

https://docs.aws.amazon.com/sagemaker/latest/dg/studio-updated-ui-customize.html

### Affected Resource(s) and/or Data Source(s)

aws_sagemaker_domain

### Potential Terraform Configuration

```terraform
resource "aws_sagemaker_domain" "example" {
  domain_name = "example"
  auth_mode   = "IAM"
  vpc_id      = aws_vpc.example.id
  subnet_ids  = [aws_subnet.example.id]

  default_user_settings {
    execution_role = aws_iam_role.example.arn
    studio_web_portal_settings {
      hidden_ml_tools = ['DataWrangler', 'FeatureStore']
      hidden_app_types = ['Canvas', 'TensorBoard']
    }
  }
}
```

### References

[AWS Docs Here](https://docs.aws.amazon.com/sagemaker/latest/dg/studio-updated-ui-customize.html)

boto3 comparable commands here:
- [update domain](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker/client/update_domain.html)
- [create domain](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker/client/create_domain.html)

go comparable references here:
- [CreateDomain](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sagemaker#Client.CreateDomain)
-- [CreateDomainInput](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sagemaker#CreateDomainInput)
--- [UserSettings](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sagemaker@v1.149.1/types#UserSettings)
--- [StudioWebPortalSettings](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sagemaker@v1.149.1/types#StudioWebPortalSettings)

### Would you like to implement a fix?

None

**Comment by jmeisele** [comment]
Tagging @DrFaust92 since he's been so helpful with other sagemaker related terraform requests 🫶

**Comment by deepakbshetty** [comment]
For information,  Hidden App types and ML Tools feature is only available for Sagemaker studio domain and not User profile.

**Comment by jmeisele** [comment]
> For information, Hidden App types and ML Tools feature is only available for Sagemaker studio domain and not User profile.

@deepakbshetty where are you reading that?

The AWS docs show you can customize at the domain level and user profile level?
 
https://docs.aws.amazon.com/sagemaker/latest/dg/studio-updated-ui-customize.html

**Comment by deepakbshetty** [comment]
@jmeisele Apologies you are right. Might have referred to out of date docs. I will raise PR for user profile when I can

**Comment by jmeisele** [comment]
> @jmeisele Apologies you are right. Might have referred to out of date docs. I will raise PR for user profile when I can

No rush on the user profile changes, this issue I raised was _just_ for the domain resource. Regardless, thank you for taking the time to implement this enhancement 🤝
