### ISSUE TITLE
[Bug]: Unable to import existing registered domain into aws_route53domains_registered_domain

### ISSUE THREAD

**Issue by OpenSourceSteve** [hashicorp/terraform-provider-aws#38279]
### Terraform Core Version

1.9.1

### AWS Provider Version

4.67.0

### Affected Resource(s)

aws_route53domains_registered_domain

### Expected Behavior

The documentation [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53domains_registered_domain#import) (bottom of page) indicates that existing registered domains may be imported.

### Actual Behavior

When I run `terraform plan` I get the following error message:

> Planning failed. Terraform encountered an error while generating this plan.
> 
> 
> │ Error: resource aws_route53domains_registered_domain doesn't support import
> │ 
> │ 
> 

### Relevant Error/Panic Output Snippet

```shell
import {
  to = aws_route53domains_registered_domain.mydomainhere_com
  id = "mydomainhere.com"
}

resource "aws_route53domains_registered_domain" "mydomainhere_com" {
  domain_name = "mydomainhere.com"

  name_server {
    name = "ns-1654.awsdns-14.co.uk"
  }

  name_server {
    name = "ns-667.awsdns-19.net"
  }

  name_server {
    name = "ns-271.awsdns-33.com"
  }

  name_server {
    name = "ns-1271.awsdns-30.org"
  }
}

> Planning failed. Terraform encountered an error while generating this plan.
> 
> ╷
> │ Error: resource aws_route53domains_registered_domain doesn't support import
> │ 
> │ 
> ╵
```

### Terraform Configuration Files

main.tf
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.16"
    }
  }

  required_version = ">= 1.2.0"
}

route_53_registered_domains.tf
import {
  to = aws_route53domains_registered_domain.mydomainhere_com
  id = "mydomainhere.com"
}

resource "aws_route53domains_registered_domain" "mydomainhere_com" {
  domain_name = "mydomainhere.com"

  name_server {
    name = "ns-1654.awsdns-14.co.uk"
  }

  name_server {
    name = "ns-667.awsdns-19.net"
  }

  name_server {
    name = "ns-271.awsdns-33.com"
  }

  name_server {
    name = "ns-1271.awsdns-30.org"
  }
}

### Steps to Reproduce

`terraform plan`

### Important Factoids

This issue could be related to https://github.com/hashicorp/terraform-provider-aws/issues/37670

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53domains_registered_domain#import

### Would you like to implement a fix?

None

**Comment by calvinbui** [comment]
doesn't support import on your provider version https://registry.terraform.io/providers/hashicorp/aws/4.67.0/docs/resources/route53domains_registered_domain

**Comment by OpenSourceSteve** [comment]
Thank you!
