### ISSUE TITLE
[Bug]: aws_s3_bucket infinite diff when using datasource as part of the name

### ISSUE THREAD

**Issue by carlosjgp** [hashicorp/terraform-provider-aws#38303]
### Terraform Core Version

1.5.6

### AWS Provider Version

5.56.0

### Affected Resource(s)

* aws_s3_bucket

### Expected Behavior

No differences in plan or apply

### Actual Behavior

On every plan or apply we get a long list of changes related to S3 resources. Bucket, policies...

when the bucket is detected as "to be replaced" all the resources using it are also marked to be replaced

### Relevant Error/Panic Output Snippet

```console
-/+ resource "aws_s3_bucket" "pipeline" {
      + acceleration_status         = (known after apply)
      + acl                         = (known after apply)
      ~ arn                         = "arn:aws:s3:::<application>-pipeline-<region>-<account alias>" -> (known after apply)
      ~ bucket                      = "<application>-pipeline-<region>-<account alias>" # forces replacement -> (known after apply) # forces replacement
      ~ bucket_domain_name          = "<application>-pipeline-<region>-<account alias>.s3.amazonaws.com" -> (known after apply)
      + bucket_prefix               = (known after apply)
      ~ bucket_regional_domain_name = "<application>-pipeline-<region>-<account alias>.s3.eu-west-1.amazonaws.com" -> (known after apply)
      ~ hosted_zone_id              = "XXXXXXXXXXX" -> (known after apply)
      ~ id                          = "<application>-pipeline-<region>-<account alias>" -> (known after apply)
      ~ object_lock_enabled         = false -> (known after apply)
      ~ policy                      = jsonencode(
```

where

```hcl
application   = "my-app"
region        = data.aws_region.current.name
account alias = data.aws_iam_account_alias.current.account_alias
```

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket" "pipeline" {
  bucket = "myapp-pipeline-${data.aws_region.current.name}-${data.aws_iam_account_alias.current.account_alias}"

  force_destroy = true
}

resource "aws_s3_bucket_policy" "pipeline" {
  bucket = aws_s3_bucket.pipeline.id
  policy = data.aws_iam_policy_document.codepipeline_s3_policy.json
}

data "aws_iam_policy_document" "codepipeline_s3_policy" {
  statement {
    sid       = "DenyUnEncryptedObjectUploads"
    effect    = "Deny"
    resources = ["${aws_s3_bucket.pipeline.arn}/*"]
    actions   = ["s3:PutObject"]

    condition {
      test     = "StringNotEquals"
      variable = "s3:x-amz-server-side-encryption"
      values   = ["aws:kms"]
    }

    principals {
      type        = "*"
      identifiers = ["*"]
    }
  }
}

terraform {
  required_version = ">= 1.5"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.26.0"
    }
  }
}
```

### Steps to Reproduce

terraform init
terraform apply -auto-approve
terraform plan # <--- diff!?
terraform apply -auto-approve
terraform plan # <--- diff!?

### Important Factoids

I understand that the some datasources might change values on apply but in this particular case these are quite immutable

We should be able to use these in a very reliable way

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @carlosjgp 👋 Thank you for taking the time to raise this! We'd need a bit more information to determine exactly what's going on here, I suspect. Are you able to supply a complete configuration that can be used to reproduce this (containing the data source definitions as well) and/or debug logs (redacted as needed)?

**Comment by justinretzolk** [comment]
Hey @carlosjgp 👋 I wanted to check in here to see if you were able to get past this, or suspect there to be a bug with the provider. If you still suspect this to be a bug, can you provide the information I requested above?

For what it's worth, without seeing the whole configuration, my suspicion is that the issue you're seeing stems from [data resource behavior](https://developer.hashicorp.com/terraform/language/data-sources#data-resource-behavior) where reading the data source is being deferred to apply time, which is causing the the `bucket` argument to be `(known after apply)`. If it seems like that's the case, that would be a behavior controlled by Terraform Core itself, and would be behaving as expected.

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
