### ISSUE TITLE
[Bug]: `aws_security_group` is created without default rules

### ISSUE THREAD

**Issue by nikpivkin** [hashicorp/terraform-provider-aws#38315]
### Terraform Core Version

1.8.5

### AWS Provider Version

5.57.0

### Affected Resource(s)

aws_security_group

### Expected Behavior

The group will be created with default rules

### Actual Behavior

The group is created without rules

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
    }
  }

  required_version = ">= 1.2.0"
}

provider "aws" {
  region  = "us-west-1"
}

resource "aws_security_group" "this" {
  name = "test_sg"
}

```

### Steps to Reproduce

```sh
terraform init && terraform plan && terraform apply -auto-approve

aws ec2 describe-security-group-rules --filter Name=group-id,Values=<group-id>--no-cli-pager
{
    "SecurityGroupRules": []
}
```

### Important Factoids

The security group is created through CLI, CloudFormation and Console with default rules. This is also mentioned in the [documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/default-custom-security-groups.html): 
> The following are the default rules for a security group that you create:
Allows no inbound traffic
Allows all outbound traffic

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @nikpivkin 👋 Thank you for taking the time to raise this! This is the expected behavior that, while different from how the CLI works, is outlined in the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group#example-usage):

> By default, AWS creates an `ALLOW ALL` egress rule when creating a new Security Group inside of a VPC. When creating a new Security Group inside a VPC, **Terraform will remove this default rule**, and require you specifically re-create it if you desire that rule. We feel this leads to fewer surprises in terms of controlling your egress rules. If you desire this rule to be in place, you can use this `egress` block:

With that in mind, I'm going to close this issue, but if you experience unexpected behavior in the future, please do let us know!

**Comment by nikpivkin** [comment]
@justinretzolk Thanks for the explanation! My inattention.
