### ISSUE TITLE
[Bug]: AWS Inspector Enabler operation Error in Region: ap-south-1

### ISSUE THREAD

**Issue by vn2699** [hashicorp/terraform-provider-aws#38327]
### Terraform Core Version

1.9.2

### AWS Provider Version

5.57.0

### Affected Resource(s)

`resource "aws_inspector2_enabler" "enable_audit" {
  account_ids = [var.admin_account_id]
  resource_types = ["ECR", "EC2"]
  provider = aws.audit
  lifecycle {
    create_before_destroy = true
    ignore_changes = [ 
      account_ids,
      resource_types
     ]
  }`

### Expected Behavior

`Resource creation completed`

### Actual Behavior

`Error: updating AWS Inspector Enabler (*******-EC2:ECR): operation error Inspector2: Disable, https response error StatusCode: 403, RequestID: ***********************, AccessDeniedException: Lambda code scanning is not supported in ap-south-1`

### Terraform Configuration Files

```
variable "admin_account_id" {
  type = string
  default = ""
  description = "The AWS account ID of the Inspector administrator account."
}

resource "aws_inspector2_enabler" "enable_audit" {
  account_ids = [var.admin_account_id]
  # resource_types = toset(local.resource_types)
  resource_types = ["ECR", "EC2"]
  # provider = aws.audit
  lifecycle {
    create_before_destroy = true
    ignore_changes = [ 
      account_ids,
      resource_types
     ]
  }
  # depends_on = [ aws_inspector2_delegated_admin_account.audit_delegate_admin_inspector, aws_inspector2_member_association.example, aws_inspector2_organization_configuration.org_config_policy ]
}
```

### Steps to Reproduce

terraform init 
terraform plan
terraform apply

### Would you like to implement a fix?

None

**Comment by githubkannadhasan** [comment]
Hi @vn2699 there is a PR already linked to this related issue https://github.com/hashicorp/terraform-provider-aws/issues/34039
Hopefully it will be fixed soon

**Comment by vn2699** [comment]
@githubkannadhasan Thank you for the update.
