### ISSUE TITLE
[Docs]: wafv2_web_acl single_header (Required)

### ISSUE THREAD

**Issue by mBlomsterberg** [hashicorp/terraform-provider-aws#38333]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl#single_header-block

### Description

The description of single_header says that "name" is Optional, but its not. 

Needs to be updated as "Required". 

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Hi @mBlomsterberg,

I think you are right. I checked the source code for that particular field [here](https://github.com/hashicorp/terraform-provider-aws/blob/cd31961d3f059ad85e67474c1484065d899b607b/internal/service/wafv2/schemas.go#L358).

By accident I also noticed the (Optional) for the `name` attribute in the `single_query_argument` block [docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl#name) which seems also to be not in line with the code base (see  [here](https://github.com/hashicorp/terraform-provider-aws/blob/cd31961d3f059ad85e67474c1484065d899b607b/internal/service/wafv2/schemas.go#L385)).

Will provide a PR that addresses this.
