### ISSUE TITLE
[Bug]: Unexpected id from data.aws_efs_access_point when upgrading yo 5.58.0

### ISSUE THREAD

**Issue by stevebosman** [hashicorp/terraform-provider-aws#38355]
### Terraform Core Version

1.9.2

### AWS Provider Version

5.58.0

### Affected Resource(s)

data aws_efs_access_point

### Expected Behavior

expected `data.aws_efs_access_point.efs_access_point.id` to return a file system access point id, e.g. 
```
data.aws_efs_access_point.efs_access_point: Read complete after 0s [id=fsap-07b128e3adebf8abc]
```

### Actual Behavior

`data.aws_efs_access_point.efs_access_point.id` returns the file system id, e.g. 
```
data.aws_efs_access_point.efs_access_point: Read complete after 0s [id=fs-0393461db5fe53abc]
```

### Terraform Configuration Files

```
data "aws_ssm_parameter" "efs_access_point" {
  name = "foo/bar"
}

data "aws_efs_access_point" "efs_access_point" {
  access_point_id = data.aws_ssm_parameter.efs_access_point.value
}
```

### Steps to Reproduce

I don't know how to do this, it is part of a much bigger pipeline and I don't have my own AWS access

### Important Factoids

Happened on upgrade from 5.57.0 to 5.58.0

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
#### v5.57.0

https://github.com/hashicorp/terraform-provider-aws/blob/3b6772b0864505f9232f737e3d72d80f14043609/internal/service/efs/access_point_data_source.go#L125

##### v5.58.0

https://github.com/hashicorp/terraform-provider-aws/blob/5b5e52929e09bbab8bd2e23adb9b9fa2a848c49c/internal/service/efs/access_point_data_source.go#L116-L117
