### ISSUE TITLE
[Enhancement]: Add support for EKS Addon Pod Identity Associations

### ISSUE THREAD

**Issue by JoeNorth** [hashicorp/terraform-provider-aws#38357]
### Description

The EKS `CreateAddon` and `UpdateAddon` APIs have been updated to support adding a Pod Identity association to an addon using the [podIdentityAssociations](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateAddon.html#AmazonEKS-CreateAddon-request-podIdentityAssociations) parameter.

Each API accepts this parameter in the form of:

```
{
   "podIdentityAssociations": [ 
      { 
         "roleArn": "string",
         "serviceAccount": "string"
      }
   ]
}
```

### Affected Resource(s) and/or Data Source(s)

* aws_eks_addon

### Potential Terraform Configuration

```terraform
resource "aws_eks_addon" "example" {
  cluster_name           = aws_eks_cluster.example.name
  addon_name             = "vpc-cni"
  pod_identity_associations = [
    {
      roleArn = aws_iam_role.vpc_cni.arn
      serviceAccount = "aws-node"
    }
  ]
}
```

### References

CreateAddon - https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateAddon.html#AmazonEKS-CreateAddon-request-podIdentityAssociations

UpdateAddon - https://docs.aws.amazon.com/eks/latest/APIReference/API_UpdateAddon.html#AmazonEKS-UpdateAddon-request-podIdentityAssociations

### Would you like to implement a fix?

No

**Comment by bryantbiggs** [comment]
on it

**Comment by aristosvo** [comment]
@bryantbiggs I've taken a quick look as well, didn't know the best way to make up for the difference in input variables and the returned ID string in the response. Curious what the way to go is in the AWS provider for such situations!
