### ISSUE TITLE
[Docs]: resource "aws_ssm_association" "example"

### ISSUE THREAD

**Issue by Divyanshutomar27** [hashicorp/terraform-provider-aws#38362]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_association#parameters

### Description

```hcl
resource "aws_ssm_association" "example" {
  name = aws_ssm_document.example.name

  # Cron expression example
  schedule_expression = "cron(0 2 ? * SUN *)"

  # Single-run example
  # schedule_expression = "at(2020-07-07T15:55:00)"

  # Rate expression example
  # schedule_expression = "rate(7 days)"

  targets {
    key    = "InstanceIds"
    values = [aws_instance.example.id]
  }
}
```

in above block of code, target block doest work as given

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Hi @Divyanshutomar27,

could you please add more details?  
What do you see when using the target block and what is your expectation?

**Comment by justinretzolk** [comment]
Hey @Divyanshutomar27 👋 I wanted to check in here to see if you still feel the documentation needs updating. If so, can you provide a bit more detail, as requested above?
