### ISSUE TITLE
aws_autoscaling_group doesn't support timeout on create and update

### ISSUE THREAD

**Issue by pb0101** [hashicorp/terraform-provider-aws#3837]
### Terraform Version
Terraform v0.11.2

### Affected Resource(s)
- aws_autoscaling_group

### Terraform Configuration Files
```hcl
  
  timeouts {
    create = "1h"
    delete = "1h"
  }
   	
```

### Expected Behavior
The problem comes when I am using rolling updates in autoscaling group and have min_elb_capacity and create_before_destroy set. My asg is doing lot of things before it is becoming healthy and the time for boot strap is little more than 10m (which is default). So I thought of adding timeout to the auto-scaling group itself, so that it doesn't timeout while waiting for ec2 to become healthy, hoping that this will be new default timeout before terraform dies on the autoscaling group. 

### Actual Behavior
[ERR] Error decoding timeout: Timeout Key (create) is not supported

### Steps to Reproduce
1. Add timeouts in aws_autoscaling_group 
2.  terraform plan or terraform apply

**Comment by smastrorocco** [comment]
@pb0101 Are you seeing it respect the delete timeout?  We are trying to increase the delete timeout to 30m and it doesn't respect it, it just always fails after the default 10m.

**Comment by bnm22** [comment]
+1

**Comment by romero-vincent** [comment]
+1

**Comment by jdimatteo** [comment]
Is the default timeout really 10 minutes?  I got a timeout after 1 minute and 20 seconds, and the timeout error stated the timeout as 1 minute.

```
13:22:18 module.foo.aws_autoscaling_group.bar: Creating...
...
13:23:38 module.foo.aws_autoscaling_group.bar: Still creating... (1m20s elapsed)
...
13:30:05 * aws_autoscaling_group.bar: Error creating AutoScaling Group: timeout while waiting for state to become 'success' (timeout: 1m0s)
```

**Comment by DzmitrySudnik** [comment]
Got exactly the same issue as @jdimatteo (also failed after 1m20s) yesterday (in us-east-1). Maybe AWS had some issues internally which caused higher timeouts... 
Anyway, ability to specify timeout for ASG creation from the config would be helpful.
10 minutes timeout is not applied here, but for waiting for at least 1 health instance (hit it separately).
