### ISSUE TITLE
[Enhancement]: add unhealthy draining interval attribute in `aws_lb_target_group`

### ISSUE THREAD

**Issue by antonincms** [hashicorp/terraform-provider-aws#38393]
### Description

Currently in an `aws_lb_target_group` resource, it is possible to specify whether AWS should terminate unhealthy connections by setting in the block `target_health_state` the variable `enable_unhealthy_connection_termination`. 

It would be interesting to also expose the corresponding `target_health_state.unhealthy.draining_interval_seconds` attribute (probably in the same block as `unhealthy_draining_interval`) to allow specifying how long AWS should wait for in-flight requests to complete when a target becomes unhealthy.

### Affected Resource(s) and/or Data Source(s)

* aws_lb_target_group

### Potential Terraform Configuration

```terraform
resource "aws_lb_target_group" "rtmp" {
  // [...]

  target_health_state {
    enable_unhealthy_connection_termination = true
    unhealthy_draining_interval = "3600"
  }
}
```

### References

* https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health.html#unhealthy-draining-interval
* https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2@v1.33.3/types#TargetGroupAttribute

### Would you like to implement a fix?

None

**Comment by Siddarthyuvaraj** [comment]
I will work on this and raise a PR later

**Comment by Siddarthyuvaraj** [comment]
PR has been created 
https://github.com/hashicorp/terraform-provider-aws/pull/38635
