### ISSUE TITLE
[Docs]: CodePipeline Source configuration - DetectChanges

### ISSUE THREAD

**Issue by sebolabs** [hashicorp/terraform-provider-aws#38409]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codepipeline

### Description

There's that `DetectChanges` property available in the `Source` action type configuration block. One can get to know it exists by checking that action AWS docs, however, that property is considered optional.

Unfortunately, If unspecified, the default value is `true` and that has got the following consequences:
- a default trigger gets auto created for a pipeline that does not have the trigger block defined explicitly
- that default trigger cannot be removed neither with Terraform nor from AWS console
- Terraform plan keeps seeing changes to the triggers section

It makes it tricky to figure out why you get a section configured that is nowhere declared.

My life example that made me raise this issue:
- had pipelines with a Source action configured with CodeStar (GitHub) provider
- the configuration block for that action didn't have the `DetectChanges` set
- after deploying pipelines they were getting the default trigger created automatically
- TF was constantly showing changes, CloudTrail was showing there was no triggers section in the request but it was there in the response
- AWS Support couldn't replicate as they do things in the console and with AWS CLI only

I've figured it out by updating the pipeline config with AWS CLI and then re-running Terraform plan. It then revealed this:
```hcl
      ~ stage {
            name = "Source"

          ~ action {
              ~ configuration    = {
                  - "DetectChanges"    = "true" -> null
                    # (3 unchanged elements hidden)
                }
                name             = "Source"
                # (7 unchanged attributes hidden)
            }
        }
```
and that let me figure it out.

After I set `"DetectChanges" = false` and re-applied the trigger was gone and no changes were detected any more.

While I appreciate you refer in the docs to AWS docs, imo considering the default value for that property is `true` it impacts the configuration of the pipeline and makes Terraform see changes that are out of control.

Maybe it would be worth adding a note to the trigger block making people aware of that behaviour?
Up to you, am just sharing my experience.

Big up!

### References

https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CodestarConnectionSource.html#action-reference-CodestarConnectionSource-config

### Would you like to implement a fix?

None

**Comment by Jyots6914** [comment]
Hi 
I will work on it and will raise PR
