### ISSUE TITLE
[Docs]: serde attribute missing on aws_glue_classifier resource

### ISSUE THREAD

**Issue by Migrove95** [hashicorp/terraform-provider-aws#38431]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_classifier#custom_datatype_configured

### Description

As the title says, reading the releases i noticed that in the version "**v5.32.0**" the serde attribute has been added to the classifier resource. [reference](https://github.com/hashicorp/terraform-provider-aws/blob/v5.32.0/CHANGELOG.md)
However in the latest documentation (and previous aswell), the attribute is missing and not usable.

### References

I also referenced the issue [#33787](https://github.com/hashicorp/terraform-provider-aws/issues/33787), seeing that the upgrade has been done with success.

### Would you like to implement a fix?

No

**Comment by stefanfreitag** [comment]
Hi @Migrove95,

I checked the provider code and it looks like `serde`  is availble [here](https://github.com/hashicorp/terraform-provider-aws/blob/c70f0c66d9a9f800f34c4162abc41ac82655efd9/internal/service/glue/classifier.go#L125).
Let me try to come up with a PR for the documentation.
