### ISSUE TITLE
[Docs]: sns_topic_subscription docs miss an important note.

### ISSUE THREAD

**Issue by hernanc** [hashicorp/terraform-provider-aws#38441]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_topic_subscription#protocol-support

### Description

The only supported protocol for FIFO topics is SQS at the moment.

If you try to create an SMS (or any other but SQS) subscription to a FIFO Topic. You'll get an `Invalid parameter: Invalid protocol type: sms` error:
```
│ Error: creating SNS Topic Subscription: operation error SNS: Subscribe, https response error StatusCode: 400, RequestID: e2796c16-9a9d-52f6-a735-33027fb4353c, InvalidParameter: Invalid parameter: Invalid protocol type: sms
│
│   with module.synthetic_canary.aws_sns_topic_subscription.topic_email_sub,
│   on ./main.tf line 124, in resource "aws_sns_topic_subscription" "topic_email_sub":
│  124: resource "aws_sns_topic_subscription" "topic_email_sub" {
```

### References

If you go to the AWS console and try to create an SNS subscription:
https://us-east-1.console.aws.amazon.com/sns/v3/home?region=us-east-1#/create-topic

You'll be presented with this choice, where the supported protocols for each are mentioned:
![Screenshot 2024-07-19 at 7 16 49 PM](https://github.com/user-attachments/assets/68cab18f-23f4-4e73-a05d-855fbe4ee7ea)

### Would you like to implement a fix?

No

**Comment by stefanfreitag** [comment]
The official AWS documentation is available [here](https://docs.aws.amazon.com/sns/latest/dg/fifo-message-delivery.html).
Quoting:
> Amazon SNS FIFO (first in, first out) topics support delivery to both Amazon SQS standard and FIFO queues to provide customers with flexibility and control when integrating distributed applications that require data consistency in near real-time. [...] SNS FIFO topics can't deliver messages to customer managed endpoints, such as email addresses, mobile apps, phone numbers for text messaging (SMS), or HTTP(S) endpoints.
