### ISSUE TITLE
[Enhancement]: Change TF behavior to complete operation of create / update RDS Clusters and Instances faster   

### ISSUE THREAD

**Issue by pthawley** [hashicorp/terraform-provider-aws#38497]
### Description

When creating or adding new clusters or database instances in RDS and Aurora. the instance is available for use during the "Storage-optimization" phase.  See the public AWS documentation [here ](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/accessing-monitoring.html#Overview.DBInstance.Status) and the AWS Knowledge Center article [here](https://repost.aws/knowledge-center/rds-stuck-in-storage-optimization). 

Therefore, the TF operations that create or modify these resources should complete when the target state is either "Available" or "Storage-optimization".

Today, in there cases where the "Storage-optimization" phase is taking a long time, one of several possibilities could occur.  Either the operation takes significantly more time than is actually needed or, in some extreme cases, it is possible that operation times out and fails.  Neither is a good experience.  

I am not really familiar with Terraform or the AWS Provider code but in looking at the wait.go file [here](https://github.com/hashicorp/terraform-provider-aws/blob/e9c3c952a6433442409b23ea33fd28055099198f/internal/service/rds/wait.go#L149), both the **waitDBClusterInstanceCreated** and **waitDBClusterInstanceUpdated** functions both view InstanceStatusStorageOptimization as a "Pending" state.  

I was originally going to call this a bug and not an enhancement request but I don't have all of the information to create a reproducible test case.  In the interest of getting this into the system faster, as well as the recognition that the existing code has been in place for a long time, please consider this hopefully small change.

### Affected Resource(s) and/or Data Source(s)

Resource: aws_rds_cluster
Resource: aws_rds_cluster_instance

### References

See the public AWS documentation [here ](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/accessing-monitoring.html#Overview.DBInstance.Status) and the AWS Knowledge Center article [here](https://repost.aws/knowledge-center/rds-stuck-in-storage-optimization). 

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/6455.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/21900.
