### ISSUE TITLE
[Enhancement]: Allow VPN Telemetry Lifecycle Ignore_Changes

### ISSUE THREAD

**Issue by dvmrry** [hashicorp/terraform-provider-aws#38494]
### Description

When attempting to use a lifecycle block to ignore changes on `vgw_telemetry` it appears to be ignored with the following message:

> Adding an attribute name to ignore_changes tells Terraform to ignore future changes to the argument in configuration after the object has
> been created, retaining the value originally configured.
> 
> The attribute vgw_telemetry is decided by the provider alone and therefore there can be no configured value to compare with. Including this attribute

Not being able to ignore these changes makes simple plans much more cumbersome to read.

I have attempted to use various combinations of different Terraform and AWS provider versions with no success.

### Affected Resource(s) and/or Data Source(s)

aws_vpn_connection

### Potential Terraform Configuration

```terraform
lifecycle {
    ignore_changes = [
      vgw_telemetry,
    ]
  }
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @dvmrry 👋 Thank you for taking the time to raise this! Ultimately, this is a Terraform Core behavior, and not something that the AWS Provider team would be able to make changes to prevent. I found a really insightful thread about this on our Discuss forum ([linked here](https://discuss.hashicorp.com/t/ignore-changes-warning/44572/2)) where some of the engineers on the Terraform Core team discuss this a bit more.

With that in mind, I'm going to close this issue, but if you run into unexpected behavior in the future, please do let us know!
