### ISSUE TITLE
Provider produced inconsistent final plan in v5.59.0 for aws_ecs_task_definition[Bug]: 

### ISSUE THREAD

**Issue by pcappaert** [hashicorp/terraform-provider-aws#38522]
### Terraform Core Version

1.9.2

### AWS Provider Version

5.59.0

### Affected Resource(s)

aws_ecs_task_definition

### Expected Behavior

Terraform should be able to apply the plan that contains a task definition that uses a secrets manager secret arn that is not known until apply time

### Actual Behavior

the plan works but the apply is not able to use the updated value

### Relevant Error/Panic Output Snippet

```shell
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.my_service.aws_ecs_task_definition.service_task_definition
│ to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .container_definitions: was cty.StringVal(""), but now
│ cty.StringVal("[~container definitions removed~]").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

### Terraform Configuration Files

  container_definitions = <<TASK_DEFINITION
[
  {
    "name": "${var.primary_container_name}",
    "image": "${var.image_uri}",
    "cpu": 256,
    "memory": 512,
    "essential": true,
    "environment": ${var.ecs_task_definition_variables},
    "secrets" : ${var.ecs_task_definition_secret_variables},
    "portMappings": [
        {
          "name": "userservice-api",
          "protocol": "tcp",
          "appProtocol": "http",
          "containerPort": 8080
        }
      ],
    "logConfiguration": {
      "logDriver": "awslogs",
      "options": {
        "awslogs-region": "${var.aws_region}",
        "awslogs-group": "logs-${var.ecs_service_name}",
        "awslogs-stream-prefix": "ecs-service"
      }
    }
  }
]
TASK_DEFINITION

### Steps to Reproduce

create a configuration with an ecs task definition that contains secrets with references to a secret arn that is not known at plan time for the configuration and this issue will happen during the apply. It does not happen on subsequent applies when the secret is created and thus known at plan time.

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@pcappaert Thanks for raising this issue.
It has already been noticed in #38461. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
