### ISSUE TITLE
[Bug]: registry.opentofu.org/hashicorp/aws" produced an invalid new value for .last_modified: was known, but now unknown.

### ISSUE THREAD

**Issue by ReXtrem** [hashicorp/terraform-provider-aws#38533]
### Terraform Core Version

1.7.2

### AWS Provider Version

5.58.0

### Affected Resource(s)

```
output "lambda_function_last_modified" {
  description = "The date Lambda Function resource was last modified"
  value       = try(aws_lambda_function.main[0].last_modified, "")
}
```

### Expected Behavior

tofu apply runs through.

### Actual Behavior

tofu apply fails with: 

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.XXX.aws_lambda_function.main[0]
│ to include new values learned so far during apply, provider
│ "registry.opentofu.org/hashicorp/aws" produced an invalid new value for
│ .last_modified: was known, but now unknown.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
```

### Terraform Configuration Files

```
terraform {
  required_version = ">= 1.7.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "= 5.58.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.6.2"
    }
  }
}
```

### Steps to Reproduce

tofu apply

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @ReXtrem 👋 Can you supply a sample configuration that can be used to reproduce this? Debug logging (redacted as needed) may also help whoever ultimately picks this issue up to look into it, if you're able to supply them. I don't suspect this will make too much of a difference, but can you also attempt to reproduce this using Terraform and the HashiCorp AWS provider, to eliminate any possibility of a discrepancy there?

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.

**Comment by etwillbefine** [comment]
In my case I have a Lambda Function deployed with an S3 Object as source. When the Lambda Function Code was updated from the AWS Lambda Console an update to the Lambda Function using Terraform (new `s3_object_version`) fails afterwards due to "last_modified" (see error in issue description).
