### ISSUE TITLE
[Bug]: data "aws_appstream_image" returns the oldest image

### ISSUE THREAD

**Issue by sergey-mz** [hashicorp/terraform-provider-aws#38561]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.60.0

### Affected Resource(s)

data "aws_appstream_image" "test" {
  name_regex  = "test.+"
  type        = "PRIVATE"
  most_recent = true
}

### Expected Behavior

Return the latest image matching the pattern

### Actual Behavior

Returns the oldest image matching the pattern

### Terraform Configuration Files

data "aws_appstream_image" "test" {
  name_regex  = "test.+"
  type        = "PRIVATE"
  most_recent = true
}

### Steps to Reproduce

Add above data source in account having several private images.

### Would you like to implement a fix?

None

**Comment by acwwat** [comment]
Not sure why but the code was comparing only the month of the create timestamp, which is not precise enough. I've submitted a PR to fix it.
