### ISSUE TITLE
[Enhancement]: Add automatic flag as part of indexing_policy in azurerm_cosmosdb_sql_container

### ISSUE THREAD

**Issue by devtechcloud** [hashicorp/terraform-provider-aws#38582]
### Description

There is currently no Terraform option to set the "automatic" flag to true or flase, as part of an indexing_policy.

When using a Cosmos DB Container within the portal, within the indexing policy an option to set "automatic" as true or false appears, however this is not available via Terraform module azurerm_cosmosdb_sql_container

### Potential Terraform Configuration

```terraform
resource "azurerm_cosmosdb_sql_container" "cosmos_container" {
  name                   = "example"
  resource_group_name    = data.azurerm_cosmosdb_account.cosmos_account.resource_group_name
  account_name           = data.azurerm_cosmosdb_account.cosmos_account.name
  database_name          = azurerm_cosmosdb_sql_database.cosmos_database.name
  partition_key_path     = "/Example"
  partition_key_version  = 1
  analytical_storage_ttl = -1

  indexing_policy {
    indexing_mode = "consistent"
    automatic     = "false"
    included_path {
      path = "/TestId/*"
    }
    excluded_path {
      path = "/*"
    }
  }
}
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @devtechcloud  👋 Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the AWS Provider. For issues with the AzureRM provider, you'll need to open an issue in the [AzureRM provider repository](https://github.com/hashicorp/terraform-provider-azurerm). With that in mind, I'm going to close this issue.
