### ISSUE TITLE
[Docs]: aws_instance: Spot instance example is not complete and is missing required market_type argument

### ISSUE THREAD

**Issue by gmadro** [hashicorp/terraform-provider-aws#38588]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance

### Description

The example in the documentation for and aws_instnance: Spot instance example is as follows:

```
data "aws_ami" "this" {
  most_recent = true
  owners      = ["amazon"]
  filter {
    name   = "architecture"
    values = ["arm64"]
  }
  filter {
    name   = "name"
    values = ["al2023-ami-2023*"]
  }
}

resource "aws_instance" "this" {
  ami = data.aws_ami.this.id
  instance_market_options {
    spot_options {
      max_price = 0.0031
    }
  }
  instance_type = "t4g.nano"
  tags = {
    Name = "test-spot"
  }
}
```

But it will produce the following error:

>Error: creating EC2 Instance: operation error EC2: RunInstances, https response error StatusCode: 400, RequestID: f71af8ea-4b73-426e-b338-371a516c84b6, api error MissingParameter: The request must contain the parameter MarketType.

### References

As specified in the documentation here: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#market-options

>The instance_market_options block supports the following:
>[market_type](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#market_type) - (Optional) >Type of market for the instance. Valid value is spot. Defaults to spot. Required if spot_options is specified.

### Would you like to implement a fix?

Yes

**Comment by Jyots6914** [comment]
I will work on it and will raise PR
