### ISSUE TITLE
[Enhancement]: Add support for additional Batch EKS Pod Properties

### ISSUE THREAD

**Issue by danquack** [hashicorp/terraform-provider-aws#38606]
### Description

Some additional attributes were added to eksProperties:

- initContainers
- shareProcessNamespace

### Affected Resource(s) and/or Data Source(s)

aws_batch_job_definition

### Potential Terraform Configuration

```terraform

resource "aws_batch_job_definition" "test" {
  name = "tf_test_batch_job_definition_eks"
  type = "container"
  eks_properties {
    pod_properties {
      host_network = true
      init_containers {
        image = "public.ecr.aws/amazonlinux/amazonlinux:1"
        command = [
          "sleep",
          "60"
        ]
        resources {
          limits = {
            cpu    = "1"
            memory = "1024Mi"
          }
        }
      }
      // More properties removed
    }
  }
}

```

### References

https://docs.aws.amazon.com/batch/latest/APIReference/API_EksPodProperties.html

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @danquack 👋 Heads up: unless I'm misunderstanding, looks like `image_pull_secret`, at least, was included in 5.60.0 via https://github.com/hashicorp/terraform-provider-aws/pull/38517.
