### ISSUE TITLE
Add ShareDBSnapshot for aws_db_snapshot resource to allow sharing between aws accounts

### ISSUE THREAD

**Issue by gaurav-fk** [hashicorp/terraform-provider-aws#3860]
Allow a db snapshot to be shared with other aws accounts.

**Comment by feraudet** [comment]
+1

**Comment by lnozot** [comment]
+1

Needing the ability to share encrypted snapshots with another account.  Need the ability to execute the terraform plan and creating the snapshot and export it for use on the other account.

**Comment by ssala7** [comment]
+1

**Comment by greystitch** [comment]
+1. Must have feature for multi-account management

**Comment by BenLeibig** [comment]
@greystitch You can build multi-provider modules to take care of multi-account management if you can share snapshots.

We just need the ability to share a snapshot with another account.

**Comment by BenLeibig** [comment]
+1

**Comment by d4n13lbc** [comment]
+1

**Comment by ShubhashriSinha** [comment]
> Allow a db snapshot to be shared with other aws accounts.

+1

**Comment by Lupunita** [comment]
+1

**Comment by nikhilnilawar-deliveroo** [comment]
+1

**Comment by DrFaust92** [comment]
ill take a look
