### ISSUE TITLE
Data Source for aws_kinesis_firehose_delivery_stream

### ISSUE THREAD

**Issue by bacoboy** [hashicorp/terraform-provider-aws#3865]
It would be helpful to have a way to lookup an `aws_kinesis_firehose_delivery_stream` by name to get the ARN and other attributes.  Usually Data Sources are used for this, but it seems to have been left out of the original implementation.

Side note: I'd argue that most new resources should probably have corresponding data sources made at time they are added to this provider.  Just saying...

**Comment by bacoboy** [comment]
Almost another year lapsed here.  Anybody want to take a crack at this?

**Comment by bacoboy** [comment]
Happy 2 year anniversary to this issue! 🥈

**Comment by querry43** [comment]
I too need a way to lookup existing resources.  Our common infrastructure is in one terraform and the apps themselves in another.  I would like to reference the arn of a firehose from common infra in the app configs where cloudfront and waf are configured.

**Comment by theherk** [comment]
Happy 3rd anniversary. :) It looks like this will be pretty straight forward, so I'll make an attempt within the next few days.

**Comment by robotdan** [comment]
Is the AWS Terraform module still under development? It looks like a PR has been submitted. Do we just need someone to review and merge the PR?
