### ISSUE TITLE
[Bug]: blue_green_update{enabled = true} is unable to enable the blue green deployment for AWS RDS aws_db_instance

### ISSUE THREAD

**Issue by pvshingala1997** [hashicorp/terraform-provider-aws#38656]
### Terraform Core Version

1.3.8

### AWS Provider Version

5.60.0

### Affected Resource(s)

AWS RDS Instance

### Expected Behavior

It should start indicating blue green deployment for AWS RDS

### Actual Behavior

Only State file is getting uptodate with changes and nothing change noticed on AWS console.

### Relevant Error/Panic Output Snippet

```shell
N/A
```

### Terraform Configuration Files

blue_green_update {
    enabled = true
  }

### Steps to Reproduce

Please add the below block to aws mysql RDS instance terraform configuration
blue_green_update {
    enabled = var.blue_green_update
  }

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @pvshingala1997 👋 Thank you for taking the time to raise this! Can you verify what you have set for the [`apply_immediately` argument](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#apply_immediately)? It may be that the change won't reflect until the next maintenance window based on this setting. 

If that doesn't appear to be the issue, can you supply a sample Terraform configuration that can be used to reproduce the issue? Whoever ultimately looks into this will need enough information to reproduce the issue. Debug logging (redacted as needed) is often helpful for the same reason.

**Comment by pvshingala1997** [comment]
Hi @justinretzolk ,
That flag was not set. But again we kind of rebooted the server but still it dint went through we had to do it manually.
Due to restrictions at my end for sharing a code, i would appriciate if you consider adding below block to rds instance configuration.
blue_green_update {
enabled = true
}

**Comment by justinretzolk** [comment]
@pvshingala1997,

Given that you're not able to supply logging or a sample configuration, can you provide steps to reproduce the issue? I'm imagining something to the effect of:

- Added `apply_immediately = true` to configuration
- Ran `terraform apply`
- ...

> Due to restrictions at my end for sharing a code, i would appriciate if you consider adding below block to rds instance configuration.
blue_green_update {
enabled = true
}

I'm not certain I follow your request here, unfortunately. The `aws_db_instance` resource currently [has a `blue_green_update` block](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#blue_green_update) as an argument.

**Comment by justinretzolk** [comment]
Hey @pvshingala1997 👋 After further review, I'm going to consolidate our conversations to #38733 so that they're not spread out between this issue, that one, and #38734. They're all addressing the same thing, and I don't want to cause undue confusion.
