### ISSUE TITLE
[Enhancement]: Allow `data.aws_s3_object` to fetch body for non-human-readable objects

### ISSUE THREAD

**Issue by lijok** [hashicorp/terraform-provider-aws#38664]
### Description

Our devs publish build artifacts to an S3 bucket which we want to retrieve the artifacts from and upload them to another S3 bucket to serve via a CDN.
Because the artifacts are not human readable, `data.aws_s3_object` refuses to fetch the body, so we can't chain it to `resource.aws_s3_object`, to load it to the CDN

### Affected Resource(s) and/or Data Source(s)

- aws_s3_object

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @lijok 👋 Thank you for taking the time to raise this! While I don't have all of the context, given that we mention this limitation in the documentation, I suspect it was carefully considered and is unlikely to change. That said, while looking at the documentation, I noticed the [`aws_s3_object_copy` resource](https://registry.terraform.io/providers/-/aws/latest/docs/resources/s3_object_copy) that seems like it might accomplish the same task. Can you review that resource to see if it might help?

**Comment by lijok** [comment]
> Hey @lijok 👋 Thank you for taking the time to raise this! While I don't have all of the context, given that we mention this limitation in the documentation, I suspect it was carefully considered and is unlikely to change. That said, while looking at the documentation, I noticed the [`aws_s3_object_copy` resource](https://registry.terraform.io/providers/-/aws/latest/docs/resources/s3_object_copy) that seems like it might accomplish the same task. Can you review that resource to see if it might help?

I'll test it out - my understanding is objects can't be natively copied between AWS accounts.
I would imagine `data.aws_s3_object` was designed to be safe, but surely that should be overridable via a flag.
Thanks for looking into this !

**Comment by justinretzolk** [comment]
Hey @lijok 👋 Were you able to verify whether `aws_s3_object_copy` worked for what you needed?
