### ISSUE TITLE
[Docs]: aws_api_gateway_api_key - customer_id says it's required, when it isn't.

### ISSUE THREAD

**Issue by KanchiMoe** [hashicorp/terraform-provider-aws#38697]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_api_key

### Description

The current documentation says

> `customer_id` - (Required) An Amazon Web Services Marketplace customer identifier, when integrating with the Amazon Web Services SaaS Marketplace.

However, this isn't actually the case. It is possible to create an api key without a customer ID being defined.

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Hi @KanchiMoe 

I see it in the [source code](https://github.com/hashicorp/terraform-provider-aws/blob/cbb9d342ba9f3a3bd08235c612abaa838eed05d4/internal/service/apigateway/api_key.go#L52) also marked as "Optional". Will verify again tomorrow and prepare a PR for this.

Thanks for raising this issue,
Stefan
