### ISSUE TITLE
[Docs]: aws_guardduty_malware_protection_plan role argument reference should specify that it requires a role ARN

### ISSUE THREAD

**Issue by kxgillispie** [hashicorp/terraform-provider-aws#38719]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_malware_protection_plan#role

### Description

Documentation for resource `aws_guardduty_malware_protection_plan`'s argument `role` says only:
> The IAM role that includes the permissions required to scan and add tags to the associated protected resource.

Based on both the code example from the same link (which specifies `role = aws_iam_role.example.arn`), and errors we've received when attempting to use a role name instead (detailed below), it seems that this argument specifically requires an ARN; it would be helpful if the documentation was updated accordingly.

===

Additionally, it seems that the URL fragment for that `role` attribute doesn't function as expected; when clicking on the attribute name the fragment is added to the URL displayed in the browser, but attempting to navigate to that URL directly does not result in the view being scrolled to it (as it does with other fragment URLs from that same page, like for the `tags` attribute: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_malware_protection_plan#tags).

===

Error from attempting to use role name for this argument instead of ARN:
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/hashicorp/aws" planned an invalid value for
│ aws_guardduty_malware_protection_plan.protection_plan.role: planned value
│ cty.UnknownVal(cty.String) does not match config value
│ cty.StringVal("GuardDutyMalwareProtectionRole").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
Operation failed: failed running terraform plan (exit 1)
```

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Hi @kxgillispie,

let me look into this.

- The ARN details should be easy to add.
- On the URL fragment issue you reported I noticed a missing "name" in the `a href`.

![image](https://github.com/user-attachments/assets/f287a15d-1852-4545-b9e0-b42c10d67f84)
