### ISSUE TITLE
[Docs]: aws_lb_listener NLB TLS example should have ssl_policy

### ISSUE THREAD

**Issue by bhardwick** [hashicorp/terraform-provider-aws#38715]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/5.61.0/docs/resources/lb_listener

### Description

The documentation gives an NLB example:
```
resource "aws_lb_listener" "front_end" {
  load_balancer_arn = aws_lb.front_end.arn
  port              = "443"
  protocol          = "TLS"
  certificate_arn   = "arn:aws:iam::187416307283:server-certificate/test_cert_rab3wuqwgja25ct3n4jdj2tzu4"
  alpn_policy       = "HTTP2Preferred"

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.front_end.arn
  }
}
```

However, the documentation states:
> [ssl_policy](https://registry.terraform.io/providers/hashicorp/aws/5.61.0/docs/resources/lb_listener#ssl_policy) - (Optional) Name of the SSL Policy for the listener. Required if protocol is HTTPS or TLS.

The example should reflect the required field when using `TLS`.

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Hi @bhardwick,

I can update the documentation for the network loadbalancer use case.

We could go with the policy `ELBSecurityPolicy-2016-08` already used in the [first example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener#forward-action) or 
with e.g. `ELBSecurityPolicy-TLS13-1-2-2021-06`. 

There seems to be a difference on the "default"  policy when using either the AWS Management Console or the CLI. Details can be found [here](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/create-tls-listener.html):

> The ELBSecurityPolicy-TLS13-1-2-2021-06 policy is the default security policy for TLS listeners created using the AWS Management Console. [...]
> The ELBSecurityPolicy-2016-08 policy is the default security policy for TLS listeners created using the AWS CLI.

**Comment by bhardwick** [comment]
@stefanfreitag Perhaps the defaulting is working on the latest version but it is not on the version we are using (and the version of the docs we were looking at). If defaulting is automatic now, thank you for clarifying in the documentation.
