### ISSUE TITLE
[Enhancement]: Create a seperate resource block for handling RDS blue/green deployment as aws_db_instance resource do not provide a realtime operational feature for RDS Blue/Green Deployment

### ISSUE THREAD

**Issue by pvshingala1997** [hashicorp/terraform-provider-aws#38734]
### Description

blue_green_update{enabled = true} is unable to enable the blue green deployment for AWS RDS aws_db_instance

### Affected Resource(s) and/or Data Source(s)

aws_db_instance

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment]
Hey @pvshingala1997 👋 Thank you for taking the time to raise this! This seems related to your other issue (#38733), where you'd linked to our [design decisions around Blue/Green deployments](https://hashicorp.github.io/terraform-provider-aws/design-decisions/rds-bluegreen-deployments/). A couple of specific quotes from that document that feel related:

> Due to Terraform's resource model and how RDS implements Blue/Green Deployments, support for Blue/Green Deployments cannot be extended to other resource types.

...and (perhaps more relevant to your interests):

> The update takes place in a single `terraform apply`, and the Blue/Green Deployment object is not exposed by the provider, since it is only an implementation detail.

With those things in mind, can you provide a bit more information as to what additional configuration options you'd like to see added to the provider with regards to blue/green deployments?

**Comment by pvshingala1997** [comment]
@justinretzolk simillar to https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/design-decisions/rds-bluegreen-deployments.md
can work for triggering,switchover and rollback

**Comment by justinretzolk** [comment]
Hey @pvshingala1997 👋 After further review, I'm going to consolidate our conversations to #38733 so that they're not spread out between this issue, that one, and #38656. They're all addressing the same thing, and I don't want to cause undue confusion.
