### ISSUE TITLE
[Enhancement]: Add resources to configure IAM Identity Center and manage provisioning

### ISSUE THREAD

**Issue by Sirz3chs** [hashicorp/terraform-provider-aws#38736]
### Description

As there are already `aws_identitystore_` resources to manage users and groups as well as `aws_ssoadmin_` resources to manage permissions, it would be practical to have resources to enable and configure IAM Identity Center.

In particular, it would be useful to have a resource to manage the rotation of access tokens for external identity providers.

### Potential Terraform Configuration

```terraform
resource "aws_identitystore" "example" {
  instance_name           = "foo"
  identity_aware_sessions = false
  session_duration        = 3600
}

###
# Identity Center directory
resource "aws_identitystore_directory_identity_source" "this" {
  identity_store_id = aws_identitystore.example.id
}

# OR
# Active Directory (managed by AWS or not)
resource "aws_directory_service_directory" "example" {
  name     = "corp.notexample.com"
  password = "SuperSecretPassw0rd"
  size     = "Small"
}

resource "aws_identitystore_active_directory_identity_source" "this" {
  identity_store_id = aws_identitystore.example.id
  directory_id      = aws_directory_service_directory.example.id
}

# OR
# External identity provider
data "aws_identitystore_metadata" "example" {
  identity_store_id = aws_identitystore.example.id
}

resource "some_other_idp" "this" {
  metadata = aws_identitystore.example.metadata # data.aws_identitystore_metadata.example.metadata
}

resource "aws_identitystore_idp_identity_source" "this" {
  identity_store_id = aws_identitystore.example.id

  metadata = some_other_idp.this.metadata
  # OR
  sign_in_url = some_other_idp.this.sign_in_url
  issuer_url  = some_other_idp.this.issuer_url
  certificate = some_other_idp.this.certificate
}
###

data "aws_identitystore_provisioning_endpoint" "example" {
  identity_store_id = aws_identitystore.example.id
}

resource "aws_identitystore_provisioning_acces_token" "example" {
  identity_store_id = aws_identitystore.example.id
}
```

### References

I've followed this documentation to setup Microsoft Entra as identity provider
https://docs.aws.amazon.com/singlesignon/latest/userguide/idp-microsoft-entra.html
https://docs.aws.amazon.com/singlesignon/latest/userguide/provision-automatically.html

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @Sirz3chs 👋 Thank you for taking the time to raise this! I took a look, and it doesn't appear there's any API endpoints for what you're looking for. On the [IAM Identity Center API documentation](https://docs.aws.amazon.com/singlesignon/latest/APIReference/welcome.html), it says:

> **Note**
> IAM Identity Center uses the `sso` and `identitystore` API namespaces.

With that in mind, I'm going to close this request, but if you have any additional requests in the future, please do let us know!
