### ISSUE TITLE
[Bug]: Support for 32-bit ASN for VPN Customer Gateway

### ISSUE THREAD

**Issue by JihedTounsiTR** [hashicorp/terraform-provider-aws#38738]
### Terraform Core Version

1.9.3

### AWS Provider Version

5.60.0

### Affected Resource(s)

```hcl
resource "aws_customer_gateway" "usw2_cgw" {
  bgp_asn    = "4200000010"
  ip_address = "15.197.196.253"
  type       = "ipsec.1"
```

### Expected Behavior

Create a customer gateway

### Actual Behavior

Deployment breaks with an error

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: strconv.ParseInt: parsing "4200000010": value out of range
│ 
│   with aws_customer_gateway.usw2_cgw,
│   on main.tf line 11, in resource "aws_customer_gateway" "usw2_cgw":
│   11: resource "aws_customer_gateway" "usw2_cgw" {
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 1.9.3"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.60.0"
    }
  }
}

provider "aws" {
  region = "us-west-2"
  alias  = "usw2"
}

resource "aws_customer_gateway" "usw2_cgw" {
  provider   = aws.usw2
  bgp_asn    = "4200000010"
  ip_address = "15.197.196.253"
  type       = "ipsec.1"
}
```

### Steps to Reproduce

```
terraform init
```
```
terraform apply -auto-approve
```

### Debug Output

2024-08-07T07:36:47.980-0400 [ERROR] vertex "aws_customer_gateway.usw2_cgw" error: strconv.ParseInt: parsing "4200000010": value out of range
╷
│ Error: strconv.ParseInt: parsing "4200000010": value out of range
│ 
│   with aws_customer_gateway.usw2_cgw,
│   on main.tf line 11, in resource "aws_customer_gateway" "usw2_cgw":
│   11: resource "aws_customer_gateway" "usw2_cgw" {
│ 
╵
2024-08-07T07:36:47.994-0400 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2024-08-07T07:36:47.998-0400 [INFO]  provider: plugin process exited: plugin=.terraform/providers/registry.terraform.io/hashicorp/aws/5.60.0/darwin_arm64/terraform-provider-aws_v5.60.0_x5 id=53804
2024-08-07T07:36:47.998-0400 [DEBUG] provider: plugin exited

### Would you like to implement a fix?

None

**Comment by drewtul** [comment]
You must set `bgp_asn_extended` instead of `bgp_asn` for values this large.

**Comment by JihedTounsiTR** [comment]
thank you.
