### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by toneill818** [hashicorp/terraform-provider-aws#38749]
### Description

Add support for blue green deployments for rds clusters. 

### Affected Resource(s) and/or Data Source(s)

aws_rds_cluster

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @toneill818 👋 Thank you for your interest in this! While this is a common request, unfortunately, it isn't something we're able to move forward with at this time, and have written [a design document](https://hashicorp.github.io/terraform-provider-aws/design-decisions/rds-bluegreen-deployments/#rds-bluegreen-deployments) outlining our reasoning. With that in mind, I'm going to close this issue. If you have future requests for the provider, please do let us know!
