### ISSUE TITLE
[New Resource]: Support for AWS Backup "logically air-gapped vault"

### ISSUE THREAD

**Issue by rymancl** [hashicorp/terraform-provider-aws#38768]
### Description

Announcement from AWS: https://aws.amazon.com/about-aws/whats-new/2024/08/general-availability-aws-backup-logically-air-gapped-vault/

Dev Guide: https://docs.aws.amazon.com/aws-backup/latest/devguide/logicallyairgappedvault.html

Blog Post: https://aws.amazon.com/blogs/storage/building-cyber-resiliency-with-aws-backup-logically-air-gapped-vault/

### Requested Resource(s) and/or Data Source(s)

* aws_lag_backup_vault
  * Note: Requesting this as a new resource/data-source as opposed to enhancement to `aws_backup_vault` as it uses a separate API to create. If you all disagree, feel free to alter.

### Potential Terraform Configuration

```terraform
resource "aws_lag_backup_vault" "example" {
  name = "example_lag_backup_vault"
}
```

### References

AWS CLI [Create]: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/backup/create-logically-air-gapped-backup-vault.html

Go SDK [Create]: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/backup#Client.CreateLogicallyAirGappedBackupVault

Looks like there is no special API for [Delete] and it used the standard `DeleteBackupVault`: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/backup#Client.DeleteBackupVault

### Would you like to implement a fix?

No

**Comment by aristosvo** [comment]
I would like to implement this. But hey, open to any kind of collaboration! 💪
