### ISSUE TITLE
[Enhancement]: Automatically set Name tag, for all resources

### ISSUE THREAD

**Issue by x1um1n** [hashicorp/terraform-provider-aws#38764]
### Description

With most tags being set at the provider, the most commonly remaining tag set on each resource is `Name`.  A lot of resources have a name property & some resources automatically set a matching tag, however most don't.

It would save a lot of unnecessary code if the provider could simply set a tag like `Name = this.name` automatically.  If a custom `Name` tag needed to be set, it could be overridden in the resource. 

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @x1um1n 👋 Thank you for taking the time to raise this! I absolutely see the utility in a request like this, particularly for a tag as relatively innocuous as `Name`. That said, one of the [provider design principles](https://developer.hashicorp.com/terraform/plugin/best-practices/hashicorp-provider-design-principles#resource-and-attribute-schema-should-closely-match-the-underlying-api) is to match the underlying API as closely as possible. This ensures that Terraform operates in a predictable manner, and doesn't impose its own opinionated methods that would make it harder to migrate to or away from.

If there are resources that add the `Name` tag natively when creating them via that API, and the provider is currently omitting that tag, we'd definitely want to take a look into that on a case by case basis. As far as adding the `Name` tag to every resource that will accept it, no matter the configuration, we won't be able to accommodate that at this time, so I'm going to close this issue. If you have any additional feature requests, or feedback for us in the future, please do let us know!
