### ISSUE TITLE
[Docs]: While ingestigating Issue/33383 i noticed the system_log_level documentation doesnt match available provider options

### ISSUE THREAD

**Issue by aidenvaines-bjss** [hashicorp/terraform-provider-aws#38789]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function

### Description

While ingestigating [Issue/33383](https://github.com/hashicorp/terraform-provider-aws/issues/33383) i noticed the system_log_level documentation doesn't match available provider options.

[The documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function) states
> [system_log_level](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#system_log_level) - (optional) for JSON structured logs, choose the detail level of the Lambda platform event logs sent to CloudWatch, such as ERROR, DEBUG, or INFO.

At apply time you will see this error when setting `logging_config{system_log_level)` to `"ERROR"`
```
Error: expected system_log_level to be one of ["DEBUG" "INFO" "WARN"], got ERROR
```

### Would you like to implement a fix?

Yes

**Comment by network-charles** [comment]
The issue may be in the implementation of the resource. According to the official [AWS documentation](https://docs.aws.amazon.com/lambda/latest/dg/monitoring-cloudwatchlogs-advanced.html) the Terraform documentation is correct.
