### ISSUE TITLE
[Docs]: `aws_mq_broker` attribute `instances.0.ip_address` not available while using RabbitMQ broker

### ISSUE THREAD

**Issue by edner-liber** [hashicorp/terraform-provider-aws#38807]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mq_broker#instances.0.ip_address

### Description

When using the `engine_type` = `RabbitMQ` option in the `aws_mq_broker` resource, the `instances.0.ip_address` attribute returns an empty string, expected behavior when this attribute is not available in the AWS API, according to the source code of this provider.

Looking at the AWS MQ documentation, when the RabbitMQ broker is used, the IP address is not made available by the API.

Therefore, I believe it would be interesting to include this information in the documentation for this resource, indicating that the attribute will not be available if the RabbitMQ broker is used.

### References

https://docs.aws.amazon.com/amazon-mq/latest/api-reference/brokers-broker-id.html#brokers-broker-id-prop-brokerinstance-ipaddress

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @edner-liber 👋 Thank you for taking the time to raise this! I took a look over the [documentation for the `aws_mq_broker` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mq_broker) and noticed that this is mentioned already (edited for brevity):

> NOTE:
> Amazon MQ currently places limits on **RabbitMQ** brokers. For example, a RabbitMQ broker cannot have: instances with an associated IP address of an ENI attached to the broker...

Given that this isn't limited to the IP address, the callout note towards the top of the page fits with how other pages are structured. With that in mind, I'm going to close this issue out. If you notice any other odd/unexpected behavior from the provider, please do let us know!
