### ISSUE TITLE
[Enhancement]: AWS Grafana Enterprise Plugins management

### ISSUE THREAD

**Issue by carlosrodgut** [hashicorp/terraform-provider-aws#38826]
### Description

The resource 'aws_grafana_workspace' does not contain any property to enable the Grafana Enterprise management 
> This option is only available in workspaces that support Grafana version 9 or newer.

### Affected Resource(s) and/or Data Source(s)

aws_grafana_workspace

### Potential Terraform Configuration

```terraform
resource "aws_grafana_workspace" "example" {
  account_access_type           = "CURRENT_ACCOUNT"
  authentication_providers      = ["SAML"]
  permission_type               = "SERVICE_MANAGED"
  role_arn                      = aws_iam_role.assume.arn
  enterprise_plugins_management = true
}
```

### References

https://docs.aws.amazon.com/grafana/latest/userguide/AMG-configure-workspace.html
https://docs.aws.amazon.com/grafana/latest/userguide/AMG-workspace-manage-enterprise.html
https://docs.aws.amazon.com/grafana/latest/APIReference/API_CreateWorkspace.html#ManagedGrafana-CreateWorkspace-request-configuration
https://docs.aws.amazon.com/grafana/latest/APIReference/API_DescribeWorkspaceConfiguration.html#ManagedGrafana-DescribeWorkspaceConfiguration-response-configuration
https://docs.aws.amazon.com/grafana/latest/APIReference/API_UpdateWorkspaceConfiguration.html#ManagedGrafana-UpdateWorkspaceConfiguration-request-configuration

### Would you like to implement a fix?

Yes

**Comment by carlosrodgut** [comment]
Other Enhancement could potentially be implemented by the same contribution.
https://github.com/hashicorp/terraform-provider-aws/issues/32608

**Comment by carlosrodgut** [comment]
The AWS Terraform Module seems to have already a `configuration` variable that caould make use of those option.
https://github.com/terraform-aws-modules/terraform-aws-managed-service-grafana/blob/master/main.tf#L17

**Comment by carlosrodgut** [comment]
A workaround in the meanwhile 
(Last Resort -> https://developer.hashicorp.com/terraform/language/resources/provisioners/syntax)

```
resource "terraform_data" "amazon_managed_grafana_configuration_enable_plugin_management_script" {
  provisioner "local-exec" {
    command = "aws grafana update-workspace-configuration --region <AWS_Region> --workspace-id <WORKSPACE_ID> --configuration '{\"plugins\": {\"pluginAdminEnabled\": true }}'"
  }
}
```

**Comment by justinretzolk** [comment]
Hey @carlosrodgut 👋 Thank you for taking the time to raise this! If I'm understanding correctly, it sounds like the recent addition of the `grafana_token` argument to the [`aws_grafana_license_association` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/grafana_license_association) might be what you're looking for. Can you review that resource and verify if it'll help you resolve your issue?

**Comment by carlosrodgut** [comment]
Hi @justinretzolk,

The recent added `grafana_token` (generated on GrafanaLabs side) grants access to the Enterprise plugins set, but once those are available you need to enable the `pluginAdminEnabled` option in order to manage the different plugins inside the Grafana workspace.

![amazon-managed-grafana-configuration-enterprise-plugin-management](https://github.com/user-attachments/assets/bdcb0976-c507-484a-829f-aa08c5f987af)

**Comment by carlosrodgut** [comment]
Hi @justinretzolk,

I have tested that value for the argument `configuration` and it works perfectly. 

Indeed is a much more convenient way to pass the JSON string with the different options.

I would like to suggest a small change on the documentation of the resource and extend it with a new usage example.

https://github.com/hashicorp/terraform-provider-aws/pull/38898
