### ISSUE TITLE
[Bug]: aws_guardduty_invite_accepter BadRequestException

### ISSUE THREAD

**Issue by connor-tyndall** [hashicorp/terraform-provider-aws#38833]
### Terraform Core Version

1.5.4

### AWS Provider Version

5.62.0

### Affected Resource(s)

* aws_guardduty_invite_accepter

### Expected Behavior

* The aws_guardduty_invite_accepter resource should successfully accept a GuardDuty invite from a master account when using the latest version of the AWS provider for Terraform.
* The resource creation should complete without errors, establishing the member account's connection to the master GuardDuty account.

### Actual Behavior

* The `aws_guardduty_invite_accepter` resource is failing to accept the GuardDuty invite.
* Terraform is encountering a BadRequestException with the following error message:
`"The request is rejected because an invalid or out-of-range value is specified as an input parameter."`
* The resource creation fails, preventing the member account from joining the master GuardDuty account.

### Relevant Error/Panic Output Snippet

`The request is rejected because an invalid or out-of-range value is specified as an input parameter.`

### Terraform Configuration Files

```hcl
data "aws_caller_identity" "current" {}

data "aws_region" "current" {}

data "aws_guardduty_detector" "master" {}

resource "aws_guardduty_detector" "member" {
  provider = aws.member
  enable   = true
}

resource "aws_guardduty_member" "member" {
  account_id = aws_guardduty_detector.member.account_id
  detector_id = data.aws_guardduty_detector.master.id
  email = var.account_email
  invite = true
  disable_email_notification = true
}

resource "aws_guardduty_invite_accepter" "member" {
  provider = aws.member
  depends_on = [aws_guardduty_member.member, aws_guardduty_detector.member]
  detector_id = aws_guardduty_detector.member.id
  master_account_id = data.aws_caller_identity.current.account_id
}
```

### Steps to Reproduce

* Use the latest version ([v5.62.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.62.0)) of the AWS provider for Terraform.
* Run terraform init to initialize the working directory.
* Execute terraform apply to create the resources.
* Observe the BadRequestException error during the apply process.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @connor-tyndall 👋 Thank you for taking the time to raise this! So that we have the information we need to look into this, can you supply a sample Terraform configuration that can be used to reproduce this and, if possible, debug logging (redacted as needed)?

**Comment by ewbankkit** [comment]
Maybe relates https://github.com/hashicorp/terraform-provider-aws/pull/38400?

**Comment by ewbankkit** [comment]
I can reproduce with our acceptance tests:

```console
% AWS_GUARDDUTY_MEMBER_ACCOUNT_ID=... AWS_GUARDDUTY_MEMBER_EMAIL=... make testacc TESTARGS='-run=TestAccGuardDuty_serial/InviteAccepter' PKG=guardduty
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/guardduty/... -v -count 1 -parallel 20  -run=TestAccGuardDuty_serial/InviteAccepter -timeout 360m
=== RUN   TestAccGuardDuty_serial
=== PAUSE TestAccGuardDuty_serial
=== CONT  TestAccGuardDuty_serial
=== RUN   TestAccGuardDuty_serial/InviteAccepter
=== RUN   TestAccGuardDuty_serial/InviteAccepter/basic
    invite_accepter_test.go:29: Step 1/2 error: Error running apply: exit status 1
        
        Error: accepting GuardDuty Invitation (): operation error GuardDuty: AcceptInvitation, https response error StatusCode: 400, RequestID: 6cf0bab9-d10a-4c58-bb42-040346540c7e, BadRequestException: The request is rejected because an invalid or out-of-range value is specified as an input parameter.
        
          with aws_guardduty_invite_accepter.test,
          on terraform_plugin_test.tf line 37, in resource "aws_guardduty_invite_accepter" "test":
          37: resource "aws_guardduty_invite_accepter" "test" {
        
--- FAIL: TestAccGuardDuty_serial (71.01s)
    --- FAIL: TestAccGuardDuty_serial/InviteAccepter (71.01s)
        --- FAIL: TestAccGuardDuty_serial/InviteAccepter/basic (71.01s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/guardduty	75.719s
FAIL
make: *** [testacc] Error 1
```

**Comment by BartlomiejKrawczykEviden** [comment]
I confirm this now works on aws provider v 5.65.0. Thank you!
