### ISSUE TITLE
[Docs]: Resource: aws_dms_endpoint engine_name missing redshift-serverless

### ISSUE THREAD

**Issue by wesleung** [hashicorp/terraform-provider-aws#38831]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint

### Description

Parameter engine_name missing valid entry redshift-serverless

Does not exist in aws cli documentation and I have also submitted a feedback to them to correct
https://docs.aws.amazon.com/cli/latest/reference/dms/create-endpoint.html

### References

https://docs.aws.amazon.com/cli/latest/reference/dms/create-endpoint.html

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Related #37063

**Comment by Jyots6914** [comment]
I will work on it and will raise PR
