### ISSUE TITLE
[Enhancement]: AWS Backup Plan

### ISSUE THREAD

**Issue by huynn0x** [hashicorp/terraform-provider-aws#38839]
### Description

I would like a Terraform Resource for creating AWS Backup Plans

### Affected Resource(s) and/or Data Source(s)

aws_backup_plan

### Potential Terraform Configuration

```terraform
resource "aws_backup_plan" "example" {
  name = "tf_example_backup_plan"

  rule {
    rule_name         = "tf_example_backup_rule"
    target_vault_name = aws_backup_vault.test.name
    schedule          = "cron(0 12 * * ? *)"

    lifecycle {
      delete_after = 14
    }
  }

  advanced_backup_setting {
    backup_options = {
      WindowsVSS = "enabled"
    }
    resource_type = "EC2"
  }
}
```

### References

https://docs.aws.amazon.com/aws-backup/latest/devguide/API_CreateBackupPlan.html

### Would you like to implement a fix?

Yes

**Comment by stefanfreitag** [comment]
Hi @huynn0x,

there is a similar resource available in the latest version of the provider. Please have a look [here](
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_plan).

**Comment by justinretzolk** [comment]
Hey @huynn0x 👋 It looks like the example configuration that you provided is identical to the example from the documentation linked above. With that information, and that we haven't heard back, I'm going to close this issue for now. If you have any additional requests for enhancements to the provider, please do let us know!
