### ISSUE TITLE
[Docs]: sqs_queue instead of sqs_queue_parameters

### ISSUE THREAD

**Issue by lebohnes** [hashicorp/terraform-provider-aws#38842]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pipes_pipe#source

### Description

The target_parameters schon be "sqs_queue_parameters " and not "sqs_queue "

Wrong part:
```
target_parameters {
    sqs_queue {
      message_deduplication_id = "example-dedupe"
      message_group_id         = "example-group"
    }
  }
```

Correct part:
```
target_parameters {
    sqs_queue_parameters {
      message_deduplication_id = "example-dedupe"
      message_group_id         = "example-group"
    }
  }
```

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Hi @lebohnes,
thanks for raising this! 
I think you are refering to this [example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pipes_pipe#sqs-source-and-target-configuration-usage) in the documentation that needs to be updated. I will have a look into this.

**Comment by lebohnes** [comment]
yes, exactly! Thanks.
