### ISSUE TITLE
[Enhancement]: `TF_AWS_DEFAULT_TAGS` does not work for tag names containing colons (aws recommends this convention)

### ISSUE THREAD

**Issue by nitrocode** [hashicorp/terraform-provider-aws#38889]
### Description

AWS recommends colons in tag names

https://docs.aws.amazon.com/tag-editor/latest/userguide/best-practices-and-strats.html

Sadly bash/shell doesn't support using colons in variable names so I'm at a loss on using `TF_AWS_DEFAULT_TAGS` to create a tag using `org:team`.

How can I set this? If it's not possible, is there a way to use a separate placeholder that could be auto replaced by the aws provider?

```bash
# theses do not work
export TF_AWS_DEFAULT_TAGS_org:team="red"
export "TF_AWS_DEFAULT_TAGS_org:team"="red"
export TF_AWS_DEFAULT_TAGS_org\:team="red"
export "TF_AWS_DEFAULT_TAGS_org\:team"="red"
```

Error

```
$ export TF_AWS_DEFAULT_TAGS_org:team="red"
export: not valid in this context: TF_AWS_DEFAULT_TAGS_org:team
```

Proposal

```bash
# maybe these can work in the future for special characters
## This could translate to org:team=red
export "TF_AWS_DEFAULT_TAGS_org__colon__team"="red"
```

### Affected Resource(s) and/or Data Source(s)

* aws provider

### Would you like to implement a fix?

None

**Comment by jessegonzalez-life360** [comment]
This may help you and others:

```
❯ env TF_AWS_DEFAULT_TAGS_org:team="red" printenv | grep TF_AWS_DEFAULT_TAGS_
TF_AWS_DEFAULT_TAGS_org:team=red
```

**Comment by nitrocode** [comment]
Perfect. That worked.

Thank you very much.
