### ISSUE TITLE
[Docs]: error in aws_kms_public_key attribute reference 

### ISSUE THREAD

**Issue by Juno-888** [hashicorp/terraform-provider-aws#38896]
### Documentation Link

https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/d/kms_public_key.html.markdown

### Description

Under the attribute reference section of the docs in the aws_kms_public_key data source; both the arn and id share the same string describing what they are, but they should be different as they are different attributes with different outputs.

### Would you like to implement a fix?

None

**Comment by Juno-888** [comment]
I am trying to fix now.

**Comment by justinretzolk** [comment]
Hey @Juno-888 👋 Thank you for taking the time to raise this! I took a look at this and noted that the `arn` and `id` values [are set to the same value](https://github.com/hashicorp/terraform-provider-aws/blob/8e9f949290029b8003116681bdab562d1e1b1fa2/internal/service/kms/public_key_data_source.go#L90-L91) within the data source's code, matching what the documentation currently says. There's a similar argument -- `key_id`, however, it's distinct from `id`, with the former being the key's identifier on the AWS side, and the latter being the identifier as far as Terraform is concerned. Is that, perhaps, where the confusion is coming from?
