### ISSUE TITLE
[Enhancement]: `data.aws_sns_topic` should have a `tags` attribute

### ISSUE THREAD

**Issue by epgui** [hashicorp/terraform-provider-aws#38910]
### Description

We have custom terraform modules for a pub-sub system: a message publisher module, and a message subscriber module.

We are attaching metadata (eg.: the relevant Glue schema) to the `aws_sns_topic` resources created by our message publisher module, via `tags`. We would like to access the data stored in these `tags` from our message subscriber module. Unfortunately the `data.aws_sns_topic` data source does not provide a `tags` attribute.

### Affected Resource(s) and/or Data Source(s)

* data.aws_sns_topic

### Would you like to implement a fix?

No

**Comment by jmonte-sph** [comment]
I also agree with this enhancement since even `data.aws_sqs_queue` has a [`tags`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/sqs_queue#tags) attribute.

I am interested in working on this issue.
