### ISSUE TITLE
[Docs]: Resource aws_mq_broker documentation example password character length error

### ISSUE THREAD

**Issue by architec** [hashicorp/terraform-provider-aws#38929]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mq_broker#example-usage

### Description

The current example for aws_mq_broker gives the following error about password character length
```
Error: "user.0.password" must be 12 to 250 characters long. provided string length: 10
```

### Would you like to implement a fix?

Yes

**Comment by SignalWhisperer** [comment]
I think the example providing an invalid password is a good secure value to have. If the example password were to be valid, it would end up being used in some deployments.

**Comment by architec** [comment]
Good point @SignalWhisperer, I agree.
