### ISSUE TITLE
[Bug]: Applying Route53 VPC DNSSEC fails for decomposing request: unsupported protocol scheme ""

### ISSUE THREAD

**Issue by yaringalmor** [hashicorp/terraform-provider-aws#38941]
### Terraform Core Version

1.1.9

### AWS Provider Version

5.63.0

### Affected Resource(s)

aws_route53_resolver_dnssec_config

### Expected Behavior

Ensure vpc route53 DNSSEC validation is enabled.

### Actual Behavior

Terraform deployment has failed.

### Relevant Error/Panic Output Snippet

```shell
Error: reading Route53 Resolver DNSSEC Config (XXXX): operation error Route53Resolver: ListResolverDnssecConfigs, decomposing request: unsupported protocol scheme ""
```

### Terraform Configuration Files

```hcl
resource "aws_route53_resolver_dnssec_config" "enable_dnssec_resolving" {
  resource_id = aws_vpc.my_vpc.id
}
```

### Steps to Reproduce

Deploy VPC wich dnssec config as attached in the terraform configuration files section.

### References

Suspecting [this commit](https://github.com/hashicorp/terraform-provider-aws/commit/d5910d90969d00dd7e706f04dd3bc64d330bb198) to cause the break.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
hey @yaringalmor 👋 Thank you for taking the time to raise this! I saw that you tracked down what seemed to be the commit that introduced this behavior. I also see that the commit was included in version 5.63.0 of the provider. With that in mind, is it safe to assume that you're not able to reproduce the issue with version 5.62.0?

**Comment by yaringalmor** [comment]
Correct, 5.62.0 worked smoothly.

**Comment by nam054** [comment]
Hi @yaringalmor,  thank you for raising the issue. I've ran the configuration of the route53 resolver dnssec config resource on the current version of the provider and am unable to recreate the error. Could you please try with the latest version of the provider 5.66.0?
And if the issue persists, could you share what the configuration looks like?

**Comment by breathingdust** [comment]
Unable to reproduce.

**Comment by joshuastern** [comment]
I am seeing this issue specifically in GovCloud accounts, as well as their standard partition siblings.
