### ISSUE TITLE
[Enhancement]: aws_inspector2_member_association to support multiple account_ids

### ISSUE THREAD

**Issue by michalz-rely** [hashicorp/terraform-provider-aws#38966]
### Description

Provide a support for multiple `account_ids` instead of single `account_id` similarly like it has been done in `aws_inspector2_enabler`. As both resources are usually used in pair (as you need to first associate an account in order to enable inspector) there's no reason to have a difference here.

### Affected Resource(s) and/or Data Source(s)

aws_inspector2_member_association

### Potential Terraform Configuration

```terraform
resource "aws_inspector2_member_association" "example" {
  account_ids = ["123456789012"]
}
```

### References

[aws_inspector2_enabler](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/inspector2_enabler)

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @michalz-rely 👋 Thank you for taking the time to raise this! The reason for the difference in the resources lies with the underlying API. While the Inspector2 API's [`Enable` action](https://docs.aws.amazon.com/inspector/v2/APIReference/API_Enable.html) accepts a list of `accountIds`, the [`AssociateMember` action](https://docs.aws.amazon.com/inspector/v2/APIReference/API_AssociateMember.html) only accepts a single `accountId`. 

Following the [provider design principles](https://developer.hashicorp.com/terraform/plugin/best-practices/hashicorp-provider-design-principles#resource-and-attribute-schema-should-closely-match-the-underlying-api), we match the underlying API as much as possible, so a change like this isn't something we'll be able to implement at this time. If the upstream API changes in the future, we'd be happy to take another look. In the meantime, the [`for_each` meta-argument](https://developer.hashicorp.com/terraform/language/meta-arguments/for_each) can be used in cases like this.

If you have any additional requests in the future, please do let us know!
