### ISSUE TITLE
[Bug]: Failures in C2S regions when creating Step Functions due to UnsupportedOperation calling ListStateMachineVersions

### ISSUE THREAD

**Issue by thefirstofthe300** [hashicorp/terraform-provider-aws#38978]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.61.0

### Affected Resource(s)

- aws_sfn_state_machine

### Expected Behavior

Step Function should have successfully been created in C2S region

### Actual Behavior

Provider fails due to unhandled UnsupportedOperation error

### Terraform Configuration Files

Any minimal step function declaration using a provider configured to use the us-iso-east-1 region.

### Steps to Reproduce

terraform apply

### Debug Output

<?xml version="1.0" encoding="UTF-8" standalone="no"?><Response><Errors><Error><Code>UnsupportedOperation</Code><Message>The functionality you requested is not available in this region.</Message></Error><RequestID>3bdcfe2bca424df6850515e5df83ba06</RequestID></Errors></Response>

### Important Factoids

We are using an emulation layer on top of a public AWS region to determine what works in C2S regions: https://www.applied-insight.com/

### Would you like to implement a fix?

No

**Comment by thefirstofthe300** [comment]
Would be part of here: https://github.com/hashicorp/terraform-provider-aws/issues/18593

**Comment by justinretzolk** [comment]
Hey @thefirstofthe300 👋 Thank you for taking the time to raise this! I left [a comment](https://github.com/hashicorp/terraform-provider-aws/issues/38977#issuecomment-2310504427) on your other issue, but wanted to link it here given that the question I asked there is relevant here as well. This comment is intended mainly to make the link for anyone else who may stumble across this 🙂.

**Comment by thefirstofthe300** [comment]
Regarding your question as to whether the error occurs in the actual C2S region, my response regarding validation in an actual C2S region stands.

I do not have any documentation that suggests that this particular API endpoint doesn't exist in the C2S region so I have no idea if the issue here is poor documentation or an actual issue. We do pay a significant sum for the emulation product so I would not be surprised if they have the ability to validate whether certain endpoints exist or not, either through documentation my team doesn't have access to or through access to an actual C2S region.

**Comment by thefirstofthe300** [comment]
Looks like this was caused by an actual bug in our emulation provider.
