### ISSUE TITLE
r/aws_lambda_event_source_mapping: Support for encryption of filter criteria

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#38988]
> AWS Lambda announces support for encryption of filter criteria for event source mappings

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/08/aws-lambda-encryption-filter-criteria-event-source-mappings/)

Requires `github.com/aws/aws-sdk-go-v2/service/lambda@1.58.0`: https://github.com/hashicorp/terraform-provider-aws/pull/38981.

**Comment by trutled3** [comment]
I am interested in working on this enhancement. I propose adding a `kms_key_id` argument similar to other resources that utilize KMS for encryption. For example following,

```terraform
resource "aws_lambda_event_source_mapping" "example" {
  event_source_arn = aws_sqs_queue.sqs_queue_test.arn
  function_name = aws_lambda_function.example.arn
  kms_key_id = aws_lambda_function.example.arn

  ... other arguments ...
}
```

I will prepare a PR for this.

**Comment by trutled3** [comment]
@ewbankkit - I opened PR #39055 to add this capability if you wanted to give a thumb!
