### ISSUE TITLE
[Docs]: Wrong parameters for dlm_lifecycle_policy#share-rule-arguments

### ISSUE THREAD

**Issue by crashev** [hashicorp/terraform-provider-aws#38985]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dlm_lifecycle_policy#share-rule-arguments

### Description

In current documentation, it states that for `share_rule` there are parameters available:

- interval
- interval_unit

when in fact those parameter's names are different:
- unshare_interval
- unshare_interval_unit

See: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/dlm/lifecycle_policy.go#L438

### Would you like to implement a fix?

None

**Comment by alinaefi** [comment]
Hi! I would like to work on this
