### ISSUE TITLE
[Enhancement]: r/aws_glue_job: Add support for job run queuing

### ISSUE THREAD

**Issue by jar-b** [hashicorp/terraform-provider-aws#38991]
### Description

To support job run queuing, add an optional `job_run_queuing_enabled` argument to the Glue job resource.

https://github.com/aws/aws-sdk-go-v2/blob/38fe812f7abf976b6b1a5122c0c3bf303502cfc5/service/glue/api_op_CreateJob.go#L136-L143

### Affected Resource(s) and/or Data Source(s)

- `aws_glue_job`

### Potential Terraform Configuration

```terraform
resource "aws_glue_job" "example" {
  ### additional configuration ###

  job_run_queuing_enabled = true
}
```

### References

- depends on #38981
- https://github.com/aws/aws-sdk-go-v2/blob/main/CHANGELOG.md#release-2024-08-21

### Would you like to implement a fix?

None

**Comment by mahadzaryab1** [comment]
@jar-b I've got a PR open at https://github.com/hashicorp/terraform-provider-aws/pull/39027/files. Do you know how I can test my changes (I'm new to this project).
