### ISSUE TITLE
[Docs]: aws_db_option_group - The parameters 'name' & 'value' are Required in the 'option_settings' block but are marked as Optional

### ISSUE THREAD

**Issue by ShaheenK27** [hashicorp/terraform-provider-aws#38992]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_option_group#option_settings-block

### Description

- The parameters `name` and `value` are ***required*** in the **_option_settings_** block resource.

- However, they are described as Optional in the terraform reference.

- These parameters have been **correctly** implemented as required in the ***source code***.
  - **name:** [option_group.go#L99](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/rds/option_group.go#L99)
 
  - **value:** [option_group.go#L103](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/rds/option_group.go#L103)

- Therefore, if not specified, there is a plan-time error for both the parameters
  - > Error: Missing required argument

- Terraform reference descriptions should be updated to indicate that these two parameters are Required in the _**option_settings**_ block.

### Would you like to implement a fix?

None

**Comment by ChinoUkaegbu** [comment]
Hi, I'd like to work on this! Just to clarify, the change is to be made to this [file](../blob/main/website/docs/r/db_option_group.html.markdown#option_settings-block)?
