### ISSUE TITLE
[Repo]: 5.64.0 registry metadata is missing for linux amd64

### ISSUE THREAD

**Issue by andythompson** [hashicorp/terraform-provider-aws#39004]
### Description

The Linux amd64 version appears to be missing the registry metadata for the [5.64.0](https://registry.terraform.io/v1/providers/hashicorp/aws/5.64.0/download/linux/amd64) release

[5.63.0](https://registry.terraform.io/v1/providers/hashicorp/aws/5.63.0/download/linux/amd64) for comparison

The binary is available though at https://releases.hashicorp.com/terraform-provider-aws/5.64.0/terraform-provider-aws_5.64.0_linux_amd64.zip

### References

https://registry.terraform.io/v1/providers/hashicorp/aws/5.64.0/download/linux/amd64 

### Would you like to implement a fix?

None

**Comment by andythompson** [comment]
Closing, this is resolved now

**Comment by nitrocode** [comment]
@andythompson Thanks for fixing. What was the resolution?

**Comment by andythompson** [comment]
> @andythompson Thanks for fixing. What was the resolution?

I didn't do anything. It was fixed by hashicorp

**Comment by nitrocode** [comment]
Oh I see, I didn't realize you were OP. I wonder how hashi fixed it. 🤔
