### ISSUE TITLE
[Docs]: aws_route53_health_check note about required arguments is incorrect

### ISSUE THREAD

**Issue by Dr-Emann** [hashicorp/terraform-provider-aws#39013]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_health_check#argument-reference

### Description

The argument documentation includes:

> **Note:**
> At least one of either fqdn or ip_address must be specified.

However, directly above, there are [two](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_health_check#aggregate-check) [examples](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_health_check#cloudwatch-alarm-check) which don't use either of those arguments (I believe correctly).

e.g.

> ```
> resource "aws_route53_health_check" "parent" {
>   type                   = "CALCULATED"
>   child_health_threshold = 1
>   child_healthchecks     = [aws_route53_health_check.child.id]
> 
>   tags = {
>     Name = "tf-test-calculated-health-check"
>   }
> }
> ```

### Would you like to implement a fix?

No

**Comment by stefanfreitag** [comment]
Hi @Dr-Emann ,

thank you for reporting the issue! I think that you are right.

The health check can be linked to endpoints (IP address/ FQDN), but also Cloudwatch Alarms work.
(see [here](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/health-checks-types.html) for the supported types)

I would propose to remove the note from documentation. Let me prepare a pull request for review.
