### ISSUE TITLE
[Enhancement]: aws_cloudhsm_v2_cluster - add support for hsm2m.medium hsm_type

### ISSUE THREAD

**Issue by guiyang2011** [hashicorp/terraform-provider-aws#39018]
### Description

The cloudhsm type "hsm2m.medium" was supported in aws-sdk-go v1.54.1, which had been added to the terraform-provider-aws already. However, it doesn't seem the current terraform-provider-aws exposes the new type yet https://github.com/hashicorp/terraform-provider-aws/blob/a89fe9b3017efc499d4b9d01c7c662266d884888/internal/service/cloudhsmv2/cluster.go#L91

### Affected Resource(s) and/or Data Source(s)

aws_cloudhsm_v2_cluster

### Potential Terraform Configuration

```terraform
resource "aws_cloudhsm_v2_cluster" "cloudhsm_v2_cluster" {
  hsm_type   = "hsm2m.medium"
}
```

### References

aws-sdk-go https://github.com/aws/aws-sdk-go/blob/02c1f723b528251a45068001bee8b56d904d7484/models/apis/cloudhsmv2/2017-04-28/docs-2.json#L382

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Hi @guiyang2011!

Thanks for reporting the issue. 
Let me have a look into this.

**Comment by prestonprice57** [comment]
Hey I can take a crack at this one. PR incoming.
