### ISSUE TITLE
[Bug]: Provider v5.64.0 does not have a package available for your current platform, linux_amd64

### ISSUE THREAD

**Issue by phreemon** [hashicorp/terraform-provider-aws#39012]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.64.0

### Expected Behavior

Provider initializes on platform linux_amd64

### Actual Behavior

│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/aws v5.64.0 does not have a
│ package available for your current platform, linux_amd64.

### Relevant Error/Panic Output Snippet

```shell
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/aws v5.64.0 does not have a
│ package available for your current platform, linux_amd64.
```

### Terraform Configuration Files

Not a configuration issue

### Steps to Reproduce

- Initialize a terraform file with provider version 5.64.0 on platform linux_amd64
- Observe error

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@phreemon Thanks for raising this issue 👏.
This looks like the same problem as reported in https://github.com/hashicorp/terraform-provider-aws/issues/39004 which has been closed as _works now_. Are you still having the issue?

**Comment by phreemon** [comment]
@ewbankkit yes we are still seeing the issue as of a couple of minutes ago. 

We're using a Nexus repository as a package mirror, I deleted the 5.64.0.json metadata file which did not contain the linux_amd64 platform. After re-initializing it pulled down a new 5.64.0.json file which has the following content:

`{
    "archives": {
        "darwin_amd64": {
            "url": "terraform-provider-aws_5.64.0_darwin_amd64.zip"
        },
        "darwin_arm64": {
            "url": "terraform-provider-aws_5.64.0_darwin_arm64.zip"
        },
        "linux_arm": {
            "url": "terraform-provider-aws_5.64.0_linux_arm.zip"
        },
        "windows_amd64": {
            "url": "terraform-provider-aws_5.64.0_windows_amd64.zip"
        },
        "linux_arm64": {
            "url": "terraform-provider-aws_5.64.0_linux_arm64.zip"
        }
    }
}`

**Comment by rsi-mrobinson** [comment]
Also encountered this issue, running terraform in CI on clean environment.

**Comment by phreemon** [comment]
We're not seeing the issue with the latest release of the AWS provider (5.65.0) so I will go ahead and close this.
