### ISSUE TITLE
[Enhancement]: aws_cognito_user_pool.password_policy.Allow_reuse_of_previous_passwords

### ISSUE THREAD

**Issue by jordancparker** [hashicorp/terraform-provider-aws#39016]
### Description

Request for Allow_reuse_of_previous_passwords to be added to the password_policy in aws_cognito_user_pool resource. 

This is a new feature released in Cognito and would make sense to enhance the password_policy as thats where it sits within the UI experience, however there is a requirement for the advanced security to be active. 

### Affected Resource(s) and/or Data Source(s)

aws_cognito_user_pool

### Potential Terraform Configuration

```terraform
resource "aws_cognito_user_pool" "this" {
  password_policy {
    minimum_length                   = "10"
    require_lowercase                = "true"
    require_numbers                  = "true"
    require_symbols                  = "true"
    require_uppercase                = "true"
    temporary_password_validity_days = "10"
    Allow_reuse_of_previous_passwords = "true"
  }
}
```

### Would you like to implement a fix?

No

**Comment by DizzyDeveloper** [comment]
I want to second this issue, with a slight addendum:

```tf
resource "aws_cognito_user_pool" "this" {
  password_policy {
    minimum_length                   = "10"
    require_lowercase                = "true"
    require_numbers                  = "true"
    require_symbols                  = "true"
    require_uppercase                = "true"
    temporary_password_validity_days = "10"

    password_history_size = 2 /* Instead of aforementioned Allow_reuse_of_previous_passwords */
  
  }
}
```

At the moment this can be achieved by using exec local and manually invoking the the aws cli `aws cognito-idp update-user-pool` however if miss configure the cli call it will overwrite what was configured as part of the original `aws_cognito_user_pool` declaration which is not optimal.
