### ISSUE TITLE
[Bug]: v5.64.0 Error: Failed to load plugin schemas, v5.63.0 works fine

### ISSUE THREAD

**Issue by nitrocode** [hashicorp/terraform-provider-aws#39023]
### Terraform Core Version

1.8.1

### AWS Provider Version

5.64.0

### Affected Resource(s)

- Any resources

### Expected Behavior

Terraform plan works as expected

### Actual Behavior

Terraform plan fails with the below error

It only seems to happen with 5.64.0. 

Downgrading to 5.63.1 terraform plan works in CICD x86 intel.

https://github.com/hashicorp/terraform-provider-aws/compare/v5.63.1...v5.64.0

### Relevant Error/Panic Output Snippet

```shell
│ Error: Failed to load plugin schemas
│ 
│ Error while loading schemas for plugin components: Failed to obtain
│ provider schema: Could not load the schema for provider
│ registry.terraform.io/hashicorp/aws: failed to instantiate provider
│ "registry.terraform.io/hashicorp/aws" to obtain schema: Unrecognized remote
│ plugin message: 
│ 
│ This usually means that the plugin is either invalid or simply
│ needs to be recompiled to support the latest protocol...
```

### Terraform Configuration Files

Terraform is too large to share.

### Steps to Reproduce

CICD (Atlantis)
terraform init
terraform plan

### Debug Output

N/A

### Panic Output

N/A

### Important Factoids

N/A

### References

N/A

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/39012.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/39004.

**Comment by nitrocode** [comment]
It's working for me now after I deleted the cached provider version and redownloaded it. Thank you.
