### ISSUE TITLE
[Bug]: Error deleting SSM parameter after upgrading provider over v5.50.0

### ISSUE THREAD

**Issue by carlosjgp** [hashicorp/terraform-provider-aws#39050]
### Terraform Core Version

1.9.5

### AWS Provider Version

5.64.0

### Affected Resource(s)

* aws_ssm_parameter

### Expected Behavior

The ssm parameters are deleted

### Actual Behavior

```
Error: deleting SSM Parameter (arn:aws:ssm:<region>:<account id>:parameter< parameter name - starts with / >): operation error SSM: DeleteParameter, https response error StatusCode: 400, RequestID: <ID>, api error ValidationException: Parameter ARN is not supported for this operation.
```

### Terraform Configuration Files

```
terraform {
  required_version = ">= 1.5.0"

  backend "local" {
    path = "terraform.tfstate"
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0, > 5.50.0"
    }
  }
}

resource "aws_ssm_parameter" "my_parameter" {
  name = "/my-parameter-name"

  description = "testing"
  type        = "String"
  value       = "test"
}
```

update required providers to
```
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }
  }
```
and remove lock file `rm .terraform.lock.hcl`
or run `terraform init -upgrade`

### Steps to Reproduce

terraform init
terraform apply
# update provider over v5.50.0
terraform init -upgrade
terraform destroy

### Important Factoids

Terraform state on S3
```
{
      "mode": "managed",
      "type": "aws_ssm_parameter",
      "name": "aurora_port",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "allowed_pattern": "",
            "arn": "arn:aws:ssm:<region>:<account id>:parameter/my-parameter-name",
            "data_type": "text",
            "description": "port",
            "id": "arn:aws:ssm:<region>:<account id>:parameter/my-parameter-name",
            "insecure_value": null,
            "key_id": "",
            "name": "/my-parameter-name",
            "overwrite": null,
```

AWS provider v5.64.0 tries to delete using the ID
https://github.com/hashicorp/terraform-provider-aws/blob/c8bdbd62df3185f993898517bcedd20e0b9e1065/internal/service/ssm/parameter.go#L339-L341

because now `ID = NAME`
https://github.com/hashicorp/terraform-provider-aws/blob/c8bdbd62df3185f993898517bcedd20e0b9e1065/internal/service/ssm/parameter.go#L209

Code update for v5.50.0 changes the way SSM parameters are stored on the state and deletion breaks
https://github.com/hashicorp/terraform-provider-aws/commit/d21628eb77e8e26f0e3d4e27c0f3166185b2aab2

pre v5.50.0
```
Name: aws.String(d.Get(names.AttrName).(string)),
```

after v5.50.0
```
Name: aws.String(d.Id()),
```

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/37481.
