### ISSUE TITLE
[Enhancement]: EKS managed node groups don't allow SSM parameters in place of AMI ID similar to launch templates terraform

### ISSUE THREAD

**Issue by emcay** [hashicorp/terraform-provider-aws#39069]
### Description

Similar to https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#image_id, and as described in https://docs.aws.amazon.com/autoscaling/ec2/userguide/using-systems-manager-parameters.html, I would like a way to specify an SSM parameter to resolve an AMI so that the launch template is able to update it dynamically and not via terraform.

I know you can use a datasource to query what is the value of the image in SSM, but I want it managed via the launch template so I can dynamically provision the latest AMIs without re-running the terraform.

### Affected Resource(s) and/or Data Source(s)

[eks](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group)

### Potential Terraform Configuration

```terraform
Something like

ami_id = "resolve:ssm:parameter-name:version-number"
or
release_version = "resolve:ssm:parameter-name:version-number"
```

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#image_id
https://docs.aws.amazon.com/autoscaling/ec2/userguide/using-systems-manager-parameters.html

### Would you like to implement a fix?

None

**Comment by ehmkrause** [comment]
Just to clarify a little, what I am hoping to do is get the node group module to support this so I don't have to break out configuration from the node group into a launch template and manage both.

**Comment by emcay** [comment]
Just to clarify what I am asking for is the node group to support this or something similar so I don't have to manually manage the launch template myself.

**Comment by bengaywins** [comment]
Not from the HashiCorp team or anything, just some rando looking for his own issues and saw this, but you can already do this @emcay.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ssm_parameter

And then reference that data source for the value `data.aws_ssm_parameter.thenameofthedatasource.value`

So example code:
```hcl
 data "aws_ssm_parameter" "ami_id" {
  name = "/aws/service/eks/optimized-ami/1.30/amazon-linux-2023/x86_64/standard/recommended/image_id"
}

# wherever you are now trying to reference this:
ami_id = data.aws_ssm_parameter.ami_id
```

**Comment by bengaywins** [comment]
Ah that would be amazing but I don't know of that feature existing even in Amazon itself, but if it did, I would try to use it!

Not saying this will work, but I just thought, the managed node groups notice that there is an updated AMI available. I wonder if you could have an event bridge notification go to a step function that tells the node groups to start the update when that parameter is updated? Just spit balling ideas here. This would make the SSM parameter data irrelevant conceptually, but achieve the dynamic automatic updates when they come.

**Comment by emcay** [comment]
That is a good idea. I do believe it is possible now with the launch templates. I was able to use this format and substitute it for an AMI ID in a launch template and it didn accept it and provision a node.

https://docs.aws.amazon.com/autoscaling/ec2/userguide/using-systems-manager-parameters.html

If I could find a way to make it work with terraform via node groups and not have to manually manage the launch template myself (and still managed automatically via eks node group) it would simplify things in my configuration and also I wouldn't have to run scheduled terraform builds to bump AMIs.

**Comment by bengaywins** [comment]
First I've seen this, so this would be amazing to implement!

**Comment by bryantbiggs** [comment]
this is not related to the provider - EKS managed node groups need to support this and then users will be able to specify this in their Terraform configuration

**Comment by justinretzolk** [comment]
Hey @emcay 👋 Thank you for taking the time to raise this! Since this isn't something that AWS currently supports, I'm going to close this issue. If there are upstream changes that allow this in the future, we'd be happy to take another look!
