### ISSUE TITLE
[New]: AWS backup plan

### ISSUE THREAD

**Issue by Debie-D** [hashicorp/terraform-provider-aws#39081]
### Description

I would like a Terraform Resource for creating AWS Backup Plans

### Requested Resource(s) and/or Data Source(s)

aws_backup_plan

### Potential Terraform Configuration

```terraform
resource "aws_backup_plan" "example" {
  name = "tf_example_backup_plan"

  rule {
    rule_name         = "tf_example_backup_rule"
    target_vault_name = aws_backup_vault.test.name
    schedule          = "cron(0 12 * * ? *)"

    lifecycle {
      delete_after = 14
    }
  }

  advanced_backup_setting {
    backup_options = {
      WindowsVSS = "enabled"
    }
    resource_type = "EC2"
  }
}
```

### References

https://docs.aws.amazon.com/aws-backup/latest/devguide/API_CreateBackupPlan.html

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment]
Hey @Debie-D 👋 Thank you for taking the time to raise this! The provider currently offers a resource called [`aws_backup_plan`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_plan). Based on your provided example configuration, it seems like this is the resource your looking for. Can you confirm whether that's the case?
