### ISSUE TITLE
[Bug]: aws_elasticache_replication_group spurious deprecation/removal of `cluster_mode`

### ISSUE THREAD

**Issue by infowolfe** [hashicorp/terraform-provider-aws#39094]
### Terraform Core Version

1.9.5

### AWS Provider Version

5.65.0

### Affected Resource(s)

`aws_elasticache_replication_group` has a deprecated and removed option `cluster_mode` that is still valid in current AWS api docs and is NOT replaceable as per the code (as well as docs being outdated).

For Redis OSS clusters, `cluster_mode` set to `compatible` means that the cluster can be sharded or replicated. This setting can currently not be modified in terraform, nor is terraform even aware of it if I adjust it manually in the aws console.

### Expected Behavior

I should be able to set `cluster_mode` to `disabled`, `enabled`, or `compatible` in terraform.

### Actual Behavior

terraform has absolutely zero awareness of this option.

### Terraform Configuration Files
```
resource "aws_elasticache_replication_group" "primary" {
  provider = aws.other_region

  replication_group_id = "example-primary"
  description          = "primary replication group"

  engine         = "redis"
  engine_version = "5.0.6"
  node_type      = "cache.m5.large"
  cluster_mode = "compatible"
  num_cache_clusters = 1
}
```
### Steps to Reproduce

attempt to plan, see if `cluster_mode` shows up at all in the output.

### References

https://github.com/hashicorp/terraform-provider-aws/commit/bb56afd725b51c3d1cb3a73589000d17c30b08ee
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-replicationgroup.html
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group

### Would you like to implement a fix?

None

**Comment by vtstanescu** [comment]
> Relates #31008. Relates #38002.

Shouldn't this be closed? The `cluster_mode` attribute is available in the resource.

**Comment by infowolfe** [comment]
Yeah this should be closed
