### ISSUE TITLE
[Enhancement]: Support for the new AWS IPAM pool of Amazon supplied public IPs for contiguous Elastic IP (EIP) allocation

### ISSUE THREAD

**Issue by mhaswell-work** [hashicorp/terraform-provider-aws#39124]
### Description

AWS now supports IPAM Pools of Amazon provided contiguous public IPs available to allocate to EC2 Elastic IPs in order to provide a simple range for third party whitelisting.

e.g. using the AWS CLI ( v2.17.42 ):

```console
$ aws ec2 allocate-address --ipam-pool-id ipam-pool-085cda2853ce8a1bb
{
    "PublicIp": "26.96.32.28",
    "AllocationId": "eipalloc-078faaf8e6ffe6a48",
    "PublicIpv4Pool": "ipam-pool-085cda2853ce8a1bb",
    "NetworkBorderGroup": "eu-central-1",
    "Domain": "vpc"
}
```

### Affected Resource(s) and/or Data Source(s)

Elastic Ips are created using (for example):

```hcl
resource "aws_eip" "new_eips" {
  instance = null
}
```

### Potential Terraform Configuration

Similarly to the existing optional arguments `public_ipv4_pool` for IPAM pools for VPC Eips, or `customer_owned_ipv4_pool` for Customer provided IPv4 ranges:

```terraform
resource "aws_eip" "new_eips" {
  instance = null
  ipam_ipv4_pool = ipam-pool-085cda2853ce8a1bb
}
```

### References

AWS Docs on manually creating a pool and associating it with EC2 instances: https://docs.aws.amazon.com/vpc/latest/ipam/tutorials-eip-pool.html 

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@mhaswell-work Thanks for raising this issue.
It has already been noticed in #39080. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
