### ISSUE TITLE
[Bug]: bootstrap_self_managed_addons forces recreate of EKS clusters.

### ISSUE THREAD

**Issue by afischer-opentext-com** [hashicorp/terraform-provider-aws#39137]
### Terraform Core Version

1.8.1

### AWS Provider Version

5.65.0

### Affected Resource(s)

aws_eks_cluster

### Expected Behavior

The PR https://github.com/hashicorp/terraform-provider-aws/pull/38162 (introduced via provider version 5.58.0) causes a severe incompatibility which we fail to address.

Before the new flag got introduced the EKS cluster was implicitely created with bootstrapping addons. 
Now when keeping the default value (bootstrap_self_managed_addons is set to true per default), a recreate of the EKS cluster is forced. 
When configuring the value bootstrap_self_managed_addons to false, we end up with an EKS cluster without the addons. 

Both is imho wrong, this is a breaking change and does not allow us to move forward. 

Request: Consider to implement logic which does not force a recreation of existing clusters while not breaking their functionality. The cluster is not recreated while maintaining its functionality.

### Actual Behavior

The cluster is attempted to be recreated. 
Flipping configuration value to `false` causes degraded functionality as pieces such as coredns are no more available as before. 

### Terraform Configuration Files

terraform {
  required_version = "1.8.1"
  backend "s3" {}
  required_providers {
    aws = {
      version = "5.65.0"
      source  = "hashicorp/aws"
    }
}

resource "aws_eks_cluster" "eks_cluster" {
  enabled_cluster_log_types = [
    "api",
    "audit",
    "authenticator",
    "controllerManager",
    "scheduler"
  ]
  name     = local.cluster_name
  role_arn = var.cluster_role_arn

  version = var.cluster_version

  lifecycle {
    prevent_destroy = true
  }

  kubernetes_network_config {
    service_ipv4_cidr = "10.100.0.0/16"
  }

  vpc_config {
    subnet_ids              = var.subnet_ids
    endpoint_private_access = true
    endpoint_public_access  = false
  }
  tags = var.tags
}

### Steps to Reproduce

* Apply EKS Cluster using AWS provider version e.g. 5.51.1.
* Apply the same code using AWS provider version e.g. 5.65.0.
* This results in
```
# module.eks_cluster.aws_eks_cluster.eks_cluster must be replaced
--
# Warning: this will destroy the imported resource
 -/+ resource "aws_eks_cluster" "eks_cluster" {
 ~ arn                           = "arn:aws:eks:us-east-1:123456789012:cluster/mycluster" -> (known after apply)
 ~ bootstrap_self_managed_addons = false -> true # forces replacement
```

### Would you like to implement a fix?

No

**Comment by afischer-opentext-com** [comment]
Dupe of #[38950](https://github.com/hashicorp/terraform-provider-aws/issues/38950) as it seems. Sorry.

**Comment by ewbankkit** [comment]
@afischer-opentext-com Thanks for raising this issue.
It has already been noticed in #38950. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
