### ISSUE TITLE
AWS Network Load Balancer & Gateway Load Balancer now supports configurable TCP idle timeout

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#39149]
#### Network Load Balancer

> Today AWS Network Load Balancer (NLB) is launching a new capability that allows you to align the TCP idle timeout value of NLB with clients and target applications.

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/09/aws-network-load-balancer-tcp-idle-timeout/)
* [Blog post](https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-nlb-tcp-configurable-idle-timeout/)

#### Gateway Load Balancer

> Today AWS Gateway Load Balancer (GWLB) is launching a new capability that allows you to align the TCP idle timeout value of GWLB with clients and target appliances.

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/09/aws-gateway-load-balancer-tcp-idle-timeout/)
* [Blog post](https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-configurable-tcp-idle-timeout-for-gateway-load-balancer/)

### Affected Resource(s) and/or Data Source(s)

* `aws_lb_listener`

### Potential Terraform Configuration

```terraform
resource "aws_lb_listener" "example" {
  tcp_idle_timeout = 600
}
```

**Comment by VarunTyagi86** [comment]
Do we know by when this configuration would be available in terraform ?

**Comment by ddericco** [comment]
This is being worked on.
