### ISSUE TITLE
[Bug]: data.aws_secretsmanager_secret_version no longer pulls secrets

### ISSUE THREAD

**Issue by jfgordon2** [hashicorp/terraform-provider-aws#39141]
### Terraform Core Version

1.9.4

### AWS Provider Version

5.65.0

### Affected Resource(s)

data.aws_secretsmanager_secret_version

### Expected Behavior

This data resource should successfully read a secret with a provided ARN.  This was tested with a cross-account secret, and on the `darwin_arm64` platform.  This doesn't appear to affect the `linux_amd64` version.

### Actual Behavior

The output is that it will return as "Still reading..." until it times out after 20 minutes.

### Terraform Configuration Files

data "aws_secretsmanager_secret_version" "secret" {
  secret_id = "arn:aws:secretsmanager:us-west-2:1234567890:secret:secret_path"
}

### Steps to Reproduce

On an M1 mac, run terraform plan from one AWS account with the above data block on version 5.65.0.  5.64.0 doesn't appear affected.

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Relates:
* https://github.com/hashicorp/terraform-provider-aws/issues/39110
* https://github.com/hashicorp/terraform-provider-aws/issues/39115
* https://github.com/hashicorp/terraform-provider-aws/issues/39125

**Comment by ewbankkit** [comment]
@jfgordon2 Assuming that the Go 1.22.6 downgrade with Terraform AWS Provider **v5.67.0** fixed this problem, I'm going to close this issue. Discussion will continue in https://github.com/hashicorp/terraform-provider-aws/issues/39311.
