### ISSUE TITLE
[Enhancement]: module can missing additional settings response timeout 

### ISSUE THREAD

**Issue by billnbell3** [hashicorp/terraform-provider-aws#39148]
### Description

I cannot find a way to set in module "can" the response timeout. The default of 30 seconds in Cloudfront - does not change.

```module "cdn" {
  source = "terraform-aws-modules/cloudfront/aws"
 ...
```

### Potential Terraform Configuration

```terraform
response_timeout = 60
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @billnbell3 👋 Thank you for taking the time to raise this! Can you provide a bit more information about what you're requesting? Issues in this repository are used to track bugs and feature requests for the Terraform AWS Provider itself, so if this is a request for changes to the `terraform-aws-modules/cloudfront/aws` module, it will need to go to that module's repository.

**Comment by justinretzolk** [comment]
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.
