### ISSUE TITLE
[Docs]: Badly placed "}" in example in ECR replication config terraform example

### ISSUE THREAD

**Issue by bsoltesz-hawkeye** [hashicorp/terraform-provider-aws#39157]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_replication_configuration#multiple-region-usage

### Description

The rule block is prematurely closed before the second destination block.

In comparison, the python and typescript version of the documentation groups the multiple destination configs within a single rule.

### Would you like to implement a fix?

None

**Comment by jmonte-sph** [comment]
@bsoltesz-hawkeye , the closing curly brace looks ok

<img width="695" alt="Screenshot 2024-09-05 at 6 03 26 PM" src="https://github.com/user-attachments/assets/909c7ea0-1bb8-41f3-8b5f-abb8f77fae03">
