### ISSUE TITLE
[Enhancement]: Add Policy-Min-TLS-1-2-PFS-2023-10 to AWS ElasticSearch Documentation

### ISSUE THREAD

**Issue by aidanhyland** [hashicorp/terraform-provider-aws#39158]
### Description

According to [AWS docs](https://docs.aws.amazon.com/cli/latest/reference/es/update-elasticsearch-domain-config.html) and [SecurityHub Docs](https://docs.aws.amazon.com/securityhub/latest/userguide/es-controls.html#es-8) 

    Specify the TLS security policy that needs to be applied to the HTTPS endpoint of Elasticsearch domain. It can be one of the following values:

        Policy-Min-TLS-1-0-2019-07: TLS security policy that supports TLS version 1.0 to TLS version 1.2
        Policy-Min-TLS-1-2-2019-07: TLS security policy that supports only TLS version 1.2
        Policy-Min-TLS-1-2-PFS-2023-10: TLS security policy that supports TLS version 1.2 to TLS version 1.3 with perfect forward secrecy cipher suites

### Affected Resource(s) and/or Data Source(s)

AWS Elasticsearch.

### Potential Terraform Configuration

```terraform
According to your docs, only two values are supported [TF docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain#tls_security_policy)
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @aidanhyland 👋 Thank you for taking the time to raise this! It looks like this is a documentation error (the value is already accepted by the provider), so I've opened a pull request to update the documentation appropriately.
