### ISSUE TITLE
[New Resource]: aws sagemaker model registry

### ISSUE THREAD

**Issue by mohit2512sharma** [hashicorp/terraform-provider-aws#39164]
### Description

At the moment, in the `aws` provider, there is a resource `aws_sagemaker_model` but there is no resource available for creating model registry in sagemaker. 
Reference: https://docs.aws.amazon.com/sagemaker/latest/dg/model-registry.html

### Requested Resource(s) and/or Data Source(s)

* aws_sagemaker_model_registry

### References

https://docs.aws.amazon.com/sagemaker/latest/dg/model-registry.html

### Would you like to implement a fix?

None

**Comment by deepakbshetty** [comment]
Sagemaker model registry is a catalog of models and not a aws resource in in itself. I dont believe this is valid request.

**Comment by DrFaust92** [comment]
This doesnt correspond to a specific resource in Sagemaker API:
https://docs.aws.amazon.com/sagemaker/latest/dg/model-registry-model-group.html specifies model_package_group resource that is already supported.

Closing for now, if there is a more specific requirement please open a new issue with relevant details.
