### ISSUE TITLE
[Bug]: ECS execution role unable to fetch secrets in 5:65.0

### ISSUE THREAD

**Issue by johnzhu-optum** [hashicorp/terraform-provider-aws#39173]
### Terraform Core Version

1.8.5

### AWS Provider Version

5.65.0

### Affected Resource(s)

data.aws_secretsmanager_secret

### Expected Behavior

module.<some_name>.data.aws_secretsmanager_secret.ecs-secrets["a_key_name"]: Read complete after 1s [id=arn:aws:secretsmanager:us-east-1:<ID>:secret:<secret>]

### Actual Behavior

module.<some_name>.data.aws_secretsmanager_secret.ecs-secrets["a_key_name"]: Still reading... [29m51s elapsed]

### Relevant Error/Panic Output Snippet

```shell
versions 5.64.0 and below works good.

ECS task execution role, defined in ecs task, has proper permission to read the secret.
```

### Terraform Configuration Files

terraform {
  required_version = "~> 1.8.0"
  backend "s3" {
    region         = "us-east-1"
  }
  required_providers {
    aws = {
      version = "~> 5.0"
      source  = "hashicorp/aws"
    }
  }
}

### Steps to Reproduce

1, create ECS task execution role
2. give permission to get/describe a secret to the role
3. create ECS task, use aws_secretsmanager_secret to fetch the secret arn by name
4.  use the role for. execution_role_arn in ECS task json definition
5. apply with terraform

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Relates:
* https://github.com/hashicorp/terraform-provider-aws/issues/39141
* https://github.com/hashicorp/terraform-provider-aws/issues/39110
* https://github.com/hashicorp/terraform-provider-aws/issues/39115
* https://github.com/hashicorp/terraform-provider-aws/issues/39125

**Comment by ewbankkit** [comment]
@johnzhu-optum Assuming that the Go 1.22.6 downgrade with Terraform AWS Provider **v5.67.0** fixed this problem, I'm going to close this issue. Discussion will continue in https://github.com/hashicorp/terraform-provider-aws/issues/39311.
