### ISSUE TITLE
[Bug]: data "aws_cognito_user_pool" unexpected error occur

### ISSUE THREAD

**Issue by richiesreng** [hashicorp/terraform-provider-aws#39183]
### Terraform Core Version

1.0.0

### AWS Provider Version

Not specified

### Affected Resource(s)

data "aws_cognito_user_pool"

### Expected Behavior

This should be able to fetch as normal.

### Actual Behavior

It is working yesterday and I just encounter this issue today when trying to access "aws_cognito_user_pool" by data source.
<img width="1067" alt="Screenshot 2024-09-06 at 2 04 03 in the afternoon" src="https://github.com/user-attachments/assets/dcda57cf-18ca-4b35-a99a-895023e64174">

### Terraform Configuration Files

N/A

### Steps to Reproduce

1. Create resource aws_cognito_user_pool
2. Access it back via data source by passing cognito user pool id
3. The issue occur

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/38869.
