### ISSUE TITLE
aws_lambda_function resource: implement zip-creation/management functionality

### ISSUE THREAD

**Issue by yermulnik** [hashicorp/terraform-provider-aws#3918]
### Terraform Version
Terraform v0.11.5
+ provider.archive v1.0.0
+ provider.aws v1.8.0
+ provider.template v1.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_lambda_function

### Expected Behavior
Instead of S3 or a local zip, user can specify the files right in `aws_lambda_function` resource and it will create a zip with all the necessary settings for Lambda.

### Actual Behavior
User has to use S3 or `archive_file` data source to create zip, ensure files in archive have appropriate access permissions either manually or by setting permission explicitly using `null_resource` with local provisioner.

### Important Factoids
https://github.com/terraform-providers/terraform-provider-archive/issues/10#issuecomment-376196789

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/terraform-providers/terraform-provider-archive/issues/10

**Comment by ErrantConstruct** [comment]
This would be great to have. I've recently hit issues using the archive_file resource to create the lambda package.

**Comment by yermulnik** [comment]
Any approx ETA on this?

**Comment by thecodingcheese** [comment]
This is a huge set back in the provider for lambdas. Without a work around, each time a lambda is changed, updated or created permission denied is always the result. One can upload a zip from the console and fix this issue or I seem to have to set some explicit permissions and repeat a lot of extra code. An ETA or update on this would be great.

**Comment by yermulnik** [comment]
Bumping to prevent from closing as this still is beneficial for those who suffer from https://github.com/hashicorp/terraform-provider-archive/issues/10
