### ISSUE TITLE
[Bug]: Unable to disable Dynamodb table TTL

### ISSUE THREAD

**Issue by jayjanssen** [hashicorp/terraform-provider-aws#39195]
### Terraform Core Version

1.6.5

### AWS Provider Version

5.66.0

### Affected Resource(s)

aws_dynamodb_table

### Expected Behavior

I should be able to disable TTLs on my dynamo table in Terraform:

```hcl
  ttl {
    enabled = false
    attribute_name = "ttlK"
  }
```

### Actual Behavior

I get a provider validation error that i cannot have a name while ttl.enabled is false.  If I try to remove the name, I get an error from the Dynamo API itself.

### Relevant Error/Panic Output Snippet

```console
│ Error: updating AWS DynamoDB Table (ttl_test): updating Time To Live: operation error DynamoDB: UpdateTimeToLive, https response error StatusCode: 400, RequestID: 4QV78T54MGHV732LBM9N0SUOIVVV4KQNSO5AEMVJF66Q9ASUAAJG, api error ValidationException: 1 validation error detected: Value '' at 'timeToLiveSpecification.attributeName' failed to satisfy constraint: Member must have length greater than or equal to 1
│ 
│   with aws_dynamodb_table.ttl_test,
│   on ttl_test.tf line 1, in resource "aws_dynamodb_table" "ttl_test":
│    1: resource "aws_dynamodb_table" "ttl_test" {
│ 
╵
```

and

```console
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Invalid Attribute Combination
│ 
│ Attribute "ttl[0].attribute_name" cannot be specified when "ttl[0].enabled" is "false".
│ ttl[0].attribute_name
│ 
│   with aws_dynamodb_table.ttl_test,
│   on ttl_test.tf line 1, in resource "aws_dynamodb_table" "ttl_test":
│    1: resource "aws_dynamodb_table" "ttl_test" {
│
```

### Terraform Configuration Files

```hcl
resource "aws_dynamodb_table" "ttl_test" {
  name = "ttl_test"

  billing_mode = "PAY_PER_REQUEST"

  hash_key  = "PK"
  range_key = "SK"

  attribute {
    name = "PK"
    type = "S"
  }

  attribute {
    name = "SK"
    type = "S"
  }

  ttl {
    enabled = true
    attribute_name = "ttlK"
  }
}
```

### Steps to Reproduce

1. Create the table described in the TF config files above
2. Try to set `enabled=false` on line 20, produces first error listed in "Relevant error" section
3. Additionally try to comment out attribute name: `#attribute_name = "ttlK"` to get the second error

### Important Factoids

I'm pretty sure this validation check is the issue: 
https://github.com/hashicorp/terraform-provider-aws/blame/main/internal/service/dynamodb/table.go#L2471-L2475

With it, there is seemingly no way to disable TTLs via Terraform

### Would you like to implement a fix?

None

**Comment by YakDriver** [comment]
I was able to reproduce this problem immediately and I'm working on a fix. The time-consuming part is waiting for testing: AWS only allows disabling TTL after it's been enabled for an hour. 🕥
