### ISSUE TITLE
[Bug]: NFW logging config fails when log_type = TLS is added

### ISSUE THREAD

**Issue by sanjeevgopal** [hashicorp/terraform-provider-aws#39197]
### Terraform Core Version

1.9.5

### AWS Provider Version

5.66.0

### Affected Resource(s)

- aws_networkfirewall_logging_configuration

### Expected Behavior

When the log_destination_config for TLS is added as below:

```hcl
    log_destination_config {
      log_destination = {
        logGroup = aws_cloudwatch_log_group.example.name
      }
      log_destination_type = "CloudWatchLogs"
      log_type             = "TLS"
    }
```

It should get enabled on the NFW.

### Actual Behavior

It fails. It works fine with log_type = FLOW or log_type = ALERT, but when the log_type = TLS, it fails.

### Relevant Error/Panic Output Snippet

```shell
Error: adding NetworkFirewall Logging Configuration (arn:aws:network-firewall:region:account:firewall/example): operation error Network Firewall: UpdateLoggingConfiguration, https response error StatusCode: 400, RequestID: 70670c57-7452-4e4c-9037-b5161c670b99, InvalidRequestException: Given logging configuration attempts to create/modify multiple log destination configs
```

### Terraform Configuration Files

```hcl
resource "aws_networkfirewall_logging_configuration" "example" {
  firewall_arn = aws_networkfirewall_firewall.example.arn

  logging_configuration {
    log_destination_config {
      log_destination = {
        logGroup = aws_cloudwatch_log_group.example_flow.name
      }
      log_destination_type = "CloudWatchLogs"
      log_type             = "FLOW"
    }
    log_destination_config {
      log_destination = {
        logGroup = aws_cloudwatch_log_group.example_alert.name
      }
      log_destination_type = "CloudWatchLogs"
      log_type             = "ALERT"
    }
    log_destination_config {
      log_destination = {
        logGroup = aws_cloudwatch_log_group.example_tls.name
      }
      log_destination_type = "CloudWatchLogs"
      log_type             = "TLS"
    }
  }
}
```

### Steps to Reproduce

Create log_destination_config for FLOW, ALERT and TLS. 

### Would you like to implement a fix?

None

**Comment by esim-sa-1ot** [comment]
Same issue in 5.68.0

**Comment by AJD-UK** [comment]
Similar to https://github.com/hashicorp/terraform-provider-aws/issues/38917

**Comment by lorodoes** [comment]
I found the issue. I over looked one line of code during the expansion.
[Problem Code](https://github.com/hashicorp/terraform-provider-aws/blob/dde75bdef252c4ff51ae69e7d9141fea6e4dec05/internal/service/networkfirewall/logging_configuration.go#L289)

I will see if I can't get a MR up shortly. Sorry for missing this.

**Comment by lorodoes** [comment]
#40092 This PR does have the fix for this issue.
