### ISSUE TITLE
[New Data Source]: aws_cloudwatch_event_buses

### ISSUE THREAD

**Issue by tsanton** [hashicorp/terraform-provider-aws#39209]
### Description

I'm hoping we can have a datasource to list event bridge event buses
- Go SDK [here](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/eventbridge#Client.ListEventBuses)
- AWS api reference [here](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_ListEventBuses.html)

### Requested Resource(s) and/or Data Source(s)

aws_cloudwatch_event_buses

### Potential Terraform Configuration

Thinking the implementation could look something like this:

```terraform
data "aws_cloudwatch_event_buses" "example" {
  name_prefix = "example-bus"
}
```

And output something like this either this:

```json
[
  { 
     "arn": "<bus-arn>",
     "name": "examle-bus-1",
     "description": "<string>",
     "policy": "<policy-name>",
     "last_modified_time": "<timestamp>",
     "creation_time": "<timestamp>"
  },
  { 
     "arn": "<bus-arn>",
     "name": "examle-bus-2",
     "description": "<string>",
     "policy": "<policy-name>",
     "last_modified_time": "<timestamp>",
     "creation_time": "<timestamp>"
  }
]
```

or (preferably) this:

```json
{
  "examle-bus-1": { 
     "arn": "<bus-arn>",
     "name": "examle-bus-1",
     "description": "<string>",
     "policy": "<policy-name>",
     "last_modified_time": "<timestamp>",
     "creation_time": "<timestamp>"
  },
  "examle-bus-2": { 
     "arn": "<bus-arn>",
     "name": "examle-bus-2",
     "description": "<string>",
     "policy": "<policy-name>",
     "last_modified_time": "<timestamp>",
     "creation_time": "<timestamp>"
  }
}
```

### Would you like to implement a fix?

I believe it's a great first issue and I would love to, but unfortunately I do not have the time for the next few months.

**Comment by tsanton** [comment]
@kamilturek any progress on this?

**Comment by kamilturek** [comment]
Sorry, I haven't had time to pick it up. I should be completing it soon.
