### ISSUE TITLE
[Bug]: ap-southeast-5

### ISSUE THREAD

**Issue by raanand-dig** [hashicorp/terraform-provider-aws#39224]
### Terraform Core Version

1.9.5

### AWS Provider Version

5.66.0

### Affected Resource(s)

- data.aws_region

### Expected Behavior

```hcl
provider "aws" {
  region                 = "ap-southeast-5"
}

data aws_region data {}

output output {
  value = data.aws_region.data
}
```

should return region name

### Actual Behavior

```
╷
│ Error: finding Region by name
│
│   with data.aws_region.data,
│   on main.tf line 6, in data "aws_region" "data":
│    6: data aws_region data {
│
│ region not found for name "ap-southeast-5"
╵
```

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: finding Region by name
│
│   with data.aws_region.data,
│   on main.tf line 6, in data "aws_region" "data":
│    6: data aws_region data {
│
│ region not found for name "ap-southeast-5"
╵
```

### Terraform Configuration Files

provider "aws" {
  region                 = "ap-southeast-5"
}

data aws_region data {}

output output {
  value = data.aws_region.data
}

### Steps to Reproduce

apply 

### Debug Output

[a.txt](https://github.com/user-attachments/files/16931641/a.txt)

### Panic Output

│ Error: finding Region by name
│
│   with data.aws_region.data,
│   on main.tf line 6, in data "aws_region" "data":
│    6: data aws_region data {
│
│ region not found for name "ap-southeast-5"

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/38989.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/36188.

**Comment by Shahard2** [comment]
@ewbankkit when we will have a fix for this?
