### ISSUE TITLE
[Enhancement]: Update the documentation to have all options for engine name

### ISSUE THREAD

**Issue by runlevel5** [hashicorp/terraform-provider-aws#39240]
### Description

<img width="843" alt="Screenshot 2024-09-10 at 3 36 34 PM" src="https://github.com/user-attachments/assets/15a037ff-f91d-474a-b6e4-634eab51cfbc">

There are more choices for `engine_name` for example for those Aurora Serverless MySQL yet we do not have those options documented.

### Affected Resource(s) and/or Data Source(s)

aws_dms_endpoint v5.66.0

### Would you like to implement a fix?

Yes

**Comment by Shiravani24** [comment]
will raise a PR for the documentation.
