### ISSUE TITLE
aws_ecr_repository_policy swallows InvalidParameterException

### ISSUE THREAD

**Issue by jeffnappi** [hashicorp/terraform-provider-aws#3924]
### Terraform Version
```
Terraform v0.11.5
+ provider.aws v1.10.0
```
### Affected Resource(s)
Please list the resources as a list, for example:
- aws_ecr_repository_policy

### Terraform Configuration Files
The following config results in an invalid policy :flushed: 

```hcl
variable "projects" {
  type = "list"

  default = [
    "alpha",
    "beta",
    "gamma",
    "delta",
  ]
}

variable "account_arns" {
  type = "map"
  # <ids> here are actual AWS account ids.
  # the :* portion is invalid and should be :root
  default = {
    test       = "arn:aws:iam::<id1>:*"
    staging    = "arn:aws:iam::<id2>:*"
    production = "arn:aws:iam::<id3>:*"
  }
}
data aws_iam_policy_document "ecr_policy" {
  statement {
    sid = "ECROrgReadAccess"

    actions = [
      "ecr:BatchCheckLayerAvailability",
      "ecr:GetDownloadUrlForLayer",
      "ecr:GetRepositoryPolicy",
      "ecr:DescribeRepositories",
      "ecr:ListImages",
      "ecr:DescribeImages",
      "ecr:BatchGetImage"
    ]

    principals {
      identifiers = ["${values(var.account_arns)}"]
      type        = "AWS"
    }
  }
}

resource aws_ecr_repository_policy "ecr_policy" {
  count = "${length(var.projects)}"
  repository = "${element(var.projects, count.index)}"
  policy = "${data.aws_iam_policy_document.ecr_policy.json}"
}

```

### Debug Output
```
* aws_ecr_repository_policy.ecr_policy.0: InvalidParameterException: Invalid parameter at 'PolicyText' failed to satisfy constraint: 'Invalid repository policy provided'
```
If needed I can pull the full log - can't include the full debug log at the moment.

### Expected Behavior
Terraform should error with the exception message.

### Actual Behavior
Terraform continually "retries" waiting for the resource to be created.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Nothing special.

### References
None.

**Comment by yusuken-freee** [comment]
Does anyone know that there are any updates on this?
I am having same issue and can not perform `terraform apply` to AWS.😢

**Comment by FelikZ** [comment]
@yusuken-freee normally this error mean that you have malformed or invalid json policy. I've fixed mine, so issue anymore. (use to have invalid account id)

**Comment by jeffnappi** [comment]
I still consider this a bug since the user is unaware that they have an invalid policy. It should fail as described in the issue. I may tackle this myself and put up a PR if there's enough interest.

**Comment by yusuken-freee** [comment]
@FelikZ 
> normally this error mean that you have malformed or invalid json policy.
as you said, yes, it should be triggered by malformed(invalid) json, and I have checked mine. But the error came up was not what I have changed (meaning, there was no changes on `aws_ecr_repository_policy` resource)🤔

**Comment by bgvladedivac** [comment]
hi guys, any plan to fix this soon ?

**Comment by msoreco** [comment]
Seeing the same issue on v0.12.17.  I can create and save a valid policy statement in AWS console, then copy and paste it into terraform aws_ecr_repository_policy policy parameter, and it fails in terraform apply.

**Comment by Va1** [comment]
@bgvladedivac i am experiencing the same issue... did you find a workaround?

**Comment by yumingqiao** [comment]
I am having the same issue with a blank policy:

```
policy      = jsonencode(
  {
    Statement = []
    Version   = "2012-10-17"
  }
)
```
