### ISSUE TITLE
[Docs]:wrong example for aws_ebs_snapshot_block_public_access

### ISSUE THREAD

**Issue by toralf-hlag** [hashicorp/terraform-provider-aws#39243]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ebs_snapshot_block_public_access

### Description

state = "block-all-sharing"

is not covered by _Allowed values are block-all, block-new-sharing, unblocked._

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Hi @toralf-hlag,
thanks for raising the issue.

I think the example code is right, but the state mentioned  in the text (`block-all`) not correct.
Here is a [link to the CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-snapshotblockpublicaccess.html).

Will create a PR for fixing this.
