### ISSUE TITLE
[New Data Source]: aws_spot_datafeed_subscription

### ISSUE THREAD

**Issue by TheNumberOne** [hashicorp/terraform-provider-aws#39259]
### Description

This is a data source that mirrors the [aws_spot_datafeed_subscription resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/spot_datafeed_subscription). Every AWS account is allowed up to one spot data-feed subscription, which updates an s3 bucket with the latest EC2 spot instance prices.

### Requested Resource(s) and/or Data Source(s)

* aws_spot_datafeed_subscription

### Potential Terraform Configuration

```terraform
data "aws_spot_datafeed_subscription" "default" { }
```

Ideally, the output would mirror the [arguments](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/spot_datafeed_subscription#argument-reference) for the `aws_spot_datafeed_subscription` resource.

### References

* AWS Go SDK v2: [DescribeSpotDatafeedSubscription](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2#Client.DescribeSpotDatafeedSubscription)
* awscli2: [describe-spot-datafeed-subscription](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/describe-spot-datafeed-subscription.html)
* AWS EC2 API Reference: [DescribeSpotDatafeedSubscription](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeSpotDatafeedSubscription.html)
* AWS EC2 User Guide: [Track your Spot Instance costs using the Spot Instance data feed](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-data-feeds.html)
* hashicorp/aws docs: [resource "aws_spot_datafeed_subscription"](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/spot_datafeed_subscription)

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Let me have a look
