### ISSUE TITLE
[Bug]: default_tags tags ids null instead of a empty map starting with aws provider 5.66

### ISSUE THREAD

**Issue by CyrilDevOps** [hashicorp/terraform-provider-aws#39278]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.66.0

### Affected Resource(s)

data.aws_default_tags.current.tags

### Expected Behavior

expect tags to be an empty map

### Actual Behavior

with aws 5.66.0 data.aws_default_tags.current.tags is null

### Terraform Configuration Files

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.66.0"
    }
  }
}

provider "aws" {
  region  = "us-east-2"

  default_tags {
    tags = {
    }
  }
}

data "aws_default_tags" "current" {}

output "test" {
value = data.aws_default_tags.current
}

output "test2" {
value = length(data.aws_default_tags.current.tags)
}

### Steps to Reproduce

do a plan with 5.65.0 
you get
Changes to Outputs:
  + test  = {
      + id   = "aws"
      + tags = {}
    }
  + test2 = 0

do a plan with 5.66.0
you get 
Changes to Outputs:
  + test = {
      + id   = "aws"
      + tags = null
    }

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.
╷
│ Error: Invalid function argument
│
│   on t.tf line 26, in output "test2":
│   26: value = length(data.aws_default_tags.current.tags)
│     ├────────────────
│     │ while calling length(value)
│     │ data.aws_default_tags.current.tags is null
│
│ Invalid value for "value" parameter: argument must not be null.
╵

### Would you like to implement a fix?

None

**Comment by CyrilDevOps** [comment]
We don't have default tags in our provider
provider "aws" {
region = "us-east-2"
}

and some code in our module do 
  non_default_tags = length(data.aws_default_tags.default_tags.tags) > 0 ? { .... } : local.additional_tags

that work with 5.65, but with 5.66 plan fail because of length(null) problem.

**Comment by kkopachev** [comment]
should be fixed by https://github.com/hashicorp/terraform-provider-aws/pull/39261 in 5.67

**Comment by breathingdust** [comment]
Closed via #39261
