### ISSUE TITLE
[Docs]: Conflicting aws_lb_listener protocol documentation for NLBs

### ISSUE THREAD

**Issue by mtomasino-solv** [hashicorp/terraform-provider-aws#39316]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener

### Description

I see these two pieces of information on the aws_lb_listener page:
* For Network Load Balancers, valid values are TCP, TLS, UDP, and TCP_UDP. 
* Please note that listeners that are attached to Application Load Balancers must use either HTTP or HTTPS protocols while listeners that are attached to Network Load Balancers must use the TCP protocol.

Which of these is correct? AWS seems to say that all those protocols are valid for Network Load Balancers.

### References

https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-listeners.html#listener-configuration

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Hi @mtomasino-solv;
thanks for raising the issue!
As part of the description for argument `protocol` the possible assignments for NLB /ALBs is already explained. I am thinking about the removal of that Note

> NOTE::
>Please note that listeners that are attached to Application Load Balancers must use either HTTP or HTTPS protocols while listeners that are attached to Network Load Balancers must use the TCP protocol.

Would that be an option for you?

**Comment by mtomasino-solv** [comment]
If the note is incorrect, then yes please remove it
