### ISSUE TITLE
[Docs]: Incorrect description of aws_ce_anomaly_subscription threshold_expression arguments

### ISSUE THREAD

**Issue by rorysedgwick** [hashicorp/terraform-provider-aws#39344]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ce_anomaly_subscription#threshold-expression

### Description

[`threshold_expression`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ce_anomaly_subscription#threshold-expression)s supports various boolean operators to create multi-dimensional expressions. The descriptions for the `or` and `not` arguments appear to incorrectly be duplicates of the `and` argument:

- `and` - (Optional) Return results that match both `Dimension` objects.
- `not` - (Optional) Return results that match both `Dimension` object.
- `or` - (Optional) Return results that match both `Dimension` object.

This should be something along the lines of:
- `and` - (Optional) Return results that match both `Dimension` objects.
- `not` - (Optional) Return results that **do not match** the `Dimension` object.
- `or` - (Optional) Return results that match **either** `Dimension` object.

### Would you like to implement a fix?

Yes

**Comment by Jyots6914** [comment]
Will Submit PR for document correction
