### ISSUE TITLE
[Bug]: aurora global cluster keep recreating if new global cluster from existing primary cluster which has database_name

### ISSUE THREAD

**Issue by wangyi198682** [hashicorp/terraform-provider-aws#39368]
### Terraform Core Version

Terraform v1.9.0

### AWS Provider Version

5.45.0

### Expected Behavior

no drift or no diffs when terraform plan again.

### Actual Behavior

after second round run terraform plan or apply, we saw that it tries to recreate global cluster.

```console
- database_name                = "mydb" -> null # forces replacement
```

and it recreates global cluster, this will cause global cluster's members being removed.

```console
aws_rds_global_cluster.this[0]: Destroying... [id=example]
aws_rds_global_cluster.this[0]: Destruction complete after 3s
aws_rds_global_cluster.this[0]: Creating...
aws_rds_global_cluster.this[0]: Creation complete after 0s [id=example]


Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
```

### Terraform Configuration Files

```hcl
resource "aws_rds_cluster" "primary" {
  //other configurations
  database_name   = "mydb"
  lifecycle {
    ignore_changes = [global_cluster_identifier]
  }
}

resource "aws_rds_global_cluster" "example" {
  force_destroy                = true
  global_cluster_identifier    = "example"
  source_db_cluster_identifier = aws_rds_cluster.primary.arn
}
```

### Steps to Reproduce

step1: terraform plan & apply.
step2: after all the resources created, then run terraform plan again.

### Would you like to implement a fix?

None

**Comment by wangyi198682** [comment]
and I solve it by using following change to "aws_rds_global_cluster"
```
lifecycle {
    ignore_changes = [   
      database_name,
    ]
  }
```

**Comment by justinretzolk** [comment]
Similar #28187
