### ISSUE TITLE
[Enhancement]: r/aws_glue_catalog_table_optimizer Add support for expiring snapshots and orphan file deletion

### ISSUE THREAD

**Issue by nickdelnano** [hashicorp/terraform-provider-aws#39405]
### Description

AWS has released [new features to Glue table optimizers to managed storage](https://aws.amazon.com/blogs/big-data/the-aws-glue-data-catalog-now-supports-storage-optimization-of-apache-iceberg-tables/). This issue tracks adding the new features to `aws_glue_catalog_table_optimizer` resource.

`aws_glue_catalog_table_optimizer` resource was added in https://github.com/hashicorp/terraform-provider-aws/pull/38052.

### Affected Resource(s) and/or Data Source(s)

aws_glue_catalog_table_optimizer

### Potential Terraform Configuration

```terraform

# Compaction (already exists)
resource "aws_glue_catalog_table_optimizer" "example" {
  catalog_id    = "123456789012"
  database_name = "example_database"
  table_name    = "example_table"
  configuration {
    role_arn = "arn:aws:iam::123456789012:role/example-role"
    enabled  = true
  }
  type = "compaction"
}

# Snapshot expiration (new)
resource "aws_glue_catalog_table_optimizer" "example" {
  catalog_id    = "123456789012"
  database_name = "example_database"
  table_name    = "example_table"
  configuration {
    role_arn = "arn:aws:iam::123456789012:role/example-role"
    enabled  = true
    retentionConfiguration {
      icebergConfiguration {
        snapshotRetentionPeriodInDays = 1
        numberOfSnapshotsToRetain = 2
        cleanExpiredFiles = true
      }
    }
  }
  type = "retention"
}

# Orphan file removal (new)
resource "aws_glue_catalog_table_optimizer" "example" {
  catalog_id    = "123456789012"
  database_name = "example_database"
  table_name    = "example_table"
  configuration {
    role_arn = "arn:aws:iam::123456789012:role/example-role"
    enabled  = true
    orphanFileDeletionConfiguration {
      icebergConfiguration {
        orphanFileRetentionPeriodInDays = 5
        location = "s3://example-bucket/path"
      }
    }
  }
  type = "orphan_file_deletion"
}


```

### References

CreateTableOptimizer API docs https://docs.aws.amazon.com/glue/latest/webapi/API_CreateTableOptimizer.html
UpdateTableOptimizer API docs https://docs.aws.amazon.com/glue/latest/webapi/API_UpdateTableOptimizer.html

The individual API docs aren't updated yet but the [Table Optimizer API docs](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-table-optimizers.html) are. Summary of changes:
- TableOptimizer -  `type` field now supports values `retention` and `orphan_file_deletion`
- TableOptimizerConfiguration - expanded to support more fields
- RetentionConfiguration - new
- IcebergRetentionConfiguration - new
- OrphanFileDeletionConfiguration - new
- IcebergOrphanFileDeletionConfiguration - new

### Would you like to implement a fix?

None

**Comment by ryanmiville** [comment]
I am interested in working on this issue.

**Comment by nickdelnano** [comment]
@ryanmiville please go ahead!
