### ISSUE TITLE
[Enhancement]: Need a mechanism to prepare an agent after creating aws_bedrockagent_agent_action_group resources 

### ISSUE THREAD

**Issue by giovanni-roque-gilead** [hashicorp/terraform-provider-aws#39400]
### Description

It seems that the Terraform resource for Action Groups for Agents for Amazon Bedrock does not [prepare an agent](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent_PrepareAgent.html) so that the latest changes are available for testing. 

Although there is a parameter to prepare the agent itself when the agent resource (aws_bedrockagent_agent) is updated or created since this [issue](https://github.com/hashicorp/terraform-provider-aws/issues/37162) was closed, AWS is very clear in its [documentation](https://docs.aws.amazon.com/bedrock/latest/userguide/agents-action-add.html) that it's necessary to prepare the agent after the creation of action groups as well. The resource for creating action groups is a different resource (aws_bedrockagent_agent_action_group) so we need a way to prepare the agent after the creation of action groups as well through Terraform, otherwise this has to be done through SDK or CLI.

Two ways this could be achieved:

- An argument such as prepare_agent added to the aws_bedrockagent_agent_action_group resource, which can cause a change to the agent but not in the agent resource (aws_bedrockagent_agent) itself
- A new resource such as aws_bedrockagent_preparation that would prepare the agent on create or update. To trigger it to run, perhaps you need to add dependencies to the above resources, which may not make sense since this is an action and not a resource.

### Affected Resource(s) and/or Data Source(s)

aws_bedrockagent_agent_action_group

### Potential Terraform Configuration

```terraform
resource "aws_bedrockagent_agent_action_group" "example" {
  action_group_name          = "example"
  agent_id                   = "GGRRAED6JP"
  agent_version              = "DRAFT"
  skip_resource_in_use_check = true
  prepare_agent              = true
  action_group_executor {
    lambda = "arn:aws:lambda:us-west-2:123456789012:function:example-function"
  }
  api_schema {
    payload = file("path/to/schema.yaml")
  }
}
```

### References

- Closed issue that included the prepare_agent parameter in the Terraform resource for agents: https://github.com/hashicorp/terraform-provider-aws/issues/37162
- Blog Post about updating action groups with Terraform: https://blog.avangards.io/how-to-manage-an-amazon-bedrock-agent-using-terraform#heading-workaround-for-agent-preparation-using-a-null-resource
- AWS documentation mentioning the need of preparing the agent after action group creation: https://docs.aws.amazon.com/bedrock/latest/userguide/agents-action-add.html
- Documentation about the prepare agent call: https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent_PrepareAgent.html
- Current action group resource in Terraform: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/bedrockagent_agent_action_group
- Current agent resource which has a parameter for preparing the agent: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/bedrockagent_agent
 

### Would you like to implement a fix?

None

**Comment by sasidhar-aws** [comment]
I have created pull request for this enhancement, once it is reviewed and merged, you can use the enhancement.
