### ISSUE TITLE
[Enhancement]: Changing display_name in identitystore_group should not force identitystore_group replacement.

### ISSUE THREAD

**Issue by jylitalo** [hashicorp/terraform-provider-aws#39415]
### Description

It should be possible to change identitystore_group's display_name with modify instead of destroy/apply.

### Affected Resource(s) and/or Data Source(s)

* aws_identitystore_group

### Potential Terraform Configuration

```terraform
Right now terraform claims that change in display_name forces replacement, even though group_id and identity_store_id are the only fields that are needed as keys in `resourceGroupUpdate()` function.
This is probably due to `ForceNew: true,` at https://github.com/hashicorp/terraform-provider-aws/blob/dd90468c8aec95815afca8e1aaa2b6d17d2098d2/internal/service/identitystore/group.go#L49C5-L49C24
```

### References

You can change identitystore_group name with `aws identitystore update-group --identity-store-id d-... --group-id ...-...-...-...-... --operations '[{ "AttributePath": "DisplayName","AttributeValue": "NewName" }]'`

### Would you like to implement a fix?

No

**Comment by alex-gunning** [comment]
Thank you for submitting something! This is a major issue for my company as well!
