### ISSUE TITLE
[Docs]: aws_lambda_function does not have attribute function_name

### ISSUE THREAD

**Issue by Kungfoosian** [hashicorp/terraform-provider-aws#39414]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#attribute-reference

### Description

In the "Basic Usage" section in the documentation for [aws_lambda_permission](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_permission) , the argument `function_name` refers to `aws_lambda_function.test_lambda.function_name`, but when I check the documentation for [aws_lambda_function](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#attribute-reference), `function_name` is not mentioned.

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Hi @Kungfoosian,
thanks for raising the issue.
I had a look into the documentation of the resources `aws_lambda_function` and `aws_lambda_permission`.
You are right, `function_name` is not explicitly mentioned as attribute of `aws_lambda_function` - but it is implictly by the sentence the attribute section starts with 

> This resource exports the following attributes in addition to the arguments above:

I think this is a common pattern you will see for many resources in the provider. It helps to avoid e.g duplication of information.

Hope this helps - if you have doubts/ questions, please let me know.
