### ISSUE TITLE
[Bug]: v5.68.0 ConcurrentModification error when using `aws_iam_role` with `inline_policy`

### ISSUE THREAD

**Issue by lorengordon** [hashicorp/terraform-provider-aws#39421]
### Terraform Core Version

1.9.5

### AWS Provider Version

5.68.0

### Affected Resource(s)

* `aws_iam_role`

### Expected Behavior

Terraform apply should complete successfully, creating the IAM Role and attaching all inline policies specified by the `inline_policy` blocks.

### Actual Behavior

Terraform attempts too many simultaneous operations, and the AWS API reports a `ConcurrentModification` error.

### Relevant Error/Panic Output Snippet

```shell
│ Error: creating IAM Role (tardigrade-role-epsilon-kwinax): operation error IAM: CreateRole, https response error StatusCode: 409, RequestID: 00a5d8fd-70f5-45c1-9293-7004e1f5299a, ConcurrentModification:
│
│   with module.create_roles["tardigrade-role-epsilon-kwinax"].aws_iam_role.this,
│   on ../../modules/role/main.tf line 2, in resource "aws_iam_role" "this":
│    2: resource "aws_iam_role" "this" {

```

### Terraform Configuration Files

https://github.com/plus3it/terraform-aws-tardigrade-iam-principals/tree/master/tests/create_roles

### Steps to Reproduce

Run init and apply in the `create_roles/prereq` directory.
Run init and apply in the `create_roles` directory.

### Important Factoids

Possibly related to changes from the new exclusive pattern? https://github.com/hashicorp/terraform-provider-aws/pull/39203

### Would you like to implement a fix?

None

**Comment by lorengordon** [comment]
Fwiw, if I downgrade to v5.67.0, then the error goes away. So pretty sure the problem is coming from something introduced in v5.68.0.

**Comment by lorengordon** [comment]
Hmm, nope, just a race condition. 5.67.0 is affected also. I guess maybe the error response is new, and not currently handled in the retryable errors logic?

**Comment by jar-b** [comment]
This is an odd one. We don't retry this error during role creation or inline policy creation (either via `inline_policy` or `aws_iam_role_policy`). Adding retry logic seems a reasonable solution. 

That said, I'm a bit confused how this happens on `CreateRole`, which _should_ be the first operation before anything else could happen concurrently. Perhaps there is some nuance with propagation of changes when roles are deleted and re-created? Either way, if it's happening often enough to reproduce across multiple provider versions we should attempt a fix. I'll assign myself.

**Comment by lorengordon** [comment]
Thanks @jar-b! I just tested several times with v5.69.0 and the issue indeed appears resolved. Appreciate the quick patch!
