### ISSUE TITLE
[Docs]: aws_elasticache_reserved_cache_node example and documentation inconsistent

### ISSUE THREAD

**Issue by joesteffee** [hashicorp/terraform-provider-aws#39452]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_reserved_cache_node

### Description

The example gives cache_node_count where the arguments allowed shows instance_count

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Hi @joesteffee,
thank you for bringing this issue in the documentation to our attention.
I had a look into the [source code](https://github.com/hashicorp/terraform-provider-aws/blob/3d12fc41ec3df42854018d62db520db3122046a5/internal/service/elasticache/reserved_cache_node.go#L62) and `cache_node_count` seems to be correct.
Let me update the documentation.
