### ISSUE TITLE
Lambda now supports tagging of Event Source Mappings and Code Signing Config resources

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#39468]
### Description

> AWS Lambda now supports tagging of Event Source Mappings and Code Signing Config resources

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/09/aws-lambda-tagging-event-source-mappings-code-signing-config-resources/)

### Affected Resource(s) and/or Data Source(s)

- [`aws_lambda_event_source_mapping`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping)
- [`aws_lambda_code_signing_config`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_code_signing_config)

**Comment by trutled3** [comment]
Hey @ewbankkit - I'm interesting in working on this issue.

**Comment by trutled3** [comment]
Pull Request is open and ready for review. Thank you for letting me work on this issue!
