### ISSUE TITLE
[Enhancement]: aws_ebs_snapshot data source should return StartTime

### ISSUE THREAD

**Issue by mss** [hashicorp/terraform-provider-aws#39497]
### Description

The `describe-snapshot` [API](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-snapshots.html#output) returns a field `StartTime`.

According to the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ebs_snapshot) it isn't exposed by the `aws_ebs_snapshot` data source.

### Affected Resource(s) and/or Data Source(s)

* aws_ebs_snapshot

### Potential Terraform Configuration

```terraform
data "aws_ebs_snapshot" "this" {
  snapshot_id = var.snapshot_id
}

resource "aws_ebs_volume" "this" {
  snapshot_id = data.aws_ebs_snapshot.this.snapshot_id
  ...

  tags = {
    Comment = format("Created from snapshot with timestamp %s", data.aws_ebs_snapshot.this.start_time)
  }
}
```

### References

* https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-snapshots.html#output

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Hi @mss,

thanks for raising the issue.
Let me have a look into this!
