### ISSUE TITLE
[Enhancement]: Security Group Referencing on Transit Gateway

### ISSUE THREAD

**Issue by ddericco** [hashicorp/terraform-provider-aws#39508]
### Description

Security Group Referencing allows customers to specify other SGs as references, or matching criterion in inbound security rules to allow instance-to-instance traffic. On 2024-09-25 AWS announced support for SG references between VPCs connected via Transit Gateway. 

This feature must be enabled on the Transit Gateway as well as the VPC attachments that will be performing the referencing. See the launch blog post for details.

### Affected Resource(s) and/or Data Source(s)

* aws_ec2_transit_gateway
* aws_ec2_transit_gateway_vpc_attachment

### Potential Terraform Configuration

```terraform
resource "aws_ec2_transit_gateway" "example" {
  description = "example"
  security_group_referencing_support = "enable"
}

resource "aws_ec2_transit_gateway_vpc_attachment" "example" {
  subnet_ids         = [aws_subnet.example.id]
  transit_gateway_id = aws_ec2_transit_gateway.example.id
  vpc_id             = aws_vpc.example.id
  security_group_referencing_support = "enable"
}
```

### References

- What's New: https://aws.amazon.com/about-aws/whats-new/2024/09/general-availability-security-group-referencing-aws-transit-gateway/
- Launch blog: https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-security-group-referencing-for-aws-transit-gateway/

### Would you like to implement a fix?

Yes

**Comment by acwwat** [comment]
This has been resolved by #34542.
