### ISSUE TITLE
[Enhancement]: aws_sagemaker_domain add idle shutdown options for JupyterLab and CodeEditor

### ISSUE THREAD

**Issue by jmeisele** [hashicorp/terraform-provider-aws#39521]
### Description

AWS Announced the ability to natively set idle timeout options for both JupyterLab and CodeEditor. Can be a value between integer 60 - 525600. This is time measured in minutes

### Affected Resource(s) and/or Data Source(s)

aws_sagemaker_domain

### Potential Terraform Configuration

```terraform
resource "aws_sagemaker_domain" "example" {
  // ...
  
  default_space_settings {
    jupyter_lab_app_settings {
      app_lifecycle_management {
        idle_settings {
          lifecycle_management = "ENABLED"
          idle_timeout_in_minutes = 60
          min_idle_timeout_in_minutes = 45
          max_idle_timeout_in_minutes = 90
          }
       }
    }  
  }

  default_user_settings {
    // ...
    
    jupyter_lab_app_settings {
      app_lifecycle_management {
        idle_settings {
          lifecycle_management = "ENABLED"
          idle_timeout_in_minutes = 60
          min_idle_timeout_in_minutes = 45
          max_idle_timeout_in_minutes = 90
          }
       }
    }  

    code_editor_app_settings {
      app_lifecycle_management {
        idle_settings {
          lifecycle_management = "ENABLED"
          idle_timeout_in_minutes = 60
          min_idle_timeout_in_minutes = 45
          max_idle_timeout_in_minutes = 90
        }
     }
    }
  }
}
```

### References

https://aws.amazon.com/about-aws/whats-new/2024/09/amazon-sagemaker-studio-automatic-shutdown-idle-applications/

https://docs.aws.amazon.com/sagemaker/latest/dg/studio-updated-idle-shutdown-setup.html

https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_IdleSettings.html

### Would you like to implement a fix?

No

**Comment by philipgebus** [comment]
Hi @jmeisele,

thank you for creating this feature request! 

According to the [Sagemaker CreateDomain API](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateDomain.html), there are also two additional attributes `MinIdleTimeoutInMinutes`, `MaxIdleTimeoutInMinutes`, which could be implemented in the same go. The idle config is nested within a `AppLifecycleManagement` block and it would be awesome to have this feature for jupyterlab shared spaces as well. As all of the previously mentioned aspects affect the same resource (`aws_sagemaker_domain`) and the same feature, would you mind adjusting the potential terraform config section of your issue as follows:

```HCL
resource "aws_sagemaker_domain" "example" {
  // ...
  
  default_space_settings {
    jupyter_lab_app_settings {
      app_lifecycle_management {
        idle_settings {
          lifecycle_management = "ENABLED"
          idle_timeout_in_minutes = 60
          min_idle_timeout_in_minutes = 45
          max_idle_timeout_in_minutes = 90
          }
       }
    }  
  }

  default_user_settings {
    // ...
    
    jupyter_lab_app_settings {
      app_lifecycle_management {
        idle_settings {
          lifecycle_management = "ENABLED"
          idle_timeout_in_minutes = 60
          min_idle_timeout_in_minutes = 45
          max_idle_timeout_in_minutes = 90
          }
       }
    }  

    code_editor_app_settings {
      app_lifecycle_management {
        idle_settings {
          lifecycle_management = "ENABLED"
          idle_timeout_in_minutes = 60
          min_idle_timeout_in_minutes = 45
          max_idle_timeout_in_minutes = 90
        }
     }
    }
  }
}
```

**Comment by jmeisele** [comment]
@philipgebus absolutely, thank you for the second set of eyes on the potential TF resource config. Updated the potential terraform configuration 🤝

**Comment by DrFaust92** [comment]
Ill take a crack at this
