### ISSUE TITLE
[Docs]: It is not clear which values could be configured

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform-provider-aws#39582]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_acl#acl

### Description

It is not listed for `acl` option which values could be configured.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @EugenKon 👋 Any of the canned ACLs listed in the [AWS documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html) should work. Do you think a resolution to this would be to link out to that documentation page?

**Comment by EugenKon** [comment]
Yes, link to the doc and an example should work.
