### ISSUE TITLE
[Bug]: Nodejs20.x isn't available as a runtime in AWS provider 5.7.0

### ISSUE THREAD

**Issue by rbrownejr** [hashicorp/terraform-provider-aws#39598]
### Terraform Core Version

1.9.7

### AWS Provider Version

5.7.0

### Affected Resource(s)

aws_lambda_function

### Expected Behavior

when setting runtime = "nodejs20.x", it should create a Lambda function using the AWS supported Nodejs20.x runtime.

### Actual Behavior

it bombs out showing a list of supported runtimes where nodejs20.x isn't an option.  it's available in AWS Provider Version 5.69.0

### Relevant Error/Panic Output Snippet

```shell
Error: expected runtime to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x nodejs16.x java8 java8.al2 java11 python2.7 python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 dotnet6 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2 nodejs18.x python3.10 java17 ruby3.2], got nodejs20.x
```

### Terraform Configuration Files

resource "aws_lambda_function" "lambda" {
  filename      = "../example.zip"
  function_name = "MyLambda"
  role          = "somesuppliedARNhere"
  handler       = "index.handler"
  memory_size   = 256

  source_code_hash = filebase64sha256("example.zip")

  runtime = "nodejs20.x"

}

### Steps to Reproduce

Just run the "terraform plan" command

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Good evening @rbrownejr!

Thank you for raising the issue. I checked the documentation and it looks like 
* the Terraform AWS provider version 5.7.0 was releases in July 2023 ([link](https://github.com/hashicorp/terraform-provider-aws/issues/39598))
* the support for NodeJs20 was added to Lambda in November 2023 ([link](https://aws.amazon.com/de/blogs/compute/node-js-20-x-runtime-now-available-in-aws-lambda/))

In general I would recommend to upgrade the provider version. The minimum version for your requirement should be v5.26.0 ([link](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#5260-november-16-2023)).

Hope this info helps.

**Comment by rbrownejr** [comment]
My apologies.  Thanks for your assistance.
