### ISSUE TITLE
[Enhancement]: Add Valkey support to Elasticache resources

### ISSUE THREAD

**Issue by jalaziz** [hashicorp/terraform-provider-aws#39641]
### Description

AWS recently [announced support for Valkey as an Elasticache engine](https://aws.amazon.com/blogs/database/amazon-elasticache-and-amazon-memorydb-announce-support-for-valkey/).

Attempting to use `valkey` as an engine argument with the existing resources results in a validation error: `expected engine to be one of ["redis"], got valkey`.

### Affected Resource(s) and/or Data Source(s)

* `aws_elasticache_replication_group`
* `aws_elasticache_cluster`
* `aws_elasticache_serverless_cache`

### Potential Terraform Configuration

```hcl
resource "aws_elasticache_replication_group" "this" {
  engine               = "valkey"
  ...
}
```

### References

* [Blog post](https://aws.amazon.com/blogs/database/get-started-with-amazon-elasticache-for-valkey/)

### Would you like to implement a fix?

None

**Comment by rtomadpg** [comment]
Would this be as simple adding `valkey` to the list of valid engine values, in: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/elasticache/consts.go ?

Btw the elasticache API docs have not yet been updated: https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateCacheCluster.html :

> Engine
> The name of the cache engine to be used for this cluster.
> 
> Valid values for this parameter are: memcached | redis
> 
> Type: String
> 
> Required: No

**Comment by jalaziz** [comment]
> Would this be as simple adding `valkey` to the list of valid engine values, in: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/elasticache/consts.go ?

I think it is a bit more involved as validation also needs to be updated: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal%2Fservice%2Felasticache%2Freplication_group.go#L129

> Btw the elasticache API docs have not yet been updated: https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateCacheCluster.html :

Yes, the docs only seem to be partially updated.

**Comment by h3ct0rjs** [comment]
I have trie to use the new value in version v5.76.0 and it says : 

```
│ Error: expected engine to be one of ["memcached" "redis"], got valkey
│
│   with module.redis.aws_elasticache_cluster.this,
│   on redis-test.tf line 16, in resource "aws_elasticache_cluster" "this":
│   16:   engine                     = "valkey"
```

**Comment by ithacasnowman** [comment]
Valkey clusters can be sized below 1 GB as per [this](https://aws.amazon.com/blogs/database/get-started-with-amazon-elasticache-for-valkey/) AWS blog post. However, there is no way to use the current implementation to configure a Valkey cache with less than 1 GB, as far as I can tell, because under the `data_strage` block, `unit` must be `GB` and `maximum`/`minimum` must be between 1 and 5,000.

**Comment by h3ct0rjs** [comment]
I was able to test this out, it looks like is not available.  😃 . Thanks for the answer @johndoe1505707
