### ISSUE TITLE
[Docs]: Usage example of `cloudfront_log_delivery_canonical_user_id` contains invalid `aws_s3_bucket_acl`

### ISSUE THREAD

**Issue by frittentheke** [hashicorp/terraform-provider-aws#39667]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/cloudfront_log_delivery_canonical_user_id#example-usage

### Description

The `aws_s3_bucket_acl` contains no `owner` field, but that is actually required - see https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_acl#access_control_policy

### References

* Original MR: https://github.com/hashicorp/terraform-provider-aws/pull/23002 by @anGie44, merged by @ewbankkit

### Would you like to implement a fix?

No

**Comment by stefanfreitag** [comment]
Hi @frittentheke,

thanks for reporting the issue! Let me have a look into it.
