### ISSUE TITLE
[Bug]: Error: reading Backup Vault (backup-vault-name): empty result in ca-west-1 region

### ISSUE THREAD

**Issue by osievtsov** [hashicorp/terraform-provider-aws#39664]
### Terraform Core Version

1.9.7

### AWS Provider Version

5.70.0

### Affected Resource(s)

aws_backup_vault

### Expected Behavior

Resource should properly create in ca-west-1 region, as in any other region.

### Actual Behavior

Resource is created in ca-west-1 region, but terraform returns - "Error: reading Backup Vault (backup-vault-name): empty result exit status 1"

### Relevant Error/Panic Output Snippet

```shell
aws_backup_vault.this: Creating...

╷
│ Error: reading Backup Vault (backup-vault-name): empty result
│ 
│   with aws_backup_vault.this,
│   on main.tf line 21, in resource "aws_backup_vault" "vault":
│   21: resource "aws_backup_vault" "vault" {
│ 
╵

exit status 1
```

### Terraform Configuration Files

https://gist.github.com/osievtsov/d8e09dcd737277125b8dd8bb4d373e43

### Steps to Reproduce

terraform apply

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/39650.
