### ISSUE TITLE
[Repo]: v5.71.0 does not have a package available for your current platform, linux_amd64.

### ISSUE THREAD

**Issue by marcustxl** [hashicorp/terraform-provider-aws#39675]
### Description

We are getting this error for our pipeline

`Provider registry.terraform.io/hashicorp/aws v5.71.0 does not have a package available for your current platform, linux_amd64.`

### References

https://github.com/hashicorp/terraform-provider-aws/issues/39004

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @marcustxl 👋 Thank you very much for taking the time to raise this! We ran into an issue with our release process that led to this, and so have pulled the 5.71.0 release to resolve the immediate issue. We're working through the release issue internally, and will make a new release once we're confident that it has been resolved.

Since the issue reported here has been resolved, I'm going to close this issue out. If you run into issues in the future, please do continue to let us know!

**Comment by dhirajsonawane-me** [comment]
Description
We are getting this error for our pipeline

Provider registry.terraform.io/hashicorp/aws v5.71.0 does not have a package available for your current platform, linux_arm.

References
https://github.com/hashicorp/terraform-provider-aws/issues/39004

Would you like to implement a fix?
None

**Comment by JonathanPitz** [comment]
Same here

```
Error: Incompatible provider version
--
Provider registry.terraform.io/hashicorp/aws v5.71.0 does not have a
package available for your current platform, linux_amd64.
```

**Comment by misbahally-snaptec** [comment]
Same here:

```
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/aws v5.71.0 does not have a
│ package available for your current platform, linux_amd64.
```

**Comment by skyreginag** [comment]
Same here as well during a migration process for terraform < 0.12

terraform state replace-provider -auto-approve "registry.terraform.io/-/aws" "hashicorp/aws"

**Comment by skyreginag** [comment]
Same here as well during a migration process for terraform < 0.12

terraform state replace-provider -auto-approve "registry.terraform.io/-/aws" "hashicorp/aws"

**Comment by hwanseokjang-lunit** [comment]
Same here

You can temporarily add `!= 5.71.0` condition to complete the build.

```
terraform {

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 2.68, != 5.71.0"
    }

}
```
