### ISSUE TITLE
[Enhancement]: Enable 256 CPUs for Aurora Serverless v2 RDS instances

### ISSUE THREAD

**Issue by katiekeel** [hashicorp/terraform-provider-aws#39672]
### Description

On 10/2/2024, [AWS announced that Aurora Serverless v2 supports database capacity of up to 256 Aurora Capacity Units (ACUs)](https://aws.amazon.com/about-aws/whats-new/2024/10/amazon-aurora-serverless-v2-256-acus/) for newer MySQL and Postgres versions.

[However, the module still appears to set `128` as the limit](https://github.com/hashicorp/terraform-provider-aws/blob/830f6917251bf606abd68055d175c65d657a39a5/internal/service/rds/cluster_test.go#L1968), although since that's a test I'm not 100% sure. But there haven't been any releases in this repo mentioning this change since it came out last week.

The [serverlessv2_scaling_configuration Argument Reference](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#serverlessv2_scaling_configuration-argument-reference) also still lists a maximum of 128 for `max_capacity`.

```
max_capacity - (Required) Maximum capacity for an Aurora DB cluster in provisioned DB engine mode. The maximum capacity must be greater than or equal to the minimum capacity. Valid capacity values are in a range of 0.5 up to 128 in steps of 0.5.
```

### Affected Resource(s) and/or Data Source(s)

aws_rds_cluster

### Potential Terraform Configuration

```terraform
resource "aws_rds_cluster" "example" {
  # ... other configuration ...

  serverlessv2_scaling_configuration {
    max_capacity = 256.0   # or any value between 128 and 256
    min_capacity = 0.5
  }
}
```

### References

https://aws.amazon.com/about-aws/whats-new/2024/10/amazon-aurora-serverless-v2-256-acus/

### Would you like to implement a fix?

None

**Comment by eugercek** [comment]
May I pick this up?
