### ISSUE TITLE
[Repo]:  v5.71.0 does not have a package available for your current platform, linux_arm.

### ISSUE THREAD

**Issue by dhirajsonawane-me** [hashicorp/terraform-provider-aws#39700]
### Description

Description
We are getting this error for our pipeline

Provider registry.terraform.io/hashicorp/aws v5.71.0 does not have a package available for your current platform, linux_arm.

References
https://github.com/hashicorp/terraform-provider-aws/issues/39675

Would you like to implement a fix?
None

### Would you like to implement a fix?

None

**Comment by yalattas** [comment]
same here
```
- Finding hashicorp/aws versions matching "~> 5.58"...
2024-10-13T09:44:50.978Z [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2024-10-13T09:44:50.978Z [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
2024-10-13T09:44:50.992Z [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/aws/versions
2024-10-13T09:44:50.992Z [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/hashicorp/aws/versions`
...
2024-10-13T09:44:51.060Z [TRACE] providercache.fillMetaCache: scanning directory .terraform/providers
2024-10-13T09:44:51.060Z [TRACE] getproviders.SearchLocalDirectory: failed to resolve symlinks for .terraform/providers: lstat .terraform/providers: no such file or directory
2024-10-13T09:44:51.060Z [TRACE] providercache.fillMetaCache: error while scanning directory .terraform/providers: cannot search .terraform/providers: lstat .terraform/providers: no such file or directory
...
2024-10-13T09:44:52.993Z [TRACE] providercache.fillMetaCache: using cached result from previous scan of .terraform/providers
2024-10-13T09:44:52.993Z [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/aws/5.71.0/download/linux/amd64
2024-10-13T09:44:52.993Z [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/hashicorp/aws/5.71.0/download/linux/amd64
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/aws v5.71.0 does not have a
│ package available for your current platform, linux_amd64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all
│ providers are available for all platforms. Other versions of this provider
│ may have different platforms supported.
╵
Operation failed: failed running terraform init (exit 1)
```

**Comment by StephaneChevassus** [comment]
We are having the same issue on hundreds of our repos:

![image](https://github.com/user-attachments/assets/ea5355f3-8bb3-4642-a70e-284b310c4914)

The issue seems to be intermittent which is very annoying.

We understand that you had to revert release 5.71 but it seems to have been re-released again but it is still broken.

We cannot even rollback or redeployed previous releases because of this issue which is very problematic.

**Comment by asvinours** [comment]
@justinretzolk  `5.71.0` is still showing as latest version available on the registry though

![image](https://github.com/user-attachments/assets/32e5bf51-08c8-42d2-9221-e8614307549b)

**Comment by JKelle** [comment]
I'm still having this issue as well.

**Comment by justinretzolk** [comment]
Hey @asvinours -- thank you for pointing that out! We're going to work with the Registry team to get the `5.71.0` documentation pulled as well; that's clearly not helping an already confusing situation.

**Comment by et304383** [comment]
> Since there's no action for the AWS Provider team to take at this point, I'm going to close this issue. If you encounter unexpected behavior in the future, please do let us know.

@justinretzolk What?  You currently have the top release pinned at 5.71.0 and nothing is there, so new projects cannot pull the latest provider.  We would have to pin to 5.70.0 just to get a download to go through.

You absolutely have an action to taken here.  You should have republished 5.70.0 as 5.72.0.

```
[username: thing]$ ll
total 8
-rw-r--r--@ 1 username  staff   116B Oct 15 10:20 versions.tf
[username: thing]$ cat versions.tf
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}
[username: thing]$ tfiu

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 5.0"...
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/aws v5.71.0 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
╵

[username: thing]$ 
```

**Comment by JKelle** [comment]
Why is this issue closed? I'm still running into this problem.

**Comment by asvinours** [comment]
This morning `5.71.0` was removed from https://registry.terraform.io/providers/hashicorp/aws/latest. Terraform would properly download `5.70.0` as latest available version.

But it seems to have re-appeared, breaking terraform pipelines again

**Comment by justinretzolk** [comment]
Hey @asvinours 👋 I posted an updated comment over [here](https://github.com/hashicorp/terraform-provider-aws/issues/39724#issuecomment-2414857723) on the most recently opened issue regarding this. Trying to consolidate the conversations over there, but the gist of it is that we're in the process of releasing `5.72.0` now, which should resolve the issue entirely.
