### ISSUE TITLE
When will the next major version be released?

### ISSUE THREAD

**Issue by ericrichtert** [hashicorp/terraform-provider-aws#39704]
### Description

The roadmap file describes the expetected changes until April 2024, what will be the next roadmap?

And when can we expect a new major version, for example to remove the deprecated "overwrite" property in the aws_ssm_parameter?

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@ericrichtert Because of a public holiday in Canada on 10/14 and HashiConf on 10/15 & 10/16, our next release will be on Thursday 10/17.
