### ISSUE TITLE
[Enhancement]: Add SecurityHub CIS3.0 standard

### ISSUE THREAD

**Issue by DanielBYosifov** [hashicorp/terraform-provider-aws#39740]
### Description

Hello Team,

Can you please add the CIS 3.0.0 standard in Terraform? Looking into the documentation, it is still not available - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_standards_subscription#argument-reference

### Affected Resource(s) and/or Data Source(s)

aws_securityhub_standards_subscription

### References

https://aws.amazon.com/about-aws/whats-new/2024/05/aws-security-hub-3-0-cis-foundations-benchmark/

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Hello @DanielBYosifov,
thank you for bringing this to our attention!

I had a look into the AWS provider code and it seems that the resource only expects a valid ARN as input. So the crucial part is to find the right ARN.
The AWS CLI offers `aws securityhub describe-standards` for this, and I got as result  below information

```hcl 
standards_arn = "arn:aws:securityhub:eu-central-1::standards/cis-aws-foundations-benchmark/v/3.0.0"
```


So I think it is more about updating the documentation for the resource to provide details on the name/ ARN of the standard.
Let me take care of that.
