### ISSUE TITLE
[Bug]: The terraform-provider-aws_v5.72.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by gkabov** [hashicorp/terraform-provider-aws#39747]
### Terraform Core Version

1.9.5

### AWS Provider Version

5.72.0

### Affected Resource(s)

* `aws_dynamodb_table`

### Expected Behavior

Whenever I update dynamoDb resource in terraform the plugin crashes without being able to update the table.

### Actual Behavior

```
4291 | │ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
4292 | │ contain more details.
4293 | ╵
4294 |  
4295 | Stack trace from the terraform-provider-aws_v5.72.0_x5 plugin:
4296 |  
4297 | panic: runtime error: invalid memory address or nil pointer dereference
4298 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13eddc54]
```

### Terraform Configuration Files

```hcl
resource "aws_dynamodb_table" "ddbTest" {
  name                        = "ddbTest"
  billing_mode                = "PAY_PER_REQUEST"
  hash_key                    = "id"
  stream_enabled              = true
  stream_view_type            = "NEW_AND_OLD_IMAGES"
  deletion_protection_enabled = true
  point_in_time_recovery {
    enabled = true
  }


  attribute {
    name = "tre"
    type = "S"
  }

  global_secondary_index {
    name            = "tre"
    hash_key        = "tre"
    projection_type = "ALL"
  }


  tags = {
    Name        = "test"
    Environment = local.app_env
    UserData    = true
  }

  lifecycle {
    prevent_destroy = true
  }
}
```

### Steps to Reproduce

Update dynamoDb terraform resource and on apply it fails with the provided error message

### Would you like to implement a fix?

None

**Comment by foxorajack** [comment]
This happened to me too, any apply that runs now fails with the same message. If I reapply the apply I did at 13:30pm on 16th October 2024 (which worked at the time), it now fails with the same error.

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/37799?

**Comment by foxorajack** [comment]
I don't believe so, as there is no `on_demand_throughput` defined in my configs

**Comment by johnsonaj** [comment]
Thank you for the issue report! I was able to reproduce this and am currently working on a fix
