### ISSUE TITLE
[Docs]: Incorrect Attribute Usage on Verified Access Group

### ISSUE THREAD

**Issue by u-blavins** [hashicorp/terraform-provider-aws#39769]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/verifiedaccess_group

### Description

Within the example usage, it states that to enable SSE encryption through KMS, you need:

```
resource "aws_verifiedaccess_group" "test" {
  verifiedaccess_instance_id = aws_verifiedaccess_instance_trust_provider_attachment.test.verifiedaccess_instance_id

  server_side_encryption_configuration {
    kms_key_arn = aws_kms_key.test_key.arn
  }
}
```

but below the snippet (also showing in IDE), `server_side_encryption_configuration` is not the correct option and should be `sse_configuration`.

### References

Terraform plan output:

```
│ Error: Unsupported block type
│ 
│   on modules/PayloadCMS/vpc.tf line 46, in resource "aws_verifiedaccess_group" "marketplace_payload_cms":
│   46:   server_side_encryption_configuration {
│ 
│ Blocks of type "server_side_encryption_configuration" are not expected here.

```

### Would you like to implement a fix?

Yes

**Comment by stefanfreitag** [comment]
Hi @jar-b,

as #39768  is merged to main - any ToDo left here?
I am asking because the PR did not contain the "Closes xyz...".
