### ISSUE TITLE
[Docs]: missing transformation block in aws_bedrockagent_data_source

### ISSUE THREAD

**Issue by pauliusmiskinis** [hashicorp/terraform-provider-aws#39773]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/bedrockagent_data_source

### Description

Docs suggest that the format is:

```
resource "aws_bedrockagent_data_source" "example" {
  vector_ingestion_configuration {
    custom_transformation_configuration {
      transformation_function {
        transformation_lambda_configuration {
        }
      }
    }
  }
}
```

but in reality it's:
```
resource "aws_bedrockagent_data_source" "example" {
  vector_ingestion_configuration {
    custom_transformation_configuration {
      transformation {
        transformation_function {
          transformation_lambda_configuration {
          }
        }
      }
    }
  }
}
```

A block named `transformation` isn't mentioned in the docs. 

### References

https://github.com/hashicorp/terraform-provider-aws/blob/08f131ce76df717ef55484128c08cdfe3e92882f/internal/service/bedrockagent/data_source_test.go#L760

### Would you like to implement a fix?

No

**Comment by stefanfreitag** [comment]
Hi @Shiravani24, any help needed of preparing the pull request?
