### ISSUE TITLE
[Bug]: aws_imagebuilder_workflow allows invalid value "DISTRIBUTION" for 'type' argument

### ISSUE THREAD

**Issue by clarkhathawayaltview** [hashicorp/terraform-provider-aws#39785]
### Terraform Core Version

1.9.7

### AWS Provider Version

5.72.0

### Affected Resource(s)

aws_imagebuilder_workflow

### Expected Behavior

The argument `type` should only allow the values "BUILD" and "TEST" per [the Image Builder workflow documentation](https://docs.aws.amazon.com/imagebuilder/latest/userguide/manage-image-workflows.html)

> The image creation workflow framework includes the following two distinct stages.
>  ...
> ***The workflow framework also includes a distribution stage. However, Image Builder handles the workflows for that stage.***

### Actual Behavior

The documentation and implementation allow for the value "DISTRIBUTION" to be passed

### Relevant Error/Panic Output Snippet

```shell
Error: creating Image Builder Workflow: InvalidParameterValueException: The value supplied for parameter 'type' is not valid. Custom distribution workflows are not supported.
```

### Terraform Configuration Files

```
resource aws_imagebuilder_workflow codebuild-projects {
  name = "CodeBuildProjectsDistributionWorkflow"
  version = "1.0.0"
  type = "DISTRIBUTION"
  data = file("${path.module}/codebuild-projects-distribution.workflow.yaml")
}
```

### Steps to Reproduce

Standard plan & apply.

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Hello @clarkhathawayaltview!
Thank you for reporting this issue related to the imagebuilder workflow resource.

I had a brief look into the relevant provider code section and it seems to be the case that we verify the input against the types defined in the AWS SDK for Go. 

I checked out the behavior of the AWS CLI and it also dislikes the type DISTRIBUTION.

```shell
❯ aws --version
aws-cli/2.17.5 Python/3.11.8 Linux/6.11.0-8-generic exe/x86_64.ubuntu.24

❯ aws imagebuilder create-workflow --name test --type DISTRIBUTION --semantic-version 0.0.1 --data "workflow"
An error occurred (InvalidParameterValueException) when calling the CreateWorkflow operation: The value supplied for parameter 'type' is not valid. Custom distribution workflows are not supported.
```
even as its listed a supported input
* [AWS CLI v1](https://docs.aws.amazon.com/cli/latest/reference/imagebuilder/create-workflow.html)
* [AWS CLI v2](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/imagebuilder/create-workflow.html)

**Comment by clarkhathawayaltview** [comment]
Your explanation was roughly what I had imagined the problem was. It is frustrating that their API is designed in this way but I'm pleased to see a quick response on this issue.
