### ISSUE TITLE
[Docs]: aws_ami_copy references undocumented "description"

### ISSUE THREAD

**Issue by stevenpitts** [hashicorp/terraform-provider-aws#39794]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ami_copy

### Description

The example in this documentation has:

```text
description       = "A copy of ami-xxxxxxxx"
```

But this `description` argument is not listed in the argument reference. It should be included in both places or neither, depending on whether this argument is actually supported.

### Would you like to implement a fix?

No

**Comment by stefanfreitag** [comment]
Good evening @stevenpitts ,

thanks for reporting this gap in the documentation. 
I think the value provided for description is  inserted into the description field of the new AMI in the destination region.

Let me take care of the documentation update.
