### ISSUE TITLE
[Bug]: New revisions of aws_batch_job_definition forgets tags

### ISSUE THREAD

**Issue by t0yv0** [hashicorp/terraform-provider-aws#39795]
### Terraform Core Version

1.8.3

### AWS Provider Version

5.72.1

### Affected Resource(s)

* aws_batch_job_definition

### Expected Behavior

When making changes to an aws_batch_job_definition with tags, newly introduced revisions of the job definition should continue to be tagged with the tags specified in the Terraform file.

### Actual Behavior

When making changes to an aws_batch_job_definition with tags, newly introduced revisions are not tagged. Only the first revision carries the tags specified in the Terraform file.

### Relevant Error/Panic Output Snippet

```shell
N/A
```

### Terraform Configuration Files

```terraform

resource "aws_batch_job_definition" "jobdef1" {
  name = "my_test_batch_job_def"
  type = "container"
  tags = {
    env = "prod"
  }
  container_properties = <<EOF
{
    "command": [
        "ls", "--help"
    ],
    "image": "busybox",
    "resourceRequirements": [
        {
            "type": "VCPU",
            "value": "1"
        },
        {
            "type": "MEMORY",
            "value": "512"
        }
    ]
}
EOF
}

```

### Steps to Reproduce

```
terraform apply
# edit ["ls", "--help"] to ["ls"]
terraform apply
aws batch describe-job-definitions --job-definition-name my_test_batch_job_definition | jq '.jobDefinitions[]|{revision: .revision, tags: .tags}'
```

Observe that revision 2 is not tagged:

```
{
  "revision": 1,
  "tags": {
    "env": "prod"
  }
}
{
  "revision": 2,
  "tags": {}
}
```

Expected revision 2 to be tagged.

### Debug Output

N/A

### Panic Output

N/A

### Important Factoids

N/A

### References

N/A

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/issues/38302.
