### ISSUE TITLE
[Enhancement]: aws_appstream_stack user_settings has been updated

### ISSUE THREAD

**Issue by sarangak** [hashicorp/terraform-provider-aws#39792]
### Description

`aws_appstream_stack` has added a new setting:
```
resource "aws_appstream_stack" "stack" {
  ...

  user_settings {
    action     = "AUTO_TIME_ZONE_REDIRECTION"
    permission = "DISABLED"
  }

  ...
}
```

This setting works with the above code, but the new setting should probably have **documentation and testing**.

### Affected Resource(s) and/or Data Source(s)

* aws_appstream_stack

### References

- https://aws.amazon.com/about-aws/whats-new/2024/10/amazon-appstream-2-0-automatic-time-zone-redirection/
- https://github.com/hashicorp/terraform-provider-aws/issues/39754
- https://github.com/hashicorp/terraform-provider-aws/pull/28766/files (This PR has some similar updates)

### Would you like to implement a fix?

No

**Comment by stefanfreitag** [comment]
Hi all, let me have a look into this.
