### ISSUE TITLE
[Bug]: aws_iam_role_policy_attachments_exclusive doesnt detach policies on destroy?

### ISSUE THREAD

**Issue by lapkritinis** [hashicorp/terraform-provider-aws#39818]
### Terraform Core Version

1.9.7

### AWS Provider Version

5.72.1

### Affected Resource(s)

* aws_iam_policy
* aws_iam_role_policy_attachments_exclusive

### Expected Behavior

Created resources should have deleted.

### Actual Behavior

`│ Error: deleting IAM Policy (arn:aws:iam::123456789012:policy/terraform-20241021154342453400000001): operation error IAM: DeletePolicy, https response error StatusCode: 409, RequestID: 51ddf8fa-2fa5-44e3-a47c-81c67a6b3043, DeleteConflict: Cannot delete a policy attached to entities.`

### Terraform Configuration Files

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.72.1"
    }
  }
}

resource "aws_iam_role" "this" {
  assume_role_policy = data.aws_iam_policy_document.trust-ec2-service.json
}

resource "aws_iam_policy" "this" {
  policy = data.aws_iam_policy_document.ebs-encrypt-decrypt.json
}

resource "aws_iam_role_policy_attachments_exclusive" "this" {
  role_name = aws_iam_role.this.name
  policy_arns = [
    aws_iam_policy.this.arn,
  ]
}

data "aws_iam_policy_document" "trust-ec2-service" {
  statement {
    sid     = "EC2AssumeRole"
    actions = ["sts:AssumeRole"]

    effect = "Allow"

    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}

data "aws_iam_policy_document" "ebs-encrypt-decrypt" {
  statement {
    effect = "Allow"
    actions = [
      "kms:DescribeKey",
    ]
    resources = ["*"]
  }
}


```

### Steps to Reproduce

terraform apply <- resources are created as expected.
terraform apply -destroy

```
aws_iam_role_policy_attachments_exclusive.this: Destroying...
aws_iam_role_policy_attachments_exclusive.this: Destruction complete after 0s
aws_iam_policy.this: Destroying... [id=arn:aws:iam::654654141215:policy/terraform-20241021155037463400000001]
aws_iam_role.this: Destroying... [id=terraform-20241021155037463400000002]
aws_iam_role.this: Destruction complete after 1s
╷
│ Error: deleting IAM Policy (arn:aws:iam::123456789012:policy/terraform-20241021155037463400000001): operation error IAM: DeletePolicy, https response error StatusCode: 409, RequestID: 373c1ae9-33d4-4b63-a392-62dae5305b2b, DeleteConflict: Cannot delete a policy attached to entities.
```

### Important Factoids

You have deprecated from `iam_role` `managed_policy_arns` in favor of `aws_iam_role_policy_attachments_exclusive`. It would be nice if you have checked that its functional. @jar-b

Working code which now is ***DEPRECATED***

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.72.1"
    }
  }
}

resource "aws_iam_role" "this" {
  assume_role_policy = data.aws_iam_policy_document.trust-ec2-service.json
  
  # ***DEPRECATED***
  managed_policy_arns = [
    aws_iam_policy.this.arn,
  ]
}

resource "aws_iam_policy" "this" {
  policy = data.aws_iam_policy_document.ebs-encrypt-decrypt.json
}

data "aws_iam_policy_document" "trust-ec2-service" {
  statement {
    sid     = "EC2AssumeRole"
    actions = ["sts:AssumeRole"]

    effect = "Allow"

    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}

data "aws_iam_policy_document" "ebs-encrypt-decrypt" {
  statement {
    effect = "Allow"
    actions = [
      "kms:DescribeKey",
    ]
    resources = ["*"]
  }
}


```

### Would you like to implement a fix?

None

**Comment by jar-b** [comment]
Hi @lapkritinis - sorry to hear you're having issues. 

In this case the `aws_iam_role_policy_attachments_exclusive` resource is behaving as expected. Destruction of this resource indicates that Terraform should no longer monitor the role to synchronize the configured attachments. It does not _remove_ attachments, as that responsibility is reserved for the `aws_iam_role_policy_attachment` resource (or deletion of the parent role resource). 

You can modify your configuration above to work as expected by adding a `aws_iam_role_policy_attachment` resource, which enables Terraform to properly sequence policy detachment before deletion.

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.72.1"
    }
  }
}

resource "aws_iam_role" "this" {
  assume_role_policy = data.aws_iam_policy_document.trust-ec2-service.json
}

resource "aws_iam_policy" "this" {
  policy = data.aws_iam_policy_document.ebs-encrypt-decrypt.json
}

### Start additions ###
resource "aws_iam_role_policy_attachment" "this" {
  role       = aws_iam_role.this.name
  policy_arn = aws_iam_policy.this.arn
}
### End additions ###

resource "aws_iam_role_policy_attachments_exclusive" "this" {
  role_name = aws_iam_role.this.name
  policy_arns = [
    aws_iam_policy.this.arn,
  ]
}

data "aws_iam_policy_document" "trust-ec2-service" {
  statement {
    sid     = "EC2AssumeRole"
    actions = ["sts:AssumeRole"]

    effect = "Allow"

    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}

data "aws_iam_policy_document" "ebs-encrypt-decrypt" {
  statement {
    effect = "Allow"
    actions = [
      "kms:DescribeKey",
    ]
    resources = ["*"]
  }
}
```

```console
% terraform destroy -auto-approve

Plan: 0 to add, 0 to change, 4 to destroy.
aws_iam_role_policy_attachment.this: Destroying... [id=terraform-20241021180512987400000002-20241021180513469200000003]
aws_iam_role_policy_attachments_exclusive.this: Destroying...
aws_iam_role_policy_attachments_exclusive.this: Destruction complete after 0s
aws_iam_role_policy_attachment.this: Destruction complete after 0s
aws_iam_policy.this: Destroying... [id=arn:aws:iam::727561393803:policy/terraform-20241021180512987100000001]
aws_iam_role.this: Destroying... [id=terraform-20241021180512987400000002]
aws_iam_role.this: Destruction complete after 0s
aws_iam_policy.this: Destruction complete after 0s

Destroy complete! Resources: 4 destroyed.
```

You could also omit the `aws_iam_role_policy_attachment` resource and instead use an explicit `depends_on` to the role resource, ensuring that role destruction (and detachment of the policy) happens before the policy is deleted. 

```terraform
resource "aws_iam_role" "this" {
  assume_role_policy = data.aws_iam_policy_document.trust-ec2-service.json

  depends_on = [aws_iam_policy.this]
}
```

```console
% terraform destroy -auto-approve

Plan: 0 to add, 0 to change, 3 to destroy.
aws_iam_role_policy_attachments_exclusive.this: Destroying...
aws_iam_role_policy_attachments_exclusive.this: Destruction complete after 0s
aws_iam_role.this: Destroying... [id=terraform-20241021180916381600000002]
aws_iam_role.this: Destruction complete after 0s
aws_iam_policy.this: Destroying... [id=arn:aws:iam::727561393803:policy/terraform-20241021180916135700000001]
aws_iam_policy.this: Destruction complete after 1s

Destroy complete! Resources: 3 destroyed.
```

This second option mimics the working example you provided (the presence of the `managed_policy_arns` argument is not what allows destruction to complete successfully, but rather the explicit dependency on the `aws_iam_policy.this` resource which causes the role to be deleted before the policy).

Hope this helps to resolve your issue!

**Comment by lapkritinis** [comment]
Constructive discussion. What is the intent of this new resource? To detach policies which should not be attached to? In that case fine, but it should not replace manage_policies_arns in my opinion. If I have like 10 policies attaching each of them with its own resources  `aws_iam_role_policy_attachment` repeating 10 times its kinda boilerplate (could be for_each maybe, but still, for_each are tricky on dynamic resources). I liked to have an single list where I saw all policies attached to a role. This explicit thingy which should done sort of same job - kinda doesn’t. It still feels odds, that it creates attachment,  but doesnt destroy - because one attachment does get detached upon destruction, but other “type” does not. For me personally whole setup seems like a downgrade without benefits and I will be using most likely that deprecated form because its most handy. If destruction would behave like it should (at least add some option for it?) I would use this new probably.

**Comment by lapkritinis** [comment]
@jar-b , I wanted to use depends_on, but in my real world scenario code is slightly different - it uses count and has more than one policy. In that case even depends_on doesnt help - it complains that cannot delete role with attached policies (which makes sense, but why with single attached policy it can?) And I think I had failure rate like 90% while testing (one time it deleted all fine)

Here is updated code:

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.72.1"
    }
  }
}

locals {
  create_count = 0
}

resource "aws_iam_role" "this" {
  count = local.create_count
  
  assume_role_policy = data.aws_iam_policy_document.trust-ec2-service[count.index].json

  depends_on = [
    aws_iam_policy.kms-describe,
    aws_iam_policy.kms-encrypt,
  ]
}

resource "aws_iam_policy" "kms-describe" {
  count = local.create_count
  
  policy = data.aws_iam_policy_document.kms-describe[count.index].json
}

resource "aws_iam_policy" "kms-encrypt" {
  count = local.create_count
  
  policy = data.aws_iam_policy_document.kms-encrypt[count.index].json
}

resource "aws_iam_role_policy_attachments_exclusive" "this" {
  count = local.create_count
  
  role_name = aws_iam_role.this[count.index].name
  policy_arns = [
    aws_iam_policy.kms-describe[count.index].arn,
    aws_iam_policy.kms-encrypt[count.index].arn,
  ]
}

data "aws_iam_policy_document" "trust-ec2-service" {
  count = local.create_count
  
  statement {
    sid     = "EC2AssumeRole"
    actions = ["sts:AssumeRole"]

    effect = "Allow"

    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}

data "aws_iam_policy_document" "kms-describe" {
  count = local.create_count
  
  statement {
    effect = "Allow"
    actions = [
      "kms:DescribeKey",
    ]
    resources = ["*"]
  }
}

data "aws_iam_policy_document" "kms-encrypt" {
  count = local.create_count
  
  statement {
    effect = "Allow"
    actions = [
      "kms:Encrypt",
    ]
    resources = ["*"]
  }
}
```

Apply result:
```
  Enter a value: yes

aws_iam_role_policy_attachments_exclusive.this[0]: Destroying...
aws_iam_role_policy_attachments_exclusive.this[0]: Destruction complete after 0s
aws_iam_role.this[0]: Destroying... [id=terraform-20241022111824008300000003]
aws_iam_role.this[0]: Still destroying... [id=terraform-20241022111824008300000003, 10s elapsed]
aws_iam_role.this[0]: Still destroying... [id=terraform-20241022111824008300000003, 20s elapsed]
aws_iam_role.this[0]: Still destroying... [id=terraform-20241022111824008300000003, 30s elapsed]
aws_iam_role.this[0]: Still destroying... [id=terraform-20241022111824008300000003, 40s elapsed]
aws_iam_role.this[0]: Still destroying... [id=terraform-20241022111824008300000003, 50s elapsed]
aws_iam_role.this[0]: Still destroying... [id=terraform-20241022111824008300000003, 1m0s elapsed]
aws_iam_role.this[0]: Still destroying... [id=terraform-20241022111824008300000003, 1m10s elapsed]
aws_iam_role.this[0]: Still destroying... [id=terraform-20241022111824008300000003, 1m20s elapsed]
aws_iam_role.this[0]: Still destroying... [id=terraform-20241022111824008300000003, 1m30s elapsed]
aws_iam_role.this[0]: Still destroying... [id=terraform-20241022111824008300000003, 1m40s elapsed]
aws_iam_role.this[0]: Still destroying... [id=terraform-20241022111824008300000003, 1m50s elapsed]
aws_iam_role.this[0]: Still destroying... [id=terraform-20241022111824008300000003, 2m0s elapsed]
╷
│ Error: deleting IAM Role (terraform-20241022111824008300000003): operation error IAM: DeleteRole, https response error StatusCode: 409, RequestID: 99a81235-95d3-423a-9498-5d193f04f3a2, DeleteConflict: Cannot delete entity, must detach all policies first.
```

**Comment by novekm** [comment]
+1, running into the same issue. I also am struggling to understand the usage of the new resource.

**Comment by sean-nixon** [comment]
I also have a hard time understanding the purpose and behavior of this new resource. What is the reason for this resource not to detach the policies when it is destroyed? It seems logical and intuitive that it would do so, since it attaches the policies when it is created, and it would avoid these dependency issues. There are a few issues I see with this:
1. This behavior contradicts the standard behavior of Terraform. Unless there are unique service/API limitations, I would expect a `terraform apply` followed by a `terraform destroy` to leave my infrastructure in an identical state. As is, if the role `terraform apply` may attach policies to a role that will stay attached after a `terraform destroy` (assuming the role was created outside of TF or in a different workspace/root module).
2. Using this resource with `aws_iam_role_policy_attachment` together with this resource as recommended seems like it will be prone to race conditions unless explicit `depends_on` is added to the `aws_iam_role_policy_attachments_exclusive` resource to force it to apply after all other attachments. As mentioned above by other commenters, this is cumbersome and `depends_on` is generally discouraged as a last resort.

Beyond the issues above, if this behavior stays as is, it warrants more explanation in the documentation in my opinion. Because this does not detach policies when it is deleted, it is not a strict replacement for the deprecated `managed_policy_arns`,  which the deprecation warning and the documentation would seem to imply. If this behavior is expected and there is a strong reason for it, I would hope for the documentation to explain the expected behavior of the resource and give examples of the recommended way to use this resource in combination with `aws_iam_role_policy_attachment`.

**Comment by jar-b** [comment]
Hi everyone - thanks for your feedback. We have a few ideas to provide more clarity around this resource and the associated deprecation. First, I'll try to answer some of the questions above and describe the distinction between this new resource and `aws_iam_role_policy_attachment`.

---

The purpose of this resource is covered in detail in [the proposal for exclusive relationship management resources](https://hashicorp.github.io/terraform-provider-aws/design-decisions/exclusive-relationship-management-resources/), but as suggested above our communication to this point has not adequately described it.

The `aws_iam_role_policy_attachments_exclusive` resource is intended to allow Terraform to own reconciliation of __all attachments__ to a given role. This includes attaching configured policies as well as detaching those not explicitly configured. For the lifecycle of this resource it's sole responsibility is to ensure the configured list of policies matches what is present in AWS, adding and removing policies as necessary. When the lifecycle of this resource ends it forfeits control of this reconciliation, but does not add or remove anything during the `destroy` workflow.  This resource is not a bulk version of the `aws_iam_role_policy_attachment` resource. 

The `aws_iam_role_policy_attachment` resource manages the lifecycle of a single attachment, including removal when the resource is destroyed.

---

I suspect the biggest contributing factor to the confusion thus far is the deprecation message for the `managed_policy_arns` argument. 

> The `managed_policy_arns` argument is deprecated. Use the `aws_iam_role_policy_attachments_exclusive` resource instead.

This is a mistake on my part. Upon reflection, this is encouraging the opposite of what I just described above - to use the `_exclusive` resource as a bulk attachment mechanism. I'm going to update this to align more closely with the `inline_policies` deprecation message.

> The `managed_policy_arns` argument is deprecated. Use the `aws_iam_role_policy_attachment` resource instead. If Terraform should exclusively manage all policy attachments (the current behavior of this argument), use the `aws_iam_role_policy_attachments_exclusive` resource as well.

This better describes our intent. The `_attachment` resource should be used to manage the lifecycle of the policy attachment, and for those uses cases which would additionally like Terraform to reconcile **all** attachments, the `_exclusive` resource is available to provide parity with the now deprecated argument.

Additionally, I'm going to add notes to the registry documentation for all `_exclusive` resources to indicate that destruction of the resource does not result in detachment of the configured policies. Hopefully a more accurate description of how to address the deprecation and more explicit documentation on the destroy behavior of the `_exclusive` resource will reduce the confusion. I'll link the changes back to this issue, but leave it open for now to allow for continued feedback.

**Comment by novekm** [comment]
Thanks Jared! Yes the new messaging for the warning clarifies a lot more - I understand the intent now. I think part of my confusion is also the multiple methods to apply policies for IAM resources, and which to use when + tradeoffs. So far I think there's:
- `aws_iam_role_policy_attachment`
- `aws_iam_policy_attachment`
- `aws_iam_role_policy`
-  or the now deprecated `managed_policy_arns` within the `aws_iam_role` resource
 
I get sort of lost in all the variations and the related resources you need to make depending which path you go down.

**Comment by lapkritinis** [comment]
Consider having 10 iam_policies which needs to be attached to a role. With managed_policy_arns it was single list. Now I need to bloat my TF file with 10 attachments. I missed the part what problem needed to be solved to deprecate that resource and how did it made life better?
In fact I took an effort to migrate existing code to managed_policy_arns and now I am forced to migrate it back? To be honest I feel stupid now.

**Comment by jar-b** [comment]
> So far I think there's:
> 
> - `aws_iam_role_policy_attachment`
> - `aws_iam_policy_attachment`
> - `aws_iam_role_policy`
> - or the now deprecated `managed_policy_arns` within the `aws_iam_role` resource

Totally understand the confusion given how many resources are available and the similarities in naming. Part of this is within our control as provider developers and some isn't. 

### Not in our control

`aws_iam_role_policy` and `aws_iam_role_policy_attachment` have to exist independently - the former covers inline policy assignments (1:1 with a role), while the latter covers managed policy attachments (1 policy: many roles). AWS has distinct APIs for each action ([`PutRolePolicy`](https://docs.aws.amazon.com/IAM/latest/APIReference/API_PutRolePolicy.html) and [`AttachRolePolicy`](https://docs.aws.amazon.com/IAM/latest/APIReference/API_AttachRolePolicy.html)), which we try to keep alignment with.

### Within our control

The `aws_iam_role_policy_attachment` resource and `aws_iam_role.managed_policy_arns` argument do have overlapping functionality. As maintainers we recommend the standalone resource because it more closely aligns with how a console or CLI user would operate (create a role, create a policy, attach the policy to the role, each as distinct motions). 

Until now we could not deprecate the `managed_policy_arns` argument because it has the additional benefit of exclusively managing which policies are attached (i.e. removing those which are not explicitly configured), which the standalone attachment resource does not provide. The `aws_iam_role_policy_attachments_exclusive` now allows for configurations using `aws_iam_role_policy_attachment` to have this same capability, and allows us to deprecate `managed_policy_arns` in favor of the standalone resource equivalents going forward.

While both options still exist, the deprecation on `managed_policy_arns` should make it clear what the preferred pattern is for net-new configurations.

Lastly, the `aws_iam_policy_attachment` resource is a legacy resource which attempted to solve the "exclusive relationship management" problem from the perspective of the policy. In practice we find this is not the way most practitioners think about this problem, but it does technically provide a distinct workflow which prevents its removal. Personally I'd love to see this deprecated to reduce an already confusing IAM resource landscape, but this is not something that was considered in-scope for the proposal linked above.

Hope this helps to clarify things a bit!

**Comment by lapkritinis** [comment]
Thanks for the explanation. While it does not make me very happy and personally, I think it is a downgrade - but I saw that this is preferred path now - similar change happened with S3 buckets.

But if this is chosen path - please make better for_each - now it is really struggling with that "key must be known" plague and it makes hard to avoid copy/paste code which reduced readability, etc.
