### ISSUE TITLE
[Docs]: `max_tokens` argument in `aws_bedrockagent_data_source`

### ISSUE THREAD

**Issue by claudiourbina** [hashicorp/terraform-provider-aws#39819]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/5.72.1/docs/resources/bedrockagent_data_source

### Description

The documentation refers to the `max_tokens` argument several times, but the correct argument is `max_token`.

```
Error: Missing required argument

  on bedrock/main.tf line 128, in resource "aws_bedrockagent_data_source" "unstructured_data_source":
 128:       semantic_chunking_configuration {

The argument "max_token" is required, but no definition was found.

Error: Unsupported argument

  on bedrock/main.tf line 131, in resource "aws_bedrockagent_data_source" "unstructured_data_source":
 131:         max_tokens = 300

An argument named "max_tokens" is not expected here. Did you mean
"max_token"?
```

### Would you like to implement a fix?

None

**Comment by saqibkhan7994** [comment]
I would like to contribute on this issue. This will be my first Open Source Contribution. Please assign it to me. Thanks!
