### ISSUE TITLE
[Bug]: Error: listing tags for Lambda Event Source Mapping

### ISSUE THREAD

**Issue by devopsrick** [hashicorp/terraform-provider-aws#39849]
### Terraform Core Version

1.9.5

### AWS Provider Version

5.72.1

### Affected Resource(s)

* `aws_lambda_event_source_mapping`

### Expected Behavior

no error

### Actual Behavior

errors during plan

### Relevant Error/Panic Output Snippet

```shell
Error: listing tags for Lambda Event Source Mapping (arn:aws:lambda:us-west-2::event-source-mapping:xxx-xxx-xxx): operation error Lambda: ListTags, https response error StatusCode: 400, RequestID: xxx-xxx-xxx, InvalidParameterValueException: Unsupported resource type for tagging or invalid arn: arn:aws:lambda:us-west-2::event-source-mapping:xxx-xxx-xxx
```

### Terraform Configuration Files

```hcl
resource "aws_lambda_event_source_mapping" "example" {
  event_source_arn  = aws_kinesis_stream.example.arn
  function_name     = aws_lambda_function.example.arn
  starting_position = "LATEST"
}
```

### Steps to Reproduce

plan with any existing untagged aws_lambda_event_source_mapping resource

### Important Factoids

From AWS:
Analysis
The event source mapping you are attempting to tag is not a supported resource type for tagging. Lambda event source mappings can only be tagged when they are created, not after the fact from the console.

### References

https://github.com/hashicorp/terraform-provider-aws/pull/39535

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
Hmm 😕. The Developer Guide explicitly states [_You can use the Lambda console to create event source mappings that have tags, add tags to existing event source mappings,_](https://docs.aws.amazon.com/lambda/latest/dg/tags-esm.html#tags-esm-console).
@devopsrick Could you please ensure that you have the [`lambda:ListTags` permission](https://docs.aws.amazon.com/lambda/latest/dg/tags-esm.html#esm-tags-required-permissions). We have seen confusing error messages returned for this resource when IAM is not allowing access: https://github.com/hashicorp/terraform-provider-aws/issues/39820.

**Comment by devopsrick** [comment]
My terraform role has the AdministratorAccess policy attached so it definitely does.  I do not see anything anywhere that might override that with an explicit deny.

**Comment by maciej-poleszczyk** [comment]
We have also encountered that issue. Apparently feature on AWS side doesn't work ... at least not everywhere.
We have moved back to provider 5.69 to unblock us and waiting for things to start work as expected.

**Comment by manishgk** [comment]
I'm facing the same issue on latest aws provider version 5.73.0, my terraform version is 1.7.5

**Comment by devopsrick** [comment]
AWS support has stated that some accounts have had this feature disabled due to a bug in cloudformation behavior.  I am unsure what the timeline or process is for this feature to be enabled for all accounts in all regions.  It may be worth adding a flag to this feature in the provider, or at least an error catch.

**Comment by manishgk** [comment]
@devopsrick I tried with latest version 5.74.0, and seems to work now

**Comment by devopsrick** [comment]
I can confirm the issue no longer appears to be present.  Thank you for whatever the fix was!
