### ISSUE TITLE
Aurora Global Database writer endpoint

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#39862]
> Amazon Aurora now supports a [Global Database](https://aws.amazon.com/rds/aurora/global-database/) writer endpoint. This highly available and fully managed endpoint simplifies routing for your applications and eliminates the need to make application code changes to establish connectivity after initiating a cross-region Global Database Switchover or Failover operation.

### Affected Resource(s)

* `aws_rds_global_cluster`

**Comment by Yonathan-Eyal** [comment]
Any news here? What is preventing this from being added?
