### ISSUE TITLE
Error applying new autoscaling group: diffs didn't match during apply

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#3986]
_This issue was originally opened by @charlesarnaudo as hashicorp/terraform#17730. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version

```
0.10.8
```

### Terraform Configuration Files

```hcl
resource "aws_launch_configuration" "spinnaker-launch-conf" {
    name = "spinnaker-${var.project}-${var.environment}-launch-conf"
    image_id = "${data.aws_ami.base_ami.id}"
    instance_type = "m4.xlarge"
    associate_public_ip_address = "${var.associate_public_ip_address}"
    key_name = "${var.key_name}"
    security_groups = ["${aws_security_group.spinnaker-sg.id}"]
    iam_instance_profile = "${aws_iam_instance_profile.spinnaker_iam_instance_profile.id}"
}
# asg
resource "aws_autoscaling_group" "spinnaker-asg" {
    availability_zones = ["us-east-1a"]
    name = "spinnaker-${var.project}-${var.environment}-asg"
    launch_configuration = "${aws_launch_configuration.spinnaker-launch-conf.name}"
    max_size = 1
    min_size = 1
    health_check_grace_period = 300
    health_check_type = "ELB"
    load_balancers = ["${aws_elb.spinnaker-elb.id}"]
    vpc_zone_identifier = ["${aws_subnet.private_subnet.id}"]
    tag {
        key = "Name"
        value = "spinnaker-${var.project}-${var.environment}-instance"
        propagate_at_launch = true
    }
}
. . . 
```

### Debug Output

https://gist.github.com/charlesarnaudo/7844fabd272bd4b2d62b7f49215c8dcd
### Expected Behavior

Create new autoscaling group, from scratch. 
### Actual Behavior

Apply failed

### Steps to Reproduce

1. Make terraform file containing resources for ASG, ASG Launch Config and whatever else you need
1. `terraform init`
2. `terraform apply`
### Additional Context

Running from command line

**Comment by bflad** [comment]
Hi @charlesarnaudo 👋  Sorry you ran into trouble here. Previous to the v1.12.0 release a few days ago, the documentation did not clarify the usage of the `availability_zones` attribute of the `aws_autoscaling_group` resource to be only required for EC2-Classic. In VPC environments, the subnet IDs passed into `vpc_zone_identifier` will automatically determine the availability zones (as a subnet is inherently part of a single AZ).

To fix your situation, simply remove the `availability_zones` configuration. Hope this helps!

**Comment by charlesarnaudo** [comment]
@bflad Awesome, thank you so much!
