### ISSUE TITLE
[Bug]: Can not disable `transit encryption` and `at_rest_encryption`

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform-provider-aws#39955]
### Terraform Core Version

v1.9.8

### AWS Provider Version

v5.67.0

### Affected Resource(s)

* aws_elasticache_replication_group

### Expected Behavior

When `at_rest_encryption_enabled = true` and `transit_encryption_enabled = true` options are removed terraform should detect that.

Default values should be described here:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#transit_encryption_enabled

### Actual Behavior

Nothing is detected.
No changes. Your infrastructure matches the configuration.

But:
![image](https://github.com/user-attachments/assets/457eabe0-bd9a-4e62-8bd6-3bf3bc83ba52)

### Terraform Configuration Files

```
resource "aws_elasticache_replication_group" "redis" {
  replication_group_id  = "redis"
  description           = "Redis cluster"
  subnet_group_name     = aws_elasticache_subnet_group.redis.name

  node_type                  = "cache.t2.micro"
  port                       = 6379
  parameter_group_name       = "default.redis7.cluster.on"
  automatic_failover_enabled = true
  num_cache_clusters         = 2

  at_rest_encryption_enabled = true
  transit_encryption_enabled = true
}
```

### Steps to Reproduce

Create Redis cluster with `at_rest_encryption_enabled = true` and `transit_encryption_enabled = true` options
Remove them
terraform plan/apply

### Would you like to implement a fix?

None

**Comment by rsafonseca** [comment]
On top of this, the default for at_rest_encryption_enabled has changed in the AWS API, but is not reflected in the API Docs, just in the Elasticache docs. I've already raised this with AWS to fix their docs.

To make it worse, when you set `at_rest_encryption_enabled = false` (or when you don't set it al all), it shows up in the plan that will be set to false, but in fact get set to true, which makes it appear on every run and require the ReplicationGroup to be recreated, rendering it unmanageable unless you explicitly set it to true.

**Comment by rsafonseca** [comment]
Hi @gdavison , thanks for taking this up.
Your MR only fixes one of the problems, which is the perpetual loop. This property should still be configurable beyond the default though and currently because it's set to Computed it cannot be configured.
