### ISSUE TITLE
[New Resource]: Security groups associated with multiple VPC

### ISSUE THREAD

**Issue by b-iurea** [hashicorp/terraform-provider-aws#39999]
### Description

Hi, 
AWS launched this new feature for Security Groups where despite the security group is associated with one vpc, you can later associate with other and multiple vpc.

For AWS doc: https://docs.aws.amazon.com/vpc/latest/userguide/security-group-assoc.html

Someone thinked about or is this resource a work in progress?

Thank you 
Bogdan I.

### Requested Resource(s) and/or Data Source(s)

aws_security_groups_associate_vpc

### Potential Terraform Configuration

```terraform
resource "aws_security_groups_associate_vpc" "example" {
    security_group_id = "string"
    vpc_ids = [list]
}
```

### References

https://docs.aws.amazon.com/vpc/latest/userguide/security-group-assoc.html

### Would you like to implement a fix?

None

**Comment by jar-b** [comment]
Relevant APIs:
- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssociateSecurityGroupVpc.html
- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DisassociateSecurityGroupVpc.html
- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeSecurityGroupVpcAssociations.html

**Comment by ddericco** [comment]
This is being worked on.

**Comment by alexbacchin** [comment]
@jar-b I raised the PR above but it was tagged as `enhancement`.
