### ISSUE TITLE
aws_elastic_beanstalk_environment - aws:elb:policies/Stickiness Policy does not apply choice

### ISSUE THREAD

**Issue by ebarault** [hashicorp/terraform-provider-aws#4000]
### Terraform Version
- Terraform: v0.11.5
- AWS provider: 1.13.0

### Affected Resource(s)
- aws_elastic_beanstalk_environment

### Terraform Configuration Files

The following setting does not apply and stickiness policy is set enabled in Elastic Beanstalk's classic ELB
```hcl
  setting {
    namespace = "aws:elb:policies"
    name      = "Stickiness Policy"
    value     = "false"
  }
```

Creating a custom aws:elb:policies:policy_name namespace named `AWSEB-ELB-StickinessPolicy` as per the [default aws:elb:policies policy name](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-elbpolicies) works and disable stickiness policy for the classic loadbalancer
```hcl
  setting {
    namespace = "aws:elb:policies:AWSEB-ELB-StickinessPolicy"
    name      = "Stickiness Policy"
    value     = "false"
  }
```

Unfortunately this setting (like any setting in a custom `aws:elb:policies:policy_name` namespace)  is not sticking and gets reapplied every time the `terraform apply` command is ran.

**Comment by szpuni** [comment]
Hi @ebarault i have tried your solution but it doesn't work either
I have have tried many iterations but none of them change stickiness
What did you do exactly to get it to work?

My namespaces are looking like this:

```
  setting {
    namespace = "aws:elb:policies:AWSEB-ELB-StickinessPolicy"
    name      = "LoadBalancerPorts"
    value     = "80,443"
  }
  setting {
    namespace = "aws:elb:policies:AWSEB-ELB-StickinessPolicy"
    name      = "Stickiness Policy"
    value     = "false"
  }
  setting {
    namespace = "aws:elb:listener:80"
    name      = "PolicyNames"
    value     = "AWSEB-ELB-StickinessPolicy"
  }
  setting {
    namespace = "aws:elb:listener:443"
    name      = "PolicyNames"
    value     = "AWSEB-ELB-StickinessPolicy"
  }

  setting {
    namespace = "aws:elb:policies"
    name      = "ConnectionDrainingEnabled"
    value     = "true"
  }
```
