### ISSUE TITLE
[Docs]: aws_backup_restore_testing_selection missing validation_window_hours

### ISSUE THREAD

**Issue by BNFlatpay** [hashicorp/terraform-provider-aws#40011]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_restore_testing_selection

### Description

Was looking for creating a selection of an RDS type for aws_backup_restore_testing_selection and was looking for where to set the retention period for the RDS instance and couldn't find any in the documentation linked. But 5.74 does contain the argument validation_window_hours which I assume is the retention period for how long the RDS instance will live before deletion.

### References

https://docs.aws.amazon.com/cli/latest/reference/backup/create-restore-testing-selection.html
![Screenshot 2024-11-05 at 12 13 34](https://github.com/user-attachments/assets/c89c401b-b009-44fa-b811-f76feb4c7bf9)

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Good morning, will have a look into this.
