### ISSUE TITLE
[Docs]: Incorrect information in `aws_sagemaker_space resource` doc: `code_repository` is actually not supported in `code_editor_app_settings`

### ISSUE THREAD

**Issue by MeirP-3** [hashicorp/terraform-provider-aws#40038]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_space#code_editor_app_settings-block

### Description

The doc lists `code_repository` as argument for `code_editor_app_settings`. Trying to apply it with terraform fails:
>$ terraform version
```
Terraform v1.9.8
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.74.0
```
>$ terraform apply
```
Error: Unsupported block type
 
   on sagemaker_spaces.tf line 8, in resource "aws_sagemaker_space" "space":
    8:       code_repository {

Blocks of type "code_repository" are not expected here.
```

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Hello @MeirP-3,

thank you for taking your time and raising the issue!

 I had a first look into the provider implementation and documentation:
- In the [provider implementation](https://github.com/hashicorp/terraform-provider-aws/blob/c8fa0fa3eb40e37c59e7b28e44659b51609e35e5/internal/service/sagemaker/space.go#L102) I can see `app_lifecycle_management` and `default_resource_spec` as allowed values.  No `code_repository` .
- In the [AWS GO SDK v2](https://github.com/aws/aws-sdk-go-v2/blob/70eb57ac775f782db6856c73f1ca22eae8e48ac2/service/sagemaker/types/types.go#L16682) the relevant struct is similar, it is not containing `code_repository`.

  ```golang
  type SpaceCodeEditorAppSettings struct {
    AppLifecycleManagement *SpaceAppLifecycleManagement
    DefaultResourceSpec *ResourceSpec
    noSmithyDocumentSerde
  }
  ```

Let me update the documentation accordingly.
