### ISSUE TITLE
[Bug]: Error: deleting Image Builder Image Recipe

### ISSUE THREAD

**Issue by ericrichtert** [hashicorp/terraform-provider-aws#40037]
### Terraform Core Version

1.9.8

### AWS Provider Version

5.74.0

### Affected Resource(s)

* aws_imagebuilder_image_recipe

### Expected Behavior

A new version of the recipe, as is working fine with version 5.73.

### Actual Behavior

An error occurs:

```console
Error: deleting Image Builder Image Recipe (arn:aws:imagebuilder:eu-west-1:0000:image-recipe/tf-imagebuilder-image-recipe-amzl2-ohra/1.0.0): operation error imagebuilder: DeleteImageRecipe, https response error StatusCode: 400, RequestID: xxxx, ResourceDependencyException: Resource dependency error: The resource ARN 'arn:aws:imagebuilder:eu-west-1:xxxx:image-recipe/tf-imagebuilder-image-recipe-amzl2-ohra/1.0.0' has other resources depended on it
```

### Terraform Configuration Files

```hcl
resource "aws_imagebuilder_image_recipe" "tf-imagebuilder-image-recipe-amzl2-ohra" {
  name              = "tf-imagebuilder-image-recipe-amzl2-xxx"
  parent_image      = "ami-xxxxxxx"
  version           = "1.0.0"
  working_directory = "/var/tmp"

  block_device_mapping {
    device_name = "/dev/xvda"

    ebs {
      delete_on_termination = true
      volume_size           = 30   
      volume_type           = "gp3" 
      encrypted             = true
      kms_key_id            = aws_kms_alias.tf-kms-alias-imagebuilder-xxxx-image.target_key_arn
    }
  }

  component {
    component_arn = data.aws_imagebuilder_component.tf-imagebuilder-component-amzl2-yum-update.arn
  }
}
```

### Steps to Reproduce

Update the ami to another ID (ami-uuuu) and apply. With version 5.74.0 the error occurs, with 5.73, eeverything goes well

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @ericrichtert 👋 Thank you for taking the time to raise this! This looks pretty similar to what was reported in #39985. Can you test the solution mentioned there (use of `replace_triggered_by`) and let us know if that solves the issue for you as well?

**Comment by Jorge-Rodriguez** [comment]
This has not been fixed. It appears in AWS Provider v.5.78.0
