### ISSUE TITLE
[Docs]: Missing AWS Target group attribute

### ISSUE THREAD

**Issue by samh241** [hashicorp/terraform-provider-aws#40053]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group_attachment

### Description

There is a missing attribute of `preserve_client_ip`  in the documentation.

```
preserve_client_ip - (Optional) - Preserves the client's IP address - The value is true or false and the default is false. 
The default is disabled if the target group type is IP address and the target group protocol is TCP or TLS. Otherwise, the default is enabled. Client IP preservation can't be disabled for UDP and TCP_UDP target groups.
```

### References

[PR the attribute was added](https://github.com/hashicorp/terraform-provider-aws/issues/17550) 
[AWS documentation - Network Load Balancers](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#target-group-attributes) - section 'Target group attributes' mentions preserve_client_ip.enabled attribute
[AWS documentation - Network Load Balancers](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#client-ip-preservation) - section 'Client IP preservation' describes the effect of the attribute

### Would you like to implement a fix?

No

**Comment by stefanfreitag** [comment]
Hi @samh241,
let me have a look into updating the documentation.

**Comment by stefanfreitag** [comment]
Good evening @samh241,

I had a look into the source code and available documentation. Could you please do me a favor and review the documentation link you provided? 
It points to the documentation for a load balancer target group *attachment*  resource and not to the one a load balancer target group resource (mentioned in the issue title).

The [documentation for the load balancer target group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group) contains already

> [preserve_client_ip](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group#preserve_client_ip-2) - (Optional) Whether client IP preservation is enabled. See [doc](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#client-ip-preservation) for more information.

If I got something wrong, please let me know.

**Comment by samh241** [comment]
Hi @stefanfreitag, apologies, yes my mistake I have got that wrong. Thank you for having a look and posting that link 👍
