### ISSUE TITLE
[Docs]: Clarify what will be destroyed

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform-provider-aws#40086]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#user_data_replace_on_change-1

### Description

It could suppose that you are speading about that EC2 instance will be destroyed. It would be better to spell that explicitly.
Thanks

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @EugenKon 👋 Thank you for taking the time to raise this! Are you essentially saying you'd like the phrasing to be updated as follows?

Old:

> will trigger a destroy and recreate

New:

> will trigger a destroy and recreate of the instance

If I've misunderstood, let me know. My personal take is that I'm not sure what else it would be referring to destroying, but I spend so much time staring at the provider and its documentation that sometimes it's hard to see the forest for the trees 🙂.

**Comment by EugenKon** [comment]
Yes, correct.

**Comment by stefanfreitag** [comment]
Hi all, seems to be a minor one, can squeeze it in.
