### ISSUE TITLE
Unable to use @ symbol in EC2 user data shell script

### ISSUE THREAD

**Issue by K111098** [hashicorp/terraform-provider-aws#40102]
### Description

Hello - I have an EC2 instance being created by Terraform. I am passing a shell script for the user data to be run on creation of the ec2 instance which is passed to terraform using a data "template_file" block. Within the bash script I have the following line of code: 
for username in "$usernames[@]}"; do

TFE is throwing an error saying: Failed to render: <template file>:80, 30-31: invalid character, this character is not used within this language and 1 other diagnostic.

The character it is referring to is where the @ symbol is. I have also tried using eval in the shell script but that does not work either. Any ideas from anyone on how to resolve?

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @K111098 👋 Thank you for taking the time to raise this! It looks like the error you're receiving is coming from Terraform Core while it's processing the configuration. We use Issues in this repository to track feature enhancements and bugs in the AWS Provider; to maintain that, we ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Terraform forum](https://discuss.hashicorp.com/c/terraform-core/27). With that in mind, I'm going to close this issue.
