### ISSUE TITLE
[Bug]: aws_api_gateway_deployment.stage_name deprecation forces resources to be re-created

### ISSUE THREAD

**Issue by jrobison-sb** [hashicorp/terraform-provider-aws#40118]
### Terraform Core Version

v1.9.1

### AWS Provider Version

v5.75.1

### Affected Resource(s)

* aws_api_gateway_deployment
* aws_api_gateway_stage

### Expected Behavior

You should not have to re-create your already-deployed cloud resources because something in this provider changed.

### Actual Behavior

You have to to re-create your already-deployed cloud resources because something in this provider changed.

### Terraform Configuration Files

We've been using HCL like this for a long time:
```
resource "aws_api_gateway_deployment" "default" {
  rest_api_id = aws_api_gateway_rest_api.default.id
  stage_name = "foo"
}
```

https://github.com/hashicorp/terraform-provider-aws/pull/40067 was released a few days ago and deprecates the `stage_name` attribute, which apparently needs to use a standalone `aws_api_gateway_stage` resource instead. So I changed the HCL like this:
```
resource "aws_api_gateway_deployment" "default" {
  depends_on = [aws_api_gateway_integration.lambda]
  rest_api_id = aws_api_gateway_rest_api.default.id
}

resource "aws_api_gateway_stage" "default" {
  deployment_id = aws_api_gateway_deployment.default.id
  rest_api_id   = aws_api_gateway_rest_api.default.id
  stage_name    = "foo"
}
```

I then `terraform import`'ed the already-existing stage to the new resource, which imported successfully.

But any subsequent `terraform plan` still proposes to delete and recreate the deployment, because it detects the deployment's `stage_name` as being deleted:
```
  # module.some_application.aws_api_gateway_deployment.default must be replaced
+/- resource "aws_api_gateway_deployment" "default" {
      - stage_name    = "foo" -> null # forces replacement
        # (2 unchanged attributes hidden)
    }
```

We need a way to migrate to the new resource type without destroying any deployed resources in AWS. The only changes necessary for this should be entirely within the terraform state.

### Steps to Reproduce

Try to fix the deprecation introduced in https://github.com/hashicorp/terraform-provider-aws/pull/40067 for an already-deployed resource using HCL similar to what I pasted above, and try to do it without destroying / re-creating anything in AWS.

### References

https://github.com/hashicorp/terraform-provider-aws/pull/40067
https://github.com/hashicorp/terraform-provider-aws/issues/39958

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @jrobison-sb 👋 Thank you for taking the time to raise this! While this waits for prioritization/review, I wanted to note that you should be able to get past this by removing the `aws_api_gateway_deployment` from the state file with [`terraform state rm`](https://developer.hashicorp.com/terraform/cli/commands/state/rm) and then [re-importing it](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_deployment#import). I realize this isn't a perfect solution, but wanted to offer something to get you moving again in the meantime.

**Comment by jrobison-sb** [comment]
Thanks @justinretzolk, that unblocked me.

I'll leave this issue open in case it's useful for prioritizing the longer term fix for others, but I personally am all set and have no personal objection if you want to close this.

Thanks again for helping me on this one.

**Comment by justinretzolk** [comment]
Glad to hear that helped @jrobison-sb! Given that re-importing resolved the issue for you, I'll go ahead and close this one for now. I suspect that long-term, once the argument is removed from the resource, this will wind up being a non-issue, but if anyone else comes across this and experiences a similar issue, please do let us know so that we can investigate further.
