### ISSUE TITLE
[Enhancement]: Support for Resource Control Policies

### ISSUE THREAD

**Issue by jack-parsons-bjss** [hashicorp/terraform-provider-aws#40126]
### Description

AWS has just announced a new feature of Organizations: Resource Control Policies, or RCPs. Please could we have support for them added?

### Affected Resource(s) and/or Data Source(s)

* aws_organizations_policy

### Potential Terraform Configuration

```terraform
data "aws_iam_policy_document" "example" {
  statement {
    effect    = "Allow"
    actions   = ["*"]
    resources = ["*"]
  }
}

resource "aws_organizations_policy" "example" {
  name    = "example"
  content = data.aws_iam_policy_document.example.json
  type    = "RESOURCE_CONTROL_POLICY"
}
```

### References

https://aws.amazon.com/blogs/aws/introducing-resource-control-policies-rcps-a-new-authorization-policy/

### Would you like to implement a fix?

No

**Comment by alexbacchin** [comment]
@jack-parsons-bjss the provider updates the references automatically #40125 already in for review.

**Comment by aristosvo** [comment]
I think the support depends indeed on #40125 and merging that will enable at least `aws_organizations_policy` as provided above.

The whole flow including attachment to OUs might require a bit more work here and there.

**Comment by NBIX-Robert-Suarez** [comment]
This is a huge leap forward for org level security... anxiously awaiting this release

**Comment by justinretzolk** [comment]
Hi all 👋 AWS Provider version `5.76.0` was released earlier today and includes #40125, which seems to enable this. Before I close this issue, can someone test and verify that it's working as expected?

**Comment by peteraglen** [comment]
Just tested with 5.76.0, and everything seems to be working. Enabled `RESOURCE_CONTROL_POLICY` in the `aws_organizations_organization` resource, added a new RCP as an `aws_organizations_policy` resource, and attached it to an OU.

**Comment by igordust** [comment]
Don't forget to update the documentation, as of now, it doesn't mention `RESOURCE_CONTROL_POLICY` among the available types.
