### ISSUE TITLE
[New Resource]: aws_ecr_account_setting resource should exist

### ISSUE THREAD

**Issue by jrobison-sb** [hashicorp/terraform-provider-aws#40140]
### Description

AWS [now offers](https://aws.amazon.com/about-aws/whats-new/2024/08/new-version-amazon-ecr-basic-scanning/) two versions of ECR scanning, `CLAIR` (the old version which people have been using for a long time), and `AWS_NATIVE` (a new thing that they just recently released, and which will eventually become the only supported version). AWS has [an API endpoint](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_PutAccountSetting.html) to choose which version you want, and Terraform should use that API to manage this setting for users.

### Requested Resource(s) and/or Data Source(s)

* aws_ecr_account_setting

### Potential Terraform Configuration

```terraform
resource "aws_ecr_account_setting" "setting" {
  name  = "BASIC_SCAN_TYPE_VERSION"
  value = "AWS_NATIVE"
}
```

### References

We are reaching out to let you know that your account is using the previous version of ECR basic scanning [1]. Starting October 1, 2025, the previous version of ECR basic scanning [1] will not be supported. On August 6, 2024, ECR announced [2] the general availability of a new, improved version of its basic scanning feature. This new version uses Amazon’s native scanning technology, which is designed to provide customers with improved scanning results and vulnerability detection across a broad set of popular operating systems. This allows customers to further strengthen the security of their container images. New ECR accounts are automatically opted into using the new scanning version.

You can easily switch your account to the new version via the AWS console or using the new put-account-setting API as shown in the 'ECR API' documentation [3]. Please note that you will have to trigger a new scan of your images to regenerate the scan findings after you switch to the new version.

The new version of ECR basic scanning [1] is generally available in all AWS commercial Regions, AWS China Regions, and the AWS GovCloud (US) Regions at no additional cost. We recommend that you make this switch at your earliest convenience.

If you have any questions or concerns, please contact AWS Support [4].

[1] https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning-basic.html
[2] https://aws.amazon.com/about-aws/whats-new/2024/08/new-version-amazon-ecr-basic-scanning/
[3] https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_PutAccountSetting.html
[4] https://aws.amazon.com/support/

Sincerely,
Amazon Web Services

### Would you like to implement a fix?

No

**Comment by acdha** [comment]
@jrobison-sb Wouldn't your proposed syntax want to have the name as well to accommodate additional future settings?

```hcl
resource "aws_ecr_account_setting" "setting" {
  name = "BASIC_SCAN_TYPE_VERSION"
  value = "AWS_NATIVE"
}
```

**Comment by good92** [comment]
Should https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_registry_scanning_configuration must be more appropriate for its configuration?

https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_PutAccountSetting.html

**Comment by jrobison-sb** [comment]
> @jrobison-sb Wouldn't your proposed syntax want to have the name as well to accommodate additional future settings?
> 
> ```hcl
> resource "aws_ecr_account_setting" "setting" {
>   name = "BASIC_SCAN_TYPE_VERSION"
>   value = "AWS_NATIVE"
> }
> ```

@acdha yeah, this makes sense. I didn't see any reference to `BASIC_SCAN_TYPE_VERSION` in the API doc initially, but after a bit of Googling I see a few references to this elsewhere. I have now updated the example in the OP.
