### ISSUE TITLE
[Enhancement]: Add support for root credential management

### ISSUE THREAD

**Issue by CyberViking949** [hashicorp/terraform-provider-aws#40151]
### Description

> Today, AWS Identity and Access Management (IAM) is launching a new capability allowing customers to centrally manage their root credentials, simplify auditing of credentials, and perform tightly scoped privileged tasks across their AWS member accounts managed using AWS Organizations.

* [Announcement 1](https://aws.amazon.com/about-aws/whats-new/2024/11/manage-root-access-aws-identity-access-management/)
* [Announcement 2](https://aws.amazon.com/about-aws/whats-new/2024/11/aws-organizations-member-accounts-access-locked-amazon-3-buckets/)
* [Blog post](https://aws.amazon.com/blogs/aws/centrally-managing-root-access-for-customers-using-aws-organizations/)

### Potential Terraform Configuration

```terraform
resource "aws_org_root_management" "root_mgmt" {
org_id = "o-xxxx"
enabled_features = [ "RootCredentialsManagement"]
}

resource "root_session_mgmt" "sessions_mgmt" {
org_id = "o-xxxx"
enabled_features = [ "RootSessions", "RootCredentialsManagement" ]
}
```

### Would you like to implement a fix?

None

**Comment by aristosvo** [comment]
I will try to implement these resources. Let me know if you want to collaborate, always up for working together!

**Comment by alexbacchin** [comment]
@aristosvo I have only seen your message after submitting the PR.  I took the 2nd approach and implemented as a single resource.

**Comment by aristosvo** [comment]
Looks exactly like I was planning to do it 👌🫣 LGTM!🚀

**Comment by CyberViking949** [comment]
Awesome, thanks everyone for the fast turn around
