### ISSUE TITLE
[Enhancement]: Add support for Python and .NET Lambda runtime SnapStart

### ISSUE THREAD

**Issue by grammeaway** [hashicorp/terraform-provider-aws#40178]
### Description

AWS recently announced that the Lambda SnapStart feature (until now only supported on Java runtimes), has been expanded to also cover Python (3.12 and newer) and .NET (8 and newer) runtimes. It would be great to have that option in the next provider release, since the SnapStart field is already a part of the resource :)

### Affected Resource(s) and/or Data Source(s)

aws_lambda_function

### References

Announcement: https://aws.amazon.com/about-aws/whats-new/2024/11/aws-lambda-snapstart-python-net-functions/
Docs: https://docs.aws.amazon.com/lambda/latest/dg/snapstart.html 

### Would you like to implement a fix?

No

**Comment by aristosvo** [comment]
Hi @grammeaway👋 

I think you can already use it with the newly supported runtime languages, only docs are lacking as far as I can see. Validation for supported runtimes is not configured on the Terraform Provider.

**Comment by grammeaway** [comment]
@aristosvo ah, sorry, that's my bad! That's a misconception on my part - I'll close the issue then~

**Comment by aristosvo** [comment]
@grammeaway Don't worry, as long as the docs aren't updated this is a question which is completely valid.

Please try it out as well, if for any reason it doesn't work out I'd like to hear.
