### ISSUE TITLE
[New]: `aws_sesv2_configuration_set` is missing `HttpsPolicy` and `MaxDeliverySeconds`

### ISSUE THREAD

**Issue by Manouchehri** [hashicorp/terraform-provider-aws#40170]
### Description

AWS SESv2 now has two new options for config sets: HTTPS Policy for tracking, and Max Delivery Seconds.

### Requested Resource(s) and/or Data Source(s)

* aws_sesv2_configuration_set.delivery_options.max_delivery_seconds
* aws_sesv2_configuration_set.tracking_options.https_policy

### References

https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_DeliveryOptions.html#SES-Type-DeliveryOptions-MaxDeliverySeconds

https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_TrackingOptions.html#SES-Type-TrackingOptions-HttpsPolicy

### Would you like to implement a fix?

No

**Comment by lvthillo** [comment]
We're also missing one of these settings. I'll try to open a PR later today / tomorrow.
