### ISSUE TITLE
[Enhancement]: Add tags support for aws_route53profiles_profile and aws_route53profiles_association

### ISSUE THREAD

**Issue by ineednewpajamas** [hashicorp/terraform-provider-aws#40241]
### Description

Add support for the `tags` argument for aws_route53profiles_profile and aws_route53profiles_association. Tags are supported in awscc and the sdk.

### Affected Resource(s) and/or Data Source(s)

aws_route53profiles_profile
aws_route53profiles_association

### Potential Terraform Configuration

```terraform
resource "aws_route53profiles_profile" "dev" {
  name = "example"

  tags = {
    Environment = "dev"
  }
}
```

### References

https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/route53profiles_profile
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/route53profiles#CreateProfileInput

### Would you like to implement a fix?

No

**Comment by ineednewpajamas** [comment]
tags_all which is just exported, and default_tags which is what feeds tags_all is not what I'm looking for. We need the ability to define specific tags for the resources.

**Comment by jeremychauvet** [comment]
Hello again @ineednewpajamas!
I've opened a PR on the provider to improve the documentation, thank you again for raising this issue!

I'm also able to confirm you can already add tags. I've successfully managed to add two tags on a profile using the following code:

```hcl
resource "aws_route53profiles_profile" "dev" {
  name = "example"

  tags = {
    IssueNumber = "40241"
    IssueLink = "https://github.com/hashicorp/terraform-provider-aws/issues/40241"
  }
}
```

**Comment by ineednewpajamas** [comment]
That does seem to be the case, I didn't have a chance to dig into the code before. Thanks for looking.
