### ISSUE TITLE
[Enhancement]: update `aws_rds_cluster` to allow auto_pause when aurora engine_mode is `provisioned`

### ISSUE THREAD

**Issue by luisrx7** [hashicorp/terraform-provider-aws#40258]
### Description

According to this [AWS documentation](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2-auto-pause.html#auto-pause-enabling-disabling), it is now possible to set up auto-pause for Aurora in `provisioned` mode. However, the provider's documentation contradicts this by stating that auto-pause can only be configured if the cluster is in `serverless` mode. Conversely, through the console, it is possible to configure auto-pause for a cluster in `provisioned` mode.

### Affected Resource(s) and/or Data Source(s)

aws_rds_cluster

### Potential Terraform Configuration

```terraform
serverlessv2_scaling_configuration {
    max_capacity = 256.0
    min_capacity = 0
    auto_pause               = true
    seconds_until_auto_pause = 300
  }
```

### References

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2-auto-pause.html#auto-pause-enabling-disabling

### Would you like to implement a fix?

No

**Comment by fatbasstard** [comment]
Bonus feature when working on this:

`expected serverlessv2_scaling_configuration.0.min_capacity to be in the range (0.500000 - 256.000000), got 0.000000` this has to support 0

**Comment by avoelkle** [comment]
May be fixed by https://github.com/hashicorp/terraform-provider-aws/pull/40230
