### ISSUE TITLE
API Gateway custom domain names for private REST APIs

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#40274]
> Amazon API Gateway (APIGW) now gives you the ability to manage your private REST APIs using custom user-friendly private DNS name like private.example.com, simplifying API discovery.

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/11/amazon-api-gateway-custom-domain-name-private-rest-apis/)
* [Blog post](https://aws.amazon.com/blogs/compute/implementing-custom-domain-names-for-private-endpoints-with-amazon-api-gateway/)
* [Developer Guide](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-custom-domains.html)

**Comment by mmichna** [comment]
+1

**Comment by raman-auseyenka-fan** [comment]
+1
Waiting for release :)
