### ISSUE TITLE
[Bug]: aws_fsx_windows_file_system throughput_capacity can be only 2048MB/s but in AWS console 12288MB/s

### ISSUE THREAD

**Issue by wsmolkowski** [hashicorp/terraform-provider-aws#40289]
### Terraform Core Version

1.5.7

### AWS Provider Version

5.77.0

### Affected Resource(s)

aws_fsx_windows_file_system throughput_capacity can be only 2048MB/s but in AWS console 12288MB/s

### Expected Behavior

can set throughput_capacity to 12288MB/s

### Actual Behavior

max is 2048 MB/s

### Relevant Error/Panic Output Snippet

```shell
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: expected throughput_capacity to be in the range (8 - 2048), got 4608
│
```

### Terraform Configuration Files

```hcl
resource "aws_fsx_windows_file_system" "example" {
  active_directory_id = aws_directory_service_directory.example.id
  kms_key_id          = aws_kms_key.example.arn
  storage_capacity    = 300
  subnet_ids          = [aws_subnet.example.id]
  throughput_capacity = 4096
}
```

### Steps to Reproduce

create resource with   throughput_capacity > 2048

### Debug Output

```
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: expected throughput_capacity to be in the range (8 - 2048), got 4608
```

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Hi @wsmolkowski,

thank you for reporting the issue. 

I had a quick look into the AWS provider source code. The allowed range is specified [here](https://github.com/hashicorp/terraform-provider-aws/blob/0c9edd45ad5b079fe7186bf8ac957371a964811c/internal/service/fsx/windows_file_system.go#L284) and a valid value is between 8 and 2048.

In the AWS documentation I found a [section](https://docs.aws.amazon.com/fsx/latest/WindowsGuide/performance.html#perf-overview) that explains that the supported max value depends on the region:

> Amazon FSx file systems provide up to 2 GB/s and 80,000 IOPS in all AWS Regions where Amazon FSx is available, and 12 GB/s of throughput and 400,000 IOPS in US East (N. Virginia), US West (Oregon), US East (Ohio), Europe (Ireland), Asia Pacific (Tokyo), and Asia Pacific (Singapore). 

Hope that helps to understand the current situation.

**Comment by ewbankkit** [comment]
* [Announcement](https://aws.amazon.com/about-aws/whats-new/2023/08/amazon-fsx-windows-file-server-increases-throughput-12-gbs/)
