### ISSUE TITLE
Cloud WAN integration with Direct Connect

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#40310]
> AWS Cloud WAN now supports native integration with AWS Direct Connect, simplifying connectivity between your on-premises networks and the AWS cloud.

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/11/aws-cloud-wan-on-premises-connectivity-direct-connect/)
* [Blog post](https://aws.amazon.com/blogs/networking-and-content-delivery/simplify-global-hybrid-connectivity-with-aws-cloud-wan-and-aws-direct-connect-integration/)

### Affected Resource(s) and/or Data Source(s)

* `aws_networkmanager_dx_gateway_attachment`

**Comment by ddericco** [comment]
I'm working on adding this support

**Comment by ddericco** [comment]
My goal is to have a PR ready by the end of this week.
