### ISSUE TITLE
[Enhancement]: Add domain name support for private api gateway

### ISSUE THREAD

**Issue by lukasgabi** [hashicorp/terraform-provider-aws#40326]
### Description

AWS has enabled support for custom domains on private api gateway instances. The domain name needs to be configured as part of the [endpoint configuration](https://docs.aws.amazon.com/apigateway/latest/api/API_EndpointConfiguration.html), this is currently not possible with terraform as it fails with validation with the following configuration:

```terraform
resource "aws_api_gateway_domain_name" "this" {
  regional_certificate_arn = aws_acm_certificate.this.arn
  domain_name              = var.domain_name
  endpoint_configuration {
    types = ["PRIVATE"] 
  }
}
```

This configuration currently throws the following error
> Error: expected endpoint_configuration.0.types.0 to be one of ["EDGE" "REGIONAL"], got PRIVATE

### Affected Resource(s) and/or Data Source(s)

* aws_api_gateway_domain_name

### Potential Terraform Configuration

```terraform
resource "aws_api_gateway_domain_name" "this" {
  regional_certificate_arn = aws_acm_certificate.this.arn
  domain_name              = var.domain_name
  endpoint_configuration {
    types = ["PRIVATE"] 
  }
}
```

### References

* https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-custom-domains.html
* https://docs.aws.amazon.com/apigateway/latest/api/API_EndpointConfiguration.html

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@lukasgabi Thanks for raising this issue.
It has already been noticed in #40274. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
