### ISSUE TITLE
[Enhancement]: Support PrivateLink Cross Region Connectivity

### ISSUE THREAD

**Issue by kimxogus** [hashicorp/terraform-provider-aws#40321]
### Description

AWS Private Link now supports cross-region connectivity.

### Affected Resource(s) and/or Data Source(s)

- `aws_vpc_endpoint_service`
- `data.aws_vpc_endpoint_service`

### Potential Terraform Configuration

```terraform
resource "aws_vpc_endpoint_service" "this" {
  ...
  service_regions = ["us-east-1", "us-west-2", "ap-northeast-1"]
}
```

### References

- https://aws.amazon.com/ko/about-aws/whats-new/2024/11/aws-privatelink-across-region-connectivity/

### Would you like to implement a fix?

No

**Comment by drewtul** [comment]
If this hasn't been picked up already I'll take a look
