### ISSUE TITLE
[Docs]: `aws_eks_cluster.kubernetes_network_config` is incorrectly formatted

### ISSUE THREAD

**Issue by SplinterHead** [hashicorp/terraform-provider-aws#40331]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#attribute-reference

### Description

`aws_eks_cluster.kubernetes_network_config` feels like it should be it's own section, but it is part of the root Attributes
Because of this, the `service_ipv4_cidr` or `ip_family` are completely undocumented

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Hi @SplinterHead!

Thank you for reporting the issue in the documentation for the `aws_eks_cluster` resource.
Let me have a look into it and prepare an update.
