### ISSUE TITLE
[Docs]: aws_resiliencehub_resiliency_policy, incorrect attribute names in sample code

### ISSUE THREAD

**Issue by jr-elliott** [hashicorp/terraform-provider-aws#40334]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/resiliencehub_resiliency_policy

### Description

The sample code contains "policy_name" and "policy_description", however this throws an error with terraform validate. The Argument Reference section has the correct attribute names, "name" and "description".

"policy_" should be removed from the sample code:

https://github.com/hashicorp/terraform-provider-aws/blob/398878c25514754dd22789c985e717c45c64a513/website/docs/r/resiliencehub_resiliency_policy.html.markdown?plain=1#L17

### References

![image](https://github.com/user-attachments/assets/8f3aeefb-0473-4b41-b802-5376a6485d78)

### Would you like to implement a fix?

Yes

**Comment by stefanfreitag** [comment]
Hi @jr-elliott,

can I pick this one up and prepare the required changes?

**Comment by jr-elliott** [comment]
> Hi @jr-elliott,
> 
> can I pick this one up and prepare the required changes?

Yeah, feel free to. I was waiting for the issue to be triaged and confirmed, but maybe a PR can just be submitted.
