### ISSUE TITLE
Amazon MemoryDB Multi-Region

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#40374]
> Today, AWS announces the general availability of Amazon MemoryDB Multi-Region, a fully managed, active-active, multi-Region database that lets you build multi-Region applications with up to 99.999% availability and microsecond read and single-digit millisecond write latencies.

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/12/general-availability-amazon-memory-db-multi-region/)
* [Blog post](https://aws.amazon.com/blogs/aws/amazon-memorydb-multi-region-is-now-generally-available/)

Requires https://github.com/hashicorp/terraform-provider-aws/pull/40380.

**Comment by bschaatsbergen** [comment]
Picking this up 👍🏼
