### ISSUE TITLE
[Enhancement]: aws_autoscaling_policy customized_metric_specification is missing period attribute

### ISSUE THREAD

**Issue by SushiFu** [hashicorp/terraform-provider-aws#40391]
### Description

On a `aws_autoscaling_policy` when using a `target_tracking_configuration` with a `customized_metric_specification` you cannot specified a custom `Period` attribute as per defined on the AWS documentation.
I've tried successfully to update my policy with the UI and set a 300 seconds custom Period.

> Period
The period of the metric in seconds. The default value is 60. Accepted values are 10, 30, and 60. For high resolution metric, set the value to less than 60. For more information, see [Create a target tracking policy using high-resolution metrics for faster response](https://docs.aws.amazon.com/autoscaling/ec2/userguide/policy-creating-high-resolution-metrics.html).
Type: Integer
Valid Range: Minimum value of 1.
Required: No

### Affected Resource(s) and/or Data Source(s)

* aws_autoscaling_policy

### Potential Terraform Configuration

```terraform
resource "aws_autoscaling_policy" "tracking-policy-cpu" {
  name  = "MY_POLICY"

  autoscaling_group_name = "MY_ASG"
  policy_type            = "TargetTrackingScaling"

  target_tracking_configuration {
    target_value = 70
    customized_metric_specification {
      metrics {
        id = "m1"
        metric_stat {
          metric {
            namespace   = "AWS/EC2"
            metric_name = "CPUUtilization"
            dimensions {
              name  = "AutoScalingGroupName"
              value = "MY_ASG"
            }
          }
          period = 300
          stat   = "Average"
        }
        return_data = true
      }
    }
  }
}
```

### References

https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_CustomizedMetricSpecification.html

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@SushiFu Thanks for raising this issue.
It has already been noticed in #40298. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
