### ISSUE TITLE
[Enhancement]: Cross-Region Support for AWS PrivateLink

### ISSUE THREAD

**Issue by evfurman** [hashicorp/terraform-provider-aws#40394]
### Description

> AWS PrivateLink now supports native cross-region connectivity. Until now, Interface VPC endpoints only supported connectivity to VPC endpoint services in the same region. This launch enables customers to connect to VPC endpoint services hosted in other AWS Regions in the same AWS partition over Interface endpoints.

![image](https://github.com/user-attachments/assets/608338d7-4e06-44a6-bb40-f92dac806426)

[Announcement](https://aws.amazon.com/about-aws/whats-new/2024/11/aws-privatelink-across-region-connectivity/)
Requires: https://github.com/hashicorp/terraform-provider-aws/pull/40380.

### Affected Resource(s) and/or Data Source(s)

aws_vpc_endpoint
aws_vpc_endpoint_service

### Potential Terraform Configuration

```terraform
resource "aws_vpc_endpoint" "ec2" {
  vpc_id            = aws_vpc.main.id
  service_name      = "com.amazonaws.us-east-1.ec2"
  vpc_endpoint_type = "Interface"
  
  supported_regions = [
   "us-east-1", 
   "us-west-2"
  ]

  private_dns_enabled = true
}
```

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@ewbankkit Thanks for raising this issue.
It has already been noticed in #40346. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
