### ISSUE TITLE
[Docs]: Incorrect attribute name for guardrail_configuration in aws_bedrockagent_agent documentation

### ISSUE THREAD

**Issue by danushkaf** [hashicorp/terraform-provider-aws#40401]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/bedrockagent_agent

### Description

**Issue: Incorrect Attribute Name in Documentation**

The Terraform Registry documentation for the `aws_bedrockagent_agent` resource lists `guardrail_config` as the attribute name, but the actual implementation expects `guardrail_configuration`.

**Incorrect Documentation**:
- URL: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/bedrockagent_agent
- Incorrect attribute: `guardrail_config`

**Correct Implementation**:
- Source: [agent.go](https://github.com/hashicorp/terraform-provider-aws/blob/8dad2d3a602c8fc103a7eacb1fc9f4d3a9ac3994/internal/service/bedrockagent/agent.go#L103C5-L103C28)
- Correct attribute: `guardrail_configuration`

**Steps to Reproduce**:
1. Use `guardrail_config` in a resource block for `aws_bedrockagent_agent`.
2. Run `terraform plan` or `apply`.
3. Observe the error message: "`Blocks of type guardrail_config are not expected here.`"

**Suggested Fix**:
Update the Registry documentation to replace `guardrail_config` with `guardrail_configuration`.

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Good evening @danushkaf ,

thank you for reporting the issue and the detailed information.
Let me have a look into it.
