### ISSUE TITLE
[Bug]: Cannot create cost category with cost allocation tag as dimension based on rule of type 'Regular'

### ISSUE THREAD

**Issue by HansBraun** [hashicorp/terraform-provider-aws#40400]
### Terraform Core Version

1.9.8

### AWS Provider Version

5.78.0

### Affected Resource(s)

aws_ce_cost_category

### Expected Behavior

Cost Category is created like it is when using the uiin the AWS console.

### Actual Behavior

Error: expected key to be one of ["AZ" "INSTANCE_TYPE" "LINKED_ACCOUNT" "LINKED_ACCOUNT_NAME" "OPERATION" "PURCHASE_TYPE" "REGION" "SERVICE" "SERVICE_CODE" "USAGE_TYPE" "USAGE_TYPE_GROUP" "RECORD_TYPE" "OPERATING_SYSTEM" "TENANCY" "SCOPE" "PLATFORM" "SUBSCRIPTION_ID" "LEGAL_ENTITY_NAME" "DEPLOYMENT_OPTION" "DATABASE_ENGINE" "CACHE_ENGINE" "INSTANCE_TYPE_FAMILY" "BILLING_ENTITY" "RESERVATION_ID" "RESOURCE_ID" "RIGHTSIZING_TYPE" "SAVINGS_PLANS_TYPE" "SAVINGS_PLAN_ARN" "PAYMENT_OPTION" "AGREEMENT_END_DATE_TIME_AFTER" "AGREEMENT_END_DATE_TIME_BEFORE" "INVOICING_ENTITY" "ANOMALY_TOTAL_IMPACT_ABSOLUTE" "ANOMALY_TOTAL_IMPACT_PERCENTAGE"], got testTag

### Terraform Configuration Files

resource "aws_ce_cost_category" "test" {  
  
  
  #effective_start   = "2024-11-01T00:00:00Z"      
  name              = "test"
  rule_version      = "CostCategoryExpression.v1"

  #Rules
  rule  {   
      value = "Bolle"
      type = "REGULAR"
      #Condition
      rule{                
            dimension {                
                  key           = "testTag"
                  values        = ["Holle"]
                  match_options = ["EQUALS"]
              }
            }

          }
 }

### Steps to Reproduce

terraform plan

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Good evening @HansBraun ,

thank you for reporting this issue. Let me have a closer look into it!.
Can you explain the use case you have for `key = "testTag"`  when defining  `dimension` ?

**Comment by HansBraun** [comment]
Let me check that again. "testtag" should be a valid name of a cost allocation tag

**Comment by stefanfreitag** [comment]
Hi @HansBraun ,

is your use case then to use a cost allocation tag inside the rule?

I gave it a try via AWS Management Console. Compared to my initial investigation I enabled a cost allocation tag `application` upfront.

![image](https://github.com/user-attachments/assets/8d067d2e-088b-448c-8a11-f3d028af0730)

Now I can see the option to use such a tag enabled. The generated JSON contains

```hcl
"Rule": {
	"Tags": {
		"Key": "application",
		"Values": [
			"super-app-"
		],
		"MatchOptions": [
			"STARTS_WITH"
		]
	}
}
```

So, it is not utilizing `dimension` at all. Can you try to adapt your setup and try?

**Comment by HansBraun** [comment]
I apologize for the inconvenience. I apparantly misunderstood the example. Now it is working. Thank you for the clarification.
