### ISSUE TITLE
Add endpoint output to `aws_service_discovery_service` 

### ISSUE THREAD

**Issue by jeffnappi** [hashicorp/terraform-provider-aws#4044]
It would be very useful to have the `endpoint` output from `aws_service_discovery_service`.

e.g. if the `aws_service_discovery_private_dns_namespace`.`name` is `example.terraform.com` and the service name is `test`. The endpoint output from `aws_service_discovery_service` would be `test.example.terraform.com`.

I am currently having to interpolate strings to pass endpoints around and it's not very clean :disappointed: 

It would also be nice to have similar outputs from the rest of the `aws_service_discovery`* resources.

What are your thoughts @atsushi-ishibashi?

I'm willing to work on this if it makes sense.

**Comment by atsushi-ishibashi** [comment]
It is useful and makes sense👍

**Comment by vinhlh** [comment]
👍 great to have

**Comment by vladturbuleasa** [comment]
Would be awesome!
