### ISSUE TITLE
[Bug]: terraform-provider-aws_v5.72.1_x5 plugin crashed for resource group

### ISSUE THREAD

**Issue by isharul-roo** [hashicorp/terraform-provider-aws#40458]
### Terraform Core Version

v1.7.5

### AWS Provider Version

v5.72.1

### Affected Resource(s)

aws_resource_grp

### Expected Behavior

Applying changes should have tagged lambda function to particular resource groups

### Actual Behavior

╷
│ Error: Plugin did not respond
│ 
│   with module.apps.module.order_transform_carrefour_fr_sqs.aws_resourcegroups_resource.lambda[0],
│   on modules/sfn_lambda/main.tf line 49, in resource "aws_resourcegroups_resource" "lambda":
│   49: resource "aws_resourcegroups_resource" "lambda" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-aws_v5.72.1_x5 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 95 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups.resourceResourceCreate({0x1af8b688, 0xc0049565d0}, 0xc00495e000, {0x18b88420, 0xc001657a00})
	github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups/resource.go:66 +0x785
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func9(0xc00495e000?, {0x18b88420?, 0xc001657a00})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1af8b688?, {0x1af8b688?, 0xc004941a10?}, 0xd?, {0x18b88420?, 0xc001657a00?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:801 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc002ef1180, {0x1af8b688, 0xc004941a10}, 0xc00465d110, 0xc004641e00, {0x18b88420, 0xc001657a00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:937 +0xa69
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc001686240, {0x1af8b688?, 0xc004941950?}, 0xc0049038b0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:1153 +0xd5c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xc001cbbd50, {0x1af8b688?, 0xc004941680?}, 0xc0049038b0)
	github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc002309ea0, {0x1af8b688?, 0xc004940ea0?}, 0xc002063ea0)
	github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov5/tf5server/server.go:865 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x189cdba0, 0xc002309ea0}, {0x1af8b688, 0xc004940ea0}, 0xc004641b80, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:545 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0013a0200, {0x1af8b688, 0xc004940e10}, {0x1b005b00, 0xc0018d04e0}, 0xc0049459e0, 0xc001a0cb10, 0x2596f538, 0x0)
	google.golang.org/grpc@v1.66.2/server.go:1394 +0xe2b
google.golang.org/grpc.(*Server).handleStream(0xc0013a0200, {0x1b005b00, 0xc0018d04e0}, 0xc0049459e0)
	google.golang.org/grpc@v1.66.2/server.go:1805 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.66.2/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 55
	google.golang.org/grpc@v1.66.2/server.go:1040 +0x125

Error: The terraform-provider-aws_v5.72.1_x5 plugin crashed!

### Terraform Configuration Files

resource "aws_resourcegroups_resource" "lambda" {
  count     = var.partner_slug != "" ? 1 : 0
  group_arn    = "aws_resourcegroups_group.${var.partner_slug}-${var.env_name}-group.arn"
  resource_arn = module.lambda.lambda_function_arn
}

### Steps to Reproduce

- Add this resource group resource under lambda modules - main.tf
- Make sure to add relevant partner_slug or env_name in variables
- Set variables with proper values in partner specific lambdas functions to

### Panic Output

╷
│ Error: Plugin did not respond
│ 
│   with module.apps.module.order_transform_carrefour_fr_sqs.aws_resourcegroups_resource.lambda[0],
│   on modules/sfn_lambda/main.tf line 49, in resource "aws_resourcegroups_resource" "lambda":
│   49: resource "aws_resourcegroups_resource" "lambda" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-aws_v5.72.1_x5 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 95 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups.resourceResourceCreate({0x1af8b688, 0xc0049565d0}, 0xc00495e000, {0x18b88420, 0xc001657a00})
	github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups/resource.go:66 +0x785
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func9(0xc00495e000?, {0x18b88420?, 0xc001657a00})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1af8b688?, {0x1af8b688?, 0xc004941a10?}, 0xd?, {0x18b88420?, 0xc001657a00?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:801 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc002ef1180, {0x1af8b688, 0xc004941a10}, 0xc00465d110, 0xc004641e00, {0x18b88420, 0xc001657a00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:937 +0xa69
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc001686240, {0x1af8b688?, 0xc004941950?}, 0xc0049038b0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:1153 +0xd5c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xc001cbbd50, {0x1af8b688?, 0xc004941680?}, 0xc0049038b0)
	github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc002309ea0, {0x1af8b688?, 0xc004940ea0?}, 0xc002063ea0)
	github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov5/tf5server/server.go:865 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x189cdba0, 0xc002309ea0}, {0x1af8b688, 0xc004940ea0}, 0xc004641b80, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:545 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0013a0200, {0x1af8b688, 0xc004940e10}, {0x1b005b00, 0xc0018d04e0}, 0xc0049459e0, 0xc001a0cb10, 0x2596f538, 0x0)
	google.golang.org/grpc@v1.66.2/server.go:1394 +0xe2b
google.golang.org/grpc.(*Server).handleStream(0xc0013a0200, {0x1b005b00, 0xc0018d04e0}, 0xc0049459e0)
	google.golang.org/grpc@v1.66.2/server.go:1805 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.66.2/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 55
	google.golang.org/grpc@v1.66.2/server.go:1040 +0x125

Error: The terraform-provider-aws_v5.72.1_x5 plugin crashed!

### Would you like to implement a fix?

No

**Comment by stefanfreitag** [comment]
Good evening @isharul-roo!

Thank you for taking your time for raising the issue and provided the details.

Based on the stack trace I think the providers errors [here](https://github.com/hashicorp/terraform-provider-aws/blob/089b4958560c3ef5e3366fa2d3253217fcf61eb4/internal/service/resourcegroups/resource.go#L66)

```go
id := strings.Join([]string{strings.Split(strings.ToLower(groupARN), "/")[1], strings.Split(resourceARN, "/")[1]}, "_")
```

Just from reading this code line group as well as resource ARN need to contain an "/". 

 EC2 resource  ARNs follow this format, e.g. something like `arn:aws:ec2:us-east-1:4575734578134:instance/i-054dsfg34gdsfg38`, Lambdas maybe not e.g. `arn:aws:lambda:us-east-1:4575734578134:function:api-fucntion:1
`.
Let me have a closer look tomorrow.

**Comment by isharul-roo** [comment]
Thanks @stefanfreitag for taking this up, let me know if there is anything else that I miss here apart from '/' missing in ARN.

**Comment by stefanfreitag** [comment]
Hi @isharul-roo,

I verified my hypothesis and I think we have all the details we need. To sum up:

The issue is related to the [different ARN formats](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference-arns.html) existing in AWS. For example

```plain
arn:partition:service:region:account-id:resource-id
arn:partition:service:region:account-id:resource-type/resource-id
arn:partition:service:region:account-id:resource-type:resource-id
```

All the created Terraform resources need to have an `id` and during its creation the provider crashes at `strings.Split(resourceARN, "/")[1]` .

Lambda function ARNs as well as ARNs of other resource types( e.g. SNS topics) do not contain a `/` and hence the `strings.Split(resourceARN, "/")` returns an array with one element at position 0. The code tries to access the element at position 1 and fails with the provided error message

Examples for problematic ARNs

```
arn:aws:lambda:us-east-1:123456789012:function:ProcessKinesisRecords
arn:aws:lambda:us-east-1:123456789012:function:ProcessKinesisRecords:your alias 
arn:aws:lambda:us-east-1:123456789012:function:ProcessKinesisRecords:1.0
arn:aws:sns:*:123456789012:my_corporate_topic
arn:aws:sns:us-east-1:123456789012:my_corporate_topic:02034b43-fefa-4e07-a5eb-3be56f8c54ce
arn:aws:sqs:us-east-1:123456789012:queue1 
```
 
We need to review the creation of the identifier.

**Comment by isharul-roo** [comment]
Thanks @stefanfreitag for detailed explanation, just a couple of follow up questions -

1. Anything that can be done to get rid of such problematic ARNs during creation itself?
2. Will there be any patch to support such ARNs as well?

**Comment by isharul-roo** [comment]
Oh just went over this https://github.com/hashicorp/terraform-provider-aws/issues/40504
Thanks @stefanfreitag @jar-b
