### ISSUE TITLE
[Bug]: Cannot destroy S3 bucket containing an object whose key has characters that cannot be encoded in XML

### ISSUE THREAD

**Issue by ravron** [hashicorp/terraform-provider-aws#40489]
### Terraform Core Version

1.10.1

### AWS Provider Version

5.80.0

### Affected Resource(s)

* aws_s3_bucket

### Expected Behavior

The bucket's sole object should be deleted, then the bucket should be destroyed.

### Actual Behavior

```
aws_s3_bucket.this: Destroying... [id=ravron-tf-force-destroy-test20241208220949121600000001]
╷
│ Error: emptying S3 Bucket (ravron-tf-force-destroy-test20241208220949121600000001): listing S3 bucket (ravron-tf-force-destroy-test20241208220949121600000001) object versions: operation error S3: ListObjectVersions, https response error StatusCode: 200, RequestID: 78NDPW6QX2NJJ0PB, HostID: Nys79MseP1rcdSJwiflA46aaNGeYEmtJnJ+EvcVyrwkTL9hQ7TQn5nHlJX1UlvaatEZlPBchhfznCZtmrCHlOw==, deserialization failed, failed to decode response body, XML syntax error on line 2: illegal character code U+0010
│
│
╵
```

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.80.0"
    }
  }

  required_version = "1.10.1"
}

provider "aws" {
  region = "us-west-2"
}

resource "aws_s3_bucket" "this" {
  bucket_prefix = "ravron-tf-force-destroy-test"
  force_destroy = true
}
```

### Steps to Reproduce

1. Apply above configuration.
2. Get the bucket name.
3. Run `aws s3api put-object --bucket $BUCKET_NAME --key $'foo\x10'.txt`, substituting the bucket name.
4. Run `terraform apply -destroy -auto-approve`.

### Debug Output

https://gist.github.com/ravron/521db7cc137eb019bd99f7ae850e334c

### Important Factoids

Most of the problematic code referenced here is in [s3/delete.go](https://github.com/hashicorp/terraform-provider-aws/blob/05c76fd93cb12b35ceb20956e5d9588d143bd1d5/internal/service/s3/delete.go).

The fundamental problem is that S3 object keys can contain any Unicode characters, but XML cannot encode all Unicode characters (see [section 2.2 of the XML spec](https://www.w3.org/TR/xml/#charsets) for allowed characters). For example, U+10 is a disallowed character. As a result, ListObjectVersions can return XML containing disallowed characters when listing objects whose keys themselves contain those characters, and the AWS Go SDK correctly refuses to parse the XML.

This is a well-known issue; see the references. The solution is to tell ListObjectVersions to URL-encode returned keys, which is easily done by setting `EncodingType: types.EncodingTypeUrl`, then URL-decode the keys on the client side. This works, but causes a new issue: DeleteObjectVersions will silently fail to delete any object whose key contains these invalid characters. This is because DeleteObjectVersions uses an XML request body, and Go will replace invalid characters with � (U+FFFD, the replacement character) in the request body. 

[I've created a branch in my fork for this issue](https://github.com/ravron/terraform-provider-aws/tree/ravron/force-destroy-unusual-key-names). It adds a failing test that demonstrates the problem, and modifies the `forEachObjectVersionsPage` function to use URL encoding for listing objects.

I'm interested in implementing a fix, but wanted to pause and ask for guidance first. There are two ways I can proceed:

1. Detect objects with these problematic keys and simply return an error, telling the user to delete those objects themself.
2. Detect objects with these problematic keys and fall back to deleting them one at a time, using DeleteObject. DeleteObject is of course much slower than DeleteObjects, but it can delete any object, because the object key is URL-encoded.

What do you think? Is there another option I haven't considered, but should?

### References

Here are some issues about the challenges of listing and bulk-deleting objects whose keys contain non-XML-safe characters:

* https://github.com/boto/boto3/issues/2005
* https://github.com/aws/aws-sdk-php/issues/1106
* https://github.com/aws/aws-sdk-go/issues/1914

### Would you like to implement a fix?

Yes

**Comment by ewbankkit** [comment]
@ravron Thanks for raising this issue.
We would like to be able to delete any objects from buckets so I think your _Option 2_ would be the best way forward for a resolution.

**Comment by ravron** [comment]
Got it, ok. I will work on doing that when I have an opportunity.
