### ISSUE TITLE
[Bug]: Amplify "preBuild" phase comes after "build" phase due to  yamlencode function

### ISSUE THREAD

**Issue by Diboby** [hashicorp/terraform-provider-aws#40487]
### Terraform Core Version

1.10.1

### AWS Provider Version

5.76.0

### Affected Resource(s)

- aws_amplify_app

### Expected Behavior

I expect "preBuild" phase comes before "build"

### Actual Behavior

"preBuild" phase comes after "build" when yamlencode function is used

### Terraform Configuration Files

-

### Steps to Reproduce

-

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @Diboby 👋 Thank you for taking the time to raise this! It sounds like the `yamlencode` function is doing some sorting, but that would occur at the Terraform Core leve, which would mean you'll want to open an issue in the [Terraform Core repository](https://github.com/hashicorp/terraform).

With that in mind, I'm going to close this issue. If you run into unexpected behavior in the future, please do let us know!
