### ISSUE TITLE
[New]: New service AWS Domain name access associations API GATEWAY

### ISSUE THREAD

**Issue by mhfayssal** [hashicorp/terraform-provider-aws#40491]
### Description

Currently, the AWS API Gateway resource in Terraform does not fully support the configuration and management of:

- **Domain Name Access Associations**: The ability to associate specific VPC Endpoints with custom domain names for APIs in PRIVATE mode.
- **Custom Domain Names with Private Mode**: The ability to set up and manage PRIVATE custom domain names, including the detailed configuration under the "Domain details" section of the AWS API Gateway console.

These features are essential for users who wish to implement private APIs with custom domain names accessible only through VPC Endpoints.

### Requested Resource(s) and/or Data Source(s)

aws_api_gateway_domain_name_access_association
aws_api_gateway_domain_name

### Potential Terraform Configuration

```terraform
resource "aws_api_gateway_domain_name_access_association" "example" {
  domain_name    = aws_api_gateway_domain_name.example.domain_name
  vpc_endpoint_id = aws_vpc_endpoint.example.id
}

resource "aws_api_gateway_domain_name" "example" {
  domain_name = "private-api.example.com"
  regional_certificate_arn = aws_acm_certificate.example.arn
  security_policy = "TLS_1_2"

  endpoint_configuration {
    types = ["PRIVATE"]
  }
}
```

### References

AWS API Gateway Documentation: [Custom Domain Names](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html)
AWS API Gateway Private Endpoints: [Private APIs in API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-apis.html)

### Would you like to implement a fix?

None

**Comment by ewbankkit** [comment]
@mhfayssal Thanks for raising this issue.
It has already been noticed in #40274. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
