### ISSUE TITLE
[Enhancement]: Cross region interface endpoint support  supplement #40346

### ISSUE THREAD

**Issue by dexterchan** [hashicorp/terraform-provider-aws#40522]
### Description

From  #40346, we see the change in "aws_vpc_endpoint_service" in 5.80.0 

However, we also require "aws_vpc_endpoint" to support cross region private link service.
By now, we received 400 when connect to a cross region service generated from 'aws_vpc_endpoint_service' 

IN AWS portal, we need to provide
- Enable Cross Region endpoint
- PrivateLink service region
when creating the interface endpoint from the privatelink service in #40346 "aws_vpc_endpoint_service"

### Affected Resource(s) and/or Data Source(s)

aws_vpc_endpoint

### References

https://github.com/hashicorp/terraform-provider-aws/pull/40346

### Would you like to implement a fix?

None

**Comment by drewtul** [comment]
This is being worked on under #40438
