### ISSUE TITLE
[Bug]: SES configuration set required deliveryOptions.maxDeliverySeconds

### ISSUE THREAD

**Issue by quentin9696** [hashicorp/terraform-provider-aws#40591]
### Terraform Core Version

1.10.2

### AWS Provider Version

5.81.0

### Affected Resource(s)

* aws_sesv2_configuration_set

### Expected Behavior

No error when setting delivery options with default values

### Actual Behavior

error mentioning the max delivery seconds must be greater or equal to 300

### Relevant Error/Panic Output Snippet

```shell
│ Error: creating AWS SESv2 (Simple Email V2) Configuration Set (issue): operation error SESv2: CreateConfigurationSet, https response error StatusCode: 400, RequestID: 97bc8e31-9235-47da-85b4-4d36c6cd6243, BadRequestException: 1 validation error detected: Value at 'deliveryOptions.maxDeliverySeconds' failed to satisfy constraint: Member must have value greater than or equal to 300
│ 
│   with aws_sesv2_configuration_set.issue,
│   on main.tf line 5, in resource "aws_sesv2_configuration_set" "issue":
│    5: resource "aws_sesv2_configuration_set" "issue" {
│
```

### Terraform Configuration Files

``` hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_sesv2_configuration_set" "issue" {
  configuration_set_name = "issue"

  delivery_options {
    tls_policy           = "REQUIRE"
  }
}
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Debug Output

The issue is very simple to reproduce

### Important Factoids

The documentation mention the argument `max_delivery_seconds` can be optional 
> if specified, the value must greater than or equal to 300 seconds (5 minutes) and less than or equal to 50400 seconds (840 minutes).

If this argument is required, it would be nice to mention in the documentation. If not, fix the issue in the provider

This option have been added in the `5.81.0` version

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_configuration_set#max_delivery_seconds-1

### Would you like to implement a fix?

No

**Comment by stefanfreitag** [comment]
Hi @quentin9696,
thanks for taking your time for reporting the issue.
I ran your example code with additional logging and when creating the resource the information below is forwarded to the API

```json
{"ConfigurationSetName":"issue","DeliveryOptions":{"MaxDeliverySeconds":0,"TlsPolicy":"REQUIRE"}}
```

As you already mentioned`"MaxDeliverySeconds":0` is causing the issue as a minimum value of 300 is expected.
