### ISSUE TITLE
[Docs]: Resource: aws_msk_replicator typo in `topic_configuration_name`

### ISSUE THREAD

**Issue by pimielowski-equinix** [hashicorp/terraform-provider-aws#40596]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_replicator

### Description

In `topic_configuration_name` is a typo, it should be like in a code -> `topic_name_configuration` it provide confusion :) 

### Would you like to implement a fix?

No

**Comment by stefanfreitag** [comment]
Hi @pimielowski-equinix!

Thanks for bringing this to our attention. 
I had a look into the source code and you are right, the correct name is `topic_name_configuration`. 
Let me update the documentation accordingly.
