### ISSUE TITLE
[Enhancement]: Support for Modifiable mTLS/TLS header names in ELB

### ISSUE THREAD

**Issue by akielbas** [hashicorp/terraform-provider-aws#40598]
### Description

AWS recently introduced [modifiable header names in ELB](https://aws.amazon.com/about-aws/whats-new/2024/11/aws-application-load-balancer-header-modification-enhanced-traffic-control-security/).

It would be great to be able to set this via terraform.

### Affected Resource(s) and/or Data Source(s)

* aws_lb_listener

### References

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/header-modification.html
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/enable-header-modification.html

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
@akielbas Thanks for raising this issue.
It has already been noticed in #40269. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
