### ISSUE TITLE
[Docs]: aws_lb_trust_store example contains mutual_authentication argument instead of block

### ISSUE THREAD

**Issue by fruechel-canva** [hashicorp/terraform-provider-aws#40605]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_trust_store

### Description

The first example on https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_trust_store contains this snippet:

```
  mutual_authentication = {
    mode            = "verify"
    trust_store_arn = aws_lb_trust_store.test.arn
  }
```

However, when trying to run the example, it fails:
```
│ Error: Unsupported argument
│
│   on main.tf line 255, in resource "aws_lb_listener" "mtls_ingress":
│  255:   mutual_authentication = {
│
│ An argument named "mutual_authentication" is not expected here. Did you mean to define a block of type
│ "mutual_authentication"?
```

The `=` should not be there, removing it fixes the issue.

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Good evening @fruechel-canva,
thanks for bringing this to our attention!

I had a look into the example you mentioned and you are right, the "=" is not correct. 
Let me update the documenation.
