### ISSUE TITLE
[Enhancement]: Retain the id attribute of aws_api_gateway_account, to allow for dependency on its existence.

### ISSUE THREAD

**Issue by jufemaiz** [hashicorp/terraform-provider-aws#40631]
### Description

Retain the `id` attribute of `aws_api_gateway_account`, to allow for dependency on its existence.

Cloudwatch logging of API Gateways cannot be achieved without this, but without the `id` attribute we cannot cleanly indicate a dependency.

### Affected Resource(s) and/or Data Source(s)

* aws_api_gateway_account

### References

https://github.com/hashicorp/terraform-provider-aws/blame/16fd0dcca46081837a863997e5bd5cca27dc456b/internal/service/apigateway/account.go#L68-L74

### Would you like to implement a fix?

Yes. Happy to.

**Comment by gdavison** [comment]
The [`depends_on` meta-argument](https://developer.hashicorp.com/terraform/language/meta-arguments/depends_on) can be used to indicate the dependency.

The existence of the `id` attribute on this resource type is a historical remnant of Terraform pre-0.12, and no longer needed or recommended for current versions of Terraform.

**Comment by jufemaiz** [comment]
@gdavison not when the dependency is on a module. Which is a common strategy when looking at a global as this particular resource is. 

If I apply a depends_on block to the module, all data elements within are considered to be refreshed. This has unintended consequences - for example, using a AWS managed KMS key, via a data element, for encryption is considered tainted in the plan as it depends on something else. Anywhere that is used considers it changed. With RDS this will indicate in the plan that the database will be destroyed and recreated. 

Depends_on at a module level is obviously not a recommended strategy to take, yet an API gateway that wants to have login does indeed depend on a global being set … that rightfully should not be set via the module itself. This leaves passing in an attribute known after create as the logical strategy (in my case, adding the is as a tag to the api gateway resource configuring logging) to ensure it exists before adding logging - otherwise it fails. 

Respectfully I request this be reconsidered, rather than so eagerly closed.
