### ISSUE TITLE
[Bug]: SID validation at plan time is invalidly applied to ALL policies

### ISSUE THREAD

**Issue by JacobAllenAbkes** [hashicorp/terraform-provider-aws#40639]
### Terraform Core Version

1.7

### AWS Provider Version

5.82

### Affected Resource(s)

aws_iam_policy_document

### Expected Behavior

We should not blanket apply plan time validation against the SID because each service may have it's own policies on allowed characters. This is a breaking change.

### Actual Behavior

We blanket apply the plan time validation against the SID.

### Terraform Configuration Files

```terraform
resource "aws_kms_key" "name" {
  description         = "something"
  policy              = data.aws_iam_policy_document.name.json
}


data "aws_iam_policy_document" "name" {
  version                 = "2012-10-17"

  statement {
    sid    = "Allow spaces"
    effect = "Allow"
    actions = [
      "kms:Decrypt"
    ]
    resources = ["*"]
  }
}
```

### Steps to Reproduce

Create an IAM policy document resource, have the SID include spaces

Attach the policy as a KMS policy

### Debug Output

│   with aws_iam_policy_document.name,
│   on file line X, in data "aws_iam_policy_document" "name":
│   line#:     sid    = "Allow spaces"

### References

https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md

https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-overview.html

### Would you like to implement a fix?

No

**Comment by faleon** [comment]
Who let the intern push to production?

**Comment by asvinours** [comment]
```
  │ Error: invalid value for statement.0.sid (must only include alphanumeric characters)
  │ 
  │   with data.aws_iam_policy_document.elb_access_logs_delivery,
  │   on load_balancer.tf line 70, in data "aws_iam_policy_document" "elb_access_logs_delivery":
  │   70:     sid       = "ELBNewerRegions"
```

Not too sure why this is considered invalid :thinking:

**Comment by faleon** [comment]
@asvinours react with a thumbs up to OP please to help get this escalated - https://github.com/hashicorp/terraform-provider-aws/issues/40639#issue-2751171576

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/40562.

**Comment by tobiasbueschel** [comment]
We've encountered the same issue just now, which blocked our deployments as we have some older `SIDs` with incorrect names.

**For now, we're using the following workaround, hope this helps anyone who might face the same issue:**

```tf
terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source = "hashicorp/aws"
      # TODO: this is temporary to fix the following error, we should eventually fix our SID to make them alphanumeric 
      # https://github.com/hashicorp/terraform-provider-aws/issues/40639
      # https://github.com/hashicorp/terraform-provider-aws/pull/40562
      version = "5.81.0"
    }
  }
}
```

**Comment by DrStrangepork** [comment]
AWS Key Management Service documentation, Creating a key policy, [Key policy format](https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-overview.html#key-policy-format):

> A key policy document must conform to the following rules:
> - Up to 32 kilobytes (32,768 bytes)
> - The Sid element in a key policy statement can include spaces. (Spaces are prohibited in the Sid element of an IAM policy document.)

KMS policy Sids _can_ include spaces, and there are dozens of examples of Sids with spaces throughout AWS documentation.

**Comment by JacobAllenAbkes** [comment]
> We've encountered the same issue just now, which blocked our deployments as we have some older `SIDs` with non-alphanumeric names.
> 
> **For now, we're using the following workaround, hope this helps anyone who might face the same issue:**
> 
> ```hcl
> terraform {
>   required_version = ">= 1.0"
> 
>   required_providers {
>     aws = {
>       source = "hashicorp/aws"
>       # TODO: this is temporary to fix the following error, we should eventually fix our SID to make them alphanumeric 
>       # https://github.com/hashicorp/terraform-provider-aws/issues/40639
>       # https://github.com/hashicorp/terraform-provider-aws/pull/40562
>       version = "5.81.0"
>     }
>   }
> }
> ```

This is a temporary workaround for active releases, this issue will continue to affect clients which deploy tagged old releases with `~>5.x`.

**Comment by YakDriver** [comment]
My apologies for the inconvenience with this. We used the regex AWS provides for the SID but that does not seem to match with the reality of usage. We will work on a fix for this right away!

**Comment by allenschein** [comment]
this is terrible! I was just trying to deploy to prod a quick hot fix before the holidays, and now I literally have to change all our SIDs with a hyphen in it, which is how we have done the naming convention in our all of our iac for yearsssss... what was supposed to be a smooth deploy this morning is now literally a renaming nightmare!!!

**Comment by allenschein** [comment]
I already started renaming stuff, only to realize how many more I have to change, and the stress that this causes on what was supposed to be a chill morning before the holidays... should I just wait for the provider to get updated? My team is waiting to hear back on this hot fix going out...

**Comment by JacobAllenAbkes** [comment]
> I already started renaming stuff, only to realize how many more I have to change, and the stress that this causes on what was supposed to be a chill morning before the holidays... should I just wait for the provider to get updated? My team is waiting to hear back on this hot fix going out...

Just set the TF version to exactly 5.81.0

**Comment by allenschein** [comment]
thanks, that makes sense... sorry for the vent, this was so unexpected

**Comment by YakDriver** [comment]
We used the regex that AWS provides for valid _IAM_ Sids but, obviously, we're seeing how much this is used outside of IAM. Again our apologies for the problems this is causing! We will have a fix soon.
