### ISSUE TITLE
[Enhancement]: support EKS node auto repair config on aws_eks_node_group

### ISSUE THREAD

**Issue by mmerickel** [hashicorp/terraform-provider-aws#40641]
### Description

AWS just released a new addon and node group config.

The `CreateNodeGroup` API has a new `nodeRepairConfig` feature that should get exposed to the `aws_eks_node_group` resource.

### Affected Resource(s) and/or Data Source(s)

- aws_eks_node_group

### Potential Terraform Configuration

```terraform
resource "aws_eks_node_group" {
  # ... snip
  node_repair_config {
    enabled = true
  }
}
```

### References

- https://aws.amazon.com/about-aws/whats-new/2024/12/node-health-monitoring-auto-repair-amazon-eks/
- https://docs.aws.amazon.com/eks/latest/userguide/node-health.html
- https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html#AmazonEKS-CreateNodegroup-request-nodeRepairConfig

### Would you like to implement a fix?

None

**Comment by hjoshi123** [comment]
@mmerickel can I pick this enhancement and work on it?

**Comment by mmerickel** [comment]
@hjoshi123 please do!

**Comment by hjoshi123** [comment]
@mmerickel just had a query.. can the issue be assigned to me or is that done once the PR is raised?

**Comment by mmerickel** [comment]
@hjoshi123 I think only members have that power.

**Comment by mmerickel** [comment]
Thanks @hjoshi123!
