### ISSUE TITLE
[Docs]: AWS MSK Replicator | topic_replication argument

### ISSUE THREAD

**Issue by Kartheeko07** [hashicorp/terraform-provider-aws#40648]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_replicator#topic_replication-argument-reference

### Description

The documentation says the argument to be used is [topic_configuration_name](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/msk_replicator#topic_configuration_name-1)

But actually that is a typo and using that argument doesn't work and terraform provider doesn't detect that, I checked the backend pull request for this feature request and found that the correct name to be used is 
`topic_name_configuration` vs topic_configuration_name

Request to please update the documentation with the correct argument name.

### Would you like to implement a fix?

Yes

**Comment by Kartheeko07** [comment]
<img width="655" alt="Screenshot 2024-12-19 at 3 06 42 PM" src="https://github.com/user-attachments/assets/00b556cd-dfc5-4cc3-9f6c-6d4f7f74a5ae" />

**Comment by stefanfreitag** [comment]
Good evening @Kartheeko07,

thank you for reporting the issue in the current version of the documentation!

We already have an existing [ticket](https://github.com/hashicorp/terraform-provider-aws/issues/40596) reporting the same issue and also a [pull request](https://github.com/hashicorp/terraform-provider-aws/pull/40646) addressing it. 

It should be resolved with the next release of the AWS provider (v5.83.0).

**Comment by ewbankkit** [comment]
@Kartheeko07 Thanks for raising this issue.
It has already been noticed in #40596. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
