### ISSUE TITLE
[Bug]: Data source for an AWS ALB listener with mTLS configured was working correctly in 5.81.0, now fails in 5.82.x

### ISSUE THREAD

**Issue by rcousens** [hashicorp/terraform-provider-aws#40651]
### Terraform Core Version

1.80.0

### AWS Provider Version

5.82.1

### Affected Resource(s)

data.aws_lb_listener

### Expected Behavior

Should have read the data source without an error.

### Actual Behavior

Instead:
```
╷
│ Error: setting mutual_authentication: Invalid address to set: []string{"mutual_authentication", "0", "advertise_trust_store_ca_names"}
│ 
│   with module.xxx.data.aws_lb_listener.mtls_listener,
│   on .terraform/modules/xxx/data.tf line 11, in data "aws_lb_listener" "mtls_listener":
│   11: data "aws_lb_listener" "mtls_listener" {
│ 
╵
```

### Terraform Configuration Files

```
data "aws_lb_listener" "mtls_listener" {
  arn      = <a valid ALB listener arn with mTLS verify enabled>
}
```

### Steps to Reproduce

Try to read a data source for an ALB listener.

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment]
Relates https://github.com/hashicorp/terraform-provider-aws/pull/40550.
