### ISSUE TITLE
[Docs]: Error in Terraform example for aws_ssoadmin_managed_policy_attachment

### ISSUE THREAD

**Issue by DaveElston** [hashicorp/terraform-provider-aws#40720]
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssoadmin_managed_policy_attachment#with-account-assignment

### Description

At the bottom of the code example, the reference for the `depends_on` example is incorrect

`depends_on = [aws_ssoadmin_account_assignment.example]`

This resource is not called `example` it's `account_assignment`. Therefore it should be

`depends_on = [aws_ssoadmin_account_assignment.account_assignment]`

Either that or the resource should be re-named to `example` to be consistent with the example

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment]
Hi @DaveElston,

thanks for reporting the issue in the resource documentation!
I think you are right, a simple `terraform plan` fails

```shell
❯ terraform plan
╷
│ Error: Reference to undeclared resource
│ 
│   on main.tf line 29, in resource "aws_ssoadmin_managed_policy_attachment" "example":
│   29:   depends_on = [aws_ssoadmin_account_assignment.example]
│ 
│ A managed resource "aws_ssoadmin_account_assignment" "example" has not been declared in the root module.
╵
```

Let me prepare an update.
