### ISSUE TITLE
Feature Request: Support CloudFront Field Level Encryption Configurations

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#4097]
Recently the AWS SDK for Go has added support for managing CloudFront field level encryption configurations as first announced in: https://aws.amazon.com/about-aws/whats-new/2017/12/introducing-field-level-encryption-on-amazon-cloudfront/

Please vote on this issue by adding a :+1: reaction to the original issue to help prioritize interest. If you're interested in implementing this feature request, please comment below.

Prerequisite: aws-sdk-go v.1.13.26 (already merged)

### Terraform Version

terraform 0.10+

### New Resource(s)

- `aws_cloudfront_field_level_encryption_config`

### Terraform Configuration Files

```hcl
# Example implementation, may change when developed
resource "aws_cloudfront_field_level_encryption_config" "example" {
  comment = "" # optional
  content_type_profile_config {
    content_type_profile {
      content_type = "" # required
      format = "" # required
      profile_id = "" # optional
    }
    forward_when_content_type_is_unknown = true # required
  }
  query_arg_profile_config {
  	forward_when_query_arg_profile_is_unknown = true # required
  	query_arg_profile {
  	  profile_id = "" # required
  	  query_arg = "" # required
  	}
  }
}
```

### Expected Behavior

Resource creates, updates, and deletes CloudFront field level encryption configurations.

### Actual Behavior

New feature.

### References

* https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/field-level-encryption.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/cloudfront/#CloudFront.CreateFieldLevelEncryptionConfig

**Comment by bflad** [comment]
After this resource is created, we need to circle back to acceptance testing it in the `aws_cloudfront_distribution` resource: #4101

**Comment by DrFaust92** [comment]
I have this in a branch, i'll open a PR after #12509 is addressed as its dependent on it.
