### ISSUE TITLE
[Feature Request]Plan time validation for aws_elasticache_cluster node type when to scale down

### ISSUE THREAD

**Issue by hanks** [hashicorp/terraform-provider-aws#4166]
Hi,

I scaled down the elasticache redis node type from, like `cache.m3.xlarge` to `cache.m3.large`, and
the plan result was ok, but when applied,  it threw a  400 error. This is an expected result, because AWS can not support scale down for the elasticache redis now. But I think it may be better to throw an error at the plan phase.

### Terraform Version
Terraform v0.10.7

### Affected Resource(s)
- aws_elasticache_cluster

### Expected Behavior
Because we can not scale down elasticache redis node type now, maybe it will
be better to throw a error at the plan phase.

### Actual Behavior
Right now, the plan phase is ok, it will be shown as in-place changes, but when to apply,
it will throw a 400 error

I aslo check the source code here, https://github.com/terraform-providers/terraform-provider-aws/blob/35907ec8333ccc8887a3fcffc566cba25207b6ba/aws/resource_aws_elasticache_cluster.go#L256

```go
func(diff *schema.ResourceDiff, v interface{}) error {
	// Plan time validation for engine_version
	// InvalidParameterCombination: Cannot modify memcached from 1.4.33 to 1.4.24
	// InvalidParameterCombination: Cannot modify redis from 3.2.6 to 3.2.4
	if diff.Id() == "" || !diff.HasChange("engine_version") {
		return nil
	}
	o, n := diff.GetChange("engine_version")
	oVersion, err := gversion.NewVersion(o.(string))
	if err != nil {
		return err
	}
	nVersion, err := gversion.NewVersion(n.(string))
	if err != nil {
		return err
	}
	if nVersion.GreaterThan(oVersion) {
		return nil
	}
	return diff.ForceNew("engine_version")
},
```

seems that we can add a node type check here like the `engine version check`, but I searched for a while, there is no way to get the memory number from the AWS API, so it is hard to compare node type only by the node string like `cache.m3.xlarge`, `cache.t2.small`, also it will be hard to maintain the node type table manually.

Any suggestion for this issue? Thank you for your time.

**Comment by emre141** [comment]
Hi,
We have same problem to change instance type from new generation to old generation node_type: "cache.t3.small" => "cache.m3.medium" but the what does the  rename resource means ? It will attempt to create new redis cluster by given new name ? What was the remaining data in old cache node ?

**Comment by lgg42** [comment]
> Hi,
> We have same problem to change instance type from new generation to old generation node_type: "cache.t3.small" => "cache.m3.medium" but the what does the rename resource means ? It will attempt to create new redis cluster by given new name ? What was the remaining data in old cache node ?

Hi, I'm in the exactly same position, did you ever found out what happened?
