### ISSUE TITLE
aws_ssm_patch_baseline operating_system CENTOS missing

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#4170]
_This issue was originally opened by @bratdim as hashicorp/terraform#17836. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
```
./terraform version
Terraform v0.11.7
+ provider.aws v1.14.0
```

### Terraform Configuration Files
```
resource "aws_ssm_patch_baseline" "patch-baseline-centos" {
  name  = "CentOS_Linux"
  operating_system = "CENTOS"
  description = "CentOS Linux baseline"
  approved_patches_compliance_level = "CRITICAL"

  approval_rule = {
    approve_after_days = 7
    compliance_level = "CRITICAL"
    patch_filter = {
      key = "SEVERITY"
      values = ["Critical"]
    }
  }
...
}
```

### Debug Output
```
2018/04/11 09:58:16 [TRACE] root: eval: *terraform.EvalValidateResource
2018/04/11 09:58:16 [ERROR] root: eval: *terraform.EvalSequence, err: Warnings: []. Errors: [expected operating_system to be one of [WINDOWS AMAZON_LINUX UBUNTU REDHAT_ENTERPRISE_LINUX], got CENTOS]
2018/04/11 09:58:16 [TRACE] [walkValidate] Exiting eval tree: aws_ssm_patch_baseline.patch-baseline-centos
```

### Expected Behavior
Terraform should create patch baseline for Centos (like it does for Amazon linux, Suse or Windows)

### Actual Behavior
Terrafrom fails with error:
```
./terraform plan

Error: aws_ssm_patch_baseline.patch-baseline-centos: expected operating_system to be one of [WINDOWS AMAZON_LINUX UBUNTU REDHAT_ENTERPRISE_LINUX], got CENTOS
```

### Steps to Reproduce
1. `terraform init`
2.  add mentioned `aws_ssm_patch_baseline` to main.tf 
3. `terraform plan`

### References
AWS documentation regarding it:
https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetDefaultPatchBaseline.html#API_GetDefaultPatchBaseline_ResponseElements

**Comment by bflad** [comment]
This has been released in [version 1.16.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1160-april-25-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
