### ISSUE TITLE
Integrate Provider Context For Cancelling Requests

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#4177]
## Description

In order to properly cancel a Terraform command, we need to reference the provider context to any AWS Go SDK calls and separately any Terraform Plugin SDK retry loops. In Terraform Plugin SDK version 2, the provider context is available via new CRUD function signatures (e.g. `CreateContext`) (#15090) which will be the starting point for any implementation.

Then when its available to the resources:

* Decide if `resource.RetryContext()`/`WaitForStateContext()` should be done as part of this effort or not. Likely separately as it can have its own set of linters.
* Passthrough the provider `context.Context` to any necessary downstream functions (if not a resource function) that call the AWS Go SDK (and `resource.Retry()`/`StateChangeConf` if necessary) -- this also includes generating [context-aware `keyvaluetags` functionality](https://github.com/hashicorp/terraform-provider-aws/issues/16346)
* If AWS Go SDK is still version 1 for all resources, switch the AWS SDK calls to their `WithContext` variant and pass through the available resource `context.Context` to them
* If AWS Go SDK is version 2 for new resources, document the appropriate code steps

**Comment by bflad** [comment]
Terraform Plugin SDK version 2 introduces CRUD functions (e.g. `CreateContext`) with the provider context automatically available (#15090) -- will adjust the description of this issue. Depending on the timing of that work and the GA release of AWS Go SDK version 2, the implementation details may change further.

**Comment by bflad** [comment]
One potential risk to threading the resource context through to all functionality is ensuring that the default resource timeouts (20 minutes) do not interfere with the provider-level `max_retries` (AWS Go SDK `MaxRetries`) setting (which defaults to 25 and ~60 minutes). We may not have a choice if it does, but it will be helpful to understand and document the behavior before migrating code to the new goodness, potentially in a major release.

**Comment by bflad** [comment]
The risk mentioned above is now mitigated with `*WithoutTimeout` functionality -- the Terraform Plugin SDK v2 function signature migration can be tracked in https://github.com/hashicorp/terraform-provider-aws/issues/15090

Will add [internal/keyvaluetags: Generate Context-Aware Functions](https://github.com/hashicorp/terraform-provider-aws/issues/16346) to the description.

**Comment by ewbankkit** [comment]
Closed by https://github.com/hashicorp/terraform-provider-aws/pull/29005.
