### ISSUE TITLE
Allow Disabling sending status emails for SES

### ISSUE THREAD

**Issue by dstufft** [hashicorp/terraform-provider-aws#4182]
With ``aws_ses_identity_notification_topic`` we can set the default SNS topics for delivery/bounce/complaints for a SES identify, however we cannot actually turn off *also* sending emails in addition to those SNS topic notifications. It would be great to be able to do that.

The relevant API that enables this is [SetIdentityFeedbackForwardingEnabled](https://docs.aws.amazon.com/ses/latest/APIReference/API_SetIdentityFeedbackForwardingEnabled.html).

**Comment by finferflu** [comment]
Are there any updates on this? This is quite an important requirement for my team. Thanks!

**Comment by yuonoda** [comment]
Hey, I started working on this issue with this PR.
#16891
