### ISSUE TITLE
Cognito User Pool standard attribute handling changed in 1.13

### ISSUE THREAD

**Issue by jyrkiput** [hashicorp/terraform-provider-aws#4228]
I want to set standard attribute as required, and 1.13 forward handling of this changed.

### Terraform Version
Terraform v0.11.7
+ provider.aws v1.14.1

### Affected Resource(s)
aws_cognito_user_pool

### Terraform Configuration Files
```hcl
provider "aws" {
  version = "1.14.1"
}

resource "aws_cognito_user_pool" "pool" {
  name = "cognito-terraform-bug"

  schema {
    attribute_data_type = "String"
    name                = "phone_number"
    required            = true
  }
}
```

### Debug Output
https://gist.github.com/jyrkiput/4b92d037fcbbb327abb8ddbfeaa5f49c

### Expected Behavior
With AWS provider 1.12, you can apply this configuration multiple times without destroying user pool.

### Actual Behavior
Terraform things that schema has changed as the `string_attribute_constraints` is not present

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform apply`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-3891 has comments about similar issue
- GH-4227 is similar but with custom attribute

### Workaround

Define `string_attribute_constraints` exactly like it seems to be (values found from plan output).
```
provider "aws" {
  version = "1.14.1"
}

resource "aws_cognito_user_pool" "pool" {
  name = "cognito-terraform-bug"

  schema {
    attribute_data_type = "String"
    name                = "phone_number"
    required            = true

    string_attribute_constraints {
      min_length = 0
      max_length = 2048
    }
  }
}
```

**Comment by Puneeth-n** [comment]
@jyrkiput So if I understood you right, you want to set the `phone_number` as **required** and earlier it was **not required**?

**Comment by jyrkiput** [comment]
@Puneeth-n the phone_number has been **required** from the beginning. With 1.12 you can create this setup and apply it again, with 1.13+ `terraform apply` start to replace whole user pool.

What I did was:
1. created a new user pool with that configuration with `terraform apply`
2. ran `terraform apply` again and user pool got replaced

Actually minimal configuration is following

```
resource "aws_cognito_user_pool" "pool" {
  name = "cognito-terraform-bug"

  schema {
    attribute_data_type = "String"
    name                = "phone_number"
  }
}
```
This will cause the user pool to be recreated on every `terraform apply`, as the "phone_number" attribute changes.

I guess that this might really be as expected, as the schema does not really represent what that phone_number -attribute really is.

**Comment by Puneeth-n** [comment]
I could reproduce this bug with the following minimal configuration:
```hcl
variable "region" {
  default = "us-east-1"
}

provider "aws" {
  version               = "1.14.1"
  region                = "${var.region}"
  forbidden_account_ids = ["940226765273"]
}

resource "aws_cognito_user_pool" "pool" {
  name = "cognito-terraform-bug"

  schema {
    attribute_data_type = "String"
    name                = "phone_number"

  }
}
```

My best guess is, it is coming from https://github.com/terraform-providers/terraform-provider-aws/blob/74a51650b29c53a389a9d034c2ece43d3fb279d5/aws/structure.go#L2750-L2756

**Comment by bflad** [comment]
In 1.13.0 (#3789 specifically), the `aws_cognito_user_pool` resource was updated to detect `schema` drift from the API. The initial implementation of this detection was able to wholesale detect changes with schema attributes, but not fully ignore Terraform configurations missing parts of a schema configuration like `string_attribute_constraints`. 

The logic is here:

https://github.com/terraform-providers/terraform-provider-aws/blob/74a51650b29c53a389a9d034c2ece43d3fb279d5/aws/structure.go#L3005-L3018

The workaround is to fully specify all the standard schema attribute information.

**Comment by loivis** [comment]
Hit the same issue a few days ago. Just workaround it but didn't get time to look into it.

**Comment by smastrorocco** [comment]
Hitting the same issue Terraform v0.11.7 AWS provider v1.16.0

**Comment by haidaraM** [comment]
Same issue with `Terraform v0.11.8` and `provider.aws v1.39.0`. Terraform always tries to recreate the user pool even when nothing changed. Example (run terraform apply twice):

```hcl
resource "aws_cognito_user_pool" "my_user_pool" {
  name                = "${var.prefix}-tuto-cognito"
  username_attributes = ["email"]

  schema {
    attribute_data_type = "String"
    name                = "name"
  }
}
```

**Comment by huihe** [comment]
I got the same issue with `Terraform v0.11.11` and `provider.aws v1.52.0`.  New custom attribute results re-creating the user pool.

**Comment by codyseibert** [comment]
Same issue with `Terraform v0.11.11` and `provider.aws v1.58.0`.

**Comment by sa-shukla** [comment]
I am also running into same issue with Terraform v0.11.8 and provider.aws v2.x . Is there a proper workaround or fix available in later versions?
