### ISSUE TITLE
Feature: Add support for launch_template in aws_instance resource

### ISSUE THREAD

**Issue by gordonbondon** [hashicorp/terraform-provider-aws#4264]
Please add support to provide Launch Template on instance creation. This feature is already available in go sdk https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#RunInstancesInput and `aws_launch_template` resource was recently implemented #2927

**Comment by ohaiwalt** [comment]
Really interested in this, as it would solve a number of issues for us. What's the current state?

**Comment by majdhamdan** [comment]
Hey. Any updates?

**Comment by julian-alarcon** [comment]
I also have this question, any updates on this? PR seems to be OK.

**Comment by wandrew26** [comment]
I would be happy to see this in the next release! ⚠️

**Comment by dtserekhman-starz** [comment]
Yes, really waiting for this feature. Thank you.

**Comment by sepulvedablanco** [comment]
When will be available this feature?

**Comment by dvir-frey** [comment]
any news on it??

**Comment by dvir-frey** [comment]
https://www.terraform.io/docs/providers/aws/r/spot_fleet_request.html look here
