### ISSUE TITLE
aws_spot_fleet_request maps subnet_id to the wrong launch_specification parameter

### ISSUE THREAD

**Issue by WheresWardy** [hashicorp/terraform-provider-aws#4265]
I'm trying to create an `aws_spot_fleet_request` resource in Terraform where I'm using the `diversified` allocation strategy to allow AWS to create spot instances in several subnets which I specify.

In Terraform, launch_specification uses `aws_instance` parameters to specify the configuration of the spot instances to be created within the fleet request, similar to how it's supported in the API (under **SubnetId** at https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SpotFleetLaunchSpecification.html). However, if I pass multiple comma-separated subnet IDs to the `subnet_id` parameter, the spot fleet isn't created (and the creation actually hangs on a waiting loop) because the AWS API is returning errors.

This is because instead of passing the subnet IDs to the `SubnetId` API parameter, Terraform is creating network interfaces with the comma-separated subnet IDs, which is invalid syntax. Thus, the following (truncated) config:

```hcl
launch_specification = {
  ...
  subnet_id              = "subnet-xxx0, subnet-xxx1, subnet-xxx2"
  vpc_security_group_ids = ["sg-xxx0", "sg-xxx1"]
  ...
}
```

creates the following (truncated) request config (using `TF_LOG=debug`):

```hcl
...
NetworkInterfaces: [{
    AssociatePublicIpAddress: true,
    DeleteOnTermination: true,
    DeviceIndex: 0,
    Groups: ["sg-xxx0","sg-xxx1"],
    SubnetId: "subnet-xxx0, subnet-xxx1, subnet-xxx2"
  }],
Placement: {
  AvailabilityZone: "",
  Tenancy: ""
},
SpotPrice: "0.056625",
SubnetId: "",
...
```

The result of this is that currently, you can't create diversified, multi-subnet spot fleet requests as the API supports.

### Terraform Version
```
Terraform v0.11.2
+ provider.aws v1.15.0
+ provider.template v1.0.0
```

**Comment by saravanan30erd** [comment]
@WheresWardy Looks like Terraform does not support the functionality where multiple subnet_id or availability_zone parameters can be specified in the same launch configuration block. If you want to specify multiple values, then separate launch configuration blocks should be used.
https://www.terraform.io/docs/providers/aws/r/spot_fleet_request.html (NOTE)
@bflad can we add any plan time validation for this?

**Comment by WheresWardy** [comment]
Yeah, I guess this is more of a feature request than a bug, I'm not sure where the line is drawn in terms of which one this is considered given that API supports something that Terraform doesn't.
