### ISSUE TITLE
aws_api_gateway_rest_api doesn't seem to handle failures

### ISSUE THREAD

**Issue by saxonww** [hashicorp/terraform-provider-aws#4273]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

Terraform 0.11.7, provider 1.15

### Affected Resource(s)

- aws_api_gateway_rest_api

### Terraform Configuration Files

Partial config:

```hcl
# Assume the following results in a valid swagger.json importable
# through the AWS console
data "template_file" "swagger" {
  template = "${file("${path.module}/swagger.json")}"

  vars {
    path_prefix     = "${local.path_prefix}"
    base_path       = "/${terraform.workspace}"
    schemes         = "https"
    integration_uri = "${local.integration_uri}"
    connection_id   = "${aws_api_gateway_vpc_link.vpc_link.id}"
  }
}

resource "aws_api_gateway_rest_api" "root" {
  name               = "Example"
  description        = "Example API"
  binary_media_types = ["*/*"]
  body               = "${data.template_file.swagger.rendered}"

  depends_on = [
    "aws_api_gateway_vpc_link.vpc_link",
  ]
}

resource "aws_api_gateway_vpc_link" "vpc_link" {
  name        = "Example link"
  description = "VPC link to internal lb for Example"
  target_arns = ["${aws_elastic_beanstalk_environment.environment.load_balancers}"]

  # Assume a valid, working configuration for beanstalk
  depends_on = [
    "aws_elastic_beanstalk_environment.environment",
  ]
}
```

### Debug Output

I can't provide full debug output. Here is a relevant excerpt (I think):

https://gist.github.com/saxonww/440da8c1945fe8962a1982e729c45db4

### Expected Behavior

Deployment fails as the call to apigateway/UpdateRestApi returns a 500 error, or at least has a reasonable number of retries before it gives up. We do not have to force-interrupt the deployment.

### Actual Behavior

It looks like PutRestApi succeeds, but then this is calling UpdateRestApi for some reason and that fails with a 500 error. Instead of aborting, Terraform continues to call UpdateRestApi; we've let it go for ~2 hours and it doesn't finish. Of course if you end the deployment process you may have to run force-unlock to unlock state.

Our swagger.json content _does_ produce warnings on import, which we haven't been seeing because those don't get displayed in the Terraform output or anything like that. I am going to file a separate issue about this and hopefully send a PR.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

This isn't happening with all of our APIs, only this one, and we have not discovered what about it is wrong. A rendered swagger.json imports OK (with warnings) through the console as well as the CLI though.

**Comment by saxonww** [comment]
We've done some more investigation on this and the actual failure is coming in trying to update the aws_api_gateway_deployment; at least, if we destroy everything and re-create it gets hung up there. Also, calling update-rest-api from the command line fails with 500 errors as well. It's still not clear what's causing this to happen because the api just doesn't return anything actionable.

It has a maximum retry count of 4, though, and fails quickly.

**Comment by cmoreira-daitan** [comment]
I might be having a similar issue. Deploying API gateway works, but updating fails.
It keeps failing even after complete destruction.

It works again if I change the `name` attribute of `aws_api_gateway_rest_api`.

> Also, calling update-rest-api from the command line fails with 500 errors

@saxonww do you believe it is an AWS API issue? Have you tried contacting them?

**Comment by saxonww** [comment]
@cmoreira-daitan I do think it's on the AWS side, since their swagger import is/was fiddly and we were seeing 500s even with the aws cli. I don't work for the company where I was experiencing this anymore, and I don't remember if anyone on my team contacted AWS about it or not (I didn't). I think @jrajax might be able to answer though, if he sees this.

**Comment by bflad** [comment]
Hi folks 👋  From looking through the comments here suggesting this was an AWS API issue and seeing that the most recent update was from May 2019, I'm going to close this issue. If there is a problem still, please open a new issue with updated details. 👍
