### ISSUE TITLE
aws_elastic_beanstalk_environment deploy or update 

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#4294]
_This issue was originally opened by @rizplate as hashicorp/terraform#17900. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

How do I update the existing terraform deployed environment **without** using awscli?

I am reading terraform elastic_beanstalk tutorials and it seems the **new** environment is created declaratively but after the environment is created it is updated using awscli. 

how do I update previously created environment using terraform i.e. how do I upload new application version , new docker via Dockerrun.aws.json?

Does it needs to be done using awscli?  why , why cant it be done using terraform?
Can someone point to a github example to do it correctly?

**Comment by mildwonkey** [comment]
Hi @rizplate! 

Could you please share more information about which tutorial you are following and your current configuration?

Here's an example of updating an application, but I don't know how well it applies to your use case. 
Let's say this is your original beanstalk configuration file:

```hcl
resource "aws_elastic_beanstalk_application" "tftest" {
  name        = "tf-test-name"
  description = "tf-test-desc"
}

resource "aws_elastic_beanstalk_environment" "tfenvtest" {
  name                = "tf-test-name"
  application         = "${aws_elastic_beanstalk_application.tftest.name}"
  solution_stack_name = "64bit Amazon Linux 2015.03 v2.0.3 running Go 1.4"
}
```

To update the application, you could create a new `aws_elastic_beanstalk_application` block and  edit the `aws_elastic_beanstalk_environment` `application`. In this example, I create and use an `aws_elastic_beanstalk_application` resource named `tftest_v2` 

```hcl
resource "aws_elastic_beanstalk_application" "tftest" {
  name        = "tf-test-name"
  description = "tf-test-desc"
}

resource "aws_elastic_beanstalk_application" "tftest_v2" {
  name        = "tf-test-v2-name"
  description = "tf-test-v2-desc"
}

resource "aws_elastic_beanstalk_environment" "tfenvtest" {
  name                = "tf-test-name"
  application         = "${aws_elastic_beanstalk_application.tftest_v2.name}"
  solution_stack_name = "64bit Amazon Linux 2015.03 v2.0.3 running Go 1.4"
}
```

**Comment by rizplate** [comment]
@mildwonkey Thanks for example, so do I have to create a new application block for each new version?
lets say I have application code, I deploy it. Now I update some code and now I have to add another block in the teraform file just for new version? how about if i have to deploy every hour, do I need 12 versions blocks in teraform file everyday?

**Comment by mildwonkey** [comment]
If you don't want the existing application to be deleted by terraform, you can either include each version in your configuration, or remove the "old" application from terraform state (which means you won't be able to use terraform to delete the application later unless you import the application version back into your state).

You can reduce repeated code using count and a list (this is untested code and meant only to get you started): 

```hcl
variable "beanstalk_version" {
   default = [ "1.0", "1.1", "1.2"]
}

resource "aws_elastic_beanstalk_application" "myapp" {
  count = ${length(var.beanstalk_version)}
  name        = "app-v${element(var.beanstalk_version, count.index)}"
  description = "myapp version ${element(var.beanstalk_version, count.index)} "
}
``` 

I hope this helps!

**Comment by bflad** [comment]
@rizplate did you need any more information here?
