### ISSUE TITLE
Feature Request: Allow Credential Creation in aws_secretsmanager_secret_version Resource

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#4353]
We recently released the `aws_secretsmanager_secret_version` resource which allows you to pass in a `secret_string` to create a secret version in the service. In a post release comment it was suggested that it might be nice if Terraform could generate the secret rather than requiring it to be passed in.

The Secrets Manager API provides an endpoint called [`GetRandomPassword`](https://docs.aws.amazon.com/sdk-for-go/api/service/secretsmanager/#SecretsManager.GetRandomPassword). This is a feature request to implement support to call that endpoint then pass the result into `SecretString` or randomly generate a secret via `crypto/rand`, similar to `aws_iam_user_login_profile`.

Please vote on this issue by adding a 👍  reaction to the original issue to help prioritize interest. If you're interested in implementing this feature request, please comment below.

### Terraform Version

terraform 0.10+

### Affected Resource(s)

- `aws_secretsmanager_secret_version`

### Terraform Configuration Files

```hcl
# Example implementation with GetRandomPassword, may change when developed
resource "aws_secretsmanager_secret_version" "example" {
  # ... other configuration ...
  generate_random_password { # optional
    exclude_characters = false
    exclude_lowercase = false
    exclude_numbers = false
    exclude_punctuation = false
    exclude_uppercase = false
    include_space = false
    password_length = 32
    require_each_included_type = true
  }
}
```

### Expected Behavior

Resource does not require `secret_string` attribute and generates a random password (via call to `GetRandomPassword` or `crypto/rand` implementation).

### Actual Behavior

New feature.

### References

* https://docs.aws.amazon.com/sdk-for-go/api/service/secretsmanager/#GetRandomPasswordInput
* https://github.com/terraform-providers/terraform-provider-aws/issues/4060#issuecomment-384418075

**Comment by teamhanded** [comment]
This would be phenomenal, since the endpoint is a part of Secrets Manager itself instead of using Terraform resources. For example, I'm resorting to this right now, which is hackish:

```
resource "random_string" "secret" {
  length   = "${var.secret_length}"
  special  = true
  number = true
  upper    = true
  lower     = true
}

resource "aws_secretsmanager_secret_version" "dummy-test-credentials" {
  secret_id       = "${var.secrets_manager_secret_id}"
  secret_string = "${random_string.secret.result}"
}
```

In my opinion, creating the credential (e.g. **prod/platforms/mysql/credentials/root**) natively (using the AWS-provided API endpoint) is much more manageable.

**Comment by teamhanded** [comment]
@bflad Any updates on this?

**Comment by bflad** [comment]
This is not currently planned on our internal roadmap, but we would happily take a look at a pull request.

**Comment by joshuatalb** [comment]
Any updates on this? I'm currently using the hacky approach in @teamhanded's comment and getting this merged would be awesome.

**Comment by spaszek** [comment]
Any updates?
