### ISSUE TITLE
AWS Data type for Codebuild list-curated-environment-images

### ISSUE THREAD

**Issue by Jamie-BitFlight** [hashicorp/terraform-provider-aws#4491]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_codebuild_curated_environment_images

In codebuild when creating a aws_codebuild_project in Terraform, you need to hardcode in the docker build image.
Which you can select from [this page](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html)

The aws API does provide the list of build images available.

### Potential Terraform Configuration

```hcl
#Outputs a list called 'name' which contains the build image names.
#Outputs a list called versions, which contains a nested list of the versions.
data "aws_codebuild_curated_environment_images" "build_image" {
  platforms      = ["UBUNTU"]
  language       = ["PYTHON", "DOCKER"]
}


resource "aws_codebuild_project" "default" {
  name         = "${module.label.id}"
  service_role = "${aws_iam_role.default.arn}"

  artifacts {
    type = "CODEPIPELINE"
  }

  # The cache as a list with a map object inside.
  cache = ["${local.cache}"]

  environment {
    compute_type    = "${var.build_compute_type}"
    image           = "${element(aws_codebuild_curated_environment_images.build_image.*.name, 0)}"
    type            = "LINUX_CONTAINER"
    privileged_mode = "${var.privileged_mode}"

}

```

### References

* https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html

**Comment by aknysh** [comment]
👍

**Comment by tetious** [comment]
This would be very helpful for keeping the image definition updated in codebuild resources. :)
