### ISSUE TITLE
Add aws_cognito_user resource

### ISSUE THREAD

**Issue by posener** [hashicorp/terraform-provider-aws#4542]
### Description

Currently the aws_cognito has an `aws_cognito_user_group` resource which represents a group of users. In the AWS IDP console there is an option to create a user, and assign it to groups. Currently terraform does not support it and it is needed to be created manually.

### New or Affected Resource(s)

* aws_cognito_user

### References

![image](https://user-images.githubusercontent.com/919294/40054680-65b75caa-584e-11e8-8752-ee5b7b86618a.png)

**Comment by SidneyNiccolson** [comment]
Hello,

I was wondering if there are any updates on this? I'm facing a similar issue and tried a null_resource  with local-exec workaround. However I'm using Terraform Cloud and it seems that the aws-cli is not available. Code:

```
resource "null_resource" "cognito_user" {
  count   = length(var.users)
  triggers = {
    user_pool_id = aws_cognito_user_pool.pool.id
  }

  provisioner "local-exec" {
    command = "aws cognito-idp admin-create-user --user-pool-id ${aws_cognito_user_pool.pool.id} --username ${element(var.users, count.index)}"
  }
}
```


Error output: "module.cognito.null_resource.cognito_user[0] (local-exec): /bin/sh: 1: aws: not found"

On my local machine I verified that the AWS cli is installed, but I do prefer using Terraform Cloud.

**Comment by tomelliff** [comment]
You can install more software on the Terraform cloud workers although it is discouraged where you can avoid it. There's more information written up [here](https://www.terraform.io/docs/cloud/run/install-software.html).

**Comment by learnhub17** [comment]
> Hello,
> 
> I was wondering if there are any updates on this? I'm facing a similar issue and tried a null_resource with local-exec workaround. However I'm using Terraform Cloud and it seems that the aws-cli is not available. Code:
> 
> ```
> resource "null_resource" "cognito_user" {
>   count   = length(var.users)
>   triggers = {
>     user_pool_id = aws_cognito_user_pool.pool.id
>   }
> 
>   provisioner "local-exec" {
>     command = "aws cognito-idp admin-create-user --user-pool-id ${aws_cognito_user_pool.pool.id} --username ${element(var.users, count.index)}"
>   }
> }
> ```
> 
> Error output: "module.cognito.null_resource.cognito_user[0] (local-exec): /bin/sh: 1: aws: not found"
> 
> On my local machine I verified that the AWS cli is installed, but I do prefer using Terraform Cloud.

Your solution worked for me and I am able to create users with null resources.

**Comment by confiq** [comment]
yeah, good luck when you have to delete users...

**Comment by RustamGimadiev** [comment]
my 5 cents here, just used the workaround above with some changes,

**Comment by vanschroeder** [comment]
> yeah, good luck when you have to delete users...

That's a good point. A better solution might be to use an `aws_s3_bucket_object` containing the user settings which which can both create and destroy the user via a handy lambda s3 lifecycle trigger which performs the cognito-idp admin command

**Comment by TommasoBianchi** [comment]
Hi everyone, any updates on this? I see there's an open PR (#19919), but it seems to have gone stale (there's been no active development for a while now).

**Comment by rtim75** [comment]
@TommasoBianchi I'm the author of #19919. I'm waiting for the second review and answers to questions regarding resetting user's passwords.
