### ISSUE TITLE
Feature request: support restoration of DynamoDB Continuous Backups and Point-In-Time Recovery (PITR)

### ISSUE THREAD

**Issue by MichaelPereira** [hashicorp/terraform-provider-aws#4558]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Since the support of [Point-in-Time-Revocery](https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html#point_in_time_recovery) added with #4063, it is now possible to save continuous backups via Terraform, but restoring them is still only possible through the [Console](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/PointInTimeRecovery.Tutorial.html#restoretabletopointintime_console) or [AWS API](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/PointInTimeRecovery.Tutorial.html#restorepointintime_cli). It would be great to be able to also restore a dynamodb_table as a new resource created from the latest restorable time or a specific restorable time, similarly to what can be done with the [`snapshot_identifier` for rds instances](https://www.terraform.io/docs/providers/aws/r/db_instance.html#snapshot_identifier)

### New or Affected Resource(s)

* [aws_dynamodb_table](https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html#point_in_time_recovery)

### Potential Terraform Configuration

An example usage in a DynamoDB module would possible look like this:
```hcl
resource "aws_dynamodb_table" "default" {
  name           = "example"
  hash_key       = "${var.hash_key}"
  range_key      = "${var.range_key}"

  point_in_time_recovery {
    restore_date_time = "${var.point_in_time_recovery_date_time}"
  }
```

### References

* #3927 : Feature request: support DynamoDB Continuous Backups and Point-In-Time Recovery (PITR) 
* #3775 : DynamoDB backup functionality?
* https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/PointInTimeRecovery.Tutorial.html#restorepointintime_cli

**Comment by iperica** [comment]
Hi, any update when this feature will be available?

**Comment by satyamsaty** [comment]
Hi , any update on this .When this feature will be available .

**Comment by AntonioDBA** [comment]
Is this in progress?
