### ISSUE TITLE
Cannot manage default aws_db_subnet_group

### ISSUE THREAD

**Issue by tdmalone** [hashicorp/terraform-provider-aws#4674]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.20.0
```

### Affected Resource(s)

* [aws_db_subnet_group](https://www.terraform.io/docs/providers/aws/r/db_parameter_group.html)

### Terraform Configuration Files

First example:

```hcl
resource "aws_db_subnet_group" "default" {
  name = "default"
  ...
}
```

Second example:

```hcl
resource "aws_db_subnet_group" "default" {
  name = "main"
  ...
}
```

### Expected Behavior

With the first example, I expected that Terraform would either generate a diff between my config and the live resource, or advise that everything is up-to-date.

With the second example, I _would_ expect the resource needs recreation, which is exactly what happens - I include this just to demonstrate that given that 'default' isn't accepted, it's not possible to directly manage this resource after importing it.

### Actual Behavior

```bash
$ terraform import aws_db_subnet_group.default default

aws_db_subnet_group.default: Importing from ID "default"...
aws_db_subnet_group.default: Import complete!
  Imported aws_db_subnet_group (ID: default)
aws_db_subnet_group.default: Refreshing state... (ID: default)

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

With first example config from above:

```bash
$ terraform apply

Error: aws_db_subnet_group.default: "Default" is not allowed as "name"
```

With second example config from above:

```bash
$ terraform apply

...
-/+ aws_db_subnet_group.default (new resource required)
      id:                                "default" => <computed> (forces new resource)
      arn:                               "arn:aws:rds:ap-southeast-2:xxxxxxxxxxxx:subgrp:default" => <computed>
      description:                       "default" => "Managed by Terraform"
      name:                              "default" => "main" (forces new resource)
      name_prefix:                       "" => <computed>
...
```

### Steps to Reproduce

1. `terraform import aws_db_subnet_group.default default`
2. Use the first example config above - i.e. setting the name of the imported db_subnet_group to 'defualt'
3. Observe that the name 'default' is not allowed
4. Observe that it's now not possible to directly manage this resource via Terraform ;)

**Comment by tdmalone** [comment]
I'm currently working around this by setting the name to anything other than 'default' and including:

```hcl
lifecycle {
  ignore_changes = ["name"]
}
```

**Comment by tdmalone** [comment]
@bflad FYI I think this may have been incorrectly tagged - should be `service/vpc`, and possibly `bug`, rather than new-resource & service/rds.

**Comment by ewbankkit** [comment]
The problem is that [`validateDbSubnetGroupName`](https://github.com/terraform-providers/terraform-provider-aws/blob/385850fe531b4ecfb4f56b056577a1a0d7fb619c/aws/validators.go#L997) is being called in all scenarios and not just when a new DB Subnet Group is being created.
If we change that then you should be able to import

```console
$ terraform import aws_db_subnet_group.default default
aws_db_subnet_group.default: Importing from ID "default"...
aws_db_subnet_group.default: Import complete!
  Imported aws_db_subnet_group (ID: default)
aws_db_subnet_group.default: Refreshing state... (ID: default)

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

write some Terraform code

```hcl
resource "aws_db_subnet_group" "default" {
 name = "default"
 description = "default"

 subnet_ids = [
   ...
 ]
}
```

and then

```console
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_db_subnet_group.default: Refreshing state... (ID: default)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

**Comment by ewbankkit** [comment]
I think we'll find the same issue with importing the default
* `aws_redshift_subnet_group`
* `aws_neptune_subnet_group`
* `aws_dms_replication_subnet_group`

**Comment by TanmayaA** [comment]
Do we know if there is any progress on the topic?

**Comment by ewbankkit** [comment]
As far as I remember, my approach for getting the working example in https://github.com/terraform-providers/terraform-provider-aws/issues/4674#issuecomment-410391001 was to

* Remove the `ValidateFunc` from the `name` attribute https://github.com/terraform-providers/terraform-provider-aws/blob/471278e9e3fc09e742f1542a06ec67b822bef7ab/aws/resource_aws_db_subnet_group.go#L33-L39
* Add a `CustomizeDiff` function that validated the DB subnet group name only when the resource was being created:
```go
func resourceAwsDbSubnetGroupCustomizeDiff(diff *schema.ResourceDiff, meta interface{}) error {
	if diff.Id() == "" {
		// New resource.
                name:= diff.Get("name").(string);
		// Same logic as validateDbSubnetGroupName.
        }
}
```

**Comment by maiconcarraro** [comment]
I'm using `Terraform v0.12.26` and for me worked just removing `name` line. 

```
resource "aws_db_subnet_group" "default" {
  name = "default"
  description = "default"
...
```

to 

```
resource "aws_db_subnet_group" "default" {
  description = "default"
...
```
