### ISSUE TITLE
changes to initial_lifecycle_hook block of ASG aren't triggering a recreate

### ISSUE THREAD

**Issue by ricoli** [hashicorp/terraform-provider-aws#4714]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.3
+ provider.aws v1.21.0

### Affected Resource(s)

* aws_autoscaling_group

### Terraform Configuration Files

```hcl
resource "aws_autoscaling_group" "asg" {
...

  initial_lifecycle_hook {
    name                 = "instance_launch"
    default_result       = "ABANDON"
    heartbeat_timeout    = 30
    lifecycle_transition = "autoscaling:EC2_INSTANCE_LAUNCHING"

    notification_target_arn = "<some SNS ARN here>"
    role_arn                = "<some IAM role arn here>"
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

### Expected Behavior

When attempting to set/update a initial_lifecycle_hook in an existing auto scaling group, I would expect that ASG to be recreated, as to apply said hook configuration.

### Actual Behavior

A Terraform plan produces an inline update for the hook configuration, which actually does nothing, as this block is only intended for newly created ASGs.

### Steps to Reproduce

1. Have an existing auto scaling group without an initial_lifecycle_hook block
2. `terraform apply` it
3. Modify ASG to have an initial_lifecycle_hook block
2. `terraform plan` produces an inline update, and applying it results in nothing getting done.

**Comment by mkv-ts** [comment]
I just encountered this today too, so I wouldn't calling this stale.

Deleting the hook from aws web console and then doing a terraform apply does nothing too.
How to get around this issue?

**Comment by krynczak** [comment]
> 
> 
> I just encountered this today too, so I wouldn't calling this stale.
> 
> Deleting the hook from aws web console and then doing a terraform apply does nothing too.
> How to get around this issue?

Hey, i've just encountered the same issue on my end and got around it by tainting the ASG.
