### ISSUE TITLE
Failing cloudwatch alarm creation not detected

### ISSUE THREAD

**Issue by andig** [hashicorp/terraform-provider-aws#4732]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

	Terraform v0.11.7
	+ provider.aws v1.20.0
	+ provider.template v1.0.0

### Affected Resource(s)

* aws_cloudwatch_metric_alarm

### Terraform Configuration Files

```hcl
resource "aws_cloudwatch_metric_alarm" "default" {
  alarm_name = "${var.lambda_name}-failure"
  comparison_operator = "GreaterThanThreshold"
  period = "300"
  evaluation_periods = "1"
  metric_name = "Errors"
  namespace = "AWS/Lambda"
  statistic = "Average"
  threshold = "0"
  alarm_description = "${var.lambda_name} lambda health alarm"
  alarm_actions = [
    "${aws_sns_topic.default.arn}"
  ],
  dimensions {
    function_name = "${aws_lambda_function.default.function_name}"
  }
}
```

### Expected Behavior

TF should notice that `function_name` is an invalid dimension (it has to be `FunctionName` for Lamda) and leads to the alarm getting stuck as 

	State changed to INSUFFICIENT DATA at 2018/06/02. Reason: Unchecked: Initial alarm creation

### Actual Behavior

Apply runs without errors. This is insofar a problem as TF creates monitoring infrastructure in this case that simply doesn't work as expected.

### References

This is a bit similar to https://github.com/terraform-providers/terraform-provider-aws/issues/4682 as such that aws resources are being created that are broken in their setup.

I'm wondering if identifying this should be in scope of TF or not?

**Comment by shouryasharmahere** [comment]
I'm facing a similar issue..
