### ISSUE TITLE
aws_spot_instance_request fail randomlly with 'No default subnet for availability zone'

### ISSUE THREAD

**Issue by pkowalczyk9LD** [hashicorp/terraform-provider-aws#4869]
In some cases 50/50 when creating 6 spot machines, one of them fail with error message mentioned bellow. 

### Terraform Version
Terraform v0.11.7
+ provider.aws v1.23.0

### Affected Resource(s)

* aws_spot_instance_request

### Terraform Configuration Files

```
variable "instance_type" { default = "t2.xlarge" }
variable "count" { default = 1 }
variable "prefix" {default = "default"}
variable "spot_price" {default = "0.2208"}

provider "aws" {
  region     = "us-west-1"
}

resource "aws_spot_instance_request" "sa_host" {
  count = "${var.count}"
  spot_price = "${var.spot_price}"
  wait_for_fulfillment = true
  ami = "ami-xxxxxxx"
  instance_type = "${var.instance_type}"
  root_block_device {
    delete_on_termination = true
    volume_type = "gp2"
  }
  tags {
    Name = "${var.prefix}-SpotWorker-${count.index}"
  }

```

### Debug Output

https://gist.github.com/pkowalczyk9LD/1823004173984e08efb9f03683ace573

### Expected Behavior

Should create machines without errors

### Actual Behavior

```
2018-06-18T10:52:53.768Z [DEBUG] plugin.terraform: remote-exec-provisioner (internal) 2018/06/18 10:52:53 [DEBUG] plugin: waiting for all plugin processes to complete...
Error: Error applying plan:

1 error(s) occurred:

* aws_spot_instance_request.sa_host[0]: 1 error(s) occurred:

* aws_spot_instance_request.sa_host.0: Error requesting spot instances: InvalidSubnetID.NotFound: No default subnet for availability zone: 'null'.
	status code: 400, request id: e5696205-39fc-4833-9267-9cfeb7e59506

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


2018-06-18T10:52:53.771Z [WARN ] plugin: error closing client during Kill: err="unexpected EOF"
```

### Steps to Reproduce

1. `terraform apply -var count="6" `

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bflad** [comment]
Hi @pkowalczyk9LD 👋  Sorry you are running into trouble here.

Could you double check that you do indeed have default subnets available for both `us-west-1a` and `us-west-1b` availability zones for `vpc-c268bfa6`?

Here's how you can check with the AWS CLI (substituting your VPC ID):

```
$ aws --region us-west-1 ec2 describe-subnets --filters Name=defaultForAz,Values=true,Name=vpcId,Values=vpc-e76be482
{
    "Subnets": [
        {
            "AvailabilityZone": "us-west-1b",
            "AvailableIpAddressCount": 4091,
            "CidrBlock": "172.31.16.0/20",
            "DefaultForAz": true,
            "MapPublicIpOnLaunch": true,
            "State": "available",
            "SubnetId": "subnet-d2b6c5b7",
            "VpcId": "vpc-e76be482",
            "AssignIpv6AddressOnCreation": false,
            "Ipv6CidrBlockAssociationSet": []
        },
        {
            "AvailabilityZone": "us-west-1a",
            "AvailableIpAddressCount": 4091,
            "CidrBlock": "172.31.0.0/20",
            "DefaultForAz": true,
            "MapPublicIpOnLaunch": true,
            "State": "available",
            "SubnetId": "subnet-ec9a2ab5",
            "VpcId": "vpc-e76be482",
            "AssignIpv6AddressOnCreation": false,
            "Ipv6CidrBlockAssociationSet": []
        }
    ]
}
```

The error `InvalidSubnetID.NotFound: No default subnet for availability zone: 'null'.` is coming from the EC2 API and it doesn't appear you are passing in a specific `subnet_id`.

**Comment by pkowalczyk9LD** [comment]
Hi Brian,
Thanks for looking into this issue.

Yes, we have default subnet defined for all availability zones in VPC, otherwise we would have run into this issue in all cases instead of just some. 

We did not specify availability zone on purpose, as it's optional field for terraform, and aws should create spot instance in cheapest one from what I understand from documentation.

However defining availability_zone parameter for aws_spot_instance_request seams to be workaround for this issue for us (we are still testing that)

**Comment by pkowalczyk9LD** [comment]
Hi Brian,
Thanks for looking into this issue.

Yes, we have default subnet defined for all availability zones in VPC, otherwise we would have run into this issue in all cases instead of just some. 

We did not specify availability zone on purpose, as it's optional field for terraform, and aws should create spot instance in cheapest one from what I understand from documentation.

However defining availability_zone parameter for aws_spot_instance_request seams to be workaround for this issue for us (we are still testing that)

**Comment by cagriy** [comment]
We are observing the same issue on 0.12.0, default subnets exists. Very same terraform configuration was working fine until few days ago. To apply a configuration change I tainted existing spot_instance_request and run terraform apply.

Instance_request destroyed successfully but failed to recreate.

**Comment by koalalorenzo** [comment]
Same here

**Comment by Gknoblau** [comment]
Having the same issue. Setting the `availability_zone=` property works as a workaround.

**Comment by girishkumarbk** [comment]
Having same issue for me too.  I have never provided availability_zone= as the parameter for aws_spot request !  The terraform script worked well all these days and suddenly one fine day it error out with same error "InvalidSubnetID.NotFound: No subnets found for the default VPC".   I requested for spot request on a different VPC with subnet and not sure why defaut vpc subnet is required here???
