### ISSUE TITLE
Terraform does not refresh S3 bucket region after manual re-creation

### ISSUE THREAD

**Issue by jeohist** [hashicorp/terraform-provider-aws#4870]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform 0.11.7
Provider "aws" 1.23.0

### Affected Resource(s)

* aws_s3_bucket

### Terraform Configuration Files

Creation:
```hcl
provider "aws" {
  region = "eu-west-1"
}

resource "aws_s3_bucket" "glue_euc" {
  bucket = "glue-eu-central-1"
}

```
Deletion and re-creation happens here

```hcl
provider "aws" {
  region = "eu-central-1"
}

resource "aws_s3_bucket" "glue_euc" {
  bucket = "glue-eu-central-1"
}
```

### Debug Output

Error: Error refreshing state: 1 error(s) occurred:

* aws_s3_bucket.glue_euc: aws_s3_bucket.glue_euc: error reading S3 bucket "glue-eu-central-1": BucketRegionError: incorrect region, the bucket is not in 'eu-west-1' region
	status code: 301, request id: , host id: 

### Expected Behavior

* User creates an S3 bucket in eu-west-1 (for example)
* User realizes they made a mistake and manually recreates bucket in eu-central-1 (for example)
* User runs Terraform refresh and state file is updated with new region and endpoint

### Actual Behavior

* User creates an S3 bucket in eu-west-1 (for example)
* User realizes they made a mistake and manually recreates bucket in eu-central-1 (for example)
* User re-applies Terraform refresh and an error is returned

### Steps to Reproduce

1. Create bucket through Terraform in region 1
2. terraform apply
3. Delete S3 bucket and recreate it in another region
4. Update Terraform configuration with the new region
5. terraform refresh

**Comment by niklasbeinghaus** [comment]
API-related race-condition:
The region in which you try to spawn a new S3-Bucket might not know about the previously deleted bucket in the original region.

**Comment by jeohist** [comment]
Still an issue unfortunately.
