### ISSUE TITLE
aws_acm_certificate data source fails on SAN lookups

### ISSUE THREAD

**Issue by LukeL99** [hashicorp/terraform-provider-aws#4877]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform does not allow searching for ACM certificates by SAN, only the main domain. I have a certificate that covers the following subdomains:

```
portal.redacted.com
staging-portal.redacted.com
dev-portal.redacted.com
```

`portal.redacted.com` is the main domain, `staging-portal` and `dev-portal` are SAN names. I'm scripting setting up of my different environments, I can't use the ACM data source to lookup the certificate to use without hardcoding `portal.redacted.com` as the domain to look up.

### Terraform Version

Terraform v0.11.7

### Affected Resource(s)

* aws_acm_certificate (data source, not resource)

### Terraform Configuration Files

```hcl
data "aws_acm_certificate" "acm_cert" {
  domain   = "dev-portal.redacted.com"
  statuses = ["ISSUED"]
  most_recent = true
}

resource "aws_cloudfront_distribution" "s3_distribution" {
  origin {
    domain_name = "${aws_s3_bucket.public_bucket.bucket_regional_domain_name}"
    origin_id   = "${aws_s3_bucket.public_bucket.bucket}"
  }

  enabled             = true
  is_ipv6_enabled     = true
  default_root_object = "index.html"

  aliases = ["${aws_s3_bucket.public_bucket.bucket}"]

  default_cache_behavior {
    allowed_methods  = ["GET", "HEAD", "OPTIONS"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "${aws_s3_bucket.public_bucket.bucket}"

    forwarded_values {
      query_string = false

      cookies {
        forward = "none"
      }
    }

    min_ttl                = 0
    default_ttl            = 3600
    max_ttl                = 86400
    compress               = true
    viewer_protocol_policy = "redirect-to-https"
  }

  price_class = "PriceClass_100"

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    acm_certificate_arn = "${data.aws_acm_certificate.acm_cert.arn}"
    ssl_support_method = "sni-only"
  }
}

```

### Expected Behavior

The data source should return the ACM cert that covers the domain queried `dev-portal.redacted.com`.

### Actual Behavior

The data source doesn't return an ACM.
`module.dev_portal.data.aws_acm_certificate.acm_cert: data.aws_acm_certificate.acm_cert: No certificate for domain "dev-portal.redacted.com" found in this region.`

### Steps to Reproduce

1. Create an ACM certificate that has a SAN subdomain.
2. Modify the above to lookup the SAN domain.
3. `terraform apply`

**Comment by nchangnon** [comment]
👍

**Comment by iancward** [comment]
I'm running into the same issue, but unfortunately, it looks like the AWS API doesn't display the SANs associated with an SSL certificate on a list-certificates API call. To add support for this, terraform would have to get the list and iterate over it, making a describe API call for every single certificate, which is probably not exactly ideal.
