### ISSUE TITLE
 using count on aws_elasticache_cluster breaks output

### ISSUE THREAD

**Issue by allcloud-jonathan** [hashicorp/terraform-provider-aws#4889]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.aws v1.23.0
+ provider.external v1.0.0
+ provider.random v1.3.1
+ provider.template v1.0.0

### Affected Resource(s)

* aws_elasticache_cluster

### Terraform Configuration Files

This is the relevant section from the module. Depending on environment/workspace: 
* redis has to be created as a replication group (not shown here)
* redis has to be created as a single node
* a local redis install will be used, so no redis should be deployed on AWS

```hcl
resource "aws_elasticache_cluster" "redis" {
  count                = "${var.create && var.number_of_replicas == 0 ? 1 : 0}"
  cluster_id           = "${substr(var.cluster_id, 0, min(20, length(var.cluster_id)))}"
  engine               = "redis"
  engine_version       = "${var.engine_version}"
  port                 = "${var.port}"
  node_type            = "${var.instance_type}"
  maintenance_window   = "${var.maintenance_window}"
  num_cache_nodes      = 1
  parameter_group_name = "${var.parameter_group_name}"
  subnet_group_name    = "${aws_elasticache_subnet_group.default.name}"
  security_group_ids   = ["${aws_security_group.redis.id}"]
  tags                 = "${local.tags}"
}

output "endpoint" {
  description = "Public DNS of the Redis resource"
  value       = "${element(concat(aws_elasticache_cluster.redis.*.cache_nodes.0.address, list("")), 0)}"
}
```

I tried working around this with the following below which didn't work either.

```hcl
output "endpoint" {
  description = "Public DNS of the Redis resource"
  value       = "${element(concat(data.template_file.bugfix-noncluster.*.rendered, list("")), 0)}"
}

data "template_file" "bugfix-noncluster" {
  count    = "${var.create && var.number_of_replicas == 0  ? 1 : 0}"
  template = "$${output}"

  vars {
    output = "${element(concat(aws_elasticache_cluster.redis.*.cache_nodes.0.address, list("")), 0)}"
  }
}
```

### Expected Behavior

if both `create` is true and `number_of_replicas` is 0 the `endpoint` output should be populated with the first (and only) cache_node address.

### Actual Behavior

```
Error: Error running plan: 1 error(s) occurred:

* module.elasticache_redis.output.endpoint: Resource 'aws_elasticache_cluster.redis' does not have attribute 'cache_nodes.0.address' for variable 'aws_elasticache_cluster.redis.*.cache_nodes.0.address'

```

### Steps to Reproduce

1. `terraform apply` or `terraform plan`

### References

* #214 is similar but the actual problem there, is using a `*` between `cache_nodes` and `address`.

**Comment by allcloud-jonathan** [comment]
Ok, here is the workaround I found. The issue lies with the splat syntax and that it won't work with computed maps.

The trick is to just use `jsonencode` to break the map down into a string, no mater what it contains and then use a regex to cut out the address which we are interested in. Really ugly, but works.

If the cluster is not created, the output of `jsonencode` will be `[]`. To keep things clean we do a outer replace so that it will actually return an empty string.

```hcl
output "endpoint" {
  description = "Public DNS of the Redis resource"
  value       = "${element(concat(list(replace(replace(jsonencode(aws_elasticache_cluster.redis.*.cache_nodes), "/.*address...([a-z0-9\\.\\-]+)\".*/" , "$1"), "[]", "")), list("")), 0)}"
}
```

**Comment by jeremygaither** [comment]
I am seeing the same error when using data:

```
data "aws_elasticache_cluster" "iavs_nodes" {
  count = "${var.iavs_redis_replicas + var.iavs_redis_extra_replicas}"

  cluster_id = "${aws_elasticache_replication_group.iavs.id}-${format("%03d", count.index + 1)}"

  depends_on = [
    "aws_elasticache_replication_group.iavs",
    "aws_elasticache_cluster.iavs_replica",
  ]
}

resource "aws_route53_record" "iavs_redis_replica" {
  count = "${var.iavs_redis_replicas + var.iavs_redis_extra_replicas}"

  name    = "REDACTED-redis-replica-${lower(var.environment_label)}-${format("%03d", count.index + 1)}"
  zone_id = "${data.aws_route53_zone.REDACTED.zone_id}"
  type    = "CNAME"
  ttl     = "30"

  records = ["${element(data.aws_elasticache_cluster.iavs_nodes.*.cache_nodes.0.address, count.index)}"]

  depends_on = [
    "aws_elasticache_replication_group.iavs",
    "aws_elasticache_cluster.iavs_replica",
  ]
}
```

Error Message:
```
Error: Error running plan: 1 error(s) occurred:

* aws_route53_record.iavs_redis_replica: 3 error(s) occurred:

* aws_route53_record.iavs_redis_replica[0]: Resource 'data.aws_elasticache_cluster.iavs_nodes' does not have attribute 'cache_nodes.0.address' for variable 'data.aws_elasticache_cluster.iavs_nodes.*.cache_nodes.0.address'
* aws_route53_record.iavs_redis_replica[1]: Resource 'data.aws_elasticache_cluster.iavs_nodes' does not have attribute 'cache_nodes.0.address' for variable 'data.aws_elasticache_cluster.iavs_nodes.*.cache_nodes.0.address'
* aws_route53_record.iavs_redis_replica[2]: Resource 'data.aws_elasticache_cluster.iavs_nodes' does not have attribute 'cache_nodes.0.address' for variable 'data.aws_elasticache_cluster.iavs_nodes.*.cache_nodes.0.address'
```

**Comment by allcloud-jonathan** [comment]
@jeremygaither Out of curiosity: where you able to adjust the workaround for the multi-node problem?

**Comment by nick4fake** [comment]
AWS provider v1.39 and TF 0.11.8 are also affected.

**Comment by Jasstkn** [comment]
> Ok, here is the workaround I found. The issue lies with the splat syntax and that it won't work with computed maps.
> 
> The trick is to just use `jsonencode` to break the map down into a string, no mater what it contains and then use a regex to cut out the address which we are interested in. Really ugly, but works.
> 
> If the cluster is not created, the output of `jsonencode` will be `[]`. To keep things clean we do a outer replace so that it will actually return an empty string.
> 
> ```terraform
> output "endpoint" {
>   description = "Public DNS of the Redis resource"
>   value       = "${element(concat(list(replace(replace(jsonencode(aws_elasticache_cluster.redis.*.cache_nodes), "/.*address...([a-z0-9\\.\\-]+)\".*/" , "$1"), "[]", "")), list("")), 0)}"
> }
> ```

Hi!
I used your workaround, I've got only first DNS. But I need to get all of the addresses. Could you help me with changing your code for this purpose?

Sample of json:
[[{"address":"****.0001.euc1.cache.amazonaws.com","availability_zone":"eu-central-1b","id":"0001","port":"6379"}],[{"address":"*****.0001.euc1.cache.amazonaws.com","availability_zone":"eu-central-1b","id":"0001","port":"6379"}]]

**Comment by gordonbondon** [comment]
@Jasstkn I was able to get all dns records like this

**Comment by Jasstkn** [comment]
@gordonbondon I found this ways for access node_endpoints:
for **redis**
```
aws_elasticache_replication_group.{name_of_redis}.primary_endpoint_address
```
for memcached
```
module.ec-memcached.node_endpoints
```

**Comment by yannick-fernand** [comment]
hi i have found a better way to get the node_endpoints as string like node_endpoint1,node_endpoint2,etc 
**main:** 
`resource "aws_elasticache_replication_group" "this" {
  engine                        = "redis"
  automatic_failover_enabled    = "${var.automatic_failover_enabled}"
  engine_version                = "${var.engine_version}"
  node_type                     = "${var.node_type}"
  parameter_group_name          = "${var.parameter_group_name}"
  port                          = "${var.port}"
  replication_group_description = "${var.replication_group_description}"
  replication_group_id          = "${var.replication_group_id}"
  security_group_ids            = ["${aws_security_group.this.id}"]
  subnet_group_name             = "${aws_elasticache_subnet_group.this.name}"
  number_cache_clusters         = "${var.number_cache_clusters}"

  lifecycle {
    ignore_changes = ["number_cache_clusters"]
  }
}

data "aws_elasticache_cluster" "replicas" {
  count      = "${var.number_cache_clusters}"
  cluster_id = "${element(aws_elasticache_replication_group.this.member_clusters,count.index)}"
  depends_on = ["aws_elasticache_replication_group.this"]
}`

**output** 

`output "node_endpoints" {
  value = "${join(",",compact(split(",",replace(jsonencode(data.aws_elasticache_cluster.replicas.*.cache_nodes), "/.*?(?:\"address\".?.?\"((?:${join("|",aws_elasticache_replication_group.this.member_clusters)})[0-9a-z\\.\\-]+)\")|(.)/", "$1,"))))}"
}`
