### ISSUE TITLE
feature request: medialive resources

### ISSUE THREAD

**Issue by micylt** [hashicorp/terraform-provider-aws#4936]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Currently there is not a resource available for Elemental MediaLive. Looking to have the ability to specify input and output groups, input specifications (maximum input bitrate, etc.), destinations and security groups.

### New or Affected Resource(s)

* aws_elemental_medialive

**Comment by ewbankkit** [comment]
Potential new resources and data sources:

* `aws_medialive_channel`
* `aws_medialive_input`
* `aws_medialive_input_security_group`
* `aws_medialive_multiplex`
* `aws_medialive_multiplex_program`

**Comment by bbayles** [comment]
I'm still interested in this issue being fixed, i.e. MediaLive support being added.

**Comment by rkdeloitted** [comment]
What happened to this resource? We need it .

**Comment by nikes** [comment]
me too, guys...

**Comment by Hibanka** [comment]
also need it

**Comment by Perlzx** [comment]
very necessary for me
