### ISSUE TITLE
r/aws_default_subnet: Full resource lifecycle

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#4957]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

[Now](https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/default-vpc.html#create-default-subnet) that default subnets can be created we should think about a "next generation" `aws_default_subnet` resource that can do full resource lifecycle operations (Create and Delete along with Read and Update).

**Comment by ewbankkit** [comment]
Replaces https://github.com/terraform-providers/terraform-provider-aws/issues/2254.

**Comment by gdavison** [comment]
The Delete operation gets potentially dangerous here, since the old behaviour was to simply remove from state.

We could leverage the [diagnostic warnings](https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html#support-for-diagnostics) added in Plugin SDK v2.

**Comment by ewbankkit** [comment]
#### v4.0.0 Design

Modify the `aws_default_subnet` resource to be able to Create and Delete default subnets.
This will be implemented so as to maximize infrastructure safety and minimize practitioner surprise.
If a default subnet already exists in the specified Availability Zone, on resource Create adopt the resource into management, otherwise call the [CreateDefaultSubnet](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateDefaultSubnet.html) API to create a new default subnet.
On resource Delete the default subnet is not deleted (it is removed from Terraform state), unless the configuration sets the new argument `force_destroy = true`. This argument’s default value will be `false`.

**Comment by anGie44** [comment]
Implementation complete with merge of #22253
