### ISSUE TITLE
r/aws_default_vpc: Full resource lifecycle

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#4959]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

[Now](https://docs.aws.amazon.com/cli/latest/reference/ec2/create-default-vpc.html) that default VPCs can be created we should think about a "next generation" `aws_default_vpc` resource that can do full resource lifecycle operations (Create and Delete along with Read and Update).

**Comment by ewbankkit** [comment]
Replaces https://github.com/terraform-providers/terraform-provider-aws/issues/1289 and https://github.com/terraform-providers/terraform-provider-aws/issues/4290.

**Comment by ewbankkit** [comment]
Similar to https://github.com/terraform-providers/terraform-provider-aws/issues/4957.

**Comment by lorengordon** [comment]
I'd find this valuable, in particular to be able to set the VPC CIDR for the default VPC. The resource should be able to create, update, and delete the default vpc. A user could import the existing resource into a config with matching attributes to avoid a resource cycle.

**Comment by dirk39** [comment]
Let me try this!

**Comment by ewbankkit** [comment]
#### v4.0.0 Design

Modify the `aws_default_vpc` resource to be able to Create and Delete default VPCs.
This will be implemented so as to maximize infrastructure safety and minimize practitioner surprise.
If a default VPC already exists, on resource Create adopt the resource into management, otherwise call the [`CreateDefaultVpc`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateDefaultVpc.html) API to create a new default VPC
On resource Delete the default VPC is not deleted (it is removed from Terraform state), unless the configuration sets the new argument `force_destroy = true`. This argument’s default value will be `false`.

**Comment by anGie44** [comment]
Implementation complete with merge of #22253
