### ISSUE TITLE
Setup Region/Partition Agnostic aws_instance Acceptance Testing

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#4987]
Its not currently possible to run the `aws_instance` resource and data source acceptance testing outside `us-west-2` and get meaningful results. For example, setting `AWS_DEFAULT_REGION=us-east-1` while running the tests today returns: `Tests failed: 61 (59 new), passed: 6`

Many of the failures are similar to:

```
--- FAIL: TestAccAWSInstance_basic (8.76s)
    testing.go:518: Step 0 error: Check failed: InvalidZone.NotFound: The zone 'us-west-2a' does not exist.
```

And:

```
--- FAIL: TestAccAWSInstance_disableApiTermination (17.22s)
    testing.go:518: Step 0 error: Error applying: 1 error(s) occurred:
        
        * aws_instance.foo: 1 error(s) occurred:
        
        * aws_instance.foo: Error launching source instance: InvalidAMIID.NotFound: The image id '[ami-4fccb37f]' does not exist
```

We can switch to using the `aws_region`, `aws_availability_zones`, and `aws_partition` data sources as appropriate to remove hardcoded `us-west-2` pieces. For acceptance tests that cannot occur outside of `us-west-2` (due to very specific AMIs, etc.), we can set them up with `t.Skip()`.

**Comment by ewbankkit** [comment]
Look also at acceptance tests for:
* `aws_ami_from_instance`
* `aws_autoscaling_attachment`
* `aws_autoscaling_lifecycle_hook`
* `aws_autoscaling_notification`
* `aws_autoscaling_schedule`
* `aws_eip_association`
* `aws_elb_attachment`
* `aws_launch_configuration`
* `aws_launch_template`
* `aws_lb_target_group_attachment`
* `aws_network_interface_attachment`
* `aws_network_interface`
* `aws_route_table`
* `aws_route`
* `aws_spot_fleet_request`
* `aws_spot_instance_request`
* `aws_volume_attachment`

as there are some with hard-coded AMIs (look for `ami` or `image_id` attributes).

**Comment by ewbankkit** [comment]
Not all instance types are available in all regions/partitions so there will need to be cleanup of `instance_type` also.

**Comment by PatMyron** [comment]
> We can use the new EC2 [`DescribeInstanceTypeOfferings`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstanceTypeOfferings.html) API to add a `PreCheck` that the test's instance type is supported.

Unfortunately instance type regional availability varies in other AWS services beyond EC2 as well. [The CloudFormation Linter gathers instance type regional availability for over a dozen services from the pricing API here](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/scripts/update_specs_from_pricing.py)
