### ISSUE TITLE
Glue table partition keys should be set to empty list instead of being unset

### ISSUE THREAD

**Issue by f0rk** [hashicorp/terraform-provider-aws#5206]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.1
+ provider.aws v1.24.0

### Affected Resource(s)

* aws_glue_catalog_table

### Terraform Configuration Files

```hcl
resource "aws_glue_catalog_table" "test" {
...
partition_keys = []
...
}
```

### Expected Behavior

Partition keys should be set to an empty list.

### Actual Behavior

Partition keys is unset.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I originally opened a support request with AWS because a view I was trying to create could not be queried. This was their response:

The issue could be caused by a bug in Athena views that the table property partitionKeys is not set when creating the table since they are not required parameters. I can reproduce the behavior and setting the partitionKeys as an empty list can mitigate the issue. I checked the tables in the views and confirmed that they have no partitionKeys property. Could you try this workaround and see if the issue still exists? Athena team is actively working to address the issue and the error message since it doesn't provide any useful information. Apologies for the inconvenience caused to you.

**Comment by f0rk** [comment]
I've tried to fix this issue, but I'm having trouble figuring out how to convince Terraform that an empty list is a value, and not no value at all. It seems many places in the code think that 0, "", [], etc. are no value at all. So when I hardcode an empty list to be set for partition keys, Terraform reports that the attribute is not set. Any ideas about how to work around this?

**Comment by rooozox** [comment]
Hitting this problem as well today. Any known workaround?  (using version 0.12.2)

**Comment by gmazelier** [comment]
Same here. Made a quick local test: it seems that explicitly having an empty list for the partition keys fix the problem. Having `nil` does not behave the same when serialising. This need more test but I will a pull request soon.
