### ISSUE TITLE
point in time restore support for aws rds instances

### ISSUE THREAD

**Issue by psura** [hashicorp/terraform-provider-aws#5286]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Today terraform aws provider support managing rds instances through aws_db_instace resource.
https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_db_instance.go
This resource also supports restoring from a snapshot if snapshot_identifier is passed and also supports restore db instance from s3.
We don't seem to have support for restoring to a specific point in time. This maps to below AWS API
https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_RestoreDBInstanceToPointInTime.html

We are trying to reduce the restore times when an incident occurs that requires db instance restore so that we can meet our RTO (and RPO) and quickly bring the production back to business. 
Having an automated restore procedure in place is very critical. In our case we are using aws rds postgres and also have plans to move to aurora in future.
Since we would like Terraform to manage the existing and newly created resources (from restore), we are looking forward for the restore to a point in time support in terraform (for rds instances as of now).

Is this in the road map? Can some one share details on timeline or what is needed to get this feature support? I am new to the go programming but am myself looking at the aws provider code base to see what can be done. Any help is appreciated.

### New or Affected Resource(s)

* aws_db_instance

### References
I see some discussion in google group here https://groups.google.com/d/topic/terraform-tool/vDUw9YmqtN4/discussion and a suggestion from Paul Hinze.
AWS API
https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_RestoreDBInstanceToPointInTime.html

**Comment by ewbankkit** [comment]
Aurora point-in-time restore: https://github.com/terraform-providers/terraform-provider-aws/pull/7031.

**Comment by chadmyers** [comment]
Is there any way to bump this up in priority to get [the PR](https://github.com/terraform-providers/terraform-provider-aws/pull/7031) reviewed and merged? Is there anything I can do to help. Thanks!

**Comment by dilunika** [comment]
Since this is open from 2018, I assume there would be a work around. Can anyone suggest what would be the workaround let Terraform to mange the point-in-time recovery or let terraform to manage both instances when we restore from a snapshot?

**Comment by maryelizbeth** [comment]
@chadmyers This issue is prioritized as part of our roadmap work for August-October. We haven't yet started work for it, but will reach out to the contributing PR author as well as on this issue as we work through the items in [our roadmap](https://github.com/terraform-providers/terraform-provider-aws/blob/master/ROADMAP.md) and begin work on point in time restore. 

Once this feature is scheduled for release, it will move from the [roadmap milestone ](https://github.com/terraform-providers/terraform-provider-aws/milestone/138) into a release milestone (e.g. v3.3.0). 

Hope this clears things up, and please reach out if you have any questions!

**Comment by mdykes-gw** [comment]
Checking in... haven't seen it in 3.10 or 3.11... how's it looking?

**Comment by jbhennin** [comment]
@maryelizbeth Any update on this enhancement.  Being able to do PITR via TF is a very needed feature as it has been in the AWS apis for some time

**Comment by anGie44** [comment]
Support for `PointInTimeRestore` has been merged for both `rds_cluster` and `db_instance` resources and will release with `v3.15.0` of the Terraform AWS Provider, expected out later today.
