### ISSUE TITLE
Inspector Resource Group tags values list

### ISSUE THREAD

**Issue by nastiazaran** [hashicorp/terraform-provider-aws#5349]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Inspector Resource Group creation does not allow to pass a list of tag values for an specific tag name.

### Affected Resource(s)
* aws_inspector_resource_group
* aws_inspector_assessment_target

### Terraform Configuration Files

```hcl
resource "aws_inspector_resource_group" "bar" {
  tags {
    Name = [ "foo", "bar" ]
  }
}

 resource "aws_inspector_assessment_target" "foo" {
  name               = "assessment target"
  resource_group_arn = "${aws_inspector_resource_group.bar.arn}"
}
```
### Expected Behavior
An aws_inspector_assessment_target  resource should be created with the 'Use Tags' Key: Name, Values: foo, bar . 
It is allowed by the [aws api](https://docs.aws.amazon.com/inspector/latest/APIReference/API_CreateResourceGroup.html):  

_**resourceGroupTags**
A collection of keys and an array of possible values, '[{"key":"key1","values":["Value1","Value2"]},{"key":"Key2","values":["Value3"]}]'_.

### Actual Behavior
```
Error: aws_inspector_resource_group.bar: tags (Name): '' expected type 'string', got unconvertible type '[]interface {}'
```

### Steps to Reproduce
```
1. terraform apply
```

**Comment by ewbankkit** [comment]
One possible implementation (to retain backwards compatibility) is something like

```hcl
resource "aws_inspector_resource_group" "example" {
  tag {
    key    = "Name"
    values = ["foo", "bar"]
  }

  tag {
    key    = "Usage"
    values = ["test"]
  }
}
```

**Comment by djordje-petrovic** [comment]
Has anyone come up with a solution to this by now? Is it possible to assign multiple values to one key? Like the OP requested.
