### ISSUE TITLE
Cloudwatch widget not showing any data when created using terraform

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#5418]
_This issue was originally opened by @Er-sumit as hashicorp/terraform#18577. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Hi
```Terraform v0.11.2```
I have created Cloudwatch dashboard and CPU Utilization widget for an instance. Dashboard and widget created successfully.
But problem is widget not showing any data.
Whereas If I create widget for same properties manually, there is data present.

widget created using Terraform
![image](https://user-images.githubusercontent.com/41416816/43504542-78dceff0-9581-11e8-9604-9a0f733d8780.png)

widget created Manually using AWS console
![image](https://user-images.githubusercontent.com/41416816/43504615-bc725408-9581-11e8-890d-bba3ad6a1923.png)

Note: Both widgets created about 10 hours ago

### Terraform Version

```
Terraform v0.11.2
...
```

### Terraform Configuration Files

```hcl
...
resource "aws_cloudwatch_metric_alarm" "es-master-1-cpu" {
  alarm_name          = "${aws_instance.master1-ins.id}-cpu-utilization"
  namespace           = "AWS/EC2"
  evaluation_periods  = "2"
  period              = "60"
  statistic           = "Average"
  alarm_description   = "This metric records cpu utilization of es master 1 instance"
  comparison_operator = "GreaterThanThreshold"
  threshold           = "80"
  metric_name         = "CPU Utilization ES-M1"
  dimensions {
    InstanceId = "${aws_instance.master1-ins.id}"
  }
}

resource "aws_cloudwatch_dashboard" "main" {
   dashboard_name = "es-dashboard"
   dashboard_body = <<EOF
 {
   "widgets": [
       {
          "type":"metric",
          "x":0,
          "y":0,
          "width":12,
          "height":6,
          "properties":{
             "metrics":[
                [
                   "AWS/EC2",
                   "CPUUtilization",
                   "InstanceId",
                   "${aws_instance.master1-ins.id}"
                ]
             ],
             "period":300,
             "stat":"Average",
             "region":"us-east-1",
             "title":"ES-M1 Instance CPU"
          }
       }
}
```

**Comment by Er-sumit** [comment]
Waiting for any response...

**Comment by prakashjha08** [comment]
Hi, has this issue been resolved with any solution ? I am facing the same problem.

**Comment by weberc2-tempus** [comment]
You can always get the widget source JSON for both the Terraform version and the manual console version and diff them to figure out the differences.

**Comment by xharsin** [comment]
@weberc2-tempus  thanks it worked
