### ISSUE TITLE
no_device support for aws_launch_config device block definition

### ISSUE THREAD

**Issue by tinder-jlee** [hashicorp/terraform-provider-aws#5464]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In [a previous PR](https://github.com/hashicorp/terraform/pull/10547), support for `no_device` attribute for ephemeral device block implemented.
However, wouldn't it be possible to support it also for device blocks definition in `aws_launch_configuration`?
Currently it's not possible (see: https://www.terraform.io/docs/providers/aws/r/launch_configuration.html#block-devices), and the definition is not the same as that is for `aws_instance` (see: https://www.terraform.io/docs/providers/aws/r/instance.html#block-devices).

I think it should be consistent for both of the cases.

Our team is using that feature in the CloudFormation, and we're trying to migrate to Terraform. It'd be really appreciated if it is implemented.

### New or Affected Resource(s)

* aws_launch_configuration

### Potential Terraform Configuration

```hcl
resource "aws_launch_configuration" "test" {
  ephemeral_block_device {
    device_name = "/dev/sdb"
    no_device = true
  }
```

### References

* https://github.com/hashicorp/terraform/pull/10547

**Comment by catsby** [comment]
Seems reasonable to me! The API/SDK is a bool here instead of a string in the EC2 version, but from a Terraform UX it should be identical.

SDK:

- https://github.com/aws/aws-sdk-go/blob/c0447dbaaf195bb477fd2d511b8e4665e04b9017/service/autoscaling/api.go#L5469

Docs:

- https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_BlockDeviceMapping.html

**Comment by tkbky** [comment]
I got the following error as I try to create a launch configuration with the `ephemeral_block_device`'s `no_device` set to `true`.
```
ValidationError: Cannot specify both ephemeral volume and no-device for block devices.
status code: 400, request id: a77b08d1-c968-11e8-b2ae-1d4f746d4928
```

**Comment by luckymagic7** [comment]
Did you solve your issue?

I met same issue as you.

I don't want to use AMI's default device mapping, but there's no way to do it.

The only way is to recreate the new AMI..

Why Hashicorp guys don't fix it?

**Comment by jeet-parekh** [comment]
Is the `no_device` attribute supposed to be added? If yes, I could work on this.
