### ISSUE TITLE
Allow setting Host Name in route53 healthcheck

### ISSUE THREAD

**Issue by russellwstanley** [hashicorp/terraform-provider-aws#5547]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

The AWS route53 healthcheck allows you to set a Host Name parameter that is passed as the value of the Host header (see https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/health-checks-creating-values.html#health-checks-creating-values-host-name). However I don't see this option as part of the terraform aws_route53_healthcheck resource https://www.terraform.io/docs/providers/aws/r/route53_health_check.html

This is particularly useful if you have resources that are served by some sort of reverse proxy that uses virtual hosting (eg nginx) and you want a healthcheck for each virtual host. 

I'm happy to have a go at this if someone could offer a little guidance. 

Many thanks in advance. 

### New or Affected Resource(s)

* aws_route53_healthcheck

### Potential Terraform Configuration

```hcl
resource "aws_route53_health_check" "example" {
  ip              = "1.2.3.4"
  port              = 80
  host_name = "example.com"
  type              = "HTTP"
  resource_path     = "/healthcheck"
  failure_threshold = "5"
  request_interval  = "30"

}
```

### References

* #0000

**Comment by jonjohnston** [comment]
A year has passed and this feature still isn't implemented in terraform? Seems like a basic minor change to me. Can this please be implemented?
