### ISSUE TITLE
AWS STS GetCallerIdentity calls timeout in v1.31.0

### ISSUE THREAD

**Issue by jdnlab** [hashicorp/terraform-provider-aws#5562]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform: v0.10.4
Terraform Provider (AWS): v1.31.0
```
### Affected Resource(s)

N/A

### Terraform Configuration Files

```hcl
data "aws_s3_bucket" "testbucket" {
  bucket = "corp-test-1"
}

resource "aws_s3_bucket_policy" "testbucket" {
  bucket = "${data.aws_s3_bucket.testbucket.id}"
  policy  =<<POLICY
{
    "Version": "2012-10-17"
    "Statement": [
      {
         "Sid": "DelegateS3Access",
         "Effect": "Allow"
         "Principal": {"AWS": "123456789"},
         "Action": ["s3:ListBucket","s3:GetObject"],
         "Resource": [
             "arn:aws:s3:::randombucket1/*",
             "arn:aws:s3:::randombucket1"
          ]
      }
   ]
}
POLICY
}
```

### Debug Output

https://gist.github.com/james-daniel/0c66c60c9b1a5e95dc52fb8abd793ccd

### Panic Output

N/A

### Expected Behavior

`terraform plan` should execute with a non-zero exit code.

### Actual Behavior

`terraform plan` hangs. Upon further investigation with TF_LOG=1, it occurs that AWS STS GetCallerIdentity requests fail to send, supposedly due to a POST with an oversized TLS "record" when attempting to connect to our corporate proxy infrastructure.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

* Corporate proxy infrastructure is functional and a non-issue. 
* HTTP/HTTPS environment variables set and functional.
* AWS environment variables set and functional.
* STS credentials are valid and functional.
* This issue does not occur with v1.27.0. This was verified by removing v1.31.0 and moving in v1.27.0 in its replacement.

### References

**Comment by txu0393** [comment]
Ran into the same issue in 1.45.0
Downgrading to 1.27.0 fixes my issue as well
