### ISSUE TITLE
Can't create aws_elasticache_replication_group with aws_elasticache_clusters  when Redis cluster mode disabled

### ISSUE THREAD

**Issue by TheCloudlessSky** [hashicorp/terraform-provider-aws#5590]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.aws v1.32.0
+ provider.random v1.1.0

### Affected Resource(s)

* aws_elasticache_replication_group
* aws_elasticache_cluster

### Terraform Configuration Files

```hcl
resource "aws_elasticache_replication_group" "test_redis" {
  replication_group_id = "test-redis"
  engine = "redis"
  engine_version = "2.8.23"
  node_type = "cache.m3.medium"
  port = 6379
  subnet_group_name = "test"
  security_group_ids = ["sg-..."]
  automatic_failover_enabled = true
  parameter_group_name = "default.redis2.8"
  at_rest_encryption_enabled = false
  transit_encryption_enabled = false
  maintenance_window = "sun:06:00-sun:07:00"
  auto_minor_version_upgrade = false
  snapshot_retention_limit = 15 # Days.
  snapshot_window = "05:00-06:00"
  apply_immediately = true
  number_cache_clusters = 2
  lifecycle {
    ignore_changes = ["number_cache_clusters"]
  }
}

resource "aws_elasticache_cluster" "test_redis_001" {
  cluster_id = "test-redis-001"
  replication_group_id = "${aws_elasticache_replication_group.test_redis.id}"
  apply_immediately = true
}

resource "aws_elasticache_cluster" "test_redis_002" {
  cluster_id = "test-redis-002"
  replication_group_id = "${aws_elasticache_replication_group.test_redis.id}"
  apply_immediately = true
}
```

### Expected Behavior

A ElastiCache replication group with 2 nodes should be created.

### Actual Behavior

The ElastiCache replication group is created with 2 nodes/clusters but once Terraform tries to create the 2 clusters defined in the configuration, I get this error:

```
Error: Error applying plan:

2 error(s) occurred:

* aws_elasticache_cluster.test_redis_002: 1 error(s) occurred:

* aws_elasticache_cluster.test_redis_002: error creating Elasticache Cache Cluster: CacheClusterAlreadyExists: Cache cluster already exists
        status code: 400, request id: 815cfce9-a223-11e8-8128-fb26d2d1718d
* aws_elasticache_cluster.test_redis_001: 1 error(s) occurred:

* aws_elasticache_cluster.test_redis_001: error creating Elasticache Cache Cluster: CacheClusterAlreadyExists: Cache cluster already exists
        status code: 400, request id: 815c12dd-a223-11e8-bdb2-af9b03e2c5d7

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
````

Am I missing something from setting this up via Terraform? It seems like because `number_cache_clusters` is set, AWS is automatically creating the cache clusters without involvement of Terraform thus causing the error.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I can't *only* use `number_cache_clusters` because I need to be able to add/destroy specific nodes. For example, Amazon has requested that a specific node/cluster of our production infrastructure needs to be destroyed because of maintenance.

### References

- I was trying to recreate my Redis infrastructure without an availability zone set while testing #5579.

**Comment by RulerOf** [comment]
I've just run into the same problem.  I was trying to perform manual maintenance on a two-node redis cluster by doing the following steps:

* Disable Multi-AZ
* Delete the replica cache cluster
* Re-apply my terraform to recreate the replica node
* Re-disable Multi-AZ
* Promote the replica to primary
* Delete the remaining replica
* Re-apply terraform to recreate the last node
^^^ This finaly step is what failed.

```
04:54 $ terraform apply plan.out 
module.nginx-redis.aws_elasticache_replication_group.cache-cluster: Modifying... (ID: prod-nginx-01)
  automatic_failover_enabled: "false" => "true"
  number_cache_clusters:      "1" => "2"
  snapshot_retention_limit:   "0" => "5"

Error: Error applying plan:

1 error(s) occurred:

* module.nginx-redis.aws_elasticache_replication_group.cache-cluster: 1 error(s) occurred:

* aws_elasticache_replication_group.cache-cluster: error creating Elasticache Cache Cluster (adding replica): CacheClusterAlreadyExists: Cache cluster already exists
	status code: 400, request id: 8b67029b-a77b-11e8-a99c-2deb87e4efee

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by estein9825** [comment]
I had the same issue, so I instead had to build it into my creation logic. Below I allow both the creation of a regular cache cluster and a manual one based on what is sent. I have attached it below.
```
resource "aws_elasticache_replication_group" "default" {
  count                         = "${var.enabled == "true" ? 1 : 0}"
  apply_immediately             = "${var.apply_immediately}"
  auth_token                    = "${var.auth_token}"
  replication_group_id          = "${var.replication_group_id == "" ? module.label.id : var.replication_group_id}"
  replication_group_description = "${module.label.id}"
  node_type                     = "${var.instance_type}"

  # if using cluster_mode then ignore number_cache_clusters value
  # had to make complex lookup since we can't do conditionals against null/empty lists
  # and the comparisons must be of the same type of lists
  number_cache_clusters = "${length(var.cluster_mode) > 0 ? 0 : var.number_cache_clusters}"

  port                 = "${var.port}"
  parameter_group_name = "${var.parameter_group_name != "" ? var.parameter_group_name : join("", aws_elasticache_parameter_group.default.*.name)}"

  # when we're specifying our cluster, then we can't designate our availability zones
  # instead, failover will be used across all available zones
  # but in case where don't specify availability zones, we want to instead just provide an empty list
  availability_zones = ["${slice(concat(var.availability_zones,list("")), 0, (var.number_cache_clusters == 0 || length(var.cluster_mode) > 0) ? 1 : var.number_cache_clusters)}"]

  # automatically enable failover if using cluster_mode
  automatic_failover_enabled = "${length(var.cluster_mode) > 0 ? true : var.automatic_failover}"
  subnet_group_name          = "${var.subnet_group_name != "" ? var.subnet_group_name : join("", aws_elasticache_subnet_group.default.*.name)}"

  security_group_ids         = ["${var.security_group_ids}"]
  maintenance_window         = "${var.maintenance_window}"
  snapshot_retention_limit   = "${var.snapshot_retention_limit}"
  snapshot_window            = "${var.snapshot_window}"
  notification_topic_arn     = "${var.notification_topic_arn}"
  engine_version             = "${var.engine_version}"
  at_rest_encryption_enabled = "${var.at_rest_encryption_enabled}"
  transit_encryption_enabled = "${var.transit_encryption_enabled}"
  tags                       = "${module.label.tags}"
  cluster_mode               = "${var.cluster_mode}"
}
```

I then pass in cluster_mode as

```
cluster_mode = [{
  num_node_groups         = 2
  replicas_per_node_group = 3
}]
```

In order to make this work, I also had to pass in

```
parameter = [{
  name  = "cluster-enabled"
  value = "yes"
}]

```

**Comment by yann-soubeyrand** [comment]
Hi!

My understanding of the documentation was that @TheCloudlessSky's configuration should work but I can confirm that it doesn't work for me neither. Should we understand from the documentation that we have to create the primary node (and a potential replica if automatic failover is activated) with aws_elasticache_replication_group and then we can only create additional replicas with aws_elasticache_cluster, taking care of not choosing conflicting names (cluster_id)?

**Comment by gdavison** [comment]
In the initial error report, Terraform is behaving as expected: When the replication group is created, it already has the two cluster nodes, so they do not need to be created separately. While it is possible to add additional cluster nodes using standalone `aws_elasticache_cluster` resources, the error you are seeing is because the default names used by the ElastiCache API and the names you are using are the same, which is why you are seeing the error "CacheClusterAlreadyExists: Cache cluster already exists".

**Comment by TheCloudlessSky** [comment]
@gdavison thanks. This was a trivial example where I believe I missed to show the next step: how can we reference the other `aws_elasticache_cluster` resources if they're transparently being created for the first time? We don't want to have to import after they're created. Does using a data resource work?
