### ISSUE TITLE
aws_autoscaling_group does not respect delete timeout

### ISSUE THREAD

**Issue by marcoreni** [hashicorp/terraform-provider-aws#5650]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform 0.11.7
AWS Provider 1.32.0
### Affected Resource(s)
* aws_autoscaling_group

### Terraform Configuration Files
```hcl
resource "aws_autoscaling_group" "ecs" {
  ...
  timeouts {
    delete = "30m"
  }
}
```

### Expected Behavior
Terraform should wait 30 minutes.

### Actual Behavior
Terraform timed out after 10 minutes.

### Steps to Reproduce
1. Attach a lifecycle hook to ASG that blocks the termination of the instances
2. Make a change on the ASG that causes a delete/create.
3. Wait :)

### References
Reported also here but unrelated: https://github.com/terraform-providers/terraform-provider-aws/issues/3837

**Comment by timm088** [comment]
Still an issue on 0.11.11 with aws provider 1.59.0

**Comment by Porkbutts** [comment]
Any movement on this?

**Comment by fcarvalho-chwy** [comment]
Still an issue on Terraform v0.12.24 with provider.aws v2.70.0. It updates the ASG delete timeout only when another change in ASG happens. If only the timeouts delete change, it doesn't get detected as a change in state and therefore doesn't get updated.
