### ISSUE TITLE
Suppress block devices included in AMIs

### ISSUE THREAD

**Issue by gebn** [hashicorp/terraform-provider-aws#5683]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When launching an EC2 instance, it can sometimes be useful to suppress a (non-root) device included in the AMI's block device mapping. It is currently possible to do this for `ephemeral_block_device`s via the `no_device` argument, but there is no equivalent for `ebs_block_device`s. I would have expected simply omitting this block would avoid creation of the device, but this is not the case.

### New or Affected Resource(s)

* aws_instance

### Potential Terraform Configuration

Suppressing all non-root block devices could be done by omitting all `ebs_block_device` sections, or, for the sake of backwards compatibility:

```hcl
resource "aws_instance" "foo" {
    ...
    ebs_block_device {
        no_device = true
    }
}
```

 Suppressing a single device could be done with 

```hcl
resource "aws_instance" "foo" {
    ...
    ebs_block_device {
        device_name = "/dev/xvdcz"
        no_device = true
    }
}
```

**Comment by dawidmalina** [comment]
I faced exactly the same issue using AWS Backup. Would love to see an option to skip all attached to the AMI volumes except root volume.
