### ISSUE TITLE
Directory Service Shared Directory Support (SharedMicrosoftAD Directory Type)

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#6003]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS recently announced support for cross-account shared Microsoft Active Directory resources: https://aws.amazon.com/about-aws/whats-new/2018/09/aws-directory-service-share-directory-across-accounts-and-vpcs/

To properly support this setup, it looks like we'll need to implement the following:
* (This feature request) Update the `aws_directory_service_directory` resource for `type = "SharedMicrosoftAD"`
* (#6004) Create new resource for sharing directories
* (#6005) Create new resource for accepting directory share requests

### New or Affected Resource(s)

* `aws_directory_service_directory`

### Potential Terraform Configuration

```hcl
# Example implementation, details may change during development
resource "aws_directory_service_directory" "example" {
  # ... other configuration ...

  type = "SharedMicrosoftAD"
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2018/09/aws-directory-service-share-directory-across-accounts-and-vpcs/
* #6002

**Comment by Tensho** [comment]
I'd like to work on this ^_^ However, I found "AWS Organisation" share method impractical because it could be achieved with "Handshake" one without any extra requirements applied, like:
- AD should be in the **master** account
- Organisation trust enabling
Could we start with "Handshake" share method to deliver it as quickly as possible and then add "AWS Organisation"?

Also, I guess it's more appropriate to set share not as a separate type but restrict Microsoft AD type to be shared only and add block configuration for sharing options:
```
resource "aws_directory_service_directory" "example" {
  ...
  share {
    target = "111111111111" # acceptor account id
    notes = "Terraform will care"
  }
  ...
}

resource "aws_directory_service_directory_share_accepter" "example" {
  shared_directory_id = "${aws_directory_service_directory_share.example.shared_directory_id}"
}
```

**Comment by krogon** [comment]
Hi. I was able to implement whole feature of shared AWS Managed MS Directory Service for my purpose. Due to AWS API implementation the solution is a little bit different than the one provided in description.

I need a little time to prepare testing coverage as this is my first contribution.

**Comment by bwallis42** [comment]
@krogon did you finish off this feature? It would be a very useful addition.

**Comment by peterx1986** [comment]
Hi @krogon, that would be great if you can share the work you have already done over AWS Managed MS Directory Service sharing? Thank you.
