### ISSUE TITLE
Directory Service Shared Directory Support (Share Directory Resource)

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#6004]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS recently announced support for cross-account shared Microsoft Active Directory resources: https://aws.amazon.com/about-aws/whats-new/2018/09/aws-directory-service-share-directory-across-accounts-and-vpcs/

To properly support this setup, it looks like we'll need to implement the following:
* (#6003) Update the `aws_directory_service_directory` resource for `type = "SharedMicrosoftAD"`
* (This feature request) Create new resource for sharing directories
* (#6005) Create new resource for accepting directory share requests

### New or Affected Resource(s)

* `aws_directory_service_directory_share`

### Potential Terraform Configuration

```hcl
# Example implementation, details may change during development
resource "aws_directory_service_directory_share" "example" {
  directory_id = "${aws_directory_service_directory.example.id}"
  share_method = "" # ORGANIZATIONS / HANDSHAKE
  share_notes = ""
  share_target = ""
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2018/09/aws-directory-service-share-directory-across-accounts-and-vpcs/
* #6002

**Comment by piotr-mlynarz-projectdrgn** [comment]
Is there any update on this?

**Comment by rkmudunuru** [comment]
Is there any ETA on the implementation of this feature?

**Comment by tmccombs** [comment]
I've started working on a PR to implement this.

**Comment by breathingdust** [comment]
Hi all 👋 Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!
