### ISSUE TITLE
aws_region should be able to pass provider to resources

### ISSUE THREAD

**Issue by Upgreydd** [hashicorp/terraform-provider-aws#6158]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
If you use multiple regions you should be able to bind provider in resources via `aws_region`

### New or Affected Resource(s)
Example:
```
provider "aws" {
  region = "us-east-1"
  alias = "us-east-1"
}

data "aws_region" "ses_region" {
  provider = "aws.us-east-1"
}

resource "aws_ses_domain_identity" "ses_identity" {
  domain = "domain.tld"
  provider = "${data.aws_region.ses_region.provider}"
}

resource "aws_ses_domain_dkim" "ses_domain_dkim" {
  domain = "${aws_ses_domain_identity.ses_identity.domain}"
  provider = "${data.aws_region.ses_region.provider}"
}

resource "aws_ses_domain_identity_verification" "ses_identity_verification" {
  domain = "${aws_ses_domain_identity.ses_identity.id}"
  provider = "${data.aws_region.ses_region.provider}"
}
```
This will allow you to change resource region by changing provider only in `aws_region` data. After that your'e able to use `aws_data` in other places where you need to get SES resource region.

At this moment provider need to be "aws" or "aws.alias" so each resource depends directly on module instead of defined data.

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by brunzefb** [comment]
Hi,

I'm running into the same issue -- my script works in region us-east-1 (which has ses) but fails in us-west-1 which has no ses service.
@Upgreydd I think your proposal for the syntax is perfect!

Friedrich
