### ISSUE TITLE
aws_elasticache_replication_group always recreates when changing replicas_per_node_group

### ISSUE THREAD

**Issue by varknull** [hashicorp/terraform-provider-aws#6184]
When a `aws_elasticache_replication_group` uses cluster mode and the `replicas_per_node_group` changes, the resource will recreate.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform version
```
$ terraform version
Terraform v0.11.8
+ provider.aws v1.40.0
```

### Affected Resource(s)

* `aws_elasticache_replication_group`

### Terraform Configuration

```hcl
resource "aws_elasticache_replication_group" "redis-rg" {
  replication_group_id          = "${var.replication_group_id}"
  replication_group_description = "ElastiCache replication group for ${var.redis_cluster_id}"
  node_type                     = "${var.redis_node_type}"
  automatic_failover_enabled    = "true"
  engine                        = "redis"
  engine_version                = "${var.redis_version}"
  port                          = "${var.redis_port}"
  at_rest_encryption_enabled    = "${var.at_rest_encryption_enabled}"
  transit_encryption_enabled    = "${var.transit_encryption_enabled}"
  auth_token                    = "${var.auth_token}"

  cluster_mode {
    num_node_groups             = "${var.redis_shards}"
    replicas_per_node_group     = "${var.redis_replicas}"
  }

 ...
}
```

### Expected Behavior
`terraform plan` should modify the cluster without recreating.

### Steps to Reproduce
1. terraform apply
2. terraform plan

**Comment by gsamarukha-conol** [comment]
According to AWS docs at https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Clusters.Create.CON.RedisCluster.html

>For Replicas per shard, choose the number of read replica nodes you want in each shard.
>The following restrictions exist for Redis (cluster mode enabled).
> * The number of replicas is the same for each shard when creating the cluster using the console.
> * The number of read replicas per shard is fixed and cannot be changed. If you find you need more or fewer replicas per shard (API/CLI: node group), you must create a new cluster with the new number of replicas. For more information, see Seeding a New Cluster with an Externally Created Backup.

So this doesn't seem like something fixable on Terraform side.

**Comment by gdavison** [comment]
Thanks for creating the issue, @varknull. Since this is a limitation of the AWS API, I'm going to close it.

**Comment by gdavison** [comment]
Actually, there is is a pair of API calls that might work for this: [IncreaseReplicaCount](https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_IncreaseReplicaCount.html) and [DecreaseReplicaCount](https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_DecreaseReplicaCount.html).
