### ISSUE TITLE
Add new resource for s3 bucket lifecycle configuration

### ISSUE THREAD

**Issue by cloudyparts** [hashicorp/terraform-provider-aws#6188]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow independent systems manage different parts of an s3 bucket configuration.
System A - manages lifecycle of bucket 
System B - manages lifecycle of bucket lifecycle configuration
Both systems use terraform modules to isolate change scope.

### New or Affected Resource(s)

* aws_s3_bucket (modifies)
* aws_s3_bucket_lifecycle_configuration (new)

### Potential Terraform Configuration

```hcl
resource "aws_s3_bucket" "b" {
  bucket = "my-tf-test-bucket"
  acl    = "private"

  tags {
    Name        = "My Bucket"
    Environment = "Dev"
  }
}

resource "aws_s3_bucket_lifecycle_configuration" {
  bucket = "${aws_s3_bucket.b.id}"

  rule  {
    id      = "log"
    enabled = true
    prefix  = "log/"

    tags {
      "rule"      = "log"
      "autoclean" = "true"
    }

    transition {
      days          = 15
      storage_class = "ONEZONE_IA"
    }

    transition {
      days          = 30
      storage_class = "STANDARD_IA"
    }

    transition {
      days          = 60
      storage_class = "GLACIER"
    }

    expiration {
      days = 90
    }
  }

  rule {
    id      = "tmp"
    prefix  = "tmp/"
    enabled = true

    expiration {
      date = "2016-01-12"
    }
  }
}


```

### References

* [hashicorp/terraform/3116](https://github.com/hashicorp/terraform/issues/3116) - possibly related implications
* #4418
* #1704

**Comment by zaphar** [comment]
Would this make more sense as an addition to the aws_s3_bucket_object resource? That is an already existing location that would make sense to attach lifecycle rules to and is already composable within the existing terraform s3 resources

**Comment by zaphar** [comment]
Has there been any movement on this? The lack of this feature is actually causing me to consider using a different tool for s3 provisioning.

**Comment by CYDX-nuna** [comment]
I would like to see this as well. It's making my life *very* complicated right now.

**Comment by realsby** [comment]
Yes I need this ass well

**Comment by adamrothman** [comment]
Another vote for this feature.

**Comment by pspot2** [comment]
Another vote

**Comment by mohanrajpac** [comment]
+1

**Comment by developerinlondon** [comment]
+1

**Comment by AchuthSankar** [comment]
+1

**Comment by shahnarendra4u** [comment]
+1, this is helpful, if we have a module for S3 and if we need to extend. 

As of now as this does not exist, have to use custom resources for same and add lifecycle policy

**Comment by pspot2** [comment]
Noticed that this already exists for S3 on Outposts: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3control_bucket_lifecycle_configuration

**Comment by pspot2** [comment]
https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md#research-topics
