### ISSUE TITLE
aws_eip.nameofmyeip.1: Failure associating EIP: IncorrectInstanceState: The pending-volume-availability instance to which 'eni-XXXXXXXXXXXXXXX' is attached is not in a valid state for this operation

### ISSUE THREAD

**Issue by devoops13** [hashicorp/terraform-provider-aws#6189]
terraform -v
Terraform v0.11.8

here is a simplified config to make it easier to read

running terraform twice fix the initial issue.

### elastic ip

resource "aws_eip" "nameofmyeip" {
  count = "${var.something_count}"
  vpc = true
  network_interface = "${element(aws_network_interface.somenic.*.id, count.index)}"
  depends_on = ["aws_internet_gateway.internet_gateway"]
}

### network interface

resource "aws_network_interface" "somenic" {
  count           = "${var.something_count}"
  subnet_id       = "${aws_subnet.subnet.0.id}"
  description     = "somenic0${count.index}"
  security_groups = ["${aws_security_group.blah.id}", "${aws_security_group.bleh.id}", "${aws_security_group.blop.id}"]
}

### ec2 instance

resource "aws_instance" "somemachine" {
  count                       = "${var.something_count}"

  ami                         = "${var.ubuntu16_ami}"
  instance_type               = "${var.some_instance_type}"
  key_name                    = "${aws_key_pair.terragrunt_key_pair.id}"
  iam_instance_profile        = "${aws_iam_instance_profile.a_profile.name}"
  user_data                   = "${data.template_file.chef_user_data_a.rendered}"
  ebs_optimized               = true
  root_block_device           = [ {
                                     volume_size = 100
                                     volume_type = "gp2"
                                } ]

  network_interface {
    network_interface_id = "${element(aws_network_interface.somenic.*.id, count.index)}"
    device_index = 0
  }

}

**Comment by rene00** [comment]
I started seeing this too recently with a similar terraform config like the one posted. Fix was to use `depends_on` and reference the `aws_instance`:

```
resource "aws_eip" "foo" {
   [...]
   depends_on = ["aws_instance.foo"]
}
```

I suspect another solution, which I haven't tested, could be not to use `aws_network_interface` and just associate `aws_eip` to the instance or it's `private_ip`. Examples can be found at https://www.terraform.io/docs/providers/aws/r/eip.html.

**Comment by devoops13** [comment]
still seeing the issue 

###EIP
```resource "aws_eip" "bastion" {
  vpc               = true
  network_interface = "${element(aws_network_interface.bastion_reserved_nic.*.id, count.index)}"
  depends_on        = ["aws_internet_gateway.internet_gateway"]
  depends_on        = ["aws_instance.bastion.id"]
}```


###EC2
```resource "aws_instance" "bastion" {
  count                       = 1
  #ami                        = "TODO: bastion image"
  ami                         = "${var.ami}"
  #instance_type              = "TODO: TBD bastion instance type"
  instance_type               = "${var.bsa_instance_type}"
  key_name                    = "${aws_key_pair.terragrunt_key_pair.id}"
  iam_instance_profile        = "${aws_iam_instance_profile.bastion_profile2.name}"
#  user_data                   = "${data.template_file.chef_user_data_bsa.rendered}"
  monitoring                  = false
  ebs_optimized               = true
#  associate_public_ip_address = true
#  subnet_id                   = "${aws_subnet.subnet.0.id}"
#  vpc_security_group_ids      = [ "${aws_security_group.allow_office.id}", "${aws_security_group.bastion.id}" ]
  root_block_device           = [ {
                                     volume_size = 100
                                     volume_type = "gp2"
                                } ]
  network_interface {
    network_interface_id = "${aws_network_interface.bastion_reserved_nic.id}"
    device_index = 0
  }
  volume_tags = {
      root_block_device  = "/dev/sda1"
  }

  tags                        = {
    Name                      = "bastion"
    Terraform                 = "true"
    Environment               = "${var.env}"
                App                                                                                             = "${var.app}"
                Region                                                                          = "${var.region}"
    Organisation              = "${var.org}"
    Build                     = "${var.build}"
  }

}```

**Comment by devoops13** [comment]
this issue occurs sporadically, some deploy will go without it, for some, it will affect only one ip/nic/ec2/volume and sometimes, 3 ip/nic/ec2/volume
