### ISSUE TITLE
Allow setting custom domain for click/open tracking as part of SES Event destination resource

### ISSUE THREAD

**Issue by nirojan** [hashicorp/terraform-provider-aws#6339]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS SES allows the use of custom domain for email open and link click tracking instead of AWS's own domain (random-subdomain.awstrack.me). This is set as part of setting up event destination resource (aws_ses_event_destination) as an additional parameter. Terraform at the moment doesn't support setting this variable but it would be good if it does.

### New or Affected Resource(s)

*  aws_ses_event_destination 

### Potential Terraform Configuration

```hcl

resource "aws_route53_record" "domain_verification" {
  zone_id = "${aws_route53_zone.domain.zone_id}"
  name    = "click.example.com"
  type    = "CNAME"
  ttl     = "3600"
  records = ["r.eu-west-1.awstrack.me"]
}

resource "aws_ses_configuration_set" "config-set" {
  name = "ses-events-cloudwatch"
}

resource "aws_ses_event_destination" "cloudwatch" {
  name                   = "event-destination-cloudwatch"
  configuration_set_name = "${aws_ses_configuration_set.config-set.name}"
  enabled                = true
  matching_types         = ["open", "click"]

/* Setting the custom domain for open/click tracking.
The domain has to be a verified domain identity or subdomain of an existing verified domain */

  domain = "click.example.com"

  cloudwatch_destination = {
    default_value  = "default"
    dimension_name = "ses-events"
    value_source   = "emailHeader"
  }
}
```

### References

* https://docs.aws.amazon.com/ses/latest/DeveloperGuide/configure-custom-open-click-domains.html
* https://www.terraform.io/docs/providers/aws/r/ses_event_destination.html

**Comment by punitrathore** [comment]
👍

**Comment by manishapme** [comment]
👍

**Comment by vukomir** [comment]
any update on this? :)

**Comment by marns93** [comment]
Are there any updates? :)

**Comment by borfig** [comment]
Actually, API-wise, the configuration set tracking options are a separate resource that depends on the configuration set:
- Creation: https://docs.aws.amazon.com/ses/latest/APIReference/API_CreateConfigurationSetTrackingOptions.html
- Update: https://docs.aws.amazon.com/ses/latest/APIReference/API_UpdateConfigurationSetTrackingOptions.html
- Delete: https://docs.aws.amazon.com/ses/latest/APIReference/API_DeleteConfigurationSetTrackingOptions.html

However, viewing the current state is describing the configuration set and asking for the tracking options: https://docs.aws.amazon.com/ses/latest/APIReference/API_DescribeConfigurationSet.html

**Comment by brunocalogero** [comment]
Any update on this?

**Comment by brunocalogero** [comment]
So @safinn and I opened a draft pull request for this, it's still in its infancy (need to add tests and probably some more documentation), make sure to thumbs up the PR for prioritisation :)
