### ISSUE TITLE
Apply Filters to Data Source ALB

### ISSUE THREAD

**Issue by danilogomesrosa** [hashicorp/terraform-provider-aws#6353]
Hi there,

It seems it is not possible to filter names in the data source Target Group using regular expressions so far.

I can see in the [documentation](https://www.terraform.io/docs/providers/aws/d/lb_target_group.html) we can currently only use the arguments "name" and "arn" but I can not apply a regex filter such as I do in aws_ami, filtering for Target Groups containing "*prod*" in his name, for example.

I was wondering if it possible to add this feature in a next roadmap.

Thank you.

**Comment by bflad** [comment]
The [Elastic Load Balancing `DescribeTargetGroups` API](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_DescribeTargetGroups.html) does not natively support this type of filtering (like [EC2 does](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImages.html)). However, it could be handled via the logic in the data source itself. The lack of native API support does not preclude this sort of enhancement from ever happening although we do try to shy away from our own implementations like this. Our recommendation in these cases is typically to reach out to the AWS service team via an AWS Support case or talking with your account managers to request the API be enhanced to include this functionality, where it can be easily included in Terraform, the AWS CLI, and other API clients.
