### ISSUE TITLE
Feature request: Add EC2 BYOIP CIDR resource

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#6521]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

BYOIP support [released](https://aws.amazon.com/about-aws/whats-new/2018/10/announcing-the-general-availability-of-bring-your-own-ip-for-amazon-virtual-private-cloud/).
Add an EC2 BYOIP CIDR resource (and maybe an EC2 Public IPv4 Pool data source).

Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/6251

**Comment by zenvdeluca** [comment]
I'd love to manage the CIDR resource pool through HCL code.  +1 here

**Comment by ewbankkit** [comment]
@zenvdeluca Would you be able to test this functionality if added?

**Comment by ewbankkit** [comment]
Now with IPv6 support:
* [Announcement](https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-virtual-private-cloud-supports-bring-own-ipv6-addresses/)

**Comment by gerricchaplin** [comment]
@ewbankkit I am happy to test this should you require someone to perform testing. I have both IPv4 and IPv6 available for testing purposes.
