### ISSUE TITLE
timeout_in_minutes values for aws_cloudformation_stack > 30 minutes are not working.

### ISSUE THREAD

**Issue by queglay** [hashicorp/terraform-provider-aws#6641]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.10

### Affected Resource(s)

aws_cloudformation_stack

### Terraform Configuration Files

if you attempt to deploy something like this microsoft AD, it will take 40 mins + to deploy.  with terraform it will time out and custom timeout values are ignored
https://docs.aws.amazon.com/quickstart/latest/active-directory-ds/scenario-1.html

I created my own fork of this AD stack above, and it works fine with cloudformation, but as soon as I use terraform, it will timeout at 30 minutes.  I have attempted to set timeout_in_minutes as an int - 
  timeout_in_minutes = 60
and as a string-
  timeout_in_minutes = "60"

...but without success or any change in behaviour.  it appears to make no difference and will always timeout at 30 minutes.

it is also unclear in the documentation as to what formatting the value requires (string or int?), I've only been using terraform for a couple of days but I think it would help to define the type required.
https://www.terraform.io/docs/providers/aws/r/cloudformation_stack.html

Here is an example template, you can replace my own s3 fork and parameters with the aws template or any template that takes longer than 30 mins.

resource "aws_cloudformation_stack" "ADStack" {
  name               = "ADStack"
  capabilities       = ["CAPABILITY_IAM"]
  timeout_in_minutes = 60

  parameters = {
    ADServer1InstanceType = "${var.ADServer1InstanceType}"
    ADServer1NetBIOSName  = "${var.ADServer1NetBIOSName}"
    ADServer1PrivateIP    = "${var.ADServer1PrivateIP}"
    ADServer2InstanceType = "${var.ADServer2InstanceType}"
    ADServer2NetBIOSName  = "${var.ADServer2NetBIOSName}"
    ADServer2PrivateIP    = "${var.ADServer2PrivateIP}"
    DomainAdminPassword   = "${var.DomainAdminPassword}"
    DomainAdminUser       = "${var.DomainAdminUser}"
    DomainDNSName         = "${var.DomainDNSName}"
    DomainNetBIOSName     = "${var.DomainNetBIOSName}"
    KeyPairName           = "${var.KeyPairName}"
    NumberOfAZs           = "${var.NumberOfAZs}"
    PrivateSubnet1CIDR    = "${var.PrivateSubnet1CIDR}"
    PrivateSubnet1ID      = "${var.PrivateSubnet1ID}"
    PrivateSubnet2CIDR    = "${var.PrivateSubnet2CIDR}"
    PrivateSubnet2ID      = "${var.PrivateSubnet2ID}"
    PrivateSubnet3CIDR    = "${var.PrivateSubnet3CIDR}"
    PublicSubnet1CIDR     = "${var.PublicSubnet1CIDR}"
    PublicSubnet2CIDR     = "${var.PublicSubnet2CIDR}"
    PublicSubnet3CIDR     = "${var.PublicSubnet3CIDR}"
    QSS3BucketName        = "${var.QSS3BucketName}"
    QSS3KeyPrefix         = "${var.QSS3KeyPrefix}"
    RestoreModePassword   = "${var.RestoreModePassword}"
    VPCCIDR               = "${var.VPCCIDR}"
    VPCID                 = "${var.VPCID}"
  }

  template_url = "https://s3-ap-southeast-2.amazonaws.com/firehawk-ad/firehawk-active-directory/templates/ad-1.template"
}

### Expected Behavior

timeout_in_minutes should be respected,

### Actual Behavior

timeout_in_minutes is ignored.

### Steps to Reproduce

take a cloudformation template that takes >30 mins to apply.  set a non default timeout_in_minutes value >30 mins.  it will timeout at 30 minutes and not respect the value you have entered.

**Comment by queglay** [comment]
I've created a public repo that demonstrates this issue I'm having with setting the aws_cloudformation_stack timeout_in_minutes.

https://github.com/firehawkvfx/terraform-quickstart-microsoft-activedirectory/blob/master/terraform/modules/ad-master-1/main.tf

In the module that launches the cloudformation stack we have set-
timeout_in_minutes = "60"

...but the cloudformation stack will timeout in 30 minutes, regardless of what value this parameter is set to.

I'm unclear if this is a bug or user error, but it should be reproducable by cloning the repo here-
https://github.com/firehawkvfx/terraform-quickstart-microsoft-activedirectory

I get timeouts at 30m0s everytime.  I have an example log below-




module.ad-master-1.aws_cloudformation_stack.ADStack: Still creating... (29m10s elapsed)
module.ad-master-1.aws_cloudformation_stack.ADStack: Still creating... (29m20s elapsed)
module.ad-master-1.aws_cloudformation_stack.ADStack: Still creating... (29m30s elapsed)
module.ad-master-1.aws_cloudformation_stack.ADStack: Still creating... (29m40s elapsed)
module.ad-master-1.aws_cloudformation_stack.ADStack: Still creating... (29m50s elapsed)
module.ad-master-1.aws_cloudformation_stack.ADStack: Still creating... (30m0s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* module.ad-master-1.aws_cloudformation_stack.ADStack: 1 error(s) occurred:

* aws_cloudformation_stack.ADStack: timeout while waiting for state to become 'CREATE_COMPLETE, CREATE_FAILED, DELETE_COMPLETE, DELETE_FAILED, ROLLBACK_COMPLETE, ROLLBACK_FAILED' (last state: 'CREATE_IN_PROGRESS', timeout: 30m0s)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by anitianswartz** [comment]
Same issue in Terraform v.0.11.11 (Same quickstart stack, even!)
It actually gets the timeout value too, when it creates:
```
module.active-directory.aws_cloudformation_stack.active-directory: Creating...
...
  template_body:                         "" => "<computed>"
...
  timeout_in_minutes:                    "" => "60"
module.active-directory.aws_cloudformation_stack.active-directory: Still creating... (10s elapsed)
...
* module.active-directory.aws_cloudformation_stack.active-directory: 1 error(s) occurred:

* aws_cloudformation_stack.active-directory: timeout while waiting for state to become 'CREATE_COMPLETE, CREATE_FAILED, DELETE_COMPLETE, DELETE_FAILED, ROLLBACK_COMPLETE, ROLLBACK_FAILED' (last state: 'CREATE_IN_PROGRESS', timeout: 30m0s)
```

Fortunately, I was able to get the desired behavior using the `timeouts` property:
```
-  timeout_in_minutes = 60
+  timeouts {
+    create = "60m"
+  }
```

```
module.active-directory.aws_cloudformation_stack.active-directory: Still creating... (35m1s elapsed)
module.active-directory.aws_cloudformation_stack.active-directory: Creation complete after 35m10s (ID: arn:aws:cloudformation:...)
```

**Comment by queglay** [comment]
that seems odd that we have two options for this.  should one potentially be removed as a suggestion for future changes?

**Comment by bflad** [comment]
Hi folks 👋 Sorry for any confusion here. It seems we could improve our documentation here.

The [CloudFormation API](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html) includes the `TimeoutInMinutes` parameter (`timeout_in_minutes` in Terraform) to automatically trigger stack rollback. This differs from the [Terraform resource `timeouts` meta configuration block](https://www.terraform.io/docs/configuration/resources.html#operation-timeouts), which influences how long Terraform itself waits for operations to finish in certain resources, but in the case of the `aws_cloudformation_stack` resource it does not trigger rollback.
