### ISSUE TITLE
ECS Cluster ARN vs. Cluster Name Forces Service Destroy/Create

### ISSUE THREAD

**Issue by reedflinch** [hashicorp/terraform-provider-aws#6695]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.11.10
```

### Affected Resource(s)

* aws_ecs_service

### Terraform Configuration Files

```hcl
resource "aws_ecs_service" "service1" {
  name            = "service1"
  cluster         = "${data.aws_ecs_cluster.test.cluster_name}"
}
```

...vs...

```hcl
resource "aws_ecs_service" "service2" {
  name            = "service2"
  cluster         = "${data.aws_ecs_cluster.test.arn}"
}
```

### Expected Behavior

`No changes. Infrastructure is up-to-date.`

I want Terraform to avoid recreating my ECS service, a fairly disruptive action, when the associated cluster would not change. 

### Actual Behavior

```
-/+ module.test.module.service.aws_ecs_service.service1 (new resource required)
      cluster:                            "test" => "arn:aws:ecs:us-east-1:<accountid>:cluster/test" (forces new resource)
```

...or...

```
-/+ module.test.module.service.aws_ecs_service.service2 (new resource required)
      cluster:                            "arn:aws:ecs:us-east-1:<accountid>:cluster/test" => "test" (forces new resource)
```

### Steps to Reproduce

1. Have an ECS service with a `cluster` value of the `cluster_name`:

```
$ terraform state show module.test.module.service.aws_ecs_service.service1
id                                 = arn:aws:ecs:us-east-1:<accountid>:service/service1
cluster                            = test
```

2. `terraform plan`

3. Terraform wants to recreate the service because it expects the cluster ARN.

OR

1. Have an ECS service with a `cluster` value of `arn`:

```
$ terraform state show module.test.module.service.aws_ecs_service.service2
id                                 = arn:aws:ecs:us-east-1:<accountid>:service/service2
cluster                            = arn:aws:ecs:us-east-1:<accountid>:cluster/test
```

2. `terraform plan`

3. Terraform wants to recreate the service because it expects the cluster name/ID.

### Important Factoids

The ECS docs for [CreateService](https://docs.aws.amazon.com/sdk-for-go/api/service/ecs/#CreateServiceInput) and [UpdateService](https://docs.aws.amazon.com/sdk-for-go/api/service/ecs/#UpdateServiceInput), in regards to the `Cluster` attribute, state:

> The short name or full Amazon Resource Name (ARN) of the cluster that your service is running on.

This is how I had assumed the provider had operated: it accepted either the cluster's short name or ARN.

I understand that _technically_ there is a diff that Terraform recognizes, so I understand why this issue is happening. My problem is that I don't know _which_ value for the cluster is going to be in a given service -- the short name or the ARN -- and frankly, I don't care that much. 

This problem makes using modules for our ECS services very difficult.

**Comment by bflad** [comment]
@reedflinch quick question: Is the difference you are seeing affected by new clusters/services in AWS accounts with the [longer ARN format enabled](https://aws.amazon.com/blogs/compute/migrating-your-amazon-ecs-deployment-to-the-new-arn-and-resource-id-format-2/)?

**Comment by reedflinch** [comment]
@bflad thanks for the quick response! No, that should not be the case.

1. These are relatively "old" (1 - 2 years) services
2. I have not yet opted in to the longer ARN format in this AWS account

**Comment by bflad** [comment]
If someone is interested in developing this feature request, it can likely be done by adding a  `DiffSuppressFunc` on the `aws_ecs_service` resource `name` argument that extracts the cluster name from the ARN if present (in either old or new) for comparison.
