### ISSUE TITLE
aws_autoscaling_schedule is often not actually created and apply must be run again

### ISSUE THREAD

**Issue by samjgalbraith** [hashicorp/terraform-provider-aws#6717]
When I perform a change that requires my autoscaling groups to be replaced, the replacement scheduled actions must also be created after the new autoscaling group. It seems that at random (but more often than not) not all of the scheduled actions are successfully created, although terraform apply finishes successfully as if they were. It's required to keep running Terraform apply until there are no changes to make. Adding a sleep provisioner of 30 seconds or less (I haven't tried longer) to the autoscaling group does not seem to solve the issue.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8
+ provider.aws v1.49.0

### Affected Resource(s)

aws_autoscaling_schedule

### Terraform Configuration Files

```hcl
resource "aws_alb_target_group" "service_v2" {
  name = "${var.service_name_short}-${var.environment_name}-${replace(timestamp(),":","")}"
  port = 443
  protocol = "HTTPS"
  vpc_id = "${var.vpc_id}"
  deregistration_delay = 10
  tags = "${local.all_tags}"
  health_check {
    path = "${var.health_check_path}"
    protocol = "HTTPS"
    matcher = "200"
    interval = 10
  }
  lifecycle {
    create_before_destroy = true
    ignore_changes = ["name"]
  }
}

resource "aws_autoscaling_group" "service" {
  vpc_zone_identifier = ["${var.private_subnet_ids}"]
  # This will force the creation of a new auto scaling group when the associated launch configuration is changed.
  # That should then force the replacement of instances
  name_prefix = "${aws_launch_configuration.service_ec2_instance_on_demand.name_prefix}"
  launch_configuration = "${aws_launch_configuration.service_ec2_instance_on_demand.id}"
  min_elb_capacity = "${var.min_in_service_instances}"
  wait_for_capacity_timeout = "${max(var.health_check_grace_period_seconds, 1200)}s"

  min_size = "${var.min_in_service_instances}"
  desired_capacity = "${var.initial_instance_count}"  # Set it to this initially. Changes in this value will be ignored, as below.
  max_size = "${var.max_instances}"
  target_group_arns = ["${aws_alb_target_group.service_v2.arn}"]
  tags = ["${data.null_data_source.autoscaling_group_tags.*.outputs}"]
  lifecycle {
    create_before_destroy = true  # We want a new autoscaling group to come up before we get rid of the old one.
    ignore_changes = ["desired_capacity"] # This is going to be changed dynamically, so don't blast over it.
  }

  # Sleep to help avoid race conditions.
  provisioner "local-exec" {
    interpreter = ["bash", "-c"]
    command = "sleep 30"
  }
}

resource "aws_autoscaling_schedule" "service_instances_teardown" {
  count = "${var.teardown_schedule_cron == "" ? 0 : 1}"
  scheduled_action_name = "teardown"
  autoscaling_group_name = "${aws_autoscaling_group.service.name}"
  recurrence = "${var.teardown_schedule_cron}"

  min_size = 0
  desired_capacity = 0
  max_size = -1
}

resource "aws_autoscaling_schedule" "service_instances_startup" {
  count = "${var.startup_schedule_cron == "" ? 0 : 1}"
  scheduled_action_name = "startup"
  autoscaling_group_name = "${aws_autoscaling_group.service.name}"
  recurrence = "${var.startup_schedule_cron}"

  min_size = "${var.min_in_service_instances}"
  desired_capacity = "${var.initial_instance_count}"
  max_size = -1

  lifecycle {
    ignore_changes = ["desired_capacity"]   # We'll be manipulating this directly to the desired value.
  }
}

```

### Expected Behavior

When var.startup_schedule_cron is provided, whenever the autoscaling group is created or replaced the two scheduled actions are both created.

### Actual Behavior

Not all scheduled actions are created on apply where there is an autoscaling group replaced. Rerunning apply is usually required to create all scheduled actions.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tomelliff** [comment]
Can you show the plan output when it's being changed?
