### ISSUE TITLE
State gets lost on when changing the region in the aws provider

### ISSUE THREAD

**Issue by volker-fr** [hashicorp/terraform-provider-aws#6731]
### Terraform Version

* Terraform v0.11.10
* provider.aws: version = "~> 1.50"

### Affected Resource(s)

* aws_lambda_function

### Terraform Configuration Files

```hcl
provider "aws" {
  # Region gets changed to trigger the unexpected outcome
  region = "us-east-1" 
}

....

resource "aws_lambda_function" "functionname" {
  filename         = "filename.zip"
  function_name    = "functioname"
  description      = "Description"
  role             = "${aws_iam_role.rolename.arn}"
  handler          = "filename.lambda_handler"
  source_code_hash = "${data.archive_file.package_code_for_lambda.output_base64sha256}"
  runtime          = "python3.6"
}
```

### Expected Behavior

I expected that the region gets stored in the statefile and not overwritten or lost in some ways.

Therefore I expected one of the following two outcomes:

1. us-east-1 resource gets deleted on the 2nd run (resource name stays, region changes)
2. us-east-1 resources gets deleted on the 3rd run (resources are stored in combination of region)

### Actual Behavior

State of lambda function in a region is lost. The resource in us-east-1 is no longer managed by Terraform.

### Steps to Reproduce

Resources in AWS from the beginning:
1. us-east-1: None
2. us-west-2: None

#### First run
```
provider "aws" {
  region = "us-east-1"
}
...
```
terraform init & terraform apply

Resources in AWS after the run
1. us-east-1: Lambda function `functionname`
2. us-west-2: None

#### Second run:
```
provider "aws" {
  region = "us-west-2"
}
```
terraform init & terraform apply

Resources in AWS after the run
1. us-east-1: Lambda function `functionname`
2. us-west-2:  Lambda function `functionname`

#### Third run:
```
provider "aws" {
  region = "us-east-1"
}
```
terraform init & terraform destroy

Resources in AWS after the run
1. us-east-1: Lambda function `functionname`
2. us-west-2:  Lambda function `functionname`

### Workaround / discussion

I am aware that you can use multiple aws providers and reference them through their alias. This is probably the way to go.
Alternatively have a region-specific variable for the state file key/file/folder.

Yet the result of loosing the state is unexpected and I only ran into it when switching the region permanently and noticed that the resource still existed in the old region.

**Comment by straubt1** [comment]
I have had the same experience that left me with a bunch of hanging infrastructure.

For posterity, here were my steps:

1. Set AWS provider to us-west-1
```
provider "aws" {
  region = "us-west-1"
}
```
2. `terraform init`
3. Add VPC resource and `terrafform apply` -> (Plan: 1 to add, 0 to change, 0 to destroy.)
4. `terraform plan` -> (No changes. Infrastructure is up-to-date.)
State file shows 1 VPC in state with:
`"arn": "arn:aws:ec2:us-west-1:zzzzzzzzz:vpc/vpc-05c1fzzzzzzzzz",`

5. Update AWS providr to us-west-2
```
provider "aws" {
  region = "us-west-2"
}
```
6. `terraform apply` -> (Plan: 1 to add, 0 to change, 0 to destroy.)
Notice the plan doesn't register anything about the VPC in us-west-1
7. `terraform plan` -> (No changes. Infrastructure is up-to-date.)
State file shows 1 VPC in state with:
`"arn": "arn:aws:ec2:us-west-2:zzzzzzzzz:vpc/vpc-0573bc2zzzzzzzzzzz",`

I now have a state file with 1 VPC in us-west-2 and the VPC in us-west-1 has been removed from state (but not deleted from AWS), leaving me with hanging infrastructure.
