### ISSUE TITLE
data.aws_ecs_task_definition plans changes

### ISSUE THREAD

**Issue by jrobison-sb** [hashicorp/terraform-provider-aws#6793]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
$ terraform -v
Terraform v0.11.8
+ provider.archive v1.0.3
+ provider.aws v1.41.0
+ provider.null v1.0.0
+ provider.template v1.0.0
```

### Affected Resource(s)

* data.aws_ecs_task_definition

### Terraform Configuration Files

```
data "aws_ecs_task_definition" "myapp_sidekiq" {
  depends_on      = ["aws_ecs_task_definition.myapp_sidekiq"]
  task_definition = "${aws_ecs_task_definition.myapp_sidekiq.family}"
}
```

### Expected Behavior

If I run a `terraform plan`, this data source should not introduce any noise significant noise to stdout. And if I run a `terraform plan -detailed-exitcode`, when no changes are needed it should exit 0. The exit code is the thing I care about most, so I can use the exit code to detect configuration drift.

### Actual Behavior

Even when no changes are planned and my infra is synced up to my TF state, this data source introduces unnecessary noise to sdtout, and when run with `-detailed-exitcode` it exits 2.

### Steps to Reproduce

```
$ terraform plan -detailed-exitcode
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
 <= read (data resources)

Terraform will perform the following actions:

 <= module.staging_application.data.aws_ecs_task_definition.myapp_sidekiq
      id:              <computed>
      family:          <computed>
      network_mode:    <computed>
      revision:        <computed>
      status:          <computed>
      task_definition: "staging-myapp-sidekiq"
      task_role_arn:   <computed>


Plan: 0 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

me@my-mbp ~/devops/terraform/mycompany/environments/staging (master) 
$ echo $?
2
```

### Important Factoids

I'm not sure if this is related or not, but I'm consuming this data source in a `aws_ecs_service` resource like this:

```
resource "aws_ecs_service" "myapp_sidekiq" {
  ...
  task_definition = "${aws_ecs_task_definition.myapp_sidekiq.family}:${max("${aws_ecs_task_definition.myapp_sidekiq.revision}", "${data.aws_ecs_task_definition.myapp_sidekiq.revision}")}"
}
```

Though even if the above usage of this data source is related, I wouldn't really call it "wrong", per se, because it's pretty much copy/pasted directly from [the documentation of this data source](https://www.terraform.io/docs/providers/aws/d/ecs_task_definition.html).

**Comment by pikeas** [comment]
Same problem here. It's apparently intended behavior that placing `depends_on` on a data object causes that object to be evaluated at `apply` time, and hence will always be shown as a pending change during a `plan`.

This is problematic when trying to bootstrap the 1st revision of a task definition:

```
resource "aws_ecs_task_definition" "app" {
  container_definitions = "<JSON string>"
  family                = "app"
  network_mode = "bridge"
}

data "aws_ecs_task_definition" "app" {
  task_definition = "${aws_ecs_task_definition.app.family}"
  depends_on      = ["aws_ecs_task_definition.main"]

resource "aws_ecs_service" "app" {
  task_definition = "${data.aws_ecs_task_definition.main.family}"
  ...<other settings not relevant here>
```

The above works *almost* perfectly - it works when the task definition does not exist, and when it does. But, as noted above, the catch is that the data source will be flagged as changed on every future `plan`.
