### ISSUE TITLE
Unexpected nil pointer when elasticache node is still being created

### ISSUE THREAD

**Issue by querry43** [hashicorp/terraform-provider-aws#6795]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.10
+ provider.aws v1.38.0
+ provider.template v1.0.0
### Affected Resource(s)

* aws_elasticache_cluster

### Terraform Configuration Files

```hcl
resource "aws_elasticache_cluster" "memcached_cluster" {
  cluster_id = "${terraform.workspace}-${var.stack_name}-cache"

  engine            = "memcached"
  engine_version    = "${var.memcached_version}"
  node_type         = "${var.memcached_host_type}"
  num_cache_nodes   = "${var.num_memcached_instances}"
  apply_immediately = true

  az_mode = "cross-az"

  parameter_group_name = "${aws_elasticache_parameter_group.memcached_parameter_group.name}"
  port                 = 11211

  subnet_group_name            = "${aws_elasticache_subnet_group.subnet_group.name}"
  security_group_ids           = ["${aws_security_group.elasticsearch_security_group.id}"]
  preferred_availability_zones = "${var.availability_zones}"
  notification_topic_arn  = "${aws_sns_topic.app_errors.arn}"

  tags {
    Name  = "${terraform.workspace}-${var.stack_name}-cache"
    Stack = "${var.stack_name}"
    Env   = "${terraform.workspace}"
  }
}
```

### Expected Behavior

Terraform throws a more useful error when memcached nodes are still being created.

### Actual Behavior

Error: Error refreshing state: 1 error(s) occurred:

* aws_elasticache_cluster.memcached_cluster: 1 error(s) occurred:

* aws_elasticache_cluster.memcached_cluster: aws_elasticache_cluster.memcached_cluster: Unexpected nil pointer in: {
  CacheNodeId: "0003",
  CacheNodeStatus: "creating",
  CustomerAvailabilityZone: "us-west-2b",
  ParameterGroupStatus: "in-sync"
}

### Steps to Reproduce

1. Create a memcached elasticache cluster in terraform
2. Manually increase the node count in the console
1. `terraform apply` while those nodes are still being created

### References

* #0000

**Comment by gdavison** [comment]
This error is caused by the node endpoints not being configured while they are still launching. To prevent the error, the Read function should wait until the cluster is in the state `available`.

The error message can also be improved.
