### ISSUE TITLE
Terraform doesn't detect that cloud formation stack was created successfully

### ISSUE THREAD

**Issue by abjrcode** [hashicorp/terraform-provider-aws#6800]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
`terraform 0.11.10`
`provider.aws: version = "~> 1.50"`
### Affected Resource(s)

* aws_cloudformation_stack

### Terraform Configuration Files

```hcl
resource "aws_cloudformation_stack" "MyStack" {
  name = "MyStack-${var.deployment}"

  parameters {
    PARAMS GO HERE...
  }

  timeouts = {
    create = "60m"
    update = "60m"
    delete = "10m"
  }

  template_url = "${var.template_url}"
  on_failure   = "${var.on_stack_creation_failure}"
  capabilities = ["CAPABILITY_IAM"]
  tags         = "${var.default_tags}"
}
```

### Debug Output

Terraform doesn't detect that stack was actually created successfully

### Panic Output
None

### Expected Behavior

It should detect that cloud formation stack was created successfully and continue.

### Actual Behavior
It throws a time out error that the cloud formation stack wasn't created in time, outputting the following message:  

> * aws_cloudformation_stack.MyStack: timeout while waiting for state to become 'CREATE_COMPLETE, CREATE_FAILED, DELETE_COMPLETE, DELETE_FAILED, ROLLBACK_COMPLETE, ROLLBACK_FAILED' (last state: 'CREATE_IN_PROGRESS', timeout: 1h5m0s)

**Comment by brunoxd13** [comment]
I'm using this feature and I've noted the same behavior.
