### ISSUE TITLE
Add resource for "aws dynamodb tag-resource" to support Local DynamoDb

### ISSUE THREAD

**Issue by abcondas** [hashicorp/terraform-provider-aws#6859]
I'm attempting to use local dynamodb in order to run "unit" tests against our dynamodb tables.  I'd like to use the same dynamodb table resources that I use to create the tables against the aws dynamodb service.  But, terraform currently won't ignore the tags that are created as part of the aws_dynamodb_table resource.  So, I ripped out the tags and created a new .tf file that creates the tags after the fact as follows:
```
resource "null_resource" "tag-table" {
  depends_on = ["aws_dynamodb_table.table"]
  provisioner "local-exec" {
    command = "aws dynamodb tag-resource --resource-arn ${aws_dynamodb_table.table.arn} --tags Key=Name,Value=${aws_dynamodb_table.table.name} "
  }
}
```
But, it would be better if terraform supported this by either ignoring the tags in the aws_dynamodb_table resource when using a local dynamodb service or by providing a new resource to tag a table.  The above method requires me to install the aws-cli in my pipeline which is a little bit of a nuisance but more importantly, it would be better to keep everything within terraform and not have to use a null-resource at all.

Thanks for your consideration.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_dynamodb_table (existing)
* aws_dynamodb_tag (new)

### Potential Terraform Configuration

```
resource "aws_dynamodb_tag" "tag-table" {
  depends_on = ["aws_dynamodb_table.table"]
  attribute {
    Key="Name",
    Value="${aws_dynamodb_table.table.name} "
  }
}
```

**Comment by mmritesh** [comment]
This feature would be really helpful since my tables are automatically created by Kinesis client library and now I need to add some custom tags to it.
