### ISSUE TITLE
Feature Request: New rds option group option settings

### ISSUE THREAD

**Issue by kylelaverty** [hashicorp/terraform-provider-aws#6899]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Recently, I am not 100% sure when, AWS updated the Options screen in RDS to add a bunch more options that need to be reflected in terraform.

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.SQLServer.Options.BackupRestore.html

#### New Screen Layout
![image](https://user-images.githubusercontent.com/12103001/50164259-2af96d80-02b0-11e9-970f-cf2abcfd7210.png)

### New or Affected Resource(s)

* aws_db_option_group 

### Potential Terraform Configuration

```hcl
resource "aws_db_option_group" "option_group" {
  name                                  = "name"
  option_group_description  = "description"
  engine_name                      = "sqlserver-se"
  major_engine_version         = "14.00"

  option {
    option_name = "SQLSERVER_BACKUP_RESTORE"

    option_settings [
    {
      name  = "IAM_ROLE_ARN"
      value = "${aws_iam_role.example.arn}"
    },
    {
     name = "S3_BUCKET"
     value = "some bucket name"
    },
    {
     name = "S3_FOLDER_PATH_PREFIX"
     value = ""
    },
    {
     name = "ENCRYPTION"
     value = "some master key"
    }
    ]
  }

  tags = {}
}
```

### References

* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.SQLServer.Options.BackupRestore.html

**Comment by bflad** [comment]
@nywilken FYI fixing the labelling here as `aws_db_option_group` is related to the RDS service, not S3.
