### ISSUE TITLE
Ignore capacity changes in DynamoDB with on demand billing

### ISSUE THREAD

**Issue by philipl** [hashicorp/terraform-provider-aws#6916]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform 0.11.11
AWS Provider 1.52

### Description

When using the on-demand billing mode, the capacity configuration for the table or GSI are not relevant and AWS will ignore them. However, terraform will see that the 'current' value is 0 and try to plan and apply a change to set them to the configured values.

It is desirable to be able to keep the configuration values in the terraform files because that allows us to easily switch between on-demand and provisioned billing with a single variable (setting the billing mode). We'd otherwise have to conditionalise the capacity values too, which blows up the set of variables to manage. It's also not possible to use the lifecycle to ignore the capacities as the lifecyle block cannot be interpolated. But even then, it would be additional configuration logic.

### Affected Resource(s)

* aws_dynamodb_table

### Expected Behavior

Capacity changes should not be planned, regardless of value as long as on-demand billing is turned on.

### Actual Behavior

Capacity changes are planned and appear to apply successfully, but just get planned again the next time.

### Steps to Reproduce

1. `terraform plan`

**Comment by tierra** [comment]
I use the same lifecycle ignore configuration with OnDemand mode as I use when configuring DynamoDB autoscaling, which is working just as effectively (the first apply will attempt to configure the capacity, but updates will properly ignore them:

```
  lifecycle {
    ignore_changes = [
      "read_capacity",
      "write_capacity",
    ]
  }
```

So I believe this is working as intended, or at the least, has an adequate workaround.
