### ISSUE TITLE
CodePipeline: ECR as Source Action

### ISSUE THREAD

**Issue by jlsan92** [hashicorp/terraform-provider-aws#7012]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

ECR was recently added to CodePipeline as a Source Stage/Action ([link](https://aws.amazon.com/about-aws/whats-new/2018/11/the-aws-developer-tools-improve-continuous-delivery-support-for-aws-fargate-and-amazon-ecs/)). The provider allows to use the ECR as Source but the CloudWatch Event configuration is missing, so the pipeline is never triggered.

### New or Affected Resource(s)

* aws_codepipeline

### Potential Terraform Configuration

```hcl
resource "aws_codepipeline" "this" {
  name     = "test-pipeline"
  role_arn = "${aws_iam_role.codepipeline.arn}"

  artifact_store {
    location = "${aws_s3_bucket.this.bucket}"
    type     = "S3"
  }

  stage {
    name = "Source"

    action {
      name             = "Source"
      category         = "Source"
      owner            = "AWS"
      provider         = "ECR"
      version          = "1"
      output_artifacts = ["source"]

      configuration {
        RepositoryName = "${aws_ecr_repository.this.name}"
        ImageTag       = "latest"
      }
    }
  }
}
```

### References

* N/A

**Comment by poflynn** [comment]
So sad :-( Any suggested workarounds to this?

**Comment by swordfish444** [comment]
+1

**Comment by jpSimkins** [comment]
With pipelines becoming a standard, this is has become a big issue. This is going to force many to move to the CDK. Is this on the roadmap to be addressed? 20 months and still nothing... given the lack of tags I assume there is no movement on this?

**Comment by brian-skafte** [comment]
Add the event rule you want and keep control. These are the resources required/created on your behalf using the AWS console to create the pipeline with ECR as a source.

```
resource "random_integer" "rule_id" {
  min = 100000
  max = 999999
}

resource "aws_cloudwatch_event_rule" "this" {
  name        = "codepipeline-${aws_ecr_repository.this.name}-latest-${random_integer.rule_id.result}-rule"
  description = "Amazon CloudWatch Events rule to automatically start your pipeline when a change occurs in the Amazon ECR image tag."

  event_pattern = <<EOF
{
  "source": [
    "aws.ecr"
  ],
  "detail": {
    "action-type": [
      "PUSH"
    ],
    "image-tag": [
      "latest"
    ],
    "repository-name": [
      "${aws_ecr_repository.this.name}"
    ],
    "result": [
      "SUCCESS"
    ]
  },
  "detail-type": [
    "ECR Image Action"
  ]
}
EOF
}

resource "aws_cloudwatch_event_target" "trigger" {
  rule      = aws_cloudwatch_event_rule.this.name
  target_id = "CodePipeline"
  arn       = aws_codepipeline.this.arn
  role_arn  = aws_iam_role.trigger.arn
}

resource "aws_iam_role" "trigger" {
  name               = "cwe-role-${var.aws_region}-${aws_ecr_repository.this.name}"
  path               = "/service-role/"
  assume_role_policy = data.aws_iam_policy_document.trigger_assume_role_policy.json
}

data "aws_iam_policy_document" "trigger_assume_role_policy" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["events.amazonaws.com"]
    }
  }
}

resource "aws_iam_policy" "trigger" {
  name   = "start-pipeline-execution-${var.aws_region}-${aws_ecr_repository.this.name}"
  path   = "/service-role/"
  policy = data.aws_iam_policy_document.trigger_permissions.json
}

data "aws_iam_policy_document" "trigger_permissions" {
  statement {
    actions = [
      "codepipeline:StartPipelineExecution"
    ]
    resources = [
      aws_codepipeline.this.arn
    ]
  }
}

resource "aws_iam_role_policy_attachment" "trigger" {
  policy_arn = aws_iam_policy.trigger.arn
  role       = aws_iam_role.trigger.name
}
```

**Comment by tmegow** [comment]
This is still busted. Creating `aws_codepipeline` with ECR source doesn't create the CloudWatch Event rule that is created when doing the same action in the AWS console.

**Comment by rabidscorpio** [comment]
@tmegow Thank you for this, having the `detail` section and the IAM permissions was really helpful.

Since I prefer to keep things as much in HCL as possible for readability, I made this change to the event rule (I added the IAM permissions to existing roles and policies):
```
resource "aws_cloudwatch_event_rule" "ecr_image_push" {
  name     = "${local.base_name}-ecr-image-push"
  role_arn = aws_iam_role.codepipeline.arn

  event_pattern = jsonencode({
    source      = ["aws.ecr"]
    detail-type = ["ECR Image Action"]

    detail = {
      repository-name = [local.source_ecr_repo_name]
      image-tag       = [var.environment]
      action-type     = ["PUSH"]
      result          = ["SUCCESS"]
    }
  })
}

resource "aws_cloudwatch_event_target" "ecr_image_push" {
  rule      = aws_cloudwatch_event_rule.ecr_image_push.name
  target_id = local.name_codepipeline
  arn       = aws_codepipeline.application.arn
  role_arn  = aws_iam_role.codepipeline.arn
}
```

**Comment by ewbankkit** [comment]
Closing this issue as I have verified that `RepositoryName` and `ImageTag` can be specified in `configuration` and the examples above show how to create the CloudWatch event.
