### ISSUE TITLE
Tech Debt: Consistently Handle ISO-8601 Attributes

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#7045]
## Description

We have a few places that require ISO-8601 timestamp handling instead of Terraform's preferred RFC3339 timestamp handling:

* `aws_autoscaling_schedule` resource `end_time` and `start_time` attributes
* `aws_pinpoint_app` resource `quiet_time` configuration block `end` and `start` attributes
* `aws_ssm_maintenance_window` resource `end_date` and `start_date` attributes
* Potentially others that are not documented with "8601" in the resource documentation

Currently plan-time validation is inconsistently applied or unapplied to these attributes. We should come up with a consistent plan for handling date formats outside of RFC3339 and implement it for these attributes. Various options include:

* Continuing to accept them passthrough in ISO-8601 format with plan-time validation implemented in the Terraform AWS provider codebase
* Continuing to accept them passthrough in ISO-8601 format with plan-time validation implemented in the Terraform provider SDK codebase
* Converting them (breaking change) to RFC3339 with plan-time validation implemented with the upstream Terraform provider SDK RFC3339 timestamp validation

**Comment by firasnajjar** [comment]
Maybe something like this can be used as a workaround for now: 

```
"${replace(timeadd(timestamp(), "10h"), "/(:\\d{2}Z)/", "Z")}"
```

**Comment by relnetops** [comment]
What is the status of this issue?  I'm still getting this error as of today:
```
Error: "2020-23-01" cannot be parsed as iso8601 Timestamp Format
```
