### ISSUE TITLE
Network Load Balancer Target Group fails to be created: The provided target group attribute is not supported

### ISSUE THREAD

**Issue by JoshuaEdwards1991** [hashicorp/terraform-provider-aws#7047]
### Expected Behavior

Terraform Creates AWS Network Load Balancer Target Group 

### Actual Behavior

aws_lb_target_group.nlb: Error modifying Target Group Attributes: InvalidConfigurationRequest: The provided target group attribute is not supported
	status code: 400

### Steps to Reproduce

1. `terraform apply`

```
resource "aws_lb_target_group" "nlb" {
  count = "${length(var.peer_tg_ports)}"

  name_prefix = "${var.tg_name}-n-"
  port        = "${element(var.peer_tg_ports, count.index)}"
  protocol    = "TCP"
  vpc_id      = "${var.vpc_id}"

  slow_start  = "900"

  lifecycle {
    create_before_destroy = true
  }

  health_check {
    protocol            = "HTTP"
    path                = "${var.hc_path}"
    port                = "${var.hc_port}"
    unhealthy_threshold = "10"
    healthy_threshold   = "10"
    interval            = "30"
  }
}
```

### Terraform Version
Terraform v0.11.10
+ provider.archive v1.1.0
+ provider.aws v1.50.0
+ provider.random v2.0.0
+ provider.template v1.0.0

**Comment by bflad** [comment]
@JoshuaEdwards1991 if you switch the `health_check` `protocol` from `HTTP` to `TCP` and remove the health check `path`, does it work?

According the the [API documentation](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateTargetGroup.html):
> **HealthCheckProtocol**
> The protocol the load balancer uses when performing health checks on targets. The TCP protocol is supported only if the protocol of the target group is TCP. For Application Load Balancers, the default is HTTP. For Network Load Balancers, the default is TCP.
> Type: String
> Valid Values: HTTP | HTTPS | TCP
> Required: No

However our [resource documentation](https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/lb_target_group.html.markdown) does not currently have the same note, so it would probably be beneficial to get that added.

We have talked in the past about separating ALB vs NLB resources so we can provide better plan-time validation for these sorts of issues, however no movement has been made in that regard and likely will not happen in the 2.0 release later this month.

**Comment by JoshuaEdwards1991** [comment]
Unfortunately, it didn't fix the problem, it responded with the same error

aws_lb_target_group.nlb: Error modifying Target Group Attributes: InvalidConfigurationRequest: The provided target group attribute is not supported
	status code: 400

```
resource "aws_lb_target_group" "nlb" {
  count = "${length(var.peer_tg_ports)}"

  name_prefix = "${var.tg_name}-n-"
  port        = "${element(var.peer_tg_ports, count.index)}"
  protocol    = "TCP"
  vpc_id      = "${var.vpc_id}"

  slow_start  = "900"

  lifecycle {
    create_before_destroy = true
  }

  health_check {
    protocol            = "TCP"
    #path                = "${var.hc_path}"
    #port                = "${var.hc_port}"
    unhealthy_threshold = "10"
    healthy_threshold   = "10"
    interval            = "30"
  }
}
```

**Comment by JoshuaEdwards1991** [comment]
That makes sense!

I found that despite the error given it wouldn't actually associate the target group to the NLB. But when run a second time terraform hooked them up.

**Comment by gurre** [comment]
I got this error from trying to use `access_logs`.

**Comment by limratechnologies** [comment]
@JoshuaEdwards1991  You saved my day! I was struggling for past 4 hours. Thank you!

**Comment by tedivm** [comment]
I've been fighting with this all day and it is really frustrating. I hope that this plan to split network and application load balancers eventually happens.

**Comment by geowa4** [comment]
For anyone coming along later, this is what I had to do to get a Target Group made with an NLB.

```
resource "aws_lb_target_group" "this" {
  name              = local.name
  port              = var.service_port
  protocol          = "TCP"
  target_type       = "ip"
  vpc_id            = var.vpc_id
  tags              = local.default_tags

  health_check {
    protocol = "HTTP"
    port     = var.service_port
    path     = var.health_check_path
  }

  lifecycle {
    ignore_changes = [
      proxy_protocol_v2,
      lambda_multi_value_headers_enabled
    ]
  }
}
```
