### ISSUE TITLE
Updating elasticsearch node type fails

### ISSUE THREAD

**Issue by pgmillon** [hashicorp/terraform-provider-aws#7048]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.7

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (1.28.0)...
- Downloading plugin for provider "template" (1.0.0)...
- Downloading plugin for provider "null" (1.0.0)...

### Affected Resource(s)

* aws_elasticsearch_domain

### Terraform Configuration Files

```hcl
resource "aws_elasticsearch_domain" "es-vpc" {
  count = "${var.AWS_ES_ENABLED}"
  domain_name           = "var.AWS_ES_DOMAIN_NAME"

  cluster_config {
    instance_type            = "var.AWS_ES_INSTANCE_TYPE"
    instance_count           = "1"
    dedicated_master_enabled = "false"
    dedicated_master_count   = "1"
    dedicated_master_type    = "t2.medium.elasticsearch"
    zone_awareness_enabled   = "false"
  }

  vpc_options = {
   security_group_ids = ["${aws_security_group.aws-es.id}"] 
   subnet_ids = ["xyz"]
  }

  encrypt_at_rest {
    enabled = "true"
    kms_key_id = "${var.KMS_ID}"
  }

  ebs_options {
    ebs_enabled = "true"
    volume_size = "35"
    volume_type = "gp2"
  }

   access_policies = <<CONFIG
{
  "Version": "2012-10-17",
  "Statement": [
      {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
          "AWS": "*"
      },
      "Action": "es:*",
      "Resource": [
        "arn:aws:es:${var.STACK_REGION}:${var.ACCOUNT_ID}:domain/${var.AWS_ES_DOMAIN_NAME}/*",
        "arn:aws:es:${var.STACK_REGION}:${var.ACCOUNT_ID}:domain/${var.AWS_ES_DOMAIN_NAME}"
      ]
    }
  ]
}
  CONFIG

  snapshot_options {
    automated_snapshot_start_hour = "${var.AWS_ES_SNAPSHOT_START_HOUR}"
  }

  tags {
    billing-category = "${var.BILLING_CATEGORY}"
    billing-subcategory = "${var.BILLING_SUB_CATEGORIES}"
    contact = "${var.CONTACT_EMAIL}"
    service = "elasticsearch"

  }
}
```

### Debug Output

https://gist.github.com/pgmillon/dc49319c69840c771c69c935949c55b5

### Expected Behavior

AWS ES Domain created

### Actual Behavior

```
Error: Error applying plan:

1 error(s) occurred:

* module.xyz.aws_elasticsearch_domain.es-vpc: 1 error(s) occurred:

* aws_elasticsearch_domain.es-vpc: ValidationException: Domain is still being deleted
	status code: 400, request id: xyz
```

### Steps to Reproduce

1. terraform apply to create the domain
2. change AWS_ES_INSTANCE_TYPE to another sizing
3. terraform apply to update the domain

### References

* #0000

**Comment by bflad** [comment]
Hi @pgmillon 👋 Sorry for the trouble here. Could you please provide the debug logs when you get a chance? Thanks.

**Comment by pgmillon** [comment]
Link to gist added, it's a pretty heavy one.
Thanks @bflad for your patience.

**Comment by pgmillon** [comment]
Hi there, anyone got a chance to have a look into this ?

**Comment by kerbyferris** [comment]
FWIW, we've faced this same issue trying to destroy and recreate an Elasticsearch instance, and the problem was on Amazon's side (for some holy reason, our es domain took three weeks to actually "delete" after the AWS console said it was gone). To rule out Amazon error, try creating the same domain manually using the AWS console. If it's an Amazon issue, you'll get the same `Domain is still being deleted` error in the UI.
