### ISSUE TITLE
aws_emr_cluster recreates cluster when there are no changes in configurations_json

### ISSUE THREAD

**Issue by l13t** [hashicorp/terraform-provider-aws#7101]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```$ terraform version
Terraform v0.11.11
+ provider.aws v1.54.0
+ provider.external v1.0.0
+ provider.postgresql v0.1.3
+ provider.template v1.0.0
```

### Affected Resource(s)

* aws_emr_cluster

### Terraform Configuration Files

```hcl
data "template_file" "emr_configuration_json" {
  template = <<EOF
[
    {
        "classification": "spark-log4j",
        "configurations": [],
        "properties": {
            "log4j.logger.org.apache.spark.repl.SparkILoop$SparkILoopInterpreter": "WARN",
            "log4j.logger.org.apache.spark.repl.SparkIMain$exprTyper": "WARN",
            "log4j.logger.org.apache.spark.streaming": "WARN",
            "log4j.rootCategory": "WARN, console"
        }
    },
    {
        "classification": "spark-env",
        "configurations": [
            {
                "classification": "export",
                "configurations": [],
                "properties": {
                    "PYSPARK_PYTHON": "/usr/bin/python3.6"
                }
            }
        ],
        "properties": {}
    }
]
EOF
}

resource "aws_emr_cluster" "data_emr_519" {
  name          = "data-emr-519"
  release_label = "emr-5.19.0"
  applications  = ["Spark", "Hadoop"]
  count         = "${lookup(var.emr_count, var.env)}"

  ec2_attributes {
    subnet_id                         = "${var.subnet_id}"
    emr_managed_master_security_group = "${var.master_security_group_id}"
    emr_managed_slave_security_group  = "${var.slave_security_group_id}"
    instance_profile                  = "${aws_iam_instance_profile.emr_profile.arn}"
    key_name                          = "${var.data_karl_marx_deploy_key_name}"
    additional_master_security_groups = "${var.sg_emr_gocd_id}"
    additional_slave_security_groups  = "${var.sg_emr_gocd_id}"
  }

  instance_group {
    instance_role  = "MASTER"
    instance_count = 1
    instance_type  = "${lookup(var.emr_master_instance_type, var.env)}"
  }

  instance_group {
    instance_role  = "CORE"
    instance_count = "${lookup(var.emr_core_instances_count, var.env)}"
    instance_type  = "${lookup(var.emr_core_instances_type, var.env)}"
  }

  tags {
    description    = "Managed by Terraform"
    "sf:costGroup" = "data"
    "sf:env"       = "${var.env}"
    "sf:team"      = "data"
  }

  configurations_json = "${data.template_file.emr_configuration_json.rendered}"

  service_role = "${aws_iam_role.iam_emr_service_role.arn}"

  bootstrap_action {
    path = "s3://${aws_s3_bucket.data_emr_bootstrap_actions.bucket}/bootstrap.sh"
    name = "bootstrap"
  }

  depends_on = ["aws_s3_bucket.data_emr_bootstrap_actions", "aws_s3_bucket_object.bootstrap"]
}
```

### Debug Output

https://gist.github.com/l13t/cca0c1c195c34dc275bdae51cc413cfe

### Expected Behavior

No cluster recreation.

### Actual Behavior

Cluster is recreated because of difference in configuration.

Trying to fix an issue I copied config from aws console. So `configurations_json` is:

```json
[
    {
        "classification": "spark-log4j",
        "configurations": [],
        "properties": {
            "log4j.logger.org.apache.spark.repl.SparkILoop$SparkILoopInterpreter": "WARN",
            "log4j.logger.org.apache.spark.repl.SparkIMain$exprTyper": "WARN",
            "log4j.logger.org.apache.spark.streaming": "WARN",
            "log4j.rootCategory": "WARN, console"
        }
    },
    {
        "classification": "spark-env",
        "configurations": [
            {
                "classification": "export",
                "configurations": [],
                "properties": {
                    "PYSPARK_PYTHON": "/usr/bin/python3.6"
                }
            }
        ],
        "properties": {}
    }
]
```
I agree that I need to remove `"configurations": [],` from config. But real root cause of issue is that terraform gets config from aws and it is in next code box:
```json
[
    {
        "Classification": "spark-log4j",
        "Properties": {
            "log4j.logger.org.apache.spark.repl.SparkILoop$SparkILoopInterpreter": "WARN",
            "log4j.logger.org.apache.spark.repl.SparkIMain$exprTyper": "WARN",
            "log4j.logger.org.apache.spark.streaming": "WARN",
            "log4j.rootCategory": "WARN, console"
        }
    },
    {
        "Classification": "spark-env",
        "Configurations": [
            {
                "Classification": "export",
                "Properties": {
                    "PYSPARK_PYTHON": "/usr/bin/python3.6"
                }
            }
        ],
        "Properties": {}
    }
]
```

So there is some magic between actual config in aws console and config downloaded by terraform to my pc.

### Steps to Reproduce

1. `terraform plan/apply`

**Comment by hylaride** [comment]
I'm having this same issue and I did a diff on mine as well. I suspect that the last box of JSON code is getting capitalized json keys?

**Comment by jpatallah** [comment]
I had the same issue, and it was solved by capitalizing the json keys to match aws.  See below:

`@@ -75,17 +75,15 @@ resource "aws_emr_cluster" "cluster" {
       "Properties": {}
     },
     {
-       "classification":"emrfs-site",
-       "properties":{
+       "Classification":"emrfs-site",
+       "Properties":{
           "fs.s3.consistent.retryPeriodSeconds":"10",
           "fs.s3.consistent":"true",
           "fs.s3.consistent.retryCount":"5",
           "fs.s3.consistent.metadata.read.capacity":"600",
           "fs.s3.consistent.metadata.write.capacity":"300",
           "fs.s3.consistent.metadata.tableName":"${aws_dynamodb_table.primary.name}"
-       },
-       "configurations":[
-       ]
+       }
     }
   ]
 EOF`

**Comment by ivanfavi** [comment]
I have the same issue if you look at the configurations in the EMR console you could see the password provided is replaced by `"********"` (it is encrypted in some way by amazon). I just updated the password provided by terraform for this value `"********"`

```
      "Classification": "hive-site",
      "Properties": {
        "javax.jdo.option.ConnectionURL": "jdbc:mysql://hive-mestatore.us-west-2.rds.amazonaws.com:3306/hive-db?createDatabaseIfNotExist=true",
        "javax.jdo.option.ConnectionDriverName": "org.mariadb.jdbc.Driver",
        "javax.jdo.option.ConnectionUserName": "hive-user",
        "javax.jdo.option.ConnectionPassword": "********"
      }
    },
```

Then terraform plan/apply didn't ask to replace the existing EMR cluster. This is a jugaard but I didn't found another approach to solve it. Maybe providing a bootstrap to set the password during the provisioning could avoid this issue but increase the complexity a bit.
