### ISSUE TITLE
Feature request - AWS Snowball

### ISSUE THREAD

**Issue by deepakbshetty** [hashicorp/terraform-provider-aws#7115]
Terraform provider support request for Snowball
Create address
Create job

**Comment by slapula** [comment]
What's the use case for this (just out of curiosity)?  I wrote an Ansible module for this a while ago and never released it since the API was pretty limited at the time.

**Comment by slapula** [comment]
Ah, addresses are still not fully CRUD so managing them via Terraform isn't really going to be doable.

**Comment by deepakbshetty** [comment]
Typically the use case is ability to create snowball ball job for migration purpose.  All our stacks are terraform and this runs out of AWS cli or AWS  console. 
Not looking to create/maintain address as individual entity, just the ability to create a snowball job.

Usually the process begins accepting address as input , type of snowball , kms keys to unlock manifest , snowball import iam role and finally sns topics for notification.

We could supply address as Json tempate file ?

**Comment by tomelliff** [comment]
Is there some benefit you'd gain from using Terraform for this if it is unable to manage the lifecycle of the resource?

**Comment by deepakbshetty** [comment]
The creation of snowball job itself. We do a several of them and only the job name or s3 bucket changes to be honest. Would be nice put it under an automation pipeline avoiding the trivial manual process of keying in same data everytime.

**Comment by charlescva** [comment]
I too am interested in this.  Less for the creation of the snowball itself, but more for re-use with my existing IaC for AWS Region endpoints.  Would love to toggle a boolean value and tweak a string or two, and deploy my software to a snowball as well as US-EAST/WEST/etc.
