### ISSUE TITLE
API Gateway Rest API + Import producing unexpected results

### ISSUE THREAD

**Issue by richardgavel** [hashicorp/terraform-provider-aws#7161]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8
+ provider.aws v1.51.0
+ provider.null v1.0.0
+ provider.template v1.0.0

### Affected Resource(s)

aws_api_gateway.resti_api

### Terraform Configuration Files

```hcl
resource "aws_api_gateway_rest_api" "main" {
  count = "${var.enable_api_gateway ? 1 : 0}"

  name = "${var.environment_id}-${var.service_name}"
  body = "${var.api_gateway_swagger_definition}"

  endpoint_configuration {
    types = ["REGIONAL"]
  }

```

### Expected Behavior

Rest API should be created with name as defined in TF and definition as defined in body

### Actual Behavior

Body overrides name. If no name provided in body, defaults to "Imported on {date/time}". Name will change to that defined in TF if applied again with no body changes.

### Steps to Reproduce

terraform apply in state where REST API does not yet exist

### Important Factoids

In looking at the code, it's clear this is because the REST API is created with the name specified https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_api_gateway_rest_api.go#L122
Then it's getting overridden by the content in the body during the import https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_api_gateway_rest_api.go#L156.

Maybe we need to update the name change after PutRestApiInput call? The name is a required field on the resource, so the expectation should be that it's going to be the name of the resource.

**Comment by bflad** [comment]
Fixes for the `aws_api_gateway_rest_api` resource handling of `api_key_source`, `binary_media_types`, `description`, `minimum_compression_size`, `name`, and `policy` configuration values will now be correctly applied as an override after OpenAPI specification import (`body` argument) on resource creation and update. This will release with version 3.25.0 of the Terraform AWS Provider, likely tomorrow.

For further feature requests, documentation updates, or bug reports with this functionality after it is released and upgrading the provider, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!
