### ISSUE TITLE
Feature Request: MediaConnect

### ISSUE THREAD

**Issue by colde** [hashicorp/terraform-provider-aws#7217]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be useful to be able to setup MediaConnect Flows, including input and outputs. The MediaConnect configuration is rather simple. But being able to send to IP's of specific EC2 resources would also be handy.

### New or Affected Resource(s)

* aws_elemental_mediaconnect

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by adamgilman** [comment]
This isn't available as a resource in terraform. Whats the work that remains to make it available?

**Comment by bflad** [comment]
Sorry this was prematurely closed when the service client was added into the provider. I just provided an initial review for the `aws_media_connect_flow` resource in #7431.
