### ISSUE TITLE
[Feature] data source for aws_iam_saml_provider

### ISSUE THREAD

**Issue by mlehner616** [hashicorp/terraform-provider-aws#7283]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is already a resource for `aws_iam_saml_provider.` I'd like to be able to lookup existing resources outside of terraform using a data source for `aws_iam_saml_provider` to use a single provider in multiple terraform states.

**Comment by asp7479** [comment]
Was there a solution for this ?. I already have a SAML provider in my AWS account and I would like to just create roles and associate the existing SAML instead of creating SAML provider with metadata extract everytime. Please update ?!

**Comment by alpacamybags118** [comment]
@asp7479 @mlehner616 i started to look/work on this today - going to try and get a PR in sometime this week / weekend.

**Comment by alpacamybags118** [comment]
I added a PR for this over a year ago but it never got reviewed. I recently updated it to meet the newer standards. Hoping to get some eyes on as the automation didn't tag it as `needs-triage`. Maybe you might know the best way to get this tagged for review @bflad ?

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!
