### ISSUE TITLE
Support for Postgres 10.5 at Aurora 2.1 version

### ISSUE THREAD

**Issue by supergarotinho** [hashicorp/terraform-provider-aws#7347]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

- Terraform v0.11.11
- provider.aws v1.57.0

### Affected Resource(s)

* aws_rds_cluster

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "aws_rds_cluster" "rds_aurora_pg" {
    engine                          = "aurora-postgresql"
    engine_version             = "10.5"
# ...
}
```

### Debug Output

```
* aws_rds_cluster_instance.rds_aurora_pg_instances: error creating RDS DB Instance: InvalidParameterCombination: Cannot find version 10.5 for aurora
```

### Expected Behavior

At AWS docs, seems that Postgres 10.5 is already being supported by Aurora 2.1; and Postgres 10.4 is being supported by aurora 2.0. [Link](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Updates.20180305.html)

> And, if you try to create a Aurora RDS by AWS console, it is possible to use the 10.6 version.

### Actual Behavior

Only until 9.6 is supported by the provider.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by supergarotinho** [comment]
Sorry for the issue. I found the problem: #4779

Should we add something at the documentation?

If not, i will close it.

**Comment by bflad** [comment]
Hi @supergarotinho 👋 Thanks for the heads up. We can certainly update the documentation if its unclear. Do you have any suggestions?

**Comment by supergarotinho** [comment]
Thank you the answer! 

Thinking better, i have some options:

1. Make the aws driver copy the cluster driver and version information to instances atributes if: (the instance is not specified) && (the instance has a cluster info).
    - Also add this behavior on the documentation
    - Add a log info or warn when copying?
2. If the instance has a cluster id associated; and the cluster driver and version is not amazon default; and there is no information, at the instance, about the driver name and version:
    - Add a warn/error on log
3. Only add a warning on the aws_rds_instance about this.

I prefer the option 1. What do you think?

**Comment by kamranzafar** [comment]
Hi @supergarotinho @bflad , we are experiencing the same issue, do you know how to resolve it? We are using terraform version 0.12.0. Below is the error message.

Error: error creating RDS DB Instance: InvalidParameterCombination: Cannot find version 10.5 for aurora                                                                                                                    status code: 400, request id: 6c83e87d-d5d6-4e74-8e1e-d51802f5f7bb
--

**Comment by supergarotinho** [comment]
Hi Kamranzafar,

The problem is mostly caused to default values at DB Cluster and Instance. The default type for the Cluster is aurora-mysql. To use aurota-postgres, you need to specify it at the Instance and DB Cluster level. As could be many problems, can you share the code for the DB Instance and Cluster?

**Comment by nywilken** [comment]
Related #9531

**Comment by bflad** [comment]
Let's use #9531 for tracking this 👍
