### ISSUE TITLE
r/aws_lb_listener: Updating protocol from TLS to TCP leads to "ValidationError: An SSL policy cannot be specifed for TCP listeners" 

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#7367]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

```hcl
resource "aws_lb_listener" "foo" {
  ...
  protocol          = "TLS"
  ssl_policy        = "ELBSecurityPolicy-TLS-1-2-Ext-2018-06"
  ...
}
```

```console
$ terraform apply
```
✅

Change to:
```hcl
resource "aws_lb_listener" "foo" {
  ...
  protocol          = "TCP"
  ssl_policy        = "" # Or removed completely
  ...
}
```

```console
$ terraform plan
...
protocol:        "TLS" => "TCP"
...
$ terraform apply
...
Error modifying LB Listener: ValidationError: An SSL policy cannot be specifed for TCP listeners
...
```

❌

NLB support for TLS added via https://github.com/terraform-providers/terraform-provider-aws/pull/7338.

**Comment by ewbankkit** [comment]
The problem is that https://github.com/terraform-providers/terraform-provider-aws/blob/f1c24b3125d85bffc33394e7e931f9557881cefd/aws/resource_aws_lb_listener.go#L344-L346 returns `ok` as `true` with `sslPolicy` equal to `ELBSecurityPolicy-TLS-1-2-Ext-2018-06`, the value set during resource creation.

**Comment by ewbankkit** [comment]
See [this](https://github.com/hashicorp/terraform/issues/4501#issuecomment-168825896) comment.

**Comment by Rohithzr** [comment]
@ewbankkit I viewed the comment you linked but I did not understand the solution to the issue. where do I set `enable_dns_hostnames = false/true`.

**Comment by ewbankkit** [comment]
@Rohithzr Unfortunately there currently is no solution 😞 due to the way that Terraform handles `Optional` + `Computed` attributes (which the `ssl_policy` attribute is).

**Comment by Rohithzr** [comment]
@ewbankkit ah! got you, that's actually a sad thing considering it seems very simple in this specific case.
I am actually trying to delay the situation where i would have to fork about 3-4 repositories (maybe more) of tf script that I am deploying. Because I need to modify the nlb listener created by that module's sub module. :/
https://serverfault.com/questions/970658/terraform-modify-lb-listener

**Comment by Frogvall** [comment]
Tainting the resource got me around this issue. Could turn out to be very annoying in the long run, since we run terraform apply in our ci/cd env.

**Comment by tophercullen** [comment]
This is still an issue in the latest provider.

**Comment by nisalupendra** [comment]
We still have this issue
