### ISSUE TITLE
Data source for  aws_directory_service_directory

### ISSUE THREAD

**Issue by marpada** [hashicorp/terraform-provider-aws#7372]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add a data source for  **aws_directory_service_directory**  resources.

### New or Affected Resource(s)

*  aws_directory_service_directory

**Comment by 0xdavew** [comment]
When creating SQL Server RDS instance using "resource aws_db_instance", I need to know the id of the directory service in the "domain" parameter.

When adding a Windows EC2 instance to the AD, it's sufficient to simply know the name of the directory services directory. However, for RDS you need the id.

Please add this enhancement.

In the meantime, I have to workaround this omission by using powershell to invoke AWS CLI to figure out the directory id, set it in an environment variable using env:TF_VAR and then use this in my terraform script.

Cheers,
Dave.

**Comment by 0xdavew** [comment]
Powershell to achieve this if interested:

If you just have one directory:
`$directory = aws ds describe-directories | ConvertFrom-Json | Select-Object -expand DirectoryDescriptions`
`$env:TF_VAR_directory_id = $directory.DirectoryId`

If you need to select a specific directory, use `Where-Object`:
`$directory = aws ds describe-directories | ConvertFrom-Json | Select-Object -expand DirectoryDescriptions | Where-Object -Property "Name" -eq -Value "INSERT_NAME_HERE"`

**Comment by marpada** [comment]
> When creating SQL Server RDS instance using "resource aws_db_instance", I need to know the id of the directory service in the "domain" parameter.

This is exactly my use case :)

**Comment by jamiefrench** [comment]
Is there an update of availability on this please?  Also found the CLI fails to return DNS IP addresses of the Shared Microsoft AD! :(

**Comment by djbrightman** [comment]
Use case is creating  security group rules for workspaces needing access to the directory (connector) that defines their security profile.  Just want workspaces to be able to access the DC's on the required ports to perform domain join and operate. Want to limit what else the workspace can get to, so want to tie down to the DC addresses and ports. i.e. lookup the directory connector on the org name and get the ip's
