### ISSUE TITLE
s3 bucket replication rule status can't be changed

### ISSUE THREAD

**Issue by CyrilDevOps** [hashicorp/terraform-provider-aws#7386]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.11
+ provider.aws v1.54.0
+ provider.template v0.1.1

### Affected Resource(s)

* aws_s3_bucket replication configuration rules status

### Terraform Configuration Files

```hcl

resource "aws_s3_bucket" "bucket" {
  provider = "aws.central"
  bucket   = "tf-test-bucket-12345"
  acl      = "private"
  region   = "eu-central-1"

  versioning {
    enabled = true
  }

  replication_configuration {
    role = "${aws_iam_role.replication.arn}"

    rules {
      id     = "foobar"
      prefix = "foo"
      status = "Enabled"

      destination {
        bucket        = "${aws_s3_bucket.destination.arn}"
        storage_class = "STANDARD"
      }
    }
  }
}
```

### Debug Output

When I switch the replication rules state from Enable to Disable or Disable to Enable,
it show a change in the terraform plan, but terraform apply does nothing.

Terraform will perform the following actions:

  ~ aws_s3_bucket.bucket_replication
      replication_configuration.0.rules.2924235698.destination.#:                                       "0" => "1"
      replication_configuration.0.rules.2924235698.destination.2702226643.access_control_translation.#: "0" => "0"
      replication_configuration.0.rules.2924235698.destination.2702226643.account_id:                   "" => ""
      replication_configuration.0.rules.2924235698.destination.2702226643.bucket:                       "" => "arn:aws:s3:::xxx"
      replication_configuration.0.rules.2924235698.destination.2702226643.replica_kms_key_id:           "" => ""
      replication_configuration.0.rules.2924235698.destination.2702226643.storage_class:                "" => "STANDARD"
      replication_configuration.0.rules.2924235698.filter.#:                                            "0" => "0"
      replication_configuration.0.rules.2924235698.id:                                                  "" => "foobar"
      replication_configuration.0.rules.2924235698.prefix:                                              "" => ""
      replication_configuration.0.rules.2924235698.priority:                                            "" => ""
      replication_configuration.0.rules.2924235698.source_selection_criteria.#:                         "0" => "0"
      replication_configuration.0.rules.2924235698.status:                                              "" => "Disabled"
      replication_configuration.0.rules.343828562.destination.#:                                        "1" => "0"
      replication_configuration.0.rules.343828562.destination.2702226643.access_control_translation.#:  "0" => "0"
      replication_configuration.0.rules.343828562.destination.2702226643.account_id:                    "" => ""
      replication_configuration.0.rules.343828562.destination.2702226643.bucket:                        "arn:aws:s3:::xxx" => ""
      replication_configuration.0.rules.343828562.destination.2702226643.replica_kms_key_id:            "" => ""
      replication_configuration.0.rules.343828562.destination.2702226643.storage_class:                 "STANDARD" => ""
      replication_configuration.0.rules.343828562.filter.#:                                             "0" => "0"
      replication_configuration.0.rules.343828562.id:                                                   "foobar" => ""
      replication_configuration.0.rules.343828562.prefix:                                               "" => ""
      replication_configuration.0.rules.343828562.priority:                                             "0" => "0"
      replication_configuration.0.rules.343828562.source_selection_criteria.#:                          "0" => "0"
      replication_configuration.0.rules.343828562.status:                                               "Enabled" => ""

Plan: 0 to add, 1 to change, 0 to destroy.

but the apply return 
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
and no change on my rule state in aws gui.

### Expected Behavior

I expect my replication rules switch from Enabled to Disabled or Disabled to Enabled

### Actual Behavior

Apply do nothing

### Steps to Reproduce

create a bucket with replication rule enabled, then switch the status of the rule to disabled and try terraform plan/apply.

### Important Factoids

just two basic s3 buckets, I try to condition the rule status to a variable so I can enable or disable it in my different environment.

(aws s3 bucket replication should be a resource by itself and not an entry in bucket (there is already an issue open for that, it will allow bi-directional replication without object cycle definition problem, and allow count on the ressource instead of playing with the 'status'.)

**Comment by tpath** [comment]
Can confirm that this still happens using provider.aws v2.5.0

**Comment by badaltitude** [comment]
Maybe related observation: after creating a replication rule, you can't add/change a priority. 

1. Plan: 0 to add, 1 to change, 0 to destroy.
2. Apply complete! Resources: 0 added, 1 changed, 0 destroyed. 
3. Plan: 0 to add, 1 to change, 0 to destroy.

provider.aws v2.42.0
