### ISSUE TITLE
EBS snapshot fails when IAM profile restricts resource creation based on Tags

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#7505]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.11
+ provider.aws v1.58.0

### Affected Resource(s)

* aws_ebs_snapshot

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

provider "aws" {
  region  = "${var.aws_region}"
  profile = "${var.profile}"
  shared_credentials_file = "${var.credentials_file}"
}

data "aws_ebs_volume" "jenkins_volume" {
  most_recent = true

  filter {
    name   = "tag:BLAHNEXTROLE"
    values = ["BLAHNEXT_${upper(var.major_env)}_BLUE_CI"]
  }
}


resource "aws_ebs_snapshot" "jenkins_snapshot" {
  volume_id = "${data.aws_ebs_volume.jenkins_volume.id}"
  tags = {
    ALERTGROUP      = "BLAHNEXT_TEAM"
    APPLICATIONENV  = "${upper(var.env)}"
    APPLICATIONROLE = "BLAHNEXT_${upper(var.major_env)}_BLUE_CI"
    BILLING         = "${var.billing_code}"
    BUSINESSENTITY  = "BLAHCLOUD"
    BUSINESSUNIT    = "BLAHCLOUD"
    BLAHNEXTROLE     = "BLAHNEXT_${upper(var.major_env)}_BLUE_CI"
    NAME            = "BLAHNEXT_${upper(var.major_env)}_BLUE_CI"
    Name            = "BLAHNEXT_${upper(var.major_env)}_BLUE_CI"
    OWNEREMAIL      = "DLBLAH@GUESS.COM"
    POD             = "${upper(var.pod)}"
    RUNNINGSCHEDULE = "00:00:23:59:1-7"
    SERVICEENTITY   = "BLAHProduct"
    SERVICENAME     = "BLAHProduct"
  }
}
```

### Actual Behavior

* aws_ebs_snapshot.jenkins_snapshot: error creating EC2 EBS Snapshot: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: 1ab56726-d4de-4b3c-802f-6f1f7195aeda

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Our company has IAM policy restrictions based on Tags. When looking at cloudtrail we found that Tags were not being passed by the aws_ebs_snapshot resource. description, volume_id were correctly passed but not the tags. which causes the 403 error.

When access was unrestricted the snapshot was successful.
### References

* #0000

**Comment by infa-stopiwal** [comment]
@nywilken any update on this or in which version might it be resolved?
