### ISSUE TITLE
Add a data source `aws_nat_gateways`

### ISSUE THREAD

**Issue by samuel-phan** [hashicorp/terraform-provider-aws#7575]
Currently, I find no way to have the list of existing NAT Gateways using the data source `aws_nat_gateway`.

Use case: I want to have the list of public IPs of my NAT Gateways to whitelist them in a security group.

```
data "aws_nat_gateways" "default" {
  vpc_id = "my-vpc"
}

resource "aws_security_group_rule" "allow_nat_gateways" {
  type            = "ingress"
  from_port       = 0
  to_port         = 65535
  protocol        = "tcp"
  cidr_blocks     = ["${formatlist("%s/32", data.aws_nat_gateways.default.public_ips)}"]

  security_group_id = "sg-123456"
}
```

The attributes should be the same as the ones we have for the data source `aws_nat_gateway` except that they would be in plural form:

- `allocation_ids` - The Ids of the EIP allocated to the selected Nat Gateway.
- `network_interface_ids` - The Ids of the ENI allocated to the selected Nat Gateway.
- `private_ips` - The private Ip addresses of the selected Nat Gateway.
- `public_ips` - The public Ip (EIP) addresses of the selected Nat Gateway.

**Comment by pjaudiomv** [comment]
@samuel-phan did you ever figure out a workaround for this, I am trying to do the same thing with whitelisting.

**Comment by samuel-phan** [comment]
> @samuel-phan did you ever figure out a workaround for this, I am trying to do the same thing with whitelisting.

I created a `common` TF module on Git, and I hardcoded the AWS NAT gateways:

- `main.tf`:

```
locals {
  aws_nat_gateway_cidr_blocks = [
    # dev / us-east-1
    "A.B.C.D/32",

    # dev / us-west-1
    "E.F.G.H/32",
    "I.J.K.L/32",

    [...]
  ]
}
```

- `output.tf`:

```
output "aws_nat_gateway_cidr_blocks" {
  value = "${local.aws_nat_gateway_cidr_blocks}"
}
```

Then to use it:

```
module "common" {
  source = "git::ssh://git@git-repo.mycompany.com/myorg/terraform-common.git"
}

module "security_group_aws_http_whitelist" {
  source = "terraform-aws-modules/security-group/aws"
  version = "~> v2.0"

  vpc_id      = "${data.aws_vpc.default.id}"

  name        = "http-whitelist"
  description = "HTTP access for the whitelisted IPs (AWS NAT gateways)"

  ingress_cidr_blocks = "${module.common.aws_nat_gateway_cidr_blocks}"
  ingress_rules       = ["http-80-tcp"]
  egress_rules        = ["all-all"]
}
```

Not ideal, but at least, the dirty hardcoded part is quarantined into a `common` TF module. You can also consider generating the `common/main.tf` NAT gateways CIDR blocks to whitelist using a script with `awscli`.

**Comment by knope** [comment]
this is still a thing.... 
[multiple NAT gateways matched; use additional constraints to reduce matches to a single NAT gateway](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_nat_gateway.go#L114-L115)

Feeding a cli loop over a TF data source feels dirty...

**Comment by bgorbuntsov** [comment]
Workaround:

data "aws_nat_gateway" "nat_gw" {
  for_each = toset(module.vpc.public_subnets)
  subnet_id = each.value
  state = "available"
  tags = local.tags
}

output "nat" {
  value = [ for v in data.aws_nat_gateway.nat_gw : format("${v.public_ip}%s", "/32") ]
}

**Comment by applike-ss** [comment]
Also waiting for this

**Comment by samuel-phan** [comment]
@iandrewt Thanks for your contribution for this `nat_gateways` data source! :pray: 

Would it be possible though to have the same attributes as the `nat_gateway` data source ?

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/nat_gateway#attributes-reference

Currently:

```hcl
data "aws_nat_gateways" "ngws" {
  vpc_id = var.vpc_id

  filter {
    name   = "state"
    values = ["available"]
  }
}

data "aws_nat_gateway" "ngw" {
  count = length(data.aws_nat_gateways.ngws.ids)
  id    = tolist(data.aws_nat_gateways.ngws.ids)[count.index]
}

resource "aws_security_group" "allow_nat_gateways" {
  vpc_id = var.vpc_id

  ingress {
    from_port        = 0
    to_port          = 65535
    protocol         = "tcp"
    cidr_blocks      = formatlist("%s/32", data.aws_nat_gateway.ngw[*].addresses[*].public_ip)
  }

  egress {
    from_port        = 0
    to_port          = 0
    protocol         = "-1"
    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }
}
```

What I would suggest:

```hcl
data "aws_nat_gateways" "ngws" {
  vpc_id = var.vpc_id

  filter {
    name   = "state"
    values = ["available"]
  }
}

resource "aws_security_group" "allow_nat_gateways" {
  vpc_id = var.vpc_id

  ingress {
    from_port        = 0
    to_port          = 65535
    protocol         = "tcp"
    cidr_blocks      = formatlist("%s/32", data.aws_nat_gateways.ngws[*].addresses[*].public_ip)
  }

  egress {
    from_port        = 0
    to_port          = 0
    protocol         = "-1"
    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }
}
```

**Comment by bhushan991** [comment]
@samuel-phan above updated code didn't work for me.

Getting:
`Error: multiple NAT gateways matched; use additional constraints to reduce matches to a single NAT gateway`

**Comment by samuel-phan** [comment]
@bhushan991 , please share your code when you're having an error. The error message alone is not sufficient to assist you.

But here, I think that you used the data source `aws_nat_gateway` instead of `aws_nat_gateways`.

Please check the docs here:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/nat_gateways

Btw, I'm not the one that implemented the solution, so I don't take any real responsibility in it 😅
