### ISSUE TITLE
r/aws_s3_bucket_object: Remove ALL leading '/'s from key when destroying

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#7583]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Terraform effectively ignores _ALL_ leading `/` characters at the start of an S3 bucket object's `key` value when creating. This must be taken into account when destroying the resource (equivalent to deleting all object versions).
I found this while fixing https://github.com/terraform-providers/terraform-provider-aws/issues/7362.
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/7262
* https://github.com/terraform-providers/terraform-provider-aws/pull/7268 - This PR addressed the single `/` case only

**Comment by ewbankkit** [comment]
I've also noticed that multiple `/`s inside or at the end of a key name are compressed to a single `/`, so that `first/second//third///` and `first/second/third` are equivalent.
I'll update the PR.

**Comment by aeschright** [comment]
Hi @ewbankkit! Is #7584 the only PR left that's needed to resolve this issue?

**Comment by ewbankkit** [comment]
@aeschright Correct. #7584 will close this issue. Thanks.
