### ISSUE TITLE
Kinesis Stream Consumer

### ISSUE THREAD

**Issue by kurtmaile** [hashicorp/terraform-provider-aws#7611]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Kindly request support for this resource:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesis-streamconsumer.html

### New or Affected Resource(s)

* aws_kinesis_stream_consumer (proposed)

### Potential Terraform Configuration

As per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesis-streamconsumer.html

**Comment by bflad** [comment]
There is currently a work in progress pull request for this here: https://github.com/terraform-providers/terraform-provider-aws/pull/6565

**Comment by mikemac42** [comment]
@bflad Looks like the PR is awaiting review.

**Comment by anthonyroach** [comment]
New pull request for this issue: #17149
