### ISSUE TITLE
AWS_REGION environment variable overrides AWS_DEFAULT_REGION

### ISSUE THREAD

**Issue by DzmitrySudnik** [hashicorp/terraform-provider-aws#7622]
### Terraform Version: 0.11.8
AWS provider version: 1.38.0

### Affected Resource(s)

at least the data sources below, but I expect it to be a more general issue:
aws_instance
aws_ami

suspect that others as well

### Terraform Configuration Files

used some publicly available ami in the market:

```hcl
data "aws_ami" "found_ami" {
  most_recent      = false
  filter {
    name   = "name"
    values = ["DS-AWSLinux-v2-946312b4-a703-432b-8683-8649293d61d3-ami-40eb323f.4"]
  }
  owners = ["679593333241"]
}
output "id" {
  value = "${data.aws_ami.found_ami.id}"
}
```

### Expected Behavior

Terraform uses a region name from AWS_DEFAULT_REGION as the documentation says: https://www.terraform.io/docs/providers/aws/#environment-variables

### Actual Behavior

if AWS_REGION is set, AWS_DEFAULT_REGION is ignored

### Steps to Reproduce

scenarios:
1.  `AWS_REGION="" AWS_DEFAULT_REGION=us-east-2 terraform apply` // outputs a correct ami id for us-east-2: id = ami-97d5e7f2
2. `AWS_REGION=us-east-1 AWS_DEFAULT_REGION=us-east-1 terraform apply` // outputs a correct ami id for us-east-1: id = ami-6ee25c11
3. `AWS_REGION=us-east-1 AWS_DEFAULT_REGION=us-east-2 terraform apply`// outputs the same ami id from us-east-1 ignoring AWS_DEFAULT_REGION: id = ami-6ee25c11

**Comment by ringods** [comment]
I think this is as expected. The AWS Go SDK does the same thing:

https://github.com/aws/aws-sdk-go/blob/275272fc5c7fdea1719f5851925dc5d9df27f89d/aws/session/env_config.go#L36-L45
