### ISSUE TITLE
r/aws_vpc_peering_connection_accepter: vpc_id and peer_vpc_id not set correctly for same-account peerings

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#7703]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Discovered while testing https://github.com/terraform-providers/terraform-provider-aws/pull/7627.
For same-account VPC peering connections the `aws_vpc_peering_connection_accepter` resource is not correctly setting the `vpc_id` and `peer_vpc_id` attributes.

**Comment by aeschright** [comment]
Hi @ewbankkit! Thanks for noting this. Can you attach a config that demonstrates the problem, so someone could work on it?

**Comment by ewbankkit** [comment]
@aeschright We can use the `testAccAwsVPCPeeringConnectionAccepterConfigSameRegionSameAccount` configuration from `aws/resource_aws_vpc_peering_connection_accepter_test.go`:

```hcl
resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
  tags = {
    Name = "test"
  }
}

resource "aws_vpc" "peer" {
  cidr_block = "10.1.0.0/16"
  tags = {
    Name = "test"
  }
}

// Requester's side of the connection.
resource "aws_vpc_peering_connection" "main" {
  vpc_id      = "${aws_vpc.main.id}"
  peer_vpc_id = "${aws_vpc.peer.id}"
  auto_accept = false
  tags = {
    Name = "test"
  }
}

// Accepter's side of the connection.
resource "aws_vpc_peering_connection_accepter" "peer" {
  vpc_peering_connection_id = "${aws_vpc_peering_connection.main.id}"
  auto_accept               = true
  tags = {
    Name = "test"
  }
}
```
