### ISSUE TITLE
aws_volume_attachment.disk_attachment: doesn't support update if ebs_block_device is defined inside an ec2 instance block

### ISSUE THREAD

**Issue by Ishagusai** [hashicorp/terraform-provider-aws#7796]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.11
+ provider.aws v2.0.0

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

```hcl
{
    "resource": {
        "aws_ebs_volume": {
            "sd_blog_mysqlwordpressblog_backup_hdd": {
                "availability_zone": "ap-south-1a",
                "count": 1,
                "size": "150",
                "tags": {
                    "Name": "sd_blog_mysqlwordpressblog_mysqlbackup_standard_${(count.index)+1+6000}"
                }
            }
        },
        "aws_instance": {
            "sd_blog_mysqlwordpressblog": {
                "ami": "ami-0057655d5333a04ec",
                "associate_public_ip_address": "false",
                "availability_zone": "ap-south-1a",
                "count": 1,
                "instance_type": "t2.micro",
                "subnet_id": "subnet-020fde21756748f87",
                "tags": {
                    "Name": "blog-mysqlwordpressblog-${(count.index)+1+6000}"
                },
		"ebs_block_device": {
		"device_name" : "/dev/sdb",
		"volume_size" : "120",
		"volume_type" : "standard",
		"delete_on_termination" : "false"
		}

		}
        },
        "aws_volume_attachment": {
            "sd_blog_mysqlwordpressblog_backup_hdd_attachment": {
                "count": 1,
                "device_name": "/dev/sdh",
                "instance_id": "${element(aws_instance.sd_blog_mysqlwordpressblog.*.id, count.index)}",
                "volume_id": "${element(aws_ebs_volume.sd_blog_mysqlwordpressblog_backup_hdd.*.id, count.index)}"
            }
        }
    }
}
```

### Expected Behavior

Should only modify disk size

### Actual Behavior

Recreating an instance while modifying ebs volume  defined outside an ec2 instance resource

### Steps to Reproduce

1. `terraform apply`
Apply complete! Resources: 2 added, 0 changed, 2 destroyed.
2. `Change aws_ebs_volume disk size from 120 to 150`
3. 'terraform plan'
Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:

  ~ aws_ebs_volume.sd_blog_mysqlwordpressblog_backup_hdd
      size:                                              "150" => "180"

-/+ aws_instance.sd_blog_mysqlwordpressblog (new resource required)
      id:                                                "i-0d1f6232890ab066d" => <computed> (forces new resource)
      ami:                                               "ami-0057655d5333a04ec" => "ami-0057655d5333a04ec"
      arn:                                               "arn:aws:ec2:ap-south-1:125417324027:instance/i-0d1f6232890ab066d" => <computed>
      associate_public_ip_address:                       "false" => "false"
      availability_zone:                                 "ap-south-1a" => "ap-south-1a"
      cpu_core_count:                                    "1" => <computed>
      cpu_threads_per_core:                              "1" => <computed>
      ebs_block_device.#:                                "2" => "1"
      ebs_block_device.1376651889.delete_on_termination: "false" => "false"
      ebs_block_device.1376651889.device_name:           "/dev/sdb" => "" (forces new resource)
      ebs_block_device.2484959975.delete_on_termination: "false" => "false"
      ebs_block_device.2484959975.device_name:           "/dev/sdh" => "" (forces new resource)
      ebs_block_device.2576023345.delete_on_termination: "" => "false" (forces new resource)
      ebs_block_device.2576023345.device_name:           "" => "/dev/sdb" (forces new resource)
      ebs_block_device.2576023345.encrypted:             "" => <computed> (forces new resource)
      ebs_block_device.2576023345.snapshot_id:           "" => <computed> (forces new resource)
      ebs_block_device.2576023345.volume_id:             "" => <computed>
      ebs_block_device.2576023345.volume_size:           "" => "120" (forces new resource)
      ebs_block_device.2576023345.volume_type:           "" => "standard" (forces new resource)
      ephemeral_block_device.#:                          "0" => <computed>
      get_password_data:                                 "false" => "false"
      host_id:                                           "" => <computed>
      instance_state:                                    "running" => <computed>
      instance_type:                                     "t2.micro" => "t2.micro"
      ipv6_address_count:                                "" => <computed>
      ipv6_addresses.#:                                  "0" => <computed>
      key_name:                                          "" => <computed>
      network_interface.#:                               "0" => <computed>
      network_interface_id:                              "" => <computed>
      password_data:                                     "" => <computed>
      placement_group:                                   "" => <computed>
      primary_network_interface_id:                      "eni-042844cdb8cc359c7" => <computed>
      private_dns:                                       "ip-10-100-7-243.ap-south-1.compute.internal" => <computed>
      private_ip:                                        "10.100.7.243" => <computed>
      public_dns:                                        "" => <computed>
      public_ip:                                         "" => <computed>
      root_block_device.#:                               "1" => <computed>
      security_groups.#:                                 "0" => <computed>
      source_dest_check:                                 "true" => "true"
      subnet_id:                                         "subnet-020fde21756748f87" => "subnet-020fde21756748f87"
      tags.%:                                            "1" => "1"
      tags.Name:                                         "blog-mysqlwordpressblog-6001" => "blog-mysqlwordpressblog-6001"
      tenancy:                                           "default" => <computed>
      volume_tags.%:                                     "1" => <computed>
      vpc_security_group_ids.#:                          "1" => <computed>

-/+ aws_volume_attachment.sd_blog_mysqlwordpressblog_backup_hdd_attachment (new resource required)
      id:                                                "vai-4180866386" => <computed> (forces new resource)
      device_name:                                       "/dev/sdh" => "/dev/sdh"
      instance_id:                                       "i-0d1f6232890ab066d" => "${element(aws_instance.sd_blog_mysqlwordpressblog.*.id, count.index)}" (forces new resource)
      volume_id:                                         "vol-0b484c228297e0b9a" => "vol-0b484c228297e0b9a"

Plan: 2 to add, 1 to change, 2 to destroy.

`However its working fine if I remove ebs_block_device defined inside ec2 instance resource block.`

**Comment by deepak-goel** [comment]
+1 facing the same issue. 

@bflad Can you please take a look.

**Comment by bflad** [comment]
The usage of `ebs_block_device` configuration blocks within the `aws_instance` resource is very problematic for managing configurations longterm. Its original intention was to help support creating volumes on creation without necessarily supporting updates of those volumes later on (e.g. for simple/temporary infrastructures) as solving the update problem is much more difficult within Terraform's provider framework. I do not believe the documentation makes this usage clear though. For environments wishing to manage the EBS volumes longer term, its suggested to use the separate `aws_ebs_volume` and `aws_volume_attachment` resources (and if necessary use `ignore_changes` on existing `ebs_block_device` usage).

I have marked this ticket for triage in the documentation.

**Comment by deepak-goel** [comment]
thanks @bflad 

Is there any plan of introducing the feature of elastic volumes in `ebs_block_device` as well?

For now. we've changed our code to keep `ebs_block_device` static and do any changes on additional EBS mounts.
