### ISSUE TITLE
Support for Managing Amazon CloudSearch Domains

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#7833]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This feature request is to gauge interest in supporting Terraform resources for [Amazon CloudSearch](https://aws.amazon.com/cloudsearch/).

### New or Affected Resource(s)

* `aws_cloudsearch_domain`
* Potentially others as determined by use cases

### Potential Terraform Configuration

```hcl
# This is a stub Terraform Configuration for the feature request
# and does not contain full details.
resource "aws_cloudsearch_domain" "example" {
  name = "example"
}
```

### References

* Previous implementation attempt: https://github.com/terraform-providers/terraform-provider-aws/pull/1541
* AWS Go SDK Reference: https://docs.aws.amazon.com/sdk-for-go/api/service/cloudsearch/
* API Reference: https://docs.aws.amazon.com/cloudsearch/latest/developerguide/api-ref.html

**Comment by nelg** [comment]
I've grabbed what has already been done, added endpoints to it, and got it working against the current version of code in git.  My copy is https://github.com/nelg/terraform-provider-aws/tree/cloudsearch_try

For me, I can then use this by compiling a custom provider for aws.

**Comment by bushong1** [comment]
Any roadmap for this?

**Comment by celestialorb** [comment]
Reviving this issue with a fresh PR, based some of the work on the old #13158 CloudSearch PR.

**Comment by akappler** [comment]
Any updates here?

**Comment by dhaval2010** [comment]
Any update on this? when we will get the terraform aws cloud search support

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters roadmap. If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

**Comment by oanacioara** [comment]
Any updates on when would this be released?
