### ISSUE TITLE
ASG with mixed_instance_policy cannot have on_demand_base_capacity set to 0

### ISSUE THREAD

**Issue by MarcusNoble** [hashicorp/terraform-provider-aws#7938]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
➜ terraform -v
Terraform v0.11.13
+ provider.aws v2.1.0
```

### Affected Resource(s)

* aws_autoscaling_group

### Terraform Configuration Files

```hcl

resource "aws_autoscaling_group" "example-asg" {
  desired_capacity     = "${var.asg_desired_capacity}"
  min_size             = "${var.asg_min_size}"
  max_size             = "${var.asg_max_size}"
  name                 = "example"
  vpc_zone_identifier  = ["${split(",", var.worker_subnets)}"]

  mixed_instances_policy {
    launch_template {
      launch_template_specification {
        launch_template_id = "${aws_launch_template.example-lt.id}"
        version = "$$Latest"
      }

      override {
        instance_type = "m5.large"
      }

      override {
        instance_type = "m5.xlarge"
      }
    }
    instances_distribution {
      on_demand_base_capacity = "1"
      on_demand_percentage_above_base_capacity = "0"
    }
  }
}
```

### Expected Behavior

The on_demand_base_capacity should always be used to set the base capacity.

### Actual Behavior

When changing from a positive number to a 0 the change is ignored.

### Steps to Reproduce

1. `terraform apply`
2. Change `on_demand_base_capacity` to 0
3. `terraform apply`

### Important Factoids

Tested the tame change with the AWS CLI and the value can be successfully set to 0

**Comment by aretakisv** [comment]
I can confirm the same. Even changing it from 0 to positive number, doesn't update the ASG!

Same version on terraform pieces

**Comment by bflad** [comment]
Hmm. Version 2.1.0 specifically should have fixed the original issue report via #7821. Does `terraform plan` after the apply show the change needing to reoccur still?

**Comment by MarcusNoble** [comment]
Plan still shows no changes. Give me 5 min and I'll put up a self-contained example that can be run.

**Comment by MarcusNoble** [comment]
https://gist.github.com/MarcusNoble/3ab6f49a86a5c4c2b24b74f7f6a12d74

You just need to provide the `private_subnets` variable.

Once applied change the `on_demand_base_capacity` value to 0 and try applying again.

**Comment by MarcusNoble** [comment]
I have also tried by compiling the latest from the master branch on GitHub and it has the same issue.

**Comment by MarcusNoble** [comment]
@bflad Did you manage to verify it also wasn't working for you?

**Comment by clarkdave** [comment]
I can confirm this too.

When creating the autoscaling group, `on_demand_base_capacity` can be set to `0` and TF will create it correctly. However, if the autoscaling group is created with `on_demand_base_capacity` set to positive integer then Terraform will ignore any attempts to change it down to `0`.

Versions:

```
Terraform v0.11.13
+ provider.aws v2.6.0
```

As a workaround we're adjusting the value by hand in AWS and then modifying the terraform state to match.

**Comment by MarcusNoble** [comment]
So I did a bit more testing and this actually gets weirder. It only fails to set back to 0 when it's currently set to 1. If set to 2 then terraform will pick up the change to 0 fine. 

I have added two tests to cover this on my fork here: https://github.com/MarcusNoble/terraform-provider-aws/commit/86c4ecf78bfe513b42a15feae2a84b1e1ae298aa

**1 -> 0**
```
➜ make testacc TESTARGS='-run=TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstanceDistribution_OnDemandQuantity_1to0'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstanceDistribution_OnDemandQuantity_1to0 -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstanceDistribution_OnDemandQuantity_1to0
=== PAUSE TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstanceDistribution_OnDemandQuantity_1to0
=== CONT  TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstanceDistribution_OnDemandQuantity_1to0
--- FAIL: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstanceDistribution_OnDemandQuantity_1to0 (48.31s)
    testing.go:538: Step 2 error: Check failed: Check 4/4 error: aws_autoscaling_group.test: Attribute 'mixed_instances_policy.0.instances_distribution.0.on_demand_base_capacity' expected "0", got "1"
FAIL
FAIL    github.com/terraform-providers/terraform-provider-aws/aws       49.324s
make: *** [testacc] Error 1
```

**2 -> 0**
```
➜ make testacc TESTARGS='-run=TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstanceDistribution_OnDemandQuantity_2to0'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstanceDistribution_OnDemandQuantity_2to0 -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstanceDistribution_OnDemandQuantity_2to0
=== PAUSE TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstanceDistribution_OnDemandQuantity_2to0
=== CONT  TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstanceDistribution_OnDemandQuantity_2to0
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstanceDistribution_OnDemandQuantity_2to0 (44.88s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       45.310s

```

**Comment by MarcusNoble** [comment]
More digging led me to this fix: https://github.com/terraform-providers/terraform-provider-aws/pull/8369

@bflad I couldn't figure out what purpose the diff suppression was doing here. I think you were the one to add it in, do you think you could take a look and see if removing it causes problems elsewhere?

**Comment by andredasilvapinto** [comment]
For me it doesn't let me set it to 1

```
Error: Error creating AutoScaling Group: ValidationError: Max bound, 0, must be greater than or equal to OnDemandBaseCapacity, 1.
```

min_size, max_size and and on_demand_base_capacity are set to 1. on_demand_percentage_above_base_capacity and spot_instance_pools set to 0

This is using TFE 0.12.2 and aws provider 2.40.0

**Comment by chancez** [comment]
This seems like a pretty old bug and seems like this should get prioritized. Does this require someone to shepherd these changes?

**Comment by ewbankkit** [comment]
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/13623.
