### ISSUE TITLE
aws_iam_role_policy should validate "attribute name" collisions

### ISSUE THREAD

**Issue by NunoPinheiro** [hashicorp/terraform-provider-aws#7939]
We had accidentally a new policy that had the same name as a previous one, and it was overridden.

Would be nice if terraform failed the creation of the resource when a policy with the same name already exists

**Comment by wkoszek** [comment]
@NunoPinheiro Is it the same root cause why `terraform plan` can't figure out that 2 policies with the same name exist?

I just got, during `terraform apply`:

```Error: Error creating IAM policy segmed_prod_iam_pol_devdb: EntityAlreadyExists: A policy called segmed_prod_iam_pol_devdb already exists. Duplicate names are not allowed.
```

It's weird that `plan` can't catch this error
