### ISSUE TITLE
Feature Request: MediaConnect Output/Entitlements

### ISSUE THREAD

**Issue by adamgilman** [hashicorp/terraform-provider-aws#7940]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For MediaConnect Flows, the ability to add outputs and entitlements to a MediaConnect Flow is critical to be able to use the MediaConnect service

### New or Affected Resource(s)

* aws_elemental_mediaconnect

### Potential Terraform Configuration

```hcl
n/a
```

### References

* #7217, #7431

**Comment by bflad** [comment]
After `aws_media_connect_flow` resource is merged, recommend modeling these as two new resources:

```hcl
resource "aws_media_connect_entitlement" "example" {
  data_transfer_subscriber_fee_percent = 0
  description = ""

  encryption {
    # ...
  }

  flow_arn = aws_media_connect_flow.example.arn
  name = ""
  subscribers = [""]
}

resource "aws_media_connect_output" "example" {
  cidr_allow_list = [""]
  description = ""
  destination = ""

  encryption {
    # ...
  }

  flow_arn = aws_media_connect_flow.example.arn
  max_latency = 0
  name = ""
  port = 0
  protocol = ""
  remote_id = ""
  smoothing_latency = 0
  stream_id = ""
}
```
