### ISSUE TITLE
r/aws_kinesis_firehose_delivery_stream: Add support for s3 custom prefixes

### ISSUE THREAD

**Issue by mwarkentin** [hashicorp/terraform-provider-aws#7953]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Kinesis Firehose support for custom prefixes in s3 was [recently announced](https://aws.amazon.com/about-aws/whats-new/2019/02/amazon-kinesis-data-firehose-announces-support-for-custom-amazon-s3-prefixes/).

Documentation: https://docs.aws.amazon.com/firehose/latest/dev/s3-prefixes.html

### New or Affected Resource(s)

* Update to `aws_kinesis_firehose_delivery_stream.extended_s3_configuration`

### Potential Terraform Configuration

```hcl
resource "aws_kinesis_firehose_delivery_stream" "extended_s3_stream" {
  name        = "terraform-kinesis-firehose-extended-s3-test-stream"
  destination = "extended_s3"

  extended_s3_configuration {
    role_arn   = "${aws_iam_role.firehose_role.arn}"
    bucket_arn = "${aws_s3_bucket.bucket.arn}"

    prefix = "myPrefix/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/hour=!{timestamp:HH}/"
  }
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2019/02/amazon-kinesis-data-firehose-announces-support-for-custom-amazon-s3-prefixes/
* https://docs.aws.amazon.com/firehose/latest/dev/s3-prefixes.html
* PR adding a similar `error_output_prefix`: https://github.com/terraform-providers/terraform-provider-aws/pull/7026

**Comment by mwarkentin** [comment]
CC @ewbankkit as you seem interested in various firehose things. :)

**Comment by deepakbshetty** [comment]
@bflad, Any chances of this feature getting implemented soon ?

**Comment by Obsecurus** [comment]
@bflad any updates on this? Seems like https://github.com/terraform-providers/terraform-provider-aws/pull/11229 fixes. The language server already supports this which lead me down the path of trying to implement it only to find it hasn't been merged.

**Comment by JeffAshton** [comment]
@Obsecurus, Been sadly waiting on this one for 3 months.  :(

**Comment by anGie44** [comment]
Hi @mwarkentin @deepakbshetty @Obsecurus @JeffAshton , https://github.com/hashicorp/terraform-provider-aws/pull/11229 has been merged, addressing the missing `error_output_prefix` in the root-level `s3_configuration` block as well as in the nested `s3_backup_configuration` in `redshift_configuration` and `extended_s3_configuration`. So i believe that completes the remaining item for this issue. I'm going to go ahead and close this but if y'all feel there's something left to address please reach out!
