### ISSUE TITLE
Feature Request: Amazon ElastiCache Redis Cluster Online Add/Remove Replica

### ISSUE THREAD

**Issue by FAYiEKcbD0XFqF2QK2E4viAHg8rMm2VbjYKdjTg** [hashicorp/terraform-provider-aws#7959]
Per the documentation*, we can do online resizing of the cluster (shards)** but we cannot do this for a single shard (replicas):

    replicas_per_node_group - (Required) Specify the number of replica nodes in each node 
    group. Valid values are 0 to 5. Changing this number will force a new resource.

Given that Elasticache Redis Cluster supports adding or removing replicas online (via the AWS console, for example), it would be nice if the provider supported this as well.

*https://www.terraform.io/docs/providers/aws/r/elasticache_replication_group.html#replicas_per_node_group
** https://github.com/terraform-providers/terraform-provider-aws/issues/2904

**Comment by bflad** [comment]
Support for this functionality was released earlier today with version 3.26.0 of the Terraform AWS Provider. 👍
