### ISSUE TITLE
aws_ecs_service: enable_ecs_managed_tags doesn't apply on existing services

### ISSUE THREAD

**Issue by ericdahl** [hashicorp/terraform-provider-aws#7973]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.2
+ provider.aws v2.2.0
+ provider.template v2.1.0

### Affected Resource(s)

* aws_ecs_service

### Terraform Configuration Files

```hcl
resource "aws_ecs_service" "httpbin" {
  cluster         = "tf-cluster"
  name            = "tf-cluster-httpbin"
  task_definition = "${aws_ecs_task_definition.httpbin.arn}"
  desired_count   = "1"

  lifecycle {
    ignore_changes = ["desired_count"]
  }

//  enable_ecs_managed_tags = true
  propagate_tags = "SERVICE"

  tags {
    Name = "httpbin"
  }
}
```

### Expected Behavior

When I toggle on 
```hcl
enable_ecs_managed_tags = true
```
I expect that this feature is enabled and that this returns true:

```
aws ecs describe-services --cluster tf-cluster --services tf-cluster-httpbin | jq '.services[].enableECSManagedTags'
false
```

### Actual Behavior

Feature is not toggled on and every Terraform Plan reports that it will attempt to re-set it. It appears that this is an immutable property, as the [UpdateService](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateService.html) API does not support it (only [CreateService](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateService.html) does)

This suggests it ought to have the `ForceNew` flag enabled based on other similar properties.

### Steps to Reproduce

1. Create service with `enable_ecs_managed_tags` turned off
2. Update service to enable `enable_ecs_managed_tags`

### References

https://github.com/terraform-providers/terraform-provider-aws/pull/6544

* #0000

**Comment by rparkhunovskyi** [comment]
I can confirm the issue is still reproducible with the latest versions:
```
Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/aws v3.34.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```
