### ISSUE TITLE
Specify explicit address from BYOIP pool

### ISSUE THREAD

**Issue by shanemeyers** [hashicorp/terraform-provider-aws#8004]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We have a CIDR allocated to us by ARIN. We used the [BYOIP](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-byoip.html) functionality to bring the addresses to AWS. Now we want to use the addresses, specifying a particular IP from our pool. Currently one can only use a random address within the pool, not a specific address.

Looking at the [AWS API documentation](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AllocateAddress.html) one needs to simply include the `Address` parameter instead of `PublicIpv4Pool` and AWS will assign the IP from the proper pool.

### New or Affected Resource(s)

* aws_eip

### Potential Terraform Configuration

```hcl
resource "aws_eip" "byoip-ip" {
  vpc              = true
  address          = "1.2.3.4"
}
```

### References

* #6251
* #6521
* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AllocateAddress.html

**Comment by ravenbyron** [comment]
Any chance we can get 👀  on that PR and get this taken care of the PR has been open for over a year!!!
