### ISSUE TITLE
Drift detection on aws_cloudformation_stack

### ISSUE THREAD

**Issue by tdmalone** [hashicorp/terraform-provider-aws#8018]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Firstly, I'm not sure if this is a good fit for Terraform or not, but I have a need for it so I thought I might try raising it and seeing what people think.

Terraform is great at detecting drift. In addition, using `terraform plan -detailed-exit-code` one can easily set up a read-only CI run to fail a build when there's unresolved drift.

CloudFormation is semi-new to the drift detection game. Other than not being able to automatically correct drift, it seems to do an alright job (for supported resources, at least).

CloudFormation stacks can be 'managed' somewhat through Terraform.

I'd be interested in whether it would be workable for Terraform to include stack drift detection as part of managing the stack resource. For example, on forming a plan, Terraform could request a stack drift update, and if there is drift, automatically taint the stack resource for re-creation (this is the only way of automatically resolving drift detection on a stack, although one could likely manually resolve it with the full output from CloudFormation's APIs).

This would be likely to be a breaking change so might need some sort of special configuration to define whether drift will be detected or not.

What do people think? It's a bit different to the usual Terraform flow which makes me a little unsure, but I think it could be useful.

### New or Affected Resource(s)

* [aws_cloudformation_stack](https://www.terraform.io/docs/providers/aws/r/cloudformation_stack.html)
* [data.aws_cloudformation_stack](https://www.terraform.io/docs/providers/aws/d/cloudformation_stack.html)

**Comment by tdmalone** [comment]
Currently I'm working around this in CI with a shell script that:
- Looks for `aws_cloudformation_stack` resources (`grep --recursive 'resource "aws_cloudformation_stack" ' --include \*.tf -- *`)
- Looping through each returned line, extracts the resource name and parses its full ARN (`id`) from `terraform state show aws_cloudformation_stack.foo`
- Runs `aws cloudformation detect-stack-drift` and waits for the job to complete
- Uses `aws cloudformation describe-stack-drift-detection-status` to determine the result and `aws cloudformation describe-stack-resource-drifts` to output the relevant changes
- Exits with non-zero if an error occurred or if any stack was was not reported as `IN_SYNC`

This runs at the end of a script that has already executed `terraform fmt`, `terraform validate`, and `terraform plan -detailed-exit-code` in each folder of my project.

It works well so far - _but_ doesn't fit in nicely for situations such as cross-account roles being defined within the Terraform code. I'll _probably_ end up expanding the script somewhat to do so, but of course would love any ideas on how/whether this might be something Terraform is interested in doing natively.

**Comment by atz** [comment]
AWS-side drift detection applies to a great many features [listed here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift-resource-list.html).  

Certainly things like S3, Route53 and IAM would be very useful to have AWS detect drift in, especially in established accounts where terraform set everything up and they have just been running for a while.

**Comment by jbigtani** [comment]
Does this issue relate to what i requested for here? 
https://github.com/hashicorp/terraform/issues/26093

The issue I created is for drift detection for resources managed by terraform while this particular issue seems to be just about cloudformation stack.

**Comment by tdmalone** [comment]
@jbigtani Yeah this issue is particularly about whether there's a way for Terraform to perhaps force re-creation of an `aws_cloudformation_stack` if it fails a drift test, since Terraform doesn't directly manage the resources that the stack manages and thus can't detect (and react to) drift on them directly. It doesn't relate to any other resources.
