### ISSUE TITLE
Manual change made to S3 is ignored by terraform

### ISSUE THREAD

**Issue by hafizullah** [hashicorp/terraform-provider-aws#8051]
### Terraform Version

Terraform v0.11.11
+ provider.aws v1.59.0

### Affected Resource(s)

* aws_s3_bucket.s3

### Expected Behavior

When someone makes a manual change to S3 resource by enabling versioning, I expect Terraform to pick that change up when I run terraform plan, especially if the S3 TF resource does not have the following block. 

``` 
 versioning {
    enabled = true
  }
```

### Actual Behavior

Terraform does not see this as change, ignores it

```
aws_s3_bucket.s3: Refreshing state... (ID:test)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.
```

### Steps to Reproduce

1. create an s3 bucket without versioning enabled (using terraform)
2. Enable versioning (using AWS Console)
3. `terraform plan`

**Comment by oniric85** [comment]
I can confirm this same behavior. Is this intended? If not I'd like to take the chance to work on this as my first contribution to this project. Any hints on where to start?
