### ISSUE TITLE
Support ECS TaskSet

### ISSUE THREAD

**Issue by atsushi-ishibashi** [hashicorp/terraform-provider-aws#8124]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_ecs_task_set

### Potential Terraform Configuration

```hcl
resource "aws_ecs_task_set" "example" {
  cluster = "example"
  service = "<service arn>"
  task_definition = "<task definition>"
  ...and others
}
```

### References

https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateTaskSet.html

**Comment by mkielar** [comment]
Is there any plan on implementing that resource?

The use case here is to use it for blue/green and canary deployments with ECS and AppMesh. ECS TaskSet can be registered in CloudMap / Service Discovery under a separate name, and that name can be used in AppMesh Virtual Router to perform traffic shifting during Canary Deployment.

Without ECS TasksSets support we will either have to do that step manually (via AWS CLI), or redeploy entire ECS Services.

**Comment by bereket42** [comment]
We're waiting for the PR to get approved, no other blockers. Perhaps the following labels would help this get attention:
`needs-triage`
`new-resource`
`service/ecs`

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters roadmap. If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!
