### ISSUE TITLE
Provisioning Kinesis Analytics Application does not validate sql code

### ISSUE THREAD

**Issue by lnavarette** [hashicorp/terraform-provider-aws#8128]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.11
+ provider.aws v2.4.0
```

### Affected Resource(s)

* aws_kinesis_analytics_application

### Terraform Configuration Files

```
provider "aws" {
  region = "us-east-1"
  version = ">= 2.4.0"
}

/* create input stream */
resource "aws_kinesis_stream" "input" {
  name        = "CodeValidationReproInput"
  shard_count = 1
}

/* configure role allowing analytics app to read from input stream */
data "aws_iam_policy_document" "kinesis_assume_role_policy_document" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["kinesisanalytics.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "role" {
  name = "CodeValidationReproReadFromInputRole"
  assume_role_policy = "${data.aws_iam_policy_document.kinesis_assume_role_policy_document.json}"
}

data "aws_iam_policy_document" "policy_document" {
  statement {
    actions = ["kinesis:DescribeStream", "kinesis:GetShardIterator", "kinesis:GetRecords"]
    resources = ["${aws_kinesis_stream.input.arn}"]
  }
}

resource "aws_iam_role_policy" "role_policy" {
  name = "CodeValidationReproReadFromInputRolePolicy"
  role = "${aws_iam_role.role.id}"
  policy = "${data.aws_iam_policy_document.policy_document.json}"
}

/* create application */
resource "aws_kinesis_analytics_application" "application" {
  name = "CodeValidationReproApp"

  inputs {
    name_prefix = "SOURCE_SQL_STREAM"
    kinesis_stream {
      resource_arn = "${aws_kinesis_stream.input.arn}"
      role_arn = "${aws_iam_role.role.arn}"
    }
    parallelism {
      count = 1
    }

    schema {
      record_columns {
        mapping = "$.objectIdentifier"
        name = "OBJECT_IDENTIFIER"
        sql_type = "BIGINT"
      }
      record_encoding = "UTF-8"
      record_format {
        mapping_parameters {
          json {
            record_row_path = "$"
          }
        }
      }
    }
  }

  /* note the misspelled source stream */
  code = "CREATE OR REPLACE STREAM \"S1\" (OBJECT_IDENTIFIER BIGINT); CREATE OR REPLACE PUMP \"PUMP\" AS INSERT INTO \"S1\" SELECT STREAM OBJECT_IDENTIFIER FROM \"SOURC_SQL_STREAM_001\";"
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

An error should occur due to the invalid sql code. Per the [documentation of the golang client](https://docs.aws.amazon.com/sdk-for-go/api/service/kinesisanalytics/#KinesisAnalytics.CreateApplication),  `ErrCodeCodeValidationException` 

### Actual Behavior

The application is successfully created. In that state, it then becomes very difficult to troubleshoot the actual issue (invalid sql) because the application behaves as though it's unable to read from its input stream. 

### Steps to Reproduce

1. `terraform apply`
2. start the application
3. write data to the input stream `aws kinesis put-record --stream-name CodeValidationReproInput --partition-key "0" --data '{ "objectIdentifier": 1 }'`
4. you'll see on the cloud watch metrics for the application, no input records are received

**Comment by ewbankkit** [comment]
@lnavarette Thanks for raising this issue.
Kinesis Analytics does not validate the SQL code for an application until that application has been started:

![Screenshot 2020-11-03 153315](https://user-images.githubusercontent.com/2404182/98037786-1bbf3280-1dea-11eb-83a0-dd0109f9769e.png)
