### ISSUE TITLE
Adding server_side_encryption forces new resource

### ISSUE THREAD

**Issue by tjcobb** [hashicorp/terraform-provider-aws#8135]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_dynamodb_table

### Terraform Configuration Files

Before
```hcl
resource "aws_dynamodb_table" "test-table" {
  name = "TestTable"
  hash_key = "Id"

  read_capacity = 2
  write_capacity = 2

  attribute {
    name = "Id"
    type = "S"
  }
}
```

After 
```hcl
resource "aws_dynamodb_table" "test-table" {
  name = "TestTable"
  hash_key = "Id"

  read_capacity = 2
  write_capacity = 2

  attribute {
    name = "Id"
    type = "S"
  }

  server_side_encryption {
    enabled = true
  }
}
```

### Expected Behavior

Per the [documentation](https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html#server_side_encryption), by solely adding server side encryption to a table I would expect terraform to update the existing resource instead of re-creating the resource. 

### Actual Behavior

When I run `terraform apply` I see...
```
server_side_encryption.#:         "0" => "1"
server_side_encryption.0.enabled: "" => "true" (forces new resource)
```

This was actually working as expected for me just yesterday (3/30/19) but now it seems to be behaving differently.

**Comment by ewbankkit** [comment]
@tjcobb This is "expected" behaviour and is all down to the difference between `DEFAULT` encryption (what you get if you specify no `server_side_encryption` attribute or specify one with `enabled = false`) and `KMS` encryption (which is what you get when you specify a `server_side_encryption` attribute with `enabled = true`).
See https://github.com/terraform-providers/terraform-provider-aws/pull/7499 for more details.
Thanks.

**Comment by ewbankkit** [comment]
With https://github.com/terraform-providers/terraform-provider-aws/pull/11081, updating the `server_side_encryption` attribute no longer recreates the table but instead updates the existing table.
