### ISSUE TITLE
Feature Request: Support for EC2 Capacity Reservations for instance

### ISSUE THREAD

**Issue by Vrtak-CZ** [hashicorp/terraform-provider-aws#8189]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS have announced a new Capacity Reservation feature to reserve capacity in AZs without making long term commitments:

* https://aws.amazon.com/about-aws/whats-new/2018/10/Amazon-EC2-now-offers-On-Demand-Capacity-Reservations/
* https://aws.amazon.com/ec2/faqs/#capacityreservations

Reservations can be associated with Instance.

### New or Affected Resource(s)

* `aws_instance`

### Potential Terraform Configuration

```hcl
resource "aws_instance" "foo" {
  ami           = "ami-1234567890"
  instance_type = "t3.micro"

  capacity_reservation_specification {
    capacity_reservation_preference = "open"
    capacity_reservation_target {
      capacity_reservation_id = "cr-123456789"
    }
  }
}
```

### References

* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Instance.html
* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CapacityReservationSpecificationResponse.html

**Comment by Vrtak-CZ** [comment]
cloned from https://github.com/terraform-providers/terraform-provider-aws/issues/6323.md and extending https://github.com/terraform-providers/terraform-provider-aws/issues/6289

**Comment by skashmeri** [comment]
Any chance this is getting worked on? Im kind of stuck targeting capacity_reservations for individual EC2s, the above implementation would be most helpful!

**Comment by farhanangullia** [comment]
hey folks, i've opened a PR for this and awaiting review: #16908
