### ISSUE TITLE
Random S3 error while refreshing state

### ISSUE THREAD

**Issue by ricosega** [hashicorp/terraform-provider-aws#8255]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

terraform -v
Terraform v0.11.13
+ provider.aws v2.5.0
+ provider.template v2.1.

### Terraform Configuration Files

main.tf
```
terraform {
  backend "s3" {
    bucket    = "bucket"
    key       = "terraform.tfstate"
    region    = "region"
    role_arn  = "arn:aws:iam::00000000:role/role"
  }
}

provider "aws" {
  alias = "region_to_deploy"
  region = "${var.region}"
  assume_role {
    role_arn  = "arn:aws:iam::${var.aws_account_id}:role/role"
   }
}

module "prod" {
  source      = "modules/prod/"

  aws_project = "${var.aws_project}"
  environment = "prod"
  region      = "${var.region}"
  domain_name = "${var.domain_name}"  
}
```
S3 resource bucket file
```
resource "aws_s3_bucket" "name" {
  provider   = "aws.region_to_deploy"
  bucket = "name-${var.aws_project}"
  acl    = "private"

  versioning {
    enabled = true
  }
}
```

### Output
```
Error: Error refreshing state: 1 error(s) occurred:

* aws_s3_bucket.bucket: error getting S3 Bucket logging: RequestError: send request failed
caused by: Get https:/bucket.s3.amazonaws.com/?logging=: dial tcp: lookup bucket.s3.amazonaws.com on 127.0.0.53:53: no such host

* module.prod.aws_s3_bucket.bucket: aws_s3_bucket.bucket: error getting S3 Bucket replication: RequestError: send request failed
caused by: Get https:/bucket.s3.amazonaws.com/?replication=: dial tcp: lookup bucket.s3.amazonaws.com on 127.0.0.53:53: no such host

* module.prod.aws_s3_bucket.bucket: aws_s3_bucket.bucket: RequestError: send request failed
caused by: Get https:/bucket.s3.amazonaws.com/?versioning=: dial tcp: lookup bucket.s3.amazonaws.com on 127.0.0.53:53: no such host

* module.prod.aws_s3_bucket.bucket: aws_s3_bucket.bucket: error getting S3 Bucket request payment: RequestError: send request failed
caused by: Get https://bucket.s3.amazonaws.com/?requestPayment=: dial tcp: lookup bucket.s3.amazonaws.com on 127.0.0.53:53: no such host
```
### Expected Behavior

Terraform to work as expected, consistently.

### Actual Behavior

Intermittent error each time I try to do a `terraform apply` command.
Normally when it happens, it happens like 2 or 3 continued times and each time one of the different errors I pasted in the output. 

### Steps to Reproduce

1. `terraform apply`

**Comment by nywilken** [comment]
Hi @ricosega thanks for reporting this issue. This looks like a possible DNS resolution issue that is occurring at the time of request. Have you tried using a previous version of the provider? Or is this your first use of Terraform in this environment?

More information on the environment this issue occurred on, and if it works with prior versions of the provider would help us better understand what may be causing this lookup error. 

You can lock the provider version by declaring a version within the provider block

```
provider “aws” {
 version = “2.4.0”
}
```

Thanks!

**Comment by ricosega** [comment]
Hi @nywilken thanks for your answer. It is the first time using AWS provider.
I will lock the version as you said and will let you know how it works.
Probably today I will get back to you.

**Comment by ricosega** [comment]
Hi @nywilken just tried, and the same error occurred...
```
* module.prod.aws_s3_bucket.bucket: aws_s3_bucket.bucket: RequestError: send request failed
caused by: Get https://bucket.s3.amazonaws.com/?lifecycle=: dial tcp: lookup bucket.s3.amazonaws.com on 127.0.0.53:53: no such host
```
Tried locally and no problems:
```
✗ nslookup
> server 127.0.0.53
Default server: 127.0.0.53
Address: 127.0.0.53#53
> bucket.s3.amazonaws.com
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
bucket.s3.amazonaws.com     canonical name = s3-1-w.amazonaws.com.
Name:   s3-1-w.amazonaws.com
Address: 52.216.228.192
```
Here you can see the log with trace level.
https://gist.github.com/ricosega/3d26e85c73d9b28ee0ed16eaf8e10298
