### ISSUE TITLE
aws_listener_rule forwarding using http request methods

### ISSUE THREAD

**Issue by Richard-Prince** [hashicorp/terraform-provider-aws#8315]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating an aws alb listener rule, you cannot forward based on http request method rules. 
I.E. 
GET _example.com/items_ forwards to target group A
POST _example.com/items_ forwards to target group B

It would also be useful to use this in combination with already existing conditions, routing based on path and request method

### New or Affected Resource(s)

* aws-listener-rule

### Potential Terraform Configuration

```hcl

resource "aws_lb_listener_rule" "main" {
  listener_arn = "${var.listner-arn}"
  priority     = "${var.priority}"

  action {
    type             = "${var.action-type}"
    target_group_arn = "${var.action-target_group_arn}"
  }

  condition {
    method = "POST"
    field  = "${var.condition-field}"
    values = ["${var.condition-value}"]
  }
}
```

**Comment by sunilkumarmohanty** [comment]
I had a suggestion, instead of using `method`, how about we add separate blocks for 
`HostHeaderConfig, PathPatternConfig, HttpHeaderConfig, QueryStringConfig, HttpRequestMethodConfig and SourceIpConfig` as shown in https://docs.aws.amazon.com/cli/latest/reference/elbv2/create-rule.html

**Comment by sunilkumarmohanty** [comment]
Looks like this was fixed in https://github.com/terraform-providers/terraform-provider-aws/pull/8268

**Comment by ewbankkit** [comment]
Yes, I think this is a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/8126.
