### ISSUE TITLE
Generic aws_budgets_budget doesn't support dynamic use of cost_filters

### ISSUE THREAD

**Issue by pitthecat** [hashicorp/terraform-provider-aws#8331]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.11.13
### Affected Resource(s)
aws_budgets_budget

### Expected Behavior
I created an generic module, which can create AWS budgets

```
resource "aws_budgets_budget" "cost" {
  name              = "${var.budget_name}"
  budget_type       = "${var.budget_type}"
  limit_amount      = "${var.limit_amount}"
  limit_unit        = "${var.limit_unit}"  
  time_period_start = "${var.time_period_start}"
  time_unit         = "${var.time_unit}"

  cost_filters = {
    Service = "${var.service_filter}"
  }

  notification {
    comparison_operator = "${var.comparison_operator}"
    threshold = "${var.threshold}"
    threshold_type = "${var.threshold_type}"
    notification_type = "${var.notification_type}"
    subscriber_sns_topic_arns = ["${var.sns_arn}"]  
  }
}
```

For some use cases I want to have a cost_filter and for some use cases I don't want to filter at all.

### Actual Behavior

cost_filter is optional, but as soon as I use
```
 cost_filters = {
    Service = "${var.service_filter}"
  }
```
It sets cost_filters.% to 1 and even if I set service_filter to "" or "*" it doesn't select a single service and the budget is not working. It doesn't support empty strings or wildcards. 

It would be good to have the option to set cost_filters.% to "0" to disable filtering in an instance of the generic budget module or to allow wildcards/empty strings to select all services

**Comment by ewbankkit** [comment]
@pitthecat Thanks for raising this issue.
It has already been noticed in #13288 and #5890. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
