### ISSUE TITLE
Add timeout support for aws_ebs_volume

### ISSUE THREAD

**Issue by dawidmalina** [hashicorp/terraform-provider-aws#8349]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The problem comes when I am trying to detach volume (volume is attach during cloud-init phase) on node which are not yet fully stopped and volume is still in use. Usually 5 minute timeout is enough but there are some cases where I would need few minutes more to finish terraform destroy successfully.

### Proposal

Increase default timeout for the AWS provider or provide timeout configuration.

### New or Affected Resource(s)

* aws_ebs_snapshot
* Terraform v0.11.13

### Potential Terraform Configuration

```hcl
resource "aws_ebs_volume" "etcd_data" {
  size     = 10
  timeouts {
    create = "10m"
    delete = "10m"
  }
}
```

### References

* https://github.com/terraform-providers/terraform-provider-aws/issues/8333

**Comment by chewvader** [comment]
I've run into a similar issue but on volume creation. My use case is standing up a larger volume (few hundred GB) with type io2 built from an encrypted snapshot. I was routinely hitting the 5m timeout. With the above PR, I was able to get passed the timeout issue, but ran into something else that I assume is aws related:

```
module.main.module.ec2.aws_ebs_volume.test: Still creating... [48m41s elapsed]
module.main.module.ec2.aws_ebs_volume.test: Still creating... [48m51s elapsed]

Error: Error waiting for Volume (vol-xyz) to become available: InvalidVolume.NotFound: The volume 'vol-xyz' does not exist.
	status code: 400, request id: xyz
```
Since ^ appears to be unrelated to this issue, I'll create a new issue for it if I can't find a workaround.
