### ISSUE TITLE
Feature Request: aws_route53_resolver_endpoint data source

### ISSUE THREAD

**Issue by yorinasub17** [hashicorp/terraform-provider-aws#8355]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I have a use case where I would like to modularize constructing forwarding rules for Route 53 Resolver endpoints across peered VPCs, which requires looking up the allocated ip addresses on a resolver endpoint. It would be nice to be able to allow the consumer of the module to only provide the resolver endpoint ID, rather than having to perform the lookup themselves to extract the IP addresses.

### New or Affected Resource(s)

* data.aws_route53_resolver_endpoint

### Potential Terraform Configuration

```hcl
data "aws_route53_resolver_endpoint" "destination" {
  name = "name-of-route53-resolver-id"
  id = "route53-resolver-endpoint-id"
  arn = "route53-resolver-endpoint-arn"
}
```

### References

* PR that added the corresponding resource: https://github.com/terraform-providers/terraform-provider-aws/pull/6574

**Comment by robh007** [comment]
The route53resolver API as two actions to get an endpoint, **ListResolverEndpoints** & **GetResolverEndpoint**. The above suggestion doesn't fit with either. The **ListResolverEndpoints** takes a filter parameter & **GetResolverEndpoint** takes a required endpoint id. Also the IPaddresses for the endpoint are only returned in a subsequent call to the **ListResolverEndpointIpAddresses** action. 

So in my PR I've catered for the following, an optional ID.
```hcl
data "aws_route53_resolver_endpoint" "foo" {
  id = "rslvr-in-1a23456789bc1e23f"
}
```
Or an the ability to apply a filter.

```hcl
data "aws_route53_resolver_endpoint" "foo" {
  filter {
     name = "NAME"
     values = ["MyResolverName"]
  }
}
```
I wasn't sure if there's possibly a need for two data resources and I've been back and forth convincing myself it that's correct or not.

Hopefully what I've done isn't an anti-pattern. I did have a look through various datasources to look for any comparisons.
