### ISSUE TITLE
aws_cloudwatch_event_target ID handling is non deterministic and causes state drift

### ISSUE THREAD

**Issue by pbdeuchler** [hashicorp/terraform-provider-aws#8378]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
 → terraform -v
Terraform v0.11.11
+ provider.aws v1.41.0
+ provider.template v1.0.0
```
### Affected Resource(s)

* aws_cloudwatch_event_target

### Terraform Configuration Files

```hcl
cloudwatch-event-config = {
  name          = "example_cloudwatch_event"
  description   = "My poetic description"
  rate          = "rate(5 minutes)"
  enabled       = true
  target_id     = "example_cloudwatch_event_target"
  target_arn    = "arn:aws:lambda:us-east-1:1234:function:hello_world"
  target_input  = "{\"foo\": \"bar\"}"
}

resource "aws_cloudwatch_event_rule" "example_scheduler" {
  name                = "${var.cloudwatch-event-config["name"]}"
  description         = "${var.cloudwatch-event-config["description"]}"
  schedule_expression = "${var.cloudwatch-event-config["rate"]}" 
  is_enabled          = "${var.cloudwatch-event-config["enabled"]}" # true
}

resource "aws_cloudwatch_event_target" "example_scheduler_target" {
  target_id = "${var.cloudwatch-event-config["target_id"]}"
  rule      = "${var.cloudwatch-event-config["name"]}"
  arn       = "${var.cloudwatch-event-config["target_arn"]}"
  input     = "${var.cloudwatch-event-config["target_input"]}" # this is escaped JSON
  depends_on = ["aws_cloudwatch_event_rule.example_scheduler"]
}

```

### Expected Behavior
I expect:

- A cloudwatch event rule to be created named "example_cloudwatch_event"
- An associated cloudwatch event rule target named "example_cloudwatch_event_target" to be created with input `{"foo": "bar"}`
- The `Id` of the target to be `example_cloudwatch_event_target`
- An invocation to be immediately fired
- An invocation to be fired every five minutes after

### Actual Behavior
Seemingly non-deterministically the cloudwatch event will trigger only failed invocations (i.e. it will either succeed and successfully invoke indefinitely, or will immediately fail on its first invocation and indefinitely fail all subsequent invocations). As of right now it does not seem possible to debug or log the cause of failed cloudwatch event rule invocations, so I cannot give an error or cause. However when this happens going into the console, editing, and then updating the cloudwatch event rule (_with no changes_), seems to fix the issue. Two side effects of this remediation are:

1. The event target `Id` changes to something like `Id123456789000`
2. Terraform loses track of the event target (probably due to the above), and future plans/applies will try to re-create the target (state drift). 

You can see this via the aws cli:
```
# Before updating manually in console, invocations are failing
 → aws events list-targets-by-rule --region us-east-1 --rule "example_cloudwatch_event"
{
    "Targets": [
        {
            "Id": "example_cloudwatch_event_target",
            "Arn":  "arn:aws:lambda:us-east-1:1234:function:hello_world",
            "Input": "{\"foo\": \"bar\"}"
        }
    ]
}

# Update with no changes made in console
 → aws events list-targets-by-rule --region us-east-1 --rule "example_cloudwatch_event"
{
    "Targets": [
        {
            "Id": "Id123456789000",
            "Arn":  "arn:aws:lambda:us-east-1:1234:function:hello_world",
            "Input": "{\"foo\": \"bar\"}"
        }
    ]
}
```

I am guessing event_targets are actually immutable, and all edits remove the previous target and create an entirely new one.

### Steps to Reproduce

(see above)

### Important Factoids

It seems to me this might be a bug all the way up the stack.

1. Are we sure we want terraform generating the IDs for event targets?
2. The AWS API should not be accepting improper IDs supplied by terraform
3. Regardless of the above, I should not be able to successfully create a cloudwatch event target (with no errors) that immediately fails
4. Terraform should know that cloudwatch event targets _are immutable_ and act appropriately (editing an existing target should result in a destroy/create, not a modify)
5. If cloudwatch event targets _are not immutable_ then terraform should not use `Id` as the primary key for identifying targets (maybe a tuple of name/input?) since it is mutable

[This code](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_cloudwatch_event_target.go#L259) is suspicious to me. As you can see `Id` is only set in error cases, and the code doesn't even query by `Id`, it queries by `target_id` and `event_rule`. It seems like the code is essentially maintaining two separate primary keys here (`Id` and `target_id`) and not consistently using one or the other. For example [here](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_cloudwatch_event_target.go#L349) the code actually compares `target_id` to `Id`. These could be usually one and the same, but as the above demonstrates it's very easy to get them out of sync. The code should pick one and be consistent for simplicity/clarity, or at the very least include comments explaining why each identifier is being used. For reference, the [AWS docs](https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_Target.html) only specify the existence of `Id`, and no `target_id` attribute.

Last, I would beg any Amazon employees who maintain this project to please communicate to the cloudwatch team that logging/debugging failed invocations is a necessity. I realize this doesn't apply to this project, but it's been incredibly frustrating while trying to fix this bug and makes dealing with cloudwatch events in terraform nearly pointless since manual intervention is almost always required to fix broken targets/state drift.

I apologize if I'm barking up the wrong tree here, or if any of the above is convoluted or confusing, but there is very little information exposed by AWS to debug this issue and the non-deterministic nature is also frustrating my attempts to establish root cause/patterns. Let me know if you need any more information or clarification.

**Comment by pbdeuchler** [comment]
FWIW, this is still occurring and making cloudwatch very difficult to use with terraform

**Comment by aeschright** [comment]
Hi @pbdeuchler 👋 I'm sorry you're running into this issue. The AWS provider is entirely maintained by a team at HashiCorp, so we don't have any more insight into what's happening on the other side than you do. Can you include an example of your debug log so someone will be able to confirm they're seeing the same problem?

**Comment by gdavison** [comment]
Hi @pbdeuchler. Are you still encountering this error?

A few observations from the code you included:

1. Ensure that your Lambda function has [appropriate permissions set](https://docs.aws.amazon.com/eventbridge/latest/userguide/resource-based-policies-eventbridge.html#lambda-permissions), otherwise the CloudWatch Events Rule will not be able to invoke the function. The AWS Console will sometimes configure this for you automatically, while you need to configure it when using Terraform.

1. Terraform can handle most [dependencies between resources](https://www.terraform.io/docs/configuration/resources.html#resource-dependencies) automatically. If you set `rule = aws_cloudwatch_event_rule.example_scheduler.name` in `resource "aws_cloudwatch_event_target" "example_scheduler_target"`, you won't need to set `depends_on`.

1. I see that you're passing the Lambda function ARN as a variable. Is the Lambda function also being created by Terraform? If it's pre-existing, it can be useful to use the [data source `aws_lambda_function`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/lambda_function) to ensure that it's available.

Answers to your questions above:

1. Yes, a `target_id` is required by the AWS API

2. We validate the `target_id`s to ensure that they are valid

3. The Rule and Target are being created, but the failure is coming from another source, likely permissions on the Lambda function.

4, 5. Targets are mutable. However, if the `target_id` is changed, we re-create the Target.

**Comment by gdavison** [comment]
I haven't heard back, so I'm going to close this ticket. If you're still encountering this error, please submit a new issue.
