### ISSUE TITLE
aws_acm_certificate data: how are ties broken?

### ISSUE THREAD

**Issue by rvandegrift** [hashicorp/terraform-provider-aws#8404]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

According to the docs, `aws_acm_certificate` allows loading by domain, status, and recency.  Today, I found an account where this isn't sufficient to uniquely determine a certificate.  We have two ACM certificates issues with the same:
1. domain
1. status (`AMAZON_ISSUED`)
1. Not Before (`2018-11-09T00:00:00UTC`)
1. Issued at (`2018-11-09T00:36:26UTC`)

Their Created At fields are different.  I bet someone created both, and then fixed the validation, triggering ACM to issue otherwise identical certificates without revoking either.

How does terraform break the tie in this case?  Would it be possible to support loading ACM certificates by `arn` for this case?

### New or Affected Resource(s)

* aws_acm_certificate

**Comment by Jukie** [comment]
Isn't this data source used to lookup the arn? If you already know it ahead of time, why else would you use it?

**Comment by rvandegrift** [comment]
I like to use data sources so other resource properties are available.  You can use variables just fine, but as a config evolves, it's often useful to have the properties around.

To be honest, I don't have a use-case for `aws_acm_certificate` in particular.  Because I try to use the data sources whenever possible, I happened to stumble across this kinda strange case.

**Comment by Jukie** [comment]
Completely agree on why you'd use data sources, I enjoy using them as well. I was specifically talking about this special case because the only thing the data source returns _is_ the arn so adding the ability to accept an arn as input seemed to just be a wasted line in your config unless I'm missing something.

That said, it may be beneficial to add support for picking which value `most_recent` is sorted on.
