### ISSUE TITLE
aws_autoscaling_group creation ignores default_cooldown of 0

### ISSUE THREAD

**Issue by MissStava** [hashicorp/terraform-provider-aws#8412]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.13
+ provider.aws v2.7.0

### Affected Resource(s)

* aws_autoscaling_group

### Terraform Configuration Files

```hcl
resource "aws_launch_configuration" "test_launch" {
  image_id = "ami-08716b70cac884aaa"
  instance_type = "t2.nano"
}

resource "aws_autoscaling_group" "test_asg" {
  max_size = "1"
  min_size = "1"
  launch_configuration = "${aws_launch_configuration.test_launch.name}"
  vpc_zone_identifier = [ "subnet-079ee7da96efebb6e" ]
  default_cooldown = "0"
}
```

### Expected Behavior

Autoscaling group created with a `default_cooldown` of 0

### Actual Behavior

Autoscaling group created with a `default_cooldown` of 300

### Steps to Reproduce

1. `terraform apply`

### Further info

After the creation of the autoscaling group, if I then run `apply` again it will recognise the difference in `default_cooldown` and amend 300 down to 0.

**Comment by f3lang** [comment]
Same base problem as with #705
Pushed a fix.

**Comment by marksumm** [comment]
This still happens with AWS provider version 3.1.0
