### ISSUE TITLE
Public IP4 not assigned by default

### ISSUE THREAD

**Issue by mutt13y** [hashicorp/terraform-provider-aws#8425]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.0-beta2
+ provider.aws v2.7.0

### Affected Resource(s)

* aws_instance
* aws_subnet

### Terraform Configuration Files

```hcl
resource "aws_instance" "bastion" {
  instance_type               = local.instance["bastion"]["instance_type"]
  ami                         = data.aws_ami.amazonix.id
  subnet_id                   = aws_subnet.public[0].id
  key_name                    = var.key_name
  vpc_security_group_ids      = [aws_security_group.public.id]
  #associate_public_ip_address = true
}

resource "aws_vpc" "corp" {
  cidr_block           = var.vpc_cidr
  enable_dns_hostnames = true
}

# Define the public subnets
resource "aws_subnet" "public" {
  vpc_id                  = aws_vpc.corp.id
  count                   = length(local.aws_az)
  cidr_block              = var.public_subnet_cidr[count.index]
  availability_zone       = local.aws_az[count.index]
  map_public_ip_on_launch = true
}
```

### Expected Behavior
With the line commented as above the instance should be assigned a public IP because this is the default for the subnet.
This was the behaviour on V0.12-beta-1 / terraform-provider-aws_1.60.0-dev20190216H00-dev

### Actual Behavior

Public IP is not assigned unless the indicated line is uncommented

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Using workspaces with S3 backend

### References
Possibly related to
https://github.com/terraform-providers/terraform-provider-aws/issues/227

* #0000

**Comment by rick-masters** [comment]
I was able to reproduce this with the 0.12 beta2 and provider 2.7.0.
However, just upgrading the provider to 2.60 with that older terraform and the problem is no longer reproducible.
Nor is the problem reproducible with terraform 0.14.5.

If you are stuck on 0.12 for some reason, you can specify a provider versions like so:
terraform {
  required_providers {
    aws = "2.60.0"
  }
}

I believe this bug can be closed.
