### ISSUE TITLE
Stop using Ubuntu Precise as the AMI in the two-tier example

### ISSUE THREAD

**Issue by alex** [hashicorp/terraform-provider-aws#8438]
https://github.com/terraform-providers/terraform-provider-aws/blob/master/examples/two-tier/variables.tf#L20

Currently the AMI used in this example is Ubuntu 12.04, which is long out of support. There are no doubt people copy and pasting from these examples, so it'd be good if they at least used an AMI still receiving security support.

**Comment by HaeyoonJo** [comment]
You're right, they can use the latest version as below : 
"ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*"
or "ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-*"

**Comment by joemsak** [comment]
FWIW here are actual AMI IDs in each region:

https://github.com/joemsak/terraform-aws-2-tier-boilerplate/blob/master/variables.tf#L24

(and see this, for anyone who came here looking around wondering why the example code isn't working OOB)
https://github.com/terraform-providers/terraform-provider-aws/issues/1493#issuecomment-623280385
