### ISSUE TITLE
Docs for `aws_backup_vault` doesn't show lifecycle

### ISSUE THREAD

**Issue by heydonovan** [hashicorp/terraform-provider-aws#8452]
```
$ terraform -v
Terraform v0.11.13
+ provider.aws v2.7.0
```

We have this in our `main.tf` file, and I just noticed that `lifecycle` isn't listed on the docs:

https://www.terraform.io/docs/providers/aws/r/backup_plan.html

```
resource "aws_backup_vault" "production" {
  name        = "production"
  tags        = "${local.tags}"
  kms_key_arn = "${data.terraform_remote_state.kms.prod_default_key_arn}"

  lifecycle {
    prevent_destroy = true
  }
}
```

**Comment by bflad** [comment]
Hi @heydonovan 👋 The `lifecycle` configuration block applies to all Terraform resources and is currently documented here: https://www.terraform.io/docs/configuration/resources.html#lifecycle-lifecycle-customizations

We currently do not surface all the [Terraform Resource Meta-Arguments](https://www.terraform.io/docs/configuration/resources.html#meta-arguments) on every Terraform AWS Provider resource documentation page, but we could theoretically link out to that page by adding a quick byline underneath each resources' **Arguments Reference** header such as:

```markdown
## Arguments Reference

In addition to the [Terraform Resource Meta-Arguments](https://www.terraform.io/docs/configuration/resources.html#meta-arguments), the following is supported:

* `attribute1` - ...
```

I will float this around to the other maintainers and see what they think.
