### ISSUE TITLE
aws_volume_attachment does not recognise attachment when changed to a list

### ISSUE THREAD

**Issue by mutt13y** [hashicorp/terraform-provider-aws#8474]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.0-beta2
+ provider.aws v2.7.0

### Affected Resource(s)

* aws_volume_attachment

### Terraform Configuration Files

Initial apply
```hcl
resource "aws_instance" "jira" {
  instance_type          = local.instance["jira"]["instance_type"]
  ami                    = data.aws_ami.Centos7.id
  subnet_id              = aws_subnet.mw[0].id
  key_name               = var.key_name
  vpc_security_group_ids = [aws_security_group.mw.id]
  iam_instance_profile   = aws_iam_instance_profile.installers.name
  monitoring             = true
  ebs_optimized          = true
  root_block_device {
    volume_size = 60
    volume_type = "gp2"
  }
}

resource "aws_ebs_volume" "jira" {
  availability_zone = local.aws_az[0]
  size              = 100
  type              = "gp2"
  tags = merge(local.tags, {
    Name = "Jira",
  })
}

resource "aws_volume_attachment" "opt_atlassian_jira" {
  device_name = "/dev/xvdf"
  volume_id   = aws_ebs_volume.jira.id
  instance_id = aws_instance.jira.id
}
```

Change to
```
resource "aws_instance" "jira" {                                           
  count                  = 1            
  instance_type          = local.instance["jira"]["instance_type"] 
  ami                    = data.aws_ami.Centos7.id
  subnet_id              = element(aws_subnet.mw.*.id, count.index)
  key_name               = var.key_name                               
  vpc_security_group_ids = [aws_security_group.mw.id]            
  iam_instance_profile   = aws_iam_instance_profile.installers.name
  monitoring             = true                                          
  ebs_optimized          = true                                                        
  root_block_device {                                              
    volume_size = 60                   
    volume_type = "gp2"           
  }                                 
 }                                           
                                                              
resource "aws_ebs_volume" "jira" {  
  count             = 1
  availability_zone = element(local.aws_az.*, count.index)
  size              = 100                              
  type              = "gp2"           
  tags = merge(local.tags, {                                      
    Name = "Jira",                                
  })                                          
}                                      
                                                     
resource "aws_volume_attachment" "opt_atlassian_jira" {                 
  count       = 1                       
  device_name = "/dev/xvdf"
  volume_id   = aws_ebs_volume.jira[count.index].id
  instance_id = aws_instance.jira[count.index].id
}

```
### Debug Output

terraform plan

```
  # aws_volume_attachment.opt_atlassian_jira[0] will be created
  + resource "aws_volume_attachment" "opt_atlassian_jira" {
      + device_name = "/dev/xvdf"
      + id          = (known after apply)
      + instance_id = "i-nnnnnnnnnnnnn"
      + volume_id   = "vol-nnnnnnnnnnn"
    }


```

terraform apply

```
Error: Error attaching volume (vol-nnnnnnnnn) to instance (i-nnnnnnnn), message: "vol-nnnnnnn is already attached to an instance", code: "VolumeInUse"

  on virtual_machines.tf line 55, in resource "aws_volume_attachment" "opt_atlassian_jira":
  55: resource "aws_volume_attachment" "opt_atlassian_jira" {


```
### Expected Behavior

Terraform should recognise that the volume is already attached to the instance

### Actual Behavior

Terraform tries to attach the volume again

### Steps to Reproduce

1. `terraform apply`
1. Change attachment resource to a count of 1
1. `terraform plan`

### Important Factoids

S3 backend
using workspaces

if I detach the volume manually and run `terraform apply` it sorts itself out.

### References

* #0000

**Comment by nywilken** [comment]
Hi @mutt13y sorry you're running into trouble here. By changing the single resource to a list of resources using count you are essentially changing the identifier of the `aws_volume_attachment` configuration from `aws_volume_attachment.opt_atlassian_jira` to `aws_volume_attachment.opt_atlassian_jira[0]` which Terraform will register as a new resource because the unique identifier `aws_volume_attachment.opt_atlassian_jira[0]` is not under Terraform management according to your state. 

The appropriate step to take after changing the resource identifier would be to import the existing attachment, but that is not something the `aws_volume_attachment` resource currently supports. I'm going to re-title this issue and label it as an enhancement request to add import support to the `aws_volume_attachment` resource.

**Comment by mutt13y** [comment]
Hi @nywilken,
What you say makes sense, however the aws_instrance and the aws_ebs_volume do support the change to a list. Only the attachment failed.

Additionally: aws_volume_attachment.opt_atlassian_jira was under terraform control and is no longer in the manifest so why wasn't it deleted?

It terraform deleted the missing attachment before creating the new one, as it does for most resources, I think it would work; because all I did to fix it was delete the attachment manually.

Thanks
Stuart
