### ISSUE TITLE
r/aws_lb_listener_rule: Support reserved IDs for priority

### ISSUE THREAD

**Issue by FernandoMiguel** [hashicorp/terraform-provider-aws#8478]
### Description

Current https://www.terraform.io/docs/providers/aws/r/lb_listener_rule.html#priority supports values from 1 to 50000
But if user wants to choose some to manually enter in some modules, while leaving others dynamic, the dynamic ones might take the lower ones we intended to use manually.

My proposal is for either a reserve pool or lower number to be set from where terraform would assigned new priority IDs.

SO if I want to enter 1 and 2 manual, but every other resource from 3 and above dynamically, 3 would be the lower limit.

### New or Affected Resource(s)

* aws_lb_listener_rule

### Potential Terraform Configuration

```hcl
resource "aws_lb_listener_rule" "static" {
  listener_arn = "${aws_lb_listener.front_end.arn}"
  priority     = 1

  action {
    type             = "forward"
    target_group_arn = "${aws_lb_target_group.static.arn}"
  }

  condition {
    field  = "path-pattern"
    values = ["/static/*"]
  }
}

resource "aws_lb_listener_rule" "host_based_routing" {
  listener_arn        = "${var.alb_listener_arn}"
  priority_prefix     = 3


  action {
    type             = "forward"
    target_group_arn = "${aws_lb_target_group.target-group.arn}"
  }

  condition {
    field  = "host-header"
    values = ["${var.domain}"]
  }
}
```

`priority_prefix` would be a new optional attribute

**Comment by jmaggio** [comment]
You can reproduce this quite easily by creating two listener rules: One with priority set to 50000, the lowest possible value, and one with priority unset. 

Currently the provider will create the priority 50000 rule and then attempt to create a rule with priority 50001 and fail.
