### ISSUE TITLE
Elastic Fabric Adapter for EC2 instances

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#8487]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

EFA network interfaces for EC2 instances [now](https://aws.amazon.com/about-aws/whats-new/2019/04/elastic-fabric-adapter-is-now-generally-available/) [available](https://aws.amazon.com/blogs/aws/now-available-elastic-fabric-adapter-efa-for-tightly-coupled-hpc-workloads/).

**Comment by ewbankkit** [comment]
Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/8482

**Comment by ewbankkit** [comment]
At a first glance this looks like
* Addition of an `interface_type` attribute to the [`aws_network_interface`](https://www.terraform.io/docs/providers/aws/r/network_interface.html) resource and data source
* Addition of an `interface_type` attribute to the [`aws_launch_template`](https://www.terraform.io/docs/providers/aws/r/launch_template.html) resource's and data source's `network_interfaces` attribute
* Addition of an `interface_type` attribute to the [`aws_instance`](https://www.terraform.io/docs/providers/aws/r/instance.html) resource's `network_interface` attribute

**Comment by rashisht1** [comment]
Commenting because I would love to see the change https://github.com/hashicorp/terraform-provider-aws/pull/18841 get in soon. Seems like an easy change
