### ISSUE TITLE
r/aws_vpn_connection: Allow migration from VGW to TGW without recreating resource

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#8500]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

As of [AWS SDK v1.19.22](https://github.com/aws/aws-sdk-go/releases/tag/v1.19.22) VPN Connections can be migrated from VGW to TGW w/o recreation:
> This release adds an API for the modification of a VPN Connection, enabling migration from a Virtual Private Gateway (VGW) to a Transit Gateway (TGW), while preserving the VPN endpoint IP addresses on the AWS side as well as the tunnel options.

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/8482

**Comment by ewbankkit** [comment]
The [`ModifyVpnConnection`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyVpnConnection.html) API allows migration of:
* An existing virtual private gateway to a new virtual private gateway
* An existing virtual private gateway to a transit gateway
* An existing transit gateway to a new transit gateway
* An existing transit gateway to a virtual private gateway

**Comment by abohne** [comment]
Any update?

**Comment by ewbankkit** [comment]
Relates #11284.
