### ISSUE TITLE
Support for RDS Reserved Instances

### ISSUE THREAD

**Issue by davidcelis** [hashicorp/terraform-provider-aws#8521]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Like EC2, Amazon's RDS system also allows the purchase of [reserved instances](https://aws.amazon.com/rds/reserved-instances/) which are used if compatible RDS instances are spun up. It'd be cool if the AWS provider supported the creation of these!

### New or Affected Resource(s)

* aws_rds_reserved_instance

### Potential Terraform Configuration

```hcl
provider "aws" {}

resource "aws_rds_reserved_instance" "my-reservation" {
  offering_id = "438012d3-4052-4cc7-b2e3-8d3372e0e706"
  reservation_id = "optionalCustomReservationID"
  instance_count = 3

  tags = {}
}
```

### References

https://docs.aws.amazon.com/cli/latest/reference/rds/purchase-reserved-db-instances-offering.html

**Comment by debu99** [comment]
+1

**Comment by LouisMaycol** [comment]
Are there any plans when can this be done? Kinda need this too

**Comment by joshuaganger** [comment]
Is there actually support for EC2 reserved instances?  The only documentation I can find is regarding capacity reservations which is a different concept entirely.

**Comment by davidcelis** [comment]
@joshuaganger Doesn't look like it, though I made no claim that the AWS provider supports EC2 reserved instances; I only said that they exist 😉

**Comment by sjoby** [comment]
Would like to see this as well. It would be nice to manage this through code as well.

**Comment by RafeKettler** [comment]
This would also be useful for aws_elasticsearch_domain resources as well. Not sure if that warrants a separate ticket, probably not given there is a broader effort to support reserved instances in terraform-provider-aws in the first place.

**Comment by jspiro** [comment]
+1

**Comment by kclinden** [comment]
+1

**Comment by johnB96** [comment]
+1, devs still want this

**Comment by YakDriver** [comment]
Relevant operations:

* [DescribeReservedDBInstances](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeReservedDBInstances.html)
* [DescribeReservedDBInstancesOfferings](https://docs.aws.amazon.com/goto/WebAPI/rds-2014-10-31/DescribeReservedDBInstancesOfferings)
* [PurchaseReservedDBInstancesOffering](https://docs.aws.amazon.com/goto/WebAPI/rds-2014-10-31/PurchaseReservedDBInstancesOffering)

**Comment by tocy1** [comment]
+1
