### ISSUE TITLE
InvalidTarget from aws_lb_target_group_attachment resources

### ISSUE THREAD

**Issue by jbarrick-mesosphere** [hashicorp/terraform-provider-aws#8537]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

* Terraform 0.11.13.
* Provider is built from master.

### Affected Resource(s)

* aws_lb_target_group_attachment

### Expected Behavior

AWS lb target groups should get attached.

### Actual Behavior

AWS lb target group fail to attach:

```
[19:13:51][Step 4/8] * aws_lb_target_group_attachment.attachment.0: Error registering targets with target group: InvalidTarget: The following targets are not in a running state and cannot be registered: 'i-05c40e7752fcba175'
[19:13:51][Step 4/8] 	status code: 400, request id: 515e8cae-7031-11e9-8e15-0d3d08d0af22
```

This issue was fixed recently for the elb_attachment resource (#8483), but also affects aws_lb_target_group_atachment.

**Comment by gdavison** [comment]
The PR #8538 was merged manually
