### ISSUE TITLE
Add lambda_layer_version_permission resource

### ISSUE THREAD

**Issue by acburdine** [hashicorp/terraform-provider-aws#8595]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Related to #6651, specifically [this comment](https://github.com/terraform-providers/terraform-provider-aws/issues/6651#issuecomment-454431427) a new resource (`aws_lambda_layer_version_permission`) needs to be created to support cross-account access to lambda layer versions.

### New or Affected Resource(s)

* `aws_lambda_layer_version_permission`

### Potential Terraform Configuration

```hcl
resource "aws_lambda_layer_version_permission" "example" {
  statement_id  = "allow org access"
  action        = "lambda:GetLayerVersion"
  layer_name    = "${aws_lambda_layer_version.example.layer_name}"
  principal     = "*"
  version       = "${aws_lambda_layer_version.example.version}"
  organization  = "o-123456789"
}
```

### References

* #6651

**Comment by fred-vogt** [comment]
A workaround for the time being is to use the CLI:
```bash
export AWS_PROFILE=...
org_id=$(cd ...; terraform output -json organization | jq -r '.id')

aws lambda add-layer-version-permission \
--layer-name "<layer-name>" \
--version-number <N> \
--statement-id xaccount-getlayerversion \
--action lambda:GetLayerVersion \
--principal '*' \
--organization-id "$org_id" \
--output text
```

Strange, but the AWS console seems to have no UI showing lambda layer resource policies.

**Comment by quickmute** [comment]
Another workaround is a CW_Event trigger that runs a lambda function that adds the permission when a new layer version is detected. 

And another workaround is a local-exec to add the new permission during apply time.

**Comment by jrobison-sb** [comment]
Since we're collecting workarounds here... the one I settled on was to deploy the lambda layer permission via Cloudformation via Terraform:

```
resource "aws_cloudformation_stack" "foo" {
  name = "lambda-layer-permission-cfn-stack"
  template_body = jsonencode(
    {
      Description = "Lambda layer permission cant be done directly in Terraform currently."
      Resources = {
        LambdaLayerPermission = {
          Type = "AWS::Lambda::LayerVersionPermission"
          Properties = {
            Action          = "lambda:GetLayerVersion"
            LayerVersionArn = aws_lambda_layer_version.foo.arn
            OrganizationId  = data.aws_organizations_organization.foo.id
            Principal       = "*"
          }
        }
      }
    }
  )
}
```

The same hack works for anything that Cloudformation supports and Terraform doesn't.

A local-exec provisioner workaround would work only upon _creation_ of a Lambda layer, it wouldn't fire if the layer was updated/changed.
