### ISSUE TITLE
aws_autoscaling_group not modified by recreation of aws_launch_configuration dependency

### ISSUE THREAD

**Issue by erbridge** [hashicorp/terraform-provider-aws#8638]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.13
+ provider.aws v2.10.0
+ provider.template v2.1.2

### Affected Resource(s)

* aws_autoscaling_group

### Terraform Configuration Files

```hcl
resource "aws_key_pair" "ecs" {
  key_name_prefix = "${var.ecs_cluster_name}-"
  public_key      = "${var.ecs_ssh_public_key}"
}

resource "aws_launch_configuration" "ecs-launch-configuration" {
  image_id                    = "${var.image_id}"
  instance_type               = "${var.instance_type}"
  iam_instance_profile        = "${var.aws_iam_ecs_instance_profile_name}"
  security_groups             = ["${aws_security_group.default.id}", "${aws_security_group.ecs.id}"]
  associate_public_ip_address = "true"
  key_name                    = "${aws_key_pair.ecs.key_name}"
  user_data                   = "${data.template_file.ecs-launch-configuration-user-data.rendered}"

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_autoscaling_group" "ecs-autoscaling-group" {
  name = "${var.project_name}-${var.environment}-${var.asg_name}-${aws_launch_configuration.ecs-launch-configuration.name}"

  availability_zones  = "${var.availability_zones}"
  vpc_zone_identifier = ["${aws_subnet.public_subnet.*.id}"]

  max_size         = "${var.asg_max_size}"
  min_size         = "${var.asg_min_size}"
  desired_capacity = "${var.asg_desired_size}"
  min_elb_capacity = "${var.asg_min_size}"

  launch_configuration = "${aws_launch_configuration.ecs-launch-configuration.name}"

  health_check_type = "ELB"

  tags = [
    {
      key                 = "Name"
      value               = "${var.project_name}-${var.environment}"
      propagate_at_launch = true
    },
  ]

  lifecycle {
    ignore_changes = ["desired_capacity"]

    create_before_destroy = true
  }
}
```

### Expected Behavior

Changes to `aws_key_pair.ecs` resulting in `-/+ aws_launch_configuration.ecs-launch-configuration` should trigger `-/+ aws_autoscaling_group.ecs-autoscaling-group`.

### Actual Behavior

Changes to `aws_key_pair.ecs` result in `-/+ aws_launch_configuration.ecs-launch-configuration`, but no changes to the autoscaling group.

Removing `"desired_capacity"` from `ignore_changes` fixes the plan.

### Steps to Reproduce

1. Change `var.ecs_ssh_public_key`
2. `terraform plan` and see no `-/+ aws_autoscaling_group.ecs-autoscaling-group`
3. Remove `"desired_capacity"` from `ignore_changes`
3. `terraform plan` and see `-/+ aws_autoscaling_group.ecs-autoscaling-group`

**Comment by bflad** [comment]
I'm not sure how I remembered there was an upstream Terraform core bug related to this, but here we go: https://github.com/hashicorp/terraform/issues/17855

The combination of `create_before_destroy` and `ignore_changes` might be problematic in this scenario. I'm not sure if there is any workaround in Terraform configurations (other than doing what you did) or code changes we can make in the Terraform AWS Provider to help at the moment.
