### ISSUE TITLE
The "aws_ssm_maintenance_window_target" resource when using "target_install" allows you to create targets with invalid characters in the tag value

### ISSUE THREAD

**Issue by waqarkhan3389** [hashicorp/terraform-provider-aws#8645]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.13

### Affected Resource(s)

* aws_ssm_maintenance_window_target

### Terraform Configuration Files

```hcl
resource "aws_ssm_maintenance_window_target" "target_install" {
  window_id     = "${aws_ssm_maintenance_window.install_window.id}"
  resource_type = "INSTANCE"

  targets {
    key    = "PatchGroups"
    values = ["windows,linux"]
  }
}
```
### Expected Behavior

Should not create target with valid tags value. Console does not allow creation of tag values with comma in the value 

### Actual Behavior

Creates the target

### Steps to Reproduce

1. `terraform apply`

**Comment by waqark3389** [comment]
Any feedback here?
