### ISSUE TITLE
Region Differences Appears to Cause "Error putting S3 ACL: AccessDenied: Access Denied"

### ISSUE THREAD

**Issue by rcuza** [hashicorp/terraform-provider-aws#867]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.9.8

### Affected Resource(s)
Please list the resources as a list, for example:
- `aws_s3_bucket`

This may be related to `terraform core`.

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-east-1"
}
resource "aws_s3_bucket" "unique-bucket" {
  bucket_prefix = "unique-bucket-"
  region = "us-west-2"
}
```

### Debug Output
https://gist.github.com/rcuza/f5d160cfd12097d98e02882390326520

### Panic Output
N/A

### Expected Behavior
When I run `terraform apply` I would expect the S3 bucket to get created and to be able to makes changes to the bucket including destroying it.

If this is not possible, I would expect `terraform` to provide a useful error indicating that the bucket region must match the provider region.

### Actual Behavior
The bucket gets created but every command after its creation fails with the error `* aws_s3_bucket.unique-bucket: Error putting S3 ACL: AccessDenied: Access Denied`. If I edit the `provider` section so the region matches the bucket, then the configuration works as expected.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
Need an AWS account to reproduce the problem.

### References

- #762 might be related

**Comment by mgeggie** [comment]
I'm also having the same issue failing to apply the ACL to a aws_s3_bucket in an alternate region.

I'm trying to setup s3 bucket replication to replicate a bucket containing our AWS Lambda functions between regions, since it also appears that Lambda can only fetch its functions from a region-local bucket.

**Comment by vibhuyadav** [comment]
Getting the same error

**Comment by knope** [comment]
Still getting this error in 0.12.5
