### ISSUE TITLE
aws_acm_certificate_validation forces new resource every time we run terraform plan

### ISSUE THREAD

**Issue by ani-patel** [hashicorp/terraform-provider-aws#8714]
Hi,

I am facing an issue where my aws_acm_certificate_validation is forcing new resource every time I do a `terraform plan` or `terraform apply` and as a result even the route 53 records are updated with their Guids

To replicate the issue below is a sample code:
```terraform
resource "aws_acm_certificate" "cert" {
  domain_name               = "${var.domain_name}"
  validation_method         = "DNS"
  subject_alternative_names = "${var.subject_alternative_names}"

  lifecycle {
    create_before_destroy = true
  }
}

# Creates route 53 records for validation of DNS
resource "aws_route53_record" "cert_validation" {
  # The number of records to be created
  count   = "${length(var.subject_alternative_names) + 1}"
  name    = "${lookup(aws_acm_certificate.cert.domain_validation_options[count.index], "resource_record_name")}"
  type    = "${lookup(aws_acm_certificate.cert.domain_validation_options[count.index], "resource_record_type")}"
  records = ["${lookup(aws_acm_certificate.cert.domain_validation_options[count.index], "resource_record_value")}"]
  zone_id = "${var.zone_id}"
  ttl     = 60
}

#  Validates the ACM certificate
resource "aws_acm_certificate_validation" "cert" {
  certificate_arn         = "${aws_acm_certificate.cert.arn}"
  validation_record_fqdns = ["${aws_route53_record.cert_validation.*.fqdn}"]
}

resource "null_resource" "dependency_setter" {
  depends_on = [
    "aws_acm_certificate_validation.cert",
  ]
}
```

This was not happening until a week back but we are facing these issues since then

**Comment by nickdgriffin** [comment]
Duplicate of #8531 I believe.

**Comment by nywilken** [comment]
@ani-patel thanks for opening this issue, and sorry you are running into trouble here. This is a duplicate of #8531 so I am going to close this issue and ask that any new comments be tracked on the existing thread. If you haven't already done so please upvote #8531

**Comment by ani-patel** [comment]
Hi Nick,

This is different than #8531. My affected resource is
"aws_acm_certificate_validation". The certificate is not recreated every
time but instead the validation is performed again and again

**Comment by Michaelerker** [comment]
@nywilken 

Please reopen this issue. It is not a duplicate of 8531. As @ani-patel  mentioned, this issue is specific to the certificate validation, NOT the certificate itself. 

Thank you!

**Comment by nywilken** [comment]
@MeMan-MasterOfTheUniverse @ani-patel thanks for the additional information here, and my apologies for any confusion. I reopened the issue and have applied the needs-triage label. Have you tried reproducing this issue with Terraform 0.12? If so can you please provide a redacted version of the plan output.

**Comment by johnhpatton** [comment]
I am also experiencing this.  Validation is forcing a new resource every time and can take up to 45 minutes before it errors out.

**Comment by vlechemin** [comment]
As a workaround, I added `ignore_changes` on the field `id` which was the current date/time:
```terraform

resource "aws_acm_certificate_validation" "certificate" {
    [...]

    lifecycle {
        ignore_changes = [
            "id",
        ]
    }
}
```
