### ISSUE TITLE
Add Amazon Lightsail Managed Databases Support

### ISSUE THREAD

**Issue by weaversam8** [hashicorp/terraform-provider-aws#8719]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As described [here](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-databases), Amazon Lightsail has the ability to create managed databases. This uses the underlying technology AWS uses in RDS, but the databases aren't viewable in RDS, and are therefore not covered by the `aws_db_instance` resource type. I'm not sure how recent of an addition this is, but we lack a resource type for this currently.

It looks like this might be a substantial implementation- I haven't investigated any of the existing implementations for Terraform Database Resources, but there's a lot of different options here on the official Amazon Lightsail API for databases.

### New or Affected Resource(s)

A proposed resource name is:
* `aws_lightsail_database`

### Potential Terraform Configuration

I'm fairly new to Terraform, but I've attempted to write a proposed resource configuration below.

```hcl
resource "aws_lightsail_database" "database_instance_name_here" {
  name              = "Database Instance"
  availability_zone = "us-east-1a"
  blueprint_id      = "mysql" # or (`postgresql`)
  bundle_id         = "???" # not sure what would go here
  # and we would probably need some additional configuration here for credentials
}
```

### References

* [Databases in Amazon Lightsail](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-databases)
* [Press Release: New – Managed Databases for Amazon Lightsail by Jeff Barr](https://aws.amazon.com/blogs/aws/new-managed-databases-for-amazon-lightsail/)
* [Amazon Lightsail API Documentation](https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/Welcome.html)
  * [`CreateRelationalDatabase` action from Amazon Lightsail API Documentation](https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_CreateRelationalDatabase.html)
  * [`GetRelationalDatabase` action from Amazon Lightsail API Documentation](https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_GetRelationalDatabase.html)
  * [`UpdateRelationalDatabase` action from Amazon Lightsail API Documentation](https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_UpdateRelationalDatabase.html)
  * [`DeleteRelationalDatabase` action from Amazon Lightsail API Documentation](https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_DeleteRelationalDatabase.html)

**Comment by brittandeyoung** [comment]
I have an open pull request to resolve this issue. I am commenting to show that I still want this issue resolved as it has been marked stale.

**Comment by brittandeyoung** [comment]
For Awareness I have begun work on creating a separate AWS lightsail provider in order to help with Speeding up contributions and to give it dedicated attention. 

The Github repo is located here: https://github.com/DeYoungTech/terraform-provider-awslightsail

The provider and documentation is published here: https://registry.terraform.io/providers/DeYoungTech/awslightsail/latest

With the most recent version, I have added support for the `database`  resource.

If you want to start using this resource now, feel free to check it out and provide feedback.
