### ISSUE TITLE
AWS Device Farm tagging

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#8745]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

As of  [AWS SDK v1.19.36](https://github.com/aws/aws-sdk-go/releases/tag/v1.19.36) AWS Device Farm resources can be tagged:
> This release introduces support for tagging, tag-based access control, and resource-based access control.

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/8742

**Comment by ewbankkit** [comment]
Affected resources:
* [`aws_devicefarm_project`](https://www.terraform.io/docs/providers/aws/r/devicefarm_project.html)

**Comment by garrett-hopper** [comment]
Still needed
