### ISSUE TITLE
AWS CodeDeploy application and deployment group tagging

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#8774]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of  [AWS SDK v1.19.38](https://github.com/aws/aws-sdk-go/releases/tag/v1.19.38) AWS CodeDeploy application and deployment group resources can be tagged:
> AWS CodeDeploy now supports tagging for the application and deployment group resources.

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/8770

**Comment by ewbankkit** [comment]
Affected resources:
* [`aws_codedeploy_app`](https://www.terraform.io/docs/providers/aws/r/codedeploy_app.html)
* [`aws_codedeploy_deployment_group`](https://www.terraform.io/docs/providers/aws/r/codedeploy_deployment_group.html)

**Comment by anGie44** [comment]
Completed w/merge of #18564 and #18716
