### ISSUE TITLE
`aws_backup_plan` should check for invalid `start_window`during plan/validate

### ISSUE THREAD

**Issue by smiller171** [hashicorp/terraform-provider-aws#8794]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14

### Affected Resource(s)

* aws_backup_plan

### Terraform Configuration Files

```hcl
resource "aws_backup_plan" "example" {
  name     = "example-backup-plan"

  rule {
    rule_name         = "nightly-backup"
    target_vault_name = "${aws_backup_vault.example.name}"
    schedule          = "cron(0 20 * * ? *)"
    start_window      = 30

    lifecycle {
      cold_storage_after = 30
      delete_after       = 120
    }
  }
}
```

### Expected Behavior

I expect `terraform plan` to inform me that the minimum `start_window` is 60 minutes

### Actual Behavior

Terraform didn't tell me about the invalid config until I tried to apply

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

**Comment by ewbankkit** [comment]
@smiller171 Unfortunately the valid values of this attribute are not documented in the [relevant AWS API documentation](https://docs.aws.amazon.com/aws-backup/latest/devguide/API_BackupRuleInput.html) which is how we normally determine whether or not to add a plan-time validation.

**Comment by smiller171** [comment]
@ewaltman Is _that_ why there are so many validations missing in this provider? That would explain a lot.

**Comment by DrFaust92** [comment]
Closing as this is a gap in AWS Docs and no way to verify what values ranges are used to validate. Please contact AWS support to update docs and reopen if needed.
