### ISSUE TITLE
Add IoT Thing Group

### ISSUE THREAD

**Issue by rpstreef** [hashicorp/terraform-provider-aws#8801]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Groups are helpful administrating policies across large numbers of iot things.

### New or Affected Resource(s)

New resource based on:
https://docs.aws.amazon.com/cli/latest/reference/iot/create-thing-group.html

**Comment by WendtWithers** [comment]
This would be very helpful - as long as you also make sure that policies can be attached to thing groups that get inherited down the line. That greatly simplifies control of permissions for large numbers of things. You already have an aws_iot_thing_principal_attachment resource, so either modify that to work with thing groups, or create something similar just for thing groups. (based on https://docs.aws.amazon.com/cli/latest/reference/iot/attach-policy.html) Thanks!

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters roadmap. If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!
