### ISSUE TITLE
aws_rds_cluster_instance missing option_group_name

### ISSUE THREAD

**Issue by jpSimkins** [hashicorp/terraform-provider-aws#8847]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is no ability to assign a `option_group_name` to the `aws_rds_cluster_instance`. This ability is available for the [db_instance](https://www.terraform.io/docs/providers/aws/r/db_instance.html) but not for the aws_rds_cluster_instance. This makes it impossible to associate the option group to the cluster.

This is not to be confused with the `db_parameter_group_name` as these are not the same.

### New or Affected Resource(s)

* aws_rds_cluster_instance

**Comment by Jukie** [comment]
I'll work on this

**Comment by Jukie** [comment]
I noticed that it's missing a lot of other arguments as well so I'll be adding others too.

**Comment by mkubenka** [comment]
Btw. Aurora does not support setting option group and API call will result with following error:

```
Option groups are not supported for DB Clusters
```
