### ISSUE TITLE
aws_waf_xss_match_set permanent diff as of 2.7.0

### ISSUE THREAD

**Issue by vobarian** [hashicorp/terraform-provider-aws#8865]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.1
+ provider.aws v2.13.0
```
Problem occurs with provider 2.7.0 and 2.13.0. The problem did not occur in 2.6.0. Problem also occurs when using Terraform 0.11.4.

### Affected Resource(s)

* aws_waf_xss_match_set

### Terraform Configuration Files

```hcl
provider "aws" {
  version= "2.13.0"
  region = "us-east-1"
}

resource "aws_waf_xss_match_set" "WAFXssDetection" {
  name = "test"

  xss_match_tuples {
    text_transformation = "URL_DECODE"

    field_to_match {
      type = "QUERY_STRING"
      data = "none"
    }
  }
}
```

### Expected Behavior

No diff occurs when running plan after a successful apply.

### Actual Behavior

The following diff shows no matter how many times it is applied.
```
Terraform will perform the following actions:

  # aws_waf_xss_match_set.WAFXssDetection will be updated in-place
  ~ resource "aws_waf_xss_match_set" "WAFXssDetection" {
        id   = "866cd618-4287-42e0-81e3-3b1eaf7c4a95"
        name = "test"

      - xss_match_tuples {
          - text_transformation = "URL_DECODE" -> null

          - field_to_match {
              - type = "QUERY_STRING" -> null
            }
        }
      + xss_match_tuples {
          + text_transformation = "URL_DECODE"

          + field_to_match {
              + data = "none"
              + type = "QUERY_STRING"
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

```
terraform init
terraform apply
terraform plan
```

**Comment by marisveide** [comment]
This bug kinda defies the whole notion of "plan" - because for the infra with some only 8 servers, on every change, everything shows as changed, because of those `-> null` line endings.
Totally impossible to spot what's actually being changed.

Anybody have any ideas how to fix this, please? 🙏

**Comment by anGie44** [comment]
Hi @vobarian @marisveide! I'm able to reproduce this but I do see a viable work-around given the state's `field_to_match` `data` value is causing the diff. It looks like the WAF API only requires and returns this field when `type` is set `HEADER` or `SINGLE_QUERY_ARG`.  So to address this, in your configuration you can omit the `data` field completely and the diff should no longer appear when running a `plan` after `apply`.

Hope this helps and if you still seem to come across this behavior, please let me know :)
