### ISSUE TITLE
resource/aws_appsync_datasource: Add support for "RelationalDatabase"

### ISSUE THREAD

**Issue by stack72** [hashicorp/terraform-provider-aws#8870]
As well as LambdaConfig, ElasticsearchConfig etc, the AWS API also has support for `RelationalDatabaseConfig`. This allows us to add the following type of config block:

```
{
  "relationalDatabaseSourceType": "RDS_HTTP_ENDPOINT",
  "rdsHttpEndpointConfig": {
    "awsRegion": "string",
    "dbClusterIdentifier": "string",
    "databaseName": "string",
    "schema": "string",
    "awsSecretStoreArn": "string"
  }
}
```

**Comment by boreview** [comment]
Hi, any updates on this? Urgently needed. Thank you

**Comment by reapz** [comment]
It would be useful to have this available at the same time as being able to enable the Data API in serverless aws_rds_cluster resources. See https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/59

**Comment by BerndWessels** [comment]
+1

**Comment by boreview** [comment]
+1!

**Comment by awsiv** [comment]
@reapz added option to enable Data API in serverless aws_rds_cluster resources here:

https://github.com/terraform-providers/terraform-provider-aws/pull/11048

**Comment by AlexEshoo** [comment]
+1, This would be very helpful!

**Comment by xai1983kbu** [comment]
+1

**Comment by bojovicivan** [comment]
Hi, any updates on this?

**Comment by BWhitfield** [comment]
+1

**Comment by Petterhg** [comment]
How is this one going? It's really a "hole" in the template that the RDS datasource is not supported.

**Comment by DCAL12** [comment]
+1

**Comment by byron-hom** [comment]
+1

**Comment by GmsDeveloper04** [comment]
+1

**Comment by econtentmaps** [comment]
+1

**Comment by econtentmaps** [comment]
wow. nearly three years.
