### ISSUE TITLE
Include jsonencode in IAM policy documentation

### ISSUE THREAD

**Issue by pauldraper** [hashicorp/terraform-provider-aws#8979]
https://www.terraform.io/docs/providers/aws/guides/iam-policy-documents.html#choosing-a-configuration-method

> The recommended approach to building AWS IAM policy documents within Terraform is the highly customizable aws_iam_policy_document data source.

> Otherwise in simple cases, such as a statically defined assume role policy for an IAM role, Terraform's multiple line heredoc syntax allows the easiest formatting without any indirection of a separate data source configuration or file.

> Additional methods are available, such single line string syntax, the file() interpolation function, and the template_file data source, however their usage is discouraged due to their complexity.

This omits what I consider to be a good (perhaps even best) method: `jsonencode`.

Native:

```hcl
data "aws_iam_policy_document" "example" {
  statement {
    actions   = ["*"]
    resources = ["*"]
    principals {
      identifiers = ["*"]
      type = "*"
    }
  }
}

resource "aws_iam_policy" "example" {
  name = "example"
  policy = data.aws_iam_policy_document.example.json
}
```

jsonencode:

```tf
resource "aws_iam_policy" "example" {
  name = "example"
  policy = jsonencode({
    Statement = [
      {
        Actions = "*"
        Effect = "Allow"
        Principal = "*"
        Resource = "*"
      },
    ]
    Version = "2012-10-17"
  })
}
```

It quite nice compared to single line string, file(), and template_file. And due to its cohesiveness, familiarity, and low learning curve to users of IAM, it *might* even be preferred to aws_iam_policy_document, though it lacks Terraform-level validation.

(Moreover, this approach works with other JSON inputs, like aws_ecs_task_definition.container_definitions)

**Comment by bflad** [comment]
Hi @pauldraper 👋 Thanks for calling this out. This guide certainly needs updates to include Terraform 0.12 features like [`jsonencode()`](https://www.terraform.io/docs/configuration/functions/jsonencode.html) and [`templatefile()`](https://www.terraform.io/docs/configuration/functions/templatefile.html)!

The team here at HashiCorp isn't focused on this particular update at the moment, but we would happily review a pull request against this repository's version of that guide at: https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/guides/iam-policy-documents.html.md Thanks!

**Comment by pauldraper** [comment]
TIL about templatefile.

**Comment by bflad** [comment]
The IAM Policy guide was moved over to the HashiCorp Learn platform at some point since this issue was created and now lives here: https://learn.hashicorp.com/tutorials/terraform/aws-iam-policy?in=terraform/aws

To provide feedback to the team that manages the content now, please use the feedback links at the bottom of the guide.
