### ISSUE TITLE
Tech Debt: Remove `provider "aws"` blocks from non provider_test.go files 

### ISSUE THREAD

**Issue by ryndaniels** [hashicorp/terraform-provider-aws#8983]
## Description

Provider configurations should be handled outside of individual test configurations. Having the provider configured in individual tests can lead to unexpected behavior when multiple configurations overlap or conflict with each other. This also allows the tests to be AWS Region and Partition agnostic.

## Test Updates

Existing tests should be updated to remove any hardcoded `provider "aws" {...}` blocks from individual test configurations.

## Linting

Going forward, a linter rule such as [AT004](https://github.com/bflad/tfproviderlint/blob/master/passes/AT004/README.md) could be added to prevent these from being added in the future.

## Definition of Done
* In `GNUmakefile`, add -`AT004` to `tfproviderlint` command under `lint` target and have TravisCI testing pass

## Issues:
- [ ] data_source_aws_cur_report_definition_test.go:63:21
- [ ] data_source_aws_eip_test.go:221:57
- [ ] data_source_aws_instance_test.go:779:21
- [ ] provider_test.go:1593:54
- [ ] resource_aws_cur_report_definition_test.go:108:21
- [ ] resource_aws_default_security_group_test.go:169:54
- [ ] resource_aws_eip_association_test.go:410:51
- [ ] resource_aws_eip_test.go:697:41
- [ ] resource_aws_elasticache_security_group_test.go:143:60
- [ ] resource_aws_instance_test.go:3386:21
- [ ] resource_aws_instance_test.go:3810:46
- [ ] resource_aws_lightsail_domain_test.go:131:21
- [ ] resource_aws_opsworks_stack_test.go:226:21
- [ ] resource_aws_opsworks_stack_test.go:312:21
- [ ] resource_aws_opsworks_stack_test.go:721:21
- [ ] resource_aws_opsworks_stack_test.go:988:21

**Comment by YakDriver** [comment]
#14216
