### ISSUE TITLE
Support for instant fleet type

### ISSUE THREAD

**Issue by bg2132332** [hashicorp/terraform-provider-aws#9007]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for AWS instant fleet type.  We need a fleet where instances provision synchronously, i.e. terraform waits for all instances to come up or fails should there be any errors.  

### New or Affected Resource(s)

* aws_ec2_fleet

### Potential Terraform Configuration

```hcl

resource "aws_ec2_fleet" "example" {
  type="instant"
  ....
}
```

### References

See https://aws.amazon.com/about-aws/whats-new/2018/11/synchronously-provision-instances-with-amazon-ec2-fleet/.

**Comment by ewbankkit** [comment]
Instance fleets can now be deleted: https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-ec2-fleet-now-supports-deleting-instant-type-fleets/.

**Comment by ewbankkit** [comment]
@dkheyman Please open a new issue referencing this one. Thanks.

**Comment by dkheyman** [comment]
Already did: #28830. Thanks,DavidOn Jan 11, 2023, at 4:23 PM, Kit Ewbank ***@***.***> wrote:﻿
@dkheyman Please open a new issue referencing this one. Thanks.
