### ISSUE TITLE
DeletionPolicy Attribute - Retain

### ISSUE THREAD

**Issue by ozbillwang** [hashicorp/terraform-provider-aws#902]
Hi there,

### Terraform Version
all 

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_s3_bucket, s3 is a sample, this feature should be applied to most resources.
-  [meta-parameters: lifecycle](https://www.terraform.io/docs/configuration/resources.html#lifecycle) 

Terraform lifecycle has three attributes: create_before_destroy, prevent_destroy, ignore_changes, but doesn't support attribute `retain` which AWS CFN supported.

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html

### Terraform Configuration Files
```hcl
resource "aws_s3_bucket" {
   ...
   lifecycle {
     retain = true|false
   }
}
```

### Expected Behavior
Need `retain` option works as in AWS Cloudformation. Related document is at http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html

>To keep a resource when its stack is deleted, specify `Retain` for that resource. `You can use retain for any resource`. For example, you can retain a nested stack, S3 bucket, or EC2 instance so that you can continue to use or modify those resources after you delete their stacks.

### Actual Behavior
No this option

**Comment by dreznick** [comment]
Do we know when this going to be available?

**Comment by fricanojohnb** [comment]
This is a pretty important thing to have in TF, especially for teams working with extensive data resources. Are there any updates here or is anyone specifically working on adding this yet? This has been stale for almost two years now.

**Comment by malachantrio** [comment]
We would very much love this option as well. At the moment we are having to fudge our ci/cd deploy machines permissions so that we remove the ability for terraform to delete certain resources

**Comment by saieva** [comment]
Supporting a retain lifecycle would be useful. This might also apply to AWS Elastic IP resources that are used to access services over the Public Internet.

**Comment by sethbacon** [comment]
Long-lived databases seem like another good area for this. RDS instances, DynamoDB tables, etc. VPCs might be another resource that is long-lived in some environments and would warrant the Retain support.

**Comment by bennettp123** [comment]
This would be useful for our deployment process. It mostly uses terraform, but it also uploads our javascript bundles to S3 with immutable filenames, which are eventually cleaned up by S3 lifecycle policies. We currently need to fall back to the aws-cli, otherwise terraform deletes previous versions which are gone from the local filesystem.

**Comment by ewbankkit** [comment]
Closing this Issue in this repository.
The requirements have been captured in various internal HashiCorp repository issues dealing with new Terraform lifecycle behaviors.
