### ISSUE TITLE
Unable to provide different Tag for Root and EBS device

### ISSUE THREAD

**Issue by kundan123456** [hashicorp/terraform-provider-aws#9033]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Headline
**How do we achieve different tags for root and ebs device under same resource aws_instance ?**
### Terraform Version
Terraform v0.12.1
provider.aws v2.14.0

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

```hcl
resource "aws_vpc" "vpc_01" {
  cidr_block           = "10.0.0.0/16"
  instance_tenancy     = "default"
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = {
    Name = "Project-vpc-01"
  }
}

resource "aws_subnet" "subnet" {
  vpc_id                  = "${aws_vpc.vpc_01.id}"
  cidr_block              = "10.0.1.0/24"
  map_public_ip_on_launch = true
  availability_zone       = "us-east-2a"
  tags = {
    Name = "Project-sn-01"
  }
}

resource "aws_security_group" "sg_all" {
  name   = "sg-01"
  vpc_id = "${aws_vpc.vpc_01.id}"
  tags = {
    Name = "Project-sg-01"
  }
}

resource "aws_instance" "my-instance" {
  count                  = "2"
  ami                    = "ami-00c79db59589996b9"
  instance_type          = "c5.large"
  subnet_id              = "${aws_subnet.subnet.id}"
  vpc_security_group_ids = "${aws_security_group.sg_all.id}"
  monitoring             = true

  root_block_device {
    volume_size           = "8"
    volume_type           = "gp2"
    delete_on_termination = false
  }
  ebs_block_device {
    volume_size           = "8"
    volume_type           = "gp2"
    delete_on_termination = false
    encrypted 		  = true
  }
  tags = {
    Name = "Instance-01"
  }
  volume_tags = {
    Name = "Volume-01"
  }
}
```

### Expected Behavior

What I want is to have two different tags for root and ebs device. But volume_tag is giving same tag to both devices.

Something like this:

Root Device Tag: Volume-01-Root
EBS Device Tag: Volume-01-Data
### Actual Behavior

It is creating same volume tag for both devices.
### Steps to Reproduce

1. `terraform plan`
2.  `terraform apply`

### References

* #0000

**Comment by kundan123456** [comment]
@bflad Any updates on the above issue ?

**Comment by biohazd** [comment]
I'm also seeing this issue.

**Comment by cringham** [comment]
@kundan123456 Have you tried breaking out additional volumes that aren't root from the `aws_instance` resource block? You can declare them with [`aws_ebs_volume`](https://www.terraform.io/docs/providers/aws/r/ebs_volume.html) and attach them with [`aws_volume_attachment`](https://www.terraform.io/docs/providers/aws/r/volume_attachment.html). The resulting code would look something like:

```hcl
resource "aws_vpc" "vpc_01" {
  cidr_block           = "10.0.0.0/16"
  instance_tenancy     = "default"
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = {
    Name = "Project-vpc-01"
  }
}

resource "aws_subnet" "subnet" {
  vpc_id                  = "${aws_vpc.vpc_01.id}"
  cidr_block              = "10.0.1.0/24"
  map_public_ip_on_launch = true
  availability_zone       = "us-east-2a"
  tags = {
    Name = "Project-sn-01"
  }
}

resource "aws_security_group" "sg_all" {
  name   = "sg-01"
  vpc_id = "${aws_vpc.vpc_01.id}"
  tags = {
    Name = "Project-sg-01"
  }
}

resource "aws_instance" "my-instance" {
  count                  = "2"
  ami                    = "ami-00c79db59589996b9"
  instance_type          = "c5.large"
  subnet_id              = "${aws_subnet.subnet.id}"
  vpc_security_group_ids = "${aws_security_group.sg_all.id}"
  monitoring             = true

  root_block_device {
    volume_size           = "8"
    volume_type           = "gp2"
    delete_on_termination = false
  }

  # Removed EBS block here

  tags = {
    Name = "Instance-01"
  }
  volume_tags = {
    Name = "Volume-01"
  }
}

# Added this
resource "aws_ebs_volume" "secondary" {
  availability_zone = "us-east-2a"
  size              = 8
  type              = "gp2"
  encrypted         = true

  tags = {
    Name = "Volume-02"
  }
}

# Added this
resource "aws_volume_attachment" "vol_2" {
  device_name = "/dev/sdh" # or something
  volume_id   = aws_ebs_volume.secondary.id
  instance_id = aws_instance.my-instance.id
}
```

**Comment by FearlessHyena** [comment]
@cringham Thanks for the workaround. While that would work having a separate tags block in the *_block_device as proposed in #4017 would be a much cleaner and preferred solution

**Comment by artkrz** [comment]
@FearlessHyena I have it separate and I do see the same issue.

**Comment by YakDriver** [comment]
We have merged a fix to the `volume_tags` issue. We have added tests to cover the issues observed. Please note that using `volume_tags` in `aws_instance` is _not_ compatible with using `tags` in `aws_ebs_volume`. You need to use one or the other. Prior to this fix, even following this rule, you would encounter errors. Along with the fix, we've added `tags` to the `root_block_device` and `ebs_block_device` configuration blocks in `aws_instance`.

Now that the fix is in place, if you find any problems with `volume_tags`, let us know by [opening a new issue](https://github.com/hashicorp/terraform-provider-aws/issues/new/choose).
