### ISSUE TITLE
Add method settings parameters to aws_api_gateway_stage

### ISSUE THREAD

**Issue by gokuatkai** [hashicorp/terraform-provider-aws#9047]
Hi,
When using `aws_api_gateway_stage` it should be giventhe possibility to set stage default method settings - see methodSettings in the following aws cli call
```
aws apigateway get-stages --rest-api-id XXXXXX
{
    "item": [
        {
            "deploymentId": "XXXXXX",
            "stageName": "prod",
            "cacheClusterEnabled": false,
            "cacheClusterSize": "0.5",
            "cacheClusterStatus": "NOT_AVAILABLE",
            "methodSettings": {
                "*/*": {
                    "metricsEnabled": false,
                    "dataTraceEnabled": false,
                    "throttlingBurstLimit": 5000,
                    "throttlingRateLimit": 10000.0,
                    "cachingEnabled": false,
                    "cacheTtlInSeconds": 300,
                    "cacheDataEncrypted": false,
                    "requireAuthorizationForCacheControl": true,
                    "unauthorizedCacheControlHeaderStrategy": "SUCCEED_WITH_RESPONSE_HEADER"
                }
            },
            "tracingEnabled": false,
            "createdDate": 1536758440,
            "lastUpdatedDate": 1560873092
        }
    ]
}

```

**Comment by DrFaust92** [comment]
Hey @gokuatkai, i believe this can achieve with `api_gateway_method_settings` resource

**Comment by elijah-roberts** [comment]
Perhaps this should be changed to a request for update in documentation. I too came in search of the ability to set default method settings for an api gateway stage deployment. 

According to: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_method_settings

method_path - (Required) Method path defined as {resource_path}/{http_method} for an individual method override, or */* for overriding all methods in the stage.

Possibly this should be documented here: 

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_stage

with either a note, or an example of setting default settings for a stage. 

This would be useful as both the AWS CLI, and cloudformation stage resources indicate that this can be set via a stage setting: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-stage.html#cfn-apigateway-stage-methodsettings
