### ISSUE TITLE
ebs_block_device with encrypted=true does not creat an EC2 instance

### ISSUE THREAD

**Issue by janitha09** [hashicorp/terraform-provider-aws#9059]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

PS C:\Users\Janitha Jayaweera\Documents\Source\janitha_config\terraform_play> terraform -v
2019/06/19 12:53:12 [INFO] Terraform version: 0.12.2
2019/06/19 12:53:12 [INFO] Go runtime version: go1.12.4
2019/06/19 12:53:12 [INFO] CLI args: []string{"C:\\ProgramData\\chocolatey\\lib\\terraform\\tools\\terraform.exe", "-v"}
2019/06/19 12:53:12 [DEBUG] Attempting to open CLI config file: C:\Users\Janitha Jayaweera\AppData\Roaming\terraform.rc
2019/06/19 12:53:12 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/06/19 12:53:12 [INFO] CLI command args: []string{"version", "-v"}
Terraform v0.12.2
2019/06/19 12:53:12 [DEBUG] checking for provider in "."
2019/06/19 12:53:12 [DEBUG] checking for provider in "C:\\ProgramData\\chocolatey\\lib\\terraform\\tools"
2019/06/19 12:53:12 [DEBUG] checking for provider in ".terraform\\plugins\\windows_amd64"
2019/06/19 12:53:12 [DEBUG] found provider "terraform-provider-aws_v2.15.0_x4.exe"
2019/06/19 12:53:12 [DEBUG] found valid plugin: "aws", "2.15.0", "C:\\Users\\Janitha Jayaweera\\Documents\\Source\\janitha_config\\terraform_play\\.terraform\\plugins\\windows_amd64\\terraform-provider-aws_v2.15.0_x4.exe"
+ provider.aws v2.15.0
### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
provider "aws" {
  region = "us-west-2"
}
resource "aws_instance" "instance" {
  ami                         = "ami-005bdb005fb00e791" #"ami-0c55b159cbfafe1f0"
  associate_public_ip_address = false
  instance_type               = "t2.micro"
  key_name                    = "janitha.jayaweera"
  monitoring                  = true
  provider                    = "aws"

  vpc_security_group_ids = ["sg-4453434343"]
  subnet_id = "subnet-545373737272"

  root_block_device {
    delete_on_termination = "true"
    volume_size           = 8
    volume_type           = "standard"
  }

  ebs_block_device {
    device_name           = "/dev/sdb"
    volume_type           = "gp2"
    volume_size           = 8
    delete_on_termination = true
    encrypted             = true
  }
  
  tags = {
    Name = "Terraform-Janitha"
  }
}

output "id" {
  value = aws_instance.instance.*.id
}

output "private_ip" {
  value = aws_instance.instance.*.private_ip
}
```

### Debug Output

https://gist.github.com/janitha09/7e6c57c4e8052514e973c3fdefe10dfe
### Expected Behavior

An EC2 instance should have been created with an encrypted mount

### Actual Behavior

when    encrypted             = true the error above occurs when it is false the ami is created

ubuntu@ip-10-63-133-74:~$ lsblk
NAME    MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
xvda    202:0    0   8G  0 disk
└─xvda1 202:1    0   8G  0 part /
xvdb    202:16   0   8G  0 disk

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by prakashjha08** [comment]
Hi Janitha,

Instead of pasting the aws_ebs_volume block inside resource "aws_instance", create and attach new EBS volume with the following code:


resource "aws_ebs_volume" "NewVolume" {
    availability_zone = "${aws_instance.ec2-terminal-server.availability_zone}"  ##This will create EBS volume in the same availability zone as the EC2 that is being created##

    size              = "${var.sapmntzel}"  ##Size has been defined in variable##

    tags {
        "Name" =  "${var.ebs_sapmntzel_tags_name}"
        
    }
    encrypted = true
    kms_key_id = "${aws_kms_key.KMS.arn}"  ##Encrypting with a customer managed Key in AWS##
}
resource "aws_volume_attachment" "NewVolumeAttachment" {
      device_name = "/dev/sdb"
      volume_id   = "${aws_ebs_volume.NewVolume.id}"
      instance_id = "${aws_instance.ec2-terminal-server.id}"
    }


Please revert in case of any queries. Thanks.
