### ISSUE TITLE
transit_gateway_default_route_table_association and transit_gateway_default_route_table_propagation always change for ec2_transit_gateway_vpc_attachment

### ISSUE THREAD

**Issue by eangeeag** [hashicorp/terraform-provider-aws#9070]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.10
+ provider.aws v2.6.0
```

### Affected Resource(s)

`aws_ec2_transit_gateway_vpc_attachment`

### Terraform Configuration Files

```hcl
data "aws_ec2_transit_gateway" "tgw" {
  id = "${var.transit_gateway_id}"
}

resource "aws_ec2_transit_gateway_vpc_attachment" "staging" {
  vpc_id                                          = "${var.vpc_id}"
  subnet_ids                                      = ["${var.subnet_ids}"]
  transit_gateway_id                              = "${data.aws_ec2_transit_gateway.tgw.id}"
  transit_gateway_default_route_table_association = false
  transit_gateway_default_route_table_propagation = false
  dns_support                                     = "${var.dns_support}"

  tags = "${merge(var.tags, map("Name", format("%s-tgw-vpc-attachment-%s", var.project, var.environment)))}"
}
```
### Expected Behavior

After applied the first time, no changes should appear in the plan

### Actual Behavior

`terraform plan` always shows the following 

```
  ~ update in-place

Terraform will perform the following actions:

  ~ module.transit_gateway_attachment.aws_ec2_transit_gateway_vpc_attachment.staging
      transit_gateway_default_route_table_association: "true" => "false"
      transit_gateway_default_route_table_propagation: "true" => "false"
```

### Steps to Reproduce
`terraform plan -out tplan`
`terraform apply tplan`
`terraform plan -out tplan`

### Important Factoids

TGW belongs to a different account and is shared via AWS Resource Access Manager.

**Comment by ewbankkit** [comment]
@eangeeag If your are importing on the accepter's side then you should use the [`aws_ec2_transit_gateway_vpc_attachment_accepter`](https://www.terraform.io/docs/providers/aws/r/ec2_transit_gateway_vpc_attachment_accepter.html) resource.

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/8383
* https://github.com/terraform-providers/terraform-provider-aws/issues/8600
