### ISSUE TITLE
Can't import Transit Gateway attachment

### ISSUE THREAD

**Issue by sethbacon** [hashicorp/terraform-provider-aws#9074]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14
+ provider.aws v2.16.0

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-east-1"
  profile = "navCore"
}

terraform {
  backend "atlas" {
    name = "NavicoCloudTeam/navCore-use1-inf-prd-networking"
    address = "https://app.terraform.io"
  }
}

resource "aws_ec2_transit_gateway_vpc_attachment" "tg_attach_egeno_vpn_use1" {}
```

### Expected Behavior

transit gateway attachment import successful

### Actual Behavior

Error: aws_ec2_transit_gateway_vpc_attachment.tg_attach_egeno_vpn_use1 (import id: tgw-attach-12345678901234567): 1 error occurred:
        * import aws_ec2_transit_gateway_vpc_attachment.tg_attach_egeno_vpn_use1 result: tgw-attach-12345678901234567: import aws_ec2_transit_gateway_vpc_attachment.tg_attach_egeno_vpn_use1 (id: tgw-attach-12345678901234567): Terraform detected a resource with this ID doesn't
exist. Please verify the ID is correct. You cannot import non-existent
resources using Terraform import.

### Steps to Reproduce

1. `terraform import aws_ec2_transit_gateway_vpc_attachment.tg_attach_egeno_vpn_use1 tgw-attach-12345678901234567`

### References

* #0000

**Comment by ewbankkit** [comment]
@sethbacon Is this an EC2 Transit Gateway VPC Attachment? If so then try using the [`aws_ec2_transit_gateway_vpc_attachment_accepter`](https://www.terraform.io/docs/providers/aws/r/ec2_transit_gateway_vpc_attachment_accepter.html) resource.
