### ISSUE TITLE
Codedeploy: CreateDeploymentGroup/aws_codedeploy_deployment_group API doc incorrect.

### ISSUE THREAD

**Issue by russmac** [hashicorp/terraform-provider-aws#9124]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.13
+ provider.aws v2.16.0

### Affected Resource(s)
aws_codedeploy_deployment_group

AWS API documentation incorrectly claims LoadBalancerInfo is an optional parameter (and its associated data types) . Support has informed me its required and non load balancer ECS code deploy deployments are not supported.

```
* aws_codedeploy_deployment_group.REDACTED: InvalidLoadBalancerInfoException: For ECS deployment group, loadBalancerInfo must be specified
	status code: 400, request id: REDACTED
```

The AWS documentation is very confusing on the subject and only mentions it in one or two places, While all the configurable params for an IN_PLACE deployment only refer to the container port and container name. This combined with the incorrect API doc is very confusing and misleads the user to thinking for example worker nodes can be deployed using a codedeploy module.

The doc modification I've made so far does not adequately describe the configuration requirements, Ill work on it when I can or happy to hear improvements/comments.

https://github.com/russmac/terraform-provider-aws/commit/5a1ad4a10b773f3c126fdb162ceb53984a6d114a

### References
https://docs.aws.amazon.com/codedeploy/latest/APIReference/API_DeploymentGroupInfo.html
https://docs.aws.amazon.com/codedeploy/latest/APIReference/API_LoadBalancerInfo.html
https://docs.aws.amazon.com/codedeploy/latest/APIReference/API_CreateDeploymentGroup.html#CodeDeploy-CreateDeploymentGroup-request-loadBalancerInfo

**Comment by bearfact** [comment]
👍
