### ISSUE TITLE
Feature request: aws_cognito_user_pool_clients data source

### ISSUE THREAD

**Issue by Stretch96** [hashicorp/terraform-provider-aws#9139]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It's currently not possible to get the `aws_cognito_user_pool_client` id unless it is launched via terraform (`aws_cognito_user_pool_client.example.id`)

Currently only the `aws_cognito_user_pools ` data source exists, which only gives the ids of the pools

### New or Affected Resource(s)

* data.aws_cognito_user_pool_clients

### Potential Terraform Configuration

```hcl
data "aws_cognito_user_pool_clients" "selected" {
  pool_name = "example"
  # or
  pool_id = "${data.aws_cognito_user_pools.example.ids[0]}"
}
```

**Comment by bflad** [comment]
Hi @Stretch96 👋 To clarify your use case here, are you looking for a "singular" data source, e.g. `aws_cognito_user_pool_client` that returns a single result, or a "plural" data source, e.g. `aws_cognito_user_pool_clients` that returns multiple results? The issue title is singular while the example configuration is plural. Thanks!

**Comment by Stretch96** [comment]
Hi @bflad yup I'll change the title to plural 😬

**Comment by oscarmorasu** [comment]
I currently have this requirement and got around by using an [external data source](https://www.terraform.io/docs/providers/external/data_source.html) to call the aws cli [list-user-pool-clients method](https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/list-user-pool-clients.html), which feels very hacky to me.

I am open to contribute with the community and implement this feature. Where can I start?

**Comment by teshd** [comment]
:+1:

**Comment by miran248** [comment]
Any news?

**Comment by lmmattr** [comment]
I'm eager for this one. My use case is that I have my UI project that will create the app client in Cognito, but I need to reference the client id when I set the audience for the API gateway authorizer. Currently I have to work around this by using remote state.

**Comment by shide1989** [comment]
Hope this one can be achieved soon, 
it would solve many Cognito Lambda trigger cycle dependency issues

**Comment by soostdijck** [comment]
Another use case where this is needed is when using AWS elasticsearch and enabling cognito authetication on it. 

The Elastic cluster configures it's own "app" inside your cognito user pool to handle logins. After ES resource creation I need to get the generated "app client id" so I can do role mappings inside `aws_cognito_identity_pool_roles_attachment`.

**Comment by adam-j-turner** [comment]
@soostdijck @awuetz Here is a workaround for the lack of data source, for use with cognito & elasticsearch:

Create an external data source that runs a bash script. Use `query` to supply the script with parameters. `profile` and/or `region` may not be necessary depending on how/where you're running terraform.

I put a dependency on the elasticsearch domain to ensure it waits until the entirety of the cognito integration is complete.
```
data "external" "ess_cognito_client" {
  working_dir = path.module

  program = [
    "bash", "scripts/your-script-name.sh"
  ]

  query = {
    profile = "terraform",
    region = data.aws_region.current.name,
    user_pool_id = var.ess_cognito_user_pool_id,
    es_domain = aws_elasticsearch_domain.main.domain_name
  }

  depends_on = [
    aws_elasticsearch_domain.main
  ]
}
```

Shell script to obtain the client information and return it in JSON format. `jq` needs to be available wherever you're running terraform.
```
#!/bin/bash
set -e

eval "$(jq -r '@sh "profile=\(.profile) region=\(.region) user_pool_id=\(.user_pool_id) es_domain=\(.es_domain)"')"

aws cognito-idp list-user-pool-clients \
    --user-pool-id $user_pool_id --profile $profile --region $region |jq -cr \
    ".UserPoolClients[] | select(.ClientName | contains(\"AWSElasticsearch-${es_domain}\"))"
```

Usage of the external data source (just need to reference `result.ClientId`) within your `aws_cognito_identity_pool_roles_attachment`.
```
  role_mapping {
    identity_provider = "cognito-idp.<region>.amazonaws.com/${var.ess_cognito_user_pool_id}:${data.external.ess_cognito_client.result.ClientId}"
```

Lastly, ensure you're not allowing terraform to overwrite the changes the Elasticsearch Service makes to the identity pool on your behalf (on your `aws_cognito_identity_pool` resource).
```
  lifecycle {
    ignore_changes = [
      allow_unauthenticated_identities,
      cognito_identity_providers
    ]
  }
```

**Comment by danquack** [comment]
I opened a PR to provide the client ids as a data source output.
