### ISSUE TITLE
Error creating SES configuration set: ConfigurationSetAlreadyExists: Configuration set <ses-verify-email-identity-config-set> already exists.

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#9186]
Hi,

I am getting the error below when I execute a aws_ses_configuration_set resource. The resource does not exist prior to me creating it. AWS shows the resource existing after the script stops. When I delete the configuration set manually from AWS and rerun the script, I get the same result.

Error occurred:
Error: Error creating SES configuration set: ConfigurationSetAlreadyExists: Configuration set <ses-verify-email-identity-config-set> already exists.
        status code: 400, request id: 8b484c22-5c36-44ed-bd21-2215a2bc7716

  on ../ses/main.tf line 1, in resource "aws_ses_configuration_set" "ses_verify_email_identity_configuration_set":
   1: resource "aws_ses_configuration_set" "ses_verify_email_identity_configuration_set" {

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
 v0.12.3

```hcl
resource "aws_ses_configuration_set" "ses_verify_email_identity_configuration_set" {
  name = "ses-verify-email-identity-config-set"
}

resource "aws_ses_event_destination" "ses" {
  name                   = "ses-verify-email-identity-destination-sns"
  configuration_set_name = "${aws_ses_configuration_set.ses_verify_email_identity_configuration_set.name}"
  enabled                = true
  matching_types         = ["bounce", "send", "reject", "complaint", "delivery", "open", "click", "renderingFailure"]

  sns_destination {
    topic_arn = "${var.sns_verify_email_identity_topic_arn}"
  }
}
```

**Comment by escanzanocloudcath** [comment]
I also get this error when I changed the resource name.

Error: Provider produced inconsistent result after apply

When applying changes to
module.ses.aws_ses_configuration_set.ses_verify_email_identity_config_set,
provider "aws" produced an unexpected new value for was present, but now
absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
