### ISSUE TITLE
Not able to launch global RDS with existing snapshot

### ISSUE THREAD

**Issue by encryptblockr** [hashicorp/terraform-provider-aws#9210]
there is issue with launching global RDS when `snapshot_identifier` is added to create from a snapshot. I used same code to launch global RDS without launching from existing snapshot nd runs fine but when i had existing snapshot, it complains in the second region and unable to launch the stack.

VERSIONS:
`Terraform v0.11.7` 
`provider.aws: version = "~> 2.15"`

**Comment by aeschright** [comment]
Hi @encryptblockr, I'm sorry to hear you ran into this issue. Before we can look at it, we need a few more details. You can follow the outline in our [bug reporting form](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md). In particular, we'll need to see the configuration file and debugging output.

If you're looking for more general support, have a look at the community forum: https://discuss.hashicorp.com/c/terraform-providers/tf-aws
Folks there may be able to help you figure out what's going on. Thanks!

**Comment by encryptblockr** [comment]
@aeschright 
I think this is a bug except if you feel otherwise

there is an issue as soon as you try to bring up the global database loaded with an existing snapshot.
I can add all the required info but first can you confirm that terraform is expected to be able to load a global RDS database fine even with existing snapshot? If you can answer YES to that then 

i will go ahead and add as much info as i can

but pretty much error i get is it starts asking me to add parameters like databse name and user and password for the second region which i dont need to add since second region is secondary database but this error happens when i specify existing snapshot to load from

and that is where the error is...which is why i said this is a bug
