### ISSUE TITLE
AWS Network Interface Output IP not match

### ISSUE THREAD

**Issue by garyjuano** [hashicorp/terraform-provider-aws#9277]
I noticed weird output behavior using `aws_network_interface` output

Here's my sample code below

> resource "aws_network_interface" "testinterface" {
>   subnet_id ="subnet-xxxx"
>   private_ips_count = 2
>   tags = {
>     Name = "testing-only"
>   }
> }
> 
> output "private_ips" {
>   value = "${aws_network_interface.testinterface.private_ips}"
> }

**Actual Output:**
private_ips = [
  "10.0.1.1",
  "10.0.1.2",
  "10.0.1.3",
]
Above output is correct

But when i changes the `private_ips_count = 1` and run `terraform apply` command again. It still showing the previous output IP.

**Actual Output:**
private_ips = [
  "10.0.1.1",
  "10.0.1.2",
  "10.0.1.3",
]

**My expected** should something like this(2 ips):
private_ips = [
  "10.0.1.1",
  "10.0.1.2",
]

Thanks,

**Comment by buec011** [comment]
Same issue if you increase private_ips_count.

If you run `terraform apply` again the output is updated.

It looks like 
`aws_network_interface.testinterface.private_ip` is not refreshed after `private_ips_count` has been changed.

And in `terraform plan` the following output may be useful, add (known after apply) to private_ips
```
      ~ private_ips       = [
            "10.18.82.30",
            "(known after apply)",
            (known after apply)
        ]
      ~ private_ips_count = 0 -> 2
        security_groups   = [
            "sg-08bcca43e47808c18",
        ]
```

Today with terraform 0.12.3 and aws provider 2.21:
```
       private_ips       = [
            "10.18.82.30",
        ]
      ~ private_ips_count = 0 -> 2
        security_groups   = [
            "sg-08bcca43e47808c18",
        ]
```

**Comment by cpalmer9** [comment]
Seeing same issue with Terraform v0.12.17 and provider.aws v2.41.0.
Basically, if you change the `private_ips_count` value on an existing `aws_network_interface`, it doesn't get refreshed for the apply and any variables that depend on that value are therefore incorrect. The ENI does get modified in AWS, it's just that Terraform doesn't seem to reflect that.

**Comment by bflad** [comment]
To properly trigger the `private_ips` attribute to show as unknown (and therefore expected to have reference updates) when the `private_ips_count` argument is updated, a `CustomizeDiff` function can be added to the `aws_network_interface` resource using [`customdiff.ComputedIf()`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff?tab=doc#ComputedIf), e.g.

```go
		CustomizeDiff: customdiff.Sequence(
			customdiff.ComputedIf("private_ips", func(_ context.Context, diff *schema.ResourceDiff, meta interface{}) bool {
				return diff.HasChange("private_ips_count")
			}),
		),
```

For acceptance testing this functionality, the `TestAccAWSENI_PrivateIpsCount` test steps can be updated to check the state `private_ips.#` value for updated amounts.

**Comment by rick-masters** [comment]
@bflad
Thanks for pointing out `ComputedIf`! I was really stuck without it but didn't know it until I stumbled upon your comment.

Most unfortunately, because the names `private_ips` and `private_ips_count` overlap, the SDK mistakenly deletes the pending change to `private_ips_count`. See https://github.com/hashicorp/terraform-plugin-sdk/issues/715 just filed. That bug causes this example and pretty much only this example to fail (i.e `private_ips_count` has no effect). That's bad luck man.🤪
