### ISSUE TITLE
aws_iam_policy_document times out with empty principal list

### ISSUE THREAD

**Issue by TimOrme** [hashicorp/terraform-provider-aws#9346]
Terraform no longer allows an empty principal list in a aws_iam_policy_document.  Instead, it seems to cause a timeout, though it appears that its trying to validate the principals in some way. 

We frequently leveraged this functionality in modules that wrap a policy, so ideally this would continue to work as it used to.  If there are hard reasons for enforcing this though, it would be great if this gave a more informative error.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform Version 0.11.10
AWS Provider Version 2.14.0
```

### Affected Resource(s)

* aws_iam_policy_document

### Terraform Configuration Files

```hcl
data "aws_iam_policy_document" "bucket_policy" {
  statement {
    sid  = "Sample Statement"
    effect = "Allow"
    actions = ["s3:GetObject"]
    resources = [
      "${aws_s3_bucket.bucket_to_add.arn}",
      "${aws_s3_bucket.bucket_to_add.arn}/*"
    ]
    principals {
      identifiers = ["${var.read_users}"]
      type = "AWS"
    }
  }
}

variable "read_users" {
  description = "List of users with read-only access"
  type = "list"
  default = []
}
```

### Debug Output

Simplified output

```module.mybucket.aws_s3_bucket_policy.bucket_policy: Still modifying... (ID: bucket-us-east-1, 10s elapsed)
module.mybucket.aws_s3_bucket_policy.bucket_policy: Still modifying... (ID: bucket-us-east-1, 20s elapsed)
module.mybucket.aws_s3_bucket_policy.bucket_policy: Still modifying... (ID: bucket-us-east-1, 30s elapsed)
module.mybucket.aws_s3_bucket_policy.bucket_policy: Still modifying... (ID: bucket-us-east-1, 40s elapsed)
module.mybucket.aws_s3_bucket_policy.bucket_policy: Still modifying... (ID: bucket-us-east-1, 50s elapsed)
module.mybucket.aws_s3_bucket_policy.bucket_policy: Still modifying... (ID: bucket-us-east-1, 1m0s elapsed)
module.mybucket.aws_s3_bucket_policy.bucket_policy: Still modifying... (ID: bucket-us-east-1, 1m10s elapsed)
module.mybucket.aws_s3_bucket_policy.bucket_policy: Still modifying... (ID: bucket-us-east-1, 1m20s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* module.mybucket.aws_s3_bucket_policy.bucket_policy: 1 error(s) occurred:

* aws_s3_bucket_policy.bucket_policy: Error putting S3 policy: timeout while waiting for state to become 'success' (timeout: 1m0s)
```

### Expected Behavior

Terraform creates a policy with an empty list of principals.

### Actual Behavior

In the previous versions of the provider (1.59.0) this went through just fine, but after upgrading to 2.14.0, the apply step hangs and eventually times out.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Code sample and debug output have been manually simplified to give this example.

**Comment by nywilken** [comment]
hi @TimOrme sorry you are running into trouble here. The issue actually looks to be related to the attachment of the generated policy and not the `aws_iam_policy_document ` data source which generates the policy as expected. Do you have a sample of the policy document that is trying to be applied, and maybe a sample of the log where the error is occurring?

In trying to reproduce this error using the provided configuration to attach a policy to a bucket I am getting 500 errors from the backend AWS API which would essentially timeout. It would be good to know what you mean by it was working with 1.59.0 (what the policy document looks like, what is the policy that is getting applied) vs the current state which is throwing an error. 

Thanks!

**Comment by dimaqq** [comment]
Here's an example:
```
  statement {
    sid = "S3ListBucketForCloudFront"
    principals {
      type = "AWS"
      identifiers = []
    }
    actions   = ["s3:ListBucket"]
    resources = ["arn:aws:s3:::${module.cdn.s3_bucket}"]
  }
```
