### ISSUE TITLE
[DataSource] aws_ec2_client_vpn_endpoint

### ISSUE THREAD

**Issue by digitalkaoz** [hashicorp/terraform-provider-aws#9443]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

add the corresponding `aws_ec2_client_vpn_endpoint` datasource for [aws_ec2_client_vpn_endpoint](https://www.terraform.io/docs/providers/aws/r/ec2_client_vpn_endpoint.html)

### New or Affected Resource(s)

* data.aws_ec2_client_vpn_endpoint

### Potential Terraform Configuration

```hcl
data "aws_ec2_client_vpn_endpoint" "example" {
  filter {
    name   = "tag:XXX"
    values = ["YYY"]
  }  
}

resource "aws_ec2_client_vpn_network_association" "example" {
  client_vpn_endpoint_id = data.aws_ec2_client_vpn_endpoint.id
  subnet_id              = var.subnet_id
}
```

**Comment by donsamiro** [comment]
push!!!

**Comment by angelabad** [comment]
Please, react with a :+1: in the pull request.

**Comment by angelabad** [comment]
@bflad could you take a look at this issue/pr?

Thanks
