### ISSUE TITLE
aws_cognito_user_pool support for dynamic blocks

### ISSUE THREAD

**Issue by stdeniss** [hashicorp/terraform-provider-aws#9454]
Hi,

Been looking around and I think I am trying this the correct way.
I am trying to use dynamic blocks under the aws_cognito_user_pool resource type to generate multiple schemas passed in as a list.

configuration Details:
-----------------------------
Terraform v0.12.5
+ provider.aws v2.20.0
+ provider.template v2.1.2

provider "aws" {
  region  = "ca-central-1"
  version = "2.20.0"
}

main.tf:
----------------
  schemas = [
    {
    schema_attribute_data_type = "String"
    schema_name = "test"
    schema_required = true
    schema_min_length = "0"
    schema_max_length = "2048"
    },
    {
      schema_attribute_data_type = "String"
      schema_name = "test2"
      schema_required = true
      schema_min_length = "0"
      schema_max_length = "2048"
    }
  ]

modules/cognito_user_pool/main.tf:
----------------------------------------------
  dynamic "iter" {

    for_each = var.schemas
    content {
      schema {
        attribute_data_type = iter.value.schema_attribute_data_type
        name = iter.value.schema_name
        developer_only_attribute = false
        mutable = true

        string_attribute_constraints {
          min_length = iter.value.schema_min_length
          max_length = iter.value.schema_max_length
        }
      }
    }
  }

terraform plan output:
-------------------------
C:\Dev\Terraform\eserv-infr-tr\infrastructure\environment\sbx>terraform plan

Error: Unsupported block type

  on ..\..\..\..\eserv-infr-common\modules\cognito_user_pool\main.tf line 178, in resource "aws_cognito_user_pool" "pool":
 178:   dynamic "iter" {

Blocks of type "iter" are not expected here.

**Comment by Sluggerman** [comment]
Try this:

```
variable "schema_attrs" {
  type        = list(map(string))
  description = "Schema attributes of a user pool"
  default = [
    {
      name = "attribute1"
      type = "String"
    },
    {
      name = "attribute2"
      type = "String"
    }
  ]
}

resource "aws_cognito_user_pool" "user_pool" {
  name = "user_pool"
  ...
  dynamic "schema" {
	for_each = var.schema_attrs
	content {
           name                     = schema.value["name"]
           attribute_data_type      = schema.value["type"]
           developer_only_attribute = false
           mutable                  = true
           required                 = false
           string_attribute_constraints {
              min_length = 1
             max_length = 256
           }
       }
   }
}
```

**Comment by DrFaust92** [comment]
Closing for lack for response
