### ISSUE TITLE
Proposal: Add support Object-level logging in the existing trail for resource 'aws_s3_bucket'

### ISSUE THREAD

**Issue by Ventals** [hashicorp/terraform-provider-aws#9459]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi! I know only one approach for enabling Object-level logging on S3 bucket via terraform - create new `aws_cloudtrail` and setup `data_source`, but in some moment it's unusable(because **we have only 5 trails per region and this limit we can't increase**)

**Maybe the best way for resolving it - add some flag for write Object-level logs to the existing trail?**

### New or Affected Resource(s)

* aws_s3_bucket

### Potential Terraform Configuration

We can add **`object_level_logging`** object supports the following fields:
**`target_trail` - takes arn existing trail**
**`events` - type of event, string value Read or Write**
```hcl
resource "aws_s3_bucket" "b" {
  bucket = "my-tf-test-bucket"
  acl    = "private"

  object_level_logging {
    target_trail = "arn:aws:cloudtrail:region:account-id:trail/trailname"
    events = "Read/Write"
  }
}
```

### References

* https://github.com/terraform-providers/terraform-provider-aws/issues/3425 - The first issue about this, for solving problem offered to create a new trail, not existing

**Comment by monkov** [comment]
Good job! thx, it's solved my problem.

**Comment by caebozzini** [comment]
Hello, was this issue solved? We need to point to an existing Cloudtrail on new S3 buckets, is there any good and elegant way to do it in pure Terraform? Thank you.

**Comment by akson012** [comment]
Same issue here.

**Comment by UdhavPawar** [comment]
Facing exact same issue. Terraform tries to create as many cloud trails as number of S3 buckets, thus overall operation fails as it passes the AWS account hard-limit of 5 cloud trails per account.

**Comment by AlexandreDemailly** [comment]
Same here !
Any clue ?

**Comment by doribd** [comment]
Any solution expected in the coming release of 14 ?
