### ISSUE TITLE
static_routes_only attribute in aws_vpn_connection flips on every plan

### ISSUE THREAD

**Issue by jpsecher** [hashicorp/terraform-provider-aws#9475]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

* terraform: 0.11.14
* aws: 2.20.0

(We are in the process of upgrading to 0.12, so 0.11.14 is a step in that process.)

### Affected Resource(s)

* aws_vpn_connection

### Terraform Configuration Files

```hcl
resource "aws_vpn_connection" "main" {
  vpn_gateway_id = "${aws_vpn_gateway.vpn_gateway.id}"
  customer_gateway_id = "${data.terraform_remote_state.env-test.customer-gateway-id}"
  type = "ipsec.1"
  static_routes_only = true
}
```

### Expected Behavior

`terraform plan` should show indicate no change.

### Actual Behavior

`terraform plan` gives
```
-/+ aws_vpn_connection.main (new resource required)
      ...
      static_routes_only:             "false" => "true" (forces new resource)
      ...

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce

Of course the change of `static_routes_only` could be a result of someone changing `static_routes_only` manually.  But if I change the configuration to match, as in:

```hcl
resource "aws_vpn_connection" "main" {
  vpn_gateway_id = "${aws_vpn_gateway.vpn_gateway.id}"
  customer_gateway_id = "${data.terraform_remote_state.env-test.customer-gateway-id}"
  type = "ipsec.1"
  static_routes_only = false
}
```

then `terraform plan` shows the opposite change:
```
-/+ aws_vpn_connection.main (new resource required)
      ...
      static_routes_only:             "true" => "false" (forces new resource)
      ...

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Important Factoids

The problem does not happen with aws provider version 1.60.0.

## Temporary workaround

Adding a lifecycle block with ignore_changes for `static_routes_only` fixes the problem.

```hcl
resource "aws_vpn_connection" "main" {
  ...
  lifecycle {
    ignore_changes = "static_routes_only"
  }
}
```

* #0000

**Comment by BenjyOC** [comment]
+1 Same issue !
