### ISSUE TITLE
Error: if ipv6 DNS resolver fails it does fall back to ipv4. Or it does not work properly

### ISSUE THREAD

**Issue by northbear** [hashicorp/terraform-provider-aws#9504]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
% terraform -v
Terraform v0.12.4
+ provider.aws v2.19.0
```

### Affected Resource(s)

I'm trying to make terraform plan and get error message: 
```
% terraform plan 
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


Error: error validating provider credentials: error calling sts:GetCallerIdentity: RequestError: send request failed
caused by: Post https://sts.amazonaws.com/: dial tcp: lookup sts.amazonaws.com on [::1]:53: read udp [::1]:58140->[::1]:53: read: connection refused

  on variables.tf line 1, in provider "aws":
   1: provider "aws" {
```

### Terraform Configuration Files

It's basic. You can use any config from any tutorial. They cause the same issue after successful ```terraform configure```.

### Expected Behavior

I'd supposed that using ipv4 stack is default. Using IPv6 should be activated by configuration setting. Or fallback to ipv4 should work properly in ipv6 fails.

### Actual Behavior

It looks like it use both ipv4 and ipv6 with priority to ipv6 but it DNS requests for ipv6 fails it does not try fallback to ipv4.   

### Steps to Reproduce

Probably it will be enough to configure ipv6 for using in local network

**Comment by jjjjeeffff** [comment]
I had this issue on OS X because I had no `/etc/resolv.conf` (still figuring out why). Doing a `sudo ln -s /var/run/resolv.conf /private/etc/resolv.conf` solved it for me.

**Comment by northbear** [comment]
Thanks a lot @aeschright! I confirm that presence of ```/etc/resolv.conf``` solves the issue. 
Any way It would be good idea to check up similar cases and provide more clear error message.

**Comment by aeons** [comment]
I have this issue on Arch Linux. I have disabled IPv6 entirely, but this still happens.

**Comment by justinretzolk** [comment]
Hey y'all 👋 Thanks for taking the time to open this issue, and for the additional discussion around it! It looks like this came down to a local system configuration. As such, we'll close this issue out.
