### ISSUE TITLE
WS was not able to validate the provided access credentials 	status code: 401

### ISSUE THREAD

**Issue by akeva22** [hashicorp/terraform-provider-aws#9597]
I created this same script under the same credentials and keypair and a few hours later they did not work. I tried adding a new access creds but same result. 

**Configuration Removed for security reasons** 

Error retrieving KeyPair: AuthFailure: AWS was not able to validate the provided access credentials
	status code: 401, request id: d7e9c3a4-779c-402f-ab51-bec82f901d0c

**Comment by nywilken** [comment]
@akeva22 sorry that you are running into trouble here. Before trying to understand what is happening here I recommend you deactivate the AWS credentials shared in your sample configuration. You may also want to delete the file from S3. As it is safe to assume that your keys been comprised; GitHub issues are public for all to see. 

Hard-coding credentials into any Terraform configuration is not recommended. Please see https://www.terraform.io/docs/providers/aws/index.html#authentication for information on how to provide AWS credentials in a more secure manner.

For future reference when posting confígs within an issue please make sure they are stripped of any sensitive information. Also note that the contents of a state file should never be posted as they can contain sensitive information as well. 

Security concerns aside I see that you are specifying 
```
skip_credentials_validation = true
  skip_requesting_account_id = true
```

Those arguments are not needed when working with a standard AWS environment. 

Have you tried to access AWS via the CLI with a fresh set of access keys?

https://aws.amazon.com/cli/


If you can authenticate via the CLI please try your new AWS Access keys without specifying  the two skip arguments.

**Comment by nywilken** [comment]
I went ahead and removed the configuration you uploaded in the issue to prevent further distribution of the file. Please rotate your keys before continuing with any Terraform related testing.

**Comment by akeva22** [comment]
Hi, I gave all those suggestions a try. I have since deleted the "compromised"  keys and created new ones. Tested with the AWS CLI and confirmed they work. Then replaced in my .tf config file without skip arguments. 

Still getting the same result and error code.

**Comment by virendramarathelinux** [comment]
hello all 
this issue is related to access which you have given to access key and secret key, if you give full access to your access key and secret key its work.

**Comment by rishavmehra** [comment]
hey, 
I'm facing the same error
