### ISSUE TITLE
Terraform appears to be hanging while performing 25 attempts due to 403 error (MFA)

### ISSUE THREAD

**Issue by amirabiri** [hashicorp/terraform-provider-aws#9601]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.12.6
+ provider.aws v2.21.1
```

### Debug Output

[tf-debug.log](https://github.com/terraform-providers/terraform-provider-aws/files/3460410/tf-debug.log)

(Removed potentially sensitive bits from the log and replaced with `**SNIPPED**`).

### Expected Behavior

Terraform should exit immediately and report a 403, as it does with other 403-related errors.

### Actual Behavior

Terraform appears to hang while performing 25 retries each resulting in a 403 due to the MFA token having expired.

### Steps to Reproduce

1. Perform login to AWS with MFA
2. Wait for MFA token to expire
3. `terraform apply`

### Important Factoids

Using MFA from the CLI (Google Authenticator, aws cli session token).

**Comment by YakDriver** [comment]
This is closed by events. See hashicorp/aws-sdk-go-base#362 for more details.
