### ISSUE TITLE
aws_codebuild_source_credential docs

### ISSUE THREAD

**Issue by zygimantas** [hashicorp/terraform-provider-aws#9613]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forum](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

Could you please provide a better documentation for `aws_codebuild_source_credential` because it's not clear how it works and how it is related to aws_codebuild_project and aws_codebuild_webbook.

aws_codebuild_project requires OAUTH auth type, while aws_codebuild_source_credential does not support OAUTH, webhook fails to be created.

Thank you.

**Comment by andrewfraley** [comment]
Does anyone know how to use aws_codebuild_source_credential with aws_codebuild_project?  I want to switch from using Github OAUTH to a personal access token, but it's not clear how to use aws_codebuild_source_credential in the aws_codebuild_project resource block.

**Comment by andrewfraley** [comment]
After further experimentation, it seems that if I declare aws_codebuild_source_credential, then any Codebuild project defined within the same module will use it.

**Comment by zygimantas** [comment]
@andrewfraley Does webhook work for you and have you disconnected from GitHub in AWS portal?

**Comment by brogers-navex** [comment]
I'm also experiencing difficulties here. The documentation is absolutely terrible in describing how this resource is used.

Currently trying to set up a webhook and this is blocking me.

**Comment by nfisher** [comment]
Docs could use some love for sure. 

Looking at the schema referenced below there are only two types of authentication supported:

1. `BASIC_AUTH`
2. `PERSONAL_ACCESS_TOKEN `

https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_codebuild_source_credential.go#L23-L58

Most of the applicable constants are defined in the AWS SDK:
https://github.com/aws/aws-sdk-go/blob/master/service/codebuild/api.go

**Comment by pharindoko** [comment]
Recognized the same behaviour.
Credentials will be used per account and not per codebuild project.
And I did not find a way to link it to the codebuild project...

**Comment by albertorm95** [comment]
This is how to use it:

https://github.com/hashicorp/terraform-provider-aws/issues/7435#issuecomment-534115342

**Comment by garybaines** [comment]
As per documentation (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codebuild_project) the auth block is deprecated and `no longer accurate or used`, so #7435 can't be the way it should be used.

`
source: auth
resource - (Optional, Deprecated) Resource value that applies to the specified authorization type. Use the aws_codebuild_source_credential resource instead.`
`type - (Required, Deprecated) Authorization type to use. The only valid value is OAUTH. This data type is deprecated and is no longer accurate or used. Use the aws_codebuild_source_credential resource instead.`

**Comment by eugene-komar-bmll** [comment]
I just realised how it works, maybe it will be helpful for someone. 

> Note: CodeBuild only allows a single credential for GitHub to be saved in a given AWS account in a given region - any attempt to add more than one will result in an error.

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codebuild.GitHubSourceCredentials.html

Thats why it does not connects with `aws_codebuild_project` resource explicitly

**Comment by pharindoko** [comment]
> I just realised how it works, maybe it will be helpful for someone. 
> 
> 
> 
> > Note: CodeBuild only allows a single credential for GitHub to be saved in a given AWS account in a given region - any attempt to add more than one will result in an error.
> 
> 
> 
> https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-codebuild.GitHubSourceCredentials.html
> 
> 
> 
> Thats why it does not connects with `aws_codebuild_project` resource explicitly 

Same thing I stated above but that's a real problem. We figured out that this can lead to the issue that credentials or a token codebuild relies on for authentication might not be there anymore. Then you get an unauthorized when you start a pipeline ...

**Comment by teru01** [comment]
I was faced with the same confusion, so will try to enhance docs.
