### ISSUE TITLE
can't make tools - missing tfproviderlint tool URL

### ISSUE THREAD

**Issue by james-martin-engineer** [hashicorp/terraform-provider-aws#9624]
The terraform GNUmakefile supplied with this repo references github.com/bflad/tfproviderlint/cmd/tfproviderlint as a tool dependency, however github.com/bflad/tfproviderlint/cmd/tfproviderlint delivers a 404 error.

Could this please be corrected so that we can validate if the current terraform-provider-aws is actually compatible with the AWS API presently?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.12.6

### Affected Resource(s)
terraform-provider-aws providers

* aws_ALL.

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Panic Output

GO111MODULE=on go install github.com/bflad/tfproviderlint/cmd/tfproviderlint
can't load package: package github.com/bflad/tfproviderlint/cmd/tfproviderlint: cannot find package "github.com/bflad/tfproviderlint/cmd/tfproviderlint" in any of:
        /usr/lib/golang/src/github.com/bflad/tfproviderlint/cmd/tfproviderlint (from $GOROOT)
        /root/go/src/github.com/bflad/tfproviderlint/cmd/tfproviderlint (from $GOPATH)
make: *** [tools] Error 1

### Expected Behavior

make tools should have succeeded

### Actual Behavior
failed due to invalid dependencies in GNUmakefile

### Steps to Reproduce
1. obtain the latest clone of the terraform-provider-aws repo, 
2. run make tools from the repo folder

### References

* #0000

**Comment by gh-mlfowler** [comment]
I'm not getting 404 but rather a checksum mismatch:

```$ make tools
GO111MODULE=on go install github.com/bflad/tfproviderlint/cmd/tfproviderlint
go: finding github.com/bflad/tfproviderlint v0.4.0
go: downloading github.com/bflad/tfproviderlint v0.4.0
go: verifying github.com/bflad/tfproviderlint@v0.4.0: checksum mismatch
        downloaded: h1:bmY47+b1uofPmD2OzKp4OoyGOiWz+t2v/TJ5vAJ29uE=
        go.sum:     h1:Pu6ascgpZKUPk0ZYx8scf658K2jJbxT1A/zCfdZamt0=
GNUmakefile:59: recipe for target 'tools' failed
make: *** [tools] Error 1
```

**Comment by gh-mlfowler** [comment]
Just re-read the requirements which states Go version 1.12, I was running 1.11. With 1.12 `make tools` completes for me.

**Comment by pbartruff** [comment]
Ubuntu did me in too!  Default Go version was 1.10.  Installed 1.12 following https://github.com/golang/go/wiki/Ubuntu.  `make tools` started to go, but then died with hashicorp/terraform#22664  

😞

**Comment by breathingdust** [comment]
Closing this looks to have been a go version issue.
