### ISSUE TITLE
Capacity-optimized allocation strategy for Amazon EC2 Spot Instances

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#9750]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

New capacity-optimized allocation strategy for EC2 Auto Scaling and EC2 Fleet.

### New or Affected Resource(s)

* [`aws_autoscaling_group`](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html)
* [`aws_ec2_fleet`](https://www.terraform.io/docs/providers/aws/r/ec2_fleet.html)
* [`aws_spot_fleet_request`](https://www.terraform.io/docs/providers/aws/r/spot_fleet_request.html)

### Potential Terraform Configuration

```hcl
resource "aws_autoscaling_group" "example" {
  mixed_instances_policy {
    instances_distribution {
      spot_allocation_strategy = "capacity-optimized"
    }
  }
}

resource "aws_ec2_fleet" "example" {
  spot_option {
    allocation_strategy = "capacityOptimized"
  }
}

resource "aws_spot_fleet_request" "example" {
  allocation_strategy = "capacityOptimized"
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/08/new-capacity-optimized-allocation-strategy-for-provisioning-amazon-ec2-spot-instances/).
[Blog post](https://aws.amazon.com/blogs/compute/introducing-the-capacity-optimized-allocation-strategy-for-amazon-ec2-spot-instances/).

* EC2 Auto Scaling support added in [AWS SDK v1.22.4](https://github.com/aws/aws-sdk-go/releases/tag/v1.22.4); Requires https://github.com/terraform-providers/terraform-provider-aws/pull/9670
* EC2 Fleet support added in [AWS SDK v1.21.10](https://github.com/aws/aws-sdk-go/releases/tag/v1.21.10)

**Comment by ruecarlo** [comment]
In the interim,  I've tried `capacity-optimized` in ASG and seems to be working well (no changes required).

From what I've checked so far there are differences in the implementation. [EC2 Fleet](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_ec2_fleet.go#L167),  [Spot Fleet](https://github.com/terraform-providers/terraform-provider-aws/blob/e94f7f0ce09b3f39675faa71e896c685accc5295/aws/resource_aws_spot_fleet_request.go#L300) and [Auto Scaling Groups](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_autoscaling_group.go#L126) take slightly different approach. 

Auto Scaling Groups, just pass the allocation strategy string through and does not validate the schema. For anyone applying it to an existing ASG config, bear in mind that `spot_instance_pools` is not compatible with `capacity-optimized` ([link](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_InstancesDistribution.html) to documentation), meaning you will need to remove the `spot_instance_pools` section to make `capacity-optimized` to work.

For EC2 Spot fleet, as I expected after checking [the code](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_ec2_fleet.go#L167), I got a validation error. Changes will be required to support it. 

```
Error: expected spot_options.0.allocation_strategy to be one of [diversified lowestPrice], got capacityOptimized

  on ec2_fleet.tf line 22, in resource "aws_ec2_fleet" "aws_fleet_example":
  22: resource "aws_ec2_fleet" "aws_fleet_example" {
```

I haven't had a chance yet to test [Spot Fleet](https://github.com/terraform-providers/terraform-provider-aws/blob/e94f7f0ce09b3f39675faa71e896c685accc5295/aws/resource_aws_spot_fleet_request.go#L300), but my understanding is that there is no validation, just a pass-through the allocation strategy, so for as long as the `instance_pools_to_use_count ` is not provided, my guess it it should work.

**Comment by cablespaghetti** [comment]
For other people finding this. The instances_distribution block for my Autoscaling Group looks like this now:
```
     instances_distribution {
       on_demand_percentage_above_base_capacity = 0
      spot_instance_pools = 0
      spot_allocation_strategy = "capacity-optimized"
     }
```

**Comment by scalp42** [comment]
It doesn't seem to work for us @cablespaghetti:

```hcl
  mixed_instances_policy {
    instances_distribution {
      spot_allocation_strategy                 = "capacity-optimized"
      on_demand_base_capacity                  = 0
      on_demand_percentage_above_base_capacity = 0
      spot_instance_pools                      = 20
    }
```

```
Error: Error updating Autoscaling group: ValidationError: SpotInstancePools option is only available with the lowest-price allocation strategy.
	status code: 400, request id: 59dc8e04-f1b5-49a1-8068-9445d86b09f6

  on prod1_fabio.tf line 255, in resource "aws_autoscaling_group" "prod1_fabio_mixed":
 255: resource "aws_autoscaling_group" "prod1_fabio_mixed" {



Error: Error updating Autoscaling group: ValidationError: SpotInstancePools option is only available with the lowest-price allocation strategy.
	status code: 400, request id: 9d217439-1bbe-4a4a-9c06-2e253f5a624e

  on prod1_nomad_compute_m5_mixed.tf line 115, in resource "aws_autoscaling_group" "prod1_nomad_compute_m5_mixed":
 115: resource "aws_autoscaling_group" "prod1_nomad_compute_m5_mixed" {
```
