### ISSUE TITLE
AWS DataSync supports VPC Endpoints

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#9755]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

You can now deploy AWS DataSync within a VPC using VPC endpoints.

### New or Affected Resource(s)

* [`aws_datasync_agent`](https://www.terraform.io/docs/providers/aws/r/datasync_agent.html)

### Potential Terraform Configuration

```hcl
resource "aws_datasync_agent" "example" {
  security_group_arns = [
     "${aws_security_group.example.arn}",
  ]

  subnet_arns = [
    "${aws_subnet.example.arn}",
  ]

  vpc_endpoint_id = "${aws_vpc_endpoint.example.id}"
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/08/aws-datasync-now-supports-amazon-vpc-endpoints/).
[User guide](https://docs.aws.amazon.com/datasync/latest/userguide/datasync-in-vpc.html).

**Comment by m4ce** [comment]
Is there any plan to implement this in the near future? We are unable to deploy datasync agents since we rely on vpc endpoints.

**Comment by rmccarthy-ellevation** [comment]
Is this going to be implemented in the near future?
