### ISSUE TITLE
Changing aws_acm_certificate from Amazon-issued to existing doesn't force new resource

### ISSUE THREAD

**Issue by ineffyble** [hashicorp/terraform-provider-aws#9809]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Provider 2.24

### Affected Resource(s)

* aws_acm_certificate

### Expected Behavior

Adding `private_key` and `certificate_body` to an `aws_acm_certificate` should create a new self-managed certificate.

### Actual Behavior

It spent 1 and a half hours modifying the existing certificate before throwing an internal server error.

**Comment by sunil238174** [comment]
I faced similar issue when I tried updating my existing certificate in aws cert manager.Its not allowing update certificate.
* aws_acm_certificate.cert: Error updating certificate: ValidationException: com.amazonaws.pki.acm.exceptions.external.ValidationException: Could not validate the certificate with the certificate chain. 
    status code: 400, request id:
