### ISSUE TITLE
Terraform AWS Provider does not support CopyDBSnapshot

### ISSUE THREAD

**Issue by PedroRibeiro95** [hashicorp/terraform-provider-aws#9885]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform AWS Provider does not support the CopyDBSnapshot API call, which allows copying a manual snapshot of an RDS instance, either to the same region, to a different region or even to a different AWS account. 

This functionality can be of particular use in Terraform for a multitude of reasons, including disaster recovery plans with snapshots copied across multiple regions, launch of testing environments on different regions restoring from some database snapshot, among others.

### New or Affected Resource(s)

* aws_db_snapshot_copy

### Potential Terraform Configuration

```hcl
resource "aws_db_snapshot_copy" "test" {
  source_region                 = "<region where the snapshot is>"
  source_db_snapshot_identifier = "<snapshot ARN>"
  target_db_snapshot_identifier = "<name to give to the copied snapshot"
  kms_key_id                    = "<key to encrypt copy>"
}
```

### References

AWS API Call documentation: https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CopyDBSnapshot.html

AWS Go SDK documentation: https://godoc.org/github.com/aws/aws-sdk-go/service/rds#CopyDBSnapshot

**Comment by joaoantunes** [comment]
Hi any news about this subject? How can I copy a snapshot between regions? Only AWS Cli?

**Comment by SpComb** [comment]
This would be required when restoring an encrypted snapshot shared from a different AWS account.

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ShareSnapshot.html#USER_ShareSnapshot.Encrypted
> * Sharing an unencrypted manual DB snapshot enables authorized AWS accounts to directly restore a DB instance from the snapshot instead of taking a copy of it and restoring from that. However, you can't restore a DB instance from a DB snapshot that is both shared and encrypted. Instead, you can make a copy of the DB snapshot and restore the DB instance from the copy.
