### ISSUE TITLE
Role Attach Recently broken for aws_iam_policy_attach

### ISSUE THREAD

**Issue by bezilla** [hashicorp/terraform-provider-aws#9887]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_iam_policy_attachment

### Terraform Configuration Files

```hcl
resource "aws_iam_policy_attachment" "name-of-policy-attachment" {
    name       = "name-of-policy-attachment"
    policy_arn = "arn:aws:iam::accountnumber:policy/path/policy-name"
    groups     = []
    users      = []
    roles      = ["group1", "group2", "group3"]
}
```

### Debug Output

https://gist.github.com/bezilla/a635596e78a319518ecadc24c9ef94ac

### Expected Behavior

Expected behavior should attach all three roles. In this case none are found. Debug output states this is causing something wrong with the plan.

- NOTE: Rolling back to a previous version of the aws provider (2.24 or earlier) fixes the issue. 

### Steps to Reproduce

1. Use the 2.25 version of the provider
2. Use the `aws_iam_policy_attachment` module to apply one, or multiple roles with a `terraform apply`

### Important Factoids

In my testing I rolled all the way back to 2.7.  However, without additional insight it might be something that was recently introduced within the last couple weeks. The changes in the URL below show in both 2.7, all the way up to 2.24 (current at the time of this writing is 2.25)

### References

Compare URL from last two releases showing change introduced:
(started with 2.7 and tracked this change in module to current):

https://github.com/terraform-providers/terraform-provider-aws/compare/v2.24.0...v2.25.0

**Comment by brikis98** [comment]
Hitting the same issue consistently. Pinning to AWS provider 2.24 is a workaround.
