### ISSUE TITLE
EMR: many steps with large arguments cause grpc error: received message larger than max

### ISSUE THREAD

**Issue by rednuht** [hashicorp/terraform-provider-aws#9888]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.7

### Affected Resource(s)

* aws_emr_cluster

### Terraform Configuration Files

Not applicable.

### Debug Output

Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4760380 vs. 4194304)

### Expected Behavior

Terraform can manage an EMR cluster with many steps where the step argument is large.

### Actual Behavior

Terraform crashes due to grpc receiving a message larger than set max value. This is caused by the list steps api which returns all steps including their argument. If the argument is large, in our case a json string, and the number of totalt steps is also large, the return value is too big for grpc.

### Steps to Reproduce

1. Create an EMR cluster.
2. Add steps(500+) using aws cli or any other api with a large json argument each.
3. Perform a terraform plan

**Comment by nokernel** [comment]
Getting this error since a few years now. On clusters with alot of steps.

Would be nice to have an option to filter our the steps in tf plan/apply/destroy at the provider level.

**Comment by davidCarroll1421** [comment]
I am also seeing issues with this. I have long lived EMR clusters that cause this issue to come up when the number of steps reach a large amount. I am currently on Terraform 0.15.5 and provider 3.4.0. Without a fix for this I am unable to upgrade past this version of the provider. 

I have been looking into it and found that this problem might be resolved by filtering out "completed" steps from the step list, while preserving other relevant steps. From looking at the reason this feature was added this should preserve the functionality while reducing the size of the step list on long running EMR clusters. 

This can be accomplished by passing a filter condition to the ListSteps function in AWS. Wondering if this is possible and could be implemented. For reference, the code location for listing steps is here: https://github.com/hashicorp/terraform-provider-aws/blob/ac06ced75cba0daf09fef2938752ad13cc6fff6e/aws/resource_aws_emr_cluster.go#:~:text=var%20stepSummaries%20%5B%5D*emr,%7D)

**Comment by alexsanderp** [comment]
I have the same problem!
