### ISSUE TITLE
Add support for importing resource aws_s3_bucket_object

### ISSUE THREAD

**Issue by jvelonis** [hashicorp/terraform-provider-aws#9903]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Resource aws_s3_bucket_object doesn't support import (AWS provider version 2.25.0).  I use Terraform to provision some S3 folders and objects, and it would be useful to be able to import existing objects.

### New or Affected Resource(s)

* aws_s3_bucket_object

### Potential Terraform Configuration

```
terraform import aws_s3_bucket_object.foo my_bucket/path/to/foo
```

**Comment by dhdersch** [comment]
I'm interested in working on this. I'll submit a pull request when I have one ready.

**Comment by dhdersch** [comment]
I made a new pull request here. I'm new to this so bear with me :)

https://github.com/terraform-providers/terraform-provider-aws/pull/10036

**Comment by jskinne3** [comment]
Thank you! I'm in need of this functionality. I could use some help upgrading.

In my `provider` block I set `version = "3.52.0"` per the above documentation. When running `init` I get a warning that this method of specifying the version is deprecated, but it appears to work. However, when I attempt to `import` an `aws_s3_bucket_object` I get the following error:

```
Error: Could not load plugin
│ 
│ 
│ Plugin reinitialization required. Please run "terraform init".
│ 
│ Plugins are external binaries that Terraform uses to access and manipulate
│ resources. The configuration provided requires plugins which can't be
│ located,
│ don't satisfy the version constraints, or are otherwise incompatible.
│ 
│ Terraform automatically discovers provider requirements from your
│ configuration, including providers used in child modules. To see the
│ requirements and constraints, run "terraform providers".
│ 
│ failed to instantiate provider "registry.terraform.io/hashicorp/aws" to
│ obtain schema: there is no package for registry.terraform.io/hashicorp/aws
│ 3.52.0 cached in .terraform/providers
```
