### ISSUE TITLE
Support AWS IoT fleet indexing configuration

### ISSUE THREAD

**Issue by tkrullmann** [hashicorp/terraform-provider-aws#9928]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It should be possible to manage the IoT fleet indexing configuration using Terraform.

### New or Affected Resource(s)

* aws_iot_indexing_config

### Potential Terraform Configuration

```hcl
resource "aws_iot_indexing_config" "test" {
  thing_group_indexing_enabled = true
  thing_connectivity_indexing_enabled = true
  thing_indexing_mode = "REGISTRY_AND_SHADOW"
}
```

### References

* https://docs.aws.amazon.com/iot/latest/developerguide/managing-index.html

**Comment by drissamri** [comment]
Is there any suggested workaround besides combining terraform with AWS CLI's in a pipeline?
