### ISSUE TITLE
aws_s3_bucket_object chages cache_control on every run if its not provided

### ISSUE THREAD

**Issue by bostrowski13** [hashicorp/terraform-provider-aws#9935]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Seen on version 0.12.1+

AWS Provider 2.25.+

### Affected Resource(s)

aws_s3_bucket_object

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket_object" "object" {
  count                  = local.object_package
  bucket                 = aws_s3_bucket.packages.id
  key                    = local.s3_key
  source                 = local.source_path
  etag                   = filemd5(local.source_path)
  server_side_encryption = "AES256"
}
```

### Debug Output

Produced this in the initial plan...
```
  # module.package_management.aws_s3_bucket_object.object[0] will be created
  + resource "aws_s3_bucket_object" "object" {
      + acl                    = "private"
      + bucket                 = (known after apply)
      + content_type           = (known after apply)
      + etag                   = "12345678901234567890"
      + id                     = (known after apply)
      + key                    = "Example/Info/GetInfo/test.zip"
      + server_side_encryption = "AES256"
      + source                 = "src/test.zip"
      + storage_class          = (known after apply)
      + version_id             = (known after apply)
    }
```

All resources are created as defined in the plan.

Then, any subsequent plan (and apply) attempts to change the value of the cache_control from "proxy-revalidate" -> "null"

```
  # module.package_management.aws_s3_bucket_object.object[0] will be updated in-place
  ~ resource "aws_s3_bucket_object" "object" {
        acl                    = "private"
        bucket                 = "my-bucket"
      - cache_control          = "proxy-revalidate" -> null
        content_type           = "binary/octet-stream"
        etag                   = "12345678901234567890"
        id                     = "Example/Info/GetInfo/test.zip"
        key                    = "Example/Info/GetInfo/test.zip"
        metadata               = {}
        server_side_encryption = "AES256"
        source                 = "src/test.zip"
        storage_class          = "STANDARD"
        tags                   = {}
        version_id             = "00000000000000000000000000"
    }
```

Another apply sets this cache_control to "null" again, since I don't have it in my code.  But any subsequent run of a plan attempts to set this back to "null" from "proxy-revalidate".

So my question is, if cache_control is an optional paramter in the s3_buket_object resource, why is AWS enforcing (or changing it) to what might be a default value of "proxy-revalidate"?

Is this actually a required parameter?  Or is this something that changed in the API or a default on s3 buckets?  

### Expected Behavior

cache_control is a required parameter that has a default value of "proxy-revalidate" (or whatever the default is from AWS, if not this).

### Steps to Reproduce

1. `terraform apply`

**Comment by J0hnnieW4lker** [comment]
Is there any solutions for this problem? I have the same issue.

**Comment by J0hnnieW4lker** [comment]
Is there any solutions for this ploblem? I have the same issue.
- cache_control          = "proxy-revalidate" -> null
        id                        = "configure-system.sh"
        tags                    = {}
      +version_id          = (known after apply)
