### ISSUE TITLE
AWS Application Auto Scaling suspend/resume scaling

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/terraform-provider-aws#9945]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Application Auto Scaling actions can now be suspended or resumed.

### New or Affected Resource(s)

* [`aws_appautoscaling_target`](https://www.terraform.io/docs/providers/aws/r/appautoscaling_target.html)

### Potential Terraform Configuration

```hcl
resource "aws_appautoscaling_target" "example" {
  suspended_state {
    dynamic_scaling_out_suspended = true
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/08/suspend-resume-scaling-now-available-in-aws-application-auto-scaling/).
[API reference](https://docs.aws.amazon.com/autoscaling/application/APIReference/API_ScalableTarget.html#autoscaling-Type-ScalableTarget-SuspendedState).

**Comment by anagarjunr** [comment]
It has been a long time waiting for this issue.
Please consider this
