### ISSUE TITLE
Create Kinesis Firehose Delivery Stream using unsupported default value to China region

### ISSUE THREAD

**Issue by zcanva** [hashicorp/terraform-provider-aws#9983]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.12.6

### Affected Resource(s)

* aws_kinesis_firehose_delivery_stream

### Terraform Configuration Files

```hcl
resource "aws_kinesis_firehose_delivery_stream" "cloudwatch_logs_firehose_stream" {
  name = var.destination_name
  destination = "extended_s3"

  extended_s3_configuration {
    prefix = var.s3_prefix
    bucket_arn = var.bucket_arn
    role_arn = "arn:${data.aws_partition.current.partition}:iam::${data.aws_caller_identity.current.account_id}:role/firehose-s3-export"
    buffer_size = var.buffer_size
    buffer_interval = var.buffer_interval
    compression_format = "GZIP"
    cloudwatch_logging_options {
      enabled = true
      log_group_name = "/aws/kinesisfirehose/${var.destination_name}"
      log_stream_name = "S3Delivery"
    }
  }
}
```

### Debug Output

https://gist.github.com/zcanva/d1ac3d9b47ede1f023424256506b39cf

### Expected Behavior

Kinesis delivery stream should be created.

### Actual Behavior

Error because it sends "DataFormatConversionConfiguration":{"Enabled":false}  
even if it's not defined anywhere.

Error: error creating Kinesis Firehose Delivery Stream: InvalidArgumentException: Firehose record format conversion is not available in the current region.

### Steps to Reproduce

Create a kinesis delivery stream in China regions.

1. `terraform apply`

### Important Factoids

This particular account is in cn-north-1

### References

* #0000

**Comment by jgearheart** [comment]
This is still an issue in any region that doesn't support the data format conversion feature. I've been able to work around this issue for now by creating a custom aws provider/plugin and commenting out all the functions related to the data format conversion in the resource_aws_kinesis_firehose_delivery_stream.go file. https://www.terraform.io/docs/extend/writing-custom-providers.html

**Comment by bflad** [comment]
@jgearheart are you able to share additional information about what regions/partitions/services are also affected?

**Comment by jgearheart** [comment]
Sure. do you guys have a dedicated team for the public/gov sector?

**Comment by bflad** [comment]
@jgearheart HashiCorp itself does have dedicated teams within the Sales and Customer Success organizations for the public/US Government sectors. On the Engineering side though, we do not have access to environments like AWS C2S and SC2S for development/testing or a goto resource for that type of work. We would love to work with folks on a mutually beneficial solution to this problem.

**Comment by groodt** [comment]
We just ran into this issue as well for the Beijing region. I believe Beijing and Ningxia do not currently support record format conversion since it is missing from their docs. Is there anyway to move this issue forward?

**Comment by groodt** [comment]
I've worked around this issue with a custom build as well:
https://github.com/groodt/terraform-provider-aws/releases/tag/v2.45.0-unoffical

All I've done is comment it out as well, which is obviously not a real solution:
https://github.com/terraform-providers/terraform-provider-aws/compare/master...groodt:master

If somebody can give me some pointers, I'm happy to try work on a real fix. I think if we can detect Beijing and Ningxia regions, we can come up with a solution. Or we allow setting a `nil` value to avoid sending "DataFormatConversionConfiguration":{"Enabled":false}.

**Comment by groodt** [comment]
Update on this. Data Format Conversion is now available in the AWS China partition. I've switched back to the official provider and it works.

I believe this issue can be closed.

**Comment by brianvoss** [comment]
Same issue with the GovCloud (us-gov-west-1) partition
